### ISSUE TITLE
error in mean.var.plot

### ISSUE THREAD

**Issue by roryk** [satijalab/seurat#1]
Hi everyone,

I have an error when I run mean.var.plot:

```
nbt = mean.var.plot(nbt, y.cutoff=2, x.low.cutoff=2, fxn.x=expMean,  fxn.y=logVarDivMean)

Error in seq.int(rx[1L], rx[2L], length.out = nb) : 'to' must be finite
```

I stuck a link up on Dropbox to a nbt object that is causing the problem.

```
https://dl.dropboxusercontent.com/u/2822886/nbt.RData
```

I'm rubbish at debugging problems in S4 objects-- any ideas about what is wrong?

**Comment by roryk** [comment]
Figured out my issue. Thanks!

**Comment by carmensandoval** [comment]
HI Roryk,

I'm having the same problem... what solved it for you in the end?

**Comment by roryk** [comment]
Sorry @carmensandoval, I forget exactly what it was but it was some problem with my data though not the function. I think I had not logged the data before making the Seurat object.

**Comment by azimmunivar** [comment]
I'm also having an issue with this. Did anyone get to the bottom of it?

**Comment by roryk** [comment]
@azimmunivar I forgot to log the data which caused the issue. Did you do that?

**Comment by marong0511** [comment]
@roryk I am also having an issue with this. Did you deal with UMI data? I did normalize data before running this.
I found when I scaledata with a linear model (default setting), everything goes well. But when I used 'negbinom' model to deal with UMI data, it goes wrong in Findvariablegenes with the same error you mentioned before.

**Comment by lihong1github** [comment]
I found the solution to this issue. If you normalize the data first using the "NormalizeData" function as shown below, it will fix this error.

seurat.object <- NormalizeData(
  object = seurat.object,
  normalization.method = "LogNormalize",
  scale.factor = 10000)
