### ISSUE TITLE
Error in .Call("_Seurat_FastMatMult

### ISSUE THREAD

**Issue by gpmc55** [satijalab/seurat#100]
I am aligning two 10x Genomics data sets using Seurat v2.0.

Data is imported directly from the matrix.mtx file rather than a expressionMatrix.txt file.

However, when running the CCA I return the following error:

Error in .Call("_Seurat_FastMatMult", PACKAGE = "Seurat", m1, m2) : 
  negative length vectors are not allowed

Has anybody else encountered this error and is there a fix?

**Comment by andrewwbutler** [comment]
Haven't seen this one before. Can you provide the code you ran prior to the error?

**Comment by gpmc55** [comment]
Hi Andrew,

Thanks for the reply. The code is below along with a snapshot of values which shows that the steps prior to CCA analysis seem to be working. As mentioned above, I am working from a matrix.mtx file. 


> library(Seurat)
> library(cowplot)
> threeprime.data <- Read10X("Data/Elliott/3prime/GRCh38")
> fiveprime.data <- Read10X("Data/Elliott/5prime/GRCh38")
> threeprime <- CreateSeuratObject(raw.data = threeprime.data)
> threeprime <- NormalizeData(threeprime)
[1] "Performing log-normalization"
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
> threeprime <- ScaleData(threeprime)
[1] "Scaling data matrix"
  | =========================| 100%
> threeprime <- FindVariableGenes(threeprime, do.plot = F)
[1] "Calculating gene dispersion"
  |  =========================| 100%
> fiveprime <- CreateSeuratObject(raw.data = fiveprime.data)
> fiveprime <- NormalizeData(fiveprime)
[1] "Performing log-normalization"
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
> fiveprime <- ScaleData(fiveprime)
[1] "Scaling data matrix"
  | =======================| 100%
> fiveprime <- FindVariableGenes(fiveprime, do.plot = F)
[1] "Calculating gene dispersion"
  |   ==============================| 100%
> hvg.threeprime <- rownames(head(threeprime@hvg.info, 2000))
> hvg.fiveprime <- rownames(head(fiveprime@hvg.info, 2000))
> hvg.union <- union(hvg.threeprime, hvg.fiveprime)
> fiveprime@meta.data[, "protocol"] <- "5Prime"
> threeprime@meta.data[, "protocol"] <- "3Prime"
> pbmc <- RunCCA(fiveprime, threeprime, genes.use = hvg.union)
Running CCA
Error in .Call("_Seurat_FastMatMult", PACKAGE = "Seurat", m1, m2) : 
  negative length vectors are not allowed

![capture](https://user-images.githubusercontent.com/30477913/28678719-ee12a864-72a5-11e7-9179-1ad34dc5a0bd.PNG)

**Comment by gpmc55** [comment]
Sorry, accidentally closed the issue without resolving the problem

**Comment by andrewwbutler** [comment]
Trying to reproduce the error. I think you may be bumping up against some memory limits. How many cells do you have in fiveprime and threeprime?

**Comment by gpmc55** [comment]
Hi Andrew,

Both data sets contain ~1,000 cells. However, they were sequenced to ~2000,000 reads per cell and sequencing saturation was reach ~70,000 reads per cell. 

Will try other samples that have approximately the same number of cells but are sequenced to a lower-depth.

**Comment by andrewwbutler** [comment]
Your input matrices look way too large to be 1,000 cells each. Make sure they are the expression matrices (genes x cells).

**Comment by gpmc55** [comment]
Turns out I was using the raw barcode matrix and not the filtered barcode matrix. Everything is working fine now. Thank you for the help and the software package. Extremely useful tool to help analyze data on a deeper level.
