### ISSUE TITLE
VizDimReduction missing in Seurat 3 (but present in v3 tut)

### ISSUE THREAD

**Issue by jblachly** [satijalab/seurat#1002]
https://satijalab.org/seurat/pbmc3k_tutorial_v3.html includes a call to `VizDimReduction`, but this function does not appear to be in the latest 3.0 candidate.

sessionInfo shows:
`[1] Seurat_3.0.0.9000`

**Comment by QiangShiPKU** [comment]
replace it using `VizDimLoading`

**Comment by andrewwbutler** [comment]
The tutorial has been updated to reflect the change from `VizDimReduction` to `VizDimLoadings`.
