### ISSUE TITLE
a question about the names of the columns in a Seurat object

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#1007]
Dear all, 

please would you advise on the following : I am running Seurat on the dataset that was published in : 

https://www.ncbi.nlm.nih.gov/pubmed/27565351 

https://github.com/broadinstitute/BipolarCell2016

In the article, there are 6 datasets on BIPOLAR cells that are all together in a matrix, and the columns are labelled in the following way : 

Bipolar1_barcode1, ...., 
Bipolar1_barcodeXYZ, 
Bipolar2_barcode1, ...., 
Bipolar2_barcodeXYZ, 
Bipolar3_barcode1, ...., 
Bipolar4_barcodeXYZ, 
Bipolar4_barcode1, ...., 
Bipolar4_barcodeXYZ, 
Bipolar5_barcode1, ...., 
Bipolar5_barcodeXYZ, 
Bipolar6_barcode1, ...., 
Bipolar6_barcodeXYZ, 

Shall I understand that, when we would like to include multiple experiments in the same matrix, we just need to label the columns according to a scheme : ExperimentA_Barcode, ...., ExperimentX_Barcode ; 

thanks a lot, 

-- bogdan

**Comment by satijalab** [comment]
There is certainly no requirement to do so, but this is good practice and we find that naming convention useful in our own work
