### ISSUE TITLE
Differential expression / fold changes

### ISSUE THREAD

**Issue by ClaireG18** [satijalab/seurat#1008]
Hi,

I would be grateful if you could clarify the following:

does the function FindMarkers assume input data have been log normalized?
do you employ exp1m because log1p(x) is used within log normalization?
what is the suggested method to use when many genes have low mean expression (and thus average fold changes with pseudocount=1 tend to be small)? is Wilcoxon still ok?
Thank you,

Claire

**Comment by ClaireG18** [comment]
Hi,

I would be grateful if you could clarify the following:

- does the function FindMarkers assume input data have been log normalized?
- do you employ exp1m because log1p(x) is used within log normalization?
- what is the suggested method to use when many genes have low mean expression (and thus average fold changes with pseudocount=1 tend to be small)? is Wilcoxon still ok?

Thank you,

Claire

**Comment by satijalab** [comment]
In the calculation of fold-changes, we do assume log-normalization. The p-values do not assume this.

You are right that for very low mean expression genes, the pseudocount can dominate. In this case you can reduce the value of that parameter. However, the p-values will remain unchanged.
