### ISSUE TITLE
DoHeatmap() Seurat v3 - slot not found 

### ISSUE THREAD

**Issue by ramTT** [satijalab/seurat#1009]
Hi!

I'm using seurat V3 and would like to use DoHeatmap() on my cluster biomarkers. **When I run** 
```R
dat <- CreateSeuratObject(counts = filtered.counts) %>% NormalizeData() %>% 
FindVariableFeatures() %>%  ScaleData() %>% RunPCA() %>% FindNeighbors() %>% FindClusters() %>% RunTSNE()
my_markers <- FindAllMarkers(object = dat, only.pos = TRUE, min.pct = 0.25, logfc.threshold = log(2))
my_markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) -> top10
DoHeatmap(object = dat, features = top10$gene) + NoLegend()
```
**I get the following error:**
```R
Error in slot(., "scale.data") : 
  no slot of name "scale.data" for this object of class "Seurat"
```
**It seems as though two things:**
1. The slot scale.data do exist and can be accessed by running:
```R
dat %>% slot("assays") %>% extract2("RNA") %>% slot("scale.data")
```
The function argument 'slot' is by default 'scale.data', which does not exist as a "main" slot in the object, but as a subslot in 'assays'. Could this be the issue?

2. The 'group.by' argument takes 'ident' by default. This is not the issue for the error message I suppose, but in Seurat v3 this slot seems to be named 'active.ident' instead. What is your opinion? Should the default be 'active.ident' and updated accordingly? 

(all other functions and the object itself works fine, it just doesn't work with the DoHeatmap() function)

Thanks,
Best
R

**Comment by mojaveazure** [comment]
Hi @ramTT,

We have not built Seurat with support for the `%>%` pipe in mind. As such, we cannot say as to what's going wrong. What happens if you try running your workflow in the traditional manner?

```R
dat <- CreateSeuratObject(counts = filtered.counts)
dat <- NormalizeData(object = dat)
dat <- FindVariableFeatures(object = dat)
dat <- ScaleData(object = dat)
```
etc...

**Comment by ramTT** [comment]
Hi!

I understand. But I've used the pipe-operator successfully for the seurat-object throughout my analysis and it seems to be working just fine. 
**If I instead run the following:**

dat <- CreateSeuratObject(counts = filtered.counts)
dat <- NormalizeData(object = dat)
dat <- FindVariableFeatures(object = dat)
dat <- ScaleData(object = dat)
dat <- RunPCA(object=dat) 
dat <- FindNeighbors(object=dat)
dat <- FindClusters(object=dat) 
dat <- RunTSNE(object=dat)

my_markers <- FindAllMarkers(object = dat, only.pos = TRUE, min.pct = 0.25, logfc.threshold = log(2))
my_markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) -> top10
DoHeatmap(object = dat, features = top10$gene) + NoLegend()

**I get the following error:**
Error in GetAssayData(object = object, slot = slot)[default.vars, cells,  : 
  subscript out of bounds

So it seems as though, still, DoHeatmap() cannot find the slot/subset/data it's looking for? That's how I interpret the error message. Any thoughts? 
All other Seurat v3 functions incl. those for plotting have been working just fine...

Many thanks,
Best,
R

**Comment by mojaveazure** [comment]
Were you using the pipe with Seurat v2.X or v3? I'm guessing you've been able to use it with v2 since the error you got refers tot he old v2 object. With v3, the object is more complicated, and the pipe operator likely cannot handle it. It looks like not using the pipe solved your first error (`no slot of name "scale.data" for this object of class "Seurat"`)

For this `DoHeatmap` error, can you provide the output of `traceback`?

Also: for `group.by`, the name 'ident' is special in Seurat and will the identity classes. This is found in all functions that support `group.by` as well as `FetchData` (give it a try: `FetchData(object = dat, vars = 'ident')`). As such, the default should not be 'active.ident'.

**Comment by Sophia409** [comment]
I need to plot a set of genes (dynamically determined using program),when i use but when i try by using this code , it didn't work,can you help me and give me the right code?
my_gene_list <- list("Hoxa1","Hoxa2","Hoxa3","Hoxa4","Hoxa5","Hoxa6","Hoxa7")
for (i in 1:ceiling(length(my_gene_list)/6)) {
  if (i*6 < length(my_gene_list)) {
    p <- VlnPlot(object = tc, features = my_gene_list[((i-1)*6+1):(i*6)])
  } else {
    p <- VlnPlot(object = tc, 
                 features = my_gene_list[((i-1)*6+1):length(my_gene_list)])
  }
  print(p)
}
![image](https://user-images.githubusercontent.com/30619010/51077097-78fd6780-16dc-11e9-89b9-eb619ebf6159.png)
However, individual plot command will work:
VlnPlot(object = tc, features = c("Hoxa1","Hoxa2","Hoxa3","Hoxa4","Hoxa5","Hoxa6"), ncol = 3)

**Comment by tmccra2** [comment]
I am also having the same problem. I was following this tutorial and got the same error: https://satijalab.org/seurat/pbmc3k_tutorial_v3.html
pbmc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) -> top10
DoHeatmap(object = pbmc, features = top10$gene) + NoLegend()

Is there an easier way to select which genes to use for the heatmap?
