### ISSUE TITLE
shape.by does not work and can cause error in release3.0

### ISSUE THREAD

**Issue by cafeblue** [satijalab/seurat#1010]
Dear Developers,

I imagine you forgot to transfer the parameter shape.by to the SingleDimPlot, it will cause errors if you set "shape.by" parameter in the DimPlot function.  

I fixed it by adding the "shape.by" parameter at line 606 of file visualization.R

`

    $ diff R/visualization.R ../../seurat-release-3.0/R/visualization.R 

    606c606                        
                                                                                                                     
    <         data = data[, c(dims, x, split.by)],       
                                                                                               
    ---          
                                                                                                                                       
    >         data = data[, c(dims, x, shape.by, split.by)], 

`
Best,
wei

**Comment by satijalab** [comment]
Thanks for the catch! We will fix (if we have not already) @mojaveazure

**Comment by lima1** [comment]
Hi, I think FeaturePlot has a similar issue, shape.by is ignored.

**Comment by mojaveazure** [comment]
Hi M. Riester,

Thanks for catching! A fix has been pushed for `FeaturePlot`
