### ISSUE TITLE
ScaleData() on @Data with NaN's produces zero matrix without throwing errors.

### ISSUE THREAD

**Issue by aislyn** [satijalab/seurat#1011]
In v3.0.0.9000, IntegrateData() produced several all NaN columns in the `@assay$integrated@data` slot (most columns are fin otherwise). When ScaleData is performed, it produces an all zero matrix in the `@assay$integrated@scale.data` slot, and does not throw an error. The error message for performing RunPCA() on an all zero matrix isn't informative either.

**Comment by satijalab** [comment]
Thanks for the question. We'll explore our error messages, but can you provide any more information or an example where IntegrateData returned NA values?

**Comment by gouinK** [comment]
I am having the same issues as well - it seems to be happening when I am trying to integrate ~20 samples where the number of cells in each sample ranges from 700 - 5000 cells. When I integrate only 8 samples it does not produce this problem.

**Comment by timoast** [comment]
Sorry for the long delay here, @aislyn can you confirm if this error still appears with the latest version on the develop branch?
