### ISSUE TITLE
AlignSubspace--specify reference group (version 2) 

### ISSUE THREAD

**Issue by DanSchnell** [satijalab/seurat#1012]
Running AlignSubspace (version 2.3) and the (control) sample that I want to be the reference has fewer cells than the other (experimental) sample.  Any way to specify the reference sample in the call? Any suggested work-arounds (in version 2)?  Would splitting the experimental sample into 2 pieces and running MultiAlign be sensible?

**Comment by satijalab** [comment]
I believe that for two-sample alignment in v2, there is no real 'reference' (both samples are treated equally, or to put it another way, you would obtain identical alignments either way). You can explore this by looking at the dtw call in AlignSubspace, but in any case, we are transitioning to the v3 methodology
