### ISSUE TITLE
FindIntegrationAnchors for ADTs returns error

### ISSUE THREAD

**Issue by MaxKman** [satijalab/seurat#1017]
Hi,

thanks for developing Seurat. Great tool! 

Using Seurat 3.0 I tried FindIntegrationAnchors on two CITE-seq ADT datasets (containing 38 markers) using the following command:

`anchors.ADT <- FindIntegrationAnchors(object.list = seurat.obj.list, assay = c("ADT", "ADT"), anchor.features = rownames(seurat.obj.list[[1]]@assays$ADT@data), dims = 1:30, scale = FALSE, max.features = 38)`

It returns
> Error in data.use[features, ] : no 'dimnames' attribute for array

traceback() returns
> 8: RowVar(x = data.use[features, ])
> 7: CheckFeatures(data.use = data.use1, features = features, object.name = "object1", 
>        verbose = FALSE)
> 6: RunCCA.Seurat(object1 = object.1, object2 = object.2, features = anchor.features, 
>        num.cc = max(dims), renormalize = FALSE, rescale = FALSE, 
>        verbose = verbose)
> 5: RunCCA(object1 = object.1, object2 = object.2, features = anchor.features, 
>        num.cc = max(dims), renormalize = FALSE, rescale = FALSE, 
>        verbose = verbose)
> 4: FUN(X[[i]], ...)
> 3: lapply(X[Split[[i]]], FUN, ...)
> 2: my.lapply(X = 1:nrow(x = combinations), FUN = function(row) {
>        i <- combinations[row, 1]
>        j <- combinations[row, 2]
>        object.1 <- object.list[[i]]
>        object.2 <- object.list[[j]]
>        object.pair <- RunCCA(object1 = object.1, object2 = object.2, 
>            features = anchor.features, num.cc = max(dims), renormalize = FALSE, 
>            rescale = FALSE, verbose = verbose)
>        if (l2.norm) {
>            object.pair <- L2Dim(object = object.pair, reduction = reduction)
>            reduction <- paste0(reduction, ".l2")
>        }
>        anchors <- FindAnchors(object.pair = object.pair, assay = c(assay[i], 
>            assay[j]), cells1 = colnames(x = object.1), cells2 = colnames(x = object.2), 
>            reduction = reduction, dims = dims, k.anchor = k.anchor, 
>            k.filter = k.filter, k.score = k.score, max.features = max.features, 
>            eps = eps, verbose = verbose)
>        anchors[, 1] <- anchors[, 1] + offsets[i]
>        anchors[, 2] <- anchors[, 2] + offsets[j]
>        return(anchors)
>    })
> 1: FindIntegrationAnchors(object.list = seurat.obj.list, assay = c("ADT", 
>        "ADT"), anchor.features = rownames(seurat.obj.list[[2]]@assays$ADT@data), 
>        dims = 1:30, scale = FALSE, max.features = 38)

Not sure if this is a bug or if the method is currently not intended to be used with small marker sets as derived from CITE-seq. The command works fine for the RNA-derived data.

Best Max

**Comment by satijalab** [comment]
can you try this with a slightly lower max.features (i.e. 30)? it only affects anchor filtering, but if that works, that will help us debug.

**Comment by MaxKman** [comment]
Just tried that. This doesn't make a difference.

**Comment by satijalab** [comment]
Thanks - we will take a look as we are certainly want to encourage users to do this. We have successfully aligned  CITE-seq datasets in the past, but will make sure this functionality works in the public release, and will reach out for more detail if needed.

**Comment by MaxKman** [comment]
Thanks, looking forward to it!

**Comment by MaxKman** [comment]
Some more information + an additional problem:
- The error only occurs when scale = FALSE is set, although the scaled data exist
- in this case the error occurs for ADTs as well as RNA
- when I start the function for the ADTs with scale = TRUE the R session aborts with a critical error after displaying:

> Scaling features for provided objects
>    |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 03s
> Finding all pairwise anchors
>    |                                                  | 0 % ~calculating  Running CCA on different assaysMore than 10% of provided features filtered out. Please check that the given features are present in the scale.data slot for both the assays provided here and that they have non-zero variance.Fewer than 50 features used as input for CCA.Running CCA

Is there a workaround by any chance until the bug is fixed?

Best Max

**Comment by satijalab** [comment]
Thanks very much. Apologies for the slow reply over the holidays and you are absolutely correct. We will fix in an upcoming version @andrewwbutler

**Comment by MaxKman** [comment]
Thanks!

**Comment by andrewwbutler** [comment]
Hi Max,

I've push a commit (dcb931a) to `release/3.0` that should set the assay parameters properly now. Let me know if that fixes the issue for you.

**Comment by FarzanT** [comment]
Hello,
I still get the same error:
```r
Finding all pairwise anchors
   |                                                  | 0 % ~calculating  Error in data.use[features, ] : no 'dimnames' attribute for array

```
For the `"RNA"` assay. My code is
```r
    cur_anchors = FindIntegrationAnchors(
        object.list = all_subs,
        assay = rep("RNA", length(all_subs)),
        anchor.features = 3000,
        dims = 1:5,
        scale = F,
        l2.norm = T,
        k.anchor = 5,
        k.filter = 200,
        k.score = 30,
        max.features = 200,
        eps = 0, 
        verbose = T
    )
```
Where `all_subs` is a list of Seurat objects made by subsetting the other Seurat objects based on some cell identifiers.
I subset by column instead of using the `Subset` function:
```r
celltype = "Macrophage"
for (i in 1:length(seurat_list)) {
    all_subs[[i]] <- seurat_list[[i]][, seurat_list[[i]]$hpca_cell_name == celltype]
}
```
Checking `dimnames(all_subs[[i]])` returns feature and cell names for all list items; I really don't know where this error is coming from.

Any help is appreciated!

Thanks,
Farzan
