### ISSUE TITLE
Questions about JackStrawPlot and PCElbowPlot

### ISSUE THREAD

**Issue by leafyes** [satijalab/seurat#1018]
Hi,
I'm trying to get the matrix file plotting the JackStrawPlot and PCElbowPlot. 
The help file of JackStrawPlot, which says 

> "Returns a Seurat object where object@dr$pca@jackstraw@overall.p.values represents p-values for each PC and object@dr$pca@misc$jackstraw.plot stores the ggplot2 plot",

 but when  I used the command "head(object@dr$pca@jackstraw@overall.p.values)" ，it returned 0 x 0 matrix. 
`JackStrawPlot(object = cel.seq, PCs = 1:20)`
`head(cel.seq@dr$pca@jackstraw@overall.p.values )`
`<0 x 0  matrix>`

I am wondering how to view the matrix file plotting the JackStrawPlot and PCElbowPlot. 
Could you help me?
Thanks
Jialin Zheng

**Comment by satijalab** [comment]
The data is pulled from (for the object pbmc_small):
pbmc_small[["pca"]]@jackstraw@empirical.p.values

**Comment by xbjie123** [comment]
Hi,

It still does work. How to deal with it?
`> combined[["pca"]]@jackstraw@empirical.p.values
Error in combined[["pca"]] : this S4 class is not subsettable`

Best
BJ

**Comment by xbjie123** [comment]
Hi,

It still doesn't work. How to deal with it?

`> combined_pre_batch[["pca"]]@jackstraw@empirical.p.values

Error in combined_pre_batch[["pca"]] : this S4 class is not subsettable
`

Best
BJ

**Comment by timoast** [comment]
In Seurat v2:

```r
pbmc_small@dr$pca@jackstraw@emperical.p.value
```

In Seurat v3:

```r
JS(object = pbmc_small[['pca']], slot = 'empirical')
```

**Comment by xbjie123** [comment]
Thanks @timoast. It works now.
