### ISSUE TITLE
Convert AnnData to Seurat fails with raw h5ad

### ISSUE THREAD

**Issue by BenjaminDoran** [satijalab/seurat#1021]
https://github.com/satijalab/seurat/blob/37a3750f599fc4c0e1226aced130441a8b250077/R/conversion.R#L364
This line fails on some unprocessed data because the dgCmatrix does not have the correct dimensions
sparseMatrix by default assumes the dimensions of the adata.raw.x matrix by using the max values of the indices. This is not always the case as when converting unprocessed data. where the last couple of rows might be all zeros.

adding 
`
dims = c(py_to_r(from$raw$X$shape[1]), py_to_r(from$raw$X$shape[0]))
`
to the sparse matrix initialization call should fix this particular error

**Comment by BenjaminDoran** [comment]
```
raw.data.matrix <- sparseMatrix(
    i = as.numeric(x = from$raw$X$indices),
    p = as.numeric(x = from$raw$X$indptr),
    x = as.numeric(x = from$raw$X$data),
    dims = c(py_to_r(from$raw$X$shape[1]), py_to_r(from$raw$X$shape[0])),
    index1 = FALSE
  )
```

**Comment by satijalab** [comment]
Thanks very much! I am flagging @mojaveazure to follow up.

**Comment by mojaveazure** [comment]
Reading Anndata h5ad files is present in Seurat v3 with `ReadH5AD` (a la #774 @cartal); writing h5ad files is still WIP

**Comment by BenjaminDoran** [comment]
After checking the `ReadH5AD` function I found a the same issue with reading unfiltered data. The S4 DgCmatrix has the wrong dimensions reading in directly from the h5 file which prevents us from putting in the rownames and column names (var, obs) from the h5ad file.

This should be fixed by replacing 
```
  x <- if (is(object = hfile[['X']], class2 = 'H5Group')) {
    as.sparse(x = hfile[['X']])
  } else {
    hfile[['X']][, ]
  }
```
with
```
  x <- if (is(object = hfile[['X']], class2 = 'H5Group')) {
    as.sparse(x = hfile[['X']])
    x@Dim <- c(length(hfile[["var"]][]$index), length(hfile[["obs"]][]$index))
  } else {
    hfile[['X']][, ]
  }
```

**Comment by smanne07** [comment]
Hi,
I am getting the following error when using  _ ReadH5AD_ in Seuratv3.

`Error in dimnamesGets(x, value) : 
  invalid dimnames given for “dgCMatrix” object
Calls: ReadH5AD ... rownames<- -> dimnames<- -> dimnames<- -> dimnamesGets`

Is this also part of this fix which is a WIP?

Thank you
SM

**Comment by BenjaminDoran** [comment]
I believe so, I was seeing that error when trying to read in unfiltered
expression matrices.  it is caused by the length of rownames not matching
between the h5 file and when hdf5r reads in the expression matrix. Check if
you have any "cells" with zero expression

**Comment by BenjaminDoran** [comment]
Huh.. Thought I fixed this, turns out there is another issue with columns of unexpressed cells. the matrix@p ends up with the wrong length. I think I have found a solution, but will test on Monday.

**Comment by screamer** [comment]
I have similar issue when it reads raw counts in the h5ad format.
The code is simple:
obj <- ReadH5AD(filename)
The error warnings are:
Pulling expression matrices and metadata
Data is unscaled
Creating assay object
Storing X as raw and raw as counts
Error in .subset2(x, i, exact = exact) : subscript out of bounds
