### ISSUE TITLE
RunMultiCCA with custom normalization

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#1022]
`RunMultiCCA` includes `NormalizeData`. Thus, if you perform custom normalization, it will get overwritten. Is there a way to get around that? It looks like the CCA calculation is done on the original objects, so maybe it doesn't matter, except that the final object does not include the original expression values. This issue was briefly discussed previously (https://github.com/satijalab/seurat/issues/612) but there was no definite answer.

This is probably a moot point since `RunMultiCCA` is retired in Seurat 3, but it would also apply to the new protocol (maybe in `IntegrateData`).

**Comment by satijalab** [comment]
This does not apply in the new version - IntegrateData does not overwrite data in the original objects, so you can use and retain any custom normalization throughout
