### ISSUE TITLE
A question about analyzing GEO data

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#1023]
Hello,

Thanks for the new version, I'm looking forward to trying it! 

I have a question about analyzing published data (downloaded from GEO). I found a study (GSE120575) where immune cells from melanoma patients were sequenced via SmartSeq. I was able to download the researcher-provided TPM counts file (featuring data from all patients) and made a large `Seurat` object. 

What is the best practice analyzing such a dataset? Can I run `PCA` and `TSNE` on this combined object and do subsequent analyses (Visualizations-differential expr comparisons etc) in subsets of cells? Or alternatively, do I need to create smaller Seurat objects by using data from individual patients and use `multiCCA` approach for aligning them before further analyses?

Thanks
Atakan

**Comment by satijalab** [comment]
You can certainly begin with a standard analysis (PCA/tSNE, etc.). If you find that cells are clustering primarily by batch/patient, and you expect there to be shared biological similarity between individual subsets across batches which is masked by these effects, then we would suggest running an alignment workflow

**Comment by atakanekiz** [comment]
Makes sense. Thank you very much!
