### ISSUE TITLE
Seurat 3.0_RunCCA error

### ISSUE THREAD

**Issue by yuwenjiesail** [satijalab/seurat#1026]
I am using Seurat_V3.0 to integrate two groups of 10x datasets. Since I could not find tutorial for Seurat_V3.0. I have to adjust codes that for seurat 2.3. Unfortunately, I could not get it doen. I am wondering if anyone could help me out either send me a tutorial link for 3.0 or change my codes listed below? Thank you so much! 

# Gene selection for input to CCA
WT <- FindVariableFeatures(WT, do.plot = F)
KO <- FindVariableFeatures(KO, do.plot = F)
g.1 <- head(rownames(WT), 1000)
g.2 <- head(rownames(KO), 1000)
features.use <- unique(c(g.1,g.2))
features.use <- intersect(features.use, rownames(WT))
features.use <- intersect(features.use, rownames(KO))
-------------------------------------------------
Everything is good so far.
Then I ran CCA, and error showed up.
-------------------------------------------------
# Run CCA
All.combined <- RunCCA(WT, KO, features.use = features.use, num.cc = 30)

Running CCA
Merging objects
Error in cca.results$ccv[colnames(combined.object), ] : 
  subscript out of bounds

**Comment by igordot** [comment]
The workflow was substantially updated in Seurat 3. You can find the updated tutorial here: https://satijalab.org/seurat/pancreas_integration_label_transfer.html
