### ISSUE TITLE
ScaleData multi-threaded

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#1027]
In Seurat 2, `ScaleData()` had a multi-threaded option. It looks like that was removed in Seurat 3. Was that on purpose or just an oversight?

Additionally, the documentation states that `features` defaults to all features (and that's what it looks like in the code as well), but it is only returning the variable genes for me. I am also concerned if this would impact the next `RunPCA` step.

**Comment by mojaveazure** [comment]
Hi Igor,

We have replaced the old multithreaded implementation with use of [futures](https://github.com/HenrikBengtsson/future). This means that you can enable multithreading via the `plan` function from future. We will release a list of all functions that use futures soon.

As for the documentation, `ScaleData` defaults to only variable features. We will update the documentation. If you would like to run on all features, simply pass `object <- ScaleData(object = object, features = rownames(x = object)...)`

**Comment by Emmavb1988** [comment]
'As for the documentation, ScaleData defaults to only variable features. We will update the documentation. If you would like to run on all features, simply pass object <- ScaleData(object = object, features = rownames(x = object)...)'

I've tried the above using Seurat v3, but I get an error: 

Error in `[<-`(`*tmp*`, features[my.inds], , value = data.scale) : 
  subscript out of bounds

Any idea what I could do about this?
