### ISSUE TITLE
Seurat version 2.0.0 NormalizeData issue

### ISSUE THREAD

**Issue by s18692001** [satijalab/seurat#103]
Hi there,

I'm now using Seurat version 2.0.0 with R 3.4.0. 
When I use the following command:
```
pbmc <- NormalizeData(object = pbmc, normalization.method = "LogNormalize", 
                      scale.factor = 10000)
```
It shows:
```
  "_Seurat_LogNorm" not available for .Call() for package "Seurat"
In addition: Warning message:
In fetch(key) : internal error -3 in R_decompress1
```
Any suggestion?
Thanks!

Sincerely,
Simon

**Comment by andrewwbutler** [comment]
Hi Simon,

How did you go about installing the package?

**Comment by s18692001** [comment]
Hi Andrew,

Thanks for your fast reply! Here is the method I used to install in my
linux system:

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

> library(devtools)
> install_github("satijalab/seurat",ref="v2.0.0")

**Comment by andrewwbutler** [comment]
Hmm, try updating to R 3.4.1 and the latest Rcpp version (0.12.12). Then try reinstalling Seurat and see if that fixes the issue.

**Comment by s18692001** [comment]
Hi Andrew,

I just reinstall the Seurat package with the command
 install_github("satijalab/seurat")
and it works! (However, I don't know how does it work...) I just pass
through the problem of normalization and face with a new issue I just
created in new ticket. It is a problem about PCHeatmap (subscript out of
bound)

Thanks!

Simon
