### ISSUE TITLE
Convert loom file to Seurat

### ISSUE THREAD

**Issue by mxs1489** [satijalab/seurat#1031]
Hi there- 
I am trying to convert an available loom file to Seurat (I am new to loompy but very familiar with Seurat - conversion would allow much more control and comfort over deeper analysis of the data). 
The convert documentation seems to support conversion to/**from** loom but I am having difficulty getting it to work.
Any help would be greatly appreciated!

hdf5r is updated (hdf5r_1.0.1); loomR is updated (loomR_0.2.0). (see below for complex session info)

Here is the command followed by the error:

S_object <- Convert(from= lfile, to= "seurat")

Error in UseMethod(generic = "Convert", object = from) :
no applicable method for 'Convert' applied to an object of class "c('loom', 'H5File', 'H5RefClass', 'R6')"

sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] splines stats4 parallel stats graphics grDevices utils
[8] datasets methods base

other attached packages:
[1] loomR_0.2.0 itertools_0.1-3 iterators_1.0.10
[4] hdf5r_1.0.1 R6_2.3.0 monocle_2.10.0
[7] DDRTree_0.1.5 irlba_2.3.2 VGAM_1.0-6
[10] Biobase_2.42.0 BiocGenerics_0.28.0 bindrcpp_0.2.2
[13] Seurat_2.3.4 Matrix_1.2-15 cowplot_0.9.3
[16] ggplot2_3.1.0

**Comment by aopisco** [comment]
hey, I found it here: https://github.com/satijalab/seurat/blob/loom/R/conversion.R
if you scroll all the way to the end of the code you have `Convert.loom`
