### ISSUE TITLE
Get genes associated with a PC

### ISSUE THREAD

**Issue by snoopy-448** [satijalab/seurat#1032]
Hi,
I want to get the genes that are mostly associated with a PC(such as PC1). It seems that PrintPCA and VizPCA can do such thing, but I don't know how to get the genes and corresponding values (PCA scores) instead of print them on screen.
I noted that PCASigGenes can also accomplish this goal, what would be the difference between the significant genes identified by PCASigGenes and PrintPCA? Which method is more reasonable?
Thanks!

Yang

**Comment by timoast** [comment]
You can look at the gene loadings for each PC

In Seurat v2:

```r
GetGeneLoadings(pbmc_small)
```

In v3:

```r
Loadings(pbmc_small[['pca']])
```
