### ISSUE TITLE
IntegrateData using all features

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#1034]
By default, `IntegrateData()` uses the features used in anchor finding for `features.to.integrate`. When I try to set that to genes found in all the datasets, I usually get an error:
```
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
```
Using the genes that are present in all the datasets solves the problem.

I am not sure why it does not always throw an error. If it does, is that expected? Should there be a warning?

**Comment by satijalab** [comment]
CCA will throw an error if you force it to run on a gene that does not exist in the dataset - which is why you are seeing this error. The solution as you suggest is to run on the intersection of all genes.
