### ISSUE TITLE
Find differentially expressed genes for two user-defined cell groups

### ISSUE THREAD

**Issue by snoopy-448** [satijalab/seurat#1035]
Hi,
I want to find DE genes between two group of cells. For example, in a 20000 x 1500(gene x cell) matrix, 1000 cells are TUMOR and 500 cells are NORMAL. I want to find the DE genes between these two groups. I think FindMarkers can do this, but do not know how to properly label these cells and how to set the ident.1 and ident.2. Could you give me some advice?
Thanks very much!
Yang

**Comment by satijalab** [comment]
You can use the SetIdent function to set identity classes for your two cell groups.

In Seurat v3 (and I believe also v2) you can pass in cell IDs instead of identity classes to FindMarkers
