### ISSUE TITLE
Get residuals without centering and scaling from ScaleData

### ISSUE THREAD

**Issue by snoopy-448** [satijalab/seurat#1037]
Hi,
I use ScaleData to regress out some effects such as nUMI and percent.mito, but I want to get the residuals without scaling and centering. I set do.center and do.scale in ScaleData to FALSE, but I check the `object@scale.data`, rowSums shows that the sum of each gene is 0, so it seems like scaling and centering is still done. I wonder if I could get the residual value before scaling and centering, could you give me some advice?
Thanks a lot!
YANG

**Comment by satijalab** [comment]
The mean may continue to be 0, even without centering, as the average of residuals can be 0. However, if you set scale to F, the variance will not be 1

I can verify this by running 
pbmc_small <- ScaleData(pbmc_small,vars.to.regress = "nCount_RNA",do.scale = F,do.center = F)

in Seurat v3
