### ISSUE TITLE
Plotting 2 unaligned datasets in Tsne space

### ISSUE THREAD

**Issue by vthaker** [satijalab/seurat#1038]
Hi Seurat team,
I am hoping to make a plot of 2 unaligned datasets prior to CCA similar to the Figure 1a in Butler 2018. 
Looked through the discussion on Github, and did not find this question. Would appreciate if someone who knows better can share the code. 
Thanks

![tsne](https://user-images.githubusercontent.com/13457736/50698303-821e7280-1012-11e9-8bd5-62d4cfe541df.png)

**Comment by leonfodoulian** [comment]
Hi @vthaker,

Simply follow the standard Seurat workflow without CCA alignment. To colour the cells by condition (and not cluster assignment), please see https://github.com/satijalab/seurat/issues/492#issuecomment-391468727.

Best,
Leon

**Comment by vthaker** [comment]
Hi Leon,

this does not seem to work for me. I have tried it in 4 different datasets, where I have evidence SC and bulk rna seq that the datasets are quite different. 

Here is what I get
![image](https://user-images.githubusercontent.com/13457736/50741227-331a3e00-11c8-11e9-8992-86990f9536b3.png)

**Comment by leonfodoulian** [comment]
Hi @vthaker,

This t-SNE plot is from the workflow without CCA alignment, right?

> this does not seem to work for me. I have tried it in 4 different datasets, where I have evidence SC and bulk rna seq that the datasets are quite different.

What is it that is not working properly? Also, what differences do you expect between your conditions? Differences in cell type? Differences in subpopulation densities? Differences in gene expression levels?

Best,
Leon

**Comment by vthaker** [comment]
The t-SNE plot is WITHOUT CCA alignment. 

If the method is able to show the differences in the Drug +/- PBMCs as in the tutorial, it should certainly show the differences between the 2 groups here. 

With CCA, there are differences in subpopulation densities and gene expression levels. 
There were > 100 cells that did not align between the 2 datasets. 
The number of cells in each group are not similar, F=3266, M= 17656. Does that make a difference?
Sometime ago I had asked the question about using CCA for uneven datasets, and the response was that unequal sizes does not matter.

**Comment by leonfodoulian** [comment]
Hi @vthaker,

> If the method is able to show the differences in the Drug +/- PBMCs as in the tutorial, it should certainly show the differences between the 2 groups here.

These differences are dataset specific. I don't think you should expect t-SNE plots that show such differences with all datasets. 

> With CCA, there are differences in subpopulation densities and gene expression levels.
> There were > 100 cells that did not align between the 2 datasets.

Nevertheless, some cell clouds in your t-SNE plot show either cell density or subpopulation composition differences between your conditions.

> The number of cells in each group are not similar, F=3266, M= 17656. Does that make a difference?
> Sometime ago I had asked the question about using CCA for uneven datasets, and the response was that unequal sizes does not matter.

I am not an authority on this but I don't think that uneven number of cells between two datasets would make a difference (unless one dataset is fairly small, which would not allow you to capture all the cell types that you would find in the other dataset with larger number of cells). 

Best,
Leon

**Comment by vthaker** [comment]
I suppose you are right: either the datasets are not different enough, or the smaller numbers are not capturing the differences accurately. 
One additional question: Do you know if interaction of two conditions be tested in CCA?
two groups x two conditions.

**Comment by satijalab** [comment]
As you say, in this case - the expression differences across conditions (for whatever reason) are not strong enough to drive dataset separation. In this case, you do not need to run an alignment workflow, as the samples are inherently mixed.
