### ISSUE TITLE
Error in FindClusters

### ISSUE THREAD

**Issue by ericvon11** [satijalab/seurat#104]
I've been following the pbmc tutorial on filtering and clustering my data, but after doing RunPCA and using ElbowPlot to pick my PCs, I can't get `FindClusters` to work. It displays its progress, reaches 100%, then gives this file "rt" error. I tried uninstalling java and reinstalling. Uninstalling R and reinstalling. Adding C:\R to my path in environmental variables. Removed the 'read-only' on C:\R folder. I have no clue how to fix it. Any ideas?
```
PData = FindClusters(object = PData, reduction.type = "pca", dims.use = 1:17, 
                   resolution = 2.5, save.SNN = T, algorithm = 2)
```
`Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: running command 'java -jar "C:/R/win-library/3.4/Seurat/java/ModularityOptimizer.jar" "C:/R/win-library/3.4/edge_52130.txt" "C:/R/win-library/3.4/output_52130.txt" 1 2.5 2 100 10 0 1' had status 127 
2: In file(file, "rt") :
  cannot open file 'C:/R/win-library/3.4/output_52130.txt': No such file or directory`

**Comment by andrewwbutler** [comment]
I think you're right about it being a file permissions problem. Have you tried setting the temp.file.location parameter to somewhere else?

**Comment by ericvon11** [comment]
I originally tried setting the temp.file.location elsewhere inside of 'My Documents', but it gave the same problem. I've checked and it does successfully write the "edgeXXXX.txt" file wherever I set the directory to, but the output.txt file is never created.

**Comment by andrewwbutler** [comment]
What happens if you just try to run `java -jar "C:/R/win-library/3.4/Seurat/java/ModularityOptimizer.jar"` from a command prompt?

**Comment by ericvon11** [comment]
It starts the Modularity Optimizer, but it throws this error at me:

```
C:\Users\Eric Vaughn>java -jar "C:/R/win-library/3.4/Seurat/java/ModularityOptimizer.jar" "C:/R/win-library/3.4/edge_52130.txt"
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Input file name: "C:/R/win-library/3.4/edge_52130.txt"
Output file name: "C:/R/win-library/3.4/output_52130.txt"
Modularity function (1 = standard; 2 = alternative): 1
Resolution parameter (e.g., 1.0): 2.5
Algorithm (1 = Louvain; 2 = Louvain with multilevel refinement; 3 = smart local moving): 2
Number of random starts (e.g., 10): 100
Number of iterations (e.g., 10): 10
Random seed (e.g., 0): 0
Print output (0 = no; 1 = yes): 1

Reading input file...

Exception in thread "main" java.io.FileNotFoundException: "C:\R\win-library\3.4\edge_52130.txt" (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at ModularityOptimizer.readInputFile(ModularityOptimizer.java:164)
        at ModularityOptimizer.main(ModularityOptimizer.java:74)
```

The file 'edge_52130.txt' does indeed exist though. Not sure what the issue is.

**Comment by ericvon11** [comment]
Just tried writing the input file without quotation marks and it worked in command prompt. It generates an output file.  So perhaps the script is adding quotation marks to the directory when java doesn't want that?

**Comment by ericvon11** [comment]
I just removed Seurat and reinstalled to a new library path and it appears to be working in R now. My old library path included a space in the directory, so I figured that could cause some issues. It appears to be fixed now so you can close this issue. Thanks Andrew.

**Comment by Lucyyang1991** [comment]
I reinstalled the R and Seurat, but it still not work

**Comment by Lucyyang1991** [comment]
I solved this problem by instralling the java.
