### ISSUE TITLE
question about runcca function

### ISSUE THREAD

**Issue by chintanparekh2301** [satijalab/seurat#1040]
Hello,
the source code for the runCCA function (https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/dimensional_reduction.R#L584-L606) has scale.data set at "true" implying that the runcca function uses data from the scale.data slot of the objects. Since the data in the scale.data slot is already centered and scaled, what is the rationale  for setting the default for the standardize parameter lower down in the code  to "true" . My understanding is that standardize centers and scales the data but if the function is already using scaled and centered data (from the scale.data slot) then wouldn't standardize just center and scale already centered and scaled data ?
Thank you very much

**Comment by satijalab** [comment]
I believe this step standardizes the columns instead of the rows, @andrewwbutler can confirm.

**Comment by andrewwbutler** [comment]
That is correct. The `standardize` parameter you're referring to below is passed to the `CanonCor` function which should do column scaling/centering.
