### ISSUE TITLE
about "StashIdent" and "SetAllIdent"

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#1041]
Dear all, 

as I was going over the tutorial presented at : https://satijalab.org/seurat/immune_alignment.html,
please would you let me know how these 2 functions work : 

-- StashIdent()
-- SetAllIdent()

and why these 2 functions/operations are necessary. Thanks a lot ! Happy and healthy new year !

**Comment by mojaveazure** [comment]
Hi Bogdan,

You can see an example of these functions in our [PBMC 3k tutorial](https://satijalab.org/seurat/pbmc3k_tutorial.html); further details can be found by reading the documentation for [`StashIdent`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/StashIdent) and [`SetAllIdent`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/SetAllIdent), accessible in R through the [`help` and `?` functions](https://www.r-project.org/help.html).
