### ISSUE TITLE
threshold values in Filtering cells

### ISSUE THREAD

**Issue by CuriusScientist** [satijalab/seurat#1043]
I can understand that we need to remove cells with unique gene counts over 2,500 or less than 200. hence, thought the threshold values will be like following 
low.thresholds = 200, high.thresholds = 2500

but in vignette, it is mentioned as follows 
low.thresholds = c(200, -Inf), high.thresholds = c(2500, 0.05)

What am I missing here?

**Comment by leonfodoulian** [comment]
Hi @CuriusScientist,

> low.thresholds = c(200, -Inf), high.thresholds = c(2500, 0.05)

In the case above, you are filtering cells based on two meta data variable. If I'm not mistaken, these correspond to the number of expressed genes and mitochondrial count abundance.

Best,
Leon

**Comment by satijalab** [comment]
In this case, we are accepting cells with 200 < expressed genes < 2500, and -Inf < mitochondrial percentage < 0.05. Hope that helps!

**Comment by CuriusScientist** [comment]
> In this case, we are accepting cells with 200 < expressed genes < 2500, and -Inf < mitochondrial percentage < 0.05. Hope that helps!

Apologies for asking such a dumb question. After analyzing plots I also came up with the same conclusion but @leonfodoulian  and @satijalab  thanks for verifying it. 

Looking at the values of nGene, I was able to understand it more clearley 
> head(sort(pbmc@meta.data$nGene,decreasing = FALSE))
[1] 212 239 246 267 267 270
> head(sort(pbmc@meta.data$nGene,decreasing = TRUE))
[1] 3422 3315 2815 2710 2694 2455 


I am still not able to understand the logic behind -Inf for percent.mito as lowest value can be only 0

> head(sort(pbmc@meta.data$percent.mito,decreasing = TRUE))
[1] 0.2256903 0.2010135 0.1046025 0.1044776 0.1017341 0.1014056
> head(sort(pbmc@meta.data$percent.mito,decreasing = FALSE))
[1] 0.000000000 0.000000000 0.000000000 0.001245330 0.001264223 0.001666667

**Comment by s2hui** [comment]
Re: low and high thresholds.

1) Are these thresholds determined by visually inspecting the violin plots?  Is there a way to programmatically determine these thresholds? 

2) If so, how or why is the lower bound of 200 selected?  I can see the reason for the upper bounds (based on looking at the violin plots, but it's hard to see the lower bound on these plots).

Thanks for your insight,
shui

**Comment by ElyasMo** [comment]
Actually, I have the same question. In a dataset, by choosing these thresholds you will loose 80% of cells. How we should determine these two thresholds? or these two numbers (2500 and 200) shouldn't change...?
