### ISSUE TITLE
Question about avg_logFC

### ISSUE THREAD

**Issue by rbioinfo** [satijalab/seurat#1045]
Hello, I found how the avg_logFC are calculated:

```
data.1 <- apply(X = data.use[genes.use, cells.1, drop = F], 
        MARGIN = 1, FUN = function(x) log(x = mean(x = expm1(x = x)) + 
            pseudocount.use))
data.2 <- apply(X = data.use[genes.use, cells.2, drop = F], 
        MARGIN = 1, FUN = function(x) log(x = mean(x = expm1(x = x)) + 
            pseudocount.use))
```
Could you please help me to understand why you applied the expm1 function to all the values before to do the mean? Is it better to consider the mean without the expm1 function?
Thank you,

**Comment by satijalab** [comment]
We apply expm1 because this function by default is run on log-normalized data (so the expm1 reverses this). Hope that helps!
