### ISSUE TITLE
Customize colors for DoHeatmap function in v3

### ISSUE THREAD

**Issue by MJ-Yang** [satijalab/seurat#1048]
Hello, 
I really appreciate your efforts to make such useful tool for single cell RNA seq.
I've been using v2 for the whole time and now adjusting to v3.

I've found that DoHeatmap function has changed a bit. Previously, we were able to set colors manually through col.low ~col .high, but I've found it's missing in v3. Is it deprecated?

If so, how can I set colors manually for DoHeatmap function?

**Comment by andrewwbutler** [comment]
Hi,

Since `DoHeatmap` returns a ggplot object in Seurat v3, you can manipulate the colors by specifying the color scale. For example

```R
library(ggplot2)
DoHeatmap(object = pbmc_small) + scale_fill_gradientn(colors = c("blue", "white", "red"))
```

You can also easily apply color schemes provided by other packages, such the viridis color palettes.
```R
library(viridis)
DoHeatmap(object = pbmc_small) + scale_fill_viridis()
```

**Comment by lima1** [comment]
Hi, I think it's currently not possible to change the color of group bar, right? 

DoHeatmap(object = pbmc_small) + scale_color_manual(values=cbPalette)

**Comment by andrewwbutler** [comment]
No, unfortunately it's not currently possible to change those colors though we would welcome a PR for that feature if anyone's interested in implementing.

**Comment by Dragonmasterx87** [comment]
Single a google search defaults to this I thought i'd add this in case someone would be interested 

[DoHeatmap](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/DoHeatmap)

`group.colors = c("red", "blue")` adds colors to the bar.

**Comment by lwhitmore** [comment]
Does anyone know if you can sort the groups (columns) in the heatmap specifically in doheatmap?

**Comment by kaizen89** [comment]
@lwhitmore You can do this by changing the order of levels of the variable that you want to sort by.
```
levels(factor(object@variable_to_sort))
> levels: 1,2,3
object@variable_to_sort <- factor(object@variable_to_sort, levels=c(3,2,1))
levels(object@variable_to_sort)
levels: 3,2,1
```

**Comment by Landau1994** [comment]
Follow the @andrewwbutler idea  , we can do the following
```R
mapal <- colorRampPalette(RColorBrewer::brewer.pal(11,"RdBu"))(256)
DoHeatmap(pbmc_small, 
          angle = 90,size = 3)+
  scale_fill_gradientn(colours = rev(mapal))
```

**Comment by jiangshan529** [comment]
> Follow the @andrewwbutler idea , we can do the following
> 
> ```r
> mapal <- colorRampPalette(RColorBrewer::brewer.pal(11,"RdBu"))(256)
> DoHeatmap(pbmc_small, 
>           angle = 90,size = 3)+
>   scale_fill_gradientn(colours = rev(mapal))
> ```

Hi, does anyone know how to deal with this error? I have installed dichromat and RColorBrewer. Thanks!

```
object of type 'closure' is not subsettable
```
