### ISSUE TITLE
How to change a gene name

### ISSUE THREAD

**Issue by pallottom** [satijalab/seurat#1049]
Hello!
I would like to know if it possible to change a gene name. Let me explain better: in different experiments I injected a eGFP virus in mice to label cell population A, in some mice, and in other mice the same virus to label cell population B. Now, I would like to compare the two cell population as well pooling together the two datasets and run some more analysis. So it would be very helpful for me to name the cell containing eGFP in cell population A different than the ones in cell population B.
I would like to know if I can change the gene name from eGFP to cellA or cellB after the cellRanger count, in Seurat.
Thank you!

**Comment by mojaveazure** [comment]
There currently isn't a way to easily modify gene or cell names of a Seurat object. To do this, we strongly recommend modifying the expression matrix before creating the Seurat object. If that isn't an option, you'll need to modify all the matrices in the Seurat object as follows:

For Seurat v2 objects, you need to modify the `object@raw.data`, `object@data`, `object@scale.data`, `object@cell.names` and `object@meta.data` slots, as well as re-running any dimensional reduction (eg. `RunPCA`)  procedures you may have run previously.

For Seurat v3, you need to modify the `counts`, `data` and `scale.data` slots for every assay you have in your Seurat object. In addition, you will also need to modify the `meta.data` slots for both the object and each assay object contained within the Seurat object. Finally, you'll need to rerun any dimensional reduction and graph-building (eg. `FindNeighbors`) procedures. More details about the Seurat v3 object structure can be found in our [Developer's Guide](https://github.com/satijalab/seurat/wiki).

**Comment by ayshwaryas** [comment]
@mojaveazure it would be helpful to see an example of how the rownames of the counts, data and scale.data slots of Seurat v3 can be modified. I run into the same error discussed here:
https://github.com/satijalab/seurat/issues/1430

**Comment by Sophia409** [comment]
still interest in seeing an example of how the rownames of the counts, data and scale.data slots of Seurat v3. @mojaveazure

**Comment by vertesy** [comment]
Hi,

you can use `RenameGenesSeurat()` from [Seurat.utils](https://github.com/vertesy/Seurat.utils/). Please take to heart what @mojaveazure said. May give you headache if using out after you created other slots in the object. 


```r
# RenameGenesSeurat  ------------------------------------------------------------------------------------
RenameGenesSeurat <- function(obj = ls.Seurat[[i]], newnames = NewSymbols) { # Replace gene names in different slots of a Seurat object. Run this before integration. It only changes obj@assays$RNA@counts, @data and @scale.data.
  print("Run this before integration. It only changes metadata; obj@assays$RNA@counts, @data and @scale.data")
  RNA <- obj@assays$RNA

  if (nrow(RNA) == nrow(newnames)) {
    if (length(RNA@counts)) RNA@counts@Dimnames[[1]]            <- newnames
    if (length(RNA@data)) RNA@data@Dimnames[[1]]                <- newnames
    if (length(RNA@scale.data)) RNA@scale.data@Dimnames[[1]]    <- newnames
    if (length(obj@meta.data)) rownames(combined.obj@meta.data) <- newnames
  } else {"Unequal gene sets: nrow(RNA) != nrow(newnames)"}
  obj@assays$RNA <- RNA
  return(obj)
}
# RenameGenesSeurat(obj = SeuratObj, newnames = HGNC.updated.genes)
```

**Comment by denvercal1234GitHub** [comment]
> Hi,
> 
> you can use `RenameGenesSeurat()` from [Seurat.utils](https://github.com/vertesy/Seurat.utils/). Please take to heart what @mojaveazure said. May give you headache if using out after you created other slots in the object.
> 
> ```r
> # RenameGenesSeurat  ------------------------------------------------------------------------------------
> RenameGenesSeurat <- function(obj = ls.Seurat[[i]], newnames = HGNC.updated[[i]]$Suggested.Symbol) { # Replace gene names in different slots of a Seurat object. Run this before integration. Run this before integration. It only changes obj@assays$RNA@counts, @data and @scale.data.
>   print("Run this before integration. It only changes obj@assays$RNA@counts, @data and @scale.data.")
>   RNA <- obj@assays$RNA
> 
>   if (nrow(RNA) == length(newnames)) {
>     if (length(RNA@counts)) RNA@counts@Dimnames[[1]]            <- newnames
>     if (length(RNA@data)) RNA@data@Dimnames[[1]]                <- newnames
>     if (length(RNA@scale.data)) RNA@scale.data@Dimnames[[1]]    <- newnames
>   } else {"Unequal gene sets: nrow(RNA) != nrow(newnames)"}
>   obj@assays$RNA <- RNA
>   return(obj)
> }
> # RenameGenesSeurat(obj = SeuratObj, newnames = HGNC.updated.genes)
> ```
> 
> *Edit: bug fixed, sry.

Hi @vertesy, changing the `obj@assays$ADT@counts@Dimnames[[1]]` does not change also the `rownames(obj` unfortunately. You have a workaround?

**Comment by erzakiev** [comment]
The strategy of 

> modifying the expression matrix before creating the Seurat object.

would have worked great if you didn't find out that you had wrong gene names in your Seurat object of 150k cells and 20Gb of size until after spending a couple of hours of cluster time to run `SCTransform` on it.

**Comment by vertesy** [comment]
In Seurat v5 the way data is stored differently, so now it is way more complicated to achieve this. An experimental solution is implemented in `Seurat.utils::RenameGenesSeurat()`
> which actually calls `Seurat.utils:::.check_and_rename()` which has the major change)
