### ISSUE TITLE
PCHeatmap subscript out of bounds

### ISSUE THREAD

**Issue by s18692001** [satijalab/seurat#105]
Hi there,

I follow the PBMC tutorial with my own 10X single cell dataset. When I use the following command:
```R
> PCHeatmap(object = pbmc, pc.use = 1, cells.use = 500, do.balanced = TRUE, label.columns = FALSE)
```
It shows:
`Error in sx[1:num.genes, , drop = FALSE] : subscript out of bounds``

Do you have any suggestion? Thanks!

**Comment by s18692001** [comment]
Does any one have advice about this issue? Thanks!

**Comment by pesho-ivanov** [comment]
Seems that you have less than 500 cells in your set. Try not specifying cells.use.
