### ISSUE TITLE
Integration of ADT and RNA data from the same cells

### ISSUE THREAD

**Issue by asigore** [satijalab/seurat#1050]
Dear Seurat team,
I'm thrilled with the release of v3! specially with the multimodal data integration capability. 
When integrating data from different assays (CITE-seq), is there a way to specify that the data has been collected from the same cells (RNA and ADT)? i.e. is cell name considered when anchoring the data? if so, is keeping identical cell names in both datasets sufficient to accomplish this? 
Thanks!
Ana

**Comment by mojaveazure** [comment]
Hi Ana,

Seurat v3's multimodal capabilities are indeed anchored around cell names, and the Seurat object will enforce identical cell naming when adding additional assays (eg. adding ADT information to an object with RNA data) to the object. Ensuring that your datasets have identical cell names and number (we currently do not allow for assays to be missing cells) is good enough, Seurat will take care of the rest.

See the "Multi-Assay Features" section of our [command cheat-sheet](https://satijalab.org/seurat/essential_commands.html) for examples of creating a multi-assay object.

**Comment by asigore** [comment]
Thank you Paul, 

That's great! Thanks for the quick response.

Ana

**Comment by asigore** [comment]
Hello Seurat team, 
I have a follow up question regarding the integration of ADT and RNA data from the same cells. But I'm unsure how to achieve this with the new integration methods.
I want to be able to perform joint clustering on proteins and transcripts, for which I'll need a merged matrix of CLR normalized ADT and log normalized RNA counts. I understand ADT won't have as many dropouts as the RNA seq, so I'm not sure if a the ADT signal needs to be scaled accordingly. Is this achieved by just running CCA on the normalized data for both assays? If so, how does Seurat handle the different feature names for ADT and RNA. 
Any help would be appreciated. Thanks, 
Ana

**Comment by PDBio** [comment]
Dear Ana,
did you find a solution for this last request yet?
Best,
Philipp
