### ISSUE TITLE
JackStraw do.par removed in v3?

### ISSUE THREAD

**Issue by nasqar** [satijalab/seurat#1054]
am using Seurat_3.0.0.9000
was JackStraw do.par removed? because I am getting:
`unused argument (do.par = T)`

appreciate your help.

**Comment by mojaveazure** [comment]
Hi @nasqar,

All multi-threading in Seurat has been replaced by [futures](https://github.com/HenrikBengtsson/future). This means that you can enable multithreading via the `plan` function from future. We will release a list of all functions that use futures soon.
