### ISSUE TITLE
TransferData Visualization Question

### ISSUE THREAD

**Issue by ejdeg** [satijalab/seurat#1055]
For your Integration and Label Transfer vignette, how would you visualize all cells (ie. UMAP or tSNE projection) after using TransferData for the fluidigmc1 data? (under section: Cell type classification using an integrated reference)

**Comment by timoast** [comment]
If you want to visualize the FluidigmC1 cells in 2D space you can run UMAP or tSNE on the FluidigmC1 object, and color the cells by their predicted label.

If you want to visualize the FluidigmC1 cells together with cells from the other technologies, you should integrate the objects (see first section of https://satijalab.org/seurat/pancreas_integration_label_transfer.html), then run UMAP or tSNE on the integrated object.
