### ISSUE TITLE
Is it possible to visualise gene expression across cell types and conditions in one plot with Seurat, in Single Cell Sequencing data ?

### ISSUE THREAD

**Issue by charlesgwellem** [satijalab/seurat#1059]
I am new to single cell sequencing data analysis but I have basic programming background in R and python. I want to be able to plot differential expression of two genes, Gene1 and Gene2, across three cell types and across three conditions on one plot. I have followed this tutorial: https://satijalab.org/seurat/pbmc3k_tutorial.html to perform QC and various differential analyses using Seurat package on my data up till now.

My data set is one object, containing information about the three cell types under three various conditions. The metadata slot of my data set contains information about my cell types as well as the conditions under which they are tested. Using the following DotPlot commands I am able to generate separate plots of gene expression with respect to cell type and with respect to condition:
```
Seurat::DotPlot(object = object, genes.plot = c("Gene1", "Gene2"), plot.legend = TRUE, group.by = "cell_types")

Seurat::DotPlot(object = object, 
        genes.plot = c("Gene1", "Gene2"), plot.legend = TRUE, group.by = "tissue_types" )
```

However I wish to have information about gene expression across cell types and conditions on one plot. I will be very grateful for any hints on how I can proceed.
![question_best 1](https://user-images.githubusercontent.com/10155881/51145424-19c26300-1854-11e9-8cef-f3809e456295.png)

**Comment by timoast** [comment]
Hi Charles, I answered your question on stackexchange here: https://bioinformatics.stackexchange.com/questions/6806/visualising-gene-expression-across-cell-type-and-conditions-in-one-plot-in-sing
