### ISSUE TITLE
how I can make the same large  vlnplot pictures containing different features when exporting as pdf?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1061]
![image](https://user-images.githubusercontent.com/30619010/51162379-e07c0880-18d0-11e9-84ad-d84f3871b7d3.png)
the above picture shows my code to export vlnplot pictures, and the last row has different elements from other rows,how I can make the last two picture as large as others in the same pdf file? I tried ncol=5,nrow=2, but in the new version seurat3.0, it hasn't nrow command.
can anyone help me?
![image](https://user-images.githubusercontent.com/30619010/51162387-e671e980-18d0-11e9-93e9-321d6f8009e7.png)

**Comment by mojaveazure** [comment]
In Seurat v3, `VlnPlot` calls `CombinePlots` under the hood to combine multiple plots into a single image, which in turn calls [cowplot's `plot_grid`](https://www.rdocumentation.org/packages/cowplot/versions/0.9.4/topics/plot_grid). If you'd like greater control over how plots are arranged, pass `combine = FALSE` to the `VlnPlot` command and pass the resulting list to `CombinePlots`. `CombinePlots` will pass any extra arguments (`...`) to `plot_grid`, as well as allow easy legend management.

```R
plots <- VlnPlot(..., combine = FALSE)
CombinePlots(plots = plots, ...)
```
