### ISSUE TITLE
Seurat vs. Monocle

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#1063]
Dear All,

I would like to share with you a reviewer's comment of a recently submitted paper to a high impact factor journal.
All the analysis were done in Seurat with very nice results, a major issue was this:

> This could be done in Monocle or other bioinformatic tools that have been become available. The computational tools used here are fairly straight-forward, but deeper investigations could yield interesting findings.

Do you agree?  is like Seurat nowadays considered a simple way to analyze data?

Many Thanks,
Paolo

**Comment by satijalab** [comment]
Haters gonna hate

**Comment by paolo-kunderfranco** [comment]
Il giorno mar 22 gen 2019, 02:07 satijalab <notifications@github.com> ha
scritto:
