### ISSUE TITLE
logTPM could be applied to cell cycle scoring?

### ISSUE THREAD

**Issue by Cheryl312518** [satijalab/seurat#1064]
Hi, everyone. Here's a question.

I applied log((TPM/10)+1) to the expression level of each gene per cell. The code is written below.
`a <- apply(Sample1@data,2,sum)`
`Sample1@data <- as(as.matrix(log2(Sample1@data/a*100000+1)), "dgCMatrix")`

But could I still use Seurat function `CellCycleScoring` and `ScaleData` to achieve Cell-Cycle Scoring and Regression?  I mean the method logTPM is different from Seurat `NormalizeData(object = pbmc, normalization.method = "LogNormalize", scale.factor = 10000)`. The cutoff to estimate the cell cycle score should be adjusted? Otherwise, could you please provide another method to regress out?

Thank you very much.

**Comment by satijalab** [comment]
Apologies for the slow reply. Yes you can absolutely use CellCycleScoring based on custom normalization. Scores are determined based on the relative expression levels of different gene sets, and we do not enforce specific cutoffs
