### ISSUE TITLE
Is num.cores option available for ScaleData in 3.0.0.9?

### ISSUE THREAD

**Issue by rlittman16** [satijalab/seurat#1065]
Hello,

I am using Seurat v 3.0.0.9000, and would like to know if the num.cores option is available in this version. I am using ScaleData, with this parameter set and it does not throw an error, but does not seem to be increasing speed at all. 

Here is the command I am running:
Hip.seurat <- ScaleData(object = Hip.seurat, features = rownames(x = Hip.seurat), vars.to.regress = c("nCount_RNA", "percent.mito"), do.par = TRUE, num.cores = 12)

Thank you in advanced!

**Comment by timoast** [comment]
Hi, please see #1027
