### ISSUE TITLE
Subsetting with external cluster information

### ISSUE THREAD

**Issue by hkarakurt8742** [satijalab/seurat#1067]
Hello,
I am using Seurat for scRNA-Seq data analysis and I used different methods for clustering on data matrix. I want to subset the data according to specific clusters of my cluster. I assigned the new cluster information to object@meta.data section. Plots with this cluster information are looking fine and I do not have an errors while grouping.
But I could not manage to Subset the data with my cluster information. 
When I use WhichCells function as like this (I need to subset Cluster 12):

length(WhichCells(object = data.integrated, ident = data.integrated@meta.data$optimal[[12]]))

I have the value, 117 which is wrong. 
How can I subset the data according to a specific information in the object@meta.data section.

Thank you.

**Comment by timoast** [comment]
Here's an example using the `pbmc_small` dataset, extracting cells from cluster 1:

```r
pbmc_small <- SetAllIdent(pbmc_small, 'res.1')
cluster1 <- SubsetData(object = pbmc_small, cells.use = WhichCells(pbmc_small, ident = 1))
```

**Comment by hkarakurt8742** [comment]
Thank you so much. Apparently I did not use SetAllIdent() function.
