### ISSUE TITLE
multi-sample intergration analysis in seurat V2 vs V3

### ISSUE THREAD

**Issue by maqueredkop** [satijalab/seurat#1069]
Hi Seurat team,
    I want to analysis multi-sample which contains two group of scRNA-seq , I found that in seurat 2, there has AlignSubspace() method to merge and intergration the dataset.  But in V3 I don't find AlignSubspace()  method , so I wonder if seurat have used FindTransferAnchors() and IntegrateData() method  as a substitute for AlignSubspace() ?  
   Thank you!

**Comment by timoast** [comment]
Hi, you can find out more about the integration methods in Seurat v3 in our recent preprint: https://www.biorxiv.org/content/early/2018/11/02/460147 
and through our vignette: https://satijalab.org/seurat/pancreas_integration_label_transfer.html

**Comment by maqueredkop** [comment]
Thanks a lot , I will try to learn about that !

**Comment by yycunc** [comment]
Hi Seurat team,
What if I want to do integration analysis for two scRNA-seq datasets and one scATAC-seq dataset?
Can I do the analysis for all the sample together or integrated the two scRNA-seq data first and then do the scATAC-seq data?
Thanks!
