### ISSUE TITLE
FindClusters iterations

### ISSUE THREAD

**Issue by djchin25** [satijalab/seurat#107]
Previously with version 1.4.0.16, i would run several resolution values (both on Linux and MacOSX)

After installing the new 2.0.0 version on a Mac laptop with R-3.4.1, the new PrintFindClustersParams only returns the first resolution factor. Then i noticed that an error when re-running FindClusters: Warning messages:
1: In BuildSNN(object = object, genes.use = genes.use, reduction.type = reduction.type,  :
  Build parameters exactly match those of already computed and stored SNN. To force recalculation, set force.recalc to TRUE.

But passing force.recalc=TRUE does not remedy the issue. Looking at the FindClusters function, it calls BuildSNN which is passed force.recalc=FALSE by default, not a variable passed by FindClusters when force.recalc=TRUE.

I tried changing the BuildSNN function to take a passed variable, but got errors about missing functions CalcInfoExists and SetCalcParams.

**UPDATE**: when i set save.SNN = FALSE in the FindClusters call, i don't get the above error, but the PrintFindClustersParams function still returns the first resolution value

**UPDATE2** i think the PrintFindClustersParams function is broken because all resolution factors are stored in sdat@calc.params; e.g. my last value was 1.2
 $FindClusters.res.1.2$resolution

**Comment by andrewwbutler** [comment]
There is an argument in PrintFindClustersParams to specify the resolution. It will default to the first one but you can specify whichever. 

The warnings you are seeing are just letting you know that you've stored the SNN and it's not recalculating it. We're probably being a little too verbose on the output here but it's not an error and can be ignored if you're just running the different resolutions over the same SNN graph.

**Comment by djchin25** [comment]
Thanks for the response. If Seurat2 is storing all tested parameters, how does one know which was the last, preferred value that was used?

**Comment by lizc07** [comment]
I will always get a returned object using FindClusters function, even if object@dr is a null 'list()'.
Seems like that BuildSNN function was never called!

**Comment by djchin25** [comment]
@lizc07 - that was my experience too- BuildSNN by default has force.recalc set to FALSE and is not passed a variable when FindClusters calls BuildSNN.  But modifying both FindClusters and BuildSNN led me to a rabbit hole with errors with missing functions CalcInfoExists and SetCalcParams.

**Comment by lizc07** [comment]
It's a pity. I have to go back to Seurat v1.4 before this bug being fixed.
