### ISSUE TITLE
splitdotplotGG Error in mutate_impl(.data, dots)

### ISSUE THREAD

**Issue by doctorjb77** [satijalab/seurat#1072]
Getting following error message with splitdotplotGG 

Error in mutate_impl(.data, dots) : 
  Evaluation error: subscript out of bounds.

Looked at similar issue #578 from before, but no underscores present in object/cluster names. 
https://github.com/satijalab/seurat/issues/578

Would appreciate any insight. Thanks

> traceback()
13: stop(list(message = "Evaluation error: subscript out of bounds.", 
        call = mutate_impl(.data, dots), cppstack = NULL))
12: .Call(`_dplyr_mutate_impl`, df, dots)
11: mutate_impl(.data, dots)
10: mutate.tbl_df(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey", 
        palette.use))(20)[avg.exp.scale])
9: mutate(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey", 
       palette.use))(20)[avg.exp.scale])
8: function_list[[i]](value)
7: freduce(value, `_function_list`)
6: `_fseq`(`_lhs`)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
2: data.to.plot %>% separate(col = id, into = c("ident1", "ident2"), 
       sep = "_") %>% rowwise() %>% mutate(palette.use = colorlist[[ident2]], 
       ptcolor = colorRampPalette(colors = c("grey", palette.use))(20)[avg.exp.scale]) %>% 
       unite("id", c("ident1", "ident2"), sep = "_")
1: SplitDotPlotGG(object = HFD.combined, genes.plot = rev(markers.to.plot), 
       cols.use = c("blue", "red"), x.lab.rot = T, plot.legend = T, 
       dot.scale = 8, do.return = T, grouping.var = "stim")

**Comment by rebeccagj** [comment]
Having a perhaps similar issue, would love any assistance.

```
> SplitDotPlotGG(totalcells_combined, 
+                grouping.var = 'orig.ident',
+                cols.use = c("gray26","deepskyblue"),
+                genes.plot = percentsGenes, 
+                x.lab.rot = T,
+                plot.legend = T,
+                dot.scale = 8)
Error in colorlist[[ident2]] : subscript out of bounds
In addition: Warning message:
Expected 2 pieces. Additional pieces discarded in 336 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].

> traceback()
11: mutate_impl(.data, dots, caller_env())
10: mutate.tbl_df(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey", 
        palette.use))(20)[avg.exp.scale])
9: mutate(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey", 
       palette.use))(20)[avg.exp.scale])
8: function_list[[i]](value)
7: freduce(value, `_function_list`)
6: `_fseq`(`_lhs`)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
2: data.to.plot %>% separate(col = id, into = c("ident1", "ident2"), 
       sep = "_") %>% rowwise() %>% mutate(palette.use = colorlist[[ident2]], 
       ptcolor = colorRampPalette(colors = c("grey", palette.use))(20)[avg.exp.scale]) %>% 
       unite("id", c("ident1", "ident2"), sep = "_")
1: SplitDotPlotGG(totalcells_combined, grouping.var = "orig.ident", 
       cols.use = c("gray26", "deepskyblue"), genes.plot = percentsGenes, 
       x.lab.rot = T, plot.legend = T, dot.scale = 8)
```

I also have no underscores present in object/cluster names.

**Comment by timoast** [comment]
Hi, sorry for the delay here, I'm going to close this issue as SplitDotPlotGG has been rewritten in version 3. If you encounter the same error using the latest version of Seurat, please open a new issue
