### ISSUE TITLE
How to set the order of groups in a Seurat object on a FeatureHeatmap plot

### ISSUE THREAD

**Issue by charlesgwellem** [satijalab/seurat#1073]
I am analysing singe cell sequence data and I have followed this tutorial,[tutorial](` https://satijalab.org/seurat/pbmc3k_tutorial.html`) to perform QC and various differential analyses using the Seurat package on my data up till now.

How can I rearrange on the resulting plot, the order in which the groups of my samples appear when I use the `FeatureHeatmap()` function to visualise the differential gene expression of Gene1 and Gene2 across the cell clusters?

```
FeatureHeatmap(object = object, features.plot = c("Gene1", "Gene2"), 
               group.by = "Conditions",
               pt.size = 0.25, key.position = "top",
               max.exp = 3)
```
produces: 
![wrong order](https://user-images.githubusercontent.com/10155881/51388604-4adbb580-1b2a-11e9-98ed-3dffe1c21c39.png)

instead of:
![rightorder](https://user-images.githubusercontent.com/10155881/51388624-55964a80-1b2a-11e9-829e-97596579e604.png)

**Comment by timoast** [comment]
Hi Charles, I answered this question on stackexhange: https://bioinformatics.stackexchange.com/questions/6838/how-to-set-the-position-of-groups-in-a-seurat-object-on-a-featureheatmap-plot/6840#6840
