### ISSUE TITLE
FindAllMarkers for pairwise analysis

### ISSUE THREAD

**Issue by tomallison24** [satijalab/seurat#1075]
Is there a way to use the findallmarkers function but instead of cluster vs all others, for all combinations of pairwise cluster analysis?

**Comment by timoast** [comment]
There isn't an inbuilt way to do this, but you could iterate over all pairwise comparisons using `FindMarkers`. For example:

```r
library(Seurat)

clusters <- unique(Idents(pbmc_small))
pairwise <- combn(clusters, 2)

results <- list()
for(i in 1:ncol(pairwise)) {
    markers <- FindMarkers(pbmc_small, ident.1 = pairwise[1, i], ident.2 = pairwise[2, i])
    results[[i]] <- markers
}
```

**Comment by tomallison24** [comment]
Hi Tim,

Thanks very much for your reply! I am getting an error for Idents, saying
it cannot find the function. Is it part of Seurat as I do have it loaded.

T

**Comment by timoast** [comment]
`Idents` is part of Seurat v3, if you're using v2 just use `object@ident` instead

**Comment by tomallison24** [comment]
I see perfect thanks, works!! One last thing, the results are saved as a
list, how can I get that into a table/data frame format? I have tried
as.data.frame etc but it just gives header names instead of the full set of
details done by the diff exp.

Thanks again for your help

T

**Comment by timoast** [comment]
Hi Tom, you can bind the dataframes using `do.call`, like this:

```r
library(Seurat)

clusters <- unique(pbmc_small@ident)
pairwise <- combn(clusters, 2)

results <- list()
for(i in 1:ncol(pairwise)) {
  markers <- FindMarkers(pbmc_small, ident.1 = pairwise[1, i], ident.2 = pairwise[2, i])
  comparisons <- pairwise[, i]
  markers$comparison <- paste(comparisons[1], comparisons[2], sep = '_')
  results[[i]] <- markers
}

results.df <- do.call(rbind, results)
```

**Comment by tomallison24** [comment]
Hey Tim,

Thank you for the code. It works, although there is a problem. For the
pairwise the same genes can appear between groups, and it seems to be
adding numbers to the ends of the genes. For e.g., the gene VIM comes up as
diff exp between cluster 1+3, 1+4 and 2+6. It therefore annotates the first
VIM as VIM, the second as VIM2 and the third as VIM3. Is there a way to
prevent this from happening so that they are all just called VIM?

Thanks

T

**Comment by timoast** [comment]
You can add the gene name as a extra column before binding all the rows together, add this to the for loop: `markers$gene <- rownames(markers)`
