### ISSUE TITLE
Suerat version 3 SetAllIdent not found

### ISSUE THREAD

**Issue by hejing3283** [satijalab/seurat#1076]
I installed the most recent version and could not find this function "SetAllIdent". Is there a replacement for it?

**Comment by timoast** [comment]
`SetAllIdent` has been replaced with `Idents` in Seurat v3. See here for more information on transitioning from v2 to v3: https://satijalab.org/seurat/essential_commands.html

Example:
```r
Idents(object = object) <- "new.idents"
```
