### ISSUE TITLE
Issue with VlnPlot and JoyPlot when plotting genes that start with a number

### ISSUE THREAD

**Issue by FloWuenne** [satijalab/seurat#108]
Hi Seurat devs,

I recently ran into this issue after updating to Seurat v2. This never occurred with the previous Seurat version so I am suspecting some minor change in the code for VlnPlot and JoyPlot to be responsible.

I get the following error when trying to plot multiple marker genes via VlnPlot or JoyPlot. Strangely the same markers plot fine when using FeaturePlot. The error is the following:

Error in `[.data.frame`(data.use, , x, drop = FALSE) : 
  undefined columns selected

I narrowed the error down to be potentially related only to genes that start with a number, such as "2900055J20Rik" but couldn't find the specific instance of the VlnPlot call that causes the error. I think it is in this snippet but that is as far as I got:

plots <- lapply(X = features.plot, FUN = function(x) {
        return(SingleVlnPlot(feature = x, data = data.use[, x, 
            drop = FALSE], cell.ident = ident.use, do.sort = do.sort, 
            y.max = y.max, size.x.use = size.x.use, size.y.use = size.y.use, 
            size.title.use = size.title.use, adjust.use = adjust.use, 
            point.size.use = point.size.use, cols.use = cols.use, 
            gene.names = gene.names, y.log = y.log, x.lab.rot = x.lab.rot, 
            y.lab.rot = y.lab.rot, legend.position = legend.position, 
            remove.legend = remove.legend))

I routinely plot the X best markers for multiple clusters via loops and ran into this problem during some standard analysis. For now I can circumvent it by excluding genes that start with a number but it would be nice to fix this in the future. 

I am running Seurat v2.0.0 in RStudio 1.0.143 with R 3.4.0 on Ubuntu 16.04.

Thanks for the support,
Best,

Florian

**Comment by FloWuenne** [comment]
Sorry I forgot to include an actual example. So let's say I ran FindAllMarkers on my object and I would then like to ploy my 4 best markers for a specific cluster. 

VlnPlot(object = expression_seurat,
          features.plot = c("Pcp4","Rprm","Hs3st4","3110035E14Rik"),
          single.legend=TRUE,
          point.size.use = -1,
          x.lab.rot = TRUE
          )

Would give me the error as described above. JoyPlot will give the same error, while FeaturePlot will correctly plot the four markers

**Comment by efheuston** [comment]
Hi! I would also like to add to this issue. I can not get VlnPlot to plot genes with "-" in them (e.g., Hbb-bt). 

VlnPlot(ms.tsne,features.plot = "Hbb-bt")

I get the same error as described above.

Error in `[.data.frame`(data.use, , x, drop = FALSE) : 
  undefined columns selected

Thanks for your help!

E

**Comment by andrewwbutler** [comment]
This should be fixed in the develop branch. You'll have to install it from source (`install_github("satijalab/seurat", ref = "develop")` but it should handle gene names that start with numbers or contain dashes.
