### ISSUE TITLE
UMAP clusters mixed with cells from different clusters

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#1081]
Hi,

I am using UMAP for visualizing the clusters on Seurat 2.3.4. As you can see from this attached plot, there are some cells from a different cluster coming into a distinct cluster e.g. 2 cells from cluster 3 in cluster 9. Is this normal or there are some parameters that need to be fixed. This is the code that I am running.
MCF7_cells_combined <- RunUMAP(object = MCF7_cells_combined, reduction.use = "pca", dims.use = 1:30, n_neighbors = 15, min_dist = 0.1)

Thanks,

Bibaswan
![umap_clusters](https://user-images.githubusercontent.com/11318165/51551726-0fe4c500-1e3d-11e9-84a5-0eb832cc3412.png)

**Comment by timoast** [comment]
Can you also post the full code you used to generate the clusters?

**Comment by ghoshal** [comment]
Hi,

Here is the full code.

MCF7_cells_combined <- ScaleData(object = MCF7_cells_combined, vars.to.regress = "nUMI")


MCF7_cells_combined <- RunPCA(object = MCF7_cells_combined, pc.genes = rownames(MCF7_cells_combined@data), do.print = TRUE, pcs.print = 1:5, 
                          genes.print = 5, pcs.compute = 50)

MCF7_cells_combined <- AlignSubspace(object = MCF7_cells_combined, reduction.type = "pca", grouping.var = "class", 
                                 dims.align = 1:30)

MCF7_cells_combined <- FindClusters(object = MCF7_cells_combined, reduction.type = "pca", dims.use = 1:30, algorithm = 3,
                                resolution = 1.2, print.output = T, save.SNN = T, force.recalc = T)

**Comment by timoast** [comment]
I suggest setting `k.param` in FindClusters to 15, to match the k you used in RunUMAP (or set `n_neighbors=30L` in RunUMAP). You might also try setting `metric = 'euclidean'` in RunUMAP to use euclidean distance rather than correlation distance (the default).

**Comment by ghoshal** [comment]
I tried multiple combinations of the same and this problem still persists.

**Comment by dpcook** [comment]
Try FindClusters() with `reduction.type="cca.aligned"` instead of pca. Your UMAP embedding is based on the aligned data, but you're clustering on unaligned data

**Comment by timoast** [comment]
In Seurat v3, we have separate clustering into two steps: FindNeighbors, which builds the SNN graph, and FindClusters, which runs community detection on the graph. We also have an option in RunUMAP to use a pre-computed graph, so you could try running UMAP on the same graph use for clustering, for example:

```r
pbmc_small <- FindNeighbors(pbmc_small, dims = 1:10)
pbmc_small <- FindClusters(pbmc_small, graph.name = 'RNA_snn')
pbmc_small <- RunUMAP(pbmc_small, graph = 'RNA_snn')
```

Beyond this, I think any differences are really due to differences between clustering and UMAP, and is beyond the scope of the Seurat package and so I will close this issue.
