### ISSUE TITLE
Cluster mutant cells onto wildtype clusters

### ISSUE THREAD

**Issue by stephenchea** [satijalab/seurat#1083]
I have two types of cells: wildtype and mutant. I want to cluster the wildtype cells on their own, and then cluster the mutant cells onto the wildtype clusters. I know how to cluster the wildtype cells by themselves, but how do I go about determining which wildtype cluster each mutant cell belongs to?

**Comment by timoast** [comment]
Hi, you might be interested in the data transfer methods in Seurat v3. See the vignette here: https://satijalab.org/seurat/pancreas_integration_label_transfer.html and our preprint here: https://www.biorxiv.org/content/early/2018/11/02/460147

**Comment by stephenchea** [comment]
After transferring the labels from the reference cells onto the query cells, how do I generate a tSNE plot with all the cells together? According to the vignette, the reference and query cells are stored in different objects.
