### ISSUE TITLE
Integration in Seurat v3.0 of HCA Bone marrow data

### ISSUE THREAD

**Issue by AMA111** [satijalab/seurat#1084]
Hey Seurat team, 

I am wondering which level did you use for integrating the bone marrow samples of the HCA data at your latest preprint: https://www.biorxiv.org/content/early/2018/11/02/460147
Did you use the (donor label or the sample level )as the integration reference.list?

Also, at the supplementary of same preprint (Figure S6. HCA data integration): 
It is mentioned that the Visualization of HCA scRNA-seq datasets (8 donors) without integration reveals the presence of systematic differences across donors. What do you mean here by systematic differences across donors? And what are the sources of these systematic differences? Could be these differences are real biological signals which are reflecting the differences between the donors?

Thank you for your help. 

Best,
Abdelrahman

**Comment by AMA111** [comment]
Hey, thank you for your answer. To which extend do we have the ability to identify the differences between what is technical either biological difference; as through the integration procedure; we could actually hide interesting biological signals, especially if we use this method in the context of heterogeneous tumour samples for example. Do you suggest a way to address this issue? 
Thanks again!

**Comment by satijalab** [comment]
You can examine differences across donors after integration, by performing DE on the uncorrected data. It is easy to do this in Seurat v3 by switching between the corrected and original (RNA) assays.

While we don't discuss it in the manuscript, we see that to some extent, T cell populations in the HCA dataset differ in their activation of stress responses. It is unclear whether this was true in situ, or rather, an artifact of dissociation - and follow-up experiments would be necessary to distinguish.
