### ISSUE TITLE
Different cluster results with different orders of samples

### ISSUE THREAD

**Issue by semir2** [satijalab/seurat#1085]
Hi,
thanks for developing Seurat. Great tool!
I run seurat whith multiple_pancreas_workflow for 10xGenomics samples. I have a proble that we get different cluster results with different orders of samples and  with the same settings. I could not understat, why?

Best Wishes

**Comment by andrewwbutler** [comment]
Hi,

Could you provide the code you ran that gave different results?

**Comment by timoast** [comment]
Hi, sorry for the delay in response here but I will close this issue for now as we are no longer developing v2
