### ISSUE TITLE
Find Marker Genes based on Expression of Transgenic Genes

### ISSUE THREAD

**Issue by SyrupBadger** [satijalab/seurat#1086]
Hi,

I am very new to coding / bioinformatics in general so apologies if some of my questions are very naive. 
 I have a single cell data set that was generated from transgenic cells that express either GFP only or GFP and tdTom.  These two main populations are similar cell types, very heterogeneous and form distinct and  overlapping clusters.  What I would like to do  first is to find general markers that identify the GFP and GFP and tdTom populations (individual cluster markers will be investigated later).  I initially subsetted the data based on tdTom expression using the following:

Found which line my gene of interest was on
`grep("tdTom", row.names(Exp@data), value = FALSE)`

I made a dataframe to house the metadata I'm interested in
`sample.info<- data.frame(cell.names = Exp@cell.names)` 

I added a column for pos/neg expressing cells
`sample.info$tdTom = `"Neg"`
`sample.info$tdTom[which(Exp@data[row.names(Exp@data)[12745], ] != 0)] <- "Pos"`

I then made the cell barcodes the rownames and I also converted the actual cell barcode column to character' 
`row.names(sample.info) <- sample.info$cell.names`
`sample.info$cell.names <- as.character(sample.info$cell.names)`

I added the new sample info to the object metadata
`Exp <- AddMetaData(object = Exp, metadata = sample.info)`
`Exp <- SetAllIdent(object = Exp, id = "tdTom")`

I then subsetted the data based on pos or neg expression of tdTom
`tdTomPos.subset <- SubsetData(object = Exp, ident.use = "Pos")`
`tdTomNeg.subset <- SubsetData(object = Exp, ident.use = "Neg")`

However, I have been unable to use the FindMarkers() function to compare the two subsets.  To try and address this I merged the two subsets back into a new Seurat object (tdTom.Exp).  The pos and neg information was kept during the merge but is stored under meta.data in a tdTom column and is not present in the ident section of the Seurat object.

When I use the FindMarkers function on this new object I receive an error saying that Pos / neg could not be found

`tdTom.Markers<-FindMarkers(object = tdTom.Exp, ident.1 = Pos, ident.2 = Neg, min.pct = 0.25)`

I have also tried:

`tdTom.Markers<-FindMarkers(object = tdTom.Exp, ident.1 = tdTom.Exp@meta.data$tdTom["Pos"], ident.2 = tdTom.Exp@meta.data$tdTom["Neg"], min.pct = 0.25)`

Is there anyway to broadly self define two clusters based on the expression of a transgenic gene and to then compare the gene expression between these two broad populations before going into more in-depth analysis looking at the clustering?

Thanks

Fraser

**Comment by andrewwbutler** [comment]
Hi Fraser,

It sounds like you were able to create a meta.data column specifying positive vs negative. In the merged object (`tdTom.Exp`), you need to set the ident to the name of that meta.data column before using `FindMarkers`. Also, in the `FindMarkers` call, make sure to have "Pos" and "Neg" in quotes.
