### ISSUE TITLE
how to access jackstraw results

### ISSUE THREAD

**Issue by rvalieris** [satijalab/seurat#109]
Hello,

the docs on the JackStraw function, says:
```
     Returns a Seurat object where object@jackStraw.empP represents
     p-values for each gene in the PCA analysis.
```

but I can't find any `obj@jackStraw*` data on the object after running the function.
I want to access the pvalues of the components.

**Comment by leonfodoulian** [comment]
Hello, 

You can run the following to obtain what you're looking for:
```
> object@dr$pca@jackstraw@emperical.p.value
> object@dr$pca@jackstraw@fake.pc.scores
> object@dr$pca@jackstraw@emperical.p.value.full
```

Nevertheless, the last code returns

```
> object@dr$pca@jackstraw@emperical.p.value.full    
     [,1]
[1,]   NA
```
even if I run `ProjectPCA()` (see [lines 15 to 17 of jackstraw.R](https://github.com/satijalab/seurat/blob/master/R/jackstraw.R#L15-L17)). I didn't yet figure out why.

Best,
Leon

**Comment by rvalieris** [comment]
thanks Leon, I got it !

**Comment by brianpenghe** [comment]
> Hello,
> 
> You can run the following to obtain what you're looking for:
> 
> ```r
> > object@dr$pca@jackstraw@emperical.p.value
> > object@dr$pca@jackstraw@fake.pc.scores
> > object@dr$pca@jackstraw@emperical.p.value.full
> ```
> 
> Nevertheless, the last code returns
> 
> ```r
> > object@dr$pca@jackstraw@emperical.p.value.full    
>      [,1]
> [1,]   NA
> ```
> 
> even if I run `ProjectPCA()` (see [lines 15 to 17 in jackstraw.R](https://github.com/satijalab/seurat/blob/master/R/jackstraw.R#L15-L17)). I didn't yet figure out why.
> 
> Best,
> Leon

object@dr$pca@jackstraw@emperical.p.value

gives a matrix of p-values.
But how was the p-value of a specific PC calculated, labeled in each subfigure?

Thanks

**Comment by chansigit** [comment]
The Jackstraw accession method doesn't work for v3, any updates?

**Comment by chansigit** [comment]
For seurat v3, 
(object[["pca"]]@"jackstraw")$overall.p.values

other slots :
     'empirical.p.values' 'fake.reduction.scores' 'empirical.p.values.full' 'overall.p.values'

**Comment by Drosophilist** [comment]
> ives a matrix of p-values.
> But how was the p-value of a specific PC calculated

Hello @brianpenghe ! Did you manage to find the answer for your question?
