### ISSUE TITLE
Seurat_3.0.0.9000 Finding DEG with replicates and different conditions

### ISSUE THREAD

**Issue by tiagu** [satijalab/seurat#1091]
Hi,

I am analysing an experiment consisting of control samples (2 replicates) versus treatment/ perturbation (2 replicates), so a total of 4 datasets. 
Although the differences control vs treatment will probably be small, I didn't want to rule out the appearance of different cell populations or changes in proportions.

**Q1:** Is the new Seurat v3 multi-dataset integration pipeline the best for this particular case? 
I have also tried the query method mentioned in the paper with one replicate of the treatment condition as query and the 2 control replicates as reference. It was unclear how to put all the data together using query though so I decided to integrate all 4 datasets from the start (code below) to have a single UMAP plot which would be much simpler and easier to highlight the same populations across replicates and conditions. Is this correct or would you recommend other way?

`reference.list <- list(control_rep1, control_rep2, treatment_rep1, treatment_rep2)`

`data.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30, verbose = TRUE)`
`data.integrated <- IntegrateData(anchorset = data.anchors, dims = 1:30, verbose = TRUE)`
`DefaultAssay(object = data.integrated) <- "integrated"`

`#Then the standard workflow : ScaleData(), RunPCA(), FindNeighbors(), FindClusters() and RunUMAP().`

**Q2:** FindMarkers function performed great at unbiasedly finding the best known markers for each cell population. However, to find DEG between control and treatment cells the function was only looking at the 2000 genes from the 'vst' selection that were later integrated between the 4 datasets. This resulted in very few genes and many of the ones we empirically found before were not present. I found a way around it (code below) but unsure if the DEG found by the downstream methods are correct when used this way. Is there a function to widen the genes FindMarkers looks at? I am assuming the DEG methods implemented take either the raw UMI counts from 'RNA' or the log-transformed and that this will be correct. Could you advise? 

Many thanks,
Tiagu

`data.integrated@meta.data$clusters_condition <- paste( 
as.vector(data.integrated@meta.data$integrated_snn_res.0.5), 
as.vector(data.integrated@meta.data$condition), sep="_")`

`# find cell names in a given cluster for a particular condition (control/ treatment)`
`cells1<-row.names(data.integrated@meta.data[ which(d7.integrated@meta.data$clusters_condition == paste(cluster_id[i],"_control",sep = "")),])`
`cells2<-row.names(data.integrated@meta.data[ which(d7.integrated@meta.data$clusters_condition==paste(cluster_id[i],"_treatment",sep = "")),])`
  
`# use cell names above to find DEG genes across conditions using 'RNA' assay (looks at more genes than the 2000 from integrated vst)`
`de_genes <- FindMarkers(object = data.integrated,`
`                         ident.1 = cells1, # control, cluster i`
`                         ident.2 = cells2, # treatment, cluster i`
`                        min.diff.pct = -Inf, logfc.threshold = -Inf, assay = 'RNA',`
`                         min.pct = 0.1, test.use ="LR") #wilcox/ MAST`

**Comment by timoast** [comment]
Q1: In your case I assume you want to find DE genes within a cell type that change according to treatment, in which case you would first need to identify equivalent cell types in control and treatment groups. Whether you need to use the integration methods depends on whether your groups separate according to batch/condition, or if the cells are well mixed without performing any correction.

Q2: `FindMarkers` by default will search all genes, not only the variable genes. You are likely only seeing variable genes because you're running on the integrated assay and IntegrateData by default only corrects the variable genes (you can change this with the `features.to.integrate` parameter). We don't recommend searching for differentially expressed genes using the integrated data matrix, instead you can change the assay to the original, uncorrected data:
`DefaultAssay(object) <- "RNA"`.

**Comment by tiagu** [comment]
Hi Tim,
Thanks for the quick reply. Q2 is clear, I was not reverting back to 'RNA' the default assay. 
Regarding Q1, a t-SNE with control vs treatment separates these groups within a given cell type although Louvain still finds them as a single cluster - so that would not be too much of an issue. But when including replicates we see quite a batch segregation hence the need for integrating. Just wanted to make sure that adding both the treatment and control samples to the pipeline to create a reference is ok..

**Comment by timoast** [comment]
Yes, completely reasonable to integrate the treatment and control groups
