### ISSUE TITLE
Choice of the resolution parameter

### ISSUE THREAD

**Issue by Felix-Simon** [satijalab/seurat#1094]
Hi,

I am clustering a dataset of around 30,000 cells using different number of PCs and different values of resolution. I am assessing the resulting clusters with BuildClusterTree and AssessNodes, by checking how many nodes are bellow an OOBE of 0.05.

I was expecting that the total number of cluster would keep increasing with the resolution, but the number of nodes below 0.05 OOBE would start decreasing after a while, when there is no more "significant" or "biologicaly relevant" clusters to be found. However, the number of nodes below 0.05 OOBE also keeps increasing.

Do you know how to explain these results? Should I keep going after 30 resolution to see if the number of nodes below 0.05 OOBE starts to drop? 30 seems already very hight to me.

Best,
Félix

This is the number of clusters (x axis: number of PCs used, y axis resolution):
<img width="318" alt="clusters" src="https://user-images.githubusercontent.com/45236949/51759904-4c136200-2097-11e9-8fba-68a807e909d9.png">

This is the number of nodes below 0.05 OOBE:
<img width="316" alt="oobe" src="https://user-images.githubusercontent.com/45236949/51759982-7b29d380-2097-11e9-8c0d-864104715137.png">

**Comment by satijalab** [comment]
Apologies for the delay in responding, as its hard for us to advise on specific analytical issues on datasets we have not looked at ourselves. A resolution of 30 is indeed very high, and i would not suggest going over that. For almost all datasets, such a parameter setting would result in substantial overclustering. Its surprising to me that you are seeing such a low OOBE error as a result, are you also seeing differentially expressed genes between clusters? Unfortunately, the OOBE can only be used as a rough guide to automatically detect clusters that are highly similar, but may not be able to detect 'optimal' resolution parameter settings.
