### ISSUE TITLE
Project query onto reference dataset in Seurat v3

### ISSUE THREAD

**Issue by cjuagf** [satijalab/seurat#1095]
Hi,

I am wondering if it is possible to project a query onto a reference data set in Seurat v3? I have two reference libraries (combined as object 1), and four query libraries (combined as object 2). I was able to follow the pancreas vignette, but something very useful would be to project them together and see what clusters are different between them.

Is this possible to do?

**Comment by satijalab** [comment]
Yes, you can simply flip the reference and query arguments in Seurat, and you will project the structure of the query dataset onto the reference
