### ISSUE TITLE
Seurat v3 input matrices for monocle

### ISSUE THREAD

**Issue by cjuagf** [satijalab/seurat#1096]
Hi,

I was wondering if anyone has tried to use Monocle2 using input matrices derived from Seurat v3? I was able to do it before (with Seurat v2), but now I am not sure if I am doing it correctly.  Using the following input information, I was able to get Monocle2 to work:

```r
expr_matrix <- subset@assays$integrated[,names(subset@active.ident)]
sample_sheet = data.frame(row.names=colnames(expr_matrix),cluster=subset@active.ident, genotype=subset@meta.data$orig.ident)
gene_annotation <- data.frame(row.names=rownames(expr_matrix), gene_short_name=rownames(expr_matrix))

## create a new CellDataSet object
pd <- new("AnnotatedDataFrame", data = sample_sheet) 
fd <- new("AnnotatedDataFrame", data = gene_annotation) 
newData <- newCellDataSet(as(as.matrix(expr_matrix), "sparseMatrix"),phenoData = pd,featureData = fd,lowerDetectionLimit=0.5,expressionFamily=negbinomial.size())
```

Thanks!

**Comment by andrewwbutler** [comment]
Hi, 

We don't currently have an conversion function in v3 for Monocle but Monocle2 has a [function here](https://github.com/cole-trapnell-lab/monocle-release/blob/7df105006756801a305ff43321b26d289cd6e890/R/cds_conversion.R#L118-L264) to import v2 Seurat objects. You can check your code against that to ensure everything is going to the right place.

**Comment by timoast** [comment]
Hi, we are in the process of adding Seurat -> Monocle conversion and it will be available soon (see https://github.com/satijalab/seurat/pull/1241)

**Comment by HomairaH** [comment]
Is the v3 -> Monocole conversion available?

**Comment by Sophia409** [comment]
@mojaveazure  Same question,Is the v3 -> Monocole conversion  available?
Recently monocle 3 has upgraded.And after I modify the code that is used to import seurat  object according to new new_cell_data_set function,it gave errors. Can you give me some help?Thank you very much.
>
> #262 how to import seurat object
> data <- Merge.integrated@assays$RNA@data
> cell_metadata <- new('AnnotatedDataFrame', data = Merge.integrated@meta.data)
> fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
> gene_metadata <- new('AnnotatedDataFrame', data = fData)
> #Construct monocle cds
> tdcds <-  new_cell_data_set(data,
> cell_metadata = cell_metadata,
> gene_metadata = gene_metadata
> )`

`Error in as.data.frame.default(from) : 
  cannot coerce class ‘structure("AnnotatedDataFrame", package = "Biobase")’ to a data.frame`
