### ISSUE TITLE
Error installing source package - 

### ISSUE THREAD

**Issue by kevinklee2003** [satijalab/seurat#11]
I am getting the following error trying to install Seurat directly from github in Rstudio.
I get the following error after entering the command 

**> install_github("satijalab/seurat")**

Downloading GitHub repo satijalab/seurat@master
from URL https://api.github.com/repos/satijalab/seurat/zipball/master
Installing Seurat
**Skipping 1 unavailable package: lfa
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \**
  '/private/var/folders/l9/7msqgpnx23zdzrg3kjfl4_h00000gr/T/Rtmphk6Gwh/devtools1cbd2bc20659/satijalab-seurat-ce16279'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library'  \
  --install-tests 

* installing *source* package ‘Seurat’ ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘lfa’
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Seurat’
Error: Command failed (1)

Apologies if this is a basic error I should be able to resolve on my own. I was installing/running the program fine until now. Any guidance appreciated!
-Kevin

**Comment by Puriney** [comment]
`there is no package called ‘lfa’ ` How about install `lfa` pkg first? See: https://www.bioconductor.org/packages/release/bioc/html/lfa.html

**Comment by natir** [comment]
I install https://github.com/StoreyLab/lfa first and I have no install problem

**Comment by andrewwbutler** [comment]
Issue should be fixed now.  I've updated the dependency handling so that if you run `source("https://bioconductor.org/biocLite.R")` before `install_github("satijalab/seurat")`, it should install without a problem.
