### ISSUE TITLE
Find k-nearest neighbors to aggreate counts from similar cells 

### ISSUE THREAD

**Issue by gouthamatla** [satijalab/seurat#1100]
Hi All,

I would like to know how to get the IDs of k-nearest neighbors from a seurat object ? Is there a in-build function that I could use to merge the data from 'k' nearest neighbors ? My goal is to reduce the sparsity of the data by merging cells and perform downstream analysis like clustering or co-expression analysis.

Do you have any other insights to performing co-expression analysis on scRNA data  ? to find cell-type specific co-expression modules ?

Thanks in advance.

**Comment by andrewwbutler** [comment]
Hi,

You can use the `FindNeighbors` function to compute the KNN graph for a Seurat object. However, there isn't a built in function for merging data as you describe. 

See #519 for one example of identifying highly correlated genes.
