### ISSUE TITLE
Multi integration vs tandem integration

### ISSUE THREAD

**Issue by DRLaks** [satijalab/seurat#1101]
Hello,
 When I do integration of 2 datasets and then repeat to add in a third, I get different results than when I do multi integration of all 3 datasets at once. Is there a reason one is better than the other? Is it correct to use the iteration method- the first method where I do 2 and then add in a third afterwards? 
  All the best,
                   Dan

**Comment by DHGK** [comment]
I'd like to know the differences, too

**Comment by satijalab** [comment]
Apologies for the slow response. There isn't a straightforward answer to this question. In  general we would suggest doing a single integration, but if you obtain better results with a tandem approach, it is not incorrect to do so.
