### ISSUE TITLE
Visualizing mutant cells after wildtype pc's are projected onto mutant cells

### ISSUE THREAD

**Issue by stephenchea** [satijalab/seurat#1102]
I've projected the pc structure of reference cells onto my query cells in order to classify the query cells into reference cell clusters. Is there a way to use the pc structure of the reference to visualize the spatial arrangement of the query cells and reference cells together in one single plot?

**Comment by satijalab** [comment]
We do have a `ProjectCellEmbeddings` function that can accomplish exactly this, however we don't have examples of precisely this analysis online. But if you look through the function you should be able to figure out how it works.

**Comment by stephenchea** [comment]
Thank you! I'll try this out and see if it works.

**Comment by stephenchea** [comment]
I looked for the command ProjectCellEmbeddings, but I wasn't able to find it in the official release of Seurat v3.0. I was able to find ProjectDim, but that won't accomplish what I want to do. Was it only in the beta release?
