### ISSUE TITLE
PlotClusterTree in version 3?

### ISSUE THREAD

**Issue by KoichiHashikawa** [satijalab/seurat#1103]
Hi,
Does Seurat v3 have PlotClusterTree function or equivalent?
It seems that PlotClusterTree is missing though it has BuildClusterTree.

thank you.

**Comment by cjuagf** [comment]
I wanted to do this also but couldn't get it to work in Seurat v3. I got around it using plot_Cladogram function in Matlab. It worked for me. You can do it using the following commands;

1. Cladogram code in Matlab
function plot_Cladogram(data,cluster_label)
% Plot Cell Cladogram
% data: gene-cell data matrix
% cluster_label: cluster labels

No_genes = size(data,1);
No_clusterr = length(unique(cluster_label));
M_cla = zeros(No_genes,No_clusterr);
for i = 1:No_clusterr
    M_cla(:,i) = mean(data(:,cluster_label ==i)');
end

%%
% M_Z = linkage(M_cla','average','cityblock'); % 
M_Z = linkage(M_cla','ward','euclidean');

ddg = dendrogram(M_Z,'Orientation','left','ColorThreshold',1);
set(ddg,'LineWidth',2);
% for i = 1:No_clusterr
%     ddg(i).Color =[0 0 0];
% end

2. Plot tree
data = importdata('gene_matrix_matlab.txt');

%% Extract data
data_matrix = data.data;
gene_name = data.textdata(2:end,1);

%% Import cluster labels
cluster_label = importdata('cell_identities_matlab.txt');
cluster_label = (cluster_label)+1;
cluster_label = cell2mat(cluster_label);


%% run function
plot_Cladogram(data_matrix,cluster_label)

**Comment by andrewwbutler** [comment]
This has been added as of 5270130.

**Comment by KoichiHashikawa** [comment]
@andrewwbutler  thanks.
I reinstalled v3 and now it has PlotClusterTree function.
But I still receive error. I opened a new issue.

**Comment by ElyasMo** [comment]
I guess you make a simple mistake.
you should put the BuildClusterTree equal to your object and then plot the object by PlotClusterTree.
It is like this:

```
CR_sample <- BuildClusterTree(CR_sample)
PlotClusterTree(CR_sample)
```
Hope it works for you.
