### ISSUE TITLE
VlnPlot symbol name issue

### ISSUE THREAD

**Issue by mjsteinbaugh** [satijalab/seurat#111]
I ran into a gene symbol issue in the v2 update.

`VlnPlot()` now fails to plot symbols with a hyphen in the name because of `data.frame()` coercion, which sanitizes the hyphen to a period in the name. Here's an example:

```r
> VlnPlot(seurat, "Cd74")  # works
> VlnPlot(seurat, "H2-Ab1")  # broken
```

Upon further debugging, I found the issue appears to be related to [line 294 in plotting.R](https://github.com/satijalab/seurat/blob/master/R/plotting.R#L294):

```r
> symbols <- c("Cd74", "H2-Ab1")
# Check sparse matrix
> symbols %in% rownames(seurat@data)
[1] TRUE TRUE
# Check `FetchData()` call
> FetchData(seurat, vars.all = symbols) %>% colnames
ENSMUSG00000024610 ENSMUSG00000073421 
            "Cd74"           "H2-Ab1"
# Mismatch in `VlnPlot()`
> data.use <- data.frame(FetchData(object = object, vars.all = features.plot, …))
[1] "Cd74" "H2.Ab1" 
```

Adding `check.names = FALSE` to the `data.frame()` call should fix the issue.

Best,
Mike

**Comment by mjsteinbaugh** [comment]
This seems to be related to [issue 108] as well. I'll work on drafting a simple pull request.

**Comment by satijalab** [comment]
Thanks for the great catch! Most of the developers in the lab are at a conference in the UK at the moment, so please do feel free to submit a pull request! If not, we'll fix next week when we return.

**Comment by andrewwbutler** [comment]
This should be fixed in the develop branch. You'll have to install it from source (`install_github("satijalab/seurat", ref = "develop"`) but it should handle gene names that start with numbers or contain dashes.

**Comment by mjsteinbaugh** [comment]
Great! That's working again for me now. Thanks for the quick response.
