### ISSUE TITLE
PlotClusterTree not importing plot.phylo and nodelabels from ape

### ISSUE THREAD

**Issue by danielruss** [satijalab/seurat#1111]
I'm not sure why the plot.phylo and nodelabels are not imported..  here is the original function
`
`
> PlotClusterTree
function (object, ...) 
{
    if (is.null(x = Tool(object = objects, slot = "BuildClusterTree"))) {
        stop("Phylogenetic tree does not exist, build using BuildClusterTree")
    }
    data.tree <- Tool(object = object, slot = "BuildClusterTree")
    plot.phylo(x = data.tree, direction = "downwards", ...)
    nodelabels()
}
<bytecode: 0x8a5b728>
<environment: namespace:Seurat>

> PlotClusterTree(neurons.integrate.ndim.50)
Error in UseMethod(generic = "Tool", object = object) : 
  no applicable method for 'Tool' applied to an object of class "function"

``

After making a small change:

> PlotClusterTree
function(object,...){
    if (is.null(x = Tool(object = object, slot = "BuildClusterTree"))) {
        stop("Phylogenetic tree does not exist, build using BuildClusterTree")
     }
    data.tree <- Tool(object = object, slot = "BuildClusterTree")
     ape::plot.phylo(x = data.tree, direction = "downwards", ...)
    ape::nodelabels()
}

it makes a nice dendogram.  I see you have the import, but something must be wrong in the import.

**Comment by andrewwbutler** [comment]
The problem was the first `Tool` call trying to find `objects` instead of `object`. This should have been resolved in 0f5eddc. I don't think it's an import problem.

**Comment by danielruss** [comment]
Freshman mistake.   My function was not in the Seurat envrionment, so the ape library was not imported.   Fixing the (s) fixed the problem in PlotClusterTree.

Thank you.
