### ISSUE TITLE
Error using PlotClusterTree in v3

### ISSUE THREAD

**Issue by KoichiHashikawa** [satijalab/seurat#1112]
I ran "PlotClusterTree" after BuildClusterTree and received following error.
```R
BuildClusterTree(Integrated, verbose = FALSE, reorder = TRUE)

An object of class Seurat 
21274 features across 23824 samples within 2 assays 
Active assay: integrated (2000 features)
 2 dimensional reductions calculated: pca, umap

PlotClusterTree(Integrated)

Error in PlotClusterTree(Integrated): Phylogenetic tree does not exist, build using BuildClusterTree
Traceback:

1. PlotClusterTree(Integrated)
2. stop("Phylogenetic tree does not exist, build using BuildClusterTree")   # at line 4 of file <text>
```

**Comment by mojaveazure** [comment]
You have to save the results of `BuildClusterTree` back to the object, otherwise it gets returned to the terminal and garbage-collected by R.

```r
Integrated <- BuildClusterTree(Integrated, verbose = FALSE, reorder = TRUE)
PlotClusterTree(Integrated)
```

**Comment by KoichiHashikawa** [comment]
@mojaveazure 
Actually, I did, but still got the same error.

**Comment by KoichiHashikawa** [comment]
str(Integrated@tools)
List of 2
 $ Integration     :Formal class 'IntegrationData' [package "Seurat"] with 7 slots
  .. ..@ neighbors         : NULL
  .. ..@ weights           : NULL
  .. ..@ integration.matrix: NULL
  .. ..@ anchors           :'data.frame':	274974 obs. of  5 variables:
  .. .. ..$ cell1   : num [1:274974] 237 119 151 156 172 81 223 187 164 38 ...
  .. .. ..$ cell2   : num [1:274974] 1 3 3 3 4 8 8 10 11 17 ...
  .. .. ..$ score   : num [1:274974] 0 0.00485 0.10194 0 0.61165 ...
  .. .. ..$ dataset1: int [1:274974] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..$ dataset2: int [1:274974] 2 2 2 2 2 2 2 2 2 2 ...
  .. ..@ offsets           : NULL
  .. ..@ objects.ncell     : NULL
  .. ..@ sample.tree       : num [1:7, 1:2] -2 -8 1 3 -3 4 6 -5 -7 -6 ...
 $ BuildClusterTree:List of 4
  ..$ edge       : int [1:56, 1:2] 30 31 31 35 40 48 48 53 53 40 ...
  ..$ edge.length: num [1:56] 62.04 50.4 16.12 10.82 3.28 ...
  ..$ tip.label  : chr [1:29] "Vglu6" "Ambiguous2" "Mix2" "Vgat15" ...
  ..$ Nnode      : int 28
  ..- attr(*, "class")= chr "phylo"
  ..- attr(*, "order")= chr "cladewise"

PlotClusterTree(Integrated)

**Comment by andrewwbutler** [comment]
Can you try reinstalling the latest Seurat v3.0 and running `BuildClusterTree` + `PlotClusterTree` again from a fresh R session? What is the output if you run:

```r
Tool(object = Integrated)
Tool(object = Integrated, slot = "BuildClusterTree")
```

**Comment by KoichiHashikawa** [comment]
Now it works after reinstallation, thanks so much @andrewwbutler  

'Integration' 'BuildClusterTree'

Phylogenetic tree with 29 tips and 28 internal nodes.

Tip labels:
	Vglu6, Ambiguous2, Mix2, Vgat15, Vgat9, Mix1, ...

Rooted; includes branch lengths.
