### ISSUE TITLE
Seurat installed but some functions not available

### ISSUE THREAD

**Issue by rosshandler** [satijalab/seurat#1113]
Hello Seurat team,

 I would like to use the latest dataset integration framework you have published in Biorxive. Following the instructions I have installed the developers version. However, functions such as FindVariableGenes
and FilterCells are not recognized. Other functions work fine. I am sure this is an easy fix but I would like to avoid falling into previous versions for cell alignment. What do you recommend?

 library(Seurat)
...
> sce.seurat <- FindVariableGenes(sce, do.plot = F)
Error in FindVariableGenes(sce, do.plot = F) : 
  could not find function "FindVariableGenes"

Thanks in advance for such awesome tool,
Ivan

**Comment by rosshandler** [comment]
Okay, I found a new function named FindVariableFeatures.

It is just a little bit confusing to follow the tutorials with respect to the newest updates.

**Comment by maximilianh** [comment]
Suggestion to the Seurat authors: you could add little stub functions that
output a message: "this function is now called xxxx"
It may save you a few Github issues and the resulting email...

**Comment by mojaveazure** [comment]
For Seurat v3, we have made every attempt to include link the help page for the old function to the new function. We've done it this way to clean up our code base of years of deprecated function calls. For this specific case, calling `?FindVariableGenes` will pull up the help page for `FindVariableFeatures`; [we also have a version of our PBMC 3k tutorial using v3 with all v3 functions](https://satijalab.org/seurat/pbmc3k_tutorial_v3.html).

If you come across a function you used to use, try calling help on it to pull up the modern help page for it. If we've forgotten to link a new function, please let us know.

**Comment by maximilianh** [comment]
Example case. User x gets Seurat commands from a colleague. X does
"install.packages(Seurat)" and think they have Seurat on their machine but
the commands don't work.

Same for: Random tutorial on the internet specifies Seurat commands.
Tutorial at a conference about Seurat mentions commands. People then
install the package but the commands won't work.

The more users you have, the harder it is to change things. It's hard to be
popular. :-)

**Comment by Naomi1009** [comment]
Oh I just can't find a function to replace FilterCells....
