### ISSUE TITLE
devtools can't install hdf5r successfully,need your help!

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1114]
This is my R code following https://satijalab.org/seurat/mca_loom.html
:
![image](https://user-images.githubusercontent.com/30619010/52134681-1403b480-267f-11e9-8eeb-f30655675691.png)
But it showed the error,I remove the dir D:/software/R-3.5.2/library/hdf5r, and rerun the cose ,but it still give this error,who can help me?
![image](https://user-images.githubusercontent.com/30619010/52134775-4dd4bb00-267f-11e9-8fb3-4c2ca4a0278d.png)
** libs
error: this package has a non-empty 'configure.win' file,
so building only the main architecture
* removing 'D:/software/R-3.5.2/library/hdf5r'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/dell/AppData/Local/Temp/RtmpuK459n/file691439c04f/hdf5r_1.0.1.tar.gz’ had non-zero exit status

**Comment by TomKellyGenetics** [comment]
You need to install the HDF5 dependancy before installing the R package. See here for details: https://github.com/hhoeflin/hdf5r#Requirements 

You can download the windows version here: https://github.com/mannau/h5-libwin

**Comment by Sophia409** [comment]
> You need to install the HDF5 dependancy before installing the R package. See here for details: https://github.com/hhoeflin/hdf5r#Requirements
> 
> You can download the windows version here: https://github.com/mannau/h5-libwin





> You need to install the HDF5 dependancy before installing the R package. See here for details: https://github.com/hhoeflin/hdf5r#Requirements
> 
> You can download the windows version here: https://github.com/mannau/h5-libwin

![image](https://user-images.githubusercontent.com/30619010/52908106-a1fbb400-32a9-11e9-9fec-9e9ea96694c2.png)
HDF5 1.8.14 has been pre-compiled for Windows and is available at https://github.com/mannau/h5-libwin - thus no manual installation is required.

**Comment by Sophia409** [comment]
@TomKellyGenetics hello, thank you for your reply.May I ask you another question? you can see it here https://github.com/mannau/h5-libwin/issues/2
My hdf5-1.8.14.zip file obtained from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/,then unpack to C:\hdf5, I use the version of cmake-3.13.4-win64-x64 and visual studio 2017 to configure, but it failed! I have no experience about this, and this turorial (https://github.com/mannau/h5-libwin) is so brief that I could't really understand and finish it.

![Uploading image.png…]()

**Comment by TomKellyGenetics** [comment]
Sorry, I have only used this software on Mac and Linux systems so I cannot help you on how to install it on Windows. This is a problem with a dependancy. Once you have installed this, the R packages should work. I'd recommend to close this issue and hope you find help specifically about h5 elsewhere.

**Comment by mojaveazure** [comment]
@Sophia409 The developers of hdf5r [provide a version of hdf5](https://github.com/mannau/h5-libwin) for R under Windows. Please try again with that version of hdf5; if that still fails, I'd recommend opening an issue with [hdf5r](https://github.com/hhoeflin/hdf5r/issues).

**Comment by Sophia409** [comment]
@mojaveazure @TomKellyGenetics Thank you for your advice.** I can't open [ The link]( http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.14.tar.gz)  that [official website ](https://github.com/mannau/h5-libwin) provided for windows users,so I downloaded buildhdf5-1.10.4 this time and configure successfully,and according to [procedure3](https://github.com/mannau/h5-libwin), I have to set these parameters manually. 
But I only find * BUILD_STATIC_EXECS**: check  HDF5_BUILD_CPP_LIB: check * HDF5_BUILD_HL_LIB: check * HDF5_ENABLE_ZLIB_SUPPORT: check **,and I couldn't fould** * CMAKE_BUILD_TYPE: Release *.**
**Also,I don't know how to Set ZLIB, where I can do**  
(ZLIB_INCLUDE_DIR: C:/Rtools/mingw_64/x86_64-w64-mingw32/include 
ZLIB_LIBRARY: C:/Rtools/mingw_64/x86_64-w64-mingw32/lib/libz.a).
**can you tell me in more detail?**
![image](https://user-images.githubusercontent.com/30619010/52935162-9e445c00-3393-11e9-8fb4-4b24ff945058.png)
![image](https://user-images.githubusercontent.com/30619010/52935447-6689e400-3394-11e9-9d55-fb92d2fd187d.png)

**Comment by Sophia409** [comment]
@TomKellyGenetics @mojaveazure @olgabot @farcasia 
I add some columns of custom metadata by using the Seurat v3.X command(object$name <- vector),but I can't delete these columns,such as "time","hours".I try many many ways,like subset, subsetdata,and test.tc11$hours >- NULL, all them didn't work.
Can you help me?
```
> test.tc11$hours <- rep("E14",7303)
> tail(x = test.tc11[[]])
                      orig.ident nCount_RNA nFeature_RNA percent.mito RNA_snn_res.0.8 letter.idents time DAY hours
A_TTTGTCACATTGGTAC SeuratProject       3987         1775            0               7             H  E11 E14   E14
A_TTTGTCAGTAAGTGGC SeuratProject       4299         1992            0               7             H  E11 E14   E14
A_TTTGTCAGTAGGACAC SeuratProject       6994         2448            0               0             A  E11 E14   E14
A_TTTGTCAGTAGGCATG SeuratProject       7906         2588            0               4             E  E11 E14   E14
A_TTTGTCAGTCTCATCC SeuratProject      24778         5035            0               8             I  E11 E14   E14
A_TTTGTCAGTTCTGTTT SeuratProject       8209         2628            0               2             C  E11 E14   E14
```

**Comment by vicramr** [comment]
If you're not interested in actually using `Seurat::Read10X_h5()` and you just want to get the rest of Seurat working, I'd recommend trying [fake-hdf5r](https://github.com/UCSF-TI/fake-hdf5r). It's a non-functional version of the `hdf5r` package that will allow Seurat to be installed successfully. To install it, you should just be able to do `remotes::install_github("UCSF-TI/fake-hdf5r")`. 

Note: I have NOT tried this on Windows. It's worked for me on Mac, though. If you want to try this, I'd recommend uninstalling Seurat, then uninstalling whatever hdf5 library you have, then installing `fake-hdf5r`, then trying to re-install Seurat.

**Comment by timoast** [comment]
Hi, in the latest version of Seurat we have removed the `hdf5r` dependency, so you should be able to install Seurat from CRAN now without HDF5: `install.packages("Seurat")`

**Comment by jonathanzhang53** [comment]
@vicramr While installing Seurat 2.3.4, I also ran into this package problem. Your suggestion worked like a charm. Thanks.

**Comment by vicramr** [comment]
@jonathanzhang53 I'm glad I was able to help!

**Comment by c5creative** [comment]
For anyone else looking for the hd5fr release (broken link), it's available at https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/

**Comment by bontix-77** [comment]
apt-get update && apt-get install -y  patch

R -e "install.packages('hdf5r')"
