### ISSUE TITLE
FeaturePlot font size

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#1115]
Hi, 

Is there an option to set/reduce the font sizes in FeaturePlot? 
With multiple plots in one frame, the font sizes are not matched and results in a plot that has no visible graphs but large title names only.

Thank you!

**Comment by andrewwbutler** [comment]
Hi,

The font sizes for `FeaturePlot` are handled via [themes](https://ggplot2.tidyverse.org/reference/theme.html) in `ggplot2`. If you're plotting multiple features in the same plot, you can set `combine = FALSE` to return a list of ggplot objects that you can then manipulate as you would any ggplot. For example:

```r
plots <- FeaturePlot(object = pbmc_small, features = c("MS4A1", "LYZ"), combine = FALSE)
plots <- lapply(X = plots, FUN = function(x) x + theme(plot.title = element_text(size = 5)))
CombinePlots(plots = plots)
```

I would also explore the size/resolution that you're using to export the plots.
