### ISSUE TITLE
Error with CreateSeuratObject

### ISSUE THREAD

**Issue by shikhagupta68** [satijalab/seurat#1116]
Would appreciate any help with fixing this error-

```r
abc.data <- Read10X(data.dir = "/home/xyz/agg/outs/filtered_gene_bc_matrices_mex/mm10")
abc <- CreateSeuratObject(raw.data = abc.data, min.cells = 3, min.genes = 200, project = "ABC")
Error in colSums(object.raw.data > is.expr) : 
  'x' must be an array of at least two dimensions
```

Thank you

**Comment by andrewwbutler** [comment]
Hi,

What does `abc.data` look like after reading it into R? Could you provide the first 5 rows/columns?

```r
abc.data[1:5, 1:5]
```

**Comment by shikhagupta68** [comment]
abc.data[1:5, 1:5]
5 x 5 sparse Matrix of class "dgCMatrix"
        AAACCTGAGGCGATAC-1 AAACCTGGTGACTCAT-1 AAACGGGAGTCCAGGA-1
Xkr4                     .                  .                  .
Gm1992                   .                  .                  .
Gm37381                  .                  .                  .
Rp1                      .                  .                  .
Rp1.1                    .                  .                  .
        AAACGGGCATTCTCAT-1 AAACGGGTCTGTCAAG-1
Xkr4                     .                  .
Gm1992                   .                  .
Gm37381                  .                  .
Rp1                      .                  .
Rp1.1                    .                  .

**Comment by shikhagupta68** [comment]
Thanks. I updated the Matrix package and now I seem to have an object without seurat object slots- 

abc_object <- CreateSeuratObject(raw.data = abc.data, min.cells = 2, min.genes = 200, project = "ABC")

slotNames(abc_object)
[1] "i"        "p"        "Dim"      "Dimnames" "x"        "factors" 

abc_object[1:5,1:5]
5 x 5 sparse Matrix of class "dgCMatrix"
        AAACCTGAGGCGATAC-1 AAACCTGGTGACTCAT-1 AAACGGGAGTCCAGGA-1
Mrpl15                   2                  .                  .
Lypla1                   1                  1                  2
Tcea1                    2                  .                  2
Atp6v1h                  2                  .                  2
Rb1cc1                   .                  .                  1
        AAACGGGCATTCTCAT-1 AAACGGGTCTGTCAAG-1
Mrpl15                   .                  .
Lypla1                   .                  .
Tcea1                    .                  .
Atp6v1h                  .                  .
Rb1cc1                   .                  .

**Comment by andrewwbutler** [comment]
Hmm, can you try starting again from a fresh R session?

**Comment by shikhagupta68** [comment]
I did that several times and everytime getting the same thing

**Comment by andrewwbutler** [comment]
I can't seem to reproduce this issue. Are you able to run the [pbmc3k tutorial](https://satijalab.org/seurat/pbmc3k_tutorial.html) using the data provided for that?

**Comment by shikhagupta68** [comment]
I was unable to run pbmc3k tutorial as well.
There was some issue with Seurat installation dependencies on my server
I finally installed it on my system and it's working well

Thank you

**Comment by iakovrudenko** [comment]
I also was unable to run pbmc3k tutorial

**Comment by kasumaz** [comment]
Dear Andrew/Satja team,
I have the same problem here too. 
I have been using Seurat quite a lot lately. 
But today...
When setting up the seurat object at the start: 
Error in CreateSeuratObject(raw.data = scex, min.cells = 10, min.genes = 20,  : 
  unused arguments (raw.data = scex, min.genes = 20)

I have this above error that comes up. 

I tried uninstalling the app and installing again. But each time closing Rstudio after uninstalling and also restarting Rstudio. 
Instead of uninstalling Rstudio altogether, and installing again, is there another work around this? 
Many thanks.

**Comment by andrewwbutler** [comment]
Hi,

It looks like you are running Seurat v3 (released on CRAN yesterday), which has updated some argument names. Check out the [website](https://satijalab.org/seurat/) for details and updated vignettes. If you would like to reinstall the last version 2 release, please see the install page [here](https://satijalab.org/seurat/install.html) for instructions.

**Comment by kasumaz** [comment]
> Hi,
> 
> It looks like you are running Seurat v3 (released on CRAN yesterday), which has updated some argument names. Check out the [website](https://satijalab.org/seurat/) for details and updated vignettes. If you would like to reinstall the last version 2 release, please see the install page [here](https://satijalab.org/seurat/install.html) for instructions.

Hi, you are absolutely right. I went through the tutorial for the new version of v3 and went back to my counts. All is good. V3 looks better, although I was used to the previous version. Just need to get used to the updated commands. 
Thanks a lot for your prompt response.
