### ISSUE TITLE
Batch-corrected data

### ISSUE THREAD

**Issue by gouthamatla** [satijalab/seurat#1118]
Hi,

I ran the integrated pipeline in Seurat_3.0.0.9000 . My Seurat object has `Object@Assays$RNA` and `Object@Assays$integrated`. This is something different from what is mentioned at https://satijalab.org/seurat/pancreas_integration_label_transfer.html (`the Seurat object will contain a new Assay with the integrated expression matrix`). 

I understood that Object@Assays$RNA holds raw data but Object@Assays$integrated has only 2000 genes. Am I missing something here ?

How do I export the batch corrected data ?

**Comment by timoast** [comment]
The integrated expression matrix is present in the integrated assay. You can access the matrix using the `GetAssayData` function, for example:

```r
integrated <- GetAssayData(object = object, assay = "integrated", slot = "data")
```

By default, only the variable genes are integrated, which is likely why you have 2000 genes in the integrated matrix. You can change this by setting the `features.to.integrate` argument in `IntegrateData`

**Comment by gouthamatla** [comment]
Thanks for the answer. It was a bit hard to think that batch-corrected data will be given for only 2000 genes by default. One would expect batch-corrected data is for all genes or for all genes after filtering the data. 

Is there a better way to get batch corrected data for most of the genes ? I mean how do we chose `anchor.features` ? BTW in my version, `anchor.features` is an option in `FindIntegrationAnchors` not in `IntegrateData`

**Comment by timoast** [comment]
Yes, `anchor.features` is an option in `FindIntegrationAnchors` and `features.to.integrate` is a option in `IntegrateData`. Setting `features.to.integrate` will allow you to change the set of genes that are integrated. We recommend using a set of variable features that are common across datasets as the features used for finding anchors, which can be found using the function `SelectIntegrationFeatures` (and is the default behaviour).

**Comment by gouthamatla** [comment]
Thanks for the quick reply and clarifying .

**Comment by penglbio** [comment]
I also have a same question about the batch-corrected gene expression matrix. If I want plot one gene expression level. But there is just 2000 corrected genes expression value, and there are also include negitive and postive value. How can I do the Featureplot() with the gene which I want to check  by the Integated  gene expression value?

**Comment by andrewwbutler** [comment]
If the gene is not one of the 2000 genes you corrected, you'll have to rerun `IntegrateData` with that gene included in the `features.to.integrate` vector. If it is (or after rerunning), you can then use `FeaturePlot` to plot its integrated gene expression value. If "integrated" is the default `Assay` (you can check with `DefaultAssay`) then `FeaturePlot` will pull those values. If not, you can either switch the default `Assay` to "integrated" or append the `Assay` key to the gene name.

```R 
# option 1
DefaultAssay(object) <- "integrated"
FeaturePlot(object = object, features = "GENE")

# option 2
FeaturePlot(object = object, features = "integrated_GENE")
```
