### ISSUE TITLE
Error while converting Seurat to Loom

### ISSUE THREAD

**Issue by kathirij** [satijalab/seurat#1119]
Hello all,
   I am facing some difficulty converting a seurat analyzed object to loom. here is the code I am using:

`test1 <- Convert(from = seurat_obj, to = "loom", filename= "seurat_obj.loom")`

This is throwing me the following error:

Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns 
This is to maintain compatibility with other loom tools 
Error in dataset_create_pl$set_chunk(chunk_dims) : HDF5-API Errors:
    error #000: ../../../src/H5Pdcpl.c in H5Pset_chunk(): line 2030: all chunk dimensions must be positive
        class: HDF5
        major: Invalid arguments to routine
        minor: Out of range
In addition: Warning messages:
1: In loomR::create(filename = filename, data = from@raw.data[, cell.order],  :
  NAs introduced by coercion
2: In dataset_create_pl$set_chunk(chunk_dims) :
  During conversion, the following issues occured: H5T_CONV_EXCEPT_RANGE_LOW

Has anyone faced a similar issue?

**Comment by kasimana37** [comment]
I have the same problem. I already downloaded these three packages so not sure what went wrong..
devtools::install_github(repo = "hhoeflin/hdf5r")
devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
devtools::install_github(repo = "satijalab/seurat", ref = "loom")

**Comment by IrinnaP** [comment]
Same issue here, even with the sample data set: pfile <- Convert(from = pbmc_small, to = 'loom', filename = 'pbmc_small.loom'). Any ideas anyone?

**Comment by mellyS** [comment]
Same problem here, Does anyone know how to fix it ??

**Comment by combiz** [comment]
Same issue here.

**Comment by RobertAlpin** [comment]
Not a lot of help but I've got the same issue. I've investigated with the current release of Seurat (2.3.4) as well and that is giving me the same error. The loomR branch updated as recently as last week, and HDf5r is within 2 weeks as well.

Has anyone tried using the pre-release of Seurat 3?

Here's my output if it helps anyone

```
             used    (Mb)  gc trigger     (Mb)    max used     (Mb)
Ncells   11891856   635.1    24545186   1310.9    24545186   1310.9
Vcells 5100557596 38914.2 13811084999 105370.3 16996302607 129671.5
Transposing input data: loom file will show input columns (cells) as rows and input rows (features) as columns
This is to maintain compatibility with other loom tools
Error in dataset_create_pl$set_chunk(chunk_dims) : HDF5-API Errors:
    error #000: ../../../src/H5Pdcpl.c in H5Pset_chunk(): line 870: all chunk dimensions must be positive
        class: HDF5
        major: Invalid arguments to routine
        minor: Out of range
Calls: Convert ... Convert.seurat -> <Anonymous> -> <Anonymous> -> <Anonymous> -> .Call
In addition: Warning messages:
1: In loomR::create(filename = filename, data = from@raw.data[, cell.order],  :
  NAs introduced by coercion
2: In dataset_create_pl$set_chunk(chunk_dims) :
  During conversion, the following issues occured: H5T_CONV_EXCEPT_RANGE_LOW
Execution halted
```

**Comment by mellyS** [comment]
Hi everyone ,
I think that when creating a Seurat Object from a loom file, it does not keep information about spliced, unspliced and ambiguous reads. Therefore, when creating a loom object from the Seurat object, the three layers remain empty

**Comment by mojaveazure** [comment]
Hi all,

The loom branch of Seurat is based on Seurat v2, which will no longer be updated as we move to Seurat v3. The pre-release of Seurat v3 has a new converter for Seurat &harr; `loom` in the forms of `as.loom` and `as.Seurat`; these converters require the latest development version of [loomR](https://github.com/mojaveazure/loomR/tree/develop), but should be functional.

For converting between Seurat and `loom`, please use the pre-release of Seurat v3; we currently do not have an ETA for running the Seurat workflow on `loom` objects as provided by the loom branch of Seurat v2

**Comment by RobertAlpin** [comment]
Thanks for the reply. It's nice to know that I'm not doing something wrong with my code, but that the documentation I'm trying to use is out of date. With that, I have some questions that not being able to use the old up:

Where can I read more about the as.loom feature? I can't find more specific details of its usage on the github page for LoomR or the prerelease info for Seurat 3.
Will I need to change the instructions for normalizing dara in Seurat 3 so that features are read in from colnames and not rownames or does seurat automatically read the loom object as transverse? Seurat v2 didn't have this written out explicitly so I'm not sure how it translates to v3.
Are there older versions of loom that I can download to use with my existing Seurat 2 code? If so, what versions of each are optimal?

**Comment by mojaveazure** [comment]
Apologies for the documentation; we're currently doing an overhaul of all our vignettes in preparation for a proper Seurat v3 release to CRAN.

- As for learning about `as.loom`, you can use `?as.loom` with Seurat v3 installed.
- Seurat has and always will automatically transpose the matrix when dealing with loom files. Seurat v3 currently cannot run `NormalizeData` directly on a loom file, but allows one to read in the data into a Seurat object by calling `as.Seurat` on a connected loom file. This functionality is only present when using loomR to connect and write to loom files
- I cannot remember which version of loomR Seurat v2 supports, but you'll also need an old version of hdf5r as there are differences between previous and current versions of that package that are supported in current versions of loomR. However, older versions of hdf5r aren't as stable as current ones, and I would recommend moving to Seurat v3 unless you absolutely need to run the Seurat workflow on your loom files directly. If that's the case, the latest version of loomR on the `master` branch *should* work, but again, I'm not sure.

**Comment by RobertAlpin** [comment]
Ok, this leads me into a new problem. Normalizing data takes up too much RAM. The seurat object I have takes up  <133 gb (which is odd as the sparse matrix is <40 gb) and normalizing the data  (in version 2.3.4) pushes the object to >200gb, which far exceeds the ram available to me without parallelization on my university's HPC. I was hoping to convert the starting seurat object to a loom object at the very beginning and put it through normalization on-words that way, but if I understand you correctly, that's not possible with the current version? And are you saying that this would be possible with the older version?

**Comment by mojaveazure** [comment]
It's not all that odd; Seurat stores each matrix ~3 times (raw, normalized, scaled). Seurat v3 has a function called `DietSeurat` that will attempt to slim down a Seurat object that works fairly well.

Correct, you cannot run the Seurat workflow on a a `loom` object using the latest versions of Seurat, loomR, and HDF5. This should be possible with old versions of Seurat, loomR (< 0.2.0), hdf5r (1.0.0), and the HDF5 library itself (older versions of hdf5r don't support HDF5 > 1.10, I believe).

**Comment by RobertAlpin** [comment]
This is all very useful to know. I'll try out DietSuerat and if it still isn't lean enough compile a container for the older version of Seurat/loomR/hdf5r. Thank you so much for your response.
