### ISSUE TITLE
[Feature Request] FindMarkers between groups of idents

### ISSUE THREAD

**Issue by billytcl** [satijalab/seurat#112]
Hi there, it would be really nice for a next release is able to perform FindMarkers between groups of idents. For example: sometimes in an analysis I have 5 clusters and want to compare 1+2 vs 3+4+5.

I can perform this using MergeNodes, but it would be nice if the syntax could support something like: FindMarkers(seurat_obj,ident.1=c(1,2,3),ident.2=c(4,5))

**Comment by satijalab** [comment]
This functionality is supported
