### ISSUE TITLE
scaledata under v3.0

### ISSUE THREAD

**Issue by trptyrphe11** [satijalab/seurat#1120]
Hi there,

For me to work on a matrix of 30K genes and 1k cells, scaledata is very time-consuming. So I am wondering if you would recommend apply this function to features of variablegenes (from VariableFeatures()); or sample code for parallel computing? Thanks.

**Comment by timoast** [comment]
You can just scale the variable features, this will save some time and RAM. Keep in mind that if you want to plot genes in a heatmap, this uses scaled data by default and you may need to re-scale to ensure all the genes you want to plot are present in the scaled data. We also have multi-threading enabled for `ScaleData` using the `future` package (see #1027).

For example:
```r 
library(future)
plan(strategy = "multicore", workers = 6)
pbmc_small <- ScaleData(pbmc_small)
```

**Comment by trptyrphe11** [comment]
Thanks for the advice and will test out. Actually when I was using v2.3 (R3.4.2) for the same dataset, scaledata was much faster (I installed v3.0 under R3.5.0), was this behavior as expected?

**Comment by FarzanT** [comment]
Note that if your expression matrix is large, it's best to increase future's maximum allowed size of objects to be exported from default of 500 MB. For example:
```R
options(future.globals.maxSize= 2048 * 1024^2)
```
which sets the maximum at 2 GB. (Trust me you don't wanna see an error after an hour of running the function)

**Comment by gkumar09** [comment]
Hi,
I am working on dataset from human cell atlas, and while using SCtransform I  get the following error:
Error: cannot allocate vector of size 190.6 Gb

I am using both multicore and increased future's maxsize option:
options(future.globals.maxSize = 2048 * 1024^2)
plan(strategy = "multicore", workers = 6)
 
Please advise- thanks!
