### ISSUE TITLE
MetegeneBiCorPlot/AlignSubspace

### ISSUE THREAD

**Issue by silpasuthram** [satijalab/seurat#1121]
I am using Seurat V3.  However, I am not finding the function: MetegeneBiCorPlot and AlignSubspace.  What is its equivalent function in Seurat V3?

**Comment by andrewwbutler** [comment]
Hi,

These functions have been removed in Seurat v3 as they have been replaced by our new integration strategy. Please see our updated vignette [here](https://satijalab.org/seurat/pancreas_integration_label_transfer.html) for how to integrate datasets in Seurat v3.

**Comment by jurtlest** [comment]
Is there a new vignette for replacing AlignSubspace ??? the link is 404 not found for me.

**Comment by andrewwbutler** [comment]
Hi,

You can check out the latest data integration vignettes [here](https://satijalab.org/seurat/articles/get_started.html#data-integration-1). I would recommend starting with the "Introduction to scRNA-seq integration" one.
