### ISSUE TITLE
Percentage distribution of treated cells in all clusters?

### ISSUE THREAD

**Issue by charlesgwellem** [satijalab/seurat#1122]
Is there are possibilty  in Seurat to visualise the percentage distributions of cells treated under a particular condition per cluster? For example I wish to be able to produce a figure where I say: X% of cells treated with Y condition were located in cluster C and so forth?

I have tried: 
```
number_perCluster<- table(object@meta.data$conditions, 
                          object@meta.data$clusterID)
```
Which gives me the result below, where 0, 1, 2, 3, and 4 are the cluster IDs.

```
 Cluster              0   1   2   3   4
 IL9KOBleomycinSkin 175  11  49   8   6
 WTBleomycinSkin    915  45  90  25  17
 WTNaClctrlSkin     488  32 257  16  17

```

I need a hint to be able to produce a comprehensive figure.

Thank you in advance.

**Comment by timoast** [comment]
Answered here: https://bioinformatics.stackexchange.com/questions/6960/percentage-distribution-of-cells-in-all-clusters-based-on-their-treatment-condit
