### ISSUE TITLE
MAST and DESeq2 in FindAllMarkers don't give warnings when not installed 

### ISSUE THREAD

**Issue by 2064240P** [satijalab/seurat#1123]
Hello, 

I tried specifying MAST and DESeq2 for test.use with FindAllMarkers and they just reported 
> No DE genes identified. 

However, when I ran FindMarkers I got the error:
> Please install DESeq2/MAST

It would be quite useful to add this warning to FindAllMarkers just in case. 

Thanks,

**Comment by andrewwbutler** [comment]
Hi,

Thanks for the suggestion. I agree that the tryCatch in `FindAllMarkers` was a little overly suppressive. The messages should now propagate and display at the end of the `FindAllMarkers`.
