### ISSUE TITLE
FindVariableGenes error. Normalized data has negative values.

### ISSUE THREAD

**Issue by hkarakurt8742** [satijalab/seurat#1124]
Hello,
I have a scRNA-Seq data matrix which is batch corrected and normalized. I want to do clustering analysis with Seurat but when I CreateSeuratObject with these values and try to FindVariableGenes,
I have an error:

"Error in text.default(x = gene.mean[pass.cutoff], y = gene.dispersion.scaled[pass.cutoff],  : 
  zero-length 'labels' specified"

How can I pass this error. Should I use all genes for PCA with "pc.genes = rownames(data@seuratobject)" ?

Thanks in advance

**Comment by satijalab** [comment]
Seurat does not support identifying variable genes on integrated (corrected) data, you need oto identify variable genes on the original RNA assay

**Comment by Dragonmasterx87** [comment]
This information is actually also important when moving a Seurat object into monocle. You cant re-compute variable genes in an integrated Seurat object, you have to re-analyze using different variable genes. Nice comment!
