### ISSUE TITLE
create seurat object from Rhapsody data

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#1125]
Hi, 
I am wondering whether there is/will be a direct command for creating a Seurat object form BD Rhapsody data? 
Thanks annecar

**Comment by timoast** [comment]
Can you share an example dataset? I'm not familiar with their data format

**Comment by annecar** [comment]
Hi thanks for answering
i attach you an example. The original comes as a csv. I saved it as txt here. 
annecar
[Rhapsody_data.txt](https://github.com/satijalab/seurat/files/2850087/Rhapsody_data.txt)

**Comment by timoast** [comment]
You can read this in using `read.table` and create a Seurat object from the matrix:

```r
library(Seurat)
counts <- read.table("Rhapsody_data.txt", skip = 7, sep = ",", header = TRUE, row.names = 1)
obj <- CreateSeuratObject(counts = t(counts))
```

**Comment by annecar** [comment]
ok, great thanks! 
so it does not matter whether the genes are in columns rather than in rows? 

Thanks and best 
Anne 



CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by timoast** [comment]
It does matter, genes should be in rows and cells in columns. You can transpose the matrix to get the required format (`t(counts)`)

**Comment by annecar** [comment]
perfect, thanks! 





Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by cathalgking** [comment]
I am working on a project that uses BD's Rhapsody and then sequences with Illumina. If I can read data from a Rhapsody into Seurat as shown above, doesnt that mean that I am ready to make t-SNE plots? What difference is that to making t-SNE plots with sequencing data?

**Comment by NDUFB11** [comment]
> Hi thanks for answering
> i attach you an example. The original comes as a csv. I saved it as txt here.
> annecar
> [Rhapsody_data.txt](https://github.com/satijalab/seurat/files/2850087/Rhapsody_data.txt)

Hi Anne, 
Looking to your file I can see that you ended up to have 2263 cells. 
Can you please tell me how many cells did you load on your cartridge? 
Thank you

**Comment by veeramv** [comment]
Hello All, 

How do it convert this tsv file below to Seurat object ?

Cell_Index                                     Gene RSEC_Reads Raw_Molecules RSEC_Adjusted_Molecules DBEC_Reads DBEC_Adjusted_Molecules
8      773006 Axin1|ENSMUST00000074370.9|Reference_end        460            18                       7        456                       3
9      773006 Ccar2|ENSMUST00000035612.6|Reference_end          6             5                       5          0                       0
10     773006        Ccn3|ENSMUST00000050027.8|PolyA_1          1             1                       1          0                       0
11     773006 Ccnd1|ENSMUST00000093962.4|Reference_end         14            12                      12          0                       0
12     773006 Ccne1|ENSMUST00000108023.9|Reference_end          2             2                       2          0                       0
13     773006        Ccny|ENSMUST00000053917.5|PolyA_1         63             9                       5         60                       2

<img width="1120" alt="Screenshot 2023-03-14 at 16 52 30" src="https://user-images.githubusercontent.com/87476823/225059579-e3f0b7a0-c236-4497-8fec-87bf04ecff6f.png">
