### ISSUE TITLE
differential expression analysis for different conditions (to identify proteins differentially expressed)

### ISSUE THREAD

**Issue by beijish** [satijalab/seurat#1126]
Good evening,

thank you a lot for Seurat, it's an amazing tool!

I am afraid I am in dire need for help. I am trying to understand how to run a differential expression analysis for different conditions from REAP-Seq data, in particular I want to compare the differential expression of proteins and genes. I see that in the paper VM Peterson et al. 2017 this is done with FindAllMarkers function, and I have tried to reproduce their results (dt.markers <- FindAllMarkers(ctrl, stim, assay.type = "REAP", only.pos = TRUE, print.bar = F), but got error ("Cell group 2 is empty - no cells with identity class Warning message:In FindAllMarkers(ctrl, stim, assay.type = "REAP", only.pos = TRUE,  : No DE genes identified"). 
For example, how shall I proceed if I want to compare the expression of protein CD45RA in the control vs stimulated group?

have read the tutorial (https://satijalab.org/seurat/immune_alignment.html) and tried to run the analyses as per that workflow, put then I get stuck because the REAP data are not retained in the immune.combined object.

Thank you a lot in advance!

Sara

This is my script so far (I am training with VM Peterson et al. data):

setwd("/Users/svalpione/Dropbox (The University of Manchester)/projects/Single cell TME/GSE100501_RAW")
library(Seurat)

ut.reap_rna_1 <- read.table("GSM2685248_mRNA_1_Donor_1_no_aCD27_matrix.txt.gz", row.names = 1, sep="\t")
ut.reap_rna_2 <- read.table("GSM2685249_mRNA_2_Donor_1_no_aCD27_matrix.txt.gz", row.names = 1, sep="\t")

t.reap_rna_3 <- read.table("GSM2685250_mRNA_3_Donor_1_with_aCD27_matrix.txt.gz", row.names = 1, sep="\t")
t.reap_rna_4 <- read.table("GSM2685251_mRNA_4_Donor_1_with_aCD27_matrix.txt.gz", row.names = 1, sep="\t")

ut.reap_protein_1 <- read.table("GSM2685258_protein_1_Donor_1_no_aCD27_matrix.txt.gz", row.names = 1, sep="\t")
ut.reap_protein_2 <- read.table("GSM2685259_protein_2_Donor_1_no_aCD27_matrix.txt.gz", row.names = 1, sep="\t")

t.reap_protein_3 <- read.table("GSM2685260_protein_3_Donor_1_with_aCD27_matrix.txt.gz", row.names = 1, sep="\t")
t.reap_protein_4 <- read.table("GSM2685261_protein_4_Donor_1_with_aCD27_matrix.txt.gz", row.names = 1, sep="\t")

names(t.reap_protein_3[1])

ut.reap_rna_combined <- Matrix(as.matrix(cbind(ut.reap_rna_1, ut.reap_rna_2)), sparse = TRUE)
t.reap_rna_combined <- Matrix(as.matrix(cbind(t.reap_rna_3, t.reap_rna_4)), sparse = TRUE)

ut.reap_protein_combined <- Matrix(as.matrix(cbind(ut.reap_protein_1, ut.reap_protein_2)), sparse = TRUE)
t.reap_protein_combined <- Matrix(as.matrix(cbind(t.reap_protein_3, t.reap_protein_4)), sparse = TRUE)

rownames(ut.reap_protein_combined) <- make.unique(paste0("REAP_", sapply(rownames(ut.reap_protein_combined), ExtractField)))
rownames(t.reap_protein_combined) <- make.unique(paste0("REAP_", sapply(rownames(t.reap_protein_combined), ExtractField)))

# Set up control object
ctrl <- CreateSeuratObject(raw.data = ut.reap_rna_combined, project = "IMMUNE_CTRL", min.cells = 5)
ctrl@meta.data$Stim <- "CTRL"
ctrl <- NormalizeData(ctrl)
ctrl <- ScaleData(ctrl, display.progress = F)
ctrl <- SetAssayData(ctrl, assay.type = "REAP", slot = "raw.data", new.data = ut.reap_protein_combined[, ctrl@cell.names])
ctrl <- NormalizeData(ctrl, assay.type = "REAP", normalization.method = "genesCLR", display.progress = FALSE)
ctrl <- ScaleData(ctrl, assay.type = "REAP",do.scale=TRUE, display.progress = TRUE)

# Set up stimulated object
stim <- CreateSeuratObject(raw.data = t.reap_rna_combined, project = "IMMUNE_STIM", min.cells = 5)
stim@meta.data$Stim <- "STIM"
stim <- NormalizeData(stim)
stim <- ScaleData(stim, display.progress = F)
stim <- SetAssayData(stim, assay.type = "REAP", slot = "raw.data", new.data = t.reap_protein_combined[, stim@cell.names])
stim <- NormalizeData(stim, assay.type = "REAP", normalization.method = "genesCLR", display.progress = FALSE)
stim <- ScaleData(stim, assay.type = "REAP", do.scale=TRUE, display.progress = TRUE)

# Gene selection for input to CCA
ctrl <- FindVariableGenes(ctrl, do.plot = F)
stim <- FindVariableGenes(stim, do.plot = F)
g.1 <- head(rownames(ctrl@hvg.info), 1000)
g.2 <- head(rownames(stim@hvg.info), 1000)
genes.use <- unique(c(g.1, g.2))
genes.use <- intersect(genes.use, rownames(ctrl@scale.data))
genes.use <- intersect(genes.use, rownames(stim@scale.data))

immune.combined <- RunCCA(ctrl, stim, num.cc = 30)

**Comment by satijalab** [comment]
In Seuratv3, the REAP assay will be retained after integration. You can just run FindMarkers, with assay="REAP", and it will return protein markers.
