### ISSUE TITLE
Heatmap-like Dimplot

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#1128]
Hi! I'm trying to do some visualization on UMAP for all cells on a defined score. numeral scores for all cell are kept in metadata. I want to color low-score cell light color and high-score cell dark color in UMAP. However, when I set group.by to the score, it does not give me a heatmap-like UMAP plot. Intead, it treated all unique numerical score as a group and colored based on such discrete group. I'm wondering if there anyway to do heatmap-like Dimplot. Also, how to use color palette on cols.use

thanks!

**Comment by andrewwbutler** [comment]
Hi,

It's likely that the numerical score you're referring to is stored as a factor in the metadata and that's why it's treating each score as a group. You can convert it with `as.numeric`.
