### ISSUE TITLE
Normalize Data

### ISSUE THREAD

**Issue by shaaaarpy** [satijalab/seurat#1129]
My expression matrix has negative values and when i try to run normalise data function, it doesn't perform anything because it uses log normalisation. Is there any other method available in seurat analysis?
Thank you

**Comment by timoast** [comment]
How did you get negative expression values? That would never happen unless you have already transformed the raw data in some way

**Comment by shaaaarpy** [comment]
Hi
Yes i transformed the raw data with some calculations and it has negative
values in it. How can i normalise this?

Thank you

**Comment by timoast** [comment]
Can you provide information about how you transformed the data?
