### ISSUE TITLE
How to set specific tsne key legend?

### ISSUE THREAD

**Issue by muktad** [satijalab/seurat#113]
Hi. I am trying to build tsne using my own gene lists using genes.use. It works fine except the key stays 0,1,2... and does not change to my gene names. Is there a quick way I can achieve this?  I basically want my plot legend to look like the figure under Run Non-linear dimensional reduction (tSNE) in this tutorial: https://github.com/satijalab/seurat/issues/new

**Comment by leonfodoulian** [comment]
The link you provided in your issue does not redirect to the Seurat guided tutorial. However, if I understood correctly, you want to rename the default identities attributed to your clusters after running `FindClusters() `?

One possible way would be to use what is already proposed in the tutorial (see [Assigning cell type identity to clusters](http://satijalab.org/seurat/pbmc3k_tutorial.html)).

Another way to do that would be to rename the clusters in the plot, by passing to `scale_color_discrete` a vector of labels. The code would look something like this:

```
# Vector of new names for each cluster
> new.cluster.names <- c(...)
# Plot tSNE with new cluster names
> TSNEPlot(object = object, do.return = TRUE) +
  scale_colour_discrete(labels = new.cluster.names)
```

Best,
Leon

**Comment by muktad** [comment]
Hi, I am getting the following error: 
> TSNEPlot(pbmc) + scale_colour_discrete(labels = new.cluster.ids)
Error in TSNEPlot(pbmc) + scale_colour_discrete(labels = new.cluster.ids) : 
  non-numeric argument to binary operator

I tried to change new.cluster.ids to numeric using : as.numeric(as.character(unlist(new.cluster.ids)) but it introduces NAs
Here is the right link to which I was originally referring to: http://satijalab.org/seurat/seurat_clustering_tutorial_part1.html

**Comment by satijalab** [comment]
Thanks Leon! you can also use RenameIdent to rename cluster IDs

**Comment by muktad** [comment]
Thanks for all your suggestions. The easiest way to fix it was to change the color.ids to a factor.
