### ISSUE TITLE
Combine Ctrl + Stim and then run Cell Cycle Scoring 

### ISSUE THREAD

**Issue by aalshawli** [satijalab/seurat#1131]
Dear All
 
I have 10x data for treated and untreated cancer cell line.  I need to combine the two sets and as the gene expression is affected by the cell cycle I need to run the cell cycle scoring.  Then I need to extract the gene expression for each phase of cell cycle for both the control and the treated cells.

I tried the following: 

1- combine the two and then sore the cell cycle => the identity of the gene expression was for the cycle phase and I could not identify in which condition the gene is up or down regulated.

2- Score the cell cycle for each condition and then combine the two  => The results were not consistent all the G1 phase were upregulated, where the G2M and S were downregulated.  And then compared to the results of the CellRange Aggr they were different.     

I used FindAllMarkers function to extract the FC_log expression but I could not know to which condition the expression values are related to.

Could you let me know how should I do it, 

What Function should I use to compare the expression between the crtl and the stim of the same cluster?
and how can I know if the logFC values are for the treated or untreated condition, please.

Could you help, please.

Thank you so much 

Best wishes, 

ABS

**Comment by satijalab** [comment]
Please see https://satijalab.org/seurat/v3.0/immune_alignment.html for a description of how to compare gene expression for the same cell type across different environmental conditions.

For cell cycle scoring, I apologize that I cannot fully understand your question. Cell Cycle scores are calculated *within* a cell, so it should not make a difference if you calculate them on the merged object, or on each object independently. It sounds like in your case, the treatment itself affects cell cycle stage. We certainly see this as well, as stimulating cells can arrest them - which sounds like what you are observing also.
