### ISSUE TITLE
Comparing pooled and unpooled samples: is multiCCA always necessary?

### ISSUE THREAD

**Issue by kmuench** [satijalab/seurat#1132]
Hello,

I'm comparing changes in cell population sizes, and differential expression, between four different conditions. The data were collected using the 10x Chromium and prepared to their standard pipeline. We tried to sequence all samples to the same depth, which ended up being ~50-80,000 reads/cell. 

I have 3 biological replicates (i.e., tissue from 3 individuals) per condition. However, some of my samples were pooled before sequencing, AND more cells collected per samples, such that some .mtx files only have 1000 cells (1000 cells from 1 individual) and other .mtx files have 10,000 cells (5,000 cells apiece from 2 individuals that were pooled together).

**My questions:** 
1. Is it even possible to include samples in a condition where some have 1,000 cells collected, and others 10,000 cells? Do I need to randomly subset the pooled samples until the number of cells is the same? Is it fine as long as my four conditions are perfectly balanced?

2. If I don't see obvious batch effects (see attached PCA), should I load all of these .mtx file into the same Seurat object for clustering and comparison of populations between condition, or should I load samples into separate Seurat objects, use MultiCCA, and follow vignettes like these?:
https://satijalab.org/seurat/immune_alignment.html
https://github.com/satijalab/seurat/issues/889

Here is an example of the sample metadata:

SampleID | Condition | Total Number of Cells | SampleCollection Date | 
------------ | ------------- | ------------- | ------------- | 
ID1 | A | 1000 | Day 1
ID2 | A | 10,000 | Day 2
ID3 | A | 1000 | Day 3
ID4 | B | 1000 | Day 1
ID5 | B | 10,000 | Day 2
ID6 | B | 1000 | Day 3
ID7 | C | 1000 | Day 1
ID8 | C | 10,000 | Day 2
ID9 | C | 1000 | Day 3
ID10 | D | 1000 | Day 1
ID11 | D | 10,000 | Day 2
ID12 | D | 1000 | Day 3

 I'm also attaching a picture of the PCA plot generated of my data - first two PCs - here, "1000" means unpooled samples with 1000 cells/individual, and "5000") means the pooled samples that have 5000 cells/individual.
[testDataPCA_pc1_pc2_CellsPerSample.pdf](https://github.com/satijalab/seurat/files/2849510/testDataPCA_pc1_pc2_CellsPerSample.pdf)

**Comment by timoast** [comment]
The different number of cells is not really a problem. To assess whether there is a batch effect, you can look at the tSNE or UMAP computed on the principal components, rather than just looking at the first 2 PCs. If you decide there is a batch effect, you might want to try our newer integration methods in Seurat v3 rather than MultiCCA (see https://satijalab.org/seurat/pancreas_integration_label_transfer.html)
