### ISSUE TITLE
Looking for Demultiplexing options without a HTO matrix file

### ISSUE THREAD

**Issue by unknowledgeable1** [satijalab/seurat#1133]
Hi,
I am new to scRNAseq analyses and R.
I have a question which would seem to be a general one about demultiplexing.

Using 10x Genomics 5' prime gel bead labeling kits, I collected barcoded single cell PBMC's from 8 different people.

The samples were again barcoded before being loaded into a flow cells for sequencing. 3 flow cells were run, fastq's, etc were generated and the samples were aggregated to produce a filtered_gene_bc_matrices_h5.h5 file consisting of ~30,000 cells.

The resulting data file appears to use the following structure:
colnames consisting of [cell barcodes plus a subject identifier (in my case numbers 1 through 8)]. the number of columns is roughly 30,000 with ~4000 good cells from each subject.
The colnames read like "AAACCTGAGGGTCTCC-1" for this cell from subject one, "AAACCTGAGATGCCAG-2" for that cell from subject 2 and so on...
rownames are the [gene names].

My impression is that this problem is similar to the 8 person "Demultiplexing with hashtag oligos" vignette. I am looking for a way to subset cells to specific people so that each one (or groups of them) can be assayed by Seurat... I think HTO is how I would do this but I do not have a HTO count matrix to load (only the h5 file). Also, since the .h5 file has subject identifiers attached with each cell (eg "-1", "-2", "-3", "-4"... "-8"), it seems like there is adequate information built into this file inorder to achieve the desired workflow allowing each person to be assayed independently.

Is there a way to do this? Do I even need an HTO-like demultiplex in this scenario? If there's no way to do this without the HTODemux, then is there a way to create a HTO matrix file from the h5 or some other method?

Any help would be AWESOME! I've been working on this for weeks and haven't been able to figure it out... like I said, I'm new to R.

Thanks,

**Comment by timoast** [comment]
This is not really the same problem that the cell hashing method (HTO) aims to address, since you have done separate 10x runs for each sample. In your case, it sounds like you want to split the Seurat object according to sample (or just add sample metadata). Since 10x adds a sample suffix to the cell barcode, you can add that information when you create the Seurat object by specifying the `names.delim` and `names.field` parameters, eg:

```r
obj <- CreateSeuratObject(counts = counts, names.field = 2, names.delim = "-")
```

This will split the cell barcode using the `-` character and create a metadata column from the second field, called `orig.ident`. You can then split the object according to sample:

```r
obj.list <- SplitObject(object = obj, split.by = "orig.ident")
```

This will give a list of objects, each containing one sample.

**Comment by unknowledgeable1** [comment]
I will try this right away but in the interim, let me just say, you have
made me teary with joy! Thank you kindly! **crosses fu gers**

**Comment by unknowledgeable1** [comment]
**fingers**

**Comment by unknowledgeable1** [comment]
This worked well. Can I get a bit more help?
The dataset contains 8 people, which I just identified individually by the orig.ident info you described above. There are 3 treatment groups amongst the 8 people: Persons [1,2,5,6,7] are treatment X, Persons [3, 8] are treatment Y, and lastly Persons [4] are treatment Z.

How would I also add a metadata field identifying which treatment group they are in?

**Comment by timoast** [comment]
You can add metadata like that by doing:

```r
lookup <- function(x) {
  if(x %in% c(1,2,5,6,7)) {
    return('X')
  }
  else if(x %in% c(3,8)) {
    return("Y")
  }
  else if(x ==4) {
    return("Z")
  }
  else{
    stop("Unkown identity")
  }
}

object$treatment <- sapply(Idents(object), lookup)
```
