### ISSUE TITLE
Can not find genes

### ISSUE THREAD

**Issue by fangge-Li** [satijalab/seurat#1135]
Hi there,
In the input file, some genes' name with "()" or "-" can not be found when "FeaturePlot" was submitted.  Could you tell me how Seruat recognizes "()" or "-" in genes' name in version3. 
Thank you so much!

Best,
FG

**Comment by andrewwbutler** [comment]
Thanks for reporting. This should be fixed as of 3acf165. Reinstalling should resolve this issue.
