### ISSUE TITLE
FeaturePlot ordering in Seurat v3

### ISSUE THREAD

**Issue by mgfield** [satijalab/seurat#1137]
In the new Seurat version 3, within FeaturePlot there is a parameter to order the plotting of features.  No matter what I try to put in for that order value, I cannot get any change in the order of plotting.  Could someone provide an example on how to do that?

Thanks so much!

**Comment by timoast** [comment]
You can change the order of plotting features by changing the order they appear in the `features` argument. The `order` argument does something else, it is not used to order the features. `order` specifies how the points are plotted in each individual plot (ie which cells are on the top and which are on the bottom)
