### ISSUE TITLE
Code no longer running - invalid character indexing

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1138]
Hello!

Thanks for developing such a powerful scRNAseq tool! 
I ran my 10x samples through pipeline for the v3 prelease without any issues many times. 
I then combined 2 samples using UMAP, FindIntegrationAnchors, and IntegrateData. Finally I went onto monocle to make a pseudotime.  

Now that I'm going back to my original code it wont run. When running the percent.mito, I get the error 
"Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing"
 
I'm trying to trouble shoot but am not sure how to proceed. I've reinstalled Seurat and loaded packages, restarted the R session. Any ideas?

Heres my code: 

```
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
library(Seurat)
library(ggplot2)
library(cowplot)
library(Matrix)

org <- Read10X(data.dir = './org/outs/filtered_feature_bc_matrix/')

exp.mat <- read.table(file = "~/Downloads/nestorawa_forcellcycle_expressionMatrix.txt",header = TRUE, as.is = TRUE, row.names = 1)
cc.genes <- readLines(con = "~/Downloads/regev_lab_cell_cycle_genes.txt")
s.genes <- cc.genes[1:43]
g2m.genes <- cc.genes[44:97]
mito.features <- grep(pattern = "^MT-", x = rownames(x = org), value = TRUE)
            
org <- CreateSeuratObject(counts = org, min.cells = 5, min.features = 200, project = "10X_org")
percent.mito <- Matrix::colSums(x = GetAssayData(object = org, slot = 'counts')[mito.features, ]) / Matrix::colSums(x = GetAssayData(object = org, slot = 'counts'))
           

```

**Comment by andrewwbutler** [comment]
Hi,

I think what's happening here is that you're defining `mito.features` before running `CreateSeuratObject` which will potentially filter our some features based on the thresholds you've set. If one of those features that gets filtered is also in `mito.features` this would cause your indexing error as you're trying to pull out rows that no longer exist. Try moving the line where you set `mito.features` to after `CreateSeuratObject`.

```r
mito.features <- grep(pattern = "^MT-", x = rownames(x = org), value = TRUE)
```
