### ISSUE TITLE
Origin of Cell Cycle Annotation Genes?

### ISSUE THREAD

**Issue by kvittingseerup** [satijalab/seurat#1139]
According to the documentation of the ```Seurat::cc.genes``` data object these gene sets were defined in [Tirosh _et al_ 2016](http://science.sciencemag.org/content/352/6282/189) (fits with table 5). In that paper Tirosh & co extracted “A core set of cell cycle genes was induced in both low-cycling and high-cycling tumors" and which are based on genes defined in 4 different papers which as far as I can tell all actually refer back to [Whitfield et al 2002](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC117619/). Whitfield _et al_ is micro array time course study of initially synchronised HeLa S3 cells with includes a lot of strange things in the methods section including manual removal of data, removal of principal components without explanation and knn imputation to fill in missing values.

Where the list of cell cycle genes further verified or does it all go back to HeLa cell cycle genes cells which have been reduced to genes used in metastatic melanomas?

**Comment by satijalab** [comment]
We'd be happy if you would like to propose an improved list of genes. These were defined in melanoma, but we have noticed extreme conservation of the core machinery of the cell cycle across scRNA-seq experiments. Essentially all of the genes that we use also were cell-cycle dependent in the barnyard mixing experiments of the first Drop-seq paper
