### ISSUE TITLE
possible error in pbmc3k tutorial?

### ISSUE THREAD

**Issue by amisharin** [satijalab/seurat#114]
Hi Seurat team, 

I was running Pbmc3k tutorial with Seurat 2.0.0.9 and got error with "Scaling the data and removing unwanted sources of variation": when running command
pbmc <- ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito"))
I get this error:
Error in ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito")) : 
  unused argument (vars.to.regress = c("nUMI", "percent.mito"))

I check the help file for ScaleData command and it seems that the correct argument is latent.vars instead of vars.to.regress. After replacing it with latent.vars everything worked well. R code on github uses vars.to.regress and not latent.vars. I am surprised that I am the first person to report this. Could you, please, clarify? 

Thank you

Alexander

**Comment by leonfodoulian** [comment]
Hi Alexander,

Seurat v2.0.0.900 (a pre-release of v2.0.0 - notice that the names of the versions are different) still uses the old function names, as in 1.4.0. The guided tutorial corresponding to this version of Seurat can be found [here](http://satijalab.org/seurat/pbmc3k_tutorial_1_4.html). You can also find the codes of these 2 releases [here](https://github.com/satijalab/seurat/releases). 

To use the current tutorial you have to install v2.0.0.

Best,
Leon

**Comment by amisharin** [comment]
Leon, thank you for your quick response. You are correct. After upgrading to 2.0 it runs as specified. I am closing the ticket. 
Thank you
Alexander
