### ISSUE TITLE
min.cells doesn't take into account is.expr in CreateSeuratObject

### ISSUE THREAD

**Issue by dhb2128** [satijalab/seurat#1141]
Hi, 

I ran into what I think is an error when I was trying to create a new seurat object. I want to only keep genes that are expressed with at least 2 UMIs in at least 3 cells . Based on the documentation, I was under the impression that running ` CreateSeuratObject(df, is.expr = 1, min.cells = 2)` should produce this result.

However, looking at the code:
```
if (min.cells > 0) {
    num.cells <- rowSums(object@data > 0)
    genes.use <- names(x = num.cells[which(x = num.cells >= min.cells)])
    object@raw.data <- object@raw.data[genes.use, ]
    object@data <- object@data[genes.use, ]
}
```
It looks that `is.expr` is not taken into account for detecting `num.cells`.

I believe the more appropriate line would be `num.cells <- rowSums(object@data > is.expr)`

Do you agree? If so, should I submit a PR with this fix?

Best,
David

**Comment by andrewwbutler** [comment]
I agree that the initialization here wasn't always the most intuitive. In Seurat v3, for clarity we've removed the `is.expr` parameter and recommend that users filter the input matrix before calling `CreateSeuratObject`.

**Comment by SeadonXing** [comment]
In Seurat version 2.3.4 , there are commands above is : 
if (is.expr > 0) {
        suppressMessages(expr = object.raw.data[object.raw.data < 
            is.expr] <- 0)
    }
So I think its take is.expr into account.
