### ISSUE TITLE
Error in mutate_impl(.data, dots) says: 'from' must be a finite number

### ISSUE THREAD

**Issue by unknowledgeable1** [satijalab/seurat#1142]
I run the alignment vignette on my dataset and have gotten stuck at the SplitDotPlotGG with the following error, can anyone help resolve this?

sdp <- SplitDotPlotGG(pbmc, genes.plot = rev(markers.to.plot), cols.use = c("green", "blue", "red"), x.lab.rot = T, plot.legend = T, dot.scale = 8, do.return = T, grouping.var = "Group")
Error in mutate_impl(.data, dots) : 
  Evaluation error: 'from' must be a finite number.
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
> traceback()
13: stop(list(message = "Evaluation error: 'from' must be a finite number.", 
        call = mutate_impl(.data, dots), cppstack = NULL))
12: mutate_impl(.data, dots)
11: mutate.tbl_df(., avg.exp.scale = as.numeric(x = cut(x = MinMax(data = avg.exp, 
        max = col.max, min = col.min), breaks = 20)))
10: mutate(., avg.exp.scale = as.numeric(x = cut(x = MinMax(data = avg.exp, 
        max = col.max, min = col.min), breaks = 20)))
9: function_list[[k]](value)
8: withVisible(function_list[[k]](value))
7: freduce(value, `_function_list`)
6: `_fseq`(`_lhs`)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
2: data.to.plot %>% ungroup() %>% group_by(genes.plot) %>% mutate(avg.exp = scale(x = avg.exp)) %>% 
       mutate(avg.exp.scale = as.numeric(x = cut(x = MinMax(data = avg.exp, 
           max = col.max, min = col.min), breaks = 20)))
1: SplitDotPlotGG(pbmc, genes.plot = rev(markers.to.plot), cols.use = c("green", 
       "blue", "red"), x.lab.rot = T, plot.legend = T, dot.scale = 8, 
       do.return = T, grouping.var = "Group")
>

**Comment by mojaveazure** [comment]
Hi @unknowledgeable1,

Sorry for the delay; does this still happen in Seurat v3 using `DotPlot` and the `split.by` parameter?
