### ISSUE TITLE
Imputed Data

### ISSUE THREAD

**Issue by silpasuthram** [satijalab/seurat#1143]
How do I plot "FeaturePlot" but using imputed data in Seurat v3.  The use.imputed option doesn't exist anymore.

**Comment by andrewwbutler** [comment]
In Seurat v3, I would store the imputed data as a separate `Assay`. For example:

```r
# e.g: some procedure that gives you back imputed count data (imputed.data)
# create an assay for the imputed data and
# store it in the Seurat object as the "imputed" assay
object[["imputed"]] <- CreateAssayObject(counts = imputed.data)
# switch the default Assay to "imputed" for ease of plotting
DefaultAssay(object = object) <- "imputed"
FeaturePlot(object = object, features = "X")
```

**Comment by silpasuthram** [comment]
Thank you.  Does FeaturePlot use "scale.data" by default? How can we set "slot" option in v3?

**Comment by andrewwbutler** [comment]
`FeaturePlot` will use "data". This function doesn't currently support plotting from any of the other slots.
