### ISSUE TITLE
RunMultiCCA in Seurat v3

### ISSUE THREAD

**Issue by Abghaith** [satijalab/seurat#1145]
Hi, 
I didn't find RunMultiCCA function in Seurat v3 package.
I have 8 samples processed in CITEseq experiment with 10X.

**Comment by andrewwbutler** [comment]
Hi,

We have a new workflow for integration in Seurat v3. Please see this [tutorial](https://satijalab.org/seurat/pancreas_integration_label_transfer.html) for an example.
