### ISSUE TITLE
AlignSubspace function unexistent in Seurat V3

### ISSUE THREAD

**Issue by pinhoribeirofa** [satijalab/seurat#1148]
Hello all
I am trying to run the function AlignSubspace in my CCA data but since I installed the Seurat v3 this function is not working anymore, can you guys help me with this? Bellow is the error message I am getting:

`> combined_cca <- AlignSubspace(combined_cca, reduction = "cca", grouping.var = "stim", dims.align = 1:20)
Error in AlignSubspace(combined_cca, reduction = "cca", grouping.var = "stim",  : 
  could not find function "AlignSubspace"`

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

We have a new workflow for integration in Seurat v3. Please see this [tutorial](https://satijalab.org/seurat/pancreas_integration_label_transfer.html) for an example.
