### ISSUE TITLE
failed to install the loom branch of Seurat

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1151]
**I need to Setup the loom Object following the protocol provided by https://satijalab.org/seurat/mca_loom.html,when I use the command(devtools::install_github(repo = 'satijalab/seurat', ref = 'loom') to install seurat from github,it showed many errors,I couldn't solve it.But when I use the command to install from CRAN(install.packages('Seurat'),it worked. Can anyone tell me the reason? 
To know which functions work on  loom objects, i use the methods function to list all functions where a method for loom objects has been defined.But it showed :> methods(class = "lfile")
no methods found. Do i have to install the the loom branch of Seurat to setup the loom object?**

![image](https://user-images.githubusercontent.com/30619010/52907750-c56f3080-32a2-11e9-93bf-ab6232d161a0.png)
![image](https://user-images.githubusercontent.com/30619010/52907799-d79d9e80-32a3-11e9-9457-9a6b199909db.png)
![image](https://user-images.githubusercontent.com/30619010/52907876-9d350100-32a5-11e9-9630-068b93f351fb.png)
![image](https://user-images.githubusercontent.com/30619010/52907875-973f2000-32a5-11e9-8577-d734f83e7cc8.png)
> devtools::install_github(repo = 'satijalab/seurat', ref = 'loom')
Downloading GitHub repo satijalab/seurat@loom
These packages have more recent versions available.
Which would you like to update?

1:   igraph (1.2.3 -> 1.2.4) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
caret        (NA    -> 6.0-81    ) [CRAN]
diffusionMap (NA    -> 1.1-0.1   ) [CRAN]
FNN          (NA    -> 1.1.3     ) [CRAN]
generics     (NA    -> 0.0.2     ) [CRAN]
gower        (NA    -> 0.1.2     ) [CRAN]
igraph       (1.2.3 -> 1.2.4     ) [CRAN]
ipred        (NA    -> 0.9-8     ) [CRAN]
lava         (NA    -> 1.6.5     ) [CRAN]
lubridate    (NA    -> 1.7.4     ) [CRAN]
ModelMetrics (NA    -> 1.2.2     ) [CRAN]
numDeriv     (NA    -> 2016.8-1  ) [CRAN]
prodlim      (NA    -> 2018.04.18) [CRAN]
ranger       (NA    -> 0.11.1    ) [CRAN]
RcppRoll     (NA    -> 0.3.0     ) [CRAN]
recipes      (NA    -> 0.1.4     ) [CRAN]
scatterpl... (NA    -> 0.3-41    ) [CRAN]
SQUAREM      (NA    -> 2017.10-1 ) [CRAN]
tclust       (NA    -> 1.4-1     ) [CRAN]
timeDate     (NA    -> 3043.102  ) [CRAN]
VGAM         (NA    -> 1.0-6     ) [CRAN]
Installing 20 packages: caret, diffusionMap, FNN, generics, gower, igraph, ipred, lava, lubridate, ModelMetrics, numDeriv, prodlim, ranger, RcppRoll, recipes, scatterplot3d, SQUAREM, tclust, timeDate, VGAM
Error: (converted from warning) unable to access index for repository https://mojaveazure.github.io/loomR/bin/windows/contrib/3.5:
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/windows/contrib/3.5/PACKAGES'
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> library(Seurat)
Error in library(Seurat) : 不存在叫‘Seurat’这个名字的程辑包
> install.packages("Seurat")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/Seurat_2.3.4.zip'
Content type 'application/zip' length 2045315 bytes (2.0 MB)
downloaded 2.0 MB

package ‘Seurat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\dell\AppData\Local\Temp\RtmpI7TP9f\downloaded_packages
> library(Seurat)
载入需要的程辑包：ggplot2
载入需要的程辑包：cowplot

载入程辑包：‘cowplot’

The following object is masked from ‘package:ggplot2’:

    ggsave

载入需要的程辑包：Matrix

**Comment by satijalab** [comment]
This should be fixed now that we have upgraded to Seurat v3. Apologies for the delay and hassle.

**Comment by Pickpickmee** [comment]
I met with a similar problem and I don't know what to do now
