### ISSUE TITLE
Is there a way to do within cluster DEG expression comparing two (or more) Tx groups in v3 pre-release?

### ISSUE THREAD

**Issue by jevanveen** [satijalab/seurat#1152]
Any help or pointers in the right direction would be highly appreciated. I've tried to adapt this workflow which I was using in 2.x:

dragonvslizard@meta.data$celltype.cond <- paste0(dragonvslizard@ident, "_", dragonvslizard@meta.data$cond)
dragonvslizard <- StashIdent(dragonvslizard, save.name = "celltype")
dragonvslizard <- SetAllIdent(dragonvslizard, id = "celltype.cond")
cluster0.firebreath <- FindMarkers(dragonvslizard, ident.1 = "0_dragon", ident.2 = "0_lizard", print.bar = FALSE, logfc.threshold = 0.001)

Using some of the new commands, I can generate the same identifiers (0_dragon, 0_lizard) but cannot stash them in active.ident because they contain characters. I can store them in meta.data, but FindMarkers doesn't look there when I try to find DEGs. Is there a workaround for this? I was thinking of maybe generating a numerical code for each condition (i.e. dragon = 100, lizard = 200) such that I change active ident from (0... 32) to (100... 232) and then run:

FindMarkers(dragonvslizard, ident.1 = "101", ident.2 = "201", print.bar = FALSE, logfc.threshold = 0.001)

but maybe there is a better way to do this? Thanks as always for your help!!

**Comment by jevanveen** [comment]
nm, found helpful old issues

**Comment by unknowledgeable1** [comment]
I have the same issue. How did you solve it?

**Comment by jevanveen** [comment]
I used the v3 command Idents() as such:

Idents(object = dragonvslizard) <- paste0(dragonvslizard@active.ident, "_", dragonvslizard@meta.data$group)

I had defined "group" before integration by:

dragons <- AddMetaData(object = dragons, metadata = "firebreathing", col.name = "group")
lizards <- AddMetaData(object = lizards, metadata = "nofire", col.name = "group")

this results in active.idents within the object going from 0, 1, 2, ... to 0_firebreathing, 0_nofire, etc... Then you can just pass those idents to FindMarkers as in version 2.x

**Comment by unknowledgeable1** [comment]
Thanks. I will try this!
