### ISSUE TITLE
Error in plotting TSNE using do.hover=True

### ISSUE THREAD

**Issue by leafyes** [satijalab/seurat#1154]
Hi 
I want to plot an interactive graph of TSNE, using`TSNEPlot(object = cel.seq, do.label = TRUE, pt.size = 0.5, do.hover = TRUE, data.hover = c("ident",  "PC1", "nGene"))`, but it sent an error:

> Error in viewer(index_html) :
>   'browser' must be a non-empty character string
> Warning messages:
> 1: In if (is.na(col)) { : The length of the condition is greater than one, so only the first element can be used
> 2: In if (is.na(col)) { : The length of the condition is greater than one, so only the first element can be used
> 3: `error_y.color` does not currently support multiple values.
> 4: `error_x.color` does not currently support multiple values.
> 5: `line.color` does not currently support multiple values.

The traceback():

> 5: stop("'browser' must be a non-empty character string")
> 4: viewer(index_html)
> 3: html_print(htmltools::as.tags(x, standalone = TRUE), viewer = if (view) viewerFunc)
> 2: print.htmlwidget(x)
> 1: function (x, ...)
>    UseMethod("print")(x)

I don't know why, could you help me ? Thank you very much.

**Comment by leafyes** [comment]
If I remove the parameter “do.hover = TRUE”，no errror reported.

**Comment by satijalab** [comment]
In Seurat v3 we now have a `HoverLocator` function that replaces the previous do.hover argument, and should fix this issue. More info at https://satijalab.org/seurat/essential_commands.html
