### ISSUE TITLE
error in install seurat V3

### ISSUE THREAD

**Issue by ysu2015** [satijalab/seurat#1155]
Hi,

I am trying to install Seruat V3 using the command line below.
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')

I have devtools installed.
But get error message 
Downloading GitHub repo satijalab/seurat@release/3.0
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Error in length(file_list) > 0 : error in running command
In addition: Warning messages:
1: In system(paste(TAR, "--version >", tf, "2>&1")) :
  error in running command
2: In system(cmd) : error in running command
3: In utils::untar(tarfile, ...) :
  ‘/bin/gzip -dc '/tmp/Rtmp7YOzTi/file75337da0b3d.tar.gz' | /bin/gtar -xf '-' -C '/tmp/Rtmp7YOzTi/remotes75332dd2e665'’ returned error code 127
4: In system(paste(TAR, "--version >", tf, "2>&1")) :
  error in running command

**Comment by andrewwbutler** [comment]
Hi,

This looks like a system problem. Here's a similar issue with a few proposed solutions that you could try.

 https://github.com/IRkernel/IRkernel/issues/487

**Comment by ysu2015** [comment]
Thanks a lot for the help. I will give a try.
