### ISSUE TITLE
Seurat v2.3.4: Error in FindClusters/RunModularityClusteringCpp

### ISSUE THREAD

**Issue by kmuench** [satijalab/seurat#1156]
Hello,

I am trying to work through the CCA tutorial on my own dataset of ~80,000 cells: https://satijalab.org/seurat/immune_alignment.html

I can get through the construction of the tSNE, before clustering, just fine:

```
chosen_res <- 1.2
chosen_cc <- 26

## make tSNE
### t-SNE and Clustering
print('Making tSNE...')
print(paste0('System time: ', Sys.time())) 
data.combined <- RunTSNE(data.combined, reduction.use = "cca.aligned", dims.use = 1:chosen_cc, do.fast = T)
 
save(data.combined, file= paste0('data.combined_withTSNE_r', chosen_res, '_CC', chosen_cc, '.RData') )

### Function to visualize tSNE
 visTSNE <- function(data.combined, myGroup){
 
     p3 <- TSNEPlot(data.combined, do.return = T, pt.size = 0.5, group.by = myGroup) 
    # save output

    ggsave(file = paste0( 'tSNE_group_', myGroup, '_res', chosen_res, '_CC', chosen_cc, '.pdf' ), plot = p3, device='pdf')
}

visTSNE(data.combined, "stim")
```

However, when I attempt to do FindClusters, like so:

```
data.combined <- FindClusters(data.combined, reduction.type = "cca.aligned", resolution = chosen_res, dims.use = 1:chosen_cc, nn.eps = 0.5)
```

...I get the following error:

```
Loading required package: Matrix
Computing nearest neighbor graph
Computing SNN
Error in RunModularityClusteringCpp(SNN, modularity, resolution, algorithm,  : 
  Not compatible with requested type: [type=character; target=double].
Calls: FindClusters ... RunModularityClustering -> RunModularityClusteringCpp
Execution halted
```

I get this error if I do reduction.type="cca" as well, but not if I do reduction.type="pca"(in that case it quits before even constructing the NN graph because I did not run PCA in this analysis, just RunMultiCCA). 

Running MakeSparse() on data.combined right before the FindClusters() line doesn't affect the error at all. 

My interpretation of this error is that there might be something wrong with passing in reduction.type to RunModularityClusteringCpp, but RunTSNE is able to use cca.aligned, and it exists within the Seurat object:

```
> names(data.combined@dr)
[1] "cca"         "cca.aligned"

```
Any ideas as to what might be going on? Thank you very much for your help.

**Comment by andrewwbutler** [comment]
Hi,

This looks to be a type issue with the parameters being passed to `FindClusters`. Can you make sure that `chosen_res` is numeric and not a character.

**Comment by kmuench** [comment]
Hello,

Thank you very much for your help with this issue.

Indeed, it seemed like this was a type issue - thank you so very much for pointing this out. The problem was that I was importing the parameter chosen_res from arguments passed in from a script. I had missed that the type was character because 'chosen_res' and 'chosen_cc' had only been used in the context of a statement like dims.use = 1:chosen_cc, which is itself an integer and wouldn't throw an error. Adding as.numeric(chosen_res) corrected the issue.

## 
Slightly longer explanation for others who might be googling this error, or who are learning how to run R via scripts on a cluster:

In order to run this code, I have two scripts. One is the actual R script itself, and the other is a script that submits my code to a scheduler on my computational cluster.

> submitJob.sh
```
#!/bin/bash
# SBATCH --nodes=1
# [ Other parameters go here]

# Arguments passed into myRScript.R: 1. chosen_res, 2. path_to_data.combined
Rscript myRScript.R 1.2 /path/to/data.combined.RData
```


> myRScript.R
```
# Title: My R Script
# By: Kristin Muench

# load library
library('Seurat', lib.loc='/path/to/seurat_2.3')

# import arguments
args <- commandArgs(TRUE)
chosen_res <- args[1]
print(chosen_res) # this should print out 1.2
class(chosen_res) # this is a character
class(1:chosen_res) # this is an integer

# In order to pass chosen_res into FindClusters, it has to be a numeric
data.combined <- FindClusters(data.combined, reduction.type = "cca.aligned", resolution = as.numeric(chosen_res), dims.use = 1:40, nn.eps = 0.5)
```
