### ISSUE TITLE
issue on re-encode for v3

### ISSUE THREAD

**Issue by mgood2** [satijalab/seurat#1157]
There is a character "–" causing an encoding issue on windows.
generics.R line 224
dimensional_reduction.R line 1288
Could you fix this issue "–" --> "-"
Thank you~

**Comment by mojaveazure** [comment]
Hi Eddie,

Thanks for the catch! I've replaced the dashes with standard hyphens at the lines you noticed; can you let me know if we've fixed this or if there are more places where we have non-Windows friendly characters?
