### ISSUE TITLE
How does Seurat generate violin plots?

### ISSUE THREAD

**Issue by j3gu** [satijalab/seurat#1158]
Hello,

I am curious about how Seurat generates violin plots. When I used ggplot2 to make violin plots for marker genes, I had issues with low-expressed genes, which give high density of zeros and low density of non-zeros. This makes the violin plots to have really narrow width on the top and flat shape at the bottom. Did you set up a threashold for number of zeros to be shown in violin plots? 

Thanks so much.
Jing

**Comment by andrewwbutler** [comment]
Hi,

You can see the relevant lines for how Seurat handles violin plots [here](https://github.com/satijalab/seurat/blob/37a3750f599fc4c0e1226aced130441a8b250077/R/plotting_internal.R#L628-L737). We don't threshold the number of zeros. If you have a lowly expressed gene with a lot of zeros, that is generally the shape that I would expect to see (wide bottom, narrow top).

**Comment by j3gu** [comment]
Got it. Thank you for your help.
