### ISSUE TITLE
A question about PBMCs analysis using Seurat

### ISSUE THREAD

**Issue by ZhenyiWangTHU** [satijalab/seurat#1159]
Dear Seurat developers,
Could you tell me what marker genes of each cell type are you using to identify cell types in the 33K pbmc data set on your web site(https://satijalab.org/seurat/get_started_v1_4.html)? I didn't find that in the command lines you provide.
I'm using Seurat to analyze this data set. And I want to cluster these cells and identify what cell types these clusters are. So the marker genes of each cell types in pbmc are really helpful to me. 
I'm really appreciate it if you can provide me these marker genes.
My e-mail address is wangzy17@mails.tsinghua.edu.cn
Regards,
Zhenyi Wang

**Comment by satijalab** [comment]
We go over this in the attached webinar : https://www.nature.com/webcasts/event/defining-the-immune-system-at-single-cell-resolution-with-seurat/
