### ISSUE TITLE
Comparative analysis

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#116]
Hi,

Is there a way to do comparative analysis between samples in different time points using seurat? We want to pick out the cells and genes that are differentially expressed in on time point over the other.

Thanks,

Bibaswan

**Comment by satijalab** [comment]
We have tutorials and vignettes at satijalab.org/seurat to demonstrate how to compare different populations from scRNA-seq, including new functionality on aligning shared cell states across datasets.
