### ISSUE TITLE
10X scATAC-seq

### ISSUE THREAD

**Issue by JBreunig** [satijalab/seurat#1160]
I saw that some modifications were being made to v3.0 for scATAC data.  

Do you have a general workflow for 10X scATAC datasets or vignette for scATAC processing?  We have matched 10X scRNA-seq and scATAC-seq datasets from the same sample (though not the exact same cells) and would like to try to use v3.0 to try to find the anchors and jointly visualize them.

**Comment by timoast** [comment]
Hi, we're working on a scATAC/scRNA integration vignette that will be released in the coming weeks

**Comment by JBreunig** [comment]
Congrats on the CRAN release!

Am I missing the scATAC/scRNA vignette or is it still forthcoming?

**Comment by timoast** [comment]
Hi @JBreunig, the integration vignette for RNA and ATAC data has not been released yet, but will be soon. I will close this issue when it is released

**Comment by timoast** [comment]
The vignette is now online here: https://satijalab.org/seurat/v3.0/atacseq_integration_vignette.html
