### ISSUE TITLE
Subset error

### ISSUE THREAD

**Issue by unknowledgeable1** [satijalab/seurat#1161]
Hi,
I have a meta.data$Group with 3 different possible variables "rock", "paper", and "scissors". I am trying to subsetdata using only "rock" and "scissors" but not using "paper" (which happens to be in the middle of the dataset). The dataset is already scaled.

I can make separate subsetdata objects for "rock" and "scissors" but cannot seem to get one object with both by using the subsetdata function.

When I use the subsetdata function like this (below), I make an object that's smaller than expected and creates the following error:

> subset_pbmc3 <- SubsetByPredicate(object = pbmc_copy, +                            vars.use = c("Group"), +                            predicate = "Group == c('rock','scissors')") >  > View(subset_pbmc3) Warning message: In paste(format.fun(x), collapse = " ") :   restarting interrupted promise evaluation Error in if (more \|\| nchar(output) > 80) { :    missing value where TRUE/FALSE needed
--
 
subset_pbmc1 (aka "rock") is a Large Seurat object at 3.6GB  (which seems correct)
subset_pbmc2 (aka "scissors") is a Large Seurat object at 1.9GB (which seems correct)
subset_pbmc3 (which should be "rock" and "scissors" but excluding "paper") is a Large Seurat object at 2.8GB (which doesn't seem correct)

How do I correctly subset out these 2 subgroups? Is there an easier way? Any help would be great and very appreciated.
Thanks in advance!

**Comment by andrewwbutler** [comment]
Hi,

You can use the `SubsetData` function as follows:

```R
subset_pbmc3 <- SubsetData(object = pbmc_copy, subset.name = "Group", accept.value = c("rock", "scissors"))
```

**Comment by unknowledgeable1** [comment]
thank you kindly! you guys are awesome at helping us figure this stuff out!
your efforts are sooo very appreciated by the community!
