### ISSUE TITLE
the output of FindConservedMarkers 

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#1164]
Dear all,  

as 'm using FindConservedMarkers() in order to compare a a cell cluster in 2 conditions ( "STZ" vs "WT"), if I may ask a very simple question, please : 

what is the the meaning/interpretation of the columns in the output file ?

i.e.   

```
STZ_p_val | STZ_avg_logFC | STZ_pct.1 | STZ_pct.2 | STZ_p_val_adj | 
WT_p_val | WT_avg_logFC | WT_pct.1 | WT_pct.2 | WT_p_val_adj | 
max_pval | minimump_p_val
```

thanks a lot !

-- bogdan

**Comment by andrewwbutler** [comment]
Hi,

The purpose of `FindConservedMarkers` is to find features that are markers in all groups (or conditions in your case). Basically, this amounts to splitting the dataset based based on condition, running separate differential expression tests, and combining the results. The `X_p_val`, `X_avg_logFC`, `X_pct.1`, `X_pct.2`,  and `X_p_val_adj` mean the same thing as they do in `FindMarkers`, just restricted to only the cells present in group X (see the [DE vignette](https://satijalab.org/seurat/de_vignette.html) for details). The `max_pval` is the maximum p-value across all groups. The `mimimump_p_val` represents one way of doing a meta-analysis of significance values (combining p-values across different tests). We use the metap R package for these functions and this can be modified via the `meta.method` parameter in `FindConservedMarkers`.

**Comment by tanasa** [comment]
Thank you Andrew ! 

Seurat is a great package : I am glad that it covers most of the analysis we do need ;)

**Comment by vincr04** [comment]
Thanks for these explanations, @andrewwbutler. However I am unsure whether it makes sense to use minimump_p_val as it is, or whether it would be a good idea to correct it for multiple comparisons with Bonferroni, as for p_val_adj?
