### ISSUE TITLE
Error in UpdateSeuratObject

### ISSUE THREAD

**Issue by koetjen** [satijalab/seurat#1165]
I just updated from version 2 to version 3. I ran UpdateSeuratObject on our previous Seurat object and received this error:

Error in UpdateJackstraw(old.jackstraw = old.dr[[i]]@jackstraw) : 
  no slot of name "jackstraw" for this object of class "dim.reduction"

The Seurat object was initially created in version 1, then used UpdateSeuratObject to version 2 and had been working well there.

Thanks -- Kary

**Comment by andrewwbutler** [comment]
Hi,

I haven't been able to reproduce this issue updating a Seurat object from v2 to v3. Are you able to share the object (or a random downsample that reproduces the error)? 

Alternatively, we do provide a [cheatsheet](https://satijalab.org/seurat/essential_commands.html) and an updated [3k tutorial](https://satijalab.org/seurat/pbmc3k_tutorial_v3.html) to help port over any v2 code you might have to rerun the analysis from the raw data.

**Comment by koetjen** [comment]
Thanks for your help. 

My downsampled object is still more than 1GB with only 60 cells remaining, and is available at this link: https://www.dropbox.com/l/scl/AAAWXcFPnfstF8LJVCKZChL1gbpK6EPMY6I
This still reproduced the error, but I noticed that adding “do.clean=T” allowed it to update to version 3. Can tSNE coordinates be easily accessed in a version 3 object to bring them in from a previous version or cloupe file?

Kary

**Comment by andrewwbutler** [comment]
Hi Kary,

Looks like something a bit strange happened at some point (probably in an update from v1 to v2). However, you should be able to work around the issue as follows:

```R
dim.reduction <- setClass(
  Class = "dim.reduction",
  slots = list(
    cell.embeddings = "matrix",
    gene.loadings = "matrix",
    gene.loadings.full = "matrix",
    sdev = "numeric",
    key = "character",
    jackstraw = "ANY",
    misc = "ANY"
  )
)

for(i in names(x = downsample@dr)) {
  downsample@dr[[i]]@jackstraw <- NULL
}

updated.v3.object <- UpdateSeuratObject(object = downsample)
```

You can access the tSNE coordinates in version 3 as follows:

```R
Embeddings(object = object[["tsne"]])
```

**Comment by koetjen** [comment]
Thanks so much, this is very appreciated.
Kary
