### ISSUE TITLE
Scaledata()  calculation formula 

### ISSUE THREAD

**Issue by leafyes** [satijalab/seurat#1166]
Hi，
I konw use ScaleData() function could  calculate the object@data to object@scale.data, but I don't know the  detailed calculation process. If I run `object=ScaleData(object)`, what is its formula?  And I find the mean value of the scaled data is not 0 , Could you help me ? Thaks a lot.
Best,
zjl

**Comment by andrewwbutler** [comment]
Hi,

`ScaleData` will perform feature(gene)-level scaling, meaning that each feature will be centered to have a mean of 0 and scaled by the standard deviation of each feature (like how base R `scale` works). However, we do set the `scale.max` parameter to 10 by default to help reduce the effects of outliers/genes expressed in a very small percentage of cells. This could cause the means of some genes after scaling to be non-zero as it clips their scaled value to 10.

**Comment by leafyes** [comment]
Thank you very much! And I am wondering the parameter "vars.to.regress", I found if I add the `vars.to.regress="UMI"` in scale() function, the tSNE plot is different from that not adding the `vars.to.regress="UMI"`. What is the significance of doing regression? and does it necessary to doing regression? 
Best,
zjl

**Comment by andrewwbutler** [comment]
Yes, regressing out variables should change your downstream results. The idea here is to construct a linear model to predict gene expression based on user-defined variables (`vars.to.regress`). The scaled z-scored residuals of these models are then used as `scale.data`. This can sometimes be useful to remove unwanted sources of variation in the data though the appropriateness of doing so will depend on the dataset you're working with.

**Comment by leafyes** [comment]
Thanks a lot. Please forgive my ignorance, can I ask another question? If I set the  parameter `vars.to.regress="UMI"`, does this means the UMI is my unwanted source of variation?

**Comment by andrewwbutler** [comment]
Yes, that means whatever information you have encoded in the metadata column called "UMI" gets regressed out as "unwanted variation".

**Comment by bounlu** [comment]
What's the difference between ScaleData and z-score?

**Comment by mreza-ef** [comment]
Hello, could you please clarify the context or provide more information about the "split.by" arguments in ScaleData?  how this might impact batch effects in a merged object?
Thanks
