### ISSUE TITLE
Seurat object with multiple original identities : How to plot independently from orig.ident?

### ISSUE THREAD

**Issue by eheude** [satijalab/seurat#1167]
Hi,
I am currently working with a seurat object containing 21 original identities (21 sequencing pools).
When I plot (ex. VlnPlot for nGene, nUMI, percent.mito), it clusters cells by original identity by default (1 plot/orig.ident).
How can I  visualize all cells in one plot independently from their orig.ident ?
Thanks

![rplot](https://user-images.githubusercontent.com/47827451/53185111-a522d700-35fe-11e9-9d62-7d9d67b92904.png)

**Comment by harinipras** [comment]
For version 3, this code will work
```javascript
levels(obj@active.ident) 
```
#i.e if you have 44 levels
44
```javascript
levels(obj@active.ident) <- rep("anythign",44)
```

**Comment by eheude** [comment]
It works! Many thanks
