### ISSUE TITLE
VlnPlot Iterations

### ISSUE THREAD

**Issue by efheuston** [satijalab/seurat#117]
Hi Seurat team--

I am fairly new to R, so I hope this is not a silly question. In Seurat v1 I created a for-loop to run both VlnPlot and FeaturePlot on a list of genes. In Seurat v2, VlnPlot no longer renders but FeaturePlot does render. Here is my code:

geneList=c("Gata1", "Gata2")

drawmyplot<-function(){
  for(gene in geneList){
    VlnPlot(mouse.tsne, gene)
    FeaturePlot(mouse.tsne, gene)
  }
}

drawmyplot()

There aren't any errors when the code runs. It simply doesn't display the VlnPlot.

If I run VlnPlot(mouse.tsne, gene) outside of the function, it renders the violin plot exactly as I'd expect.

Do you have any advice?

Thanks,

E

**Comment by satijalab** [comment]
you can set do.return=T to return a ggplot object
