### ISSUE TITLE
problem with loading data generated by Cell ranger v3

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#1171]
Hi ,
I have successfully installed Seurat v3:

> packageVersion(pkg = "Seurat")
[1] ‘3.0.0.9000’

But here is what I get when I am trying to load the data:

> CD3_CR3_2.data <- Read10X(data.dir = "~shendong/Desktop/CD3_GEX_CR3filt")
Error in Read10X(data.dir = "~shendong/Desktop/CD3_GEX_CR3filt") : 
  Gene name file missing

The problem that I see is the path of filtered_bc_matrices generated by Cellranger3 is:
/outs/filtered_feature_bc_matrix/barcodes.tsv.gz 
/outs/filtered_feature_bc_matrix/features.tsv.gz  
/outs/filtered_feature_bc_matrix/matrix.mtx.gz

I could go further in the analysis by opening the gz files and changing the name of features.tsv to gene.tsv but at the next step:

pbmc <- CreateSeuratObject(counts = pbmc.data, min.cells = 3, min.features = 200, project = "10X_PBMC")

I have the following error:

Error in new(Class = "seurat", raw.data = raw.data, is.expr = is.expr,  : 
  argument "raw.data" is missing, with no default
In addition: Warning messages:
1: In mget(objectNames, envir = ns, inherits = TRUE) :
  restarting interrupted promise evaluation
2: In mget(objectNames, envir = ns, inherits = TRUE) :
  internal error -3 in R_decompress1
3: In mget(objectNames, envir = ns, inherits = TRUE) :
  restarting interrupted promise evaluation
4: In mget(objectNames, envir = ns, inherits = TRUE) :
  internal error -3 in R_decompress1

The problem I think comes from the fact that data generated from cell ranger 3 is not the usual format outs/filtered_gene_bc_matrices/GRCh38/(barcodes.tsv  genes.tsv  matrix.mtx) but look like this:

/outs/filtered_feature_bc_matrix/barcodes.tsv.gz 
/outs/filtered_feature_bc_matrix/features.tsv.gz  
/outs/filtered_feature_bc_matrix/matrix.mtx.gz

It is probably a very simple thing that I am missing but I am very new at this and would appreciate some guidance.

Thank you very much for your help!

**Comment by timoast** [comment]
It looks like you still have version 2 loaded. Try restarting your R session and verifying that Seurat v3 is loaded by running `sessionInfo()` before running the commands.

**Comment by shendong124** [comment]
I started a new session and it worked!

Thank you very much!
