### ISSUE TITLE
Seurat v3.0: Error: 'merge' is not an exported object from 'namespace:Seurat'

### ISSUE THREAD

**Issue by Thessentials** [satijalab/seurat#1175]
Just installed Seurat v3.0 and I'm having some trouble merging objects. No matter what alias I use, I can't seem to access the merge function. Any alias, either by itself or in conjunction with Seurat::, I use results in an error stating that the function cannot be found because it isn't in the namespace. I tried reinstalling the Seurat package but that didn't seem to fix the problem.

I have made sure to load the library, and pulling up the documentation for the function seems to work fine.

**Comment by andrewwbutler** [comment]
Hi,

Can you verify that all the objects you are trying to merge have been updated to be compatible with Seurat v3 (via `UpdateSeuratObject`)?

**Comment by Thessentials** [comment]
Yes. I was attempting to merge Seurat objects that I created for a new project today using the CreateSeuratObject function from Seurat v3. Creating the Seurat objects went smoothly.

I also attempted to simply run Seurat::merge and other aliases by themselves (executing only the function name in order to look at the code) to no avail. 

I also have tried this on different systems with different versions of R (3.4.1 and 3.5.2).

**Comment by andrewwbutler** [comment]
Can you post code you're running?  If you're going to use the double colon, you need to be calling `Seurat::merge.Seurat` .

**Comment by Thessentials** [comment]
Here is an example:

`> library(Seurat)
> Seurat::merge
Error: 'merge' is not an exported object from 'namespace:Seurat'
> Seurat::merge.Seurat
Error: 'merge.Seurat' is not an exported object from 'namespace:Seurat'
> Seurat::CreateSeuratObject
function (counts, project = "SeuratProject", assay = "RNA", min.cells = 0, 
    min.features = 0, names.field = 1, names.delim = "_", meta.data = NULL) 
{
    assay.data <- CreateAssayObject(counts = counts, min.cells = min.cells, 
        min.features = min.features)
    Key(object = assay.data) <- paste0(tolower(x = assay), "_")
    assay.list <- list(assay.data)
    names(x = assay.list) <- assay
    init.meta.data <- data.frame(row.names = colnames(x = assay.list[[assay]]))
    idents <- factor(x = unlist(x = lapply(X = colnames(x = counts), 
        FUN = ExtractField, field = names.field, delim = names.delim)))
    if (any(is.na(x = idents))) {
        warning("Input parameters result in NA values for initial cell identities. Setting all initial idents to the project name")
    }
    ident.levels <- length(x = unique(x = idents))
    if (ident.levels > 100 || ident.levels == 0 || ident.levels == 
        length(x = idents)) {
        idents <- rep.int(x = factor(x = project), times = ncol(x = counts))
    }
    names(x = idents) <- colnames(x = counts)
    object <- new(Class = "Seurat", assays = assay.list, meta.data = init.meta.data, 
        active.assay = assay, active.ident = idents, project.name = project, 
        version = packageVersion(pkg = "Seurat"))
    object[["orig.ident"]] <- idents
    n.calc <- CalcN(object = assay.data)
    names(x = n.calc) <- paste(names(x = n.calc), assay, sep = "_")
    object[[names(x = n.calc)]] <- n.calc
    if (!is.null(x = meta.data)) {
        object <- AddMetaData(object = object, metadata = meta.data)
    }
    return(object)
}
<bytecode: 0x111c344a0>
<environment: namespace:Seurat>`

**Comment by andrewwbutler** [comment]
Try using a triple colon instead of the double colon if you want to access the code. However, this shouldn't be necessary to run the code. You should be able to just call `merge`:

```R
merge(object1, object2)
```

**Comment by mojaveazure** [comment]
@Thessentials Seurat doesn't define `merge`, but `merge.Seurat` (an [S3 method](https://stackoverflow.com/questions/6583265/what-does-s3-methods-mean-in-r) for R's [`merge`](https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/merge) function).

What this means is rather than define a new merging function, we simply define how `merge` works on Seurat objects (the same way `print` works differently for lists and vectors compared to data frames). As such, you shouldn't need to ever call `merge.Seurat`, simply calling `merge` on Seurat objects should be enough for R to figure out how to merge your objects.

You can see a list of various functions for which we've defined methods for the Seurat object (meaning you shouldn't call `<function name>.Seurat`) with `methods(class = 'Seurat')`. Anything that looks similar to normal R functions (eg. `merge`, `dim`, `subset`, etc.) should never need the colons (`::`) to work on a Seurat object.

**Comment by Thessentials** [comment]
Ah I see, thank you very much! I was initially wary of simply calling the merge function since it appeared to still be coming from base R instead of the Seurat package, hence my use of the double colon. Your explanation makes sense.

Thanks for the great package!
