### ISSUE TITLE
How to create a seurat object selecting a subset of cells positive for two genes of interest

### ISSUE THREAD

**Issue by eheude** [satijalab/seurat#1176]
Hi,
I am working with a large scRNAseq dataset. 
I would like to create a Seurat object selecting only cells positive for two genes of interest.
How can I do it?
Thanks

**Comment by andrewwbutler** [comment]
Hi,

Please see the `SubsetData` function (for Seurat v2) or the `subset` function (for Seurat v3) to take specific subsets of cells from a Seurat object that meet some criteria for the expression level of a given gene(s).
