### ISSUE TITLE
FeaturePlot filtered low expression points?

### ISSUE THREAD

**Issue by iiiir** [satijalab/seurat#1177]
Hi,

I checked several of my genes using feature plot and it seems that some genes with expression, but not showing colors. e.g. there are 8 cells below but when i plot it is only showing 1:

```R
> myproject@data[c("CD8A","CD8B"),cell_check]
2 x 8 sparse Matrix of class "dgCMatrix"
     D8_P6_M15 E2_P6_M17 C1_P4_M23 F11_P2_M9_L001 H9_P2_M9_L001 B4_P5_M83_L001 D11_P4_M91_L001
CD8A      8.56      1.08      1.93           1.04           1.2           1.81            1.51
CD8B      3.14      .         .              .              .             .               .   
     H6_P3_M91_L001
CD8A           2.62
CD8B           .   

> FeaturePlot(myproject, features.plot = c("CD8A","CD8B"), overlay = T,
             cells.use = cell_check,
             cols.use = c("grey","blue","green","red"),
             pt.size = 2,min.cutoff = 0,max.cutoff = 25)
```

![image](https://user-images.githubusercontent.com/4137873/53427915-cba69080-39b7-11e9-9f81-83eb0abf0aac.png)

**Comment by mojaveazure** [comment]
Hi Shuoguo,

The way that overlayed `FeaturePlot`s work is by using [`cut`](https://www.rdocumentation.org/packages/base/versions/3.5.2/topics/cut) to split the expression of each feature into "high" and "low" values. We then color each cell based on whether it falls into the 'high' category for the first feature, the second feature, both features, or neither feature.

In this case, the seven grey points are cells that fell into the "neither" category, while the red point is the cell that had high expression in both categories (I'm guessing this is `D8_P6_M15`, but you can verify that with `do.hover = TRUE`). So, all eight cells are plotted here and colored correctly.
