### ISSUE TITLE
how to delete custom additional column from seurat metadata?Help!

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1179]
I add some columns of custom metadata by using the Seurat v3.X command(object$name <- vector),but I can't delete these columns,such as "time","hours".I try many many ways,like subset, subsetdata,and test.tc11$hours >- NULL, all them didn't work.
Can you help me?
```
> test.tc11$hours <- rep("E14",7303)
> tail(x = test.tc11[[]])
                      orig.ident nCount_RNA nFeature_RNA percent.mito RNA_snn_res.0.8 letter.idents time DAY hours
A_TTTGTCACATTGGTAC SeuratProject       3987         1775            0               7             H  E11 E14   E14
A_TTTGTCAGTAAGTGGC SeuratProject       4299         1992            0               7             H  E11 E14   E14
A_TTTGTCAGTAGGACAC SeuratProject       6994         2448            0               0             A  E11 E14   E14
A_TTTGTCAGTAGGCATG SeuratProject       7906         2588            0               4             E  E11 E14   E14
A_TTTGTCAGTCTCATCC SeuratProject      24778         5035            0               8             I  E11 E14   E14
A_TTTGTCAGTTCTGTTT SeuratProject       8209         2628            0               2             C  E11 E14   E14
```

**Comment by Thessentials** [comment]
I believe you could just do the following, although there may be better ways.

```
> test.tc11@meta.data <- test.tc11@meta.data[, -which(colnames(test.tc11@meta.data) %in% 'hours')]
```

**Comment by mojaveazure** [comment]
This was an oversight on our part, you should now (as of commit 49eae61) be able to remove metadata columns using either `[[` or `$`

```R
object$column.to.remove <- NULL
object[['column.to.remove']] <- NULL
```

Thanks for bringing this up!

**Comment by Sophia409** [comment]
@mojaveazure  I still could't be able to remove metadata columns using either `[[` or `$`.But I can delete it using this command :
`test.tc11@meta.data <- test.tc11@meta.data[, -which(colnames(test.tc11@meta.data) %in% 'time')]`.What's the matter?
```
> head(test.tc11@meta.data)
                   time
A_AAACCTGAGCAGCGTA  E11
A_AAACCTGAGCGATGAC  E11
A_AAACCTGAGTACCGGA  E11
A_AAACCTGAGTGACTCT  E11
A_AAACCTGCAGTGGAGT  E11
A_AAACCTGCAGTTCCCT  E11
> test.tc11$time <- NULL
Error: Cannot find object time
> test.tc11[['time']] <- NULL
Error: Cannot find object time
```
```
> test.tc11@meta.data <- test.tc11@meta.data[, -which(colnames(test.tc11@meta.data) %in% 'time')]
> head(test.tc11@meta.data)
data frame with 0 columns and 6 rows
```

**Comment by mojaveazure** [comment]
Please make sure you reinstall Seurat v3 from GitHub from a fresh R session

```R
> devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
> library(Seurat)
> data(pbmc_small)
> pbmc_small
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne
> names(x = pbmc_small[[]])
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8"
[5] "letter.idents"   "groups"          "RNA_snn_res.1"  
> pbmc_small$groups <- NULL
> names(pbmc_small[[]])
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8"
[5] "letter.idents"   "RNA_snn_res.1"  
> pbmc_small[['letter.idents']] <- NULL
> names(x = pbmc_small[[]])
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8"
[5] "RNA_snn_res.1"
```

**Comment by Sophia409** [comment]
Thank you! It works. @mojaveazure @Thessentials

**Comment by Sophia409** [comment]
@mojaveazure Hello, mojaveazure.I have another question to consult you.
I need to merge my seurat data of 3 experimental time points with the Hippocampus data provided by [Guided Clustering of the Mouse Cell Atlas: loom edition.](http://mousebrain.org/tissues.html) I merged my own data by using the merge command and do trajectory analysis using monocle. But I don't know how to convert this loom file to seurat object or expression matrix, so that I can merge them with my data and do next analysis.
The tutorial says that : Seurat offers a conversion function to go from Seurat objects to loom files. The reverse conversion is currently in progress.
Does it means that I could't convert loom file to seurat? So what should I do to merge them? Can you give me some advice?Thank you very much!
![default](https://user-images.githubusercontent.com/30619010/53738357-f4ec8280-3ec9-11e9-92d9-49bb3ef82463.png)
