### ISSUE TITLE
Installation guide for Ubuntu

### ISSUE THREAD

**Issue by wyattmcdonnell** [satijalab/seurat#1183]
Hi all

Just getting our new Ubuntu box set up and completely forgot what a pain it is to set up Seurat from scratch on a new machine. Is there any interest in a more-complete installation guide for Debian/Ubuntu? If so I'd be happy to put a draft together including a long list of everything that needs to be called from `sudo apt-get install` and installing R from terminal too. 

Thanks
Wyatt

**Comment by mojaveazure** [comment]
Hi Wyatt,

Could you elaborate as to what problems you've been having installing Seurat on Ubuntu? I use Ubuntu 16.04 as my primary OS, and haven't had too many issues. Installation time is long (~40 minutes for Seurat v2), but that'll change with Seurat v3 (~20 minutes during my latest test a couple of months ago). However, I've been using this machine for a while, so it has a lot of stuff (dependencies) on it already.

I made a Docker image using Ubuntu 18.04 as the base to see what's needed from a bare-bones Ubuntu installation, and there aren't too many things. I've pasted the Dockerfile below, so you can see what's going on. Everything before adding the CRAN PPA for R can usually be skipped by the end user as most Ubuntu installations come with ca-certificates and GPG2 (Docker images tend to be even more stripped down than Ubuntu Desktop and Ubuntu Server images).

Overall, I've found three things besides R needed for Seurat v2.3.4 (from CRAN; I haven't tested Seurat v3 as that currently involves devtools, which won't be needed by most users and comes with its own host of system-level dependencies needed, but should be less than what's needed for v2.X): libhdf5-dev, libcurl4-openssl-dev, and libssl-devl; is there anything else that's been causing you issues?

```dockerfile
#   Docker image for the latest build of Seurat
FROM ubuntu:bionic

LABEL org.label-schema-version="latest" \
    org.label-schema.name="Seurat" \
    org.label-schema.name="Satija Lab" \
    org.label-schema.license="GPLv3" \
    org.label-schema.build-date=''


#   Set up the system for Seurat
#   Don't ask for user input
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
#   Configure tzdata (ish)
RUN echo 'tzdata tzdata/Areas select US' | debconf-set-selections
RUN echo 'tzdata tzdata/Zones/US select New York' | debconf-set-selections
#   Add CRAN PPA
RUN apt-get update
RUN apt-get install -y ca-certificates gnupg2
RUN echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" | tee --append /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
#   Install R
RUN apt-get update
RUN apt-get install -y r-base-dev

#   Install system Seurat dependencies
RUN apt-get install -y libhdf5-dev libcurl4-openssl-dev libssl-dev

#   Install Seurat
RUN R --slave --no-restore --no-save -e "install.packages('Seurat', repos='https://cloud.r-project.org')"

CMD [ "/bin/bash" ]
```

**Comment by saisomesh2594** [comment]
Hello All,

I am trying to install seurat on my Ubuntu 18.04 and keep running into dependency issues especially with openssl. I have openssl and libssl;dev install and yet the problem persists. 

So, I would very much appreciate a comprehensive installation guide for seurat. Any other help or direction is highly appreciated.

Thanks,
Somesh
![openssl](https://user-images.githubusercontent.com/22415829/54230653-2c30e400-4507-11e9-8c37-e9953319f0a8.png)

**Comment by wyattmcdonnell** [comment]
Hi @mojaveazure and @saisomesh2594 

For everything to work on a clean install of Xenial, I had to run the following (including installing some libraries that don't come with Xenial by default, which surprised me):

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install curl
sudo apt-get install openssl
sudo apt-get install libcurl4-openssl-dev
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
sudo apt-get update
sudo apt-get install r-base
sudo apt-get install libhdf5-dev
sudo apt-get install libhdf5-serial-dev
sudo apt-get install h5utils
sudo apt-get install hdf5-tools
sudo apt-get install hdf5-helpers

sudo -i R
```

**Comment by mojaveazure** [comment]
@saisomesh2594 Hi Somesh, this seems to be an issue with openssl, I suggest taking this up with them.

@wyattmcdonnell Hi Wyatt, huh, interesting. I don't think we'll be putting together a "complete guide" as this seems to vary system by system. We will release an official Docker image for Seurat in the near future for people who don't want to go through the hassle of installing the system dependencies for Seurat, but don't have more information at this time.

**Comment by smk5g5** [comment]
Is there an installation guide like this for macos because I am having all sorts of trouble installing seurat 3 on mac os catalina. My R version is 3.6.2 (2019-12-12). I would like to remove any current R installation and start from scractch to make Seurat work on mac. If there is installation guide for seurat in mac that would be great. Thanks!
