### ISSUE TITLE
Understand the ScaleData Function

### ISSUE THREAD

**Issue by NTNguyen13** [satijalab/seurat#1184]
Hi,

I'm new to using Seurat for scRNA-seq analysis. The tutorial on Seurat homepage very informative and helpful for using this package. 

I want to understand the ScaleData function as shown in this example:

`pbmc <- ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito"))`

as I read the document, this step is: "Scales and centers genes in the dataset. If variables are provided in vars.to.regress, they are individually regressed against each gene, and the resulting residuals are then scaled and centered.", but I don't understand how it was done.

For example, If I have this matrix
```
         A    B    C    D
Cell1    1    0    0    4
Cell2    0    1    2    0
Cell3   10    0    3    0
Cell4    0    3    0    1
```

then how the function operate and transform my data? Thank you in advance

**Comment by timoast** [comment]
Hi, please see #1166
