### ISSUE TITLE
Citeseq and scRNA-seq analysis 

### ISSUE THREAD

**Issue by sri540** [satijalab/seurat#1186]
I first ran scRNA-seq analysis and then ran CITE-seq analysis. Later, I made few changes to scRNA-seq pipeline, tried to generate a tSNE plot.  Instead of seeing a scRNA-seq tSNE, I'm seeing only CITE-seq feature plot. 

The data is stored in different slots, so I don't understand why I am not able to retrieve the scRNA-seq data after running CITE-seq analysis. 

#------------------------------------------------
seurat_obj <- CreateSeuratObject(raw.data=rna_common)
DimPlot(object = seurat_obj, 
        assay.type = "RNA"
        reduction.use = "tsne",
        pt.size = 1.0,
        cols.use=brewer,
        do.return = TRUE,
        vector.friendly = TRUE)

#------------------------------------------------
seurat_obj <- SetAssayData(seurat_obj, assay.type = "CITE", slot = "raw.data", new.data = citeseq_common)

FeaturePlot(seurat_obj, features.plot = c("tag1","tag2","tag3","tag4"),reduction.use = "tsne", min.cutoff = "q05", max.cutoff = "q95", nCol = 4, cols.use = c("lightgrey", "red"), pt.size = 0.5)

#------------------------------------------------

**Comment by andrewwbutler** [comment]
I'm not sure what the issue is here. If you want a standard "tSNE" plot you should run `DimPlot` as you did in the second line. If you are seeing a standard "feature plot", you likely ran the last `FeaturePlot` line of code.

**Comment by sri540** [comment]
I ran DimPlot to create a 'tSNE' plot, but once the CITE-seq analysis is run, I'm not able to generate the original tSNE even though I specified assay.type = 'RNA'.

**Comment by andrewwbutler** [comment]
Can you post all the code that you ran? 

Did you call `RunTSNE` on the CITE-seq data after creating the original tSNE plot? If so, did you also set the `reduction.name` to something other than "tsne"? If not, this would cause the original tsne coordinates calculated based on the RNA data to get overwritten by the tsne coordinates for the CITE-seq data.

**Comment by sri540** [comment]
I did n't call RunTSNE function on the CITE-seq data after creating the tSNE plot on scRNA-seq data. 

Code:
#----------------------------------------------------------------------------------------------------
#step 1 - scRNA-seq data
setwd("~/Desktop")
library(Seurat)
seurat_obj <- CreateSeuratObject(assay.type = "RNA",
                                 raw.data=rna_common)
#--------------------
#Normalize RNA data with log normalization
seurat_obj <- NormalizeData(seurat_obj,display.progress = FALSE,
                            normalization.method = "LogNormalize",
                            scale.factor = 10000)
#--------------------
#Find variable genes
seurat_obj <- FindVariableGenes(seurat_obj,mean.function = ExpMean, 
                                dispersion.function = LogVMR,
                                x.low.cutoff = 0.0125, 
                                x.high.cutoff = 3.5, 
                                y.cutoff = 0.5, 
                                do.plot = TRUE,
                                display.progress = FALSE)
length(x = seurat_obj@var.genes) #7992 genes
#--------------------
#scale data
seurat_obj <- ScaleData(seurat_obj,
                        vars.to.regress = c("nUMI"),
                        display.progress = FALSE)
#--------------------
#PCA
seurat_obj <- RunPCA(seurat_obj,
                     pc.genes = seurat_obj@var.genes,
                     do.print = TRUE, 
                     pcs.print = 1:5,
                     genes.print = 5)

#statistically significant principal components

PCElbowPlot(seurat_obj)

#--------------------
#Clustering 
seurat_obj <- FindClusters(seurat_obj,dims.use = 1:20,
                           resolution=1.5, 
                           reduction.type = "pca", 
                           print.output = FALSE)

#--------------------
#TSNE 
seurat_obj <- RunTSNE(seurat_obj, 
                      reduction.use="pca", 
                      dims.use = 1:20,
                      tsne.method = "Rtsne",
                      reduction.name = "tsne",
                      reduction.key = "tSNE_")
TSNEPlot(object = seurat_obj)


#----------------------------------------------------------------------------------------------------
#step 2
#LOAD CITESEQ DATA
seurat_obj <- SetAssayData(seurat_obj, 
                           assay.type = "CITE", 
                           slot = "raw.data", 
                           new.data = tags)
seurat_obj <- NormalizeData(seurat_obj, 
                            assay.type = "CITE", 
                            normalization.method = "genesCLR")
seurat_obj <- ScaleData(seurat_obj, 
                        assay.type = "CITE", 
                        display.progress = FALSE)

FeaturePlot(seurat_obj, 
            features.plot = c("TAG1","TAG2"), 
            reduction.use = "tsne",
            min.cutoff = "q05", 
            max.cutoff = "q95", 
            nCol = 2, 
            cols.use = c("lightgrey", "red"), 
            pt.size = 0.5)

#----------------------------------------------------------------------------------------------------
#step 3

TSNEPlot(object = seurat_obj, 
         assay.type = "RNA") #not working

#----------------------------------------------------------------------------------------------------

**Comment by andrewwbutler** [comment]
I was able to run the code successfully (substituting the RNA/ADT data from the multimodal tutorial). The specification of `assay.type="RNA"` to `TSNEPlot` isn't necessary but shouldn't cause issues. 

In what way is it not working? Is there an error message? If so, can you post the results of `traceback()`? Also are you working with the last v2 release (v2.3.4)?
