### ISSUE TITLE
Inconsistent results with FindIntegrationAnchors

### ISSUE THREAD

**Issue by csoneson** [satijalab/seurat#1188]
Dear Seurat developers,

we are running the new integration method, and noticed that in different environments (on the same hardware), we get very different numbers of anchors from the `FindIntegrationAnchors` function. Within a given environment, the results are reproducible. The differences seem to stem from the `RunCCA` function, and based on our testing may be due to differences between the BLAS libraries. We were wondering whether you had seen similar inconsistencies/dependencies on the (system) libraries, and if there are places in the `RunCCA` code that may be particularly sensitive. A similar issue seems to be reported in https://github.com/satijalab/seurat/issues/1077. 

More details:
* We have `R Under development (unstable) (2019-02-17 r76112)`, but the issue appears also under R v3.5.
* We run `Seurat v 3.0.0.9000 @0562c69`.
* We are running the exact code from the integration vignette (https://satijalab.org/seurat/pancreas_integration_label_transfer.html), up until the `FindIntegrationAnchors` step.

Environment 1 (`libopenblas-r0.3.3.so`) returns the following:
```
> pancreas.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
Computing 2000 integration features
Scaling features for provided objects
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 06s
Finding all pairwise anchors
   |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 3510 anchors
Filtering Anchors
        Retained 2759 anchors
Extracting within-dataset neighbors!
   |+++++++++++++++++                                 | 33% ~20s          Running CCA
Merging objects
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 3501 anchors
Filtering Anchors
        Retained 2729 anchors
Extracting within-dataset neighbors!
   |++++++++++++++++++++++++++++++++++                | 67% ~10s          Running CCA
Merging objects
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 6176 anchors
Filtering Anchors
        Retained 4561 anchors
Extracting within-dataset neighbors!
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 35s
```

Environment 2 (`libopenblas_skylakexp-r0.3.5.so`) returns the following:
```
> pancreas.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
Computing 2000 integration features
Scaling features for provided objects
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 05s
Finding all pairwise anchors
   |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 135 anchors
Filtering Anchors
        Retained 17 anchors
Extracting within-dataset neighbors!
   |+++++++++++++++++                                 | 33% ~22s          Running CCA
Merging objects
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 71 anchors
Filtering Anchors
        Retained 8 anchors
Extracting within-dataset neighbors!
   |++++++++++++++++++++++++++++++++++                | 67% ~11s          Running CCA
Merging objects
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 182 anchors
Filtering Anchors
        Retained 14 anchors
Extracting within-dataset neighbors!
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 36s
```

Any insights would be highly appreciated. 
Thanks!
Charlotte

**Comment by andrewwbutler** [comment]
Hi Charlotte,

Thanks for the detailed report! I've looked into this and was able to reproduce the issue when using R linked to `libopenblas_skylakexp-r0.3.5.so`. The issue traces back to the step in `RunCCA` where we perform an approximate svd via the `irlba` package. The issue can be seen as well by just running a comparison of that function under both setups:

```R
set.seed(1)
mat <- matrix(data = rnorm(n = 1e6), nrow = 1e3)
results <- irlba::irlba(mat, nv = 30)
results.base <- base::svd(mat, nv = 30)
```

Not yet sure exactly beyond that what the underlying cause might be. For now, I would recommend just using the internal BLAS provided with R.

**Comment by csoneson** [comment]
Hi Andrew,
Thanks for the quick reply! This is a good test case - I can confirm that I get wildly different results between `irlba` and `svd` with `libopenblas_skylakexp-r0.3.5.so`, but consistent ones with `libopenblas-r0.3.3.so`. 
Thanks,
Charlotte

**Comment by satijalab** [comment]
Thanks Charlotte for identifying this - we have always used default BLAS libs to my knowledge. It looks like this change would affect most steps in downstream Seurat analysis, or at least anything that leverages irlba

**Comment by csoneson** [comment]
Yes - it seems to be linked to a known issue with OpenBLAS on SkylakeX architecture (https://github.com/xianyi/OpenBLAS/issues/1955). We'll just stick to the standard R BLAS for now. Thanks.
