### ISSUE TITLE
FeaturePlot Seurat v3 Blend Function

### ISSUE THREAD

**Issue by whdmstjr0702** [satijalab/seurat#1189]
Hello, 

I am trying to visualize co-expression of two genes using blend function.  When used the "blend = T", the color gradient appears to be fixed between "Black", "Green", "Red", and "Yellow" even when I specify different color .  

I was wondering if there is a way for me to assign different colors.

The code I entered was:
` FeaturePlot(object = integrated.2, features = c("Krt5", "Krt14"), reduction = 'umap', pt.size = 1, blend = T, cols = c("grey", "red", "green", "blue"), min.cutoff = 0, max.cutoff = 5)
`

The plot I get from code above is as follow:
![krt5 krt14_combined](https://user-images.githubusercontent.com/46611286/53668649-1fc0a780-3c3a-11e9-8db2-5d2744acb6d6.jpeg)

**Comment by igordot** [comment]
It looks like the color scale is currently hard-coded based on `BlendMatrix()`: https://github.com/satijalab/seurat/blob/0562c6934ffe0a7ef219b7befed3194e3b3ec24c/R/visualization.R#L853-L861
Thus, only the default colors seem to be possible without modifying the function.

**Comment by yuhanH** [comment]
Yes. Currently, there are only default colors. Later, we can add more colors for this function.

**Comment by magiclafz** [comment]
Is that feasible to use both "blend" and "split by" together? To split the blend plot into different group?

**Comment by yuhanH** [comment]
I think there is a bug when you use `blend` and `split.by` together, and we will fix it soon.

**Comment by sameet** [comment]
Hi, 
I need to use `blend` with `split.by` for a data-set.  It should be possible from the way I think I understand the code is written.  But it gives an error 

    FeaturePlot(my.exp, c(gene.list.co[1], "eGFP"), blend = T, blend.threshold = 0.2, pt.size = 0.2, split.by = "seurat_clusters", ncol = 18)
    Error in levels(x = data$split)[[idx]] : subscript out of bounds

Is there a solution for this?

**Comment by sameet** [comment]
Also is there any way to grey out the cells that have no expression, so make it a bit easier on the eyes, instead the "black" color, which makes it a tad difficult to see.

**Comment by yuhanH** [comment]
Maybe you could try `+DarkTheme()`, but it will not print out axis labels and titles.
`blend` and `split.by` issue will be fixed in the next develop version.  Right now, you could split your objects and run `blend` respectively. Sorry for the inconvenience.

**Comment by semmrich** [comment]
I tried `+DarkTheme()`, was better to the eyes, but that gave a white grid into the background. Also tried with additional `+NoGrid()`, that did not remove it.
A bled from RColor gray90 to red vs gray90 to blue with blue over purple to red would be THE THING! Or just replace the current "darkgray" with gray90...
Would there be a way how I can fiddle with [seurat/R/visualization.R](url) @ [Lines 853 to 861 in 0562c69](url) like @igordot pointed out earlier?

However Thank you so much for this function in the first place, its very helpful and extremely informative! GREAT JOB!!

**Comment by Dragonmasterx87** [comment]
I was wondering what happened to the black color for double negatives....then I saw this post......Damn....Seurat is literally an organism, not code....it grows every day....lol
