### ISSUE TITLE
RunTSNE output has different levels of identity factors than number of genes specified

### ISSUE THREAD

**Issue by muktad** [satijalab/seurat#119]
Hi, when i try to run RunTSNEPlot with 5 genes the identity levels are 9. The TSNEPlot thus generated has key legends with 5 genes and 4NAs of different colors and the NA colors are plotted as well. What I am trying to do is look at specific genes and see their distribution amongst different cells.

I tried using RenameIdent, which gave me the following warnings:
>gocn<-RenameIdent(goc, old.ident.name = goc@ident, new.ident.name = goi)
 Warning messages:
1: In if (!old.ident.name %in% object@ident) { :
  the condition has length > 1 and only the first element will be used
2: In if (new.ident.name %in% old.levels) { :
  the condition has length > 1 and only the first element will be used
3: In if (!(new.ident.name %in% old.levels)) { :
  the condition has length > 1 and only the first element will be used
4: In is.na(e1) | is.na(e2) :
  longer object length is not a multiple of shorter object length
5: In `==.default`(new.levels, old.ident.name) :
  longer object length is not a multiple of shorter object length
6: In ident.vector[WhichCells(object, old.ident.name)] = new.ident.name :
  number of items to replace is not a multiple of replacement length
7: In `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  :
  duplicated levels in factors are deprecated 

If I ignore the warnings and go ahead with TSNEPlot anyway the legend looks fine, but I am afraid the plot looks weird.

**Comment by satijalab** [comment]
Please view the documentation for RenameIdent to learn more about proper usage
