### ISSUE TITLE
How to convert loom file to seurat object?help!!!

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1190]
Hello, @olgabot @farcasia @1j @gokceneraslan.I need to merge my seurat data of 3 experimental time points with the Hippocampus data provided by Guided Clustering of the Mouse Cell Atlas: loom edition. I merged my own data by using the merge command and do trajectory analysis using monocle. But I don't know how to convert this loom file to seurat object, so that I can merge them with my data and do next analysis.
The tutorial says that : Seurat offers a conversion function to go from Seurat objects to loom files. The reverse conversion is currently in progress.
Does it means that I could't convert loom file to seurat? So what should I do to merge them? Can you give me some advice?Thank you very much!
![default](https://user-images.githubusercontent.com/30619010/53692616-26802380-3dce-11e9-9a14-421dfa094c9a.png)

**Comment by Sophia409** [comment]
@mojaveazure

**Comment by PeteHaitch** [comment]
@Sophia409 Please stop tagging me in your questions about seurat.
I am not one of the developers.

**Comment by Sophia409** [comment]
@
