### ISSUE TITLE
error in install seurat3.0 

### ISSUE THREAD

**Issue by wupeng2** [satijalab/seurat#1191]
I try to install Seurat3.0 through the command above 
> devtools::install_github(repo = "satijalab/seurat", ref = "release/2.0")
Error in curl::new_handle() : An unknown option was passed in to libcurl
 there is a error information 
then I clone seurat from GitHub ,and install it 
installing to /public/home/wupeng1/software/R/install/lib64/R/library/Seurat3.0/libs
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘Seurat3.0’ in library.dynam(lib, package, package.lib):
 shared object ‘Seurat.so’ not found
错误: 载入失败
停止执行
ERROR: loading failed
* removing ‘/public/home/wupeng1/software/R/install/lib64/R/library/Seurat3.0’
Warning message:
In install.packages("/public/home/wupeng1/software/Seurat_3.0.0.9000.tar.gz",  :
  安装程序包‘/public/home/wupeng1/software/Seurat_3.0.0.9000.tar.gz’时退出狀態的值不是0.
I don't know who to deal with this problem.
thanks lot

**Comment by timoast** [comment]
Try running `devtools::install_github(repo = "satijalab/seurat", ref = "release/3.0")`

**Comment by iakovrudenko** [comment]
I had the same initial problem (using R version 3.5.3 on PC) tried the above suggestion and used devtools::install_github(repo = "satijalab/seurat", ref = "release/3.0") but got another mistake:

failed to lock directory 'C:/Users/Jacob/Documents/R/win-library/3.5' for modifying
Try removing 'C:/Users/Jacob/Documents/R/win-library/3.5/00LOCK-glue'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘glue’ had non-zero exit status

Any further advice?

Thanks

**Comment by mojaveazure** [comment]
Hi @iakovrudenko, can you try removing `C:/Users/Jacob/Documents/R/win-library/3.5/00LOCK-glue`, reinstalling glue (`install.packages('glue')`), then try reinstalling Seurat v3 if the installation of glue works?

**Comment by iakovrudenko** [comment]
Thank you very much for the advice. I tried it ut still got a Error at the end:

> install.packages('glue')
Installing package into ‘C:/Users/Jacob/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/glue_1.3.1.zip'
Content type 'application/zip' length 172471 bytes (168 KB)
downloaded 168 KB

package ‘glue’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘glue’

The downloaded binary packages are in
        C:\Users\Jacob\AppData\Local\Temp\RtmpwhSpzq\downloaded_packages
> install.packages('devtools')
Installing package into ‘C:/Users/Jacob/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/devtools_2.0.1.zip'
Content type 'application/zip' length 384687 bytes (375 KB)
downloaded 375 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Jacob\AppData\Local\Temp\RtmpwhSpzq\downloaded_packages
> devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
Downloading GitHub repo satijalab/seurat@release/3.0
Installing 1 packages: glue
Installing package into ‘C:/Users/Jacob/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.5/glue_1.3.1.zip'
Content type 'application/zip' length 172471 bytes (168 KB)
downloaded 168 KB

package ‘glue’ successfully unpacked and MD5 sums checked
Error: (converted from warning) cannot remove prior installation of package ‘glue’
> library(Seurat)
Error in library(Seurat) : there is no package called ‘Seurat’

Any other ideas?

**Comment by iakovrudenko** [comment]
Problem solved when I installed R studio instead of R 3.5.3 on the other computer. Thanks
