### ISSUE TITLE
Further subdivisions within clusters

### ISSUE THREAD

**Issue by semir2** [satijalab/seurat#1192]
Hello! I am tryed Further subdivisions within clusters, I used two different methons for do this. First, I followed the  manual with Further subdivisions within cell types （resolution=0.8），Second，I subset my data with special  cluster0 and run all pipeline such as  recalculate Variable Genes, scale, run PCA, and cluster（resolution=0.8）. I get different  sub-cluster0 ，I am confused which method is right.

First method,  cluster0 subdivided two sub-clusters.
![image](https://user-images.githubusercontent.com/46958122/53737349-40516180-3ec7-11e9-8aba-cacfa01da546.png)

Second method, cluster0 subdivided four sub-clusters.
![image](https://user-images.githubusercontent.com/46958122/53738228-93c4af00-3ec9-11e9-99ba-f80a9fdeafa9.png)

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

Determining the "right" set of clusters for a single-cell dataset is a challenging problem and often requires interpretation from a biological viewpoint. As mentioned in #819, this article provides a good review on single cell clustering.

https://www.nature.com/articles/s41576-018-0088-9

**Comment by semir2** [comment]
> Hi,
> 
> Determining the "right" set of clusters for a single-cell dataset is a challenging problem and often requires interpretation from a biological viewpoint. As mentioned in #819, this article provides a good review on single cell clustering.
> 
> https://www.nature.com/articles/s41576-018-0088-9

Many thanks
