### ISSUE TITLE
heatmap of cells with same TCRs

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#1194]
Hi,
I am using dataset from 10X gene expression and TCR sequencing. I am looking at the same patient PBMC through different time points before and after treatment. I would like to be able to generate heatmap of  gene expression (for a specific set of genes) within cells that keep the same TCR through the different treatment and time points.

I can get the barcodes of the cells with the same TCRs for each conditions but I am not sure how to generate the heatmap with the genes that I am interested in.

Thank you very much!

**Comment by andrewwbutler** [comment]
Hi,

You can provide a vector of gene names to either the`features` (in v3) or `genes.use` (in v2) parameter of `DoHeatmap`.

**Comment by Dragonmasterx87** [comment]
@andrewwbutler you the man bro. Vectoring 🤦‍♂️

**Comment by LIYANGYANGSIBS** [comment]
did u solve it? need to do similar analysis

**Comment by Dragonmasterx87** [comment]
@LIYANGYANGSIBS please read @andrewwbutler 's comment. Create a vector of required genes and generate a heatmap against that.

**Comment by shendong124** [comment]
Hi
I was able to use a vector with the genes I wanted to look at for a subset
of cells created according to the expression of gene (e.g. AIRE):

DoHeatmap(aire, features = c("AIRE", "CD3E", "CD4", "CD8A", "CD8B", "GZMB",
"FOXP3", "IFNG", "MKI67", "IL2RA", "CTLA4", "HLA-DRA", "HLA-DRB1",
"HLA-DRB5"))

But I am still trying to figure out how to subset the cells according to
their barcodes?

Thank you Seurat Team!
Shen
