### ISSUE TITLE
VlnPlot in a loop (follow up on #253)

### ISSUE THREAD

**Issue by CMC-LI** [satijalab/seurat#1195]
I followed the suggestions in thread [#253](https://github.com/satijalab/seurat/issues/253) to make VlnPlot in a for loop, but both options gave me the following error:
"Error in data.expression[vars.all[gene.check], cells.use, drop = FALSE] : 
  invalid or not-yet-implemented 'Matrix' subsetting"

Here is an example of what i did: 
gene.list <- list("Krt8", "Krt18", "Krt19")
for (i in 1:length(gene.list)) {
  plot.list[[i]] <- VlnPlot(object = seurat, features.plot = gene.list[i], do.return = TRUE)
}

Do you have suggestions for what could be done to get around this problem?  Thank you very much for your help!

**Comment by timoast** [comment]
You need to use the double bracket to access items in `gene.list`, ie:

```r
gene.list <- list("Krt8", "Krt18", "Krt19")
plot.list <- list()
for (i in 1:length(gene.list)) {
    plot.list[[i]] <- VlnPlot(object = seurat, features.plot = gene.list[[i]], do.return = TRUE)
}
```

**Comment by CMC-LI** [comment]
Thanks for catching the typo! I copy-pasted from the thread without realizing it was missing the double bracket.
