### ISSUE TITLE
No update, how to use Seurat 2.3.4 to analysis 10X cellranger V3 data ?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1196]
Hi all : 
   I use cellranger 3.0 to analysis 10X v3 samples.  And I want to use Seurat to do the downstream analysis.  I know that the Seurat 2.3.4 read the file in unzip format and need a file named genes.tsv.  So if I use Read10X in Seurat 2.3.4 function there will be a error occur.  My question is if I dont want to update my Seurat to version 3.0 , how can I use the Read10X function to handle 10X v3 data ?
    I try that  (1) unzip the three files to barcodes.tsv features.tsv and matrix.mtx
                    (2) rename the  features.tsv to  genes.tsv
                    (3) use Read10X function as before
 And there is no error and warnings , so I want to make sure that am I right to use Seurat 2.3.4 to analysis 10X cellranger V3 data ?

Best
Seadon

**Comment by andrewwbutler** [comment]
Hi,

`Read10X` is just a convenience function for loading in the data matrices to R. You can read more about how that data is formatted in Cell Ranger v3 [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices) and they give an example of how to read in the data as well. However, your strategy should work as long as you only have RNA features. If you measured additional modalities in your experiment (e.g. ADTs), these will be returned in the same matrix as the RNA features if you use the v2 version of the function. The v3 version will return them as a list of separate matrices.

**Comment by SeadonXing** [comment]
Thanks for reply !
    Exactly, my data only have RNA features.  The names in the third colum of features.tsv are all "Gene Expression" . So I think my  strategy is works !

Seadon
