### ISSUE TITLE
Problem with non-normalized data

### ISSUE THREAD

**Issue by cynthiazhou1005** [satijalab/seurat#120]
Dear Seurat developers,

I use to be able run previous version with data that I would like to not perform normalization.
However, now it raised problem when I tried to findvariablegenes....

```R
[1] "Calculating gene dispersion"
  |===========================================================| 100%
Error in text.default(x = gene.mean[pass.cutoff], y = gene.dispersion.scaled[pass.cutoff],  : 
  zero-length 'labels' specified
```

Although the graph shows all the genes are within my cutoff settings.

Is there a solution to that?

Thank you so much!

WZ

**Comment by andrewwbutler** [comment]
Can you provide either the data or the two series of commands you are comparing (the commands you ran before that worked in an earlier version and the commands you ran to get this error)?

**Comment by cynthiazhou1005** [comment]
with the same data:
old Seurat package:

C1_obj <- new("seurat", raw.data = FISHdata)
C1_obj <- Setup(C1_obj, min.cells = 3, min.genes =20,names.field = 1,names.delim = "_", do.logNormalize = F, is.expr = 0.6,total.expr = 1e6, project = "C1_Tcell")
C1_obj <- MeanVarPlot(C1_obj ,fxn.x = expMean, fxn.y = logVarDivMean, x.low.cutoff = 0.5, x.high.cutoff = 8, y.cutoff = 0.5, do.contour = F)

I was able to proceed with all the analysis


with the current Seurat 2.0/2.1:

C1_obj <- CreateSeuratObject(raw.data =  FISHdata, min.cells = 3)
C1_obj  <- FilterCells(C1_obj, subset.names = "nGene", low.thresholds = 20,  high.thresholds = Inf)
# C1_obj  <- NormalizeData(C1_obj)
C1_obj  <- FindVariableGenes(C1_obj, x.low.cutoff = 0.1)


then it pops our errors as described above....or issues that basically will get resolved once I run the NormalizeData command. My question is, if there is any possibility of not normalizing the data?

Thanks a lot,
WZ

**Comment by satijalab** [comment]
If you wish to not perform data normalization, you can simply set object@data = object@raw.data, as an alternative to normalization. Without seeing the data, we can't be certain about the origin of the text_labels error in your initial post.
