### ISSUE TITLE
Error in FindMarkers:Cell group 1 has fewer than 3 cells in identity class 1

### ISSUE THREAD

**Issue by leafyes** [satijalab/seurat#1200]
Hi,
When I run the command `cluster1.markers <-FindMarkers(object = cel.seq, ident.1 = 1, min.pct = 0.25)`, an error was reported :Cell group 1 has fewer than 3 cells in identity class 1。Then I ran the following command:
`ident.1=1`
`length(x = as.vector(x = ident.1))`
1
`cells.1 <- WhichCells(object = cel.seq, ident = ident.1)`
`length(x = cells.1)`
[1]448`
It showed that there were 448 cells in cell.1，which means that cell group 1 has more than 3 cells in identity class 1. 
The following shows some content of object@meta.data

  | nGene | nUMI | group | orig.ident | res.0.6
-- | -- | -- | -- | -- | --
509 | 663 | 1856 | group1 | 10Xdata0_8 | 1
508 | 463 | 1204 | group1 | 10Xdata0_8 | 1
499 | 725 | 1977 | group1 | 10Xdata0_8 | 1
493 | 805 | 1879 | group1 | 10Xdata0_8 | 1
490 | 816 | 2258 | group1 | 10Xdata0_8 | 1
489 | 638 | 1548 | group1 | 10Xdata0_8 | 1
488 | 786 | 2278 | group1 | 10Xdata0_8 | 1
483 | 881 | 2673 | group1 | 10Xdata0_8 | 1
482 | 757 | 2528 | group1 | 10Xdata0_8 | 1
478 | 749 | 2266 | group1 | 10Xdata0_8 | 1
477 | 698 | 2103 | group1 | 10Xdata0_8 | 1
476 | 762 | 1767 | group1 | 10Xdata0_8 | 1
472 | 540 | 1588 | group1 | 10Xdata0_8 | 1
466 | 704 | 2157 | group1 | 10Xdata0_8 | 1
464 | 914 | 2919 | group1 | 10Xdata0_8 | 1
463 | 741 | 2195 | group1 | 10Xdata0_8 | 1
460 | 854 | 2616 | group1 | 10Xdata0_8 | 1
452 | 756 | 2156 | group1 | 10Xdata0_8 | 1
448 | 599 | 1624 | group1 | 10Xdata0_8 | 1
435 | 782 | 2385 | group1 | 10Xdata0_8 | 1
 
In addition, my input data was filtered in other software，and with no filtering operation in Seurat。
I don't konw how to solve this problem,could you help me ? Thanks a lot.

**Comment by andrewwbutler** [comment]
Hi,

Are your cell names numbers? If so, this could throw things off as `FindMarkers` allows `ident.1/2` to be either an "identity" or a vector of cell names. If you have cell names that are the same as an identity class (e.g. a cell called "1"), then the set of cells that will be used for `ident.1` will just be the cell "1" instead of all cells belonging to class 1. If this is the case, I recommend adding some prefix to your cell names via `RenameCells` before running `FindMarkers`.

**Comment by leafyes** [comment]
Hi,
Thank you very much! I did what you said ,and it works correctly now!
Best.

**Comment by abedkurdi** [comment]
I am facing the same problem here when running `FindConservedMarkers` for integrated data, however, my cells' names are not numbers (i.e. s20_TGAGGAGCATCGCTGG-1). What should I do?

Thanks in advance.

**Comment by michael-kotliar** [comment]
@abedkurdi I had the same problem when running `FindConservedMarkers`. In my case I had `grouping.var="condition"` which left me only with 2 cells in one of the groups of a certain cluster.
