### ISSUE TITLE
Cross-species integration for Seurat(v3)

### ISSUE THREAD

**Issue by Roooosh** [satijalab/seurat#1201]
Hello Seurat team,
I was wondering about the computational decisions I should follow for a cross-species analysis in Seurat V3.

I understand how the analysis was done in Seurat V2 through the multi-CCA alignment. But in my scenario, I am modeling for both batch and species.

Here is my current workflow:
1. Perform integration analysis and annotate clusters on the Species 1.
2. Using the integrated object from Species 1, I project Species 2 on this reference to predict and quantify the cell identities in Species 2. 

Using the projection workflow, I think I have been able to achieve acceptable results without modifying the original gene-cell matrices.

I have also performed integration analysis of all of the datasets together (assuming that batch and species will be corrected at once), is this a reasonable assumption to make?? Should I perform this in a step-wise process(integrate batches first, then integrate species)?? For the latter point, is that possible? (note for this approach the original gene-cell matrices were filtered to only include high confidence, 1-1 orthologs)

Please let me know your thoughts, especially with the Seurat(v3) platform, as to which method seems most reasonable. Thanks!

And thanks for developing this package, it's been a real treat to use.

**Comment by andrewwbutler** [comment]
The integration procedure in v3 is inherently step-wise. One of the first things we do is build a "guide tree" based on similarity between datasets (see the [pre-print](https://www.biorxiv.org/content/early/2018/11/02/460147) for details) and recursively merge up the tree. In your case, I would imagine that the batches would fall closer on this guide tree than the species so in effect, you would be integrating batches first and then species. 

However, one argument for breaking the procedure into two explicit steps (first batches, then species) would be that if you integrate within a species first, you could have access to all genes (not only 1-1 orthologs) and this might result in better integration on the per-species level.

**Comment by Roooosh** [comment]
Thanks. I'll go ahead and move forward with your suggestion. You may close this issue
