### ISSUE TITLE
reset clusters

### ISSUE THREAD

**Issue by xnaer** [satijalab/seurat#1202]
Hi

I want to choose parts of the clusters to re-run CCA or PCA. Once I run 'subsetdata' function, should I normalize data again? I known 'scaledata' and 'findvariblegenes' are necessary, but how about 'normalizedata'? Are there any differences between redoing and not redoing 'normalizedata'?

Bests

Na

**Comment by andrewwbutler** [comment]
Hi,

Please see #678.
