### ISSUE TITLE
could not find function "DimPlot.loom"

### ISSUE THREAD

**Issue by zzgw** [satijalab/seurat#1204]
hello,
loom version is a very nice tool for me. I appreciate you guys excellent work on this.

I installed seurat loom version and run the mca tutorial just fine until the DimPlot step and FeaturePlot step.
Dimplot step complains that could not find function "DimPlot.loom".
FeaturePlot runs but only show X-axis and Y-axis.

my environment is R3.4.4 and rstudio server in an aws and I use chrome to connect to it.

I reinstalled using force=True but the problem persists.

Can you help me on this?

Many thanks.

best wishes,

**Comment by satijalab** [comment]
I'm closing this now just to help us manage issues on this repository, but would encourage you to post loom-related issues directly on the loomR repository at https://github.com/mojaveazure/loomR/issues
