### ISSUE TITLE
somthing wrong about merge two seurat object

### ISSUE THREAD

**Issue by soleilll** [satijalab/seurat#1205]
Hi,I want to merge two seurat objects,but something went wrong.

day2_4 <- merge(x = day2se, y = day4se,add.cell.ids=c("day2","day4"),merge.data=TRUE, project="10X_HSC")
Error in as.data.frame.default(x) :
  cannot coerce class ‘structure("seurat", package = "Seurat")’ to a data.frame

Then i thought maybe this merge function is base::merge,so i try Seurat::merge,but it still went wrong.
Error: 'merge' is not an exported object from 'namespace:Seurat'

Can you give me some advice?

Thank you !

**Comment by andrewwbutler** [comment]
Hi,

Please see #1175. Be sure your objects (`day2se` and `day4se`) have been updated to v3 Seurat objects. You can do this with the `UpdateSeuratObject` function.
