### ISSUE TITLE
Small bug in preprocessing.R for the loom branch

### ISSUE THREAD

**Issue by VincentGardeux** [satijalab/seurat#1208]
In the function NormalizeData.loom
I think the end of the script should not be
    dataset.use = "layers/norm_data"
but rather
 dataset.use = name

Because if one try to change the name arg of the function, it fails to run correctly.

**Comment by VincentGardeux** [comment]
Also, the same issue exists in ScaleData.loom
But this time
dataset.use = "layers/scale_data"
should be replaced by
dataset.use = paste('layers', name, sep = '/')

However, this still generates an HDF5 error message saying that some attributes cannot be written (but the layer is still correctly written)

**Comment by VincentGardeux** [comment]
As expected, the same remains for RunPCA, but actually a bit worse.
There are many occurrences where the dataset.use is hardcoded instead of using the args of the function.

Additionally, I would recommend adding an args for the cell_names location, for e.g.
cell.names = 'col_attrs/cell_names',

And subsequently replace in the function. Because the Loom format default path for cell names should be 'col_attrs/CellID'

For information, even after changing in the main RunPCA.loom function, it still tries to access the hardcoded path (probably in another function?)

Moreover, the irlba is not running with the following error:
Error in irlba(A = t(x = data), nv = pcs.compute, ...) : 
  starting vector near the null space

And following warnings:
```diff
- In addition: Warning messages:
- 1: batch.scan and batch.next have been deprecated; please use map/apply instead. For generating chunks, please use loom$chunk.points or loom$chunk.indices
```
If setting the parameter online.pca = F, it goes a bit farther, but still generates an error:

```diff
Computing eigen decomposition
- Error in eigen(covariance.mat) : infinite or missing values in 'x'
```

**Comment by chuiqin** [comment]
Hi,I have the same problem.
"Error in x$create_attr(which, robj = value) : HDF5-API Errors:
    error #000: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5A.c in H5Acreate2(): line 249: no write intent on file
        class: HDF5
        major: Invalid arguments to routine
        minor: Write failed"
Have you solved the problem yet?

**Comment by TiongSun** [comment]
Try removing some columns with special characters from the metadata using

SeuratObject@meta.data$column <- NULL

I removed 4 columns and the problem solved.
