### ISSUE TITLE
IntegrateData() Error in Embeddings

### ISSUE THREAD

**Issue by kravarik** [satijalab/seurat#1209]
Hello,

I am encountering an error that I cannot troubleshoot when attempting to integrate 34 datasets between 500-5000 cells per dataset. I successfully integrated a subset of the same datasets previously (with just 6 samples). Is this an known issue? Is there anything that can be done to address it?

Cheers,
Kellie 

`liver.integrated_all <- IntegrateData(anchorset = sample.anchors, dims = 1:30)`

Console output:
>...
> Integrating data
> Merging dataset 10 20 11 24 34 into 32 33 18 23 7 14 21 4 3 8 19 22
> Extracting anchors for merged samples
> Finding integration vectors
> You're computing too large a percentage of total singular values, use a standard svd instead.Finding integration vector weights
> Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds

Error Traceback:
> Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds
> 2. FindWeights(object = merged.obj, integration.name = integration.name, reduction = dr.weights, cpp = do.cpp, dims = dims, k = k.weight, sd.weight = sd.weight, eps = eps, verbose = verbose)
> 1.  IntegrateData(anchorset = sample.anchors, dims = 1:30)

**Comment by RobertKSuter** [comment]
Hi Kellie,

I'm also having this same issue when trying to integrate larger numbers of datasets with lower cell counts. Curious if you've had any luck getting past this?

Thanks,
Rob

**Comment by kravarik** [comment]
Hi Rob,

I have not many any progress on this error, and I am hoping the package authors have some suggestions. I have successfully integrated several different combinations of the same data, but only in groups up to 10. My code originally errored when combining 12 datasets with 4 more.

@mojaveazure @andrewwbutler Is there a known limit to the number of datasets that can be integrated with IntegrateData()?

Cheers,
Kellie

**Comment by timoast** [comment]
Hi, this is likely because you have fewer than 100 anchors in a dataset. There is no limit to the number of datasets that can be integrated, but there is a lower limit to the number of cells present in each datasets, since the integration works by leveraging information from neighboring cells. You might be able to work around this if you can merge or exclude your smaller datasets

**Comment by kravarik** [comment]
@timoast Thanks. To confirm, IntegrateData can take pre-integrated datasets?

**Comment by yasin-chop** [comment]
Hi. I face the same problem. One dataset has several thousand cells and the other is about 350 cells. When I try to run
imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, 
+                            weight.reduction = rna_object[["lsi"]])

I see the same error:
Finding integration vectors
Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds

Do you have any idea about the problem?
Thanks.
