### ISSUE TITLE
idents.use in FeatureHeatmap

### ISSUE THREAD

**Issue by rpeys** [satijalab/seurat#121]
Does the idents.use argument in FeatureHeatmap work? I don't see it get utilized in the code for the FeatureHeatmap function, and when I try to use it I get an error: 
![image](https://user-images.githubusercontent.com/19732554/28932588-0d6a73ac-7848-11e7-832c-74ec2b7a0cd1.png)

**Comment by leonfodoulian** [comment]
Close the parentheses after the list of gene names at ' "Cd163"), idents.use...'.

Best,
Leon

**Comment by AndyR2** [comment]
expecting this script: 
FeatureHeatmap(x, features.plot = c("Aqp4"), idents.use = c("1","12"), pt.size = .5)

to return a plot of Apq4 expression, showing only clusters 1 and 12.   However, all clusters shown in graph.  How is ident.use being used?  How do I define a specific set of clusters to be plotted?
