### ISSUE TITLE
Seurat3 and subsetting features with dashes (-) in the name

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#1212]
Hello,

I've found that I'm unable to use the subset() function to subset based on features that have dashes in their name.

`Aggreg.data <- Read10X(data.dir = "./filtered_feature_bc_matrix/")
test <-  CreateSeuratObject(counts = Aggreg.data, min.cells = 50, min.features = 0)

This works fine:
> summary(test@assays$RNA@data["CD8A",])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   0.000   0.000   3.556   3.000  94.000

> test2 <- subset(x = test, subset = CD8A > 0)  
> summary(test2@assays$RNA@data["CD8A",])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    3.00    6.00    9.81   14.00   94.00 `

However, this does not work:
> test3 <- subset(x = test, subset = MT-CO3 > 0)
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells) : 
  None of the requested variables were found: 
> test3 <- subset(x = test, subset = 'MT-CO3' > 0)
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells) : 
  None of the requested variables were found: 

What I find more troubling is that if a single requested variable is found, Seurat will not warn you that the "missing" variables were not used in the subset:
> test4 <- subset(x = test, subset = 'MT-CO3' > 0 & nFeature_RNA > 500)
> summary(test4@assays$RNA@data["MT-CO3",])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   28.00   50.00   81.78  102.00 1506.00 

This is kind of strange to me because Seurat will specifically convert underscores to dashes in feature names, so I assume this is not intended. Does anyone know if there is a workaround for this, or should I replace all underscores and dashes in the features tsv file before reading in the data?

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

To use `subset` or `WhichCells` on features that have dashes in their names you'll need to surround the feature in backticks. E.g:

```R
test3 <- subset(x = test, subset = `MT-CO3` > 0)
```

This is consistent with how base R subsets data.frames based on column names. 

As far as the missing variable problem, when you put the name in quotes, R will treat it as a string rather than a variable so it will evaluate the expression `'MT-CO3' > 0`, which evaluates to TRUE (you can verify this outside of subset by just entering that expression in the command line).

**Comment by jeremycfd** [comment]
Ah, thanks so much for the help!

**Comment by katie-connor** [comment]
Hi there, I am having this exact warning coming up when I am running my shiny app. 

The app works but I can't get rid of this warning message. If I change input$single_cell_gene to a "genename"  then there is no problem. I have tried changing as.character(input$single_cell_gene) 

`cell_type_violin <- reactive({
  p <- VlnPlot(object = data, features = input$single_cell_gene, pt.size = input$dot_size)
  p + theme(axis.text.x = element_text(size = rel(0.7))) + labs(x=NULL)
})`


This has been bugging me for ages - any help much approeciated!

**Comment by wgk51** [comment]
This fix, to have the gene name surrounded by backticks, no longer works in Seurat 4.0. Any ideas for how to get around this? Trying to subset genes with "-" in the name and getting the below error. I get the same error if I put any other gene name in ticks, even those that subset just fine without them. 

Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found:

**Comment by andrewwbutler** [comment]
Hi @wgk51,  can you provide an example?

**Comment by swaggggyzhao** [comment]
I got the same problem with @wgk51.
Example:
      I did:   WhichCells(PC, expression='Ighv7-1'>0 )
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found:

**Comment by cwseidel** [comment]
Putting a gene name in back ticks works fine for me. But how does one put a gene name into a variable?
subset(obj, subset = `Nkx1-2` > 0)  # success!
mygene <- "Sox10"
subset(obj, subset = mygene > 0)  # doesn't work! :(

**Comment by paulitikka** [comment]
I have the same problem:

# So this works:
length(WhichCells(data, slot = 'data', expression = Pitx2 > 0))
#[1] 379

# But this does not work:
a=c('Pitx2')
length(WhichCells(data, slot = 'data', expression = a[1] > 0))  
#  Error in FetchData.Seurat(object = object, vars = unique(x = expr.char[vars.use]),  :  
# None of the requested variables were found: 

This would be needed to loop many gene names at one go. E.g. via:

vars=c('Pitx2','Sox2','Shh')
 for(i in 1:length(vars)) {
length(WhichCells(data, slot = 'data', expression =vars[i]> 0))}
