### ISSUE TITLE
Seurat v3: Reanalyze after subsetting clusters

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#1214]
Hi, 
In Seurat v3, how can I reanalyze a subsetted cluster?
I am analyzing PBMCs from 9 samples. After integrating the samples followed by initial clustering, I subset the CD4 population and am going to re-analyze this population. 
However, when I tried to find variable features, my list came up with 0.
When I perform the subsetting, I also included `do.clean = TRUE` as in Seurat v2.
I was able to re-analyze previously in Seurat v2 but not in v3. 
Please advice. Thank you.

**Comment by nicodemus88** [comment]
I apologize! Issue closed as it was a mistake on my part.

**Comment by mojaveazure** [comment]
How exactly are you subsetting the dataset in v3? We don't have a `do.clean` argument in v3 anymore.
