### ISSUE TITLE
How to correctly do multiCCA with 3 datasets?!

### ISSUE THREAD

**Issue by MichaelStreuber** [satijalab/seurat#1216]
Hi all,

I want to do a multi-analysis with 3 different datasets. My question might be very general.
From this forum and the great paper of Butler et al. 2018 I saw that with more than 2 datasets one is doing multiCCA and using all datasets together.
I heard from a colleague who attended a Single Cell Analysis Conference last November that some groups are doing in such a case (more than 2 datasets) first a comparative analysis e.g. between dataset 1 vs. dataset 2 and took these aligned dataset to compare it with a dataset 3.
In Butler et al., the 4 pancreatic datasets were used/analyzed all together and not comparative first between 2 datasets and then the next one for example.

I just would like to know what is correct?!?!

Many thanks and best wishes,
Michael

**Comment by andrewwbutler** [comment]
Hi,

I would say that it depends on the types of comparative analyses you want to do. The alignment strategy in Seurat v2 is useful for identifying common cell types across datasets but doesn't return adjusted or "corrected" gene expression measurements (if this is something you want, please see Seurat v3).  Therefore, if you have three datasets and you want to perform a joint clustering of all three, you need to run the alignment strategy on all three.

**Comment by satijalab** [comment]
We strongly recommend using the Seurat v3 alignment procedure for multi-dataset integration. You can see a vignette here
https://satijalab.org/seurat/pancreas_integration_label_transfer.html
