### ISSUE TITLE
uploading new data

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#1217]
Hi, 
I am new to Seurat. I have no problem whatsoever with with the pbmc tutorials. All works fine. 
I have some data already compiled which I would like to re-analyze. 
When I upload my own data thats in a matrix with single cells as columns and genes in rows. The header indicates the cell in each column and its something like stemcell_1, stemcell_2, stemcell_3, progenitor_1, progenitor_2, progenitor_3, progenitor_4  ..... etc. 
How can we tell it that i already have clusters identified? I most need it to try to dig out some predefined clusters and their specific genes. 
Many thanks for the suggestions!!

**Comment by andrewwbutler** [comment]
Hi,

Please see the `names.field` and `names.delim` parameters to `CreateSeuratObject` if your clusters are encoded in the names of the cells. In your case, the default parameters of `1` and `_` should set the cell identities to "stemcell" and "progenitor".

**Comment by kasumaz** [comment]
Hi, 
Thanks so much for that. This step works.
when I do the levels(filename@ident)...the right clusters show up finally. 
However, when I try to do some tests...
for example: 

> # Find differentially expressed genes between stemcells and progenitors 
stemcells <- FindMarkers(filename, ident.1 = "stemcells", ident.2 = "progenitors ")

I have this error:
   |                                                  | 0 % ~calculating  Error in model.frame.default(formula = countdata.test[x, ] ~ coldata[,  : 
  invalid type (list) for variable 'countdata.test[x, ]'

I assumed that the data needs to be normalised...
so at the start I did this: 
filename=log(filename+1) 

Is there a function that I could be missing before I try to run differential analysis? 
Many thanks pal.  I am almost there with what I need seurat for...for the being.

**Comment by andrewwbutler** [comment]
If you want to follow a "standard analysis", you can work through the [3K pbmc tutorial](https://satijalab.org/seurat/pbmc3k_tutorial.html), which covers normalization and DE. In your case, you may need to run `NormalizeData`.

**Comment by kasumaz** [comment]
Hi, 
Thanks for your reply. 
It did work as you suggested. I can do differential analysis for my own datasets. I am just going through other functions now for seurat. 

For sure I will come across other issues and will check these pages incase someone else has corrected it.
Much appreciated. 
Cheers, Kaz
