### ISSUE TITLE
The meaning of power and myAUC in the results of FindAllMarkers

### ISSUE THREAD

**Issue by leafyes** [satijalab/seurat#1219]
Hi,
I have some questions in using FindAllMarkes function. (1), What the meaning of "myAUC"? Does it represent for AUC ( Area under the curve) of the ROC? or ROC score? and what the biological significance of "myAUC"?  (2), What the meaning of "power"? Is it the same as the "statistical power" that deals with Type II errors? And what the biological significance of "power"? How to calculate it ? 

gene | myAUC | avg_diff | power | avg_logFC | pct.1 | pct.2 | cluster
-- | -- | -- | -- | -- | -- | -- | --
S100A9 | 0.991 | 3.785147875 | 0.982 | 3.785147875 | 0.996 | 0.227 | 1
S100A8 | 0.982 | 3.739865731 | 0.964 | 3.739865731 | 0.978 | 0.133 | 1
GZMB | 0.992 | 3.262048173 | 0.984 | 3.262048173 | 1 | 0.078 | 5
GNLY | 0.968 | 3.124682994 | 0.936 | 3.124682994 | 0.967 | 0.142 | 5

Please forgive my ignorance，could help me ? Thank you very much!
Best,
Jialin Zheng

**Comment by andrewwbutler** [comment]
Hi,

1. "myAUC" represents the area under the ROC curve. 
2. "power" is defined as the predictive power and is calculated as `abs(AUC-0.5)`.

From the `FindMarkers` documentation:
"For each gene, evaluates (using AUC) a classifier built on that gene alone, to classify between two groups of cells. An AUC value of 1 means that expression values for this gene alone can perfectly classify the two groupings (i.e. Each of the cells in cells.1 exhibit a higher level than each of the cells in cells.2). An AUC value of 0 also means there is perfect classification, but in the other direction. A value of 0.5 implies that the gene has no predictive power to classify the two groups. Returns a 'predictive power' (abs(AUC-0.5)) ranked matrix of putative differentially expressed genes."

**Comment by lixin4306ren** [comment]
how can the power value as large as 0.982 based on its definition abs(AUC-0.5)? Does it mean the AUC is negative 0.482? I'm confused.

**Comment by andrewwbutler** [comment]
This was a typo in the docs. It should read `abs(AUC-0.5)) * 2`. This was recently corrected (#1586).

**Comment by timj6599** [comment]
Sorry, I know this is an old thread but the difference between AUC and power still have me a bit confused. While doing a bit of research, different stats forums say: "If we must label certain scores as good or bad, we can reference the following rule of thumb from Hosmer and Lemeshow in [Applied Logistic Regression](https://onlinelibrary.wiley.com/doi/book/10.1002/9781118548387) (p. 177):

0.5 = No discrimination
0.5-0.7 = Poor discrimination
0.7-0.8 = Acceptable discrimination
0.8-0.9= Excellent discrimination
>0.9 = Outstanding discrimination " https://www.statology.org/what-is-a-good-auc-score/#:~:text=0.5%2D0.7%20%3D%20Poor%20discrimination,%3E0.9%20%3D%20Outstanding%20discrimination
With this being said, I would assume a myAUC score of 0.7 or above would imply the marker is effective. However given the formula used to calculate power, a myAUC score of 0.7 would correlate to a power of 0.4. So with this being said, would it be fair to assume that myAUC should be ignored for the purposes of validating markers? Or should both values be taken into account somehow?
