### ISSUE TITLE
DBClustDimension in v3.0

### ISSUE THREAD

**Issue by shokohirosue** [satijalab/seurat#1220]
Does DBClustDimension not work in v3.0 Seurat, and if so, is there an alternative?

I am aware of this helpful list of commands comparing v2 and v3,(https://satijalab.org/seurat/essential_commands.html) however, I could not find the information here.
Where is the best place to find the most updated version of Seurat v3 function/argument information?

Thank you for your help!

**Comment by andrewwbutler** [comment]
Hi,

We recommend graph based methods for clustering and provide several options for that via the `FindNeighbors` and `FindClusters` functions. For function/argument information, please see the documentation for the function of interest (e.g. `?FindClusters`). We are in the process of updating the website documentation and vignettes for the official v3 release but provide several resources already including the essential commands list you mentioned, an updated [pbmc3k tutorial](https://satijalab.org/seurat/pbmc3k_tutorial_v3.html), and a [demonstration](https://satijalab.org/seurat/pancreas_integration_label_transfer.html) of the new integration method.

**Comment by shokohirosue** [comment]
Thank you very much!
