### ISSUE TITLE
Missing method Read10x_hd in loom branch

### ISSUE THREAD

**Issue by sickman2000** [satijalab/seurat#1221]
I try to load 10x data from h5 files to merge it and store it as loom file, after installing the loom branch of seurat the method Read10x_h5 is missing ... can anybody help me ?

**Comment by mojaveazure** [comment]
The loom branch was created before `Read10X_h5` was written, so it never had it. I would recommend reading in your data using the CRAN version of Seurat (`install.packages('Seurat')`, [save the object as an RDS file](https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/readRDS), unload Seurat and install the loom branch using devtools, then reload Seurat and your object from the RDS file to save it as a loom file.

**Comment by sickman2000** [comment]
Ah yes I see, thank you for the tip. Unfortunately HDF5-API raises an error when I try to generate the loom file. 

Error in dataset_create_pl$set_chunk(chunk_dims) : HDF5-API Errors:
    error #000: ../../../src/H5Pdcpl.c in H5Pset_chunk(): line 2030: all chunk dimensions must be positive
        class: HDF5
        major: Invalid arguments to routine
        minor: Out of range

I tried it first with my dataset and after the error with the pbmc_small set following the instructions from the seurat site with the same result ?  I use Debian9 and installed the libhdf5-dev package 1.10.0, is there a kown problem with this version ?

**Comment by mojaveazure** [comment]
Sorry for the delay. There have been known issues with HDF5 1.10.X and our HDF5 interface, hdf5r. I suggest upgrading your Seurat and hdf5r packages to the latest available on CRAN, updating your Seurat object to a v3 object, then writing out as a loom file.

**Comment by sickman2000** [comment]
Thank you for your help ...

Am 10.05.2019 um 17:59 schrieb Paul Hoffman:
