### ISSUE TITLE
The following X features requested have not been scaled (running reduction without them)

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#1222]
Hello,

In using Seurat3, I keep running into this issue when attempting to RunPCA on my filtered Seurat object using the cell cycle features. This warning occurs regardless of whether or not I specifically ScaleData using the cell cycle features or whether I FindVariableFeatures first, although the number of features labeled as not scaled does change.

Aggreg_filt <- NormalizeData(object = Aggreg_filt, normalization.method = "LogNormalize", scale.factor = 1e4)
Aggreg_filt <- FindVariableFeatures(object = Aggreg_filt, selection.method = 'vst')
Aggreg_filt <- CellCycleScoring(object = Aggreg_filt, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
Aggreg_filt <- RunPCA(object = Aggreg_filt, features = c(s.genes, g2m.genes), do.print = FALSE)
>.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
PC_ 1 
Positive:  MKI67, UBE2C, TPX2, AURKB, TYMS, BIRC5, CDCA8, TOP2A, CDK1, CENPF 
	   NUSAP1, CDC20, CENPU, ANLN, CKAP2L, CKS1B, HMMR, RAD51AP1, KIF11, HMGB2 
	   SMC4, PSRC1, CDCA2, CENPE, TACC3, NDC80, CLSPN, TMPO, JPT1, CKS2 
Negative:  UNG, MSH2, POLD3, TIPIN, SLBP, CCNE2, PRIM1, CASP8AP2, G2E3, NASP 
	   UBR7, RANGAP1, MCM6, POLA1, RPA2, GAS2L3, LBR, BLM, CTCF, MCM4 
	   WDR76, FEN1, USP1, TUBB4B, RFC2, CBX5, CDCA7, MCM5, MCM2, RRM1 
PC_ 2 
Positive:  NASP, CBX5, TUBB4B, UBR7, RPA2, POLD3, CKAP5, CKS1B, USP1, MSH2 
	   RRM1, HELLS, UNG, MCM5, CTCF, ANP32E, TYMS, SLBP, MCM6, MCM2 
	   RFC2, PCNA, POLA1, CASP8AP2, MCM4, G2E3, RANGAP1, FEN1, PRIM1, ECT2 
Negative:  HMGB2, CKS2, GAS2L3, JPT1, BLM, TACC3, UBE2C, MKI67, CDC20, NUSAP1 
	   PSRC1, ANLN, AURKA, TPX2, CENPE, CDCA8, BIRC5, CDK1, AURKB, TOP2A 
	   HMMR, KIF11, CKAP2L, CDCA2, CKAP2, NDC80, KIF20B, CLSPN, TIPIN, SMC4 
PC_ 3 
Positive:  CBX5, POLD3, CKAP5, ECT2, GAS2L3, CKS1B, CENPF, UBE2C, CDCA8, MKI67 
	   BIRC5, CDC20, CTCF, TPX2, TUBB4B, PSRC1, AURKB, CDK1, MSH2, BLM 
	   CENPE, NCAPD2, RAD51AP1, RPA2, HMMR, POLA1, ANLN, TYMS, TOP2A, G2E3 
Negative:  SLBP, CKS2, RANGAP1, JPT1, MCM6, PCNA, CKAP2, CDCA7, UNG, WDR76 
	   ATAD2, NDC80, CCNE2, TACC3, GMNN, HELLS, HMGB2, NUSAP1, KIF20B, ANP32E 
	   CLSPN, MCM4, NASP, DTL, TIPIN, LBR, PRIM1, FEN1, TMPO, UBR7 
PC_ 4 
Positive:  HELLS, MCM5, TYMS, BLM, CDCA7, RFC2, MCM2, MCM4, CENPU, CLSPN 
	   ATAD2, GAS2L3, RAD51AP1, TIPIN, DTL, PCNA, UBR7, HMGB2, MKI67, FEN1 
	   CBX5, WDR76, POLA1, RPA2, AURKB, GMNN, POLD3, TPX2, TOP2A, CCNE2 
Negative:  TUBB4B, ANP32E, SLBP, CDC20, NASP, CKAP5, KIF20B, G2E3, LBR, CENPF 
	   RANGAP1, JPT1, SMC4, UNG, CTCF, MSH2, AURKA, HMMR, CENPE, RRM1 
	   TMPO, CDK1, PSRC1, NDC80, UBE2C, CKAP2, TACC3, ECT2, MCM6, CKAP2L 
PC_ 5 
Positive:  TUBB4B, CKS2, GMNN, JPT1, HMGB2, GAS2L3, PCNA, POLD3, BLM, MCM4 
	   TIPIN, USP1, ECT2, CBX5, ANP32E, MSH2, RPA2, RFC2, NASP, NUSAP1 
	   MCM5, SMC4, AURKA, CKAP5, CTCF, SLBP, PSRC1, DTL, MCM2, RAD51AP1 
Negative:  MCM6, NDC80, TACC3, RANGAP1, ATAD2, CKAP2, NCAPD2, LBR, CDCA7, TYMS 
	   TOP2A, CLSPN, PRIM1, KIF20B, CASP8AP2, HELLS, RRM1, CDCA2, MKI67, UBE2C 
	   AURKB, UNG, CDC20, TPX2, BIRC5, CKAP2L, CDCA8, CENPE, TMPO, WDR76 
Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 25 features requested have not been scaled (running reduction without them): GINS2, UHRF1, RAD51, RRM2, CDC45, CDC6, EXO1, DSCC1, CHAF1B, BRIP1, E2F8, NUF2, PIMREG, CCNB2, BUB1, GTSE1, HJURP, CDCA3, TTK, CDC25C, KIF2C, DLGAP5, KIF23, NEK2, CENPA`

Does anyone have any ideas about what's going on here and how this might impact cell cycle scoring?

Thanks!

**Comment by andrewwbutler** [comment]
Do you have those features in your dataset? Here's one way to check:

```R
cc.genes <- c(s.genes, g2m.genes)
cc.genes[!cc.genes %in% rownames(Aggreg_filt)]
```

This should return any features from the cell cycle list that are not present in your dataset.

**Comment by jeremycfd** [comment]
I'm suddenly unable to replicate this issue, so I suspect you are correct that there were some problems with which features were actually included in the object. Thanks!

**Comment by dagarfield** [comment]
I was hoping I could follow up with this. I'm getting a very similar error/warning:

Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 56 features requested have not been scaled (running reduction without them): MCM5, FEN1, MCM2, MCM4, RRM1, UNG, MCM6, CDCA7, DTL, PRIM1, MLF1IP, HELLS, RFC2, RPA2, NASP, WDR76, SLBP, CCNE2, UBR7, POLD3, MSH2, ATAD2, RAD51, CDC45, CDC6, EXO1, TIPIN, DSCC1, BLM, CASP8AP2, USP1, CLSPN, POLA1, CHAF1B, BRIP1, E2F8, NDC80, TMPO, CKAP2L, ANP32E, TUBB4B, KIF20B, HJURP, CDC25C, KIF2C, NCAPD2, CDCA2, CDCA8, ECT2, PSRC1, LBR, CKAP5, CTCF, G2E3, GAS2L3, CBX5

In this case, I can confirm that only MLF1IP is missing from the cc.genes. 
> cc.genes <- c(s.genes, g2m.genes)
> cc.genes[!cc.genes %in% rownames(myData)]
[1] "MLF1IP"

Is there anything else you can suggest checking?
I should note that the separation by cell cycle is not strong on the PCA (PCAPlot) that comes after the "CellCycleScoring" step, so perhaps the warning indicates something about the cell cycle genes being low expressed or not highly informative?
