### ISSUE TITLE
Seurat 3.0 SCE

### ISSUE THREAD

**Issue by L30P30** [satijalab/seurat#1225]
I have a large Seurat object (made with v3) and I'd like to convert it to SCE format for use with SCMAP. 

I used Seurat 3.0 because the count matrix was generated with CellRanger 3.0.

I see that the convert function isn't available yet for v3. Is it possible to convert this object in v2 or do I need to start from scratch?

Thanks a lot

**Comment by andrewwbutler** [comment]
Hi,

You can use `as.SingleCellExperiment` to convert to SCE in Seurat v3.

**Comment by L30P30** [comment]
Worked like a charm, thank you Andrew!
