### ISSUE TITLE
visualizing dispersion plot in v3

### ISSUE THREAD

**Issue by rekham1077** [satijalab/seurat#1228]
Hi, how do you visualize the dispersion plot in seurat v3? I have tried do.plot = TRUE but that does not make the plot appear. I can't find it in any of the help documentation either.

**Comment by andrewwbutler** [comment]
Hi,

You can use the `VariableFeaturePlot`  function for this.

**Comment by rekham1077** [comment]
thanks!

**Comment by thetapper** [comment]
Hi,
I was wondering if this also works with using `SCTransform()` for finding variable genes?
Because I get an error message running `VariableFeaturePlot()`:

````
> VariableFeaturePlot(data, assay="SCT")
Error in `[.data.frame`(slot(object = x, name = "meta.features"), , i,  : 
  undefined columns selected
> VariableFeaturePlot(data)
Error in `[.data.frame`(slot(object = x, name = "meta.features"), , i,  : 
  undefined columns selected

> object[["RNA"]][[]]
Error: object 'object' not found
> object[["SCT"]][[]]
Error: object 'object' not found
````

Thanks!

**Comment by ChristophH** [comment]
This functionality was just added now. VariableFeaturePlot now also
works for assays created with the SCTransform function. To see what
values are being plotted, you can pull out the relevant feature meta
data with HVFInfo(object, assay), where object is a Seurat object and
assay the assay name (e.g. 'SCT')
