### ISSUE TITLE
how to print genes in  $cca.aligned

### ISSUE THREAD

**Issue by guoyanzhao** [satijalab/seurat#1229]
Hi Seurat team,

Thank you for developing this great tool!

I did RunMultiCCA on a set of 4 samples each with 2 biological replicates and performed AlignSubspace() using first 5 dimentions. After RunTSNE() and FindClusters() I got 10 cell clusters. I am trying to find out what are the genes that separates those clusters.

I can use VlnPlot to see which ACC contributes to each cluster.
VlnPlot(object = data_integrated, features.plot = "ACC1", x.lab.rot = TRUE)

I can get the genes in each CCA by using the following code.
PrintDim(data_integrated, reduction.type = 'cca', dims.print = 1:5, genes.print = 10)

However the code trying to print genes in aligned CCA did not output anything:
PrintDim(data_integrated, reduction.type = 'cca.aligned', dims.print = 1:2, genes.print = 10) # did not work

My question is:

How can I get the genes in each "aligned CCA"? Or are they the same genes as in $cca? For example if I used 5 dimensions to AlignSubspace() the ACC1 will be the same as CC1?

The default number of genes to print is 30 (genes.print = 30). The actually genes in each dimension are hundreds. Are the genes ordered by their importance in dimension reduction? If not where is that information stored and how can I access it?

I remember seeing somewhere a plot showing which principle component explains the most variance of each cluster. Can similar plot be made with ACC?

Thank you very much for your help!

**Comment by timoast** [comment]
Hi, `AlignSubspace` will just change the cell embeddings, so the top genes will be the same as in the original CCA. You might also want to look at some of the newer integration methods we have developed in Seurat v3: https://satijalab.org/seurat/pancreas_integration_label_transfer.html

**Comment by guoyanzhao** [comment]
Hi Tim,
Thank you very much for your explanation. Yes, I am experimenting with the new version of Seurat and will compare the results with the current version. It's a great software. Thank you!Guoyan


    On Friday, March 15, 2019, 2:29:39 PM CDT, Tim Stuart <notifications@github.com> wrote:  
 
 
Hi, AlignSubspace will just change the cell embeddings, so the top genes will be the same as in the original CCA. You might also want to look at some of the newer integration methods we have developed in Seurat v3: https://satijalab.org/seurat/pancreas_integration_label_transfer.html
