### ISSUE TITLE
FilterCells function gene upper limits

### ISSUE THREAD

**Issue by s18692001** [satijalab/seurat#123]
Hi there,

I'm curious what the purpose to set the high.thresholds of the unique gene counts over 2500 in the PBMC tutorial?
Here is the codes:
```
pbmc <- FilterCells(object = pbmc, subset.names = c("nGene", "percent.mito"), 
                    low.thresholds = c(200, -Inf), high.thresholds = c(2500, 0.05))
```

**Comment by leonfodoulian** [comment]
Higher number of detected genes compared to the average is [most probably] indicative of doublets. Provided that a minority of the cells in the 2700 PBMC dataset had gene counts over 2000, it is reasonable (and even suggested) to remove them from any downstream analysis as this may affect the results. There is no absolute threshold of gene counts for filtering cells. It all depends on the tools you're using (as the rate of gene detection varies between methods), [the sequencing depth,] and on the cell types (e.g. with my experience, neurons tend to have higher number of detected genes compared other neighbouring cell types). 

Best,
Leon

**Comment by s18692001** [comment]
Thanks for the reply.
What do you mean doublelet of gene and  what is the potential reason to
have doublelet? Thanks!
2017/8/6 上午12:56於 "satijalab" <notifications@github.com>寫道：

**Comment by leonfodoulian** [comment]
"Doublets" refers to having 2 or more cells that were captured at once. Hence, you see them as being one cell, but in reality, the resulting cDNA that has been sequenced comes from multiple cells. This, depending again on the methods you're using, increases the number of detected genes. 

Best,
Leon
