### ISSUE TITLE
Colour tSNE according to the information in metadata

### ISSUE THREAD

**Issue by shokohirosue** [satijalab/seurat#1230]
Would it be possible to color tSNE plot with percent.mito in metadata? (eg. 0%(blue)---100%(green) gradient)?
If so, what is the best way to do so?

It seems FeaturePlot plots continuous data but takes gene names as feature, and DimPlot takes metadata as group but is suitable for discrete data.

Thank you very much!

**Comment by andrewwbutler** [comment]
Hi,

You can use `FeaturePlot` for continuous data stored in metadata. E.g.

```R
FeaturePlot(object = object, features = "percent.mito")
```

**Comment by shokohirosue** [comment]
Dear Andrew,

Thank you so much. This is what I was looking for! 

What is the best way to find what the argument can take? For now, I have been relying on the tutorial (eg. https://satijalab.org/seurat/pbmc3k_tutorial_v3.html), so I only knew it could take row names in quotes. 
R documentation for FeaturePlot's says "features - Vector of features to plot" - Does "feature" mean metadata columns and rownames of the matrix? Is it better to look at the source code for the function if I really want to know what all the available options are?

Thank you very much for your help.

Best regards,
Shoko

**Comment by andrewwbutler** [comment]
Hi,

`FeaturePlot` can plot any "feature" or row from the `data` slot of an `Assay` (e.g. gene expression). Additionally, it supports plotting any column from the `meta.data` slot and any of the cell embedding values from a `DimReduc` (e.g. PC embedding "scores").  Generally, the R documentation is the place to look for details on the argument with examples given in the different vignettes. I agree though that here the docs here weren't very specific. I've updated the `features` parameter description as of 57bf859.
