### ISSUE TITLE
FeaturePlot v3.0 scale when using argument split.by

### ISSUE THREAD

**Issue by asigore** [satijalab/seurat#1231]
Dear Seurat team, 

I have a couple of questions regarding the FeaturePlot function in Seurat v3.0: 

1) When using the "split.by" argument, is the feature plotted at the same scale in the split
tsne/UMAPs, or is it plotted at a different scale for the group of cells of each split category?
 
2) Also, is there a way to display the scalebar at the side of each plot when using "split.by"? I see that "no.legend" is no longer an optional argument. 

Thanks in advance for your help, 

Ana

**Comment by satijalab** [comment]
The features are plotted on the same scale using default parameters. However you can set the max/min to quantiles (for example 'q90'), to place the features on relative scales - which we do routinely for the same reasons driving your question.

2. Unfortunately we do not support adding an additional side bar at the moment
