### ISSUE TITLE
Unable to run JackStraw on more than 50 dims

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#1232]
I was wondering if anyone else has had this issue. No matter how many PCs I generate via RunPCA, I cant seem to run JackStraw with dims set >50.

This for example works fine:
`  TestObj <- RunPCA(object = TestObj,   features = VariableFeatures(object = TestObj), verbose = FALSE, npcs = 80)`
  `TestObj <- JackStraw(object = TestObj, num.replicate = 100, dims = 50)`

However, setting dims > 50 results in an error:
`TestObj <- JackStraw(object = TestObj, num.replicate = 100, dims = 51)`
`Error in Loadings(temp.object)[rand.genes, r1.use:r2.use] :   subscript out of bounds`

I've verified that the PCs do exist in the object.
Thanks!

**Comment by andrewwbutler** [comment]
Thanks for reporting! This bug was because of the use of an old parameter name in one of the internal functions. Should be fixed as of 3cf1cf2.

**Comment by iddryg** [comment]
I am getting a similar error... I tried dims = 60 in the initial call but this warning and error came up. 

Warning in JackStraw(dataset, num.replicate = 100, dims = 50) :
  Number of dimensions specified is greater than those available. Setting dims to 30 and continuing
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=10s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Error in pAll[, dims, drop = FALSE] : subscript out of bounds
