### ISSUE TITLE
Why Seurat give different FindAllMarkers sorting result when I give different  top_n value?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1233]
It is very weird. When I give different value to the command  top_n, it will give me distint result.For example, I foucs on the Crabp1 gene, it is first-ranked among cluster 1 gene list in the top 50 excel, but it is not among the list in the top 20. Why seurat give distint ordering result? It seems that seurat  throw away some genes of the top 50, because I find its p_val_adj sorting result didn't start from 0 in the top 20 list.
The heatmap result vary with the change of top_n value,if I do DoHeatmap with features=top5$gene,or top20$gene,I could't find the Crabp1 gene.
**How can I keep the top 5 gene in the top50 list same with any other list? Or how can I make the Crabp1 gene keep 1st in the top5 result or any other list?** 
Can you help me?Thank you very much!

**Comment by timoast** [comment]
Here you're selection the 50 or 20 genes with the highest adjusted p-value, not lowest. To select the lowest adjusted p-values, use a negative value for `n` (see the documentation for `top_n` for more information)

**Comment by hfberg** [comment]
Hi, I just read this post and I had no idea that this was the case. I've played around with different settings now and i realize that I get the clearest heatmap using the highest adj p-value. How come? This means I've used DE genes with 0 in p-value. Does that mean that my heatmap is unstrustable?
