### ISSUE TITLE
percent.mito is not a percentage

### ISSUE THREAD

**Issue by scottgigante** [satijalab/seurat#1235]
From what I gather, the value returned by `'percent.mito'` is not actually a percentage. In the [tutorial](https://satijalab.org/seurat/pbmc3k_tutorial.html), you filter cells which have less than 0.05 "percent" mitochondrial expression - I think you actually mean 5% which implies that the percentage ranges from 0 to 1. This is confusing and misleading.

**Comment by mschilli87** [comment]
@scottgigante: What would be your preferred solution?

- [ ] Rename `percent.mito` to `fraction.mito` and keep the current behaviour.
- [ ] Adjust the code to divide by 100 to make the range from 0 to 100.

**Comment by scottgigante** [comment]
I think the 'fraction.mito' solution is desirable as simply "fixing" percent.mito would silently break a lot of code, where at least with fraction.mito people will continue to get the behaviour they expect.

**Comment by mschilli87** [comment]
@scottgigante:
> [...] simply "fixing" percent.mito would silently break a lot of code, where at least with fraction.mito people will continue to get the behaviour they expect.

Except for breaking scripts that explicitely pass `percent.mito=0.1`. :wink:

**Comment by scottgigante** [comment]
Valid point - maybe a warning should be raised whenever `percent.mito` is used regardless of its value, just in case someone really wanted to filter anything with more than 0.1% mitochondrial RNA :)

**Comment by mschilli87** [comment]
@scottgigante:
> Maybe a more user friendly thing to do would be to catch percent.mito and tell the user about the new API.

I thought about this too but I think the major version bump from 2.x to 3.0 is a good opportunity to change the API without further comlicating the code.

If anyone disagrees, feel free to modify/ignore my PR. :slightly_smiling_face:

**Comment by andrewwbutler** [comment]
I agree that changing the variable name to `fraction.mito` in the vignette is probably the best bet here. However, this isn’t really a Seurat level API change as that’s just a variable name we define (albeit imprecisely) in a vignette. Users should still be able to create `percent.mito` and store that in metadata if they want so I don’t think a warning is necessary here. We’ll make sure this is updated for all v3 versions of the vignettes.

**Comment by eisascience** [comment]
p.mito can be used as it could mean proportion mito and percent mito. but recall percent is always *100 otherwise it's a proportion.

**Comment by satijalab** [comment]
Fixed in Seurat v3
