### ISSUE TITLE
Synthesizing Gene Expression and Antibody Capture data in Seurat3

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#1237]
Hello,

In working with 10x CellRanger3 outputs in Seurat3, Read10X returns a list of assays when your 10x data includes Feature Barcodes, e.g. "Gene Expression" and "Antibody Capture". When creating the Seurat object, you must select which list to use. Currently I'm creating two Seurat objects, one for gene expression and the other for antibody capture, and then converting the Antibody Capture counts into a data frame and adding it to the Gene Expression object as metadata. I was just wondering if there is an alternative, perhaps more efficient or more appropriate way to go about this. In some cases the antibody capture data are just for hashing, so I don't really feel compelled to do any scaling, etc. However, in other cases the antibody capture data are being used to quantify cell surface marker expression; for those data, do you think that the standard Seurat workflow (normalization, scaling, etc) are appropriate? My naive guess would be no, since I would expect the distributions of single-cell surface marker data to look very different from single-cell gene expression data, but I'm wondering if you have thoughts on this.

Thanks for your time, and keep up the great work on Seurat!

**Comment by andrewwbutler** [comment]
Hi,

Part of the motivation behind the redesign for Seurat v3 was to handle multiple assays in a more seamless manner. For this we, now have individual `Assay`s which can be stored within a single `Seurat` object. In your scenario, I would first create the Seurat object using the RNA data and then create a new `Assay` to add into the Seurat object that contains the antibody capture counts. The workflow would look something like:

```R
object <- CreateSeuratObject(counts = rna.counts)
# standard analysis pipeline for RNA - NormalizeData, FindVariableFeatures, ScaleData, etc...
object[["ADT"]] <- CreateAssayObject(counts = adt.counts)
# downstream functions will have an assay parameter to specify 
# which data to run any particular function on. By default functions will
# operate on DefaultAssay(object). 
object <- NormalizeData(object = object, assay = "ADT", normalization.method = "CLR")
```

Also, please see the [multimodal vignette](https://satijalab.org/seurat/multimodal_vignette.html) for recommendations on ADT data. This vignette is currently written using Seurat v2 but is being updated along with all the other vignettes for the official v3 release.
