### ISSUE TITLE
duplicated rownames in object@data causing error in FindVariableGenes

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#1238]
Hi, 

When I try to FindVariableGenes in my sample from cellranger3.0, I get this error:

>WT.seurat = FindVariableGenes(object = WT.seurat, do.plot = FALSE)
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘Aldoa’, ‘Gm16701’, ‘Gm2464’, ‘Gm35558’, ‘Nudt8’, ‘Pcdha11’, ‘Pick1’ 

This seems to be caused by duplicated row (gene) names in the seurat object
> any(duplicated(rownames(WT.seurat@data)))
[1] TRUE
> table(duplicated(rownames(WT.seurat@data)))
FALSE  TRUE 
19132     7

In the original matrix import, I used this to make the row names:
> rownames(WT.mat) = WT.feature.names$V2
#where V1 is the gene ENSG number and V2 is the gene name
#this is using the list provided by the cellranger 3.0 output

Do you have any ideas to fix this?

Any help is appreciated!

Thanks

**Comment by lennycheung** [comment]
I figured out the reason for this error but now I get an error somewhere else, in calculating CellCycleScoring.  

It seems this has been caused by me using the gene symbols as row names instead of ENSG# when loading in the matrix
rownames(WT.mat) = WT.feature.names$V1

However, now when I try to do CellCycleScoring I get this error:

> WT.seurat = CellCycleScoring(object = WT.seurat, s.genes = s.genes, g2m.genes = g2m.genes, set.ident = F)
Error in AddModuleScore(object = object, genes.list = genes.list, enrich.name = enrich.name,  : 
  The following gene lists do not have enough genes present in the object: S.Score exiting...The following gene lists do not have enough genes present in the object: G2M.Score exiting...
In addition: Warning messages:
1: In AddModuleScore(object = object, genes.list = genes.list, enrich.name = enrich.name,  :
  Could not find enough genes in the object from the following gene lists: S.Score Attempting to match case...Could not find enough genes in the object from the following gene lists: G2M.Score Attempting to match case...
2: In grep(pattern = paste0("^", s, "$"), x = match, ignore.case = TRUE,  :
  argument 'pattern' has length > 1 and only the first element will be used
3: In grep(pattern = paste0("^", s, "$"), x = match, ignore.case = TRUE,  :
  argument 'pattern' has length > 1 and only the first element will be used

I think this is now because the cc.genes are gene symbols but my genes in my seurat object are ENSG#.

Is there something else I can do or should I simply convert the 97 genes to ENSG#s?

Thanks

**Comment by timoast** [comment]
Hi, you need to make sure the matrix rownames are unique before creating the Seurat object. You can do this with the `make.unique` function, or as of commit 8ae96eb3b130bc82bb51ba2daba305602987c23d `Read10X_h5` and `Read10X` will do this for you by default.

**Comment by lennycheung** [comment]
Thanks Tim,

Yeah it turns out I had duplicated gene names in the genes.tsv file, and I made them all unique with the make.unique as you suggested.  FindVariableGenes is working fine now.

Thanks a lot,

Leonard
