### ISSUE TITLE
Problem with FindVariableGenes

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#124]
Hi, I am following the tutorial on one of my samples and I am getting an error when I run the FindVariableGenes.

Error in kde2d(x = gene.mean, y = gene.dispersion.scaled) : 
  bandwidths must be strictly positive

Help would be greatly appreciated.

Thanks,

Bibaswan

**Comment by satijalab** [comment]
Can't debug the problem too carefully without the data, but if you set do.contour=F, that should at least allow you to continue (will only affect the plot)

**Comment by ghoshal** [comment]
If I do that then later on when I run the RunPCA for dimension reduction then I get the following error.

Error in irlba(A = t(x = data.use), nv = pcs.compute, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

**Comment by MattMyint** [comment]
Hi, I'm facing the same problem when trying to run a dataset of 119 cells, with TPM values ranging from 0 to 99050.2.

I normally run FindVariableGenes with `x.low.cutoff = 0.1, y.cutoff = 0.5`, however, even changing this still returns the error message.

Furthermore, when I try to set `do.contour = FALSE`, the function ends up running near forever with the message looping over and over.
```
Unknown Type: ... (11)
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
```

 I'm not sure if this is actually an infinite loop, but i only let it run for a maximum of 3 min before giving up.

Thanks,
Matthew

**Comment by satijalab** [comment]
Closing this issue as it appear to be solved, note that as the previous user mentions, please run ScaleData on your object prior to running PCA to avoid this error

**Comment by plijnzaad** [comment]
> Error in kde2d(x = gene.mean, y = gene.dispersion.scaled) :
> bandwidths must be strictly positive
> 

I had this when I did the first tutorial with _actual_ percentages (i.e. fraction*100) for filtering on mitochondrial genes but then forgot the adjust the rest of the `high.thresholds` while copy-pasting (note to authors: please don't call it a percentage ... ). Result is that most of the cells don't survive the filtering, leading to a zero interquartile range (used by density estimator).  I.e. make sure you have enough cells.

**Comment by veghp** [comment]
I had this error when I subset the data using the following cell list:
`cell.list <- seuratobject@ident[!(seuratobject@meta.data$nUMI > 75000)]`
One has to use `names()` to avoid this problem:
`seuratobject <- SubsetData(seuratobject, cells.use=names(cell.list), subset.raw=F)`

**Comment by leonfodoulian** [comment]
Hi @veghp,

In your case, you are obliged to use the `names()` function, because your subsetting gives you a vector of identities, and not cell names (however, the identities are named with their corresponding cell names).

Best,
Leon
