### ISSUE TITLE
Original ID per cluster in integrated data set

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1242]
Hello!

I've recently integrated two data sets and performed the tSNE clustering. 
```
DimPlot(object = sc10x, reduction = "tsne")
DimPlot(object = sc10x, reduction = "tsne", group.by = "orig.ident")
```
Allows me to view the tSNE clusters and the tSNE colored by the original identities of the two samples. 

Is there a way to ask Seurat how many cells in each cluster come from each sample? Example: Cluster 0 = 50 cells sample 1 and 300 cells sample 2

Thanks!

**Comment by timoast** [comment]
You can use the `table` function, for example:

```r
table(pbmc_small$letter.idents, pbmc_small$RNA_snn_res.1)
```
```
     0  1  2
  A 35  1 17
  B  1 24  2
```

**Comment by tmccra2** [comment]
Thanks for your response! When I look at my metadata for the "RNA_snn_..." line, its only present for one of the samples and seems to be showing me the original clustering prior to integration. I'd like to look at how both of my samples contribute to the combined clusters

**Comment by timoast** [comment]
When you run clustering in Seurat v3, the results will be stored with a prefix describing the assay used to produce the clusters. The integration procedure creates a new assay called "integrated" by default, so to access the integrated clustering results, you need to look for "integrated_snn..." in the metadata.

**Comment by tmccra2** [comment]
Got it! Thanks for your quick response and help!
