### ISSUE TITLE
HVG plot 

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#1243]
Hi!
I have a doubt in the HVG plot. If Y axis is showing the variance of each gene, and the variance cannot be negative (the low value can only be 0 if no differences were found in a the expression of a gene among all cells in a dataset), what represents the points that appear below 0 variance in the HVG plot? And why the plot has such a curious form at the bottom (multiple decreasing peaks, with a blue shadow and with white lines, mostly in the first peak)? It seems weird to me. 
Thanks a lot!
Marina

**Comment by leonfodoulian** [comment]
Hi Marina,

Details regarding this function (`Seurat::FindVariableGenes()`) can be found in the documentation of the function (simply use `?Seurat::FindVariableGenes` in `R`).

Briefly, what is plotted on the y-axis is the dispersion of the genes (i.e. `log(Variance/Mean)`). In fact, genes are binned in a given number of bins (defined in the `num.bin` argument of the function, which is by default set to 20) based on their mean expression values (i.e. their location on the x-axis). Then, dispersion values of the genes in each bin are z-scored (i.e. scaled if you prefer). Although dispersion values cannot be negative, z-scoring the data centers the data with a mean of 0 and a standard deviation of 1, hence the negative values. Regarding the white lines, these represent the density of points on the plot, indicating that many more genes have low mean expression values, and fewer ones have high mean expression values across the cells.

Best,
Leon

**Comment by satijalab** [comment]
I would add that we have significantly re-organized this procedure in Seurat v3. Here, we learn the mean-variance relationship from the unnormalized count data, and then identify genes that are outliers based on these trends. This is described in the Supplementary Methods of:
https://www.biorxiv.org/node/138080

If you have a UMI dataset, we particularly recommend trying a set of new features we have implemented based on the modeling of UMI count data using a regularized NB distribution, described here:
https://www.biorxiv.org/content/10.1101/576827v2
