### ISSUE TITLE
CCA gene loading

### ISSUE THREAD

**Issue by livnatje** [satijalab/seurat#1244]
Hi!

Thank you for developing and providing this great framework!

I'm using CCA, which works beautifully! But, I'm not how the final (unified) gene loadings are obtained (the output of _GetGeneLoadings(object, reduction.type = "cca")_), and I was wondering if you could explain. If I understand correctly, each dataset has its own gene loading for projection CCA#i, such that the loadings of the different datasets are highly correlated, right?

So how do you obtain the final/single gene loading for each projection?

Thanks!
Livnat

**Comment by andrewwbutler** [comment]
Hi,

We use CCA to find cell embedding which project the cells into highly correlated subspaces. To get the gene loadings, we multiply the original scaled data (input to CCA) by these cell embeddings to get loadings per dimension.

**Comment by livnatje** [comment]
I see, thanks for explaining! So there is no additional adjustment in the gene space, as you do on the cell loadings. Also, if there are some significantly larger datasets they will dominate the loading, but that should be easy to fix.
