### ISSUE TITLE
marking subsets from pooled dataset in tsne-plot

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#1245]
Hi, 

In a tsne-plot of pooled datasets how can I mark (red) just one patient, while leaving (but still plotting) the rest grey? 
Something like this (patientID is added to seuratobj@meta.data)?
`TSNEPlot(object = seuratobj, do.label = F,  pt.size = 2, group.by = "patientID", no.axes = T)
`
, but where to I match the patient with the color?

Or maybe with the FeaturePlot function:
```
FeaturePlot(object = seuratobj,
            features.plot = features.plot,
            cols.use = c("grey", "red"),
            pt.size = 1,
            reduction.use = "tsne",
            no.axes = T,
            nCol = 4)
```
but then how shall I define features.plot?

Thank you for any tips!

**Comment by andrewwbutler** [comment]
In v2, you can use `TSNEPlot` as you have above but also provide the `colors.use` parameter with a vector of colors corresponding to each patient.

**Comment by pbrazda** [comment]
One more question; 

When I do 
```
TSNEPlot(object = seuratobj,
         do.label = F,
         pt.size = 2, 
         colors.use = c("red",
                        "grey",
                        "grey",
                        "grey",
                        "grey"),
         no.axes = T)
```
The colouring is based on the clusters, so in this case only cluster0 of the five clusters will be red. I wanted to give the mark based on the patients instead, listed in the 'patient' column of seuratobj@meta.data. How do I select for those?
Thanks!
