### ISSUE TITLE
Use cca.aligned in v3 for tSNE and clustering

### ISSUE THREAD

**Issue by Sethupathy-Lab** [satijalab/seurat#1246]
Hi,

We are migrating from Seurat v2 to v3. In our previous workflow, we used:

```
SeuratObjCombined <- RunCCA(SeuratObj1, 
                            SeuratObj2, 
                            genes.use = genes_list, 
                            num.cc = 30)

SeuratObjCombined <- AlignSubspace(SeuratObjCombined, 
                                   reduction.type = "cca", 
                                   grouping.var = "group", 
                                   dims.align = 1:20)

# CCA t-SNE and Clustering
SeuratObjCombined <- RunTSNE(SeuratObjCombined, 
                             reduction.use = "cca.aligned", 
                             genes.use = genes_list, 
                             dims.use = 1:20, 
                             do.fast = T)

SeuratObjCombined <- FindClusters(SeuratObjCombined, 
                                  reduction.type = "cca.aligned", 
                                  resolution = 0.6, 
                                  dims.use = 1:20)
```

It seems that v3 has done away with AlignSubspace and instead uses FindIntegrationArrows followed by IntegrateData, but is there any way to get cca.aligned for our tSNE and clustering functions?

Thanks for your help!
Matt

**Comment by andrewwbutler** [comment]
Hi Matt,

For v3, we recommend the integration procedure described the [pre-print here](https://www.biorxiv.org/content/early/2018/11/02/460147) and demonstrated in [this vignette](https://satijalab.org/seurat/pancreas_integration_label_transfer.html) as we believe this represents a significant improvement over the implementation in v2. If you want to use cca followed by `AlignSubspace`, you'll need to reinstall Seurat v2.
