### ISSUE TITLE
install version 3 in Anconda

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#1247]
Hi, 
I tried to install v3 in Anconda
devtools::install_github(repo = "satijalab/seurat", ref = "release/3.0")
I got the below error:
![image](https://user-images.githubusercontent.com/23288387/54613346-f02edf00-4a30-11e9-809a-63f719d942a7.png)

It works in R studio, but it does not work in Anocnda. Thanks

**Comment by andrewwbutler** [comment]
Are you able to install any R packages in your Anaconda environment (try a few of the ones listed in the error message) and also, are you able to install any other R package using `install_github`?
