### ISSUE TITLE
"Warning in irlba" while scaling data matrix (4 10X Samples)

### ISSUE THREAD

**Issue by rondjlee** [satijalab/seurat#1249]
Warning in irlba(A = t(x = data.use), nv = pcs.compute, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.

Do you guys have any idea what I can do differently?

**Comment by andrewwbutler** [comment]
This doesn't look like an issue with `ScaleData`. It looks like an warning from `RunPCA`. We use an approximate algorithm for PCA which doesn't provide much benefit if the number of features is close to the number of PCs requested. It is usually safe to ignore this message.

**Comment by vertesy** [comment]
Also happened to me when accidentally passing on `..., npcs = NULL`.
