### ISSUE TITLE
How can I change the  x-axis ordering in VlnPlot?

### ISSUE THREAD

**Issue by cjpark85** [satijalab/seurat#1250]
Hello, 
I found some similar issue, #463 and #559 and tried to make it, but I couldn't. I have two different groups. When I draw VlnPlot, EB300 is appeared first in x-axis.
How can I change the order of the items on the x axis like 'Intact' 'EB300'?
Also, can I exclude 'NA' from my data as well as in this plot?

```R
table(combined@meta.data$orig.ident)
  10Xhypo_EB300 10Xhypo_Intact 
           3307           3566 
VlnPlot(object = combined, features = c("Bad", "Bax"), group.by = "orig.ident")
```

![image](https://user-images.githubusercontent.com/48735218/54641297-dce73800-4a5f-11e9-9054-65b47228da0c.png)

   
 version  R version 3.5.2 (2018-12-20)
 Seurat         * 3.0.0.9000 2018-12-17 [1] Github (satijalab/seurat@aa9ffda)

**Comment by mojaveazure** [comment]
Have you tried making the `orig.ident` metadata column a factor ordered in the way you prefer?

```R
combined$orig.ident <- factor(x = combined$orig.ident, levels = c('10Xhypo_Intact', '10Xhypo_EB300'))
```

**Comment by cjpark85** [comment]
mojaveazure, Thank you! It works well.
