### ISSUE TITLE
Dimplot cells.highlight overwhelmed by unassigned class

### ISSUE THREAD

**Issue by danielruss** [satijalab/seurat#1253]
Hello,  I am trying to create a plot using DimPlot with cells.hightlight but the unassigned class is overwhelming the plot.  Using the clustered PBMC data as a starting point (I also created a UMAP, but a TSNE should show the same issue).  To simulate the problem, you need to create "fake" clusters that overlap, and set the pt.size to a large value so they overlap.
 

`pbmc$fake <- sample(0:7,size=ncol(pbmc),replace=T)
DimPlot(pbmc,label=T,pt.size=4,group.by="fake", cells.highlight=WhichCells(pbmc,expression=fake==4),cols="grey"  )
DimPlot(pbmc,label=T,pt.size=4,group.by="fake", cells =WhichCells(pbmc,expression=fake==4))
`

Notice that the grey unselected class dominates the plot (the highlighted class is barely visible).  I tried adding order=c("Group_1","Unselected"); order=c("Unselected","Group_1"); order=c(4,"Unselected"), order=c("4","Unselected")  I tried variations of setting the cols.highlight,  but I cannot get a layer plotted for the Unassigned, and then a layer for the groups.  I've even tried to emulate the what I want without using cells.highlight, but by setting the order and the cols.  

Is this the desired behavior?

**Comment by andrewwbutler** [comment]
Hi,

Thanks pointing this out. The `cells.highlight` parameter should now work as expected with the highlighted cells being plotted last (on top) as of feae377.
