### ISSUE TITLE
Find DEGs after doing integration

### ISSUE THREAD

**Issue by azazel777** [satijalab/seurat#1256]
Dear Seurat Team,

I'm doing a control vs treatment experiment on 2 groups and 4 batches (8 samples in total).

According to this https://satijalab.org/seurat/pancreas_integration_label_transfer.html tutorial.

I did:

1. Merge every pair of control and treatment groups as a single batch. So I have 4 Seurat objects named "Batch1" to "Batch4", and save all 4 batches into a list.

2. Doing "NormalizeData" and "FindVariableFeatures" on every batch in the list by for loop.

3.Run "FindIntegrationAnchors" and "IntegrateData". Here I set the "features.to.integrate" to all gene, because I want to do DEG analysis on whole data set. As your team mentioned here: https://github.com/satijalab/seurat/issues/1091#issuecomment-457285643 , we can set this parameter to integrate all genes. But you also didn't recommend to find markers on a corrected dataset. Instead, set the activate assay back to "RNA". So I'm confused if the integration can remove the batch effect, why we have to find the DEGs on an uncorrected data? 

4. I also continued to finish "ScaleData","RunPCA","JackStraw","FindNeighbors","FindClusters"and "Findmarkers" of paired cell type on corrected data with whole genes, just like the normal pipeline.
I know this method is not recommended by your team, but it seems no other choice here.

I think maybe I missed some important tutorial or some basic concepts.

Please give me some suggestion.

Best regards,

Richard

**Comment by satijalab** [comment]
As a general rule, we always recommend performing DE on originally measured values - instead of on batch-corrected, imputed, etc. values.

This ensures that the measurements that enter the DE test are indeed independent from each other, which is a requirement of any statistical DE test.
