### ISSUE TITLE
Scatter plot of average gene expression across 2 samples existing within the same seurat object

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#1258]
Hello, first off thank you for such a user-friendly and excellent tool for scRNAseq analysis!

I have a question regarding scatter plots, where I am comparing the average gene expression of two samples. I know this issue has a vignette and has been [discussed,](https://satijalab.org/seurat/immune_alignment.html) however, how can I 

1. calculate the R squared value of a scatter plot, and add a trendline?
2. Also, The vignette is for Seurat 3, how can you label genes on a scatter plot using v2.3.4? The labelUR function doesn't work in the older version of Seurat (v2.3.4), or is there something I am missing?
3. How can I color code a certain region of the scatter plot, say make all cells deviating from the R squared, trendline by some factor say standard deviation? So that all outliers turn red (so that we can identify easily genes having high expression in one sample vs the other?)

# Here is my code (where: HP2300_HP2304.combined.cells is a combined seurat object, generated by the MergeSeurat function) 

HP2300_HP2304.combined.cells <- SetAllIdent(HP2300_HP2304.combined, id = "HP2300")
avg.HP2300_HP2304.combined.cells <- log1p(AverageExpression(HP2300_HP2304.combined.cells, show.progress = TRUE))
avg.HP2300_HP2304.combined.cells$gene <- rownames(avg.HP2300_HP2304.combined.cells)

p1 <- ggplot(avg.HP2300_HP2304.combined.cells, aes(HP2304, HP2300)) + geom_point() + ggtitle("Scatter")

scatterplot <- plot_grid(p1)
print(scatterplot)

# This is what I get:

![Rplot](https://user-images.githubusercontent.com/39837140/54777605-0a132200-4be9-11e9-997f-dc48d8f1e7e7.png)

Is there a better way of doing this?
Thank you so much for your help!!

P.S. This is how I did the Merging:

HP2300.data <- Read10X(data.dir = "C:/~10x Gen imput files/HP2300/filtered_feature_bc_matrix")
HP2300 <- CreateSeuratObject(raw.data = HP2300.data,
                             project = "HP2300")

HP2304.data <- Read10X(data.dir = "C:/~10x Gen input files/HP2304/filtered_feature_bc_matrix")
HP2304 <- CreateSeuratObject(raw.data = HP2304.data,
                             project = "HP2304"
)

# Merging HP2300 with HP2304
HP2300_HP2304.combined <- MergeSeurat(object1 = HP2300, 
                               object2 = HP2304, 
                               add.cell.id1 = "HP2300",
                               add.cell.id2 = "HP2304",
                               project = "HP2300_HP2304"
)

# Check data
tail(HP2300_HP2304.combined@cell.names)
head(x = HP2300_HP2304.combined@cell.names)
table(HP2300_HP2304.combined@meta.data$orig.ident)

# Cheers!!

**Comment by Dragonmasterx87** [comment]
P.S. This is how I did the Merging:

HP2300.data <- Read10X(data.dir = "C:/Users/mxq52/Box/Fahd Shared JUAN/Dominguez-Bendala, Juan scRNAseq prj/10x Gen input files/HP2300/filtered_feature_bc_matrix")
HP2300 <- CreateSeuratObject(raw.data = HP2300.data,
                             project = "HP2300")

HP2304.data <- Read10X(data.dir = "C:/Users/mxq52/Box/Fahd Shared JUAN/Dominguez-Bendala, Juan scRNAseq prj/10x Gen input files/HP2304/filtered_feature_bc_matrix")
HP2304 <- CreateSeuratObject(raw.data = HP2304.data,
                             project = "HP2304"
)

# Merging HP2300 with HP2304
HP2300_HP2304.combined <- MergeSeurat(object1 = HP2300, 
                               object2 = HP2304, 
                               add.cell.id1 = "HP2300",
                               add.cell.id2 = "HP2304",
                               project = "HP2300_HP2304"
)

# Check data
tail(HP2300_HP2304.combined@cell.names)
head(x = HP2300_HP2304.combined@cell.names)
table(HP2300_HP2304.combined@meta.data$orig.ident)


# Cheers!!

**Comment by andrewwbutler** [comment]
Hi,

These are mostly not Seurat specific questions but I'll answer briefly. 

1.  You can construct a linear model with the `lm` function in R. Calling `summary` on the model that is returned will give you the R-squared value. 
2. The vignette you linked above is for v2 not v3 so all code used there should work with Seurat v2.3.4
3. One way of doing this would be to add a column to the data.frame that you're plotting (`avg.HP2300_HP2304.combined.cells`) that specifies whether or not you classify the point as an outlier. Then your aesthetic mapping for color in the ggplot call would be that variable.

**Comment by Dragonmasterx87** [comment]
@andrewwbutler Cheers mate. I'm going to work on this and share the code with you once I get it to work. I'm trying to do something shown similar to Fig 4D [here](https://www.nature.com/articles/s41467-018-06176-3).

Will let you know!!
