### ISSUE TITLE
cannot coerce class ‘structure("seurat", package = "Seurat")’ to a data.frame

### ISSUE THREAD

**Issue by ElleRDZ** [satijalab/seurat#1259]
Hello!

I'm trying to run this command, and I keep getting this error:

>names(Rep1B)[-1]=paste(topcells[1,3],names(Rep1B)[-1],sep="_")
>names(Rep2B)[-1]=paste(topcells[2,3],names(Rep2B)[-1],sep="_")
> mousetmp=Reduce(function(x,y) merge(x,y,all=TRUE), list(Rep1B,Rep2B) )
Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("seurat", package = "Seurat")’ to a data.frame

I also checked if my files are updated and yes they are (or is it that my code is too old for the new version?)

> UpdateSeuratObject(Rep1B)
Object representation is consistent with the most current Seurat version.
An object of class seurat in project Rep1B

> UpdateSeuratObject(Rep2B)
Object representation is consistent with the most current Seurat version.
An object of class seurat in project Rep2B

Do you have an idea of how can I fix this?

Thank you very much for your patience and help!

**Comment by andrewwbutler** [comment]
Which version of Seurat are you using? It looks like the objects are still v2 objects if the class is being returned is lowercase "seurat". If you want to use `merge` to merge the objects, you'll need to update to v3. The v2 equivalent would be `MergeSeurat`.

**Comment by ElleRDZ** [comment]
I'm so sorry, I know I should've checked this earlier. For some reason, I thought I was running my code on V3, but I was using V2. So I updated everything to V3, but I get this error now:

> names(Rep1B)[-1]=paste(topcells[1,3],names(Rep1B)[-1],sep="")
Error in names(Rep1B)[-1] = paste(topcells[1, 3], names(Rep1B)[-1],  : 
  invalid to use names()<- on an S4 object of class 'Seurat'

I tried to look around what this would mean, but I haven't been able to find anything about it.

Could you please help me out?

Thank you very much!!

**Comment by ElleRDZ** [comment]
I'm so sorry, I thought I was using V3 and it was V2. I'll close the thread. Thank you very much!!
