### ISSUE TITLE
Error in creating Seurat Object

### ISSUE THREAD

**Issue by iakovrudenko** [satijalab/seurat#1261]
Hi,

I am new to R and Seurat and currently trying to go over tutorial: https://satijalab.org/seurat/immune_alignment.html

I would greatly appreciate if someone can help me to solve simple error. 

> ctrl <- CreateSeuratObject(raw.data = ctrl.data, project = "IMMUNE_CTRL", min.cells = 5)
Error in CreateSeuratObject(raw.data = ctrl.data, project = "IMMUNE_CTRL",  : 
  unused argument (raw.data = ctrl.data)

Thanks

**Comment by Dragonmasterx87** [comment]
I think this tutorial is for Seurat v3, and if you did:

Install.packages('Seurat')

You installed v2.3.4 by default.

Have you done the [first](https://satijalab.org/seurat/pbmc3k_tutorial.html) tutorial? I suggest doing that first, before installing v3.0

**Comment by timoast** [comment]
If you're learning to use Seurat now I highly recommend installing version 3, going through the v3 tutorials and ignore the v2 tutorials completely. We have a v3 version of the pbmc 3k vignette here: https://satijalab.org/seurat/pbmc3k_tutorial_v3.html 

@iakovrudenko, it looks like you have v3 installed but are following the v2 tutorial for immune alignment, you can look at the integration vignette for v3 here: https://satijalab.org/seurat/pancreas_integration_label_transfer.html

**Comment by iakovrudenko** [comment]
> I think this tutorial is for Seurat v3, and if you did:
> Install.packages('Seurat')
> You installed v2.3.4 by default.
> Have you done the first tutorial? I suggest doing that first, before installing v3.0
> I am learning myself, so take what I say with a pinch of salt till a dev comments 👍

Thanks, this actually helped.

**Comment by iakovrudenko** [comment]
> If you're learning to use Seurat now I highly recommend installing version 3, going through the v3 tutorials and ignore the v2 tutorials completely. We have a v3 version of the pbmc 3k vignette here: https://satijalab.org/seurat/pbmc3k_tutorial_v3.html
> @iakovrudenko, it looks like you have v3 installed but are following the v2 tutorial for immune alignment, you can look at the integration vignette for v3 here: https://satijalab.org/seurat/pancreas_integration_label_transfer.html

Thanks, will try

**Comment by Dragonmasterx87** [comment]
BTW @timoast nice review in [NatRevGenet.](https://www.nature.com/articles/s41576-019-0093-7) Cheers. 🐉
