### ISSUE TITLE
HTODemux Error

### ISSUE THREAD

**Issue by sri540** [satijalab/seurat#1263]
I'm getting the following error when tried to use HTODemux() on hashing data of 8 samples. 

I added lower(c(0,0)) to fitdist() using trace("HTODemux",edit=TRUE). Is there a fix for this?

cd4_seurat_obj <- HTODemux(cd4_seurat_obj,
+                            assay.type = "HTO",
+                            positive_quantile =0.99,
+                            print.output = FALSE)
<simpleError in constrOptim(theta = vstart, f = fnobj, ui = Mat, ci = Bnd, grad = gradient,     fix.arg = fix.arg, obs = data, ddistnam = ddistname, hessian = !is.null(gradient),     method = meth, ...): initial value is not in the interior of the feasible region>
 Show Traceback
 
 Rerun with Debug
 Error in fitdist(hto_values_use, "nbinom", lower = c(0, 0)) : 
  the function mle failed to estimate the parameters, 
                with the error code 100

**Comment by satijalab** [comment]
We haven't seen this error before, it seems like its not possible to fit a negative binomial distribution to your hashing data- which suggests that you may have very sparse values for your hashing data that may be incompatible with HTODemux.

I will note that you can also try the `MULTIseqDemux()` function that implements the procedure form https://www.biorxiv.org/content/early/2018/08/08/387241, as an alternative
