### ISSUE TITLE
Two "seed" in function AddModuleScore

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1264]
Hi : 
    I just want to make clearly that what`s the different between "seed.use" and "random.seed" in function AddModuleScore ? I check the source code that they may only functioned in the command line "set.seed(seed = random.seed)" , so the seed.use seems useless ?

Best

**Comment by andrewwbutler** [comment]
Hi,

`seed.use` can be ignored. Only `random.seed` seems to be used in that function. 

In v3, both arguments have been replaced by `seed`.
