### ISSUE TITLE
Export mergedseurat file to csv

### ISSUE THREAD

**Issue by bwrich02** [satijalab/seurat#1265]
I am trying to export a merged Seurat file to .csv for analysis in another program.

library(data.table)
data_to_write_out <- as.data.frame(as.matrix(seuratObject@scale.data))
fwrite(x = data_to_write_out, file = "outfile.csv")

While the following works for a single object, when I used a merged object I receive the following error:

Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

Any help would be greatly appreciated.

**Comment by timoast** [comment]
Hi, this is likely because `scale.data` will be cleared during the merge. You will need to rescale the data after merging the objects.
