### ISSUE TITLE
DimHeatmap fast = T does not return the plot

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#1266]
This might be an obvious side-effect of not using ggplot when fast=T in DimHeatmap; however, I see differing behaviors:

```
# This implies fast = T.  It plots the heatmap and returns NULL
x <- DimHeatmap(object = seuratObj, dims = 1, cells = 500, balanced = TRUE)

# This returns the ggplot object as the documentation suggests:
x <- DimHeatmap(object = seuratObj, dims = 1, cells = 500, balanced = TRUE, fast = F)
```

I assume when fast=T and ggplot is not used, one cant return a ggplot object.  It might be nice to update your docs to that effect though, and note the default is actually not going to return that ggplot object.

**Comment by andrewwbutler** [comment]
Yes, when using `fast = TRUE`, `DimHeatmap` uses `image` to generate the heatmap which is faster but doesn't give you a ggplot object to manipulate. I've updated the return value info (as of 
9ec4396) to reflect that by default, this doesn't return anything but will return a ggplot object if `fast=FALSE`.
