### ISSUE TITLE
Order is ignored in FeaturePlot for version 3

### ISSUE THREAD

**Issue by koetjen** [satijalab/seurat#1272]
Specifying subgroups for FeaturePlot(object, order = ordered.list) or DimPlot(object, order=ordered.list) does not change the cell plotting order.

I re-installed from Github after the recent issue with cells.highlight #1253 was fixed, but it didn't help.

For FeaturePlot(), does order need to be passed to SingleDimPlot here?
https://github.com/satijalab/seurat/blob/0b51e414fde3c4d8d7e415c3dde4f414bd7c5bf5/R/visualization.R#L883

**Comment by andrewwbutler** [comment]
Hi,

I don't think `order` was originally intended to work with `FeaturePlot` (must have made it through to the docs by mistake). However, in the context of `FeaturePlot` I can see `order` being useful as a boolean of whether or not to plot cells in the order of their expression of the feature (so highly expressed genes show up on top for example). Is that how you were envisioning it working?

**Comment by koetjen** [comment]
Hi Andrew,

Thanks for your help. I have been trying to use order in either DimPlot or FeaturePlot, and have been unsuccessful with both in version 3. I agree that DimPlot makes more sense, but I can convert to work with FeaturePlot if needed, so tried that as well.

For both DimPlot and FeaturePlot, the order was just being ignored in v3 without giving any particular error. I updated to the newest 3.0 release this week (to see if addressing the cells.highlight issues would also help), and have an additional problem with DimPlot that plots only one of the cells and then gives an error for the rest.

> summary(Idents(XPv4))
 MUT   WT   ND 
  17   47 6110 
> DimPlot(XPv4, cols = c("red", "blue", "#E8E8EE"))
> DimPlot(XPv4, order =  c("MUT","WT","ND"), cols = c("red", "blue", "#E8E8EE"))
Warning message:
Removed 6173 rows containing missing values (geom_point). 

I uploaded the object here, and you should have access: https://www.dropbox.com/s/to3jkgjti40w7ir/XPv4.rds?dl=0 <https://www.dropbox.com/s/to3jkgjti40w7ir/XPv4.rds?dl=0>

Kary

**Comment by andrewwbutler** [comment]
Hi Kary,

Thanks sending. The `DimPlot` bug should be fixed now with a reinstall. I also went ahead and added the `FeaturePlot` option to plot discussed above.

**Comment by koetjen** [comment]
It looks great, thank you!

**Comment by PhilipDusart** [comment]
I have found a similar problem, the order = TRUE works in smaller datasets, but it seems to be ignored when using larger datasets or when raster = TRUE is used. For some reason the order is ignored when rasterising the output image
