### ISSUE TITLE
HTODemux

### ISSUE THREAD

**Issue by NicolasHipp** [satijalab/seurat#1273]
Hi everyone!
I'm testing HTOdemux on my dataset. 
We have a scRNAseq experiment with 8 wells of 10X genomics chromium. In each well we mix 2 samples tagged with an HTO. So we have in theory 16 unique samples. 

I first tried with the full dataset (I used cellranger aggr to merge the 8 wells) but it produces me a bug so I take a subset to understand but the problem still exist :
So I take 2 GEM wells, subset 100 cells in each libraries.
So I have 4 HTO and 176  cells with an UMI find with CITE-seq-Count (NYGC) and from 10X output in this subset

```
> HTO_tab2<-dtm_cbind(mat_HTO1[1:2,1:100],mat_HTO2[1:2,1:100])
> test<-Read10X("~/ScRNAseq/10X/Analyse/Dossier_Gene_expression/Full_first_run_none_normalization/outs/filtered_feature_bc_matrix/")
> joint_bcs <- intersect(colnames(test),colnames(HTO_tab2))
> pbmc_umi_sparse <- test[,joint_bcs]
> pbmc_hto <- as.matrix(HTO_tab2[,joint_bcs])
> print (rownames(pbmc_hto))
[1] "HTO1_lib1" "HTO2_lib1" "HTO1_lib2" "HTO2_lib2"
> dim(pbmc_hto)
[1]   4 176
> pbmc_hashtag <- CreateSeuratObject(pbmc_umi_sparse)
> pbmc_hashtag <- NormalizeData(pbmc_hashtag,display.progress = FALSE)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> pbmc_hashtag <- FindVariableFeatures(pbmc_hashtag,do.plot = F,display.progress = T)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> pbmc_hashtag <- ScaleData(pbmc_hashtag,genes.use = pbmc_hashtag@var.genes,display.progress = T)
Scaling data matrix
  |==================================================================================================================| 100%
> pbmc_hashtag[["HTO"]]<-CreateAssayObject(counts=pbmc_hto)
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
> pbmc_hashtag <- NormalizeData(pbmc_hashtag,assay = "HTO",normalization.method = "CLR",display.progress = T)
Normalizing across features
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 04s
> pbmc_hashtag <- HTODemux(pbmc_hashtag, assay = "HTO" , positive.quantile =  0.99, verbose=T, init=5)
Error in HTODemux(pbmc_hashtag, assay = "HTO", positive.quantile = 0.99,  : 
  Cells with zero counts exist as a cluster.
```

When I looked in the dataset from the tutorial, HTO assay is quite different from mine :

```
>pbmc_hashtag@assays$HTO@counts[,c(1:10,166:176)]
4 x 21 sparse Matrix of class "dgCMatrix"
   [[ suppressing 21 column names ‘AAATGCCCATCAGTCA-1’, ‘AACTCTTTCTGCTTGC-1’, ‘ACACCCTAGCCGGTAA-1’ ... ]]
                                                                                                
HTO1-lib1  45 1023 828  909  19 943 1102 964 929 761   .   .   .   .   .   .   .   .   .   .   .
HTO2-lib1 993  125  28 1115 958  70  126 207  97 249   .   .   .   .   .   .   .   .   .   .   .
HTO1-lib2   .    .   .    .   .   .    .   .   .   . 875  76 793 845  58 849 121 794 802 886 871
HTO2-lib2   .    .   .    .   .   .    .   .   .   .  63 886  40  80 876  35 856 102  69  33  79
```
and from the tutorial

```
> pbmc_hashtag2@assays$HTO@counts[,1:10]
8 x 10 sparse Matrix of class "dgCMatrix"
   [[ suppressing 10 column names ‘CCTTTCTGTCCGAACC’, ‘CTGATAGGTGACTCAT’, ‘AGCTCTCGTTGTCTTT’ ... ]]

HTO-A   19    4   21   11    8 2490   5   16   21   24
HTO-B   60   11   11 1190 6821    3  11 5929   23   13
HTO-C 2686   12    3   25   16   19   8 2946    9   13
HTO-D   48    9   21   22    9   12  16   45   11    6
HTO-E   10    8 3156    9   53   16   3 2998    4   36
HTO-F   41 1206   41   13   26   16  21   47   29    9
HTO-G   95   44   69   41   52   33  42   89   35 2045
HTO-H 1189   22   24   10   22   23 725   20 1602   16

```

When I looked in the HTOdataset from the tutorial I found some cells with no count in one HTO, but I'm wondering If the design of my experiment with all these "0" in HTO induce this error? 
Maybe as my samples don't come from the same GEM well I have to identify doublets by well before remove them from the dataset?

**Comment by bbimber** [comment]
For what it's worth, we also hit this.  The crux seems to be that after clustering the HTO counts, HTODemux tries to establish a background threshold based on the cluster with the lowest # of reads from each HTO.  If a cluster is negative, this would fail.  Would it be reasonable to base that threshold on the lowest non-zero cluster?  Something like:

minNonZero <- which.min(x = average.expression[iter,average.expression[iter, ] > 0])
  values.use <- values[WhichCells(
    object = object,
    idents = levels(x = Idents(object = object))[[minNonZero]]
  )]

Perhaps a smarter threshold could try to look at the distribution of average.expression across clusters and select the bottom 0.05?  The only issue is that one could run HTODemux with any number of barcodes, and a 1-2 barcode experiment would be much different than an 8 barcode input.

**Comment by satijalab** [comment]
These are good ideas and we will explore. I would mention that we also support an alternative demultiplexing technique, MULTIseqDemux() - that may work better for these samples.

**Comment by NicolasHipp** [comment]
Thanks for these answers, I will try both

**Comment by jdgagnon** [comment]
Hi, I am seeing a similar issue with HTODemux() but when I try to use MULTIseqDemux(), I get the following error:

`Error in model(x) : could not find function "model"`

Any suggestions? Is this function deprecated?
