### ISSUE TITLE
AddSamples bug when using min.genes and add.cell.id argument

### ISSUE THREAD

**Issue by boyinggong** [satijalab/seurat#1274]
This is related to #431, I get the same error when merging two objects if I use the argument `min.genes` and `add.cell.id` at the same time. This is because of the following lines of code in `AddSamples` function.

line 31-36. If I use `add.cell.id`, the dimension of `combined.meta.data` will be the number of cells BEFORE filtering.
```R
  if (!is.null(x = add.cell.id)) {
    combined.meta.data$orig.ident <- factor(x = combined.meta.data$orig.ident, 
      levels = c(levels(x = combined.meta.data$orig.ident), 
        add.cell.id))
    combined.meta.data[colnames(new.data), ] <- add.cell.id
  }
```
line 38-41. However, the new object is created AFTER the filtering.
```R
  new.object <- CreateSeuratObject(raw.data = combined.data, 
    project = project, min.cells = min.cells, min.genes = min.genes, 
    is.expr = is.expr, scale.factor = scale.factor, do.scale = F, 
    do.center = F, names.field = names.field, names.delim = names.delim)
```
As a result, when combining the meta data in line 60
```R
  new.object@meta.data <- cbind(new.object@meta.data, combined.meta.data)
```
The dimensions do not match. And it will give an error like this
```
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 39597, 39598
```

I believe there are similar errors using `MergeSeurat` although it does not give an explicit error message. But the metadata created using `MergeSeurat` will be messed up and result in a lot of `<NA>` values.

**Comment by boyinggong** [comment]
For those who encountered the same problem, you can avoid the error by setting `min.genes` to 0 and then use the `SubsetData` function to subset the object.
```R
# Keep all cells with at least 500 detected genes
min.genes <- 500
num.genes <- colSums(seurat_object@raw.data > 0)
cells.use <- names(x = num.genes[which(x = num.genes > min.genes)])
seurat_object <- (seurat_object, cells.use = cells.use)
```

**Comment by timoast** [comment]
Closing this for now as we're no longer developing v2, but please open a new issue if the same problem exists using the latest development version of Seurat v3.
