### ISSUE TITLE
Unable to use transposed sparse matrix as an input to CreateSeuratObject

### ISSUE THREAD

**Issue by davisidarta** [satijalab/seurat#1275]
Hello all,

I've been using Seurat for a few months and I really enjoy it!

Recently I stumbled into an issue when trying to create a Seurat object out of SplitSeq data (https://doi.org/10.1126/science.aam8999 , accession https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE110823). This massive data comes in .mat format, which I read into R using the readMat function from the R.matlab package. This got me a list of objects, including the DGE, which I extracted from it. The DGE is organized as an sparse matrix from the formal class dgCMatrix, from the package Matrix.

The problem is the data is wrongly formatted to be a Seurat input, as it has cells as rows and genes as columns. 

**However, giving its transpose as an input to CreateSeuratObject returns a error**: 

`Error in strsplit(x = string, split = delim) : non-character argument`

I've also tried to obtain the dense matrix from the sparse matrix I'm working with, but I get the following error: 

`Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105` 
, probably due to its gigantic size.

Any recommendations on how should I proceed? Is this a Seurat glitch or a malfunction in my own system?

Thanks in advance and congratulations for the great work the Seurat team has developed!

Cheers,
Davi

Here's my code:
```
library(Seurat)
library(Matrix)
library(fossil) 
library(plyr)
library(dplyr)
library(liger)
library(R.matlab)

#Preprocessing SplitSeq Data!

splitseq <- readMat("split_seq.mat")

spseq_dge <- splitseq$DGE

splitseq_dge <- spseq_dge

splitseq_dge@Dimnames <- list(splitseq$barcodes, splitseq$genes)

SplitSeq <- CreateSeuratObject(raw.data = t(splitseq_dge))
```

**Comment by andrewwbutler** [comment]
Hi,

It looks like the `splitseq$barcodes` are given as `integer` values, not characters which is what Seurat is expecting for cell names. A quick fix would be to just cast them to characters:

```R
splitseq_dge@Dimnames <- list(as.character(splitseq$barcodes), splitseq$genes)
```

**Comment by davisidarta** [comment]
Hello Andrew!

Thank you! That worked for me.
