### ISSUE TITLE
visualize co-expression of two genes in seurat v3

### ISSUE THREAD

**Issue by kunUCSD** [satijalab/seurat#1276]
Hi,
I'm trying to plot two genes using Seurat V3, but the "overlay" function met error.
I tried the "blend" function, but it shows a black background. Because some genes expression are not very high, it's hard to display a clear expression plot. 
I wander if there are any function I can use to mimic Seurat V2 co-plot? Thanks.
Best, Kun

**Comment by davisidarta** [comment]
Hello, Kun!

Which version of R and Seurat are you using? 

Can you give some more information, for example the outuput you get as error?

Best,

Davi

**Comment by kunUCSD** [comment]
Hi Davi,
Sorry. Here is more info:
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
> packageVersion("Seurat")
[1] ‘3.0.0.9000’

When run the featurePlot, I got this error:
> FeaturePlot(object = gc, features = c("Id4", "Utf1"), cols= c("grey", 
+                                                                              "red", "blue", "green"), overlay = TRUE)
Error in FeaturePlot(object = gc, features = c("Id4", "Utf1"), cols = c("grey",  : 
  unused argument (overlay = TRUE)

Best, Kun

**Comment by andrewwbutler** [comment]
Hi,

In Seurat v3, the parameter for visualizing co-expression on a `FeaturePlot` should be `blend = TRUE`, not `overlay = TRUE`.

**Comment by kunUCSD** [comment]
Hi Andrew,
Yes, I know the blend, but the background is black, which makes the plot not clear when the genes expression are low. I tried different color input, but didn't work. I wander if there's any possibilities I can change the color? Thanks
Best, Kun

**Comment by andrewwbutler** [comment]
You can try playing with the `blend.threshold` parameter. Currently, this function doesn't support other colors.

**Comment by kunUCSD** [comment]
I see, thank you.

Best, K
