### ISSUE TITLE
DoHeatmap gives no output in Seurat 3

### ISSUE THREAD

**Issue by polojacky** [satijalab/seurat#1277]
Hi, 
I'm running Seurat 3.0 to analyze more than 50K cells (R 3.5.2), but DoHeatmap just gives empty plots. Here is the code:
hc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) -> top10
png(file="feature.png", bg="transparent",width = dpi*40, height = dpi*20, units = "px",res = dpi,type='cairo')
DoHeatmap(object = hc.tsne, features = top10$gene) + NoLegend()
dev.off() 

Best, Frank

**Comment by andrewwbutler** [comment]
Hi,

In Seurat v3, `DoHeatmap` will return a ggplot object. Does `ggplot2::ggsave()` work?

```R
plot <- DoHeatmap(object = hc.tsne, features = top10$gene) + NoLegend()
ggplot2::ggsave(filename = "feature.png", plot = plot) # can add additional parameters similar to png 
```

**Comment by polojacky** [comment]
Thanks, I figured out that the cause is the device used. Both png and jepg format gave no output, pdf or tiff is ok.

**Comment by jessie-wangjie** [comment]
I got the same problem. pdf works, not png. 
Some datasets works for both png and pdf, some datasets work for pdf only. The png only shows the labels and legend, no heatmap.

**Comment by twmccart** [comment]
Even the PDF being created by ggsave is showing the labels and legend but not the heatmap in some PDF viewers.

**Comment by veravevo** [comment]
I'm having the same problem. Even though it worked before, suddenly when I'm trying to save a heatmap as pdf, labels and legend appear, but not the heatmap.

**Comment by atongsa** [comment]
onely show legend and labels in PDF
