### ISSUE TITLE
FindMarkers needs multi-thread computing

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#1278]
I was running FindMarkers. It took a long time for each cluster's marker identification. It seems that it was single-threaded either. Can you make it compute in a multi-threaded mode?

**Comment by timoast** [comment]
Hi, this was discussed in #457 

In v3, you can enable multi-threading through the `future` package. For example:

```r
library(future)
plan(strategy = "multicore", workers = 6)
```

**Comment by NTNguyen13** [comment]
> Hi, this was discussed in #457
> 
> In v3, you can enable multi-threading through the `future` package. For example:
> 
> ```r
> library(future)
> plan(strategy = "multicore", workers = 6)
> ```

Hi, I'm using seurat v3, I have tried to use those 2 lines of code but the FindMarkers with DESeq2 still runs in just 1 core. Can you please elaborate how to perform parallel computation in Seurat v3 please? Thank you

**Comment by ishwarvh** [comment]
> Hi, this was discussed in #457
> 
> In v3, you can enable multi-threading through the `future` package. For example:
> 
> ```r
> library(future)
> plan(strategy = "multicore", workers = 6)

Hello, 

It seems like this only works on OSX (unix based systems). All functions running still running on a single core in Windows. Is this supposed to be the case? I thought the advantage of using "future" was that its compatible with all OS's.

Using the Seurat v3 on Windows 10.

Thank you,

**Comment by ChristophH** [comment]
From the future package documentation:
Not all systems support multicore futures. For instance, it is not
supported on Microsoft Windows. Trying to create multicore futures on
non-supported systems will silently fall back to using sequential futures,
which effectively corresponds to a multicore future that can handle one
parallel process (the current one) before blocking.

I recommend `future::plan(strategy = "multiprocess", workers = 6)`, see
`?future::plan` for details.

**Comment by rjb67** [comment]
I am having a similar issue. I am able to get "multiprocess" to work just fine, but I would prefer to use multicore, but it still runs in one core even when I am trying to use multiple cores. I am running Seurat v3 on Mac.

**Comment by brianpenghe** [comment]
> From the future package documentation: Not all systems support multicore futures. For instance, it is not supported on Microsoft Windows. Trying to create multicore futures on non-supported systems will silently fall back to using sequential futures, which effectively corresponds to a multicore future that can handle one parallel process (the current one) before blocking. I recommend `future::plan(strategy = "multiprocess", workers = 6)`, see `?future::plan` for details.
> […](#)
> On Sun, Apr 14, 2019 at 5:14 AM ishwarvh ***@***.***> wrote: Hi, this was discussed in #457 <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_satijalab_seurat_issues_457&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=e2kPyDtZAzQoyPfLTjZ5kw&m=HlbdB7G97_q7dpXMPQfN6NcBr02uo59-Bj4G1V8pTGg&s=27cS3dchWr_0NI3eD9yJ1MEGQ_xAwLkb93Tgx1mxrN8&e=> In v3, you can enable multi-threading through the future package. For example: library(future) plan(strategy = "multicore", workers = 6) Hello, It seems like this only works on OSX (unix based systems). All functions running still running on a single core in Windows. Is this supposed to be the case? I thought the advantage of using "future" was that its compatible with all OS's. Using the Seurat v3 on Windows 10. Thank you, — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_satijalab_seurat_issues_1278-23issuecomment-2D482915867&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=e2kPyDtZAzQoyPfLTjZ5kw&m=HlbdB7G97_q7dpXMPQfN6NcBr02uo59-Bj4G1V8pTGg&s=mXVgNEAsplhHIom1CJvWhov9l8CXsPOzf3PDfVKbI0U&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADjuVbiF-2DInhkiFjJg8kEJI2Ux-5FaR0uJks5vgp0LgaJpZM4cLEfS&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=e2kPyDtZAzQoyPfLTjZ5kw&m=HlbdB7G97_q7dpXMPQfN6NcBr02uo59-Bj4G1V8pTGg&s=z_ASCf2zk8U83jTUC8vVRiO8CWKhf4qt-37VkutoNqQ&e=> .

multiprocess didn't work for my case : (

**Comment by kaizen89** [comment]
Is mutli-threading using future package compatible with rstudio?
When I use
```
future::plan(strategy='multiprocess', workers=6)
```
I get the error: Forked processing ('multicore') is disabled in future (>= 1.13.0) when running R from RStudio, because it is considered unstable. 
Is there a workaround?
