### ISSUE TITLE
Issue with VlnPlot

### ISSUE THREAD

**Issue by jdai265** [satijalab/seurat#128]
Hi! I'm trying to use VlnPlot, but keep running into this error:

Error in `[.data.frame`(data.use, , x, drop = FALSE) : 
  undefined columns selected

The same arguments work for FeaturePlot, and this error in VlnPlot only occurs with certain gene names. I'm not sure what the cause is. Thanks in advance!

**Comment by leonfodoulian** [comment]
Please refer to [this post](https://github.com/satijalab/seurat/issues/111).

Best,
Leon
