### ISSUE TITLE
FindAllMarkers filtering

### ISSUE THREAD

**Issue by andrebolerbarros** [satijalab/seurat#1280]
Hey!

First of all, congrats on the excellent package!

One question I had is when someone uses the function `FindAllMarkers`, does the function automatic filters the genes which have **zero cells expressing it (pct = 0 for both ident)?**. Just to check if that's the reason the result data-frame doesn't contain all the genes.

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

You can see the default parameter values in the documentation with `?FindAllMarkers`. The default value for `min.pct` is 0.1 so that is likely why the resulting data-frame doesn't contain all genes.

**Comment by andrebolerbarros** [comment]
Hey,

First of all, thanks for your response! 

I am currently defining `min.pct=0` but I still don't get the full gene dataset with the function

**Comment by andrewwbutler** [comment]
Hi,

If you really want to test every gene, you will need to set `min.pct = -Inf` and `logfc.threshold = -Inf`.
