### ISSUE TITLE
"RidgePlot"-like display for discrete values per cluster

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#1281]
Hi,

I am trying to make a type of graph that can show discrete values for each cell per cluster, like a RidgePlot but with e.g. orig.ident instead of a range of values.  I can do something like this with a FeaturePlot but I have to compare the tSNE-cluster plot with the featureplot.  I am trying to show whether some clusters are e.g. made of cells from only one sample, or are mostly in G2S/M phase.

Thanks,

Leonard

**Comment by andrewwbutler** [comment]
Hi Leonard,

I think what you probably want here is just a standard barplot. 

https://ggplot2.tidyverse.org/reference/geom_bar.html

You can pull out the relevant information from the metadata slot.

**Comment by lennycheung** [comment]
Hi Andrew,

Thanks a lot, I am quite new to R (as you can probably tell)!
I'll close this ticket.
Thanks,

Leonard
