### ISSUE TITLE
Calculating average expression of specific genes

### ISSUE THREAD

**Issue by elevenson** [satijalab/seurat#1283]
Hi,

I have made two groups within my object, not clusters.  I would like to find the average expression from the scaled data within each group for a set of specific genes. I made the groups like this:

P1RSVHIGH.vector = WhichCells(object = P1RSV, subset.name = "NS1/1C", accept.low = 4.5, accept.high = Inf)

P1RSV@meta.data$cell.type <- ifelse(rownames(P1RSV@meta.data) %in% P1RSVHIGH.vector, "HIGHRSV", "LOWRSV")

P1RSV <- SetAllIdent(object = P1RSV, id = "cell.type")

I am using 2.3.4

Thank you for your help.

**Comment by andrewwbutler** [comment]
Hi,

Please see the `AverageExpression` function.

**Comment by fionaaa12** [comment]
Hi,

@andrewwbutler I have a Seurat object that has been clustered, and there are 2 groups in each cluster. I want to use the AverageExpression function to compare the avg expression of the 2 groups within each cluster. Is there a way to do this? Thnk you!

**Comment by elevenson** [comment]
Thank you. Works great.
