### ISSUE TITLE
CreateDimReducObject

### ISSUE THREAD

**Issue by chrsyl** [satijalab/seurat#1284]
I took normalized & scaled data from my Seurat object (v3.0) and performed prcomp PCA and included the embeddings etc in CreateDimReducObject. How can I include the CreateDimReducObjec into my Seurat object for further analysis with tsne?

**Comment by mojaveazure** [comment]
You can use `[[` to add a `DimReduc` object to a Seurat object

```R
dr <- CreateDimReducObject(...)
seurat.object[['pca']] <- dr
```
