### ISSUE TITLE
Values in Y axis of a violin plot and AverageExpression function

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#1285]
Hi all,
When we represent a violin plot of a given gene expression, which values are exactly represented in Y axis? Normalized, scaled, any other change after CCA, in lineal or logarithmic scale? The values I usually found are ranking between 0 and 5 and I don't know what are they really meaning. When I plot nUMI or nGene, I understand that the values represented in Y axis are the raw number of UMIs and genes, because these parameters were not modified during the analysis after being calculated at the beginning. But after clustering cells and plot the expression of a given gene in violin plots, I don't understand how the values of expression are plotted in Y axis.
I would also like to know how the AverageExpression function calculates the mean values if not using use.scale=T or use.raw=T. Is it using and showing then normalized values? In lineal or log-scale? In addition, is there any way to calculate the SEM of these averages values and the p-value of the differences between the groups compared?
Thanks a lot!

**Comment by andrewwbutler** [comment]
Hi,

If you're plotting gene expression, the data in the `@data` slot is what gets plotted by `VlnPlot`. You can find further discussion of the different data slots in FAQ 7 [here](https://satijalab.org/seurat/faq).

 For `AverageExpression`, if you're not using `use.scale=T` or `use.raw=T`, then averaging is done with `mean(expm1(x))`. Relevant code lines here: https://github.com/satijalab/seurat/blob/9c4bcb74cec54f40163c8ea0d707ea6017f7135a/R/utilities.R#L569-L577 

There aren't any function in Seurat to compute statistics on what is returned from `AverageExpression`. If you want to look at differences between groups, I would recommend `FindMarkers`.

**Comment by mvalenzuelav** [comment]
Hi Andrew, 

So if it is used de @data slot for violin plots, then they are normalized values, right? But in FAQ 7 it is said that "The data slot (object@data) stores normalized and log-transformed single cell expression". I cannot see the Y axis in violin plots in log scale... maybe the function transform the normalized data to non-log scale to plot gene expression?

Regarding AverageExpression, I keep not understanding what "x" means in mean(exp1m(x)). Is "x" the normalized expression value of a gene from each cell? I just want to find out what kind of data is used when I don't specify scaled nor raw data. I think the other option is data from the @data slot. Thus, normalized data, but not in log scale because the function does the exponential, right? I made this question because I want to obtain the average expression values in the most "real" value to understand the "real expression". I mean, what is the option most used to give averaged expression of genes: raw, scale or the default (I guess normalized in non-log scale)?

About FindMarkers, I already run this function in my two cell groups and the genes that I am interested in obtaining their average expression values and violin plots did not appear as DE genes. So, if they were not found as DE when running this function, could I say that the differences in their average expression between the two groups are not significant? I mean... FindMarkers look for DE genes by averaging the expression of that gene along all cells in a group, right? So it looks that p-values obtained from this function can be applied to the results of AverageExpression. Is is correct? Regarding the SEM, this value cannot be obtained from FindMarkers neither, if I am not wrong. That is why I wanted to know if it was possible to calculate the SEM and p-value (in the case that it is not applicable the one obtained by FindMarkers) when running AverageExpression.

Thanks a lot!

**Comment by andrewwbutler** [comment]
`VlnPlot` doesn't perform any additional transformations on the data. It will just plot what you have stored in `@data`. You can verify this for yourself if you want by pulling the data out manually and inspecting the values. 

For `AverageExpression`, `x` comes from the `@data` slot (by default) so this function is assuming you have log transformed the data and because of the exponentiation, will therefore return the data in non-log space. 

`FindMarkers` has a number of differential expression tests (see the `test.use` parameter. Which you choose will determine how exactly it calculates whether or not the difference between the groups is significant. Standard errors aren't returned by these functions but should be straightforward to compute with base R functions. Just pull out the relevant features from the `@data` matrix.

**Comment by mvalenzuelav** [comment]
I have used the default test for FindMarkers (Wilcoxon rank sum test). So if a gene does not appear as a significant DE gene after running FindMarkers between my two groups, could I assume that there are no significant differences between my groups in terms of the gene average expression? Or should I calculated the p-value based on their average expression?

**Comment by andrewwbutler** [comment]
Yes, if a gene doesn't appear as significantly differentially expressed after running `FindMarkers` between the two groups, that means that there is no significant difference. I'm not sure how you would propose calculating a p-value based on average expression but I would recommend the first option.

**Comment by mvalenzuelav** [comment]
Thanks a lot! I think the results of FindMarkers are the best option too. I just want to confirm that not finding a gene as DE will really mean no significant differences at all. Of course, I have no idea on how to calculate a p-value based on average expression!
Thank you very much!
