### ISSUE TITLE
Change label color in DimPlot

### ISSUE THREAD

**Issue by chansigit** [satijalab/seurat#1286]
Can you please provide a parameter changing the label's color?

When I used a black-background theme, the black labels become invisible.

**Comment by andrewwbutler** [comment]
Hi,

You can get different label colors in `DimPlot` as follows 

```R
plot <- DimPlot(object = pbmc_small)
LabelClusters(plot = plot, id = "ident", color = "red")
```

**Comment by Sophia409** [comment]
how do you solve the problem?I also encounterred this problem.When I used a white-background theme, the default white labels become invisible.
![图片](https://user-images.githubusercontent.com/30619010/59159339-d0bcc500-8afa-11e9-8147-d65b171d2312.png)
How can I chang the label's color to black?
