### ISSUE TITLE
GenePlot colouring single cells

### ISSUE THREAD

**Issue by Schay95** [satijalab/seurat#1287]
Hi, 
I have created the GenePlot. **Is there a possibility to colour single cells?**

I know it is possibility with other plots, however those don't accept the Seurat object as input.
It would be really helpful!

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

In Seurat v3, there is a greater degree of flexibility with this function (which has been renamed to `FeatureScatter`) and it should behave more consistently with the other plots in terms of functionality and options. 

I'm not exactly sure what you mean by "colour single cells". Colors are determined by the current identities of the cells (or with the `group.by` option in v3) so you can manipulate the identities to get different colorings.

**Comment by Schay95** [comment]
Thanks! I will try that with Seurat v3.
