### ISSUE TITLE
How I can get average UMI for each cluster and rest in FindAllMarkers 

### ISSUE THREAD

**Issue by polojacky** [satijalab/seurat#1291]
FindAllMarkers does not give the average of all genes in each cluster and the rest, how can I get the average UMI in the differential analysis?

Best, Frank

**Comment by timoast** [comment]
Hi Frank, please see the `AverageExpression` function

**Comment by polojacky** [comment]
Thanks, that gives the average expression. By the way, how can I convert the output of FindAllMarkers to a gene-cluster matrix?
