### ISSUE TITLE
FindAllMarkers(obj) - Error in UseMethod(generic = "Idents", object = object)

### ISSUE THREAD

**Issue by alextamburino** [satijalab/seurat#1293]
Hi, I recently upgraded to Seurat v3 and am trying to interact with an object created in v2. Are they compatible? If so, can you please advise on this error?

FindAllMarkers(obj)
Error in UseMethod(generic = "Idents", object = object) :
  no applicable method for 'Idents' applied to an object of class "seurat"

Thanks, Alex

**Comment by mojaveazure** [comment]
Hi Alex,

Seurat v2 objects (`seurat` with a lower case "s") can be loaded in Seurat v3, but not used. As I [mentioned in] (https://github.com/satijalab/seurat/issues/990#issuecomment-444606845) #990, all methods in Seurat v3 will be designed for Seurat v3 objects (`Seurat` with a capital "S"). The only reason we define the v2 object is to allow people to load and upgrade their old datasets.

When using Seurat v3, we strongly recommend upgrading your v2 objects to v3 objects with `UpgradeSeuratObject`

**Comment by alextamburino** [comment]
Excellent. Thanks!
