### ISSUE TITLE
Seurat v3.0 Installation Issue Window 

### ISSUE THREAD

**Issue by whdmstjr0702** [satijalab/seurat#1294]
Hello,

I have re-installed R v3.5.3 and R Studio in my Campus Window Computer.

I tried to install Seurat v3.0 using R Studio with devtools as instructed with following code:
`devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')`

I get following error message:

> ** R
>Error : (converted from warning) unable to re-encode 'objects.R' line 1419
>ERROR: unable to collate and parse R files for package 'Seurat'
>* removing 'C:/Users/edcho/Documents/R/win-library/3.5/Seurat'
>* restoring previous 'C:/Users/edcho/Documents/R/win-library/3.5/Seurat'
>
>In R CMD INSTALL
>installation of package �C:/Users/edcho/AppData/Local/Temp/RtmpYjnLL8/file203c6d667876/Seurat_3.0.0.9000.tar.gz� had non-zero exit status

I am not sure what the issue is.  Can someone help me please? 

Thank you.

**Comment by evolvedmicrobe** [comment]
The comment on that line of the file has a character that isn't standard, you can delete this line:

https://github.com/satijalab/seurat/blob/bb45fab3d1734f6efd03909e20f9c5e1345f8864/R/objects.R#L1419

And try again.

**Comment by mojaveazure** [comment]
Sorry about that, should be fixed now.

**Comment by evolvedmicrobe** [comment]
https://github.com/satijalab/seurat/pull/1295

**Comment by mojaveazure** [comment]
Crap, sorry Nigel, didn't see that you made a PR for this.

**Comment by evolvedmicrobe** [comment]
No worries at all! It was a super quick fix, glad it was already there!
