### ISSUE TITLE
FindIntegrationAnchors - Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :    'x' must be atomic

### ISSUE THREAD

**Issue by davisidarta** [satijalab/seurat#1296]
Hello again, Seurat team!

I'm having some trouble running the `FindIntegrationAnchors` function from Seurat v3. When I create a list of Seurat objects and try to find integrated anchors, I get the following error output:

```
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
```
A chunk of example code:
```
#Load libraries
devtools::install_github(repo = "satijalab/seurat", ref = "release/3.0")
library(Seurat)
library(Matrix)
library(fossil) 
library(plyr)
library(dplyr)
library(liger)
library(R.matlab)
library(ggplot2)
library(cowplot)

#Load datasets
arc <- readRDS("~/analysis/bighyp/arc.Rds")
chen <- readRDS("~/analysis/bighyp/chen.Rds")
romanov <- readRDS("~/analysis/bighyp/romanov.Rds")
split_p2 <- readRDS("~/analysis/bighyp/split_p2.RDS")
split_p11 <- readRDS("~/analysis/bighyp/split_p11.RDS")
b1_mca <- readRDS("~/analysis/bighyp/MCA/b1_mca.Rds")
b2_mca <- readRDS("~/analysis/bighyp/MCA/b2_mca.Rds")
fetal_mca <- readRDS("~/analysis/bighyp/MCA/fetal_mca.Rds")
neo1_mca <- readRDS("~/analysis/bighyp/MCA/neo1_mca.Rds")
neo2_mca <- readRDS("~/analysis/bighyp/MCA/neo2_mca.Rds")


whole_brain <- list(split_p2, split_p11, b1_mca, b2_mca, neo1_mca, neo2_mca, fetal_mca)

for (i in 1:length(x = datasets)) {
  datasets[[i]] <- NormalizeData(datasets[[i]])
  datasets[[i]] <- FindVariableFeatures(datasets[[i]], num.bin = 300)
  
  mito.genes <- grep(pattern = "^mt-", x = rownames(x = datasets[[i]]@assays$RNA@data), value = TRUE)
  percent.mito <- Matrix::colSums(datasets[[i]]@assays$RNA@counts[mito.genes, ])/Matrix::colSums(datasets[[i]]@assays$RNA@counts)
  datasets[[i]] <- AddMetaData(object = datasets[[i]], metadata = percent.mito, col.name = "percent.mito")
  datasets[[i]] <- ScaleData(datasets[[i]], genes.use = datasets[[i]]@var.genes, vars.to.regress = ("nCount_RNA"))
}

#Constructing anchoring points between datasets

dataset.anchors <- FindIntegrationAnchors(object.list = whole_brain, dims = 1:50)

```

From what I've read from the existing documentation, FindIntegrationAnchors function takes a list of Seurat objects as input. Does anybody know what might be going on?

Thank you a lot in advance!

Best regards,

Davi

**Comment by timoast** [comment]
Shouldn’t `object.list` be `datasets` not `whole_brain`? `whole_brain` not defined here

**Comment by davisidarta** [comment]
I`m sorry, its a typo from when I copied to github. Edited and corrected.

**Comment by satijalab** [comment]
Still a bit confused, what is datasets?

**Comment by brunetc** [comment]
I am having the same problem when combining data from two different species. 

Computing 2000 integration features
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic

**Comment by awaickm1** [comment]
Hello Seurat team!

I'm getting the error when I'm attempting to run FindIntegrationAnchors using the ‘Reference-based’ integration option a set of samples following SCTransformation

`> immune.anchors <- FindIntegrationAnchors(object.list = immune.list, normalization.method = "SCT", anchor.features = immune.features, reference = reference_dataset, verbose = TRUE)
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
> traceback()
6: stop("'x' must be atomic")
5: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4: sort.default(x = reference)
3: sort(x = reference)
2: unique(x = sort(x = reference))
1: FindIntegrationAnchors(object.list = immune.list, normalization.method = "SCT", 
       anchor.features = immune.features, reference = reference_dataset, 
       verbose = TRUE)`

**Comment by adf-ncgr** [comment]
Hi, I just ran into the same issue and discovered that in my case the problem stemmed from the fact that all of my feature names contained underscore characters. These get converted in some place in the code into dashes, but then this bit of code 
`  for (i in 1:length(x = object.list)) {
    var.features <- var.features[names(x = var.features) %in% rownames(x = object.list[[i]][[assay[i]]])]
  }`
within SelectIntegrationFeatures seems to run into trouble due to inconsistency of the feature names in different places in the data structures. The result is an empty list of var.features which produces the error. I was able to remove the underscores in my input names and everything worked fine, but probably the code could be improved to avoid this issue. I imagine that if only some of the input feature names had underscores you might not get the error but these features might drop out of the integration analysis. hope that helps.

**Comment by whiteorchid** [comment]
I also tried to converted the feature names in advance(underscore to dash) and  the 'x must be atomic'  error still shows........

**Comment by whiteorchid** [comment]
```
x <- read.csv("result.csv",header =TRUE)
count <- as.matrix(x[2:58390])
rownames(count) <- x$barcodes
count <- t(count)    ## convert title to cell; row name to gene name
whole <-  CreateSeuratObject(counts = count, project = "GvsT",min.cells = 3, min.features = 200)
sub <- read.csv('target.txt', sep = '\t', header = F)    
control <- subset(whole, features = rownames(whole)[!rownames(whole) %in% sub$V1])             
target <- subset(whole, features = rownames(whole)[rownames(whole) %in% sub$V1])  
target <- NormalizeData(target)
target <- FindVariableFeatures(object = target)
control <- NormalizeData(control)
control <- FindVariableFeatures(object = control)
**reference.list <- list(control, target)**
whole.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
```

Hi, 

I am trying above script to do the integration, the ''x must be atomic" error shows, tried the original script according to the manual it will show the error"can not coerce to integer", so I used "**reference.list <- list(control, target)**", can you help to give some guidance, thanks a lot!

Best,

**Comment by dbgoodman** [comment]
I had the same problem when I ran this command:

`integrate.features <- SelectIntegrationFeatures(object.list = scrna.list, nfeatures = 3000, assay=rep('SCT',4))`

I got this error:

![image](https://user-images.githubusercontent.com/515076/103448253-bf428d00-4c4b-11eb-9fc4-2468aa0da3ca.png)

There were no features with underscores, but I did find offending features in a different assay. I figured this would not be an issue since I specified the assay in the arguments to the FindIntegrationAnchors() function, but when I changed the default assay for each object manually:

```
for (i in 1:4) { DefaultAssay(scrna.list[[i]]) <- 'SCT' }
```

Then things worked. I have seen this issue with different assays not overriding the default assay appear in other parts of the code as well.

**Comment by jurtlest** [comment]
Has anyone solved this issue yet ? I've ran into similar situation and checked that there are no feature or gene names that consist of any underscore in my meta.data.. 

`
> anchors <- FindIntegrationAnchors(object.list = data_list, reference = reference.list, reduction = "rpca", dims = 1:50)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=10s
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=18s
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :
  'x' must be atomic
`

**Comment by levinhein** [comment]
Solved this issue by specifying the _reference_ parameter of FindIntegrationAnchors() as the index of the specific datasets in your "_KD.list_" object.

Example:

############################################################################
KD.list <- list(datasetA1, datasetA2, datasetA3, datasetB1, datasetB2, datasetB3) 

KD.anchors <- FindIntegrationAnchors(object.list = KD.list, 
normalization.method = "SCT",
anchor.features = KD.features, 
dims = 1:30, 
**reference = c(0, 3)**, 
reduction = "rpca")

############################################################################

**Comment by moalf2** [comment]
I had this issue too however, it was due to me having different modalities across my two Seurat objects. I had to ensure the DefaultAssay for both was "RNA". That fixed it.

**Comment by Jingheng-ZHANG-1999** [comment]
my ifnb.list2 was a list consisting 25 seurat objects. at first, i ran the following code which give me this error:
```
reference_dataset <- c(ifnb.list2[[1]],ifnb.list2[[2]],ifnb.list2[[3]],
  ifnb.list2[[4]],ifnb.list2[[5]],ifnb.list2[[6]],ifnb.list2[[7]],
  ifnb.list2[[15]],ifnb.list2[[16]],
  ifnb.list2[[18]],ifnb.list2[[19]],ifnb.list2[[20]],ifnb.list2[[21]])
```
Then i tried 
`reference_dataset <- c(1,2,3,4,5,6,7,15,16,18,19,20,21)`
and it worked
