### ISSUE TITLE
Error in "equal_frequency" in FindVariableGenes/FindVariableFeatures

### ISSUE THREAD

**Issue by dhb2128** [satijalab/seurat#1298]
With the `equal_frequency` option, if no genes have a mean of 0 (which is often the case in standard practices that subselect to only include genes expressed in a minimum number of cells), the gene that has the lowest mean will end up in a bin by itself, and then the variance is `NA`. 

This is the result of this line: `data_x_bin <- cut(x = gene.mean, breaks = c(-1,quantile(gene.mean[gene.mean>0],probs=seq(0,1,length.out=num.bin))))`

I can understand why the -1 is there to capture genes with zero mean, but I'm not sure whether it makes the most sense for use cases where all genes have nonnegative means.

**Comment by yuhanH** [comment]
Sorry for the very delayed responses.  Does this issue still exist?
If so, could you provide some reproducible code? Thanks.
