### ISSUE TITLE
Integration vs RunCCA alignment

### ISSUE THREAD

**Issue by arnssino** [satijalab/seurat#1299]
Hallo! I am testing integration in Seurat 3.0 using 2 datasets of the same tissue from different experiments. The results (left) looks quite different from what was produced by "RunCCA" in Seurat 2 (right) using the same datasets. It seems to me that alignment produced "better" result in removing the batch effect. I checked the code for Integration and found nothing wrong. Is it because RunCCA tend to "overfit" the different datasets (so it looks perfectly matched) while integration does not, or because I did something wrong with data integration in Seurat 3.0 leading to the "seemingly bad" result? Thanks a lot in advance!

![alignment](https://user-images.githubusercontent.com/11786671/55288240-110b1300-53e7-11e9-87ac-6e149caa9f81.png)

Here is the code used to perform integration
```R 
dataset1 <- NormalizeData(object = dataset1, verbose = FALSE)
dataset1 <- FindVariableFeatures(object = dataset1, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
dataset2 <- NormalizeData(object = dataset2, verbose = FALSE)
dataset2 <- FindVariableFeatures(object = dataset2, selection.method = "vst", nfeatures = 2000, verbose = FALSE)

merged <- merge(x = dataset1, y = dataset2, do.normalize = FALSE)
merged.list <- SplitObject(object = merged, split.by = "datasets")

reference.list <- merged.list[c("dataset1", "dataset2")]
merged.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:50)
merged.integrated <- IntegrateData(anchorset = merged.anchors, dims = 1:50)

DefaultAssay(object = merged.integrated) <- "integrated"
merged.integrated <- ScaleData(object = merged.integrated, verbose = FALSE)
merged.integrated <- RunPCA(object = merged.integrated, npcs = 50, verbose = FALSE)

merged.integrated <- RunTSNE(object = merged.integrated, reduction = "pca", dims = 1:50)
merged.integrated <- FindNeighbors(object = merged.integrated)
merged.integrated <- FindClusters(object = merged.integrated, resolution = 0.2)
   
p1 <- DimPlot(object = merged.integrated, reduction = "tsne", group.by = "datasets")
p2 <- DimPlot(object = merged.integrated, reduction = "tsne", group.by = "integrated_snn_res.0.2", 
    label = TRUE, repel = TRUE) + NoLegend()
plot_grid(p1, p2)
```

**Comment by timoast** [comment]
Could you send the expression matrix for `dataset1` and `dataset2` so we can reproduce this?

**Comment by mgfield** [comment]
I had the same thing happen with my datasets as well.  Interested to know the answer.

**Comment by satijalab** [comment]
Its impossible to say from the tSNE plots alone. It is certainly possible for Seurat2 (or any method) to overfit the integration procedure when there is minimal conservation, Seurat3 is far more robust to this.

I can only recommend that you explore the genes that are conserved between the two datasets. If Seurat2 is matching biologically relevant populations defined by the same markers, this may be a case where v2 outperforms v3, but I admit we have rarely (if ever) encountered this

**Comment by arnssino** [comment]
I may have found the answer by integrating more than 2 datasets (integrated 7 different datasets). Integration performed amazingly well this time. Seems that a large number of datasets boosted the performance of integration in Seurat v3.0, while RunCCA is still pretty good at aligning 2 datasets.

**Comment by mgfield** [comment]
@arnssino  For your dataset, does the RunCCA alignment that looks really good make sense in terms of clusters and gene expression and actual cell populations?  Or does it seem to be overfitted, and the Seurat v3 makes more sense?

**Comment by arnssino** [comment]
@mgfield I think the RunCCA alignment makes sense. I also noticed that when integrated with other datasets using Seurat v3, these two datasets were aligned pretty well.

**Comment by satijalab** [comment]
This is one advantage of v3, where integration improves with more samples. Glad this is working for you now
