### ISSUE TITLE
Error in FindClusters

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#1300]
I was trying to set k.scale parameter but it returned errors no matter what parameter I chose.

The error message is like this:
Erro in FindClusters(object = .......................
Traceback:

**Comment by andrewwbutler** [comment]
Which version of Seurat are you using? The `k.scale` parameter was removed a while back.

**Comment by brianpenghe** [comment]
I was using Seurat_2.3.1
Can I ask why was that parameter removed?
![bitmoji](https://render.bitstrips.com/v2/cpanel/402ccdad-3037-4e74-a13b-ddd639b1b29d-4c0edd69-002f-4ee5-9171-2ca626e1370d-v1.png?transparent=1&palette=1&width=246)

**Comment by andrewwbutler** [comment]
That parameter was removed in the 2.3 release. We made some efficiency improvements to how the SNN graph was constructed that removed the need for that parameter. `k.scale` essentially controlled how much of the jaccard similarity matrix (for the SNN) was computed. In that update, we improved how we were doing that calculation such that it was no longer problematic to compute the entire thing.
