### ISSUE TITLE
Analysis of primary versus secondary tumors

### ISSUE THREAD

**Issue by ts3139** [satijalab/seurat#1301]
Hi all,

A quick question. I have two datasets of tumor sample. One obtained from primary tumor, and one from a secondary recurrence of the primary tumor. I would like to essentially analyze the data together in an aggregate form to see how the primary and the secondary cells cluster together. 

What kind of analysis do you recommend? Merged PCA or CCA analysis? Thanks!

**Comment by andrewwbutler** [comment]
Hi,

If your goal is to identify common cell types across the two datasets, I would recommend the new integration workflow in Seurat v3. You can find an example [here](https://satijalab.org/seurat/pancreas_integration_label_transfer.html).
