### ISSUE TITLE
FindIntegrationAnchors neighbors

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#1302]
The `FindIntegrationAnchors()` has a few different neighbors-related parameters:

- `k.anchor`: How many neighbors (k) to use when picking anchors (5)
- `k.filter`: How many neighbors (k) to use when filtering anchors (200)
- `k.score`: How many neighbors (k) to use when scoring anchors (30)

For smaller datasets, those numbers become more relevant. For example, if you use the default 200 neighbors for filtering, you will get an error if you have fewer than 200 cells in any of the datasets (as mentioned in a previous issue: https://github.com/satijalab/seurat/issues/997). If you have 201 cells, you will avoid the error, but it probably doesn't make much sense to use 200 neighbors for anything.

Is there some additional documentation or guidance available? For example, how much should you reduce those numbers if you only have 50 cells per dataset? Obviously every dataset has unique considerations, but does it even make sense to try anything at that point?

**Comment by satijalab** [comment]
I agree that for very small datasets this becomes a problem. however, for very small datasets - the vast majority of methods in Seurat (or other packages that use nearest-neighbor or graph-based approaches -which assume that k << # of cells) will struggly to effectively process. you can certainly reduce the neighbor parameters, but unfortunately we can't provide guidance in this regime.
