### ISSUE TITLE
Meaning of data value after Scaling

### ISSUE THREAD

**Issue by NTNguyen13** [satijalab/seurat#1303]
Hi, I have two sample, and I want to compare their data by using the method described in this article: https://www.nature.com/articles/s41467-017-01015-3

In short, I will calculate perform the statistical test between the gene expression distribution of 2 samples to see whether there's significant changes or not. However, the data after ScaleData has some minus, and integer value. For example, I got average expression of gene STAT1 in sample A is 0.05, in sample B is -0.005, their values are 10 fold different, but they are so close to 0, so do it make sense to the average expression in sample A is 10 times larger than in sample B?

Thank you

**Comment by timoast** [comment]
The scaled data are obtained by subtracting the mean and dividing by the standard deviation (scale and center). We typically use normalized data to look at differential expression, not scaled data. In the case you gave, the values in sample A are 10-fold higher than sample B, but whether this difference is considered statistically significant is a different question that requires information about the distribution.
