### ISSUE TITLE
CombineIdent in SuratV3

### ISSUE THREAD

**Issue by kunUCSD** [satijalab/seurat#1304]
Hi,
In V2, there is the CombineIdent function that can be used to combine two attributes, I wander if V3 also keeps it. I tried CombineIdent, but get the error: could not find function "CombineIdent".
My Seurat version: [1] ‘3.0.0.9000’
Thanks,
Best, Kun

**Comment by mojaveazure** [comment]
Hi Kun,

We don't have a replacement for `CombineIdent`, but it's functionality can be easily duplicated in Seurat v3:

```R
Idents(object = object) <- paste(Idents(object = object), object$orig.ident, sep = '_')
```

With this, you can swap any combination the current cell identities, entries in object meta data, or vectors you have in memory, making it far more flexible than the old `CombineIdent`
