### ISSUE TITLE
Can`t remove the effect of cell cycle

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1305]
Hi : 
    I want to regress out the effect of cell cycle in my lung tissue sample. I perform the steps follow by "https://satijalab.org/seurat/cell_cycle_vignette.html" . After regress out the effect of cell cycle, I can still view a cluster high express cell cycle genes like "MKI67","TOP2A","PCNA". So I think the cell cycle effects doesn`t regress out in my sample. My question is why the method perform not as good as in my sample ? It that due to low percentage cell cycle genes in my sample ? This situation , how to regress out the cell cycle effects and not get a cluster full of cell cycle cells ?

Best

**Comment by satijalab** [comment]
Would you mind pasting the code you are using?

**Comment by SeadonXing** [comment]
Hi :
    I use Seurat version 2.3.4 . After run the step of 'Detection of variable genes across the single cells" by FindVariableGenes. I run the code that want to regress out cell cycle effect as below : 
`
# Cell-Cycle Scoring and Regression
data(cc.genes)
s.genes <- cc.genes$"s.genes"
g2m.genes <- cc.genes$"g2m.genes"
scObject <- CellCycleScoring(object = scObject, s.genes = s.genes, g2m.genes = g2m.genes, 
	set.ident = FALSE)
scObject <- ScaleData(object = scObject, vars.to.regress = c("nUMI", "percent.mito", "S.Score", "G2M.Score"),
	do.par = TRUE, num.cores = 8);

# Perform linear dimensional reduction
scObject <- RunPCA(object = scObject, pc.genes = scObject@var.genes, do.print = TRUE, pcs.print = 1:20, 
	genes.print = 10, pcs.compute = 30, seed.use = 11)
# Cluster the cells
scObject <- FindClusters(object = scObject, reduction.type = "pca", dims.use = c(1:20), 
	resolution = 0.6, print.output = 0, save.SNN = TRUE, force.recalc = TRUE, random.seed = 11);
PrintFindClustersParams(object = scObject, resolution=0.6)

# Run Non-linear dimensional reduction (tSNE)
scObject <- RunTSNE(object = scObject, dims.use = c(1:20), do.fast = TRUE, seed.use = 11)
TSNEPlot(object = scObject, do.label=TRUE, colors.use=brewer33);
`
    I am really in hurry want to know that why this method cant regress cell cycle effect in my data.

Hope reply
Best

**Comment by SeadonXing** [comment]
Hi ：
    I send a email with title "Attached files for Seurat question "Can`t remove the effect of cell cycle #1305 "" to "seuratpackage@gmail.com" , please check and get more information from the attached files in emails. 
    Or if you still need something please let me know. 

Sincere thanks
Best

**Comment by penglbio** [comment]
I  also have same  problem. I have three samples. I need integrate the data. Before I do the integration, I regress out the cell cycle effect. But After I integrated the data, I run DimPlot() command group_by phase, I also find the cell circle phase cells are clustered separately.

**Comment by satijalab** [comment]
One option is to try cell cycle regression after performing IntegrateData (in the ScaleData call that comes immediately afterwards). That should help

**Comment by SeadonXing** [comment]
Hi satijalab :
     I try the method you methioned and still useless.  I can still find a cluster full of many type of cells, while they all express cell cycle genes. Any method to regress out the cell cycle effect ?

Best

**Comment by diala-ar** [comment]
I am experiencing the same problem, anybody was able to overcome it?

Thanks

**Comment by plijnzaad** [comment]
In my experience  regressing out doesn't works, better to just remove all cell cycle genes from the variable features. Tirossh et al. cell cycle genes are built-in to Seurat and are available in list `cc.genes` after doing `data(cc.genes)`
