### ISSUE TITLE
Viewing Source Code

### ISSUE THREAD

**Issue by Fore7630** [satijalab/seurat#131]
Hi,

I just wanted to quickly ask how I can see the source code for your LogNorm function? I have gotten to the point where R is telling me that you are calling to a C function inside Seurat: `.Call("Seurat_LogNorm", PACKAGE = "Seurat", data, scale_factor, 
        display_progress)`
How would I view the code for the C function you are calling to?

Thanks,
Corey

**Comment by leonfodoulian** [comment]
Hello Corey,

You can find the code at [lines 111 to 122 in data_manipulation.cpp](https://github.com/satijalab/seurat/blob/master/src/data_manipulation.cpp#L111-L122).

Best,
Leon
