### ISSUE TITLE
FeaturePlot in Seurat v3.0, how to select cells for reclustering 

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1310]
I want to select a cluster of cells by hovering over them in the tSNE plot. and then I want to re-run the clustering on those to see if they cluster further into subtypes. I also want to e.g. select a group by hovering over and then extract their cell names.

I've been trying to follow this example (https://satijalab.org/seurat/visualization_vignette.html#interactive-plotting-features) for doing that however the code is not working for me, possibly due to it being written for the earlier version. 

The example code I was following
```
pbmc <- RenameIdent(object = pbmc, old.ident.name = "Dendritic cells", new.ident.name = "CD14+ Monocytes")
select.cells <- TSNEPlot(object = pbmc, do.identify = TRUE)
head(select.cells)
pbmc <- SetIdent(object = pbmc, cells.use = select.cells, ident.use = "NewCells")

# Now, we find markers that are specific to the new cells, and find clear DC
# markers
newcells.markers <- FindMarkers(object = pbmc, ident.1 = "NewCells", ident.2 = "CD14+ Monocytes", 
    min.diff.pct = 0.3, only.pos = TRUE)
head(x = newcells.markers)
```
The way I ran it on my data
`select.cells <- RunTSNE(object=decoder,do.identify=TRUE)`
No hovering option appeared for me in the output.

Can you please help me figure out a solution to this? 

Thank you!

**Comment by mojaveazure** [comment]
The `do.identify` parameter of various plotting functions has been replaced by `FeatureLocator`, as indicated in the documentation of `DimPlot` in Seurat v3; using `FeatureLocator` is done as such

```R
plot <- DimPlot(object = pbmc, reduction = 'tsne')
select.cells <- FeatureLocator(plot = plot)
```
