### ISSUE TITLE
Get genes correlated with module score

### ISSUE THREAD

**Issue by sarahrosental** [satijalab/seurat#1311]
Hi,

I added a module score with the function AddModuleScore() in my existing seurat object. I got a Seurat object with my module scores added to object@meta.data.
Now I would like to get a list of genes with are correlated with my module score.
Thanks for your help.

**Comment by SeadonXing** [comment]
Hi ：
    I also perform a similiar analysis recently. I use the "GenePlot" function and input my interesting genes one by one. I also want to find a method can perform all the gene list at one time. BTW, but I find that the results of co-expression of gene to gene or module score to genes are poor in 10X droplet single cell data. Most of the genes  correlation are  nearly to 0. While only are few genes show high correlation are housekeeping genes, like RPL/RLS ,MHC-I/II . For that ,are there any better methods to use for analysising gene /gene or module score / gene  express similiarity ?

Best

**Comment by SeadonXing** [comment]
You can modify the code here "https://github.com/satijalab/seurat/issues/519"  to

matrix<-subset0_STIM@data
matrix_mod<-as.matrix(matrix)
gene<-as.numeric(object@meta.data$"module_score")
correlations<-apply(matrix_mod,1,function(x){cor(gene,x)})

The "module_score" is the colum name in meta.data after you run AddModuleScore()

Hope help you.

**Comment by sarahrosental** [comment]
Hi,

I use this code for my correlations of my "gene of interest". But for my "module score" it is not working. 

Error in cor(gene, x) : incompatible dimensions. 

I guess, my matrix does not provide @meta.data dimension.
Any suggestions?
Thanks

**Comment by SeadonXing** [comment]
You have to make sure that your "gene" and "x" are in the same length . This error may induced by different dimension you run function "cor"

**Comment by sarahrosental** [comment]
Hi,

Thanks. It working for me.
