### ISSUE TITLE
[Seurat 2.3] Marker with p_val_adj = 1, p_val = 0.96?

### ISSUE THREAD

**Issue by kmuench** [satijalab/seurat#1312]
Hello,

I ran the following command to find genes that are differentially expressed in cluster 1 between two of my conditions: 

FindMarkers(data.combined, ident.1 = 'Group1_cluster1', ident.2 = 'Group2_cluster1', print.bar = TRUE)

I notice that in some comparisons of this type (e.g. clusters 1,12,23), there are genes included in the output list include both the low p-values I expect (e.g. p_val 4.872189e-11, p_val_adj 9.470074e-07), but also very large p_val (9.4e-01) and very large p_val_adj (1.000). When I do this comparison with other clusters (e.g. 4, 8, 12), all of the genes fall within a p_val < 0.05.

I'm curious:
1. How are the thresholds chosen for what genes to display?
2. Should I believe that all markers called in this list are truly DE, or should I disregard all genes called markers with p_val_adj > 0.05?
3. In the ?FindMarkers page, I'm intrigued by this sentence: "as Aaron Lun has pointed out, p-values 
should be interpreted cautiously, as the genes used for clustering are the same genes tested for differential expression." I hadn't heard of this before and I'd like to learn more, but I'm having trouble locating where or what Aaron Lun said. Is this referring to a paper? Another section of the Seurat manual? Or something else?

Thank you for creating such a wonderful resource.

**Comment by andrewwbutler** [comment]
Hi,

1. The thresholds for what genes are tested can be seen in the documentation (`?FindMarkers`). Specifically, take a look at `logfc.threshold`, `min.pct`, `min.diff.pct`. 
2. (3) The p-values that come out of these DE tests should be approached cautiously. The statements in the documentation were based on personal correspondences that I'm not sure were ever written up anywhere but you can check out this [paper here](https://www.biorxiv.org/content/10.1101/463265v2) which makes the same point well.
