### ISSUE TITLE
Differential expression by orig.ident

### ISSUE THREAD

**Issue by L30P30** [satijalab/seurat#1314]
I would like to test for differential expression between two groups of samples (3v3) as defined by their orig.ident. Could anyone help with this? I am using Seurat 3.0.

Thanks a lot

**Comment by andrewwbutler** [comment]
Hi,

If you want to perform a differential expression test based on `orig.ident`, you should switch the cell identities to `orig.ident` and then run `FindMarkers`.

```R
Idents(object = object) <- "orig.ident"
FindMarkers(object = object, ...)
```

**Comment by satijalab** [comment]
There is also a group.by argument in FindMarkers that you can use instead:

```R
FindMarkers(object = object, group.by = 'orig.ident', ...)
```

**Comment by L30P30** [comment]
Fantastic, thank you both!
