### ISSUE TITLE
Would be good to have an early error check on meta.data provided to CreateSeuratObject() 

### ISSUE THREAD

**Issue by NathanSkene** [satijalab/seurat#1316]
I just had the error

stop("Metadata provided doesn't match the cells in this object")

Because I'd passed a matrix instead of a dataframe. Took ~5mins after calling the function before I got the error. Would be good if error checking like this was done as first thing the function does.

Thanks!

**Comment by mojaveazure** [comment]
Hi Nathan,

Sorry for the delay; this should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
