### ISSUE TITLE
Assigning sample ID column in metadata, based on the name of the cells

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#1318]
Hello, I'm pretty new at these things, so please don't mind if I ask a naive question. 
I want to assign a column with the sample ID to the metadata, based on the name of the cells. The cell names end with a specific four-digit symbol that represents the sample from which the cells originate. Based on these 4-digit symbols I would like to assign another column with sample ID. For example, for all cells ending with e.g. 1111 to assign "sample1", for cells ending with 2222 to assign "Sample2", etc.

Thanks a lot for your help
Amel

**Comment by andrewwbutler** [comment]
Hi Amel,

Assuming it's only the last digit of the 4-digit symbol that matters (as in your examples), you can do something like

```R
object$sampleID <- sapply(X = colnames(object), FUN = function(x) {
  paste0("Sample", substr(x, nchar(x), nchar(x)))
})
```

**Comment by AmelZulji** [comment]
Hi Andrew, 

Thanks a lot for your response, I tried but I couldn't get desired results. 
I think that I didn't explained it well. 
So here is the code with which im doing it but I think there should be function to make it easier.
`
sample.info <- data.frame(cell.names = sc@cell.names)
sample.info$sampleID = 'Unknown'
sample.info$sampleID[grep('CO40', sc@cell.names)] <- 'Sample 1'
sample.info$sampleID[grep('PDCO40', sc@cell.names)] <- 'Sample 2'
sample.info$sampleID[grep('CO34', sc@cell.names)] <- 'Sample 3'
sample.info$sampleID[grep('MS76', sc@cell.names)] <- 'Sample 4'
sample.info$sampleID[grep('MS80', sc@cell.names)] <- 'Sample 5'
sample.info$sampleID[grep('MS99', sc@cell.names)] <- 'Sample 6'
row.names(sample.info) <- sample.info$cell.names
sample.info$cell.names <- as.character(sample.info$cell.names)
sc<-AddMetaData(object = sc, metadata = sample.info, col.name = "SampleID")
p3<-TSNEPlot(object = sc, group.by="sampleID")`

Do you maybe have an idea? 

Once again thank you.

**Comment by satijalab** [comment]
Your code is absolutely valid, but unfortunately I think we would struggle to include a Seurat function that could make this faster. As you note, users are able to modify object meta data using standard R functions as well
