### ISSUE TITLE
Install of Seurat v3.0 fails due to missing loomR binary?

### ISSUE THREAD

**Issue by psavas** [satijalab/seurat#1323]
Hi, thanks very much for Seurat, it's great software.
I'm keen to use version 3.0, but have had problems installing using the following command:

`devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')`

On both Windows 7 and Mac OS (Mojave), I get the following error:
> Error: (converted from warning) unable to access index for repository https://mojaveazure.github.io/loomR/bin/macosx/el-capitan/contrib/3.5: cannot open URL 'https://mojaveazure.github.io/loomR/bin/macosx/el-capitan/contrib/3.5/PACKAGES'`

It installed fine on Ubuntu however. I have tried (to no avail):
- installing the pre-requisites to run loomR as detailed at https://github.com/mojaveazure/loomR#dependencies, and:
- installing loomR after the above prior to trying to install Seurat
- following the instructions here: 

The URL listed in the error does not actually seem to exist.

Thank you.

**Comment by cakirb** [comment]
https://github.com/satijalab/seurat/issues/914#issuecomment-479967597

**Comment by Dragonmasterx87** [comment]
#914 (comment)[https://github.com/satijalab/seurat/issues/914#issuecomment-480409323](url)

**Comment by mojaveazure** [comment]
[As mentioned previously](https://github.com/satijalab/seurat/issues/914#issuecomment-478633110), this is an issue with `devtools`/`remotes`, as it should ignore suggested packages (like loomR is), but is instead trying to download and install it.

**Comment by psavas** [comment]
Thanks, sorry for the duplicate issue, I didn't search the closed issues. The most useful description of what to do was here:

[https://github.com/satijalab/seurat/issues/914#issuecomment-480260819](url)
