### ISSUE TITLE
Batch correction, RunCCA-AlignSubspace, IntegrateData

### ISSUE THREAD

**Issue by pawelsm** [satijalab/seurat#1324]
Hi,

I have 2 10xGen replicate runs which I want to integrate so I did merging by RunCCA followed by SubsetData and AlignSubspace (seurat v2).  Projection plots shows improved alignment.  
Then I saw the question about accessing corrected data and that seurat do not output corrected data
https://github.com/satijalab/seurat/issues/283#issuecomment-360892489

and in my eyes contradictory post 
https://github.com/satijalab/seurat/issues/387

I checked my objects@scale.data which are obviously different if I do merge or RunCCA.

If AlignSubspace is not changing @scale.data which is then used by FindAllMarkers - than it means that selection of relevant genes could be driven by batch effects.

What would be the correct way to select genes not based on batch but on biological effects?
Should I do ScaleData or ComBat with orig.ident or use CCA embeddings and loadings data to re-create cell x gene value?

thanks for your work,

P.

**Comment by satijalab** [comment]
The posts are not contradictory, but reference different versions of Seurat. We suggest using v3, and provide extensive vignettes and documentation on the website.
