### ISSUE TITLE
node assessment in seurat v3

### ISSUE THREAD

**Issue by leonvgurp** [satijalab/seurat#1326]
I am trying to assess my clustering in Seurat 3. In version 2, I used the BuildClusteringTree, AssessNodes and MergeNodes functions for this. I cannot find out how to do this in Seurat 3:

1) BuildClusteringTree is still present in Seurat 3, although I am not sure where it stores its information?

2) AssessNodes and MergeNodes functions are no longer available. I cannot find an alternative for it in the command list overview between 2.X and 3.X.

Is there an alternative to do this? Any help would be appreciated!

**Comment by MediciPrime** [comment]
I am having the same problem as well.  Does anyone know a possible workaround for this issue?

**Comment by mojaveazure** [comment]
As stated in the [documentation for `BuildClusterTree`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.0/topics/BuildClusterTree):

> A Seurat object where the cluster tree can be accessed with [`Tool`](https://www.rdocumentation.org/link/Tool?package=Seurat&version=3.0.0)

`BuildClusterTree` stores the tree in the `tools` slot of of the object, accessible with the `Tool` accessor. To see a list of all tools that have stored data in the `tools` slot, use `Tool(object = object)`; to get the value of a specific tool, use `Tool(object = object, slot = "NameOfFunction")` (eg. `Tool(object = object, slot = 'BuildClusterTree')`)

We currently do not have alternatives for `AssessNodes` and `MergeNodes`; we are working on bringing them back, but do not currently have a timeline for their restoration.

**Comment by Drosophilist** [comment]
Any update on this matter? @satijalab 
I'm highly interested in merging back clusters that have biologically meaningless splits. Any alternative methods one could use to do this? Any tips would be extremely appreciated.
All the best

**Comment by timoast** [comment]
I'd suggest using [clustree](https://lazappi.github.io/clustree/) to find an optimal clustering resolution, and performing DE between clusters to assess whether you think the splits are meaningful.
