### ISSUE TITLE
failed to install Seurat

### ISSUE THREAD

**Issue by xiwa2006** [satijalab/seurat#1327]
I tried install.packages("Seurat") and got below errors.

installing to /home/xwang/R/x86_64-pc-linux-gnu-library/3.4/hdf5r/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘hdf5r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/xwang/R/x86_64-pc-linux-gnu-library/3.4/hdf5r/libs/hdf5r.so':
  libhdf5_hl.so.100: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/xwang/R/x86_64-pc-linux-gnu-library/3.4/hdf5r’
ERROR: dependencies ‘igraph’, ‘png’, ‘hdf5r’ are not available for package ‘Seurat’
* removing ‘/home/xwang/R/x86_64-pc-linux-gnu-library/3.4/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpyOUq7X/downloaded_packages’
Warning messages:
1: In install.packages("Seurat") :
  installation of package ‘igraph’ had non-zero exit status
2: In install.packages("Seurat") :
  installation of package ‘png’ had non-zero exit status
3: In install.packages("Seurat") :
  installation of package ‘hdf5r’ had non-zero exit status
4: In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status

My environment is 
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /opt/sw/R/3.4.4/lib/R/lib/libRblas.so
LAPACK: /opt/sw/R/3.4.4/lib/R/lib/libRlapack.so

**Comment by igordot** [comment]
```
ERROR: dependencies ‘igraph’, ‘png’, ‘hdf5r’ are not available for package ‘Seurat’
```
Did you check if you can load those packages?

**Comment by chatterjee89** [comment]
Install those dependencies mentioned in the above comment separately, and then try installing Seurat.
That worked for me!
