### ISSUE TITLE
Differential expression

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#133]
Hello Seurat Team,

Thanks for the nice upgrades in the Seurat 2 package!  I am a bit lost as to how exactly differential gene expression (FindAllMarkers) analysis is carried out in Seurat.  Is there a place where this is described in detail?  If not, it will be great if somebody could throw some light on this, at least in some detail.  I would really like to know what's the basic concept.  For example, in finding marker genes of one cluster compared to all other cells, is it doing a pairwise comparison of all possible gene pairs above the specified thresholds, and comparing the average expressions of the genes in the chosen cluster and the other cells?

Thanks a lot!

**Comment by satijalab** [comment]
FindAllMarkers compares each cluster against all other cells in the dataset. It recomputes genes which pass the given thresholds separately for each cluster. I apologize that I don't quite understand your question in full, but you can also see all the code on this GitHub repository.
