### ISSUE TITLE
How can I clean up my tSNE/UMAP plot? OR is there a way to regress out the expression of a selected set of target genes?

### ISSUE THREAD

**Issue by chatterjee89** [satijalab/seurat#1333]
I understand that these might be two different questions...

I'm running a CCA analysis between a control group of ~12,000 cells and an over-expression genotype of ~10,000 cells. My final clusters, using every algorithm and settings (dimensions = 1:75, min_dist=  0.001) for UMAP-based reduction give me an extremely crowded plot with not-so-distinct clusters. It does make biological sense overall, correlated with what changes in Control vs Sample I'm expecting, but I want to clean it up a bit for the sake of visual clarity. Note, there are over 30 distinct cell types for the control itself - this is from a whole tissue sample set and choosing comparable number of dimensions for PCA really does separate out the different cell types.

One thing I wanted to try (and it would also be a lot more sensible to my downstream questions) - since I'm looking at transcriptional changes associated with a change in fate, some cell type clusters show transcriptional changes (because the target gene profile is up-regulated due to the over-expression genotype) without showing a fate change, while some clusters show both. I want to tap into that "both" aspect, where I want to look into the secondary effects that bring about the fate changes in the cell type clusters of interest. I was wondering if there's a way to regress out the expression of the canonical known target genes? (can I use the AddModuleScore function using a modified gene list for this?). Clearly, I don't know what to expect, and this is purely hypothetical at this point.

But also, will that clear up my crowding issue on the tSNE/UMAP plots?

**Comment by chatterjee89** [comment]
A little follow-up to why I think this might help clean up the plot a bit: After running CCA over 75 dimensions, the clusters that don't undergo fate changes but have a pretty large difference in the transcriptome - due to the large array of target genes that are misregulated - are slightly off-set from the corresponding control cluster. This leads to significant overlapping with their neighboring clusters.

Am I absolutely nuts to be thinking this way? Sorry, I'm more of a biologist than a computational person.

**Comment by Dragonmasterx87** [comment]
Hi @chatterjee89 , 

You can regress out the effect of target genes similar to what Seurat uses for [cell cycle gene regression].(https://satijalab.org/seurat/v3.0/cell_cycle_vignette.html) However in my opinion, initially I would perform a un-supervised clustering to look at overall cluster distribution. Perform your analysis on the CCA output, if you want to be stringent just decrease your variable genes. This will map cells onto similar clusters.

Also if you are interested in a particular cluster, subset that cluster and just look at it independently. But in the context of 'the map of the world' using a few variable genes to generate a tSNE will always (to a greater degree) extrapolate true biological effect. Being over ambitious in supervised clustering can mask transitional phenotypes that may be brushed of as a 'batch effect'. After all, the transcriptome of a cell is a transcriptome of a cell.
