### ISSUE TITLE
human cell altas data

### ISSUE THREAD

**Issue by notimenocall** [satijalab/seurat#1336]
hi all,
I am trying to analyze the human cell altas bone marrow and cord blood data. I used the 'Read10X_h5' function of Seurat to load the .h5 files. However, when tried to CreateSeuratObject, there's an error

> Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features) : Non-unique features (rownames) present in the input matrix

When I tried to remove the duplicate with 

`hca_bm <- CreateSeuratObject(counts = hca_bm.counts[!which(duplicated(row.names(hca_bm.counts))),], project = "hca_bm", min.cells = 5, min.features  =200)`

The followed errors appear:
`Error in `[[<-`(`*tmp*`, "orig.ident", value = c(1L, 1L, 1L, 1L, 1L, 1L, : Cannot add more or fewer cell meta.data information without values being named with cell names`

Please help! Thanks!!

**Comment by ddiez** [comment]
I have tried your code in some other dataset and cannot reproduce the error, but my dataset does not have duplicated names, so can't comment on those specifics. I have noticed however that you may not be using `!` and `which` in your code in the way you probably want. I may have completely misunderstood what you want to do and if so I apologize. But if not then I hope this is useful:

Basically if you want to remove rows with duplicated names this should be enough:

```
!  duplicated(rownames(hca_bm.counts))
```

`duplicated()` gives you a logical vector of size `nrow(hca_bm.counts)` and you are just keeping those not duplicated. `which()` on the other hand returns a vector of indexes. So you could do this and should give you the same result:

```
which(!  duplicated(rownames(hca_bm.counts)))
```

But you are doing this instead:

```
!  which(duplicated(rownames(hca_bm.counts)))
```

Take a look a what happens in this small example:

```
x <- 1:10

x > 5 # logical vector of size 10
! x > 5 # logical vector of size 10
which(x > 5) # numeric index of size 5
which(! x > 5) # numeric index of size 5
! which(x > 5) # logical vector of size 5: will be recycled!
```

**Comment by notimenocall** [comment]
Hi Diego,
Thanks a lot for your comments. You are right about the syntax. It worked when I did it the way you suggested.
