### ISSUE TITLE
Unable to run JackStraw: no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#1337]
Updated Seurat today and ran into this issue:
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')

```
TestObj <- RunPCA(object = TestObj, features = VariableFeatures(object = TestObj), verbose = FALSE)
TestObj <- JackStraw(object = TestObj, num.replicate = 100)
|                                                  | 0 % ~calculating  
Error in Loadings(temp.object)[rand.genes, r1.use:r2.use] : 
  no 'dimnames' attribute for array
```

**Comment by jeremycfd** [comment]
I'm now wondering if something happened with my environment, as when I attempted to install earlier commits the problem persisted, e.g. devtools::install_github(repo = 'satijalab/seurat', ref = '42aa5c88de0f492ad4c55bea7bd41598018002f1')
Hrm...

**Comment by jeremycfd** [comment]
I was able to resolve this by installing commit 0e070c1878f5301421bd0dae0c6cde32c29da1f1 with   devtools::install_github(repo = 'satijalab/seurat', ref = '0e070c1878f5301421bd0dae0c6cde32c29da1f1', force = TRUE)

I tested every commit after that and they all produced the same error.

**Comment by panxiaoguang** [comment]
I have the same problems ,it sames that the seurat have a 

> Dimnames

**Comment by mojaveazure** [comment]
Hi @jeremycfd and @panxiaoguang,

Sorry for that, this should now be fixed. Could you give it a whirl and let me know if it's still causing problems?

**Comment by fly4all** [comment]
I'm having the same problem. I tried installing commit but it still gives me the same error:
```
Error in Loadings(temp.object)[rand.genes, r1.use:r2.use] : 
  no 'dimnames' attribute for array
```

**Comment by Weiwen1992** [comment]
Same problem here.
Error in Loadings(temp.object)[rand.genes, r1.use:r2.use] : 
  no 'dimnames' attribute for array.

**Comment by fly4all** [comment]
It worked for me after installing commit and restarting R!

**Comment by ChickenWangSY** [comment]
the same error in JackStraw.

**Comment by ChickenWangSY** [comment]
> the same error in JackStraw.

ok， installing the Seurat 3.0 again worked for this issue.   
Much thanks for your jobs
