### ISSUE TITLE
UMAP post integration illustrates "outlier" cells that were not previously identified 

### ISSUE THREAD

**Issue by jaxlilli** [satijalab/seurat#1338]
I am using Seurat_3.0.9.9000 to analyze Chromium 10x (2,957 cells) and Fluidgm C1 (158 cells) data. I have analyzed both captures independently and now I am using the new FindIntegrationAnchors() and IntegrateData() to analyze them together following the provided tutorial. The technologies were implemented on the same somewhat homogeneous, flow sorted population. I have performed quality control on both data sets separately prior to integration. After integration I use tSNE and UMAP to visualize the data. tSNE resembles the tSNE generated when working with the captures independently but UMAP separates out 9 cells (4-10x and 5-C1) very far (UMAP_2 < -60) away from the remainder rest of the cells (UMAP_2 around 0), image attached. When visualizing the data with tSNE, these cells are more seamlessly integrated. I have extracted the UMAP 1 and 2 embeddings, identified the "problematic" cells in UMAP space, but I cannot find anything biological to support the distance introduced during UMAP reduction. I have looked at nFeature_RNA, nCount_RNA, percent.ribo, percent.mito.  I was just curious if anyone else has observed this with UMAP and if there are any recommendations for figuring out what is different about these cells either technically or biologically.  The same #PCs are being given to both UMAP and tSNE.  Any insights would be helpful, thanks! 
[tSNE_UMAP.pdf](https://github.com/satijalab/seurat/files/3055827/tSNE_UMAP.pdf)

**Comment by andrewwbutler** [comment]
Hi,

One way to investigate what might be driving those differences is using the `CellSelector` function in the latest Seurat v3 release. You can see an example in the "Interactive plotting features" section of the [visualization vignette](https://satijalab.org/seurat/v3.0/visualization_vignette.html). You could then run a differential expression test between the group of cells you select and the rest to see what might be different.
