### ISSUE TITLE
call to WhichCells() within FilterCells() produces error: Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  :    length of 'dimnames' [2] not equal to array extent

### ISSUE THREAD

**Issue by mkarikom** [satijalab/seurat#134]
Performing the new pre-processing workflow on an old dataset produced this error, which did not happen in the old workflow.  I get an error when WhichCells() is called within the following loop (line 770 in Preprocessing.R): 

    for (i in seq(nrow(data.subsets))) {
    cells.use <- WhichCells(object = object, cells.use = cells.use, 
      subset.name = data.subsets[i, 1], accept.low = data.subsets[i, 
        2], accept.high = data.subsets[i, 3])
    }    

I examined parameters "data.subsets" and "cells.use" in an attempt to trace the problem, but both seem to have normal values:

    Browse[3]> data.subsets
    subset.names low.thresholds high.thresholds
    1        nGene            200         2500.00
    2 percent.mito           -Inf            0.05

    Browse[3]> cells.use[1:5]
    [1] "E3.5_P8_Cell2_embryo1_single"  "E3.5_P8_Cell3_embryo2_single" 
    [3] "E3.5_P8_Cell5_embryo3_single"  "E3.5_P8_Cell7_embryo4_single" 
    [5] "E3.5_P8_Cell22_embryo5_single"

    Browse[3]> object
    An object of class seurat in project Single_Cell 
    17932 genes across 721 samples.

**Comment by mkarikom** [comment]
Tracing into the actual call to WhichCells() reveals the problem: none of the cells have alignment of less than 4009 genes, which is above the maximum value of 2500, thus the "pass.inds" value ends up being empty (line 687 in interaction.R):

    subset.data <- data.use[, subset.name, drop = F]
    if (!is.null(x = accept.value)) {
      pass.inds <- which(x = subset.data == accept.value)
    }
    else {
      pass.inds <- which(x = (subset.data > accept.low) & 
        (subset.data < accept.high))
    }
    cells.use <- rownames(x = data.use)[pass.inds]
    }
    return(cells.use)

Checking parameters:

    Browse[4]> accept.low
    [1] 200
    Browse[4]> accept.high
    [1] 2500
    Browse[4]> head(subset.data)
                              nGene
    E3.5_P8_Cell2_embryo1_single   5482
    E3.5_P8_Cell3_embryo2_single   6382
    E3.5_P8_Cell5_embryo3_single   5850
    E3.5_P8_Cell7_embryo4_single   4394
    E3.5_P8_Cell22_embryo5_single  5248
    E3.5_P8_Cell25_embryo1_double  4756

    Browse[4]> max(subset.data[,1])
    [1] 10575
    Browse[4]> min(subset.data[,1])
    [1] 4009

    Browse[4]> pass.inds
    integer(0)

    Browse[4]> cells.use
    character(0)

Now the error can be regenerated by plugging in the resulting values while tracing through FilterCells():

    Browse[3]> cells.use <- character(0)
    Browse[3]> SubsetData(object, cells.use)
    An object of class seurat in project Single_Cell 
      17932 genes across 0 samples.
    Browse[3]> object<-SubsetData(object, cells.use)
    Browse[3]> return(object)
    Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
      length of 'dimnames' [2] not equal to array extent

**Comment by andrewwbutler** [comment]
Thanks for bringing this up. We'll put in some better error checking for this case in the future. I'm not sure how you were filtering in the older version but the filters that you choose though should be specific to your dataset. In this case it doesn't really make sense to put a high threshold at 2500 for nGene.
