### ISSUE TITLE
Permutation when using FindAllMarkers()?

### ISSUE THREAD

**Issue by computingenomics** [satijalab/seurat#1340]
When using FindAllMarkers(), each cluster is compared to all remaining ones. As the sample sizes of the two comparing groups (one cluster vs. all others) could be very unequal, especially for the smallest cluster vs. all others, I was wondering if permutation is needed, or if the unequal sample size issue has been taken care of in this function. Thanks for any helpful information.

**Comment by satijalab** [comment]
We do not perform any correct based on uneven cluster sizes. You can do so if you wish, prior to running FindAllMarkers, you can subset the object using the subset command and the downsample argument

**Comment by computingenomics** [comment]
Dear satijalab,

Thanks very much for your reply.

Just a minor follow up question: I noticed that there are multiple subset functions: SubsetData(), SubsetData.Assay(), SubsetData.Seurat(), etc. Do they do the same thing? I was not able to tell the differences, if any,  but was wondering why there are several of them. Thanks for your continuous attention to this question.

**Comment by andrewwbutler** [comment]
Hi,

This gets a bit technical but any function where you see `FUNCTIONNAME.Seurat/Assay/default` just means that that particular function has been defined for more than one object class. You can read more about how R handles method dispatch [here](https://adv-r.hadley.nz/s3.html#method-dispatch). From an end user perspective you should generally just call the main function without the part after the `.`  and R will figure out which one to use. 

In this specific case, there is a duplication of functionality between `SubsetData` and `subset`. I would recommend using `subset` going forward.

**Comment by computingenomics** [comment]
Great. Thank you very much for your reply and helpful information.
