### ISSUE TITLE
How to visualize my clusters?

### ISSUE THREAD

**Issue by YangLilith** [satijalab/seurat#1341]
I am dealing with GEO dataset. And the first step is to cluster my data. Here are my steps:
1. Dimensional reduction: I implemented PCA. 
2. Run JackStraw to find the principal components. And use the first 12 components to run t-sne.
3. Using the result of t-sne to run FindClusters. Here is a problem. After I ran FindClusters function. How can I plot it?

I searched online and found everyone run t-sne after finding clusters. Why? I thought t-sne is a way of dimensional reduction. it cannot visualize the clusters.
Even though I run t-sne, I still cannot get better clusters. All dots are overlapped.
```
# Importing the library
library(Seurat)
library(dplyr)
library(Matrix)

# Importing the dataset
kidney = read.table("final - age.csv", sep = ",", header = T, row.names = 1)

# Create the object
kidney = log(kidney+1)
kidney_object1 <- CreateSeuratObject(raw.data = kidney, min.cells = 10, min.genes = 1260)


# Find the variables genes
data_var =FindVariableGenes(object = kidney_object1,
                            mean.function = ExpMean,
                            dispersion.function = LogVMR)

# Scale data
data_scale <- ScaleData(object = data_var)


# PCA -- dimentional reduction
data_PCA = RunPCA(data_scale,
                  pc.genes = data_scale@var.genes)
PCAPlot(data_PCA)

# -- Don't use all genes -- 

# JackStraw -- principle components
data_PC=JackStraw(data_PCA,num.replicate = 1000)
JackStrawPlot(data_PC,PCs = 1:12)

# t-SNE
data_TSNE <- RunTSNE(data_PC, perplexity=30, do.fast = T)
TSNEPlot(data_TSNE, do.label = F)

# find cluster
data_cluster <- FindClusters(object = data_TSNE, reduction.type = "pca", dims.use = 1:12, 
                             resolution = 0.6, print.output = 0, save.SNN = TRUE)
PrintFindClustersParams(object = data_cluster)

# Why run t-sne?
data_TSNE <- RunTSNE(data_cluster, perplexity=30, do.fast = T)
TSNEPlot(data_TSNE, do.label = F)
```
The results is：
![image](https://user-images.githubusercontent.com/49418705/55763279-3d9cdb80-5a34-11e9-98ea-4d92011d6be4.png)

**Comment by Dragonmasterx87** [comment]
Consider decreasing the number of variable genes used for clustering. reducing dimensionality increases spatial 'tightening' of clusters. Also, what is data_PC? when you run your tSNE the obj is not described elsewhere.

I strongly recommend following the [S3 protocol](https://satijalab.org/seurat/v3.0/immune_alignment.html) UMAP clustering will improve your cluster tightness.
