### ISSUE TITLE
Reference of Cell type markers

### ISSUE THREAD

**Issue by AMA111** [satijalab/seurat#1344]
Hey, 
I am wondering if you could please provide me the references / papers you used to define cell types markers; specially CD4/CD8 T- cells and NK cells in both of these tutorials?
https://satijalab.org/seurat/v3.0/sctransform_vignette.html
https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html

Thanks,
Abdelrahman

**Comment by SeadonXing** [comment]
Yes , I agree with Abdelrahman. Sometimes its difficult for me to distinguish memory and navie T cells.  Are there any good markers for single cell RNA-seq data to identify memory and naive cell ?
BTW, there maybe a mistake in https://satijalab.org/seurat/v3.0/sctransform_vignette.html  that there are two S100A4, and I  think one of it should be IL32.

Best

**Comment by satijalab** [comment]
We typically use S100A4 and CCR7 as markers that have been established in the literature for memory and naive. For CD8 and NK we use canonical markers (i.e. CD8 and GNLY).

**Comment by AMA111** [comment]
Actually, GNLY is a cytotoxic marker which could be expressed in both Cytotoxic CD8 T-cells and NK cells. Also,  there is NKT cells which express T cell markers and the canonical marker for the NK cells (CD56). Please, check the following : 
https://www.nature.com/articles/s41591-018-0045-3/figures/1 


![image](https://user-images.githubusercontent.com/29317258/59137170-a649fb00-8986-11e9-97b9-17ee2133b7ff.png)

https://www.thermofisher.com/antibody/product/CD52-Antibody-clone-CF1D12-Monoclonal/67-0529-42

![image](https://user-images.githubusercontent.com/29317258/59137145-90d4d100-8986-11e9-8090-01cecfe0d195.png)

Thanks,
Abdelrahman
