### ISSUE TITLE
Seurat 3 re-clustering

### ISSUE THREAD

**Issue by iiiir** [satijalab/seurat#1347]
Hi,
I had some hard time to understand the re-clustering results.  here are the steps i took:
`## subclustering T cells`
`myproject.15.t <- SubsetData(myproject.15, ident.use = c(2,3,6,8,9,16))`
`myproject.15.t <- RunPCA(object = myproject.15.t, verbose = F)`
`myproject.15.t <- FindClusters(myproject.15.t, resolution = 0.6,n.iter = 50)`
`myproject.15.t <- RunTSNE(object = myproject.15.t, dims = 1:30, verbose = F)`

After re-clustering why the numbers of the clusters are `Levels: 1 3 6 7 14` instead of `Levels: 0 1 2 3 4`?

![image](https://user-images.githubusercontent.com/4137873/55827056-51e5e480-5ad7-11e9-885e-6b42f35e4cc7.png)

![image](https://user-images.githubusercontent.com/4137873/55827089-6a55ff00-5ad7-11e9-895d-2732fd28dce1.png)

Thanks a lot,
Shuoguo

**Comment by andrewwbutler** [comment]
That doesn't seem right to me. Which version of Seurat are you using and are you able to share `myproject.15` or a subset that reproduces the issue?

**Comment by iiiir** [comment]
Sorry I cannot provide that dataset, and my network preventing me from upload files to public domains. 
I will try to find a public dataset to test and follow up on the topic later.

**Comment by satijalab** [comment]
The only additional comment I have is that you could rescale after doing a subset on your data. I'm closing this for now but feel free to get in touch if you can share more info
