### ISSUE TITLE
JackStraw plot - how to interpret this result?

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1348]
I'm still a beginner at analysing scRNAseq data, and I'm having trouble interpreting these results. I ran the JackStraw plot and got the following result. Is it strange that the first two PC values are 0 and the rest are quite significant?

![Screenshot (130)](https://user-images.githubusercontent.com/41524686/55847591-e1ab8300-5b17-11e9-8017-b1cc7ac4cb9a.png)

Here's the elbow plot:
![Screenshot (131)](https://user-images.githubusercontent.com/41524686/55847714-58e11700-5b18-11e9-9ce6-926a870633c8.png)

**Comment by andrewwbutler** [comment]
Hi, 

This is likely because the p-value is smaller than can be represented in R and so it get's assigned as 0. I would certainly include the first 2 PCs here in your downstream analyses.
