### ISSUE TITLE
Duplicate cell names when running CCA

### ISSUE THREAD

**Issue by jprestonnn** [satijalab/seurat#135]
Hello,

My data has the same cell barcode in both objects. I'm wondering if there is an easy way to rename the cells by appending a label before aligning, like the 'add.cell.id1' option in MergeSeurat?

The error:
> N2s <- RunCCA(object = N2_1, object2 = OH_1, group.by = "sample", scale.data = TRUE, rescale.groups = TRUE)
Running CCA
Merging objects
Error in MergeSeurat(object1 = object, object2 = object2, do.scale = FALSE,  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names

Thanks so much

**Comment by inakicm** [comment]
I use 10x datas so before calling CreateSeuratObject(), I change the colnames of my two matrix:

pbmc.data_firstProject <- Read10X(data.dir = "~/Downloads/first/filtered_gene_bc_matrices/hg19/")
**colnames(pbmc.data_firstProject) = paste0("firstProject_", colnames(pbmc.data_firstProject) )**
pbmc_firstProject <- CreateSeuratObject(raw.data = pbmc.data_firstProject, min.cells = 3, min.genes = 200, project = "10X_PBMC_first")

pbmc.data_secondProject <- Read10X(data.dir = "~/Downloads/second/filtered_gene_bc_matrices/hg19/")
**colnames(pbmc.data_secondProject) = paste0("secondProject_", colnames(pbmc.data_secondProject) )**
pbmc_secondProject <- CreateSeuratObject(raw.data = pbmc.data_secondProject, min.cells = 3, min.genes = 200, project = "10X_PBMC_second")

**Comment by andrewwbutler** [comment]
We've added support for this scenario (#129) on the develop branch if you want to try that out. You can now give parameters to RunCCA that get passed on to MergeSeurat (such as add.cell.id1).

**Comment by bio-la** [comment]
Hi,
for some reason the add.cell.id1 and 2 strings are pasted to all of slots storing the cell names BUT the cca@cell.embeddings. Also, if I match the cca names with the merged_object@cell.ident they're not sorted ?
If I run mergeSeurat the names are correct.

my code is

HLA.cca<-RunCCA(HLA.pos,HLA.neg,genes.use = hgv.union, 
                group1 =unique(HLA.pos@ident),group2 =unique(HLA.neg@ident),
                add.cell.id1="pos", add.cell.id2="neg") 
all.equal(attr(HLA.cca@dr$cca@cell.embeddings, "dimnames")[[1]],gsub("neg_","",gsub("pos_","", HLA.cca@cell.names)))
is.unsorted(match(attr(HLA.cca@dr$cca@cell.embeddings, "dimnames")[[1]] , gsub("neg_","",gsub("pos_","", HLA.cca@cell.names))  ))

**Comment by bio-la** [comment]
(ah. I think I know the answer to the second question. it's the barcodes shared by both the datasets  that are matched twice.)
