### ISSUE TITLE
How to remove batch effect only drived by one sample ?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1353]
Hi all :
    After perform all the steps by Seurat , I got a tSNE overview of my sample. But I found that there is one sample that always split from other samples for specific cell types.
    As you see from the Fig : https://github.com/SeadonXing/Questions-For-Seurat/blob/master/BatchDrivedByOneSample.PNG
    Especially for cluster 7,8,11, it can be clearly see that in each of the cluster, Sample_2 is always split from the large cluster and group to a small subcluster.
    My question is that how to remove this effect only drived by one sample (Sample_2) and merge it to the whole large cluster ? I know that the most easy way is to drop this samples, but you know that its too treasure for me.
    I have try the method here : https://github.com/satijalab/seurat/issues/262 by identify high var.genes related to Sample_2 and exclude this genes from “pc.genes” by run step of "RunPCA(object = scObject, pc.genes = setdiff(scObject@var.genes, Sample_2specificGenes)) " . But nearly no effect . So you may raise good advice for this situation.

Best

**Comment by satijalab** [comment]
See #1351
