### ISSUE TITLE
error in install seurat V3

### ISSUE THREAD

**Issue by huuthoth** [satijalab/seurat#1356]
Hi,
i am trying to install Seurat
install.packages('Seurat')
library(Seurat)
but I get the error message:
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘robustbase’

**Comment by huuthoth** [comment]
i install robustbase
after that i run devtools and it has error
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
Downloading GitHub repo satijalab/seurat@release/3.0
Error: Could not find tools necessary to compile a package

**Comment by MichaelStreuber** [comment]
Hi @huuthoth 

Try this:
install.packages('BiocManager')
library(BiocManager)
BiocManager::install(c('ape', 'fitdistrplus', 'future', 'future.apply', 'ggridges', 'ica', 'igraph', 'irlba', 'lmtest', 'metap', 'pbapply', 'RANN', 'reticulate', 'ROCR', 'rsvd', 'SDMTools', 'tsne', 'RcppProgress'), ask=T )

#You can try options("warn"=0) to restore the default warning behavior which might allow the install to complete
options("warn"=0)

#Now try to install it with depencies = FALSE to turn off the automatic dependency installation if you already have the required dependencies.
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0', dependencies=FALSE)

#You might get this error below
#ERROR: dependencies 'cowplot', 'ggrepel', 'plotly', 'png', 'Rtsne', 'RcppEigen' are not available for package 'Seurat'
#Now install them with BiocManager manually:
BiocManager::install(c('cowplot', 'ggrepel', 'plotly', 'png', 'RcppEigen'), ask=T )

#When installing these packages R might ask you if you want to update old packages, yes do it and type "a" for all
BiocManager::install(c('cluster', 'MASS', 'Matrix', 'mgcv', 'survival'), ask=T )
BiocManager::install(c('Rtsne'), ask=T )

#Now it should work when you run the same command from before (some users also recommend to restart R), installation could take a while so don't worry
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0', dependencies=FALSE)

#Test it
library(Seurat)

Hope it will work for you too ;)

Best,
Michael

**Comment by Dragonmasterx87** [comment]
This is what works for me, I have hard uninstalled R, RStdio and re-formatted my OS before testing this:
Install Rv 3.5.1 and Rstudio

install.packages("Matrix")
install.packages("ggridges")
install.packages("cowplot")
install.packages('devtools')
install.packages('ggrepel')
devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
library(Seurat)
packageVersion("Seurat")

**Comment by huuthoth** [comment]
Thank you for your suggestion.
it's still error when i run 
> devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
Downloading GitHub repo satijalab/seurat@release/3.0
Error: Could not find tools necessary to compile a package

may be i should re-formatted my OS, reinstall R, Studio

**Comment by MichaelStreuber** [comment]
Hi @huuthoth 

Could you maybe provide us with the output of "sessionInfo" command?

Also check out the previous issue with discusssion: #914 

Best,
Michael

**Comment by huuthoth** [comment]
Hi Michael,
Many thanks for method. 
specifically, i have problem when i install 'reticulate'
* installing *source* package ‘reticulate’ ...
** package ‘reticulate’ successfully unpacked and MD5 sums checked
** libs
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
ERROR: compilation failed for package ‘reticulate’

**Comment by MichaelStber** [comment]
Hi @huuthoth 

Mmh... is the system specifically asking you to install "reticulate"?

Have you tried the script commands from @Dragonmasterx87 and me?
Normally it should work. You can also try to run
`.rs.restartR()`
to restart R

What do you get after running
`devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0', dependencies=FALSE)`
???

**Comment by huuthoth** [comment]
Hi Michael,
I tried both script commands from  @Dragonmasterx87 and you.
I got this error when i run devtools
> devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')
Downloading GitHub repo satijalab/seurat@release/3.0
Error: Could not find tools necessary to compile a package

**Comment by MichaelStber** [comment]
A what a pity! I see.
Can you send us you sessionInfo??
It looks like this:

`> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2.2  umap_0.2.0.0    networkD3_0.4   tidyr_0.8.1     beepr_1.3       devtools_1.13.6 dplyr_0.7.6    
 [8] Seurat_2.3.4    Matrix_1.2-14   cowplot_0.9.2   ggplot2_3.1.0  

loaded via a namespace (and not attached):
  [1] Rtsne_0.15          colorspace_1.4-1    class_7.3-14        modeltools_0.2-22   ggridges_0.5.1     
  [6] mclu`

**Comment by huuthoth** [comment]
Hi Michael,

>  sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        ps_1.3.0          prettyunits_1.0.2 rprojroot_1.3-2  
 [5] digest_0.6.18     crayon_1.3.4      withr_2.1.2       assertthat_0.2.1 
 [9] R6_2.4.0          backports_1.1.4   magrittr_1.5      rlang_0.3.4      
[13] cli_1.1.0         curl_3.3          fs_1.2.7          remotes_2.0.4    
[17] testthat_2.0.1    callr_3.2.0       desc_1.2.0        devtools_2.0.2   
[21] tools_3.5.1       glue_1.3.1        pkgload_1.0.2     compiler_3.5.1   
[25] processx_3.3.0    pkgbuild_1.0.3    sessioninfo_1.1.1 memoise_1.1.0    
[29] usethis_1.5.0

**Comment by MichaelStber** [comment]
Hi,

have you tried it with the new released Seurat Version 3?

[(https://satijalab.org/seurat/install.html)]

**Comment by huuthoth** [comment]
Hi Michael,
I have tried with the new released Seurat V3, and it worked.

Many thanks for your suggestion,

Best,

Tho

**Comment by MichaelStber** [comment]
Hi Tho,
Good, glad to hear that it finally worked :)

Have fun!
