### ISSUE TITLE
Empty results from Loadings function

### ISSUE THREAD

**Issue by zhaocheng3326** [satijalab/seurat#1358]
Hi there.
I am using Seurat_3.0.0.9000 and I find a problem with "Loading" function. You can repeat it with 
```R
library(Seurat)
data <- CreateSeuratObject(counts = pbmc_small@assays$RNA@counts, meta.data = pbmc_small@meta.data)
data <- NormalizeData(data, verbose = FALSE)
data <- FindVariableFeatures(data, selection.method = "vst",nfeatures = 100, verbose = FALSE)
data <- ScaleData(data, verbose = FALSE, vars.to.regress = c("nFeature_RNA"))
data <- RunPCA(data, npcs = 15, verbose = FALSE)

Loadings(data) ### empty
Loadings(pbmc_small) ### the real gene loadings
```

**Comment by mojaveazure** [comment]
Hi,

Can you install the latest version of Seurat v3 (3.0.0.9100)? Under this version, I am unable to replicate this issue.

**Comment by zhaocheng3326** [comment]
Thanks for your quick replying and no wonder Seurat is such an outstanding tool. I just installed Seurat_3.0.0.9100. And it works now. Many thanks.
