### ISSUE TITLE
import merged subject from v2.3.4 to v3.0

### ISSUE THREAD

**Issue by marong0511** [satijalab/seurat#1359]
Hi

Has anyone encountered the problem when importing merged subject from seurat v2.3.4 to v3.0? I mean the subject can be loaded anyway, but it cannot be identified as S4 class or seurat object in v3.0 as before. Besides, I cannot use other functions in v3.0 over my subject output from v2.3.4.

For example, I was going to rename cell identity so I imput Idents(object = immune.combined) but it got error: Error in UseMethod(generic = "Idents", object = object) : no suitable method for this object.

Thanks 
Rong

**Comment by mojaveazure** [comment]
Hi Rong,

[As stated](https://github.com/satijalab/seurat/issues/1293) [previously](https://github.com/satijalab/seurat/issues/990#issuecomment-444606845), you cannot use v2 objects in v3 except for updating a v2 object to a v3. In Seurat v3, we no longer support the v2 object and only define methods for the v3 object. To continue your analysis, we recommend either upgrading your object to a v3 object with `UpdateSeuratObject` or rolling back to v2

**Comment by marong0511** [comment]
> Hi Rong,
> 
> [As stated](https://github.com/satijalab/seurat/issues/1293) [previously](https://github.com/satijalab/seurat/issues/990#issuecomment-444606845), you cannot use v2 objects in v3 except for updating a v2 object to a v3. In Seurat v3, we no longer support the v2 object and only define methods for the v3 object. To continue your analysis, we recommend either upgrading your object to a v3 object with `UpdateSeuratObject` or rolling back to v2

OK, thanks for quick reply!
Rong
