### ISSUE TITLE
IntegrateData: new data doesn't have same number of features as the current data

### ISSUE THREAD

**Issue by cap76** [satijalab/seurat#1360]
I'm using Seurat3 and attempting to follow some of the tutorials for comparing 10X data (changing some of the datasets) and am encountering an error when I try to use IntegrateData function (see below). I'm wondering if anyone has encountered this before?  

Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Warning: The new data doesn't have the same number of features as the current data
Error: Attempting to add a different number of cells and/or features

**Comment by fidelram** [comment]
I had the same problem. See #1357 for a solution.

**Comment by cap76** [comment]
Ah, how did I miss that. Thank you :-) Sorry all for the unnecessary Issue open.
