### ISSUE TITLE
CITE-seq COUNT cell number

### ISSUE THREAD

**Issue by notimenocall** [satijalab/seurat#1362]
Hi,
I am using CITE-seq COUNT for ADT and HTO analysis and couldn't get the correct number of cells defined. (And it worked before but not anymore...)
Below is the script used:
```
CITE-seq-Count -R1 ADT_HTO_tag_R1.fastq.gz -R2 ADT_HTO_tag_R2.fastq.gz -t /home/chenx302/Xiao/XC7_hashing/XC7_libraries_tag_CITE.csv -cbf 1 -cbl 16 -umif 17
-umil 28 -cells 11496 -wl /home/chenx302/Xiao/XC7_hashing/XC7_WHITELIST_antibody -o ~/Xiao/XC7_hashing/XC7_hashing/outs/fastq_path/tags_fastqs/CITE_SEQ_04122
019
```
The WHITELIST contains 11496 rows and I also '-cells 11496'. However the barcodes.tsv in umi_count only contains 11484 rows.
Any idea why?? I got the proper number of rows before with the same files. But now I merged all the *R1*.fastq from different NextSeq lanes and the same for *R2*.fastq and it stopped working. Can CITE-seq COUNT handle multiple R1 R2 entries? I did the below script previously but it seems like the output from the last file overwrite the previous.
```
R1="ADT_tag_S2_L001_R1_001.fastq.gz ADT_tag_S2_L004_R1_001.fastq.gz HTO_tag_S3_L003_R1_001.fastq.gz ADT_tag_S2_L002_R1_001.fastq.gz HTO_tag_S3_L001_R1_001.f
astq.gz HTO_tag_S3_L004_R1_001.fastq.gz ADT_tag_S2_L003_R1_001.fastq.gz HTO_tag_S3_L002_R1_001.fastq.gz"

R2="ADT_tag_S2_L001_R2_001.fastq.gz ADT_tag_S2_L004_R2_001.fastq.gz HTO_tag_S3_L003_R2_001.fastq.gz ADT_tag_S2_L002_R2_001.fastq.gz HTO_tag_S3_L001_R2_001.f
astq.gz HTO_tag_S3_L004_R2_001.fastq.gz ADT_tag_S2_L003_R2_001.fastq.gz HTO_tag_S3_L002_R2_001.fastq.gz"

arr=($R1)
arr2=($R2)

for i in {0..7}
do
       CITE-seq-Count -R1 ${arr[i]} -R2 ${arr2[i]} -t /home/chenx302/Xiao/XC7_hashing/XC7_libraries_tag_CITE.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells 114
96 -wl /home/chenx302/Xiao/XC7_hashing/XC7_WHITELIST_antibody -o ~/Xiao/XC7_hashing/XC7_hashing/outs/fastq_path/tags_fastqs/CITE_SEQ
done
```

**Comment by notimenocall** [comment]
I got the proper number of rows before with the same files. But now I merged all the *R1*.fastq from different NextSeq lanes and the same for *R2*.fastq and it stopped working.

**Comment by mojaveazure** [comment]
Please file issues for CITE-seq-Count at its repository:  https://github.com/Hoohm/CITE-seq-Count

**Comment by notimenocall** [comment]
@mojaveazure  Thanks a lot for your prompt response! My version is the most updated.
```
CITE-seq-Count --version
CITE-seq-Count v1.4.2
```
