### ISSUE TITLE
How to obtain dispersion values and gene expression values for the highly variable genes?

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1363]
I would like to look at the genes that are highly variable in a cluster (I've been able to separate out the cluster by subset() so that part works fine). 
Now I want to output something like [gene name] [dispersion value] [gene expression value].
In other words: from my dispersion plot, can I just get the values of y and x axis for each of those red dots?

Of note: I'm using Seurat v3.0

<img width="748" alt="Screen Shot 2019-04-11 at 1 13 30 PM" src="https://user-images.githubusercontent.com/41524686/55976966-a619d180-5c5b-11e9-9c1c-64239e32232e.png">

**Comment by mojaveazure** [comment]
Hi Maria,

You can get feature dispersion information using `HVFInfo`; this will provide information for all features, so you can subset that to only variable features using `VariableFeatures`

```R
HVFInfo(object)[VariableFeatures(object), ]
```

**Comment by fly4all** [comment]
Awesome, thank you!
Two quick questions. 1) How is "variance.standardized" calculated here?
I tried calculating variance-to-mean ratio but that's a different value than "variance.standardized" so I'm curious about how it gets to those values.
2) Is there a threshold set by default to define a gene as highly variable? My concern is that each gene would likely have some biological variability from cell-to-cell so how is the threshold set?

**Comment by fly4all** [comment]
Hi Petra,

I used "vst" as selection.method. 
```
FindVariableFeatures(object=decoder, selection.method="vst",min.features=2000)
VariableFeaturePlot(object=decoder)

```

**Comment by ravipatel4** [comment]
> Awesome, thank you!
> Two quick questions. 1) How is "variance.standardized" calculated here?
> I tried calculating variance-to-mean ratio but that's a different value than "variance.standardized" so I'm curious about how it gets to those values.
> 2) Is there a threshold set by default to define a gene as highly variable? My concern is that each gene would likely have some biological variability from cell-to-cell so how is the threshold set?

@fly4all, I am also looking for an answer to the Q1. Did you find an answer?
