### ISSUE TITLE
Step-wise integration for v3

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#1365]
Dear Seurat Team,

Previously I have successfully integrated two datasets, set A and B, to set AB using v3. Now, I was hoping to align a new dataset C to the previously integrated dataset. Although I know it's impossible for UMAP or tsne to add new data, I'm wondering if it's reasonable to integrate previously integrated Set AB with new data C instead of doing a multi-integration of ABC.

When I try to integrate AB with C, I got the error: The following 15337 features requested have zero variance (running reduction without them): ... RPS27, TPM3, C1orf43, UBAP2L, HAX1, AQP10, ATP8B2, IL6R, SHE, UBE2Q1, ADAR, KCNN3, PMVK, PBXIP1, PYGO2, RP11-307C12.12, SHC1Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
and also the $integrated@data@x are NaN

I really appreciate all your help.

Thanks

**Comment by DHGK** [comment]
> At which stage of the analysis are you performing the merge? I say this because you say that 'its impossible for UMAP or tSNE to add data' which suggests you are already well on your way in terms of downstream thresholding and normalization QC, so you are not merging raw Seurat objects which could be why you are facing integration issues.
> 
> You should do this just after you make Seurat objects. Please look [here](https://satijalab.org/seurat/v3.0/merge_vignette.html) and navigate to: **'Merging More Than Two Seurat Objects'**
> 
> Also, I am not a dev. So if this doesn't help you should wait for a reply from a Seurat dev.

I get what you mean, but I was hoping to use CCA instead of merge function to the alignment. I've used CCA/anchorgenes to combined my A and B datasets. I'm now not sure as I got a new smaller dataset C. if I should do a multi-integration of 3 datasets or just integrate AB with C.

**Comment by satijalab** [comment]
You can perform step-wise integration. In this case, just make sure that when you run FindIntegrationAnchors and IntegrateData, you select the 'integrated' assay.
