### ISSUE TITLE
Error Running FindClusters

### ISSUE THREAD

**Issue by ml439** [satijalab/seurat#1367]
I'm running Seurat_2.3.4 in R version 3.5.1. And when I try to call clusters with the following command I get and error for which  I cannot find an answer anywhere.

 FindClusters( object = scE15dat, reduction.type =  "pca", dims.use = 1:15,
                             resolution = 1.4, print.output = 0, save.SNN= TRUE)

Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument
In addition: Warning message:
In max(connectivity, na.rm = T) :
  no non-missing arguments to max; returning -Inf

I wonder if the error has something to do with the fact that I have few cells, or if it's due to something else. I would appreciate any suggestion. 
scE15dat 
An object of class seurat in project E15.5_mDO 
 7772 genes across 39 samples.

Thank you very much
Miriam

**Comment by andrewwbutler** [comment]
Does the error persist if you lower the resolution value?

**Comment by ml439** [comment]
Hi,


Thank you for your email. I did not try that but I found a bug in my script that was filtering out too many cells, once that was corrected I had more cells and then the error did not appear again. Sorry to have bothered you.


Best wishes,


Miriam

________________________________
