### ISSUE TITLE
Error in data.use[features, ] : no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by FarzanT** [satijalab/seurat#1368]
Hello,
I am trying to run `FindIntegrationAnchors` for a list of Seurat objects that were made by subsetting another list of Seurat objects by some cells:
```r
    all_subs <- vector(mode = "list", length = length(seurat_list))
    for (i in 1:length(seurat_list)) {
        Idents(seurat_list[[i]]) <- "hpca_cell_name"
        all_subs[[i]] <- SubsetData(seurat_list[[i]], ident.use = celltype)
    }
```
But when I try to find anchors, I get the following error:
```r
    cur_anchors = FindIntegrationAnchors(
        object.list = all_subs,
        # assay = rep("RNA", length(all_subs)),
        anchor.features = 2000,
        dims = 1:5,
        scale = F,
        l2.norm = T,
        k.anchor = 5,
        k.filter = 200,
        k.score = 30,
        max.features = 200,
        eps = 0, 
        verbose = T
    )
Finding all pairwise anchors
   |                                                  | 0 % ~calculating  Error in data.use[features, ] : no 'dimnames' attribute for array
```
I have tried updating to latest GitHub Ref, creating a new Seurat objects based on the subsets, using the subsetting by cell names instead of the `SubsetData` function, but I still get the same error. This issue was discussed in #1017, but I don't think it's been fixed yet.

Any help is much appreciated,
Farzan

**Comment by andrewwbutler** [comment]
Hi Farzan,

Are all the features that you're using to find the anchors already scaled in each of objects in the `all_subs` object list? Generally, if you're going to handle the scaling yourself (by setting `scale =F`), you should also provide the set of `anchor.features` to ensure that they're scaled in each object. You can see which features `FindIntegrationAnchors` is choosing by running `SelectIntegrationFeatures` and verifying that they're actually scaled in each of the objects.

**Comment by FarzanT** [comment]
Thank you, I've set the `ScaleData = TRUE`, but I now get another error downstream in the `IntegrateData` function:
```r
> cur_integrated = IntegrateData(anchorset = cur_anchors, dims = 1:30, verbose = T)
Error in hclust(d = dist.mat) : 
  NA/NaN/Inf in foreign function call (arg 11)
```
I didn't find a related issue, am I doing something wrong?

Thank you so much for the help,
Farzan

**Comment by andrewwbutler** [comment]
Sorry for the delayed response. Did you figure out this issue? If not, could you provide an object that can reproduce the error?

**Comment by FarzanT** [comment]
I kept only those experiments that had at least 50 cells, and the error went away. I think it's mainly something to do with the `k.weights` parameter in the `IntegrateData` function.
Thanks!
