### ISSUE TITLE
where does imputed values stored in new seurat 3 object

### ISSUE THREAD

**Issue by roofya** [satijalab/seurat#1370]
Hello,
I had updated my old seurat object to version 3. I'm wondering where does imputed values stored in the new seurat. And for FeaturePlot and VlnPlot function for old version of Seurat there was "use.imputed" option to plot feature based on imputed values but in Seurat 3 there is not this option.

Thank you

**Comment by mojaveazure** [comment]
Hi @roofya,

Unfortunately, I don't believe `UpdateSeuratObject` brings the `imputed` slot from a v2 object into a v3 object. However, this is fairly easy to do if you have both objects loaded at the same time:

```R
v3.object <- UpdateSeuratObject(object = v2.object)
v3.object[['imputed']] <- CreateAssayObject(data = as.matrix(x = v2.object@imputed))
```

This will store the imputed data in an [`Assay`](https://github.com/satijalab/seurat/wiki/Assay) object called "imputed" and you can work with it the same way you would any other assay in a multi-modal v3 object. You can plot features using the key for the "imputed" assay (`Key(object = v3.object[['imputed']])`) or set it to be the default assay

```R
DefaultAssay(object = v3.object) <- 'imputed'
```

For more information about multi-modal objects in Seurat v3, please see our [multi-modal vignette](https://satijalab.org/seurat/v3.0/multimodal_vignette.html).

**Comment by roofya** [comment]
Thank you so much Paul, 

It was so helpful.
