### ISSUE TITLE
Highlight specific genes in the dispersion plot

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1371]
Hi,
I would like to highlight (by showing text over the data point) certain genes in the variableFeaturePlot. What would be the best way to do that?
If I try it with 
```
top10 <- head(x=VariableFeatures(object=decoder),10) 
plot1<- VariableFeaturePlot(object=decoder)
LabelPoints(plot=plot1, labels=top10)
```
that would only give me the top10 genes. If my gene of interest is not within those top 10 or 20 etc. how can I just display those over the plot? Also, if there is a hoverLocator option that could show me gene names on the plot as I move my cursor over them, that would be great.

Thank you!

**Comment by andrewwbutler** [comment]
Hi,

If you want to display other names on the plot, you just need to provide a different vector of gene names to the `labels` parameter in `LabelPoints`. As for `HoverLocator`, that should work with `VariableFeaturePlot` to show you gene names. E.g.

```R
plot1 <- VariableFeaturePlot(object=decoder)
HoverLocator(plot = plot1)
```

**Comment by fly4all** [comment]
that worked, thank you!
