### ISSUE TITLE
FindConservedMarkers; find markers that are not conserved?

### ISSUE THREAD

**Issue by Emmavb1988** [satijalab/seurat#1372]
I have created an integrated Seurat Object from two different single cell RNAseq datasets and am currently trying to identify the different resulting clusters.

FindConservedMarkers() gives me the markers of clusters that are conserved between the two datasets, but I also have clusters that are not represented by both datasets and I'm trying to figure out how I can find the markers of these clusters.

FindAllMarkers() still gives me only yhe conserved markers and FindMarkers() gives me a 'subscript out of bounds' error suggesting that the cluster I am trying to identify the markers for is not stored either, right?

Do you maybe have a solution for this?

Thanks a lot in advance!

**Comment by andrewwbutler** [comment]
What is the issue with `FindMarkers`? Can you provide the code you've ran?

**Comment by Emmavb1988** [comment]
FindConservedMarkers(object = myobject, ident.1 = 0, grouping.var = "set",  verbose = FALSE) 

#gives me the conserved markers and works.

FindAllMarkers(object = myobject, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25) 

#also only gives me the conserved markers

FindMarkers(object = myobject, ident.1 = 1, min.pct = 0.25) 

#cluster 1 is a cluster that is not conserved between the two datasets that I integrated; I get the following error after running the code untill 100% of the calculations are done

Error in data.alpha[rownames(x = de.results), , drop = FALSE] : 
  subscript out of bounds

I've increased the RAM used by R allready so I don't think it is a memory issue?

**Comment by andrewwbutler** [comment]
No, it's not a memory issue. Does the issue persist if you lower the `min.pct` threshold?

**Comment by Emmavb1988** [comment]
I get the same error with the default min.pct (=0.1)

**Comment by MediciPrime** [comment]
Although not entirely related to the topic of this issue, I was wondering if we can use FindAllMarkers to accurately ID the cell clusters as done w/ a non integrated analysis?  I am asking because FindConservedMarkers isn't automated for all the clusters like FindAllMarkers.

**Comment by satijalab** [comment]
You can use FindAllMarkers to do this. However, if any one gene is particularly important, its worth going and checking its expression in multiple datasets to make sure there is support.
