### ISSUE TITLE
using AddModuleScore with imputed data 

### ISSUE THREAD

**Issue by doctorjb77** [satijalab/seurat#1376]
Hello, 
Trying to use the AddModuleScore to create a score with a set of genes. 
I would like to create the score based on the Magic imputed values, and tried to use the specific assay (i.e. Objectname[["magic"]] ) as object but getting the following error message:
no applicable method for 'DefaultAssay' applied to an object of class "Assay"

Is there a good way to do this? 
thanks,

**Comment by mojaveazure** [comment]
Hi JBK,

`AddModuleScore` has an `assay` parameter, where you can set which assay to use. You can also set the default assay beforehand and `AddModuleScore` will use it automatically.

```R
# Pass "magic" as a parameter to AddModuleScore
object <- AddModuleScore(object = object, assay = "magic", ...)
# Set default assay beforehand
DefaultAssay(object = object) <- "magic"
object <- AddModuleScore(object = object, ...)
```

**Comment by doctorjb77** [comment]
Thank you!
