### ISSUE TITLE
Version specific Seurat Installation key

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#1379]
Very simple question, when writing code for supplementary files, I realized it would be better to point Seurat installations towards the particular version used for the analysis. I see that S3.0.0.9000 has already become S3.0.0.9150, although yes the functions may not change, if I have run my analysis on a particular version of Seurat, it would be nice to direct the install in the first few lines of code to the version of Seurat which I used for the analysis. This way someone who wants to reproduce my experiments, will not have to hit their head against the wall trying to figure out cross-version compatibility issues. Which will be the case if I include install.packages('Seurat'). It would be great if I didn't contribute to graduate students suffering and looking through lines of code, to figure out how to make it work.

Could you provide a version specific installation guide? if that's too complicated, just a line of code, and then the 'ref' variables for different versions of Seurat?

Cheers for the help.

**Comment by andrewwbutler** [comment]
Hi,

You can checkout version specific installation instructions [here](https://satijalab.org/seurat/install.html).

Sorry for any confusion with the versioning. We have been preparing the official release of v3.0.0 and were using 3.0.0.9XXX to internally track that progress as we resolved a few last minute things. As of today, `install.packages("Seurat")` will by default install version 3.0.0 now. Any older released versions can still be installed with 
```R
devtools::install_version(package = 'Seurat', version = package_version('2.X.X'))
```
Note that this only works for CRAN releases (i.e. not 3.0.0.9XXX versions). 

If you want to install a specific commit from github, you can do that with
```R
devtools::install_github(package = 'Seurat', ref = "XXXX") # replace with commit id
```

**Comment by Dragonmasterx87** [comment]
Cheers! Thanks!!

**Comment by Dragonmasterx87** [comment]
Also congratulations, big day for your guys. V3 is o CRAN. I just used install.packages('Seurat') and packageVersion(Seurat) came up with 3.0.0.9000.

**Comment by andrewwbutler** [comment]
Hmm, try restarting R. The [CRAN page](https://cran.r-project.org/web/packages/Seurat/index.html) shows the version to be 3.0.0.

**Comment by Dragonmasterx87** [comment]
Fixed!
