### ISSUE TITLE
Error in TransferData: cannot find more nearest neighbours than there are points

### ISSUE THREAD

**Issue by thomasdwu** [satijalab/seurat#1381]
In Seurat v3 (both the 3.0.0 version in CRAN and the pre-release version), I am seeing the following error in some pairs of datasets (all where combined2.obj is the same):

> tumor1.obj <- CreateSeuratObject(counts=mat.t1, project="T1")
> tumor1.obj <- SCTransform(tumor1.obj)
> normal1.obj <- CreateSeuratObject(counts=mat.n1, project="N1")
> normal1.obj <- SCTransform(normal1.obj)
> combined.anchors <- FindIntegrationAnchors(c(tumor1.obj, normal1.obj), dims=1:30)
> combined1.obj <- IntegrateData(combined.anchors, dims=1:30)
> combined1.obj <- ScaleData(combined1.obj)
> combined1.obj <- RunPCA(combined1.obj, npcs=30)
> combined1.obj <- RunTSNE(combined1.obj, reduction="pca", dims=1:30)
> combined1.obj <- FindClusters(combined1.obj)

[Same process is repeated to combine tumor2.obj and normal2.obj into combined2.obj.]

> anchors <- FindTransferAnchors(reference=combined1.obj, query=combined2.obj, dims=1:30)
Performing PCA on the provided reference using 2000 features as input.
Projecting PCA
Finding neighborhoods
Finding anchors
        Found 160 anchors
Filtering anchors
        Retained 27 anchors
Extracting within-dataset neighbors

> predictions <- TransferData(anchorset=anchors, refdata=combined1.obj@active.ident, dims=1:30)
Finding integration vectors
Finding integration vector weights
Error in nn2(data = data.use[anchors.cells2, ], query = data.use, k = k +  1, eps = eps)
  Cannot find more nearest neighbors than there are points

This is similar to the issue as reported in "Seurat v3 integrative analysis #997", although this involves the TransferData function.  Is there any way to resolve this error?  Let me know if you need further information or the raw files.

**Comment by timoast** [comment]
This is because you only have 27 anchors and the default `k` for weighting anchors in `TransferData` is 50. 27 is very small, how many cells do you have in each group total? Do you expect shared cell types in combined1.obj and combined2.obj?

**Comment by thomasdwu** [comment]
In combined1.obj@active.ident, FindClusters generated 11 clusters, ranging in size from 33 to 2708.  In combined2.obj@active.ident, FindClusters generated 15 clusters, ranging in size from 15 to 2245.

I do expect shared cell types across the two datasets, since they are samples from two patients with similar types of tumors, although I do not know in advance if every cluster in combined1.obj has representation in combined2.obj, or vice versa.  From your description of the problem, I can think of the following workarounds:

1.  Set k to be smaller than 50 (perhaps based on the size of the smallest cluster)
2.  Tell FindClusters not to find any small clusters (but I don't know how to do this).
3.  Replace small clusters in refdata with NA

Do you have any advice on this?  I was hoping that the TransferData procedure could handle this automatically without the need for manual intervention.

**Comment by timoast** [comment]
For each cell in the query we find the `k` nearest anchor cells and look at the identities of these in the reference dataset to compute the prediction score for each class. If there are less than `k` anchors this will cause an error.

It looks like you're having problems finding a good set of anchors for the transfer, how many do you find for each of the integration steps making `combined1.obj` and `combined2.obj`?.

If the datasets are very different you could try using CCA for finding transfer anchors (`reduction = 'cca'` in `FindTransferAnchors`). I would not recommend setting `k` < 50, the underlying issue is a low number of anchors.

**Comment by thomasdwu** [comment]
Okay, thanks for your advice.  I suppose there are cases that may be a bit
problematic.
