### ISSUE TITLE
How to use function FastWhichcells in Seurat3.0

### ISSUE THREAD

**Issue by weichen123hahah** [satijalab/seurat#1383]
I want to use following in Seurat3.0 ,but I can not find FastWhichcells 
cells.target1 <- FastWhichCells(my_seurat, group.by='orig.ident', subset.value=c('P01N','P03N'),invert = T)

**Comment by andrewwbutler** [comment]
Hi,

You can use `WhichCells` in Seurat v3 for equivalent functionality. The equivalent function call would look like:

```R
cells.target1 <- WhichCells(
    object = my_seurat, 
    expression = orig.ident %in% c('P01N', 'P03N'), 
    invert = TRUE
)
```
