### ISSUE TITLE
heatmap color style

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#1384]
Hi, 
 could you please reveal whether the purple yellow style used in "doHeatmap" can be reproduced in ggplots? Is this an exisiting style or custom made? 
And second, is it possible to use color styles fro Brewer in eh heatmap? 
Thanks and best 
annecar

**Comment by andrewwbutler** [comment]
Hi Annecar,

The purple and yellow color palette used in `DoHeatmap` can be access with `PurpleAndYellow()`. `DoHeatmap` returns a ggplot object which you can style in any way you would normally do with ggplot. For example:

```R
DoHeatmap(object = pbmc_small) + 
    scale_fill_gradientn(colors = RColorBrewer::brewer.pal(n = 10, name = "RdBu"))
```

**Comment by annecar** [comment]
Dear Andrew, 
thanks a lot!
This was easy and works nicely!! 

Best 
Anne 


CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by Dragonmasterx87** [comment]
Or you can just do this and have way more control over your color selection:

DoHeatmap(object = adata) + scale_fill_gradientn(colors = colorRampPalette(c("#0200ad", "#fbfcbd", "#ff0000"))(256))

**Comment by annecar** [comment]
ok, thanks a lot!! 

Best 
Anne 



CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de
