### ISSUE TITLE
Dotplot subscript out of bounds v3.0

### ISSUE THREAD

**Issue by harinipras** [satijalab/seurat#1386]
Hi,

I was trying to get the dotplot, and I got the following error. I'm using v3.

```javascript
DotPlot(temp, features = markers.to.plot,cols = c("red","blue"), split.by = "stim")
```
And I got
```javascript
Error in FUN(X[[i]], ...) : subscript out of bounds
```
I did traceback,
```javascript
traceback()
2: vapply(X = strsplit(x = as.character(x = data.plot$id), split = "_"), 
       FUN = "[[", FUN.VALUE = character(length = 1L), 2)
1: DotPlot(temp, features = markers.to.plot, cols = c("red", "blue"), 
       split.by = "stim", col.max = 0.5, col.min = -0.5)
```

I also tried uninstalling and installing Seurat. But to no avail. Any help would be very much appreciated. Thank you very much

**Comment by andrewwbutler** [comment]
Hi,

Are you able to provide a downsampled version of the object that reproduces the issue?

**Comment by harinipras** [comment]
I don't understand what that means. Would you mind elaborating?

**Comment by andrewwbutler** [comment]
The easiest way for me to figure out what's going on here is if I have a Seurat object that reproduces the issue. Often these datasets can be large and so running something like 
```R
smaller_object <- subset(x = object, downsample = XXX)
```
is nice as it reduces upload/download times.

**Comment by satijalab** [comment]
Unfortunately its very difficult for us to understand whats going on here, particularly if there are any issues with your Seurat object, or if (for example) some of the genes in markers.to.plot don't actually exist in your object. I'm closing now, but feel free to post an object here if you haven't been able to solve the issue. I would also encourage you to reproduce the split dot plots that we show in the immune ctrl/stimulated vignette to make sure Seurat is working for you
