### ISSUE TITLE
Intergeted 3 samples

### ISSUE THREAD

**Issue by penglbio** [satijalab/seurat#1390]
I want to integrate  3 samples 10x single-cell RNA_seq data. But I also want to use the SCTransform to normalise my data. so I should to do the SCTransform before Integration or not.
first I process the 3 samples separetely, then integrated. But I don't know when should I Regressout the cellcycle effect?  my project's code is following,
library(Seurat)
library(ggplot2)
library(sctransform)
N5<- Read10X(data.dir = "../projects/JSK/10.singlecell_ZZ_ADSC_24358/N5/outs/filtered_gene_bc_matrices/hg19/")
N7<- Read10X(data.dir = "../projects/JSK/10.singlecell_ZZ_ADSC_24358/N7/outs/filtered_gene_bc_matrices/hg19/")
N8<- Read10X(data.dir = "../projects/JSK/10.singlecell_ZZ_ADSC_24358/N8/outs/filtered_gene_bc_matrices/hg19/")

ADSC_N5 <- CreateSeuratObject(counts = N5, project = "N5")
ADSC_N7 <- CreateSeuratObject(counts = N7, project = "N7")
ADSC_N8 <- CreateSeuratObject(counts = N8, project = "N8")

ADSC_N5[["percent.mt"]] <- PercentageFeatureSet(object = ADSC_N5, pattern = "^MT-")
ADSC_N7[["percent.mt"]] <- PercentageFeatureSet(object = ADSC_N7, pattern = "^MT-")
ADSC_N8[["percent.mt"]] <- PercentageFeatureSet(object = ADSC_N8, pattern = "^MT-")

###outlierFinder

outlierFinder <- function(data){
  lowerq = quantile(data)[2]
  upperq = quantile(data)[4]
  iqr = upperq - lowerq
  mild.threshold.upper = (iqr * 1.5) + upperq
  mild.threshold.lower = lowerq - (iqr * 1.5)
  return(c(mild.threshold.lower,mild.threshold.upper))
}

gene<- outlierFinder(ADSC_N5@meta.data$nFeature_RNA)
umi<- outlierFinder(ADSC_N5@meta.data$nCount_RNA)
mt_pc<-outlierFinder(ADSC_N5@meta.data$percent.mt)

ADSC_N5 <- subset(ADSC_N5, subset = nFeature_RNA > gene[1] & nFeature_RNA < gene[2] &
                  nCount_RNA > umi[1] & nCount_RNA < umi[2] 
                  & percent.mt > mt_pc[1] & percent.mt < mt_pc[2])

gene<- outlierFinder(ADSC_N7@meta.data$nFeature_RNA)
umi<- outlierFinder(ADSC_N7@meta.data$nCount_RNA)
mt_pc<-outlierFinder(ADSC_N7@meta.data$percent.mt)
ADSC_N7 <- subset(ADSC_N7, subset = nFeature_RNA > gene[1] & nFeature_RNA < gene[2] &
                    nCount_RNA > umi[1] & nCount_RNA < umi[2] 
                  & percent.mt > mt_pc[1] & percent.mt < mt_pc[2])

gene<- outlierFinder(ADSC_N8@meta.data$nFeature_RNA)
umi<- outlierFinder(ADSC_N8@meta.data$nCount_RNA)
mt_pc<-outlierFinder(ADSC_N8@meta.data$percent.mt)
ADSC_N8 <- subset(ADSC_N8, subset = nFeature_RNA > gene[1] & nFeature_RNA < gene[2] &
                    nCount_RNA > umi[1] & nCount_RNA < umi[2] 
                  & percent.mt > mt_pc[1] & percent.mt < mt_pc[2])

###cell cycle
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

ADSC_N5 <- CellCycleScoring(object = ADSC_N5, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

ADSC_N7 <- CellCycleScoring(object = ADSC_N7, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

ADSC_N8 <- CellCycleScoring(object = ADSC_N8, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

ADSC_N5<- SCTransform(object = ADSC_N5, vars.to.regress = c("percent.mt","S.Score", "G2M.Score"), verbose = FALSE)
ADSC_N7 <- SCTransform(object = ADSC_N7, vars.to.regress = c("percent.mt","S.Score", "G2M.Score"), verbose = FALSE)
ADSC_N8 <- SCTransform(object = ADSC_N8, vars.to.regress = c("percent.mt","S.Score", "G2M.Score"), verbose = FALSE)

ADSC_N5$stim <- "N5"
ADSC_N7$stim <- "N7"
ADSC_N8$stim <- "N8"

ADSC.anchors <- FindIntegrationAnchors(object.list = list(ADSC_N5, ADSC_N7,ADSC_N8), dims = 1:20)
ADSC.combined<- IntegrateData(anchorset = ADSC.anchors, dims = 1:20)

DefaultAssay(object = ADSC.combined) <- "integrated"

### Run the standard workflow for visualization and clustering
ADSC.combined <- ScaleData(object = ADSC.combined, vars.to.regress = c("percent.mt","S.Score", "G2M.Score"),verbose = FALSE)
ADSC.combined <- RunPCA(object = ADSC.combined, npcs = 30, verbose = FALSE)
### t-SNE and Clustering
ADSC.combined <- RunUMAP(object = ADSC.combined, reduction = "pca", dims = 1:20)
ADSC.combined <- FindNeighbors(object = ADSC.combined, reduction = "pca", dims = 1:20)
ADSC.combined <- FindClusters(ADSC.combined, resolution = 0.5)
pdf("umap.pdf")
p1 <- DimPlot(object = ADSC.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(object = ADSC.combined, reduction = "umap", label = TRUE, group.by = "celltype")
plot_grid(p1, p2)
dev.off()

**Comment by satijalab** [comment]
Please see https://github.com/ChristophH/sctransform/issues/4 for a discussion on combining SCTransform with v3 integration. This is not fully supported yet, but we will be releasing new functionality in the future
