### ISSUE TITLE
How to export UMAP data for 10X Loupe Cell Browser?

### ISSUE THREAD

**Issue by akiokoba** [satijalab/seurat#1391]
How can I export UMAP projection data (barcodes, X coordinates and Y coordinates) of Seurat objects in the CSV format? We would like to import the Seurat UMAP data into 10X Loupe Cell Browser v3.1. 

10X Loupe Cell Browser v3.1 says:
The CSV format for importing projections is as follows:
- header is required
- first column: barcodes that are at least a subset of the barcodes in the .cloupe file
- second column: numbers which represents the X coordinates
- third column: numbers which represents the Y coordinates

**Comment by satijalab** [comment]
Please see https://satijalab.org/seurat/v3.0/dim_reduction_vignette.html for a detailed discussion on how to extract dimensional reduction coordinates from a Seurat object

**Comment by xjyang01** [comment]
Does this work?

**Comment by akiokoba** [comment]
The following worked with Seuart v2 for UMAP plots in the Loupe Cell Browser.
write.csv(Seura_object_name@dr$umap@cell.embeddings, file = paste("File_name.csv",sep=""))

**Comment by xjyang01** [comment]
Thanks. I will test it. Have you tried data from other packages such as Scanpy as well?

**Comment by tilofreiwald** [comment]
Hi, to export UMAP embeddings from Seurat v3 to Loupe Cell Browser v4 this works for me:
````R
umap = cbind("Barcode" = rownames(Embeddings(object = seu, reduction = "umap")), Embeddings(object = seu, reduction = "umap"))
write.table(umap, file="./write/umap_rna.csv", sep = ",", quote = F, row.names = F, col.names = T)
````

**Comment by latestgo** [comment]
@tilofreiwald Hello, I tried your code. The Loupe Cell Browser v4 needs cloupe file. I can't import csv file in Loupe Cell Browser.
