### ISSUE TITLE
integrated (or ‘batch-corrected’) expression matrix for all cells

### ISSUE THREAD

**Issue by penglbio** [satijalab/seurat#1392]
I also have a same question about the batch-corrected gene expression matrix. If I want plot one gene expression level. But there is just 2000 corrected genes expression value, and there are also include negitive and postive value. How can I do the Featureplot() with the gene which I want to check by the Integated gene expression value?

**Comment by satijalab** [comment]
It is difficult to understand your question, but in general we suggest using the corrected data to perform dimensional reduction and clustering, but you can visualize gene expression using data from the RNA assay. We demonstrate this here : https://satijalab.org/seurat/v3.0/immune_alignment.html
