### ISSUE TITLE
Should I RegressOut cellcycle and percent.mt before ingeration analysis

### ISSUE THREAD

**Issue by penglbio** [satijalab/seurat#1393]
If I have 3 samples of 10x scRNAseq data. Before I integate them, should I first RegressOut the effects of cell cycle and percentage.mito, liking running the following command  each sample separetely? :
ScaleData(object = Data.combined,vars.to.regress = c("percent.mt","S.Score", "G2M.Score") verbose = FALSE,do.scale=FALSE,do.center=FALSE)?

**Comment by satijalab** [comment]
You should be able to regress out either before or after integration. We have not actually tested the two options, but if you do, I'd be curious to hear how they worked for you.

**Comment by dwucsf** [comment]
@penglbio, how did this work out for you? I'm curious, as I am trying to do this now.

**Comment by xmc811** [comment]
Based on our observation, the @scale.data in $RNA is removed after integration, so you'll need to do ScaleData after integration anyway, and the results will be stored in $integrated.
https://github.com/satijalab/seurat/issues/1607#issuecomment-497816994
