### ISSUE TITLE
Is there a way to annotate only selected genes using DoHeatmap function?

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#1395]
Is there a way to annotate only some genes while removing other genes used to plot the heatmap?

**Comment by andrewwbutler** [comment]
Hi,

You can select which genes to plot in the heatmap with the `features` argument. If you're asking how to only label certain genes, that can be handled via ggplot. One way of doing that might be something like:

```R
# replace all.genes with the genes you want in the heatmap
all.genes <- VariableFeatures(object = pbmc_small)[1:10] 
# replace genes.to.label with genes you want to be labeled
genes.to.label <- sample(x = VariableFeatures(object = pbmc_small)[1:10], size = 5) 
labels <- rep(x = "transparent", times = length(x = all.genes))
labels[match(x = genes.to.label, table = all.genes)] <- "black"

DoHeatmap(object = pbmc_small, features = all.genes) +
  theme(axis.text.y = element_text(color = rev(x = labels)))
```

**Comment by kaizen89** [comment]
Yes, that's almost what I was looking for. But do you think it is possible to add lines like in this example? https://jokergoo.github.io/ComplexHeatmap-reference/book/heatmap-annotations.html#mark-annotation
Thanks

**Comment by andrewwbutler** [comment]
I'm not sure what would be the best way to add lines like that. You might look into the [ggrepel package](https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html).  Alternatively, if you really want the plot to look like the example, it might be less work to just pull out the matrix and plug it into that function from the ComplexHeatmap package.

**Comment by kaizen89** [comment]
I already looked into ggrepel, didn't manage so far. I am now using ComplexHeatmap.
Thanks

**Comment by andynkili** [comment]
@andrewwbutler,

I tried your solution which is close to mine:
```
indices<-match(specific_genes),all_genes)
labels = rep("",length(all_genes))
labels[indices] = all_genes[indices]
labels[is.na(labels)] <- ""
DoHeatmap(seurat_obj, features = all_gene,size = 4)+scale_y_discrete(labels=rev(labels))
```

But in both cases, it doesn't work.
It seems like the indices from the Y axis are shifted up.
Do you have any suggestions?

Best,
Andy
