### ISSUE TITLE
Using metadata in FeaturePlot in v3

### ISSUE THREAD

**Issue by limpbizkit6** [satijalab/seurat#1396]
I'm trying to do something similar to #938 . I'm very new to Seurat and R so apologies for my ignorance.

I have a dataset with 9 different conditions, the identifier which I've loaded from the meta data into 'orig.ident'. After performing the Seurat workflows I can plot the entire set using DimPlot, or I can even show each sample as a separate plot using Dimplot (object = x, ... , split.by = 'orig.ident'). The problem is when all 9 samples are overlaid onto the UMAP projection, it becomes hard to see the bounds or extent of each condition within the projection and when I use split.by in Dimplot, it does not show each condition overlayed against the entire set, which is difficult for comparison purposes. 

My goal is to show what part of the entire UMAP projection is made up by each one of my orig.ident variables. I think this most closely aligns with FeaturePlot in which I can have each orig.ident variable highlighted against a background of the entire dataset in a 3x3 array of plots to show each variable. Using the helpful suggestion above I've tried to do the following to plot just one of the conditions. 

My first attempt using orig.ident is unsuccessful
FeaturePlot(object, features = c("orig.ident"), split.by = 'orig.ident')

Then trying to subset the data: 
variable1 = subset(x= object, subset = orig.ident =="variable1")
FeaturePlot(object, features=  variable1
This results in R becoming non responsive. 

I can separate this into: 
variable1 = subset(x= object, subset = orig.ident =="variable1")
where I get a seurat object made up of just variable1-- though I'm not sure if a Seurat object can be used as a feature in FeaturePlot? 

Even if I can get this to work, I'm not sure of the best way to iterate through all of my samples other than doing it manually. I'm not sure if the split.by operator would work for my purposes here?

**Comment by andrewwbutler** [comment]
No a Seurat object can't be used as a feature in `FeaturePlot`. I think what you're looking for here is the `cells.highlight` parameter in `DimPlot`. For example:

```R
DimPlot(
  object = object, 
  cells.highlight = WhichCells(object = object, expression = orig.ident == "variable1"
)
```

You can then just loop over `orig.ident`, storing the plots in a list which you can pass to `CombinePlots` to get your 3x3 array.

```R
plot.list <- list()
for (i in unique(x = object$orig.ident)) {
  plot.list[[i]] <- DimPlot(
    object = pbmc_small, 
    cells.highlight = WhichCells(object = pbmc_small, expression = orig.ident == i)
  ) + NoLegend() + ggtitle(i)
}
CombinePlots(plots = plot.list, ncol = 3)
```

**Comment by limpbizkit6** [comment]
Perfect, thank you!!
