### ISSUE TITLE
marker gene list is shorter when using SCTranform normalization method

### ISSUE THREAD

**Issue by ysu2015** [satijalab/seurat#1397]
Hi,

I am trying to use the new normalization method "SCTransform" for data normalization and scale. A major impression is that compared to the "standard workflow", the gene list is much shorter. Is that reasonable to use the SCTransform for clustering, but non-scale matrix for marker identify? or use different differential expression gene method will be better?

Y

**Comment by ChristophH** [comment]
Hi,

When running `SCTransform` the 'scale.data' slot of the new assay is by default subset to only variable genes. This can be changed with the `return.only.var.genes = FALSE` argument to `SCTransform`. The 'counts' and 'data' slots are filled for all genes (and are corrected by default).

We have seen good performance when identifying markers based on the output of `SCTransform`, but feel free to try other workflows e.g. clustering using `SCTransform` and marker identification using traditional normalization.

**Comment by ysu2015** [comment]
Thanks a lot for the quick response. 
I am pretty happy to use the V3, a lot of improvements I would said.

**Comment by ysu2015** [comment]
Hi ChristophH,
One more question about the SCTransform assay. When we normalized the data with SCTran, after we got the differential expression genes by using Findmarker function. How do we modify the parameter for DoHeatmap function for data visualization. The "scale.data" slot did not fill. Thanks a lot.

Y
