### ISSUE TITLE
Batch reduction on 6 samples and heatmap of features of integrated data

### ISSUE THREAD

**Issue by hfberg** [satijalab/seurat#1400]
Hi! I would like to integrate multiple datasets, 3 from successful and 3 from unsuccessful patients. (10x, but I'm using their cell_gene_expression matrices).  I have two questions:

1. I want to do a batch reduction. Is there any way I can tell seurat that 3 of the samples are more similar than the other 3. I believe that all of these samples shouldn't be treated equal? Or is that ok? I already have seurat objects for each individual sample.

2. I then want to plot some specific genes in a heatmap and label them with samples (and in the future, also clusters and samples) Like in the picture below. To generate the picture, I used the following code. No other "slots" was accepted by DoHeatmap.

`DoHeatmap(object = DGE.integrated, features = features, slot = "data") + NoLegend()`

However, from the code I understand that the slot data represents object@data in the seurat object, which (I guess) is represented by DGE.integrated@assays[["RNA"]]@data in Seurat3. Is this correct? In that case, am I really using the batch corrected data for the heatmap? or am I using the previous data? Which one should I use?

https://ibb.co/smHz9V0

**Comment by andrewwbutler** [comment]
Hi,

1. Generally, we find the automatically generated sample tree works pretty well and don't tend to manually specify it. One option would be to do separate integrations for each group of patients and then a final integration across the groups. 
Alternatively, we are working on better support for this kind of functionality but currently, you can specify the `sample.tree` manually in `IntegrateData`, which will control the order of integration. It's possible the tree this function generates would be the one you would specify. You can check with `Tool(object = test, slot = "Integration")@sample.tree`. Negative numbers here specify the dataset, positive numbers indicate results of integrating that given row. E.g.
```
-2 -3  # integrate datasets 2 and 3
1, -1 # then integrate the results of row 1 with dataset 1
```

2. After running `IntegrateData`, the default `Assay` is set to the `integrated` `Assay`. This only contains a matrix in the "data" slot, representing the normalized/corrected data (which is probably why you're getting "no other slots were accepted"). By default, what we plot in `DoHeatmap` is "scaled.data", so to visualize the integrated data, I would run `ScaleData` and then try `DoHeatmap` again. If you want to plot the unintegrated data, you can specify `assay = "RNA"` in `DoHeatmap`.

**Comment by hfberg** [comment]
Thank you!

**Comment by linzhangTuesday** [comment]
> Hi,
> 
> 1. Generally, we find the automatically generated sample tree works pretty well and don't tend to manually specify it. One option would be to do separate integrations for each group of patients and then a final integration across the groups.
>    Alternatively, we are working on better support for this kind of functionality but currently, you can specify the `sample.tree` manually in `IntegrateData`, which will control the order of integration. It's possible the tree this function generates would be the one you would specify. You can check with `Tool(object = test, slot = "Integration")@sample.tree`. Negative numbers here specify the dataset, positive numbers indicate results of integrating that given row. E.g.
> 
> ```
> -2 -3  # integrate datasets 2 and 3
> 1, -1 # then integrate the results of row 1 with dataset 1
> ```
> 
> 1. After running `IntegrateData`, the default `Assay` is set to the `integrated` `Assay`. This only contains a matrix in the "data" slot, representing the normalized/corrected data (which is probably why you're getting "no other slots were accepted"). By default, what we plot in `DoHeatmap` is "scaled.data", so to visualize the integrated data, I would run `ScaleData` and then try `DoHeatmap` again. If you want to plot the unintegrated data, you can specify `assay = "RNA"` in `DoHeatmap`.

Hi, Thanks for the wonderful pipeline.

May I ask is it possible to integrate parts of the samples instead of all samples, using a manually specified sample.tree for integration?

For example, 14 samples in total, only integrate 4 of them. As there are different factors (some are batch, some are biological factors of interest) in the data, mixing with each other. We want to keep the biological factors of interest while correct for batch effect for 4 of the samples.

Please let me know if there are any suggestions on that. Thanks!
