### ISSUE TITLE
ScaleData for all features - subscript out of bounds error

### ISSUE THREAD

**Issue by Emmavb1988** [satijalab/seurat#1401]
I have a question on ScaleData. I'm using the new Seurat 3.0 version. 
I've started with the same problem as #1088, where now I indeed get the warning that some of the genes that are not in ScaleData are not included into the heatmap generated by DoHeatmap.

However, when I try to run ScaleData for all the genes that are in my Seurat Object:

all.genes <- rownames(x = myobject)
myobject<- ScaleData(object = myobject, features = all.genes)

I get the following error:

Error in `[<-`(`*tmp*`, features[my.inds], , value = data.scale) : 
  subscript out of bounds

-------------------------------------------------------
Some information on how I created the object:
myobject_raw is a data frame of 36955 rows and 1261 variables

myobject <- CreateSeuratObject(myobject_raw , project = "myproject", min.cells = 0, min.features = 0)
myobject <- NormalizeData(object = myobject , normalization.method = "LogNormalize", scale.factor = 10000, verbose = FALSE)
myobject <- FindVariableFeatures(object = myobject , selection.method = "vst")

myobject

An object of class Seurat 
36955 features across 2197 samples within 1 assay 
Active assay: RNA (36955 features)
 2 dimensional reductions calculated: pca, umap

**Comment by andrewwbutler** [comment]
It doesn't look like there's anything wrong with the code you posted. Are you able to share an object (or downsampled version) that reproduces the issue?

**Comment by Emmavb1988** [comment]
Hi Andrew,

Below the object that gives me the same error when running the code I posted above.
[myobject.zip](https://github.com/satijalab/seurat/files/3117368/myobject.zip)

Thanks a lot in advance!

**Comment by andrewwbutler** [comment]
Ok so it looks like the problem is that the first gene in your object is unnamed. You can verify with

```R
> head(x = rownames(x = myobject))
[1] ""         "A1BG"     "A1BG-AS1" "A1CF"     "A2M"      "A2M-AS1" 
```

If you resolve that in `myobject_raw` matrix before running `CreateSeuratObject`, the code you were trying should work.

**Comment by Emmavb1988** [comment]
Thanks a lot this for spotting that, it works now!

**Comment by Cumol** [comment]
The same error appears when the colnames of the countmatrix are not unique.

generating unique IDs with the stringi package and assigning them to the colnames of the countmatrix solves the issue.

The error message is not very informative. Maybe you could catch those types of errors somehow.

**Comment by andrewwbutler** [comment]
Non-unique cell names (colnames of the counts matrix) shouldn't be allowed when creating the object. 
https://github.com/satijalab/seurat/blob/94343c4fdb35a3a1e7a7e14d4a0bb0cec657075c/R/objects.R#L460-L467

If there's an edge case where you're getting non-unique cell names, we can look into it further if you provide a reproducible example.
