### ISSUE TITLE
FeaturePlot of Average Gene Expression for all Genes

### ISSUE THREAD

**Issue by SyrupBadger** [satijalab/seurat#1402]
Hi,
I have followed your tutorial for calculating the average gene expression for my clusters and produced a nice heat map that shows the difference between the replicates, all good so far.  What I would like to do next is calculate the average gene expression for each cluster across all genes expressed and plot that as a FeaturePlot so I can visualise which clusters in my samples are more active.  Is this possible in Seurat V3?

**Comment by satijalab** [comment]
Apologies that we do not support this in FeaturePlot, which plots cell-specific (and not cluster-specific) expression levels.
