### ISSUE TITLE
gene/gene expression scatter plot

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#1403]
Hi,

I would like to try and make a scatter plot to show whether two genes are co-expressed or mutually exclusive, like in Figure 1D of this paper https://www.nature.com/articles/s41467-018-07540-z.pdf .
In the 10x Loupe 3.x they have something like that but they call it a 'Feature Plot' which makes it hard to find the equivalent thing in Seurat!

Thanks,

Leonard

**Comment by andrewwbutler** [comment]
Hi,

Please see the `FeatureScatter` function in Seurat.

**Comment by lennycheung** [comment]
Thanks!
