### ISSUE TITLE
Further info in doc for DotPlot

### ISSUE THREAD

**Issue by rspreafico** [satijalab/seurat#1404]
Hi there, congrats on Seurat v3! Would it be possible to specify in the docs of DotPlot whether the average expression is computed only on cells that express a gene or whether it's computed across all cells? Since DotPlot also captures the percentage of expression, my expectation is that the average expression excludes negative cells, otherwise the two metrics would be too correlated (more than they are already since the probability of dropout increases with lower expression).

Secondarily, would it be possible to specify from which assay (RNA or SCT) and slot (I guess data) are these metrics derived? (or even better, leave this choice to the user, as in other plotting functions).

Thanks for your consideration!

**Comment by andrewwbutler** [comment]
Hi,

The average expression is computed across all cells here. We've update the docs to hopefully make this a bit clearer. 

There are several ways to specify which assay the feature should come from. 
1. Set the `DefaultAssay` before calling `DotPlot`.
2. Append the assay key to the beginning of the feature name (e.g. `rna_GENE` or `sct_GENE`)

We've now also added an `assay` parameter to specify which assay the features should be pulled from. This essentially just amounts to setting the default assay for all features requested but should be somewhat more convenient.

**Comment by rspreafico** [comment]
Thank you for the rapid additions, that's awesome!

**Comment by davidbmorse** [comment]
Thanks for the great resources Seurat team!

I see in the DotPlot function that avg.exp is taken from log-normalized data which is 'un-log normalized' via the expm1 function.

`avg.exp <- apply(
        X = data.use,
        MARGIN = 2,
        FUN = function(x) {
          return(mean(x = expm1(x = x)))
        }
      )`

Is there a reason why this is done rather than pulling data from the '@counts' slot? 
[~issue1045](https://github.com/satijalab/seurat/issues/1045)
