### ISSUE TITLE
Best approach for integration of large no. samples? Which Assay? 

### ISSUE THREAD

**Issue by lcymcdnld** [satijalab/seurat#1406]
Hello, 

I am really liking the new Seurat release so far but I have a few questions...

1) I have an integrated object which contains 5 groups of different disease conditions. I integrate the samples specific objects within each group to make a condition specific object and then I integrate these objects. Is this the best way to approach this? I have quite a lot of batch affect as my samples were sequenced in different places, at different times but the new integration method seems to work pretty well and I am pleased. However I am concerned I am loosing interesting factors that are different between groups and so I feel like the final integration is unnecessary. I tried doing just a merge() of the already integrated group specific objects.. but the tSNE is really bizare looking. Do you have any suggestions?

2) When performing DE analysis which assay is should I use? - I have RNA, SCT and integrated. When I look at expression of genes of interest using FeaturePlot(), the genes which I found as cluster-specifc markers using the old seurat appear to be expressed at roughly the same level across all cells but SCT assay (which i understand is normalized data) looks more like what I saw previously. 

Much appreciated, 
Lucy

**Comment by andrewwbutler** [comment]
Hi Lucy,

1. The goal of integration is often to identify common cell types in order to then ask what makes them different in different conditions (similar to the analysis in the [PBMC stimulation vignette](https://satijalab.org/seurat/v3.0/immune_alignment.html)). Related to your second question, if you perform DE on the unintegrated data, you won't miss the interesting factors that are different between groups even if you perform the full integration. 

2. Please see [FAQ 4](https://satijalab.org/seurat/faq) for a brief discussion on this. We are working on a more detailed DE vignette that will hopefully clear up some confusion around this point.

**Comment by lcymcdnld** [comment]
Hi Andrew,

Thanks for your response. I had not seen FAQ4 before. When performing differential expression analysis I have being using SCT assay and then plotting on heatmap as integrated assay. Does that sound ok?

Cheers again,
Lucy

On 25 Apr 2019, at 14:14, Andrew Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lucy,

  1.  The goal of integration is often to identify common cell types in order to then ask what makes them different in different conditions (similar to the analysis in the PBMC stimulation vignette<https://satijalab.org/seurat/v3.0/immune_alignment.html>). Related to your second question, if you perform DE on the unintegrated data, you won't miss the interesting factors that are different between groups even if you perform the full integration.

  2.  Please see FAQ 4<https://satijalab.org/seurat/faq> for a brief discussion on this. We are working on a more detailed DE vignette that will hopefully clear up some confusion around this point.

**Comment by satijalab** [comment]
We unfortunately can't advise on what is or is not OK on individual plots - but just be aware that when doing a heatmap of integrated values, they do not represent original measurements, but are batch-corrected.
