### ISSUE TITLE
Different cluster labels in DimPlot of an integrated data set using split.by option

### ISSUE THREAD

**Issue by vbarrera** [satijalab/seurat#1407]
Hi to all the Seurat team and thank you very much for your work on this package.

I am working with a case similar to your vignette (https://satijalab.org/seurat/v3.0/immune_alignment.html) and I am having an issue with the labels in DimPlot using the option `split.by`.

After integrating my two datasets WT and KO as described, and setting the DefaultAssay as:

```DefaultAssay(object = cardio.combined) <- "integrated"
# Run the standard workflow for visualization and clustering
cardio.combined <- ScaleData(object = cardio.combined, verbose = FALSE)
cardio.combined <- RunPCA(object = cardio.combined, npcs = 30, verbose = FALSE)
# t-SNE and Clustering
cardio.combined <- RunUMAP(object = cardio.combined, reduction = "pca", dims = 1:20)
cardio.combined <- RunTSNE(object = cardio.combined, reduction = "pca",dims = 1:20)
cardio.combined <- FindNeighbors(object = cardio.combined, reduction = "pca", dims = 1:20)
```
I do apply FindClusters and plot them:
```
cardio.combined <- FindClusters(cardio.combined, resolution = 0.6,  verbose = FALSE)
DimPlot(object = cardio.combined, reduction = 'tsne', split.by = "GT", label = TRUE)
```
The problem is that although each subplot has the same shape (except for the cell density) and colors, the cluster labels are moved or assigned to other clusters. Due to the treatment, some clusters have almost disappeared in one of the conditions(desired effect). I'm not sure if this is the cause.

I've checked without the `split.by` option and the resulting plot is one of the subplots. Related to this, which id is then assigned to each cell in the combined object?

Thank you very much in advance.

**Comment by andrewwbutler** [comment]
Hi,

I'm not sure exactly what your first question is but if you want to verify that `split.by` is working properly, you can always split the object yourself into the two conditions (using `subset`) and do separate `DimPlots` on the resulting subset objects. 

You can get the current ids of the cells with the `Idents` function. E.g.

```R
Idents(object = object)
```

**Comment by vbarrera** [comment]
Hi Andrew,

Thank you very much for your answer.

Using your suggestion, I've checked the combined and the independent objects and split.by is working correctly. 
The label repositioning is caused by a decrease in the number of cells in one of two subsets of dots for the same cluster. A I assume the label is located near the highest density section of one cluster, when the density of cells in one subset is reduced, the label was repositioning. I wasn't seen it initially due to the color gradient.
This is an issue specific to my analysis and not a problem with Seurat.

Thank you very much for your help.

I'm closing the issue as solved.
