### ISSUE TITLE
General question about dispersion plot/highly variable genes

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1410]
For the genes that show up in dispersion plot, I was wondering how exactly is "variance.standardized" calculated here?

I calculated the variance-to-mean ratio but that's a different value than "variance.standardized" so I'm curious about how it gets to those values.

Secondly, is there a threshold set by default to define a gene as highly variable? My concern is that each gene would likely have some biological variability from cell-to-cell so how is the threshold set?

**Comment by andrewwbutler** [comment]
Hi,

You can checkout this [preprint](https://www.biorxiv.org/content/10.1101/460147v1) (Methods section - Data preprocessing - Feature selection for individual datasets)  for a detailed description of how this is calculated. The relevant code can be viewed here https://github.com/satijalab/seurat/blob/868646df677f3680177fff6d2b9869ebc40499b9/R/preprocessing.R#L1333-L1359

Generally, when selecting features using this method, we choose the top N features ranked by `variance.standardized`.
