### ISSUE TITLE
createseuratobject problems

### ISSUE THREAD

**Issue by arararararararar8** [satijalab/seurat#1411]
Hello,

I am currently using Seurat v2.3.3. I have an error with createseurat object.

Here are two pieces of code that are giving me errors:
1. 
```R
pbmc.data <- Read10X(data.dir = "C:/Users/aishw/Documents/R/project/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

**Error in new(Class = "seurat", raw.data = raw.data, is.expr = is.expr,  : 
  argument "raw.data" is missing, with no default**
```
2. 
```R
meta_ss2 = read.table("E-MTAB-6678_arrayexpress_ss2_meta.txt", sep="\t", header = T, check.names = F, comment.char = "", stringsAsFactors = F)
expr_matrix <- read.table("raw_data_ss2.txt", sep="\t", header=T, check.names = F, comment.char = "", stringsAsFactors = F)

data_all1 <- CreateSeuratObject(raw.data = expr_matrix, min.cells = 3, min.genes = 200, project = "SS2")

**Error in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn,  : 
  length of 'dimnames' [2] not equal to array extent**
```

**Comment by andrewwbutler** [comment]
Hi,

1.  It looks like you're using code examples from the v3.0.0 tutorials which are not compatible with version 2 of Seurat. You can switch between vignette versions with the red box in the lower right of the screen. 
2. Can you verify that `expr_matrix` has unique features as rownames and unique cell names as column names?

**Comment by satijalab** [comment]
Please check out our pbmc3k vignette on the website (you can access the v2 version by clicking the red box on the right-hand corner) for the proper command and arguments for CreateSeuratObject
