### ISSUE TITLE
The difference in mitochondrial gene ratio between the two groups is too large

### ISSUE THREAD

**Issue by LHXANDY** [satijalab/seurat#1412]
I want to do CCA analysis on the two groups of single-cell sequencing results, but I found that the proportion of mitochondrial genes in one group was only about 10%, while the other group was 50%. So how should I choose the range of mitochondrial genes? Are they all set to 10%, or 10% and 50%?
Many thanks.

**Comment by andrewwbutler** [comment]
I'm not sure I understand your question. Generally, we filter cells with a higher percentage of reads mapping to mitochondrial genes as this can be an indicator of low-quality / dying cells. The exact threshold is likely going to depend on the system/dataset you're working with.

**Comment by LHXANDY** [comment]
Thank you very much
I follow the official website tutorial for CCA processing, and the results are grouped, but there is no significant difference in the position of the TSNE map, and the gene thermogram has no cluster-specific high expression gene. In this case, is it reliable?
![cluster](https://user-images.githubusercontent.com/49830970/56567141-dca20580-65e6-11e9-91a0-cfef0129c383.png)
![heatmap](https://user-images.githubusercontent.com/49830970/56567155-e1ff5000-65e6-11e9-87ed-cf311b6b12e3.png)
Thanks

**Comment by andrewwbutler** [comment]
Unfortunately, we can't provide that level of individual guidance on any particular analysis. I would recommend looking into the genes that are markers for your clusters and if they make sense biologically. On a surface level, it looks like clusters 3 and 4 have distinct gene expression programs but it's hard to say much without knowing the genes/system.
