### ISSUE TITLE
working with both versions

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#1413]
I've installed Seurat3. However, I still need Seurat2 for consistency of my project. Is there a way I can selectively load Seurat2 or 3? Or has Seurat3 overwritten Seurat2 after installation?

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Unfortunately you can't have both installed to the same library location simultaneously. If you want to reinstall v2, see the instructions [here](https://satijalab.org/seurat/install.html#previous). 

One option is to install them to different library locations. Here's a [blog post](https://hansjoerg.me/2018/03/06/multiple-package-versions/) that goes into a bit more detail on that.
