### ISSUE TITLE
Not enough colors for the number of groups

### ISSUE THREAD

**Issue by MichaelPeibo** [satijalab/seurat#1414]
Hi, Seurat team

I am using DotPlot in v3. I have a object made up by 3 groups of sample.
When I did DotPlot of certain genes, `split.by`=`groups`, it gave me the error that: 

> Not enought colors for the number of groups

Is two more groups spliting not available?

Thanks!

**Comment by andrewwbutler** [comment]
If you want to split by more than two groups, you'll also need to provide as many colors as you have groups to the `cols` parameter.

**Comment by MichaelPeibo** [comment]
Great! It works! Thanks!
