### ISSUE TITLE
Question about the 12-HTO dataset

### ISSUE THREAD

**Issue by xhongyi** [satijalab/seurat#1415]
It seems that the 12-HTO dataset is not pre-processed.

May I ask roughly how many cells are loaded per HTO sample and what is the estimated capture rate?

I want to know how many cells is loaded for hashing so it will help guide our own cell hashing experiment.

Thank you!

**Comment by satijalab** [comment]
Please do check out the Cell Hashing manuscript (Stoeckius, Zheng et al, Genome Biology 2018) which contains all of these details.

**Comment by xhongyi** [comment]
Hi, I have thoroughly read the Genome Biology paper. However, it does not describe the experiment setup for the 4-cell-line 12-HTO cell hashing experiment.

It does include the description for the 8-HTO PBMC cell hashing experiment. The online 12-HTO dataset contains more than 50K active barcodes. It seems like to be just raw data without any pre-processing.

Would be great if we can compare the 2 HTO experiments and decide which setting is more suited for our experiment.
