### ISSUE TITLE
meaning of FindIntegrationAnchors

### ISSUE THREAD

**Issue by hfberg** [satijalab/seurat#1416]
Hi! For the same dataset I've ran FindIntegrationAnchors with values: 50, 2000 and 5000. I thought the integration and batch effect reduction would be better with a larger reference, but it looks like the opposite is happening. How come? Does this mean that I should use a lower value on FindIntegrationanchors? 

No batch removal
https://ibb.co/KqQ0CbZ

Anchor = 50
https://ibb.co/YDjpTjs

Anchor = 2000
https://ibb.co/xFjzwNx

Anchor = 5000
https://ibb.co/0DhQHnT

**Comment by andrewwbutler** [comment]
Can you post the code you're running? Couple other questions:

1. By `Anchor` do you mean `anchor.features`? 
2. What do you mean by "larger reference"? Are you changing the dataset you're using between runs? 
3. Do you expect all of the same cell types in each dataset?

**Comment by hfberg** [comment]
Hi @andrewwbutler 
I would run a code looking something like this:

`# Merge samples analyze seurat
devtools::load_all("~/dftoolz")
library(Seurat)
setwd("/home/proj/process")

raw<- dftoolz::DGE_load("C25+CP1+CP25")
annot<-dftoolz::annot_load("C25+CP1+CP25", samp = T)

DGE<-CreateSeuratObject(counts = raw, meta.data = annot)

DGE.list <- SplitObject(object = DGE, split.by = "samp.name")

for (i in 1:length(x = DGE.list)) {
  DGE.list[[i]] <- FindVariableFeatures(object = DGE.list[[i]], selection.method = "vst", nfeatures = 2000, verbose = FALSE)
}

#Find anchors

reference.list <- DGE.list[c("C25", "CP1", "CP25")]

> DGE.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:15, anchor.features = 50)
> DGE.integrated <- IntegrateData(anchorset = DGE.anchors, dims = 1:15)
> DGE.integrated <- RunTSNE(object = DGE.integrated, reduction = "pca", dims = 1:15, check_duplicates = FALSE)
> DimPlot(object = DGE.integrated, reduction = "tsne", group.by = "samp.name")`

1. yes

2. sorry, that was sloppy of me. With larger reference I mean the size of anchor.features. I am not changing my dataset between runs.

3. The samples are all from the same, untreated, tissue, so except for some batch effects I'm expecting the same cell types.

**Comment by satijalab** [comment]
I apologize that we can't debug this individual example, but in general we do not recommend reducing this to looking at only 50 genes. In our preprint describing this approach, we use default parameters for anchor.features in all analyses.
