### ISSUE TITLE
Switching dot color in DimPlot (conditions)

### ISSUE THREAD

**Issue by bikohcello** [satijalab/seurat#1417]
Hi! I'm trying to switch the color of my dots/points between the two conditions I've set. I know how to set standard colors, but I'm trying to find the default colors (the light red and the turquoise) to just switch between the two...Any way to do this the easy way? Thank you!

**Comment by andrewwbutler** [comment]
Hi,

To change the colors in `DimPlot`, you can use the `cols` parameter and provide a vector of colors. E.g.

```R
DimPlot(object = pbmc_small, cols = c("purple", "yellow", "orange"))
```

**Comment by shendong124** [comment]
Hi, I have tried cols:
DimPlot(mergetest2.big, reduction = "umap", group.by = "orig.ident", cols = ("red", "grey", "blue"))

here is the error message:
Error: unexpected ',' in "DimPlot(mergetest2.big, reduction = "umap", group.by = "orig.ident", cols = ("red","

thank you for your help

**Comment by Connorr0** [comment]
Hey I don't know if this is still useful to you, but I think you are missing a c. in R to define a list I think you need to do c(..., ..., ...) so you should try:

DimPlot(mergetest2.big, reduction = "umap", group.by = "orig.ident", cols = c("red", "grey", "blue"))
