### ISSUE TITLE
SCTransform DoHeatmap plot

### ISSUE THREAD

**Issue by ysu2015** [satijalab/seurat#1418]
Hi ChristophH,

One question about the SCTransform assay. When we normalized the data with SCTran, after we got the differential expression genes by using Findmarker function. How do we modify the parameter for DoHeatmap function for data visualization. The "scale.data" slot did not fill and I still trying to plot the both up and down changes not just the counts. Thanks a lot.

Y

**Comment by ysu2015** [comment]
Does anyone experience the same issue?

**Comment by satijalab** [comment]
SCTransform automatically fills the scale.data slot in the SCT assay. You can test this for yourself by trying our SCTransform vignette on the website, and plotting a heatmap for the pbmc3k dataset.
