### ISSUE TITLE
finding distance between UMAP clusters

### ISSUE THREAD

**Issue by csennis** [satijalab/seurat#1419]
Hello!  I am new to Seurat and am currently trying to calculate the distance between UMAP clusters (meaning 1:2, 1:3, 2:3, etc).  

I believe this used to be done by using the get.centroids() command in previous versions of Seurat, but it has since been deprecated.  Currently, my plan is to calculate the average expression per gene for each cluster, then determine the euclidean distance between the clusters using that metric.  

However, I would love to know if there is another/better way to accomplish this.  Thank you!

**Comment by andrewwbutler** [comment]
Hi,

You can access the UMAP coordinates with `Embeddings(object = object[["umap"]])`. To calculate the centroids, you just need to average the coordinates for the cells in each cluster. Whether the exact distances in UMAP space are interpretable is a different question and I would direct you this [post](https://github.com/lmcinnes/umap/issues/92) some further discussion.
