### ISSUE TITLE
JoyPlot can't plot certain genes

### ISSUE THREAD

**Issue by symbiologist** [satijalab/seurat#142]
Hi Seurat team,

I've been using the new JoyPlot function, which is fantastic. However I've noticed that it throws an error when trying to plot certain genes.

Using the data from this vignette: http://satijalab.org/seurat/Seurat_AlignmentTutorial.html

This line leads to the following error:

JoyPlot(pbmc, 'MT-ND2')

Error in `[.data.frame`(data.use, , x, drop = FALSE) : 
  undefined columns selected

I've noticed that this error only occurs when plotting genes with dashes in the gene name (e.g. mitochondrial genes, antisense lncRNAs) as well as gene names that start with numbers (Rik genes in mouse data). It seems to have no problems with any other genes and it does not seem to depend on the expression level of the gene.

Thanks!

David

**Comment by leonfodoulian** [comment]
Please refer to [issue 111](https://github.com/satijalab/seurat/issues/111).

Best,
Leon

**Comment by symbiologist** [comment]
Aha, thanks! Looks like it that was it.

Best,

David
