### ISSUE TITLE
Analysis for Single Cell ATAC-seq

### ISSUE THREAD

**Issue by xhbkirby** [satijalab/seurat#1422]
Hi,

Can I use Seurat to analyze single cell ATAC-seq data generated by the 10x Chromium scATAC-seq platform (with raw sequencing reads first processed by Cell Ranger)? I know Seurat can process scRNA-seq data from 10x platform but not sure if it can also process scATAC-seq. Thanks!

**Comment by satijalab** [comment]
Not at the moment (or at least not effectively), but stay tuned!

**Comment by davisidarta** [comment]
Hello @satijalab ! Has any development been made in this aspect? I'm working in a large scRNAseq meta-analysis and it would be extremely interesting to merge scRNAseq data and ATACseq data.
