### ISSUE TITLE
New batch correction method and DE on corrected values

### ISSUE THREAD

**Issue by hkarakurt8742** [satijalab/seurat#1423]
Hello,
Thank you for the new version. I have a question about the batch correction. I have seen Seurat still uses CCA for batch correction and we obtain a corrected expression matrix. The matrix have negative values as expected.
So, If we want to do a DE analysis between batches (e.g. healthy vs. disease with replicates), is it proper to use these corrected values with statistical tests like Wilcoxon rank sum or should we use methods such as DESeq2, EdgeR or DESingle on uncorrected counts matrix?

Thank you in advance.

**Comment by andrewwbutler** [comment]
Hi,

You should use the uncorrected/"unintegrated" values for your differential expression tests. This is primarily because the integration procedure inherently introduces dependencies between data points that would violate the assumptions of those statistical tests.

**Comment by irmed** [comment]
Hi! I have a question related to this too. As far as I understand, when doing clustering after CCA, CCs are used for SNN, but then modularity algorithm like _louvain_ is applied and distance matrix is calculated. Does any algorithm apply expression matrix as an input on any step? (it is Seurat v2)

**Comment by satijalab** [comment]
The neighbor graphs are calculated on the aligned CCs. The expression matrix is not an input (of course, it is used to calculate the CCs themselves).
