### ISSUE TITLE
Error in RunTSNE: too big perplexity

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#1424]
I ran _RunTSNE_ on a 31-cell dataset of 5,583 genes and it threw the following error:

Error in .check_tsne_params(nrow(X), dims = dims, perplexity = perplexity,  : 
  perplexity is too large for the number of samples

PCA dimensionality reduction with 30 PCs finds two cell clusters and I assume the error has to do with that.  Since I cannot change the perplexity of the tSNE in the _RunTSNE_ function, can anyone recommend a way around this error so that I can visualise my data?

**Comment by andrewwbutler** [comment]
Hi,

You can pass the `perplexity` parameter through the dots (`...`) in `RunTNSE`. 
> ...  Arguments passed to other methods and to t-SNE call (most commonly used is perplexity)

E.g.

```R
RunTSNE(object = object, dims = 1:30, perplexity = X)
```
