### ISSUE TITLE
Changing colors in split VlnPlot

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#1425]
Hello,

I can't seem to get the colors to change in violin plots when a split plot is used.

This is the default color scheme:

```
plots <- VlnPlot(object = combined, features = c("Arg1", "Tnf"), split.by = "group", group.by = "active.ident", pt.size = 0, combine = FALSE, log=T)
```

![image](https://user-images.githubusercontent.com/38366155/56595813-8b752000-65ac-11e9-9a45-085692cf6370.png)

Here is the code I try to change the colors of both groups:

```
plots <- VlnPlot(object = combined, features = c("Arg1", "Tnf"), split.by = "group", group.by = "active.ident", pt.size = 0, combine = FALSE, log=T, cols=c("red", "black"))

# > the condition has length > 1 and only the first element will be used
```

I have two samples in a combined Seurat object (group metadata variable). When I pass the character vector as `c("red", "black")`, it changes the color of a single data group. and the second groups seems to change color randomly:

![image](https://user-images.githubusercontent.com/38366155/56595948-d0995200-65ac-11e9-8eae-d1b9a6b39955.png)
 

Another curious point here: `group` metadata variable is a factor with ordered levels `WT` and `KO` respectively. But in the `VlnPlot` code, the color of the `KO` group changes reminiscent of factor reordering (due to alphabetical prioritization of `KO` over `WT`). Can you help me understand how I can change the color of both groups and without the internal(?) reordering of the factor levels?

Thanks

**Comment by mojaveazure** [comment]
Hi Atakan,

Thanks for bringing this up. This is a bug in `VlnPlot`. For now, you can add colors after the fact with `scale_fill_manual`

```R
plots <- VlnPlot(object = combined, features = c('Arg1', 'Tnf'), split.by = 'group', pt.size = 0, combine = FALSE, log = TRUE)
plots <- lapply(
  X = plots,
  FUN = function(p) p + ggplot2::scale_fill_manual(values = c('red', 'black'))
)
CombinePlots(plots = plots, legend = 'right')
```

**Comment by atakanekiz** [comment]
Thanks for the help!

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by lcymcdnld** [comment]
Is there any way to add different combinations for WT/KO for each cluster? I was wantign to colour by cluster but include darker/lighter version of that cluster for the appropriate split violin. Any ideas?

Cheers,
Lucy

**Comment by stephanyfoster** [comment]
hello-

I'm making Vlnplots for an integrated object, 8 objects integrated and 22 clusters total. My vlnplot for a gene shows expression for each of the 8 conditions but three of the objects are shown in blue, it's difficult to differentiate. I tried to manually add colors but I got an error (need 22 colors). Is there a way to change this without manually imputing 22 colors?

![Screen Shot 2020-02-06 at 11 10 07 AM](https://user-images.githubusercontent.com/43393591/73955594-985fc780-48d1-11ea-8ed4-6045735cb312.png)

**Comment by CroixJeremy2** [comment]
Hello,
Just an additional comment. In my code, I have noticed that the bug [that wrong colors are applied even if specified in the cols= option within VlnPlot()] appears when VlnPlot() is located AFTER that scale_fill_manual() is used in an other plot.

I mean:
plot1 = VlnPlot(cols = ...) # no problem
plot2 = VlnPlot(cols = ...) # no problem
plot3 = VlnPlot(cols = ...) # no problem
plot3 = "whatever_plot" + scale_fill_manual(values = ...) #no problem
plot4 = VlnPlot(cols = ...) # PROBLEM, the colors in cols= are not the ones asked
plot5 = VlnPlot(cols = ...) # PROBLEM, the colors in cols= are not the ones asked
plot6 = VlnPlot(cols = ...) # PROBLEM, the colors in cols= are not the ones asked

I am not a developer, but I guess it could come from a conflict when scale_fill_manual() is loaded from the ggplot2 package that then leads to conflicts with VlnPlot().

Anyway,  using:
plot4 = VlnPlot() + scale_fill_manual(values = ...)
solves the problem, thus from now on, I will only use scale_fill_manual(values = ...) to set my colors with VlnPlot() as it will always work

Cheers,
