### ISSUE TITLE
sctransform reached iteration limit, problem rendering Rmarkdown reports

### ISSUE THREAD

**Issue by lc822** [satijalab/seurat#1426]
Hi,

Thank you for developing Seurat - it is very useful package.  I am having a couple of issues with Seurat 3.0.0 that I was hoping you could help me to address.  Sorry if the questions are naïve – I am quite new to bioinformatics.

1.    In the previous version of Seurat, I was able to render Rmarkdown files to html.  However, with the new Seurat version, I am getting the following error:

`Quitting from lines 297-299 (4-genes_and_TCR_samples_without_CD3.Rmd)` 
`Error in [[.Seurat (object, reduction) : `
  `Cannot find 'rmarkdown::render' in this Seurat object`
`Calls: <Anonymous> ... do.call -> DimPlot -> Embeddings -> [[ -> [[.Seurat`
`Execution halted`

The line is quits on is:
`sample <- RunTSNE(object = sample, dims = 1:30)    # Should use same number of PCs as for finding clusters`
`TSNEPlot(object = sample)`

What does this error mean?

2.    I am using the sctransform package for normalization and identifying highly variable genes.  However, I get the following warning (repeated many times e.g. 50) when I run the sctransform command in Seurat:
`iteration limit reached`

What does this mean and how can I prevent it from happening?  

3.    Does sctransform remove some genes from the matrix during the normalization process?  The reason that I ask this is because when I am using DoHeatmap to plot genes that were identified as cluster markers by FindAllMarkers, I get the following error message for several genes:
`The following features were omitted as they were not found in the scale.data slot for the SCT assay: LDHB`

Many thanks,
Lucy

**Comment by andrewwbutler** [comment]
Hi Lucy,

1. Can you share the .Rmd file? 

2. Please see #1378 

3. You can set `return.only.var.genes = FALSE` to return all genes from the `SCTransform` function.

**Comment by w2niva** [comment]
Hi,
I have a similar issue. I am just doing CCA and I am unable to knit my file. I am very new to R so it could be something that I am unaware of and doing wrong.
[CCA_Mated_1.zip](https://github.com/satijalab/seurat/files/3122482/CCA_Mated_1.zip)

**Comment by satijalab** [comment]
I apologize that we can't debug RMD issues outside of Seurat, due to the volume of issues received here.

2. This can happen when you have data that is extremely sparse, or for whatever reason cannot be fit well by a negative binomial. There's nothing you can do to prevent it unfortunately.

3. See andrew's answer

**Comment by lc822** [comment]
Hi,

Thank you for the response.  Please find attached the Rmd file that gives me the following error when I run R Markdown render.

Quitting from lines 297-299 (4-genes_and_TCR_samples_without_CD3.Rmd)
Error in [[.Seurat (object, reduction) :
Cannot find 'rmarkdown::render' in this Seurat object
Calls: <Anonymous> ... do.call -> DimPlot -> Embeddings -> [[ -> [[.Seurat
Execution halted

Relating to question 3, if a gene is not identified as variable by sctransform, how can it come up as a top 10 cluster marker in FindAllMarkers?  Does this mean that the gene is not in the top 3000 variable genes in the dataset?

Best wishes,
Lucy

__________________________________

Lucy Garner
Wellcome Trust PhD student
Klenerman group
Translational Gastroenterology Unit, John Radcliffe Hospital
University of Oxford

lucy.garner@merton.ox.ac.uk<mailto:Lucy.garner@merton.ox.ac.uk>
+44 1865 220663

**Comment by osvobod** [comment]
Hi, I think that I can see similar issue as Lucy. When I do SCTtransform, I'm missing some of the genes within the SCT assay even though I set "return.only.var.genes = F" and comparing to RNA assay.
Here is what I see when I look at both assays:

> UNI@assays
$RNA
Assay data with 14477 features for 971 cells
First 10 features:
 phtf2.1, dusp16, crebl2, gpr19, tbk1, eps8a, si:ch73-252i11.1, msgn1,
si:ch211-51e12.7, mrps10 

$SCT
Assay data with 12353 features for 971 cells
Top 10 variable features:
 hbbe1.3, hbae1.1, hbbe1.2, hbae1.1.1, hbae1.3, tmsb4x, marcksl1a,
pfn1, hbbe3, actb2 


Is there any explanation for this? Sorry, if I missed the answer elsewhere. Are the missing genes evaluated as a noise by SCT and that's why they are excluded?

Thank you,

Ondrej

**Comment by wupeng2** [comment]
> Hi, I think that I can see similar issue as Lucy. When I do SCTtransform, I'm missing some of the genes within the SCT assay even though I set "return.only.var.genes = F" and comparing to RNA assay.
> Here is what I see when I look at both assays:
> 
> UNI@assays
> 
> $RNA
> Assay data with 14477 features for 971 cells
> First 10 features:
> phtf2.1, dusp16, crebl2, gpr19, tbk1, eps8a, si:ch73-252i11.1, msgn1,
> si:ch211-51e12.7, mrps10
> 
> $SCT
> Assay data with 12353 features for 971 cells
> Top 10 variable features:
> hbbe1.3, hbae1.1, hbbe1.2, hbae1.1.1, hbae1.3, tmsb4x, marcksl1a,
> pfn1, hbbe3, actb2
> 
> Is there any explanation for this? Sorry, if I missed the answer elsewhere. Are the missing genes evaluated as a noise by SCT and that's why they are excluded?
> 
> Thank you,
> 
> Ondrej

hello,i've got the same problem ,did you find out the resaon?

**Comment by osvobod** [comment]
Hi, 
here is what I did and what I found:
1. I created Seurat object as usual and I run SCTransform (I didn't subset any death cells or any doublets):

`UNI.data <- Read10X(data.dir = path10x)`
`UNI <- CreateSeuratObject(UNI.data, min.cells = 2, min.features = 200, project = "UNI")`
`UNI[["percent.mito"]] <- PercentageFeatureSet(object = UNI, pattern = "^mt-")`
`UNI <- SCTransform(object = UNI, vars.to.regress = c("percent.mito", "nCount_RNA"), verbose = T, return.only.var.genes = F)`

2. I generated the list of all genes detected within the Seurat object for each 'RNA' or 'SCT' assays and I appended to each gene the total number of counts and also total number of cells in which the particular gene got detected.

`# genes.SCT`
`genes.sums <- data.frame(Matrix::rowSums(UNI[["SCT"]]@counts))`
`genes.counts <- rowSums(data.frame(UNI[["SCT"]]@counts) !=0) `
`genes.SCT <- cbind(rownames(genes.sums), genes.sums, genes.counts)`
`colnames(genes.SCT) <- c("ID","sums","counts")`
`rownames(genes.SCT) <- c(1:nrow(genes.SCT))`

`# genes.RNA`
`genes.sums <- data.frame(Matrix::rowSums(UNI[["RNA"]]@counts))`
`genes.counts <- rowSums(data.frame(UNI[["RNA"]]@counts) !=0) `
`genes.RNA <- cbind(rownames(genes.sums), genes.sums, genes.counts)`
`colnames(genes.RNA) <- c("ID","sums","counts")`
`rownames(genes.RNA) <- c(1:nrow(genes.RNA))`

3. I subsetted the genes detected in RNA assay to see the one that are missing in SCT assay:

`missingGenes <- subset(genes.RNA, !(ID %in% genes.SCT$ID)) %>% arrange(desc(counts))`

4. I can see that all the genes that got excluded in SCT assay are beeing detected in less than 4 cells no matter what are the overall counts. This is the pattern, tell me if I'm wrong, but it seems to be something in default (not optinoal) setting in SCTransform funstion.

Ondrej

**Comment by timoast** [comment]
Hi, this is due to the `min.cells` argument in `vst`, which is called by `SCTransform`. By default this is set to [5](https://github.com/ChristophH/sctransform/blob/8e48f495e7212230f9de44ad34ce9192d4ac8a60/R/vst.R#L85).

You can pass arguments through `SCTransform` to change this default, so if you call `SCTransform` with `min.cells=-1` it will not perform any filtering of genes.

**Comment by lc822** [comment]
Hi,

I am still confused by this.  I have checked the expression of one of the genes, LDHB, that is not present in the scale.data slot following SCTransform, and it has values in the range 0-15 in the data slot.  What is the detection limit in vst?

Best wishes,
Lucy

**Comment by erikagucciardo** [comment]
Hi, the "min_cells" parameter is the minimum number of cells were the gene must be detected in order to be included in the data scaling. I had the same issue of gene loss in the SCT compared to the RNA slot (same as the closed issue #27) and after setting "min_cells = -1", no gene was filtered, and the genes in SCT and RNA are now the same.
Thank you all for your valuable suggestions!

**Comment by lc822** [comment]
That's great, thanks for the suggestion.

**Comment by rleonriv** [comment]
Hi, has anyone been able to set min_cell = -1 with Seurat v.3.0.2? I tried but get the error 
"Error in sample.int(length(x), size, replace, prob) : 
  NA in probability vector" 
I tried setting it to 0 and it would not allow me either

**Comment by lc822** [comment]
Have you tried "min_cells" instead of "min_cell"?

min_cells = -1 works for me with Seurat v3.1.1

**Comment by kmshort** [comment]
This may well be closed as an issue - but it is still happening in April 2020.

I've knitted an Rmd with

`SCTransform(seurat.object, min_cells = 3, verbose = FALSE, vars.to.regress = c("Sex","percent.mt","Cyclone.Cell.Cycle.Phases"))`

I get 120 pages of 
`iteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reachediteration limit reached` (you get it)

and 

`SCTransform(seurat.object, min_cells = 3, return.only.var.genes = FALSE, verbose = FALSE, vars.to.regress = c("Sex","percent.mt","Cyclone.Cell.Cycle.Phases"))`

makes no difference.

I'd love for somebody, anybody, to help figure this out. I'm at wit's end. I don't want 120 pages of "reachediteration limit reachediterationlimit".

Can we simply have a switch on SCTransform to suppress warnings? So with it, none of these warnings ever come out?

best regards,
Kieran

**Comment by andrewwbutler** [comment]
Hi Kieran,

You can always just set the r markdown chunk option to not display warnings and/or messages. E.g.

`
{r, warning = FALSE, message = FALSE}
`
