### ISSUE TITLE
Using group.by parameter with FindMarkers 

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#1428]
Hello,

I'm trying to figure out the best way of doing differential expression analysis at the cluster level between data subsets. My setup is as follows:

1) Integrated 4 samples (two genotypes two timepoints: let's call them `day0wt`, `day0ko`, `day5wt`, `day5ko`)
2) The `combined` object has the sample information under `combined$group` variable (e.g. `day0wt` etc.)
3) Calculated clusters (let's say I have `10` clusters)
4) `combined$active.idents` slot stores cluster data for each cell (e.g. `0`, `1`, `2`, etc)
5) For each cluster, I'd like to do pairwise comparisons (e.g. `1-to-2`, `1-to-3`, and `1-to-4` etc.)

What is the best way of doing this analysis? I was thinking the following but didn't quite work out:

```
# Create a list object for storing results
grp1_vs_2 <- list() 

for(i in levels(Idents(combined))){

grp1_vs_2[[i]] <- FindMarkers(combined, group.by="group", 
                  ident.1="day0wt", ident.2 = day0ko", subset.ident=i)

}

# > Error: Cannot find the following identities in the object: day0ko
```

Using `group.by = "group"` argument makes the function understand to look for `ident.1 = "day0wt"` in `combined$group` slot, but `ident.2` doesn't work quite the same way. Do you recommend subsetting data somehow for this type of analysis? Or, alternatively, is it better to use `cells.1` and `cell.2` arguments for this kind of pair-wise analyses?

Atakan

**Comment by atakanekiz** [comment]
A relevant update: 

Using a different Seurat object involving 2 samples (WT and KO), I tried running the differential expression analysis by feeding the relevant cell barcodes to `cell.1` and `cell.2` parameters as follows: 

```

# group slot stores sample information (WT vs KO)
# active.ident slot stores cluster information (Nai T, B cell etc.)

# Fetch cells to find out relevant cell barcodes
barcode_df <- FetchData(seurat_obj, vars = c("group", "active.ident")
barcode_df$barcode <- rownames(barcode_df)

# Filter on data subsets and pull barcode names
  cells1 <- barcode_df %>%
    filter(group == "WT") %>%
    filter(active.ident == "Naive T") %>%
    pull(barcode)
    
  
  cells2 <- df %>%
    filter(group == "KO") %>%
    filter(active.ident == "Naive T") %>%
    pull(barcode)

de_results <- FindMarkers(combined, ident.1 = cells1, ident.2=cells2)

# 30 differentially expressed genes are found
dim(de_results)
# > 30 7

```

When I ran the diff exp analysis using the following code in Seurat v3 I"m observing a lot more genes being detected as differentially expressed. All the 30 genes I found using the code below constitute the top 30 genes in this new analysis in the same order, but they have a lot smaller p values now.

```

nai_t_diff <- FindMarkers(combined, group.by="group", ident.1="WT", subset.ident = "Naive T")

# 115 differentially expressed genes are found
dim(nai_t_diff)
# > 115 7
```

**Comment by andrewwbutler** [comment]
Hi,

Using `group.by` and `subset.ident` should work. Based on the code you provided, it looks like you're pulling the cell names (barcodes) from an object called `seurat_obj` where as you're running `FindMarkers` on an object called `combined`? If these are actually different objects, that would explain the difference in DE results between your two methods.

**Comment by atakanekiz** [comment]
Sorry my bad. My example code was meant to say the same object. I'm using `combined` object for both parts. Updated the code above accordingly.

**Comment by satijalab** [comment]
You can check out a few examples of DE tests across clusters, or within clusters across replicates, here:
https://satijalab.org/seurat/v3.0/immune_alignment.html

Apologies that due to the volume of issues we receive here we're limited in the amount of custom code we can write for specific analyses
