### ISSUE TITLE
Error: Cannot allocate vector size X GBs

### ISSUE THREAD

**Issue by ericvon11** [satijalab/seurat#143]
Thanks for all the great work on the recent update to Seurat! I have a persistent problem I've given up on trying to figure out myself. I have a very large dataset with about 30k cells in it. I'm running on on Windows10 64bit, i7 Kaby Lake, 32GB DDR4 RAM. My Seurat object is currently 8.9GBs after filtering, normalizing, scaling, PCA, and tSNE. However, I can't regress anything out, nor can I run `FindClusters` because  I run into the error: 
`Error: cannot allocate vector of size 6.4 Gb` (or around 5GBs in other cases)
I know this normally just means R has run out of memory, but according to resource manager, roughly 40-50% of my 32GB is available when starting this task and it gives the error in some cases without ever having gone over about 65% of the 32GBs. Hence, there's a lot more memory available when I get this error.

When I try to regress out any variables, it takes about 2-3 hours to complete 100%, then throws the error. When I run `FindClusters`, it usually throws the error after analyzing a couple clusters.
In addition, I `gc()` prior to running these resource heavy tasks to try to allot as much space as I can.

Has anyone experienced something similar? I haven't run the PBMC33k dataset, but since a lot of people run that on their laptops, I'm assuming my 30k dataset should also work. Is there anything within the Seurat object that's excess and could delete? Or am I missing some settings in R?

Here's my systeminfo related to memory my object loaded.
```
Total Physical Memory:     32,636 MB
Available Physical Memory: 17,855 MB
Virtual Memory: Max Size:  40,396 MB
Virtual Memory: Available: 13,033 MB
Virtual Memory: In Use:    27,363 MB
```

**Comment by jprestonnn** [comment]
Hello,

Just curious if you found a solution to this problem? I'm having the same issue. Thanks!

-Jessica

**Comment by lrlvnvgene** [comment]
Has anybody found a solution to this issue?

**Comment by ericvon11** [comment]
This is definitely an issue of not having enough memory (even if it seems like your computer might have more memory available than R is requesting/failing to allocate.) Running this on a computer with more RAM or on a cluster works without issue, so I recommend you either upgrade your computer, or probably more usefully, learn to code in R through cluster computing. You should be able to request as much RAM as you need there. You can run your RAM intensive steps there, then work with your finished Seurat object on your personal computer.
I hope this helps.

Best,
Eric

**Comment by ajynair** [comment]
In Seurat3/4 will merging data as smaller groups help to overcome this problem. Issue #1400 talks about merging data as subgroups
[https://github.com/satijalab/seurat/issues/1400]
