### ISSUE TITLE
change feature names for objects in Seurat3

### ISSUE THREAD

**Issue by RuiyangLiu94** [satijalab/seurat#1430]
Hi,
I am trying to use FeaturePlot function in Seurat3 and I am coming across some difficulty here.

So the features of my objects are gene ids (starting with "ENSGxxx"), but in terms of featureplots, I want to label them as the gene name.

Previously when using Seurat2, I would use this code to solve the inconsistency:

gene_id<-"ENSG00000171345"
gene_name<-"KRT19"
tmp<-pan
tmp@data<-pan@data[gene_id,]
rownames(tmp@data)<-gene_name

Then I will use the tmp as the new object for featureplot.

Now with Seurat3, I could only access object@data via GetDataAssay(object), but things are not working when I tried this:
tmp<-pan
GetAssayData(tmp)<-GetAssayData(pan)[gene_id,]
Error in GetAssayData(tmp) <- GetAssayData(pan)[gene_name, ] :
  could not find function "GetAssayData<-"

I also tried to rename the feature names for the object by using:
rownames(tmp)<-as.character(plyr::mapvalues(rownames(tmp),from=gene_id,to=gene_name))
But things are still not working- the error is:
Error in dimnames(x) <- dn : 'dimnames' applied to non-array

So I am stuck in this step and wondering if there are some solutions for this.

Another thing to mention is that, I can't assign gene_name to the rownames of the original raw count matrix before CreatingSeuratObject, because there are few times when two gene_ids are matched to one gene_name, so I have to do it at some later step.

Thanks!

**Comment by mojaveazure** [comment]
Hi,

Currently, Seurat does not allow renaming of features after creation of an object. However, the labels in `FeaturePlot` are simply ggplot2 titles. This means you can change the label on the plot simply by changing the plot title using ggplot2's utilities.

**Comment by RuiyangLiu94** [comment]
Thanks for your explanation!

I am not sure how to change the title for a couple of ggplots (when I have multiple features to view) exactly, but I figured out an alternative way; just in case someone has a similar confusion, here is what I did:

markers <- c("KRT19", "MZB1")
markers.ens <- c("ENSG00000171345","ENSG00000170476")
tmp<-pan
tmp@meta.data[,markers]<-GetAssayData(tmp)[top.markers.ens,] %>% as.matrix %>% t
FeaturePlot(object = tmp, features = markers, reduction = "umap")

**Comment by VBRay** [comment]
I have achieve it witi some tips:
gg_Fig <- FeaturePlot(tmp_seu, features=gene_ids, **do.return=T**)
gg_Fig <- lapply( 1:length(gene_ids), function(x) { gg_Fig[[x]] + labs(title=gene_names[x]) }
gg_Fig <- CombinePlots( gg_Fig )

You could have a try for it. @RuiyangLiu94

**Comment by msherafatian** [comment]
Thanks @VBRay. It can also be achieved without separating and combining individual plots via assigning titles through a for loop.
for (i in 1:  length(gene_ids)) gg_Fig[[i]]$labels$title = gene_names[i]
