### ISSUE TITLE
Is that possible the same type of cells but location different?

### ISSUE THREAD

**Issue by zqyhyunbin** [satijalab/seurat#1431]
Hello, guys!
this is the problem i have met, i have many scRNA-seq samples, and use the CCA method to minimize the batch effect, but when i do the t-SNE plot, i found there are two same cell types(use the known markers), but they are really far way, is that possible?

**Comment by satijalab** [comment]
Please consider trying the Seurat v3 integration workflow (examples in) https://satijalab.org/seurat/v3.0/immune_alignment.html. Hopefully this performs better on your data
