### ISSUE TITLE
Resolution parameter

### ISSUE THREAD

**Issue by jmzvillarreal** [satijalab/seurat#1432]
Hi Seurat users,

Is there any way of estimating the optimal number of clusters of a dataset in Seurat and fix an according value for the resolution parameter ? The tutorials recommend from 0.6 to 1.2 for 3K cells but its not very clear why...

Thanks very much in advance !

**Comment by lshepard2154** [comment]
My understanding is that the resolution depends upon the heterogeneity of your dataset. That range is good for 3K cells, but if you have a dataset with much higher heterogeneity, then you should use a higher resolution (e.g.: in the vignette of the [mouse atlas dataset](https://satijalab.org/seurat/v3.0/mca.html), they use `resolution = 3`)

I agree that it would be nice to have a more unsupervised approach to this, but I don't think the field is quite there yet.
