### ISSUE TITLE
"Error in attributes[[i]] : subscript out of bounds" in as.loom function

### ISSUE THREAD

**Issue by cakirb** [satijalab/seurat#1433]
I have an issue while writing loom file. I have this error at Adding: "Gene" step.
```
> fetal.loom <- as.loom(x = fetal.seurat, filename = "fetal.loom", verbose = TRUE)
Transposing input data: loom file will show input columns (cells) as rows and input rows (features) as columns
This is to maintain compatibility with other loom tools
  |=========================================================================================| 100%
Adding: CellID
Adding: Gene
Adding a layer to norm_data (layer 1 of 1)
  |=========================================================================================| 100%
Error in attributes[[i]] : subscript out of bounds
```

There is another issue about the same error in LoomR page: https://github.com/mojaveazure/loomR/issues/36. This Seurat object doesn't include any result from the functions, only the matrix and the metadata. **It worked when I ran the Seurat workflow.** And I could successfully write loom file with another dataset before which I ran the workflow for that also, but I could not find any difference between the attributes of these two Seurat objects. Is it possible to save loom without running Seurat pipeline?

**Comment by mojaveazure** [comment]
Can you provide a the object, or a downsampled version said object, that's causing this error?

**Comment by satijalab** [comment]
In the interest of prioritizing issues on our side (this is a loomR issue as opposed to a Seurat issue), I will close this now - but please do continue the discussion on the loomR page.
