### ISSUE TITLE
problem with BuildClusterTree reorder

### ISSUE THREAD

**Issue by zbgaber** [satijalab/seurat#1434]
Hello,
I'm really loving Seurat 3.0.  The anchors and the inclusion of SCTransform are producing really clean results!  However, I'm having a bit of trouble with BuildClusterTree - I don't seem to be getting it to reorder cells.  What I want is for the clusters to be both renamed and reordered based on their positions in the cluster tree.  So I run:

`sigPC = 25`
`chromium <- BuildClusterTree(object = chromium, dims = 1:sigPC, reorder = TRUE, reorder.numeric = TRUE)`

This doesn't seem to be working.  I'm just getting the same tree but running from clusters 1-20 instead of from clusters 0 to 19.  Am I doing something wrong here?  

The first plot below was made with BuildClusterTree() with reorder = FALSE and reorder.numeric = FALSE.  The second plot had both arguments set to TRUE.  

![FALSE](https://user-images.githubusercontent.com/37221776/56738620-e487b400-6764-11e9-90fa-a734a271e2a2.png)
![TRUE](https://user-images.githubusercontent.com/37221776/56738630-e6517780-6764-11e9-9d22-52d458b25482.png)

**Comment by satijalab** [comment]
Thanks for sending - we recently independently identified this as a bug as well. We will update here when fixed.

**Comment by zbgaber** [comment]
Thanks!

**Comment by mojaveazure** [comment]
Hi Zachary,

This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
