### ISSUE TITLE
how to combine VDJ profile with gene expression profile

### ISSUE THREAD

**Issue by songeric1107** [satijalab/seurat#1435]
I have the results of VDJ profile (5') and the gene expression profile (3') from 10X, I already generate the cluster based on gene expression profiles, how do I include the VDJ profile with gene expression profile? I could not find any examples online.

Thank you

**Comment by satijalab** [comment]
We don't have any examples online and won't be able to add some in the near future. However, you can save the clonotype information in the object meta data (see the `AddMetaData` function). This way you can reference it during any downstream analyses in the object. This is how we analyze VDJ data from 10X in our lab

**Comment by hemadelon** [comment]
Which file of the Cell Ranger output of VDJ profile should I load to add to the metadata?

**Comment by j-andrews7** [comment]
@hemadelon 

Here is a function I wrote to add to add my 10x TCR clonotype data to the metadata of a Seurat object. I keep the clonotype ID in addition to the AA sequence since the clonotype ID may not be unique if samples are combined. I presume B cell VDJ should be similar.

```R
add_clonotype <- function(tcr_location, seurat_obj){
    tcr <- read.csv(paste(tcr_folder,"filtered_contig_annotations.csv", sep=""))

    # Remove the -1 at the end of each barcode.
    # Subsets so only the first line of each barcode is kept,
    # as each entry for given barcode will have same clonotype.
    tcr$barcode <- gsub("-1", "", tcr$barcode)
    tcr <- tcr[!duplicated(tcr$barcode), ]

    # Only keep the barcode and clonotype columns. 
    # We'll get additional clonotype info from the clonotype table.
    tcr <- tcr[,c("barcode", "raw_clonotype_id")]
    names(tcr)[names(tcr) == "raw_clonotype_id"] <- "clonotype_id"

    # Clonotype-centric info.
    clono <- read.csv(paste(tcr_folder,"clonotypes.csv", sep=""))

    # Slap the AA sequences onto our original table by clonotype_id.
    tcr <- merge(tcr, clono[, c("clonotype_id", "cdr3s_aa")])

    # Reorder so barcodes are first column and set them as rownames.
    tcr <- tcr[, c(2,1,3)]
    rownames(tcr) <- tcr[,1]
    tcr[,1] <- NULL

    # Add to the Seurat object's metadata.
    clono_seurat <- AddMetaData(object=seurat_obj, metadata=tcr)
    return(clono_seurat)
    }
```

**Comment by hemadelon** [comment]
@j-andrews7 Thanks so much! I really appreciate it.

**Comment by atakanekiz** [comment]
@j-andrews7 thanks for this vignette. I expanded it further to work with my own data. 

The detailed tutorial can be found at [my Biostars post](https://www.biostars.org/p/384640/).

**Comment by christensensm** [comment]
This was a great help! Took your function and (1) fixed the issue of defined tcr_location vs. used tcr_folder and (2) added in some extra metadata from the vdj analysis (v_gene, j_gene, chain, etc.). Thanks!

**Comment by j-andrews7** [comment]
@christensensm Care to share? I've been too lazy to devote much time to parsing out the genes, but it'd be super helpful to have.

**Comment by khaled406** [comment]
Hell

> Of course @j-andrews7! See the below altered code.
> The line `tcr <-tcr[,c("barcode","raw_clonotype_id","chain","v_gene","d_gene","j_gene")]` can be changed to include whatever columns you want from the vdj result file. Other changes were needed as well but this will get you colontype id, v d and j genes, and cdr3aa sequences added as metadata to your seurat object.
> 
> ```
>   tcr <- read.csv(paste(tcr_folder,"filtered_contig_annotations.csv", sep=""))
>   
>   # Remove the -1 at the end of each barcode.
>   # Subsets so only the first line of each barcode is kept,
>   # as each entry for given barcode will have same clonotype.
>   tcr$barcode <- gsub("-1", "", tcr$barcode)
>   tcr <- tcr[!duplicated(tcr$barcode), ]
>   
>   # Only keep the barcode and clonotype columns. 
>   # We'll get additional clonotype info from the clonotype table.
>   tcr <- tcr[,c("barcode", "raw_clonotype_id","chain","v_gene","d_gene","j_gene")]
>   names(tcr)[names(tcr) == "raw_clonotype_id"] <- "clonotype_id"
>   
>   # Clonotype-centric info.
>   clono <- read.csv(paste(tcr_folder,"clonotypes.csv", sep=""))
>   
>   # Slap the AA sequences onto our original table by clonotype_id.
>   tcr <- merge(tcr, clono[, c("clonotype_id", "cdr3s_aa")])
>   
>   # Reorder so barcodes are first column and set them as rownames.
>   tcr <- tcr[, c(2,1,3:7)]
>   rownames(tcr) <- tcr[,1]
>   tcr[,1] <- NULL
>   
>   # Add to the Seurat object's metadata.
>   clono_seurat <- AddMetaData(object=seurat_obj, metadata=tcr)
>   return(clono_seurat)
> }```
> ```

@christensensm
How do you then export the data all together?
Thanks

**Comment by jgbaum** [comment]
For anyone still following this thread or interested in recovering data for up to 4 chains (2 TRA + 2 TRB), we have updated the function provided by @j-andrews7.  In this version, there will be 4 sets of columns, one set for each possible TRA and TRB chain.  The metadata columns added will look like:

```
 [1] "clonotype_id"         "v_gene.tra1"          "j_gene.tra1"          "c_gene.tra1"          "v_gene.tra2"         
 [6] "j_gene.tra2"          "c_gene.tra2"          "v_gene.trb1"          "d_gene.trb1"          "j_gene.trb1"         
[11] "c_gene.trb1"          "v_gene.trb2"          "d_gene.trb2"          "j_gene.trb2"          "c_gene.trb2"         
[16] "clonotype_frequency"  "clonotype_proportion" "cdr3s_aa"             "cdr3s_nt"             "inkt_evidence"       
[21] "mait_evidence"  
```

Barcodes with only 1 alpha or beta chain will have `NA` values in the `tra2` or `trb2` sets of columns respectively.  Hope this is useful!

```r
library(dplyr)
library(tidyr)
library(readr)

add_clonotype <- function(tcr_folder, seurat_obj){
  tcr <- read_csv(paste(tcr_folder,"filtered_contig_annotations.csv", sep=""))
  
  # Only keep the needed subset of columns
  # We'll get additional clonotype info from the clonotype table. - this isn't strictly necessary as we
  # can cobble together the CDR3 data and other fields from here, but it's already neatly
  # incorporated in that table - plus the clonotype table includes additional columns with INKT & MAIT evidence fields
  tcr <- tcr %>%
    select("barcode", "raw_clonotype_id","chain","v_gene","d_gene","j_gene","c_gene") %>%
    rename(clonotype_id = raw_clonotype_id)
  
  # now we make 1 row per barcode and 4 sets of columns for v, d, j, and c genes
  tcr <- tcr %>%
    # Remove d_gene for TRA chains
    mutate(d_gene = ifelse(chain == "TRA", NA_character_, d_gene),
           d_gene = na_if(d_gene, "")  # convert any "" to NA
           ) %>%
    # Create chain index per barcode and chain type
    group_by(barcode, chain) %>%
    mutate(chain_idx = row_number()) %>%
    ungroup() %>%
    # Create chain suffix: tra1, trb2, etc.
    mutate(suffix = paste0(tolower(chain), chain_idx)) %>%
    # Select only necessary columns
    select(barcode, clonotype_id, suffix, v_gene, d_gene, j_gene, c_gene) %>%
    # Pivot to wide format
    pivot_wider(
      names_from = suffix,
      values_from = c(v_gene, d_gene, j_gene, c_gene),
      names_glue = "{.value}.{suffix}",
      values_fill = NA_character_
    ) %>%
    distinct()
  
  # let's reorder the columns so that they are grouped by tra1, tra2, trb1, trb2
  tra_fields <- c("v_gene", "j_gene", "c_gene")
  trb_fields <- c("v_gene", "d_gene", "j_gene", "c_gene")
  final_col_order <- c(
    "barcode", "clonotype_id",
    unlist(lapply(c("tra1", "tra2"), function(chain) paste0(tra_fields, ".", chain))),
    unlist(lapply(c("trb1", "trb2"), function(chain) paste0(trb_fields, ".", chain)))
  )
  
  # Reorder if all expected columns are present
  tcr <- tcr %>%
    select(any_of(final_col_order))
  
  # read in the Clonotype-centric info.
  clono <- read_csv(paste(tcr_folder,"clonotypes.csv", sep=""))
  
  # merge the clonotype data with the TCR data
  # and reorder so barcodes are set as rownames.
  tcr <- tcr %>%
    left_join(clono,
              by='clonotype_id') %>%
    rename(clonotype_frequency=frequency,
           clonotype_proportion=proportion) %>%
    column_to_rownames('barcode')
  
  # Add to the Seurat object's metadata.
  clono_seurat <- AddMetaData(object=seurat_obj,
                              metadata=tcr)
  
  return(clono_seurat)
}
```
