### ISSUE TITLE
How can I change the size of gene names displayed on DoHeatmap?

### ISSUE THREAD

**Issue by SFF-singecell-user** [satijalab/seurat#1437]
Hi, I am using v3 and would like to shrink the gene name labels on a heatmap. (In v2 I used cex.row = , but that does not work with v3)
Thanks in advance for any tips!

**Comment by timoast** [comment]
Hi, you can change the text size using the `theme` function in `ggplot2`:

```r
DoHeatmap(object = pbmc_small, features = VariableFeatures(pbmc_small)) + 
    theme(text = element_text(size = 20))
```

**Comment by SFF-singecell-user** [comment]
Hi Tim, Thanks so much for your suggestion. Unfortunately, that only seems to change the size of the Legend text, not of the gene names.

**Comment by timoast** [comment]
I can't reproduce that, here's the output of my example without changing `element_text`:

![no_change](https://user-images.githubusercontent.com/4591688/56749924-ada7a300-6750-11e9-91f1-c2f158e8aa1a.png)

And setting `element_text(size = 20)`:

![size_20](https://user-images.githubusercontent.com/4591688/56749950-c021dc80-6750-11e9-864d-814335be4a79.png)

**Comment by SFF-singecell-user** [comment]
Hi Tim,
Thank you so much for your reply.
This what happens when I do it (below, size 20 and size 4) – it only changes the legend.
I appreciate it so much if you have any other recommendations
Shelli



DoHeatmap(object = immune.small, features = top20$gene, assay = "integrated") + theme(text = element_text(size = 45))
[cid:image001.png@01D4FB6A.9B373A20]
[http://euler.med.yale.edu:8787/graphics/plot.png?width=1104&height=708&randomizer=-685418423][http://euler.med.yale.edu:8787/graphics/plot.png?width=1104&height=708&randomizer=-685418423]

> DoHeatmap(object = immune.small, features = top20$gene, assay = "integrated") + theme(text = element_text(size = 4))


[cid:image003.png@01D4FB6A.9B373A20]

[http://euler.med.yale.edu:8787/graphics/plot.png?width=1104&height=708&randomizer=-685418423]

[http://euler.med.yale.edu:8787/graphics/plot.png?width=1104&height=708&randomizer=-685418423]

**Comment by SFF-singecell-user** [comment]
Hi Tim,
This is what happens when I try that- it only changes legend size.
I really appreciate your help, and any further suggestions

> DoHeatmap(object = immune.small, features = top20$gene, assay = "integrated") + theme(text = element_text(size = 4))

[size4.pdf](https://github.com/satijalab/seurat/files/3118260/size4.pdf)

**Comment by SFF-singecell-user** [comment]
Good news- Was able to fix it, had to use theme(axis.text.y = ...)
thanks again for your help!

> DoHeatmap(object = immune.small, features = top20$gene, assay = "integrated") + theme(axis.text.y = element_text(size = 5))

**Comment by jiangshan529** [comment]
Hello, good discussion! I would like to know how to change the x axis font size. I used "theme(axis.text.x.top  = element_text(size = 10))", but it seems it does not work.
