### ISSUE TITLE
What does the Integration functions in V3 do for sample specific cell types?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1438]
Hi : 
     I know that there are the new integration workflows in Seurat v3. And its seems more suitable for identify common cell types across the datasets or conditions!?  But, I think its common situation that there are specific cells types correspoing to samples or patients. For example , single cells of tumor, there are lots of evdience show that tumor alignment cells are patient specifced and will cluster by patient not by cell types, but  immune and stromal cells will cluster together by cell types rather than  patient. So my question is  "What does the Integration functions in V3 do for sample specific cell types? " ,  does the Integration functions only intergrate the common cell types and leave the patient specific cells alone ? or It will integrate all the cell types and there is no clusters that correspoding to one patient ?
     There are big batch effect for my data, And I cant regress out it by using ScaleData. I have to use Integration functions to merge them together to analysis, but for each of my samples there are one to two specific cell type correspoding to samples. I aim to merge this data together and the final tSNE show that most of cells clustering by cell types , but there are still some clusters are samples specific.
     And for this situation, any advices for integrate and analysis such samples ?

Best

**Comment by timoast** [comment]
We explain this in detail in our preprint: https://doi.org/10.1101/460147
