### ISSUE TITLE
combining scRNAseq data produced on different platforms

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#1439]
Hi,

Our lab is producing data on the 10x platform but we have a collaborator producing scRNAseq data on the seq-well platform.  I was wondering you think it is OK to load these data into Seurat and analyze them together even though they are produced on different platforms, or if it is important that all the data are produced from the same platform?

Thanks,

Leonard

**Comment by timoast** [comment]
This is fine, if you observe technology-specific variation you can consider using the integration methods outlined here: https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html and https://www.biorxiv.org/content/10.1101/460147v1.full

**Comment by lennycheung** [comment]
Thanks a lot!

Leonard
