### ISSUE TITLE
run tsne and umap on 3000 most variable features

### ISSUE THREAD

**Issue by janinemelsen** [satijalab/seurat#1442]
Hi,

Rather than using principal components I would like to apply a SNE and UMAP analysis on the 3000 most variable genes which are saved in my SCT assay. The normalized values are stored in the scale.data slot. 

I tried the following code:

```{r fig.height=5, fig.width=10}
NKbonemarrow_seurat <- RunTSNE(object = NKbonemarrow_seurat, dims = NULL, verbose = FALSE, features = NKbonemarrow_seurat[["SCT"]]@var.features)
```
which gave me the following error:
longer object length is not a multiple of shorter object lengthError: All cells in the object being added must match the cells in this object

And this code:
```{r fig.height=5, fig.width=10}
NKbonemarrow_seurat <- RunTSNE(object = NKbonemarrow_seurat, dims = NULL, verbose = FALSE, features = NKbonemarrow_seurat[["SCT"]]@var.features, assay = "SCT")
```
Error: All cells in the object being added must match the cells in this object

So my question: how do I refer correctly to the 3000 most variable genes in the SCT scale.data slot as input for my SNE analysis?

**Comment by mojaveazure** [comment]
I am unable to reproduce this error:

```R
> pbmc <- readRDS(file = '~/Downloads/pbmc3k/pbmc3k_final.rds')
> pbmc
An object of class Seurat 
13714 features across 2638 samples within 1 assay 
Active assay: RNA (13714 features)
 2 dimensional reductions calculated: pca, tsne
> pbmc <- SCTransform(object = pbmc, verbose = FALSE)
There were 50 or more warnings (use warnings() to see the first 50)
> pbmc
An object of class Seurat 
26233 features across 2638 samples within 2 assays 
Active assay: SCT (12519 features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, tsne
> dim(x = GetAssayData(object = pbmc, slot = 'scale.data'))
[1] 3000 2638
> pbmc <- RunTSNE(object = pbmc, features = VariableFeatures(object = pbmc), reduction.key = 'sctSNE_', reduction.name = 'sctsne')
> pbmc
An object of class Seurat 
26233 features across 2638 samples within 2 assays 
Active assay: SCT (12519 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, tsne, sctsne
> DimPlot(object = pbmc, reduction = 'sctsne')
```
![image](https://user-images.githubusercontent.com/11035068/56837517-af549200-6848-11e9-8187-bd30a678d2b8.png)

Could you provide your object, or a downsampled version of it, so we can try to reproduce this error?

**Comment by satijalab** [comment]
Thanks for your question.  I believe when we use features, we use the data slot by default. If you'd like to use scale.data - you can use GetAssayData to pull this slot, and then feed it into Rtsne (or similar) outside of Seurat. You can then add the reduction back as you would any custom dimensional reduction.

Apologies that due to the volume of issues we receive here, we likely won't be able to debug this particular example further

**Comment by janinemelsen** [comment]
Hi,

by removing the argument dims=NULL, and assay = 'SCT', the function worked. However, as stated above, I think that the non-normalized data is used. By adding assay="SCT" still the error '_formal argument "assay" matched by multiple actual arguments'_ appears.
