### ISSUE TITLE
Visualise Two Conditions Side by Side When One Condition Contains 3 Replicates

### ISSUE THREAD

**Issue by SyrupBadger** [satijalab/seurat#1443]
Hi,
I am looking at the vignette for the control Vs stimulated PBMCs as it is similar to my experiment which contains cells from naive and injured samples.  However, I have three biological reps for naive and one for the injured.  I generated the Seurat object using the merge function for multiple samples 
`NewObject<-merge(x=Injured, y=c(Naive1, Naive2, Naive3), add.cell.ids=c("identification for the samples")`
This worked fine and the naive samples all mapped together while the injured sample was separate when visualised by uMAP reduction.  
What I would like to do is visualise the two different conditions side-by-side when looking at gene expression.  Is there a way I can tell Seurat to class Naive1, 2 and 3 as one sample rather than three individual samples and the injured as another sample?  Currently when I try to split the samples I get an error saying that 'dims' must be a two-length vector.
Thanks

**Comment by satijalab** [comment]
Yes, you can setup a metadata column called NaiveVsInjured (or whatever name you would like). Assign this column to Naive for the Naive cells, and Injured for the injured ones. Then you can add split.by="NaiveVsInjured" to your DimPlot call. You can see some examples in https://satijalab.org/seurat/v3.0/immune_alignment.html
