### ISSUE TITLE
Subset Error: Under current subsetting parameters, the default assay will be removed. 

### ISSUE THREAD

**Issue by hfberg** [satijalab/seurat#1444]
Hi! I have used v3 for a while without problem, but today, I got this error message in both my two (completly independent) samples with independent thersholds. I tried with lower or fewer thresholds as well, but I got the same error message. How can I fix this?

```
> pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 500)
> pbmc[["percent.mt"]] <- PercentageFeatureSet(object = pbmc, pattern = "^mt-")
> # Visualize QC metrics as a violin plot
> VlnPlot(object = pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
> pbmc <- subset(x = pbmc, subset = nFeature_RNA > 500 & nFeature_RNA < 1200 & percent.mt < 2.3 & nCount_RNA>500 & nCount_RNA< 2000)
Error: Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay.
> traceback()
3: stop("Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay.", 
       call. = FALSE)
2: subset.Seurat(x = pbmc, subset = nFeature_RNA > 500 & nFeature_RNA < 
       1200 & percent.mt < 2.3 & nCount_RNA > 500 & nCount_RNA < 
       2000)
1: subset(x = pbmc, subset = nFeature_RNA > 500 & nFeature_RNA < 
       1200 & percent.mt < 2.3 & nCount_RNA > 500 & nCount_RNA < 
       2000)
```

**Comment by timoast** [comment]
How many cells should you retain using these cutoffs? My guess is that these criteria would remove all cells in your dataset, which would explain the error. In particular, <2.3% mitochondrial counts seems like a very low cutoff.

**Comment by hfberg** [comment]
It's true that I would not keep a lot of cells, but the data quality is really low so I just want to analyze a few high quality cells anyway. This is not the same dataset because I'm not at work but the VlnPlot typically looks like this:

https://ibb.co/zPcCg9L

**Comment by mnovalri** [comment]
I do have the same issue but using the data with the tutorial (PBMCs).

Here is the code I'm using. 
> pbmc.data <- Read10X(data.dir = "~/Dropbox/R_Single_cell/Seurat tuto/filtered_gene_bc_matrices/hg19")
> pbmc <- CreateSeuratObject(counts = pbmc.data, project = "seurat.tuto", min.cells = 3, min.features = 200)
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')

> dense.size <- object.size(x = as.matrix(x = pbmc.data))
> sparse.size <- object.size(x = pbmc.data)
> sparse.size
> dense.size / sparse.size

> pbmc[["percent.mt"]] <- PercentageFeatureSet(object = pbmc, pattern = "^MT-")
> pbmc <- subset(x = pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
Error: Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay.

> traceback()
3: stop("Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay.", 
       call. = FALSE)
2: subset.Seurat(x = pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 
       2500 & percent.mt < 5)
1: subset(x = pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 
       2500 & percent.mt < 5)

This is the tutorial dataset, but if I add my own dataset I have the same error. 
Not sure what I'm doing wrong. 
M

**Comment by mnovalri** [comment]
It appears my "Seurat" package was corrupted.
I deinstalled and reinstalled the package and everything works great now.

**Comment by hfberg** [comment]
great @mnovalri , thank you so much! :):):)

**Comment by duyck** [comment]
I get this same error only when using the development branch (no matter the cutoffs). After reinstalling from CRAN there is no longer and issue. I have installed and uninstalled multiple times from each to ensure it is not a file corruption issue.

**Comment by hfberg** [comment]
I can confirm that the error was fixed by reinstalling seurat! Thanks for your help everone.
