### ISSUE TITLE
Scanpy cannot read Seurat-created loom file

### ISSUE THREAD

**Issue by cakirb** [satijalab/seurat#1445]
As I mentioned in https://github.com/theislab/scanpy/issues/598, I cannot read loom files from Seurat in Scanpy. It gives this error:`ValueError: column index exceeds matrix dimensions`. Is there anything to fix this error? Previously, I was unable to write loom file in Seurat. I was trying to write without running Seurat workflow (https://github.com/satijalab/seurat/issues/1433), but I could manage it after running the workflow. I wanted to tell my previous issues since I do or skip some steps in this process.

**Comment by mojaveazure** [comment]
Hi @cakirb,

This seems to be an issue with Scanpy. I'm closing this issue for now; please update if the scanpy developers find something wrong with Seurat's implementation of `as.loom`
