### ISSUE TITLE
How to get scaled data for all genes after integration with IntegrateData (CCA) in Seurat v3?

### ISSUE THREAD

**Issue by rlorenzc** [satijalab/seurat#1447]
Hello,

Is there a way to get the scaled expression of all the genes after integration with IntegrateData(CCA)? Currently, I'm only able to get the number of genes I've set for FindVariableFeatures (nfeatures = 2000). I plan to use this gene list for GSEA analyses.
Similarly, is there any particular reason why one would limit the integration to 2000 variable genes and not all the genes (aside from computationally heavy resources)? Naïvely, I think that I can ramp up the nfeatures to 20,000 to get all my genes included in the IntegrateData computation. Any insight would be highly appreciated!

Thanks!

**Comment by satijalab** [comment]
in IntegrateData you can set the `features.to.integrate` to be all genes. The only reason we don't do this is to save time and memory

**Comment by PernilleYR** [comment]
Hi, 

In the same topic would you advice to use integrated data for GSEA? Is it ok to calculate FC on these type of data? If we plot the expression of a specific gene (as points) we can see that there is still pattern of expression specific to each batch and I'm scared this might influence the FC by batch (especially if you have non homogeneous distribution of cells from each batch in different cluster). Also should integrated values considered a log (or even log(1+x)) values? 

Would you then only advice to perform GSEA by batch? 

Thank you very much for your insight!

Pernille

**Comment by cdarby** [comment]
@PernilleYR  Your new question is more likely to receive attention from the dev team and the user community if you open a new GitHub issue, instead of commenting on this closed issue. You can do this easily by clicking the three dots in the upper-left corner of your comment and selecting "Reference in new issue". Thanks!
