### ISSUE TITLE
Distribution of samples by cluster

### ISSUE THREAD

**Issue by L30P30** [satijalab/seurat#1448]
I'm hoping you can help me with these two things I'm trying to do:

1) Calculate the proportion of each sample (by orig.ident) that is attributed to each cluster

2) Test whether samples are comprised of certain clusters more than would be expected by chance.

For example, if cluster 1 makes up 20% of the total population of cells, does sample X have significantly more or less than 20% of cells attributed to cluster 1? Do you think this is a valid question to ask? I haven't seen anyone else do this analysis before but it would be particularly useful for my experiment, where I am interested in the equivalence/similarity of different cell lines.

I am using 3.0 by the way.

Many thanks!

**Comment by satijalab** [comment]
You can check out this paper for an example: https://stm.sciencemag.org/content/10/463/eaaq0305/tab-figures-data

Stay tuned for more updates to Seurat that will implement similar types of tests for DE of cluster membership
