### ISSUE TITLE
Bug(?) in FindMarkers counts data

### ISSUE THREAD

**Issue by giorgosminas** [satijalab/seurat#1449]
Hi, 

Can you look into the code FindMarkers.default of Seurat v3 lines 63-77? 

It appears to me that when you do the initial test for whether the differences pass the logfc.threshold you take the exponential of the counts and then log it. 

The trouble is that if the count is large, which for my data this is the case for a lot of interesting genes, by taking the exponential it becomes infinity and then the genes are subsequently dropped by the differential expression test. 

This might explain some earlier issues reported for differences between wilcoxon test results and "negbinom", "poisson". 

This should be trivial to solve but, if true, is very serious because you could miss a lot of important de genes. 

Best wishes,

Giorgos

**Comment by satijalab** [comment]
Thanks for taking a look. Those lines pull from the `@data` slot (which is by default log-normalized), so there is no bug.

**Comment by giorgosminas** [comment]
I don’t think they use the data slot. They should, but the object that it uses to do this part is the counts data.
