### ISSUE TITLE
FeatureHeatmap  'features.plot' not found

### ISSUE THREAD

**Issue by brianjohnhaas** [satijalab/seurat#145]
In running through the tutorial: http://satijalab.org/seurat/Seurat_AlignmentTutorial.html

I encountered the following at the very end:

> FeatureHeatmap(object = pbmc, features.plot = c("CD3D", "FCGR3A", "MS4A1"), 
+     group.by = "protocol", sep.scale = TRUE, pt.size = 0.5, cols.use = c("lightgrey", 
+         "blue"))
Error in FUN(X[[i]], ...) : object 'features.plot' not found

My installation is on ubuntu and was performed according to the instructions, using devtools and installing from github.

thanks in advance!

**Comment by andrewwbutler** [comment]
We fixed a few bugs in the latest patch (2.0.1). Try updating and see if that resolves the issue.
