### ISSUE TITLE
name of units for expression in AverageExpression and GenePlot/FeatureScatter

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#1450]
Hi,

I am using making plots with values from AverageExpression and FeatureScatter (GenePlot in 2.3.4) and I was asked to clarify the y-axes units.  Could you clarify for me what those might be properly called?  I see in some of your previous questions that they are non-log transformed values of expression.  But I don't think I can call them e.g. UMI count because they are not integer values?

Thanks,

Leonard

**Comment by satijalab** [comment]
They are in the same units as Seurat normalized data. This is similar to TPM but instead of per-million, is per 10,000

**Comment by lennycheung** [comment]
Thanks a lot!
