### ISSUE TITLE
Wrong in cell type assigned in 2700PBMC tutorail

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1452]
Hi :
    In the 2700PBMC tutorial here : https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html
    Cluster0 express IL7R and CCR7 but you labeled with Memory T cells, while Cluster1 express IL7R and S100A4 you labeled with Naive T cells. But I think it should reverse, and you also answer question in https://github.com/satijalab/seurat/issues/1344. S100A4 or CREM for Memory T cells and CCR7 for Naive T cells.
Best

**Comment by andrewwbutler** [comment]
Thanks for catching! The vignette has been updated accordingly.
