### ISSUE TITLE
p_val & avg_logFC?

### ISSUE THREAD

**Issue by chrsyl** [satijalab/seurat#1453]
Very simple question but I could not find the definition.
avg_logFC = 1.6084812 should be the natural log base.
but p_val = 3.709555e-4 is this also the natural log base? So in ordinary language this is not p<3.7*10(-4) = 0.00037 but p < 3.7*exp(-4) = 0.06776786

**Comment by leonfodoulian** [comment]
Hi,

`e-x` in `R` is the same as `10^-x` (same for positive values of `x`).

```R
> 1*10^-4
[1] 1e-04
```

Best,
Leon
