### ISSUE TITLE
Issue with FindMarkers in Seurat 3 confirmed 

### ISSUE THREAD

**Issue by giorgosminas** [satijalab/seurat#1454]
Hi, 

I made an earlier issue yesterday which is now closed, but I now confirmed the error with pbmc data and hoping that you will look into that. 

The code below returns too different outputs for comp and comp1. The output is expected to be different, but the filtered features derived before applying the test should have been the same. It turns out that they are not and features are filtered mistakenly. This is extremely important.  

pbmc.counts <- Read10X(data.dir = "~/Downloads/pbmc3k/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.counts)
pbmc <- NormalizeData(object = pbmc)
pbmc <- FindVariableFeatures(object = pbmc)
pbmc <- ScaleData(object = pbmc)
pbmc <- RunPCA(object = pbmc)
pbmc <- FindNeighbors(object = pbmc)
pbmc <- FindClusters(object = pbmc)
comp <- FindMarkers(object = pbmc, ident.1 = 1,
                    test.use = "wilcox",
                    slot="data")
comp1 <- FindMarkers(object = pbmc, ident.1 = 1,
                    test.use = "negbinom",
                    slot="data")

I identified the problem by running debug(FindMarkers). I saw that data.slot used in FindMarkers.default that runs within FindMarkers is always "counts" for test.use="negbinom". This means that the average logfc computed below is computed on counts (!) and not on normalised data. 

  data.1 <- apply(X = object[features, cells.1, drop = FALSE], 
                  MARGIN = 1, FUN = function(x) {
                    return(log(x = mean(x = expm1(x = x)) + pseudocount.use))
                  })

  data.2 <- apply(X = object[features, cells.2, drop = FALSE], 
                  MARGIN = 1, FUN = function(x) {
                    return(log(x = mean(x = expm1(x = x)) + pseudocount.use))
                  })

But when the count is 710 or higher, expm1(x = x) returns infinite and the feature is filtered out in the lines below

  total.diff <- (data.1 - data.2)
  features.diff <- if (only.pos) {
    names(x = which(x = total.diff > logfc.threshold))
  }

For pbmc data you do not have such big counts. For my data this happened for the highly expressed genes, which are very important for my analysis. Even if you do not have such a problem the logfc threshold should not be the same for normalised and non-normalised data. 

I can fix this for my analysis, but I suppose it is much better if your lab fix it. 

Thanks in advance. 

Giorgos

**Comment by satijalab** [comment]
Thanks. We don't support the use of the negbinom test in Seurat3, as it is being replaced by DE tests using the sctransform workflow (soon to come). We'll update to make sure this is clearer, and ensure that we pull from the right slot for count-based DE tests

**Comment by giorgosminas** [comment]
Thanks for your reply. The issue applies to negbinom, poisson and DESeq2 tests. It will be great to see this sorted out.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
