### ISSUE TITLE
Global number of cells per each gene

### ISSUE THREAD

**Issue by cesco-lemon** [satijalab/seurat#1456]
Hey community!

I am trying to add some extra QCs to my Seurat pipeline. I'm working with a pretty big dataset and I wanted to look at the number of cells per genes, similarly to what I do when looking at nGene and nUMI, just so I can filter out genes that are expressed by a very low number of cells but have an empirical number to use instead of an arbitrary cut-off of for example genes expressed in at least 10% of the cells.

Any suggestions or lines of code I can try?

Thank you!

**Comment by leonfodoulian** [comment]
Hi,

Assuming `counts` is your digital gene expression matrix, you can use the following code to count the number of cells expressing each gene in your dataset:

```R
> n.cells.per.gene <- Matrix::rowSums(x = counts > 0)
> head(x = n.cells.per.gene)
0610007P14Rik 0610009B22Rik 0610009L18Rik 0610009O20Rik 0610010F05Rik 
          513           116            27           114           290 
0610010K14Rik 
          173 
```

Below, you can find two ways to plot the data, although I am not sure you would be able to set any empirical value graphically for gene filtering:

```R
# Violin plot
# Did not plot the points as the graph will be completely masked by a dense cloud of points
require(ggplot2)
ggplot(data = as.data.frame(x = n.cells.per.gene),
       mapping = aes(x = "n.cells.per.gene",
                     y = n.cells.per.gene)) +
  geom_violin()

# Density plot
require(ggplot2)
ggplot(data = as.data.frame(x = n.cells.per.gene),
       mapping = aes(x = n.cells.per.gene,
                     y = ..count..)) +
  geom_density()
```

Otherwise, you can use the following code to keep all genes expressed in at least 10% of the cells:

```R
> genes.to.keep <- Matrix::rowSums(x = counts > 0) >= floor(x = 0.1 * ncol(x = counts))
> head(x = genes.to.keep)
0610007P14Rik 0610009B22Rik 0610009L18Rik 0610009O20Rik 0610010F05Rik 
         TRUE          TRUE         FALSE          TRUE          TRUE 
0610010K14Rik 
         TRUE 
> counts.sub <- counts[genes.to.keep,]
```

Best,
Leon
