### ISSUE TITLE
Question about the 12-HTO dataset

### ISSUE THREAD

**Issue by xhongyi** [satijalab/seurat#1457]
Hi, I have thoroughly read the Genome Biology paper. However, it does not describe the experiment setup for the 4-cell-line 12-HTO cell hashing experiment.

It does include the description for the 8-HTO PBMC cell hashing experiment tho. I would guess in your previous answer, you might be referring to the 8-HTO dataset.

However, the description for the 12-HTO 4-cell-line dataset is missing. Also when I download the dataset, I noticed that unlike the 8-HTO dataset, this one contains more than 50K cell barcodes. It can't be that more than 50K cells are recovered from a single cell hashing run can it? Or is it just raw data without any pre-processing.

Would be great if we can compare the two HTO experiments included in the paper and decide which setting is more suited for our experiment.

**Comment by satijalab** [comment]
Apologies- this was actually run with the Drop-seq (as opposed to 10X) technology, so I don't think the experimental parameters we used will be relevant for your analysis - as they will be entirely different.

**Comment by xhongyi** [comment]
Thank you.

Appreciated.
