### ISSUE TITLE
seurat_clusters column

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#1458]
A few weeks ago, `seurat_clusters` column was added to the `meta.data` slot. Is there a purpose for it?  It does not add any additional information (it's a copy of `Idents`, which itself is a copy of the clustering results) and it is never used as the only [mention of it](https://github.com/satijalab/seurat/blob/25b830b0dd6f12538516f0faf9a3b3ddfd0ce6d8/R/clustering.R#L181) in the code is where it is being assigned:
```
Idents(object = object) <- colnames(x = clustering.results)[ncol(x = clustering.results)]
object[['seurat_clusters']] <- Idents(object = object)
```

I am concerned because now there is the same data stored in 3 different places, potentially adding an additional challenge for troubleshooting.

**Comment by satijalab** [comment]
Thanks for your concern. I requested this column, as it’s helpful to store the most recent results of a clustering analysis - without having to go back and check the exact resolution that was used, or in case Idents got overwritten with something else. We’ve found it useful in our analyses, and I don’t have concerns about having the same information stored in the object.
