### ISSUE TITLE
violin plot shows just random noise when there are no data

### ISSUE THREAD

**Issue by brianjohnhaas** [satijalab/seurat#146]
I stumbled across a case where a violin plot was generated that showed a nice distribution of data points but only after careful inspection of the axis it was clear that it was centered at zero and extending +- 2x10^-5 , so essentially just slightly above and below zero.    The SingleVlnPlot function  appears to add this little bit of noise to each of the data points.   The I came across this was because all my percent.mito points were set to zero, as the mito genes were encoded differently in a data set such that the grep ^MT didn't pick them up.   

When there's no variation in the raw data, maybe it's better to report an error rather than to generate the violin plot containing just the added noise.

**Comment by satijaml** [comment]
Agreed- we'll implement in a future release

**Comment by satijalab** [comment]
Agreed - we'll fix in a future release

**Comment by andrewwbutler** [comment]
Fixed in 2.1.0
