### ISSUE TITLE
the problem ofsubsetbyyPredicate

### ISSUE THREAD

**Issue by LHXANDY** [satijalab/seurat#1460]
I want to creates a Seurat object containing only a subset of the cells in the original object.But I don not know how to choose two subset.,such as :pbmc1 <- SubsetByPredicate(object = pbmc_small, vars.use = c("res.1"), predicate = " res.1=='3'|res.1='4'")

**Comment by andrewwbutler** [comment]
Hi,

All subsetting functionality can be done with `subset` in version 3. E.g.

```R
subset(pbmc_small, res.1 %in% c(3, 4))
```

In version 2, you can try the `SubsetData` function if `SubsetByPredicate` isn't working for you.
