### ISSUE TITLE
sctransform on imputed data

### ISSUE THREAD

**Issue by jingyaq** [satijalab/seurat#1461]
Hi, 

I'm eager to try out the new SCTransform() normalization method, but am wondering if it works properly on imputed data? My first attempt gave me the following warning message:
1: In dpois(y, mu, log = TRUE) : non-integer x = 47.879000
2: In dpois(y, mu, log = TRUE) : non-integer x = 3.104000
3: In dpois(y, mu, log = TRUE) : non-integer x = 5.569000

My guess is this has something to do with the characteristics of our imputed data, which has very few 0s and the number of features detected (nFeature_RNA) is the same for each cell. 

Is the poisson model warning okay or should I not be using this normalization on imputed data?

Thanks so much for your help!

**Comment by satijalab** [comment]
Thanks for the question. SCTransform cannot be applied to imputed data.
