### ISSUE TITLE
Load my own data

### ISSUE THREAD

**Issue by arararararararar8** [satijalab/seurat#1464]
Hello,

I am trying to load my own data into seurat.
This is single cell rna seq data in a .csv file type with different rows indicating genes and columns indicating cells. How can I read this data using seurat? Can you give me the code for doing this?

(Disclaimer: I don't have the matrix, genes and barcodes file as given in the pbmc example on the seurat website)

**Comment by andrewwbutler** [comment]
Hi,

You just need to read the data into R and provide that matrix to the `counts` parameter of `CreateSeuratObject`.

**Comment by arararararararar8** [comment]
Can you give me the code to do this please? 
It is a tab delimited file (I have the same file in two formats .csv and .txt). 
![image](https://user-images.githubusercontent.com/49823305/56908826-b1973600-6a6c-11e9-9777-3845c28685fd.png)

Here is a screenshot if you need it. Can you please tell me how to best read this data and create the object?

**Comment by andrewwbutler** [comment]
You can checkout this [link](http://www.cookbook-r.com/Data_input_and_output/Loading_data_from_a_file/) for how to read data into R.

**Comment by arararararararar8** [comment]
_library(readxl)
a<-read_excel('raw data 10x.xlsx')
dim(a)
data<- CreateSeuratObject(raw.data = a, min.cells = 3, min.genes = 500, project = "a")_

I get this error message:
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric
