### ISSUE TITLE
ScaleData use own normlized data in Seurat3

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1465]
Hi : 
    In Seurat2.3.4 there is a "data.use" pharamater in ScaleData that can be useful to scale my own normalized and batch correct data. Whats the same pharamater in Seurat3.0 ?
    And if I want to supply a data to ScaleData function how to do while I dont want replace the  scObject[["RNA"]]@data !

Best

**Comment by andrewwbutler** [comment]
Hi,

If you want to run `ScaleData` on your own batch corrected/normalized matrix, you can call `ScaleData` on that matrix directly (just pass the matrix to the `object` parameter instead of a Seurat object) and it will return a scaled version of the matrix.

**Comment by mojaveazure** [comment]
`ScaleData` in Seurat v3 no longer supports a `data.use` or similar parameter, but it can now run directly on a matrix thanks to S3 Method Dispatch (see official documentation [here](https://stat.ethz.ch/R-manual/R-devel/library/base/html/UseMethod.html) or a summary from Hadley Wickham [here](http://adv-r.had.co.nz/S3.html)). If you look at `methods(generic.function = 'ScaleData')`, you'll see we have three methods, one for Seurat objects, one for Assay objects, and one default method designed for matrices.

```R
> library(Seurat)
> methods(generic.function = 'ScaleData')
[1] ScaleData.Assay*   ScaleData.default* ScaleData.Seurat* 
see '?methods' for accessing help and source code
```

This will allow you to do anything `ScaleData` does on your own matrix, returning a scaled data matrix. Then, use `SetAssayData` to add it back to your Seurat object.
