### ISSUE TITLE
Add orig.ident metadata depnding on the name of the cells

### ISSUE THREAD

**Issue by ChaDuss** [satijalab/seurat#1466]

**Comment by ChaDuss** [comment]
Hello,

My dataset contain cells that are coming from four different samples, and the name of the cells coming from sample one are named ; ATGCATGCATGC_1, from sample 2 : ATGCATGCATGC_2 etc... ;
how can i add in metadata the origin of the cells ?

**Comment by SeadonXing** [comment]
Just use names.field = 2, names.delim = "_" in CreateSeuratObject

**Comment by ChaDuss** [comment]
Thank you :-)

Le lun. 29 avr. 2019 à 15:32, SeadonXing <notifications@github.com> a
écrit :
