### ISSUE TITLE
Markdown render problem

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#1468]
Hi,

I found a previous issue mentioning a similar problem (#1426 ) but I think my situation is a bit different.

I have converted a previously analyzed v2 object to v3 object and just trying to create some plots. I encountered the following error message when executing `TSNEPlot` function during markdown rendering:

```
Quitting from lines 33-58 (WT_TCKO_tumor_scseq.rmd) 
Error in `[[.Seurat`(object, reduction) : 
  Cannot find 'rmarkdown::render' in this Seurat object
Calls: <Anonymous> ... do.call -> DimPlot -> Embeddings -> [[ -> [[.Seurat
```

When I interactively execute code chunks in the markdown file, there aren't any issues. Also, when I omit the `TSNEPlot` chunk, rendering completes with no issues. I have created markdown reports with Seurat v3 before with no problem, but this piece of code doesn't seem to work. Any ideas what might be happening here? Attaching the rmd file for reference.

[WT_TCKO_tumor_scseq.zip](https://github.com/satijalab/seurat/files/3128225/WT_TCKO_tumor_scseq.zip)

Thanks
Atakan

**Comment by atakanekiz** [comment]
When I use `DimPlot` function instead `TSNEPlot`, the problem went away. 

```
DimPlot(combined, cols = cluster_colors, label=T, repel=F) +
  NoLegend()

```

I will close this issue now. Hopefully, it would help someone running into the same problem.

**Comment by lc822** [comment]
Did you manage to fix the problem with TSNEPlot and render?

**Comment by atakanekiz** [comment]
When I use `DimPlot` function instead `TSNEPlot`, the problem went away. See my previous code as an example.
