### ISSUE TITLE
$integrated@data and $RNA@data have the same value

### ISSUE THREAD

**Issue by Lijinluu** [satijalab/seurat#1471]
Hi,

Thanks for developing this amazing tool  for us. I am using Seurat V3 to cluster scRNA-data. I want to integrate two datasets. But when I finished the following commands: 
`twodatasets.anchors<-FindIntegrationAnchors(object.list = reference.list, dims = 1:30)`
` object.integrated<-IntegrateData(anchorset = twodatasets.anchors,dims = 1:30)`
 , as [https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html] provided, 
  I found the object.integrated@assay$RNA@data and object.integrated@assay$integrated@data have the same value.
   Could someone please tell me why ,and how I can solve this problem?

Thank you in advance
JinLu

**Comment by andrewwbutler** [comment]
Hi,

How are you checking for equality? Can you provide a reproducible example?

**Comment by Lijinluu** [comment]
Thanks for your reply!  
I checked the  value using the following  code:
`object@array$integrated@data[1:3,1:5]`
the result just as the following:(not really value ,i just give an  example)
gene1    0.1    0.2    0.345      .        0.4  
gene2      .             .               .          0.1      0.2
gene3    0.3     0.4      0.5           .         0.3
then,i used the following code check the object$array$RNA@data:
`object$array$RNA@data["gene1",1:5]`
the values are  equal  with object@array$integrated@data["gene1",1:5],as following:
gene1    0.1    0.2    0.345   .       0.4

the object$array$RNA@data seems like the correct normalized value,while the object@array$integrated@data value just equal to object$array$RNA@data.

But, today, I found  only one dataset'value   are  equal ,the other  dataset' value are  changed. Is Seurat select a  dataset as a reference  when it integrate  two datasets?
[ps:  I  splited  the data as two datasets by the "SplitObject "step using split.by  parameter :    SplitObject(object = SeuratObject, split.by = "group")]

**Comment by andrewwbutler** [comment]
Yes, if you are integrating two datasets, only the values in one of them will change. You can think about it as "correcting" one dataset onto the other.  You can find more details on how the integration procedure works in our pre-print [here](https://www.biorxiv.org/content/10.1101/460147v1)

**Comment by Lijinluu** [comment]
Thanks for your feedback.
