### ISSUE TITLE
How to reduce the over-fitting in Seurat version3 when Intergration?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1472]
Hi Seurat team : 
    I know that the Intergration workflow is so strong to intergrate each different batch, technology sampels. But also in the paper "Comprehensive integration of single cell data" you methioned "For each anchor pair, we assign a score based on the consistency of anchors across the neighborhood structure of each dataset.Incorrect anchors tend to have low scores and so are downweighted in future analyses " so that it can keep unique cell type in some samples. Sometimes it may also intergrate this "unique cell types" in my sample.
    So my question is , if I think the results are over-fitting, what parameter can I adjust to change cell score and weighted to make more strict thereshold to intergrate data. Just like "k.anchor = 5, k.filter = 200, k.score = 30, max.features = 200" in FindIntegrationAnchors or "k.weight = 100, weight.reduction = NULL, sd.weight = 1" in IntegrateData function.

Thanks

**Comment by rmenafra** [comment]
I'm also very interested in this topic, what are the parameters affecting a possible "over-fitting" of the data and if there is a way to determine 'a-priori' what are the best settings for a specific set of anchors.
Thanks

**Comment by timoast** [comment]
Hi, you can try decreasing `k.weight` if you think the integration is too aggressive, although we have found in most cases the default parameters will work well.
