### ISSUE TITLE
Seurat V2.3.0 on R v 3.5.3

### ISSUE THREAD

**Issue by araksm** [satijalab/seurat#1473]
Hi,

I'm trying to install Seurat V2.3.0 on R v 3.5.3
> devtools::install_version(package = 'Seurat', version = package_version('2.3.0')) 

and am getting an error:

ERROR: dependency ‘fpc’ is not available for package ‘Seurat’

How could I fix that?

Thank you,
Araks

**Comment by SeadonXing** [comment]
install.packages("fpc") 
 BTW, recommand you to install Seurat version 3.0.

**Comment by araksm** [comment]
Thanks Seadon!

Maybe it's the problem of fpc on R v 3.5.3. I'm unable to install it.

I switched to Rv3.3 to be able to use Seurat V2.3.0.

**Comment by araksm** [comment]
Regarding Seurat v3: I'm unable to update V2 object into V3 by UpdateSeuratObject(). Is there a function that performs this task? 

Thanks,
Araks

**Comment by SeadonXing** [comment]
I dont use UpdateSeuratObject(). I just install a latest R version 3.5.3 and then  run install.packages("Seurat"). It will instll the Seurat 3.0 for me automaticlly. Hahaha!
Hope help !

**Comment by mojaveazure** [comment]
Hi Araks,

The [latest release of fpc](https://cran.r-project.org/package=fpc) appears to be available for R 3.6 or higher only. If you need an older version, you can download an older source from [fpc's archive](https://cran.r-project.org/src/contrib/Archive/fpc/) and install it using `R CMD INSTALL` from the command line.

As for `UpdateSeuratObject`, this is present in Seurat v3 and will update a v2 object to a v3 object.

```R
object <- UpdateSeuratObject(object = object)
```
