### ISSUE TITLE
FindMarkers:Wilcoxon rank sum test  P values

### ISSUE THREAD

**Issue by VasoLG** [satijalab/seurat#1474]
Hi,

I am running the following command:
<cluster6.markers <- FindMarkers(object=test.combined, ident.1=6, min.pct = 0.25)>

The command is running without issues, but some of my top values are 0. For example:
	p_val	avg_logFC	pct.1	pct.2	p_val_adj								
gene1	0	0.942198033	0.319	0.006	0								
gene2	0	-0.809253551	0.73	0.95	0								
gene3	0	-0.907071366	0.301	0.773	0								
gene4	0	-0.998257734	0.229	0.71	0								
gene5	0	-1.103430836	0.242	0.747	0								
gene6	5.88E-303	-1.000369918	0.146	0.64	8.36E-299								
gene7	8.44E-278	-1.00885924	0.097	0.566	1.20E-273								

How can I calculate the exact P value for the first 5 genes?

Thanks

**Comment by andrewwbutler** [comment]
Hi,

This is because the p-value for these genes is smaller than can be represented in R and so it get's assigned as 0.
