### ISSUE TITLE
Restore support for diffusion maps

### ISSUE THREAD

**Issue by RoganGrant** [satijalab/seurat#1475]
I'm wondering if you intend to begin supporting Diffusion Map plotting again with Seurat in the near future. Writing custom functions for this purpose is not particularly difficult, but they are likely to break as Seurat is updated.

**Comment by mojaveazure** [comment]
Hi Rogan,

Diffusion map visualization can be done with [`DimPlot`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.0/topics/DimPlot), assuming store it as a `DimReduc` object in the Seurat object, by passing the name of the diffusion map reduction to the `reduction` parameter.

We currently don't have a timeline for restoring `RunDiffusion`, but that should be easy for a stable custom function using Seurat's getters and setters. Please see our [Developer's Guide](https://github.com/satijalab/seurat/wiki) for more details about the objects in Seurat v3 and how to interact with them.

**Comment by laijen000** [comment]
Hello! 
I would like to store my diffusion map results as a custom dimensional reduction in Seurat. I looked at the tutorial's example for MDS, but am having a hard time getting it to work with my destiny results. 

# diffusion map matrix from destiny 
tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1],
                  DC2 = eigenvectors(dm)[, 2]))
# add as custom dim reduct 
micro[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro))
# plot dimplot 
DimPlot(micro, reduction="dm")

When I try to plot, I get the error: Error in Embeddings(object = object[[reduction]])[cells, dims] : 
  subscript out of bounds

Has anyone been able to store destiny results as a custom dimensional reduction and have advice on how to do so? Thank you so much!

**Comment by TiongSun** [comment]
Hi,

Your codes seem fine. I used the following codes, which are basically similar to yours and it works.

diffmap <- read.delim(file =  './diffmap.csv'), header = TRUE, sep = ",", row.names = 1)
diffmap1 <- data.matrix(diffmap)
dr <- CreateDimReducObject(embeddings = diffmap1, key = 'DC')
seurat.object[['DC']] <- dr
DimPlot(object = seurat.object, reduction = "DC") + coord_fixed(ratio = 1)

I think the reason in your case might be the matrix dimension is not right. Try checking seurat.object@reductions to see if the matrix size is the same as your tmp matrix.

Thanks. 



> Hello!
> I would like to store my diffusion map results as a custom dimensional reduction in Seurat. I looked at the tutorial's example for MDS, but am having a hard time getting it to work with my destiny results.
> 
> tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1],
> DC2 = eigenvectors(dm)[, 2]))
> micro[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro))
> DimPlot(micro, reduction="dm")
> 
> When I try to plot, I get the error: Error in Embeddings(object = object[[reduction]])[cells, dims] :
> subscript out of bounds
> 
> Has anyone been able to store destiny results as a custom dimensional reduction and have advice on how to do so? Thank you so much!

**Comment by maxbond233** [comment]
> DimReduc

Hi, you can just add the cell names in your matrix and it may work:

tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1]
                              , DC2 = eigenvectors(dm)[, 2]
                              , row.names = colnames(microSub))) ###
microSub[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro))
DimPlot(micro, reduction="dm")

Thanks

**Comment by maxbond233** [comment]
> Hello! I would like to store my diffusion map results as a custom dimensional reduction in Seurat. I looked at the tutorial's example for MDS, but am having a hard time getting it to work with my destiny results.
> 
> tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2])) micro[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro)) DimPlot(micro, reduction="dm")
> 
> When I try to plot, I get the error: Error in Embeddings(object = object[[reduction]])[cells, dims] : subscript out of bounds
> 
> Has anyone been able to store destiny results as a custom dimensional reduction and have advice on how to do so? Thank you so much!

tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1]
                              , DC2 = eigenvectors(dm)[, 2]
                              , row.names = colnames(microSub)))
microSub[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro))
DimPlot(micro, reduction="dm")

**Comment by maxbond233** [comment]
> Hello! I would like to store my diffusion map results as a custom dimensional reduction in Seurat. I looked at the tutorial's example for MDS, but am having a hard time getting it to work with my destiny results.
> 
> tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1], DC2 = eigenvectors(dm)[, 2])) micro[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro)) DimPlot(micro, reduction="dm")
> 
> When I try to plot, I get the error: Error in Embeddings(object = object[[reduction]])[cells, dims] : subscript out of bounds
> 
> Has anyone been able to store destiny results as a custom dimensional reduction and have advice on how to do so? Thank you so much!

Hi, you can add cell names in your matrix and it may works:
tmp <- data.matrix(data.frame(DC1 = eigenvectors(dm)[, 1]
                              , DC2 = eigenvectors(dm)[, 2]
                              , row.names = colnames(microSub))) ###
microSub[["dm"]] <- CreateDimReducObject(embeddings = tmp, key="DC_", assay=DefaultAssay(micro))
DimPlot(micro, reduction="dm")

Thanks
