### ISSUE TITLE
Error in CombinePlots

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1476]
When I use CombinePlots function to illustrate two ggplot2 object,
 there is a error occour : " Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :  Viewport has zero dimension(s).

When I use plot_grid I  can also find this error. 
 But the plot1 and plot2 can plot and show seperatly.

**Comment by andrewwbutler** [comment]
Hi,

Try increasing the size of your viewport panel.

**Comment by SeadonXing** [comment]
Thanks andrewwbutler , I slove this problems.

**Comment by El-Castor** [comment]
Hi SeadonXing, 

Ho do you solve this issues please, I have the same trooble when I run Seurat? 

Thanks in advance

**Comment by mattmaxwell1995** [comment]
Hi SeadonXing,

How did you solve this problem? I'm having the same problem as El-Castor. 

Thanks

**Comment by El-Castor** [comment]
Hi mattmaxwell1995, 

You can used Dimplot to plot your tsne. Combineplot doesn't work in a markdown.

**Comment by denvercal1234GitHub** [comment]
Try to increase your viewport window (the window that you "zoom" out your plot), and set label=FALSE. It should help.
