### ISSUE TITLE
Error in VariableFeaturePlot

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1477]
Hi :
    I first run : 
```
scObject <- FindVariableFeatures(object = scObject, selection.method = "vst", nfeatures = 2000);
plot1 <- VariableFeaturePlot(object = scObject)
``` 
 everything is OK. But I then want to change method to select genes by runing 
```
scObject <- FindVariableFeatures(object = scObject, selection.method = "dispersion", nfeatures = 2000); 
plot1 <- VariableFeaturePlot(object = scObject);
``` 
There is an error : Error in switch(which(dispersion.names %in% colnames(x = object[[]]))

**Comment by mojaveazure** [comment]
Thank you for bringing this up; we are working on a fix

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by SeadonXing** [comment]
Sincere thanks !
