### ISSUE TITLE
How to choose parameters for JackStraw tests?

### ISSUE THREAD

**Issue by chansigit** [satijalab/seurat#1478]
does parameters like num.rep, prop.freq affect the results? and how?

**Comment by andrewwbutler** [comment]
The `num.rep` parameter will change how many times the resampling procedure is done. 

The `prop.freq` parameter will change the proportion of features (genes) that are randomly permuted in each random sampling. 

There is a balance between these two parameters that will trade off runtime speed for the accuracy of the resulting p-values/robustness of the results. Please see [this paper](https://academic.oup.com/bioinformatics/article/31/4/545/2748186) for a more in depth discussion.
