### ISSUE TITLE
Obtaining counts for clustered cells in integrated analysis

### ISSUE THREAD

**Issue by bioinfo28** [satijalab/seurat#1480]
I am running Seurat 3.0 and I want to integrate 2 or more samples/replicates, identify clusters and obtain raw RNA counts for each cell in each cluster for downstream analysis.

In my Seurat 2 pipeline, I used seurat.obj@raw.data to obtain counts. seurat.obj was built with RunCCA(object = d1, object2 = d2, genes.use = hvg.union ...) and further processed.
In my new Seurat 3 pipeline, I noticed that GetAssayData is not working for "counts", it returns an empty matrix.

When I request "data" in GetAssayData (d = GetAssayData(object = seurat.obj, slot = "data")) I get a populated matrix. However, dim(d) tells me that it's a 2000 x 22750 matrix. It seems IntegrateData() only uses 2000 genes? I couldn't find information in the help page.

Am I doing something wrong or only 2,000 genes are used to integrate data in Seurat 3 and I have to go back to each Seurat object before integration to obtain counts per cell?

Thank you.

**Comment by SeadonXing** [comment]
You should run  GetAssayData by using "RNA" assays. As they said in "https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html",  "After running IntegrateData, the Seurat object will contain a new Assay with the integrated expression matrix. Note that the original (uncorrected values) are still stored in the object in the “RNA” assay, so you can switch back and forth."
I am just a active user of Seurat.
Hope help

**Comment by andrewwbutler** [comment]
Please see #1447, #1198
