### ISSUE TITLE
counts slot in FeaturePlot

### ISSUE THREAD

**Issue by ltosti** [satijalab/seurat#1483]
Hi there,

Is it possible to select a different slot of the object when using the FeaturePlot function? For example, if one is interested in plotting counts instead of data?

Thank you!

**Comment by mojaveazure** [comment]
Hi,

It is currently not possible to change the slot for `FeaturePlot`; we are working on this and will update when we have more to report.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
