### ISSUE TITLE
CCA in Seurat 3

### ISSUE THREAD

**Issue by irmed** [satijalab/seurat#1484]
Hi! 

I have a question. As far as I understand, FindIntegrationAnchors runs CCA as initial step by default.
Is there any possibility to extract CCs from the integrated object or anchors and not to run RunCCA separately?

Thank you a lot in advance!

**Comment by andrewwbutler** [comment]
Hi,

`FindIntegrationAnchors` will run CCA between pairs of datasets to establish a low-dimensional space in which to find anchors. The results of these individual CCAs are not stored in the final object.
