### ISSUE TITLE
How is gene expression scaled in FeaturePlot?

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1485]
Hi,

I wanted to know the nature of normalization that's done by featureplot when it plots the gene expression. Is the scale bar showing the count log-base2 normalized? 

Thanks,
Maria

**Comment by SeadonXing** [comment]
I think it is the "normlized data loge-based"

**Comment by andrewwbutler** [comment]
Hi, 

`FeaturePlot` will display the normalized data (from the `@data` slot). Please see the documentation for `NormalizeData` for a description of the normalization procedures.
