### ISSUE TITLE
Which assays should be used in FindIntegrationAnchors for already intergrate object?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1486]
Hi Seurat team :
    I have three conditions, one condition for normal 5 samples, the second for 8 patient samples, the third for 7 patient with drug treat. I want to join them together analysis, so I choose the integration pipeline to perform.  I separate integrations for each condition of patients
. So now I have three integrated object normal/disease/drug which each of them have two assays "RNA" and "integrated",  and then I want to do final integration across the conditions. 
My question is (1) What steps should I start to integrate them, I guess may be "FindIntegrationAnchors" ?
                        (2) The FindIntegrationAnchors use the default assays to find anchors, for my situation I have already integrate for samples for each condition. If I want to intergrate condtion now, which assays should I use , "RNA" or "integrated"  and why ?  For each samples, we integrate them use "RNA" assays, for already integrated condition we use "intergrated" ?
                        (3) If use "integrated" assays, what`s the RNA assays data slot store? It will store the condition intergrated value not the raw value ?

Best

**Comment by andrewwbutler** [comment]
Hi,

1. Yes, you should start with `FindIntegrationAnchors`
2. You should use the "integrated" assays. 
3. The RNA assay will still store the unintegrated data. If you want to keep the results of the intermediate (within condition) integration, you should change the `new.assay.name` parameter in `IntegrateData` or it may be over written.

**Comment by SeadonXing** [comment]
Thanks andrewwbutler ！！！
