### ISSUE TITLE
Merging distinct datasets

### ISSUE THREAD

**Issue by thomasdwu** [satijalab/seurat#1487]
This is an analysis question.  Suppose I have two distinct datasets -- for ease of discussion, suppose one is from brain cells and one is from liver cells -- and I would like to merge them to create a sort of "atlas".  I am thinking that such an atlas could then be used with the TransferData procedure to label data from a query object that has both types of cells.  The two datasets might already have had IntegrateData applied to each of them.

What would be the procedure for merging such two distinct datasets?  Am I right that IntegrateData might not be appropriate, because it is looking for common structure between the two datasets?  Or will IntegrateData work between two different types of cells?

**Comment by andrewwbutler** [comment]
Hi,

The integration procedure in v3 relies on the assumption that at least a subset of cells share the same biological state. Therefore, if you're looking at two completely distinct datasets with no overlap, I wouldn't recommend running `IntegrateData`.

**Comment by saeedfc** [comment]
@andrewwbutler ; The same question. What would be the best strategy then. I am trying to integrate scRNA seq data between two cell types. One of the cell types say neurons are already publicly available. I want to merge it with immune cell scRNA seq data that I have. I want to use this combined matrix with CellPhoneDB, a pipeline that detects receptor-ligand interactions. CellPhoneDB requires one single matrix. What would be the best idea as I don't expect any common cell type subsets between them? Just merge and go ahead with the usual normalization?
