### ISSUE TITLE
scTransform error

### ISSUE THREAD

**Issue by gouthamatla** [satijalab/seurat#1488]
Hi All,

I am trying to run ScTransform on my single cell data (not 10X based).

```
test.data <- read.table("gene_counts.txt", header=T, row.names=1)
test.data <- as(as.matrix(test.data), "dgCMatrix")
test <- CreateSeuratObject(counts = test.data)
```

I dont have MT genes in my quantifications **so I did not run the following command**

`PercentageFeatureSet(object = test, pattern = "^MT-", col.name = "percent.mt")`

If I run 
`test <- SCTransform(object = test, verbose = FALSE)`

I am getting the following error:

```
Error in glm.fit(x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  : 
  NA/NaN/Inf in '
```x'

I am following this vignette https://satijalab.org/seurat/v3.0/sctransform_vignette.html


sctransform_0.2.0 
Seurat_3.0.0 

Thanks,
Goutham A

**Comment by ChristophH** [comment]
Do you have NA, NaN, or Inf values in your matrix? Are the column sums in your matrix all the same?

If you can share your `test.data` dgCMatrix, I can have a look.

**Comment by ChristophH** [comment]
Your data includes cells with very few non-zero features, including a cell that has a total UMI count of zero. If I remove 44 cells with less than 100 total UMI `SCTransform` does not throw an error.

**Comment by gouthamatla** [comment]
Ok. Thanks. I will filter cells before running sctransform.

**Comment by hmassalha** [comment]
hi @ChristophH, 
I have the same issue. I filtered out cells with less than 100 UMIs, still having the same problem! 
I have no NA, NAN, inf... any suggestions? 

Best, HM
