### ISSUE TITLE
Cells removed by integrated analysis?

### ISSUE THREAD

**Issue by 23sd98fg** [satijalab/seurat#1489]
Hi, 

I had already analyzed a 10x scRNA-seq data set with two conditions (control and stimulated) using the alignment function in Seurat version 2. Now, I was interested to test and compare the new Seurat version 3 using the integrated analysis and including sctransform.

In my two conditions only one group shows Egfp expression which I was able to detect in the previous analysis (due to an adapted reference transcriptome). In the new integrated analysis with the new Seurat version I cannot detect Egfp expression anymore. Another gene that I realized was not detected anymore was Prf1. 

I get the follwing warning/error if I plot following genes with the DotPlot function: 
DotPlot(immune.combined, features= c("Egfp", "Prf1", "Cd8a"))
Warning: Found the following features in more than one assay, excluding the default. We will not include these in the final dataframe: Egfp, Prf1
Warning message:
In FetchData(object = object, vars = features) :
  The following requested variables were not found: Egfp, Prf1

I wonder if this could be related to the removal of anchors classified as incorrect?
Could you comment on this and do you have a solution to this problem?

Thank you for your reply in advance!
Laura

**Comment by andrewwbutler** [comment]
Hi Laura,

Cells shouldn't be removed by the integration procedure (you can check by looking at the cell number before and after). What's likely happening is that the genes that you're interested aren't in the 2000 that are used by default in `IntegrateData`. Please see #1447, #1198 for further discussions.

**Comment by 23sd98fg** [comment]
Hi Andrew, 

Thank you for the quick reply and the easy solution! 

I got a vector with all genes as follows:
g.1 <- rownames(x = ctrl)
g.2 <- rownames(x = stim)
genes.use <- unique(c(g.1, g.2))

I hope this is the correct way? Thanks again for your help!

**Comment by 23sd98fg** [comment]
Hi Andrew, 

The analysis using the new integration strategy seems to produce nice results. But the new normalization strategy, sctransform, generated an unexpected result. As I mentioned Egfp expression is present in the dataset but only in one of the two groups that were integrated. With the new normalization strategy it is,  although to a very weak extent, also present in the other group which cannot be true.

Would you have an explanation for this? Could this be avoided by adjusting some parameters? If not I would stick to the old normalization strategy as this seems to be more reliable.

Thank you very much for your comment on this issue in advance.

**Comment by timoast** [comment]
Is this a consequence of the normalization strategy by SCTransform or of the integration? SCTransform should not convert any 0 counts to >0, this would only happen during integration. You can check this by comparing the RNA and integrated assays

**Comment by 23sd98fg** [comment]
I can only look at Egfp expression using the integrated assay. When I switch to RNA assay it gives me the follwing error: 
Error in cut.default(x = avg.exp.scaled, breaks = 20) : 
  'breaks' are not unique

I also analyzed the same data using the integration strategy and the "old" normalization scheme. Then, the Egfp expression was correctly only detected in the stimulated group. I wonder if this could be due to the fact that the ScaleData step was run after integration not beforehand as discussed here: https://github.com/ChristophH/sctransform/issues/4.
As this could apparaently change the biological results. Could this be the issue here as well? As I understand you are currently working on the implementation of this possibility (first scaling for each group the integrating the data)?

**Comment by timoast** [comment]
> Error in cut.default(x = avg.exp.scaled, breaks = 20) :
'breaks' are not unique

Running what code gives that error?

The integration procedure aims to make the datasets more similar, and so it's not surprising that it would adjust GFP expression to be consistent across the datasets. For this reason you should use the integrated data to identify common cell states and compare expression values using the uncorrected data

**Comment by dwucsf** [comment]
> > Error in cut.default(x = avg.exp.scaled, breaks = 20) :
> > 'breaks' are not unique
> 
> Running what code gives that error?
> 
> The integration procedure aims to make the datasets more similar, and so it's not surprising that it would adjust GFP expression to be consistent across the datasets. For this reason you should use the integrated data to identify common cell states and compare expression values using the uncorrected data

@timoast: Can you elaborate on what you mean by "you should use the integrated data to identify common cell states and compare expression values using the uncorrected data"? Are you recommending to map the common cell states back onto the un-integrated, individual datasets?

**Comment by LiuYing732** [comment]
> Hi,
> 
> I had already analyzed a 10x scRNA-seq data set with two conditions (control and stimulated) using the alignment function in Seurat version 2. Now, I was interested to test and compare the new Seurat version 3 using the integrated analysis and including sctransform.
> 
> In my two conditions only one group shows Egfp expression which I was able to detect in the previous analysis (due to an adapted reference transcriptome). In the new integrated analysis with the new Seurat version I cannot detect Egfp expression anymore. Another gene that I realized was not detected anymore was Prf1.
> 
> I get the follwing warning/error if I plot following genes with the DotPlot function: DotPlot(immune.combined, features= c("Egfp", "Prf1", "Cd8a")) Warning: Found the following features in more than one assay, excluding the default. We will not include these in the final dataframe: Egfp, Prf1 Warning message: In FetchData(object = object, vars = features) : The following requested variables were not found: Egfp, Prf1
> 
> I wonder if this could be related to the removal of anchors classified as incorrect? Could you comment on this and do you have a solution to this problem?
> 
> Thank you for your reply in advance! Laura

hi, did you solve this problem? if you do, could you share it with me. I also meet this problem now.
