### ISSUE TITLE
Version 3 functions should raise an error when passed deprecated arguments

### ISSUE THREAD

**Issue by ilyakorsunsky** [satijalab/seurat#1495]
Great improvements in the interface for V3! 

In the downstream analysis functions, like RunUMAP, users are still allowed to pass the V2 argument "reduction.use". This argument is ignored and the default PCA is used instead (see example below). Please consider throwing an error when deprecated argument names are used. 

Runs with harmony
sc <- RunUMAP(sc, reduction = "harmony", dims = 1:20)

Runs with PCA
sc <- RunUMAP(sc, reduction.use = "harmony", dims = 1:20)

**Comment by mojaveazure** [comment]
Agreed, we are working on a way to handle this and will update later when we have more information to share. Thanks!

**Comment by ilyakorsunsky** [comment]
Awesome, thanks for the update!

**Comment by andrewwbutler** [comment]
Hi Ilya,

Just an update on this. We've added an internal `CheckDots` function which should try to catch most errors like these and give suggestions for the renamed parameters if you're using one of the common older ones. This is now available on the develop branch if you want to try it out and have any feedback.

**Comment by ilyakorsunsky** [comment]
Awesome, thanks for following up Andrew!
