### ISSUE TITLE
Venn Diagram Control vs. Stim

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1496]
Hello!

I was wondering if theres an easy way to visualize the number of DEGs and conserved genes between control and treatment? Such as:

- venn diagram for genes for each sample
- venn diagram for genes for each cluster 

Thanks!
Tara

**Comment by andrewwbutler** [comment]
Hi Tara,

There aren't any built in functions in Seurat that would allow you to do this directly. My recommendation would be to run `FindMarkers`/`FindConservedMarkers` to get lists of deferentially expressed genes that you could then feed into a package like [VennDiagram](https://cran.r-project.org/web/packages/VennDiagram/).

**Comment by Deepesh123gupta** [comment]
Hello, 

To follow up of the above question, I have three conditions to analyze. To know the common and unique genes between the conditions, first thing I need to do is to find the all gene lists for each of condition. How would be possible to pull out those genes ?

1. From the raw count matrix 
2.  From Integrated seurat dataset (by stim): Cell Conditions

I would be happy to do both ways 1 and 2, and see the difference in the venn diagram. 
Thanks
