### ISSUE TITLE
Violin plot hidden behind cells

### ISSUE THREAD

**Issue by piepertc** [satijalab/seurat#1497]
Hi Seurat team,

I am unable to see the actual distribution visualization in my violin plots as the data in front is just too dense. Do you have any advice on how to maybe make the data points smaller or just show a subset of them that match the distributions?

I appreciate your help! 

(Violin plots attached)
<img width="1410" alt="Screen Shot 2019-05-03 at 3 44 32 PM" src="https://user-images.githubusercontent.com/49733959/57164655-68bbe600-6dba-11e9-8c63-c270c7bf315b.png">

**Comment by unknowledgeable1** [comment]
Use a dot size = 0

**Comment by piepertc** [comment]
The only methods I can find that modify dot size don't seem to work in the VlnPlot function. I'm not super familiar with R and don't have a great intuition about how to accomplish this. Thanks for your help!

**Comment by rmenafra** [comment]
Assuming you are using Seurat3 then the option for the VlnPlot is to set pt.size = 0. This will hide completely the dots.
VlnPlot(object, features , pt.size = 0)

**Comment by piepertc** [comment]
That did the trick; thanks!

**Comment by ms-gx** [comment]
Is it possible to swap the order? Violin in front of dots.
