### ISSUE TITLE
seurat normalized data and TPM

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#1498]
Hi, 

I just had a quick question about the normalization scale factor.  I previously asked about the units of the normalized Seurat object (#1450) and you told me that it was like TPM but per 10 thousand.  So I was then wondering, if in NormalizeData() if I used scale.factor = 1000000, would that then be equivalent to TPM?  Are there any reasons I should avoid that?  Some people have asked me questions about showing TP10K rather than the more familiar TPM.

Thanks,

Leonard

**Comment by timoast** [comment]
Hi Leonard, this is an arbitrary scaling factor and it will make no difference if you use 1e4, 1e6, or any other number. This is used for convenience in scRNA-seq, as we typically have counts per cell much lower than in bulk RNA-seq, and so use the smaller counts per 10,000 rather than counts per million.

**Comment by suragnair** [comment]
The equivalence to TPM/TP10K seems wrong. I was unable to find a step where the counts are divided by gene length.

```R
>> print(rna@assays$RNA@counts[1:20,1])
AL627309.1 AL627309.5 AP006222.2  LINC01409     FAM87B  LINC01128  LINC00115 
         0          0          0          0          0          1          0 
    FAM41C AL645608.6 AL645608.2 AL645608.4  LINC02593     SAMD11      NOC2L 
         0          0          0          0          0          0          1 
    KLHL17    PLEKHN1      PERM1 AL645608.7       HES4      ISG15 
         0          0          0          0          0          6 
```

```R
>> rna_norm = NormalizeData(rna, scale.factor = 1e4, normalization.method="RC")@assays$RNA@data
>> print(rna_tpm[1:20,1])
AL627309.1 AL627309.5 AP006222.2  LINC01409     FAM87B  LINC01128  LINC00115 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.8044405  0.0000000 
    FAM41C AL645608.6 AL645608.2 AL645608.4  LINC02593     SAMD11      NOC2L 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.8044405 
    KLHL17    PLEKHN1      PERM1 AL645608.7       HES4      ISG15 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  4.8266431 
```

This is not length normalised. Please correct me if I'm wrong.

**Comment by igordot** [comment]
For UMI-based protocols, which is what most people use, each transcript is labeled with a barcode, so longer genes would not be expected to have more counts.

**Comment by suragnair** [comment]
Thanks for clarifying!
