### ISSUE TITLE
Error occur after IntegrateData in ScaleData by using "negbinom" method

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1499]
Hi Seurat team : 
    I do the IntegrateData and then I want to scale the data and regress out the cell cycle effect. 
    I run : 
```
DefaultAssay(object = scObject.integrated) <- "integrated"
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
scObject.integrated <- CellCycleScoring(object = scObject.integrated, s.features = s.genes, g2m.features = g2m.genes, set.ident = FALSE)
scObject.integrated <- ScaleData(object = scObject.integrated, vars.to.regress=c("S.Score", "G2M.Score"),model.use="negbinom")
```
There is a error occur : "Error in object[features, , drop = FALSE] : 
  invalid or not-yet-implemented 'Matrix' subsetting"
I think the error may induced by "use.umi" paramater that Regress on UMI count data. Default is FALSE for linear modeling, but automatically set to TRUE if model.use is 'negbinom' or 'poisson'
. While the "integrated" assays dont have the counts slot.
So does that mean after integrated data, I can only use linear model to scale data?

BTW, I find that "negbinom" perfrom better than "linear", and my cells number are enought to perform. In most times in my sample, linear cant regress out the cell cycle effect in my situation while negbinom can do. So if I want to use "negbinom" after IntegrateData in "integrated" assays, waht should I do.

Best

**Comment by SeadonXing** [comment]
BTW, I find that "negbinom" perfrom better than "linear", and my cells number are enought to perform. In most times in my sample, linear cant regress out the cell cycle effect in my situation while negbinom can do. So if I want to use "negbinom" after IntegrateData in "integrated" assays, waht should I do.

**Comment by timoast** [comment]
Hi, you can’t use negative binomial or poisson regression after integration because, as you say, the data is no longer UMI counts. If you want to regress out effects like cell cycle following integration you need to use a linear model.

**Comment by leonvgurp** [comment]
Hi, sorry for potential ignorance on the underlying principles, but is this also true for differential expression analysis? 

To be more precise, I get an error running FindAllMarkers on an integrated dataset using the "negbinom" test (see below). Which alternative would you suggest to use instead? Is the MAST test appropriate?

===

error:
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:
	Cell group 2 is empty - no cells with identity class 

===

This error repeats for all clusters

**Comment by timoast** [comment]
@leonvgurp we don't recommend performing DE on the integrated data, instead you should use the uncorrected data and include batch as a latent variable, for example:

```r
markers <- FindMarkers(object, assay = 'RNA', ident.1 = 1, ident.2 = 2, latent.vars = 'batch', test.use = 'LR')
```

**Comment by leonvgurp** [comment]
Thanks for your response! One follow-up question regarding that: can I pull the uncorrected data directly from the integrated data object, or should I create a separate object for this by merging the original datasets?

**Comment by timoast** [comment]
@leonvgurp the integrated data is stored in a different assay, and the uncorrected data will be present in the original assay. See the integration vignettes for more information: https://satijalab.org/seurat/v3.1/integration.html

**Comment by leonvgurp** [comment]
Great, that is actually fairly easy to manage this way. Thanks so much for your help!
