### ISSUE TITLE
batch correction suboptimal

### ISSUE THREAD

**Issue by brianjohnhaas** [satijalab/seurat#150]
Hi,

On a previously published data set that I've been experimenting with involving retinal bipolar cells, we have two batches of cells.  When we do batch correction using ComBat, it seems to work quite well.  I'd prefer to stay within Seurat for this, though, but when I run Seurat to regress out the batch signal, it doesn't appear to work as well as ComBat.   My example for this is available here:
http://rpubs.com/bman/303098
where you can just quickly look at the two most bottom tSNE plots where the one at the very bottom corresponds to ComBat corrected data and the one above is Seurat.

In case it's of interest, the data I'm using are available here:
https://github.com/broadinstitute/CEGS_single_cell_tx_workshop_Sept2017/tree/master/data
and one directory up is the Rmd

I'm preparing this material for a workshop we're hosting at the end of Sept. at the Broad, which is going to revolve around using Seurat-2 for exploring these data.

many thanks!

~brian

**Comment by satijalab** [comment]
Thanks Brian! also for the reproducible question :)

I agree that COMBAT is working well here, but to be honest, I don't see a huge difference between the methods. We could certainly add COMBAT to a future version of the package though (its not too challenging to run externally, as you show, but indeed would be a bit easier for tutorials if everything was self-contained).

We'll try to get to it soon, but if you're up for it, we'd love you to try a pull request!

**Comment by brianjohnhaas** [comment]
Sounds good!  I'll work on a pull req later in the week.
