### ISSUE TITLE
Error after run RunTSNE by using "RNA" assay

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1502]
Hi Seurat team : 
    I first run : 
```
scObject <- RunTSNE(object = scObject, reduction = "pca", dims = 1:30, check_duplicates = FALSE)
```
Everything is OK. Even I know that the default assay here is "RNA" , I still want to remind me which assay I used. So I run
```
scObject <- RunTSNE(object = scObject, reduction = "pca", dims = 1:30, check_duplicates = FALSE, assay="RNA")
```
There is an error : Error in RunTSNE.matrix(object = object[[, dims]], assay = DefaultAssay(object = object)

Best

**Comment by mojaveazure** [comment]
Hi @SeadonXing,

Thanks for catching! We are working on a fix and will update when we have more information.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
