### ISSUE TITLE
Error in usemethod

### ISSUE THREAD

**Issue by Lei-GitHub** [satijalab/seurat#1504]
When I want to use whichcells method in Seruat, it shows the following message:
Error in UseMethod(generic = "WhichCells", object = object) : 
  no applicable method for 'WhichCells' applied to an object of class "seurat";
How to fix this kind of issue? Thank you very much.

**Comment by timoast** [comment]
Hi, it looks like you're trying to use an old Seurat object (not v3). Run `UpdateSeuratObject` to update the object to the Seurat v3 class before running functions from the v3 package

**Comment by Lei-GitHub** [comment]
Thank you very much. Yes, I need to Updateseuratobject to update the object. Thank you.
