### ISSUE TITLE
AssessNodes error

### ISSUE THREAD

**Issue by yanwu2014** [satijalab/seurat#151]
Hey it seems like AssessNodes is looking for clusters that aren't there (possibly renamed from BuildClusterTree?) and giving me this error:

```R
Error in WhichCells(object = object, ident = group2) :
  Identity : 14 not found.
Calls: AssessNodes ... pblapply -> lapply -> FUN -> AssessSplit -> WhichCells
```

Code snippet:

```R
se.obj <- FindClusters(se.obj, reduction.type = "pca", dims.use = 1:pcs.use, resolution = 0.8, k.param = 30, save.SNN = T, prune.SNN = 1/20)
se.obj <- BuildClusterTree(se.obj, do.reorder = T, reorder.numeric = T)
node.scores <- AssessNodes(se.obj)
```

**Comment by leonfodoulian** [comment]
Hello,

You can set `reorder.numeric = F` in `BuildClusterTree()` to keep the identities computed by `FindClusters()` unchanged. Check also the documentation (by running `?BuildClusterTree`) for more details.

Best,
Leon
