### ISSUE TITLE
DoHeatmap and SubsetData not working for Integrated Analysis

### ISSUE THREAD

**Issue by MediciPrime** [satijalab/seurat#1510]
I have performed an integrated analysis using the following Seurat 3.0 [tutorial](https://satijalab.org/seurat/v3.0/immune_alignment.html).  It was a great tutorial, thank you for creating it!  

Now I am trying to create a Heatmap using the DoHeatmap function however I am running into the following error: 
`Error in GetAssayData(object = object, slot = slot)[features, cells, drop = FALSE] : no 'dimnames' attribute for array`
Could someone please tell me how to solve this problem so that I can create some heatmaps?

My other question is regarding how to subset data.  When I use the SubsetData function for non-integrated analyses everything works fine:
`sub <- SubsetData(ifn.combined, subset.name='active.ident', ident.use=c('1', '2', '3')`
However once again the integrated analysis throws a wrench in my plans by giving me the following error for the same code:
`Error in FetchData(object = object, vars = subset.name, cells = cells, : None of the requested variables were found: active.ident`.  
Could someone please help me solve this problem as well?  

Thank you!

**Comment by MediciPrime** [comment]
For SubsetData I figured out that I had changed 'active.ident' to cluster names thus I wasn't working when I provided the SubsetData function with number.  

However I am still not sure why I wasn't able to create even a basic heatmap with the DoHeatmap function.  So some help with this would be very much appreciated. :)

**Comment by satijalab** [comment]
Apologies for the confusion- if you want to do a heatmap of integrated data, please make sure the default assay of your object is set to integrated, i.e.

`DefaultAssay(immune.combined) <- 'integrated'`

Alternately, set the `assay` parameter in DoHeatmap to `integrated`

If you want to do a heatmap on the RNA assay (original data), then make sure you first run `ScaleData` on the RNA assay.

**Comment by tmccra2** [comment]
You have previously posted that you suggest using integrated assay for cluster identities, but recommend original RNA assay for downstream analysis.

So for the heatmap here, would you recommend performing with integrated assay or doing the ScaleData and using RNA?

**Comment by Dragonmasterx87** [comment]
@tmccra2 excellent point mate. So what I think, is one can set your default assay to RNA:

```
# Look at your default assay
DefaultAssay(object = objectname)
# Change default assay to RNA, saves information in the "RNA" assay
DefaultAssay(object = objectname) <- "RNA"

```

and then, perform your scaling without fear:


```
# An intresting observartion. All that integration, and no scalling of the RNA dataslot, prevents # doheatmap from picking up genes other than in scale.data slot
objectname <- NormalizeData(objectname)
all.genes <- rownames(objectname)
objectname <- ScaleData(objectname, features = all.genes)
```


Devs please correct me if I'm wrong, cheers for the help.

**Comment by Dragonmasterx87** [comment]
In continuation of my comment above 

First of all, in the vignette, the devs suggest NOT scaling an integrated dataset. I agree. ALl of your analysis, including DE-genes to heatmaps SHOULD BE DONE ON THE data scaled and normalized in the 'integrated' slot. Here are some of my opinions::

1. The integrated slot, contains data derived from 3000 most variable genes, if you perform a heatmap calculation on the RNA sot, even if you do something like `NormalizeData` you will not be a able to isolate variable genes for your heatmap, and the heatmaps may look 'okay-ish' but not accurate in my opinion, because if you calculated markers from your RNA slot, that means you're NOT looking into genes in the Variable gene bin, rather the entire dataset. THIS IS WRONG.

2. Finding marker genes for clusters based on your integrated data-analysis will give you genes which while they originate from your integrated, 3000 most variable genes slot, will enable you to accurately look at genes that are a part of your over-arching integrated data-analysis.

3. The heatmaps from running the analysis on the integrated data are gorgeous. Compromise on your DE gene analysis, by selecting the default 10% of expressing cells rather than the 50% of expressing cells, and you will STILL get an optimal result because you are selecting from your variable genes withing the integrated slot.

My apologies for the lack of brevity! Just thought I'd share, please let me know if you think I am still wrong. Cheers!

🐉

**Comment by Dragonmasterx87** [comment]
I deleted everything I said before because I just discovered `VariableFeatures`
Restrict your analysis to Variable features only throughout your entire analysis.

```
object.markers <- FindAllMarkers(object = object, features = VariableFeatures(object, assay = 'SCT'),
                                                                                only.pos = TRUE, 
                                                                                min.pct = 0.25, 
                                                                                logfc.threshold = 0.7, 
                                                                                assay = 'SCT3', 
                                                                                slot = c('data'))

object.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)

top50 <- object.markers %>% group_by(cluster) %>% top_n(n = 50, wt = avg_logFC)
DoHeatmap(object = object, 
          features = top50$gene, 
          disp.min = -1, 
          disp.max = 1) + scale_fill_gradientn(colors = colorRampPalette(c("#0200ad", 
                                                                           "#fbfcbd", 
                                                                           "#ff0000"))(256))
```
Enjoy!

🐉

**Comment by JoaoGabrielMoraes** [comment]
Hi @Dragonmasterx87 ,

Thanks for posting your code! I've tried it using my own integrated object but it's not working. The command runs fine, but no plot is generated. Any thoughts on what's going on? 

Below is my code:
```
object.markers <- FindAllMarkers(object = singlecell.combined, features = VariableFeatures(singlecell.combined, assay = 'integrated'),
                                                                                only.pos = TRUE, 
                                                                                min.pct = 0.25, 
                                                                                logfc.threshold = 0.25, 
                                                                                assay = 'integrated', 
                                                                                slot = c('data'))

object.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)

top10 <- object.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)

DoHeatmap(object = singlecell.combined, 
          features = top10$gene, 
          disp.min = -1, 
          disp.max = 1) + scale_fill_gradientn(colors = colorRampPalette(c("#0200ad", 
                                                                           "#fbfcbd", 
                                                                           "#ff0000"))(256))
```

**Comment by Dragonmasterx87** [comment]
Hi @JoaoGabrielMoraes ! 

So this issue has been talked about before #1277 check it out, but the colution as provided by @andrewwbutler seems to be:

```
plot <- DoHeatmap(object = hc.tsne, features = top10$gene) + NoLegend()
ggplot2::ggsave(filename = "feature.png", plot = plot) # can add additional parameters similar to png 
```

You can try saving as pdf or tiff, just change .png to .pdf 

Hope it works!

🐉

**Comment by JoaoGabrielMoraes** [comment]
@Dragonmasterx87 ,

That worked for me, thanks a lot!! It has to do with the format that the plot is saved. PDF worked for me. 

Thanks again!!
