### ISSUE TITLE
pbmc tutorial small error

### ISSUE THREAD

**Issue by JonThom** [satijalab/seurat#1512]
In the [pbmc](https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html) tutorial, the QC filtering step is currently
`pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)`

I think it should be `percent.mt < 0.05`

**Comment by lshepard2154** [comment]
The current filtering should be correct I believe. Keeping everything below 0.05 would remove too many cells. Note that in this new version, the expressions within the subset function are to keep the cells (thus, keeping all cells which have percent.mt < 5, in other words, removing everything > 5).

**Comment by satijalab** [comment]
The line in the tutorial is correct. We are removing outlier cells with < five percent mitochondrial reads, hence the `percent.mt < 5`. 

Apologies for the confusion. Previously, we had the `percent.mito` column actually store the fraction (not percentage) of mitochondrial reads, but have fixed this now.
