### ISSUE TITLE
Seurat CellCycleScoring "not have enough features"

### ISSUE THREAD

**Issue by BrunoGuillotin** [satijalab/seurat#1513]
Hi all,

I saw many people use the function CellCycleScoring on seurat (V3) with success. I am working on plant and we don't have all these long list of cell cycle marker. But I used 30 genes for g2m and 30 genes for S phase.
But when I try to run the function I got the error:
Error in AddModuleScore(object = object, features = features, name = name,  : 
  The following feature lists do not have enough features present in the object: S.Score exiting...The following feature lists do not have enough features present in the object: G2M.Score exiting...

I checked and the 60 genes are present in my data set. However only 30 out of 60 are present in the assay$Integrated part. (22 in G2M and only 8 in S phase). 

What is the minimum of gene to have in the G2M or S list ?
Is the function CellCycleScoring use the 2000 integarted genes ?

Thank you very much for your help.

**Comment by timoast** [comment]
You can change the set of genes to be corrected during the integration using the `features.to.integrate` argument in the `IntegrateData` function. By default we correct only the variable genes, which is why you have 2000 genes in the integrated assay. You could add the cell cycle genes to the list of genes to integrate in order to retain the full list of 60.

**Comment by BrunoGuillotin** [comment]
Hi Tim,

Thanks for your help, but actually what I want to do is to remove the effect of cell cycle because I get a specific cluster of cell all in G2/M phase. But in that cluster I have cells from very different tissue all mixed together. 
So in a sens I don't want to integrate using these genes. I could manually remove them from the integrated assay (although I don't really know the command) but I would like to introduce a cell cycle score to each cells so I can keep track of their cycle stage when they will be correctly clustered. Is there a reason why CellCycleScoring is not working in my case ?

**Comment by lengfei5** [comment]
I have a naive question, which is how to get the list of cell cycle markers, i.e. genes for S phase and those for G2/M phases, because I am working on C. elegans.  
Do we have to manually curate from the literature ?

**Comment by BrunoGuillotin** [comment]
Hi,

Yes I combine markers from different publications to have enough genes.
There is, at least for plant, no perfect list ready to use, yet.
Bru

**Comment by lengfei5** [comment]
Many thanks @BrunoGuillotin for your answer, which is very helpful.
I saw that you have 22 genes in G2M and 8 genes in S, which is already enough from what you see in your data ?
