### ISSUE TITLE
Seurat Version 3 Vlnplot in integrated analysis

### ISSUE THREAD

**Issue by rajasreemenon** [satijalab/seurat#1514]
Hi,
I am getting negative values for one dataset when I do integrated analysis of two seurat objects  and view the gene expression per cluster using vlnplot. Please see the plot below.
Any suggestion is greatly appreciated.
![image](https://user-images.githubusercontent.com/43355566/57396979-9bd6ee80-7199-11e9-889c-4cb7e265b566.png)
Thank you,
Raji

**Comment by rmenafra** [comment]
I think it's related to the active assay you have. If you don't switch that from Integrated to RNA then you see those negative values. You can switch assay by typing DefaultAssay(object.combined) <- "RNA". Hope this helps.
Best,
Roberta

**Comment by rajasreemenon** [comment]
Thank you Roberta.

Raji

________________________________

**Comment by timoast** [comment]
We recommend visualizing the uncorrected data, which you can do by switching the assay as pointed out by @rmenafra
