### ISSUE TITLE
FeaturePlot main title as vector

### ISSUE THREAD

**Issue by kevmei** [satijalab/seurat#1515]
Hi, in the previous Seurat version, using vector.friendly=T allowed me delete the gene name/plot title when I import my plot into Adobe Illustrator because it was a separate object from the plot. In the new Seurat v3, using AugmentPlot actually makes the  gene name/plot title part of the PNG image rather than as a separate object that can be deleted.

I would like to keep the gene name as the plot title so I can identify what plot I'm looking at, but I would like to delete this gene name when I work in Illustrator. Is there some way I can save my plot as a PNG and the title separately as another vector?

Thank you!

**Comment by satijalab** [comment]
Apologies for this - @mojaveazure will correct me if I am wrong, but this does appear to be incorrect behavior for `AugmentPlot`, which should not store the plot title as part of the PNG. We will fix in an upcoming update. In the mean time, you can of course add the plot title in Adobe Illustrator itself.

**Comment by andrewwbutler** [comment]
A current work around is to add the title after running `AugmentPlot`.  E.g.

```R
p <- DimPlot(pbmc_small)
p <- AugmentPlot(p)
p + ggtitle("title")
```

**Comment by kevmei** [comment]
Thank you so much for the help!

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by brunetc** [comment]
Thanks for solving this issue. I noticed than after using AugmenPlot, the scale bar is gone. How can I keep it in the plot? Thanks!

**Comment by el-hodiri** [comment]
Same issue as latest message from @bruntec (scale bar is gone). Also, dots are now no longer round (they look like they're elongated horizontally?).  This is after using AugmentPlot on a FeaturePlot.
