### ISSUE TITLE
Heatmaps with multiple metadata annotations

### ISSUE THREAD

**Issue by AMA111** [satijalab/seurat#1516]
Dear Developers,

I would like to ask if there is a a way of plotting multiple annotations (Clusters, cell type, original Id, others ) from the metadata to the top of the heat map after doing DE analysis .. Like this one:
![image](https://user-images.githubusercontent.com/29317258/57441488-5e7e6980-724a-11e9-9f96-871de539d67a.png)

If not, do you have in-mind some suggestions. Thank you in advance!

Best,
Abdelrahman

**Comment by satijalab** [comment]
Unfortunately this is not currently something we support in Seurat, but there are packages in R (for example, the `heatmap.plus` package, which do support this. It is something we will consider adding in a future version
