### ISSUE TITLE
FindConservedMarkers does not work if one cluster is empty

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#1517]
Dear all, 

I used the Seurat pipeline to recluster cells from different donors with high variablity. Basically, instead of ctrl vs stim, I used donor 1 thru 5. And it works brilliantly.

Now I want to find conserved clusters: Like you want to know which markers are conserved in NK cells in the example (https://satijalab.org/seurat/v3.0/immune_alignment.html); I now want to know which markers are conserved in all donors. 

**For 1 cluster it works well:** 
`donor.markers <- FindConservedMarkers(donor.combined, ident.1 = 0, grouping.var = "donor", verbose = FALSE)
`
**For combining 2 clusters it also works but gives a warning I dont understand:**
`donor.markers.02 <- FindConservedMarkers(donor.combined, ident.1 = c(0,2), grouping.var = "donor", verbose = FALSE)

> `Warning messages:
> 1: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 2: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 3: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 4: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 5: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 

**However, now I want to find conserved markers in 5 clusters** (because they are 5 subtypes). Then it fails because cluster 14 has zero cells in donor 4 (which is correct, I checked!).
`donor.markers.5clusters <- FindConservedMarkers(donor.combined, ident.1 = c(0,2,3,5,13,14), grouping.var = "donor", verbose = FALSE)`

> Error in WhichCells.Seurat(object = object, idents = ident.use.1) : 
>   Cannot find the following identities in the object: 14_donor4
> In addition: Warning messages:
> 1: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 2: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 3: In if (!ident.use.1 %in% Idents(object = object)) { :
>   the condition has length > 1 and only the first element will be used
> 

How should I avoid this? Should I use FindMarkers instead? Because I really want to have the conserved markers, meaning: which markers are conserved in all the donors. Help?

**Comment by satijalab** [comment]
Thanks for taking a look at this. We'll keep this issue open and fix in an upcoming version - instead of throwing an error, `FindConservedMarkers` should perform tests only in cases where the cluster is present (i.e. in your case, it should exclude donor 4).

In the meantime, you can use FindMarkers, but run individually on cells from each Donor (you can use the `subset` function) to accomplish this

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by stephanyfoster** [comment]
Hello, 
I would like to find conserved markers for all clusters as well and know which cluster the markers belong to. I tried a similar code to the one in this thread (FindConservedMarkers(donor.combined, ident.1 = c(0,2,3,5,13,14)) and it works for me except it doesn't specify cluster identity.

In the past I did something like this to extract markers per cluster and save in a file:
###
for (cluster in seq(0,length(unique(EB@meta.data$res.0.5))-1)){
  clustermarker <- FindConservedMarkers(EB, ident.1 = paste(cluster), grouping.var = "Con", print.bar = FALSE, logfc.threshold = 0, return.thresh = 1.1)
write.table(clustermarker,file=paste("./ConservedMarkers/",sample1,"_",sample2,"_Cluster_",cluster,"CONSERVED.txt",sep=""),quote=F,sep="\t")
}
###
But this set up doesn't work when I', extracting markers in the integrated dataset. I receive an error:
Warning: Identity: -1 not present in group mb. Skipping mb
Warning: Identity: -1 not present in group eb. Skipping eb
Error in names(marker.test) <- levels.split : 
  'names' attribute [2] must be the same length as the vector [0]


any tips for this? thank you!!
