### ISSUE TITLE
change colors in Dimplot UMAP

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#1518]
Hi ,
I merged 3 10X datasets (V0, V6, V8) and performed successfully the umap regression:

DimPlot(mergetest2.big, reduction = "umap", group.by = "orig.ident")
each of the 3 dataset is colored with seurat default colors but I would like to change the colors of each orig.ident. as following:
V0=red 
V6=grey
V8=grey

how should I proceed?
Thank you very much!!
Shen

**Comment by mojaveazure** [comment]
Hi Shen,

As seen in the documentation for [`DimPlot`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.0/topics/DimPlot), you can pass colors to the `cols` argument. to specify colors:

```R
DimPlot(object = mergetest2.big, reduction = 'umap', group.by = 'orig.ident', cols = c('V0' = 'red', 'V6' = 'grey', 'V8' = 'grey')
```

**Comment by shendong124** [comment]
Hi Paul,
Thanks a lot!!
Shen


Le ven. 10 mai 2019 à 07:53, Paul Hoffman <notifications@github.com> a
écrit :
