### ISSUE TITLE
should you perform SCTransform on a subset?

### ISSUE THREAD

**Issue by zbgaber** [satijalab/seurat#1519]
Hello, 
I've been getting some really great results with Seurat 3.0 - this isn't a bug but just asking whether I'm doing something correctly.  My usual pipeline has me doing the analysis twice - first on all cells, then on just a subset of cells from the lineage my lab is interested in.  My question is how I should handle the subset.  The dataset has been processed with SCTransform to produce corrected UMI, find variable genes, and scale.  After I pull out the subset of interest - I'm wondering if I should perform SCTransform again on it.  My thinking is that it would be better to just find a new set of genes variable within the subset and rescale those using FindVariableFeatures and ScaleData.  My thinking is that SCTransform is modelling each gene based on all cells in the dataset and to repeat SCTransform on a subset is just to do the modelling with fewer datapoints and that I'm better off leaving the existing SCT corrected UMI.  Am I right in this?

**Comment by timoast** [comment]
It might not be necessary but there’s certainly no issue in running SCTransform on a subset of the data.
