### ISSUE TITLE
 FindAllMarkers - Error in rbind(deparse.level, ...) 

### ISSUE THREAD

**Issue by sebastiangornik** [satijalab/seurat#152]
When I run: FindAlMarkers

I get:

|++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 01s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 01s
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
In addition: Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded

Any suggestions?

Thx!

**Comment by satijalab** [comment]
This can occur if individual clusters don't have any transcriptomic markers. We'll improve in a future release, but you can either use FindMarkers, or lower the threshold for DE  to solve.
