### ISSUE TITLE
x and y coordinate of t-SNE plot

### ISSUE THREAD

**Issue by trueth1206** [satijalab/seurat#1520]
Hi,

I am trying to project the t-SNE/UMAP from Seurat to loupe cell browser (10x). I used the RunTSNE and RunUMAP function and they went well in R. But I could not find the x coordinate and y coordinate of each cell/barcode, which are needed for the projection to loupe cell browser. Could anybody tell me how to find these the value in my data? Thank you very much!

**Comment by satijalab** [comment]
You can use the `Embeddings` function to fetch embeddings from a Seurat object, after tSNE or UMAP has been run, for example:

`embds = Embeddings(pbmc_small[["tsne"]])`

Hope that helps!

**Comment by vertesy** [comment]
For the record, as of `v3.1.4`, they are stored in `obj@reductions$tsne`.
