### ISSUE TITLE
RunPCA showed Error unused argument (pc.features=features)

### ISSUE THREAD

**Issue by ningli-microbiome** [satijalab/seurat#1521]
I start using Seurat version 3, and running through the PBMC example. My R version is 3.5.

I run into the issue like this:
> pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
Error in irlba(A = t(x = object), nv = npcs, ...) :
  unused argument (pc.features = features)

I don't really understand it the error, because there is no "pc.features" argument in RunPCA. I stuck here, and couldn't move forward. Any help will be really appreciated.

**Comment by mojaveazure** [comment]
Hi Ning,

This is a bug in `RunPCA`, we are working on a fix and will update when we have more to share.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
