### ISSUE TITLE
 error:could not find function "WriteH5AD"

### ISSUE THREAD

**Issue by ikohideonbush** [satijalab/seurat#1522]
Hi :
I am very confused about this error(current  Seurat version: 3.0.0.9000 ):

When I tried to export the result of Seurat,  
I could just  get the information of the "WriteH5AD" fuction after typing "?WriteH5AD() " 
but failed to use this funtion.

The error is expressed as the  following:
___________________________________________________________________________________________________
Error in WriteH5AD(fish.combined, file = "fish.3t.integrated.afterQC.h5"): **could not find function** "WriteH5AD"
Traceback:
___________________________________________________________________________________________________
Do you have any idea ? Thanks in advance.

**Comment by mojaveazure** [comment]
Hi,

`WriteH5AD` is not currently functional. In order to export data to Scanpy, please save it as a loom file instead via `as.loom`

**Comment by ikohideonbush** [comment]
> Hi,
> 
> `WriteH5AD` is not currently functional. In order to export data to Scanpy, please save it as a loom file instead via `as.loom`

Sadly I just got a feedback --could not find function "as.loom"].
:(   T^T
