### ISSUE TITLE
featureplot problem

### ISSUE THREAD

**Issue by Lei-GitHub** [satijalab/seurat#1523]
Anyone can help me, I use the FeaturePlot to plot the tsne data. 
When I plot three genes, all these genes seem no expression in my data, please check the summary:
<img width="669" alt="Screen Shot 2019-05-10 at 2 20 09 PM" src="https://user-images.githubusercontent.com/26446235/57548383-c4442180-732e-11e9-9861-2d57ab695802.png">
However, the FeaturePlot shows one genes('Olfm4'), has high expression in the plots,
![FeaturePlot](https://user-images.githubusercontent.com/26446235/57548507-17b66f80-732f-11e9-81b7-6771330bd680.jpg)

FeaturePlot(Con_intestine_cells_tsne,features = c('Lgr5','Olfm4','Ascl2'),min.cutoff = 'q9', pt.size = 1)

I notice that in this gene's plots, the legend is a value with several number after decimal point. how to fix this problem? Thank you very much.

**Comment by yuhanH** [comment]
It seems that Olfm4 only has one non-zero value in your data.
You could try this.
```
FeaturePlot(Con_intestine_cells_tsne,features = 'Olfm4', pt.size = 1)
```

**Comment by Lei-GitHub** [comment]
Hi YuHan, Thank you very much. It fixed by your suggestion.
