### ISSUE TITLE
findtransferanchor

### ISSUE THREAD

**Issue by lo2811** [satijalab/seurat#1526]
Hi,
I'm trying to use FindTransferAnchor with  reference and query SCT seurat objects. This is what I used:
anchors <- FindTransferAnchors(reference = reference, query = query, dims = 1:20, npcs= NULL)

However, I ran into this error:
Projecting PCA
Error in Loadings(object = reference[[reduction]])[features, dims] : 
  no 'dimnames' attribute for array

I tried "project.query=T" but it didn't help.

Can you please help? Thank you!

**Comment by yuhanH** [comment]
Current Seurat doesn't support this `FindTransferAnchors` on the SCT normalized dataset, and if you want to use `FindTransferAnchors` or `FindIntegrationAnchors`, you have to use `NormalizeData` to normalize data.  But it will be added soon.
