### ISSUE TITLE
Integration or Label transfer?

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat#1527]
Hi,
first of all thanks for the great Seurat v3!
I have an analysis question:
I have scRNA data from 10X libraries (sequenced in 5 separate runs). The data represents multiple individuals divided in 2 conditions (patient and control) and 2 time points (before and after stimulation).
The libraries were obtained with HTO strategy, and in each run multiple antibodies were pulled, but each antibody represent a unique combination of donor#_condition_stimulation per run.
I had to first HTO-demultiplex the 5 run separately (because the same antibody was associated to 1 donor in run1 but to a different donor in run2 for instance).
After demultiplexing and selection of singlets I merged the data into a unique Seurat object to perform integrated analysis. I have to specify that different donors may change in cell number, ranging from the smallest (200) to the biggest (2000). The goal of the analysis would be compare the drug effect after stimulation, between the two groups (patients and control).
I wonder what's the best strategy to perform integrated analysis?
-Integrate the 5 demultiplexed runs? (instead of just merging them) and then re-iterate integration on the treatment (before/after) and condition (patient/control)
-merging the 5 demultiplexed runs and integrate twice: once based on condition (patient/control) and the second time based on stimulation (before/after).
-Is the workflow from https://satijalab.org/seurat/v3.0/immune_alignment.html more suited for this comparison or it's better the https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html?
-Since the label transfer works with one condition at the time would that mean that I need to sequentially process 1 variable at the time? 

The five sequencing runs were performed at the same sequencing depth, at the same time, just on different lanes.

Sorry for the very long question and thanks in advance for your time.
Best,
Roberta

**Comment by satijalab** [comment]
Hi Roberta,

Thanks for the question - we understand the complexities here in choosing a path forward. We can't advise on specific strategies for particular experiments, but I can say the following.

1. The purpose of our integration workflows is to help shared cell types group together across different experiments. However, this is not always necessary - especially for technical replicates. We typically first run the standard Seurat workflow, and then repeat with an integration workflow only if necessary.
PS - the same strategy applies to, for example, the regression of mitochondrial percentage. If this technical covariate does not drive heterogeneity in your dataset (i.e. MT genes do not define a PC), then this is not necessary.

2. When choosing between integration or transfer-  we generally suggest using integratedata when you feel your reference is incomplete, and will benefit from adding more cells or replicates (i.e., you expect to discover new clusters by pooling datasets together). If you are happy with your existing set of cluster IDs in your reference, you can run the transfer workflow.
