### ISSUE TITLE
Error in percent.mito

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#153]
Hi,

I am following the seurat tutorial in analyzing the pbmc data. I am getting an error in the step 
percent.mito <- colSums(pbmc@raw.data[mito.genes,])/colSums(pbmc@raw.data)

Error in colSums(pbmc@raw.data[mito.genes, ]) : 
  'x' must be an array of at least two dimensions

Although, when I check the dimensions of pbmc@raw.data it shows
> dim(pbmc@raw.data)
[1] 13714  2700

Do you have any idea where it is going wrong?

Thanks,

Bibaswan

**Comment by andrewwbutler** [comment]
Hi Bibaswan,

You need to have the Matrix package loaded. If you want to be explicit about it, you could write `percent.mito <- Matrix::colSums(pbmc@raw.data[mito.genes,])/Matrix::colSums(pbmc@raw.data)`

**Comment by ghoshal** [comment]
The Matrix package is already loaded. But I'll write it explicitly and see if that works.

Thanks
