### ISSUE TITLE
Adjusting DoHeatMap color scale

### ISSUE THREAD

**Issue by sophiecowman** [satijalab/seurat#1531]
Is there any way of setting the color scale in DoHeatMap so that 0 is always a specific color e.g white?

This is what happens currently: - you can see that 0 is not in the centre so this can be a little misleading. 
![image](https://user-images.githubusercontent.com/50600588/57658963-dd9ed500-759d-11e9-995e-749cb854c4d2.png)

I can use display.max and display.min to 'even' out the scale like this: 
![image](https://user-images.githubusercontent.com/50600588/57659041-25256100-759e-11e9-82b2-d903d47383ff.png)

but this also means I have clipped off some of the data and it becomes a little less informative. 

My code is as follows:
DoHeatmap(object = cluster.averages,features = c("GENE1", 'GENE2', 'GENE3'), size = 3, disp.max = 1.4, disp.min = -1.5) + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdBu")))

Any help with this would be greatly appreciated!

**Comment by yuhanH** [comment]
Try to use `scale_fill_gradient2` which can set middle point and color. 

```
DoHeatmap(object = cluster.averages,features = c("GENE1", 'GENE2', 'GENE3'), size = 3, disp.max = 1.4, disp.min = -1.5)+ scale_fill_gradient2( low = rev(c('#d1e5f0','#67a9cf','#2166ac')), mid = "white", high = rev(c('#b2182b','#ef8a62','#fddbc7')), midpoint = 0, guide = "colourbar", aesthetics = "fill")
```

**Comment by sophiecowman** [comment]
Works great thanks!
