### ISSUE TITLE
Seurat v3.0 error in SubsetData

### ISSUE THREAD

**Issue by KatjaRM** [satijalab/seurat#1532]
Hello,

I am trying to run SubsetData in Seurat v3.0 on an object that was created with an earlier version and updated via UpdateSeuratObject. Unfortunately, in whatever combination I am trying SubsetData (with idents =  or cells = ) it always returns the error 

> Error in Embeddings(object = object[[dr]])[cells, ] :   subscript out of bounds

Here is an example:

First of all using 

`WhichCells(object, c = ("Clust1", "Clust2")`

returns a list of cells, as expected.

However, running 

`X <- SubsetData(object, WhichCells(object, c = ("Clust1", "Clust2")`

returns the error above. The same is true when using other ways of subsetting data (with or without WhichCells, as apparently it can be run directly in v3). I have tried cells = list, ident.use, ident.remove. All of them returned the same error. 

Even simply running `X <- SubsetData(object, ident.use = Clust1)`
returns the error.

Any idea of what the issue is?

Best,

Katja

**Comment by mojaveazure** [comment]
What happens if you use `subset` instead?

```R
subset(x = object, idents = c('Clust1', 'Clust2'))
```

**Comment by KatjaRM** [comment]
Yes, also when running this it throws the same error.

> Error in Embeddings(object = object[[dr]])[cells, ] : 
  subscript out of bounds
