### ISSUE TITLE
Issue using FeaturePlot with "split.by" 

### ISSUE THREAD

**Issue by ahoffrichter** [satijalab/seurat#1533]
Hi, 

I just started working with Seurat. I Have a scRNA dataset with a control (ctrl) and a knock-out (KO) sample and want to compare the different cell types. 
To get a first impression I wanted to visualize the expression of certain marker genes in the t-SNE plot using FeaturePlot. I used the argument "split.by" in order to see the expression in the ctrl and KO side by side. 
For two genes I got a weird picture. In the ctrl cells the genes are only sparsely expressed, but in the KO it looks as if the gene is expressed with the same value in every cell. (all have the same shade of purple, see picture)
![Example](https://user-images.githubusercontent.com/23699647/57699211-937a2a00-7657-11e9-8e18-8ccbc2132c33.png)
I wanted to check the expression values and used this command: 
`FetchData(object= KO, vars =  "PENK")`
this returned an error:
Error in FetchData(object = KO, vars = "PENK") : 
  None of the requested variables were found: PENK

For the ctrl the command works and I can see the expression values for the different cells. 
Does that mean, that in the KO sample there are simply no cells expressing PENK? But why are the cells in the graph then colored as if it is expressed? 
Or did I lose the data regarding PENK in KO somewhere? 

I hope you can help me. If any more information is needed, I'm happy to provide it. 
Cheers, 
Anne

**Comment by ahoffrichter** [comment]
Hi, 
maybe I can give you a bit more information, on how I processed the data:

`### Set up control object
ctrl <- CreateSeuratObject(counts =ctrl.rawdata, min.cells = 3, min.features = 200, project = "CTRL_E")
ctrl$KO <- "CTRL"
ctrl[["percent.mt"]] <- PercentageFeatureSet(object = ctrl, pattern = "^MT-")
## Filter cells, only keep cells with more than 200 and less than 7500 features, and less than 5% MT-genes
ctrl <- subset(x=ctrl, subset= nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt <5)
ctrl <- NormalizeData(object = ctrl, verbose = FALSE)
ctrl <- FindVariableFeatures(object = ctrl, selection.method = "vst", nfeatures = 2000)
### Set up KO object
KO <- CreateSeuratObject(counts =KO.rawdata, min.cells = 3, min.features = 200, project = "KO_E")
KO$KO <- "KO"
KO[["percent.mt"]] <- PercentageFeatureSet(object = KO, pattern = "^MT-")
## Filter cells, only keep cells with more than 200 and less than 7500 features, and less than 5% MT-genes
KO <- subset(x=KO, subset= nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt <5)
KO <- NormalizeData(object = KO, verbose = FALSE)
KO <- FindVariableFeatures(object = KO, selection.method = "vst", nfeatures = 2000)
### Combine Data from ctrl and KO
### Identify Anchors
E.anchors <- FindIntegrationAnchors(object.list = list(ctrl, KO), dims = 1:20)
E.combined <- IntegrateData(anchorset = E.anchors, dims = 1:20)
### Perform an integrated analysis
DefaultAssay(object = E.combined) <- "integrated"
### Run the standard workflow for visualization and clustering
E.combined <- ScaleData(object = E.combined, verbose = FALSE)
E.combined <- RunPCA(object = E.combined, npcs = 30, verbose = FALSE) 
### t-SNE and Clustering
E.combined <- RunUMAP(object = E.combined, reduction = "pca", dims = 1:20) 
E.combined <- FindNeighbors(object = E.combined, reduction = "pca", dims = 1:20) 
E.combined <- FindClusters(E.combined, resolution = 0.5)
### Feature Plot 
DefaultAssay(object = E.combined) <- "RNA"
FeaturePlot(E.combined, features = c("PENK"), split.by = "KO")
`

**Comment by ahoffrichter** [comment]
I'm still having this problem. It happens with several genes that are only lowly expressed in one condition and not at all in the other. 
Is it somehow possible to define, if there are only 0-values, they appear as leightgrey?

**Comment by andrewwbutler** [comment]
Hi,

Can you try installing the latest development version? I believe a similar issue was recently addressed that might resolve this as well.  Install instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by ahoffrichter** [comment]
Hi Andrew, 
thanks a lot! This solved  the problem. Now, if the gene isn't expressed in any of the cells, all dots are grey.
