### ISSUE TITLE
Top 5 DE genes for each cluster was not included in variable genes

### ISSUE THREAD

**Issue by shokohirosue** [satijalab/seurat#1536]
Hello,

I found not all the genes retrieved from `FindAllMarkers` are present in integrated data. 
(My data gives more than 4000 genes with arguments `min.pct = 0.25`, `logfc.threshold = 0.25`, when there are only 2000 genes in integrated data.)

When I took 5 top genes from each clusters, there were 75 genes as there were 15 clusters, but only 52 genes out of 75 were present in integrated data.

Does this mean I should retrieve more than 2000 genes as variable genes?

Thank you.

**Comment by andrewwbutler** [comment]
Hi,

We've found that 2000 genes tends to work well across a wide range of analyses. If after clustering the integrated dataset, you find that you're missing a cluster that is defined by some of these marker genes you describe, you could certainly try augmenting the variable gene list.
