### ISSUE TITLE
Visualizing gene expression in 3D plots

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#1537]
Hello Devs!

So I have worked on a small chunk of code for making nice 3D tSNE plots of Seurat v3.0.0/3.0.0.9000/3.0.0.9150 [take a look](https://github.com/Dragonmasterx87/3D-Plotting-in-Seurat-3.0.0). Now, my question is, if I want to look at gene expression on this 3D plot what should one do?

Any tips would be helpful!!

Thank you for all the wonderful support!!!

**Comment by andrewwbutler** [comment]
Hi,

I would recommend using [plotly](https://plot.ly/r/) for this. Here's a quick example using PCA but you could substitute any other coordinates:

```R
library(plotly)
plotting.data <- FetchData(object = pbmc_small, vars = c("PC_1", "PC_2", "PC_3", "LYZ"))
plot_ly(data = plotting.data, x = ~PC_1, y = ~PC_2, z = ~PC_3, color = ~LYZ,
 type = "scatter3d", mode = "markers")
```

**Comment by Dragonmasterx87** [comment]
Cheers mate!

**Comment by Dragonmasterx87** [comment]
@andrewwbutler I have one question, how can I adjust the scale-key? Say I want the values to range from 0-5, not 0-8, how can I change that in the code you have suggested? 

Thanks!!

**Comment by andrewwbutler** [comment]
If you want similar behavior to the `min.cutoff` or `max.cutoff` parameters in `FeaturePlot`, you can use the `MinMax` function from Seurat to adjust the `plotting.data` matrix accordingly. 

```R
plotting.data <- MinMax(data = plotting.data, min = 0, max = 5)
```

**Comment by Dragonmasterx87** [comment]
Added you as a contrib. Here is the [code used](https://github.com/Dragonmasterx87/3D-Plotting-in-Seurat-3.0.0/blob/master/Seurat_3D_plotting_V1.R). Cheers.
