### ISSUE TITLE
Subset within function not using local variable

### ISSUE THREAD

**Issue by eloimercier-stemcell** [satijalab/seurat#1538]
I am attempting to pass some variables set within a function to "subset" but it doesn't find the variables. It seems that the subset function cannot see the variable set within the function.

Here is an example:
 ```
testFunction <- function(pbmc, threshold=c(200,2500)){
   sub <- subset(pbmc, subset = nFeature_RNA > threshold[1] )
     return(sub)
 }
 test <- testFunction(pbmc)
 Error in eval(expr = expr) : object 'threshold' not found 
```

Setting up the variable outside of the function works:
```
threshold=c(200,2500)
test <- testFunction(pbmc)
#OK
```

Any idea to resolve this issue?
Thanks!

**Comment by mojaveazure** [comment]
Hi Eloi, 

Please see https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002
