### ISSUE TITLE
Cant find common markers

### ISSUE THREAD

**Issue by drpatshah** [satijalab/seurat#1539]
Hello,
I am working with the integratedata function in seurat. 
I am using SCTransform on my initial seurat objects and then merging them using FindIntegrationAnchors and IntegrateData. 
However though both my original objects shows diffuse Cd3e expression (these are CD3 sorted cells), the integrated object does not show Cd3e expression. 

Is this to be expected?
Also is there documentation describing the IntegrateData function in more detail than the tutorial link below?
https://satijalab.org/seurat/v3.0/immune_alignment.html

Thank you so much for your help.

**Comment by yuhanH** [comment]
The object normalized by SCTransform cannot be used for integration, but it will be added soon. You have to use `NormalizeData ` for normalization now.
