### ISSUE TITLE
FeaturePlot Custom Scale without Binning

### ISSUE THREAD

**Issue by samuel-marsh** [satijalab/seurat#1540]
Hi,

Just wondering if there is another way to implement custom color scale in FeaturePlot() without binning the data into the number of colors.  Would like to retain gene expression values but implement custom color scheme.

Two particular instances I'm trying to make work:
1.  Setting NA expression values to gray and implement scale on the remaining.
`FeaturePlot(object, "gene", cols = c("lightgray", "yellow", "navy"))`
--This "works" except all scales are now 1-3 values

2.  Implement scales from viridis package
`plasma <- viridis(10, direction = 1, option = "C")`
`FeaturePlot(object, "gene", cols = plasma)`
--Again "works" except for the binning aspect which isn't what you really want when displaying several genes side-by-side

Thanks very much!
Sam

**Comment by satijalab** [comment]
Seurat FeaturePlot works by placing expression levels into bins and then assigning colors to cells based on bin assignment. I'm not quite sure how we could avoid doing this in any case. Please note that if you have multiple genes with different expression ranges you can bin based on quantiles (i.e. setting min and max 'q10' and 'q90'), which often is an effective solution.
