### ISSUE TITLE
FindMarker for differential gene expression statistic testing 

### ISSUE THREAD

**Issue by KingstonData** [satijalab/seurat#1543]
Hello,

I am wondering when using the FindMarker function to find the differentially expressed genes between group A and B, does it use expression of each gene in all the cells within group A to get an average expression and then compared that to the group B average for that particular to calculate the unadjusted p value?

Thanks, and sorry for the silly question.

**Comment by andrewwbutler** [comment]
Hi,

`FindMarkers` has a number of differential expression testing functions. The default test is a Wilcoxon rank sum test. For more details on other options, please see the `test.use` parameter in the function documentation.
