### ISSUE TITLE
Error in DotPlot

### ISSUE THREAD

**Issue by rushikapandya** [satijalab/seurat#1544]
Hello, 

I am trying to create a DotPlot with Seurat v3 and get an error message. 

This is DotPlot code for my dataset
```
DotPlot(combined, features = rev(top10), cols = c("blue", "red"), dot.scale = 8, split.by = "treat")
```

Error message:
```
Error in GetAssayData(object = object, slot = slot)[default.vars, cells,  : 
  invalid or not-yet-implemented 'Matrix' subsetting
```

Could you please advise on how to resolve this and the cause for this? Thank you!

**Comment by andrewwbutler** [comment]
Hi,

I'm not able to reproduce this issue. Can you check that the `top10` features are present in the object?

```R
all(top10 %in% rownames(combined))
```

**Comment by rushikapandya** [comment]
Hello Andrew,

Thank you for your response! No, I do not see top10 features in the object. I have added the code I use to generate the top10 markers below.
1. I have used FindAllMarkers to find markers for all the clusters. 
2. I wanted to select the top10 markers from each cluster
3. Plot dotplot for the 2 treatments and all clusters for the top 10 genes

I want to understand why the top10 genes are not present in `combined` seurat object.
'''
all.markers <- FindAllMarkers(object = combined, min.pct = 0.25, logfc.threshold = 0.25)
top10 <- all.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
DotPlot(combined, features = rev(top10), cols = c("blue", "red"), dot.scale = 8, split.by = "treat")
'''

**Comment by andrewwbutler** [comment]
Your second line is returning a tibble, not a list of genes. You can verify this by printing out `top10`. You can pull out the gene column with 

 ```R
top10 <- all.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) %>% pull(gene)
```

**Comment by rushikapandya** [comment]
Ahh. I see. Thank you so much, this works!
