### ISSUE TITLE
Seurat 3.0, what to do when top10 most variant genes are mitochondria?

### ISSUE THREAD

**Issue by ahdee** [satijalab/seurat#1545]
Hi so after subsetting 
`pbc =  subset(pbc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)`

I then normalize this with `NormalizeData` using LogNormalize 
I notice that a few of the top10 most variant genes are still mitochondria using `FindVariableFeatures`.  

I can see the 2000 top variant genes under,  `pbc@assays$RNA@var.features` I can easily get rid of all the mitochondria genes by just greping it out.  The question is should I? What is the recommended method here? thanks!

**Comment by denvercal1234GitHub** [comment]
Hi @ahdee - Did you find the solutions to your question? If so, would you mind explaining how or what you found out? I also detected mitochondrial genes and HSP genes being on top of my cluster markers. Thank you so much!

**Comment by ahdee** [comment]
In general having a lot of mitochondria genes is not a good sign; it basically means a lot of the cells were compromised or something was not optimal with the assay. However, its not the end f the world. You can regress this out and make sure that the the data make sense.  With that said, even if the data is good, you probably want to look back to see what went wrong and, sorry to say this, but you probably have to repeat the experiment.
