### ISSUE TITLE
How to analysis the subset cells of already intergrated object?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1547]
Hi Seurat team :
    I have integrated samples across different batch and different conditions. So I have a Seurat object with two assays (RNA and Integrated). Now I want to subset a specific cell type to investgate the subtypes within this cell type. I try to increase the resolution but limited cell types as I expected. So I want to recluster this specific celltypes. 
    I first obtain this type of cells by "subset".  And then I follow the standard Seurat pipeline to do following steps by using the "RNA" assay. "NormalizeData/FindVariableFeatures/ScaleData/RunPCA/FindNeighbors/FindClusters/RunUMAP and DimPlot."
    However , I can see the obviously batch effect appared again.  I think its due to I am not remove batch here. So I want to set the default assays to "integrated". But the dim row in integrate is 2000 variable genes. This 2000 genes is a variable set for all cell types. So I think its should not use "integrated" here.
    My question is, if the whole cell object have no batch, but the subset celltype have batch again, how to remove the batch effect in the subset of already integrated object ? Should I reintegrated all of this specific celltype for each sample again ?

Best

**Comment by HugoGonzalezVelozo** [comment]
Hi there, 
I'm having the same issue, this is the strategy that I'm following and I'm not seeing batch effect doing sub_clustering of an already integrated sample, by a previous issue, the Seurat team indicated that they DO NOT support the recalculation variable features in a subset of clusters after integration in Seurat 3. 

Subset_Cells <- SubsetData(Sample_integrated, subset.name = "seurat_clusters", accept.value = c(0, 1, 2), assay = 'RNA')

Subset_Cells <- ScaleData(Subset_Cells, verbose = FALSE, vars.to.regress = c("nCount_RNA", "percent.mt", "S.Score", "G2M.Score"))
Subset_Cells <- RunPCA(Subset_Cells, npcs = 50, verbose = FALSE)
Subset_Cells <- FindNeighbors(Subset_Cells, reduction = "pca", dims = 1:20)
Subset_Cells <- FindClusters(Subset_Cells, resolution = 0.5)
Subset_Cells <- RunUMAP(Subset_Cells, reduction = "pca", dims = 1:20)


cheers,


Hugo

**Comment by timoast** [comment]
You can change the set of features to be integrated by using the `features.to.integrate` argument in `IntegrateData`. By default, this is set to the `VariableFeatures`, which is why you find 2000 rows in the integrated assay. I would not recommend repeating the integration on a subset of the cells, using the integrated assay computed on the full dataset should be sufficient for subclustering.

**Comment by HichamAffia** [comment]
As Integration was performed on the complete dataset, I would not suggest to subset the integrated assay. You can subset based on individual batches and re normalize/scale from the raw counts.
Hope it helps!

**Comment by JingleW** [comment]
> You can change the set of features to be integrated by using the `features.to.integrate` argument in `IntegrateData`. By default, this is set to the `VariableFeatures`, which is why you find 2000 rows in the integrated assay. I would not recommend repeating the integration on a subset of the cells, using the integrated assay computed on the full dataset should be sufficient for subclustering.

Hi, timoast, 
As your suggestion, the "features.to.integrate" should be set to all the features when running "IntegrateData". So, should "nfeatures" in the "SelectIntegrationFeatuers" be set to all the features, if I want to further sub-cluster analysis of the integrated data?
Thanks.
