### ISSUE TITLE
What does this warnings mean, can I ignored this ?

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1548]
Hi Seurat team :
    I want to normalize and find variable genes for a list of Seurat object. I run : 
```
for (i in 1:length(x = scObject.list)) {
	scObject.list[[i]] <- NormalizeData(object = scObject.list[[i]], normalization.method = "LogNormalize", 
		scale.factor = 10000, verbose = FALSE)
	scObject.list[[i]] <- FindVariableFeatures(object = scObject.list[[i]], selection.method = "vst", 
		nfeatures = 2000, verbose = FALSE)
}
```
There are some warnings 
![image](https://user-images.githubusercontent.com/31844287/57862607-359e3b80-782b-11e9-865e-e64581312f31.png)

Whats this meaning, Can I ignored this ?

Best

**Comment by SeadonXing** [comment]
And I check that, these warnings caused by two samples. One sample is 144 cells, another is 707 cells. Both of them have 17211 genes.

**Comment by satijalab** [comment]
These warnings indicate uncertainty in the calculation of the mean-variance relationship, that we leverage to identify variable genes. This can happen when there are relatively few cells in the data. While results will be more robust with larger cell number (as for all tasks), they are not problematic in this context.
