### ISSUE TITLE
Cell cycle phases

### ISSUE THREAD

**Issue by alex20170908** [satijalab/seurat#155]
Hi there,
I was wondering why would you divide cell phase into 3 stages (S, G2/M and G1) instead of the canonical 5 stages (G1, G1/S, G2, G2/M, M and S)?
If I understand it correctly, all the cells with negative scores for both G2/M and S would be annotated as G1. Is is possible that those cells might acctually be M, G1/S or G2 instead?
Thanks very much in advance.
Regards,
Alex

**Comment by satijalab** [comment]
We don't actually use the annotations for cell cycle regression, but provide them in case they are of interest to the user. You can certainly set finer subdivisions or custom annotations based on the cell cycle scores, but our current approach is meant to be conservative.
