### ISSUE TITLE
Identify the percentage of mitochondria gene

### ISSUE THREAD

**Issue by trueth1206** [satijalab/seurat#1550]
Hi,

I tried use PercentageFeatureSet to identify the percentage of mitochondria gene. But the gene name of my dataset is shown in ensembl ID, but not the gene name. 
I am unable to use the function object[["percent.mt"]] <- PercentageFeatureSet(object, pattern = "^MT-") because the gene is not named as MT-xxxx. 

Instead, I tried 

object[["percent.mt"]] <- PercentageFeatureSet(object, features = c("ENSMUSG00000064336", "ENSMUSG00000064337", "ENSMUSG00000064338", "ENSMUSG00000064339", "ENSMUSG00000064340"...))

to key in all 37 mouse mitochondria genes. 
But I got an error

Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

Is there anyway to solve this issue?
Thank you very much.

**Comment by timoast** [comment]
Hi, can you confirm that all the genes you supplied to the `features` argument are present in the object?

```r
all(mito.features %in% rownames(object))
```

**Comment by trueth1206** [comment]
Hi, Thank you very much~ You are right. Some of the genes are not present in the object. I now run the function well.
