### ISSUE TITLE
Correlation Matrix in Seurat v3

### ISSUE THREAD

**Issue by ts3139** [satijalab/seurat#1552]
Hi all,

Just a quick question. I want to be able to plot a correlation matrix between my different clusters with a dendrogram, similar to how its done in Scanpy (see below):

![visualizing-marker-genes_99_1](https://user-images.githubusercontent.com/48571352/57889597-3cb15380-7803-11e9-8a93-b03c1155e18f.png)

I was wondering if there is a way to do this in Seurat v3, or if possibly this is something that can be added to newer versions of Seurat. Thanks!

**Comment by timoast** [comment]
Hi, we don't currently have plans to add something like this but we're open to a PR if anyone would like to contribute. It's fairly simple to compute this using the `AverageExpression` function, for example:

```r
av.exp <- AverageExpression(pbmc_small)$RNA
cor.exp <- as.data.frame(cor(av.exp))
cor.exp$x <- rownames(cor.exp)
cor.df <- tidyr::gather(data = cor.exp, y, correlation, c('0', '1', '2'))
ggplot(cor.df, aes(x, y, fill = correlation)) +
  geom_tile()
```

<img width="562" alt="Screen Shot 2019-05-24 at 11 48 18 AM" src="https://user-images.githubusercontent.com/4591688/58340437-dd160200-7e19-11e9-98f8-819a3b217d97.png">

**Comment by Bathroomboss** [comment]
Sorry, I still have question. I find it's strange that the correlation coefficients do not have negative values.
