### ISSUE TITLE
Export PC genes

### ISSUE THREAD

**Issue by HomairaH** [satijalab/seurat#1554]
Hello,
Is it possible to export a txt file of a list of all the genes in PC 1 in Seurat v3.0?

**Comment by yuhanH** [comment]
For example, you could extract loadings of genes in PC1 in `pbmc_small` using this common:
`pbmc_small@reductions$pca@feature.loadings[,1]`

**Comment by andrewwbutler** [comment]
We also provide the `Loadings` getter function which is useful to pull this information. 

```R
Loadings(pbmc_small[["pca"]])
```

**Comment by HomairaH** [comment]
Thanks - It looks like these are giving me all genes and their scores with respect to each PC. 
 Is it possible to get a list of all genes that are in PC1 only?

I would like to be able to remove PC1 genes from an analysis I am performing and require the list to input.

**Comment by yuhanH** [comment]
Each PC is a combination of all genes.  You could delete genes with high loading (absolute value) in the PC1 coordinates.
