### ISSUE TITLE
group.order in Seurat v3

### ISSUE THREAD

**Issue by jmzvillarreal** [satijalab/seurat#1555]
Hi Seurat users,
I have upgraded to v3 and I don't find an equivalent function of 'group.order' to define the order of the different clusters in a heatmap... Is there any ?
Many thanks !
Jaime.

**Comment by timoast** [comment]
To change the order of different clusters you can change the factor levels for the identities before creating the plot. For example:

```r
DoHeatmap(pbmc_small, features = VariableFeatures(pbmc_small), group.by = 'groups')
# change groups
pbmc_small$groups <- factor(pbmc_small$groups, levels = c('g2', 'g1'))
DoHeatmap(pbmc_small, features = VariableFeatures(pbmc_small), group.by = 'groups')
```
