### ISSUE TITLE
BuildClusterTree doesn't work with SCTransform

### ISSUE THREAD

**Issue by chansigit** [satijalab/seurat#1559]
I run SCTransform and do clustering, then run:

Idents(obj)<-"RNA_snn_res.0.5"
obj.clustertree<-BuildClusterTree(object=obj)

I got:

Finished averaging RNA for cluster 0
Finished averaging RNA for cluster 1
Finished averaging RNA for cluster 2
Finished averaging RNA for cluster 3
Finished averaging RNA for cluster 4
Finished averaging RNA for cluster 5
Finished averaging RNA for cluster 6
Finished averaging RNA for cluster 7
Finished averaging RNA for cluster 8
Finished averaging SCT for cluster 0
Finished averaging SCT for cluster 1
Finished averaging SCT for cluster 2
Finished averaging SCT for cluster 3
Finished averaging SCT for cluster 4
Finished averaging SCT for cluster 5
Finished averaging SCT for cluster 6
Finished averaging SCT for cluster 7
Finished averaging SCT for cluster 8

Error in hclust(d = data.dist): NA/NaN/Inf in foreign function call (arg 11)
Traceback:

1. BuildClusterTree(object = bin.cluster)
2. as.phylo(x = hclust(d = data.dist))
3. hclust(d = data.dist)

It seems that AverageExpression(object = obj, features = VariableFeatures(obj))  returns matrices with Inf values.

**Comment by andrewwbutler** [comment]
Hi,

We've added a parameter to `BuildClusterTree` on the develop that allows you to set the `slot` parameter. If you're using SCTransform, you should set this to `scale.data`. This should resolve the issue but if not, please post back here with some data that reproduces the issue. 

To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by chlee-tabin** [comment]
Hi, I have a similar error, and per your recommendation tried the development version with slot="scale.data" parameter. A different error happens:

```
BuildClusterTree( object = test, slot = "scale.data" )
Error in data.use[features.assay, temp.cells, drop = FALSE] : 
  no 'dimnames' attribute for array
```

Would you mind suggesting where to go?

**Comment by janinemelsen** [comment]
Hi,

To circumvent his problem I calculated the tree based on the principal components (which are based on the SCtransformed data), that worked for me:

object <- BuildClusterTree((object, dims=1:75)

**Comment by andrewwbutler** [comment]
@chlee-tabin Can you provide an example dataset that reproduces the issue?

**Comment by chlee-tabin** [comment]
Sorry for the delay. The minimal reproducible example is as follows:

```
test <- CreateSeuratObject( counts = GetAssayData( pbmc_small, assay = "RNA", slot = "counts" ), meta.data = pbmc_small@meta.data )
test <- SCTransform( test )
Idents( test ) <- Idents( pbmc_small )
BuildClusterTree( test, slot = "scale.data" )
```

generates an error.
