### ISSUE TITLE
Support title on multi-featured FeaturePlot / CombinedPlot

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#1560]
Hello,

It would be useful if seurat3 had the ability to add a title to the output of FeaturePlot, when this produces a grid of plots.  For example, one might plot a set of 4 genes (each sub-plot labeled by gene), but would want to label the whole figure 'Lineage Markers'.  Because you return the plot_grid object we can modify it (one way to this this below).  It's not a huge problem, but would be convenient if this type of thing were directly supported.  Perhaps a 'plotGridTitle' argument?  This is one way to add a title to that grid;

addTitleToMultiPlot <- function(plotGrid, title, relHeights = c(0.1, 1)) {
  plot_grid(ggdraw() + draw_label(title), plotGrid, ncol = 1, rel_heights = relHeights)
}

Also, I dont think docs are not technically correct about the return from FeaturePlot.  they say 'returns ggplot object', but I think that only applies when one feature is plotted, right?  Otherwise it's the cowplot/grid?

**Comment by timoast** [comment]
Hi, there is an open PR for this (https://github.com/satijalab/seurat/pull/1568). I have fixed the docs for `FeaturePlot` to properly describe the objects returned under different arguments, and the fix will be available on the `develop` branch soon.
