### ISSUE TITLE
Can we use the FindIntegrationAnchors() and IntegrateData() funtion directly on 3datasets?

### ISSUE THREAD

**Issue by ikohideonbush** [satijalab/seurat#1563]
Hi Seurat team:
I am focusing on the 2nd tutorial on your website(stimulated vs. control PBMC ).
It seems that if the object list contains more than 2 datasets, this function will calculate between every pair of datasets. I am wondering is it OK ? Or should we perform other treatments? I noticed that it will simply run cca if I put more than 2 datasets in the list, but RunCCA just differs from RunmultiCCA?

**Comment by yuhanH** [comment]
Sure. Just put the object list with three datasets. It will order your dataset according to the similarities of pair wise anchors. 
You could see the this integration tutorial: https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html
