### ISSUE TITLE
Finding optimal cluster resolution in Seurat 3?

### ISSUE THREAD

**Issue by Biogitte** [satijalab/seurat#1565]
Hi,

I am still adjusting to the new release of Seurat (i.e., ver. 3), but so far, I like many of the new additions/corrections in relation to Seurat 2.

I am, however, struggling to figure out the best resolution for my data set. At the moment, I use a resolution of 0.5  for around 2,000 cells (which I think to make a bit too many clusters). Are there functions in Seurat 3 where it is possible to compare the different cluster resolutions? Or a pipeline like this one (Seurat 2; does not function in Seurat 3):[https://ucdavis-bioinformatics-training.github.io/2017_2018-single-cell-RNA-sequencing-Workshop-UCD_UCB_UCSF/day3/scRNA_Workshop-PART5.html](url)? 

Thanks,

Best wishes, Birgitte

**Comment by Dragonmasterx87** [comment]
Hi Brigitte, I am not a Seurat developer, but your question has been discussed previously #96 In essence, there is no correct clustering parameter, either you will over or under cluster your data. To compensate for what makes biological sense in the context of your experiment, you can merge certain clusters together. I usually don't do this and just tweak the resolution till each cluster has at least 20 unique differentially expressed genes. I think as long as you define a cluster like a differentially expressed gene, it should be fine. Those are my thoughts though. 

I have attached here some old R code from what I believe were Seurat v1.4 tutorials, it has a few lines and some description on how to perform cluster re-assignment......something to look at while you wait for a Seurat dev's answer. 🐉 

[pbmc33k.zip](https://github.com/satijalab/seurat/files/3197897/pbmc33k.zip)

**Comment by mojaveazure** [comment]
Hi Birgitte,

While Seurat doesn't have tools for comparing cluster resolutions, there is a tool called [clustree](https://cran.r-project.org/web/packages/clustree/index.html) designed for this task and works on `Seurat` v3 objects natively. It's available on CRAN and can be installed with a simple `install.packages('clustree')`

You can read their [vignette](https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html) ([`Seurat` object section](https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html#seurat-objects)) for more details.

**Comment by tilofreiwald** [comment]
Hi Birgitte, there is another new tool called IKAP that helps to identify meaningful cutoffs for clustering resolutions:
[IKAP github](https://github.com/NHLBI-BCB/IKAP) and [IKAP preprint](https://www.biorxiv.org/content/10.1101/596817v1)

**Comment by msadman-sakib** [comment]
> Hi Birgitte,
> 
> While Seurat doesn't have tools for comparing cluster resolutions, there is a tool called [clustree](https://cran.r-project.org/web/packages/clustree/index.html) designed for this task and works on `Seurat` v3 objects natively. It's available on CRAN and can be installed with a simple `install.packages('clustree')`
> 
> You can read their [vignette](https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html) ([`Seurat` object section](https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html#seurat-objects)) for more details.

Thank you very much for this!!!
