### ISSUE TITLE
DimPlot error (Error: Cannot add more or fewer cell meta.data information without values being named with cell names)

### ISSUE THREAD

**Issue by wwjd918** [satijalab/seurat#1566]
Hi,

I converted SingleCellExperiment object into Seurat object like this:

`Seu_obj <- as.Seurat(x =sce_obj, counts = "counts", data = "logcounts")`

Next, I used DimPlot like this:
`DimPlot(object = Seu_obj, reduction = "UMAP", pt.size = 0.5, group.by="cluster")`

Then I had the error saying:
````
Error: Cannot add more or fewer cell meta.data information without values being named with cell names
Traceback:

1. DimPlot(object = Seu_obj, reduction = "UMAP", pt.size = 0.5, 
 .     group.by = "cluster")
2. `[[<-`(`*tmp*`, "ident", value = new("factor", .Data = integer(0), 
 .     levels = character(0), .S3Class = "factor"))
3. `[[<-`(`*tmp*`, "ident", value = new("factor", .Data = integer(0), 
 .     levels = character(0), .S3Class = "factor"))
4. stop("Cannot add more or fewer cell meta.data information without values being named with cell names", 
 .     call. = FALSE)
````

FYI, I had this error after installing recent version of Seurat (3.0.1) yesterday: before this installation, I didn't have this error. Could you help me to fix this error? I also attach small test datasets for sce_obj and Seu_obj.

Many thanks in advance.

[sce_obj.RData.zip](https://github.com/satijalab/seurat/files/3198559/sce_obj.RData.zip)
[Seu_obj.RData.zip](https://github.com/satijalab/seurat/files/3198565/Seu_obj.RData.zip)

**Comment by wwjd918** [comment]
Hi,

This issue has been sorted out after installing Seurat version 3.0.0. I wonder why the higher version generates this issue.

**Comment by lengfei5** [comment]
I got the same error. It still worked before and seems that some updated dependencies bring this error.

**Comment by andrewwbutler** [comment]
Hi,

This is because the `active.idents` slot wasn't being filled by default when performing this conversion. If you run
```R
Idents(Seu_obj) <- "cluster"
```
then the downstream plotting functions should work again. We will update this function to set it to the project.name by default to avoid these errors.

**Comment by Moloch0** [comment]
Hi, I met this problem when I was trying to add a vector to the metadata. The length of the vector is longer than the column name of the metadata. Finally I solved the problem.

**Comment by idoyairi** [comment]
> ```r
> Idents(Seu_obj) <- "cluster"
> ```

how did you solve the problem?

**Comment by cathalgking** [comment]
I get this error when trying to integrate multiple Seurat objects with the following line:
`all[["Spatial"]] <- split(all[["Spatial"]], f = all$sample)`
Is this issue related?
@mojaveazure

**Comment by JosieCen** [comment]
> I get this error when trying to integrate multiple Seurat objects with the following line: `all[["Spatial"]] <- split(all[["Spatial"]], f = all$sample)` Is this issue related? @mojaveazure

I got the same error in the same circumstance. Have you corrected the error yet?

**Comment by BiotechPedro** [comment]
I also got the same error

**Comment by bhavyaac** [comment]
I also got this error with the `split` function. I had accidentally been running with a Seurat version < 5. I used Seurat v5.0.3 and no longer had this error.
