### ISSUE TITLE
no fast_tsne_path specified and fast_tsne binary is not in the search path Seurat V3.0.1

### ISSUE THREAD

**Issue by weihuaguo** [satijalab/seurat#1567]
I cannot run the FIt-SNE on the latest version seurat. I install the package by "devtools::install_version(package = 'Seurat', version = package_version('3.0.1'))", R version is 3.5.1. My tSNE command is "srsc <- RunTSNE(object = srsc, dims = 1:num_dim, tsne.method = "FIt-SNE", nthreads = 12, max_item = 2000)". Can any one help? Thanks!

**Comment by mojaveazure** [comment]
Hi Weihua,

Do you have FIt-SNE installed already? This is an [external program written by the Kluger Lab](https://github.com/KlugerLab/FIt-SNE) that we call from within Seurat.
