### ISSUE TITLE
ScoreJackStraw & ElbowPlot dims can not be >20

### ISSUE THREAD

**Issue by JPingLin** [satijalab/seurat#1569]
Hi 
I am going through tutorial using standard pbmc dataset on Seurat v3 dev package. DimHeatmap allow me to see PC after 20 but I find I can not run/plot jackstraw elbowplot for dims over 20. I tried on other dataset is the same, 20 seems the limit for my case. I checked the #1232 and installed recent released dev package but not sure if that is the problem.  

pbmc <- RunPCA(object = pbmc, features = VariableFeatures(object = pbmc))
pbmc <- JackStraw(object = pbmc, num.replicate = 100)
pbmc <- ScoreJackStraw(object = pbmc, dims = 1:30)
Error in pAll[, dims, drop = FALSE] : subscript out of bounds

JackStrawPlot(object = pbmc, dims = 1:30)
Error in JackStrawPlot(object = pbmc, dims = 1:30) : Max dimension is 20

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

This is because the default number of dimensions to compute the jackstraw for is 20. Please see the `dims` parameter of `JackStraw`.
