### ISSUE TITLE
CCA segfaults

### ISSUE THREAD

**Issue by tallulandrews** [satijalab/seurat#157]
Running:
obj <- CreateSeuratObject(raw.data=data)
obj <- NormalizeData(object=obj)
obj <- ScaleData(object=obj)
obj@meta.data$dataset = groups
out <- RunCCA(object=obj,
                                group1=1,
                                group2=2,
                                group.by="dataset",
                                genes.use=features)

Causes:
 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("_Seurat_FastMatMult", PACKAGE = "Seurat", m1, m2)
 2: FastMatMult(m1 = data.use, m2 = cell.embeddings)
 3: ProjectDim(object = object, reduction.type = "cca", do.print = FALSE)
 4: RunCCA(object = combined, group1 = 1, group2 = 2, group.by = "dataset",     genes.use = features)

**Comment by satijalab** [comment]
Hi Tallulah,

Can you provide any more details about the dataset/environment you're running here, and how you installed? Are you able to run the integration examples we have on the website?

best,
Rahul

**Comment by tallulandrews** [comment]
Hi Rahul,
I've run the example on your website successfully, and replicating that example with the datasets I'm trying to use also worked - i.e. creating a separate seurat object for each dataset then using 

RunCCA(object=dataset1, object2=dataset2, genes.use=features)

runs without problems. It is only when I combine them into a single Seurat object and try to use the 

out <- RunCCA(object=combined, group1=1, group2=2, group.by="dataset", genes.use=features) 

formulation that I get the seg fault

I'm running R(3.3.0), on Ubuntu with Seurat installed from CRAN.

**Comment by andrewwbutler** [comment]
Thanks for bringing this up. Try reinstalling from the develop branch and see if that resolves the problem.
