### ISSUE TITLE
Error when running FindMarkers with DESeq2

### ISSUE THREAD

**Issue by rjb67** [satijalab/seurat#1570]
I am trying to test out differential expression of our data using DESeq2 as the test in FindMarkers(). However, when I run it I end up getting this error:

```
Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : 
  every gene contains at least one zero, cannot compute log geometric means
```

Do you have any recommendations for how to approach this or what the problem could be? Our counts were obtained using 10X.

**Comment by yuhanH** [comment]
We will fix this bug soon.
If you want to let it work now, you could add one count to your counts table, and then run DESeq2 in `FindMarkers` . Also, make sure the slot is set to counts.
`object[["RNA"]]@counts<-as.matrix(object[["RNA"]]@counts)+1`
`FindMarkers(object, ..., test.use = "DESeq2", slot = "counts")`

**Comment by brianpenghe** [comment]
same error!!!!!

**Comment by AmelZulji** [comment]
Hello Satija team,

Is there any progress made in removing above mentioned bug?

Best regards,
Amel

**Comment by senaj** [comment]
Hello Satija team,

I too am having the same issue.

Best,

senaj

**Comment by jr-leary7** [comment]
Has any progress been made on this bug? And if not, are there any workarounds for running DESeq2 manually and re-importing the results back into the Seurat object?

**Comment by satijalab** [comment]
Closing as we are in the process of removing support from DESeq (see #2938)

**Comment by BenjaminDEMAILLE** [comment]
Stil encounter this bug in Seurat 4.3.0

**Comment by jr-leary7** [comment]
@BenjaminDEMAILLE in general a better option for running `DESeq2` is to perform pseudobulk aggregation & then run the testing manually using the typical workflow. Otherwise, if you're looking to perform e.g., multi-sample DE testing I'd look at using (generalized) linear mixed models with your feature of interest as a covariate instead. I can provide code for either option if you're interested.

**Comment by apal6** [comment]
Hi Jack, 

I have been trying to run pseudobulk but I am not sure if I understand it fully. I have three treatment groups and each having 4 samples. Would be great if you share your code as I am not able to run findmarkers using DESeq2. 

Thanks

**Comment by yulchen810** [comment]
> We will fix this bug soon. If you want to let it work now, you could add one count to your counts table, and then run DESeq2 in `FindMarkers` . Also, make sure the slot is set to counts. `object[["RNA"]]@counts<-as.matrix(object[["RNA"]]@counts)+1` `FindMarkers(object, ..., test.use = "DESeq2", slot = "counts")`

Hi, I tried this way, but it's not resolved. Is there any other solutions? Thank you very much!
`Obj_Integrate[["RNA"]]@counts<-as.matrix(Obj_Integrate[["RNA"]]@counts)+1
markers_DESeq2 <- FindMarkers(Obj_Integrate, ident.1 = "MBLI", ident.2 = "MB93", test.use = "DESeq2", slot = "counts") %>% filter(p_val_adj < 0.05) 
`
which returns an error:
Error in h(simpleError(msg, call)) :
在为'rowSums'函数选择方法时评估'x'参数出了错: invalid or not-yet-implemented 'Matrix' subsetting
