### ISSUE TITLE
Is there a way to label or color code a specific cluster when using FeaturePlot

### ISSUE THREAD

**Issue by ahdee** [satijalab/seurat#1571]
So it would be really useful if during FeaturePlot we can label a specific cluster.  The reason why is because often when plotting the feature say a gene of interest ( eg from DGE ) we want to see how well this particular gene differentiate with other clusters.  Its difficult to do when there are no labeling of the clusters.  thanks!

**Comment by mojaveazure** [comment]
Please see the `label` parameter to [`FeaturePlot`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/FeaturePlot)

**Comment by ahdee** [comment]
thanks @mojaveazure yes I tried that but it does not label the clusters properly.  When I set label=T at best it would clump the numbers together. Also it does not label the clusters correctly.   Can you look into this? thanks. I'm using seurat 3

**Comment by andrewwbutler** [comment]
This should be fixed now in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by Maj18** [comment]
I added reduction = "umap", then the label works, otherwise, it does not
