### ISSUE TITLE
installing UMAP in R using reticulate

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#1572]
Hello everyone,

After i try to instal UMAP using: 
`reticulate::py_install(packages ='umap-learn')` 

following error is thrown:
Error: Prerequisites for installing Python packages not available.
Execute the following at a terminal to install the prerequisites:
$ sudo /usr/bin/easy_install pip
$ sudo /usr/local/bin/pip install --upgrade virtualenv

after executing `$ sudo /usr/bin/easy_install pip` in terminal, following warning is shown:
<myID> is not in the sudoers file.  This incident will be reported.

is there any possibility to overcome this issue without going deep into root accounts? 

I havent seen that anyone had the same problem with sudo account. Can anyone help? 

I am using:
macOS Mojave, version 10.14.5. (18F132)
RStudio, Version 1.1.463 – © 2009-2018 RStudio, Inc.

**Comment by mschilli87** [comment]
@AmelZulji: try

```sh
# Check if easy_install is available, otherwise install as per 
# https://www.slothparadise.com/install-pip-user/
which easy_install  || \
wget --no-check-certificate \
     https://bootstrap.pypa.io/ez_setup.py \
     -O - \
| python - --user

# Install pip for the current user only (no root required).
easy_install --user pip

# Update pip (just in case) for the current user only (no root required).
pip --user --upgrade pip

# Get latest virtualenv (as required by reticulate) for the current user only (no root required).
pip --user --upgrade virtualenv
```

Note that this is untested and your question is not related to Seurat at all.
So if this doesn't help, please consider seeking help on StackOverflow or pip/easy_install/reticulate support channels.
