### ISSUE TITLE
Cannot install loom branch of Seurat, (bad url?)

### ISSUE THREAD

**Issue by dcoukos** [satijalab/seurat#1575]
Hi,

While trying to install the tools to use loom with Seurat, as instructed at the beginning of this [`tutorial`](https://satijalab.org/seurat/mca_loom.html) from the Satija lab, I get an error when running:

devtools::install_github(repo = 'satijalab/seurat', ref = 'loom')

Error: (converted from warning) unable to access index for repository https://mojaveazure.github.io/loomR/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/macosx/el-capitan/contrib/3.6/PACKAGES'

I believe this is because this url has changed to https://mojaveazure.github.io/loomR/src/contrib/PACKAGES

I am not familiar with R, is there anything I can do to fix this?
Thanks!

**Comment by mojaveazure** [comment]
This is an issue with `devtools` not knowing to look for source packages in addition to binaries. Try installing loomR first, then install the `loom` branch of Seurat.

**Comment by dcoukos** [comment]
Hi mojaveazure, 

Thanks for the reply! I reinstalled devtools via install.packages, but I get the same error.

**Comment by mojaveazure** [comment]
Please install loomR first, then install the `loom` branch of Seurat. This issue where `devtools` will only install binaries, not source, hasn't been fixed in any recent version of `devtools` (as far as I know).

**Comment by dcoukos** [comment]
Hi mojaveazure, 

I have checked and I already have loomR installed. I am using OSX mojave, and R 3.6, could this be an issue? 
Thanks!

**Comment by mojaveazure** [comment]
Then the issue is `devtools` isn't recognizing that you already have loomR, not necessarily with Seurat, loomR, R, or macOS. If you've installed Seurat v2 in the past under R 3.6, I would rerun `devtools::install_github`, but with [`dependencies = FALSE`](https://www.rdocumentation.org/packages/remotes/versions/2.0.4/topics/install_github); otherwise, [install Seurat v2](https://satijalab.org/seurat/install.html#previous), then install the `loom` branch with `devtools` as above.

**Comment by margiezilla** [comment]
I was able to get around this problem with devtools by using a R package called githubinstall
https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html
after installing, you can run
> library(githubinstall)
> gh_install_packages("satijalab/seurat", ref="loom") to install the loom branch
