### ISSUE TITLE
Error from RunUMAP

### ISSUE THREAD

**Issue by compbio** [satijalab/seurat#1577]
Hi,

I got an error when I ran the following command from Vignette: Stimulated vs. Control PBMCs :
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:20)

Error message is as follows
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: unsupported hash type md5

Do you have any idea? It seems like that hashlib package works properly. 

Thanks!

**Comment by andrewwbutler** [comment]
If you're able to verify that hashlib works properly, can you also check whether you're able to run umap directly via python?
