### ISSUE TITLE
Extracting cell barcodes with the dash & number

### ISSUE THREAD

**Issue by L30P30** [satijalab/seurat#1578]
After processing my data in Seurat I have removed a lot of low viability cells. I'd like to go back and generate a new filtered Loupe file for other members in the lab you aren't comfortable at the command line. In order to do this I need to run cellranger reanalyze and provide a csv with all the cell barcodes I want to keep. The barcodes in my Seurat object appear like "AAACCCAAGGTCATAA" and don't match those in the cellranger aggregate barcode matrix which have an addition dash and number like this "AAACCCAAGGTCATAA-1". 

Do you know how I can retrieve this additional information to filter my Loupe file?

Many thanks

**Comment by andrewwbutler** [comment]
Hi, 

Seurat removes the  "-1" if all cell names contain it as it doesn't really encode any additional information. You can add it back in if you want with `RenameCells`. E.g.

```R
object <- RenameCells(object = object, new.names = paste0(Cells(x = object), "-1"))
```

**Comment by L30P30** [comment]
Hi Andrew,

Is it not possible that there was "AAACCCAAGGTCATAA-2" in my Seurat object but no "AAACCCAAGGTCATAA-1", therefore removing "-2"?

Thanks for your help!

**Comment by andrewwbutler** [comment]
No, it only is looking for the "-1". See relevant code from `Read10X` here:
https://github.com/satijalab/seurat/blob/f195c4a75081713d057e648430a4d288ca752835/R/preprocessing.R#L727-L734

**Comment by L30P30** [comment]
Ah fantastic, thank you!
