### ISSUE TITLE
Error in RunCCA

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#158]
Hi,

I am getting an error in RunCCA. 

MCF7 <- RunCCA(object = sampleA4, object2 = sampleA5, genes.use = hvg.union)
Error in RunCCA(object = sampleA4, object2 = sampleA5, genes.use = hvg.union) : 
  0 valid genes in genes.use

If I run MergeSeurat and then ScaleData and RunPCA then there are no errors. But certain stages in the CalcVarExpRatio  is not working without CCA.

Here are the steps that I ran

sampleA5.data <- Read10X(data.dir = "/Volumes/Promise_Pegasus/Single_cell_seq/July_2017/Hezhe/sample_Dan_A5/outs/filtered_gene_bc_matrices/GRCh38/")
sampleA5 <- CreateSeuratObject(raw.data = sampleA5.data, min.cells = 3, min.genes = 100, 
                               project = "sample_A5")

sampleA5 <- FilterCells(object = sampleA5, subset.names = c("nGene"))
sampleA5 <- NormalizeData(object = sampleA5, normalization.method = "LogNormalize", 
                          scale.factor = 10000)
sampleA5 <- FindVariableGenes(object = sampleA5, mean.function = ExpMean, dispersion.function = LogVMR, 
                              x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)

sampleA4.data <- Read10X(data.dir = "/Volumes/Promise_Pegasus/Single_cell_seq/July_2017/Hezhe/sample_Dan_A4/outs/filtered_gene_bc_matrices/GRCh38/")
sampleA4 <- CreateSeuratObject(raw.data = sampleA4.data, min.cells = 3, min.genes = 100, 
                               project = "sample_A4")

sampleA4 <- FilterCells(object = sampleA4, subset.names = c("nGene"))

sampleA4 <- NormalizeData(object = sampleA4, normalization.method = "LogNormalize", 
                          scale.factor = 10000)

sampleA4 <- FindVariableGenes(object = sampleA4, mean.function = ExpMean, dispersion.function = LogVMR, 
                              x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)

hvg.sampleA4 <- rownames(x = head(x = sampleA4@hvg.info, n = 2000))
hvg.sampleA5 <- rownames(x = head(x = sampleA5@hvg.info, n = 2000))
hvg.union <- union(x = hvg.sampleA4, y = hvg.sampleA5)

sampleA5@meta.data[, "protocol"] <- "sampleA5"
sampleA4@meta.data[, "protocol"] <- "sampleA4"

**Comment by satijalab** [comment]
This is most likely because the hvg.union contains no genes. This can happen if there is no overlap between the variable genes between two options, or alternately, if the gene names are upper case in one object, and lower case in another.

**Comment by ghoshal** [comment]
I am getting a similar error again. This time the hvg.union has more than 1000 genes and the gene naming is consistent between the two datasets.

# Load the C04 dataset
C04.data <- Read10X(data.dir = "/Volumes/Promise_Pegasus/Single_cell_seq/Nov_2017/Arshad/sample_C04/outs/filtered_gene_bc_matrices/mm10/")
C04 <- CreateSeuratObject(raw.data = C04.data, min.cells = 3, min.genes = 100, 
                               project = "C04")

mito.genes <- grep(pattern = "^mt-", x = rownames(x = C04@data), value = TRUE)
percent.mito <- Matrix::colSums(C04@raw.data[mito.genes, ])/Matrix::colSums(C04@raw.data)

C04 <- AddMetaData(object = C04, metadata = percent.mito, col.name = "percent.mito")
C04 <- FilterCells(object = C04, subset.names = c("nGene", "percent.mito"))
C04 <- NormalizeData(object = C04, normalization.method = "LogNormalize", 
                          scale.factor = 10000)
C04 <- FindVariableGenes(object = C04, mean.function = ExpMean, dispersion.function = LogVMR, 
                              x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
length(x = C04@var.genes)

# Load the C06 dataset
C06.data <- Read10X(data.dir = "/Volumes/Promise_Pegasus/Single_cell_seq/Nov_2017/Arshad/sample_C06/outs/filtered_gene_bc_matrices/mm10/")
C06 <- CreateSeuratObject(raw.data = C06.data, min.cells = 3, min.genes = 100, 
                          project = "C06")

mito.genes <- grep(pattern = "^mt-", x = rownames(x = C06@data), value = TRUE)
percent.mito <- Matrix::colSums(C06@raw.data[mito.genes, ])/Matrix::colSums(C06@raw.data)

C06 <- AddMetaData(object = C06, metadata = percent.mito, col.name = "percent.mito")
C06 <- FilterCells(object = C06, subset.names = c("nGene", "percent.mito"))
C06 <- NormalizeData(object = C06, normalization.method = "LogNormalize", 
                     scale.factor = 10000)
C06 <- FindVariableGenes(object = C06, mean.function = ExpMean, dispersion.function = LogVMR, 
                         x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
length(x = C06@var.genes)


# we will take the union of the top 2k variable genes in each dataset for
# alignment note that we use 1k genes in the manuscript examples, you can
# try this here with negligible changes to the overall results
hvg.C06 <- rownames(x = head(x = C06@hvg.info, n = 100))
hvg.C04 <- rownames(x = head(x = C04@hvg.info, n = 100))
hvg.union <- union(x = hvg.C06, y = hvg.C04)

# lastly, we set the 'protocol' in each dataset for easy identification
# later it will be transferred to the merged object in RunCCA
C04@meta.data[, "protocol"] <- "C04"
C06@meta.data[, "protocol"] <- "C06"

whole_epithelium <- MergeSeurat(object1 = C04, object2 = C06, min.cells = 3, min.genes = 200,
                    add.cell.id1 = "C04", add.cell.id2 = "C06", project = "whole_epithelium")

whole_epithelium <- ScaleData(whole_epithelium, genes.use = hvg.union, do.center = F, do.scale = T)

whole_epithelium <- RunCCA(object = C04, object2 = C06, add.cell.id1 = "C04", add.cell.id2 = "C06")
Error in RunCCA(object = C04, object2 = C06, add.cell.id1 = "C04", add.cell.id2 = "C06") : 
  0 valid genes in genes.use
Called from: RunCCA(object = C04, object2 = C06, add.cell.id1 = "C04", add.cell.id2 = "C06")

Thanks,

Bibaswan
