### ISSUE TITLE
Between Sample Normalization for Sequencing Depth

### ISSUE THREAD

**Issue by stephenchea** [satijalab/seurat#1580]
I have 12 10X Genomics Chromium single-cell RNA sequencing libraries of varying depths. I want to perform cell to cell comparisons as well as sample to sample comparisons, so this requires that these libraries be normalized for sequencing depth per library and sequencing depth per cell. I typically normalize for sequencing depth using CellRanger's aggr command, which downsamples (which is less than ideal), but I've noticed that once we filter out cells at the beginning of Seurat's pipeline, the total sequencing depth per library is no longer normalized. Does Seurat's following normalization procedures, whether by NormalizeData or SCTransform take this into account?

**Comment by yuhanH** [comment]
Right. You could use `SCTransform` to control sequencing depth and libraries. 
`SCTransform (object, vars.to.regress = library)`
 The normalized data is stored in the `scale.data` slot.
