### ISSUE TITLE
Error in UseMethod when calling FindIntegrationAnchors

### ISSUE THREAD

**Issue by r-melo** [satijalab/seurat#1581]
When I try to run
 
`pbmc_anchors <- FindIntegrationAnchors(object.list =  pbmc_list, dims = 1:40,k.filter = 40)`

where pbmc_list is a list of seurat objects, it trows the following error:

`Computing 2000 integration features
Error in UseMethod(generic = "DefaultAssay<-", object = object) : 
  no applicable method for 'DefaultAssay<-' applied to an object of class "NULL"
Calls: FindIntegrationAnchors -> SelectIntegrationFeatures -> DefaultAssay<-
Execution halted`

Thank you for your help

**Comment by andrewwbutler** [comment]
Can you verify that every element in `pbmc_list` is actually a Seurat object? If that's not the issue, can you provide an example that reproduces the issue?
