### ISSUE TITLE
Why all the "percent.mt" values  are zero?

### ISSUE THREAD

**Issue by hua1991** [satijalab/seurat#1582]
Hi everyone,

I'm confronting a problem with the command "PercentageFeatureSet(object, pattern = "^MT-")". I followed **Seurat - Guided Clustering Tutorial**  to calculate the value of "percent.mt" with my data. But, the result showed the percent.mt values all were zero. When I tried with the tutorial pbmc data, it seemed normal. And, I also checked the mt genes in the features.tsv file, it actually had mitochondrial genes like mt-Nd1, mt-Co3, and mt-Cytb. I think it may be something wrong with my data, but I can't figure it out. Does anyone know how to solve this problem?
![image](https://user-images.githubusercontent.com/51027086/58373356-46d30080-7f2d-11e9-9584-c87e97b92ce2.png)
![image](https://user-images.githubusercontent.com/51027086/58373433-a41b8180-7f2e-11e9-9ad9-798467dc9327.png)

Best,
hua

**Comment by chlee-tabin** [comment]
I think you were using the capitalized letters. Try to change that to small letters ```PercentageFeatureSet(object, pattern = "^mt-")```.

**Comment by yuhanH** [comment]
I agree.  The pattern should be `^mt-`

**Comment by stefanonard85** [comment]
Hello all, 

I have the same problem but is not resolved just changing from capital letters to small one. from
obj <- PercentageFeatureSet(obj, 
                               pattern = "^mt-", 
                               col.name = "percent.mt")

I get this error
In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :
  All cells have the same value of percent.mt.

**Comment by ayanarajagopal** [comment]
Hi Stefan, did you find a solution for this? I am also facing the same issue and I work on a non-model organism.

**Comment by yuhanH** [comment]
Can you check what are prefix of mitochondria genes in your RNA matrix?

**Comment by ayanarajagopal** [comment]
Yes, they are "MT-" for me, I checked and I do find them in the initial gene file, but lose them afterwards.

**Comment by yuhanH** [comment]
sorry for the delayed reply... 
Are those MT genes in your object?  
```
grep ("^MT-", rownames(object[["RNA"]]),value = T)
```
Does this command show MT genes?

**Comment by ayanarajagopal** [comment]
It gives me this: 
grep ("^MT-", rownames(youngf[["RNA"]]),value = T)
 [1] "MT-ND1"  "MT-ND2"  "MT-COX1" "MT-COX2" "MT-ATP8" "MT-COX3" "MT-ND3"  "MT-ND4L" "MT-ND5"  "MT-CYTB" "MT-ND6"

**Comment by yuhanH** [comment]
One more question to clarify the issue. 
In your case, you have mitochondria genes in your count matrix, but are all your percent.mt zero? 
Are they all zero in the count matrix?
Thanks.

**Comment by ayanarajagopal** [comment]
Yes indeed, I see only zeros in the count matrix and in addition, the warning message in VlnPlot I get is the following:
**Warning message:
In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :
  All cells have the same value of percent.mt.**

**Comment by yuhanH** [comment]
Thanks. I think it is not an issue related to seurat, because your count matrix doesn't have the mitochondria genes counts. 
You would better check your alignment results.

**Comment by Gbighe** [comment]
This is a late reply, but it worked very well in my case.
"MT-" is the beginning of the name of the human mitochondrial gene, e.g. "MT-ND1". If the FEATURES column of the dataset is not named in this way, e.g. in GSE190129 the authors used the form "MT.ND1", the code needs to be changed to 
`pattern` = "^MT." 
not
`pattern` = "^MT-"
I hope my answer is helpful.

**Comment by DirtyHarry80** [comment]
@Gbighe thank you for your answer! Your solution works.

**Comment by talhar123456** [comment]
> u for your answer! Your solution works.

thanks worked for me "^MT."

**Comment by mitra-frn** [comment]
Hi,
Mitochondria gene patterns could change when you change the reference-genome annotation file in aligning step.(e.g. 'mt.','mt-','MT.','MT-'). In my dataset, Mitochondria genes are started by "MT."
but to avoid mismatching, it's better to use 
pattern = "^MT\\."
not 
pattern = "^MT."
in this way, you roll out genes that are started by MT but aren't  Mitochondria genes.

**Comment by yojetsharma** [comment]
> Hi, Mitochondria gene patterns could change when you change the reference-genome annotation file in aligning step.(e.g. 'mt.','mt-','MT.','MT-'). In my dataset, Mitochondria genes are started by "MT." but to avoid mismatching, it's better to use pattern = "^MT\\." not pattern = "^MT." in this way, you roll out genes that are started by MT but aren't Mitochondria genes.

I am experiencing the same issue. None of the solutions seem to work for me. Which got me wondering if it is because all the genes are ensemble ids in my seurat obj. Could this be the reason?

**Comment by WalkingBandaid** [comment]
> I am experiencing the same issue. None of the solutions seem to work for me. Which got me wondering if it is because all the genes are ensemble ids in my seurat obj. Could this be the reason?

@yojetsharma I was experiencing the same issue, so I checked what gene names were being used by checking the row names

Genes <- rownames(object[["RNA"]])

I then exported it as a .csv so I could scroll through it and look manually. 

Looks like mine was "Mt", not "MT" or "mt".

Switching it to "^Mt-" fixed it.

**Comment by akalbasi25** [comment]
Hi, I am having the same issue. I followed all the suggestions and still no luck. 

grep ("^MT", rownames(sobj[["RNA"]]),value = T)
[1] "MT-ND6"  "MT-CO2"  "MT-CYB"  "MT-ND2"  "MT-ND5"  "MT-CO1"  "MT-ND3"  "MT-ND4"  "MT-ND1"  "MT-ATP6"
[11] "MT-CO3"  "MT-ND4L" "MT-ATP8"

sobj[["percent.mt"]] <- PercentageFeatureSet(sobj, pattern = "^MT-")

I still get the error: `Error in if (all(data[, feature] == data[, feature][1])) { : 
  missing value where TRUE/FALSE needed`
  
  Any further suggestions?

Thank you so much!

**Comment by apal6** [comment]
Hi, I am having the same issue. I followed all the suggestions and still no luck.

grep ("^MT", rownames(sobj[["RNA"]]),value = T)
[1] "MT-ND6" "MT-CO2" "MT-CYB" "MT-ND2" "MT-ND5" "MT-CO1" "MT-ND3" "MT-ND4" "MT-ND1" "MT-ATP6"
[11] "MT-CO3" "MT-ND4L" "MT-ATP8"

sobj[["percent.mt"]] <- PercentageFeatureSet(sobj, pattern = "^MT-")

I still get the error: Error in if (all(data[, feature] == data[, feature][1])) { :  missing value where TRUE/FALSE needed

Any further suggestions?

Thank you so much!
