### ISSUE TITLE
 Questions about --Guided Tutorial on your lab website

### ISSUE THREAD

**Issue by BigGiAnts** [satijalab/seurat#1587]
hi,
i am a beginner in bioinformatics, and i am trying to learn your seurat packages from the  Guided Tutorial. Guided Tutorial use  seurat version 2.XX，however, version 3.XX can be used on my server.
you have clearly listed some changes in version 3.XX on your labwebsite.
but i can't find the function like  CalcVarExpRatio and CalcLDProj.

 or did i miss something ?

thanks.

bellow is one error message:

![P~6~0HIVENG0T(O820KY~ 7](https://user-images.githubusercontent.com/34053372/58403449-481f3d00-8095-11e9-8198-0eba0d6a33f7.png)

**Comment by Dragonmasterx87** [comment]
Bro, they have guided tutorials for v3.0.0 [click here](https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html) If you go to the small orange tab at the lower right edge of your screen you can shift between different tutorials. Learn from 3.0.0, the 2.3.4 is now outdated.

Cheers!

**Comment by BigGiAnts** [comment]
got it !
thanks  bro.
