### ISSUE TITLE
Some questions about subset fuction from a SCTnormalized data

### ISSUE THREAD

**Issue by yhli1992** [satijalab/seurat#1588]
I met some problem when I use subset fuction to get data from a SCTnormalized data. After subset option, the data has RNA assay and SCT assay. 
`t = subset(all,cells = colnames(all)[grep("T-",colnames(all))])
t
An object of class Seurat 
30071 features across 47 samples within 2 assays 
Active assay: SCT (13982 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, tsne, umap`
But when I used 
`GetAssayData(t,assay = "RNA",slot = "counts")` ,
I found that it's different from the raw data matrix.  Is that a bug? And how can I solve this problem?
`packageVersion("Seurat")
[1] ‘3.0.0’`

**Comment by yuhanH** [comment]
What are the differences you mentioned?

**Comment by yhli1992** [comment]
Sorry, I found that I used cbind() to merge different tables before create Seurat object,and didn't sort these tables by rownames.
