### ISSUE TITLE
Output matrix for Monocle

### ISSUE THREAD

**Issue by rmtsoa** [satijalab/seurat#159]
Hi again:

I have already finished the clustering and called for top differentially expressing genes for each cluster. Now, I am trying to get this data set for psudotime analysis using Monocle. Has anyone tried it?

Thanks,
Rosemarie

**Comment by satijalab** [comment]
Please see our FAQ and interaction vignette for examples on how to extract the data matrix from a Seurat object. You can use this as input to Monocle. We'll be providing conversion functions to make this process easier in the near future.

**Comment by rmtsoa** [comment]
Found it. Thanks, it is very helpful.

Rosemarie
