### ISSUE TITLE
When using repel, set xnudge and ynudge to 0 for optimal results

### ISSUE THREAD

**Issue by DawnEve** [satijalab/seurat#1590]
when using my data,

> plot1 <- VariableFeaturePlot(pbmc4)

> plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
`When using repel, set xnudge and ynudge to 0 for optimal results`

> CombinePlots(plots = list(plot1, plot2))
`Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)`

**Comment by Dragonmasterx87** [comment]
Try this:

```
plot1 <- VariableFeaturePlot(object = pbmc4)
LabelPoints(plot = plot1, points = top10, repel = TRUE, xnudge = 0, ynudge = 0)
```

Also, did you do this before:

```
pbmc4 <- FindVariableFeatures(object = pbmc4, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(x = VariableFeatures(object = pbmc4), 10)
```

**Comment by DawnEve** [comment]
this will be fine to get 2 pictures:

VariableFeaturePlot(pbmc4)

LabelPoints(plot = plot1, points = top10, repel = TRUE)
`When using repel, set xnudge and ynudge to 0 for optimal results`

**Comment by DawnEve** [comment]
I can see 2 plot separately, but when combining,  an error accured. 

> plot1 <- VariableFeaturePlot(pbmc4)
> plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE,xnudge=0,ynudge=0)
> CombinePlots(plots = list(plot1, plot2))
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)

**Comment by ojikj2019** [comment]
Looks like the same as the issue#1476.

**Comment by Wangsj2020** [comment]
I changed the "repel=TRUE" to "repel=FALSE", the result picture is correct, but I don't know the reason.

**Comment by Wangsj2020** [comment]
I changed the "repel=TRUE" to "repel=FALSE", the result picture is correct, but I don't know the reason.

**Comment by Liberty1011** [comment]
> I changed the "repel=TRUE" to "repel=FALSE", the result picture is correct, but I don't know the reason.

thank you,  I made it using this way

**Comment by frankluo149** [comment]
> I changed the "repel=TRUE" to "repel=FALSE", the result picture is correct, but I don't know the reason.

I also made it by this way. But, I still wonder the reason. It makes me feel unsecurity to change other's code.

**Comment by 1524519659** [comment]
You just need to enlarge the Plots panel in the bottom right corner of RStudio
