### ISSUE TITLE
Visualizing more than one metadata slot at once

### ISSUE THREAD

**Issue by rlorenzc** [satijalab/seurat#1591]
Hi,

Is there anyway to quickly visualize a sample with DimPlot that is split by one metadatum and then followed by another? For example, I'd like to visualize my merged object that is first split by control vs. disease (2 plots), and then further splitting this by treatments A vs. B (each previous plot is now split again into 2 for a total of 4 plots). 

Otherwise, the only method that I can imagine to achieve this is to subset my data (i.e. by disease state) and then visualizing one metadata slot only. 

Thanks!

**Comment by yuhanH** [comment]
You can generate one new column containing both information in your metadata. 
For example, you store the control-disease in the disease column and  treatments A-B in the treatment column in your metadata. You can paste those two columns to obtain a new one, disease_treatment, and then you can split by this column.

`object$disease_treatment<-paste(object$disease, object$treatment, sep = "_")`
