### ISSUE TITLE
Changing RunUMAP parameters

### ISSUE THREAD

**Issue by soprescu** [satijalab/seurat#1592]
I am using the RunUMAP() function to visulize some scRNAseqdata. 
I want to change some of the parameters (such as n_neighbors, min_distance, etc) but every time I input the values I want, RunUMAP() just calls the UMAP function with a seemingly default set of values. 
How can I change those so I can run UMAP with other values?
Thank you! 
<img width="688" alt="Screen Shot 2019-05-28 at 2 07 26 PM" src="https://user-images.githubusercontent.com/37408669/58501257-f688b800-8151-11e9-9f0c-d517c2d60d87.png">

**Comment by andrewwbutler** [comment]
Hi,

Are you changing the corresponding parameters in the `RunUMAP` function call? For example, to change the `n_neighbors` parameter, you need to set `n.neighbors` (generally, we just replaced underscores with periods to be consistent with Seurat's coding style).

**Comment by soprescu** [comment]
ah yes, that worked! thank you so much!
