### ISSUE TITLE
running a comparison of samples for multimodal data

### ISSUE THREAD

**Issue by talban14** [satijalab/seurat#1593]
Hi i'm using citeseq data of 16 samples and tryint to do comparisons using Seurat but I'm having trouble figuring out proper way to import so that the comparisons can be done smoothly.  Are there any vignettes for this type of comparison using multimodal data? or any way for me to perform the comarison on the transcripts and then look at the protein levels of each cluster at the end?

**Comment by mojaveazure** [comment]
Please see our [vignette for multimodal analyses](https://satijalab.org/seurat/multimodal_vignette.html).
