### ISSUE TITLE
fFindVariableFeatures, can't copy to .eps file

### ISSUE THREAD

**Issue by hkanya** [satijalab/seurat#1594]
I am troubleshooting a R script:

#Normalizes the gene expression measurements for each cell by the total transcripts, multiplies this by a scale factor(10000 by default), and then log-transforms(takes natural log "e") the result
```R
seurat_object <- NormalizeData(object = seurat_object, normalization.method = "LogNormalize", scale.factor = 10000)
#find highly variable genes
seurat_object <- FindVariableFeatures(object = seurat_object, selection.method = "vst", mean.function = ExpMean, dispersion.function = LogVMR, mean.cutoff = c(0.0125, 3), dispersion.cutoff =c(0.5, Inf))
dev.copy2eps(file=paste(seurat_file_address,"meanvarplot.eps", sep=""), width = 8.5, height = 11)
dev.copy2pdf(file=paste(seurat_file_address,"meanvarplot.pdf", sep=""), width = 8.5, height = 11)
dev.off()
```

However this keeps resulting in an error saying: 'no device to print from'
I am wondering if it has something to do with the FindVariableFeatures function or is there something else I should troubleshoot.

**Comment by andrewwbutler** [comment]
Hi,

`FindVariableFeatures` is not a plotting function. Please see `VariableFeaturePlot`.
