### ISSUE TITLE
Visualize cell identity already stored in the original matrix, not in meta.data

### ISSUE THREAD

**Issue by cesco-lemon** [satijalab/seurat#1595]
Hi everyone,
I'm working on Seurat v2.4 on a big dataset (120k cells) stored in as a sparse matrix. I've started to generate some plots and looked at subclustering and I am pretty happy with what I see.
The sparse matrix stores information from each cell from various individuals. The columns in the matrix look this way:
Control_id1_BARCODE
Control_id2_BARCODE
Control_id3_BARCODE
Patient_id4_BARCODE
Patient_id5_BARCODE
Patient_id6_BARCODE
Where BARCODE is the barcode for each cell and where each "id" has thousands of barcodes.
Note, these are not separate matrices, all the information is stored in one big matrix in which 

As shown in the graph below I can see the patient vs control because Seurat automatically picks this info up but I would like to also see how each id is represented in the various clusters. I've added "names.field=2" in CreateSeuratObject so that Seurat can look at the second delimitation in the column headings but how do I generate a tSNE plot in which I can see each person's id?

![tSNE_patient vs control](https://user-images.githubusercontent.com/42619695/58519529-061ff500-8182-11e9-950e-31eaae2e070b.png)

On a similar note, I've also generated subclusters of my tSNE with the FindClusters (graph below). I know want to see how the Control and Patient populate each cluster. I figure I should use the DimPlot function but I'm not sure how to set the identities to Control and Patient. Would this work?
DimPlot(object, reduction = "tsne", group.by =c("Control", "Patient"))
Could I use this to also look at the different identities by changing it to c("id1", "id2",...)?

![tSNE_clusters_03_labels](https://user-images.githubusercontent.com/42619695/58519954-914dba80-8183-11e9-8225-8583517adf11.png)

Thanks a lot!

**Comment by andrewwbutler** [comment]
Hi,

1. To generate a tSNE plot colored by each person's id, you just need to pass the name of the meta.data column denoting that to the `group.by` parameter of `DimPlot`.
2. To examine two groupings (e.g cluster and patient vs control), you could view them side by side as you have above. Alternatively, you could create a new meta.data column with both piece of meta.data encoded. E.g.
```R
object@meta.data$cluster_patient <- paste0(object@meta.data$cluster, "_", object@meta.data$patient)
DimPlot(object, group.by = "cluster_patient")
```
