### ISSUE TITLE
(pre-)process multimodal BD Rhapsody data with multiple conditions

### ISSUE THREAD

**Issue by PDBio** [satijalab/seurat#1596]
Hi,

I am processing mRNA + AbSeq (like CITE-seq) data from BD Rhapsody (output of their pipeline on SevenBridges).

I have a single file as input containing data for two experimental conditions (treatment/control). 

Should I subset this data for each condition and run separate pre-processing steps (filtering, normalization, find variable features) and then re-integrate them? (As is demonstrated in the "stimulated vs. control PBMCs" tutorial)
Or can I directly perform this steps on the combined dataset?
Are there disadvantages with any approach?

Thank you,
Philipp

**Comment by andrewwbutler** [comment]
Hi,

If your goal is to identify common cell types across experimental conditions, I would generally recommend running the integration workflow (as in the tutorial).
