### ISSUE TITLE
Error with IntegrateData

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#1597]
I am facing an error with integrating 9 datasets. 
Previously I was able to integrate them with the following command lines:
```
sample.list <- list(s11.so, s12.so, s13.so, s14.so, s15.so, s16.so, s17.so, s18.so, s19.so)
integrate.anchors <- FindIntegrationAnchors(object.list = sample.list, dims = 1:30)
integrated.so <- IntegrateData(anchorset = integrate.anchors, dims = 1:30)
```

However, when I try them again this time with the same dataset, I got an error message as below.
`Error in slot(object = anchorset, name = "command") : 
  no slot of name "command" for this object of class "AnchorSet"`

Does anyone have the same problem with integrating data?

**Comment by andrewwbutler** [comment]
Hi,

We haven't seen this error before. Are you able to provide example data that reproduces the issue?

**Comment by nicodemus88** [comment]
I'm not sure what I changed or did but the issue is solved and I can no longer reproduce the issue. Thank you for your feedback.
