### ISSUE TITLE
Strange behavior of Seurat v3.0

### ISSUE THREAD

**Issue by alanlamsiu** [satijalab/seurat#1598]
Recently, I found out that the behavior of Seurat is a bit strange when using future for parallelization. Then I decided to run a test by following the Guided Tutorial (https://satijalab.org/seurat/v3.0/immune_alignment.html) strictly, except that I used future parallelization with the following lines.

library(future)
plan("multiprocess", workers=20)

The attached figure in pdf is what I get from the analysis, without getting any error. It is quite obvious that something is going wrong.

[test.pdf](https://github.com/satijalab/seurat/files/3231693/test.pdf)

I have tried re-install Seurat, even R, however, I can't get Seurat to work normally.  Therefore, I am writing to seek if anyone has any clue on the issue.

Thanks!
Alan

**Comment by andrewwbutler** [comment]
This should be fixed now in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
