### ISSUE TITLE
Seurat 1.3 not working with Windows

### ISSUE THREAD

**Issue by joeburns06** [satijalab/seurat#16]
Hi,

There are a couple issues with Seurat 1.3 on Windows, both related to full file/directory name specification.  Read10X doesn't work because Windows doesn't recognize directories that end in "/".  So Read10X will not get past the initial file.exists check if I use Read10X("./"), but it will if I use Read10X(".").  But then it fails at  barcode.loc <- paste(data.dir, "barcodes.tsv", sep = "") because it's expecting "/" after data.dir.  

The second issue is with RunModularityClustering.  system.file(package="Seurat") returns "C:/Program Files/R/R-3.3.1/library/Seurat", but Windows doesn't recognize file paths with spaces in them.  Not sure what the workaround here is because Windows won't overwrite "Program Files" to "PROGRA~1" (just defaults back to "Program Files").

**Comment by andrewwbutler** [comment]
Hi Joe,

Thanks for pointing these out so clearly. I've updated the functions to be compatible with Windows (they work on my machine at least). If you're still having issues with things related to RunModularityClustering, make sure you have java installed.

**Comment by joeburns06** [comment]
No problem.  I’ll let you know if I have any more problems.  Thanks for fixing!

**Comment by joeburns06** [comment]
Hi Andrew,

Just tried running this again.  Read10X works great now.  Still having trouble with FindClusters though.  See the attached screenshots.  I have java installed and I added the directory to my path just in case.  Looks like it’s still having trouble with the space in “Program Files”.  Let me know if you need more info.  Lastly, is plot.SNN working on your end?

Thanks,
Joe

**Comment by andrewwbutler** [comment]
I can't seem to see the screenshots but one solution might be to just install the library in a different location. See the following [post](http://stackoverflow.com/questions/24646065/how-to-specify-lib-directory-when-installing-development-version-r-packages-from) for an example. 

Just pushed the fix for plot.SNN. It was originally built for data on the order of a couple hundred cells so running it on datasets much larger (such as the 3K PBMC one) will lead to some slow downs but it should work now.

**Comment by joeburns06** [comment]
Yea definitely.  My understanding was that if I moved the library location, I had to move all my libraries (and from a more general perspective, most people will have their libraries in the default location).  Not sure why the screenshots didn’t go through.  Trying them as attachments this time, hopefully they’ll go through.

**Comment by joeburns06** [comment]
And the fix you suggested worked.  Thanks for all the help!

-Joe
