### ISSUE TITLE
igraph installation/possible to use older igraph version?

### ISSUE THREAD

**Issue by whitleyo** [satijalab/seurat#160]
Hello,

I've been trying to install Seurat in R 3.4 (OS is Ubuntu 16.04 on a VM). I've been able to install most of the dependencies (after installing a missing debian package here and there), except for igraph. When I try and install igraph (version 1.1.2), I get an error replicating the one in this issue raised on github: https://github.com/igraph/rigraph/issues/213. I tried the suggested fix and it didn't work. I was wondering if an older version of igraph, say version 1.0.0, would work just fine for Seurat, or if Seurat specifically requires the newest version of igraph. Thank you for your help.

Best regards,
       Owen Whitley

**Comment by satijalab** [comment]
It should be fine - we use igraph for a couple plotting functions, but these should be unaffected.
