### ISSUE TITLE
integrating multi-modal data

### ISSUE THREAD

**Issue by talban14** [satijalab/seurat#1601]
When using FindIntegrationAnchors with citeseq data where I have both RNA and protein data in the assays  is the protein data lost when anchors are found based only on rna?  With the next step IntegrateData function I have a similar question here?   My end goal is to integrate my dataset based on RNA while maintining my protein data in the seurat object because later I would like to look at protein levels between the clusters.

**Comment by timoast** [comment]
The protein information is not lost. After integration, you can change the assay back to the assay used to store protein information to view the protein data
