### ISSUE TITLE
Way to do PCA using samples instead of cells?

### ISSUE THREAD

**Issue by talban14** [satijalab/seurat#1604]
Is there a way to analyze global similary and differences on a sample wise basis instead of a per cell basis? I have 16 samples to compare (8 treated and 8 Untreated) and would like to see if globally they group differently instead of the single cell tsne I want each sample to represent 1 datapoint.

**Comment by mojaveazure** [comment]
If you have your sample information in object metadata, you can set it as the object identity (so each cell is identified by sample), then use [`AverageExpression`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/AverageExpression) to consolidate each sample into a single data point.

```R
# Set a field in object metadata called "sample.name" for sample information
# Then run the following
Idents(object = object) <- "sample.name"
sample.object <- AverageExpression(object = object, return.seurat = TRUE)
```
