### ISSUE TITLE
Comparing proportions of cells in 2 sample types

### ISSUE THREAD

**Issue by rushikapandya** [satijalab/seurat#1607]
Hello,

I wanted to understand if I can comment on the changes in the proportion of cells in the control and stimulated samples when I perform the combined analysis.

**Comment by rushikapandya** [comment]
Scale data only scales the variable genes
```
[Scale Data](https://github.com/satijalab/seurat/issues/1198)
```

**Comment by yuhanH** [comment]
Do you run `ScaleData` in the RNA assay?

**Comment by rushikapandya** [comment]
I do run scale data on the Seurat objects before I merge them. This information is not stored in the combined object. I rerun the scale data again on the combined object.

**Comment by yuhanH** [comment]
Right.  The `scale.data` in the RNA assay is discarded after objects integration. 
You could re-run `ScaleData ` under the RNA assay.
