### ISSUE TITLE
ScaleData unused argument error

### ISSUE THREAD

**Issue by thesinglestcell** [satijalab/seurat#1608]
Hi Seurat team,

I am going through the pbmc3k tutorial and trying to perform run the ScaleData function on a preliminary dataset I've generated. However, I've come across the following error: 

> sclc <- ScaleData(sclc, features = all.genes)
Error in ScaleData(sclc, features = all.genes) : 
  unused argument (features = all.genes)

I get the following error when I try to run it without the 'features' argument:

> sclc <- ScaleData(sclc, features = all.genes) 
Error in ScaleData(sclc, features = all.genes) : 
  unused argument (features = all.genes)

I went back and tried running the provided 'pbmc' dataset through this pipeline and ended up with the same two errors (with and without the 'features' argument): 

> pbmc <- ScaleData(pbmc, features = pbmc.all.genes)
Error in ScaleData(pbmc, features = pbmc.all.genes) : 
  unused argument (features = pbmc.all.genes)
> pbmc <- ScaleData(pbmc) #same error 
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector

Here is some information about the session:
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6
other attached packages:
[1] dplyr_0.8.0.1 Seurat_3.0.1 

Any help/insight would be appreciated!

**Comment by mojaveazure** [comment]
Hi,

What's the object class of `sclc` and `pbmc`? It doesn't look like they're `Seurat` v3 objects

```R
class(x = sclc)
class(x = pbmc)
```

**Comment by thesinglestcell** [comment]
I get the following outputs for both objects: 
[1] "Seurat"
attr(,"package")
[1] "Seurat"

**Comment by andrewwbutler** [comment]
Are you able to provide an example dataset that reproduces the issue?

**Comment by thesinglestcell** [comment]
Hi Andrew,

I was just running through the normalization and scaling on my dataset again and the error does not seem pop up when I run 'ScaleData'. Not sure what changed between my last session and this time, but it seems like the problem is resolved for now. Do you have any idea what might have caused this?

If not, no worries. Thanks so much for your time.

Cheers,
David
________________________________
