### ISSUE TITLE
Error in FindAllMarkers with scaled SCTransform data

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#1609]
Hello!
 
I am using FindAllMarkers with SCTransform normalized data. My understanding from the vignette is that this would be best done with the residuals but is not supported yet. I am using the scale data as recommended. 

This is the call: 

```R
scRNA_merged_08.allMarkers <- FindAllMarkers(object = scRNA_merged_08, assay = "SCT", slot = "scale.data", only.pos = FALSE, min.pct = 0.10, test.use = "wilcox", return.thresh = 0.01,logfc.threshold = 0.25)
```

I get a running counter for calculating all the clusters (a few hours) then end up with this error message (and no scRNA_merged_08.allMarkers object):
```
Error in -gde$avg_logFC : invalid argument to unary operator
```
Any help would be greatly appreciated!!!!
Thank you! Josephine

**Comment by andrewwbutler** [comment]
Hi Josephine,

I believe this issue has been fixed on the develop branch. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development). You can set the `max.cells.per.ident` parameter to something small to quickly test.

**Comment by jogiles** [comment]
Great. This seemed to fix the problem with a small test. I'm running the full size clusters now. Thank you!
