### ISSUE TITLE
Subset Seurat object programmatic way

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#1610]
Hi, I am aware that Seurat's `subset` function is designed for interactive use only. However, I have several datasets which I need to analyze. It's a bit troublesome to do them individually so I am writing a R script in which to parse all my data into to run Seurat for all of them.

Is there any way I can perform subsetting in a programmatic way? 

I saw in #1053 that we can use `FetchData` and `which `but this only subsets the object called by FetchData, not the original Seurat object, isn't it? Can someone guide me on how to perform subsetting in a programmatic way?

**Comment by timoast** [comment]
> but this only subsets the object called by FetchData, not the original Seurat object, isn't it?

In this case the objects are the same. You can also subset by supplying a vector of cell names to retain, which will work programmatically. For example:

```r
cells.use <- colnames(pbmc_small)[which(pbmc_small[[]]['RNA_snn_res.0.8'] == 1)]
pbmc_subset <- subset(pbmc_small, cells = cells.use)
```

**Comment by nicodemus88** [comment]
Thank you very much for the solution!

**Comment by mpmorley** [comment]
What about using eval() for the variable? I've used this without issue so far. 

```R
cutoff<-40
pbmc_subset <- subset(pbmc_small, subset=nFeature_RNA > eval(cutoff))
```

**Comment by MSGanbold** [comment]
Hi, with "subset" function I get this error: "Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing'. I am not sure what is the problem. Thank you for your time!

#attempt 1
cl6_cells <- rownames( T4_obj@meta.data [which(T4_obj$res.0.6==6), ])
str(cl6_cells) #chr [1:273] "120703455022374" "120703455746859"
subset_obj <- subset(obj, cells = cl6_cells) #invalid char indexing error 

#attempt 2
subset_obj <- subset(obj, idents = 6) #invalid char indexing error

#attempt 3
subset_obj <- subset(obj, subset=res.0.6=="6") #invalid char indexing error
