### ISSUE TITLE
T-Test/Wilcoxon test for violin plot data

### ISSUE THREAD

**Issue by shikhagupta68** [satijalab/seurat#1612]
Hi,

I was wondering if there is a way to simultaneously have measures of significance while plotting the data using VlnPlot function?

Please let me know

Thank you

**Comment by andrewwbutler** [comment]
Hi,

The plots returned from `VlnPlot` are ggplot objects so while we do not natively provide options for that in Seurat directly, there are other solutions available. Here is [one example](https://github.com/const-ae/ggsignif).
