### ISSUE TITLE
Add cluster names to cell id

### ISSUE THREAD

**Issue by Hofphi** [satijalab/seurat#1614]
Hey,

I would like to know if there is a way to add the cluster names to the cell.ids of those cells that build the cluster. Basically rename the cells of the SeuratObject based on their clustering information.

There is some nice documentation on how to obtain basic info of the cells after clustering like `WhichCells(object=pbmc, idents="NK")` or how to rename cells 
`RenameCells(object = pbmc,new.names = paste0("A_", Cells(x = pbmc))`

However, I could not figure out how to add the cluster ID "NK" to the cell.ids obtained from the list of cells by `WhichCells(object=pbmc, idents="NK")`.

I would very much appreciate your help with this.

Best,
Philipp

**Comment by andrewwbutler** [comment]
Hi Philipp,

You can use `RenameCells` as follows to append the cluster information to the cell name (assuming the cluster information is stored in metadata).

```R
RenameCells(
  object, 
  new.names = paste0(object$cluster, "_", Cells(object))
)
```

**Comment by Hofphi** [comment]
Hey Andrew,
thanks for your suggestion. This solution worked great!
