### ISSUE TITLE
Error using CreateSeuratObject

### ISSUE THREAD

**Issue by hkanya** [satijalab/seurat#1615]
I;m trying to load a .txt file from GEO as a seurat object in R. However I keep getting this error:
**In storage.mode(from) <- "double" : NAs introduced by coercion**

The seurat object is created and seemed normal, however, subsequent plotting and analysis results in:
**Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  no 'dimnames[[.]]': cannot use character indexing**

I have tried using the read_tsv and read.table functions. Anyone with experience in analyzing GEO .txt data file? (text file is tab delimited)

**Comment by andrewwbutler** [comment]
Can you verify that after reading the data into R, that you have a matrix with the feature (gene) names as rows and the cell names as columns? This is what `CreateSeuratObject` is expecting as input.

**Comment by Ryo-1234** [comment]
When I read a CSV file I received the same error message; In storage.mode(from) <- "double" : NAs introduced by coercion. I'm using row.name=1 as Seurat tutorial.  Did you solve this error?

**Comment by hkanya** [comment]
Hi I resolved the issue using the read.table function and specifying the options. Here's the line I used:
raw_data <- read.table(file = <filename>, header = T, row.names=1, sep="", as.is=T)

**Comment by stuartblakemore** [comment]
Hi,

I'm having a similar issue with the CreateSeuratObject. I've loaded the data exactly how hkanya specifies in their last post, leading to a sparse matrix where the row names are column names aren't an integral part of df (as required). But I still get the exact same storage.mode(from) error. Any additional ideas anyone?
