### ISSUE TITLE
single panel for violin plot for multiple genes

### ISSUE THREAD

**Issue by shikhagupta68** [satijalab/seurat#1616]
Hi,

I was wondering if there is a way to plot multiple genes for a sample in single panel of violin plot.

Please let me know.

Thank you so much!

**Comment by andrewwbutler** [comment]
Hi,

That is not currently possible with the `VlnPlot` function.

**Comment by CodeInTheSkies** [comment]
Hi @andrewwbutler ,

Is plotting multiple genes on the x-axis on a single violin plot possible now?   I am just looking to plot one violin per gene, without any other group splitting.  Thanks!

**Comment by andrewwbutler** [comment]
Hi @CodeInTheSkies,

There are no immediate plans to add this functionality.
