### ISSUE TITLE
cell.embeddings

### ISSUE THREAD

**Issue by zhangguy** [satijalab/seurat#1617]
Hi,
In Seurat 2 after ```RunMultiCCA``` and ```AlignSubspace``` there will be cell embeddings in ```@dr$cca.aligned@cell.embeddings```. 
Is there an equivalent matrix in Seurat 3 after ```FindIntegrationAnchors``` and ```IntegrateData```?
Thanks.

**Comment by andrewwbutler** [comment]
Hi,

In the integration algorithm for in Seurat v3, we return the integrated ("corrected") values as a separate `Assay` that you can use for downstream processing (e.g. PCA, clustering, etc ... ). The closest "equivalent" I suppose would be the embeddings after running a dimension reduction procedure on the integrated matrix. Though to be clear, these are different algorithms and will produce different results.
