### ISSUE TITLE
merge 3 dataset but Vlnplot only 2

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#1618]
Hi Seurat team,

I am very new in the R and seurat programming and I am stuck with what is probably a very basic R programming problem.
I was able to generate a data set by merging 3 10X runs. I would like to only display 2 of the 3 dataset in the violin plot. 
here is my code:

```R
plots <- VlnPlot(mergetest2.big, 
  features = c("CD8A", "CD8B", "FCGR3A", "GZMB", "GZMH", "GZMA", "IFNG"),
  split.by = "orig.ident",  
  ident.include = c("V0", "V6"),
  pt.size = 0, 
  combine = FALSE)
CombinePlots(plots = plots, ncol = 1)
```

My 3 orig.ident are "V0" , "V6 " and "V8" and I would like to display on the vlnplot only V0 vs V6.  
So far, with the code above, it is only displaying the 3 dataset.
Thank you very much for your help!

**Comment by andrewwbutler** [comment]
Hi,

I think you want to use `group.by` instead of `split.by` here. Alternatively, you could set the idents to `orig.ident` before plotting to be sure they correspond to `orig.ident`. E.g.

```R
Idents(mergetest2.big) <- "orig.ident"
```

**Comment by shendong124** [comment]
Hi Andrew,

I changed the ident as following:
 plots <- VlnPlot(mergetest2.big, features = c("EOMES", "KLRG1", "FOXP3", "TIGIT"), split.by = "orig.ident", pt.size = 0, combine = FALSE, idents = c("test_merge_V0", "test_merge_V6"))
> CombinePlots(plots = plots, ncol = 1)

but now I am not ploting the different clusters on the x axis:
![image](https://user-images.githubusercontent.com/29153026/59067779-4f99cf80-8867-11e9-845b-8ef95c4e4b52.png)

before I had this:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/29153026/59067868-8b349980-8867-11e9-9500-8bb9516d8520.png">

I would like to have the violin plot of genes for different clusters (like second picture) but for only 2 ident.orig.

Thank you so much for you help!!!

**Comment by andrewwbutler** [comment]
One way to solve this would be to subset out the group you don't want and then plot it.
