### ISSUE TITLE
RunuMAP

### ISSUE THREAD

**Issue by LHXANDY** [satijalab/seurat#1619]
when I use RunUMAP in R ,I have a trouble.
 RunUMAP(pbmc, dims = 1:10)
 Error in RunUMAP.default(object = data.use, assay = assay, n.neighbors = n.neighbors,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).

**Comment by timoast** [comment]
Did you try installing umap-learn using pip?

**Comment by LHXANDY** [comment]
But I use seurat in R ,can I use PIP?

**Comment by YunZheHuang** [comment]
you have to install reticulate in R before using pip

**Comment by timoast** [comment]
@LHXANDY `umap-learn` is a python package, so you can install it any way you would install a python package. Using `pip` is one easy way, or if you want to install it from within R you can run: 

```r
reticulate::py_install(packages ='umap-learn')
```

@YunZheHuang I answered your question in #1672

**Comment by LHXANDY** [comment]
I have install pip and download umap-learn.But R can't find python.There are some relation about the location of R and python
![ABH9 7B8@4 $D_IE1CO74J6](https://user-images.githubusercontent.com/49830970/59323158-113f5d00-8d0c-11e9-87e8-8c1fc555b3b4.png)

**Comment by timoast** [comment]
Hi, please see the documentation for `reticulate` for information on how to set up reticulate, this is a bit outside the scope of the Seurat package https://rstudio.github.io/reticulate/
