### ISSUE TITLE
error in subsetting matrix

### ISSUE THREAD

**Issue by calvinhuapeng** [satijalab/seurat#162]
after updating Seurat to 2.0.1 and Matrix to 1.2-11 (R3.4.1, Rstudio1.0.153), this issue occurs when running pbmc scripts on pbmc data (https://s3-us-west-2.amazonaws.com/10x.files/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz):

> percent.mito <- colSums(pbmc@raw.data[mito.genes, ])/colSums(pbmc@raw.data)
>Error in colSums(pbmc@raw.data[mito.genes, ]) : 
  'x' must be an array of at least two dimensions

**Comment by andrewwbutler** [comment]
This can happen if you load a package that masks the colSums() function from the Matrix package. To be explicit, you can write `percent.mito <- Matrix::colSums(pbmc@raw.data[mito.genes,])/Matrix::colSums(pbmc@raw.data)`
