### ISSUE TITLE
Gene-gene correlation/de novo identification of co-regulated gene modules

### ISSUE THREAD

**Issue by ws2260** [satijalab/seurat#1622]
Hi,

I'm trying to find a way to look check modules of co-expressed genes. I'm aware that there is the `AddModuleScore` function in Seurat but is there a way to identify gene modules de novo before using those modules and applying the module scores for the clusters. 

I suppose one way to visualize this is a gene-gene correlation matrix heatmap of top variable genes to see the modules of co-expressed genes. Is there a proper way/an example I can follow?

Thanks!

**Comment by satijalab** [comment]
We often use the `DimHeatmap` function for the purpose of visualizing correlated sets of genes, as you can see at https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html. We find this very effective, but we have also seen instances where other groups have run WGCNA to find modules in single-cell data (though this is not native in Seurat).
