### ISSUE TITLE
Discrete expression values after SCTransform

### ISSUE THREAD

**Issue by lc822** [satijalab/seurat#1623]
Hi,

If I plot a violin plot on the "data" slot after running SCTransform, the expression values seem to take only specific values (see plot below).  Is this what I should be seeing?

Many thanks,
Lucy

![image](https://user-images.githubusercontent.com/22564745/58811335-84174c80-8617-11e9-9838-bb90b05ab4e2.png)

**Comment by yuhanH** [comment]
SCTransform will store the normalized gene value in the `scale.data` slot.
You could choose `scale.data` slot in the violin plot.

**Comment by baracus37** [comment]
Hi, I am having the same issue after running SCTransform. And its does not matter which slot is used for plotting. Interestingly, looking at the [SCTransform vignette](https://satijalab.org/seurat/v3.0/sctransform_vignette.html) the Violin Plots shown there towards the end of the page show the same phenomenon. I would be really interested in an explanation for this!

**Comment by Meijian** [comment]
Has this issue been solved? I have seen the same issue in my data.

**Comment by yuhanH** [comment]
Hi,  @Meijian 
It is solved. Just make sure to update seurat package. 
Then, you can see the violin plot difference in the following example:

```
 pbmc_small <- SCTransform(pbmc_small)
 VlnPlot(pbmc_small, features = 'PPBP' )
 VlnPlot(pbmc_small, features = 'PPBP', slot = 'scale.data')
```

**Comment by Meijian** [comment]
@yuhanH Thank you!

**Comment by lucygarner** [comment]
So should the "scale.data" slot rather than the data slot be used for sctransform data, because by default the "data" slot is plotted?  In the sctransform vignette, they don't use the "scale.data" slot (https://satijalab.org/seurat/articles/sctransform_vignette.html)

**Comment by yuhanH** [comment]
@lucygarner  
You are right. We only recommend to use data slot for the visualization such as FeaturePlot, VlnPlot

**Comment by liuweihanty** [comment]
Thanks for the answer @yuhanH . Just want to clarify. for downstream analysis eg to plot SCT normalized expression value of a gene vs pseudotime. Should I choose data or scale.data to be the expression value for that gene? If I understood it correctly, choosing data slot is the way to go right?(which is how the vignette does it). Thanks!

**Comment by yuhanH** [comment]
hi @liuweihanty 
Right. data slot is log-normalized counts result. You can either use RNA data slot or SCT data slot for your downstream analysis.

**Comment by eblchen** [comment]
In Seurat v5 the "slot" option is deprecated? Is there an alternative way to fix the issue of discrete expression values after SCTransform in VlnPlot()

**Comment by iddryg** [comment]
@eblchen I think you can just replace "slot" with "layer" and it should work...

**Comment by rieverg** [comment]
> @eblchen I think you can just replace "slot" with "layer" and it should work...

Doesn't work for me, the plots are exactly the same with the ones before the normalisation

**Comment by iddryg** [comment]
@rieverg same with me.

**Comment by nigiord** [comment]
From what I understand [here](https://github.com/satijalab/seurat/issues/6968#issuecomment-1444110896)  (issue #6968) , `scale.data` contains the residuals and should not really be used for visualization purposes in the case of SCT. The "corrected counts" stored in the `data` slot/layer (and shown by default) are especially computed for this purpose.

I’m not really sure why people are surprised by the discrete nature of the violin plots. Those are initially counts in the raw data (1, 2, 3, 4...) that are corrected to be comparable between genes, but they nonetheless remain counts.

I’m citing also another post of @saketkc : https://github.com/satijalab/seurat/issues/3923#issuecomment-1441954892

> As we show in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9) pearson residuals are variance stabilized and useful for downstream processing (including PCA/neighbor finding/dimensionality reduction but not for DE). We do recommend using the corrected counts for DE (which as we show in the paper gives more true positives controlling for the same FDR).

ViolinPlots are basically the visualization of a differential analysis, so it probably make more sense to represent counts and not the pearson coefficients.
