### ISSUE TITLE
Error when running FindConservedMarkers with empty cluster.

### ISSUE THREAD

**Issue by jessie-wangjie** [satijalab/seurat#1624]
Here is the error.
Error in names(marker.test) <- levels.split :
  'names' attribute [3] must be the same length as the vector [2]
Calls: <Anonymous> ... withVisible -> eval -> eval -> FindConservedMarkers

There was an empty cluster in one group, and FindMarkers didn't get run for this group.
then line 320: names(x = marker.test) <- levels.split got the error message. because the marker.test only had 2 vector, while the levels.split had 3 groups.

**Comment by timoast** [comment]
Hi, thanks for reporting. This is a bug and we will fix in the future.

**Comment by timoast** [comment]
Can you provide the output of `sessionInfo()`?
