### ISSUE TITLE
Would be helpful to be able to plot Scaled.Data in vizualizations

### ISSUE THREAD

**Issue by ericvaughn11** [satijalab/seurat#163]
I don't currently see any way to use the Scaled.Data in things like FeaturePlot or VlnPlot, however this would be very useful to plot for expression differences.

Currently I have a dataset with about 1500 more UMI per cell in one dataset vs the other, hence the normalized data plotted in FeaturePlot shows pretty much all cells in Dataset 1 to have a much higher expression value than Dataset2, even for genes that should be level in both.

I figure that regressing out nUMI differences in ScaleData should help show a more accurate relative expression for each cell, but I don't know how to plot this. I realize that the scaled data has negative values included, but would it be possible to just define the min value as zero and plot the relative expression scores from there?

**Comment by dhb2128** [comment]
It looks like FeaturePlot makes a call to FetchData. To get the scaled data you could add use.scaled as an input in the call to FetchData. See the source code for GenePlot for comparison
