### ISSUE TITLE
Marking up- or down-regulated gene in ggplot

### ISSUE THREAD

**Issue by cjpark85** [satijalab/seurat#1633]
Hello,

I'm following the example code of Seurat V3. I think this is kinds of basic, but I don't know how to change the dot color in ggplot. I used below script for plotting. Can I make up-regulated genes (adj p <0.05) as red dot and down-regulated genes (adj p <0.05) as blue dot? Also, Can I mark the line for adj p value = 0.05? Thank you.

`> head(x = KO.response, n = 15)`
                 p_val  avg_logFC pct.1 pct.2     p_val_adj
Gm8730   1.298682e-206 -1.4452369 0.392 0.872 2.773335e-202
Hsd17b11 1.207839e-151 -1.1300398 0.186 0.744 2.579340e-147
Susd3    1.799869e-148 -1.2681195 0.240 0.769 3.843619e-144
Etl4     8.132792e-147 -1.2433468 0.207 0.747 1.736758e-142
Arl4d    1.721160e-144 -0.6340928 0.062 0.639 3.675538e-140
Zbtb16   3.262431e-138 -0.6194148 0.006 0.562 6.966922e-134
Gas2l1   5.494558e-124 -1.0194410 0.571 0.842 1.173363e-119
Epas1    3.124102e-123 -0.8901516 0.216 0.701 6.671520e-119
Tmx1     2.409918e-122 -1.0523711 0.704 0.891 5.146380e-118
Stxbp6   2.588484e-122 -0.9340905 0.315 0.744 5.527707e-118
Mt2      4.903109e-122 -1.5040644 0.376 0.786 1.047059e-117
Wbp1l    2.957717e-118 -0.9005969 0.540 0.832 6.316205e-114
Tsc22d3  8.192543e-118 -0.8704138 0.247 0.713 1.749518e-113
S100a10  1.036380e-116 -1.1249672 0.836 0.927 2.213191e-112
Sphk1    3.227713e-113 -0.5302279 0.031 0.517 6.892781e-109
```
genes.to.label = c("Sprr2g", "Mt2", "Gm8730", "Slc25a33", "Gm26917", "Susd3", "Mt1", "Etl4", "S100a6", "Socs2",  "F3", "Areg", "Tnfaip6", "Ptgs2", "Cited4", "Ereg", "Inhba", "Pde10a", "Ddit4l", "Btc")
pp1 <- ggplot(avg.cells, aes(WT, KO)) + geom_point() + ggtitle("DEG")
pp1 <- LabelPoints(plot = pp1, points = genes.to.label, repel = TRUE, xnudge = 0, ynudge = 0)
plot_grid(pp1)
```

![image](https://user-images.githubusercontent.com/48735218/58912840-9d380000-86e0-11e9-90b3-2f89e54b0704.png)

**Comment by mojaveazure** [comment]
I'd suggest you look at ggplot2's [examples for `geom_point`](https://ggplot2.tidyverse.org/reference/geom_point.html#examples) and [`geom_abline`](https://ggplot2.tidyverse.org/reference/geom_abline.html)
