### ISSUE TITLE
Data Integration weird after 3.0.1 update

### ISSUE THREAD

**Issue by NTNguyen13** [satijalab/seurat#1635]
Hi, I have used Seurat v3 from Apr 16, and at that time I got no problem when integrating two data. I can get this tSNE plot after integration:

![Aligned](https://user-images.githubusercontent.com/39985901/58940943-ba8ace00-87b5-11e9-98c7-5e6a08db2bfa.png)

As you can see, two datasets are aligned quite well.
However, after 3.0.1 update, using the same code on the same data, but this time the result is totally different.

![image](https://user-images.githubusercontent.com/39985901/58941168-3127cb80-87b6-11e9-90c6-1383a30a3a45.png)

The data: https://drive.google.com/open?id=1A6wH8FcsPKws1-HQPRdX4VXmuMCOnvo0
My code
```
control.data <- Read10X(data.dir = "01_sample/Control.1/filtered_gene_bc_matrices/hg19/")
test.data <- Read10X(data.dir = "01_sample/Test.2/filtered_gene_bc_matrices/hg19/")

#load data into Seurat object, add mito.gene
load.data <- function(rawdata, mincell, sample) {
  seu.data <- CreateSeuratObject(count = rawdata,
                                 project = sample,
                                 min.cells = mincell)
  
  seu.data[["percent.mt"]] <- PercentageFeatureSet(object = seu.data, pattern = "^MT-")
  return(seu.data)
}
control <- load.data(control.data, 3, "Control")
head(control@meta.data)
control$stim <- "CTRL"

test <- load.data(test.data, 3, "Test")
test$stim <- "TEST"
head(test@meta.data)

control <- subset(x = control, subset = nFeature_RNA > 1000 & nFeature_RNA < 2500 & percent.mt < 19)
test <- subset(x = test, subset = nFeature_RNA > 1000 & nFeature_RNA < 2500 & percent.mt < 19)

# Normalization
control <- NormalizeData(object = control, normalization.method = "LogNormalize", scale.factor = 10000)
test <- NormalizeData(object = test, normalization.method = "LogNormalize", scale.factor = 10000)

control <- FindVariableFeatures(object = control, selection.method = "vst", nfeatures = 2000)
test <- FindVariableFeatures(object = test, selection.method = "vst", nfeatures = 2000)


immune.anchors <- FindIntegrationAnchors(object.list = list(control, test), dims = 1:20)
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)

DefaultAssay(object = immune.combined) <- "integrated"
immune.combined <- ScaleData(object = immune.combined, verbose = FALSE)
immune.combined <- RunPCA(object = immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunTSNE(object = immune.combined, reduction = "pca", dims = 1:20)
DimPlot(object= immune.combined, reduction = "tsne")
```

**Comment by andrewwbutler** [comment]
Hi,

I was unable to reproduce the issue with the code provided. However, if I set the plan "multicore" and then run it, I see the same problem. This seems to be related to  #1598. We are looking into this but for now I would use `plan("sequential")` as that gives the same results as before or revert to v3.0.0.

**Comment by andrewwbutler** [comment]
This should be fixed now in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by NTNguyen13** [comment]
Yes, I figured it out that I also used multicore in this, I can confirm that stop using multicore or update to the dev branch fixed this one
