### ISSUE TITLE
Recommendation of integration parameters of datasets with rare cell types

### ISSUE THREAD

**Issue by kvittingseerup** [satijalab/seurat#1636]
I have two datasets with plenty of overlap (>90% of cell types) where I want to transfer cell types from one to the other. The problem is the reference dataset include some quite rare cell types (e.g. n=15) which have decent similarly to one of the more numerous cell types. 

Are there some options in the label transfer process ( via ```FindTransferAnchors()``` and ```TransferData()``` as suggested [here](https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html)) that can be tweeted to increase the label transfer of this smaller group to the new dataset?

Cheers
Kristoffer

**Comment by timoast** [comment]
Hi, you could try decreasing `k.anchor` and/or `k.weight` if you are finding the rare cells are being misclassified. You could also look at the individual prediction scores for each cell type for each cell rather than simply classifying each cell as the cell type with the highest score.
