### ISSUE TITLE
The Link on the "Frequently Asked Questions" is wrong.

### ISSUE THREAD

**Issue by sameet** [satijalab/seurat#1638]
The link that is supposed to point to Vignette for querying Cell atlas instead points to the "Label Transfer" Vignette.

**Comment by andrewwbutler** [comment]
The links here are correct. The last two links under the first bullet point in Q1 should point to the same vignette as that demonstrates both integration and label transfer.

**Comment by sameet** [comment]
The text on the website says 

> Classifying cells in a query dataset based on a reference ‘atlas’

However, the word "atlas" is not mentioned at all on the link where it points to i.e. "https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html".

Is this is correct link?

Best,
Sameet

**Comment by andrewwbutler** [comment]
Yes, this is the correct link.

**Comment by sameet** [comment]
Okay, understood.  Please close the issue.
