### ISSUE TITLE
How to search and pull specific pattern of cell barcodes and add identity to metadata

### ISSUE THREAD

**Issue by JPingLin** [satijalab/seurat#1639]
Hi, 
I have ran cellranger aggr function on my upstream before seurat pipeline. And it returns barcodes.tsv.gz file in -1 and -2 pattern at the end of the barcode, ex:  
GGGCATCAGACTGGGT-1
....
GTAACGTAGAGTACCG-2
.....

I was wondering if there is the a function for search barcode names by pattern and add identity to metadata. So I can specify group.by in the downstream usage. I have look into WhichCells function, I have search the exact barcode by name="GGGCATCAGACTGGGT-1", but don't know how to search as "-1" or "-2" and edit info accordingly. 

Thanks!

**Comment by JPingLin** [comment]
Never mind, I found [it](https://kb.10xgenomics.com/hc/en-us/articles/360004524851-How-can-I-identify-the-10x-library-sources-when-analyzing-an-aggr-matrix-using-Seurat-).

**Comment by dcastaneda5** [comment]
Hi @JPingLin I am running into same problem now. Could you please post how you solved this issue?
Thank you

**Comment by JPingLin** [comment]
Sure, here is the link. Good luck! 
https://kb.10xgenomics.com/hc/en-us/articles/360004524851-How-can-I-identify-the-10x-library-sources-when-analyzing-an-aggr-matrix-using-Seurat-

**Comment by JingleW** [comment]
> Sure, here is the link. Good luck!
> https://kb.10xgenomics.com/hc/en-us/articles/360004524851-How-can-I-identify-the-10x-library-sources-when-analyzing-an-aggr-matrix-using-Seurat-

Hi JPingLin, 
According to the link I provided, I understand that "AGACCATTGAGACTTA-1 and AGACCATTGAGACTTA-2 are distinct cell barcodes from different libraries, despite having the same nucleotide sequence. ". However, I do not know how to set barcodes ended with -1 as one library, and barcodes with -2 as another library. Could you please provide the detailed code for doing this in Seurat? Thank you very much.

**Comment by JPingLin** [comment]
Hi 
Not sure if you are looking for editing your cell name after you created seurat? Instead of edit individual slot in seurat, it is best that you edit the names in the matrix space and create seurat object again to avoid any conflict. Or you can simply add a new meta.data slot to indicate different libraries if you don't want to loose your other calculation and meta.data. etc. 

Anyway, here is if you are looking for edit cell names, and after seurat object created
```
seurat.matrix <- seurat@assays[["RNA"]]@counts # pull the matrix
colnames(seurat.matrix) <- paste0(colnames(seurat), "-1") 
new.seurat <- CreateSeuratObject(seurat.matrix)
```

PS. I just realized that the link that I provided before somehow the content is changed from the 10x, and no longer address the original issue. Anyway, here is the code if you had a barcode-1 format and want to split them. 
`seurat$library <- unlist(lapply(strsplit(colnames(new.seurat), "-"), `[[`, 2))
`
Hope it helps, good luck!

**Comment by JingleW** [comment]
> Hi
> Not sure if you are looking for editing your cell name after you created seurat? Instead of edit individual slot in seurat, it is best that you edit the names in the matrix space and create seurat object again to avoid any conflict. Or you can simply add a new meta.data slot to indicate different libraries if you don't want to lose your other calculation and meta.data. etc.
> 
> Anyway, here is if you are looking for edit cell names, and after seurat object created
> 
> ```
> seurat.matrix <- seurat@assays[["RNA"]]@counts 
> colnames(seurat.matrix) <- paste0(colnames(seurat), "-1") 
> new.seurat <- CreateSeuratObject(seurat.matrix)
> ```
> 
> PS. I just realized that the link that I provided before somehow the content is changed from the 10x, and no longer address the original issue. Anyway, here is the code if you had a barcode-1 format and want to split them and search them.
> 
> ```
> seurat$library <- unlist(lapply(strsplit(colnames(new.seurat), "-"), `[[`, 2))
> which(seurat$library == "1") 
> ```
> 
> Hope it helps, good luck!

Thank you. I will try.

**Comment by j0ecal** [comment]
Hi, I have a related problem. I have a 10x dataset with barcodes tagged with ID and disease state e.g. AAACCTGAGAAACCTA_COL07_CRC. I'm trying to transfer them to another column and then split them into 2 separate metadata columns but I'm getting the following error:

Error: Cannot add more or fewer cell meta.data information without values being named with cell names.

Anyone have any ideas on how to get around this. My coding skills are pretty basic!

Thanks!

**Comment by JPingLin** [comment]
Hi @j0ecal, 

I guess you try to split the COL07 and CRC part into new meta.data label with your string but cell name does not match? 
have you created a Seurat object? If you do, what is the output of your Seurat@meta.data[1:5, 1] look like?
