### ISSUE TITLE
moving over to R implementation of UMAP?

### ISSUE THREAD

**Issue by Yue-Jiang** [satijalab/seurat#1640]
Looks like there is Rcpp implementation of UMAP available on CRAN: https://cran.r-project.org/web/packages/umap/index.html, or https://cran.r-project.org/web/packages/uwot/index.html per the umap doc's recommendation, I wonder if it makes sense to consider removing the dependency for the python implementation. Would be nice if user doesn't have to separately install python packages to be able to use RunUMAP. Admittedly the Rcpp implementation is probably less stable, but might be something to keep an eye on.

**Comment by andrewwbutler** [comment]
Hi,

It's a good suggestion. We're looking into this and will likely add this functionality in the near future as an option to `RunUMAP`.

**Comment by andrewwbutler** [comment]
Update to this, we've added `uwot` support to the `RunUMAP` function. This is now available on the develop branch and will become the default option when we release 3.1 to CRAN (though will retain the umap python wrapper option for those wanting to reproduce old plots. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
