### ISSUE TITLE
marker gene finding after integration

### ISSUE THREAD

**Issue by hwlim** [satijalab/seurat#1641]
Hi

I've tried FindIntegrationAnchors followed by IntegrateData.
Then after scaling/dimension reduction, I did FindAllMarkers.

However, it seems like FindAllMakers after "integration" only considers the anchor features only. Is there any way to perform the MarkerGene analysis using all expressed genes? or Is it impossible by definition of integration?

Thank you.

**Comment by andrewwbutler** [comment]
Hi,

Generally, we recommend performing DE on the "RNA" assay as in the [immune alignment](https://satijalab.org/seurat/v3.0/immune_alignment.html) vignette. This will contain the full set of features and thus consider all expressed genes.

**Comment by hwlim** [comment]
Great! Thank you!
