### ISSUE TITLE
Reinstall Seurat 2.3.4 - link provided doesn't work

### ISSUE THREAD

**Issue by cesco-lemon** [satijalab/seurat#1643]
Hi,

I've tried to reinstall Seurat v2.3.4 using:
devtools::install_version(package = 'Seurat', version = package_version('2.3.4'))

But this actually installs the v3.0.1. I've found the v2.3.4 here:
https://cran.r-project.org/src/contrib/Archive/Seurat/

Unfortunately though I am working on a cluster and can't link the terminal to a folder on my computer, I would need a link as "repo" that would direct the terminal to v2.3.4

Any idea on what I can do?

Thanks!

**Comment by riselinuh** [comment]
I have the same problem to reinstall Seurat v2.3.4 but it always installs v3.0.1. Any suggestions how should I proceed?

**Comment by andrewwbutler** [comment]
Hi,

You can try

```R
devtools::install_version(package = "Seurat", version = "2.3.4")
```

**Comment by cesco-lemon** [comment]
Hey Andrew,
I've tried this but a lot of the dependencies aren't attached to it and if I try to install them one by one it takes for ever and actually some of them seem to not work even if I install them separately.
Any suggestion?

**Comment by satijalab** [comment]
The command Andrew listed should install all associated dependencies, and we've been able to replicate this on multiple machines on our end. It sounds like you are having difficulty installing some of the dependencies which is unfortunately outside of Seurat. I'm closing this issue for now as its likely outside the scope of what we can help with, and you should contact the package developers. However, if you post more info on what dependencies are failing for you, we'll try to respond if we've seen a similar case before.
