### ISSUE TITLE
Read10X_h5 error

### ISSUE THREAD

**Issue by BSharmi** [satijalab/seurat#1644]
Hi,

I am using hdf5r v 1.2.0 and Seurat v 3.0.1.
I am trying to read the 1M_neurons_filtered_gene_bc_matrices_h5.h5 file (https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.3.0/1M_neurons/aggr - Gene / cell matrix HDF5 (filtered) h5 file) in R using 

    library(Seurat)
    library(hdf5r)
    my10X = Read10X_h5('/home/bsharmi6/NA_TF_project/scRNAseq_1million/1M_neurons_filtered_gene_bc_matrices_h5.h5',use.names = TRUE, unique.features = TRUE)

but get the error -

Error in if ((lp <- length(p)) < 1 || p[1] != 0 || any((dp <- p[-1] -  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]),  :
  NAs introduced by coercion to integer range

I was wondering if I need to process the data before I can read it in R?

Thank you

**Comment by timoast** [comment]
Hi, this is unfortunately a limitation of the sparse matrix class in R (`dgCMatrix`), as it cannot store more that 2^32-1 non-zero elements.

**Comment by paupuigdevall** [comment]
Has anyone find a work around to this problem?

**Comment by ShanSabri** [comment]
@timoast @paupuigdevall I'd also like to know if there exists a valid workaround.
