### ISSUE TITLE
Seurat 3.0 subset function "None of the requested variables were found" error

### ISSUE THREAD

**Issue by mdurante1** [satijalab/seurat#1647]
When I use the new subset() function with gene names that have a "-" in them followed by a number I receive the following error:

```
object.Nkx4.1 <- subset(x = object, subset = Nkx4-1 > 0)  

Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells,  : 
  None of the requested variables were found: 
```

This works in the deprecated function:

```
object.Nkx4.1 <- SubsetData(object, subset.name = "Nkx4-1", low.threshold = 0.00001, high.threshold = Inf)

Warning messages:
1: 'SubsetData' is deprecated.
Use 'subset' instead.
See help("Deprecated") 
2: 'OldWhichCells' is deprecated.
Use 'WhichCells' instead.
See help("Deprecated") 
```

I have tried multiple different syntax variations as well as storing the name using the c() function but none of this works. Is there a specific syntax I should be using?

Thanks,
Michael

**Comment by mojaveazure** [comment]
Hi Michael,

Please see https://github.com/satijalab/seurat/issues/1212#issuecomment-470983294 for subsetting on features that have a dash in their name.

**Comment by mdurante1** [comment]
Great, thank you for this information!

**Comment by annpa1231** [comment]
Hello,

I am trying to analyze motifs using Signac for single cell ATAC sequencing data.
Any idea what I am doing wrong when I type this command? I am getting error message that "none of the requested variables were found: SC294C_peaks"

da_peaks <- FindMarkers(object = SC294C, ident.1 = 'MPH SPP1 LGMN', ident.2 = 'MPH INHBA FABP4', only.pos = TRUE, test.use = 'LR', latent.vars = 'SC294C_peaks')
Error in FetchData(object = object, vars = latent.vars, cells = c(ident.1,  : 
  None of the requested variables were found: SC294C_peaks


Thank you
