### ISSUE TITLE
Feature names cannot have underscores ('_'), replacing with dashes ('-')

### ISSUE THREAD

**Issue by dxiangmedsci** [satijalab/seurat#1648]

**Comment by sun-zhenzhu** [comment]
Hi, I'm using R in windows and following the official Guided tutorial — 2,700 PBMCs. I also get this warning and cannot use CreatSeuratObject function. Could you share your solution?

**Comment by yhr961002** [comment]
> Hi, I'm using R in windows and following the official Guided tutorial — 2,700 PBMCs. I also get this warning and cannot use CreatSeuratObject function. Could you share your solution?嗨，我正在窗口中使用 R, 并遵循官方指导教程 ——2700 个 PBMC。我还收到了这个警告，无法使用 CreatSeuratObject 函数。您能分享您的解决方案吗？

I think you can sanitize the gene names yourself before passing the matrix to CreateSeuratObject.

rownames(pbmc.data) <- gsub("_", "-", rownames(pbmc.data))
