### ISSUE TITLE
CreateAssayObject error

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#1650]
Hello
When I tried to CreatAssayObject with my ADT matrix, it throw out an error saying:

`Error in CreateAssayObject(counts = sample7.adt) : 
  No feature names (rownames) names present in the input matrix`

My input csv file format is exactly the same as the one that in "Using Seurat with multi-modal data" tutorial, so why I got this error message?

**Comment by andrewwbutler** [comment]
This error implies that you are providing a matrix with no rownames to `CreateAssayObject`. Take a look at the input matrix and make sure that it has the features as rownames and the cell names as the colnames. 

```R
sample7.adt[1:5,1:5]
```

If you're using the same csv file, did you set `row.names = 1` as in the tutorial?

**Comment by satijalab** [comment]
Andrew's previous answer (that the matrix has no rownames) is indeed most likely what is happening. I am closing this issue for now, but feel free to comment if you are certain that your matrix has row names, but are still running into issues

**Comment by Ncondeg** [comment]
Hello, 

Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features) : 
  No cell names (colnames) names present in the input matrix

how do I solve this error?

**Comment by andrewwbutler** [comment]
`CreateAssayObject` just requires that the input matrix (`counts` in your example) has column names. If you have something like barcodes that you want to associate with each cell, the you should label the column names of the input matrix with those. If the exact name of the cells doesn't matter for your analysis, you could just label them however you want. E.g.
```R
colnames(counts) <- paste0(colnames(counts), 1:ncol(counts)) 
```

**Comment by FernandaScar** [comment]
Hello!

I'm new at Single Cell and I'm having the same error "Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features) No cell names (colnames) names present in the input matrix" when I'm trying to create a Seurat object.

I'm using a public data from GEO https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE93374 and the GSE93374_Merged_all_020816_BatchCorrected_LNtransformed_doubletsremoved_Data.txt.gz zip file. In my columns are the barcodes. 

I've try colnames(counts) <- paste0(colnames(counts), 1:ncol(counts)) as well and didn't work out.

Someone knows how to fix this error?

**Comment by zhangmin0923** [comment]
> Hello.I'm also a new at Single Cell and I also met the same problem. Have you solved it? Can you help me
