### ISSUE TITLE
regress nCount_RNA in ScaleData

### ISSUE THREAD

**Issue by jmzvillarreal** [satijalab/seurat#1652]
Hi Seurat users,
Is it necessary or advisable to regress out the number of UMIs if the dataset has been previously normalized by library size per cell ?
Cheers !
Jaime.

**Comment by andrewwbutler** [comment]
Hi,

Generally, I'd recommend using [sctransform](https://github.com/ChristophH/sctransform) if you believe that the number of UMIs is confounding in your analysis. A vignette is available [here](https://satijalab.org/seurat/v3.0/sctransform_vignette.html).
