### ISSUE TITLE
subset, WhichCells issue pulling info from assay RNA

### ISSUE THREAD

**Issue by GabeFalcao** [satijalab/seurat#1653]
Hello all,

I have been having an issue trying to isolate cells that express a specific gene after **integrating** the data. There is no issue whatsoever if the gene is one of the ones used in the integrative steps. However, if I try to subset my data based on a gene present only in the assay "RNA", I get this error:
`> eypf.only <- subset(seurat.object, subset = eyfp > 1, slot = 'counts')`
`Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : no 'dimnames[[.]]': cannot use character indexing`

Thanks!

**Comment by andrewwbutler** [comment]
Hi Gabe,

If you set the default assay to "RNA" first, then the subset should work. E.g.

```R
DefaultAssay(seurat.object) <- "RNA"
eypf.only <- subset(seurat.object, subset = eyfp > 1, slot = 'counts')
```
