### ISSUE TITLE
The input data of demo 'Integration and Label Transfer' is different from the original data

### ISSUE THREAD

**Issue by nottwy** [satijalab/seurat#1656]
Recently, I'm learning your tool Seurat and find that the input data of the case 'Integration and Label Transfer' (https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html) is different from the original data accompanying with the manuscript.

I download this one "SMART-Seq2 (E-MTAB-5061)" and find the count of ['ICMT','HP1507101_F1'] = 33.728877901 in the original data,
but it's equal to 74 in the input data you provided (https://www.dropbox.com/s/1zxbn92y5du9pu0/pancreas_v3_files.tar.gz?dl=1).

So, my question is how to explain this difference and what pre-process have you done on the original data when you prepared this input data.

Thank you for your reply.

**Comment by timoast** [comment]
Hi, that dataset contains both normalized and count data as consecutive columns in the matrix. We use only the count data in the integration vignette.

```r
dat <- read.table("~/Downloads/pancreas_refseq_rpkms_counts_3514sc.txt", sep = '\t', header = FALSE)
cellnames <- unlist(strsplit(readLines(con = "~/Downloads/pancreas_refseq_rpkms_counts_3514sc.txt", n = 1), '\t'))
gene.names <- make.unique(as.character(dat$V1))
rownames(dat) <- gene.names

norm.data <- dat[3:((ncol(dat)/2)+1)]
count.data <- dat[((ncol(dat)/2)+2):ncol(dat)]

colnames(norm.data) <- cellnames[2:length(cellnames)]
colnames(count.data) <- cellnames[2:length(cellnames)]
```

```r
> count.data['ICMT','HP1507101_F1']
[1] 74
> norm.data['ICMT','HP1507101_F1']
[1] 33.72888
```

**Comment by nottwy** [comment]
thank you for your answer!
If it's convenient, could you tell me how do you realise that there is still "hidden" data which appended to each row?
I could find these data without your reminding.
