### ISSUE TITLE
How can I chang the label's color in Dimplot to black?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1657]
Hello,When I used a white-background theme, the default white labels become invisible.
![图片](https://user-images.githubusercontent.com/30619010/59159375-40cb4b00-8afb-11e9-8a7b-2d81dbe7d183.png)

How can I chang the label's color to black?

**Comment by andrewwbutler** [comment]
Hi,

The default label color is black. E.g.

```R
plot <- DimPlot(object = pbmc_small)
LabelClusters(plot = plot, id = "ident")
```

Can you try running `LabelClusters` after adjusting your theme? If that doesn't work, could you post the code you're using?

**Comment by Sophia409** [comment]
Hello, Andrew.Do you mean that we couldn't change the default lable color to user-defined? @andrewwbutler

**Comment by mojaveazure** [comment]
As seen in the [documentation for `LabelClusters`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/LabelClusters), you can pass extra parameters to `LabelClusters` that get passed on to `geom_text_repel` or `geom_text`, including color

> ... Extra parameters to geom_text_repel, such as size

```R
plot <- DimPlot(object = pbmc_small) + NoLegend() + DarkTheme()
LabelClusters(plot = plot, id = 'ident', color = 'white')
```

**Comment by Sophia409** [comment]
Thank you,mojaveazure.I try your code, but it didn't change the label color.And in your documentation for LabelClusters,there is no color parameter as you showed.How can I change the label color only to my defined ?Could you show me the   @andrewwbutler 
`> plot <- DimPlot(Merge.integrated,pt.size = 1.5,label=TRUE, label.size = 6)
> plot
> plot <- DimPlot(Merge.integrated,pt.size = 1.5,label=TRUE, label.size = 6)
> LabelClusters(plot = plot, id = 'ident', color = 'white')
> plot`
![图片](https://user-images.githubusercontent.com/30619010/59206678-07b4d880-8bd8-11e9-97a4-53e98d623dd4.png)
