### ISSUE TITLE
Gene signal diminished after Integration

### ISSUE THREAD

**Issue by dwucsf** [satijalab/seurat#1659]
I'm integrating 4 different biological samples, and 3 out of the 4 have a cluster defined by gene X (i.e. NGN3). After I integrate the 4 datasets, I barely see any signal of NGN3 in any cluster. Is there a way to preserve the expression of known marker genes such as NGN3 using integration?

**Comment by yuhanH** [comment]
After the integration, you'd better visualize your gene expression in the RNA slot. 
You could either switch the default assay to "RNA" `Default(obj)<-"RNA"` or use `rna_NGN3` in your visualization.

**Comment by dwucsf** [comment]
Thanks! One follow-up question: Are there downstream analyses in which you would recommend using the integrated, batch-corrected gene values?

**Comment by yuhanH** [comment]
For downstream analysis, we recommend to use the original data.  Integrated data mainly help you find the cells you need to compare.

**Comment by dwucsf** [comment]
Got it. Thank you very much, @yuhanH! Not sure if you've used integrated data with pseudotemporal ordering, but if you have: do you recommend using the integrated data for import into Monocle 3 for pseudotemporal ordering? If so, would you also recommend then using the original data to map the gene expression levels back on the pseudo temporal trajectories and to conduct branch analyses?

**Comment by Sophia409** [comment]
@dwucsf @yuhanH Same question. Which assay(integrated vs RNA) to use for importing batch-corrected data to monocle?
