### ISSUE TITLE
Integrating stimulated vs. control PBMC datasets and In file(file, "rt") :cannot open

### ISSUE THREAD

**Issue by sygongcode** [satijalab/seurat#1660]
Hi, everyone,
when I was doing "Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses". When I want to read the matrixes that are the output from cellranger3.0 (3 files, barcodes.tsv, features.tsv, matrix.mtx), I have a problem that is "Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :cannot open
file'C:/Users/shang/Documents/data/xxxscRNAseq/15mins_xxx/filtered_feature_bc_matrix': Permission denied. The code is:
ctrl_wdsnr115min.data <- read.table(file = "C:/Users/shang/Documents/data/xxxscRNAseq/15mins_xxx/filtered_feature_bc_matrix", sep = "/t")
Can anyone help me? I am a new one who just learn some basic knowledge about R. Thank you.

**Comment by mojaveazure** [comment]
`read.table` doesn't work on directories, only files. You passed it a directory for reading, not a file. Moreover, `read.table` requires a TSV- or CSV-like format, not a [Matrix Market Exchange](https://math.nist.gov/MatrixMarket/formats.html) file (MTX files are Matrix Market Exchange files). To read Cell Ranger output, please see [`Read10X`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/Read10X)

**Comment by sygongcode** [comment]
> `read.table` doesn't work on directories, only files. You passed it a directory for reading, not a file. Moreover, `read.table` requires a TSV- or CSV-like format, not a [Matrix Market Exchange](https://math.nist.gov/MatrixMarket/formats.html) file (MTX files are Matrix Market Exchange files). To read Cell Ranger output, please see [`Read10X`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/Read10X)

Sorry for the delayed reply. Thank you so much for your help.
