### ISSUE TITLE
conversion between the V2 and V 3

### ISSUE THREAD

**Issue by LHXANDY** [satijalab/seurat#1662]
Hi:
 I want to import my seurat object into monocle by "importcds".But I find the monocle packages can not support the seurat v3 object. And I want to do some postime analysis in monocle.How I deal with this problem

Thanks in advance!

**Comment by mojaveazure** [comment]
As stated [previously](https://github.com/satijalab/seurat/issues/1096#issuecomment-493503574), we are in the [process of adding Seurat &harr; Monocle converters](https://github.com/satijalab/seurat/pull/1241).
