### ISSUE TITLE
How can I change the unselected cells' color in Dimplot to user defined instead of default black? 

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1663]
Hello,satijalab! In dimplot function, cols.highlight parameter can only be used to set colors to highlight the selected cells,not unselected cells.
So, how can I change the unselected cells' color in Dimplot to user defined such as grey instead of default black? Just as the  result `cols =c("lightgray", "red") `in featureplot makes.

![图片](https://user-images.githubusercontent.com/30619010/59215485-ef4eb900-8beb-11e9-947f-35909ef4d044.png)

**Comment by andrewwbutler** [comment]
Hi,

To change the unselected cells color, set the `cols` parameter. E.g.

```R
DimPlot(pbmc_small, cells.highlight = Cells(pbmc_small)[1:10], cols = "blue", cols.highlight = "yellow")
```

**Comment by jbridge873** [comment]
Is there a way to make the cols.highlight unique for each highlighted cells?

**Comment by JiahuaQu** [comment]
If I not only want to color the unselected cells in grey, but also want to split the plot into six samples and color each genotype in one highlighted color in one plot, how should I do? I found the 
DimPlot(mydata, reduction = "umap", split.by = "sample", group.by = "genotype", cols = "grey")
doesn't work.
Error in `f()`:
! Insufficient values in manual scale. 6 needed but only 1 provided.
Run `rlang::last_error()` to see where the error occurred.

Specifically, I want to generate six plots in parallel. Every one, the selected sample in a highlited color while all other unselected samples in grey.

Thank you.
