### ISSUE TITLE
How to change the default legend title (unselected and Group1)in Dimplot to my defined text?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1664]
Hello, does anyone know how I can change the default legend title (unselected and Group1)in Dimplot to my defined text?Below is my code and corresponding picture. 
 `DimPlot(Merge.integrated, pt.size = 2,cells.highlight = WhichCells(Merge.integrated,cells= grep(E14, Merge.integrated@meta.data$time)),cols.highlight="red")`
![图片](https://user-images.githubusercontent.com/30619010/59213317-24a4d800-8be7-11e9-8107-aaf8e6b9867c.png)

**Comment by andrewwbutler** [comment]
Hi,

`DimPlot` returns a ggplot object so you can manipulate these plots as you would any other ggplot object. I'd recommend familiarizing yourself with their [manual](https://ggplot2.tidyverse.org/reference/) if you are going to want to do a lot of customization. For changing stuff with the legend, here's an example:

```R
DimPlot(pbmc_small, cells.highlight = Cells(pbmc_small)[1:10]) + 
  scale_color_manual(labels = c("New Value1", "New Value2"), values = c("grey", "red")) +
  labs(color = "legend title")
```
