### ISSUE TITLE
PercentageFeatureSet does not work with features

### ISSUE THREAD

**Issue by irmed** [satijalab/seurat#1665]
Hi!

Thank you a lot for the great package!

There is one issue I am not able to solve. When I am running PercentageFeatureSet on integrated data set, trying to select my genes of interest stored in character vector format I receive this:

PercentageFeatureSet(integrated, features=genes_list)
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  no 'dimnames[[.]]': cannot use character indexing

I tried to run with RNA assay, but have the same error.
With "MT-" it works on the raw data, but not with integrated data.

Thank you a lot in advance!

**Comment by timoast** [comment]
Can you confirm all the genes are present in the integrated assay?

```r
all(genes_list %in% rownames(integrated))
```

**Comment by irmed** [comment]
Yes, there are. I use them for downstream analysis. 
But these genes are not in HVG list that was used for integration:

combined.features <- SelectIntegrationFeatures(object.list=integration.list, nfeatures = 2000, assay = NULL, verbose = TRUE)
combined.anchors <- FindIntegrationAnchors(object.list = integration.list, dims = 1:30, anchor.features = combined.features)
to_integrate <- Reduce(intersect, lapply(combined.anchors@object.list, rownames))
integrated <- IntegrateData(anchorset = combined.anchors, dims = 1:30, features.to.integrate = to_integrate)
integrated <- ScaleData(object = integrated, verbose = FALSE, features=to_integrate) 
integrated <- RunPCA(object = integrated, npcs = 30, verbose = FALSE)
ElbowPlot(object = integrated, ndims = 30)
integrated <- RunUMAP(object = integrated, reduction = "pca", dims = 1:20)

**Comment by timoast** [comment]
Can you please run `all(genes_list %in% rownames(integrated))` and post the output?

**Comment by irmed** [comment]
![genes](https://user-images.githubusercontent.com/17064974/59532887-f27dc980-8eb7-11e9-995a-101312cc7b13.png)

**Comment by mojaveazure** [comment]
`PercentageFeatureSet` does not work if the `counts` slot is empty. Integration in Seurat doesn't populate the `counts` slot.

Can you run `Seurat:::IsMatrixEmpty(GetAssayData(integrated, slot = 'counts'))`?

**Comment by irmed** [comment]
Sorry for the late response!

> Seurat:::IsMatrixEmpty(GetAssayData(integrated, slot = 'counts'))
[1] TRUE

I see, it makes sense!
Thank you, **mojaveazure**!

**Comment by nasqar** [comment]
@mojaveazure  Does it make sense to calculate the percentages based on normalized counts ('data' slot)?

Thanks

**Comment by fangxingv5** [comment]
Hi, I met the same problem when used PercentageFeatureSet, could u tell how did u sovle this problem?

**Comment by sudiptaashe** [comment]
Hi, I too am facing the same problem.
Seurat:::IsMatrixEmpty(GetAssayData(integrated, slot = 'counts')) returned FALSE
Can you help with how to get over this problem?

**Comment by kmuench** [comment]
@fangxingv5 , @sudiptaashe , Depending on what your objective is, you might be able to work around this simply by pointing PercentageFeatureSet to another assay, e.g.:

data.combined_sc_integrated[["percent.rps"]] <- PercentageFeatureSet(data.combined_sc_integrated, pattern = "^RPS", assay = 'RNA')

**Comment by udp3f** [comment]
I have the same error and 
Seurat:::IsMatrixEmpty(GetAssayData(integrated, slot = 'counts')) returns FALSE for me. Even the percent.rps throws the same error. Any suggestion?

**Comment by pbpayal** [comment]
Can PercentageFeatureSet work with ENSEMBL IDs or it just works with gene names. I ask this because I gave a list of ENSEMBL Ids and it gives the following error:

`Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing`

However I have chekced the dataset contains the ENSEMBL Ids.
I am using Seurat version 3.1.5

**Comment by CHoeltermann** [comment]
Second this, I have the same problem:

I give PercentageFeatureSet() a vector of ENSEMBL IDs that are 100% in my data set. It returns

Error in h(simpleError(msg, call)) (seurat_analysis.R#42): error in evaluating the argument 'x' in selecting a method for function 'colSums': invalid character indexing

What do I miss?

**Comment by rLannes** [comment]
I have the same issue, 
gene are present and count is not empty

```

 Seurat:::IsMatrixEmpty(GetAssayData(d7_1, slot = 'counts'))
[1] FALSE

d7_1@assays$RNA@counts[rownames(d7_1) %in% mito_gene_id,]
15 x 14044 sparse Matrix of class "dgCMatrix"
   [[ suppressing 54 column names ‘AAACCCAAGATACGAT-1’, ‘AAACCCAAGATGGGCT-1’, ‘AAACCCAAGCGTGAGT-1’ ... ]]
                                                                                                                        
FBgn0013680  1 .  .  .  .  .  .  .  .  .  .  1  1  . .  . .  10  1 .  .  1 .  .  10 .  1  .  .  .  .  1  1  .  .  . .  .
FBgn0013674 11 6  6  6  3 33  4  1  5 11 17  9  5 17 2  6 4 332  3 2  5  8 2 10 258 1 16  3 21  5 40 12 30 12  9 10 5 19
FBgn0013675 12 3  7 10  4 44  4  6  5  7 31 13 13 17 3 11 4 330  4 5  7 11 7  6 266 3 17  9 20 10 53 10 40 18 20  8 4 17
FBgn0013673  1 .  .  .  .  .  .  .  .  .  .  .  1  . .  . .   4  1 .  .  . .  .   2 .  .  .  .  .  .  2  .  .  .  . .  .
FBgn0013672 10 5  4  3  3 25  6  6  5  7 14  4  4  7 3  4 1 367  3 1  8  6 7 10 226 4 16  3 16  8 47  5 40 10 13  5 7  6
FBgn0013676 10 1  6  3  4 45 11  3  2  6 17  7  8 13 7 10 1 297  7 4 19 12 7 15 246 4 27 10 19  9 46  8 27 15  9 10 7 11
FBgn0013681  . .  2  .  .  .  .  1  .  .  2  .  .  . .  . .  12  . .  .  . .  1   9 .  .  2  3  .  2  .  .  1  .  . .  .
FBgn0013684  1 1  .  1  1  4  .  .  1  .  .  .  .  . 1  2 .  30  1 .  .  1 .  .  14 .  5  .  1  2  6  1  6  1  1  . 1  .
FBgn0013683  . .  1  .  .  .  .  .  .  .  .  .  .  . .  . .   2  . .  .  . .  .   . .  .  .  .  .  .  .  .  .  .  . .  .
FBgn0013685  1 .  2  .  .  1  .  .  .  .  .  .  1  . 1  1 .  17  1 .  1  2 .  .   7 .  1  .  .  .  2  .  2  .  .  . 1  .
FBgn0013678  5 1  6  4  2 16  4  3  2  7  9 10  4  7 2  4 6 197  6 3  5  1 2  2 132 5 12  3 10  5 27  5 10  7  7  2 4  3
FBgn0013679  . .  .  .  3  .  .  .  1  .  2  1  1  1 1  . 1  41  3 .  1  2 .  .  19 1  4  1  2  1  1  1  6  2  2  1 2  1
FBgn0013686 13 6 11 11 12 13  8 10 16  8 21 11  3  9 5 11 6 135 12 5 14 19 6 15 148 4 72  9 32 19 26 11 55 12 16 14 7 14
FBgn0013688  2 3  1  1  .  2  1  .  3  1  1  1  1  . 5  1 .  18  1 3  2  3 2  .   3 1  7  1  2  1  5  .  5  2  2  1 1  .
FBgn0262952  2 2  1  1  .  3  1  .  2  1  2  1  .  2 .  . .  81  . .  1  . 1  .  37 1  2  1  2  3  5  1  6  .  3  2 1  3
                                                                
FBgn0013680  1  .  .  2  .  .  .  2  . . .  .  .  .  .  . ......
FBgn0013674 10 10  6  8 16 13 11 14 11 2 4 17 19  3  6  9 ......
FBgn0013675 12 16  8 15 14  4  4 15 12 5 6 20 30  3  3  8 ......
FBgn0013673  .  1  1  .  1  .  .  .  . . .  .  2  1  .  . ......
FBgn0013672  4 13  5 13 10 12  1  5  8 3 6  5 13  1  5  5 ......
FBgn0013676  5 17  4  9  6 15  7  9  7 1 2 13 23  5  6 13 ......
FBgn0013681  .  1  .  .  2  .  .  .  . . .  1  .  .  .  . ......
FBgn0013684  3  2  1  .  .  2  2  .  1 1 1  3  2  1  .  1 ......
FBgn0013683  .  .  .  .  .  .  .  .  . . .  .  .  .  .  . ......
FBgn0013685  .  .  .  .  2  1  1  .  . . .  2  1  .  2  1 ......
FBgn0013678  5  5  3  3 11  3  6  9  8 . 4  8 13  4  4  . ......
FBgn0013679  .  .  3  1  1  .  .  1  . . 1  1  2  1  1  . ......
FBgn0013686  7 15 12  6 28 20  6  6 11 9 4 17 10 11 12  9 ......
FBgn0013688  .  1  2  .  2  .  .  2  . . .  .  1  .  .  2 ......
FBgn0262952  1  .  1  .  3  1  2  1  1 . .  .  2  .  .  2 ......

 .....suppressing 13990 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................
> d7_1[["percent.mt"]] <- PercentageFeatureSet(d7_1, features = mito_gene_id)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'colSums': invalid character indexing

```
