### ISSUE TITLE
Treated versus control 

### ISSUE THREAD

**Issue by brunetc** [satijalab/seurat#1666]
Dear Seurat Team,

I am currently performing the analysis of my sc data obtained with 10X. I haw two different experimental conditions, treated and control. I have run the pipeline "Tutorial: Integrating stimulated vs. control PBMC datasets". I was able to identify each cluster and obtain conserved and non-conserved genes among conditions. Since I have different number of cells for some clusters in the normal versus the treated condition; I was wondering if the changes I observe, such an upregulation of some genes, are actually due to the treatment or only to the difference in cell number. Is this normalize somehow?

Thanks a lot in advance. 

Clarisse

**Comment by satijalab** [comment]
Assuming that you are performing differential expression *within* a cluster and *across* conditions (for example, the 'Identify differential expressed genes across conditions' section in : https://satijalab.org/seurat/v3.0/immune_alignment.html), then the DE genes will not be affected by relative differences in cell number.
