### ISSUE TITLE
Do heatmap for integrate

### ISSUE THREAD

**Issue by wupeng2** [satijalab/seurat#1668]
hello ,
thanks for your excellent job, but recently I got confused when I preform Doheatmap function for integrat.
1\i don't know whether should I use 'RNA' assay or 'integrate'assay for Doheatmap.
2\as for 'integrate'assay,even I set sacle all genes by using follow script 
immune.combined <- ScaleData(immune.combined, features = rownames(x = immune.combined),verbose = T)
there still only 2000 gene in scale.data for 'integrate'assay.

**Comment by satijalab** [comment]
We would suggest using the RNA assay. As a general rule of thumb, we suggest using the integrated assay to learn cluster identities, trajectories, etc. - but then use the original RNA assay to do downstream analyses (i.e. find differentially expressed genes between conditions, etc.)
