### ISSUE TITLE
How to obtain DEGs (markers) of some specific cells

### ISSUE THREAD

**Issue by rahulnutron** [satijalab/seurat#1669]
Hello everyone,

I am trying to obtain "markers" of some specific cells from a cluster. I am using a Arabidopsis root single cell data. I found gene wox5 is present in two cells of cluster 10. I want to run FindMarkers, where the program should only compare the two cells of cluster 10 (instead of all cells of cluster 10) with all other cells in different clusters. In this way I aim to obtain some specific genes of the two cells which express wox5 in cluster 10. The code I used is given below

cells<-WhichCells(object = ara, expression = AT3G11260 > 3, idents = 10)
c10.markers <- FindMarkers(object = ara, cells.use = cells, 
                                ident.1 = 10, ident.2=NULL,min.diff.pct = 0.5, only.pos = TRUE)
However, the genes I obtain show much higher expression in other clusters also (may not be specific to the two wox5 expressing cells). I will be thankful if anyone let me know if this is the correct way to do this.

Regards,
Rahul

**Comment by Vladyslav3** [comment]
Hey,

If you want to compare only the 2 cells with other cluster/s you can just subset your cells in two different character vectors. One containing the 2 cells which express your gene and the other list with the cells against which you want to compute FindMarkers.
And if you dont have a particular reason to use ident.1 and ident.2 dont use them for DEG computing.
Example: 
`DEG = FindMarkers(data, cells.1 = cells_1, cells.2 = cells_2, verbose = T)`

So it will compute DEG between cells.1 and cells.2

**Comment by rahulnutron** [comment]
Thanks Vladyslav3, 
I changed my code according to your suggestion, however getting a different error. Just to test I used the below code

DEG = FindMarkers(data, cells.1 = c("AGTGTCATCTGCTTGC", "CAAGTTGTCACAAACC", "GGCTGGTAGATGCCAG"), cells.2 = colnames(ara), verbose = T)

Error in FindMarkers.default(data, cells.1 = c("AGTGTCATCTGCTTGC", "CAAGTTGTCACAAACC",  : 
  The following cell names provided to cells.1 are not present:

**Comment by Vladyslav3** [comment]
Your cells.1 should be names of cells (in your case those 2 which express wox5) and cells.2 should be names of cells against which you want to find differential expressed genes:

This is the code that I normally use:
The matrix have cells in colnames and genes as rownames.
```
data = as.matrix(data)

#Select the names of cells to which to compute DEG
cells_1 = colnames(data)[grep("X", colnames(data))]
cells_2 = colnames(data)[grep("Y", colnames(data))]

DEG = FindMarkers(data, cells.1 = cells_1, cells.2 = cells_2, verbose = T)```

**Comment by rahulnutron** [comment]
Thank you!

I tried to use the 2 cells but I think minimum 3 cells are need to be considered. I changed the limit then to obtain more than 2 cells, which express wox5. This time again I get the same error. I think there are some problem with my cell names.

> cells<-WhichCells(object = ara, expression = AT3G11260 > 3, idents = 10,invert = F)
> cells
[1] "AGTGTCATCTGCTTGC" "CAAGTTGTCACAAACC"
> DEG = FindMarkers(data, cells.1 = cells, cells.2 = colnames(ara), verbose = T)
Error in FindMarkers.default(data, cells.1 = cells, cells.2 = colnames(ara),  : 
  Cell group 1 has fewer than 3 cells
> cells<-WhichCells(object = ara, expression = AT3G11260 > 2.5, idents = 10,invert = F)
> cells
[1] "AGTGTCATCTGCTTGC" "CAAGTTGTCACAAACC" "GGCTGGTAGATGCCAG" "TAAGCGTTCACTCCTG" "TGGACGCCAGAGCCAA"
> DEG = FindMarkers(data, cells.1 = cells, cells.2 = colnames(ara), verbose = T)
Error in FindMarkers.default(data, cells.1 = cells, cells.2 = colnames(ara),  : 
  The following cell names provided to cells.1 are not present: 
>

**Comment by Vladyslav3** [comment]
I think you are having problems because Whichcells return a list of names and your input in FindMarkers should be a vector. To select the first vector of the list its like cells[[1]].
Try : 
`DEG = FindMarkers(data, cells.1 = cells[[1]], cells.2 = colnames(ara), verbose = T)`

The "data" should be your matrix.

If this doenst work you are having problem with names. Try to check if they match.
Check also if you have current Seurat version, should be v3.

Try also to check [https://github.com/satijalab/seurat/issues/718](url) since it has a simular topic to yours.

**Comment by rahulnutron** [comment]
Sorry! It was my mistake, I used "data" instead of "ara" as an object.  Also this brings me to an another error, which I am trying to fix (formal argument "cells.1" matched by multiple actual arguments). Thanks for your suggestion.

**Comment by rahulnutron** [comment]
Thank you Vladyslav3. Your suggestion worked.
I was using "data" instead of my matrix "ara.data". "Copy-paste" problem :).

>remc <- colnames(ara)[!colnames(ara) %in% cells]
>deg = FindMarkers(object=ara.data,cells.1=cells,cells.2=remc,only.pos = T)
