### ISSUE TITLE
creating new seurat object from cells of excitatory neuron clusters

### ISSUE THREAD

**Issue by seekingseq** [satijalab/seurat#1673]
hi all! 

I am very new to Seurat and coding in general, so sorry if this is a silly question (I don't see this exact question has been asked before). 

I have data from scRNA seq of DMSO and RO48. I completed the first 2 guided tutorials on the satija lab site, so that is where I am at now. I want to use the data from tutorial 2 where I combined DMSO and RO48 and create a new seurat object only from the cells of excitatory neuron clusters. 

Following that, I want to combine those excitatory neuron clusters together as a single seurat object, while preserving originial identity (i.e., RO48-tutorial 1, DMSO-tutorial 1)

any and all help is appreciated! thanks in advance!

**Comment by satijalab** [comment]
Here are a  couple resources that might help:

Seurat object interaction vignette: `https://satijalab.org/seurat/v3.0/interaction_vignette.html`
Command list "cheat sheet": `https://satijalab.org/seurat/essential_commands.html`

Note that when you merge objects, the meta data merges as well. So for example, you could say

```r
object1$ID = "RO48"
object2$ID = "DMSO"
merged_object = merge(x=object1, y=object2)
```
