### ISSUE TITLE
Which assay(integrated vs RNA) to use for importing batch-corrected data to monocle3?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1674]
Hi,satijalab! Should I use the batch-corrected, integrated gene values in the "integrated" assay or the non-integrated gene values in the "RNA" assay for downstream Monocle analyses?
And As you said in the past,[Seurat does not return batch-corrected expression values ,Instead, Seurat can be used to generate a corrected cell/cell distance matrix. ](https://github.com/satijalab/seurat/issues/283).
Does it mean that integrated gene data matrix values in the "integrated" assay is a corrected cell/cell distance matrix? If so,we couldn't import the integrated data to monocle.Can we only use monocle to do batch correct  and further pseudotemporal ordering analysis ?Has any way to import the batch corrected data integrated by seurat to monocle and do further analysis?

**Comment by satijalab** [comment]
Thanks for the question. Please note that for our previous answer, that was for Seurat v2, and does not hold in the new version.

You should use the intergrated data for constructing a pseudotime trajectory.

However, if you are doing any comparisons across conditions (for example, if you construct an integrated trajectory for WT and KO cells, and want to find genes that change with pseudotime in the WT but not in the KO), you will need to do those comparisons on the original data.

**Comment by Sophia409** [comment]
@satijalab   Hi,thank you for your reply.
Monocle v2 has been deprecated and v3 has been finalized.As you advised,I can  use the intergrated data for constructing a pseudotime trajectoryin monocle.But now we can only import one assay(integrated or RNA) to monocle and do further pseudotime trajectory.So we are really expecting your added support for the  v3 CellDataSet object.
For example,I have integrated data from mouse cells from different times,including E11,15,18,p5,p10,p30.And I want to do further linage tracing and pseudotime trajectory.My data was batch corrected,so it's not right for me to just use one assay to do analysis.Because if I import the integrated assay to monocle for clustering,monocle will automatically find markers for these cluster referring to integrated data matrix.[And in fact, you said that for data integration these values should not be interpreted next, and  contain negative values as seurat are subtracting values from datasets to remove technical differences. 
But if import the RNA assay to monocle for clustering,the data matrix was not batch corrected,it still not right to use it for do clustering and pseuodotime analysis.
I'm really confused and waiting for your reply.Thank you!
](https://github.com/satijalab/seurat/issues/1057#issuecomment-454145423)
![图片](https://user-images.githubusercontent.com/30619010/59547441-90819a80-8f71-11e9-82d5-aa022ea1188f.png)

**Comment by Sophia409** [comment]
@satijalab Hello,
thank you for your explanation. I'm still a little confused.You mean we should use the intergrated data for constructing a pseudotime trajectory.But there are only data slot and scaledata slot on the integrated assay.The  batch corrected counts slot doesn't exists, which is the key to import to monocle to do analysis.And monocle people advise to give the counts slot not the normalized data.when you give it the batch corrected integrated assay,actually you give a corrected cell/cell distance matrix.[ That is pretty tricky for monocle to analysis.](https://github.com/cole-trapnell-lab/monocle3/issues/111#issuecomment-503790399) How can i deal with the problem?

**Comment by veravevo** [comment]
I'm having the exact same problem: I have used integrated Seurat-data to construct the trajectory, but need to used the "RNA"-counts to perform comparison between conditions in Monocle2. However, only one assay can be stored in the CDS, and changing values in the CDS is not possible. Is there a solution to this issue?

**Comment by rg734** [comment]
I was just wondering whether there was ever any resolution/additional thought around this problem?
