### ISSUE TITLE
Error in BuildClusterTree after SCTransform in Seurat 3.0 

### ISSUE THREAD

**Issue by yxiao832** [satijalab/seurat#1677]
Hello Seurat Team, 

I have WT and KO Seurat objects. And I got this error after I use BuildClusterTree 

BuildClusterTree(Combined): 
Finished averaging RNA for cluster 0
Finished averaging RNA for cluster 1
Finished averaging RNA for cluster 2
Finished averaging RNA for cluster 3
Finished averaging RNA for cluster 4
Finished averaging RNA for cluster 5
Finished averaging RNA for cluster 6
Finished averaging RNA for cluster 7
Finished averaging RNA for cluster 8
Finished averaging RNA for cluster 9
Finished averaging RNA for cluster 11
Finished averaging RNA for cluster 12
Finished averaging RNA for cluster 13
Finished averaging RNA for cluster 14
Finished averaging RNA for cluster 15
Finished averaging RNA for cluster 16
Finished averaging RNA for cluster 17
Finished averaging RNA for cluster 18
Finished averaging RNA for cluster 19
Finished averaging RNA for cluster 20
Finished averaging RNA for cluster 21
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 3000, 1445

Then I tried dim with BuildClusterTree(Combined, dims=20) and I got another error:

  |                                                  | 0 % ~calculating  Error in embeddings[cells, ] : incorrect number of dimensions

Here below is my script I used before "buildclusterTree "
WT.data <- Read10X(data.dir = ")
KO.data <- Read10X(data.dir = ")

WT <- CreateSeuratObject(counts = WT.data)
KO <- CreateSeuratObject(counts = KO.data)

WT[["percent.mt"]] <- PercentageFeatureSet(WT, pattern = "^mt-")
KO[["percent.mt"]] <- PercentageFeatureSet(KO, pattern = "^mt-")

WT <- NormalizeData(WT, normalization.method = "LogNormalize", scale.factor = 10000)
WT <- FindVariableFeatures(WT, selection.method = "vst", nfeatures = 2000)

KO <- NormalizeData(KO, normalization.method = "LogNormalize", scale.factor = 10000)
KO <- FindVariableFeatures(KO, selection.method = "vst", nfeatures = 2000)

Integrated.anchors <- FindIntegrationAnchors(object.list = list(A,B), dims = 1:20)
Combined <- IntegrateData(anchorset = Integrated.anchors, dims = 1:20)

Combined <- SCTransform(Combined, vars.to.regress = "percent.mt", verbose = TRUE)

Combined <- RunPCA(Combined, verbose = T)
Combined <- RunUMAP(Combined, dims = 1:30, verbose = T)
Combined <- FindNeighbors(Combined, dims = 1:30, verbose = T)
Combined <- FindClusters(Combined, verbose = T)

Thanks a lot!
Yang

**Comment by andrewwbutler** [comment]
Hi,

Please see  #1613 regarding the workflow with SCTransform and IntegrateData. Are you able to provide an object that reproduces the `BuildClusterTree` error?

**Comment by snsansom** [comment]
Hi Andrew,

On our systems running the SCTransform vignette (https://satijalab.org/seurat/v3.0/sctransform_vignette.htm)l + BuildClusterTree returns the following:

`
> pbmc_data <- Read10X(data.dir = "../filtered_gene_bc_matrices/hg19/")
> pbmc <- CreateSeuratObject(counts = pbmc_data)
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')

> pbmc <- PercentageFeatureSet(pbmc, pattern = "^MT-", col.name = "percent.mt")

> pbmc <- SCTransform(pbmc, vars.to.regress = "percent.mt", verbose = FALSE)
There were 50 or more warnings (use warnings() to see the first 50)

> pbmc <- RunPCA(pbmc, verbose = FALSE)
> pbmc <- RunUMAP(pbmc, dims = 1:30, verbose = FALSE)
> pbmc <- FindNeighbors(pbmc, dims = 1:30, verbose = FALSE)
> pbmc <- FindClusters(pbmc, verbose = FALSE)
> DimPlot(pbmc, label = TRUE) + NoLegend()

> pbmc <- BuildClusterTree(pbmc)
Finished averaging RNA for cluster 0
Finished averaging RNA for cluster 1
Finished averaging RNA for cluster 2
Finished averaging RNA for cluster 3
Finished averaging RNA for cluster 4
Finished averaging RNA for cluster 5
Finished averaging RNA for cluster 6
Finished averaging RNA for cluster 7
Finished averaging RNA for cluster 8
Finished averaging RNA for cluster 9
Finished averaging RNA for cluster 10
Finished averaging RNA for cluster 11
Finished averaging SCT for cluster 0
Finished averaging SCT for cluster 1
Finished averaging SCT for cluster 2
Finished averaging SCT for cluster 3
Finished averaging SCT for cluster 4
Finished averaging SCT for cluster 5
Finished averaging SCT for cluster 6
Finished averaging SCT for cluster 7
Finished averaging SCT for cluster 8
Finished averaging SCT for cluster 9
Finished averaging SCT for cluster 10
Finished averaging SCT for cluster 11
Error in hclust(d = data.dist) : 
  NA/NaN/Inf in foreign function call (arg 11)

`
Best wishes,
Steve
