### ISSUE TITLE
Question regarding Cell Cycle Scoring and sctransform order

### ISSUE THREAD

**Issue by j-andrews7** [satijalab/seurat#1679]
Hi,

In the Cell Cycle regression vignette, you run `NormalizeData` before assigning the Cell Cycle scores. However, since `SCTransform` combines the normalization and scaling steps, I was wondering if it's valid to perform Cell Cycle scoring on the raw data prior to running `SCTransform` so that they can properly be used for regression.  Or would the proper approach be to run SCTransform, add the Cell Cycle scores, and then run it again to regress out the differences?

Thanks.

**Comment by yuhanH** [comment]
In the  `SCTransform`, there is one parameter called `vars.to.regress`.
You could put the variables containing Cell Cycle scores.

**Comment by j-andrews7** [comment]
Yes, I understand that, but that's not my question. Is running the `CellCycleScoring` function on unnormalized data prior to `SCTransform` valid or would it lead to potential problems? Should I run `NormalizeData`, run `CellCycleScoring`, and then run `SCTransform` to scale and regress out the Cell Cycle scores?

**Comment by satijalab** [comment]
Thanks for the question, and this is indeed a bit complex. I would recommend exactly the procedure you list out above. Make sure you run `NormalizeData` prior to `CellCycleScoring`. This learns cell cycle scores that can be added to the `vars.to.regress` parameter in `SCTransform`. For all downstream analyses, you can use the `SCT` assay.

**Comment by atermanini** [comment]
Hi, why not run SCTransform, then evaluate cell cycle, than apply again SCTransform using vars.to.regress ? This should avoid using the old NormalizeData, using the more robust sctranform. Am I wrong?

**Comment by mistrm82** [comment]
I had the exact same thought as @atermanini , I'm assuming it should be okay?

**Comment by CodeInTheSkies** [comment]
Same question, as raised above by @atermanini !!  Would be great if @satijalab could please comment  :)

Thanks a tonne!!

**Comment by satijalab** [comment]
I think both approaches would be valid. We have not tested the latter (running SCTransform twice), but it  should in principle be slightly more robust if there are substantial differences in sequencing depth across cells.

**Comment by anoronh4** [comment]
If we are running SCtransform twice, should we set `assay = "RNA", new.assay.name = "SCT"` the first time and then `assay = "SCT", new.assay.name = "SCT"` the second time? Not sure if we can overwrite the first assay.

**Comment by romanhaa** [comment]
> If we are running SCtransform twice, should we set `assay = "RNA", new.assay.name = "SCT"` the first time and then `assay = "SCT", new.assay.name = "SCT"` the second time? Not sure if we can overwrite the first assay.

I think you should run SCTransform with the same parameters both times.

```r
seurat <- SCTransform(seurat, assay = 'RNA', new.assay.name = 'SCT', ...)
seurat <- CellCycleScoring(seurat, ...)
seurat <- SCTransform(seurat, assay = 'RNA', new.assay.name = 'SCT', vars.to.regress = ...)
```

Otherwise you would normalise the already normalised data, no? You just need the first run of `SCTransform()` to learn the cell cycle status. Then, you normalise the same raw data again but while also regressing for cell cycle effects. At least this is how it makes sense to me.

**Comment by anoronh4** [comment]
hi romanhaa,

I see your point but I am not sure if assay "RNA" is original data or not, i guess that is the main gap in my knowledge. if RNA remains "unnormalized" data and and i calculate cell cycle regression based on SCT assay, then i'm not really combining the power of 2 SCTransform calculations, I'm just replacing my first regressed dataset on one set of variables with a second regression dataset on another set of variables. Let me go through the two scenarios I'm thinking about: 

```
sample <- SCTransform(sample, vars.to.regress = c("percent.mt","nFeature_RNA","nCount_RNA",assay = 'RNA', new.assay.name = 'SCT')) # unnormalized, untransformed
sample <- CellCycleScoring(sample, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE) #presumably running on SCT assay
sample <- SCTransform(sample, vars.to.regress = c("S.Score", "G2M.Score"), assay = 'RNA', new.assay.name = 'SCT') #runs on same original assay.
```
And here's the next one
```
sample <- SCTransform(sample, vars.to.regress = c("percent.mt","nFeature_RNA","nCount_RNA",assay = 'RNA', new.assay.name = 'SCT')) # unnormalized, untransformed
sample <- CellCycleScoring(sample, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE) #presumably running on SCT assay
sample <- SCTransform(sample, vars.to.regress = c("S.Score", "G2M.Score"), assay = 'SCT', new.assay.name = 'SCT') #runs on the assay already normalized/transformed.
```
Looking forward to hearing from the community!

**Comment by romanhaa** [comment]
Each assay has two slots for the expression data + an additional which might contain fewer genes than the other two.

* `seurat@assays$RNA@counts`
* `seurat@assays$RNA@data`
* `seurat@assays$RNA@scale.data`

When you initialise your Seurat object, both `counts` and `data` contain your raw transcripts counts (assuming that's your raw data). While the matrix stored in `counts` generally remains the raw data, the data in the `data` slot will be normalised when you run `NormalizeData()`.

Now, I don't have a lot of experience with the `SCTransform()` method, but in the description of the function you find the following part:

> Results are saved in a new assay (named SCT by default) with counts being (corrected)
counts, data being log1p(counts), scale.data being pearson residuals; sctransform::vst intermediate results are saved in misc slot of new assay.

Based on this, my proposal is the following:

```r
# normalize data with SCTransform()
sample <- SCTransform(
  sample,
  assay = 'RNA',
  new.assay.name = 'SCT',
  vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA')
)

# perform cell cycle analysis (make sure to specify the "assay" parameter
sample <- CellCycleScoring(
  sample,
  s.features = s.genes,
  g2m.features = g2m.genes,
  assay = 'SCT',
  set.ident = TRUE
)

# normalise again but this time including also the cell cycle scores
sample <- SCTransform(
  sample,
  assay = 'RNA',
  new.assay.name = 'SCT',
  vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA', 'S.Score', 'G2M.Score')
)
```

This should then overwrite the data in the `SCT` assay slot with your data after normalisation for all those factors you provided while ensuring that the cell cycle analysis was performed on your data normalised with `SCTransform()`.

Hopefully a Seurat developer will call me out if I'm wrong :)

**Comment by CodeInTheSkies** [comment]
Hello @romanhaa , @anoronh4 , @j-andrews7 , @yuhanH , 

Just wanted to check in as to which of the above-discussed methods you all tried, and at this date, how did your results turn out, and which of the methods (NormalizeData followed by SCT, or running SCT twice) would you recommend?

Many thanks for any responses, and am looking forward to hearing your views!

**Comment by j-andrews7** [comment]
I tried both and doing nothing at all with cell cycle, saw little difference, and stopped caring about cell cycle phases in my data. 🤷‍♂

**Comment by anoronh4** [comment]
> Hello @romanhaa , @anoronh4 , @j-andrews7 , @yuhanH ,
> 
> Just wanted to check in as to which of the above-discussed methods you all tried, and at this date, how did your results turn out, and which of the methods (NormalizeData followed by SCT, or running SCT twice) would you recommend?
> 
> Many thanks for any responses, and am looking forward to hearing your views!

Correct, I have been trying both of these approaches and even tried regressing out the difference between G2M and S scores. I have yet to to come across a dataset where it made a difference -- and I process datasets from lots of different tissue types/preps. i'll keep it in my code, simply because it is recommended, but that's about it.
