### ISSUE TITLE
how to extract the aligned raw data after performing alignment between two single cell data

### ISSUE THREAD

**Issue by guest-zhoupc** [satijalab/seurat#168]
Hi, 
I am trying to remove batch effects by performing alignment between two single cell data from two chips (replicates). Based on my understanding, the scaled data are aligned in low-dimensional space. But it seems the raw data (e.g., FPKM or UMI data) have not been aligned. I think it is better if I can extract the aligned raw data, which will be useful for downstream analysis such as differential expression analysis and pseudotime analysis, etc. Could you give me some suggestions on how to extract the aligned raw data? Thank you!

By the way, I also encountered a error when using RunTSNE function.  I found this problem appears when the number of cell is less than # 100 (If I used more cells such as 180, there is no problem). Although I changed the Perplexity to be 10 or even 5, this error also appears. 
object <- RunTSNE(object, dims.use = 1:numPC, do.fast = T,check_duplicates = FALSE,Perplexity = 10)
Error in Rtsne.default(as.matrix(data.use), dims = dim_embed, ...) : 
  Perplexity is too large.

Could you give me some suggestions? Thanks!

**Comment by ErisonChen** [comment]
hi   zhou
    Could you please tell me how to fix this issue?
    I happened to meet this and confused with it.

Thanks
