### ISSUE TITLE
Analyzing multi-model with  merging 3 samples

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#1680]
Hello, 

I want to merge 3 samples into one and analyzing it. Each samples have an RNA expression data and an ADT(Antibody) data. I just found the tutorial showing how to merge RNA expression data, but don't know how to merge ADT data, anyone give me any idea?

**Comment by timoast** [comment]
Hi, running `merge` will also merge each assay in the object if they have the same name.
