### ISSUE TITLE
Leiden algorithm does not use random seed

### ISSUE THREAD

**Issue by ccasar** [satijalab/seurat#1683]
Hi,

running 

`data <- FindClusters(data,algorithm=4,random.seed = 0)`

twice in a row returns different clustering results. 

The `find_partition` method from the `leidenalg` package has a `seed` argument. Is there a specific reason the `random.seed` argument is not passed through?

**Comment by mschilli87** [comment]
@ccasar: I added a patch passing down `random.seed` from `FindClusters` to `find_partition` via `RunLeiden`. Could you test https://github.com/mschilli87/seurat/patch-1 to confirm you suggested solution works?

**Comment by ccasar** [comment]
@mschilli87 Nope, does not work. Using the default value for `FindClusters` `random.seed` or specifying custom values ends up with an error message:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: integer argument expected, got float

Detailed traceback: 
  File "~/miniconda3/lib/python3.6/site-packages/leidenalg/functions.py", line 88, in find_partition
    optimiser.set_rng_seed(seed)
  File "~/miniconda3/lib/python3.6/site-packages/leidenalg/Optimiser.py", line 230, in set_rng_seed
    _c_leiden._Optimiser_set_rng_seed(self._optimiser, value)
```
I've tried with an explicit integer casting in your code (i.e. adding `random.seed = int(random.seed)` in line 563), but `FindClusters` still throws the same error after reinstalling the package and restarting the R session.

**Comment by andrewwbutler** [comment]
This should be fixed now in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
