### ISSUE TITLE
Combine many sc runs

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#1685]
Hello,

is there another way to combine more than 2 samples of sc data with Seurat NOT using RunMultiCCA?

Thanks, Chris

**Comment by jspaezp** [comment]
Hello @balthasar0810 (Chris)

You could manually append the count matrices (`cbind` or equivalent) and then generate a Seurat object. 
Let me know if this could work for you.

Best, Sebastian

**Comment by j-andrews7** [comment]
See the [merge vignette](https://satijalab.org/seurat/v3.0/merge_vignette.html).

**Comment by timoast** [comment]
Yes, concatenating the matrices or running `merge` will work, or you could run our new [integration](https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html) methods. Please note that RunMultiCCA is no longer present in the latest version of Seurat.
