### ISSUE TITLE
Transformation after scTransform 

### ISSUE THREAD

**Issue by sean00002** [satijalab/seurat#1687]
Hello Seurat Team,

After the `scTransform`, the SCT would be the default. But can I still apply some other transformations to the data after `scTransform` before running UMAP or T-SNE? I have tried to modify `@assays$SCT@data` directly but the plots turned out to be the same as before. I am wondering what matrix or data UMAP and T-SNE would take as an input from the object?

Best, 
Sean

**Comment by satijalab** [comment]
Prior to running UMAP or tSNE, we first run PCA to reduce the dimensionality of our data. The PCA pulls from the `@assays$SCT@scale.data` slot, which stores the Pearson residuals.

For more details, take a look at https://satijalab.org/seurat/v3.0/sctransform_vignette.html (and in particular, the "Where are normalized values stored for sctransform?" drop down.

**Comment by sean00002** [comment]
Thank you for your answer! But does this mean that for the current version, I am not able to apply the transformation to Pearson residuals? and this is the reason why tSNE and UMAP stay the same since they are only taking input from Pearson residuals?
