### ISSUE TITLE
Install Seurat version 2.3.4

### ISSUE THREAD

**Issue by nhuhoa** [satijalab/seurat#1688]
Dear Seurat team, 
I have a question regarding the installation: 
I tried to install Seurat version 2.3.4 using R command (RStudio, anaconda) that you indicate in Seurat website. Before installing Seurat, I did not have any version of Seurat package in my computer.
https://satijalab.org/seurat/install.html
        install.packages('Seurat', repo = c('satijalab.org/ran/', getOption("repos")))
However, the installed Seurat version is 3.0.1, not 2.3.4 as indication. Have you updated the Seurat package in this repository? 

I also tried: 
devtools::install_version(package = 'Seurat', version = package_version('2.3.4'))
but seems version 2.3.4 is not uploaded here. 

Can you show me how to install Seurat version 2.3.4? Thanks a lot, 

Best, 
Hoa Tran

**Comment by satijalab** [comment]
We are unable to reproduce this error on our end. The command you are running is the correct one - please be sure that the `devtools` package is installed. I am closing the issue for now as I assume that is the problem, but if it is not, please feel free to reply with the exact error you get when you run the devtools command.
