### ISSUE TITLE
Tutorial - Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses

### ISSUE THREAD

**Issue by AnnaC-G** [satijalab/seurat#1691]
Hi, 

I'm currently learning how to use RStudio to analyze single-cell databases; to do that I'm using the Seurat Tutorial. I'm currently working through the  "Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses" tutorial. I had some trouble opening the files but managed to int he end with read.csv ; but when I try to plot the anchors found, I get different results; in fact I don't even find the same cell markers. My first head marker is : RP11-51J9.5  
Do you have any idea what the problem could be? Am I reading the files wrong?

**Comment by satijalab** [comment]
Unfortunately its hard for us to debug without more information, but perhaps the read.csv solution is not correctly reading in the files. You should be able to read in the files using the commands in the vignette on any system.

I am closing this issue for now as it is likely related to this file input issue, but if you have been unable to fix it, please feel free to follow up and list exactly what errors you receive when trying to read in the expression matrices.
