### ISSUE TITLE
Subset according to a list of barcode from vloupe

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#1693]
Hi Seurat team,

I have a list of barcodes that I got from the vloupe file. It is a group of TCR that are highly enriched in my samples. I would like to make a heatmap of certain genes only for this list of TCRs. 

I read the issue #1435 that will make me integrate the VDJ data and then I can subset according to a given barcode or CDR3?

Alternatively I was thinking to subset a seurat object according to that list of barcode? But I am very new using R and ca not find a way to do this.

Thank you very much for your help,
Shen

**Comment by timoast** [comment]
Hi, you can subset the Seurat object to contain any given list of cells using the `subset` function, for example:

```r
cells.use <- head(colnames(pbmc_small))
subset_pbmc <- subset(pbmc_small, cells = cells.use)
subset_pbmc
```
```
An object of class Seurat 
230 features across 6 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne
```

**Comment by shendong124** [comment]
Thank you! It is working very well!

I am detailing a bit here for the other beginner users like me:

I converted my list of barcodes (csv file) into a list of vectors of
characters :

V8_CD4barcodes <- read.csv("~/Desktop/testbarcodes2.csv", header = FALSE)$V1
V8_CD4barcodes_vector <- as.character(V8_CD4barcodes)

then subset:
testbarcode <- SubsetData(merge002003.big, cells = V8_CD4barcodes_vector)

then heatmap on the subset

DoHeatmap(testbarcode, features = c("MKI67", "CD3E", "CD4", "CD8A", "CD8B",
"GZMB", "FOXP3", "IFNG", "MKI67", "IL2RA", "CTLA4"))

Shen




Le ven. 21 juin 2019 à 08:23, Tim Stuart <notifications@github.com> a
écrit :

**Comment by chjp** [comment]
Error in subset.default(pbmc_small, cells = cells.use
  argument "subset" is missing, with no default

**Comment by apredeus** [comment]
> Error in subset.default(pbmc_small, cells = cells.use argument "subset" is missing, with no default

you are running the `subset` command on the matrix object. You need to `CreateSeuratObject` first. 

(I just did the same thing and spend about 10 min trying to figure out what went wrong - maybe this will save someone some frustration).
