### ISSUE TITLE
How can I import both assay(integrated and RNA) to monocle and do further pseudotime trajectory.

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1694]
Hi,satijalab:
thank you for your work!
Monocle v2 has been deprecated and v3 has been finalized. I can use the intergrated data for constructing a pseudotime trajectory in monocle.But now we can only import one assay(integrated or RNA) to monocle and do further pseudotime trajectory.So we are really expecting your added support for the  v3 CellDataSet object.
For example,I have integrated data from mouse cells from different times,including E11,15,18,p5,p10,p30.And I want to do further linage tracing and pseudotime trajectory.My data was batch corrected,so it's not right for me to just use one assay to do analysis.Because if I import the integrated assay to monocle for clustering,monocle will automatically find markers for these cluster referring to integrated data matrix.[[And in fact, you said that for data integration these values should not be interpreted next, and  contain negative values as seurat are subtracting values from datasets to remove technical differences.] ](https://github.com/satijalab/seurat/issues/1057#issuecomment-454145423)
But if import the RNA assay to monocle for clustering,the data matrix was not batch corrected,it still not right to use it for do clustering and pseuodotime analysis.
I'm really confused and waiting for your reply.Thank you!
(https://github.com/satijalab/seurat/issues/1057#issuecomment-454145423)
![图片](https://user-images.githubusercontent.com/30619010/59547441-90819a80-8f71-11e9-82d5-aa022ea1188f.png)

**Comment by dwucsf** [comment]
Just to echo what @Sophia409 has stated: If it's simple to make a Monocle v3 CellDataSet contain two assays (i.e. be able to hold both integrated counts and original RNA counts) instead of being single-assay, that would be extremely helpful! Thank you!!

Or, if you have other suggestions on how to approach this problem, I am more than happy to hear your suggestions!

**Comment by mojaveazure** [comment]
Please see https://github.com/satijalab/seurat/issues/1658#issuecomment-502763190
