### ISSUE TITLE
Function CalcVarExpRatio and AlignSubspace

### ISSUE THREAD

**Issue by VVVVera** [satijalab/seurat#1696]
Hi,

I followed the pipeline in Seurat Alignment - Guided Tutorial, and when I try to do the CCA, I had a problem, it was fine when I use old version.
I updated the latest version of Seurat, but the two function, CalcVarExpRatio and AlignSubspace, are not exist anymore.
I also checked command cheat sheet, but there are no updates.
Are they changed to other functions?

**Comment by satijalab** [comment]
These functions were specific to the v2 workflow, and are not used in V3. You can see an example for how to integrate datasets using the V3 workflow at: https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html

**Comment by rojinsafavi** [comment]
Did you figure this out?
I'm new to Seurat, and as you mentioned the new version does not have those two functions. I was wondering what are the alternatives here?  which functions should I use to perform the same thing in V3?
