### ISSUE TITLE
Changing the order of clusters on x-axis for plots Seurat v3 (VlnPlot)?

### ISSUE THREAD

**Issue by Emmavb1988** [satijalab/seurat#1697]
I've been trying different ways (that were suggested here) to change the order of the clusters in my Seurat object so the graphs that I will plot, and VlnPlot in specific, will use this order. 
I've only found one suggestion for Seurat v3 that changes the names instead of re-ordering:

levels(myobject)
[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

levels(x = myobject) <- c("10", "3", "1", "4", "7", "11", "5", "8", "6", "9", "2", "12")
 
So this does not what I want to do. Any suggestions?

**Comment by mojaveazure** [comment]
Hi,

This was a bug in `levels<-` in previous versions of Seurat and should be fixed in v3.0.2; you should now be able to use `levels<-` to reorder identities of a `Seurat` object.
