### ISSUE TITLE
Integrating error

### ISSUE THREAD

**Issue by QqQss** [satijalab/seurat#1698]
Hi, satijalab,

I encountered an error recently when tried to integrate  a big data which contains 25 batches and near to 400k cells.

The commands I executed are:
```
anchors = FindIntegrationAnchors(object.list=seu.list, dims=1:50, anchor.features=gene.selected)
seu = IntegrateData(anchorset=anchors, dims=1:50)
```

The first command 'FindIntegrationAnchors' run normally. But the second returned me an error at a very late step:
```
...
...
Integrating data
Merging dataset 14 into 8 10 18 19 23 13 1 6 3 7 9 12 11 15 21 16 24 25 4 17 22 2 5
Extracting anchors for merged samples
Finding integration vectors
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive                                                                              
```
Why is this so？and how to fix it?

**Comment by QqQss** [comment]
I guess I found the reason. This problem was raised by the gene sets I used in 'FindIntegrationAnchors'.
Then, if I let the function selecting genes automatically, the issue was gone.

**Comment by liuyang0681** [comment]
I have encountered the same problem, how to solve it?

**Comment by QqQss** [comment]
@liuyang0681  sorry about the late reply. I just let the 'FindIntegrationAnchors' command select used genes automatically,  and then the issue was gone...
