### ISSUE TITLE
Problem running PCA

### ISSUE THREAD

**Issue by cartal** [satijalab/seurat#17]
Hi

I just installed the new version of Seurat via Bioconductor and I'm having some issues running the PCA function.

My command is:

deconv <- PCA(deconv, pc.genes = deconv@var.genes, do.print = TRUE, pcs.print = 5, genes.print = 5)

But after that I have an error:

Error in pca.obj$rotation[, 1:pcs.store] : subscript out of bounds

I have tried to find what the problem may be, but I can't identify the source of the error.

Previous steps didn't show errors, until this one. I don't think there is an issue with the format of the original data since it worked at first (although it may very well be the case). 

Looking forward to hearing from you

Regards

**Comment by andrewwbutler** [comment]
I think I found the problem. Essentially, there was a bug in how we were storing PC values when the number of cells was less than the value in pc.store. Reinstalling from the latest github version should resolve the issue.

**Comment by cartal** [comment]
Thanks! It works now.
