### ISSUE TITLE
Problem with BuildSNN

### ISSUE THREAD

**Issue by mashranga** [satijalab/seurat#170]
When use  plot.SNN = TRUE in BuildSNN, it give the following error . 

Error in BuildSNN(pbmc, plot.SNN = TRUE) : 
  trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots

I think there is no slot is available for that . 
or any idea ?

**Comment by andrewwbutler** [comment]
This would happen if you hadn't yet run a tSNE on the data yet. The develop branch has been updated to better check for this.
