### ISSUE TITLE
UMAP plots look different in immune alignment tutorial

### ISSUE THREAD

**Issue by shanmcdonell** [satijalab/seurat#1700]
I've been working through the Seurat 3.0 immune integration tutorial, and have come across something odd. Whenever I run the code in the tutorial, everything works, but I've been getting different UMAP plots than those in the tutorial, including one less cluster, attached below, with the image from the tutorial below that. Any ideas what might be causing this? 

My UMAP plots:
![Tutorial_UMAP](https://user-images.githubusercontent.com/51927455/59628092-cd829400-910d-11e9-91cf-42def318cc27.png)

Tutorial UMAP plots:
![from_tutorial](https://user-images.githubusercontent.com/51927455/59628213-19353d80-910e-11e9-8cf7-1625ce6f0e39.png)

**Comment by satijalab** [comment]
This is entirely normal and nothing to worry about. The exact contour of a UMAP plot will change on different runs, depending on a random seed which is set. We set this seed internally to try and minimize variation across runs, but you may observe slightly different results across platforms (as you do here)

**Comment by FireflyFrye** [comment]
I know it's been closed already but my UMAP looked exactly like yours for this tutorial. I also had to make ref=0.55 instead of 0.5 to get cluster 13 to appear.
