### ISSUE TITLE
Species mixture plots

### ISSUE THREAD

**Issue by kfontanez** [satijalab/seurat#1702]
Hello Seurat team,

I'm new to the platform so I apologize if my search of the man pages missed the obvious answer. I would like to recreate a species mixture plot (aka barnyard plot) similar to the attached picture. The color aren't strictly necessary but a nice feature. The idea is just to see the number of transcripts assigned to each species in a dot plot format.

![image](https://user-images.githubusercontent.com/5814641/59638165-a768ee00-9125-11e9-95c5-0446fa1820b7.png)

I know that other R packages, like DropBead, have functions for this but I wondered if Seurat had any capability of doing this as well. I was surprised that I didn't see a vignette about this as it's a common first step when evaluating single cell technologies against each other.

Thank you!

**Comment by satijalab** [comment]
We don't support this as a vignette, but you can easily generate these plots using the information in a Seurat object, by summing all genes associated with human, and all genes associated with mouse. Its not easy to generate a vignette as it depends on exactly which reference people align to and the associated gene names may not be the same (to my knowledge, Monocle and Scanpy also do not have functions for this).
