### ISSUE TITLE
loomR Error : Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by reginawongg** [satijalab/seurat#1703]
Hi, 

Thanks for building Seurat.

I am facing these errors while installing loomR 

> devtools::install_github(repo = "satijalab/seurat", ref = "loom")
> Downloading GitHub repo satijalab/seurat@loom
> Error: Could not find tools necessary to compile a package

> devtools::install_github(repo = "hhoeflin/hdf5r")
> Downloading GitHub repo hhoeflin/hdf5r@master
> Error: Could not find tools necessary to compile a package

I found the same error here --> #1004 
and I already have Rtools installed 

From my session info, hdf5r and loomR are already attached. 

Here is my sessionInfo()
![image](https://user-images.githubusercontent.com/44029432/59655825-34678200-91ce-11e9-9809-0bd8f85ed81f.png)

Please advise. 

Thanks!

**Comment by mojaveazure** [comment]
This might be an issue with [devtools](https://github.com/r-lib/devtools), I'd suggest bringing it up with them.

**Comment by satijalab** [comment]
check out this link here:
https://github.com/r-lib/devtools/issues/1879

It proposes a solution at the end. I hope this might work with you (unfortunately this is unrelated to Seurat)

**Comment by tanpuekai** [comment]
found a problem, but then found that ppl suggested installing RTools by following these steps:
`https://cran.r-project.org/bin/windows/Rtools/index.html`
and then it can proceed.
