### ISSUE TITLE
whether I can integrate tow RDS directly

### ISSUE THREAD

**Issue by Sylvia-Cheng** [satijalab/seurat#1704]
Hi,

I have two RDS normalized by your new method SCT, and now I want to integrate them. So I wonder whether I can combine them directly, or I should use the raw data (gene expression matrices).

And if I can integrate the two RDS directly, which steps should I start? And which assay should I choose in "FindIntegrationAnchors", "RNA" or "SCT"?

Best!

**Comment by satijalab** [comment]
1. You can certainly combine them together (using the 'merge' object). If you see the same cell states group together across objects, you can proceed with the standard Seurat workflow, and do not need to run integration analysis.


2. At the moment we only support integration of the RNA assay, but we are preparing to introduce new functionality enabling the direct integration of pearson residuals from the SCTransform procedure. I will close this issue for now, but please keep an eye on the website for updates.

**Comment by Sylvia-Cheng** [comment]
thanks for your reply! It's really helpful for me. And I'm looking for your new functionality : )






------------------ 原始邮件 ------------------
发件人: "satijalab"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 晚上11:13
收件人: "satijalab/seurat"<seurat@noreply.github.com>;
抄送: "欸乃"<1016256537@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [satijalab/seurat] whether I can integrate tow RDS directly(#1704)



 
 
You can certainly combine them together (using the 'merge' object). If you see the same cell states group together across objects, you can proceed with the standard Seurat workflow, and do not need to run integration analysis.
 
 
 
At the moment we only support integration of the RNA assay, but we are preparing to introduce new functionality enabling the direct integration of pearson residuals from the SCTransform procedure. I will close this issue for now, but please keep an eye on the website for updates.
