### ISSUE TITLE
How to interpret the output of FindConservedMarkers

### ISSUE THREAD

**Issue by KaiSakana** [satijalab/seurat#1705]
Dear all:
When i use FindConservedMarkers() to find conserved markers between the stimulated and control group (the same dataset on your website), I get logFCs of both groups. 
<img width="850" alt="屏幕快照 2019-06-18 下午3 40 47" src="https://user-images.githubusercontent.com/46432369/59663412-92519500-91e1-11e9-8108-19c417ba0dad.png">
So i'm confused of which gene should be considered as marker gene since the top genes are different. 
Thanks a lot!

**Comment by yuhanH** [comment]
Hi,
In your case, `FindConservedMarkers` is to find markers from stimulated and control groups respectively, and then combine both results.
You could use either of these two pvalue to determine marker genes:
`max_pval` which is largest p value of p value calculated by each group or `minimump_p_val` which is a combined p value.

**Comment by tmccra2** [comment]
Is the Average Log FC with respect the other clusters? As in how high or low is that gene expressed compared to all other clusters? All other cells? All other treatments in the integrated dataset?

**Comment by KaiSakana** [comment]
> Hi,
> In your case, `FindConservedMarkers` is to find markers from stimulated and control groups respectively, and then combine both results.
> You could use either of these two pvalue to determine marker genes:
> `max_pval` which is largest p value of p value calculated by each group or `minimump_p_val` which is a combined p value.

It's of great help, thanks a lot!!!

**Comment by KaiSakana** [comment]
Please have a look at https://scrnaseq-course.cog.sanger.ac.uk/website/seurat-chapter.html (9.12). This may give you the answer.




------------------ 原始邮件 ------------------
发件人: "tmccra2"<notifications@github.com>; 
发送时间: 2019年6月21日(星期五) 上午7:40
收件人: "satijalab/seurat"<seurat@noreply.github.com>; 
抄送: "鱼笨"<277237673@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [satijalab/seurat] How to interpret the output ofFindConservedMarkers (#1705)




Is the Average Log FC with respect the other clusters? As in how high or low is that gene expressed compared to all other clusters? All other cells? All other treatments in the integrated dataset?

**Comment by tmccra2** [comment]
Thanks for your response, that website describes "FindMarkers" and "FindAllMarkers" and I'm trying to understand FindConservedMarkers. 

FindMarkers identifies positive and negative markers of a single cluster compared to all other cells and  FindAllMarkers finds markers for every cluster compared to all remaining cells. FindConservedMarkers identifies marker genes conserved across conditions.

I'm trying to understand if FindConservedMarkers is like performing FindAllMarkers  for each dataset separately in the integrated analysis and then calculating their combined P-value. In this case it would show how that cluster relates to the other cells from its original dataset.
OR
Is FindConservedMarkers similar to performing FindAllMarkers on the integrated clusters, and you see which genes are highly expressed by that cluster related to all other cells in the combined dataset?

Thanks!

**Comment by yuhanH** [comment]
`FindConservedMarkers` is like performing `FindMarkers` for each dataset separately in the integrated analysis and then calculating their combined P-value.

I am sorry that I am quite sure what this mean:  how that cluster relates to the other cells from its original dataset.

**Comment by tmccra2** [comment]
I think you answered it!

Would you ever use FindMarkers on the integrated dataset?

**Comment by yuhanH** [comment]
You would better to use FindMarkers in the RNA assay, not integrated assay.
