### ISSUE TITLE
error in FindIntegrationAnchors

### ISSUE THREAD

**Issue by ChickenWangSY** [satijalab/seurat#1706]
Hi, satijalab  

when I run  `FindIntegrationAnchors`  in four  `seurat`  object ,  i got the error as following :

```
> pr.anchors <- FindIntegrationAnchors(object.list = list(pr1,pr2,pr3,pr4), dims = 1:30)
Computing 2000 integration features
Scaling features for provided objects
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 51s
Finding all pairwise anchors
   |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 1340 anchors
Filtering anchors
        Retained 1144 anchors
Extracting within-dataset neighbors
Error in SNNAnchor(k_matrix = k.matrix, anchor_only = anchor.only) :
  std::bad_alloc
```
and i run another job including 4 `seurat` objects successfully. the difference between them was cells number. successful job's cell number was much fewer  than unsuccessful jobs.

could you please give me some advice ?

regards

**Comment by timoast** [comment]
How many cells were in the runs that failed? And how much memory is available on your system?
