### ISSUE TITLE
DoHeatmap columns not in order

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#1707]
Hello! 

I'm using DoHeatmap to plot the top genes per cluster. The columns are not in the same order as the "active.ident" factor levels.  

Any help would be greatly appreciated!
Josepine

levels(scRNA_merged@active.ident)
 [1] "0"  "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14"
[16] "15" "16" "17" "18" "19" "20" "21" "22" "23" "24" "25"

top2 <- allMarkers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_diff)
pdf(file = paste0(wd,"top2genes_bycluster_heatmap", fileAdd, date_processed, ".pdf"), width = 20, height = 10)
DoHeatmap(object = scRNA_merged, group.by = "ident", features = top2$gene)
dev.off()

null device 
          1 
packageVersion("Seurat")
[1] ‘3.0.1.9010’

[top2genes_bycluster_heatmap_allSamples_20190618.pdf](https://github.com/satijalab/seurat/files/3301297/top2genes_bycluster_heatmap_allSamples_20190618.pdf)

**Comment by tmccra2** [comment]
This was also an issue with my heatmap, I updated the Seurat package to the release from a few days ago and the issue was fixed!

**Comment by jogiles** [comment]
This fixed the problem. Thank you!
