### ISSUE TITLE
Normalization and scale factor

### ISSUE THREAD

**Issue by medinih** [satijalab/seurat#1708]
Hi,

I have a question about the normalization scale factor. 
In NormalizeData() if I used scale.factor = 1000000, I get much more significant differentially expressed genes than in scale.factor = 10000. In scale.factor = 10000 I get none of the genes significant (only 5 passed, and none of them passed the FDR correction, compared to 3 out of 305 in scale.factor 1e6 passed the FDR). 
Is it acceptable scientific to use this resolution of scale.factor = 1000000?
I would like to know the explanation behind it. How can the size of this factor be determined according to my data?

Example of the size order of my data:

After normalization in scale.factor = 10000:
> obfbn@data[1:5,1:5]
5 x 5 sparse Matrix of class "dgCMatrix"
             3884      3886       3888      3889     3891
Gnai3 0.453600589 0.2726921 0.88210136 0.1973104 1.147343
Cdc45 .           .         .          .         .       
Scml2 .           .         .          .         .       
Apoh  .           .         .          .         .       
Narf  0.008530219 .         0.02829793 .         .       
>   

After normalization in scale.factor = 1000000:
> obfbn@data[1:5,1:5]
5 x 5 sparse Matrix of class "dgCMatrix"
           3884     3886     3888     3889     3891
Gnai3 4.0672632 3.476601 4.960023 3.127296 5.375192)
Cdc45 .         .        .        .        .       
Scml2 .         .        .        .        .       
Apoh  .         .        .        .        .       
Narf  0.6187848 .        1.353309 .        .      

Thank you,
Hadar.

**Comment by satijalab** [comment]
We typically do not use 1e6 (as is used in bulk) because of the substantially reduced number of molecules present in single cells.

I cannot say this is a solved problem for scRNA-seq, but we do have improved methods for normalization and pre-processing that do not require the calculation of size factors:
https://www.biorxiv.org/content/10.1101/576827v2

**Comment by medinih** [comment]
Thank you for your reply,
Can this approach (SCTransform) be applied also on **non**-UMI (read based counts)?

**Comment by MichaelPeibo** [comment]
Hi @medinih ,
I came to same issue, which is unexpected for me.
Have you find a proper way to deal with it? Or does SCTransform work well for your data?

It will be helpful if you can share some experience!
Thanks!

**Comment by medinih** [comment]
Hi,
SCTransform will not eliminate sequencing depth bias for my data because I have non-UMI data (as @yuhanH  wrote in another issue), thus I continued to use the regular way of normalization with the default scale.factor 10,000.  If you have UMI data I think SCTransform function can work well for you.
