### ISSUE TITLE
Import gene list to define cell types in cluster

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#1709]
Hello, 

I just wondering if I can import gene list to Seurat to define cell types? For example,from GenomicCytometry. Since the default cell markers are not sufficient  for our sample, and some of the subset of cell type (Subtype of B cells, etc) are not in the cell types library of Seurat, we want to import other genes to define cell type in Cluster. The gene list will be in CSV format. However, I couldn't see this on the tutorial. I just wondering how can I do this? Thank you!

**Comment by j-andrews7** [comment]
One way would be to use the `AddModuleScore` function based on the markers for each cell type of interest. This would yield a score for each that would allow you to assign cell type based on those scores. 

Not sure how well it'd actually work, but it'd be pretty easy to try it.

**Comment by timoast** [comment]
This was answered on bioinformatics stack exchange: https://bioinformatics.stackexchange.com/questions/8830/import-gene-list-to-seurat-to-define-cell-types
