### ISSUE TITLE
Log Transformation

### ISSUE THREAD

**Issue by sudhirthakurela** [satijalab/seurat#171]
Hi There,

I am importing TPM data into Seurat and hence didn't want to do any cell-level scaling. But I would like to supply logged TPMs to Seurat and then perform scaling (gene based).  I am using Seurat2. 
So, first I would like to know if internal log transformation of seurat is natural log or log2 or log10? Does it make sense to import TPMs in Seurat the way I plan to do and then use gene (row) scaling? 

Thanks and regards,
ST

**Comment by andrewwbutler** [comment]
1. The log transformation uses the natural log --- ln(x+1).
2. You can use TPMs with Seurat, just pass the TPM matrix into `CreateSeuratObject` as raw.data

**Comment by sudhirthakurela** [comment]
Hi,

Just had a follow up question on this. As TPM data is already normalized and results to colSum of 1M, do I still need to run Normalization step in Seurat or supplying log transformed values to CreareSeuratObject as raw data will be enough?

**Comment by andrewwbutler** [comment]
If you're supplying already normalized values to `CreateSeuratObject`, you should skip the normalization step. You will likely see a warning when you run ScaleData (which is checking whether you normalized using Seurat). You can ignore this or turn it off by setting `check.for.norm` to FALSE.

**Comment by brianpenghe** [comment]
> Hi,
> 
> Just had a follow up question on this. As TPM data is already normalized and results to colSum of 1M, do I still need to run Normalization step in Seurat or supplying log transformed values to CreareSeuratObject as raw data will be enough?

Shouldn't you log-transform the data?

**Comment by Diozao666** [comment]
> If you're supplying already normalized values to `CreateSeuratObject`, you should skip the normalization step. You will likely see a warning when you run ScaleData (which is checking whether you normalized using Seurat). You can ignore this or turn it off by setting `check.for.norm` to FALSE.

1. should I still skip it if I am subsetting a group of cells that are already normalized?
2. if I didn't skip it is it going to use the raw counts for this new normalization? (my Seurat object contains slots of both)
