### ISSUE TITLE
Adjusting contrast of blended FeaturePlot

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1711]
Hello!

Thank you for your excellent package and responsive support!

I have an integrated dataset in which I am trying to observe the co-expression of two markers. If I do a FeaturePlot on the RNA for each marker separately, you can see the expression is quite high.
![vitDcca_CDH1_RNA](https://user-images.githubusercontent.com/46829204/59701840-12650400-91bc-11e9-8107-f1ed83957bab.jpeg)
![vitDcca_KRT13_RNA](https://user-images.githubusercontent.com/46829204/59701848-16912180-91bc-11e9-8ed7-b5c9013cf56a.jpeg)

But when they are plotted together with blend, they appear to be very low. I am assuming this is because of the max/min cutoff, so I attempted to manually set that but had not luck. 
![CDH1_KRT13_RNA_blend](https://user-images.githubusercontent.com/46829204/59702002-64a62500-91bc-11e9-9adf-145f259993fd.jpeg)

If I do the blended FeaturePlot of the integrated assay, the issue is resolved, but I am trying only use the RNA assay as was recommended. 
![CDH1_KRT13_integrated_blend](https://user-images.githubusercontent.com/46829204/59702007-67087f00-91bc-11e9-81a7-4cad207a2ca4.jpeg)

Any tips?

**Comment by yuhanH** [comment]
i would suggest you try to adjust `blend.threshold`. When the signal is weak in the blend plot, you could decrease the value of `blend.threshold`. You could set `blend.threshold=0.2` to have a look.

**Comment by tmccra2** [comment]
Thanks for your response! 

Greatly reducing the blend threshold did help, but its hard to visualize two genes together that have such a difference in expression. 
![CDH1_KRT13_RNA_blend](https://user-images.githubusercontent.com/46829204/59703232-10e90b00-91bf-11e9-8258-1b9cf82976fc.jpeg)

Is it a bad idea to use the integrated assay in this case? If you report that you used that for the plot

**Comment by yuhanH** [comment]
It is not good to use integrated gene expression for the visualization, because those data is corrected according to the reference dataset in the integration and those value are not the real value.
You may add `DarkTheme()` but it will overlap the label now.
