### ISSUE TITLE
Bug in LogSeuratCommand, fails when name of object contains "Seurat"

### ISSUE THREAD

**Issue by raulmendez** [satijalab/seurat#1712]
Hi,
 
I am using Seurat 3.0.1 (which is the current stable version installed from CRAN) to process some scRNA-seq data from 10x Genomics, I have create an initial Seurat object:
 
Seurat.obj <- CreateSeuratObject(counts = data, project = project.name, min.cells = 3, min.features = 200)
 
That contained 7,645 cells and 21,882 features.
 
I have the subset them
Seurat.obj <- subset(Seurat.obj, subset = nFeature_RNA > min_RNA_feat & nFeature_RNA < max_RNA_feat & percent.mt < max_percent.mt)
According to:
 
min_RNA_feat <- 200
max_RNA_feat <- 6000
max_percent.mt <- 25
 
to 7,302 cells

Then I have normalized data:
 
> Seurat.obj <- NormalizeData(Seurat.obj, normalization.method = "LogNormalize", scale.factor = 10000)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
 
And then applied FindVariableFeatures to get 2,000 variable features
> Seurat.obj <- FindVariableFeatures(Seurat.obj, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
 

Now when I am trying to get the VariablePlot, I get the following error:
 
> plot1 <- VariableFeaturePlot(Seurat.obj)
Error: Please run either 'FindVariableFeatures' or 'SCTransform'
 
But I have already run ‘FindVariableFeatures’, and the corresponding vst data is there:

> head(Seurat.obj[["RNA"]]@meta.features[Seurat.obj[["RNA"]]@meta.features$vst.variable,])
           vst.mean vst.variance vst.variance.expected vst.variance.standardized vst.variable
HES4     0.57764996   2.39357245             1.0672659                  2.242714         TRUE
ISG15    0.51821419   6.30777668             0.9199350                  6.743350         TRUE
TNFRSF18 0.25527253   0.68321764             0.3697306                  1.847880         TRUE
TNFRSF4  0.19474117   1.15314040             0.2721618                  4.236966         TRUE
MXRA8    0.09052314   0.22533409             0.1183763                  1.903541         TRUE
VWA1     0.01574911   0.03851375             0.0188703                  2.040971         TRUE

> dim(Seurat.obj[["RNA"]]@meta.features[Seurat.obj[["RNA"]]@meta.features$vst.variable,])
[1] 2000    5

Previously I had created the Variable Plot without any problem, with the same data, but sub setting it with more stringent cutoffs:
 
subset(BreasTumor, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5),
 
which yielded 1,285 cells (and same number of features 21,882).
 
Do you know what’s going on?
 
Thanks,

Raul

**Comment by raulmendez** [comment]
I have found what the problem was: the name of my Seurat object was "Seurat.obj" and it cannot have the word Seurat on it, and perhaps ".", the reason being (I am not sure) LogSeuratCommand in ./R/objects.R library (highlighted lines):

LogSeuratCommand <- function(object, return.command = FALSE) {
  time.stamp <- Sys.time()
  #capture function name
  which.frame <- sys.nframe() - 1
  if (which.frame < 1) {
    stop("'LogSeuratCommand' cannot be called at the top level", call. = FALSE)
  }
  command.name <- as.character(x = deparse(expr = sys.calls()[[which.frame]]))
  **command.name <- gsub(pattern = ".Seurat", replacement = "", x = command.name)**
  call.string <- command.name
  command.name <- ExtractField(string = command.name, field = 1, delim = "\\(")
  #capture function arguments
  argnames <- names(x = formals(fun = sys.function(which = sys.parent(n = 1))))
  argnames <- grep(pattern = "object", x = argnames, invert = TRUE, value = TRUE)
  argnames <- grep(pattern = "anchorset", x = argnames, invert = TRUE, value = TRUE)
  argnames <- grep(pattern = "\\.\\.\\.", x = argnames, invert = TRUE, value = TRUE)
  params <- list()
  p.env <- parent.frame(n = 1)
  argnames <- intersect(x = argnames, y = ls(name = p.env))
  # fill in params list
  for (arg in argnames) {
    param_value <- get(x = arg, envir = p.env)
    #TODO Institute some check of object size?
    params[[arg]] <- param_value
  }
  # check if function works on the Assay and/or the DimReduc Level
  assay <- params[["assay"]]
  reduction <- params[["reduction"]]
  if (class(x = reduction) == 'DimReduc') {
    reduction = 'DimReduc'
  }
  # rename function name to include Assay/DimReduc info
  if (length(x = assay) == 1) {
    command.name <- paste(command.name, assay, reduction, sep = '.')
  }
  **command.name <- sub(pattern = "[\\.]+$", replacement = "", x = command.name, perl = TRUE)**
  command.name <- sub(pattern = "\\.\\.", replacement = "\\.", x = command.name, perl = TRUE)
  # store results
  seurat.command <- new(
    Class = 'SeuratCommand',
    name = command.name,
    params = params,
    time.stamp = time.stamp,
    call.string = call.string
  )
  if (return.command) {
    return(seurat.command)
  }
  object[[command.name]] <- seurat.command
  return(object)
}

So you'd better change those regular expressions to be more general or alternatively, warn people in your tutorial not use "Seurat" in the object name  name and/or "."

Raul

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
