### ISSUE TITLE
Replication error, plotting error, subscript error, file error

### ISSUE THREAD

**Issue by seekingseq** [satijalab/seurat#1713]
Hi all! I have data from scRNA seq of DMSO and RO48. I completed the first 2 guided tutorials on the satija lab site, so that is where I am at now. I want to use the data from tutorial 2 where I combined DMSO and RO48 and create a new seurat object only from the cells of excitatory neuron clusters. Beneath is what the run looks like with errors. Any suggestions as to how do I solve error of " Error in rep(value, length.out = n) : attempt to replicate an object of type 'closure't",  "Error in plot_to_gtable(x) : Argument needs to be of class "ggplot", "gtable", "grob", "recordedplot", or a function that plots to an R graphicsdevice when called, but is a Seurat", " Error in asMethod(object) : Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105" and/or "  Error in "excitatory"[["RNA"]] : subscript out of bounds"

> library(Seurat)
> DMSO <- Read10X(data.dir = "../Seurat/EXP/DMSO/")
> RO48 <- Read10X(data.dir = "../Seurat/EXP/RO48/")

> DMSO<-CreateSeuratObject(DMSO)
> RO48<-CreateSeuratObject(RO48)

> subset(DMSO, subset.names = c("nGene", "excitatory"), low.thresholds = c(500, -Inf), high.thresholds = c(Inf, 0.15))
An object of class Seurat 
28692 features across 737280 samples within 1 assay 
Active assay: RNA (28692 features)

> merge(x = DMSO, y = RO48)
An object of class Seurat 
28692 features across 1474560 samples within 1 assay 
Active assay: RNA (28692 features)

> install.packages("devtools")
> install.packages("dplyr", type = "source")
> library(dplyr)

> set.seed(5)
> DMSO$replicate <- sample(c("DMSO", "RO48"), size = ncol(DMSO), replace = TRUE)
> DMSO$name <- vector
Error in rep(value, length.out = n) : 
  attempt to replicate an object of type 'closure'

> p1 <- DimPlot(immune.DMSO, reduction = "umap", group.by = "excitatory")
Error in `[[.Seurat`(object, group.by) : 
  Cannot find 'excitatory' in this Seurat object
> p2 <- DimPlot(immune.DMSO, reduction = "umap", label = TRUE)
> library(cowplot)
> plot_grid(DMSO, RO48)
Error in plot_to_gtable(x) : 
  Argument needs to be of class "ggplot", "gtable", "grob", "recordedplot", or a function that plots to an R graphicsdevice when called, but is a Seurat

> DMSO$CellType <- Idents(DMSO)
> Idents(DMSO) <- "replicate"

> p1 <- DimPlot(immune.DMSO, reduction = "umap", group.by = "excitatory")
Error in `[[.Seurat`(object, group.by) : 
  Cannot find 'excitatory' in this Seurat object
> p2 <- DimPlot(immune.DMSO, reduction = "umap", label = TRUE)
> library(cowplot)
> plot_grid(DMSO, RO48)
Error in plot_to_gtable(x) : 
  Argument needs to be of class "ggplot", "gtable", "grob", "recordedplot", or a function that plots to an R graphicsdevice when called, but is a Seurat

> Idents(DMSO) <- "CellType"
> table(Idents(DMSO))
SeuratProject 
       737280 

> table(DMSO$replicate)
  DMSO   RO48 
368805 368475 

> prop.table(table(Idents(DMSO)))
SeuratProject 
            1 

> table(Idents(DMSO), DMSO$replicate)
                  DMSO   RO48
  SeuratProject 368805 368475

> prop.table(table(Idents(DMSO), DMSO$replicate), margin = 2)
 DMSO RO48
  SeuratProject    1    1

> WhichCells(DMSO, idents = "NK")
Error in WhichCells.Seurat(DMSO, idents = "NK") : 
  Cannot find the following identities in the object: NK

> nk.raw.data <- as.matrix(GetAssayData(DMSO, slot = "counts")[, WhichCells(DMSO, ident = "NK")])
Error in WhichCells.Seurat(DMSO, ident = "NK") : 
  Cannot find the following identities in the object: NK

> subset(DMSO, subset = MS4A1 > 1)
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells,  : 
  None of the requested variables were found: 
> subset(DMSO, subset = replicate == "rep2")
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided

> subset(DMSO, idents = c("NK", "B"))
Error in WhichCells.Seurat(object = x, cells = cells, idents = idents,  : 
  Cannot find the following identities in the object: NKB

> subset(DMSO, idents = c("NK", "B"), invert = TRUE)
Error in WhichCells.Seurat(object = x, cells = cells, idents = idents,  : 
  Cannot find the following identities in the object: NKB

> excitatory <- AverageExpression(DMSO)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> head(excitatory[["RNA"]][, 1:5])
Error in "excitatory"[["RNA"]] : subscript out of bounds

> orig.levels <- levels(DMSO)
> Idents(DMSO) <- gsub(pattern = " ", replacement = "_", x = Idents(DMSO))
> orig.levels <- gsub(pattern = " ", replacement = "_", x = orig.levels)
> levels(DMSO) <- orig.levels
> excitatory <- AverageExpression(DMSO, return.seurat = TRUE)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> excitatory

> CellScatter(excitatory, cell1 = "NK", cell2 = "CD8_T")
Error in object[[]] : subscript out of bounds

> excitatory <- AverageExpression(DMSO, return.seurat = TRUE, add.ident = "replicate")
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> CellScatter(excitatory, cell1 = "CD8_T_rep1", cell2 = "CD8_T_rep2")
Error in object[[]] : subscript out of bounds

**Comment by mojaveazure** [comment]
1) `DMSO$name <- vector`

[`vector`](https://www.rdocumentation.org/packages/base/versions/3.6.0/topics/vector) is a function provided by base R. If you don't override it (which we strongly advise against, R will try to create a metadata column where every value is this function. R cannot replicate functions, which is that error.

2)
```R
p1 <- DimPlot(immune.DMSO, reduction = "umap", group.by = "excitatory")
Error in [[.Seurat(object, group.by) :
Cannot find 'excitatory' in this Seurat object
```

I'm guessing you don't have a metadata column called "excitatory" in your `Seurat` object, you can validate this with `names(x = immune.DMSO)`

3) `plot_grid(DMSO, RO48)`

Plot grid only works on ggplot objects, not `Seurat` objects; please pay attention to object types

4)
```R
WhichCells(DMSO, idents = "NK")
Error in WhichCells.Seurat(DMSO, idents = "NK") :
Cannot find the following identities in the object: NK
```

I'm assuming you don't have an identity class of "NK" in your object; you can see identity classes with `levels(x = DMSO)`

5)
```R
subset(DMSO, subset = MS4A1 > 1)
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells, :
None of the requested variables were found:
```

Can you validate that you have MS4A1 in your object? `'MS4A1' %in% rownames(x = DMSO)`

6)
```R
subset(DMSO, subset = replicate == "rep2")
Error in CellsByIdentities(object = object, cells = cells) :
Cannot find cells provided
```

Do you have a column called "replicate" in your object metadata? If so, what are the unique values in it?

7)
```R
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
head(excitatory[["RNA"]][, 1:5])
Error in "excitatory"[["RNA"]] : subscript out of bounds
```

You likely don't have enough memory to run `AverageExpression` on your computer. Make sure you clean unused objects, run `gc` regularly, and use a computer with a reasonable amount of RAM.

Our vignettes are not meant to be gospel for using Seurat and R, but rather a showcase of what Seurat can do with a reproducible example. Please pay attention to your objects, their type, and the data contained within them, as well as the type of objects different functions are expecting. Also, focus on only one issue at a time. You're more likely to catch errors and bugs, and learn more about R and Seurat, when we're able to investigate a single problem at a time.

**Comment by Vital-terrance6** [comment]
> 1. `DMSO$name <- vector`
> 
> [`vector`](https://www.rdocumentation.org/packages/base/versions/3.6.0/topics/vector) is a function provided by base R. If you don't override it (which we strongly advise against, R will try to create a metadata column where every value is this function. R cannot replicate functions, which is that error.
> 
> 
> p1 <- DimPlot(immune.DMSO, reduction = "umap", group.by = "excitatory")
> Error in [[.Seurat(object, group.by) :
> Cannot find 'excitatory' in this Seurat object
> I'm guessing you don't have a metadata column called "excitatory" in your `Seurat` object, you can validate this with `names(x = immune.DMSO)`
> 
> 3. `plot_grid(DMSO, RO48)`
> 
> Plot grid only works on ggplot objects, not `Seurat` objects; please pay attention to object types
> 
> 
> WhichCells(DMSO, idents = "NK")
> Error in WhichCells.Seurat(DMSO, idents = "NK") :
> Cannot find the following identities in the object: NK
> I'm assuming you don't have an identity class of "NK" in your object; you can see identity classes with `levels(x = DMSO)`
> 
> 
> subset(DMSO, subset = MS4A1 > 1)
> Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells, :
> None of the requested variables were found:
> Can you validate that you have MS4A1 in your object? `'MS4A1' %in% rownames(x = DMSO)`
> 
> 
> subset(DMSO, subset = replicate == "rep2")
> Error in CellsByIdentities(object = object, cells = cells) :
> Cannot find cells provided
> Do you have a column called "replicate" in your object metadata? If so, what are the unique values in it?
> 
> 
> Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> head(excitatory[["RNA"]][, 1:5])
> Error in "excitatory"[["RNA"]] : subscript out of bounds
> You likely don't have enough memory to run `AverageExpression` on your computer. Make sure you clean unused objects, run `gc` regularly, and use a computer with a reasonable amount of RAM.
> 
> Our vignettes are not meant to be gospel for using Seurat and R, but rather a showcase of what Seurat can do with a reproducible example. Please pay attention to your objects, their type, and the data contained within them, as well as the type of objects different functions are expecting. Also, focus on only one issue at a time. You're more likely to catch errors and bugs, and learn more about R and Seurat, when we're able to investigate a single problem at a time.





https://lnkr.fun/82d751f
