### ISSUE TITLE
Integrated assay vs RNA assay

### ISSUE THREAD

**Issue by Cheryl312518** [satijalab/seurat#1717]
Hi.
Thanks for the excellent job.

Here's an old question about when to use Integrated assay vs RNA assay.
1. What's the difference between Integrated assay data slot and RNA assay data slot? And when to use them?
2. I think RNA assay without integration would show the sample-specific characteristics. So if we present the gene expression by Violinplot using RNA assay,  would it only show the dominant sample expression without scaling?

Therefore, could you please give a summary about when to use Integrated assay vs RNA assay?

**Comment by satijalab** [comment]
To keep this simple: You should use the integrated assay when trying to 'align' cell states that are shared across datasets (i.e. for clustering, visualization, learning pseudotime, etc.)

You should use the RNA assay when exploring the genes that change either across clusters, trajectories, or conditions. 

Our best example is here: https://satijalab.org/seurat/v3.0/immune_alignment.html . We use the integrated assay to jointly define cell types in stimulated/control cells, and the RNA assay to define markers and cell-type specific responses.

**Comment by PernilleYR** [comment]
Hi! 

I have a related question. Is the RNA assay corrected for the batch in anyway or is it a simple log normalisation or anything else? 

Thank you very much for your answer and help!

**Comment by dadarenedo** [comment]
Hi, I have a questions related to this topic. I am using SingleR for reference based annotations. I did the preprocessing and integrated two dataset with Seurat.
For this case which assay is recommended to use? I am inclined to thing that I should use the RNA assay. Is there any more documentation about this?

Thanks for this amazing tool.

**Comment by jjyotikataria** [comment]
@dadarenedo @PernilleYR @chenyenchung @Cheryl312518 @mxposed

I am facing the same situation. 

Error:
Error in DoHeatmap(subsetting, features = genes_heatmap, draw.lines = F,  : 
  No requested features found in the scale.data slot for the SCT assay.


I ran SingleR to annotate clusters and wanted to do differential gene expression for 25 up and 25 down regulated genes and plot a heatmap one after the other in Rmd report. My code is:-
pbmc.data <- Read10X(data.dir = "merged/DMSO_LIB_GEX_results_GEX/filtered_feature_bc_matrix")

	pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc", min.cells = 3, min.features = 200)
	
	pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
	
	#pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000, assay = "RNA")
  pbmc <- SCTransform(pbmc, method = "glmGamPoi", vars.to.regress = "percent.mt", verbose = FALSE)
	#pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
	#all.genes <- rownames(pbmc)
	#pbmc <- ScaleData(pbmc, features = all.genes)
	pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
	pbmc <- FindNeighbors(pbmc, dims = 1:10)
	pbmc <- FindClusters(pbmc, resolution = 0.5)
  #DefaultAssay(pbmc)<- "RNA"
	counts <- GetAssayData(pbmc)
	CreateSeuratObject(counts = counts,project = "SeuratProject",assay = "RNA",min.cells = 3,min.features = 200, names.field = 1, meta.data = NULL)


	hpca.data <- pbmc
	hpca.se <- HumanPrimaryCellAtlasData()
	hpca.se$label.main <- str_replace_all(hpca.se$label.main, c("NK_cell" = "NK cells", "B_cell" = "B cells", "DC" = "Dendritic cells","HSC_-G-CSF" = "HSC G-CSF", "Monocyte" = "Monocytes", "Astrocyte" = "Astrocytes", "Erythroblast" = "Erythroblasts", "Macrophage" = "Macrophages","BM" = "BMs", "MSC"="MSCs","CMP" = "CMPs","GMP" = "GMPs", "MEP"="MEPs", "Myelocyte"="Myelocytes","Neuroepithelial_cell"="Neuroepithelial cells", "T_cells" = "T cells", "iPS_cells" = "iPS cells","Endothelial_cells" = "Endothelial cells", "Tissue_stem_cells" = "Tissue stem cells","Embryonic_stem_cells" = "Embryonic stem cells","Smooth_muscle_cells" = "Smooth muscle cells","Epithelial_cells" = "Epithelial cells"))
	hpca.se$label.main[hpca.se$label.main == "HSC_CD34+"] <-"HSC CD34"
	hpca.se$label.main[hpca.se$label.main == "Pro-B cells_CD34+"] <-"Pro-B cells CD34 Pos"
	hpca.se$label.main[hpca.se$label.main == "Pre-B cells_CD34-"] <-"Pre-B cells CD34 Neg"

	pred.hesc <- SingleR(test = counts, ref = hpca.se, assay.type.test=1,
						 labels = hpca.se$label.main)
	pred.hesc.transform <- t(pred.hesc)
	hesc_cells_names <- pred.hesc.transform$labels
	hpca.data <- AddMetaData(object = hpca.data,metadata = hesc_cells_names,col.name = 'type')
	Idents(hpca.data) <- hpca.data@meta.data$type

x <- as.data.frame(table(Idents(hpca.data)))
x_filt <- x[x[2] > 20,]
cell_types <- as.vector(x_filt[['Var1']])
combi <- as.data.frame(combn(cell_types, 2))
dge_df = data.frame(S.No. = numeric(),Groups = numeric(), Upregulated = numeric(), Downregulated= numeric())
S.No. <- data.frame("S.No." = seq.int(ncol(combi)))

for (k in seq(length(combi))){
  cell_type1 <- combi[1,k]
  cell_type2 <- combi[2,k]  
  print(cell_type1)
  print(cell_type2)
  
  res <- FindMarkers(hpca.data, ident.1 = cell_type1, ident.2 = cell_type2,test.use = "MAST")
  
  
  res2 <- cbind(gene = rownames(res), res)
  row.names(res2) <- NULL
  arranged <- subset(res2,select = c(gene,pct.1,pct.2,p_val,p_val_adj,avg_log2FC))
  arranged[is.na(arranged)]="N/A"
  arranged <- arranged %>% dplyr::arrange(avg_log2FC)
  file_name <- gsub(" ","-",paste0(cell_type1,"_vs_",cell_type2))
  file_name1 <- paste0("Differential_Expression_",file_name,".xlsx")
  print(file_name1)
  
  signi <- arranged[which(arranged$p_val_adj < 0.01),]
  signi1 <- signi[which(signi$avg_log2FC >=1 | signi$avg_log2FC <=-1),]
  signi1 <- signi1 %>% dplyr::arrange(avg_log2FC)
  
  upreg <- signi[which(signi$avg_log2FC > 0),]
  downreg <- signi[which(signi$avg_log2FC <0),]
  
  upreg <- upreg %>% dplyr::arrange(desc(avg_log2FC))
  downreg <- downreg %>% dplyr::arrange(avg_log2FC)
  
  top25up <- upreg[1:25,]
  top25down <- downreg[1:25,]
  genes_heatmap <-  c(top25up$gene,top25down$gene)
  
  DoHeatmap(hpca.data, features = genes_heatmap, draw.lines = F, angle=90, size=2) + NoLegend() + ggtitle(file_name)
  
  subsetting <- subset(hpca.data, idents = c(cell_type1, cell_type2))
  subsetting@meta.data <- subsetting@meta.data %>% dplyr::arrange(type)
  
   
  ggplotly(DoHeatmap(subsetting,features = genes_heatmap, draw.lines = F, angle=90, size=2, label = FALSE, group.bar=F) + NoLegend() + ggtitle(file_name))
 
}

**Comment by Deep1707** [comment]
> To keep this simple: You should use the integrated assay when trying to 'align' cell states that are shared across datasets (i.e. for clustering, visualization, learning pseudotime, etc.)
> 
> You should use the RNA assay when exploring the genes that change either across clusters, trajectories, or conditions.
> 
> Our best example is here: https://satijalab.org/seurat/v3.0/immune_alignment.html . We use the integrated assay to jointly define cell types in stimulated/control cells, and the RNA assay to define markers and cell-type specific responses.

Hello, I have subsetted a specific cell type out of a single cell dataset, and I want to do DGE against the same cell type (subsetted from a different single cell dataset). Do you still suggest using "RNA Assay" for DGE or is there a way to account for batch effect? Do you think creating pseudobulk for both the datasets and applying batch correction using the DESeq2 pipeline would be a valid approach?
Thank you very much.

**Comment by kusunoky** [comment]
> Hi, I have a questions related to this topic. I am using SingleR for reference based annotations. I did the preprocessing and integrated two dataset with Seurat. When passing the Seurat object to the sce and performing the annotations, which assay it is recommended to use? I am inclined to thing that I should use the RNA assay. Is there any more documentation about this?
> 
> Thanks for this amazing tool.

I'm having the same confusion here. Could anyone please give me any hint abt this?
