### ISSUE TITLE
How is the color scaling created in FeaturePlot?

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#1718]
Hello!

I am using ggplot with a dataframe (not Seurat object). I would like to recreate the color scaling generated by FeaturePlot. It does a beautiful job making a visually useful scale with the scaled RNA counts. I dug around in the source code a bit and can't figure it out.

Any help would be greatly appreciated!
Josephine

**Comment by mojaveazure** [comment]
Hi Josephine,

`FeaturePlot` uses ggplot2's [`scale_color_gradientn`](https://www.rdocumentation.org/packages/ggplot2/versions/3.2.0/topics/scale_colour_gradient) with the colors "lightgrey" and "blue"

**Comment by jogiles** [comment]
Hello,

Thank you for your quick response. It's not the colors I would like to change, but the scaling.

Thank you!
Josephine

**Comment by mojaveazure** [comment]
Hi Josephine,

All of the scaling is done within ggplot2; `scale_color_gradientn` figures out how to apply the colors based on the distribution of the data. We allow some customization by applying cutoffs (`min.cutoff` and `max.cutoff` arguments), but we don't do any of the scaling calculations ourselves.

**Comment by samuel-marsh** [comment]
@mojaveazure related question.
Simply using `FeaturePlot() + scale_color_gradientn` works well for applying custom color scales but I'm wondering if there is a way to color cells with zero expression a specific color and then apply the color scale to the remaining cells?  I've tried `FeaturePlot() + scale_color_gradientn(colors = custom_palette, na.value = "lightgray")` but that doesn't change the result.

Thanks!!
Sam

**Comment by Leran10** [comment]
Hi,

I have the same problem of coloring the cells with zero expression to a specific color. Is there a solution for this?

Thank you so much!!
Leran

**Comment by plijnzaad** [comment]
> I've tried `FeaturePlot() + scale_color_gradientn(colors = custom_palette, na.value = "lightgray")` but that doesn't change the result.

This worked fine for me (although I believe ligthgrey is the default color for `NA` so it may have worked but still looked the same as a result).
