### ISSUE TITLE
Standard Error or Deviation in AverageExpression

### ISSUE THREAD

**Issue by sinjia7** [satijalab/seurat#1719]
Hello Satijalab,

I have been using your Seurat package for a while now and stumbled upon your AverageExpression() function which worked great. However, I would like to know if you guys have a built in function to find the standard deviation/error of the averages I get for each gene per cell cluster. Thank you!

**Comment by satijalab** [comment]
We do not support this at the moment. Its an interesting idea, and we would be happy to accept a PR if you would be interested in contributing.

**Comment by Dragonmasterx87** [comment]
This is a interesting function, can someone create a PR for this? @satijalab   thoughts?

**Comment by Dragonmasterx87** [comment]
@timoast can you create a function for this when you have the time? Sorry for the bother. (for SD and SEM) This is an interesting metric, because it doesn't rely on cluster-cluster relationships rather cell to cell within a cluster.

**Comment by Nidane** [comment]
i manage to do this but with several lines of codes - as i am pretty newbie anyway lol - and not sure it's correct ? 
first 
obj <- FetchData(object = X, vars = "gene_name")
then 
sd(obj$gene_name)
?
