### ISSUE TITLE
Converting data from natural log to log2 scale for plots

### ISSUE THREAD

**Issue by CMC-LI** [satijalab/seurat#1723]
Hi there, 

I was wondering if there is a way to convert the data slot of a SeuratV3 object (i.e. object@data, which contains the normalized and natural log-transformed single cell expression) from natural log to log2 scale? In some context, the log2 scale is easier for visualizing gene expression in VlnPlot.  

I thought I might be able to convert an object in natural log to log2 by the following: 
object --> exp(object) --> log2(exp(object))

I tried the following but didn't work:

1) What I tried: 
seurat_log2 = SetAssayData(object = seurat, slot = "data", new.data = log2(exp(GetAssayData(object = seurat, slot = "data"))))

The problem I got: 
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “dgeMatrix” is not valid for slot ‘data’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE

2) What I also tried: 
seurat_log2 = SetAssayData(object = seurat[["RNA"]], slot = "data", assay = "RNA", new.data = log2(exp(GetAssayData(object = seurat[["RNA"]], slot = "data", assay = "RNA"))))

The problem I got: 
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “dgeMatrix” is not valid for slot ‘data’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE

3) What I also tried: 
seurat_log2 = SetAssayData(object = seurat[["RNA"]], slot = "data", new.data = log2(exp(GetAssayData(object = seurat))), assay = "RNA")
 
The problem I got:
Warning: The new data doesn't have the same number of features as the current data
Error: Attempting to add a different number of cells and/or features

I am new to this. Any pointer will be much appreciated! Thank you!

**Comment by CMC-LI** [comment]
I think I found a solution. Since "data" is a dgeMatrix, converting it to matrix allows it to be added to the seurat object.

seurat_log2 = SetAssayData(object = seurat, slot = "data", new.data = log2(exp(as.matrix(GetAssayData(object = seurat, slot = "data")))))

Thanks!

**Comment by yuhanH** [comment]
Right. When you change `data` from sparse matrix to matrix, you can do operation on it.
