### ISSUE TITLE
Error in FindMarkers  for "negbinom" test ... The following cell names provided to cells.1 are not present

### ISSUE THREAD

**Issue by elo073** [satijalab/seurat#1725]
Hi!

The FindMarkers function doesn't seem to recognise identities when using negbinom test. No issues with default testing.

> ident2=levels(srat@active.ident)[3]
> ident1=levels(srat@active.ident)[2]
> tmp.de=FindMarkers(srat, ident.1 = ident1, ident.2 = ident2, max.cells.per.ident=700, test.use="negbinom", latent.vars="Donor")
Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
  The following cell names provided to cells.1 are not present: 
> 
> cells1=WhichCells(srat, idents = ident1)
> cells2=WhichCells(srat, idents = ident2)
> tmp.de=FindMarkers(srat, cells.1 = cells1, cells.2 = cells2, max.cells.per.ident=700, test.use="negbinom", latent.vars="Donor")
Error in FindMarkers.Seurat(srat, cells.1 = cells1, cells.2 = cells2,  : 
  Please provide ident.1
> tmp.de=FindMarkers(srat, ident.1 = cells1, ident.2 = cells2, max.cells.per.ident=700, test.use="negbinom", latent.vars="Donor")
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: AAACCTGCACCGCTAG-1-HCATisStab7463846AAACCTGCATTTCACT-1-HCATisStab7463846AAACGGGGTGTGTGCC-1-HCATisStab7463846AACCATGCATACCATG-1-HCATisStab7463846AACTCAGAGTTATCGC-1-HCATisStab7463846AACTGGTCAAGTTAAG-1-HCATisStab7463846AAGGCAGGTCCGTGAC-1-HCATisSt....

> tmp.de=FindMarkers(srat, ident.1 = cells1, ident.2 = cells2, max.cells.per.ident=700)    \|++++++++++++++++++++++++++++++++++++++++++++++++++\| 100% elapsed = 02s
--

**Comment by timoast** [comment]
Hi, I was not able to reproduce this issue. Are you using the latest version from the develop branch?

Could you provide a reproducible example using the `pbmc_small` dataset, or one of the datasets used in the Seurat vignettes, and post the output of `sessionInfo()`? If you can't reproduce the issue with any of those datasets, can you share the `srat` object so that I can try to reproduce the error?

**Comment by estevezb** [comment]
Having same issue. 
# findings markers for individual 42POS samples
> Runx1_integration_positive1= SetIdent(Runx1_integration_positive, value="orig.ident")
> levels(Runx1_integration_positive1)
[1] "cor42_pos_dmso"   "fpd_42_pos_83567" "fpd_42_pos_83568"
> Marker_genes_42POS= FindMarkers(Runx1_integration_positive1, ident.1= "cor42_pos_dmso", ident.2 = "fpd_42_pos_83567",test.use="negbinom")
Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
  The following cell names provided to cells.1 are not present:
