### ISSUE TITLE
Trouble creating object v3

### ISSUE THREAD

**Issue by elevenson** [satijalab/seurat#1727]
HI,

I am comfortable with v2 but in trying v3.0.2 to process the new features.tsv in cell ranger for 10X data. I am getting this error when trying to make the Seurat Object:

> A549RSV1 <- CreateSeuratObject(counts = A549INF1.data)
Error in if (any(rownames(x = counts) == "")) { : 
  missing value where TRUE/FALSE needed

Please help.

**Comment by timoast** [comment]
Hi, what is `A549INF1.data`?

```r
class(A549INF1.data)
head(rownames(A549INF1.data))
head(colnames(A549INF1.data))
```

**Comment by elevenson** [comment]
This is how I made A549INF1.data

> library(Seurat)
> A549INF1.data <- Read10X(data.dir = "~/Documents/Eric Sync/Single Cell/Pippa/A549_INF1/filtered_feature_bc_matrix/")

This is from the output of cellranger v3.

Thank you

**Comment by timoast** [comment]
Can you run those lines I posted above?

**Comment by elevenson** [comment]
Thanks

> class(A549INF1.data)
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
> head(rownames(A549INF1.data))
[1] "MIR1302-2HG" "FAM138A"     "OR4F5"       "AL627309.1"  "AL627309.3"  "AL627309.2" 
> head(colnames(A549INF1.data))
[1] "AAACCTGAGCTGATAA" "AAACCTGCAAGCCTAT" "AAACCTGCAGGACCCT" "AAACCTGCAGGTCTCG" "AAACCTGTCATCATTC" "AAACCTGTCGTAGGTT"
>

**Comment by timoast** [comment]
Thanks, it looks like this could be a bug. Do you mind sharing the 10x output that causes this error, so that I can debug (~/Documents/Eric Sync/Single Cell/Pippa/A549_INF1/filtered_feature_bc_matrix/)?

**Comment by elevenson** [comment]
No problem.  You want the matrix files in the folder above? I can archive and send. How can I get them to you?

**Comment by timoast** [comment]
Yes that would be great, if it's small enough to email you can email to tstuart@nygenome.org, or you could send me a dropbox/google drive link (or whatever works for you)

**Comment by timoast** [comment]
This was due to the presence of NA values in the count matrix rownames. I have pushed a fix for `Read10X` to the develop branch that will check if any gene names are NA, and if so try to fill it in with the other column of the annotation (eg, the ensembl ID if using gene names or vice versa). Fixed as of a981bf97828169bc97ee54d0d1ba95c00c3a6696

**Comment by Ariunaa5000** [comment]
Hi @timoast. I am running into a same problem. I converted Ensembl IDs to Gene symbol. And I checked if I have any NAs in my rownames. I got 0 NAs. I was wondering what else could cause this error?

**Comment by Ariunaa5000** [comment]
Hello @timoast 

I am running into a same problem. I checked to make sure I have no NAs in the rowname of the file i am trying to convert to Seurat object. Do you have any idea why I might be seeing this error?
