### ISSUE TITLE
Error in RunCCA

### ISSUE THREAD

**Issue by DivyanshAgarwal** [satijalab/seurat#173]
Hi, 
I believe this question was mentioned previously too #158 , but I'm also getting an error with RunCCA, even though my union set is not empty and neither are there problems with upper/lower case naming of genes between the two data sets. Here is my code:

D2600.data <- Read10X("d2600/outs/filtered_gene_bc_matrices/mm10")
D5500.data <- Read10X("d5500/outs/filtered_gene_bc_matrices/mm10")
D2600 <- CreateSeuratObject(D2600.data, project = "D2600", min.cells = 3, min.genes = 200, is.expr=0, normalization.method = "LogNormalize", scale.factor = 10000)
D5500 <- CreateSeuratObject(D5500.data, project = "D5500", min.cells = 3, min.genes = 200, is.expr=0, normalization.method = "LogNormalize", scale.factor = 10000)

D2600 <- FindVariableGenes(object = D2600, mean.function = ExpMean, dispersion.function = LogVMR,x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
D5500 <- FindVariableGenes(object = D5500, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)

hvg.d2600 <- rownames(x = head(x = D2600@hvg.info, n = 500))
hvg.d5500 <- rownames(x = head(x = D5500@hvg.info, n = 500))

hvg.union1 <- union(x = hvg.d2600, y = hvg.d5500)
#length(hvg.union1) is 1200

D2600@meta.data[, "protocol"] <- "D2600"
D5500@meta.data[, "protocol"] <- "D5500"

merge1 <- RunCCA(object = D2600, object2 = D5500, genes.use = hvg.union1)
#gives the error:

Error in RunCCA(object = D2600, object2 = D5500, genes.use = hvg.union1) : 
  0 valid genes in genes.use

Any suggestion on what I may be missing here?

**Comment by andrewwbutler** [comment]
Have you run `ScaleData()`? `RunCCA()` along with our other supported dimensional reduction techniques all are performed on scaled data.

**Comment by DivyanshAgarwal** [comment]
Thank you! ScaleData() addressed the problem.
