### ISSUE TITLE
GetAssayData(): slot=count vs assay=RNA 

### ISSUE THREAD

**Issue by dwucsf** [satijalab/seurat#1730]
In the GetAssayData() function, what is the difference between having slot="counts" vs assay="RNA"? Don't both provide the original RNA counts of your sequencing data?

**Comment by timoast** [comment]
They are not the same. By default, `GetAssayData` will pull from the `data` slot, so if you set `slot="counts"` you would get the counts from the default assay (which may not be RNA, could be protein or anything else). If you set `assay="RNA"` it will retrieve the normalized data from the RNA assay.

**Comment by dwucsf** [comment]
Makes sense. Thank you for the explanation!
