### ISSUE TITLE
how to get historical version seurat 3 alpha?

### ISSUE THREAD

**Issue by htc502** [satijalab/seurat#1731]
Hi guys,

I want to know how I can get back to seurat 3 alpha? I want to repeat my old results which was done with this version of seurat.
Thank you in advance

**Comment by mojaveazure** [comment]
You can clone the git repository for Seurat, checkout the commit you want (we unfortunately don't have tags for the alphas or a list of which commit corresponds to which alpha build), and install with either [`R CMD`](http://kbroman.org/pkg_primer/pages/build.html) or [`devtools::install`](https://www.rdocumentation.org/packages/devtools/versions/2.0.2/topics/install)
