### ISSUE TITLE
RunALRA and SCTransform integration

### ISSUE THREAD

**Issue by CasiratiG** [satijalab/seurat#1732]
I would like to integrate ALRA in my Seurat3 pipeline (which is now using SCTransform for data Normalization/Scaling). The problem is that the "alra" assay does not have a counts slot, therefore SCTransform cannot run on imputed data. Using the "RNA" counts would bypass ALRA imputation, so it would be pointless. 

Is there a way to integrate ALRA and SCTranform in the pipeline, without having to resort to NormalizeData and ScaleData (which is, by the way, extremely slow)? Would the imputation>normalize/scale/var.genes>pca>UMAP etc.. sequence make sense?

I would like to run the following:
Subset/Filtering (based on percent.mito, nCount_RNA, nFeature_RNA)
CellCycleScoring
RunALRA on "RNA" assay
SCTransform on "alra" assay 
RunPCA on "SCTransform"
RunTSNE and RunUMAP on "pca"
FindNeighbors and FindCluster on "pca"

Thanks!

**Comment by satijalab** [comment]
Thanks for the question. SCTransform normalization should be run on sequencing counts from the original quantifications, and should not be run after ALRA. Running ALRA first would violate the  original input assumptions of SCTransform

**Comment by lkqnaruto** [comment]
@satijalab If ALRA is required for me, then I assume it would find to follow the standard Seurat analysis work flow without using SCTransform, right? For example: LogNormolizeData -> RunALRA->FindVaraibleFeatures->SelectIntegrationFeatures->FindIntegrationAnchors->IntegrateData->ScaleData->RunPCA->RunUMAP, etc.
