### ISSUE TITLE
control vs stim post integrating datasets

### ISSUE THREAD

**Issue by talban14** [satijalab/seurat#1733]
I have 16 datasets that I integrated together following the stimulated vs. control PBMC  walkthrough.  Before I integrated everything I assigned the stim metadata with a control group and stimulated group and it works great for later comparisons, however I was wondering if there is a way to do this downstream of the integration step based on orig.ident of the samples? 

For example I originally used a stim vs control category but now I want to create a male vs female category based on the original sample identity without going back to the begining and assigning these groups before inetgration.  It seems that addmetadata should be able to accomplish this but I'm just not sure how. Thank you for the help!

**Comment by andrewwbutler** [comment]
Yes, you could do this downstream (assuming you know the mapping between `orig.ident` and male vs female). Something like:

```R
object$sex <- "MALE"
object$sex[object$orig.ident %in% c(FEMALE_SAMPLES)] <- "FEMALE"
```
