### ISSUE TITLE
Integrating tumor vs normal data, with sctransform

### ISSUE THREAD

**Issue by NienkeMekkes** [satijalab/seurat#1734]
Dear Sir, Madam,

Thank you for this awesome tool. Currently I have two matrices (10x data), one normal and one tumor. I want to integrate them as explained in https://satijalab.org/seurat/v3.0/immune_alignment.html, but with using the new sctransform normalised tool. 

`normal <- CreateSeuratObject(counts = normal_data, project='CRC_normal', min.cells = 3)`
`normal$type <- "normal"`
`normal <- SCTransform(normal, verbose = T)`

`tumor <- CreateSeuratObject(counts = tumor_data, project='CRC_tumor', min.cells = 3)`
`tumor$type <- 'tumor'`
`tumor <- SCTransform(tumor, verbose = T)`

`tumor.anchors <- FindIntegrationAnchors(object.list = list(normal, tumor), dims = 1:30,scale = F)`
`crc.combined <- IntegrateData(anchorset = tumor.anchors, dims = 1:30)`
`DefaultAssay(crc.combined) <- "integrated"`
`crc.combined <- ScaleData(crc.combined, verbose = FALSE)`
Visualisation/clustering etc. 
`crc.combined <- RunPCA(crc.combined, npcs = 30, verbose = FALSE)`

Now, everything works, but I was wondering:

1. Am I correct by not using FindVariableFeatures()?
2. Am I correct that the use of subset() in the example is not strictly necessary? What is the aim of this subset()?
3. I use `scale=F` in FindIntegrationAnchors(), would this be advised when using sctransform?
4.. I am not sure whether to use ScaleData or not. In the sctransform vignette, it is explained that scaling is not longer necessary, but my script does not work without ScaleData(). Is it necessary since we merge the two sets? 

Thank you

**Comment by satijalab** [comment]
Apologies for the delay. We are going to release a vignette describing how to use V3 integration alongside SCTransform in the very near future (keep an eye on the website). I'm going to close this issue for now, but if you still have questions after we release the vignette, please feel free to re-open.

**Comment by vincr04** [comment]
Hi, I am still unclear about the 3rd question from @NienkeMekkes . The vignette doesn't mention the `scale` option, which probably indicates that it is okay to leave the default `scale=TRUE`. But I am not sure why this is the case, as SCTransform is meant to be an alternative to `NormalizeData`, `FindVariableFeatures` AND `ScaleData`. Is scaling the data in `FindIntegrationAnchors` really necessary?
Thanks,
Vinnie
