### ISSUE TITLE
Identify differential expressed genes across conditions

### ISSUE THREAD

**Issue by Ryo-1234** [satijalab/seurat#1736]
_Seurat Tutorial name: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses._

Using the Seurat tutorial, I'm training about single-cell RNA analysis. I have one question about the data plot.
In this tutorial, they are plotting a dataset that comparison of CTRL vs STIM of the CD4Naive T cell content. Also, I want to plot a dataset that comparison of CD4 Naive T_CTRL(A) vs NK_STIM(B) that are part of the split Identity, not CTRL vs STIM.
How do I rewrite the tutorial code when comparing A and B that are part of the split Identity?

the tutorial code
```
t.cells <- subset(immune.combined, idents = "CD4 Naive T")
Idents(t.cells) <- "stim"
avg.t.cells <- log1p(AverageExpression(t.cells, verbose = FALSE)$RNA)
avg.t.cells$gene <- rownames(avg.t.cells)
genes.to.label = c("ISG15", "LY6E", "IFI6", "ISG20", "MX1", "IFIT2", "IFIT1", "CXCL10", "CCL8")
p1 <- ggplot(avg.t.cells, aes(CTRL, STIM)) + geom_point() + ggtitle("CD4 Naive T Cells")
p1 <- LabelPoints(plot = p1, points = genes.to.label, repel = TRUE)
plot_grid(p1)

```

<img width="990" alt="スクリーンショット 2019-06-24 23 38 43" src="https://user-images.githubusercontent.com/51925343/60053884-4cad3480-96d9-11e9-9f48-88e3055a0a6b.png">

<img width="450" alt="スクリーンショット 2019-06-24 23 01 51" src="https://user-images.githubusercontent.com/51925343/60051788-14572780-96d4-11e9-9a03-65d3dc02424f.png">

**Comment by andrewwbutler** [comment]
If you want to select cells like that (e.g. CD4 Naive T_CTRL and NK_STIM), one way to do that would be:

```R
immune.combined$celltype_stim <- paste0(immune.combined$celltype, "_", immune.combined$stim)
t_nk <- subset(immune.combined, subset = celltype_stim %in% c("CD4 Naive T_CTRL", "NK_STIM"))
```

You should then be able to make scatter plots like the one shown above.

**Comment by Ryo-1234** [comment]
Great! Thanks, It does work.


I have one more question about how to change the color of specified dots.

I want to change the specified dot labeled by genes.to.label1 to blue and
by genes.to.label2 to red.

I tried the following code, but I could not change the color. Can you tell
me if you know?


Thanks.



immune.combined$celltype_stim <- paste0(immune.combined$celltype, "_",
immune.combined$stim)

t_nk<- subset(immune.combined, subset = celltype_stim %in% c("CD4 Naive
T_CTRL", "NK_STIM"))

avg.t_nk <- log1p(AverageExpression(t_nk, verbose = FALSE)$RNA)

avg.t_nk$gene <- rownames(avg.t_nk)

genes.to.label_1 = c( "IAPP")

genes.to.label_2 = c("REG1A", "REG1B", "CTRB2", "PRSS1")

p1 <- ggplot(avg.t_nk, aes(CD4 Naive T_CTRL, NK_STIM)) + geom_point(size=1,
label_1="Scatter plot")

#p1 <- ggplot(avg.t_nk, aes(CD4 Naive T_CTRL, NK_STIM)) + geom_point( colour
= "black", size=1)

# + geom_point(genes.to.label_1, colour = "red", size = 1) +
geom_point(genes.to.label_2, colour = "blue", size = 1)

p1 <- LabelPoints(plot = p1, points = genes.to.label, repel = TRUE, xnudge
= 0, ynudge = 0)

plot_grid(p1)

2019年6月28日(金) 15:13 Andrew Butler <notifications@github.com>:
