### ISSUE TITLE
FeaturePlot fails with cells argument

### ISSUE THREAD

**Issue by alexvpickering** [satijalab/seurat#1737]
The error is `arguments imply differing number of rows: 84, 173`.

Ran this after data integration (but don't think it is specific to):
```
Seurat::FeaturePlot(scseq, gene, cells = cells, reduction = 'umap')
```
This issue appears to be in `FetchData` where the idents are not being subsetted according to cells:

```R
# Pull identities
  if ('ident' %in% vars && !'ident' %in% colnames(x = object[[]])) {
    data.fetched[['ident']] <- Idents(object = object)
  }
```

This seems to fix it: 

```R
# Pull identities
  if ('ident' %in% vars && !'ident' %in% colnames(x = object[[]])) {
    data.fetched[['ident']] <- Idents(object = object)[cells]
  }
```

Shouldn't introduce any new bugs because `cells` is either all or a subset of column names:

```R
cells <- cells %||% colnames(x = object)
```

I'll submit a PR.

**Comment by mojaveazure** [comment]
Fixed in #1738
