### ISSUE TITLE
What's the best cutoff for the Filtercells and FindVariableGenes?

### ISSUE THREAD

**Issue by lilycanfly** [satijalab/seurat#174]
I have an sample which have ~7,000 cells. When I plot the nGene, nUMI and percent.mito. The percent.mito seems extremely low. In this case what should be the percent.mito cutoff for the FilterCells?

![image](https://user-images.githubusercontent.com/32545217/31505219-65158fd4-af42-11e7-9ccc-1523ea68956b.png)

After I run the FindVariablegenes
pbmc <- FindVariableGenes(object = pbmc, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 4.5, y.cutoff = 0.2)
It will have 1766 genes left. What should be the good cutoff and good number of genes in my data?

![image](https://user-images.githubusercontent.com/32545217/31506386-42baa124-af45-11e7-895c-f7f8f44f64d2.png)

Thank you so much.

**Comment by andrewwbutler** [comment]
For future reference, Github issues should be used to report bugs in the source code or requested enhancements/features. 

1. It's likely that you have 0 percent.mito. VlnPlot adds a small amount of random noise by default and can be a little misleading when there is no variance in the data. This will be fixed an upcoming release. 
2. We generally find that 1-2k variable genes works well in most analyses but this can vary some depending on the underlying data. Based on the information above, you've probably got a good set of genes to go ahead with for downstream analyses.
