### ISSUE TITLE
Rare_cell genes not included in the integrated object, causing issue in visualization 

### ISSUE THREAD

**Issue by yuwenjiesail** [satijalab/seurat#1741]
Dear Satija group,

I really appreciate that you develop and share such a great scRNAseq analysis R tool kit. It enables the person like me without any coding background to process scRNAseq data by myself.
**Issue:**
I have one issue regarding multiple groups of sample integration and visualization. I am trying to do feature plot about some high expressed genes in rare cell types. Since these rare cells and their marker genes are not detectable in one group of the samples, they are not included in the "integrated_gene list". As a result, I cannot plot them out with defaultassay setting as "integrated"
If I change the defaultassay to "RNA", I have the plot, but it is the original RNA reads various a lot without any normalization and scaling, which only highlights the cells with the extremely high expression level.
If I change the defaultassay to "SCT", I can find all cells with the gene expression, but they are not highlighted with strong color.

**My question:**
1) Does seurat has a way to include these genes in the integrated_gene list, so we can use the "integrated" defaultassay to plot the marker genes for rare cell types?
2) Are the any ways to use "logRNA" or "SCT" to generate great feature plots for downstream analysis?

**Please find my code below:**
`# Seurat 3.0
library(Seurat)
library(sctransform)

# Load four groups of merged samples 
Merged.A <- readRDS(file = "~/Documents/scRNAseq/merged_sample_condition_A.rds")
Merged.B <- readRDS(file = "~/Documents/scRNAseq/merged_sample_condition_B.rds")
Merged.C <- readRDS(file = "~/Documents/scRNAseq/merged_sample_condition__C.rds")
Merged.D <- readRDS(file = "~/Documents/scRNAseq/merged_sample_condition__D.rds")

Merged.A$Genotype <- "WT"
Merged.A$Tissue <- "Large"
Merged.A <- SCTransform(Merged.A, return.only.var.genes = FALSE, verbose = FALSE)

Merged.B$Genotype <- "KO"
Merged.B$Sample <- "Large"
Merged.B <- SCTransform(Merged.B, return.only.var.genes = FALSE, verbose = FALSE)

Merged.C$Genotype <- "WT"
Merged.C$Tissue <- "Small"
Merged.C <- SCTransform(Merged.C, return.only.var.genes = FALSE, verbose = FALSE)

Merged.D$Genotype <- "KO"
Merged.D$Sample <- "Small"
Merged.D <- SCTransform(Merged.D, return.only.var.genes = FALSE, verbose = FALSE)

# Perform integration
ABCD.anchors <- FindIntegrationAnchors(object.list = list(Merged.A, Merged.B, Merged.C, Merged.D), dims = 1:50)
to_integrate <- Reduce(intersect, lapply(ABCD.anchors@object.list, rownames))
ABCD.combined <- IntegrateData(anchorset = ABCD.anchors, features.to.integrate = to_integrate, dims = 1:50)

# Perform an integrated analysis
DefaultAssay(object = ABCD.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
ABCD.combined <- ScaleData(object = ABCD.combined, vars.to.regress = "percent.mt", features =to_integrate, verbose = T)
ABCD.combined <- RunPCA(object = ABCD.combined, npcs = 50, verbose = FALSE)
# UMAP and Clustering
ABCD.combined <- RunUMAP(object = ABCD.combined, reduction = "pca", dims = 1:50)
ABCD.combined <- FindNeighbors(object = ABCD.combined, reduction = "pca", dims = 1:50)
ABCD.combined <- FindClusters(ABCD.combined, resolution = 0.5)
# Visualization
DimPlot(ABCD.combined, label = TRUE) + NoLegend()
# Plots
FeaturePlot(object = ABCD.combined, features = c("ACTA2", "CD7"), min.cutoff = "q9")

## The following requested variables were not found: ACTA2, CD7

DefaultAssay(object = ABCD.combined) <- "RNA" 
### Have the featurePlots, but it is the original reads of the RNA, which has very big various!!!
# or
DefaultAssay(object = ABCD.combined) <- "SCT"
### Have the plot, but the heatmap of cells with targeted_gene expression is not strong
`
Thank you very much for your help

Wenjie

**Comment by timoast** [comment]
You can define the set of genes to be used for integration with the `anchor.features` argument in `FindIntegrationAnchors`.

You can also change the default assay using `DefaultAssay`, and normalize the uncorrected data using `NormalizeData` or `SCTransform`.

If there are expression outliers in the `FeaturePlot` this can sometimes make it hard to visualize the full range of expression. You can set the `min.cutoff` and `max.cutoff` values in `FeaturePlot` to change the minimum and maximum values displayed. You can set this to a quantile by using for example “q5” for the lower 5%
