### ISSUE TITLE
FeaturePlot() does not use reduction parameter properly

### ISSUE THREAD

**Issue by MaxKman** [satijalab/seurat#1742]
Hi,

thanks so much for developing Seurat! 

I am using Seurat 3.0.3 on a Mac with R 3.5.1 (the problem I describe seems to also occur in Seurat 3.0).

I noticed that when I calculate multiple UMAPs (e.g. for different assays) FeaturePlot does not use the reduction I define with
`FeaturePlot(object, reduction = "my_UMAP")`

Instead it defaults to the UMAP I ran for the RNA assay. The same problem does not occur with DimPlot(). I glimpsed at the function definition of FeaturePlot. It seems that only the Key ("UMAP_") is passed on to FetchData not the whole name of the reduction. Here are the corrresponding lines of code:
 
`dims <- paste0(Key(object = object[[reduction]]), dims)`

```
data <- FetchData(object = object, vars = c(dims, "ident", 
    features), cells = cells, slot = slot)
```

Can this be fixed easily or is there a work around? I am currently a bit stuck with my work...

Thanks!
Max

**Comment by mojaveazure** [comment]
Prematurely closed

**Comment by satijalab** [comment]
Make sure that when you define a new UMAP in the RunUMAP function, you also set the reduction.key parameter (and make sure it is not UMAP_). This avoids the possibility that two dimensional reductions have the same key, which creates uncertainty and problems downstream.

For example:

```
test = RunUMAP(test, assay = 'ADT',  dims = 1:30, reduction.name = 'adtumap', reduction.key='adtumap_')
```

Actually, we specifically have error checking in place to make sure this doesn't happen, but either that failed in your case, or you explicitly tried to set the key to be UMAP_.

best,
Rahul

**Comment by MaxKman** [comment]
Hey Rahul,

thanks for the quick answer, in my case I set reduction.name = 'int_UMAP' and didn't set reduction.key. I'll try your solution!

Best,
Max
