### ISSUE TITLE
How to define new cell type base on  over expression in one gene and low expression in another gene

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#1743]
Hello, 

I want to recluster  a cell type, for example, I got a general cluster of NK cells, now I want to recluster this NK cells and see the subtype of the NK cells. If a cell is over express in one particular gene while low express in another particular gene, it will be define as a new type of NK cells, I want to mark all those cells within the NK cluster, any way I can do this? Thank you !

**Comment by andrewwbutler** [comment]
Hi,

You can use  the`WhichCells` function to perform these sorts of manual thresholding selections. For example:

```R
pbmc_small$subtypes <- pbmc_small$celltypes
pbmc_small$subtypes[WhichCells(object, idents = "NK", expression = GENE1 > XXX & GENE2 < YYY)] <- "subtype1"
```
