### ISSUE TITLE
Error install previous version v2.3.4

### ISSUE THREAD

**Issue by yulongliu68** [satijalab/seurat#1745]
**I uninstalled v3 of Seurat and tried to install v2.3.4 with:** 

`install.packages('devtools')`

`devtools::install_version(package = 'Seurat', version = package_version('2.3.4'))`

**But I received the following error:**

Trying https://cran.rstudio.com/
Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/Seurat/Seurat_2.3.4.tar.gz
These packages have more recent versions available.
Which would you like to update?

1:   All
2:   CRAN packages only
3:   None
4:   rlang (0.3.4 -> 0.4.0) [CRAN]
5:   xfun  (0.7   -> 0.8  ) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 
Installing 5 packages: doSNOW, hdf5r, knitr, snow, yaml
Installing packages into ‘C:/Users/Yulong/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/doSNOW_1.0.16.tar.gz'
Content type 'application/x-gzip' length 8004 bytes
downloaded 8004 bytes

trying URL 'https://cran.rstudio.com/src/contrib/hdf5r_1.2.0.tar.gz'
Content type 'application/x-gzip' length 2001040 bytes (1.9 MB)
downloaded 1.9 MB

trying URL 'https://cran.rstudio.com/src/contrib/knitr_1.23.tar.gz'
Content type 'application/x-gzip' length 880134 bytes (859 KB)
downloaded 859 KB

trying URL 'https://cran.rstudio.com/src/contrib/snow_0.4-3.tar.gz'
Content type 'application/x-gzip' length 22675 bytes (22 KB)
downloaded 22 KB

trying URL 'https://cran.rstudio.com/src/contrib/yaml_2.2.0.tar.gz'
Content type 'application/x-gzip' length 89447 bytes (87 KB)
downloaded 87 KB

* installing *source* package 'hdf5r' ...
** package 'hdf5r' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
cp 1_8_14/*.c 1_8_14/*.h .
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG       -I/include/hdf5 -I/include/hdf5_hl -I/include/cmakeconf -I1_8_14 -I. -D__USE_MINGW_ANSI_STDIO   -O3 -Wall  -std=gnu99 -mtune=generic -c const_export.c -o const_export.o
In file included from const_export.h:22:0,
                 from const_export.c:23:
global.h:23:18: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
                  ^
compilation terminated.
make: *** [const_export.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB="hdf5r.dll" ' had status 2
ERROR: compilation failed for package 'hdf5r'
* removing 'C:/Users/Yulong/Documents/R/win-library/3.4/hdf5r'
In R CMD INSTALL
Error: (converted from warning) running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\Yulong\Documents\R\win-library\3.4" C:\Users\Yulong\AppData\Local\Temp\RtmpIPldwc/downloaded_packages/hdf5r_1.2.0.tar.gz' had status 1
In addition: Warning message:
In is.na(remote_deps$package) :
  is.na() applied to non-(list or vector) of type 'NULL'

`sessionInfo()`
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        ps_1.3.0          prettyunits_1.0.2 rprojroot_1.3-2   digest_0.6.19     crayon_1.3.4      withr_2.1.2      
 [8] assertthat_0.2.1  R6_2.4.0          backports_1.1.4   magrittr_1.5      rlang_0.3.4       cli_1.1.0         fs_1.3.1         
[15] remotes_2.0.4     callr_3.2.0       desc_1.2.0        devtools_2.0.2    tools_3.4.3       glue_1.3.1        pkgload_1.0.2    
[22] compiler_3.4.3    processx_3.3.1    pkgbuild_1.0.3    sessioninfo_1.1.1 memoise_1.1.0     usethis_1.5.0    

**If I try to install v2.3.4 with:**
`install.packages('Seurat', repo = c('satijalab.org/ran/', getOption("repos")))`
**v3 will be installed instead of v2.3.4**

**Comment by yulongliu68** [comment]
Solved by a clean installation of R3.6

**Comment by MichaelStber** [comment]
Dear @yulongliu68 

I have the same problem and ended up in an installed seurat v3.

What do you actually mean with "clean installation of R3.6" ??

**Comment by yulongliu68** [comment]
It worked for me when I  removed R3.6 and all its associated packages, and then reinstall R3.6 again. 

You should try their new binary installation.
source("http://bit.ly/archived-seurat")
