### ISSUE TITLE
Using Seurat 3 Data for Pseudotime Analysis in Monocle 3

### ISSUE THREAD

**Issue by hkarakurt8742** [satijalab/seurat#1746]
Hello,
I have 2 scRNA-Seq data set for 2 conditions. There is not any batch effect. Tissues, platforms, date of experiments are completely identical. Only difference is condition so if I do a batch correction, I would lose the information I need so I analyzed each data set seperately. I processed, clustered and identified cell types.

Now I want to to trajectory analysis of a specific cell type in both of the condition. To do that, I used subset function to create cell type specific Seurat object and merged them. 
After that, should I use counts data and start the analysis with Monocle 3 from the beginning  or should I create CDS object with normalized data and directly order cells?

Thank you in advance.

**Comment by saeedfc** [comment]
Monocle 2 used to advice raw counts. This maybe an issue to be asked to Monocle.

**Comment by timoast** [comment]
Unfortunately we can’t give much advice about how to run Monocle, please raise an issue with the authors about whether monocle can run with pre-normalized data
