### ISSUE TITLE
subsetting cells to find sub clusters - bringing cluster info back to parent popultaion

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#1748]

**Comment by annecar** [comment]
Hi 
I have been subsetting a cluster from a Seurat object to find subclusters. After defining such subclusters, i would like to bring back the clusterinfo of the new subclusters to the parent Seurat object, in order to find (sub)-clustermarkers specific for the new subclusters in relation to all cells (and clusters) of the parent object. Is that possible? 
Thanks 
annecar

**Comment by yuhanH** [comment]
Sure. You could generate a new column in your meta.data showing your subclusters info, and use cell name to add the subcluster information.
For example:
```
# Subset pbmc_small cluster1 and sub-cluster
pbmc_small.c1 <- subset(pbmc_small, idents = 1)
pbmc_small.c1 <- FindNeighbors(pbmc_small.c1, dims = 1:10, k.param = 5)
pbmc_small.c1 <- FindClusters(pbmc_small.c1)

# Generate a new column called sub_cluster in the metadata
pbmc_small$sub_cluster <- as.character(Idents(pbmc_small))

# Change the information of cells containing sub-cluster information
pbmc_small$sub_cluster[Cells(pbmc_small.c1)] <- paste("c1",Idents(pbmc_small.c1))
DimPlot(pbmc_small, group.by = "sub_cluster")
```

**Comment by annecar** [comment]
Thanks, i will try! 
Anne 




Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by annecar** [comment]
Hi, Thanks again for the code; one more thing: i wanted to run it in Seurat 2.3.4. But there is no “Cell” functions. 

so the line 
> pbmc_small$sub_cluster[Cells(pbmc_small.c1)] <- paste("c1",Idents(pbmc_small.c1))

does not work. 
How can  i do it in the older version? 
And also, what does the “c1” stand for? 

Thanks again for your help! 

Best 
Anne 




CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by yuhanH** [comment]
c1 means that those clusters are sub-clusters from original cluster1.   You could change it to any words.
You use `WhichCells(pbmc_small, idents = 1)` or ` rownames(pbmc_small.c1@meta.data)` to get cells names from `pbmc_small.c1`

**Comment by annecar** [comment]
It doe snot seem to work. 
I subset “CG_cDC”  from “data”, then i try to create a new metadata slot: 

data@meta.data$DC_subclusters[WhichCells(CG_cDC)] <- paste("c1",CG_cDC@meta.data$celltypes)

and get the error: 


Error in `$<-.data.frame`(`*tmp*`, DC_subclusters, value = c("cDC", "cDC",  : 
  replacement has 7146 rows, data has 3573


what is wrong? 




CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by yuhanH** [comment]
Right. You need to generate a column with value first, and then replace the value of your target cells. 
Like the line I use here: `pbmc_small$sub_cluster <- as.character(Idents(pbmc_small))`

**Comment by annecar** [comment]
but again “Idents” does not work in 2.3
therefore i tried to build it with “paste0”

What can i take for 2.3? 


CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by yuhanH** [comment]
Maybe you could try `object@active.ident` or you could find the Idents information in the column of your metadata, which may be called something like RNA_snn_res.1

One question. Why don't you update your seurat to the latest version?

**Comment by annecar** [comment]
This doesn’t work either… 

To answer your question: i am using Seurat 2 on a project that i started almost 2 years ago; everything was analysed with the old version, and i just need to do one more further thing, and therefore did not want to re-run the whole analysis with Seurat 3. Particularly, as i have used CCA alignment for batch effect correction, and as i am not sure whether i can transpose this into Seurat3. 
Of course, for the next upcoming projects i will use the latest version. But as far aas i understood, the idea was to maintain older versions for cases exactly like mine. 


But thanks for your help anyway. 




Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by yuhanH** [comment]
OK. Could you try `object@ident` ? 
It at least should work at seurat 2.4. If still not work, I will reopen your issue

**Comment by annecar** [comment]
no, didn’ t work. 
i made a subcluster “small_data” from data which i clustered, and then

data@meta.data$DC_subclusters <- paste0(data@meta.data$celltypes)
data@meta.data$DC_subclusters[small_data@ident] <- paste("c1”,small@meta.data$Clusters)

the object data was then transformed into the object small_data… 





Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by yuhanH** [comment]
`object@ident` just tells you the cluster information about your cells. The second line of your code is not correct. 
You could change it into this

`data@meta.data$DC_subclusters[rownames(small_data@meta.data)] <- paste("c1”, small_data@meta.data$Clusters)`

One thing to confirm. You put the sub-cluster information into `small_data@meta.data$Clusters` right?

**Comment by annecar** [comment]
this still does nt work, teh same error again: 

Error in `$<-.data.frame`(`*tmp*`, DC_subclusters, value = c("cDC", "cDC",  : 
  replacement has 12895 rows, data has 9322



Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by yuhanH** [comment]
Have a more try. Thanks.
`data@meta.data[rownames(small_data@meta.data), "DC_subclusters"] <- paste("c1”, small_data@meta.data$Clusters)`

**Comment by annecar** [comment]
thanks to you and your patience… 
but nope, still not ok… 




CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by satijalab** [comment]
unfortunately this is more of an R issue than a Seurat issue. As Yuhan mentioned, all you need to do is create a column in the object meta data matrix that stores this information. It involves a small amount of matrix manipulation in R, but unfortunately its outside the scope of the support we can provide to list exact commands.
