### ISSUE TITLE
AddMetaData - data in any order, as long as rownames match cellnames?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#175]
Hi Seurat Team,

I need this quick clarification about AddMetaData.  As long as the rownames of my meta data match cell names, but are in any random order, would this still work?  

Thanks!

**Comment by andrewwbutler** [comment]
Yes, that should still work. If you want to check, you could always reorder them first and compare:

`new.metadata <- new.metadata[rownames(object@meta.data),  ]`

**Comment by mojaveazure** [comment]
AddMetaData orders your metadata based off the rownames in `object@meta.data`.

```R
# Abbreviated snippets of AddMetaData
cols.add <- colnames(x = metadata)
meta.add <- metadata[rownames(x = object@meta.data), cols.add]
object@meta.data[, cols.add] <- meta.add
```
