### ISSUE TITLE
K means clustering in Seurat

### ISSUE THREAD

**Issue by SaraAli83** [satijalab/seurat#1751]
Hi,

I'm new to Seurat and would be grateful for some advice regarding K means clustering as the default clustering method in Seurat fails to reveal a rare cell population which I can see very clearly in the loupe browser using the K means clustering method. I have the latest version of Seurat which doesn't seem to have the DoKMeans function which is mentioned in another thread.
I tried to apply the following which is the method given in the package but it doesn't seem to work:
kmeans(x, centers, iter.max = 10, nstart = 1,
algorithm = c("Hartigan-Wong", "Lloyd", "Forgy",
"MacQueen"), trace=FALSE)

Many thanks.

Sara

**Comment by timoast** [comment]
Hi, we don’t support k-means clustering in Seurat but you can always extract the PCA embeddings using the `Embeddings` function, and then run any methods you like. One other thing you might like to try is to change some of the parameters in `FindClusters`, particularly `resolution` and `algorithm`
