### ISSUE TITLE
ColorTSNESplit not in Seurat 3?

### ISSUE THREAD

**Issue by nroak** [satijalab/seurat#1752]
I want to color part of tSNE plot at a specific node ClusterTree.
However, it seems this function is no longer available in newer Seurat3 package.
`
seuratObject <- BuildClusterTree(seuratObject, dims = 1:15,reorder = F,reorder.numeric = F)
ColorTSNESplit(seuratObject, node = 22)
Error in ColorTSNESplit(seuratObject, node = 22) : 
  could not find function "ColorTSNESplit"
`
Is there an alternative function to replace this?

**Comment by ccruizm** [comment]
Hello! 
I would also like to plot the output from the cluster tree onto a tSNE plot. I could not find a similar function in the new version (v3). Any suggestions? Thanks in advance

**Comment by tiagobrc** [comment]
Also looking forward to knowing the answer to this question!

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
