### ISSUE TITLE
Error in merge function

### ISSUE THREAD

**Issue by KatjaRM** [satijalab/seurat#1753]
Hello Satijalab :)

I am trying to merge two objects in Seurat v 3.0.2 via 

`Combined <- merge(x = a, y = b, add.cell.ids = c("10K", "5K"), merge.data = T)
`
and am getting the error

> Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

I realized that the Dimnames for the cells are actually one shorter than the number of cells for both datasets, but I am not sure why and how to fix it.

Not sure if that could be the reason but both datasets were created in older versions of Seurat and then updated.

Do you have a suggestion?

Best,

Katja

**Comment by satijalab** [comment]
Apologies for the delay in responding.

The fact that the dim lengths themselves is different from the number of cells is likely causing the problem. Perhaps there was some bug in the update.

The easiest thing to do is just to recreate the object as a new v3 object, for example

`a_v3 = CreateSeuratObject(counts = a@raw.data)`

And then to merge after that. This should solve your problem, but please re-open if it does not.

**Comment by KatjaRM** [comment]
Great! That works. Thank you very much!!!
Just in case anyone else runs into the same issue, here's the code I ran:

```
a_v3 = CreateSeuratObject(counts = a@assays$RNA@data)
a_v3$tsne <- a$tsne
a_v3@active.ident <- a@active.ident

b_v3 = CreateSeuratObject(counts = b@assays$RNA@data)
b_v3$tsne <- b$tsne
b_v3@active.ident <- b@active.ident

Combined <- merge(x = a_v3, y = b_v3, add.cell.ids = c("10K", "5K"), merge.data = T) 
```
Katja
