### ISSUE TITLE
Batch correction from two independent sequencing runs but on the same platorm

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#1755]
Hi all, 

I was wondering if you could help with a question I have for which I have not found a clear answer and any clarification would be much appreciated. 

I have two (and soon will have more than two) single cell sequencing 10x sets of data. I would like to combine these in order to find clusters present in both data sets but also different clusters as one of the sequencing runs contains cells that have been treated. As both of the sequencing runs have come from the same sequencer and 10x preparation, is it sufficient to use the ScaleData function as a batch correction method after merging two Seurat objects together? Will this mitigate variation by batch/sequencing/library preps?

My script is as follows: 

`sccombined<-merge(Seuratuntd, y=Seurattreated, add.cell.ids = c("x", "y"),project="combined")`

**downstream analysis which eventually reached:**

`sccombined <- ScaleData(sccombined, features = all.genes)
`

Apologies that this is not specifically an issue, however I have . not been able to find clear answer as to whether a specific batch correction step **beyond** scale data is required. especially as these were run on completely different experiments/days, but on the same sequencing platform etc....

many thanks!

**Comment by timoast** [comment]
My advice would be to first run an analysis without any batch correction, and see if there appears to be a batch effect in your data. If there is a batch effect that you want to remove I recommend using the integration methods in Seurat v3 (`FindIntegrationAnchors` and `IntegrateData`). If you don’t observe strong differences between batches driven by technical variation, then there would be no need to integrate.

**Comment by phoebee-h** [comment]
Hi, 
According to this situation, if we use the SCTransform without batch correction, is the following script appropriate? Should we first normalize two datasets separately,  or merging them first?

```
WT <- CreateSeuratObject()
MUT <- CreateSeuratObject()
## Then, rename cell barcode or AddMetaData()
WT_MUT <- merge(x=WT, y=MUT)
sct_intbefore <- WT_MUT %>%
  SCTransform(verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>%
  RunTSNE(dims = 1:20) %>%
  RunUMAP(dims = 1:20) %>%
  FindNeighbors(reduction = "pca", dims = 1:20) %>%
  FindClusters(resolution = 0.5) 
```

**Comment by phoebee-h** [comment]
Found a similar issue here:
https://github.com/ChristophH/sctransform/issues/32#issue-469922932
