### ISSUE TITLE
Aligned count matrix after MultiCCA

### ISSUE THREAD

**Issue by sarajimenez** [satijalab/seurat#1757]
Hello! 

I'm trying to implement Palantir (https://github.com/dpeerlab/Palantir) for single-cell trajectory detection in Python. I want to use a combined data set (data sets coming from different sequencing techniques), so I run MultiCCA in order to remove the batch effect. 

Now, I need an aligned count matrix [cellsxgenes]; however, after running MultiCCA I just can get a matrix with cells and the aligned canonical components [cellsxACC].

GetCellEmbeddings(data_cca, reduction.type = "cca.aligned", dims.use = 1:20)

I was wondering if is there a way to get a matrix of (cells)x(aligned_gene_expression). 

I'd really appreciate any information! 

Thanks in advance :)

**Comment by timoast** [comment]
Hi, MultiCCA does not provide a corrected matrix, and is no longer supported in Seurat v3.

Our new integration methods do provide a corrected matrix, see the vigette [here](https://satijalab.org/seurat/v3.0/immune_alignment.html) and paper [here](https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub)
