### ISSUE TITLE
CellSelector error

### ISSUE THREAD

**Issue by TziYang** [satijalab/seurat#1759]
Hi, I have a question about an error while using CellSelector function. I want to manually group cells by selecting them on the tSNE plot using the code below:

plot <- DimPlot(X3dpi, pt.size = 0.3, reduction = "tsne")
select.cells <- CellSelector(plot = plot)

An error popped up when I ran the code:

Error in pnt.in.poly(pnts = plot.data[, c(1, 2)], poly.pnts = polygon) : 
  pnts & poly.pnts must be a 2 column dataframe or matrix

I tried to google the problem but couldn't find the solution. Do you know how to solve it? I am using Seurat 3.0.1 and R 3.5.1 in Mac. Thank you in advance.

**Comment by mojaveazure** [comment]
I am unable to replicate this issue, could you share your object, a subset of your object that reproduces the issue, or your ggplot object?

**Comment by TziYang** [comment]
Thanks for the fast reply. I attach the ggplot object from pbmc_small dataset. It gives me the same error. 
[plot.RDS.zip](https://github.com/satijalab/seurat/files/3336623/plot.RDS.zip)

**Comment by mojaveazure** [comment]
I'm afraid I can't reproduce this issue. I would suggest restarting R and reinstalling Seurat and it's dependencies, including ggplot2, graphics, and SDMTools (the packages we use to enable `CellSelector` functionality).

![issue_1759](https://user-images.githubusercontent.com/11035068/60388352-16c3d380-9a7e-11e9-9042-625d1152ca0a.gif)

**Comment by mhclev27** [comment]
Hi, using the CellSelector function, it always returns the same error for me as well. I have reinstalled Seurat and the dependencies you suggested, and tried to run the function on the plot in your previous example, as well. Do you have any other advice for how to fix this error?

**Comment by ncborcherding** [comment]
I only get the error above if I am running the code in markdown, if running in the console, things run smoothly.

**Comment by apal6** [comment]
When I am running the IntegrateData function on my dataset, I get this error;

merging dataset 8 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length

Any advice?
