### ISSUE TITLE
question about Multi-set CCA

### ISSUE THREAD

**Issue by zacharylau10** [satijalab/seurat#176]
Hi Seurat Team,
    I want to analysis my own data sets with CCA, and I noticed the methods mentioned in preprint. First, I chose a reference dataset with other set respectively, and the `object@dr$cca.aligned@cell.embeddings` are bind with row-wise to performing tsne. I know it is wrong, so the result is terrible.
    So, could you give me some advice to perform CCA with multi-set CCA?
Thanks!

**Comment by satijalab** [comment]
We do not support this at the moment, but will be releasing methods for multiple alignment in the near future

**Comment by del2007** [comment]
Looking forward to the multiple alignment methods release!
In the meantime, is there any way you could break down a protocol in steps to reiteratively align multiple data sets? 
I am seeing that the order in which one does this matters - dependent of the common genes and variability between each pair of objects one aligns. Is this correct? If the CCAs from the first alignment are limited then it affects the next alignment and so on? If this is true is there a way to get around this by reusing the raw data and redoing the alignment every time a new object is added to the previously-aligned object?

Thanks for any insights.
