### ISSUE TITLE
Cannot find UMAP, please install through pip (e.g. pip install umap-learn).

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1760]
The package version of Seurat is 3.0.2
I tried pip install umap-learn and even
library("reticulate")
 use_condaenv(condaenv="Renv", conda="/Users/user/anaconda3/bin/conda")
All showed umap is installed. But it still showed that it can not find umap.
Thank you,
Jinping

**Comment by satijalab** [comment]
Please try this command, and make sure to restart R afterwards
reticulate::py_install(packages ='umap-learn')

**Comment by surljp2012** [comment]
Thank you!
I tried and it showed:
> reticulate::py_install(packages ='umap-learn')
Error in conda_python(envname = envname, conda = conda) :
  conda environment r-reticulate not found

Do you know what should I do to deal with this?
Thank you,
Jinping

**Comment by nbartonicek** [comment]
Installed new conda, umap installed, even tried reticulate::py_install(packages ='umap-learn'), restarted R and: "Cannot find UMAP, please install through pip...".
Doesn't work.

**Comment by surljp2012** [comment]
Great!
Thank you,
Jinping

**Comment by rlittman16** [comment]
Hi Jinping,

Try: 
`reticulate::py_install(envname="Renv", packages ='umap-learn')`

py_install is looking for the environment r-reticulate, but you have a different name for it. 

If this doesn't work, you can create a new environment called r-reticulate with:
`library(reticulate)`
`conda_create("r-reticulate")`

**Comment by surljp2012** [comment]
Thank you so much for your suggestions!

Best wishes,
Jinping

**Comment by achamess** [comment]
> Hi Jinping,
> 
> Try:
> `reticulate::py_install(envname="Renv", packages ='umap-learn')`
> 
> py_install is looking for the environment r-reticulate, but you have a different name for it.
> 
> If this doesn't work, you can create a new environment called r-reticulate with:
> `library(reticulate)`
> `conda_create("r-reticulate")`

The above worked for me after many tries with different solutions.
Note: I installed umap not with conda but with pip

**Comment by timoast** [comment]
We have now added support for the UWOT R package, so you no longer need to install the python package to run UMAP in Seurat. This is currently in the develop branch, see installation instructions [here](https://satijalab.org/seurat/install.html)

**Comment by surljp2012** [comment]
Great!

Thank you and best wishes,
Jinping
