### ISSUE TITLE
Cannot find UMAP: with installed UMAP

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1761]
The package version of Seurat is 3.0.2
I tried pip install umap-learn and even
library("reticulate")
use_condaenv(condaenv="Renv", conda="/Users/user/anaconda3/bin/conda")
I also tried:
reticulate::py_install(packages ='umap-learn')
This shows:
**Error in conda_python(envname = envname, conda = conda) :
  conda environment r-reticulate not found**

Thank you,
Jinping

**Comment by mojaveazure** [comment]
Hi Jinping,

Please uninstall Anaconda and use the version of Python that came with your Mac. There are workarounds to getting Anaconda to work with reticulate, but they seem to break often. [We've noticed many issues with Anaconda and reticulate not working together](https://github.com/satijalab/seurat/issues?utf8=%E2%9C%93&q=is%3Aissue+conda+), and strongly suggest using your computer's default Python installation.

**Comment by surljp2012** [comment]
Thank you, Paul!
It works after uninstall Anaconda and restart R.
Thank you so much,
Jinping

**Comment by davidasiegel** [comment]
So basically you're saying that python users are out of luck??

**Comment by YichaoOU** [comment]
There must be a parameter to set the path to umap for seurat, right? So that it can solve the anaconda users' problem?

**Comment by davidasiegel** [comment]
YichaoOU this ended up working for me: https://github.com/satijalab/seurat/issues/631

**Comment by YichaoOU** [comment]
Yeah, after I made this comment, I did some search and found a similar solution, but I have to specify both `use_python` and `use_condaenv`, and they have to be run in order, I don't know why.
