### ISSUE TITLE
Error in sample.int(length(x), size, replace, prob) :    NA in probability vector

### ISSUE THREAD

**Issue by biowak** [satijalab/seurat#1762]
I am trying the SCTransform using the same seurat object from CreateSeuratObject that I used to run through the same pipeline as the standard seurat for comparison (exactly what is shown in the vignette). However, the SCTransform command gives this error while the standard pipeline worked exactly like the vignette demonstrated:
Error in sample.int(length(x), size, replace, prob) :    NA in probability vector

Can you please point me in the correct direction?
Thank you.

**Comment by yuhanH** [comment]
Could you show me the script you used? Thanks

**Comment by biowak** [comment]
mypath = "/media/epigenetics/scRNAseq/"
setwd(mypath)

library(Seurat)
library(dplyr)
library(Matrix)
library(AnnotationDbi)
library(org.Mm.eg.db)
library(tidyr)
library(umap)

multmerge = function(mypath){
  filenames=list.files(path=mypath, pattern="Transcript_Count.txt")
  datalist = lapply(filenames,
function(x){read.delim(file=x,header=T,sep="\t")})
  Reduce(function(x,y) {merge(x,y)}, datalist)}

mymergeddata = multmerge("/media/epigenetics/scRNAseq/")
mydata <- mymergeddata[!duplicated(mymergeddata[,'ID']),]
row.names(mydata) <- mydata[,1]
mydata <- mydata[,-1]

###Convert the ensembl ID to gene symbol###
mydata$symbol <- mapIds(org.Mm.eg.db,
                       keys = row.names(mydata),
                       column = "SYMBOL",
                       keytype = "REFSEQ",
                       multiVals = "first")

mydat <- mydata[!duplicated(mydata[,'symbol']),]
mydat <-na.omit(mydat, cols="symbol")
row.names(mydat) <- mydat$symbol
myda <- mydat[,-4993]

###Import the metadata table###
List_cell_names_omicsoft <-
read.delim("/media/epigenetics/gsk03/PRMT1/scRNAseq/List_cell_names_omicsoft.txt",
row.names=1)
###Import counts table into seurat and filter for cells with low counts and
min # of cells###
data <- CreateSeuratObject(myda, project="Omicsoft_PRMT1",min.cells = 3,
min.features = 200, meta.data=List_cell_names_omicsoft)
data

# store mitochondrial percentage in object meta data
data <- PercentageFeatureSet(data, pattern = "^MT-", col.name = "percent.mt
")
# run sctransform
data <- SCTransform(data, verbose = FALSE)

**Comment by satijalab** [comment]
I don't see any particular issues in the code, so there is likely something in the data that is causing an error when running SCTransform. I am assuming you can run SCTransform on the datasets we provide.

Unfortunately there's not much we can do in terms of debugging without having access to the data itself, as we have not encountered this error before. If you are comfortable, you can post either your object or a subset of your object that reproduces your error as an issue on the SCTransform github (https://github.com/ChristophH/), and @ChristophH may be able to help.

**Comment by davemcg** [comment]
I've run into the same issue. Perhaps because my this dataset is too small (79 cells)? 

```
# bash
wget https://hpc.nih.gov/~mcgaugheyd/SRP161678_SMARTSeq_v4.Rdata .
```

```
# R
library(Seurat)
load('SRP161678_SMARTSeq_v4.Rdata')
> sct <- SCTransform(SRP161678_SMARTSeq_v4)
Calculating cell attributes for input UMI matrix
Error in sample.int(length(x), size, replace, prob) :
  NA in probability vector
```

**Comment by qingchaoxiantiao** [comment]
I happen to have the same issue.  It solved automatically after I set "min_cells" to a higher value.
More information on the argument "min_cells" could be found by typing in " ?sctransform::vst ".
I'm using Seurat_3.1.5 and running on R version 3.6.
