### ISSUE TITLE
FindMarkers with negbinom/DeSeq2 giving error

### ISSUE THREAD

**Issue by VilainLab** [satijalab/seurat#1763]
Hi,

I was trying to use the negbinom or the DeSeq2 option for FindMarkers. It is throwing me an error. "The following cell names provided to cells.1 are not present: ". I had checked a previous issues (Issue#932) , and it made sense to me to use the development version of Seurat, to get rid of this error. But I am still facing the same issue. Please find below the code for the same. 
WTM1.seurat$stim = "WTM1"
B1M.seurat$stim = "B1M"
WTM1.seurat.filterd <- subset(WTM1.seurat, subset = (nFeature_RNA > 100 & nFeature_RNA < 6500) &  (nCount_RNA > 100 & nCount_RNA < 60000))
B1M.seurat.filterd <- subset(B1M.seurat, subset = (nFeature_RNA > 300 & nFeature_RNA < 6000) &  (nCount_RNA > 100 & nCount_RNA < 50000))
WTM1.seurat.Normalized <- NormalizeData(WTM1.seurat.filterd, verbose = FALSE)
B1M.seurat.Normalized <- NormalizeData(B1M.seurat.filterd, verbose = FALSE)
WTM1.seurat.variable <- FindVariableFeatures(WTM1.seurat.Normalized, selection.method = "disp", nfeatures = 2000)
B1M.seurat.variable <- FindVariableFeatures(B1M.seurat.Normalized, selection.method = "disp", nfeatures = 2000)
**WTM1.seurat.variable**
An object of class Seurat 
31053 features across 1406 samples within 1 assay 
Active assay: RNA (31053 features)
 **B1M.seurat.variable**
An object of class Seurat 
31053 features across 1385 samples within 1 assay 
Active assay: RNA (31053 features)
macrophages.anchors <- FindIntegrationAnchors(object.list = list(WTM1.seurat.variable, B1M.seurat.variable))
macrophages.combined <- IntegrateData(anchorset = macrophages.anchors)
DefaultAssay(macrophages.combined) <- "integrated"
macrophages.combined_scale <- ScaleData(macrophages.combined, verbose = FALSE)
macrophages.combined_PCA <- RunPCA(macrophages.combined_scale, npcs = 30, verbose = FALSE)
macrophages.combined_tSNE <- RunTSNE(macrophages.combined_PCA, reduction = "pca")
macrophages.combined_neigbor <- FindNeighbors(macrophages.combined_tSNE, reduction = "pca")
macrophages.combined_Clust <- FindClusters(macrophages.combined_neigbor, resolution = 0.5)
p1 <- DimPlot(macrophages.combined_Clust, reduction = "tsne", group.by = "stim")
p2 <- DimPlot(macrophages.combined_Clust, reduction = "tsne", label = TRUE)
plot_grid(p1, p2)
**macrophages.combined_Clust**
An object of class Seurat 
33053 features across 2791 samples within 2 assays 
Active assay: integrated (2000 features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, tsne
DefaultAssay(macrophages.combined) <- "RNA"

mutant_vs_wildtype_macrophage <- FindMarkers(macrophages.combined_Clust, ident.1 = "B1M", ident.2 = "WTM1", verbose = TRUE,  test.use = "negbinom", group.by = "stim")
**Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : **
**The following cell names provided to cells.1 are not present: **

Can you please help me debug this issue?

Thanks,
Surajit

**Comment by yuhanH** [comment]
Have you tried Deseq2 under development version of Seurat?

**Comment by VilainLab** [comment]
Yes. I installed the developement version of Seurat using
install.packages('devtools')
devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')
library(Seurat)

Is there anything else I need to do?

Thanks,
Surajit

**Comment by yuhanH** [comment]
Does the default `FindMarkers` work?
`FindMarkers(macrophages.combined_Clust, ident.1 = "B1M", ident.2 = "WTM1", verbose = TRUE, group.by = "stim")`

**Comment by VilainLab** [comment]
Yes...That works
mutant_vs_wildtype_macrophage <- FindMarkers(macrophages.combined_Clust, ident.1 = "B1M", ident.2 = "WTM1", verbose = TRUE,  test.use = "wilcox", group.by = "stim")
mutant_vs_wildtype_macrophage[1:5,]
               p_val  avg_logFC pct.1 pct.2     p_val_adj
Mucl1  9.375462e-274 -0.7674649 0.756 0.037 1.875092e-270
Hspb1  9.178729e-145 -0.3261143 0.927 0.182 1.835746e-141
Ear2   6.126924e-125 -0.3042546 0.955 0.228 1.225385e-121
Cd209b 2.507864e-116 -0.3346509 0.953 0.232 5.015729e-113
Ccnd2  2.616307e-105 -0.2829952 0.968 0.266 5.232614e-102

**Comment by satijalab** [comment]
Closing as we are in the process of removing support from DESeq (see #2938)
