### ISSUE TITLE
[Help] Mapping Immune Microenvironment with tSNE Visualization

### ISSUE THREAD

**Issue by jonathanzhang53** [satijalab/seurat#1764]
So right now I am using Seurat in order to try to map the immune micro environment for murine mammary gland cells.

tSNE returned 30 identifiable clusters with ~30k cells. I have grouped most of the clusters but some groups have many clusters within them (such as the B cell and T cell group), where I want to identify subtypes in the group which should match up with clustering info.

I am currently looking at literature to identify potential markers that will differentiate but it is agonizingly slow and I've run into a lot of dead ends. I've tried using FindMarkers but it generally doesn't yield anything useful (and everything it gives I have to check against literature to see if there is some conclusion there).

Any suggestions?

Currently I'm just running commands like this one and seeing what gets plotted.:
```
FeaturePlot(object = d, features.plot = c('Sell','Csf1r','Cd14'), cols.use = c("grey", "blue"), reduction.use = "tsne")
```

**Comment by timoast** [comment]
This is quite a general question so it’s difficult to give specific advice, but good ways of exploring the data are using the plotting functions like `VlnPlot`, `FeaturePlot`, `DoHeatmap`, and `DotPlot`. Interpreting the clusters is often the most difficult and time consuming step of a single-cell analysis.

**Comment by jonathanzhang53** [comment]
@timoast thanks for the guidance. I am new to this scrna stuff so I was a bit stuck. 

Also, is there any complete command lists/guides/tutorials for Seurat 2.3.4 or just Seurat v2? My lab is using the older version.

**Comment by timoast** [comment]
You can find old versions of all the vignettes on the Seurat [website](https://satijalab.org/seurat/get_started.html), by clicking the orange box at the bottom right of each vignette to change the version. I would encourage you to use the new version though (particularly if you're just getting started learning Seurat), we made many improvements over v2
