### ISSUE TITLE
Paired Samples + different time points differential expression 

### ISSUE THREAD

**Issue by AMA111** [satijalab/seurat#1765]
Dear Seurat team, 
I am analysing a patient cohort which have been sequenced in two different time points. For example: 5 patients in group A and 5 patients in group B and each patient have been sequenced in two different time points (10 years is the difference between the two time points). After assigning cell types; I would like to perform differential expression analysis between the paired samples in the different time points within the different groups for each cell type. 

Do you suggest a certain function (FindMarkers/ FindConservedMarkers) or test to perform such analysis? 

Thank you in advance!

Best,
Abdelrahman

**Comment by satijalab** [comment]
Thanks for the interesting question.
I would suggest using the logistic regression DE test, which allows you to set a latent variable that you want to control for (in this case, the exact patient ID within a group).

For example, to find differences in NK cells between groups A and B at timepoint 1:

`markers = FindMarkers(subset(object, time==1), test.use="LR", latent.vars = 'patient', group.by = 'celltype', subset.ident = "NK")`

You can repeat this analysis across cell types and time points.

Stay tuned for more updates on our side on how to streamline this process.

**Comment by AMA111** [comment]
Interesting read "On the discovery of population-specific state transitions from
multi-sample multi-condition single-cell RNA sequencing data" https://www.biorxiv.org/content/biorxiv/early/2019/07/26/713412.full.pdf 

Best,
Abdelrahman

**Comment by MarijaDur** [comment]
Hi, I have similar problem with analyzing paired data. In my case, I have one sample at 4 time points (before and after treatment). How to perform comparisons of different time points within cluster and between clusters?
I have tried next:
`FindMarkers(sc.combined, test.use="LR", latent.vars = 'patient', group.by = 't_exp', ident.1 = 0) `
But it provides me error: 
```
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: 0
```
Thanks,
Marija
