### ISSUE TITLE
VlnPlot Sv.3 update tutorial

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#1766]
using Seurat v3.0.2 
Under
# Visualize QC metrics as a violin plot
This line gives an error:
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

This line plots three metric features correctly
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))

**Comment by AndyR2** [comment]
Also,  two features of S v2 that were useful that don't run in S v3 are 
GetClusters(obj)
table(obj@ident)

**Comment by mojaveazure** [comment]
Can you provide the `VlnPlot` error? The functionality of `GetClusters` can be replicated with `FetchData(obj, vars = 'ident')`

**Comment by AndyR2** [comment]
Well, now it's fine.   Was using Seurat v 3.0.2.   Now using freshly installed developmental version (3.0.3.9007).   I will delete this thread.
