### ISSUE TITLE
use SCTransform for DEG detection and how to interpret avg_diff

### ISSUE THREAD

**Issue by guoyanzhao** [satijalab/seurat#1767]
Dear Seurat Team,
Thank you for this wonderful tool. It has been very useful in analyzing our data.

Following your recommendation “the absolute best way to do this is to run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data.” I tried the following:

I used “return.only.var.genes = FALSE” to obtain pearson residuals as suggested. 

C1_subset <- SCTransform(C1_subset, return.only.var.genes = FALSE, vars.to.regress = c("percent.mito", "nCount_RNA"), verbose = FALSE) 

Then I used  the following command to use Pearson residuals for DEG detection using wilcox test.

FindMarkers(object = C1_subset, ident.1 = cell1, ident.2 = cell2, assay = "SCT", slot = "scale.data", only.pos = FALSE, min.pct = 0.25, test.use = "wilcox", logfc.threshold = 0.25)

My question is:
1)	Whether my command for doing SCTransform is correct?
2)	Whether my command to use Pearson residuals for DEG detection is correct?
3)     There is a column in the DEG output named "avg_diff". How is that calculated? The range of avg_diff  is -2023.84  to  616.06 which seems huge. How to interpret that?

Thank you very much for your time and help!

**Comment by satijalab** [comment]
1. The command is correct
2. SCT Pearson residuals place highly expressed and lowly expressed genes on the same scale, so it is not meaningful to consider average logFC of these values. In the future we will consider replacing the logFC  values with those calculated from the @data slot instead.

**Comment by flde** [comment]
Dear Seurat Team, 
Many thanks for your awesome work! 

One follow because it worries me and it fits with this threat. How does findMarkers on SCTransform scale.data handle the logfc.threshold? And anything new about replaceing the logFC in the @DaTa slot? 

Best, Flo
