### ISSUE TITLE
how to create seurat object using GEO data?

### ISSUE THREAD

**Issue by ZenobiaDing117** [satijalab/seurat#1769]
I'm wondering about how to use the single cell data provided in GEO. It provides SOFT formatted family file(s), MINiML formatted family file(s) and Series Matrix File(s). Which one do I need to use? I think they are raw data right? Should I use CreateSeuratObject function to transform the data in GEO to seurat object or some other R package is needed? Thank you very much if you can help me on this!

**Comment by mojaveazure** [comment]
[`CreateSeuratObject`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/CreateSeuratObject) takes an expression matrix ([sparse](https://www.rdocumentation.org/packages/Matrix/versions/1.2-17/topics/dgCMatrix-class) or [dense](https://www.rdocumentation.org/packages/base/versions/3.6.0/topics/matrix)) where the columns are cells/samples and the rows are features/genes. While we don't have a function for reading directly from GEO, as long as you can get an expression matrix for the data you're interested in and read it into R (see [`readMM`](https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/externalFormats.html), [`read.table`](https://www.rdocumentation.org/packages/utils/versions/3.6.0/topics/read.table), or other functions for reading data into R), you can pass that to `CreateSeuratObject`

**Comment by Diozao666** [comment]
I successfully loaded the expression and cell labels in a Seurat object, but even after following the tutorial I don't understand how you can add the metadata using SOFT or xml files, as mentioned by Zhang. The structure of these files don't resemble any other identities tables I have seem in other Seurat objects
