### ISSUE TITLE
Error running BuildClusterTree using SNN

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#177]
Hi,

I was using `BuildClusterTree()` to build a tree of my clustering result as described in the pbmc33k tutorial. When I try to build a tree based on SNN graph connectivity between clusters, I got the following error:

```
umi_seurat <- umi_seurat %>% BuildClusterTree(SNN.use = umi_seurat@snn)

Error in WhichCells(object = object, ident = j) : Identity : 28 not found.
```
I have 28 clusters in the `@ident` slot. Looking at the source code, I think the problem is because the `FindClusters()` gives indices that start from 0 (0, 1, ..., 27), but `BuildClusterTree()` looks for cluster indices that start from 1 (1, 2, ..., 28). The error can be resolved by resetting the `@ident` slot to (1, 2, ... 28).

**Comment by mschilli87** [comment]
@andrewwbutler: was this fixed now or invalid?

**Comment by andrewwbutler** [comment]
Whoops. Closed the wrong issue. I don't think this has been address yet.

**Comment by satijalab** [comment]
Issue has been fixed on develop branch, will be in the next CRAN release
