### ISSUE TITLE
UpdateSeuratObject glitch workaround

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#1770]
I am getting a similar failure when trying to use UpdateSeuratObject on objs created in v 2.3.4 and showing that version.  Currently running Seurat 3.0.3.9007

`Mp0_F3_M6_S2@version`
[1] ‘2.3.4’

`Up_Mpo_F3_M6_S2 <- UpdateSeuratObject(Mp0_F3_M6_S2)`
Error: We are unable to convert Seurat objects less than version 2.X to version 3.X
Please use devtools::install_version to install Seurat v2.3.4 and update your object to a 2.X object

_Originally posted by @AndyR2 in https://github.com/satijalab/seurat/issues/1722#issuecomment-506991067_

**Comment by AndyR2** [comment]
update:  loaded Robj into different workstation running Seurat 3.0.2.
UpdateSeuratObject  ran properly to update Robj v 2.3.4 to 3.0.2.

brought updated Robj back into Seurat 3.0.3.9007 and it showed as updated and is interactive.

so, I conclude the glitch was in the particular dev version of Seurat that I installed.

**Comment by mojaveazure** [comment]
Hi @AndyR2,

Would you be able to share the object, or a downsampled version of the object that reproduces the error, so we can debug and make sure that the development version of Seurat is able to update Seurat v2 objects properly?

**Comment by AndyR2** [comment]
Paul,
Here is a link to an Robj in Dropbox that I could not get to update using S 3.0.3.9007, but did work on S 3.0.2.     This object was created using S 2.3.4
https://www.dropbox.com/s/e3jwdjc9bgjwn64/Mp0_F3_M6_cr2.Robj?dl=0

regards
AndyR

**Comment by mojaveazure** [comment]
Hi @AndyR2,
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development). Could you give it a whirl and let me know if it works?

**Comment by AndyR2** [comment]
UpdateSeuratObject now working.    Seurat version number now showing S v 3.0.3.9009.

Thx Paul
