### ISSUE TITLE
merging Seurat objects  with different gene lengths

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#1771]
Hi all, 

I was just wondering how merging two or more Seurat object handles the objects when gene lists are of different lengths (i,.e one of the object with a count matrix of 18,000 and the other of 20,000 for example. I have a couple of questions just for my own sanity to be sure that merging the objects is working correctly:

1. Do the genes have to be in the same order for both seurat objects before merging ? (presumably not as the merge function should match values) and therefore counts for each gene in different object should be correct for all samples?

2. When making duplicate genes unique in order to preserve all genes in the matrix, how does the merge function handle these genes as well as genes that are present in one data set but not the other? 

Are the counts that exist for one data set added to the bottom of the list and then for the other seurat object all assigned 0's for those counts?

Does merging two seurat objects which represent different experiments take care of the above? I have not encountered this in the vignette or other documentation.

does `all.genes <- rownames(Seuratmerged)` still keep the right genes and counts for each sample correctly?

Any help would be much appreciated! thank you!

**Comment by satijalab** [comment]
1. The genes do not have to be in the same order
2. Yes, the counts for genes that are unique to one object are preserved, and set to 0 for the other object.

It sounds like this is the behavior your are looking for. If you find an example where Seurat is not behaving in this way upon merging objects, just let us know.

**Comment by amjass12** [comment]
thank you so much!!! this answers my question completely! it was more of a sanity check as i will be doing alot of merging of objects together so want to make sure the gene orders are preserved and merged appropriately without loosing information!!

I have not come across such a situation but will let you know if i do!

thank you for all your help :)
