### ISSUE TITLE
BuildClusterTree error

### ISSUE THREAD

**Issue by L30P30** [satijalab/seurat#1772]
Hi, I'd like to build a cluster tree but I am running into the following error:

> Object <- BuildClusterTree(Object, verbose = TRUE)
Finished averaging RNA for cluster x
Finished averaging RNA for cluster y
Finished averaging RNA for cluster z
Finished averaging SCT for cluster x
Finished averaging SCT for cluster y
Finished averaging SCT for cluster z
Error in hclust(d = data.dist) : 
  NA/NaN/Inf in foreign function call (arg 11)

Do you have any suggestions?

Many thanks

**Comment by andrewwbutler** [comment]
Hi, 

Could you share an object that reproduces the issue?

**Comment by chlee-tabin** [comment]
I just wanted to make sure there is a reproducible error using pbmc_small (although it does not generate the same error message, I think it is still related to SCT and may give some hint):

https://github.com/satijalab/seurat/issues/1559#issuecomment-516269481
