### ISSUE TITLE
error in "FindConservedMarkers" of the PBMC tutorial to identify Identify "conserved cell type markers"

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1773]
Hi,
I met the error by running the PBMC tutorial from the link of https://satijalab.org/seurat/v3.0/immune_alignment.html

>nk.markers <- FindConservedMarkers(immune.combined, ident.1 = 7, grouping.var = "stim", verbose = FALSE)

Warning: Identity: 7 not present in group CTRL. Skipping CTRL
Warning: Identity: 7 not present in group STIM. Skipping STIM
**Error in names(marker.test) <- levels.split :** 
  **'names' attribute [2] must be the same length as the vector [0]**
Do you have any suggestions about it?
I think this will lead more error with downstream codes.
Thank you,
Jinping

**Comment by a582213088** [comment]
Hi,
I have the same error and what can I do to deal with it？
Thanks
