### ISSUE TITLE
Behavior of UMI correction after sctransform

### ISSUE THREAD

**Issue by chlee-tabin** [satijalab/seurat#1775]
![image](https://user-images.githubusercontent.com/31305155/60451754-cb82ff80-9bfa-11e9-8341-cba39bfec0af.png)

I am wondering how to interpret the relationship between nCount_RNA and nCount_SCT where the relationship is inverse (see above figure). What would be the correct way to explain this?

**Comment by chlee-tabin** [comment]
I just realized that this might be probably due to the fact that sctransform is omitting genes that are not variable, and the counts represents cumulative counts from the select genes that were transformed, not the raw data, as I see somewhat sharp drop of feature count numbers around 1000-2000 as well.

![image](https://user-images.githubusercontent.com/31305155/60981106-b184a380-a303-11e9-8090-8bf040355365.png)

Would this mean that my selection of 2,000-3,000 variable genes are not appropriate?

**Comment by satijalab** [comment]
It is not meaningful to plot nFeature_RNA vs nFeature_SCT, so I would not worry about these results. The true output of SCT is stored in the scale.data slot, and can be positive or negative. The UMI corrected values are primarily meant for the convenience of visualization (for example, drawing violin  or Feature plots).
