### ISSUE TITLE
SCTransform return.only.var.genes	 

### ISSUE THREAD

**Issue by atermanini** [satijalab/seurat#1776]
Hi,

reading the online tutorial here:
https://satijalab.org/seurat/v3.0/sctransform_vignette.html

I found:

"To save memory, we store these values only for variable genes, by setting the return.only.var.genes = TRUE by default in the SCTransform function call."

However, by looking at the help of the function with ?SCTransform, I found:
return.only.var.genes	... default is FALSE

Which one is right?

Thanks very much,
Alberto

**Comment by yuhanH** [comment]
Hi, 
Thanks. It should be `return.only.var.genes = FALSE`
When you run SCTransform on the object, your object will only have Pearson residual value  top 3000 variable genes by default.

**Comment by yuhanH** [comment]
It has been fixed in the current Seurat version.
