### ISSUE TITLE
LogNormalize Integrated Question

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1778]
Hi all, 

Thanks again for all of your help with this package. 

Question about the integration workflow: if we wish to perform the cell cycle regression, do we do this on the individual datasets prior to integration, on the integrated dataset on the integrated assay, or on the RNA assay of the integrated data? 

Thanks!

**Comment by satijalab** [comment]
We would recommend calculating cell cycle scores on the RNA assay, and regressing on the integrated  assay.
