### ISSUE TITLE
Annotation file for PBMC scATAC-seq Vignette

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#1779]
Hello everyone,
How do I find the annotation file and download it? can anyone provide a link please?
Thank you

**Comment by satijalab** [comment]
The scATAC-seq metadata file is available here : http://cf.10xgenomics.com/samples/cell-atac/1.0.1/atac_v1_pbmc_10k/atac_v1_pbmc_10k_singlecell.csv
