### ISSUE TITLE
add a colour annotation bar to the heatmap generated by DoHeatmap function

### ISSUE THREAD

**Issue by Ryo-1234** [satijalab/seurat#1780]
Using Seurat, I want to make multiple annotations of my Do.heatmap, but I don't know how should I do.
My heat map had one annotation including 60 identities that mixed 4 human samples and 15 cell types respectively. It was coded like the Seurat tutorial.
I would like to make multiple annotations of the human samples classification, the cell type classification and dendrographs of the cell types respectively. 
How should I change my code?

```
all.genes <- rownames(panc.combined)
panc.combined <- ScaleData(panc.combined, features = all.genes)
panc.markers <- FindAllMarkers(panc.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
library(stats)
library(dplyr)
panc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
top10 <- panc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
DoHeatmap(panc.combined, features = top10$gene, draw.line = TRUE, size = 3) + FontSize (x.text = 2, y.text = 2, x.title = 2, y.title = 2)
```

**Comment by satijalab** [comment]
We currently do not support  this in  Seurat. It is on our list of possible enhancements, so please stay tuned for future updates.

**Comment by smk5g5** [comment]
Is there an enhancement added to Do.heatmap function to be able to add row annotations?
