### ISSUE TITLE
Removing cells expressing high levels of marker genes from microglia, astrocyte, etc. cell populations

### ISSUE THREAD

**Issue by seekingseq** [satijalab/seurat#1782]
Hi! 

Does anybody have any insight as to how I might sub-cluster a cluster by removing cells expressing high levels of marker genes from microglia, astrocyte, etc. cell populations? 

Any help would be much appreciated! thanks!

**Comment by satijalab** [comment]
You can use the subset function to do  so, for  example:
`object = subset(object, GFAP < 4)`

More examples here: https://satijalab.org/seurat/v3.0/interaction_vignette.html
