### ISSUE TITLE
Find all genes expressed in a specific cluster

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1783]
I want to look at e.g. all cell surface molecules expressed in a particular cluster of cells. I don't want to look at only those genes that are differentially expressed, but any gene with higher than e.g. 2 read counts. After that, I can probably do a GO analysis to find which of those are cell surface molecules.

I'm not sure what are some possible ways to do this. If I try FindMarkers, it will only return to me genes that are differentially expressed. But I am interested in what genes are just expressed within that cluster itself.

Also, if I wanted to look for all genes expressed in one cell above a certain threshold, is there a function that could be used for that?

**Comment by satijalab** [comment]
You can use the AverageExpression function to get cluster-level  expression values, and then subset out your genes of interest.  More info here: https://rdrr.io/github/satijalab/seurat/man/AverageExpression.html
