### ISSUE TITLE
Error in fftRtsne(X = object, dims = dim.embed, rand_seed = seed.use,  :    no fast_tsne_path specified and fast_tsne binary is not in the search path

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1784]
Hi,

I met this issue"Error in fftRtsne(X = object, dims = dim.embed, rand_seed = seed.use,  :    no fast_tsne_path specified and fast_tsne binary is not in the search path" when I run through the code of "Mouse Cell Atlas"

Would you please help me with this?

Thank you,
Jinping

**Comment by satijalab** [comment]
You need to install the FIt-SNE package - and can find instructions to do so  here:
https://github.com/KlugerLab/FIt-SNE

**Comment by surljp2012** [comment]
Great! :)

Thank you,
Jinping
