### ISSUE TITLE
FindIntegrationAnchors cannot allocate vector of size 

### ISSUE THREAD

**Issue by jhl0214** [satijalab/seurat#1786]
So I have 3 data sets of 34x150000, 34x180000, 34x190000. It does not cause any problems when I am trying to create seurat object with these data. However, when I run the FindIntegrationAnchors with the 3 seurat objects that are created from the 3 data sets, it gives me this error:

Error: cannot allocate vector of size 254.8 Gb

Does it usually require that much memory for those sizes of the data sets? Each seurat object has size of 108Mb, 128.9Mb, and 140.6Mb.

Can anyone suggest me a solution for this problem?

I tried using half of the data when creating seurat object, and when I tried to run FindIntegrationAnchors, it gives same error, but this time for size 60.4 Gb.

**Comment by satijalab** [comment]
We will be releasing an update to FindIntegrationAnchors  that enables the processing of very large datasets with substantially reduced memory overhead in the near future. Please keep an eye on the website.  I am closing this issue for the moment, but if you continue to run into issues afterward the  update, please do reopen.
