### ISSUE TITLE
What's the difference between merge() and IntegrateData()

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#1787]
What's the difference between merge() and IntegrateData()?

I counted the numbers of gene names in the Seurat matrix of SeuratObject_1, SeuratObject2, SeuratObject_merged_1&2，and SeuratObject_integrated_1&2, by using the function "length(rownames(as.matrix(GetAssayData(SeuratObject))))", which resulted in 19978, 20077, 31053, and 2000 respectively.

Why the numbers varied so much?
And what's the functional difference between merge() and IntegrateData()?
Thank you so much!

PS 
SeuratObject_merged_1&2 <- merge(x = SeuratObject_1, y = SeuratObject2)

certain.anchors <- FindIntegrationAnchors(object.list = list(SeuratObject_1, SeuratObject2), dims = 1:11)
SeuratObject_integrated_1&2 <- IntegrateData(anchorset = certain.anchors, dims = 1:11)

**Comment by yuhanH** [comment]
Hi
`merge` just concatenates the counts or data table from two object together. If either object has unique genes, it will be added in the merged objects.
`IntegrateData ` is a step in the integration, integrating two objects by anchor cells. The detail you could find in the paper, [here.](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8)
The object obtained from `IntegrateData` only contains anchor genes, which can be set in the `FindIntegrationAnchors `

**Comment by grimwoo** [comment]
> Hi
> `merge` just concatenates the counts or data table from two object together. If either object has unique genes, it will be added in the merged objects.
> `IntegrateData ` is a step in the integration, integrating two objects by anchor cells. The detail you could find in the paper, [here.](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8)
> The object obtained from `IntegrateData` only contains anchor genes, which can be set in the `FindIntegrationAnchors `

Sorry, I still cannot fully understand the difference. Could I explain it this way: merge() conserved the original raw data of the objects; and IntegrateData() normalized the raw data?
And another question is which function I should use in my experiment. I have two data from two different conditions. Should I use merge() or IntegrateData(), because the RunUMAP() results are largely varied? Look forward to your reply.

**Comment by yuhanH** [comment]
Right. Your understanding is correct. 
I think this [tutorial](https://satijalab.org/seurat/v3.0/immune_alignment.html) fits your situation.

**Comment by grimwoo** [comment]
> Right. Your understanding is correct.
> I think this [tutorial](https://satijalab.org/seurat/v3.0/immune_alignment.html) fits your situation.

Thank you so much!!
