### ISSUE TITLE
RunPCA error

### ISSUE THREAD

**Issue by zyzhangyan** [satijalab/seurat#1788]
Hi Seurat Team,
I followed the tutorial of Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses. 
```
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:30)
DefaultAssay(immune.combined) <- "integrated"  
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
```
I did these above successfully.
### The immune.combined is 
An object of class Seurat
16494 features across 142032 samples within 2 assays
Active assay: integrated (2000 features)
 1 other assay present: RNA

But when I did the RunPCA, there was something wrong with it.
`immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)`
**the error is :**
Error in irlba(A = t(x = object), nv = npcs, ...) :
  max(nu, nv) must be positive

Could you please help me with that? 

Many thanks,
Emily

**Comment by andrewwbutler** [comment]
Hi Emily,

Are you running this on the data from that tutorial? If not, could you provide an object that reproduces the issue?

**Comment by zyzhangyan** [comment]
Hi Andrew,


I'm not running the data from the tutorial but using the large data that contains more than 130,000 cells from 23 samples. So maybe it's not convenience to provide the data.
And I was wondering if the number of the cells is too much. 








 




------------------ Original ------------------

**Comment by andrewwbutler** [comment]
Hmm, if you downsample the object to say 1k cells do you get the same error?

**Comment by timoast** [comment]
Closing this now as we have not heard back, but please re-open if you are still having problems

**Comment by woshilushu** [comment]
Hi Emily，

have you solved this problem?
I met the same with my data, but I just have around 500 cells from 5 groups(5 96cells/well ).

**Comment by eregenyi** [comment]
Hi, in case someone comes across this post, I had the same error message. I saw another issue regarding this, and I made the same comment there too, sorry for posting twice. 
So after finding the variable genes with the FindVariableFeatures() function prior to PCA, RunPCA() did not complain any more. Don't know why it did not work without it though.

```
seu <- FindVariableFeatures(object = seu)
seu <- RunPCA(seu, features = VariableFeatures(object = seu) )
```

**Comment by Vikrant-Kumar2019** [comment]
Hi Seurat Team,
I have 98000 cells from 27 samples. 
 
I run the following code
```
Gastricv2.integrated <- IntegrateData(anchorset = Gastricv1.anchors, features.to.integrate = my.genes,  dims = 1:30)
DefaultAssay(Gastricv2.integrated) <- "integrated"
Gastricv2.integrated <- ScaleData(Gastricv2.integrated, features = my.genes, verbose = FALSE)
```
and I able to run it.

However when i run the following code:
`Gastricv2.integrated <- RunPCA(Gastricv2.integrated, npcs = 30, verbose = FALSE)`

I get the following error and warning:
 
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 2000 features requested have zero variance (running reduction without them)...

So I tried running codes again using 9 samples and 49000 cells and I could run successfully.  

Can you help me to figure out why I am not able to run it when I use 27 samples with 98000 cells?

Thanks very much,
Vikrant

**Comment by romanhaa** [comment]
I'm getting the same error in the SCT workflow for data integration, even after down-sampling the whole data set from roughly 90k to 25k cells.

```r
seurat_integrated <- IntegrateData(
  anchorset = seurat_anchors,
  normalization.method = 'SCT'
)

seurat_integrated
# An object of class Seurat 
# 37391 features across 24680 samples within 3 assays 
# Active assay: integrated (3000 features)
#  2 other assays present: RNA, SCT

seurat_integrated <- RunPCA(seurat_integrated)
# Error in irlba(A = t(x = object), nv = npcs, ...) : 
#   max(nu, nv) must be positive
# In addition: Warning message:
# In PrepDR(object = object, features = features, verbose = verbose) :
#   The following 3000 features requested have zero variance (running reduction without them): LYZ, HBA1, HBB, S100A8, HBA2, S100A9, HBD, HBM, CA1, GNLY, RP11-1143G9.4, AHSP, CCL5, CXCL8, HIST1H4C, HLA-DRA, S100A12, CST3, TYROBP, CD74, IGLL1, CA2, FCN1, IGKC, JCHAIN, KLRB1, NKG7, GYPA, IGLC3, LST1, LGALS1, IGLC2, G0S2, GZMB, STMN1, CCL3, FCER1G, AIF1, TUBA1B, CTSS, CCL4, HLA-DPB1, TCL1A, HLA-DPA1, CSTA, HLA-DRB1, FCGR3A, ALAS2, PRDX2, VCAN, MZB1, HMGB2, GZMK, HEMGN, CMC1, IGHM, SNCA, VPREB3, GZMA, HLA-DQA1, FCER1A, TRDC, SAT1, TUBB, SPINK2, GZMH, HLA-DQB1, CD79B, RETN, KIAA0101, S100A11, CD79A, MNDA, GYPB, IFIT1B, LGALS2, BLVRB, COTL1, IFITM3, AZU1, CD14, SERPINA1, CD24, MS4A1, SLC4A1, FGFBP2, TMCC2, TRBC1, CXCL2, SOX4, SLC25A37, IGHA1, IGHG3, IGHG1, CFD, CH17-373J23.1, CCL3L3, LTB, EREG, KLRF1, MS4A6A, FAM178B, IL32, CD8B, KLRD1, HLA-DRB5, IGHD, NEAT1, CST7, MS4A7, S100A4, S100A6, SRGN, FTL, HMGB1, CLIC3, PLAUR, PSAP, UBE2C, IRF8, CTSW, IFI30, RGS2, IFNG, PLD4, PRSS57, VIM, PRF1, HOPX, NA [... truncated]
```

I also tried to run `RunPCA()` with the features specified, as suggested by @eregenyi, but that didn't work either.

With all cells, I already got an error when trying to split the cells by group using `SplitObject()` which I couldn't figure out how to solve.

**Comment by cadyyuheng** [comment]
Hi Seurat Community,

I encountered a similar issue when trying to combine a 700-cell object with a previously combined 4800-cell set. When I tried running "FindVariableFeatures" before running pca, I got the error: "Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : invalid 'x'" 

Sincerely hope someone could share their solution!

Thanks!

**Comment by rahulnutron** [comment]
I encountered the same problem, then checked that the total variable genes are 'zero' (0) due to one unintentional mistake in the pipeline. So please check if total variable genes are present or not. I am not sure but if the cells are from one cell-types only and having few cells in number might cause this issue too.

**Comment by cadyyuheng** [comment]
> I encountered the same problem, then checked that the total variable genes are 'zero' (0) due to one unintentional mistake in the pipeline. So please check if total variable genes are present or not. I am not sure but if the cells are from one cell-types only and having few cells in number might cause this issue too.

Hi Rahul,
Thanks for sharing! May I ask how did you fix when total variable genes not resented if one cell tpe containing few cells?

**Comment by TriLe965** [comment]
I encountered the same issue. So there are genes in my data having variance = 0. This create `NA` in the sparseMatrix after using log normalization. Then when I used `ScaleData`, it created a lot of zeros. I guess when `Seurat` feeded this scaled data to `irlba`, `irlba` removed columns/rows having variance = 0 and the final matrix was smaller than their expected number of left/right singular vectors. Fyi, this is my `data` (a Seurat object). :
```
sum(data@assays$RNA@meta.features$vst.variance == 0)
# 95
table(is.na(data@assays$RNA@counts@x))
# FALSE
# 19332
table(is.na(data@assays$RNA@data@x))
# FALSE  TRUE
# 19332 12870
data <- Seurat::RunPCA(data, npcs = 50, verbose = FALSE)
# Error in irlba(A = t(x = object), nv = npcs, ...) :
#  max(nu, nv) must be positive
```
So I replaced the `NA` in my normalized matrix with 0 (this is not right I know), re-scale the data, and re-run PCA. An it worked.
```
data@assays$RNA@data@x[is.na(data@assays$RNA@data@x)] <- 0
data <- Seurat::ScaleData(data, features = Seurat::VariableFeatures(data))
data <- Seurat::RunPCA(data, npcs = 50, verbose = FALSE)
```
Any better solution?

**Comment by wzhao01** [comment]
> I'm getting the same error in the SCT workflow for data integration, even after down-sampling the whole data set from roughly 90k to 25k cells.
> 
> ```r
> seurat_integrated <- IntegrateData(
>   anchorset = seurat_anchors,
>   normalization.method = 'SCT'
> )
> 
> seurat_integrated
> # An object of class Seurat 
> # 37391 features across 24680 samples within 3 assays 
> # Active assay: integrated (3000 features)
> #  2 other assays present: RNA, SCT
> 
> seurat_integrated <- RunPCA(seurat_integrated)
> # Error in irlba(A = t(x = object), nv = npcs, ...) : 
> #   max(nu, nv) must be positive
> # In addition: Warning message:
> # In PrepDR(object = object, features = features, verbose = verbose) :
> #   The following 3000 features requested have zero variance (running reduction without them): LYZ, HBA1, HBB, S100A8, HBA2, S100A9, HBD, HBM, CA1, GNLY, RP11-1143G9.4, AHSP, CCL5, CXCL8, HIST1H4C, HLA-DRA, S100A12, CST3, TYROBP, CD74, IGLL1, CA2, FCN1, IGKC, JCHAIN, KLRB1, NKG7, GYPA, IGLC3, LST1, LGALS1, IGLC2, G0S2, GZMB, STMN1, CCL3, FCER1G, AIF1, TUBA1B, CTSS, CCL4, HLA-DPB1, TCL1A, HLA-DPA1, CSTA, HLA-DRB1, FCGR3A, ALAS2, PRDX2, VCAN, MZB1, HMGB2, GZMK, HEMGN, CMC1, IGHM, SNCA, VPREB3, GZMA, HLA-DQA1, FCER1A, TRDC, SAT1, TUBB, SPINK2, GZMH, HLA-DQB1, CD79B, RETN, KIAA0101, S100A11, CD79A, MNDA, GYPB, IFIT1B, LGALS2, BLVRB, COTL1, IFITM3, AZU1, CD14, SERPINA1, CD24, MS4A1, SLC4A1, FGFBP2, TMCC2, TRBC1, CXCL2, SOX4, SLC25A37, IGHA1, IGHG3, IGHG1, CFD, CH17-373J23.1, CCL3L3, LTB, EREG, KLRF1, MS4A6A, FAM178B, IL32, CD8B, KLRD1, HLA-DRB5, IGHD, NEAT1, CST7, MS4A7, S100A4, S100A6, SRGN, FTL, HMGB1, CLIC3, PLAUR, PSAP, UBE2C, IRF8, CTSW, IFI30, RGS2, IFNG, PLD4, PRSS57, VIM, PRF1, HOPX, NA [... truncated]
> ```
> 
> I also tried to run `RunPCA()` with the features specified, as suggested by @eregenyi, but that didn't work either.
> 
> With all cells, I already got an error when trying to split the cells by group using `SplitObject()` which I couldn't figure out how to solve.
> 
> EDIT: I'm using Seurat v3.1.1 on R 3.6.1.

Hi romanhaa,

Did you ever figure out the solution to this issue? I'm experiencing the exact same thing on a dataset of 9k cells.

Thanks,
Will

**Comment by ipatop** [comment]
I encountered the same issue. Any news on this? Thanks

**Comment by ehatl** [comment]
I have the same problem with RunPCA

 pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Someone have the solution?????

**Comment by GildasLepennetier** [comment]
One has to do the following before the PCA:
```
GEX <- NormalizeData(GEX, normalization.method = "LogNormalize", scale.factor = 10000)
GEX <- ScaleData(GEX, features = rownames(GEX))
GEX <- FindVariableFeatures(GEX, selection.method = "vst", nfeatures = 2000)
GEX <- RunPCA(GEX, features = VariableFeatures(object = GEX))
```

**Comment by mohama32** [comment]
"The default number of PCs to compute is 50, so you are trying to find more components than there are cells. You need to set npcs to less than the smallest dimension of the dataset"
see here: https://github.com/satijalab/seurat/issues/1914

**Comment by joshrud** [comment]
I encountered the same error running FindTransferAnchors() on 2 objects: one of 16512 cells and the other of 8536 cells.  I suspect they stem from the same bug so I'm reporting here.  In my case, both objects had variable features calculated and 20 dimensions for each PCA, in the integrated assay for each.  Even running with reference.assay = "integrated" and query.assay = "integrated" didn't solve the issue as I had hoped.  

However, running DefaultAssay(seurat_object) <- "integrated" for both objects before running FindTransferAnchors() resolved the issue.  Maybe DefaultAssay() needs to be set to the assay with PCs calculated explicitly before calling RunPCA() on that object.  Calling functions like NormalizeData(), ScaleData(), or FindVariableFeatures() resets the DefaultAssay of an object, so that will also work, but are unnecessary if you've already called them and are encountering this error.  

You can check the assay used to calculated PCs with the following line: 
`seurat_object@reductions$pca@assay.used`

```
a1.anchors <- FindTransferAnchors(reference = a1, 
                                                 query = a2, 
                                                 dims = 1:20,
                                                 reference.assay = "integrated",
                                                 query.assay = "integrated",
                                                 project.query = F)
#Performing PCA on the provided reference using 0 features as input.
#Error in irlba(A = t(x = object), nv = npcs, ...) : 
#  max(nu, nv) must be positive

DefaultAssay(a1) <- "integrated"
DefaultAssay(a2) <- "integrated"
a1.anchors <- FindTransferAnchors(reference = a1, 
                                                 query = a2, 
                                                 dims = 1:20,
                                                 reference.assay = "integrated",
                                                 query.assay = "integrated",
                                                 project.query = F)
#Performing PCA on the provided reference using 2000 features as input.
#Projecting PCA
#Finding neighborhoods
#Finding anchors
#	Found 15636 anchors
#Filtering anchors
#	Retained 8526 anchors
```

**Comment by amr15** [comment]
> Hi Seurat Team,
> I have 98000 cells from 27 samples.
> 
> I run the following code
> 
> ```
> Gastricv2.integrated <- IntegrateData(anchorset = Gastricv1.anchors, features.to.integrate = my.genes,  dims = 1:30)
> DefaultAssay(Gastricv2.integrated) <- "integrated"
> Gastricv2.integrated <- ScaleData(Gastricv2.integrated, features = my.genes, verbose = FALSE)
> ```
> 
> and I able to run it.
> 
> However when i run the following code:
> `Gastricv2.integrated <- RunPCA(Gastricv2.integrated, npcs = 30, verbose = FALSE)`
> 
> I get the following error and warning:
> 
> Error in irlba(A = t(x = object), nv = npcs, ...) :
> max(nu, nv) must be positive
> In addition: Warning message:
> In PrepDR(object = object, features = features, verbose = verbose) :
> The following 2000 features requested have zero variance (running reduction without them)...
> 
> So I tried running codes again using 9 samples and 49000 cells and I could run successfully.
> 
> Can you help me to figure out why I am not able to run it when I use 27 samples with 98000 cells?
> 
> Thanks very much,
> Vikrant

Hi Vikrant,
Did you figure out how to get around this?  I am having a similar issue.
Thanks!
Anu

**Comment by zji90** [comment]
I have encountered the same error when integrating 36 samples. I figured out decreasing k.weight in 'IntegrateData' help solve the problem.

The previous code that went wrong was:
IntegrateData(anchorset = anchors)

I changed it into this and it works:
IntegrateData(anchorset = anchors,k.weight=50)

I haven't tried it yet but I guess changing other parameters in 'FindIntegrationAnchors' and 'IntegrateData' related to number of anchors (k.*) may also help.

Maybe it's worthwhile to automatically determine the number of anchors in Seurat program so that the function does not break down? Or determine the optimal number based on data itself?

**Comment by Shuming13** [comment]
I had the same problem and I solved it by changing the npcs value.
It's set to 50 by default. I changed it to npcs = a value that's smaller than my column numbers and it worked. Hope this helps.

**Comment by Hrovatin** [comment]
I had the same problem. For me it seems to always work for integration of dataset pairs, but fails when adding the 3th dataset on a merged pair, regardless of data order/which batches are used. I am working on a small test dataset so may not be very variable - I have tried some of the above suggestions, but that did not help (I made sure to add HVGs, changed dims and k.weight, and removing less variable datasets).

```
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /mnt/home/icb/karin.hrovatin/miniconda3/envs/scib-pipeline/lib/libmkl_rt.so.2

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] matrixStats_0.61.0 reticulate_1.22    SeuratObject_4.0.4 Seurat_4.1.0      
[5] optparse_1.7.1    

loaded via a namespace (and not attached):
  [1] nlme_3.1-157          spatstat.sparse_2.1-0 RcppAnnoy_0.0.19     
  [4] RColorBrewer_1.1-3    httr_1.4.2            repr_1.1.4           
  [7] sctransform_0.3.3     tools_4.1.3           utf8_1.2.2           
 [10] R6_2.5.1              irlba_2.3.5           rpart_4.1.16         
 [13] KernSmooth_2.23-20    uwot_0.1.11           mgcv_1.8-40          
 [16] DBI_1.1.2             lazyeval_0.2.2        colorspace_2.0-3     
 [19] gridExtra_2.3         tidyselect_1.1.2      compiler_4.1.3       
 [22] cli_3.2.0             plotly_4.10.0         scales_1.1.1         
 [25] spatstat.data_2.1-4   lmtest_0.9-40         ggridges_0.5.3       
 [28] pbapply_1.5-0         goftest_1.2-3         stringr_1.4.0        
 [31] pbdZMQ_0.3-7          digest_0.6.29         spatstat.utils_2.3-0 
 [34] base64enc_0.1-3       pkgconfig_2.0.3       htmltools_0.5.2      
 [37] parallelly_1.30.0     fastmap_1.1.0         htmlwidgets_1.5.4    
 [40] rlang_1.0.2           shiny_1.7.1           generics_0.1.2       
 [43] zoo_1.8-9             jsonlite_1.8.0        spatstat.random_2.2-0
 [46] ica_1.0-2             dplyr_1.0.8           magrittr_2.0.3       
 [49] patchwork_1.1.1       Matrix_1.4-1          Rcpp_1.0.8.3         
 [52] IRkernel_1.3          munsell_0.5.0         fansi_1.0.3          
 [55] abind_1.4-5           lifecycle_1.0.1       stringi_1.7.6        
 [58] MASS_7.3-56           Rtsne_0.15            plyr_1.8.7           
 [61] grid_4.1.3            parallel_4.1.3        listenv_0.8.0        
 [64] promises_1.2.0.1      ggrepel_0.9.1         crayon_1.5.1         
 [67] deldir_1.0-6          miniUI_0.1.1.1        lattice_0.20-45      
 [70] IRdisplay_1.1         cowplot_1.1.1         splines_4.1.3        
 [73] tensor_1.5            pillar_1.7.0          igraph_1.3.0         
 [76] uuid_1.0-4            spatstat.geom_2.4-0   reshape2_1.4.4       
 [79] future.apply_1.8.1    codetools_0.2-18      leiden_0.3.9         
 [82] glue_1.6.2            evaluate_0.15         data.table_1.14.2    
 [85] png_0.1-7             vctrs_0.4.0           httpuv_1.6.5         
 [88] polyclip_1.10-0       spatstat.core_2.4-2   gtable_0.3.0         
 [91] getopt_1.20.3         RANN_2.6.1            purrr_0.3.4          
 [94] tidyr_1.2.0           scattermore_0.8       future_1.24.0        
 [97] assertthat_0.2.1      ggplot2_3.3.5         mime_0.12            
[100] xtable_1.8-4          later_1.3.0           survival_3.3-1       
[103] viridisLite_0.4.0     tibble_3.1.6          cluster_2.1.3        
[106] globals_0.14.0        fitdistrplus_1.1-8    ellipsis_0.3.2       
[109] ROCR_1.0-11

**Comment by SDJ7007** [comment]
Hello, I am having the same issue of rthe RUNPCA command,
Is there any solution to it?
My data is the CMO from Cell Plex and I am using the intial codes from 10X Genomcis and tehn continuing with the iintegrated codes from Seurat,
pbmc.singlet <- RunPCA(pbmc.singlet, features = VariableFeatures(pbmc.singlet))
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive

I have tried all the solutions mentioned in this thread but still receiving this error.
Is there any way I can resolve this error please?

Thank you

**Comment by john-j-oh** [comment]
Hi, Seurat Team and all on this post,

Honestly, I have no idea how I fixed this. After trying to figure out what was happening for a few hours, I decided to reapproach it fresh in the morning. I restarted R, cleared all of the history and etc, and reran the commands I saved from the previous night.

Surprisingly, it did not encounter the same error as the RunPCA error. Maybe a hard reset of the program might be helpful for those still stuck.

I hope that helps...!

**Comment by hddlty** [comment]
> 我遇到了同样的问题。因此，我的数据中有一些基因的方差 = 0。这将在使用日志规范化后在 sparseMatrix 中创建。然后当我使用 时，它创建了很多零。我猜当将此缩放数据馈送到 时，删除了方差 = 0 的列/行，并且最终矩阵小于其预期的左/右奇异向量数量。仅供参考，这是我的（修拉对象）。:`NA``ScaleData``Seurat``irlba``irlba``data`
> 
> ```
> sum(data@assays$RNA@meta.features$vst.variance == 0)
> # 95
> table(is.na(data@assays$RNA@counts@x))
> # FALSE
> # 19332
> table(is.na(data@assays$RNA@data@x))
> # FALSE  TRUE
> # 19332 12870
> data <- Seurat::RunPCA(data, npcs = 50, verbose = FALSE)
> # Error in irlba(A = t(x = object), nv = npcs, ...) :
> #  max(nu, nv) must be positive
> ```
> 
> 因此，我将归一化矩阵中的矩阵替换为 0（我知道这是不正确的），重新缩放了数据，并重新运行了 PCA。它奏效了。`NA`
> 
> ```
> data@assays$RNA@data@x[is.na(data@assays$RNA@data@x)] <- 0
> data <- Seurat::ScaleData(data, features = Seurat::VariableFeatures(data))
> data <- Seurat::RunPCA(data, npcs = 50, verbose = FALSE)
> ```
> 
> 还有更好的解决方案吗？

I also found some problems after reading the whole data frame, which may be caused by some problems in the previous standardization. assay$RNA$var.feature is empty, which may affect the subsequent varfeature analysis. I believe that there are many people who may also have this question, please look for the answer in the previous standardization step.

**Comment by taoshengqiansui** [comment]
I encountered this problem too, and I found that the reason it happened was because the row names of the matrix were missing when I read the matrix with fread() and did not use column_to_rownames to set the row names
