### ISSUE TITLE
Diversion in Data from Tutorial in JackStraw and UMAP 

### ISSUE THREAD

**Issue by FireflyFrye** [satijalab/seurat#1789]
Hi all,

I'm new to Seurat and to R in general, and was working through the tutorials for Seurat to learn how to use it. I've hit a bit of a snag when it comes to running JackStraw. Until I come to the JackStraw section, my pictures and output looks pretty much the same as what's on the tutorial. However, once I get to Jackstraw, my graph shape looks the same-ish but my p values are very different. Then once I get to the RunUMAP section, my graph looks different. The shapes and relatively distributions of gene clusters are fairly similar, but they're distributed differently on the graph. I think that somehow the tutorial writers had cleaned up their data either more or less than I did at that step but I've gone through it several times and can't figure out where I diverge from the tutorial. 

**I did see a prior forum [post](https://github.com/satijalab/seurat/issues/1700) stating that it is normal for UMAP graphs to look somewhat different on different systems but wasn't sure if it was the same for JackStraw. If so, please ignore the below text. If not, more info is below:** 

Things I've tried: 
- went back and ran the data with the pbmc <-ScaleData(pbmc,vars.to.regress=percent.mt step because I wasn't sure if the writers of the tutorial had done that to generate their data 
- Installed the "jackstraw" package 
- done the same thing from scratch to make sure I didn't just skip a step 

Here's the code I've entered. I think it's exactly the same as the code on the tutorial but it's entirely possible I'm missing something: 

```
> pbmc.data<-Read10X(data.dir="filtered_gene_bc_matrices/hg19")
> pbmc<-CreateSeuratObject(counts=pbmc.data,project="pbmc3k",min.cells=3,min.features=200)
> pbmc[["percent.mt"]]<-PercentageFeatureSet(pbmc,pattern="^MT-")
> head(pbmc@meta.data,5)
> VlnPlot(pbmc,features=c("nFeature_RNA","nCount_RNA","percent.mt"),ncol=3)
> plot1<-FeatureScatter(pbmc,feature1="nCount_RNA",feature2="percent.mt")
> plot2<-FeatureScatter(pbmc,feature1="nCount_RNA",feature2="nFeature_RNA")
> CombinePlots(plots=list(plot1,plot2))
   #This one also looked the same as the one on the Seurat tutorial
> pbmc<-subset(pbmc,subset=nFeature_RNA>200 & nFeature_RNA<2500 & percent.mt<5)
> pbmc<-NormalizeData(pbmc,normalization.method="LogNormalize",scale.factor=10000)
> pbmc<-FindVariableFeatures(pbmc,selection.method="vst",nfeatures=2000)
> top10<-head(VariableFeatures(pbmc),10)
   #again, looked the same 
> plot1<-VariableFeaturePlot(pbmc)
> plot2<-LabelPoints(plot=plot1,points=top10,repel=TRUE)
When using repel, set xnudge and ynudge to 0 for optimal results
> plot2<-LabelPoints(plot=plot1,points=top10,repel=TRUE,xnudge=0,ynudge=0)
> all.genes<-rownames(pbmc)
> pbmc<-ScaleData(pbmc,features=all.genes)
> pbmc<-RunPCA(pbmc,features=VariableFeatures(object=pbmc))
> pbmc<-JackStraw(pbmc,num.replicate=100)
> pbmc<-ScoreJackStraw(pbmc,dims = 1:20)
> JackStrawPlot(pbmc,dims=1:15)
```
Prior to that point everything looks the same as in the Seurat tutorial, but after that things start to diverge. Is there something simple that I'm missing? 

I'm working on:
MacOS Mojave v10.14.3
Seurat v 3.0.0
R v 3.6.0

Thank you all for your patience in helping a total noob!

**Comment by satijalab** [comment]
It is possible for these values to change slightly, based on the exact computing platform. Your code is correct, so it is not something I would worry about. I will close the issue but if you are particularly concerned you can post your exact outputs.
