### ISSUE TITLE
CalcVarExpRatio (subscript out of bounds) 

### ISSUE THREAD

**Issue by amr15** [satijalab/seurat#179]
Has anyone seen "Error in object@dr[[i]]@cell.embeddings[cells.use, , drop = FALSE] :subscript out of bounds "  when using the CalcVarExpRatio function?

**Comment by dawe** [comment]
I'm getting the same error when using CalcVarExpRation and AlignSubspace

**Comment by ghoshal** [comment]
Have you tried installing the development version of Seurat? I am using that and I am not getting any errors while running these functions.

Bibaswan

**Comment by gauravsinghrathore** [comment]
I tried with development version of Seurat also but it gives same error. Any comments??

**Comment by amr15** [comment]
Actually I'm having this problem again

**Comment by amr15** [comment]
If you use this version of the Seurat Package, it seems to work fine: install_url('https://github.com/satijalab/seurat/archive/v2.0.1.tar.gz')

**Comment by gauravsinghrathore** [comment]
It was mainly problem with mac os High Sierra.  The development version of Seurat was not getting compiled despite of trying all the suggested fixes. I later try to run on Linux and everything went perfect.  Thank you. :)

**Comment by mojaveazure** [comment]
@gauravsinghrathore For your installation issues, try updating your compilers. The ones that come with macOS aren't suitable for R as-is. CRAN offers some [here](https://cloud.r-project.org/bin/macosx/tools/), and you can get them through the [Homebrew](https://brew.sh)  package manager (highly recommended)

**Comment by ankushjad** [comment]
I'm getting the same error when using CalcVarExpRation and AlignSubspace; "Error in object@dr[[i]]@cell.embeddings[cells.use, , drop = FALSE] :subscript out of bounds ".
I tried v2.0, v2.3.3, v2.4 but getting same error, help me please?
