### ISSUE TITLE
IntegrateData and FindIntegrationAnchors default anchor.features count

### ISSUE THREAD

**Issue by gilstel** [satijalab/seurat#1790]
From what I gather, if samples have a batch effect then IntegrateData (Seurat version 3) will shift the expression levels to relieve this effect.
I followed the step described in the vignette (https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html).

In subsequent steps, like plotting with VlnPlot or DoHeatmap, the functions will not find an expression value in the "integrated" assay for some genes and therefore use the expression value in the "RNA" assay.  This is a bit confusing.

I looked into why this is happening and found that IntegrateData uses the anchor.features that were created in FindIntegrationAnchors.  The default anchor.features count in FindIntegrationAnchors is 2000.  I am guessing that this number is used since the previous step (FindVariableFeatures) sets the variable gene count to 2000 by default.  Why is this number selected?
When I try to take the entire gene count for a sample (leaving all other parameters as their default values) almost all the genes are found to be variable for a single sample.    What will happen if I use all genes instead in FindIntegrationAnchors and IntegrateData?
What is the rationale for selecting this feature count for variable gene selection and subsequent integration steps?
If 2000 is the mandatory gene count, is there any other solution for plot creation in subsequent steps?

Many thanks

**Comment by sheep-liu** [comment]
This question has borthered me for a while , if there is just 2000 genes for the following analysis ,is it too little to retain the information of the data set?If you have any understanding of this question, expect to discuss with you

**Comment by satijalab** [comment]
See issue #1803  for a response to this question.

**Comment by samcwj** [comment]
> From what I gather, if samples have a batch effect then IntegrateData (Seurat version 3) will shift the expression levels to relieve this effect.
> I followed the step described in the vignette (https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html).
> 
> In subsequent steps, like plotting with VlnPlot or DoHeatmap, the functions will not find an expression value in the "integrated" assay for some genes and therefore use the expression value in the "RNA" assay. This is a bit confusing.
> 
> I looked into why this is happening and found that IntegrateData uses the anchor.features that were created in FindIntegrationAnchors. The default anchor.features count in FindIntegrationAnchors is 2000. I am guessing that this number is used since the previous step (FindVariableFeatures) sets the variable gene count to 2000 by default. Why is this number selected?
> When I try to take the entire gene count for a sample (leaving all other parameters as their default values) almost all the genes are found to be variable for a single sample. What will happen if I use all genes instead in FindIntegrationAnchors and IntegrateData?
> What is the rationale for selecting this feature count for variable gene selection and subsequent integration steps?
> If 2000 is the mandatory gene count, is there any other solution for plot creation in subsequent steps?
> 
> Many thanks

Hi gilstel,

I'm new to this, and am currently facing the same issue with the DoHeatMap function. It does not find an expression value in the "integrated" assay for many of my genes. May I ask how you used the expression value in the "RNA" assay instead? Is there a code or parameter I can use to do this?

Thank you!

samcwj
