### ISSUE TITLE
Following the vignette gives an error when analyzing scATAC-seq

### ISSUE THREAD

**Issue by sameet** [satijalab/seurat#1791]
I am trying to follow the vignette as given at [https://satijalab.org/seurat/v3.0/atacseq_integration_vignette.html].  When I try to generate the activity matrix I get an error.  To clarify I trying to use this with _D. rerio_.  However, I keep getting an error 

    Error in `$<-.data.frame`(`*tmp*`, "peak", value = ":-") :
      replacement has 1 row, data has 0
    In addition: Warning message:
    In .Seqinfo.mergexy(x, y) :
      The 2 combined objects have no sequence levels in common. (Use
       suppressWarnings() to suppress this warning.)

When I digged into the code, it seems that on line 195 you need at add
    
    GenomeInfoDb::seqlevelsStyle(peaks.gr) <- "UCSC"

This takes care of the "replacement as 1 row, data as 0" error part.  However, at the `GenomicRange::distanceToNearest` call, I keep getting the error:

    Error: logical subscript contains NAs

Is there a way around this.

**Comment by satijalab** [comment]
We will be introducing a series of new methods to calculate Gene Activities in the very near future. I'm going to close this issue for now, but please reopen if your issue is not solved in the next update.

**Comment by sameet** [comment]
Any hint on when the next update will be?

**Comment by satijalab** [comment]
https://twitter.com/satijalab/status/1151142658984873984

**Comment by ErinJF** [comment]
@sameet Im also interested. I ran into the same problem using Danio_rerio.GRCz11.96.gtf. 
Looking forward to the update.

**Comment by eandrew3** [comment]
I'm having the same issue with _D. rerio_ in version 3.1.1 with `GenomicRange::distanceToNearest`. Any solutions to the NA issue?
