### ISSUE TITLE
Do.Clean in SubsetData

### ISSUE THREAD

**Issue by hgb1111** [satijalab/seurat#1792]
In Seurat v2, I routinely subsetted seurat objects and used the do.clean=T feature to ensure that I was doing a fresh analysis on the cells selected. 

How can I do that in seurat v3? I am struggling to find a way to easily subset from an existing seurat object and start a fresh analysis on those cells.

**Comment by andrewwbutler** [comment]
Hi,

You can run `DietSeurat` after subsetting specific cells to clear out much of the same information that the `do.clean` option did in v2.

**Comment by crazyhottommy** [comment]
I have the same question, I do not see how `DietSeurat` works here. DietSeurat can remove the counts, or data matrix, but how to remain the subsetted counts and data matrix?

**Comment by timoast** [comment]
In `DietSeurat` you choose what to keep, so if you do:

```r
DietSeurat(object, counts = TRUE, data = TRUE, scale.data = FALSE)
```

You will keep the counts and data, and remove scale.data, dimension reductions, and graphs. Note that to remove the dimension reductions and graphs you currently need to install from the develop branch.

**Comment by crazyhottommy** [comment]
Thanks Tim! I understand that. The problem is that if I do `subsetData`, the counts and data matrix will be still the full matrix as before the subsetting.

```r
RandomSubsetData<- function(object, rate, random.subset.seed = NULL, do.clean = TRUE, ...){
        ncells<- nrow(object@meta.data)
        ncells.subsample<- round(ncells * rate)

        set.seed(random.subset.seed)

        selected.cells<- sample(colnames(object), ncells.subsample)
        # can not do do.clean =T for V3..
        object<- SubsetData(object, cells.use =  selected.cells, 
                            ...)
        return(object)
}

pbmc_small
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne

subset_pbmc<- RandomSubsetData(pbmc_small, rate = 0.8)
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne

```
should contain only 80* 0.8 = 64 cells in the matrix. 
DietSeurat(subset_pbmc) will not keep the subsetted matrix with only 64 cells

**Comment by crazyhottommy** [comment]
Also, it seems `subsetData` is deprecated... now Seurat suggest using `subset`, does `subset` receive `do.clean = TRUE`?

**Comment by timoast** [comment]
This is because you have `cells.use` instead on `cells` in the SubsetData function, so the argument isn't being matched correctly in `SubsetData`. We don't have `do.clean` anymore in `subset` or `SubsetData`, you'll have to subset and then use `DietSeurat` if you want to clean out old slots in the object

**Comment by crazyhottommy** [comment]
Thanks! that's true... I am trying to update my old functions in Seuratv2... but the arguments of V3 have changed a lot.. hard for me to catch sometimes.

**Comment by crazyhottommy** [comment]
Note that the `meta.data` seems to be unchanged after `DieatSeurat`
