### ISSUE TITLE
RunPCA returns different results

### ISSUE THREAD

**Issue by Zepeng-Mu** [satijalab/seurat#1793]
Hi, I am using PCA using two different parameters:

```r
res.seu <- RunPCA(
  object = res.seu,
  npcs = 15
)
```
and
```r
res.seu <- RunPCA(
  object = res.seu,
)
```

Then I run the following code:
```r
res.seu <- RunUMAP(res.seu, dims = 1:15)
res.seu <- FindNeighbors(res.seu, dims = 1:15, k.param = 30)
res.seu <- FindClusters(res.seu, resolution = 0.8)

DimPlot(
  object = res.seu,
  reduction = "umap",
  pt.size = 0.5,
  label = T,
  cols = myCol
) + NoLegend()
```

I got two different results:
<img width="699" alt="Screen Shot 2019-07-03 at 4 08 10 PM" src="https://user-images.githubusercontent.com/21952317/60625580-d7fb8980-9dad-11e9-8031-4224497d03a6.png">
This is the result when `npcs = 50` in `RunPCA`.

<img width="703" alt="Screen Shot 2019-07-03 at 4 09 47 PM" src="https://user-images.githubusercontent.com/21952317/60625621-f497c180-9dad-11e9-8639-0212605aa5c3.png">

This is the result when `npcs = 15` in `RunPCA`.

The two results are really different, although I used only 15 PCs in the following steps.
This concerns me a little bit because I would imagine that no matter how many PCs are returned, the first PCs should be the same.

I guess that the PCA algorithm uses some approximation to speed up PCA, therefore the result is different if I ask for a different number of PCs to return.

My question is, does this significantly influence the downstream analysis? If there is a difference between 15 and 50, things because trickier to find the best number of PCs to use.

Thanks!

**Comment by satijalab** [comment]
I think there can be miniscule numerical differences in the results - but these should not materially affect the downstream  analysis (your clusterings appear identical). the UMAP plots may differ, but you will also get slightly different UMAP plots if you select different random seeds.
