### ISSUE TITLE
Filtering FindMarkers with Curated Gene Database

### ISSUE THREAD

**Issue by jonathanzhang53** [satijalab/seurat#1794]
Many FindMarkers() results will return genes that are expressed heavily in all clusters involved for some reason and other genes are not very useful for phenotyping because of the lack of literature or maybe it's not a marker.

I was wondering if there [could be/is] functionality to allow for further subsampling for FindMarkers() with a curated list of gene names. Therefore, DE genes could be filtered for the ones that are markers/novel genes.

I am currently phenotyping the immune microenvironment and in my curated list I would have some TFs and all the clusters of differentiation to filter with.

I can probably write a function for this but this could also be a suggestion for an enhancement.

**Comment by satijalab** [comment]
Thanks for the suggestion.  FindMarkers accepts a `features` argument which will only perform  DE on  a certain set of features, and should address this.
