### ISSUE TITLE
Old input name of fonction are not consider but no error...

### ISSUE THREAD

**Issue by PernilleYR** [satijalab/seurat#1796]
Dear author, 

I sadly realised that for many of your functions the input name have changed (RunTSNE dims.use become dims for example) however if we run with the old name no error or warning is sent but it is also not taking as an input.

Many person, such as me, might have adapted their code from the previous version to the new one and therefore this type of problem can happen very often ...  

Maybe it would be great to send a warning telling that this is the old input name to avoid this kind of situation next time you change some input names (all my tSNEs are done on 5 first dimension of PCA and not what I wanted for example..) 

Thanks! 

Best, 

Pernille

**Comment by satijalab** [comment]
We agree this would help avoid confusion, and is on our list  of future enhancements (see #1495). Thanks for your feedback.
