### ISSUE TITLE
cannot install seurat version 3 in R 3.5.1

### ISSUE THREAD

**Issue by chazdm** [satijalab/seurat#1798]
Hi,

I get several errors when I try to install the new seurat version 3. I have pasted these below. Any advice would be greatly appreciated. Thank you. 

Error : package ‘colorspace’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package ‘scales’
* removing ‘/gpfs/home/cdmelloc/anaconda/envs/U87study/lib/R/library/scales’
ERROR: dependency ‘scales’ is not available for package ‘ggplot2’
* removing ‘/gpfs/home/cdmelloc/anaconda/envs/U87study/lib/R/library/ggplot2’
ERROR: dependency ‘ggplot2’ is not available for package ‘phateR’
* removing ‘/gpfs/home/cdmelloc/anaconda/envs/U87study/lib/R/library/phateR’
ERROR: dependency ‘ggplot2’ is not available for package ‘Seurat’
* removing ‘/gpfs/home/cdmelloc/anaconda/envs/U87study/lib/R/library/Seurat’

The downloaded source packages are in
        ‘/tmp/RtmpJAImqd/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("Seurat", dependencies = TRUE) :
  installation of package ‘scales’ had non-zero exit status
2: In install.packages("Seurat", dependencies = TRUE) :
  installation of package ‘ggplot2’ had non-zero exit status
3: In install.packages("Seurat", dependencies = TRUE) :
  installation of package ‘phateR’ had non-zero exit status
4: In install.packages("Seurat", dependencies = TRUE) :
  installation of package ‘Seurat’ had non-zero exit status

**Comment by mojaveazure** [comment]
Reading the error message, it looks like you had an issue installing colorspace. I'd suggest starting there for your debugging.

**Comment by chazdm** [comment]
Ok I will give that a try
