### ISSUE TITLE
DotPlot

### ISSUE THREAD

**Issue by shokohirosue** [satijalab/seurat#1799]
May I ask two questions re. DotPlot?

1) Does it use normalized (not scaled) data as an input?
2) How is the average expression scaled? I would like to know how to interpret negative values shown in the legend.

Thank you.

**Comment by satijalab** [comment]
You can see the exact commands using: `View(DotPlot)`

1. Yes, we use the normalized data to calculate the average expression.
2. We use the `scale` function in R (on the averaged expression values) so that we can examine relative values across cell types.
