### ISSUE TITLE
FindClusters problem 

### ISSUE THREAD

**Issue by cartal** [satijalab/seurat#18]
Hi again,

Similar to the previous problem with the PCA, FIndClusters also gives an error message:

My command: 

B3 <- FindClusters(B3, pc.use = 1:3, resolution = 0.6, print.output = 0, save.SNN = T, plot.SNN = T)

The error message:

Error in my.knn$nn.index[, 1:(k.param - 1)] : subscript out of bounds

Is this also a bug?

Looking forward to hearing from you.

**Comment by andrewwbutler** [comment]
So what I think is causing this is that you have (or rather the default) k.param is larger than the number of cells in your dataset. I went ahead and made the default behavior to change k.param to the number of cells - 1 and it now prints a more informative warning. You should consider setting k.param in the FindClusters function call though as it will influence the clustering more significantly when you have a small number of cells.

**Comment by cartal** [comment]
Oh yes, I can see that now. 

I'm using a Seurat object with 22 cells. When I changed the k.param to other numbers (i.e: 21, 19, 17), I still got an error:

Error in norm_coords(layout, -1, 1, -1, 1) : 
  `layout' should have 2 or three columns

Perhaps I'm missing something obvious here, but I can't tell if its my data or not.

**Comment by andrewwbutler** [comment]
No it's not obvious and it's not your data. We use the tSNE coordinates to plot the SNN graph and if you haven't computed the tSNE yet, it throws that error. I added a better warning message which now allows the main computation to continue even if you can't plot the SNN. To get the SNN plot though, call RunTSNE() first to store the tSNE coordinates and then call FindClusters() with plot.SNN = T. Thanks for pointing these out by the way.

**Comment by cartal** [comment]
Ok, now I have managed to run those steps of the tutorial. Thanks a lot for the rapid support. I will keep in mind your suggestions.
