### ISSUE TITLE
Help with Classifying Cell Type 

### ISSUE THREAD

**Issue by FireflyFrye** [satijalab/seurat#1801]
I'm working through the Seurat tutorials and trying to classify cells based on their canonical markers. Is there an automated way to do this? I saw something about a ClassifyCells command in earlier versions of R but couldn't find it in this version.

Or do I need to just manually look up the top 10 or so markers for every cluster to determine what cell type? And if so, any reference data source that's helpful for this? It just seems like a lot of the markers are expressed by multiple different types of cells and I get a bit lost in terms of trying to classify them.

Thanks!

**Comment by satijalab** [comment]
Please see the label transfer (i.e. classification) section in the second tab: https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html
