### ISSUE TITLE
How to export mean counts, logFC, ajusted-p.value of all genes in each cluster.

### ISSUE THREAD

**Issue by hffqyd** [satijalab/seurat#1802]
Hello, I'm using Seurat for single cell RNA sequencing analysis.

I've done t-SNE analysis and got seperate clsuters of single cell. Now I'm wanting to export mean counts, logFC, ajusted-p.value of all genes in cells of each cluster, like the results in *outs/analysis/diffexp/kmeans_4_clusters/differential_expression.csv* given by Cell Ranger count.

How can I get this result from Seurat?

Thank you very much for your help.

**Comment by MattTreadwell** [comment]
Haven't tested this but you can try the following from the tutorial

```
write.csv(pbmc.markers %>% group_by(cluster) , filename="export.csv")
```

**Comment by satijalab** [comment]
You can use the FindMarkers command to perform differential expression for each cluster, you can see more here: https://satijalab.org/seurat/v3.0/de_vignette.html

**Comment by lc822** [comment]
Thanks - is it possible using the FindMarkers to output the fold-changes and p-values for the genes even if they aren't significant?  I haven't been able to work this out.

**Comment by MattTreadwell** [comment]
@lc822 adjust the `logfc.threshold`, `min.pct`, and `min.diff.pct` parameters for `FindMarkers`. Keep in mind, it will increase the compute time.

**Comment by lc822** [comment]
Thanks @MattTreadwell - does the min.diff.pct need to be adjusted from the default of -Inf?

**Comment by MattTreadwell** [comment]
@lc822 `min.diff.pct` does not need to be changed from `-Inf` if you want to use all genes. You could set it to a non-zero fraction to speed up compute time, but some genes will be lost.
