### ISSUE TITLE
Questions about integrating data

### ISSUE THREAD

**Issue by sheep-liu** [satijalab/seurat#1803]
I am a beginner and recently i am following the tutorial on the website to repeat the process.And when i follow the tutorial of Integrating stimulated vs. control PBMC datasets,i find after i use FindIntegrationAnchors function and IntegrateData(),the dim of the integrated data is 2000,13999.At first I thought maybe i made a mistake which leads to obtain just 2000 genes.I find that the default value of a parameter, anchor.features, of the function FindIntegrationAnchors() is 2000 after checking the official instructions.And i realize this is the problem.If i change the value of anchor.features,then the dim of integrated data will change,too.So if i do not change the value and just use the default value 2000,this means that in the following analysis, i have only 2000 genes.So is it too little for the following data analysis?If I understand the meaning of the function wrong, please let me know, this problem has been bothering me for a long time.

**Comment by satijalab** [comment]
We and others have found that working on a subset of variable genes is sufficient for clustering  and integration analyses. Of course, the remaining genes are still present in the object, in the original RNA assay, so no data has been lost. You can also increase the number of features if you wish.

**Comment by sheep-liu** [comment]
> We and others have found that working on a subset of variable genes is sufficient for clustering and integration analyses. Of course, the remaining genes are still present in the object, in the original RNA assay, so no data has been lost. You can also increase the number of features if you wish.

Can you tell me why these 2000 genes can be used to analyze subsequent identification? Are they all differential genes?Thank you very much and look forward to your reply.
