### ISSUE TITLE
Managing cluster labels

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#1804]
Hi folks,

Im wondering if there is a way to change colours of the cluster labels? To make for example the colour of the label the same as the colour of cluster, and to be nicely repeled.

Thank you in advance for your help.

Amel

**Comment by andrewwbutler** [comment]
Hi Amel,

One way of doing this is to use the `LabelClusters` function. E.g.

```R
p <- DimPlot(pbmc_small)
LabelClusters(p, id = "ident", color = "red")
```

This changes all the label colors to red. If you want them to match the color of the cluster, you can provide a vector of colors to the `color` argument. To get the cluster colors, you can pull the colors from the plot object.

```R
LabelClusters(p, id = "ident", color = unique(ggplot_build(p)$data[[1]]$colour))
```
