### ISSUE TITLE
FindMarkers filters p values

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#1806]
It seems that FindMarkers() doesn't filter genes on p-values. In other words, if you don't set a stringent set of filters like logFC or min.diff.pct, you might get genes that are not significant based on your test but still included in the output data.frame.
I have been manually filtering the output files. But is it possible to add a p-value filter option to FindMarkers() ?

Thanks

**Comment by satijalab** [comment]
We do not support this, because we often find it useful to see p-values even for  genes that lie outside 
 of a user-defined cutoff. It is very easy to use the subset the resulting marker list based on any user defined cutoff using the `subset` function in R.
