### ISSUE TITLE
Converting a Seurat 2 object into a Seurat 3 object?

### ISSUE THREAD

**Issue by Biogitte** [satijalab/seurat#1807]
Dear all,

Is there a way of converting a Seurat 2 object into a Seurat 3 object? If so, how does it work?

Thanks,

Best wishes, Birgitte

**Comment by samuel-marsh** [comment]
Hi Birgitte,

Not part of the Dev team but you can check out the documentation of the `UpdateSeuratObject` in the Seurat documentation.
`updated_seurat_object <- UpdateSeuratObject(object = old_seurat_object)`

Best,
Sam

**Comment by Biogitte** [comment]
Thank you! It works!

I did, however, in the meanwhile find another way to solve my issue. My actual goal was to extract one (S1) of two samples (i.e., S1 and S2) present in the old Seurat 2 object, and then perform a new analysis (from with pre-processing, dimension reduction, etc.) on that individual sample. This is how I did it, in case anyone could use it:

```
# load the Seurat 2 object
load("~/data/old_object.Rdata")

# create a Seurat 3 object from the raw.data slot in the Seurat 2 object
ms <- CreateSeuratObject(counts = old_object@raw.data, project = "ms",  min.cells = 3, min.features = 200)

# calculate proportion of mitochondrial transcripts and add it to the metadata
ms[["percent.mt"]] <- PercentageFeatureSet(ms, pattern = "^mt-|^MT-|^mtrnr|^MTRNR")

# split seurat object based on orig.ident (i.e., S1 and S2)
obj.list <- SplitObject(ms, split.by = "orig.ident")

# check the Seurat objects present in obj.list
obj.list

# extract the wanted sample object
S1 <- obj.list$S1

# then continue with the preprocessing
```
