### ISSUE TITLE
Merging of distinct data sets

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#1809]
Hi,

The integration procedure in v3 relies on the assumption that at least a subset of cells share the same biological state. Therefore, if you're looking at two completely distinct datasets with no overlap, I wouldn't recommend running `IntegrateData`.

_Originally posted by @andrewwbutler in https://github.com/satijalab/seurat/issues/1487#issuecomment-488741231_

@andrewwbutler ; The same question. What would be the best strategy then. I am trying to integrate scRNA seq data between two cell types. One of the cell types say neurons are already publicly available. I want to merge it with immune cell scRNA seq data that I have. I want to use this combined matrix with CellPhoneDB, a pipeline that detects receptor-ligand interactions. CellPhoneDB requires one single matrix. What would be the best idea as I don't expect any common cell type subsets between them? Just merge and go ahead with the usual normalization?

**Comment by yuhanH** [comment]
Hi,
I think you could use `merge` function for your two seurat objects.

**Comment by saeedfc** [comment]
@yuhanH Merge and then do SCTransform? Will that be a good idea? Thanks for the help.

**Comment by yuhanH** [comment]
I think it is good idea. 
If not work, you could try SCTransform separately and then merge.
For this method, when you merge two objects, the scale.data slots will not be merged , and you need to merge it your self and import it into scale.data slot

**Comment by kvshams** [comment]
Is there any way to create the single object after the object is split?

`object.list <- SplitObject(object.harmony.integrated, split.by = "Treatment")
object.list <- RunALRA(object.list$Treatment1)
object.list <- RunALRA(object.list$Treatment2)
`
as the `merge()` function is not preserving the `alra`/`pca`/ or `umap`

**Comment by GouQiao** [comment]
> 

Hi yuhan, 

I also met the same problem: after merging, how to import the scale.data slots into merged objects.
Do you have good way to do this?

Best.

**Comment by yuhanH** [comment]
hi @GouQiao 
When your data is normalized by `SCTransform`, `merge` function will merge you scale.data.
When your data is normalized by `LogNormalize`, you would better just re-run `ScaleData` on the merged object.
`ScaleData` is used to center (mean = 0) and scale (sd = 1) the data slot. Merging scale.data from two different datasets may not be valid. While, if you want to import scale.data to your merged object, you can manually merge two scale.data slots into a merged matrix and then add the matrix to seurat obejct.

**Comment by QianLLLL** [comment]
Hi @saeedfc, I'm almost doing the same thing. Merge two datasets together and analyze cell-cell interaction. When I merged  two datasets together, I saw this warning message:
_1: In CheckDuplicateCellNames(object.list = objects) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
2: Attempting to merge an SCTAssay with another Assay type 
Converting all to standard Assay objects.

I have no idea about _Converting all to standard Assay objects_. Do I need to do SCTransform again after merging?

Best.

**Comment by yuhanH** [comment]
hi @QianLLLL 
It seems that your two objects have the overlapped cell names. You could rename them before merging them.
`RenameCells` can be used.
You don't need to re-run SCTransform after merging.

**Comment by QianLLLL** [comment]
Hi @yuhanH 

Thank you for your reply! I think the _merge_function has helped me to do the rename automatically. But I came up with another question for the following downstream analysis. May I do Cellchat analysis based on the merged gene matrix? Cellchat is a pipeline that detects receptor-ligand interactions based on the expression difference of L-R genes.

**Comment by yuhanH** [comment]
hi @QianLLLL 
The merged gene matrix can be used for Cellchat. Yet, I think you would better use log-normalized data for Cellchat.

**Comment by QianLLLL** [comment]
hi @yuhanH 

Thank you! I'm thinking of using the SCT assay for Cellchat analysis, as the SCT normalization method also log-normalizes and scales the dataset. Do you think it makes sense?

**Comment by yuhanH** [comment]
hi @QianLLLL 
Right. Sequenced-depth controlled log counts are stored the SCT data slot, so you can use them for Cellchat. 
But the residuals in the scaele.data are not suggested

**Comment by QianLLLL** [comment]
hi @yuhanH 

Thank you for pointing out _residuals in scale. data_. I have no idea about it before. I'll do more search about it.
