### ISSUE TITLE
Reproducible way to convert Seurat2 object to anndata or loom

### ISSUE THREAD

**Issue by mxposed** [satijalab/seurat#1812]
Hi

I have a bunch of Seurat 2 objects, and I want to import them to scanpy.
I use Seurat v2.3.4

While converting to anndata (like here https://satijalab.org/seurat/v2.4/conversion_vignette.html)
I get 
```
Error in np_array(X@i) :
  no slot of name "i" for this object of class "dgeMatrix"
```

While converting to loom (like here https://satijalab.org/loomR/loomR_tutorial.html) I get
```
Transposing input data: loom file will show input columns (cells) as rows and input rows (features) as columns
This is to maintain compatibility with other loom tools
Error in dataset_create_pl$set_chunk(chunk_dims) : HDF5-API Errors:
    error #000: H5Pdcpl.c in H5Pset_chunk(): line 868: all chunk dimensions must be positive
        class: HDF5
        major: Invalid arguments to routine
        minor: Out of range
In addition: Warning messages:
1: In loomR::create(filename = filename, data = from@raw.data[, cell.order],  :
  NAs introduced by coercion
2: In dataset_create_pl$set_chunk(chunk_dims) :
  During conversion, the following issues occured: H5T_CONV_EXCEPT_RANGE_LOW
```
I used loomR `master` and `develop` branches, and `anndata v0.6.22.post1`

I would be glad if you could point me into the right direction

**Comment by satijalab** [comment]
We have updated our conversion pipelines in Seurat v3. We would recommend first converting  the v2 object to v3 with UpdateSeuratObject. After that you can convert to loom (which can be read into scanpy)
