### ISSUE TITLE
Error in FindTransferAnchors (FastSparseRowScaleWithKnownStats)

### ISSUE THREAD

**Issue by massonix** [satijalab/seurat#1816]
I have a scRNA-seq that I want to annotate using the Linnarson's brain cell atlas. To that end, I am using the Label Transfer pipeline. This is my code

```{r}
# Connect to loom object
brain_loom <- connect(filename = "data/TM_brain_ref.loom")
brain_loom 

# Convert to Seurat
brain_seu <- as.Seurat(brain_loom)

# Pre-processing
brain_seu <- NormalizeData(
  object = brain_seu, 
  normalization.method = "LogNormalize",
  scale.factor = 10000, 
  display.progress = TRUE
)
brain_seu <- FindVariableFeatures(brain_seu, selection.method = "vst", nfeatures = 2000)
brain_seu <- ScaleData(brain_seu)
brain_seu <- RunPCA(brain_seu, features = VariableFeatures(object = brain_seu))
saveRDS(brain_seu, "results/R_objects/brain_reference_Seurat.rds")

# Project data
anchors <- FindTransferAnchors(reference = brain_seu, query = epid_seu, dims = 1:30, project.query = TRUE)
```
However, I get the following error:

Performing PCA on the provided query using 2000 features as input.
Projecting PCA
Error in SparseRowVar2(mat = reference.data, mu = feature.mean, display_progress = FALSE) : 
  Not an S4 object.

Do you have any idea of what could be the problem?

Thanks a lot

Ramon

**Comment by andrewwbutler** [comment]
Hi Ramon,

Did you mean to set the `project.query = TRUE` option and if so, have you run PCA on `epid_seu`?

Generally, we don't recommend this option but it can be useful in rare cases where the query dataset has a much larger cell number, but the reference dataset has a unique assay for transfer. If you are going to use this option, you need to be sure you've run a PCA on the query before hand.

**Comment by massonix** [comment]
Hi Andrew,

Thanks for your reply! I indeed ran PCA and it progressed. However, now I'm stucked in another error:

Error in SNNAnchor(k_matrix = k.matrix, anchor_only = anchor.only) : 
  std::bad_alloc

It is the same issue as #1706 . If it is indeed a memory problem, there is not much I can do anymore, because I am running it on the cluster of our sequencing facility. On the other hand, I was watching Rahul's 10X webinar today, and he mentioned a new capability called "turbo" that was available for Seurat 3.1. Do you know if that could help with this?

Thanks a lot

R

**Comment by andrewwbutler** [comment]
It may be a memory limitation. Could you provide some details on the size of the objects you're working with and the amount of available memory on the clusters? You could also try downsampling the objects before running to check if the size is the issue. 

The 'turbo' mode mainly includes improvements to the integration workflow (`FindIntegrationAnchors` and `IntegrateData`), not the data transfer workflow but you can view the new vignettes [here](https://satijalab.org/seurat/v3.0/integration.html) if you're interesting in checking them out.

**Comment by massonix** [comment]
I will try to downsample, thanks for the idea!
