### ISSUE TITLE
could not find function "SetIfNull"

### ISSUE THREAD

**Issue by andrea-de-micheli** [satijalab/seurat#1817]
Hello,

I get this error after trying to run ScaleData on an integrated dataset (Seurat v3).

Error in SetIfNull(x = data.use, default = GetAssayData(object = object,  : 
  could not find function "SetIfNull"

Any ideas?

Thank you.

**Comment by andrea-de-micheli** [comment]
The error only seem to appear of Seurat datasets that have been converted using UpdateSeuratObject(). I can't figure out if its related.

**Comment by mojaveazure** [comment]
`SetIfNull` is not present in Seurat v3's codebase. I'm guessing you have v2 or one of the beta versions of v3 loaded, not v3 proper. Please try updating your Seurat version, then run again.

**Comment by andrea-de-micheli** [comment]
I did just that and it doesn't solve the issue.

**Comment by andrea-de-micheli** [comment]
@mojaveazure I have re-installed Seurat version 3.0.2 on a clean R background and on a new machine and I still get the error. What should do?
Thank you for your support.

**Comment by mojaveazure** [comment]
That's unusual, could you send your `sessionInfo`, the code you ran, and the object or a downsampled version of the object that reproduces the error?

**Comment by VBRay** [comment]
SetIfNull is present in Seurat v2's codebase. I found it in the source codes of Seurat-2.3.3. SetIfNull is present in the R script named untilities_internal, line 414. Hope it helps you out. @andrea-de-micheli
