### ISSUE TITLE
Memory Problems for Matrix Operations - Even in Development Version

### ISSUE THREAD

**Issue by onurdanaci** [satijalab/seurat#1818]
Hi,
I have a seurat object of the dimensions "18312 x 219995". And, trying to normalize this matrix, 

pbmc <- NormalizeData(object = pbmc, normalization.method = "CLR"),

yields the error code:

"Normalizing across features
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105"

I've seen, from past issues in this github, people are having similar errors when they were dealing any sort of sparse matrix related linear algebraic operations such as CCA. They were either advised to get more memory, or, install new, development (beta) versions of Seurat. And, I did. I was using 450gb ram from cluster, I moved to a high_mem cluster that can take 1+ tb ram. I deleted everything, and all the dependencies, and installed up-to-date packages alongside with Development version Seurat ( packageVersion("Seurat")=‘3.0.3.9010’). Nothing seems to be working.

My case is rather bizarre. Because, the current memory usage is only around 14-15gb, even though I have tons more under my hand. Yet, it somehow leaks memory and kills the process. I tried trimming the data and matrices as much as possible. But, I can't go beyond that.

What would you suggest me to do?
Thank you for your time.
Onur

**Comment by satijalab** [comment]
We have not seen this before, and I don't quite understand the cause. The error can arise from CCA (which can have large memory requirements) on huge datasets, but not NormalizeData (which has minimal memory requirements).

This is likely some other broad issue with your installation (or your dataset), and is not a memory issue. Can you check the following things?

1. Can you run NormalizeData on any dataset (ie pbmc3k?), and get through the rest of the tutorial?
2. Can you run NormalizeData on a smaller subset of your data.

**Comment by onurdanaci** [comment]
Hi,
1. Yes, I can normalize on pbmc3k:
"> pbmc
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features)
> pbmc=NormalizeData(pbmc,normalization.method="CLR")
Normalizing across features
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 09s"

And, yes, afterwards it gets through the rest of the tutorial and give me all the necessary outputs (pbmc3k_umap.png, pbmc3k_final2.rds)

2) Also yes. If I take small batches out of my combined object (comb.counts), turn it into a Seurat object, then normalize it with "CLR" method, everything works fine.

Right now I am basically taking small batches, normalizing them, and concatenating the outputs. 
Like A=[A1,A2] --> A1=normalize(A1) , A2=normalize(A2) --> A_new=[A1,A2]. But, if you use this method for any ancillary example, the difference matrix norm between "normalize(A)" and "A_new" is  non zero, and it's a bit worrisome. I mean, consider you have the following scale due to log transformation:
norm( normalize(A) ) = 21 , norm( A_new)=20.9, but norm( normalize(A) - A_new ) = 0.3 

So, from normalizing in batches and concatenating later you might not be getting the same result.

**Comment by repeatpipettor** [comment]
Hello,

I am running into the same issue with a Seurat object of similar dimensions, and am wondering if you ever came across a solution. I am currently running the development version (3.1.5.9005). 

Thanks very much.

**Comment by yuhanH** [comment]
HI, 
We don't suggest you run CLR normalization for RNA. The CLR method will output a dense matrix, so it may cause a memory issue.

**Comment by moverm0210** [comment]
I have the same issue with normalization of 230k cells

**Comment by yuhanH** [comment]
@moverm0210 
do you use CLR method for RNA normalization?

**Comment by moverm0210** [comment]
> @moverm0210 do you use CLR method for RNA normalization?

I used normalization.method = "LogNormalize"

**Comment by yuhanH** [comment]
hi @moverm0210 
is your counts matrix sparse? What are the dimension of the matrix? How many non-zero element there?
