### ISSUE TITLE
Paper to cite

### ISSUE THREAD

**Issue by chent5** [satijalab/seurat#1819]
Hi,

I am using Seurat (version 2.3.4) to analyze my data. I see on your website mentioning:
If you use Seurat in your research, please considering citing:
    Butler et al., Nature Biotechnology 2018.
    Stuart*, Butler*, et al., Cell 2019

But I didn't use CCA... What I used is pbmc3k_tutorial.Rmd you provided online. I am wondering which paper I should cite when preparing a manuscript?

Thank you so much for developing this package!

**Comment by satijalab** [comment]
Unfortunately we do not have the resources to write individual manuscripts for each feature in Seurat.  We request that if you use Seurat2,  please consider citing Butler et al., Nature Biotechnology 2018.
