### ISSUE TITLE
UpdateSeuratObject fails on pre v1.3 Seurat objects

### ISSUE THREAD

**Issue by b-dawes** [satijalab/seurat#182]
Hello,

My lab group has been using the Seurat package since it's release. We have some old Seurat objects that we would like to convert to the new format using UpdateSeuratObject. The method works fine for most objects, however some of our very old files are failing. The error message is:
```
Error in UpdateSeuratObject(dropseq) : 
  no slot of name "snn.sparse" for this object of class "seurat"
```

Prior to version 1.3, Seurat did not have slots for snn. I haven't thoroughly tested but I assume this issue would affect any pre v1.3 Seurat object. Do you have any plans to extend UpdateSeuratObject to work with these older objects?

Best,
Brian

**Comment by andrewwbutler** [comment]
Hi Brian,

This should be fixed on the develop branch now if you want to try installing that version. 
See [this page](http://satijalab.org/seurat/devinstall.html) for install instructions.

**Comment by b-dawes** [comment]
Thanks Andrew, the fix worked for me.
