### ISSUE TITLE
DoHeatmap() one cluster only

### ISSUE THREAD

**Issue by deliasoto** [satijalab/seurat#1820]
Hello,

I'm trying to make a Heatmap showing only one cluster. I have FindMarkers for that cluster agains all the rest and I would like to see only the top genes in my cluster of interest in a heat map. So what is not working is setting up top genes for that cluster only. I am using this function %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
from the tutorial but since I have only one cluster it seems group_by does not work
It does create a list of genes, but without the gene symbols, like this:
> head(GermTop10Markers, n = 5)
  p_val avg_logFC pct.1 pct.2 p_val_adj
1     0  3.027280 0.998 0.182         0
2     0  2.765348 0.997 0.575         0
3     0  1.954083 0.999 0.494         0
4     0  1.845386 0.999 0.660         0
5     0  1.698031 0.969 0.059         0

The original list with the differential expressed genes looks Ok
> head(GermDEMarkers, n = 5)
        p_val avg_logFC pct.1 pct.2 p_val_adj
CD9             0  3.027280 0.998 0.182         0
SLC25A5     0  2.765348 0.997 0.575         0
CTSV           0  1.954083 0.999 0.494         0
AKR1B1        0  1.845386 0.999 0.660         0
TKTL1          0  1.698031 0.969 0.059         0

Is there a way of filtering genes from just one cluster? I'm not very experience using Seurat so any type of help will help me. Oh I'm using Seurat v3 BTW.
Thanks!

**Comment by yuhanH** [comment]
You could add a new column containing gene name, and then your code will work.
`GermDEMarkers$gene <- rownames(GermDEMarkers)`

**Comment by deliasoto** [comment]
Thank you yuhanH but that is not what I'm trying to do. I need to filter top markers from a list of DE markers generated comparing one cluster agains the rest. How could I do that? function %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) does not work.

**Comment by yuhanH** [comment]
I know.  The first step you could add gene column to the marker table.
`GermDEMarkers$gene <- rownames(GermDEMarkers)`
Then, you could put the threshold you like.
`GermDEMarkers%>%filter(p_val < 0.001, avg_logFC >2)`
You can find more information about `filter` [here](https://dplyr.tidyverse.org/reference/filter.html)
