### ISSUE TITLE
Trouble installing Seurat v3 at command line, using R-v3.4.1

### ISSUE THREAD

**Issue by mvinyard** [satijalab/seurat#1821]
Hi there, I am really excited to use this new version of Seurat. However, I can't seem to get around these errors that pop up during installation - most of them seem to be concerning the dependencies of Seurat. Some of the errors are quite similar to what others are experiencing, however, it seems that they had additional errors which were the root cause of their issues and thus, I have not found a solution. My apologies if I missed it and it has already been answered. 

After submitting (at the command line in R, using version 3.4.1): install.packages('Seurat')

also installing the dependencies ‘scales’, ‘ggplot2’, ‘ggrepel’, ‘sctransform’

#### left out some bulky installation messages - doesn't seem to throw any errors here and the beginning of my problems start below:

* installing *source* package ‘scales’ ...
** package ‘scales’ successfully unpacked and MD5 sums checked
** libs
g++  -I/home/unix/mvinyard/.conda/envs/scATAC/lib/R/include -DNDEBUG  -I"/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/Rcpp/include" -I/home/unix/mvinyard/.conda/envs/scATAC/include   -fpic  -I/home/unix/mvinyard/.conda/envs/scATAC/include  -c RcppExports.cpp -o RcppExports.o
/bin/sh: g++: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘scales’
* removing ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/scales’
* restoring previous ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/scales’
* installing *source* package ‘ggplot2’ ...
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘scales’ 0.4.1 is being loaded, but >= 0.5.0 is required
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/ggplot2’
* restoring previous ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/ggplot2’
* installing *source* package ‘ggrepel’ ...
** package ‘ggrepel’ successfully unpacked and MD5 sums checked
** libs
g++  -I/home/unix/mvinyard/.conda/envs/scATAC/lib/R/include -DNDEBUG  -I"/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/Rcpp/include" -I/home/unix/mvinyard/.conda/envs/scATAC/include   -fpic  -I/home/unix/mvinyard/.conda/envs/scATAC/include  -c RcppExports.cpp -o RcppExports.o
/bin/sh: g++: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘ggrepel’
* removing ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/ggrepel’
* installing *source* package ‘sctransform’ ...
** package ‘sctransform’ successfully unpacked and MD5 sums checked
** libs
g++  -I/home/unix/mvinyard/.conda/envs/scATAC/lib/R/include -DNDEBUG  -I"/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/Rcpp/include" -I"/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/RcppEigen/include" -I/home/unix/mvinyard/.conda/envs/scATAC/include   -fpic  -I/home/unix/mvinyard/.conda/envs/scATAC/include  -c RcppExports.cpp -o RcppExports.o
/bin/sh: g++: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘sctransform’
* removing ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/sctransform’
ERROR: dependencies ‘ggrepel’, ‘sctransform’ are not available for package ‘Seurat’
* removing ‘/xchip/cga_home/mvinyard/.conda/envs/scATAC/lib/R/library/Seurat’

The downloaded source packages are in
	‘/tmp/Rtmp8uSxX7/downloaded_packages’
Warning messages:
1: In install.packages("Seurat") :
  installation of package ‘scales’ had non-zero exit status
2: In install.packages("Seurat") :
  installation of package ‘ggplot2’ had non-zero exit status
3: In install.packages("Seurat") :
  installation of package ‘ggrepel’ had non-zero exit status
4: In install.packages("Seurat") :
  installation of package ‘sctransform’ had non-zero exit status
5: In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status

**Comment by mojaveazure** [comment]
The error message states
> /bin/sh: g++: command not found

It looks like your compiler can't be found. Please ensure you have a C++ compiler installed for your system
