### ISSUE TITLE
Empty seurat object from initial tab-delimited count matrix

### ISSUE THREAD

**Issue by Biogitte** [satijalab/seurat#1822]
Dear all,

I want to read in a count matrix from a tab-delimited txt file and create a Seurat 3 object. My attempts do, however, result in an empty object.

The format of the tab-delimited txt file (only a few cells and features are shown here):

```
GENE	GCTATGTCACCC	GCCTTACCACTA    
0610007N19Rik	0	0
0610007P14Rik	0	1
2810430I11Rik	0	0
```

The txt file is read into R: 
`> sample.raw <- read.table(file = "~/data/sample.txt.gz", sep = "\t")`

The dimensions of the count matrix in R is 14711  obs. and 2001 variables. 
It should, however, consist of 13011 obs. (i.e., features) across 1343 variables (i.e., cells). 

The Seurat 3 object is created:
`> my.data <- CreateSeuratObject(counts = sample.raw, project = "ms", min.cells = 3, min.features = 200)`

Which results in the following warning:

```
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion
```
and an empty object:

```
> my.data
An object of class Seurat 
0 features across 0 samples within 1 assay 
Active assay: RNA (0 features)
```

Does anyone know how to solve this issue? I am aware it has something to do with NA's, but am not sure how to solve it in regards to Seurat.

Thanks,

Best wishes, Birgitte

**Comment by Biogitte** [comment]
I solved it like this:

```
> sample.raw <- read.table(file =  "~/data/sample.txt.gz", header = TRUE, row.names = 1, sep = "\t", as.is = TRUE)

> my.data <- CreateSeuratObject(counts = sample.raw, project = "ms", min.cells = 3, min.features = 200)
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')

> my.data
An object of class Seurat 
12119 features across 1344 samples within 1 assay 
Active assay: RNA (12119 features)

```

**Comment by jjyotikataria** [comment]
Hi. But Seurat object takes data from both the files features and barcodes both. The command shown above just takes care of one of them.

**Comment by jjyotikataria** [comment]
@Biogitte @troels @mxposed @zeehio Please help.

Output:
> pbmc.data <- Read10X(data.dir = "2002009/sc_results/CWB_GEX_results_GEX/filtered_feature_bc_matrix")
> pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
> pbmc
An object of class Seurat
0 features across 0 samples within 1 assay
Active assay: RNA (0 features, 0 variable features)



Input:

> list.files("2002009/sc_results/CWB_GEX_results_GEX/filtered_feature_bc_matrix")
[1] "barcodes.tsv.gz" "features.tsv.gz" "matrix.mtx.gz"
