### ISSUE TITLE
How to use ZIFA in Seurat?

### ISSUE THREAD

**Issue by CocoKecheng** [satijalab/seurat#1823]
The following vignette mentioned that we could store the results of custom dimensional reduction techniques such as MDS and zero-inflated factor analysis(ZIFA). Could you give an example on how to run ZIFA in R and store in Seurat? Thanks a lot!

https://satijalab.org/seurat/v3.0/dim_reduction_vignette.html

**Comment by andrewwbutler** [comment]
Hi,

Unfortunately we can't advise on how to run other group's software but after you've run ZIFA, one of the output results should be a matrix that represents your cells in a lower dimensional space (e.g. a matrix that is cells x dims). You can then add that into your Seurat object as demonstrated in the vignette you link to. E.g.

```R
colnames(zifa.output) <- paste0("ZIFA", 1:2)
object[["zifa"]] <- CreateDimReducObject(embeddings = zifa.output, key = "ZIFA_", assay = DefaultAssay(object))
```
