### ISSUE TITLE
Differential expression analysis and data export with integrated Seurat v3 project: "RNA" vs "integrated" slot?

### ISSUE THREAD

**Issue by qiuyuguo** [satijalab/seurat#1824]
Dear Seurat team,

I would like to thank you for making such a great toolkit and did a great job in making tutorial as well.

I've been performing DE analysis referring to your tutorial https://satijalab.org/seurat/v3.0/immune_alignment.html

I noticed that when you plot the scatter plot between conditions, you used the data from the slot "RNA" instead of "integrated":
t.cells <- subset(immune.combined, idents = "CD4 Naive T")
Idents(t.cells) <- "stim"
avg.t.cells <- log1p(AverageExpression(t.cells, verbose = FALSE)$RNA)

I also noticed that under t.cells@assay, you have both "RNA" and "integrated" slots, where the "RNA" corresponds to the original normalized counts from individual data sets before integration, while "integrated" corresponds to those after integration. In this case, wouldn't you want to plot with the data from the "integrated" slot? 

Also, when you run the DE analysis with
b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL", verbose = FALSE)
, did you use the data from the "RNA" or the "integrated" slot?

Obviously when you integrate, you used only 2000 features by default, which results in the "integrated" slot has only 2000 features. Does it mean the UMAP plot of integrated data set were done based on the 2000 features?

Finally, as I'm trying to run Monocle and URD using integrated data sets by Seurat, the only way I can think of is to export the integrated normalized counts from an integrated Seurat object, which would be data from the "integrated" slot. The caveat again is that there are only limited amount of features available. However, I understand that those selected features are those with max variance among the data sets therefore representative. Is that correct?

Many thanks!

**Comment by dwucsf** [comment]
From my understanding, there isn't an easy way to import integrated data into Monocle right now.

**Comment by royfrancis** [comment]
@qiuyuguo From [FAQs](https://satijalab.org/seurat/faq.html),

>4. I’ve run an integration analysis and/or sctransform and now want to perform a differential expression analysis. Which Assay should I use?
>
> We recommend running your differential expression tests on the “unintegrated” data. By default this is stored in the “RNA” Assay. There are several reasons for this.
>
>* The integration procedure inherently introduces dependencies between data points. This violates the assumptions of the statistical tests used for differential expression.
>* DE and integration are not currently supported with sctransform but will be soon.

**Comment by qiuyuguo** [comment]
@royfrancis Thanks for pointing it out. This is helpful.

I wonder if it is reasonable to apply 'integrated' data to Monocle 2.

**Comment by qiuyuguo** [comment]
@dwucsf I was able to run Monocle 2 with data from the 'integrated' slot after transform it with 2^. However I wasn't so sure if this is a valid way to do it. However since the integrated data can be used in generating dimensional reduction such as tSNE and UMAP, maybe it's not so bad with Monocle?

**Comment by satijalab** [comment]
You can certainly export integrated data for loading into monocle. 

If you want to export more integrated features, you can set the features.to.integrate parameter in IntegrateData.

You can also calculate a UMAP in Seurat and export this to Monocle for downstream analysis. Since monocle3 learns trajectories on the UMAP embedding (at least based on our understanding), this is likely the best way to combine the workflows. How to import an externally-derived UMAP into a Monocle CDS object is a question for the Monocle developers.
