### ISSUE TITLE
Split.by view in DimPlot 

### ISSUE THREAD

**Issue by dwucsf** [satijalab/seurat#1825]
I have 7 different batches that I've merged, each labeled with a unique name in "orig.ident." I'm running the following code:

DimPlot(seur_ob, reduction = "umap", label = FALSE, label.size = 4, split.by = "orig.ident")

I get plot attached. Is it possible to get each UMAP plot as its own individual image?

[UMAP-splitby-origident.pdf](https://github.com/satijalab/seurat/files/3388449/UMAP-splitby-origident.pdf)

**Comment by andrewwbutler** [comment]
It's possible to undo the facetting after returning the plot (see example [here](https://stackoverflow.com/questions/40218814/extract-single-plot-from-ggplot-with-facet-grid) ) but it might be easier to subset your original object and make the individual plots you want up front. E.g.
```R
ob.list <- SplitObject(seur_ob, split.by = "orig.ident")
plot.list <- lapply(X = ob.list, FUN = function(x) {
    DimPlot(x, reduction = "umap", label = FALSE, label.size = 4)
})
```
