### ISSUE TITLE
HoverLocator lost label

### ISSUE THREAD

**Issue by vikkki** [satijalab/seurat#1828]
Hi,

I'm trying to add label of cluster on the plot with , but it seems these part of parameter is not catched by `HoverLocator`, then no label is shown on the plot. and also the x-axis label and title has seemilar satuation.
```
plot = DimPlot(sc, reduction = "umap",
            pt.size = input$umap_point_size, 
            label = TRUE, 
            cols = getPalette(length(levels(sc))))+ ggtitle(label = "UMAP")
    HoverLocator(plot = plot, information = FetchData(sc, vars = c("ident","UMAP-1","UMAP-2","nFeature_RNA","nCount_RNA")))
```
I tried to use `plot_ly()` with `DimPlot`, but I haven't find a way to pass information I want to show when hover. Is the lost of label because that `HoverLocator` is now just for `FeaturePlot`? And is there other ways to have label on interactive DimPlot?

Many thank for your time:)

Xiao

**Comment by andrewwbutler** [comment]
Hi Xiao,

It looks like you're right that the x-axis label, title, and labels aren't preserved in the `HoverLocator`. We will look into fixing and post back here with any updates.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by shaniAmare** [comment]
Hi @mojaveazure ,

Can you please check - looks like this bug has been reintroduced?

Thanks, Shani.
