### ISSUE TITLE
data = CreateSeuratObject(raw.data = data, min.cells = 1, min.genes = 1) Error in object@raw.data[, cells.use] :    invalid or not-yet-implemented 'Matrix' subsetting

### ISSUE THREAD

**Issue by xuebaliang** [satijalab/seurat#1830]
Hello, recently I use the seurat package to analysis my single cell data. The input data is a dgCMatrix. My seurat version is 2.3.0, and my Matrix package version is 1.2.17. But I do not know why I get this error! Thus ask for solution. Thanks!

**Comment by andrewwbutler** [comment]
Hi,

If you're just starting out with a new Seurat analysis, I would highly recommend starting with the most recent version (3.0.2). That should resolve the issue but if you need to use an older version, could you provide a reproducible example?

**Comment by xuebaliang** [comment]
Thanks for your reply. I have solved this problem. Ok, I will use the seurat3.0 in the future. But I advise that you can write a complete tutorial on the official website. Begin with data preprocessing for different data format, and so on.
