### ISSUE TITLE
Featureplot blend.threshold

### ISSUE THREAD

**Issue by ahoffrichter** [satijalab/seurat#1832]
Dear seurat-team & -community,

I am trying to understand what the numbers in the colour threshold legend actually mean, and what exactly I'm changing, when I adjust the `blend.threshold` parameter. 

I am using two sets of marker genes, of which I create the mean of logcounts. 

`genes <- c("SLC17A7", "SLC17A6", "GRIN1", "GRIN2B", "GLS", "GLUL")`
`boost_seurat[["glut"]]  <- colMeans(as.matrix(boost_seurat@assays$RNA@data[genes,]))`

`genes <- c("SLC2A1", "GABBR1", "GABBR2", "GAD2", "GAD1")`
`boost_seurat[["GABA"]] <- colMeans(as.matrix(boost_seurat@assays$RNA@data[genes,]))`

I am using then 

`FeaturePlot(boost_seurat,features = c("GABA", "glut"), label = F, blend = TRUE, order = TRUE, blend.threshold = 0.1)`

with different values for `blend.threshold`

![000025](https://user-images.githubusercontent.com/23699647/61286597-77b01300-a7c3-11e9-81e7-9ba2d2548d59.png)

I'm wondering now, what do the numbers on the legend mean. 
Is this just a "ratio" between the two features? And is the blend.threshold in percent? for example 0.5 would mean, only cells that are above that percentile are depicted with color?
I'm a bit lost, because I just have no idea, what I'm seeing here.
I hope somebody can help me and clear things a bit up :) 
Thanks in advance!

**Comment by yuhanH** [comment]
Hi, 
0.5 means the positive percentile. If the expression is above 50% cells, it will be highlighted.

**Comment by ahoffrichter** [comment]
But how can I have highlighted cells in color threshold:1 ? That would mean these cells have a higher expression than 100% of the cells (so higher than all cells)? 

And what does 1 to 10 on the color threshold mean? 
Is it just a relative scale? 
And if it's a relative scale is it (in my case) 1 (green) = lowest expression in "glut", 10 (green) = highest expression in "glut", 1(red) = lowest expression in "GABA", 10 (red) = highest expression in (GABA)
or is it combined 1 (red & green) = lowest expression in GABA/glut, 10(red & green) = highest expression GABA/glut?

**Comment by yuhanH** [comment]
You are right. It is not exactly positive percentile, but propositional to it. We will clarify it in the next version.
1 to 10 is a relative scale for either genes respectively.
It is (in your case) 1 (green) = lowest expression in "glut", 10 (green) = highest expression in "glut", 1(red) = lowest expression in "GABA", 10 (red) = highest expression in (GABA)
