### ISSUE TITLE
could not find function "PrepSCTIntegration"

### ISSUE THREAD

**Issue by RobertKSuter** [satijalab/seurat#1833]
Hi,

After making sure to install the developer version of Seurat using:

```{r}
library(devtools)
devtools::install_github(repo = "satijalab/seurat", ref = "develop")
```
I am unable to find the function PrepSCTIntegration()

```{r}
library(Seurat)
int.features <- SelectIntegrationFeatures(
  object.list = int.list,
  nfeatures = 3000
)

int.list <- PrepSCTIntegration(
  object.list = int.list,
  anchor.features = int.features,
  verbose = FALSE)
```
# Error Message:
Error in PrepSCTIntegration(object.list = int.list, anchor.features = int.features,  : 
  could not find function "PrepSCTIntegration"

Everything else seems to be working fine.

Thanks!
Rob

**Comment by ChaDuss** [comment]
Hello,
We have the same error message, what is the solution ? 

> pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)
> pbmc.list <- PrepSCTIntegration(object.list =  pbmc.list), anchor.features = pbmc.features)
Error in PrepSCTIntegration(object.list = , anchor.features = pbmc.features) : 
could not find function "PrepSCTIntegration"

thanks !
Chaduss

**Comment by RobertKSuter** [comment]
Hi Chaduss,

I ended up just restarting my rsession and reloading the libraries - this fixed the problem for me. 

Thanks!
Rob
