### ISSUE TITLE
FindTransferAnchors error

### ISSUE THREAD

**Issue by Saospark** [satijalab/seurat#1834]
I was trying to transfer gene expression values from scRNA-seq data to a MERFISH dataset. The dimension for scRNA-seq is 19109x9485 and the dimension for MERFISH is 134x73641. When I ran FindTransferAnchors I got a warning message during  Extracting within-dataset neighbors like this:

Warning message:
In RunCCA.Seurat(object1 = reference, object2 = query, features = features,  :
  More than 10% of provided features filtered out. Please check that the given features are present in the scale.data slot for both the assays provided here and that they have non-zero variance.

Any suggestion for how to fix it? The parameters are here.
 merfishscrna.anchors<- FindTransferAnchors(reference = scrna, query = merfish, reduction="cca", dims = 1:20)

**Comment by timoast** [comment]
Hi, this is not actually an error (just a warning). As the warning says, you should check that all the MERFISH genes are present in the scale.data in the scRNA-seq, as more than 10% of the requested genes were not present
