### ISSUE TITLE
SCT assay after integration workflow

### ISSUE THREAD

**Issue by bio-la** [satijalab/seurat#1836]
Hi, thanks for providing the new vignette on integration after performing SCT. 
Can I ask for clarification on the workflow:

1. SCT normalize data for each seurat object to be integrated
2. Prepare for integration and integrate as in https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html#standard-workflow
3. RunPCA (and UMAP for visualization) on the default assay which is now [["integrated"]]
4. FindNeighbors and FindClusters (on PCA calculated from slot [["integrated"]], calculated from SCT normalized data)
5. Set default assay to SCT and FindMarkers on SCT@data (SCT@scale.data is empty after integration!) using cluster identities found on the integrated data (through step 4). 

Is this correct?

I'm also referencing some closed issues related to this.
#1613 
#1611 

thanks.

**Comment by royfrancis** [comment]
I have a related question to this. After sctransform based integration approach, there are assays 'SCT' and 'integrated'. What's the difference? And where in this workflow do I correct for mito.percent, cell cycle etc? Show I run sctransform again on 'integrated' using argument 'vars.to.regress'?

**Comment by nicodemus88** [comment]
In reference to @royfrancis question, what I did was performing the QC first before sctransform. My current workflow is:

1) Create Seurat object
2) QC by filtering out cells based on `percent.mito`
3) SCT normalize each dataset specifying the parameter `vars.to.regress = percent.mito`
4) Integrate all datasets
5) Run PCA, UMAP, FindNeighbors (on default assay which is "integrated")
6) Change default assay to "RNA"; normalize then generate FeaturePlots and perform differential expression analysis

I'm hoping Seurat developers can clarify if my workflow is correct. In addition to that, I wanted to ask if we should perform another round of SCTransform on the integrated dataset, either in the standard workflow or the SCTransform integration workflow.

**Comment by satijalab** [comment]
Thanks - yes the workflow @nicodemus88 lists is the one we recommend. Do not run a second round of SCTransform on the integrated assay.

The only additional point I would make is that for point 6, you can also use the SCT assay instead of the RNA assay (this represents the SCT normalized values for each dataset, prior to integration).

**Comment by jiangshan529** [comment]
> Thanks - yes the workflow @nicodemus88 lists is the one we recommend. Do not run a second round of SCTransform on the integrated assay.
> 
> The only additional point I would make is that for point 6, you can also use the SCT assay instead of the RNA assay (this represents the SCT normalized values for each dataset, prior to integration).

Hello, for DEG analysis, I believe we need to set the array to "RNA", right?
