### ISSUE TITLE
Error: no slot of name "dr" for this object of class "Seurat"

### ISSUE THREAD

**Issue by naomi-croft** [satijalab/seurat#1838]
myPCA <- allsample.data.seurat@dr$tsne@cell.embeddings

Hi I have tried running the above command, which worked previously, but I have now made several updates. Now there is an error message which says:
Error: no slot of name "dr" for this object of class "Seurat"

Any suggestions? I don't know the new term to replace dr with

**Comment by mojaveazure** [comment]
Hi,

Dimensional reduction information is stored in [DimReduc objects](https://github.com/satijalab/seurat/wiki/DimReduc). You can access the object by using the [double subset `[[` operator](https://satijalab.org/seurat/essential_commands.html)

```R
allsample.data.seurat[['tsne']]
```

Cell embedding values can be accessed directly with the [`Embeddings`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/Embeddings) function
