### ISSUE TITLE
Error using WhichCells in a for loop

### ISSUE THREAD

**Issue by ahoffrichter** [satijalab/seurat#1839]
Hello, 

I'm am having some troubles using the `WhichCells()` within a for loop. 
My code looks like this: 

```{r}
genes <- c("KIF22", "RPGRIP1L")
v <- c(1:length(genes))
for (i in v){
  cells <- WhichCells(seurat_object, expression = genes[i] > 0)
  print(length(cells))
}
```
But when I run this I get the following error message: 

> Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells, : None of the requested variables were found:

When I simply run 

`WhichCells(seurat_object, expression = KIF22 > 0) `

it works fine. 

In the end I would like to use this for loop to get some summary statistics for my genes of interest (e.g. min/max expression, mean expression, number of cells expressing the gene etc.). 
So it would be great if I could find a way to make this work, or is there even a more simple/prebuilt way to do this?

**Comment by mojaveazure** [comment]
Hi Anne,

Much like `subset`, the `expression` parameter for `WhichCells` is designed for interactive use only, not programmatic. In fact, `subset.Seurat` calls `WhichCells` under the hood. For using `subset` and `WhichCells` in a programmatic way, please see https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002

**Comment by rahulnutron** [comment]
Thanks for this! this is what I did
Thanks,
Rahul

items <-c( 'AT1G06990', 'CHX14')
for (gene1 in items)
  {
  if (gene1 %in% rownames(gen.sobj))
    
    {
    expr <- FetchData(object = gen.sobj, vars = gene1)
    gene_cells <- gen.sobj[, which(x = expr >= 0.5)]
    write.csv(colnames(gene_cells),paste('E:/Rahul/',gene1,'.csv',sep = ''))
    
    }
}
