### ISSUE TITLE
A bug about the alignment for two-datasets

### ISSUE THREAD

**Issue by thbin** [satijalab/seurat#184]
I'v tried to analyze my two datasets according to "the Seurat Alignment -Guided Tutorial", and found a bug in the RunCCA function.
I created two SeurateObjects: tumor3 and normal3. Then, when I ran the RunCCA, I found there were duplicate cell names: 
```
Running CCA
Merging objects
Error in MergeSeurat(object1 = object, object2 = object2, do.scale = FALSE,  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names
```
Therefore, I reran the RunCCA by setting the parameters `add.cell.id1` and `add.cell.id2`. The command as follows 
```
sample3 <- RunCCA(object=tumor3,object2= normal3, genes.use = hvg.sample3,
                  add.cell.id1="Tumor3",add.cell.id2="Normal3")
```
However, the plot's functions didn't been run for the Seurat's object. For example, when I ran `DimPlot` , there were the following errors.
```
p1 <- DimPlot(sample3, reduction.use = "cca", group.by = "protocol",do.return=TRUE)
Error in `$<-.data.frame`(`*tmp*`, "pt.size", value = 1) : 
  replacement has 1 row, data has 0
```
I've checked the DimPlot's source code, and found that the problem was caused by the cell's prefixes (add.cell.id1, add.cell.id2).
In the Seurat's object, there were cell's prefixes in all data's slots (such as raw.data, data, scale.data etc.). Howerver, there wasn't the prefixes in the cca slot. For example, the colname was 'Tumor3_AAACCTGAGGCGTACA' in the data's slot, while the rowname was 'AAACCTGAGGCGTACA' in the cca's `cell.embeedings`'s slot. Therefore, it wouldn't get the cells by the command `cells.use <- intersect(x = cells.use, y = rownames(x = data.plot))` in the DimPlot function.
Thanks! Looking forward to your reply.

**Comment by andrewwbutler** [comment]
Thanks for the detailed bug report! This should be fixed now in the develop branch.

**Comment by mojaveazure** [comment]
Fixed in commit 0175a3b on the develop branch

**Comment by thbin** [comment]
It sounds good. Thanks for your reply.

**Comment by AndyR2** [comment]
I just got this same error at the DimPlot function.  I opened a New Issue in regard to, then I read this.  

It was posted that this bug was fixed "in the develop branch".   What does that mean?
