### ISSUE TITLE
Set range for color code in FeaturePlot

### ISSUE THREAD

**Issue by lihaone** [satijalab/seurat#1841]
Hey Seurat team, 
Thanks for the great package. 
I'm trying to use FeaturePlot to make plots for many genes and would like to have them in the same color code / range. As these genes have different expression levels, and I noticed that the color code is 0~maximum of the gene expression. 
Can you instruct me how to achieve this? Thank you in advance! 
Best, 
Hao

**Comment by yuhanH** [comment]
Sure. But it requires several steps now.
I will use pbmc_small as an example:
You can see that these three genes have different scale.
`FeaturePlot(pbmc_small, features = c("PPBP","IGLL5","SDPR") )`

set combine to FALSE, and set your color scale limits.
```
p1 <- FeaturePlot(pbmc_small, features = c("PPBP","IGLL5","VDAC3"), combine = FALSE )
fix.sc <- scale_color_gradientn( colours = c('lightgrey', 'blue'),  limits = c(1, 8))
```

Add the new color scale into plots, and combine them
```
p2 <- lapply(p1, function (x) x + fix.sc)
CombinePlots(p2)
```
