### ISSUE TITLE
Clean subset?

### ISSUE THREAD

**Issue by royfrancis** [satijalab/seurat#1844]
How do I do a clean subset of a Seurat object just keeping the raw RNA assay? The `do.clean=T` option from `SubsetData()` is not available anymore.

`su5 <- subset(su,subset=seurat_clusters==5)`

I do it manually at the moment.

```
cells <- names(su$seurat_clusters[su$seurat_clusters=="5"])
su5 <- CreateSeuratObject(GetAssayData(su,assay="RNA")[,cells],project="cluster5")
```

Is this a good way to do this?

**Comment by mojaveazure** [comment]
Hi Roy,

Please see [`DietSeurat`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/DietSeurat).
