### ISSUE TITLE
Global size exceeds maximum allowed size when using Seurat3 develop version

### ISSUE THREAD

**Issue by arnssino** [satijalab/seurat#1845]
Hi,
I am working on the analysis with my datasets of ~50k cells. I followed the new "Integration and Label Transfer" vignette, using the develop version of Seurat3 that supports integrating cells based on sctransform. Everything went good until running "FindIntegrationAnchors" where I encountered this error:

list.anchors <- FindIntegrationAnchors(object.list = reference.list, normalization.method = "SCT", anchor.features = reference.features, dims = 1:30, verbose = FALSE)

Error in getGlobalsAndPackages(expr, envir = envir, globals = globals) : 
  The total size of the 21 globals that need to be exported for the future expression (‘FUN()’) is 13.35 GiB. This exceeds the maximum allowed size of 500.00 MiB (option 'future.globals.maxSize'). The three largest globals are ‘object.list’ (13.35 GiB of class ‘list’), ‘FUN’ (439.40 KiB of class ‘function’) and ‘anchor.features’ (223.23 KiB of class ‘character’).
Calls: FindIntegrationAnchors ... getGlobalsAndPackagesXApply -> getGlobalsAndPackages
Execution halted

This is not encountered using the current released version of Seurat 3.0.2. Looks like this is a solution here [https://stackoverflow.com/questions/40536067/how-to-adjust-future-global-maxsize-in-r](url).

**Comment by yxiao832** [comment]
Hi arnssino, 
How did you solve this issue?
I ran into the same problem. 
Thanks
Yang

**Comment by yxiao832** [comment]
I found in this webpage https://satijalab.org/seurat/v3.0/future_vignette.html. FAQ. 
Yang

**Comment by roofya** [comment]
Hi arnssino and yxiao832

I got the same error, 
Error in getGlobalsAndPackages(expr, envir = envir, globals = globals) : 
  The total size of the 6 globals that need to be exported for the future expression ('FUN()') is 3.58 GiB. This exceeds the maximum allowed size of 850.00 MiB (option 'future.globals.maxSize'). The three largest globals are 'object.list' (3.58 GiB of class 'list'), 'anchor.features' (316.65 KiB of class 'character') and 'IsSCT' (54.51 KiB of class 'function').
Even I use
plan("multiprocess", workers = 10)

Would you please help me to fix it.

Thank you

**Comment by Shawn10312** [comment]
Hi  yxiao832 and roofya,

plan("multiprocess", workers = 24) could not figure out the error neither.

Could Seurat team and others give us some advice?

Thanks.

**Comment by pabloatria18** [comment]
This worked for me:

options(future.globals.maxSize = 8000 * 1024^2)

**Comment by mtorressahli** [comment]
Hi

I've tried these two alternatives:

```
options(future.globals.maxSize = 8*1024^3)

options(future.globals.maxSize = +Inf)
```

When checking if the option was set, it seems to have worked, either with the higher limit:

```
> options('future.globals.maxSize')
$future.globals.maxSize
[1] 8589934592
```

or no limit:

```
> options('future.globals.maxSize')
$future.globals.maxSize
[1] Inf
```

But I keep receiving the message as if the option was set at 500 MiB

I'm setting a nested futures plan:

```
plan(list(
  tweak(multisession, workers = availableCores() %/% 3),
  tweak(multisession, workers = availableCores() %/% 3),
  tweak(multisession, workers = availableCores() %/% 3)
))
```

Not sure if that might affect the setting?

Im using `future_1.29.0`, `future.apply_1.10.0`, and `R version 4.2.1 (2022-06-23 ucrt)` in Windows 11.

Any help would be much appreciated

**Comment by edridgedsouza** [comment]
To add to this, I obtained better results when I increased the maxSize as well as when I set `plan('sequential')` to better see the progress when setting `verbose=T`. No idea why, but in default mode I was stuck in an execution loop for 1.5h before crashing, but with sequential execution I could see the function progress clearly and it finished within 10 mins. Unclear whether this speedup was due to the execution plan or due to the increased memory allowance though.

**Comment by ycsun0821** [comment]
> To add to this, I obtained better results when I increased the maxSize as well as when I set `plan('sequential')` to better see the progress when setting `verbose=T`. No idea why, but in default mode I was stuck in an execution loop for 1.5h before crashing, but with sequential execution I could see the function progress clearly and it finished within 10 mins. Unclear whether this speedup was due to the execution plan or due to the increased memory allowance though.

Yes
