### ISSUE TITLE
how to make my own data into "seurat" format? My data are from flow cytof .csv files of different patients.

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1846]
Dear, 

I have .csv files of flow-cytof data and  they are from different patients samples and normal controls.

Would you please give me some suggestions how to make my own data into "seurat" format?
The aim is to find the difference between the controls and patients.

Thank you so much for your help in advance!

Best wishes,
Jinping

**Comment by timoast** [comment]
Hi, Seurat requires data in a matrix with cells in columns and features (eg genes) in the rows. Once you have your data in this format, you can create a Seurat object using `CreateSeuratObject`. See the [vignettes](https://satijalab.org/seurat/vignettes.html) for more information.

**Comment by surljp2012** [comment]
Great, Tim!

Thank you,
Jinping
