### ISSUE TITLE
reference-based integration

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#1847]
Hey Seurat Team!

It was a wonderful Webinar yesterday and I simply couldn't help trying all the new stuff out!

While I'm checking new functionalities of integration analysis, I came up with this question: Is it legit for me to use an integrated Seurat object as a reference and integrated the object with a new dataset? Also, when I trying to follow the reference-based integration tutorial, it tells me it "could not find function "PrepSCTIntegration". I'm using Seurat v3.0.2 and am I supposed to switch to a developing version?

Btw, is there anywhere I could find some description of the mathematical details of these new integration functions?

Thanks!

**Comment by yuhanH** [comment]
Hi,
Sure. You could as the integrated seurat object as a reference and integrate with other dataset.
But in this current version, the integrated object is integrated by individual SCTransform object, and it cannot be integrated with other dataset again.   We will add this soon in the next version. 
If your integrated object is integrated by individual LogNormalize object, it can be integrated with other dataset again.  

If your data is SCTranform, you need to perform `PrepSCTIntegration` before integration, and this function is in the develop version, so you need to switch to the develop version. 

For the CCA integration, you  could check this [paper](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8)
For the SCTransform, it is in the bioarchive, [here](https://www.biorxiv.org/content/10.1101/576827v2)

**Comment by DHGK** [comment]
@yuhanH ,

Thanks a lot for your reply. Just a follow-up question:

When I try to integrate a lognormalized integrated object and another object, I got the following error when RunPCA on newly integrated object:
The following 1823 features requested have zero variance (running reduction without them): (GENES NAMES) ,Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive

Some previous posts said this is because having fewer var.genes than pcs. I use the default setting which  using genes from anchors, I believe, but I don't really know why all those features have zero variance. Did I need to specify which assay I want to use ("interated" for the integrated object and "RNA" for the new object) somewhere?

Thanks!

**Comment by laijen000** [comment]
Hi @yuhanH ,
I just wanted to follow up on this issue. I have an integrated object that was integrated using SCT. I have a new data set that I want to integrate using the first integrated object as a reference. Is it possible now to do so now using SCT? 

If so, could you provide an example for how to use the integrated object by SCT as a reference for integrating with another object? 

Thank you!

**Comment by yuhanH** [comment]
hi, 
sorry for the delay reply. You can use you can use your integrated object as a reference to integrate another SCT normlaized object. 
If you meet errors, i would suggest you re-generate your reference using our latest branch which should handle integrated assay and SCT assay integration.
