### ISSUE TITLE
Merge function not found in Seurat

### ISSUE THREAD

**Issue by nickcicero18** [satijalab/seurat#1848]
I was trying to merge to Seurat objects together when I got this error:

> merged_mouse <- merge(x = myeloid, y = non_myeloid, project = 'mouseBrain')

> Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("seurat", package = "Seurat")’ to a data.frame

So from there I tried to have R use the merge function from Seurat so I did this:

> merged_mouse <- Seurat::merge(x = myeloid, y = non_myeloid, project = 'mouseBrain')

> Error: 'merge' is not an exported object from 'namespace:Seurat'

...seems like the merge() function may have some bug in the update?

When I do '?merge' the merge function in Seurat pops up and I can go to the help tab and see all of the documentation for merge, but for some reason cannot execute it. (I have Seurat 3.0.2 installed)

Thanks in advance!

**Comment by mojaveazure** [comment]
Hi,

It looks like you're using an old v2 object. Objects of class `seurat` with a lower-case 's' are the older v2 objects. We don't define any methods for those objects. Objects of class `Seurat` with an upper-case 'S' are the newer v3 objects, and those are the ones supported in Seurat v3.X. Please see https://github.com/satijalab/seurat/issues/990#issuecomment-444606845 for greater detail about the `seurat` vs `Seurat` distinction and why we have both classes.

As for the error that `merge` is unexported, please see https://github.com/satijalab/seurat/issues/1175#issuecomment-467612385

**Comment by nickcicero18** [comment]
Thanks for the help!
