### ISSUE TITLE
Gene expression difference of one cluster between two conditions

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#1850]
I want to find the expression difference between two conditions, "STIM" vs "CTRL", of one cluster named `0` or "CD14 Mono". The official pipeline is [there](https://satijalab.org/seurat/v3.0/immune_alignment.html). I need the significantly different expression of RNA between two conditions in only one clusters (rather than comparing to the rest clusters).

The function I think Seurat provided is the following:
"
_# Find protein markers for all clusters, and draw a heatmap
adt.markers <- FindAllMarkers(cbmc.small, assay = "ADT", only.pos = TRUE)
DoHeatmap(cbmc.small, features = unique(adt.markers$gene), assay = "ADT", angle = 90) + NoLegend()_
"

However, as I tried many ways such as subset(), SplitObject(), and then merge(), I cannot perform the FindAllMarkers() functions. Look forward to your early reply.

**Comment by timoast** [comment]
You can perform differential expression between any two groups of cells using the `FindMarkers` function and setting the `ident.1` and `ident.2` arguments. As shown in the [immune alignment](https://satijalab.org/seurat/v3.0/immune_alignment.html) vignette, you can combine the cluster and treatment information to create a new set of cell identities, and then find differentially expressed genes within a cluster between treatment groups.

Relevant lines from the vignette:
```r
immune.combined$celltype.stim <- paste(Idents(immune.combined), immune.combined$stim, sep = "_")
Idents(immune.combined) <- "celltype.stim"
b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL")
```

**Comment by grimwoo** [comment]
> You can perform differential expression between any two groups of cells using the `FindMarkers` function and setting the `ident.1` and `ident.2` arguments. As shown in the [immune alignment](https://satijalab.org/seurat/v3.0/immune_alignment.html) vignette, you can combine the cluster and treatment information to create a new set of cell identities, and then find differentially expressed genes within a cluster between treatment groups.
> 
> Relevant lines from the vignette:
> 
> ```r
> immune.combined$celltype.stim <- paste(Idents(immune.combined), immune.combined$stim, sep = "_")
> Idents(immune.combined) <- "celltype.stim"
> b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL")
> ```

Thanks for your quick reply.
I change the code of the code for my own program. But I have the error for the FindMarker() function: 
#Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
#No features pass logfc.threshold threshold


original:
immune.combined$celltype.stim <- paste(Idents(immune.combined), immune.combined$stim, sep = "_")
immune.combined$celltype <- Idents(immune.combined)
Idents(immune.combined) <- "celltype.stim"
b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL", verbose = FALSE)
head(b.interferon.response, n = 15)

changed:
ME.subset.combined$celltype.Sex <- paste(Idents(ME.subset.combined), ME.subset.combined$Sex, sep = "_")
ME.subset.combined$celltype <- Idents(ME.subset.combined)
Idents(ME.subset.combined) <- "celltype.Sex"
Cluster.Sex.Difference <- FindMarkers(ME.subset.combined, ident.1 = "0_ME_MALE", ident.2 = "0_ME_FEMALE", verbose = FALSE)
**#Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
#No features pass logfc.threshold threshold**

head(ME.subset.combined$celltype.Sex)
#AAACCCAAGGTTACCT_1 AAACCCACAATAGTGA_1 AAACCCACATCACGGC_1 
#"0_ME_MALE"        "0_ME_MALE"        "0_ME_MALE" 
#AAACGAAAGGTAAACT_1 AAACGAACACGTCATA_1 AAACGAAGTCGAGTTT_1 
#"0_ME_MALE"        "0_ME_MALE"        "0_ME_MALE"

head(Cluster.Sex.Difference, n = 15)
