### ISSUE TITLE
FindIntegrationAnchors error

### ISSUE THREAD

**Issue by xiexiaowei** [satijalab/seurat#1851]
Hi,

I want to build the map comprised of celltype1,celltype2 and celltype3 with the command as follow:
FindIntegrationAnchors(object.list=indiv.list[c("ct1","ct2","ct3")], dims=1:20)
However, it breaks with the error like this:
Filtering anchors
Error in nn2(data = cn.data2[nn.cells2, ], query = cn.data1[nn.cells1,  : 
  Cannot find more nearest neighbours than there are points

It seems that different celltypes can't anchor with each other.

So, what should I do? Any suggestion?
Thanks very much and looking forward to your reply!
Xiaowei,

**Comment by timoast** [comment]
How many cells do you have in each object that you're trying to integrate? Do you expect there to be shared cell states present in each object? The anchor finding procedure is designed to _avoid_ having different cell types anchor with each other, as this would lead to poor integration results.

**Comment by xiexiaowei** [comment]
About 600 cells in each object. In fact, I want to integrate different cell types with 3 batchs.
So, what should I do?
1. anchor for each cell type with 3 different replicates to correct the batch effect
2. just merge the object of different anchored cell types 
Is that ok or any other suggestions? 
Thanks again for your reply!

xiaowei,

**Comment by timoast** [comment]
If there are not shared cell types between the batches and you want them in the same object, you should just merge them. If there are shared cell types and there is a batch effect, then you should use the [integration](https://satijalab.org/seurat/v3.0/integration.html) methods

**Comment by xiexiaowei** [comment]
Thanks very much for your reply!
But I have a new question related to this.

When I just integrat batch1, batch2 and batch3 for ct1, the tSNE map was consistent with our research background. However, when I merge the objects of integrated ct1 (with 3 batchs) and integrated ct2 (also with 3 batchs), then scale and RunPCA again for tSNE; the tSNE map of ct1 and ct2 was worse than before.
So, how can I merge different cell types and present them in the same map and simultaneously keep consistent with separated integration for each cell type?
