### ISSUE TITLE
pct.1 and pct.2 in the FindMarkers function

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1854]
I am confused about how to interpret pct.1 and pct.2. I know that they represent the percentage of cells where the feature is detected. What I'm unsure of is how the detection of a feature is defined in this case? Is it the expression of that gene supposed to be above a certain threshold in those cells? Is there a way to set that threshold?

**Comment by satijalab** [comment]
We use a detection threshold of 0, but we do not allow for the modification of this threshold.
