### ISSUE TITLE
Mean in FindVariableFeatures not matching Mean of VlnPlot?

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#1855]
I wanted to look at violin plots of genes which appear to have high dispersion (variance.standardized) in the list returned by _findVariableFeatures_. However the values of mean don't seem to be consistent. Is there some log normalization being done that I'm not observing?

I used _FindVariableFeatures_ with default parameters:
`ab1 <- FindVariableFeatures(object=ab1,selection.method="vst")`

The mean returned from this function is 8.917 for the gene. The violin plot for that gene is shown below. The maximum is around 5 in expression in the plot, whereas mean of expression was ~9 so I'm unsure about how to compare the two.

![VlnPlot](https://user-images.githubusercontent.com/41524686/61547610-b8a16500-aa19-11e9-9b30-c35ed2b8e428.png)

Thank you.

**Comment by satijalab** [comment]
Thanks for your question. The discrepancy is because the Violin plot reports values in log-scale, while the mean is calculated without log-transformation.
