### ISSUE TITLE
Ran integration but still seeing batch effect due to percent.mito

### ISSUE THREAD

**Issue by dwucsf** [satijalab/seurat#1857]
I combined 7 different datasets using Seurat 3's integration method, but I am still seeing batch effect due to percent.mito (see attached plots). Is there a way to merge my data better and remove this batch effect from percent.mito? Is it recommended to regress on percent.mito in the ScaleData() step? Thanks!

[UMAP-percent-mito.pdf](https://github.com/satijalab/seurat/files/3414407/UMAP-percent-mito.pdf)

[UMAP-origident.pdf](https://github.com/satijalab/seurat/files/3414411/UMAP-origident.pdf)

**Comment by satijalab** [comment]
You can regress on percent.mito in the ScaleData step as you say, but my interpretation from these results is that integration has effectively matched cell types across datasets, despite large differences in mitochondrial percentage. The differences that you see in perecnt.mt are minor, and are unlikely to modify downstream analyses. Given this, further regression would be an optional step.
