### ISSUE TITLE
DoHeatmap function returns a list instead of a ggplot

### ISSUE THREAD

**Issue by daymegr** [satijalab/seurat#1859]
I performed the integration of 4 tsamples and I obtained a seurat object with 2 assays: RNA and integrated. When I want to represent the positive markers that obtained the biggest FC in a heatmap, I don't get any plot and the object which is returned is a list instead of a ggplot object. This is the code I use for the heatmap in Seurat v3:
top_FC <- posMarkers %>% group_by(cluster) %>% top_n(param$markersToShow, avg_logFC)
DoHeatmap(object = scData, features = top_FC$gene, label = FALSE) + theme(axis.text.y = element_text(size = 8))

top_FC$gene is a character vector and it contains the names of the genes I want to represent.

**Comment by yuhanH** [comment]
Hi, I think your code is correct. I cannot reproduce the error. 
Could you give me more information?  Have you updated to the latest version?

**Comment by CamilleDC** [comment]
Hi,

I know this issue is old, but I have the same problem, where my DoHeatmap output is saved as a list instead of a ggplot. When looking inside that list, it seems that it contains the same elements as a ggplot (a dataframe, some layers, etc.).
I am using Seurat 3.1.1
