### ISSUE TITLE
NormalizeData without raw.data

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#186]
If you run `CreateSeuratObject()` with `save.raw = FALSE`, then the `raw.data` slot is empty.

However, if you try to run `NormalizeData()` on that object, you get an error:
```
> NormalizeData(s_obj, normalization.method = "LogNormalize", scale.factor = 10000)
Error in to.return[, object@cell.names] : 
  no 'dimnames' attribute for array
```

The problem seems to be that `NormalizeData()` is looking for the `raw.data` slot and setting `save.raw = TRUE` fixes the error.

I am not sure what they real issue is. `NormalizeData()` has a check for existence of `raw.data`, but that does not seem to work as intended. More importantly, shouldn't `NormalizeData()` be using `data` slot instead of `raw.data` (filtered cells instead of pre-filtered cells)?

**Comment by satijalab** [comment]
Good catch - the save.raw argument is from an older version, but under the new workflow, we would not suggest setting this argument to F for exactly the reason you describe.

NormalizeData does use object@raw.data[,object@cell.names] to ensure that only filtered cells are normalized.

We'll remove the save.raw argument in the future.

**Comment by mojaveazure** [comment]
Fixed in the develop branch, see [this page](http://satijalab.org/seurat/devinstall.html) for instructions on installing from this branch.
