### ISSUE TITLE
ADT label transfer

### ISSUE THREAD

**Issue by ChaDuss** [satijalab/seurat#1861]
Hi,
i would like to transfer protein expression from one seurat object : "CITEseqdata to another seurat object scRNAseqdata using the FindTransferAnchors and TransferData functions in Seurat v3, but i can't manage to do it.
Here is the code i tried but that doesn't work:

pbmcmerge <- FindTransferAnchors(reference = CITEseqdata, query = scRNAseqdata)                                        dims = 1:30)
predictions <- TransferData(anchorset = pbmcmerge, refdata = CITEseqdata@assays[["ADT"]], 
                            dims = 1:30)
scRNAseqdata@assays[["ADT"]] <-predictions

Thanks for your answer.

ChaDuss

**Comment by yuhanH** [comment]
HI, 
Just add counts there.
```
predictions <- TransferData(anchorset = pbmcmerge,
 refdata = CITEseqdata@assays[["ADT"]]@counts,
dims = 1:30)
```
