### ISSUE TITLE
Use variable containing gene name instead of gene name with subset

### ISSUE THREAD

**Issue by CoderMatthias** [satijalab/seurat#1862]
Hi,

I've recently updated my analyses pipeline to v3 over v2. I'm having an issue with the new subset method with v3. I create functions to produce graphs to cut down on coding repetition and feed in gene names, so the gene names are held in a variable. Specifically, I subset a Seurat object by expression of a gene of interest.

In v2, my code would look like this:
`
goi <- 'SomeGene'
subsetted_seurat_obj <- SubsetData(seurat_obj, subset.name = goi, accept.low = .00000000001)
`

This worked, but with v3, my code would look something like this:
`
goi <- 'SomeGene'
subsetted_seurat_obj <- subset(seurat_obj, subset = goi > .00000000001)
`

This doesn't work, as it wants subset to look like this: subset(seurat_obj, subset = SomeGene > .0000000001)

I tried a couple different things without luck, any idea how to use a variable instead of the gene name in this case?

Thanks for your help and this remarkable package!

Best,
Matt

**Comment by mojaveazure** [comment]
Please see https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002
