### ISSUE TITLE
Applying Ref-based integration w/ 2 samples

### ISSUE THREAD

**Issue by DanSchnell** [satijalab/seurat#1863]
I'd like to designate the smaller of 2 samples as the reference for integration.

Using the development version (3.0.3.9015), and following the 7-16 vignette, I specified reference="SMALL" in the call to FindIntegrationAnchors.

The following appeared:
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 08s
Error in FindIntegrationAnchors(object.list = MCA, anchor.features = 2000,  : 
  Error: requested reference object SMALL but only 2 objects provided

How could the call or workflow be adjusted to use "SMALL" as the reference for integration?

Thanks much,
Dan

**Comment by andrewwbutler** [comment]
Hi Dan,

The `reference` parameter should be the index of the object in the list provided. However, if you only have 2 objects, it won't make a difference in anchor finding as you have to find anchors between a pair of objects. If you want to "correct" the data of the larger one onto the smaller one, you could set the `sample.tree` argument in `IntegrateData` to manually specify this. This argument is expecting a matrix like you would get back from `hclust` (see ?hclust - the merge return value for a more detailed description). Should look something like this for two objects:
```R
[,1] [,2]
[1,]  -1  -2
```
