### ISSUE TITLE
logFC different among different DE tests

### ISSUE THREAD

**Issue by kapoormanav** [satijalab/seurat#1864]
Hi, I am getting different avg_logFC estimate with negative binomial and MAST analysis. Some genes have positive signs in negative binomial analysis but have negative logFC sign in MAST. It seems that negative binomial test is calculating avg_logFC from counts slot.

**Comment by yuhanH** [comment]
Hi,
You are right. negative binomial uses the counts slot and MAST uses data slot. 
Not sure how different those two tests are. Do the genes with different DE logFC have small p value ? 
Do you set latent variables? You can check more detail information about these two DE test.
They are in the function `GLMDETest` and `MASTDETest`.
