### ISSUE TITLE
findallmarkers using all available cores, seurat v2.3.4

### ISSUE THREAD

**Issue by chintanparekh2301** [satijalab/seurat#1865]
Hi
I am using findallmarkers in seurat v2.3.4 and it uses all available cores by default, which is a problem because I am using a shared workstation. Is there a way to limit the number of cores the function uses when using v2.3.4?  I cannot use seurat v3 for this project because most of the project has already been analyzed using v2.3.4 and I would like to keep things consistent.
Thank you very much

**Comment by timoast** [comment]
Hi, which DE test are you using?

**Comment by chintanparekh2301** [comment]
MAST
Thank you very much

Sent from my iPhone

On Aug 9, 2019, at 7:18 AM, Tim Stuart <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, which DE test are you using?

**Comment by satijalab** [comment]
Apologies that we never responded. We've changed the settings for multi-thread processing going forward (https://satijalab.org/seurat/v3.0/future_vignette.html)
