### ISSUE TITLE
selecting subsets of cells based on multiple criteria

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#1866]
Dear all, 

i would appreciate a piece of advise please : 

shall we have a matrix of cells (by Drop-seq), after 3 treatments (PBS, Tr1, Tr2) , 

that are clustered in 10 clusters (below),

how shall i extract the cells associated with (let's say) cluster_3 separately in these 3 conditions (PBS, Tr1, Tr2) ? thank you ..

```
- [ ] head(samples.combined@meta.data) |   |   |   |   |   |   |   |  
- [ ] -- | -- | -- | -- | -- | -- | -- | -- | --
- [ ]   | nGene | nUMI | orig.ident | stim | percent.mito | Res.06 | cell.type.stim | cell.type
- [ ] PBS-AAACCTGAGAGGTAGA | 1998 | 4096 | PBS-AAACCTGAGAGGTAGA | PBS | 0.04080137 | 1 | 1_PBS | 1
- [ ] TR1-AAACCTGAGATCGGGT | 1616 | 3159 | TR1-AAACCTGAGATCGGGT | TR1 | 0.04529617 | 8 | 8_TR1 | 8
- [ ] TR2-AAACCTGAGATGCGAC | 1101 | 1956 | TR2-AAACCTGAGATGCGAC | TR2 | 0.0398773 | 0 | 0_TR2 | 0
```

**Comment by mojaveazure** [comment]
You can use `subset` on a Seurat v3 object the same way you'd use it on a data frame, including chaining subset terms.
