### ISSUE TITLE
Error in UseMethod, Convert

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#1868]
I am trying to convert my V3 Seurat object into a loom file using:

```
pfile <- Convert(from = x, to = "loom", filename = "x.loom", 
    display.progress = TRUE)
```

 I am currently getting the error:

```
Error in UseMethod(generic = "Convert", object = from) : 
  no applicable method for 'Convert' applied to an object of class "Seurat"
```

Do you have any idea what could be wrong? I took this code from:
https://satijalab.org/loomR/loomR_tutorial.html

**Comment by Connorr0** [comment]
I also noticed that the library I installed from:

> devtools::install_github(repo = 'satijalab/seurat', ref = 'loom')

Is giving me the following session info:
other attached packages:
```
 [1] devtools_2.1.0   usethis_1.5.1    Seurat_2.3.1     Matrix_1.2-17    cowplot_1.0.0    ggplot2_3.2.0    loomR_0.2.1.9000 hdf5r_1.2.0     
 [9] R6_2.4.0         tictoc_1.0

```
My previous installation of Seurat was 3.0, and it appears that I have downloaded Seurat 2, is Seurat 3 available with loom support?

**Comment by mojaveazure** [comment]
The loom branch of Seurat is v2, not v3. We are working on updating it, but have no news to share on that front. To convert a v3 object to a loom object, please use `as.loom`

**Comment by vlaufer** [comment]
Just a suggestion, if this distinction between v2 and v3 were included in the relevant tutorial on the Seurat webpage, might save users some time.
