### ISSUE TITLE
PrepSCTIntegration error

### ISSUE THREAD

**Issue by afidanza** [satijalab/seurat#1869]
I am trying to integrate an old Seurat Object obtained by 10X V2 and analyzed on SeuratV2  with a 10X V3/SeuratV3. I get an error when I run PrepSCTIntegration. I thought it was the ADT assay on the new object so I have removed it, but the error persisted. 
---------------------------------------------------------------------
seurat.old <- seuratobject
seurat.old <- UpdateSeuratObject(seurat.old)
seurat.old.small <- subset(seurat.old, cells=sample(colnames(seurat.old), 1000))
seurat.old.small <- SCTransform(seurat.old.small)
seurat.small@assays$ADT <- NULL
seurat.list <- c(seurat.old.small, seurat.small)
integration.features <- SelectIntegrationFeatures(object.list = seurat.list, nfeatures = 3000)
seurat.list <- PrepSCTIntegration(object.list = seurat.list, 
                                  anchor.features = integration.features, 
                                    verbose = FALSE)

Error in y - mu : non-conformable arrays

**Comment by yuhanH** [comment]
Do you use `subset` for the object seurat.small after SCTransform?

**Comment by afidanza** [comment]
Yes, I used subset after running SCTransform, both objects have SCT in their assays.

**Comment by yuhanH** [comment]
HI,
Currently, you need to do `subset` before running `SCTransform`.
If you have to do `subset` after `SCTransform`,  you need to filter SCT model output now. But we will fix this in the coming version.
```
vst <- object[["SCT"]]@misc$vst.out
vst$cell_attr <- vst$cell_attr[Cells(object),]
vst$cells_step1 <- intersect(vst$cells_step1, Cells(object))
object[["SCT"]]@misc$vst.out <- vst
```
The object is the one after subsetting.

**Comment by MichaelPeibo** [comment]
Hi @yuhanH , still got this error following your guide code.

**Comment by MichaelPeibo** [comment]
Hi @yuhanH ,
Thanks for reply.
I updated seurat to dev version and still got the error.
Then I checked the `vst` slot and I found where my problem is.
Before `PrepSCTIntegration` , I `RenameCells` my two objects, and names in `vst` slot keep unmatched.

Now I found I did not rename two objects, and got it through.

**Comment by yuhanH** [comment]
That's great! `RenameCells` currently cannot change the cell name in the `vst` slot.
