### ISSUE TITLE
Using a min.cell filter when merging data from different stages

### ISSUE THREAD

**Issue by alexthiery** [satijalab/seurat#1870]
Hi,

I am merging my data collected from different sample stages instead of using cellranger aggr (all stages were multiplexed together so there should be no batch effects). I am then wanting to filter genes which are expressed in at least 3 cells. However I would like to do this step after the merge, incase I lose genes if they expressed in more than 3 cells but across more than one sample. Is there an easy way to do this as in CreateSeuratObject, or do I need to just make a logical vector for genes which are in more than 3 cells?

Thanks!
Alex

**Comment by alexthiery** [comment]
Would it be reasonable for example to pass the output from merge() directly back to CreateSeuratObject() again in order to filter for min.cells=3

e.g.
temp <- merge(Sample1, y = c(Sample2, Sample3, Sample4), add.cell.ids = c("Sample1", "Sample2", "Sample3", "Sample4"), project = "10x", min.cells = 3)
merged.data<-CreateSeuratObject(GetAssayData(temp), min.cells = 3, project = "10x")

**Comment by andrewwbutler** [comment]
Hi Alex,

If you have separate count matrices for each sample, I would just merge those ahead of running `CreateSeuratObject` and then specify the `min.cells` parameter when you set up the object.

**Comment by alexthiery** [comment]
Hi Andrew,

Thanks for your reply. Yes that makes sense, the only thing is that I don't seem to be able to use the Seurat::merge function directly on my separate count matrices - should this be possible or is this function only to merge Seurat objects? If its possible then I think it might be a RAM issue in which case I can run it on the cluster.

Thanks again!

**Comment by andrewwbutler** [comment]
Yeah, the Seurat merge function only works on Seurat objects. Other merge functions are defined for other classes (e.g. [Matrix](https://www.rdocumentation.org/packages/Matrix.utils/versions/0.9.7/topics/merge.Matrix)) that you could try or if the rownames are all the same (and in the same order) you could just use `cbind`.

**Comment by alexthiery** [comment]
perfect, thanks! I wasn't sure if Seurat was doing any other data manipulation at this stage - but this seems straight forward.
