### ISSUE TITLE
Loading HTO matrix in H5AD format

### ISSUE THREAD

**Issue by cc36** [satijalab/seurat#1872]
Hi,

I would like to try the demultiplexing with hashtag oligos from your tutorial, however, I do not have the input files in the same format.

I have run cellranger 3.0.2, which generates a "multidimensional" matrix that contains both "Gene Expression" and "Antibody Capture" information.

As I usually work with scanpy, I loaded the "multidimensional" matrix into scanpy, subsetted the "Gene Expression" and "Antibody Capture" data into separate H5AD files and tried loading them into Seurat using the ReadH5AD function.

I successfully loaded the "Gene Expression" data but not the "Antibody Capture", even when I indicate assay = "HTO" as an argument. I get the following error message:

```
Pulling expression matrices and metadata
Data is unscaled
Creating assay object
Storing X as raw and raw as counts
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Error: Cannot add more or fewer meta.features information without values being named with feature names
Traceback:

1. ReadH5AD("/mnt/CITEseq/write/hto_data.h5ad", assay = "HTO")
2. ReadH5AD.character("/mnt/CITEseq/write/hto_data.h5ad", 
 .     assay = "HTO")
3. ReadH5AD(file = hfile, assay = assay, verbose = verbose)
4. ReadH5AD.H5File(file = hfile, assay = assay, verbose = verbose)
5. `[[<-`(`*tmp*`, names(x = meta.features), value = structure(list(
 .     gene.ids = c("N5", "N6", "N7", "N8"), feature.types = c(0L, 
 .     0L, 0L, 0L)), class = "data.frame", row.names = c("N5_HTO", 
 . "N6_HTO", "N7_HTO", "N8_HTO")))
6. `[[<-`(`*tmp*`, names(x = meta.features), value = structure(list(
 .     gene.ids = c("N5", "N6", "N7", "N8"), feature.types = c(0L, 
 .     0L, 0L, 0L)), class = "data.frame", row.names = c("N5_HTO", 
 . "N6_HTO", "N7_HTO", "N8_HTO")))
7. stop(err.msg, call. = FALSE)
```

Could you please advise on how to read the HTO file or how to convert it to a Seurat compatible format?

Thank you in advance,
Cecilia

**Comment by cc36** [comment]
I just found in your documentation the following option to directly read from cellranger output different feature_types:

```
# For output from CellRanger >= 3.0 with multiple data types
data_dir <- 'path/to/data/directory'
list.files(data_dir) # Should show barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz
data <- Read10X(data.dir = data_dir)
seurat_object = CreateSeuratObject(counts = data$`Gene Expression`)
seurat_object[['Protein']] = CreateAssayObject(counts = data$`Antibody Capture`)
```

Still, I would highly appreciate if you could advise on how would this plugin on the demultiplexing tutorial and how could I make the distinction between the HTO and ADT data, as both are labeled as 'Antibody Capture'.

Thanks again.
Cecilia

**Comment by andrewwbutler** [comment]
Hi Cecilia,

You'll need to split the Antibody Capture matrix into two separate matrices. One for the HTO data and one for the ADT data. Then you can create two separate assays and add them to the Seurat object as you were doing above.
