### ISSUE TITLE
RunUMAP was working fine and now it has stopped working

### ISSUE THREAD

**Issue by CamilleCouture** [satijalab/seurat#1873]
Since UMAP has been released I have been using it this way:
adult <- RunUMAP(object = adult, dims = 1:10, reduction = "pca", assay = "RNA", n.neighbors = 30)

I did a small clean up of files on my computer (which might have included files I didn't realize were important) but now when I try to run my script it stops at the RunUMAP argument and gives me the following error:

Fatal Python error: initsite: Failed to import the site module
ModuleNotFoundError: No module named 'site'

Current thread 0x00000001131225c0 (most recent call first):
Error in RunUMAP.default(object = data.use, assay = assay, n.neighbors = n.neighbors,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/Users/camillecouture/anaconda3/envs/r-reticulate/bin/python' "/Library/Frameworks/R.framework/Versions/3.5/Resources/library/reticulate/config/config.py"' had status 1

I have successfully done:
> library(reticulate)
> py_install("umap-learn")

but still get the same error... curious what else I could try

**Comment by CamilleCouture** [comment]
<img width="959" alt="Screen Shot 2019-07-24 at 11 38 14 AM" src="https://user-images.githubusercontent.com/47834391/61807487-a489a900-ae07-11e9-870a-4e01a391fca4.png">
<img width="905" alt="Screen Shot 2019-07-24 at 11 37 56 AM" src="https://user-images.githubusercontent.com/47834391/61807492-a5bad600-ae07-11e9-9661-68215188f9dc.png">

**Comment by j-andrews7** [comment]
Not having the `site` module means you likely broke your python. Can you start an interactive python session from the command line? 

I'd recommend creating a new conda env with everything Seurat needs as well - installing things into base conda is generally not a good idea.

**Comment by CamilleCouture** [comment]
I am able to start python through the command line!

I created a new Conda env like you said and everything is running again THANK YOU!!
