### ISSUE TITLE
Scaling Integrated Dataset for DEGs

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1874]
Hello!

I'm reaching out again about an integrated analysis that i am performing with 7 different single cell libraries. My workflow is as follows: 

1. Set up each library, remove high mito cells, give cell cycle score: 
`wtME <- Read10X(data.dir = './ME/outs/filtered_feature_bc_matrix/')
wtME <- CreateSeuratObject(counts = wtME, project = "10X_wtME")
wtME <- PercentageFeatureSet(object = wtME, pattern = "^MT-", col.name = "percent.mt")
wtME <- subset(x = wtME, subset = nFeature_RNA > 2500 & percent.mt < 15)
wtME <- NormalizeData(wtME, verbose = FALSE)
wtME <- FindVariableFeatures(wtME, selection.method = "vst", nfeatures = 2000)
wtME <- CellCycleScoring(object = wtME, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
wtME$CC.Difference <- wtME$S.Score-wtME$G2M.Score 
wrE14$stim <- "wrV14"`
...repeat 6x for each library 

2. Integrate data
`vitDcca <- FindIntegrationAnchors(object.list = list(wrE14, wrD14, wtME, wtMD, wrE7, wrD7, awE7), dims = 1:50)
vitDcca <- IntegrateData(anchorset = vitDcca, dims = 1:50)
DefaultAssay(object = vitDcca) <- "integrated"`

3. Regress cell cycle, follow standard workflow for visualization and clustering:
`vitDcca <- ScaleData(object = vitDcca, vars.to.regress = c("CC.Difference"), verbose = FALSE)
vitDcca <- RunPCA(object = vitDcca, npcs = 60, verbose = FALSE)
vitDcca <- FindNeighbors(object = vitDcca, reduction = "pca", dims = 1:40)
vitDcca <- FindClusters(vitDcca, resolution = 0.4) 
vitDcca <- RunUMAP(object = vitDcca, reduction = "pca", dims = 1:40)
DimPlot(object = vitDcca, reduction = "umap")`

4. Find markers for each cluster
`DefaultAssay(object = vitDcca) <- "RNA"
vitDcca.markers <- FindAllMarkers(vitDcca, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write.table(vitDcca.markers, file = "vitDcca-RNAmarkers_All.csv")`

5. Visualize markers with heatmap
`all.genes <- rownames(x = vitDcca)
vitDcca <- ScaleData(object = vitDcca, features = all.genes)
vitDcca.markers %>% group_by(cluster) %>% top_n(n = 12, wt = avg_logFC) -> top10
DoHeatmap(subset(vitDcca, downsample = 100), features = top10$gene, size = 3)`

6. Perform DEG analysis for different comparisons of interest
`vitDcca$celltype.stim <- paste(Idents(vitDcca), vitDcca$stim, sep = "_")
vitDcca$celltype <- Idents(vitDcca)
Idents(vitDcca) <- "celltype.stim"
DEG.genes0 <- FindMarkers(vitDcca, ident.1 = "0_wrD14", ident.2 = "0_wrV14", verbose = FALSE)`

So I have two questions about this workflow. 
1. I have a ScaleData step on the integrated assay, but then added a ScaleData step prior to generating a heatmap assay because I was getting an error that there was no scale.data slot. Should I be doing this after integration on the RNA assay, or should I do this while setting up each individual object before integration? Or is it no difference when I do this step. 
2. Does this scaling step affect the DEG analysis? I use the RNA assay for my DEG analysis, but am getting avgFC values that are ~1. I notice in your tutorials you also have modest avgFC values. For my data, I know some of the genes should have very high FC and are at the top of the list, but top off at 0.98. I'm wondering if this has to do with the scaling.  

Thanks for all your help/support and creating this amazing tool for us!

**Comment by andrewwbutler** [comment]
Hi,

1. Yes, you can do this on the RNA assay after integration for visualizing your markers in the heatmap. 

2. No, scaling does not affect the DE analysis as we used the log normalized data for those tests.

**Comment by tmccra2** [comment]
Thanks for your reply!

So my question is how to manage or scale the DE output. I know that my most differentially expressed gene should be about 200 fold higher in my treatment but it shows a logFC around 1.26. To use logFC values for Ingenuity Pathway Analysis or other down stream software you generally want FC <-1 or >1. Almost all of my genes are scaled between -1.5 and 1.5. If I try to convert back to FC then all negative values become positive number between 0 and 1. 

Do you have any recommendations on how to scale the logFC output, or generate a different output like FC?

**Comment by tmccra2** [comment]
Bumping to see if I can get some clarity on this: 

I see that most tutorials and posts from users on here show equally unimpressive avg_logFC values around 1-3 for genes. Can you help me understand how avg_logFC is calculated and how I would be able to scale my data beyond -1 and 1 avg_logFC values in order to input in pathway analysis software?

Thanks!'
