### ISSUE TITLE
Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses

### ISSUE THREAD

**Issue by sygongcode** [satijalab/seurat#1875]
Hello, All,
I am confusing about a question in the tutorial: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses. In the part of Identify conserved cell type markers. To find conserved markers irrespective of stimulation condition in cluster 6 (NK cells). But in the code, the ident.1 = 7. And I find the gene GNLY only expressed in cluster 7, not in cluster6. I do not really understand why. Can anyone help me? Thanks.

**Comment by andrewwbutler** [comment]
Hi,

This is a typo in the text for that tutorial. It should read "cluster 7". We will update accordingly.
