### ISSUE TITLE
FindTransferAnchors with SCTransform-ed dataset and the project.query parameter

### ISSUE THREAD

**Issue by mxposed** [satijalab/seurat#1876]
Hello

Could you please explain how to use `FindTransferAnchors` with SCTransformed data?

I have 2 datasets that were _only_ sctransformed.
Then I do
```r
int.features <- SelectIntegrationFeatures(
  list(sc1, sc2),
  nfeatures = 3000
)
data.list <- PrepSCTIntegration(
  list(sc1, sc2),
  anchor.features = int.features
)
anchors <- FindTransferAnchors(
  sc1, 
  sc2,
  normalization.method = "SCT", 
  features = int.features
)
```
and it fails with error:
```
Error in `[.data.frame`(slot(object = x, name = "meta.features"), , i, : 
  undefined columns selected
```

However, if I supply `project.query` parameter to `FindTransferAnchors` then it does not do `ScaleData` and there is no error, but this feels strange

**Comment by yuhanH** [comment]
Hi, 
When you use `FindTransferAnchors` for SCTransform data, you should set query and reference.
For the data normalized SCTransform, it doesn't run `ScaleData`.
Could you describe a little why you feel the result is strange? Thanks

**Comment by mxposed** [comment]
Hi, thank you for the quick response. I should have mentioned, I use `develop` version of Seurat.
What is strange is that I have that error when I do not pass `project.query` parameter.
I pass query and reference objects, I just don't name them explicitly, but will change according to your style.

**Comment by yuhanH** [comment]
HI, 
Thanks for reporting this bug. We have fixed this issue. 
You don't need to set `project.query`. I suggest you set your object with `query ` and `reference`
