### ISSUE TITLE
Error in lfile$add.layer(layers = list(scale_data = as.matrix(x = t(x = as.data.frame(x = GetAssayData(object = x,  :    unused argument (verbose = verbose)

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#1877]
when I perform the code from the loom [vignette](https://satijalab.org/seurat/v3.0/conversion_vignette.html), I encountered the following error. Please let me know how to solve it. I want to save seurat.objec as loom file for further analysis in scanpy.

**> combined**
_An object of class Seurat 
24537 features across 27238 samples within 2 assays 
Active assay: integrated (2000 features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap_

**> combined.loom <- as.loom(combined, filename = "D:/personal data/Seurat Processed Data/Subclustes.loom", verbose = FALSE)**
_Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns 
This is to maintain compatibility with other loom tools 
  |=========================================================================================================| 100%
Error in lfile$add.layer(layers = list(scale_data = as.matrix(x = t(x = as.data.frame(x = GetAssayData(object = x,  : 
  unused argument (verbose = verbose)_
**> combined.loom**
_Error: object 'combined.loom' not found_

**Comment by mojaveazure** [comment]
Hi,

Which version of loomR are you using? Please ensure you're using the latest development version of loomR with `devtools::install_github("mojaveazure/loomR", ref = 'develop')`

**Comment by grimwoo** [comment]
> Hi,
> 
> Which version of loomR are you using? Please ensure you're using the latest development version of loomR with `devtools::install_github("mojaveazure/loomR", ref = 'develop')`

Thanks!

**Comment by grimwoo** [comment]
sorry for this issue again as I posed it before #1877. I still have this problem.

I first update the loomR package as following:
_> devtools::install_github("mojaveazure/loomR", ref = 'develop')
**Skipping install of 'loomR' from a github remote, the SHA1 (1eca16a6) has not changed since last install.
  Use `force = TRUE` to force installation**_

After that, it still give the following error:
_> pbmc.loom <- as.loom(pbmc, filename = "D:/personal data/Wu Haoda/Ependymoma/Seurat Processed Data/Processed_Information_of_Patient_with_Raw_Expression_Seurat_Object.loom3", verbose = FALSE)
Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns 
This is to maintain compatibility with other loom tools 
  |===========================================================================================| 100%
Adding a layer to norm_data (layer 1 of 1) 
  |===========================================================================================| 100%
**Error in lfile$add.layer(layers = list(scale_data = as.matrix(x = t(x = as.data.frame(x = GetAssayData(object = x,  : 
  unused argument (verbose = verbose)**
> pbmc.loom
**Error: object 'pbmc.loom' not found**_

**Comment by grimwoo** [comment]
up to now, i have tried 3 computers and 4 Rstudio, 3 result in same error. And another give the error "Error: cannot allocate vector of size 256.5 Mb", which may be due to the poor computation ability of my laptop.

**Comment by cjuagf** [comment]
Were you able to get this to work? I am running into the same issue.

**Comment by grimwoo** [comment]
@cjuagf No, I gave up   :)

**Comment by rsatija** [comment]
We are closing this issue now as we are no longer prioritizing support for loom conversion.

In Seurat v5, we include support for the [v5 assay class](https://satijalab.org/seurat/articles/seurat5_essential_commands.html), which can flexibly store data in a variety of formats (including disk-backed formats). We include multiple examples for disk-backed analysis using the [BPCells package from Ben Parks ](https://github.com/bnprks/BPCells).
