### ISSUE TITLE
Running CCA to merge human and mouse data in seurat 2.3.4.

### ISSUE THREAD

**Issue by gauravsinghrathore** [satijalab/seurat#1878]
When i try to run cca on human and mouse dataset the unique 1000 highly variable gene finding would not work because of different ways of annotation.
If i merge gene list 500 genes form mouse and 500 humans and feed as vector to genes.use it will me error like this. 
Error in data.use[genes.use, ] : incorrect number of dimensions

any suggestion to solve this problem??

**Comment by andrewwbutler** [comment]
Hi,

You will need to map the human and mouse gene names to a common system. Often, for human and mouse, this just entails making all gene names of the same case (i.e. capitalize the mouse gene names to match the human ones).

**Comment by gauravsinghrathore** [comment]
Hi Andrew,

I have been trying to convert mouse gene names to all Caps in Seurat 2.0 matrix but never works, could you please suggest a code to do this task. Our lab will be grateful to you. ☺

Thanks a lot in advance. ☺


Regards
Gaurav

--
Gaurav Singh Rathore
PhD Student
Novo Nordisk Foundation Centre for Stem Cell Biology - DanStem
University of Copenhagen,
Faculty of Medical and Health Sciences
Blegdamsvej 3B, Building 6, 5th floor
2200 Copenhagen N
Denmark
[cid:image001.png@01D3519F.C6C92FC0]
