### ISSUE TITLE
WhichCells invert parameter doesn't work with the "cells" argument (Seurat v. 3.0.3.9015)

### ISSUE THREAD

**Issue by AHPool** [satijalab/seurat#1880]
In the current development version of Seurat (v. 3.0.3. 9015) the WhichCells function returns an empty character vector (character(0)) if the "cells=" parameter is used in combination with "invert=T". Interestingly the cells specifying parameter works on its own as does invert when used in combination with "idents" parameter. However, using both cell subspecification and inversion results in an empty vector. This function is however intact in seurat v. 3.0.2.

Sample code:
> desired_cells = WhichCells(object = seurat_dbase, cells = discard_cells, invert = T) 
> desired_cells
character(0)

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
