### ISSUE TITLE
loom branch of Seurat Reverts to Seurat v2.3.1

### ISSUE THREAD

**Issue by sinjia7** [satijalab/seurat#1881]
Hello Seurat team.

I have recently tried to work with loom objects with Seurat as my datasets are getting bigger. However, after I install hdf5r and loomR (both successfully), I tried to install the loom branch of Seurat via your command: 
`devtools::install_github(repo = "satijalab/seurat", ref = "loom")`
While the branch installs, I realized that Seurat does not work the same. A quick `sessionInfo()` command and I notice that the Seurat package has reverted to the 2.3.1 version. However, when I update Seurat using the `install.packages()` function, the loom methods for Seurat are no longer present as a quick check using the `methods(class = 'loom')` command will reveal.
Is there another command I should be using to install the loom branch of Seurat? Thank you!

**Comment by Connorr0** [comment]
I ran into the same problem and was wondering what the new loom functions are. there is at least as.loom() but other than that I am not sure what they are.

**Comment by mojaveazure** [comment]
The loom branch is on v2. We are working on updating it to v3 but have no news to share at this point.
