### ISSUE TITLE
Feature Plot with dual genes

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#1882]
hey guys, 

So I followed the new 'blend' option [here](https://satijalab.org/seurat/v3.0/visualization_vignette.html) to plot two genes using the code below:

`FeaturePlot(ASeurta_v3Object, 
            features = c("PDX1", "RFX6"),
            pt.size = 2,
            blend = TRUE,
            blend.threshold = 0.5)`

My question is regarding the color scale, how can I change it? The color scale for double-negative cells is a really dark-grey/blue and it masks cells which are positive for a certain marker. Can you please tell me how to modify the color spectrum (by modifying colors NOT the blend threshold) to make double negative cells light-grey?

I know it has something to do with:

`cols = ifelse(test = c(blend, blend), yes = c("#ff0000", "#00ff00"), no
                          = c("lightgrey", "blue"))`

But I keep getting this error:
`Error in ifelse(test = c(blend, blend), yes = c("#ff0000", "#00ff00"),  : 
  object 'blend' not found`

Thanks

**Comment by yuhanH** [comment]
Unfortunately, right now you cannot change the double negative cells to light-grey. We will add this option in the next version. 
But you could change the background to dark color which should be better, and you could also change the cells order.
here is the code you could change cell order which will also be added in the next version.
```
blend.features <- c("AKR1C3", "VDAC3")
# default plot
FeaturePlot(pbmc_small, features = blend.features, blend = TRUE, pt.size = 7)

cells.sort <- Cells(pbmc_small)[ order(GetAssayData(pbmc_small,slot = "data")[blend.features[1],],
                                     GetAssayData(pbmc_small,slot = "data")[blend.features[2],],
                                     decreasing = F)]
# sorted plot
FeaturePlot(pbmc_small, features = blend.features, blend = TRUE, pt.size = 7, cells = cells.sort)
```

Here is the way you could change the background.
```
p <- FeaturePlot(pbmc_small, features = c( "AKR1C3"   , "VDAC3"), blend = TRUE, pt.size = 5,cells = cells, combine = FALSE)
p <- lapply(p, function(x) x+DarkTheme() + NoLegend())
CombinePlots(p)
```
For the error, do you use the latest develop version? It should be resolved.

**Comment by Dragonmasterx87** [comment]
Cheers @yuhanH mate.
