### ISSUE TITLE
The requirement of The requirement of “Differential expression testing”

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#1884]
Recently, I want to use “[Differential expression testing](https://satijalab.org/seurat/v3.0/de_vignette.html)” using my own data.

I wonder whether FindMarkers() function used the raw data (or original expression data, like 1, 2, ...) or used normalized data (like 0.975, -1.23).

specifially, after "_as.matrix(GetAssayData(object = Seurat.object))_", the object with the renamed clusters possessed normalized/computed expression data. I don't know whether it would cause data unreliability.

Should i used the processed Seurat information (such as renamed clusters) to mark the orinal unprocessed merged Seurat.object, hence I could get the object with celltype information and unprocessed expression data? If it's neccessary, how to do it?

**Comment by timoast** [comment]
Hi, you can set the slot to use in `FindMarkers` with the `slot` parameter. You can find documentation for the function by running `?FindMarkers`.

**Comment by grimwoo** [comment]
> Hi, you can set the slot to use in `FindMarkers` with the `slot` parameter. You can find documentation for the function by running `?FindMarkers`.

hi, I still didn't understand the function. Should i use the processed Seurat.object or unprocessed one?

**Comment by timoast** [comment]
Hi, it's unclear what you mean by "processed" and "unprocessed." In your above example you give negative values for normalized data, which only occurs following integration, so I will point out that we do not recommend running differential expression on integrated data, as the integration procedure introduced dependencies between data points that violate the assumptions of differential expression tests.
