### ISSUE TITLE
How could I get the percentage of cells expressing each gene?

### ISSUE THREAD

**Issue by guanyukun** [satijalab/seurat#1888]
Hi,

When I calculate the average expression using “AverageExpression”, how can I obtain the percentage of cells in a cluster expressing each gene at the same time?

I know that "FindMarkers" and "DotPlot" could show both the expression level and the percentage of cells in a cluster expressing any given gene. 
But how could I get the whole genes list with both expression level and the percentage of cells expressing each gene?

Thank you so much!
Yukun

**Comment by yuhanH** [comment]
HI, yukun
You could save the `DoPlot` into an object, and then you could extract the percent value there.
```
cd_genes <- c("CD247", "CD3E", "CD9")
a <- DotPlot(object = pbmc_small, features = cd_genes)
a$data
```
You can find a column called pct.exp which represents the percentage of cells in each cluster

**Comment by guanyukun** [comment]
Hi yuhan,
Thank you so much for your help. 
I can get the percent value based on given genes using "DotPlot".

What if I want to find the gene list with different gene expression or percentage?
How could I get the percentage value & average expression for the transcriptome?

Thank you so much!

**Comment by yuhanH** [comment]
Sorry that I don't fully understand your questions here.  In the DotPlot, you could change the features you have interests.

**Comment by guanyukun** [comment]
Thank you.
I can first find deferentially expressed gene, and then get the percentage value using Dotplot.
Previously, I just want to get the average expression & expression percentage at the same time to figure out the interested genes.

**Comment by ksaunders73** [comment]
Is there a way to do this for a merged gene list plotted onto a single dot plot? The merged code is taken from https://github.com/satijalab/seurat/issues/3521 

nkfocuslist <- list(c("FOS", "TNFAIP3", "NR4A1", "CCL4", "RASGRP2", 
                      "PARVB", "NR4A2"))
sobj <- AddModuleScore(object = sobj, features = nkfocuslist, name = "NK_Focus_List")  
a <- DotPlot(object = sobj, features = c("FOS", "TNFAIP3", "NR4A1", "CCL4", "RASGRP2", 
                                         "PARVB", "NR4A2"))

a <- DotPlot(object = sobj, features = "NK_Focus_List1")

This results in the following: 
![image](https://user-images.githubusercontent.com/62159599/118903302-22704b80-b8dd-11eb-8f22-e116a9699261.png)

Is there a way to get it more like this thread with the gene names by it?
![image](https://user-images.githubusercontent.com/62159599/118903330-33b95800-b8dd-11eb-9ab7-cc1079e4304a.png)
