### ISSUE TITLE
IntegrateData error, subscript out of bound

### ISSUE THREAD

**Issue by jhl0214** [satijalab/seurat#1889]
Hi,
I am trying to integrate 3 data sets of 26x18000, 26x24000, 26x38000. I created seurat objects with each data set and ran "data.anchors <- FindIntegrationAnchors". After that, I tried to run this code:
data.combined <- IntegrateData(anchorset = data.anchors). 
However, it keeps giving me this error:

> Merging dataset 3 into 1
> Extracting anchors for merged samples
> Finding integration vectors
> Warning in irlba(A = t(x = object), nv = npcs, ...) :
>   You're computing too large a percentage of total singular values, use a standard svd instead.
> Warning in irlba(A = t(x = object), nv = npcs, ...) :
>   did not converge--results might be invalid!; try increasing work or maxit
> Finding integration vector weights
> Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds
> 

Can anyone suggest how to fix this error?
Thank you.

**Comment by timoast** [comment]
If you have only 26 features measured in each dataset you will need to adjust the default parameters. You should change the number of dimensions used in each step, the number of features used when filtering anchors (or turn the filtering off entirely by setting `k.filter=NA`), and change `k.weight`. All these parameters need to be less than the number of features measured.

**Comment by JingqunMa** [comment]
I have the same error when following the scATAC-seq integration vignette (https://satijalab.org/signac/articles/integration.html#integration-with-harmony). I've tried different parameters in the FindIntegratonAnchors(set k.filter=NA) and change the default parameters in IntegrateData (change k.weight, dims, weight.reduction). The same error persists:
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds

Any insights for this error or troubleshooting advice, please?

**Comment by amjass12** [comment]
what does k.filter=NA achieve versus leaving it as the default? although it can't be guaranteed how the data will perform, is it a viable option to use this method of integration? in other words, where there are datasets with enough cells, should these be integrated as they would be if the other dataset without min=200 cells was present?

**Comment by deborah-chasman** [comment]
I got the same error message under different circumstances, and I was able to work through it. I'm leaving a comment here in case it's useful for someone in the future.

I was trying to integrate feature barcoding datasets from 10X Genomics. I have 11 features measured in thousands of cells across multiple samples. So in my case, it's not an issue of having too few cells, but having too few features.

I'm using the standard workflow, so these are the steps:

Step 1. FindIntegrationAnchors
Step 2. IntegrateData

Initially I ran FindIntegrationAnchorslike so, and it ran successfully, but I got the same error as Jingqun Ma when I ran IntegrateData.
```
anchors <- FindIntegrationAnchors(object.list=split.datas, assay=rep("FB",length(split.datas)), dims=1:11, max.features=11)

anchor.data <- IntegrateData(anchorset = anchors, new.assay.name = "integrated_FB", dims=my.dims)
```

It seems that I need to set the **anchor.features** parameter, not the dims or max.features, in FindIntegrationAnchors in order to get IntegrateData to work. It works whether I set it to the names of my features (here, fb.names) or an integer up to the number of features (eg 11).

```
fb.names <- rownames(split.datas[[1]][["FB"]])
anchors <- FindIntegrationAnchors(object.list=split.datas, assay=rep("FB",length(split.datas)), anchor.features=fb.names, dims=1:10)

anchor.data <- IntegrateData(anchorset = anchors, new.assay.name = "integrated_FB", dims=1:10)
```

**Comment by Manisha0328** [comment]
@timoast 
Hii,
Seurat is really a useful tool! I am a new to it, facing some issue. Need help to resolve

I am trying to integrate 3 datasets(2 from specieA and 1 from specieB).For this I am following https://satijalab.org/seurat/v3.0/immune_alignment.html pipeline.
It works well when only 2 datasets from specieA are integrated but when dataset from SpecieB is added in the object.list(i.e. neoskin), IntegrateData() gives an error.

Can you please see and tell what am I doing wrong here?
Below is the output from code which I used. 

`> skin2
An object of class Seurat 
14706 features across 1348 samples within 1 assay 
Active assay: RNA (14706 features, 2000 variable features)
> skin3
An object of class Seurat 
10932 features across 328 samples within 1 assay 
Active assay: RNA (10932 features, 2000 variable features)
> neoskin
An object of class Seurat 
13723 features across 1916 samples within 1 assay 
Active assay: RNA (13723 features, 2000 variable features)
> #Perform Integration
> hmskin.anchors <- FindIntegrationAnchors(object.list = list(skin2, skin3,neoskin), dims = 1:20)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 1575 anchors
Filtering anchors
	Retained 1008 anchors
  |+++++++++++++++++                                 | 33% ~22s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 4976 anchors
Filtering anchors
	Retained 869 anchors
  |++++++++++++++++++++++++++++++++++                | 67% ~16s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 1632 anchors
Filtering anchors
	Retained 315 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=45s  
There were 50 or more warnings (use warnings() to see the first 50)
> hmskin.combined <- IntegrateData(anchorset = hmskin.anchors, dims = 1:20)
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds`

Many Thanks!
Any help would be appreciated.

Thank You.
