### ISSUE TITLE
Add MNN out as a dimension reduction in Seurat object

### ISSUE THREAD

**Issue by garsat** [satijalab/seurat#1891]
Hello,

Does any one have an idea how we can add the out put of MNN algorithm as a new dimension reduction in Seurat object.
This an example of the out of fastMNN:

str(out)
List of 5
 $ corrected: num [1:2245, 1:50] -0.1843 0.0975 -0.0785 -0.1308 0.0887 ...
 $ batch    :Formal class 'Rle' [package "S4Vectors"] with 4 slots
  .. ..@ values         : int [1:2] 1 2
  .. ..@ lengths        : int [1:2] 1217 1028
  .. ..@ elementMetadata: NULL
  .. ..@ metadata       : list()
 $ pairs    :List of 1
  ..$ :Formal class 'DataFrame' [package "S4Vectors"] with 6 slots
  .. .. ..@ rownames       : NULL
  .. .. ..@ nrows          : int 4251
  .. .. ..@ listData       :List of 2
  .. .. .. ..$ first : int [1:4251] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. ..$ second: int [1:4251] 1808 1520 1793 1860 1288 1762 1742 1563 2036 1392 ...
  .. .. ..@ elementType    : chr "ANY"
  .. .. ..@ elementMetadata: NULL
  .. .. ..@ metadata       : list()
 $ order    : int [1:2] 1 2
 $ rotation : num [1:20071, 1:50] 0 0 0 0 -0.00105 ...

the function to add a new dimension reduction is :
CreateDimReducObject(embeddings = new(Class = "matrix"),
  loadings = new(Class = "matrix"), projected = new(Class = "matrix"),
  assay = NULL, stdev = numeric(), key = NULL, jackstraw = NULL,
  misc = list())

out$corrected contain the news coordinates of cells which I can use it as embeddings, 
but my issue is the loadings; can I use the feature loadings of my previous object before running MNN algorithm ?

THANKS

**Comment by mojaveazure** [comment]
Hi,

You can run fastMNN directly on a Seurat object using `RunFastMNN` from [SeuratWrappers](https://github.com/satijalab/seurat-wrappers), please see [this vignette](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/fast_mnn.html) for more details.

**Comment by garsat** [comment]
THANKS !!!

**Comment by garsat** [comment]
Hi,

I  successed to install SeuratWrappers and I tried to install SeuratData  but it doesn't work

devtools::install_github('satijalab/seurat-data')

Downloading GitHub repo satijalab/seurat-data@master
✔  checking for file ‘/private/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T/RtmprqnCCO/remotes3c0159aa0332/satijalab-seurat-data-56a538f/DESCRIPTION’ (544ms)
─  preparing ‘SeuratData’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SeuratData_0.1.0.tar.gz’
   
* installing *source* package ‘SeuratData’ ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: unable to access index for repository https://seurat.nygenome.org/src/contrib:
  impossible d'ouvrir l'URL 'https://seurat.nygenome.org/src/contrib/PACKAGES'
Error: package or namespace load failed for ‘SeuratData’:
 .onAttach failed in attachNamespace() for 'SeuratData', details:
  call: pkg[["Package"]]
  error: indice hors limites
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/SeuratData’
Erreur : Failed to install 'SeuratData' from GitHub:
  (converti depuis l'avis) installation of package ‘/var/folders/qz/73f1ych53d96d4m0rj5xrlt00000gp/T//RtmprqnCCO/file3c017c079ed/SeuratData_0.1.0.tar.gz’ had non-zero exit status
>

**Comment by mojaveazure** [comment]
SeuratData is not required for SeuratWrappers, it's merely a data distribution platform for our vignettes. Any issues installing SeuratData should be posted to [its repository](https://github.com/satijalab/seurat-data/issues).
