### ISSUE TITLE
FindTransferAnchors() : Fatal error 

### ISSUE THREAD

**Issue by cchenal** [satijalab/seurat#1892]
Hi, 

I'm trying two integrate scATAC-seq and scRNA-seq data following this vignette : https://satijalab.org/seurat/v3.0/atacseq_integration_vignette.html.

FindTransferAnchors() leads to a fatal error and I have to start a new session. I tried to execute it step by step and it crashes at the RunCCA() function. 

transfer.anchors <- FindTransferAnchors(reference = pbmc.rna, 
                                        query = pbmc.atac, 
                                        features = VariableFeatures(object = pbmc.rna), 
                                        reference.assay = "RNA", 
                                        query.assay = "ACTIVITY", 
                                        reduction = "cca")

Do you have any idea of what could be the problem ?

Thanks a lot, 

Clothilde

**Comment by timoast** [comment]
Hi, what is the error message that appears? I haven't been able to reproduce this, are you able to provide a reproducible example and post the output of `sessionInfo()`?
