### ISSUE TITLE
seurat RNA velocity

### ISSUE THREAD

**Issue by notimenocall** [satijalab/seurat#1893]
Hi,
Thanks for developing the great tools and continuing having new additions.
My question is how to properly implement RNA velocity to Seurat objects. Specifically, what reference should be use for mapping: cDNA/introns info are required for velocity but I think mapping to the whole transcriptome may be more accurate. In this case, can we generate velocity with a seurat object consisting the spliced/unspliced assays and then transfer the calculated velocity info to another seurat object generated by mapping to the transcriptome by matching the cell identities? If so, how to do it? If not, what could be a better strategy?
Thanks much!

**Comment by mojaveazure** [comment]
Hi Xiao,

This is a question for the [velocyto team](https://github.com/velocyto-team), as RNA velocity is their technique. We are able to answer technical questions (eg. how to prepare a Seurat object for `RunVelocity`), though those should be asked over at [SeuratWrappers](https://github.com/satijalab/seurat-wrappers).
