### ISSUE TITLE
Percent proportion of idents in integrated analysis 

### ISSUE THREAD

**Issue by akhst7** [satijalab/seurat#1894]
I did not see this in the tutorial, but is there a such class as a % indents in an integrated object  ? I'd like to plot promotions of each indents.

**Comment by timoast** [comment]
Hi, if you are trying to compute the proportion of different identity classes in each integrated cluster, you can do so using the `table` function in R, for example:

```r
> table(pbmc_small$RNA_snn_res.0.8, pbmc_small$groups)
   
    g1 g2
  0 30 23
  1 14 13
```
