### ISSUE TITLE
an error while computing the differential markers

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#1896]
Dear all, 

i have been using Seurat on two samples in order to find the differential markers between the clusters in those 2 samples : 

**FindMarkers(samples.combined, ident.1 = IDENT1, ident.2 = IDENT2, print.bar = FALSE, only.pos = FALSE)** 

and I am getting the following error (below). Please would you let me know how could I fix it ? Seurat stops after computing the differential expression between half of the clusters. Thanks !

**Error in if (all(unlist(x = strsplit(x = my.var, split = "[0-9]+")) ==  : 
  missing value where TRUE/FALSE needed
Calls: VlnPlot -> data.frame -> FetchData**

**Comment by andrewwbutler** [comment]
Hi,

It's strange that your error calls `VlnPlot`. Could you provide a reproducible example?

**Comment by tanasa** [comment]
thank you Andrew, I hope I will ... just need to find some time now. Thank you for your time and help !

**Comment by tanasa** [comment]
Dear Andrew, i am replying to the message after a long time (my apologies). It has been an oversight on my side, i had tried to print more differential genes than available in a list :                                                            

```
 IDENT1=paste0(i, "_", CTRL)
 IDENT2=paste0(i, "_", STIM)

  LIST.CLUSTERS.and.DIFFERENTIAL.MARKERS[[i+1]] <- FindMarkers(samples.combined, 
                                                                                 ident.1 = IDENT1, 
                                                                                 ident.2 = IDENT2, 
                                                                                 print.bar = FALSE, only.pos = FALSE)

   x <- as.data.frame(as.matrix(LIST.CLUSTERS.and.DIFFERENTIAL.MARKERS[[i+1]]))  
   x$gene <- row.names(x)

   write.table(x, file=paste(NAME, 
  "figure8.samples.combined.here.DIFFERENTIAL.MARKERS.cluster", i, "LIST.txt", sep="."), 
                  sep="\t", quote=F, row.names=T, col.names=T)

   x_count_genes = dim(x)[1]
```
now, it is working. thanks again for your time and help !

**Comment by andrewwbutler** [comment]
No worries. Glad you figured it out.
