### ISSUE TITLE
avg_logFC vs pct

### ISSUE THREAD

**Issue by cBioPort** [satijalab/seurat#1897]
I am trying to analyze scRNA data and doing FindMarkers comparisons between two subclusters. Code used:

`dataBvsC <- FindMarkers(immune.combined, ident.1 = '12_pt8b_pt8b' , ident.2 = '12_pt8c_pt8c' , verbose = FALSE, logfc.threshold = 0) #note I am comparing b to c
`
Excerpt of results and VlnPlot are below.

What's confusing to me is the following:
1) Looking at the table result: Looks like although the gene is expressed in only 8.2% of 12_pt8b_pt8b vs in 87.8% in 12_pt8c_pt8c, the avg_logFC indicates that it is much more abundant (+0.32) in pt8b vs pt8c. Is this being driven by the fact that although only 8.2% express it in sample pt8b, it is so highly expressed that it skews the whole data? Or am I flipping the interpretation

2) Regarding volcano plot today: does the more "red" volcano space in pt8c (left) indicate that more cells express the gene albeit at a lower level compared to pt8b (right) where the expression level is higher but not as many cells express it (hence no violin)?

Or am I flipping the comparisons? 

`

  | p_val | avg_logFC | pct.1 | pct.2 | p_val_adj
-- | -- | -- | -- | -- | --
G0S2 | 2.4E-22 | 0.321116 | 0.082 | 0.878 | 4.79E-19
CXCL2 | 7.26E-18 | 0.263945 | 0.164 | 1 | 1.45E-14
IL32 | 3.62E-17 | 0.33236 | 0.033 | 0.595 | 7.24E-14
MMP25 | 6.29E-17 | -0.31838 | 0.115 | 0.811 | 1.26E-13
ADAM8 | 3.1E-16 | -0.28436 | 0.139 | 0.865 | 6.21E-13
SEPT5 | 1.25E-12 | -0.25507 | 0.049 | 0.514 | 2.51E-09
C1QB | 2.18E-12 | -1.10785 | 0.033 | 0.459 | 4.36E-09
C1QC | 1.41E-11 | -1.11953 | 0.041 | 0.459 | 2.82E-08
PROK2 | 2.34E-10 | -0.45193 | 0.074 | 0.797 | 4.68E-07

`

![image](https://user-images.githubusercontent.com/44423007/61988905-a44b0280-afed-11e9-997e-d7690c8fe0d4.png)

**Comment by andrewwbutler** [comment]
Hi,

1. `pct.1` should correspond to the `ident.1` in the `FindMarkers` call. The percentage of cells expressing a gene in a cluster is not the same thing as the average log FC so it's possible that you can have a small number of highly expressing cells drive the FC value.   Based on the plot, that is likely what is happening here.
2. The width of the violin corresponds to a density estimate so your interpretation here is correct (and makes sense w.r.t your first question).
