### ISSUE TITLE
docs for WilcoxDETest()

### ISSUE THREAD

**Issue by kelly-zalocusky-gladstone** [satijalab/seurat#1899]
Greetings,

I am running Seurat 2.2.1, and using the WilcoxDETest() function. I see that the FindMarkers function provides corrected and uncorrected p-values separately. Is the output from WilcoxDETest() multiple-comparisons corrected or uncorrected p-values? If corrected, which correction (BH, Bonferroni, etc)? It's unclear to me from the docs.

Thanks!

**Comment by yuhanH** [comment]
In the docs of `FindMarkers`, it mentioned that `bonferroni correction` is used for p-value adjustment. 
 p_val from `WilcoxDETest` is not corrected.
