### ISSUE TITLE
Feature plots of genes that don't make it into `object@data`

### ISSUE THREAD

**Issue by ekernf01** [satijalab/seurat#19]
Hi Satija Lab!

In `FetchData`, there is a line to check if the desired variables are genes:

```
        gene_check <- vars.all %in% rownames(object@data)
```

Downstream, this winds up giving errors on genes that get filtered out during setup. Would you consider changing `data` to `raw.data`?

Many thanks from a regular Seurat user.

**Comment by andrewwbutler** [comment]
Closing for now. If you want to pull out specific genes from the raw.data matrix you can do so with `object@raw.data[gene.names, ]`
