### ISSUE TITLE
Multispecies CCA

### ISSUE THREAD

**Issue by Esbertrand** [satijalab/seurat#190]
Hello,

i'm looking for an example of multispecies CCA (basically Human/mouse) as it is shown in your paper.
How do you handle the different gene Ids between the two species for "RunCCA" function?
I have not seen any issue related to this question so far.
Thanks in advance,

Bertrand

**Comment by satijalab** [comment]
We do require prior knowledge for homologous mapping of gene names between multiple species. In our example in the manuscript we use genes with matching gene IDs between species, but could envisage users developing more advanced methods in the future.
