### ISSUE TITLE
DE on RNA Assay - Normalisation after integration?

### ISSUE THREAD

**Issue by graddi** [satijalab/seurat#1900]
Hello,

Thank you very much for your hard work on this wonderful package. Quick question about DE analysis that is still confusing me.

I have followed the immune integration worked example (https://satijalab.org/seurat/v3.0/immune_alignment.html) and found this solved issue: https://github.com/satijalab/seurat/issues/1717

However, I am confused because object@assays$RNA$counts and object@assays$RNA$data seem to have the same values in 'p'. While $scale.data is empty.

1) Should I normalise and scale the RNA assay again after integration before running DE analysis? Or is this done and preserved pre-integration (I understand the DE tests should automatically ignore the scale.data slot and go to data slot or counts slot?)

In your immune tutorial you do not specify any further normalisation. However, in the integration vignette (https://satijalab.org/seurat/v3.0/integration.html) you do:
DefaultAssay(pbmc.integrated) <- "RNA"
pbmc.integrated <- NormalizeData(pbmc.integrated, verbose = FALSE)

2) Do you recommend using FindConservedMarkers or FindAllMarkers (with standard Wilcoxon test) on the RNA assay after integration? I am getting different results for my same clusters running those two analyses without doing any further normalisation on the RNA assay.

Thanks again!

**Comment by yuhanH** [comment]
Q1. It depends on what slot you used for DE analysis.
In both `FindConservedMarkers` and `FindAllMarkers `, the default slot is data, so you don't need to rescale your data.
For the integration vignette, it uses SCTransform to normalize data, so in the RNA assay, the data slot is empty.  When you want to use RNA data slot to calculate DE, you need to generate it. 
For the  immune tutorial, the data is not normalized by SCTransform, so data slot in the RNA assay is already calculate. 
Q2. The DE gene found by `FindConservedMarkers` should be more conserved.  But it is hard to say which you should use. 
Normalize RNA assay before or after integration will make no difference.

**Comment by graddi** [comment]
Thank you!
