### ISSUE TITLE
ADT expression level are the same across Clusters

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#1901]
Hello,

We are analyzing 6 samples. We just noticed that when we run our samples to test the antibody expression across cluster, we found that 3 of our samples showing the same Antibody expression across all the clusters for all the antibody including CD19, which this cannot be true. Then we use Seqgeq to test our samples, we can find the different expression level across cell types there, that means this is not because of our samples.  We are using the same script for all the 6 samples, just wondering why only 3 of them have this issue.

**Comment by timoast** [comment]
Hi, could you provide the code you're running and plots to show how the expression of all ADTs are the same?

**Comment by timoast** [comment]
You can just post the code and plots here

**Comment by timoast** [comment]
The ADT level is not _exactly_ the same, so I don't think this is an issue with the code. It's possible that the antibody binding failed. You could check this by looking at the expression of two proteins that should not co-occur, such as CD8 and CD4. For example: 

```r
FeatureScatter(sample7, "CD8", "CD4")
```
You should not see many cells expressing both proteins.
