### ISSUE TITLE
How to export NormalizeData(data) and ScaleData(data) to csv files?

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1902]
Dear,
I run the following and want to export the data for from normalize and scale steps:

data <- CreateSeuratObject(counts = data) 
data <- NormalizeData(data) 
data1 <- ScaleData(data)
data2 <- FindVariableFeatures(data1)  

Would you please help me how exactly to export the gene data from **NormalizeData(data)** and **ScaleData(data)** to CSV files?

BTW, I am using the v3 Seurat.

Thank you and best wishes,
Jinping

**Comment by yuhanH** [comment]
You could use `GetAssayData` to obtain scale.data and data matrix. Then you could use `write.table` function or any other functions to write them into csv files. 
```
 data.table<- as.matrix(GetAssayData(data, slot = "data"))
 scale.table <- GetAssayData(data1 , slot = "scale.data")
```

**Comment by surljp2012** [comment]
Great, Yuhan!

Thank you,
Jinping
