### ISSUE TITLE
Error about Oversize during running FindIntegrationAnchors().

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1903]
Dear,
I have a dataset, which has million cells both in control (ctrl) and treatment (treated)
When I run the following code, I met the issues in HPC.

immune.anchors <- FindIntegrationAnchors(object.list = list(ctrl, treated)) 
Error: cannot allocate vector of size 135262.9 Gb

How should I solve this problem by setting up some parameters?

Thank you and best wishes,
Jinping

**Comment by timoast** [comment]
Hi Jinping, how many features are you providing for `features.to.integrate`? Running at the scale of >1M cells will require a lot of memory.

**Comment by surljp2012** [comment]
Dear Tim,

I only have 13 selected features.

Yes, I found 200G request in HPC can only run 800K cells after several
trials.

Hopefully, this will be solved in the future.

Thank you and best wishes,
Jinping
