### ISSUE TITLE
Can monocle V2 support be added to Seurat 3 CRAN version?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1904]
Hello, I have a question. You said that Monocle v2 support is present in the development version of Seurat in this issue https://github.com/satijalab/seurat/issues/1658#issuecomment-501747208) ,So it means that we can convert seurat v3 object to monocle 2 celldataSet object through the development version?Is there any tutorial about how to make this conversion in this version?I couldn't find it.
Since monocle 3 is not finished, I imported the Seurat3 integrated data to monocle2 to do analysis.Could you add monocle V2 support to Seurat 3 CRAN version?I think it does good to users.
Also, with this new conversion capability, will the CDS be able to accept both original RNA counts and integrated RNA counts from a Seurat 3 object?

**Comment by mojaveazure** [comment]
Seurat &harr; Monocle v2 converters have been available on the CRAN version of Seurat for a month and a half now; please read the [NEWS file](https://cran.r-project.org/web/packages/Seurat/news/news.html) for a list of additions and changes for all CRAN releases.

While we don't have specific tutorials for Seurat &harr; Monocle conversions (we're an academic lab, not a software development company with resources to develop tutorials for every feature), we encourage you to read the documentation for [`as.CellDataSet`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/as.CellDataSet) and [`as.Seurat`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/as.Seurat)
