### ISSUE TITLE
loom does not appead to be a valid Loom file according to Loom spec version '2.0.1'

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#1906]
I exported the seurat.object as a loom file. However , I cannot import it in scanpy. Could you help me?

Seurat command :
#Patient.combined.loom <- as.loom(Patient.combined, filename = "D:/personal data/Wu #Haoda/Ependymoma/Seurat Processed #Data/Processed_Information_of_Patient_with_Raw_Expression.loom", verbose = FALSE)
#Patient.combined.loom
#Always remember to close loom files when done
#Patient.combined.loom$close_all()

Scanpy command:
#adata = sc.read_loom('Object.loom')
The error information was listed bellow:
_ValueError: Row attribute 'gene_names' dtype object is not allowed
Column attribute 'ClusterName' dtype object is not allowed
Column attribute 'Patient' dtype object is not allowed
Column attribute 'cell_names' dtype object is not allowed
Column attribute 'integrated_snn_res_0_2' dtype object is not allowed
Column attribute 'orig_ident' dtype object is not allowed
Column attribute 'seurat_clusters' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
**Object.loom does not appead to be a valid Loom file according to Loom spec version '2.0.1'_**

**Comment by yuanbell** [comment]
I have met the exactly same issue. Have you fix this issue? Could you please tell me how?

**Comment by rsatija** [comment]
We are closing this issue now as we are no longer prioritizing support for loom conversion.

In Seurat v5, we include support for the [v5 assay class](https://satijalab.org/seurat/articles/seurat5_essential_commands.html), which can flexibly store data in a variety of formats (including disk-backed formats). We include multiple examples for disk-backed analysis using the [BPCells package from Ben Parks ](https://github.com/bnprks/BPCells).
