### ISSUE TITLE
Feature barcoding: Remove Batch Effect of Patients

### ISSUE THREAD

**Issue by ATA82** [satijalab/seurat#1907]
Hi,

I have data from 10x (scRNA-Seq + FeatureBarcoding). The data are from two different patients for each patient we used an different feature barcode for CD45 (we didn't used HTO due to some constraints). I have generated this feature plot with Seurat:

![Compartments_CD45_both](https://user-images.githubusercontent.com/26165262/62124666-11e77f00-b2cb-11e9-98a0-56c1b370ba44.png)

here we can clearly see the batch effect.

It would be very nice, if you can suggest to me the best way to remove this batch effect with Seurat 3.

Thank you very much in advance

Best Regards

**Comment by satijalab** [comment]
1. Even though you did not use an HTO, you effectively performed cell hashing. So, you can use the CD45.1 levels to assign cells to individually patients (for example, with HTODemux). 

2. Then you can align datasets across patients (examples at https://satijalab.org/seurat/v3.0/integration.html)

**Comment by ATA82** [comment]
Thank you very much!
