### ISSUE TITLE
Differential expression analysis between two groups within a specific cluster 

### ISSUE THREAD

**Issue by LBerthoin** [satijalab/seurat#1908]
Hello,

I would like to know what genes are differentially expressed between a group A and a group B, within a specific cluster c.

I have created a combined objet between A and B using Seurat V3 following the comparative analysis vignette and was able to generate different types of graph showing some alterations between the two groups. However, I would like to be more quantitative and find out what genes are altered in group A compared to group B and the level of variation.

Is there a script for generating a csv file for this type of comparison?

Best,

Lionel

**Comment by timoast** [comment]
Hi, please see the [immune alignment vignette](https://satijalab.org/seurat/v3.0/immune_alignment.html) for an example of how to do differential expression testing between conditions within a cluster.
