### ISSUE TITLE
Surat-Identify differential expressed genes across conditions

### ISSUE THREAD

**Issue by ShakirHasan** [satijalab/seurat#1909]
Hello,
I have been trying to find differentially expressed genes between steady-state and treated conditions with a given a cluster. A UMAP dimension reduction resulted in 7 clusters. However, where I use the Seurat-Identify differential expressed genes across conditions, as shown in "Tutorial: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses", the command for each cluster results in the same 20 genes popping up, although the cells types and expression patters across the clusters are very heterogenous. Following is the command line: 

```{r}
diff1 <- subset(Epi.combined, idents = "1")
Idents(diff1) <- "treat"
avg.diff1 <- log1p(AverageExpression(diff1, verbose = FALSE)$RNA)
avg.diff1$gene <- rownames(avg.diff1)
head(rownames(avg.diff1), 20)
```
This command line was for finding the differentially expressed genes within cluster 1 in SS and treated conditions. However, the same set of genes pop up no matter which cluster I run it for. I have chosen not to rename the clusters yet. Anyone has faced this issue? Any solutions? Thank you in advance.

**Comment by timoast** [comment]
If you have certain genes that are upregulated across all cell types in a treatment condition, the these will be identified in all cluster comparisons. However, this won't prevent the identification of cell-type-specific genes, so you should be able to look at the output of `FindMarkers` further and identify these genes if they exist. See https://github.com/satijalab/seurat/issues/1850 for more info on DE between conditions within a cluster.

**Comment by LooLipin** [comment]
Hi @timoast, I've used the FindMarkers function to find DE genes between genotypes in my clusters and I've noticed something peculiar. 

`Markers <- FindMarkers(combined, ident.1 = "WT", ident.2 = "MUT", group.by = "gt", subset.ident = "0", test.use = "wilcox", )`

At first I thought this was really cool but then I noticed that DE genes are detected to be expressed in higher % in population 2 (ident.2, in this case mutant cells). I have repeated this on other datasets and regardless of genotypes or conditions, the second population always has more cells with genes expressed. 
<img width="732" alt="Screen Shot 2019-11-01 at 4 24 10 pm" src="https://user-images.githubusercontent.com/57159632/68004037-0f2e6880-fcc4-11e9-9709-689c5b9f7c8b.png">

I did a sanity check and calculated the % of cells expressing the Gusb gene in this cluster and it's actually quite similar in %. Is the code I'm using for subset.ident actually counting something else? Please advise. Thanks.
