### ISSUE TITLE
Adjusted p-values  - Benjamini Hochberg?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#191]
Hello Seurat Team,

It is great that Seurat now gives out the Bonferroni adjusted p-values for Diff Expression analysis.  But as it is known, Bonferroni correction is very stringent, at least for some situations.  So, is there a plan to include the popular Benjamini-Hochberg (aka FDR) method?

In any case, if I were to compute BH values outside Seurat using the regular pvalues given out by Seurat and the R function p.adjust, do I just input the total number of genes in the dataset to the function?  My worry is, the function p.adjust assumes that all the unobserved p-values are 1.  Would that affect the results?  If you were to do this inside Seurat, would you do the same, or is there any way I can get out the actual p-value for every gene in the dataset?

Any thoughts or tips would be greatly appreciated!

Thanks.

**Comment by satijalab** [comment]
We are not planning to implement BH correction. You can certainly run your own p-value correction techniques on the output of FindMarkers, with the caveats that you mention.

**Comment by CodeInTheSkies** [comment]
OK, thanks.  Any specific reason that you think BH correction is disadvantageous?  Just curious, since you said you don't plan on implementing it in Seurat although BH is a widely used p-value correction technique.

**Comment by joshuagi** [comment]
I was recently wondering about the same thing. I would also like to perform BH correction on the p-values from FindMarkers. 

My problem is that FindMarkers only returns results of a few 100 genes instead of all the genes in the dataset. Do you have any suggestions on how I can get FindMarkers to return the whole list? I'll try BH correction on my own afterwards.

**Comment by winni2k** [comment]
> OK, thanks. Any specific reason that you think BH correction is disadvantageous? Just curious, since you said you don't plan on implementing it in Seurat although BH is a widely used p-value correction technique.

I would also be very interested in an answer to this question.

**Comment by diala-ar** [comment]
You can run FindMarkers in a way to keep all genes in the results and then apply the Benjamini and Hochberg pvalue correction using the code below:
degs = FindMarkers(seur, ident.1=clust_1, ident.2=clust_2, logfc.threshold=0, min.pct=0, min.diff.pct=0)
degs$p_val_adj = p.adjust(degs$p_val, method='fdr')

**Comment by ismailelshimy** [comment]
@diala-ar To include all genes in the analysis, the min.diff.pct should be kept equal to the default value of -Inf, otherwise if you set it to zero, you will exclude genes that have a lower detection fraction in the test group than in the control group

**Comment by jgarces02** [comment]
How is `p.adjust` considering zero P-values ([because smaller than can be represented](https://github.com/satijalab/seurat/issues/1474))? Is it including them?
