### ISSUE TITLE
Adjustment for multiple conditions

### ISSUE THREAD

**Issue by pagarwal14** [satijalab/seurat#1911]
In FindMarkers is there a way to compare multiple conditions and correct for the resulting multiple comparisons (multi-way ANOVA).  The way it works now it looks like only pair-wise comparison between two conditions can be done.  I have an experiment that has 5 conditions and would like to test for gene expression differences between each and be able to correct for multiple comparison based on the gene set (which I guess is the default ) as well as multiple treatment conditions.
Thanks,
- Pankaj

**Comment by timoast** [comment]
Sorry for the delay here. We currently only support pairwise comparisons in `FindMarkers`. You can run `FindAllMarkers` to perform each one-vs-all comparison
