### ISSUE TITLE
DoHeatmap average expression

### ISSUE THREAD

**Issue by jhl0214** [satijalab/seurat#1912]
Hi,
I am trying to draw a heatmap with average expression instead of having all the cells on the heatmap. So, I have 14 clusters and 26 features. I want the heatmap to have only one color for each cluster per feature, total of 26x14 colors. 
I have looked at the guide where AverageExpression(object, return.seurat=True) is used. The guide then just did "DoHeatmap(return object of the AverageExpression)". 
However, when I tried that with my own data, it keeps giving me this error:
Error in names(x) <- value : 
  'names' attribute [3] must be the same length as the vector [1]

`cluster.averages <- AverageExpression(data.combined, return.seurat=TRUE)
DoHeatmap(cluster.averages)`
where data.combined is a seurat object from using IntegrateData().

**Comment by yuhanH** [comment]
The object `cluster.averages` doesn't have variable genes. You need to set features for the function `DoHeatmap`
