### ISSUE TITLE
Filter Cells by Percent Mito Content for Integrated + SCTransform

### ISSUE THREAD

**Issue by MediciPrime** [satijalab/seurat#1913]
I noticed that the scTransform tutorial didn't have any mention of filtering cells based on mitochondrial content.  I was wondering if it's bad to filter cells based on high mito.percent and w/in a certain nFeature_RNA threshold.  I am asking this because I am not sure if the integrated + sctransform analysis makes it so that filtering cells based on high mito.percent and nFeature_RNA is no longer required or even potentially detrimental to the analysis.  

Thank you!

**Comment by satijalab** [comment]
The filtering and downstream normalization steps are separate, so you should not adjust your filtering steps based on how you normalize the data. I suppose we don't do QC filtering on mitochondrial percentage in the SCTransform vignette, but that just means we are accepting the 10X defaults that comes out of CellRanger.

**Comment by MediciPrime** [comment]
Thank you!
