### ISSUE TITLE
errors when runing RunPCA

### ISSUE THREAD

**Issue by tianchen2019** [satijalab/seurat#1914]
When I run 
klf5_d2 <- RunPCA(klf5_d2, features = VariableFeatures(object = klf5_d2))
the error is : Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

the number of cells is 42, the number of features is 20239.
When i use the data having 95 cells , it works well. So, Is it because there are so few cells?

**Comment by timoast** [comment]
The default number of PCs to compute is 50, so you are trying to find more components than there are cells. You need to set `npcs` to less than the smallest dimension of the dataset

**Comment by plijnzaad** [comment]
> The default number of PCs to compute is 50, so you are trying to find more components than there are cells. You need to set `npcs` to less than the smallest dimension of the dataset

Just to clarify: the _genes_ x _cells_ matrix is rotated to a _PC_ x _cells_ matrix so mathematically, only the number of genes is relevant. E.g. `prcomp(t(matrix(rnorm(24), nrow=3, ncol=8)))` (3 'genes', 8 'cells') and `prcomp(t(matrix(rnorm(6), nrow=3, ncol=2)))` (3 'genes', 2 'cells') work perfectly fine. The `min(nrow(A), ncol(A))` is probably needed for `irlba` to work fast.
