### ISSUE TITLE
Error: Unable to find a DimReduc matching one of 'umap', 'tsne', or 'pca', please specify a dimensional reduction to use > 

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1916]
Dear,
I am trying the tutorial: https://satijalab.org/seurat/Seurat_AlignmentTutorial.html

And code has error is the second line: 

**pbmc <- RunCCA(object = tenx, object2 = seqwell, genes.use = hvg.union)
p1 <- DimPlot(object = pbmc, reduction.use = "cca", group.by = "protocol", pt.size = 0.5, do.return = TRUE)**
Error: Unable to find a DimReduc matching one of 'umap', 'tsne', or 'pca', please specify a dimensional reduction to use 
I tried both Seurat 2.2.0 and Seurat develop older version:

Both showed the error.

Would you please give me some suggestions to solve this problem?

Thank you

**Comment by mojaveazure** [comment]
The error message
> Error: Unable to find a DimReduc matching one of 'umap', 'tsne', or 'pca', please specify a dimensional reduction to use

is present only in Seurat v3; `DimPlot` did not try to automatically find a dimensional reduction in Seurat v2

If you want to use Seurat v2, please see the "Previous Versions" tab on [this page](https://satijalab.org/seurat/install) for installation details; if you want to use Seurat v3, please see check your parameters for [`DimPlot`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/DimPlot)

**Comment by surljp2012** [comment]
Thank you, Paul!

Best wishes,
Jinping
