### ISSUE TITLE
FindAllmarkers gene output

### ISSUE THREAD

**Issue by kumara3** [satijalab/seurat#1917]
Hello,

I have used the below code to output all the genes in each of the cluster of a seurat object
Obj <- FindAllMarkers(Obj, only.pos = FALSE,min.pct = -Inf, logfc.threshold = -Inf)

The output from FindAllMarkers shows my gene of interest (say geneX) in few specific clusters and not all the clusters, even though geneX is being expressed in all the clusters. What could be the reason of geneX not showing up in all the clusters?

Please let me know.

Ashwani

**Comment by yuhanH** [comment]
Do you mean that geneX should not be a marker for any cluster?
One more question. What slot you used show geneX is being expressed in all the clusters?
You could add the `slot` in the function `FindAllMarkers`.

**Comment by kumara3** [comment]
1)geneX should appear in all the clusters
2) I am using slot="data" (normalized values relative to all the genes in a cell)

**Comment by kumara3** [comment]
Any update on this? Please let me know

**Comment by timoast** [comment]
If gene X is expressed equally in all clusters then it should not show up as differentially expressed in any of the comparisons, so the output of `FindAllMarkers` makes sense
