### ISSUE TITLE
Error in .replace_seqlevels_style(x_seqlevels, value) :    found no sequence renaming map compatible with seqname style "UCSC" for this object

### ISSUE THREAD

**Issue by cuperusj** [satijalab/seurat#1918]
While creating the activity matrix for 10x ATAC on Arabidopsis, CreateGeneActivityMatrix is attempting to check the genome names against the UCSC naming scheme, which doesnt exist for Arabidopsis.

activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "/Users/cuperusj/Downloads/genes.gtf", upstream = 400, verbose = TRUE, seq.levels = c("Chr1", "Chr2", "Chr3","Chr4","Chr5"))

Error in .replace_seqlevels_style(x_seqlevels, value) : 
  found no sequence renaming map compatible with seqname style "UCSC" for this object

I also attempted to manually change this in the code to Tair9, but there were additional issues

**Comment by timoast** [comment]
Hi, this is because the `GenomeInfoDB` package does not provide a mapping between TAIR9 and UCSC-style chromosome names. Since you're only using chr1:5 (no chloroplast), you might be able to get around this by just making the chromosomes in your gtf start with lowercase "chr" rather than "Chr".

**Comment by timoast** [comment]
I will also add that we are working on more detailed methods for scATAC-seq analysis through the [Siganc](https://github.com/timoast/signac) package

**Comment by cuperusj** [comment]
ok thanks, I’ll have to reprocess everything with the new gtf file, so ill reply in like 2 days after that is done.

**Comment by timoast** [comment]
You shouldn't need to reprocess anything, just changing the chromosome names in the GTF and expression matrix.

**Comment by cuperusj** [comment]
Any good recommendations for altering a h5 file, I have no experience doing this

**Comment by timoast** [comment]
Once you read in the matrix using `Read10X_h5`, change the row names, for example:

```r
counts <- Read10X_h5(file)
rownames(counts) <- gsub(pattern = "Chr", replacement = "chr", x = rownames(counts))
```

To change the GTF file on-disk, you can use `sed` (running on command line):

```
sed -e 's/Chr/chr/g' genes.gtf > genes_ucsc.gtf
```

**Comment by cuperusj** [comment]
well since you are here Ill just keep peppering things at you…

peaks matrix looks correct I think...

activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "/Users/cuperusj/Downloads/genes_ucsc.gtf", 
+      upstream = 400, verbose = TRUE, seq.levels = c("chr1", "chr2", "chr3","chr4","chr5"))
Error in `$<-.data.frame`(`*tmp*`, "peak", value = ":-") : 
  replacement has 1 row, data has 0
> 
> head(peaks)
6 x 161163 sparse Matrix of class "dgCMatrix"
   [[ suppressing 65 column names ‘GATGGCCGTGCATTGT-1’, ‘TCGGGACCACATAAAG-1’, ‘CCACGTTAGTATACGA-1’ ... ]]
                                                                                                                                              
chr1:325-4016    . . . . 2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:4629-4753   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:6033-6894   . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:8449-9898   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:13501-15776 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:18917-19590 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
                           
chr1:325-4016    . . ......
chr1:4629-4753   . . ......
chr1:6033-6894   . . ......
chr1:8449-9898   . . ......
chr1:13501-15776 . . ......
chr1:18917-19590 . . ......


head genes_ucsc.gtf
chr1	Araport11	5UTR	3631	3759	.	+	.	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	exon	3631	3913	.	+	.	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	start_codon	3760	3762	.	+	.	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	transcript	3760	3913	.	+	0	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	exon	3996	4276	.	+	.	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	transcript	3996	4276	.	+	2	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	exon	4486	4605	.	+	.	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	transcript	4486	4605	.	+	0	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	exon	4706	5095	.	+	.	transcript_id "AT1G01010.1"; gene_name "AT1G01010"
chr1	Araport11	transcript	4706	5095	.	+	0	transcript_id "AT1G01010.1"; gene_name "AT1G01010"

**Comment by timoast** [comment]
Ok there's another problem, which is that the `CreateGeneActivityMatrix` function filters out anything not labelled as "gene" in the gtf. In the Araport11 annotation, the coding genes are labelled "CDS", and so we're left with nothing after the filter.

A workaround is to replace CDS with gene in the gtf, so if you run:

```
sed -e 's/CDS/gene/g' genes_ucsc.gtf > genes_corrected.gtf
``` 

it should then work (I tried on the araport annotation)

**Comment by timoast** [comment]
I'm going to assume this has solved the issue @cuperusj since I have not heard back

**Comment by cuperusj** [comment]
Yep. Thanks.
