### ISSUE TITLE
Data QC by -Mt issue

### ISSUE THREAD

**Issue by Jingchen1996** [satijalab/seurat#1919]
When I tried to use the command  PercentageFeatureSet with pattern = "^Mt-" (mice genome), it gives me 0 for all data. When I looked at the gene file, I realized that no genes started with the name Mt-. And genes that start with Mt were a mix of mitochondrial and non-mitochondrial genes. How can I solve this issue and perform QC by mitchondria RNA count?

**Comment by chlee-tabin** [comment]
If the following command

```
grep( "^mt-", rownames(seurat.object), value = T)
```

produces values (in my case), you could substitute the pattern to "^mt-" to achieve the objective. If your gene lists are in some IDs (Ensembl IDs etc.), need to look for the mapping (most likely using `bioMart`).

**Comment by Jingchen1996** [comment]
> If the following command
> 
> ```
> grep( "^mt-", rownames(seurat.object), value = T)
> ```
> 
> produces values (in my case), you could substitute the pattern to "^mt-" to achieve the objective. If your gene lists are in some IDs (Ensembl IDs etc.), need to look for the mapping (most likely using `bioMart`).

the command gives me Error in rownames(seurat.object) : object 'seurat.object' not found

**Comment by mojaveazure** [comment]
@Jingchen1996 

The pattern '^Mt-' looks for features starting with "Mt-" (case specific). In order to get `PercentageFeatureSet` to work on your data, you need to adjust the pattern for your specific mitochondrial genes. You can learn more about patterns by learning about [regular expressions](https://en.wikipedia.org/wiki/Regular_expression).

As for @chlee-tabin's example, the 'seurat.object' is simply a placeholder for a `Seurat` object; you have to replace that with the name of your `Seurat` object

**Comment by Jingchen1996** [comment]
> @Jingchen1996
> 
> The pattern '^Mt-' looks for features starting with "Mt-" (case specific). In order to get `PercentageFeatureSet` to work on your data, you need to adjust the pattern for your specific mitochondrial genes. You can learn more about patterns by learning about [regular expressions](https://en.wikipedia.org/wiki/Regular_expression).
> 
> As for @chlee-tabin's example, the 'seurat.object' is simply a placeholder for a `Seurat` object; you have to replace that with the name of your `Seurat` object

Ah, I see. the return is 0. I think the gene names in the data for mitochondria gene does not start with "mt-" and ones that start with "mt" are not specifically mitochondria genes.

**Comment by chlee-tabin** [comment]
Double check whether your transcriptome annotation to derive your single cell count matrix contains mitochondrial chromosomes at all. I have seen in publicly available single cell dataset omission of mitochondrial chromosome at all.

There are really not that many mouse mitochondrial genes there so you could even manually find those genes and pick them for calculation.

**Comment by Jingchen1996** [comment]
> Double check whether your transcriptome annotation to derive your single cell count matrix contains mitochondrial chromosomes at all. I have seen in publicly available single cell dataset omission of mitochondrial chromosome at all.
> 
> There are really not that many mouse mitochondrial genes there so you could even manually find those genes and pick them for calculation.

what are some other ways for QC besides mitochondrial genes and feature counts?
