### ISSUE TITLE
leiden algorithm memory error

### ISSUE THREAD

**Issue by kevin199011** [satijalab/seurat#1921]
Hi, I was using leiden algorithm in the FindCluster on a data with 38000 cells. However, it returns below error:
Error in py_call_impl(callable, dots$args, dots$keywords) : MemoryError: 
Using louvain algorithm didn't return errors. Could you please help to figure this out? Thank you!

Kevin

**Comment by timoast** [comment]
Hi Kevin,

Could you provide a reproducible example with a dataset in the [SeuratData](https://github.com/satijalab/seurat-data) package, and the output of `sessionInfo()`?
