### ISSUE TITLE
ifelse multiple condition

### ISSUE THREAD

**Issue by naomi-croft** [satijalab/seurat#1923]
I am doing single cell sequencing analysis. 
I have 11 different samples which I have merged together on seurat to make one matrix. All barcodes for each sample is labelled ..._01 ..._02 ..._03 etc. I have made a tSNE plot which clusters cell types together. 
I now want to show on the same tSNE plot how the different samples are distributed. I have managed to make a script which can do this for each individual sample;

myPCA <- Embeddings(object = allsample.data.seurat[['tsne']])
samples <- row.names(myPCA)
myPCA <- as.tibble(data.frame(id = samples, myPCA, row.names = NULL))
myPCA <- separate(myPCA, id, sep = "_", into = c("barcode", "sample"))
ggplot(myPCA, aes(tSNE_1, tSNE_2, colour = sample)) + geom_point()
myPCA$samples<- ifelse(myPCA$sample == "01", "sample 1", "all other samples")
a <- ggplot(myPCA, aes(tSNE_1, tSNE_2, colour = samples)) + geom_point(size = 1, alpha = 1)
a + scale_colour_manual(values = c("grey", "red"))

This shows a plot with sample 01 as red and the rest of the samples as grey. 

However, several of my samples are from the same tissue (i.e. sample 01, 02 and 05 are all from spleen). How can I show all spleen samples in red and the rest of the samples in grey?

I tried simply doing this:
myPCA$samples<- ifelse(myPCA$sample == c("01","02", "05"), "sample 1", "all other samples")

But that didn't work.

Any suggestions would be very helpful!

**Comment by chlee-tabin** [comment]
```
myPCA$samples<- ifelse(myPCA$sample %in% c("01","02", "05"), "sample 1", "all other samples")
```

would work I guess!

**Comment by naomi-croft** [comment]
Thank you! That worked!
