### ISSUE TITLE
BuildClusterTree in SCT

### ISSUE THREAD

**Issue by chlee-tabin** [satijalab/seurat#1924]
Hi,

Seems like the automatic bot is closing the issue because of the lack of information from the original author, so I put it by myself. I still get an error using the `slot="scale.data"` fix for the SCTransformed data. Shown in the following comment for minimal reproduction:

https://github.com/satijalab/seurat/issues/1559#issuecomment-516269481

**Comment by chlee-tabin** [comment]
P.S. Somehow the above link was broken, so I fixed it for your reference.

**Comment by andrewwbutler** [comment]
Hi,

The code you provided in #1559 doesn't reproduce any errors for me. Could you try with the latest develop version from a fresh R session?

```R
test <- CreateSeuratObject( counts = GetAssayData( pbmc_small, assay = "RNA", slot = "counts" ), meta.data = pbmc_small@meta.data )
test <- SCTransform( test )
Idents( test ) <- Idents( pbmc_small )
BuildClusterTree( test, slot = "scale.data" )
```

**Comment by chlee-tabin** [comment]
Thank you, after updating from Seurat_3.0.3.9023 to Seurat_3.0.3.9024 solved the problem!
