### ISSUE TITLE
Overload the memory: Running FindIntegrationAnchors(), it need allocate vector size of 135262.9 Gb

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1926]
Dear,
I have million cells and when try to run tutorial **Stimulated vs Control PBMCs**:https://satijalab.org/seurat/v3.0/immune_alignment.html

The error generated:
immune.anchors <- FindIntegrationAnchors(object.list = list(ctrl, treated))
Error: cannot allocate vector of size 135262.9 Gb

How should I set up parameter to solve the overloaded memory.

Thank you and best wishes,
Jinping

**Comment by satijalab** [comment]
We're working on a reduced-memory version of cca-based alignment. In the mean time, you can use reciprocal PCA as an alternative to align your data. You can see issue #1720 for an example

**Comment by surljp2012** [comment]
Thank you so much for your suggestions!

Best wishes,
Jinping
