### ISSUE TITLE
SCT assay and FindAllMarkers for DoHeatmap

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#1928]
Hello everyone,
I'm using the SCT method and as I understand, DGE should be done with RNA assay. 
I did DefaultAssay(x)<-"RNA" then did FindAllMarkers, then DoHeatmap, I get an error that says  No requested Features found in the scale.data slot for the RNA assay. I tried to then do DefaultAssay(x)<-"SCT" and then plot the heatmap again, but it's ugly and a lot of genes are omitted. 
How do I turn around that? 
Thank you

**Comment by yuhanH** [comment]
When you normalize data by SCTransform, the `data` and `scale.data` slots are empty in the RNA assay. You need to change the default assay to RNA and run `NormalizeData` and `ScaleData` to generate data for those two slots.
