### ISSUE TITLE
Does AverageExpression return log-normalized values?

### ISSUE THREAD

**Issue by dhb2128** [satijalab/seurat#193]
HI,
In the code, it looks like AverageExpression only returns log-normalized values if return.seurat is on? In the docs it says that "Output is in log-space, but averaging is done in non-log space." but I don't see in the code where it's converted back to log-normalized values? If return.seurat is true NormalizeData is run, but if not there's no equivalent log1p. Am I reading the code right?

**Comment by kathirij** [comment]
Hello,
   Looks like I am also seeing the same issue. AverageExpression returns data in non-log space even though the docs say that output is in log-space. Is it the issue with newer Seurat version? Because the older seurat definitely returned average expression values in log space.

**Comment by mschilli87** [comment]
@dhb2128: If you already checked the code, it's probablt trivial for you to open a PR fixing this issue.
In my experince, this is a much faster way to resolve thing then waiting for an answer to an issue. :wink:

**Comment by satijalab** [comment]
Correct, if you set return.seurat=T, NormalizeData is called which by default performs log-normalization. Otherwise we do not log-normalize. Apologies if this is slightly different than the previous version, but was intended to give more flexibility.

**Comment by mschilli87** [comment]
@satijalab: Shouldn't the docs be updated in this case?
If they say "Output is in log-space, but averaging is done in non-log space."  and that's not true, I wouldn't consider this isue resolved and close it. :wink:

Maybe I just missed sth...

**Comment by mojaveazure** [comment]
@mschilli87 @dhb2128 @kathirij The documentation has been updated in the develop branch to reflect the behaviour of AverageExpression. Please see [this page](http://satijalab.org/seurat/devinstall.html) for instructions on installing the development version of Seurat.

**Comment by dhb2128** [comment]
The other issue I have with AverageExpression is that with the return.seurat option, the results can become inaccurate if you use a small number of genes (in the argument genes.use) since only this subset of genes is then used in the call to NormalizeData. With few genes the sum of their counts may not match the number of UMIs for that cell. 

Therefore, if you call AverageExpression and then SubsetData with the genes you're interested in you get a different answer then if you call AverageEpression with that subset of genes via genes.use. 

Not sure what's the best way around this. Rather than calling normalize data, would doing log1p(obj@raw.data * 1e4) make more sense?

**Comment by malosreet** [comment]
I think there is a discrepancy in the values returned by AverageExpression when using the "data" slot when there are some identities which contain only a single cell.  When there is a single cell for an identity, and the "data" slot is selected, the log-normalized values are returned corresponding to that single cell. For all other identities (with more than one cell), the function uses mean(expm1(x)) which gives the non-log normalized averages.
