### ISSUE TITLE
Error in example code in 'Seurat - Interaction Tips' vignette

### ISSUE THREAD

**Issue by nolanpokpongkiat** [satijalab/seurat#1931]
```
# How do I create a UMAP plot where cells are colored by replicate?  First, store the current
# identities in a new column of meta.data called CellType
pbmc$CellType <- Idents(pbmc)
# Next, switch the identity class of all cells to reflect replicate ID
Idents(pbmc) <- "replicate"
DimPlot(pbmc, reduction = "umap")
# Switch back to cell type labels
Idents(pbmc) <- "CellType"
```

Just wanted to address this chunk of code that is supposed to plot cells with UMAP and color by the replicate/condition they came from. There's a bit of an error in the code-- assuming you set the replicate upon loading as follows....
```
# Load in data using the Read10X function
IMQ1.data <-Read10X(data.dir = "data/m_IMQ_7d_1_IMQ1_mex"))
IMQ1 <- CreateSeuratObject(counts =IMQ1.data, project = "1", min.cells = 3, min.features = 200)
IMQ1@meta.data$replicate <- "IMQ1" 
...
IMQ2.data <-Read10X(data.dir = "data/m_IMQ_7d_1_IMQ2_mex"))
IMQ2 <- CreateSeuratObject(counts =IMQ2.data, project = "1", min.cells = 3, min.features = 200)
IMQ2@meta.data$replicate <- "IMQ2" 
...
```
... then you can do the following to change the UMAP to plot and color by replicate instead of cluster:

```
# saves the current cell types (defined in "Idents") to imq.combined 
imq.combined$CellType <- Idents(imq.combined)
# sets the replicates as the cell "identities"
Idents(imq.combined) <- imq.combined@metadata$replicate 
# plot with identity as replicate
DimPlot(imq.combined, reduction = "umap")
# assign the identities back to the cell type
Idents(imq.combined) <- imq.combined$CellType
```

Just sharing in case anyone has the same issue!

**Comment by mojaveazure** [comment]
I'm curious as to what the issue with the vignette's code is? The steps you've outlined here are the same as what the vignette is doing, just not using Seurat's shorthand for metadata columns.

**Comment by nolanpokpongkiat** [comment]
Sorry, correct me if I’m wrong— doesn’t assigning `Idents(pbmc) <- “replicate”` assign the identity of every cell to the string literal “replicate”?

**Comment by mojaveazure** [comment]
Not always. If the character string is a column name in object metadata, then it will pull that column. For example:

```R
> data("pbmc_small") # Load the pbmc_small object, included with Seurat
> pbmc_small
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne
> levels(pbmc_small) # Get the unique identity classes
[1] "0" "1" "2"
> names(pbmc_small[[]]) # Get the column names of object metadata
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8"
[5] "letter.idents"   "groups"          "RNA_snn_res.1"  
> Idents(pbmc_small) <- 'groups' # Assign cell identities to the groups column
> levels(pbmc_small)
[1] "g2" "g1"
> Idents(pbmc_small) <- 'pbmc_small' # Assign cell identities to the string literal 'pbmc_small'
> levels(pbmc_small)
[1] "pbmc_small"
```
Examples showcasing this functionality can be found in the [documentation for `Idents<-`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/Idents)

**Comment by PerkyTussellop** [comment]
Thank you, Paul, for all the effort you're putting to answering people online. I'm new to all this. What is "g2" and "g1" symbolizing here in your example? I'm a bit confused re: the concept of levels of cell identity in Seurat.
