### ISSUE TITLE
For each cluster, find how many cells came from each original condition/replicate?

### ISSUE THREAD

**Issue by jeff-li-98** [satijalab/seurat#1932]
I am trying to determine the cluster membership by replicate but am having difficulty tabulating from which replicate cells came from. 

```
table(Idents(pbmc), pbmc$replicate)
```

I found this in the documentation at https://satijalab.org/seurat/v3.0/interaction_vignette.html but it doesn't seem to work-- it seems to tabulate the replicates against themselves.

**Comment by mojaveazure** [comment]
What is the result of `all(Idents(pbmc) == pbmc$replicate)`? If the result it `TRUE`, then your object has the `replicate` column set as the cell identity classes, so it should naturally appear to tabulate against itself.
