### ISSUE TITLE
NormalizeData; Error in 1L:ceiling(x = dsize/csize) : NA/NaN argument

### ISSUE THREAD

**Issue by holitics-zz** [satijalab/seurat#1933]
Hello,

I try to prepare for sub-clustering a set of cells from a completed CCA-merged analysis as below:
```R

# Using Seurat 3.0.2 | R version 3.6.1

COI = c(3,7:10, 13) # r03

combined.obj$'saved.idents' <- Idents(combined.obj)
Idents(combined.obj) <- combined.obj$'integrated_snn_res.0.3'

obj.subset <- subset(x = combined.obj, idents =  COI, do.clean = T) # 
Idents(obj.subset)
dim(obj.subset)
dim(combined.obj)

obj.subset <- NormalizeData(obj.subset)
# Error in 1L:ceiling(x = dsize/csize) : NA/NaN argument

# obj.subset <- ScaleData(object = obj.subset)
```

`NormalizeData` seem to fail. I guess it is because individual datasets before CCA merger have been normalized already. I did not find others (google/github) encountering this issue. (Unfortunately I cannot share the data object.)

Any ideas how to debug? Thanks!

**Comment by timoast** [comment]
Hi, do you have any NA or NaN values in the count matrix? By the way, `do.clean` is no longer an option in `subset` in v3.

**Comment by DCarbonez** [comment]
I suppose integration is performed using the normalized counts in the data attribute of the Seurat objects. In the Integrated assay, the original counts are not stored (seurat_object@assays$integrated@counts stores a 0x0 sparse Matrix). Therefore, calling NormalizeData on this object won't work and is unnecessary as normalizing over different datasets makes no sense.
