### ISSUE TITLE
Converting a Seurat object feature into a separate assay of the same object

### ISSUE THREAD

**Issue by gloriabk** [satijalab/seurat#1936]
Hi,
is it possible, and how, to take data from one of the features (for example - a feature antibody data) from Seurat object and add it back to the same object, but as a separate assay? 
Thanks for the help,
Gloria

**Comment by timoast** [comment]
Hi Gloria, I don't quite understand what you're asking, but you can add any assay to a Seurat object provided the cells are the same. For example:

```r
object[['newassay']] <- CreateAssayObject(counts = counts)
```

**Comment by gloriabk** [comment]
Hi Tim, for example, if you had protein barcodes and hashtags in the same library (and consequently their expression data in the same assay in Seurat object), would you be able to separate them into two different assays in the Seurat object?

**Comment by timoast** [comment]
If you have protein expression and hashing data present in the same matrix (as is output by cellranger feature barcoding), you should split the matrix into ADT and HTO before creating the different assays. For example:

```r
cellranger <- Read10X_h5(filepath)
obj <- CreateSeuratObject(counts = cellranger$`Gene Expression`)
# adt and hto are vectors of the feature names for ADT and HTO
adt <- cellranger$`Antibody Capture`[adt, ]
hto <- cellranger$`Antibody Capture`[hto, ]

obj[['ADT']] <- CreateAssayObject(counts = adt)
obj[['HTO']] <- CreateAssayObject(counts = hto)
```

**Comment by gloriabk** [comment]
Hi Tim, I did try, and I get the following error: 

> object[["HTO"]] <- CreateAssayObject(counts = HTO[, colnames(x = object)])
Error in CreateAssayObject(counts = HTO[, colnames(x = object)]) : 
  No cell names (colnames) names present in the input matrix

Here is my code: 
object.data <- Read10X(data.dir = "filepath")
object <- CreateSeuratObject(counts = object.data[["Gene Expression"]], min.cells = 4, min.features = 200)
ADTs <- object.data$`Antibody Capture`@Dimnames[[1]][1:10]
ADT <- object.data$`Antibody Capture`[ADTs, ]
HTOs <- object.data$`Antibody Capture`@Dimnames[[1]][11]
HTO <- Matrix(object.data$`Antibody Capture`[HTOs, ], sparse = T, nrow = 1, byrow = F, dimnames = list(HTOs, colnames(ADT)))
object[["ADT"]] <- CreateAssayObject(counts = ADT[, colnames(x = object)])
object[["HTO"]] <- CreateAssayObject(counts = HTO[, colnames(x = object)])

For ADT, it works, but for HTO it gives an error message.
Here are the headers of both matrices:
> ADT 
10 x 4060 sparse Matrix of class "dgCMatrix"
   [[ suppressing 58 column names ‘AAACCTGAGAGTAAGG’, ‘AAACCTGAGGTAGCCA’, ‘AAACCTGCAAGGGTCA’ ... ]]
> HTO
1 x 4060 sparse Matrix of class "dgCMatrix"
   [[ suppressing 58 column names ‘AAACCTGAGAGTAAGG’, ‘AAACCTGAGGTAGCCA’, ‘AAACCTGCAAGGGTCA’ ... ]]

**Comment by yuhanH** [comment]
it looks that some cells in the object but not existed in the HTO matrix. 
```
all.cells <- Reduce(intersect, list(colnames(object), colnames(ADT), colnames(HTO))
object <- subset(object, cells = all.cells )
```
Then, `object[["HTO"]] <- CreateAssayObject(counts = HTO[, colnames(x = object)])` should work.
