### ISSUE TITLE
Discrepancy between PCA loadings and actual PCA values

### ISSUE THREAD

**Issue by bradbal** [satijalab/seurat#1937]
Dear @satijalab,

There appears to be a discrepancy between the PCA loadings and the outputted PCA values.
**If I calculate the PCA in seurat with the following code:**

```
wt <- RunPCA(treatmentObjects2[['WT']], npcs=3, assay='SCT', features=VariableFeatures(wt)[1:100], 
             weight.by.var = F, approx=F, center=F, verbose=T)
wt@reductions$pca@cell.embeddings[1:3,1:3]
```
**I get this for the first 3 cells value in the first 3 PCs:**
```
PC_1       PC_2       PC_3
1] 2.830093 -0.9671529 -0.6632738
2] 2.667357 -0.9008137 -1.3534134
3] 2.059652 -0.4086380 -0.2846330
```
**Now when I calculate the PCA values 'manually':**
```
y <- t(as.matrix(wt@assays$SCT@scale.data)[VariableFeatures(wt)[1:100],])%*%wt@reductions$pca@feature.loadings
y[1:3,1:3]                                                                     
  PC_1       PC_2      PC_3
1] -12.382724  6.3524436 12.429122    
2] -8.521815 -0.9163374 7.565482
3]   1.391023 -0.6179421 2.810488
```
They don't match. The vector dot product of the PCA loadings on the original data should give the PCA values. I then check if running this with prcomp, with code copied from Seurat, would agree with the manual or the RunPCA calculation:
**Now when I copy and paste code from seurat for pca, I get the same values as the manual calculation:**
```
myRunPCA <- function(object, npcs, weight.by.var=F, ...){
  #below is from Seurat dimensional_reduction.R PCA function
  npcs <- min(npcs, nrow(x = object))
  pca.results <- prcomp(x = t(object), rank. = npcs, ...)
  feature.loadings <- pca.results$rotation
  sdev <- pca.results$sdev
  total.variance <- sum(sdev)
  if (weight.by.var) {
    cell.embeddings <- pca.results$x %*% diag(pca.results$sdev[1:npcs]^2)
  } else {
    cell.embeddings <- pca.results$x
  }
  results <- list('cell.embeddings'=cell.embeddings, 'feature.loadings'=feature.loadings)
  return(results)
}

wtPCA <- myRunPCA(as.matrix(wt@assays$SCT@scale.data)[VariableFeatures(wt)[1:100],], 
                                     3, center=F, weight.by.var = F)
loadings <- wtPCA[['feature.loadings']]
pcaValues <- wtPCA[['cell.embeddings']]
pcaValues[1:3,1:3]
```
**I get:**
PC1        PC2       PC3
1] -12.382724  6.3524436 12.429122
2]  -8.521815 -0.9163374 7.565482
3]   1.391023 -0.6179421 2.810488
**You'll notice I set the inputs for RunPCA so that it should run the same as in myRunPCA.**
Yet the PCA values are different, but the loadings are the same. Note that I've set weight.by.var=F, so it can't be this. I've read through the code and can't seem to find anywhere that any changes to the cell.embeddings should occur after call RunPCA. I've tested for correlation using cor.test with the PCA values from manual PCA calculation versus RunPCA in Seurat, and they aren't significantly correlated. Something strange is happening. 

I was wondering if there were any upstream changes that occur after RunPCA that could result in this discrepancy between the loadings and PCA values? Or if there is something else at fault here?

Thankyou,

-Brad

**Comment by andrewwbutler** [comment]
Hi,

Can you provide a reproducible example with data? It seems to be consistent in this example:

```R
data(pbmc_small)
pbmc_small <- SCTransform(pbmc_small)
pbmc_small <- RunPCA(pbmc_small, assay = "SCT", npcs = 3, features = VariableFeatures(pbmc_small), weight.by.var = FALSE, approx = FALSE, center = FALSE)
y <- t(as.matrix(pbmc_small[["SCT"]]@scale.data)[VariableFeatures(pbmc_small),]) %*% Loadings(pbmc_small[["pca"]])
all.equal(y, Embeddings(pbmc_small[["pca"]]))
> TRUE
```
