### ISSUE TITLE
Error in irlba(A = t(x = data.use), nv = pcs.compute, ...) :    max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1938]
Dear,
Thank you so much for helping us!
When I run my own data on the tutorial: https://satijalab.org/seurat/Seurat_AlignmentTutorial.html

The code has error
pbmc <- CalcVarExpRatio(object = pbmc, reduction.type = "pca", grouping.var = "group",  dims.use = 1:20)
It shows me error as the title.

ncol(x = pbmc@scale.data)  # this is 40000
nrow(x = pbmc@scale.data) # this is 13

How do I change the dims.use to make this step run well?
Thank you and best wishes,
Jinping

**Comment by surljp2012** [comment]
If I set **dims.use** as 200, if will show error Could not find the following dimensions: from 21 to 200.
If I set **dims.use** as 20, it will show the error like title.
Is it possible to set a proper **dims.use** ?
Thank you and best wishes,
Jinping

**Comment by andrewwbutler** [comment]
Hi,

If you only have 13 features in scale.data, you can't reduce the dimension (via PCA or CCA) to something larger than 13 (i.e. 20 or 200). Assuming this is a standard scRNA-seq analysis, I would double check how you've processed the data up to this point.

**Comment by surljp2012** [comment]
Thank you, Andrew!

I will try 13 in this.

Best wishes,
Jinping
