### ISSUE TITLE
RunDiffusion function is not found in Seurat3

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1941]
Why RunDiffusion function is not found in Seurat3?Does it is replaced by another function?
By the way,how can I do pseudotime analysis through destiny or diffusionmap on seurat object?

**Comment by andrewwbutler** [comment]
Hi,

`RunDiffusion` is not currently implemented in Seurat v3. You can still run destiny or diffusionmap on your data and store it as a dimensional reduction though (check out the [dimensional reduction vignette](https://satijalab.org/seurat/v3.0/dim_reduction_vignette.html) for an example of storing a custom dimensional reduction).
