### ISSUE TITLE
Displaying pca and heatmap plots of integrated two datasets by DimPlot and DimHeatmap 

### ISSUE THREAD

**Issue by akhst7** [satijalab/seurat#1943]
I created the integrated datasets by `FindIntegrationAnchors` and `IntegrateData` and would like to see pca and heatmap of two datasets individually.  Since DimPlot and DimHeatmap functions do not have `group by` and/or `split by` arguments,  they wont let me do this. Are there any other ways to get around this ? 

Thanks in advance.

**Comment by timoast** [comment]
Hi, I we don't have a `split.by` option for heatmaps but we do have the `cells` parameter, so I would suggest creating different heatmaps by supplying different lists of cells, for example:

```r
cells.1 <- WhichCells(object, idents = 'a')
cells.2 <- WhichCells(object,  idents = 'b')
hm1 <- DoHeatmap(object, cells = cells.1)
hm2 <- DoHeatmap(object, cells = cells.2)
```

**Comment by NeuronNewton** [comment]
Hello! 
Struggling to get this method for heatmaps to works with the following error message:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': error in evaluating the argument 'x' in selecting a method for function 't': no 'dimnames' attribute for array

Would you have any suggestions on how to resolve that?

**Comment by NeuronNewton** [comment]
Thank you very much for responding, this fixed the error!
