### ISSUE TITLE
Error in names(marker.test) <- levels.split : 'names' attribute [2] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by surljp2012** [satijalab/seurat#1944]
Dear,
I believe me and other people met the error by running the PBMC tutorial from the link of https://satijalab.org/seurat/v3.0/immune_alignment.html

nk.markers <- FindConservedMarkers(immune.combined, ident.1 = 7, grouping.var = "stim", verbose = FALSE)

Warning: Identity: 7 not present in group CTRL. Skipping CTRL
Warning: Identity: 7 not present in group STIM. Skipping STIM
**Error in names(marker.test) <- levels.split :
'names' attribute [2] must be the same length as the vector [0]**
Do you have any suggestions about it?
I think this will lead more error with downstream codes.
Thank you,
Jinping

**Comment by timoast** [comment]
Hi, I'm not able to reproduce this. Are you running the exact code that's in the vignette, on the same dataset? Can you also provide the output of `sessionInfo()`?

**Comment by stephanyfoster** [comment]
hello--
I am facing the same error but with my own dataset, not all of the seurat objects have the same number of clusters so when I try to find conserved markers on the integrated dataset, I get this error. How can I find conserved markers on clusters of an integrated dataset?
