### ISSUE TITLE
error:findconservedmarkers

### ISSUE THREAD

**Issue by a582213088** [satijalab/seurat#1945]
Hi Seurat Team,
Thanks for developing such a useful tool for single-cell genomics
I am confused when using the function named “FindConservedMarkers" in Seurat because of the error :
**Error in names(marker.test) <- levels.split :
'names' attribute [2] must be the same length as the vector [0]**
I think it maybe due to that there is not common cluster among all dataset. For example, if all datasets have clusterA and clusterB ,this function can work ,but if clusterB is not in all datasets, this function to get differential expression geneset between A and B can not work.
So I try to find the common clusters among all dataset ,the R script is ：
**intersect.cluster<-tapply(seurat.integrated$seurat_clusters,seurat.integrated@meta.data$orig.ident,table)
intersect.cluster1<-vector()
for (i in 1:length(levels(seurat.integrated@meta.data$seurat_clusters))) {
  m=0
  for (j in 1:dim(intersect.cluster)) {
    if (intersect.cluster[[j]][i]!=0) {
  m=m+1
    }
  }
  if (m==dim(intersect.cluster)) {
    print(i-1)
    intersect.cluster1=c(intersect.cluster1,i-1)
  }
}
intersect.cluster1
seurat.marker<-FindConservedMarkers(seurat.integrated,ident.1 = 1,ident.2 = intersect.cluster1[intersect.cluster1!=1],grouping.var = "orig.ident",test.use="roc",only.pos=T)**
And the error is removed ，the function can work
but I do not know if this treatment is right ,so could you please give me some advice about this?
thank you!

**Comment by timoast** [comment]
Hi, thanks for reporting. This is a bug and the same as https://github.com/satijalab/seurat/issues/1624. We will try to have it fixed soon
