### ISSUE TITLE
How to plot metadata information

### ISSUE THREAD

**Issue by jbridge873** [satijalab/seurat#1947]
Hi guys,

 I have added in my TCR information to my Seurat object but want to know if there is an easier way to Feature plot certain TRAV (for example; TRAV5-4) without having to pull the barcodes and create a list and plot it via the list?

Cheers,

J

**Comment by mojaveazure** [comment]
As per the [documentation for `FeaturePlot`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/FeaturePlot)

> **features**: vector of features to plot. Features can come from:
> - An Assay feature (e.g. a gene name - "MS4A1")
> - A column name from meta.data (e.g. mitochondrial percentage - "percent.mito")
> - A column name from a DimReduc object corresponding to the cell embedding values (e.g. the PC 1 scores - "PC_1")
