### ISSUE TITLE
Remove background in FeaturePlot

### ISSUE THREAD

**Issue by ogarmar3** [satijalab/seurat#1948]
Hello,

I'm plotting gene expression on tSNE using FeaturePlot, **Seurat v.2.3.3**.
How can I **remove the grey background grid**?

![Gene_tSNE_test2](https://user-images.githubusercontent.com/40645584/62642559-d7996580-b8fa-11e9-8baa-6569819c2efd.png)

I need just plain white background, but I can't find a way to do it.

Thank you!

Marcos

**Comment by j-andrews7** [comment]
Seurat plots are just ggplot2 plots. You can adjust the theming as needed, for example:

```
yourplot = FeaturePlot(...) + ggplot2::theme_classic()
```

**Comment by mojaveazure** [comment]
Hi Marcos,

If you pass [`do.return = TRUE`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.3/topics/FeaturePlot), you can get the ggplot2 object returned to you. This allows you to manipulate the plot using standard ggplot2 functions. In your case, I suggest looking at the [`theme`](https://ggplot2.tidyverse.org/reference/theme.html) function

**Comment by ogarmar3** [comment]
It works. I'm learning about ggplot2 now.

Thank you!

**Comment by yingyonghui** [comment]
> It works. I'm learning about ggplot2 now.
> 
> Thank you!

Hi @ogarmar3,
I'm wondering how you solved the problem.
I just came up with the same question.
I tried  FeaturePlot(...) + ggplot2::theme_classic(), but it returned 'NULL' and the figure showed no changes.
Any suggestions would be appreciated!

Many thanks!
Best,
Yingyong
