### ISSUE TITLE
Seurat v3.0.2 in CRAN

### ISSUE THREAD

**Issue by cesco-lemon** [satijalab/seurat#1949]
Hi everyone,

I was wondering if Seurat v3.0.2 will be released on CRAN any time soon. For a long list of reasons I can only use whatever is directly available on CRAN (following the extremely useful instructions as offered by you guys), any idea of when the 3.0.2 will be available there?

Thanks!

Cesco

**Comment by j-andrews7** [comment]
3.0.2 is the version currently on CRAN.

CRAN doesn't like devs to update constantly - they basically demand a month or two between updates. And getting new code ready for CRAN submissions takes time.

Why can you only use the CRAN version?

**Comment by mojaveazure** [comment]
Seurat v3.0.2 has been available on CRAN for nearly two months. I strongly urge you to read documentation on [our website](https://satijalab.org/seurat/), our [CRAN page](https://cran.r-project.org/package=Seurat), and in the [package help pages](https://cran.r-project.org/web/packages/Seurat/Seurat.pdf) for details about Seurat, including release information.
