### ISSUE TITLE
mclapply in RegressOutResid

### ISSUE THREAD

**Issue by batson** [satijalab/seurat#195]
Hello,

I'm new to R and therefore to it's system for parallelization, but I was wondering if it would be possible to use mclapply instead of lapply in the RegressOutResid function. I find this is the slowest part of running Seurat on a large dataset, and it might benefit from the ability to use multiple cores (as RegressOutNB does).

-Josh

**Comment by satijalab** [comment]
Agreed - this is a feature that would benefit from parallelization. We won't be able to update in the very near future, but please feel free to try a pull request.
