### ISSUE TITLE
Very large avg_logFC values don't seem to make sense?

### ISSUE THREAD

**Issue by sfcs** [satijalab/seurat#1950]
HI, I am using 3.0.3.9023.  I have datasets using two conditions, which I have integrated using the SCTransform workflow.  I am doing differential expression analysis, like this, comparing each cluster:

`c0.diffs <- FindMarkers(mydata.integrated, ident.1 = "0_Uninduced", ident.2 = "0_Induced_5_day", verbose = F)`

My issue is that I'm getting back very large avg_logFC values, in the range of -70 to -120 for some genes.  These make no sense, clearly.   A violin plot or ridge plot of the same data suggest relatively subtle changes in gene expression.  

The gene with the largest avg_logFC is an r-protein expressed in nearly 100% of cells, if that's helpful.

**Comment by timoast** [comment]
Hi, can you please post the full code you're running and the output of `sessionInfo()`?

**Comment by sfcs** [comment]
I'm sorry if I am doing something stupid.  I started out using the standard workflow, which doesn't have this problem, but it didn't show increased expression of the gene I am inducing.  When I tried the SCTransform workflow it at least detected the gene I am inducing.  I didn't notice the weird fold change values at first!  

So here I am not doing the differential between clusters as you see, but I'm still getting the erroneous fold change.  

[example.txt](https://github.com/satijalab/seurat/files/3487745/example.txt)
[sessionInfo.txt](https://github.com/satijalab/seurat/files/3487746/sessionInfo.txt)
[head_of_markers0.txt](https://github.com/satijalab/seurat/files/3487747/head_of_markers0.txt)

**Comment by timoast** [comment]
For running DE on the SCTransform-normalized data you should use `slot='scale.data'`. Can you try that and see if you still have the same problem?

**Comment by Liuy12** [comment]
This might be irrelevant, but I want to post it here in case someone else face similar issues in the future. I encountered similar issues (very large fold changes) when trying to identify conserved genes using FindConservedMarkers. I believe this is the cause: FindConservedMarkers does not recognize the assay set by 'DefaultAssay'. Instead it still uses 'RNA' assay by default. So if you are using SCT transformation, this could a issue. To solve this, you will need to set assay='SCT' and slot='data' for FindConservedMarkers.

**Comment by satijalab** [comment]
Apologies that we never responded. This is one of the reasons we now recommend using the RNA assay for DE (normalized counts)
