### ISSUE TITLE
CSV/EXCEL file of the Normalized Data MATRIX

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#1951]
Hi everyone,
How can I turn the the normalized matrix in V3.0 into a CSV/EXCEL file? 
Thank you

**Comment by j-andrews7** [comment]
```
mat <- GetAssayData(scrna@assays$RNA, slot = "data")
write.csv(as.matrix(mat), file ="./pathto/output.csv", quote = FALSE)
```

**Comment by cBioPort** [comment]
Using the solution above, I am getting a memory error  that  I am unable to bypass. is there another way to export the data in a less memory consuming way?

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

**Comment by andrewwbutler** [comment]
It's probably the conversion to a dense matrix with `as.matrix` that's giving you the issue. You could break the matrix into chunks and write sections at a time to try to get around this but for matrices of that size, csv is probably not the format you want.

**Comment by msmicker** [comment]
I am not sure why this error happens if there is sufficient RAM. That said, writing in chunks worked for me. In case it is useful for others:

```R
# get df from Seurat object
counts_df <- seuratObj@assays$RNA@data

fname="counts.txt"

# make a column vector and write to a file
colnames <- 1:counts_df@Dim[2]
colnames <- R.utils::insert(colnames, 1, c("gene_name"))
colnames <- matrix(colnames, 1)
write.table(colnames, file=fname, row.names = FALSE, col.names=FALSE, sep="\t", quote = FALSE)

# rows per chunk, this could be determined based on cells but just fixed below
# e.g. for 40000 cells I used 1000
elements_per_chunk = 1000
l = split(1:nrow(counts_df), ceiling(seq_along(1:nrow(counts_df))/elements_per_chunk))

# Write large data frame to csv in chunks
count = 1
for(i in l){
  print(count)
  write.table(counts_df[i,], file=fname, sep = "\t", row.names = TRUE,
              append = TRUE, quote = FALSE, col.names=FALSE)
  count = count + 1
}
```
