### ISSUE TITLE
equivalent CalcVarExpRatio() function in Seurat v3.0

### ISSUE THREAD

**Issue by arubenstein** [satijalab/seurat#1953]
Hi, I am trying to integrate several PBMC scRNA-seq samples in Seurat v3.0.  I was following the [Integrated Stim. and Control tutorial](https://satijalab.org/seurat/v3.0/immune_alignment.html), which was extremely helpful, as well as the 2018 Nature paper.  The paper mentions a method to compare CCA and PCA to find rare, non-overlapping cell populations, and the function CalcVarExpRatio() in previous versions of Seurat appears to do that.  However, this function is not present in Seurat v3.0. **Is there a reason for this function no longer being supported?** If not, I would download Seurat version 2 and attempt to re-run the integration for the sake of performing this analysis, so I'd like to make sure that the function is still considered a reasonable analysis before doing that.

Thank you.

**Comment by nyoonhee** [comment]
I also have the exact same question

**Comment by xwang0228** [comment]
I also have the same question.

**Comment by satijalab** [comment]
See #1696 , these functions are not supported in V3 because we use an updated alignment strategy
