### ISSUE TITLE
remove un-wanted variation before IntegrateData?

### ISSUE THREAD

**Issue by stemangiola** [satijalab/seurat#1955]
Sorry, I could not find a better place for this question.

In your post https://satijalab.org/seurat/v3.0/integration.html you mention to not ScaleData after the integration.

1) If I have unwanted variation in my many samples data set (e.g., cell cycle) should I remove all the unwanted variation before the integration or after. In the latter case what function should I use?

2) Or if I have for example 4 samples coming from an experiment/technology and 5 samples coming from another, should I process sample by samples, integrate and remove technology variation, or some other approach?

Thanks

**Comment by yuhanH** [comment]
Hi,
If your data is normalized by SCTransform, we don't suggest you run ScaleData after the integration.
q1. For the cell cycle or mitochondrial effects, you could regress them out in the SCTransform before the integration.
q2. First, you need to check out if those 4 samples or 5 samples have strong batch effects.
 If true, you need to do the integration by samples.
If not, you can integrate by technology.
