### ISSUE TITLE
Multiple species

### ISSUE THREAD

**Issue by brunetc** [satijalab/seurat#1956]
Hi Seurat, 

I'm trying to compare data from multiple species.
I read in Butler et al, 2018 that you compare gene expression based on identical gene names. 
Since different species have different annotation, what would you recommend me to do? 

I tried to follow the pipeline, but I got this error (I believed it comes from the annotation issue) : Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic

Thanks in advance.

**Comment by timoast** [comment]
Hi, 

You will need to identify gene homologs between the species and rename the homologous genes to have the same name across the different Seurat objects. You can then use the standard integration methods outlined here: https://satijalab.org/seurat/v3.0/integration.html

**Comment by mamtagiri** [comment]
If you are still looking for a method to convert gene names to kits corresponding orthologs, here is a script :
https://github.com/mamtagiri/SingleCellSequencinginR/blob/master/OrthologsConvertion.R
