### ISSUE TITLE
SCTransform vs NormalizeDate, ScaleData, FindVariableFeatures produces different results

### ISSUE THREAD

**Issue by prmunn** [satijalab/seurat#1957]

**Comment by prmunn** [comment]
I'm going through the "Using SCTransform" vignette and attempting to replace NormalizeDate, ScaleData, and FindVariableFeatures in my code with SCTransform. However, when I look for specific genes using GetAssayData I am able to find counts greater than zero using the original normalization method, but the counts are zero for the SCTransform method. Why the difference?

**Comment by andrewwbutler** [comment]
Hi,

It is expected that the two different workflows will produce different results. How are you looking for the counts of these specific genes? 

The SCTransform workflow results in Pearson residuals, which you can think of as similar to what you get after `ScaleData` in the standard workflow. These can be found with `GetAssayData(object[["SCT"]], slot = "scale.data")`. Note that by default here, we only return these values for features determined as "variable". In the SCT assay, we also return "corrected" UMI counts in the "counts" slot.

**Comment by jliu678** [comment]
> Hi,
> 
> It is expected that the two different workflows will produce different results. How are you looking for the counts of these specific genes?
> 
> The SCTransform workflow results in Pearson residuals, which you can think of as similar to what you get after `ScaleData` in the standard workflow. These can be found with `GetAssayData(object[["SCT"]], slot = "scale.data")`. Note that by default here, we only return these values for features determined as "variable". In the SCT assay, we also return "corrected" UMI counts in the "counts" slot.

Hi,

Could you describe how corrected umi is generated by the function sctransform::correct, if possible?

As far as I have understood, looks like you input the residual and the estimated parameters to get the corrected umi, and further round it and eliminate negative values. But except the round process,  how come part of the corrected umi is different with the original umi? and why its necessary?

thanks
