### ISSUE TITLE
Threshold for Label transfer

### ISSUE THREAD

**Issue by baracus37** [satijalab/seurat#1959]
Hi,

I am using the [Integration and Label Transfer Vignette](https://satijalab.org/seurat/v3.0/integration.html) in order to transfer labels between two datasets that share a large portion of the celltypes they contain. But each dataset also contains unique celltypes. When doing label transfer these unique celltypes will score a low `prediction.score.max` as expected, but they will however get assigned an `predicted.id` based on their highest score.
Is there a way to set a threshold for `prediction.score.max` that will lead to an  `predicted.id`? I am thinking about something like: Every cell with `prediction.score.max < x` will not get a `predicted.id`.

A workaraound might be to manually manipulate @meta.data and set  `predicted.id` to NA for all cells that have `prediction.score.max < x`, but I am lacking R skills to do so. Any help for that would be appreciated as well.

**Comment by timoast** [comment]
Hi, the `predicted.id` will always be the ID with the highest prediction score for the cell, regardless of how high or low the score may be. We leave it to the user to choose an explicit threshold for classifying cells as "unknown." You can do this with:

```r
object$celltype <- ifelse(object$prediction.score.max > threshold, object$predicted.id, NA)
```

**Comment by baracus37** [comment]
thanks for the help. That is appreciated. 
Can the prediction score be seen as a percentage of accordance, as it ranges from 0 to 1? Could you give some additional background information on how the prediction score is calculated? Otherwise it is hard to set a meaningful threshold.

**Comment by andrewwbutler** [comment]
You can check out the paper [here](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8) for details on how these scores are calculated.
