### ISSUE TITLE
definition of snn

### ISSUE THREAD

**Issue by batson** [satijalab/seurat#196]
Hello,

I'm a bit confused about the definition of the snn. How exactly is this being computed from the distance matrix?

The particular thing I'm finding confusing is that the number of nonzero entries in a given row is much larger than k.param, and I thought this was a pruned version of the knn graph for k = k.param.

**Comment by satijalab** [comment]
You can see the code in BuildSNN, but two cells can share nearest neighbors even if they themselves are not nearest neighbors, which is why the number of non-zero entries is > k.param.
