### ISSUE TITLE
how to correct cluster inaccuracy on Umap in integrated/combined analysis 

### ISSUE THREAD

**Issue by akhst7** [satijalab/seurat#1960]
Hi 

I have an combined/integrated object (by using `FindIntegrationAnchors` and `IntegrateData`) and drew an Umap of the object.  I noticed that there were some inconsistencies between two groups which are highlighted on an attached image.  I would appreciate any pointers to make group 1 clusters agrees with group2 clusters.  

Thanks. 

[Umap2.pdf](https://github.com/satijalab/seurat/files/3486840/Umap2.pdf)

**Comment by timoast** [comment]
Hi, not sure what you mean exactly by inconsistencies between the groups. Can you clarify the problem you're having, and post your code and the output of `sessionInfo()`?

**Comment by akhst7** [comment]
I followed the instruction described in  _Tutorial: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses_ to create the integrated object.   To get a UMAP plot, I used a following code;  `DimPlot(PA.combined.sct, reduction = "umap", label = T, repel = T, label.size=6, split.by = "type")+theme(legend.position = "none" )`.

At the beginning, we thought it was inconsistency in cluster labelling, for example, cluster 17 in group1 is not the same location in group2 on the Umap, however by looking at the color of clusters, It appears that the label, **17** might just have been moved while indicating the same set of clusters.  Is there any way to  plot a particular cluster, eg. 17 by FeaturePlot  to make sure the same clusters are the label  by the same number ? 

Thanks. 

Here is my sessioninfo just in case,

`> session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin18.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Indiana/Indianapolis
 date     2019-08-09                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version   date       lib source                                     
 acepack                1.4.1     2016-10-29 [1] CRAN (R 3.6.1)                             
 annotate               1.63.0    2019-05-02 [1] Bioconductor                               
 AnnotationDbi          1.47.0    2019-05-02 [1] Bioconductor                               
 ape                    5.3       2019-03-17 [1] CRAN (R 3.6.0)                             
 assertthat             0.2.1     2019-03-21 [1] CRAN (R 3.6.0)                             
 backports              1.1.4     2019-04-10 [1] CRAN (R 3.6.0)                             
 base64enc              0.1-3     2015-07-28 [1] CRAN (R 3.6.0)                             
 bibtex                 0.4.2     2017-06-30 [1] CRAN (R 3.6.0)                             
 Biobase              * 2.45.0    2019-05-02 [1] Bioconductor                               
 BiocFileCache          1.9.1     2019-06-04 [1] Bioconductor                               
 BiocGenerics         * 0.31.5    2019-07-03 [1] Bioconductor                               
 BiocManager          * 1.30.4    2018-11-13 [1] CRAN (R 3.6.0)                             
 BiocNeighbors          1.3.3     2019-07-20 [1] Bioconductor                               
 BiocParallel         * 1.19.0    2019-05-02 [1] Bioconductor                               
 bit                    1.1-14    2018-05-29 [1] CRAN (R 3.6.0)                             
 bit64                  0.9-7     2017-05-08 [1] CRAN (R 3.6.0)                             
 bitops                 1.0-6     2013-08-17 [1] CRAN (R 3.6.0)                             
 blob                   1.2.0     2019-07-09 [1] CRAN (R 3.6.1)                             
 callr                  3.3.1     2019-07-18 [1] CRAN (R 3.6.1)                             
 caTools                1.17.1.2  2019-03-06 [1] CRAN (R 3.6.0)                             
 checkmate              1.9.4     2019-07-04 [1] CRAN (R 3.6.1)                             
 cli                    1.1.0     2019-03-19 [1] CRAN (R 3.6.0)                             
 cluster                2.1.0     2019-06-19 [2] CRAN (R 3.6.1)                             
 codetools              0.2-16    2018-12-24 [2] CRAN (R 3.6.1)                             
 colorspace             1.4-1     2019-03-18 [1] CRAN (R 3.6.0)                             
 cowplot                1.0.0     2019-07-11 [1] CRAN (R 3.6.1)                             
 crayon                 1.3.4     2017-09-16 [1] CRAN (R 3.6.0)                             
 curl                   4.0       2019-07-22 [1] CRAN (R 3.6.1)                             
 data.table           * 1.12.2    2019-04-07 [1] CRAN (R 3.6.0)                             
 DBI                    1.0.0     2018-05-02 [1] CRAN (R 3.6.0)                             
 dbplyr                 1.4.2     2019-06-17 [1] CRAN (R 3.6.0)                             
 DelayedArray         * 0.11.4    2019-07-03 [1] Bioconductor                               
 DelayedMatrixStats     1.7.1     2019-06-16 [1] Bioconductor                               
 desc                   1.2.0     2018-05-01 [1] CRAN (R 3.6.0)                             
 DESeq2               * 1.25.9    2019-07-30 [1] Bioconductor                               
 devtools             * 2.1.0     2019-07-06 [1] CRAN (R 3.6.0)                             
 digest                 0.6.20    2019-07-04 [1] CRAN (R 3.6.0)                             
 dplyr                * 0.8.3     2019-07-04 [1] CRAN (R 3.6.0)                             
 fitdistrplus           1.0-14    2019-01-23 [1] CRAN (R 3.6.0)                             
 foreign                0.8-72    2019-08-02 [2] CRAN (R 3.6.1)                             
 Formula                1.2-3     2018-05-03 [1] CRAN (R 3.6.1)                             
 fs                     1.3.1     2019-05-06 [1] CRAN (R 3.6.0)                             
 future                 1.14.0    2019-07-02 [1] CRAN (R 3.6.0)                             
 future.apply           1.3.0     2019-06-18 [1] CRAN (R 3.6.0)                             
 gbRd                   0.4-11    2012-10-01 [1] CRAN (R 3.6.0)                             
 gdata                  2.18.0    2017-06-06 [1] CRAN (R 3.6.0)                             
 genefilter             1.67.1    2019-05-11 [1] Bioconductor                               
 geneplotter            1.63.0    2019-05-02 [1] Bioconductor                               
 GenomeInfoDb         * 1.21.1    2019-05-15 [1] Bioconductor                               
 GenomeInfoDbData       1.2.1     2019-05-14 [1] Bioconductor                               
 GenomicRanges        * 1.37.14   2019-06-24 [1] Bioconductor                               
 ggplot2              * 3.2.0     2019-06-16 [1] CRAN (R 3.6.0)                             
 ggrepel                0.8.1     2019-05-07 [1] CRAN (R 3.6.0)                             
 ggridges               0.5.1     2018-09-27 [1] CRAN (R 3.6.0)                             
 globals                0.12.4    2018-10-11 [1] CRAN (R 3.6.0)                             
 glue                   1.3.1     2019-03-12 [1] CRAN (R 3.6.0)                             
 gplots                 3.0.1.1   2019-01-27 [1] CRAN (R 3.6.0)                             
 gprofiler2           * 0.1.5     2019-07-04 [1] CRAN (R 3.6.0)                             
 gridExtra              2.3       2017-09-09 [1] CRAN (R 3.6.0)                             
 gtable                 0.3.0     2019-03-25 [1] CRAN (R 3.6.0)                             
 gtools                 3.8.1     2018-06-26 [1] CRAN (R 3.6.0)                             
 Hmisc                  4.2-0     2019-01-26 [1] CRAN (R 3.6.1)                             
 htmlTable              1.13.1    2019-01-07 [1] CRAN (R 3.6.1)                             
 htmltools              0.3.6     2017-04-28 [1] CRAN (R 3.6.0)                             
 htmlwidgets            1.3       2018-09-30 [1] CRAN (R 3.6.0)                             
 httr                   1.4.1     2019-08-05 [1] CRAN (R 3.6.1)                             
 ica                    1.0-2     2018-05-24 [1] CRAN (R 3.6.0)                             
 igraph                 1.2.4.1   2019-04-22 [1] CRAN (R 3.6.0)                             
 IRanges              * 2.19.10   2019-06-11 [1] Bioconductor                               
 irlba                  2.3.3     2019-02-05 [1] CRAN (R 3.6.0)                             
 jsonlite               1.6       2018-12-07 [1] CRAN (R 3.6.0)                             
 KernSmooth             2.23-15   2015-06-29 [2] CRAN (R 3.6.1)                             
 knitr                  1.24      2019-08-08 [1] CRAN (R 3.6.1)                             
 labeling               0.3       2014-08-23 [1] CRAN (R 3.6.0)                             
 lattice                0.20-38   2018-11-04 [2] CRAN (R 3.6.1)                             
 latticeExtra           0.6-28    2016-02-09 [1] CRAN (R 3.6.1)                             
 lazyeval               0.2.2     2019-03-15 [1] CRAN (R 3.6.0)                             
 listenv                0.7.0     2018-01-21 [1] CRAN (R 3.6.0)                             
 lmtest                 0.9-37    2019-04-30 [1] CRAN (R 3.6.0)                             
 locfit                 1.5-9.1   2013-04-20 [1] CRAN (R 3.6.0)                             
 lsei                   1.2-0     2017-10-23 [1] CRAN (R 3.6.0)                             
 magrittr               1.5       2014-11-22 [1] CRAN (R 3.6.0)                             
 MASS                   7.3-51.4  2019-03-31 [2] CRAN (R 3.6.1)                             
 Matrix                 1.2-17    2019-03-22 [2] CRAN (R 3.6.1)                             
 matrixStats          * 0.54.0    2018-07-23 [1] CRAN (R 3.6.0)                             
 memoise                1.1.0     2017-04-21 [1] CRAN (R 3.6.0)                             
 metap                  1.1       2019-02-06 [1] CRAN (R 3.6.0)                             
 monocle3             * 0.1.2.0   2019-07-02 [1] Github (cole-trapnell-lab/monocle3@45f57a0)
 munsell                0.5.0     2018-06-12 [1] CRAN (R 3.6.0)                             
 nlme                   3.1-141   2019-08-01 [2] CRAN (R 3.6.1)                             
 nnet                   7.3-12    2016-02-02 [2] CRAN (R 3.6.1)                             
 npsurv                 0.4-0     2017-10-14 [1] CRAN (R 3.6.0)                             
 pbapply                1.4-1     2019-07-15 [1] CRAN (R 3.6.1)                             
 pillar                 1.4.2     2019-06-29 [1] CRAN (R 3.6.0)                             
 pkgbuild               1.0.4     2019-08-05 [1] CRAN (R 3.6.1)                             
 pkgconfig              2.0.2     2018-08-16 [1] CRAN (R 3.6.0)                             
 pkgload                1.0.2     2018-10-29 [1] CRAN (R 3.6.0)                             
 plotly                 4.9.0     2019-04-10 [1] CRAN (R 3.6.0)                             
 plyr                   1.8.4     2016-06-08 [1] CRAN (R 3.6.0)                             
 png                    0.1-7     2013-12-03 [1] CRAN (R 3.6.0)                             
 prettyunits            1.0.2     2015-07-13 [1] CRAN (R 3.6.0)                             
 processx               3.4.1     2019-07-18 [1] CRAN (R 3.6.1)                             
 ps                     1.3.0     2018-12-21 [1] CRAN (R 3.6.0)                             
 purrr                  0.3.2     2019-03-15 [1] CRAN (R 3.6.0)                             
 R.methodsS3            1.7.1     2016-02-16 [1] CRAN (R 3.6.0)                             
 R.oo                   1.22.0    2018-04-22 [1] CRAN (R 3.6.0)                             
 R.utils                2.9.0     2019-06-13 [1] CRAN (R 3.6.0)                             
 R6                     2.4.0     2019-02-14 [1] CRAN (R 3.6.0)                             
 RANN                   2.6.1     2019-06-13 [1] Github (jefferis/RANN@90d57e7)             
 rappdirs               0.3.1     2016-03-28 [1] CRAN (R 3.6.0)                             
 RColorBrewer           1.1-2     2014-12-07 [1] CRAN (R 3.6.0)                             
 Rcpp                   1.0.2     2019-07-25 [1] CRAN (R 3.6.1)                             
 RCurl                  1.95-4.12 2019-03-04 [1] CRAN (R 3.6.0)                             
 Rdpack                 0.11-0    2019-04-14 [1] CRAN (R 3.6.0)                             
 remotes                2.1.0     2019-06-24 [1] CRAN (R 3.6.0)                             
 reshape2               1.4.3     2017-12-11 [1] CRAN (R 3.6.0)                             
 reticulate           * 1.13      2019-07-24 [1] CRAN (R 3.6.1)                             
 rlang                  0.4.0     2019-06-25 [1] CRAN (R 3.6.0)                             
 ROCR                   1.0-7     2015-03-26 [1] CRAN (R 3.6.0)                             
 rpart                  4.1-15    2019-04-12 [2] CRAN (R 3.6.1)                             
 rprojroot              1.3-2     2018-01-03 [1] CRAN (R 3.6.0)                             
 RSQLite                2.1.2     2019-07-24 [1] CRAN (R 3.6.1)                             
 rstudioapi             0.10      2019-03-19 [1] CRAN (R 3.6.0)                             
 rsvd                   1.0.2     2019-07-29 [1] CRAN (R 3.6.1)                             
 Rtsne                  0.15      2018-11-10 [1] CRAN (R 3.6.0)                             
 S4Vectors            * 0.23.17   2019-06-22 [1] Bioconductor                               
 scales                 1.0.0     2018-08-09 [1] CRAN (R 3.6.0)                             
 sctransform            0.2.0     2019-04-12 [1] CRAN (R 3.6.0)                             
 SDMTools               1.1-221.1 2019-04-18 [1] CRAN (R 3.6.0)                             
 sessioninfo            1.1.1     2018-11-05 [1] CRAN (R 3.6.0)                             
 Seurat               * 3.0.2     2019-06-14 [1] CRAN (R 3.6.0)                             
 SingleCellExperiment * 1.7.4     2019-08-03 [1] Bioconductor                               
 SingleR              * 0.98.4    2019-08-09 [1] Github (LTLA/SingleR@37e568a)              
 statmod              * 1.4.32    2019-05-29 [1] CRAN (R 3.6.0)                             
 stringi                1.4.3     2019-03-12 [1] CRAN (R 3.6.0)                             
 stringr                1.4.0     2019-02-10 [1] CRAN (R 3.6.0)                             
 SummarizedExperiment * 1.15.6    2019-07-31 [1] Bioconductor                               
 survival               2.44-1.1  2019-04-01 [2] CRAN (R 3.6.1)                             
 testthat               2.2.1     2019-07-25 [1] CRAN (R 3.6.1)                             
 tibble                 2.1.3     2019-06-06 [1] CRAN (R 3.6.0)                             
 tidyr                  0.8.3     2019-03-01 [1] CRAN (R 3.6.0)                             
 tidyselect             0.2.5     2018-10-11 [1] CRAN (R 3.6.0)                             
 tsne                   0.1-3     2016-07-15 [1] CRAN (R 3.6.0)                             
 usethis              * 1.5.1     2019-07-04 [1] CRAN (R 3.6.0)                             
 vctrs                  0.2.0     2019-07-05 [1] CRAN (R 3.6.0)                             
 viridis                0.5.1     2018-03-29 [1] CRAN (R 3.6.0)                             
 viridisLite            0.3.0     2018-02-01 [1] CRAN (R 3.6.0)                             
 withr                  2.1.2     2018-03-15 [1] CRAN (R 3.6.0)                             
 xfun                   0.8       2019-06-25 [1] CRAN (R 3.6.0)                             
 XML                    3.98-1.20 2019-06-06 [1] CRAN (R 3.6.0)                             
 xtable                 1.8-4     2019-04-21 [1] CRAN (R 3.6.0)                             
 XVector                0.25.0    2019-05-02 [1] Bioconductor                               
 zeallot                0.1.0     2018-01-28 [1] CRAN (R 3.6.0)                             
 zlibbioc               1.31.0    2019-05-02 [1] Bioconductor                               
 zoo                    1.8-6     2019-05-28 [1] CRAN (R 3.6.0)                             

[1] /Users/ahoji/Documents/R_lib
[2] /usr/local/Cellar/r/3.6.1/lib/R/librar`

**Comment by j-andrews7** [comment]
Pretty sure cluster labels just get tossed near the largest collection of cells for said cluster. Illustrator is likely your friend here.

**Comment by mojaveazure** [comment]
@j-andrews7 is correct; when using `split.by`, each plot in the split is generated using only the cells in that grouping. For each plot in the split, we look at the cells present and choose a "median" point by coordinate to place the label. With `repel = TRUE`, some labels may be further shifted to avoid label overlap. Please see the code for [`LabelClusters`](https://github.com/satijalab/seurat/blob/master/R/visualization.R#L2491-L2564) for exact implementation.
