### ISSUE TITLE
pca on citeseq data

### ISSUE THREAD

**Issue by sri540** [satijalab/seurat#1963]
I'm getting this following error when I run RunPCA() on Citeseq data
june16_june24_seurat_obj_b <- RunPCA(seurat_obj_b,features = rownames(seurat_obj_b),
                                     reduction.name = "pca_adt",
                                     reduction.key = "pca_adt_",verbose = FALSE,
                                     assay="ADT" )

Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  did not converge--results might be invalid!; try increasing work or maxit
Warning: All keys should be one or more alphanumeric characters followed by an underscore '_', setting key to pca_

**Comment by timoast** [comment]
Hi, this is a warning not an error, just saying that you're running partial SVD but computing most (or all) of the singular values. You can set `approx=FALSE` to run standard SVD instead.

**Comment by alexanderlewis99** [comment]
Similar @mariannebest, I have the same error message also after adding adding approx = FALSE. Any suggestions? Should I simply ignore the warning since I should now being computing a standard svd?
