### ISSUE TITLE
Cross species integration - RunPCA error

### ISSUE THREAD

**Issue by lcymcdnld** [satijalab/seurat#1964]
Hello Seurat team! :) 

I am have performed a stepwise integration of samples across multiple condititions, across species (human vs mouse). However, when I go to RunPCA on final integrated object I get the following error:

```
combined <- RunPCA(object = combined, verbose = FALSE)
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
```
I feel like there is something going wrong in the process of scaling the data. 

<img width="815" alt="Screen Shot 2019-08-10 at 15 33 39" src="https://user-images.githubusercontent.com/40166451/62823105-062a7100-bb85-11e9-8967-ff9d9a7cb2d1.png">

```
ncol(x = combined@scale.data)
Error in ncol(x = combined@scale.data) : 
  no slot of name "scale.data" for this object of class "Seurat"

nrow(x = combined@scale.data)
Error in nrow(x = combined@scale.data) : 
  no slot of name "scale.data" for this object of class "Seurat"
```

Please help! 

Cheers,
Lucy

**Comment by lcymcdnld** [comment]
$integrated@data@x are NaN

**Comment by andrewwbutler** [comment]
Hi Lucy,

If you have `NaN`s in the `data` slot, then downstream steps like scaling or PCA are probably going to be affected. Could you post the code you ran up through integration?

**Comment by eregenyi** [comment]
Hi, in case someone comes across this post, I had the same error message. After finding the variable genes with the FindVariableFeatures() function prior to PCA, RunPCA() did not complain any more. Don't know why it did not work without it though.

`seu <- FindVariableFeatures(object = seu)` 
`seu <- RunPCA(seu, features = VariableFeatures(object = seu) )`

**Comment by zuodabin** [comment]
1. There are many methods in the process of cross-species single-cell transcriptome data integration, such as CCA, RPCA, Harmony, etc. I have now used the one2one gene from multiple species and combined these three methods to integrate single-cell data from six species. This raises the question, do I annotate the cell types of each species first and then aggregate the data, or do I annotate the cell types of six species first and then aggregate the data? (Data for all six species are from the same tissue, all cochlea)
