### ISSUE TITLE
Determine number of clusters and plot DoHeatmap with subset cells

### ISSUE THREAD

**Issue by shux999** [satijalab/seurat#1968]
Hi Team Seurat,

Thank you for your effort and this is really a brilliant program.

I have two questions,

1, I am now working on a file that is merged from two 10X genomics sequencing. I got ~10k cells after cell filtering and would like to do cell clustering. I chose top 10 PC and resolution=3 in FindCluster. It gave me total number of 43 clusters. I am wondering whether it is normal to have such a high number of clusters? Will it have adverse effect on the further analysis ? (It is recommended to use resolution=0.6-1.4 when dealing with 3k cells).

2, I finally assign the 43 clusters into four different cell types. But I am now want to look at one particular cell subpopulation in one cell type (say type A). I first create a seurat object that only contain cell type A:

`A <- subset(pbmc, idents = c("A"))`

Then I create two new seurat object, one is this subpopulation based on their specific marker, the other is other cells in Cell type A:

`Subpopulation <- subset(A, subset = Spg > 1)`
`Subpopulation_none <- subset(A, subset = Spg > 1, invert = TRUE)`

I am wondering how can I calculate the average expression of each genes in this two object and using that to plot a heatmap (compare the gene expression between this two object)?

**Comment by andrewwbutler** [comment]
Hi, 

1. The number of clusters you get will depend on many things and there's not really any way to tell if it's normal in your case based on what you mention. It will be directly tied to the resolution parameter you pick as well as the inherent diversity of cell types/states in your system. You should always evaluate your clusters in a biological context and if you're seeing an excess of clusters that don't seem sufficiently different from nearby ones, you may consider lowering the resolution parameter. 
 
2. Check out the [interaction vignette](https://satijalab.org/seurat/interaction_vignette.html) for an example of plotting average expression heatmaps.
