### ISSUE TITLE
BuildClusterTree silently

### ISSUE THREAD

**Issue by b-dawes** [satijalab/seurat#197]
Hello,

This is just a small quibble, but it looks like there's no way to run BuildClusterTree silently. For example, running BuildClusterTree prints:
```
[1] "Finished averaging RNA for cluster 1"
[1] "Finished averaging RNA for cluster 2"
[1] "Finished averaging RNA for cluster 3"
[1] "Finished averaging RNA for cluster 4"
[1] "Finished averaging RNA for cluster 5"
[1] "Finished averaging RNA for cluster 6"
[1] "Finished averaging RNA for cluster 7"
[1] "Finished averaging RNA for cluster 8"
[1] "Finished averaging RNA for cluster 9"
```

I'm running seurat in a pipelined script and want to keep my output log clean. I found a work-around by wrapping the function call in `invisible(capture.output())` but having an option built into the function would be much nicer looking.

It looks like the output is being printed by the AverageExpression call which has an option for show.progress. This could probably be fixed by having a show.progress option in BuildClusterTree that gets passed to AverageExpression.

Brian

**Comment by mojaveazure** [comment]
Fixed in the develop branch, see [this page](http://satijalab.org/seurat/devinstall.html) for instructions on installing from this branch.

**Comment by b-dawes** [comment]
I downloaded the develop branch but the new option didn't seem to help. I think this is because if do.reorder is true, BuildClusterTree is rerun and the show.progress option isn't passed to it.

**Comment by mojaveazure** [comment]
Whoops, my bad. Thank you for catching this!
