### ISSUE TITLE
merge different cell types

### ISSUE THREAD

**Issue by xiexiaowei** [satijalab/seurat#1970]
Hi,

In my last issue, you responded to me:
"If there are not shared cell types between the batches and you want them in the same object, you should just merge them. If there are shared cell types and there is a batch effect, then you should use the integration methods"

But I have a new question related to this.

When I just integrate batch1, batch2 and batch3 for cell type1, the tSNE map was consistent with our research background. 
However, when I merge the objects of integrated cell type1 (with 3 batchs) and integrated cell type2 (also with 3 batchs), then scale and RunPCA again for tSNE; the tSNE map of cell type1 and cell type2 was worse than before.

So, how can I merge different cell types and present them in the same map and simultaneously keep consistent with separated integration for each cell type?

Looking forward to your reply and thanks very much again!

**Comment by yuhanH** [comment]
How do you normalize your data before integration?
If you use SCTransform to normalize your data, you cannot merge two integrated objects directly.

**Comment by xiexiaowei** [comment]
The result for integrating the data containing cell type1 and 2 was not well, they could not anchor together. 
However, I tried another way, the effect is better:
1. SCTransform for each cell type (each cell type including 3 batchs)
2. merge 2 cell types
3. SCTransform again and runPCA, runUMAP
How do you think about this?
