### ISSUE TITLE
PBMC vignette: UMAP not recognised by reticulate on Windows

### ISSUE THREAD

**Issue by yassintp** [satijalab/seurat#1973]
I'm trying to follow the basic Seurat tutorial for the 10X Genomics PBMC dataset. Everything worked perfectly up to the UMAP dimensionality reduction. My setup is as follows:
- Windows 10 1903 64-bit
- R 3.6.1 64-bit
- RStudio 1.2.1335
- Seurat 3.0.2
- Python 3.7.4 64-bit

When trying to install `umap_learn`, `py_install()` wanted me to setup Anaconda for Windows. So I installed Anaconda3, set up a Conda environment and installed `umap_learn` successfully. However `py_module_available("umap_learn")` still returned `FALSE` and Seurat wouldn't find UMAP. After searching around your Github repo I found several users with similar issues and your team suggested to not use Anaconda since `reticulate` might have problems finding Anaconda-installed packages. Now I uninstalled Anaconda again and ran `pip install umap_learn` successfully on the command line. `py_config()` also recognises the Python installation: 

```
> py_config()
python:         C:\Users\Yassin\AppData\Local\Programs\Python\Python37\python.exe
libpython:      C:/Users/Yassin/AppData/Local/Programs/Python/Python37/python37.dll
pythonhome:     C:\Users\Yassin\AppData\Local\Programs\Python\Python37
version:        3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

python versions found: 
 C:\Users\Yassin\AppData\Local\Programs\Python\Python37\python.exe
 C:\Users\Yassin\AppData\Local\Programs\Python\Python37\\python.exe
 C:\Users\Yassin\AppData\Local\Programs\Python\PYTHON~1\\python.exe
```
Still the UMAP module is not available though, and trying to install it from within R asks to install Anaconda again. 

What's the proper way to install UMAP on Windows for use with the Seurat package in R?

Thanks a lot!

**Comment by mojaveazure** [comment]
I'm not sure what the issue is; here's how I've set up Seurat/UMAP on my Windows 10 machine

```ps
PS C:\Users\mojav> pip --version
pip 19.0.3 from c:\program files\python37\lib\site-packages\pip (python 3.7)
PS:C\Users\mojav> python --version
Python 3.7.4
PS:C\Users\mojav> pip install --user umap-learn
[truncated]
```

```R
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth
> install.packages("Seurat")
> library(Seurat)
> data("pbmc_small")
> pbmc_small
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne
> pbmc_small <- RunUMAP(pbmc_small, dims = 1:ncol(pbmc_small[['pca']]))
> pbmc_small
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 3 dimensional reductions calculated: pca, tsne, umap
> reticulate::py_config()
python:         C:\PROGRA~1\Python37\python.exe
libpython:      C:/PROGRA~1/Python37/python37.dll
pythonhome:     C:\PROGRA~1\Python37
version:        3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\mojav\AppData\Roaming\Python\Python37\site-packages\numpy
numpy_version:  1.17.0

python versions found: 
 C:\PROGRA~1\Python37\python.exe
 C:\PROGRA~1\Python37\\python.exe
> retic```ulate::py_module_available('umap')
TRUE
```

I doubt that it's an issue between R 3.5 and 3.6; the one thing I can think of is that you used an underscore instead of a dash for installing `umap-learn`, but I'm not at all convinced that's it.

What happens if you import UMAP in Python?

```python
>>> import umap
```

**Comment by yassintp** [comment]
Thanks a lot for your answer, I think the problem was that during the Anaconda installation, I did not choose the option to put Conda in my PATH variable since the installer said this was not recommended. I installed Anaconda again with the PATH variable and now it works like a charm!
