### ISSUE TITLE
RunUMAP, RunTSNE, finding cluster,

### ISSUE THREAD

**Issue by jhl0214** [satijalab/seurat#1976]
Hi, so I followed the tutorial on seurat website. They first integrated the data and ran RunPCA to reduce the dimension to 1:30 by setting npcs = 30 when running the function. So is it recommended to use RunUMAP(data, reduction = "pca", dims = 1:30) with dims=1:30 since PCA has 30 dimensions? Or should I use less dimensions?
Also, if I pass the argument n.components = 5L when running RunUMAP or RunTSNE, shouldn't it reduce either umap or tsne to 5 dimensions? I thought it should, but it's keep reducing to 2 dimensions.
Lastly, can I run FindNeighbors with reduction = "umap" or reduction = "tsne" and dims = 1:5? or is this not recommended at all and just using reduction = "pca", dims = 1:30 is recommended?

Thanks in advance!

**Comment by andrewwbutler** [comment]
Hi,

1. Choosing the dimensionality of your dataset is not really a solved problem. We provide some guidance in [this tutoria](https://satijalab.org/seurat/pbmc3k_tutorial.html).
2. For `RunUMAP`, yes the parameter is `n.components`. This should reduce to 5 dimensions. E.g.
```R
pbmc_small <- RunUMAP(pbmc_small, dims = 1:3, n.components = 5)
> dim(Embeddings(pbmc_small[["umap"]]))
[1] 80  5
```
3. We typically build the graphs used for clustering (via `FindNeighbors`) in PCA space and use umap/tsne for visualization though you could explore using umap for graph building as well.
