### ISSUE TITLE
Can Sctransform work in Seurat 3.0.3 CRAN version?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1977]
Hello,
I couldn't install Seurat develop version for a lot of reasons.And I saw Sctransform function in [your package help pages](https://cran.r-project.org/web/packages/Seurat/Seurat.pdf) which compiled in 2019-06-15,but in your[ Integration and Label Transfer page](https://satijalab.org/seurat/v3.0/conversion_vignette.html) which compiled: in 2019-07-16, it shows that we need use this function after installing develop version.
I'm really confused.Coud you give me some intruction?How can I determine if a function is added ito CRAN version？
![图片](https://user-images.githubusercontent.com/30619010/63068586-4a7f8d80-bf46-11e9-8ba3-6a76d62e9a31.png)

**Comment by andrewwbutler** [comment]
Hi,

The `SCTransform` function is available on the latest CRAN version. This is demonstrated in the [sctransform vignette](https://satijalab.org/seurat/sctransform_vignette.html) with some explanation of what it is doing. 

The tab on the integration vignette demonstrates how to use that function in combination with the integration workflow. This combined functionality is currently only available on the develop version but will be submitted to CRAN in the near future.
