### ISSUE TITLE
Can't use reduced data and cells.use in RunDiffusion?

### ISSUE THREAD

**Issue by mukundvarma** [satijalab/seurat#198]
It looks like if you use PCA or ICA in RunDiffusion(),  with a subset of the cells, then the data is not subset correctly?

Lines 1128:1136 in dimensionality_reduction.R

**Comment by satijalab** [comment]
Good catch, thanks!. Please do feel free to fix and submit a pull request.

Having said that, it would likely be a better option to first create a new Seurat object with SubsetData, and then to run dimensionality reduction on that object.
