### ISSUE TITLE
rownames of a DotPlot object $data

### ISSUE THREAD

**Issue by akhst7** [satijalab/seurat#1980]
I exported a DotPlot object as in;

 `e=DotPlot(PA.combined.sct, features = con.genelist2$V2, cols=c("red", "blue"), split.by = "type", group.by = "mouse")+theme(axis.text.x.bottom = element_text(size=8,angle = 45), axis.text.y.left=element_text(size = 8))`

When I looked at gene names in **rownames**of e$data, I noticed names have additional number corresponding to increment of repeated names, as `"Mmp14`.....`Mmp141`....`Mmp142`and so forth.  Is there any way I can suppress this addition of increment number at the end of gene names ?

**Comment by yuhanH** [comment]
I think there may some duplicated gene names in your data. You can add other character there to make gene names unique.

**Comment by akhst7** [comment]
There is no duplicated names.   Numbers were added at the end of every gene names in my list and added systematically according to the order of clusters. First cluster has no numbers added and in the second cluster, all the featured gene names have 1 added at the end and in the next cluster, all of them have 3, and so forth.
