### ISSUE TITLE
PrepSCTIntegration

### ISSUE THREAD

**Issue by afcmalone** [satijalab/seurat#1981]
Hi, this may be a silly question. Is there a reason for the future.globals.maxSize = 4000 * 1024^2 size limit when running SCTransform integration pipeline os per the vignette on the Seurat website? I am trying to run this code on a number of large objects and i get an error saying globals that need to be exported exceed size limit.
Thanks

**Comment by andrewwbutler** [comment]
Hi,

If you're exceeding the size limit you should increase that option parameter to reflect the larger object sizes.
