### ISSUE TITLE
DoHeatmap by group and cluster

### ISSUE THREAD

**Issue by RafMD** [satijalab/seurat#1982]
Hi,

I recently used the integrated function to combine a KO and a WT of the same cell. I was able to successfully create a TSNE plot which i was able to split based on condition. However i was wondering if  it is also possible to do the same thing with a heatmap where. i first construct a heatmap with the combine data then split the heatmap based on the clusters and group. Thanks in advance.

**Comment by timoast** [comment]
Hi, please see https://github.com/satijalab/seurat/issues/1943
