### ISSUE TITLE
DoHeatMap Adjust Column Widths

### ISSUE THREAD

**Issue by totipoint** [satijalab/seurat#1984]
Is there a way to adjust the column widths for the cell clusters that are plotted by the DoHeatMap function?
![image](https://user-images.githubusercontent.com/50008266/63180069-74ef4a80-c01b-11e9-8386-c233bf7ef1e5.png)
For instance, in the example above from the Guided Clustering Tutorial, is there a way I can make it such that each of the clusters has an equal column width (i.e., the width of the cluster 8 column is the same as the width of the other clusters)?

**Comment by mojaveazure** [comment]
Hi,

Each column (line of color) in `DoHeatmap` is an individual cell. You could downsample your object to have an equal number of cells per identity if you really wanted equal cluster columns, but there's no way to set that as a parameter in `DoHeatmap`.
