### ISSUE TITLE
Calculating silhouette scores from Seurat v3 outputs

### ISSUE THREAD

**Issue by gnovikov** [satijalab/seurat#1985]
Hello

I saw in your recent paper (Stuart et al.) that you computer silhouette scores for your clustering in Seurat. I know that this is a package within cluster but I am not sure what would be the correct input to that function to generate those scores. I would sincerely appreciate your help!

Gloriia

**Comment by timoast** [comment]
Hi Gloriia,

You can see how we computed the silhouette scores [here](https://github.com/satijalab/Integration2019/blob/master/analysis_code/integration/integration_metrics.R#L36)

**Comment by tkapello** [comment]
Hi,

 I wanted to ask for a clarification about the SIlhouette score you calculated here. In your code, can you please explain what the columns of the _sil_ silhouette object represent? I would expect that the first column is each cell from each cluster and the third column would be the silhouette values. But what about the second one? Thanks in advance!

**Comment by satijalab** [comment]
You can type
```
?silhouette
```
 for more information:

silhouette() returns an object, sil, of class silhouette which is an n x 3 matrix with attributes. For each observation i, sil[i,] contains the cluster to which i belongs as well as the neighbor cluster of i (the cluster, not containing i, for which the average dissimilarity between its observations and i is minimal), and the silhouette width s(i) of the observation. The colnames correspondingly are c("cluster", "neighbor", "sil_width").


So the second column is the neighbor cluster for cell i

**Comment by chansigit** [comment]
> Hi Gloriia,
> 
> You can see how we computed the silhouette scores [here](https://github.com/satijalab/Integration2019/blob/master/analysis_code/integration/integration_metrics.R#L36)

Could you tell us how long it takes to run it? I got 50k cells and it looked slow.

**Comment by chansigit** [comment]
> Hi Gloriia,
> 
> You can see how we computed the silhouette scores [here](https://github.com/satijalab/Integration2019/blob/master/analysis_code/integration/integration_metrics.R#L36)

Could you tell us how long it takes to run it? I got 50k cells and it looked slow.

**Comment by JunyanKan** [comment]
When I performed `silhouette(x, dist)` function, I met an error `long vectors (argument 5) are not supported in .C`. My dataset contains about 80,000+ cells. Do you have any idea?

**Comment by LucaTucciarone** [comment]
I have the same problem, where you able to fix it?
If I downsample the object I can get around it, but I really wanted to calculate the silhouette scores per cell (and use that metric to QC my data). I got only 57k cells and I have that error
