### ISSUE TITLE
Error in Read10X(data.dir = counts_matrix_filename Seurat version 3

### ISSUE THREAD

**Issue by EleniStylianou** [satijalab/seurat#1986]
I am trying to read GSE116222_Expression_matrix.txt.gz using the following code:

dirname <- "/.../Downloads/mydir/"
counts_matrix_filename = paste0(dirname, "/GSE116222_Expression_matrix.txt.gz/")
counts <- Read10X(data.dir = counts_matrix_filename)

I get the following error:

Error in Read10X(data.dir = counts_matrix_filename) :
Directory provided does not exist

I would appreciate your help. I have verified that I am running  Seurat v 3.

Thank you.

**Comment by j-andrews7** [comment]
You're providing a directory name instead of a file name. Also, it's not a 10X directory, so you shouldn't be using `Read10X()`.

Something like this should work:
```
dirname <- "/.../Downloads/mydir/"
counts_matrix_filename = paste0(dirname, "/GSE116222_Expression_matrix.txt.gz")
counts <- read.table(counts_matrix_filename, sep = "\t", header = TRUE)
scrna <- CreateSeuratObject(counts)
```

**Comment by EleniStylianou** [comment]
Thank you. Appreciate the helpful and rapid reply.

 

Best,

Eleni

**Comment by pariaaliour** [comment]
-When I try to read and create Seurat object using the command below:

samples <- c("T01472", " T01473", " T01479", " T01486", " T01489", " T01493", " T01496", " T01500")
for (sample in samples) {
    sc.data <- Read10X(data.dir = paste0("~/runs/paria/projects/als.project/Cellranger/", sample, ".outs/raw_feature_bc_matrix"))
    assign(paste0(sample), CreateSeuratObject(sc.data, project = paste0(sample)))
}
-I get the following error:
Error in Read10X(data.dir = paste0("~/runs/paria/projects/als.project/Cellranger/",  : 
  Directory provided does not exist

Does anyone know how should I solve it? I appreciate any comments.
