### ISSUE TITLE
What is the difference between seurat_clusters and integrated_snn_res.0.5?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1987]
Hello,
 I have a small but strange question.What is the difference between seurat_clusters and integrated_snn_res.0.5?I have only made one time findcluster analysis,so in my view they should be same.And they are both factors and have same number .Why I got different  order after grouping by and count based on them?
I'm really confused.  Why the order made by integrated_snn_res.0.5 is so disordered?
```
> class(Merge.integrated$seurat_clusters)
[1] "factor"
> class(Merge.integrated$integrated_snn_res.0.5)
[1] "factor"
> percentData <- Merge.integrated@meta.data %>% group_by(time.sum) %>% dplyr::count(integrated_snn_res.0.5) %>%
+   dplyr::mutate(ratio=scales::percent(n/sum(n)))
> percentData
# A tibble: 81 x 4
# Groups:   time.sum [4]
   time.sum integrated_snn_res.0.5     n ratio
   <chr>    <fct>                  <int> <chr>
 1 " E11"   0                        284 5.3% 
 2 " E11"   1                       1080 20.2%
 3 " E11"   10                       126 2.4% 
 4 " E11"   11                       183 3.4% 
 5 " E11"   12                       321 6.0% 
 6 " E11"   13                       185 3.5% 
 7 " E11"   14                       330 6.2% 
 8 " E11"   15                       130 2.4% 
 9 " E11"   16                       106 2.0% 
10 " E11"   17                       212 4.0% 
# ... with 71 more rows
> percentData <- Merge.integrated@meta.data %>% group_by(time.sum) %>% dplyr::count(seurat_clusters) %>%
+   dplyr::mutate(ratio=scales::percent(n/sum(n)))
> percentData
# A tibble: 81 x 4
# Groups:   time.sum [4]
   time.sum seurat_clusters     n ratio
   <chr>    <fct>           <int> <chr>
 1 " E11"   0                 284 5.3% 
 2 " E11"   1                1080 20.2%
 3 " E11"   2                 721 13.5%
 4 " E11"   3                 247 4.6% 
 5 " E11"   4                 284 5.3% 
 6 " E11"   5                  82 1.5% 
 7 " E11"   6                 191 3.6% 
 8 " E11"   7                 209 3.9% 
 9 " E11"   8                 286 5.3% 
10 " E11"   9                 346 6.5% 
```
![image](https://user-images.githubusercontent.com/30619010/63205611-8ac34500-c0d9-11e9-871d-13f14209506d.png)

**Comment by j-andrews7** [comment]
The factor level order is just different for each. The ratio should be the same for each label.

This isn't really a Seurat question. More can be read [here](http://www.cookbook-r.com/Manipulating_data/Changing_the_order_of_levels_of_a_factor/) (or by googling "R factor level order").

**Comment by mojaveazure** [comment]
As stated in the documentation for [`FindClusters`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.2/topics/FindClusters)

> Returns a Seurat object where the idents have been updated with new cluster info; latest clustering results will be stored in object metadata under 'seurat_clusters'. Note that 'seurat_clusters' will be overwritten everytime FindClusters is run

Please be sure to read the documentation for more information about what results are generated from Seurat-provided functions and where said results are stored
