### ISSUE TITLE
What's the difference among the four algorithms in findcluster function

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1988]
Hello,
First question,what's the difference among the four algorithms in findcluster function.[The article ](https://arxiv.org/abs/1810.08473)said that the Leiden algorithm is faster than the default Louvain algorithm.But in my data, it's opposite.The Leiden algorithm takes more time! And I don't understand the reminder that 1 singletons identified.What's singletons?
Also, I can't distinguish them from the result.the first one is made by Louvain,the second one is made by Leiden.How can it prove that Leiden is well-connected than Louvain[ as the article said](https://arxiv.org/abs/1810.08473)?

```
> Merge.integrated <- FindClusters(object = Merge.integrated,resolution = 0.6,algorithm = 4 )
1 singletons identified. 16 final clusters.
```
![image](https://user-images.githubusercontent.com/30619010/63214543-ed552900-c14b-11e9-8c24-99a0930f932b.png)

![image](https://user-images.githubusercontent.com/30619010/63214503-85064780-c14b-11e9-9d39-0909bb91e78f.png)

**Comment by andrewwbutler** [comment]
Hi, 

1. The Leiden paper you mention discusses the differences between the algorithms a bit. You could also refer to the [SLM paper](https://rd.springer.com/article/10.1140%2Fepjb%2Fe2013-40829-0) for more discussion of the methods.
2. The exact timing of the various algorithms depends somewhat on the implementation. The initial inclusion of the Leiden algorithm in Seurat was basically as a wrapper to the python implementation. This introduces overhead moving between the two languages that make timing comparisons less meaningful. We have updated this in #1858 to use the leiden R package.
3. Singletons are cells that compose an entire cluster (i.e. single cell clusters).
4. If you want to prove statements about connectivity, take a look at Appendix B in the leiden paper you link to. In practice for single-cell data, there are cases where Leiden may outperform but there are also cases where these algorithms seem to return essentially the same results, YMMV.
