### ISSUE TITLE
FindVariableFeatures and FindClusters functions in seurat

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#1989]
Hi all,

  this is a theoretical question, rather than a bug issue so apologies if it should not posted here. I have been using the Seurat pipeline for a few months now and I wanted some advice on the _FindVariableFeatures_ and _FindCLusters_ functions. The question I have is how do the user set up their arguments, e.g. number of variable genes or resolution, especially in samples (tissues) where no particular number of cell types is expected (unlike, for instance, in the blood where the analysis could be tailored to find the major leukocytes). I once read that a rule of thumb is to opt for the parameters which give the highest numbers of clusters so that no distinct cell types are merged. Is this what others follow or are there specific values to number of genes or resolution that generally work well?

**Comment by andrewwbutler** [comment]
Hi,

Generally, we find that 2-3K genes tend to work well for most datasets that we analyze (and that's what we use in all [vignettes](https://satijalab.org/seurat/vignettes.html)). We tend to vary the resolution parameter more between datasets depending on the cell type/state complexity of the data. There is no "right" answer that will work for all datasets. For annotating clusters by hand, there are generally two strategies that people seem to use. Either you start out with a relatively low resolution to define the major cell types and then refine/iterate down from that to get more subtle subdivisions. The other strategy is the one that you mention where you start with a high resolution and merge back clusters that are deemed "overclustered" (essentially biologically meaningless splits). However you want to approach it, we generally advise a careful biological inspection of the clusters and their defining features to be sure that you've captured all the distinct cell types without introducing spurious clusters.
