### ISSUE TITLE
Visualize CCA after merge

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#199]
Putting together two 10X datasets.  Seurat 2.1.  Following Seurat Alignment Tutorial.  Got past the "add.cell.id" issue.   RunCCA seems to have worked (after allotting more RAM).   But I'm getting a persistent DimPlot error.  See below: 

```R
> MergP2_16 <- RunCCA(object = mp2.data,object2 = me16p5.data, add.cell.id1 = 'mp2.data', add.cell.id2 = 'me16p5.data', genes.use = hvg.union)
Running CCA
Merging objects
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Scaling data matrix"
  100%
> p1 <- DimPlot(object = MergP2_16, reduction.use = "cca", group.by = "protocol", pt.size = 0.5, do.return = TRUE)
Error in `$<-.data.frame`(`*tmp*`, "pt.size", value = 0.5) : 
  replacement has 1 row, data has 0
```

**Comment by AndyR2** [comment]
Here are the other scripts in this project, up to the DimPlot error.
library(Seurat)
library(dplyr)
library(Matrix)
library(cowplot)
me16p5.data <- CreateSeuratObject(raw.data = me16p5.data)
me16p5.data <- NormalizeData(object = me16p5.data)
me16p5.data <- ScaleData(object = me16p5.data)
me16p5.data <- FindVariableGenes(object = me16p5.data, do.plot = FALSE)
mp2.data <- CreateSeuratObject(raw.data = mp2.data)
mp2.data <- NormalizeData(object = mp2.data)
mp2.data <- ScaleData(object = mp2.data)
mp2.data <- FindVariableGenes(object = mp2.data, do.plot = FALSE)
hvg.m2p.data <- rownames(x = head(x = mp2.data@hvg.info, n = 2000))
hvg.me16p5.data <- rownames(x = head(x = me16p5.data@hvg.info, n = 2000))
hvg.union <- union(x = hvg.mp2.data, y = hvg.me16p5.data)
mp2.data@meta.data[, "protocol"] <- "Mp2"
me16p5.data@meta.data[, "protocol"] <- "Me16.5"
MergP2_16 <- RunCCA(object = mp2.data,object2 = me16p5.data, add.cell.id1 = 'mp2.data', add.cell.id2 = 'me16p5.data', genes.use = hvg.union)
p1 <- DimPlot(object = MergP2_16, reduction.use = "cca", group.by = "protocol", pt.size = 0.5, do.return = TRUE)

**Comment by AndyR2** [comment]
Don't know if this is making the difference at the DimPlot error, but to initially load my 10X files, rather than using the "read.table" function , I used the "Read10X" function (as shown in ClusteringTutorial), as I had .tsv files rather than .txt files.

mp2.data <- Read10X(data.dir = "~/Cell Ranger Files/Mouse/Mp2_100617/filtered_gene_bc_matrices/mm10")

**Comment by AndyR2** [comment]
I note that #184 shows the same error, and it was commented on that this was a bug that is fixed in "develop branch".    Please explain how I implement that fix. thx

**Comment by leonfodoulian** [comment]
Dear AndyR2,

Please follow the instructions in [this page](http://satijalab.org/seurat/devinstall.html) to install the developmental version of Seurat. When the version of Seurat will be updated, the fix will also be updated. So, then you can reinstall the new version of Seurat from CRAN following the instructions in [this page](http://satijalab.org/seurat/install.html).

Best,
Leon

**Comment by AndyR2** [comment]
Leonfodoulian,
Thx for the reply.  However, after installing the Dev Ver of Seurat per instructions you provided, then rerunning the project, I got that same DimPlot error.

note:  under the Packages tab, I still see Seurat 2.1.0.   Should this have changed?

**Comment by AndyR2** [comment]
Leon
After installing Dev Version, per instructions on linked page, I re-ran the commands and I got that same error at the same line.

**Comment by leonfodoulian** [comment]
Dear AndyR2,

I have received an e-mail from you in which you state that installing the development version of Seurat did not fix your issue. However, I don't see the post here on GitHub. Did the issue get fixed?

Regarding the version of Seurat, it is still the version Seurat v2.1.0, but the development one.

Best,
Leon

**Comment by AndyR2** [comment]
Leon,
I deleted that note because I didn't have the install completed correctly at the time.   btw, the install instructions should add the line "library(devtools)" in order to be complete.

Anyway, I did get the install done and re-ran the project.  Getting past DimPlot command, but now getting an error at the next line:  VlnPlot.   Pasting that chunk of scripts below.


> mp2.data@meta.data[, "protocol"] <- "Mp2"
> me16p5.data@meta.data[, "protocol"] <- "Me16.5"
> MergP2_16 <- RunCCA(object = mp2.data,object2 = me16p5.data, add.cell.id1 = 'mp2.data', add.cell.id2 = 'me16p5.data', genes.use = hvg.union)
Running CCA
Merging objects
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Scaling data matrix"
  |=============================================| 100%
Warning messages:
1: In rownames(cca.data) == object@cell.names :
  longer object length is not a multiple of shorter object length
2: In rownames(cca.data) == object@cell.names :
  longer object length is not a multiple of shorter object length
3: In rownames(cca.data) == object2@cell.names :
  longer object length is not a multiple of shorter object length
4: In rownames(cca.data) == object2@cell.names :
  longer object length is not a multiple of shorter object length
> p1 <- DimPlot(object = MergP2_16, reduction.use = "cca", group.by = "protocol", pt.size = 0.5, do.return = TRUE)
> p2 <- VlnPlot(object = MergP2_16, features.plot = "CC1", group.by = "protocol", do.return = TRUE)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 6946, 3464

**Comment by blancha** [comment]
Yes, I'm getting exactly the same issue as AndyR2, with the development version.
I installed the development version to fix the described bug with the RunCCA function. 
My code will now run the DimPlot function, but fails on the VlnPlot function.
Since AndyR2 is reporting exactly the same problem, I'm assuming the problem is with the Seurat source code, and not my own code, but it's always possible that I'm making a mistake.
Thank you.

```
> p1 <- DimPlot(object=data.merged, reduction.use="cca", group.by="sample" ....                                                                                 
[TRUNCATED]                                                                                                                                                     
                                                                                                                                                                
> p2 <- VlnPlot(object=data.merged, features.plot="CC1", group.by="sample", do.r                                                                                
eturn=TRUE)                                                                                                                                                     
Error in data.frame(..., check.names = FALSE) :                                                                                                                 
  arguments imply differing number of rows: 8871, 7471                                                                                                          
In addition: Warning messages:                                                                                                                                  
1: In rownames(cca.data) == object@cell.names :                                                                                                                 
  longer object length is not a multiple of shorter object length                                                                                               
2: In rownames(cca.data) == object@cell.names :                                                                                                                 
  longer object length is not a multiple of shorter object length                                                                                               
3: In rownames(cca.data) == object2@cell.names :                                                                                                                
  longer object length is not a multiple of shorter object length                                                                                               
4: In rownames(cca.data) == object2@cell.names :                                                                                                                
  longer object length is not a multiple of shorter object length 
```

**Comment by blancha** [comment]
Thanks for the quick fix attempt, but I'm still getting an error message.
If we look at it on the bright side, he difference between the numbers of rows is lower now, so we're making progress?

```
> p1 <- DimPlot(object=data.merged, reduction.use="cca", group.by="sample" ....
[TRUNCATED]
                                                                                
> p2 <- VlnPlot(object=data.merged, features.plot="CC1", group.by="sample", do.r
eturn=TRUE)                                    
Error in data.frame(..., check.names = FALSE) :       
  arguments imply differing number of rows: 8871, 8857
```

**Comment by AndyR2** [comment]
blancha,
hi.  thx for getting involved in fixing this issue.  I guess I am over my head, but how did implement the fix provided by mohaveazure?   Did you modify the seurat code, of download a modified development version?

**Comment by AndyR2** [comment]
Ok.  Assumed the right course was to reinstall Seurat dev. version.    That went well.    Re-ran the project and Viola!   It worked through the plot_grid(p1, p2) command with no errors or warnings.   Thx.   Moving on to next step, hopefully.

**Comment by blancha** [comment]
Great. Works for me too.
Thanks!

On an unrelated subject, I'm still not quite clear on how the algorithm works exactly, so I'd love an opportunity to better understand the algorithm. If you ever provide any other information other than the published article, like a filmed conference presentation or a video-conference, I'd love to know.

@AndyR2 
As you found out, you can just reinstall the package to squash the previous version.
If you want, you can also keep different versions in different folders, in case you don't want the latest version to squash the older one, or you don't want the development version to replace the master version.
```
library(devtools)
dir.create("~/R_alternative_packages")
withr::with_libpaths(new = "~/R_alternative_packages", install_github("satijalab/seurat", ref = "develop"), action="prefix")
withr::with_libpaths(new = "~/R_alternative_packages", library("Seurat"), action="prefix")
```

**Comment by AndyR2** [comment]
Hurray!  Made it through clustering and tsne plotting.   Thx for the help folks!

I do have a related Q:   Suppose I have THREE data sets that I want to merge.   Do I put them all in together at the start, e.g. expanding the number of initial Seurat objects created to 3, or some thing like taking my new MergP2_16 dataset and adding another data set to that?

**Comment by satijalab** [comment]
Good to see this is working now. See also #176

**Comment by xnaer** [comment]
Hi Leon

I try to install dev.version of seurat but got the error below. What should I do? Thx.

> library(devtools)
> install_github("satijalab/seurat", ref = "develop")
Installation failed: Problem with the SSL CA cert (path? access rights?)

Bests,
Na

**Comment by mschilli87** [comment]
This is not related to Seurat (see https://github.com/COMBINE-lab/wasabi/issues/6 and https://github.com/Fuzzy-Logix/AdapteR/issues/13 as other examples).

However,

```r
install.packages(c("curl", "httr"))
```

might help (according to https://github.com/hadley/devtools/issues/1079#issuecomment-182390147).

---
In case this helps, [here is how I found out about it](http://lmgtfy.com/?iie=1&q=Installation+failed%3A+Problem+with+the+SSL+CA+cert+(path%3F+access+rights%3F)). :wink:

**Comment by xnaer** [comment]
@mschilli87 : Thanks for your kind reply. I changed the command to install_git("git://github.com/satijalab/seurat.git", branch = "develop") 
and it works.
