### ISSUE TITLE
Error in FeaturePlot when selecting cells

### ISSUE THREAD

**Issue by DirtyHarry80** [satijalab/seurat#1990]
Have defined my cells which I want to focus on from the Seurat object in form of a vector. I did prepare two vectors using CellSelector and another one directly by FetchData function. When I run TSNEPlot function, I can nicely set the argument "cells" as equal to my vector. Plotting works. When I want to do the same in FeaturePlot, now highlighting a gene, I get an error message:

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, :
arguments imply differing number of rows: 33, 8444

Any idea?

**Comment by mojaveazure** [comment]
Can you provide the code and data used, or a dataset that reproduces the error?

**Comment by DirtyHarry80** [comment]
Hi there,
It is Seurat object called HumanLiver from the following source: https://github.com/BaderLab/HumanLiver

As you will see below, error appears only in FeturePlot and only when argument "cells" is selected.

The code:

library(Seurat)
library(cowplot)
library(reticulate)
library(ggplot2)
library(dplyr)
library(HumanLiver)
viewHumanLiver()

# Run the standard workflow for visualization and clustering
HumanLiverSeurat <- ScaleData(HumanLiverSeurat, verbose = FALSE)
HumanLiverSeurat <- RunPCA(HumanLiverSeurat, npcs = 40, verbose = FALSE)

# t-SNE and Clustering
HumanLiverSeurat <- FindNeighbors(HumanLiverSeurat, reduction = "pca", dims = 1:30)
HumanLiverSeurat <- FindClusters(HumanLiverSeurat, resolution = 0.5)
HumanLiverSeurat <- RunUMAP(HumanLiverSeurat, dims = 1:30)

# Visualization
p1 <- DimPlot(HumanLiverSeurat, reduction = "umap")
plot_grid(p1)

# Save the object (analysis-part1)
saveRDS(HumanLiverSeurat, file = "../output/ctrlnew.rds")

# Find markers for every cluster compared to all remaining cells, report only the positive ones
markers <- FindAllMarkers(HumanLiverSeurat, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
print(ctrl.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC),n=95)

# Label clusters function
HumanLiverSeurat <- RenameIdents(HumanLiverSeurat, `0` = "Hep A", `1` = "CD3 T", `2` = "Hep B", 
                         `3` = "CD68 Mk", `4` = "Hep C", `5` = "Plasma", `6` = "NK", `7` = "gd T (A)", `8` = "CD163 Mk", `9` = "Endo (A)", 
                         `10` = "Endo (B)", `11` = "Endo (C)", `12` = "Hep D", `13` = "Hep E", `14` = "B cells", `15` = "Cholangio", `16` = "gd T (B)", `17` = "Erytho", `18` = "Stellate/Fibro")

# Make a vector of cell identities
# Way 1
cells.ident <- FetchData(HumanLiverSeurat, vars="ident")
cells.fibro <- grep("Stellate/Fibro", cells.ident$ident, ignore.case=T)
# Way 2
plot <- TSNEPlot(HumanLiverSeurat, label = TRUE, pt.size=3, repel=TRUE)
select <- CellSelector(plot, ident = "Stellate/Fibro")

# Make Plots
TSNEPlot(HumanLiverSeurat, cells=cells.fibro, label = TRUE, pt.size=3, repel=TRUE)
TSNEPlot(HumanLiverSeurat, cells=select, label = TRUE, pt.size=3, repel=TRUE)

# Plot gene of interest
FeaturePlot(HumanLiverSeurat, features ="PRELP",cells=cells.fibro, pt.size=2, reduction = "tsne")
>>>Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 36, 8444
FeaturePlot(HumanLiverSeurat, features ="PRELP",cells=select, pt.size=2, reduction = "tsne")
>>>Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 38, 8444

**Comment by mojaveazure** [comment]
I'm unable to replicate this issue; please try updating your version of Seurat.
![image](https://user-images.githubusercontent.com/11035068/63609374-0d9a4300-c5a5-11e9-9c86-7e44f5b0c58b.png)

**Comment by DirtyHarry80** [comment]
Hi Paul,

Thank you for trying to see what is the issue. I have downloaded Seurat just 2 weeks ago, so I think that I have the newest release (version 3.1.0)?

Best regards,
Andrei

--
Dr. Andrei Turtoi
Institut de Recherche en Cancérologie de Montpellier
Inserm U1194 – Université Montpellier
Tumor Microenvironment and Resistance
to Treatment Lab
208 Avenue des Apothicaires
F-34298 Montpellier Cedex 5, France
Tél: +33.(0)4.67.61.37.46
Fax: +33.(0)4.67.61.23.37
https://ircm.fr/index.php?pagendx=1146

**Comment by AgnesSteixner** [comment]
Hi, I just wanted to report that I came across the same error with my data using Seurat v3.0.2.

Best,
Agnes

**Comment by smurray33** [comment]
Hello,
 
I'm also having the same issue with Seurat v3.0.2.  The cells argument should take a vector of cell names (the colnames of the counts matrix), right?

Thanks!

**Comment by AmichayAfriat** [comment]
Hi,

I'm using v3.0.2 and having the same issue. supplying logical, numerical(index) and string(names) all yielded the same output.

`FeaturePlot(SRDS, features = "nCount_RNA", cells = !is.na(SRDS[["ETA"]]$ETA))`
> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
>   arguments imply differing number of rows: 334, 371

```
> SRDS
An object of class Seurat 
3677 features across 371 samples within 1 assay 
Active assay: RNA (3677 features)
 2 dimensional reductions calculated: pca, tsne

> SRDS[["ETA"]]$ETA
  [1]         NA         NA 0.82333826         NA 0.22009085         NA         NA 0.52970724         NA
 [10]         NA 0.86827032 0.54585244 0.54127026         NA 0.53387619         NA 0.80181428         NA
 [19]         NA 0.27286407 0.53417049 0.82290258 0.44932416         NA         NA 0.45003536 0.16659124
 [28] 0.60718900 0.74251871 0.87074690 0.90089457 0.51878074 0.88051289 0.87625515 0.40425750 0.88019307
 [37] 0.66802003 0.91402361 0.66749677 0.88299110 0.76788770 0.56106074 0.70112040 0.81150627 0.32612756
 [46] 0.77611980 0.84834070 0.84800361 0.79091027 0.88885455 ......etc
```

**Comment by AgnesSteixner** [comment]
@smurray33 Yes, correct!
