### ISSUE TITLE
Why findcluster Result give ill-defined  and unclear result?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#1991]
Hello,
I don't understand why cluster 20 is defined as a cluster.It's distribution is messy.And findallmarker result only shows 2 marker gene in this cluster.
Also,in picture 3,the pink dots(cluster 21) is messy.Can't default Louvain algorithm distinguish cluster more clearly?Or any other reason?
![image](https://user-images.githubusercontent.com/30619010/63226626-a9772800-c20e-11e9-9b46-faf9f71e7697.png)
![image](https://user-images.githubusercontent.com/30619010/63226677-50f45a80-c20f-11e9-89bd-6dc3b8f3373a.png)
![image](https://user-images.githubusercontent.com/30619010/63226732-51412580-c210-11e9-8d61-c51956a21da6.png)

**Comment by andrewwbutler** [comment]
Hi,

Your specific clustering results depends on everything done upstream as well so without any of that information, it's hard to give any concrete feedback. Based solely on the UMAP plot and the fact that there aren't many clear markers, it's possible that you're overclustering the data and lowering the resolution parameter may help. I would also look into the features that are being selected and the PCs that are being used as input (assuming that you're using a somewhat standard Seurat clustering workflow).

**Comment by Sophia409** [comment]
@andrewwbutler hello,
thanks for your reply.My cell number is about 50 thousand.So i think my resolution 0.6 is not excessive.And I find when I use tsneplot to show it ,the clusters separate well.So what's the reason?How can I make these clusters separate well on the umapplot? Because umap can show better connectivity and the relationship among these clusters, I prefer to use it not tsne.

tsne plot
![image](https://user-images.githubusercontent.com/30619010/63634767-92f92280-c68d-11e9-8d01-869e453ea48d.png)
umap plot
![image](https://user-images.githubusercontent.com/30619010/63634768-97254000-c68d-11e9-9b49-e5e6802914c7.png)
