### ISSUE TITLE
Question About Loadings(obj) <- Loadings(obj) + 0.01

### ISSUE THREAD

**Issue by xizhihui** [satijalab/seurat#1992]
Hi, thanks for creating so nice a tool which helps me a lot.
Here is my question：
In some tutorials, I found some codes as follows:
```R
new.loadings <- Loadings(object = pbmc_small[["pca"]])
new.loadings <- new.loadings + 0.01
Loadings(object = pbmc_small[["pca"]]) <- new.loadings
pbmc_small<- JackStraw(pbmc_small, ...)
```
I found these codes were also in the vignette of the `Loadings` function ( maybe it was the original source).   In my case, the results would be better, I mean cluster would be more in line with my expectation if `newloadings + 0.01` was used. However, `new.loadings + 0.01` is too large to add compared to its raw value (in my data, values would be 0.003126095, -0.021079403, et al). 
Should I use `newloadings + 0.01` in my analysis? Is this addition right? Could you give me some advices?
Thank you very much.

**Comment by xizhihui** [comment]
Hi, I came back again.
When I tried to solve the above problem, I found `Loadings` didn't work as expectation.
```r
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
oldloadings <- Loadings(pbmc[["pca"]])
oldloadings[1:5, 1:5]
newloadings <- oldloadings + 0.01
Loadings(pbmc[["pca"]]) <- newloadings
## below should be all TRUE
Loadings(pbmc[["pca"]])[1:5, 1:5] == newloadings[1:5, 1:5]
## below should be all FALSE
Loadings(pbmc[["pca"]])[1:5, 1:5] == oldloadings[1:5, 1:5]
```
pbmc was from `file = system.file('extdata', 'pbmc_raw.txt', package = 'Seurat')` and processed along with the standard workflow.  `Loadings(pbmc[["pca"]])[1:5, 1:5] == newloadings[1:5, 1:5]`  was not TRUE and `Loadings(pbmc[["pca"]])[1:5, 1:5] == oldloadings[1:5, 1:5]` was all TRUE.
What goes on? Did I do something wrong?
Thank you very much.

**Comment by andrewwbutler** [comment]
Hi,

No you should not add `0.01` to you PCA loadings. I'm not sure which tutorial you're referring to but we never recommend doing that in any of our online vignettes. This is in the example code for demonstrating how to use the `Loadings<-` setter function but just as general demonstration of how to add a set of new values to the `feature.loadings` slot, not intended as an analysis recommendation.

**Comment by kas-nik** [comment]
Hello,
I seem to have the same problem, with the `Loadings<-` setter function not working (using Seurat 3.1.5), even though following exactly the example code from the function documentation. No errors are given, just no changes happen to the `Loadings(object = pbmc_small[["pca"]])` after running the example code:
`new.loadings <- Loadings(object = pbmc_small[["pca"]])`
`new.loadings <- new.loadings + 0.01`
`Loadings(object = pbmc_small[["pca"]]) <- new.loadings`

Many thanks.
