### ISSUE TITLE
"umi_corrected" vs original umi in function "sctransform::correct"

### ISSUE THREAD

**Issue by jliu678** [satijalab/seurat#1993]
Hi,

Could you describe how "umi_corrected" is generated by the function sctransform::correct ("sctransform" calls "vst", which in turn calls sctransform::correct), if possible?

As far as I have understood, looks like you input the residual and the estimated parameters to get the "umi_corrected", and further round it and eliminate negative values. But except the round process, how come part of the "umi_corrected" is different with the original "umi"? and why its necessary?

thanks

**Comment by timoast** [comment]
Hi, please ask this question in the [sctransform](https://github.com/ChristophH/sctransform) repository

**Comment by jliu678** [comment]
thanks already moved it to sctransform
