### ISSUE TITLE
ReadH5AD duplicated 'row.names'

### ISSUE THREAD

**Issue by RebeccaHerbst** [satijalab/seurat#1995]
When importing the data using the ReadH5AD function, I run into an error because of the duplicated gene names. The unique.features which is part of Read10X and Read10X_h5 does not work here. Any help much appreciated in how to best read in citeseq data.

**Comment by mojaveazure** [comment]
Hi,

We are transitioning our support for AnnData/H5AD files to [SeuratDisk](https://github.com/mojaveazure/seurat-disk), our new package for interfacing `Seurat` objects with single-cell HDF5-based file formats. We would very much like it if you could give this a shot for reading in your data.

You can install SeuratDisk with the following:
```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")
```

A tutorial on how to read in AnnData/H5AD files via the h5Seurat intermediate can be found [here](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html). Greater detail about the new `Convert` mechanism can be found [here](https://mojaveazure.github.io/seurat-disk/reference/Convert.html)

If you come across any bugs in reading in your HDF5 files, please post them in mojaveazure/seurat-disk#1. Please note, there are some stipulations about the format of your AnnData/H5AD posted in https://github.com/mojaveazure/seurat-disk/issues/1#issue-619215532
