### ISSUE TITLE
Does FindConservedMarkers take into account the sign (directionality) of the log fold change across groups/conditions

### ISSUE THREAD

**Issue by toddknutson** [satijalab/seurat#1996]
Thank you for the explanation of `FindConservedMarkers` in these issues https://github.com/satijalab/seurat/issues/1164 and https://github.com/satijalab/seurat/issues/1705#issuecomment-504473676.

One thing that was not discussed was whether `FindConservedMarkers` takes into account the sign (directionality) of the log fold change across groups/conditions (e.g. X and Y)? 

For example, if `X_avg_logFC ` was positive and `Y_avg_logFC ` was negative, both with small individual p-values (`X_p_val_adj` and `Y_p_val_adj`), does the `mimimump_p_val ` take this "opposite" gene expression directionality into account? It seems straightforward to post-filter the output table based on matching `X_avg_logFC ` and `Y_avg_logFC ` sign. But I would appreciate your thoughts. Thank you!

**Comment by andrewwbutler** [comment]
Hi Todd,

It's a good point. The direction of the gene expression difference is not reflected in combined p-value (you can read more about what exactly the different meta-analysis methods are doing in the respective function docs -- i.e. `?metap::minimump`). Filtering the output table as you suggest would be a good way to ensure the markers you identify are both consistently different across groups/conditions between the two defined clusters **and** are different in the same direction.
