### ISSUE TITLE
group coloring switches sides in VlnPlot with split.by 

### ISSUE THREAD

**Issue by Ryan-Zhu** [satijalab/seurat#1998]
Hello,
I am running the dev version. Below is my command to make a Violin plot split by a grouping variable:
`VlnPlot(object = obj, features = "gene1",  split.by = "group", assay="RNA", pt.size=0.5)`
Strangely, group1(red) is initially plotted on the left side but switched to the right side in the same graph. An example is attached. Thank you. 
<img width="370" alt="example" src="https://user-images.githubusercontent.com/6526590/63295035-90a75a80-c280-11e9-9feb-1b5b79b97c49.PNG">

**Comment by andrewwbutler** [comment]
Hi,

This is strange. Does the switching persist if you remove the empty identity ("Lym")?

**Comment by Ryan-Zhu** [comment]
Hi Andrew,

I removed "Lym" identity and the VlnPlot worked properly now. Note the "Lym" identity is not totally empty--there's one cell in one of the two groups. To further test this, I removed all cells in group2 (green) of "Inh", and it caused color switching again. Moreover, cells belonging to goup1 of "Inh", which should have been plotted on the left side only, are now distributed across the entire "Inh" column, which can be misleading. I'd appreciate your help to fix the bug. Thank you.
![image](https://user-images.githubusercontent.com/6526590/63623504-9c5f8d80-c5ae-11e9-88a6-381fe490995a.png)

**Comment by ahoffrichter** [comment]
> Moreover, cells belonging to goup1 of "Inh", which should have been plotted on the left side only, are now distributed across the entire "Inh" column, which can be misleading.

I think this is a general "bug". I also noticed that, when you use `split.by`, the violins are split, but the points are still allover. This can be especially misleading, when you don't have enough cells in the cluster expressing the respective gene. 

![vlnplot_black](https://user-images.githubusercontent.com/23699647/69140103-1e822400-0ac2-11ea-9c5c-2a1ba1bf674e.png)

I used the following code to show that the points are allover:
`VlnPlot(seurat.object, features = genes[2], split.by = "condition")+aes(color=seurat.object$condition)`

![vln_plot_col](https://user-images.githubusercontent.com/23699647/69140117-25109b80-0ac2-11ea-8799-859cfdbce46d.png)


If the dots are all black, in condition 2 in this plot, you would expext that more ore less the same amount of cells is expressing this gene, at more or less the same level. But when coloring the dots, it becomes clear that these are actually expressed at very different levels in the two conditions.

Is there a possibility to plot the dots of each condition only to the side of that condition when using the `split.by`  argument?

**Comment by ahoffrichter** [comment]
I just realized that with the above mentioned code 

`VlnPlot(seurat.object, features = genes[2], split.by = "condition")+aes(color=seurat.object$condition)`

the coloring again switches sides in each group. 

<img width="821" alt="Screenshot 2019-12-06 at 15 21 58" src="https://user-images.githubusercontent.com/23699647/70329685-3f75a380-183c-11ea-908a-ab7be7d08ef2.png">

**Comment by timoast** [comment]
Thanks for reporting this, it will be fixed in the next release.

**Comment by timoast** [comment]
This is now fixed on the develop branch

**Comment by saeedfc** [comment]
This still seems not fixed. I am opening a new issue.

**Comment by yulchen810** [comment]
> This still seems not fixed. I am opening a new issue.

Hi,
I also have this problem, is yours resolved?

**Comment by Chanukya-Pavan** [comment]
Hi,

This issue still persists, if anyone figured out how to fix it, please let me know

**Comment by yi6kim** [comment]
I'm encountering the same issue as well. However, I'm having the same issue when I try to create the split violin plot using ggplot() + geom_split_violin(), which I'm assuming is what the VlnPlot(split.by= ##, split.plot=TRUE) is based on. I tried setting up factors and checked levels() to see if my split.by groups are truly factorized but no success.

I wish that there was a parameter such as 'hue_order' as in seaborn.violinplot in Python so that I can control the left and right (https://stackoverflow.com/questions/59460067/controlling-sides-in-split-seaborn-violin-chart). So I don't think this is necessarily a bug in VlnPlot(), but just that there is yet no parameter that would allow us to control the ordering.
