### ISSUE TITLE
Finding clusters using custom gene list

### ISSUE THREAD

**Issue by rohan913** [satijalab/seurat#200]
Hi everyone,

I was having an issue using a custom gene list to find clusters in a dataset. I tried setting pc.genes in RunPCA to my gene list and doing the rest of my clustering as in the 33k tutorial (running FindClusters and RunTSNE based on significant principal components) but I am unable to obtain any well defined clusters as they all appear mixed together.

Thank you for your support.
Rohan

**Comment by satijalab** [comment]
This is the workflow we would suggest if you have a custom gene set to cluster on.  Apologies that it did not lead to well-defined clusters in your case.
