### ISSUE TITLE
Question regarding differential expressed

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#2000]
Hi, 
I use the default Wilcoxon rank sum to look for differentially expressed genes. I have 1200 cells and within this, I have rarer populations where single cell numbers are lower. The genes differentially expressed fits in terms of biology in the rarer cell populations. I just would like to know about how Wilcoxon works in terms of the how many minimum cells it uses in one group versus the other for any gene counts. Looking around in google, it looks like at least 3 samples/cells are used. Does this also apply in Seurat? 
Just so that I know and can describe it a little bit more on manuscripts. 
Thanks a lot.

**Comment by andrewwbutler** [comment]
Hi,

The minimum number of cells in any group being compared is set via the `min.cells.group` parameter. The default value for this in Seurat is 3. You can check out more details in the `?FindMarkers` documentation. Also, for reference, the relevant part of the code is here:

https://github.com/satijalab/seurat/blob/c9f2660ee6b88189acc3ff4aa6088a46a2558dd3/R/differential_expression.R#L1512-L1562
