### ISSUE TITLE
number of reads

### ISSUE THREAD

**Issue by naomi-croft** [satijalab/seurat#2001]
Hi, I have a Seurat object with single cell sequencing data, which I have called allsample.data.seurat

This allsample.data.seurat object contains data from 11 merged samples. I have added the tag _01, _02, _03 etc to the cell barcodes so that I can still identify the origin of each sample embedded.

How can I calculate the average number of reads per cell for each sample within allsample.data.seurat? 

I managed to make this script which gives me the average number of genes per cell:

n.genes=colSums(GetAssayData(object = allsample.data.seurat, slot = "counts")>0)
mean(n.genes[grepl("_01",names(n.genes))])
mean(n.genes[grepl("_02",names(n.genes))])
mean(n.genes[grepl("_03",names(n.genes))])
mean(n.genes[grepl("_04",names(n.genes))])
mean(n.genes[grepl("_05",names(n.genes))])
mean(n.genes[grepl("_06",names(n.genes))])
mean(n.genes[grepl("_07",names(n.genes))])
mean(n.genes[grepl("_08",names(n.genes))])
mean(n.genes[grepl("_09",names(n.genes))])
mean(n.genes[grepl("_10",names(n.genes))])
mean(n.genes[grepl("_11",names(n.genes))])

But I can't work out how to get the average number of reads per cell. Any suggestions would be very welcome!
BW,
Naomi

**Comment by timoast** [comment]
To find the mean number of counts for each cell you can run:

```r
Matrix::colMeans(allsample.data.seurat, slot = 'counts')
```

**Comment by liliay** [comment]
Hi there, 
@naomi-croft did you manage to get the mean reads per cell info ? and if so, how did you do that ? 

thx in advance for your reply

**Comment by Naomi-Guslund** [comment]
Yes I did :) This gives the average number of genes per cell per sample (what I have called orig.ident). To get average number of transcripts change nFeature_RNA to nCount_RNA

#Average number of genes expressed per sample

mean(seurat.obj@meta.data$nFeature_RNA[which(seurat.obj@meta.data$orig.ident=="01")])
with(seurat.obj@meta.data, tapply(nFeature_RNA,orig.ident, mean))

**Comment by Naomi-Guslund** [comment]
So in my example above you get the average number of reads for orig.ident 01 (sample 01)

I think you can get average number of reads per cell cluster by changing orig.ident to seurat_clusters
