### ISSUE TITLE
Could you please help me why pct.1 < pct.2 in the Cluster 0?

### ISSUE THREAD

**Issue by swlx08** [satijalab/seurat#2007]
Dear Sir or Madam,

I am using Seurat 3.0 to integrate 8 samples (3 KI, 2 KO and 3 WT) with the standard workflow. Then I Identify conserved cell type markers of Cluster 0:

![图片](https://user-images.githubusercontent.com/36035647/63400323-f3762e80-c405-11e9-9f14-bcc4df0053ce.png)

It is strange that value of pct.1 of some top marker genes is much less than the corresponding pct.2. The other clusters (1-39) have normal pct.1 values (larger than pct.2).

So could you please tell me should I solve this problem? I can't just subset Cluster 0 from my data, since it has more than 4000 cells (1/8 total cells).

Thanks a million for your attention.

Best,
Stanley

**Comment by andrewwbutler** [comment]
Hi Stanley,

I think what you're seeing here is a discrepancy between the percentage of cells expressing a particular gene (pct.1/2) and the average expression level differences between the two groups. As an example, imagine in cluster 1 you have a small subset of cells expressing the gene at very high levels where as in cluster 2 **all** cells express the gene at very low levels. This would lead to the scenario where pct.2 would be larger than pct.1 but on average it may be that cluster 1 has higher expression and thus a positive avg_logFC value.

**Comment by swlx08** [comment]
Hi andrewwbutler,

Thank you very much for your answer. Now I understand. Given that the avg_logFC values are so small (about 0.26), does it mean the cluster 0 is not biological meaningful? 
Or, should I combine the cluster 0 with another one? 

Thanks a million again,
Stanley
