### ISSUE TITLE
Sometimes UMAP reduction is mixed together and tSNE is more reasonable?

### ISSUE THREAD

**Issue by swlx08** [satijalab/seurat#2011]
Hi,

I am performing dimensional reduction on my integrated data using Seurat 3.0. Firstly I tried UMAP according to the tutorial:

`EPRN.features <- SelectIntegrationFeatures(object.list = reference.list, nfeatures = 3000)`  
 `reference.list <- PrepSCTIntegration(object.list = reference.list, anchor.features = EPRN.features, verbose = FALSE)` 
`EPRN.anchors <- FindIntegrationAnchors(object.list = reference.list, normalization.method = "SCT", anchor.features = EPRN.features)`
`EPRN <- IntegrateData(anchorset = EPRN.anchors, normalization.method = "SCT")`
`EPRN <- RunPCA(EPRN, verbose = FALSE)`
`EPRN <- RunUMAP(object = EPRN, dims = 1:30)`
`EPRN <- FindNeighbors(EPRN, reduction = "pca", dims = 1:30)`
`EPRN <- FindClusters(EPRN, resolution = 0.8)`
`p1 <- DimPlot(EPRN, reduction = "umap", group.by = "treatment")`   
`p2 <- DimPlot(EPRN, reduction = "umap", label = TRUE)`  
 `plot_grid(p1, p2)`

And I got a "twisted" plot:
![图片](https://user-images.githubusercontent.com/36035647/63498331-4203f580-c4f8-11e9-93eb-1082e365d4af.png)

It is obvious that the clusters on the right hand side are mixed together (Cluster 17, 12, 5, 10, 9, 16, 4, 14), which can't be separated clearly.

However, when I turned to tSNE:
`EPRN <- RunTSNE(object = EPRN, dims.use = 1:30, do.fast = TRUE)`
`p1 <- DimPlot(EPRN, reduction = "tsne", group.by = "treatment")`
`p2 <- DimPlot(EPRN, reduction = "tsne", label = TRUE)`
`plot_grid(p1, p2)`

The plot seems to be more acceptable:
![图片](https://user-images.githubusercontent.com/36035647/63499632-cd7e8600-c4fa-11e9-82b9-b7137d21fc3a.png)

So my questions are:
(1) Why the UMAP plot is mixed together?

(2) In my case, is tSNE better than using UMAP?

Thanks a million for your attention.
Stanley

**Comment by andrewwbutler** [comment]
Hi Stanley, 

1. The UMAP does look a little strange but it's hard to say why exactly. You could experiment with the input features/number of PCs to include to see how that affects the UMAP plot. 

2. In this case, tSNE does look "better". Generally, we tend to use both of these method for visualization purposes only so it's not "wrong" to use one over the other.
