### ISSUE TITLE
Kind request for suggestions from those experienced with large data

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#2012]
> Any updates on this? I'm getting the same issue with ~400K cells across 30 datasets. Should I just switch to RPCA for now?

> (300 GB of RAM....will try again with 1TB)"

_Originally posted by @davemcg in https://github.com/satijalab/seurat/issues/1720#issuecomment-516948860_

Sorry for a silly question here. So far I have only worked with a normal workstation for upto 8k cells. 
Soon we are planning big experiments with 15-20 samples of 10k cells each (150k - 200k cells) (~18000 features)
Is 128GB RAM sufficient for the pipeline (SCT & Integration included).  But seeing this thread @davemcg using 300GB RAM and still not able to work with 400k cell, I am not sure about what to buy.

**Comment by satijalab** [comment]
We cannot advise on hardware, but if you read the rest of that thread, we provide an alternative approach for running extremely large datasets even in the absence of a high-memory machine
