### ISSUE TITLE
SCTransform on subsets

### ISSUE THREAD

**Issue by luluyadummy** [satijalab/seurat#2014]
Dear Seurat Team,

May I get some suggestions on using SCTransform on subset and FindAllMarkers with slot='scale.data' here:

We are running a dataset with samples with different conditions. We first merge all samples and run SCTransform on the merged object, find clusters, identify different cell types, then subset based on the cell types. Use WhichCells to pull the cells of a certain cell type from the merged **raw data** (rather than using the normalized residuals/counts), and perform SCTransform on the subsets. 

Based on the description it is the most optimal to use object[["SCT"]]]@scale.data to find DEGs. I tried doing it on one of my subset data and compared it to the result I got from using slot='data' or slot='counts' in FindAllMarkers. I got many more DEGs using slot='scale.data'. When I lower the logfc.threshold value with slot='data' I see that the markers that show up using 'scale.data' but not using 'data' are significant but have very small logfc, which are not very useful for us.

My questions are:
1. Is it better to perform SCTransform on the individual subsets then do the downstream analysis (subset first then SCTransform)? Or is it better to run SCTransform on the overall object, subset, then use that subsetted data for the downstream analysis (SCTransform first then subset)?
2. Is there a way to put a threshold to limit out the genes with low logFC values while running FindAllMarkers using 'scale.data'? Also is it possible to return only genes with small enough p.adj values (I think now the return.thresh only works on p-values)? 

`T.markers.scaled <- FindAllMarkers(object = T_cell_UMAP,
                               only.pos = TRUE,
                               min.pct = 0.10,
                               return.thresh = 0.01,
                               slot = 'scale.data')`   ###2218 genes found

`T.markers <- FindAllMarkers(object = T_cell_UMAP,
                               only.pos = TRUE,
                               min.pct = 0.10,
                               return.thresh = 0.01,
                               slot = 'counts',
                            logfc.threshold = 0.10)`   ###4978 genes found

Any advice will be appreciated!

**Comment by CodeInTheSkies** [comment]
Hi @luluyadummy ,  

I wonder why you closed this question before getting a response from @satijalab .  Did you get clarity on your above questions by some other means, or by searching around in the forum and/or the tutorials?  If so, for the benefit of people like me having similar questions and situations, would you please post your answers/opinions here for the questions you had asked?

That will be fantastic!

Thanks a lot!

**Comment by luluyadummy** [comment]
> Hi @luluyadummy ,
> 
> I wonder why you closed this question before getting a response from @satijalab . Did you get clarity on your above questions by some other means, or by searching around in the forum and/or the tutorials? If so, for the benefit of people like me having similar questions and situations, would you please post your answers/opinions here for the questions you had asked?
> 
> That will be fantastic!
> 
> Thanks a lot!

Hi @CodeInTheSkies ,

Sorry, I closed this issue because at the time I wasn't sure if this is where I suppose to post these questions since I didn't get any response from anyone for over a month and didn't know there are people also watching.

From what I understand, with the first question, if you believe that batch effect is not a problem for your data then it's okay to just merge the data. Unfortunately, I still don't have any firm answer on the other question and I am still searching for one. What we see with our data though, running SCTransform directly on the subset data after gives more cell type specific variable genes (with global SCTransform on the whole object then subset we have the exact same 3000 variable genes as the whole data) and a DEG list that makes more sense with our single cell data. That's just what we see based on our data, please don't take it as a standard. 

Thanks for letting me know that there are people also waiting for an answer to the same question, I will edit and reopen this post!

**Comment by knoedlerj** [comment]
I have a very similar question, although in my case I'm trying to merge two samples of subtly different conditions and look for DEGs between matched cell populations. After subsetting to get rid of low-quality cells, if I rerun SCT on the merged dataset I get segmentation of populations by condition that are strikingly concordant with bulk RNA-seq data generated by an orthogonal purification strategy. I worry that I'm 'overfitting' or otherwise massaging the data, but it seems unlikely that an overfit would just happen to move everything in the right direction. Thoughts??

**Comment by alexthiery** [comment]
I am also struggling with this - I need to subset the data for various reasons (both cells and genes) and am not sure whether re-running SCTransform on a data subset is OK (given that the initial normalisation takes information between genes across the dataset). However, with SCTransform both scaling and finding variable genes after normalisation, I feel like the data has to be re-normalised every time it is subset. Any clarification would be much appreciated!

**Comment by satijalab** [comment]
I apologize that we never responded. 

1. You can absolutely rerun SCTransform after subsetting the object, especially if you intend to rerun PCA (i.e. subclustering)

2. When running DE, we suggest using the RNA assay (normalized counts)

**Comment by Victor21v** [comment]
So, shall we use lognormalized counts of RNA assay to do differential expression within clusters on a integrated data, or the scale.data slot from SCT as you propose in sctransform tutorial? I find it a little confusing.

Thanks in advance.
