### ISSUE TITLE
ReadH5AD doesn't read all layers

### ISSUE THREAD

**Issue by ajwilk** [satijalab/seurat#2016]
AnnData objects can store multiple layers of matrices with the same dimensions of X. The layers attribute of AnnData objects is particularly salient for use with the scvelo package, where spliced and unspliced counts can be stored in the same object. Unfortunately, it seems that Seurat's ReadH5AD doesn't support the reading of layers? In python: 
```
tdata
tdata
AnnData object with n_obs × n_vars = 17829 × 2408 
    obs: 'orig.ident', 'clusters', 'cell.type', 'n_counts', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'root_cells', 'end_points', 'velocity_pseudotime'
    var: 'means', 'dispersions', 'dispersions_norm', 'velocity_gamma', 'velocity_r2', 'velocity_genes'
    uns: 'pca', 'neighbors', 'velocity_graph', 'velocity_graph_neg', 'cell.type_colors'
    obsm: 'X_umap', 'X_pca', 'velocity_umap'
    varm: 'PCs'
    layers: 'spliced', 'unspliced', 'Ms', 'Mu', 'velocity'

tdata.layers
Layers with keys: spliced, unspliced, Ms, Mu, velocity

tdata.write('~/combined.h5ad')
```
In R: 
```
combined <- ReadH5AD("~/combined.h5ad")
Pulling expression matrices and metadata
Data is unscaled
Creating assay object
Storing X as raw and raw as counts
No variable feature expression found in h5ad file
No dimensional reduction information found
Assembling Seurat object
No nearest-neighbor graph

combined@assays
$RNA
Assay data with 2408 features for 17829 cells
First 10 features:
 AARS2, ABCA1, ABCA8, ABCB4, ABCB5, ABCC2, ABCC4, ABCC5, ABHD15, ABI2 

colnames(combined@meta.data)
 [1] "orig.ident"             "clusters"               "cell.type"              "nCount_RNA"            
 [5] "initial.size.unspliced" "initial.size.spliced"   "initial.size"           "root.cells"            
 [9] "end.points"             "velocity.pseudotime" 
```
There's only one count matrix, $RNA, written from tdata.X. Are there any plans to enable reading of layers as separate assays? Would be immensely helpful to me! Let me know if there's some behavioral option I'm missing... Thanks.

**Comment by mojaveazure** [comment]
Hi,

We don't currently support reading in H5AD layers as assay objects. However, that is something we should add. Could you provide an H5AD file with layers so we can build and test this functionality?

**Comment by ajwilk** [comment]
Absolutely, thanks!

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
