### ISSUE TITLE
Jackstraw Plot shows no significant PC for significant PCs?

### ISSUE THREAD

**Issue by tiagobrc** [satijalab/seurat#2018]
Hi,
After plotting jackstraw, in seuratv3 some of my dimensions does not show as significant, altghout it looks like they are. How can I interpret this and why is this happening? I put the seuratV2 plot to show how different it is: 

SeuratV3
<img width="646" alt="Screenshot 2019-08-24 18 40 15" src="https://user-images.githubusercontent.com/12516337/63643461-a1036f00-c69e-11e9-9db4-f68e9aa92f13.png">

SeuratV2:

<img width="1139" alt="Screenshot 2019-08-24 18 42 21" src="https://user-images.githubusercontent.com/12516337/63643478-eaec5500-c69e-11e9-8113-186b6a688c2b.png">

This issue seems to be connected to this issue: https://github.com/satijalab/seurat/issues/1871
but no response came from that post, so I am reposting it here. Thanks!

**Comment by timoast** [comment]
Assuming you're using SCTransform here, this has been addressed in #1871

If you're not using SCTransform please re-open the issue
