### ISSUE TITLE
SubsetData does not subset @raw.data

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#202]
```
> umi_seurat
An object of class seurat in project org
 17635 genes across 1172 samples.
> umi_c6 <- umi_seurat %>% SubsetData(ident.use=c(6))
> umi_c6
An object of class seurat in project org
 17635 genes across 185 samples.
> dim(umi_c6@raw.data)
[1] 17635  1172
> dim(umi_c6@data)
[1] 17635   185
> dim(umi_c6@scale.data)
[1] 17635   185
```
Looks like the function does not subset the `@raw.data` slot.

**Comment by andrewwbutler** [comment]
Hi,

This was an old design choice back when the `raw.data` matrices were much smaller/cheaper to keep around. We've added the `subset.raw` parameter to `SubsetData` in the develop branch to allow for you to optionally subset this matrix also.
