### ISSUE TITLE
Unable to access FetchData for genes after SCTransform

### ISSUE THREAD

**Issue by pratarora** [satijalab/seurat#2020]
Hi Seurat Team
After performing SCtransform, I am unable to get counts/data for any gene. The funcion works for other variables, such as percent mito, but gives var not found if a gene is selected. I can get the feature plot for the genes, so those genes are not removed while filtering. Any idea how to go about this?

Thanks!
Prateek

**Comment by wong-nw** [comment]
Hi Prateek, I've encountered a similar issue. How did you resolve it?

Thanks!
-Nathan
