### ISSUE TITLE
What should I do when encounter "No features pass logfc.threshold threshold" Error?

### ISSUE THREAD

**Issue by swlx08** [satijalab/seurat#2021]
Hi, 

I am using Seurat 3.0 for integrating my 8 samples (2 KO, 3 WT, 3 KI). After Clustering I tried to Identify conserved cell type markers:

`> LIST.CLUSTERS.and.MARKERS <- list()`
`> for (i in 0:25) {`
`+ LIST.CLUSTERS.and.MARKERS[[i+1]] <- FindConservedMarkers(ERNP, ident.1 = i, grouping.var = "treatment", only.pos = TRUE)`
`+ LIST.CLUSTERS.and.MARKERS[[i+1]] <- head(LIST.CLUSTERS.and.MARKERS[[i+1]], 5)`
`+ }`
`Testing group KO: (0) vs (3, 5, 25, 7, 4, 8, 16, 19, 17, 13, 12, 1, 6, 15, 18, 9, 23, 22, 10, 2, 21, 14, 11, 20, 24)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 29s
Testing group WT: (0) vs (18, 4, 13, 9, 8, 15, 14, 3, 20, 23, 21, 5, 10, 2, 7, 11, 12, 1, 19, 17, 22, 24, 6, 16, 25)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 03s
Testing group KI: (0) vs (7, 17, 1, 2, 21, 10, 23, 4, 6, 12, 5, 14, 13, 24, 19, 3, 16, 11, 18, 20, 9, 8, 15, 25, 22)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 05s
Testing group KO: (1) vs (3, 5, 25, 7, 4, 8, 16, 19, 17, 13, 12, 6, 15, 18, 9, 23, 22, 10, 0, 2, 21, 14, 11, 20, 24)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 17s
Testing group WT: (1) vs (18, 4, 13, 9, 8, 15, 14, 3, 20, 23, 21, 5, 10, 2, 7, 11, 12, 0, 19, 17, 22, 24, 6, 16, 25)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 15s
Testing group KI: (1) vs (7, 17, 0, 2, 21, 10, 23, 4, 6, 12, 5, 14, 13, 24, 19, 3, 16, 11, 18, 20, 9, 8, 15, 25, 22)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 49s
Testing group KO: (2) vs (3, 5, 25, 7, 4, 8, 16, 19, 17, 13, 12, 1, 6, 15, 18, 9, 23, 22, 10, 0, 21, 14, 11, 20, 24)
Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
  No features pass logfc.threshold threshold`

The calculation can't go forward because of the "No features pass logfc.threshold threshold" Error.

Besides, when I tried to identify the markers one by one, on actual markers could be found for Cluster0:

`> Cluster0 <- FindConservedMarkers(ERNP, ident.1 = 0, grouping.var = "treatment", only.pos = TRUE)`
`Testing group KO: (0) vs (3, 5, 25, 7, 4, 8, 16, 19, 17, 13, 12, 1, 6, 15, 18, 9, 23, 22, 10, 2, 21, 14, 11, 20, 24)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 29s
Testing group WT: (0) vs (18, 4, 13, 9, 8, 15, 14, 3, 20, 23, 21, 5, 10, 2, 7, 11, 12, 1, 19, 17, 22, 24, 6, 16, 25)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 03s
Testing group KI: (0) vs (7, 17, 1, 2, 21, 10, 23, 4, 6, 12, 5, 14, 13, 24, 19, 3, 16, 11, 18, 20, 9, 8, 15, 25, 22)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 05s`
`> head(Cluster0)`
 `[1] KO_p_val       KO_avg_logFC   KO_pct.1       KO_pct.2       KO_p_val_adj   WT_p_val       WT_avg_logFC   WT_pct.1       WT_pct.2       WT_p_val_adj   KI_p_val      
[12] KI_avg_logFC   KI_pct.1       KI_pct.2       KI_p_val_adj   max_pval       minimump_p_val`

Only blank results were returned, with no error reported.

So my questions are:
(1) Why the Cluster2 and Cluster0 didn't have positive cell markers? Does it mean they were not biological meaningful? 

(2) What should I do in the next step? Should I modify the resolution and run again, or subdivide the clusters which have no positive markers into smaller clusters?

Thank you very much for your attention,
Stanley

**Comment by RuixiangLiu01** [comment]
I also get the same problem as u,have u solved?thank u

**Comment by satijalab** [comment]
I apologize that we never responded. The question is what to do when there are no clusters (or DE genes) identified in the dataset. Unfortunately there's not much we can recommend in these cases, you can certainly attempt clustering at a different level of resolution as that will affect DE results

**Comment by brianpenghe** [comment]
Same question here. I was running a loop which is disrupted by this error. It would be very useful if no error is thrown.
