### ISSUE TITLE
SCTransform: why Normalize RNA data for visualization purposes?

### ISSUE THREAD

**Issue by atermanini** [satijalab/seurat#2023]
Hi, I am using SCTransform for separately normalize several 10x scRNA-Seq datasets,
and than I am following the tutorial about PrepSCTIntegration with great results: PCA, UMAP / tSNE and clustering were calculated by setting the new "integrated" assay as default assay.

Now, which is the best way to go with data visualization (VlnPlot, FeaturePlot etc)?
Reading the online documentation, the slot [["SCT"]]@data should contains log-normalized values of corrected counts. However, since SCTransform was performed on each sample separately, if I want to use [["SCT"]]@data for visualization I need to run SCTransform again so that it runs on the whole dataset?

At the end of this tutorial: https://satijalab.org/seurat/v3.0/sctransform_vignette.html
I see that, after integration, visualization was preceded by LogNormalization with NormalizeData on the RNA assay: "Normalize RNA data for visualization purposes", but I can't find other details about visualization using SCTransform-ed data.

Thanks very much!
Best,
Alberto

**Comment by jdrnevich** [comment]
I also have the exact same question, so I am commenting on this one in the hopes it will be answered and more clearly explained in the vignette. It seems that if the SCTransform's normalized and scaled data are better, why do you go back to the regular normalization in the integration vignette? And would we also use ScaleData to get values for heatmaps?

**Comment by CodeInTheSkies** [comment]
Same question in my mind too!  Would love to hear back on this from @satijalab !  Thank you!!

**Comment by nevilledusaj** [comment]
I believe they address this question in their response here: #1836 . Using the normalized RNA or SCT assay is acceptable for further downstream analysis.
I am wondering, if we revert to the SCT assay, do we use the `data` or `scale.data` slot for visualization, differential expression, or other downstream analyses, and why we'd prefer one slot over the other.

**Comment by jdrnevich** [comment]
One problem I can see with using the SCT assay after integration is that the SCT normalization was done  separately for each sample, which is likely to introduce batch effects down the line. We are using the RNA assay, normalized after integration. The `data` slot is the default used for FeaturePlot, VlnPlot, FindConservedMarkers and the `scale.data` slot is the default for DoHeatmap, and we use the defaults. Typically scaled data (mean-centered, sd-adjusted) is only used for heatmaps and the rest, especially differential expression, you want to do on normalized count values.

**Comment by nevilledusaj** [comment]
That makes a lot of sense, thank you! In that case, you it be reasonable to re-run the `SCTransform` on the integrated object's RNA Assay, saving it under a new assay name, as another way to normalize the data, correct batch effects, and find variable features for downstream analysis?

**Comment by jdrnevich** [comment]
In #1836 (linked above) they say explicitly not to re-run SCTransform on the integrated data, but running it on the RNA assay should be fine. I have not tried that yet...

**Comment by atermanini** [comment]
Oh yes, siamo alla versione 10

Sul forum github di Seurat un paio di mie domande hanno aperto un dibattito ahahhahaha 

Inviato da iPhone

**Comment by CodeInTheSkies** [comment]
> One problem I can see with using the SCT assay after integration is that the SCT normalization was done separately for each sample, which is likely to introduce batch effects down the line. We are using the RNA assay, normalized after integration. The data slot is the default used for FeaturePlot, VlnPlot, FindConservedMarkers and the scale.data slot is the default for DoHeatmap, and we use the defaults. Typically scaled data (mean-centered, sd-adjusted) is only used for heatmaps and the rest, especially differential expression, you want to do on normalized count values.

Hi @jdrnevich ,  Just to get clarification about what you said (pasted above), you use the SCT assay, normalized separately on each sample before integration, followed by PrepSCTIntegration and such as per tutorial, for PCA, etc., up until clustering and tSNE.  But then, for visualization and markers, you switch back to the RNA assay.  Is my understanding correct?  Many thanks!

**Comment by jdrnevich** [comment]
Yes, @CodeInTheSkies, we switch back to the RNA assay, run NormalizeData() and ScaleData(), then proceed with visualizations and marker detection.

**Comment by satijalab** [comment]
Apologies that we never responded, but the last comment in this thread is reasonable.

**Comment by lkqnaruto** [comment]
@jdrnevich Hi thank you for the answers. I wonder what visualization you refer to?

**Comment by jdrnevich** [comment]
Heatmaps, violin plots, shading expression values on tSNE/UMAP. Anywhere you want to see the expression differences.

**Comment by lkqnaruto** [comment]
@jdrnevich thank you for the quick response. Btw, please correct me if I'm wrong, the RNA assay after the integration step is simply the concatenated RNA assays which belongs to each dataset?

**Comment by jdrnevich** [comment]
I believe so

**Comment by lkqnaruto** [comment]
@jdrnevich Thank you. Sorry for taking your time, I have one last question. I did SCTransform for each one of my datasets, 4 in total, and then I integrate them together following the tutorial, since my goal is to perform cell type annotation, so I decide to use SingleR package, which requires the data has to be lognormalized, but I notice that both FindIntegrationAnchors and IntegrateData function use "SCT" as normalize method, therefore the integrated data would be in the scale.data slot. so I wonder whether it would be reasonable to use "LogNormalize" in those two functions based on the [description](https://satijalab.org/seurat/reference/integratedata), given I have used SCTransform for each dataset before integration?

**Comment by jdrnevich** [comment]
Sorry, I can't really give you any advice on that.

**Comment by lkqnaruto** [comment]
That's completely alright, thank you for the reply, appreciate it very much.

**Comment by hemantgujar** [comment]
Hi

I have a question.

Why do we run SCTransform on individual samples and not the dataset ?
Instead of running SCTransform on every sample and then integrating the data. Can I run SCTransform over the entire database or a group of database ? If yes. Do I need to lognormalize after that ? I want to check differential expression of genes.

Thanks
