### ISSUE TITLE
Why umap give ill-defined  and unclear clusters result?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#2024]
@andrewwbutler hello,
My cell number is about 50 thousand.So i think my resolution 0.6 is not excessive.And I find when I use tsneplot to show it ,the clusters separate well and cluster 21 gather together.But in the umap, cluster 21(pink dots) is really scattered. So what's the reason?How can I make these clusters separate well on the umapplot? Because umap can show better connectivity and the relationship among these clusters, I prefer to use it not tsne.
https://github.com/satijalab/seurat/issues/1991#issuecomment-524376266

tsne plot
![image](https://user-images.githubusercontent.com/30619010/63634767-92f92280-c68d-11e9-8d01-869e453ea48d.png)
umap plot
![image](https://user-images.githubusercontent.com/30619010/63634768-97254000-c68d-11e9-9b49-e5e6802914c7.png)

**Comment by andrewwbutler** [comment]
Hi,

There are a number of factors that influence the UMAP results. You can consider the PCs that are included and how many/which features are used as input to the PCA. There are also a number of UMAP-specific parameters that you can play with. See [this document](https://umap-learn.readthedocs.io/en/latest/parameters.html) or the help (`?RunUMAP`) for a more thorough discussion of some of those parameters.
