### ISSUE TITLE
Difference in results between uwot & umap-learn?

### ISSUE THREAD

**Issue by samuel-marsh** [satijalab/seurat#2025]
Hi,

I noticed that Seurat recently made the move to uwot as the default implementation of umap.  I understand the decision given the preference to run natively in R vs dependency of python.  Just wondering if you have any guidance/thoughts on differences in results between the two implementations?

I decided to run side-by-side comparison on recent dataset.  Below are the results running with the two different methods and the code.  Only difference between the plots is the `umap.method`.

As you can see the results of the two methods provide plots with a number of differences in relative cluster location and in spacing of clusters (most noticeably cluster 5).

Thanks very much!
Sam

_Edit_
Just to add this analysis was performed in Seurat v3.1 installed from CRAN this morning into a fresh packrat library, R3.5.1, Mac OSX Mojave.

```
all_cns <- SCTransform(all_cns, vars.to.regress = "percent.mt", verbose = TRUE, variable.features.n = NULL)
all_cns <- RunPCA(all_cns, verbose = FALSE, npcs = 75)
```

```
all_cns_uwot <- RunUMAP(all_cns, dims = 1:60, verbose = FALSE, n.neighbors = 30, min.dist = 0.3, umap.method = "uwot")
all_cns_uwot <- FindNeighbors(all_cns_uwot, dims = 1:60, verbose = FALSE)
all_cns_uwot <- FindClusters(all_cns_uwot, resolution = 0.4, verbose = FALSE)
DimPlot(all_cns_uwot, label = TRUE)
```

```
all_cns_umap <- RunUMAP(all_cns, dims = 1:60, verbose = FALSE, n.neighbors = 30, min.dist = 0.3, umap.method = "umap-learn")
all_cns_umap <- FindNeighbors(all_cns_umap, dims = 1:60, verbose = FALSE)
all_cns_umap <- FindClusters(all_cns_umap, resolution = 0.4, verbose = FALSE)
DimPlot(all_cns_umap, label = TRUE)
```

**uwot Results:**
[uwot.pdf](https://github.com/satijalab/seurat/files/3541558/uwot.pdf)

**umap-learn Results:**
[umap-learn.pdf](https://github.com/satijalab/seurat/files/3541559/umap-learn.pdf)

**Comment by andrewwbutler** [comment]
Hi Sam,

For a comparison of `uwot` with the python implementation of umap, please see this part of the [uwot documentation](https://jlmelville.github.io/uwot/pycompare).  Based on this, it is expected that the two different implementations won't always agree but we can't really advise on which you "should use". We opted to move the default version to `uwot` as it seemed generally comparable in terms of results/runtime while also hopefully making installation a bit simpler (there were quite a number of issues from people trying to link their python packages with R). We did leave both options to maintain reproducibility for those wanting to regenerate old plots.
