### ISSUE TITLE
Harmony and Seurat - merging experiments 

### ISSUE THREAD

**Issue by fede86** [satijalab/seurat#2026]
Hi, thank you for your great tool - Seurat works very well for our experiments  with relatively high batch effect when normalizing first with harmony. We have two different experimental  conditions (treated and untreated) with 3 replicates each, we use Seurat  (v3.1) to merge those experiments. Do you have any suggestions/guidelines when (before or after batch-correction) and especially how to merge the experiments when using harmony and Seurat? Thank you in advance!

**Comment by andrewwbutler** [comment]
Hi,

Please see the following workflows for using Harmony with Seurat.

https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/harmony.html

https://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/docs/SeuratV3.html
