### ISSUE TITLE
Subsetting SCT transformed data

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat#2027]
Dear Seurat team,
I have a big dataset where I have been running SCT transformation and clustering.  After identifying cells subpopulations I did subset my initial object.
The question is, to further analyze each subset (for DGE) do I have to stick to SCT transformation of each subset or I could follow the "standard" :
FindVariableFeatures, Scale?
If I want to use this workflow do I have to switch from SCT to RNA assay? In case I have to switch to RNA assay first, do I need to NormalizeData as well?

I hope my questions are clear and I'm looking forward to any feedback.
Best
Roberta

**Comment by alexthiery** [comment]
I have the same question. Any clarification on this would be much appreciated!

**Comment by satijalab** [comment]
Apologies that we never responded. 

1. For DGE, we recommend using the RNA assay (normalized counts)
2. If you intend to sub-cluster your data, you can rerun SCTransform on RNA assay from the subsetted object
