### ISSUE TITLE
featureplot

### ISSUE THREAD

**Issue by benxiahu** [satijalab/seurat#2030]
I have downloaded a scRNA-seq matrix which has been clustered or named the cell types. Now I do not want to reanalyze this data, I just want to make the featureplot for several genes with seurat. I am not sure whether it is possible to do this one.
thanks in advance,
best,

**Comment by mojaveazure** [comment]
Yes, it’s possible

**Comment by benxiahu** [comment]
thanks for your reply.
scRNAseq<-read.table("singlecellexpression.txt",sep="\t",header=T)
rownames(scRNAseq)<-scRNAseq[,1]
scRNAseq<-scRNAseq[,-1]
sc<-CreateSeuratObject(counts=scRNAseq,project="scRNAseq")
 head(sc)
An object of class Seurat 
1 features across 3462 samples within 1 assay 
Active assay: RNA (1 features)
FeaturePlot(sc, features = 'GRIN2B',combine=FALSE,cols = c("lightgrey", "red"))
which produced this error:
Error in `[[.Seurat`(object, reduction) : 
  Cannot find 'NA' in this Seurat object
Do you know how to deal with it?
