### ISSUE TITLE
Umap shows different graphic when choosing between 2 or 3 components to embed.

### ISSUE THREAD

**Issue by tiagobrc** [satijalab/seurat#2031]
If I change the number of components in the RunUMAP function it gives a slightly different graphic, is that expected? The same does not occur with tsne.

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Yes, I believe that is expected. You can read the [UMAP docs](https://umap-learn.readthedocs.io/en/latest/parameters.html#n-components) for more discussion.
