### ISSUE TITLE
Different Integrate approaches different results

### ISSUE THREAD

**Issue by happar73** [satijalab/seurat#2034]
Andrew,

Thanks for your reply to post #2006 . We had a few follow-up questions.

We corrected the variable nfeatures and set it consistently at 2000 and it helped reduce the differences to some extent. However, even with this modification there are still significant gene list output differences when identifying differentially expressed genes between STIM and CTRL for each cluster, depending upon the approach we use for combining the 3 replicates each for STIM and CTRL and then comparing the 2 different conditions (STIM vs CTRL).

If we had to distinguish use cases at a 3000 ft level, I think you are saying it is preferable to **MERGE** replicates, but **INTEGRATION** can be used for replicates in cases where there is lots of noise in the system (noisy biology, more than one platform etc.) I surmise that a potential drawback of using **INTEGRATE** instead of **MERGE** on replicates is eliminating some more variable genes, leaving fewer to compare between conditions (when replicates are compared against each other). Is this correct?

We've now tried 3 different approaches to combining the 3 replicates for the 2 conditions, which all give different outputs:

Approach 1: **merge** the 3 replicates for each condition, normalizedata, findvariable features, and then **integrate** the 2 conditions
Approach 2: normalizedata, findvariable features for each replicate individually, then **integratedata** for the 3 replicates for each condition, then **integrate** the 2 conditions
Approach 3: normalizedata, findvariable features and specify 2 conditions separately for each of the 6 samples and **integrate** all 6 samples
In the attached excel file, we've showed the DE genes for the STIM vs CTRL comparison for the first 2 clusters (out of 20 clusters) for these 3 approaches. Tab 1 lists output from DE genes for approach 1, Tab 2 lists output from DE genes from approach 2, and Tab 3 lists output from approach 3. You can see that for # of significant genes, approach 3 > approach 1 > approach 2. Also, you'll see that the gene lists are pretty different for all 3 approaches. There is minimal overlap between 1 and 2 but not at all with approach 3.
We believe that approach 1 is preferrable based on your previous reply since there are minimal replicate-specific differences but were concerned by the differences in output for the 3 different approaches.
Are all 3 of these approaches reasonable or is one of these inherently compromised?

Many Thanks!
[3 approaches DE for first 2 clusters.xlsx](https://github.com/satijalab/seurat/files/3547621/3.approaches.DE.for.first.2.clusters.xlsx)

**Comment by timoast** [comment]
Sorry for the delay. To clear a few things up:

>  I surmise that a potential drawback of using INTEGRATE instead of MERGE on replicates is eliminating some more variable genes, leaving fewer to compare between conditions (when replicates are compared against each other). Is this correct?

Integrating rather than merging will not affect the number of genes that can be compared. In any case, we recommend always performing DE using the uncorrected (RNA) assay, as documented in the FAQ and in many issues.

> We've now tried 3 different approaches to combining the 3 replicates for the 2 conditions, which all give different outputs:

Are you comparing integrated data here? If so, we recommend using the uncorrected data. The differences in approach above should only change how you're grouping the cells, the underlying expression values that will be compared should always be the same as you need to use the RNA assay rather than the integrated assay
