### ISSUE TITLE
The output of DE across condition

### ISSUE THREAD

**Issue by happar73** [satijalab/seurat#2035]
Dear Seurat Team,

I'm using FindMarkers() in order to get DE of a cluster in 2 conditions ( "CTRL" vs "STIM") following the linkhttps://satijalab.org/seurat/v3.0/immune_alignment.html. I am sure I following the Vignettes, I don't know why the output for every cluster looks the same. Is it the right way or is there something wrong with the code? Really appreciate your help!

The code is:
```
DefaultAssay(skin.big) <- "RNA"
immune.big@meta.data$cluster_condition <- paste(immune.big@meta.data$seurat_clusters, immune.big@meta.data$stim, sep = "_")
Idents(immune.big) <- immune.big@meta.data$cluster_condition
head(Idents(immune.big))
immune.big.deg <- FindMarkers(immune.big, ident.1 = "0_CTRL", ident.2 = "0_STIM", verbose = FALSE)
write.csv(immune.big.deg, "E:/cluster 0.csv")
```
I checked the condition, it was right (9 clusters)
STIM1_AAACCTGAGCTGCCCA STIM1_AAACCTGAGTGCGATG STIM1_AAACCTGCAATGACCT STIM1_AAACCTGCATGGGACA 
                4_STIM                 0_STIM                 5_STIM                0_STIM
18 Levels: 4_STIM 0_STIM 5_STIM 1_STIM 2_STIM 3_STIM 7_STIM 8_STIM 6_STIM 0_CTRL 2_CTRL 1_CTRL 3_CTRL 4_CTRL ... 8_CTRL

The output of the first 2 clusters is here:
[DE across condition for first 2 clusters.xlsx](https://github.com/satijalab/seurat/files/3548747/DE.across.condition.for.first.2.clusters.xlsx)

Thanks a million!

**Comment by timoast** [comment]
Sorry for the delay here. The code looks ok, so I think it's likely the case here that there are some genes that are globally differentially expressed between the two conditions (DE in all cell types)
