### ISSUE TITLE
Unable to run MultiCCA in Seurat V3

### ISSUE THREAD

**Issue by genecell** [satijalab/seurat#2036]
Hi,

I previously ran `RunMultiCCA` in Seurat V2 in my project, but I found this function no longer supported in Seurat V3.
Could you please let me know if I could run MultiCCA in Seurat V3?
Thanks in advance!

Best regards,
BP

**Comment by swlx08** [comment]
Hi,

The RunMultiCCA() has been replaced by IntegrateData() in Seurat v3. Check https://satijalab.org/seurat/v3.0/immune_alignment.html
