### ISSUE TITLE
Lost preservation of custom meta data during integration

### ISSUE THREAD

**Issue by akhst7** [satijalab/seurat#2037]
During integration of multiple objects, manually added mata data gets lost.  Here is an example.  
I have one seruat object with following @meta.data;

[str(ft.sa@meta.data)
'data.frame':	14815 obs. of  7 variables:
 $ orig.ident  : Factor w/ 1 level "Saline": 1 1 1 1 1 1 1 1 1 1 ...
 $ nCount_RNA  : num  16133 2159 8295 2014 1430 ...
 $ nFeature_RNA: int  3869 828 2566 801 533 658 3330 2591 474 853 ...
 $ percent.mt  : num  8.93 46.73 8.02 40.71 50.28 ...
 $ nCount_SCT  : num  5564 4100 5679 3958 3563 ...
 $ nFeature_SCT: int  1932 914 2517 880 769 801 2278 2591 690 1020 ...
 $ type        : chr  "FT" "FT" "FT" "FT" ...](url)

A last column is added before integration but after integration, $type of the integrated object gets all NA as follows, 

str(all.int@meta.data)
'data.frame':	55979 obs. of  7 variables:
 $ orig.ident  : chr  "Alt+Pne" "Alt+Pne" "Alt+Pne" "Alt+Pne" ...
 $ nCount_RNA  : num  14491 2706 23109 4323 3241 ...
 $ nFeature_RNA: int  3896 1339 4041 1472 1666 1718 754 1139 269 1847 ...
 $ percent.mt  : num  6.64 17.26 5.01 40.48 20.33 ...
 $ nCount_SCT  : num  3951 3165 3935 4053 3374 ...
 $ nFeature_SCT: int  1697 1339 1240 1472 1666 1718 808 1139 389 1840 ...
 $ type        : chr  "NA" "NA" "NA" "NA" ...

I can manually fix this but it is pain in the butt.  Any fixes ?

Thanks.

**Comment by andrewwbutler** [comment]
Hi,

Can you post your sessionInfo?

**Comment by akhst7** [comment]
Sorry to post this late but here we go. 

> session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin18.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Indiana/Indianapolis
 date     2019-09-04                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version   date       lib source                        
 ape                    5.3       2019-03-17 [1] CRAN (R 3.6.0)                
 assertthat             0.2.1     2019-03-21 [1] CRAN (R 3.6.0)                
 backports              1.1.4     2019-04-10 [1] CRAN (R 3.6.0)                
 bibtex                 0.4.2     2017-06-30 [1] CRAN (R 3.6.0)                
 Biobase              * 2.45.0    2019-05-02 [1] Bioconductor                  
 BiocGenerics         * 0.31.5    2019-07-03 [1] Bioconductor                  
 BiocManager          * 1.30.4    2018-11-13 [1] CRAN (R 3.6.0)                
 BiocParallel         * 1.19.2    2019-08-11 [1] Bioconductor                  
 bitops                 1.0-6     2013-08-17 [1] CRAN (R 3.6.0)                
 callr                  3.3.1     2019-07-18 [1] CRAN (R 3.6.1)                
 caTools                1.17.1.2  2019-03-06 [1] CRAN (R 3.6.0)                
 cli                    1.1.0     2019-03-19 [1] CRAN (R 3.6.0)                
 cluster                2.1.0     2019-06-19 [2] CRAN (R 3.6.1)                
 codetools              0.2-16    2018-12-24 [2] CRAN (R 3.6.1)                
 colorspace             1.4-1     2019-03-18 [1] CRAN (R 3.6.0)                
 cowplot                1.0.0     2019-07-11 [1] CRAN (R 3.6.1)                
 crayon                 1.3.4     2017-09-16 [1] CRAN (R 3.6.0)                
 data.table           * 1.12.2    2019-04-07 [1] CRAN (R 3.6.0)                
 DelayedArray         * 0.11.4    2019-07-03 [1] Bioconductor                  
 desc                   1.2.0     2018-05-01 [1] CRAN (R 3.6.0)                
 devtools             * 2.1.0     2019-07-06 [1] CRAN (R 3.6.0)                
 digest                 0.6.20    2019-07-04 [1] CRAN (R 3.6.0)                
 dplyr                * 0.8.3     2019-07-04 [1] CRAN (R 3.6.0)                
 fitdistrplus           1.0-14    2019-01-23 [1] CRAN (R 3.6.0)                
 fs                     1.3.1     2019-05-06 [1] CRAN (R 3.6.0)                
 future                 1.14.0    2019-07-02 [1] CRAN (R 3.6.1)                
 future.apply           1.3.0     2019-06-18 [1] CRAN (R 3.6.0)                
 gbRd                   0.4-11    2012-10-01 [1] CRAN (R 3.6.0)                
 gdata                  2.18.0    2017-06-06 [1] CRAN (R 3.6.0)                
 GenomeInfoDb         * 1.21.1    2019-05-15 [1] Bioconductor                  
 GenomeInfoDbData       1.2.1     2019-05-14 [1] Bioconductor                  
 GenomicRanges        * 1.37.14   2019-06-24 [1] Bioconductor                  
 ggplot2              * 3.2.1     2019-08-10 [1] CRAN (R 3.6.1)                
 ggpubr                 0.2.2     2019-08-07 [1] CRAN (R 3.6.1)                
 ggrepel                0.8.1     2019-05-07 [1] CRAN (R 3.6.0)                
 ggridges               0.5.1     2018-09-27 [1] CRAN (R 3.6.0)                
 ggsignif               0.6.0     2019-08-08 [1] CRAN (R 3.6.1)                
 globals                0.12.4    2018-10-11 [1] CRAN (R 3.6.0)                
 glue                   1.3.1     2019-03-12 [1] CRAN (R 3.6.0)                
 gplots                 3.0.1.1   2019-01-27 [1] CRAN (R 3.6.0)                
 gridExtra              2.3       2017-09-09 [1] CRAN (R 3.6.0)                
 gtable                 0.3.0     2019-03-25 [1] CRAN (R 3.6.0)                
 gtools                 3.8.1     2018-06-26 [1] CRAN (R 3.6.0)                
 htmltools              0.3.6     2017-04-28 [1] CRAN (R 3.6.0)                
 htmlwidgets            1.3       2018-09-30 [1] CRAN (R 3.6.0)                
 httr                   1.4.1     2019-08-05 [1] CRAN (R 3.6.1)                
 ica                    1.0-2     2018-05-24 [1] CRAN (R 3.6.0)                
 igraph                 1.2.4.1   2019-04-22 [1] CRAN (R 3.6.0)                
 IRanges              * 2.19.14   2019-08-25 [1] Bioconductor                  
 irlba                  2.3.3     2019-02-05 [1] CRAN (R 3.6.0)                
 jsonlite               1.6       2018-12-07 [1] CRAN (R 3.6.0)                
 KernSmooth             2.23-15   2015-06-29 [2] CRAN (R 3.6.1)                
 labeling               0.3       2014-08-23 [1] CRAN (R 3.6.0)                
 lattice                0.20-38   2018-11-04 [2] CRAN (R 3.6.1)                
 lazyeval               0.2.2     2019-03-15 [1] CRAN (R 3.6.0)                
 leiden                 0.3.1     2019-07-23 [1] CRAN (R 3.6.1)                
 listenv                0.7.0     2018-01-21 [1] CRAN (R 3.6.0)                
 lmtest                 0.9-37    2019-04-30 [1] CRAN (R 3.6.0)                
 lsei                   1.2-0     2017-10-23 [1] CRAN (R 3.6.0)                
 magrittr               1.5       2014-11-22 [1] CRAN (R 3.6.0)                
 MASS                   7.3-51.4  2019-03-31 [2] CRAN (R 3.6.1)                
 Matrix                 1.2-17    2019-03-22 [2] CRAN (R 3.6.1)                
 matrixStats          * 0.54.0    2018-07-23 [1] CRAN (R 3.6.0)                
 memoise                1.1.0     2017-04-21 [1] CRAN (R 3.6.0)                
 metap                  1.1       2019-02-06 [1] CRAN (R 3.6.0)                
 munsell                0.5.0     2018-06-12 [1] CRAN (R 3.6.0)                
 nlme                   3.1-141   2019-08-01 [2] CRAN (R 3.6.1)                
 npsurv                 0.4-0     2017-10-14 [1] CRAN (R 3.6.0)                
 pbapply                1.4-1     2019-07-15 [1] CRAN (R 3.6.1)                
 pillar                 1.4.2     2019-06-29 [1] CRAN (R 3.6.0)                
 pkgbuild               1.0.5     2019-08-26 [1] CRAN (R 3.6.1)                
 pkgconfig              2.0.2     2018-08-16 [1] CRAN (R 3.6.0)                
 pkgload                1.0.2     2018-10-29 [1] CRAN (R 3.6.0)                
 plotly                 4.9.0     2019-04-10 [1] CRAN (R 3.6.0)                
 plyr                   1.8.4     2016-06-08 [1] CRAN (R 3.6.0)                
 png                    0.1-7     2013-12-03 [1] CRAN (R 3.6.0)                
 prettyunits            1.0.2     2015-07-13 [1] CRAN (R 3.6.0)                
 processx               3.4.1     2019-07-18 [1] CRAN (R 3.6.1)                
 ps                     1.3.0     2018-12-21 [1] CRAN (R 3.6.0)                
 purrr                  0.3.2     2019-03-15 [1] CRAN (R 3.6.0)                
 R.methodsS3            1.7.1     2016-02-16 [1] CRAN (R 3.6.0)                
 R.oo                   1.22.0    2018-04-22 [1] CRAN (R 3.6.0)                
 R.utils                2.9.0     2019-06-13 [1] CRAN (R 3.6.0)                
 R6                     2.4.0     2019-02-14 [1] CRAN (R 3.6.0)                
 RANN                   2.6.1     2019-06-13 [1] Github (jefferis/RANN@90d57e7)
 RColorBrewer           1.1-2     2014-12-07 [1] CRAN (R 3.6.0)                
 Rcpp                   1.0.2     2019-07-25 [1] CRAN (R 3.6.1)                
 RcppAnnoy              0.0.12    2019-05-12 [1] CRAN (R 3.6.0)                
 RcppParallel           4.4.3     2019-05-22 [1] CRAN (R 3.6.0)                
 RCurl                  1.95-4.12 2019-03-04 [1] CRAN (R 3.6.0)                
 Rdpack                 0.11-0    2019-04-14 [1] CRAN (R 3.6.0)                
 remotes                2.1.0     2019-06-24 [1] CRAN (R 3.6.0)                
 reshape2               1.4.3     2017-12-11 [1] CRAN (R 3.6.0)                
 reticulate             1.13      2019-07-24 [1] CRAN (R 3.6.1)                
 rlang                  0.4.0     2019-06-25 [1] CRAN (R 3.6.0)                
 ROCR                   1.0-7     2015-03-26 [1] CRAN (R 3.6.0)                
 rprojroot              1.3-2     2018-01-03 [1] CRAN (R 3.6.0)                
 rstudioapi             0.10      2019-03-19 [1] CRAN (R 3.6.0)                
 rsvd                   1.0.2     2019-07-29 [1] CRAN (R 3.6.1)                
 Rtsne                  0.15      2018-11-10 [1] CRAN (R 3.6.0)                
 S4Vectors            * 0.23.20   2019-08-26 [1] Bioconductor                  
 scales                 1.0.0     2018-08-09 [1] CRAN (R 3.6.0)                
 sctransform            0.2.0     2019-04-12 [1] CRAN (R 3.6.0)                
 SDMTools               1.1-221.1 2019-04-18 [1] CRAN (R 3.6.0)                
 sessioninfo            1.1.1     2018-11-05 [1] CRAN (R 3.6.0)                
 Seurat               * 3.1.0     2019-08-20 [1] CRAN (R 3.6.1)                
 SingleCellExperiment * 1.7.7     2019-08-26 [1] Bioconductor                  
 statmod              * 1.4.32    2019-05-29 [1] CRAN (R 3.6.0)                
 stringi                1.4.3     2019-03-12 [1] CRAN (R 3.6.0)                
 stringr                1.4.0     2019-02-10 [1] CRAN (R 3.6.0)                
 SummarizedExperiment * 1.15.8    2019-08-25 [1] Bioconductor                  
 survival               2.44-1.1  2019-04-01 [2] CRAN (R 3.6.1)                
 testthat               2.2.1     2019-07-25 [1] CRAN (R 3.6.1)                
 tibble                 2.1.3     2019-06-06 [1] CRAN (R 3.6.0)                
 tidyr                  0.8.3     2019-03-01 [1] CRAN (R 3.6.0)                
 tidyselect             0.2.5     2018-10-11 [1] CRAN (R 3.6.0)                
 tsne                   0.1-3     2016-07-15 [1] CRAN (R 3.6.0)                
 usethis              * 1.5.1     2019-07-04 [1] CRAN (R 3.6.0)                
 uwot                   0.1.3     2019-04-07 [1] CRAN (R 3.6.0)                
 viridisLite            0.3.0     2018-02-01 [1] CRAN (R 3.6.0)                
 withr                  2.1.2     2018-03-15 [1] CRAN (R 3.6.0)                
 XVector                0.25.0    2019-05-02 [1] Bioconductor                  
 zlibbioc               1.31.0    2019-05-02 [1] Bioconductor                  
 zoo                    1.8-6     2019-05-28 [1] CRAN (R 3.6.0)                

[1] /Users/ahoji/Documents/R_lib
[2] /usr/local/Cellar/r/3.6.1_1/lib/R/library

**Comment by timoast** [comment]
Is `type` present in both objects that you integrate? Could you also run `table(all.int$type)`?
