### ISSUE TITLE
Which assay to use?

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [satijalab/seurat#2039]
Hi,
i'm using Seurat v3 and I create a Seurat object of all cells except the 2 clusters using **subset** function.
After that step i'd re-cluster the cell as you suggest using #re-running **FindVariableFeatures()** and **ScaleData()**# but i don't understand at this point which assay use? "RNA" assay for both FindVariableFeatures() and ScaleData() or "RNA" for FindVariableFeatures() and  "integrated" for
ScaleData()?
I hope I was clear.

thanks for you time,
kind regards.

**Comment by DomenicoSkyWalker89** [comment]
![Capture22](https://user-images.githubusercontent.com/53559811/65710264-f57d7e00-e092-11e9-9a5b-c194f7d90cdf.PNG)

**Comment by mojaveazure** [comment]
Sorry for the late response; please see https://github.com/satijalab/seurat/issues/1717#issuecomment-504458665 for information about when to use the integrated assay and when to use the RNA assay.
