### ISSUE TITLE
BuildClusterTree

### ISSUE THREAD

**Issue by Gorman222** [satijalab/seurat#204]
Hello, I am having an issue with the BuildClusterTree function where I am getting this error:

obj <- BuildClusterTree(obj, do.reorder = TRUE, reorder.numeric = TRUE, pcs.use = PC.toUse)
[1] "Finished averaging RNA for cluster 0"
[1] "Finished averaging RNA for cluster 1"
[1] "Finished averaging RNA for cluster 2"
[1] "Finished averaging RNA for cluster 3"
[1] "Finished averaging RNA for cluster 4"
[1] "Finished averaging RNA for cluster 5"
[1] "Finished averaging RNA for cluster 6"
[1] "Finished averaging RNA for cluster 7"
[1] "Finished averaging RNA for cluster 8"
[1] "Finished averaging RNA for cluster 9"
[1] "Finished averaging RNA for cluster 10"
Error in BuildClusterTree(obj, do.reorder = TRUE, reorder.numeric = TRUE,  : 
  no slot of name "pca.obj" for this object of class "seurat"
In addition: There were 11 warnings (use warnings() to see them)

I see that the function is looking for a slot object@pca.obj:

if (!is.null(x = pcs.use)) {
        data.pca <- AveragePCA(object = object)
        data.use <- data.pca[pcs.use, ]
        if (is.null(x = object@pca.obj[[1]]$sdev)) {
            data.eigenval <- (object@pca.obj[[1]]$d)^2
        }
        else {
            data.eigenval <- (object@pca.obj[[1]]$sdev)^2
        }

But in the RunPCA function, it looks as though the slot is created and then renamed object@dr$pca:

pca.obj <- new(Class = "dim.reduction", gene.loadings = gene.loadings, 
        cell.embeddings = cell.embeddings, sdev = sdev, key = reduction.key)
    eval(expr = parse(text = paste0("object@dr$", reduction.name, 
        "<- pca.obj")))

Can anyone tell me if this is an error on my part or an error within Seurat?
Thank you for your help.

**Comment by mschilli87** [comment]
@Gorman222: How did you resolve this issue?

**Comment by Gorman222** [comment]
I removed the pcs.use argument and it worked fine.
I think it doesn't look for the pca.obj slot if you don't specify pcs.use.
