### ISSUE TITLE
Differential expressed comparing several clusters in one group versus a few clusters in another group.

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#2041]
Hi, 

I have 13 clusters identified in Seurat V3.
Out of these 13 clusters, I wanted to compare some that are part of a particular lineage. 

I tried this: 
diff.markers <- FindMarkers(scex, ident.1 = "cluster1", "cluster2", "cluster3",  "cluster4", "cluster5", ident.2 = "cluster6", "cluster7", only.pos = FALSE)

I am trying to compare genes up in clusters1-5 versus those in cluster 6+7. 

I tried to look around the threads in Github, I couldnt find what I was looking for. 
I am writing here as a last resort. 
I guess if I converted clusters1-5 and clusters6+7 to something like CTRL and STIM, respectively, it could work. As I would have similar analysis as to what I am trying to come, I guess its best to ask here. 

Many thanks for any suggestions.

**Comment by psavas** [comment]
Yes, you can rename the clusters to represent the groups that you want and then use `FindMarkers`. Nothing wrong with that.

**Comment by yuhanH** [comment]
Agree with psavas. You could rename the clusters for the differential analysis.
