### ISSUE TITLE
You can change the set of features to be integrated by using the `features.to.integrate` argument in `IntegrateData`. By default, this is set to the `VariableFeatures`, which is why you find 2000 rows in the integrated assay. I would not recommend repeating the integration on a subset of the cells, using the integrated assay computed on the full dataset should be sufficient for subclustering.

### ISSUE THREAD

**Issue by gilstel** [satijalab/seurat#2042]
Dear Tim 

I am using Seurat 3.
I have an integrated object.  I obtained a subset of cells from the integrated object and wish to recluster the subset.
When I did this with Seurat 2 I used do.clear.  Since this is depracated in Seurat 3 I tried using the DietSeurat function to clear all the information from the object prior to FindVariableFeatures 
DietSeurat(object = neuron.reclust.list[[i]], counts = TRUE, data = TRUE, scale.data = FALSE)
but recieved the following error - 
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  no 'dimnames[[.]]': cannot use character indexing

I confused as to how to proceed.

From what I read in various posts this would need to be followed by ScaleData, RunPCA, FindNeighbors and finally FindClusters.

If I run ScaleData with the current 2000 features that are marked as variable features without finding new ones. 
ScaleData(object = neuron.reclust.list[[i]], block.size = 4000)
I recieve the following warning -
Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 3 features requested have zero variance (running reduction without them): F13a1, Cd209f, F630028O10Rik

ALTERNATIVE #1

When I try to do find variable features with the DefaultAssay (which is "integrated" at the moment) 
FindVariableFeatures(object = neuron.reclust.list[[i]])
I recieve several warnings - 
Warning messages:
1: In FindVariableFeatures.Assay(object = assay.data, selection.method = selection.method,  :
  selection.method set to 'vst' but count slot is empty; will use data slot instead
2: In eval(predvars, data, env) : NaNs produced
3: In hvf.info$variance.expected[not.const] <- 10^fit$fitted :
  number of items to replace is not a multiple of replacement length

1997 variable features were found

ALTERNATIVE #2

Switch DefaultAssay to "RNA" and then find variable features.  2000 features were found (since the default param was not changed in FindVariableFeatures) that are different from those that were stored as variable features during the original integration process.
I then used ScaleData.  This was followed JackStraw and ScoreJackStraw which were fine.  

JackStraw(object = neuron.reclust.list[[i]], num.replicate = 100)
ScoreJackStraw(object = neuron.reclust.list[[i]], dims = 1:20)

When I subsequently used JackStrawPlot 
JackStrawPlot(object = neuron.reclust.list[i], dims = 1:20)
I received the following error - 
Error in UseMethod(generic = "JS", object = object) : 
  no applicable method for 'JS' applied to an object of class "NULL"

Neveretheless, I continued to use FindNeighbors and FindClusters with 20 PC's (using DimHeatmap)

If I use alternative #2, how is the integration information used at all, since I used the RNA assay throughout the reclustering?

Many thanks,
Gil

You can change the set of features to be integrated by using the `features.to.integrate` argument in `IntegrateData`. By default, this is set to the `VariableFeatures`, which is why you find 2000 rows in the integrated assay. I would not recommend repeating the integration on a subset of the cells, using the integrated assay computed on the full dataset should be sufficient for subclustering.

_Originally posted by @timoast in https://github.com/satijalab/seurat/issues/1547#issuecomment-495681165_

**Comment by timoast** [comment]
Hi, sorry we never replied here. Basically you should not be using the integrated assay to find variable features, the integration vignettes show how to run this type of analysis: https://satijalab.org/seurat/v3.2/integration.html
