### ISSUE TITLE
PBMC scATAC-seq Vignette: Issue using gene activity matrix in CreateAssayObject

### ISSUE THREAD

**Issue by rlevantovsky** [satijalab/seurat#2043]
Hi there,

I am following the scATAC-seq integration vignette and running into trouble when at the CreateAssayObject step.

I was unable to run activity.matrix <- CreateGeneActivityMatrix on my own mac because I don't have the memory capacity, so I did it on a super computer and saved the output as a csv file.

When I try to do the next step, atac[["ACTIVITY"]] <- CreateAssayObject(counts = activity.matrix), I am getting the following error:

Error: Cannot add a different number of cells than already present
In addition: Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion

I don't know how to interpret this.

Afterwards, I am able to apply SCtransform, LSI, and UMAP on the atac data, but when I get to FindTransferAnchors I get the following error:

Error in `DefaultAssay<-.Seurat`(object = `*tmp*`, value = query.assay) : 
  Cannot find assay ACTIVITY

Do you have any advice about how to successfully get an activity matrix? Should I save it as something other than a csv? I assume the trouble with CreateAssayObject begins there.

Thanks!

**Comment by mojaveazure** [comment]
The first error message states:
> Error: Cannot add a different number of cells than already present

All assays within a `Seurat` object must have the same number of cells. When creating your assay, I would suggest subsetting the matrix to the cells present in your object

```R
atac[['ACTIVITY']] <- CreateAssayObject(counts = activity.matrix[, colnames(atac)])
```

For the second error message, since the ACTIVITY assay was never added, you cannot set the default assay to ACTIVITY.
