### ISSUE TITLE
Could not find function "PercentageFeatureSet" V3.1

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#2045]
Dear All,
I just installed SEURAT V3.1
The function "PercentageFeatureSet" is not working, is that because it is still very new?
Should I go back to v3.0? IF so, how do I do that?
Thank you so much

**Comment by EDYAC** [comment]
I did this to go back to V3.0.0
devtools::install_version(package = 'Seurat', version = package_version('3.0.0'))
And now it's working

**Comment by timoast** [comment]
Hi, `PercentageFeatureSet` is in Seurat v3.1. See here for relevant lines: https://github.com/satijalab/seurat/blob/master/R/utilities.R#L894

Try installing the package from CRAN and restarting R
