### ISSUE TITLE
ReadH5AD failed to load embedding from h5ad file

### ISSUE THREAD

**Issue by screamer** [satijalab/seurat#2047]
I created a h5ad file using anndata.write(), which can be download at https://www.dropbox.com/s/d3icxel0kto42s5/scxx_output_embedding.h5ad?dl=0

However, ReadH5AD failed to load it in R. It works when I removed embedding in anndata.obsm.

The error output is as follows:
Pulling expression matrices and metadata
Data is scaled
Merging feature-level metadata dataframes
Creating assay object
Storing X as scale.data and raw as data
No variable feature expression found in h5ad file
Pulling dimensional reduction information
Pulling cell embeddings
Error in file[["obsm"]]$get_type() : attempt to apply non-function

Thanks in advance!

**Comment by mojaveazure** [comment]
Sorry for the delay in response. This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
