### ISSUE TITLE
Scaledata() scales/centers each row instead of column?

### ISSUE THREAD

**Issue by jliu678** [satijalab/seurat#2048]
hi,

**I don't understand why core function of Scaledata() is "Eigen::MatrixXd FastRowScale" equivalent to using t(scale(t(mat))) in R, which scales and centers matrix on each row instead of columns**

According to your 2019 cell paper as well as previous papers on integrating muti-scRNAseq datasets, the CCA requires column variance to be 1.

**Also, is there scaling/centering process before the new_residual is put into Scaled.data?** I understand that when original Scaled.data doesn't contain necessary Pearson residual, PrepSCTIntegration() will add the needed new_residual, but I only see the below line to center it without scaling.

`new_residual <- new_residual - rowMeans(new_residual)`

thanks, and looking forward to expertise

I also post in https://github.com/ChristophH/sctransform/issues/40, since Scaledata() now is wrapped by SCtransform()

**Comment by jliu678** [comment]
![image](https://user-images.githubusercontent.com/53794392/64276387-d701e800-cf15-11e9-9f5c-d36ba162fa07.png)

The above is cropped from DOI:10.1038/nbt.4096 your _Nature Biotechnology_ paper. It clearly shows CCA requires column variance to be 1.

Looking forward to your reply soon.

best

**Comment by satijalab** [comment]
Apologies for the slow reply (I feel like I have responded to this same question in another forum or issue?).

You are correct that ScaleData does not scale columns, but scales rows (it is meant to mirror the scale=TRUE argument in prcomp).

For CCA we do require column variance to be 1, but this is actually taken care of in the RunCCA function itself (using the Standardize function).

Finally, for SCTransform - that is correct, when row-scaling: we only center the Pearson residuals, we do not scale them.  For column-scaling (as in CCA), we would still perform this step (as before, using the Standardize function in RunCCA).

**Comment by jliu678** [comment]
thank you
