### ISSUE TITLE
How to extaxct normalized expression matrix from seurat object?

### ISSUE THREAD

**Issue by CSBioAzim** [satijalab/seurat#2049]
Hi,

I want to extract expression matrix in different stages (after removing constant features, removing the cell cycle effect, etc.) from Seurat object. 
Is there any command to do it easily?

**Comment by j-andrews7** [comment]
Their [cheat sheet](https://satijalab.org/seurat/essential_commands.html) shows how to access any of the data you'd need. Probably the `data` slot, maybe from the `SCT` assay if you're using `SCTransform`, for your case.

**Comment by yuhanH** [comment]
Thanks Jared.
You could use either data slot, or scale.data slot after SCTransform. 
The scale.data slot contains the pearson residuals of variable genes, which is also corrected for the confounding effects you put.

**Comment by dhkwnr97** [comment]
https://www.biostars.org/p/420841/

**Comment by ahdee** [comment]
@yuhanH thanks for info; 

I'm a bit confused would this then be the normalized count we can use? What what is the unit is it TPM? 

`df= pbmc[["SCT"]]@scale.data`

in other words when I plot say GAPDH data extracted from the above df, what would be the units?
