### ISSUE TITLE
marker p-values returned as 0

### ISSUE THREAD

**Issue by bioryguy** [satijalab/seurat#205]
I'm not sure if this is an issue or not. I've run a clustering analysis following the pbmc3k tutorial on my own data and the results that have come back seem to match our expectations however when I use the FindMarkers function some of the markers are returned with a 0 p-value. The other reported p-values are also very low (e.g. 9.4E-288) and the p-values reported as 0 seem to be more differentially expressed than even those. I'm inclined to think that Seurat is outputting 0 p-values because they are so low as to be effectively 0. However, I don't want to blindly assume that. Is there some mistake that I may have made to cause this? Thanks for the help and let me know if you need any more details.
[example.xlsx](https://github.com/satijalab/seurat/files/1447146/example.xlsx)

**Comment by andrewwbutler** [comment]
Yes, it's possible that for large datasets with strong markers that you would see some p-values of 0. It's not so much a Seurat specific feature, rather the smallest number that R can represent is 2.225074e-308 (you can check this with `.Machine$double.xmin`). So any values less than that are just treated as 0.

**Comment by bioryguy** [comment]
Ok great thanks, that is excellent information to know!

**Comment by Arshammik** [comment]
Can we Split the count matrix as test/train using tools like [This](https://pubmed.ncbi.nlm.nih.gov/36511385/) and use the test count matrix to get the markers with higher amount of p-value?
