### ISSUE TITLE
SCT Integrated Workflow Help 

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#2050]
Hello!

Thank you for releasing the SCT/integration work flow! I had three questions about the workflow listed below.

I followed your tutorial and then used this post to help guide my FindAllMarkers and DEG analysis: https://github.com/satijalab/seurat/issues/1836
Workflow:
1. Create Seurat object
2. QC by filtering out cells based on percent.mito and nFeature_RNA
(I added the cell cycle scoring during this step)
3. SCT normalize each dataset specifying the parameter vars.to.regress = percent.mito
(I added the cell cycle regression during this step, CC.difference)
4. Integrate all datasets
5. Run PCA, UMAP, FindClusters, FindNeighbors (on default assay which is "integrated")
6. Change default assay to "RNA"; normalize then generate FeaturePlots and perform differential expression analysis

Questions: 

1. Same question as here, but with SCT: https://github.com/satijalab/seurat/issues/1778
I'm do the cell cycle regression, I performed this during the initial SCT normalization along with percent.mito. Is this correct? 

2. I'm having a similar problem as I had here: https://github.com/satijalab/seurat/issues/1874
I'd like to generate a heatmap of my integrated SCT data, but DoHeatmap uses the RNA slot. Is there a way to use a different slot, or do I need to scale in this workflow? 
`all.genes <- rownames(x = vitDcca) vitDcca <- ScaleData(object = vitDcca, features = all.genes) vitDcca.markers %>% group_by(cluster) %>% top_n(n = 12, wt = avg_logFC) -> top10 DoHeatmap(subset(vitDcca, downsample = 100), features = top10$gene, size = 3)`

3. Same question as here, but with SCT: https://github.com/satijalab/seurat/issues/1242
I tried 
`table(vitD.integrated$orig.ident, vitD.integrated$SCT_snn_res.0.4)` 
but got 

> Error in `[[.Seurat`(x, i, drop = TRUE) : 
>   Cannot find 'SCT_snn_res.0.4' in this Seurat object

Thanks so much for all of your help!

**Comment by satijalab** [comment]
Apologies for the slow response:

1. Addressed in #1778. Your workflow is valid.

2. You can set both the assay and the slot in DoHeatmap, both are parameters. So you can do a heatmap of Pearson residuals by setting the assay to SCT and the slot to scale.data

3. This must be because you have not run a clustering with res=0.4 on the object. You can run colnames(vitD.integrated@meta.data) to see what resolutions have been run, and what column names are valid
