### ISSUE TITLE
why does it have to use the “RNA” OR

### ISSUE THREAD

**Issue by a582213088** [satijalab/seurat#2052]

**Comment by a582213088** [comment]
Hi Seurat team，
Thank you for the useful tool for our data-analysis.
I have a question about the function "FindMarkers".In the website ,you said that

> We recommend running your differential expression tests on the “unintegrated” data. By default >this is stored in the “RNA” Assay. There are several reasons for this.

>1. The integration procedure inherently introduces dependencies between data points. This violates >the assumptions of the statistical tests used for differential expression.

>2.DE and integration are not currently supported with sctransform but will be soon.
I am confused about why it has to use the “RNA”  or “SCT" assay for differential expression analysis.
Will the data which has the batch effect in "RNA" assay  influence the results of DE ? If so ,what is the aim we run the integrating workfolw?
Thank you !

**Comment by timoast** [comment]
One goal of running the integration is to identify common cell states across experiments. See the paper for a more detailed explanation of the motivations (https://doi.org/10.1016/j.cell.2019.05.031).

To account for technical differences between batches when finding differentially expressed genes, you can include batch as a latent variable in the differential expression test. For example:

```r
markers <- FindMarkers(object, ident.1, ident.2, test.use = "LR", latent.vars = "batch")
```
