### ISSUE TITLE
Integrating small Dataset with large one : Error in nn2 [...] Cannot find more nearest neighbours than there are points when running IntegrateData()

### ISSUE THREAD

**Issue by ccp77** [satijalab/seurat#2056]
Hi, 

I'm writing because I'm trying to integrate 7 datasets using the standard Seurat V3 workflow, and I'm facing limitations probably because of the number of cells present in some of the dataset (Dataset1 = 80 cells; Dataset2 = 90 cells; all the other ones > 2000 cells). I'm able to integrate all 7 datasets together with a k filter of 70, but I don't know if the results make sense. Indeed, when I try to integrate Dataset1 with any of the large ones only, I get the following error:
> bone_marrow.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30, k.filter = 70) 
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 14s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 373 anchors
Filtering anchors
	Retained 275 anchors
Extracting within-dataset neighbors
  |+++++++++++++++++                                 | 33% ~10s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 420 anchors
Filtering anchors
	Retained 24 anchors
Extracting within-dataset neighbors
  |++++++++++++++++++++++++++++++++++                | 67% ~11s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 480 anchors
Filtering anchors
	Retained 15 anchors
Extracting within-dataset neighbors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 40s
bone_marrow.integrated <- IntegrateData(anchorset = bone_marrow.anchors, dims = 1:30)
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 2 1 into 3
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
**Error in nn2(data = data.use[anchors.cells2, ], query = data.use, k = k +  : 
  Cannot find more nearest neighbours than there are points**

I would like to know why I don't get an error when running the integration on all the Datasets together, while there doesn't seem to be enough anchors between Dataset1 and any of the other ones when run individually. This will be important for me to know wether the integration with all the Datasets together makes sense.

Thank you very much for your help!

**Comment by timoast** [comment]
Hi, the integration method does require a minimum number of cells per dataset, as it works by weighting information across cells. You could try adjusting the `k.filter` and `k.weight` parameters to try to get better results. See these previous issues for more suggestions: #997 #1381

**Comment by mbuttner** [comment]
Hi,
I have run into this error as well. I want to integrate 6 different datasets, the smallest with ~ 600 cells, the largest with ~ 8k cells. `k.filter` is set to 200. When I try to run Seurat v3 using all the genes (no selection of highly variable genes), Seurat works without errors, but as soon as I select 2000 custom genes (which should be highly variable in at least one dataset; selection performed via scripts from @LuckyMD), I have this error message: 
```
rpy2.rinterface_lib.embedded.RRuntimeError: Error in nn2(data = data.use[anchors.cells2, ], query = data.use, k = k +  : 
  Cannot find more nearest neighbours than there are points
``` 
I work on a Fedora25 Linux machine, with Python3.7 and R 3.5.1

Any feedback, comments, help is highly appreciated.

**Comment by liekevandehaar** [comment]
@timoast what would you say is the lowest number of cells per dataset for which the integration still works (given that you set `k.filter` and `k.weight` correctly)

**Comment by stefanonard85** [comment]
I follow @liekevandehaar question

**Comment by timoast** [comment]
Closing this now as I think the original question was answered. In general, methods that use k-nearest neighbors assume k is much smaller than the total number of cells. See also https://github.com/satijalab/seurat/issues/3207#issuecomment-651862274
