### ISSUE TITLE
How to find EGFP positive cell clusters

### ISSUE THREAD

**Issue by sygongcode** [satijalab/seurat#2057]
Hello, all, 
I have a very sample question. How can I find out the EGFP positive cell clusters in my project? Because EGFP is not an in vivo gene. I tried to use EGFP as a feature to do the plot. But, I got that the expression is very low. Actually, there are many cells express EGFP in my sample. So, could anyone help me? I will be very appreciated if someone shares his/her code. Thank you.
Yours sincerely,
Shangyu

**Comment by samuel-marsh** [comment]
Hi Shangyu,

Not a member of the dev team but hope this can help.  Did you add the eGFP construct sequence from your experiment to your genome before aligning your raw sequencing files to genome?

If not then you won't be able to detect eGFP in Seurat or any software really.  If not it's also not really Seurat question and there are other bioinformatics forum's better suited to helping you with the process of adding eGFP to your reference genome.

Best,
Sam

**Comment by sygongcode** [comment]
> Hi Shangyu,
> 
> Not a member of the dev team but hope this can help. Did you add the eGFP construct sequence from your experiment to your genome before aligning your raw sequencing files to genome?
> 
> If not then you won't be able to detect eGFP in Seurat or any software really. If not it's also not really Seurat question and there are other bioinformatics forum's better suited to helping you with the process of adding eGFP to your reference genome.
> 
> Best,
> Sam

Hi, Sam,
Thank you for your reply. We did add the eGFP construct sequence from your experiment to our genome. I don't know what is wrong. Thank you.
Best,
Shangyu

**Comment by diazdc** [comment]
Did you also add the GFP data to your annotation file? If not, you won't see the results in the count matrix because there won't be a row to quantify the counts. Here's an example from what I did in zebrafish to map GFP counts:

In your genome.fa file (note, "EGFP" is treated as its own chromosome):

    >EGFP
    ATGGTGAGCAAG...

In your annotation (gtf):

    EGFP	ensembl	exon	1	717	.	+	.	gene_id "EGFP"; gene_version "1"; 
    transcript_id "EGFP"; transcript_version "1"; gene_name "EGFP"; gene_source "ensembl"; 
    gene_biotype "EGFP"; transcript_name "EGFP"; transcript_source "ensembl"; transcript_biotype 
    "EGFP"; exon_number "1"; exon_id "EGFP"; exon_version "1"; tss_id "EGFP";

**Comment by sygongcode** [comment]
> Did you also add the GFP data to your annotation file? If not, you won't see the results in the count matrix because there won't be a row to quantify the counts. Here's an example from what I did in zebrafish to map GFP counts:
> 
> In your genome.fa file (note, "EGFP" is treated as its own chromosome):
> 
> ```
> >EGFP
> ATGGTGAGCAAG...
> ```
> 
> In your annotation (gtf):
> 
> ```
> EGFP	ensembl	exon	1	717	.	+	.	gene_id "EGFP"; gene_version "1"; 
> transcript_id "EGFP"; transcript_version "1"; gene_name "EGFP"; gene_source "ensembl"; 
> gene_biotype "EGFP"; transcript_name "EGFP"; transcript_source "ensembl"; transcript_biotype 
> "EGFP"; exon_number "1"; exon_id "EGFP"; exon_version "1"; tss_id "EGFP";
> ```

Hi,
Thank you so much for help and sharing. I will check it.

**Comment by andrewwbutler** [comment]
Closing as this seems to be an issue upstream of Seurat processing.
