### ISSUE TITLE
Why I got different cluster distribution plots by using two methods?How can I clearly plot these clusters separately in order to make sure their distribution?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#2058]
Hello,
I want to see clearly the distribution of my cluster,because I find some clusters are scattered, and I cant't make sure its location.
First,I use the cells.highlight parameter to see it,but I find many clusters are not separated .This distribution is really weird and disagree with the result split.by clusters(I think this one is right),but i couldn't find the reason.Is this because that some clusters have large cell numbers and highlighted cells overlapped nonhighlighted cells?
By using split.by parameter, i could't see the overall structure.So how can I clearly plot these clusters separately in order to make sure their distribution?
`DimPlot(Merge.integrated ,cols = "lightgrey", pt.size = 0.1,cells.highlight = WhichCells(Merge.integrated,cells= grep("clusternumber", Merge.integrated@meta.data$integrated_snn_res.0.7)),cols.highlight="blue",reduction="tsne" )`

`DimPlot(Merge.integrated,pt.size = 1,label=TRUE, label.size = 5,reduction = "umap",split.by = "integrated_snn_res.0.7",ncol = 8)`
![image](https://user-images.githubusercontent.com/30619010/64189836-aa16ec00-cea7-11e9-977f-bb217f0831fc.png)
![image](https://user-images.githubusercontent.com/30619010/64189685-602e0600-cea7-11e9-8a2c-56cd48afbf80.png)
![image](https://user-images.githubusercontent.com/30619010/64189016-14c72800-cea6-11e9-9b2e-9e011a852821.png)

**Comment by timoast** [comment]
I think what happened here is that when you use `grep` to find cells for each cluster, you are matching multiple clusters. Searching for "0" will match both "0" and "10", which looks consistent with the featureplots you showed

**Comment by Sophia409** [comment]
You are so clever!Thank you so much! @timoast
