### ISSUE TITLE
Error when doing FindIntegrationAnchors

### ISSUE THREAD

**Issue by Thegreatjoyce** [satijalab/seurat#2062]
Hi Seurat Team, 
I recently encountered an issue related with FindIntegrationAnchors. 
######################################################################
object.list <- list(PurkinjeCell, P0, P8a, P8b, P0A, P0B, P4A, P4B, P7A, P7B, P10A, P10B)

for (i in 1:length(object.list)) {
  object.list[[i]] <- SCTransform(object.list[[i]], vars.to.regress = c("nCount_RNA", "percent.mito"), verbose = FALSE, return.only.var.genes = FALSE)
}

GenesToIntegrate <- Reduce(intersect, lapply(object.list, rownames))
Integrate.anchors <- FindIntegrationAnchors(object.list, dims = 1:20)
Computing 2000 integration features
Scaling features for provided objects
   |                                                  | 0 % ~calculating  Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “numeric” is not valid for slot ‘scale.data’ in an object of class “Assay”; is(value, "matrix") is not TRUE

I can do FindIntegrationAnchors without "PurkinjeCell" object, but I don't find why it does not work when include this object.

**Comment by andrewwbutler** [comment]
Hi,

Are you able to successfully run `SCTransform` on the "PurkinjeCell" object? What does the resulting output (`GetAssayData(PurkinjeCell, assay = "SCT", slot = "scale.data")`) look like?

**Comment by Thegreatjoyce** [comment]
> Hi,
> 
> Are you able to successfully run `SCTransform` on the "PurkinjeCell" object? What does the resulting output (`GetAssayData(PurkinjeCell, assay = "SCT", slot = "scale.data")`) look like?

I solved the problem, it's because the gene name convention of 'PurkinjeCell' is different from the other objects. After rename the genes with same format, it can be solved.
