### ISSUE TITLE
`long vectors not supported yet` IntegrateData SCT 74k cells

### ISSUE THREAD

**Issue by mxposed** [satijalab/seurat#2063]
Hello,

I'm trying to integrate 18 datasets with 74k cells in total, using SCT normalization, but I get this error:
```
Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519
Calls: IntegrateData ... validObject -> anyStrings -> isTRUE -> validityMethod
17: validityMethod(as(object, superClass))
16: isTRUE(x)
15: anyStrings(validityMethod(as(object, superClass)))
14: validObject(.Object)
13: .nextMethod(.Object = .Object, ... = ...)
12: callNextMethod()
11: initialize(value, ...)
10: initialize(value, ...)
9: new("dgTMatrix", Dim = d, Dimnames = dn, i = i, j = j, x = x)
8: newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[, 2]),
       x = if (Generic == "+") c(e1@x, e2@x) else c(e1@x, -e2@x))
7: .Arith.Csparse(e1, e2, .Generic, class. = "dgCMatrix")
6: data.use2 - data.use1
5: data.use2 - data.use1
4: FindIntegrationMatrix(object = merged.obj, integration.name = integration.name,
       features.integrate = features.to.integrate, verbose = verbose)
3: RunIntegration(filtered.anchors = filtered.anchors, normalization.method = normalization.method,
       reference = object.1, query = object.2, cellnames.list = cellnames.list,
       new.assay.name = new.assay.name, features.to.integrate = features.to.integrate,
       features = features, dims = dims, weight.reduction = weight.reduction,
       do.cpp = do.cpp, k.weight = k.weight, sd.weight = sd.weight,
       eps = eps, verbose = verbose)
2: PairwiseIntegrateReference(anchorset = anchorset, new.assay.name = new.assay.name,
       normalization.method = normalization.method, features = features,
       features.to.integrate = features.to.integrate, dims = dims,
       k.weight = k.weight, weight.reduction = weight.reduction,
       sd.weight = sd.weight, sample.tree = sample.tree, preserve.order = preserve.order,
       do.cpp = do.cpp, eps = eps, verbose = verbose)
1: IntegrateData(anchorset = anchors, normalization.method = "SCT",
       dims = 1:40, verbose = FALSE)
```

From what I've read in other issues, I think that this error usually happens with a larger number of cells.

In relation to this issue, I wonder:
1. What would be the difference between the integration above and integrating in pairs, and then integrating integrated objects and so on?
2. What would be the difference between the integration above and integrating onto one of the selected datasets as reference? Does it matter which dataset is selected as reference?

Thank you.
PS. I use Seurat v 3.1.0

**Comment by polojacky** [comment]
I think it is due to a large number of datasets was integrated. I met the same issue when integrating many samples with heterogeneous cells in each sample. You can try the reference-based method. According to the vignette (https://satijalab.org/seurat/v3.1/integration.html), "In this example, we use the 10X v3 dataset, as the dataset contains both high cell number and high sensitivity. Users can apply similar criteria when selecting a reference. Furthermore, you can change this setting in the workflow below (for example, try selecting the 10X v2, or Drop-seq datasets as a reference), with only very minor differences in the final result."
And as for me, I chose the dataset with the largest cell number as the reference.

**Comment by Santos22903** [comment]
Well, I have exactly the same problem:

Integrating data
Merging dataset 11 22 16 20 9 into 1 2 3 14 21 6 26
Extracting anchors for merged samples
Finding integration vectors
Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:522
Calls: sctransFn ... validObject -> anyStrings -> isTRUE -> validityMethod
In addition: There were 14 warnings (use warnings() to see them)
Execution halted

I guess, no use opening a new issue, this one has been open since Sep 3. Does anybody know if SCTransform without reference (October 18 comment) cannot handle large number of cells in principle, or there can be a way. By the way, I have 28 samples and ~270K cells.

**Comment by zhangguy** [comment]
> Well, I have exactly the same problem:
> 
> Integrating data
> Merging dataset 11 22 16 20 9 into 1 2 3 14 21 6 26
> Extracting anchors for merged samples
> Finding integration vectors
> Error in validityMethod(as(object, superClass)) :
> long vectors not supported yet: ../../src/include/Rinlinedfuns.h:522
> Calls: sctransFn ... validObject -> anyStrings -> isTRUE -> validityMethod
> In addition: There were 14 warnings (use warnings() to see them)
> Execution halted
> 
> I guess, no use opening a new issue, this one has been open since Sep 3. Does anybody know if SCTransform without reference (October 18 comment) cannot handle large number of cells in principle, or there can be a way. By the way, I have 28 samples and ~270K cells.



> Hello,
> 
> I'm trying to integrate 18 datasets with 74k cells in total, using SCT normalization, but I get this error:
> 
> ```
> Error in validityMethod(as(object, superClass)) :
>   long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519
> Calls: IntegrateData ... validObject -> anyStrings -> isTRUE -> validityMethod
> 17: validityMethod(as(object, superClass))
> 16: isTRUE(x)
> 15: anyStrings(validityMethod(as(object, superClass)))
> 14: validObject(.Object)
> 13: .nextMethod(.Object = .Object, ... = ...)
> 12: callNextMethod()
> 11: initialize(value, ...)
> 10: initialize(value, ...)
> 9: new("dgTMatrix", Dim = d, Dimnames = dn, i = i, j = j, x = x)
> 8: newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[, 2]),
>        x = if (Generic == "+") c(e1@x, e2@x) else c(e1@x, -e2@x))
> 7: .Arith.Csparse(e1, e2, .Generic, class. = "dgCMatrix")
> 6: data.use2 - data.use1
> 5: data.use2 - data.use1
> 4: FindIntegrationMatrix(object = merged.obj, integration.name = integration.name,
>        features.integrate = features.to.integrate, verbose = verbose)
> 3: RunIntegration(filtered.anchors = filtered.anchors, normalization.method = normalization.method,
>        reference = object.1, query = object.2, cellnames.list = cellnames.list,
>        new.assay.name = new.assay.name, features.to.integrate = features.to.integrate,
>        features = features, dims = dims, weight.reduction = weight.reduction,
>        do.cpp = do.cpp, k.weight = k.weight, sd.weight = sd.weight,
>        eps = eps, verbose = verbose)
> 2: PairwiseIntegrateReference(anchorset = anchorset, new.assay.name = new.assay.name,
>        normalization.method = normalization.method, features = features,
>        features.to.integrate = features.to.integrate, dims = dims,
>        k.weight = k.weight, weight.reduction = weight.reduction,
>        sd.weight = sd.weight, sample.tree = sample.tree, preserve.order = preserve.order,
>        do.cpp = do.cpp, eps = eps, verbose = verbose)
> 1: IntegrateData(anchorset = anchors, normalization.method = "SCT",
>        dims = 1:40, verbose = FALSE)
> ```
> 
> From what I've read in other issues, I think that this error usually happens with a larger number of cells.
> 
> In relation to this issue, I wonder:
> 
> 1. What would be the difference between the integration above and integrating in pairs, and then integrating integrated objects and so on?
> 2. What would be the difference between the integration above and integrating onto one of the selected datasets as reference? Does it matter which dataset is selected as reference?
> 
> Thank you.
> PS. I use Seurat v 3.1.0

This happens to me when I give a large number of genes for ```features.to.integrate```.

**Comment by satijalab** [comment]
I think the issue here is the use of large numbers of genes for features.to.integrate. This creates a non-sparse matrix for all genes, and is infeasible for any method - its not a specific problem with the Seurat alignment workflow. We do not suggest batch-correcting all genes, only ones that exhibit variation across single-cells, which are informative for downstream clustering analyses.

**Comment by JingleW** [comment]
> I think the issue here is the use of large numbers of genes for features.to.integrate. This creates a non-sparse matrix for all genes, and is infeasible for any method - its not a specific problem with the Seurat alignment workflow. We do not suggest batch-correcting all genes, only ones that exhibit variation across single-cells, which are informative for downstream clustering analyses.

I met the same problem when integrating 15 samples. Could you please specify how to batch-correct only the genes exhibiting variation across single-cells?
    There were new methods for integration, reference-based and reciprocal PCA. Which one do you recommend for integration? Standard or SCTransform integration with batch-correct only the genes exhibiting variation across single-cells, or reference-based or reciprocal PCA? 
    Thank you very much.

**Comment by yingyonghui** [comment]
Hello, 
I just came across the same problem when integrating 33 samples with ~120k cells.
Any practical suggestion would be appreciated!
