### ISSUE TITLE
Missing column in the Seurat object hangs the R process

### ISSUE THREAD

**Issue by royfrancis** [satijalab/seurat#2064]
Missing column in the Seurat object hangs the R process. And I have to restart the R session to continue. It would be nice if this returned an error gracefully.

In this example below, column *cell_type* does not exist.
```
TSNEPlot(e,group.by="cell_type")
Error in `[[.Seurat`(object, group.by) : 
  Cannot find 'cell_type' in this Seurat object
```

Seurat 3.1.0 on R version 3.6.0 under Ubuntu 18.04.3 LTS

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
