### ISSUE TITLE
Extract a 'corrected' counts matrix from "integrated" assay?

### ISSUE THREAD

**Issue by JG-Nicholson** [satijalab/seurat#2065]
Hi Seurat Team,
        I'm trying to perform downstream GRN inference (using BigSCale2) on Seurat v3 integrated data (from different tumour samples). This requires 'raw' reads as input, so no negative values & unlogged data.

Is there a way I might be able to do this? Ie. something similar to what you obtain from pbmc[["SCT"]]@counts after normalisation. I have a feeling the answer is no.... but here's hoping for a yes!

thanks,
James

**Comment by timoast** [comment]
Hi, as you guessed we don't provide corrected counts. I would not recommend using corrected data for gene regulatory network inference anyway, for the same reason we don't recommend using corrected data for differential expression.
