### ISSUE TITLE
AverageExpression versus GetAssayData units problem

### ISSUE THREAD

**Issue by drewvoigt10** [satijalab/seurat#2066]
Hello, Thank you for the fantastic package of Seurat.

Some of my collaborators enjoy seeing average expression of the genes in each cluster, and would like the FeaturePlots scale to match their spreadsheets. I was going to create a custom plot function to accomplish this task, but am having trouble with expression units. In a reproducible example:

Here, I pull out the average expression of CD79A from the data slot.
`Idents(pbmc_small) <- "RNA_snn_res.1"` 
`AverageExpression(pbmc_small, features = "CD79A", slot = "data")` 
In cluster 2, the average expression of CD79A is 215.1

However, if I subset the cells in cluster 2 and grab their expression from the @data slot, like so...
`cluster2 <- subset(pbmc_small, RNA_snn_res.1==2)`
`data <- GetAssayData(object = cluster2, slot="data")`
`summary(data[which(rownames(data)=="CD79A"),])`
the mean expression is 2.822. 

Why are these so disparate? How can I calculate the average expression of CD79A from the data slot and match the output of the AverageExpression function?

**Comment by andrewwbutler** [comment]
Hi,

From the  documentation for `AverageExpression`
> Output is in log-space when return.seurat = TRUE, otherwise it's in non-log space. Averaging is done in non-log space. 

If you want to match the output, change the `summary` line to:
```R
mean(expm1(data["CD79A", ]))
```
If you want it back in log-space, wrap in a `log1p` call.
