### ISSUE TITLE
Integrating two or more scRNA datasets.

### ISSUE THREAD

**Issue by piyush-jo15** [satijalab/seurat#2069]
Hi,
I am following the seurat vignette for integrating two scRNA-seq data. What is not clear to me is that are the two datasets raw unprocessed data or already filtered for mitochondrial transcript percentage and low and high level of genes called.
In my case I first analyzed individual data by filtering and scaling with regressing out cell cycle gene effect. Then I wish to integrate the two filtered and processed dataset to perform cluster analysis. 
On the tutorial I see that the integrated data was normalized and scaled, but not filtered for mitochondrial transcripts and low/high gene calls. 
Any suggestion will be appreciated!

**Comment by timoast** [comment]
Hi, we recommend performing QC and filtering low quality cells from each dataset before integration.
