### ISSUE TITLE
RemoveAssayObject-method

### ISSUE THREAD

**Issue by zinagood** [satijalab/seurat#2070]
Dear Seurat Team,

I'm running into memory issues with large Seurat objects. One way to reduce the size of an object is to remove data that is no longer needed. For example, I'm doing data integration with SCTransform pipeline, which means that i no longer need to use the RNA assay. However, if I re-create a new Seurat with only SCT data, it appears that I'm missing some tags that PrepSCTIntegration is looking for. Can I remove RNA data (e.g. you could make RemoveAssayObject function), or create a new Seurat object that has all features for PrepSCTIntegration?

Thanks!
Zina

**Comment by andrewwbutler** [comment]
Hi Zina,

You can check out the `DietSeurat` function to remove parts of the Seurat object that you don't want to keep around any more.
