### ISSUE TITLE
FindAllMarkers cannot allocate vector of size 1.0 Gb - Data conversion 

### ISSUE THREAD

**Issue by zezhuo** [satijalab/seurat#2072]
Hi Seurat team,

I passed an integrated SingleCellExperiment object to Seurat by as. seurat funtion with counts = NULL. However, FindVariableFeatures function cannot allocate vector of size 2.1 Gb (6 batches of scRNAseq data). It works well when aggregating 2 batches of scRNAseq data only. In this regard, I caculated the variable features by other methon and pass it to seurat object directly. Clustering went well. But when I tried to run FindAllMarkers. Similar error came out: cannot allocate vector of size 1.0 Gb. 

Will a better computor/icloud solve the problem?

Looking Forward to your suggestions.

Best regards,
Nelson

```
> b6mnn <- FindVariableFeatures(object = b6mnn, selection.method = "vst", nfeatures = 2000)
Error: cannot allocate vector of size 2.1 Gb
In addition: Warning message:
In FindVariableFeatures.Assay(object = assay.data, selection.method = selection.method,  :
  selection.method set to 'vst' but count slot is empty; will use data slot instead
```

```
# Pass to Seurat
assay(f.out) <- as.matrix(assay(f.out))
b6mnn <- as.Seurat(f.out, counts = NULL, data = "reconstructed")
VariableFeatures(object = b6mnn) <- combined.dec[order(combined.dec$bio, decreasing = T), ] %>% head(2000) %>% row.names()
```

```
> # Finding differentially expressed features (cluster biomarkers)
> b6mnn.markers <- FindAllMarkers(object = b6mnn, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, slot = "data")
Calculating cluster 0
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Calculating cluster 7
Calculating cluster 8
Calculating cluster 9
Calculating cluster 10
Calculating cluster 11
Calculating cluster 12
Calculating cluster 13
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:
	cannot allocate vector of size 895.6 Mb
Warning: When testing 1 versus all:
	cannot allocate vector of size 900.4 Mb
Warning: When testing 2 versus all:
	cannot allocate vector of size 932.3 Mb
Warning: When testing 3 versus all:
	cannot allocate vector of size 956.3 Mb
Warning: When testing 4 versus all:
	cannot allocate vector of size 1007.4 Mb
Warning: When testing 5 versus all:
	cannot allocate vector of size 1010.1 Mb
Warning: When testing 6 versus all:
	cannot allocate vector of size 1011.7 Mb
Warning: When testing 7 versus all:
	cannot allocate vector of size 1023.7 Mb
Warning: When testing 8 versus all:
	cannot allocate vector of size 1.0 Gb
Warning: When testing 9 versus all:
	cannot allocate vector of size 1.0 Gb
Warning: When testing 10 versus all:
	cannot allocate vector of size 1.0 Gb
Warning: When testing 11 versus all:
	cannot allocate vector of size 1.0 Gb
Warning: When testing 12 versus all:
	cannot allocate vector of size 1.0 Gb
Warning: When testing 13 versus all:
	cannot allocate vector of size 1.1 Gb
Warning message:
In diff.default(xscale) : reached elapsed time limit
```

**Comment by timoast** [comment]
How much RAM do you have?

**Comment by zezhuo** [comment]
> 
> 
> How much RAM do you have?

Hi @timoast ,

I have 12 GB RAM. How many do you recomend for 20k x 20k data. We are generating more and more data. Thanks!

Regards,
Neslon

**Comment by zezhuo** [comment]
Hi @j-andrews7 ,

Thanks for your suggestions. I did return all genes from Scaledata. Do you means FindAllmarkers only test the scaled genes? If so, will there be any significant markers that are missing in the top variable features?

Regards,
Nelson

**Comment by j-andrews7** [comment]
If you return all genes, it will drive up the size of the object by a ton, as that matrix is not sparse - it takes up much more memory than the count matrices. `FindAllMarkers` doesn't use the scaled data (by default), but rather uses the normalized counts. You will not miss any markers by not returning all genes from `ScaleData`. The only thing it *might* impact is removing a handful of genes if you use `DoHeatmap` on your markers.

**Comment by zezhuo** [comment]
Hi @j-andrews7 ,

Oh, I see. ScaleData is the problem. It is used for PCA analysis and visualization of marker genes. For the integrated data, FindAllMarkers take the corrected normalized matrix as input. I got some problem when I apply FindAllMarkers to raw log count matrix without betch effects removal. I wonder, can FindAllMarkers block batch effect when applied to raw log count matrix?

Regards,
Nelson

**Comment by timoast** [comment]
Hi Nelson, we don't recommend running DE on the integrated data as this introduces dependencies between datapoints that violates assumptions in the DE test. Instead you should run DE on the RNA assay, and you can include batch as a latent variable in the test, for example:

```r
markers <- FindAllMarkers(object, test.use = "LR", latent.vars = "batch")
```

(where "batch" is a variable in the object metadata that groups the cells by batch)
