### ISSUE TITLE
Problem with cluster identity permutations and AverageExpression

### ISSUE THREAD

**Issue by jopejor** [satijalab/seurat#2073]
When I permute the cluster identities I keep getting the same AverageExpression matrix all the time, a similar issue occurs when sampling with subset.

seu.downsample = subset(seu.selected, cells = sample(Cells(seu), 10000))
seu.boot <- seu.downsample
seu.boot@meta.data$permutation = permute(seu.boot@meta.data$CellType)
Idents(object = seu.boot) = 'permutation'
wut = AverageExpression(object = seu.boot,verbose=FALSE)
data = wut$SCT
head(data)

**Comment by andrewwbutler** [comment]
Hi,

Can you provide a reproducible example using either the test dataset (`pbmc_small`) or one of the datasets from [SeuratData](https://github.com/satijalab/seurat-data).
