### ISSUE TITLE
Negative expression values (FeaturePlot) after integration

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#2074]
Hi!

I followed the instructions for the data integration with anchoring ('[IntegrateData](https://satijalab.org/seurat/v3.0/integration.html)') 4 datasets. After 

_NormalizeData > FindVariableFeatures > IntegrateData > ScaleData > RunPCA > RunUMAP > FindNeighbors > FindClusters_ 

 I looked at some markers with FeaturePlot and the scale suggests values from -2 to 4.
I might have misunderstood sg, but how do I get **negative expression values** here?

thank you!

**Comment by timoast** [comment]
Please see #1057
