### ISSUE TITLE
UMAP and ClusterTree don't match up

### ISSUE THREAD

**Issue by PedroRaposo** [satijalab/seurat#2075]
Hi!

After I did my PCA, I clustered my data and plotted on a UMAP plot, and on a cluster tree plot. It seems the data does not match up. Some clusters that are very far apart in UMAP are reported to be very similar in cluster tree plot. (I'm using the first 20 PC in both approaches, so I don't know why this happens.)

![UMAP_Adipose](https://user-images.githubusercontent.com/16338197/64433428-52020480-d0b6-11e9-8752-3d629088821a.png)

![Cluster_Adipose](https://user-images.githubusercontent.com/16338197/64433444-5af2d600-d0b6-11e9-8a2d-caceda4250e1.png)

In this example, you can see this happening in cluster 5 and 6.
Can someone shed a light on this issue?
Could this be because UMAP uses a non-linear approach and (maybe) ClusterTree uses a linear approach (I don't know if this is true)? 
Thank you in advance!

**Comment by timoast** [comment]
You should be cautious in interpreting distances in the 2D UMAP, see this issue for more information: https://github.com/lmcinnes/umap/issues/92
