### ISSUE TITLE
Updated symbols for cc.genes

### ISSUE THREAD

**Issue by jbalberge** [satijalab/seurat#2076]
Human cell cycle-related genes _MLF1IP_, _FAM64A_ and _HN1_ have new symbols (resp. _CENPU_, _PICALM_ and _JPT_) that could be added to `cc.genes` lists.

MLF1IP, FAM64A and HN1 are in `cc.genes`, but are replaced by CENPU, PICALM and JPT in more recent alignment tools. `CellCycleScoring` doesn't throw any warning (see `return(intersect(x = x, y = rownames(x = object)))` in Seurat::AddModuleScore)

Can we securely add new symbols to the cc.genes lists? Can we throw an error / warning if scoring genes are not found in the feature-barcode matrix ?

**Comment by mojaveazure** [comment]
Hi,

We've added warning messages if features in the feature list are not present in the object for `AddModuleScore` (and, by extension, `CellCycleScoring`). In addition, we've added a new `search` parameter to automatically search for updated symbols using [HGNC's gene names database](https://www.genenames.org) (`TRUE` by default). Finally, we've added a `cc.genes.updated.2019` object with the same feature list as `cc.genes` updated with symbols as of Sept. 13, 2019; see the help page for the object for more details about which features have been updated and what their new symbols are.

All of the above fixes are on the development branch. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
