### ISSUE TITLE
Error in dim.data.self[cells1, ] : incorrect number of dimensions

### ISSUE THREAD

**Issue by sygongcode** [satijalab/seurat#2077]
Hello, everyone,
When I was running anchor, I have got an error "Error in dim.data.self[cells1, ] : incorrect number of dimensions". What does that mean? Which dimension is not incorrect? The dimension in each object or somewhere else? Does someone also have the error? Thank you. My code is:
xxx$stim <- "CTRL"
yyy$stim<- "STIM"
aaa.anchors <- FindIntegrationAnchors(object.list = list(xxx, yyy), dims = 20)

**Comment by timoast** [comment]
`dims` should be a vector, not a single number, ie. `1:20`. See the documentation for `FindIntegrationAnchors` for more information.

**Comment by sygongcode** [comment]
> `dims` should be a vector, not a single number, ie. `1:20`. See the documentation for `FindIntegrationAnchors` for more information.

I use the default code

**Comment by sygongcode** [comment]
> > `dims` should be a vector, not a single number, ie. `1:20`. See the documentation for `FindIntegrationAnchors` for more information.
> 
> I use the default code

Oh, I see. thank you so much.

**Comment by sygongcode** [comment]
> > > `dims` should be a vector, not a single number, ie. `1:20`. See the documentation for `FindIntegrationAnchors` for more information.
> > 
> > 
> > I use the default code
> 
> Oh, I see. thank you so much.
I have made a so stupid mistake.
