### ISSUE TITLE
Change seurat object to make it version 2 compatible

### ISSUE THREAD

**Issue by bapoorva** [satijalab/seurat#2078]
Hi ! I'm trying to run [PAGA](https://romanhaa.github.io/blog/paga_to_r/) on my single cell dataset. Unfortunately this algorithm works only with Seurat version2. Now i have Seurat 2.3.4 installed in a different location. However my seurat object was created with v3. I know UpdateSeuratObject function makes it compatible with the most latest version but is there an easier way to convert it to the lower version without having to analyze it again ?

Thanks

**Comment by timoast** [comment]
Hi, we don't support conversion from v3 to v2. You can create a new Seurat object using v2 by extracting the data and metadata from the v3 object using `GetAssayData`, then loading the v2 package and running `CreateSeuratObject`.

**Comment by bapoorva** [comment]
Figured that is what I'd have to do. Thank you very much.

**Comment by GianlucaDuda** [comment]
Hi bapooorva,
can you share how you downgrade the v3 object?

**Comment by Lindsey8383** [comment]
You can write whatever information you desire to keep to CSV files. 

For example, if you want to retain raw counts and metadata information, do something like the following (in your newer Seurat version):

`write.csv(as.matrix(GetAssayData(object = obj_name, slot = "counts")), '/path/to/raw_counts.csv')
write.csv(obj_name@meta.data,"/path/to/metadata.csv")`

Then, you can "downgrade" your Seurat version by installing an old version to the directory housing your packages (whatever directory that calling `.libPaths()` returns to you). Here is an example downgrading to version Seurat 3.1.0:

`remotes::install_version(package = 'Seurat', version = package_version('3.1.0'), lib="/path/returned/by/libPaths/Seurat_old_version")`

First, "unload" your current, newer version of the Seurat package:
`detach("package:Seurat", unload=TRUE)`

Then import your older Seurat version: 
`library("Seurat", lib.loc="/path/returned/by/libPaths/Seurat_old_version")
`

Check to make sure you've imported the version you want:
`packageVersion('Seurat')`

Recreate your Seurat object in the older version:
`counts<-read.csv(file = '/path/to/raw_counts.csv', header = TRUE)
meta_dat <- read.csv(file='/path/to/metadata.csv', header = TRUE)
v3_obj <- CreateSeuratObject(counts=counts, meta.data=meta_dat)`
