### ISSUE TITLE
An issue with rpy2

### ISSUE THREAD

**Issue by MingBit** [satijalab/seurat#2079]
Hey,

I just re-installed the newest version of Seurat. Unfortunately, it didn't work with **rpy2**
It works with other R packages (e.g. openxlsx).

```
>>> import rpy2.robjects.packages as rpackages
>>> rpackages.importr('openxlsx')
```

```
>>> import rpy2.robjects.packages as rpackages
>>> rpackages.importr('Seurat')
Segmentation fault (core dumped)
```

Any ideas? Thanks a lot. :D

**Comment by MingBit** [comment]
It works with old version **(v 2.3.3)**

**Comment by mojaveazure** [comment]
This is not something we have the capabilities to address. We are an academic lab, not a software development company. As such, we only have the bandwidth to support Seurat under certain environments. As this is an R package and the vast majority of our users use Seurat from R, not Python, we prioritize issues running Seurat in R over running Seurat in Python. I recommend using Seurat in R instead of from Python via rpy2. If you have issues using Seurat in R, we can work on addressing those.

**Comment by JoaoGabrielMoraes** [comment]
@MingBit

I am having the same problem. Were you able to make it work on version 3.0?

Thank you!

**Comment by MingBit** [comment]
Not yet. Switched to Scanpy...:D

**Comment by JoaoGabrielMoraes** [comment]
@MingBit 

Thanks! I think that's what I'll do.

**Comment by fidelram** [comment]
Was having the same issue. Solved it by downgrading Seurat to version 3.0.2 using:
```R
devtools::install_github(repo = 'satijalab/seurat@v3.0.2', dependencies=FALSE, force=TRUE)
```
@mojaveazure in case it helps, some code added between 3.0.2 and 3.1.0 releases is breaking this functionality.

**Comment by maximilianh** [comment]
I'm also having this problem, for an importer of various Seurat objects into the cell browser. If this is not a priority for the team, which I can understand, I guess I'll stick with generating R scripts and running them through Rscript and parsing the resulting .tsv files.

**Comment by qinqian** [comment]
The key part of this is to use the right R version, I have the same problem when using R 3.6.1. But when I downgraded R to 3.5.1, seurat 3.1.1 import is correct. The python environment is conda 4.6.12 with python 3.6.7. 

Below is the test script:
```
from rpy2.robjects.packages import importr
seurat = importr('Seurat')
print(seurat)
```

**Comment by sri540** [comment]
Is running Seurat on Python provide any advantages ?

**Comment by qinqian** [comment]
> Is running Seurat on Python provide any advantages ?

It is easier to write pipeline.
