### ISSUE TITLE
How can I analysis several sample together?

### ISSUE THREAD

**Issue by lilycanfly** [satijalab/seurat#208]
Hi, I have 3 samples of single cell RNA seq data. I would like to pull them together and analyze them. Is there any way I can do it? Thanks a lot.

**Comment by andrewwbutler** [comment]
Try using `MergeSeurat` and/or `AddSamples`. You can see some examples of how to use those [here](http://satijalab.org/seurat/merge_vignette.html).

**Comment by lilycanfly** [comment]
Thanks a lot. After merge my sample, Could I just follow the normal analysis like PBMC tutorial? Or I should follow the alignment tutorial? 

Best,
Lili

**Comment by satijalab** [comment]
The integration/alignment procedure is most valuable when standard analyses (as described in the PBMC tutorial) fail to align shared populations across experiments or batches. You can read more about this in the preprint : https://www.biorxiv.org/content/early/2017/07/18/164889
