### ISSUE TITLE
Transfer query dataset to reference embedding?

### ISSUE THREAD

**Issue by chlee-tabin** [satijalab/seurat#2080]
Is it possible to project the cells from a query dataset to the embedding of a reference, where the reference embedding has been already computed? (This is different from computing the embedding all together with the integrated workflow)

The motivation of this question comes from the standard LabelTransfer procedure; For our type of questions, instead of cell type labels, we have a continuum (differentiation) and we want to know where a query cell might lie within a continuum.

Any suggestions appreciated!

**Comment by andrewwbutler** [comment]
Hi,

Yes it should be possible to transfer the reference embeddings by providing them to the `refdata` parameter, though we haven't extensively tested this case of transferring low dimensional representations. As you mention, you could also integrate the reference and query to compute a joint embedding as well.
