### ISSUE TITLE
Add sample to meta data of seurat object? 

### ISSUE THREAD

**Issue by Seandelao** [satijalab/seurat#2081]
Hello, 

I am working off of a Seurat object that consists of multiple samples merged together. How would I add sample identifiers to an already created/merged dataset in relation to the orig.ident? 

For example, I have a merged object with orig.idents of sample1_lane 1, sample1_lane2, sample2_lane1, sample2_lane2. I would like to add meta data so that sample1_lane1 and sample1_lane2 cells can be identified as "Sample1", sample2_lane1 and sample2_lane2 as "Sample2" etc. 

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

This is more of an R question that a Seurat question but essentially you need to make a new vector that maps your `orig.idents` to the new sample names and then add that to a new metadata column. One way of doing that could be:

```R
object$sample <- plyr::mapvalues(
    x = object$orig.ident, 
    from = c("sample1_lane1", "sample1_lane2", "sample2_lane1", "sample2_lane2"), 
    to = c("Sample1", "Sample1", "Sample2", "Sample2")
)
```

**Comment by meliseedwards** [comment]
Hi there, 

Would either of you have suggestions for merging multiple metadata files into the Seurat object?

For example, I have 3 metadata files; 

1) barcode, sample ID, batch
2) orig.ident, nCount_RNA, nFeatureRNA, barcode 
3) a clinical metadata matrix with sample ID, barcode, and diagnosis information (e.g., disease status, genotype) 

I have tried merging these files (by="barcode"), "AddMetaData" (Seurat), and so far nothing has worked to solve the issue of making sure all metadata information is together and stored as one single metadata file. 

Is this something that should be done before the Seurat object is made? Thanks in advance for any help or suggestions.
