### ISSUE TITLE
find.markers.node

### ISSUE THREAD

**Issue by NaomiCroft** [satijalab/seurat#2084]
Hi,
I am using Seurat V3 and working with a non-model organism. I want to find common markers within two clusters, to see if they are sub-clusters of the same cell branch, or if they very different. 

I used the function BuildClusterTree to relate the ‘average’ cell from each cluster. I then wanted to use this to define markers of a clade, instead of an individual cluster. 

When I try to use the function find.markers.node:
all.markers <- find.markers.node(object = allsample.data.seurat, node = 16)
#head(x = all.markers)

I get this error message:
Error in find.markers.node(object = allsample.data.seurat, node = 16) : 
  could not find function "find.markers.node"

Is there another function I can use? Crucially I don't want the differential gene expression between the clusters of a clade, I want to the shared markers that a clade expresses.

Thanks for your time.

**Comment by diazdc** [comment]
I believe that function was removed for version 3+. Here's one way to do it manually:

    # Grab possible nodes, assuming you've run BuildClusterTree()
    nodes <- unique(seurat_obj@tools$BuildClusterTree$edge[,1])
    
    tree_markers <- list()
    for(i in 1:length(nodes)) {
       tree_markers[[i]] <- FindMarkers(
         seurat_obj, ident.1 = "clustertree", ident.2 = nodes[i])
    }

**Comment by andrewwbutler** [comment]
Hi,

Please see the `FindMarkers` function. If you pass either the `phylo` object or the string "clustertree" to `ident.1` and the node you're interested in to `ident.2`, this should provide the functionality you're looking for.

**Comment by NaomiCroft** [comment]
I thought the FindMarkers function would only print the differentially expressed genes between clusters, not give shared markers?
