### ISSUE TITLE
FeaturePlot when use min.cutoff and split.by together

### ISSUE THREAD

**Issue by liuyifang** [satijalab/seurat#2086]
Hi, I found an issue when use `min.cutoff` and `split.by` together if the gene is not expressed in all the cells in one of my samples.

When do not use `min.cutoff`:

```R
FeaturePlot(obj, features = gene, cols = c("grey", "blue"), reduction = "umap", split.by = "Sample")
```

It plot correctly with a warning: 

> In FeaturePlot(obj, features = gene, cols = c("grey", "blue"),  :
>   All cells have the same value (0) of gene.
<img width="806" alt="Screen Shot 2019-09-10 at 4 08 44 PM副本" src="https://user-images.githubusercontent.com/520808/64648576-2a2ddc00-d3e9-11e9-8f05-464e585d11e1.png">

But when use `min.cutoff` and `split.by` together:

```R
FeaturePlot(obj, features = gene, cols = c("grey", "blue"), reduction = "umap", min.cutoff = 1, split.by = "Sample")
```

It plot incorrectly with a warning: 

> In FeaturePlot(obj, features = gene, cols = c("grey", "blue"),  :
>   All cells have the same value (1) of gene.

All the cells in Sample3 seems express the gene at the same level, but actually no cells in the Sample3 express this gene.
<img width="806" alt="Screen Shot 2019-09-10 at 4 09 10 PM副本" src="https://user-images.githubusercontent.com/520808/64648593-3154ea00-d3e9-11e9-8745-f78c1ac14ae9.png">

**Comment by mojaveazure** [comment]
This is the expected behavior of `min.cutoff`; what happens is it sets all expression values below the cutoff to the cutoff value.

**Comment by oligoelemento** [comment]
I do the following trick, giving artificial value of 1 to the first cell for the desired gene:
`# To correct the scale in FeaturePlot
if (sum(s$RNA@data[gene,])<1){
    s$RNA@data[gene,1]=1
 }`
