### ISSUE TITLE
Subclustering an integrated object

### ISSUE THREAD

**Issue by gilstel** [satijalab/seurat#2087]
I used the standard integration workflow.  Now I want to subcluster a subset of the cells from the integrated object.  From reading various vingettes and here on github, the recommended workflow seems to be - subset the desired cells, FindVariableFeatures, ScaleData, RunPCA, FindNeighbors, FindClusters (and then RunUMAP).

I have several issues - 

1. The Seurat 3 "subset" function does not support do.clean which was recommended in Seurat2  for subsetting cells.  I tried using the Seurat v3 DietSeurat - 
DietSeurat(object = neuron.reclust.list[[i]], counts = TRUE, data = TRUE, scale.data = FALSE)
but recieved the following error -
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) :
no 'dimnames[[.]]': cannot use character indexing
Therefore, I gave up on using DietSeurat.

2. I could use the variable features already found and continue to ScaleData.  This doesn't make much sense since the features previously selected for the entire dataset as variable features and not necessarily for the subsetted cells.  Indeed,  when I do this - 
ScaleData(object = neuron.reclust.list[[i]], block.size = 4000)
I recieve the following warning -
Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
The following 3 features requested have zero variance (running reduction without them): F13a1, Cd209f, F630028O10Rik

3.  FindVariableFeatures for the subset using the current "integrated" default assay - 
FindVariableFeatures(object = neuron.reclust.list[[i]])
I recieve several warnings -
Warning messages:
1: In FindVariableFeatures.Assay(object = assay.data, selection.method = selection.method, :
selection.method set to 'vst' but count slot is empty; will use data slot instead
2: In eval(predvars, data, env) : NaNs produced
3: In hvf.info$variance.expected[not.const] <- 10^fit$fitted :
number of items to replace is not a multiple of replacement length

1997 variable features were found (only 2000 features have normalized data since they were selected as anchors by default, none of the features has count data in the integrated object)

4.  Switch to the "RNA" assay and find variable features.  2000 features were found (since the default param was not changed in FindVariableFeatures) that are different from those that were stored as variable features during the original integration process.
I then used ScaleData, followed by JackStraw and ScoreJackStraw which were fine.

JackStraw(object = neuron.reclust.list[[i]], num.replicate = 100)
ScoreJackStraw(object = neuron.reclust.list[[i]], dims = 1:20)

When I subsequently used JackStrawPlot
JackStrawPlot(object = neuron.reclust.list[i], dims = 1:20)
I received the following error -
Error in UseMethod(generic = "JS", object = object) :
no applicable method for 'JS' applied to an object of class "NULL"

Neveretheless, I continued to use FindNeighbors and FindClusters with 20 PC's (based on DimHeatmap).

If I continue with the RNA assay, how is the integration information used at all, since I used the RNA assay throughout the reclustering?

Thanks,
Gil

**Comment by carmensandoval** [comment]
I'm having a similar issue when trying to find the variable features of an integrated object.

![image](https://user-images.githubusercontent.com/10520084/65467758-0e79fb00-de17-11e9-9ed4-8f722ebe7d8a.png)

```
Warning messages:
1: In FindVariableFeatures.Assay(object = assay.data, selection.method = selection.method,  :
  selection.method set to 'vst' but count slot is empty; will use data slot instead
2: In eval(predvars, data, env) : NaNs produced
3: In hvf.info$variance.expected[not.const] <- 10^fit$fitted :
  number of items to replace is not a multiple of replacement length
```

I want to find the variable features *after batch correction*, before running PCA on the integrated object, as currently PCA is performed on the  *current* `var.features`, which I believe are imported from the anchoring features used to integrate the object.

**Comment by innesbre** [comment]
I think the issue #2551 might be a cause of this?

**Comment by timoast** [comment]
Sorry for the delay here. Just to clarify, here is what I'd suggest for subclustering a log-normalized integrated assay:

1. Subset the cells
2. Find variable features in the subset using the RNA assay
3. Run ScaleData on the integrate assay on the new set of variable features
4. Run PCA on the integrated assay using the new set of variable features
5. Run FindNeighbors and FindClusters using the new PC dimensions

**Comment by duocang** [comment]
> Sorry for the delay here. Just to clarify, here is what I'd suggest for subclustering a log-normalized integrated assay:
> 
> 1. Subset the cells
> 2. Find variable features in the subset using the RNA assay
> 3. Run ScaleData on the integrate assay on the new set of variable features
> 4. Run PCA on the integrated assay using the new set of variable features
> 5. Run FindNeighbors and FindClusters using the new PC dimensions

@timoast 
What if I need do cell cycle and findmarker? Should  I follow the scaleData on the inegrated (step 3 obove)?

**Comment by duocang** [comment]
> Sorry for the delay here. Just to clarify, here is what I'd suggest for subclustering a log-normalized integrated assay:
> 
> 1. Subset the cells
> 2. Find variable features in the subset using the RNA assay
> 3. Run ScaleData on the integrate assay on the new set of variable features
> 4. Run PCA on the integrated assay using the new set of variable features
> 5. Run FindNeighbors and FindClusters using the new PC dimensions

Hi @timoast 
Should I run SCTransform again when subsetting an integrated by **SCT-normalized integration**?


For example
```r
LoadData("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")
ifnb.list <- lapply(X = ifnb.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT",
    anchor.features = features)
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")


############ I am a separation line ###############

# subsetting happens here for sepcific cells
cell.target <- c(...)
seu.ONE <- subset(immune.combined.sct, cells= cells.target)
```

Can I run FindVariableFetures on seu.ONE?
Should I run SCTransform on seu.ONE again?

**Comment by denvercal1234GitHub** [comment]
Hi @duocang - Did you settle on the workflow for your SCTransform-ed integrated object?

**Comment by duocang** [comment]
> 

@denvercal1234GitHub Hi. Not sure what you mean settle on the workflow for SCT-ed integrated.

**Comment by denvercal1234GitHub** [comment]
hI @duocang - Above, you asked "Can I run FindVariableFetures on seu.ONE? and Should I run SCTransformon seu.ONE again?". Did you get some answers for these questions?

**Comment by duocang** [comment]
@denvercal1234GitHub .

I had no solid answer.

I neve re-do FindVariableFeatures because my genes of interest are week, so I leave nfeatures with a big number in the first step.

There is no big difference to run sct again. But your umap can be better after you run it again.

**Comment by denvercal1234GitHub** [comment]
I see. Thank you.

**Comment by apal6** [comment]
Hi,

I wonder what is the recommended workflow for subclustering? Do we redo the integration or not? 
I am clustering my T cell population after subsetting and have so far tried both but not sure what would be the ideal way. 

Thanks in advance.

Best,
Aastha
