### ISSUE TITLE
sctransform error 

### ISSUE THREAD

**Issue by FaithZhang** [satijalab/seurat#2089]
I was running sctranform and the error message came:

Error in while ((it <- it + 1) < limit && abs(del) > eps) { : 
  missing value where TRUE/FALSE needed

May I know what the issue may be?

Best,

Jiajia

**Comment by timoast** [comment]
Please post this issue in the sctransform repository: https://github.com/ChristophH/sctransform

**Comment by mdidish** [comment]
If others have the same problem, installing the development version fixed the problem for me :
`remotes :: install_github ("ChristophH / sctransform @ develop")`.
Best
Marc
