### ISSUE TITLE
k.filter settings on FindIntegrationAnchors

### ISSUE THREAD

**Issue by DRLaks** [satijalab/seurat#2090]
Hello,
     What is the optimal way to set k.filter for FindIntegrationAnchors if there are less than 200 cells? Should this parameter be set as high as possible or at a fraction of total cells? The results seem sensitive to this parameter so I would like to know what is the best way to set k.filter.
      All the best,
                       Dan

**Comment by satijalab** [comment]
Apologies for the slow reply. To be fully transparent, the Seurat integration methods (and indeed, any graph-based methods including Louvain clustering), begin to struggle with far less than 200 cells. Its difficult to give advice here, but I suppose I would personally turn off the anchor flitering (set k.filter = NA)
