### ISSUE TITLE
What's the differences between adt pca and general pca

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#2093]
Hello, Seurat team,

I'm doing clustering based on ADT data only. I saw that Seurat have adt pca for clustering based on ADT data only, however, since we don't have RNA expression data, we cannot create Seurat object, and I have 6 samples and I have to merge them to one to do the analysis and the Seurat merge function only apply to Seurat object. Therefore, I cannot apply adt pca to my samples. Instead, I using general pca and TSNE (the one that apply to RNA data), however, the result not seems make sense biologically. Therefore, I just wondering what's the differences between adt pca and general pca? And what's the differences between ADT TSNE and general TSNE? If general pca is not works for ADT data, how can I run ADT TSNE ,ADT PCA and clustering with ADT data only without RNA expression data?

**Comment by andrewwbutler** [comment]
Hi,

I'm not sure exactly what you're asking here. There only difference between the PCA on ADT data and the PCA on RNA data is the data (i.e. a different feature set in the matrix that PCA is performed on). I would recommend taking a close look at the [multimodal vignette](https://satijalab.org/seurat/multimodal_vignette.html) if you're still confused by these concepts.

**Comment by YunZheHuang** [comment]
Hello, @andrewwbutler 
I did take a look the multimodal vignette, there is a section call" Cluster directly on protein expression levels", under this section, you guys apply "adt_pca" in the RunPCA function, I just curious what's the differences between "adt_pca" from the 'pca". Thank you!
