### ISSUE TITLE
trajectory analysis for coembed Seurat object

### ISSUE THREAD

**Issue by s18692001** [satijalab/seurat#2094]
Hi there,

I'm working on Monocle 3 trajectory analysis for Seurat coembed scRNA+scATACC object.
I've already annotated the clusters and have the CCA dimension reduction matrix. I'm curious is there any suggestion to import these coembedding information for Monocle3 trajectory analysis? Thanks!

**Comment by andrewwbutler** [comment]
Hi,

For Monocle trajectory analysis questions, I would recommend asking over on the Monocle forums.
