### ISSUE TITLE
Integrate two sets of very similar cell types

### ISSUE THREAD

**Issue by qoiopipq** [satijalab/seurat#2095]
I've done integration analysis of distinct cell types (i.e. different tissue samples) from different platforms/data sets, which worked quite well. 

Then I tried to integrate two 10X libraries of very similar cell types (same tissue) using standard workflow and SCTransform with and without cell cycle regression. In this case,  batch 1 contains cell types: A, B, C, D; batch 2 contains cell types: A, B, C. I expected to see A, B, C from two sets overlap with each other and form cell type specific clusters, while D from batch 1 form a non-overlapping cluster. 
However, I observed:
Cell type A & C:  overlapped quite well from both sets
Cell type B: formed two distinct clusters according to batch 1 and 2
Cell type D: clustered with cell type B from batch 2

My questions are
a) Is CCA sensitive enough to identify canonical correlation vectors that define cell type D presents in only batch 1? If CCA struggles to identify vectors, is it ok to use PCA to compensate this?
b) As two library sizes differ, are there any weighting methods that I can try?

Cheers

**Comment by yuhanH** [comment]
Hi, 
Could you show me your code to do the integration using SCTransform?

**Comment by qoiopipq** [comment]
Hi,
I tried MNN by using RunFastMNN to integrate these two libraries. Same cell types integrated together quite well. Non-overlapping cell type clustered by itself. Overall, the MNN integrated clusters are reasonable. Maybe I did something incorrectly when I was using SCTransform, and here's my code:
###Integration analysis SCTransform###
dn.list<-list(dn.data.f,dn12_singlet)
dn.list

data("cc.genes")
library(stringr)
cc.genes$s.genes<-str_to_title(cc.genes$s.genes)
cc.genes$g2m.genes<-str_to_title(cc.genes$g2m.genes)

for (i in 1:length(dn.list)){
  dn.list[[i]]<-CellCycleScoring(dn.list[[i]], s.features = cc.genes$s.genes,
                                 g2m.features = cc.genes$g2m.genes, set.ident = TRUE)
  dn.list[[i]]$cc.diff<-dn.list[[i]]$S.Score-dn.list[[i]]$G2M.Score
  dn.list[[i]]<-SCTransform(dn.list[[i]], vars.to.regress ="cc.diff" ,verbose = FALSE)
}

dn.features<-SelectIntegrationFeatures(object.list = dn.list, nfeatures = 2000)
dn.list<-PrepSCTIntegration(object.list = dn.list, anchor.features = dn.features)

dn.anchors<-FindIntegrationAnchors(object.list = dn.list, normalization.method = "SCT",
                                   anchor.features = dn.features, dims=1:30,verbose = FALSE)
dn.integrated<-IntegrateData(anchorset = dn.anchors, normalization.method = "SCT", verbose = FALSE, dims=1:30)

dn.integrated<-RunPCA(dn.integrated, verbose = FALSE)
dn.integrated<-RunTSNE(dn.integrated, reduction = "pca",dims=1:30)

dn.integrated <- FindNeighbors(object = dn.integrated)
dn.integrated <- FindClusters(dn.integrated, resolution = 1, dims.use = 1:30)

Cheers

**Comment by jaisonj708** [comment]
If you have cell types that are only present in 1 of your 2 batches, CCA might not preserve the variation between this cell type and others, nor is it guaranteed to preserve the variation within the cell type (though it often does). RPCA might work better here, but it seems like MNN is working for you.
