### ISSUE TITLE
CCA merging objects: names(new.idents) not the same length as rownames(combined.meta.data)

### ISSUE THREAD

**Issue by carmensandoval** [satijalab/seurat#2096]
Hi,

I'm having trouble running CCA on Seurat v3 - keep getting this error when it's merging the two objects:

![image](https://user-images.githubusercontent.com/10520084/64754247-60e41f00-d4db-11e9-975b-c46e391b862f.png)

The total number of cells from the two objects is `88,298`. I don't understand where the `142,727` length for the `names` attribute is coming from. 

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

That is strange. Are you able to share a reproducible example (e.g. using some of the tutorial datasets or downsampled versions of your objects)?
