### ISSUE TITLE
FeaturePlot result rotate when using readRDS to get Seurat object saved by saveRDS

### ISSUE THREAD

**Issue by hffqyd** [satijalab/seurat#2097]
When I FeatuePlot of tsne using Seurat object read from `rds` files saved by saveRDS, the tsne plot rotated and was different from that ploted using Seurat object before saving.

What might be the problem to get this situation, please?

Thanks for your help.

**Comment by andrewwbutler** [comment]
Hi,

I can't see why this would be happening. Could you provide a reproducible example?

**Comment by hffqyd** [comment]
Thans for your reply.

Below is the example code I used.

```R
sample_data = Read10X(data.dir = "outs/filtered_feature_bc_matrix/")

sample = CreateSeuratObject(sample_data, min.cells = min_cells, min.features = min_features, project = "sample")

sample = NormalizeData(sample, normalization.method = "LogNormalize", scale.factor = scale.factor, verbose = FALSE)

sample = FindVariableFeatures(sample, selection.method = "vst", nfeatures = nfeature_variable_feature, verbose = FALSE)

sample = ScaleData(sample, features = allgenes, verbose = FALSE)

sample = RunPCA(sample, features = VariableFeatures(sample), npcs = total_pc, verbose = FALSE)

sample = FindNeighbors(sample, dims = 1:20, verbose = FALSE)

sample = FindClusters(sample, resolution = resolution, verbose = FALSE, random.seed = random.seed)

# set random seed
sample = RunTSNE(sample, seed.use = random.seed, dims = 1:20)

saveRDS(“sample.rds”)

sample = readRDS("sample.rds")

DimPlot(sample, reduction = "tsne")

```

Having import the saved RDS, I did the Dimplot but the resulting plot was different from that before I `saveRDS`.

I had set the random seed used in the `RunTSNE` function, which I supposed caused what happened. But I cannot figure out how to get the same plot by directly doing `DimPlot` without re-doing `RunTSNE`.

Thanks again for your help.

**Comment by andrewwbutler** [comment]
Hi,

In this example, you aren't actually saving anything with your `saveRDS` function call (you only provided the path, not the actual R object). It's possible you read in a different object than the one you thought you saved and that's why you're getting a different plot.
