### ISSUE TITLE
Integrating datasets with Seurat v3

### ISSUE THREAD

**Issue by LuckyMD** [satijalab/seurat#2098]
Hi,

I'm trying to run Seurat v3 data integration with `findIntegrationAnchors()` and `integrateData()`. I'm running this on python 3.7 via `rpy2` version 3.0.5. R version is 3.5.1.

The error I'm getting is:
```
rpy2.rinterface_lib.embedded.RRuntimeError: Error in nn2(data = data.use[anchors.cells2, ], query = data.use, k = k +  : 
  Cannot find more nearest neighbours than there are points
```

This is related to issue https://github.com/satijalab/seurat/issues/2056

I would be grateful for some help. We're trying to compare Seurat to some other algorithms, but have only been able to get it running on some Pancreas datasets. The we have a custom highly variable gene selection method that selects genes that are variable in as many batches as possible.

**Comment by timoast** [comment]
Hi, I think we spoke about this offline. Closing now, feel free to raise a new issue if there are still problems.

**Comment by LuckyMD** [comment]
yes, we've solved this. Thanks again!

**Comment by AteeqKhaliq** [comment]
I am also facing this error , please let me know how best this can be solved.

**Comment by melancholy12** [comment]
Can we use the Seurat v3 or v4 function in the scanpy of python?
