### ISSUE TITLE
CreateSeuratObject automatically removes 0

### ISSUE THREAD

**Issue by jhl0214** [satijalab/seurat#2099]
Can I create a seurat object with keeping 0s from my data?
It seems like 0s are always not included.
Or does it not matter if 0 is included or not?

Thanks.

**Comment by timoast** [comment]
Hi, not sure what you mean here by removes zeros. There are parameters in `CreateSeuratObject` for the minimum number of cells expressing a feature in order for the feature to be kept (`min.cells`) and minimum number of features expressed by the cell for the cell to be kept (`min.features`), both of which are 0 by default.

**Comment by jhl0214** [comment]
Hi,
so if there are 0s in the data frame and I create a seurat object with that data, when I check the seurat object "count" and "data", the 0s are removed. let's say the data frame contains
 [1,2,0,4;    
 8, 2, 0 1]
then the "count" and "data" in the seurat object will have [1, 2, 4, 8, 2, 1].

**Comment by timoast** [comment]
When you print a sparse matrix (which is what Seurat uses to store the counts and data), zeros are displayed as `.`. If you're seeing that the values are actually removed, can you provide a reproducible example?

**Comment by jhl0214** [comment]
Oh, I see what you mean. When I run c@assays[["RNA"]]@counts, it does show 0 as ".". 
 I thought it is removed because c@assays[["RNA"]]@counts@x shows only the values greater than 0. Is the c@assays[["RNA"]]@counts@x  used in all the other calculations? or does it use c@assays[["RNA"]]@counts which also includes 0s?

**Comment by timoast** [comment]
It includes the zeros, this is just how data is stored as a sparse matrix. Storing only the position of the non-zero elements saves space when most of the elements are zero.
