### ISSUE TITLE
Issue with FeaturePlot and AddImputedScore

### ISSUE THREAD

**Issue by baracus37** [satijalab/seurat#210]
Dear Seurat-Team,

I wanted to test the AddImputedScore feature as a means to account for dropout effects of 10X data. When running the pbmc_small example from the documentation and subsequently doing a FeaturePlot with
 
```R
pbmc_small <- AddImputedScore(object = pbmc_small, genes.fit = "MS4A1")
FeaturePlot(pbmc_small,features.plot = "MS4A1", use.imputed = T)
```

works just fine.  when I do the same thing on my own dataset (aligned dataset with ~35k cells) I do get the following error: 

```R
Error in `[.data.frame`(object@imputed, vars.all[gene.check], cells.use,  : 
  undefined columns selected
```

Even though the object@imputed contains the imputed values for the imputed gene.

can anyone help?

Best,

Tobias

EDIT:

I tried to further look into this and from my understanding this error appears to come from `FetchData`, as it appears to me that `FeaturePlot` relies on `FetchData` and when running 

```R
FetchData(object,vars.all = "MS4A1",use.imputed = T)`
```

I get the same error with the following traceback

```R
Error in `[.data.frame`(object@imputed, vars.all[gene.check], cells.use,  : 
  undefined columns selected 
5. stop("undefined columns selected") 
4.`[.data.frame`(object@imputed, vars.all[gene.check], cells.use, 
    drop = FALSE) 
3.object@imputed[vars.all[gene.check], cells.use, drop = FALSE] 
2.t(object@imputed[vars.all[gene.check], cells.use, drop = FALSE]) at <tmp>#26
1.FetchData(test2, vars.all = "MS4A1", use.imputed = T) 
```

**Comment by mojaveazure** [comment]
Hi Tobias,

Are you setting `cells.use` in your `FeaturePlot`/`FetchData` calls? If not, can you send the output of `all(test2@cell.names %in% colnames(x = test2@imputed))`

**Comment by dschrein** [comment]
in my case there are two different delimiters used in how the cell names were constructed with barcode and sample #:

```
> tail(colnames(x = sceData@imputed))
[1] "TTTGGTTCATTCGACA.6" "TTTGGTTGTCTCAACA.6" "TTTGGTTTCTGCCCTA.6" "TTTGGTTTCTTATCTG.6"
[5] "TTTGTCACACATCCAA.6" "TTTGTCAGTCCGTGAC.6"
> tail(sceData@cell.names)
[1] "TTTGGTTCATTCGACA-6" "TTTGGTTGTCTCAACA-6" "TTTGGTTTCTGCCCTA-6" "TTTGGTTTCTTATCTG-6"
[5] "TTTGTCACACATCCAA-6" "TTTGTCAGTCCGTGAC-6"
```
