### ISSUE TITLE
 vector memory exhausted (limited reached?) when applying RunTSNE on matrix creating by  "dist" (create custom distance matrix) on ADT data

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#2103]
Hello, Seurat team,

I'm clustering based on ADT  data, I followed the tutorial on Multimodel vignettes and it said instead of doing PCA, I should use the "dist" to create a custom distance matrix, I did create the dist successfully, however, when I run the RunTSNE one the data, it throw out an error saying " vector memory exhausted (limit reached?)", can you please tell me how to solve this?

**Comment by andrewwbutler** [comment]
Hi,

One alternative to the default `RunTSNE` method, would be to try the `FIt-SNE` implementation of tSNE (via the `tsne.method` parameter). You could also try `RunUMAP` for an alternative visualization strategy.
