### ISSUE TITLE
How I can assignment of precursor cells to adult subtypes after integrating both datasets in Seurat V3? 

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#2104]
Hello,
Recently I have read you paper which called "Developmental diversification of cortical inhibitory interneurons". And I want to follow your pipeline to assign precursor cells to adult subtypes in my data. Since Seurat has updated to V3, IntegrateData has replaced RunCCA-AlignSubspace function. So wondering in this version, how I can assignment of precursor cells to adult subtypes after integrating both datasets?
I read your Script 2_cell_assignment.R in github,and try to modify MapCells function(as shown below) to v3 verison. But because I'm a new PhD and a new comer in R language, I have tried my best and still couldn't finish this task. I will be much appreciated if you can show me the updated code to Perform this function.
Looking forward to your help
![image](https://user-images.githubusercontent.com/30619010/64910566-3f3c9f00-d74a-11e9-9c6e-a2a2eefe1fbe.png)
```
library(pbapply)
# assign precursor cells to adult subtypes
MapCells=function(object, timepoint.dev="P10", timepoint.end="P56", num.k=10, thresh.require=0.9,map.col="AdultTypes1",new.col="Map1") {
  tsne.dims=object@calc.params$RunTSNE$dims.use
  input.dims=GetCellEmbeddings(object,reduction.type = "cca.aligned",dims.use = tsne.dims)
  input.dist=as.matrix(dist(input.dims))
  cells.end=FastWhichCells(object,"DevStage",timepoint.end)
  cells.map=FastWhichCells(object,"DevStage",timepoint.dev)
  map.id=pbsapply(cells.map,function(x)
    names(which(sort(table(object@meta.data[names(sort(input.dist[x,cells.end])[1:num.k]),map.col]),decreasing = T)>=num.k*thresh.require))[1])
  nn.same=pbsapply(cells.map, function(x) length(intersect(names(sort(input.dist[x,])[1:num.k]),cells.map)))
  print(table(map.id))
  map.id[is.na(map.id)]="Unassigned"
  map.id[names(which(nn.same>=num.k*1))]="Unassigned"
  print(table(map.id))
  object@meta.data[cells.end,new.col]=object@meta.data[cells.end,map.col]
  object@meta.data[cells.map,new.col]=map.id
  return(object)
} 
```

**Comment by andrewwbutler** [comment]
Hi,

If you want to run this exact code, you can always install version 2 of Seurat (see instructions [here](https://satijalab.org/seurat/install.html)). One sort of "equivalent" workflow with the v3 functions would be to integrate the datasets (as demonstrated in the vignettes), and run a PCA on the integrated datasets. You could then use the same strategy in that script, just substituting the integrated PCA for the aligned CCA. Another alternative that you could explore would be the label transfer procedure also described in the [integration vignette](https://satijalab.org/seurat/install.html) to classify the E18 precursor cells based on the adult cell subtypes.
