### ISSUE TITLE
How to obtain all genes from all the cells in a subcluster?

### ISSUE THREAD

**Issue by molybdenumt** [satijalab/seurat#2105]
Is there a way to obtain all genes from all the cells in a Seurat object?

I tried FindAllMarkers(object, only.pos=TRUE) but it only seems to find genes that are distinguishing for each of the cluster like CD3D only shows up for 2 clusters out of 5. But when I plot CD3D using FeaturePlot, it shows CD3D in all the clusters.

**Comment by andrewwbutler** [comment]
Hi,

If you want to recover the gene expression matrix, you can use the `GetAssayData` function. If you want to just list all the genes present, you can use the `rownames` function on your Seurat object.
