### ISSUE TITLE
can we show the orig.ident in separate windows by using Seurat

### ISSUE THREAD

**Issue by naixiangxiaozi** [satijalab/seurat#2106]
I'm curious about can we show the orig.ident in sprat windows by using Seurat? Here are my code and the fig I got. Is it possible that I can separate each orig.ident into a single panel like the Loupe Cell Browser can split each org.ident separate in single windows as shown in the fig? 

`DimPlot(whole,group.by = "orig.ident", reduction = "umap"`

![](https://i.stack.imgur.com/oc7hY.jpg)
![image](https://user-images.githubusercontent.com/42306818/64924038-cb2fe480-d7a5-11e9-9212-7827de8ce82d.png)

**Comment by timoast** [comment]
You can use the `split.by` option in `DimPlot`

**Comment by naixiangxiaozi** [comment]
Hi, do you mean that I can use spilt.by="orig.ident"?

________________________________

**Comment by timoast** [comment]
@naixiangxiaozi yes

**Comment by naixiangxiaozi** [comment]
If I used the code below"

DimPlot(whole,spilt.by="orig.ident", reduction = "umap") ", I got the picture that only showed the cluster number as in the screenshot. Is there anything I still need to do?

[cid:19102082-826a-4302-8ade-d865eeb71063]

Best,
Hua

________________________________

**Comment by timoast** [comment]
I don't see the screenshot, but you will need to set `split.by` to whatever column in the Seurat metadata that you want to split the cells by.

You can look at the documentation for `DimPlot` and at the tutorials we have on the Seurat website for more information: https://satijalab.org/seurat/vignettes.html

**Comment by naixiangxiaozi** [comment]
I have tried to reedit the code from the beginning to add the genotype as below:
"

wt@meta.data$genotype<-"WT"

Nkx2_5_KO@meta.data$genotype<-"Nkx2-5-KO"

Shox2_KO@meta.data$genotype<-"Shox2-KO"

Double_KO@meta.data$genotype <-"Double-KO"

"

And using the dimplot with the spilt.by="genotype" as below code:

"

DimPlot(whole,spilt.by="genotype", reduction = "umap")

"

Then it still got the picture in the whole as below:

[cid:549acda1-9e50-41da-b8fe-615049f7359e]


Could you please give me some more advice?


Thank you,

Hua

________________________________

**Comment by timoast** [comment]
Again, the screenshot is not included so it's hard to know what the problem is here. Please attach the plot properly and post the full code you're using.

**Comment by naixiangxiaozi** [comment]
`library(Seurat)
library(dplyr)
library(Matrix)
wt.data <- Read10X("~/Shox2cre_mtmg_S5_GFP/outs/filtered_feature_bc_matrix")
wt <-CreateSeuratObject(count= wt.data, project = "wt_with_GFP",min.cells = 3, min.features = 200)
Nkx2_5_KO.data <- Read10X("~/NKX2_5_KO_GFP/outs/filtered_feature_bc_matrix")
Nkx2_5_KO <-CreateSeuratObject(count= Nkx2_5_KO.data, project = "Nkx2_5_KO_with_GFP",min.cells = 3, min.features = 200)
Shox2_KO.data <- Read10X("~/Shox2crecre_mtmg1_GFP/outs/filtered_feature_bc_matrix")
Shox2_KO <-CreateSeuratObject(count= Shox2_KO.data, project = "Shox2_KO_with_GFP",min.cells = 3, min.features = 200)
Double_KO.data <- Read10X("~/Shox2crecre_Nkx2_5FF_mtmg_S3_GFP/outs/filtered_feature_bc_matrix")
Double_KO <-CreateSeuratObject(count= Double_KO.data, project = "Double_KO_with_GFP",min.cells = 3, min.features = 200)
wt@meta.data$genotype<-"WT"
Nkx2_5_KO@meta.data$genotype<-"Nkx2-5-KO"
Shox2_KO@meta.data$genotype<-"Shox2-KO"
Double_KO@meta.data$genotype <-"Double-KO"
whole <- merge(x = wt, y = list(Nkx2_5_KO, Shox2_KO, Double_KO))
whole[["percent.mt"]] <- PercentageFeatureSet(whole, pattern = "^mt-")
VlnPlot(whole, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), nCol = 3)
plot1 <- FeatureScatter(whole, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(whole, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
whole <- subset(whole, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
whole <- NormalizeData(whole, normalization.method = "LogNormalize", scale.factor = 10000)
whole <- FindVariableFeatures(whole, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(whole), 10)
plot1 <- VariableFeaturePlot(whole)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1, plot2))
all.genes <- rownames(whole)
whole<- ScaleData(whole, features = all.genes)
whole <- RunPCA(whole, features = VariableFeatures(object = whole))
print(whole[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(whole, dims = 1:2, reduction = "pca")
DimPlot(whole, reduction = "pca")
DimHeatmap(whole, dims = 1, cells = 500, balanced = TRUE)
DimHeatmap(whole, dims = 1:15, cells = 500, balanced = TRUE)
ElbowPlot(whole)
whole <- FindNeighbors(whole, dims = 1:10)
whole <- FindClusters(whole, resolution = 0.5)
head(Idents(whole), 5)
whole <- RunUMAP(whole, dims = 1:10)
DimPlot(whole,split_by = "genotype", reduction = "umap")
`
![image](https://user-images.githubusercontent.com/42306818/64998522-1df2c480-d8aa-11e9-9233-6c39738deec8.png)

**Comment by timoast** [comment]
You're using `split_by`, the correct argument is `split.by` (`.` not `_`)

**Comment by naixiangxiaozi** [comment]
Or, sorry for the copy error. Actually, my code is using split.by.
________________________________

**Comment by timoast** [comment]
Can you show the output of `head(whole[[]])`?

**Comment by naixiangxiaozi** [comment]
[cid:1aee41b6-093b-459b-b277-3bf3051723fc]
________________________________

**Comment by mojaveazure** [comment]
@naixiangxiaozi You cannot attach images via email and have them show up here. If you want to paste a screenshot, you have to use the website.

**Comment by naixiangxiaozi** [comment]
![image](https://user-images.githubusercontent.com/42306818/65056503-930bdb80-d936-11e9-8020-6e4a46495a39.png)

**Comment by timoast** [comment]
I can't reproduce this. Can you run this code and show the output:

```r
library(Seurat)
DimPlot(pbmc_small, split.by = 'letter.idents')
sessionInfo()
```

**Comment by naixiangxiaozi** [comment]
![image](https://user-images.githubusercontent.com/42306818/65198810-27b32e00-da4a-11e9-8b1b-8434c8e3939f.png)
and I also have the same Dimplot picture as before.

**Comment by naixiangxiaozi** [comment]
<img width="1440" alt="Screen Shot 2019-09-18 at 7 28 19 PM" src="https://user-images.githubusercontent.com/42306818/65198911-8b3d5b80-da4a-11e9-8187-3920a65bd319.png">
And I got the dimplot picture as before.

**Comment by naixiangxiaozi** [comment]
![image](https://user-images.githubusercontent.com/42306818/65198986-e1aa9a00-da4a-11e9-94b0-313b55485d02.png)
Hi, thank you for your help. And by the way after using "split.by = 'letter.idents' ", I got the same dimplot picture as before.

**Comment by timoast** [comment]
Please enter the exact code shown above and post the entire output here

**Comment by naixiangxiaozi** [comment]
I've using cypress to run Rscript, and got the following session information. And the attached file is the dimplot I got.

R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

Matrix products: default
BLAS/LAPACK: /share/apps/intel_parallel_studio_xe/2015_update1/composer_xe_2015.1.133/mkl/lib/intel64/libmkl_intel_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Matrix_1.2-15 ggplot2_3.2.1 dplyr_0.8.3   Seurat_3.1.0

loaded via a namespace (and not attached):
 [1] nlme_3.1-137        tsne_0.1-3          bitops_1.0-6
 [4] RcppAnnoy_0.0.12    RColorBrewer_1.1-2  httr_1.4.1
 [7] sctransform_0.2.0   tools_3.5.2         backports_1.1.4
[10] R6_2.4.0            irlba_2.3.3         KernSmooth_2.23-15
[13] uwot_0.1.3          lazyeval_0.2.2      colorspace_1.4-1
[16] withr_2.1.2         npsurv_0.4-0        tidyselect_0.2.5
[19] gridExtra_2.3       compiler_3.5.2      plotly_4.9.0
[22] labeling_0.3        caTools_1.17.1.2    scales_1.0.0
[25] lmtest_0.9-37       ggridges_0.5.1      pbapply_1.4-2
[28] stringr_1.4.0       digest_0.6.20       R.utils_2.9.0
[31] pkgconfig_2.0.2     htmltools_0.3.6     bibtex_0.4.2
[34] htmlwidgets_1.3     rlang_0.4.0         zoo_1.8-6
[37] jsonlite_1.6        ica_1.0-2           gtools_3.8.1
[40] R.oo_1.22.0         magrittr_1.5        Rcpp_1.0.2
[43] munsell_0.5.0       ape_5.3             reticulate_1.13
[46] lifecycle_0.1.0     R.methodsS3_1.7.1   stringi_1.4.3
[49] gbRd_0.4-11         MASS_7.3-51.1       gplots_3.0.1.1
[52] Rtsne_0.15          plyr_1.8.4          grid_3.5.2
[55] parallel_3.5.2      gdata_2.18.0        listenv_0.7.0
[58] ggrepel_0.8.1       crayon_1.3.4        lattice_0.20-38
[61] cowplot_1.0.0       splines_3.5.2       SDMTools_1.1-221.1
[64] zeallot_0.1.0       pillar_1.4.2        igraph_1.2.4.1
[67] future.apply_1.3.0  reshape2_1.4.3      codetools_0.2-15
[70] leiden_0.3.1        glue_1.3.1          lsei_1.2-0
[73] metap_1.1           data.table_1.12.2   RcppParallel_4.4.3
[76] vctrs_0.2.0         png_0.1-7           Rdpack_0.11-0
[79] gtable_0.3.0        RANN_2.6.1          purrr_0.3.2
[82] tidyr_1.0.0         future_1.14.0       assertthat_0.2.1
[85] rsvd_1.0.2          RSpectra_0.15-0     survival_2.43-3
[88] viridisLite_0.3.0   tibble_2.1.3        cluster_2.0.7-1
[91] globals_0.12.4      fitdistrplus_1.0-14 ROCR_1.0-7

![image](https://user-images.githubusercontent.com/42306818/65262697-84f1c280-dad0-11e9-8077-79a6fa97377f.png)

**Comment by timoast** [comment]
That UMAP is not from the `pbmc_small` data, so you're either not running the code above or you're not looking at the correct plot.

**Comment by naixiangxiaozi** [comment]
oh, I see. you mean that I need to try the PBMCs_small data? ok, I will try.

Best,
Hua
________________________________

**Comment by naixiangxiaozi** [comment]
Hi here is my output:
![image](https://user-images.githubusercontent.com/42306818/65275699-ce9bd680-daeb-11e9-8a8b-74c11e826776.png)
![image](https://user-images.githubusercontent.com/42306818/65275781-f2f7b300-daeb-11e9-9df2-5cb8e7d81ab5.png)

**Comment by timoast** [comment]
Again, not sure what this is but it's not `pbmc_small`. All you need to do is copy and paste those lines into R and show the resulting plot. Here they are again: 

```r
library(Seurat)
DimPlot(pbmc_small, split.by = 'letter.idents')
```

**Comment by naixiangxiaozi** [comment]
Sorry to ask about this stupid question about do I need to download the pbmc_small data? If so, where to download. If not, did it mean that I need to copy the code you give me to my Rscript.R and run it then give you my output?

**Comment by naixiangxiaozi** [comment]
Hi Tim, I would like to know whether it is a bug or I do something wrong?
________________________________
