### ISSUE TITLE
SCT for a subcluster, got error when RunUMAP

### ISSUE THREAD

**Issue by Thegreatjoyce** [satijalab/seurat#2107]
`cluster11_as_PC <- subset(All.integrated, idents = "11")
table(cluster11_as_PC$orig.ident)

cluster11_as_PC <- SCTransform(cluster11_as_PC, verbose = FALSE, return.only.var.genes = FALSE)

cluster11_as_PC <- RunPCA(cluster11_as_PC, npcs = 30, verbose = FALSE)
cluster11_as_PC <- RunUMAP(cluster11_as_PC, reduction = "pca", dims = 10)`
09:33:59 Read  rows and found  numeric columns
Error in if (n_neighbors > n_vertices) { : argument is of length zero

is there anyone met the same issue?

**Comment by timoast** [comment]
`dims` should be a vector, not a single number, eg `1:10`
