### ISSUE TITLE
subset for SCTransform object

### ISSUE THREAD

**Issue by zinagood** [satijalab/seurat#2108]
Dear Seurat Team!

I'm attempting integration of 18 objects containing 10X scRNA-seq and ADT data. However, I keep getting this error message during PrepSCTIntegration:
"The following assays have not been processed with SCTransform"
... followed by a list of all Seurat objects that I'm trying to integrate.

I checked that the default assay is "SCT", and I did not do any steps after SCTransform, other than adding ADT data and sampling cells. I also updated Seurat to v3.1.0 on 14Sep19.

What could be wrong?

Thanks!!
Zina

**Comment by yuhanH** [comment]
do you subset the object after running SCTransform?

**Comment by zinagood** [comment]
Apologies for the slow reply!
Yes, I used the subset function after SCTransform.
I went around the issue by re-running the analysis and subsetting before SCTransform.
What is the effect of subset that prevents integration?
And would it be possible to apply subset prior to integration in the future?
Thanks!

**Comment by yuhanH** [comment]
Hi,
Current the subset function doesn't subset the parameters generated by SCTransform, so some SCT related functions may not work on the subset object now. But we will fix it soon.

**Comment by zinagood** [comment]
Thanks a lot! Really appreciate you working on it!

**Comment by JingleW** [comment]
> Hi,
> Current the subset function doesn't subset the parameters generated by SCTransform, so some SCT related functions may not work on the subset object now. But we will fix it soon.

Hi, does this mean that if I subset a cluster after integration with SCT transform for further sub-cluster analysis, I need to re-run SCT-transform of the subset data with the assay of "RNA"? Thank you very much.

**Comment by yuhanH** [comment]
`subset` function now works smoothly on the sct integrated data. 
For further sub-cluster analysis, if you need to re-run SCT-transform, it really depends on what questions you have.
