### ISSUE TITLE
batch effect of different donors and different data's 

### ISSUE THREAD

**Issue by tianchen2019** [satijalab/seurat#2109]
I have two batches of single-cell transcriptome data(Smart-seq2) from different laboratories. The experimental procedures in both laboratories are consistent. I use the Seurat's standard process(https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html).
The result is below:
![image](https://user-images.githubusercontent.com/46451175/65026372-03345480-d96b-11e9-9030-24496cfe861d.png)
I want to check batch effect, so I plot the sample's distribution.

![image](https://user-images.githubusercontent.com/46451175/65026489-3a0a6a80-d96b-11e9-8b93-215bab8e08ed.png)
AM and mMPPa are from a lab, and Ryoaged is from anothor lab. AM1 AM2 and Ryoaged used same cell'marker to screen cells through FACS. AM1 and AM2 are two different mice.  We can see there were two clusters between AM and Ryoaged sample, but they used sample markers. Can Seurat remove batch effect of AM and Ryoaged samples? and the batch effect of AM1 and AM2 samples(two different mice) ?

**Comment by yuhanH** [comment]
From your plot, I don't strong batch effect between mice. I don't think you need to remove that batch effect.
For the batch effect between AM1 AM2 and Ryoaged, you can check out our integration vignettes: https://satijalab.org/seurat/v3.1/integration.html
Either Standard Workflow or SCTransform
