### ISSUE TITLE
PCA component values and tSNE coordinates are changing using v3.1 vs 3.0.2

### ISSUE THREAD

**Issue by katsikora** [satijalab/seurat#2110]
Dear Devs,

If I understood correctly, there were no changes in how tSNE reduction is calculated in version 3.1 vs 3.0.2. Is that right?

Because I see quite a dramatic change for my dataset:

a<-as.data.frame(Embeddings(sc_old,reduction="tsne")[,1,drop=FALSE])
b<-as.data.frame(Embeddings(sc_new,reduction="tsne")[,1,drop=FALSE])
plot(x=a$tSNE_1,y=b$tSNE_1[match(rownames(a),rownames(b))])
abline(a=0,b=1,col="red")
![image](https://user-images.githubusercontent.com/7079932/65032928-6ced3800-d944-11e9-8dd8-53efccbf54f4.png)

Can you comment on that?
The ordering of cells has changed, but I've reordered them for the plot.

Looking at the PCA embeddings, some of them have been rotated:

for(i in 1:50){a<-as.data.frame(Embeddings(sc_old)[,i,drop=FALSE]);b<-as.data.frame(Embeddings(sc_new)[,i,drop=FALSE]);print(cor(x=a[,1],y=b[match(rownames(a),rownames(b)),1]))}

[1] 0.9999996
[1] 0.9999994
[1] 0.9999967
[1] -0.9999918
[1] -0.9999864
[1] 0.9999999
[1] -0.9999999
[1] 0.9999973
[1] -0.9999992
[1] 0.9999772
[1] 0.9999137
[1] -0.9998307
[1] 0.9998501
[1] -0.9999943
[1] 0.9993967
[1] -0.9993532
[1] -0.9999966
[1] 0.9999927
[1] -0.9999945
[1] -0.9999882
[1] 0.9999239
[1] -0.9997996
[1] 0.9999299
[1] -0.9998901
[1] 0.9999342
[1] -0.9999263
[1] 0.9999994
[1] 0.9999203
[1] 0.9999785
[1] -0.9997762
[1] -0.999509
[1] 0.9997713
[1] -0.9999076
[1] -0.9999875
[1] -0.9999573
[1] 0.99995
[1] -0.9996946
[1] -0.9996084
[1] 0.9970626
[1] 0.9956678
[1] 0.9997862
[1] 0.9982838
[1] 0.9847808
[1] 0.9866902
[1] 0.9930613
[1] -0.9977248
[1] -0.9983305
[1] -0.9991211
[1] 0.9874065
[1] 0.9903883

Cluster assignments and marker genes are near identical, although the pvalues have changed a bit.

Can you comment on that? Which is now the correct dataset representation, v3.0.2 or v3.1? 

Thanks and best regards,

Katarzyna

**Comment by andrewwbutler** [comment]
Hi Katarzyna,

Sorry for the delayed response. I'm having trouble reproducing this issue. There should be any difference in the PCA values between those two versions. Here's what I did to test that:

```R
# using the pbmc3k.final object from the tutorial
# 3.0.2 - git checkout v3.0.2
# reload the package
load_all("~/software/seurat/")
pbmc3k.final <- RunPCA(object = pbmc3k.final, reduction.name = "pca302")

# 3.1.0 - git checkout v3.1.0
# reload the package
load_all("~/software/seurat/")
pbmc3k.final <- RunPCA(object = pbmc3k.final, reduction.name = "pca310")

# compare the embeddings
all.equal(Embeddings(pbmc3k.final[["pca302"]]), Embeddings(pbmc3k.final[["pca310"]]), check.attributes = FALSE)
[1] TRUE
```

Can you provide an example where these are different? Is is possible something upstream of PCA/tSNE changed when you ran the two examples?
