### ISSUE TITLE
ScaleData() behavior

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#2111]
Hello, I am trying to combine RNA counts from two separate objects, merge them, and then run some tests on the data.

Both objects have been normalized and batch corrected. Additionally they have both been scaled while in: ```DefaultAssay(obj) <- "integrated"```

I combined the objects using ```comb_obj <- merge(obj1, obj2)``` and set the default assay to RNA.

If I run ScaleData(comb_obj) would this have the same behavior as normalizing both objects, merging them, and then scaling the combined object?

Thanks

**Comment by yuhanH** [comment]
One question. After you merge that two objects, do you observe batch effects between obj1 and obj2?

**Comment by kaizen89** [comment]
I have a similar question, when integrating two objects should I scale on variable features of each object separately or run everything on the merged objects?

**Comment by yuhanH** [comment]
You would better scale two objects separately. 
You can have a look at the integration vignettes https://satijalab.org/seurat/v3.1/integration.html.

**Comment by kaizen89** [comment]
Thanks, that was my intuition but the vignettes for Seurat integration and for harmony suggest otherwise.
For Seurat
```
pancreas.integrated <- ScaleData(object = pancreas.integrated, verbose = FALSE)
```
For Harmony
```
pbmcsca <- NormalizeData(pbmcsca) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA(verbose = FALSE)
pbmcsca <- RunHarmony(pbmcsca, group.by.vars = "Method")
```
Is this in agreement with what you suggested?

**Comment by yuhanH** [comment]
For Seurat,
```
for (i in 1:length(pancreas.list)) {
    pancreas.list[[i]] <- NormalizeData(pancreas.list[[i]], verbose = FALSE)
    pancreas.list[[i]] <- FindVariableFeatures(pancreas.list[[i]], selection.method = "vst", 
        nfeatures = 2000, verbose = FALSE)
}
```
When we split the pancreas `merged` objects by the tech, we normalize the data separately.
pancreas.integrated is already integrated. ScaleData here is for the downstream analysis.

**Comment by kaizen89** [comment]
Yes, but normalization is anyway dataset independent, as we normalize by library size of each cell, right? Indeed, for variable features for Seurat it is dataset independent.
Do you have any comments on the Harmony workflow as mentionned above on the Seurat website? where every step is run on the merged objects and not separately.

**Comment by yuhanH** [comment]
You can open a new issue asking the difference of Seurat and Harmony integration, in term of preprocessing individual objects and merged objects.
