### ISSUE TITLE
Error in nbrOfWorkers() : could not find function "nbrOfWorkers"

### ISSUE THREAD

**Issue by whelena** [satijalab/seurat#2112]
I am trying to use PrepSCTIntegration but I keep getting this error with Seurat 3.1.0.

**Comment by xizhihui** [comment]
Hi, you must load the `future` library first.

**Comment by mojaveazure** [comment]
Sorry for the late response; could you provide the code you're using and the output of `sessionInfo()`? Also, could you try restarting your R session to see if that clears things up?

**Comment by whelena** [comment]
Hi I got this to work by adding library(future) so it's all good now. Thank you!
