### ISSUE TITLE
line in "nCount_RNA" vs "percent.mt" graph

### ISSUE THREAD

**Issue by beamaraba** [satijalab/seurat#2113]
Hi,

I was trying ti include a line in the graph "nCount_RNA" vs "percent.mt" graph made with the FeatureScatter function. It worked before with Seuratv2 using abline but I can not do it now with seurat3. There is any way to do it?
Perhaps this is a silly question but I am new in R and I do not have any experience in coding. 

Thanks

**Comment by yuhanH** [comment]
FeatureScatter will generate a ggplot object. 
You could add line in FeatureScatter as the way adding line in the ggplot.
Here is a website showing how to add line in the ggplot:
http://www.sthda.com/english/wiki/ggplot2-add-straight-lines-to-a-plot-horizontal-vertical-and-regression-lines
