### ISSUE TITLE
DE SCTransform 

### ISSUE THREAD

**Issue by rleonriv** [satijalab/seurat#2115]
Hi, 

I have performed SCTransform and Integration on 5 samples setting the option return.only.var.genes = FALSE and integrating based on the intersect between all genes. I have run DE using the following 2 codes
1: DefaultAssay(samples.integrated) <- "RNA"
DE_markers_RNA <- FindAllMarkers(object = samples.integrated, logfc.threshold = 0.25)
2:DefaultAssay(samples.integrated) <- "SCT"
DE_markers_SCT <- FindAllMarkers(object = samples.integrated, assay = "SCT", slot = "scale.data", logfc.threshold = 0.25)

On previous posts it had been mentioned that the DE genes should be giving similar results regardless of whether we perform DE on the SCT or on the RNA but from a first glimpse I am not getting similar genes or p_val_adj. 

My questions are:
1)Do I have a mistake in my command for the DE_markers_SCT that makes my results different? If so, how would it be an appropriate way to code it? 
2)I understand that the results from DE when using SCT scaled data does not make sense to get the avg_logFC, but would it be possible to explain what avg_dif means? 
3)How could one interpret the avg_dif values to choose for significant ones (similar to setting cutoffs for avg_logFC to 1.5 or 2 depending on stringency?

Thank you

**Comment by satijalab** [comment]
We can't guarantee that the two methods will give similar results, although we often see similar genes at the top of the marker list regardless of precisely what DE method was used.

One thing I will add is that SCTransform (by default)  only stores pearson residuals for 3,000 variable features, to save memory. So performing DE on the scale.data slot of this assay means you are only testing 3,000 genes. Performing DE on the RNA assay (or on the data slot of the SCT assay) will test all genes.

**Comment by rleonriv** [comment]
Thank you! Additionally: 

3)How could one interpret the avg_dif values to choose for significant ones (similar to setting cutoffs for avg_logFC to 1.5 or 2 depending on stringency?

**Comment by JingleW** [comment]
> integrating based on the intersect between all genes

Hi, rleonriv, 
In the sentence "integrating based on the intersect between all genes", do you mean that in the procedure of "SelectIntegrationFeatures", the nfeatures was set to be the "intersect between all genes" of all the samples used for integration?
Thank you.
