### ISSUE TITLE
DietSeurat keep reductions and graph

### ISSUE THREAD

**Issue by Jemkon** [satijalab/seurat#2116]
Hello,

I am trying to slim Seurat object using DietSeurat function. It was working fine with Seurat v3.0.0 with following command.

    scObj.slim <- DietSeurat(scObj, counts = TRUE, data = TRUE, scale.data = FALSE)

But now with Seurat v3.1.0 this function has changed and removes reduction and graph by default. How do I specify to keep reductions and graph using DietSeurat function? 

I tried following command but didn't work.

    scObj.slim <- DietSeurat(scObj, counts = TRUE, data = TRUE, scale.data = FALSE, dimreducs = c('pca','tsne','FItSNE','umap'))
 
Many thanks,

**Comment by andrewwbutler** [comment]
Hi,

The second command you posted should work to keep the `DimReduc`s that you specified. I am not able to reproduce this on my end. Can you try testing from a fresh R session/Seurat install? If the issue persists, could you provide a reproducible example alongside your sessionInfo?
