### ISSUE TITLE
Empty markers for some clusters after integration + clustering

### ISSUE THREAD

**Issue by mxposed** [satijalab/seurat#2117]
Hello,

We've integrated a set of datasets with a standard workflow (https://satijalab.org/seurat/v3.1/integration.html) and then ran clustering on integrated object. Then, we switched to `RNA` assay to see the markers for all the clusters, but `FindAllMarkers` have found no genes for some of the clusters.
I wonder if this is an expected behaviour or is something wrong?
What would be your advice on how to find out what drives those clusters’ separation?

We're using version 3.1.0

P.S. Thank you for the great tool

**Comment by timoast** [comment]
Sorry for the delay, what are you trying to find markers between? If they are well-defined clusters I would expect there to be differentially expressed genes present, but if the data is overclustered it's possible that no significant markers exist
