### ISSUE TITLE
Adjusting VlnPlot 

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#2118]
Hi folks,

I have a VlnPlot produced using:

`VlnPlot(object = corx, features = "nCount_RNA", group.by = "sample", log = T, adjust = 1, y.max = 9000) + NoLegend()`

and the plot looks like this:

![VLNplot test](https://user-images.githubusercontent.com/49162517/65323007-90182180-dba8-11e9-8be3-54d2e20a5194.jpeg)

I would like to narrow scattered points (cells) in VlnPlot i.e. to look something like this:

<img width="510" alt="Screenshot 2019-09-20 at 13 18 11" src="https://user-images.githubusercontent.com/49162517/65323409-9529a080-dba9-11e9-8bc8-d4af9f63207a.png">

I couldn't find any argument for that option in default Seurat's VlnPlot() function. 
Is there a way to do that?

Also, when the argument `log = TRUE`,  the argument `y.max ` cant be used, or?

Thank you in advance for your help.

Best regards,
Amel Zulji

**Comment by yuhanH** [comment]
HI, 
Currently, seurat doesn't support the Violin plot you suggested.
In case you think the dot size is too big and it overlap the distribution shape, you can adjust `pt.size` or set it to zero.
