### ISSUE TITLE
FindIntegrationAnchors error when using reference based integration: 'x' must be atomic 

### ISSUE THREAD

**Issue by awaickm1** [satijalab/seurat#2119]
Good morning Seurat team!

I'm running into an error when I attempt to run FindIntegrationAnchors on an SCTransformed dataset using the 'Reference-based’ integration workflow. It seems to be related to the reference-based workflow aspect, since I can start FindIntegrationAnchors without the 'reference' option without any issues.

> immune.anchors <- FindIntegrationAnchors(object.list = immune.list, normalization.method = "SCT", anchor.features = immune.features, reference = reference_dataset, verbose = TRUE)

Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic

> traceback()
6: stop("'x' must be atomic")
5: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4: sort.default(x = reference)
3: sort(x = reference)
2: unique(x = sort(x = reference))
1: FindIntegrationAnchors(object.list = DHIM_thai.immune.list, normalization.method = "SCT", 
       anchor.features = immune.features, reference = reference_dataset, 
       verbose = TRUE)

**Comment by yuhanH** [comment]
Have you updated the seurat develop branch into latest version?
