### ISSUE TITLE
using tsne vs Rtsne

### ISSUE THREAD

**Issue by guilhermesena1** [satijalab/seurat#212]
Is there an advantage in using tsne instead of Rtsne for reduction? I was curious why both options are available and that tsne is default given that it is much slower. Also, if add.iter = T only tsne is available though we can add iterations in Rtsne too. Was that a design choice? This becomes an issue for larger datasets (20k+ cells) if the default 1000 iterations from Rtsne aren't enough for convergence. 

Thank you in advance!

**Comment by satijalab** [comment]
We use the barnes-hut tSNE implementation primarily for speed and scalability to large datasets. The default number of iterations is set by the package designers, though indeed with the Rtsne implementation you can add more iterations if you like

**Comment by wyattmcdonnell** [comment]
Hi @satijalab—were y'all aware that there are some flaws with the tsne package and how it's implemented that aren't present in the Rtsne package? This could cause some serious issues in downstream analysis for users who aren't familiar with how t-SNE operates (which is a lot of people). 

http://www.bioinformatics.babraham.ac.uk/tsne/

**Comment by leonfodoulian** [comment]
Hi Wyatt,

Thank you for sharing the link. However, it would also be useful for readers to mention that Seurat uses `Rtsne` by default (contrary to what was mentioned by @guilhermesena1). `tsne` is used if `do.fast = FALSE`, or if `add.iter > 0` (both of which are not met if default settings are used). For more details, please check [lines 283 to 304 in dimensional_reduction.R](https://github.com/satijalab/seurat/blob/master/R/dimensional_reduction.R#L283-L304).

Best,
Leon

**Comment by wyattmcdonnell** [comment]
Thanks and great point @leonfodoulian! Maybe the way to address this in a future version would look something like the following: 

1. Remove support for the ```tsne``` package in Seurat
2. Set ```do.fast = FALSE``` to send the additional flag ```theta = 0``` to the ```Rtsne``` package, which runs full t-SNE via ```Rtsne``` instead of the Barnes-Hut implementation. 

This way people are using the (much) faster ```Rtsne``` package anyways and won't have to go back and double-check if their embeddings are correct. Just my 2¢ :) Have a good one!

**Comment by leonfodoulian** [comment]
Thats a good way to avoid the issue presented in the link you shared! You can submit a pull request for this if you're interested in getting it done quickly. 

Have a good one too!

Best,
Leon
