### ISSUE TITLE
Calculate DEG in a certain cluster

### ISSUE THREAD

**Issue by firhn** [satijalab/seurat#2120]
I am a new user of Seurat, and I'd like to know how to correctly calculate the DEG from a certain cluster/sub-population?
Here are some basic description about the data I have and the steps I use - 
Samples: 3 control samples and 3 case/disease samples
Steps:
1) In the first several steps, I used FindVariableFeatures() followed by FindIntegrationAnchors(...anchor.features = 1000...) and IntegrateData() to make a Seurat object (1000 gene x 36000 cells from 3+3 samples) 
2) In the next steps, I got the 11 clusters in the tsne plot  
3) subset() to get the cells in a Cluster1, and Idents(Cluster1)=Cluster1@meta.data$Group to divide case and control
4) Then shall I used a) or b) or some other method to calculate DEG?
a) deg_1000 <- FindMarkers(hsc, ident.1 = "ctrl", ident.2 = "case", verbose = FALSE)  
b) deg_all <- FindMarkers(hsc, ident.1 = "ctrl", ident.2 = "case", verbose = FALSE, assay="RNA") 
As in a) the max number of genes I have is 1000, but from the original assay "RNA", I have totally ~20K genes, for which I want to know the pattern of gene expression changes. 
Am i doing right here? Please help ~

**Comment by timoast** [comment]
Hi, we cover a lot of this in our vignettes online. I would recommend checking out [this](https://satijalab.org/seurat/v3.1/immune_alignment.html) vignette first. We also recommend running differential expression on the uncorrected data (not using the integrated assay), so you should set `assay = "RNA"` as in (b)
