### ISSUE TITLE
Reorder samples on violin plot

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#2121]
Plot order VlnPlot #454

How do we reorder samples on violin plots for V3?

Thanks!

**Comment by AndyR2** [comment]
this works for me

object_copy <- object
my_levels <- c(set_custom_order_of_clusters)
factor(Idents(object_copy), levels= my_levels)
Idents(object_copy) <- factor(Idents(object_copy), levels= my_levels)

VlnPlot(object_copy, features = c("some_gene"), point.size.use = 0.25)

**Comment by yuhanH** [comment]
Thanks Andy!
