### ISSUE TITLE
Setting seed for UMAP in Seurat v3.0

### ISSUE THREAD

**Issue by rushikapandya** [satijalab/seurat#2124]
Hello,

I had used seurat v3.0.1 for my scRNA-Seq data and had made plots. Now, when I run the same script after a month I notice that my Umap plot looks different. It does not make my results seem consistent. 
1. Does this mean my clusters change in terms of the cells and cell number everytime I run Umap?
2. Can I manually set the seed so that I can get the same plots and make my experiment reproducible?

Thank you,

Rushika

**Comment by Thegreatjoyce** [comment]
Having the same issue.

**Comment by MichaelStber** [comment]
Hello @rushikapandya .

I assume your R version hasn't change in that time frame?
Sorry for this banal question but I observed difference in the past when I used Seurat v3 when my R version was updated once.

Best,
Michael

**Comment by mojaveazure** [comment]
Hi Rushika,

Sorry for the delay; while the cluster identity of individual cells can vary based on the seed provided to `FindClusters`, it shouldn't change the number of clusters and the markers used to identify them.

You can indeed set a seed in `RunUMAP`, [as seen in the docs](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/RunUMAP) for the function. However, I recommend you upgrade to the newest version of Seurat to take advantage of an R-native implementation of UMAP, which we've found to accept a seed value more reliably than the old Python/reticulate implementation. The R-native UMAP is present in Seurat v3.1.0 and later.
