### ISSUE TITLE
FindClusters returns same results despite changing seed

### ISSUE THREAD

**Issue by aselewa** [satijalab/seurat#2125]
Hello,

I am trying to perform cluster stability analysis by writing a wrapper for FindClusters in order to choose an optimal resolution. I am using the default louvain algorithm.

However, I am finding that FindClusters returns exactly the same labels despite changing the seed, random number of starts, and changing the algorithm used.

Is this expected? When I run other clustering algorithms such as kmeans I get slightly different results with each iteration. 

Any insight is appreciated.
Thanks.

**Comment by timoast** [comment]
Hi, sorry for the delay. This is not expected, are you able to provide a reproducible example?
