### ISSUE TITLE
RunUMAP error: Error: invalid version specification ‘NA’

### ISSUE THREAD

**Issue by peaceisking** [satijalab/seurat#2127]
I have already tried 

> "pip install umap-learn" 
![image](https://user-images.githubusercontent.com/46219838/65381420-7fd88180-dd23-11e9-91a1-f8e80c988e9b.png)

> pip3 install umap-learn
![image](https://user-images.githubusercontent.com/46219838/65381439-d47bfc80-dd23-11e9-92a7-0978be2d89ba.png)

  and
 > reticulate::py_install(packages ='umap-learn'), 

![image](https://user-images.githubusercontent.com/46219838/65381405-325c1480-dd23-11e9-8517-5f9a5a03bef8.png)

and they can run normally 

but,   everytime I try runUMAP like this 

> day7_sctransform <- RunUMAP(object=day7_sctransform, dims = 1:50)  

   The result is 

>  Error: invalid version specification ‘NA’
![image](https://user-images.githubusercontent.com/46219838/65381412-4dc71f80-dd23-11e9-8458-c0ece3f68ac1.png)

so how can I resolve the problem?Thanks

**Comment by mojaveazure** [comment]
As stated [previously](https://github.com/satijalab/seurat/issues/1761#issuecomment-506865850), we've noticed many issues with `RunUMAP` and Anaconda Python. Please do not use Anaconda with Seurat, it doesn't work as well as using your system's provided Python installation or any of the official [CPython](https://www.python.org/) installations.

Also, with [Seurat v3.1.0](https://github.com/satijalab/seurat/releases/tag/v3.1.0), we've introduced support for UWOT, an R/C++ implementation of UMAP. If you continue to have issues with Python UMAP, we recommend using this.
