### ISSUE TITLE
Expose hidden parameters of SCTransform

### ISSUE THREAD

**Issue by rspreafico-vir** [satijalab/seurat#2128]
Hi there,

currently `SCTransform` internally calls functions that may reduce the dimensionality of the barcode-feature expression matrix. For example, it internally filters for genes expressed in at least 5 cells, even if the original Seurat object was constructed with no such filter. This procuces a dimensionality mismatch between the `RNA` and the `SCT` assay. Exposing hidden parameters to the user (with defaults) would allow documenting the inner workings of the function, as a side effect. For the specific gene filter based on expression cell count I am mentioning here, I wonder whether in addition this should be reconciled with the original selection made when building the Seurat object.

There may be other parameters that also influence outcome and are not immediately visible to the end user, which could be exposed as well.

Thank you!

**Comment by yuhanH** [comment]
Hi, 
The hidden parameters you mentioned are described here 
https://github.com/ChristophH/sctransform
Also, the parameters calculated in the process are also stored in the  object[["SCT"]]@misc$vst.out

**Comment by rspreafico-vir** [comment]
Understood, but indeed I did not open an issue with `ChristophH/sctransform`, but with `satijalab/seurat`. Most people will access `sctransform` via the Seurat-provided `SCTransform` wrapper, as opposed to the `vst` function from `sctransform`. This is also how the Seurat documentation suggests to run normalization. So the wrapper is missing parameters of the function that it is wrapping. Having those defined explicitly (with defaults) in `SCTransform` would greatly help. The case of `min_cells` is particularly obvious since there is a matching parameter in `CreateSeuratObject`. So if one follows the Seurat documentation, he/she may set `min_cells` in `CreateSeuratObject`, only to be overridden without notice by the very same, yet undescribed parameter in `SCTransform`.

**Comment by rleonriv** [comment]
Is there any way to change the min_cells from the sctransform::vst function via Seurat? I have tried but have been unsuccesful...

I am finding that a gene of interest is getting excluded after integration because 1 sample has less than 5 cells expressing such transcript (4 cells express it instead of 5) and I would greatly appreciate to be able to change this if possible.

**Comment by satijalab** [comment]
Apologies for the confusion and slow reply here. Any extra arguments passed into SCTransform will get passed into the vst call, so you can simply set min_cells and this will pass through. The same applies to other parameters of the vst function.

For example,
```
pbmc <- SCTransform(pbmc,min_cells=3)
```
