### ISSUE TITLE
 vector memory exhausted  when running SCTransform on IntegrateData

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#2132]
Hello, 
I have a merged sample that contains 30000 cells, I run the integration pipeline on the sample and then apply SCTransform, however, when i perform IntegratedData on the sample, The error" vector memory exhausted" show up. Below is my code:

`options(future.globals.maxSize = 4000 * 1024^2)

mixedCell.list <- SplitObject(projectB.merged, split.by = "ident")

for (i in 1:length(mixedCell.list)) {
  mixedCell.list[[i]] <- SCTransform(mixedCell.list[[i]], verbose = FALSE)
}
mixedCell.features <- SelectIntegrationFeatures(object.list = mixedCell.list, nfeatures = 2000)
mixedCell.list <- PrepSCTIntegration(object.list = mixedCell.list, anchor.features = mixedCell.features, 
                                    verbose = FALSE)

mixedCell.anchors <- FindIntegrationAnchors(object.list = mixedCell.list, normalization.method = "SCT", anchor.features = mixedCell.features, verbose = FALSE)
 mixedCell.integrated <- IntegrateData(anchorset = mixedCell.anchors, normalization.method = "SCT", 
                                       verbose = FALSE)
 `
I tried the solution online such as set R_MAX_VSIZE=16GB, but it doesn't solve the problem. The laptop I'm using is a 256GB 16GM memory Macbook pro. And I didn't encounter this error when I apply log normalization(Standard normalization pipeline) on the IntegrateData.

**Comment by JTR634** [comment]
Hello, Yunzhe!
I'm not one of the developers, pardon me. Just curious, are you using the newest development version of Seurat? If you check the R code of  `IntegrateData`, you may find that integration + SCTransform is performed directly with the Pearson residuals which make matrix dense, while standard integration is still performed with the sparse matrix of LogNormalized values. May this explain help you.

Yuchen

**Comment by YunZheHuang** [comment]
@JTR634 
Hello, Yuchen,
Yes, I think I'm using the newest version of Seurat. Thank you so much for your explanation. However, do you have any suggestion how can I fix this issue?

**Comment by JTR634** [comment]
Hello, Yunzhe!
If you mean to do it on your laptop, I think you could try using virtual memory which I'm doing to 
my laptop although that could do harm to your hardware. Actually the `IntegrateData` create a bit many objects within its function enviroment, maybe you could try forking their package and optimizing the R code to add `rm()` and `gc()` between some steps to free the memory.

**Comment by YunZheHuang** [comment]
@JTR634 
Thank you!

**Comment by yuhanH** [comment]
Hi, Yunzhe
We did some change of data structures of the SCT normalized objects. It should take less memory. 
Is your issue solved?
