### ISSUE TITLE
Realloc error when running IntegrateData()

### ISSUE THREAD

**Issue by whelena** [satijalab/seurat#2133]
I am running analysis on a dataset from 3 sequencing runs (~6.9 GB) and I keep getting the error:
Error in asMethod(object) : 
  'Realloc' could not re-allocate memory (562272000 bytes)

I am wondering if this is a problem with the dataset or the memory available in the local computer.

**Comment by ogarmar3** [comment]
Definitely sounds like you run out of memory

**Comment by timoast** [comment]
Yes it sounds like you are running out of RAM. You can try reciprocal PCA for integration, which should use less RAM: https://satijalab.org/seurat/v3.1/integration.html
