### ISSUE TITLE
RNA is not an assay present in the given object. Available assays are: ToIntegrate

### ISSUE THREAD

**Issue by mduan31** [satijalab/seurat#2135]
Hi All,

I was trying to rerun my previous integration analysis, but I found that Seurat updated the 'FindIntegrationAnchors' function and I couldn't rerun it successfully. Following is my error message:

![image](https://user-images.githubusercontent.com/55726202/65477828-89fa9d00-de55-11e9-8698-11be61398418.png)

Then, I digged into the source code of the function, but I couldn't find any print messages for 'Merging objects', only a print message for 'Merging dataset'. I'm confused as to which part of the function is giving me the error.

Additionally, I couldn't find a "GetAssay.Seurat" function but I did find one named "GetAssayData" so I'm not sure how to proceed with debugging for my current analysis.

My current R version is R/3.6.0 and Seurat version is 3.1.0.

Thanks in advance!

Best,
Michelle

**Comment by mojaveazure** [comment]
Hi Michelle,

The error states that it's trying to pull an assay named "RNA" which is not present in one of your objects. Please ensure the assay that you want to integrate in your each of your objects is named the same across all your objects (eg. if you want to integrate the "ToIntegrate" assay in one object, ensure the corresponding assays in your other objects are also called "ToIntegreate") and pass that as the `assay` parameter to `FindIntegrationAnchors`.

As for `GetAssay.Seurat`, this is a method for `GetAssay` on `Seurat` objects. You can quickly view the code in R using [`getAnywhere`](https://www.rdocumentation.org/packages/utils/versions/3.6.1/topics/getAnywhere)
