### ISSUE TITLE
FeaturePlot integrated data show negative values

### ISSUE THREAD

**Issue by bruselly** [satijalab/seurat#2136]
I integrate 3 data into one object ,and then i use FeaturePlot function .However ,I found the expression range of  cells show negative values ,so the picture is  bad ,and i can't see the result clearly .
Just like this :
![1](https://user-images.githubusercontent.com/41354365/65517390-394a7900-df15-11e9-85b9-defa1b1dca62.PNG)

**Comment by yuhanH** [comment]
Right. It is possible. 
Thus, `integrated` assay is only used to identify cell types. For other analysis, such as visualization and differential analysis, we don't suggest you use the `integrated` assay. 
You would better use `RNA` assay.
