### ISSUE TITLE
Normalized matrix to use for FeaturePlot post CCA

### ISSUE THREAD

**Issue by parveendabas** [satijalab/seurat#2137]
Dear Seurat Developers

Post CCA batch correction, I obtained the UMAP coordinates and wanted to visualize a gene X using FeaturePlot. 

Because, UMAP was run on CCA-corrected data, is it correct to use data/scaled.data only from the "CCA-corrected assay" for featurePlot or I can also use "RNA" assay to extract data/scaled.data to visualize gene X in FeaturePlot?

**Comment by yuhanH** [comment]
Hi,
For the FeaturePlot, you should use RNA assay. 
The CCA-corrected data is mainly designed to help you eliminate batch effects and find cell types.
