### ISSUE TITLE
Cell Name Duplicate Error -- Even after RenamingCells

### ISSUE THREAD

**Issue by mthimma** [satijalab/seurat#2139]
Dear Satija's lab,

I am using Seurat 3 for my data analysis. I have three seurat objects and renamed the cells in each object with unique name.

While findintegrationanchors it throws a warning message :
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

After ignoring this warning, the umap plot for each group has one more 'NA' group too.

How to resolve this 'NA' group in my data?

**Comment by andrewwbutler** [comment]
Hi,

Can you post a reproducible example? It doesn't sounds like the renaming worked if you're seeing that warning message.  How are you grouping the cells in the UMAP plot? Do any of the cells have NA values for that grouping variable in the original objects before integration?
