### ISSUE TITLE
Mismatch between FindClusters default and the FindClusters documentation

### ISSUE THREAD

**Issue by andrewhill157** [satijalab/seurat#214]
In the documentation for FindClusters, the following description is provided:
```
#' Identify clusters of cells by a shared nearest neighbor (SNN) modularity
#' optimization based clustering algorithm. First calculate k-nearest neighbors
#' and construct the SNN graph. Then optimize the modularity function to
#' determine clusters. For a full description of the algorithms, see Waltman and
#' van Eck (2013) \emph{The European Physical Journal B}.
```

However, as best as we can tell from the code, this function defaults to calling the standard Louvain algorithm, rather than option 2 (with modularity optimization) or option 3 (the 2013 method cited). Not sure if this is a misunderstanding on our part, but wanted to let you know just in case!

**Comment by satijaml** [comment]
Thanks! Yes that is correct, we run Louvain (which also aims to optimize modularity) as a default, but in have used the alternative algorithms in other cases, and want to leave those options open to the user. We will clarify further in the docs to avoid confusion.

**Comment by andrewhill157** [comment]
Totally makes sense and thanks very much for clarifying!
