### ISSUE TITLE
Integrated vs. RNA assay for CellxGene

### ISSUE THREAD

**Issue by rosalinamae** [satijalab/seurat#2142]
I am working with an integrated Seurat object, comparing samples from different conditions. I understand for the pca/clustering I should work with the integrated assay, and later on use the RNA assay for any differential expression analysis.

My question is, which assay should I use for CellxGene, which has its own differential expression function. When I export the seurat object to a loom object, and later convert to H5AD for cellxgene, my understanding is that it will export the integrated assay. Exporting the RNA assay will not work for cellxgene because there was no clustering done on this assay.

It seems I am left with the choice of either using the integrated assay, which will be problematic when using the differential expression function within CellxGene, or skipping the integration step during the seurat workflow, which carries its own issues.

Any suggestions are appreciated! Thank you so much.

**Comment by timoast** [comment]
I would suggest running the integration and creating the clustering and reduced dimensions you want (eg, tSNE or UMAP), and saving these as well as the uncorrected RNA assay
