### ISSUE TITLE
Hclust error in "IntegrateData" function

### ISSUE THREAD

**Issue by EraslanBas** [satijalab/seurat#2143]
Hi,
I am integrating 37 different data sets but I get an error in hclust function called in IntegrateData function:

> my.anchors <- FindIntegrationAnchors(object.list = samps)
>IntegrateData(anchorset = my.anchors, dims = 1:50)

Error in hclust(d = dist.mat) : 
  NA/NaN/Inf in foreign function call (arg 10)

The samples are normalized beforehand as follows:

>serObj <- NormalizeData(serObj, verbose = FALSE)
>serObj <- FindVariableFeatures(serObj, selection.method = "vst", nfeatures = 2000)

Would you mind helping me with this issue?

**Comment by andrewwbutler** [comment]
Hi,

Are you able to provide a reproducible example?
