### ISSUE TITLE
how to use Seurat to find the same expression gene between two cluster?

### ISSUE THREAD

**Issue by naixiangxiaozi** [satijalab/seurat#2144]
Hi, it is all know that we can easily to get the different gene expression profile by using Seurat function FindMarkers. And I would like to know can we get the same expression gene between two cluster?

Thank you,
Hua

**Comment by yuhanH** [comment]
You could find the differential genes between these two clusters. Then, the un-differential genes can be considered as the similar expression across two clusters.
