### ISSUE TITLE
CreateSeuratObject for aggregate cells

### ISSUE THREAD

**Issue by siyunw** [satijalab/seurat#2145]
Hi, When I CreateSeuratObject for aggregate cells using the singlecell.csv, I got this following:
Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features) : 
  No cell names (colnames) names present in the input matrix

I checked the number of columns in the individual singlecell.csv vs 10x genomics aggregated singlecell.csv, there are missing columns 
![image](https://user-images.githubusercontent.com/14063363/65733965-bb59af80-e085-11e9-876b-40ef1dfc69a8.png)
![image](https://user-images.githubusercontent.com/14063363/65733986-c4e31780-e085-11e9-9bcf-5c47dbaf1857.png)
how should i load the correct format of singlecell csv for the aggregate of two cell types?

Thank you!

**Comment by timoast** [comment]
Hi, if you are trying to create a Seurat object using the singlecell.csv file from cellranger atac you need to instead use the count matrix. See the Signac package for more information about loading and analyzing scATAC-seq data: https://github.com/timoast/signac

**Comment by nbahlis** [comment]
Hello Siyunw

Did you figure out how to run Signac on a cell ranger aggr object. I ran into similar errors
