### ISSUE TITLE
How to use cell-cycle-scoring with SCTransform?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#2146]
Hi @satijalab ,

Since this question **#1679** is very relevant to me (and potentially many others), I would like to ask this again, as the #1679 issue is now closed.

https://github.com/satijalab/seurat/issues/1679#issuecomment-535997040

Would be great if @satijalab could please comment on the point raised by @atermanini in #1679.

Many thanks!

**Comment by satijalab** [comment]
Closing this issue as I responded a couple weeks ago to #1679. Again, this is a case where there is no 'best' answer, but as long as you understand what each step is doing, you can make an informed decision on how to move forward.
