### ISSUE TITLE
Cell cycle effect still can't be removed on integrated data 

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#2148]
Hello Seurat team :
 I try to regress out cell cycle effects of Radial glia cells from my mouse brain data(picture 1). So I subset the  Radial glia cells and do regress following [your tutorial](https://satijalab.org/seurat/v3.1/cell_cycle_vignette.html). But it seems that only the difference between the G2M and S phase scores is removed,and signals separating non-cycling cells and cycling cells still be maintained(picture 2-2). Because my data is integrated data, i doubt that the 2000 integrated variable features didn't include enough cell cycle genes. So I verify it by comparing  these features with cc.genes your tutorial provided.The code is as follows:
`
```
>   length(cc.genes)
[1] 97
>   length(s.features)
[1] 43
>   length(g2m.features)
[1] 54
>   length(x = which(x = cc.genes %in% rownames(x = GetAssayData(RGCcell))))
[1] 66
>   length(x = which(x = s.features %in% rownames(x = GetAssayData(RGCcell))))
[1] 23
>   length(x = which(x = g2m.features %in% rownames(x = GetAssayData(RGCcell))))
[1] 43`

```
The result suggest cell cycle genes are indeed not all included.So I follow your advice on this post and integrate RGC cells subset from all data again.
As you suggected,when running IntegrateData, we need to integrate all features, not just the variable genes. But setting features.to.integrate to be equal to all genes makes the integrated object too big and consumes system memory.So I intersect the cc.genes which exist in all the 
datasets with 2000 IntegrationAnchors and get  2012 final genes. And I set features.to.integrate to these genes.This ensures that the integrated assay will keep values for cell cycle genes. However, the result didn't improve at all(picture 3-2).
```
The integration pipeline:
DefaultAssay(RGCcell) <- "RNA"
RGC.list <- SplitObject(RGCcell, split.by = "time")
for (i in 1:length(RGC.list)) {
  RGC.list[[i]] <- NormalizeData(RGC.list[[i]], verbose = FALSE)
  RGC.list[[i]] <- FindVariableFeatures(RGC.list[[i]], selection.method = "vst", nfeatures = 2000, 
                                          verbose = FALSE)
}
RGC.anchors <- FindIntegrationAnchors(object.list = RGC.list, dims = 1:30)
RGC.ccgenes <- intersect((rownames(x = GetAssayData(RGCcell,assay = "RNA"))),cc.genes)
features.to.integrate =union(RGC.anchors@anchor.features,RGC.ccgenes)
RGC.integrated<- IntegrateData(anchorset = RGC.anchors, dims = 1:30,features.to.integrate =features.to.integrate)
RGC.integrated`
```
Why cell cycle effect can't be removed in my data? Why signals separating non-cycling cells and cycling cells still be maintained? Is it normal for Radial glia cells?Do you have any suggestions on my analysis?

**Comment by MichaelStber** [comment]
I observed same effect on one of my datasets after doing cell cycle regression.
I would be interested in an explanation as well.

Best,
Michael

**Comment by olechnwin** [comment]
I am having the same problem. Hoping to get some advice as well.

**Comment by satijalab** [comment]
I apologize that we never responded here. The workflow you presented  above  makes sense, to ensure that cc genes are included in integration. Afterwards,  you can calculate cell cycle  scores based on the integrated dataset, and regress these out  using ScaleData (after integration).

It appears this is not solving  your  problem though. The only additional advice I can offer  is  to exclude PCs that are  driven by cell-cycle  genes from  your final clustering and visualization analyses.

**Comment by alanlamsiu** [comment]
I also got a similar problem recently. I tried both incorporating all cell cycle genes or excluding the PC corresponding to cell cycle genes, but neither could work. Then I used 4,000 variable features for integration and the cell cycle effect could be regressed out.
