### ISSUE TITLE
order.by.ident in DoHeatmap

### ISSUE THREAD

**Issue by cynthiazhou1005** [satijalab/seurat#215]
I found out the order.by.ident option is not used anymore in the DoHeatmap function. I had identified a few clusters and would like to put them in specific orders for displaying purpose. I was able to change the 'ident' using overwrite factor. But the plots still doesn't show up as right order. How can I change the heatmap cluster order?
Thanks!

**Comment by andrewwbutler** [comment]
If you want to install the [development version](http://satijalab.org/seurat/devinstall.html), we've added a parameter to `DoHeatmap` called `group.order` which allows you to specify the order the clusters will appear. You could also try manually changing the factor level order of `object@ident` to match your desired ordering.

**Comment by twmccart** [comment]
This is still a problem that should be fixed. When the object@active.ident is a factor, the order of groups on the heatmap should be the order of levels of that factor. It's not obvious to me why this isn't already the case, but there should definitely be an argument for setting the order of the clusters.
