### ISSUE TITLE
errors in merging Seurat objects

### ISSUE THREAD

**Issue by JLiLab** [satijalab/seurat#2150]
I got this error message: "Error in y - mu : non-conformable arrays" when I tried to merge two Seurat objects (single-cell RNA-seq data). I will appreciate you help.
James

**Comment by bharati16mehani** [comment]
Even I am trying to merge 5 samples but getting the same error, wondering if you could solve this issue?

**Comment by andrewwbutler** [comment]
Hi,

Are you able to provide a reproducible example (downsampled objects are fine)?

**Comment by EDYAC** [comment]
I'm having the same issue
"Error in y - mu : non-conformable arrays"
This is the error message I'm getting,
so I have a dataset, that contain Lymphocytes and Myeloid cells. I susbet Cluster 3 which is a Lymphocyte. this is my first subset object.
I then take all the myeloid cells recluster them and subset another cluster.
So now I want to merge the C3 lymphocyte and the new Myeloid cell cluster.
I get the error.

**Comment by EDYAC** [comment]
The reason why I want to do that is that when I zoom in on my myeloid cells (macrophages) I now have a cluster that express a lot of T cells markers. I'm trying to figure out if this macrophage cluster is doublet contamination of if it's a macrophage that phagocyte a T cells. any idea on that?

**Comment by aelyaderani** [comment]
i have the same problem after i updated my Seurat package 
<img width="1452" alt="Screen Shot 2019-12-15 at 6 11 54 PM copy" src="https://user-images.githubusercontent.com/34661195/70872646-ea860b80-1f66-11ea-8588-8bb04390995f.png">

**Comment by mxposed** [comment]
@aelyaderani I suggest try first renaming cells individually in objects, then run SCTransform individually, then merge without `add.cell.ids` parameter
