### ISSUE TITLE
Spline bug in FeatureScatter in development version

### ISSUE THREAD

**Issue by pebonte** [satijalab/seurat#2151]
Hi all, 

I just want to report a bug. When making a scatter plot with featureScatter and adding the smoothing loess/spline argument, there is a . bug when the feature contains a "-" character.

This portion of code will work correctly : 
`FeatureScatter(object = integrated.te.uniq, feature1 = "RLTR17B-Mm-dup19149", feature2 = "sig.gene.interferon", group.by = "merged_gene_cluster2" , cols = colors_exhausted, slot = "data")`
<img width="703" alt="Capture d’écran 2019-09-30 à 15 13 40" src="https://user-images.githubusercontent.com/43744831/65882315-185ea980-e395-11e9-84ce-33fca7e61f4c.png">

But adding the span argument will cause an error because there is an "-" character in the name of the feature (in the assay@integrated slot).

`FeatureScatter(object = integrated.te.uniq, feature1 = "RLTR17B-Mm-dup19149", feature2 = "sig.gene.interferon", group.by = "merged_gene_cluster2" , cols = colors_exhausted, slot = "data", span = TRUE)`

<img width="694" alt="Capture d’écran 2019-09-30 à 15 13 12" src="https://user-images.githubusercontent.com/43744831/65882745-e863d600-e395-11e9-8dac-8cdc9d9b5dab.png">
(which translate by object RLTR17B not found)

I just wanted to report it and hopefully it will be corrected.

Thank you for your hardwork.

Best,

Pierre-Emmanuel

**Comment by andrewwbutler** [comment]
Thanks for reporting! We are able to reproduce the issue and are working on a fix. Will post back here once addressed.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
