### ISSUE TITLE
Get data for SCTransform and Featureplot()

### ISSUE THREAD

**Issue by sri540** [satijalab/seurat#2153]
1) Is it possible to get SCTransformed matrix/data from Seurat object? 
2) Does Featureplot() function use raw values or normalized values for the plots?

**Comment by andrewwbutler** [comment]
Hi,

1. Yes, please see the `GetAssayData` function for accessing the data matrices and `?SCTransform` for what is stored in each slot.
2. By default, `FeaturePlot` pulls from the `data` slot which typically represents normalized expression values (again, see `?SCTransform` for what is stored in each slot in that context).
