### ISSUE TITLE
How to get a full list of result from FindMarkers() in Seurat

### ISSUE THREAD

**Issue by lizhaozhi** [satijalab/seurat#2154]
I am new to Seurat and I am wondering is there any function or options that I can use to get a full list of results from FindMarkers()? I am curious about the performance of each gene in the test, but Seurat only returns part of those genes. Maybe Seurat only return significant results?

**Comment by sri540** [comment]
FindMarkers()
#https://www.rdocumentation.org/packages/Seurat/versions/3.1.0/topics/FindMarkers

# S3 method for default
FindMarkers(object, slot = "data",
  counts = numeric(), cells.1 = NULL, cells.2 = NULL,
  features = NULL, reduction = NULL, logfc.threshold = 0.25,
  test.use = "wilcox", min.pct = 0.1, min.diff.pct = -Inf,
  verbose = TRUE, only.pos = FALSE, max.cells.per.ident = Inf,
  random.seed = 1, latent.vars = NULL, min.cells.feature = 3,
  min.cells.group = 3, pseudocount.use = 1, ...)

# S3 method for Seurat
FindMarkers(object, ident.1 = NULL, ident.2 = NULL,
  group.by = NULL, subset.ident = NULL, assay = NULL,
  slot = "data", reduction = NULL, features = NULL,
  logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1,
  min.diff.pct = -Inf, verbose = TRUE, only.pos = FALSE,
  max.cells.per.ident = Inf, random.seed = 1, latent.vars = NULL,
  min.cells.feature = 3, min.cells.group = 3, pseudocount.use = 1,
  ...)

When you don't specify value for all parameters in FindMarkers() function, it takes default values. Thus, you see fewer number of genes in marker lists. 
change values for -  logfc.threshold, min.cells.feature, min.cells.group, min.pct. If you change the values of these parameters, you will see lot more genes in your marker gene list.

**Comment by ceesu** [comment]
Quick clarification question about this --the documentation for logfc.threshold says that we use it to 

> Limit testing to genes which show, on average, at least X-fold difference (log-scale) between the two groups of cells. Default is 0.25

Does this mean that if we set logfc.threshold <=0 we are essentially not setting a log2fc threshold? Also, this is sort of the same question, but does the default threshold imply 0.25 fold change (in either direction between the two populations) or something else e.g. perhaps exp(0.25)?

Thanks!

**Comment by tilofreiwald** [comment]
As a follow up on @sri540 's comment, this snippet returns most genes and not just the most relevant ones:

````R
markers = FindMarkers(seu, 
                        group.by = "my_clustering", 
                        ident.1 = "my_cluster1", 
                        ident.2 = "my_cluster2", 
                        min.cells.group = 1, 
                        min.cells.feature = 1,
                        min.pct = 0,
                        logfc.threshold = 0,
                        only.pos = FALSE
                        )

**Comment by raquelgarza** [comment]
Hi, 

I changed my code to:
FindMarkers(seu, group.by = "condition", ident.1 = "conditionA", lfcThreshold = 0, min.cells.feature = 1, min.cells.group = 1, min.pct = 0)

But I still don't have results for a gene I'm interested in. It's very sparsely expressed, about ~50 cells express this gene. But I still think this is differentially expressed between my two conditions. 

Any ideas on how to get the complete results?

**Comment by aaltulea** [comment]
> Hi,
> 
> I changed my code to: FindMarkers(seu, group.by = "condition", ident.1 = "conditionA", lfcThreshold = 0, min.cells.feature = 1, min.cells.group = 1, min.pct = 0)
> 
> But I still don't have results for a gene I'm interested in. It's very sparsely expressed, about ~50 cells express this gene. But I still think this is differentially expressed between my two conditions.
> 
> Any ideas on how to get the complete results?

You can use pesudobulk and proceed with DESeq2 analysis. That package returns all genes, regardless of significance
