### ISSUE TITLE
Dimensionality reduction directly on gene levels

### ISSUE THREAD

**Issue by cbligaard** [satijalab/seurat#2155]
Hi Seurat team,

I am running R v. 3.6.0 and Seurat v. 3.1.0, and I having an issue when trying to follow [the multimodal vignette](https://satijalab.org/seurat/v3.1/multimodal_vignette.html).

I would like to run clustering and UMAP directly on my data (not finding variable genes and running PCA on the way). But when I try to generate a FeaturePlot, I get the following error:

```
Error: The dimensions requested were not found
In addition: Warning:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: umap_1, umap_2
``` 

My code looks like follows (HS is my Seurat object):
```
adt.data <- GetAssayData(HS, slot = "data")
adt.dist <- dist(t(adt.data))

# Now, we rerun UMAP using our distance matrix defined only on ADT (protein) levels.
HS[["umap_adt"]] <- RunUMAP(adt.dist)
HS[["adt_snn"]] <- FindNeighbors(adt.dist)$snn
HS <- FindClusters(HS, resolution = 1, graph.name = "adt_snn")

driving_markers <- FindAllMarkers(HS, only.pos = TRUE)

DimPlot(HS, reduction = "umap_adt", group.by = "type", cells = 1:ncol(cd))
FeaturePlot(HS, cells = 1:ncol(cd), features = c("CD3E", "CD19", "CD8A", "NCAM1"), 
                    min.cutoff = "q05", max.cutoff = "q95", ncol = 2, reduction = 'umap_adt')
```

Any suggestions?

**Comment by andrewwbutler** [comment]
Hi,

Does the `DimPlot` in the line above also give the same error? Can you confirm that `HS[["umap_adt"]]` exists in the object?

**Comment by cbligaard** [comment]
No, the DimPlot works, but only when I include the `cells = 1:ncol(cd)` argument. 

Regarding the `HS[["umap_adt"]]`, it exists yes:

```
> HS[["umap_adt"]]

A dimensional reduction object with key umap_ 
 Number of dimensions: 2 
 Projected dimensional reduction calculated:  FALSE 
 Jackstraw run: FALSE 
 Computed using assay: RNA 
```

and the UMAP coordinates are also in there:

```
> head(HS[["umap_adt"]]@cell.embeddings)
        umap_1    umap_2
[1,]  4.008199  2.893487
[2,] -7.544287  6.472837
[3,]  2.450984  5.164797
[4,]  3.866802  1.655440
[5,] -7.921798  3.509809
[6,]  4.726174 -9.208515
```

**Comment by yuhanH** [comment]
I think it is related to the umap key.
When you run the RunUmap on the cell-cell distance, you need to set a reduction key.
`HS[["umap_adt"]] <- RunUMAP(adt.dist,  reduction.key = "adtUMAP_" )`. If not work, I will reopen the issue.

**Comment by cbligaard** [comment]
Hi Yuhan, 

Unfortunately, it does not seem to be related to the reduction key - I have tested that as well:

```
> HS <- CreateSeuratObject(harmonized, meta.data = meta)
> adt.data <- GetAssayData(HS, slot = "data")
> adt.dist <- dist(t(adt.data))

> HS[["umap_adt"]] <- RunUMAP(adt.dist, reduction.key = "adtUMAP_", seed.use = 123)
> HS[["adt_snn"]] <- FindNeighbors(adt.dist)$snn
> HS <- FindClusters(HS, resolution = 1, graph.name = "adt_snn", random.seed = 123)

> FeaturePlot(HS, reduction = "umap_adt", cells = 1:ncol(cd), features = c("CD3E", "CD19", "CD8A", "NCAM1"), min.cutoff = "q05", max.cutoff = "q95", ncol = 2)

Error: The dimensions requested were not found
In addition: Advarselsbesked:
I FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: adtUMAP_1, adtUMAP_2
```

**Comment by yuhanH** [comment]
Hi, 
I know the issue. The cell embedding of the reduction doesn't have cell names.
In your case, you can just add the cell name into the embeddings. We will fix this bug soon.
```
rownames(HS[["umap_adt"]]@cell.embeddings) <- Cells(HS)
```

**Comment by cbligaard** [comment]
Yes, that works! Thank you.
