### ISSUE TITLE
RunMultiCCA function no longer available in Seurat 3? 

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#2156]
Hello, Seurat team,
I tried to run CCA on 6 samples today, however, when I used the RunMultiCCA function it throw out an error saying there is no function called RunMultiCCA, I also saw one of you in said in a previous post saying you guys replaced RunMultiCCA with the integration workflow. So is that means the RunMultiCCA function is removed from the package?

**Comment by andrewwbutler** [comment]
Yes, that is correct. We recommend using the new v3 integration workflow and therefore removed functions relevant only for the v2 workflow from the updated package. If you need to run these functions, you will need to install an older version of Seurat (see [this page](https://satijalab.org/seurat/install.html#previous-versions) for details).
