### ISSUE TITLE
Multimodal data - Integrated Seurat object

### ISSUE THREAD

**Issue by sri540** [satijalab/seurat#2157]
I'm trying to add CITE-seq data to an integrated datasets - Seurat object. It's not working. 

The object and CITE-seq data has same number of cells. 

> citeseq_oc12019[["ADT"]] <- CreateAssayObject(counts=subset2)
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion
> citeseq_oc12019 <- NormalizeData(citeseq_oc12019, assay.type = "ADT", normalization.method = "CLR")
Warning: The following arguments are not used: assay.type
Normalizing across features
Error: The new data doesn't have the same number of cells as the current data
> citeseq_oc12019 <- ScaleData(citeseq_oc12019, assay.type = "ADT")
Warning: The following arguments are not used: assay.type
Centering and scaling data matrix
  |===================================| 100%

**Comment by MichaelStber** [comment]
Hi @sri540 .

Have you tried to run assay instead of assay.type ?
`citeseq_oc12019 <- NormalizeData(citeseq_oc12019, assay.type = "ADT", normalization.method = "CLR")`

Best,
Michael

**Comment by sri540** [comment]
assay works. 

But I'm getting this warning when reading the data. 

citeseq_oc12019[["ADT"]] <- CreateAssayObject(counts=subset2)
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion

**Comment by andrewwbutler** [comment]
This looks like there might be something strange going on with `subset2`. I would recommend checking that this is some sort of numeric matrix (i.e. doesn't contain strings, factors, etc) and it doesn't contain any missing values (`NA`s).

**Comment by sri540** [comment]
How to check if the large matrix is numeric?
