### ISSUE TITLE
no "InstallData()"

### ISSUE THREAD

**Issue by vmorozov** [satijalab/seurat#2158]
Hi,
I try to follow the data integration vignette https://satijalab.org/seurat/v3.1/integration.html

> InstallData("pbmcsca")
 Error in InstallData("pbmcsca") : could not find function "InstallData"
--
 
  |  
 

> sessionInfo() R version 3.6.1 (2019-07-05) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 18.04.3 LTS  Matrix products: default BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] Seurat_3.1.0  loaded via a namespace (and not attached):  [1] httr_1.4.0          tidyr_0.8.3         viridisLite_0.3.0   jsonlite_1.6        splines_3.6.1       lsei_1.2-0           [7] R.utils_2.9.0       leiden_0.3.1        gtools_3.8.1        RcppParallel_4.4.4  Rdpack_0.11-0       assertthat_0.2.1    [13] ggrepel_0.8.1       globals_0.12.4      pillar_1.3.1        lattice_0.20-38     glue_1.3.1          reticulate_1.12     [19] digest_0.6.18       RColorBrewer_1.1-2  SDMTools_1.1-221.1  colorspace_1.4-1    cowplot_1.0.0       htmltools_0.3.6     [25] Matrix_1.2-17       R.oo_1.22.0         plyr_1.8.4          pkgconfig_2.0.2     bibtex_0.4.2        tsne_0.1-3          [31] listenv_0.7.0       purrr_0.3.2         scales_1.0.0        RANN_2.6.1          gdata_2.18.0        Rtsne_0.15          [37] tibble_2.1.1        ggplot2_3.1.1       ROCR_1.0-7          pbapply_1.4-2       lazyeval_0.2.2      survival_2.44-1.1   [43] magrittr_1.5        crayon_1.3.4        R.methodsS3_1.7.1   future_1.14.0       nlme_3.1-141        MASS_7.3-51.4       [49] gplots_3.0.1.1      ica_1.0-2           tools_3.6.1         fitdistrplus_1.0-14 data.table_1.12.2   gbRd_0.4-11         [55] stringr_1.4.0       plotly_4.9.0        munsell_0.5.0       cluster_2.1.0       irlba_2.3.3         compiler_3.6.1      [61] rsvd_1.0.2          caTools_1.17.1.2    rlang_0.3.4         grid_3.6.1          ggridges_0.5.1      rstudioapi_0.10     [67] RcppAnnoy_0.0.13    htmlwidgets_1.3     igraph_1.2.4.1      bitops_1.0-6        npsurv_0.4-0        gtable_0.3.0        [73] codetools_0.2-16    reshape2_1.4.3      R6_2.4.0            gridExtra_2.3       zoo_1.8-6           dplyr_0.8.0.1       [79] uwot_0.1.4          future.apply_1.3.0  KernSmooth_2.23-15  metap_1.1           ape_5.3             stringi_1.4.3       [85] parallel_3.6.1      Rcpp_1.0.1          sctransform_0.2.0   png_0.1-7           tidyselect_0.2.5    lmtest_0.9-37
--
 
  |

**Comment by sri540** [comment]
devtools::install_github('satijalab/seurat-data')

By installing the 'satihalab/seurat-data', you should be able to load the data and InstallData() function will work.

**Comment by Dragonmasterx87** [comment]
For those of you who like me remain mind-boggled for a few minutes as 'to why it still doesn't work' don't forget to run `library(SeuratData)` after `devtools::install_github('satijalab/seurat-data')`

Sometimes I get the dumbs. 🤣 

Cheers.

**Comment by yulchen810** [comment]
Hi,
it seems that `devtools::install_github('satijalab/seurat-data')` is not gonna to work in seurat v4.
![image](https://github.com/user-attachments/assets/50991327-83af-4910-ae88-e167e594fc03)
