### ISSUE TITLE
Specifying interaction terms for linear models

### ISSUE THREAD

**Issue by khandarius** [satijalab/seurat#216]
Hi,

Is there a way to include interaction terms for differential expression testing in Seurat? For example, I have a nested factorial design with cells from four samples, two samples per genotype, and I would like to test for differential expression within a cluster of cells. The linear model formula would be ~nUMI + genotype+genotype:sample, with genotype being my effect of interest.

Thanks in advance.

**Comment by satijalab** [comment]
We do not support this at the moment, but would be thrilled if you would put together a pull request!
