### ISSUE TITLE
In storage.mode(from) <- "double" : NAs introduced by coercion

### ISSUE THREAD

**Issue by sri540** [satijalab/seurat#2160]
I'm getting this warning while adding ADT data:In storage.mode(from) <- "double" : NAs introduced by coercion

The subsequent analysis is failing - Error in quantile.default(x = data, probs = this.quantile) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

The data in itself looks fine.

> citeseq_oc12019[["ADT"]] <- CreateAssayObject(counts=subset2)
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion
> #
> citeseq_oc12019 <- NormalizeData(citeseq_oc12019, assay = "ADT", normalization.method = "CLR")
Normalizing across features
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
> citeseq_oc12019 <- ScaleData(citeseq_oc12019, assay = "ADT")
Centering and scaling data matrix
  |=================================================| 100%
>FeaturePlot(citeseq_oc12019, 
+                     #assay = "ADT",
+                     features = CD4-marker,
+                     reduction="umap",
+                     min.cutoff = "q05",
+                     max.cutoff = "q95", 
+                     cols = c("lightgrey","gold","red"),
+                     pt.size=0.6,
+                     ncol=1))
+   
Error in quantile.default(x = data, probs = this.quantile) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
#---------------------------------------------------------------------------
subset2 [1:2,1:5]
             june16_GTTTCTATCTTGCAAG-1
x1-marker                   6.976375
x2-marker                 19.974971
             june16_ACGCAGCAGCTCCCAG-1
x1-marker                   2.517739
x2-marker                  0.000000
             june16_TTAGGCACACCAGGCT-1
x1-marker                   5.218216
x2-marker                 15.937020
             june16_CTGCGGAAGTCATGCT-1
x1-marker                   7.915093
x2-marker                  4.532547
             june16_TCTTCGGTCCTTTACA-1
x1-marker                   1.908728
x2-marker                166.139907
#---------------------------------------------------------------------------

**Comment by andrewwbutler** [comment]
Hi,

Are you able to share the data (or subset) that reproduces the issue?
