### ISSUE TITLE
ADT related memory issues

### ISSUE THREAD

**Issue by Yue-Jiang** [satijalab/seurat#2161]
There have been several open or closed issues related to memory issues when clustering by ADT only (e.g. #2103, #2134, #2149). I think this might have to do with how the tutorial (https://satijalab.org/seurat/v3.1/multimodal_vignette.html) handles ADT data. If I understand this correctly, the tutorial is also trying to use ADT analysis as an example to show how `RunTSNE`, `FindNeighbors` and `FindClusters` work with custom distance matrix. However, when people try to follow the tutorial it may appear the official way of working with ADT data is to calculate a cell-cell pairwise distance matrix by calling `dist()` and supply this potentially huge matrix to aforementioned functions, which tend to breach memory limit on their machines. If I understand it correctly, setting the default assay of the Seurat object to "ADT" and supplying all ADT features as an argument will likely resolve the memory issue as long as the RNA part of the experiment had worked OK.

```
# assuming obj is the Seurat object
adt_features <- rownames(comb@assays$ADT)
DefaultAssay(obj) <- "ADT"
obj <- RunTSNE(obj, features = adt_features, reduction.name = "tsne_adt", reduction.key = "adtTSNE_")
obj <- FindNeighbors(obj, assay = "ADT", features = adt_features, graph.name = "adt_snn")
obj <- FindClusters(obj, graph.name = "adt_snn")
# latest clustering results will be stored in object metadata under 'seurat_clusters'
obj[["ADTClusterID"]] <- obj@meta.data$seurat_clusters
DefaultAssay(obj) <- "RNA" # set default assay back to the original one, assuming it's "RNA"
```

Looking through the code it seems no distance matrix is generated when operating on a Seurat object, instead there's a `NNHelper` function that calls `‘RANN::nn2` which finds the k nearest neighbors by euclidian distance with a much smaller memory footprint, without generating the full distance matrix, hence the difference in performance.

I'm looking for an official confirmation if I missed anything; or if this approach looks reasonable it might be worth mentioning in the tutorial. Thanks!

**Comment by yuhanH** [comment]
HI,
You are right. We usually use the neighbors to build the dimension reduction rather than the entire cell-cell matrix. It is impossible to put the cell-cell matrix in the RunTsne when the cell number is big. 
We will add some more clarifications on the multi-model vignette.

**Comment by yuhanH** [comment]
Sorry for the late reply. You can RunPCA directly on ADT data rather than calculate cell-cell distance matrix. 
You can find the updated multimodal vignette here. https://satijalab.org/seurat/v3.2/multimodal_vignette.html
