### ISSUE TITLE
How to write AverageExpression into cvs?

### ISSUE THREAD

**Issue by chaoqunwang2018** [satijalab/seurat#2166]
Hello!
I am using the following code to generate and export the AverageExpression of the list of gene (MASTdrug.response).

AverageExpression <- AverageExpression(Clearimmune.combined, assays = NULL, features = "MASTdrug.response",
                                       return.seurat = TRUE, add.ident = NULL, slot = "data",
                                       use.scale = FALSE, verbose = TRUE)

write.csv(AverageExpression,row.names = TRUE, file="/Users/Chaoqun/Desktop/AverageExpression.csv")

I got this Error:
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("Seurat", package = "Seurat")’ to a data.frame

Do you know what might be causing this error? 

Thank you,
Chaoqun

**Comment by phoebee-h** [comment]
Hi,
I'm not from official. If you want to get the AverageExpression as a data frame directly, you shouldn't set the "return.seurat = TRUE",  as this parameter returns you a Seurat Object.  

Hope this helps.
