### ISSUE TITLE
How to add AverageExpression in the MAST and DEseq2 csv?

### ISSUE THREAD

**Issue by chaoqunwang2018** [satijalab/seurat#2167]
Hello!
I am using the following code to generate the differential expression genes between treated Vs untreated. There are p_val, avg_logFC, pct.1, pct.2, and p_val_adj for each genes, but there is
 no AverageExpression. Do you know how to  add "AverageExpression" in the MAST.csv?
Thank you very much!

MASTdrug.response <- FindMarkers(object = Clearimmune.combined, ident.1 = "treated", ident.2 = "untreated", test.use = "MAST", logfc.threshold = log(x = 0.0000001))

write.csv(MASTBleo.response, file="/Users/chaoqun/Desktop/MASTdrug.response.csv")

Best,
Chaoqun

**Comment by yuhanH** [comment]
I think `AverageExpression` function is what you need.
You can find the documentation of this function by `?AverageExpression`
