### ISSUE TITLE
some errors in using UpdateSeuratObject

### ISSUE THREAD

**Issue by tianchen2019** [satijalab/seurat#2170]
When I used UpdateSeuratObject for transforming seurat V2  to seurat V3 data, I found my gene names have been changed. the rownames "ENSMUST00000002518.8_Aes-201" has been changed into "ENSMUST00000002518.8-Aes-201" . And the `colnames@reductions[["pca"]]` should be PC-1,PC-2,PC-3(in seurat V3),but it seems not been changed(PC1,PC2,PC3). You may need to modify the code in  **UpdateSeuratObject**

**Comment by Reductions** [comment]
@tianchen2019  Why do you call? :D

**Comment by mojaveazure** [comment]
@tianchen2019, I'm confused as to what the bug would be. Generally speaking, there won't be dashes `-` in the dimensional reduction names. Is there a part of Seurat that doesn't work when you use `UpdateSeuratObject`

@Reductions, I believe that was an accident. When people don't post their code in code blocks, they trigger notifications to other users if they have the same name as one of the slots in our objects. We will try to encourage our users to use code blocks whenever possible (@tianchen2019, please use code blocks when typing code; if you need help, please see [GitHub's help pages on Markdown](https://guides.github.com/features/mastering-markdown/)). Apologies for any inconvenience.

**Comment by tianchen2019** [comment]
![image](https://user-images.githubusercontent.com/46451175/66368116-94767400-e9c9-11e9-85b0-c902d58016b7.png)
"hsc1" is a seurat V2 object. The colnames of   dimensional reduction names is PC1 ,PC2,PC3.

when I used **UpdateSeuratObject** to  transform seurat V2 to seurat V3 data.The colnames of   dimensional reduction names are not changed.
![image](https://user-images.githubusercontent.com/46451175/66368231-0c449e80-e9ca-11e9-9ab5-e68d17cb4fe6.png)
when i used Featureplot, the error appear.
![image](https://user-images.githubusercontent.com/46451175/66368377-a6a4e200-e9ca-11e9-9ed7-62712a7ef6c7.png)
I think the error come from **UpdateSeuratObject**.
The colnames of dimensional reduction names in seurat V3 is PC_1,PC_2.
![image](https://user-images.githubusercontent.com/46451175/66368480-faafc680-e9ca-11e9-9a48-a0f3871fb6c5.png)
"clu_tu_hong" is a seurat V3 object.
