### ISSUE TITLE
VariableFeaturePlot for an integrated dataset

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#2172]
Hi Guys!

How can one generate a VariableFeaturePlot of var.features in the integrated assay slot? It seems like variableFeaturePlot only recognizes either SCT or RNA (vst) variable feature slots for plotting. 

I've tried all combinations and more as given [here](https://rdrr.io/cran/Seurat/man/VariableFeaturePlot.html)

Cheers!

**Comment by Dragonmasterx87** [comment]
nvm figured it out. Cheers!

**Comment by surbhi-sona** [comment]
@Dragonmasterx87 Could you please share your solution? I keep getting errors message" Please run either 'FindVariableFeatures' or 'SCTransform' " even though I ran this on every object prior to integration. 

I even ran this function post integration and when I tried to print the variable genes plot, it gave me same error as above.

**Comment by Dragonmasterx87** [comment]
Sorry for the late reply @surbhi-sona, so, the funny story is either I've forgotten how I did this or realized it was really dumb of me to attempt in the first place (emphasis on me 😅). Here is what I think now:

So, based on #2778 and @satijalab 's [reply](https://github.com/satijalab/seurat/issues/2778#issuecomment-608520618) you can't run this on the integrated slot of an integrated dataset.....which makes sense because that would mean that 1) from a coding perspective the meta.features slot would need to be populated with values for things like sct.detection_rate sct.gmean etc etc, and 2) conceptually, the integrated slot only exists to allow for optimal clustering. You should definitely not use it for anything else (such as gene expression, most variable genes etc). 

Therefore, if you want to show variable genes (genes relevant to your analysis), you can either show the variable genes in the RNA slot, or re-run SCT transform using:

```
IAmASeruatObj <- SCTransform(IAmYourSeruatObj, 
                                       assay = "RNA", 
                                       new.assay.name = "SCT2", # make a new test assay
                                       verbose = TRUE, 
                                       return.only.var.genes = TRUE)
```

and then plot var genes using:

```
VariableFeaturePlot(
  IAmASeruatObj,
  cols = c("black", "red"),
  pt.size = 1,
  log = NULL,
  selection.method = c('sct'),
  assay = "SCT2"
)
```

Now you may argue, that well, an integrated dataset is integrated using a set of variable features, which could be interesting to show, from a clustering perspective....and to that, I don't have an answer. The devs will have to answer that 😄 because honestly, I have learned from experience not to venture close to the integrated assay after getting a batch corrected UMAP. The integrated slot is a realm not made for mere mortals like me, it's someplace only demon slayers like Seurat devs venture.

Cheers,
🐲

**Comment by surbhi-sona** [comment]
Thanks, for sharing your experience @Dragonmasterx87. It does make sense as they warn people against using integrated assay for anything else other than clustering.

I don't mind not getting other info, just wanted to pull out var genes from integrated object and managed to get those using **obj@assays$integrated@var.features**

**Comment by Dragonmasterx87** [comment]
Oh! @surbhi-sona if you want the `var.features` data you can also use: `obj@assays[["integrated"]]@var.features`

Another cool trick, if you want a particular data point, just open the object from your RStudio Global Env window, and if you open your assays>integrated, you can actually move the cursor to the right and a small box appears, which upon clicking opens a segment of code directing to that slot 😃 That helped me a few years back.
