### ISSUE TITLE
Doublets vs. Phagocytic Macrophages

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#2175]
Hi Seurat Community,
I have a dataset composed of mainly immune cells.
I do study macrophages in the context of inflammation,
as you know macrophages are phagocytic and thus can eat other cells.
When I cluster my macrophages, I get a cluster that express T cell markers.
How can I be sure that these are phagocytic macrophages and not doublets?
Anyone working with macrophage has encountered such a thing?
Thank you

**Comment by satijalab** [comment]
This is beyond the capability of a software package to answer definitely, and has more to do with your biological intepretation of data, and the tradeoff between assuming that a strange result  (which can be explained by a technical artifact) could in fact have a plausible biological basis.

The phrase "When you hear hoofbeats think horses not zebras" is always a good one to keep in mind.

**Comment by csecarroll** [comment]
What are the T cell markers they express? There are so many overlapping markers and the distinction between cell subtypes is becoming less and less distinct.  And when activated T cells and macrophages can express some markers in common.
