### ISSUE TITLE
Recreation of density plots from previous tutorials

### ISSUE THREAD

**Issue by astrovsky01** [satijalab/seurat#2176]
![image](https://user-images.githubusercontent.com/40246333/66319961-f1036180-e8eb-11e9-8a66-2e07620c95cd.png)
I'm attempting to recreate the plot in one of your tutorials for v2, which used mean.var.plot. It appears that the new version replaces that function with VariableFeaturesPlot(), but I cannot get the graph to show the density lines or the actual gene names. Furthermore, when using selection.method="mvp", the mean.function and dispersion.function cause errors, and return them as unused arguments. Is there a method in v3 for recreating that original plot?

**Comment by mojaveazure** [comment]
Hi Alex,

The density plots were removed in Seurat v3 as we've transitioned (nearly) all of our plots to ggplot2 which does not have an easy way of creating these density plots. To make it easier to distinguish variable features on these plots, we now highlight the variable features in red.

![image](https://user-images.githubusercontent.com/11035068/66668761-f4685700-ec23-11e9-9a21-71440d788e71.png)

**Comment by astrovsky01** [comment]
Thank you! That's what I figured, but I just wanted to make sure.

**Comment by classycammy** [comment]
If I would like to re-create the blue density plots from your previous tutorial, are there any ways I can do it? Appreciate any advises. Thank you.
