### ISSUE TITLE
DoHeatmap() runs, but does not plot

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#2179]
Hi,

I have an integrated dataset of ~70,000 cells and I wanted to plot a heatmap of 49 interesting for me genes. I ran DoHeatmap(), but although the command runs fine, it never plots the graph. Can anyone think of a possible reason for that? Could it be the cell number?

Thanks,
Theo

**Comment by timoast** [comment]
I can't reproduce this, what plotting device are you using?

**Comment by tkapello** [comment]
I use RStudio for plotting, but in the last month, it has given me a couple of errors, e.g. _label=T_ plots numbers and not the cluster numbers and now it runs, but does not plot.

**Comment by timoast** [comment]
I think this is an issue you're having with RStudio and not Seurat. Try running `dev.off()` a couple of times until you see `Error in dev.off() : cannot shut down device 1 (the null device)`. If you still have issues restart RStudio, and you can contact RStudio for further support.

**Comment by Echo226** [comment]
Hi,

I had the same issue. Finally I found out that having a large number of cells is one of the reason for not plotting the graph, when you have more than 30k cells. Please read #2724 for more details. The author mentioned this issue there.
