### ISSUE TITLE
How can percent.mito genes be lower than 0?

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#218]
How is this possible? A percent cannot be less than 0, no? 

allmito <- FilterCells(object = all6i, subset.names = c("nUMI", "percent.mito"), 
                        low.thresholds = c(1, 0), high.thresholds = c(Inf, Inf))

length(x=allmito@ident)
#9818

allmito <- FilterCells(object = all6i, subset.names = c("nUMI", "percent.mito"), 
                       low.thresholds = c(1, -Inf), high.thresholds = c(Inf, Inf))

length(x=allmito@ident)
#437435

**Comment by leonfodoulian** [comment]
Hello,

The short answer to your question is no. There cannot be percentage values below 0. However, the default setting for `low.threshold` is `-Inf`. If you specify 0 instead, you will loose all the cells having 0 `percent.mito`. The code for this can be found [here](https://github.com/satijalab/seurat/blob/master/R/interaction.R#L377).

Best,
Leon

**Comment by del2007** [comment]
Thanks Leon, I assumed that threshold was inclusive of itself. It makes sense now.
