### ISSUE TITLE
Confused about how to do DE after SCTransform

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#2180]
Hello,

I looked both in the tutorials and vignettes, as well as in this forum, but I am still not sure how to, or even if it is possible, to use the SCTransform-ed Pearson residuals for DE analysis using `FindAllMarkers` and `FindMarkers`.

In conclusion, on this date, it doesn't look like doing DE on the SCT assay is fully supported yet, and so the best option right now is to do DE on the RNA assay, as we used to do in Seurat V2.

Could somebody from @satijalab please confirm/comment on this asap, so that the user community can decide how to proceed with their data at this point?

References: #2115, #1501, and #1623.  Also, point 4 in https://satijalab.org/seurat/faq.html

Many many thanks!

**Comment by AndyR2** [comment]
I'm running Seurat v 3.0.3.9023 (development version - but 3.1 is available).    FindAllMarkers seems to run fine.  Here is some script for a recent project

`# run sctransform
X <- SCTransform(X, vars.to.regress = "nCount_RNA", verbose = FALSE)

#check the R obj.  by highlighting it and hit enter.   Should look like this:
X
An object of class Seurat 
41845 features across 62582 samples within 3 assays 
Active assay: integrated (2000 features)
 2 other assays present: RNA, SCT
 2 dimensional reductions calculated: pca, tsne

save(X, file = "C:/X.Robj")

X <- RunPCA(X, npcs = 30, verbose = FALSE)
X <- RunTSNE(X, reduction = "pca", dims = 1:30)
X <- FindNeighbors(X, reduction = "pca", dims = 1:30)
X<- FindClusters(X, resolution = 1.0)
TSNEPlot(X, label = T, pt.size = 0.5, label.size = 7)
X.markers <- FindAllMarkers(X, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)`

**Comment by CodeInTheSkies** [comment]
Hi @AndyR2 ,

If you use `FindAllMarkers` as you describe, then you would be using the `@data` slot of `SCT`.  However, as per the current recommendation of the authors, it is best to use the `@scale.data` slot, isn't that so?

**Comment by CodeInTheSkies** [comment]
Further on this question to @satijalab , in #1501, you say that you recommend **_option 1_** therein, and so would that mean, just to confirm, it is best to do DE on the SCT assay's `@data` slot?  That would be the log-transformed "corrected counts", which are obtained by reversing the NB model, like it is explained here https://github.com/ChristophH/sctransform/issues/36#issuecomment-526056501.  Is this correct?

Thank you!

**Comment by satijalab** [comment]
There are a number of similar questions you have asked with regards to the SCTransform workflow (including how to handle cell cycle regression, etc.). It is not always possible for us to say what is "best", and I'm going to try to refrain from using such language in the future, as there are pluses and minuses to the approaches. 

What I can do is to confirm your interpretation of the different slots. Performing DE on scale.data means that you are performing DE on the pearson residuals that come out of regularized NB regression. 

The counts and data slot transforms these values back into integer values (stored in counts), and then performs a log-transformation (stored in data). 

When possible, we try to perform operations directly on the Pearson residuals themselves. However, these values are not sparse (contain exclusively non-zero elements), so they take a lot of memory to store, and as a result we don't compute them for all genes by default. Unless you change the defaults in SCTransform, performing DE on the scale.data slot would only test differences in variable genes. We also find that pearson residuals are challenging to visualize/interpret on either Feature or Violin plots, and therefore find the data slot in the SCT assay quite useful for this.

Again, we cannot advise on the "best" approach for every downstream analysis, but as long as you understand what each data slot contains you can make an informed decision on how to move forward.

**Comment by 10adavis** [comment]
> There are a number of similar questions you have asked with regards to the SCTransform workflow (including how to handle cell cycle regression, etc.). It is not always possible for us to say what is "best", and I'm going to try to refrain from using such language in the future, as there are pluses and minuses to the approaches.
> 
> What I can do is to confirm your interpretation of the different slots. Performing DE on scale.data means that you are performing DE on the pearson residuals that come out of regularized NB regression.
> 
> The counts and data slot transforms these values back into integer values (stored in counts), and then performs a log-transformation (stored in data).
> 
> When possible, we try to perform operations directly on the Pearson residuals themselves. However, these values are not sparse (contain exclusively non-zero elements), so they take a lot of memory to store, and as a result we don't compute them for all genes by default. Unless you change the defaults in SCTransform, performing DE on the scale.data slot would only test differences in variable genes. We also find that pearson residuals are challenging to visualize/interpret on either Feature or Violin plots, and therefore find the data slot in the SCT assay quite useful for this.
> 
> Again, we cannot advise on the "best" approach for every downstream analysis, but as long as you understand what each data slot contains you can make an informed decision on how to move forward.

Sorry to raise this issue again but I'm finding conflicting advice on this particular question. I've run an integrated analysis of my data and used the SCTransform workflow. Based on the FAQ page, point #4 recommends running the DE analysis on the "unintegrated" data stored in the "RNA" assay. It also mentions that this data should be normalized first. Does it need to be scaled as well?

**Comment by AndyR2** [comment]
if I recall these discussions, just run NormalizeData function.   Scaling is now brought under that function, as shown below.   Works well.   

NormalizeData(
  object,
  normalization.method = "LogNormalize",
  scale.factor = 10000,
  margin = 1,
  block.size = NULL,
  verbose = TRUE,

**Comment by 10adavis** [comment]
> if I recall these discussions, just run NormalizeData function. Scaling is now brought under that function, as shown below. Works well.
> 
> NormalizeData(
> object,
> normalization.method = "LogNormalize",
> scale.factor = 10000,
> margin = 1,
> block.size = NULL,
> verbose = TRUE,

Thanks for the quick response, @AndyR2. 
So starting with my integrated dataset: "seurat.integrated", I would run the following:

DefaultAssay(seurat.integrated) <- "RNA"
# Normalize RNA data 
seurat.integrated <- NormalizeData(seurat.integrated, verbose = FALSE)
# Run DE on the unintegrated data:
skin.markers.RNA <- FindAllMarkers(seurat.integrated,assay="RNA",slot="data",only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

**Comment by AndyR2** [comment]
This is my standard set of markers calls for any dataset I get to this point on.
`xxx.markers <- FindAllMarkers(xxx, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
xxx.markers %>% group_by(cluster) %>% top_n(5, avg_logFC)

top10 <- xxx.markers %>% group_by(cluster) %>% top_n(10, avg_logFC)
top25 <- xxx.markers %>% group_by(cluster) %>% top_n(25, avg_logFC)
top50 <- xxx.markers %>% group_by(cluster) %>% top_n(50, avg_logFC)

write.csv(xxx.markers, "xxx.markers.csv")
write.csv(top10, "xxx.top10.csv")
write.csv(top25, "xxx.top25.csv")
write.csv(top50, "xxx.top50.csv")

xxx_Clu <-FetchData(xxx, vars = 'ident')
write.csv(xxx_Clu, "xxx_clusters.csv") `

**Comment by vravik** [comment]
Hi all,

I just have a question regarding this proposed workflow downstream of data integration: 

DefaultAssay(seurat.integrated) <- "RNA"
seurat.integrated <- NormalizeData(seurat.integrated, verbose = FALSE)
skin.markers.RNA <- FindAllMarkers(seurat.integrated,assay="RNA",slot="data",only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

If after integrating the dataset, we are going to use the log-normalized RNA counts data for all downstream analysis, what is the point of performing the SCT normalization in the first place? I understand it's being used as input for the IntegrateData function, but given the benefits of this normalization approach over the regular log-normalization, why don't we use this for downstream differential expression analysis as well?

**Comment by msadman-sakib** [comment]
> Hi all,
> 
> I just have a question regarding this proposed workflow downstream of data integration:
> 
> DefaultAssay(seurat.integrated) <- "RNA"
> seurat.integrated <- NormalizeData(seurat.integrated, verbose = FALSE)
> skin.markers.RNA <- FindAllMarkers(seurat.integrated,assay="RNA",slot="data",only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
> 
> If after integrating the dataset, we are going to use the log-normalized RNA counts data for all downstream analysis, what is the point of performing the SCT normalization in the first place? I understand it's being used as input for the IntegrateData function, but given the benefits of this normalization approach over the regular log-normalization, why don't we use this for downstream differential expression analysis as well?

Honestly I am having this exact same question right now! 
I tried to do the SCT normalization for all genes ( by turning on `return.only.var.genes = F` in `SCTransform()` , but it is always crashing because of memory issue on my local computer. And that's why the authors explicitely made the `return.only.var.genes = T` by default to avoid this.
