### ISSUE TITLE
Integrated Data in multiple steps

### ISSUE THREAD

**Issue by akhst7** [satijalab/seurat#2184]
HI, 

I attempted to integrate 7 seurat objects by 

 `all.int<-IntegrateData(anchorset = int.anchors, normalization.method = "SCT", dims =1:50, verbose = T)`

Integrating 7 seurat objects, typically gets me an out of memory error ( RAM maxed out at 64GB) even with lower dims. So,  I am wondering if there is an option to split an `integrateData` in multiple steps or alternatively adding additional seurat objects into the existing integrated Data by using the same anchorset/int.anchors.  

Thanks.

**Comment by timoast** [comment]
Doing the integration in multiple steps won't help, but if you use reciprocal PCA this should require less memory. See the vignette online for more information: https://satijalab.org/seurat/v3.1/integration.html
