### ISSUE TITLE
Find markers for a specific cell type (derived from metadata) within each cluster compared to all cells in all clusters

### ISSUE THREAD

**Issue by BhaktiDwivedi** [satijalab/seurat#2186]
I have a single-cell RNAseq data from two experimental conditions ("T1" and "T2"). I have identified the clusters (n=15) in the data. Next I would like to find markers differentially expressed in each treatment cells (T1 and T2) within each cluster when compared to all cells of all remaining clusters. For example, cluster "1" T1 markers compared to all cells of all clusters (including the T2 cells from cluster 1), likewise cluster "1" T2 markers compared to all cells of clusters (including the T1 cells from cluster 1), and so forth.

I am able to identity markers and compare the T1 from T2 cells within each cluster using the FindMarkers, For example,
`markers <- FindMarkers(scrnaKeep, ident.1 = "T1", ident.2 = "T2", group.by = 'group', subset.ident = "1", test.use="MAST")`

But I am not able to figure out how to find markers distinct to T1 (or T2) cells of each cluster when compared to all remaining clusters cells. Is there a way to do this? Appreciate any help and suggestions.

Thanks so much!

Regards,
BD

**Comment by timoast** [comment]
Hi, you would just need to change the comparison you're making in `FindMarkers`, for example:

```r
markers <- FindMarkers(scrnaKeep, ident.1 = "T1", group.by = 'group', subset.ident = "1", test.use="MAST")
```

will compare "T1" vs all other cells.
