### ISSUE TITLE
Interpreting results from JackStrawPlot and ElbowPlot to determine statistically significant principal components

### ISSUE THREAD

**Issue by JoaoGabrielMoraes** [satijalab/seurat#2187]
Hello Seurat community!

Attached are the results from JackStrawPlot and ElbowPlot from my dataset. 
[JackStrawPlot and ElbowPlot.pptx](https://github.com/satijalab/seurat/files/3704757/JackStrawPlot.and.ElbowPlot.pptx)

Although both methods are used to determine statistically significant principal components (PC), by looking at the plots (please see attached file), all PCs in the JackStrawPlot are really significant, but not so much when PCs are ranked based on the percentage of variance explained by each one using the ElbowPlot.  

Any suggestions on interpreting these differences when determining how many PCs to include?

**Comment by satijalab** [comment]
See #2677
