### ISSUE TITLE
Dual Y-axis scatter plot.

### ISSUE THREAD

**Issue by vlcm2019** [satijalab/seurat#2188]
Can you generate a dual Y-axis scatter plot using the following three features in Seurat: nCount_RNA, nFeature_RNA, and percent.mt?

**Comment by timoast** [comment]
We don't support this in Seurat, you can always plot them separately. See this post for more information: https://stackoverflow.com/questions/3099219/ggplot-with-2-y-axes-on-each-side-and-different-scales/3101876#3101876
