### ISSUE TITLE
Is there a need to use the Seurat alignment tools if the samples were aligned with CellRanger software?

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#219]
These are 6 data sets from 10X already aligned by CellRanger. I assume some normalization already took place when merging the sets. 
I now have a combined object but there seem to be 2 distributions of the nUMI and nGene. (4 samples follow distribution "a" and 2 samples follow distribution "b" for example). Does this mean that CellRanger did not really align the sets? Is there a need to realign with the Seurat tools before proceeding to analyze the combined object? 

Thank you for any insights!

**Comment by satijalab** [comment]
You may want to look at the CellRanger documentation a bit more closely to see exactly how it is normalizing the samples, but the biological results (and not the technical metrics alone) should guide your decision to use the Seurat integration workflow if desired. You can read a bit more about this on our preprint : https://www.biorxiv.org/content/early/2017/07/18/164889
