### ISSUE TITLE
How can I make a plot showing the number of transcripts expressed per cell

### ISSUE THREAD

**Issue by NaomiCroft** [satijalab/seurat#2192]
I have made a UMAP plot showing clusters of cells from single cell RNA sequencing data using this script:

allsample.data.seurat <- RunUMAP(allsample.data.seurat, dims =1:30)
DimPlot(allsample.data.seurat, reduction = "umap", label = TRUE, label.size = 5)

What I would like is to show the number of transcripts per cell on this plot. I guess the easiest way is by showing this by colour intensity, so cells with a high transcript number are a stronger colour.

I am interested in this to visualise which cell clusters are transcriptionally very active and which are not. Any suggestions?

Thanks for your time!

**Comment by sri540** [comment]
Have you tried FeaturePlot() ?

**Comment by AndyR2** [comment]
After clustering, you can run VlnPlot, and it will give “per cluster” info for genes, UMIs or %mito (use correct metadata name [nFeature_RNA, ncount_RNA. Percent.mt])

VlnPlot(obj, features = c("nFeature_RNA"), pt.size = 0.5)
![image](https://user-images.githubusercontent.com/33207886/66610667-2ec4ec00-eb71-11e9-8cef-0a2e3e7d8234.png)

**Comment by NaomiCroft** [comment]
Thank you, very helpful :)
