### ISSUE TITLE
SCTransform and Integration of Multiple Patient Samples

### ISSUE THREAD

**Issue by nevilledusaj** [satijalab/seurat#2193]
Hello,

We are trying to integrate a series of patient samples using SCTransform for normalization. However, following integration, it appears that the expression levels of genes remains discretized in the first sample into which Seurat tries to integrate. Is this expected, and is there a reason Seurat doesn't use the "scale.data" slot from the SCTransform step for integration purposes? I am mostly curious about how this might impact clustering and dimensionality reduction downstream, if the expression levels of one sample are structured so differently from the other 3 (this issue appears to be consistent across all genes I have checked so far). Also, I am pretty certain that it is not an issue with the sample in question since, if I change the order in which Seurat integrates the sample, it switches to whatever the first sample integrated into is (as in the 2nd image). 

Thanks,
Neville

![Rplot](https://user-images.githubusercontent.com/44072764/66584823-cf0c1800-eb53-11e9-97d8-b16fe64c3bdd.png)
![image (2)](https://user-images.githubusercontent.com/44072764/66584836-d59a8f80-eb53-11e9-9e9f-27f4292f1db5.png)

**Comment by yuhanH** [comment]
HI, Neville
For the SCTransform normalized data, we use `scale.data` to do the integration. 
When you did the violin plot, the default slot is data slot. You could set the slot to `scale.data` and it will not be discretized.

**Comment by nevilledusaj** [comment]
HI Yuhan,

These plots are from the `scale.data` slot in the "integrated" assay (and the plots from the `data` slot look identical as well). In the "SCT" assay, you are correct, that the `data` slot appears discretized across all samples while the `scale.data` slot does not. My understanding is that the "integrated" assay is the one being used for steps such as `RunPCA` and `RunUMAP`, in which case the data I've plotted above would be inconsistent when going from the single sample with discrete expression levels to the other three. Or is PCA/UMAP for integrated datasets run using a different assay than "integrated"?

Thanks,
Neville

**Comment by satijalab** [comment]
Hi Neville. Could you make sure you are running with the latest Seurat version (3.1.1)? You should see integrated values mirror the range for the scale.data slot of the reference dataset.

If you don't see this,  please can you send your commands/output using one of the vignette examples?

**Comment by nevilledusaj** [comment]
Hello,

Updating to 3.1.1 from 3.1.0 changed the results significantly! For the gene plotted above in the original post, the distributions are much more similar in structure. However, for a couple genes I quickly tested, there still appear to be soft "levels" in one or more samples (examples below). Is this something you have noticed before?

Thanks,
Neville
![Rplot](https://user-images.githubusercontent.com/44072764/66721908-97ac9e00-edd5-11e9-98b1-2b3bc59de1cd.png)
![Rplot01](https://user-images.githubusercontent.com/44072764/66721910-97ac9e00-edd5-11e9-8b66-767ad2b15223.png)
![Rplot02](https://user-images.githubusercontent.com/44072764/66721911-97ac9e00-edd5-11e9-8101-57e46ffb416d.png)
