### ISSUE TITLE
Can't install Seurat on MacBook Pro

### ISSUE THREAD

**Issue by xietinglily** [satijalab/seurat#2194]
Hi I was trying to install seurat but it's not successful. install 'data.table' is unsuccessful. 

I'm using a MacBook Pro. R Studio Version 1.2.5001, R Version R 3.6.1 GUI 1.70 El Capitan build (7684).

Thank you!

> install.packages("Seurat")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/Seurat_3.1.1.tgz'
Content type 'application/x-gzip' length 3105101 bytes (3.0 MB)
==================================================
downloaded 3.0 MB

The downloaded binary packages are in
	/var/folders/cl/gd5fjfkd3zbcxz5c_xythldxkdxmnt/T//RtmpCK006h/downloaded_packages
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’

> install.packages("data.table")

  There is a binary version available but the source
  version is later:
           binary source needs_compilation
data.table 1.12.2 1.12.4              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
installing the source package ‘data.table’

trying URL 'https://cran.rstudio.com/src/contrib/data.table_1.12.4.tar.gz'
Content type 'application/x-gzip' length 5010321 bytes (4.8 MB)
==================================================
downloaded 4.8 MB

* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c assign.c -o assign.o
clang: error: unsupported option '-fopenmp'
make: *** [assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/data.table’
Warning in install.packages :
  installation of package ‘data.table’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/cl/gd5fjfkd3zbcxz5c_xythldxkdxmnt/T/Rtmp9NZXLm/downloaded_packages’
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’

**Comment by timoast** [comment]
This is an issue with the installation of `data.table` not `Seurat`, please open an issue with them

**Comment by GULIRAYNA** [comment]
I have got the same error in macbook pro with same version. Did you find any solution yet?
