### ISSUE TITLE
Error: Default assay will be removed 

### ISSUE THREAD

**Issue by reginawongg** [satijalab/seurat#2195]
Hi, when I'm trying to split my seurat object using SplitObject I get the following error and I'm not sure why. 

intdata.list <- SplitObject(object = intdata, split.by= "samp")

Error: Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay.

Does someone else come across the same error when running SplitObject?

Thanks!

**Comment by yuhanH** [comment]
Hi,
Could you provide more information about your object?
What analysis did you do in this object?
