### ISSUE TITLE
FindMarkers, Error in WhichCells

### ISSUE THREAD

**Issue by GBeattie** [satijalab/seurat#2196]
Hey,

Attempting to run DE on my sample based on custom metadata "expanded", which contains cells which are either NA or a number value (hoping to perform DE between the two).

My command looks like this:

`expanded.Treg.wt.negbinom <- FindMarkers(temp.combined, group.by = 'expanded', ident.1 = 'NA', test.use = "negbinom", logfc.threshold = 0.0)`

and the error looks like this:
```
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: NA
```

**Comment by mojaveazure** [comment]
Hi Gordon,

Could you provide a dataset, subset of a dataset, or an example using one of the [SeuratData](https://github.com/satijalab/seurat-data) datasets so we can test this?

**Comment by GBeattie** [comment]
Hey, sorry for the late response, I figured out it was due to the "expanded" metadata being a factor variable, I converted to numeric and changed my NA's to 0 as below which was a satisfactory fix.

```
wt.combined@meta.data[["expanded"]] <- as.numeric(wt.combined@meta.data[["expanded"]])
wt.combined@meta.data[["expanded"]][is.na(wt.combined@meta.data[["expanded"]])] <- 0
```
