### ISSUE TITLE
Which correlation method("pearson" (default), "kendall", or "spearman") to compute the correlation score between different clusters of SC-RNAseq data?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#2198]
Hello, Seurat team
I'm wondering how to choose the correlation method("pearson" (default), "kendall", or "spearman") if I want to compute the correlation score between different clusters?
Since Pearson method is Parametric correlation and Spearman is non-parametric correlation, how do I 
make sure my data type and choose a right method?
Below is my gene expression matrix: rows are gene names,and columns are clusters.I use the default Pearson method to do analysis,but I really don't know if it is right.
Below is my code:
```
CorOb.av.exp <- AverageExpression(CorOb)$RNA
dim(CorOb.av.exp)
CorOb.cor.exp <- as.data.frame(cor(CorOb.av.exp))
CorOb.cor.exp$x <- rownames(CorOb.cor.exp)
neupeptide.cor.df <- tidyr::gather(data = CorOb.cor.exp, y, correlation,CorOb.cor.exp$x)
a <- ggplot(neupeptide.cor.df, aes(x, y, fill = correlation)) + geom_raster()+scale_fill_gradientn(colors = c("blue", "white", "red"))+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()

a
```

**Comment by timoast** [comment]
Closing this issue as answers have been posted on bioinformatics stack exchange: https://bioinformatics.stackexchange.com/questions/10582/which-correlation-method-to-compute-the-correlation-score-between-different-clus
