### ISSUE TITLE
Passing in Matrix 

### ISSUE THREAD

**Issue by emerygoossens** [satijalab/seurat#22]
Hello, 

I am having trouble working with my own data. When I create a new seurat object with a matrix and then try to do the Setup function, I get the following error:

conway <- Setup(conway, min.cells = 3, min.genes = 200, do.logNormalize = T, total.expr = 1e4, project = "conway")
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

**Comment by emerygoossens** [comment]
I believe this was an issues with the Matrix package that needed to be updated.

**Comment by huangkang314** [comment]
Tring Matrix::colSums( ) instead of colSums()
