### ISSUE TITLE
Add/Remove Variable genes/features in seurat object

### ISSUE THREAD

**Issue by hlmeng** [satijalab/seurat#2200]
After running FindVariableFeatures, Seurat will perform PCA and clustering analysis on the gene expression profiles on those high variable genes. I wonder what is the best way to 1) add a list of genes OR 2) get rid of a list of genes from selected high variable genes for future PCA/Clustering analysis.

Thank you so much!

**Comment by mojaveazure** [comment]
Please see [`VariableFeatures<-`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/VariableFeatures)

**Comment by hlmeng** [comment]
Thanks! I have multiple samples. I guess I need to add extra genes to var.features before I run "FindIntegrationAnchors" and "IntegrateData". In that case, it does not grantee that the added genes  can be survived until PCA/Clustering analysis. Is that correct? Or is there a better way to do it? Thank you.
