### ISSUE TITLE
subset to include two groups based on nFeature_RNA numbers

### ISSUE THREAD

**Issue by stephanyfoster** [satijalab/seurat#2202]
hello-
I want to subset my data to include cells containing 1500-2500 features and cells containing 4500-6000 features, Is this possible with Seurat V3?
If I try to include in one command I get an error, not sure how to proceed?

S1 <- subset(S1, subset = nFeature_RNA > 1500 & nFeature_RNA < 2500 & nFeature_RNA > 4500 nFeature_RNA < 6000)

Error in cells %||% colnames(x = object) : 
  object 'nFeature_RNA' not found

**Comment by AndyR2** [comment]
this might work:
If you have an object with the nFeature_RNA range >1500 & <6000, then you can subset with "invert", like so:

S1 <- subset(S1, subset = nFeature_RNA > 2500 & nFeature_RNA < 4500, invert = TRUE)

**Comment by stephanyfoster** [comment]
this worked! thank you
