### ISSUE TITLE
MULTIseqDemux or HTODemux

### ISSUE THREAD

**Issue by bio-la** [satijalab/seurat#2203]
Hi,
I have a very noisy multiplexed dataset (chemically barcoded cells) and I seem to get very good results with your new MULTIseqDemux. #1273 

Can you comment on when it would be better to default to MULTIseqDemux instead of HTOdemux? my guess is that the default HTODemux works great for very clean hashing data because the Ab counts tend to be very clean, but as soon as you have more than 10 ab or noisy tagging, this will result in calling all cells doublets (cause the threshold to be called a singlet is very low for each single tag, so it's easier for a cell to be called doublet)

What's the rationale behind autoThresh=False, which automatically triggers ClassifyCells, can you comment on how this works and suggest a set of optimal params for a likely scenario?

I guess that setting autoThresh to True will perform as described in "MULTI-seq: sample multiplexing for single-cell RNA sequencing using lipid-tagged indices" but I'm not sure I want the function to classify my cells into singlets at all costs - at least that's what I seem to understand the iteration should achieve.

any suggestion appreciated, thanks!

**Comment by satijalab** [comment]
This is really a question for the Multi-seq developers, so I will close it here and refer you to 
https://github.com/chris-mcginnis-ucsf/MULTI-seq

Feel free to post any updates here if you feel there is info that would be useful to Seurat users.
