### ISSUE TITLE
Should I remove batch effect by integration?

### ISSUE THREAD

**Issue by peaceisking** [satijalab/seurat#2204]
I have already seen [Can not remove batch effect by ScaleData ! #1351](https://github.com/satijalab/seurat/issues/1351) 

 But I still have some questions, for example ,I have 4 groups, each with 5 samples.
       
 If I only wanna combine samples in a group together, should I use regress.out in sctransform  function after merge function ,or with integration ?  
 Should I use regress.out  when the samples in a groups are similar,  like the pictures below
![image](https://user-images.githubusercontent.com/46219838/66844857-a3e55680-efa1-11e9-9081-146dc09efe2c.png)

and use integration when the samples are not similar, just like the picture below ?
![image](https://user-images.githubusercontent.com/46219838/66844954-cf684100-efa1-11e9-9733-8dbfa6742e60.png)

       
And what if I wanna combine samples between groups together ? regress.out or integration?
    
Hope you reply
Best

**Comment by satijalab** [comment]
We don't typically recommend using regress out to combine samples, as this assumes that both samples have exactly the same cell types at the same proportions, and that all cell types have the same batch effect.

You should perform integration if you are struggling to identify shared biological states across your datasets. If shared cell types in your samples cluster together under a standard analysis (like your first plot), there is no need for applying integration workflows
