### ISSUE TITLE
Numerous significant PCs in JackStraw plot when using SCtransform/Integration approach

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#2205]
Hello,

Thanks for implementing the `sctransform` approach I read through the issues and found some helpful posts. In my case, I'm trying to use sctransform and combine 6 datasets as recommended [in this workflow](https://github.com/satijalab/seurat/issues/1836#issuecomment-513063259). Here is my code:

```
yng_ctr <- SCTransform(yng_ctr, vars.to.regress = "percent.mt", verbose = F, return.only.var.genes = F)
old_ctr <- SCTransform(old_ctr, vars.to.regress = "percent.mt", verbose = F, return.only.var.genes = F)
yng_hu <- SCTransform(yng_hu, vars.to.regress = "percent.mt", verbose = F, return.only.var.genes = F)
old_hu <- SCTransform(old_hu, vars.to.regress = "percent.mt", verbose = F, return.only.var.genes = F)
yng_rel <- SCTransform(yng_rel, vars.to.regress = "percent.mt", verbose = F, return.only.var.genes = F)
old_rel <- SCTransform(old_rel, vars.to.regress = "percent.mt", verbose = F, return.only.var.genes = F)


anchors <- FindIntegrationAnchors(list(yng_ctr, old_ctr, yng_hu, old_hu, yng_rel, old_rel), dims=1:30)
combined <- IntegrateData(anchorset = anchors, dims = 1:30, normalization.method = "SCT")


combined <- RunPCA(object = combined, npcs = 30, verbose = FALSE)


combined <- RunUMAP(object = combined, reduction = "pca", dims = 1:30)


combined <- FindNeighbors(combined, dims = 1:30, verbose = FALSE)
combined <- FindClusters(combined, verbose = FALSE)

DimPlot(combined, label = TRUE) + NoLegend()

combined <- JackStraw(combined, num.replicate = 100, dims = 30)
combined <- ScoreJackStraw(combined, dims = 1:30)

ElbowPlot(combined, ndims = 30)
JackStrawPlot(combined, dims = 1:30)
```
## Elbow plot output
![image](https://user-images.githubusercontent.com/38366155/66863283-eb42f700-ef4f-11e9-9f6c-2a8daf840d11.png)

## Jackstraw plot output
![image](https://user-images.githubusercontent.com/38366155/67023947-d8036900-f0c0-11e9-9df0-d1d5611b2eed.png)

### My specific questions:
__1.__ I wasn't expecting to see all the 30 PCs to look highly significant. Am I doing something wrong here?

__2.__ In other posts, I saw `SelectIntegrationFeatures` and `PrepSCTIntegration` functions are used before finding anchors and integrating. I'm a bit unclear what these do differently than finding integration anchors.
 
Thanks so much for the awesome, awesome work!

**Comment by atakanekiz** [comment]
I just found the vignette about SCtransform integration. In light of that, I think my code is incomplete here because I didn't use the `SelectIntegrationFeatures` and `PrepSCTIntegration` functions.  I'm still curious to understand though why all these PCs look highly significant.

**Comment by atakanekiz** [comment]
I think part of my question had to with not fully understanding what's happening under the hood. The second question regarding several PCs being highly significant, may be a dataset-specific observation, and there is another post asking how to decide on the dimensions for downstream analysis. I will close this issue, as new answers to other posts will probably address similar points. Thanks for all the efforts!

**Comment by aepstein96** [comment]
Did you ever figure out what was causing multiple highly significant PCs? I am encountering the same issue, but have not found any other threads about it. I assume it is due to some intrinsic property of the dataset, but I am not sure how best to deal with it.

**Comment by atakanekiz** [comment]
I haven't really. I think there might be a real biological reason as opposed to a technical artifact. I recommend trying different numbers of PCs to see what makes sense better.

**Comment by davisidarta** [comment]
> No, I didn't really. I think there might be a real biological reason as opposed to a technical artifact. I recommend trying different numbers of PCs to see what makes sense better.

I'd imagine in that case you're dealing with highly non-linear data (PCA assumes data low dimensional structure is linear). I'd recommend trying a diffusion approach for fast fully non-linear dimensionality reduction, as with [dbMAP](https://github.com/davisidarta/dbMAP).
