### ISSUE TITLE
how to get the gene list with highest correlation to a given gene list 

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#2208]
Hi, I previously performed `AddModuleScore()` based on those genes (ex. neuronal marker genes) I interested in. However, the result was not good enough: all differentiation score were similar across all cells, which means all clusters may have no significant difference in differentiation score (ex. neuranal score , immunal score, and etc.) on raw data or processed data. Please have a look at the attached figure.

![20190808_Cell_Score_of_GABAergic neuron_RawData_](https://user-images.githubusercontent.com/49429496/66919835-ad7bc680-f054-11e9-829f-0c745778cd80.png)
![20190808_Cell_Score_of_GABAergic neuron_ProcessedData_](https://user-images.githubusercontent.com/49429496/66919836-ae145d00-f054-11e9-8d71-50a1feecb731.png)

Hence, I hypothesized that this bad result may result from the limited number of genes I input. And I want use the correlation analysis to found out genes that correlate with the gene list I give (maybe in the sample I have, or in the specific normal cell from others paper). Then,  I would perform `AddModuleScore()` again based on marker genes and correlated genes.

**Comment by satijalab** [comment]
We don't have a function to automate this in Seurat, but you can use a combination of a `for` loop in R and the `cor` function to compute individual gene correlations, and then choose the top values.
