### ISSUE TITLE
Error with PrintCalcParams() function

### ISSUE THREAD

**Issue by FloWuenne** [satijalab/seurat#221]
Hi there,

I am also getting an error with the PrintCalcParams() function when using it on any of my objects.  A friend of mine tried to run it on an independent dataset on a different machine and had the same error:

```
printCalcParams(object = expression_seurat)
Error in object@calc.params[[calculation]] : 
  invalid subscript type 'symbol'
```

Are we using the function wrong or is there an issue with the function not working correctly?

**Comment by leonfodoulian** [comment]
Hello Florian,

You have to specify the `calculation` argument (i.e. the function name) in the code you're running (e.g. `"RunPCA"`, `"RunTSNE"`). Please check the R documentation of the function by running `?PrintCalcParams` in R.

Best,
Leon

**Comment by FloWuenne** [comment]
Hi Leon,

thanks for the clarification. I thought you could also use the function without specific arguments to get all calculated parameters of that Seurat object. From the tutorials it sounded that way. 

Correctly calling the function with RunPCA or RunTSNE obviously works fine. 
Ticket can be closed for my question. I still think it would be nice to get a complete Params report when not specifying any calculation though :).

**Comment by leonfodoulian** [comment]
Hello Florian,

I am not sure whether the documentation states that. It rather says _"Print entire contents of calculation settings slot (calc.params) for given calculation"_. _"Given calculation"_ meaning a specific calculation function (i.e. RunPCA or RunTSNE). I agree that a more generic function printing all parameters would be helpful. You could keep the issue opened and potentially discuss with Andrew or Rahul about this. 

Best,
Leon
