### ISSUE TITLE
Error in ”Gene activity quantification” for scATAC analysis

### ISSUE THREAD

**Issue by xbjie123** [satijalab/seurat#2210]
Hi,

I'm using the scATAC tutorial for analysis. However, I got the error information when I did the 1st step.

The error is` logical subscript contains NAs`

Here I list my code.

```
peaks <- Read10X_h5("E:/BJ/scATAC/raw_data/rep1/filtered_peak_bc_matrix.h5")
chromosomes = c(1:25)
chromosomes = paste("chr", chromosomes, sep="")
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "E:/BJ/scATAC/raw_data/genes_corrected.gtf", seq.levels = chromosomes, upstream = 2000, verbose = TRUE)

```
And the gtf file has already been rewritten according to 
`sed -e 's/CDS/gene/g' genes.gtf > genes_corrected.gtf`

So, could you help me with this issue?
Thanks very much~~
Hope to get your reply.

Baijie

**Comment by timoast** [comment]
Hi, sorry for the delay here. We have developed another package that contains functions for computing a more accurate gene activity matrix, and we recommend that you use that instead: https://satijalab.org/signac/
