### ISSUE TITLE
About merging RNA velocity Seurat object 

### ISSUE THREAD

**Issue by Lobbii** [satijalab/seurat#2212]
Hi, I am trying to merge several Seurat objects includes RNA velocity, and here is the error:

Error in GetAssay.Seurat(object = object, assay = assay) :
RNA is not an assay present in the given object. Available assays are: spliced, unspliced, ambiguous, SCT

How should I fix it ?

**Comment by torkencz** [comment]
You should double check if all of the objects you are trying to merge have matched assay names. You can fix it by renaming assays with the RenameAssays command.
