### ISSUE TITLE
Feature names not working with CreateSeuratObject

### ISSUE THREAD

**Issue by CamilleCouture** [satijalab/seurat#2213]
So I work with Drosophila (fruit fly) genes and their gene names, unlike mammals, they have a lot of characters ie. "(", ")", "-". This is a huge problem when I try to create a Seurat object because it converts them all to dots "."

Is there a way to make Seurat objects while keeping their original names?

Thanks!!

**Comment by timoast** [comment]
Right now we do need to enforce this character change in Seurat. I think this would only be a problem if there are genes that become non-unique after changing those characters to a ".", eg two genes named "Gene,1" and "Gene-1". Is that really the case in Drosophila?

**Comment by CamilleCouture** [comment]
No it is not the case, however if I want to look at gene ontology or do quick comparisons it no longer works because genes cannot be recognized since they are not correctly written out - there are ~1000 genes with this issue so not trivial to fix otherwise

**Comment by timoast** [comment]
You could make a lookup table to get back the original gene name, for example:

```r
gene.names <- rownames(counts) # from the original count matrix, before gene names are modified by Seurat
names(gene.names) <- gsub(pattern = "-|,", replacement = ".", x = gene.names)

# to then get original names, for example from the output of FindMarkers
orig.names <- gene.names[[rownames(markers)]]
```

Seurat only converts "_" to "-". but other characters like "," and "-" are sometimes converted by R to "." if they are in the rownames of a dataframe or matrix. If the gene names are already modified in the count matrix, you'll need to read in the unmodified gene names from somewhere else (like the features.tsv.gz file from 10x for example) but then just follow the same strategy as above
