### ISSUE TITLE
Version of seurat objects

### ISSUE THREAD

**Issue by vwtlin** [satijalab/seurat#2215]
Hi all,

I am a web-lab guy, totally a newbie to scRNA-seq analysis and starting to learn Seurat. Quickly comes up with a very naive question. 

My Seurat objects are generated by Seurat v2 by bioinformaticians. Could I directly apply Seurat v3 to analyse these objects? Or what do I need to do any conversion?

Thanks in advance.

**Comment by timoast** [comment]
Hi, you will need to update v2 Seurat objects to v3 to use Seurat v3. You can do this using the `UpdateSeuratObject` function
