### ISSUE TITLE
FindIntegrationAnchors Error

### ISSUE THREAD

**Issue by reginawongg** [satijalab/seurat#2216]
Hi, 

I created a merged Seurat object with 7 datasets and I'm trying to do the following step: 

`datas.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)`

However, I get this error: 

```
Error in scale.function(mat = object[features[my.inds], split.cells[[x]],  : 
  std::bad_alloc
```

Has anyone come across this error before?

The only thing I find different in my datas Seurat object is the active.ident. In the pancreas tutorial active.ident is a Factor with 14980 levels: "celseq", "celseq".. etc and the D101_5 is a Factor with 1 levels: "celseq". 

However, in my dataset, active.ident is a Factor with 1 level. Would this be a problem and how can I fix this? Any help or comments are appreciated!

Thank you so much!

**Comment by ArtemiyGolden** [comment]
Hi, I have the exact same issue!

Have you managed to find a solution?
