### ISSUE TITLE
Loading input files

### ISSUE THREAD

**Issue by bryanyung** [satijalab/seurat#2218]
Hello, I'm new to RNAseq and I'm trying to run Seurat on some datasets. I currently practicing on this database: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE99254

I downloaded the norm.center.txt, count.txt., and TPM.txt. files and I was wondering which file I should use to create the seurat object with (following the PBMC vignette), and what commands to use to incorporate it.

**Comment by sri540** [comment]
It should be a count matrix -> count.txt.

**Comment by bryanyung** [comment]
after running CreatSeuratObject, I get this warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion

Also, when trying to normalize data, I get this error:
Error: Attempting to add a different number of cells and/or features

**Comment by phoebee-h** [comment]
Check this. Maybe you should specify the "row name" column.
https://github.com/satijalab/seurat/issues/1615

**Comment by phoebee-h** [comment]
Data you've provided contains both "geneID" and "symbol" column, which "symbol" column is with duplicated name and thus you can only set "geneID" as row name. 

I have no problem doing this:
```
data1 <- read.table("GSE99254_NSCLC.TCell.S12346.count.txt",row.names = 1,header = T)
data <- data1[-1]　
# Just take a look at your data. 
data[1:3,1:5]
test <- CreateSeuratObject(counts = data, project = "GSE99254")

```

I'm not from official. 
A friendly reminder that you should always check your data format first.
