### ISSUE TITLE
CollapseSpeciesExpressionMatrix on 10x Output

### ISSUE THREAD

**Issue by JenniferWUSTL** [satijalab/seurat#2219]
Good afternoon, I am trying to run the _CollapseSpeciesExpressionMatrix_ function on CITE-seq data run through the 10x platform.  I can get the same code to work on data that does not include the ADT tags in the output (10x genomics example species-mixing gene expression data).  Is there a way to _CollapseSpeciesExpressionMatrix_ using the 10x output (barcodes.tsv, features.tsv, matrix.mtx) that combines gene expression and ADT into the same file? 

This is my code and corresponding errors: 
> test.data = Read10X("/Users/username/Box/clustertest/filtered_feature_bc_matrix")
10X data contains more than one type and is being returned as a list containing matrices of each type.
> test.data <- CollapseSpeciesExpressionMatrix(test.data, prefix = "GRCh38_", controls = "mm10_", ncontrols = 100)
Error in object[controls, ] : incorrect number of dimensions

Thank you for your time!

**Comment by satijalab** [comment]
Thanks - is your data from an experiment that includes both human and mouse cells? The input feature matrix has to have at least 100 genes that start with GRCh38_, and 100 genes that start with mm10_. I am guessing that your matrix does not have this, but if you can verify that it does, please reopen the issue

Of course, if your experiment has only a single species, there is no need to run this function

**Comment by cpcook1** [comment]
@JenniferWUSTL I found this error to be the result of not pointing back at the gene expression matrix when subsetting. For example if you do:

`Object$"Gene Expression" <- CollapseSpeciesExpressionMatrix(Object$"Gene Expression",
                prefix = "mm10_", controls = "GRCh38_", ncontrols = 0)`

Or similar (given your own parameters) It should collapse the rownames

**Comment by JenniferWUSTL** [comment]
That works, thank you very much!
