### ISSUE TITLE
Gene Ontology Background Genes

### ISSUE THREAD

**Issue by rohan913** [satijalab/seurat#222]
Hello,

I wanted to perform GO enrichment within a specific cell type I identified with Seurat. I broke the cluster into a few sub groups and I wanted to look at GO processes enriched in each sub cluster using a list of background and target genes. I was wondering what the best way to get the background list of genes using Seurat data would be. So far I have tried FindAllMarkers with a threshold of 0 while keeping the other defaults, but depending on how other parameters (like min.pct) are set the list of genes can vary in size. Is there certain way I should be working with Seurat to optimize my list? Any insight would help. 

Thank you,
Rohan

**Comment by satijalab** [comment]
This is an interesting question, but a bit outside of the scope of Seurat. Certainly, removing non-expressed genes from the background list, has been shown to help GO enrichment, but setting thresholds for this is not something we have experience with. You can read https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0761-7 and other articles for more info.
