### ISSUE TITLE
Fetching top K nearest neighbors per cell when doing ATAC/RNA pairing

### ISSUE THREAD

**Issue by vkartha** [satijalab/seurat#2220]
Hi, 
  When performing the ATAC/RNA dataset pairing as per the turorial, is there is a way to fetch  the top N (say 50) nearest neighbors per cell from 1 data set in the other based on the shared lower dimensional space? Perhaps using something stored in the object somewhere after determining the transfer/integration anchors?)

I know that there are parameters (k.anchor, k.filter, k.score) for specifying how the anchors are determined / filtered, but I don't think that helps me here?

Thanks

**Comment by satijalab** [comment]
We don't explicitly support this, as we don't return the results from the CCA in the anchor set (perhaps we should). However, you can easily recreate the L2-CCA space here (code is taken from FindIntegrationAnchors).

Once you have this, you can use FindNeighbors or NNHelper to get a list of neighbors.

```
        object.pair <- RunCCA(
            object1 = object.1,
            object2 = object.2,
            assay1 = assay[i],
            assay2 = assay[j],
            features = anchor.features,
            num.cc = max(dims),
            renormalize = FALSE,
            rescale = FALSE,
            verbose = verbose
          )
          if (l2.norm){
            object.pair <- L2Dim(object = object.pair, reduction = reduction)
            reduction <- paste0(reduction, ".l2")
            nn.reduction <- reduction
          }
```
