### ISSUE TITLE
R/rstudio crashes when loading seurat 

### ISSUE THREAD

**Issue by jkanche** [satijalab/seurat#2223]
Hello,

I don't remember having this issue before but rstudio crashes when loading the `Seurat` package. I tried both the published version on CRAN and the development version from github. Both cause the same error - screenshot - https://imgur.com/a/jYjAGc6

If this is a known issue, let me know if there's a fix. 

I'm on Arch linux and my session info -

> sessionInfo()
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Manjaro Linux
> 
> Matrix products: default
> BLAS:   /usr/lib/libopenblasp-r0.3.7.so
> LAPACK: /usr/lib/liblapack.so.3.8.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.1 tools_3.6.1

**Comment by PaniGopaluni** [comment]
Just wondering if you had any update on this? I am having a similar issue and this seems to be specific to RStudio as I could use Seurat via base R using terminal. When I type library(Seurat) in RStudio, it gets busy but nothing happens and after a while it crashes. I thought this started after installing "leiden" which I removed and reinstalled current version and developer version but not able to resolve the issue. I would really appreciate a fix to this problem. Below, is my sessionInfo()

Many thanks,
Pani

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0

**Comment by jkanche** [comment]
not sure, I figured it was specific to rstudio since I could still run Seurat in an R terminal. Probably something to do when it loads Rcpp class files

**Comment by PaniGopaluni** [comment]
I could resolve it by loading version 3.0.0

Hope that helps.
Pani

**Comment by timoast** [comment]
This seems to be more of an RStudio issue if you can run Seurat in R but not RStudio, so I will close this for now

**Comment by olneykimberly** [comment]
Trying running in R and it still crashes

Process:               R [38098]
Path:                  /Applications/R.app/Contents/MacOS/R
Identifier:            org.R-project.R
Version:               R 3.6.0 GUI 1.70 El Capitan build (7657)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           R [38098]
User ID:               501

**Comment by deliasoto** [comment]
Hello, I'm having the same problem and started after Seurat requested installing miniconda. Before that everything was working fine.
Any recommendations?!
