### ISSUE TITLE
FeatureScatte split by orig.ident

### ISSUE THREAD

**Issue by francescarivello** [satijalab/seurat#2224]
I am using Seurat to analyze my inDrop experiments over different stimulation times. I stored the stimulation times in the meta.data of the Seurat object under orig.ident
I would like to plot using FeatureScatter the correlations between two genes which I do giving the following command:
FeatureScatter(combined_Seu_6clusters, feature1 = "VEGFA", feature2 = "EGR1", group.by = "orig.ident", pt.size = 2)

However this leads to one plot with all the stimulation times overlapping. I would like to see one plot per each stimulation time. In FeatureScatter I cannot add split.by = "orig.ident"

How to do otherwise?

**Comment by timoast** [comment]
Hi, we don't support this right now but could think about adding it in the future. In the meantime you could either subset the data and create different plots for different subsets, or extract the data using `GetAssayData` and create the plots using ggplot2.

**Comment by francescarivello** [comment]
Thank you Tim for the quick reply. I was also having some trouble on su setting a Seurat object based on orig.identity = 3h for example. Which kind of command should I give?

**Comment by timoast** [comment]
You can subset to keep idents == "3h" like so:

```r
sub.obj <- subset(object, idents = "3h")
```

**Comment by satijalab** [comment]
I'll just add that I agree this would be a very useful enhancement

**Comment by rsatija** [comment]
Have implemented this and will come out with the next develop release. Closing the issue now for our internal accounting
