### ISSUE TITLE
Reference numbers in Reciprocal PCA 

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2225]
[anchors <- FindIntegrationAnchors(object.list = bm40k.list, **reference = c(1, 2)**, reduction = "rpca", 
    dims = 1:30)
](url)
I have to add more than two samples as a reference? When I add my three samples like this reference = **c(1, 2, 3)** i got following error? How can i make it?

[Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 'x' must be atomic
6.
stop("'x' must be atomic")
5.
sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4.
sort.default(x = reference)
3.
sort(x = reference)
2.
unique(x = sort(x = reference))
1.
FindIntegrationAnchors(object.list = combined.organ, reference = list(c(8, 10, 9)), reduction = "rpca", dims = 1:50)](url)

[Since this dataset contains both men and women, we will chose one male and one female (BM1 and BM2) to use in the reference-based workflow. We determined donor sex by examining the expression of the XIST gene. Next, identify anchors and integrate the datasets. Commands are identical to the standard workflow, but make sure to set reduction = 'rpca':

**Comment by timoast** [comment]
Hi, I think the problem here is that you are supplying a list with one element (`list(c(8,10,9))`) rather than a numeric vector. Just change to this and it should then work:

```r
FindIntegrationAnchors(object.list = combined.organ, reference =c(8, 10, 9), reduction = "rpca", dims = 1:50)
```

**Comment by JayalalKJ** [comment]
> anchors <- FindIntegrationAnchors(object.list = combined.organ,reference =c(8,9,10), reduction = "rpca",dims = 1:50)
Computing 2000 integration features
Scaling features for provided objects
Computing within dataset neighborhoods
**[Error in FindIntegrationAnchors(object.list = combined.organ, reference = c(8,  : 
  Error: requested reference object 10 but only 3 objects provided](url)**

**Comment by timoast** [comment]
How many objects are in `combined.organ`?. The error message says you've supplied 3 objects and requested to use object 8, 9, and 10 as the reference objects

**Comment by JayalalKJ** [comment]
Yes, I had created three objects instead of 19. Now, I resolved the issue
Thanks.  Tim
