### ISSUE TITLE
Error in FindTransferAnchors: CellsByIdentities fails

### ISSUE THREAD

**Issue by martaint** [satijalab/seurat#2226]
Dear Seurat developers,
I am using FindTransferAnchors with both reference and query datasets result of the integration using SCT normalization. Each dataset was processed separately, but in the same way. When I call 
`FindTransferAnchors(reference = reference.integrated, query = query.integrated,
                                      normalization.method = "SCT", dims = 1:30, 
                                      reference.assay = "integrated", query.assay = "integrated")`

I get the error
`Performing PCA on the provided reference using 3000 features as input.
Projecting PCA
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided`

Could you help me with this issue? Thanks a lot!!

`> sessionInfo() R version 3.6.1 (2019-07-05) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Debian GNU/Linux 9 (stretch)  Matrix products: default BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] panc8.SeuratData_3.0.2 SeuratData_0.1.0       RColorBrewer_1.1-2     sctransform_0.2.0      [5] ggplot2_3.2.1          Seurat_3.1.1            loaded via a namespace (and not attached):  [1] nlme_3.1-140        tsne_0.1-3          bitops_1.0-6        RcppAnnoy_0.0.13    httr_1.4.1           [6] tools_3.6.1         backports_1.1.5     R6_2.4.0            irlba_2.3.3         KernSmooth_2.23-15  [11] uwot_0.1.4          lazyeval_0.2.2      colorspace_1.4-1    withr_2.1.2         npsurv_0.4-0        [16] tidyselect_0.2.5    gridExtra_2.3       compiler_3.6.1      cli_1.1.0           plotly_4.9.0        [21] caTools_1.17.1.2    scales_1.0.0        lmtest_0.9-37       ggridges_0.5.1      pbapply_1.4-2       [26] stringr_1.4.0       digest_0.6.21       R.utils_2.9.0       pkgconfig_2.0.3     htmltools_0.4.0     [31] bibtex_0.4.2        htmlwidgets_1.5.1   rlang_0.4.0         rstudioapi_0.10     zoo_1.8-6           [36] jsonlite_1.6        ica_1.0-2           gtools_3.8.1        dplyr_0.8.3         R.oo_1.22.0         [41] magrittr_1.5        Matrix_1.2-17       Rcpp_1.0.2          munsell_0.5.0       ape_5.3             [46] reticulate_1.13     lifecycle_0.1.0     R.methodsS3_1.7.1   stringi_1.4.3       gbRd_0.4-11         [51] MASS_7.3-51.4       gplots_3.0.1.1      Rtsne_0.15          plyr_1.8.4          grid_3.6.1          [56] parallel_3.6.1      gdata_2.18.0        listenv_0.7.0       ggrepel_0.8.1       crayon_1.3.4        [61] lattice_0.20-38     cowplot_1.0.0       splines_3.6.1       SDMTools_1.1-221.1  zeallot_0.1.0       [66] knitr_1.25          pillar_1.4.2        igraph_1.2.4.1      future.apply_1.3.0  reshape2_1.4.3      [71] codetools_0.2-16    leiden_0.3.1        glue_1.3.1          lsei_1.2-0          metap_1.1           [76] RcppParallel_4.4.4  data.table_1.12.4   vctrs_0.2.0         png_0.1-7           Rdpack_0.11-0       [81] gtable_0.3.0        RANN_2.6.1          purrr_0.3.2         tidyr_1.0.0         future_1.14.0       [86] assertthat_0.2.1    xfun_0.10           rsvd_1.0.2          survival_2.44-1.1   viridisLite_0.3.0   [91] tibble_2.1.3        cluster_2.1.0       globals_0.12.4      fitdistrplus_1.0-14 ROCR_1.0-7
--`

**Comment by satijalab** [comment]
I believe this is due to an error in FindTransferAnchors when using the SCT workflow that has since been fixed. if the problem persists, please reopen this issue and we'll assign someone to look in detail.

**Comment by tina-roostaei** [comment]
Hi, 

I have a problem with IntegrateData which I think might be related to this issue, as I get the same error.

I have two integrated datasets (data1: n=19 samples and data2: n=17 samples) and I am trying to integrate the two together. The default assay for both data1 and data2 is "integrated". 
Here is my code:

data.list1 <- SplitObject(data1, split.by = "orig.ident")
data.list2 <- SplitObject(data2, split.by = "orig.ident")
data.list <- c(data.list1,data.list2)

data.features <- SelectIntegrationFeatures(object.list = data.list, nfeatures = 3000)
data.list <- PrepSCTIntegration(object.list = data.list, anchor.features = data.features)

reference_dataset <- which(names(data.list) == "xxx")
data.anchors <- FindIntegrationAnchors(object.list = data.list, normalization.method = "SCT", anchor.features = data.features, reference = reference_dataset,assay = rep("integrated",36), k.filter = 100)

data.integrated <- IntegrateData(anchorset = data.anchors, normalization.method = "SCT")

Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided

R version 3.6.2 (2019-12-12)
Seurat_3.1.4 

I would be grateful if you could help with this issue.
Thanks,
Tina
