### ISSUE TITLE
How to concurrently filter RNA and CITEseq data within seurat object

### ISSUE THREAD

**Issue by cpcook1** [satijalab/seurat#2227]
I have a Seurat object I created from RNA and CITEseq data. I load the matrices and create a seurat object with assays for each ("RNA" and "ADT"). The dimensions are identical as are the column barcodes. 

I want to filter the data based on counts/feature counts/%MT (so, from the RNA side) and subset the matrix with my filter, but have the cells removed from both the RNA and the ADT data set simultaneously. 

When I run: `Object <- subset(Object, subset = nCount_RNA > 1050 & nFeature_RNA > 300` or similar, the resulting matrix has the ADT assay deleted. I assume this is because I'm telling it to subset with only the RNA data, but its not clear to me how to remove the same cells from each assay at the same time?

**Comment by timoast** [comment]
Hi, both assays should be subset automatically. If this isn't happening, can you please provide a reproducible example using a dataset from the [`SeuratData`](https://github.com/satijalab/seurat-data) package?

**Comment by cpcook1** [comment]
Hi thanks for the reply. I tried it using the cbmc dataset and it subsets both fine. 

I found what the problem was. After I load in the ADT assay into the seurat object, I use a function to trim the names of the Abs in the row (its tagged with *-TotalseqA or similar).

If I skip this step and go on to the QC the cells from both assays subset fine..... weird huh?

**Comment by timoast** [comment]
You can't actually change the feature names after creating the object because this would mess up a few things, and might be why you have this problem with subset. If you need to change the ADT names, you should do it before creating the assay by changing the row names of the count matrix
