### ISSUE TITLE
1 features requested have not been scaled ? Why?

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2229]
Why one of the features, not scaled? How can I rectify this error in the further downstream analysis? 

[The following 1 features requested have not been scaled (running reduction without them): Mlf1ipYou're computing too large a percentage of total singular values, use a standard svd instead.PC_ 1](url)

**Comment by timoast** [comment]
In Seurat v3 we only scale the variable features by default. If you would like to scale other features too, you can pass a list of genes to `ScaleData` using the `features` parameter
