### ISSUE TITLE
Comparison of clusters through transcriptome similarities

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#2230]
Hi all, 

This is a data analysis question however i am not sure how to add a tag to this, apologies if this is not in the right place, but if somebody could advise i would be very greatful.

I have run a batch correction on various data that i have (multiple experiments with various organs). I have attached a section of the UMAP produced which shows the bulk of one sample clustering together as it should. whats really interesting is that there are some cells from other organs etc that are also similar to this organ! 

this is absolutely fine! however, i would like to show through a similarity matrix or something like this based on the transcriptome that indeed, the cells in this cluster that belong to different organs are more transcriptionally similar to this cluster than they are to their own organ of origin (which themselves have their own cluster)..

Is there a way of showing through some sort of similarity matrix based on the transcriptome in seurat that indeed these cells are closer to this cluster compared to their sample of origin. the reason i ask is that there are many tissues and so i would like another elegant form of comparing for example two or more clusters based on differences/similarities in the transcriptome of these cells?

I would need to prove some sort of similarity matrix that these cells are indeed more similar to their tissue of origin or not through transcriptional comparisons. 

many thanks!!

![Screenshot 2019-10-21 at 15 03 15](https://user-images.githubusercontent.com/33659783/67212846-ddd8b180-f414-11e9-8f49-e99b65bb0017.png)

**Comment by satijalab** [comment]
You can of course use some sort of measure of global similarity (transcriptome-wide correlation). You can use AverageExpression to calculate the pseudo-bulk profile of each cluster in each condition, and then calculate these correlations.

You can also use FindConservedMarkers to identify markers that are conserved in the same cluster across both conditions
