### ISSUE TITLE
 Visualize co-expression of more than two features (FeaturePlot)

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#2232]
Hi, 

Are there any updates about this option? 'blend=T' looks nice, but it would be great to look at co-expression of genesets. Thanks!

**Comment by satijalab** [comment]
No updates, and we are not actively pursuing this. I think it could be quite challenging to interpret three simultaneous signals with one color scheme and am closing this for now, but if you have an example (even from another data type) that looks compelling, please post here and we can consider implementing
