### ISSUE TITLE
‘dimensionality’ of integrated datasets

### ISSUE THREAD

**Issue by 23sd98fg** [satijalab/seurat#2233]
Hi, 

We have some questions about the choice of the ‘dimensionality’ of our integrated dataset. We are using 2 datasets (CTR and EXP) that we integrate. We use LogNormalize for the normalization and 2000 genes to find variable features.
Before integration we find our anchors (using FindIntegrationAnchors) using dimensions 1:30.
then we integrate the datasets (using IntegrateData) again using dimensions 1:30.
After scaling the data and running PCA, using npcs=30, we use Jackstrawplot, Elbowplot and Heatmaps from the PCs 1-30 to choose the number of PCs to proceed.
Then we decide for a (lower) number of PCs e.g. 23 and proceed the analysis by using dims = 1:23 in the FindNeighbors, FindClusters and RunUMAP function.

Is this the correct procedure, or once we decided for the dimensionality should we go back in the script and do “find anchors” with 1:23 instead of 1:30 and then “integrate” using 1:23 dimensions  instead of 1:30 to stick always to the same dimensionality?

Thank you very much for your reply!

Best, 
Laura

**Comment by timoast** [comment]
Hi Laura, you don't need to use the same number of dimensions for the integration (CCA) and subsequent analysis on integrated data (PCA)

**Comment by stephanyfoster** [comment]
hello, 
I would like to integrate 8 datasets that are from different timepoints. How do I choose the dims when running FindIntegrationAnchors? Is the number 20 a default value in the vignette? I am referring to the line below:  
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, dims = 1:20)

Should I be running CCA analysis following v2.4?
thnx in advance!
