### ISSUE TITLE
I want to subset cells based on clustering done by UMAP and Seurat v3

### ISSUE THREAD

**Issue by bharati16mehani** [satijalab/seurat#2235]
Hi All,
I have 10X scRNA Seq from two subtypes of a cancer, where 4 clusters from a subtype were found to be associated with 2 clusters from another subtype by hierarchical clustering. To look them into more detail I want to subset these cells from the four clusters. I amusing following commands:

```
wt_norm_log_var_feat.integrated <- ScaleData(wt_norm_log_var_feat.integrated, verbose = FALSE)
wt_norm_log_var_feat.integrated <- RunPCA(wt_norm_log_var_feat.integrated, npcs = 30, verbose = FALSE)
wt_norm_log_var_feat.integrated <- RunUMAP(wt_norm_log_var_feat.integrated, reduction = "pca", dims = 1:30)
wt_norm_log_var_feat.integrated<-FindNeighbors(wt_norm_log_var_feat.integrated, reduction = "pca", dims = 1:30)
wt_norm_log_var_feat.integrated<-FindClusters(wt_norm_log_var_feat.integrated, resolution = 0.5)
p2<-DimPlot(wt_norm_log_var_feat.integrated,reduction = "umap", group.by = "seurat_clusters")
select.cells <- CellSelector(plot = p2)
```

Getting following error:

Click around the cluster of points you wish to select
ie. select the vertecies of a shape around the cluster you
are interested in. Press <Esc> when finished (right click for R-terminal users)

Error in pnt.in.poly(pnts = plot.data[, c(1, 2)], poly.pnts = polygon) : 
  pnts & poly.pnts must be a 2 column dataframe or matrix

Any help will be highly appreciated.
Thanks

**Comment by satijalab** [comment]
Not sure what is happening here. Does the error pop up immediately when you run the command? Or after you select your cells?

If it pops up immediately, are you able to view the plot p2 (just type the command p2 to display it)

**Comment by timoast** [comment]
Closing this now as we haven't heard back from you, please re-open the issue if you're still having problems and can provide the requested information
