### ISSUE TITLE
Error where all cells in one experimental group express low levels of every gene

### ISSUE THREAD

**Issue by bacteria2019** [satijalab/seurat#2238]
Hi,

I'm analyzing two 10x files using the "Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses" vignette on the Satija Lab website. I was able to successfully generate a umap plot, create a list of differentially expressed genes in each cluster, and determine which cell type each cluster is. However, when trying to create feature plots or violin plots, I noticed that no matter what gene I look at, there is low level of expression in every cell in one of my conditions, as you can see by the pink hue of the "ko10x" plot.  Any ideas? I'm not sure if this is due to some error in Seurat or any 10x processing error.  Thanks! 
![Screen Shot 2019-10-22 at 2 42 48 PM](https://user-images.githubusercontent.com/56896909/67336507-548bb280-f4da-11e9-9034-4454d4f1f770.png)

**Comment by andrewwbutler** [comment]
Hi,

For visualization with `FeaturePlot` or `VlnPlot`, we recommend using the underlying `RNA` assay, not the `integrated` assay. This is why we have the following line in that stim vs control pbmc vignette.
 
```R
DefaultAssay(immune.combined) <- "RNA"
```

**Comment by rleonriv** [comment]
Does this still hold true if we integrate after sctransform? Which slot should we use in the RNA assay? Data or scaled data?

**Comment by bacteria2019** [comment]
Thank you!  This resolved my issues You're right--I forgot to switch assays.
