### ISSUE TITLE
FindMarkers cannot exit gracefully and crashes scripts

### ISSUE THREAD

**Issue by ArielPaulson** [satijalab/seurat#2239]
Hi,

There are three problematic stop() calls in FindMarkers that need to be replaced with proper exit procedures like return().  These are the "No features pass" conditions which are currently on lines 523, 530, 571.  

The fact that no features were found is not cause to invoke stop(), which is highly disruptive and stops execution of the entire R script.  These need to be handled with return() or some other approach that allows FindMarkers() to exit normally when it has no results, so I don't have to wrap FindMarkers calls with try() just to stop it from killing the entire R workflow.

Thanks,
Ariel

**Comment by mojaveazure** [comment]
Given that `FindMarkers` is designed to find differentially expressed features, or markers, between clusters, it doesn't make sense that a situation where no markers were found to be treated as "normal". This is why we have the `stop` calls, being unable to find markers means something went wrong and an error occurred. The `stops` simply follow the logic of the function.

If you want to override this behavior, use [`try`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/try.html) or [`tryCatch`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/conditions.html), that's what they're there for. Yes it's annoying to wrap every call to `FindMarkers`, but we'd rather have errors propagate than effectively allow the function to fail silently. The `stops` allow us to bring this inability to find markers between clusters to the user's attention.
