### ISSUE TITLE
ADT-labelled cells and multiplets

### ISSUE THREAD

**Issue by 23sd98fg** [satijalab/seurat#2240]
Hi, 

We have a 10x scRNA-seq data set, where we had pooled 5 different samples labelled with 5 different TotalSeq antibodies respectively.

After generating the Seurat object and the Assay object we have a nFeature_ADT column labelled with numbers from 0-5 so 6 populations in total.  

We have seen your multimodal vignette (https://satijalab.org/seurat/v3.1/multimodal_vignette.html) but still have the following questions:

1) We would like to understand which population (0-5) corresponds to which antibody? And if the additional population (as only 5 in total are expected) contains unlabelled or multiplets?
2) We would like to extract the number of cells which have only one antibody label and which ones have two or more. Those with multiple labels we would also like to exclude as doublets/multiplets.

Would you have a suggestions on how to do that? 

Thank you very much in advance for your reply, 
Laura

**Comment by timoast** [comment]
Hi Laura, our cell hashing vignette should have the answers to your questions: https://satijalab.org/seurat/v3.1/hashing_vignette.html
