### ISSUE TITLE
Reciprocal PCA ‘Futurized’ functions _ what this workers=4 stands for? 

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2243]
**library(future)
library(future.apply)
plan("multiprocess", workers = 4**

 [library"future." ](url) [what this workers=4 stands for?](url)

change the current plan to access parallelization
plan("multiprocess", [**workers = 4)**](url)
plan()

**Comment by andrewwbutler** [comment]
Hi,

The `workers` parameter sets the maximum number of parallel futures that can be active at the same time. Please see the [future package documentation](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html) for more detailed information.
