### ISSUE TITLE
Merging in cell counts from another dataset

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#2244]
Hello, I have a sparse dgc matrix that I got from processing some CRISPR guides, it has each guide as a feature and each cell as a column. I previously was able to merge the data with:

```
VSX2$RNA@data <- merge.sparse(VSX2$RNA@data, guide_frame)
VSX2$RNA@counts <- merge.sparse(VSX2$RNA@counts, guide_frame)
VSX2$RNA@data
```

Unfortunately, when we got new data this no longer works and I now get the error:
`Error: Attempting to add a different number of cells and/or features`

Do you have any advice? Do I need to change nFeature_RNA?

**Comment by Connorr0** [comment]
Update:

There appears to be the same number of cells before and after merging according to `length(colnames(VSX2$RNA@counts))`. Additionally `length(colnames(VSX2$RNA@counts)) == length(colnames(VSX2$RNA@data))`

Full output from `NormalizeData()`:

```Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Feature names cannot have underscores ('_'), replacing with dashes ('-')Adding features not currently present in the objectError: Attempting to add a different number of cells and/or features```

**Comment by mojaveazure** [comment]
Hi Connor,

What is it that you're trying to do? As a general rule, you should never access part of a `Seurat` object using `@`; we provide setters and accessors to handle these tasks and ensure that the data being put into a `Seurat` object is valid.

**Comment by Connorr0** [comment]
Do to experimental design we had our sequencing data split into two pieces. The first section contained the gene expression for endogenous mouse genes, while the second contained information on the CRISPR guides introduced to the experiment (we could not run these together since the guides had a separate barcode). I was hoping to append this guide frame to the expression frame and work with them in the Seurat object.

*This is not pressing as for now I added them into meta.data instead which actually works better for what we were looking for

**Comment by andrewwbutler** [comment]
Hi Connor,

If you want the guide expression in the same matrix as the expression data, you could just merge the matrices upstream of creating the Seurat object. Another option that we tend to prefer for these types of scenarios is to create two separate `Assay` objects, one for the RNA and one for the guides. The [multimodal vignette](https://satijalab.org/seurat/v3.1/multimodal_vignette.html) has some demonstration of working with multiple `Assay`s.
