### ISSUE TITLE
Issue installing version 3.1.0 from cran

### ISSUE THREAD

**Issue by rleonriv** [satijalab/seurat#2245]
I am trying to install version 3.1.0 but I keep on getting the following error:

 Error in package_find_repo(package, repos) : 
  couldn't find package 'Seurat'

**Comment by mojaveazure** [comment]
How are you installing Seurat? `package_find_repo` is not provided by CRAN-provided R package.

**Comment by rleonriv** [comment]
I was able to install the version 3.1.0 after uninstalling and reinstalling R, RStudio, conda, and UMAP. Thanks!

**Comment by lc822** [comment]
Hi, 

I am trying:
devtools::install_version(package = 'Seurat', version = package_version('3.1.2'))

However, I am also getting the following error:

> Error in package_find_repo(package, repos) : 
  couldn't find package 'Seurat'

Best,
Lucy
