### ISSUE TITLE
Visualize after TransferData

### ISSUE THREAD

**Issue by wupengomics** [satijalab/seurat#2246]
I used the "Transfer" function in Seurat and obtained a reasonable cell type classification for query object based on the reference. I'm confused about how to achieve the visualization the query set on reference object. After "Transfer", I can only get the query cells' predicted cell type. We would project these query cells onto the reference UMAP plot. How can I do it?

**Comment by timoast** [comment]
Hi @wupengomics, I would suggest running `IntegrateData` if you want to visualize the query cells in the same space as the reference cells

**Comment by satijalab** [comment]
Thanks for the question. I understand that you are looking to project query cells onto a previously computed UMAP. We don't currently support this in Seurat and i am going to close this issue for the moment, but please do stay tuned for future updates as I agree that this would be valuable functionality.
