### ISSUE TITLE
How can I change the scale of X aixs in Ridgeplot? 

### ISSUE THREAD

**Issue by YunZheHuang** [satijalab/seurat#2248]
Hello, 
I draw a Ridgeplot in Seurat to see how the antibody works. However, the X axis that generated automatically makes that graph difficult to interpret so I want to change the scale of the X axis and I used the command below. However, it didn't work. Can anyone tell me how can I change the scale of the X axis of a ridgeplot? 

RidgePlot(B620, features = "TotalSeq-C0100-CD20-TTCTGGGTCCCTAGA", coord_cartesian(xlim = c(-1, 0.5))

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but believe this should work.  As with other Seurat plotting features they return ggplot objects that can be modified in standard fashion.  RidgePlot uses the ggridges package to create the plot.  So you should be able to modify the plot using standard ggplot code.

```
RidgePlot(object, feature) + 
  scale_x_continuous(enter specific values here)
```

I would suggest reading the help docs for ggplot, scale_x_continuous, and ggridges if you have additional issues.

Best,
Sam
