### ISSUE TITLE
p-value cutoff for FindMarkers

### ISSUE THREAD

**Issue by mxiang128** [satijalab/seurat#2249]
Hi, I am using FindMarkers to find DEGs for two subsets. I see that the function returns genes with p < 0.01. Is there a way to change this cutoff to include more or all genes (like return.thresh in FindAllMarkers)? Thanks!

**Comment by satijalab** [comment]
The function should return all genes that pass the preliminary filtering thresholds, i.e. logfc.threshold, min.pct, etc.), including genes that have p-value > 0.01

You can set the other thresholds to 0 to return all genes (though this will slow down DE)
