### ISSUE TITLE
Error in RunCCA

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#225]
Hi,

I am again getting RunCCA error. Here is the script. The hvg.union has 1665 genes and the gene naming is consistent.

```R
C04.data <- Read10X(data.dir = "/Volumes/Promise_Pegasus/Single_cell_seq/Nov_2017/Arshad/sample_C04/outs/filtered_gene_bc_matrices/mm10/")
C04 <- CreateSeuratObject(raw.data = C04.data, min.cells = 3, min.genes = 100, 
                               project = "C04")

mito.genes <- grep(pattern = "^mt-", x = rownames(x = C04@data), value = TRUE)
percent.mito <- Matrix::colSums(C04@raw.data[mito.genes, ])/Matrix::colSums(C04@raw.data)

C04 <- AddMetaData(object = C04, metadata = percent.mito, col.name = "percent.mito")
C04 <- FilterCells(object = C04, subset.names = c("nGene", "percent.mito"))
C04 <- NormalizeData(object = C04, normalization.method = "LogNormalize", 
                          scale.factor = 10000)
C04 <- FindVariableGenes(object = C04, mean.function = ExpMean, dispersion.function = LogVMR, 
                              x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
length(x = C04@var.genes)


C06.data <- Read10X(data.dir = "/Volumes/Promise_Pegasus/Single_cell_seq/Nov_2017/Arshad/sample_C06/outs/filtered_gene_bc_matrices/mm10/")
C06 <- CreateSeuratObject(raw.data = C06.data, min.cells = 3, min.genes = 100, 
                          project = "C06")

mito.genes <- grep(pattern = "^mt-", x = rownames(x = C06@data), value = TRUE)
percent.mito <- Matrix::colSums(C06@raw.data[mito.genes, ])/Matrix::colSums(C06@raw.data)

C06 <- AddMetaData(object = C06, metadata = percent.mito, col.name = "percent.mito")
C06 <- FilterCells(object = C06, subset.names = c("nGene", "percent.mito"))
C06 <- NormalizeData(object = C06, normalization.method = "LogNormalize", 
                     scale.factor = 10000)
C06 <- FindVariableGenes(object = C06, mean.function = ExpMean, dispersion.function = LogVMR, 
                         x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
length(x = C06@var.genes)


hvg.C06 <- rownames(x = head(x = C06@hvg.info, n = 2000))
hvg.C04 <- rownames(x = head(x = C04@hvg.info, n = 2000))
hvg.union <- union(x = hvg.C04, y = hvg.C06)

C04@meta.data[, "protocol"] <- "C04"
C06@meta.data[, "protocol"] <- "C06"

whole_epithelium <- MergeSeurat(object1 = C04, object2 = C06, min.cells = 3, min.genes = 200,
                    add.cell.id1 = "C04", add.cell.id2 = "C06", project = "whole_epithelium")

whole_epithelium <- ScaleData(whole_epithelium, genes.use = hvg.union, do.center = F, do.scale = T)

whole_epithelium <- RunCCA(object = C04, object2 = C06, add.cell.id1 = "C04", add.cell.id2 = "C06")

Error in RunCCA(object = C04, object2 = C06, add.cell.id1 = "C04", add.cell.id2 = "C06") : 
  0 valid genes in genes.use
Called from: RunCCA(object = C04, object2 = C06, add.cell.id1 = "C04", add.cell.id2 = "C06")
```

Please help.

Thanks,

Bibaswan

**Comment by Ceallaig33** [comment]
Maybe try RunCCA with you genes.use="hvg.union"? According to the ?RunCCA, it seems genes.use should default to the union of the variable genes between the two objects, but maybe just confirm that.

Also, your output if MergeSeurat is likely overwritten when you do RunCCA (which serves the same purpose as MergeSeurat).

**Comment by Ceallaig33** [comment]
And which version of Seurat are you using? It is possible some of this has been resolved in the development version judging by the closed issues.

**Comment by ghoshal** [comment]
I ran with and without genes.use. Also, tried running RunCCA directly without MergeSeurat and that didn't help either.

**Comment by ghoshal** [comment]
The sessionInfo() output.

R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4         Seurat_2.1.0        Biobase_2.36.2      BiocGenerics_0.22.0 Matrix_1.2-11      
[6] cowplot_0.8.0       ggplot2_2.2.1

**Comment by ghoshal** [comment]
Hi,

The RunCCA is working after I scaled the individual datasets. But then it is giving another error whenever I try to use the merged dataset.

> p1 <- DimPlot(object = whole_epithelium, reduction.use = "cca", group.by = "protocol", pt.size = 0.5, 
+               do.return = TRUE)
Error in `$<-.data.frame`(`*tmp*`, "pt.size", value = 0.5) : 
  replacement has 1 row, data has 0
Called from: `$<-.data.frame`(`*tmp*`, "pt.size", value = 0.5)
Browse[1]> 
> p2 <- VlnPlot(object = whole_epithelium, features.plot = "CC1", group.by = "protocol", do.return = TRUE)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 3800, 0
Called from: data.frame(..., check.names = FALSE)
Browse[1]> 

whole_epithelium <- RunCCA(object = C04, object2 = C06, genes.use = hvg.union, add.cell.id1 = "C04", add.cell.id2 = "C06", scale.data = T)
whole_epithelium
An object of class seurat in project C04 
 15411 genes across 3800 samples.

Also, why it is showing as an object of the 1st group only?

**Comment by Ceallaig33** [comment]
These issues seem to be due to the CRAN version of Seurat not appending the sample prefix to the sample names in the cca slot (object@dr$cca). You can double-check that in your case by looking at whole_epithelium@dr$cca .

I was running into the same problem, which is how I found your post in the first place.

This issue was reported #199 and then closed when a fix was implemented in the development version - the easiest solution (as suggested in the resolution is to install the development version of Seurat from Github). http://satijalab.org/seurat/devinstall.html

An alternative fix is to use MergeSeurat, which appropriately add the prefix to the sample names, then used the subsets of that object as input to CCA. This is a cumbersome workaround, but one which should make sure the changes happen in all appropriate locations in the object.

**Comment by ghoshal** [comment]
Thanks. Installing the development version of Seurat solved the error messages that I was receiving. However, every time I am doing a plot with group.by = "protocol", the two samples are not getting separated by color. Is there something I need to ensure before I run the plots?

**Comment by leonfodoulian** [comment]
Hi,

Could you please provide an example of your meta.data slot?

Best,
Leon

**Comment by ghoshal** [comment]
Here you go.

> head(whole_epithelium@meta.data)
                     nGene  nUMI orig.ident percent.mito protocol var.ratio.pca res.0.8
C04_AAACCTGAGGACGAAA   947  5890        C04   0.69660441      C04     1.1506396       0
C04_AAACCTGAGGAGTTGC  1712  7529        C04   0.47031478      C04     1.2794780       0
C04_AAACCTGAGTTCGCGC  2404  9367        C04   0.08637625      C04     1.0608181       5
C04_AAACCTGCAAGGACTG  5020 50586        C04   0.03993515      C04     0.9522838       9
C04_AAACCTGCACACGCTG   998  4026        C04   0.48087432      C04     1.0529164       1
C04_AAACCTGCATAGGATA   339  2407        C04   0.80681346      C04     1.0100690       4
> tail(whole_epithelium@meta.data)
                     nGene nUMI orig.ident percent.mito protocol var.ratio.pca res.0.8
C06_TTTGTCAGTAAGTAGT  1525 6077        C06    0.4430546      C06      1.121998       0
C06_TTTGTCAGTAGCTCCG   375 2080        C06    0.7312500      C06      1.053511       4
C06_TTTGTCAGTTTGACTG  1245 6385        C06    0.5907596      C06      1.009028       2
C06_TTTGTCATCAAACAAG   405 1701        C06    0.6402116      C06      1.018558       4
C06_TTTGTCATCAATAAGG   291 1672        C06    0.7344498      C06      1.005365       1
C06_TTTGTCATCGGAGCAA   281 1533        C06    0.7181996      C06      1.071906       4

**Comment by leonfodoulian** [comment]
What do the colors of your points correspond to in your plots? If you try to group by res.08, does that work? Also check if you wrote "protocol" correctly in the argument.

Best,
Leon

**Comment by leonfodoulian** [comment]
Also, you can try to color by orig.ident, since protocol and orig.ident are identical. Does that work?

**Comment by ghoshal** [comment]
I tried both orig.ident and protocol and they did not work. The plot shows two colors (red & blue) on the labels of protocol but the cells are just one color (always C06).

But using res.0.8 works great.

**Comment by leonfodoulian** [comment]
Ok. Can you check the colnames of your data slot? Do they correspond only to C06 cells?

**Comment by ghoshal** [comment]
It shows both samples.

> tail(colnames(whole_epithelium@data))
[1] "C06_TTTGTCAGTAAGTAGT" "C06_TTTGTCAGTAGCTCCG" "C06_TTTGTCAGTTTGACTG" "C06_TTTGTCATCAAACAAG" "C06_TTTGTCATCAATAAGG"
[6] "C06_TTTGTCATCGGAGCAA"
> head(colnames(whole_epithelium@data))
[1] "C04_AAACCTGAGGACGAAA" "C04_AAACCTGAGGAGTTGC" "C04_AAACCTGAGTTCGCGC" "C04_AAACCTGCAAGGACTG" "C04_AAACCTGCACACGCTG"
[6] "C04_AAACCTGCATAGGATA"

**Comment by ghoshal** [comment]
Also, this problem is consistent with both DimPlot and TSNEPlot.

**Comment by leonfodoulian** [comment]
If you create a new column in your meta.data slot where you attribute "A" for C04 cells, and "B" for C06 cells, and then group by that column name, what do you get?

**Comment by ghoshal** [comment]
I created a meta.data slot called class and named them based on C04 and C06. Unfortunately, the plots are the same. However, it is interesting that it is still plotting by the equivalent of C06.

**Comment by leonfodoulian** [comment]
Do you think there is any chance that your C06 cells are completely overlayed on your C04 cells? If you manually define NA as color for C06 cells, do you see the points corresponding to the C04 cells?

**Comment by ghoshal** [comment]
Yes. Thanks for all the help. They look exactly the same. Now, I'll have to figure out why that is.

**Comment by leonfodoulian** [comment]
You can also see that in the tsne embedding slot of your Seurat object. One thing you can check is the raw input data you gave to Seurat. Provided that the cell names are different, I may assume that there might be an error prior to creating your Seurat objects.

Best,
Leon

**Comment by ghoshal** [comment]
Thanks for all the help Leon. Figured out the issue. The original cell ranger outputs got overwritten.
Everythings works great now.
