### ISSUE TITLE
%||% operation

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#2250]
Hi,

I'm trying to take a look at some intermediate matrices from integrateData function and. However, when I try to get matrices by running the source codes, I noticed there was this "%||% " operation in the code, which could not be executed by my r, neither did I find any information regarding the operation on Google. Could anyone explain how to execute the operation? I sincerely hope someone could help me with this!

Best!

**Comment by timoast** [comment]
Hi, `%||%` is a function defined in Seurat but not exported:

https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/utilities.R#L1253-L1259

**Comment by DHGK** [comment]
Wow, I don't even know we could define a function this way! Thanks a lot!
