### ISSUE TITLE
SCTransform integration produces empty assay slot

### ISSUE THREAD

**Issue by dsb66** [satijalab/seurat#2252]
I am following the SCTransform integration vignette to integrate 25 single-cell RNAseq datasets. After integration is completed I proceed to the PCA step in the downstream analysis, which fails with the following message:

> erythro.integrated <- RunPCA(erythro.integrated)
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 3000 features requested have zero variance (running reduction without them): (complete list of the 3000 variant features identified with SelectIntegrationFeatures).

When I inspect the integrated assay of the erythro.integrated object, the count slot is a [0 x 0] matrix, and the data slot contains an i vector with values:
0 1 2 3 4 5 ...
and a p slot with values:
0 3000 6000 9000 12000 15000

The RNA and SCT assays look properly populated.

This is the sequence of commands I ran:

erythro.data <- CreateSeuratObject(erythro.data, project = "Erythroid")
erythro.list <- SplitObject(erythro.data, split.by = "orig.ident")
erythro.list <- lapply(erythro.list, function(x) SCTransform(x))
erythro.features <- SelectIntegrationFeatures(object.list = erythro.list, nfeatures = nfeat)
erythro.list <- PrepSCTIntegration(object.list = erythro.list, anchor.features = erythro.features)
erythro.anchors <- FindIntegrationAnchors(object.list = erythro.list, normalization.method = "SCT", 
                                          anchor.features = erythro.features)
erythro.integrated <- IntegrateData(anchorset = erythro.anchors, normalization.method = "SCT")

**Comment by dsb66** [comment]
This error occurs independently of the choice of normalization method (LogNormalize or SCT) and reduction method (cca or rpca), but it does not occur if I use a reference dataset at the FindIntergrationAnchors step.

The cells I am working with are a subset of a larger sample and are supposedly from the same lineage but at different differentiation states. Is the integration problem I described possibly related to the nature of the dataset?

**Comment by tushard1987** [comment]
> erythro.list <- lapply(erythro.list, function(x) SCTransform(x))

Hi

did you try including PCA in the SCTransform step?
e.g.
> erythro.list <- lapply(X = erythro.list, FUN = function(x) {
     x <- SCTransform(x)
     x <- RunPCA(x, verbose = FALSE)
 })

**Comment by dsb66** [comment]
No I didn't try including PCA in the SCTransform step. But what would be the rationale for doing a reduction on individual samples before integration? Integration is done on the gene features, not principal components.

**Comment by Tushar-87** [comment]
> No I didn't try including PCA in the SCTransform step. But what would be the rationale for doing a reduction on individual samples before integration? Integration is done on the gene features, not principal components.

I don't know the rationale.
I referred to following post:

https://github.com/satijalab/seurat/issues/1720

If you compare the two replies from andrewwbutler, he has included PCA step in both of them.

In the first reply, he includes it in the SCT step.
It appears from his second reply that when integrating more than 2 samples, PCA step should be included after SCT.

**Comment by yuhanH** [comment]
Sorry for the delay reply. 
Do you still meet this error in our seurat v4? 
You can install it by this: `remotes::install_github("satijalab/seurat", ref = "release/4.0.0")`
