### ISSUE TITLE
Error in embeddings, subscript out of bounds

### ISSUE THREAD

**Issue by neuro007** [satijalab/seurat#2258]
Hello!

I am trying to plot a UMAP after successfully running the UMAP function on Suerat 3.1.

> pbmc <- RunUMAP(df)
> DimPlot(pbmc, reduction="umap")
Error in embeddings[i, j, drop = drop, ...] : subscript out of bounds

I found some resolved questions on this website for "subscript out of bounds" errors for other functions, but those fixes [increasing memory limit, labeling an unlabeled column] did not work.

Any guidance would be much appreciated!!
Thanks.

**Comment by mojaveazure** [comment]
This seems to be an issue with [uwot](https://github.com/jlmelville/uwot), not Seurat. I suggest you bring it up with them.

**Comment by timoast** [comment]
Can you post the output of `sessionInfo()`? Are you able to provide a reproducible example using one of the datasets from the [SeuratData](https://github.com/satijalab/seurat-data) package?
