### ISSUE TITLE
Total variance calculates sd not var

### ISSUE THREAD

**Issue by macroscian** [satijalab/seurat#2260]
https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/dimensional_reduction.R#L830

I don't think it's used anywhere, but the above line puts the total standard deviation rather than total variance in the `srat$pca@misc$total.variance` slot - would it be better to move the `approx=TRUE` value of the total.variance outside the conditional, as even if we square the standard devation, because we can limit the rank of the PC, the sum of the squares will only be the sum of the first few components, not the total.

**Comment by timoast** [comment]
Hi, thanks for pointing this out! We will address this in an update soon

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
