### ISSUE TITLE
What does the data stored in the 'data' slot of the integrated assay represent?

### ISSUE THREAD

**Issue by cpcook1** [satijalab/seurat#2262]
After running `IntegrateData` between a control and treated group I have data in the 'data' slot of the integrated assay for the combined dataset.

What is this data accually for each cell? Does it relate at all to the differences for each gene between the two groups?

Is it possible to extract on a per-cell basis the magnitude (fold change) of a DEG in the treatment group vs. the population of control group? FindMarkers returns more or less a batch (per cluster) assesment of these differences but is this calculated and stored on a per-cell basis?

Thanks so much!

**Comment by timoast** [comment]
The data stored in the integrated assay represents, for query cells, the original normalized expression with the expression differences between reference and query anchor cells removed. This is explained in detail in the paper: https://doi.org/10.1016/j.cell.2019.05.031

Subtracting the original expression matrix from the integrated matrix will give you, for each cell, the transformation that was applied in the integration.
