### ISSUE TITLE
feature name has space and "-"

### ISSUE THREAD

**Issue by tiffanyhuuu** [satijalab/seurat#2263]
Hi there,

I want to create a FeaturePlot with a particular feature, and I am using a reference that had additional sequences appended onto it. Unfortunately, the person who appended it for me named the appended feature with spaces, "-", and "_" in the name, and therefore I keep getting the error that the feature is not found. Is there a way to circumvent this? Thank you!

-- Tiffany

**Comment by timoast** [comment]
Hi, do you mean that you have a feature stored in the object that is not able to be plotted in any plotting functions because of characters in the feature name? If so, can you provide a reproducible example?
