### ISSUE TITLE
DimPlot could use better colour defaults 

### ISSUE THREAD

**Issue by Alanocallaghan** [satijalab/seurat#2264]
It's really common to see clustering plots made with Seurat with the default ggplot2 discrete colour scale. This scales (haha) very badly with increased K, with clusters eventually becoming indistinguishable.

It would be great if you would consider using a palette which is more useful for the typically large K in modern single cell experiments. Obviously above ~25-30 this becomes difficult, but under that is fairly doable ime. If you agree I'm more than happy to submit a PR.

example of a bad plot (several clusters blend together, unclear whether some are distinct):
![bad](https://user-images.githubusercontent.com/10779688/67813937-b4fe8f00-fa9a-11e9-91e7-798745cab3bb.png)

less bad (alphabet palette from pals package):
![lessbad](https://user-images.githubusercontent.com/10779688/67813944-b760e900-fa9a-11e9-97a5-a8949afad360.png)

**Comment by satijalab** [comment]
I think this is great - please do go ahead and submit a PR. At the very least we can have an argument to easily substitute in an alternate palette. Of course, with any color palette there is a risk that two adjacent clusters will be assigned similar colors.
