### ISSUE TITLE
loading pre-analyzed data

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#2265]
I would like to do some analysis on data loaded to Geo. Unfortunately the raw counts were not available but a scaled and normalized matrix was. Is there a way to load the scaled data into Seurat from the start?

**Comment by timoast** [comment]
Hi, you can create a Seurat object using the normalized or scaled data and then set the scale data directly using `SetAssayData`, for example:

```r
obj <- CreateSeuratObject(counts = scale.data)
obj <- SetAssayData(object = obj, slot = 'scale.data', new.data = scale.data)
```

Just be aware that you should then avoid using any functions that require raw counts
