### ISSUE TITLE
axis label is incorrect when log = TRUE

### ISSUE THREAD

**Issue by Alanocallaghan** [satijalab/seurat#2267]
The y axis label for violin plots (and perhaps other plots) is incorrect when log = TRUE.

See this plot. It implies an expression level of e^100, which depending on the base of the log, is between 10^30 and 10^100.
![markers-1](https://user-images.githubusercontent.com/10779688/67882239-d9f60f00-fb39-11e9-9cd7-fcb037853dfe.png)

**Comment by timoast** [comment]
Fixed in 8d5a8c4171b6a1b51fb0df54b550927adc1a99b9
