### ISSUE TITLE
scATAC FeaturePlot cut-offs create NaN error

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#2269]
Hello!

First, thank you so much for creating Signac. It is great!

I am using FeaturePlot with a single cell ATAC-seq object created with Signac to plot TF motif scores after running chromVAR.

My code is based on the vignette:
FeaturePlot(object = scATAC, reduction = "umapNorm",features = "MA0071.1",min.cutoff = 'q10',max.cutoff = 'q90',pt.size = 0.1)

Some of the motifs generate this error:
Error in quantile.default(x = data, probs = this.quantile) : l) missing values and NaN's not allowed if 'na.rm' is FALSE

If I do not specify the min and max cutoffs, I don't get the error. So, it's something about the quantile calculations? But, I really need to use the cut-offs to get good distinction in the plots.

Any help would be greatly appreciated!!!!!!

Thank you! 
Josephine

**Comment by timoast** [comment]
Hi Josephine, are you able to provide a reproducible example for this? Can you also post the output of `sessionInfo()`?

**Comment by jogiles** [comment]
Hi Tim,

Thanks for the speedy response!

Here is the code and session info. (We tried with Seurat on an LSF cluster and Signac on AWS).

I can share a subsetted version of the object -- what is the best way to share this?

Thank you!
Josephine


[code_output_session_info.txt](https://github.com/satijalab/seurat/files/3799806/code_output_session_info.txt)

**Comment by timoast** [comment]
Thanks Josephine, you can email it to tstuart@nygenome.org, or if the object is too large you can put it on google drive / box / dropbox and send the link. Can you also include the full code you used to create the object?

**Comment by timoast** [comment]
@jogiles I'm going to close this now as I haven't heard from you, if you're still having issues please email me a link to the object and the code you're using
