### ISSUE TITLE
Questions for IntegrateData

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#2270]
Hi,

I was trying to integrate data using "SCTransform", I found the number of genes returned was equal to the number of features(3000). I want to return all the genes(>10000) that are present in the datasets. I don't know which of the following is right:
(1)
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = all_genes)   #all genes, not 3000
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features,
    verbose = FALSE)
 pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT",
    anchor.features = pbmc.features, verbose = FALSE)
pbmc.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT",
    verbose = FALSE)

Or
(2)
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)   
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features,
    verbose = FALSE)
 pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT",
    anchor.features = pbmc.features, verbose = FALSE)
pbmc.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT",
    verbose = FALSE, features.to.integrate=all_genes)     #set "features.to.integrate" to all genes

The second question is I found you visualize the expression of the original measurements ("RNA" not "integrated"). In the downstream analysis, for example, transcription factors analysis or correlation analysis with bulk expression profile, Do I use "RNA" or "integrated"? If I use "RNA", does it not consider batch effects?
Thanks!

**Comment by satijalab** [comment]
Option (2) is the workflow to achieve what you describe.

We typically recommend using the RNA assay, as the integrated will 'subtract' any batch effects. If the two experiments differ only in technical batch then perhaps the use of integrated is OK, but if not (for example, if they originate from multiple experimental conditions), then the integrated assay will remove these differences.
