### ISSUE TITLE
Is it possible to construct tSNE plots identical to the one published in a paper using Seurat, with raw data deposited in NCBI as .csv files?

### ISSUE THREAD

**Issue by kpy619** [satijalab/seurat#2271]
Greetings,

First,  I'd like to thank all who has contributed to developing Seurat, an amazing tool to analyze scRNA-seq data.

I am currently trying to reconstruct the same tSNE plot using the raw scRNA-seq data deposited in NCBI for further analysis within the scope of my research.

The paper I am referring to is [[ Giordani, Lorenzo, et al. "High-Dimensional Single-Cell Cartography Reveals Novel Skeletal Muscle-Resident Cell Populations." Molecular cell 74.3 (2019): 609-621. ]]

They have kindly deposited their raw scRNA-seq data in the form of .csv.gz files on NCBI database; I wish to construct the same tSNE plots as they have for further analysis using Seurat.

That being said, my questions are:

1. Is it technically possible to achieve what I am trying to do? (using .csv files to construct tSNE plot shown in the published paper)

2. If so, can anyone help me with writing the code for it?

Since I had basically no programming experience before this, I've been wandering around websites to collect bits of information, and below is the code I came up with:
Criticisms are always welcome. 

# downloading Seurat v.2.3.4
source("https://z.umn.edu/archived-seurat")

library(Seurat)
library(ggplot2)
library(Matrix)

mus1.rna <- as.data.frame(read.csv(file = "/Users/KPY/Desktop/GSM3520458_20171018_uninjured_wt_filtered.csv.gz", 
                               sep = ",", header = TRUE, row.names = 1))
mus2.rna <- as.data.frame(read.csv(file = "/Users/KPY/Desktop/GSM3520459_20180917_uninjured_wt_filtered.csv.gz", 
                               sep = ",", header = TRUE, row.names = 1))

mus1 <- CreateSeuratObject(mus1.rna)
mus2 <- CreateSeuratObject(mus2.rna)

mus1 <- NormalizeData(mus1)
mus2 <- NormalizeData(mus2)
mus1 <- ScaleData(mus1)
mus2 <- ScaleData(mus2)

mus1 <- FindVariableGenes(mus1)
mus2 <- FindVariableGenes(mus2)

mus_CCA <- RunCCA(mus1, mus2, num.cc = 20)
#PrintDim(mus_CCA, reduction.type = 'cca')
#MetageneBicorPlot(mus_CCA, grouping.var = "group", dims.eval = 1:20, display.progress = TRUE)
mus_CCA <- RunTSNE(mus_CCA, reduction.use = 'cca', seed = 1, perplexity = 30, theta = 0.5, 
                   iteration = 1000, dims.use = 1:20)
mus_CCA <- FindClusters(mus_CCA, reduction.type = 'cca', dims.use = 1:20, plot.SNN = TRUE, 
                        resolution = 0.1)
DimPlot(mus_CCA, reduction.use = 'tsne')
![Rplot01](https://user-images.githubusercontent.com/57208249/67922310-c6a47b80-fbed-11e9-8e57-c8f0b41410bf.jpeg)

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but hopefully this is helpful.  If the authors provided their raw counts matrix then yes it would be technically possible.  If not then you would have to process their raw read files to create raw counts matrix.  However, without detailed methods or the authors code (including package versioning) recreating this exact tSNE would likely be difficult as there are a significant number of variables in different steps that would be to be identical to the ones the authors used.

You could definitely reach out to authors and hopefully they would be willing to share their analysis code with you and that would allow you to recreate the plot exactly.

I would also add that while being able to replicate the authors exact plots and code can be useful, it can sometimes be even more useful to reanalyze the data and see if the results are concordant or not.  

All of that being said this isn't really a question or error about the Seurat the R package and is probably better suited to other bioinformatic forums.

Best,
Sam

**Comment by kpy619** [comment]
Dear Sam,

Thank you for the productive comment. I really appreciate it.

I'm new to forums such as Github, and didn't know where to share my questions; my bad if it confused the community in any way.

I did reach out to the authors, hoping to get positive feedback.

Again thank you for the comment.
