### ISSUE TITLE
ScaleData run time can be prohibitively long?

### ISSUE THREAD

**Issue by msraredon** [satijalab/seurat#2273]
Hi Satija Lab et al,

I have found that in Seurat 3.0, the ScaleData function, particularly when also being used to regress out variables such as nUMI, percent.mito, and cell cycle scores (which is excellent by the way!) can take extraordinary times to run.  For ~6000 cells with said regressions this step can easily take 2-3 hours.  For larger datasets (~80,000 cells) this step takes so long that it becomes prohibitive and we have had to remove regressions from our processing, which is a bummer.  Is anyone else having this difficulty? Any advice and/or workarounds?

Thanks,
Sam

**Comment by combiz** [comment]
Also recently encountered possibly the same issue.  On our 10x data, the processing time per variable regressed out is reasonable: ~4.5 minutes per variable on 15,000 cells / 13,000 genes -- this uses 1 core and ~ 12 Gb RAM.  However, when the ScaleData function is called there is a long period, 2-3 hours, where it stalls before proceeding with the regression steps.  This wasn't happening before.  The SCTransform function similarly stalls at the scaling step (also not an issue before).

**Comment by satijalab** [comment]
This is a bit strange, scaledata should be feasible even on extremely large datasets. For datasets that you describe, it should take seconds-minutes. Can you post an example using one of the datasets in SeuratData, so we can check your code?

**Comment by msraredon** [comment]
Hi Satija Lab,

Here is an example that is at least replicable on our machines.  We're running most of our stuff locally, which has proven quite fast, except for this step recently in Seurat 3.0.  We let it run for ~45 min but then cut it off, it got to 6% in that time.  Code:

# Load Data
InstallData("panc8")
data("panc8")

# Set Percentage Mitochondria
panc8[["percent.mt"]] <- PercentageFeatureSet(panc8, pattern = "^MT-")

# Normalize
panc8 <- NormalizeData(panc8)
panc8 <- FindVariableFeatures(panc8, selection.method = "vst")

# Cell Cycle Scoring
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
panc8 <- CellCycleScoring(panc8, s.features = s.genes, g2m.features = g2m.genes, set.ident = FALSE)

# 
start.time <- Sys.time()
panc8 <- ScaleData(panc8, vars.to.regress = c("S.Score", "G2M.Score",'percent.mt'), features = rownames(panc8))
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

<img width="787" alt="Screen Shot 2019-11-08 at 4 28 47 PM" src="https://user-images.githubusercontent.com/42100128/68512026-35648300-0245-11ea-8b22-cffdbe39f1b7.png">

Would love to hear your advice! We suspect we might be doing something wrong, but cannot seem to figure out what it is.  Thanks!

Sam

**Comment by andrewwbutler** [comment]
Hi Sam,

One way to speed this up would be to only scale the variable features. Right now you're specifying all features (~33k) which is not necessary if you're only going to use the variable genes for downstream steps (e.g. RunPCA, etc).

**Comment by PriyaLakr** [comment]
Hi,

How did you solve the issue? I'm having similar issue.

Would running ScaleData() only on top X variable features affected downstream analysis like FindAllMarks() or other DE analysis()? 

As recommend in the tutorial, ScaleData() only on top X variable features would affect heatmap visualization.

Thank you,

**Comment by chilampoon** [comment]
the default features in ScaleData() and RunPCA() are top variable features so just scaling the subset should be fine

**Comment by alifarhat40** [comment]
@timoast by following your tutorial it is taking many hours to perform

`seurat_obj <- ScaleData(seurat_obj, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(seurat_obj)),
`
are you saying when setting `features = rownames(seurat_obj)` it should instead be the HVGs?
