### ISSUE TITLE
Problems adding Antibody Capture matrix with single feature to Seurat Object

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#2274]
Hello,

I have a 10x dataset where we've included Antibody Capture data, but the Antibody Capture matrix has only a single feature.  When trying to add that count matrix to a Seurat object, I get an error that I've never had when adding a matrix with multiple features:

```
> J.data <- Read10X(data.dir = "~/TheData/outs/filtered_feature_bc_matrix/")
    10X data contains more than one type and is being returned as a list containing matrices of each type.
> Jobj <- CreateSeuratObject(counts = J.data$`Gene Expression`)

> Jobj[['SLC3A2ab']] <- CreateAssayObject(counts = J.data$`Antibody Capture`)
Error in CreateAssayObject(counts = J.data$`Antibody Capture`) : 
  No cell names (colnames) names present in the input matrix

> str(J.data$`Antibody Capture`)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:6586] 0 1 2 3 4 5 6 7 8 9 ...
  ..@ p       : int [1:2] 0 6586
  ..@ Dim     : int [1:2] 6587 1
  ..@ Dimnames:List of 2
  .. ..$ : chr [1:6587] "AAACCTGAGCTGAAAT" "AAACCTGAGTCGCCGT" "AAACCTGCAAGCCATT" "AAACCTGCACATCCAA" ...
  .. ..$ : NULL
  ..@ x       : num [1:6586] 85 106 265 68 38 339 103 215 33 99 ...
  ..@ factors : list()
```

It seems like the single feature name, which I've confirmed is in the matrix output from CellRanger, is not being represented in the matrix generated by Read10X. I've tried to fix that manually with no luck. Any suggestions appreciated. Thanks!

**Comment by jeremycfd** [comment]
I was able to get around this by exporting the matrix and changing some stuff around, but I still think this may be a bug with how matrices with just one feature are loaded in during Read10X.

```
> abmat <- as.matrix(J.data$`Antibody Capture`)
> abmat <- t(abmat[colnames(Jobj),])
> rownames(abmat) <- c("SLC3a2ab")
> Jobj[['SLC3A2ab']] <- CreateAssayObject(counts = abmat)
```

**Comment by satijalab** [comment]
Thanks for pointing this out - its something we should fix in Read10X itself (@yuhanH)

**Comment by andrewwbutler** [comment]
This should now work properly on the `develop` branch as of 5958391704449727add2cfa46c0c2c2420d66ae4.
