### ISSUE TITLE
Replicate gene.groups parameter in SplitDotPlotGG to DotPlot

### ISSUE THREAD

**Issue by MediciPrime** [satijalab/seurat#2276]
Is there a way to replicate the gene.groups parameter from SplitDotPlotGG into the DotPlot function?

I want to take the markers I have assigned for the individual cell types:

tcell <- c("Cd3e", "Cd4")
bcell <- c("Cd19", "Cd79a", "Cd80", "Ms4a1")
macrophage <- c("Adgre1", "Ccr2", "H2-Ab1", "Icam2", "Il1b", "Itgam", "Itgax")

And the case sensitive cell type names ('tcell', 'bcell', 'macrophage') from the meta.data column to group the markers by cell type.  Thus I want to create a plot similar to the ones in this [issue](https://github.com/satijalab/seurat/issues/681) where the different cell type labels are at the top of the plot.  

Thank you,
Behram

**Comment by satijalab** [comment]
Closing this as we no longer have the SplitDotPlotGG function, but we are looking into adding this functionality back into DotPlot (which now includes  a split.by argument)
