### ISSUE TITLE
Cell-Cycle Scoring clarification

### ISSUE THREAD

**Issue by macsalvin** [satijalab/seurat#2277]
Hi, 
I'm running Cell-Cycle Scoring (Seurat version 3.1.1) on stimulated vs. control datasets and I would like to see how phases are distributed on WT and KO (in each cluster).
I noticed that I get  different results if I run it in the combined dataset (Experiment.combined of WT and KO) as in the following code:

`
Experiment.anchors <- FindIntegrationAnchors(object.list = list(WT, KO), dims = 1:20)
Experiment.combined <- IntegrateData(anchorset = Experiment.anchors, dims = 1:20)
DefaultAssay(Experiment.combined) <- "integrated"
Experiment.combined <- ScaleData(Experiment.combined, verbose = FALSE)
Experiment.combined <- RunPCA(Experiment.combined, npcs = 30, verbose = FALSE)
Experiment.combined <- RunUMAP(Experiment.combined, reduction = "pca", 
dims = 1:20, verbose = TRUE)
Experiment.combined <- FindNeighbors(Experiment.combined, 
reduction = "pca", dims = 1:20)
Experiment.combined <- FindClusters(Experiment.combined, resolution = 0.5)

DefaultAssay(Experiment.combined) <- "RNA"
*#SAVE A COPY BEFORE RUNNING CellCycleScoring*
Experiment.combined2 <- Experiment.combined

Experiment.combined <- CellCycleScoring(Experiment.combined, s.features = s.genes,  g2m.features = g2m.genes, set.ident = TRUE)

head(Experiment.combined@meta.data)

                    orig.ident nCount_RNA nFeature_RNA seurat_clusters      S.Score    G2M.Score Phase
WT_AAACCTGAGATCCGAG         WT      10424         1990               5 **-0.029539901 -0.006093801    G1**
WT_AAACCTGAGCATCATC         WT      13635         2277               5 **-0.043500308 -0.005479391    G1**
WT_AAACCTGAGCTGCCCA         WT       4078         1498               0 **-0.007978393 -0.010220978    G1**
WT_AAACCTGAGGAGTACC         WT       4548         1519               8  **0.231410182 -0.017759301     S**
`

Or If I run it separately (subset data and run CellCycleScoring):

`
WT <- subset(Experiment.combined2, idents = "WT")
KO <- subset(Experiment.combined2, idents = "KO")
WT <- CellCycleScoring(WT, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
KO <- CellCycleScoring(KO, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

head(WT@meta.data)
                    orig.ident nCount_RNA nFeature_RNA seurat_clusters      S.Score    G2M.Score Phase
WT_AAACCTGAGATCCGAG         WT      10424         1990               5 **-0.027571428  0.006046009   G2M**
WT_AAACCTGAGCATCATC         WT      13635         2277               5 **-0.046208393  0.001280697   G2M**
WT_AAACCTGAGCTGCCCA         WT       4078         1498               0 **-0.010667601 -0.010809597    G1**
WT_AAACCTGAGGAGTACC         WT       4548         1519               8  **0.230647762 -0.020266466     S**
`
As you see there are different Phases for the same cells (The bold one).

As I understood, CellCycleScoring uses AddModuleScore and as you say in the helper: 
Calculate the average expression levels of each program (cluster) on single-cell level, subtracted by the aggregated expression of control feature sets. All analyzed features are binned based on averaged expression, and the control features are randomly selected from each bin. 

*If I run it on the combined dataset, it will mix WT and KO average expression in order to calculate the phase?*
Since my goal is to see the cell cycle differences in the genotypes and also in clusters, should I separate them before the Phase calculation? 

Thanks a lot

**Comment by satijalab** [comment]
Thanks for the good question - yes the issue is that the average expression of each gene differs, which therefore changes the randomized feature set that is used as a background.

This will (inevitably) change some of the values. However, note that the scores themselves are barely changing. The discrete classifications change slightly because the scores just barely move above 0 (from -0.0006 to 0.0006), but there is substantial uncertainty here.

So there is no correct answer to your question, both workflows should give quite similar results, and appear to do so here

**Comment by macsalvin** [comment]
Thanks to you for this great tool

**Comment by xie186** [comment]
Hi @satijalab,  Could you please give us some more detailed information of how  randomized feature set is used as background? Thank you. I subset a cluster and redo cellcyclescoring. The results is quite different from the result in which I used all the cells. When I use all the cells, more than 90% of the cells are assigned to G1. When I use only the subset data only 25% of the cells were assigned as G1.

**Comment by laijen000** [comment]
I ran CellCycleScoring on a neuronal dataset in which I would expect none of the cells to be cycling. However, ~60-70% of cells were assigned to G2M/S. Is there a way to fine tune the threshold for classification? I am interested in the proportions of cycling v. non-cycling cells and would appreciate any advice. Thank you!

**Comment by sofiapuvogelvittini** [comment]
Hi laijen000, I found the same problem. 
You can " tune the threshold for classification" by changing the in the source code:
https://rdrr.io/github/satijalab/seurat/src/R/utilities.R 

FUN = [function](https://rdrr.io/r/base/function.html)(scores, first = 'S', second = 'G2M', null = 'G1') {
      if ([all](https://rdrr.io/r/base/all.html)(scores < 0))

for the following line:

FUN = [function](https://rdrr.io/r/base/function.html)(scores, first = 'S', second = 'G2M', null = 'G1') {
      if ([all](https://rdrr.io/r/base/all.html)(scores < **th**))

and setting **th** to a particular desired threshold (this is the value obtained in AddModuleScore)
