### ISSUE TITLE
NNHelper function

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#2278]
When checking the NNHelper function, I'm a little confused about the exact meaning of the function. I also wonder what nn2 stands for. I'd really appreciate if someone could help me with this.

**Comment by satijalab** [comment]
NNHelper helps identify neighbors in single-cell data. The nn2 function comes from the RANN package, with more info here:
https://www.rdocumentation.org/packages/RANN/versions/2.6.1/topics/nn2
