### ISSUE TITLE
Removing legends in violin plot

### ISSUE THREAD

**Issue by Bioinfo1** [satijalab/seurat#2279]
Hi,
I am currently using Seurat 3.1.1. I am visualizing gene expression in single nuclei clusters using `VlnPlot()`. I have 75 clusters in a visualization and so I do not want cluster legends in the plot as they take considerable area in the plot. The clusters have labels (`x.lab`) and so I can identify the clusters using the labels.
In a previous version (e.g., Seurat v2.3.4), it seems it was possible to remove legends using the `remove.legend = TRUE `parameter setting. However, in Seurat v3.1.1, `remove.legend` is not available. It doesn’t take the ggplot2 parameter setting `show.legend = FALSE` either.
Could you please let me know how to switch off the legends in `VlnPlot()`?
Many thanks,
Mani

**Comment by timoast** [comment]
You can use `theme(legend.position = 'none')` from `ggplot2`, for example:
```r
VlnPlot(object, 'Pvalb') + theme(legend.position = 'none')
```

**Comment by Bioinfo1** [comment]
Thanks very much Tim. That's very helpful.

**Comment by singletrips** [comment]
Yes, it works for me.

**Comment by marodon** [comment]
Great thanks

**Comment by dkcoxie** [comment]
Note - for Seurat 4.3.0, the syntax has shifted: `VlnPlot(object, 'Pvalb') & theme(legend.position = 'none')` worked without error to remove the legend.
