### ISSUE TITLE
Changing shapes in TSNEPlot and/or classifying by secondary identity

### ISSUE THREAD

**Issue by Gorman222** [satijalab/seurat#228]
I am wondering if it is possible to change the shape of data points in the TSNEPlot function. I also want to know if a data set can be classified by a secondary identity in addition to the clustering identity.
So for example, I have an experimental and control group that I have combined into one Seurat object.  The TSNEPlot function graphs them together based on 15 clusters.  Can I change the shape of the data points of the experimental data points so that I can see what group they fall into?  The colors of the points are based on object@identity, but could I affect the shape based on a new object@metadata slot?
Any help on this would be greatly appreciated, thanks.

**Comment by leonfodoulian** [comment]
Hi,

Yes, you can define the shape of your points. Is there a specific column in your `object@meta.data` slot defining the two types of cells? If not, you may want to create that column, and pass the name of that column to the `pt.shape` argument of `TSNEPlot()`.

```
# Create a column identifying the experimental groups to which the cells pertain
object@meta.data$cell.orig <- ifelse(rownames(object@meta.data) %in% colnames(experimental.data), 
                                     "ExpGroup", 
                                     ifelse(rownames(object@meta.data) %in% colnames(control.data), 
                                            "ConGroup", NA))

# Plot tSNE and define shape of points based on 'cell.orig'
TSNEPlot(object = object, pt.shape = "cell.orig", pt.size = 3)
```

Hope that helps!

Best,
Leon

**Comment by leonfodoulian** [comment]
In case you want to manually change the type of points to be plotted, you can do that by adding to the code `scale_shape_manual()`. The trick here is that you need to set `do.return = TRUE`.

```
# Plot tSNE and define shape of points based on 'cell.orig'
# Change point shapes through 'scale_shape_manual()'
TSNEPlot(object = object, pt.shape = "cell.orig", pt.size = 3, do.return = TRUE) + 
  scale_shape_manual(values = c("ConGroup" = 3, "ExpGroup" = 16))
```

Best,
Leon

**Comment by Gorman222** [comment]
Brilliant!  That's exactly what I was looking for, thank you very much!
