### ISSUE TITLE
Save.snn not working in Findcluster 

### ISSUE THREAD

**Issue by aloke206** [satijalab/seurat#2281]
Hii, I am trying to save snn value while executing Findcluster function by using save.SNN = TRUE or save.snn=T. But none of the function works. 
It is giving error
Warning: The following arguments are not used: save.snn
Could you please suggested how to do that

I am also trying to estimate distance matrix between cell. But I am unable to do that. Is there any option in seurat by which I can get distance matrix between cells.

**Comment by timoast** [comment]
Hi, the clustering workflow was split into two separate functions in Seurat v3. We now use `FindNeighbors` to generate a neighbor graph and SNN graph, and this is stored in the object. `FindClusters` then uses the NN or SNN graph to find clusters. The save.SNN parameter is no longer needed in `FindClusters`.

**Comment by XiaofeiSunUCSF** [comment]
If we delete this argument, how can we use Ident(object)<- "snn_resolutionX" to set up the default Idents?
What if we ident(object)<- to other metadata, and like to ident() back to "snn_resolutionX" (unsupervised cluster number)? I checked my metadata list and could not find any hints about the cluster number. 
Could you guide me to find the cluster number in metadata?

**Comment by XiaofeiSunUCSF** [comment]
@timoast 
Add on another point. 
The old version save.snn allow us the try several resolutions at the same time. We can easily check the resolution difference by call ident<-snn_resxxx. all snn_resxx were stored in metadata. 
Do you know what is the alternative function we can use?
