### ISSUE TITLE
How to use integration in Seurat

### ISSUE THREAD

**Issue by peaceisking** [satijalab/seurat#2285]
For example , I have 4 group ,each group with 3 samples, and I wanna analysis them together.

But when I follow the vignettes in Seurat [https://satijalab.org/seurat/v3.1/integration.html](url),I found that I should split them in the vignettes

> pancreas.list <- SplitObject(panc8, split.by = "tech")

What I do is simply merge them together first,but then I have a question.

Should I split them by the 4groups ,or by the 12 samples?

What is the reason doing either of them?

Hope for your reply

**Comment by peaceisking** [comment]
And another question is , does the heterogeneity between samples in the group influence the approach?

**Comment by tushard1987** [comment]
> For example , I have 4 group ,each group with 3 samples, and I wanna analysis them together.
> 
> But when I follow the vignettes in Seurat [https://satijalab.org/seurat/v3.1/integration.html](url),I found that I should split them in the vignettes
> 
> > pancreas.list <- SplitObject(panc8, split.by = "tech")
> 
> What I do is simply merge them together first,but then I have a question.
> 
> Should I split them by the 4groups ,or by the 12 samples?
> 
> What is the reason doing either of them?
> 
> Hope for your reply

I have a simpler case: 4 groups with one sample each. I merge them first and then split as you have also done. I guess this is correct approach.
In your case, how different are your samples within a group ? Are you using 10x genomics system?
If the samples are just replicates,then you may want to make aggregates before you load the data to Seurat. It again depends if your samples were loaded into the same or different 10x well.

**Comment by peaceisking** [comment]
Thank you for your reply!

All the samples used 10x genomics, and they were loaded into different 10x well. Samples in a group are only replicates from different individuals , but it looks like they are quit different.

 So do you suggest me using cellranger aggregate first? But I always doubt whether it is a good method , because I think the principle of it is to subset reads from the deep-depth samples,until all the samples have the same depth. I don't know if it would influence the subsequent analysis if I use CCA in Seurat.

How about I only seperate them by the group , and don't care about the batch effect between samples in a group ?    

Thank you very much!

**Comment by tushard1987** [comment]
Cell ranger aggregate is available with or without normalization to the read depth.

If your ultimate aim to compare the groups, then aggregating the samples before integrating the groups would make sense.

If you split them just by groups (without aggregating the samples within the groups first), I suspect the samples would remain as distinct groups within the group.

In my opinion, scTransform + rPCA would be a better option than Normalization + CAA.

**Comment by peaceisking** [comment]
I searched in 10x Genomics ,and found you are right
![image](https://user-images.githubusercontent.com/46219838/68955948-0c725e00-0802-11ea-8679-b59f58620c3a.png)

Yes , my aim is to compare data between groups ,my question is ,in the picture, cellranger aggr only can remove batch effect caused by sequencing depth, but this can also be done by Normalize() or SCTransform().
 So how about SCTransform + CAA or SCTransform +rPCA? Do not use cellranger aggr,and do not remove batch effects within groups. Because I cannot think out a method to remove batch effects within groups.As I said , I think cellranger aggr can be replaced by sctransform.

**Comment by tushard1987** [comment]
> I searched in 10x Genomics ,and found you are right
> ![image](https://user-images.githubusercontent.com/46219838/68955948-0c725e00-0802-11ea-8679-b59f58620c3a.png)
> 
> Yes , my aim is to compare data between groups ,my question is ,in the picture, cellranger aggr only can remove batch effect caused by sequencing depth, but this can also be done by Normalize() or SCTransform().
> So how about SCTransform + CAA or SCTransform +rPCA? Do not use cellranger aggr,and do not remove batch effects within groups. Because I cannot think out a method to remove batch effects within groups.As I said , I think cellranger aggr can be replaced by sctransform.
> 
> Best wishes to you!

...this also seems reasonable. SCTransform+ integration should remove batch effects.
It would be great if we could share the experiences on this issue from time to time.
All the best!

**Comment by timoast** [comment]
Closing this now as the issue seems to be resolved
