### ISSUE TITLE
How to use Featureplot after integration

### ISSUE THREAD

**Issue by peaceisking** [satijalab/seurat#2286]
After I run integration as the vignettes [https://satijalab.org/seurat/v3.1/immune_alignment.html](url) says

I found that the data in the my.data.integrated@assays$integrate@data wa like this
![image](https://user-images.githubusercontent.com/46219838/68139966-052b9480-ff66-11e9-97b4-ecf097cf8057.png)

And this would cause a problem that when I use Featureplot ,the plot is difficult to recognize
![image](https://user-images.githubusercontent.com/46219838/68140160-4d4ab700-ff66-11e9-9c15-f7b75c479f84.png)
 So,how can I set the minimum value to zero,instead of below zero (in this plot ,-10)

**Comment by yuhanH** [comment]
Hi,
We don't suggest you use the integrated data slot for the visualization. The integrated data is mainly aimed for cell type identification.
Similar question answered here: https://github.com/satijalab/seurat/issues/1717

**Comment by leonvgurp** [comment]
Hi peaceisking,

I fully agree with the Seurat team that it is not the ideal approach to use featureplot on integrated data, but practically speaking: add the argument "min.cutoff = 0" to FeaturePlot function. This should solve your problem
