### ISSUE TITLE
Subsetting a Seurat object

### ISSUE THREAD

**Issue by ADvorkinGheva** [satijalab/seurat#2287]
Greetings,

I have a Seurat object, which has meta.data
When I try to subset the object, this is what I get:

subcell<-subset(x=myseurat,idents = "AT1")
subcell@meta.data[1,]

<pre>
orig.ident nCount_RNA nFeature_RNA Diagnosis Sample_Name Sample_Source
NA       <NA>       3002         1640      NA        NA          NA
Status percent.mt nCount_SCT nFeature_SCT seurat_clusters population
NA       NA       5289         1775              NA       NA
celltype
NA
</pre>

However, if I examine the same cell in the original Seurat object (myseurat), all the information is there.

myseurat@meta.data[which(myseurat@meta.data$celltype=="AT1")[1],]
<pre>
                        orig.ident nCount_RNA nFeature_RNA Diagnosis
F00409_AAGACCTCAAAGGTGC     F00409       3002         1640   Control
                        Sample_Name Sample_Source  Status percent.mt nCount_SCT
F00409_AAGACCTCAAAGGTGC      VUHD69    Vanderbilt Control   1.265823       5289
                        nFeature_SCT seurat_clusters population celltype
F00409_AAGACCTCAAAGGTGC         1775              19 Epithelial      AT1
</pre>

I will appreciate any advice on how to solve this.

Thank you very much!

Regards,
Anna

**Comment by andrewjkwok** [comment]
Hi - I'm having a similar issue and just wanted to check how or whether you managed to resolve this problem? Cheers.
