### ISSUE TITLE
Seurat3 steps for TPM data

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#2288]
Hi,
I read some previuos posts but still confused.
-I have TPM data,
-I imported as it is through CreateSeuratObject.
-I found FindVariableFeatures,.

Now I would like to perform scaling of the data, some previous posts reccomend to ln (natural log+1) tranform the dat. Is this correct?

If yes, I tried to elaborate the S@assays$RNA@data slot.

a<-S@assays$RNA@data
b<-ln(S@assays$RNA@data+1)

S@assays$RNA@data<-b
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “dgeMatrix” is not valid for @‘data’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE

so what I did is to convert it as:

M1 <- as(b, "dgCMatrix")
and replaced in Seurat @data slot
S@assays$RNA@data<-M1

Could you please comment and help me? Am i correct? should i proceed with scaling now?

Many Thanks
Paolo

**Comment by yuhanH** [comment]
When you use `NormalizeData`, the default setting is log-transformation. The detailed information could be found in the documentation.  You don't need to do it by your own functions.
