### ISSUE TITLE
Creating a Seurat Object out of Non traditional Matrix Files

### ISSUE THREAD

**Issue by willmonty14** [satijalab/seurat#2289]
I have some scRNA seq data that I downloaded off the internet and would like to put through Seurat given that it is the most effective (in my opinion) analysis tool for Single Cell data, but the data is not in the traditional format (i.e, not in the filtered feature matrix file format). Instead, it simply a single cell matrix file with cells on the columns and genes on rows. In addition, I have an annotation file that tells me which cells correspond to which samples. Is there a way to input this into Seurat?

**Comment by mojaveazure** [comment]
There's nothing non-traditional about an expression matrix with cells as columns and features as rows. This is precisely the input that Seurat expects. If when you read your data into R, you're given a matrix (dense or sparse) with cells as columns (and colnames set to cell IDs or barcodes) and features as rows (and rownames set to feature names), you can feed this directly to `CreateSeuratObject`
