### ISSUE TITLE
Multiple genes on one violin plot

### ISSUE THREAD

**Issue by kjrgreen1** [satijalab/seurat#2290]
Is there a way to have multiple genes on one violin plot? I want to make a plot similar to the one at the end of the Stimulated vs Control PBMCs vignette, but instead of celltype on the x-axis, I want one to analyze one celltype with multiple genes on the x-axis; still split by condition.

**Comment by andrewwbutler** [comment]
Hi,

Unfortunately, this feature is not currently supported in Seurat. You can pull the expression data plotted via `VlnPlot` though with `FetchData` if you're interested in constructing on your own.
