### ISSUE TITLE
the previoulsy pre-processed scRNA-seq data set in PBMC scATAC-seq Vignette can't download

### ISSUE THREAD

**Issue by aina91** [satijalab/seurat#2291]
hello, Thanks for providing such useful tools for sc-RNA seq data and sc_ATAC seq data。However, when i reading the tutorial about "PBMC scATAC-seq Vignette ",i want to input the annotaioned scRNA-seq dataset ，i find the link couldn't work,it can't find the preprocessed file in the dropbox

**Comment by andrewwbutler** [comment]
Hi,

Is this the link you're referring to? 
https://www.dropbox.com/s/3f3p5nxrn5b3y4y/pbmc_10k_v3.rds?dl=1

It seems to be working on our end.

**Comment by aina91** [comment]
Thx~ I  had changed the server
