### ISSUE TITLE
FindMarkers trouble

### ISSUE THREAD

**Issue by yloemie** [satijalab/seurat#2293]
Hi Satija's team, 

first thanks for your work. I have a question : 
I want to make some figures (custom heatmap) and I wanted to use the log_FC from the FindMarkers function. I have realized that if I put just one gene in the genes.use option it took exactly the same time that if I used the default parameter (all genes). The problem is I didn't want to filter any genes (I just want the log_FC).

FindMarkers(mydata, genes.use = "Prtn31",ident.1="i1",ident.2="i2",group.by="orig.ident",min.pct=-Inf,logfc.threshold = -Inf,min.diff.pct = -Inf)
It indicates that it will take 1h30 exactly the same time without the genes.use parameter.

Is it normal?

Best,

Yann

**Comment by timoast** [comment]
`genes.use` is not a parameter in FindMarkers, which is why it doesn't do anything. I think you want to use `features`, you can check the documentation for the function for more information

**Comment by yloemie** [comment]
Oups, really sorry for that, thanks for your time !

Best,
