### ISSUE TITLE
Does RunPCA use all genes or variable genes only after sctransform with return.only.var.genes = FALSE?

### ISSUE THREAD

**Issue by lc822** [satijalab/seurat#2295]
Hi,

If I set return.only.var.genes = FALSE for sctransform, will RunPCA use all genes by default or only variable genes (as it would with return.only.var.genes = TRUE)?

Best wishes,
Lucy

**Comment by andrewwbutler** [comment]
Hi Lucy,

If the `features` parameter is left as `NULL`, `RunPCA`will run on the variable features for the Assay.  If you want to run with all genes, you will need to both set `return.only.var.genes = FALSE` and specify all features to the `features` parameter. We will update the documentation for that parameter to make it clearer what is used when `features` is left as `NULL`.

**Comment by lc822** [comment]
Great, thanks very much.
