### ISSUE TITLE
Error in documentation of NormalizeData

### ISSUE THREAD

**Issue by chang-che** [satijalab/seurat#2296]
Hi, Seurat team,

In the paper: Stoeckius, M., Zheng, S., Houck-Loomis, B. Rahul Satija . Cell Hashing with barcoded antibodies enables multiplexing and doublet detection for single cell genomics. Genome Biol 19, 224 (2018) doi:10.1186/s13059-018-1603-1 

> Classification of barcodes based on HTO levels
> HTO raw counts were normalized using centered log ratio (CLR) transformation, where counts were divided by the geometric mean of an HTO **across cells** and log-transformed:

And in the documentation of NormalizeData:

> margin
> If performing CLR normalization, normalize across features (1) or cells (2)

What I find in the source code of seurat is  that the normalization across cells is actually margin = 1 and normalization across features is actually margin = 2.

Can you please help to confirm that? Thanks!

**Comment by yuhanH** [comment]
Hi, 
margin = 2 does mean normalization across cells. Could you show me where you think  that normalization across features is actually margin = 2 in the source code?
For example,
```
pbmc_small <- NormalizeData(pbmc_small, normalization.method = "CLR", margin = 2)
denominator <- pbmc_small[["RNA"]]@counts[,2]/(exp(pbmc_small[["RNA"]]@data[,2]) - 1)
denominator
exp(sum(log1p(pbmc_small[["RNA"]]@counts[,2]))/nrow(pbmc_small))

```
You can see that `RNA/exp(data)` which represents the denominator in the CLR, is a constant within a cell, which is the sum counts of all genes. You can find the exact function in the source code.
