### ISSUE TITLE
How do I increase the minimum dot size in Seurat's DotPlot function?

### ISSUE THREAD

**Issue by charlesgwellem** [satijalab/seurat#2297]
Thank you very much for your hard work in developing the very effective and user friendly package Seurat. I want to use the DotPlot function to visualise the expression of some genes across clusters. However when the expression of a gene is zero or very low, the dot size is so small that it is not clearly visible when printed on paper. Please is there a possibility to increase the minimum dot size in the DotPlot function to make the dot sizes more visible when printed?

For example, I would like to have a minimum dot size set to be like this:
![Bild1](https://user-images.githubusercontent.com/10155881/68374403-21d1f300-0145-11ea-82e0-bc56c8cf7e37.png)
from [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5746044/)

Rather than this: 
![minimumdotsize2](https://user-images.githubusercontent.com/10155881/68374158-a53f1480-0144-11ea-8c3f-f2f7141d4458.png)
from [this other paper](https://www.nature.com/articles/s41598-018-24725-0/figures/1)

Thank you in advance for your helpful response.

**Comment by jan-glx** [comment]
Already answered on SO: https://bioinformatics.stackexchange.com/q/10738/3773

**Comment by yuhanH** [comment]
Thanks, Jan.
