### ISSUE TITLE
total.variance calculation in function RunPCA

### ISSUE THREAD

**Issue by XinWang19** [satijalab/seurat#2298]
Hi,
I found a problem when I try to calculate explained variation percentage of PCs in Seurat. Seurat used 2 methods to perform PCA: one is through SVD using irlba and another is through eigendecomposition of covariance matrix. For the second method, Seurat regarded the summation of the standard deviations produced by "prcomp" function as total.variance. But actually it should be the summation of variations or eigenvalues. 
Best regards,
Xin

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/2260
