### ISSUE TITLE
PCA outliers filtering and expression matrix in Seurat object

### ISSUE THREAD

**Issue by Delriosa** [satijalab/seurat#2300]
Hii, 

I have been trying to analyse an available scRNA seq data set with the script they provided, however as a beginner it was not that intuitive for me so I decided to combine it with Seurat/SCE pipelines on my own and try to get a similar final outcome. 

Here is the available script in Github (https://github.com/saeyslab/brainimmuneatlas/blob/master/script_scRNAseq.R) as a reference. 

In my case, I converted the data.matrix into a Seurat object, visualize QC metrics and did a first cleaning based on that, calculated cell-cycle scores for second cleaning, then I converted to SCE and used isOutlier function to clean outliers (cells, genes and mit DNA %) (mad=4). Then I examined genes levels and did a cutoff in 10^-3.5. 

In this point I have two problems:
1) For generating PCA and cleaning from outliers, I used runPCA function and detected outliers, however I am a bit lost in how to delete them from my original sce object. Do I need to create a metadata matrix as in the original script or is there an easier way?

2) Once I want to normalize, I used computeSumFactors for correct calculation of size factors and then I normalize and from there I return the expression values matrix with exprs function. If now I want to create a new Seurat object with this expression matrix, would I need to normalized again (with NormalizeData function) or it is not necessary anymore? 

Hope it was not too much!

Thanks a lot,
Alba

**Comment by timoast** [comment]
Hi, I think question 1 should be directed at the sce/scater authors. For question 2, you shouldn't run the normalization again on already normalized data.

**Comment by Delriosa** [comment]
Yes, sorry I did not close or edit it before! I did it now so it is more suitable. And thank you for your answer!
