### ISSUE TITLE
FetchData not working for features with '(' in name

### ISSUE THREAD

**Issue by kverstae** [satijalab/seurat#2302]
Hi,

FetchData is showing some unexpected behaviour when some features have a '(' in their name.

`result <- FetchData(object, vars = ("CD4", "CD366(Tim-3)")`: returns 2 columns, but with incorrect column names. `colnames(result) =>  "CD4" NA`

This is not that big of problem, but when retrieving more than 2 features there is a bigger problem.
`FetchData(object, vars = ("CD4", "CD5", "CD366(Tim-3)")` returns a dataframe with only 2 columns, but I expect it to return 3. Data for CD366(Tim-3) seems to be missing from the result.

Am I doing something wrong or is there a problem with this function?

Kind regards,
Kevin

PS. I know the easiest fix for this is to rename the features, but this is not something I want to do

**Comment by satijalab** [comment]
Apologies - but the best way forward is to rename the features at the onset of creating the object.

There are simply too many internal functions in R that will get confused by parenthesis in feature names.
