### ISSUE TITLE
Scale.Data slot when using the SCTransform-Integration workflow.

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#2303]
Hi, 
I am sorry. I am getting confused here. The vignette here https://satijalab.org/seurat/v3.1/integration.html shows how to use SCTranscform and then go for the integration. In this case, I don't have anything in my scale.data slot. What is the best slot to use for heatmaps and dotplots when using this workflow referring to the reply from the collaborator here.
 Kindly advise. 
Thanks and kind regards, Saeed
> Hi,
> Several issues here. Currently, you cannot use SCTransformed data for the integration, so you have the error ` No requested features found in the scale.data slot for the RNA assay.` You could use `NormalizeData()` to normalize your data, if you want to use it for integration.
> But this function will be added soon.
> 
> When you perform `DotPlot `, you would better confirm that default assay is RNA, or you can set assay in the `DotPlot`. `DotPlot(obj, assay = "RNA")`
> 
> `FindAllMarkers` usually uses `data` slot in the RNA assay to find differential genes.
> For a heatmap or dotplot of markers, the scale.data in the RNA assay should be used.
> 
> Here is an issue explaining when to use RNA or integrated assay. It may be helpful.
> #1717

**Comment by yuhanH** [comment]
It is solved in the latest develop branch. When you follow the integration vignette, the scale.data should not be empty.
