### ISSUE TITLE
Possible Bug in FindMarkers

### ISSUE THREAD

**Issue by willmonty14** [satijalab/seurat#2304]
Dear Seurat Team, 
I'm currently using your FindMarkers function to test for differential expression between two conditions, "APPPS1" and "WT". Interestingly, when I set 
slot = "scale.data" the function returns "avg_diff" instead of "avg_logFC". However, if I set
slot= "data" or
slot = "counts" I get "avg_logFC" again. Any idea what's going on?

**Comment by timoast** [comment]
This isn't a bug, if you use scaled data you can't compute the log fold change, so we return the average difference instead.
