### ISSUE TITLE
Where are the statistics of harmony reduction stored?

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#2306]
Hi,
I'm using  RunHarmony on a seurat object on which I already performed a PCA and selected the dimensions using the ElbowPlot. Where can I find the statistics of the harmony reduction so that I can choose the appropriate number of dimensions for downstream analysis?
Thanks

**Comment by timoast** [comment]
Please see the harmony [vignette](https://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/docs/SeuratV3.html) and [website](https://portals.broadinstitute.org/harmony/) from the Raychaudhuri lab for information on the harmony method
