### ISSUE TITLE
CITE seq data analysis

### ISSUE THREAD

**Issue by imj835** [satijalab/seurat#2307]
Hello,
Thank you for the vignette, "Using Seurat with multi-modal data". I have feature barcoding data from 10X and get a filtered feature barcode matrix as an output after I run in CellRanger, but no ADT and RNA files. How do I get the separate ADT and RNA files from CellRanger outputs so that I can use this vignette?
Thank you for your help in advance!
Insiya

**Comment by andrewwbutler** [comment]
Hi Insiya,

You should be able to use the `Read10X` function to read in the data. If you have both gene expression and protein expression, these should show up as separate elements in the list that gets returned. For an example, see the docs in `?Read10X`.
