### ISSUE TITLE
Possible Subset Function Bug

### ISSUE THREAD

**Issue by JenniferWUSTL** [satijalab/seurat#2308]
Good evening,

I'm recently running into issues with the subset function on scRNA-seq multiple datasets.  I believe it is a bug, as I'm successful at subsetting the same Seurat object on a Docker image of Seurat and at earlier times in the same Seurat session in my personal Macbook.  I've received multiple different error messages trying to subset and I've uninstalled and reinstalled Seurat twice, but I'm still running into issues.  These are the issues I'm seeing: 
```
cellsubset <- subset(seuratobject, idents = c("0", "1", "2", "3", "4", "5", "6"))
Error: Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay.
```

and

```
cellsubset2 <- subset(seuratobject2, idents = c("1", "2", "4", "6", "11"))
Error in `[[.Seurat`(x, DefaultAssay(object = x)) : 
  Cannot find 'RNA' in this Seurat object
```

To confirm 'RNA' is there: 
```
DefaultAssay(seuratobject2)
[1] "RNA"
```

Thank you for your work on Seurat and I would appreciate hearing any advice regarding fixing this function.  Thank you!

**Comment by andrewwbutler** [comment]
Hi,

The first issue suggests that you're trying to remove all the cells from the object. If you check the current idents of the object, do you have any cells with values not in 0:6? E.g.

```R
any(!Idents(seuratobject) %in% 0:6)
```

For the second error, are you able to provide a reproducible example or the object (or downsampled version) that reproduces the problem?

**Comment by JenniferWUSTL** [comment]
Hi Andrew!  Thank you for the reply.  Yes, I have 11 clusters in the 1st seurat object.  I've been able to reproduce both errors- sometimes it is easily fixed by restarting R, but other times I have to use Seurat on a different machine.  Thanks!

**Comment by andrewwbutler** [comment]
Can you send us an example object where you consistently have this issue along with the code you were trying to run?
