### ISSUE TITLE
VlnPlot() change y-axis

### ISSUE THREAD

**Issue by swvanderlaan** [satijalab/seurat#2309]
I would like to edit the y-axis label in the `VlnPlot()` function, is this possible? And if so: how?

Thanks.

Sander

**Comment by samuel-marsh** [comment]
Hi Sander,

Not member of the Dev team but this should work.  `VlnPlot()` returns a ggplot object that can be modified using standard ggplot code.  In this case:

```
VlnPlot(object, "feature") +
  ylab("new_y_axis_label")
```

Best,
Sam
