### ISSUE TITLE
as.loom fails to write Seurat object to loom after subsetting with cells and leaving columns in meta.data empty

### ISSUE THREAD

**Issue by pcm32** [satijalab/seurat#2310]
If, after a subsetting operation where a list of cell is given, one of the columns in `obj@meta.data` data frame ends up being empty, the export to loom fails:

```
> as.loom(l5, filename="test_filter5.loom")
Transposing input data: loom file will show input columns (cells) as rows and input rows (features) as columns
This is to maintain compatibility with other loom tools
  |======================================================================| 100%
Adding: CellID
Adding: Gene
Adding a layer to norm_data (layer 1 of 1)
  |======================================================================| 100%
Adding: vst_mean
Adding: vst_variable
Adding: vst_variance
Adding: vst_variance_expected
Adding: vst_variance_standardized
Adding: Selected
Adding: orig_ident
Adding: nCount_RNA
Adding: nFeature_RNA
Adding: Factor_Value_Ontology_Term_cell_type_
Adding: Factor_Value_Ontology_Term_single_cell_identifier_
Adding: Factor_Value_cell_type_
Adding: Factor_Value_single_cell_identifier_
Adding: Sample_Characteristic_Ontology_Term_cell_type_
Error in self$set_size(size) : HDF5-API Errors:
    error #000: H5T.c in H5Tset_size(): line 2180: size must be positive
        class: HDF5
        major: Invalid arguments to routine
        minor: Bad value
```

adding a value to one of the entries in the empty columns fixes this. Metadata was added to the object at creation time through `CreateSeuratObject` metadata field. The metadata given was a dataframe read through `read.table(opt$metadata,header = TRUE, sep="\t", row.names = 1)`. Should I be using any particular options on read.table that would make this problem go away? Please note that export to loom does work before the subset step (actually, after having to force through findVariableGenes on the created object, due to another issue of loomR described elsewhere).

Thanks!

**Comment by pcm32** [comment]
Also, setting blank values to `NA` doesn't work either, there needs to be at least one non-empty string present in each column to pass complete the loom writing. This is using the latest version of loomR in bioconda (r-loom package).

**Comment by satijalab** [comment]
Thanks for finding this. We could do specific error checking here, but my sense is that its poor practice in any case to have an empty metadata column. We would recommend having non-blank entires (i.e. NONE, or similar) as an alternative to blank or NA values.

**Comment by pcm32** [comment]
The problem is that invariable after some filtering you might find yourself with the case of metadata columns that are empty (because cells that had values, for some reason, went away). Is not that we provide metadata columns that are empty on start, so I don't think that this is a problem of poor practice :-), but a potential side effect of filtering.

**Comment by pcm32** [comment]
..and the standard way of representing empty values in R is not an arbitrary text, like "NONE", so I wouldn't endorse such a recommendation.

**Comment by satijalab** [comment]
I understand - I'm suggesting that there should be no blank values in the object meta data (it sounds like you have a column where some values are blank and others are not). There's no right answer here and it is indeed a matter of opinion.
