### ISSUE TITLE
Doing PCA for multiple scRNA-seq samples using Seurat v3

### ISSUE THREAD

**Issue by myaqubi** [satijalab/seurat#2311]
Hi Seurat team

Thanks for your excellent package. Maybe this is not related to Seurat package, but I am wondering can I do PCA for multiple scRNAseq datasets to see how disperse they are? In my project I am merging 12 different scRNAseq datasets from different time points of human development. I am curious to know to what extent different datasets are similar according to their age. 

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Yes, you can definitely do that in Seurat. You could run a PCA on on the merged dataset and see whether there is a PC(s) that separates the data based on time point. I would expect that there would be variation that is associated with time point and that a PCA would probably pick up on that.
