### ISSUE TITLE
FindVariableFeatures() after cell cycle regression?

### ISSUE THREAD

**Issue by liuyigh** [satijalab/seurat#2313]
According to current [cell cycle vignette](https://satijalab.org/seurat/v3.1/cell_cycle_vignette.html), we go directly to `RunPCA()` after `ScaleData()` with cell cycle scores. 

It seems the `RunPCA()` uses argument `feature = VariableFeatures()`. Isn't this still the old _Variable Features_ **before** regression? Don't we need to redo `FindVariableFeatures()`?

Thanks for any explanation.

**Comment by jan-glx** [comment]
As you can see in https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/preprocessing.R#L1595-L1604
Selection of variable features is performed on `@data` or `@counts`, not `@scale.data` and therefore unaffected by `ScaleData`.

**Comment by liuyigh** [comment]
Thank you very much for the explanation and reference to code. I appreciate it.
