### ISSUE TITLE
as.SingleCellExperiment generate "Object with Null Pointers"

### ISSUE THREAD

**Issue by bluestone12** [satijalab/seurat#2314]
Hello Satija Lab,

First of all, thank you for developing Seurat, it's a very useful tool. 

I was trying to covert my large Seurat object to a single cell experiment with the following code:

`seurat_cellcycle_PCA.singlecell <- as.SingleCellExperiment(seurat_cellcycle_PCA)`
where `seurat_cellcycle_PCA` is a v3 large Seurat object. The code ran, but `seurat_cellcycle_PCA.singlecell` is shown as a "object with null pointers", and the metadata is shown as a list of length [0]. I'm wondering what would be a good way to get around this. 

Thank you in advance!

**Comment by leonvgurp** [comment]
Hi bluestone,

Regarding the null pointer, this has to do with the version key of your S4 object, as explained here: https://github.com/rstudio/rstudio/issues/4741

Regarding metadata, this is stored in colData: try "colData(seurat_cellcycle_PCA.singlecell)" and you should have it
