### ISSUE TITLE
DoHeatmap lines separating clusters

### ISSUE THREAD

**Issue by erikagucciardo** [satijalab/seurat#2315]
Hi, thanks for a great tool for single-cell RNA seq data analysis!
I was wondering if and how I could change the color of the line separating clusters within the heatmap as well as in the group bar above the heatmap. In the group bar the line is white, while within the heatmap the line is grey. Is there a way to have this line also white?

And how can I edit things like font size, font face etc within the ggplot? I can't seem to find the correct slot.

Thanks

**Comment by andrewwbutler** [comment]
Hi,

That's strange that the heatmap lines are grey. What exactly is the code you're running to generate the heatmap and can you provide a reproducible example? One thing you could try (changing the `na.value` parameter should change the line color):

```R
DoHeatmap(object) + 
  scale_fill_gradientn(colors = PurpleAndYellow(), na.value = "white")
```

Changing aspects like font size should be done via `theme` (reference [here](https://ggplot2.tidyverse.org/reference/theme.html)). For example, to change the font size of the gene labels:

```R
DoHeatmap(pbmc_small) + theme(axis.text.y = element_text(size = 20))
```

**Comment by erikagucciardo** [comment]
Thank you so much, this worked!

**Comment by mengfeich** [comment]
I was trying to change the size of the gene name under DoHeatmap, but I got the warning message that could not find function "theme", but I just installed the ggthemes.

Here are my codes, thanks in advance.

> library(ggthemes)
> DoHeatmap(pbmc, features = top10$gene) + theme(axis.text.y = element_text(size = 5))
Error in theme(axis.text.y = element_text(size = 5)) : 
  could not find function "theme"
