### ISSUE TITLE
Subset by UMIs cutoff of a list of gene from a certain cell culster

### ISSUE THREAD

**Issue by Chenmengpin** [satijalab/seurat#2316]
Hi all,

I have a group of genes that are supposed highly express in plasma cells, and I want to use those genes to seperate plasma cells and other typle of cells using a cutoff of 100UMIs per cell. I'm quite new to bioinformatics and I feel like subset funtion can do that, but don't know the what exact code can make that happen. Can anyone give some suggetion for that?

Thank you very much!

**Comment by andrewwbutler** [comment]
Hi, 

Yes, if you want a Seurat object with just the cells that pass your thresholds, then the `subset` function would be appropriate. If you just want a vector of cells names, then you can use `WhichCells`. For example:

```R
WhichCells(object, expression = GENE1 > 100 & GENE2 > 100, slot = "counts")
```

or if you wanted to say that the sum of the group of genes should be greater than 100

```R
WhichCells(pbmc_small, expression = GENE1 + GENE2 > 100, slot = "counts")
```
