### ISSUE TITLE
FindVariableFeatures Error:Cannot add more or fewer meta.features information without values being named with feature names

### ISSUE THREAD

**Issue by saum-kmr** [satijalab/seurat#2317]
I have a smart-seq2 dataset for which I have used SCTransform to carryout the analysis, which works perfectly. Now I want to have a look at "RNA" assay and use those normalized values for downstream analysis. I first set the DefaultAssay to "RNA" and then did "LogNormalize" for Normalization of data.  When I run FindVariableFeatures command, I get the following error:

DataNorm = FindVariableFeatures(DataNorm,selection.method = "vst",nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Cannot add more or fewer meta.features information without values being named with feature names

I looked up this error and found a link with DimPlot command and similar error. So I tried setting up the idents to one of the clusters, But I still get the same error with FindVariableFeatures command. 

Thanks in advance for help!

**Comment by andrewwbutler** [comment]
Hi,

Are you able to provide a reproducible example or the object you're working with (or downsampled version that reproduces the issue)?

**Comment by saum-kmr** [comment]
Hello, Please see attached a very very small subset of the R Object. 
[dataNormSubset.RData.zip](https://github.com/satijalab/seurat/files/3854554/dataNormSubset.RData.zip)

**Comment by andrewwbutler** [comment]
Thanks for posting the data. I was able to reproduce the problem here. I think something went a bit weird when setting up the RNA assay. How exactly did you create that? The problem is that the rownames of the `meta.features` data.frame are all `NA.XX`. A quick fix would be to just run:

```R
dataNormSubset[["RNA"]]@meta.features <- data.frame(row.names = rownames(dataNormSubset[["RNA"]]))
```

**Comment by saum-kmr** [comment]
Hello,

Yes this fix works! Thank you very much!

Since this is all smart-seq2, I had created these objects using Seurat v2 using CreateSeuratObject command and creating my own dataframe as metadata. After seurat v3 was released, I had simply upgraded them for use with Seurat v3. Since then I had been using with SCT assay for downstream analysis.

**Comment by aditisk** [comment]
I'm trying to use a (gene X cells) counts table from a published dataset and running into the same error message. The Seurat object is created but it might not be setup correctly.

`> hn1
An object of class Seurat 
18899 features across 6060 samples within 1 assay 
Active assay: RNA (18899 features, 0 variable features)`

This is my error message:

`> hn1 <- FindVariableFeatures(hn1, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Cannot add more or fewer meta.features information without values being named with feature names`

How do I fix this issue ? Thanks in advance for the help.

**Comment by aditisk** [comment]
Quick update:

It turns out that the text file from GEO had some formatting errors and missing values. I fixed it in excel and also found this suggestion to be helpful.

`my_data <- read.table(file = "Matrix.txt", header = T, sep="\t", as.is=T,row.names = 1)`

Previously I was importing the data with read.csv(). A combination of the two fixed my problem.
