### ISSUE TITLE
Regressing drosophila cell cycle genes

### ISSUE THREAD

**Issue by algal4** [satijalab/seurat#2319]
The Tirosh cell cycle genes included with Seurat don't apply because I'm working with drosophila data. I've created my own list of s and g2 genes, but I don't know how to implement it.

If anyone knows how to regress out a selection of genes or alter the cc.genes file please let me know!

Thanks,
Alex

**Comment by lxhuang7** [comment]
You just need to create a list with two elements s and g2. Each contains a character vector that consists of your genes of interest.

cc.genes.drosophila <- list(s = c('gene1', 'gene2'), g2 = c('gene3', 'gene4', 'gene5'))
