### ISSUE TITLE
Alignment Script Error in FindVariableGenes

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#232]
Hi, could you please assist with this error? 

I'm running R3.4 and did not have this issue with R3.3.

obj6v <- FindVariableGenes(object = obj6s, do.plot = FALSE)
Error in .Call("_Seurat_FastExpMean", PACKAGE = "Seurat", mat, display_progress) : 
  "_Seurat_FastExpMean" not available for .Call() for package "Seurat"

**Comment by leonfodoulian** [comment]
Hi,

It seems to me that it's an issue of cpp. Can you try this instead?

```
obj6v <- FindVariableGenes(object = obj6s, do.plot = FALSE, do.cpp = FALSE)
```

Otherwise, try to [re-install Seurat from CRAN](http://satijalab.org/seurat/install.html).

Best,
Leon
