### ISSUE TITLE
how to change the name of clusters in DoHeatmap

### ISSUE THREAD

**Issue by benxiahu** [satijalab/seurat#2320]
Hello,
 Here are the code I want to change the name of clusters
```R
pbmc.combined<-RunTSNE(object=pbmc.combined,dims.use=1:10,do.fast=TRUE)
my_levels <- c(1,2,3,4,5,6,7,8)
pbmc.combined@active.ident <- factor(pbmc.combined@active.ident, label=my_levels,levels = my_levels)
pbmc.markers <- FindAllMarkers(pbmc.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

top5 <- pbmc.markers %>% group_by(cluster) %>% top_n(5, avg_logFC)
```
when I ran the following code, I met this error:

```R
DoHeatmap(pbmc.combined, features = top5$gene)

Error in data.frame(group = sort(x = group.use), x = x.divs) : 
  arguments imply differing number of rows: 10293, 10294
```

**Comment by andrewwbutler** [comment]
Hi,

Are you able to provide the object or reproducible example for us to test with? 

As a side note, you can use the `levels` function to change the factor levels of the current ident. E.g:

```R
levels(pbmc.combined) <- c(1,2,3,4,5,6,7,8)
```

**Comment by RoganGrant** [comment]
I am having the identical issue. I'm using archival data, so this may make for a workable example. Currently using version 3.1.1

Download expression matrix as `GSE104276_all_pfc_2394_UMI_count_NOERCC.xls.gz`: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE104276&format=file&file=GSE104276%5Fall%5Fpfc%5F2394%5FUMI%5Fcount%5FNOERCC%2Exls%2Egz
Download metadata as `GSE104276_readme_sample_barcode.xlsx`: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE104276&format=file&file=GSE104276%5Freadme%5Fsample%5Fbarcode%2Exlsx

```
library(Seurat)
library(readxl)
library(tibble)
zhongMat = read.delim(gzfile("GSE104276_all_pfc_2394_UMI_count_NOERCC.xls.gz"))
zhongMat = data.matrix(zhongMat)
zhongMeta = as.data.frame(read_xlsx("GSE104276_readme_sample_barcode.xlsx",
                      sheet = "SampleInfo"))
zhongMeta = column_to_rownames(zhongMeta, var = "...1")
zhong = CreateSeuratObject(counts = zhongMat, 
                           project = "zhong", 
                           meta.data = zhongMeta,
                           min.features = 100)
zhong = SCTransform(zhong)
DoHeatmap(object = zhong, group.by = "cell_types")
```

Error:
> Error in data.frame(group = sort(x = group.use), x = x.divs) : 
  arguments imply differing number of rows: 2345, 2346

Session:
> sessionInfo()
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server 7.5 (Maipo)
> 
> Matrix products: default
> BLAS:   /hpc/software/R/3.6.0/lib64/R/lib/libRblas.so
> LAPACK: /hpc/software/R/3.6.0/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] BiocParallel_1.20.0 tibble_2.1.3        readxl_1.3.1        Seurat_3.1.1        Matrix_1.2-17       R.matlab_3.6.2     
> [7] RCurl_1.95-4.12     bitops_1.0-6       
> 
> loaded via a namespace (and not attached):
>   [1] tsne_0.1-3          nlme_3.1-139        RcppAnnoy_0.0.14    RColorBrewer_1.1-2  httr_1.4.1          sctransform_0.2.0  
>   [7] tools_3.6.0         backports_1.1.5     utf8_1.1.4          R6_2.4.1            irlba_2.3.3         KernSmooth_2.23-15 
>  [13] uwot_0.1.4          lazyeval_0.2.2      colorspace_1.4-1    npsurv_0.4-0        gridExtra_2.3       tidyselect_0.2.5   
>  [19] compiler_3.6.0      cli_1.1.0           plotly_4.9.1        labeling_0.3        caTools_1.17.1.2    scales_1.0.0       
>  [25] lmtest_0.9-37       ggridges_0.5.1      pbapply_1.4-2       stringr_1.4.0       digest_0.6.22       rmarkdown_1.17     
>  [31] R.utils_2.9.0       base64enc_0.1-3     pkgconfig_2.0.3     htmltools_0.4.0     bibtex_0.4.2        htmlwidgets_1.5.1  
>  [37] rlang_0.4.1         rstudioapi_0.10     zoo_1.8-6           jsonlite_1.6        ica_1.0-2           gtools_3.8.1       
>  [43] dplyr_0.8.3         R.oo_1.23.0         magrittr_1.5        fansi_0.4.0         Rcpp_1.0.3          munsell_0.5.0      
>  [49] ape_5.3             reticulate_1.13     lifecycle_0.1.0     R.methodsS3_1.7.1   stringi_1.4.3       yaml_2.2.0         
>  [55] gbRd_0.4-11         MASS_7.3-51.4       gplots_3.0.1.1      Rtsne_0.15          plyr_1.8.4          grid_3.6.0         
>  [61] parallel_3.6.0      gdata_2.18.0        listenv_0.7.0       ggrepel_0.8.1       crayon_1.3.4        lattice_0.20-38    
>  [67] cowplot_1.0.0       splines_3.6.0       SDMTools_1.1-221.1  zeallot_0.1.0       knitr_1.26          pillar_1.4.2       
>  [73] igraph_1.2.4.1      reshape2_1.4.3      future.apply_1.3.0  codetools_0.2-16    leiden_0.3.1        glue_1.3.1         
>  [79] evaluate_0.14       lsei_1.2-0          metap_1.1           RcppParallel_4.4.4  data.table_1.12.6   png_0.1-7          
>  [85] vctrs_0.2.0         Rdpack_0.11-0       cellranger_1.1.0    gtable_0.3.0        RANN_2.6.1          purrr_0.3.3        
>  [91] tidyr_1.0.0         future_1.15.0       assertthat_0.2.1    ggplot2_3.2.1       xfun_0.11           rsvd_1.0.2         
>  [97] RSpectra_0.15-0     survival_2.44-1.1   viridisLite_0.3.0   cluster_2.0.9       globals_0.12.4      fitdistrplus_1.0-14
> [103] ROCR_1.0-7

**Comment by hepcat72** [comment]
I get this same exact error in the galaxy version of Seurat on everything. I even ran the counts file included in the galaxy tool install. According to our logs, Seurat on our galaxy instance has never run successfully, yet all the dependencies appear to have installed without error. The version of Seurat on galaxy is 3.1.2. We suspect that perhaps there’s an unnamed dependency? Because the same file and parameters run fine in a fresh R Studio install, though that gets the latest Seurat. So can you comment on whether this was a bug in 3.1.2 or whether there is perhaps an unnamed dependency?
