### ISSUE TITLE
Can not require Seurat

### ISSUE THREAD

**Issue by namhuynhnc** [satijalab/seurat#2321]
Hi,
Normally I use Seurat well. This morning I cant require Seurat (v3.1.1) package. The session is aborted every time I try. I have reinstall Seurat, R, Rstudio but all same but it is still fine when I installed Seurat v2.3.

Anyone can help me? I need to use Seurat asap.
Thank you. 

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1 tools_3.6.1

**Comment by timoast** [comment]
Hi, I haven't been able to reproduce this issue on macOS Catalina. The only thing I can suggest is reinstalling the Seurat dependencies
