### ISSUE TITLE
Cannot find MapQuery function in Seurat V3.1.1

### ISSUE THREAD

**Issue by kritikakarri** [satijalab/seurat#2322]
Hello,
I am trying to create an integrated reference using my old dataset and then map a new query dataset unto to the reference using MapQuery. But Seurat doesn't seem to give me that option and I have installed the most recent version of Seurat (v3.1.1).

**Comment by andrewwbutler** [comment]
Hi,

`MapQuery` is an internal function in Seurat and is not meant to be directly called. It seems that our internal documentation for this function included the roxygen formatted comments and thus appears in the searchable docs, which was not the intention. We will correct this in future versions.

For creating an integrated reference, I would recommend using the functions `FindIntegrationAnchors` and `IntegrateData` as demonstrated in the vignette [here](https://satijalab.org/seurat/integration.html).
