### ISSUE TITLE
Save both 2nd and 3rd dimensions in UMAP

### ISSUE THREAD

**Issue by simeenz** [satijalab/seurat#2323]
Hi- Is there a way to save both n.components  = 2L and  n.components  = 3L in the RunUMAP function to the Seurat object?

**Comment by timoast** [comment]
You can't save both at once, as running with n.components = 2 and n.components = 3 gives different embeddings. If you want both you'll need to run twice

**Comment by simeenz** [comment]
After running n.components = 2, can I run n.components = 3 on the same object that 2L was run on so that I will get both embeddings in one Seurat object? Or will I have to save them in 2 separate Seurat objects?

**Comment by vertesy** [comment]
You can store it in one object, using the `@misc` slot.
```r
obj <- RunUMAP(obj, dims = 1:p$n.PC, n.components = 2)
obj@misc$'reductions.backup'$umap2d <- obj@reductions$umap
obj <- RunUMAP(obj, dims = 1:p$n.PC, n.components = 3)
obj@misc$'reductions.backup'$umap3d <- obj@reductions$umap
```
Note that, technically, you could also store it in `obj@reductions$umap3d `, but don't do it: it will mess up functions like `FetchData()`.

Also, while functions like `FeaturePlot()` will work without an error on both `umap3d` and `umap` slots (of `@reductions`), they will use the 1st 2 components without a notice that a 3rd dimension exists.

```R
obj <- RunUMAP(obj, dims = 1:p$n.PC, n.components = 3)
obj@reductions$umap3d <- obj@reductions$umap
obj <- RunUMAP(obj, dims = 1:p$n.PC, n.components = 2)
FeaturePlot(obj,features = "TOP2A", reduction = "umap3d")
FeaturePlot(obj,features = "TOP2A", reduction = "umap")
```

**Comment by Dragonmasterx87** [comment]
^ nice one bro ;)

**Comment by vertesy** [comment]
Thanks, I wrapped them into proper functions: `BackupReduction()`, `SetupReductionsNtoKdimensions()`, `RecallReduction()` in [Seurat.utils](https://github.com/vertesy/Seurat.utils/blob/master/plotting.dim.reduction.3D.R). It also includes a 3D plotting function (`plot3D.umap()`) based on your code – thanks too!
