### ISSUE TITLE
Seurat hard codes random seed

### ISSUE THREAD

**Issue by constantAmateur** [satijalab/seurat#2324]
I have been writing some code, which use Seurat as a sub-routine in the following way.

```
stdProcess = function(ddd,...){
  ss = CreateSeuratObject(ddd)
  ss = NormalizeData(ss,verbose=FALSE)
  ss = CellCycleScoring(ss, s.features=GenesS,g2m.features=GenesG2M)
  ss = ScaleData(ss,vars.to.regress=c('S.Score','G2M.Score'),verbose=FALSE,...)
  return(ss@assays$RNA@scale.data)
}
```

The problem with this is my larger body of code relies on a `rbinom` with the reasonable expectation that subsequent calls to rbinom should be random.  So something like this:

```
for(i in seq(10)){
  really_random_numbers = rbinom(1000,1000,0.5)
  stdProcess(ddd)
  #Do something with really_random_numbers
}
```

The problem is, that one of the Seurat functions in stdProcess calls set.seed somewhere.  The result of which is that really_random_numbers gives the same results from the second time round the loop onwards.  That is, really_random_numbers is identical when i is in the range 2 to 10.

I have not bothered to try and work out where Seurat is setting the random seed, but needless to say it should absolutely not be doing this without the user explicitly asking for it.  At a minimum it should be documented that this is happening very clearly.

**Comment by mojaveazure** [comment]
If you read the docs for [`CellCycleScoring`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/CellCycleScoring), you would see this line:

> ... Arguments to be passed to [`AddModuleScore`](https://www.rdocumentation.org/link/AddModuleScore?package=Seurat&version=3.1.1)

This clearly states that `CellCycleScoring` is calling another function (`AddModuleScore`) and that you should read those docs to understand what's going on. Looking at those [docs](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/AddModuleScore), we see

> seed Set a random seed

Seems to me like it's fairly well documented that we're setting a seed
