### ISSUE TITLE
 "snn_resolutionX" in metadata set

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [satijalab/seurat#2325]
We realized the argument save.snn is removed in function FindCluster. I have question as below.

If we delete this argument, how can we use Ident(object)<- "snn_resolutionX" to set up the default Idents?
What if we ident(object)<- to other metadata, and like to ident() back to "snn_resolutionX" (unsupervised cluster number)? I checked my metadata list and could not find any hints about the cluster number. 
Could you guide me to find the cluster number in metadata?

Add on another point.
The old version save.snn allow us to try several resolutions at the same time. We can easily check the resolution difference by call ident<-snn_resxxx. all snn_resxx were stored in metadata.
Do you know what is the alternative function we can use?

_Originally posted by @XiaofeiSunUCSF in https://github.com/satijalab/seurat/issues/2281#issuecomment-553357385_

**Comment by andrewwbutler** [comment]
Hi,

The clustering results are stored in meta.data under `ASSAY_snn_res.X`. For example, the`pbmc_small` object contains two different clustering results (`RNA_snn_res.0.8` and `RNA_snn_res.1`) :
```R
> names(pbmc_small[[]])
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8" "letter.idents"   "groups"          "RNA_snn_res.1" 
```

In Seurat v3, we have more explicitly separated the construction of the neighbor graph and the clustering algorithm. Therefore, the expected workflow is to run `FindNeighors` to generate the SNN graph and then run `FindClusters` to determine the clustering. If you want to try several values for the resolution parameter, you can pass a vector of values to the `resolution` parameter in `FindClusters`.

**Comment by XiaofeiSunUCSF** [comment]
Hi,

Thank you for your reply. I tried 
![image](https://user-images.githubusercontent.com/51248547/68969943-fe3d2700-079a-11ea-9951-d5a244246ae2.png)
 and could not find options of resolution 0.4 or 0.6 in my metadata. 

![image](https://user-images.githubusercontent.com/51248547/68969911-efef0b00-079a-11ea-8d94-efe6058aa12e.png)
Could you please help me figure it out?

**Comment by XiaofeiSunUCSF** [comment]
I figured it out!!!
It didn't show doesn't mean it didn't exist. They actually exist and didn't show due to the space issue. 
Thanks!!!
