### ISSUE TITLE
Anchor Scoring and Weighting

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#2326]
When checking the source code, I noticed, to find knn for query cells, the method first finds k+1 neighbors using NNHelper and then removes the first neighbor founded. I wonder what's the reason for doing this. Why couldn't we just use k as an input for NNHelper? Thanks!

**Comment by timoast** [comment]
The first neighbor will be the query cell itself, so if we want to find the k nearest other cells we find k + 1 nearest neighbors and remove the first result
