### ISSUE TITLE
no outcome nor any message after running Leiden using FindClusters for more than 10 hours

### ISSUE THREAD

**Issue by Feihong-Xu** [satijalab/seurat#2328]
Hi Satija Lab et al,

Thanks for the great package. 

I am having difficulties running Leiden through `Seurat::FindClusters`. I am using the development version of Seurat and Leiden. I could not get any outcome or result after running `Seurat::FindClusters(object = prisctregpcann, algorithm = 4, method = "igraph")` overnight with 8 workers. I fed the "SCT_snn" directly to Leiden::Leiden as following: 
```
snn = graph_from_adjacency_matrix(prisctregpcann@graphs$SCT_snn)
partition <- leiden(snn, resolution_parameter = 0.1, n_iterations = -1)
```
It didn't take much time to get the output form Leiden, yet there seems a huge amount of singletons: `length(unique(partition))` gave 50346, which is only slightly less than the number of cells(50562) in my dataset. Seurat call `GroupSingletons` right behind `RunLeiden`, which involve some for-loops, so I guess it might be the `GroupSingletons` step that took much time. Besides, the singletons problem cannot be fixed by adjust resolution parameter.

Could you help me with this? Thanks.

Feihong

**Comment by Feihong-Xu** [comment]
Hi Satija Lab et al,

With `group.singletons` set to `FALSE`, `FindClusters` works within minutes with following code:
`prisctreg = FindClusters(prisctregpcann, algorithm = 4, method = "igraph", random.seed = 19980219, verbose = TRUE, group.singletons = FALSE)`
Now my seurat object has a "cluster" of 141 levels.
I am confused about this situation, could I run Leiden with `group.singletons` set to `TURE`

Thank you so much!

Best,
Feihong

**Comment by kaizen89** [comment]
I have a similar issue:
```
object <-  FindClusters(object, resolution = 0.2, algorithm = 4, method = "igraph") 
Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument
In addition: Warning message:
In max(connectivity, na.rm = T) :
  no non-missing arguments to max; returning -Inf
traceback()
7: sample.int(length(x), size, replace, prob)
6: sample(x = names(x = connectivity[mi]), 1)
5: GroupSingletons(ids = ids, SNN = object, group.singletons = group.singletons, 
       verbose = verbose)
4: FindClusters.default(object = object[[graph.name]], modularity.fxn = modularity.fxn, 
       initial.membership = initial.membership, weights = weights, 
       node.sizes = node.sizes, resolution = resolution, method = method, 
       algorithm = algorithm, n.start = n.start, n.iter = n.iter, 
       random.seed = random.seed, group.singletons = group.singletons, 
       temp.file.location = temp.file.location, edge.file.name = edge.file.name, 
       verbose = verbose, ...)
3: FindClusters(object = object[[graph.name]], modularity.fxn = modularity.fxn, 
       initial.membership = initial.membership, weights = weights, 
       node.sizes = node.sizes, resolution = resolution, method = method, 
       algorithm = algorithm, n.start = n.start, n.iter = n.iter, 
       random.seed = random.seed, group.singletons = group.singletons, 
       temp.file.location = temp.file.location, edge.file.name = edge.file.name, 
       verbose = verbose, ...)
2: FindClusters.Seurat(bladder_stroma, resolution = 0.2, algorithm = 4, 
       method = "igraph")
1: FindClusters(bladder_stroma, resolution = 0.2, algorithm = 4, 
       method = "igraph")
```

**Comment by milescsmith** [comment]
Chime in here to say that I am having the same problem as @Feihong-Xu - running `leiden()` on the graph object produced by `FindNeighbors` returns nearly as many clusters as there are cells.  I have found, however, that generating a distance matrix from the expression data and passing that to `FindClusters()` produces clusters that approximate those found when using scanpy.

**Comment by timoast** [comment]
Hi, this issue is due to the problems being discussed in #2440 and #2438

Currently (49a1be0427f2f26a531eb468ba93eeb18d8a2edb) Leiden is broken for both the `igraph` and `matrix` methods in Seurat and we are discussing the best way to fix these.

The smart local moving algorithm is very similar to Leiden and will give very similar partitions on single-cell data, I would recommend using that. If you really prefer to use Leiden, you will currently need to roll back to Seurat v3.1.1

**Comment by TomKellyGenetics** [comment]
@milescsmith I noticed this issue while troubleshooting #2440 as well. The latest version of leiden should resolve the problem with singletons. Returning too many single “clusters” seems to be a problem for `Seurat`. Please note that the `resolution` parameter for `FindClusters` is different to the default. You can increase the `resolution` if you have this problem.
