### ISSUE TITLE
seurat input from ballgown object?

### ISSUE THREAD

**Issue by sualice1** [satijalab/seurat#2332]
I'm wondering if it is possible to create a new seurat object from an existing ballgown object. I'm doing the HISAT, StringTie, and Ballgown pipeline on scRNAseq data. I know there is an python script after StringTie (prepDE.py) to create a count matrix however, I could not run it. 

I have created a ballgown object and have gene expression and transcript matrices. 
The transcript matrix is transcripts vs. FPKM of each cell. 
According to ballgown, the gene expression matrix is gene ID vs. "gene-level measurements are calculated by appropriately combining FPKMs from the transcripts comprising the gene." for each cell.

**Comment by timoast** [comment]
I'm not familiar with ballgown but if you have a matrix of genes x cells you can create the Seurat object in the standard way using the `CreateSeuratObject` function.
