### ISSUE TITLE
Vln, Ridge visualizations not working with integrated clusters?

### ISSUE THREAD

**Issue by rlevantovsky** [satijalab/seurat#2334]
Hi,

I am trying to apply some visualizations to an already integrated Seurat object - I don't have the raw files or upstream objects. Whenever I try to apply either VlnPlot or RidgePlot to the renamed cluster object, I get no color visual output. However, feature plots work. Is the issue with Vln/Ridge that I only have the integrated output? Is there another fix? Thanks!

This is the object:

 ```
An object of class Seurat 
22992 features across 70226 samples within 2 assays 
Active assay: integrated (2000 features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
```

Code for Violin plot, output
`VlnPlot(IntegratedCD_Mamta_renamed, features = c("IL17RA"))`
![image](https://user-images.githubusercontent.com/53229601/69084072-73199680-0a11-11ea-8c5a-3da98ff5cae7.png)

Code for Ridge plot, output
`RidgePlot(IntegratedCD_Mamta_renamed, assay = "RNA", features = IL17.features)`
![image](https://user-images.githubusercontent.com/53229601/69084160-a3f9cb80-0a11-11ea-82e7-3264f58ccee7.png)

**Comment by timoast** [comment]
Hi, it appear that these genes are just lowly expressed. One reason for the discrepancy you see between plots could be that you are using the uncorrected RNA assay in the RidgePlot and the integrated data in the VlnPlot. We generally recommend performing visualization and differential expression with the uncorrected data. If you can provide a more concrete example where the expression level is not being accurately displayed in a plot please reopen this issue
