### ISSUE TITLE
Gene Co-Expression with Gene of Interest

### ISSUE THREAD

**Issue by hippoConfused** [satijalab/seurat#2335]
Hi, I am using the raw data from dropviz.org to try and see what other genes are highly correlated (co-expressed) with a gene of interest at the single-cell level. 
So far, I have taken the raw data, processed it, and run PCAs/NearestNeighbor/etc. How should I proceed from here?

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but hopefully this is helpful.  I would first recommend checking out the Seurat Vignettes on the Satija Lab website ([https://satijalab.org/seurat/vignettes.html](https://satijalab.org/seurat/vignettes.html).

If you still have questions I would recommend posting them to more relevant bioinformatics forum (Biostars, Bioinformatics Stack Exchange) for answers to your questions.  Github is meant more to report issues or questions with the software itself and not analysis based questions.

Best,
Sam
