### ISSUE TITLE
Dotplot split.by order

### ISSUE THREAD

**Issue by LooLipin** [satijalab/seurat#2336]
Hi there,

I generated a dotplot split by genotype but my mutant identity shows up above the WT. May I know what's the easiest way to fix this? I would like to have the WT show up before the mutant.

Thanks,
Lipin
<img width="1080" alt="Screen Shot 2019-11-19 at 5 31 52 pm" src="https://user-images.githubusercontent.com/57159632/69122275-82bcdc00-0af2-11ea-9f89-be6f4c7662c6.png">

**Comment by saeedfc** [comment]
Dear,
I only see one way to get around. Even reordering the genotype factor wouldn't do.
For example, if your meta data column called "genotype" holds the information for mut/wt,
You have to reorder the meta data.

library(plyr)
object@meta.data$GEN <- object@meta.data$genotype
object@meta.data <- object@meta.data %>%
      mutate(GEN = ifelse(GEN == "WT",0,1))
Now you can arrange the data in increasing or decreasing order of genotype using the GEN column to get the dotplot the way you want.
object@meta.data <- dplyr::arrange(object@meta.data, object@meta.data$GEN)

or **(not the '-' sign)**
object@meta.data <- dplyr::arrange(object@meta.data, -object@meta.data$GEN)

**Comment by satijalab** [comment]
Thanks for this, it is a complicated solution but I don't see an easier way for the moment

**Comment by gabrieljm00** [comment]
sorry, guys,
I tried it, but it just changes the positions of the labels, but the values and points size stay the same and don't move with the labels

see:

![teste](https://user-images.githubusercontent.com/81363931/113309905-05a49800-92de-11eb-9209-38b5b35113e9.png)
![teste1](https://user-images.githubusercontent.com/81363931/113309912-06d5c500-92de-11eb-99a5-9d3e1db21e31.png)

**Comment by sidlawrence** [comment]
don't know if anyone still has this issue but i found if the object is formed from integrating or merging multiple smaller objects formed from [eg] Read10x function, they will always split by the REVERSE order in which you merge, even if you alter the levels.
So for the original post: srat<- merge(x=C199Ssrat, y=WTsrat) will order the WT first and C199S second when you split. I wanted to split by gestational age in order, and also by the sample ID and other metadata that covary with age for various plots, and found the only way was to start again and merge them all in REVERSE order of age

Srat<- merge(x=PCW17, y=PCW12)
Srat<- merge(x=Srat, y=PCW10)
Srat<- merge(x=Srat, y=PCW9)
Srat<- merge(x=Srat, y=PCW7)
Srat<- merge(x=Srat, y=PCW5)

hope that is useful

**Comment by ektapathak08** [comment]
Dear [@satijalab](https://twitter.com/satijalab), Thanks for this wonderful package.

@sidlawrence, thanks for your solution. It did work😊.

Using a factor for a particular order of orig.ident(sample name) or sample type for the plots works for Vlnplot but not for DotPlots here. 

Instead of starting again with merging data(when you have already done integration, clustering, and further analysis), one can subset the data for each sample(using the subset function) and then merge again these subsets in the required order.


Best
Ekta

**Comment by sidlawrence** [comment]
I found another handy edit for this function - you can remove grey as the default low expression colour through trace:

trace("DotPlot",edit=TRUE) 
#and edit this line: return(colorRampPalette(colors = c("grey", color))(20)[value])

you can specify your colour eg white for low expression
