### ISSUE TITLE
assay parameter in PercentageFeatureSet() function 

### ISSUE THREAD

**Issue by vstanislas** [satijalab/seurat#2337]
Hello everyone,

I detected a small bug in the function PercentageFeatureSet() when using the argument assay.
The computation of the sum over the subset of feature is always calculated on the DefaultAssay and doesn't take into account the value specified in the assay argument. However, the computation of the overall sum for the division does, thus generating false percentages. 

To be more precise this is the actual function inside PercentageFeatureSet() that compute percentages:
`percent.featureset <- colSums(x = GetAssayData(object = object, slot = "counts")[features, , drop = FALSE])/object[[paste0("nCount_",  assay)]] * 100`

which will be better as: 
`percent.featureset <- colSums(x = GetAssayData(object = object, assay=assay, slot = "counts")[features, , drop = FALSE])/object[[paste0("nCount_",  assay)]] * 100
`

Thanks a lot for your work on Seurat, it's a great package to use!

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting! This should be fixed now in the develop version as of 29a92902.
