### ISSUE TITLE
having difficult in installing Seurat

### ISSUE THREAD

**Issue by Shawn10312** [satijalab/seurat#2339]
It is really strange, because in the before, I can install seurat easily in R3.5.

But after update the R to 3.6.1, I confront the problem in installing seurat in Centos as following:

> install.packages('Seurat')
Installing package into ‘/gpfs/ycga/home/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/Seurat_3.1.1.tar.gz'
Content type 'application/x-gzip' length 790426 bytes (771 KB)
==================================================
downloaded 771 KB

ERROR: failed to lock directory ‘/gpfs/ycga/home/R/x86_64-pc-linux-gnu-library/3.6’ for modifying
Try removing ‘/gpfs/ycga/home/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-Seurat’
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpFC9sMA/downloaded_packages’

> Sys.info()
                              sysname                               release 
                              "Linux"          "3.10.0-957.38.1.el7.x86_64" 
                              version                              nodename 
"#1 SMP Thu Sep 26 12:15:44 EDT 2019"     "c15n01.ruddle.hpc.yale.internal" 
                              machine                                 login 
                             "x86_64"                             "unknown" 
                                 user                        effective_user 
                              "y"                               "y" 

So how can I handle this problem?

**Comment by timoast** [comment]
Try removing ‘/gpfs/ycga/home/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-Seurat’

**Comment by Shawn10312** [comment]
cool, that works!
Thanks.
