### ISSUE TITLE
Could not find Function "%>%"

### ISSUE THREAD

**Issue by LachlanMacdonald** [satijalab/seurat#234]
Currently doing the PBMC Guided Clustering Tutorial (Oct 12, 2017).

The %>% function is not working for either _finding differentially expressed genes_ or later on before the second heat map is created.

The error is expressed as the following:
> pbmc.markers %>% group_by(cluster) %>% top_n(2, avg_logFC)
Error in pbmc.markers %>% group_by(cluster) %>% top_n(2, avg_logFC) : 
  could not find function "%>%"

Thanks in advance

**Comment by Ceallaig33** [comment]
Make sure you have the dependent dplyr package installed and have it loaded.

Run this only once
`install.packages(dplyr)`

Need to load this every time along with Seurat (and 'Matrix' if you are using sparse matrices)
`library(dplyr)`

**Comment by LachlanMacdonald** [comment]
This seems to have fixed the issue. Thanks. Closing this thread now.
