### ISSUE TITLE
FeatureScatter 'cells' and 'group.by' parameter clash

### ISSUE THREAD

**Issue by davidsanin** [satijalab/seurat#2341]
Hey, 

I am using FeatureScatter to correlate two genes in a specific cluster in my data by passing the cell barcodes to the command. When I try to color the scatter plot by condition, I get a dimensionality error. Any way of getting past this?

This works:
`FeatureScatter(object = data, feature1 = GeneA, feature2 = GeneA, group.by = 'condition', cols = colors)`
This works:
`FeatureScatter(object = data, feature1 = GeneA, feature2 = GeneA, cells = cells)`
This fails:
`FeatureScatter(object = data, feature1 = GeneA, feature2 = GeneA, cells = cells, group.by = 'condition', cols = colors)`

The error displayed is:
Error in `$<-.data.frame`(`*tmp*`, "colors", value = c("CONTROL", "CONTROL",  : 
  replacement has 6059 rows, data has 2516

Thanks for your help!

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
