### ISSUE TITLE
Error in GetAssayData(combined, slot = "counts")[, WhichCells(combined,  :    no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2343]
Hi¨
getting some error with my test dataset? what could be the possible reason? 

**Seurat - Interaction Tips**
https://satijalab.org/seurat/v3.0/interaction_vignette.html

# How can I extract expression matrix for all NK cells (perhaps, to load into another package)
nk.raw.data <- as.matrix(GetAssayData(combined, slot = "counts")[, WhichCells(combined, ident = 12)])

# Can I create a Seurat object based on the expression of a feature or value in object metadata?
subset(combined, subset = MS4A1 > 1)

```
[Error in GetAssayData(combined, slot = "counts")[, WhichCells(combined,  : 
  no 'dimnames' attribute for array
](url)

**Comment by saeedfc** [comment]
nk.subset <- subset(Combined, idents = 12)
nk.raw.data <- as.matrix(GetAssayData(nk.subset, assay = "RNA", slot = "counts"))

This should work

For the second part, 

subset_SO <- subset(combined, cells = WhichCells(combined, expression = MS4A71>1)) 
#you can replace MS4A71 with any column names from the meta.data, for eg.
subset_SO <- subset(combined, cells = WhichCells(combined, expression = genotype  == "KO"))
