### ISSUE TITLE
Clustering on UMAP reduction

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#2344]
Dear,

As discussed here (https://github.com/satijalab/seurat/issues/1081#issue-401862041), I have the same issue of having the cells diffuse too much into other clusters. I have exhausted the options of trying different parameters with FindNeighbours and RunUMAP functions.
@timoast If I cluster on the UMAP instead of PCA , Can it still be considered unsupervised clustering? This in fact gives 'cleaner' clusters. Kindly advice
```

#SO = seurat_object
SO <- FindNeighbors(SO,reduction = "umap", dims = 1:2, force.recalc = T)
SO <- FindClusters(SO)
UMAPPlot(SO)

```
Thanks in advance!

**Comment by timoast** [comment]
Yes the clustering is still unsupervised. The clusters will likely appear more consistent with the UMAP visualization if you cluster on UMAP coordinates, but UMAP is usually just for visualization and I think performing clustering in PC space is generally a better idea.
