### ISSUE TITLE
DESeq2 cannot work 

### ISSUE THREAD

**Issue by weihuaguo** [satijalab/seurat#2345]
I am trying to run DE analysis with DESeq2 via Seurat. But I got following errors:
`Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  :
  The following cell names provided to cells.1 are not present:
Calls: FindMarkers ... FindMarkers.Seurat -> FindMarkers -> FindMarkers.default
`
My script is: 
`useDE = "DESeq2"
hmMarker = FindMarkers(srsc, ident.1 = "1", ident.2 = "0", test.use = useDE, slot = "counts")
`

My seurat object info is:
An object of class Seurat
38117 features across 2716 samples within 2 assays
Active assay: integrated (2000 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, umap, tsne

My session info is:
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS/LAPACK: /home/xxxxxxxx/xxxx/envs/scrnaseqr/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
character(0)

other attached packages:
[1] Seurat_3.1.1

loaded via a namespace (and not attached):
[1] compiler_3.5.1  graphics_3.5.1  utils_3.5.1     grDevices_3.5.1
[5] stats_3.5.1     datasets_3.5.1  methods_3.5.1   base_3.5.1   
>

**Comment by tushard1987** [comment]
> I am trying to run DE analysis with DESeq2 via Seurat. But I got following errors:
> `Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, : The following cell names provided to cells.1 are not present: Calls: FindMarkers ... FindMarkers.Seurat -> FindMarkers -> FindMarkers.default `
> My script is:
> `useDE = "DESeq2" hmMarker = FindMarkers(srsc, ident.1 = "1", ident.2 = "0", test.use = useDE, slot = "counts") `
> 
> My seurat object info is:
> An object of class Seurat
> 38117 features across 2716 samples within 2 assays
> Active assay: integrated (2000 features)
> 1 other assay present: RNA
> 3 dimensional reductions calculated: pca, umap, tsne
> 
> My session info is:
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-conda_cos6-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.3 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /home/xxxxxxxx/xxxx/envs/scrnaseqr/lib/R/lib/libRblas.so
> 
> locale:
> [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C
> [3] LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8
> [5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
> [7] LC_PAPER=en_US.UTF-8 LC_NAME=C
> [9] LC_ADDRESS=C LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> character(0)
> 
> other attached packages:
> [1] Seurat_3.1.1
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.5.1 graphics_3.5.1 utils_3.5.1 grDevices_3.5.1
> [5] stats_3.5.1 datasets_3.5.1 methods_3.5.1 base_3.5.1
> 
> >
Hello

I would set default assay to RNA for DE analysis. I would also make sure that data slot in RNA assay is normalized. 

Best wishes,
Tushar

**Comment by weihuaguo** [comment]
It works! Thanks a lot!

Best,
Weihua
