### ISSUE TITLE
MAST DE cannot work

### ISSUE THREAD

**Issue by weihuaguo** [satijalab/seurat#2346]
I was trying to run DE analysis with MAST, but I cannot do it. I added the scater library and it still  didn't work. Here is my error:
`Error in sanity_check_sca(obj) : 
  Assay in position 1, with name et is unlogged. Set `check_sanity = FALSE` to override and then proceed with caution.
Calls: FindMarkers ... FindMarkers.default -> MASTDETest -> <Anonymous> -> sanity_check_sca
'

My script is:
`useDE = "MAST"
hmMarker = FindMarkers(srsc, ident.1 = "1", ident.2 = "0", test.use = useDE)
`

My session info:
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS/LAPACK: /home/xxxxxx/xxxxxxxxx/envs/scrnaseqr/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
character(0)

other attached packages:
[1] Seurat_3.1.1

loaded via a namespace (and not attached):
[1] compiler_3.5.1  graphics_3.5.1  utils_3.5.1     grDevices_3.5.1
[5] stats_3.5.1     datasets_3.5.1  methods_3.5.1   base_3.5.1     

Could you please help me with it? Thanks!

**Comment by timoast** [comment]
Is this caused by the same problem as your previous closed issue? https://github.com/satijalab/seurat/issues/2345

**Comment by weihuaguo** [comment]
Yes. Thanks, Tim! It works!

**Comment by ondp15** [comment]
Hello,

I'm having a similar error. I've installed and loaded:
library(scater)
library(MAST)
library(Seurat)

and ran this code:

`DEMAST <- FindMarkers(cells, ident.1 = "2", ident.2 = "12", test.use = "MAST",  assay = "RNA")`

and obtain this: 
`Error in sanity_check_sca(obj) : 
  Assay in position 1, with name et is unlogged. Set `check_sanity = FALSE` to override and then proceed with caution.`

Of note, I've already visited issue #2345 and added assay = "RNA" and still obtain the error above. I think it may be that I am not pulling out which variables to use for testing? Any advice is more than welcome. 

Thanks for your help!

**Comment by mr-september** [comment]
Hi, sorry but could someone please explain what exactly was the code added to "fix" this?
I tried adding
`DefaultAssay(pbmc) = "RNA"`
one line before running `FindAllMarkers`, which didn't work.
Adding the `assay = "RNA"` parameter also didn't work.

In the other thread: 
> I would set default assay to RNA for DE analysis. I would also make sure that data slot in RNA assay is normalized.

How exactly can I do this/check that it is done? I know I have a counts and separate `sizeFactor` column under `meta.data`, since I converted this dataset to `SCE` type to run `scran`, then converted it back to `Seurat`.
