### ISSUE TITLE
UMAP or t-SNE with UMI codes !

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2348]
Hi
I have to highlight cell bar codes (UMI codes).  

I have filtered out some UMI barcodes codes(See below) with following tutorial link  https://satijalab.org/seurat/v3.0/interaction_vignette.html

each UMI codes has a biological meaning, So, i would like to highlight these UMI codes into a UMAP or t-SNE with rest of the dataset?   
1","ABS28_3_AACTCCCGTGGACGAT"
"2","ABS28_3_AAGGCAGGTGAGTATA"
"3","ABS28_3_AAGGTTCCAATCTGCA"
"4",ABS28_3_ACTGTCCCATGCCCGA"

Means, I have to highlight cells with the UMI codes, see an example fig (below) 

![image](https://user-images.githubusercontent.com/40278254/69351144-19b4a000-0c7b-11ea-99f7-e92467785af9.png)

**Comment by timoast** [comment]
Do you mean highlight certain the cell barcodes? That can be done with the `cells.highlight` parameter in DimPlot. If you want to highlight cells with counts that had a certain UMI sequence, that information is not typically stored but you could add it to the metadata and then plot it using FeaturePlot.

**Comment by MalteMederacke** [comment]
I have a related question: I have a matrix consisting of a subset of cell barcodes and for every barcode one rational number. I want to highlight every barcoded cell proportional to this value. How would I do this?
