### ISSUE TITLE
Adding transparency to Featureplot blend = TRUE

### ISSUE THREAD

**Issue by kmshort** [satijalab/seurat#2349]
Seurat 3.11 can display colours with an alpha transparency channel in the form RGBA, and this works with standard FeaturePlot
`FeaturePlot(object = data, features = c("thingo_1", "thingo_2"), cols = c("#4AEB8E33", "#FF5A1233"), pt.size = 1)`
with alpha being #33 (#00 = fully transparent, #FF is opaque).

This is great, but as soon as you invoke blend=TRUE in FeaturePlot, the RGBA is trimmed automatically back to RGB and transparency is lost. Presumably scaling was only intended for RGB so everything else is ditched during scaling calculation. So when blend = TRUE is invoked, can scaling also please be applied to A, so that RGBA is maintained and scaled for FeaturePlot in this case?

**Comment by yuhanH** [comment]
Hi, 
Sure. We will convert the RGB to RGBA in the blend plot soon. Thanks for your suggestions.

**Comment by mojaveazure** [comment]
This should be present in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
