### ISSUE TITLE
Differential expressed genes from merged seurat objects

### ISSUE THREAD

**Issue by tulikakakati** [satijalab/seurat#2351]
Hi,
Please correct me, if I am wrong.
I have two different samples of scRNAs (Normal and Disease). First I created two seurat objects (n and d) and then merged them using merge(n,d). I used the merged_object further for differential expression analysis after clustering. I used FindMarkers(merged_object, ident.1 = id, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE) function to find the marker genes for each cluster represents the differentially expressed genes.

My queries to you is as follows:

The cell clusters composed of cells from both normal and disease samples. So do the markers we found from these clusters signify the differentially expressed genes between normal and disease cells or between different clusters of merged objects.
Thank you

**Comment by timoast** [comment]
It depends what groups you have contrasted in `FindMarkers`, from this it's not clear what the variable `id` is. Does it group cells by cluster and normal/disease, or only cluster, or only normal/disease?

**Comment by tulikakakati** [comment]
Here, id is each cell cluster.

It grouped cells by cluster with normal/ disease. For example, cluster 1 will have cells from both normal as well as disease samples.
ah-ACACGCGCACGGCGTT
ah-ACTATGGCATAACTCG
ah-AGATAGAGTTTCCAAG
ah-CCTGTTGCAATAGTCC
ah-GCATGATCAGTCAACT
ah-GGTAATCTCATCACAG
ah-GTGGCGTTCTCGCCTA
ah-GTTCCGTTCAAAGGAT
ah-TCATTGTCACTCCCTA
ah-TCCTTTCCACGGTCTG
ah-TTCTTGAAGATTGCGG
hc-AACCCAAAGGCGTTGA
hc-AATTCCTGTGACTAAA
hc-AGATGAAGTTGGCCGT
hc-ATAGGCTAGGCTCTCG
hc-ATCGATGAGTCCGTCG
hc-ATGACCAAGCTCAGAG
hc-ATGACCATCACCTGGG
hc-ATTCCTAGTGGCGTAA
hc-CAGATTGTCGGTTAGT
hc-CCACACTAGATCCGAG
hc-CCTAACCTCCACTGAA
hc-CCTACGTGTAGCTTGT
hc-CCTCAACTCCTACCGT
hc-GGCTTTCAGGATCATA
hc-GTACAACTCTCCTGTG

And the marker gene I found from this cell cluster is listed below:

myAUC | avg_diff | power | pct.1 | pct.2 |  
-- | -- | -- | -- | -- | --
LTB | 0.871 | 1.117306 | 0.742 | 0.995 | 0.666
IL7R | 0.84 | 0.993148 | 0.68 | 0.944 | 0.489
RPS29 | 0.821 | 0.594928 | 0.642 | 1 | 0.997
TPT1 | 0.813 | 0.509112 | 0.626 | 1 | 0.999
IL32 | 0.791 | 0.753823 | 0.582 | 0.955 | 0.612
RPL41 | 0.781 | 0.389246 | 0.562 | 1 | 0.999
RPS27 | 0.779 | 0.483321 | 0.558 | 1 | 0.999
RPL36 | 0.772 | 0.423398 | 0.544 | 1 | 0.994
RPL39 | 0.771 | 0.416769 | 0.542 | 1 | 0.998
RPL23A | 0.769 | 0.424361 | 0.538 | 1 | 0.998
RPS18 | 0.766 | 0.453968 | 0.532 | 1 | 0.999
RPL37 | 0.765 | 0.387516 | 0.53 | 1 | 0.999
RPS21 | 0.755 | 0.410167 | 0.51 | 0.998 | 0.969
RPL18A | 0.754 | 0.387009 | 0.508 | 1 | 0.999
EEF1A1 | 0.751 | 0.376171 | 0.502 | 1 | 0.999
LDHB | 0.75 | 0.487094 | 0.5 | 0.944 | 0.671
RPL13 | 0.75 | 0.398402 | 0.5 | 1 | 0.999
RPL14 | 0.746 | 0.366663 | 0.492 | 1 | 0.998
CD3D | 0.741 | 0.470769 | 0.482 | 0.945 | 0.556
RPS28 | 0.74 | 0.340005 | 0.48 | 1 | 0.999
RPL7A | 0.74 | 0.320323 | 0.48 | 1 | 0.999
RPS4Y1 | 0.739 | 0.541711 | 0.478 | 0.893 | 0.611
AQP3 | 0.739 | 0.531384 | 0.478 | 0.598 | 0.134
RPSA | 0.739 | 0.411218 | 0.478 | 1 | 0.99
RPL10A | 0.739 | 0.384066 | 0.478 | 1 | 0.997
RPLP1 | 0.739 | 0.345047 | 0.478 | 1 | 0.999
RPS2 | 0.738 | 0.356415 | 0.476 | 1 | 0.999
RPS12 | 0.735 | 0.385934 | 0.47 | 1 | 0.999

**Comment by timoast** [comment]
If the groups you're contrasting contain cells from both conditions then the answer is no. If you want to contrast disease/normal you will need to add that as a grouping variable and specify the grouping variable in FindMarkers. See this vignette for more information: https://satijalab.org/seurat/v3.1/immune_alignment.html

**Comment by tulikakakati** [comment]
Thank you
