### ISSUE TITLE
FeaturePlot(order) vs. FeaturePlot(sort.cells)

### ISSUE THREAD

**Issue by samuel-marsh** [satijalab/seurat#2352]
Hi,

Just a clarifying question.  In `FeaturePlot` there are two arguments `order` and `sort.cells` but unless I'm mistaken these arguments are actually just doing the same thing (moving expressing cells in front of non-expressing cells).  Is there rationale for `order` vs. `sort.cells`?

Thanks very much!!
Sam

**Comment by yuhanH** [comment]
You are right. 
`sort.cell` is a redundant parameter. It will be deleted in the next released version.

**Comment by satijalab** [comment]
This does appear to be redundant. Thanks for pointing out - we will take a look (@k3yavi @andrewwbutler )

**Comment by andrewwbutler** [comment]
Yep, this is redundant. Thanks for reporting! We have deprecated the `sort.cell` parameter now in the `develop` branch with a warning and it should be removed in the next minor release (3.2.0).
