### ISSUE TITLE
error in Integration 

### ISSUE THREAD

**Issue by Shawn10312** [satijalab/seurat#2353]
hi,
It is wrong in integrating several samples' data.

>>for (i in 1:length(SeuratObject.list)) {
  SeuratObject.list[[i]] <- NormalizeData(SeuratObject.list[[i]], verbose = T)
  SeuratObject.list[[i]] <- FindVariableFeatures(SeuratObject.list[[i]], selection.method = "vst", 
                                                 nfeatures = 3000, verbose = T)
}
>>SeuratObject.anchors <- FindIntegrationAnchors(object.list = SeuratObject.list, dims = 1:30)

Merging objects
Finding neighborhoods
Finding anchors
        Found 93 anchors
Filtering anchors
        Retained 9 anchors
Extracting within-dataset neighbors
  |+++++++++++++++                                   | 29% ~01m 38s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 110 anchors
Filtering anchors
        Retained  anchors
Error in `$<-.data.frame`(`*tmp*`, "cell2", value = integer(0)) :
  replacement has 0 rows, data has 3

So how to overcome the error?

Thanks.

**Comment by timoast** [comment]
How many cells do you have in each object? The integration algorithm weights information over neighboring cells, so there is a minimum number of cells required to run the integration. Here you are finding only 9 anchors, which is not enough to proceed with the integration.

**Comment by Shawn10312** [comment]
3000 ~ 5000 cells / sample

**Comment by timoast** [comment]
Do you expect common cell states between the different samples?

**Comment by Shawn10312** [comment]
Those samples have the same pathological results. So there should be the common cell states among them.

By the way, I just want to remove the "batch-effect" among those samples by using the Integration in Seurat.

**Comment by Shawn10312** [comment]
Or other methods can you recommend?
I want to remove the "batch-effect" among those samples, because the heterogeneity of clinical samples is so obvious.

**Comment by Shawn10312** [comment]
New problem:

for (i in 1:length(SeuratObject.list)) {
  SeuratObject.list[[i]] <- NormalizeData(SeuratObject.list[[i]], verbose = T)
  SeuratObject.list[[i]] <- FindVariableFeatures(SeuratObject.list[[i]], selection.method = "vst", 
                                                 nfeatures = 3000, verbose = T)
}                                   ### done
SeuratObject.anchors <- FindIntegrationAnchors(object.list = SeuratObject.list, dims = 1:30)  ### done
SeuratObject.integrated <- IntegrateData(anchorset = SeuratObject.anchors, dims = 1:30)
### error 
Merging dataset 2 into 3
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
Error in nn2(data = c(-8.29099889797187e+214, -1.47044325485371e+214,  :
  Cannot find more nearest neighbours than there are points


So what this about?

**Comment by timoast** [comment]
Closing this now as I believe this was addressed in other issues, please create a new issue if you're still having problems
