### ISSUE TITLE
Tracking cells on UMAP plot

### ISSUE THREAD

**Issue by myaqubi** [satijalab/seurat#2354]
Hi 

In my project I am going to merge 12 single cell RNAseq datasets (about 20000 cells). I am particularly interested in a small cluster which contains proliferative cells. However, when I increase my sample size form 10 datasets to 12 datasets that cluster disappears. I'm wondering if there is a way in Seurat to track the cells of that specific cluster to locate them in the new umap plot?

**Comment by timoast** [comment]
You can color cells by the old clustering information, or you can use the `cells.highlight` parameter to highlight specific cells.
