### ISSUE TITLE
confusion in plotting gene expression 

### ISSUE THREAD

**Issue by yinshiyi** [satijalab/seurat#2355]
Here my object is pancreas.integrated, and gene of interest is CFTR

1
CFTR<-as.data.frame((pancreas.integrated@assays$RNA@counts)[c('CFTR'),])
#This is the actual raw count from the matrix
2 
my.data=FetchData(pancreas.integrated,c("ident","orig.ident","CFTR"))
#this is the value used in the Featureplot?

There two values are different, as [2] seems to be roughly the log of [1], can you provide more details of the differences between these two methods of getting the gene expression values?

Thanks.

**Comment by timoast** [comment]
By default the normalized data is used for most plots (FeaturePlot, VlnPlot), and scaled data used for heatmaps. In (1), you're extracting the raw counts, and in (2) you are extracting the normalized data. See the Seurat documentation for more information: https://satijalab.org/seurat/
