### ISSUE TITLE
How is scaleData handled when a seurat object is derived from a single cell object

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#2357]
Hello!

I have a question about the scaleData function and the pipeline in general from a seurat object made from a SCE object. 
The SCE object i have already has information such as percent mitochondrial percentage, total counts etc....

For this reason i do not run the mitochondrial percentage step in the pre-processing step from seurat as this information is already contained within the metadata. 

Given that this is the case, when scaling the data, i chose to not to regress out variable such as mitochondrial effects after i have filtered them to a certain threshold anyway. 

Does Seurat do any internal regressing of any factors during scaleData? If so, are there any columns in the metadata that this is dependent on (again bearing in mind the pre-processing hasn't taken place via seurat) or is this re-calculated internally during the scaleData function. 

Thank you for clarifying!

**Comment by andrewwbutler** [comment]
Hi,

Only variables specified in the `vars.to.regress` argument will be regressed out in `ScaleData`. If you don't specify this parameter, no variables will be regressed out.
