### ISSUE TITLE
Output of FindConservedMarkers

### ISSUE THREAD

**Issue by tulikakakati** [satijalab/seurat#2358]
Hi,
I used FindConservedMarkers() to find the marker genes for each cluster, irrespective of the sample conditions (AH and HC). However, I did not understand the meaning of the hc.pct.1. hc.pct.2, ah_pct.1 ah_pct.2 in the following output.

> markers <- FindConservedMarkers(liver.integrated, ident.1 = 7, grouping.var = "orig.ident", verbose = FALSE)
> head(markers)
                   hc_p_val hc_avg_logFC **hc_pct.1 hc_pct.2**  hc_p_val_adj
CD8B          2.573636e-268    1.3819406    0.787    0.078 8.425569e-264
RP11-291B21.2 1.115839e-240    0.9164708    0.353    0.012 3.653035e-236
CD8A          3.111320e-103    0.7165588    0.545    0.088  1.018584e-98
NELL2          3.419409e-75    0.5614590    0.306    0.041  1.119446e-70
RPS3A          7.267388e-71    0.5625362    1.000    0.930  2.379197e-66
RPS6           1.706379e-69    0.5947169    1.000    0.920  5.586344e-65
                   ah_p_val ah_avg_logFC **ah_pct.1 ah_pct.2**  ah_p_val_adj
CD8B           0.000000e+00    1.5245020    0.928    0.076  0.000000e+00
RP11-291B21.2  0.000000e+00    0.9073176    0.606    0.037  0.000000e+00
CD8A          1.325729e-285    0.8995138    0.805    0.085 4.340172e-281
NELL2         1.318252e-127    0.6410246    0.518    0.083 4.315692e-123
RPS3A          6.194803e-84    0.5629633    1.000    0.972  2.028055e-79
RPS6           3.864762e-83    0.6076260    1.000    0.968  1.265246e-78
                   max_pval minimump_p_val
CD8B          2.573636e-268   0.000000e+00
RP11-291B21.2 1.115839e-240   0.000000e+00
CD8A          3.111320e-103  2.651458e-285
NELL2          3.419409e-75  2.636503e-127
RPS3A          7.267388e-71   1.238961e-83
RPS6           1.706379e-69   7.729525e-83

Thanks

**Comment by yuhanH** [comment]
Hi,
You can find the definition of pct using `?FindMarkers`.
pct.1: The percentage of cells where the gene is detected in the first group.
In your case, hc_pct.1 means the percentage of `HC cells` where the gene is detected in the `ident 7`
