### ISSUE TITLE
Mismatch for default test.use in 'FindAllMarkers' usage and arguments list

### ISSUE THREAD

**Issue by dhsamp** [satijalab/seurat#236]
Hi,
Just want to bring to your notice that in Seurat v2.1 vignette page 50, there is a mismatch for 'FindAllMarkers' usage: test.use="bimod" whereas in arguments it's mentioned that 'wilcox' is the default. I am aware that FindMarkers (page 55)has both usage and arguments as 'Wilcox' default. 

Could you correct this in your vignette so it avoids the confusion?

**Comment by andrewwbutler** [comment]
The tutorial has been updated to reflect this and now also links to the more detailed DE vignette. Thanks!
