### ISSUE TITLE
load large seurat dataset in monocle error

### ISSUE THREAD

**Issue by LIUMENG004** [satijalab/seurat#2361]
I try to import raw Seurat 2 data into monocle 2, with the following code:

 **tenx <- importCDS(tenx)**

then, it told me:
**Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105**

My data is around 100k cells and 30000 features, so how to solve the problem?

**Comment by timoast** [comment]
This is really a question you should ask the monocle authors, but please see our dataset conversion [vignette](https://satijalab.org/seurat/v3.1/conversion_vignette.html)
