### ISSUE TITLE
Question regarding how singlecell data slot behaves in suerat when object is created from singlecellexperiment

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#2362]
Hello, 

I was wondering if you could clarify an issue i am having with conversion of a singlecell object to seurat object using the as.Seurat function.

I don't want keep logcounts present in the singlecell object as I would like to carry out the normalisation steps as part of the seurat pipeline. I have come across something a little strange (but maybe it is intended to be this way)..

When I read in my data as follows:
`seuratObj<-as.Seurat(sce, data="counts")or
`
`seuratObj<-as.Seurat(sce, counts="counts", data=NULL)
`
the object is created without errors. the RNA assay however, contains both counts and data slots. At this point, BOTH counts and data contain RAW counts. May i confirm this is the correct behaviour of the conversion?

I need to read it in this way as my SCE object only contains the raw counts in the assay and when attempting to create the seurat object as

`seuratObj<-as.Seurat(sce, counts="counts")`

I get an error stating that there is no file in the assay called logcounts. Now to me this is correct as i do not want to import any normalised counts and would like this step to be explicitly carried out in the seurat pipeline and so i what i really want is for the raw counts to be read in with no normalised counts at all... May i therefore confirm that the first two ways of reading in the object are correct?

After normalising (when i read in the object in the first two ways), the counts lsot in the RNA assay retains the raw counts, and the data slot now becomes normalised. I assume this is the correct behaviour?

Please can you confirm that the scaleData function is indeed working from the normalised counts in the data slot and not from the counts slot, and that the fact that raw counts are present in both slots when the object is first created from a singlecell object is intentional? 

I could not find the source code for scaleData so am unsure of which slot it is calling..

Similarly, when i normalise the counts in the singlecell object prior to seurat conversion and then convert the object as follows:

`sce<-as.Seurat(sce, counts="counts")

This works without any errors however the data slow now contains the logscale normalized counts from the SCE object. 

I run the noramlization step in the suerat pipeline. May i confirm at this point that the normalization simply overwrites the logcounts from the SCE object and created the normalized data as per the seurat function? 

I assume it does as creating a counts data frame from all three methods above, all data frames are identical (identical())... TRUE

Sorry for the lengthy post but just want confirmation that the raw counts existing in the data slow after creating the seurat object by:

`seuratObj<-as.Seurat(sce, data="counts")or
`
`seuratObj<-as.Seurat(sce, counts="counts", data=NULL)
`

and that after normalization, all subsequent code is using the data slow (normalized counts) and not raw counts. 

many thanks!
`

**Comment by andrewwbutler** [comment]
Hi,

1. Yes it expected that both the `counts` and `data` slot contain the raw counts immediately after converting based on the commands you ran. This way of doing things is fine. 
2. Yes, after normalizing in Seurat, the data slot should contain the normalized data (and the `counts` slot still contains the raw data). 
3. Yes, `ScaleData` works off of the normalized data (`data` slot). The source code for `ScaleData` is [here](https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/preprocessing.R#L2420) 
4. `NormalizeData` always works off of the `counts` slots and will overwrite the `data` slot.
