### ISSUE TITLE
NA feature for DotPlot found in RNA assay

### ISSUE THREAD

**Issue by bryanyung** [satijalab/seurat#2363]
Hello,

I'm running the dotplot function after integrating two datasets (treated vs untreated), and when I try to examine a certain gene, I get this warning message: "Warning: Could not find Ptprc in the default search locations, found in RNA assay instead" and I see this: 
<img width="198" alt="Screen Shot 2019-11-25 at 10 40 05 AM" src="https://user-images.githubusercontent.com/43685419/69568175-f9812b80-0f6f-11ea-8043-4348e423c8ee.png">

Is there a way to include the gene name as a label on the X axis?

**Comment by timoast** [comment]
We recommend that you visualize the original RNA values, not the integrated data. Do you still have this issue when changing the default assay to RNA?

**Comment by ktrns** [comment]
Hi there. I had the same problem: 
`Warning: Could not find Sox1 in the default search locations, found in RNA assay instead
`

My default assay was SCT. After switching it to RNA, the plot contained "Sox1" rather than "NA". 

Would you generally recommend doing plots (DotPlot, FeaturePlot,...) for RNA rather than SCT?

Thanks!

**Comment by denvercal1234GitHub** [comment]
@ktrns - Did you find the answers to this question? I have the same issue. Thank you!

**Comment by AndyXG** [comment]
I got the same issue, and then I found adding assay="..." can solve the problem. Maybe you should have a try, for example:
DotPlot(sample.combined,features = unique(top5markers$gene),assay = "Protein")+RotatedAxis()+coord_flip()

**Comment by npont** [comment]
Hello, I have the same problem even when adding manually assay="SCT" in DotPlot (which makes no sense as SCT is the active assay). Anyone solved this issue?
