### ISSUE TITLE
FindMarkers - number of genes divided by Bonferroni correction

### ISSUE THREAD

**Issue by phoebee-h** [satijalab/seurat#2364]
Hi, 
Seurat is a convenient tool for me. Thanks for the good work! 

Here's my little concern: 
While subsetting single-cell data into a new Seurat object, there could be some genes eliminated, right? Since some genes only expressed in the cells that were filtered.

![image](https://user-images.githubusercontent.com/28743573/69594190-7f67aa00-1036-11ea-8dd8-283aeda5c429.png)

**Comment by timoast** [comment]
In your example above you're only subsetting the cells, not features, so the same set of features is present in the subset object.

**Comment by phoebee-h** [comment]
Hi,
Oh, so in this case, if we filtered the cells, we should probably do something like this? 
```
# (1) Prevent count matrix from feature_count = 0 across cells.
old <- CreateSeuratObject(counts = oridata, project = "ori", min.cells = 1)
old[["percent.mt"]] <- PercentageFeatureSet(old, pattern = "^[M|m][T|t]-")

# (2) Prevent count matrix from feature_count = 0 across cells after subsetting
new <- subset(old, subset = nFeature_RNA > 200  & nFeature_RNA < 2500 & percent.mt < 25)
notzerogenes <- which(rowSums(data.frame(new[["RNA"]]@counts))!=0)
new <- subset(new, features = notzerogenes)
```
![image](https://user-images.githubusercontent.com/28743573/69786199-e3d06800-11f4-11ea-9b67-cb5d6dab7e9c.png)

Or do you have any suggestions?
Thank you!

**Comment by timoast** [comment]
Yes that’s reasonable, although you don’t need to coerce the count matrix to a dataframe, using `Matrix::rowSums` will be much faster

**Comment by phoebee-h** [comment]
Got it. 
Thank you!
