### ISSUE TITLE
Scale the data 

### ISSUE THREAD

**Issue by rosaranli** [satijalab/seurat#2365]
Thank you for this wonderful tool. I have a few questions about the function ScaleData.

In the argument explanation of this function, it says

features: Vector of features names to scale/center. Default is all features

I would assume that ScaleData(data,features=rownames(data)) does the same thing as  ScaleData(data), but I noticed that the latter one runs much faster that the former one. Could you please explain that ScaleData(data) runs on all features or NULL features? 

Another question about ScaleData is,

Sometimes I play around with a subset of a Seurat object which has been scaled.  I would assume that I have to rescale the data again once I get a subset because the centres and deviation of the data may change in the subset. Does the scaling work on the scaled data, or on the raw data? 

Thank you very much!

**Comment by timoast** [comment]
Hi, in this case the documentation for ScaleData is actually incorrect and the default is to scale only the variable features. This is why you find using `features = rownames(data)` to be slower, as it is running on many more features than the default. We will fix the documentation soon.

Yes, you should re-scale after subsetting the data as the mean and sd will change by removing a subset of cells. The scaling uses normalized data, not raw counts.

**Comment by rosaranli** [comment]
Thank you for your reply. I also noticed that if FindVariableFeatures was not ran before ScaleData, the default features would be all the features, rather than the variable features.
I have another question about ScaleData. If I regress out some features, shall I always do it in one go? For example, If I regress out nUMI first when scale the data, then regress out the score of cell cycle genes when scale the data the second time, does that mean I have to regress out the nUMI again because the second one would overwrite the first  one?

**Comment by timoast** [comment]
Yes, the running again will overwrite the results of the first run.

**Comment by rosaranli** [comment]
Sorry I still have a question about Scale.Data. If I use the genes from one chromosomes to scale the data, that means there are only, for example, 1000 genes in scale.data. Does that mean when I RunPCA, the default input would be the scaled 1000 genes?

**Comment by timoast** [comment]
The default for RunPCA is to use the variable features, but there is a requirement that the features are scaled. You can find the documentation for these functions by running `?<function_name>`, eg `?RunPCA`

**Comment by rosaranli** [comment]
Thank you very much for your reply. The document has an error so ?RunPCA doesn't help. I noticed that even in the data$RNA@scale.data, the number of genes is 1000 but the number of variable genes is 2000, RunPCA can still work. If it require variable genes has to be scaled, how can this happen? Does RunPCA work on the data data$RNA@scale.data?

**Comment by timoast** [comment]
What's the error in the RunPCA documentation? RunPCA can only use features present in the scaled data, and will issue a warning when you request features not in scaled data, but will still proceed with the subset that are scaled.

**Comment by rosaranli** [comment]
Thank you very much for your clarification. That helps a lot. When I said the document had an error I actually meant ScaleData. Sorry I mixed them up. But about RunPCA, it will be great if it also specify what the default features are in it, when it says "Features to compute PCA on" about Features in the current version.

**Comment by timoast** [comment]
We do state the default features the RunPCA documentation:

> `features`     Features to compute PCA on. If features=NULL, PCA will be run using the variable features for the Assay

I will add another note in the docs to highlight the fact that features must also be present in the scale data.

**Comment by timoast** [comment]
These documentation fixes are now in the latest Seurat release
