### ISSUE TITLE
How to pull the exact list of colors used in DimPlot?

### ISSUE THREAD

**Issue by cpcook1** [satijalab/seurat#2366]
Is there a way to generate a list that DimPlot uses for coloring the clusters? I want the exact colors to use to match up some other plots. So for example if I plot 12 clusters, ask the system to return a list of the 12 colors used in those clusters.

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Dimplot uses the default ggplot2 color scheme.  You can view the hex codes and see the colors using the scales package:
`show_col(hue_pal()(12))`

or you can create list manually using this function:
```
ggplotColours <- function(n = 6, h = c(0, 360) + 15){
  if ((diff(h) %% 360) < 1) h[2] <- h[2] - 360/n
  hcl(h = (seq(h[1], h[2], length = n)), c = 100, l = 65)
}

color_list <- ggplotColours(n=4)
```

Source: [https://stackoverflow.com/questions/8197559/emulate-ggplot2-default-color-palette](https://stackoverflow.com/questions/8197559/emulate-ggplot2-default-color-palette)

Best,
Sam
