### ISSUE TITLE
Merging when features are unique to a dataset after SCTransform

### ISSUE THREAD

**Issue by d93espinoza** [satijalab/seurat#2368]
Hi Seurat team,

I have 2 datasets (A and B) that I am attempting to merge in Seurat. The 2 datasets have been independently run through SCTransform. However, I am running into the case where a feature, say "Gene X", is a variable feature in Dataset A (and present in the SCT scale.data slot), but is not present in Dataset B either in the RNA assay or the SCT assay at all. 

Thus when merging, Seurat cannot calculate a Pearson residual for Gene X in Dataset B and the feature is excluded from the merged Seurat object's SCT scale.data slot. Then Gene X will not be used in the downstream PCA, which is calculated from the merged object's SCT scale.data slot. In my case, I am finding that because of this, there are informative features in Dataset A that become excluded from the merged object's SCT scale.data slot and thus do not influence the merged object's PCA dimensionality reduction.

In the above case, is there an appropriate way to get a Pearson residual for Gene X in Dataset B or set it to some value (given that it does not exist in Dataset B) prior to the merging in order to prevent this from happening? I would like to use features such as Gene X for the PCA dimensionality reduction step of the merged object.

Thanks!

**Comment by davisidarta** [comment]
Hi - I have run through similar trouble,

I would recommend you merged these objects with `merge`. This way, Seurat will automatically make the union of genes expressed in at least one dataset. You can further split this object with `SplitObject` (add some metadata to set in  the `'split.by'` argument). Now your datasets have the same number of rows (genes) in the RNA slot.

You should now set the argument `return.only.var.genes = F` in `SCTransform` and continue with your workflow. This will make that all genes are added to the SCT@scale.data slot, regardless of being highly variable or not. That resolved the issue in my case.

**Comment by yuhanH** [comment]
Thanks, davisidarta.
When you set `return.only.var.genes = F`, the issue can be solved.
Or you can run `GetResidual` on Dataset B with the feature "Gene X". It will add "Gene X" in the Dataset B SCT scale.data.

**Comment by d93espinoza** [comment]
> Hi - I have run through similar trouble,
> 
> I would recommend you merged these objects with `merge`. This way, Seurat will automatically make the union of genes expressed in at least one dataset. You can further split this object with `SplitObject` (add some metadata to set in the `'split.by'` argument). Now your datasets have the same number of rows (genes) in the RNA slot.
> 
> You should now set the argument `return.only.var.genes = F` in `SCTransform` and continue with your workflow. This will make that all genes are added to the [SCT@scale.data](mailto:SCT@scale.data) slot, regardless of being highly variable or not. That resolved the issue in my case.

Thanks for the replies, @davisidarta and @yuhanH . However, I am still a bit confused. In the above example, that @davisidarta posited, after merging A and B and then splitting, Dataset B would indeed have Gene X in the "RNA" assay because of its presence in Dataset A. The values for Gene X in Dataset B's "RNA" assay would be all zeros as it is not present in any cells in Dataset B. Thus, when calling SCTransform on Dataset B, Gene X would not be included in the "SCT" assay because SCTransform requires a "min_cells" of at least 1 to even include in the "SCT" assay (in the counts or data slot). Because Gene X is not in the counts or data slot of the "SCT" assay of Dataset B, "GetResidual" cannot be called on it.
