### ISSUE TITLE
Error merging seurat objects

### ISSUE THREAD

**Issue by jydong123** [satijalab/seurat#2370]
Hi, I'm trying to merge three Seurat objects, each from a biological replicate, so all the data may be 
analyzed together based on the group. I loaded up three .rds files which are "An object of class Seurat", used the following command:

sham.big <- merge(sham1, y = c(sham2, sham3), add.cell.ids = c("1", "2", "3"), project = "shamyoung")

And the following error resulted: 

Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("Seurat", package = "Seurat")’ to a data.frame

Please help, thank you!

Jeff

**Comment by davisidarta** [comment]
You're using c() - which concatenates vectors, i.e. one-dimensional arrays -  with Seurat objects. `merge` takes lists of Seurat objects as arguments in `y` when you want to merge more than two objects at once. 

Can you see if this resolve the issue?
`sham.big <- merge(sham1, y = list(sham2, sham3), add.cell.ids = c("1", "2", "3"), project = "shamyoung")`

**Comment by jydong123** [comment]
Worked perfectly. Thank you so much!
