### ISSUE TITLE
Percentage of cells expressing a particular gene increases in representative cluster in integrated dataset with respect to original data set.

### ISSUE THREAD

**Issue by charlesgwellem** [satijalab/seurat#2372]
Hi, I have followed [this standard tutorial](https://satijalab.org/seurat/v3.0/integration.html) to integrate my single cell rna seq data with another one which I found online. The cells in both datasets are the same cell type but the treatments are different. I have clustered each of the datasets independently. I also did an integration because I want to compare the phenotypes of the cells using a dot plot of some particular genes. After integration, I grouped the dotplot by treatment type.

However, I have noticed that some genes have a significanlty  higher percentage expression in the integrated clusters that represent each treatment compared to their expression in each of the datasets.

For illustration, I take the example of the expression of Il5 and Notch1 genes:

Dotplot of independent dataset1 - Treatment A

![treatmenta](https://user-images.githubusercontent.com/10155881/69870703-0d4ec980-12b1-11ea-9a7b-3e97fb17189d.png)

Dotplot of independent dataset2 - Treatment B

![treatmentb](https://user-images.githubusercontent.com/10155881/69866499-885db300-12a4-11ea-9b1a-8436f1e6e003.png)

Integrated TSNE

![integrated tsne](https://user-images.githubusercontent.com/10155881/69865867-c1952380-12a2-11ea-8f44-2b6b54c740e3.png)

Integrated Dotplot

![integratedAandB](https://user-images.githubusercontent.com/10155881/69866511-927fb180-12a4-11ea-8f97-0a58863d2e52.png)

Can someone please help explain to me what is happening and if there is an error somewhere?

Thanks in advance.

**Comment by timoast** [comment]
This is due to plotting integrated data rather than the untransformed values. The integration methods will adjust the expression values in order to remove technical differences between the groups to be integrated. We don't recommend visualization or DE on the integrated data

**Comment by charlesgwellem** [comment]
Thanks for your response. Is there a recommended way in Seurat to compare the phenotypes of cells treateted under different conditions with respect to their expression of selected genes?

**Comment by timoast** [comment]
Yes, we recommend that you identify common cell states by clustering with the integrated data, and use the un-corrected data for differential expression between conditions
