### ISSUE TITLE
Error in opening anndata in R. 

### ISSUE THREAD

**Issue by KalkiKukreja** [satijalab/seurat#2373]

**Comment by KalkiKukreja** [comment]
I use scanpy for scRNA seq analysis and wanted to try some functions written in R. So, I was trying to open anndata object using ReadH5AD and I got this error:

Error in sparseMatrix(i = x[["indices"]][] + 1, p = x[["indptr"]][], x = x[["data"]][],  : 
  all(dims >= dims.min) is not TRUE

The anndata object I am trying to open doesn't even have a Sparse matrix (it is scaled) so I am not able to comprehend what this error means.

**Comment by yuhanH** [comment]
duplicated with https://github.com/satijalab/seurat/issues/2374
