### ISSUE TITLE
Error in opening anndata in R. #2373

### ISSUE THREAD

**Issue by KalkiKukreja** [satijalab/seurat#2374]
I use scanpy for scRNA seq analysis and wanted to try some functions written in R. So, I was trying to open anndata object using ReadH5AD and I got this error:

Error in sparseMatrix(i = x[["indices"]][] + 1, p = x[["indptr"]][], x = x[["data"]][], :
all(dims >= dims.min) is not TRUE

The anndata object I am trying to open doesn't even have a Sparse matrix (it is scaled) so I am not able to comprehend what this error means.

**Comment by dylkot** [comment]
I have the same problem. I tested this out with a minimal AnnData object consisting of just obs, var, and X (in sparse csc_matrix format) attributes. I am using Seurat_3.1.1

**Comment by satijalab** [comment]
See #2485. We are looking into this- so please feel free to post any example files that are not loading so that we can debug

**Comment by mukund109** [comment]
> I have the same problem. I tested this out with a minimal AnnData object consisting of just obs, var, and X (in sparse csc_matrix format) attributes. It is 58126 cells x18266 genes and I filtered out any genes detected in <5 cells and any cells with fewer than 200 genes detected. I am using Seurat_3.1.1

I had the same issue, fixed it by saving it in sparse row format `scipy.sparse.csr_matrix`
