### ISSUE TITLE
integration of umap original neighbour searching method

### ISSUE THREAD

**Issue by MichaelPeibo** [satijalab/seurat#2376]
Hi Seurat team,
Is it possible to add umap original neighbor search efficiency [method ](https://arxiv.org/abs/1802.03426) like scanpy's [`pp.neighbor` does](https://icb-scanpy.readthedocs-hosted.com/en/latest/api/scanpy.pp.neighbors.html)?

Because I found in my time course data, using scanpy default pipeline can produce better consistency among series time points. Then I checked the methods both packages use, my guess is different between UMAP based neighbour searching and SNN based graph construction.

**Comment by satijalab** [comment]
You can set RunUMAP to use the python umap version (umap-learn), which should replicate the exact neighbor-finding algorithm used in the python pacakge. The differences should be quite minor.
