### ISSUE TITLE
SDMTools dependency is orphaned

### ISSUE THREAD

**Issue by mjsteinbaugh** [satijalab/seurat#2377]
Hi Seurat devs,

I'm seeing an error pop up when you install Seurat with all dependencies:

```r
install.packages("Seurat", dependencies = TRUE)
```

The [SDMTools](https://cran.r-project.org/package=SDMTools) package is orphaned and currently imports [adehabitat](https://cran.r-project.org/web/packages/adehabitat/index.html), which is no longer available on CRAN. This can cause installation of Seurat to fail.

This import in Seurat may need to be moved into the package:

```
importFrom(SDMTools,pnt.in.poly)
```

@jjvanderwal Can we push an update to SDMTools that removes the adehabitat dependency?

Best,
Mike

**Comment by mjsteinbaugh** [comment]
See related issue https://github.com/jjvanderwal/SDMTools/issues/2

**Comment by mojaveazure** [comment]
Hi Michael,

Why are you setting `dependencies = TRUE`? The default for this argument (`dependencies = NA`) is enough to get Seurat installed and running. Setting `dependencies = TRUE` installs all suggested packages, which can introduce errors like the one you're seeing here (suggested packages aren't stringently checked by CRAN, which is how these errors are allowed to propagate).

As seen on the [CRAN page for SDMTools](https://cran.r-project.org/package=SDMTools), adehabitat is suggested, not imported. If you aren't having R install suggested packages, you won't have this problem.

**Comment by mjsteinbaugh** [comment]
@mojaveazure `dependencies = TRUE` is useful for setting up an R package library from scratch, particularly when building Docker images. I can install with `install.packages("Seurat")` without issue, but wanted to give you a heads up that Seurat currently has issues with this setting.

**Comment by mojaveazure** [comment]
Hi Michael,

Okay, thank you. We currently use SDMTools for some of the interactive visualizations in Seurat, but we may look into re-implementing those routines in Seurat to remove the dependency.

Thanks for bringing this to our attention!

**Comment by hugokitano** [comment]
Hi, I am running into a problem installing Seurat 2.3.4 because of this orphaned dependency. The up to date version of Seurat works, but unfortunately does not run on the codebase I'm trying to use. Any quick workarounds?
