### ISSUE TITLE
Cell identities after clustering

### ISSUE THREAD

**Issue by andrewjkwok** [satijalab/seurat#2378]
Hi,

I ran a 10 sample scRNA-seq experiment with samples hashed, pooled and sequenced together. I demultiplexed with the Seurat HTOdemux function, then tried to do downstream clustering of cells. However, after following the Seurat vignettes, the active identity of my Seurat object seems to be stuck with the sample / hashtag antibody used - how do I manipulate my Seurat object based on the identity of the cells as determined by clustering, rather than the identity of the cells based on which sample they originated from? 

Many thanks.

**Comment by yuhanH** [comment]
Hi,
You can use `Idents(obj)` to change the default active identity.
for example, `Idents(obj) <- obj$celltype`
