### ISSUE TITLE
Accompanying Data Files for Spatial Inference Tutorial Unaccessible

### ISSUE THREAD

**Issue by dburkhardt** [satijalab/seurat#238]
It seems that the permissions to access the files for the Spatial Inference Tutorial <http://satijalab.org/seurat/get_started_v1_2.html> are not set properly. I get a 403 (Forbidden) error when I try to access this link:

http://www.broadinstitute.org/~rahuls/seurat/seurat_files_zfin.zip

Is there anywhere else it is possible to access these files?

**Comment by adomingues** [comment]
I am also running into the same issue. It would nice to have those files to do the zebrafish tutorial.

**Comment by akdess** [comment]
I also have the same issue.

**Comment by andrewwbutler** [comment]
Apologies, the website link has been updated. You can now find these files here:

https://www.dropbox.com/s/ev78jelev0jgu5s/seurat_files_zfin.zip?dl=1
