### ISSUE TITLE
FindConservedMarkers for loop error, can I do with V3?

### ISSUE THREAD

**Issue by stephanyfoster** [satijalab/seurat#2380]
hello,

with Seurat v2 I was able to use a for loop to identify conserved markers per cluster when analyzing a stim vs control integrated dataset. When I try this now, using seurat v3, the output is only one cluster, cluster 0.

I follow Stim v Control vignette and run the following to identify markers:
'''
for (cluster in seq(0,length(unique(A.combined@meta.data$RNA_snn_res.0.5))-1)){
  A.markers <- FindConservedMarkers(A.combined, ident.1 = paste(cluster),grouping.var = "Con", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
  write.table(A.markers,file=paste("./ConservedMarkers/","Cluster_",cluster,"CONSERVED.txt",sep=""),quote=F,sep="\t")
}
''' 

Any suggestions would be much appreciated

**Comment by timoast** [comment]
How many clusters do you have? You should be able to do something like:

```r
all.clusters <- sapply(levels(object), function(x) FindConservedMarkers(object, ident.1 = x, grouping.var = "Con"))
```

**Comment by stephanyfoster** [comment]
Hello,

thank you for the suggestion-- I am doing a timecourse analysis so in the data, the first "Con" may have 4 clusters and the last "Con" 20 clusters. I tried your suggestion and it does run. However, one of the things I wanted to do was create a separate table of markers for each cluster.

A clarification question: Does your suggestion give conserved markers for each level/"Con" as opposed to conserved markers say for cluster 5 across all datasets?

thank you!

**Comment by stephanyfoster** [comment]
I gave up on the for loop and tried without-
I am trying to identify cell type markers for an integrated dataset of 8 conditions. I run the following 
DefaultAssay(Sp.combined) <- "RNA"
Sp0.markers <- FindConservedMarkers(Sp.combined, ident.1 = 0, grouping.var = "Con", verbose = FALSE)

For the clusters I do get an output, it is as little as 2-3 genes. I considered subsetting the integrated dataset to the last condition which for most clusters I expect has the highest cell numbers. I tried two ways and get different values in terms of fold changes and p values.

Sp0.markers <- FindConservedMarkers(subset(Sp.combined, subset= Con=='T8_LG'), ident.1 = 6, grouping.var = "Con", only.pos = TRUE, verbose = FALSE)

T8<-subset(Sp.combined, subset= Con=='T8_LG')
Sp.mark <- FindConservedMarkers(T8, ident.1 = c(6), grouping.var = "Con",only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, verbose = FALSE)

How should I appropriately find markers for cell types with an integrated dataset?

**Comment by satijalab** [comment]
The issue here is that you have 8 conditions. In order for the gene to be tested, it needs to clear the min.pct and logfc.threshold parameters in all 8 conditions, independently. Only a subset of genes are doing this. You should reduce these parameters which will enable more genes to be tested.
