### ISSUE TITLE
further clarification on use of expm1 function within DotPlot function

### ISSUE THREAD

**Issue by davidbmorse** [satijalab/seurat#2381]
Thanks for the great resources Seurat team!

I see in the DotPlot function that avg.exp is taken from log-normalized data which is 'un-log normalized' via the expm1 function.

`avg.exp <- apply( X = data.use, MARGIN = 2, FUN = function(x) { return(mean(x = expm1(x = x))) } )`

Is there a reason why this is done rather than pulling data from the 'counts' slot?
#1045
#1404

**Comment by satijalab** [comment]
The expm1 does un-log the data, but the normalization persists (this would be lost in the counts slot)

**Comment by davidbmorse** [comment]
Ah that makes sense. Thanks so much for the reply.

**Comment by zenghh1226** [comment]
Thanks for the powerful tools invited by Satijalab.
I still wonder why  take un-log data when calculate average expression. Is it both ok to choose un-log or log data to calculate mean expression?Or is it better to choose un-log data and why? I am going to calculate the avg expression for each sample and perform linear regression.
