### ISSUE TITLE
How to make sure the genes that I have regressed out are not included in my object any more?

### ISSUE THREAD

**Issue by myaqubi** [satijalab/seurat#2382]
Hi 

I am wondering how can I make sure the genes that I have regressed out are not included in my object any more? I regressed a group of genes from my object, however, after clustering, heatmap and also differentially expressed gene analysis I still see some of them.

thanks

**Comment by timoast** [comment]
You can remove features from the object using the `subset` function. If you have certain genes that you don't want to use for PCA, you could remove them from the variable features rather than removing them from the object completely.

**Comment by myaqubi** [comment]
Hi Tim

Thanks for your answer.

Actually I have tried that with following code


object <- FindVaribaleFeatures(object, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(object)

object <- ScaleData(object, vars.to.regress = c("genes"), features = all.genes)

object <- RunPCA(object, features = variableFeatures(object))


However, I still see some of the "genes" that I removed in my further analysis.

I would greatly appreciate any advice that you have.

Moein
________________________________

**Comment by timoast** [comment]
At which step above do you remove genes?

**Comment by myaqubi** [comment]
object <- ScaleData(object, vars.to.regress = c("genes"), features = all.genes)

**Comment by timoast** [comment]
Ok, that won't remove the genes from the object, but regresses out the effect of the genes in the scaled data (see [ScaleData](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/ScaleData)).

The code I suggested above (using `subset`) will remove the genes from the object

**Comment by Chenmengpin** [comment]
> Ok, that won't remove the genes from the object, but regresses out the effect of the genes in the scaled data (see [ScaleData](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/ScaleData)).
> 
> The code I suggested above (using `subset`) will remove the genes from the object

Hi, I ran into the same issue, and want to remove several genes in order to get a better clustering results. But I could'nt find a way to remove those gened from  variableFeatures using 'subset' function, could you please give me some advice.  Very appreciate for your help,thanks!

**Comment by timoast** [comment]
You can't remove genes from the variable features using `subset`, `subset` would be used to remove them from the object completely.

To remove them from the variable features you would assign the variable features yourself, for example:

```r
VariableFeatures(object) <- setdiff(VariableFeatures(object), genes.remove)
```

**Comment by Chenmengpin** [comment]
> You can't remove genes from the variable features using `subset`, `subset` would be used to remove them from the object completely.
> 
> To remove them from the variable features you would assign the variable features yourself, for example:
> 
> ```r
> VariableFeatures(object) <- setdiff(VariableFeatures(object), genes.remove)
> ```

Got it, I'll try that later. Thanks for your suggestion.
