### ISSUE TITLE
Analysis of stimulated and unstimulated conditions with paired samples and biological replicates

### ISSUE THREAD

**Issue by achamess** [satijalab/seurat#2384]
I have 10x data from an experiment with the following setup:

<img width="505" alt="Screen Shot 2019-12-03 at 2 52 52 PM" src="https://user-images.githubusercontent.com/7445362/70088918-cd535380-15dc-11ea-8ccc-b4f0e5a8f600.png">

I stimulated 5 animals (n=5) and have 5 unstimulated controls (n=5). From each animal, I took samples from both the left and right part of the brain. 

I now want to analyze this using Seurat. I've looked at the Vignette for stimulated samples using the integrated analysis, but I'm not sure how to deal with the paired samples and also the biological replicates. The comparisons I want to make are indicated by the lines below. I want to (1) cluster them, (2) compare genes between clusters group by condition or side. 

What would be the best way to handle this?

**Comment by timoast** [comment]
Hi , sorry for the delay. I think one way to do this would be to integrate all the samples and perform differential expression between the integrated clusters across stimulated / control. 

For differential expression you would use the original uncorrected data, and include replicate as a covariate (for example, `test.use = "LR", latent.vars = "replicate"`)
