### ISSUE TITLE
about the sets of non-differential genes between the clusters

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2385]
Dear all, 

would you please let me know : shall we have a scRNA-seq with cluster_A and cluster_B of cells, 

if there a (quick) way to get the NON-differential expressed genes between the clusters A and B ?

(i.e. could I set up the FindMarkers in such a way it lists also the NON-differential expressed genes ? ). 

I'd think that a longer process is to extract all the genes associated with clusterA, or with clusterB, and put aside the DEG between clusterA and clusterB .. thank you !

-- bogdan

**Comment by timoast** [comment]
If you find the differentially expressed genes, then all other genes would be non-differentially expressed
