### ISSUE TITLE
address 0x7edcd1898010, cause 'memory not mapped'

### ISSUE THREAD

**Issue by Lobbii** [satijalab/seurat#2386]
when I run the function internetgrateData and there is an error
 *** caught segfault ***
address 0x7edcd1898010, cause 'memory not mapped'

Traceback:
 1: RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names,     mat2_rownames = mat2.names, all_rownames = all.names)
 2: RowMergeSparseMatrices(mat1 = merged.counts, mat2 = ValidateDataForMerge(assay = assays[[i]],     slot = "counts"))
 3: merge.Assay(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],     merge.data = merge.data)
 4: merge(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],     merge.data = merge.data)
 5: merge.Seurat(x = object.list[[1]], y = object.list[2:length(x = object.list)])
 6: merge(x = object.list[[1]], y = object.list[2:length(x = object.list)])
 7: IntegrateData(anchorset = anchors, dims = 1:40)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

I want to know how to solve this question and why?

**Comment by timoast** [comment]
It looks like you're running out of memory, how much RAM do you have and what is the size of the datasets you're integrating? Can you provide your full code and the output of `sessionInfo()`?
