### ISSUE TITLE
local minimum of t-sne

### ISSUE THREAD

**Issue by phoebee-h** [satijalab/seurat#2388]
Hi Seurat team,
Thanks for your good work. I've read some materials about t-SNE clustering these days, and I wonder **how can I deal with the "local minimum"** as mentioned in slide "Do's and Don'ts of using t-SNE to Understand Vision Models" by Laurens van der Maaten, like this:
![image](https://user-images.githubusercontent.com/28743573/70132035-568e8700-16be-11ea-84e3-1cdf85fc3db3.png)

Many have questions about clustering result #2053 #1814 , and basically the answers come to :
1. number of HVGs
2. number of PCs
3. resolution (which does not change the shape of t-SNE but only increase the split cluster number)
4. Louvain to Leiden

Are they all that I can check? What else do you suggest?
Also, I wonder: **is "perplexity = 30" in default Seurat::RunTSNE?**

Thank you in advance.

**Comment by timoast** [comment]
For advice on understanding and tuning tSNE parameters I recommend reading this: https://distill.pub/2016/misread-tsne/

Remember that the tSNE visualization is not what is typically used for clustering. For your questions on clustering, the points you lost are the main parameters to consider in clustering the data. The only other thing I might add is the normalization method used prior to PCA, eg sctransform vs log normalization.
