### ISSUE TITLE
Motivation behind Wilcoxon test in FindMarkers function

### ISSUE THREAD

**Issue by fransilvion** [satijalab/seurat#2391]
Hi,

I am just curious, why non-parametric Wilcoxon rank sum test became a default option for differential expression testing in FindMarkers function?

**Comment by timoast** [comment]
Hi, we found the Wilcoxon test is fast and generally gives good results. See this benchmarking study for a comparison of methods: https://www.nature.com/articles/nmeth.4612, and see here for more discussion of the Wilcoxon test: https://osca.bioconductor.org/marker-gene-detection.html#using-the-wilcoxon-rank-sum-test
