### ISSUE TITLE
RStudio session crashes with FindTransferAnchors() function

### ISSUE THREAD

**Issue by RegnerM2015** [satijalab/seurat#2392]
To whom it may concern,

I am trying to integrate my own scATAC-seq with scRNA-seq using the Seurat v3 workflow found here (https://satijalab.org/seurat/v3.1/atacseq_integration_vignette.html). 

Everything is working fine up until the FindTransferAnchors() function: 

transfer.anchors <- FindTransferAnchors(reference = pbmc.rna, query = pbmc.atac, features = VariableFeatures(object = pbmc.rna),  reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")

Although I was able to successfully run this function using the PBMC tutorial data, running the function on my own data results in **RStudio crashing without error messages.** 

Has anyone experienced this issue? Please let me know if I can clarify anything.

Thanks in advance!
Matt R

**Comment by RegnerM2015** [comment]
Update:

I have looked at the source code for FindTransferAnchors() and I have identified RunCCA() as the culprit. I can run ScaleData on my data (WHIM11) just fine. Running RunCCA() results in a crash. 

 if (reduction == "cca") {
    WHIM11.rna <- ScaleData(object = WHIM11.rna, features = features, 
                           verbose = FALSE)
    WHIM11.atac <- ScaleData(object = WHIM11.atac, features = features, 
                       verbose = FALSE)
    combined.ob <- RunCCA(object1 = WHIM11.rna, object2 = WHIM11.atac), 
                          features = features, num.cc = max(dims), renormalize = T, 
                          rescale = FALSE, verbose = TRUE)
  }

**Comment by timoast** [comment]
What is the size of the two objects you're integrating, and how many features are you using for the integration? Can you provide the full code that you're using, and the output of `sessionInfo()`?

**Comment by RegnerM2015** [comment]
I was actually able to resolve this crashing issue!

The gene list in the scATAC object had standard gene names while the gene list in the scRNA-seq object had the GRCh38- prefix.

This difference in notation caused the crash. I removed the GRCh38- prefix and it ran without issues!

Thanks,

Matt Regner
Biological & Biomedical Sciences Program (BBSP)
regnerm@live.unc.edu
________________________________
