### ISSUE TITLE
availability of the datasets (SeuratData)

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2393]
Dear all, 

please would you advise, as I am following the tutorial on ReciprocalPCA : 
https://satijalab.org/seurat/v3.1/integration.html

where can I find these datasets : 

-- **bm40k.SeuratData**

_when i do InstallData(pkgs = "bm40k.SeuratData"), it says : 
Error in NameToPackage(ds = ds) : 
  argument "ds" is missing, with no default_

-- and **"ica_bone_marrow_h5.h5"**

(in order to read it into _"bm280k.data <- Read10X_h5("ica_bone_marrow_h5.h5"_) 

Thanks a lot ! with much appreciation, 

bogdan

**Comment by timoast** [comment]
`pkgs` is not an argument for the `InstallData` function, as stated in the error message

The HCA bone marrow data can be found here: https://data.humancellatlas.org/explore/projects/cc95ff89-2e68-4a08-a234-480eca21ce79

**Comment by LieselWong** [comment]
I'm still having trouble findind the ica_bone_marrow_h5.h5 dataset, what specifically do you download??
