### ISSUE TITLE
cca/cca.l2 in the integrated object

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#2396]
Dear Seruat Team,

I wonder if I could retrieve cca or cca.l2 reduction slots in the final output object after integration.

Thanks!

**Comment by timoast** [comment]
Hi, this is not stored in the output. You can compute CCA using the [`RunCCA`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/RunCCA) function, and apply the L2 norm using [`L2Dim`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/L2Dim)
