### ISSUE TITLE
Error installing Seurat!

### ISSUE THREAD

**Issue by imandehzangi** [satijalab/seurat#2398]
Hi, 
I am trying to install Seurat on Ubuntu 18.04 (R version 3.6.1). Yet, I keep receiving the following error:

ERROR: configuration failed for package ‘openssl’
* removing ‘/home/iman/R/x86_64-pc-linux-gnu-library/3.6/openssl’
ERROR: dependencies ‘curl’, ‘openssl’ are not available for package ‘httr’
* removing ‘/home/iman/R/x86_64-pc-linux-gnu-library/3.6/httr’
ERROR: dependency ‘httr’ is not available for package ‘plotly’
* removing ‘/home/iman/R/x86_64-pc-linux-gnu-library/3.6/plotly’
ERROR: dependencies ‘httr’, ‘plotly’ are not available for package ‘Seurat’
* removing ‘/home/iman/R/x86_64-pc-linux-gnu-library/3.6/Seurat’

Could you help me solve it, please?
Thanks

**Comment by timoast** [comment]
It looks like you’re having issues installing a Seurat dependency, openssl, rather than Seurat itself. I suggest you raise the issue with openssl

**Comment by imandehzangi** [comment]
Thanks for your prompt response! 
I will try that.
