### ISSUE TITLE
Error using FindMarkers

### ISSUE THREAD

**Issue by mplass** [satijalab/seurat#24]
Hi,
if I try to use the negative binomial test in the function FindAllMarkers it crashes. 

**Example:**
all.markers <- FindAllMarkers(nbt, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25,test.use = "negbinom")
   |                                                  | 0 % ~calculating  Error in while ((it <- it + 1) < limit && abs(del) > eps) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In `[<-.data.frame`(`*tmp*`, , "GENE", value = list(plan2_AAGCAGATTAAA = 2,  :
  provided 9930 variables to replace 1 variables

Thanks,

**Comment by dhb2128** [comment]
I also just got the same error:
"FindMarkers"
Error in while ((it <- it + 1) < limit && abs(del) > eps) { :
  missing value where TRUE/FALSE needed
Calls: FindMarkers ... lapply -> FUN -> summary -> glm.nb -> as.vector -> theta.ml
In addition: Warning message:
In `[<-.data.frame`(`*tmp*`, , "GENE", value = list(DS11TCCTTATTTCAG = 6L,  :
  provided 6207 variables to replace 1 variables

**Comment by satijalab** [comment]
If you could provide some sample data that recreates this error or the object itself, that would be helpful. Can't seem to reproduce it on the datasets I have.

**Comment by andrewwbutler** [comment]
Resolved the bug. Reinstalling should allow you to run any of the marker detection functions with the "negbinom" test without problems.
