### ISSUE TITLE
Marking individual cells on a tSNE plot

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#240]
Hi,

I want to mark specific cells with the use of their unique barcodes. Is there a way in Seurat to do this probably in a way we plot genes in Featureplot?

Thanks,

Bibaswan

**Comment by satijalab** [comment]
This is a good idea - we don't support this as of yet but will do so in a future release.

At the moment, the best solution would be to use SetIdent to give these cells a unique identity, so they will be marked on the plot.

**Comment by ghoshal** [comment]
Thanks. It will be great to have this function in the development version.

If I use SetIdent for these cells, then how do I overlay them on the TSNE plot?

**Comment by ghoshal** [comment]
The SetIdent works great with Dimplot and TSNEplot. Thanks
