### ISSUE TITLE
FeaturePlot color scale legend with custom colors

### ISSUE THREAD

**Issue by AidanQuinn** [satijalab/seurat#2400]
Hi satijalab,

I've noticed unexpected behavior when I plot metadata in Seurat3 using FeaturePlot. Specifically, I have a metadata slot called "VIPER_Activity" which contains continuous data in the range approximately (-2.5, +2.5). When I plot these data with FeaturePlot without specifying the color:

`FeaturePlot(data, features = "VIPER_Activity")`

I get the expected output which has a color scale (-2.5, +2.5). If I use custom colors, though the color scale seems to take the index-value of the color array it is contained in:

`FeaturePlot(data, features = "VIPER_Activity", cols = rev(brewer.pal(n = 11, name = "RdBu")))`

I've solved this issue by using ggplot directly on the data, but seems to me like it's not the desired behavior by your function.

Thanks for your great work on this package - it's super useful and clean!

**Comment by andrewwbutler** [comment]
Hi @AidanQuinn ,

Sorry if the `cols` parameter is a bit unclear as it tries to handle a lot of cases (specifically w.r.t to the blend functionality). If you want a continuous gradient scale like that, you can provide the colors corresponding to the min and max and it will create the scale based off those. E.g.

```R
FeaturePlot(pbmc_small, "LYZ", cols = c("red", "blue"))
```

However, a solution probably closer to what you want with `RdBu` would be to add the continuous color scale as you would for any ggplot object. E.g.

```R
FeaturePlot(pbmc_small, "LYZ") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
```

**Comment by AidanQuinn** [comment]
> Hi @AidanQuinn ,
> 
> Sorry if the `cols` parameter is a bit unclear as it tries to handle a lot of cases (specifically w.r.t the blend functionality). If you want a continuous gradient scale like that, you can provide the colors corresponding to the min and max and it will create the scale based off those. E.g.
> 
> ```r
> FeaturePlot(pbmc_small, "LYZ", cols = c("red", "blue"))
> ```
> 
> However, a solution probably closer to what you want with `RdBu` would be to add the continuous color scale as you would for any ggplot object. E.g.
> 
> ```r
> FeaturePlot(pbmc_small, "LYZ") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
> ```

Yeap, that's more or less what I did. Totally makes sense why it's happening, just an unexpected behavior from my end. Thanks!

**Comment by christianholland** [comment]
Hi @andrewwbutler 

your proposed workaround works nicely if a **single feature** is plotted. However, when adding a list/vector of **various features** the function `scale_color_gradient()` just changes the color of the **last plot**. I guess this is due to the usage of `patchwork`. Any idea how to change the color scale for all plots within the plot arrangement?

Thanks for developing Seurat and best wishes,
Christian

**Comment by andrewwbutler** [comment]
Hi @christianholland ,

If you want to apply the scale to all the plots, you need to use the `&` operator instead. E.g.
```R
FeaturePlot(pbmc_small, c("LYZ", "MS4A1")) & 
  scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
```

This was actually one of the reasons we switched to patchwork was being able to easily add themes/scales/etc to these kind of composite ggplot objects. For more details on this topic, please see the [patchwork docs](https://patchwork.data-imaginist.com/articles/guides/assembly.html) (particularly the "Modifying everything" section here).

**Comment by christianholland** [comment]
Great, thanks for pointing to this feature of `patchwork`

**Comment by gabrielnegreira** [comment]
> Hi @christianholland ,
> 
> If you want to apply the scale to all the plots, you need to use the `&` operator instead. E.g.
> 
> ```r
> FeaturePlot(pbmc_small, c("LYZ", "MS4A1")) & 
>   scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu")))
> ```
> 
> This was actually one of the reasons we switched to patchwork was being able to easily add themes/scales/etc to these kind of composite ggplot objects. For more details on this topic, please see the [patchwork docs](https://patchwork.data-imaginist.com/articles/guides/assembly.html) (particularly the "Modifying everything" section here).

Hi, sorry to revive an old thread but I am having a small problem when I try to create a plot with a custom color scale. I am doing a plot with 4 samples in a seurat object using FeaturePlot() with the argument "split.by" set to "sample". I want the color scale for the feature I'm plotting to have the same range across the 4 samples. I understand this is the standard behavior of the FeaturePlot() function as the keep.scale argument is by default set to "feature". However, if I add a custom color scale using &scale_colour_gradientn(), then each plot has its own scale range, making comparisons between samples not feasible. If the &scale_colour_gradientn() is not included, then the color range is the same across samples, so I think the scale_colour_gradientn() function overwrites the keep.scale argument from FeaturePlot(). Is there a way to fix this?

The code that returns a plot with the same scale range across samples is:

```
FeaturePlot(seuratObj, feature, keep.scale = "feature", split.by = "sample")
```

While the code that returns a plot with each sample having its own color scale range is:

```
FeaturePlot(seuratObj, feature, keep.scale = "feature", split.by = "sample")&
  scale_color_gradientn(colors = my_pallete)
```

Thanks for any suggestions!
