### ISSUE TITLE
How to set a group of HTO signal?

### ISSUE THREAD

**Issue by josh4ever** [satijalab/seurat#2401]
Hi Seurat team,

I need to make a group of hto signals so that I can make a tsne plot by group (same color).

Could you please help me to do that?

group A: hto_1,hto,5,hto6
group B: hto_3,hto_7

**Comment by timoast** [comment]
There are several ways to do this, see the [RenameIdents](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/Idents) function for example. Another option:

```r
obj$group <- ifelse(obj$hto %in% c("hto_1", "hto_5", "hto_6"), "A", "B")
```
