### ISSUE TITLE
MAST DE Error

### ISSUE THREAD

**Issue by ondp15** [satijalab/seurat#2403]
Hello,

I need you advice on running DE using MAST. 
I've installed separately MAST using the following command 

`install.packages("BiocManager")` # Needed to install all Bioconductor packages
`BiocManager::install("MAST")`

Then loaded the libraries: 

`library(scater)
library(MAST)
library(Seurat)` *Seurat was already installed previously. 

and ran this code:

`DEMAST <- FindMarkers(cells, ident.1 = "2", ident.2 = "12", test.use = "MAST")`

and obtain this:

`Error in sanity_check_sca(obj) : Assay in position 1, with name et is unlogged. Set check_sanity = FALSE to override and then proceed with caution.`

Of note, I've already visited issues #2346 and #2345 and added assay = "RNA" and still obtain the error above. I think it may be that I am not pulling out which variables to use for testing? Any advice is more than welcome.

R 3.6.1
MAST version 1.10.0

Thanks for your help!

**Comment by weihuaguo** [comment]
What I did is changing the default assay to RNA:
DefaultAssay(srsc) = "RNA"
You can try this before your DE analysis.
Thanks!

Best,
Weihua

**Comment by weihuaguo** [comment]
I encountered this issue again. Is there anyone can help on this? Thanks a lot!

**Comment by yuhanH** [comment]
One suggestion is update the MAST. The current version is 1.12.0. 
If still not work, can you send an object as an example? i cannot reproduce this error. 
Thanks

**Comment by happar73** [comment]
I updated the "MAST" and set DefaultAssay( object) <- "RNA", but it still doesn't work. 

Is there any other solutions?

Thanks,
Yale

**Comment by yuhanH** [comment]
is your data in the RNA assay log-normalized?

**Comment by happar73** [comment]
Thanks. I used the "RC" normalization and the data is not log-normalized. After I normalized the data, it works.

Thanks again!
Yale
