### ISSUE TITLE
Using Seurat with Small Subsetted Dataset

### ISSUE THREAD

**Issue by willmonty14** [satijalab/seurat#2404]
Dear Seurat Team, 
I've been using Seurat for about six months now and consider myself okay at using the program, but one big problem that I keep running into is how Seurat handles smaller datasets. In my work I usually start off with a larger dataset of immune cells and then subset out the T cells after clustering, leaving me with much fewer cells than most Seurat datasets used in examples (sometimes as low as 200-500 cells). When I attempt to run UMAP and clustering on these cells though, my UMAPS always end up looking very poor, with no real discernible clusters (I have tried playing with min.dist and spread to no avail). Is Seurat just not meant to handle datasets this small? Is there anything that I can do to improve my clustering? Thank you very much for your time, and have a nice day.

**Comment by timoast** [comment]
Hi, you could try re-defining variable genes and running PCA on your subsetted data, that might pick up on more of the variation within the subset. Alternatively you could keep the original embedding from the full dataset.
