### ISSUE TITLE
CellCycleScoring: using own list of genes

### ISSUE THREAD

**Issue by whelena** [satijalab/seurat#2405]
I am trying to classify my cells into it's phases and the list provided by satija lab does not properly do that (maybe due to some cell type-specific expression). I was wondering if I can plug my own list of genes into CellCycleScoring.

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but hopefully this helps.  `CellCycleScoring` passes the information supplied to the `AddModuleScore` command.  So you can use your own gene lists with AddModuleScore.  

See the manual pages for `CellCycleScoring` and `AddModuleScore` for more info.

Best,
Sam

**Comment by whelena** [comment]
Thank you Sam!
