### ISSUE TITLE
Seurat Saved Clustering Parameters

### ISSUE THREAD

**Issue by subkhankul** [satijalab/seurat#2407]
Previously SeuratV2 had an option to save clustering parameters and recall them -PrintFindClustersParams(object). 
Now  in Seurat3 I've tried to find  PCA dimensions which have been used to cluster cells within my object,  with the commands:
object$FindClusters (works fine) and
object$FindNeighbors  or object$FindNeighbors. The error occurs:

Error in `[[.Seurat`(x, i, drop = TRUE) : 
 Cannot find 'FindNeighbors' in this Seurat object.

What is wrong? Is the information about dims used still stored somewhere in the object?

Many thank in advance, 
Tatiana

**Comment by timoast** [comment]
You need to pass the assay and reduction used in the FindNeighbors call. You can see the names of all the commands stored in the object by running `Command(object)`. For example, if `FindNeighbors` was run on the RNA assay with PCA dimension reduction, you can retrieve the parameters by running `object$FindNeighbors.RNA.pca`

**Comment by subkhankul** [comment]
Thank you very much, Tim

________________________________
