### ISSUE TITLE
DimPlot error: Error: Must request at least one colour from a hue palette.

### ISSUE THREAD

**Issue by liuweihanty** [satijalab/seurat#2408]
Hi there, I was trying to plot the UMAP based on my assigned identity, but this error keeps throwing up: Must request at least one colour from a hue palette.. Here is my code, I basically just created a new column final.ident in the metadata table which store the cell's name based on 
clusters returned by RNA_snn_res.0.7:

kon1 <- FindClusters(object = kon1, resolution = 0.7)
# Look at cluster IDs of the first 5 cells
head(x = Idents(object = kon1), 5)

#plot kon1
kon1@meta.data <- kon1@meta.data %>% mutate(final.ident = NA)

for (i in 1:nrow(kon1@meta.data)) {
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 0) {
                kon1@meta.data$final.ident[i] <- "Monocyte"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 1) {
                kon1@meta.data$final.ident[i] <- "Neutrophil"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 2) {
                kon1@meta.data$final.ident[i] <- "HSC"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 3) {
                kon1@meta.data$final.ident[i] <- "Neutrophil"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 4) {
                kon1@meta.data$final.ident[i] <- "B"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 5) {
                kon1@meta.data$final.ident[i] <- "Monocyte"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 6) {
                kon1@meta.data$final.ident[i] <- "Neutrophil"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 7) {
                kon1@meta.data$final.ident[i] <- "Neutrophil"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 8) {
                kon1@meta.data$final.ident[i] <- "Megakaryocyte"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 9) {
                kon1@meta.data$final.ident[i] <- "Erythrocyte"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 10) {
                kon1@meta.data$final.ident[i] <- "Basophil"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 11) {
                kon1@meta.data$final.ident[i] <- "B"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 12) {
                kon1@meta.data$final.ident[i] <- "B"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 13) {
                kon1@meta.data$final.ident[i] <- "Erythrocyte"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 14) {
                kon1@meta.data$final.ident[i] <- "Neutrophil"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 15) {
                kon1@meta.data$final.ident[i] <- "DC"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 16) {
                kon1@meta.data$final.ident[i] <- "Monocyte"
        }
        if (kon1@meta.data$RNA_snn_res.0.7[i] == 17) {
                kon1@meta.data$final.ident[i] <- "Erythrocyte"
        }
}

Idents(kon1) <- "final.ident"
DimPlot(kon1, reduction = "umap")

**Comment by timoast** [comment]
Please see the [RenameIdents](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/Idents) function for information about renaming identities.

**Comment by Avaptel18** [comment]
I am also having the same error. I just added one extra column with dplyr::left_join ("cell_label") into metadata of Seurat object and I can't plot UMAP with Dimplot any more, it gives me the same error. 
@liuweihanty how did you solve the error? Thanks!

**Comment by Moloch0** [comment]
I encountered the error and fixed that by checking `"NA"` value in `idents`

**Comment by mtdinc** [comment]
> I am also having the same error. I just added one extra column with dplyr::left_join ("cell_label") into metadata of Seurat object and I can't plot UMAP with Dimplot any more, it gives me the same error.
> @liuweihanty how did you solve the error? Thanks!

The left_join function eliminates the row names from Seurat's metadata. I'm not sure if there's an easier way, but this is what I do: I store the row names in a separate vector. After I use left_join, I add the row names to the Seurat object's metadata. This fixes the problem.

**Comment by boolean-jiang** [comment]
> > I am also having the same error. I just added one extra column with dplyr::left_join ("cell_label") into metadata of Seurat object and I can't plot UMAP with Dimplot any more, it gives me the same error.
> > @liuweihanty how did you solve the error? Thanks!
> 
> The left_join function eliminates the row names from Seurat's metadata. I'm not sure if there's an easier way, but this is what I do: I store the row names in a separate vector. After I use left_join, I add the row names to the Seurat object's metadata. This fixes the problem.

@AayushiNotra I will second this advice as I had the same issue. Check to make sure that your Seurat metadata object hasn't somehow lost its row names - in particular, `row.names(seurat_object@meta.data)` should return a vector of barcode identifiers, NOT just plain index numbers like 1, 2, 3, 4... In my case, after some metadata merges, my object ended up with a column called "Row.names" that stored this information - so I simply ran `row.names(seurat_object@meta.data) <- seurat_object@meta.data$Row.names` and this helped me fix my `DimPlot()` bugs. 

I hope this helps - if not, I'll try to investigate further and see if there are additional potential causes!

**Comment by Silvia-pigeon** [comment]
You should check the row names. I have the same error when the row names are incorrect

**Comment by Silvia-pigeon** [comment]
You should check the row names. I have the same error when the row names are incorrect
