### ISSUE TITLE
Seurat fails to install from CRAN

### ISSUE THREAD

**Issue by tmtabor** [satijalab/seurat#2409]
I have attempted to install Seurat from CRAN using your instructions and receive an error.

> \> install.packages('Seurat')
> installation of package ‘Seurat’ had non-zero exit status

I believe this error is caused by your dependency on the `metap` package. That package depends on `mutoss` which itself depends on `multtest`, which has been removed from CRAN. So when you try to do a fresh install of Seurat, it fails to find all the dependencies in the dependency tree.

I can get around this issue by first installing `multtest` from Bioconductor then installing Seurat:

> BiocManager::install('multtest')
> install.packages('Seurat')

**Comment by MLKaufman** [comment]
Can confirm this started happening.
Installing multtest via BiocManager works. Thanks for the tip.

**Comment by mojaveazure** [comment]
Hi Thorin,

Thank you for letting us know. The next version of Seurat will be configured to install Bioconductor dependencies automatically. Until then, configuring R to check Bioconductor repositories will allow `install.packages` to work without first using BiocManager

```R
# Tell R to use both CRAN and Bioconductor repositories when installing packages
setRepositories(ind = 1:2)
```

**Comment by Chenghao8686** [comment]
Thanks so much, my issue is fixed.

This works.
