### ISSUE TITLE
100% Cluster Representation From a Single Sample

### ISSUE THREAD

**Issue by basilkhuder** [satijalab/seurat#2411]
We are running our analysis with multiple samples, and using the sctransform wrapper of Seurat. For quality control, we first use `PercentageFeatureSet` on the sample for MT genes, and then set three cutoff values that are based on the quantile of MT % present and nFeature_RNAs. For example:

```
low_mito_cutoff <- quantile(sample1$percent.mt, probs = 0.025)
high_mito_cutoff <- quantile(sample1$percent.mt, probs = 0.975)
feature.cutoff <- quantile(sample1$nFeature_RNA, probs = 0.975)
```
We then subset each sample where nFeature is less than our feature cutoff, percent.mt is greater than our low cutoff and less than our high cutoff. We then merge samples, and carry on with the rest of the analysis.  This has worked well for past experiments, but we are dealing with a situation where one cluster's composition is made up entirely of a single sample.  Furthermore, this cluster has a significantly low mitochondrial percentage. 

My concern is that there may not be an ideal cutoff value, which would require us to manually adjust our cutoffs per experiment (which is potentially adding bias to our analysis.)  

Any help would be appreciative!

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but hope this is helpful.  You may be better off asking this question on more focused bioinformatics forum.  Github is mainly for errors or issues with the software package itself and less the underlying principles of the analysis.  You could try biostars or bioinformatics stack exchange as a start.

Best,
Sam

**Comment by timoast** [comment]
I agree with Sam, we can't really advise on how to interpret experiments. There is certainly no set cutoff value for different QC metrics, and the "best" value to use might change across experiments.
