### ISSUE TITLE
AverageExpression value after sctransform

### ISSUE THREAD

**Issue by MonkeySylvia** [satijalab/seurat#2413]
Hi,
I have a dataset which contains 2 sequencing batches, and I want to correct the batch effect. I used the sctransform(SCTransform, PrepSCTIntegration) to normalize the data and then integrated the datasets (FindIntegrationAnchors, IntegrateData). Everything works perfectly, and then I want to compare the expression value of my interested genes between clusters.
When I ran the standard Seurat workflow, I used "AverageExpression" to get the normalized count (Counts per 10000 reads) for each cluster, then I can compare my genes between clusters.
But after sctransform, the values (AverageExpression$SCT) is scaled, and I can't get the counts per 10000 reads anymore.
I wonder if there is a better way to do the comparison between clusters, or there is a hidden function that I didnt know about.

Many thanks!
Sylvia

**Comment by satijalab** [comment]
Thanks, and sorry that this is a tricky issue.

You can run AverageExpression on SCTransform normalized objects, and it should work fine.

However, you cannot run AverageExpression on an *integrated* assay after SCTransform normalization. This is not a bug, but is one of the limitations of the workflow - it requires working with scaled values, and after integration they cannot be transformed back to counts.

So you should run AverageExpression on the data from your original objects, prior to integration
