### ISSUE TITLE
SCTransform clip.range inconsistency

### ISSUE THREAD

**Issue by DanieleBarreca** [satijalab/seurat#2414]
I have a question related to SCTransform-ed data. It seems to me that there are two inconsistent clipping ranges for the Pearson residuals:

1. The first range is passed to the sctransform::vst function (line 1249 of preprocessing.R) which defaults to sqrt(N) if not explicitly set
`res.clip.range <- vst.args[['res_clip_range']] %||% c(-sqrt(x = ncol(x = umi)), sqrt(x = ncol(x = umi)))`

2. The second range is the range used in the SCTransform function in Seurat (lines 1325,1326) which defaults to sqrt(N)/30 if not explicitly set
` scale.data[scale.data < clip.range[1]] <- clip.range[1]`
  `scale.data[scale.data > clip.range[2]] <- clip.range[2]`

This leads to an inconsistency in the variance-mean reltionship when using the defaults. The question is whether there is a need to perform this double clipping (once in the sctransform::vst function and once in the SCTransform function) and in case yes why there are two different default values used in vst vs SCTransform. 

### Variance calculated from the scale.data slot of the SCT assay with standard parameters
![image](https://user-images.githubusercontent.com/7959223/70711488-f6ad6700-1ce1-11ea-8aa1-76b5a4b8f7c3.png)

### Variance Plot generated with PlotVariableFeatures (which uses the results of vst)
![image](https://user-images.githubusercontent.com/7959223/70711664-5441b380-1ce2-11ea-90a7-eb87a9ce3565.png)

### Variance calculated from the scale.data slot of the SCT assay with `clip.range=c(-Inf,Inf)`
![image](https://user-images.githubusercontent.com/7959223/70711836-ab478880-1ce2-11ea-900e-1d0a0f01e318.png)

**Comment by yuhanH** [comment]
HI, 
You are right. There are actually two clip ranges. 
 If we don’t clip at all, outlier counts can have a huge effect and residual variance can become very large for some genes, usually genes with few non-zero observations. This was the reason to introduce the 1st level of clipping which is +-sqrt(number.of.cells).

We later observed that it can be beneficial to even further reduce the range when we use the residuals as input to PCA - this is where the 2nd level of clipping comes in at +-sqrt(number.of.cells/30)

**Comment by satijalab** [comment]
Thanks for the careful review, and I agree this is a tricky question.

As you have observed, the reason we clip the residuals, is to prevent the potential influence of any one value. This can dramatically increase robustness to outliers. However, if we clip too much, it can mask the appearance of rare populations as well (which appear to be outliers).

How much to clip is an empirical determination. When originally writing vst, we used a simple default of sqrt(N). As we tested more datasets in Seurat, we felt it was helpful to impose a more stringent cutoff.

[PS - I just saw Yuhan respond above, and you can see that we have the same response]
