### ISSUE TITLE
create a seurat 3 subset based on a specific gene list?

### ISSUE THREAD

**Issue by LIUMENG004** [satijalab/seurat#2415]
i have a seurat object with 100,000cells and 33000 features. Also, i have a gene list contained 1500 metabolic genes. Can i create a seurat subset with only these 1500 genes?

**Comment by timoast** [comment]
Please see the [subset](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/%5B.Seurat) function

**Comment by stephanyfoster** [comment]
Can I use subset to look at cells that express three particular markers? Or will it pull cells that do express any one or two of the markers on my short list as well?
