### ISSUE TITLE
Unable to retrieve specific genes such as CD14 when plotting dotplot and heatmap

### ISSUE THREAD

**Issue by classycammy** [satijalab/seurat#2418]
Hi,
I have difficulty finding certain genes such as CD14 in my data set. When I performed PCA, CD14 was identified as the variable gene (see attached). However, Dot plot and Heatmap failed to pick up genes including CD14 within the dataset. Could you please advise? Thank you very much.
![PCA_PC3-4_mc6g400](https://user-images.githubusercontent.com/4042691/70761781-86b2e580-1da2-11ea-9b69-dd767fec53af.png)

```
> DotPlot(mel, features = rev(kazi.markers), cols = c("blue", "red"), dot.scale = 8) + RotatedAxis()
Warning message:
In FetchData(object = object, vars = features) :
  The following requested variables were not found: cD14, cD68
> DoHeatmap(subset(mel, downsample = 100), features = markers.to.plot, size = 3)
Warning message:
In DoHeatmap(subset(mel, downsample = 100), features = markers.to.plot,  :
  The following features were omitted as they were not found in the scale.data slot for the RNA assay: cD14, cD68
```

**Comment by timoast** [comment]
Is that gene present in the object? What happens if you run:

```r
setdiff(kazi.markers, colnames(mel))
```

**Comment by classycammy** [comment]
Thanks very much for the prompt response. Deeply appreciate it. I have attempted your suggestion, and after running it, those genes (e.g. CD14) are present in the object. May I know what is the best approach for this issue? CD16 and CD68 are our genes of interests.

Notably, I noticed that the small letter 'c' for cD68 and cD14. I also attempted to change to lower case and it still did not work. Any advise will be much appreciated.

```
> setdiff(kazi.markers, colnames(mel))
[1] "cD68"   "cD14"   "FCGR3A" "CD4"    "CD8A"   "CXCL9"  "CXCL10" "CXCL11"
```

**Comment by timoast** [comment]
Those genes are not in the object, as you can see by the output of `setdiff`. My guess is that you have `CD14` in the object and `cD14` in the list of markers. You just need to change the gene list. You can make them all uppercase by doing `kazi.markers <- toupper(kazi.markers)`

**Comment by classycammy** [comment]
Thank you so much, Tim. It works. It's good to know that they are capital sensitive.
