### ISSUE TITLE
AddModuleScore adds "1" to the name of the module

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#2419]
I have noticed that when using `AddModuleScore` the `name` parameter is not conserved, and is renames as `name1`.
```
cd_features <- list(c(
  'CD79B',
  'CD247'
))
pbmc_small <- AddModuleScore(
  object = pbmc_small,
  features = cd_features,
  ctrl = 5,
  name = 'CD_Features'
)
colnames(pbmc_small@meta.data[,8, drop=F])
#[1] "CD_Features1"
```

**Comment by mojaveazure** [comment]
This is the expected behavior of `AddModuleScore`; for each grouping of features, we append the group number to `name` so that you can find the specific group in object metadata later on.

**Comment by vertesy** [comment]
See: [a fix](https://github.com/satijalab/seurat/issues/2559#issuecomment-611437066)
