### ISSUE TITLE
FindClusters error: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by kwhuang88** [satijalab/seurat#242]
I tried to run FindClusters on a large dataset (~50K cells, object size ~9.2 Gb) and got the following error messages after the function tries to read the input file:

```R
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> 	at ModularityOptimizer.readInputFile(ModularityOptimizer.java:211)
> 	at ModularityOptimizer.main(ModularityOptimizer.java:74)
> Error in file(file, "rt") : cannot open the connection
> In addition: Warning message:
> In file(file, "rt") :
>   cannot open file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/output_16288.txt': No such file or directory
```

The edge_\*.txt files are generated, but not the output_\*.txt files.

I also tried `options(java.parameters = "-Xmx32g")` before loading the libraries and re-running it (this machine has 64 GB total), but still received the same errors. The function runs normally with smaller objects of < 30K cells.

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Thanks!

**Comment by bioryguy** [comment]
There may be a better solution than this, but I received a similar error at one point and I was able to work around it by allocating more memory to R using:
`memory.limit(#)`
The # being the amount of memory you wish to allocate in Mb.

**Comment by satijalab** [comment]
This is an older issue (apologies for the slow reply), but we have made a number of improvements in speed and memory management since this was posted, and have additional significant improvements still to come. you should be able to run clustering of ~50k cells on a personal machine (we do this routinely on a 16GB machine).
