### ISSUE TITLE
Problem with disaasociation genes 

### ISSUE THREAD

**Issue by beginner984** [satijalab/seurat#2420]
Hi

I have faced confusion about regressing out genes related to tissue disassociation.

I have regressed out a list of such a list in my data but again some of them like CXCL1 is being highly differentially expressed exclusively to one cluster of cells. Does this mean that CXCL1 expressing due to biology rather than artefact coming from experimental procedures? This is feature plot of CXCL1

![CXCL1](https://user-images.githubusercontent.com/43682980/70791460-1189e500-1d8f-11ea-885d-96cb5e19f63c.png)

**Comment by timoast** [comment]
The regression in ScaleData won't change the expression values for the features that you regress. See the [ScaleData](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/ScaleData) function for documentation.
