### ISSUE TITLE
How to calculate and store feature.loadings.projected in PCA reduction?

### ISSUE THREAD

**Issue by singletrips** [satijalab/seurat#2422]
![34C4BEC5-7C7C-49F6-90A6-FCBE9258A885](https://user-images.githubusercontent.com/31929730/70810301-86f6b500-1d91-11ea-9d3f-352000424490.png)

**Comment by timoast** [comment]
See the [ProjectDim](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/ProjectDim) function

**Comment by singletrips** [comment]
Thanks for your prompt help.
