### ISSUE TITLE
AverageExpression vs FindMarkers: difference in the avg_logFC

### ISSUE THREAD

**Issue by JulieDBNYC** [satijalab/seurat#2423]
Hello
I am trying to have the differential expressed genes after integrated 2 datasets.
I did the Average Expression to obtain the scatter plots then I used FindMarkers to find the genes that are different and also to have the p values. But I don't find the same avg_expression value and also not the same genes. I have very basic knowledge with R so I am not able to see where I made a mistake.

```r
CD14.mono <- subset(pool.combined, idents = c("3", "5"))
Idents(CD14.mono) <- "week6.combined"
avg.CD14.mono <- log1p(AverageExpression(CD14.mono, verbose = FALSE)$RNA)
avg.CD14.mono$gene <- rownames(avg.CD14.mono)

pool.combined$celltype.Week6 <- paste(Idents(pool.combined), pool.combined$week6.combined, sep = "_")
pool.combined$celltype <- Idents(pool.combined)
Idents(pool.combined) <- "celltype.Week6"
CD14.response <- FindMarkers(pool.combined, ident.1 = c("3_Baseline","5_Baseline"), ident.2 = c("3_Week6","5_Week6"), verbose = FALSE)
```

i.e. for FOS gene: avg_logFC = 3.36 and 2.23 with AverageExpression, avg_logFC = 0.064 with FindMarkers (pcts > 0.5). I checked with the dotplots and this gene is supposed to be high expressed.

I tried to change the test method and the logFC threshold but I have the same problem.
I attached the full script I used for the integration.
Thank you for you help!
[poolAnalysis.docx](https://github.com/satijalab/seurat/files/3961711/poolAnalysis.docx)

**Comment by timoast** [comment]
Hi, sorry for the delay. You script looks fine but I don't quite understand the issue. 

> i.e. for FOS gene: avg_logFC = 3.36 and 2.23 with AverageExpression, avg_logFC = 0.064 with FindMarkers (pcts > 0.5)

What are you trying to compare here?

One thing I would suggest is that you make sure you're computing differential expression on the original expression values, not the integrated values

**Comment by JulieDBNYC** [comment]
Hi, Thank you for your answer!
But yes indeed I figured out that I was using the integrated value instead of the original ones!
