### ISSUE TITLE
ADT normalization across libraries

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#2425]
The default RNA normalization is per cell, but the ADT normalization is per feature. Thus, adding or removing cells does not impact the normalized RNA values, but it does for ADT values. If you have multiple libraries, would it make more sense to normalize all cells together or each library independently? Since the sequencing depth (and other variables) can vary between libraries, is it even reasonable to normalize by feature if that is the case?

**Comment by timoast** [comment]
Yes that is a reasonable approach. We don't have an option for this in `NormalizeData` currently, but you could normalize each object separately and then merge them

**Comment by yuhanH** [comment]
Hi, igor
You are right. You need to normalize ADT per library, and merge them. If there are strong batch effects, you can use the integration method to eliminate the batch effects on ADT data.

**Comment by Lesdormis** [comment]
Hi yuhan, @yuhanH 
Sorry to add on this closed issue.
But could you tell me a little more in detail how to eliminate the batch effects on ADT data? 
I am currently having this strong issue, but not sure how to remove it.

Thanks!
