### ISSUE TITLE
nCount_SCT weird distribution

### ISSUE THREAD

**Issue by MajoroMask** [satijalab/seurat#2427]
Hello folks. I been using Seurat lately to analysis my 10x LUAD data. As far as I know the `nCount_SCT` column in Seurat object's `meta.data` slot represents the sum-up of each genes' UMI in one cell, and I should expect them follow normal distribution. But my data looks like this:

```
srt %>% class()
#: [1] "Seurat"
#: attr(,"package")
#: [1] "Seurat"

srt %>% GetAssayData(assay = "RNA") %>% class()
#: [1] "dgCMatrix"
#: attr(,"package")
#: [1] "Matrix"

p4 <-
  srt[[]] %>%
  ggplot(aes(nCount_SCT)) +
  geom_density(size = 2, linetype = 2, color = "gray80") +
  geom_density(aes(color = stage))
p4
```
![test](https://user-images.githubusercontent.com/19700954/70874326-9cb3e680-1fec-11ea-9b3f-6fb93753f370.jpg)

The gray bold dashline is the overall density of `srt$nCount_SCT`, and colored lines are grouped by my metadata. Why the distribution looks like this? Is there anything wrong? Could anyone explain this or give me a discussion forum for this kind of question. Thanks a lot!

**Comment by chlee-tabin** [comment]
https://github.com/satijalab/seurat/issues/1775#issue-462803415 I asked awhile about this behavior and got answer from the developers.

**Comment by MajoroMask** [comment]
@chlee-tabin Thanks for replying. I'm just wondering if this "dual-peak" distribution means that I have too many double droplets, since the right peak is roughly twice the `nCount_SCT` over the left peak.

I believe the `nCount_SCT` column is calculated as sum-up of each column in the original `RNA` UMI matrix:

```
identical(
  srt %>% GetAssayData(assay = "RNA") %>% colSums(),
  srt$nCount_RNA
)
#: [1] TRUE
```
So we can expect it to have a normal distribution over all cells. Please correct me if I'm wrong. It's nice to have someone to discuss with and learn to.

**Comment by chlee-tabin** [comment]
@MajoroMask I do not know about this, but checking whether the original "RNA" slot follows the same distribution (dual peak) would help for further the discussion. My understanding from the developer's response above was that there is no meaning with the nCount_SCT slot and should be disregarded. I would be also curious to know whether my understanding is incorrect.

**Comment by MajoroMask** [comment]
@chlee-tabin Thanks for your reply. I tried some public data from `Seurat` and `monocle3` tutorials. 

```
library(Seurat)
library(tidyverse)

plot_rna_count <- function(srt_obj, color = NULL) {
  require(Seurat)
  require(tidyverse)
  
  stopifnot(class(srt_obj) == "Seurat")
  stopifnot(color %in% colnames(srt_obj[[]]))

  color <- sym(color)
  p <- 
    srt_obj[[]] %>% 
    ggplot(aes(x = nCount_RNA + 1)) + 
    geom_density(color = "gray80", linetype = 2, size = 1.5) + 
    geom_density(aes(color = !!color)) +
    scale_x_log10() +
    theme_bw()
}
```

Please notice that I use `scale_x_log10()` to scale the x axis. If not all curve line will look like a gamma distribution.

## CAO data from monocle3 tutorial ([source](https://cole-trapnell-lab.github.io/monocle3/docs/starting/))

```
sm_cao <- read_rds("./cao/cao_l2_expression.rds")
df_meta_cao <- read_rds("./cao/cao_l2_colData.rds")
cao <- CreateSeuratObject(
  counts = sm_cao, meta.data = df_meta_cao, project = "cao"
)
p1 <- plot_rna_count(cao, color = "plate")
```

(Please try run this code by yourself since I been keeping failing upload my PNG file. All hail to the Great Firewall.)

## PBMC data from Seurat tutorial

The `pbmc_stim.RData` from https://portals.broadinstitute.org/harmony/SeuratV3.html is derived from https://satijalab.org/seurat/v3.0/immune_alignment.html

```
load("./pbmc/pbmc_stim.RData")
pbmc <- CreateSeuratObject(
  counts = cbind(stim.sparse, ctrl.sparse), project = "PBMC", min.cells = 5
)
# identical(
#   pbmc$nCount_RNA, 
#   GetAssayData(pbmc, assay = "RNA") %>% Matrix::colSums()
# )
pbmc@meta.data$stim <- c(
  rep("STIM", ncol(stim.sparse)), 
  rep("CTRL", ncol(ctrl.sparse))
)
p2 <- plot_rna_count(pbmc, color = "stim")
```

![nCount_RNA_pbmc](https://user-images.githubusercontent.com/19700954/71072485-932ba980-21b9-11ea-8bed-d6db9ff64d3e.png)

## MCA data from Seurat V3 tutorial ([source](https://satijalab.org/seurat/v3.1/mca.html))

```
sm_mca <- read_rds("./MCA/MCA_merged_mat.rds")
df_meta_mca <- 
  data.table::fread("./MCA/MCA_All-batch-removed-assignments.csv") %>% 
  column_to_rownames(var = "Cell name")
mca <- CreateSeuratObject(
  counts = sm_mca, meta.data = df_meta_mca, project = "MouseCellAtlas"
)
mca <- mca[, !is.na(mca$ClusterID)]
mca_sub <- mca[, mca$Tissue == "Uterus" | mca$Tissue == "Stomach"]
p3 <- plot_rna_count(mca_sub, color = "Tissue")
```

![nCount_RNA_mca_sub](https://user-images.githubusercontent.com/19700954/71072239-0385fb00-21b9-11ea-8c7d-82a584ca8567.png)

Please notice that I use subset of this huge dataset to make the pattern more clear. If you try passing `mca` object to the plot function, you may notice there is a continuous pattern that spread through each subset. Some samples show simple gamma distirubion-like curve, while others show "dual-peak" curve with the higher peak on the right or left side of the axis x.

**Comment by MajoroMask** [comment]
![nCount_RNA_cao](https://user-images.githubusercontent.com/19700954/71138106-53120880-2245-11ea-8183-29bfa44a5186.png)

This is `p1` that mentioned above. This `plate` represent different batches used in sample preparation. You can see the weird distribution in some batches.

**Comment by chlee-tabin** [comment]
@MajoroMask Honestly, I do not think the weiredness you see after SCT is there for the RNA assays (given you log scaled for the RNA assay whereas for the SCT of the initial issue it is linear). The dual peak I see for the RNA assays are most likely stemming from empty droplets (or bad cells) whereas pretty much for a lot of SCT graphs the peak modes are much larger.

Again, not from the development team and just remembering the past response that SCT nCounts should be disregarded. (Open to further explanations or corrections!)

**Comment by RobinPranter** [comment]
@MajoroMask Did you ever find an answer to this question? I am having a similar problem: 

<img width="1907" height="951" alt="Image" src="https://github.com/user-attachments/assets/4532e48a-2b32-4725-a6e6-5c4b2eeaf861" />
The three first plots are total number of reads, UMIs and genes per cell. The following two are the SCT-normalized number of UMIs and genes per cell and the last four are the normalized expression of house keeping genes. Each dot is a cell and each violin is a plate.
