### ISSUE TITLE
Working with index sort data in Seurat

### ISSUE THREAD

**Issue by Florencia1805** [satijalab/seurat#2428]
Hello, 

I have done scRNAseq (SORT-seq) on a population of cells on which I have also performed an index sort during FACS. I have looked at your vignette on working with multi-modal data in Seurat and was wondering whether I could achieve such nice plots with the protein expression levels from my index sort as well. I do not have any ADT files however, as I have not made use of DNA-barcoded antibodies but merely FACS antibodies for the sort. I therefore do not know how I could nicely link the protein expression levels that I have obtained from the FACS with my scRNAseq data. Any advice on how to do this? 

Many thanks in advance, 
Florencia

**Comment by samuel-marsh** [comment]
Hi Florencia,

Not a member of the Dev team but hope this can be helpful.  I'm assuming when you did the sort do you have unique cell barcodes in the wells and that you know the barcode value in each well?  If you have this info then you can link the flow data to the scRNA-seq expression data.  

You should be able to do it by creating data.frame in R or in excel a csv with the values from the index sort, just like in the vignette where they import the ADT .csv file.  Create your own file that mirrors the file structure in that vignette (cell barcodes in column names and flow index value names in the row names).

Then you should be able to simply follow the vignette to import your file with custom values and integrate it into your object for analysis.

Hope that helps!
Best,
Sam

**Comment by Florencia1805** [comment]
Hi Sam, 

Thank you very much for your kind advice! Yesterday I have indeed tried to do that. So I created a CSV file with the values from the index (geoMFI of 7 fluorochromes). The column names are the "cell IDs'' so to speak and the row names are the respective fluorochromes/surface markers. 

However, I perform QC and filtering steps on my "RNA" file and after that I am left with fewer cells than the original 384. Thus, when I try the CreateAssayObject step, I get an error saying "Error: Cannot add a different number of cells than already present" which makes sense, ofcourse. So now I'm stuck here, because I cannot seem to export the dataframe that I worked on (which was the "RNA" file) and look at the structure. I get the error "cannot coerce class ‘structure("Seurat", package = "Seurat")’ to a data.frame". So I tried to convert the object (class was dgCmatrix) into a regular matrix with the function as.matrix and tried a couple of other things but with no success :(. 

If you have any advice on how to proceed or what I might have done wrong, please feel free to comment!

Many thanks again, 
Florencia

**Comment by samuel-marsh** [comment]
Hi Florencia,

The Devs may have better solution but as work around does it work if you simply get list of cell IDs in the filtered object and then filter your index csv file prior to adding it?

I would also say that someone else can probably give better opinions on proper normalization of index sort data as opposed to ADT data but that might be better for bioinformatic forum (Biostars/Stack Exchange).

Best,
Sam

**Comment by Florencia1805** [comment]
Hi Sam, 

Thanks for your comments, very much appreciated and I will take them into account. Fingers crossed that someone else might have additional suggestions!

Kind regards,
Florencia
