### ISSUE TITLE
Should RunTSNE() and  TSNEPlot() give the same result if I  run RunTSNE() multiply times?

### ISSUE THREAD

**Issue by singletrips** [satijalab/seurat#2430]
Should RunTSNE() and  TSNEPlot() give the same result if I  run RunTSNE() multiple times?
My results are always the same. So I was wondering whether the TSNEPlot() result should change or not?

**Comment by kaizen89** [comment]
`RunTSNE` sets `seed.use=1` by default to give the same output when run multiple times. I have experienced sometimes that running tSNE on linux or windows gives a slightly different result.

**Comment by singletrips** [comment]
Got it, thanks@kaizen89.
