### ISSUE TITLE
-split.by- command on Merged Files returns aberrant tSNE plot 

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#2433]
Hi all,
I am trying to analyze differential gene expression between 2 data sets ("ctrl" and "treated"). I am running Seurat standard workflow ( -> CreatSeuratObject -> QC -> Normalization ->scaling ->PCA -> clustering). After doing dimension  reduction tsne with the merged file (Merged-ctrl-treated), I get a nice cluster separation of the cells in both groups (ctrl and treated). Then, I do tsne with `group.by = orig.ident` to separate cells based on their original identity. 

But then, Seurat was not allowing me to use the argument `split.by = treated` to visualize how cells from the two samples are spread out across different clusters in tsne, independently (i.e: a tsne with ctrl sample and another tsne with treated sample side-by-side). Thus, I copied part of the code used with vignette "integrating stimulated vs control" in Satija's homepage, where after `CreateSeuratObject' "ctrl", I have an extra line `ctrl$treated <- "ctrl"`.  And after `CreateSeuratObject` "Treated", I have an extra line `Treated$treated <- "treated"`. 

First problem: after doing the clusters analysis using the argument `split.by` , the cluster analysis returns some clusters with very low cell numbers, very different of the cell numbers per cluster I get when I run each sample individually.

Second Problem: Now, I am capable of doing dimension reduction tsne and observe how cells of the two samples spread out in tsne across different clusters. However, the plot seems a bit awkward. Very different of the one I get when I work with each sample (ctrl or treated) individually. 

Both "ctrl" and "Treated"
<img width="730" alt="image" src="https://user-images.githubusercontent.com/58445209/70955385-51262a80-2036-11ea-937c-027fd414284d.png">

only "ctrl"
<img width="263" alt="image" src="https://user-images.githubusercontent.com/58445209/70956201-ea564080-2038-11ea-911e-03a3851b1193.png">

Only "treated"

<img width="269" alt="image" src="https://user-images.githubusercontent.com/58445209/70956169-d14d8f80-2038-11ea-9aca-abf15cf8ef55.png">

It is also different from the tsne I get when I run the vignette "integrating stimulated vs control", with the combined ctrl-treated file. 

This "artifact, does not seems to interfere with different visualization tools such as violin plots.

I guess, the question right now is why is the tsne of the merged file different of the individual ones?
I thank you all in advance.

**Comment by kaizen89** [comment]
Hi, 
I'm not from satijalab. Both clustering and tSNE would give different results if they are not run on the same dataset with the same parameters. This is not an issue related to the `split.by` argument. You can try this on the merged dataset and plot the tSNE with the cells colored by group (ctrl vs trt) you will see that it is still different from what you get when you perform the analysis on individual datasets.

**Comment by giovanegt** [comment]
In my case, I am running the same data sets with the same parameters. However, I get different results depending on if I integrate the two files or merge it. The `split.by` argument is only accepted with the merged file if I do the following.

`ctrl.data <- Read10X(data.dir ="/...")`
`ctrl <- CreateSeuratObject(counts = ctrl.data, project = "ctrl")`
`ctrl$treated <- "ctrl"`
`ctrl`

treated.data <- Read10X(data.dir ="/...")
treated <- CreateSeuratObject(counts = treated.data, project = "treated")
treated$treated <- "treated"
treated

Merged.big <- merge(ctrl, y = c(treated), add.cell.ids = c("ctrl","treated"), project = "ctrl_treated")
Merged.big`

Now, both, `ctrl$treated<- "ctrl"` and `treated$treated <- "treated` are used for the integration and not to Merge different files. I believe that i need to use these 2 lines to be able to split the merged files for further analysis. But when I do it, something is changing with the, perhaps, cluster analysis, PCA and dimension reduction. 
If you notice the first figure the treated sample group (blue) fit perfectly inside the control sample group (red), in tsne. Please compare the first graph above with this one, below. 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/58445209/71032738-8f295a00-20db-11ea-8e4e-4c4b8b62c8dc.png">

**Comment by kaizen89** [comment]
Could you share the code that you used to generate the figures in your first post starting from the count matrices?

**Comment by giovanegt** [comment]
sure,
after, Normalize, FindVariableFeatures, scaling.

Run PCA
`Merged.big <- RunPCA(Merged.big, features = VariableFeatures(object = Merged.big))`
```
```{r}
#The 20 most variable genes in the first 10 principal components
`print(Merged.big[["pca"]], dims = 1:10, nfeatures = 20)`
```
```{r}
`VizDimLoadings(Merged.big, dims = 1:2, reduction = "pca")`
```
```{r}
`DimPlot(Merged.big, reduction = "pca", label.size = 20) + theme(text = element_text(size = 20))`
```
```{r}
The resolution here is = 0.3 to control the number of clusters.
`Merged.big <- FindNeighbors(Merged.big, dims = 1:20)`
`Merged.big <- FindClusters(Merged.big, resolution = 0.3)`
```
``{r}
`Merged.big[["my.clusters"]] <- Idents(object = Merged.big)`
```
```{r}
# Get number of cells per cluster and per sample of origin
`table(Merged.big@meta.data$my.clusters, Merged.big@meta.data$orig.ident)`
```
`Merged.big <- RunTSNE(object = Merged.big, dims = 1:11)`
dims = 11 accordingly, to the number of communities from before.

Now, tsne with the merged Seurat object. 
````{r}
`DimPlot(Merged.big, reduction = "tsne", label = TRUE, label.size = 10, pt.size = 2) + theme(text = element_text(size = 25, face = "bold"))`

Then, tsne with `split.by' argument, that gives the separation observed  the on top, in the very first figure. 
```{r}
`DimPlot(Merged.big, reduction = "tsne", split.by = "yn1", label = TRUE, label.size = 10, pt.size = 1) + theme(text = element_text(size = 25, face = "bold"))`
```
I guess, my concerns are whether I doing something wrong that is generating a scientific artifact in my results.

**Comment by kaizen89** [comment]
What about the "only ctrl" and "only treated" figures?
The tSNE plots in the code you shared give the same ouptut right? Where exactly is the issue?

**Comment by giovanegt** [comment]
The results I get are different (tsne, number of cells per cluster, cluster identity), that is the problem. If I run the analysis separately, I get something like the results above, please see, "only ctrl"  and "only treated" tsne (shown above). 
if I merge  ctrl and treated samples, and  split them after,  I get a different results in `FindNeighbors(Merged.big, dims = 1:10)` and  `FindClusters(Merged.big, resolution = 0.5)`
some cluster become  empty basically (see variation of Clusters "0" and "1" up on top, first tsne graph.

why would the merged ctrl-treated files give clustering numbers and cell number per cluster different of the individual samples?

```

**Comment by kaizen89** [comment]
A fas as I know there are too many reasons to explain theis difference, but to give you an example, run a PCA on the individual samples and another PCA on the merged samples. You will see that the distribution of the cells for each individual sample is different from the one you get in PCA on the merged samples. Both tSNE and clustering are based on the PCA, not to mention the fact that they are not robust to a change in the number of cells.

**Comment by giovanegt** [comment]
This is cluster number and cell number per cluster when the two condition are treated merged together.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/58445209/71122269-cd8b4b80-21a5-11ea-9f8c-44c5b56a8c3b.png">

Now if only treated sample is handled independently I have
cluster       cell number
  0   --           1118
  1    --           1044
  2    --          1033
  3   --           736
  4   --           694
  5    --          645
  6    --           573
  7  --             510
  8   --           412
  9   --           351
  10   --          298
I guess, I expected to find the same number of cells per cluster, independently of handling the merged file or each sample (ctrl , treated) separately.  Perhaps, I could rum a PCA in each sample separately, and them merge the files for differential gene expression analysis. Would it be correct?
I thank you very much for your attention. I appreciate it.

**Comment by kaizen89** [comment]
I do not see the point to do that.

**Comment by giovanegt** [comment]
The cell number differences per cluster concerns me.

**Comment by timoast** [comment]
This is the expected behaviour. If you change the set of cells that you're using, the tSNE and clustering results will change. There no reason that, for example, cluster 8 in the merged dataset would correspond to cluster 8 in one of the datasets when clustered independently.
