### ISSUE TITLE
Correct format for saving Cell IDs for subsetting

### ISSUE THREAD

**Issue by kathirij** [satijalab/seurat#2435]
Hello All,
  This is a really naive question - what is the correct format of saving cell names from an object so that it can be read later on for subsetting?

More specifically, I have two large populations in my object - epithelial and mesenchymal.. i can create two objects by subsetting with "WhichCells" command and choose either epi or mes cells based on clusters. However, I would like to save these cell IDs and use them again later on... If i save them as CSV, how do I read them so that they are in the correct format for future WhichCells command?

--
Thanks,

**Comment by MajoroMask** [comment]
You can save this information into the `meta.data` slot of your `Seurat` object. 

Let's say we build a classing vector (in your case these are the two objects `WhichCells` return):

```
group_ms4a1_high <- WhichCells(pbmc_small, expression = MS4A1 > 5)
group_ms4a1_low <- WhichCells(pbmc_small, expression = MS4A1 < 3)

group_info <- rep(0, ncol(pbmc_small))
names(group_info) <- colnames(pbmc_small)
group_info[group_ms4a1_high] <- 1
group_info[group_ms4a1_low] <- -1
```
Check it by calling `table(group_info)` or `head(group_info)`:
```
table(group_info)
#> group_info
#> -1  0  1 
#> 68  3  9 
head(group_info)
#> ATGCCAGAACGACT CATGGCCTGTGCAT GAACCTGATGAACC TGACTGGATTCTCA AGTCAGACTGCACA TCTGATACACGTGT 
#>             -1             -1             -1             -1             -1             -1 
```
Call `AddMetaData()` to add this variable to `meta.data` slot of your `Seurat` object:

```
pbmc_new <- AddMetaData(pbmc_small, group_info, col.name = "cut_MS4A1")
```

After this, you can call it back like all other metadata, just like this: `pbmc_new$cut_MS4A1`.
Or use it to subset your `Seurat` object like `pbmc_new[, pbmc_new$cut_MS4A1 == 1]`:

```
identical(pbmc_new$cut_MS4A1, group_info)
#> [1] TRUE

pbmc_new[, pbmc_new$cut_MS4A1 == 1]
#> An object of class Seurat 
#> 230 features across 9 samples within 1 assay 
#> Active assay: RNA (230 features)
#>  2 dimensional reductions calculated: pca, tsne
```

**Comment by timoast** [comment]
You can save the information in metadata as @MajoroMask suggests, or write to a file using `writeLines` and read back into R using `readLines`

**Comment by kathirij** [comment]
Thank you to both of you!
