### ISSUE TITLE
What's the corresponding parameter for "ident.remove" in subset()?

### ISSUE THREAD

**Issue by singletrips** [satijalab/seurat#2437]
In SubsetData() I can use " ident.remove" parameter. However SubsetData function will be deprecated. So what's the corresponding parameter for "ident.remove" in subset()?

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but hopefully this is helpful.  To remove a parameter use the `invert = TRUE` as part of the subset call.  See the following example that is part of the subset documentation:
`subset(x = pbmc_small, idents = '0', invert = TRUE)`

Best,
Sam

**Comment by singletrips** [comment]
Thanks! It works!
