### ISSUE TITLE
Installation of Seurat

### ISSUE THREAD

**Issue by ylive001** [satijalab/seurat#2441]
Hi there,

I tried to install and load library (Seurat). 

> install.packages('Seurat',depedencies = TRUE)
> library(Seurat)

However, I received an error message as below:

Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 object 'vI' not found

Do you happen to know what the problem is and how to fix this issue?

Thanks,
Mia

**Comment by timoast** [comment]
Does the problem persist if you restart R and try again?

**Comment by kihyunleephd** [comment]
Hi,

I have the exact same error. I tried everything including reload R, update.packages, restart the R studio and computer, etc. I still see the error msg. Can anyone help this with me?

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 object 'vI' not found
