### ISSUE TITLE
Cell cycle regression in scRNA before integration with scATAC

### ISSUE THREAD

**Issue by RegnerM2015** [satijalab/seurat#2443]
I am trying to perform the scRNA/scATAC integration analysis on my own data similar to here: https://satijalab.org/seurat/v3.1/atacseq_integration_vignette.html 

I want to implement the cell cycle regression in my scRNA-seq before integrating with matched scATAC-seq. In my scRNA-seq data, cells cluster by cell cycle phase in both PCA and UMAP. However, in my scATAC-seq data I get 1-2 large clusters of cells after LSI reduction. After using the cell cycle regression in my scRNA data, it better resembles the matched scATAC in terms of clustering. 

Is it generally acceptable to perform this cell cycle regression on one of your datasets (but not both) before integrating? Would it more acceptable/appropriate to also perform the cell cycle regression on the gene activity matrix on the scATAC dataset before integrating with scRNA? 

Please let me know if any more information would be helpful. 

Thanks in advance!

**Comment by timoast** [comment]
It should be fine to perform cell cycle regression in the RNA data and not the ATAC data
