### ISSUE TITLE
Creating PDFs with FeaturePlot in seurat v3.1

### ISSUE THREAD

**Issue by Schleifchen90** [satijalab/seurat#2444]
Hi,
I found that i cannot open pdf files that were created with "FeaturePlot" function in seurat v3.1 when using a for loop:

genestoplot <- c("Il1b","Il6")
pdf(sprintf("%s/featureplots.pdf",pbmc.workdir, pointsize = 12)
for (i in 1:length(genestoplot)){
FeaturePlot(pbmc, features = c(genestoplot[i]), max.cutoff = 3, cols = c("grey", "red"), combine = FALSE)}
dev.off()

Is there another way to print multiple featureplots?

**Comment by andrewwbutler** [comment]
Hi,

`FeaturePlot` returns ggplot2 objects. I would try using [`ggsave`](https://ggplot2.tidyverse.org/reference/ggsave.html) inside the for loop here.

**Comment by Schleifchen90** [comment]
Thank you so much! Its working now
