### ISSUE TITLE
Given an error when analyzing scATAC-seq using CreateGeneActivityMatrix

### ISSUE THREAD

**Issue by yycunc** [satijalab/seurat#2447]
I am trying to generate a gene activity matrix for scATAC-seq data using Danio_rerio.GRCz11.98.filtered.gtf. However, I meet an error "Error: logical subscript contains NAs".

I define the seq.levels separately by giving the function one chromosome each time and find that all other chromosomes except chr8 and chr16 are OK. The error only occurs for these two chromosomes. 

I saw somebody else who did the analysis on zebrafish also have the same issue. Is there any idea what is going wrong and how to fix this error?

Thanks.

**Comment by timoast** [comment]
We recommend using functions in [Signac](https://satijalab.org/signac/index.html) to create a gene activity matrix. If you need to use this function for some reason, can you provide a reproducible example?
