### ISSUE TITLE
adding a transgene to mm10, and scRNA-seq analysis with Seurat

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2448]
Dear all, 

'd appreciate please having your advise on the process of adding a transgene (it is called  "mCherry_4D)" to the mouse reference sequence mm10 in order to be fully analyzed with Seurat 
('ve been using Seurat 2.3.4) : 

the initial steps work well, however, at the end there is a bit of issue ...

I've followed the steps : 

1 . 've updated the GTF file of mm10 genes

2.  've updated the FASTA file of mm10

3.  've made a new reference genome sequence : it is called " mm10_with_mCherry_4D"

4.  've aligned the scRNA-seq FASTQ  to the new reference genome sequence

5.  and in the file features.tsv (genes.tsv), I do see the TRANS-GENE: 
ENSMUSG00000096730	Vmn2r122	Gene Expression
ENSMUSG00000095742	CAAA01147332.1	Gene Expression
mCherry_4D mCherry_4D Gene Expression 

6. however, after I reading the matrix/ feature /barcodes in Seurat 2.3.4, the transgene  "mCherry_4D" is not in the matrix data of Seurat. 

Is there a particular way we can fix it ? could it be a problem with the name of the trans-gene ? 
or something else that we can potentially miss ? thank you, 

-- bogdan

**Comment by andrewwbutler** [comment]
Hi,

When you read the matrix into R, what are the values across all cells that you see for the transgene? It's possible that it is getting filtered out in the initial `CreateSeuratObject` step if it doesn't meet the thresholds you set in that function (or if it has no counts in any cells).

**Comment by tanasa** [comment]
Dear Andrew, thank you for your reply. We wish you a fruitful and joyful 2020 !

I am still investigating the issue with the folks from 10X Genomics.

**Comment by shengqh** [comment]
I am building the reference with transgene now. Will have a look if I will meet this problem.
