### ISSUE TITLE
Umap plot is different from the old one.

### ISSUE THREAD

**Issue by gdk43** [satijalab/seurat#2449]
Hello,

I have used seurat v3.1.0 for scRNA-Seq data and had made plots.
Now, when I run the same script after two months, I can't get the same UMAP plot. 
Overall, It looks similar and had the same number of clusters & marker gene compare to the old one,
but the UMAP plot is a little bit different.

I tried the same script in the various version (3.0.2/3.1.1/3.1.2) and manipulated the seed.use in RunUMAP.
However, I can't get the same result.
This makes my results seem inconsistent.

I tried different versions with the same script, but I don't know why not.

1. Any ideas What makes my UMAP look different and can I get the same UMAP plot?
2. Is it natural for the UMAP plot to change??

Thank you

gdk43

**Comment by andrewwbutler** [comment]
Hi,

If you reinstall Seurat v3.1.0, are you able to reproduce the same plots from before? Also, are you using the same version of the UMAP package that was used in the initial analysis?

**Comment by gdk43** [comment]
Thanks for your quick reply!
The culprit was the UMAP package.
when I downgraded the version of uwot package, the matter was gone.

Thank you
