### ISSUE TITLE
DESeq2 won't work with FindAllMarkers() but Wilcox test does

### ISSUE THREAD

**Issue by jr-leary7** [satijalab/seurat#2450]
After running QC / dimension reduction / clustering on my Seurat object, I'm trying to use `DESeq2` with `FindAllMarkers()`. The function runs through the typical "Calculating cluster i, converting counts to integer mode" for each cluster before resulting in the following error: 
```
The following tests were not performed: When testing 0 versus all: every gene contains at least one zero, cannot compute log geometric means
```
I get that `DESeq2` uses a log-link modeling function and that taking log(0) is going to cause problems. How do I avoid this? Using a Wilcox test works perfectly fine, but I'd prefer to use `DESeq2` if possible. Would defining `counts = counts + 1` fix the problem?

**Comment by satijalab** [comment]
Adding 1 to the counts would fix the problem, but could violate some of the assumptions of DESeq. This would be a question for the DESeq/2 authors to better understand how to apply their workflows (which are tailored to bulk data) to scRNA-seq experiments
