### ISSUE TITLE
issue about FindMarkers function

### ISSUE THREAD

**Issue by jhT1995** [satijalab/seurat#2452]
i have learned about the source code of FindMarkers, and i can't understand for the symbol '%| |%' of the line 469 in differential_expression.R, what the meaning of this symbol, and which package defined this symbol? and which format of the input data in this function, raw count, raw count scale data or i can use the data after scTransform?

**Comment by andrewwbutler** [comment]
Hi,

`%||%` is an internal convenience function that we use to set the value of a variable if the current value is `NULL` (originally proposed [here](https://adv-r.hadley.nz/functions.html#missing-arguments)).  The input for `FindMarkers` will depend on what you specify with the `slot` parameter. Please see the function documentation for further details.
