### ISSUE TITLE
FindTransferAnchors when normalization.method is SCT

### ISSUE THREAD

**Issue by lyc-1995** [satijalab/seurat#2453]
Hello,
I have used Seurat 3.1.1 to do integration and label transfer, and I notice that you have try to avoid doing `ScaleData` when `normalization.method` is set to SCT. However, when I checked the source code `integration.R,` I found that, in https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/integration.R#L463 and https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/integration.R#L559, the `FindTransferAnchors` function still used `ScaleData` in spite of the `normalization.method`. 
I wonder if it is right to do this. It will be appreciated if there is any information or advice you could give me.

Thank you,
Yuchen Lee

**Comment by andrewwbutler** [comment]
Hi Yuchen,

Sorry for the slow response. You're correct that `ScaleData` shouldn't be performed here if `normalization.method = "SCT`. This was recently fixed on the `develop` branch (0d5e5e0878f90e66eae3a8bdd3ffd39d77ef5567)  if you want to try reinstalling from there.

**Comment by lyc-1995** [comment]
The fixed version was helpful to me. Thank you so much!

**Comment by deevdevil88** [comment]
Hi! is this still a bug in the default version on CRAN and github? Do I need to use the develop branch  to avoid this.

**Comment by andrewwbutler** [comment]
No, as long as you are using Seurat v3.1.3 (v3.1.4 is the current CRAN version), this bug should be fixed.
