### ISSUE TITLE
Regressing parameters for further analysis

### ISSUE THREAD

**Issue by meshik** [satijalab/seurat#2455]
Hello!
I'm trying to compare 2 groups from my Seurat object,
but the differentially expressed genes I find are influenced mainly by sex difference and 1 more parameter that are distributed unequally between the groups.
Is there a way to regress these influences out and search for "real" differences in gene expression?

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

The `latent.vars` parameter in `FindMarkers` could be used here to include additional variables in the differential expression tests. Note that if you choose to use this approach, you will need to specify a `test.use` (e.g. `LR`)  that allows the DE modeling to include additional latent variables.
