### ISSUE TITLE
How do find differential expressed gene between two samples within the three more samples

### ISSUE THREAD

**Issue by naixiangxiaozi** [satijalab/seurat#2456]
Hi all, I was wondering whether we can only find differential expressed genes between the two samples within the three samples. As shown in my figure that there are three samples (Shox2-KO, Double-KO, and WT) and got two clusters. But I would like to find the differential expressed genes between the sample Shox2-KO and Double-K0. Another question is about whether we can do heatmap that can group_by sample rather than cluster?
<img width="579" alt="spiltby 2 clusters" src="https://user-images.githubusercontent.com/42306818/71455115-39972200-2759-11ea-96c8-79741a8b3db4.png">

**Comment by satijalab** [comment]
Apologies for the slow reply. you can use the group.by argument (both in FindMarkers and DoHeatmap) to group cells however you like (i.e. by sample, cluster, etc.)

In (https://satijalab.org/seurat/v3.1/immune_alignment.html), we cover an example for how to discover DE genes either across cell types, or within the same cell type (across conditions)
