### ISSUE TITLE
Question for SCTransform counts

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#2457]
Hi

I'm a little confused about the counts of "SCT" assay in the Seurat object. In my data, I found some genes' counts in some cells were increased in "SCT" assay compared with "RNA" assay, as shown below:

```
seu@assays$RNA@counts["NKG7",1:5]
```

> AAACCCAAGTATCCTG    AAACCCACAAACGGCA    AAACCCACAGGCATGA
                  17                                    0                                    17
AAACCCAGTATAGGAT AAACCCAGTCGAGCTC
                   0                    0
```
seu@assays$SCT@counts["NKG7",1:5]
```

> AAACCCAAGTATCCTG AAACCCACAAACGGCA AAACCCACAGGCATGA
                  10                    0                   22
AAACCCAGTATAGGAT AAACCCAGTCGAGCTC
                   0                    0

I wonder why this is happening.
Thanks!

**Comment by CodeInTheSkies** [comment]
I'm not from the development team, but just attempting to chime in.  I think the `counts` slot of the "SCT" assay is supposed to be adjusted/corrected counts derived by reverse-transforming the Pearson residuals, see here: https://github.com/satijalab/seurat/issues/1957
The `counts` slot of the "RNA" assay, on the other hand, would just have the raw counts read from the UMI data, see the beginning of the tutorial here:  https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html

So, they can be different, and I think in your case, the SCT-normalized corrected counts for some of the genes you mentioned end up increasing post normalization.  Essentially, the `SCT@counts` may be viewed as the normalized versions of the `RNA@counts` based on the SCT technique.  I'm not entirely sure, but this is what I could gather.  Hopefully, if I am wrong here, somebody from the Seurat team would correct me.

Hope this helps.

**Comment by yuhanH** [comment]
Hi, 
@CodeInTheSkies 's reply is correct. SCT counts is supposed to be sequencing depth corrected counts.

**Comment by coralzhang** [comment]
I am still confused about this one. is the corrected counts calculated from the pearson residuals in the scaled.data in SCT?

**Comment by yuhanH** [comment]
It is calculated from the GLM model used for pearson residuals
You can find more information in the sctransform paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1

**Comment by coralzhang** [comment]
Thanks for the response. Yes, I checked the paper. I am only confused about why you say it is sequence depth corrected? I am looking at the method description on page 11 and it should be on the same scale and meaning of the raw counts or one may say more like the fitted version of the raw counts?

**Comment by coralzhang** [comment]
And also I have one follow up question about the residuals. Pearson residual output from SCTransform (scaled.data) is very clearly stated in the paper. Now my question is about the residuals used in the function correct_counts, the output of which is saved in the counts in SCTransform output. Is the scaled.data used as input to calculate the correct_counts?

**Comment by yuhanH** [comment]
scaled.data is the centered Pearson residual. From the function correct_counts, you can see the Pearson residual is recalculated using the parameters learned by the model.
