### ISSUE TITLE
About FindMarkers function

### ISSUE THREAD

**Issue by ahmedabbas81** [satijalab/seurat#2458]
Dear all,

Why does the output list of marker genes contains genes with negative avg_logFC and also non significant p-values?

Should I do more filtering to this output marker genes list? And if I should do more filtering, what should be the filtering criteria?

Thanks

**Comment by AndyR2** [comment]
You should add thresholds to your call to limit the output.  For eg.
rna.markers <- FindAllMarkers (object, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

learn to use the Help tab to see R Documentation in R studio.   All Seurat functions fully explained

**Comment by ahmedabbas81** [comment]
Is there a way to get the marker genes by cell type instead of active ident? 

I am storing cell types in meta data of Seurat object. I cannot simply change labels of active ident to cell types because for example ident 0 may contain 2 cell types.

Thanks

**Comment by mojaveazure** [comment]
Please see the `group.by` parameter in the documentation for [`FindMarkers`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/FindMarkers)
