### ISSUE TITLE
Gene name and row.names not same in output of FindAllMarkers()

### ISSUE THREAD

**Issue by piyushjo15** [satijalab/seurat#2459]
Hi,

I see that quite a few entries in the "gene" column of the output from FindAllMarkers() is not same as the rownames. I don't know what has happened in the code. Some of the gene values are truncated rownames. Eg:

                p_val         avg_logFC       pct.1  pct.2     p_val_adj    cluster   gene
VIM3     1.791258e-160    1.1327442   0.989   0.970   4.825829e-156      13    VIM
RPLP11  3.032379e-129 1.3707208 0.935 0.892 8.169533e-125      13  RPLP1
RPS22   3.324361e-125 1.4767944 0.906 0.826 8.956162e-121      13   RPS2
EEF1A11 2.687522e-124 1.1772156 0.949 0.957 7.240454e-120      13 EEF1A1
RPL33   2.392474e-120 1.3557063 0.911 0.894 6.445565e-116      13   RPL3

**Comment by AndyR2** [comment]
column 1 in this output is just [gene name] + [instance in the full list].  
So, if there are, for example, four clusters with VIM, there will be VIM1, VIM2, VIM3 and VIM4.
Sort alphabetically on column one to see  this more clearly.
