### ISSUE TITLE
Extracting the common genes from multiple Seurat objects

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#246]
Hello, 

Is there a way to find the common genes between six datasets? 
I have a Seurat object for each as well as a raw combined (non-aligned) object.  

Any direct matrix operations I tried crashes my R - I think due to having very large data sets (hundreds of thousands of cells). Working with the Seurat object for this task would be helpful! Thank you!

**Comment by leonfodoulian** [comment]
Is this what you want to do?

```
# Create vector of gene names from all 6 Seurat objects
total.genes <- c(rownames(object1@data),
                 rownames(object2@data),
                 rownames(object3@data),
                 rownames(object4@data),
                 rownames(object5@data),
                 rownames(object6@data))

# Get common gene names 
common.genes <- unique(total.genes[duplicated(total.genes)])
```

**Comment by leonfodoulian** [comment]
My bad, the code above will not work. What you have to do is this:

```
# Create list of gene names from all 6 Seurat objects
total.genes <- list(rownames(object1@data),
                    rownames(object2@data),
                    rownames(object3@data),
                    rownames(object4@data),
                    rownames(object5@data),
                    rownames(object6@data))

# Get common gene names 
common.genes <- Reduce(f = intersect, x = total.genes)
```

**Comment by del2007** [comment]
Thank you Leon, this works!
 Is there a way to keep some of the gene expression metrics and thus generate an object instead of a character list? Such as the average gene expression per set or even the average expression per combined sets 1to4 vs 5and6, for example?

**Comment by leonfodoulian** [comment]
Hi,

I'm sorry but I don't quite understand what is it that you exactly want to do. If you want to have a common Seurat object for datasets 1 to 4, and one for datasets 5 and 6, I suggest you filter the raw data for the common genes, and then create your Seurat objects. You can then [iteratively merge your objects using the `MergeSeurat()` function](https://github.com/satijalab/seurat/issues/207). Any further analysis can then be performed on the resulting objects. 

In case you want details on how to subset the raw data:

```
raw.data.1.subset <- raw.data.1[common.genes,]
```

Hope this helps!

Best,
Leon

**Comment by denvercal1234GitHub** [comment]
@leonfodoulian - Thank you, Leon! Would you mind also helping me to obtain the cells and the genes that get excluded when I set min.cells=9 and min.features=20 in CreateSeuratObject()? It is part of issue #3955. Thank you very much again!

**Comment by denvercal1234GitHub** [comment]
Never mind. I think I figured it out albeit probably not the most robust way to do it. 😅

```
index_excluded <-! rownames(allObject) %in% rownames(filteredObject)
# To get an actually seurat object
genes_excluded_by_mincells <- allObject[index_excluded,]
# To just get a vector of genes names 
genes_excluded_by_mincells_vector <- rownames(genes_excluded_by_mincells)

```
