### ISSUE TITLE
RunUMAP results appear non-deterministic

### ISSUE THREAD

**Issue by slcr-code** [satijalab/seurat#2462]
Hi,

When using the RunUMAP function with one of our datasets, I've found that using a precomputed graph improves the visual quality of the clustering (using the code recommended below). Running UMAP without a precomputed graph results in some moderate cross-cluster contamination. 

However, when I re-run RunUMAP with the same parameters, the output consistently changes. I have tried adjusting several parameters but haven't been able to improve the reliability of the output. 

Is there a way to run UMAP on a precomputed graph and produce a consistent output? (By modifying parameters, etc.) Or is the process non-deterministic?  

Thanks!

In Seurat v3, we have separate clustering into two steps: FindNeighbors, which builds the SNN graph, and FindClusters, which runs community detection on the graph. We also have an option in RunUMAP to use a pre-computed graph, so you could try running UMAP on the same graph use for clustering, for example:

```r
pbmc_small <- FindNeighbors(pbmc_small, dims = 1:10)
pbmc_small <- FindClusters(pbmc_small, graph.name = 'RNA_snn')
pbmc_small <- RunUMAP(pbmc_small, graph = 'RNA_snn')
```

_Originally posted by @timoast in https://github.com/satijalab/seurat/issues/1081#issuecomment-493500876_

**Comment by jr-leary7** [comment]
The UMAP algorithm is non-deterministic (just like t-SNE). It's necessary to provide a seed (there is a seed argument in the `RunUMAP` function) to be able to reproduce your results.

**Comment by jgarces02** [comment]
But the internal option `seed.use` doesn't work...
