### ISSUE TITLE
Subset based on multiple types of assays

### ISSUE THREAD

**Issue by yksaito** [satijalab/seurat#2463]
Hi,
I am analyzing a Seurat object which contains two assays (RNA expression & ADT).
I want to subset Seurat object based on protein expression and RNA expression.

First, I tried to subset my Seurat object based on protein expression.
The script below did not work.
```
# error
subset(tumor_df, subset = `CD4-TotalSeqC` > 0 )

None of the requested variables were found
```

I noticed that I could overcome this problem by changing the default assay.
```
# this script works
DefaultAssay(object = tumor_df) <- "ADT"
subset(tumor_df, subset = `CD4-TotalSeqC` > 0)
```

However, I could not subset Seurat object based on protein expression and RNA expression.

```
# error
subset(tumor_df, subset = `CD4-TotalSeqC` > 0 & GAPDH > 0)
```

Is there any way to do this?
Thanks.

**Comment by mojaveazure** [comment]
Hi,

Could you try the subset command again, but keying your features? See [documentation for `Key`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/Key) for details about querying assay keys in a `Seurat` object and the "Multi-Assay Features" section of our [command cheat-sheet](https://satijalab.org/seurat/essential_commands.html) for details about keying features in functions.

**Comment by yksaito** [comment]
The script below worked. Thank you!!

```
# Set the key for RNA & ADT
Key(object = tumor_df[["RNA"]]) <- "newkey_"
Key(object = tumor_df[["ADT"]]) <- "newkey2_"

subset(tumor_df, subset = `newkey2_CD4-TotalSeqC` > 0 & `newkey_GAPDH` > 0)
```

**Comment by timoast** [comment]
FYI, you didn't need to set a new key here. Doing this would have worked:

```r
subset(tumor_df, subset = `adt_CD4-TotalSeqC` > 0 & rna_GAPDH > 0)
```
