### ISSUE TITLE
Error when running RunTSNE

### ISSUE THREAD

**Issue by zzhmark** [satijalab/seurat#2464]
Error message:
`Error in system2(command = "which", args = "fast_tsne", stdout = TRUE) : 
  '"which"' not found`

I assume that's because I ran it on win, which doesn't have such cmd as `which`.

**Comment by mojaveazure** [comment]
Hi,

Thank you for bringing this to our attention; we are working on a fix and will update when we have more details.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
