### ISSUE TITLE
RunUMAP ERROR in uwot

### ISSUE THREAD

**Issue by xf78** [satijalab/seurat#2466]
Hi dear seurat team:
i generate a seurat object from my count file,i want to RunUMAP with all feature(~6000 genes)
RunUMAP(exp_seurat,features = rownames(exp_seurat),min.dist = 0.5)

###############################
09:32:04 UMAP embedding parameters a = 0.583 b = 1.334
Error in uwot(X = X, n_neighbors = n_neighbors, n_components = n_components,  : 
  Sparse matrices are only supported as distance matrices

how could i solve this problem,thinks

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
