### ISSUE TITLE
JackStrawPlot is odd

### ISSUE THREAD

**Issue by benxiahu** [satijalab/seurat#2467]
when I used Seurat3 to analyze scRNA-seq data, and made a plot with JackStrawPlot. But this plot seems to be too strange.
Do you know what wrong is?

![image](https://user-images.githubusercontent.com/12387462/71672484-1285b500-2d44-11ea-8d9a-55642f7a687d.png)

**Comment by timoast** [comment]
I don't think there's anything unusual about this. It looks like you have over 20 significant PCs.
