### ISSUE TITLE
Heterogenous Samples: Data integration and batch correction

### ISSUE THREAD

**Issue by soprescu** [satijalab/seurat#2468]
Hi, 

I am working with Seurat v3.1 to analyze some of our single-cell sequencing datasets. First, thank you for developing this tool. It is a life-saver! I do have some questions regarding data-integration and when to apply it.

We collected samples at 7 different time-points (in 4 batches, not grouped by time-point, all done on the sample platform, same species, and by the same researcher). Currently, there is no obvious reason to suspect major batch-effects as the samples cluster by their time-point rather than batch. We also expect this to be the case as this is a progressive process we are attempting to capture. 

However, I am not sure what the best method is to visualize all of the 7 time-points together, as these time-points are from whole tissue and we anticipate both intra- and inter-sample biological heterogeneity.

Here are the methods I have attempted and am still unsure which is best:
(1) Merging the data first and then normalizing, clustering, etc (used both SCTranform and log-normalization, generally yields similar UMAP structure)
(2) Integrating the datasets (following the tutorials, using the time-points as reference (again, used both the log-normalization and SCTransform)

I worry that some of the biological variation may be masked/considered technical when using (2) but I also am worried that first combining all the data and using SCTransform is not ideal (as the pre-print suggests when the individual samples are heterogeneous).

Any advice on which method you would recommend using (or heuristic approaches I can use to determine which method is best) is greatly appreciated, thank you so much!

**Comment by satijalab** [comment]
Thanks, and I know this is a challenging and confusing topic, regardless of the specific computational method for integration that is used.

In similar situations, we will typically perform integration of samples within a timepoint, but then merge the integrated assays of samples from different time points. This removes within-timepoint heterogeneity, but preserves changes across time. This is essentially a hybrid approach of (1) and (2)
