### ISSUE TITLE
Choice in integration

### ISSUE THREAD

**Issue by peaceisking** [satijalab/seurat#2470]
I have four groups ,each group has four samples. But in each group ,some of them are sequenced by 10X Chromics V2 , some are sequenced by 10X Chromics V3.

Like the Vignettes say

> pancreas.list <- SplitObject(panc8, split.by = "tech")

> pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]

So what kind of variable should I choose to split by in integration ? Method or Group?Or other methods?

Thank you very much!

**Comment by timoast** [comment]
You should group by whatever makes the most sense for your dataset (v2 vs v3, group, or both combined). By looking at the data first without integration you should be able to determine the source of batch effects if there are batch effects present
