### ISSUE TITLE
re-order plots after using split.by function to split tsne based on orig.ident

### ISSUE THREAD

**Issue by aciecko** [satijalab/seurat#2471]
Hi--I have done an integrated analysis and used the split.by function to divide my tsne plot based on the orig.ident. However, I need to change the order in which the plots appear on the graph (from left to right). 

As an example:
DimPlot(cd8, reduction = "tsne", split.by = "orig.ident")

![image](https://user-images.githubusercontent.com/54730926/71708866-b493b480-2db9-11ea-9657-b770601e1861.png)

Can I make 12wk appear on the right and 7wk appear on the left?

Thank you!

**Comment by AndyR2** [comment]
try adding to the DimPlot call
`order = c("7wk", "12wk")`

also, learn to use Help tab in RStudio to see R Documentation for Seurat DimPlot.

**Comment by andrewwbutler** [comment]
Hi,

The ordering here is affected by the factor levels of the variable you are splitting on. You could try reordering the levels on `orig.ident`. E.g.

```R
cd8$orig.ident <- factor(x = cd8$orig.ident, levels = c("7wk", "12wk"))
DimPlot(cd8, split.by = "orig.ident")
```

**Comment by aciecko** [comment]
Thank you for the help. I really appreciate it. I know it was a naïve question.

**Comment by hoyu310** [comment]
Hi,
What about controlling the font sizes of the split.by plot titles (i.e. 7wk, 12wk in this post)? I tried both the ggplot theme(plot.title = element_text(size=)) and Seurat FontSize(main=) but they both don't seem to affect the split.by plot titles.

**Comment by andrewwbutler** [comment]
Hi,

The `split.by` plots are using `facet_wrap` so you can modify the title themes as follows:

```R
p = DimPlot(pbmc_small, split.by = "groups")
p + theme(strip.text = element_text(size=25))
```

**Comment by hoyu310** [comment]
Thanks a lot for your help, it works!

**Comment by asbhuiya** [comment]
Hi,
I have five groups and 'split.by' function give me five graphs. But i want to include only 3 or 4 how can I do this.

**Comment by AndyR2** [comment]
asbhuiya,
do want the dataset represented as just 3 replicates?  If so, use some metadata (or create it) column that sees the dataset as 3 samples.
or
do want to subset the dataset computationally?   If so, create a new Robj with just the samples you want using subset function.

**Comment by asbhuiya** [comment]
AndyR2, 
i keep 5 groups but want to show only 3 or 4 groups in the graphs. How can i do this. please provide me code. 
thanks.

**Comment by AndyR2** [comment]
here is how you would create a new metadata column, based on existing metadata (e.g. "orig.ident).   In the example, I had six replicates under "orig.ident" that I wanted to plot as two "groups".   

`#Add new meta.data column called "group" 

#Extract a text string from metadata column "orig.ident" Start 1, End 2
group <- substring(Ma_p0 merge@meta.data$orig.ident, 1,2)

#Create new metadata column and add as "group"
names(group) <- rownames(Ma_p0 merge@meta.data)
Ma_p0 merge <- AddMetaData(Ma_p0 merge, metadata = group, col.name = "group")

#example data 

![image](https://user-images.githubusercontent.com/33207886/90808881-8ece0800-e2d5-11ea-9874-39fbce415775.png)
