### ISSUE TITLE
Merging Seurat objects from multiple sequencing runs

### ISSUE THREAD

**Issue by kmowsiany** [satijalab/seurat#2472]
Hi, I wanted to seek clarification about how to analyze libraries sequenced on more than one flow cell. I have 9 libraries that were randomized and run on two NextSeq runs to get greater depth. I followed the advice from 10x on how to preprocess these data and end up with two matrices per library. (https://kb.10xgenomics.com/hc/en-us/articles/360000930812-Can-I-combine-data-from-multiple-sequencing-runs-for-the-same-10x-library-). However, I can’t properly merge them in Seurat because the merge function enforces cell names to be different. In my understanding, for a given cell that was barcoded, some of its transcripts ended up on sequencing run 1 and others on run 2, but in reality they came from the same cell. Right now when I merge I just end up with an object with double the number of cells, named with _1 and _2. Is there a way to combine these data so I get all features assigned for each cell? Or, I might have done this totally wrong and I’ll have to treat the objects simply as replicates.  Any advice appreciated!

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hope this helps.  How did you end up with two matrices per library?  As detailed in the link from 10X that you posted when you specify multiple fastq paths from multiple sequencing runs in the same `count` run it will combine samples run on multiple flowcells into a single sample output.  This should solve the issue of multiple sample names.

Can you provide some more information?

Thanks,
Sam

**Comment by timoast** [comment]
As Sam said, you need to process the data differently upstream of Seurat. If you need to combine data from multiple sequencing runs you can either concatenate the fastqs or specify multiple fastq files when running cellranger count. See the [cellranger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger) docs for more information.

**Comment by naumenko-sa** [comment]
Sometimes it is faster to merge counts than to merge fastq and re-calculate:

```
# parse cell_ids: fc_id-CELL_ID, remove fc_id
read_mtx <- function(flowcell){
    mtx <- readMM(paste0("data/", flowcell, "/matrix.mtx"))
    barcodes <- read_csv(paste0("data/", flowcell, "/barcodes.tsv"), col_names = "cell_id")
    barcodes$cell_id <- str_split(barcodes$cell_id, "-", 2, simplify = T)[,2]
    colnames(mtx) <- barcodes$cell_id
    features <- read_csv(paste0("data/", flowcell, "/features.tsv"), col_names = "feature_id")
    rownames(mtx) <- features$feature_id
    return(mtx)
}

# add columns to mtx given a vector of all_cells
# reorder columns
complement_mtx <- function(mtx, all_cells){
    m1 <- Matrix(0,
                 nrow = nrow(mtx),
                 ncol = length(all_cells) - ncol(mtx))
    colnames(m1) <- setdiff(all_cells, colnames(mtx))
    mtx <- cbind(mtx, m1)
    mtx <- mtx[,all_cells]
    return(mtx)
}

FC1.mtx <- read_mtx("FC1")
FC2.mtx <- read_mtx("FC2")

all_cells <- c(colnames(FC1.mtx), colnames(FC2.mtx)) %>% unique()

FC1.mtx <- complement_mtx(FC1.mtx, all_cells)
FC2.mtx <- complement_mtx(FC2.mtx, all_cells)

merged.mtx <- FC1.mtx + FC2.mtx

writeMM(merged.mtx, "data/matrix.mtx")
fwrite(list(all_cells), "data/barcodes.tsv")
fwrite(list(rownames(merged.mtx)), "data/features.tsv")
```
Then use Read10X and CreateSeuratObject

**Comment by timoast** [comment]
@naumenko-sa that would not collapse UMIs correctly

**Comment by naumenko-sa** [comment]
thanks, you are right, we need UMIs from all flowcells when counting before Seurat.
