### ISSUE TITLE
IntegrateData Out of Bounds

### ISSUE THREAD

**Issue by afichtenholtz** [satijalab/seurat#2473]
Trying to integrate data sets using SCTransform and keeping all intersecting genes. Receiving out of bounds error. Integration using standard workflow works fine. Command history:

> Donor_01 <- Read10X_h5("Reyfman/GSM3489182_Donor_01_filtered_gene_bc_matrices_h5.h5")
> Donor_01 <- CreateSeuratObject(Donor_01, project="Donor_01")
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
> Donor_02 <- Read10X_h5("Reyfman/GSM3489185_Donor_02_filtered_gene_bc_matrices_h5.h5")
> Donor_02 <- CreateSeuratObject(Donor_02, project="Donor_02")
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
> Donor_01 <- SCTransform(Donor_01, return.only.var.genes = FALSE, min_cells=1)
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 22113 by 5437
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 5437 cells
  |==================================================| 100%
Found 13 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 22113 genes
  |==================================================| 100%
Computing corrected count matrix for 22113 genes
  |==================================================| 100%
Calculating gene attributes
Wall clock passed: Time difference of 2.582456 mins
Determine variable features
Set 3000 variable features
Place corrected count matrix in counts slot
Centering data matrix
  |==================================================| 100%
Set default assay to SCT
There were 50 or more warnings (use warnings() to see the first 50)
> Donor_02 <- SCTransform(Donor_02, return.only.var.genes = FALSE, min_cells=1)
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 22275 by 3858
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 3858 cells
  |==================================================| 100%
Found 24 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 22275 genes
  |==================================================| 100%
Computing corrected count matrix for 22275 genes
  |==================================================| 100%
Calculating gene attributes
Wall clock passed: Time difference of 1.881287 mins
Determine variable features
Set 3000 variable features
Place corrected count matrix in counts slot
Centering data matrix
  |==================================================| 100%
Set default assay to SCT
There were 50 or more warnings (use warnings() to see the first 50)
> Donor.list = list(Donor_01,Donor_02)
> Donor.features <- SelectIntegrationFeatures(object.list=Donor.list, nfeatures=3000)
Donor.list <- PrepSCTIntegration(object.list=Donor.list, anchor.features=Donor.features)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 01s
> Donor.anchors <- FindIntegrationAnchors(object.list = Donor.list, normalization.method = "SCT", anchor.features=Donor.features)
Finding all pairwise anchors
   |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 11422 anchors
Filtering anchors
	Retained 9618 anchors
Extracting within-dataset neighbors
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 35s
Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
> to_integrate <- Reduce(intersect,(lapply(Donor.anchors@object.list, rownames)))
> Donor.integrated <- IntegrateData(anchorset = Donor.anchors, normalization.method = "SCT", features.to.integrate = to_integrate)
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Error in GetAssayData(object = object, assay = assay, slot = "data")[features.integrate,  : 
  subscript out of bounds

**Comment by satijalab** [comment]
Closing as this is also brought up in #2590 , we are looking into this now
