### ISSUE TITLE
DoHeatmap issue

### ISSUE THREAD

**Issue by Seojoonho001** [satijalab/seurat#2474]
Hello community,
While following the immune cell integration protocol, I came into a few issues.
I am using my own immune cell dataset. 

I am trying to make a heatmap of CCL2, FCRL and TMEM119 genes, grouped by WT vs KO.
I was successful until it showed an error message that says the following:
![current heatmap](https://user-images.githubusercontent.com/58821934/71851107-c91aca00-30a3-11ea-8595-6e5abffb43f2.jpg)

"The following features were omitted as they were not found in the scale.data slot for the integrated assay: Tmem119"
 ![heatmap issue](https://user-images.githubusercontent.com/58821934/71851117-cddf7e00-30a3-11ea-8545-93fdc827bb12.jpg)

At first,  it seemed like it was a scaling issues.
So I have tried different scaling codes (separately, no scaling twice/thrice) to include all genes to scale, not just the ones found in FindVariableFeatures.
![scale codes](https://user-images.githubusercontent.com/58821934/71851097-c1f3bc00-30a3-11ea-8379-11eea1d5c702.jpg)

Yet, the problem persists...I cannot get Tmem119 to show up on my heatmap. The gene is in the RNA assay, but not in integrated assay. Does this mean that Tmem119 gene is not included in the integrated assay?  If so, how can I include it in the integrated assay? It also looks like I have many other genes that don't show up in the integrated assay just like Tmem119...is there any way I can include all the genes in the integrated assay? 

I have wanted to try **features.to.integrate** argument, but I am not sure how...how would I define features.to.integrate?
Right now I am using the integration codes of 
![integrate code](https://user-images.githubusercontent.com/58821934/71851502-b654c500-30a4-11ea-883a-5cd5436dcd1f.jpg)

I hope I can get some answers-I have tried many suggested solutions to no joy :(

Thank you so much for your help!

Joon

**Comment by timoast** [comment]
You can use the `features.to.integrate` parameter to set the features to integrate. See the documentation for `IntegrateData`. Note that we do not recommend plotting integrated data, for reasons explained in several closed issues.

**Comment by Seojoonho001** [comment]
Thank you timoast,
I was able to use the features.to.integrate to integrate all cells.
Also, as per your recommendation, I am using RNA assay for plotting now.

I have another question, related to this. If I wanted to generate a heatmap of only 1 cluster out of all the clusters, does cells function in DoHeatmap allow this?

For example, I have renamed clusters as the following: 
![Ident cell](https://user-images.githubusercontent.com/58821934/71871208-7f9f9e80-30e6-11ea-83ca-d2e2c7b22af2.jpg)

and I want to generate a heatmap of genes c(Ccl2....) only in the "Microglia" cluster.

I have subset "Microglia", as shown here:
![heatmap only microglia](https://user-images.githubusercontent.com/58821934/71871317-d0af9280-30e6-11ea-9520-ef71a4504fe2.jpg)

When I run the code I get the error :
"Error in GetAssayData(object = object, slot = slot)[features, cells, drop = FALSE] : 
  invalid subscript type 'S4'"

Would you help me solve this issue please?

Thank you for all your hard work.

Joon

**Comment by timoast** [comment]
The `cells` argument should be a vector of cell names, not a Seurat object. If you use `cells=colnames(mi)` it should work
