### ISSUE TITLE
VlnPlot Seurat v3 add to quartile/statistic information

### ISSUE THREAD

**Issue by molybdenumt** [satijalab/seurat#2475]
I want to compare the gene expression of two conditions. Is there a way I can provide statistics on it like p-value between the two conditions and/or quartile information for or instead of the vlnplot? 

I found this for VlnPlot https://github.com/satijalab/seurat/issues/764. But the function do,return = T is not available in the new seurat. 

I would like something like the example that I quickly put together. 

![Example](https://user-images.githubusercontent.com/55332337/71857709-64f50780-309d-11ea-916e-eac42eaa3b7a.png)

**Comment by timoast** [comment]
You don't need the `do.return` argument in v3, a ggplot object is returned by default

**Comment by molybdenumt** [comment]
I already tried the code from https://github.com/satijalab/seurat/issues/764 without do.return and it does not work.  In the comment it says "You will need to set do.return = TRUE to be able to modify the plot," that's why I thought we need to have a specific line of code for the code to work. 

Since this doesn't work, is there a way I can provide statistics on it like p-value between the two conditions and/or quartile information for or instead of the vlnplot?

This is the code I tried
```
median.stat <- function(x){
  out <- quantile(x, probs = c(0.5))
  names(out) <- c("ymed")
  return(out) 
}
VlnPlot(sample, features = c("CD3D","CD14"), group.by = "stim") +stat_summary(fun.y = median.stat, geom='point', size = 10, colour = "blue") 
```

**Comment by timoast** [comment]
What is the error that you get?

**Comment by timoast** [comment]
Actually for VlnPlot you will need to set `combine=FALSE`, then modify the plot, then use `CombinePlot` to combine the modified plots

**Comment by molybdenumt** [comment]
It doesn't have an error. It just does not show the median. I tried combine = FALSE and CombinPlot. ```
median.stat <- function(x){
  out <- quantile(x, probs = c(0.5))
  names(out) <- c("ymed")
  return(out) 
}
plot = VlnPlot(soupx62, features = c("CD3D","CD14"), group.by = "stim", combine = F) + stat_summary(fun.y = median.stat, geom='point', size = 10, colour = "blue") 
CombinePlots(plot)
````
No graph is shown and I get:
> CombinePlots(plots = plot, ncol = 1)
NULL
> CombinePlots(plot)
NULL

**Comment by vertesy** [comment]
It works for me as below, including a wrapper

```R
# draw median for a single plot
MedianVioSeu <- function() stat_summary(fun.y = median, geom='point', size = 15, colour = "darkred", shape = 95)

# for a list of ggplots
apply.MedianVioSeu.and.combine <- function(ls.ggplots=pl$A) {
  for (i in 1:l(ls.ggplots)) ls.ggplots[[i]] = ls.ggplots[[i]]+MedianVioSeu()
  return(CombinePlots(ls.ggplots, legend = 'none'))
}

goi = c("GeneSymbol1", "GeneSymbol2", "GeneSymbol3")
pl=NULL
pl$A <- VlnPlot(object = combined.obj, features = goi, group.by =  'v.project'
                , pt.size = 0, assay = "RNA", log = T, combine = F) 
pl$A <- apply.apply.MedianVioSeu.and.combine(pl$A)
pl$A

```

**Comment by molybdenumt** [comment]
hi vError in l(ls.ggplots) : could not find function "l"


> It works for me as below, including a wrapper
> 
> ```r
> # draw median for a single plot
> MedianVioSeu <- function() stat_summary(fun.y = median, geom='point', size = 15, colour = "darkred", shape = 95)
> 
> # for a list of ggplots
> apply.MedianVioSeu.and.combine <- function(ls.ggplots=pl$A) {
>   for (i in 1:l(ls.ggplots)) ls.ggplots[[i]] = ls.ggplots[[i]]+MedianVioSeu()
>   return(CombinePlots(ls.ggplots, legend = 'none'))
> }
> 
> goi = c("GeneSymbol1", "GeneSymbol2", "GeneSymbol3")
> pl=NULL
> pl$A <- VlnPlot(object = combined.obj, features = goi, group.by =  'v.project'
>                 , pt.size = 0, assay = "RNA", log = T, combine = F) 
> pl$A <- apply.apply.MedianVioSeu.and.combine(pl$A)
> pl$A
> ```

I keep getting the Error in l(ls.ggplots) : could not find function "l". Is it a different package that I don't have? 
These are what I loaded
library(Seurat)
library(sctransform)
library(dplyr)
library(cowplot)
theme_set(theme_cowplot())
library(ggplot2)
require("ggrepel")

**Comment by vertesy** [comment]
Sorry, `l` us just my alias for `length`. I fixed the code.

**Comment by molybdenumt** [comment]
I got it to run . I only got the median line. Do you know if I can get a box for quartile information? 
![plot_zoom_png](https://user-images.githubusercontent.com/55332337/78157792-49c43a80-73f5-11ea-8613-a6aa257e7c03.png)

**Comment by vertesy** [comment]
Great! This function only does median.

**Comment by molybdenumt** [comment]
Thank you! I'll try to modify it to get a box function. But this is super helpful. Thank you again.

**Comment by Yale73** [comment]
@molybdenumt Here is a good example to add the significant p-val even though they don't have the box. https://www.biostars.org/p/458261/

--Yale

**Comment by KBoostan** [comment]
Is a violin plot the only visualization graph you can generate p value for? I am trying to generate one for a feature scatter plot and it's giving me an error. 
FeatureScatter(object = TotCol, feature1 = 'PDGFRA', feature2 = 'COL3A1', group.by = "group", shuffle = TRUE, cols = c("red", "blue")) + stat_compare_means(aes(group = "group")
![Screen Shot 2021-12-09 at 10 52 37 AM](https://user-images.githubusercontent.com/54972577/145457881-413d21f1-0aef-4749-a0b6-6be4fa20c3fc.png)

**Comment by mitralaboratory** [comment]
ow do I modify this code to include median value line on the generated violin plots
## Cluster gene expression map 0.2 using raw count
```{r}
library(patchwork)
library(cowplot)
library(ggplot2)
library(RColorBrewer)
library(Seurat)
gene_list <- c("NDUFV1","NDUFV2","NDUFS1","NDUFS2","NDUFS3","NDUFS8","NDUFS7",
               "MT-ND1","MT-ND2","MT-ND3","MT-ND4","MT-ND4L","MT-ND5","MT-ND6")

data <- seurat_02
DefaultAssay(data) <- "RNA"
plot_list <- list()
for (i in gene_list) {
  plot_list[[i]] <- FeaturePlot(data, features = i, split.by = "sample", cols = c("grey","blue"))
}
vplot_list <- list()
data$clusternum <- Idents(data)
for (i in gene_list) {
  vplot_list[[i]] <- VlnPlot(data, features = i, split.by = "sample", group.by = "clusternum",
    pt.size = 0, combine = FALSE) +
    stat_summary(fun = median, geom='point', size = 10, colour = "blue")
}
for (i in gene_list) {
  ggsave(paste0("/home/mitralab/featureplot/","map_", i, "_0.2_raw.pdf"),plot = plot_list[[i]], width = 11, height = 8.5)
  pdf(paste0("/home/mitralab/vlnplot/","vin_", i, "_0.2_raw.pdf"), width = 11, height = 8.5)
   print(vplot_list[[i]])
  dev.off()
}
