### ISSUE TITLE
Plot single colour gradient when using DotPlot w/split.by

### ISSUE THREAD

**Issue by GBeattie** [satijalab/seurat#2478]
Hey,

I'm plotting a DotPlot with the split.by argument (as below). The split.by argument requires a colour vector to assign colours to each group, however having each sample have a different colour makes it a little hard to determine differences accurately. Is it possible to override this colour variable with a single colour scale (e.g. red/blue)? I've tried adding "+ scale_color_gradient(low = "red2",  high = "mediumblue")" to the line below but get "Error: Discrete value supplied to continuous scale" in response.

Thanks in advance for any assistance!

DotPlot.UT.CD8 <- DotPlot(temp, features = temp@assays[["integrated"]]@var.features, split.by = "expansion", cols = viridis(10)) + RotatedAxis()

![image](https://user-images.githubusercontent.com/11555832/71892740-a808b680-3141-11ea-9c15-69f1117d7ed2.png)

**Comment by andrewwbutler** [comment]
Hi,

Are you sure you need `split.by` here? It looks like everything is `Cytotoxic CD_*`. If you just want to group the cells by a variable other than the current idents, you could use the `group.by` parameter.
