### ISSUE TITLE
Is there a replacemnt/recomendation for AddImputedScore function

### ISSUE THREAD

**Issue by Thomas-Jackson-2019** [satijalab/seurat#2479]
Is there a replacemntfor AddImputedScore function in Seurat 2 or is there a recomended way of dealing with dropout in seurat3.

**Comment by satijalab** [comment]
We have a wrapper to the ALRA package (https://www.biorxiv.org/content/10.1101/397588v1.full.pdf), see 
https://satijalab.org/seurat/vignettes.html
