### ISSUE TITLE
AddModuleScore Error

### ISSUE THREAD

**Issue by dylanmr** [satijalab/seurat#248]
I am attempting to create a stemness score for my single cell dataset. I have obtained a list of stemness genes, only included genes that are found in my filtered dataset and am attempting to pass it through the AddModuleScore function. However, I keep running into this error: 

Error in apply(X = object@data[genes.use, ], MARGIN = 2, FUN = mean) :
  dim(X) must have a positive length

I am unsure how to troubleshoot this. If you can please let me know how I can work around this that would be greatly appreciated.

**Comment by leonfodoulian** [comment]
Hi,

I have submitted a pull request to fix this issue. You can check [here](https://github.com/satijalab/seurat/pull/251) for more details. Once the changes are implemented, don't forget to download the latest [develop version of Seurat](http://satijalab.org/seurat/devinstall.html) to be able to perform the analysis you are willing to perform. 

Best,
Leon
