### ISSUE TITLE
How to combine the tSNE?

### ISSUE THREAD

**Issue by Tingting8305** [satijalab/seurat#2481]
Dear Seurat team,
In my analysis of scRNAseq, i do two-step clustering. In the first clustering, i find some raw clusters. And then, i focus on 1-2 of the raw clusters and do the fine clustering to find some subsets. Can i plot all the clusters together in one tSNE images?
Thank you very much!
Ting

**Comment by timoast** [comment]
You will need to combine the metadata information such that you have <coarse_cluster>_<fine_cluster>. For example: `obj$class <- paste0(obj$coarse_cluster, "-", obj$fine_cluster)`
