### ISSUE TITLE
Read10X() issues

### ISSUE THREAD

**Issue by ebutka** [satijalab/seurat#2483]
Hi,

I found a small bug in the Read10X function: when the barcodes/features/matrix files are gunzipped, the error "Barcode file missing" is output unless features.tsv is renamed to genes.tsv. This is an inappropriate error message as the file is not missing, and this issue does not arise when either the genes/features file is named genes.tsv or all three files are gzipped. I am able to make the appropriate changes and initiate the Seurat object, I just thought I would let you know about this bug. I am running the latest versions of both cellranger and Seurat.

**Comment by andrewwbutler** [comment]
Hi,

In the `Read10X` function, we distinguish between output generated with cellranger 2 versus cellranger 3 based on the presence or absence of the `genes.tsv` file (as that was renamed to `features.tsv.gz` in cellranger 3). I wouldn't recommend uncompressing those files as that's not necessary for analysis in R/Seurat and we do say in the documentation example for `Read10X` that we're expecting the files to be compressed for cellranger 3. 
> `list.files(data_dir) # Should show barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz` 

However, we can make the error messages better reflect that and we'll be sure to update those before the next release.
