### ISSUE TITLE
generating heatmap from AverageExpression results 

### ISSUE THREAD

**Issue by Seojoonho001** [satijalab/seurat#2486]
Hi Seurat community,

I was following the integration tutorial with my own data, and I have successfully created heatmaps of genes of my interest, with WT vs KO information in it. 
![current heatmap](https://user-images.githubusercontent.com/58821934/71990930-48261480-3202-11ea-925a-a5ee79333f1f.jpg)

I have used the following codes for the heatmap.
![1](https://user-images.githubusercontent.com/58821934/71990972-5d02a800-3202-11ea-8f37-53925be1eb4b.jpg)

However, the issue is, that this heatmap shows every cell that is used by cells= function, but one of my issues right now is that the number of KO cells vs WT cells are different, so I would like to create a heatmap with averaged expression...like this 
![2](https://user-images.githubusercontent.com/58821934/71991151-ae129c00-3202-11ea-9334-da2452087dea.jpg)

So I used AverageExpression function, as the following: 
![3](https://user-images.githubusercontent.com/58821934/71991762-dbf7e080-3202-11ea-8b26-2e8f8f264029.jpg)

However, I am not sure what codes to use to create heatmaps with Averaged Expression object. I tried some codes to add Averageexpression to immune.combine metadata, but it gave me errors saying the rows are different and etc...

Could you guys please help me figure out how to create heapmaps using the Averageexpression with WT and KO information in it? The tutorial doesn't have this part..

Thank you guys for all your help!

Joon

**Comment by timoast** [comment]
You would need to find the average expression in each cell type and each condition separately, I think here you probably just have the average expression in each cell type. First combine the cell type and treatment information so that you have Microglia_KO, Microglia_WT, etc. then run AverageExpression and you should have the information needed to create the heatmap you want.

**Comment by satijalab** [comment]
Note that AverageExpression actually includes an add.ident argument that does exactly what Tim suggested above, so you could say

```avgexp = AverageExpression(immune.combined, return.seurat = T, add.ident = 'Genotype')```

You can then treat this as a regular Seurat object to generate Heatmaps, plots, etc. on average data

**Comment by lkotiwari** [comment]
Hi, 
I am having the same issue. I want to make a heatmap of selected genes of a specific cluster (not all clusters). I am getting a similar plot (As above @ Seojoonho001 ). I want to plot  AveragEexpression but it is not working. Can anyone help?

**Comment by karabicicim** [comment]
Could anyone please explain the necessary steps one by one when I try it it just gives me an average of my subsets.
