### ISSUE TITLE
How to read *.bam and *.bam.bai files into Seurat

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#2488]
I download the whole brain data of mouse, and unfortunately, they're *.bam and *.bam.bai files.

Could you help me read these files in Seurat, or process them and then read in Seurat?

**Comment by timoast** [comment]
This is not supported in Seurat, you will need to create a count matrix before loading data into Seurat.

**Comment by biobug16** [comment]
Hi @grimwoo and @timoast 
Can you please help and guide me too? How did you resolve this issue, as I am also confused and unable to find a way to convert my bam file to count matrix.

I will appreciate your help.
Thanks
