### ISSUE TITLE
merging seurat objects while conserving ident

### ISSUE THREAD

**Issue by andrea-de-micheli** [satijalab/seurat#249]
Hello,

Merging two seurat object seem to rename all of the ident values. How can I conserve the ident values of the respective seurat objects while merging them together?

What I mean:

s1 = RenameIdent(s1, old.ident.name = "old name", new.ident.name = "s1")
s2 = RenameIdent(s2, old.ident.name = "old name", new.ident.name = "s2")

s_combined = MergeSeurat(s1,s2)

However s_combined@ident doesn't conserve the s1 and s2 names.

Thank you!

**Comment by andrewwbutler** [comment]
Hi,

One way to retain the `ident` values is to store them in the `meta.data` slot using `StashIdent`. The `meta.data` dataframe elements are preserved through the merge process.

**Comment by andrea-de-micheli** [comment]
Thank you very much! It's exactly what I ended up doing.
Would be easier if in a future version of Seurat MergeSeurat() could conserve ident.

**Comment by satijalab** [comment]
We had this originally, but it wound up being unclear where the idents came from after significant further analysis. We suggest users explicitly store information as Andrew suggested before a merge. It adds a few more lines of code but enables greater clarity downstream.
