### ISSUE TITLE
How to make a 'summary' gene; How to print all transcripts in a cluster

### ISSUE THREAD

**Issue by NaomiCroft** [satijalab/seurat#2491]
Hi,
I have been following the Satija Lab tutorial to analyse my single cell transcriptomics data in R. I have a seurat object and have been able to make lists of differentially expressed genes in different cell types.

I have two separate questions:
I have about 20 immunoglobulin genes differentially expressed in a B cell cluster. I can visualise the expression of these genes in a dotplot using this function (p.s. Many of the Ig are not properly annotated as this is a non-model organism, so I just have the LOC location, p.p.s. I am aware cd8a is not an Ig):

DotPlot(allsample.data.seurat, features = c("cd8a", "LOC115559408", "LOC115549499", "LOC115543856", "LOC115543836", "LOC115544139", "LOC115559330", "LOC115543835", "LOC115543484", "LOC115554304", "swap70", "cd79a", "cd79b", "LOC115559315", "LOC115543501", "LOC115559451", "LOC115543493", "mef2c", "LOC115543867")) + RotatedAxis()

![image](https://user-images.githubusercontent.com/48726315/72051610-eaf29780-32c3-11ea-91f1-df07ebf75abd.png)

Question 1) Is it possible to combine all of the immunoglobulin genes into one 'summary gene', which could then be displayed on the dotplot?

Question 2) Is it possible to print all the transcripts expressed by a cluster (not just the differentially expressed ones)? My plasma cell cluster has 1915 transcripts. I want to find out what proportion of these transcripts are immunoglobulin genes. 

Thanks for your help!
Naomi

**Comment by MoaES** [comment]
Not from the team, but I may be able to help you with the summary gene; Look into [AddModuleScore](https://rdrr.io/github/satijalab/seurat/man/AddModuleScore.htm): 

Your code could look something like this:

### Create list with immunoglobulin genes
`immunoglobulin_genes = list(c("cd8a", "LOC115559408", "LOC115549499", "LOC115543856", "LOC115543836", "LOC115544139", "LOC115559330", "LOC115543835", "LOC115543484", "LOC115554304", "swap70", "cd79a", "cd79b", "LOC115559315", "LOC115543501", "LOC115559451", "LOC115543493", "mef2c", "LOC115543867"))`

### Set module score
`allsample.data.seurat <- AddModuleScore(allsample.data.seurat, features = immunoglobulin_genes, name = "Immunoglobulin_genes")`

### Plot
`DotPlot(allsample.data.seurat, features = "immunoglobulin_genes") + RotatedAxis()`

**Comment by NaomiCroft** [comment]
Hi, Thanks for replying!
When I try your suggestion, I get the an error message. This is what I imput:

#Create list with immunoglobulin genes
immunoglobulin_genes <- list(c("cd8a", "LOC115559408", "LOC115543856", "LOC115543836", "LOC115544139", "LOC115559330", "LOC115543835", "LOC115543484", "LOC115559315", "LOC115543501", "LOC115559451", "LOC115543493", "LOC115543867"))

#Set module score
allsample.data.seurat <- AddModuleScore(allsample.data.seurat, features = "immunoglobulin_genes", name = "immunoglobulin_genes")

#Plot
DotPlot(allsample.data.seurat, features = "immunoglobulin_genes") + RotatedAxis()

The error message reads:
Error in AddModuleScore(allsample.data.seurat, features = "immunoglobulin_genes", : The following feature lists do not have enough features present in the object: exiting...

Traceback:
2. | stop(paste("The following feature lists do not have enough features present in the object:", paste(names(x = which(x = !LengthCheck(values = features)))), "exiting..."))
-- | --
1. | AddModuleScore(allsample.data.seurat, features = "immunoglobulin_genes", name = "immunoglobulin_genes")
-- | --

I am not very R competent so hopefully I have just missed a minor issue here!

p.s. I tried all variations of immunoglobulin_genes being in and out of quotation marks

Thanks for your time,
Naomi

**Comment by timoast** [comment]
@NaomiCroft it should be `features = immunoglobulin_genes)` for all.
