### ISSUE TITLE
FindNeighbors() memory allocation error

### ISSUE THREAD

**Issue by mcfwoodruff** [satijalab/seurat#2492]
Hello,

I'm starting to establish a Seurat pipeline for our groups single-cell transcriptomics data, and I'm running into issues with the FindNeighbors function. Specifically, ComputeSNN() is failing and returning a std::bad_alloc error. I assume this is a memory allocation issue but didn't know enough about the function to really troubleshoot. Thanks for the help!

macOS 10.13.6, 128Gb DDR4
Rstudio 1.2.5019
R 3.6.1

Thanks!

**Comment by mcfwoodruff** [comment]
Following up, this is clearly a local memory issue. No action or response is needed. Thanks!

**Comment by hejincan** [comment]
> Following up, this is clearly a local memory issue. No action or response is needed. Thanks!

I get the same error whiling using FindNeighbors(). Could you please tell me how you fix this issus?

**Comment by mcfwoodruff** [comment]
The dataset you are working with is likely too large for your machine's local memory to handle when carrying out the process. If you run the function on a small subset of your data it should work.

**Comment by hejincan** [comment]
> The dataset you are working with is likely too large for your machine's local memory to handle when carrying out the process. If you run the function on a small subset of your data it should work.

 Thank you!
