### ISSUE TITLE
cell-cycle genes (cc.genes) for mouse

### ISSUE THREAD

**Issue by chansigit** [satijalab/seurat#2493]
Can you please provide a cell-cycle-associated genes for mouse? 
It is troublesome to convert human genes to mouse homolog every time.

**Comment by kmshort** [comment]
> Can you please provide a cell-cycle-associated genes for mouse?
> It is troublesome to convert human genes to mouse homolog every time.

I agree 100%

**Comment by satijalab** [comment]
Thanks. We don't provide different capitalizations because this gene list was developed on a human dataset, and we don't want to create ambiguity by suggesting its created from a mouse reference dataset. In practice however, we've found it works quite well for mouse also, and recommend the solution above.

**Comment by johnstonmj** [comment]
I was having issues with the BiomaRt solution connecting to Ensembl.
I found another conversion method using gprofiler2:

library(gprofiler2)
mmus_s = gorth(cc.genes.updated.2019$s.genes,   source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name
mmus_g2m = gorth(cc.genes.updated.2019$g2m.genes, source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name

**Comment by calinep** [comment]
Hello, 

Just as a follow up to the above question. 
I am essentially trying to reproduce some results from a dataset (AML cells) and I am trying to regress out some cell cycle genes as per Seurat Cell Cycle Scoring and Regression Vignette. One question is can I get some guidance on how I can convert the list of genes from human to mouse homolog genes? Prior to scoring and regression. Any help would be welcome!

**Comment by David-R-bird** [comment]
Here I have transformed Cell cycle genes from human to mouse,https://github.com/David-R-bird/Seurat_ccgenes/blob/main/mouse_cell_cycle_genes_2019.rds
mouse_cell_cycle_genes_2019 <- readRDS("~/mouse_cell_cycle_genes_2019.rds")

**Comment by auberginekenobi** [comment]
@David-R-bird (and anyone else using this set) heads-up that your list has renamed `g2m.genes` to `m.genes` and includes 'N/A' values which break Seurat's `CellCycleScoring` function (and also evade `is.na`)

**Comment by David-R-bird** [comment]
@auberginekenobi Thank you for your advices, the transform progress creat N/A, now the updated list in https://github.com/David-R-bird/Seurat_ccgenes/blob/main/mouse_cell_cycle_genes_2019.update.rds
