### ISSUE TITLE
the CLUSTER IDs over MULTIPLE EXPERIMENTS

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2497]
Dear all, 

I would like to ask you please for a suggestion : we do have a set of multiple scRNAseq experiments CTRL and STIM (in the same tissue) over 4 months i.e:  

**CTRL_1month, CTRL_2months, CTRL_3months, CTRL_4months**

**STIM_1month, STIM_2months, STIM_3months, STIM_4months**

and I have done the analysis with SEURAT by comparing : 

**a) CTRL1_month vs STIM_1month**

**b) CTRL2_month vs STIM_2month**

however, for each comparison,  the CLUSTER NUMBERS differ i.e. : 

the CLUSTER_NUMBERS of the comparison : **a) CTRL1_month vs STIM_1month**, 

differ from  the comparison :  **b) CTRL2_months vs STIM_2months** ...

is there any way we can keep the same CLUSTER NUMBERS over multiple comparisons (based on a few known markers of each cluster). 

We've looked also at the **CONSERVED MARKERS** between CLUSTERS in CTRL1 vs STIM1, and CTRL2 vs STIM2; the problem is that some of the clusters share many conserved markers ...

thanks a lot, 

-- bogdan

**Comment by satijalab** [comment]
Thanks for your question. This is the primary reason we developed methods for the integration of multiple datasets. By integrating them together, you can generate a single clustering that enables consistent downstream comparison. Please see:
https://satijalab.org/seurat/v3.0/integration.html
and
https://satijalab.org/seurat/v3.1/immune_alignment.html

for examples
