### ISSUE TITLE
Subclustering after fastMNN batch correction

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#2498]
Hi,
I was wondering what would be the best approach to perform clustering on a subset of cells pulled out from a MNN-batch-corrected object.
I used fastMNN from SeuratWrappers to perform a MNN batch-correction and perform an integrated analysis.
Then I subsetted a cluster of cells and wanted to perform re-clustering.
Should I proceed with a Seurat workflow (standard or SCT) or do I need to perform another round of MNN batch-correction?
Thank you.

**Comment by satijalab** [comment]
Thanks for your question. Whether using fastMNN or Seurat v3, there is no single correct answer here. You can subset on the existing batch-corrected/integrated expression levels, or you can also re-run the batch correction analysis on the original data, but using only a subset of cells.

**Comment by QuanLG** [comment]
Hi @satijalab ,Based on the above discussion, my understanding is as follows:
1.  subset on the existing batch-corrected/integrated expression levels
        is that mean I don't need to re-scale? so I just RunPCA ,FindNeighbors,Runtsne, FindClusters 
2. re-run the batch correction analysis on the original data.
         Fisrt I subset cells of one cluster, this cells comes from three dataset, so I should FindVariableFeatures, ScaleData, then  merge three object and  batch correct; Finally RunPCA, FindNeighbors, FindClusters 

Is that all right? Thank you

**Comment by parvathisudha** [comment]
Hi @QuanLG,

I have the same question. Did you find a better way to dot this?
In my case, I am need to remove the erythrocyte clusters from the dataset, and I need to re-analyze the dataset. I am looking for the best method to do this. Any help is appreciated.

Thanks!
