### ISSUE TITLE
UpdateSeuratObject function fails to create nCounts_RNA in updated object

### ISSUE THREAD

**Issue by kmwinkley** [satijalab/seurat#2499]
After updating a Seurat version 2 object to a Seurat version 3 object using the UpdateSeuratObject function, I get the error:

Error in `[[.Seurat`(object, paste0("nCount_", assay)) : 
  Cannot find 'nCount_RNA' in this Seurat object

This occurs both on macOS and Linux when running Seurat 3.1.2 but not when running v 3.1.1. I'm wondering if this has to do with the update in 3.1.2:

-  Only run CalcN (generates nFeatures and nCounts) when counts changes

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting. This should now be fixed on the `develop` branch.

**Comment by chiwwong** [comment]
May I know whether this problem is fixed since 3.1.2? I am running the subset function to filter out cells using SeuratObject_4.0.4 Seurat_4.1.0. However, the nCounts_RNA is not found. I also tried manually adding a nCount slot there, but it does not work either. Thanks!
