### ISSUE TITLE
Error in Findclusters

### ISSUE THREAD

**Issue by Hoohm** [satijalab/seurat#25]
Hello,

I'm having an issue with FindClusters. it tries to write an edge file to /usr/lib/R/library instead of the Seurat folder. Here is the error:
```
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/usr/lib/R/library/edge_33895.txt': Permission denied
```

I'v tried locally and it seem changing line 185 from
seurat.dir <- paste0(strsplit(seurat.dir, "/")[[1]][0:(length(strsplit(seurat.dir, "/")[[1]])-1)], collapse = "/")
to
seurat.dir <- paste0(strsplit(seurat.dir, "/")[[1]][0:(length(strsplit(seurat.dir, "/")[[1]]))], collapse = "/")
solves it when I run it locally.

Running:
```
seurat.dir <- system.file(package="Seurat")
seurat.dir
seurat.dir <- paste0(strsplit(seurat.dir, "/")[[1]][0:(length(strsplit(seurat.dir, "/")[[1]])-1)], collapse = "/")
seurat.dir
seurat.dir <- paste0(seurat.dir, "/", sep = "")
seurat.dir
```
outputs:
```
> seurat.dir <- system.file(package="Seurat")
> seurat.dir
[1] "/usr/lib/R/library/Seurat"
> paste0(strsplit(seurat.dir, "/")[[1]][0:(length(strsplit(seurat.dir, "/")[[1]])-1)], collapse = "/")
[1] "/usr/lib/R/library"
> seurat.dir <- paste0(strsplit(seurat.dir, "/")[[1]][0:(length(strsplit(seurat.dir, "/")[[1]])-1)], collapse = "/")
> seurat.dir
[1] "/usr/lib/R/library"
> seurat.dir <- paste0(seurat.dir, "/", sep = "")
> seurat.dir
[1] "/usr/lib/R/library/"

```

I tried to rebuild Seurat using a local modified copy and the error is still there even though now it's different.
```

Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/usr/lib/R/library/Seurat/edge_33895.txt': Permission denied
```
So I still have to look for a real fix.
Any Idea why I get this issue?
Thanks for your help
Hoohm

PS: I'm on Arch

**Comment by Hoohm** [comment]
I solved it.
I usually install packages using sudo to avoid issues with packages and paths, etc...
Seems this time it bit me back.

**Comment by sentisci** [comment]
How did you solve it ? I am facing the same issue.Can you please explain ?

**Comment by andrewwbutler** [comment]
We recently released a patch that allows you to specify the location of these temporary files. See the temp.file.location parameter in FindClusters(). This would allow you to specify a location where you have the proper permissions and might resolve your issue.

**Comment by sentisci** [comment]
It works .Thanks
