### ISSUE TITLE
Getting the cells from the clusters Seurat has found

### ISSUE THREAD

**Issue by suvi93** [satijalab/seurat#2500]
Hello,
        I've been using Seurat v3.1 for single-cell analysis of mouse data. I've clustered the cells and Seurat has found 12 different clusters for my data. Now, I need to name the clusters so that I know which particular cell type has clustered where on the UMAP plot. Is there any other way to do this other than using the FindMarkers() function and then naming them based on the most differentially expressed gene in the cluster? Also, is there a way to retrieve the data where we know which cell/data has gone into the UMAP predicted cluster so that I can at least I know which cell type has gone where in the plot based on a metadata file I have for my data?

Thank you.

**Comment by AndyR2** [comment]
If you know already know marker genes for cell types, explore the identities using visualization tools
https://satijalab.org/seurat/v3.1/visualization_vignette.html

Try the interactive plotting function HoverLocator to ID cells with feature plots.

Also, you can output a list of barcodes [cells] for each cluster using
`object <-FetchData(object, vars = 'ident')
write.csv(object_Clu, "object_clusters.csv")`

**Comment by satijalab** [comment]
You can also use the `WhichCells` function to identify which barcodes fall into each cluster
