### ISSUE TITLE
Warning when integrating data

### ISSUE THREAD

**Issue by yjlee0331** [satijalab/seurat#2505]
Hi, I'm trying to integrate ctrl vs. disease, and when I use the IntegrateData function, I get this warning: 

Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Warning: Adding a command log without an assay associated with it

After this, once I go into 'counts' in my integrated assay via object@data$integrated@counts, everything keeps showing up as 0.

Can someone please help me out? Thank you

**Comment by satijalab** [comment]
Our integration works on normalized datasets in the data slot (or on the pearson residuals scale.data slot for the SCTransform workflow), which is why your counts slot is empty in the integrated assay. So there is nothing to worry about here.

**Comment by andrewwbutler** [comment]
I'll just add that the command log warning can be safely ignored here as well.

**Comment by kmshort** [comment]
I have another question on this same topic.

So am I correct, after reading what you said, that if the SCT workflow is used for integration, we can use the counts in pbmc@assays$SCT@counts for downstream analysis?

**Comment by andrewwbutler** [comment]
The values stored in the SCT assay counts slot represent the corrected UMI counts after SCTransform normalization. These values are not changed when running the integration workflow (i.e. in the integration workflow, we're correcting the Pearson residuals and those are what gets stored in the `scale.data` slot of the integrated assay).
