### ISSUE TITLE
Error in dimnamesGets(x, value) when running FindTransferAnchors function to identify anchors between the scATAC-seq dataset and the scRNA-seq dataset

### ISSUE THREAD

**Issue by yycunc** [satijalab/seurat#2506]
Hi, when I ran FindTransferAnchors function to identify anchors between the scATAC-seq dataset and the scRNA-seq dataset, I met the same issue

Error in dimnamesGets(x, value) :
invalid dimnames given for “Graph” object

My command is
transfer.anchors <- FindTransferAnchors(reference = sample2_3.combined_subset, query = x.atac, features = variable.genes, reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")

Here sample2_3.combined_subset is a seurat object integrating two scRNA batches, and x.atac is a seurat object of scATAC-seq data.

Would you please show me how to fix it?

Thanks

**Comment by satijalab** [comment]
The issue is that you are specifying the RNA assay in reference, but you mentioned that you had previously integrated the two objects. Assuming that you have done all processing on the integrated assay, you should therefore specify this one.
