### ISSUE TITLE
Integration of several samples

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#2510]
Hi all,

I want to integrate four human patient samples into one object using anchoring in Seurat, but my project is not finished and I know I will sequence more samples in the next months. Should I repeat the integration every time I have a new sample (integrating it with all the old ones) or can I integrate the new sample with the bulk of old ones? I include a schema of what I am suggesting below:

A+B>AB
A+B+C>ABC
A+B+C+D>ABCD

or 

A+B>AB
AB+C>ABC
ABC+D>ABCD

Hope it makes sense!

**Comment by timoast** [comment]
Yes you can add samples to an integrated dataset, this is actually what happens internally when integrating multiple samples
