### ISSUE TITLE
SCTransform: Error in data.use[features, ] : no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by KASHISH72** [satijalab/seurat#2511]
I am trying to run SCTransform integration on our data and at the RunPCA step it is giving me error.
Here is the error it outputs when I run the RunPCA step
Error in data.use[features, ] : no 'dimnames' attribute for array
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 3000 features requested have not been scaled (running reduction without them):

According to the vignette SCTransform does not require the command to ScaleData. And when I used the option to ScaleData, RunPCA command worked.
Can you please give your input on this.

Kashish

**Comment by satijalab** [comment]
Thanks for the question. You are correct that the SCTransform workflow does not require you to run ScaleData. Running SCTransform should fill the object@scale.data slot.

Can you try the following? I'll assume your object is named pbmc, and has 15,000 cells

after you run SCTransform (i.e `pbmc = SCTransform(pbmc)`)

Can you let us know:
1. What are the dimensions of the scale data slot (i.e. `dim(object[["SCT"]]@scale.data)`)
it should be 3,000 x 15,000
2. What is the active assay (i.e `DefaultAssay(pbmc)` )
it should be 'SCT'

If (1) and (2) aren't correct, then something is going wrong with SCTransform. If (1) and (2) are correct, then there's likely an error in your code somewhere after running SCTransform and performing integration. Let us know and feel free to reopen this issue

**Comment by shaln** [comment]
Hello. 

1. I am having a similar issue with RunPCA after SCTransform. I have 3 samples, and I SCTransformed them individually, before merging all 3 samples as one single Seurat object. I then ran RunPCA but had the following error: 

`Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.`

The active assay is 'SCT', and I understand that I do not need to run FindVariableFeatures since it's part of SCTransform, so I'm unsure why I am getting this error. Below is the code I used:

```
# Import SCE objects that have been QC-ed using scater
sample_list <- list()
sample_list[[1]] <- contA.data.sce_filtered
sample_list[[2]] <- contB.data.sce_filtered
sample_list[[3]] <- cont1.data.sce_filtered
names(sample_list) <- c("Sample 1", "Sample 2, "Sample 3")

# Remove genes not found in ALL datasets
sample_common.genes <- intersect(rownames(sample_list[[1]]), rownames(sample_list[[2]]))
sample_common.genes <- intersect(samplel_common.genes, rownames(sample_list[[3]]))
for (i in names(sample_list)){
  sample_list[[i]] <- (sample_list[[i]])[sample_common.genes,]
}

# Import datasets into Seurat
sample1.seurat <- as.Seurat(sample_list[[1]], counts = "counts", data = NULL, project="sample1")
sample2.seurat <- as.Seurat(sample_list[[2]], counts = "counts", data = NULL, project="sample2")
sample3.seurat <- as.Seurat(sample_list[[3]], counts = "counts", data = NULL, project="sample3")

# Run SCtransform on each of the Seurat object
sample1.seurat <- SCTransform(sample1.seurat, vars.to.regress = "subsets_Mito_percent")
sample2.seurat <- SCTransform(sample2.seurat, vars.to.regress = "subsets_Mito_percent")
sample3.seurat <- SCTransform(sample3.seurat, vars.to.regress = "subsets_Mito_percent")

# Merge all samples into one Seurat object
sample_seurat <- merge(x = sample1.seurat, y = c(sample2.seurat, sample3.seurat), add.cell.ids = c("sample1", "sample2, "sample3"), project = "sample",merge.data = TRUE)
sample_seurat <- AddMetaData(sample_seurat, sample_seurat@active.ident, col.name = "orig.ident")
sample_treatment.groups <- rep("sample", 11483)
sample_seurat <- AddMetaData(sample_seurat, sample_treatment.groups, col.name = "treatment")

# Clustering
sample_cluster <- sample_seurat
sample_cluster <- RunPCA(sample_cluster)
```

2. Another question: Before SCTransform: 31054 features, 11483 cells, After SCTransform: 14092 features, 11483 cells. Is this loss of features expected after SCTransform? 

Thank you.
