### ISSUE TITLE
problem in installation

### ISSUE THREAD

**Issue by Shawn10312** [satijalab/seurat#2513]
I have confronted the problem in installing Seurat. As following:

> install.packages('Seurat')
Installing package into ‘/R/x86_64-conda_cos6-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://rweb.crmda.ku.edu/cran/src/contrib/Seurat_3.1.2.tar.gz'
Content type 'application/x-gzip' length 794277 bytes (775 KB)
==================================================
downloaded 775 KB

* installing *source* package ‘Seurat’ ...
** package ‘Seurat’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() :
  argument is of length zero
* removing ‘/R/x86_64-conda_cos6-linux-gnu-library/3.6/Seurat’

The downloaded source packages are in
        ‘/tmp/RtmpnCl7z4/downloaded_packages’
Warning message:
In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status

> Sys.info()
                              sysname                               release
                              "Linux"          "3.10.0-957.38.1.el7.x86_64"
                              version                              nodename
"#1 SMP Thu Sep 26 12:15:44 EDT 2019"     "c15n06"
                              machine                                 login
                             "x86_64"                             "unknown"
                                 user                        effective_user
                              "yx"                               "yx"

I changed the version of R to 3.5.0, Seurat can not be installed too.

**Comment by mojaveazure** [comment]
This is an issue with Conda. Please install R from CRAN and try again.
