### ISSUE TITLE
Cheat sheet error

### ISSUE THREAD

**Issue by kmshort** [satijalab/seurat#2514]
Hi,

This is for the Seurat commands list on the Satija Lab Seurat website. Apologies for posting it here, I wasn't sure where to post this.

However, I've noticed that a couple of the Seurat v2.X vs v3.x SetIdent vs Idents commands are erroneous.

```
SetIdent(object = object, ident.use = "new.idents") | Idents(object = object) <- "new.idents")

SetIdent(object = object, cells.use = 1:10, ident.use = "new.idents") | Idents(object = object, cells = 1:10) <- "new.idents")
```

Should be:
```
SetIdent(object = object, ident.use = "new.idents") | Idents(object = object) <- "new.idents"

SetIdent(object = object, cells.use = 1:10, ident.use = "new.idents") | Idents(object = object, cells = 1:10) <- "new.idents"
```
Right?

and one more:

`levels(x = object@idents) | levels(x = objects)`
should be

`levels(x = object@idents) | levels(x = object)`

**Comment by andrewwbutler** [comment]
Hi,

Yep, thanks for catching those typos. The webpage has been updated to reflect those changes.
