### ISSUE TITLE
Use all genes for FindAllMarkers

### ISSUE THREAD

**Issue by MonkeySylvia** [satijalab/seurat#2517]
Hi,
I'm interested in particular subset of gene expression in my drop-seq dataset. 
To correct for batch effect, I first used <FindIntegrationAnchors> and <IntegrateData> to integrate the reads from 4 different sequencing batches.
Then I ran <FindAllMarkers>, but regardless the threshold I set (even for logfc.threshold=0, return.thresh=1), I always got the markers from VariableFeatures.
I realized that the markers are only calculated from variable feature subset, although on the documentation page it said it should be from all genes.

I wonder if it is due to the integrated data? Because the genes I'm interested are not in the variable features, if there is anyway I can calculate markers from all genes? 

Thanks!
Sylvia

**Comment by jeremycfd** [comment]
Might help people diagnose your issue if you provide an example of the command you are using to find markers.

**Comment by satijalab** [comment]
We do not recommend calculating differential expression using the integrated assay. Please use the RNA assay for DE, which will enable you to test for all genes.
