### ISSUE TITLE
library(Seurat) package mullttest; fail to be installed? Can not function the read10X

### ISSUE THREAD

**Issue by sunlit12345** [satijalab/seurat#2518]
<img width="768" alt="image" src="https://user-images.githubusercontent.com/60066863/72682326-d2298380-3b06-11ea-89c2-c56b8c35a142.png">
Why this error happen?

Who can help?  Thanks very much!

**Comment by sunlit12345** [comment]
1. package mullttest; fail to be installed?
2. Can not function the read10X

**Comment by samuel-marsh** [comment]
Hi,

Please see solution previously posted #2409 

Best,
Sam
