### ISSUE TITLE
Is it possible to use FindAllMarkers to find markers based on a metaData column?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#252]
Hello there,

As far as I understand, the function FindAllMarkers by default uses the identity classes allocated by Seurat's cluster-finding step earlier in the pipeline.  So, if there are nine clusters identified by FindClusters, then FindAllMarkers uses these cluster IDs to find markers.

However, if we have another identity scheme for each cell computed by an external package which gives only 5 distinct classes, then can I use FindMarkers by adding these new cell identities as a metaData column to my Seurat object?  If so, how exactly do I give the metaData column as input to FindAllMarkers?

Alternatively, I tried to trick Seurat by manually changing the object@ident.  But that did not work, maybe simply changing object@ident is not enough?

Any help would be greatly appreciated!

**Comment by leonfodoulian** [comment]
Hi,

You can change the identity of your cells to the desired identity located in the `object@meta.data` slot.

```
# Set the identity of your cells to the desired column
object <- SetAllIdent(object = object, id = "desired.column")
```

Best,
Leon

**Comment by vertesy** [comment]
In version Seurat 3, based in #1076,
it is `Idents(object = object) <- "new.idents"`, 
and a concrete example would be 
```R
Idents(object = object) <- object@meta.data$'integrated_snn_res.0.3'
```

**Comment by annamarie67** [comment]
Hi. No one here mentioned what the input would be into the findallmarkers after this: 
Idents(H3_RNA = H3_RNA) <- H3_RNA@meta.data$'wsnn_res.2.5'

I have RNA data, ATAC data, and combined WNN based clusters
I want my WSNN_res2.5 to be the input to FindAllMarkers, so I can compare that to the data generated by RNA alone
The issue I'm running into is it still asks for a default assay
