### ISSUE TITLE
Average expression of all genes in a cluster in Integrated data

### ISSUE THREAD

**Issue by priyamnarain** [satijalab/seurat#2522]
Hi,

I have an integrated data set Circadian.combined. I need to see average expression of all genes in a particular cluster. I have used the following:

CIRCADIAN.combined$celltype.stim <- paste(Idents(CIRCADIAN.combined), CIRCADIAN.combined$stim, sep = "_")
CIRCADIAN.combined$celltype <- Idents(CIRCADIAN.combined)
Idents(CIRCADIAN.combined) <- "celltype.stim"
markers <- FindMarkers(CIRCADIAN.combined, ident.1 = "2_ZT2", ident.2 = "2_ZT13", verbose = FALSE)
head(markers, n = "max.print")

Can you please let me know that how do I find the average expression all the genes in my clusters named: ident.1 = "2_ZT2", ident.2 = "2_ZT13".

**Comment by andrewwbutler** [comment]
Hi,

Please see the `AverageExpression` function.
