### ISSUE TITLE
Change colors in bar of heatmap

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#2523]
Hello!

How do I change the color of the bar showing cluster identity on a heat map? I know how to manually change the color of the clusters in my UMAP plot, how do I change the heatmap to reflect this color change? 

I want to update the heatmap to show these cluster colors:
`DimPlot(object = org1, cols = c('0' = "#F8766D", '1' = "#F564E3", '2' = "#00BFC4", '3' = "#7CAE00"))`

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Please see documentation for `DoHeatmap()`.  `group.colors` will allow you to specify the color of the bars on heatmap.

Best,
Sam
