### ISSUE TITLE
FeatureScatter normalized values below 0

### ISSUE THREAD

**Issue by lennycheung** [satijalab/seurat#2525]
Hi,

I am looking at a FeatureScatter plot and I am getting values below 0.
I thought the values plotted were normalized values equivalent to transcripts per 10 thousand so I don't know how they are negative?
Some FeatureScatters I do are fine and show only values >=0.

Many thanks,

Leonard

![Capture](https://user-images.githubusercontent.com/15195720/72844286-31ec6f80-3c6a-11ea-990a-4f7e64f9dfb6.PNG)

**Comment by Connorr0** [comment]
Did you integrate your datasets? Integration can pull gene expression values below 0. What are your axes?

**Comment by lennycheung** [comment]
Oh yes they are integrated data with the CCA so that would be it.  The axes are just two genes and I made it with just the standard FeaturePlot function.  Why can integration pull negative values if the original objects did not have negative values?  

Thanks,  Leonard

**Comment by timoast** [comment]
Please see the [paper](https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub) for a description of the method and why negative values are expected. As stated in previous issues, we don't recommend using the integrated data for DE or visualization.
