### ISSUE TITLE
Exclude clusters from Violin Plot

### ISSUE THREAD

**Issue by keenhl** [satijalab/seurat#2529]
I know how to reorder cluster order on the Violin plot.  However, I was wondering if there was a way to selectively exclude certain clusters from the plot.

Thanks

**Comment by samuel-marsh** [comment]
Hi,

Please see docmentation for `VlnPlot()` for more information.  I believe you are looking for `idents = c("Cluster_1, "Cluster_3, etc)`

Best,
Sam

**Comment by keenhl** [comment]
Hi Sam,

That works.  Thank you for taking time to help me with that.
