### ISSUE TITLE
VlnPlot in a loop

### ISSUE THREAD

**Issue by iiiir** [satijalab/seurat#253]
Hi,

I need to plot a set of genes (dynamically determined using program). But cannot show p when doing in a loop.

```R
pdf('test.pdf')
seruat_sub <- genelist.seurat.12[genelist.seurat.12 %in% all_genes]
for (i in 1:ceiling(length(seruat_sub)/6)) {
    if (i*6 < length(seruat_sub)) {
        VlnPlot(object = myproject, features.plot = seruat_sub[(i-1)*6+1:(i*6)])
    } else {
        VlnPlot(object = myproject, features.plot = seruat_sub[(i-1)*6+1:length(seruat_sub)])
    }
}
dev.off()
```

However, individual plot command will work:
```R
>>> i = 1
>>> VlnPlot(object = myproject, features.plot = seruat_sub[(i-1)*6+1:length(seruat_sub)])
```

Can someone help?
Thanks,

**Comment by leonfodoulian** [comment]
Hi,

Here are 2 options (simplified compared to what you are doing, but you can adapt them easily):

```
#### Option 1 ####
# Create an empty list, and store VlnPlots in the list
plot.list <- list()
for (i in 1:length(genes.list)) {
  plot.list[[i]] <- VlnPlot(object = object, features.plot = genes.list[i], do.return = T)
}
# Check elements of plot.list
plot.list

#### Option 2 ####
# Directly print output of VlnPlot
for (i in 1:length(genes.list)) {
  print(VlnPlot(object = object, features.plot = genes.list[i]))
}
```

Best,
Leon

**Comment by iiiir** [comment]
Thanks! I used the second option. Here is the working code:

```
for (i in 1:ceiling(length(my_gene_list)/6)) {
    if (i*6 < length(my_gene_list)) {
        p <- VlnPlot(object = myproject, 
		features.plot = my_gene_list[((i-1)*6+1):(i*6)],
		do.return = T)
    } else {
        p <- VlnPlot(object = myproject, 
		features.plot = my_gene_list[((i-1)*6+1):length(my_gene_list)],
		do.return = T)
    }
    print(p)
}
```

**Comment by satijalab** [comment]
I would also add that you can create a series of plots as a list, and then use the plot_grid function from the cowplot package to display them side-by-side.

**Comment by Sophia409** [comment]
I also need to plot a set of genes,when i use but when i try by using this code , it didn't work,can you help me and give me the right code?
my_gene_list <- list("Hoxa1","Hoxa2","Hoxa3","Hoxa4","Hoxa5","Hoxa6","Hoxa7")
for (i in 1:ceiling(length(my_gene_list)/6)) {
if (i*6 < length(my_gene_list)) {
p <- VlnPlot(object = tc, features = my_gene_list[((i-1)6+1):(i6)])
} else {
p <- VlnPlot(object = tc,
features = my_gene_list[((i-1)*6+1):length(my_gene_list)])
}
print(p)
}
image
However, individual plot command will work:
VlnPlot(object = tc, features = c("Hoxa1","Hoxa2","Hoxa3","Hoxa4","Hoxa5","Hoxa6","Hoxa7"), ncol = 3)

**Comment by Sophia409** [comment]
![image](https://user-images.githubusercontent.com/30619010/51161830-ee308e80-18ce-11e9-9cc1-25cb91fa7fa3.png)
the above picture shows my code to export vlnplot pictures, and the last row has different elements from other rows,**how I can make the last two picture as large as others in the same pdf file?** I tried ncol=5,nrow=2, but in the new version seurat3.0, it hasn't nrow command.
**can anyone help me?**

![image](https://user-images.githubusercontent.com/30619010/51161836-f25cac00-18ce-11e9-951c-9c97baad3b42.png)
