### ISSUE TITLE
Issue of loading Seurat package

### ISSUE THREAD

**Issue by vwtlin** [satijalab/seurat#2531]
Dear Seurat team

My desktop is macOS 10.15.2, RStudio Version 1.2.5033 and R version 3.6.2. I encounter an issue as shown below. Does it affect anything and how could I solve it?

Thanks a lot.

>library(Seurat)
Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/usr/bin/python3' "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/reticulate/config/config.py" 2>/dev/null' had status 1

**Comment by andrewwbutler** [comment]
Hi,

This looks like an issue with your reticulate and/or your python installation. Are you able to load reticulate separately of Seurat without this warning? Overall though, the reticulate package is only used for a small subset of the functionality in Seurat so I would proceed with your analyses in the mean time.

**Comment by vwtlin** [comment]
Dear Andrew,

Thanks very much for the comments. I tried to reinstall my Python and the problem is solved.
