### ISSUE TITLE
Labeling cells, not clusters

### ISSUE THREAD

**Issue by algal4** [satijalab/seurat#2532]
I was wondering if anyone had a way of labeling cells rather than identifying clusters so that when a sample is integrated with another they retain the same assignments. For example, if I know that a cell is a photoreceptor I would like it to be labeled as such rather than analyzing top markers in the cluster it belongs to.

**Comment by Connorr0** [comment]
You can label cells in your pre-integration dataset, but I do not know of any tools that will type the cells for you. If you label your cells before integration you can compare the cell types before and after using the metadata.
