### ISSUE TITLE
Error running ColorTSNESplit 

### ISSUE THREAD

**Issue by CcYyQq** [satijalab/seurat#254]
Hi,
   I tried the tutorial guide of PBMC33k, always have an error when running 

```R
ColorTSNESplit(pbmc.merged,node = 33)
Error in WhichCells(object = object, ident = left.group) : 
  Identity : NA not found.
```
I have 38 clusters in the  @ident.

**Comment by leonfodoulian** [comment]
Hi,

The `node` argument in `ColorTSNESplit()` corresponds to cluster tree nodes, and not to cluster identities. What you should do first is to plot the cluster tree of your data, then select a node of interest, and provide the node value to the `node` argument in `ColorTSNESplit()`. More details can be found in the documentation of the function (simply run `?ColorTSNESplit` in R).

```
# Plot cluster tree
PlotClusterTree(object = object)

# Select a node of interest and run ColorTSNESplit() for that node
ColorTSNESplit(object = object, node = 39)
```

Best,
Leon

**Comment by CcYyQq** [comment]
Hi
Thank you for your reply  @leonfodoulian. 
I've run the code `PlotClusterTree(object=object)`,and no error was reported. Then I run the code `ColorTSNESplit(object=object,node=33)`
Always have the same error. And I don't konw how to solve it.
![_20171220162539](https://user-images.githubusercontent.com/34188141/34197662-7309879e-e5a2-11e7-97e0-58535c61f5a8.png)


> error

**Comment by leonfodoulian** [comment]
Hi,

Sorry if I have not been clear in my answer. In your previous post, you mentioned that you have up to 38 clusters in your `object@ident` slot. So values ranging from 0 (or 1 if you already ran 
`object <- BuildClusterTree(object = object, reorder.numeric = TRUE)`
) to 37 or 38 cannot be used as input for the `node` argument. These values correspond to cluster identities, and not to cluster nodes. The node values are displayed in bleu/grey coloured boxed at each split in the plotted cluster tree when you run `PlotClusterTree(object = object)`. The values that you can use as input for the `node` argument are the ones that you get when you run `unique(object@cluster.tree[[1]]$edge[,1])`. This is why I had `39` as input to the `node` argument (and not `33`). 

Hope this is clearer.

Best,
Leon
