### ISSUE TITLE
help with heatmap setting

### ISSUE THREAD

**Issue by SFF-singecell-user** [satijalab/seurat#2541]
Hello, This is not so much a Seurat question as a ggplot2 question: I would like to shrink the text size for the cluster labels in the DoHeatmap but can't figure this out.
I tried  + theme(axis.text.x = element_text(size = 5)) but it does not do the trick.
Does anyone know how to do this?
Thanks in advance,

**Comment by andrewwbutler** [comment]
Hi,

Please see the `size` parameter for `DoHeatmap` to adjust text size above the color bar.
