### ISSUE TITLE
a suggestion about running Seurat 2.3.4 or Seurat 3.1

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2543]
Dear all, 'd appreciate having your suggestions on the following : 

I am running scRNA-seq analyses (in R 3.6.1) on a SLURM CLUSTER , and I do have 2 scripts :                   

a) a script that requires the package **Seurat 2.3.4** (historically, for "compatibility" with older data), and 

b) another script that requires the new version **Seurat 3.1.** 

When I submit the jobs to the SLURM cluster, how could specify in the R script the use of the library Seurat 2.3.4 versus Seurat 3.1 ? 

(as we know, when we load the Seurat library , we just write : library("Seurat"), without specifying the version). 

do I need to use a docker/singularity container for R.3.6.1 with Seurat 2.3.4, and another docker/singularity container with Seurat 3.1 ? thanks a lot !

**Comment by timoast** [comment]
You could use docker containers, or you can download the source for each version and use `devtools::load_all()` to load the different versions in the R script

**Comment by tanasa** [comment]
thank you ...
