### ISSUE TITLE
analysis of multiple time points * 2 replicates of scRNA-seq

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2544]
Dear all, 

'd appreciate also having your suggestions on the following case of scRNAseq analysis with Seurat 3.1. ; the question is : what analysis strategy would you recommend (described below) ?

shall we have 4 batches of scRNA-seq data of these experiments :  

**WT_batch1, WT_batch2, A_batch1, A_batch2**

**WT_batch3, WT_batch4, B_batch3, B_batch4** 

what is the optimal way to analyze the data-sets ? Several analysis strategies are possible : 

**STRATEGY A.** 

**1. to use CELLRANGER AGGR (with NORMALIZATION = TRUE) on :** 

**WT_batch1, WT_batch2**  : to produce WT_batch_1_2

**A_batch1, A_batch2** : to produce A_batch_1_2

**WT_batch3, WT_batch4** : to produce WT_batch_3_4

**B_batch3, B_batch4** : : to produce B_batch_3_4

2. and to follow the descriptions of SEURAT pipelines with LIGER, HARMONY, CONOS, fastMNN (below) on **WT_batch_1_2, WT_batch_3_4, A_batch_1_2, B_batch_3_4** :

_https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/conos.html_

_https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/harmony.html_

_https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/liger.html_

_https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/fast_mnn.html_ 

**STRATEGY B.** 

**1. to use SEURAT  MERGE function in order to have all the data (WT_batch1, WT_batch2, A_batch1, A_batch2, WT_batch3, WT_batch4, B_batch3, B_batch4) in a large MATRIX**

**2. follow the tutorials on SCTRANSFORM, or reciprocal_PCA in https://satijalab.org/seurat/v3.1/integration.html**

however, when I call the function **FindMarkers** (FindMarkers(object, ident.1, ident.2), how shall I specify the REPLICATES in ident.1 and in ident.2 ? ,

Any other analysis strategy ? Any suggestions, comments would be very welcome ! Thanks a lot !

-- bogdan

**Comment by samuel-marsh** [comment]
Hi Bogdan,

Not a member of the dev team but maybe this can be helpful.  I think you might get better assistance with this question on a more bioinformatics focused forum (bioinformatic stackexchange/biostars) rather than a github issue which is primarily for errors in the software/package.

Best,
Sam

**Comment by timoast** [comment]
Closing as this has been answered here: https://support.bioconductor.org/p/127811/
