### ISSUE TITLE
"biocViews:" in CRAN description breaks usage of rstudio/rsconnect

### ISSUE THREAD

**Issue by pcantalupo** [satijalab/seurat#2545]
Hello,

Please see issue [#399](https://github.com/rstudio/rsconnect/issues/399) of the rsconnect repo. In particular this comment described the problem clearly: https://github.com/rstudio/rsconnect/issues/399#issuecomment-578739539

Is it possible to remove the "biocViews:" from the CRAN DESCRIPTION file?

Thank you

**Comment by mojaveazure** [comment]
A package we [depend on](https://cran.r-project.org/package=mutoss) imports a [Bioconductor package](http://www.bioconductor.org/packages/release/bioc/html/multtest.html), but [R can't normally handle installing across repositories](https://github.com/satijalab/seurat/issues/2409). If a package has a biocViews entry in the DESCRIPTION, it tells R to look in both CRAN and Bioconductor for dependent packages.

We've added the biocViews to allow our users to install Seurat via `install.packages` without having to set the repository; removing it breaks the seamless installation process of Seurat. As such, this is an issue with rsconnect/packrat for not being able to handle cross-repository packages.
