### ISSUE TITLE
FindMarkers Cutoff

### ISSUE THREAD

**Issue by willmonty14** [satijalab/seurat#2546]
Hello Satjia Lab,
I've been using FindMarkers for a while now and I've noticed that it often returns genes that have a p-value that is greater than 0.05, and an adjusted p-value of 1. What is the cutoff in the source code for reporting differentially expressed genes? Thanks a lot, and have a nice day.

**Comment by andrewwbutler** [comment]
Hi,

You can see the different default cutoffs on the documentation page for `?FindMakers`. There is no p-value cutoff for what this function reports (will return for all genes tested), only cutoffs that determine which genes get tested. If you want to filtered based on some p-value threshold, you should subset the data.frame that gets returned.
