### ISSUE TITLE
Convert SingleCellExperiment to Seurat gives error

### ISSUE THREAD

**Issue by shaln** [satijalab/seurat#2548]
Hello,

I am having trouble converting `SingleCellExperiment` objects to `Seurat`, using `as.Seurat`. 
To give you a little bit of background on my data, I have 6 samples, each of them as a separate `SingleCellExperiment` object. After pre-processing the raw data using `CellRanger`, I performed quality control using `scater` to remove the outliers and did normalisation using `scran`. I then unlogged the log-transformed data and re-logged them to match the natural log used in `Seurat`. 

Next, I wanted to convert each `SingleCellExperiment` object into `Seurat`, before merging/integrating all 6 of them together in `Seurat`. However, I get the following error for every sample when I run the following code: 

```
> sample1.seurat <- as.Seurat(sample1.sce, counts = "counts", data = "logcounts")
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “dgeMatrix” is not valid for slot ‘data’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE
```
I'm not sure why I'm getting this error or what I should do to correct this. Any help would be much appreciated!

**Comment by andrewwbutler** [comment]
Hi @shaln. 

The code here looks correct - so we'd like to check this out in more detail. Can you either attach an object or e-mail a dropbox download link to abutler@nygenome.org? If possible, try to reproduce the error on downsampled objects so it will be a bit easier to share.

**Comment by Henry-zhang-For** [comment]
excuse me, I met the same question when i convert singlecellexperiment to seurat, did you solve this question?
