### ISSUE TITLE
manipulating FeaturePlot, integrated dataset

### ISSUE THREAD

**Issue by stephanyfoster** [satijalab/seurat#2550]
hello,

I am struggling with creating feature plots for particular genes in an integrated dataset.
When I try this:
FeaturePlot(S.combined, features = c("CBP"), label= TRUE, split.by = "Con", pt.size = 0.5, min.cutoff = 0) 
My plot is stretched vertically to the point where all I can see are the axes. It also doesn't seem to behave like a ggobject, I am able to change aspect ratio when using DimPlot but not FeaturePlot. What I'd like is to see each dataset clearly and separately. I welcome any tips!

ty

**Comment by timoast** [comment]
I think this is an issue with the plotting device you're using rather than Seurat, I suggest using a larger plotting device
