### ISSUE TITLE
subset ignores assays if "data" slot is empty

### ISSUE THREAD

**Issue by innesbre** [satijalab/seurat#2551]
Hi!
I am running `subset(x,cells=some_cell_names)` on a Seurat object with assays "RNA" and "SCT", where no normalization was run on the RNA assay (and as such, assay RNA contains slots "counts": a matrix of [genes,cells], and "data": a matrix of `logi[1,1] NA`).  The object returned does not contain the RNA assay, where you'd expect it to contain the RNA assay with a counts slot with just those cells.  
From looking at the source code for `subset`, I think the problem lies here:
```
for (assay in assays) {
        assay.features <- features %||% rownames(x = x[[assay]])
        slot(object = x, name = "assays")[[assay]] <- tryCatch(expr = subset.Assay(x = x[[assay]], 
            cells = cells, features = assay.features), error = function(e) {
            return(NULL)
        })
    }
```
Because `features %||% rownames(x = x[[assay]])` returns NULL for the "RNA" assay, but the gene list for the "SCT" assay.  I understand why the behaviour for `rownames(SeuratObject[[Assay]])` defaults to the "data" slot, but maybe if data slot is empty (or a 1x1 matrix of NA, since apparently that's the default) it should try "counts" too?

**Comment by satijalab** [comment]
We've discussed this internally, and for a variety of reasons (in particular, the number of functions that rely on the data slot), we need to have information in the data slot as a requirement to consider the assay valid. I do understand the logic of defaulting to counts if data is unavailable, but its not something we can support.
