### ISSUE TITLE
difficulty isolating cell cluster

### ISSUE THREAD

**Issue by lpdmagee** [satijalab/seurat#2552]
Hi,

I'm new to Seurat and I'm having difficulty isolating a neutrophil cluster from a set of integrated metastasis data. Out of 4 different data sets which I've integrated, I'm trying to isolate all the members of this one cell type. I've been attempting to use the WhichCells() function, but nothing I've passed into it has successfully isolated the neutrophils.

When I use Idents = "Neutrophils," R studio tells me that Idents is not a variable that is found, so instead of isolating the neutrophils from the integrated data set, it simply uses the entire integrated data set and returns what I already had.

Working with the integrated data set (works correctly):
<img width="871" alt="Screen Shot 2020-01-29 at 10 50 06 AM" src="https://user-images.githubusercontent.com/40338045/73387250-1e9e5d00-4285-11ea-974f-bc22298b4cf2.png">

Attempting to isolate the neutrophils (doesn't work):
<img width="807" alt="Screen Shot 2020-01-29 at 10 50 45 AM" src="https://user-images.githubusercontent.com/40338045/73387295-3544b400-4285-11ea-80e5-3ee12a345dc5.png">

 Plotting the neutrophil data— the fact that this is basically the same graph as the integrated data indicates that isolating the neutrophils hasn't worked and it's just re-plotting the integrated data:
<img width="702" alt="Screen Shot 2020-01-29 at 10 51 08 AM" src="https://user-images.githubusercontent.com/40338045/73387328-42fa3980-4285-11ea-852f-1bde78fc62f5.png">

Any and all suggestions would be greatly appreciated.

**Comment by lpdmagee** [comment]
Hi, 
I apologize if I wasn't specific enough. For context, I'd like to explain how we got to this point of clustering the cells in the first place. We used the tsne clustering method to obtain 19 unique communities on the plot. We then converted our Seurat object to a SingleR object and used the built-in immgen dataset as a reference annotation object. From there, we used the SingleR function to annotate all the different cell types and used the TsnePlot function with group.by= "SingleR labels" to verify that SingleR located the nuetrophil cluster correctly, as indicated by the first screenshot in the original post. 
Now, we are trying to isolate the neutrophil data by creating a subset of the larger integrated Seurat Object using the WhichCells() function. Unfortunately, we are still stuck at how we correctly use this function to identify the neutrophil cluster, or whether WhichCells() is the correct approach. 
If there are any further clarifications that need to be made to solve this issue, please let me know. Thank you for any suggestions!

**Comment by timoast** [comment]
`obj <- IntMetastasis[, IntMetastasis$labels == "Neutrophils"]`
