### ISSUE TITLE
Regarding the Wilcoxon test in DE testing

### ISSUE THREAD

**Issue by suvi93** [satijalab/seurat#2558]
Hello,
         I was just wondering if the default option for DE testing (Wilcoxon test) assumes if the data is paired even though it might not be the case for the user's data?

I've used both the default option and DESeq2 option in test.use argument and found that some genes that are shown as upregulated in the Wilcoxon test are being shown as down-regulated when calculated using DESeq2 option. Any idea why this is happening?

Thank you.
Suvi

**Comment by jeremycfd** [comment]
You are confusing your Wilcoxon tests. The Wilcoxon Rank Sum test is for independent samples. It's the Wilcoxon signed-rank test (not implemented in Seurat as far as I know) that is for paired samples.
