### ISSUE TITLE
AddModuleScore appending "1" to name in metadata

### ISSUE THREAD

**Issue by GBeattie** [satijalab/seurat#2559]
Hey! 

I know it's a small thing, but I've started using the AddModuleScore function a lot. The function adds "1" to every metadata entry name, i.e.

`NSCLC.seu <- AddModuleScore(NSCLC.seu, features = list(genes.A), name = "Gene_Signature_A")`

Results in:

`NSCLC.seu@meta.data[["Gene_Signature_A1"]]`

This would be fine if it was simple to change names in the metadata, but having to create new metadata and delete the old one isn't efficient if you have many modules and many objects.

Thanks!

**Comment by GBeattie** [comment]
Just realised this is a duplicate issue #2419, my apologies, but I'll keep this open in case there is an easy way around it I'm missing (i.e. simpler renaming  of the metadata), as I'm doing a lot of manual renaming.

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team, but as this seems to be the intended behavior of AddModuleScore can I ask why you are renaming the columns?

Best,
Sam

**Comment by mojaveazure** [comment]
This is the intended behaviour of `AddModuleScore`; if you wish to rename columns after the fact, you can do this with a for-loop and a named list with before and after names or `gsub` the trailing digits after the metadata column name.

**Comment by vertesy** [comment]
That is:
```r
colnames(obj@meta.data) <-
      gsub(x = colnames(obj@meta.data)
           , pattern = paste0(ScoreName,1)
           , replacement = ScoreName
           )
# ScoreName is the name without 1

```
I wrapped it into the `AddGOScore()` function in [Seurat.utils](https://github.com/vertesy/Seurat.utils/). Call after `GetGOTerms()`. [Details](https://github.com/vertesy/Seurat.utils/blob/master/Seurat.gene.sets.and.GO.terms.R).

**Comment by kobeho24** [comment]
> That is:
> 
> ```r
> colnames(obj@meta.data) <-
>       gsub(x = colnames(obj@meta.data)
>            , pattern = paste0(ScoreName,1)
>            , replacement = ScoreName
>            )
> # ScoreName is the name without 1
> ```
> 
> I wrapped it into the `AddGOScore()` function in [Seurat.utils](https://github.com/vertesy/Seurat.utils/). Call after `GetGOTerms()`. [Details](https://github.com/vertesy/Seurat.utils/blob/master/Seurat.gene.sets.and.GO.terms.R).

Had error when running the code above, fixed it by the following one

colnames(object@meta.data) <- gsub("Gene_index1","Gene_index",colnames(object@meta.data))

**Comment by GBeattie** [comment]
I ended up switching to UCell (https://github.com/carmonalab/UCell) because of the way AddModuleScore names the metadata entries (still makes no sense why it would do it the way it does...), but I've had to switch back to the Seurat approach for a particular application. For anyone using AddModuleScore who prefers simply having the score names be **exactly** the same as how they've been named in your list of signatures, see below for my approach.

```
seu.int <- AddModuleScore(seu.int, features = sig.list, name = "_score")
names(seu.int@meta.data)[grep("_score", names(seu.int@meta.data))] <- names(sig.list)
FeaturePlot(seu.int, features = names(sig.list))
```
