### ISSUE TITLE
about DefaultAssay()

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2561]
Dear all, i am following the tutorial : https://satijalab.org/seurat/v3.1/immune_alignment.html

and if I may ask you question please : 

shall we set up : **DefaultAssay(immune.combined) <- "integrated"**

or :  **DefaultAssay(immune.combined) <- "RNA"** 

before running **FindMarkers() or FindConservedMarkers()** ? thank you very much !

**Comment by satkins1** [comment]
I think that FAQ number should help answer this:

https://satijalab.org/seurat/faq.html

Essentially it appears that DE testing should be performed on the unintegrated data though some appear to suggest using the `scale.data` slot in the integrated assay this doesnt appear to be fully supported/recommended and the interpretation is not as straightforward as avgLFC (at least as I understand the current situation).
