### ISSUE TITLE
assy.orig and assay.used

### ISSUE THREAD

**Issue by sandbox-rgb** [satijalab/seurat#2562]
Dear All,

I get the following warning message when I do str(object): 

Warning messages:
1: Not a validObject(): no slot of name "assay.orig" for this object of class "Assay" 
2: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand" 
3: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand" 
4: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand" 

what does this mean? 

The Seurat object seems to work and looks as expected so it doesn't seem these warning hinder function to that degree. However I am not sure what the cause is.

**Comment by mojaveazure** [comment]
You can ignore these warnings. Those slots will be used in the future to track the provenance of individual assays (eg. an SCT assay coming from an RNA assay) and command logs (eg. `FindClusters` using the ADT assay) in a more robust way than what we have now. The slots were added in newer versions of Seurat, so objects generated with prior versions of Seurat don't have these slots for `Assay` and `SeuratCommand` objects. If you want to silence these warnings, you can update your `Seurat` object with [`UpdateSeuratObject`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/UpdateSeuratObject).

**Comment by brianpenghe** [comment]
If you do `UpdateSeuratObject()` the error is gone

**Comment by sandbox-rgb** [comment]
@brianpenghe thank you for letting me know!

**Comment by liuyu988** [comment]
> You can ignore these warnings. Those slots will be used in the future to track the provenance of individual assays (eg. an SCT assay coming from an RNA assay) and command logs (eg. `FindClusters` using the ADT assay) in a more robust way than what we have now. The slots were added in newer versions of Seurat, so objects generated with prior versions of Seurat don't have these slots for `Assay` and `SeuratCommand` objects. If you want to silence these warnings, you can update your `Seurat` object with [`UpdateSeuratObject`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/UpdateSeuratObject).

Dear sir,could the seurat object add a slot parameter,except data,counts,scale.data?thanks
