### ISSUE TITLE
Better Seurat object summary

### ISSUE THREAD

**Issue by royfrancis** [satijalab/seurat#2563]
Seurat object summary provides minimal info. Before and after several analysis steps.

```
An object of class Seurat 
97866 features across 213 samples within 3 assays 
Active assay: spliced (32622 features)
 2 other assays present: unspliced, ambiguous
 3 dimensional reductions calculated: pca, tsne, umap
```

Compare that to Scanpy Anndata.

Before analysis

```
AnnData object with n_obs × n_vars = 213 × 32622 
    obs: 'cell_type', 'cell_type1'
    obsm: 'X_tsne', 'X_umap', 'velocity_tsne', 'velocity_umap'
    layers: 'spliced', 'unspliced'
```

After analysis

```
AnnData object with n_obs × n_vars = 213 × 32622 
    obs: 'cell_type', 'cell_type1', 'n_counts', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime', 'latent_time'
    var: 'velocity_gamma', 'velocity_r2', 'velocity_genes', 'fit_alpha', 'fit_beta', 'fit_gamma', 'fit_t_', 'fit_scaling', 'fit_std_u', 'fit_std_s', 'fit_likelihood', 'fit_u0', 'fit_s0', 'fit_pval_steady', 'fit_steady_u', 'fit_steady_s', 'fit_alignment_scaling'
    uns: 'pca', 'neighbors', 'velocity_settings', 'velocity_graph', 'velocity_graph_neg', 'cell_type1_colors', 'recover_dynamics'
    obsm: 'X_tsne', 'X_umap', 'velocity_tsne', 'velocity_umap', 'X_pca'
    varm: 'PCs', 'loss'
    layers: 'spliced', 'unspliced', 'Ms', 'Mu', 'velocity', 'variance_velocity', 'fit_t', 'fit_tau', 'fit_tau_', 'velocity_u'
```

This is so much more transparent and easy to see what's going on.

I think it would be nice to get some more summary info from Seurat without having to dig in too much.

**Comment by timoast** [comment]
What specifically would you like to see included in the Seurat object summary?

**Comment by royfrancis** [comment]
It's a general idea rather than request for something specific. Generally, it would be nice to which slots are updated/filled in after running various steps.

**Comment by timoast** [comment]
I will close this issue then, re-open if you have a specific request.

**Comment by trgibbons** [comment]
I'd like to second @royfrancis's request, and to ask for a more constructive response to user feedback than, "give me a detailed spec sheet or gtfo." 

The summary info provided by Seurat is very sparse. Perhaps it's possible to exactly recreate the Scanpy summary, or perhaps Seurat S4 and Scanpy Anndata objects are different in ways that make this impractical. I'm not familiar enough with the inner workings of either to make this determination, but I would greatly appreciate it if the Seurat developers could look at the Scanpy example provided by @royfrancis, and see if there's a reasonable way to export a similarly-verbose summary from Seurat S4 objects.
