### ISSUE TITLE
SpatialPlot: option to not display image background

### ISSUE THREAD

**Issue by lima1** [satijalab/seurat#2564]
Hi,

I could not find a way to hide the image in SpatialPlot. The file sizes become quite large when I generate PDFs with lots of features.  Would it be possible to add an option to hide the H&E image and plot only dots? 

I can bring the sizes down dramatically with Adobe Acrobat's reduced PDF export, but that's a manual step that I don't think has an equivalent R solution.

Thanks for the great 3.2 update!
Markus

**Comment by lima1** [comment]
I ended up simply resizing the images in case somebody else has the same issue.

```
.resize_slice_images <- function(obj, w = 300) {
    if (!requireNamespace("EBImage", quietly = TRUE)) return(obj)
    .resize_image <- function(k) {
        new_k <- paste0(k, "_scaled")
        obj@images[[new_k]] <- obj@images[[k]]
        obj@images[[new_k]]@image <- EBImage::resize( obj@images[[k]]@image, w = w)
        r <- w / nrow(obj@images[[k]]@image)
        obj@images[[k]] <- NULL
        obj@images[[new_k]]@scale.factors$lowres <- obj@images[[new_k]]@scale.factors$lowres * r
        obj
    }
    all_images <- Images(obj)
    for(i in all_images) {
        obj <- .resize_image(i)
    }    
    obj
}
```

**Comment by andrewwbutler** [comment]
Hi Markus,

It's a good suggestion, especially for the case you mention. We'll look into adding this functionality in the near future.

**Comment by andrewwbutler** [comment]
The `spatial` branch has been updated. There is now an `image.alpha` parameter that controls the opacity of the background image. If you set this to 0, it should remove the image entirely.
