### ISSUE TITLE
Trouble installing Seurat v3.2- Libcurl not found 

### ISSUE THREAD

**Issue by cvw462** [satijalab/seurat#2565]
Hi all,

I'm a newbie to Seurat and I've tried installing it but I'm getting an error message of a missing libcurl package. I'm also running R/3.6.0.

Thanks you so much in advance guys! I really appreciate it. 

> devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')
Downloading GitHub repo satijalab/seurat@develop
These packages have more recent versions available.
Which would you like to update?

 1: All                                      
 2: CRAN packages only                       
 3: None                                     
 4: httr        (1.4.0    -> 1.4.1   ) [CRAN]
 5: curl        (3.3      -> 4.3     ) [CRAN]
 6: mime        (0.7      -> 0.8     ) [CRAN]
 7: openssl     (1.4      -> 1.4.1   ) [CRAN]
 8: pkgconfig   (2.0.2    -> 2.0.3   ) [CRAN]
 9: htmlwidgets (1.3      -> 1.5.1   ) [CRAN]
10: dplyr       (0.8.3    -> 0.8.4   ) [CRAN]
11: data.table  (1.12.4   -> 1.12.8  ) [CRAN]
12: RSpectra    (0.15-0   -> 0.16-0  ) [CRAN]
13: cli         (1.1.0    -> 2.0.1   ) [CRAN]
14: fansi       (0.4.0    -> 0.4.1   ) [CRAN]
15: pillar      (1.4.2    -> 1.4.3   ) [CRAN]
16: vctrs       (0.2.0    -> 0.2.2   ) [CRAN]
17: stringi     (1.4.3    -> 1.4.5   ) [CRAN]
18: sys         (3.2      -> 3.3     ) [CRAN]
19: mvtnorm     (1.0-11   -> 1.0-12  ) [CRAN]
20: yaml        (2.2.0    -> 2.2.1   ) [CRAN]
21: tidyselect  (0.2.5    -> 1.0.0   ) [CRAN]
22: BH          (1.69.0-1 -> 1.72.0-3) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
library(Seurat)5
Enter one or more numbers, or an empty line to skip updates:
5
curl (3.3 -> 4.3) [CRAN]
Installing 1 packages: curl
Installing package into ‘/home-new/cvw462/R’
(as ‘lib’ is unspecified)
trying URL 'https://cran.revolutionanalytics.com/src/contrib/curl_4.3.tar.gz'
Content type 'application/octet-stream' length 673779 bytes (657 KB)
==================================================
downloaded 657 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
** using staged installation
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/home-new/abc123/R/curl’
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘curl’ had non-zero exit status
`

**Comment by jeremycfd** [comment]
Have you tried manually installing that library?
`install.packages("curl")`

**Comment by mojaveazure** [comment]
As stated in the error message, you're missing the Curl development libraries (eg. `libcurl4-openssl-dev` for Ubuntu Linux and other Debian-based systems). You need to install the Curl development libraries on your computer before installing the `curl` R package
