### ISSUE TITLE
units scale feature plot

### ISSUE THREAD

**Issue by beamaraba** [satijalab/seurat#2567]
Hi!

I would like to know what the units of the color scales in the feature plots (tsne) are when the expression of a gene is plotted. Is it average? maximum? Log?
Maybe it is explained somewhere but I couldn´t find it.

Many thanks!

**Comment by jeremycfd** [comment]
The default slot of FeaturePlot() is "data", is generated from your counts when you use the NormalizeData() function. The standard normalization.method is "LogNormalize", which does the following (as explained in ?NormalizeData): LogNormalize: Feature counts for each cell are divided by the total counts for that cell and multiplied by the scale.factor. This is then natural-log transformed using log1p.
