### ISSUE TITLE
RNA Velocity using Seurat

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#2568]
I want to filter the cells from Dropest matrices before running velocyto. I have 4945 cells in my dropest file and I have some doublets in my data set which I want to remove.  How should I filter these cells?

**Comment by timoast** [comment]
Use the `subset` function, as described [here](https://satijalab.org/seurat/essential_commands.html) with examples shown in the vignettes [here](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html)
