### ISSUE TITLE
Sorting x-axis on VlnPlot using an integrated object and group.by

### ISSUE THREAD

**Issue by cswoboda** [satijalab/seurat#2571]
Hello! 

I have an integrated dataset from 5 timepoints, and I'd like to sort them chronologically. I've looked at past issues (#2121 & #454)  regarding sorting using levels on cell types, but I'm unaware how to do this with my time points.

Thanks,

Casey

**Comment by jeremycfd** [comment]
What do you mean "sort" them? Are you trying to visualize them? If you could provide an example of what you are trying to do and what you want it to look like, that would be helpful, but I suspect that this is really a basic R question rather than a Seurat-specific question.

**Comment by jeremycfd** [comment]
The order of the time points on the X axis is defined by the factor-levels of that variable [(read about factors in R here)](https://www.stat.berkeley.edu/~s133/factors.html). If you create a VlnPlot like this:
`VlnPlot(object = MyObject, features = "Gene", group.by = "TimePoint")`
the order on the X-axis is defined by levels(MyObject@meta.data$TimePoint) if that variable is already a factor, or levels(factor(MyObject@meta.data$TimePoint)) if that variable is not yet a factor. If you want to set the order yourself, you can do something like this:
`MyObject@meta.data$NewTimePoint <- factor(MyObject@meta.data$TimePoint, levels = c("Time1", "Time10", "Time20"))`
making sure that you put each possible value of the TimePoint variable in the specific order you want. Then if you make a VlnPlot grouping by NewTimePoint, it should present in the order you specified in the levels argument.

**Comment by cswoboda** [comment]
This helped tremendously thanks!!
