### ISSUE TITLE
Change default colours in SpatialDimPlot?

### ISSUE THREAD

**Issue by mvhunter1** [satijalab/seurat#2573]
Hi,
I'm trying to change the default colours for clusters plotted onto the tissue image using SpatialDimPlot. For DimPlot I was able to change the colour palette using the argument "cols" but there is no such argument in the Spatial plot functions. Trying to change the palette using scale_color_manual in ggplot also doesn't work. Is there a way to change the default colours in the spatial plots?
Thanks!

**Comment by andrewwbutler** [comment]
Hi,

You can use `scale_fill_manual` to change the color palette manually.  It's a good point though. We will look into adding the `cols` parameter to `SpatialDimPlot` to bring functionality more in line with `DimPlot`.

**Comment by andrewwbutler** [comment]
The `spatial` branch has been updated and now `SpatialDimPlot` has a `cols` parameter.

**Comment by zoucheng123** [comment]
Hi, 
When I use the "cols" parameter to change the default colours, it still doesn't work. 

SpatialPlot(scRNA, ncol = 2, group.by = "seurat_clusters", pt.size.factor = 1.6,
                    cols = c("#7fc97f", "#beaed4", "#fdc086", "#386cb0", "#f0027f"))
# Error in `cli::cli_abort()`:
# ! Insufficient values in manual scale. 16 needed but only 0 provided.
# Run `rlang::last_trace()` to see where the error occurred.

Is there anything wrong?
Thanks!

**Comment by Streisenberg** [comment]
Hello @zoucheng123,

I am not on the development team but this is another way to change default colors with SpatialDimPlot

```
my_cols <- c("Cell1" = "#e3dac9", "Cell2" = "#ff681f", "Cell2" = "#91403d")
srt_object$Class1 <- factor(srt_object$Class1 ,levels=names(my_cols))

SpatialDimPlot(srt_object, group.by = "Class1", crop = F, alpha = 0.5, pt.size.factor = 1.6, cols = my_cols)
```

Hope it helps!

**Comment by Prathyusha-konda** [comment]
> Hi,
> 
> You can use `scale_fill_manual` to change the color palette manually. It's a good point though. We will look into adding the `cols` parameter to `SpatialDimPlot` to bring functionality more in line with `DimPlot`.

scale_fill_manual option only seems to work for the last slice and not all of them. Could you please let me know how to change on all merged slices?

**Comment by nina-hahn** [comment]
Dear @Prathyusha-konda , have you added it with a + sign or & sign? The last should do the work. Best

**Comment by Jorges1000** [comment]
Hi, version 5.1.0, discrete vector of colors (e.g. c('Red','Green','Blue') still gives same error:
Error in `palette()`:
! Insufficient values in manual scale. 3 needed but only 0 provided.

**Comment by HuXuantao** [comment]
Version 5.2.1, either discrete vector of colors or named STILL gives same error: Error in palette():
! Insufficient values in manual scale. X needed but only 0 provided.
Any one can help?
