### ISSUE TITLE
Control handling of weighted graphs for FindClusters

### ISSUE THREAD

**Issue by TomKellyGenetics** [satijalab/seurat#2574]
As discussed (see: https://github.com/satijalab/seurat/pull/2440) for the Leiden algorithm, control of weighted graph inputs for `FindClusters` would be beneficial. Weights can be specified explicitly and passes to the clustering algorithm, however it would be more convenient to control whether or not weights are derived from the values of the adjacency matrix. This leads to very different results between when weights are used or not.

Therefore I propose to add a `weighted` argument (defaults as `weighted = TRUE`) to `FindClusters`. If no `weights` are given (`weights = NULL`) then the values of the adjacency matrix are used. As discussed with @andrewwbutler default support for weighted graphs is preferable.

https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/clustering.R#L39
https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/clustering.R#L153

Specific to `RunLeiden` I propose to change the `method = "igraph"` to create an undirected weighted matrix in this case. An undirected graph is preferable as the "shared nearest neighbours" adjacency matrix should be symmetrical. Note that **this will change the default results** but it is preferable. It is not clear to me whether other methods supported by `RunModularityClustering` take weights into account.

https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/clustering.R#L691

Please note that Leiden has been added to the core `igraph` library and an `r-graph` implementation in development. This implementation will be preferable for performance once it is available: https://github.com/igraph/igraph/pull/1259 https://github.com/igraph/rigraph/issues/346

**Comment by satijalab** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move to igraph implementation of Leiden](https://trello.com/c/trV0m7fI/1-move-to-igraph-implementation-of-leiden)

**Comment by TomKellyGenetics** [comment]
As discussed in ##3233, it is preferable to have handling weighted graphs be the default for `method = "igraph"`. It should also be the default for `method = "matrix"` provided that a non-binary sparse matrix is passes to `leiden` with integer weights for each non-zero edge.

**Comment by rsatija** [comment]
We are closing this issue as we  chose not to implemnent this. We did look into it but the igraph implementation did not work reliably with large graphs.  I know its been a while, but please feel free to re-open if there have been improvements to the igraph package and we will take another look.
