### ISSUE TITLE
Error in merging two Seurat objects to run RNA Velocyto

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#2576]
Hi Seurat team,
I have two Seurat objects. 
###First Object###
data_rds<-readRDS(file ="counts.matrices.rds") #count matrices from DropEst
bm <- as.Seurat(x = data_rds) # make seurat object
> str(bm)
Formal class 'Seurat' [package "Seurat"] with 12 slots
  ..@ assays      :List of 3
  .. ..$ exon    :Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:3364826] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. .. .. .. ..@ p       : int [1:4946] 0 85 169 247 331 418 494 574 659 739 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 17284 4945
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:17284] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. .. .. .. .. ..@ x       : num [1:3364826] 1 1 1 1 2 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:3364826] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. .. .. .. ..@ p       : int [1:4946] 0 85 169 247 331 418 494 574 659 739 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 17284 4945
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:17284] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. .. .. .. .. ..@ x       : num [1:3364826] 1 1 1 1 2 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "exon_"
  .. .. .. ..@ var.features : logi(0) 
  .. .. .. ..@ meta.features:'data.frame':	17284 obs. of  0 variables
  .. .. .. ..@ misc         : NULL
  .. ..$ intron  :Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:1369810] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. .. .. .. ..@ p       : int [1:4946] 0 82 180 191 211 228 313 407 423 434 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 15036 4945
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:15036] "ENSORLG00000029794" "ENSORLG00000014696" "ENSORLG00000003723" "ENSORLG00000002306" ...
  .. .. .. .. .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. .. .. .. .. ..@ x       : num [1:1369810] 1 1 2 1 1 1 1 1 2 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:1369810] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. .. .. .. ..@ p       : int [1:4946] 0 82 180 191 211 228 313 407 423 434 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 15036 4945
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:15036] "ENSORLG00000029794" "ENSORLG00000014696" "ENSORLG00000003723" "ENSORLG00000002306" ...
  .. .. .. .. .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. .. .. .. .. ..@ x       : num [1:1369810] 1 1 2 1 1 1 1 1 2 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "intron_"
  .. .. .. ..@ var.features : logi(0) 
  .. .. .. ..@ meta.features:'data.frame':	15036 obs. of  0 variables
  .. .. .. ..@ misc         : NULL
  .. ..$ spanning:Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:685115] 0 1 2 3 4 5 6 7 8 9 ...
  .. .. .. .. .. ..@ p       : int [1:4946] 0 10 19 34 44 56 74 88 102 107 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 13766 4945
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:13766] "ENSORLG00000010629" "ENSORLG00000011476" "ENSORLG00000002549" "ENSORLG00000023504" ...
  .. .. .. .. .. .. ..$ : chr [1:4945] "TTAACTCGTGAACCTT" "AGCTCCTAGTACGTAA" "CCTTTCTGTATAATGG" "CTAACTTGTTGAGTTC" ...
  .. .. .. .. .. ..@ x       : num [1:685115] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  
### Second object:  has filtered cells (2593) that I want to use for velocyto##
> str(Seurat_Object2)
Formal class 'Seurat' [package "Seurat"] with 12 slots
  ..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:3446114] 0 1 2 5 6 9 13 22 24 27 ...
  .. .. .. .. .. ..@ p       : int [1:2593] 0 1299 4251 5884 7172 8840 10176 12582 12739 12946 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 18377 2592
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:18377] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:2592] "AAACCTGAGAGCTGCA" "AACCGCGCAGTCCTTC" "ATGCGATCAAAGTGCG" "ATGCGATGTACCGCTG" ...
  .. .. .. .. .. ..@ x       : num [1:3446114] 10 1 2 1 4 1 29 18 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:3446114] 0 1 2 5 6 9 13 22 24 27 ...
  .. .. .. .. .. ..@ p       : int [1:2593] 0 1299 4251 5884 7172 8840 10176 12582 12739 12946 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 18377 2592
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:18377] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:2592] "AAACCTGAGAGCTGCA" "AACCGCGCAGTCCTTC" "ATGCGATCAAAGTGCG" "ATGCGATGTACCGCTG" ...
  .. .. .. .. .. ..@ x       : num [1:3446114] 3.17 1.19 1.72 1.19 2.32 ...
  .. .. .. .. .. ..@ factors : list()

I tried to merge these two objects to get only filtered cells. But I got an error.
> bm_filtered <- merge(Seurat_Object2, as.Seurat(data_rds)[, colnames(Seurat_Object2)])
|                                                                                                                                                              |   0%Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
  |==============================================================================================================================================================| 100%
Warning message:
In CheckDuplicateCellNames(object.list = objects) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

> str(bm_filtered)
Formal class 'Seurat' [package "Seurat"] with 12 slots
  ..@ assays      :List of 4
  .. ..$ RNA     :Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:3446114] 0 1 2 5 6 9 13 22 24 27 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 1299 4251 5884 7172 8840 10176 12582 12739 12946 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 18377 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:18377] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:3446114] 10 1 2 1 4 1 29 18 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:3446114] 0 1 2 5 6 9 13 22 24 27 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 1299 4251 5884 7172 8840 10176 12582 12739 12946 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 18377 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:18377] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:3446114] 3.17 1.19 1.72 1.19 2.32 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "rna_"
  .. .. .. ..@ var.features : chr(0) 
  .. .. .. ..@ meta.features:'data.frame':	18377 obs. of  0 variables
  .. .. .. ..@ misc         : NULL
  .. ..$ exon    :Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:2824415] 0 1 2 6 13 23 24 25 27 38 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 17284 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:17284] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:2824415] 10 1 2 1 5 9 18 21 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:2824415] 0 1 2 6 13 23 24 25 27 38 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 17284 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:17284] "GFP-cassette" "ENSORLG00000016114" "ENSORLG00000012561" "ENSORLG00000017361" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:2824415] 10 1 2 1 5 9 18 21 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "exon_"
  .. .. .. ..@ var.features : chr(0) 
  .. .. .. ..@ meta.features:'data.frame':	17284 obs. of  0 variables
  .. .. .. ..@ misc         : NULL
  .. ..$ intron  :Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:948207] 0 7 10 11 21 25 30 31 33 46 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 15036 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:15036] "ENSORLG00000029794" "ENSORLG00000014696" "ENSORLG00000003723" "ENSORLG00000002306" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:948207] 1 5 1 13 9 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:948207] 0 7 10 11 21 25 30 31 33 46 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 15036 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:15036] "ENSORLG00000029794" "ENSORLG00000014696" "ENSORLG00000003723" "ENSORLG00000002306" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:948207] 1 5 1 13 9 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "intron_"
  .. .. .. ..@ var.features : chr(0) 
  .. .. .. ..@ meta.features:'data.frame':	15036 obs. of  0 variables
  .. .. .. ..@ misc         : NULL
  .. ..$ spanning:Formal class 'Assay' [package "Seurat"] with 7 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:562918] 1 11 14 18 19 20 22 24 25 27 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 13766 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:13766] "ENSORLG00000010629" "ENSORLG00000011476" "ENSORLG00000002549" "ENSORLG00000023504" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:562918] 2 2 1 5 1 2 88 20 1 7 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:562918] 1 11 14 18 19 20 22 24 25 27 ...
  .. .. .. .. .. ..@ p       : int [1:5185] 0 0 0 0 0 0 0 0 0 0 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 13766 5184
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:13766] "ENSORLG00000010629" "ENSORLG00000011476" "ENSORLG00000002549" "ENSORLG00000023504" ...
  .. .. .. .. .. .. ..$ : chr [1:5184] "AAACCTGAGAGCTGCA_1" "AACCGCGCAGTCCTTC_1" "ATGCGATCAAAGTGCG_1" "ATGCGATGTACCGCTG_1" ...
  .. .. .. .. .. ..@ x       : num [1:562918] 2 2 1 5 1 2 88 20 1 7 ...
  .. .. .. .. .. ..@ factors : list()
It gave me all cells (5185) but I only want filtered (2592). In both objects, I have different cells. How can I fix this issue. Kindly help me in this regard. Thanks

**Comment by timoast** [comment]
What's the error?
