### ISSUE TITLE
an analysis question about filtering and integrating data in Seurat3

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2577]
Dear all, 

I am following the analysis tutorials on Seurat 3 (on data integration and differential expression), 

https://satijalab.org/seurat/v3.1/integration.html
https://satijalab.org/seurat/v3.1/immune_alignment.html

and i'd have a little question about FILTERING STEP : 

at which step shall I add the FILTERING (and if it makes a difference) ? 

Th R code that i do have is : 

`ctrl <- CreateSeuratObject(ctrl.data, project = CTRL)`

(shall I add the Filtering at this point in the R code ?)

`stim <- CreateSeuratObject(stim.data, project = STIM)`

(shall I add the Filtering at this point in the R code ?)

and the next few steps : 

```
samples.combined <- merge(x=ctrl, y = stim, project = NAME)

samples.combined.list <- SplitObject(samples.combined, split.by = "orig.ident")

samples.combined.list <- lapply(X = samples.combined.list, FUN = function(x) {

```
(shall I add the Filtering at this point in the R code ?)

```
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

```

**Comment by timoast** [comment]
We typically recommend filtering cells at the earliest point in the analysis that you can

**Comment by tanasa** [comment]
thanks, Tim !
