### ISSUE TITLE
Running Seurat

### ISSUE THREAD

**Issue by Jemkon** [satijalab/seurat#258]
Hi,

I would like to use Seurat to analyse single cell RNAseq data. I have paired-end illumina reads from single cell RNA sequencing. I have already aligned reads to HG38 and used featureCounts for raw read counts. 

Now I dont know the next step to create expression matrix from this raw reads count. How do i create matrix that I can use for Seurat?

any help much appreciated.

Thanks.

**Comment by leonfodoulian** [comment]
Hi,

Could you please provide an example of the output data from `featureCounts`? The required data for Seurat is a matrix (or a data frame) with cells names in the columns, and gene names in rows. Here's an example:

```
head(object@raw.data[1:3,1:3])

              LFHT2_ROW01_01 LFHT2_ROW01_02 LFHT2_ROW01_03
0610007P14Rik       10.82694       2.549058       10.09271
0610009B22Rik        0.00000      14.000000        0.00000
0610009L18Rik        0.00000       0.000000      105.00000
```

Best,
Leon

**Comment by Jemkon** [comment]
Hi Leon,

Thanks for reply.

Here is the output from featureCounts:

##                 NA19098.r1.A01 NA19098.r1.A02 NA19098.r1.A03
## ENSG00000237683        10000        5670            340
## ENSG00000187634        0            570             530
## ENSG00000188976        1157         7140            4561
## ENSG00000187961        110          5530            460
## ENSG00000187583        4430         550             4560
## ENSG00000187642        550          550             5650

The columns are cell names and rows are genes. The values are raw read
counts (reads aligned to features, genes, exons, cds).

I need to convert it into expression matrix with normalization? I
looked for DexSeq2 but it requires conditions for two samples. as here
i dont have such conditions.

Can you guide?

Many thanks,

Alan

**Comment by leonfodoulian** [comment]
Hi Alan,

Sorry for the delay. Your dataset is ready to be inputed as `raw.data` to the `CreateSeuratObject()` function. Please follow the instructions on [this website](http://satijalab.org/seurat/pbmc3k_tutorial.html) to get familiarised with Seurat. It is a very well explained guided tutorial. If you've got specific questions regarding the analysis, or encountered some issues, you can check the [closed](https://github.com/satijalab/seurat/issues?q=is%3Aissue+is%3Aclosed) and still [open](https://github.com/satijalab/seurat/issues) issues on the GitHub page. If you don't find an answer to your question, or your question has not been asked yet, you can post another issue.

Happy new year!

Best,
Leon
