### ISSUE TITLE
RenameIdents issue using variables as ident names

### ISSUE THREAD

**Issue by BRThomson** [satijalab/seurat#2580]
Thanks for all your work on this package, and the extensive documentation--it's all great. This is the first issue I've come across that I haven't been able to solve by reading other issues, maybe it's my limited familiarity with R showing through but I don't understand what's happening and would appreciate any suggestions.

Running Seurat 3.1.1 on R 3.6.1

I'm trying to rename clusters in a seurat object using RenameIdents, which works fine with manually entered names. However, when using variables as names I'm getting an error:

The following code produces a new object where cluster 5 has been renamed 6, as expected:
`newClusters <- RenameIdents(object = oldClusters, '5' = '6')`

However, this code produces an error I can't figure out:
`x <- '5'`
`y <- '6'`
`newClusters <- RenameIdents(object = oldClusters, x = y)`
`Error in RenameIdents.Seurat(object = newclusters, x = y) : 
  All arguments must be named with the old identity class`

The following code does work:
`newClusters <- RenameIdents(object = oldClusters, '5' = y)`

I assume that x isn't the correct type, or isn't being parsed as a variable somehow but I don't know enough R to understand where I'm going wrong. 

`newClusters <- RenameIdents(object = oldClusters, as.character(x) = '6')`
does not work but
`newClusters <- RenameIdents(object = oldClusters, '5' = as.character(y))`
does.

Thanks for any help or suggestions.

**Comment by BRThomson** [comment]
I've solved this, but I'm not sure why it works exactly.

Looking at the code for the RenameIdents() function (https://github.com/satijalab/seurat/blob/master/R/objects.R), I found that the error I'm seeing is coming from this section:

`  if (is.null(x = names(x = ident.pairs))) { 
    stop("All arguments must be named with the old identity class")
  }`

Since the error I'm seeing is associated with names() being null, I've modified my code and found that the following works to rename ident "5" to "6":

`newIdent <- '6'`
`names(newIdent) <- '5'`
`newClusters <- RenameIdents(object = oldClusters, newIdent)`

I'm still unsure why passing the variables x and y rather then '5' and '6' results in names() being null, but this solution seems to work.

Thanks again for the package,
Ben

**Comment by mojaveazure** [comment]
Hi Ben,

`RenameIdents` is not designed to take variables as old identity names. Instead, we've built it in such a way that makes it clear which identity classes are being renamed and to what they're being renamed to.

As you've figured out, you can pass a named vector to `RenameIdents`, and that's due to the way R handles named vectors and the `...` in function calls (what we use in `RenameIdents`). However, passing variables as argument names simply won't work, and we have no plans to build support for this functionality at this time.

**Comment by BRThomson** [comment]
Thanks mojaveazure, that makes sense. Not sure why it didn't click to me that `RenameIdents( oldname = "newname")` was making a variable assignment in the function call rather than passing a combined "oldname = newname" value to the internal function. Appreciate you taking the time to explain.
