### ISSUE TITLE
how to remove a specific gene list (regress out perhaps) from Seurat Obrject? 

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#2581]
hi all,
 I am trying to regress out a specific list of genes from my Seurat object.
First, I created a list with the genes I would like to regress out.

`rbc.Type.Genes <- list("Hba-a1", "Hbb-y", "Hba-x", "Hbb-bs", "Hbb-bt", "Hbb-bh1", "Hba-a2")`
 
then, I tried to regress out this specific genes. 

`Seurat Object<- ScaleData(Seurat Object, vars.to.regress = c("rbc.Type.Genes"))`

But I am getting a message error as followed

`Regressing out rbc.Type.Genes
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: GENE ~ 
   ^`
I have been running around without being able to solve this problem. I guess it is because I am a new user of Seurat.
I appreciate any help, and I thank you all in advance

**Comment by satkins1** [comment]
Why not use the same principle as regressing out cell cycle effects?

Use your rbc.Type.Genes module to AddModuleScore and then include this as you would "S.Score", "G2M.Score" or "percent.mt" in vars.to.regress...

**Comment by giovanegt** [comment]
Thank you very much. It is working now. 
I think the problem was a extra "(" in the code. 
Once again, I thank you a lot!
