### ISSUE TITLE
umap plot with speckles

### ISSUE THREAD

**Issue by doctorjb77** [satijalab/seurat#2582]
![image](https://user-images.githubusercontent.com/10649344/73910633-c0fda800-4864-11ea-9fea-efa61b26108f.png)
I merged 8 objects and ran SCTranform and I'm getting these speckles on the umap that I have not seen before. What do these speckles signify?

**Comment by andrewwbutler** [comment]
Hi,

It's not really possible to say much without more information about the data and how you processed it. Very generally, something probably went wrong upstream of `RunUMAP`.

**Comment by jacksonloper** [comment]
@doctorjb77 did you ever figure it out?  we get speckles too sometimes and can't figure out what it means

**Comment by JarneBelien** [comment]
@doctorjb77 I am getting a super similar result - did you ever figure out the reason?

**Comment by JarneBelien** [comment]
@BenxiaHu I don't think there was anything particularly wrong because I did all the possible troubleshooting. I came across other people who sometimes also saw this. Solution: try different normalization and integration methods... After Harmony integration eg this did not occur anymore.

**Comment by BenxiaHu** [comment]
@JarneBelien
 thanks a lot.
 can you show the specific codes?

**Comment by JarneBelien** [comment]
@BenxiaHu I just checked my code again, and actually after all different integration methods (so also Seurat integration), the UMAP normalized, so I guess it was mainly due to the different samples/datasets not being properly integrated before visualisation.

For Seurat integration, I used the workaround appointing reference datasets to lower memory requirement as such:

```
Integration_Features <- SelectIntegrationFeatures(Split_Blood, nfeatures = 3000)

Split_Blood <- lapply(X = Split_Blood, FUN = function(x) {
    x <- RunPCA(x, features = Integration_Features, verbose = FALSE)
})

options(future.globals.maxSize = 20000*1024^2)

Split_Blood <- PrepSCTIntegration(Split_Blood, anchor.features = Integration_Features, verbose = FALSE)

Anchors <- FindIntegrationAnchors(object.list = Split_Blood, reference = c(1, 5, 10, 13, 17), reduction = "rpca", dims = 1:50, normalization.method = "SCT", anchor.features = Integration_Features)
```
For Harmony, you can just follow the vignette: https://portals.broadinstitute.org/harmony/articles/quickstart.html

Good luck!

**Comment by BenxiaHu** [comment]
thanks a lot.
do you follow this one:
https://satijalab.org/seurat/archive/v4.3/integration_introduction

**Comment by JarneBelien** [comment]
You can indeed follow that one. I followed a workaround that's less memory intensive, the one using recirpocal PCA: 
![image](https://github.com/satijalab/seurat/assets/133022501/42f4133a-dd13-4159-829e-83422854f25f)
But that vignette is not supported anymore.

**Comment by BenxiaHu** [comment]
thanks a lot.
I try this one: https://satijalab.org/seurat/archive/v4.3/integration_introduction
<img width="605" alt="image" src="https://github.com/satijalab/seurat/assets/12387462/bcd25167-e906-42be-9c1c-e0901b1abcfe">
but still see many cell speckles.

**Comment by BenxiaHu** [comment]
@JarneBelien do you see anything different from your code?

**Comment by JarneBelien** [comment]
I do not see an overt difference in the code no. You could try several things:
- make your preceding QC filtering more strict
- perform normalization and scaling in a different way, i.e. not through SCTranform
- try a different integration method eg Harmony or SCVI

Good luck!
