### ISSUE TITLE
DotPlot not showing average expression with only one Identity factor

### ISSUE THREAD

**Issue by TobiTekath** [satijalab/seurat#2583]
Hi,

I noticed a small bug in the `DotPlot()` function, when I tried to used it with a subsetted Seurat object, where only one active identity factor was left.

The produced DotPlot still shows the "Percent Expressed" correctly, but the "Average Expression" colouring is missing (all dots are grey).

This is caused by the call to `scale(x = data.use)` in

https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/visualization.R#L1937-L1945

The scaling is not useful when there is only one value per feature and returns NaNs - so all `avg.exp.scaled` values are NaN.

This could easily be patched by just checking the length of `data.use` before scaling:

```
if (length(x = data.use) > 1) {
   data.use <- scale(x = data.use)
}
```

Thanks in advance.

**Comment by satijalab** [comment]
Thanks for the feedback. The purpose of the color is to compare values across identity classes, so its a bit hard to interpret if there is only one identity class. However, we should not be returning NaN values, and will fix

**Comment by yuhanH** [comment]
Hi, Tobi 
the bug is fixed in the latest develop branch. Thanks for pointing this out.

**Comment by ZiyingZhang1** [comment]
I got the same problem. Actually, I used the lasted version, it did not work .
#Showing both legend
pdf(file=paste("merge_Dotplot_up5.pdf"),width=14,height=14)
plots <- DotPlot(project, features = as.character(ddup),assay="RNA",group.by ="celltype",cols = c("grey","red"))  + RotatedAxis() 
print(plots)
dev.off()

#Not showing the legend   Just used different features 
pdf(file=paste("merge_Dotplot_down5.pdf"))
plots <- DotPlot(project, features = as.character(unique(dddown)),assay=NULL,group.by ="celltype",scale.by = "size")  + RotatedAxis()
print(plots)
dev.off()
