### ISSUE TITLE
Cell Cycle Regression - Issue

### ISSUE THREAD

**Issue by TimJCooper** [satijalab/seurat#2584]
Using 10x Cellranger data as an input, i'm attempting to perform cell-cycle regression, however I am encountering the following error:

```
> s.genes <- cc.genes$s.genes
> g2m.genes <- cc.genes$g2m.genes
> MDSC_ss <- CellCycleScoring(MDSC_ss, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
Warning: The following features are not present in the object: MCM5, PCNA, TYMS, FEN1, MCM2, MCM4, RRM1, UNG, GINS2, MCM6, CDCA7, DTL, PRIM1, UHRF1, MLF1IP, HELLS, RFC2, RPA2, NASP, RAD51AP1, GMNN, WDR76, SLBP, CCNE2, UBR7, POLD3, MSH2, ATAD2, RAD51, RRM2, CDC45, CDC6, EXO1, TIPIN, DSCC1, BLM, CASP8AP2, USP1, CLSPN, POLA1, CHAF1B, BRIP1, E2F8, not searching for symbol synonyms
Warning: The following features are not present in the object: HMGB2, CDK1, NUSAP1, UBE2C, BIRC5, TPX2, TOP2A, NDC80, CKS2, NUF2, CKS1B, MKI67, TMPO, CENPF, TACC3, FAM64A, SMC4, CCNB2, CKAP2L, CKAP2, AURKB, BUB1, KIF11, ANP32E, TUBB4B, GTSE1, KIF20B, HJURP, CDCA3, HN1, CDC20, TTK, CDC25C, KIF2C, RANGAP1, NCAPD2, DLGAP5, CDCA2, CDCA8, ECT2, KIF23, HMMR, AURKA, PSRC1, ANLN, LBR, CKAP5, CENPE, CTCF, NEK2, G2E3, GAS2L3, CBX5, CENPA, not searching for symbol synonyms
Warning message:
In AddModuleScore(object = object, features = features, name = name,  :
  Could not find enough features in the object from the following feature lists: S.Score Attempting to match case...Could not find enough features in the object from the following feature lists: G2M.Score Attempting to match case...
```
If I alter the cell-cycle gene lists:

```
> s.genes <- str_to_title(cc.genes$s.genes)
> g2m.genes <- str_to_title(cc.genes$g2m.genes)
```
CellCycleScoring matches the genes and runs - however, I still encounter problems downstream (e.g. with RidgePlot):

```
RidgePlot(MDSC_cl, features = c("PCNA", "TOP2A", "MCM6", "MKI67"), ncol = 2)
Error in FetchData(object = object, vars = features, slot = slot) : 
  None of the requested variables were found: PCNA, TOP2A, MCM6, MKI67
```

 Is there something I can do to alter the format of my featurelist in my Seurat object (MDSC_ss)?

**Comment by TimJCooper** [comment]
All of these genes used by RidgePlot ARE present in the object.

**Comment by satkins1** [comment]
Are your feature names set to ENCODE IDs rather than HGNC names?

My 10x data from Cellranger comes with ENCODE as the default gene name so prior to creating the Seurat object I use:

rownames(raw.data) <- rowData(raw.data)[["Symbol"]]

To change to HGNC names. As I understand it there is no way to do this easily once you have created the Seurat object.

**Comment by satijalab** [comment]
Apologies - of RidgePlot (or equivalently, ViolinPlot, FetchData, etc.) is not detecting PCNA, TOP2A, MCM6, or MKI67 - then Seurat is not detecting their presence in the object.

This seems to be a capitalization issue, your gene names are likely Pcna, Top2a, Mcm6, or Mki67 - as your use of str_to_title above indicates.

Using the correct capitalization in the call to RidgePlot should fix this

**Comment by laumanzanares** [comment]
Hello,
I have the same error. I looked and in most codes it appears as a warning however in my case it appears as an error and I don't really know how to fix it. Can someone help? I'm new so apologies if it is a simple question.

patient_alpha <- CellCycleScoring(patient_alpha, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
Error: (converted from warning) The following features are not present in the object: MLF1IP, not searching for symbol synonyms

**Comment by r-osorio** [comment]
Had the same problem, it was a warning before and now is an error. I had it running successfully in the past and now it won't seem to run. I wrapped my function in suppresswarnings() and it ran fine though! Hope this helps others.
