### ISSUE TITLE
AddModuleScore generates expression values for each gene as separate metadata slots

### ISSUE THREAD

**Issue by rlorenzc** [satijalab/seurat#2585]
Hi!

I'm using AddModuleScore to get the average expression of genesets across different clusters. However, for some reason I'm getting separate metadata values with the same length as the vector that I set as my `features`. 

`subset_sample <- AddModuleScore(object = subset_sample, features = genesetA, name = 'genesetA')`

For example the `features` vector contains 10 genes, I would also have the the same number of metadata slots in my seurat object( i.e. subset_sample$genesetA1, subset_sample$genesetA2, ..., subset_sample$genesetA10).

Is this correct? If so, which slot would contain the average expression of the geneset? If not, what am I doing wrong?

I am currently using Seurat 3.1.2.

Thank you,
Lorenz

**Comment by samuel-marsh** [comment]
Hi Lorenz,

Can you paste the code that you are using to generate your "genesetA"?

Thanks,
Sam

**Comment by rlorenzc** [comment]
Hi Sam,

Thanks for the reply! I simply used:
`genesetA <- c("geneA", "geneB", "geneC, "geneD", ...)`

I also loaded the following packages:
`library(Seurat)
library(dplyr)
library(cowplot)
library(ggrepel)`

Thank you!
Lorenz

**Comment by samuel-marsh** [comment]
Hi Lorenz,

So the issue is that AddModuleScore requires gene list to be in `list()` in order to create score for a series of genes as a single score.
Just change your code to be:
`genesetA <- list(c("geneA", "geneB", "geneC", "geneD", ...))`

Then you should be good!

Best,
Sam

**Comment by rlorenzc** [comment]
Hi Sam,

This resolved my issue.  Thank you again for all your help!

Lorenz

**Comment by Henry-zhang-For** [comment]
I met the same question, but even I use "as list" for a gene set, the warning was still arriving. 
> Gene_expression <- AddModuleScore(T.obj,
+                           features = Fea,
+                           ctrl = 100,
+                           name = "Fea")

**Comment by samuel-marsh** [comment]
Hi,

So the issue is using `as.list()` instead of `list()`.  `as.list` will create a list with the number of lists as long as the vector with one element per list.  `list()` will create a list list with single list containing all elements of the vector.

Best,
Sam

**Comment by Henry-zhang-For** [comment]
Wow, thank you so much for your help. It totally resolve my problem. I don't discover the difference between these.  And I resolve previous problem, too.
Thanks again! Best,
Zhang
