### ISSUE TITLE
DimPlot tSNE split.by overlayed to the full tSNE 

### ISSUE THREAD

**Issue by francescarivello** [satijalab/seurat#2586]
Hi! I am plotting my tSNE plot split.by="orig.ident" which are my different samples so I can see the cell clusters expressed per sample. I would like to overlay it to the full t-SNE comprehending all the cells not splitted per sample in light grey for example.
So basically I would like to overlay these two plts:
DimPlot(Seurat_object, reduction = "tsne", pt.size = 1.5) #in light grey on the background
DimPlot(Seurat_object, reduction = "tsne", pt.size = 1.5, split.by="orig.ident") #with the different clusters colored
Anyone has an idea on how to do that?

**Comment by mojaveazure** [comment]
Hi,

While Seurat doesn't have this functionality built-in, you can approximate it using [`levels`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/Idents), [`CellsByIdentities`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/CellsByIdentities), the [`cells.highlight`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/DimPlot) parameter, and [`CombinePlots`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/CombinePlots)

```R
plots <- lapply(
  X = levels(Seurat_object),
  FUN = function(x) {
    return(DimPlot(
      Seurat_object,
      reduction = "tsne",
      pt.size = 1.5,
      cells.highlight = CellsByIdentities(Seurat_object, idents = x)
    ))
  }
)
CombinePlots(plots)
```

This will use whatever the active identity classes are; to change the active identity classes, please see the [`Idents<-`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/Idents) function.

**Comment by francescarivello** [comment]
Hi! Thank you for the quick answer. In this way indeed I see one cluster per plot with on the back the full t-SNE.
But I would have liked to see different plots based on the orig.ident instead than on the clusters and still highlight in each of these plots the different clusters presents. Do you think there is an easy way to implement that?
