### ISSUE TITLE
Integrating datasets using SCTransform generating v.large files

### ISSUE THREAD

**Issue by satkins1** [satijalab/seurat#2587]
I am trying to integrate a number of 10X datasets from published studies and some of our own data. The data is spread across several subjects with several runs per subject - total number of individual runs is 24 and the number of cells around 90k.

I have been following the Seurat vignettes to integrate using SCTransform. The initial step involves splitting the Seurat of all cells into a list of Seurats defined by the level of technical variation to remove (as I understand it). I have elected to do this at the level of 10X runs, ie:

`list <- SplitObject(seurat, split.by = "Fileset_name")
`

Gives me a list of 24 individuals Seurats, the combined total size of the list at this stage is around 2.9Gb.

I then perform SCTransform on each Seurat in turn as per the vignette:

```
for (i in 1:length(list)) {
    list[[i]] <- SCTransform(list[[i]], verbose = FALSE)
}
```

Though I elected to achieve this with some additional actions through lapply() (as it seems that this is a more memory efficient method of assigning elements to a list in R) resulting in:

```
list <- lapply(list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- CellCycleScoring(x, s.features = s.genes, g2m.features = g2m.genes, set.ident=FALSE)
  x <- ScaleData(x, vars.to.regress = c("S.Score", "G2M.Score", "percent.mt", "percent.rb"))
  x <- SCTransform(x, vars.to.regress = c("S.Score", "G2M.Score", "percent.mt", "percent.rb"))
})
```
The final list of objects when returned using this methodology is around 25GB in size which is giving me memory issues on the system I am using currently. If I simply run the SCTransform command on the entire Seurat without splitting it first the resulting object is around 7.4GB in size.

I would appreciate advice on:

1. Is it anticipated that the list of Seurats processed individually should be around 3x larger than if processed as a single object (where is the extra data coming from)?
2. If not any suggestions on where I am going wrong would be appreciated
3. If yes is there an alternative solution to having to try and load such a large object into memory in order to proceed to the next stages of integration

Thanks

**Comment by yuhanH** [comment]
Hi, 
It is expected that the list of SCT normalized objects is bigger than the single object. SCTransform will produce the parameter tables in the SCT misc slot, `object[["SCT"]]@misc`  to each object in the list.  Those tables will be used in the integration process.
 After integration, you can get rid of those tables to make the object smaller.

**Comment by michaellehmann** [comment]
Hi yuhanH,

Can you post code that will allow me to remove the parameter tables after SCT integration. Thanks!

**Comment by yuhanH** [comment]
You can delete the models in the SCT assay in this way `obj.integrated[["SCT"]]@misc <- NULL`
