### ISSUE TITLE
vars.to.regress in ScaleData

### ISSUE THREAD

**Issue by biounix** [satijalab/seurat#2588]
Hi,

I noticed that when using `ScaleData` function (Seurat 3.1.1) with `vars.to.regress` with more than one variable, the function does not complain if any of the variables is wrong or does not exist, as long as at least one of them exists. Thus, creating the impression that the regression is carried out over all of them, even if they do not exist in the meta.data slot. That can lead to silent mistakes after a typo or the user not loading the meta.data correctly.

I suggest that adding a warning, as in other functions when a feature is missing, for instance, can save some headaches.

Thanks a lot,

**Comment by satijalab** [comment]
I agree that adding a warning is a good idea - we will fix (@timoast).

**Comment by timoast** [comment]
This is updated now on the develop branch

**Comment by Yinglei1** [comment]
> Hi,
> 
> I noticed that when using `ScaleData` function (Seurat 3.1.1) with `vars.to.regress` with more than one variable, the function does not complain if any of the variables is wrong or does not exist, as long as at least one of them exists. Thus, creating the impression that the regression is carried out over all of them, even if they do not exist in the meta.data slot. That can lead to silent mistakes after a typo or the user not loading the meta.data correctly.
> 
> I suggest that adding a warning, as in other functions when a feature is missing, for instance, can save some headaches.
> 
> Thanks a lot,

Hi, 
You said “the function does not complain if any of the variables is wrong or does not exist, as long as at least one of them exists.” I have no idea how to add the warning. 
Thanks in advance!
