### ISSUE TITLE
an error when computing Differential Expression in Seurat 2.3.4

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2591]
Dear all, 

we are slowly moving from Seurat 2.3.4 to Seurat 3, and if you do not mind, my question is about Seurat 2.3.4 (it will take us a while to re-run all the samples). 

we have 2 samples **(WT, MUT)** on each of 5 time points (time1, ..., time5); and when I compute Differential Expression on Cluster_5 between **WT versus MUT**, I am getting the following error : 

```
Error in if (all(unlist(x = strsplit(x = my.var, split = "[0-9]+")) ==  : 
  missing value where TRUE/FALSE needed
Calls: VlnPlot -> data.frame -> FetchData
Execution halted
```

although there are lots of cells **in Cluster_5 in both WT and MUT conditions**. Thanks a lot ;) !

-- bogdan

**Comment by andrewwbutler** [comment]
Hi,

Based on the error it looks like you are trying to do a violin plot? Is it possible that you're trying to plot a feature that has some unusual characters in it's name?

**Comment by tanasa** [comment]
Dear Andrew, thank you for your reply. I will double check ..

**Comment by tanasa** [comment]
Dear Andrew, thank again for your reply, it has been an oversight on my side ; after the following piece of R code below, I was trying to print more differential markers than available in the list : 


```
IDENT1=paste0(i, "_", CTRL)
IDENT2=paste0(i, "_", STIM)

 LIST.CLUSTERS.and.DIFFERENTIAL.MARKERS[[i+1]] <- FindMarkers(samples.combined, 
                                                                                 ident.1 = IDENT1, 
                                                                                 ident.2 = IDENT2, 
                                                                                 print.bar = FALSE, only.pos = FALSE)

   ### printing all (or the initial 30 DIFFERENTIAL MARKERS) in a CELL CLUSTER
   x <- as.data.frame(as.matrix(LIST.CLUSTERS.and.DIFFERENTIAL.MARKERS[[i+1]]))  
   x$gene <- row.names(x)

   write.table(x, file=paste(NAME, "figure8.samples.combined.here.DIFFERENTIAL.MARKERS.cluster", i, "LIST.txt", sep="."), 
                        sep="\t", quote=F, row.names=T, col.names=T)
    
   x_count_genes = dim(x)[1]
```
