### ISSUE TITLE
Trouble in instillation of Seurat v3.2

### ISSUE THREAD

**Issue by vHelmholtz** [satijalab/seurat#2592]
I have trouble with the installation of Seurat v3.2 as below. Could you give me advice about this issue?

**> devtools::install_github("satijalab/seurat", ref = "spatial")**
Downloading GitHub repo satijalab/seurat@spatial
Skipping 3 packages ahead of CRAN: multtest, BiocGenerics, Biobase
Installing 1 packages: stringi
Installing package into ‘C:/Users/jongshin.kim/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.4.4  1.4.5              TRUE

installing the source package ‘stringi’

trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.4.5.tar.gz'
Content type 'application/x-gzip' length 7284255 bytes (6.9 MB)
downloaded 6.9 MB

ERROR: failed to lock directory 'C:/Users/jongshin.kim/Documents/R/win-library/3.6' for modifying
Try removing 'C:/Users/jongshin.kim/Documents/R/win-library/3.6/00LOCK-stringi'
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘stringi’ had non-zero exit status

**Comment by timoast** [comment]
Try removing 'C:/Users/jongshin.kim/Documents/R/win-library/3.6/00LOCK-stringi'
