### ISSUE TITLE
Cell cycle regression_Integrate data

### ISSUE THREAD

**Issue by priyamnarain** [satijalab/seurat#2594]
Hi,

I am trying to regress out cell cycle genes on integrated data and gettin the following error after setting "features.to.integrate=all_genes"

**> CIRCADIAN.combined <- IntegrateData(anchorset = CIRCADIAN.anchors, dims = 1:20,features.to.integrate = all_genes)
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing**

**Comment by satijalab** [comment]
Apologies - its hard to get a sense of where the error is arising without seeing the earlier steps where you perform regression .Would you be able to post the full workflow? Thanks!
