### ISSUE TITLE
question about gene activity matrix

### ISSUE THREAD

**Issue by ahmedabbas81** [satijalab/seurat#2595]
Dear all,

I am trying to create the gene activity matrix. But I cannot read "filtered_peak_bc_matrix.h5" file. The function Read10X_h5() is not working with me.

The following code is not working:

mex_dir_path <- "filtered_peak_bc_matrix"
mtx_path <- paste(mex_dir_path, "matrix.mtx", sep = '/')
feature_path <- paste(mex_dir_path, "peaks.bed", sep = '/')
barcode_path <- paste(mex_dir_path, "barcodes.tsv", sep = '/')

features <- readr::read_tsv(feature_path, col_names = F) %>% tidyr::unite(feature)
barcodes <- readr::read_tsv(barcode_path, col_names = F) %>% tidyr::unite(barcode)

mtx <- Matrix::readMM(mtx_path) %>%
  magrittr::set_rownames(features$feature) %>%
  magrittr::set_colnames(barcodes$barcode)

activity.matrix <- CreateGeneActivityMatrix(peak.matrix = mtx, annotation.file = "Mus_musculus.GRCm38.98.gtf",seq.levels = c(1:19, "X","Y"), upstream = 2000, verbose = TRUE)

The above code gives me the next error:
Error in names(x) <- value : 
  'names' attribute [3] must be the same length as the vector [1]

Any suggestion please?

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Can you provide a reproducible example? My guess is that there is something different about the structure of the rownames of your peak matrix. You could compare what you have here to the example in the [vignette](https://satijalab.org/seurat/atacseq_integration_vignette.html) to try to get a sense for what's different. Another option would be to try to signac procedure for creating this activity matrix. See this [vignette](https://satijalab.org/signac/articles/pbmc_vignette.html) for an example.

**Comment by ahmedabbas81** [comment]
Thank you, I managed to go around the problem
