### ISSUE TITLE
Error in installing Seurat

### ISSUE THREAD

**Issue by Manojbioinfo** [satijalab/seurat#2596]
Dear member,
I am trying to install Seurat in R v 3.4.3 or 3.6.1 or 3.6.2 or 3.5.1 of Ubuntu 18/Window 10 by using the command install.packages('Seurat') and every time I am getting error that Seurat is not available for these R version.

Please help

**Comment by rozovr** [comment]
Same here.
I'm seeing this on CRAN:
<img width="747" alt="Screen Shot 2020-02-10 at 12 46 32" src="https://user-images.githubusercontent.com/6791673/74143441-7cc32c80-4c03-11ea-9f5e-ff52d29d072b.png">

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/2589
