### ISSUE TITLE
RNA Velocyto using Seurat: UMAP dimensions

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#2597]
Hi 
I have a plot after running Velocyto using Seurat. 
[Filtered_cells_S1_velocyto_dim20.pdf](https://github.com/satijalab/seurat-wrappers/files/4181098/Filtered_cells_S1_velocyto_dim20.pdf)
I want to zoom into the upper clusters, where the dimensions are following UMAP_1 >-5 and UMAP_2 >5.
I tried to save these dimensions like this way.
> umap <- data.frame(bm@reductions$umap@cell.embeddings, row.names = rownames(bm@reductions$umap@cell.embeddings)

Could you plz tell me how can I plot only a specific dimension in Velocyto? 
Thanks

**Comment by basilkhuder** [comment]
First, create a data frame with the filtered UMAP coordinates of interest:

`umap <- as.data.frame(Embeddings(seurat_obj, reduction = "umap"))`

Then filter based upon the coordinates, while keeping the Cell IDs. 

`umap[umap$UMAP_1>-5 & umap$UMAP_2 >5,]`

You'll now have to filter your loom file for the cells that pertain to those UMAP coordinates. This will allow you to plot only those specific dimensions in Velocyto.

**Comment by sikh09** [comment]
Thanks @basilkhuder .

**Comment by sikh09** [comment]
How can I do filtration in the Seurat object/ loom file?

**Comment by basilkhuder** [comment]
> How can I do filtration in the Seurat object/ loom file?

Are you using Velocyto.R or Velocyto in Python?

**Comment by sikh09** [comment]
I am using Velocyto.R in Seurat.

**Comment by basilkhuder** [comment]
> I am using Velocyto.R in Seurat.

I haven't used the Velocyto R package much, but I'm assuming you're following [this guide](https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/velocity.html). If so, you should be able to just subset your Seurat object based upon the filtered UMAP cell IDs (rownames.) 

`seurat_subset <- subset(seurat_obj, cells = rownames(umap)`

**Comment by sikh09** [comment]
Thanks a lot. it worked.

**Comment by Drosophilist** [comment]
> How can I do filtration in the Seurat object/ loom file?

@basilkhuder Hello, I'm really interested in the answer to the question above but for Velocyto.py. My current objective is to run Velocyto on the same filtered cells of my Seurat object and have the same UMAP coordinates and clusters as in the Seurat analysis. Could you give me some guidance on how to export the cluster information, UMAP coordinates from Seurat, and filter the velocyto loom file to the same cells as Seurat? 
Not really an expert with python and some help would be extremely appreciated! 

Cheers,
Jose

**Comment by basilkhuder** [comment]
> > How can I do filtration in the Seurat object/ loom file?
> 
> @basilkhuder Hello, I'm really interested in the answer to the question above but for Velocyto.py. My current objective is to run Velocyto on the same filtered cells of my Seurat object and have the same UMAP coordinates and clusters as in the Seurat analysis. Could you give me some guidance on how to export the cluster information, UMAP coordinates from Seurat, and filter the velocyto loom file to the same cells as Seurat?
> Not really an expert with python and some help would be extremely appreciated!
> 
> Cheers,
> Jose

I wrote a guide about this on my Github: 
https://github.com/basilkhuder/Seurat-to-RNA-Velocity
Read through that and post any questions you may have as an issue.

**Comment by Drosophilist** [comment]
Wow, incredible! Thank you very much.
All the best,
Jose
