### ISSUE TITLE
Error running ValidateClusters

### ISSUE THREAD

**Issue by brshres** [satijalab/seurat#26]
I keep getting the following error when trying to run **ValidateClusters(abc, pc.use = c(1:10) )**, where abc is a Seurat object that I have run **FindClusters()** on with the same set of PCs without any problem. 

_Error in as.data.frame.default(x[[i]], optional = TRUE) :  cannot coerce class "structure("dgCMatrix", package = "Matrix")" to a data.frame_

Any suggestions or insights would be appreciated.

**Comment by andrewwbutler** [comment]
This should be resolved in v2.0. Please reopen if not though.
