### ISSUE TITLE
Conda or Bioconductor support?

### ISSUE THREAD

**Issue by romanhaa** [satijalab/seurat#260]
Hi guys!

Are you planning to add the Seurat package to the Conda or Bioconductor repository anytime soon? I manage my workflows through conda environments for reproducibility reasons and Bioconductor packages are (at least it seems) automatically added to the Conda repository. It would help me a lot and I'm sure it would also make Seurat more attractive to others.

Cheers,
Roman

**Comment by satijalab** [comment]
Hi Roman,

Thanks for your interest. We'd love to support this, and certainly plan to add more support/interconversion in the future. Stay tuned!

best,
Rahul

**Comment by romanhaa** [comment]
Thanks, that's great to hear!

As I mentioned before, maybe putting Seurat on Bioconductor would be an easy way to increase outreach as they have their own channel in the Conda repository which would make it available there without any extra work. But I never submitted an R package to Bioconductor so I don't know what requirements they have compared to CRAN (and having it in both is not recommended for obvious reasons).

Anyway, thanks again!
