### ISSUE TITLE
Seurat v2/3 package in R CRAN was archived without any notice/warning/reason !

### ISSUE THREAD

**Issue by BIOBRICK** [satijalab/seurat#2601]
I hope that the members of the development team could notice that your R package has been classified as "archive" in R CRAN, and again there seems to be no related notices. Although I can still install form source ,this is very painful way for many rookies. Until now (2020-02-11), We still cannot install directly form CRAN repo. 

Many thanks to the development team for bringing us such a good single-cell analysis R component, I hope such a good tool will not be buried.
：）

**Comment by samuel-marsh** [comment]
Please see: #2589
