### ISSUE TITLE
Issue with DimPlt & Split by

### ISSUE THREAD

**Issue by Haitham-Hajjo** [satijalab/seurat#2602]
Hi, 
I have 2 conditions in my Seurat object. 
I want to display their UMAO projection separately. 
I used this command as described in the vignette 
DimPlot(immune.combined, reduction = "umap", split.by = "orig.ident") 

But, in the output, the same cluster in the different conditions is colored differentially. 
I need the same cluster in the 2 conditions to be colored by the same color. 

Thanks for you help, 
H

**Comment by basilkhuder** [comment]
By default, `DimPlot()` will color cells by their identities. See below:

> By default, cells are colored by their identity class (can be changed with the group.by parameter).

`group.by	`

> Name of one or more metadata columns to group (color) cells by (for example, orig.ident); pass ident' to group by identity class
