### ISSUE TITLE
Discrepancy in PBMC Reference

### ISSUE THREAD

**Issue by basilkhuder** [satijalab/seurat#2603]
I'm currently testing [SoupX](https://github.com/constantAmateur/SoupX) for the issue of ambient-RNA, which requires both the filtered and unfiltered CR counts. I just noticed that for the PBMC dataset, filtered genes are within an hg19 folder, while the raw are within GRCh38. Could somebody clarify which reference these samples used?

**Comment by andrewwbutler** [comment]
Which PBMC dataset are you referring to here?
