### ISSUE TITLE
data frame to dgCMatrix and then seurat object

### ISSUE THREAD

**Issue by Tushar-87** [satijalab/seurat#2604]
Dear all, 

I have a tsv file with following column heads
gene cell count

Under the column gene: there are gene names (same gene name may appear more than once, nonunique)
Under the column cell: there are cell barcodes (same barcode may appear more than once, nonunique)
Under the column count: number of umi

I read the tsv file in r using read.table function to obtain a data frame with the same column heads (gene cell count)
Now I want to convert that data frame to dgCMatrix so that I can use createseurateobject function.
Another problem, I cannot assign unique rownames using the characters in gene column as they are non-unique.
I looked into issues posted here but I could not find solution although there are similar problems faced by others.

Best wishes,
Tushar

**Comment by Tushar-87** [comment]
problem solved, here:
https://stackoverflow.com/questions/60189902/how-to-reshape-and-then-convert-a-data-frame-into-dgcmatrix/60190780?noredirect=1#comment106469434_60190780

**Comment by st-tky** [comment]
This was helpful when converting a single tsv file from GEO into a Seurat object.
Thanks for sharing!

**Comment by Voltarikk** [comment]
hi,I'm trying to read a dgCMatrix data,but failed to convert it into Seurat object.I have no choices,could you help me to solve it thanks！
here is my code and traceback.
`library(Seurat)
library(SeuratDisk)
library('loomR')

sdata <- readRDS(file="D:/code/single_cell/github_code/harmony2019/data/figure3/exprs_30k.rds")

sdata.loom <- as.loom(x = sdata, filename = "D:/code/single_cell/github_code/harmony2019/data/figure3/data.loom", verbose = FALSE)

sdata.loom$close_all()`
**Error: Unable to coerce an object of class dgCMatrix to a Seurat object**
