### ISSUE TITLE
Error in install seurat V3.1.0 on macOS Mojave 10.14.5

### ISSUE THREAD

**Issue by ensiferum877** [satijalab/seurat#2606]
Hi there,

I tried to install Seurat 3.1.0 in R 3.6.1 and I got the following error:

installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB

 *** caught segfault ***
address 0x70, cause 'memory not mapped'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
 7: reticulate::py_module_available("leidenalg")
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
15: asNamespace(ns)
16: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
17: loadNamespace(name)
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(expr, names, parentenv, handlers[[1L]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch(loadNamespace(name), error = function(e) {    warning(gettextf("namespace %s is not available and has been replaced\nby .GlobalEnv when processing object %s",         sQuote(name)[1L], sQuote(where)), domain = NA, call. = FALSE,         immediate. = TRUE)    .GlobalEnv})
22: ..getNamespace(c("Seurat", "3.0.1"), "pbmc_small")
23: load(zfile, envir = tmp_env)
24: utils::data(list = f, package = package, lib.loc = lib.loc, envir = dataEnv,     overwrite = TRUE)
25: data2LazyLoadDB(pkg_name, lib, compress = data_compress)
26: doTryCatch(return(expr), name, parentenv, handler)
27: tryCatchOne(expr, names, parentenv, handlers[[1L]])
28: tryCatchList(expr, classes, parentenv, handlers)
29: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
30: try(data2LazyLoadDB(pkg_name, lib, compress = data_compress))
31: do_install_source(pkg_name, instdir, pkg, desc)
32: do_install(pkg)
33: tools:::.install_packages()
An irrecoverable exception occurred. R is aborting now ...
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34:  5289 Done                    echo 'tools:::.install_packages()'
      5290 Segmentation fault: 11  | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7b/stv1v9_d4nvg0_31qmdnnlsr0000gn/T//RtmpgD15qm/file125929076d7a/Seurat_3.1.3.tar.gz’ had non-zero exit status

Somebody has experience a similar error ? 

Many thanks,

Felipe

**Comment by andrewwbutler** [comment]
Hi Felipe,

It looks like you're trying to install `3.1.3`? This is the latest release and I would try installing from CRAN with `install.packages("Seurat")` if that's the case. 

However, if you really need `3.1.0`, can you try installing from a fresh R session and see if that resolves the issue. I assume you are running `devtools::install_github("satijalab/seurat", ref = "v3.1.0")`

**Comment by ensiferum877** [comment]
Hi Andrew,

I have tried to install both versions but it is not really working. When I try to install seurat using devtools I get the error that I described in my first message. Additionally, when I try to install Seurat from CRAN, I get  a very similar mistake:

> install.packages('Seurat')
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://stat.ethz.ch/CRAN/bin/macosx/el-capitan/contrib/3.6/Seurat_3.1.3.tgz'
Content type 'application/x-gzip' length 3204699 bytes (3.1 MB)
==================================================
downloaded 3.1 MB


The downloaded binary packages are in
	/var/folders/7b/stv1v9_d4nvg0_31qmdnnlsr0000gn/T//RtmpJN2jr5/downloaded_packages
> library(Seurat)
2020-02-15 17:29:29.756 R[7944:2286316] dataFromGeneratingCandidatesForSelectedRange timed out

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
 7: reticulate::py_module_available("leidenalg")
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
15: asNamespace(ns)
16: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
17: loadNamespace(package, lib.loc)
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(expr, names, parentenv, handlers[[1L]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
22: library(Seurat)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

Not quite sure what it is not working

**Comment by satijalab** [comment]
This is a problem that is not directly due to Seurat, but seems to be a general issue where there is a mismatch between library versions in your R install.

There is detailed information and a few proposed solutions here:
https://stackoverflow.com/questions/49190251/caught-segfault-memory-not-mapped-error-in-r

I am closing this issue for now but please re-open if this does not fix.
