### ISSUE TITLE
AverageExpression split.by option

### ISSUE THREAD

**Issue by LooLipin** [satijalab/seurat#2607]
Hi there,

We can generate dotplots with split.by option but I was wondering if there is a way for me to pull out the average expression of a gene of interest from each cluster by its condition, ie

```R
AverageExpression(object, assay = "RNA", features = "GeneofInterest", split.by = "condition")
```
I would like to get a numerical value to go with the dotplots.

Thanks,
Lipin

**Comment by andrewwbutler** [comment]
Hi Lipin,

Please see the `add.ident` parameter. I believe that should accomplish what you need here but if not feel free to reopen.
