### ISSUE TITLE
AddModuleScore

### ISSUE THREAD

**Issue by dylanmr** [satijalab/seurat#261]
Hi Again,

I posted about an issue with the addModuleScore function which was recently fixed and updated. However, the new function now generates a separate score for each gene in the module that I attempt to create. So when I try and calculate a stemness score with a set of 50 genes, the output is 50 columns of scores added to the meta-data. I assume that the score should be an average of all these scores? I was unsure how to handle this output. 

Any advice would be greatly appreciated. 

Best,
Dylan

**Comment by leonfodoulian** [comment]
Hi,

Is your `genes.list` input a vector of gene names? If yes, then you'll get an independent score for each gene. To get a single score, your input should be a list of a character vector of gene names. 

```
# Create a list of a vector of gene names for score computing
genes.for.scoring <- list(c("Actb", "Gapdh", "Rps9"))

# Create Stemness score using 'genes.for.scoring'
object <- AddModuleScore(object = object, genes.list = genes.for.scoring, enrich.name = "StemnessScore", random.seed = 1)
```

For more details, please refer to the R documentation of the function (by running `?AddModuleScore`).

Best,
Leon

**Comment by dylanmr** [comment]
Hi Leon, 

My gene list is in list format, yet I still receive a score for each gene. 

Best
Dylan

**Comment by leonfodoulian** [comment]
Can you please share your code?

**Comment by leonfodoulian** [comment]
Hi Dylan,

I received an e-mail from you, but you seem to have deleted the post. Did you fix the issue?

Best,
Leon

**Comment by dylanmr** [comment]
Hi Leon, 

Apologies, I did fix the issue. I had tested my code the wrong way, your advice worked as directed. Thank you for your help! 

Dylan

**Comment by leonfodoulian** [comment]
Great! Could you please close this issue?

Best,
Leon

**Comment by Leoarie-lab** [comment]
Hello everyone, 
I am sorry but do you know how to calculate (subtract) 2 AddModuleScore.
I mean we will run subtype score for genlist1 and genlist2 by AddModuleScore and how can we show the combined score = max [0,Sgenlist1[ - max [0,Sgenlist[. in AddModuleScore.
Thank you very much.
