### ISSUE TITLE
Parallel analysis, gives some selection error while running the FindIntegrationAnchors function ?

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2611]
Hi
Got a selection error, see below?

```{r}

anchors <- FindIntegrationAnchors(object.list = combined.organ,reference =c(1,4), reduction = "rpca",dims = 1:15)
combined.organ.Integrated <- IntegrateData(anchorset = anchors, dims = 1:15)

```

**Error in serialize(data, node$con) : error writing to connection**

**Comment by andrewwbutler** [comment]
Can you try restarting R and running again? It's also possible that you're running out of memory here. Does it run if you don't parallelize it?
