### ISSUE TITLE
 'names' attribute [10738] must be the same length as the vector [10700] in FindTransferAnchors

### ISSUE THREAD

**Issue by CSBioAzim** [satijalab/seurat#2614]
Hi,

I have integrated multiple scATAC files using Signac, here is how does the final integrated scATAC file looks like :
```
> brain
An object of class Seurat 
63015 features across 10738 samples within 2 assays 
Active assay: peaks (42851 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: lsi, umap, harmony

```
I want to annotate the scATAC clusters in 'brain' object using my scRNA-seq object which looks like this:
```
> RNA_Seq
An object of class Seurat 
33538 features across 30809 samples within 1 assay 
Active assay: RNA (33538 features)
 2 dimensional reductions calculated: pca, umap
```
I computed gene activity matrix for the integrated scATAC object as follow:
```
gene.activities <- FeatureMatrix(
  fragments = "/Users/jimi/Desktop/ATAC//fragment_files/fragments.tsv.gz",
  features = genebodyandpromoter.coords,
  cells = colnames(brain),
  chunk = 20
)

```
and until now everything looks good
```
> dim(gene.activities)
[1] 20164 10738

> gene.activities[1:4,1:4]
4 x 4 sparse Matrix of class "dgCMatrix"
           AAACGAAAGAACGACC-1 AAACGAAAGAGTCCGA-1 AAACGAAAGGGCTCTC-1 AAACGAAAGTTAGCAA-1
OR4F5                       .                  .                  .                  .
AL627309.1                  .                  .                  .                  .
AL669831.1                  .                  .                  .                  .
AL645608.2                  .                  .                  .                  .

```
When I add gene.activities to the atac files and try to normalize it as follow, I get an error
```
brain[['RNA']] <- CreateAssayObject(counts = gene.activities)
brain <- NormalizeData(
  object =brain,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(brain$nCount_RNA)
)

Performing log-normalization
Error in names(data.return) <- rep.int(x = colnames(x = x), times = length(x = i)) : 
  'names' attribute [10738] must be the same length as the vector [10700]
```

Or when i further want to find the anchors between ATAC and RNA, I get the following error:

```
> transfer.anchors <- FindTransferAnchors(
+   reference = RNA_Seq,
+   query = brain,
+   reduction = 'cca',
+   query.assay='RNA'
+   #reference.assay = "RNA"
+ )
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
```
I was wondering cas someone help me with it?

**Comment by andrewwbutler** [comment]
Hi,

If you run `LogNormalize`directly on the `gene.activities` matrix, does that give the same error? Also, if you could provide an example (maybe on a random subset of your data) that we would be able to reproduce, that would be helpful for debugging on our end.

**Comment by laurabchopp** [comment]
Hi @CSBioAzim and @andrewwbutler,

I've run into the exact same issues.
For the first issue, I managed to normalize the RNA assay by dropping the scale.factor command.

However, I haven't found a way around the issue with finding transfer anchors between my scRNAseq and scATACseq datasets.

I get the same error:
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**Comment by sanjeevRJMU1** [comment]
Running into the same issue here at the FindTransferAnchors step for scATACseq+scRNAseq (which until very recently was working, only change was an update to v3.1.3).

Ran my script on cluster and got an extra line for the error that maybe can help with debugging?

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: FindTransferAnchors ... RenameCells.Seurat -> RenameCells -> RenameCells.Assay
Execution halted

**Comment by sanjeevRJMU1** [comment]
update: I think there may be something specific to v3.1.3. I just downgraded to v3.1.1 and re-ran the same script with the same data and FindTransferAnchors worked just fine. A temp fix, while the seurat team is debugging, would be to check your version and maybe 3.1.1 works for you as well....

**Comment by rojinsafavi** [comment]
I am getting the same error even though I switched to Seurat 3.1.1

**Comment by Roger-GOAT** [comment]
I get the same error. Can anyone give a suggestion?

**Comment by Ruismart** [comment]
> I get the same error. Can anyone give a suggestion?

hi, I'm searching other issues for FindTransferAnchors(), but I think I may have answer for this ' 'names' attribute [xi] must be the same length as the vector [xii]' question.    

xi is 'cell number' of a seurat object, you could get it as 'length(rownames(seur.object@metadata))' , xii is length of seur.object@active.ident.  'xi != xii ' would cause this kind of error.

for a normal 10x scRNAseq experiment, you may name a cell as 'Batch_Sample.barcode', then this active.ident may name as 'Batch_Sample' or just 'Batch', active.ident is a factor vector which could be built from the cell names or related batch info, or could be easily defined like this:    

seur.object@active.ident <- factor(rep("your_ident"), length(rownames(seur.object@meta.data))))
names(seur.object@active.ident) <- rownames(seur.object@meta.data)
