### ISSUE TITLE
Looping subset() with backticks rather than quotes

### ISSUE THREAD

**Issue by DanielWendisch** [satijalab/seurat#2619]
Hello,
this is somewhat of a R issue but it only came up using Seurat and I couldn't find a solution yet elsewhere for it either. So maybe there is an easy Seurat work-around.
I want to create multiple graphs based on different subsets of my Seurat object, that are defined by the expression of certain genes (eg. CD80>1).  For this I want to iterate through a vector of genes that I feed into

obj_subset<- subset(obj, subset = subs_mark>1)
.
 This doesn't work because the character vector obviously has characters in double quotes as elements (eg. "CD80") but the expression
subset(obj, subset = subs_mark>1)
only allows backticks (eg. `CD80` )or no quotes. 
Creating a vector with c( 'gene1', `gene2` ) also results in a normal character vector. 
How can I create multiple subsets in an automated fashion based on gene expression?
Help very much appreciated!
Best,
Daniel

subset_markers <- c("gene_C","gene_D")

for (subs_mark in subset_markers) {
obj_subset<- subset(obj, subset = subs_mark>1)
}

Fehler in FetchData(object = object, vars = expr.char[vars.use], cells = cells,  : 
  None of the requested variables were found: 

(Fehler is German for Error)

**Comment by satijalab** [comment]
Thanks for a good question. The subset function itself was meant primarily for interactive use, but there are other workflows which can accomplish the same goal, for example:
```
obj_subset <- obj[, GetAssayData(obj[[assay]])[subs_mark, ] > 1]
```
