### ISSUE TITLE
Regress confounders using variables form meta.data

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#262]
Hi 
i would like to regress my data using the command 

```R
data <- ScaleData(object =data, vars.to.regress = c("percent.mito", "orig.ident", "nUMI"), genes.use = data@var.genes, model.use = "negbinom")
```
 
i would like to use as a variable a column of my meta.data, that i have named "Patient", instead of using the variable "orig.ident". nevertheless, this seems not to be working, as i obtain comparable results if including the variable "Patient" or not including it. 
How can i do this differently? 
Thanks

**Comment by leonfodoulian** [comment]
Hi,

Do you expect any differences? When you plot your gene expression levels of your variable genes for each level in your `Patient` column, do you see any difference in gene expression levels? Also, could you please share your code?

Best,
Leon

**Comment by annecar** [comment]
Thanks for your answer. 
If i run 
data <- ScaleData(object =data, vars.to.regress = c("percent.mito",  "nUMI"), genes.use = data@var.genes, model.use = "negbinom")
and then run tSNE i find a cell distribution that is clearly keeping cells from each sample toghether. I have 10 patients, each patient has 3 samples, these 3 samples were run on the same 10x chip. I wanted to regress out the batch effect, by regressing for "Patient". 
i then used 
data <- ScaleData(object =data, vars.to.regress = c("percent.mito", "Patient", "nUMI"), genes.use = data@var.genes, model.use = "negbinom")

which gave me a pattern identical to the first version. which made me think, that someting went wrong with the regression. 
Regressing out for data <- ScaleData(object =data, vars.to.regress = c("percent.mito", "orig.ident", "nUMI"), genes.use = data@var.genes, model.use = "negbinom")

gives me of course data where cells from each sample are spread all over the place, but i think this correction is not be correct, as 3 samples are form the same batch and shuld be kept toghether.

**Comment by leonfodoulian** [comment]
Hi @annecar,

So if I understand correctly, the difference between the 2 variables is that your `orig.ident` variable has a distinct level attributed to each of the samples (3 samples for 10 patients = 30 distinct levels), whereas your `Patient` variable has only 10 levels (one for each patient). Is that correct? If both variables are identical, there shouldn't be any difference between both approaches. Also, do you expect that cells from all patients be intermingled, or that you've got patient induced biases in profiled cells? Also, why don't you consider each sample as a given batch? Were they not prepared separately before loading the 10x chip? Technically, I don't see an issue in the codes you ran. But I suggest you try to inspect the individual gene expression levels of your variable genes for all patients. 

Best,
Leon

**Comment by annecar** [comment]
Hi Leon 
Thanks again for your answer. 
The 2 variables are not identical, as you said, there are 10 for Patient and 30 for sample. As you suggest to consider each sample a batch might be right - i am not sure about it though, i do not know how much patient induced bias to expect. 
How are you usually handling this: are you regressing for samples variance? Is there another way to regress? 
At what stage would you suggest to compare gene expression between the patients (sorry - i am not yet that famliar with Seurat) : after the looking for variable genes and before scaling? And how can i do this easily? How can i select the most variable genes at this stage? 
Sorry to bother you with these may be basic questions. 


Thanks you very muc for your help 

Anne 







Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by leonfodoulian** [comment]
Hi Anne,

I think that batch effects are induced not only by the chip of origin, but by sample preparation too. So, in such cases, I would regress out for each sample. I am more keen to think that the patient specific clusters are an artefact (i.e. batch induced effect). In other words, It would surprise me that all the cell types in you data set are specific to each patient. 

One way to visualise gene expression levels across patients is to use the `VlnPlot()` function of Seurat. This function has an argument called `group.by`, which allows you to easily define a given column from your `object@meta.data` slot to be used as x axis to your plots. The first command line below allows you to transform your `object@var.genes` into a list, where each element of the list corresponds to a given gene. Subsequently, you can get the violin plots for all those genes and store them in `p`. Given that we ran the first command line, now the names of the elements of `p` will correspond to the names of the genes that were plotted. You can then browse your plots by calling each gene when you run `p$GENENAME` (GENENAME being the name of the gene of interest). At this stage, the log-normalised data from `object@data` are used to plot gene expression levels. Running `ScaleData()` will not affect this, as it will create an additional data that you can find in `object@scale.data`, which is not plotted here.

```R
# Get a list of variable genes
var.genes <- sapply(X = object@var.genes, FUN = list)

# Get violin plots of gene expression levels or variable genes accross patients
p <- lapply(X = var.genes, FUN = function(var.gene) { 
  VlnPlot(object = object, features.plot = var.gene, group.by = "Patient") 
  })
```

I hope I was clear. If not, don't hesitate to ask for further clarification.

Best,
Leon

**Comment by annecar** [comment]
Hi Leon, 

Thanks you vey much for yor detailed help! This is really helpful, and very kind of you. 
I have fully understood what you suggested and have been able to cary it out without any problem. 

I have one question, nevertheless: i have 800 var genes, do you suggest to look at all of them? I guess, just a part? 
And: are the var genes listed in increasing p-value order, or what is the order of the list I receive? Can i access the p-values, i.e. can i export them in  a list that would help selecting the top var genes? 

Further, if most patients look ‘steady’ in their expression of most var genes and one or two are outstanding, i would then expect the outstanding ones to cluster apart, even after scaling by regressing for sample? 

Then i have another question (sorry again to bother you…) . 
In the example of analysis for large data sets (33KPBMC) you show how to merge clusters, if the data looks overclustered. Nevertheless, i found it difficult to understand what is your criteria to choose te splits to merge. In the example it was 8. And, are the splits counted form the top of the three? I have not found any help on this elsewhere. 

Thanks a lot again for your help and suggestions, 

Best 
Anne 











CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by leonfodoulian** [comment]
Regarding your second question, you can find more details on the `AssessNodes()` function by running `?AssessNodes` in R. A relatively simple post on what does Random Forest (RF) do, and what is Out of Bag error (OBE) can be found [here](https://stackoverflow.com/questions/18541923/what-is-out-of-bag-error-in-random-forests). But maybe you can find more detailed explanations if you'd like to elsewhere on the web. 

The idea here is that you want to merge clusters that show high OBE (i.e. those clusters for which we are not confident in their split into distinct clusters). The `node` column in the output of `AssessNodes()` corresponds to the nodes at each split of your data into distinct clusters. For visual inspection, you can find these node labels in the bleu/grey boxes at each split of your cluster tree when you run `PlotClusterTree(object = object)`. An equivalent function that allows you to do the same thing, but that will merge the clusters automatically for you based on input parameters (e.g. `acc.cutoff`) is `ValidateClusters()`. This function uses SVMs (support vector machine learning algorithms) instead of RF. 

Hope this helps.

Best,
Leon

**Comment by annecar** [comment]
HI Leon, 
Thanks for code. Yes it is very clear to me now, how to sleect highly variable genes and how to analyse them accross patient. 
It looks as indeed, the variabilty is not driven by patients specific cells, for most genes. There are some exceptions, but in ca 90 % of the cases it does not seem to. I guess yo cannot expect this tp be completely homogenous? What is your experience?
Regressing out  samples is therefore more appropriate. Still, i am not happy with the results i obtain after regressing out for sample variation.  After running tSNE, there is no structure left at all in the data. 
I quickly explain what i have been doing so far:  my data set is the following: we sorted 3 cell popoulations by FACS (pDCs, adcs and Monocytes) pooled them and run them on the 10x platform, for each of 10 patients we needed a separate run, and we had 3 separate samples for each patient. So far i have been running the analysis for the whole data set first, scaling, running tSNE and clustering etc. I obtained top variable genes between the obtained clusters, and then separted cDCs, pDCs and Monocytes accoring to this, by selecting the clusters with the typical cell markers and subsetting them into a new seurat object. 
While tSNE on the whole data (regressed for sample) set still yielded nicely separated clusters and structured data, tSNE after subsetting (and re-scaling  the data for sample variation) yielded a projection that is completely unstructure.

What i am getting to is the question, whether it does at all make sense to subset the data, or whether, if the cells are too similar, it will be difficult to find a structure? 
What is you rexpereinec on that? 
Thanks again! 

Anne 



CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by leonfodoulian** [comment]
Hi Anne,

Why do you want to subset your clusters? If your aim is to find whether you have subclusters for these cell types, why not simply increase the resolution parameter for the clustering? You can then try to merge those clusters that you judge as being non legitimate. Also, do you expect to find any subclusters? You can also read [this recently closed issue (#263)](https://github.com/satijalab/seurat/issues/263) regarding the use of a negative binomial test to regress out confounder variables.

Best,
Leon

**Comment by annecar** [comment]
Right, i will work on this, then. 

Best 
Anne 



CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by SeadonXing** [comment]
Hi @leonfodoulian ：
    I have a question may similiar to this question, and I ask a question here https://github.com/satijalab/seurat/issues/1351 and https://github.com/satijalab/seurat/issues/1353
I just want to know that why I include "batch" in ScaleData and to regress out sample batch is not work for my data.
Hope you reply
Best
