### ISSUE TITLE
PrepSCTIntegration error: "RNA is not an assay present in the given object"

### ISSUE THREAD

**Issue by mvhunter1** [satijalab/seurat#2622]
ABC_list <- list(MHV01_A1, MHV02_B1, MHV03_C1)
list_features <- SelectIntegrationFeatures(object.list = ABC_list, nfeatures = 3000)
ABC_list <- PrepSCTIntegration(object.list = ABC_list, anchor.features = list_features, assay = "SCT", verbose = FALSE)

Error in GetAssay.Seurat(object = object, assay = assay) : 
  RNA is not an assay present in the given object. Available assays are: Spatial, SCT

I am getting the above error every time I try to merge Seurat objects, whether it's with the "merge" function or with PrepSCTIntegration. The strange thing is that I was able to do this a couple days ago without any issues. Adding "assay = "SCT" doesn't fix the error. Any help would be appreciated!

**Comment by jeremycfd** [comment]
I've also been having this problem when merging Spatial objects, as I reported in #2579 . The strange thing is that I haven't been able to replicate the issue when merging objects obtained from the SeuratData package download, but they arise when I'm using my own Seurat objects.

**Comment by jeremycfd** [comment]
@mvhunter1 did you do any custom processing in CellRanger to generate your matrices? I'm trying to figure out if that's what's causing issues.

**Comment by satijalab** [comment]
Thanks for pointing this out. Closing the issue as we've now released a fix. Feel free to re-open if this does not solve
