### ISSUE TITLE
Seurat Spatial installation failing

### ISSUE THREAD

**Issue by mvhunter1** [satijalab/seurat#2623]
Hi, I'm trying to install the Spatial version of Seurat using devtools::install_github("satijalab/seurat", ref = "spatial"). 

It worked well when I installed it on another computer, but now is giving many warnings and failing with the following error:

installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘miniUI’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Seurat’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Seurat’
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/b1/zz9dhmt52y33gw9yyxs1fwt40000gn/T//Rtmp91YWZw/file146a16f592696/Seurat_3.1.3.9002.tar.gz’ had non-zero exit status

I'm specifically analyzing spatial data so need this version of Seurat for my analysis. Any help would be appreciated. Thanks!

Edit: I should probably also mention that I'm getting many of the following types of warnings:
In file included from RModularityOptimizer.cpp:9:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/RcppEigen.h:25:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/RcppEigenForward.h:40:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:51:
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/unsupported/Eigen/../../Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop

**Comment by andrewwbutler** [comment]
Hi,

It looks like you're missing the `miniUI` package. Are you able to install that on its own?

```R
install.packages("miniUI")
```

**Comment by mojaveazure** [comment]
This was an error on our end not specifying miniUI as a dependency. This has been resolved as of fe6cfd53, running `install_github` should now install all dependent packages
