### ISSUE TITLE
Converting Seurat object generated in version 1.4 to version 3.1.3

### ISSUE THREAD

**Issue by alexnevue** [satijalab/seurat#2625]
I am trying to use `UpdateSeuratObject` on a Seurat object generated in version 1.4 in a published dataset. I get the error message:
Error: We are unable to convert Seurat objects less than version 2.X to version 3.X
Please use devtools::install_version to install Seurat v2.3.4 and update your object to a 2.X object

When I use `devtools` to install v2.3.4 I get the error:
Error: Failed to install 'unknown package' from URL:
  (converted from warning) package ‘SDMTools’ is not available (for R version 3.6.2)

`SDMTools` has been removed from CRAN. My other attempts to install it have not been successful.

Either 1) is there a way to install v2.3.4 independent of `SDMTools` or 2) is there a way to update a Seurat object from version 1 to version 3 without having to install v2.3.4?

**Comment by andrewwbutler** [comment]
Hi,

One thing you could try is to install the last version of `SDMTools` from the CRAN archive. E.g.

```R
devtools::install_version('SDMTools', version = '1.1-221.2', repos = 'http://cran.us.r-project.org')
```

This should allow you to install Seurat v2 and then hopefully upgrade the object to v3.

**Comment by alexnevue** [comment]
Hi Andrew,

Thank you. I am now able to run Seurat v2.3.4. Unfortunately I ran into another issue. When I try `UpdateSeuratObject` I now get the error:
Error in initialize(value, ...) : 
  trying to get slot "raw.data" from an object of a basic class ("character") with no slots

However, using `@raw.data` on my Seurat object gives me a matrix as expected.

I tried `slot(object = neurons, name = 'version') <- package_version(x = '2.3.4')` but got the error:
Error in checkSlotAssignment(object, name, value) : 
  ‘version’ is not a slot in class “dgCMatrix”

`getSlots()` said I do not have a defined class and `nameSlots()` gave me character(0)

I am trying to convert the Seurat objects found here (presently trying turtle.neurons): https://public.brain.mpg.de/Laurent/ReptilePallium2018/

Thank you for your help,
Alex

**Comment by andrewwbutler** [comment]
Hi Alex,

After you install Seurat v2.3.4, can you try restarting your R session? To check that you have the correct Seurat version loaded you can use `packageVersion("Seurat")`. 

As an alternative to the `UpdateSeuratObject` workflow, you could just create a v3 version from the counts matrix and meta.data (assuming that's all you really want from the v1 object). 

```R
turtle.neuronsv3 <- CreateSeuratObject(counts = turtle.neurons@raw.data, meta.data = turtle.neurons@data.info)
```

**Comment by alexnevue** [comment]
Hi Andrew,

`CreateSeuratObject` worked! Thank you so much for your help!
