### ISSUE TITLE
DotPlot: Gene found in non-default RNA assay and labelled as NA

### ISSUE THREAD

**Issue by ktrns** [satijalab/seurat#2626]
Hi there. I had the same problem: 
`Warning: Could not find Sox1 in the default search locations, found in RNA assay instead
`

My default assay was SCT. After switching it to RNA, the plot contained "Sox1" rather than "NA". 

Would you generally recommend doing plots (DotPlot, FeaturePlot,...) for RNA rather than SCT?

Thanks!

_Originally posted by @ktrns in https://github.com/satijalab/seurat/issues/2363#issuecomment-585230097_

**Comment by yuhanH** [comment]
Is the Sox1 a low expression gene in the RNA assay? 
You could plot using either RNA or SCT assay data slot. SCT counts/data slots are sequencing-depth corrected.
We don't recommend to use integrated assay to plot.
