### ISSUE TITLE
Integration based on subset of cells

### ISSUE THREAD

**Issue by hxy265** [satijalab/seurat#2627]
Hi Seurat team,

I was wondering if it was possible to perform the integration step on multiple datasets based on just one or two cell types?

Essentially my datasets contain mostly tumour cells and some normal microenvironment cells. The standard SCTransform and integration I feel overfits my data and perhaps forces the tumour cells across datasets together when there may be some subtle differences? Therefore, I was wondering if its possible to perform the anchoring based only on these normal cells which i can identify by first analysing the datasets on their own?

Many thanks in advance!

**Comment by satijalab** [comment]
Yes, you can perform integration on a subset of cells.

Please note that just when Seurat aligns cells together that have subtle differences, this is not overfitting. We do this precisely because we want to identify cells that are in a shared biological state. In a secondary step, you can then identify differentially expressed genes between them.

**Comment by akramdi** [comment]
@satijalab , would it be possible to give further indication on how to perform integration on a subset of cells? Should we just feed `FindIntegrationAnchors` a list of seurat object containing the subset of cells (normal cells, as mentioned above), then use the output ` AnchorSet object` to integrate the full data. Does it sound correct?

Many thanks,

**Comment by ConDem94** [comment]
> @satijalab , would it be possible to give further indication on how to perform integration on a subset of cells? Should we just feed `FindIntegrationAnchors` a list of seurat object containing the subset of cells (normal cells, as mentioned above), then use the output ` AnchorSet object` to integrate the full data. Does it sound correct?
> 
> 
> 
> Many thanks,

Hi, did you find a solution to this? Thinking of performing the same analysis. I have six studies (60 primary tumour samples overall). I tried integrating everything but it did not maintain biological heterogeneity in the neoplastic compartment. 

So i'm thinking of identifying the cancer cells for each study seperately, then just integrate the stromal compartment for downstream analyses. But when I will analyse the cancer cells, I will simply merge and not integrate. Does that sound correct?

Thank you!
