### ISSUE TITLE
MKL Error 

### ISSUE THREAD

**Issue by SMerkling** [satijalab/seurat#2628]
Hello, 

I have issue installing Seurat and get the following message: 

INTEL MKL ERROR: dlopen(/Users/sarahmerkling/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/sarahmerkling/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
installation of package ‘/var/folders/mb/rv2j9mkd7n53pzf3lytzptt80000gn/T//Rtmpr2ejPM/file54e523703c2/Seurat_3.1.0.tar.gz’ had non-zero exit status

I tried to install it using the
`install.packages('Seurat')`
and `devtools::install_github("satijalab/seurat", ref = "v3.1.0")`

I am on Mac Catalina 10.15.3
and  R version 3.6.2

Any help would be appreciated ! 
Many many thanks, 
Sarah 
>

**Comment by mojaveazure** [comment]
This seems to be an issue with Miniconda. Please install R from CRAN instead of alternate sources and try again.

**Comment by akuisara** [comment]
@mojaveazure I have the same issue here, same R version, same OS, and got the same tracebacks. I didn't install R from alternate sources before. I installed both "multtest" and "Seurat" from BiocManager. Seurat was working a few days ago but suddenly stopped working. Now, every time I call "library(Seurat)", I got an Intel MKL FATAL ERROR.

I reinstalled R from https://cloud.r-project.org/ and reinstalled Rstudio from https://rstudio.com/products/rstudio/download/#download. However, this issue persists. Please help, thanks a lot!

**Comment by SMerkling** [comment]
Hi there,
I managed to get back on track by reinstalling mini-conda (or anaconda if you use it). I hope this works for you too!

**Comment by jdriver509** [comment]
I am having the same issue with Seurat. It crashes every time I try to upload Seurat. Error message below. 

The downloaded binary packages are in
	/var/folders/m2/szvm3l0n0nv3crvn17078p3m0000gn/T//RtmpcN3dFu/downloaded_packages
INTEL MKL ERROR: dlopen(/Users/ju467/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/ju467/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.

I've tried reinstalling R/R studio, reinstalling miniconda. Any help would be greatly appreciated.

**Comment by mimisikai** [comment]
I have the same issue!

**Comment by TomKellyGenetics** [comment]
I'm getting the same Issue with Mac OS Mojave. It doesn't appear to be specific to Catalina.
