### ISSUE TITLE
Issues about data normalization

### ISSUE THREAD

**Issue by Fackie** [satijalab/seurat#263]
1\here u suggested better normalized data before scale data, but here i found the normalized data just use the sum counts as normalize factor ,and scaledata here u use variables such as "nUMI" to regress out the impact of total counts, is that reasonable since u already take a normalization?
2\here i found that in scaledata function:
_use.umi
Regress on UMI count data.  Default is FALSE for linear modeling, but auto-
matically set to TRUE if model.use is ’negbinom’ or ’poisson’_
but in the pbmc 10x tutorial ,u didnt set this to be true? I m alittle confused...

**Comment by satijalab** [comment]
We regress on nUMI to capture any depth-dependent effects that were not removed in the initial normalization. This step is of course optional. It is not necessary to regress these features in every dataset, and users may want to first analyze their data without regression and then identify if confounding factors remain. 

We use linear modeling in the 3k tutorial, not GLM based on poisson or negative binomial. In practice we've found that GLM-mediated regression works well, but requires significantly more cells (>10k) to be robust to overfitting of GLM parameters. We're working on better ways to address this problem as well.
