### ISSUE TITLE
FindIntegrationAnchors, 2 references 1 query produces error message

### ISSUE THREAD

**Issue by DanSchnell** [satijalab/seurat#2630]
I'm trying to integrate one mouse sample (M) with 2 human samples (Hn, Ho), and want the 2 human samples to serve as a reference.  (I have already converted mouse feature names to human names.)

According to the FindIntegrationAnchors documentation, I should be able to specify c("Hn","Ho") as the references and ... " anchors are first found between each query and each reference. The references are then integrated through pairwise integration. Each query is then mapped to the integrated reference.", which is what I want.

But, getting a run-time error: Error: requested reference object Ho but only 3 objects provided.

I've checked the input object list and tried re-ordering the samples in the object list and in the references= specification, but always the same error.

Any help to get this running or suggested alternative workflow would be appreciated.

**Comment by DanSchnell** [comment]
Having the same problem with 4 samples, specifying 1 as the reference.

**Comment by DanSchnell** [comment]
Figured out another way to do this.

**Comment by AAA-3** [comment]
How did you solve this? @DanSchnell
