### ISSUE TITLE
[Analysis Qustion] overlapped markers mean similar clusters？

### ISSUE THREAD

**Issue by xizhihui** [satijalab/seurat#2632]
Hi,
I used Seurat got some clusters, eg. A, B, they were assigned two cell types. And I got the subclusters of A and B, like A1-A5, B1-B5. And I found that there are some overlapped markers between the subcluster markers in B1 and A2. Do these overlapped markers indicate that B1 and A2 are the similar cells in some way? 
In my opnion, these overlapped markers indicate nothing, is it right?

**Comment by satijalab** [comment]
If both populations have similar markers then that does indicate that they are similar cell types. For example, both CD4 Naive and CD4 Memory T cells will share a similar set of markers, when compared to all PBMCs.
