### ISSUE TITLE
Analyzing bulk RNAseq along with scRNAseq

### ISSUE THREAD

**Issue by rgranit** [satijalab/seurat#2633]
Hello,

Is it possible to combine bulk RNA data with single cells expression data for analysis in Seurat? any special guidelines? 

Thanks!

**Comment by satijalab** [comment]
It is possible to analyze bulk data. No special guidelines to suggest - other than we recommend using DE-Seq2 for DE in bulk samples, as this is optimally tailored for lower number of replicates (which characterize bulk experiments)

**Comment by rgranit** [comment]
@satijalab thanks, but I was actually wondering if one can analyze bulkRNA-seq & scRNA-seq together in the **same analysis**? (e.g. cluster the cells together in the same plot and study the similarity between populations)

**Comment by akramdi** [comment]
Hello @rgranit, 
Were you able to analyze bulkRNA-seq & scRNA-seq together ? Would you mind sharing your experience with such analysis? 

Thanks!

**Comment by rgranit** [comment]
Hi @akramdi I've attempted this quite a while ago, was quite a naive attempt.. I took the expression matrix and loaded is as if it was scRNAseq data (after making sure that the genes overlap) and next using seurat functions attempted to merge the objects. It did work technically, and clustered not too bad but was hard to say something meaningful the # of samples was low.. 

Perhaps you will find this paper somewhat relevant:
https://www.nature.com/articles/s41467-020-20294-x

**Comment by akramdi** [comment]
Thanks for the paper ! Too bad they didn't mix bulk with scRNAseq but it's really nice to see how they analyzed bulk data using scRNAseq methods. 
I've been reading about this recently and I can't find a proper workflow or guidelines on how to analyze both types of data side by side. For now, I will stick to a correlation analysis between pseudo-bulk of single cell clusters and bulkRNAseq (as shown in [this paper](https://www.science.org/doi/10.1126/sciadv.abh2169)) or maybe just do a PCA. This will help me answer my biological question to some extend.
