### ISSUE TITLE
Results Variation of CellCycleScoring and AddModuleScore

### ISSUE THREAD

**Issue by SiyiWanggou** [satijalab/seurat#2634]
Hi Seurat Team,
     I'm using Seurat v3 for single cell RNAseq analysis in these days and it is really a powerful pipeline. 
     Recently, when I used CellCycleScoring for analysis, I met some issues.
     I found that everytime I restarted the computer and ran CellCycleScoring, it returned a result with different G2M.score and S.score. I noticed that the CellCyclScoring using AddModuleScore to calculate the scores. In the description of AddModuleSocre, it says "Calculate the average expression levels of each program (cluster) on single cell level, subtracted by the aggregated expression of control feature sets. All analyzed features are binned based on averaged expression, and the control features are randomly selected from each bin." It seems that the control features are randomly selected everytime when I run this function. Even if I set the random seed to the argument, the scores still alter time by time.
     I'm going to use the cell-cycle-regressed-out matrix for downstream analysis, but the inconsistence of G2M.score and S.score makes my downstream analysis not reproducible.  
     I'm fresh on Seurat and is there any idea on how to solve this issue?
     Thanks.

**Comment by satijalab** [comment]
I have not been able to reproduce this problem. We do fix the random seed to ensure that the list of background features is reproducible. There may be some issue with your R installation where the random seed setting is not working. I would recommend updating to the most recent version of R, following instructions here:
https://community.rstudio.com/t/getting-different-results-with-set-seed/31624/5

Feel free to reopen if this problem persists
