### ISSUE TITLE
Regressing out gene.list gives back error message ' Error in parse(text = x, keep.source = FALSE) :     <text>:2:0: unexpected end of input 1: GENE ~     ^'

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#2635]
Dear all,
I am trying to regress out a list of genes from my Seurat object. These are RBC genes that should not be part of the analysis. 
so, I created the list
`ctrl_rbc_features <- list(c('Hba-a1', 'Hbb-y', 'Hba-x', 'Hbb-bs', 'Hbb-bt', 'Hbb-bh1', 'Hba-a2'))`

then, I used AddModuleScore function (similar to the procedure to remove CC genes).
`ctrl <- AddModuleScore(
  object = ctrl,
  features = ctrl_rbc_features,
  ctrl = 5,
  name = 'ctrl_rbc_features'
)
head(x = ctrl[[]])`

Then, I tried to regress out these genes

`ctrl <- ScaleData(ctrl, vars.to.regress = c("ctrl_rbc_features"))`

But I am getting back the following error message.

`Regressing out ctrl_rbc_features
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: GENE ~ 
   ^`
I know people have debated similar topics previously, but I could not find a way to solve this problem looking at past topics. Can anyone tell me what I am doing wrong and how to fix it?
I thank you in advance for your time and patience with a new user.

**Comment by satijalab** [comment]
Can you check the column names in object@meta.data? Its possible that AddModuleScore actually returns the column name: ctrl_rbc_features1 . That should fix your problem. I'm cc'ing @mojaveazure as we should either fix this, or make the documentation more clear.

**Comment by Alexgr97** [comment]
Hi all - I'm getting the same problem:

```
> fcmvc_reg <- ScaleData(object=filtered_cells_norm, vars.to.regress = c('metadata_cell_ids_post$nUMI', 'metadata_cell_ids_post$mitoRatio', 'metadata_cell_ids_post$batch'))

Regressing out metadata_cell_ids_post$nUMI, metadata_cell_ids_post$mitoRatio, metadata_cell_ids_post$batch
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: GENE ~ 
   ^
```

This keeps happening whether I try and put the vars I want regressed out into a list or do them individually.

```
`> var_regs <- cbind(metadata_cell_ids_post$nUMI, metadata_cell_ids_post$mitoRatio, metadata_cell_ids_post$batch)
> fcmvc_reg <- ScaleData(object=filtered_cells_norm, vars.to.regress = c("var_regs"))
Regressing out var_regs
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: GENE ~ 
   `^``
```

I had assumed it was something I was doing, but I cannot work out why I keep getting this parse error.

Thanks for your help.

All the best,
Alex
