### ISSUE TITLE
FindMarker DE: which slot is used in seruat object?

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#2636]
Hi all, 

I am currently going through different ways of doing DE analysis with single cell data and have opted for seurat FindMarkers approach. 

As well finding marker of individual clusters, i am also just interested in understanding what differences exist between different conditions (i.e wt vs treated) regardless of which clusters cells belong to.

I have run the full pipeline as well as limited pre-processing **up to** normalising the data only. 

I then specify the Idents as the groups of interest (wt, treated) etc.. and simply pass these in to ident.1 and ident.2 as follows:

`##Set idents for "group label" to carry out DE between groups
Idents(merged)<- "Group"
table(Idents(merged))

FindMarkers(merged, ident.1 = "Trted", ident.2 ="Ctrl", only.pos = FALSE, verbose = T, logfc.threshold = 0, min.pct = 0)

`
Note, all thresholds have been set to 0, this has been done on purpose. as I want the full ranking of gene lists ( a more agnostic and holistic way of DE):

My question is: I have stopped at the normalise data step so that i do not have to specify the most variable genes, this way all genes are included in the De analysis. Can i confirm that FindMarkers pulls the counts from the 'data' slot of the seurat object and therefore the normalised counts are used for testing?

when I carry out the method above (DE in just normalized data vs batch corrected pipeline, the direction of log fold changes are the same, however there are massive discrepancies in the pct1 and pct2 statistics!) example gene:

DE on batch corrected pipeline: split data, normalise , variable features ,integrate anchors, scale, cluster, FindMarkers:

`

p_val | avg_logFC | pct.1 | pct.2 | p_val_adj
-- | -- | -- | -- | --

4.63E-26 | 0.93451251 | 0.856 | 0.951 | 9.26E-23
-- | -- | -- | -- | --

`

and when i do non-batch corrected but normalize the data alone and then FindMarkers:

`

0 | 1.13827755 | 0.377 | 0.107 | 0
-- | -- | -- | -- | --

`

As you can see, there is a huge discrepancy in pct1 and pct2 which i dont really understand, this is the same for all genes. Any explanation would be much appreciated as I thought DE was being carried out on normalized data. Alternatively is there a way of speciying all genes as variable features (or omitting this step) in the pipeline when running integrate anchors so that I can do the DE analysis on all genes?

As i understand it, batch corrected data (shifted counts) should not be used for DE... There are batches within groups (i.e within wt and within trtd) but not across. Is this safe to ignore since the DE is being done between groups?

many thanks!!

**Comment by satijalab** [comment]
For most tests (except those that explicitly require the use the counts slot, for example the GLM tests), we do use normalized data.

The issue here is that you should be using the RNA slot for DE, not the integrated slot. You should not be running DE on 'batch-corrected' data. If you run on the integrated slot, the pct.1 and pct.2 values cannot be accurate, as you point out.

**Comment by amjass12** [comment]
Thank you very much for the prompt response, please may i clarify the correct use of the FindMarker function for when data is integrated, just to confirm that the correct slot is used by default.

when carrying ot the following:

combinedList <- SplitObject(merged, split.by = "Sample")
combinedList

for (i in 1:length(combinedList)) {
    combinedList[[i]] <- NormalizeData(combinedList[[i]], verbose = FALSE)
    combinedList[[i]] <- FindVariableFeatures(combinedList[[i]], selection.method = "vst", nfeatures = 2000, 
        verbose = FALSE)
}

anchors <- FindIntegrationAnchors(object.list = combinedList, dims = 1:30)

anchors.integrated <- IntegrateData(anchorset = anchors, dims = 1:30)

DefaultAssay(anchors.integrated) <- "integrated"

after making the Defaultassay "integrated" and further downstream analysis:

is it correct to use the FindMarkers function as follows:

FindAllMarkers(anchors.integrated, only.pos = FALSE, verbose = T, logfc.threshold = 0.25, min.pct = 0.2)..etc?

Will FindAllMarkers pull data from the correct slot for DE analysis?

thank you!

**Comment by kinali** [comment]
As they stated in this tutorial:
https://satijalab.org/seurat/v3.1/immune_alignment.html

You need to switch back to the "RNA" slot for DE analysis.
DefaultAssay(anchors.integrated) <- "RNA"

**Comment by artemisDiscovery** [comment]
I ran into this thread and have a similar question about FindMarkers. 

When I use FindVariableFeatures selecting 2,000 features and then run FindMarkers on a clustering, my sense is that I should always see no more than 2,000 DE genes in any comparison - after all the gene list should be reduced to that number.

It seems however that I sometimes see more than 2,000 DE genes for a cluster. Does that reflect an error on my part, or some difference in the data slot that FindMarkers accesses by default?

Thanks
