### ISSUE TITLE
Can't find the transgenes in my data

### ISSUE THREAD

**Issue by sygongcode** [satijalab/seurat#2637]
Hello all, 

I have met a problem. When I try to plot some genes which are some transgenes. It shows that can not find them. I have already added their sequences into the reference genome. I work in the Drosophila model. And the transgenes are EGFP, Gal4, and p35. These genes should be highly express in the majority of cells. So, is that possible that at the Cellranger step, they have been filtered? Did anyone also have this problem? Thanks

Shangyu

**Comment by samuel-marsh** [comment]
Hi Shangyu,

Not member of Dev team but hopefully this can be helpful.  Unless the genes have counts in the expression matrix but not in the Seurat object then this isn't likely a Seurat issue.  I would suggest checking out this recent blog post detailing some potential issues with transgenes when using cell ranger pipeline.
[https://divingintogeneticsandgenomics.rbind.io/post/cellranger-mk-reference-with-transgenes/](https://divingintogeneticsandgenomics.rbind.io/post/cellranger-mk-reference-with-transgenes/)

Best,
Sam

**Comment by sygongcode** [comment]
Hi, Sam,

Thank you so much for your help. I will try to fix it to follow this blog.
Have a nice day.

Best,
Shangyu


Samuel Marsh <notifications@github.com> 于2020年2月19日周三 上午7:33写道：
