### ISSUE TITLE
X and Y axis not the same in DimPlot and FeaturePlot for same UMAP (Seurat v3)

### ISSUE THREAD

**Issue by corina444** [satijalab/seurat#2638]
Hi there! 

Thank you for your excellently written vignettes, they are very helpful. 

I am facing a difficulty in plotting my UMAP with the `DimPlot()` and `FeaturePlot()` functions.
Even though it's the exactly the same UMAP, the output is different from the two functions. The x and y axis are different and in `FeaturePlot()`, the plot is smaller in general. 

How can I produce graphs that are consistently the same size for exactly the same UMAP between these two functions? 

Attached an example (I removed the data points, but you get the gist)

Thank you!

<img width="655" alt="Screenshot 2020-02-19 at 13 37 27" src="https://user-images.githubusercontent.com/60880112/74835577-f2bf4600-531d-11ea-9ab9-5817e81664d5.png">

**Comment by satijalab** [comment]
Since both FeaturePlot and DimPlot return ggplot2 objects, you can set manual limits to make sure everything is exactly the same:

```
DimPlot(object)+xlim(-7,7) 
```
