### ISSUE TITLE
Hot to set the y-axis limits to the same value in RidgePlot?

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#2639]
I have tried to do this by setting `same.y.lims=T`
```
RidgePlot(object, features = "TPSAB1", idents = c(5,6,7,8), same.y.lims=T)
```
But it does not change anything to the output, also I am not able to get back the scale of the y-axis.
Is there an easy way to do these two things but especially the first one?

**Comment by andrewwbutler** [comment]
Hi,

The `same.y.lims` parameter will only apply if you are plotting more than one feature (i.e. passing a vector to the `features` parameter). If you want to adjust the y-axis range after plotting, you can do so as with any ggplot object. E.g.

```R
library(ggplot2)
RidgePlot(object, features = "TPSAB1", idents = c(5,6,7,8)) + ylim(c(0, 10))
```

**Comment by kaizen89** [comment]
Hi Andrew,
Unfortunately your suggestion gives an error
```
RidgePlot(pbmc_small, features = "CD3D") + ylim(c(0,10))
Error: Discrete value supplied to continuous scale
```
I also tried
```
RidgePlot(pbmc_small, features = "CD3D")+ scale_y_continuous(0,10)
Error: Discrete value supplied to continuous scale
```
There is a variable `y=..scaled..`  to set in` stat_density` but I don't know how to insert that in RidgePlot function.

**Comment by andrewwbutler** [comment]
Hi @kaizen89 ,

The y-axis on RidgePlots corresponds to the discrete identity classes. Did you want to change the spacing between those or adjust the x-axis limits? If the latter, then the solution above should work if you change `ylim` to `xlim`.

**Comment by kaizen89** [comment]
What I actually want is to have the same maximum height for each identity.
Here's what I get using `RidgePlot`
![image](https://user-images.githubusercontent.com/30392707/77942961-bd166100-72bc-11ea-852d-06a9e4313a4c.png)
Here's what I get when I set the maximum height for each Identity to be the same.
```
DF_to_plot <- function(object, group){
Data <- as.data.frame(Matrix::t((GetAssayData(object, slot = "data", assay = NULL))))
Data[, group] <- object[[group]][colnames(object), , drop = F]
return(Data)
}
Df <- DF_to_plot(object=immune_small, group="seurat_clusters")
ggplot(Df, aes(y=factor(seurat_clusters), x=CLEC10A, fill=seurat_clusters)) + 
ggridges::geom_density_ridges(aes(height= ..ndensity.., scale = 10)) + ggridges::theme_ridges()
```
![image](https://user-images.githubusercontent.com/30392707/77943416-78d79080-72bd-11ea-88c2-49850c92febf.png)

**Comment by vsuryaw** [comment]
> What I actually want is to have the same maximum height for each identity.
> Here's what I get using `RidgePlot`
> ![image](https://user-images.githubusercontent.com/30392707/77942961-bd166100-72bc-11ea-852d-06a9e4313a4c.png)
> Here's what I get when I set the maximum height for each Identity to be the same.
> 
> ```
> DF_to_plot <- function(object, group){
> Data <- as.data.frame(Matrix::t((GetAssayData(object, slot = "data", assay = NULL))))
> Data[, group] <- object[[group]][colnames(object), , drop = F]
> return(Data)
> }
> Df <- DF_to_plot(object=immune_small, group="seurat_clusters")
> ggplot(Df, aes(y=factor(seurat_clusters), x=CLEC10A, fill=seurat_clusters)) + 
> ggridges::geom_density_ridges(aes(height= ..ndensity.., scale = 10)) + ggridges::theme_ridges()
> ```
> 
> ![image](https://user-images.githubusercontent.com/30392707/77943416-78d79080-72bd-11ea-88c2-49850c92febf.png)

Hi Kaizen,

I am trying to do the same thing as you. Were you able to find a workaround for this within Seurat?

**Comment by kaizen89** [comment]
@vsuryaw no, not within Seurat

**Comment by witszymanski** [comment]
Hi!
Try:

```
Df <- DF_to_plot(object=immune_small, group="seurat_clusters")
ggplot(Df, aes(y=factor(seurat_clusters), x=CLEC10A, fill=seurat_clusters)) + 
ggridges::geom_density_ridges(aes(height= ..ndensity.., scale = 10)) + ggridges::theme_ridges()+
**coord_cartesian(xlim = c(0, 100))** 
```
