### ISSUE TITLE
remove the dot from VlnPlot

### ISSUE THREAD

**Issue by lilycanfly** [satijalab/seurat#264]
Hi, 

Is there a way to remove the dot from the VlnPlot? like something show as the below? Thanks.

Best,
Lili

![image](https://user-images.githubusercontent.com/32545217/34852035-b5970708-f6fa-11e7-87a6-8957064c3c5c.png)

**Comment by leonfodoulian** [comment]
Hi,

Simply specify `NA` as `point.size.use`.

```R
VlnPlot(object = object, features.plot = "Actb", point.size.use = NA)
```

Best,
Leon

**Comment by lilycanfly** [comment]
Hi Leon,

Thank you so much.

Best

**Comment by jianggl2000** [comment]
pt.size=0 in Seurat 3.

**Comment by bbsirtale** [comment]
pt.size=0 doesn't really work for me. It removed most of the points on the plot but not the putative outliers? See example below
![image](https://user-images.githubusercontent.com/3329184/58916252-2820f680-86f1-11e9-9659-007752be64a0.png)

Here's what I did:
VlnPlot(object = seurat_mat_filtered, features = markers_filt[[i]], pt.size = 0)+geom_boxplot(width=0.1,fill="white")

**Comment by bbsirtale** [comment]
Sorry problem solved... The dots are from my geom_boxplot(). Can simply add outlier.size=0 in geom_boxplot

**Comment by randymi01** [comment]
@Yijun-Tian 
You can create separate plots then merge using patchwork
`p1 <- VlnPlot(pbmc, features = "nFeature_RNA", pt.size = 1)
p2 <- VlnPlot(pbmc, features = "nCount_RNA", pt.size = 1)
p3 <- VlnPlot(pbmc, features = "percent.mt", pt.size = 0)

combined_plot = p1 | p2 | p3

ggsave("combined_violin_plots.png", combined_plot, width = 15, height = 5, units = "in", dpi = 300)`
