### ISSUE TITLE
Why using unnormalized data for FindVariableFeatures ?

### ISSUE THREAD

**Issue by nebetbastet** [satijalab/seurat#2641]
Hi,

I switched quite recently (few months ago) on Seurat3 as I was used to Seurat2.

I use a "personnal" normalization (scran) that I integrated in a Seurat object. By mistake, the normalized data were added in two slots:
object@assays$RNA@data AND object@assays$RNA@counts
In other words, I lost raw data. 

Until yesterday, I thought it was OK as I thought raw counts were not used again in the worflow. 
It's only yesterday, when I decided to have a closer look on your paper on integration that I noticed that the "FindVariableFeatures" procedure was performed on raw data (at least with the default method "vst").

Unfortunately, the results are very different when I have raw counts or normalized counts in the "counts" slot : only 1/3 of genes are consistent...

I have two questions:
- Why this choice of un-normalized data to identify variable genes ? Maybe I am mistaken, but I think this is not explained in the paper or in your vignette
- If by mistake, you use normalized data in this procedure (as I did), which bias can you expect? In other words, why would it be "better" to use unnormalized data?

Thank you in advance for your answers!

**Comment by timoast** [comment]
This is explained in the section "Feature selection for individual datasets" in [Stuart and Butler et al. 2019](https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub)

The section shown here:

<img width="688" alt="Screen Shot 2020-02-26 at 2 51 30 PM" src="https://user-images.githubusercontent.com/4591688/75381862-84dbc700-58a7-11ea-8c67-4a2083121c1f.png">

It is not valid to run the same procedure (`selection.method="vst"`) on normalized count data

**Comment by duocang** [comment]
@timoast 

So unnormalized data is for `FindVariableFeatures`. We assume it is under `RNA` assay. 

Can I run `SCTransform` first and `FindVariableFeatures` later? Because I get different variable features after `SCTransform`. The unnormalized data from `SCT` assay is the corrected read counts, does the corrected read counts work better than counts from `RNA`?
