### ISSUE TITLE
More verbose documentation

### ISSUE THREAD

**Issue by frenkiboy** [satijalab/seurat#2642]
Dear Seurat team, 

Firstly I would like to thank you for making such a wonderful package!

Seurat now has a strong user base and is one of three main solutions for analysis
of single cell data. The development of the package has enabled multiple non linear
analysis paths, and figuring out which one is the best one for a certain data set is hardly straightforward. Therefore it would be really really helpful if the code base documentation
becomes more user friendly, and more verbose. Currently it is really hard to figure out what the functions, and their parameter are doing without going thoroughly into the code, and more importantnly which data set is being used by which function. Especially regarding data integration.
This would ameliorate a lot of the issues which are currently being reported.

For example:
PrepSCTIntegration - Prepare an object list that has been run through SCTransform for integration

The description of the function does not in any way convey what the function does, and why it does it. In the end we have no idea why we need to explicitly run this function, and why it wasn't automatically integrated in a different part of the work flow. 

Best regards, 

Vedran Franke

**Comment by timoast** [comment]
Thanks for the feedback and suggestion, we will continue to improve the documentation over time. We are always open to receiving PRs if you would like to help contribute.
