### ISSUE TITLE
How many PCs should be considered for downstream analyses?

### ISSUE THREAD

**Issue by bioinforesearchquestions** [satijalab/seurat#2643]
Hi All,

I have two groups WT and KO. 

```
merged_cond <- merge(x = WT_seurat_obj, y = KO_seurat_obj, add.cell.id = c("WT","KO"))

# filtered the merged_con based on mito, etc
filtered_cond_seurat

# split seurat object by condition from filtered_cond_seurat

for (i in 1:length(split_cond)) {
  split_cond[[i]] <- NormalizeData(split_cond[[i]], verbose = TRUE)
  split_cond[[i]] <- CellCycleScoring(split_cond[[i]], g2m.features=g2m.genes,
                     s.features=s.genes, set.ident = TRUE)
  split_cond[[i]] <- SCTransform(split_cond[[i]], vars.to.regress = c("mitoRatio",
                     "S.Score","G2M.Score"))
}
integ_features <- SelectIntegrationFeatures(object.list = split_cond, nfeatures = 3000) 

split_cond <- PrepSCTIntegration(object.list = split_cond, 
              anchor.features = integ_features)

integ_anchors <- FindIntegrationAnchors(object.list = split_cond, 
              normalization.method = "SCT", anchor.features = integ_features)

cond_integrated <- IntegrateData(anchorset = integ_anchors, 
                     normalization.method = "SCT")

[WT_KO_Exploratory_Plots.pdf](https://github.com/satijalab/seurat/files/4231871/WT_KO_Exploratory_Plots.pdf)
![PC_heatmaps](https://user-images.githubusercontent.com/20073601/74957487-97508f00-53d5-11ea-9fea-81b9893afe08.png)
cond_integrated <- RunPCA(object = cond_integrated)
DimHeatmap(cond_integrated, dims = 1:15, cells = 500, balanced = TRUE)
cond_integrated <- JackStraw(cond_integrated, num.replicate = 100, dims=50)
cond_integrated <- ScoreJackStraw(cond_integrated, dims = 1:50)
JackStrawPlot(cond_integrated, dims = 1:50)
ElbowPlot(object = cond_integrated, ndims = 50)
```
PC_Dim_Heatmap_Plot
![PC_heatmaps](https://user-images.githubusercontent.com/20073601/74957610-ce26a500-53d5-11ea-976e-aaf01fc1cc82.png)

PC_JackStraw_Plot
![JackstrawPlot](https://user-images.githubusercontent.com/20073601/74957813-19d94e80-53d6-11ea-96e6-2afdf1ad016c.png)

PC_Elbow_Plot
![Screen Shot 2020-02-20 at 11 43 15 AM](https://user-images.githubusercontent.com/20073601/74957986-4beab080-53d6-11ea-9b1e-4b1de1ed9b76.png)

As per the Jackstraw plot, ‘Significant’ PCs will show a strong enrichment of features with low p-values (solid curve above the dashed line). 
**1) How to interpret the JackStraw plot. How come even the PCs with p-value =1 is above the dashed line.** 
**2) PC 5 has pvalue "1". Do I need to consider the PCs which has only pvalue <0.05 (PC : 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14 and 15) for the downstream analyses?**

**As per the Elbow plot, looks like at PC 34 the standard deviation is touching the ground and staying constant.**

**So how many PCs should I consider for the downstream analyses like (find neighbors, find clusters and UMAP)?**
```
cond_integrated <- FindNeighbors(object = cond_integrated, dims = ?)
cond_integrated <- FindClusters(object = cond_integrated)
cond_integrated <- RunUMAP(cond_integrated, reduction = "pca", dims = ?)
```

As I change the number of dimensions each time, I am getting different UMAP clustering. 

These are the other similar queries I referred but no solutions given.
 
https://github.com/satijalab/seurat/issues/2018
https://github.com/satijalab/seurat/issues/1871

**Comment by satijalab** [comment]
We recognize that it is difficult to precisely identify a single number that clearly represents the correct number of dimensions to use in downstream analyses. This is an unsolved challenge not just for single-cell analysis, but more generally in the stats/ML community.

In the PBMC vignette we go into detail about the different tools we provide to help users identify a range of values that might be acceptable, but there's no guarantee that all approaches will provide exactly the same number.

The good news is that particularly in v3, we're seeing that this parameter choice does not substantially affect downstream results when varied over a small range. Of course the exact UMAP and clustering results will change, but in general, real biological results should be robust to exactly what value you suggest. 

For example, in the v3 paper (Stuart*, Butler* et al,), we used 30 for basically all of our analyses across many different datasets (increasing to 60 in one case where the dataset was huge and encompassed multiple organs).

30 would seem like an acceptable solution in your case as well, but I hope that the results would be quite similar even when choosing 50.

**Comment by vincr04** [comment]
Hi, 
What puzzles me is that for the same (large, ~65k cells) dataset, Jackstraw recommends me to use completely different numbers of PCs depending on whether I use SCTransform (11 PCs) or not (133 PCs) before the integration step. Any idea of why using SCTransform may induce such a difference?

**Comment by timoast** [comment]
@vincr04 see #1871

**Comment by htc502** [comment]
> Hi,
> What puzzles me is that for the same (large, ~65k cells) dataset, Jackstraw recommends me to use completely different numbers of PCs depending on whether I use SCTransform (11 PCs) or not (133 PCs) before the integration step. Any idea of why using SCTransform may induce such a difference?

any comments on such big and intriguing differences?
Thanks.
