### ISSUE TITLE
Unexpected PCA Change When Using return.only.var.features = FALSE in SCTransform

### ISSUE THREAD

**Issue by jmrussell** [satijalab/seurat#2644]
Hello,

When regressing over percent.mt only, I can run SCTransform and return all genes instead of variable features without issue - the downstream analysis for output is the exact same. However, when I run SCTransform and regress across nCount in addition to percent.mt, I find that my PCA (and subsequently UMAP) changes unexpectedly. 

1. As I understand it, regressing on nCount is not necessarily required because nUMI is regressed during the SCTransform process - in that case, do you suggest only regressing on percent.mt (or ribsomal content) per the SCTransform vignette? 

2. Why does the data change when return all genes is enabled when regressing on nUMI, but not on percent.mt? I am unsure if this is a bug or misunderstanding on my part.

Attached are two PCA plots and UMAPs showing the differences between the following two commands:

```
obj <- SCTransform(obj, vars.to.regress = c("percent.mt", nCount_RNA",))
obj <- RunPCA(obj, npcs = 100)
obj <- RunUMAP(obj, dims = 1:60)
obj <- FindNeighbors(obj, dims = 1:60)
obj <- FindClusters(obj, resolution = 0.4)
```

```
obj <- SCTransform(obj, vars.to.regress = c("percent.mt", "nCount_RNA", 
                        return.only.var.genes = FALSE)   
obj <- RunPCA(obj, npcs = 100)  
obj <- RunUMAP(obj, dims = 1:60)   
obj <- FindNeighbors(obj, dims = 1:60)  
obj <- FindClusters(obj, resolution = 0.4)  

```

* Only variable genes returned

![pca_plot_old](https://user-images.githubusercontent.com/8886267/74968833-1eefcb00-53e1-11ea-9121-440065338d77.png)

* All genes returned 
![pca_plot_new](https://user-images.githubusercontent.com/8886267/74968852-28793300-53e1-11ea-9bba-1ef09ef69018.png)

* Only variable genes returned
![60dim_0 4res](https://user-images.githubusercontent.com/8886267/74968935-53638700-53e1-11ea-87d8-35d67798d8c9.png)

* All genes returned
![60dim_0 4res_allgenes](https://user-images.githubusercontent.com/8886267/74968940-56f70e00-53e1-11ea-9265-6887431d6d66.png)

**Comment by satijalab** [comment]
Apologies for the confusion, you absolutely should not be regressing on nCount_RNA when using SCTransform, as this is already built in. It sounds like removing this fixes your issue.
