### ISSUE TITLE
Average expression of gene on dotplot

### ISSUE THREAD

**Issue by Zifeng1995** [satijalab/seurat#2649]
Hi,
I was trying to select cells based on the expression of some genes and following your tips as follows

```
# Can I create a Seurat object based on expression of a feature or value in object metadata?
subset(pbmc, subset = MS4A1 > 1)
```

But I found something wrong with the selected cell.
My code is as follows.
```
#select cells based on expression of CD3D
seurat <-subset(seurat,subset =CD3D>1)
#test the expression level of CD3D
VlnPlot(seurat, features ="CD3D")
DotPlot(seurat, features ="CD3D")
```
![image](https://user-images.githubusercontent.com/53402047/75095293-43f56100-55ce-11ea-8aa5-06f502a8fe61.png)
![image](https://user-images.githubusercontent.com/53402047/75095307-67201080-55ce-11ea-9e8e-cca99a1ff888.png)

I was wondering why the average expression value on my dotplot starts from -1. Is there any different  between vlnplot and dotplot? Can anyone help me?

**Comment by satijalab** [comment]
You should use the ViolinPlot to select your thresholds. The DotPlot shows scaled values (which can be both positive and negative). This is because we want to be able to visualize both highly and lowly expressed genes on the same color scale.

**Comment by QiangShiPKU** [comment]
@satijalab In my opinion, it will be better if DotPlot adds the parameter deciding whether scaling average expression values or not.
