### ISSUE TITLE
Interpretation of MixingMetric output

### ISSUE THREAD

**Issue by DanSchnell** [satijalab/seurat#2650]
As implemented in the seurat v3 function, do lower mean values indicate better mixing?
(In the paper it appears that higher values are better.)

Thanks,
Dan Schnell

**Comment by timoast** [comment]
As described in the paper, higher values indicate better mixing.

**Comment by deborah-chasman** [comment]
There is a related question in the repository for the manuscript: https://github.com/satijalab/Integration2019/issues/1

That issue says that in the paper's figure, the mixing metric value is subtracted from the number of neighboring cells considered (default 300) before plotting. It sounds like the value output by the MixingMetric function is a median rank value, where lower is better. Is that true?
