### ISSUE TITLE
Seurat install failed on Mac

### ISSUE THREAD

**Issue by satellite119** [satijalab/seurat#2652]
Hello, when I tried to install Seurat on my Mac and failed several times as below:

> install.packages('Seurat')
also installing the dependency ‘reticulate’

  There is a binary version available but the source version is later:
           binary source needs_compilation
reticulate   1.13   1.14              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Y
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/Seurat_3.1.3.tgz'
Content type 'application/x-gzip' length 3204699 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

The downloaded binary packages are in
	/var/folders/74/jb7xksb52633vs9tn_ddsnzh0000gn/T//RtmprTjIp8/downloaded_packages
installing the source package ‘reticulate’

trying URL 'https://cran.rstudio.com/src/contrib/reticulate_1.14.tar.gz'
Content type 'application/x-gzip' length 1504849 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

* installing *source* package ‘reticulate’ ...
** package ‘reticulate’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘reticulate’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/reticulate’
Warning in install.packages :
  installation of package ‘reticulate’ had non-zero exit status

Do you have any suggestions to fix it?
Thanks

**Comment by Xbar** [comment]
You need the command line compilation tools.
1. If not installed, install Xcode from AppStore. Open XCode on Mac and accept the the user agreement (if poped up). Then close it.
2. Open terminal and run "xcode-select --install". Follow the instructions.

**Comment by satellite119** [comment]
Thank you for your reply. I installed the Xcode and enter the code, but still failed as below:

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘reticulate’
> xcode-select-install
Error: object 'xcode' not found

Thanks

**Comment by Xbar** [comment]
Sorry for the confusion, but you need to type the command in the MacOS Terminal, not the R or Rstudio terminal.
Close R/Rstudio
Open MacOS Terminal
Type "xcode-select --install"

After everything's done, reopen R.

**Comment by satellite119** [comment]
I followed the inctraction and enter the code on MacOS Terminal:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
kyuushous-MacBook-Pro:~ qiushaowei$ xcode-select--install
-bash: xcode-select--install: command not found
kyuushous-MacBook-Pro:~ qiushaowei$ "xcode-select--intall"
-bash: xcode-select--intall: command not found

**Comment by timoast** [comment]
@satellite119 you've mistyped the command, it should be `xcode-select --install` with a space before `--install`. Closing this now as it's not a Seurat issue.

**Comment by satellite119** [comment]
It works, thank you so much.

**Comment by Headtlove** [comment]
I am having the same problem with my Seurat package which fails to install in my R. 
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so
In addition: Warning message:
package ‘Seurat’ was built under R version 4.0.2 

How do I resolve this?

**Comment by Xbar** [comment]
> I am having the same problem with my Seurat package which fails to install in my R.
> 
> > library(Seurat)
> > Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
> > unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so':
> > dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so, 6): Symbol not found: _EXTPTR_PTR
> > Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so
> > Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
> > in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppAnnoy/libs/RcppAnnoy.so
> > In addition: Warning message:
> > package ‘Seurat’ was built under R version 4.0.2
> 
> How do I resolve this?

You installed Seurat on an older version of R and upgraded R later. Please remove Seurat and reinstall it.

**Comment by Headtlove** [comment]
Yes, that worked! Thanks 

Headtlove Essel Dadzie
Ms.,MLS(ASCP)
