### ISSUE TITLE
 Problem with Read10X (). I don't understand the error message

### ISSUE THREAD

**Issue by Mr-Tyrannique** [satijalab/seurat#2653]
Hello everyone !

For first time, I analyze single-cell data thanks to Seurat.
I started by following this tutorial (https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html). But I have a little problem, when I try to create an object with Read10X function (as you can see on screenshot), an error message appear and I don't understand it.

![screen_error_message_seurat](https://user-images.githubusercontent.com/44369538/75110040-3ae5ad80-5629-11ea-8f6c-7dd3adc33fa9.png)

I reformatted my data  to match that of this tutorial (https://davetang.org/muse/2017/08/01/getting-started-seurat/), but it still doesn't work

<img width="509" alt="Screen_data_format" src="https://user-images.githubusercontent.com/44369538/75110041-49cc6000-5629-11ea-8a15-3a64484e8ea2.png">

Has anyone had the same problem? Or have a solution to suggest so that I can move forward?

I thank you in advance.

**Comment by evolvedmicrobe** [comment]
Your files `barcodes.tsv`, `features.tsv` and `matrix.mtx` need to be gzipped with the `.gz` extension on the file name.

**Comment by Mr-Tyrannique** [comment]
I had already tried this solution but unfortunately without success.

The data was produced from version 2 of CellRanger.
If I understood correctly, Seurat therefore considers that the files must be unzipped and that the "features" file is not called features.tsv but genes.tsv

It is only for a version of CellRanger> = 3.0 that the files must be zipped and that the "features" file is called features.tsv.gz

**Comment by timoast** [comment]
You have files called "features.tsv" rather than "genes.tsv", so the function expects the cellranger 3 format which has these files gzipped.

If you actually generated the files with cellranger 2 there's no need to rename them. Don't modify the output from cellranger in any way and you should be able to read the files using the `Read10X` function.

**Comment by Mr-Tyrannique** [comment]
Finally I found the answer, it was because the second line of the .mtx file did not correspond to the number of lines in my barcodes and genes files.

Initially the order was:
number of feature
number of barcodes
number of rows in the matrix. 

In my case the number of feature was reversed with the number of barcode.
