### ISSUE TITLE
SCTransform on SmartSeq data set

### ISSUE THREAD

**Issue by Xbar** [satijalab/seurat#2654]
The integration example in the vignette used SCTransform on data from all different technologies including SmartSeq2, but the preprint paper suggests that the statistics behind SCTransform is based on negative binomial distribution of UMI. 
Is that OK for TPM values from SmartSeq datasets? TPM seems to follow log-normal distribution. Would that break the assumptions?

**Comment by yuhanH** [comment]
You could apply SCTransform to non-UMI data as a normalization.
But it will not eliminate sequencing depth bias.
