### ISSUE TITLE
How to get genes, matrix and barcode files from GEOdatabase

### ISSUE THREAD

**Issue by sudiptaashe** [satijalab/seurat#2655]
Hi,
I would like to use Read10X on human pancreas data available in 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE81547

I have just starting with Seurat analysis. I am not able to find the files for Seurat. I tried unzipping all the downloadable files from this dataset but couldnot locate the specific files. Can you please help with this?

Thanks!
Sudi

**Comment by timoast** [comment]
The `Read10X` function is designed to read the output from Cellranger. It looks like these files are in csv format, so you can read them into R using the `read.table` function.
