### ISSUE TITLE
AverageExpression() -  averaging across all cells or expressing cells?

### ISSUE THREAD

**Issue by sandbox-rgb** [satijalab/seurat#2657]
Hi,

Does AverageExpression() return the average expression of a gene in **all** cells of a cluster: 

avg expr = expression of that gene / total number of all cells in that cluster

or does it return the average expression of that gene for only cells that express the gene? 

avg expr =  expression of that gene / total number of cells that express that gene

The first way would give smaller values, the second way would give higher values. If average expression  averages over cells expressing the gene (second way) then it seems one may need to use Dotplot to see if those higher values are over a very small percentage of cells over almost the whole cluster.

Thanks!

**Comment by timoast** [comment]
It's all cells, not only cells that have >0 counts for the gene. You can find the code here: https://github.com/satijalab/seurat/blob/master/R/utilities.R#L245

**Comment by sameerh** [comment]
Hi,

Is it all cells from a specific cluster or is it the total cells from all the clusters identified?

Thanks!
