### ISSUE TITLE
Question about the integration method

### ISSUE THREAD

**Issue by rojinsafavi** [satijalab/seurat#2658]
I know that as a preliminary step Seurat uses CCA for data integration. I have also read the paper, and it seems that (in case of the atac-seq and RNA integration) the input matrices are (genesXnumber of samples). Please let me know if my understanding is wrong. I would appriciate it if you can explain the CCA step in more detail?

Thank you!

**Comment by timoast** [comment]
Yes, it is also a gene x cell matrix for the RNA/ATAC integration. CCA is explained in the paper and also in the literature: https://en.wikipedia.org/wiki/Canonical_correlation
