### ISSUE TITLE
Colors inconsistent across multiple slices when using SpatialDimPlot

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#2659]
Hello,

When using SpatialDimPlot to visualize across multiple slices in a merged object, if one of the slices lacks a particular discrete grouping, the colors on that slice will not be entirely consistent to other slices that have all of the relevant groupings.

**Comment by satijalab** [comment]
Thanks for pointing this out. Yes this is a bug - we should fix this so that cells in the same cluster receive the same color across multiple slices. This usually happens, but I can see in this particular case (where an entire cluster is missing from one slice), we need to account for that.

**Comment by mojaveazure** [comment]
Hi Jeremy,

Thanks for reporting; this should be fixed on the latest commit of the spatial branch. You can install the patch with `remotes::install_github('satijalab/seurat', ref = 'spatial')`

**Comment by GuoanQi1996** [comment]
I met the same issue and the provided tag `spatial` seems unavailable now.
