### ISSUE TITLE
Seurat alignment - DotPlot resolved for clusters and samples

### ISSUE THREAD

**Issue by 23sd98fg** [satijalab/seurat#266]
Hello, 

I am using the Seurat alignment tool to align a control and activated sample. As in Butler and Satija, bioRxiv, 2017, figure 2D, I would like to look at different markers in a dotplot resolved for the different clusters of the two different samples. 
I select the markers I want to look for and use the DotPlot function.
features.plot <- c("Cd19", "Ms4a1", "Cd3d", "Cd3e", "Cd3g", "Cd8a", "Cd4")
DotPlot(object = pbmc, genes.plot = features.plot, plot.legend = TRUE)
The result is a DotPlot showing the markers for the merged/averaged clusters of the two samples.

With which command can I resolve the data so that the plot is showing the markers for each cluster within the different samples as done in the publication?

Thank you very much for your reply!

Best, 
Laura

**Comment by leonfodoulian** [comment]
Hi,

Assuming that the `clusters` column in your `object@meta.data` slot stores the cluster identities of your cells, you can do the following:

```R
# Create a new column in 'object@meta.data' combining 'orig.ident' and cluster identities
object@meta.data$full.ident <- paste(object@meta.data$clusters, object@meta.data$orig.ident, sep = "_")

# Select genes to plot
features.plot <- c("Cd19", "Ms4a1", "Cd3d", "Cd3e", "Cd3g", "Cd8a", "Cd4")

# Plot gene expression levels using DotPlot()
# 'group.by' allows to group your cells by a given variable in 'object@meta.data'
DotPlot(object = object, genes.plot = features.plot, plot.legend = TRUE, group.by = "full.ident")
```

Best,
Leon

**Comment by 23sd98fg** [comment]
Hi Leon, 

The cluster information was stored in the object@meta.data$ident so adapting your first command slightly and keeping the rest identical solved my issue perfectly. 

object@meta.data$full.ident <- paste(object@meta.data$ident, object@meta.data$orig.ident, sep = "_")
features.plot <- c("Cd19", "Ms4a1", "Cd3d", "Cd3e", "Cd3g", "Cd8a", "Cd4")
DotPlot(object = object, genes.plot = features.plot, plot.legend = TRUE, group.by = "full.ident")

Thank you very much for your quick reply and help!

Best, 
Laura
