### ISSUE TITLE
Issues regarding the Idea of Anchor Filtering

### ISSUE THREAD

**Issue by cadyyuheng** [satijalab/seurat#2660]
Hello Seurat Team!

When I went through the cell paper, I noticed that there is an anchor filtering step which based on the paper is for "ensuring not to identify correspondences between reference and query cells with very divergent expression profiles". According to my understanding, the anchor pairs are found on the CC-space, which is shared by query and reference. Why there is still a need to recheck the high dimensional data if we've already done CCA?

Also, in the paper, it mentions that the similarity score is a distance in the PC-space. I'm a little confused about the differences between this PC-space and the CC-space. 

Thanks!

**Comment by timoast** [comment]
The filtering provides a "sanity check" that the two cells are not very distant from each other in the original data.

The similarity score is used for weighting anchors, and so does not need to be computed in the shared CCA space. Instead we find the distance for each cell to the k nearest anchor cells in PCA space and use this distance to compute a weight for each anchor for the cell.
