### ISSUE TITLE
Question for overlapping between clusters

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#2661]
Hi

When I used Seurat to cluster one PBMC sample, I found two cluters overlapping (cluter 0 and 13 in figure1.pdf). I tried to modify the filtering conditions,  the number of features, and  parameters of clustering (such as "dims"), but the result was similar. I don't know how to deal with this situation. I need your help. Thanks!

[figure1.pdf](https://github.com/satijalab/seurat/files/4248644/figure1.pdf)

**Comment by muhammed-ali** [comment]
You may use the tSNE plot to visualize the data, definitely, it will have a different cluster organization and maybe you could see better-separated clusters that way. If we consider the provided tutorial as a reference, then you could do:

```
pbmc <- RunTSNE(pbmc, reduction = "pca", dims = 1:10)
DimPlot(pbmc, label = TRUE, reduction = "tsne")
```

I hope it helps.

**Comment by lh12565** [comment]
Hi @muhammed-ali. I've tried tsne before, but it divides similar cell subtypes too far apart, such as CD8+ T cell subtypes, B cell subtypes or NK. Is there any other way to solve this issue? Thanks!

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/1081
