### ISSUE TITLE
Removing Assays from Seurat Object

### ISSUE THREAD

**Issue by nevilledusaj** [satijalab/seurat#2662]
After following the vignette for Integration with SCTransform, I would like to remove the integrated and SCT assays from the object to make it smaller in size and more manageable for further downstream analysis. 

I tried the following:
`ch.integrated@assays$integrated <- NULL
ch.integrated@assays$SCT <- NULL`

This reduced the object size significantly, but when I tried to subset this object, I got the following error message:
`Error: Cannot find assay 'integrated' in this Seurat object
Error during wrapup: no slot of name "global" for this object of class "DimReduc"`

Any suggestions for how to properly remove an assay, or how to go about and quickly create a new Seurat object with just the assays, metadata, and reductions that I want?

**Comment by mojaveazure** [comment]
To remove an Assay from a Seurat object, please set the assay as `NULL` using the double bracket `[[` setter (eg. `ch.integrated[['integrated']] <- NULL`)

We strongly urge users to not rely on calling slots directly using `@`, as this doesn't take care of all references to the underlying data. For more details about the getters and setters, please see our Seurat object [cheatsheet](https://satijalab.org/seurat/essential_commands.html).

**Comment by UboCA** [comment]
##Add-in
Actually, seurat wrappers [DietSeurat](https://satijalab.org/seurat/reference/dietseurat) could shrink volume of seurat object by set assays/reductions/graphs...
It's very useful to remove SCT assays or other unwanted sub-structure.
