### ISSUE TITLE
Integrating data sets from distinct patients

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#2663]
Hi Seurat team,

Thanks for developing Seurat. I am using the Anchoring feature in Seurat to integrate 6 data sets - all derived from distinct patients (2 normal and 4 tumor tissues; the normal tissue is not from tumor donors). I am not using SCTransform. For my pipeline, I did the following;

1. Quality control for each library
2. Created a Seurat object for each data set
3. Merged the 2 normal tissues as 1 object (normal), and the 4 tumor tissues as another object (tumor)
4. Normalized normal and tumor tissue objects separately; i.e. normalized the normal tissue (containing 2 normal samples) and tumor tissue (containing 4 normal samples) 
5. Find variable features for normal tissue and tumor tissue objects 
6. Found integration anchors between the object list (normal and tumor tissue objects)
7. Integrated both normal and tumor tissue objects
8. Scaled data and ran PCA
9. Clustering
10. Downstream analysis

Does this approach sound reasonable? At first glance it appears that the cells are clustering by patient, but when I look closely, I see that normal and tumor tissues cluster together (all cell types except the tumor cells), but the bulk of epithelial tumor cells cluster different from normal and between tumor types and because we reasoned that the tumor subtypes we are analyzing might be another reason why cells are not clustering together between them. We do not think it is a batch because of these reasons,  but would like to hear some comments/advice from you/community?

Note: If I use anchoring between all samples, without prior merging of normal or tumor as mentioned above - everything is merged together and no clear distinction is observed between clusters - it's a big mess. This is, in my opinion, not very good, because I know that there are cell types in normal tissues that are not present in the tumor samples... (i.e. other components of normal tissue).

Any advice will be appreciated!

**Comment by timoast** [comment]
You should not run `ScaleData` after integration if you're using `SCTransform`. Please see the [integration](https://satijalab.org/seurat/v3.1/integration.html) vignette for more information.
