### ISSUE TITLE
unused argument (vector.friendly = TRUE) in FeaturePlot

### ISSUE THREAD

**Issue by Shawn10312** [satijalab/seurat#2664]
Hi,

The function of vector.friendly can not be used in FeaturePlot any more.

Why does this happen? And how to figure it out??

Thanks a lot!

**Comment by timoast** [comment]
`vector.friendly` is no longer an argument in `FeaturePlot` or `DimPlot`. You can use the `AugmentPlot` function to achieve the same thing. Also see the ggrastr package: https://github.com/VPetukhov/ggrastr

**Comment by Shawn10312** [comment]
Oh, that really helps.

But it does not have the legends. And I have not found the related index for legends in AugmentPlot function.

**Comment by timoast** [comment]
Original legends and axes will be lost during augmentation with the `AugmentPlot` function. If this is a problem, try the ggrastr package.

**Comment by Shawn10312** [comment]
Yeap.
But in current version of ggrastr package, legends can disturbe raster plots.
Well I will picture the legend manually.
