### ISSUE TITLE
Clustering methods

### ISSUE THREAD

**Issue by Kai6662** [satijalab/seurat#2665]
Hi,
I am wondering that if such clustering methods including umap, pca, kmeans, could be used to bulk tissue expression data clustering. It makes sense or not?

Best regards,
Kai

**Comment by timoast** [comment]
Yes they can. Note that UMAP and PCA are dimension reduction methods not clustering methods.

**Comment by Kai6662** [comment]
Thank you for your  reply.

Best,
Kai
