### ISSUE TITLE
Categorizing cells and adding a class out of two (suppose A or B) in their metadata.

### ISSUE THREAD

**Issue by biobug16** [satijalab/seurat#2666]
Hi @timoast , @mojaveazure and All,
Based on the CNV profile for the cells I want to tag them either as "malignant" or "non-malignant". Towards which I also have the cell ids belonging to each category but I am not sure how to add this information to the meta data of my Seurat object.
Any help in this regard will be highly appreciated.

Thanks

**Comment by timoast** [comment]
Please see the `AddMetaData` function

**Comment by biobug16** [comment]
Hi @timoast, Thanks for your reply.
I have checked the AddMetaData() but not sure about the syntax. I am using following command.
`test<-AddMetaData(test,normal,metadata = 'normal',col.name = 'type')`

Note: normal is the list of cell ids with no CNV.

but getting an error:
```
Error in AddMetaData(test, normal, metadata = "normal", col.name = "type") : 
  unused argument (normal)

```

**Comment by timoast** [comment]
`metadata` needs to be a named vector of metadata to add or a dataframe with cell names as the row names. For example, define a character vector containing "malignant" or "non-malignant" for each cell.
