### ISSUE TITLE
a question about the analysis pipeline in SEURAT3, with HARMONY, LIGER, etc

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2667]
Dear all, 

i am following the tutorials on SEURAT3 wrappers and HARMONY, LIGER, CONOS, etc, as these are presented at : 

https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/liger.html
https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/conos.html

and I am using the commands on our laboratory scRNA-seq datasets. If my understanding is correct, after we process the data according to the methods that are presented in the tutorials,   

we shall follow the tutorial : https://satijalab.org/seurat/v3.1/immune_alignment.html, in order to learn cell specific responses :  

-- Identify conserved cell type markers : FindConservedMarkers
-- Identify differential expressed genes across conditions : FindMarkers

thanks, 

bogdan

**Comment by samuel-marsh** [comment]
Hi Bogdan,

Not member of Dev team but hopefully this can be helpful.

I'm not entirely sure of your question but you wouldn't want to run the immune alignment tutorial after running liger or CONOS as the data is already integrated.  Are you asking specifically about running the final two commands that you identified there?

Best,
Sam

**Comment by tanasa** [comment]
hi Sam, 

yes, the pipeline would have 2 parts : 

**a. part A.** as described in CONOS, LIGER, HARMONY tutorials; 

**b. part B.** as described on the page : https://satijalab.org/seurat/v3.1/immune_alignment.html : 

skipping the functions : FindIntegrationAnchors; IntegrateData; ScaleData, RunPCA, RunUMAP, FindNeighbours, FindClusters

and starting directly in part B with : FindConservedMarkers() and FindMarkers() , on the cell alignments that were performed by CONOS, LIGER, HARMONY etc.

thank you !

**Comment by samuel-marsh** [comment]
Hi Bogdan,

So yes, I mean that sounds reasonable depending on the situation.  I would also point out that circumvents some of the other functionalities of the various packages themselves for comparing and contrasting groups in the datasets.  This is more general bioinformatics question though than it is Seurat issue.  May get better/more in depth answers on general bioinformatics forum.

Best,
Sam

**Comment by tanasa** [comment]
Thanks Sam. "ve posted the question also on Biostars : https://www.biostars.org/p/424350/
although I'd love to hear from Seurat's authors as well, if possible ..

**Comment by satijalab** [comment]
Yes, FindConservedMarkers and FindMarkers can be run on datasets after alignment, regardless of exactly which alignment method is used
