### ISSUE TITLE
question about logFC while using DESeq2 in Seurat

### ISSUE THREAD

**Issue by suvi93** [satijalab/seurat#2668]
Hello, 
          the question I have is - log to which base is reported when we use test.use="DESeq2" in the FindMarkers() function?

I know the default logFC while using Wilcoxon test in FindMarkers() is reported in natural log, is this true when we use DESeq2 as well? 
I have this doubt as DESeq2 reports FC in log to the base 2 and not natural log.

Thanks
Suvi

**Comment by satijalab** [comment]
We report the FC calculated by Seurat, so it is natural log.
