### ISSUE TITLE
Arrows in Velocyto

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#2669]
Hi,
I want to know how arrows are generated in RNA velocity? I read papers but I didn't get clear view of it.
Second thing, can I apply RNA Velocity on the data that has no time points? I have data on adult stage of a species.
Thanks in advance.

**Comment by samuel-marsh** [comment]
Hi ,

Not member of the Dev team but hopefully this can be helpful.  I would suggest posting your question to the velocyto team that designed the algorithm.  This isn't really a Seurat question.
See link here: [https://github.com/velocyto-team/velocyto.py](https://github.com/velocyto-team/velocyto.py)
