### ISSUE TITLE
Error in CreateSeuratObject

### ISSUE THREAD

**Issue by kathyushakov** [satijalab/seurat#267]
Hello,

It is probably a very simple issue, but I'm struggling to create a Seurat object. I have a digital expression data rows as genes columns as cells and whenever I'm trying to create the object I get the following error message:

```R
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric
This is the code I'm using:
hfd <- CreateSeuratObject(raw.data = cell_matrix, min.cells = 3, min.genes = 200, 
                           project = "normal_vs_hf")
```

I've made sure that the expression data is of a numeric class. Can you help me understand why is it happening? 

Thank you,
Kathy

**Comment by Xcubitor** [comment]
Same here :-s Can't work around it so far.

**Comment by kathyushakov** [comment]
Actually with the help of a colleague, I just figured it out! And it seems to work :)

In my case, my initial file wasn't correct - 
You should have `row.names=1` in read.table

**Comment by Xcubitor** [comment]
Hey thanks! I think the issue is that the first column is not identified as row names (genes in this case) but as data. I am trying to fix this now.

**Comment by paolo-kunderfranco** [comment]
Have you resolved?
I am the same problem

**Comment by aina91** [comment]
repro <- CreateSeuratObject(raw.data = repro.data, project = "CTRL")         
 Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  :
  'data' must be of a vector type, was 'NULL'

when i add [row.names=1, header=T] in read..table(),but i also can't createseuratobject, could you give me some suggestions,please~

**Comment by husain223** [comment]
Error in CreateSeuratObject(raw.data = pbmc.data, min.cells = 3, min.genes = 200,  : 
  unused arguments (raw.data = pbmc.data, min.genes = 200)
how to solve this error

**Comment by AndyR2** [comment]
In Sv3, the CreateSeuratObject function has these variables
CreateSeuratObject(counts, project = "SeuratProject", assay = "RNA", min.cells = 0, min.features = 0, names.field = 1, names.delim = "_", meta.data = NULL)

note the change of 'min.genes' to 'min.features' in Sv3.
and there is no argument for 'raw.data' in this function.

go here and follow the directions
https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

**Comment by husain223** [comment]
it works! thank you
