### ISSUE TITLE
Differential gene expression between two subsets

### ISSUE THREAD

**Issue by KinSimon96** [satijalab/seurat#2670]
Dear all,

From original dataset, I subsetted it into two parts:

- One with cells expressing YFP gene
`YFP_cells <- subset(combined, subset = YFP > 0.000001)`
- One with cells who don't express YFP gene
`YFP_neg_cells <- subset(combined, subset = YFP < 0.000001)`

Then, I performed differential analysis for YFP_cells data on the 10 clusters (only 1 is given below):

`current.cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)`
`new.cluster.ids <- c("Group 1", "Group 2", "Group 3",
                     "Group 4", "Group 5", "Group 6",
                     "Group 7","Group 8","Group 9",
                     "Group 10")`
`names(new.cluster.ids) <- levels(YFP_cells)`
`YFP_cells <- RenameIdents(YFP_cells, new.cluster.ids)`

`G1_all_markers <- FindMarkers(YFP_cells, ident.1 = "Group 1", ident.2 = NULL, only.pos = TRUE, logfc.threshold = 0.65)`

I've finally obtained a heatmap with positive markers for all clusters (only some genes are showed here):
`YFP_cells_averages <- AverageExpression(YFP_cells, return.seurat = TRUE)`

`DoHeatmap(YFP_cells_averages, features = c(         
                                     "Krt8","2300002M23Rik","Krt19","Fetub","S100g","Krt14","Krt20")
                                     ,label = FALSE ,draw.lines = FALSE)  + 
  scale_fill_gradientn(colors = RColorBrewer::brewer.pal(n =4, name = "RdBu"))`

Would it be possible to find positive markers between all cells from YFP_neg_cells with every clusters from YFP_cells data?

Example: 
- positive markers of all clusters from YFP_neg_cells with "group 1" from YFP_cells
- positive markers of all clusters from YFP_neg_cells with "group 2" from YFP_cells
- etc
Findmarkers() only allows one seurat object while 2 are required for my issue.

Thanks for reading!
Best

**Comment by KinSimon96** [comment]
If it sounds too hard, I'd be already glad if you could find a way to perform differential analysis between cells expressing YFP and the others, but only with one seurat object from original data called "combined".
Thank you

**Comment by timoast** [comment]
To perform DE between YFP-positive and YFP-negative cells you just need to add a YFP +/- classification to the metadata. You can follow the [immune alignment](https://satijalab.org/seurat/v3.1/immune_alignment.html) vignette for some guidance on how to perform this sort of between-group analysis.
