### ISSUE TITLE
Question about reference-based integration

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#2672]
Hi,

I have some pbmc samples from different patients, including normal, benign and malignant. Could I use one sample as a reference to integrate my samples? If I use a normal sample as a reference to integrate datasets, is there a loss of specific cell populations in cancer samples (the benign and malignant), such as specific tumor infiltrating lymphocyte subtypes? 
And if I use one sample or more than one samples as a reference, some clusters are distributed everywhere (figure1.png, cluster 11). I was trying to adjust many parameters, such as filter condition, Normalization and SCTtransform, dims, metric, resolution, but some clusters always overlap or distribute everywhere. Is there a way to solve it? Thanks!

Code:
```
samples<-c(1,2,....)
seu.list<-list()
for(arg in samples){
    mac.data<-Read10X(data.dir=paste0("/data/count/",arg,"/outs/filtered_feature_bc_matrix"))
	
    colnames(mac.data)<-paste0(colnames(mac.data),"-",arg)
    seu <- CreateSeuratObject(counts = mac.data, project = arg, min.cells = 3, min.features = 200)
	
    seu[["percent.mt"]] <- PercentageFeatureSet(seu, pattern = "^MT-")
    seu <- subset(seu, subset = nFeature_RNA > 200)

    sce<-as.SingleCellExperiment(seu)
    is.mito <- grepl("^MT-", rownames(sce))
    df <- perCellQCMetrics(sce, subsets=list(Mito=is.mito))
    qc.nexprs <- isOutlier(df$detected, type="higher")
    qc.mito <- isOutlier(df$subsets_Mito_percent, type="higher")
    total<-qc.nexprs|qc.mito
    cells<-colnames(sce[,!total])

    seu<-subset(seu,cells=cells)
    seu<-SCTransform(seu)
    seu.list[[arg]]<-seu
}

seu.features <- SelectIntegrationFeatures(object.list = seu.list, nfeatures = 3000)
seu.list <- PrepSCTIntegration(object.list = seu.list, anchor.features = seu.features)
seu.anchors <- FindIntegrationAnchors(object.list = seu.list, normalization.method = "SCT", 
    anchor.features = seu.features, reference = 1)
seu <- IntegrateData(anchorset = seu.anchors, normalization.method = "SCT")

seu <- RunPCA(seu)
seu <- FindNeighbors(seu, dims = 1:40)
seu <- FindClusters(seu, resolution = 0.5)    
seu <- RunUMAP(seu, dims = 1:40)

DimPlot(seu, reduction = "umap",label=TRUE)
```

![figure1](https://user-images.githubusercontent.com/24219321/75523968-f8b4d580-5a47-11ea-844a-9f5824546058.png)

**Comment by timoast** [comment]
We've found reference-based vs all-vs-all integration usually give similar results. However, the main motivation behind reference-based integration is to save time, so if having the integration run for a while isn't a problem for you then you can use the standard workflow. 

Regarding the clustering results, there have been several similar questions asked previously. See #1081 for example

**Comment by lh12565** [comment]
Hi, @timoast, I tried to set metric = 'euclidean' before, but it didn't work. And you said "UMAP is usually just for visualization and I think performing clustering in PC space is generally a better idea" in #2344, so I still used the default "pca", but this issue (overlap) remains unresolved.
