### ISSUE TITLE
Seurat Integration (or Merge) for 7 samples from 2 different batches

### ISSUE THREAD

**Issue by younjung82** [satijalab/seurat#2676]
Hi Seurat Team,
I have several questions regarding integration or merging datasets.

Question 1.
I have 7 datasets from 2 different batches.
I'll name them A1, A2, A3, B1, B2, B3, B4. (A1-3 = Group A, B1-4 = Group B)
Group A and Group B are from two different batches.

I made them into 7 individual Seurat objects.
I applied the same Normalization to the 7 samples to make the Seurat objects.

After making 7 Seurat objects for the individual datasets,
I integrated the 7 Seurat objects to make one integrated Seurat object.
Is this correct?
I was thinking if I needed to merge the Seurat object A1, A2, A3 and then merged the other Seurat objects B1, B2, B3, B4 to pass the two merged SeuratA and Seurat B for integration.

Question 2.
I want to compare these samples in several ways,

1) Group A total vs. Group B total
2) Group A total vs. B1
3) Group A total vs. B2
4) A1 vs. B1+B2
5) A2 + A3 vs. B3 + B4

In this case, is it okay to make a list containing the 7 Seurat objects and then select Seurat objects from the list for each comparison?
For example, to do the 1st comparison,
list01 <- list (A1, A2, A3, B1, B2, B3, B4)
list01.anchors <- FindIntegrationAnchors(object.list = list01, dims = 1:30)
list01.integrated <- IntegrateData(anchorset = list01.anchors, dims = 1:30)

list02 <- list (A1, A2, A3, B1)
list02.anchors <- FindIntegrationAnchors(object.list = list02, dims = 1:30)
list02.integrated <- IntegrateData(anchorset = list02.anchors, dims = 1:30)

Question 3.
If the answer of Question 1 is NO, which means I should've done merge for each batch and integration for the two merged Seurat, can I still do the Question 2 flow?

Thanks.

**Comment by satijalab** [comment]
1. Both workflows are allowable. If you find that there are 'batch effects' for different samples within group A (i.e shared cell types are clustering separately), then you need to integrate all 7 samples separately. If the cells in group A and cells in group B can be effectively merged (i.e., shared cell types group together)), then you can integrate two objects, one from batch A and the other from batch B.

2. I don't quite understand this question. I assume that by comparison, you mean identify differentially expressed genes. In this case, the precise comparisoin you do (i.e. A1 vs B1, or all A vs. all B), will depend on what cells you pass to the FindMarkers command, and your biological question of interest.
