### ISSUE TITLE
jackstraw plot

### ISSUE THREAD

**Issue by obwan74** [satijalab/seurat#2677]
Hello Seurat users,

Jackstraw plot from suerat, I observe all 20 dimensions are significant.
Can this happen? Is that my data is highly dense, do I have to cutdown
the # of features ( i used 4500 features).

Thanks
Adrian
<img width="985" alt="Screen Shot 2020-02-28 at 1 13 56 PM" src="https://user-images.githubusercontent.com/35461985/75574401-36a40080-5a2c-11ea-8b60-4fd65059c690.png">

**Comment by satijalab** [comment]
Yes - it is quite normal for >20 dimensions to be significant (we just show the first 20 as a default).
