### ISSUE TITLE
FindMarkers Error

### ISSUE THREAD

**Issue by KBoostan** [satijalab/seurat#2679]
Hello, 
I have created a tsne plot of neutrophils that were isolated from a larger subset of SingleR data. I wanted to replace the clusters of the neutrophil plot with a reference list from the conditions we are testing, which are labelled "healthy", "adjacent", "contralateral", and "tumor". Now that I have successfully done that, I wanted to find markers of differentially expressed genes of each condition relative to all others. However, when I try the FindMarker function and put ident1= condition, it gives me the error that "comparison (1) is possible only for atomic and list types. 
I will put all relevant code down below. Is there a way I can circumvent this error? Thanks!
![Screen Shot 2020-02-19 at 4 22 58 PM](https://user-images.githubusercontent.com/54972577/75749133-ef409d00-5cd5-11ea-9556-b4424615f760.png)
![Screen Shot 2020-02-14 at 4 04 33 PM](https://user-images.githubusercontent.com/54972577/75749137-f36cba80-5cd5-11ea-8ab8-bce24ef021b0.png)
![Screen Shot 2020-03-02 at 10 36 11 PM](https://user-images.githubusercontent.com/54972577/75749295-59f1d880-5cd6-11ea-9a86-bdf829a6c5e2.png)
![Screen Shot 2020-03-02 at 10 36 23 PM](https://user-images.githubusercontent.com/54972577/75749304-5bbb9c00-5cd6-11ea-82fd-b2a66a887800.png)
![Screen Shot 2020-03-02 at 10 36 36 PM](https://user-images.githubusercontent.com/54972577/75749305-5d855f80-5cd6-11ea-868c-a428c2812f88.png)

![Screen Shot 2020-03-02 at 7 30 14 PM](https://user-images.githubusercontent.com/54972577/75749165-097a7b00-5cd6-11ea-8012-ad7e0d686ce4.png)
![Screen Shot 2020-03-02 at 7 30 05 PM](https://user-images.githubusercontent.com/54972577/75749174-0ed7c580-5cd6-11ea-8888-536f3066311e.png)

**Comment by satijalab** [comment]
If you are interested in finding markers for all cells (not for a specific cluster):

```
tumor.markers = FindMarkers(neutrophil.integrated, ident.1 = 'tumor', assay = 'RNA', group.by = 'group'
```

If you are interested in doing this only for a specific cluster (i.e cluster 1):

```
tumor.markers = FindMarkers(neutrophil.integrated, ident.1 = 'tumor', assay = 'RNA', group.by = 'group', subset.ident='1')
```
