### ISSUE TITLE
DoHeatmap v3 no grouping of cells

### ISSUE THREAD

**Issue by e1992** [satijalab/seurat#2680]
Hi all, 

I am trying to plot a heatmap with DoHeatmap (v3) where I retain the order of the cells specified by "cells =".  My plot only includes the cells specified, but continues to group cells by identity instead of retaining the order. 

Im using
DoHeatmap(cds, cells = my_cells, features = my_features)

Thanks!

**Comment by satijalab** [comment]
Thats correct-  when passing a cells argument, DoHeatmap will continue to group cells by their identity, but will order cells *within* an identity class using the provided argument.

The easiest solution is just to set a constant identity. i.e

```
cds$id = "Constant"
DoHeatmap(cds, cells=my_cells, features=my_features, group.by='id')
```
