### ISSUE TITLE
error: *** caught segfault *** address 0x80, cause 'memory not mapped'

### ISSUE THREAD

**Issue by hzhu48187** [satijalab/seurat#2681]
Hello,

I am new to Seurat, so forgive me if this is a naive question. I installed bioconductor and seurat on my macbook, but I keep getting this error when I try to perform: library('Seurat'). I have uninstalled and re-installed the newest version of R (by removing through R.frameworks and from the apps menu) and newest version of python, but this keeps happening. Do you have any insight on what the issue could be? 

Thanks so much for this package, and I look forward to getting it up and running so I can use it on my data!

Best,
hzhuchan

> library('Seurat')

 *** caught segfault ***
address 0x80, cause 'memory not mapped'

Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch({    import(module)    TRUE}, error = clear_error_handler(FALSE))
 7: reticulate::py_module_available("leidenalg")
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
15: asNamespace(ns)
16: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
17: loadNamespace(package, lib.loc)
18: doTryCatch(return(expr), name, parentenv, handler)
19: tryCatchOne(expr, names, parentenv, handlers[[1L]])
20: tryCatchList(expr, classes, parentenv, handlers)
21: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
22: library("Seurat")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by mojaveazure** [comment]
This seems to be an issue with installing [leiden](https://github.com/vtraag/leidenalg); can you try installing it through Python (ensuring you're using your system's Python instead of Anaconda)?

**Comment by hzhu48187** [comment]
Apologies for the late response! I solved the issue by re-installing R again - thank you anyway for your help!

Best,
Han
________________________________

**Comment by jjyotikataria** [comment]
@hzhu48187 @mojaveazure @troels @timoast 

Hi guys, please help me with this error while installing Seurat on my server with Rversion 4

* installing to library '/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library'
installing source* package 'RcppAnnoy' ...
** package 'RcppAnnoy' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/include" -DNDEBUG -I../inst/include/ -I'/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/include" -DNDEBUG -I../inst/include/ -I'/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c annoy.cpp -o annoy.o
g++ -std=gnu++11 -I"/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/include" -DNDEBUG -I../inst/include/ -I'/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c arch.cpp -o arch.o
gcc -std=gnu99 -I"/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/include" -DNDEBUG -I../inst/include/ -I'/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c init.c -o init.o
g++ -std=gnu++11 -I"/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/include" -DNDEBUG -I../inst/include/ -I'/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/Rcpp/include' -I/usr/local/include -fpic -g -O2 -c version.cpp -o version.o
g++ -std=gnu++11 -shared -L/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/lib -L/usr/local/lib64 -o RcppAnnoy.so RcppExports.o annoy.o arch.o init.o version.o -L/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/lib -lR
installing to /MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/00LOCK-RcppAnnoy/00new/RcppAnnoy/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
sh: line 1: 30574 Segmentation fault (core dumped) R_TESTS= '/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpLAALot/file6ee9246e5d9c'

** caught segfault **
address 0x20, cause 'memory not mapped'

Traceback:
1: Module(module, mustStart = TRUE, where = env)
2: doTryCatch(return(expr), name, parentenv, handler)
3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
6: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE)
7: (function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>)
8: doTryCatch(return(expr), name, parentenv, handler)
9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>), error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e), list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e), list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(package, lib.loc)
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(expr, names, parentenv, handlers[[1L]])
19: tryCatchList(expr, classes, parentenv, handlers)
20: tryCatch({ attr(package, "LibPath") <- which.lib.loc ns <- loadNamespace(package, lib.loc) env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) { P <- if (!is.null(cc <- conditionCall(e))) paste(" in", deparse(cc)[1L]) else "" msg <- gettextf("package or namespace load failed for %s%s:\n %s", sQuote(package), P, conditionMessage(e)) if (logical.return) message(paste("Error:", msg), domain = NA) else stop(msg, call. = FALSE, domain = NA)})
21: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
22: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
23: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE))
24: doTryCatch(return(expr), name, parentenv, handler)
25: tryCatchOne(expr, names, parentenv, handlers[[1L]])
26: tryCatchList(expr, classes, parentenv, handlers)
27: tryCatch(expr, error = function(e) { call <- conditionCall(e) if (!is.null(call)) { if (identical(call[[1L]], quote(doTryCatch))) call <- sys.call(-4L) dcall <- deparse(call)[1L] prefix <- paste("Error in", dcall, ": ") LONG <- 75L sm <- strsplit(conditionMessage(e), "\n")[[1L]] w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w") if (is.na(w)) w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L], type = "b") if (w > LONG) prefix <- paste0(prefix, "\n ") } else prefix <- "Error : " msg <- paste0(prefix, conditionMessage(e), "\n") .Internal(seterrmessage(msg[1L])) if (!silent && isTRUE(getOption("show.error.messages"))) { cat(msg, file = outFile) .Internal(printDeferredWarnings()) } invisible(structure(msg, class = "try-error", condition = e))})
28: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)))
29: tools:::.test_load_package("RcppAnnoy", "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/00LOCK-RcppAnnoy/00new")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing '/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/R-4.0.5/lib64/R/library/RcppAnnoy'
