### ISSUE TITLE
Questions about umap-learn

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#2682]
Hi

I have some questions about umap-learn:
1. I tried to use a pre-computed graph to run umap as @timoast  said in #1081 as follows:
```R
seu<-FindClusters(seu, graph.name = 'integrated_snn')
seu <- RunUMAP(seu, graph = 'integrated_snn')
```
It seems like using umap-learn to run umap. There are some warnings as follows:
```
Warning: The following arguments are not used: n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py:229: UserWarning: Embedding a total of 4 separate connected components using meta-embedding (experimental)
  n_components

        completed  0  /  200 epochs
        completed  20  /  200 epochs
        completed  40  /  200 epochs
        completed  60  /  200 epochs
        completed  80  /  200 epochs
        completed  100  /  200 epochs
        completed  120  /  200 epochs
        completed  140  /  200 epochs
        completed  160  /  200 epochs
        completed  180  /  200 epochs
```
As you see, are there any default values for n.neighbors and other parameters? Do I have to set these parameters? Are there any recommended values for these parameters? 
And what does "Embedding a total of 4 separate connected components using meta-embedding" mean ? Can I ignore this warning or is there any other way to avoid this warning?

2. What's the difference between the following two ways of running  umap using umap-learn:
(1)
```R
seu<-FindClusters(seu, graph.name = 'integrated_snn')
seu <- RunUMAP(seu, graph = 'integrated_snn')
```
(2)
```R
seu <- RunUMAP( seu, dims.use = 1:5,umap.method = "umap-learn")
```

Thanks!

**Comment by satijalab** [comment]
1. Yes you can ignore the error. These parameters are not relevant when running UMAP using a graph.

2. In the second method, UMAP calculates the nearest-neighbor graph itself, and then calculates an embedding. In the first method, you are passing UMAP a pre-computed graph.

**Comment by lh12565** [comment]
Hi @satijalab,  I got a new error when I run first method as follows:
```R
Warning: The following arguments are not used: n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py:229: UserWarning: Embedding a total of 6 separate connected components using meta-embedding (experimental)
  n_components
Error in py_call_impl(callable, dots$args, dots$keywords) :
  TypeError: pairwise_distances() argument after ** must be a mapping, not NoneType

Detailed traceback:
  File "/home/lh/.local/lib/python3.6/site-packages/umap/umap_.py", line 962, in simplicial_set_embedding
    metric_kwds=metric_kwds,
  File "/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py", line 240, in spectral_layout
    metric_kwds=metric_kwds,
  File "/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py", line 122, in multi_component_layout
    metric_kwds=metric_kwds,
  File "/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py", line 53, in component_layout
    component_centroids, metric=metric, **metric_kwds
```
Is there a way to solve it? Thanks!

**Comment by laijen000** [comment]
Hi @lh12565, I am also trying to RunUMAP using graph = 'integrated_snn', and get the same error as you: 

TypeError: pairwise_distances() argument after ** must be a mapping, not NoneType. 

Have you found a way around this error? Thank you!

```
so <- FindNeighbors(so, dims = 1:50, k.param = 15)
so <- FindClusters(so, resolution = 1, algorithm = 4, method = 'igraph', graph = 'integrated_snn') 
so <- RunUMAP(so, umap.method = 'umap-learn', graph = 'integrated_snn')
```

**Comment by lh12565** [comment]
> Hi @lh12565, I am also trying to RunUMAP using graph = 'integrated_snn', and get the same error as you:
> 
> TypeError: pairwise_distances() argument after ** must be a mapping, not NoneType.
> 
> Have you found a way around this error? Thank you!
> 
> ```
> so <- FindNeighbors(so, dims = 1:50, k.param = 15)
> so <- FindClusters(so, resolution = 1, algorithm = 4, method = 'igraph', graph = 'integrated_snn') 
> so <- RunUMAP(so, umap.method = 'umap-learn', graph = 'integrated_snn')
> ```

Hi @laijen000, you can change the reference in the integration steps.
