### ISSUE TITLE
Integrating a different number of different conditions

### ISSUE THREAD

**Issue by jad362** [satijalab/seurat#2683]
Hi- I'm looking to integrate around 9 different samples across multiple conditions but I have a different number of samples per conditions (2 conditions have 1 sample, 2 conditions have 2, and another condition has 3 samples). I'm wondering if there will be a bias towards the conditions with more samples (and by extension, more cells) and if there's a way to combine the samples pre-integration from each condition so that they're treated as one sample and that presumed bias is accounted for. I believe that integrating the individual samples from each condition originally won't help because all of the cells would be retained, so is there any way to fix this issue? 

Thanks for the help!

**Comment by satijalab** [comment]
You can certainly combine samples from multiple conditions together using merge - this concatenates the object together without creating an integrated assay.

See for example:
https://satijalab.org/seurat/v3.1/merge_vignette.html

**Comment by jad362** [comment]
Thanks for the quick reply- would you say it's better to use merge and then integrate the different conditions or integrate first and then integrate integrated objects?
