### ISSUE TITLE
Error in FindTransferAnchors

### ISSUE THREAD

**Issue by lololiam** [satijalab/seurat#2684]
Hi,

I'm getting the same error as in issue[ 1816](https://github.com/satijalab/seurat/issues/1816).

`Error in SparseRowVar2(mat = reference.data, mu = feature.mean, display_progress = FALSE) : 
  Not an S4 object.`

I have run PCA on both objects which I confirmed by viewing the Seurat objects, and tried downsampling both (even though in the aforementioned issue, the memory limitation related to another error message) and received the same error. 

Code is as below:
```
mca.seurat <- FindVariableFeatures(mca.seurat, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
mca.seurat <- ScaleData(mca.seurat, verbose = FALSE)
mca.seurat <- RunPCA(mca.seurat, npcs = 30, verbose = FALSE)
mca.seurat <- RunUMAP(mca.seurat, reduction = "pca", dims = 1:30)

hca.seurat <- FindVariableFeatures(hca.seurat, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
hca.seurat <- ScaleData(hca.seurat, verbose = FALSE)
hca.seurat <- RunPCA(hca.seurat, npcs = 30, verbose = FALSE)
hca.seurat <- RunUMAP(hca.seurat, reduction = "pca", dims = 1:30)

anchors <- FindTransferAnchors(reference = mca.seurat, query = hca.seurat, dims = 1:30)
```
Any advice would be greatly appreciated.

Thanks,
Liam

**Comment by satijalab** [comment]
Thanks Liam. The code here looks correct - so we'd like to check this out in more detail. Can you either attach on object or e-mail a dropbox download link to seuratpackage@gmail.com? If possible, try to reproduce the error on downsampled objects so it will be a bit easier to share.
