### ISSUE TITLE
Problems pulling out CITE-Seq signal - multimodal data

### ISSUE THREAD

**Issue by rodgson543** [satijalab/seurat#2686]
Hi there,

Thanks very much for all your vignettes - they've been really useful. 

I was wondering if you had any advice on anything to try for a problem with signal from 2 of my CITE-seq antibodies:

I have just had the data back from a 10X genomics project, where 6 samples of murine T cells were multiplexed with HashTags, then stained together with 15 CITE-Seq antibodies. 4/6 samples had 10% CD45.1/CD45.1 or CD45.1/CD45.2 spiked in population to act as an internal control, the rest of the sample is CD45.2+/CD45.2+. After de-multiplexing with the HashTags, I had been planning on using CITE-Seq anti-CD45.1 and anti-CD45.2 to identify the spike populations. However, I can't seem to get a signal with them to pull out the populations when using Seurat v3.0.

My troubleshooting so far:
Before sequencing, I confirmed the spike population ratios using flow cytometry, using the same antibody clones for flow as with cite-seq for anti-CD45 isoforms.
I have also previously used the same clones of anti-CD45.1 and CD45-2 antibodies in combination with the same clone anti-CD45 that is used in the HashTag mixture for mass cytometry - with no problems and clear staining. This data, along with logic that the epitopes shouldn't result in competition gave us confidence that we could use these antibodies for further demultiplexing.

So far, I have tried different methods of normalisation for the ADT CITE-Seq data: neither LogNormalize or CLR normalisation (or just looking at raw counts) have managed to pull out the correct populations by looking at FeatureScatter plots or other visualisation methods.

Have you got any ideas of whether to try anything else? I'm quite new to this field and I don't know if anyone's had similar problems with CITE-Seq antibodies not showing signal and how to troubleshoot this?

Thanks a lot in advance,
Rose

**Comment by satijalab** [comment]
This sounds like its likely an issue with experimental design as opposed to normalization strategy - if the experiment worked successfully the signal should be binary and robust to normalization method.

I would suggest visiting https://cite-seq.com/contact/ for experimental troubleshooting. Closing the thread for now, but if you feel it is a computational issue, please feel free to re-open with a bit more description about what you mean by antibody not showing signal (no reads? no difference between positive/negative populations?)

**Comment by rodgson543** [comment]
Thanks very much for your reply and advice.

Rose
