### ISSUE TITLE
FindMarkers: genes with lots of p_val_adj = 1

### ISSUE THREAD

**Issue by alicelee07** [satijalab/seurat#2687]
Hello, 
I performed FindMarkers with default parameters to identify DE genes between two groups (ident.1 = test, ident.2 =control) However, my results showed that most of my genes are p_val_adj = 1 and only 9 out 2403 genes are p_val_adj <0.05 and 11 genes are p_val_adj <0.1:

![image](https://user-images.githubusercontent.com/20826586/76006894-2cc24780-5edb-11ea-99cb-a9efb197e3ec.png)

Should I conclude that only 9 genes are significant? or am I missing something? Please let me what would be the best options to find my DE genes, such as using different parameters. Thank you in advance for your help!

**Comment by satijalab** [comment]
Yes, that is the correct conclusion. We updated our default DE tests based on https://www.nature.com/articles/nmeth.4612, but you can read this article for more information

**Comment by GouQiao** [comment]
> Hello, I performed FindMarkers with default parameters to identify DE genes between two groups (ident.1 = test, ident.2 =control) However, my results showed that most of my genes are p_val_adj = 1 and only 9 out 2403 genes are p_val_adj <0.05 and 11 genes are p_val_adj <0.1. Should I conclude that only 9 genes are significant? or am I missing something? Please let me what would be the best options to find my DE genes, such as using different parameters. Thank you in advance for your help!

Hi Alice,

I also met the same problem. I found lots of genes are p_val_adj = 1. I am not sure about the genes are really significant or not. Did you solve this problem? If you did, could you give me some suggestions? Thanks in advance!
