### ISSUE TITLE
Expression values in Violin plot

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#2688]
![Picture1](https://user-images.githubusercontent.com/61842606/76008137-c803ee80-5ed4-11ea-89d1-bba53eec3dbc.jpg)
I am creating Violin plot using VlnPlot() function of Seurat. However I am getting plots where some of the values in the plot are below zero (Please see attached image). Is it possible for Seurat to output expression level below zero or  minus values. How can I correct it?

**Comment by satijalab** [comment]
The values are not below 0, but the plotting package that estimates density is plotting expected density values that are below 0. This is a result of the GeomSplitViolin that is used for generating the split violin plots and is nothing to worry about. The alternative is to remove the split.by argument from VlnPlot

**Comment by singcell** [comment]
Thank you!
