### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by truittll** [satijalab/seurat#269]
Hello all!

So I am trying to align two different data sets. The same experimental procedures were used on both, but they are done about a month apart. When I look at the tSNE for each data set individually, we see the same distinct cluster, expressing the same DEGs. However, when aligning the data sets this cluster does not separate from the others. So, I figure I must be doing something wrong in the aligning steps. Thoughts?

**Comment by leonfodoulian** [comment]
Hi,

It is difficult to assess what you are doing without checking your code. Can you please share it? Also, you can probably merge both Seurat objects without aligning them, and check whether your tSNE map shows dataset specific clusters, or whether cells from that cluster come from both datasets. 

Best,
Leon
