### ISSUE TITLE
A question about "FindIntegrationAnchors"

### ISSUE THREAD

**Issue by evenDDDDD** [satijalab/seurat#2690]
Hi！
My experiment includes the treatment group and the control group, each group contains a duplicate, that is, a total of four. I only pay attention to the differences between the experimental group and the control group. Should I integrate the repeated data of the experimental group (or the control group first), and then integrate the respective integrated result? 
Attach my part of code here：
.........
immune.anchors1 <- FindIntegrationAnchors(object.list = list(pbmc1, pbmc2), dim=1:20)
immune.combined1 <- IntegrateData(anchorset = immune.anchors1, dims = 1:20)
DefaultAssay(immune.combined1) <- "integrated"
immune.combined1$stim <- "c12"

immune.anchors2 <- FindIntegrationAnchors(object.list = list(pbmc3, pbmc4), dim=1:20)
immune.combined2 <- IntegrateData(anchorset = immune.anchors2, dims = 1:20)
DefaultAssay(immune.combined2) <- "integrated"
immune.combined2$stim <- "s12"

immune.anchors <- FindIntegrationAnchors(object.list = list(immune.combined1, immune.combined2), dim=1:20)
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)
DefaultAssay(immune.combined) <- "RNA"
immune.combined <- FindVariableFeatures(immune.combined, selection.method = "vst", nfeatures = 2000)

immune.combined <- ScaleData(immune.combined,  verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:20)
p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE)
plot_grid(p1, p2)
........
Best wishes！
thank you！

**Comment by satijalab** [comment]
You can do this, but a simpler approach would be to integrate all samples together in one analysis. Then, when you do downstream comparisons (i.e. differential expression), you can compare cells in the treatment vs cells in the control group, regardless of replicate (make sure to use the RNA assay for differential expression)

**Comment by evenDDDDD** [comment]
Sincerely appreciate your reply！
Could you please help me look at the attached code. This is the code I integrated twice without error. Especially, the step after the integration of four data, that is: 
### immune.combined <-FindVariableFeatures (immune.combined, selection.method = "vst", nfeatures = 2000 ) 
If I don't use FindVariableFeatures here, RunPCA will prompt that FindVariableFeatures is missing.
###Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.
Similarly, I performed FindVariableFeatures() on the integrated experimental group and control group before the second integration, and reported the same error. I don't know if the code attached above is feasible.

Sincere thank you !

**Comment by cathalgking** [comment]
> Sincerely appreciate your reply！
> Could you please help me look at the attached code. This is the code I integrated twice without error. Especially, the step after the integration of four data, that is:
> 
> ### immune.combined <-FindVariableFeatures (immune.combined, selection.method = "vst", nfeatures = 2000 )
> If I don't use FindVariableFeatures here, RunPCA will prompt that FindVariableFeatures is missing.
> ###Error in PrepDR(object = object, features = features, verbose = verbose) :
> Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.
> Similarly, I performed FindVariableFeatures() on the integrated experimental group and control group before the second integration, and reported the same error. I don't know if the code attached above is feasible.
> 
> Sincere thank you !


Did you solve this issue? Im trying to get past the "Variable features haven't been set" error.
