### ISSUE TITLE
Cannot get Read10x function (Seurat) to work!

### ISSUE THREAD

**Issue by joyn17** [satijalab/seurat#2691]
Hello all, I am trying to learn how to use R for single-cell RNA seq using the Seurat guided tutorial (pbmc) but I can't even get started because the first function Read10x will not run no matter which version of it I try. I know there are already similar issues but the error I'm getting isn't like any of the ones I've found that were related to a specific package being missing etc. I would really appreciate any input. Here is a sample of what has been coming up:

> library(Seurat)
> library(patchwork)
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> setwd("~/Downloads")
> pbmc <- Read10x("../data/pbmc3k/filtered_gene_bc_matrices/hg19/")
Error in Read10x("../data/pbmc3k/filtered_gene_bc_matrices/hg19/") : 
  could not find function "Read10x"
> list.files(data_dir)
Error in list.files(data_dir) : object 'data_dir' not found
> pbmc <- Read10x(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19/")
Error in Read10x(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19/") : 
  could not find function "Read10x"
> Read10X(data.dir = NULL, gene.column = 2, unique.features = TRUE)
Error in full.data[[1]] : subscript out of bounds
> setwd("~/Downloads/filtered_gene_bc_matrices")
> setwd("~/Downloads/filtered_gene_bc_matrices/hg19")
> Read10X(data.dir = NULL, gene.column = 2, unique.features = TRUE)
Error in full.data[[1]] : subscript out of bounds
> setwd("~/Downloads/filtered_gene_bc_matrices/hg19")
> Read10(data.dir = NULL, gene.column = 2, unique.features = TRUE)
Error in Read10(data.dir = NULL, gene.column = 2, unique.features = TRUE) : 
  could not find function "Read10"

**Comment by timoast** [comment]
The function is `Read10X` not `Read10x`
