### ISSUE TITLE
AddModuleScore - Weighted

### ISSUE THREAD

**Issue by TimJCooper** [satijalab/seurat#2692]
My apologies as this is not an issue, but rather a question. 

I'd like to calculate expression values (via AddModuleScore) using genes identified using differential gene expression analysis. Rather than apply an arbitrary logFC-cutoff (e.g. 1.25), and use all those genes above the threshold - I'd like to calculate scores while weighting for each gene's logFC. For example, those genes with the highest logFC have a greater impact on the final score. Is this possible?

**Comment by satijalab** [comment]
I think this is an interesting idea (effectively to weight module scores based on a pre-establish importance ranking), but its not something we currently support in Seurat. It would not be impossible for you to modify the code in AddModuleScore to do this, but its unlikely that we will address this in the near future. If you do make modifications, please feel free to submit a pull request.

**Comment by NoemieL** [comment]
Hello,
I am interested in applying an individual weight to each gene when using the AddModuleScore function. Did you find a way to manage this, @TimJCooper? Thanks
