### ISSUE TITLE
Inspecting quality of anchor cell pairs when comparing two data sets

### ISSUE THREAD

**Issue by siggia** [satijalab/seurat#2693]
I am following the standard script to integrate a pair of data sets.   https://satijalab.org/seurat/v3.1/integration.html

After running FindIntegrationAnchors() on a pair of data sets, I would like to get some graphical output for which cells are paired and their score; for instance by overlaying via colors the score on a DimPlot() done for each data set separately.  Thus I looked at the anchor class as defined in https://rdrr.io/github/satijalab/seurat/man/AnchorSet-class.html  and the N x 5 data frame in the anchor slot. 

I can not interpret the columns “cell1” etc. There are frequently repeated indices (mapped to different “cell2” entries), so should I just take the one with the best score??  More crucially the max “cell1” entry is larger than the number of cells in that data set (which is the smaller of the two being compared), so I have no idea how to take the cell1 entry and find the appropriate cell in the original data set.  Also the max of the cell1,2 columns are the same, so they must be pointing to some other common table for the lookup back to the original cell labels. There must be a simple way of doing this. 

Can you suggest a sample script that would pull back data from the IntegrationAnchors function to the original data set for overlaying and plotting?? or any other methods for assessing the quality of anchors. Also helpful would be a user set parameter to restrict anchors to only those of certain quality. My data sets probably have only a minority of cells with good homologue in the other data set, hence these questions. I can resort to taking subsets of each set (as defined by clustering) that will plausibly have homologues in the other and proceed that way, but a bit of a mess. 

(ps I have read you Stuart et al paper in cell)

**Comment by satijalab** [comment]
Thanks for your question - I agree that it would be helpful to have scripts that could assist in the interpretation (and if you choose, filtration) of downstream anchors. We have these internally but have not released publicly. We will prepare to do so, and will respond to this issue when ready @andrewwbutler

**Comment by timoast** [comment]
We now have the `AnnotateAnchors()` and a `subset()` function available for anchor objects that allows anchor exploration and filtering.
