### ISSUE TITLE
Error accessing latest Spatial version documentation

### ISSUE THREAD

**Issue by mvhunter1** [satijalab/seurat#2694]
Hi, I'm trying to use the latest version of the Seurat Spatial installation but I get the following error any time I try to access the documentation for a function:

Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Seurat/help/Seurat.rdb' is corrupt

and also get an error in Rstudio whenever I type a function in the command line, saying "Error Retrieving Help: R code execution error". It seems like the help folder for this version is corrupt?

**Comment by andrewwbutler** [comment]
Hi,

Please try restarting your R session.

**Comment by mvhunter1** [comment]
Hi, thanks that fixed the problem!
