### ISSUE TITLE
A problem with add a column to the analysised data without changing the analysis.

### ISSUE THREAD

**Issue by Midsummer723** [satijalab/seurat#2696]
I have a SCTransfromed Data which merged 30 patients data.  
I can use the subsets function to analysis the subgroups( the cases and controls). 
I want to add a column to identify which are controls.  However, I want to use that column to show the whole picture of the 30 patients.  
I want to ask if I can add the column which will not impact the result I already have. 
Because  I tried  to add the column by split the data. I need to merge the data after adding the column which need to do the analysis again that will lead to different plots. 
HOW can I add the column without changing the results? OR is there any other solutions?
Thank you very much.

**Comment by timoast** [comment]
Adding a metadata column will not affect any of the existing data in the object. Please review the tutorials on the Seurat website: https://satijalab.org/seurat/vignettes.html
