### ISSUE TITLE
Deprecated CombinePlots() Function

### ISSUE THREAD

**Issue by Crystalizeee** [satijalab/seurat#2697]
`Warning message:
CombinePlots is being deprecated. Plots should now be combined using the patchwork system. `

So this is the message that pops up whenever I use CombinePlots() function. I do not really know what you guys mean by the patchwork system. Can you explain please how to use this alternative?

**Comment by timoast** [comment]
The CombinePlots function will be removed in the future as this functionality is now supported by the patchwork package: https://github.com/thomasp85/patchwork; https://cran.r-project.org/web/packages/patchwork/index.html

**Comment by PikalaxALT** [comment]
Is there a general recommendation for migrating CombinePlots calls to instead use methods from patchwork?

**Comment by timoast** [comment]
Yes it's quite straightforward and is also being used in the Seurat vignettes right now

**Comment by Dragonmasterx87** [comment]
I'm just adding this here in case someone finds this post and wonders how to arrange in rows or columns. Because p1 + p2 sucks if you have p1, p2....pn. it autos to p1|p2/p3|pn/p(n+1)

```
# where you did 
CombinePlots(plots=list(p1, p2, p3, p4))

# you now do
p1/p2  # arranges plots p1 and p2 in the same row
p1|p2  # arranges plots p1 and p2 in the same column

# So for a 4x4 layout
p1/p2|p3/p4 # arranges p1 & p2 in the same row, p3 & p4 in the same row, while p1+p2 and p3 +p4 are in the same column
```

🐲

**Comment by chlee-tabin** [comment]
Just in case for anyone who finds this post and wonders how to have even more number of plots being combined:

```
pi <- list(p1, p2, p3, p4, p5, p6)
Reduce( `+`, pi ) +
      patchwork::plot_layout( ncol = 3 )
```

Of course, can use other operators as well in a similar fashion.

**Comment by timoast** [comment]
@chlee-tabin you can also do:

```r
patchwork::wrap_plots(p1, p2, p3, p4, p5, p6, ncol = 3)
```

see https://patchwork.data-imaginist.com/articles/guides/assembly.html#functional-assembly
