### ISSUE TITLE
Normalization of protein expression data (geoMFI) of index sort

### ISSUE THREAD

**Issue by Florencia1805** [satijalab/seurat#2698]
Hi, 

I am quite new to R and have been analyzing my scRNAseq data using Seurat with great pleasure. Now I am trying to link my index sort data (protein expression levels from the FACS sort) to my scRNAseq data. I have now added the geoMFI values of five different markers to my metadata. However, I believe I should normalize the protein expression levels so that I can compare them with my RNA expression levels, and now I came across the "CreateAssayObject" function in the vignette but do not fully understand how to apply this to my data. I have tried several things without success. 

To very briefly explain what I have done:

#load data
dat <- read.table(("E:/R/scRNAseq_data_FM_AM_20191003_thymus/counts_thymus/SAN-DA-001_H3JJMBGXC_S5_R2.TranscriptCounts.tsv"), header=TRUE)

#create object
thymus <- CreateSeuratObject(counts = dat, project = "Thymus", min.cells = 3, min.features = 350)

# filter cells based on QC
thymus <- subset(thymus, subset = nFeature_RNA > 350 & nFeature_RNA < 4000 & percent.mt < 22)

# normalize
thymus <- NormalizeData(thymus)

#import valid_cells file to fish out only post QC cells
valid_cells <- read.delim("thymus_valid_cells.csv", sep=";",header = F)
colnames(valid_cells) <- "ID"

#add dataframe with index sort data and add to metadata
index.sort <- read.table("thymus_index_sort_geoMFI.csv", sep=";", header=TRUE, fileEncoding="UTF-8-BOM", row.names=NULL)
thymus <- AddMetaData(object=thymus, metadata=index.sort)

When this gave me an odd protein expression distribution I decided to try the CreateAssayObject function from the vignette, but to be honest I have no idea how to do this correctly. I would ideally like to normalize my geoMFI data ("index.sort") to the same extent as I have done so with my RNA expression data, but how? So I tried the following:

thymus[["FACS"]] <- CreateAssayObject( counts = index.sort)

And got an error: "Error: Cannot add a different number of cells than already present"

So then after some googling I tried:

thymus[["FACS"]] <- CreateAssayObject(thymus[, colnames(x = thymus)])

But then got the error: "Error in as.vector(data) : 
  no method for coercing this S4 class to a vector"

Furthermore, I thought, what about my "index.sort" dataframe in the second function, where to put it? Also, what am I doing by putting down "thymus[["FACS"]]"? 

As a newbie I am a bit clueless at the moment. Hopefully someone knows how to help me out!

Many cheers in advance,
Florencia

**Comment by mojaveazure** [comment]
Hi Florencia,

`CreateAssayObject` takes an expression matrix, not a Seurat object. Your second attempt at `CreateAssayObject` appears to be passing your Seurat object (`thymus`), not your expression matrix (`index.sort`).

You have two options for solving the `Error: Cannot add a different number of cells than already present`:
1. Subset your expression matrix to only the cells present in `thymus` (`index.sort[, colnames(thymus)]`), the pass that to `CreateAssayObject`
2. Create an Assay with `index.sort`, then subset to only the cells present in `thymus` (`protein <- CreateAssayObject(index.sort); protein <- subset(protein, cells = colnames(thymus))`)

Please note, you need **exactly** the same cells in your Seurat object as your assay. If you have more or fewer or different cells, Seurat will error out. If you have cells present in the protein data but not the RNA and vice versa, I would recommend subsetting **both** the Seurat object and the protein expression matrix to a common set of cells first, then try adding the protein data to your Seurat object.
