### ISSUE TITLE
Question about ScaleData()

### ISSUE THREAD

**Issue by Crystalizeee** [satijalab/seurat#2699]
https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

So in this link, there are explanations about how `ScaleData()` does all of these:

* Uses just the variable features found by `FindVariableFeatures()`
* Shifts the expression of each gene, so that the mean expression across cells is 0
* Scales the expression of each gene, so that the variance across cells is 1
* This step gives equal weight in downstream analyses, so that highly-expressed genes do not dominate
* The results of this are stored in pbmc[["RNA"]]@scale.data

I am not too sure what it really means by regressing out "percent.mito" here. 

<B> How exactly does percent.mito content of the cell affect this scaling process onto individual genes in the cells? </B>

And I just realized the numbers of features from before and after `SCTransform()` with `vars.to.regress = "percent.mt"` have reduced.

`nrow(WT_Seurat_Transformed@assays$RNA) # [1] 14367
nrow(WT_Seurat_Transformed@assays$SCT) # [1] 13582`

<B>I guess this is probably to do with the `vars.to.regress` parameter? </B>

One more thing. The variable count in my data has turned out to be 3000 out of 13582 features. 
<B>
Does that mean all these 3000 features would be used for any kinds of dimensionality reduction?

But these 3000 genes are not used for differential gene expression analysis like `FindMarkers()` and `FindAllMarkers` right? 

Would the 13582 genes be used for differential gene expression analysis between clusters?
</B>

Thanks.

**Comment by yuhanH** [comment]
For your first question, you can check the function `RegressOutMatrix` to find more detailed information. Generally, we use a regression model to regress out the effects of latent variables. In your case, it is the percent.mito.
Right, in the SCTransform, `vars.to.regress` regress out the percent.mito by the same method of `ScaleData`.
In default, SCTransform will return top 3000 variable genes, and you can set the number of variable genes you need by `variable.features.n = `.  Those 3000 genes will be used for downstream analyses such as PCA, UMAP.
When you want to find marker genes, you would better use all genes instead of only top 3000 variable genes.

**Comment by denvercal1234GitHub** [comment]
@yuhanH - Thank you for your response. Is there a way to determine the number of variable genes to use? Because SCTransform() allows us to use more than 3000 (default)?

**Comment by yuhanH** [comment]
HI, 
SCTransform sorts the genes by the residual variance to determine the top variance genes. 
Except for `variable.features.n` which limits the number of variable genes , `variable.features.rv.th` which sets residual variance cutoff, can be used to find variable genes.

**Comment by denvercal1234GitHub** [comment]
Thank you @yuhanH! And I suppose, we will just need to try different thresholds here since there is not like a rule of thumb for these residual variance or for the fixed number of variable genes to use?

**Comment by yuhanH** [comment]
You are right... there are no clear cutoff to distinguish variable and constant genes.

**Comment by jyang635** [comment]
Hi @yuhanH,

Could you clarify if the linear regression for "regress out" is performed on log-normalized data or Z-scored data? I think it should be log-normalized data. But it will be great if you could confirm it.

All the best,
Junkai

**Comment by yuhanH** [comment]
hi @jyang635 
You are right. The linear regression model is applied on log-normalized data. Then Z-score transformation is utilized.

**Comment by jyang635** [comment]
> hi @jyang635 You are right. The linear regression model is applied on log-normalized data. Then Z-score transformation is utilized.

Great! Thank you very much~
