### ISSUE TITLE
HTO from the CITE-seq data

### ISSUE THREAD

**Issue by shivarice** [satijalab/seurat#2704]
Hopefully this is the right place to ask this question. But I'm going through [vignette](https://satijalab.org/seurat/v3.1/multimodal_vignette.html) on multi-modal dataset and I was wondering how would I generate the HTO counts from the example dataset that was being used. (here is the link to the dataset: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE100866.)

**Comment by timoast** [comment]
One way to quantify CITE-seq ADTs or HTOs is using [CITE-seq count](https://github.com/Hoohm/CITE-seq-Count). You can also use [kallisto bustools](https://www.kallistobus.tools/introduction)
