### ISSUE TITLE
Cell hashing vignette modification to joint.bcs command required for correct results on our dataset

### ISSUE THREAD

**Issue by heathergeiger** [satijalab/seurat#2705]
We are currently working on a dataset where all cells present in the HTO output are present in the RNA output, but not vice versa. A handful of cells have RNA but not HTO information, but all cells with HTO information have RNA information.

Anyway, we noticed a piece of code from the vignette produces incorrect output when run on our data.

Common part of the code (to read in matrices from CellRanger for RNA and CITE-Seq-Count for HTO):

`RNA_counts <- Read10X(paste0("Sample_",sample,"-cDNA/compbio/outs/filtered_feature_bc_matrix/"));HTO_counts <- Read10X(paste0("Sample_",sample,"-HTO/compbio/umi_count/"),
    gene.column=1)
`

Code I originally used based on the vignette (that provides incorrect results):

`joint.bcs <- intersect(colnames(RNA_counts),colnames(HTO_counts));RNA_counts <- RNA_counts[,joint.bcs];HTO_counts <- HTO_counts[,joint.bcs]
`

Code that provides correct results:

`joint.bcs <- intersect(colnames(HTO_counts),colnames(RNA_counts));RNA_counts <- RNA_counts[,joint.bcs];HTO_counts <- HTO_counts[,joint.bcs]
`

Assuming this is some issue with subsetting by column name not behaving as expected with sparse matrix format?

**Comment by andrewwbutler** [comment]
Hi @heathergeiger ,

It looks like the only difference between the two code chunks is the order of the arguments to the `intersect` function? The order here shouldn't matter. Could you elaborate a bit more on why it gives incorrect results and provide an example that we could try reproducing (either post here or send to abutler@nygenome.org)?
