### ISSUE TITLE
Seurat with MultipleDataSet integration with multi-modal data CITE-seq 

### ISSUE THREAD

**Issue by marencc** [satijalab/seurat#2706]
I have a question regarding this [issue: 924](https://github.com/satijalab/seurat/issues/924) What would it be the proper way of analyzing the data.
So far, I have followed your "Standard Workflow" for each "Control-Stimulated" data, then Integrating that. 
Afterwards, I've divided again in Control/Stimulated to add the corresponding protein data to each data set. 
Afterwards, I've proceeded to the "Using Seurat with multi-modal data" for each Control/Stim data set.
 But, now I was wodering if it's logical to now re-integrate using the protein expression levels as default assays? Or would it be sense-less? Is it correct to integrate "Twice"?
Or Should I follow the standar workflow for each Control/stim and then integrate it with just the protein data? or both the rna and the protein data integrated?

**Comment by satijalab** [comment]
We would suggest performing separate integrations of both the protein and RNA data. In our internal analyses (stay tuned for public releases), we have observed good performance in using Seurat v3 to harmonize both scRNA-seq and ADT data from CITE-seq, in separate analyses, using the standard workflow for each assay.
