### ISSUE TITLE
Minimum requirement for HTO UMI count

### ISSUE THREAD

**Issue by Jimmyyun** [satijalab/seurat#2709]
Hi,

I was wondering if there is some minimum requirement for UMI count per cell in HTO library. I believe it would require for certain UMI count to separate multiplexing samples? 
ps) Our data was about 90 UMI count per cell, and cutoff was like 40. 

Cheers,
Jimmy

**Comment by satijalab** [comment]
There is no strict cutoff, but these numbers seem reasonable. In the Hashing paper in genome biology, we ran the hashing antibodies over a large dilution series and did not see significant degradation in performance (I believe the lowest dilution resulted in ~20 UMI/cell), with the caveat that this was on cell line data.

**Comment by Jimmyyun** [comment]
Thank you for the reply!
I guess my concern is if we have too less UMI counts, we would lose potential matchup with RNA cell barcodes. Relatively lot less cell barcodes would be detected in HTO library. So, initially let's say you aim for 5,000 cell recovery, but you might end up losing additional 2,000 cells because HTO library didn't have enough cell barcode coverage. Have you seen a case like this?
