### ISSUE TITLE
Error when running FindClusters with >1e5 cells

### ISSUE THREAD

**Issue by gabprg** [satijalab/seurat#271]
Hello,

I wanted to report the fact that the FindClusters function fails when your Seurat object contains > 1e5 cells. Specifically, the error occurs because the edge file, when printed out, contains scientific notation for the cell number 100,000 , which then causes ModularityOptimizer.jar to throw an error when reading it as input.

To provide you some detail, I run the function with the following command:
`seur <- FindClusters(seur,
                       dims.use = 1:40,
                       resolution = 1,
                       print.output = T,
                       save.SNN = T,
                       plot.SNN = F,
                       reuse.SNN = T)`

Which throws the following error:
"
Exception in thread "main" java.lang.NumberFormatException: For input string: "1e+05"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at ModularityOptimizer.readInputFile(ModularityOptimizer.java:184)
	at ModularityOptimizer.main(ModularityOptimizer.java:74)
"

And when I go and look into the temporary edge_[xxx].txt file, here is an excerpt:
"
1e+05   91852   0.111111111111111
1e+05   91969   0.0909090909090909
1e+05   92005   0.0714285714285714
1e+05   92127   0.0714285714285714
1e+05   92226   0.111111111111111
1e+05   92268   0.0714285714285714
"

Seems like this should be an easy fix at least!

Thanks,
Gabriela

**Comment by andrewwbutler** [comment]
Hi Gabriela,

Thanks for reporting this! A quick temporary fix would be to run `options(scipen=10)` before running `FindClusters`. This should force it to write properly.

**Comment by gabprg** [comment]
Yep, that solves the issue! Thanks!
