### ISSUE TITLE
How to subtract the background noise  from total signal

### ISSUE THREAD

**Issue by songeric1107** [satijalab/seurat#2710]
I have two markers to show the background noise，igG1 and igG2，how to subtract them from total signal in Seurat 

Thank you

**Comment by satijalab** [comment]
We dont have specific functionality for this now (stay tuned), but you can try using our `RegressOut` function to do this if you would like. Analagous to regressing RNA levels on mitochondrial percentage, you could regress protein levels on total IgG expression.
