### ISSUE TITLE
Dimensionality of Clusters in Reclustering Using Subset

### ISSUE THREAD

**Issue by iSinedeus** [satijalab/seurat#2711]
Hi,

I am analyzing a dataset and want to recluster some of my clusters to look at them more in depth. I am using the subset() function to do this and I was wondering if I should plot elbowplots and jackstrawplots to define the dimensionality of these individual clusters in order to determine the number of dims used in reclustering for the function FindNeighbors() in my new dataset. My initial dataset is not especially larger (~5k cells). Sorry it's a bit of a simple question but I wasn't able to find an answer to this elsewhere.

Thank you

**Comment by satijalab** [comment]
Yes, you can re-estimate dimensionality when performing subclustering.
