### ISSUE TITLE
RenameIdents bug

### ISSUE THREAD

**Issue by petervangalen** [satijalab/seurat#2714]
If you use RenameIdents to give one of the (numeric) clusters the same name as an already existing metadata column, the renaming will be erroneous.

For example, if the Seurat object pbmc had a numeric metadata column named "B", and you try use the following, unexpected levels(pbmc) will ensue:

pbmc <- RenameIdents(object = pbmc, "0" = "Tumor", "1" = "B", "2" = "Progenitor", "3" = "TNK", "4" = "Mono", "5" = "HSPC")

**Comment by mojaveazure** [comment]
This is not a bug. We say in the documentation that if you pass the name of a metadata column to any identity-setting function, it uses that instead of the character value.
