### ISSUE TITLE
Some values of meta.data become NA after CreateSeuratObject

### ISSUE THREAD

**Issue by Alisa-YTC** [satijalab/seurat#2715]
Hi,

I'm using Seurat_3.1.4 and trying to do CreateSeuratObject and SplitObject.
I have 2 different objects.
The function of CreateSeuratObject works well for the first object but not for the second one.

I use the code as following:
stripped.cells <- CreateSeuratObject(
  counts = tumor_subset@raw.data,
  meta.data = tumor_subset@meta.data)
Somehow the meta.data of the second one would get NA and can not do SplitObject for next step.
The raw.data and meta.data all look fine before CreateSeuratObject.

<img width="762" alt="螢幕快照 2020-03-11 下午10 52 58" src="https://user-images.githubusercontent.com/62090349/76493484-f2cbd680-63ef-11ea-8fc9-1414cf6a3f06.png">

I really appreciate any help

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can help a bit.  It looks like you are trying to use CreateSeuratObject on existing Seurat Object.  Can you explain goal a bit more?  Why not just use `subset`?

Best,
Sam

**Comment by Alisa-YTC** [comment]
Hi Sam,

Thank you so much for your email.

My goal is to perform SCTransform normalization.
The existing Seurat Object had already been calculated so I want to strip
the calculated part and split by the "analysis".

As Fig1, tiss_subset_tumor2 is the existing Seurat Object.
I use subset to generate that and the meta.data contains all of the INFO
(as Fig2).
However, after I used  CreateSeuratObject, the INFO would become NA (as
Fig3) and I kept getting  "Error in CellsByIdentities(object = object,
cells = cells)".

The goal is to use tiss_subset_tumor2 to perform SCTransform normalization.
I am a very beginner and try to learn it.
I really appreciate your help.

Best,
Yu-Ting

**Comment by timoast** [comment]
@Alisa-YTC you can't attach images via email so if you want to attach some plots please use the github page.

Your data looks a little weird, you can see that the first cell has 594781 counts whereas the second cell has 30 counts. I suggest you look closely at the matrix that you're using to create the Seurat object, there's likely a problem with it.

**Comment by Alisa-YTC** [comment]
Hi,

Sorry I didn't know I can't attach images via email.

I also think n_Count_RNA looks weird.
I expected  count and feature are associated with nGene and nReads which look fine in existing Seurat Object.
<img width="843" alt="Fig2" src="https://user-images.githubusercontent.com/62090349/76562379-80e0a500-6462-11ea-98ad-76ff6b7c8378.png">

Is that possible the problem is caused from existing object?
I used subset to get existing object as the attachment.
<img width="1277" alt="Fig1" src="https://user-images.githubusercontent.com/62090349/76563017-d5d0eb00-6463-11ea-9ac6-f012f961c6d4.png">

Thank you so much!

**Comment by satijalab** [comment]
The problem is that your raw data slot has 27350 rows (suggesting that there are 27350 cells), but your meta data slot only has 3620 columns.

This should work:
```
stripped.cells <- CreateSeuratObject(counts = tumor_subset@raw.data[rownames(tumor_subset@meta.data),meta.data = tumor_subset@meta.data)
```

**Comment by Alisa-YTC** [comment]
It works!
Thank you so much!

**Comment by carmensandoval** [comment]
Hi,

I'm getting a similar error when using `subset`.

My original object has 698,820 cells, and this is the same across @metadata, @assays$RNA@scale.data, @assays$RNA@data, and @assays$RNA@counts.

However, when I create a subset of the object using:

```
cells.keep <- my_object %>% colnames %>% sample(., size = length(.) * 0.05)
object_small <- my_object %>% subset(cells = cells.keep)
```

I get an object where consistently ~1% of rows in the metadata are NA.

**Comment by paupuigdevall** [comment]
The same issue with NA's in the metadata explained by @carmensandoval is observed on my side. Did you find any workaround?

**Comment by shexiaolu** [comment]
I also meet same issue when i use subset function.Any solutions?

**Comment by shexiaolu** [comment]
I seem to figure out my problem. I just checked out the row name of seurat object metadata and i found it turned to the number not barcode.When i rename the row name with barcode , it works! By the way, why dose the row name of metadata turn to number when i use mutate() to add a column to the metadata?

**Comment by erosix** [comment]
Having the same issue. Did someone find out why row.names change into numbers and how to avoid this?

**Comment by rschauner** [comment]
The tidyverse is pretty opinionated, and as such, belives rownames should not exist, they should be columns. They hold information, thus should not be "special". As such, many of the functions silently strip rownames. If you use `rownames_to_column()` and `column_to_rownames()` you can keep them pretty easily when using `mutate()`
