### ISSUE TITLE
Deploying Shiny apps using Seurat library to shinyapps.io

### ISSUE THREAD

**Issue by dataMaster-Kris** [satijalab/seurat#2716]
Hi,

Given the recent trend of providing interactive web applications to explore scRNA-seq data with manuscripts, we made an app using R Shiny package. The app works fine locally but when I tried to deploy it on RStudio's [shinyapps.io](https://www.shinyapps.io/), it gave me the following error:

Error: Unhandled Exception: Child Task 702752924 failed: Error parsing manifest: Unable to determine package source for Bioconductor package Seurat: Repository must be specified

I have specified the Bioconductor repository using the method mentioned [here](https://stackoverflow.com/questions/60263496/unable-to-deploy-app-to-shinyapps-io-unable-to-determine-package-source). As I understand and also indicated in the linked StackOverflow question, Seurat is not on Bioconductor. I tried several ways to specify the repository for Seurat but failed. 

Can you please advise?

Here is a minimal script to reproduce the error.

         library(shiny)
         library(Seurat)

            ui <- fluidPage(
   
           titlePanel("Old Faithful Geyser Data"),
 
          sidebarLayout(
             sidebarPanel(
                   sliderInput("bins",
                     "Number of bins:",
                     min = 1,
                     max = 50,
                     value = 30)
                ),
      
                 mainPanel(
                 plotOutput("distPlot")
                  )
                )
               )

            server <- function(input, output) {
   
             output$distPlot <- renderPlot({
      
             x    <- faithful[, 2] 
              bins <- seq(min(x), max(x), length.out = input$bins + 1)
      
              hist(x, breaks = bins, col = 'darkgray', border = 'white')
               })
            }

           shinyApp(ui = ui, server = server)

You can reproduce the error by trying to deploy it on shinyapps.io with a free account. It is caused by the requirement of Seurat library and goes away when Seurat is not required.

**Comment by mojaveazure** [comment]
Hi,

This is likely because we've added a `biocViews` tag to Seurat in an attempt to force R to install dependencies from Bioconductor in addition to CRAN. However, this seems to have caused more problems without actually solving the issue of depending on Bioconductor packages while being on CRAN.

As such, we've [removed the Bioconductor dependencies and the `biocViews` tag on the latest development version of Seurat](https://github.com/satijalab/seurat/issues/2675#issuecomment-594866188). Try using that version, if shinyapps.io allows you to use GitHub packages rather than CRAN ones, and let me know if that works. We don't yet have a timeline for when the next CRAN release will happen, fully removing `biocViews` from Seurat.

**Comment by dataMaster-Kris** [comment]
Thanks, it worked.

**Comment by Lobbii** [comment]
I have similar issue.
Here is script of global.R: 
install.packages("BiocManager")
BiocManager::install("multtest")
BiocManager::install("Biobase")
devtools::install_version(package = 'Seurat', version = package_version('3.1.5'))
library("Seurat")


Uploading bundle for application: 2338352...Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package lsei
Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package npsurv
DONE
Deploying bundle: 3177156 for application: 2338352 ...
Waiting for task: 735178753
  building: Processing bundle: 3177156
  building: Parsing manifest
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 735178757 failed: Error parsing manifest: Unable to determine package source for Bioconductor package Biobase: Repository must be specified

**Comment by Lobbii** [comment]
> Hi,
> 
> This is likely because we've added a `biocViews` tag to Seurat in an attempt to force R to install dependencies from Bioconductor in addition to CRAN. However, this seems to have caused more problems without actually solving the issue of depending on Bioconductor packages while being on CRAN.
> 
> As such, we've [removed the Bioconductor dependencies and the `biocViews` tag on the latest development version of Seurat](https://github.com/satijalab/seurat/issues/2675#issuecomment-594866188). Try using that version, if shinyapps.io allows you to use GitHub packages rather than CRAN ones, and let me know if that works. We don't yet have a timeline for when the next CRAN release will happen, fully removing `biocViews` from Seurat.

Hi, I tried to install Seurat through GitHub, but it didn't work. Here is my script to install Seurat:

 %
if(!require(Seurat)){
  library(devtools)
  install_github(repo = 'satijalab/seurat', ref = 'develop', force=T)
  require(Seurat)
}
 

rsconnect::deployApp('/Users/mjia/Desktop/Seurat_Object/SC340_Aging/')
Preparing to deploy application...
Update application currently deployed at
https://mij51.shinyapps.io/sc340_aging/? [Y/n] Y
DONE
Uploading bundle for application: 2338352...Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package lsei
Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package npsurv
DONE
Deploying bundle: 3180113 for application: 2338352 ...
Waiting for task: 735597225
  building: Processing bundle: 3180113
  building: Parsing manifest
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 735597227 failed: Error parsing manifest: Unable to determine package source for Bioconductor package Seurat: Repository must be specified

**Comment by ChristophH** [comment]
This is a known issue in the current version of sctransform. See [sctransform issue #72](https://github.com/ChristophH/sctransform/issues/72) for a discussion of the problem and a link to a solution.
