### ISSUE TITLE
Only one reference for FindIntegrationAnchors

### ISSUE THREAD

**Issue by yewero** [satijalab/seurat#2717]
I am using `Seurat v3.1.4` for label transferring.

But I have only one reference and one query dataset.

```
reference.list <- res.list["smartseq2"]
res.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
```
I got an error for this:
```
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Error in which(x = object.classes, useNames = TRUE) :
  argument to 'which' is not logical
```

How to perform `FindIntegrationAnchors` with only one reference dataset and for label transferring?

**Comment by timoast** [comment]
What's your goal? I think the function you want is FindTransferAnchors rather than FindIntegrationAnchors

**Comment by satijalab** [comment]
I'll agree with Tim's comment. You are looking to use FindTransferAnchors- see for example the code below:

```
pancreas.anchors <- FindTransferAnchors(reference = pancreas.reference, query = pancreas.query, 
    dims = 1:30)
predictions <- TransferData(anchorset = pancreas.anchors, refdata = pancreas.reference$celltype, dims = 1:30)
```

**Comment by yewero** [comment]
@timoast Thanks. My goal is to obtain a batch-corrected expression matrix using these two datasets and then transfer the reference ID to the query dataset.

**Comment by timoast** [comment]
If you want to integrate two objects you need to put them both in the object list, eg:

```r
anchors <- FindIntegrationAnchors(object.list = list(object1, object2), dims = 1:30)
integrated <- IntegrateData(anchors)
```

See the vignettes for more information: https://satijalab.org/seurat/v3.1/integration.html

**Comment by AC-H** [comment]
@timoast Hi Tim, I have same issue as @yewero. I have only one reference and only one query sc-data set and y can't run **_FindTransferAnchors_** from _integrarion tutorial_ I got this error:
```
Error in UseMethod(generic = "RenameCells", object = object) : 
  no applicable method for 'RenameCells' applied to an object of class "list"

```
