### ISSUE TITLE
Cell count in each cluster when comparing two samples with different conditions

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#2718]
![Picture1](https://user-images.githubusercontent.com/61842606/76593256-d4cfa600-64c3-11ea-82cc-bffe1f9e1b6d.png)

I wanted to determine if the number of particular cell type in a cluster is increasing or decreasing with the treatment. I am using stimulated vs. control PBMC datasets vignette for this analysis.

Question:
How to determine the cell number in each cluster associated with CTRL and STIM samples such as how many B cells and T cells in CTRL and STIM samples.

Is it even possible to determine absolute counts since we are using  "anchor.features = 2000"? just wondering

Thank you

**Comment by satijalab** [comment]
you can use the `table` command in R, for example, 

```
table(Idents(immune.combined), immune.combined$stim)
```

Hope that helps!
