### ISSUE TITLE
Questions about umap-learn

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#2719]
Hi

I got a error when I used a pre-computed graph to run umap as follows:
```R
seu<-FindClusters(seu, graph.name = 'integrated_snn')
seu <- RunUMAP(seu, graph = 'integrated_snn')

Warning: The following arguments are not used: n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py:229: UserWarning: Embedding a total of 6 separate connected components using meta-embedding (experimental)
  n_components
Error in py_call_impl(callable, dots$args, dots$keywords) :
  TypeError: pairwise_distances() argument after ** must be a mapping, not NoneType

Detailed traceback:
  File "/home/lh/.local/lib/python3.6/site-packages/umap/umap_.py", line 962, in simplicial_set_embedding
    metric_kwds=metric_kwds,
  File "/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py", line 240, in spectral_layout
    metric_kwds=metric_kwds,
  File "/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py", line 122, in multi_component_layout
    metric_kwds=metric_kwds,
  File "/home/lh/.local/lib/python3.6/site-packages/umap/spectral.py", line 53, in component_layout
    component_centroids, metric=metric, **metric_kwds
```
Is there a way to solve it? Thanks!

**Comment by satijalab** [comment]
I can't tell what is causing the error from this info, but perhaps the following below will help

1. The warning messages are displayed whenever running UMAP on a graph, and are not a cause for concern.
2. Can you confirm that the graph is valid for clustering - i.e.
```
seu <- FindClusters(seu, graph = 'integrated_snn')
```
return valid results?
3. Do the following commands work?
```
seu <- RunUMAP(seu,dims=1:30)
```
and
```
seu <- RunUMAP(seu,dims=1:30,umap.method='umap-learn')
```

Just trying to get a sense of whether the error is with your object, or with the python UMAP install

**Comment by lh12565** [comment]
Hi, @satijalab , when I run FindClusters, it seems to be successful with no error as follows:
```R
seu <- FindClusters(seu, graph = 'integrated_snn')

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|

**************************************************|
Maximum modularity in 10 random starts: 0.9440
Number of communities: 36
Elapsed time: 213 seconds
4 singletons identified. 32 final clusters.

class(seu@graphs$integrated_snn)

[1] "Graph"
attr(,"package")
[1] "Seurat"
```

It works with the command "seu <- RunUMAP(seu,dims=1:30)" and "seu <- RunUMAP(seu,dims=1:30,umap.method='umap-learn')".

By the way, I use the integration method to integrate my samples before running umap with  pre-computed graph. When I change the reference samples, it works. But I still want to know why this error occur.
And I used the uwot method and umap-learn (use dim not the pre-computed graph) before, but some clusters always overlap or distribute everywhere as in #2672 figure1.png, so I'm using the pre-computed graph method now.

**Comment by MaxKman** [comment]
Hi, just chiming in to say that I have the exact same problem. Trying to use the graph from the clustering routine in RunUMAP results in the above error. Python installation of umap-learn works fine in general.

**Comment by laijen000** [comment]
Hi @MaxKman and @lh12565 , I am having the same problem, would you mind sharing if you found a solution? Thank you so much!
