### ISSUE TITLE
Hierarchical integration on multiple datasets

### ISSUE THREAD

**Issue by liuxl18-hku** [satijalab/seurat#2723]
### A bit of context

We are working on the large dataset with >300k cells, those samples are from multiple patients and each patient also has > 1 samples. At the beginning, we are trying to do Integration on all samples in one go: `SCTransform() on each samples -> PrepSCTIntegration -> FindIntegrationAnchors(..., normalization.method = "SCT", ...) -> IntegrateData(..., normalization.method = "SCT", ...)`

However, we suffered from the problem of too large sparse matrix as mentioned in issue #1029 

Now we want to use a hierarchical approach, basically, integrate samples for each patient first, then integrate all integrated objs of patients.

### Question

Thanks to the active community of Seurat, I always can find a useful suggestion here. Would like to pick u guys' mind for how to perform such hierarchical integration best.

bless~
Xingliang

**Comment by satijalab** [comment]
1. Please try using our 'reciprocal pca' workflow, which has dramatically improved speed and memory requirements, and may avoid this error entirely.

IntegrateData actually already works hierarchically - with the samples integrated based on a tree of similarity. However, if you want to select your own order of integration, you can specify this using the sample.tree argument. For example, you could specify to first integrate samples from the same patient, and then to integrate samples across patients

**Comment by liuxl18-hku** [comment]
Hi @satijalab ,

Thank u very much for ur comments. I forgot to mention, rpca has already been applied, my bad.

Two questions just for curiosity:
1. The issue I mentioned #1029 , is that because of large memory or because of bug in Matrix package (cannot support vector longer than 2^31)
2. Is specifying sample.tree in IntegrateData can help to get around the long vector issue in #1029 or not.

Thank you!
bless~
