### ISSUE TITLE
FindTransferAnchors error 

### ISSUE THREAD

**Issue by rojinsafavi** [satijalab/seurat#2726]
I integrated two datasets with Harmony, and when I try to do atac-seq + scRNAseq alignment I get the following error at the anchoring step.

`rna_seurat`
An object of class Seurat 
58361 features across 27996 samples within 2 assays 
Active assay: SCT (25289 features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
`unintegrated`
An object of class Seurat 
86924 features across 17327 samples within 1 assay 
Active assay: ATAC (86924 features)
 3 dimensional reductions calculated: lsi, umap, harmony
integrated
​
# Coembed ATAC and RNA
```
transfer.anchors <- FindTransferAnchors(reference = rna_seurat, query = unintegrated, 
                                    features = VariableFeatures(object = rna_seurat), 
                                    reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")
```
​
Error in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length
Traceback:

1. FindTransferAnchors(reference = rna_seurat, query = unintegrated, 
 .     features = VariableFeatures(object = rna_seurat), reference.assay = "RNA", 
 .     query.assay = "ACTIVITY", reduction = "cca")
2. RenameCells(object = query, new.names = paste0(Cells(x = query), 
 .     "_", "query"))
3. RenameCells.Seurat(object = query, new.names = paste0(Cells(x = query), 
 .     "_", "query"))
4. `rownames<-`(x = `*tmp*`, value = new.cell.names)
5. `row.names<-`(`*tmp*`, value = value)
6. `row.names<-.data.frame`(`*tmp*`, value = value)
7. `.rowNamesDF<-`(x, value = value)
8. stop("invalid 'row.names' length")

**Comment by timoast** [comment]
Are you sure the `ACTIVITY` assay is present in your scATAC-seq dataset? It is not listed in the object summary above

**Comment by saisomesh2594** [comment]
Hi, 

I am facing the same error. I am trying to use `FindTransferAnchors` by using the `SCT` assays of both reference and query and it fails in the `RenameCells` step. 

Any idea what's causing this?

Thanks!

**Comment by rojinsafavi** [comment]
Yes I do have that, here is a screenshot of my notebook
![image](https://user-images.githubusercontent.com/19545198/80018843-8252b380-848b-11ea-8e38-0547918ac69f.png)

**Comment by timoast** [comment]
Can you please verify that this is still an issue with the current release of Seurat (v3.1.5)?

**Comment by rojinsafavi** [comment]
Yes,
packageVersion("Seurat")
[1] ‘3.1.5’

**Comment by timoast** [comment]
Now fixed on the develop branch (https://github.com/satijalab/seurat/commit/0ef1df468576075c2f4298240c190e5f888935e1)

**Comment by JLTrincado** [comment]
Dear authors,

I have this same issue. Two scRNA-seq sets processed independently via SCT. At the time of FindTransferAnchors it gives the same error pointed in the first posts:

`
R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(Seurat)

> 
> cat(paste0(Sys.time(),"Starting script...\n"))
2020-06-17 17:04:32Starting script...
> #reference
> cat("Loading BATLLE_18 CD4...\n")
Loading BATLLE_18 CD4...
> BATTLE_18 <- readRDS(file="/scratch/devel/jtrincado/SCBATLLE_22/misc/SCBATLLE_18_CD4_embedding.rds")
> #query BATTLE_22
> cat("Loading BATTLE_22...\n")
Loading BATTLE_22...
> load(file="/scratch/devel/jtrincado/SCBATLLE_22/misc/1_Seurat_analysis.obj.v2.RData")
> BATTLE_22 <- all_cells_f
> cat("FindTransferAnchors...\n")
FindTransferAnchors...
> anchors <- FindTransferAnchors(reference = BATTLE_18, query = BATTLE_22, dims = 1:30,   normalization.method = "SCT")
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
`

I'm running last development version:
`
> packageVersion("Seurat")
[1] ‘3.1.5.9008’
`

Thanks for your time and work.
Best.

Juan L.

**Comment by Diozao666** [comment]
same issue

**Comment by rahulnutron** [comment]
Hello Everyone,

This problem might occur when one or more cell names (IDs) are identical in the two integrated datasets. When I removed (just a trial) the identical named cells, its worked.
