### ISSUE TITLE
Negative value over singlet

### ISSUE THREAD

**Issue by Jimmyyun** [satijalab/seurat#2727]
Hi,
It seems I get almost 45% of negative, 45% of singlet and 10% doublet. Do people see this happening frequently? I only tested two hashing antibodies in two cell lines.
Best,
Jimmy

**Comment by satijalab** [comment]
This should not be happening. I would suggest two things

1. Create a FeatureScatter of the two HTO levels, that will tell you whether you have set your thresholds correctly in HTODemux (feel free to post here)

2. This is likely to be an experimental issue, you can explore resources at cite-seq.com for troubleshooting
