### ISSUE TITLE
Wilcoxon Rank-Sum test - one-sided or two-sided?

### ISSUE THREAD

**Issue by baracus37** [satijalab/seurat#2728]
Hi,

just a quick question about the statistic behind the FindAllMarkers function. We used the default test (Wilcoxon Rank-Sum test) and now for publication the journal insists on wether the statistical test are one-sided or two-sided. Could anyone help me out here? I was unable to find anything about this in the documentation.

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

The underlying wilcox test in `FindMarkers`/`FindAllMarkers` is performed by the `stats::wilcox.test` function (or `limma::rankSumTestWithCorrelation` in the current `develop` version). These are two-sided tests. The relevant code is here:
https://github.com/satijalab/seurat/blob/94343c4fdb35a3a1e7a7e14d4a0bb0cec657075c/R/differential_expression.R#L1531-L1555

For `wilcox.test` we're using default parameter settings here so `alternative = "two.sided"`.  You can read more details on the `wilcox.test` man page.
