### ISSUE TITLE
Can Seurat v3 CCA  project cells with low sequencing depth (total UMI) between scRNA datasets?

### ISSUE THREAD

**Issue by wangmeijiao** [satijalab/seurat#2729]
Hi all,

  Thanks for contributing such a good single cell analysis suite: seurat v2 and seurat v3 (with CCA projection). I recently focused on the latter CCA function, for datasets projection. And I have read through the published Seurat v3 cell paper, along with its recommended online example.  When analyzing with my real data,   I checked some unmapped clusters and found that they are not doublets (evaluate with scrublet) but cells with low sequencing depth. Here comes my question 1: what if the sequencing-depth is low in one dataset or both, the CCA projection has inherit difficulties to map them successfully?  question 2: what will you suggest to map these low sequencing depth cells ?

Many thanks!

**Comment by satijalab** [comment]
Yes, you can certainly use the anchor functionality in Seurat to integrate high-depth and low-depth datasets (for example, we've aligned SMART-Seq2 data and SPLiT-Seq data, which have dramatically different sparsities). Of course, if the UMI depth is too low, there may not be enough information to facilitate clear mapping.

One thing you can try is to use our TransferData functionality, and to treat the high-depth dataset as a reference. This will enable you to classify low-sequencing depth cells based on labels previously computed in a high-depth reference.

**Comment by unknowledgeable1** [comment]
is there a vignette on how to use the anchor functionality to cca align to
datasets that just aren't aligning well?

**Comment by wangmeijiao** [comment]
Thanks for the suggestion, that is definitely worthy  a try!
