### ISSUE TITLE
Can I use MULTIseqDemux or HTODemux on ADT data to find singlets?

### ISSUE THREAD

**Issue by jyang635** [satijalab/seurat#2730]
Hi,

Sorry if it is a stupid question. I am trying to identify singlets, doublets and negtive cells in our ADT assay. And we don't have HTO data for the sample. Can I use MULTIseqDemux or HTODemux since I think HTO and ADT are similar?

Thank you for reading this question,
Junkai

**Comment by satijalab** [comment]
Unfortunately this is not possible, these tools will only work on Cell Hashing data which individually barcodes samples, not ADT data from CITE-seq
