### ISSUE TITLE
Better workflow for Integration

### ISSUE THREAD

**Issue by Lesdormis** [satijalab/seurat#2732]
Dear Seurat Developers,

I am trying to integrate different datasets by using the Anchor method from your vignettes.
I was wondering which pre-processed workflow is better for the integration, the Standard log-normalization workflow or the SCTransform one?
After running both of these, it seems to me that the standard workflow might not perform very well if the library size of different datasets is very different?

Any suggestions would be appreciated!

Thanks!

**Comment by Lesdormis** [comment]
To make the question more clearly:
I have 4 datasets that I want to integrate together, but one of dataset's library size is extremely large compare to the others. (Please check the image below) (The left one is the extremely large one, the rest are similar the right one)
![image](https://user-images.githubusercontent.com/30546732/76798083-48640280-67a5-11ea-8ef6-d771847b06f8.png)

After trying to follow the standard log-normalization workflow, the mRNA58 completely cannot integrate with the others.
![image](https://user-images.githubusercontent.com/30546732/76798217-8c570780-67a5-11ea-8930-7796ee4c9dc3.png)

My first question is should I do vars.to.regress for the integrated dataset like this #1778? But still not working...
![image](https://user-images.githubusercontent.com/30546732/76798387-dfc95580-67a5-11ea-9935-f438d91fbfd5.png)

Or SCTransform might be a better fit in this circumstance.

Thanks!

**Comment by wangmeijiao** [comment]
Perhaps you can try to downsample the bigger one with downsampleMatrix in the DropletUtils package (https://rdrr.io/bioc/DropletUtils/man/downsampleMatrix.html)? I happened to find it was very handy to shrink (without change the distribution) a sparse matrix(like dgCMatrix) . After the downsampling, you can create your own seurat object by CreateSeuratObject. Perhaps this is worthy to have a try.

**Comment by Lesdormis** [comment]
It sounds a very good idea!
Thanks!
