### ISSUE TITLE
FindMarkers between conditions

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#2733]
Hi Seurat team,

Thank you for developing Seurat. I am running comparative analysis between two conditions and would like to identify DEGs between two clusters across these conditions (i.e. between condition A cluster 1 vs. condition B cluster 1 cells). I have a few questions and was hoping you can help me address them;

1. I used SCTransform/anchoring pipeline to correct and integrate my data. I am now running the FindMarkers command and would like to get your advice on whether it looks correct. See below for the code.

t10x_subset <- subset 
DefaultAssay(t10x_subset) <- "SCT"
t10x_subset_Der_Sub0_markers <- FindMarkers(t10x_subset, ident.1 = "0_mouse1", ident.2 = "0_mouse2", verbose = FALSE, **assay = "SCT"**, **slot = "scale.data"**, min.pct = 0.25, test.use = "wilcox", logfc.threshold = 0.25)

2. The comparative analysis is between two distinct species (i.e. mouse species) and I used the same genome/reference to map both - get pretty good coverage. In terms of fold change, is 0.25X FC standard/good practice? I was first using 1.5X FC but thought it was too stringent as I was loosing a lot of genes, so I am wondering whether I should lower to 0.25X FC/average difference instead?

3. Do you recommend using adj_p value rather than p value? 

4. Is Wilcox the best test to use for this?

Thanks for your help!

**Comment by satijalab** [comment]
The command looks OK, but I should mention that for all DE analyses and downstream interpretation, there is a general assumption that a reasonable fraction of genes do not change across conditions. In this context (comparing across species), I would expect almost the vast majority of genes to change (though the magnitude of change will of course vary).
