### ISSUE TITLE
SCTransform data integration and the order of batches

### ISSUE THREAD

**Issue by shokohirosue** [satijalab/seurat#2736]
Hi, thank you for maintaining a great tool! 
Does the order of datasets in the list affect the final result when you run SCTransform Integratedata?
(https://satijalab.org/seurat/v3.0/integration.html)

Thank you so much.

Best,
Shoko

**Comment by satijalab** [comment]
It does not. The order of integration is determined by building a similarity tree across the samples, which should be the same regardless of which order they are inputted in.
