### ISSUE TITLE
Seurat doesn't throw an error if cell names are provided as identities in findMarkers function

### ISSUE THREAD

**Issue by shashj** [satijalab/seurat#2738]
I am using cell names and passing them to ident.1 to get markers but Seurat does not throw any error, it gives legitimate results

`de_results_cells_tmp <- FindMarkers(Seurat_subset_v3, ident.1 = cells1, ident.2=cells2, test.use = "bimod")`

Could you help me understand why this might be the case?

**Comment by satijalab** [comment]
Please use the cells.1 and cells.2 arguments to pass in cell names. Unfortunately we can't perform error checking for every argument, but please feel free to reopen if using the correct argument names doesn't fix the issue
