### ISSUE TITLE
Subsetting Seurat object based on genes

### ISSUE THREAD

**Issue by Gorman222** [satijalab/seurat#274]
I know it is easy to subset a Seurat object with the SubsetData function and a character vector of cell names, but can the same thing be done with a character vector of gene names?
For instance, if I create a vector of all genes except mitochondrial genes:
non.mito.genes <- grep("^mt-", x = rownames(x = object@data), value = TRUE, invert = TRUE)
Can I use that to exclude all mitochondrial genes from my Seurat object?
Thanks

**Comment by satijalab** [comment]
I'm not sure we will include this in our workflow- we would suggest that you create a new Seurat object based on the subsetted matrix.

**Comment by Gorman222** [comment]
I assume you are referring to the dgTMatrix object.  How would I go about subsetting an object like that?
