### ISSUE TITLE
Using `ensym` to capture arguments fails with the infix `$` operator

### ISSUE THREAD

**Issue by rbpatt2019** [satijalab/seurat#2741]
Hi all,

Thanks for the great product! 

I am trying to adapt the code found [here](https://github.com/satijalab/Integration2019/blob/master/analysis_code/integration/integration_metrics.R#L36) to produce a generic silhouette function that will calculate the silhouette scores for an cluster identity and reduction. I'm pretty sure I need to use `ensym` to catch the `cluster` argument, since it needs to be evaluated as a symbol.

```r
sil.scores <- function(obj,
                       reduction = "pca",
                       dims = 30,
                       cluster = final_cluster_assignment) {
  cluster <- ensym(cluster)
  dist.matrix <- dist(x = Embeddings(object = obj[[reduction]])[, dims])
  clusters <- obj$cluster
  sil <- silhouette(x = as.numeric(x = as.factor(x = clusters)), dist = dist.matrix)
  obj$sil <- sil[, 3]

  return(obj)
}
```

This, however, fails with the error `Cannot find 'cluster' in this Seurat object`. What's confusing is this: if you have the function just return `cluster`, then one can easily see that it is of type `symbol` and captures the value of the input properly. 

Some digging suggests that this is because the infix operator `$` does not evaluate its second argument. That is: `obj$cluster` searches `obj` for `cluster`, not for `cluster`'s symbolic value. Interestingly, even trying to force the substitution with `!!` (like `obj$!!cluster` or `` `$`(obj, !!cluster)``) still fails as it now searches `obj` for the literal `!!cluster`, so it fails with the error `Invalid subscript type 'language'`.

Which bring us to the question: **How do I pass values into the function such that they can be used to retrieve data from the seurat object using the `$` operator?**

Apologies if I'm missing some super basic topic on tidy evaluation. I've only just started learning it, and can find no documentation on sym/quo/etc. with infix operators like `$`.

Thanks for the help!

**Comment by andrewwbutler** [comment]
Hi,

Assuming that you're trying to pull a column of cluster IDs out of the meta data slot of the Seurat object, I would recommend using the double bracket `[[` operator. i.e

```R
clusters <- obj[[cluster]]
```

This should work even when `cluster` is a variable and not a character string.

**Comment by rbpatt2019** [comment]
@andrewwbutler, that is what I'm trying to do - and your solution certainly works in this case! - but it's worth noting that `$`and `[[` are not equivalent. As an example I just came across: while using `caret`to create data partitions for training in various machine learning models, I encounter the following situation. `caret::createDataPartition(obj$cluster)` runs successfully, while `caret::createDataPartition(obj[['cluster']])` fails, as `[[` returns lists, not vectors, necessitating a call to `unlist`. Though this is usable workaround, it does create the situation where catching the input and evaluating symbolically would be preferred.
