### ISSUE TITLE
How to save sparse matrix as file?

### ISSUE THREAD

**Issue by vagabond12** [satijalab/seurat#2743]
We have a sparse matrix, which is so large that could not convert to dense matrix and save it.

Could anyone tell me how to save sparse matrix in R , like 10x sparse matrix?

**Comment by mxposed** [comment]
Package `Matrix` has a method `writeMM` — it will generate `.mtx` file like 10x.
You will need to save cell barcodes and genes separately

**Comment by yuhanH** [comment]
You can also use `write10xCounts()` from `library(DropletUtils)`
It was reported here: https://github.com/satijalab/seurat/issues/884

**Comment by vagabond12** [comment]
@yuhanH @mxposed  Ok. I will try, thank you!
