### ISSUE TITLE
Some problems about re-clustering

### ISSUE THREAD

**Issue by XinYu-pumch** [satijalab/seurat#2744]
Hi, Seurat team. Thanks for your work about the guideline in the vigettes. I've followed the vigettes about Multiple Dataset Integration and Label Transfer. 
However, when it comes to 're-clustering', I've got a few questions:

For example, I've got 8 PBMC samples (sample1_PBMC……sample8_PBMC), but I just concentrate on monocytes. 
**So should I pick up monocytes from PBMC first and then intergrate them**:
- first analyse (the pipeline: "FindVariableFeatures -> RunPCA -> RunTSNE -> FindNeighbors -> Findclusters") and subset monocytes in **each sample** to create 8 new objects(sample1_Mo……sample8_Mo). 

- then  "FindVariableFeatures" again in each 8 new monocyte objects

- then use the function "IntegrateData" to intergrate 8 monocyte objects

- finally run the pipeline "RunPCA -> RunTSNE -> FindNeighbors -> Findclusters" again 

**Or should I first intergrated PBMC and then pick monocytes from intergrated object and re-cluster them:**

- first intergrate 8 raw data (samplei_PBMC)

- then subset monocyte from the intergrated PBMC object to created the "intergated Monocyte object" 
- then do the pipeline "RunPCA -> RunTSNE -> FindNeighbors -> Findclusters" again on the "intergated Monocyte object"  

I think the first method is more complicated but will be more appropriate. However, my question is does the second method make sense? After all, it takes less time to analyse. 

It seems that the difference between two methods lies on the batch effect.
The first method removes the batch effect by the genes from monocytes.
The second method removes the batch effect by the genes from all cells in PBMC

**Comment by XinYu-pumch** [comment]
My question is similar with the issue #752, but this time my question lies on the **batch effect**.
If method 2 makes sense, then my problem will be fixed.

**Comment by satijalab** [comment]
Both options are allowable- method 2 does make sense (and so does method 1). We can't specifically recommend one or another - but you can perform integration on a subset of the data. When doing so, make sure to perform integration on the RNA assay (i.e. don't perform batch-correction on previously batch-corrected data)
