### ISSUE TITLE
wrong cluster # assigned for PBMC stim vs. ctrl dataset

### ISSUE THREAD

**Issue by arielyh** [satijalab/seurat#2745]
Hi Seurat Team,

I found the cluster annotation is reversed between cluster 6 and 7 for this tutorial. https://satijalab.org/seurat/v3.1/immune_alignment.html
cluster 6 should be "NK" cells and 7 should be "T activated" cells, which is consistent with the immune.combined@metadata$seurat_annotations. 
![seurat1](https://user-images.githubusercontent.com/20131500/77087798-eb04c700-69d9-11ea-9ab8-0a478f2c61f8.png)

Another small mistake is:
there is no cluster 13 at resolution = 0.5. So anything with the "Mono/Mk doublets" should be removed. For example, the following script. 
![seurat2](https://user-images.githubusercontent.com/20131500/77088020-3919ca80-69da-11ea-9853-47d79dde56ae.png)

Thank you very much.

**Comment by yuhanH** [comment]
Thanks for pointing these mistakes out!
We will fix them.

**Comment by andrewwbutler** [comment]
This is now fixed. Thanks!
