### ISSUE TITLE
Silhouette score of all cells

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#2747]
Hi,

   this is related to issue 1985 and Silhouette scores of clusters. In the provided script there, I am confused about what the columns of the _sil_ Silhouette object represent. The first column are all cells from all clusters and the third is the Silhouette scores, but what is the second one? Could you please elaborate? I want to plot the contents of this object to make a decision about how I should set the resolution parameter in `FindCLusters()`.

**Comment by satijalab** [comment]
Answered in #1985
