### ISSUE TITLE
Error installing Seurat and loading PBMC dataset for tutorial

### ISSUE THREAD

**Issue by Osterhhase** [satijalab/seurat#2749]
Hey guys,
I'm trying to install Seurat to use the tutorials with following functions:

install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('Seurat')
library(Seurat)

The following Error occurs for the last part - library(Seurat):

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘igraph’

Following from this I have problems to load the PBMC dataset due to following error:

> pbmc.data <- Read10X(data.dir = ".../Downloads/filtered_gene_bc_matrices/hg19/")
Fehler in Read10X(data.dir = ".../Downloads/filtered_gene_bc_matrices/hg19/") : 
  Function "Read10X" not found

I would really appreciate your help!!
Thanks a lot :)

**Comment by timoast** [comment]
Try installing the igraph package: `install.packages("igraph")`

**Comment by Osterhhase** [comment]
Hi timoast,
thank you a lot for your quick answer! :)

I followed your advice and installed igraph. Unfortunately following error occurred:

ERROR: compilation failed for package ‘igraph’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status

The downloaded source packages are in
‘/private/var/folders/lw/zpnnptf933z40_3f31v_fnb40000gn/T/RtmpGNAmb6/downloaded_packages’

I still tried the first function again, but the Error remained:

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘igraph’


Do you have any idea what the problem could be? 
Thank you a lot!! :)

**Comment by timoast** [comment]
This looks like an issue with igraph installation, I suggest you raise an issue with the igraph developers and they should be able to help you out: https://github.com/igraph/rigraph

**Comment by Osterhhase** [comment]
Perfect, thanks a lot for your help!

**Comment by TongtongWang0908** [comment]
Hi,

I just met the same problem as you. Could you please share how did you fix that?

Thanks a lot!
