### ISSUE TITLE
Visualizing coexpression of two genes 

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#275]
Hi,

This feature has proven really useful to me - thanks for including it!

Would you please expand on how the discrete "high" and "low" expression cutoffs are calculated? 
Also, is there an option to render a more detailed figure legend to include the cutoff values too, other than just "high in gene 1", "high in gene 2", "both high"? 
Thank you in advance!

**Comment by mojaveazure** [comment]
High and low cutoffs are, by default, the minimum and maximum expression values for each feature. You can specify these as arguments, either as values or quantiles in the form of `q#` (eg. `q3` for the third quantile); if these are specified, any values below the minimum or above the maximum get masked so they classify as "low" or "high", respectively. Classifying cells as "low" or "high" is done using the [`cut`](https://www.r-bloggers.com/r-function-of-the-day-cut-2/) function. If you'd like to take a look, see the BlendPlot function starting on [line 271 of `plotting_internal.R`](https://github.com/satijalab/seurat/blob/master/R/plotting_internal.R#L271).

As for a more detailed figure legend, we currently do not offer that as an option, but it's a good idea! If you'd like to tackle it, please feel free to get it working and submit a pull request with the feature!
