### ISSUE TITLE
Doublets not present when using sctransform but present in standard seurat workflow

### ISSUE THREAD

**Issue by iSinedeus** [satijalab/seurat#2750]
Hi,

I have recently switched to using the sctransform workflow instead of the standard workflow and I have noticed that populations that appear to be doublets (for example CD3+ and CD14+) are present in the standard workflow but I am not able to see them when using sctransform.

<img width="949" alt="19F25a markers" src="https://user-images.githubusercontent.com/62082838/77197079-c2e09b00-6aa1-11ea-86df-436d448cd783.PNG">
![19F25a markers sctransform](https://user-images.githubusercontent.com/62082838/77197091-c6742200-6aa1-11ea-93e6-606cdf8376f2.PNG)

You can see in the vlnplots from the standard workflow that there appears to be some doublets present in cluster 4 but when I process that same sample using sctransform I don't see a population that seems to match this. I was wondering what happened to this population of cells that I am not seeing it when using sctranform?

Thank you

**Comment by iSinedeus** [comment]
I'm sorry it appears my sctransform vlnplot did not load. Here it is:


![19F25a markers sctransform](https://user-images.githubusercontent.com/62082838/77197245-16eb7f80-6aa2-11ea-8744-7abc6ddafb03.PNG)

**Comment by denvercal1234GitHub** [comment]
Hi @iSinedeus - How did you resolve the potential issue of those cells being doublets? Did you use any packages or functions like DoubletFinder to ensure they were in fact doublets and how did you go about removing them computationally?
