### ISSUE TITLE
Some dots in dotplot are white when using split.by function

### ISSUE THREAD

**Issue by drmofjv** [satijalab/seurat#2752]
Hello,

I was trying to make a dotplot with the split.by function. However, when I do this some of the dots turn out to be white and therefore unvisible in the plot, while this does not happen when I don't use the split.by function. Is there a way to avoid this from happening? 
The code I used is: DotPlot(seurat_control_filt, features = rev(markers.to.plot.c), dot.scale = 4, split.by = "Age", cols = c("#5681c9", "#de6f96")) + RotatedAxis() 
And it came out looking like this:

![Dotplot_markers_control_split_b-1](https://user-images.githubusercontent.com/61495603/77235735-99fef980-6bb8-11ea-9184-8d0972f91e97.jpg)

So for example the last dots for the WBC and also some of the Sc dots are white...

Thank you very much in advance!

**Comment by timoast** [comment]
I think this is due to the custom color scale you've provided. If you choose a different color scale you shouldn't have this issue

**Comment by drmofjv** [comment]
> I think this is due to the custom color scale you've provided. If you choose a different color scale you shouldn't have this issue

Unfortunately I have the same problem when I just use the default colors... So I don't think my color scale is the problem...

**Comment by svaidy88** [comment]
@drmofjv - I have the same issue. I am curious if you figured out a solution?
