### ISSUE TITLE
PBMC vignette error with call to LabelPoints()

### ISSUE THREAD

**Issue by mheskett** [satijalab/seurat#2754]
Following the pbmc3k tutorial v3.1 line for line, running 
```plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)```
gives error: 

```Error in `[[.Seurat`(x, i, drop = TRUE) : 
  Cannot find 'layers' in this Seurat object```

**Comment by andrewwbutler** [comment]
Hi, 

Are you running the tutorial with the pbmc3k data or your own data? Could you also provide the output of `sessionInfo`? Thanks!

**Comment by goutamjnu** [comment]
Hi, I am having the same issue. I am running the tutorial with NSCLC data from the 10x platform. Can you pls tell me how can I solve this? Thanks.
I am attaching the screenshot of the session info. 

<img width="944" alt="Screenshot 2022-05-02 at 13 05 30" src="https://user-images.githubusercontent.com/104765344/166224509-61f2cecc-ffb8-482a-af59-ac7928cb77d5.png">

**Comment by Tjorbenn** [comment]
I'm having the same issue with the provided pbmc3k data.
