### ISSUE TITLE
GetTransferPredictions: object slide.seq not found.

### ISSUE THREAD

**Issue by lima1** [satijalab/seurat#2755]
Hi,

in the new GetTransferPredictions function (in the spatial branch),  "slide.seq" needs to be replaced with "object".
  
dat <- GetAssayData(slide.seq[[assay]], slot = slot)

There is also a typo in the manpage resulting in a warning.

Cheers,
Markus

**Comment by andrewwbutler** [comment]
Hi Markus,

This should be fixed now on the `spatial` branch.
