### ISSUE TITLE
Adding zebrafish mitochondria data to the metadata

### ISSUE THREAD

**Issue by SlearnsR** [satijalab/seurat#2756]
Hello,

I am very new to R and I am analysing my first ever 10x dataset from zebrafish using Seurat. I managed to extract the list of mitochondrial genes using the reference genome using,
mt.list = rownames(ref)[grep("MT",ref$Exons)]

But when I try to add this list to my meta.data, it gives me an error,

scRNAseq[["percent.mt"]]=PercentageFeatureSet(scRNAseq, features = mt.list)

Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

When I try replacing "features" with "pattern", it says mitochondrial genes as zero.

Any feedback or suggestions will be greatly appreciated.  Thank you!!

**Comment by andrewwbutler** [comment]
Hi,

Can you confirm that the features you are passing as `mt.list` are actually present in the Seurat object?

```R
mt.list[!mt.list %in% rownames(scRNAseq)]
``` 
This will give you a vector of any genes that are in `mt.list` that aren't in your `scRNAseq` Seurat object. 

If you want to work with the `pattern` parameter instead, you need to pass the pattern you're trying to match against the gene names ("MT"), not the feature list. I'm not that familiar with zebrafish gene names but I would just note though, that just matching against "MT" has the possibility of matching non-mitochondrial genes so you want to be careful with your regex patterns if that's a concern here. Also relevant are the capitalization conventions.

**Comment by SlearnsR** [comment]
Hi Andrew,

Thanks for your response. You're right that mt.list gives me a vector of genes that are not a part of the Seurat object since  I was trying to extract this list from the reference. But then I realized that I could just use,

scRNAseq[["percent.mt"]] <- PercentageFeatureSet(scRNAseq, pattern = "^mt-").

"mt-" is how the mitochondrial genes are denoted in my features.tsv files. Now I get a column with the percent.mt in my metadata. 

Thank you,
Sobhika
