### ISSUE TITLE
combining multiple atacseq

### ISSUE THREAD

**Issue by rojinsafavi** [satijalab/seurat#2757]
I have 5 atacseq that I would like to combine into 1 Seurat object, and then use the combined one for ATAC +RNA integration. Is this the right way of combining the atacs? because at the end of the day I get NA assigned to atacseq instead of cell type.

```
m = merge(one, 
          c(two, 
          three, 
          four, 
          five))
```

**Comment by timoast** [comment]
Please see the scATAC-seq merge vignette here: https://satijalab.org/signac/articles/merging.html
