### ISSUE TITLE
Checking normalization in Seurat

### ISSUE THREAD

**Issue by rmondragon90** [satijalab/seurat#2758]
Hi, I am analyzing a public available dataset. The file was .txt and importing it to Seurat and doing the quality control step, I noticed that the data is already filtered (by nFeature and percent.mt). Because of this, I am unsure whether the data is normalized already. What would you recommend to visualize whether a data set has undergone normalization?

**Comment by timoast** [comment]
You should check the source of the data, they should document somewhere what processing has been done. If the data are integer counts, then it's not normalized.
