### ISSUE TITLE
Trouble with '_' character in features

### ISSUE THREAD

**Issue by Themostene** [satijalab/seurat#2759]
Hello, 
I am trying to subset a Seurat object in Seurat V3.1 and I always get the same error message  about underscore being replaced, and then that the features are not recognized (although they are on the same Seurat version in R studio; 
I tried to put backticks, change the name of the variable to 'nCount-RNA' and other answers I found online to no avail. This is running in a conda environment in a linux machine, and work fine in Rstudio...
is there a way to fix this?
 Thanks 
T 

`FFseurat <- Read10X(data.dir="scratch60/RNA17032020/MS1205FF_final/MS1205FF/filtered_feature_bc_matrix")
> FFseurat <- CreateSeuratObject(counts = FFseurat, project = "VCStroke",min.features = 200, min.cells = 3 )
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
> mitoFF <- PercentageFeatureSet(FFseurat, pattern = '^Mt-')
> FFseurat <- subset(FFseurat, subset = FFseurat@meta.data[["nCount_RNA"]] > 500 &  mitoFF < 5)
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells,  : 
  None of the requested variables were found: 
`

**Comment by timoast** [comment]
Try:

```r
FFseurat[['percent.mt']] <- PercentageFeatureSet(FFseurat, pattern = '^Mt-')
cells <- (FFseurat$nCount_RNA > 500) & (FFseurat$percent.mt < 5)
FFseurat <- FFseurat[, cells]
```
