### ISSUE TITLE
Changing the default value of pseudocount.use in FindMarkers()

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#276]
Hi, I'm confused by the default value of `pseudocount.use = 1` in FindMarkers(). 

I often set `logfc.threshold = log(2)` to find genes that are differentially expressed at least 2-fold. However, I constantly run into situations where the calculated `avg_logFC` is much smaller than what I expected, which leads to some marker genes being filtered out. I think this is because the default value of `pseudocount.use = 1`. 

From the documentation, the `logfc.threshold` parameter is explained as follows: 

> Limit testing to genes which show, on average, at least X-fold difference (log-scale) between the two groups of cells.

My understanding is that, for a given gene and two groups of cells, if the average count of the cells are `count.1 / count.2 = 2`, then the log fold change should be `log(2) = 0.693`, regardless of the exact values of count.1 and count.2.
```R
logfc = log(count.1) - log(count.2)= log(count.1/count.2)  = log(2) = 0.693. 
```

However, looking at the source code: 
```R
data.1 <- apply(X = data.use[genes.use, cells.1, drop = F], MARGIN = 1, 
        FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))
data.2 <- apply(X = data.use[genes.use, cells.2, drop = F], MARGIN = 1, 
        FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))
total.diff <- (data.1 - data.2)
```
With `pseudocount.use = 1` as default, the formula becomes:

```R
logfc = log(count.1 + 1) - log(count.2 + 1)= log[(count.1+1)/(count.2+1)]
```
This makes `logfc` much smaller than log(2) even though `count.1 / count.2 = 2`. This effect is strong especially when count.1 and count.2 are small (e.g. when pct.1 and pct.2 are small).

For example, if the average counts are `count.1 = 0.4, count.2 = 0.2`, `pseudocount.use = 1` gives `logfc = 0.154`, much smaller than log(2) = 0.693. If we set `pseudocount.use = 0.001`, the result `logfc = 0.691` is a much better approximation of the actual log fold change of log(2). 

Even if we set `count.1 = 1.2`, which is a 6 fold change compare to `count.2`, `pseudocount.use = 1` gives `logfc = 0.606`, still smaller than log(2) = 0.693. Setting `pseudocount.use = 0.001` gives `logfc = 1.787`, similar to `log(6) = 1.792`.

So I would suggest changing the default value of `pseudocount.use` to a much smaller value like 0.001 (to avoid zero-division error). I don't quite understand the purpose of adding a large pseudocount when calculating log fold change. 

Thanks! 
Yueqi

**Comment by satijalab** [comment]
Thanks again - we chose this pseudocount value to be conservative, this ensures that extremely lowly expressed genes (i.e. expression in clusterA/clusterB is 0.000001/0.000) do not dominate the DE results. By making this a user-defined parameter, we allow you to change this to the value of your choice.

best,
Rahul
