### ISSUE TITLE
cannot reproduce same UMAP embedding with different version Seurat

### ISSUE THREAD

**Issue by Lobbii** [satijalab/seurat#2760]
I updated Seurat from 3.1.0 to 3.1.4 and some CRAN packages, then I cannot reproduce same embedding as previous one. What cause this issue?

**Comment by KinSimon96** [comment]
If you have not modified PCA/UMAP PC's, RNA counts filtering, resolution, variable features number, then it may come from intern preprocessing changes. Seurat beeing in constant evolution, it can only gives more accurate results. 

If you really want to keep your previous umap, install manually an older version of Seurat, i guess this is still available online.

Couldn't help a lot but i only see this as "issue".

**Comment by timoast** [comment]
If you reinstall 3.1.0 are you able to get the same UMAP as before? Are you using the same version of the UMAP package that was used in the initial analysis?

**Comment by Lobbii** [comment]
I updated uwot package as well.

**Comment by Lobbii** [comment]
> If you reinstall 3.1.0 are you able to get the same UMAP as before? Are you using the same version of the UMAP package that was used in the initial analysis?

I updated uwot package as well

**Comment by timoast** [comment]
If you reinstall 3.1.0 are you able to get the same UMAP as before?
