### ISSUE TITLE
FindVariableFeatures: Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric, : invalid 'x'

### ISSUE THREAD

**Issue by aheravi** [satijalab/seurat#2761]
I am getting the error after running the normalization step. Could you please comment on that?

>   pbmc <- NormalizeData(pbmc)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|

>   pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'

_Originally posted by @aheravi in https://github.com/satijalab/seurat/issues/2387#issuecomment-602903345_

**Comment by KinSimon96** [comment]
Hey,

What if you do it like this?

`UP <- NormalizeData(UP, normalization.method = "LogNormalize", scale.factor = 10000)`

If it is still not working, i think i won't be able to help more...

**Comment by yuhanH** [comment]
it seems that this issue is solved in https://github.com/satijalab/seurat/issues/2387#issuecomment-602903345

**Comment by kleurless** [comment]
For anyone still running into this problem, I was trying to NormalizeData and FindVariableFeatures on my integrated assay, this should have been the RNA assay.
