### ISSUE TITLE
SCTransform on a merged object

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#2763]
Hi,

For a particular project, I found that Integration will not work for us. Hence, I went with concatenating the matrices and made a seurat object with the combined matrix. I could still use SCTransform there instead of the step by step pipeline involving normalize/scale functions. Right?

Kindly advise!
Thanks in advance!

**Comment by yuhanH** [comment]
hi, 
What are those objects? Do they have strong batch effects?
If not, you can merge the counts and run SCTransform.
