### ISSUE TITLE
Cannot install Seurat V3 (R studio keeps installing Seurat V2) 

### ISSUE THREAD

**Issue by ankitaburman** [satijalab/seurat#2765]
Hi,

I have been trying to install Seurat Version 3 (current version) by following the instructions on the Satija website which are:

Enter commands in R (or R studio, if installed)
install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('Seurat')
library(Seurat)

However, no matter what I try, on entering the command install.packages('Seurat'), it keeps installing the old version of Seurat - Seurat 2.3.4. I tried restarting r studio, uninstalling the seurat package and reinstalling but nothing worked. Can you please help me in installing version 3 of seurat?

Following is the output that I am getting:

**> install.packages('BiocManager')
Installing package into ‘C:/Users/burmana/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2019-04-15/bin/windows/contrib/3.5/BiocManager_1.30.4.zip'
Content type 'application/zip' length 291596 bytes (284 KB)
downloaded 284 KB

package ‘BiocManager’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\burmana\AppData\Local\Temp\RtmpYRJYup\downloaded_packages
> BiocManager::install('multtest')
Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.3 (2019-03-11)
Installing package(s) 'multtest'
trying URL 'https://bioconductor.org/packages/3.8/bioc/bin/windows/contrib/3.5/multtest_2.38.0.zip'
Content type 'application/zip' length 953091 bytes (930 KB)
downloaded 930 KB

package ‘multtest’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\burmana\AppData\Local\Temp\RtmpYRJYup\downloaded_packages
installation path not writeable, unable to update packages: boot, checkpoint, cluster, curl, doParallel, foreign, iterators, jsonlite, KernSmooth,
  lattice, MASS, Matrix, mgcv, nlme, nnet, R6, RODBC, rpart, RUnit, survival
Update old packages: 'BiocManager'
Update all/some/none? [a/s/n]: 
n
> install.packages('Seurat')
Installing package into ‘C:/Users/burmana/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2019-04-15/bin/windows/contrib/3.5/Seurat_2.3.4.zip'
Content type 'application/zip' length 2047582 bytes (2.0 MB)
downloaded 2.0 MB

package ‘Seurat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\burmana\AppData\Local\Temp\RtmpYRJYup\downloaded_packages**

When it asks me whether I want to update all/some/none (after the BioManager command), even if I say 'a' instead of 'n', I run into the same problem - it still installs the old version of Seurat. 

Thank you so much for your help,
Ankita

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can be helpful!  It appears you have microsoft's mran repository snapshot with date of 4/15/2019 set as your repository to install packages instead of CRAN.  In RStudio you can change this back to CRAN through: Preferences > Packages > Primary CRAN Repository and removing the mran snapshot from secondary repositories unless you have specific reason to need package from that date.

Alternatively if you need to keep that mran snapshot but only want Seurat update you can run:
`install.packages("Seurat", repos = "https://cloud.r-project.org")` to install directly from CRAN repo.

Best,
Sam

**Comment by ankitaburman** [comment]
Hello Sam, 

Thank you so much for your help!

Best,
Ankita
