### ISSUE TITLE
error merging multiple seurat objects 

### ISSUE THREAD

**Issue by amunzur** [satijalab/seurat#2766]
Hi, 

I am trying to merge multiple seurat objects. I tried both: 

`merged <- merge(object1, y = list(object2, object3), add.cell.ids = c('one', 'two', 'three'))`

`merged <- merge(object1, y = c(object2, object3), add.cell.ids = c('one', 'two', 'three'))`

I keep getting this error: 
`Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class 'structure("Seurat", package = "Seurat")' to a data.frame`

I am using Seurat 3.0.1

**Comment by andrewwbutler** [comment]
Hi, 

The code here looks correct - so we'd like to check this out in more detail. Can you either attach the objects or e-mail a dropbox download link to seuratpackage@gmail.com? If possible, try to reproduce the error on downsampled objects so it will be a bit easier to share.

**Comment by andrewwbutler** [comment]
Hi,

Thanks for sending the file.  I wasn't able to reproduce the issue on this data using either the most current Seurat version or v3.0.1. 
```R
sl <- readRDS("seuratList.rds")
object1 <- sl[[1]]
object2 <- sl[[2]]
object3 <- sl[[3]]
merged <- merge(object1, y = list(object2, object3), add.cell.ids = c('one', 'two', 'three'))
```

One other thing you could check is that all the objects (`object1`, `object2`, `object3`) are actually Seurat objects and not something else like a data.frame. E.g.

```R
inherits(x = object1, what = "Seurat")
```
