### ISSUE TITLE
FindIntegrationAnchors Error

### ISSUE THREAD

**Issue by jad362** [satijalab/seurat#2767]
Hi- I'm attempting to integrate two datasets together and am running into this error in FindIntegrationAnchors:
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
Calls: FindIntegrationAnchors ... RenameCells.Seurat -> RenameCells -> RenameCells.Assay
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

This is after running SelectIntegrationFeatures and PrepSCTIntegration. This is exactly the error from issue #1785 but their issue was resolved after clearing the environment, whereas mine isn't. I'm pretty sure it has to do with the fact that the cell barcodes in the objects are not unique but Renaming them to make them unique is failing and I'm not sure why.

Thanks for the help!

**Comment by jad362** [comment]
Please disregard my incompetence- I messed up something earlier on which led to this error, it now works

**Comment by rojinsafavi** [comment]
@jad362 did you figure out what the issue was? I am getting the same error

**Comment by jad362** [comment]
Make sure when you run FindIntegrationAnchors that you reference the IntegrationFeatures you found in the previous step in the parameter anchor.features. Not sure why this fixed my error but it wasn't shown in the vignettes. Once I put in the parameter, it worked with my data.
