### ISSUE TITLE
ProjectPCA doesn't update JackStraw p-values

### ISSUE THREAD

**Issue by gokceneraslan** [satijalab/seurat#277]
I observe that after I run ProjectPCA, `seurat_object@dr$pca@jackstraw@emperical.p.value.full` is still an empty matrix:

```r
ps <- RunPCA(pbmc_small)
ps <- JackStraw(ps, num.pc = 3, prop.freq = 0.5)
ps@dr$pca@jackstraw@emperical.p.value.full

#     [,1]
#[1,]   NA

ps <- ProjectPCA(ps)
ps@dr$pca@jackstraw@emperical.p.value.full

#     [,1]
#[1,]   NA

```

@leonfodoulian also mentioned this in https://github.com/satijalab/seurat/issues/109#issuecomment-319507026.

**Comment by gokceneraslan** [comment]
It's gone during the upgrade from v1.4 to v2.0 I guess.

**Comment by satijalab** [comment]
Thanks, this is a bug. We'll fix in an upcoming release. Note that we may make the p-value projection optional, as it can be quite slow.

**Comment by markymarcii** [comment]
Hello All,

I am also experiencing this issue. I have tried using two version of the toolkit (V2.3.4 and develop), however, this issue still persists. Please advise on how to proceed.

**Comment by elo073** [comment]
I have the same problem with V2.3.4. Is it fixed on the development version? Then I'll try that one.
