### ISSUE TITLE
Error in library (Seurat)

### ISSUE THREAD

**Issue by TongtongWang0908** [satijalab/seurat#2770]
Hello,

I basically followed what the Satija lab suggests to insall R, Rtudio and Seurat.

Here are the codes:

**install.packages('BiocManager')**
I got a warning to install Rtools, and I successfully installed it.

**BiocManager::install('multtest')** 
**install.packages('Seurat')**
"The downloaded source packages are in 'C:Users\..\..\.downloaded_packages' "

**library(Seurat)**
Error:  package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
There is no package called 'igraph'

I searched online but am still pretty confused. Could someone please help me?

**Comment by TongtongWang0908** [comment]
I tried to install "igraph", which looks successful.
**install. packages("igraph")**
"The downloaded source packages are in 'C:Users.....downloaded_packages' "

But I didn't see it in the library.

**Comment by timoast** [comment]
Are you sure that igraph installed sucessfully? What happens if you run `library(igraph)`?

You can also try restarting your R session and clearing your environment.

**Comment by KinSimon96** [comment]
I had the same problem months ago when installing Seurat.

The only solution i had found was to open R studio as administrator, going to "package" slot, install, writing "igraph" and download it in the second R library `C:/Program Files/R/R-3.6.2/library` (non available if you run R studio as normal).

Once installed, manually go to this repertory, copy the igraph folder and paste it to your first R library (mine is `C:/Users/Simon/Documents/R/win-library/3.6`)

Running back `library(igraph)` should work now.

**Comment by TongtongWang0908** [comment]
Thanks a lot, KinSimon96! I solved this problem by using the same method as yours. It seems "igraph" package somehow couldn't be auto installed.

**Comment by Dragonmasterx87** [comment]
A more appropriate solution is to install the binary:

`install.packages("igraph", type="binary")`

This will install a precompiled binary of igraph.

🐲
