### ISSUE TITLE
Gene of Interest Present in Original Matrix but Not Seurat Object

### ISSUE THREAD

**Issue by Maura-Schwartz** [satijalab/seurat#2771]
I have looked through the issues and have so far not found one similar to mine. I am using Seurat to analyze single cell RNA sequencing data and identifying expression levels of my GOIs after PCA of the Seurat object. There are two genes in my data that are "not found" when I want to visualize with any of the numerous methods (e.g. violin plot). At first I thought there must be a step in the initial process where I am filtering them out and tried relaxing all of the cutoffs to no avail.

I wrote the code below to see if my genes were present in the original matrix, and they were. It seems that when I make the Seurat object from this matrix, they dissapear. I have tried everything to resolve this, although it could be an easy solution (amateur coder). How do I make sure my genes of interest are included in the Seurat object?

n.cells.per.gene<- Matrix::rowSums(x = data > 0)
as.data.frame(n.cells.per.gene)
write.csv(n.cells.per.gene, "C:\\.csv", row.names = TRUE) 

Thank you for the help in advance!

**Comment by timoast** [comment]
Hi, the `min.cells` parameter in `CreateSeuratObject` will determine if the feature is included in the object. By default, this is set to 0 so that no filtering is performed. If you didn't change that parameter, the genes will be present in the object. If the gene name contained an underscore ("_"), this will be replaced with a dash ("-"), which may be the reason you're not finding them.

**Comment by Maura-Schwartz** [comment]
> Hi, the `min.cells` parameter in `CreateSeuratObject` will determine if the feature is included in the object. By default, this is set to 0 so that no filtering is performed. If you didn't change that parameter, the genes will be present in the object. If the gene name contained an underscore ("_"), this will be replaced with a dash ("-"), which may be the reason you're not finding them.

Hi Tim, 

Thank you for your response! Unfortunately, I haven't changed the min.cells parameter from 0 and there is no underscore present in any of the gene names. Any other ideas?

**Comment by timoast** [comment]
Are you able to provide a reproducible example where a gene present in the input matrix is not present in the Seurat object?

**Comment by Maura-Schwartz** [comment]
Hi Tim,

Am replying in email to preserve the confidentiality of my data before publishing publicly.

Attached I have the count matrix "scRNA Macaque RNA Cell Counts" before loading into the Seurat object which has all four of my genes of interest: "CLN3", "CLN6", "CLN8", "eGFP".

Next is the list of features "Seurat Object Features" that was pulled from the Seurat object with min.cells = 0. Present in this list is "CLN6", "CLN8", and "eGFP".

Finally, a screenshot of the error codes that are presented when I try to visualize gene expression of "CLN3" or "eGFP" within my clusters.

I am not understanding why CLN3 completely disappears after making the Seurat object. In addition, eGFP is present in both lists which means I might have to print out the features list after every filtering step to figure out where it is going missing and adjust accordingly?

Thankful for any guidance you can provide! I am desperate!

Best,
Maura Schwartz



[The Ohio State University]
Maura K. Schwartz
PhD Candidate
College of Medicine - Biomedical Sciences Graduate Program

Meyer Lab - Gene Therapy Center

The Research Institute at Nationwide Children's Hospital

700 Children's Dr, Columbus, OH 43205 (WA2109)

schwartz.2009@osu.edu<mailto:schwartz.2009@osu.edu>

________________________________

**Comment by Maura-Schwartz** [comment]
Actually as a follow up. It does print EGFP. I had the "e" lowercased on accident. But it says the expression is 0 in all clusters for GFP despite there being at least 3,251 cells expressing GFP.


[The Ohio State University]
Maura K. Schwartz
PhD Candidate
College of Medicine - Biomedical Sciences Graduate Program

Meyer Lab - Gene Therapy Center

The Research Institute at Nationwide Children's Hospital

700 Children's Dr, Columbus, OH 43205 (WA2109)

schwartz.2009@osu.edu<mailto:schwartz.2009@osu.edu>

________________________________

**Comment by timoast** [comment]
Hi Maura, you can't send attachments via the github email, can you send to tstuart@nygenome.org instead and include the code you're running?

**Comment by vinothkr11** [comment]
I am having a similar problem. How did you manage to solve the issue?
