### ISSUE TITLE
FindTransferAnchors:  length of 'dimnames' [1] not equal to array extent 

### ISSUE THREAD

**Issue by sn-GT** [satijalab/seurat#2773]
`anchors <- FindTransferAnchors(reference = allen, query = cortex, normalization.method = "SCT")`
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

I am not sure if this is the cause if this error, but the column names of my allen object have "_" in it, so I thought may be that is causing this error:
`colnames(allen)[1:3]
[1] "P1TLH_AAACCTGAGCAGCCTC_1" "P1TLH_AAACCTGTCCTCATTA_1" "P1TLH_AAACCTGTCTAAGCCA_1"`

So, I tried to rename the cells of my seurat object to replace the underscore with dashes, however I still get the same error: 
`new <- gsub("_", "-", colnames(allen))
RenameCells(allen, new.names = new)`
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

My gene names do not have underscore but "." in them:
`rownames(allen)[1:5]
[1] "RP11-34P13.7"  "FO538757.2"    "AP006222.2"    "RP4-669L17.10" "RP11-206L10.9"`

Please let me know how can I resolve this issue.

Thanks

**Comment by timoast** [comment]
Can you post the full code that you're running?

**Comment by Nh-Zhu** [comment]
It seems that the dims of the matrix inside the assays is different.
You should check out their respectly, and then trying  run ``` NormalizeData() %>% ScaleData()```again to fix the error.

**Comment by Nh-code** [comment]
It seems that the dims of the matrix inside the assays is different.
You should check out their respectly, and then trying run NormalizeData() %>% ScaleData()again to fix the error.

**Comment by Nh-code** [comment]
It seems that the dims of the matrix inside the assays is different.
You should check out their respectly, and then trying run ```NormalizeData() %>% ScaleData()``` again to fix the error.
