### ISSUE TITLE
Anyone used for unmodified HTO primers vs. modified HTO primers?

### ISSUE THREAD

**Issue by Jimmyyun** [satijalab/seurat#2775]
Hi 
I was following the old cell hashing protocol, which was without phosphorothioate modification in HTO cDNA PCR additive primer, SI-PCR primer, and TruSeq D701_s primer. However, it seems now all three primers use the phosphorothioate modification. I understand the purpose of using that modification that is for inhibiting nuclease degradation. 
Has anyone seen the difference in the Cell Hashing case? Does it make a difference enough to get much better quality data? 
Best

**Comment by timoast** [comment]
Hi, I think this question would be better directed to the CITE-seq developers: https://cite-seq.com/
