### ISSUE TITLE
MixingMetric documentation

### ISSUE THREAD

**Issue by DanSchnell** [satijalab/seurat#2776]
This comment is related to previously closed issue, "Interpretation of MixingMetric output #2650"

The text in the Value section of the MixingMetric documentation seems inconsistent with the Description--see below.

r\value{
Returns a vector of values representing the entropy metric from each
bootstrapped iteration.
}
\description{
Here we compute a measure of how well mixed a composite dataset is. To
compute, we first examine the local neighborhood for each cell (looking at
max.k neighbors) and determine for each group (could be the dataset after
integration) the k nearest neighbor and what rank that neighbor was in the
overall neighborhood. We then take the median across all groups as the mixing
metric per cell.
}

**Comment by andrewwbutler** [comment]
Hi, thanks for bringing this up. The return text was incorrect but has now been updated on the `develop` branch to reflect what is described in the description field.
