### ISSUE TITLE
Differential gene expression

### ISSUE THREAD

**Issue by odagliyan** [satijalab/seurat#2777]
I am trying to do differential gene expression using the data that consists of multiple stimulation conditions from multiple technologies (10x and indrop). When I used your integration algorithm, it uses nFeature=2000 so the resulting integrated data has 2000 x all cells matrix. Then how can I perform differential gene expression for all the genes using the integrated matrix? Should I integrate in a different way or should I use the original merged (unintegrated) matrix for differential gene expression data analysis? If so, how do I do the normalization then?
thanks so much for the help.

**Comment by yuhanH** [comment]
Hi, 
when you do the differential analysis, you should use the RNA or SCT assay instead of integrated assay.  You can check the IFNB simulated pbmc vignette to learn more of differential analysis 
https://satijalab.org/seurat/v3.1/immune_alignment.html]
