### ISSUE TITLE
Variable features post-intergration of SCT data

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#2778]
Following integration of SCT datasets, I ran VariableFeaturePlot() and got the following error:

`Error: Please run either 'FindVariableFeatures' or 'SCTransform'`

Which should I run?

Thanks,
NM

**Comment by satijalab** [comment]
At the  moment we don't support running VariableFeaturePlot on integrated datasets,  but you  can run this function on individual datasets prior to integration
