### ISSUE TITLE
v3.1.4 IntegrateData Error in umi.assay[[v]] : subscript out of bounds

### ISSUE THREAD

**Issue by erbader** [satijalab/seurat#2779]
Hi,

I tried using v3.1.4 to re-run IntegrateData on samples I have previously integrated. I got the following error, which I haven't seen before and couldn't find any issues about:
Error in umi.assay[[v]] : subscript out of bounds
Calls: IntegrateData -> merge -> merge.Seurat

I couldn't figure out what was causing this error, maybe an internal function? I went back to v3.1.2 and IntegrateData runs as expected. Just thought I'd bring this up in case anyone else runs into the same issue. Hopefully it can be resolved in the future!

Happy to provide additional info if needed.

Elyssa

**Comment by andrewwbutler** [comment]
Hi Elyssa,

Did you recreate the objects you were trying to integrate from the raw data matrices or just reran the integration step? Could you also try running `UpdateSeuratObject` on the objects before integration to see if that resolves the issue?
