### ISSUE TITLE
Generating multiple Featureplots does not pass ggplot2 functions to all ggplot objects

### ISSUE THREAD

**Issue by RobertWhitener** [satijalab/seurat#2780]
Hi,

I'm having trouble with generating multiple FeaturePlots and passing ggplot functions to all of them.

Here is my code:

`features_to_check_feat = c('GeneC', 'GeneB', 'GeneC')`
`FeaturePlot(HANDELP, features = features_to_check, order = TRUE, pt.size = 1, ncol = 1, cols = c("gray", "red"), label = TRUE, label.size = 6, repel = FALSE, coord.fixed = TRUE, combine = FALSE)`

Correctly returns 3 ggplot2 plots.

However, if I try to eliminate the legends: 

`features_to_check_feat = c('GeneC', 'GeneB', 'GeneC')`
`FeaturePlot(HANDELP, features = features_to_check, order = TRUE, pt.size = 1, ncol = 1, cols = c("gray", "red"), label = TRUE, label.size = 6, repel = FALSE, coord.fixed = TRUE, combine = FALSE) + Nolegend()`

It returns "NULL"

and if I set combine = TRUE
`features_to_check_feat = c('GeneC', 'GeneB', 'GeneC')`
`FeaturePlot(HANDELP, features = features_to_check, order = TRUE, pt.size = 1, ncol = 1, cols = c("gray", "red"), label = TRUE, label.size = 6, repel = FALSE, coord.fixed = TRUE, combine = TRUE) + Nolegend()`

The legend is only removed from the "GeneC" plot.

Similar behavior occurs if I try to pass DarkTheme() or NoAxis() for example.

I have a large list of interesting genes that I'd like to plot, and would like to avoid generating each plot one at a time, but can do so if necessary.

Thank you!
Robert (R amateur)

**Comment by timoast** [comment]
We now use the [patchwork](https://github.com/thomasp85/patchwork) package to combine plots, which allows ggplot parameters to be easily passed to all of the plots in the combined object. For example:

```r
library(patchwork)
library(Seurat)
FeaturePlot(pbmc_small, head(rownames(pbmc_small))) & NoLegend()
```
