### ISSUE TITLE
File accessibility error - H5 file not opening with Read10X 

### ISSUE THREAD

**Issue by ankitaburman** [satijalab/seurat#2781]
Hi,

I am unable to open any H5 file with the Read10X function. The very same code with the same H5 files had worked for my colleague but is not working for me. Can you help me fix this? Thank you so much!

Note: My h5 file "YD14-1.h5" is stored in "Z:/Guanling Huang/Projects and Data/AEC2/Single cell/Raw data of 20 samples", and is loading in the files section on the right hand side in rstudio when I set the working directory; however, on using the Read10X function to open the file, I am getting the errors listed below:

> library(Seurat)
> library(tidyverse)
> library(dplyr)
> library(Matrix)
> library(ggplot2)
> library(cowplot)
> library(ggpubr)
> library(hdf5r)

> setwd("Z:/Guanling Huang/Projects and Data/AEC2/Single cell/Raw data of 20 samples")

> YD141.DATA=Read10X_h5("YD14-1.h5")
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: C:\pkg\hdf5-1.8.14\src\H5F.c in H5Fopen(): line 604: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: C:\pkg\hdf5-1.8.14\src\H5Fint.c in H5F_open(): line 990: unable to open file: time = Fri Mar 27 11:21:12 2020
, name = 'Z:\Guanling Huang\Projects and Data\AEC2\Single cell?\Raw data of 20 samples\YD14-1.h5', tent_flags = 0
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: C:\pkg\hdf5-1.8.14\src\H5FD.c in H5FD_open(): line 992: open failed
        class: HDF5
        major: Virtual File Layer
        minor: Unable to initialize object

    error #003: C:\pkg\hdf5-1.8.14\src\H5FDsec2.c in H5FD_sec2_open(): line 343: unable to open file: name = 'Z:\Guanling Huang\Projects and Data\AEC2\Single cell?\Raw data of 20 samples\YD14-1.h5', errno = 2, error message = 'No such file or directory',         class: HDF5
        m
> 

Thank you so much for your help!

Best,
Ankita

**Comment by timoast** [comment]
The error says that there's not such file at that path, are you sure that you're supplied the correct path to the file?

**Comment by ankitaburman** [comment]
Hello, 

The folder containing the h5 file in located on a server (Z drive); I am able to successfully set the working directory to the folder containing the h5 file by using 'Set working directory' in the 'Session' tab and R is able to load other csv files from this folder. However, when I try to load the h5 files, I get the error that I mentioned above. 

Commands used:

library(Seurat)
library(tidyverse)
library(dplyr)
library(Matrix)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(hdf5r)
setwd("Z:/Guanling Huang/Projects and Data/AEC2/Single cell/Raw data of 20 samples")
YD141.DATA=Read10X_h5("YD14-1.h5")

However, if I copy paste the folder containing the h5 file onto my desktop, and set the working directory to the folder now on my desktop, R is able to open the h5 file. 

Commands used:

setwd("C:/Users/burmana/Desktop/Raw data of 20 samples")
YD141.DATA=Read10X_h5("YD14-1.h5")

Most of my folders are on the server (Z drive) and I would like to be able to open my h5 files directly from the server. Since I am able to successfully set the working directory to folders in the server (Z drive) and open all other files directly from there, I am not sure why I am getting file accessibility/path error while trying to open the h5 files. Do you know of ways that I could try to fix this? Thank you so much for your help.

**Comment by timoast** [comment]
I don't know how to do it on windows but this stack exchange question might have the answer: https://superuser.com/questions/364083/windows-list-files-and-their-permissions-access-in-command-line
