### ISSUE TITLE
Pick a resolution based on clustree results

### ISSUE THREAD

**Issue by liuxl18-hku** [satijalab/seurat#2782]
Hi @mojaveazure and the team,

I currently has a data set with ~300k cells. I have done integration and use 50 PCs for UMAP and FindNeighbors(). Now I am trying to use the very cool package -- clustree to help me pick a better resolution for clustering (actually a bit over-clustering) as suggested in #1565 .

Here I tried 10 different resolutions from 1 to 10, and plotted clustree (using sc3_stability). The tree has ten layers representing res=1 to 10 from top to bottom.

To me, the number of clusters became relatively stable when resolution > 5, and I didn't see much cross until resolution = 10. My understanding would be I can pick resolution = 10 for over-clustering.

Would like to pick ur minds for better interpretation and resolution options.

[clustree_stability.pc50.pdf](https://github.com/satijalab/seurat/files/4396653/clustree_stability.pc50.pdf)

Have a good weekend and take care.

bless~

**Comment by timoast** [comment]
Hi, I think you need to ask this question in the clustree repo: https://github.com/lazappi/clustree

**Comment by liuxl18-hku** [comment]
Hi, my bad, pls delete the issue, I don't have the admin rights to do that.

bless~
