### ISSUE TITLE
Which assay should I use when calling FindConservedMarkers

### ISSUE THREAD

**Issue by RuixiangLiu01** [satijalab/seurat#2783]
Hello developer, thanks for giving a excellent tools for scRNA-seq.
Now I have 3 10X datasets,I deal these with blow steps:
1.read raw data and qc;
2.do SCTransform for each data;
3.integrate them and run pca,clustering,tsne with integrated assay;
Now, I want to find conserved markers across 3 samples and I notice that the default argument 'assay' for FindConservedMarkers is 'RNA',but my integrated object has no any data transformation about 'RNA' and will get error when I call this function while use 'MAST' method.
So,can someone explain whether I can use SCT assay to call this function or I should Call NormalizeData and ScaleData for the 'RNA' assay in integrated object and then call FindConservedMarkers. Thanks a lot!

**Comment by satijalab** [comment]
You  should  call  NormalizeData on the RNA slot, and then run MAST.
