### ISSUE TITLE
" CreateSeuratObject()" from raw data?

### ISSUE THREAD

**Issue by Baharehh** [satijalab/seurat#2785]
Hi 
I am a new user and i like to use the matrix of raw counts from the below link and load it in Seurat as a Seurat object. then i like to convert to 10x format to apply some of the upstream steps to the data. But I am not sure as a first step which one of the files in the below link I could load to R and apply it to  " CreateSeuratObject()"? where is the gene and barcode info?

I  used "readMM" to import "GSE124872_raw_counts_single_cell.mtx.gz", but the CreatSeuratObject doesn't take the input.

**GEO lin**k: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124872

**this is my code:**
matrix.path <- paste0(matrix_dir, "GSE124872_raw_counts_single_cell.mtx.gz")
mat <- readMM(file = matrix.path)
reateSeuratObject()"? stuck

Thank you for guidance
April

**Comment by liuxl18-hku** [comment]
Hi,

If you want to use `.mtx` file then you have to prepare barcode and gene info, it seems that they are absent in the GSE.

Another option is to use .RData solely, which is available there:

```bash
wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE124nnn/GSE124872/suppl/GSE124872_raw_counts_single_cell.RData.gz
gunzip GSE124872_raw_counts_single_cell.RData.gz # will give u GSE124872_raw_counts_single_cell.RData
```

```r
load("GSE124872_raw_counts_single_cell.RData") # open R at the same dir as GSE124872_raw_counts_single_cell.RData or you specify the full path of it
library(Seurat)

obj <- CreateSeuratObject(
  raw_counts,
  project = "GSE124872",
  assay = "RNA",
  min.cells = 0,
  min.features = 0
)

# > library(Seurat)
# > 
# > obj <- CreateSeuratObject(
# +   raw_counts,
# +   project = "GSE124872",
# +   assay = "RNA",
# +   min.cells = 0,
# +   min.features = 0
# + )
# Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
```

As you can see the data is loaded into `counts` slot

```r
obj@assays$RNA@counts[1:3, 1:3]
# > obj@assays$RNA@counts[1:3, 1:3]
# 3 x 3 sparse Matrix of class "dgCMatrix"
#               old_1:TTCCGTGCCCCT old_1:TTGCCCAATTAA old_1:AAGCCCAGCTAT
# 0610005C13Rik                  .                  .                  .
# 0610007N19Rik                  .                  .                  .
# 0610007P14Rik                  .                  .                  .
```

Genes are in MGI format, you can convert them into HGNC format using Ensembl BioMart.

```r
FeatureScatter(obj, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
```

![tmp](https://user-images.githubusercontent.com/42717675/78108609-531bca00-742a-11ea-921b-dea43d345425.png)

```r
VlnPlot(obj, features = c("nFeature_RNA", "nCount_RNA"), ncol = 3)
```

![tmp vln](https://user-images.githubusercontent.com/42717675/78108639-5fa02280-742a-11ea-803f-385eb5306d91.png)

Hope that helps.

bless~

**Comment by Baharehh** [comment]
thank you, this sounds great!!
my best regards
Bahareh

**Comment by wfma** [comment]
Hello! How are about able to first find the .Rdata file? I am having a similar problem but not sure how to get the link you used.
Wei
