### ISSUE TITLE
CreateSeuratObject() with just a count matrix?

### ISSUE THREAD

**Issue by GitHubbit** [satijalab/seurat#2786]
I have scRNA data, but am lacking the barcodes. I have a count matrix, with UIDs/Ensembl IDs that I mapped to gene names in Ensembl...I just have a count matrix with gene names as rows and cells as columns (50 cells total, so not your usual huge data set).

When I mapped Ensembl IDs to gene names...
(1) it did not return a gene name for every UID. What do you recommend for those Ensembl IDs that did not have a matching gene name? I am reluctant to simply drop those rows bc they weren't filtered by other QC pre-processing - they seem impt.
(2) it did return duplicate gene names for different UIDs. When I use CreateSeuratObject(), does it handle these duplicate gene cases, where I have some duplicate rows due to the same gene names corresponding to different UIDs? Is it the Read10X function, which I cannot use bc I don't have a barcodes file, that handles these cases? Essentially, does CreateSeuratObject() handle duplicate rows?

Many thanks.

**Comment by mojaveazure** [comment]
`CreateSeuratObject` requires that the input counts matrix has both row (feature) and column (cell) names. These can be any value, but must be unique across both dimensions (eg. all column names must be unique from one another and all row names must be unique from one another). If you don't have the actual cell barcodes, you can create fake names rather easily

```R
colnames(counts.matrix) <- paste0("Cell", 1:ncol(counts.matrix))
```

As for Ensembl IDs that don't match to gene names, that's up to you. There should be no duplicates and duplicate row names will cause errors in Seurat. You can choose to keep the Ensembl IDs or only keep the IDs that are duplicates or don't match. Your choice.
