### ISSUE TITLE
update seurat object

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [satijalab/seurat#2787]
Hey guys,

I am trying to update this seurat object: https://nih.figshare.com/ndownloader/files/20706645. I used the updateSeuratObject function.

First I got the following error:

Updating from v2.X to v3.XError in validObject(.Object) :invalid class “Assay” object: invalid object for slot "scale.data" in class "Assay": got class "numeric", should be or extend class "matrix"

Since the class of object@scale.data in this object is "numeric(0)", I copied and pasted object@data into object@scale.data (in this case, this is appropriate since object@data in this object has already been scaled [using scran]).

However, I got almost the same error: Updating from v2.X to v3.XError in validObject(.Object) :invalid class “Assay” object: invalid object for slot "dgcMatrix" in class "Assay": got class "numeric", should be or extend class "matrix"

The only difference is that now "dgcMatrix" matrix is not a class excepted for object@scale.data! That was really weird.

I converted the dgcMatrix to matrix, added to the object, but now a different error was happening: 'data' must be of a vector type, was 'NULL'

At this point, I don't know what to do next and would really appreciate any help.

**Comment by satijalab** [comment]
Thanks for posting this, we will take a look and get back to you  (tagging myself @satijalab)

**Comment by mojaveazure** [comment]
Hi,

The `counts` and `data` slots must be either a standard `matrix` or a `dgCMatrix` from the Matrix package. The `scale.data` slot, on the other hand, must be a standard `matrix`; furthermore, the `data` slot must be filled while the other slots can simply be empty matrices (either `new(Class = 'matrix')` or `new(Class = 'dgCMatrix')`). I would recommend that, rather than trying to move data from one slot to the other, you should simply fill any slots that should be empty (eg. the `scale.data` slot) with an empty matrix using `new`

**Comment by nasjr08** [comment]
I have a similar issue whereby I converted the object@scale.data to a matrix and the error then became : 

Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), : 'data' must be of a vector type, was 'NULL'

As far as I can tell, the counts and data are both of acceptable class dgCMatrix.

Here is what I get when I use str(object):

Formal class 'seurat' [package "Seurat"] with 20 slots
  ..@ raw.data    :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:175080321] 53 93 121 186 245 517 600 1262 1602 1722 ...
  .. .. ..@ p       : int [1:419968] 0 185 1077 1106 2779 3502 3592 3660 4732 5508 ...
  .. .. ..@ Dim     : int [1:2] 32738 419967
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:32738] "MIR1302-10" "FAM138A" "OR4F5" "RP11-34P13.7" ...
  .. .. .. ..$ : chr [1:419967] "AAACCTGAGAAACGCC_H1B1ln1" "AAACCTGAGAAGGTTT_H1B1ln1" "AAACCTGAGACCACGA_H1B1ln1" "AAACCTGAGAGATGAG_H1B1ln1" ...
  .. .. ..@ x       : num [1:175080321] 1 1 1 1 1 2 1 1 1 1 ...
  .. .. ..@ factors : list()
  ..@ data        :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:39696390] 166 210 227 255 325 326 379 442 446 464 ...
  .. .. ..@ p       : int [1:53202] 0 723 1499 2172 2767 3474 4311 4761 5461 6140 ...
  .. .. ..@ Dim     : int [1:2] 32738 53201
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:32738] "MIR1302-10" "FAM138A" "OR4F5" "RP11-34P13.7" ...
  .. .. .. ..$ : chr [1:53201] "AAACCTGAGAGCCCAA_H1B1ln1" "AAACCTGAGGCGTACA_H1B1ln1" "AAACCTGCAGGTGGAT_H1B1ln1" "AAACCTGCAGTATCTG_H1B1ln1" ...
  .. .. ..@ x       : num [1:39696390] 1.12 1.12 1.12 1.12 1.12 ...
  .. .. ..@ factors : list()
  ..@ scale.data  : num[0 , 0 ] 
  ..@ var.genes   : logi(0) 
  ..@ is.expr     : num 0
  ..@ ident       : Factor w/ 2 levels "1","2": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..- attr(*, "names")= chr [1:53201] "AAACCTGAGAGCCCAA_H1B1ln1" "AAACCTGAGGCGTACA_H1B1ln1" "AAACCTGCAGGTGGAT_H1B1ln1" "AAACCTGCAGTATCTG_H1B1ln1" ...
  ..@ meta.data   :'data.frame':	53201 obs. of  16 variables:
  .. ..$ cell_label              : chr [1:53201] "CD16++ NK" "CD8+ Naive T" "CD4+ Naive T" "CD4+ Naive T" ...
  .. ..$ orig.ident              : Factor w/ 1 level "SeuratProject": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ DEMUXLET.BARCODE        : chr [1:53201] "AAACCTGAGAGCCCAA-1" "AAACCTGAGGCGTACA-1" "AAACCTGCAGGTGGAT-1" "AAACCTGCAGTATCTG-1" ...
  .. ..$ sample                  : chr [1:53201] "256_d0" "273_d0" "256_d0" "200_d0" ...
  .. ..$ sampleid                : chr [1:53201] "256" "273" "256" "200" ...
  .. ..$ total_features_by_counts: int [1:53201] 723 776 673 595 707 837 450 700 679 790 ...
  .. ..$ nGene                   : int [1:53201] 723 776 673 595 707 837 450 700 679 790 ...
  .. ..$ nUMI                    : num [1:53201] 1567 2754 2485 1803 1678 ...
  .. ..$ p3_dist_1               : chr [1:53201] "5" "6" "0" "0" ...
  .. ..$ p3_dist_2               : chr [1:53201] "5" "6" "0" "0" ...
  .. ..$ p3_dist_3               : chr [1:53201] "4" "3" "0" "0" ...
  .. ..$ p3_dist_4               : chr [1:53201] "23" "5" "1" "1" ...
  .. ..$ K0                      : chr [1:53201] "pseudo-bulk" "pseudo-bulk" "pseudo-bulk" "pseudo-bulk" ...
  .. ..$ K1                      : chr [1:53201] "C5" "C6" "C0" "C0" ...
  .. ..$ K2                      : chr [1:53201] "C5.0" "C6.0" "C0.0" "C0.0" ...
  .. ..$ K3                      : chr [1:53201] "C5.0.0" "C6.0.0" "C0.0.0" "C0.0.0" ...
  ..@ project.name: chr "SeuratProject"
  ..@ dr          :List of 6
  .. ..$ protpca  :Formal class 'dim.reduction' [package "Seurat"] with 0 slots
 Named list()
  .. ..$ tsne_p10 :Formal class 'dim.reduction' [package "Seurat"] with 0 slots
 Named list()
  .. ..$ tsne_p50 :Formal class 'dim.reduction' [package "Seurat"] with 0 slots
 Named list()
  .. ..$ tsne_p90 :Formal class 'dim.reduction' [package "Seurat"] with 0 slots
 Named list()
  .. ..$ tsne_p130:Formal class 'dim.reduction' [package "Seurat"] with 0 slots
 Named list()
  .. ..$ tsne_p170:Formal class 'dim.reduction' [package "Seurat"] with 0 slots
 Named list()
  ..@ assay       :List of 2
  .. ..$ CITE:Formal class 'assay' [package "Seurat"] with 0 slots
 Named list()
  .. ..$ HTO :Formal class 'assay' [package "Seurat"] with 0 slots
 Named list()
  ..@ hvg.info    :'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. ..@ .Data    : list()
  .. .. ..@ names    : chr(0) 
  .. .. ..@ row.names: int(0) 
  .. .. ..@ .S3Class : chr "data.frame"
  ..@ imputed     :'data.frame':	0 obs. of  0 variables
Formal class 'data.frame' [package "methods"] with 4 slots
  .. .. ..@ .Data    : list()
  .. .. ..@ names    : chr(0) 
  .. .. ..@ row.names: int(0) 
  .. .. ..@ .S3Class : chr "data.frame"
  ..@ cell.names  : chr [1:53201] "AAACCTGAGAGCCCAA_H1B1ln1" "AAACCTGAGGCGTACA_H1B1ln1" "AAACCTGCAGGTGGAT_H1B1ln1" "AAACCTGCAGTATCTG_H1B1ln1" ...
  ..@ cluster.tree: list()
  ..@ snn         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int(0) 
  .. .. ..@ p       : int 0
  .. .. ..@ Dim     : int [1:2] 0 0
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : NULL
  .. .. ..@ x       : num(0) 
  .. .. ..@ factors : list()
  ..@ calc.params :List of 5
  .. ..$ CreateSeuratObject:List of 13
  .. .. ..$ project             : chr "SeuratProject"
  .. .. ..$ min.cells           : num 0
  .. .. ..$ min.genes           : num 0
  .. .. ..$ is.expr             : num 0
  .. .. ..$ normalization.method: NULL
  .. .. ..$ scale.factor        : num 10000
  .. .. ..$ do.scale            : logi FALSE
  .. .. ..$ do.center           : logi FALSE
  .. .. ..$ names.field         : num 1
  .. .. ..$ names.delim         : chr "_"
  .. .. ..$ display.progress    : logi TRUE
  .. .. ..$ ...                 : symbol 
  .. .. ..$ time                : POSIXct[1:1], format: "2019-11-24 00:31:43"
  .. ..$ NormalizeData     :List of 1
  .. .. ..$ normalization.method: chr "scran"
  .. ..$ ScaleData         :List of 16
  .. .. ..$ genes.use         : chr [1:87] "AnnexinV_PROT" "BTLA_PROT" "CD117_PROT" "CD123_PROT" ...
  .. .. ..$ vars.to.regress   : symbol 
  .. .. ..$ model.use         : chr "linear"
  .. .. ..$ use.umi           : logi FALSE
  .. .. ..$ do.scale          : logi TRUE
  .. .. ..$ do.center         : logi TRUE
  .. .. ..$ scale.max         : num 10
  .. .. ..$ block.size        : num 1000
  .. .. ..$ min.cells.to.block: num 3000
  .. .. ..$ display.progress  : logi FALSE
  .. .. ..$ assay.type        : chr "CITE"
  .. .. ..$ do.cpp            : logi TRUE
  .. .. ..$ check.for.norm    : logi TRUE
  .. .. ..$ do.par            : logi TRUE
  .. .. ..$ num.cores         : num 8
  .. .. ..$ time              : POSIXct[1:1], format: "2019-11-29 17:31:32"
  .. ..$ RunPCA            :List of 14
  .. .. ..$ pc.genes      : chr [1:83] "AnnexinV_PROT" "BTLA_PROT" "CD117_PROT" "CD123_PROT" ...
  .. .. ..$ pcs.compute   : num 20
  .. .. ..$ use.imputed   : logi FALSE
  .. .. ..$ rev.pca       : logi FALSE
  .. .. ..$ weight.by.var : logi TRUE
  .. .. ..$ do.print      : logi TRUE
  .. .. ..$ pcs.print     : num 0
  .. .. ..$ genes.print   : num 30
  .. .. ..$ reduction.name: chr "protpca"
  .. .. ..$ reduction.key : chr "PC"
  .. .. ..$ assay.type    : chr "CITE"
  .. .. ..$ seed.use      : num 0
  .. .. ..$ ...           : symbol 
  .. .. ..$ time          : POSIXct[1:1], format: "2019-11-29 17:31:35"
  .. ..$ RunTSNE           :List of 13
  .. .. ..$ reduction.use  : chr "protpca"
  .. .. ..$ cells.use      : NULL
  .. .. ..$ dims.use       : int [1:7] 1 2 3 4 5 6 7
  .. .. ..$ genes.use      : NULL
  .. .. ..$ seed.use       : num 0
  .. .. ..$ tsne.method    : chr "Rtsne"
  .. .. ..$ add.iter       : num 0
  .. .. ..$ dim.embed      : num 2
  .. .. ..$ distance.matrix: NULL
  .. .. ..$ reduction.name : chr "tsne_p170"
  .. .. ..$ reduction.key  : chr "tSNE_"
  .. .. ..$ ...            :length 1, mode "...": 170
  .. .. ..$ time           : POSIXct[1:1], format: "2019-11-29 18:37:29"
  ..@ kmeans      : NULL
  ..@ spatial     :Formal class 'spatial.info' [package "Seurat"] with 0 slots
 Named list()
  ..@ misc        : NULL
  ..@ version     :Classes 'package_version', 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 2 3 4
