### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by rojinsafavi** [satijalab/seurat#2788]
I have 5 ATACseq. I followed this tutorial to merge them:
https://satijalab.org/signac/articles/merging.html

my final combined data looks like this:

```combined```

```
An object of class Seurat 
550587 features across 44420 samples within 2 assays 
Active assay: peaks (114010 features, 114006 variable features)
 1 other assay present: ATAC
 2 dimensional reductions calculated: lsi, umap
```

Now I would like to do scRNA + ATACseq alignment.

for that I am following this tutorial:
[https://satijalab.org/seurat/v3.0/atacseq_integration_vignette.html](url)

But I am not sure if I am doing it right since I am not sure how to create the activity matrix from the combined Seurat object:

```
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = combined, annotation.file = "Homo_sapiens.GRCh37.82.gtf", 
    seq.levels = c(1:22, "X", "Y"), upstream = 2000, verbose = TRUE)
```

I was wondering if you could help me navigate the problem?
Thanks!

**Comment by rojinsafavi** [comment]
I also tried the following:
```
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = combined@assays$peaks@counts, 
                                            annotation.file = anno_file,
                                            seq.levels = c(1:22, "X", "Y"), upstream = 2000, verbose = TRUE)
```

```
Error in asMethod(object): Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
Traceback:

1. CreateGeneActivityMatrix(peak.matrix = combined@assays$peaks@counts, 
 .     annotation.file = anno_file, seq.levels = c(1:22, "X", "Y"), 
 .     upstream = 2000, verbose = TRUE)
2. as(object = peak.matrix, Class = "matrix")
3. asMethod(object)
```

**Comment by KinSimon96** [comment]
Hello!
How many RAM does your computer have?
`Cholmod error 'problem too large' at file...` mostly tells you that this is a memory issue.
Working with 5 combined datasets must require a (very) powerful computer. Because the code you provided seems correct.

**Comment by timoast** [comment]
@rojinsafavi if you followed the merge vignette for scATAC-seq on the Signac website (https://satijalab.org/signac/articles/merging.html) and created a merged fragment file, you can use the same methods to create a gene activity matrix as shown in the other Signac vignettes: https://satijalab.org/signac/articles/pbmc_vignette.html#create-a-gene-activity-matrix
