### ISSUE TITLE
SubsetData error with large cell numbers

### ISSUE THREAD

**Issue by gabprg** [satijalab/seurat#279]
Hello!

I wanted to report that the SubsetData function fails when trying to subset a large Seurat object. I'm not sure what the limit is, but in my case I have >100k cells, and when I try to use the function the error is:

```R
Error in complete.cases(object@scale.data) : 
  long vectors not supported yet: complete_cases.c:192
```

This is obviously not due to the Seurat code itself, so fixing it may require breaking the matrix up into smaller chunks for complete.cases to function. In the meantime, I'm just re-creating a new Seurat object and manually re-populating what I need.

Gabriela

**Comment by bio-la** [comment]
Hi, I have the same problem and I'm solving it as @gabprg , my cell.use vector is 5K, the object has  70k cells.

SubsetData(data.ob.pos, cells.use = psn)
Error in complete.cases(object@scale.data) : 
  long vectors not supported yet: complete_cases.c:192

**Comment by yaroslavbaranov** [comment]
Hi, I have the exact same problem with dataset of 55k cells as well
just after this line:
SubsetData(object, subset.name = "nGene", accept.high = 3500)

Error in complete.cases(object@scale.data) : 
  long vectors not supported yet: complete_cases.c:192

**Comment by satijalab** [comment]
We have fixed this issue in the develop branch on GitHub, and will include the fix in the next CRAN release
