### ISSUE TITLE
IntegrateData: "Error: Cannot delete the default assay"

### ISSUE THREAD

**Issue by liuxl18-hku** [satijalab/seurat#2791]
Hi all,

Does any one encounter the error: "Error: Cannot delete the default assay" when running IntegrateData. No luck when google, any hints are appreciated.

More information:
```r
# the anchor set has two objects, default assays are both 'integrated'
> DefaultAssay(sample.anchors@object.list[[1]])
[1] "integrated"
> DefaultAssay(sample.anchors@object.list[[2]])
[1] "integrated"
```

Both sets are integrated dataset, one of them are subsetted due to memory limitation.

One more information is `SelectIntegrationFeatures` only found ~160 features although it was asked to find 3000 (nfeatures = 3000).

Hope these informations help!

bless~

**Comment by timoast** [comment]
Can you provide the full code you're running? Finding only 160 features for integration suggests that you might need to first identify a larger set of variable features in each individual dataset

**Comment by liuxl18-hku** [comment]
Hi Tim @timoast ,

Thank you for your suggestion, is there anyway I can force Seurat to find more features. Before that, here is the code as you requested.

```r
sample.list <- list()
sample.list[[1]] <- integrated #  the downloaded reference dataset, integration was performed by myself
sample.list[[2]] <- readRDS(file="../integrated_singlet_pca.rds") # our own dataset, integration was performed by myself
```
`SelectIntegrationFeatures` only gave me ~160 features (with `nfeatures = 3000`)

```r
sample.features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures = 3000)
```

```r
options(future.globals.maxSize=100000000000)
sample.list <- PrepSCTIntegration(object.list = sample.list, anchor.features = sample.features, verbose = T)
sample.list <- lapply(X = sample.list, FUN = RunPCA, verbose = T, features = sample.features)
sample.anchors <- FindIntegrationAnchors(object.list = sample.list, normalization.method = "SCT", anchor.features = sample.features, verbose = T, reduction = "rpca", reference=c(1))
saveRDS(sample.anchors, file="sample.anchors.rds")
```

Then is the problematic step:
```r
integrated <- IntegrateData(anchorset = sample.anchors, normalization.method = "SCT", verbose = T)
```

bless~
Xingliang

**Comment by yuhanH** [comment]
Hi, 
I think this issue results from the assays in your objects are also called "integrated".
Try to set the new assay name for the new integrated data. 
For example,
`integrated <- IntegrateData(anchorset = sample.anchors, normalization.method = "SCT", verbose = T, new.assay.name = "INTE")`
If it does not solve the question, I will reopen it.

**Comment by liuxl18-hku** [comment]
Good catch, it works, just in case you want know. Thank you and have a good weekend.
