### ISSUE TITLE
How can do better separation of following clusters ?

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2793]
![clusters_Jon_seperation](https://user-images.githubusercontent.com/40278254/78075305-959ac380-73a4-11ea-826d-97e39e167cec.JPG)

**Comment by KinSimon96** [comment]
One solution would be to increase the resolution paramater in FindClusters() function, as that you would have more cluster and maybe a separation in what you want.

But i'd do it via this way:
1) Put your resolution as 0.000001. This will only display one general cluster.
2) Manual indentation:
xxx <- WhichCells(object = combined, expression = Krt8 > 1 & Krt7 > 1 & Krt14 > 1 & Fetub > 1)
combined <- SetIdent(object = combined, cells = xxx, value = 'Intestinal cells')

This is an example. If you wanna work with 3 renamed cluster, find very specific markers for each of them, then do the code above 3 times. At the end, you will be able to perform good differential analysis.
