### ISSUE TITLE
Hierarchical Clustering for scRNA-seq data

### ISSUE THREAD

**Issue by AlasdairCUPEI** [satijalab/seurat#2795]
Hi everyone,
I would like to perform hierarchical clustering on my single-cell data, but it appears that Seurat does not seem to have this functionality. I was wondering if anyone has any recommendations for R packages or other potential methods in R in order to create these dendrograms/heatmaps. How have people been doing hierarchical clustering?

Thank you!

**Comment by KinSimon96** [comment]
Hey,

1) You can use hclust to cluster your data, then using `SetIdent()` to place the resulting cluster IDs back into your Seurat object.
2) You can tranfer your Seurat object into a Monocle CDS (manual steps), then perform a hierarchical clustering, available in Monocle3 package.

Hope it will help!
