### ISSUE TITLE
Spatial: Understanding how image coordinates are laid on the tissue 

### ISSUE THREAD

**Issue by sn-GT** [satijalab/seurat#2796]
How can map the spot coordinates onto the tissue ? 

`head(brain@images$slice1@coordinates)`

                   tissue row col imagerow imagecol
AAACAAGTATCTCCCA-1      1  50 102     9346    10268
AAACAGTGTTCCTGGG-1      1  73  43    12437     5677
AAACATTTCCCGGATT-1      1  61  97    10830     9875
AAACCCGAACGAAATC-1      1  45 115     8674    11279
AAACCGTTCGTCCAGG-1      1  52  42     9600     5609
AAACCTAAGCAGCCGG-1      1  65  83    11367     8786

I would like to rename the cells (tissue column above) as Spot-1, Spot-2, Spot-3 ... so on and then determine where they are laid onto the tissue.  I tried to make a SpatialDimplot with cell.highlight, however, it seems that  "cols.highlight" does not highlight the cells. It assigns a grey color to all the spots on the tissue. 

`SpatialPlot(brain, cells.highlight =  c("AAACCTAAGCAGCCGG-1", "AAACCGTTCGTCCAGG-1","AAACCCGAACGAAATC-1"), facet.highlight = TRUE,cols.highlight =  c("red","black"), pt.size.factor = 2)`

Please help me understand:
1) how to map the tissue coordinates of each spot onto the tissue image
2) Cols.highlight does not color the selected cells. How to resolve it.

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

1. You can view the coordinate axes on the `SpatialPlot` if you add a different theme that includes the axes. E.g.
```R
SpatialPlot(brain) + ggplot2::theme_minimal()
```
However, what's plotted here aren't exactly the values present in the data frame you posted. Please use the `GetTissueCoordinates` get retrieve the coordinates that will be plotted. This handles some of the internal image scaling that is going on here. 

2. That seems to be a bug. Will report back here when fixed. Thanks for reporting!

**Comment by andrewwbutler** [comment]
Ok,  the `spatial` branch has now been updated with a fix that should restore the proper behavior of `cells.highlight`.

**Comment by lch14forever** [comment]
Hi

This thread is super helpful. I am curious how the transformation is done from the location of spots to the image location. So basically, if we have located a pixel (or a cluster of pixels) of interest from the image, how can I retrieve the corresponding cell from the data?

Thank you advance!
