### ISSUE TITLE
FindIntegrationAnchors gives "Error in base::crossprod(x, y) : non-conformable arguments", after merging three Seurat objects

### ISSUE THREAD

**Issue by GoBucket** [satijalab/seurat#2797]
I am following the Integration and Label Transfer vignette to analyse my own dataset of gene expression of three different species: humans, mouse and marmoset. FindIntegrationAnchors works perfectly fine when I merge humans-mouse or humans-marmoset, but after I try to merge all three to integrate, FindIntegrationAnchors gives me:
Error in base::crossprod(x, y) : non-conformable arguments

When I merge Seurat objects I follow this example:
pbmc.big <- merge(pbmc3k, y = c(pbmc4k, pbmc8k), add.cell.ids = c("3K", "4K", "8K"), project = "PBMC15K")

I don't understand what this error is referring to, and any help is appreciated.

**Comment by timoast** [comment]
Hi, are you sure that all the features you're using are present in all the objects? Can you provide the full code that you're running?

**Comment by GoBucket** [comment]
> Hi, are you sure that all the features you're using are present in all the objects? Can you provide the full code that you're running?

I just realised that in the processing of converting EnsemblID into symbols (so that it's consistent across all three objects), quite a few ID's didn't actually convert correctly and so that inconsistency made it seem as though I was missing features. Thank you for your response.
