### ISSUE TITLE
Incorrect FindClusters edge file

### ISSUE THREAD

**Issue by GWW** [satijalab/seurat#28]
Hi,

I was examining the temporary edge file Seurat outputs and noticed that the node order is incorrect.  According to the [SLM manual](http://www.ludowaltman.nl/slm/):

> For each pair of nodes, the node with the lower index is listed first, followed by the node with the higher index. The lines in an input file are sorted based on the node indices (first based on the indices in the first column, then based on the indices in the second column). 

Neither of these requirements appear to be met by Seurats output.

**Comment by andrewwbutler** [comment]
Great catch! It doesn't seem to significantly change the results of the clustering procedure but the latest version (1.4.0.5) has been fixed to reflect the proper input format. Thanks!
