### ISSUE TITLE
Modularity score

### ISSUE THREAD

**Issue by apblair** [satijalab/seurat#2800]
Hello,

Is the maximum modularity score stored in the Seurat object? Or is there a way to pipe the output log of "FindClusters" to the "misc" slot?

Thanks,
Andrew

**Comment by satijalab** [comment]
We don't currently do this but its an interesting idea, we will look into this

**Comment by andrewwbutler** [comment]
Hi Andrew,

No, unfortunately the modularity score is not stored anywhere currently. You could hack it with `capture.output` though. Something like:

```R
out <- capture.output(FindClusters(pbmc_small), type =  "output")
modularity <- as.numeric(unlist(strsplit(x = out[7], split = ":"))[2])
```

**Comment by apblair** [comment]
Thanks for the fast reply and I appreciate the code snip.
