### ISSUE TITLE
seurat fails to load after installation

### ISSUE THREAD

**Issue by Sumithrasank** [satijalab/seurat#2801]
I installed according to the instructions given in https://satijalab.org/seurat/install.html, but when I try to load the library, I get this error
>library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘sn’
Could you help me fix it. Thanks

**Comment by KinSimon96** [comment]
Open RStudio, go to "Packages", click on "install", watch for 'sn', then download it. 
Second one is to open RStudio as administrator, doing the same command but installing your package in the second library. 

Then `library(Seurat)`, hoping it will work.

**Comment by Sumithrasank** [comment]
It worked well, thanks
