### ISSUE TITLE
integrating RNA and protein analysis

### ISSUE THREAD

**Issue by xuebaliang** [satijalab/seurat#2803]
Hello, recently I ran your example of integrating RNA and protein analysis of CBMC dataset by CITE-seq. Although I followed your procedure, it also occured error. The error is:
> library(Seurat)
> library(ggplot2)
> library(patchwork)
> cbmc.rna = as.sparse(read.csv(file = "D:/singlecell/multi-modal/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv.gz", sep = ",", header = TRUE, row.names = 1))
> dim(cbmc.rna)
[1] 2873 8617
> cbmc.adt = as.sparse(read.csv(file = "D:/singlecell/multi-modal/GSE100866_CBMC_8K_13AB_10X-ADT_umi.csv.gz", sep = ",", header = TRUE, row.names = 1))
> dim(cbmc.adt)
[1]   13 8617
> cbmc.rna <- CollapseSpeciesExpressionMatrix(cbmc.rna)
> dim(cbmc.rna)
[1] 2873 8617
> cbmc.adt <- cbmc.adt[setdiff(rownames(x = cbmc.adt), c("CCR5", "CCR7", "CD10")), ]
> dim(cbmc.adt)
[1]   10 8617
> cbmc <- CreateSeuratObject(counts = cbmc.rna)
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
> cbmc <- NormalizeData(cbmc)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> cbmc <- FindVariableFeatures(cbmc)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in hvf.info$variance.expected[not.const] <- 10^fit$fitted : 
  NAs are not allowed in subscripted assignments

Can you fix this problem? Look forward to your response. Thanks!!!

**Comment by timoast** [comment]
Do you have any NA values in the matrix?

```r
sum(is.na(cbmc.rna@x))
```

**Comment by BrianLohman** [comment]
Hello,

I am having the same problem. I am using public data from UCSC

data source:
```
wget https://cells.ucsc.edu/early-brain/exprMatrix.tsv.gz
wget https://cells.ucsc.edu/early-brain/meta.tsv
```
data prep, according to UCSC: https://cellbrowser.readthedocs.io/load.html
```
mat <- fread("zcat < exprMatrix.tsv.gz")
meta <- read.table("meta.tsv", header=T, sep="\t", as.is=T, row.names=1)
genes = mat[,1][[1]]
genes = gsub(".+[|]", "", genes)
mat = data.frame(mat[,-1], row.names=genes)
so <- CreateSeuratObject(counts = mat, project = "ucsc", meta.data=meta)

# check for NAs, as suggested above
sum(is.na(so@assays$RNA@data@x))
[1] 204

# drop NAs
so@assays$RNA@data@x = na.omit(so@assays$RNA@data@x)

> so = NormalizeData(so)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> so = FindVariableFeatures(so, selection.method = "vst", nfeatures = 2000, verbose = TRUE)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in hvf.info$variance.expected[not.const] <- 10^fit$fitted : 
  NAs are not allowed in subscripted assignments

# check that NAs were dropped
sum(is.na(so@assays$RNA@data@x))
[1] 204

# check for NAs in expression matrix, prior to building Seurat object
> sum(is.na(mat))
[1] 0

```

This would suggest that the NAs are being introduced when the Seurat object is made. 

Which slot do I need to modify to get rid of the NAs? I was under the impression that it was the data slot, but that does not appear to work. 

Thanks for your help.
