### ISSUE TITLE
Installation error: there is no package called 'sn'

### ISSUE THREAD

**Issue by vho3** [satijalab/seurat#2804]
Hi, I'm trying to install Seurat but run into an error after these commands:

install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('Seurat')
library(Seurat)

Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘sn’

Please advise. I'm using Rstudio and initially had a problem with 'reticulate', but that seem to be fixed with the solution to issue #2652. Thanks in advance!

**Comment by KinSimon96** [comment]
Open RStudio, go to "Packages", click on "install", watch for 'sn', then download it.
Second one is to open RStudio as administrator, doing the same command but installing your package in the second library.

Then `library(Seurat)` , hoping it will work.

**Comment by mojaveazure** [comment]
Asked and answered in #2801
