### ISSUE TITLE
Trouble loading Seurat on MacOS Catalina

### ISSUE THREAD

**Issue by dinger8** [satijalab/seurat#2806]
I'm having trouble getting started with Seurat on my Mac. I've read posts for similar issues on Github and tried all the solutions I could find with no success, including installing Xcode.  I have also tried quitting R and reopening with a clean workspace. I've included all possible data from my session, sorry if it is overkill, I'm new to coding.  Here is what my console looks like:

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

# first I download BiocManager, seems to go ok:

> install.packages('BiocManager')
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/BiocManager_1.30.10.tgz'
Content type 'application/x-gzip' length 94951 bytes (92 KB)
==================================================
downloaded 92 KB

The downloaded binary packages are in
	/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T//Rtmphsbqpp/downloaded_packages

# Then I try to install multtest:

> BiocManager::install('multtest')
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.3 (2020-02-29)
Installing package(s) 'multtest'
trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/macosx/el-capitan/contrib/3.6/multtest_2.42.0.tgz'
Content type 'application/x-gzip' length 854810 bytes (834 KB)
==================================================
downloaded 834 KB

The downloaded binary packages are in
	/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T//Rtmphsbqpp/downloaded_packages
Old packages: 'quantreg'
Update all/some/none? [a/s/n]: 
a

  There is a binary version available but the source version is later:
         binary source needs_compilation
quantreg   5.54   5.55              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Y
installing the source package ‘quantreg’

trying URL 'https://cran.rstudio.com/src/contrib/quantreg_5.55.tar.gz'
Content type 'application/x-gzip' length 995519 bytes (972 KB)
==================================================
downloaded 972 KB

* installing *source* package ‘quantreg’ ...
** package ‘quantreg’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran  -fPIC  -Wall -g -O2  -c boot.f -o boot.o
make: gfortran: No such file or directory
make: *** [boot.o] Error 1
ERROR: compilation failed for package ‘quantreg’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/quantreg’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/quantreg’

The downloaded source packages are in
	‘/private/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T/Rtmphsbqpp/downloaded_packages’
Warning message:
In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘quantreg’ had non-zero exit status

# Since quantreg seemed to have trouble installing, I tried installing it separately:

> install.packages('quantreg')

  There is a binary version available but the source version is later:
         binary source needs_compilation
quantreg   5.54   5.55              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Y
installing the source package ‘quantreg’

trying URL 'https://cran.rstudio.com/src/contrib/quantreg_5.55.tar.gz'
Content type 'application/x-gzip' length 995519 bytes (972 KB)
==================================================
downloaded 972 KB

* installing *source* package ‘quantreg’ ...
** package ‘quantreg’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran  -fPIC  -Wall -g -O2  -c boot.f -o boot.o
make: gfortran: No such file or directory
make: *** [boot.o] Error 1
ERROR: compilation failed for package ‘quantreg’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/quantreg’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/quantreg’
Warning in install.packages :
  installation of package ‘quantreg’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T/Rtmphsbqpp/downloaded_packages’

# That didn't really seem to help, so I moved on with installing Seurat:

> install.packages('Seurat')
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/Seurat_3.1.4.tgz'
Content type 'application/x-gzip' length 3207929 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

The downloaded binary packages are in
	/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T//Rtmphsbqpp/downloaded_packages

# Then loaded Seurat Library:
> library(Seurat)

#  Then I tried to run the initial code of my RMD file for the Seurat Tutorial. It looks like this:

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
```

```{r load packages and data, include=FALSE}
library(dplyr)
library(Seurat)
library(patchwork)
```

```{r load PBMC dataset, include=FALSE}
pbmc.data <- Read10x(data.dir = ".../Desktop/saurat tutorials/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
```

# And I get this error message: 
Error in Read10x(data.dir = ".../Desktop/saurat tutorials/filtered_gene_bc_matrices/hg19/") : could not find function "Read10x" Calls: <Anonymous> ... handle -> withCallingHandlers -> with VIsible -> eval -> eval In addition: Warning messages: 1. In block_exec(params) : Failed to tidy R code in chunk 'load packages and data' .  Reason: Error in loadNamespace(name) : there is no package called 'formatR' 2: In block_exec(params) : Failed to tidy R code in chunk 'load PBMC dataset' . Reason : Error in loadNamespace(name) : there is no package called 'formatR' Execution halted.  

# the output looks like this:
  |............                                                          |  17%
  ordinary text without R code

  |.......................                                               |  33%
label: setup (with options) 
List of 1
 $ include: logi FALSE

processing file: saurat-tutorial.Rmd
  |...................................                                   |  50%
  ordinary text without R code

  |...............................................                       |  67%
label: load packages and data (with options) 
List of 1
 $ include: logi FALSE

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

  |..........................................................            |  83%
  ordinary text without R code

  |......................................................................| 100%
label: load PBMC dataset (with options) 
List of 1
 $ include: logi FALSE

Quitting from lines 26-28 (saurat-tutorial.Rmd) 
Error in Read10x(data.dir = ".../Desktop/saurat tutorials/filtered_gene_bc_matrices/hg19/") : 
  could not find function "Read10x"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
In addition: Warning messages:
1: In block_exec(params) :
  Failed to tidy R code in chunk 'load packages and data'. Reason:
Error in loadNamespace(name) : there is no package called 'formatR'

2: In block_exec(params) :
  Failed to tidy R code in chunk 'load PBMC dataset'. Reason:
Error in loadNamespace(name) : there is no package called 'formatR'

Execution halted

# Then I tried to load 'Read10x separately:
> load.packages('Read10x')

# and got the following message:
 package ‘Read10x’ is not available (for R version 3.6.3)

**Comment by timoast** [comment]
The function is `Read10X` not `Read10x`
