### ISSUE TITLE
Error in library(Seurat) : there is no package called ‘Seurat’

### ISSUE THREAD

**Issue by nitinmahajan20** [satijalab/seurat#2808]
I am trying to install the Seurat using the following four lines  one by one, first three lines ran well but got error again and again when I run the fourth line 
ERROR: ""Error in library(Seurat) : there is no package called ‘Seurat’""

install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('Seurat')
library(Seurat)

PLEASE HELP TO FIX THIS

**Comment by nitinmahajan20** [comment]
ALSO, GOT ERROR ""Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘reticulate’""

**Comment by KinSimon96** [comment]
https://github.com/satijalab/seurat/issues/2809

**Comment by wenjunatstanford** [comment]
what should I do about the error message?   I am using a PC.   Thank you!
> library(Seurat)
Error in library(Seurat) : there is no package called ‘Seurat’
