### ISSUE TITLE
Problem Installing Seurat

### ISSUE THREAD

**Issue by nitinmahajan20** [satijalab/seurat#2809]
I am having problem installing Seurat.  
Version of R Studio - Version 1.2.5033

Error I am getting

Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘reticulate’

**Comment by KinSimon96** [comment]
Open RStudio, go to "Packages", click on "install", watch for 'reticulate', then download it.
Second one is to open RStudio as administrator, doing the same command but installing your package in the second library.

Then ` library(Seurat)` , hoping it will work.
