### ISSUE TITLE
is there any other site for tutorial resources except of dropbox

### ISSUE THREAD

**Issue by gnilihzeux** [satijalab/seurat#2810]
Dear author,
  It's a great job of Seurat for the biological field. I'd followed with Seurat for a time but I've been sufferring with our national network firewall. So all resources on droxbox are not available for us.
  So, is there any other site for tutorial resources except of dropbox ?

**Comment by KinSimon96** [comment]
The problem still remains if you use a VPN ?

**Comment by satijalab** [comment]
We are aware of this and looking into a long-term alternative,  but for now, we offer Dropbox to host some resources. Many datasets can also be loaded with SeuratData (https://github.com/satijalab/seurat-data)
