### ISSUE TITLE
MASTDEtest in differential_expression.R

### ISSUE THREAD

**Issue by lwhitmore** [satijalab/seurat#2811]
Seems like your group labels are backwards in the MASTDEtest function

  group.info[cells.1, "group"] <- "Group1"
  group.info[cells.2, "group"] <- "Group2"

Should be
  group.info[cells.1, "group"] <- "Group2"
  group.info[cells.2, "group"] <- "Group1"

if it were to match how seurat is calculating the log fold change although I don't think it is causing issues since logFC from mast are not used and just p-values are but thought I would mention it

**Comment by satijalab** [comment]
Thanks for pointing this out. As you say, this won't change the output - and the group names (1 vs 2) is an arbitrary distinction. The code looks less confusing this way (otherwise set cells.1 to Group2), which was our rationale.
