### ISSUE TITLE
Reclustering Subsets of Integrated Data from SCtransform Workflow

### ISSUE THREAD

**Issue by iSinedeus** [satijalab/seurat#2812]
Hello,

Based on previous issues posted here I gather that if I want to recluster a subset of my dataset that has been integrated I should use the "RNA" assay when I subset my data if I wish to rerun the integration. I was wondering how to do this? I am running the sctransform workflow. I tried to use defaultassay to change the assay of my subset to use the "RNA" assay but I get the same results when I integrated that subset again.  I am running this code following the initial integration:

cd3_s10 <- subset(s10, idents = c(0, 1, 2, 4, 19))
cd3_s10 .list <- SplitObject(object = cd3_s10 , split.by = "orig.ident")
for (i in 1:length(cd3_s10.list)) {
  +    cd3_s10.list[[i]] <- SCTransform(cd3_s10.list[[i]], verbose = FALSE)
  + }
cd3_s10.features <- SelectIntegrationFeatures(object.list = cd3_s10.list, nfeatures = 3000)
cd3_s10.list <- PrepSCTIntegration(object.list = cd3_s10.list, anchor.features = cd3_s10.features, 
                                    verbose = FALSE)
cd3_s10.anchors <- FindIntegrationAnchors(object.list = cd3_s10.list, normalization.method = "SCT", 
anchor.features = sc_merged.features, verbose = FALSE)
cd3_s10.integrated <- IntegrateData(anchorset = cd3_s10.anchors, normalization.method = "SCT", verbose = FALSE)
cd3_s10.integrated <- RunPCA(cd3_s10.integrated, verbose = FALSE)
cd3_s10.integrated <- RunUMAP(cd3_s10.integrated, dims = 1:50)

I then use:
cd3_s10 <- FindNeighbors(cd3_s10, dims = 1:50, verbose = FALSE)
cd3_s10 <- FindClusters(cd3_s10, verbose = FALSE)

I have seen from other issue threads that I could just use runpca and do findneighbors and findclusters immediately after subsetting the initial integrated dataset but I think I get slightly better definition in my clusters when I integrate the subset independently. I appreciate any advice anyone can offer.

Thank you

**Comment by yuhanH** [comment]
Hi,
In case you run SCTransform on RNA assay, but not integrated assay, you can use `DietSeurat` to only keep RNA assay before spliting.
` cd3_s10 <- DietSeurat(cd3_s10, assays = "RNA")`

For question 2, it depends on what you subset. If the subset clusters still contain many heterogeneity, then you re-run SCTransform and it will give you better variable features to describe your subset clusters. Those new variable features will give a better definition in the subset clusters.

**Comment by yuhanH** [comment]
One thing to add. When you subset the clustering, Re-run PCA actually has more impacts than re-run SCTransform

**Comment by rtoddler** [comment]
Hi @yuhanH 
I tried DietSeurat and get return "The default assay is slated to be removed, please change the default assay. So I change the default assay to either SCT or integrated and do it again. 
However, I got the same error. Is there anything wrong with the following script?

sw_subset <- subset(sw.integrated, ident = c("0","1", "2", "3", "4"))
sw_subset <- DietSeurat(sw_subset, assays = "RNA")

Thanks!

**Comment by vwtlin** [comment]
Hi @yuhanH  
Thanks for the information above. I was doing something similar in this thread. From your first reply, re-running SCTransform is recommended if the subsetted clusters still contain much heterogeneity. In your second reply, you mentioned re-running PCA had more impacts.

My questions are
(1) To what extent do you think the clusters contain much heterogeneity? Could I use SCTransform if I subset the T cell cluster for further clustering?
(2) A second example would be the monocyte/macrophage cluster. Could it be considered as a cluster with less heterogeneity? Therefore, re-running PCA here is better?

Thanks!
Weitao

**Comment by neilzhang-ucsb** [comment]
> Hi @yuhanH
> Thanks for the information above. I was doing something similar in this thread. From your first reply, re-running SCTransform is recommended if the subsetted clusters still contain much heterogeneity. In your second reply, you mentioned re-running PCA had more impacts.
> 
> My questions are
> (1) To what extent do you think the clusters contain much heterogeneity? Could I use SCTransform if I subset the T cell cluster for further clustering?
> (2) A second example would be the monocyte/macrophage cluster. Could it be considered as a cluster with less heterogeneity? Therefore, re-running PCA here is better?
> 
> Thanks!
> Weitao

According to satijalab's comment in https://github.com/satijalab/seurat/issues/2014, it is fine to rerun SCTransform after subsetting the object.

**Comment by rrchai** [comment]
> Hi @yuhanH
> I tried DietSeurat and get return "The default assay is slated to be removed, please change the default assay. So I change the default assay to either SCT or integrated and do it again.
> However, I got the same error. Is there anything wrong with the following script?
> 
> sw_subset <- subset(sw.integrated, ident = c("0","1", "2", "3", "4"))
> sw_subset <- DietSeurat(sw_subset, assays = "RNA")
> 
> Thanks!

Hi @rtoddler, just saw your question. If you change default assay to RNA, it should fix your problem.
```
DefaultAssay(sw.integrated) <- "RNA"
sw_subset <- subset(sw.integrated, ident = c("0","1", "2", "3", "4"))
sw_subset <- DietSeurat(sw_subset, assays = "RNA")
```
