### ISSUE TITLE
Error during Integration:  'list' object cannot be coerced to type 'integer' 

### ISSUE THREAD

**Issue by Gnosta** [satijalab/seurat#2815]
Hi, awesome package and web tutorials.

I am hoping you can help me with the following error.

I am attempting to integrate two data sets (10X, Strtseq) but receiving error message as below. 
> intesivtivv.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
**Error in FindIntegrationAnchors(object.list = reference.list, dims = 1:30) : 
  'list' object cannot be coerced to type 'integer'**

10X data(hemivt) is read into Seurat as a raw output after cellranger and Strtseq data(gao2018_SI) is a tsv file of TPM values.
Both data can go through Seurat pipeline without an issue individually.

Below is the console output from the beginning. Many thanks in advance.

> library(dplyr)
> library(Seurat)
> library(ggplot2)
> library(patchwork)
>
> hemivt.data <- Read10X(data.dir = "C:/Users/")
> hemivt.data <- log1p(hemivt.data)
> hemivt <- CreateSeuratObject(counts = hemivt.data, project = "hemivt_1", min.cells = 3, min.features = 200)
**Feature names cannot have underscores ('_'), replacing with dashes ('-')**
> hemivt <- AddMetaData(object = hemivt, metadata = "hemivt1", col.name = 'data.source')
> 
> gao2018 <- read.table("c:/Users/sontae00/Documents/RawData/GSE95630_Digestion_TPM_new.txt", header = T, sep = "\t", row.names = 1)
> gao2018_SI <- select(gao2018, contains("SI"))
> gao2018_SI <- select(gao2018_SI, -contains("_v"))
> gao2018_SI <- log1p(gao2018_SI)
> gao2018_SI <- CreateSeuratObject(counts = gao2018_SI, project = "gao2018_SI", min.cells = 3, min.features = 200)
**Feature names cannot have underscores ('_'), replacing with dashes ('-')**
> gao2018_SI <- AddMetaData(object = gao2018_SI, metadata = "gao2018_SI", col.name = 'data.source')
> 
> hemivt
**An object of class Seurat
22241 features across 13592 samples within 1 assay 
Active assay: RNA (22241 features)**
> gao2018_SI
**An object of class Seurat 
22131 features across 1199 samples within 1 assay 
Active assay: RNA (22131 features)**
> 
> hemivt[["percent.mt"]] <- PercentageFeatureSet(hemivt, pattern = "^MT-")
> VlnPlot(hemivt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size =0.1)
> plot1 <- FeatureScatter(hemivt, feature1 = "nCount_RNA", feature2 = "percent.mt")
> plot2 <- FeatureScatter(hemivt, feature1   = "nCount_RNA", feature2 = "nFeature_RNA")
> plot1 + plot2
> hemivt <- subset(hemivt, subset = nFeature_RNA > 900 & nFeature_RNA < 5000 & nCount_RNA < 30000 & percent.mt < 10)
>
> gao2018_SI[["percent.mt"]] <- PercentageFeatureSet(gao2018_SI, pattern = "^MT-")
> VlnPlot(gao2018_SI, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size =0.1)
**All cells have the same value of percent.mt.**
> plot1 <- FeatureScatter(gao2018_SI, feature1 = "nCount_RNA", feature2 = "percent.mt")
**l'�cart type est nulle**
> plot2 <- FeatureScatter(gao2018_SI, feature1   = "nCount_RNA", feature2 = "nFeature_RNA")
> plot1 + plot2
> hemivt <- NormalizeData(hemivt, normalization.method = "RC", scale.factor = 1e6)
**Performing relative-counts-normalization**
> hemivt <- FindVariableFeatures(hemivt, selection.method = "vst", nfeatures = 2000)
**Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|**
> 
> #gao2018 is a TPM data thus no normalization. The data has been natural log transformed.
> gao2018_SI <- FindVariableFeatures(gao2018_SI, selection.method = "vst", nfeatures = 2000)
**Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|**
> 
> 
> reference.list <- objects()
> reference.list$hemivt = hemivt
**Conversion automatique de LHS en liste**
> reference.list$gao2018_SI = gao2018_SI
> intesivtivv.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
**Error in FindIntegrationAnchors(object.list = reference.list, dims = 1:30) : 
  'list' object cannot be coerced to type 'integer'**

**Comment by andrewwbutler** [comment]
Hi,

I think your problem may be in the creation of the object list. Can you try the following? 

```R
reference.list <- list(hemivt, gao2018_SI)
intesivtivv.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
```

**Comment by Gnosta** [comment]
Worked like a charm- Downstream analysis also works so far. Many thanks again. The revised code used and output below.

```
reference.list <- list(hemivt, gao2018_SI)
intesivtivv.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
intesivtivv.integrated <- IntegrateData(anchorset = intesivtivv.anchors, dims = 1:30)
```

_Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 4650 anchors
Filtering anchors
	Retained 2546 anchors
Extracting within-dataset neighbors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 01s
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Adding a command log without an assay associated with it_

**Comment by ETO-C** [comment]
Thanks very much，it’s helps me a lot

**Comment by whiteorchid** [comment]
Hi, 
I have tried to combine two Seurat object, came across the same error, and I tried to use `reference.list <-  list(A, B)`, the error stays. The A Seurat object has 34660 features and the B Seurat object has 815 features before **Normalize** and **FindVariableFeatures**; I tried to adjust the nfeatures to 800, still shows the error.

Thanks a lot for any guidance!

**Comment by andrewwbutler** [comment]
@whiteorchid , can you please post the code you're running that leads to the error?

**Comment by whiteorchid** [comment]
sure, I post the scripts in another issue(they are somewhat related...) at https://github.com/satijalab/seurat/issues/1296, thanks a lot!

**Comment by andrewwbutler** [comment]
Can you confirm that the `reference.list` here is a list with two Seurat objects as elements?
