### ISSUE TITLE
Integrating datasets that do not share a common cell type

### ISSUE THREAD

**Issue by xhbkirby** [satijalab/seurat#2816]
I'm working on a large collection of scRNA-seq datasets which contain cells from a similar anatomical tissue type but taken at different developmental stages (i.e., early fetal, late fetal, young and adult). For each of the stages there are several replicates/batches. So on one hand it's obviously desirable to perform data integration/alignment to correct for the batch effects between biological replicates of the same developmental stages. On the other hand, although all of the datasets are from the same broad tissue type, the cellular compositions of this tissue across different developmental stages are quite different (based on analysis of distinct developmental stage datasets separately). Although the tissue could contain certain cell types (say endothelial cells) that belong to the same broad cell type category across development, there are significant and biologically very important differences between even the "same" broad cell type at different developmental stages.

So in this situation where there is no "perfectly" shared cell types across all datasets (but cell type similarities are well presented between a subset of batches), is it recommended to perform data integration using Seurat V3 functions? Will there be concerns of over-correction (and loss of true biological differences) if integration/alignment is performed? Thanks!

**Comment by satijalab** [comment]
This can be a concern for any integration method - if only a subset of cell types is preserved, there is always a chance of over integration.

We would suggest using our reciprocal PCA workflow, which should minimize the possibility of this, and to carefully look at the results to make sure they make sense biologically
