### ISSUE TITLE
Difference in number of genes while doing differential expression testing

### ISSUE THREAD

**Issue by suvi93** [satijalab/seurat#2819]
I've run the FindMarkers() function using the default Wilcoxon test and using DESeq2. 
the number of differentially expressed genes greatly varies between them. the difference is almost 10x greater when i use DESeq2 when compared to the Wilcoxon test.

1. Is there any reason why this is happening? 
2. which test should I trust more?

**Comment by timoast** [comment]
They're different tests, so it's expected that the output is not the same. There are several papers that look at different methods for single-cell differential expression, for example: https://www.nature.com/articles/nmeth.4612, https://www.nature.com/articles/s41592-018-0303-9. Keep in mind that DESeq2 was not developed for testing differential expression in single-cell experiments.
