### ISSUE TITLE
Differential expression between conditions

### ISSUE THREAD

**Issue by daymegr** [satijalab/seurat#2820]
Dear Seurat team, 
I have 4 SCRNA-seq datasets from 4 different patients. Two of them are tumor samples and the other two are controls. After performing the dataset integration as explained in your vignette: https://satijalab.org/seurat/v3.1/immune_alignment.html, I want to find differentially expressed genes in Tumor vs Control for each specific cluster. I have clear technical differences in the 4 patients. Should I first scale my integrated dataset regressing the patient variable? ScaleData(object = scData, vars.to.regress = "patient") and then do the differential expression between conditions and cluster with a logistic regression model including as a latent variable the patient too? FindAllMarkers(object=scData, test.use = "LR", only.pos=TRUE, latent.vars = "patient"). I am also confused because patient is my batch and I only have one replicate per batch. 

I appreciate your help. Thank you. 
Daymé

**Comment by andrewwbutler** [comment]
Hi Daymé,

For differential expression testing here, I would use a model-based test (e.g. "LR" like you suggest) with patient as a latent variable. However, I would recommend performing the test on the original "RNA" assay, not the integrated data (see [FAQ 4](https://satijalab.org/seurat/faq) ) .
