### ISSUE TITLE
Create Seurat Object min.features

### ISSUE THREAD

**Issue by erikagucciardo** [satijalab/seurat#2821]
Hi,
After I create the Seurat object with the CreateSeuratObject function with min.features = 200, I get a Seurat object where there is one cell with 199 feature. How is that possible?
If I filter manually, the cell that has 199 features shows to have 200 features instead.

**Comment by andrewwbutler** [comment]
Hi,

Are you also filtering using `min.cells`? This will filter out features that aren't expressed in a minimum number of cells (default of 0). The `CreateSeuratObject` function will first filter out any cells with fewer than `min.features` and then filter out any features expressed in fewer than `min.cells`. If this still doesn't explain it, could you provide a reproducible example?

**Comment by erikagucciardo** [comment]
Yes, I checked the CreateSeuratObject function, which calls the CreateAssayObject function where the filtering is done.

data <- Read10X(data.dir = "filtered_feature_bc_matrix")
seu <- CreateSeuratObject(counts = pdr.data1_10, min.cells = 3,min.features = 200, names.delim = "-",names.field = 2)
table(seu$nFeature_RNA == 199)
FALSE  TRUE 
17662     1 

I actually tried to do the filtering manually again and I get the same problem: one cell (same cell) has 199 Features. This is how I do it manually:
nfeatures = Matrix::colSums(x = data > 0)
data = data[,which(nfeatures >= 200)]
ncells = Matrix::rowSums(x = data  > 0)
data  = data [which(ncells >= 3),]
nfeatures_data = Matrix::colSums(x = data   > 0)
length(data[,which(nfeatures_data == 199)][data[,which(nfeatures_data == 199)] > 0])
[1] 199

Why do I get one cell having 199 Features when I set the minimum to 200?

**Comment by erikagucciardo** [comment]
Yes, I checked the CreateSeuratObject function, which calls the CreateAssayObject function where the filtering is done.

data <- Read10X(data.dir = "filtered_feature_bc_matrix")
seu <- CreateSeuratObject(counts =data, min.cells = 3,min.features = 200, names.delim = "-",names.field = 2)
table(seu$nFeature_RNA == 199)
FALSE TRUE
17662 1

I actually tried to do the filtering manually again and I get the same problem: one cell (same cell) has 199 Features. This is how I do it manually:
nfeatures = Matrix::colSums(x = data > 0)
data = data[,which(nfeatures >= 200)]
ncells = Matrix::rowSums(x = data > 0)
data = data [which(ncells >= 3),]
nfeatures_data = Matrix::colSums(x = data > 0)
length(data[,which(nfeatures_data == 199)][data[,which(nfeatures_data == 199)] > 0])
[1] 199

Why do I get one cell having 199 Features when I set the minimum to 200?

**Comment by andrewwbutler** [comment]
This can happen because the gene filtering happens after the cell filtering. Imagine the case where you have a cell that expresses 200 features but one of those features is only expressed in that one cell. The cell will pass the `min.feature` cutoff and thus be included in the final matrix but the gene that is only expressed in that cell will be filtered out with the `min.cells` cutoff. Therefore, in the final matrix, that cell will have only 199 features.
