### ISSUE TITLE
Correlation question

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#2822]
Hi all!

Thanks for making this great package and being so exceptionally responsive and helpful!

My question is about drawing correlations between conditions. 

If you have a control (NA) and a two treated samples (V7, V14) and integrate them to obtain a single UMAP. Once you split the view into individual UMAPs for each sample, is there a way to show how well each condition correlates for each cluster? or how well the conditions correlate together? 

Thanks!
![Poster_Split](https://user-images.githubusercontent.com/46829204/78610354-47654480-782a-11ea-81d5-41b6a5926fc9.jpeg)

**Comment by yuhanH** [comment]
Hi, tmccra2
Could you explain more about the question:  is there a way to show how well each condition correlates for each cluster? or how well the conditions correlate together?
What is the meaning of "each condition correlates for each cluster"? 
This stimulated vs. control PBMC vignette may give me some ideas to compare different conditions: https://satijalab.org/seurat/v3.1/immune_alignment.html

**Comment by tmccra2** [comment]
Thanks for your response! I got this as a question at a conference and didn't really understand it, glad to see it doesn't make sense to you either! I'll use a few other ways in the tutorial to show more comparisons between conditions. Thanks!
