### ISSUE TITLE
QC filtering and Elbow plot questions

### ISSUE THREAD

**Issue by rrkatreddi** [satijalab/seurat#2824]
Hi,

I am new to single cell RNA sequencing analysis and I am learning on Seurat/Rstudio. I have following questions regarding QC filtering:

1. For QC filtering:
 Does the percent mitochondrial genes and number of features used to filter low quality cells differ from one experiment to other. In pbmc data set they chose 5% mito genes and 2500 number of features on the basis of the graphs.
However, in our data I am not sure how to chose threshold for percent mitochondrial genes and number of genes on the higher end. It looks like we got around 9000 features and 25% mito genes in our graph.

Question: Do we in general choose 5 to 10% mitochondrial genes as common threshold or does it change for every data. If I chose 25% mito genes, is it a lot? And also is 9000 genes as higher threshold for QC in a single cell analysis a lot? Can there be doublets there even after I chose filtered reads but not raw reads from cell ranger output?

2. Regarding number of significant principal components for dimensional reduction
[percent mt.pdf](https://github.com/satijalab/seurat/files/4441910/percent.mt.pdf)

:
From elbow plot where standard deviation is plotted against number of PCs, the number of significant PCs that you chose is affecting how cells are clustered in UMAP. How exactly do you chose the number of PCs. If I chose more than required, it is affecting the way cells are getting clustered. Is there a standard way to chose number of PCs rather than looking at the elbow plot. Because it is most of the times subjective to choose the elbow point.

**Comment by timoast** [comment]
1. Yes, the mitochondrial percentage will vary between experiments. From the plot that you've show, you can see that the cells with low total counts have a much higher percentage of mitochondrial reads. If you applied some filtering of these cells, the average mitochondrial percentage would be <10%.
2. Please see the section "Determining the dimensionality of the dataset" in the PBMC vignette: https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html
