### ISSUE TITLE
how to use sctransform/integration in place of cell ranger aggr

### ISSUE THREAD

**Issue by danhtruong** [satijalab/seurat#2826]
I have read some of the old issues and they do not answer my question completely. I read the sctransform article and it suggests to use this method as a normalization technique that accounts for different sequencing depths. 

Now I have 3 experiments (batches) with 8 samples each. Each of the samples do not have the same read depth due to technical errors. 

1. Do I combine them into their batches and perform sctransform on the batches followed by integration?
2. Do I perform sctransform on the entire experiment then split into batches and use integration?
3. Do I do sctransform on each sample individually and then use integration?

Thank you for time and response in these difficult times. Hope everyone is well.

**Comment by danhtruong** [comment]
As a follow up question, would you recommend performing removing low quality cells before sctransform/integration or in the new merged dataset?

**Comment by yuhanH** [comment]
Hi,
You should remove low quality cells before SCTransform.
Do your sample have strong sample effects within the same batch?

If not, you can run SCTransform on each batch, and integrate those batches, like the SCT integration vignettes https://satijalab.org/seurat/v3.1/integration.html

If each of your samples have a strong sample-effect, you can run SCTransform on each sample, and integrate them.
