### ISSUE TITLE
Error Using CreateSeuratObject  (In storage.mode(from) <- "double" : NAs introduced by coercion)

### ISSUE THREAD

**Issue by oh111** [satijalab/seurat#2827]
I am loading a .txt file from GEO as a Seurat Object in R but I keep getting this error: 

**_Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion_**

My Row names are the Gene name and my column names are the cell type. 
I thought that perhaps the data entered is in 'character' format, but when I convert it to 'numeric', I get the same error.

when I: 
**_sseq
An object of class Seurat 
55855 features across 563 samples within 1 assay 
Active assay: RNA (55855 features)_**
Which seems normal, but when I look at the meta.data, nCount_RNA and nFeatures_RNA are all NAs (at least for the first 50 rows)

Any help with GEO .txt files would be awesome. 

EDIT: I used just a subset of the whole data set and it works fine. But the Original file still gives the error.

**Comment by aditisk** [comment]
Hi @oh111, I'm running into the same issue with a txt file from GEO. Were you able to find a way to use the whole dataset ? Thanks.

**Comment by oh111** [comment]
Hi @aditisk, for my particular dataset, I noticed there were some issues with the geo txt file-- either the spaces were missing or misaligned or something else of the sort. 
My solution is not the most elegant: I put the entire dataset into excel, and looked at the rows to see the issue, and then adjusted accordingly. Particularly it was with certain genes that I was having an issue.

**Comment by aditisk** [comment]
Hi @oh111, mine seemed to have the same issue too. I fixed it in excel and also found this suggestion to be helpful.

`my_data <- read.table(file = "Matrix.txt", header = T, sep="\t", as.is=T,row.names = 1)`

Previously I was importing the data with read.csv(). A combination of the two fixed my problem.

Thanks for your prompt response :)
