### ISSUE TITLE
Issue with IntegrateData - "out of memory" 

### ISSUE THREAD

**Issue by SaraJeanne08** [satijalab/seurat#2828]
Hi,

I am running single cell seq analysis and am being held at the IntegrateData step:

seurat_integrated <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT")

Integrating data
Merging dataset 10 6 1 into 7 11 9 8
Extracting anchors for merged samples
Finding integration vectors
Error in .Arith.Csparse(e1, e2, .Generic, class. = "dgCMatrix") : 
  Cholmod error 'out of memory' at file ../Core/cholmod_memory.c, line 147

My integ_anchors object is 1.3Gb. I am running this on GCP, my instance type is memory-optimized, so there are 26 GB of RAM. How much memory do I need to boost my vm to in order to get this to run?

Thank you,

Sara

**Comment by timoast** [comment]
It's very difficult to estimate the amount of memory required, as this will depend on several things including the number of cells in each object, the sparsity of the data, and the number of features you're integrating. If you need to reduce the memory required, you can try using the reference-based or reciprocal PCA workflows (https://satijalab.org/seurat/v3.1/integration.html)
