### ISSUE TITLE
Continuing trouble with SCTransform - Iteration limit reached

### ISSUE THREAD

**Issue by divya-sam** [satijalab/seurat#2829]
I am using Seurat v 3.1.4 and I'm still getting "iteration limit reached" when I run SCTransform on my 10x Genomics scRNA seq gene expression libraries. I see that this issue has been reported last year as well. Anyone with successful SCTransform runs?

**Comment by andrewwbutler** [comment]
Hi,

Please see https://github.com/ChristophH/sctransform/issues/25 for a discussion of this warning message.

**Comment by MWRR** [comment]
I am facing the same problem when I run
Cproject <- SCTransform(Cproject, vars.to.regress = c("percent.mt", "percent.rps", "percent.rpl", "percent.rrna", "nCount_RNA", "nFeature_RNA"), verbose = FALSE, return.only.var.genes = FALSE)
the warning is not stop just if I stop the code running.   **ChristophH/sctransform#25** not work for me.
Anyone finds solution to this issue?
