### ISSUE TITLE
Using Batch Corrected data downstream for Monocle

### ISSUE THREAD

**Issue by k3yavi** [satijalab/seurat#283]
Hi guys,

I am wondering is it possible to extract only the relevant information from the `seurat` object after performing `cca-alignment` (batch-correction) to work downstream as an input to Monocle's `importCDS` function for making time-series plots?

Thanks!

**Comment by satijalab** [comment]
Seurat does not return batch-corrected expression values (if we did, we would not be able to compare expression values over different conditions, as these would be subtracted). Instead, Seurat can be used to generate a corrected cell/cell distance matrix. I do not know if Monocle accepts this as input for trajectory reconstruction, but if it does, then this should be doable.
