### ISSUE TITLE
Merging Subsets that have been Processed Through Sctransform

### ISSUE THREAD

**Issue by iSinedeus** [satijalab/seurat#2831]
Hello,

When I integrate my samples using the sctransform workflow and then subset them and attempt to merge these subsets I get the following error:
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

I was wondering how to work around this to allow me to merge different subsets? The reason I am interested in doing this is because I am working with a set number of samples at a time to process them and hope to combine cell types from these different sets of samples. The dataset would be too large for my computing capability to process them all together.

Thank you

**Comment by iSinedeus** [comment]
I've found I can use: Subset2 <- SubsetData(s10, accept.value = c(3, 4, 5), assay = 'RNA')
And then later merge subsets created in this manner. But if I use the non-deprecated "subset" function and try to use assay = "RNA" I get the message that the assay argument is not used. Is it acceptable to subset in this manner for merging files? And if I subset through this method am I able to recluster the initial subset when I subset using the RNA assay? When I look at the default assay it still says integrated in these subsets

**Comment by andrewwbutler** [comment]
Hi,

There's a small bug in how subset is working on sctransform Assays (basically it's not subsetting all that it should be and then recombining subsetted objects throws it off). A work around for now is to rerun `SCTransform` on the subsetted objects before merging.

**Comment by jhe2020** [comment]
Hi, I also have trouble with merging subsetted objects on SCT assays. I subsetted obj1 and obj2 from a parent seurat object that underwent SCTransform. obj2 is subsetted with random downsample to match cell number in obj1. I'm not able to merge obj1 and obj2. I also get different errors when I try to rerun SCTransform on the subsetted objects. 

> obj1
An object of class Seurat 
2 features across 496 samples within 2 assays 
Active assay: SCT (1 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, harmony, umap
> obj2
An object of class Seurat 
2 features across 496 samples within 2 assays 
Active assay: SCT (1 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, harmony, umap

> obj.merged <- merge(x=obj1, y=obj2)
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “numeric” is not valid for slot ‘data’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE

> obj1<-SCTransform(obj1, assay = "SCT")
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 0 by 496
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 0 genes, 496 cells
  |                                                             |   0%Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

> obj2<-SCTransform(obj2, assay = "SCT")
Calculating cell attributes for input UMI matrix
Error in row_gmean(umi, eps = gmean_eps) : 
  matrix x needs to be of class matrix or dgCMatrix

**Comment by timoast** [comment]
I believe this was fixed in d42126de4348f21d7bdad19fa08f5b47ced22bed. If it's still an issue with the current version  on the develop branch, please reopen the issue
