### ISSUE TITLE
Using Seurat merged object for pseudo time analysis in Monocle 3

### ISSUE THREAD

**Issue by CaroSegami** [satijalab/seurat#2833]
I have an SCTtransformed merged Seurat object and I would like to follow up with a pseudo time analysis. I've seen that last year Seurat didn't support conversion of Seurat objects to Monocle 3 cds because it was still beta. Is this still the case? Which pseudo time analysis that could be compatible with Seurat object would you recommend? I expect my data to be linear rather than branched. Thank you.

**Comment by KinSimon96** [comment]
Hello, 
Here is how I convert the object of class Seurat into a cds object (Monocle3) for pseudotime analysis. Eveything will be unchanged. I don't know if it will work with SCTransformed, but you should be able to do your own modifications with the code below. My seurat object here is "Try"

```
gene_annotation <- as.data.frame(rownames(try@reductions[["pca"]]@feature.loadings),
                                 row.names = rownames(try@reductions[["pca"]]@feature.loadings))
colnames(gene_annotation) <- "gene_short_name"


cell_metadata <- as.data.frame(try@assays[["RNA"]]@counts@Dimnames[[2]],
                               row.names = try@assays[["RNA"]]@counts@Dimnames[[2]])
colnames(cell_metadata) <- "barcode"


New_matrix <- try@assays[["RNA"]]@counts
New_matrix <- New_matrix[rownames(try@reductions[["pca"]]@feature.loadings), ]
expression_matrix <- New_matrix

library(monocle3)

cds_from_seurat <- new_cell_data_set(expression_matrix,
                                     cell_metadata = cell_metadata,
                                     gene_metadata = gene_annotation)


recreate.partition <- c(rep(1, length(cds_from_seurat@colData@rownames)))
names(recreate.partition) <- cds_from_seurat@colData@rownames
recreate.partition <- as.factor(recreate.partition)

cds_from_seurat@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partition



list_cluster <- try@active.ident
names(list_cluster) <- try@assays[["RNA"]]@data@Dimnames[[2]]

cds_from_seurat@clusters@listData[["UMAP"]][["clusters"]] <- list_cluster



cds_from_seurat@clusters@listData[["UMAP"]][["louvain_res"]] <- "NA"


cds_from_seurat@int_colData@listData$reducedDims@listData[["UMAP"]] <-try@reductions[["umap"]]@cell.embeddings


cds_from_seurat@preprocess_aux$gene_loadings <- try@reductions[["pca"]]@feature.loadings
```
Then perform pseudotime analysis:


```
cds_from_seurat <- learn_graph(cds_from_seurat, use_partition = F)

plot_cells(cds_from_seurat, 
                   color_cells_by = 'cluster',
                   label_groups_by_cluster=TRUE,
                   label_leaves=FALSE,
                   label_branch_points=TRUE,
           graph_label_size=4)
```


Hope it will help. Good luck!

**Comment by CaroSegami** [comment]
Thanks a lot! It worked!

**Comment by satijalab** [comment]
This is very helpful - thanks! We're preparing to release some updates as well to make this a bit easier, stay tuned!

**Comment by mojaveazure** [comment]
Beta Monocle 3 support us available on [SeuratWrappers](https://github.com/satijalab/seurat-wrappers) on the [feat/monocle3](https://github.com/satijalab/seurat-wrappers/tree/feat/monocle3) branch. Conversion to and from `Seurat` objects is available with `as.cell_data_set` and `as.Seurat`

**Comment by CaroSegami** [comment]
Hi @mojaveazure, I couldn't make the as.cell_data_set command work after installing SeuratWrappers:

```
library(SeuratWrappers)
cds<-as.cell_data_set(my_seurat_object)
```
It gives me:

Error in as.cell_data_set(my_seurat_object) : 
  could not find function "as.cell_data_set"

**Comment by mojaveazure** [comment]
You need to use the feat/monocle3 branch of SeuratWrappers, not the master or develop branches.

**Comment by CaroSegami** [comment]
How do I do that?
Is the installation different?
I used this:

`devtools::install_github('satijalab/seurat-wrappers')`

**Comment by CaroSegami** [comment]
Nevermind! I managed, but when I try to run "learn_graph" from Monocle3 it gives me this error:

No dimensionality reduction for UMAP calculated. Please run reduce_dimensions with reduction_method = UMAP and cluster_cells before running learn_graph.

Does this mean that it didn't save all the characteristics of the previous merged Seurat object? I could directly run the learn_graph with the cds object resulting from the code above.

**Comment by vlcm2019** [comment]
Thank you KinSimon96 for sharing your code. It worked for pseudotime analysis.

**Comment by ahoffrichter** [comment]
I had to change

`cds_from_seurat@int_colData@listData$reducedDims@listData[["UMAP"]] <-try@reductions[["umap"]]@cell.embeddings`

to 

`cds_from_seurat@reducedDims@listData[["UMAP"]] <-boost@reductions[["umap"]]@cell.embeddings`

in @KinSimon96  's solution to make it work for me. 

Thanks for the workaround!

**Comment by nbahlis** [comment]
I downloaded the develop version of monocle 3 but I still get this error below, any help is greatly appreciated

> cds <- as.cell_data_set(integrated)
Error in as.cell_data_set(integrated) : 
  could not find function "as.cell_data_set"

**Comment by chlee-tabin** [comment]
install `SeuratWrappers` and follow https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html

**Comment by Mohebg1234** [comment]
@mojaveazure , thanks for the update in seuratwrappers, I have a question regarding plotting in tSNE, rather than UMAP?
It seems that I can only plot UMAP, rather than tSNE in the cell dataset object converted from Seurat

**Comment by qoiopipq** [comment]
@Mohebg1234  same issue

Have you figured out how to do it using SeuratWrappers? Or have to do it manually?

**Comment by vicscott** [comment]
> Hello, Here is how I convert the object of class Seurat into a cds object (Monocle3) for pseudotime analysis. Eveything will be unchanged. I don't know if it will work with SCTransformed, but you should be able to do your own modifications with the code below. My Seurat object here is `try`
> 
> ```
> gene_annotation <- as.data.frame(rownames(try@reductions[["pca"]]@feature.loadings),
>                                  row.names = rownames(try@reductions[["pca"]]@feature.loadings))
> colnames(gene_annotation) <- "gene_short_name"
> 
> 
> cell_metadata <- as.data.frame(try@assays[["RNA"]]@counts@Dimnames[[2]],
>                                row.names = try@assays[["RNA"]]@counts@Dimnames[[2]])
> colnames(cell_metadata) <- "barcode"
> 
> 
> New_matrix <- try@assays[["RNA"]]@counts
> New_matrix <- New_matrix[rownames(try@reductions[["pca"]]@feature.loadings), ]
> expression_matrix <- New_matrix
> 
> library(monocle3)
> 
> cds_from_seurat <- new_cell_data_set(expression_matrix,
>                                      cell_metadata = cell_metadata,
>                                      gene_metadata = gene_annotation)
> 
> 
> recreate.partition <- c(rep(1, length(cds_from_seurat@colData@rownames)))
> names(recreate.partition) <- cds_from_seurat@colData@rownames
> recreate.partition <- as.factor(recreate.partition)
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partition
> 
> 
> 
> list_cluster <- try@active.ident
> names(list_cluster) <- try@assays[["RNA"]]@data@Dimnames[[2]]
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["clusters"]] <- list_cluster
> 
> 
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["louvain_res"]] <- "NA"
> 
> 
> cds_from_seurat@int_colData@listData$reducedDims@listData[["UMAP"]] <-try@reductions[["umap"]]@cell.embeddings
> 
> 
> cds_from_seurat@preprocess_aux$gene_loadings <- try@reductions[["pca"]]@feature.loadings
> ```
> 
> Then perform pseudotime analysis:
> 
> ```
> cds_from_seurat <- learn_graph(cds_from_seurat, use_partition = F)
> 
> plot_cells(cds_from_seurat, 
>                    color_cells_by = 'cluster',
>                    label_groups_by_cluster=TRUE,
>                    label_leaves=FALSE,
>                    label_branch_points=TRUE,
>            graph_label_size=4)
> ```
> 
> Hope it will help. Good luck!

So great, it can even help me at 2022!

**Comment by paulatn240** [comment]
> Hello, Here is how I convert the object of class Seurat into a cds object (Monocle3) for pseudotime analysis. Eveything will be unchanged. I don't know if it will work with SCTransformed, but you should be able to do your own modifications with the code below. My Seurat object here is `try`
> 
> ```
> gene_annotation <- as.data.frame(rownames(try@reductions[["pca"]]@feature.loadings),
>                                  row.names = rownames(try@reductions[["pca"]]@feature.loadings))
> colnames(gene_annotation) <- "gene_short_name"
> 
> 
> cell_metadata <- as.data.frame(try@assays[["RNA"]]@counts@Dimnames[[2]],
>                                row.names = try@assays[["RNA"]]@counts@Dimnames[[2]])
> colnames(cell_metadata) <- "barcode"
> 
> 
> New_matrix <- try@assays[["RNA"]]@counts
> New_matrix <- New_matrix[rownames(try@reductions[["pca"]]@feature.loadings), ]
> expression_matrix <- New_matrix
> 
> library(monocle3)
> 
> cds_from_seurat <- new_cell_data_set(expression_matrix,
>                                      cell_metadata = cell_metadata,
>                                      gene_metadata = gene_annotation)
> 
> 
> recreate.partition <- c(rep(1, length(cds_from_seurat@colData@rownames)))
> names(recreate.partition) <- cds_from_seurat@colData@rownames
> recreate.partition <- as.factor(recreate.partition)
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partition
> 
> 
> 
> list_cluster <- try@active.ident
> names(list_cluster) <- try@assays[["RNA"]]@data@Dimnames[[2]]
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["clusters"]] <- list_cluster
> 
> 
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["louvain_res"]] <- "NA"
> 
> 
> cds_from_seurat@int_colData@listData$reducedDims@listData[["UMAP"]] <-try@reductions[["umap"]]@cell.embeddings
> 
> 
> cds_from_seurat@preprocess_aux$gene_loadings <- try@reductions[["pca"]]@feature.loadings
> ```
> 
> Then perform pseudotime analysis:
> 
> ```
> cds_from_seurat <- learn_graph(cds_from_seurat, use_partition = F)
> 
> plot_cells(cds_from_seurat, 
>                    color_cells_by = 'cluster',
>                    label_groups_by_cluster=TRUE,
>                    label_leaves=FALSE,
>                    label_branch_points=TRUE,
>            graph_label_size=4)
> ```
> 
> Hope it will help. Good luck!

Thank you very much! It works for me, I just had to change preprocess_aux for reduce_dim_aux  :)

**Comment by qimiaonnegliguo** [comment]
> Hello, Here is how I convert the object of class Seurat into a cds object (Monocle3) for pseudotime analysis. Eveything will be unchanged. I don't know if it will work with SCTransformed, but you should be able to do your own modifications with the code below. My Seurat object here is `try`
> 
> ```
> gene_annotation <- as.data.frame(rownames(try@reductions[["pca"]]@feature.loadings),
>                                  row.names = rownames(try@reductions[["pca"]]@feature.loadings))
> colnames(gene_annotation) <- "gene_short_name"
> 
> 
> cell_metadata <- as.data.frame(try@assays[["RNA"]]@counts@Dimnames[[2]],
>                                row.names = try@assays[["RNA"]]@counts@Dimnames[[2]])
> colnames(cell_metadata) <- "barcode"
> 
> 
> New_matrix <- try@assays[["RNA"]]@counts
> New_matrix <- New_matrix[rownames(try@reductions[["pca"]]@feature.loadings), ]
> expression_matrix <- New_matrix
> 
> library(monocle3)
> 
> cds_from_seurat <- new_cell_data_set(expression_matrix,
>                                      cell_metadata = cell_metadata,
>                                      gene_metadata = gene_annotation)
> 
> 
> recreate.partition <- c(rep(1, length(cds_from_seurat@colData@rownames)))
> names(recreate.partition) <- cds_from_seurat@colData@rownames
> recreate.partition <- as.factor(recreate.partition)
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partition
> 
> 
> 
> list_cluster <- try@active.ident
> names(list_cluster) <- try@assays[["RNA"]]@data@Dimnames[[2]]
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["clusters"]] <- list_cluster
> 
> 
> 
> cds_from_seurat@clusters@listData[["UMAP"]][["louvain_res"]] <- "NA"
> 
> 
> cds_from_seurat@int_colData@listData$reducedDims@listData[["UMAP"]] <-try@reductions[["umap"]]@cell.embeddings
> 
> 
> cds_from_seurat@preprocess_aux$gene_loadings <- try@reductions[["pca"]]@feature.loadings
> ```
> 
> Then perform pseudotime analysis:
> 
> ```
> cds_from_seurat <- learn_graph(cds_from_seurat, use_partition = F)
> 
> plot_cells(cds_from_seurat, 
>                    color_cells_by = 'cluster',
>                    label_groups_by_cluster=TRUE,
>                    label_leaves=FALSE,
>                    label_branch_points=TRUE,
>            graph_label_size=4)
> ```
> 
> Hope it will help. Good luck!

hi thanks for your great work. I have a small question. If im working on an integrated Seurat object, should I use 'integrated' instead of 'RNA' assay? Thank you.

**Comment by dclee2024** [comment]
#

> > Hello, Here is how I convert the object of class Seurat into a cds object (Monocle3) for pseudotime analysis. Eveything will be unchanged. I don't know if it will work with SCTransformed, but you should be able to do your own modifications with the code below. My Seurat object here is `try`
> > ```
> > gene_annotation <- as.data.frame(rownames(try@reductions[["pca"]]@feature.loadings),
> >                                  row.names = rownames(try@reductions[["pca"]]@feature.loadings))
> > colnames(gene_annotation) <- "gene_short_name"
> > 
> > 
> > cell_metadata <- as.data.frame(try@assays[["RNA"]]@counts@Dimnames[[2]],
> >                                row.names = try@assays[["RNA"]]@counts@Dimnames[[2]])
> > colnames(cell_metadata) <- "barcode"
> > 
> > 
> > New_matrix <- try@assays[["RNA"]]@counts
> > New_matrix <- New_matrix[rownames(try@reductions[["pca"]]@feature.loadings), ]
> > expression_matrix <- New_matrix
> > 
> > library(monocle3)
> > 
> > cds_from_seurat <- new_cell_data_set(expression_matrix,
> >                                      cell_metadata = cell_metadata,
> >                                      gene_metadata = gene_annotation)
> > 
> > 
> > recreate.partition <- c(rep(1, length(cds_from_seurat@colData@rownames)))
> > names(recreate.partition) <- cds_from_seurat@colData@rownames
> > recreate.partition <- as.factor(recreate.partition)
> > 
> > cds_from_seurat@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partition
> > 
> > 
> > 
> > list_cluster <- try@active.ident
> > names(list_cluster) <- try@assays[["RNA"]]@data@Dimnames[[2]]
> > 
> > cds_from_seurat@clusters@listData[["UMAP"]][["clusters"]] <- list_cluster
> > 
> > 
> > 
> > cds_from_seurat@clusters@listData[["UMAP"]][["louvain_res"]] <- "NA"
> > 
> > 
> > cds_from_seurat@int_colData@listData$reducedDims@listData[["UMAP"]] <-try@reductions[["umap"]]@cell.embeddings
> > 
> > 
> > cds_from_seurat@preprocess_aux$gene_loadings <- try@reductions[["pca"]]@feature.loadings
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then perform pseudotime analysis:
> > ```
> > cds_from_seurat <- learn_graph(cds_from_seurat, use_partition = F)
> > 
> > plot_cells(cds_from_seurat, 
> >                    color_cells_by = 'cluster',
> >                    label_groups_by_cluster=TRUE,
> >                    label_leaves=FALSE,
> >                    label_branch_points=TRUE,
> >            graph_label_size=4)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope it will help. Good luck!
> 
> hi thanks for your great work. I have a small question. If im working on an integrated Seurat object, should I use 'integrated' instead of 'RNA' assay? Thank you.

Same Question in 2025...
```
gene_annotation <- data.frame(
  gene_short_name = rownames(try@reductions[["pca"]]@feature.loadings),
  row.names = rownames(try@reductions[["pca"]]@feature.loadings)
)
cell_metadata <- try@meta.data
New_matrix <- try@assays[["RNA"]]@layers$counts
New_matrix <- New_matrix[rownames(try@reductions[["pca"]]@feature.loadings), ]
```
Here it reported an error: 
```
Error in .subscript.2ary(x, i, , drop = TRUE) : subscript out of bounds
```
