### ISSUE TITLE
  Cannot find 'pca' in this Seurat object

### ISSUE THREAD

**Issue by MariamHakobyan95** [satijalab/seurat#2834]
I am going through the Satija Lab tutorial using the pbmc data set.
When trying to run the PCA, I am getting this:

Error in `[[.Seurat`(object, reduction) : 
  Cannot find 'pca' in this Seurat object

Oddly, I am getting the same error when running DimHeatmap with:
DimHeatmap(pbmc, dims = 1, cells = 500, balanced = TRUE)

I have already restarted the R session and re-installed Seurat. Nothing changes.
I am currently using the 3.1.4 version of Seurat. 
Would be grateful for any suggestions!

**Comment by yuhanH** [comment]
Hi, 
Could you provide more codes that you ran?

**Comment by bobilili** [comment]
I have encountered the same problem. Is there any solution？

**Comment by yuhanH** [comment]
hi, @bobilili 
could you post a reproducible example?
