### ISSUE TITLE
Is there a way to set alpha for DimPlot?

### ISSUE THREAD

**Issue by ahdee** [satijalab/seurat#2835]
Hi there does not seem to be an option for setting alpha for groups such as shape.by; I tried doing posthoc but it does not seem to work.  For example. 

```
tplot = DimPlot(main.integrated
, group.by = c("group" )
, combine = FALSE
, pt.size=1
, cols=c("#F8F8F8","red"))
tplot[[1]] +  scale_alpha_manual( values= c(.9,.001)) # this does nothing. 
```
using. 
Seurat_3.1.4

**Comment by ahdee** [comment]
found a solution. 
`tplot[[1]]$layers[[1]]$aes_params$alpha =  .1 `
to get it to plot by group then every pt needs to have  value so here is an example

`tplot[[1]]$layers[[1]]$aes_params$alpha =  ifelse ( main.integrated@meta.data$samples == "exp", 1, .5 )`

**Comment by JDB2191** [comment]
For anyone out there looking for another option, you can just make your own color palette and then call `alpha`, like so. Just make sure that the number of colors in 'my_cols' is greater than or equal to your number of groups.

```
library(RColorBrewer)
my_cols = brewer.pal(8,"Dark2")
tplot <- DimPlot(main.integrated, group.by='group',cols=alpha(my_cols,0.66),pt.size=1)
```

**Comment by dbtsshome** [comment]
> found a solution and posting in case some else needs this. `tplot[[1]]$layers[[1]]$aes_params$alpha = .1 ` to get it to plot by group then every pt needs to have value so here is an example
> 
> `tplot[[1]]$layers[[1]]$aes_params$alpha = ifelse ( main.integrated@meta.data$samples == "exp", 1, .5 )`

your answer is professional, but another guy offers another useful one.
