### ISSUE TITLE
Error using FindMarkers on integrated Seurat object with test.use = DESeq2

### ISSUE THREAD

**Issue by ph329** [satijalab/seurat#2836]
Hi, I have been using the FindMarkers function for a while with no issues. However it is now giving an error when I try to use it on an integrated Seurat object. I'm inputting a vector of cluster idents as ident.1, and want to search for markers upregulated in cells in those clusters compared to all other cells. Leaving ident.2 blank has always worked in the past, but now I'm getting this error: 

Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
  Cell group 2 is empty - no cells with identity class

I only get this error when using FindMarkers on an integrated object - if I try it on a normal Seurat object, leaving ident.2 blank, the function works fine. Any advice? Thank you!

Edit: this error seems to be specific to test.use = "DESeq2", as removing that parameter allows the function to run correctly.

**Comment by KinSimon96** [comment]
Hey,

If test.use is not set, it will automatically perform a Wilcoxon Rank Sum test.
This may be a dumb question, but have you installed the DESeq2 package ? (https://bioconductor.org/packages/release/bioc/html/DESeq2.html)

also try `test.use = "t"` or `test.use = "roc"`, it does not require packages, so you will see if your problem is specific to a test or not.

**Comment by mojaveazure** [comment]
@ph329, after running `IntegrateData`, the default assay is generally changed to `integrated` and the `counts` slot is empty in that. Can you provide the object, a subset of the object, or an example using one of the [SeuratData](https://github.com/satijalab/seurat-data) datasets that reproduces this error, including all code for processing, integration, and the call for `FindMarkers`
