### ISSUE TITLE
Use Seurat3 integration for cell cycle phases

### ISSUE THREAD

**Issue by YiqunCao** [satijalab/seurat#2837]
Hi Seurat team,

I tried the regression process to remove the cell cycle effect for the integrated assay (integration of patients), but the cell cycle effect was still quite strong. 
So I further split the data by cell cycle phases and applied seurat3 integration among the phases. The results showed that the cell cycle effect was nearly removed, much better than the regression one. 
I was wondering if there would be any concern about using Seurat3 integration for cell cycle phases. Would you have any comments? Thanks!

**Comment by satijalab** [comment]
The workflow you suggest is fine, you can see issue #2148 for a deeper discussion
