### ISSUE TITLE
Zoomin clustering

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#2840]
Hi, I used Seurat for my scRNA_seq data. I have now 12 different clusters. I want to zoom into two purple clusters in my clustering and down 3 big clusters for further analysis. 
[Plot12_UMAP_0.5_resolution.pdf](https://github.com/satijalab/seurat/files/4454908/Plot12_UMAP_0.5_resolution.pdf)

Should I start it from scratch for re_clustering?
I used these commands.
```
Subset_seurat <- SubsetData(object = All.data, ident.use = c(0,1,3), do.clean = TRUE)
Subset_seurat <- FindVariableFeatures(Subset_seurat , selection.method = "vst", nfeatures = 2000)
Subset_seurat  <- ScaleData(Subset_seurat , features = rownames(Subset_seurat ))
Subset_seurat  <- RunPCA(Subset_seurat , features = VariableFeatures(object = Subset_seurat ))
Subset_seurat <- FindNeighbors(Subset_seurat, dims = 1:10)
Subset_seurat <- FindClusters(Subset_seurat, resolution = 0.09)
Subset_seurat <- RunUMAP(Subset_seurat, dims = 1:10, min.dist = 0.65)
```
Please help me in this regard. Thanks in advance.

**Comment by KinSimon96** [comment]
If you subset by choosing indents (clusters), your selections will be "zoomed" in the `DimPlot()` function.

`purple_clusters <- subset(Subset_seurat, idents = c("9","10","11") )`
`DimPlot(purple_clusters)`

`3_big_clusters <- subset(Subset_seurat, idents = c("0","2","8") )`
`DimPlot(3_big_clusters)`

Once done, you can only work with the selected clusters, because they are in another Seurat object name (purple_clusters and 3_big_clusters)

Hope it helped.

**Comment by liuxl18-hku** [comment]
Was wondering which way is better:
* Re-do from scratch (scaling, dim reduct, clustering) on UMIs matrix for subset of cells in clusters we want to look into deeper.
* Keep original graph layout, but just increase resolution.

bless~

**Comment by sikh09** [comment]
> Was wondering which way is better:
> 
> * Re-do from scratch (scaling, dim reduct, clustering) on UMIs matrix for subset of cells in clusters we want to look into deeper.
> * Keep original graph layout, but just increase resolution.
> 
> bless~

Exactly this is my actual question. I also tried different approaches but still confused which way is the best.

**Comment by sikh09** [comment]
> If you subset by choosing indents (clusters), your selections will be "zoomed" in the `DimPlot()` function.
> 
> `purple_clusters <- subset(Subset_seurat, idents = c("9","10","11") )`
> `DimPlot(purple_clusters)`
> 
> `3_big_clusters <- subset(Subset_seurat, idents = c("0","2","8") )`
> `DimPlot(3_big_clusters)`
> 
> Once done, you can only work with the selected clusters, because they are in another Seurat object name (purple_clusters and 3_big_clusters)
> 
> Hope it helped.

It just gives the exact clusters. But I want to zoom into theses clusters and find sub-clusters into it. I hope you are getting my point now.

**Comment by andrewwbutler** [comment]
Hi @sikh09,

Yes, your approach of "starting from scratch" on the subset object is reasonable if you want to look for additional heterogeneity within specific clusters.
