### ISSUE TITLE
IntegrateData Is Removing Cells

### ISSUE THREAD

**Issue by hasuni-max** [satijalab/seurat#2843]
Hello,

I am trying to integrate my 4 samples currently. I am following the integrating vignette closely as a first pass. I am now noticing something strange. After integrating my data, it looks like thousands of cells from two of the samples are being thrown out while the other two are untouched. Looking at the documentation I can't find anything that would suggest this is something Integrating will do. 

More specifically, all I have done at this point is filter/normalize/findvariablefeatures separately on each data set. For filtering I just did the standard nFeature_RNA heuristic. I checked the number of cells after this step and majority of my dataset was still there. From there I used the FindIntegrationAnchors with default params. Lastly, I used IntegrateData. 

Link to vignette I am using:
https://satijalab.org/seurat/v3.1/immune_alignment.html

**Comment by timoast** [comment]
Can you provide the full code you're running?

**Comment by hasuni-max** [comment]
library(Seurat)
library(dplyr)
library(ggplot2)
library(rstudioapi)
library(cowplot)

options(future.globals.maxSize = 6000 * 1024^2)

clean_genes <- function(object){
  object.keep <- apply(object, MARGIN = 1, FUN = function(x){sum(x) > 2}) #filtering across samples
  cleaned_object <- object[object.keep,]
  
  return(cleaned_object)
}


f1 <- Read10X("")
f2 <- Read10X("")
m1 <- Read10X("")
m2 <- Read10X("")

#Remove genes with less than 2 counts across all cells. Tried Integration both with and without doing this. 
f1_clean <- clean_genes(f1) 
f2_clean <- clean_genes(f2)
m1_clean <- clean_genes(m1)
m2_clean <- clean_genes(m2)


f1.object = CreateSeuratObject(counts = f1, project = "F1") 
f2.object = CreateSeuratObject(counts = f2, project = "F2")
m1.object = CreateSeuratObject(counts = m1, project = "M1")
m2.object = CreateSeuratObject(counts = m2, project = "M2")

v1 <- VlnPlot(f1.object, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
v2 <- VlnPlot(f2.object, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
v3 <- VlnPlot(m1.object, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
v4 <- VlnPlot(m2.object, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
plot_grid(v1,v2,v3,v4)

f1.filtered <- subset(f1.object, subset = nFeature_RNA > 400 & nFeature_RNA < 6500 & nCount_RNA < 100000)
f2.filtered <- subset(f2.object, subset = nFeature_RNA > 400 & nFeature_RNA < 6500 & nCount_RNA < 100000)
m1.filtered <- subset(m1.object, subset = nFeature_RNA > 400 & nFeature_RNA < 6500 & nCount_RNA < 100000)
m2.filtered <- subset(m2.object, subset = nFeature_RNA > 400 & nFeature_RNA < 6500 & nCount_RNA < 100000)

v5 <- VlnPlot(f1.filtered, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
v6 <- VlnPlot(f2.filtered, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
v7 <- VlnPlot(m1.filtered, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
v8 <- VlnPlot(m2.filtered, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
plot_grid(v5,v6,v7,v8)


sample.list <- lapply(X=c(f1.filtered,f2.filtered,m1.filtered,m2.filtered), FUN = function(x){
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x,selection.method = "vst",nfeatures=2000)
})

sample.anchors <- FindIntegrationAnchors(object.list = sample.list,dims = 1:20)
sample.combined <- IntegrateData(anchorset=sample.anchors,dims=1:20)

DefaultAssay(sample.combined) <- "integrated"
#DefaultAssay(sample.combined) <- "RNA"


sample.combined <- ScaleData(sample.combined,verbose = FALSE)
sample.combined <- RunPCA(sample.combined,npcs = 30,verbose = FALSE)

brain.sample <- RunUMAP(sample.combined,reduction = 'pca',dims = 1:15)
brain.sample <- FindNeighbors(sample.combined,reduction = 'pca',dims=1:15)
brain.sample <- FindClusters(sample.combined,resolution = 0.6)

p1 <- DimPlot(sample.combined,reduction = 'umap',group.by = 'orig.ident')

**Comment by hasuni-max** [comment]
Sorry, it seems that it is now working. I cleaned out my R environment and re-ran everything and now cell counts is preserved. I must have been doing something without knowing. Closing this out.
