### ISSUE TITLE
Integrating Data vs Merging Data [Theoretical/Factual]

### ISSUE THREAD

**Issue by saisomesh2594** [satijalab/seurat#2844]
Hi,

I apologize if this is not the right thread to discuss conceptual questions. 

For experimental designs involving different conditions/treatments, etc. where each condition/treatment was sequenced separately (so separate count matrices), an integration approach of all the matrices from all of these covariates leads to a data where condition/treatment - specific differences are not clearly visible on the embedding (lets say when you do a `split.by` on a `DimPlot`) - Is that correct? (Because, integration acts as batch-corrector, I would expect to more uniformity across the batches)

On the other hand, when you do a simple aggregation or concatenation of counts from different conditions, the same condition/treatment - specific differences are strikingly visible on the embedding (cells are grouped by cell-types but clusters are split by treatment/condition).

For eg.,
![image](https://user-images.githubusercontent.com/22415829/79026393-fa1a0780-7b88-11ea-901b-cf3faa2ed931.png)

Could anyone explain why these differences arise? 

Thanks!

**Comment by timoast** [comment]
I think this is described extensively in the literature, but basically the difference between the batches can vary between different cell types.
