### ISSUE TITLE
Seurat2 and Seurat3 on the same machine

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2846]
Dear all, 

i'm looking forward to have you suggestions please, rather than reporting a bug. i'd appreciate if you could please let me know how could I have Seurat2 and Seurat3 on the same machine, and preferentially run either Seurat2 or Seurat3 ? I believe that I could use 2 docker containers, or is there another solution ? thanks a lot !

-- bogdan

**Comment by mojaveazure** [comment]
Asked and answered in https://github.com/satijalab/seurat/issues/2543#issuecomment-583448319
