### ISSUE TITLE
LabelCluster() & geom_text_repel()

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#2848]
Hi folks,

I am trying to use `LabelCluster()` to generate cluster labels which are matching color of corresponding cluster. Here is an example:

```
library(tidyverse)
library(SeuratData)
library(Seurat)

data("pbmc3k")

plot1 <- DimPlot(pbmc3k.final) + NoLegend()
LabelClusters(plot1, id = "ident", color = unique(ggplot_build(plot1)$data[[1]]$colour), size = 5, repel = T)

```
![Rplot](https://user-images.githubusercontent.com/49162517/79050234-ff2e9380-7c28-11ea-8a3b-fb0980ddd22a.jpeg)

However the labels are not well repeld. 

As mentioned in the Seurat documentation, `LabelCluster()` can be combined with  `geom_text_repel()` to generate nicely repeled cluster labels, but I am struggling with combining these two. I tried this: 

`LabelClusters(plot9, id = "ident", color = unique(ggplot_build(plot9)$data[[1]]$colour),  size = 5, repel = T) + geom_text_repel()
`

and this: 

`LabelClusters(plot9, id = "ident", color = unique(ggplot_build(plot9)$data[[1]]$colour),  size = 5, repel = T) + geom_text_repel(aes(x = plot9$data$UMAP_1, y = plot9$data$UMAP_2, label = plot9$data$ident))`

unfortunately both were not valid. Can you please provide help.

Thank you in advance.
Amel Zulji

**Comment by andrewwbutler** [comment]
Hi,

The `repel` argument is already specifying whether to use `geom_text_repel`. This will ensure that the labels aren't overlapping with each other but doesn't push them into empty space w.r.t the points. You can pass additional parameters to `geom_text_repel` (see the help documentation for that for details). This may get you closer to what you want. For example:

```R
plot1 <- DimPlot(pbmc3k.final) + NoLegend()
LabelClusters(plot1, id = "ident", color = unique(ggplot_build(plot1)$data[[1]]$colour), size = 5, repel = T,  box.padding = 1)
```

**Comment by AmelZulji** [comment]
Thank you, Andrew!
