### ISSUE TITLE
computing CONSERVED and DIFFERENTIAL MARKERS on SAMPLES that do not ALIGN

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#2849]
Dear all, 

here if I may ask for a suggestion please : shall I have 2 scRNA-seq samples that do not align too well  by using either CCA (in Seurat2) or Seurat3 methods, the calculation of the CONSERVED MARKERS or DIFFERENTIAL MARKERS likely fails on the cell clusters that do not align. 

how could I still compute the CONSERVED or DIFFERENTIAL MARKERS on the cell clusters that align (in some extent) ? Many thanks for your suggestions; stay safe, stay healthy, 

-- bogdan

**Comment by satijalab** [comment]
You can run FindMarkers and FindConservedMarkers on any dataset, regardless of the quality of alignment. However, as you suggested, if there is no alignment, it is likely that there will not be conserved markers.
