### ISSUE TITLE
About Seurat dependency

### ISSUE THREAD

**Issue by pengyubio** [satijalab/seurat#2850]
I don't want to install miniconda. Is it required to install miniconda in order to use Seurat? Can the python dependency be separated into a different package?

```
R> library(Seurat)
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
sh: line 1: 91390 Abort trap: 6           '/Users/xxx/.virtualenvs/yyy/bin/python' "/Users/xxx/Library/R/3.6/library/reticulate/config/config.py" 2> /dev/null
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘multtest’
In addition: Warning message:
In system2(command = python, args = paste0("\"", config_script,  :
  running command ''/Users/xxx/.virtualenvs/yyy/bin/python' "/Users/xxx/Library/R/3.6/library/reticulate/config/config.py" 2>/dev/null' had status 134
R> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘multtest’
```

**Comment by mojaveazure** [comment]
Miniconda is not required by Seurat for installation. This is an option from the reticulate package, which, for some reason, offers to install Miniconda when loading (sometimes, not every time). We strongly encourage you to **not** install Miniconda as it messes with a lot of R. If you do choose to install Miniconda and run into problems with Seurat, we will ask that you remove Miniconda and all other Condas from your system before continuing to debug Seurat.

Currently, we use Python/reticulate for a few core functions in Seurat. We are looking at replacing such functionality with R-native implementations as they become available.

**Comment by pengyubio** [comment]
What about the error of `multtest`?

**Comment by evanbiederstedt** [comment]
CC @mojaveazure 

I was confused by this prompt as well. It's a bit annoying, as I'm not a fan of `Miniconda`

I haven't looked deeply at this, but you mention that this could be related to reticulate. 

https://rstudio.github.io/reticulate/

> By default, reticulate uses the version of Python found on your PATH (i.e. Sys.which("python")).

Well, I get either `"/usr/local/bin/python" ` or `"/Users/evanbiederstedt/.pyenv/shims/python" `, the latter of which is using `pyenv` to manage python versions. https://github.com/pyenv/pyenv

In any sense, it's a prompt which should be removed somehow. I'm happy to help out, if you could point me in the right direction---I haven't looked closely yet.

**Comment by JenniferWUSTL** [comment]
@mojaveazure Can you elaborate on what things can go wrong with having miniconda on your system? Is it some dependency issue or does it change my analysis (like pvalues, counts etc)?

**Comment by MarcJung** [comment]
I am somewhat dependent on using miniconda next to R, I would be interested to know how this can mess with R as well and which functions in Seurat are currently still impacted.
