### ISSUE TITLE
How to indirectly call gene name within 'subset' function

### ISSUE THREAD

**Issue by cpcook1** [satijalab/seurat#2851]
I'm trying to perform a number of subsets within a loop, and I thought the easiest way would be to make gene list and call the index within the subset function but it doesn't work.

For example: I tried the following 3 methods:

```
gene.list <- c("Ccl1", "Ccl2", "Ccl3", "Ccl4", "Ccl5")

Sample <- subset(Data, gene.list[1] > 0)
Sample <- subset(Data, `gene.list[1]` > 0)
Sample <- subset(Data, "gene.list[1]" > 0)
```

All of which return the error:
```
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells,  : 
  None of the requested variables were found:
```

I couldn't think of another way to call the gene name with an index number besides these methods. Have I overlooked something or is it not possible with this function?

If its not possible could you recommend a method to try to subset the cells in this manner?

Thanks so much and I really appreciate all of these wonderful tools

-Chris

**Comment by mojaveazure** [comment]
Please see https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002
