### ISSUE TITLE
Installation of package 'Seurat' had non-zero exit status

### ISSUE THREAD

**Issue by BarvauxS** [satijalab/seurat#2857]
I try for several hours to install the package "Seurat" but no way ... I am using R on an HPC cluster.

I have started with : 

Install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('Seurat')

and I have these 3 errors : 

In install.packages('Seurat') : 
Installation of package 'Rtsne' had non-zero exit status 
Installation of package 'cluster' had non-zero exit status 
Installation of package 'Seurat' had non-zero exit status

I tried to install these indenpedently (with install.packages('...') or BiocManager::install('...')) but each time I try, I have the same error message ...

Can someone help me ?

**Comment by mojaveazure** [comment]
If you're having issues installing Rtsne or cluster, you'll need to bring it up with the authors of those packages. Once you have all dependencies installed, try installing Seurat again. If it still doesn't work after installing all dependencies successfully, then open a new issue.
