### ISSUE TITLE
Mac FindClusters problem

### ISSUE THREAD

**Issue by sidichen** [satijalab/seurat#286]
Hi Seurat experts, we've got a problem when testing FindClusters. can you help? thank you.

tried different datasets, install/uninstall R/Rstudio/Java, put in a new folder, restart etc, still exist. 

```R
####
> pbmc <- FindClusters(object = pbmc, reduction.type = "pca", dims.use = 1:10, 
+                      resolution = 0.6, print.output = 0, save.SNN = TRUE)
No Java runtime present, requesting install.
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/var/folders/x9/w26vb_mj4kz52gnd6klr8vzc0000gp/T//Rtmp4eqC9e/file2684134ced6_output_33200.txt': No such file or directory
```

**Comment by bc2zb** [comment]
You need to install the java development kit, not just java. Install JDK from [here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
