### ISSUE TITLE
DEG with sct transform / covariates

### ISSUE THREAD

**Issue by loverend** [satijalab/seurat#2861]
Hi, 
Its been a while since I have seen any discussion regarding using pearson residuals from SCT transform for DEG. I know currently it states this is not supported and previous posts (from 2019) suggest it was coming soon but I haven't seen any updates. Are there any issues with for example setting the assay within FindAllMarkers and slot scale.data to force it to use residuals rather than corrected counts? 
e.g.
merged_data_pdac.markers <- FindAllMarkers(merged_data_pdac, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, assay='SCT', slot='scale.data')

Further more, do you support any DEG which would consider orig.ident as a co-variate? For context, I have normalised 6 data sets independently with SCT, used your SelectIntegrationMarkers, merged into one large object and then used these as integration features to integrate my data sets with using harmony (I was running out of memory with SCTintegrate - 50k cells). My understanding is therefore my pearson residuals will still have a batch effect that would need to be considered in some kind of regression model.  

Thank you,

**Comment by satijalab** [comment]
Please see #2899 and stay tuned for more info
