### ISSUE TITLE
Question about DataTransfer for Spatial Transcriptomics

### ISSUE THREAD

**Issue by mchernys** [satijalab/seurat#2862]
Hello, 

I am following the spatial vignette on how to infer cell types for spatial transcriptomics data, and I was wondering if I could get a bit more context on what the output of the cell type prediction means. From what I understand, the scores for each cell type are obtained with a weighted vote classifier. Would it be reasonable to interpret these scores as relative abundances of cell types?  

Thank you very much!

**Comment by andrewwbutler** [comment]
Hi,

Yes, the scores are obtained from what is essentially a weighted vote classifier but I would be cautious in interpreting them as relative abundances. Intuitively, the prediction score and the relative abundances are likely pretty correlated but we're not explicitly trying to solve a deconvolution problem with the label transfer procedure, just give a prediction for what class we think a spot/cell/bead should belong to.
