### ISSUE TITLE
Error in DoHeatmap – no labelling of identities above colourbar possible

### ISSUE THREAD

**Issue by hartmannmark** [satijalab/seurat#2864]
Hello,

I try to generate a heatmap just as it is explained in this vignette:
https://satijalab.org/seurat/v3.1/interaction_vignette.html

It works, when I turn off the labelling

```
DoHeatmap(CB, 
          features = unlist(TopFeatures(CB[["pca"]], balanced = TRUE)), 
          group.by = "predicted.id", 
          label = FALSE)
```

However, when I apply the default setting or label= TRUE, respectively, I get the following error message:

```
Error in data.frame(group = sort(x = group.use), x = x.divs) : 
  arguments imply differing number of rows: 22727, 0
```

This seems strange to me because the legend shows the correct labels (identity), but I cannot label the colour bar as such.
I tried and tried, but I cannot figure out the problem... Any ideas? 

Thanks in advance!

**Comment by timoast** [comment]
I think this is related to a few other previous issues (https://github.com/satijalab/seurat/issues/2399, https://github.com/satijalab/seurat/issues/2320, https://github.com/satijalab/seurat/issues/2722) that seem to be related to running DoHeatmap with SCTransformed data. Are you using SCTransform here too? Can you update Seurat (new version was released yesterday) and all the dependencies and check if you still see the same error?

**Comment by hartmannmark** [comment]
I did not use SCTransform, but still the update worked. (Or it's been the re-start of R, who knows... ;.))
