### ISSUE TITLE
Gene symbols instead of ENSEMBL IDs

### ISSUE THREAD

**Issue by hartmannmark** [satijalab/seurat#2865]
Hello,

We use ENSEMBL IDs for the features to avoid ambiguity of gene names in the analyses.

However, for quick biological revisions gene names / symbols are much more suitable for a biologist.

Is there a way to use gene names instead of ENSEMBL IDs for Featureplots, Heatmaps, Ridgeplots etc.?

In 2018, you said that this wasn't supported at that time. Is it now? Or how can I explicitly work around this problem?
https://github.com/satijalab/seurat/issues/625

Thanks in advance!

**Comment by mojaveazure** [comment]
Seurat supports feature-level metadata on the `Assay` level rather than the `Seurat` level. For more details about adding to and using feature-level metadata, please see https://github.com/satijalab/seurat/issues/2855#issuecomment-614733444

As for using alternate IDs for labels, we don't currently have that ability in Seurat. You can either use gene symbols from the beginning (before making your `Seurat` object) or change the labels yourself with ggplot2

**Comment by hartmannmark** [comment]
I'm sorry, but I do not manage to solve the problem...

When I apply e.g. ggtitle to a multi feature plot, the title of only one of the three, the last plot is changed and the other two remain as ensembl IDs.

`FeaturePlot(seuratobject, features=c("ENSG00000135318", "ENSG00000138185", "ENSG00000131203")) + ggtitle(c("NT5E", "ENTPD1", "IDO1"))`

Can anybody help here, please?

Thanks in advance!

**Comment by hartmannmark** [comment]
Still having problems with editing Seurat plots...

I am trying to add gene symbols by using vector names. It works partially as it at least puts the symbols as names on top of the columns of a dotplot. 

But unfortunately it automatically splits the plot, I guess applying names automatically groups the gene list.

```
data.4 <- c("ENSG00000182568", "ENSG00000140968", "ENSG00000124813") 
names(data.4) <- c("SATB1", "IRF8", "RUNX2") 

DotPlot(object = obj, 
        features = data.4,
        cols = c("lightgrey", "darkred"), 
        scale.by = "size", 
        scale.min = 0,
        scale.max = 100) +
  theme(axis.text.x = element_text(angle = 90))
```

For the FeaturePlot function the vector names do not make any difference...
 
Would be great to get a hint how to solve this or even better to realy exchange the ENSEMBL IDs by symbols!


[Example.pdf](https://github.com/satijalab/seurat/files/5561562/Example.pdf)

**Comment by hartmannmark** [comment]
> Still having problems with editing Seurat plots...
> 
> I am trying to add gene symbols by using vector names. It works partially as it at least puts the symbols as names on top of the columns of a dotplot.
> 
> But unfortunately it automatically splits the plot, I guess applying names automatically groups the gene list.
> 
> ```
> data.4 <- c("ENSG00000182568", "ENSG00000140968", "ENSG00000124813") 
> names(data.4) <- c("SATB1", "IRF8", "RUNX2") 
> 
> DotPlot(object = obj, 
>         features = data.4,
>         cols = c("lightgrey", "darkred"), 
>         scale.by = "size", 
>         scale.min = 0,
>         scale.max = 100) +
>   theme(axis.text.x = element_text(angle = 90))
> ```
> 
> For the FeaturePlot function the vector names do not make any difference...
> 
> Would be great to get a hint how to solve this or even better to realy exchange the ENSEMBL IDs by symbols!
> 
> [Example.pdf](https://github.com/satijalab/seurat/files/5561562/Example.pdf)

This can be used applying the ggplot2 `scale_x_discrete()` function:
```  
data.4 <- c("ENSG00000182568", "ENSG00000140968", "ENSG00000124813") 
data.4.names <- c("SATB1", "IRF8", "RUNX2") 
DotPlot(object = obj, 
        features = data.4,
        cols = c("lightgrey", "darkred"), 
        scale.by = "size", 
        scale.min = 0,
        scale.max = 100) +
  theme(axis.text.x = element_text(angle = 90)) +
scale_x_discrete(labels = data.4.names)
```
However, this does not work with the split.by function. In each column of the split plot, the gene naming starts again from the beginning... :-( 

Any ideas why this happens?

**Comment by hartmannmark** [comment]
> As for using alternate IDs for labels, we don't currently have that ability in Seurat. You can either use gene symbols from the beginning (before making your `Seurat` object) or change the labels yourself with ggplot2

Meanwhile, is this possible? 

It is very inconvenient when exploring e.g. PCs where I do not have the genes a priori... Would be good to be able to change the IDs to symbold for DimHeatmap etc.!
