### ISSUE TITLE
Caution:  Factors vs character in "meta.data" between Seurat v3 vs v2

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#2867]
Hi there,

I discovered this the hard way.  Seurat 3 stores the cluster IDs in meta.data as factors, whereas in older Seurat versions, those were stored as "character".  Using factors in Seurat 3 for meta.data seems to have the unintended consequence of incrementing the actual cluster IDs somehow by 1 when extracting the meta.data columns into another variable.  I had the following situation:

After clustering, I want to separately take out the cluster IDs along with the cell names for other processing in my code from the meta.data.  I used to do this like this in Seurat v2:

`sep_ClustIDs <- data.frame(Sep.ClustIDs=c(pbmc1@meta.data$res.0.4, pbmc2@meta.data$res.0.4))`

which worked as intended.  However, when I do the same thing in Seurat 3:

`sep_ClustIDs <- data.frame(Sep.ClustIDs=c(pbmc1@meta.data$RNA_snn_res.0.4, pbmc2@meta.data$RNA_snn_res.0.4))`

the extracted cluster IDs suddenly are incremented by 1.  What I mean by this is that all cluster 0 labels are now cluster 1, and so on!

In effect, in Seurat 2, the meta.data column was a character:

`str(pbmc1@meta.data$res.0.4)
 chr [1:5079] "0" "0" "4" "3" "2" "1" "2" "2" "1" "0" "0" "0" "5" "4" "2" ...`

But in Seurat 3, this is a factor, like this:

`str(pbmc1@meta.data$RNA_snn_res.0.4)
 Factor w/ 7 levels "0","1","2","3",..: 1 1 5 4 3 ...`

So, when I create a data frame as above, something weird happens.

So, to avert this, I am now doing `as.character()` when creating the data frame.  Is this the right way to do it, or is there a better way?

Thanks for any responses!

**Comment by timoast** [comment]
When you concatenate factors in R they'll be converted to integers (see https://stackoverflow.com/questions/3443576/how-to-concatenate-factors-without-them-being-converted-to-integer-level)

A simpler solution if you want to combine metadata from two objects in a dataframe with the same column is:

```r
pbmc2 <- pbmc_small
rbind(data.frame(res08=pbmc_small$RNA_snn_res.0.8), data.frame(res08=pbmc2$RNA_snn_res.0.8))
```
