### ISSUE TITLE
Loading cell counts csv file into seurat object

### ISSUE THREAD

**Issue by manukrishnamurthy** [satijalab/seurat#2869]
Hi, I have a cell counts csv file that looks like this 
![cell counts file](https://user-images.githubusercontent.com/36338922/79501482-1b9d4800-7ffc-11ea-96c1-d88e4949dc81.JPG)
And I'm trying to load it into a seurat object as the counts parameter. I've tried the following 2 ways 
`countsData<-read.delim(file = "Thalamus\\Single_cell\\thal_singlecell_counts.csv", header = TRUE, sep = ",")`
`pbmc <- CreateSeuratObject(counts = countsData, project = "thal_single_cell", min.cells = 3, min.features = 200)`

and 
`countsData<-read.csv("Thalamus\\Single_cell\\thal_singlecell_counts.csv", header = TRUE)`
`pbmc <- CreateSeuratObject(counts = countsData, project = "thal_single_cell", min.cells = 3, min.features = 200)`
But when I run the line 
`pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")`
I get the following error
`Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  no 'dimnames[[.]]': cannot use character indexing`
Running `all(genes_list %in% rownames(integrated))` results in 
`Error in genes_list %in% rownames(integrated) : 
  object 'genes_list' not found`
Why is this happening and how can I fix it?
Thanks

**Comment by timoast** [comment]
It looks like your matrix is transposed, `CreateSeuratObject` expects features in the rows and cells in the columns. You should run `t(countsData)` before creating the object

**Comment by Romhop** [comment]
hello,i have met the same question ,have you resolved this problem?
