### ISSUE TITLE
Cluster Separation on different conditions

### ISSUE THREAD

**Issue by KBoostan** [satijalab/seurat#2870]
Hi there, 
I am trying to separate the early and late stage of a disease progression on a TSNE plot using dimensional reduction and label transfer. I have tried using SCT Transform, but the early and late stage of the disease don't seem to separate out properly, instead overlapping with each other. Is there something that I'm doing wrong when applying label transfer methods? 
![Screen Shot 2020-04-16 at 3 16 13 PM](https://user-images.githubusercontent.com/54972577/79512158-b181a480-7ff5-11ea-96af-13b1c27987d8.png)
![Screen Shot 2020-04-16 at 3 18 35 PM](https://user-images.githubusercontent.com/54972577/79512287-f9083080-7ff5-11ea-85c0-44e367e8c07c.png)
![Screen Shot 2020-04-16 at 3 18 46 PM](https://user-images.githubusercontent.com/54972577/79512312-06251f80-7ff6-11ea-97a5-f275b538d314.png)
![Screen Shot 2020-04-16 at 3 18 55 PM](https://user-images.githubusercontent.com/54972577/79512324-0e7d5a80-7ff6-11ea-85e7-c4352554f621.png)
![Screen Shot 2020-04-16 at 3 19 06 PM](https://user-images.githubusercontent.com/54972577/79512336-13daa500-7ff6-11ea-9e69-7f601f3585ce.png)

**Comment by timoast** [comment]
Can you post the full code you're running (not screenshots)?

**Comment by KBoostan** [comment]
Early1.data <- Read10X(data.dir = "../kaveh/Documents/Early1/filtered_gene_bc_matrices/mm10/")
Early1 <- CreateSeuratObject(counts = Early1.data, project = "Early1", min.cells = 3, min.features = 200)
Early2.data <- Read10X(data.dir = "../kaveh/Documents/Early2/filtered_gene_bc_matrices/mm10/")
Early2 <- CreateSeuratObject(counts = Early2.data, project = "Early2", min.cells = 3, min.features = 200)
Disease1.data <- Read10X(data.dir = "../kaveh/Documents/Late Disease 1/filtered_gene_bc_matrices/mm10/")
Disease1 <- CreateSeuratObject(counts = Disease1.data, project = "Disease1", min.cells = 3, min.features = 200)
Disease2.data <- Read10X(data.dir = "../kaveh/Documents/Late Disease 2/filtered_gene_bc_matrices/mm10/")
Disease2 <- CreateSeuratObject(counts = Disease2.data, project = "Disease2", min.cells = 3, min.features = 200)
Disease3.data <- Read10X(data.dir = "../kaveh/Documents/Late Disease 3/filtered_gene_bc_matrices/mm10/")
Disease3 <- CreateSeuratObject(counts = Disease3.data, project = "Disease3", min.cells = 3, min.features = 200)
CD45Int <- merge(EarlyTot, y = c(DiseaseTot))
add.cell.ids = c("EarlyTot", "DiseaseTot")
groups <- sample(c("EarlyTot", "DiseaseTot"), size = 33316, replace = TRUE)
names(groups) <- colnames(CD45Int)
CD45Int <- AddMetaData(object = CD45Int, metadata = groups, col.name = "group")
CD45Int[["percent.mt"]] <- PercentageFeatureSet(CD45Int, pattern = "^MT-")
C45Int <- SCTransform(CD45Int, vars.to.regress = "percent.mt", verbose = FALSE)
CD45Int <- RunPCA(CD45Int)
CD45Int <- FindNeighbors(CD45Int, dims= 1:10)
CD45Int <- FindClusters(CD45Int, resolution = 0.5)
CD45Int <- RunTSNE(CD45Int)
DimPlot(CD45Int, reduction = "tsne", normalization.method = "SCT", group.by = "group")

**Comment by timoast** [comment]
Here you're just randomly assigning the label "EarlyTot" and "DiseaseTot", it's not related at all to the experiment the cell originated from

**Comment by KBoostan** [comment]
Sorry EarlyTot and DiseaseTot refers to the combination of all the early experiments and all the late experiments, which I saved in the global environment so it's not in the code. Are there any suggestions about how to assign the labels to the actual experiment?

**Comment by timoast** [comment]
Here you're assigning randomly the different groups (`groups <- sample(c("EarlyTot", "DiseaseTot"), size = 33316, replace = TRUE)`), and it's also in the screenshot above, and it's also clear from that tSNE that they're random, so not sure what you mean that it's not in the code

To assign labels correctly just add them before merging the data:

```r
EarlyTot$group <- "early"
DiseaseTot$group <- "disease"
```

**Comment by KBoostan** [comment]
EarlyTot$group <- "early"
DiseaseTot$group <- "disease"
CD45Int <- merge(EarlyTot, y = c(DiseaseTot))
CD45.list <- SplitObject(CD45Int, split.by = "group")
CD45.list <- CD45.list[c("EarlyTot", "DiseaseTot")]

Thank you, I've been trying different ways to write this code but I still seem to be running into the same problem; was this what you meant by labelling before merging the data?

**Comment by KBoostan** [comment]
Nevermind I got it; thank you so much!
