### ISSUE TITLE
Getting barcode.tsv.gz from .Rdata

### ISSUE THREAD

**Issue by ralzabey** [satijalab/seurat#2871]
I currently have this code to load .Rdata, and read it using Read10X. However, I get the "Barcode file missing. Expecting barcodes.tsv.gz". Any help is greatly appreciated

<img width="428" alt="Screen Shot 2020-04-16 at 7 57 13 PM" src="https://user-images.githubusercontent.com/63824570/79517532-78a8f600-801c-11ea-8171-49f0a54349a7.png">

**Comment by samuel-marsh** [comment]
Hi,

`Read10X` function is specifically meant for reading the output of the Cell Ranger pipeline.  It looks like you have RData file which contains a Seurat object.  You should just be able to read that object in and start your analysis from there.

Best,
Sam

**Comment by ralzabey** [comment]
Hi Sam,

Thank you for getting back to me! Do you know how I can read the object to start the analysis? 

Best,
Roze

**Comment by timoast** [comment]
As Sam said, `Read10X` is for reading the output of cellranger. Here you've already loaded the Seurat object (called `dat1`), so you're good to go.
