### ISSUE TITLE
Is it possible to identify a subset of cells based on expression, and label them in the larger object without accually subsetting?

### ISSUE THREAD

**Issue by cpcook1** [satijalab/seurat#2872]
I want to identify two groups of cells within a dataset. One subset has High expression of a gene above 3, the other is the subset of all cells that have no expression of that gene. But I would like to tag this group within the dataset that I subsetted them form rather than accually subset them.

For example if i wanted to create a single object of these groups of cells I would do this:
```
Expr <- FetchData(Object = Dataset, vars = "Ccr1")
  High.Ccr1 <- Dataset[, which(x = Expr > 3)]
  Zero.Ccr1 <- Dataset[, which(x = Expr == 0)]

High.Ccr1$exp <- "high"
Zero.Ccr1$exp <- "zero"

Dataset.Ccr1 <- merge(x = High.Ccr1, y = Zero.Ccr1)
```
If I do this I can run a DEG against these two groups using Dataset.Ccr1

But what I would like to do is label these two groups within the larger Dataset at Dataset$exp = "high" or "zero" and run the DEG using the larger Dataset object by calling idents high and low instead of subsetting out the two groups and merging them

Is this possible? Thanks so much for any insight into this problem

**Comment by timoast** [comment]
Yes, you just need to assign some new metadata based on the classifications you want to make. For example:

```r
pbmc_small$MS4A1_high <- GetAssayData(pbmc_small, "data")["MS4A1", ] > 2
```
