### ISSUE TITLE
Filtering mitochondrial counts from vignette "Integrating stimulated vs. control PBMC datasets" #3.1

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#2873]
I am working to integrate two datasets from different conditions using your vignette "Integrating stimulated vs. control PBMC datasets" #3.1
Following step by step guidelines I was able to analyze my data. However, I do not see any step where it filters cells that have mitochondrial counts.

I was wondering how can I filter mitochondrial count from vignette "Integrating stimulated vs. control PBMC datasets" #3.1.

Thank you

**Comment by samuel-marsh** [comment]
Hi,

You should be able to filter the same way you would any Seurat object.
i.e. from [https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html)
`pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)`

Best,
Sam
