### ISSUE TITLE
None of the requested features were found:

### ISSUE THREAD

**Issue by jdime** [satijalab/seurat#2874]
Hello,
I've found similar error reports but not the same that I'm reporting here.
I'm using Seurat v3.1.1, and I can't get `FeaturePlot()` to plot any feature. However, I know the features exist in the object, because if I call `GetAssayData()` immediately after the failed `FeaturePlot()` call, I get the data. What may be wrong?

This is the error that I'm getting:

> seurat.object.each_dataset_type.sa
> An object of class Seurat 
> 29745 features across 7509 samples within 1 assay 
> Active assay: RNA (29745 features)
>  2 dimensional reductions calculated: umap, tsne

> FeaturePlot(object = seurat.object.each_dataset_type.sa, features = "A1CF", slot = "data")
> **Error: None of the requested features were found: A1CF in slot data**

> GetAssayData(object = seurat.object.each_dataset_type.sa, slot = "data")["A1CF",1:3]
> LV_1_tx_AAACCTGAGCCCGAAA LV_1_tx_AAACCTGCAGAAGCAC LV_1_tx_AAACCTGGTTGGACCC 
>                        0                        0                        0 

> rownames(seurat.object.each_dataset_type.sa)[1:5]
> [1] "A1BG"   "A1CF"   "A2ML1"  "A4GALT" "AAAS"

**Comment by timoast** [comment]
Can you provide the full code you're running to create the object, and the output of sessionInfo()?

**Comment by jdime** [comment]
Hello @timoast,

This was part of a big script where I integrate datasets and then subset counts and UMAP/TSNE coordinates from the integrated datasets object to call FeaturePlot() at two levels:
1) for each individual dataset used for the integration and
2) for each "dataset type" (either controls or treatments).

As I was preparing the relevant part of the script to show you I found out what the problem was. I was getting the read counts correctly from the RNA slot "data" for each dataset and for each 'dataset type'. But, incorrectly, I was subsetting the UMAP/TSNE coordinates only for some cells for each dataset and the Error referred to that.

Thanks for your time.

J.
