### ISSUE TITLE
Different vars.to.regress, same output

### ISSUE THREAD

**Issue by akramdi** [satijalab/seurat#2875]
Hi everyone, 

I have tested two parameters of normalization starting from the same seurat object and I am getting identical results which I did not expect:

```
#sctransform_0.2.1 
#Seurat_3.1.4

#original seurat object
#sobj.ori
#17160 features across 6630 samples within 1 assay 

#----------------------------normalize for MT only
sobj.mt <- SCTransform(object = sobj.ori, vars.to.regress = "percent.MT", verbose = FALSE)
sobj.mt 
#33013 features across 6630 samples within 2 assays 
#Active assay: SCT (15853 features)
#1 other assay present: RNA

#----------------------------normalize for multiple covariates
sobj.full <- SCTransform(object = sobj.ori, vars.to.regress =  c("nFeature_RNA","nCount_RNA", "percent.MT"), verbose = FALSE)
sobj.full 
#33013 features across 6630 samples within 2 assays 
#Active assay: SCT (15853 features)
#1 other assay present: RNA

````

The normalized coverage output is identical for both types of normalizations, I've further checked this by computing the normalized cell coverage from the SCT assay (counts slot):

```
x=colSums(as.matrix(GetAssayData(object = sobj.full, assay='SCT', slot = 'counts')))
y=colSums(as.matrix(GetAssayData(object = sobj.mt, assay='SCT', slot = 'counts')))
ylab="MT.Norm.SCT.counts"
xlab="full.Norm.SCT.counts"
plot(x,y, xlab=xlab,ylab=ylab, pch=16, main="Normalized cell coverage")
```

![SCT-assay count-slot nCount](https://user-images.githubusercontent.com/8793228/79598858-eae50d80-80e4-11ea-81b3-7b3ea34ff46c.png)

I was expecting at least some differences/effect... What am I missing here?

--
Also, when deciding which slot to chose for my tests, I went back to wiki page about slots (https://github.com/satijalab/seurat/wiki/Assay#slots) and, based on the definitions, I was wondering if it would be correct to extract the normalized count matrix with:

`GetAssayData(object = sobj, assay='RNA', slot = 'data')`

Many thanks in advance!

**Comment by timoast** [comment]
Here you should compare the `scale.data` rather than `counts`

**Comment by akramdi** [comment]
Thank you for the quick reply. I've just realised that this was kind of answered in #1775

> It is not meaningful to plot nFeature_RNA vs nFeature_SCT, so I would not worry about these results. The true output of SCT is stored in the scale.data slot, and can be positive or negative. The UMI corrected values are primarily meant for the convenience of visualization (for example, drawing violin or Feature plots).

I'm still curious about the identical values in `counts`. This slot contains the corrected values that will be used for visualization (as mentioned above). In my case, the cell coverage appears to be the same before/after normalization which is misleading when we want to test if the normalization worked by visualization. Do you have any comment on this?
Thanks!
