### ISSUE TITLE
List of highly dysregulated genes across conditions in a particular cluster

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#2876]
I am trying to integrate two datasets from different conditions using Seurat vignette "Integrating stimulated vs. control PBMC datasets" #3.1
 I wanted to Identify highly dys-regulated genes or highlighting genes that exhibit dramatic responses across conditions in a particular cluster.

For example, in the scatter plots below dots further away from line are dysregulated (exhibit dramatic responses) but I need to supply the list of genes to label those outlier point (_genes.to.label_). 

**My question is**, Is there any way to label those outlier DOTS  without knowing identity of those dots  beforehand or to determine the list of genes belonging to a cluster that are exhibiting dramatic responses between two treatment conditions.

<img width="739" alt="Screen Shot 2020-04-17 at 3 30 31 PM" src="https://user-images.githubusercontent.com/61842606/79611960-561ce880-80c1-11ea-8132-06622ac8d016.png">

Thank you

**Comment by satijalab** [comment]
You can find differentially expressed genes using FindMarkers to identify genes that are differentially expressed within the same cluster, across conditions (the vignette includes an example of how to do this)
