### ISSUE TITLE
Individual cluster's Feature_RNA, nCount_RNA and percentage of MT

### ISSUE THREAD

**Issue by bsun-bo** [satijalab/seurat#2877]
Hi Seurat Group,

I am quite new here. Is there a way to check the individual cluster's nFeature_RNA, nCount_RNA and percentage of MT? 

Very appreciate for your help:)

Regards,
Bo

**Comment by KinSimon96** [comment]
Hello,

Follow the steps available [here](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html). Once you've performed the umap, rerun this part of code:

`VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)`

It will display what you want for each cluster.

**Comment by bsun-bo** [comment]
Thank you, Simon! It works very well:)
