### ISSUE TITLE
I am getting warning  like this  argument not  used 

### ISSUE THREAD

**Issue by Hemantcnaik** [satijalab/seurat#2878]
>dat[["percent.ERCC"]] <-PercentageFeatureSet(dat, pattern="^ERCC")

>dat <- ScaleData(dat, vars.to_regress="percent.ERCC")
Warning: The following arguments are not used: vars.to_regress

can you please explain  me  why  am  getting this warning

**Comment by KinSimon96** [comment]
Seems like it is `vars.to.regress` instead of `vars.to_regress`
`dat <- ScaleData(dat, vars.to.regress="percent.ERCC")`

It should work.

Best,
Simon
