### ISSUE TITLE
DotPlot vector error with top genes

### ISSUE THREAD

**Issue by atflores** [satijalab/seurat#2879]
Hello, I am trying to make a DotPlot with the top genes but am getting an error message:

markers <- FindAllMarkers(data, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
top7genes <- markers %>% group_by(cluster) %>% top_n(n = 7, wt = avg_logFC) %>% pull(gene)
DotPlot(data, features = top7genes)

Error in names(x) <- value : 
  'names' attribute [112] must be the same length as the vector [110]

Can you please advise on how to resolve this error? Many thanks-

**Comment by liuxl18-hku** [comment]
You can check whether there are duplicates in your top7genes and try to remove duplicates:

```r
which(duplicated(top7genes))
DotPlot(data, features = unique(top7genes))
```

bless~
