### ISSUE TITLE
how to  save the feature plot data

### ISSUE THREAD

**Issue by Hemantcnaik** [satijalab/seurat#2880]
hello seurat

great work, i was following the tutorial, my main objective to cell segregation according to marker gene. successfully ran i want to save csv file off featureplot data culteres, 
FeaturePlot(pbmc, features = c("MS4A1", "GNLY", "CD3E", "CD14", "FCER1A")

**Comment by KinSimon96** [comment]
If I undersrtood well, you want to put ID to cells according to specific markers.
For that, it is rather easy:

1) Put resolution to 0.0001 in findcluster() function. It will tell you that all of your cells are included in one general cluster

2) Rename cells according to specific markers

`MS4A1_marker <- WhichCells(object = pbmc, expression = MS4A1 > 0.5)
`
```
pbmc <- SetIdent(object = pbmc, cells = MS4A1_marker , value =
'MS4A1 positive cells')
```

Then, repeat these 2 commands for each of your markers in your feature plot. After that, you will be able to perform Differential Analysis between those cells IDs.

Kind regards,
Simon

**Comment by Hemantcnaik** [comment]
Thank you simon for your replay i need one more help, i ran tsne plot using below  command 
mca <- RunTSNE(mca, dims = 1:75, tsne.method = "Rtsne", nthreads = 4, max_iter = 1000, perplexity = 50)
I want two cordinates data of tsne plot , like columns (cell_id, tsne_dimention1, tsne_dimention2) how to achive this one

**Comment by KinSimon96** [comment]
`DimPlot(mca, reduction.use = "tsne")`

**Comment by KinSimon96** [comment]
If you want to re-cluster cells with your specific marker:

`mca_subset <- subset(mca, subset = MS4A1 > 1)`

Then perform anoter pca, findneighboors,... and tsne on it and `DimPlot()`
You will see heterogeneity in cells expressing your specific marker.

Best

**Comment by Hemantcnaik** [comment]
library(Seurat)
library(patchwork)
library(dplyr)

mus=read.csv("rpkm.csv",header=TRUE,sep="\t", row.names=1 )
mca <- CreateSeuratObject(counts = mus, project ="Cell")
mca[["percent.ERCC"]] <- PercentageFeatureSet(mca, pattern = "^ERCC")
mca <- NormalizeData(mca, normalization.method = "LogNormalize", scale.factor = 10000)
mca <- FindVariableFeatures(mca, selection.method = "vst", nfeatures =3000)
all.genes <- rownames(mca)
mca <- ScaleData(mca, features = all.genes)
mca <- ScaleData(mca, vars.to.regress = "percent.ERCC")
mca <- RunPCA(mca, ndims.print = 1:5, nfeatures.print = 5)
mca <- FindNeighbors(mca, reduction = "pca", dims = 1:75, nn.eps = 0.5)
mca <- FindClusters(mca, resolution = 0.5, n.start =10)
mca <- RunTSNE(mca, dims = 1:75, tsne.method = "Rtsne", nthreads = 4, max_iter = 2000, perplexity = 50)
DimPlot(mca, reduction = "tsne", pt.size = 2) + ggtitle(label = "Rtsne"

i am currently running  above script getting  multiple cluster i want cluster tsne according.  to gene name  is there any  posibility to do so, i have  5 diffrent gene marker i want 5 clusters

**Comment by yuhanH** [comment]
You can use the `Embeddings` function to get the tsne coordinates for all cells.
For example, `Embeddings(pbmc_small, reduction = "tsne")`

For you second question, do you want to run tsne only based on marker genes?
If true, you can set your marker genes in the RunPCA step.
`RunPCA(mca,  features = marker.gene)`
