### ISSUE TITLE
Not finding the function MeavarPlot

### ISSUE THREAD

**Issue by Hemantcnaik** [satijalab/seurat#2881]
i am currently running below script 
> pbmc33k <- MeanVarPlot(mca, x.low.cutoff = 0, y.cutoff = 0.8)
Error in MeanVarPlot(mca, x.low.cutoff = 0, y.cutoff = 0.8) : 
  could not find function "MeanVarPlot"

Getting above error how could i fix it

**Comment by liuxl18-hku** [comment]
I think that function is in Seurat 1.x age. Maybe `VariableFeaturePlot` is what u want now.

**Comment by Hemantcnaik** [comment]
Okay thanks worked fine , i need one help  how to get each clustered  values from tsne plot, i saw average expression but I need all values with name

**Comment by andrewwbutler** [comment]
If you mean the cluster identity of each cell, that can be retrieved with `Idents(object)`. 

If you mean the tsne coordinates for each cell, that can be pulled with `Embeddings(object, reduction = "tsne")`
