### ISSUE TITLE
Error in dimnamesGets(x, value) :   invalid dimnames given for “dgCMatrix” object

### ISSUE THREAD

**Issue by smk5g5** [satijalab/seurat#2885]
Hi,

I am getting the following error when merging antibody capture object in seurat.

`[1] "Creating Seurat Objects..."
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in dimnamesGets(x, value) :
  invalid dimnames given for “dgCMatrix” object
Calls: merge ... colnames<- -> dimnames<- -> dimnames<- -> dimnamesGets
Execution halted`

Below is the code I am using. What Should I do to make it work. Thanks!

`
scrna_AB.list = list();
for (i in 1:length(data.10x)) {
scrna_AB.list[[i]] = CreateAssayObject(counts = data.10x[[i]]$'Antibody Capture');
}
scrna_ADT <- merge(x=scrna_AB.list[[1]], y=c(scrna_AB.list[[2]],scrna_AB.list[[3]],scrna_AB.list[[4]],scrna_AB.list[[5]]), add.cell.ids = c('TWFN-GBM091-1','TWFN-GBM098-1','TWFN-GBM103TIL-GBM103TIL','TWFN-GBM105-TIL','TWFN-GBM106-TIL_3'));`

**Comment by andrewwbutler** [comment]
Hi,

It looks like there might be a bug in `merge.Assay` when adding these prefixes. One work around is to just make them Seurat objects (so use `CreateSeuratObject` in the first loop instead). Then the merge should work and you can pull out the merged assay if you need it as an `Assay` object.

**Comment by rsatija** [comment]
Has been fixed in v5, which has better support for merging with diverse prefixes
