### ISSUE TITLE
Using split-seq data

### ISSUE THREAD

**Issue by hepcat72** [satijalab/seurat#2887]
*UPDATE: I have extensively edited this issue description based on feedback elsewhere.*

I'm trying to use Seurat for the first time and am learning about single-cell analysis for the first time, and I'm doing so with split-seq data. (Full disclosure: I'm also a lightweight when it comes to R.)  My purpose is that I'm trying to establish a workflow for SPLiT-Seq data generated by our sequencing core facility in such a manner that it can be fed to Seurat without need for conversion or massaging.  Toward that end, I have encountered the following issues on which I would like some clarification.

I first naïvely tried to use Read10X on the mtx and associated files output by split-seq, which didn't seem to work, no matter how much I manipulated the files to make them look exactly like a 10x dataset (based on various examples and descriptions).

It would have been nice to get that to work so as to not make the file sizes so large, but I couldn't figure that out, so I converted the sparse market matrix format to a dense tsv format.  Here is a head of that file:

```
AAACATCGAAACATCG_0	AAACATCGAAACATCG_1	AAACATCGAACGTGAT_0	AACGTGATAAACATCG_0	AACGTGATAAACATCG_1	AACGTGATAACGTGAT_0	AACGTGATAACGTGAT_1
hg38_X,ENSG00000000003,TSPAN6	8	2	2	26	15	17	13
hg38_X,ENSG00000000005,TNMD	0	0	0	0	0	2	0
hg38_20,ENSG00000000419,DPM1	22	26	27	73	43	50	28
hg38_1,ENSG00000000457,SCYL3	6	6	5	12	7	19	8
hg38_1,ENSG00000000460,C1orf112	23	10	24	59	34	49	21
hg38_1,ENSG00000000971,CFH	101	44	129	331	151	270	122
hg38_6,ENSG00000001036,FUCA2	33	28	24	82	58	74	36
hg38_6,ENSG00000001084,GCLC	30	16	14	72	27	54	42
hg38_6,ENSG00000001167,NFYA	14	9	17	41	28	31	12
```

The column names were extracted as-is from split-seq's cell_metadata.csv file, which the core facility requested and I thought that would be OK, since it looks so similar to the cell barcodes in the 10x datasets I've seen examples of.  The file represents a mix of 7 human and mouse cells.  I added the chromosomes to the row names (which includes the species (e.g. hg38) so as to easily differentiate human/mouse), after I encountered the mitochondrial QC step in the tutorial I was following, because while the human annotations had "MT-" in the gene symbols, mm10 didn't.

I read that tsv file in using:

```
dge_data <- as.matrix(read.table("DGE.tsv", sep="\t", header=TRUE))
pbmc <- CreateSeuratObject(counts = dge_data, min.cells = 3, min.features  = 200, project = "SPLITSEQ_TT", assay = "RNA")
```

I started following chapter 9 of the scRNA-Seq course I found [here](https://scrnaseq-course.cog.sanger.ac.uk/website/seurat-chapter.html). I ran into some issues which I was able to resolve by tweaking my mtx to tsv conversion script, but I ran into some errors that I assume have to do with the format of the gene names/IDs and possibly some issues stemming from cell names/IDs (which I've thus far been able to work through, I think).

However, given errors like the following, and the fact that I can't seem to find specifications on these sorts of row/column name requirements, I was wondering if I could be directed to somewhere where those specifications are laid bare, so that I can check them in my conversion script.  For the most part, the original row names I used have not been a problem, but I ran afoul in this step (where it appears to complain about a comma):

```
> FeatureScatter(object = pbmc, feature1 = "hg38-4,ENSG00000074966,TXK", feature2 = "PC_1")
Error in parse(text = x) : <text>:1:7: unexpected ','
1: hg38.4,
          ^
```

Also, when I look at how CellsByIdentities behaves (while I was working through other errors/warnings), I realized I'm not sure that the column names are being processed correctly due to the underscores (followed by a number (e.g. `_0`)), because my understanding is that the `_#` portion of the split-seq cell barcode indicates the first well barcode, which would be needed to uniquely identify the cells in the table. I infer from this output from CellsByIdentities that it's only using the sequence portion of the cell barcodes to uniquely identify cells, which I don't think is correct:

```
> CellsByIdentities(object=pbmc, cells=colnames(pbmc))
$AAACATCGAAACATCG
[1] "AAACATCGAAACATCG_0" "AAACATCGAAACATCG_1"

$AAACATCGAACGTGAT
[1] "AAACATCGAACGTGAT_0"

$AACGTGATAAACATCG
[1] "AACGTGATAAACATCG_0" "AACGTGATAAACATCG_1"

$AACGTGATAACGTGAT

[1] "AACGTGATAACGTGAT_0" "AACGTGATAACGTGAT_1"
```

When I change my conversion script to change the underscores to dashes, CellsByIdentities outputs the following:

```
CellsByIdentities(object = pbmc, cells = colnames(pbmc))
$SPLITSEQ_TT
[1] "AAACATCGAAACATCG.0" "AAACATCGAAACATCG.1" "AAACATCGAACGTGAT.0" "AACGTGATAAACATCG.0" "AACGTGATAAACATCG.1" "AACGTGATAACGTGAT.0"
[7] "AACGTGATAACGTGAT.1"
```

which is very different than when I used the unaltered cell barcodes, and I assume that this is a critical difference given the changes I see in the plots generated by subsequent steps.

I made all the changes to characters used in the row and column names which I inferred from errors, warnings and observed behaviors to the following:

```
AAACATCGAAACATCG-0	AAACATCGAAACATCG-1	AAACATCGAACGTGAT-0	AACGTGATAAACATCG-0	AACGTGATAAACATCG-1	AACGTGATAACGTGAT-0	AACGTGATAACGTGAT-1
hg38-X.ENSG00000000003.TSPAN6	8	2	2	26	15	17	13
hg38-X.ENSG00000000005.TNMD	0	0	0	0	0	2	0
hg38-20.ENSG00000000419.DPM1	22	26	27	73	43	50	28
hg38-1.ENSG00000000457.SCYL3	6	6	5	12	7	19	8
hg38-1.ENSG00000000460.C1orf112	23	10	24	59	34	49	21
hg38-1.ENSG00000000971.CFH	101	44	129	331	151	270	122
hg38-6.ENSG00000001036.FUCA2	33	28	24	82	58	74	36
hg38-6.ENSG00000001084.GCLC	30	16	14	72	27	54	42
hg38-6.ENSG00000001167.NFYA	14	9	17	41	28	31	12
```

And it seems to have fixed most of the issues.  For example, the violin plots now have curvy brown swaths down the center that were not there before.  And in particular, the CellsByIdentities output, as indicated above, now looks correct (as opposed to when I had the original underscores, which appeared to group the 7 cells in 3 pairs and one individual).

My other concerns have to do with data size requirements.  I was running a small set of test data, and I had to adjust some parameters, which is understandable, but I would like to know if there's a hard lower limit on the amount of data. And do I need to restructure my data to separate counts of genes from different species (e.g. mouse & human)? I.e. Should I create separate matrices that have only the human-identified cells and gene annotations to use it with Seurat?  Perhaps I'm worrying too much, but without knowing what may rely on column/row name format assumptions, I can't be sure my data is being analyzed properly.  For reference as to the data size I'm using in my testing, this is the first data line from the original split-seq mtx file:

```
7 38526 194539
```

My goal is to process our core facility's SPLiT-Seq results so that our output can be directly used with Seurat by the users without issues or need for further conversion.  So I specifically would like to know what makes row or column names valid or invalid, as opposed to what to change WRT this specific dataset.  We may be supplied with annotations from various sources that may have different characters in the gene symbols, or accession numbers, or even chromosome names.  And I would like to know what other characters we may come across that could cause errors or unexpected behaviors.

Also, is Seurat designed to utilize non-unique gene symbols (e.g. from paralogs) or do the row names have to be unique?

**Comment by satijalab** [comment]
1. I would suggest manipulating your core's output files to produce a single matrix (ideally sparse), that has genes as rows and cells as columns, these can then be directly read into Seurat.

2. The gene names do have to be unique

3. We do have a few specifications on where row and column names can include dashes. This is to avoid uncertainty that can occur later (for example, if you had a gene called PC_1, this could conflict with the dimensional reduction embeddings from PCA).

@mojaveazure can list those requirements below

4. there are no hard limits on data

5. when dealing with human/mouse data, you can create two separate matrices (and two objects), or combine them into one matrix where the gene names include the name of the species.

**Comment by hepcat72** [comment]
Thanks very much for your response.

I'll look into how to load the sparse matrix data.  I didn't know that was a possibility.  Though it sounds like I will still have to be careful of the character content of the row and column names.  We were thinking of strictly limiting to alphanumeric plus dash and dot, and replacing anything else with dash.

Is there a way to incorporate other metadata such as species, chromosome, gene symbol other than concatenating them together in the row names?  I know that the tutorials I followed rely on "^MT-" in the row names for QC, and the mouse annotations don't have that.

**Comment by hepcat72** [comment]
So I was able to figure out how to get the SPLiT-Seq output to directly be loaded into Seurat.  I'm still concerned about the cell & row naming requirements however.  Based on subsetting I've seen in the tutorial I followed, which uses the pattern `^MT-` to identify mitochondrial genes via the row names, I'm a little worried that if I use `make.names`, it may break possible assumptions about the row name format.  So currently, I have the following to read in the SPLiT-Seq data:

```
coldata <- read.csv(file="cell_metadata.csv", header=TRUE, sep=",")
colnames <- gsub("[^[:alnum:\\\\-\\\\.] ]", "-", paste(coldata$cell_barcode))

rowdata <- read.csv(file="genes.csv", header=TRUE, sep=",")
rownames <- gsub("[^[:alnum:\\\\-\\\\.] ]", "-", paste(rowdata$gene_name, rowdata$genome, rowdata$gene_id, sep = "."))

library("Matrix")
mtx <- t(as.matrix(readMM("DGE.mtx")))
rownames(mtx) <- rownames
colnames(mtx) <- colnames

pbmc <- CreateSeuratObject(counts = mtx, min.cells = 3, min.features  = 200, project = "SPLITSEQ_TT", assay = "RNA")
```

I'm not sure that everything here is necessary, but the `gsub`s and `paste`s appear to correct issues I encountered such as the behavior of `CellsByIdentities`, which I assume is addressed when SPLiT-Seq's `coldata$cell_barcode` gets its underscore replaced.  I still need to find a reliable way of mitochondrial gene subsetting for QC steps in the tutorial I'm following.

Given that the tutorial uses a `^MT-` pattern match to identify mitochondrial genes, I'm slightly concerned that there may be steps in Seurat that assume the presence of dashes and/or gene name patterns that are anchored at the beginning (which the usage of `make.names` could potentially break depending on the annotation source).  Are these assumptions that only exist outside of Seurat or are these assumptions used internally as well?

**Comment by mojaveazure** [comment]
Hi Robert,

Quick clarification on feature names in Seurat: we disallow underscores `_`, pipe characters `|`, and duplicated names. We resolve duplicates by calling `make.unique` on the row names of the input matrix. Underscores and pipe characters are replaced with dashes `-` using `gsub`. We only care about underscores because we use these in [keys](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/Key), pipes because they break ggplot2, and duplicate names because R doesn't like duplicate names.

Other than these, we do not do any other processing of feature names. The function used to read in the data may call `make.names` when creating the input matrix. I would strongly discourage odd characters (eg. commas `,` and symbols such as `$` or `&`, etc) in feature names.

We do not may any assumptions about format for feature names or symbols. You could, for example, name every feature as `feature1`...`featureN`, Seurat simply doesn't care about that. We use `^MT-` to find mitochondrial genes in our tutorials because our datasets mark mitochondrial genes with `^MT-`, no other reason. You can name your features anything you want as long as they are unique and do not contain underscores or pipe characters; we encourage you to choose what fits your workflow best.

Feature-level metadata is stored on the `Assay` level; see https://github.com/satijalab/seurat/issues/2855#issuecomment-614733444 for more details

**Comment by hepcat72** [comment]
Ah, great!  Thanks for the clarification.  At what point do you remove underscores?  Because I found that unless I remove underscores from the column names, my outputs are weird.  And I thought it had to do with the underscores coming from the `cell_metadata.csv` from splitseq, best shown when you call CellsByIdentities with the column names from the seurat object:

```
> CellsByIdentities(object=pbmc, cells=colnames(pbmc))
$AAACATCGAAACATCG
[1] "AAACATCGAAACATCG_0" "AAACATCGAAACATCG_1"

$AAACATCGAACGTGAT
[1] "AAACATCGAACGTGAT_0"

$AACGTGATAAACATCG
[1] "AACGTGATAAACATCG_0" "AACGTGATAAACATCG_1"

$AACGTGATAACGTGAT

[1] "AACGTGATAACGTGAT_0" "AACGTGATAACGTGAT_1"
```

So it seems I should pre-filter those underscores out?

**Comment by mojaveazure** [comment]
We allow underscores in cell names, since they usually don't cause issues. What's happening here is `CreateSeuratObject` is assigns identities to be the first part of the cell names, split by an underscore (see the `names.field` and `names.delim` paramters of `CreateSeuratObject`). If there are more than 100 cells or no split based on `names.field` and `names.delim`, then we assign the `project` as the cell identities. In your case, you must have fewer than 100 cells and a logical split based on the underscore (not human logical but computer logical). You can either filter these out or suppress this behaviour by changing the `names.delim` paramter of `CreateSeuratObject`

**Comment by hepcat72** [comment]
Yes, that seems to be what happened.  It was a small test (but real) dataset off our sequencer for QC.  Only a handful of cells.
