### ISSUE TITLE
Demultiplexing HashTag Data

### ISSUE THREAD

**Issue by f0ng1203** [satijalab/seurat#2888]
Hi,

I have run CITE-seq-Count to demultiplex my data and as I am intersecting the data between UMI and HTO, the file that I stored it in shows character (empty).

I have made sure that the RDS containing HTO is correct with the corresponding cell barcode.
As for my UMI, I got it after running cellranger count.

Anybody has any idea of what could have gone wrong?

Thank you in advance.

regards,
fong

**Comment by yuhanH** [comment]
I think you question is more related to the CITE-seq-Count, but not seurat. 
You may try Alevin to align your CITEseq data. 
https://combine-lab.github.io/alevin-tutorial/2020/alevin-features/
