### ISSUE TITLE
Problem with MAST for findMarkers

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#289]
Hi 
i have been trying to use MAST as a test for differentially expressed genes. 
An error is returned, that has been discussed in a recent post (273). 
Nevertheless, the help that was given in 273 did not solve my problem. 
I run: 
```R
dif.markers <- FindAllMarkers(object = object, only.pos = TRUE, test.use = "MAST", logfc.threshold=log(2))
Fehler in eval(e, x, parent.frame()) : Objekt 'avg_logFC' nicht gefunden
```

Thanks for your help

**Comment by leonfodoulian** [comment]
Hi,

Have you tried installing the latest [develop version of Seurat](http://satijalab.org/seurat/devinstall.html)? I am not sure if the issue is related to this, but try to give it a try.

Best,
Leon

**Comment by annecar** [comment]
Hi Leoa
i have installed the update, but i still get the same error. unfortunately... any other idea???

**Comment by satijalab** [comment]
This seems to be a bug in FindAllMarkers (also observed for DESeq2), we will fix in the next release.

**Comment by satijalab** [comment]
This has been fixed and will roll out first to the develop branch, then CRAN in the next day or so.

As a side note, this occurs either because the first test in FindAllMarkers returns no DE genes, or fails due to some error. You can use FindMarkers to check which of the two is the cause
