### ISSUE TITLE
Add in already existing metadata to the Seurat Object.

### ISSUE THREAD

**Issue by oliviajc** [satijalab/seurat#2890]
Hello,

I am looking at the data available online. The authors posted them a count file and a separate metadata file. Is it possible to add the existing metadata to the Seurat object (from the count file)?

Thank you,

Olivia

**Comment by KinSimon96** [comment]
Watch [here](https://nbisweden.github.io/workshop-archive/workshop-scRNAseq/2018-05-21/labs/seurat_analysis.html) at the "Load expression values and metadata" part, they processed similarly to your question their pre-Seurat object, with count and metadata file!

Best,
Simon

**Comment by oliviajc** [comment]
Thank you so much Simon!
