### ISSUE TITLE
Loading the Seurat library crashes. 

### ISSUE THREAD

**Issue by dianaliduke** [satijalab/seurat#2891]
Last week I successfully downloaded R, R studio, Seurat package, and the PBMC practice data. I ran through the tutorial. Today, I tried to help my lab members do the same exercise and had major issues. 

I tried to load library(Seurat) after installing Seurat package. It caused my R studio to have a fatal error and abort my session. I have successfully downloaded it before. I have uninstalled R and R studio and reinstalled, restarted my computer. I am new to R too, so I'm not sure what I'm doing.

I am following the directions provided on the satijalab.org website on how to install Seurat.

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but this might be helpful.  Check out issue #2769.  Do any of those conditions or solutions apply to your installation of R/fix the issue you are having?  If those do not apply/fix the issue I would recommend posting the output of sessioninfo here to give the devs more information about your system/ R setup.

Best,
Sam

**Comment by dianaliduke** [comment]
Perfect, thank you Sam!

Diana Li, Ph.D.
Postdoctoral Fellow in Roper Lab
Division of Gastroenterology
Department of Medicine
Duke University
Work Phone: (919) 660-2924
