### ISSUE TITLE
Exporting Normalized data

### ISSUE THREAD

**Issue by Hemantcnaik** [satijalab/seurat#2892]
Hello everyone I wish to export normalized and scaled data , i tried below command both giving me error
1.  > as.matrix(mca@data)
       Error in as.matrix(mca@data) : 
         no slot of name "data" for this object of class "Seurat"
2.  >  as.matrix(mca@scale.data)
Error in as.matrix(mca@scale.data) : 
  no slot of name "scale.data" for this object of class "Seurat"

**Comment by KinSimon96** [comment]
Hey,

You didn't go far enough in your S4 class branches.
Try this:
`as.matrix(mca@assays$RNA@data)`
`as.matrix(mca@assays$RNA@scale.data)`

It should work.

Best,
Simon

**Comment by mojaveazure** [comment]
Please see the [`GetAssayData`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/GetAssayData) function for reliably accessing expression matrices from a `Seurat` object
