### ISSUE TITLE
Comparative analyses with custom data

### ISSUE THREAD

**Issue by Karop7** [satijalab/seurat#2893]
Hi there, thanks for a well documented software! 

I have a small single-cell dataset that I have generated myself, ie it did not come out of a sequencer. By using Excel/R to arrange the data so that each row is a gene and each column is a cell (numbered 1,2,3...), I was able to fully run my Seurat analysis by following instructions from the "Guided tutorial" vignette.

I would now like to run the "Stimulated vs Control" vignette, or compare groups of cells that originated in different samples, and see which cluster each sample maps to. How should I (manually) structure my original dataframe to make this possible, ie how should I assign each cell to a given class so that this info is will be integrated into the seurat object?

Thanks for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but this may be able to help.  So depending on your analysis you don't necessarily need to run the code any differently (unless you want to perform different analysis with integration method like in the Stim vs Control vignette).  You also don't need to modify your original data frame of cell x gene.  All you need to do is add column to the metadata in Seurat object specifying which cells come from which samples.  The you can pass that variable in DimPlot to identify the distribution of cells by sample, or treatment, or any other variable you add to meta data.  You can do this in your current analysis and that may guide you as to whether using integration methods (like the stim vs control vignette) is necessary.

Best,
Sam

**Comment by Karop7** [comment]
Thanks Sam. 
This works if I save the names column separately before creating the seurat object of all the cells, and then add it on as metadata. However, if I want to create a Seurat object with the initial filtration steps  (min.cells = 3 and min.features = n number of my genes), then a small percentage of cells are discarded from the resulting Seurat object, and the names column I made originally no longer matches the dataset. 

I have tried setting the names as the first row of the input matrix, but for some reason this produces a Seurat object with no features. 

Thanks for any further suggestions!

**Comment by samuel-marsh** [comment]
Hi,

After creating Seurat matrix with filtering parameters pull the cell names that remain.  Then you can filter your original list of cell names to only include those in the object and then add that subsetted list of conditions and matching cell names to the object.

Best,
Sam
