### ISSUE TITLE
Subset cluster including features with non-zero expression

### ISSUE THREAD

**Issue by atflores** [satijalab/seurat#2896]
Hello, following clustering, I'd like to subset a cluster of cells and restrict the pull to only genes expressed in that cluster (e.g. exclude features with zero expression).

I've tried using the following approaches:
mac <- subset(object, idents = "mac", subset = object@assays$RNA@scale.data >0)

Or creating an expression matrix with the genes:
genes <- as.matrix(object@assays$RNA@scale.data > 0)[, WhichCells(object, idents = "mac")]

These approaches don't remove the non-expressed genes in the select cluster though. Any suggestions?
Many thanks-

**Comment by timoast** [comment]
You can use the `GetAssayData` function to access the expression information, see the wiki for more information: https://github.com/satijalab/seurat/wiki/Seurat#data-access

For example:

```r
cells <- Idents(object) == "mac"
counts <- GetAssayData(object, slot = "counts")[cells, ]
genes.use <- rowSums(counts) > 0
```
