### ISSUE TITLE
Seurat::FeaturePlot appears to fail if input genes have no variance

### ISSUE THREAD

**Issue by alexgraehl** [satijalab/seurat#29]
Seurat::FeaturePlot( your_seurat_object_here, features.plot=genes_with_zero_counts.vec) errors out due to a problem with cut / breaks.

**Comment by andrewwbutler** [comment]
Thanks for pointing this out. It's now been fixed in latest (1.4.0.6) version.

**Comment by alexgraehl** [comment]
Thanks! Seurat is pretty much the best single cell resource ever, and I'm
glad to see that it's under active development!
