### ISSUE TITLE
Error in RunMultiCCA due to duplicate cell names

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#290]
Hi, 

When attempting to integrate 4 datasets, I get the error below due to common cell names between the sets.  
Where should I input the add.cell.id1 - add.cell.id4? On the RunMultiCCA line? The merge obj function is built into it I see...

I thought about recreating the seurat objects if there is no other solution? How can I rename the cell ids while I do this? 

Thank you!

> norms.integrated <- RunMultiCCA(ob.list, genes.use = genes.use, num.ccs = 15)
[1] "Computing CC 1"
[1] "Computing CC 2"
[1] "Computing CC 3"
[1] "Computing CC 4"
[1] "Computing CC 5"
[1] "Computing CC 6"
[1] "Computing CC 7"
[1] "Computing CC 8"
[1] "Computing CC 9"
[1] "Computing CC 10"
[1] "Computing CC 11"
[1] "Computing CC 12"
[1] "Computing CC 13"
[1] "Computing CC 14"
[1] "Computing CC 15"
Error in MergeSeurat(object1 = combined.object, object2 = object.list[[i]],  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names

**Comment by leonfodoulian** [comment]
Hi,

I don't think there is such an option to `RunMultiCCA()`. This question has already been asked, in [issue #270](https://github.com/satijalab/seurat/issues/270). I guess you should give your cells unique names when creating your initial Seurat objects.

Hope this helps!

Best,
Leon

**Comment by yingxixu** [comment]
Did you solve this problem? all my 3 databases are 10X, so cell.id are same, I still don't know how to add"add.cell.id“...
