### ISSUE TITLE
Create new clusters within existing clusters in Seurat

### ISSUE THREAD

**Issue by divya-sam** [satijalab/seurat#2901]
Is there a way to create new clusters within existing clusters in Seurat? I have a single cluster of NK cells and B cells; Seurat has put these cells into one cluster because they all show high expression of PLCG2 gene (common to NK cells and B cells). On the UMAP, this cluster separates into 2 subsets - one next to NK cells and the other next to B cells (the canonical cell surface markers also indicate that they are separate cell types). However, they're all coloured same as they are assigned the same cluster. How should I proceed with separating these cell types into different clusters and have all the data in the main UMAP cluster plot?

Attached is the plot:

![Rplot - celltype identified](https://user-images.githubusercontent.com/63321731/80234744-ea350580-8615-11ea-843f-5dcdc2b90611.png)

**Comment by timoast** [comment]
You can either increase the clustering resolution, or subset the cells and perform another round of clustering on the subset object
