### ISSUE TITLE
Differential gene expression between two conditions

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#2903]
Hi Seurat team,

Thank you for developing Seurat. I am running comparative analysis between two conditions and would like to identify DEGs between two clusters across these conditions (i.e. between condition A cluster 1 vs. condition B cluster 1 cells). I used SCTransform/anchoring pipeline to correct and integrate my data. I am now running the FindMarkers command and would like to get your advice on a couple of things. 

1. Is the FindMarkers command run on counts or normalized counts? I get different results when using either one.

2. I used SCTransform for integration, this is the code I am using - does it look ok?

t10x_subset <- subset
DefaultAssay(t10x_subset) <- "SCT"
t10x_subset_Der_Sub0_markers <- FindMarkers(t10x_subset, ident.1 = "0_mouse1", ident.2 = "0_mouse2", verbose = FALSE, assay = "SCT", slot = "scale.data", min.pct = 0.25, test.use = "wilcox", logfc.threshold = 0.25)

3. In terms of fold change, is 0.25X FC standard/good practice? 

4. This test only yields one list of genes, but I do not know which gene is up-regulated in each condition unless I plot them using FeaturePlot. Is there a way to get a list for each condition?

Thanks for your help!

**Comment by satijalab** [comment]
We recommend running FindMarkers on the RNA slot (using the normalized counts). When you run FindMarkers, the sign of the fold-change will tell you if its up or down-regulated
