### ISSUE TITLE
Making heatmap from DEG result

### ISSUE THREAD

**Issue by ruohuchengxhe** [satijalab/seurat#2907]
Hi,
I'm using Seurat to analysis a population of cells across conditions. The aim is to do DEG to compare this cell population to all the cells, as well as compare this cell population in those two conditions.
I tried in both DEG results, and this is always the case:
Acquire DEG of 'cellx' compare to all cells: 
`pop.markers = FindMarkers(s, cellx)`
then I have results like this:
![image](https://user-images.githubusercontent.com/43062204/80287755-06769680-872b-11ea-950c-4f152ecda4a9.png)
it has all the columns, but doesn't have gene column. When using` findallmarkers`, it returns a tibble with 'gene' column. I'm not sure if this matters.
Then, however, when I try to filter genes and do a heatmap:
```
top10<-pop.markers %>% group_by(cluster) %>% top_n(2, avg_logFC)
DoHeatmap(object = s, features = top10$gene, label = TRUE)
```
I got an error: Error: Column `cluster` is unknown.
If I filter only with `pop.markers %>%  top_n(2, avg_logFC)`, I can have the genes by manually add the gene to one column, but still not able to create a heatmap. So, I'm looking for help for: 
1. should I add cluster somewhere to solve this issue? Otherwise what can I do? 
2. When creating a heatmap,  how can plot to compare across conditions? `group_by` seems not working for me. Is there any example code? I can have other plots from: https://satijalab.org/seurat/v3.1/immune_alignment.html. But this one doesn't have heatmap. 
Thanks in advance!

**Comment by timoast** [comment]
1. The `cluster` column is not present in that dataframe. This is only added if you run `FindAllMarkers`. If you run `FindMarkers`, all the markers are for one group of cells
2. There is a `group.by` (not `group_by`) parameter in `DoHeatmap`. See the documentation for `DoHeatmap` by running `?DoHeatmap`
