### ISSUE TITLE
order of merging objects impacts cluster result when merging 3 different objects

### ISSUE THREAD

**Issue by HChen1216** [satijalab/seurat#2908]
Hi,

When I merged 3 Seurat objects, I found that 
merged_object <- merge(object1, y = c(object2, object3), add.cell.ids = c("aa1", "aa2", "aa3")), 
the clustering is different from
merged_object <- merge(object2, y = c(object1, object3), add.cell.ids = c("aa2", "aa1", "aa3"))

The whole script is exactly the same except this line (order changed). I got the same cluster number but different cluster shape, even the cluster annotation is changed.

I'm so confused.

**Comment by samuel-marsh** [comment]
Hi All,

I'm able to verify this issue issue using merge vignette with 3 pbmc datasets and the standard guided tutorial code 3.1 vignette.  Code and example images below.  

The UMAP plots are extremely similar though appear to be different orientations and slightly different shapes.  Unclear why this would be given the overall starting data should be identical.


`pbmc4k.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices_2/GRCh38/")
pbmc4k <- CreateSeuratObject(counts = pbmc4k.data, project = "PBMC4K")
pbmc4k


pbmc8k.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices_3/GRCh38/")
pbmc8k <- CreateSeuratObject(counts = pbmc8k.data, project = "PBMC8K")
pbmc8k

pbmc3k <- readRDS(file = "~/Downloads/pbmc3k_final.rds")
pbmc3k


pbmc <- merge(pbmc3k, y = c(pbmc4k, pbmc8k), add.cell.ids = c("3K", "4K", "8K"), project = "PBMC15K")
pbmc

pbmc2 <- merge(pbmc8k, y = c(pbmc3k, pbmc4k), add.cell.ids = c("*K", "3K", "4K"), project = "PBMC15K2")
pbmc2`

`pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
ElbowPlot(pbmc)
pbmc <- FindNeighbors(pbmc, dims = 1:15)
pbmc <- FindClusters(pbmc, resolution = 0.5)
pbmc <- RunUMAP(pbmc, dims = 1:15)
DimPlot(pbmc, reduction = "umap")`

`# Second run
pbmc2[["percent.mt"]] <- PercentageFeatureSet(pbmc2, pattern = "^MT-")
pbmc2 <- subset(pbmc2, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc2 <- NormalizeData(pbmc2, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc2 <- FindVariableFeatures(pbmc2, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc2)
pbmc2 <- ScaleData(pbmc2, features = all.genes)
pbmc2 <- RunPCA(pbmc2, features = VariableFeatures(object = pbmc2))
ElbowPlot(pbmc2)
pbmc2 <- FindNeighbors(pbmc2, dims = 1:15)
pbmc2 <- FindClusters(pbmc2, resolution = 0.5)
pbmc2 <- RunUMAP(pbmc2, dims = 1:15)
DimPlot(pbmc2, reduction = "umap")`

**Comment by samuel-marsh** [comment]
![merge1](https://user-images.githubusercontent.com/38284410/80506995-541a1b80-8944-11ea-903f-285c4a4e82ed.png)
![merge2](https://user-images.githubusercontent.com/38284410/80507003-55e3df00-8944-11ea-9d84-b5becf161d1e.png)

**Comment by andrewwbutler** [comment]
Hi,

Thanks for the reproducible example! Yes, the starting data is identical and all the processing is the same up until the `RunPCA` step. For this, by default we're using an approximate algorithm (via `irlba`) to compute the first N PC embeddings. If you shuffle the input order for that matrix, you will very slightly change the results and these small differences will get propagated downstream. You can verify this by just running some random matrices through irlba compared with a full svd. E.g

```R
> set.seed(42)
> A <- matrix(runif(400), nrow=20)
> new.order <- sample(1:nrow(A))
> B <- A[new.order ,]
> 
> T1 <- irlba(A, 3)
> T2 <- irlba(B, 3)
> 
> all.equal(abs(T1$u[new.order, ]), abs(T2$u))
[1] "Mean relative difference: 1.63062e-07"
> all.equal(abs(svd(A)$u[new.order, ]), abs(svd(B)$u))
[1] TRUE
```

This shouldn't change the overall manifold of the data though which is why you get very similar umap plots at the end.

**Comment by samuel-marsh** [comment]
Hi @andrewwbutler,

Awesome thanks so much for the info.  Ya wasn't very concerned considering the similarities that appeared by eye to be more visual than anything but great to understand the reason behind it.

Thanks!
Sam
