### ISSUE TITLE
Easy way to control cluster separation in TSNEPlot?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#291]
Hello Seurat Team,

Is there an easy way to separate the clusters in Seurat's TSNEPlot function output in case of a large number of cells?  I mean physically separating the clusters in just the plot, like more of an aesthetic thing.  I get 9 clusters, but some of the clusters are overlapping quite a bit in the plot and hence are harder to differentiate.  I have seen plots online where the clusters are far apart.  Is this a controllable feature?

Thanks a lot for any help!

**Comment by mojaveazure** [comment]
Use `do.return = TRUE` to store the plot as a variable (ie. `p <- TSNEPlot(object = my.seurat.object, do.return = TRUE, ...)`) and [add custom axis limits to it with ggplot2](https://stackoverflow.com/questions/3606697/how-to-set-limits-for-axes-in-ggplot2-r-plots).

**Comment by muktad** [comment]
Is there a way to control the number of clusters?
