### ISSUE TITLE
RunPCA error

### ISSUE THREAD

**Issue by manukrishnamurthy** [satijalab/seurat#2910]
Hi, I'm following the guided seurat tutorial, and when I get to the  RunPCA step I get this error
`Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))`
Everything has been fine until this point. The counts data looks like this, and I have transformed the counts matrix for the seurat object.
![cell counts file](https://user-images.githubusercontent.com/36338922/80314292-a16c8080-87be-11ea-912a-64fe71e9e644.JPG)
How can I fix this/why is it happening?

Thanks

**Comment by andrewwbutler** [comment]
Hi, 

Could you post the code you ran up until this point? A reproducible example (e.g. on a downsampled version of this data) would be helpful as well if you can provide it.
