### ISSUE TITLE
ReadH5AD function replaces categories with numbers in meta.data

### ISSUE THREAD

**Issue by elimereu** [satijalab/seurat#2911]
Hi, 
I have a problem when I use the function ReadH5AD. It seems that categories are replaced by numbers. In my case for example in the meta.data there is the column cell_type in which cell type labels were replaced by numbers. Is there any way to solve this? The data are at the following link: https://cellgeni.cog.sanger.ac.uk/gutcellatlas/Colon_cell_atlas.h5ad . 

Thank you in advance for you help!

Elisabetta

**Comment by mojaveazure** [comment]
Hi,

We are transitioning our support for AnnData/H5AD files to [SeuratDisk](https://github.com/mojaveazure/seurat-disk), our new package for interfacing `Seurat` objects with single-cell HDF5-based file formats. We would very much like it if you could give this a shot for reading in your data.

You can install SeuratDisk with the following:
```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")
```

A tutorial on how to read in AnnData/H5AD files via the h5Seurat intermediate can be found [here](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html). Greater detail about the new `Convert` mechanism can be found [here](https://mojaveazure.github.io/seurat-disk/reference/Convert.html)

If you come across any bugs in reading in your HDF5 files, please post them in mojaveazure/seurat-disk#1. Please note, there are some stipulations about the format of your AnnData/H5AD posted in https://github.com/mojaveazure/seurat-disk/issues/1#issue-619215532

**Comment by colinmcgovern** [comment]
The categories are turned into numbers after conversion, because they are a vector of factors instead of a vector of characters. If you're new to R, this may confuse you at first. My solution is to convert all of the factor vectors in the meta data over to character vectors, assuming pmbc is a Seurat object:

i <- sapply(pbmc@meta.data, is.factor)
pbmc@meta.data[i] <- lapply(pbmc@meta.data[i], as.character)
