### ISSUE TITLE
Error in if (any(rownames(x = counts) == "")) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by ceh88** [satijalab/seurat#2912]
I am analyzing single cell rna-seq data and this error comes up when I try to create an object. 

Here is what I am trying to run & what I am getting:

mock.data <- Read10X(data.dir = ".../outs/filtered_feature_bc_matrix")
Warning: Some features names are NA. Replacing NA names with ID from the opposite column requested

mock <- CreateSeuratObject(counts = mock.data, project = "mock", min.cells = 3, min.features = 100)
Error in if (any(rownames(x = counts) == "")) { : 
    missing value where TRUE/FALSE needed

Does anyone have any ideas on how to fix this? Thank you!

**Comment by diazdc** [comment]
I'm not on the Seurat team, but I can try to help. It's very likely that you have an empty row name. Try `grep("", rownames(mock.data))` and see if you get a hit.

**Comment by ceh88** [comment]
hi diazdc, I think I've figured it out. Unfortunately both my transcript ID and gene ID are "NA", so even though there is a fix to replace the "NA" with the name from the other column, the other column also has "NA" so there isn't really a fix. I will need to remake my reference file with cell ranger and start over. Thank you for your help!

**Comment by MengjurJ** [comment]
Try grep("", rownames(mock.data)), and then delete the row which rowname is 'NA'

**Comment by MengjurJ** [comment]
> I'm not on the Seurat team, but I can try to help. It's very likely that you have an empty row name. Try `grep("", rownames(mock.data))` and see if you get a hit.

Try which(is.na(rownames(mock.data))), and then delete the row which rowname is 'NA'.
