### ISSUE TITLE
Boxplot statistics for split.by VlnPlot

### ISSUE THREAD

**Issue by cesco-lemon** [satijalab/seurat#2914]
Hi everyone! I'm adding some boxplots with medians and such to my violin plots and it worked fine by just having VlnPlot(object, feature) + geom_bloxplot(width=0.1, fill="white") (graph1)

Then I tried to add it to violin plots using the split.by function and I get nice split violin plots but the boxplot don't "split2 with the violins (graph2). VlnPlot(object, feature, split.by="orig.ident") + geom_bloxplot(width=0.1, fill="white")

Any suggestions on ho to generate split boxplots or two separate boxplots for each side of the violin? Thank you very much for keep on developing Seurat and for the constant support!!!

![graph1](https://user-images.githubusercontent.com/42619695/80321531-c3c8c300-87eb-11ea-96bc-9f08201cceca.png)

![graph2](https://user-images.githubusercontent.com/42619695/80321537-c9bea400-87eb-11ea-80c2-997ef732f020.png)

**Comment by crebli** [comment]
Thanks a lot！

**Comment by timoast** [comment]
This works for me on the current Seurat release:

```r
library(Seurat)
library(ggplot2)

VlnPlot(pbmc_small, "CD79B", group.by = "groups", split.by = "letter.idents") +
  geom_boxplot()
```

**Comment by KrGurashi** [comment]
If you also came across this post looking for an answer, doing the following would do the trick:

VlnPlot(object = SeuratObj, group.by = 'X', split.by = 'Y') + geom_boxplot(position=position_dodge(1))

**Comment by Ruismart** [comment]
tried and failed in Seruat V3, temp way is to set another meta column as new identity, 
e.g.  X: A-B-C   Y:m-n         so to set Z: A.m A.n B.m B.n C.m C.n  (and order them in factor levels)        
then only do VlnPlot(group.by = "Z"), could successfully add box for each new group

**Comment by crebli** [comment]
Thanks!发自我的荣耀手机-------- 原始邮件 --------发件人： Liushaorui ***@***.***>日期： 2024年6月24日周一 下午1:31收件人： satijalab/seurat ***@***.***>抄送： crebli ***@***.***>, Comment ***@***.***>主    题： Re: [satijalab/seurat] Boxplot statistics for split.by VlnPlot (#2914)
tried and failed in Seruat V3, temp way is to set another meta column as new identity,
e.g.  X: A-B-C   Y:m-n         so to set Z: A.m A.n B.m B.n C.m C.n  (and order them in factor levels)
then only do VlnPlot(group.by = "Z"), could successfully add box for each new group
