### ISSUE TITLE
Demultiplex Cell Hashing data error

### ISSUE THREAD

**Issue by ibseq** [satijalab/seurat#2915]
hello, 
I was trying to run the Demultiplex Cell Hashing data but got the errro below from beginning, any advice?

> library(Seurat)
> load("/Users/ib/Desktop/HTODemuxFiles/pbmc_umi_mtx.rds")
Error in load("/Users/ib/Desktop/HTODemuxFiles/pbmc_umi_mtx.rds") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘pbmc_umi_mtx.rds’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 

thanks
ib

**Comment by mojaveazure** [comment]
You can't use `load` for Rds files; please read the documentation for [`load`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/load) and [`readRDS`](https://www.rdocumentation.org/link/readRDS?package=base&version=3.6.2)

**Comment by ibseq** [comment]
Thanks Paul, my mistake. Example dataset run normal
To reproduce it on my 10x dataset : how do I generate the "pbmc_umi_mtx.rds”
 And do I have to convert whichever output in .rds? Are there step by step vignettes about this too?


Thanks
Ib
