### ISSUE TITLE
What is the difference between nGenes and nUMIs?

### ISSUE THREAD

**Issue by sdabral05** [satijalab/seurat#2917]
Hi I am using Seurat to analyse scRNA data .

I have used CreateSeuratObject(). As results it gives result as ::
                   orig.ident nCount_RNA nFeature_RNA 
AAACCCAAGAGCATCG-1     monkey      43406         6931   
AAACCCAAGGGCAGTT-1     monkey      60448         7626   
AAACCCACAGTAGATA-1     monkey      45554         7316   
AAACCCACATTCACCC-1     monkey       7404         1948  
AAACCCATCTAGATCG-1     monkey       2607         1063   
AAACGAAAGTTACGAA-1     monkey      35497         6190   

I am not able to understand what is tjis nCount_RNA and nFeature_RNA and How it calculated ??
As AAACGAAAGTTACGAA-1  .. etc are the column name how corresponding to nCount_RNA and nFeatue_RNA ,what these number implicates ?

**Comment by samuel-marsh** [comment]
Hi,

nFeature_RNA is genes/cell and nCount_RNA is UMIs/cell.  They are calculated from the counts matrix that is imported when creating the Seurat Object.

Best,
Sa,
