### ISSUE TITLE
Adding more than 2 data sets in

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#2918]
Hello,

I know how to merge two data sets into seurat, but I am currently stumped as to how to do 4.  Can you please let me know? Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Hi, please see the matching vignette for more details ([https://satijalab.org/seurat/v3.1/merge_vignette.html](https://satijalab.org/seurat/v3.1/merge_vignette.html))  Briefly you can combine more than two datasets by supplying the objects during the merge command:
i.e. `pbmc.big <- merge(pbmc3k, y = c(pbmc4k, pbmc8k), add.cell.ids = c("3K", "4K", "8K"), project = "PBMC15K")`

Best,
Sam
