### ISSUE TITLE
GetSeuratData behavior when subsetting features

### ISSUE THREAD

**Issue by ddiez** [satijalab/seurat#2919]
I found a strange behavior in `GetSeuratData` when subsetting on features. The same behavior does not occur when subsetting on cells. Below is a minimal reproducible example to make my point:

```
library(Seurat)
x <- matrix(1:25, ncol = 5, dimnames = list(letters[1:5], LETTERS[1:5]))
x

  A  B  C  D  E
a 1  6 11 16 21
b 2  7 12 17 22
c 3  8 13 18 23
d 4  9 14 19 24
e 5 10 15 20 25

x <- CreateSeuratObject(x)
x
An object of class Seurat 
5 features across 5 samples within 1 assay 
Active assay: RNA (5 features, 0 variable features)
```

Then I run GetAssayData on a subset of features:

```
GetAssayData(x[c("a", "b"), ])
2 x 5 sparse Matrix of class "dgCMatrix"
  A B  C  D  E
a 1 6 11 16 21
b 2 7 12 17 22
```

But if I change the order of the features, the returned matrix does not preserve that order:

```
GetAssayData(x[c("b", "a"), ])
2 x 5 sparse Matrix of class "dgCMatrix"
  A B  C  D  E
a 1 6 11 16 21
b 2 7 12 17 22
```

If I do the same on cells I get my expected outcome (the order is preserved):

```
GetAssayData(x[, c("A", "B")])
5 x 2 sparse Matrix of class "dgCMatrix"
  A  B
a 1  6
b 2  7
c 3  8
d 4  9
e 5 10

GetAssayData(x[, c("B", "A")])
5 x 2 sparse Matrix of class "dgCMatrix"
   B A
a  6 1
b  7 2
c  8 3
d  9 4
e 10 5
```

I took a look at `subset.Assay` code. There is a line [here](https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/objects.R#L6005) where it calculates the intersect of the passed features and the feature names to check all exists. I think this might be the culprit:

```
intersect(c("a", "b", "c"), c("b", "a"))
"a" "b"
```

And it fits that a similar line does not exists for cells, so they are not affected.

Maybe it is enough to invert the arguments in that line?

```
intersect(c("b", "a"), c("a", "b", "c"))
"b" "a"
```

**Comment by mojaveazure** [comment]
Hi Diego,

Thanks for bringing this to our attention. `subset.Assay` was not intended to reorder features, which is why we didn't care if the order of features put into `subset.Assay` was the same as the ones that came out. We will look into fixing this (though we would welcome a PR that addresses the issue as well!)

**Comment by ddiez** [comment]
Excellent! Thank you Paul. I have sent a pull request #2944 (it's been some time so hope I did everything OK).

In case anyone else is hit by this, a workaround for the GetAssayData behavior is, instead of doing:

```
GetAssayData(x[features, ])
```

to do:

```
GetAssayData(x)[features, ]
```

And arguably nicer to look at.
