### ISSUE TITLE
question FindALLMaker: genes with low overall expression picked up

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#292]
HI, 
I have a dataset that has been clustered, and where i try to find Markers distinguishing the clusters. 
I am using the following line of code: 

data.markers <- FindAllMarkers(object = data, thresh.use = 0.25, only.pos = TRUE)
top10 <- data.markers %>% group_by(cluster) %>% top_n(10, avg_logFC)
DoHeatmap(object = data, genes.use = top10$gene, slim.col.label = TRUE, remove.key = TRUE)

Strangely there are genes coming up that have barely any expression over all the clusters. I do not understand why they show up. This is reproduced independently of the test applied (poisson, roc or DESeq2). 
Is this something people see as well? 

Thanks 
Anne 

I

**Comment by satijalab** [comment]
Of course it depends what you mean by 'barely any expression', and also depends on the number of cells in your  clusters (and their associated p-values). In general, even lowly expressed genes can be accurately detected as DE if there are large numbers of cells, but it is unlikely that they would be the most returned markers.
