### ISSUE TITLE
installation of package ‘Seurat’ had non-zero exit status

### ISSUE THREAD

**Issue by KhushiVirah** [satijalab/seurat#2920]
Hi members. I have been trying to install Seurat several times but its said: Warning in install.packages :  "installation of package ‘Seurat’ had non-zero exit status". I am failing to understand the issue.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team (just fyi).  Please post the output of the R console so that the issue causing the installation failure can be diagnosed.

Thanks,
Sam

**Comment by KhushiVirah** [comment]
That is the output on the R console:
![Screen Shot 2020-04-28 at 1 23 56 PM](https://user-images.githubusercontent.com/64295982/80517978-e118a100-8953-11ea-95a2-06d081aad56f.png)
Thank you for your consideration

**Comment by samuel-marsh** [comment]
According to that output it seems the package caTools is missing.  Try installing caTools from CRAN directly and then attempting to install Seurat again.
`install.packages("caTools")`

**Comment by KhushiVirah** [comment]
It says that caTools is not available for the R version 3.5.2
![Screen Shot 2020-04-28 at 1 36 52 PM](https://user-images.githubusercontent.com/64295982/80519067-66508580-8955-11ea-8eac-1f4fcb88a258.png)

**Comment by mojaveazure** [comment]
[As seen on their CRAN page](https://cran.r-project.org/web/packages/caTools/index.html), caTools is available for R v3.6 or higher. To install an older version of caTools for R v3.5, please use [`remotes::install_version`](https://www.rdocumentation.org/packages/remotes/versions/2.1.1/topics/install_version) to install an older version of caTools that is compatible with R v3.5
