### ISSUE TITLE
Dot plot Metrics

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#2921]
I have generated dot plots using `DotPlot` function. I get information about percent expressed and level of gene expression. Is it possible to get values associated with it?

Thank you

**Comment by andrewwbutler** [comment]
Hi,

There isn't a stand-alone exported function for returning percent expressed but you can pull out the gene expression matrices with `GetAssayData` and compute it relatively easily. For average expression, see the `AverageExpression` function.

You could also pull the data from the plot itself potentially. E.g.

```R
> p = DotPlot(pbmc_small, features = "LYZ")
> p$data
```
