### ISSUE TITLE
SCTransform with multiple days of experiments

### ISSUE THREAD

**Issue by xAZx** [satijalab/seurat#2922]
Hi Seurat Team,

I am currently analyzing PBMC data from patients with kidney disease. My original data from the diseased patient experiments was spread across 2 days of experiments and sequencing (all aspects of the experiments were identical, it's just that the volume of work required 2 days of experiments), so I have used SCTransform across the 2 days of experiments to help reduce batch effects. It seems to have worked well after comparing the same data analyzed without SCTransform.

My issue now is that I want to introduce data from healthy control PBMCs from a separate experiment to compare to our diseased patient PBMCs. My only thought was to use SCTransform and treat this as a "day 3" of experiments, and therefore integrate all my data on these 3 days of experiments to help reduce batch effects. What I worry about is that by doing so, I could possibly be losing the ability to show differences between healthy control PBMCs and diseased patient PBMCs because of the integration/anchoring effects across the 3 days of experiments. Is this a valid concern? If not and there is no other way, I will just use SCTransform as described above. Many thanks in advance.

**Comment by yuhanH** [comment]
Hi,
In your case, you could definitely treat healthy control as another group. The goal of integration of case and control is to define common cell types. After you define the cell types in the integrated assay, you can do the differential analysis between case and control in the RNA assay.
The stimulated PBMC vignette demonstrated the similar story with yours. 
https://satijalab.org/seurat/v3.1/immune_alignment.html
