### ISSUE TITLE
Trying to load data in Seurat 2.x-generated object

### ISSUE THREAD

**Issue by amikomae** [satijalab/seurat#2923]
Trying to load any plot of our data that was generated on Seurat 2.x build on a computer with Seurat 3.1.5. Experiencing issues, never been able to load this data on this computer. Tried installing Seurat 2.3 but unable to. Hoping for guidance. Do I need to update the data format? is it possible? Really hoping to avoid starting completely from scratch with counts matrices. THANKS!

Example of errors: 
> VlnPlot(data)
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "seurat"
> TSNEPlot(data)
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "seurat"

**Comment by samuel-marsh** [comment]
Hi,

After loading the Seurat object into R run `UpdateSeuratObject(data)` first and then you should be all set.

Best,
Sam

**Comment by amikomae** [comment]
Thanks so much, Sam.  I tried your suggestion of UpdateSeuratObject(data) after loading the libraries and the data but unfortunately anytime I tried to plot the data I received an error:
> TSNEPlot(data)
Error in UseMethod(generic = "DefaultAssay", object = object) :
  no applicable method for 'DefaultAssay' applied to an object of class "seurat"
> DimPlot(data)
Error in UseMethod(generic = "DefaultAssay", object = object) :
  no applicable method for 'DefaultAssay' applied to an object of class "seurat"

Do you have any further thoughts on what might be wrong or how to troubleshoot?
Thanks so much,
A

**Comment by mojaveazure** [comment]
Your object is a v2 object, not a v3 object. When you ran `UpdateSeuratObject`, you didn't save the object, so it didn't get updated. Please see https://github.com/satijalab/seurat/issues/990#issuecomment-444606845 for more details about v2 vs v3 objects.
