### ISSUE TITLE
Trying to install and run Seurat 2.3.4

### ISSUE THREAD

**Issue by pvimal95** [satijalab/seurat#2924]
I tried using the instructions to install Seurat 2.3.4 on a computer running R 3.4.4. 

Whenever I load Seurat using the "library" function, it always gives me this error:
> library(Seurat)
Loading required package: ggplot2
Error: package ‘cowplot’ required by ‘Seurat’ could not be found

Have tried multiple trouble shooting as well as installing the package cowplot directly to no avail. 

Any and all help is appreciated!

**Comment by mojaveazure** [comment]
> Have tried multiple trouble shooting as well as installing the package cowplot directly to no avail.

If you have issues installing cowplot, you should ask [them](https://github.com/wilkelab/cowplot) for help.
