### ISSUE TITLE
Creating a DotPlot for just 2 clusters

### ISSUE THREAD

**Issue by Drosophilist** [satijalab/seurat#2925]
Dear Satija Lab,

First of all, thank you for this amazing package. It's super intuitive and user friendly.
I'd like to ask you if it is possible to create a Dotplot to compare gene expression just between 2 or 3 clusters, without having to crop out the results for the other clusters. The latter is my current solution.

All the best,
Jose

**Comment by timoast** [comment]
This is not currently enabled but we can look at adding an `idents` parameter to `DotPlot`

**Comment by Drosophilist** [comment]
Thank you for the prompt response. Can I close the issue? (New to github and bioinformatics)
Cheers

**Comment by timoast** [comment]
We can leave the issue open until the functionality is added

**Comment by satijalab** [comment]
We're adding this in (@ jaisonj708) - mirroring the functionality in VlnPlot

**Comment by Drosophilist** [comment]
Thank you @satijalab 
Seurat improves by the day, you're incredible.

**Comment by jaisonj708** [comment]
DotPlot now has an ‘idents’ parameter so you can choose which Identities to display. This is available in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
