### ISSUE TITLE
weight reduction in TransferData

### ISSUE THREAD

**Issue by bsierieb1** [satijalab/seurat#2926]
Hi,

I'm trying to transfer labels between two highly divergent species, both sequenced using 10X. When I use TransferData with weight.reduction = "pca", I get better results than with the default setting weight.reduction = "pcaproject". Better means that predicted IDs are more consistent with manual cluster annotations based on selected markers and predicted IDs are more consistent within clusters.

I prefer to have a good reason to change any settings from its default. I wonder if you could very briefly explain to me in which situation which weight reduction procedure may work best? Alternatively, you may just point me towards a resource with the explanation.

Thanks a lot!
Bogdan

**Comment by satijalab** [comment]
Thanks, its a good question. PCAproject will work best when the reference dataset has more information than the query.  For example, when you have a large 'atlas' of pre-annotated cells, and want to annotate a small query dataset. This assumes that the structure in the reference describes the structure in the query.

pca will work best in the case you describe, cross-species analysis. In this case, the internal structure (i.e. its internal pca) in the query dataset is a good representation of its cells.
