### ISSUE TITLE
SCTtransform innerworkings

### ISSUE THREAD

**Issue by loverend** [satijalab/seurat#2927]
Hi, 
I was hoping to run SCTransform on a subset of (viral) genes (~120) from a dataset including human and viral reads, with the aim of performing clustering etc on viral vs host genes. I found that there seemed to be too many 1 / NA values and the glm wouldn't compute on this gene set (Perhaps you have suggestions for this?)

My solution was to run SCTransform on the whole dataset (human +viral genes) and return all normalised genes (return.only.var.genes = FALSE; memory isn't really an issue). Hopefully, therefore, the viral genes would be normalised as part of the whole data set, and I could then subset and run clustering on just the viral genes for example (post normalisation). 

However I am struggling to understand how SCTransform populates all of its data slots, does it remove features for which there are no counts in the RNA assay? The number of features in the scale.data slot is much less than the number of features in the RNA assay. Similarly the number of genes in the corrected counts is not the same as in the RNA assay or the SCT@scale.data slot. 

Could you clarify how you are omitting genes? Is it simply that if they have no counts in RNA they are not included in the SCT assay and how does this relate to the corrected counts? It makes it hard to determine whether or not I have truly normalised all the genes as intuitively I would expect SCT@scale.data / data / counts to have the same genes when return.only.var.genes = FALSE is used and that this should be the length of the RNA assay?
This issue seems to arise when merging an object with an SCT assay. Each indivdidal data set has SCT scaledata=data=counts  and yet the merged object scaledata!=counts/data. 
Interestingly there are also fewer features in the merged object compared to each one of its parts. 

merged_data_ebv.list <- SplitObject(merged_data_ebv, split.by ="orig.ident")
for (i in 1:length(merged_data_ebv.list)) {
   [i]] <- SCTransform(merged_data_ebv.list[[i]], verbose = TRUE, variable.features.n=4000, return.only.var.genes = FALSE)
}

merged_data_ebv.features <- SelectIntegrationFeatures(object.list = merged_data_ebv.list, nfeatures = 6000)
merged_data_ebv.list <- PrepSCTIntegration(object.list = merged_data_ebv.list, anchor.features = merged_data_ebv.features, verbose = FALSE)
merged_data_ebv <- merge(merged_data_ebv.list[[1]], c(merged_data_ebv.list[[2]], merged_data_ebv.list[[3]], merged_data_ebv.list[[4]]))

Length issue: 
length(rownames(merged_new[['SCT']]@scale.data))                           
[1] 15767     

length of one of the 4 samples I merged:
length(rownames(SRR8291066[['SCT']]@scale.data))                           
[1] 16644

**Comment by satijalab** [comment]
We omit genes that are detected in <5 cells (5 is the default as set by vst, but can be changed using the  min_cells parameter). 

By default,  we only return pearson residuals for genes which have high biological variance,  but this can be changed as you say.

**Comment by loverend** [comment]
Sorry is this in the merge function where you omit genes detected in less than <5 cells? Despite using the merge.data = TRUE as part of the merge function, this seems to be where the issue is occurring - for some reason counts are merged for the sct object and scale data is not. I got round this by separately using rowMergeSpaseMatrices to independently create the scale.data / counts slots but this is memory intensive and a bit of a faff.
