### ISSUE TITLE
Integration across treatments

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#2928]
Hello, I was looking for some advice on integration. Namely, I see many people use MNN integration across treatment types (or time courses) to correct for batch. This seems to violate several of the  assumptions of the MNN correction which state:

The batch effect is almost orthogonal to the biological subspace.
The batch-effect variation is much smaller than the biological-effect variation between different cell types.

It is easy to imagine how cell types gathered from different developmental timepoints or treated with different drugs could have batch effect that is not orthogonal to the biological subspace. If I am interpreting this correctly the "batch" in this case, would not be solely due to technological and environmental variation but could largely be contributed by real biological processes.

Since a lot of people trust your package and you do great work I was wondering if you think MNN is appropriate for combining datasets across treatments, and if you believe there is a better alternative available?

**Comment by satijalab** [comment]
On of the reasons we use CCA is that it can successfully identify anchors even when the magnitude of the batch effect is larger than the biology. Cross-species and cross-modality integration is a good example of this.

The IFNB-stimulation example on our website (which we  also  run on multiple integration tools using Seurat Wrappers) is another good example of a dataset where there are large treatment-effects, that are also cell-type specific.
