### ISSUE TITLE
Seurat spatial installation failing

### ISSUE THREAD

**Issue by ph329** [satijalab/seurat#2930]
Hi, I'm trying to update my Seurat spatial version to the latest version, but the installation keeps failing with the following error:

`installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 18619 Done                    echo 'tools:::.install_packages()'
     18620 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/r5/sjlv78ys79nc00gtf7q_dl4s0q66gc/T//RtmpvltCAU/file483c20806c30/Seurat_3.1.4.9904.tar.gz’ had non-zero exit status`

Any tips? Thank you!

**Comment by andrewwbutler** [comment]
Have you tried installing from a fresh R session?
