### ISSUE TITLE
Default behavior on Read10x changed for "-1"?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#2932]
Unless I'm missing something, when the new 'strip.suffix' was added to Read10x, this flips the previous behavior, right?  Making an argument to make this optional seems reasonable, but what's the reasoning for flipping the default on this behavior from before (which could not be disabled so was effectively TRUE)?

https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/preprocessing.R#L865

**Comment by timoast** [comment]
Changing the cell barcodes by default can cause problems for some applications (scATAC-seq for example), so we set the default to not change the barcodes. The old behaviour can be achieved with `strip.suffix=TRUE`

**Comment by bbimber** [comment]
Normalizing around what 10x creates probably is ultimately a better idea and I understand that it's an option to strip or not.  However, this unexpected change caused problems when integrating with TCR/ADT/hashing data.  It would be helpful to users if future changes from existing behavior could at least be called out in the release notes.

**Comment by timoast** [comment]
I agree the changed default should have been highlighted in the release notes, we will add it retrospectively.

**Comment by jan-glx** [comment]
*at least*
