### ISSUE TITLE
Sample combined SCtransform before integration

### ISSUE THREAD

**Issue by stevehxf** [satijalab/seurat#2934]
Hi,

Thank you for developing Seurat. Super useful! I am new in scRNAseq analysis and have a question. We have control and treatment samples and we used control as as reference to do reference-based integration and query the treatment and other controls. We expect to see that some biologically different clusters will not intermingle with each other after integration. We try 2 different approaches:

1. According to the Vignettes of Reference-based integration, we do SCtransform separately on each sample, then do the rest. 

2. What if I combined all the sample to do SCtransform and then split the object into list without further SCtransform and do the rest?

I found significant difference between this two approaches. Is the 2. approach a correct way to do this analysis? The results look better in my case though.

Please advice. 

Thank you very much!

Best regards,
Steve

**Comment by satijalab** [comment]
We would suggest doing SCTransform individually on each dataset. The method learns a model of technical noise directly from the data. These models may not be directly comparable across technologies or datasets, which is why we suggest running individually.
