### ISSUE TITLE
dimensional_reduction.R fix needed for FIt-SNE 1.2.1 version 

### ISSUE THREAD

**Issue by rafalwoycicki** [satijalab/seurat#2935]
Hello,

I wanted to run mca <- RunTSNE(mca, dims = 1:75, tsne.method = "FIt-SNE", nthreads = 4, max_iter = 2000) today but I am getting the info that version 1.2.1 is not compatibile with Seurat.
I have checked and dimensional_reduction.R holds check for version 1.0 and 1.1.0 and gives error with different version.
As I do not see it possible to download earlier version of FIt-SNE than 1.2.1, do you think that Seurat will work with 1.2.1? Can I somehow by myself change the code in dimensional_reduction.R so that it will accept 1.2.1 version of FIt-SNE?

Thank you .

Best regards,
Rafał

**Comment by liuxl18-hku** [comment]
#2792

**Comment by mojaveazure** [comment]
This has been brought to our attention. We have plans to implement support for FIt-SNE 1.2 but have other things on our plate at the moment.

**Comment by rafalwoycicki** [comment]
Thanks @mojaveazure @liuxl18-hku
