### ISSUE TITLE
Please pin ggplot version 3.2.1 to the conda package of seurat 3.1.2 to fix galaxy installs

### ISSUE THREAD

**Issue by hepcat72** [satijalab/seurat#2936]
Refer to: https://github.com/galaxyproject/tools-iuc/pull/3009

**Comment by mojaveazure** [comment]
The Conda version of Seurat is neither maintained nor supported by the Seurat developers. To use Seurat, please install it from [CRAN](https://cran.r-project.org/package=Seurat) or [GitHub](https://github.com/satijalab/seurat) using R from [CRAN](https://cran.r-project.org/), not Conda.

We have this policy as Conda messes with R and Seurat and nearly every problem (that we've seen) that exists in Seurat when using Conda to either install Seurat or R are solved by removing Conda and using R and Seurat from official sources.

**Comment by hepcat72** [comment]
Whoops. Sorry.
