### ISSUE TITLE
FindConservedMarkers with DESeq2

### ISSUE THREAD

**Issue by mihaelaolaRCSI** [satijalab/seurat#2938]
Hello, 
Thank you so much for developing Seurat and the constant support! I am looking for some help with the FindConservedMarkers function in Seurat after data integration. I have been using the function FindMarkers with test.use="DESeq2" on the integrated data with no problem, but when I run FindConservedMarkers with test.use="DESeq2" on the same data, I get an _"Error in if (invalid) { : missing value where TRUE/FALSE needed"_.

The command I am running is:
FindConservedMarkers(mouse.integrated, ident.1 = 0, grouping.var = "orig.ident", test.use = "DESeq2")

The DE per each group seems to be running correctly, as I am getting the usual DESeq2 output for each test before the error occurs, so I believe the problem occurs when trying to combine the results.

_Testing group CM5: (0) vs (1, 3, 2, 4)
converting counts to integer mode
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
Testing group CM3: (0) vs (3, 2, 1, 4)
converting counts to integer mode
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates_

I have also tried to run the FindConservedMarkers with every other possible test, including "MAST" and it is working fine for everything else. And functions FindMarkers and FindAllMarkers work fine with DESeq2, so I can't figure where the problem is.
Any help is greatly appreciated!

**Comment by satijalab** [comment]
Thanks for your question. We're actually planning to remove support for DESeq2 in the future  from Seurat. Its obviously a fantastic option for bulk analysis but in general we worry that some of the assumptions of method are not ideally suited  for single-cell analysis. For example, DESeq2 calculates the geometric mean for each gene, which can be particularly problematic with the large percentage of zeros present in scRNA-seq data.

I'll leave this issue open for comment in case people feel strongly that we should reconsider, please let us know.

**Comment by mihaelaolaRCSI** [comment]
Dear satijalab,
Thank you so much for your answer! We have been using DESeq2 for this particular dataset as the data is quite compact, separating in very close clusters, and the negative binomial distribution method showed the best results in capturing the small differences between them. 
We decided on DESeq2 for easier comparison with RNAseq data we had analysed as part of this experiment. Would you recommend the integrated negative binomial model over DESeq2 as being more robust for scRNA-seq?
Could you please also let me know if there is any way I could still use the FindConservedMarkers function with DESeq2 at this point? It would be of great help to be able to compare the final results obtained so far.

Kind regards,
Mihaela

**Comment by satijalab** [comment]
We've decided that we won't support this natively in Seurat going forward for the reasons specified above.

Of course, you can always run DESeq separately in both conditions, and intersect the results - which is the logic behind FindConservedMarkers.

Apologies for that and thanks
