### ISSUE TITLE
FindNeighbors has no output

### ISSUE THREAD

**Issue by giderk** [satijalab/seurat#2939]
I really like this package, and this is my first issue with it. Using the latest release of Seurat 3.1.5 with R version 3.6.0, and following the [guided clustering tutorial](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html) step-by-step, when I get to the step 'pbmc <- FindNeighbors(pbmc, dims = 1:10)' there is no discernible output. The help pages indicate that 'pbmc@snn' should be filled, but it doesn't exist, nor is there anything populated into 'pbmc@neighbors'. All that I can see from running the FindNeighbors step is the following verbose text...
```
> pbmc <- FindNeighbors(pbmc, dims = 1:10)
Computing nearest neighbor graph
Computing SNN
```
Any ideas what is going on? Thanks for any help.

**Comment by mihaelaolaRCSI** [comment]
Hi giderk,
I find this information in pbmc@graphs, two Graph objects called RNA_nn and RNA_snn. Is this what you are looking for?

**Comment by mojaveazure** [comment]
Apologies for the documentation mismatch; the graphs are stored in the `graphs` slot of the `Seruat` object. You can find the names of all graphs, assays, and dimensional reductions by calling `names` on the `Seurat` object

```R
names(pbmc)
```

Graphs are typically named `assay_method` (eg. `RNA_snn` for an SNN graph computed using the RNA assay). You can filter the results of `names` to just graphs with the following:

```R
Filter(f = function(x) inherits(pbmc[[x]], "Graph"), names(pbmc))
```

**Comment by giderk** [comment]
Thank you for clarifying!
