### ISSUE TITLE
Issue with regressing out cell cycle phase

### ISSUE THREAD

**Issue by alessia-catozzi** [satijalab/seurat#2940]
Hi Seurat team,

Thank you for developing this useful tool in the first place! I am new to scRNAseq and your package has made learning the pipeline for analysis quite easy, I have to say.
I have a question regarding the regression of cell cycle phase from a scRNAseq dataset I am analysing. I am using your SCTransform and cell cycle scoring vignettes (https://satijalab.org/seurat/v3.1/sctransform_vignette.html and https://satijalab.org/seurat/v3.1/cell_cycle_vignette.html) to normalize the data and regressing out cell cycle related effects. To validate this I run PCA before and after regressing out cell cycle related effects. 

In the PCA plot after regressing out cell cycle related effects, I still see quite a big influence from the G2M phase. If I go on to run UMAP or tSNE after that, I see that most of the cells still cluster based on their cell cycle phase (and the G2M cells are actually detected as a separate cluster when running clustering analysis). 

Any reason you think this might happen and do you have any suggestions? 

Here is the code I am using:
```
# calculate cell cycle scores and visualize in PCA

seurat_phase <- NormalizeData(seurat_filtered, normalization.method = "LogNormalize", scale.factor = 10000)
seurat_phase <- CellCycleScoring(seurat_phase, 
                                 g2m.features = g2m.genes, 
                                 s.features = s.genes)
seurat_phase <- FindVariableFeatures(seurat_phase, 
                     selection.method = "vst",
                     nfeatures = 2000, 
                     verbose = FALSE)
seurat_phase <- ScaleData(seurat_phase)

# Compute PCA based on cc genes

seurat_phase <- RunPCA(seurat_phase, features = c(s.genes, g2m.genes))
DimPlot(seurat_phase, reduction = "pca", group.by = "Phase") +
  ggtitle("LogNormalized data")

```
Output:
![image](https://user-images.githubusercontent.com/64639771/80801512-f3d9e280-8bac-11ea-8e3c-ac8cb0570930.png)

```
# regress out cell cycle effects

seurat_sct <- SCTransform(seurat_phase, vars.to.regress = "Phase")
seurat_sct <- RunPCA(seurat_sct, assasy = "SCT", features = c(s.genes, g2m.genes))
DimPlot(seurat_sct, reduction = "pca", group.by = "Phase")

```
Output:
![image](https://user-images.githubusercontent.com/64639771/80801214-ebcd7300-8bab-11ea-92c8-71a99852a09f.png)

UMAP plot showing that cells in G2M cluster together, away from cells in G1 and S phase. (note that here I have done: RunPCA on all features, and then runUMAP).
![image](https://user-images.githubusercontent.com/64639771/80801735-96926100-8bad-11ea-95ee-6bb94917a037.png)

**Comment by satijalab** [comment]
We would recommend regressing on the S.Score and G2M.score instead of Phase. I imagine that will solve your problem. If not, please reopen this issue and we'll take a closer look (and perhaps ask you to send us your dataset).
