### ISSUE TITLE
Finding marker genes across different samples

### ISSUE THREAD

**Issue by ahmedabbas81** [satijalab/seurat#2941]
Hello,

I have 2 scRNA-seq samples of diff ages. I integrated the two samples as in https://satijalab.org/seurat/v3.0/integration.html

and then, I use FindMarkers to see markers across diff cell types in the integrated object

However, I noticed that there are negative values in the  cells belonging to one sample in the integrated assay, the data entry.

Is the presence of these negative values normal? And do these negative values affect the accuracy of output of FindMarkers?

Thanks

Thanks

**Comment by ahmedabbas81** [comment]
Should I use the RNA assay and the results of FindMarkers will be fine across the two integrated samples?

**Comment by mojaveazure** [comment]
Please see https://github.com/satijalab/seurat/issues/1717#issuecomment-504458665 for a discussion on when to use the RNA assay and when to use the integrated assay
