### ISSUE TITLE
Assign groups to a Seurat object

### ISSUE THREAD

**Issue by eduardobonavita** [satijalab/seurat#2942]
Hi, I anticipate that I am very new to R coding and I only recently started using Seurat to analyze a scRNAseq dataset that I have. 
Thanks to the help of the tutorial vignette present on Seurat website I managed to do run everything, but I am now unable to assign the cells to a group. 

In other words, I have some cell barcodes like AAACCCAAGGTCATAA-1 (ending in 1 and corresponding to sample 1), AAACCCAAGGTAATAT-2 (ending in 1 and corresponding to sample 2) and  AAACCCAAGGTTAAGA-3 (ending in 1 and corresponding to sample 3) in the same run. 
I am sure there is a way to assign the sample name to a group of cells but I cannot find the command line to do this....
Can someone help me?

**Comment by timoast** [comment]
If you set `names.field=2` in CreateSeuratObject it will pull this information from the cell barcodes and store it as the initial identities for the object. See the documentation for CreateSeuratObject: https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/CreateSeuratObject
