### ISSUE TITLE
Warning: Identity: 22 not present in group InjCtx2

### ISSUE THREAD

**Issue by Ruei-Jen** [satijalab/seurat#2943]
Hi Seurat team,

I used the following codes for finding conserved markers for Cluster 22:
Ctx.markers22 <- FindConservedMarkers(Ctx.com, ident.1 = 22, grouping.var = "orig.ident", verbose = FALSE)

The error message I got was:
Warning: Identity: 22 not present in group InjCtx2. Skipping InjCtx2
Error in FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  : 
  Cell group 1 has fewer than 3 cells

How can I fix the error? What codes shall I use to skip a group and to ignore the group that has less than 3 cells?

Thank you in advance for your help!

**Comment by andrewwbutler** [comment]
Hi,

You can try lowering the `min.cells.group` parameter.
