### ISSUE TITLE
Error while installing 'Seurat' from GitHub

### ISSUE THREAD

**Issue by Roopali24** [satijalab/seurat#2945]
Hi,

I am trying to install Seurat v3.2 via GitHub and I get the following error:

ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Seurat’
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T//Rtmp5PwTIS/filed2397252a9f6/Seurat_3.1.4.9904.tar.gz’ had non-zero exit status.

Then I remove the '00LOCK-Seurat' folder and retry and then I get this error:

installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 55350 Done                    echo 'tools:::.install_packages()'
     55351 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T//Rtmp5PwTIS/filed23952facd9f/Seurat_3.1.4.9904.tar.gz’ had non-zero exit status.

Please help. What am I doing wrong?

**Comment by mojaveazure** [comment]
The error `55351 Killed: 9` makes it seem as though your computer had an error not related to Seurat itself. If you were running from RStudio, I would try again from a clean R session on the command line. If that fails, then try reinstalling R/RStudio, ensuring you're downloading R from [CRAN](cran.r-project.org/) and RStudio from [rstudio.com](https://www.rstudio.com) and that you don't have any form of Conda on your computer, then try reinstalling Seurat.

**Comment by Roopali24** [comment]
Thank you for your reply. So turns out I had miniconda. I removed it and tried installing Seurat again. This time it worked fine but now when I do library(Seurat) it gives the following message:

No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: 

So should I install it or not? I thought it is required to run Seurat.
