### ISSUE TITLE
What  determines ViolinPlot Y  axis (expression value) ?

### ISSUE THREAD

**Issue by sandbox-rgb** [satijalab/seurat#2951]
When I use Seurat to make a violin plot, the y-axis s hows expression level. Based on the violin plot function, the default slot  = data, which is the log normalized data. Then when the y-axis of the violin plot shows expression level, what is it? Is it the log normalized values? 

So to get a sense of how the gene is actually expressed should we do 2.71^(log normalized value)?

Before I thought maybe this value was the same as the one from the AverageExpression function but when I checked the values with AverageeExpression I realized they do not match up.

Thanks.

**Comment by andrewwbutler** [comment]
Hi,

Yes, `VlnPlot` is plotting the data from the `data` slot by default. In a standard workflow, this will be the log normalized data. If by actually expressed, you mean the raw count values, you can set `slot = "counts"` to have it pull the data from the `counts` slot instead.

**Comment by sandbox-rgb** [comment]
Thank you!
