### ISSUE TITLE
Best approach to compare CITE-seq with RNA expression?

### ISSUE THREAD

**Issue by smk5g5** [satijalab/seurat#2952]
When you compare gene expression of gene with the associated antibody do you use a different normalization strategy since the RNA data and CITE-seq data are normalized differently? (CITE-seq with CLR normalization and RNA with CPM normalization)

![image](https://user-images.githubusercontent.com/6811915/80929840-cc357680-8d74-11ea-9752-04c3b1ce1ce9.png)

**Comment by timoast** [comment]
You can't compare these directly as they're different modalities. Testing for a difference between means, for example, is not meaningful in this case. You can compare in other ways, for example looking at the correlation between RNA expression and protein expression.
