### ISSUE TITLE
RunMultiCCA with Seurat3 object

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#2953]
Hi, 
I have a question concerning MultiCCA. I need to batch correct some data using MultiCCA, as in Seurat 2.34. The reason is that i am running a verification experiment to confirm findings made with older data analysed with MultiCCA, as in Seurat 2.34. this old data yielded a number of DE genes when comparing two groups. When running the verification data on Seurat 3 using the new batch correction methods, i am not able to find back the same DE genes. 
Therefore i would like to run this new dataset on Seurat2, correct it with multiCCA, and see wehtehr i can reproduce my old findings. 
I have tried using the new surat object in Seurat 2 but this does not work as some slots are not available, as "hvg" are not present n Seurat objects. 
Could you please provide me some help as how to run the following Seurat 2 code with a Seurat 3 object: 

ob.list <- list(Child1, Child2, Child3, Child4,Child5, Child6, Child7, Child8, Child9, Child10)
genes.use <- c()
for (i in 1:length(ob.list)) {
  genes.use <- c(genes.use, head(rownames(ob.list[[i]]@hvg.info), 1000))
}
genes.use <- names(which(table(genes.use) > 1))
for (i in 1:length(ob.list)) {
  genes.use <- genes.use[genes.use %in% rownames(ob.list[[i]]@scale.data)]
}
# Run multi-set CCA
object.integrated <- RunMultiCCA(ob.list, genes.use = genes.use, num.ccs = 15)

Thanks a lot!! 
annecar

**Comment by andrewwbutler** [comment]
Hi,

The Seurat 3 object is not backwards compatible with Seurat 2 (hence the major version increase). In this scenario, I would recommend performing the same analysis using just Seurat v2 for the entire analysis. It will be much more straightforward that way.

**Comment by annecar** [comment]
Yes i tought of that, but wanted to be sure there eis no easier way . Thanks !!


Anne Eugster, PhD
Scientist AG Bonifacio

CRTD - Center for Regenerative Therapies TU Dresden
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de<mailto:a.eugster@crt-dresden.de>
Webpage: www.crt-dresden.de<http://www.crt-dresden.de>




On 8. May 2020, at 17:46, Andrew Butler <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

The Seurat 3 object is not backwards compatible with Seurat 2 (hence the major version increase). In this scenario, I would recommend performing the same analysis using just Seurat v2 for the entire analysis. It will be much more straightforward that way.
