### ISSUE TITLE
Question about HTO count normalisation before using HTODemux()

### ISSUE THREAD

**Issue by aricht** [satijalab/seurat#2954]
Hi,

I have a question regarding the HTO count normalisation before using HTODemux().

In the Vignette "Demultiplexing with hashtag oligos (HTOs)" it is shown to use the `CLR` option in NormalizeData() that performs a centered log-ratio transformation across features (per HTO in this case, because the default setting is `margin = 1`) for normalising the HTO counts.

However, as an answer to this question (issue [2383](https://github.com/satijalab/seurat/issues/2383)) regarding a problematic data set you suggested to set `margin = 2` in NormalizeData() to then perform the centered log-ratio transformation across _cells_ instead of _features_.

My questions are:
1) When do you advise to normalise across tags and when across cells?
2) Is HTODemux() developed to deal with data normalised across cells just like data normalised across features?
3) Is there any way to normalise across both, cells and features?

We have a dataset where we observe “contamination” of cells from a different HTO after HTODemux(). If we normalise across features the hash tag where cells have overall the lowest HTO counts (compared to the cells labelled with the other hash tags) contains many false positive cells. The false positives we can detect from biological features of our sample. On the other hand, if we normalise across cells then the hash tag where cells have overall higher HTO counts contains many false positives.
This is why we try to get a better understanding about the two options of normalisation.

Thank you in advance and for the already great support!

**Comment by satijalab** [comment]
Thanks, these are good questions 

1. We advise normalizing across tags particualrly when there is substantial variation in how well each hash performs. We saw this a lot when we were doing our own conjugations (like the original hashing paper)

We advise normalizing across cells in most other cases

2. Yes, it should work in both cases

3. We don't currently support anything here yet, but do understand the potential value

**Comment by aricht** [comment]
Thank you very much!
