### ISSUE TITLE
SCTransform & downstream

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#2955]
Hi folks,

We are using SCTransform as it, indeed, preserves biological heterogeneity in our datasets. However, we have a question regarding DGE analysis. We are aware that, currently, DGE analysis is not supported for SCT (question 4 in FAQs at official Satijalab website), and that you are suggesting using RNA assay for calculating DEGs, but in that case we have following questions:
- What type of test to use in Findmarkers(), is the "negbinom" test the most appropriate one, since we have UMI-based datesets?
- Can we use SCT assays for visualisation of DEGs calculated on RNA assay? If not, does that mean that in addition to SCT we have to normalize raw counts using log transformation, and then use that data for ploting? 
- What do you think about pseudobulk approach with DESeq2? If we do simply a sum of counts across cells for samples, do we need to worry about zero inflation, mentioned here #2938

You suggestions would be greatly appreciated! 

Thank you in advance
Amel

**Comment by satijalab** [comment]
1. We do not suggest the use of negbinom, as the test does not use a regularized NB (which is essential for preserving biological heterogeneity).
2. Yes, you can visualize SCT 
3. I think that approach is reasonable, but one downside is that you may not have experimental replicates - which are quite important for DESeq.
