### ISSUE TITLE
how to improve my clusters

### ISSUE THREAD

**Issue by yaoxucpu** [satijalab/seurat#2956]
I got many clusters, more than I want. I have tried to decrease the number of variable genes used for clustering and reduce dimensionality, but there are still too many clusters. Can I decrease the resolution to 0.3? Also, is there any way to make my cluster look better?  

data6 <- RunPCA(data6, features = VariableFeatures(object = data6))
data7 <- JackStraw(data6, num.replicate = 100)
data7 <- ScoreJackStraw(data7, dims = 1:20) 
JackStrawPlot(data7, dims = 1:20, xmax = 0.3, ymax = 1)
ElbowPlot(data7)

![image](https://user-images.githubusercontent.com/64571470/80983297-6986be00-8dfa-11ea-84f2-0b14678b4d3c.png)

data8 <- FindNeighbors(data7, dims = 1:10)  #I reduced dimensionality
dataF <- FindClusters(data8, resolution = 0.3)  #To decrease the number of clusters, I decreased the resolution
data9 <- RunUMAP(dataF, dims = 1:10, max.dim=3L)
DimPlot(data9, reduction = "umap")

![image](https://user-images.githubusercontent.com/64571470/80983776-f598e580-8dfa-11ea-85fa-b3c63f81ce5c.png)

Thank you very much.

**Comment by andrewwbutler** [comment]
Hi,

Yes, you can continue to lower the clustering resolution. Ultimately though, clustering is just a tool to interpret groups of cells in a biological context so if you feel that two clusters should be merged (based on differential expression/domain-specific knowledge etc...), it's not unreasonable to manually merge them as well.

**Comment by jan-glx** [comment]
There now is also Seurat::BuildClusterTree which can be used to merge similar clusters until the desired number of clusters is reached.
