### ISSUE TITLE
FindAllMarkers, test.use = 'roc' - Returns only AUC >0.7

### ISSUE THREAD

**Issue by Drosophilist** [satijalab/seurat#2957]
Hello Satija Lab,

Using FindAllMarkers(SeuratObject, min.pct = 0.25, test.use = "roc", only.pos = TRUE) will only return genes with an AUC > 0.7. Correct? Should this be included in the documentation?
Is there a way to get all features with an AUC > 0.5?
Cheers,
Jose

**Comment by keenhl** [comment]
The default AUC is 0.7, but you can set the return.thresh parameter to use a different value when using the roc test.

**Comment by Drosophilist** [comment]
But return.thresh takes as input power and not AUC, right?
Yet, in the source code of FindAllMarkers return.thresh seems to use AUC. 
```
if ((test.use == "roc") && (return.thresh == 1e-2)) {
    return.thresh <- 0.7
```
Finding this a little bit confusing. Shouldn't return.thresh use either AUC or power?

**Comment by keenhl** [comment]
I agree, in the documentation it states that power is used, but AUC is used in the source code.  I just set return.thresh to 0 to get everything and then filter the results later, if needed.

`
if (test.use == "roc") {
        gde <- subset(
          x = gde,
          subset = (myAUC > return.thresh | myAUC < (1 - return.thresh))
`

**Comment by Drosophilist** [comment]
Thank you @keenhl That's what I'll do too.
Cheers

**Comment by satijalab** [comment]
Just adding a reminder that AUC and power are directly related (one is directly and linearly based off of the other)
