### ISSUE TITLE
subsetting aggregated scATAC-seq object, but will not plot using "split.by"

### ISSUE THREAD

**Issue by doctorjb77** [satijalab/seurat#2958]
Hello, 

I merged 8 scATAC-seq samples using aggr function in Cellranger. 
then, I embedded their sample info (gemgroup) as metadata into the object. 
Then, I subsetted the aggregated samples by their gemgroup to include just 2 samples. 

> atac_aggr_3_8 <- subset(atac_aggr, subset = gemgroup == c('3','8'))
Warning messages:
1: In `==.default`(gemgroup, c("3", "8")) :
  longer object length is not a multiple of shorter object length
2: In is.na(e1) | is.na(e2) :
  longer object length is not a multiple of shorter object length

After that, I tried to generate a Featureplot using the "split.by" function to compare the two samples, however, getting the following error message.

> FeaturePlot(atac_aggr_3_8, features = "MA0039.3", min.cutoff = 'q10', max.cutoff = 'q90', pt.size = 0.1, split.by = "gemgroup")
Error in seq.default(range[1], range[2], length.out = self$detail) : 
  'from' must be of length 1

Any suggestions? Thansks,

**Comment by andrewwbutler** [comment]
Hi,

You `subset` function call should be rewritten as:

```R
atac_aggr_3_8 <- subset(atac_aggr, subset = gemgroup %in% c('3','8'))
```
