### ISSUE TITLE
Anchor finding

### ISSUE THREAD

**Issue by coralzhang** [satijalab/seurat#2959]
Hi, 

I have two questions about the anchor finding. 
1) I read the paper supplementary materials about the CCA and the L2-normalization but just want to make sure if I understand it correctly. After CCA we should end up with a matrix of the left and right eigenvectors rbind together of dimension (n1+n2)xk, and then assess the L2 normalized distance of cells in two data using the MNN algorithm. Then those cells that are mutual nearest neighbors are defined as anchors. Is this correct?
2) In the object of output of IntegrateData function, how is the data slot generated?

**Comment by timoast** [comment]
1. Yes, correct
2. The data slot in the integrated assay contains the batch-corrected expression vectors for each cell. How this is computed is described in the section "Data integration for reference assembly" in the [paper](https://doi.org/10.1016/j.cell.2019.05.031). In short, the correction vector for each cell in the query dataset is defined as the weighted average of the k-nearest anchor cell correction vectors (the differences between the expression vectors of the two cells in the anchor pair). We subtract this correction vector from the expression vector of the cell, and repeat for all cells in the query.
