### ISSUE TITLE
Do I need to run ScaleData again for the RNA assay after Integration?

### ISSUE THREAD

**Issue by shaln** [satijalab/seurat#2960]
Hello,

I have 6 samples (3 controls, 3 treated) with only 1 cell type. Pre-processing as follows: QC with scater, normalisation using multibatchnorm in the Batchelor package, removed contaminating cells identified using SingleR, converted and merged the SCEs into one single Seurat object. This object (allsamples_list) was then read in for integration (standard workflow) using the code below: 

```
allsamples_list <- SplitObject(allsamples, split.by = "orig.ident")
controls.only_list <- c(allsamples_list[[1]],
                        allsamples_list[[5]],
                        allsamples_list[[6]])
names(controls.only_list) <- c("Cont1", "Cont2", "Cont3")

for (i in 1:length(controls.only_list)) {
  controls.only_list[[i]] <- FindVariableFeatures(controls.only_list[[i]],
                                                  selection.method = "vst",
                                                  nfeatures = 2000,
                                                  verbose = FALSE)
}

controls <- controls.only_list
controls_anchors <- FindIntegrationAnchors(object.list = controls, dims = 1:30)
controls_integrate <- IntegrateData(anchorset = controls_anchors, dims = 1:30)

# Variable features in RNA assay of the integrated object wiped (from 2000 to 0 after integration)
# Hence, set variable features of the integrated object to the intersection of the individual sample's variable features
controls_var <- intersect(intersect(controls[[1]][["RNA"]]@var.features,
                                    controls[[2]][["RNA"]]@var.features),
                          controls[[3]][["RNA"]]@var.features)
controls_integrate[["RNA"]]@var.features <- controls_var

controls_integrate <- ScaleData(controls_integrate)
controls_integrate <- RunPCA(controls_integrate)
controls_integrate <- FindNeighbors(controls_integrate, dims = 1:4)
controls_integrate <- FindClusters(controls_integrate, resolution = 0.1)
controls_integrate <- RunUMAP(controls_integrate, dims = 1:4)

DefaultAssay(controls_integrate) <- "RNA"

# Find conserved canonical markers
conserved.c30.4_0 <- FindConservedMarkers(controls_integrate, ident.1 = 0, grouping.var = "orig.ident", verbose = FALSE)
conserved.c30.4_1 <- FindConservedMarkers(controls_integrate, ident.1 = 1, grouping.var = "orig.ident", verbose = FALSE)
conserved.c30.4_2 <- FindConservedMarkers(controls_integrate, ident.1 = 2, grouping.var = "orig.ident", verbose = FALSE)
conserved.c30.4_3 <- FindConservedMarkers(controls_integrate, ident.1 = 3, grouping.var = "orig.ident", verbose = FALSE)
conserved.c30.4_4 <- FindConservedMarkers(controls_integrate, ident.1 = 4, grouping.var = "orig.ident", verbose = FALSE)

# Find cluster biomarkers
c30.4_allmarkers <- FindAllMarkers(controls_integrate)
write.csv(c30.4_allmarkers, "c30.4_allmarkers.csv")

c30.4_allmarkers.top10 <- c30.4_allmarkers %>% group_by(cluster) %>% top_n(n=10, wt=avg_logFC)
DoHeatmap(controls_integrate, features = c30.4_allmarkers.top10$gene)
```

I wanted to generate an expression heat map for the top 10 markers for each cluster, but had the following error: 

```
> DoHeatmap(controls_integrate, features = c30.4_allmarkers.top10$gene)
Error in DoHeatmap(controls_integrate, features = c30.4_allmarkers.top10$gene) : 
  No requested features found in the scale.data slot for the RNA assay.
```

I've already ran ScaleData right after IntegrateData, and from what I understand, I should be using the RNA assay for finding markers/differential gene expression analysis, hence why I changed the DefaultAssay to this prior to finding the conserved/differential markers. 

Do I need to re-run ScaleData, RunPCA, FindNeighbours, FindClusters and RunUMAP after changing the DefaultAssay to 'RNA'? Do let me know if I've misunderstood anything here.  

Thank you.

**Comment by shaln** [comment]
I noticed that this issue was previously raised in [issue #1421] but was unaddressed in the responses, and [FAQ 4](https://satijalab.org/seurat/faq) does not provide any additional info on this either. Would appreciate some clarification for this. Thank you.

**Comment by andrewwbutler** [comment]
Hi,

Here the `DoHeatmap` function is trying to pull values from the `scale.data` slot of the RNA assay. However, it doesn't look like you ran `ScaleData` on that assay and thus the slot is empty. If you want to plot a heatmap of the scaled RNA data, you only need to run `ScaleData` before making that `DoHeatmap` call (not the other functions you list).

**Comment by Ashone1992** [comment]
perform this code：DefaultAssay(Seuratdatabase) <- "integrated" rather than DefaultAssay(Seuratdatabase) <- "RNA"

**Comment by jjyotikataria** [comment]
@andrewwbutler @Ashone1992 @shaln @troels @mxposed 

I did perform scale data but its not working so. Here is the command I used. I am trying run differential gene expression between clusters in a sample.


	pbmc.data <- Read10X(data.dir = "merged/DMSO_LIB_GEX_results_GEX/filtered_feature_bc_matrix")

	pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc", min.cells = 3, min.features = 200)
	
	pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
	pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000, assay = "RNA")

	pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
	all.genes <- rownames(pbmc)
	pbmc <- ScaleData(pbmc, features = all.genes)
	pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
	pbmc <- FindNeighbors(pbmc, dims = 1:10)
	pbmc <- FindClusters(pbmc, resolution = 0.5)
  DefaultAssay(pbmc)<- "RNA"
	counts <- GetAssayData(pbmc)
	CreateSeuratObject(counts = counts,project = "SeuratProject",assay = "RNA",min.cells = 3,min.features = 200, names.field = 1, meta.data = NULL)


	hpca.data <- pbmc
	hpca.se <- HumanPrimaryCellAtlasData()
	hpca.se$label.main <- str_replace_all(hpca.se$label.main, c("NK_cell" = "NK cells", "B_cell" = "B cells", "DC" = "Dendritic cells","HSC_-G-CSF" = "HSC G-CSF", "Monocyte" = "Monocytes", "Astrocyte" = "Astrocytes", "Erythroblast" = "Erythroblasts", "Macrophage" = "Macrophages","BM" = "BMs", "MSC"="MSCs","CMP" = "CMPs","GMP" = "GMPs", "MEP"="MEPs", "Myelocyte"="Myelocytes","Neuroepithelial_cell"="Neuroepithelial cells", "T_cells" = "T cells", "iPS_cells" = "iPS cells","Endothelial_cells" = "Endothelial cells", "Tissue_stem_cells" = "Tissue stem cells","Embryonic_stem_cells" = "Embryonic stem cells","Smooth_muscle_cells" = "Smooth muscle cells","Epithelial_cells" = "Epithelial cells"))
	hpca.se$label.main[hpca.se$label.main == "HSC_CD34+"] <-"HSC CD34"
	hpca.se$label.main[hpca.se$label.main == "Pro-B cells_CD34+"] <-"Pro-B cells CD34 Pos"
	hpca.se$label.main[hpca.se$label.main == "Pre-B cells_CD34-"] <-"Pre-B cells CD34 Neg"

	pred.hesc <- SingleR(test = counts, ref = hpca.se, assay.type.test=1,
						 labels = hpca.se$label.main)
	pred.hesc.transform <- t(pred.hesc)
	hesc_cells_names <- pred.hesc.transform$labels
	hpca.data <- AddMetaData(object = hpca.data,metadata = hesc_cells_names,col.name = 'type')
	Idents(hpca.data) <- hpca.data@meta.data$type

x <- as.data.frame(table(Idents(hpca.data)))
x_filt <- x[x[2] > 20,]
cell_types <- as.vector(x_filt[['Var1']])
combi <- as.data.frame(combn(cell_types, 2))
dge_df = data.frame(S.No. = numeric(),Groups = numeric(), Upregulated = numeric(), Downregulated= numeric())
S.No. <- data.frame("S.No." = seq.int(ncol(combi)))

for (k in seq(length(combi))){
  cell_type1 <- combi[1,k]
  cell_type2 <- combi[2,k]  
  print(cell_type1)
  print(cell_type2)
  
  res <- FindMarkers(hpca.data, ident.1 = cell_type1, ident.2 = cell_type2,test.use = "MAST")
  
  
  res2 <- cbind(gene = rownames(res), res)
  row.names(res2) <- NULL
  arranged <- subset(res2,select = c(gene,pct.1,pct.2,p_val,p_val_adj,avg_log2FC))
  arranged[is.na(arranged)]="N/A"
  arranged <- arranged %>% dplyr::arrange(avg_log2FC)
  file_name <- gsub(" ","-",paste0(cell_type1,"_vs_",cell_type2))
  file_name1 <- paste0("Differential_Expression_",file_name,".xlsx")
  print(file_name1)
  
  signi <- arranged[which(arranged$p_val_adj < 0.01),]
  signi1 <- signi[which(signi$avg_log2FC >=1 | signi$avg_log2FC <=-1),]
  signi1 <- signi1 %>% dplyr::arrange(avg_log2FC)
  
  up <- sum(signi1$avg_log2FC > 0)
  down <- sum(signi1$avg_log2FC < 0)
  dge_df <- rbind(dge_df, data.frame(file_name,up,down))
  
  dge_header <- read.csv("dge_header.txt",sep="\t")
  wb <- createWorkbook()
  addWorksheet(wb, sheetName = "Header Information")
  writeData(wb, "Header Information",dge_header)
  header <- read.csv("dge_header.txt",sep="\t")
  addWorksheet(wb, sheetName = "All.Genes")
  writeData(wb, "All.Genes",arranged)
  addWorksheet(wb, sheetName = "p_val_adj < 0.01 & FC +-2")
  writeData(wb,"p_val_adj < 0.01 & FC +-2",signi1)
  saveWorkbook(wb, file = file_name1, overwrite = T)
  
  upreg <- signi[which(signi$avg_log2FC > 0),]
  downreg <- signi[which(signi$avg_log2FC <0),]
  
  upreg <- upreg %>% dplyr::arrange(desc(avg_log2FC))
  downreg <- downreg %>% dplyr::arrange(avg_log2FC)
  
  top25up <- upreg[1:25,]
  top25down <- downreg[1:25,]
  genes_heatmap <-  c(top25up$gene,top25down$gene)
  
  DoHeatmap(hpca.data, features = genes_heatmap, draw.lines = F, angle=90, size=2) + NoLegend() + ggtitle(file_name)
  
  subsetting <- subset(hpca.data, idents = c(cell_type1, cell_type2))
  subsetting@meta.data <- subsetting@meta.data %>% dplyr::arrange(type)
  
   print(file_name)
  ggplotly(DoHeatmap(subsetting,features = genes_heatmap, draw.lines = F, angle=90, size=2, label = FALSE, group.bar=F) + NoLegend() + ggtitle(file_name))
 
}


Error:
Error in DoHeatmap(hpca.data, features = genes_heatmap, draw.lines = F,  : 
  No requested features found in the scale.data slot for the RNA assay.
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> DoHeatmap

**Comment by tinakeshav** [comment]
Hi, FAQ4 is not found. Could we kindly have the updated link or a follow-up on this thread on whether/how we should get the scaled counts for RNA assay in an integrated object? Thanks a ton! 
> I noticed that this issue was previously raised in [issue #1421] but was unaddressed in the responses, and [FAQ 4](https://satijalab.org/seurat/faq) does not provide any additional info on this either. Would appreciate some clarification for this. Thank you.

**Comment by loneMT** [comment]
Do I need to re-run ScaleData, RunPCA, FindNeighbours, FindClusters and RunUMAP after changing the DefaultAssay to 'RNA'? Do let me know if I've misunderstood anything here.

I have the same question. what should i do?

**Comment by ondina-draia** [comment]
> perform this code：DefaultAssay(Seuratdatabase) <- "integrated" rather than DefaultAssay(Seuratdatabase) <- "RNA"

It's not recommended at all, you should use the RNA assay 
Written in the [ Integration tutorial from Satja lab](https://satijalab.org/seurat/articles/integration_introduction.html) and
And the recommandation Satjalab wrote as a reply also [recommandation Satjalab wrote as a reply also](https://github.com/satijalab/seurat/issues/1717#issuecomment-504458665)

**Comment by mhutchen** [comment]
I have the same problem.  Seurat object PT following usual workflow as in tutorial, including FindVariableFeatures and ScaleData.
`PT.rh<-subset(PT, idents=c("something", "something_else"))`
Then...
`DoHeatmap(PT.rh, features =some_features_that_are_for_sure_in_my_data, group.by="treatment")`
This yields the error:  Error in DoHeatmap(etc) :   No requested features found in the scale.data slot for the RNA assay.
Therefore I do the following:
`all.genes <- rownames(PT.rh)
PT.rh <- ScaleData(PT.rh, features = all.genes)
DoHeatmap(PT.rh, features =some_features_that_are_for_sure_in_my_data, group.by="treatment")`

This yields the same error:  Error in DoHeatmap(etc) :   No requested features found in the scale.data slot for the RNA assay

Although it is not a recommended practice I have done this with DefaultAssay set to "integrated" in addition to the usual "RNA".  This does not ameliorate the error.

FAQ4 as linked above still produces a 404 error as reported above.  Any help or guidance would be greatly appreciated.

**Comment by mariamnawaz1** [comment]
I am having the same issue, please help. I have tried the above suggestion of scaling the RNA assay data, 

gse <- ScaleData(gse, features = rownames(gse), assay="RNA", verbose = FALSE)
DoHeatmap(gse, features=features, assay = "RNA") 

Thanks!
