### ISSUE TITLE
Cannot load h5ad file

### ISSUE THREAD

**Issue by gbloeb** [satijalab/seurat#2961]
Attempting to load this h5ad file: 
https://cellgeni.cog.sanger.ac.uk/BenKidney_v2.1/Mature_Full_v2.1.h5ad

I get the following error
> stewart<-ReadH5AD(file = "~/Desktop/Stewartetal/Mature_Full_v2.1.h5ad")
Pulling expression matrices and metadata
Error in sparseMatrix(i = x[["indices"]][] + 1, p = x[["indptr"]][], x = x[["data"]][],  : 
  all(dims >= dims.min) is not TRUE

sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] loomR_0.2.1.9000            hdf5r_1.3.2                 R6_2.4.1                   
 [4] scater_1.12.2               ggplot2_3.3.0               SingleCellExperiment_1.6.0 
 [7] SummarizedExperiment_1.14.1 DelayedArray_0.10.0         BiocParallel_1.18.1        
[10] matrixStats_0.56.0          Biobase_2.44.0              GenomicRanges_1.36.1       
[13] GenomeInfoDb_1.20.0         IRanges_2.18.3              S4Vectors_0.22.1           
[16] BiocGenerics_0.30.0         Seurat_3.1.5.9001

**Comment by mojaveazure** [comment]
Hi,

We are transitioning our support for AnnData/H5AD files to [SeuratDisk](https://github.com/mojaveazure/seurat-disk), our new package for interfacing `Seurat` objects with single-cell HDF5-based file formats. We would very much like it if you could give this a shot for reading in your data.

You can install SeuratDisk with the following:
```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")
```

A tutorial on how to read in AnnData/H5AD files via the h5Seurat intermediate can be found [here](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html). Greater detail about the new `Convert` mechanism can be found [here](https://mojaveazure.github.io/seurat-disk/reference/Convert.html)

If you come across any bugs in reading in your HDF5 files, please post them in mojaveazure/seurat-disk#1. Please note, there are some stipulations about the format of your AnnData/H5AD posted in https://github.com/mojaveazure/seurat-disk/issues/1#issue-619215532
