### ISSUE TITLE
FindClusters, get Cluster determination score

### ISSUE THREAD

**Issue by BrunoGuillotin** [satijalab/seurat#2963]
Hi all,

I would like to know if in 'FindClusters' on Seurat there is a factor calculated for each cell that tells the confidence in the cluster attribution ?
I am using a 10x generated scRNA-seq dataset with some cells transitioning along time from one state to another and would like to get more info on determining which cells are attributed to one cluster or another.

Thanks in advance for your help .

**Comment by andrewwbutler** [comment]
Hi,

There aren't any metrics on clustering "confidence" that are reported from `FindClusters`. One metric that you could look into though for this kind of thing is the [silhouette](https://en.wikipedia.org/wiki/Silhouette_(clustering)) score. There's an implementation of this in the [cluster](https://cran.r-project.org/web/packages/cluster/index.html) package.
