### ISSUE TITLE
Barplot in R (names.arge)

### ISSUE THREAD

**Issue by sarabdn** [satijalab/seurat#2965]
I am trying to design a **barplot** with the arrival times. 
I want to name every block in the image with a certain time slot of half an hour, however when I try to use names.arge I get the following error: 
![Boxplot](https://user-images.githubusercontent.com/64911499/81190276-ead77f80-8fb7-11ea-8d6e-206c6d0fc247.png)

Error in barplot.default(z$freq, names.arg = z$x, main = "Frequency table of arrival time",  : formal argument "names.arg" matched by multiple actual arguments

**Comment by mojaveazure** [comment]
This question does not pertain to Seurat and should be asked on a more general forum.
