### ISSUE TITLE
differential expression analysis between samples but not clusters

### ISSUE THREAD

**Issue by kinali** [satijalab/seurat#2967]
Hi all,

I have two samples as naive and resistant. I just want to see differentially expressed genes between them at first (I do not want to see DE genes between clusters and I do not have cell types either). Also, I checked this tutorial https://satijalab.org/seurat/v3.1/immune_alignment.html, so it did not help me about this.

I am doing this:

` de <- merge(s2,s3,add.cell.ids=c("naive","resistant")) `
` de[["percent.mt"]] <- PercentageFeatureSet(de,pattern = '^MT-')`
`  de$percent.mt <- de$percent.mt[de$percent.mt < 7.5]`
`  de <- NormalizeData(de, normalization.method = "LogNormalize")`
`  markers <- FindMarkers(object = de,ident.1 = "naive",ident.2 = "resistant")`

   
but I am getting this error:

  Error in WhichCells.Seurat(object = object, idents = ident.2) : 
  Cannot find the following identities in the object: resistant

I would appreciate if you could help me about how to perform DE analysis between samples but not clusters. 
best,

**Comment by wzhao01** [comment]
Hi kinali,

When you merge, you are adding "naive" and "resistant" to the end of the individual cell names, but you need to create a column in the metadata for each prior to merging them. Try the following:

```
s2$sample <- "naive"
s3$sample <- "resistant"
de <- merge(s2,s3,add.cell.ids=c("naive","resistant"))
de[["percent.mt"]] <- PercentageFeatureSet(de,pattern = '^MT-')
de$percent.mt <- de$percent.mt[de$percent.mt < 7.5]
de <- NormalizeData(de, normalization.method = "LogNormalize")
Idents(de) <- "sample"
markers <- FindMarkers(object = de,ident.1 = "naive",ident.2 = "resistant")```

**Comment by kinali** [comment]
Thank you so much wzhao01!
