### ISSUE TITLE
Identification of TFs with Seurat ?

### ISSUE THREAD

**Issue by BarvauxS** [satijalab/seurat#2969]
Hi, 

I did an analyze with Seurat, I compared gene expression between treatment groups and a control group.
Now I have gene expression, I want to identify which TFs were transduced in different groups.
Does it exist a way to do that with Seurat ? Or should I use an other software ?

Thank you in advance.

**Comment by andrewwbutler** [comment]
Hi,

We don't have lists of which genes are transcription factors stored within Seurat. You will need to find that information for your specific system. Once you know that though, you could run differential expression in Seurat via `FindMarkers` and intersect that list of marker genes with your list of TFs to get a sense of which TFs are different between your groups.
