### ISSUE TITLE
How to plot italic form gene names during FeaturePlot two or more genes?

### ISSUE THREAD

**Issue by vagabond12** [satijalab/seurat#2970]
We can plot italic form gene names during FeaturePlot one gene in seurat3.0.0. But theme does not work when FeaturePlot two or more genes, then is there any method to realize it? Thank you.

**Comment by chlee-tabin** [comment]
Thanks to the `patchwork` system, the only thing to do is to change the "+" to "&" in combining the `theme`.

```
FeaturePlot( integrated.expanded, features = c("Hoxa11", "Hoxd11")) & theme( plot.title = element_text( face = "italic") )
```

**Comment by vagabond12** [comment]
It does not work for me.

Error in FeaturePlot(pbmc, features = c("Hoxa11", "Hoxd11")) & theme(plot.title = element_text(face = "italic")) : 
  operations are possible only for numeric, logical or complex types

![image](https://user-images.githubusercontent.com/24886447/81311591-2fe2db00-90b8-11ea-81a1-c098b500cf2f.png)

**Comment by samuel-marsh** [comment]
Hi,

Patchwork compatibility was implemented in Seurat 3.1.4.  Prior to that it was not possible to theme plots when supplying multiple features from within the Seurat function.  To solve your issue you can either upgrade to Seurat v 3.1.4 or greater or you can plot features independently and supply the `theme(plot.title = element_text( face = "italic")` as you normally would for ggplot2 object using the `+` symbol.  Individual plots can then be grouped either using cowplot, patchwork, etc.

Best,
Sam

**Comment by timoast** [comment]
@vagabond12 you also need to load the packwork package: `library(patchwork)`

**Comment by vagabond12** [comment]
@timoast @chlee-tabin @samuel-marsh  Thank you very much. Now I know how use patchwork package and new version of Seurat. You all help me a lot. Thank you very much.
