### ISSUE TITLE
Issue with four different samples

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#2971]
Hello I just have a question on getting some graphing features to work since my code just gives me one dot in the center. 
I have four groups Young_Male Young_Female Old_Male and Old_Female which are under orig.ident  I have not identified clusters yet. 

object$celltype.age <- paste(Idents(object), object$orig.ident, sep = "_")
object$celltype <- Idents(object)
Idents(object) <- "celltype.age"
differences <- FindMarkers(object, ident.1 = "3_Young_Male", ident.3 = "3_Old_Male", verbose = FALSE)
head(differences, n = 15)

**Comment by andrewwbutler** [comment]
Hi,

What exactly is the issue here? None of the commands you listed are plotting functions.

**Comment by aelias1** [comment]
Yes.

**Comment by andrewwbutler** [comment]
I'm still not sure what the issue is here. Could you please elaborate and provide a reproducible example?
