### ISSUE TITLE
Allen brain atlas to seurat

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#2972]
Hello,

I was wondering how you are able to use the identities used from Allen brain atlas to define clusters in your own data set.  If you have a vignette on how to do this with a similar data set, I would greatly appreciate it.

**Comment by andrewwbutler** [comment]
Hi,

What you will need to do for this is to add the identities from the Allen (or any other source) into a meta.data column of the Seurat object. I'm not sure exactly how the dataset you're referring to is formatted but the workflow should be similar regardless. Basically what you want to do is

```R
meta.data <- read.table("metadatafile.csv") 
seurat.object <- AddMetaData(seurat.object, metadata = meta.data)
Idents(seurat.object) <- "identity.column.name"
```

You may need to adjust how exactly the data is read in and make sure the cell names match the cell names in the Seurat object.
