### ISSUE TITLE
Merging question.

### ISSUE THREAD

**Issue by vlcm2019** [satijalab/seurat#2974]
I am a beginner with single cell analysis. I had the initial analysis completed through an outside source and I am primarily using the Robj file provided to look at the clusters and the gene expression profiles across clusters. I am trying to see if there is a way to merge two data sets from the Robj file to compare the samples. Any advice would be greatly appreciated. Thank you.

**Comment by andrewwbutler** [comment]
Hi,

If you just want to merge two Seurat objects, please see the `merge` function - outlined in [this vignette](https://satijalab.org/seurat/merge_vignette.html). If you have some sort of confounding differences between the samples, an integration workflow may be more appropriate. We have an example vignette of that [here](https://satijalab.org/seurat/integration.html).

**Comment by vlcm2019** [comment]
Hi,

Thank you for the quick response. I tried to do integration following the vignette but I am getting the warning below. So I am not sure what is going on, and if should proceed further. Any guidance would be much appreciated.

load("~/Robj/sample_15-2013_final.Robj")
> s1 <- sample

> load("~/Robj/sample_14-0009_final.Robj")
> s2 <- sample

> sample_int <- merge(x = s1, y = s2)
Warning message:
In CheckDuplicateCellNames(object.list = objects) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

> sample.list <- SplitObject(sample_int, split.by = "orig.ident")

> sample.list <- sample.list[c("15-2013", "14-0009")]

> for (i in 1:length(sample.list)) {
+     sample.list[[i]] <- SCTransform(sample.list[[i]], verbose = FALSE)
+ }
There were 50 or more warnings (use warnings() to see the first 50)

> warnings()
Warning messages:
1: In theta.ml(y = y, mu = fit$fitted) : iteration limit reached

**Comment by andrewwbutler** [comment]
This warning is generally safe to ignore. Please see https://github.com/ChristophH/sctransform/issues/25 for further discussion.

**Comment by vlcm2019** [comment]
Thank you for the clarification.

**Comment by vlcm2019** [comment]
Sorry to keep bugging. If I am trying to identify common vs. different cell types across multiple patient samples, just by making a comparison within the patient samples and not using a reference dataset would you recommend that I just use the merge function for this analysis? The samples were all prepared and analyzed in a similar manner. Thank you.
