### ISSUE TITLE
Seurat Aborting R

### ISSUE THREAD

**Issue by smallkamal** [satijalab/seurat#2975]
Whenever I'm trying to run library(Seurat), RStudio is aborting. I am also having an issue in the R program itself. I've tried the whole remove and install 'reticulate' and seurat process, but it hasn't worked. Any suggestions?

**Comment by andrewwbutler** [comment]
Hi,

Have you tried any of the suggestions in issue #2769 (in particular, removing the conda installation)? If those don't resolve the issue, could you post the output of `sessionInfo()` here?

**Comment by smallkamal** [comment]
I have deleted anaconda, but I think it might still be on my computer. How do I completely remove it from my system? And for some reason, I downloaded Seurat, R and Rstudio on a different account on the same computer, and when I called install.packages('Seurat'), it asked me if I want to install Miniconda. I said yes and then it worked fine. (keep in mind, this is on a different account. There is still problems on my main account).

**Comment by mojaveazure** [comment]
Anaconda is hard to fully remove as it messes with your environment PATH. If you're on macOS or Linux, check your `~/.profile`, `~/.bash_profile`, or `~/.bashrc` files to see if there are any lines that have "conda" in them and remove the offending lines. For Windows, see [this](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) for modifying the system PATH. This might help if you're having problems with R itself on your main account. If not, please re-open, including system information and what error you get with R on your main account.

When installing reticulate, it asks (sometimes) if you want to install Miniconda. We don't have the ability to prevent this from happening, but I would strongly suggest selecting "no"

**Comment by EvanLemire** [comment]
Hey I am still having this issue on mac as well. I don't have r-miniconda on my computer, and I can't find a reference to conda in any of those three files. Seurat crashes my R session in the terminal whenever it is loaded, but seems to work in R studio. Have there been any further solutions to this issue?
