### ISSUE TITLE
Gene names and ensembl IDs 

### ISSUE THREAD

**Issue by willrosenow** [satijalab/seurat#2976]
Hello,

I ran through the Seurat vignette with Ensembl IDs. However, for our downstream analyses some require gene names while others require Ensembl IDs. Is there a way to easily convert between IDs and names in the Seurat object after QC, transformation, etc. ? I've tried running 2 versions from the beginning by changing the gene.column option, but they give slightly different UMAPs. It would be great to have the same UMAP for further analyses.

Thanks,
Will

**Comment by satijalab** [comment]
You can easily convert between gene names and ensembl ids using ENSEMBL BioMart, but we don't natively support this in Seurat. The reason the UMAPs are slightly different is that there is not always a 1:1 correspondence between ENSEMBL ID and gene name - so inevitably there will be minor discrepancies.
