### ISSUE TITLE
Best way to select integration features when integrating two integrated datasets

### ISSUE THREAD

**Issue by liuxl18-hku** [satijalab/seurat#2979]
Dear developers,

I am not reporting bugs, just want to find a proper way to select integration features for my wired application context (two rounds of integration, and we are doing that because of #1029)

Here is the context, I got two integrated dataset, each of them have 3000 features available for the default `integrated` assay, which I think they are highly variable features only.

Not sure `SelectIntegrationFeatures` is also designed for this case. From what I can see, the piece of code from `SelectIntegrationFeatures` below will sharply decrease the number of output features in this case, while in the context of integrating `SCTransform`ed datasets with `rownames` is actually returning all features (I mean NOT only `VariableFeatures`), same constrains seems too stringent for two "integrated" dataset.

https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/integration.R#L1441-L1443

bless~
Xingliang

**Comment by satijalab** [comment]
The ```SelectIntegrationFeatures``` is the appropriate one to use here. The code you listed intersects the rownames of the data slot, which represents all genes that were measured in the dataset (not just variable ones). This is true in both the SCTransform and regular workflows.

However, you are certainly welcome to use any feature set you would like - for example, you can take the union of the two variable feature sets if you would like to try that option.
