### ISSUE TITLE
MergeSeurat does not normalize

### ISSUE THREAD

**Issue by plijnzaad** [satijalab/seurat#298]
My understanding is that MergeSeurat only merges two objects, roughly by concatenating their data. I would therefore expect that also the normalized data is merged, yet after a merge, the `@data` slot is identical to the `@raw.data` slot, which is very unexpected (and e.g. leads to infinities during `FindVariableGenes`. I would seem logical that, by default, after a merge, the normalized data is the merged version of the individual normalized data.

**Comment by leonfodoulian** [comment]
Hi,

The `MergeSeurat()` function includes the `do.normalize` argument, with TRUE as default input. More information in the documentation of the function (simply run `?Seurat::MergeSeurat` in R).

Best,
Leon

**Comment by plijnzaad** [comment]
ah sorry, yes, my bad. This was hidden in a function I wrote to merge more than two sets (which BTW would be very nice to have, since merging it in pairs leads to weird cell names)
