### ISSUE TITLE
Seurat V3  can not  use  add.iter >0 

### ISSUE THREAD

**Issue by tuqiang2014** [satijalab/seurat#2982]
when i use to adds additional iterations :

```
Seurat::RunTSNE(pbmc_small,perplexity  = 5, check_duplicates = FALSE, add.iter=3)
```

i get  error 

```
Error in tsne(X = object, initial_config = as.matrix(x = tsne.data), max_iter = add.iter,  : 
  argument not use(pca = FALSE, check_duplicates = FALSE)
```

when run  

```
Seurat::RunTSNE(pbmc_small,perplexity  = 5, check_duplicates = FALSE, add.iter=0)

An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features)
 2 dimensional reductions calculated: pca, tsne
```

**Comment by timoast** [comment]
Hi, the `add.iter` parameter is really just left over from older versions and is not needed anymore with the newer, faster versions of tSNE (barnes hut and FItSNE). This is non-functional and will be removed, if you want to increase the number of iterations you can pass the `max_iter` parameter through `RunTSNE()` to the `Rtsne()` or `fftRtsne()` function call.
