### ISSUE TITLE
Does integration influence expression?

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#2983]
I integrated mutipul datasets and calculated the defferentially expressed genes (DE). However, I wander whether integration could influence (change) the expression data and thus results in different DE compared to 'merge' function ?

**Comment by yuhanH** [comment]
HI, 
Right. The integration process will change the gene expression value to eliminate the batch effects.
We suggest you do the differential analysis on the `RNA` assays after the integration instead of doing differential analysis in the `integrated` assay.

**Comment by grimwoo** [comment]
@yuhanH Thanks a lot!
