### ISSUE TITLE
differential expression from scRNAseq data using expression of single gene

### ISSUE THREAD

**Issue by saurabhJpradhan** [satijalab/seurat#2985]
I have a 10x datasets from zebra fish (single sample) in which i have over expressed factor of interest in a mosaic manner. In principle, i have cells which express different level of factor of interest.  I tried routine pipeline but since my factor is expressed in mosaic manner it is not falling into one particular cluster. This factor is not expressed at this stage in wild type scenario. Is there any way, I can identify cells expressing my factor and perform DE against cells which are not expressing factor of interest. Purpose of performing this experiment was to understand whether gene regulation by this factor is cell autonomous or non cell autonomous.

Many thanks and regards,
Saurabh

**Comment by satijalab** [comment]
You can identify cell subsets based on a single gene using the command below
- more information at https://satijalab.org/seurat/v3.0/interaction_vignette.html
```
# Can I create a Seurat object based on expression of a feature or value in object metadata?
subset(pbmc, subset = MS4A1 > 1)
```
