### ISSUE TITLE
FeaturePlot(...., split.by, combine=FALSE) - plot x/y axis coordinates and title

### ISSUE THREAD

**Issue by Hoxd13** [satijalab/seurat#2987]
Hi Seurat people,

I have a question for you, sort of spinning out of #1260 and #2550 I guess.

Whenever I use _FeaturePlot, split.by_ a factor containing more than 2 levels, the final combined patchworked ggplot is progressively stacked (horizontally). It is therefore of very limited use - see attached plot A below (6x level)

[A.pdf](https://github.com/satijalab/seurat/files/4610786/A.pdf)

Because the ncol argument is not taken into account when _split.by_ is active, I'm bypassing this issue by using the _combine=FALSE_ argument to return a series of individual plots.

It's working well except that the UMAP/TSNE coordinates and plot title is not systematically printed on the x and y axis of each of the returned plots. This is then in turn impacting the scales of the individual plots and can't be easily solved in ggplot - see attached plots in B below for illustration.

[B.pdf](https://github.com/satijalab/seurat/files/4610787/B.pdf)

**My question is therefore the following; could Seurat print systematically the x-y axis coordinates and titles/legends on all the FeaturePlots generated by _split.by, combine=FALSE_?**

Thanks for any inputs & feedbacks
Cheers

Hoxd13

**Comment by satijalab** [comment]
Thanks for bringing this up. We'll try to fix in the near-mid term and respond when we do

**Comment by aubreyghoward** [comment]
I have been bypassing this issue with by calling lapply over the combine=false plot object and setting the function to the ggplot manipulations i wish to make. Then combining the plot Combine plots. That might be a partial solution to re-centering your plot titles at least.

**Comment by Hoxd13** [comment]
@satijalab 
Thanks for the reply ... and for the tool you're building and maintaining!

@aubreyghoward 
Absolutely, it works well for the titles but I couldn't find a way to apply it to solve the x-axis issue.
This is actually what prompted this post.

**Comment by aubreyghoward** [comment]
@Hoxd13 I can confirm the issue now and have been able to replicate it with my own code. Thanks for the insight. (Also I love your username and wish I had been so cleaver :) )

**Comment by Hoxd13** [comment]
@aubreyghoward 
Nothing like a little piece of old school genetic ;)

**Comment by rsatija** [comment]
Apologies as its been a while since we responded. I think when using split.by we want to use facet_wrap, which does not systematically replot axes labels and titles. If you want to modify this behavior the lapply functionality is exactly the way  to go, basically making individual FeaturePlots and then plotting them together.
