### ISSUE TITLE
Generating treatment-specific VlnPlots from combined object

### ISSUE THREAD

**Issue by w2niva** [satijalab/seurat#2988]
Hi,

I have 8 samples (4 treatments and 2 replicates) which I have as a combined object. I want to see the expression of specific genes but generate separate Vlnplots for treatments. Currently, split.by in Vlnplot overlays all the treatments. Analysing 8 samples together is a problem with these plots. Is there any way I can generate 8 VlnPlots or VlnPlots for desired treatments from the combined object?

**Comment by yuhanH** [comment]
One easy strategy to use is to subset your object to your desired treatment before the VlnPlots. 
```
obj.sub <- subset( obj, subset = treatment == "T1")
```
You can change the subset condition to fit your purpose.
