### ISSUE TITLE
Split Seurat object by a particular gene's expression

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#2989]
I want to run differential expression to compare geneA positive cells vs geneA negative cells in my seurat object. Is there a way I can split the seurat object into two parts based on gene A's expression? Or is there a way to reassign the "ident" so that there are only two idents - one idnet that expresses gene A, and the other that doesn't?

Any help would be appreciated!
Thank you!

**Comment by andrewwbutler** [comment]
Hi,

Basically, what you want is a new meta.data column that tells you for each cell whether it is above or below a certain threshold for that gene. One way to do that would be to use `WhichCells` to determine which cells fall into one of your two categories. Here's an example using `pbmc_small` and the `LYZ` gene.

```R
pbmc_small$lyz.group <- "lyz.pos"
pbmc_small$lyz.group[WhichCells(pbmc_small, expression = LYZ < 5)] <- "lyz.neg"
Idents(pbmc_small) <- "lyz.group"
```

How you set that threshold though is up to you.
