### ISSUE TITLE
When running the SCT integration what assay is the integrated matrix saved too?

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#2990]
When you run IntegrateData(foo, normalization.method = "SCT") where is the new integrated assay saved?

**Comment by liuxl18-hku** [comment]
I may misunderstand, but you can check

```r
foo <- IntegrateData(foo, normalization.method = "SCT")
```

`foo[['integrated']]` suppose to be the integrated assay.
`foo[['integrated']]@scale.data` slot would be the harmonized residuals used for dim reduction.

bless~

**Comment by Connorr0** [comment]
Something must have been weird last time I ran this. The integrated assay has now appeared.
