### ISSUE TITLE
IntegrateData crashes: Need S4 class dgRMatrix for a sparse matrix

### ISSUE THREAD

**Issue by rubenchazarra** [satijalab/seurat#2991]
Hello everyone,
I'm trying to perform Seurat 3 batch integration of a dataset composed of 3 batches, 1000 cells each. The **IntegrateData** function crasses with the error:
`Error in RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names, : Need S4 class dgRMatrix for a sparse matrix`

This is how I'm performing the integration:
```
suppressPackageStartupMessages(require(Seurat))
dataset <- as.Seurat(sce, counts = "logcounts", data = "logcounts")
DefaultAssay(dataset) <- "RNA"
batch_list <- SplitObject(dataset, split.by = "Batch")
for (i in 1:length(batch_list)) {
  batch_list[[i]] <- NormalizeData(object = batch_list[[i]], verbose = FALSE)
  batch_list[[i]] <- FindVariableFeatures(object = batch_list[[i]],
                                          selection.method = "dispersion", nfeatures = 2000, verbose = FALSE)
}
anchors <- FindIntegrationAnchors(object.list = batch_list, dims = 1:30,  k.filter = k_filter)
integrated <- IntegrateData(anchorset = anchors, dims = 1:30)
```
Strangely, this error only happens when there are 3 or more batches, with 2 batches worked fine without error. 
I have checked the comments on similari issue #1355, but got no clue about what may be causing the error. 
My belief is that some incompatibilities happen when I convert SCE object to Seurat via `as.Seurat`.  Although the same error appears if I create the object from scratch via `CreateSeuratObject`.
Here I attach my input SingleCellExperiment object as a ZIP file.
[sce.gz](https://github.com/satijalab/seurat/files/4615070/sce.gz)

**Comment by satijalab** [comment]
Thanks for sending the data - this is a bug on our end and we're taking a look

**Comment by rubenchazarra** [comment]
Strangely, `IntegrateData` function ran succesfuly  for any other number of cells a part from 1000.

**Comment by timoast** [comment]
Hi @rubenchazarra, sorry for the delay but this should be fixed now on the develop branch
