### ISSUE TITLE
names(new.cluster.ids)

### ISSUE THREAD

**Issue by ibseq** [satijalab/seurat#2992]
hello, 
I'd like to make clusters based on expression of specific markers - and only have those, then name them 

I'm following the guided tutorial on PBMC and I'm here"new.cluster.ids <- c("Naive CD4 T", "Memory CD4 T", "CD14+ Mono", "B", "CD8 T", "FCGR3A+ Mono", 
    "NK", "DC", "Platelet")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
DimPlot(pbmc, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()

how can I before this step generate my own clusters?

thanks
ib

**Comment by timoast** [comment]
The clustering workflow is shown in the Seurat [vignettes](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html). To use a specific set of genes for clustering cell, set those genes as the variable features for the object.
