### ISSUE TITLE
SCTransform slot. 

### ISSUE THREAD

**Issue by loverend** [satijalab/seurat#2993]
Hi could you clarify please: 

Will SCTransfrom use seurat_object[['RNA']]@counts as default? I couldn't find this explicitly stated as part of the arguments/hidden vst functions I just want to make sure that if I also run straight up normalisation / scale data (for some quick visualisation/ clustering) on the same object that these slots  will then not be utilised if I then instead run SCTransform. 

Thanks!

**Comment by basilkhuder** [comment]
In the code for the ```SCTransform()``` , which can be seen [here](https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/preprocessing.R#L1224),  ```GetAssayData``` is pulling from ```slot = "counts"```

**Comment by basilkhuder** [comment]
In the code for the ```SCTransform()``` , which can be seen [here](https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/preprocessing.R#L1224),  ```GetAssayData``` within the function is pulling from ```slot = "counts"``` and not a normalized slot.

**Comment by loverend** [comment]
Thank you! Much appreciated.

**Comment by yuhanH** [comment]
@basilkhuder  Thanks for your reply.
