### ISSUE TITLE
Differential gene expression across 3 or more conditions

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#2994]
Hello Seurat Team,

Is it possible to perform differential gene expression across 3 more more conditions (time points) in Seurat?

**Comment by satijalab** [comment]
We only support pairwise differential expression tests. I'm not sure how we would implement a 3-way test, but if you have conditions A, B, and C - you can test for A vs (B, C). You can simply specify multiple cell types in ident.1 or ident.2
