### ISSUE TITLE
Analysis question: integrating different library preps

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#2996]
Hello!

As always, thank you for building this beautiful package and being so available on Github!

I had an analysis question:
When integrating datasets, would you consider it valid to integrate datasets that use different library prep kits, such as 10x genomics v2 and v3 chemistries? Your website has a vignette for integrating multiple different single cell technologies, so I assume that two different version of a prep kit from the same technology would be okay. I read that integration attempts to remove batch effects but preserve biological differences, but I wanted to double check that you would recommend this. 

Thanks!

**Comment by kleurless** [comment]
Have you read this paper on [Comprehensive Integration of Single-Cell Data](https://www-sciencedirect-com.proxy.library.uu.nl/science/article/pii/S0092867419305598?via%3Dihub#sec4.3.2) by Butler and Satija (2019)? They comment and eloborate on your question.
