### ISSUE TITLE
Error: cannot allocate vector of size 790.8 Gb

### ISSUE THREAD

**Issue by mamtagiri** [satijalab/seurat#2997]
Hi guys,

I have scaled multiple samples using the same computational power that Iam using right now. But somehow even scaling 1 sample I get this error:

Error: cannot allocate vector of size 790.8 Gb

I tried using future as well but no luck there. I get error different errors with this.

**Comment by kleurless** [comment]
It sounds like this is a memory issue rather than an actual Seurat issue. You might want to look in to your R settings and current R-session.

"Error messages beginning cannot allocate vector of size indicate a failure to obtain memory, either because the size exceeded the address-space limit for a process or, more likely, because the system was unable to provide the memory. Note that on a 32-bit build there may well be enough free memory available, but not a large enough contiguous block of address space into which to map it."

**Comment by timoast** [comment]
@mamtagiri how many cells are in your dataset, and how many genes are you scaling? In most cases scaling only the variable features is needed and reduces the memory requirements substantially. Can you provide the full code you're running?

**Comment by Dragonmasterx87** [comment]
So guys I dunno if this is helpful, but I have run into this issue before over 10K cells as well. I started having this issue in the days of Seruat v2.4, and later on especially if using SCTransform. So I do this:

```
# Adjust Memory parameters
memory.limit()
memory.limit(27000) # this is in MB and only works in 64bit R, most optimal on centOS or ubuntu 
```

Decreasing the mem limit gives me the error again, so I assume adjusting the memory allocation helps, especially if you are not working on an HPC in the background. I feel for you us mere mortals have memory issues lol.

Jokes apart, Tim is right, you are probably doing:

```
# Scaling all genes
IAmGroot <- ScaleData(IAmGroot, features = all.genes)

# Do this to let Seurat auto to Var genes only
IAmGroot <- ScaleData(IAmGroot)
```
In the early days when I knew nothing, I would scale before lunch and it would run for like an hour. Lmao, now I look back and think what a noob and SMH. Luckily RAM modules and processors cant cuss.

🐲

**Comment by mamtagiri** [comment]
haha.. thanks for sharing your experience.
I changed Renviron and also did gc(reset=TRUE), not sure which one worked but now I can actually do 
IAmGroot <- ScaleData(IAmGroot, features = all.genes) 
on my local computer 16GB computer.

**Comment by mjryan110** [comment]
@mamtagiri how did you switch to Reviron? I am having a similar issue in my R Studio and cannot get it to run. Tried gc(reset = TRUE) but getting the same error: "Error: cannot allocate vector of size 780.6 Gb"
