### ISSUE TITLE
Error found when read h5ad file exported from scanpy write.h5ad function

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#2998]
Hi SatijaLab,
     There were somethings seemigly bug occurred when  taking seurat ReadH5ad function to load the h5ad object of scanpy exported showing below error:
     Error in file [["obs"]] []: objects of category 'environment' cannot take a subset.
     Version:
     Python 3.8.2
     scanpy 1.4.6
     Seurat 3.1
     Any tips would be appreciated

**Comment by kleurless** [comment]
They're working on it: #2748

**Comment by satijalab** [comment]
Closing as its a duplicate, but indeed we will be responding with updates very soon.
