### ISSUE TITLE
merge data slot

### ISSUE THREAD

**Issue by loverend** [satijalab/seurat#2999]
Hi, 

I have noticed that when using merge on the Seurat objects (with SCT assay) despite setting merge.data = TRUE the length of the new scale data slot in the merged SCT assay is smaller than any one of the individual assays scale.data slot.  Why might this be?
I can work around this on small data sets (using  RowMergeSparseMatrices to rebuilt and correct the slot) however this isn't a scalable solution. 

Thanks.

**Comment by loverend** [comment]
I have done a fair bit of googling and one suggestion I found when looking through the code is that merge has a minimum feature cuttoff? If so please can you clarify what this value is / whether it can be adjusted. 

"Some cells removed after object merge due to minimum feature count cutoff"

**Comment by andrewwbutler** [comment]
Hi,

Just to clarify, when you say that the length of the new scale.data slot of the merged assay is smaller, do you mean fewer features or fewer cells or both? 

It's possible that there would be fewer features in the scale.data slot of the SCT assay if you have one or more features that are only present in a subset of the objects being merged. In this situation, it is unclear what values should be present for those residuals in the scale.data matrix (you can't just fill with 0s) so we opt to remove those features from the merged SCT assay. If that's not what's happening though, could you provide an reproducible example where this does happens?
