### ISSUE TITLE
Seurat::FindAllMarkers( ... ) can fail in certain circumstances with an unclear error message

### ISSUE THREAD

**Issue by alexgraehl** [satijalab/seurat#30]
> r.markers <- Seurat::FindAllMarkers(seurat_data)
[1] "Cell group 2 is empty - no cells with identity class "
Error in genes.de[[i]] : subscript out of bounds

**Comment by andrewwbutler** [comment]
In this case, FindAllMarkers is failing because one of your clusters has no cells assigned to it. You can quickly see which one by doing `table(object@ident)`.

**Comment by alexgraehl** [comment]
Thanks again for the info! This was incredibly helpful; I don't know if I
would have been able to track it down without your help.
