### ISSUE TITLE
VlnPlot:  X axis label on multiple plots

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#300]
Trying to generate multiple plots, each with the specified X-axis label to replace default label "Identity".   Script below adds the label - but now only returns plot for first item; no longer makes a set of plots.    How do I get multiple plots returned WITH desired X axis label?  Thx  

```R
VlnPlot(object = XMa_tube, features.plot = "Ugt2b38","Slc22a30", ident.include = c(7,17,3,23)) + labs(x = "PT")
```

**Comment by leonfodoulian** [comment]
Hi,

In your `features.plot` argument, you didn't combine the genes. So it is completely normal that your function returns a single plot. The code should be written as:

```R
VlnPlot(object = XMa_tube, features.plot = c("Ugt2b38","Slc22a30"), ident.include = c(7,17,3,23))
```

However, adding `labs(x = "PT")` will not change the x labels of the plots. The following function should get the job done:

```R
# Function to change x labels of individual violin plots
VlnPlot_2 <- function(object, features.plot, ident.include, xlab) {
  
  # Main function
  main_function <- function(object = object, features.plot = features.plot, ident.include = ident.include, xlab = xlab) {
    VlnPlot(object = object, features.plot = features.plot, ident.include = ident.include) + 
      labs(x = xlab)
  }
  
  # Apply main function on all features
  p <- lapply(X = features.plot, object = object, ident.include = ident.include, xlab = xlab,
              FUN = main_function)
  
  # Arrange all plots using cowplot
  # Adapted from Seurat
  # https://github.com/satijalab/seurat/blob/master/R/plotting.R#L1100
  # ncol argument adapted from Josh O'Brien
  # https://stackoverflow.com/questions/10706753/how-do-i-arrange-a-variable-list-of-plots-using-grid-arrange
  cowplot::plot_grid(plotlist = p, ncol = ceiling(sqrt(length(features.plot))))
}
```

In your case, the following function should produce the graph you're aiming to get. 

```R
VlnPlot_2(object = XMa_tube, features.plot = c("Ugt2b38","Slc22a30"), ident.include = c(7,17,3,23), xlab = "PT?")
```

Hope this helped!

Best,
Leon

**Comment by AndyR2** [comment]
Thx again Leon

![image](https://user-images.githubusercontent.com/33207886/36225741-7f0bfa18-1180-11e8-947f-6ea63434f168.png)

**Comment by MichaelPeibo** [comment]
Hi, is there any way to stack them in the same x axis? such as some paper shows?
![image](https://user-images.githubusercontent.com/32219336/37211484-03b41c8c-23e7-11e8-9d7f-64f99452e80c.png)

**Comment by AndyR2** [comment]
Michael,
As far as I know, the figures like that are compiled in Adobe Illustrator.

**Comment by MichaelPeibo** [comment]
@AndyR2 AI really works! Thanks!

**Comment by mmfalco** [comment]
For those still interested in modify the axis label there is now an easier way to modify plots using patchwork package. For example is you want to remove the "identity" label from x axis using Seurat function `VlnPlot` you can use:
`VlnPlot(obj, features = c("log2nFeature", "log2nCount","log2nReads", "percent.mt")) &  theme(axis.title.x = element_blank())`

This way you can easily modify a lot of the plot variables using ggplot2 functions

**Comment by chitcode** [comment]
This wrapper function may be helpful https://divingintogeneticsandgenomics.com/post/stacked-violin-plot-for-visualizing-single-cell-data-in-seurat/

**Comment by samuel-marsh** [comment]
@chitcode as fyi Updated `Stacked_VlnPlot` with additional features can now be found in scCustomize package (function included with permission, authorship, and assistance from Ming): https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#stacked-violin-plots.

I have also implemented updated version of his `Clustered_DotPlot` as well: https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#clustered-dotplots

Best,
Sam

**Comment by leonfodoulian** [comment]
Hi,

Functionalities to generate such plots already exist in `Seurat` (not exactly sure when this was implemented but version 3 should already have it). Simply set `stack = TRUE` in the `VlnPlot()` function from Seurat.

Best,
Leon

**Comment by samuel-marsh** [comment]
Yes Seurat does have stack feature.  I was simply referring to the code referenced by @chitcode that has now been updated and incorporated into scCustomize.

Best,
Sam

**Comment by Chanukya-Pavan** [comment]
> Hi,
> 
> Functionalities to generate such plots already exist in `Seurat` (not exactly sure when this was implemented but version 3 should already have it). Simply set `stack = TRUE` in the `VlnPlot()` function from Seurat.
> 
> Best, Leon

Hi,

I've tried the stack feature but it shows an error like this.
![image](https://github.com/satijalab/seurat/assets/112158036/49c96ced-ac48-4338-9c7e-fe534b6d84fc)
