### ISSUE TITLE
FeatureScatter bug

### ISSUE THREAD

**Issue by Daliya-K** [satijalab/seurat#3000]
Hi,
I was trying to plot a FeatureScatter plot for some HTO data, using an object with "RNA" and "HTO"assay.
I ran:
FeatureScatter(seur, feature1 = "HASH1", feature2 = "HASH2")
which throws an error:
Warning: Could not find HASH1 in the default search locations, found in HTO assay instead
Warning: Could not find HASH2 in the default search locations, found in HTO assay instead
Error: Feature 1 (HASH1) not found.

Then I noticed that FeatureScatter does a check :
if (isFALSE(x = feature1 %in% colnames(x = data))) {
        stop("Feature 1 (", feature1, ") not found.", 
            call. = FALSE) }
but in data, HASH1 is pulled as "hto_HASH1", so that's why it throws an error.

Could you please correct this?

Thank you!
Daliya

**Comment by yuhanH** [comment]
Thanks for pointing this out. We will fix it soon.

**Comment by Eomesodermin** [comment]
I have encountered this same bug. 

Easiest fix in the meantime is to append "rna_" or "hto_" or "adt_" as prefix to the feature1/2 call when retrieving data not in the default assay.

**Comment by apaikari** [comment]
Same problem here.

**Comment by andrewwbutler** [comment]
This should be fixed now on the `develop` branch. To install, please see instructions [here](https://satijalab.org/seurat/install.html#development)

**Comment by Daliya-K** [comment]
Thank you!
