### ISSUE TITLE
cells.1 parameter in FindMarkers doesn't work

### ISSUE THREAD

**Issue by yfu** [satijalab/seurat#3001]
Specifying ```cells.1``` and ```cells.2``` causes ```FindMarkers``` to throw an error. On the other hand, ```ident.1``` and ```ident.2``` work great.

```R
> FindMarkers(so_all_cells, cells.1 == my_cell_ids)
Error in FindMarkers.Seurat(so_all_cells, cells.1 == ccr2_mac_cell_ids) : 
  object 'cells.1' not found
```

I did a quick search and found [this commit](https://github.com/satijalab/seurat/commit/ba98cc63414384ab32ac487ccc31bac390d49e7a#diff-5a9faffef040e69c40847f9655f99892), which is supposed to fix this issue. But the bug is still present.

Thanks!
Yu

**Comment by andrewwbutler** [comment]
Hi Yu,

If you're calling `FindMarkers` on a Seurat object (which it looks like you're doing here), you can pass the vector of cell names to the `ident.1` parameter. The `cells.1` and `cells.2` parameter were primarily for when calling `FindMarkers` on an `Assay` object or matrix directly where you don't have the `Seurat` object level ident information. I agree though that the documentation isn't particularly clear here so we'll look into improving.
