### ISSUE TITLE
How strongly do you recommend that we keep the default setting of do.scale=TRUE for ScaleData?

### ISSUE THREAD

**Issue by malisas** [satijalab/seurat#3003]
Hi, thanks for providing Seurat and all the wonderful vignettes as a resource!
   
I would like to understand the decision behind the choice to set `do.scale=TRUE` as the default setting in `ScaleData`.
 Seurat, by default, scales the data prior to PCA & clustering. Importantly, it requires users to run `ScaleData` before PCA & clustering, whether or not you set `do.scale=TRUE` or `do.scale=FALSE`.
But some other pipelines don't scale the data by default prior to clustering.
   
For an example of the latter, see the code in [this]( https://osca.bioconductor.org/clustering.html) section of the Orchestrating Single-Cell Analysis book, which calls `scran::denoisePCA` (which internally calls `BiocSingular::runSVD`, which is [set](https://github.com/LTLA/BiocSingular/blob/b9183b50e6b0baf6482aacca3f798df89726482b/R/runSVD.R#L6) to `scale=FALSE` by default).
   
Issue [#2048](https://github.com/satijalab/seurat/issues/2048#issuecomment-546455968) partially addresses why Seurat sets `do.scale=TRUE` by default:
>  ScaleData ... scales rows (it is meant to mirror the scale=TRUE argument in prcomp)  

My interpretation of this is that one reason for setting `do.scale=TRUE` by default is that you are being consistent with prcomp (called [here](https://github.com/satijalab/seurat/blob/67ec21a9840f9000420e467bd608dd420258617f/R/dimensional_reduction.R#L835)).
Interestingly, I believe prcomp's [default setting](https://github.com/wch/r-source/blob/2825c6e39c848ce479289ba5f7521baae955d6f6/src/library/stats/R/prcomp.R#L22) is `scale. = FALSE`, though it recommends “in general scaling is advisable”.
   
So far, it seems to me that this choice depends on whether we are more interested in highly expressed genes vs lowly expressed genes, and in general it seems like a dataset-specific choice.
   
**Q:** By setting it as the default, is it your intention to <ins>recommend</ins> that users scale their data with `do.scale=TRUE` prior to PCA & clustering?  
If yes, do you have a compelling reason as to why your default setting differs from the other pipeline and why we should stick with it?  
If no, it will be good to know, because I will feel more justified in setting `do.scale=FALSE`.
   
Thanks!

**Comment by satijalab** [comment]
As you say, we have this as a default in order to make sure highly expressed genes do not dominate the analysis. It is a method of variance stabilization.

In the SCTransform workflow, we perform a better version of variance stabilization, so we do not scale in this case.

**Comment by malisas** [comment]
Thank you for your response.

Just a clarification that for SCTransform, the data does get put onto the same scale, even though do.scale is set to FALSE (see [manuscript](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6927181/)):
> We utilize the Pearson residuals (response residuals divided by the expected standard deviation), effectively representing a variance-stabilizing transformation (VST), where both lowly and highly expressed genes are transformed onto a common scale
