### ISSUE TITLE
Infinite values when using Average expression function

### ISSUE THREAD

**Issue by xw213** [satijalab/seurat#3004]
Hello,

I am new to Seurat and i have a problem with using the Average Expression function.
If i use this function on my data set to create the average expression for each sample in each cluster i am ending up with infinite values. Can someone explain to me why these values are infinite and how i can solve this or how i can track down where these values are coming from?

i am using sctransform on my data set, i think that is good to know..

Thanks in advance!

**Comment by satijalab** [comment]
You should not be receiving infinite values when running AverageExpression. I would recommend checking the data slot of your SCT assay (and of your original RNA assay). There are likely negative or NaN values in either of these which are causing your problem.

If that does not solve your problem, please feel free to reopen the issue and we'll take a closer look

**Comment by xw213** [comment]
Hello again,

I checked my original @assays$RNA@data and @assays$SCT@data slots and both do not contain NaN values or negative values.

I am using this code to check

in original RNA
`has.neg <- apply(CD4SeuratObject@assays$RNA@data, 1, function(row) any(row < 0))
length(which(has.neg))
any(is.nan(as.matrix(CD4SeuratObject@assays$RNA@data)))`

in SCT 
`has.neg <- apply(analysis_output$cd4subset@assays$SCT@data, 1, function(row) any(row < 0))
length(which(has.neg))
any(is.nan(as.matrix(analysis_output$cd4subset@assays$SCT@data)))`

However, if i run Sctransform i do get an warning message about NaNs(see image)
![nanerror](https://user-images.githubusercontent.com/65335943/82303609-74754d00-99bb-11ea-8777-20d1256e5b52.PNG)

If i am using NormalizeData, FindVariableFeatures and scaleData i am not getting infinite values.

This is the code that i use for SCtransform
`cd4subset <- SCTransform(cd4subset, vars.to.regress = "percent.mt", verbose = FALSE)`

and this is the code i would use for the normal normalization
`  cd4subset <- NormalizeData(cd4subset)
  cd4subset <- FindVariableFeatures(cd4subset, selection.method = "vst", nfeatures = 2000)
  all.genes <- rownames(cd4subset)
  cd4subset <- ScaleData(cd4subset, features = all.genes)`

I hope someone can still help me with this additional information

**Comment by rbpatt2019** [comment]
@satijalab @xw213 As this was never reopened, I created a new issue for the same problem. See #3106. Feel free to close that and re-open this if you prefer. Cheers!

**Comment by semir2** [comment]
I got the same problems.

**Comment by xw213** [comment]
Hello,

I think my problem was that i was using the AverageExpression$RNA assay instead of the $SCT assay. I did not notice there were to assays. The RNA assay is indeed filled with infinites but the $SCT assay is not. I hope this can help anyone
