### ISSUE TITLE
cant find the resolution prefixes

### ISSUE THREAD

**Issue by klai001** [satijalab/seurat#3005]
Hi Developers of Seurat
thanks for the really informative vignettes and for developing Seurat. I really like it.

I wanted to adjust resolution parameters of my tSNE clustering and checked by using Clustree
which requires a prefix
I have checked the colnames of Seurat Object which i got 

> [1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "percent.mt"     
[5] "RNA_snn_res.0.5" "seurat_clusters"

intuitively, i suppose that RNA_snn_res.0.5 is my prefix however, when i run it that is not the case.
I also tried "seurat_clusters" but i get the same error.

Would appreciate if you share w me what am i Missing.

I am following closely the same workflow as mentioned in your "pbmc_3k" tutorial
thank you

**Comment by mojaveazure** [comment]
`FindClusters` stores partitions as `ASSAY_GRAPH_res.RESOLUTION`, with the `ASSAY_GRAPH_res.` part being the prefix (as indicated by [Clustree's vignette](https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html#seurat-objects)). In your case, the prefix would be "RNA_snn_res.` (which would indicate that you clustered on the RNA assay using the SNN graph; the "0.5" bit indicates that you clustered at a resolution of 0.5).

The `seurat_clusters` column is simply the latest clustering, and cannot be used in Clustree
