### ISSUE TITLE
IntegrateData() assay has a huge loss of features - can I retrieve them?

### ISSUE THREAD

**Issue by kleurless** [satijalab/seurat#3006]
Hi! 

I have used `IntegrateData()` for batch correction of my time-series dataset (fyi, each time slot has a low number of cells). I really like the results, and would like to continue with some downstream analysis in Scanpy. But, if I export the object I end up with 2000 features as opposed to all 28.538 features in the RNA-assay; a huge loss of data.

I exported the integrated assay to a loom file, and I then have the cluster determination and pca/tsne/umap dimensions, but with only 2000 features. If I export the RNA assay to a loom file, I have the entire matrix with all 28.538 features, but without the cluster determination and pca/tsne/umap dimensions.
Is there a way for me to export the object with ALL features and clusters + dimensions, or to change my code so that the integrated assay contains all features?

Below is the code that I used to integrate the data:
```
embryo.anchors <- FindIntegrationAnchors(object.list = list(e11, e12, e13, e15, e18, p4, p7, adult), dims = 1:20, k.filter=50, k.score=10, k.anchor=4, anchor.features = 2000) 
embryo.combined <- IntegrateData(anchorset = embryo.anchors, dims = 1:20)
```

I have tried to set `anchor.features=28538`, but then the integrated assay contains 4787 features.

This is what my object "looks" like:
```
An object of class Seurat 
30538 features across 2773 samples within 2 assays 
Active assay: integrated (2000 features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, tsne, umap
```

**Comment by liuxl18-hku** [comment]
`features.to.integrate` from [IntegrateData](https://rdrr.io/github/satijalab/seurat/man/IntegrateData.html) is the way to export all features you want in integrated output (not only those features used in anchor finding).

But not sure the pearson residuals in integrated output is what you want for Scanpy.

bless~

**Comment by kleurless** [comment]
Thank you!! I only looked at the FindTransferAnchors, so I missed that one.
