### ISSUE TITLE
Coloring switch in VlnPlot with the current development version as well

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#3007]
https://github.com/satijalab/seurat/issues/1998#issue-482496890

Dear community,
The bug that was reported in the above issue (link above) seems not fixed still. The variable tend to switch sides(or colours)
my seurat version : ‘3.1.5.9003’
The plotted feature is from a metadata column (not a gene from the assays).
Anybody seen any easy fix? otherwise I will have to wait until next release I guess. 
![image](https://user-images.githubusercontent.com/40058022/81948951-9315c580-9602-11ea-885b-8c92ce9e42c3.png)

**Comment by timoast** [comment]
This is fixed when using the default setting (`split.plot=FALSE`), which plots separate violins per split. Fixing this for the split violins is difficult and is currently very low in our list of priorities, as the same result can be achieved with `split.plot=FALSE` and (in my opinion) is a better way of showing the data anyway
