### ISSUE TITLE
input the many *_filtered_gene_bc_matrices_h5.h5 files into Seurat integration

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3009]
Hello,

Thank you so much for developing so nice R package Seurat!

I have eight samples ended with `*_filtered_gene_bc_matrices_h5.h5` and want to integration them together into one file to do the downstream analysis.

How I can input these eight files into Seurat integration?

Thanks in advance for great help!

Best,

yue

**Comment by basilkhuder** [comment]
I'm assuming that these .h5 files only contain the matrix and not the barcodes or genes, correct?  And when you say "integrate", do you mean actual [Seurat Integration Workflow](https://satijalab.org/seurat/v3.0/integration.html), or are you looking to simply merge these eight samples into a Seurat object and then run downstream analysis?

**Comment by basilkhuder** [comment]
Do these.h5 files only contain a matrix with barcodes and genes, or is it only the matrix? And when you say "integrate", do you mean actual Seurat Integration Workflow, or are you looking to simply merge these eight samples into a Seurat object and then run downstream analysis?

**Comment by yueli711** [comment]
Hello basilhuder,
Thank you so much for your quick response!
Thank you again!
Best,
Yue

'''> install.packages("hd5fr")
Installing package into ‘/home/li/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Warning message:
package ‘hd5fr’ is not available (for R version 3.6.1) '''

**Comment by timoast** [comment]
@yueli711 the package should be hdf5r (not hd5fr)

**Comment by yueli711** [comment]
Hello, timoast,

Thank you so much for your great help!

Best,

Yue

**Comment by yueli711** [comment]
Hello timoast and basilkhuder,

Thank you so much for your great help!

I already have h5_seurat, how I can use Seurat to do the cluster? How I can input the data?

https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

Thank you in advance for your great help!

Best,

Yue

`h5_seurat  <- merge(h5_seurat[[1]], y = h5_seurat[2:length(h5_seurat)], add.cell.ids = c("1", "2", "3", "4", "5", "6", "7","8"), project = "project")`
