### ISSUE TITLE
Dimplot Split.by and ggplot formatting?

### ISSUE THREAD

**Issue by oh111** [satijalab/seurat#3011]
Hi, 
I have been trying to use the ggplot2 formatting to format my graphs from the Dimplots and have reached a blockade that I cannot see addressed anywhere. 

Normally, I can format it the way I want for instance (this may be a round about way):

```
PCAPlot(Compiled.SOBJ, group.by="Identity")+
geom_point(aes(PC_1, PC_2, filly= Compiled.SOBJ[["Identity"]], shape=21), size=2)+
guides(fill=guide_legend(override.aes= list(shape=21), color=FALSE)+
scale_shape_identity()+
scale_fill_manual(values=c("red", "blue", "green"))
```

But now, I want to split.by a group "Subtype" that has 18-sub-groups. This results in numerous very small plots that are not discernable. Instead, I split the SeuratObject as a list: 

```
Subtype<-SplitObject(Compiled.SOBJ, split.by="subtype")
TissueType<-SplitObject(Compiled.SOBJ, split.by="TissueType")

plot<-lapply(X=TissueType.SOBJ, FUN=function(x){
PCAPlot(TissueType.SOBJ, group.by="subtype")
```

This alone produces the right graph, but the formatting is not what I am looking for. And Simply adding the same formatting with geom_point does not give me the same style. Attached are reference pictures.

Any assistance is appreciated!

[AAA.pdf](https://github.com/satijalab/seurat/files/4631798/AAA.pdf)
[bbb.pdf](https://github.com/satijalab/seurat/files/4631799/bbb.pdf)

**Comment by mojaveazure** [comment]
Why are you adding `geom_point` to the plot returned by Seurat? That's adding a second layer with the exact same data, effectively doubling the graph? You should be able to modify the graph returned by `DimPlot` without needing to redraw it.

When you add `split.by` to `DimPlot`, it returns a patchworked ggplot2 object. Patchwork allows you to apply formatting to any part or all of the stitched graphs. I would suggest using `DimPlots` `split.by` argument and using patchwork to apply formatting across each sub-plot. For help using patchwork, I would suggest reading [their documentation](https://patchwork.data-imaginist.com/)

**Comment by oh111** [comment]
It was my understanding that there was no way to put a "black point border" for example point with index 21 (circle with black border), hence why I used ggplot to overlay the same points but with the black border...
