### ISSUE TITLE
two sample merge into one on seurat slot counts issue

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3012]
Hi SatijiaLab,
     There are had several problem that make me confused a lots. 
      Should i individually extract certain clusters count that i interest to regenerate two seurat object and then merge those into one to execute identical merge workflow as well if i want to reanalyze the certain clusters on combined seurat of two samples, or just using below scripts to extract count and generate new seurat object, so then using single sample workflow to analyze it ?
 endot<-as.matrix(GetAssayData(pancreas.integrated_end,slot = 'counts')[,WhichCells(pancreas.integrated_end,idents = c('non_Endothelial_cells_Cancer','Endothelial_cells_Cancer'))])
################
endot1<-CreateSeuratObject(endot,min.cells = 3,min.features = 200)

      Finally, i want to ask last a question.  i wonder that after the merged seurat object of two samples finished,  whether the slot 'data' of seurat  just making every cells normlization from merged slot counts or not and it was not related with integration. and It indicated that whether or not the normlized within slot data did normlized respective  cells from two sample ?
     Thanks 
      any advice would be appreciated

**Comment by satijalab** [comment]
You can use the subset command in Seurat to address this, and to create a subsetted object that contains only the celltypes you want.

examples in: https://satijalab.org/seurat/v3.0/interaction_vignette.html
