### ISSUE TITLE
Project new data on UMAP

### ISSUE THREAD

**Issue by mdidish** [satijalab/seurat#3013]
Hello,
First, I thank you for this great package!

In your last release, you wrote:
> Added ability to store model learned by UMAP and project new data
>
I did not find with which function / argument, can you say more?
Best regards

**Comment by satijalab** [comment]
Coming soon! Apologies for the delay, will comment on this issue when fully released

**Comment by hxy265** [comment]
Hi Seurat team, any update on this or test code we could try? Really keen to be explore some new data this way, thanks!

**Comment by mdidish** [comment]
Hi, is this function now available?
Regards

**Comment by mdidish** [comment]
this feature is available with Seurat 3.2.1:
https://github.com/satijalab/seurat/issues/3570
