### ISSUE TITLE
Difference between "RNA" and "Integrated" assays

### ISSUE THREAD

**Issue by cloitz2** [satijalab/seurat#3014]
Hello,

I am a new r/seurat user and working to improve my overall understanding of how the process works. I am integrating data from one control and one treated set and am using the FindIntegrationAnchors and then IntegrateData functions (Have copied my order of code below if needed as a reference). I was told that the Default Assay should be "integrated" when running pca and creating UMAPS/tSNE plots, and "RNA" when finding markers, running differential gene expression and for heatplots/dotplot; I was also told that the "RNA" assay must be scaled for heatplots/dotplots. My question is what is the difference between the two assays and why am I utilizing them at different times and why do I have to scale the "RNA" assay for heat/dot plots? Also, are there other instances when I need to use "integrated" vs. "RNA" or vice versa that I should be aware of.

#install/load packages
library(Seurat)
library(dplyr)
library(ggplot2)
library(cowplot)

#Load data and create Seurat object
CE.data = Read10X(data.dir = "~/Downloads/CE.zip.download/CE/outs/filtered_feature_bc_matrix/")
CE <- CreateSeuratObject(counts = CE.data, project = "10X_wtCE")
CE[["percent.mt"]] <- PercentageFeatureSet(CE, pattern = "^MT-")

#Process/remove unwanted cells
CE <- subset(x = CE, subset = nFeature_RNA > 2500 & percent.mt < 15)
CE <- NormalizeData(CE, verbose = FALSE)
CE = FindVariableFeatures(CE, selection.method = "vst", nfeatures = 2000)

#Load data and create Seurat object for second data set
ME.data = Read10X(data.dir = "~/Downloads/ME/outs/filtered_feature_bc_matrix/")
ME <- CreateSeuratObject(counts = ME.data, project = "10X_wtME")
ME[["percent.mt"]] <- PercentageFeatureSet(ME, pattern = "^MT-")

#Process/remove unwanted cells
ME <- subset(x = ME, subset = nFeature_RNA > 2500 & percent.mt < 15)
ME <- NormalizeData(ME, verbose = FALSE)
ME <- FindVariableFeatures(ME, selection.method = "vst", nfeatures = 2000)

#Labells for UMAP
ME$treat <- "wtM"
CE$treat <- "wtC"

#Perform integration
Org10x <- FindIntegrationAnchors(object.list = list(ME, CE), dims = 1:50)
Org10x <- IntegrateData(anchorset = Org10x, dims = 1:50)
DefaultAssay(object = Org10x) <- "integrated"

# Run the standard workflow for visualization and clustering
Org10x <- ScaleData(object = Org10x, verbose = FALSE)
Org10x <- RunPCA(object = Org10x, npcs = 50, verbose = FALSE)

#Determine PC's
ElbowPlot(object = Org10x, ndims = 50)
DimHeatmap(Org10x, dims = 1:15, cells = 500, balanced = TRUE)
DimHeatmap(Org10x, dims = 15:29, cells = 500, balanced = TRUE)
DimHeatmap(Org10x, dims = 30:40, cells = 500, balanced = TRUE)

#Cluster
Org10x <- FindNeighbors(object = Org10x, reduction = "pca", dims = 1:40)
Org10x <- FindClusters(Org10x, resolution = 0.4)

#Create UMAP
Org10x <- RunUMAP(object = Org10x, reduction = "pca", dims = 1:40)
DimPlot(object = Org10x, reduction = "umap")
DimPlot(object = Org10x, reduction = "umap", group.by = "treat")
DimPlot(object = Org10x, reduction = "umap", split.by = "treat")

Org10x <- RunTSNE(object = Org10x)
DimPlot(object = Org10x, reduction = 'tsne')
DimPlot(object = Org10x, reduction = 'tsne', group.by = "treat")
DimPlot(object = Org10x, reduction = "tsne", group.by = "group")
saveRDS(Org10x, file = "~/Downloads/Org10x.rds")

#Find markers of each cluster
 DefaultAssay(object = Org10x) <- "RNA"
markers <- FindAllMarkers(Org10x, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(markers, file = "Org10x-RNAmarkers_All.csv")

#Scale RNA slot --> heatmap and dotplot use scale.data of RNA assay
all.genes <- rownames(x = Org10x)
Org10x <- ScaleData(object = Org10x, features = all.genes)
saveRDS(Org10x, file = "~/Downloads/Org10x.rds")

#DEGs with wtM vs wtC culture
DefaultAssay(object = Org10x) <- "RNA"
Org10x$celltype.treat <- paste(Idents(Org10x), Org10x$treat, sep = "_")
Org10x$celltype <- Idents(Org10x)
Idents(Org10x) <- "celltype.treat"
DEG.genes0 <- FindMarkers(Org10x, ident.1 = "0_wtC", ident.2 = "0_wtM", verbose = FALSE)
DEG.genes1 <- FindMarkers(Org10x, ident.1 = "1_wtC", ident.2 = "1_wtM", verbose = FALSE)
DEG.genes2 <- FindMarkers(Org10x, ident.1 = "2_wtC", ident.2 = "2_wtM", verbose = FALSE)
DEG.genes3 <- FindMarkers(Org10x, ident.1 = "3_wtC", ident.2 = "3_wtM", verbose = FALSE)
DEG.genes4 <- FindMarkers(Org10x, ident.1 = "4_wtC", ident.2 = "4_wtM", verbose = FALSE)
DEG.genes5 <- FindMarkers(Org10x, ident.1 = "5_wtC", ident.2 = "5_wtM", verbose = FALSE)
DEG.genes6 <- FindMarkers(Org10x, ident.1 = "6_wtC", ident.2 = "6_wtM", verbose = FALSE)
DEG.genes7 <- FindMarkers(Org10x, ident.1 = "7_wtC", ident.2 = "7_wtM", verbose = FALSE)

**Comment by timoast** [comment]
Please see the paper for an explanation of what these different assays are: https://doi.org/10.1016/j.cell.2019.05.031
