### ISSUE TITLE
Formatting of Graphs

### ISSUE THREAD

**Issue by oh111** [satijalab/seurat#3015]
I guess this is a follow up to my previous post #3011 --
I cannot for the life of me figure out how to get the point border black with the fill color different. 

I know for any plot (eg. Dimplot) there is a cols option, but there isn't a separate option for the outline. 

The only way I can think of adding it is to add the geom_point layer over just for the outline...

**Comment by timoast** [comment]
We don't currently provide a way to explicitly set the point style like that. In this case, the easiest thing to do might be to extract the data from the object and plot it yourself using ggplot2.

For example:

```r
library(Seurat)
library(ggplot2)

# get metadata
md <- pbmc_small[[]]

# get embeddings
coords <- Embeddings(pbmc_small[["tsne"]])

# combine dataframes
md <- cbind(md, coords)

# plot
ggplot(md, aes(x = tSNE_1, y = tSNE_2, fill = groups)) +
  geom_point(shape = 21, size = 2) + theme_classic()
```
<img width="497" alt="Screen Shot 2020-05-15 at 12 22 08 pm" src="https://user-images.githubusercontent.com/4591688/82073077-b4c88880-96a6-11ea-9139-b03d103b5dda.png">

**Comment by sangh0lim** [comment]
> We don't currently provide a way to explicitly set the point style like that. In this case, the easiest thing to do might be to extract the data from the object and plot it yourself using ggplot2.
> 
> For example:
> 
> ```r
> library(Seurat)
> library(ggplot2)
> 
> # get metadata
> md <- pbmc_small[[]]
> 
> # get embeddings
> coords <- Embeddings(pbmc_small[["tsne"]])
> 
> # combine dataframes
> md <- cbind(md, coords)
> 
> # plot
> ggplot(md, aes(x = tSNE_1, y = tSNE_2, fill = groups)) +
>   geom_point(shape = 21, size = 2) + theme_classic()
> ```
> 
> <img alt="Screen Shot 2020-05-15 at 12 22 08 pm" width="497" src="https://user-images.githubusercontent.com/4591688/82073077-b4c88880-96a6-11ea-9139-b03d103b5dda.png">

IS this also can be applied for FeaturePlot?
