### ISSUE TITLE
The standard integrated workflow showing non-existed batch-corrected UMI counts slot like SCTransform pipeline

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3017]
Hi Satijalab,
     The Standard integrated workflow you posted demonstrate non-exist batch-corrected  slot counts like SCTranform. how can i make differential expression for all genes.
      shoud i using the data of RNA assay to analysis the DEG, and i wonder that is the data slot of RNA assay  had normlized and batch-corrected already ?
      Can i used it to scale or to analysis deg ?
       any advice would be appreciated.

**Comment by yuhanH** [comment]
HI, 
Right. We suggest you use RNA assay to do the differential analysis for the integrated object. 
You can find it in the question 4 of FAQ
https://satijalab.org/seurat/faq.html
