### ISSUE TITLE
input of the merged files to do the cluster

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3020]
Hello

I have eight samples ended with ` *_filtered_gene_bc_matrices_h5.h5` files, and already  merged them together by using:

`h5_seurat <- merge(h5_seurat[[1]], y = h5_seurat[2:length(h5_seurat)], add.cell.ids = c("1", "2", "3", "4", "5", "6", "7","8"), project = "project")`

How I can input them and do the cluster?

https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

Please see: https://github.com/satijalab/seurat/issues/3009

Thanks in advance for great help!

Best,

Yue

**Comment by andrewwbutler** [comment]
Hi,

If you've merged the separate Seurat objects and you aren't seeing confounding sample-specific effects, you can essentially treat it as a single Seurat object (as in the pbmc3k tutorial) and follow that workflow to perform a standard clustering analysis.
