### ISSUE TITLE
format of input matrices in function of Integration

### ISSUE THREAD

**Issue by Shawn10312** [satijalab/seurat#3021]
Hi,

I have a question of using function Integration in Seurat.
If I want to integrate four different database data, should all the input matrices be raw count matrices?

I checked the format of input files, `pancreas.data <- readRDS(file = "../data/pancreas_expression_matrix.rds")`, used in your website vigetttehttps://satijalab.org/seurat/v3.0/integration.html.
Matrix of samrtseq2 seems like raw counts data, but matrices of celseq and celseq2 are normalized data. And I am not sure what the format of fluidigmc1.

Can you tell me the difference?

Thanks for your help.

**Comment by yuhanH** [comment]
HI, 
If you want to integrate different datasets, you need to normalize them one by one first, and then integrate them. 
In the integration vignette, you can see how we normalize the raw counts. 
https://satijalab.org/seurat/v3.1/integration.html
```
for (i in 1:length(pancreas.list)) {
    pancreas.list[[i]] <- NormalizeData(pancreas.list[[i]], verbose = FALSE)
    pancreas.list[[i]] <- FindVariableFeatures(pancreas.list[[i]], selection.method = "vst", 
        nfeatures = 2000, verbose = FALSE)
}
```

**Comment by Shawn10312** [comment]
You mean using raw count matrices to generate seuratobject one by one. Then, normalize these seuratobjects one by one and integrate them together at the end.

Well, my problem as follows:
Because I download published scRNA-seq data, not all the authors provide us the raw counts or raw TMPs matrices. If I get some normalized-already count or TMP matrices, should I also go the above standard workflow to integrate them together? Or there will be some difference??
