### ISSUE TITLE
Show a gene set on FeaturePlot

### ISSUE THREAD

**Issue by schelp72** [satijalab/seurat#3022]
Hope everyone is well.

I would like to display the average expression level of a set of genes (at least 5) in a FeaturePlot but the function only takes 2 genes max in its argument. 

My request is similar to what is asked here:
https://github.com/satijalab/seurat/issues/528
https://www.biostars.org/p/334617/

I am a beginner to R and do not know how to update this code to the newest Seurat version.

Thanks!

**Comment by Eomesodermin** [comment]
You can try generating a module score for the gene set: 

Seurat.obj <- AddModuleScore(
  object = Seurat.obj,
  features = list(geneset.vector),
  name = 'Module_score_name'
)

then plot the module score in FeaturePlot

**Comment by schelp72** [comment]
Thank you this is exactly what I needed!
