### ISSUE TITLE
Cluster defenition

### ISSUE THREAD

**Issue by satellite119** [satijalab/seurat#3023]
Hi, I am doing cluster annotation from Seurat. I am using scMCA(http://bis.zju.edu.cn/MCA/blast.html) for the cluster annotation. But the imported file needs gene symbol and cells. Do you know how to make it from Seurat meta.data?
Thanks

**Comment by andrewwbutler** [comment]
Hi,

You can pull any of the data matrices stored within Seurat using the `GetAssayData` function. This will return the data as a matrix that you can then export for use in any other software.
