### ISSUE TITLE
ScaleData() on merged seurat object

### ISSUE THREAD

**Issue by piyushjo15** [satijalab/seurat#3024]
Hi,
I am trying to understand why ScaleData() on the merged seurat object is not run with split.by parameter. 

If I have two different objects, with different sequencing depth, I understand that normalizing them separately will take care of the the depth issue. However, when I will merge them, how will I re-normalize to adjust the depth difference between the two objects?

Second, when I scale this merged object, it will assume that a count for given genes has the same source and scale it accordingly. But wouldn't this be wrong? What is the distribution (sd) of a gene in one sample was smaller than the other, shouldn't scaling them separately with `split.by="orig.ident"` be the correct thing?

**Comment by timoast** [comment]
You can certainly run with the `split.by` argument, and that's what the argument is meant for. I'm not sure what you mean by "is not run with the split.by parameter" as the parameter choices are up to the user (you)

**Comment by piyushjo15** [comment]
Thanks. I actually wanted a sort of explanation why is the default settings for scaling a merged object is not by splitting by source of counts. That will help me understand what  I should choose.
