### ISSUE TITLE
integrate eight single cell *.csv files into one *.csv file 

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3026]
Hello,

I have eight single cell *.csv files and want to integrate them into one *.csv file Then I can do the downstream Seurat analysis: https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html.

How can I do it?

Thanks in advance for great help!

Best,

Yue

**Comment by samuel-marsh** [comment]
Hi Yue,

This is less of Seurat question and more of general R question so I would suggest checking out StackExchange or other R focused forum for info on how best to merge .csv before import into Seurat.  If you want to merge files using Seurat specifically then you could create different Seurat objects for each .csv file and then merge the individual Seurat objects with:
`merged_seurat <- merge(x = seurat1, y = c(seurat2, seurat 3, seurat 4, etc))`

Best,
Sam
