### ISSUE TITLE
Differential Gene Expression; using Latent Variables argument

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#3028]
Dear Community,

I have human data from different ages and gender. After using integration, how would I best control for these confounding factors during differential gene expression. I see the option of latent.vars in FindMarkers function.
Can I give latent.vars = c("Age", "gender") to account for both together? or can I only use one at a time?
Kindly advice,
Kind regards,
Saeed

**Comment by andrewwbutler** [comment]
Hi,

Yes, you can provide multiple variables to `latent.vars` as you do above.
