### ISSUE TITLE
seurat merged 10x lanes - error scaling: Error: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by ibseq** [satijalab/seurat#3029]
HI all, 
I merged different 10x runs and tried scaling the data but encountered the issue below: is there a limit to the number of experiments we can merge?

> all.genes <- rownames(merged_10x_runs)
> merged_10x_runs <- ScaleData(merged_10x_runs, features = all.genes)
Centering and scaling data matrix
  |=========================================================================================================| 100%
Error: vector memory exhausted (limit reached?)

thanks
ibseq

**Comment by timoast** [comment]
This indicates that you're running out of memory on your computer. We recommend that you scale only the variable features, this is all that's needed in most cases and reduces the memory requirement substantially.
