### ISSUE TITLE
Integration Workflow Question

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#303]
Hello,

In the integration workflow, when the objects are combined during RunCCA, are they batch normalized? 

Related question: if they are not batch normalized during RunCCA, is it still possible to use the integration workflow with non-normalized datasets? (mine, for example, are from the same platform/organism but of variable depth). At what point in the workflow could one force batch normalization? 
Thanks!!

**Comment by satijalab** [comment]
I'm not quite sure what you mean by batch normalization, but yes, you can run the workflow with non-Normalized datasets if you wish. You can also normalize objects (either gene-specific normalization with ScaleData or cell-specific with NormalizeData) at any point prior to RunCCA.
