### ISSUE TITLE
Removal of Seurat clusters 

### ISSUE THREAD

**Issue by nitinsai1** [satijalab/seurat#3030]
Hello,

I plotted UMAP using Seurat Object (Single cell RNA-seq dataset, newbie to analysis). I want to remove 3 different clusters from UMAP plot. Can anybody give me code snippet.

Thank you,
nitin

**Comment by samuel-marsh** [comment]
Hi Nitin,

You can use the `subset` function and specify the idents of the clusters to keep (or remove if you set `invert = TRUE`) and that will remove the cells in those clusters.  However, if you are planning on doing analysis of the subset you should probably reanalyze again as the old analysis from Variable Features onward was based on those cells still being present in the object.

Best,
Sam

**Comment by nitinsai1** [comment]
Hi Sam,

Thank you it worked :)

Best,
nitin

**Comment by shawn387** [comment]
> Hi Nitin,
> 
> You can use the `subset` function and specify the idents of the clusters to keep (or remove if you set `invert = TRUE`) and that will remove the cells in those clusters. However, if you are planning on doing analysis of the subset you should probably reanalyze again as the old analysis from Variable Features onward was based on those cells still being present in the object.
> 
> Best,
> Sam



> Hi Nitin,
> 
> You can use the `subset` function and specify the idents of the clusters to keep (or remove if you set `invert = TRUE`) and that will remove the cells in those clusters. However, if you are planning on doing analysis of the subset you should probably reanalyze again as the old analysis from Variable Features onward was based on those cells still being present in the object.
> 
> Best,
> Sam

Hi Sam,
I have the same problems as Nitin, but i don't know how to use the `subset` function to deal with this kind of questions, Can you give me some hint. Thank you!

Best,
Shawn

**Comment by samuel-marsh** [comment]
Hi Shawn,

For future reference information on functions and their parameters they are often described in function help/manual pages that can be accessed within R.

For subset here are examples (in this case it assumes your clusters have numeric idents (i.e. default after running `FindClusters`) but can also provide other values if you have renamed your clusters before subsetting):

```
# To subset and perform new analysis on single cluster
sub_obj <- subset(object = obj_name, idents = 1)

# To subset and remove single cluster and keep the remaining clusters for new analysis
sub_obj <- subset(object = obj_name, idents = 1, invert = TRUE)

# Can also provide multiple idents using the typical R syntax "c()"
sub_obj <- subset(object = obj_name, idents = c(1, 2, 3))

# If you have renamed the clusters be sure to provide their names in quotes in the function
sub_obj <- subset(object = obj_name, idents = "Monocytes")
```

Best,
Sam

**Comment by shawn387** [comment]
> Hi Shawn,
> 
> For future reference information on functions and their parameters they are often described in function help/manual pages that can be accessed within R.
> 
> For subset here are examples (in this case it assumes your clusters have numeric idents (i.e. default after running `FindClusters`) but can also provide other values if you have renamed your clusters before subsetting):
> 
> ```
> # To subset and perform new analysis on single cluster
> sub_obj <- subset(object = obj_name, idents = 1)
> 
> # To subset and remove single cluster and keep the remaining clusters for new analysis
> sub_obj <- subset(object = obj_name, idents = 1, invert = TRUE)
> 
> # Can also provide multiple idents using the typical R syntax "c()"
> sub_obj <- subset(object = obj_name, idents = c(1, 2, 3))
> 
> # If you have renamed the clusters be sure to provide their names in quotes in the function
> sub_obj <- subset(object = obj_name, idents = "Monocytes")
> ```
> 
> Best,
> Sam

Hi sam,
Your reply is so detailed and fast, It's very useful for me, Thank you very much!
Best,
Shawn

**Comment by DeySayanti** [comment]
Hello!

I have been trying the same with my UMAPs for removing clusters but it is showing:

Error in UpdateSlots(object = x) : 
  argument "x" is missing, with no default

Please help me with this !

**Comment by candacechan** [comment]
> 
 This error appears for me too in version 4.1.3. It works if you use "x" instead of "object" in the function like this:
`sub_obj <- subset(x = obj_name, idents = c(1, 2, 3))`
