### ISSUE TITLE
 `no slot of name "scale.data" for this object of class "Seurat"` this message appears when I try to generate a cvs table from the Seurat Object. how to fix it?

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#3031]
Hi all,

Two quick questions, and before hand,I thank you very much for you time.

1) I am trying to export my Seurat object as a .cvs table, for that I am running the following scripts:

`library(data.table)`
`Merged.big <- as.data.frame(as.matrix(Merged.big@scale.data))`

`fwrite(x = Merged.big,  row.names = TRUE, file = "Merged.big.csv")`

However, I am getting back the following message

`Error in as.matrix(Merged.big@scale.data) : 
  no slot of name "scale.data" for this object of class "Seurat"`

I have carried out the following  `Merged.big<- ScaleData(object = Merged.big) as part of Seurat workflow. 

`Merged.big <- CreateSeuratObject(counts = filtered.counts)`
`Merged.big <- NormalizeData(object = Merged.big)`
`Merged.big <- FindVariableFeatures(object = Merged.big)`
`Merged.big <- ScaleData(object = Merged.big)`
`Merged.big <- RunPCA(object=Merged.big)` 
`Merged.big <- FindNeighbors(object=Merged.big)`
`Merged.big<- FindClusters(object=Merged.big)` 
`Merged.big <- RunTSNE(object=Merged.big)`
Can anybody help me out?

2) How to I export a .tsv file after run PCA in Seurat to feed it into STREAM(Single-cell Trajectories Reconstruction, Exploration And Mapping of omics data)?

Once again, I thank you very much for yur time and help, sorry for having two different issues in a single post, but they both are related to exporting data as different  table formats.

Best,

**Comment by jushrabanti** [comment]
I also need an answer to this question. Please somebody help. Thank you so much for your help!
