### ISSUE TITLE
Seurat 3.2 mislabled?

### ISSUE THREAD

**Issue by wfma** [satijalab/seurat#3032]
Hello! I am trying to work thru the spatial [transcriptomic vignette](https://satijalab.org/seurat/v3.1/spatial_vignette.html) here but when I run the install from github using the code:
`devtools::install_github("satijalab/seurat", ref = "spatial")
`
I get 3.1.4 installed. I am running R 3.6.2. Can you help?
Thank you,
Wei

**Comment by mattrosef** [comment]
I noticed the same: v3.2 is listed as 3.1.4.9904 in RStudio package list. However, it appears to work as shown in the 3.2 vignette.
Matt

**Comment by wfma** [comment]
> I noticed the same: v3.2 is listed as 3.1.4.9904 in RStudio package list. However, it appears to work as shown in the 3.2 vignette.
> Matt

Hi, are you saying that 3.1.49904 would work with the spatial analysis?
Wei

**Comment by andrewwbutler** [comment]
Hi,

Yes, the plan is to roll in the new spatial features into the next minor release (v3.2). Currently though, this is still in development so anything with the `.99XX` suffix should work for spatial analysis. To be sure you're using the latest version with spatial support, you can install from github with
```R
devtools::install_github("satijalab/seurat", ref = "spatial")
```

Sorry for any confusion.
