### ISSUE TITLE
subset(downsample= X)

### ISSUE THREAD

**Issue by chrismahony** [satijalab/seurat#3033]
Can you tell me, when I use the downsample function, how does seurat exclude or choose cells?

Thanks
Chris

**Comment by yuhanH** [comment]
Hi, 
You can set `invert = TRUE`, then it will exclude input cells. 
For example
```
select.cell <- WhichCells(pbmc_small, idents = 0)
pbmc_small <- subset(x = pbmc_small, cells = select.cell, invert = TRUE)
```

**Comment by chrismahony** [comment]
Thanks for this, but I really want to understand more how the downsample function actualy works. If I have an input of 2000 cells and downsample to 500, how are te 1500 cells excluded? What pareameters are excluding these cells? Thanks

**Comment by yuhanH** [comment]
downsample is an input parameter from `WhichCells`

Maximum number of cells per identity class, default is Inf; downsampling will happen after all other operations, including inverting the cell selection

**Comment by bug1303** [comment]
It's a closed issue, but I stumbled across the same question as well, and went on to find the answer.

You can see the code that is actually called as such: `SeuratObject:::subset.Seurat`, which in turn calls  `SeuratObject:::WhichCells.Seurat` (as @yuhanH mentioned).

It first does all the selection and potential inversion of cells, and then this is the bit concerning downsampling:

```
    cells <- CellsByIdentities(object = object, cells = cells)
    cells <- lapply(X = cells, FUN = function(x) {
        if (length(x = x) > downsample) {
            x <- sample(x = x, size = downsample, replace = FALSE)
        }
        return(x)
    })

```

So indeed, it groups it into the identity classes (e.g. clusters or whichever idents are chosen), and then for each of those groups calls `sample` if it contains more than the requested number of cells. So, it's just a random selection.
