### ISSUE TITLE
DoHeatmap fix cells dimensions

### ISSUE THREAD

**Issue by GildasLepennetier** [satijalab/seurat#3034]
Hi all,
I was wondering how I could control the colored cells using DoHeatmap.
So far I have rectangle and their size change depending on the plotting device dimensions.
I found out it is possible to use **"+ coord_equal()"** to at least plot a square, but in this case _the top bar with the groups disappear_.
Anyone could advice me? I would like to have figures I could publish and when making several heatmaps, it looks clumsy to have different cell sizes.
I did not find any solution and after some hours of try-and-fail I decided to just ask you guys.
Thanks in advance!

Here some visual explanation:
[ without coord_equal() (default) ](https://i.postimg.cc/rFpHm08L/without-coord-equal.jpg)
[ with coord_equal(), but top bar disapear ](https://i.postimg.cc/2jGJrFNw/with-coord-equal.jpg)

**Comment by satijalab** [comment]
Apologies for the slow reply. This is a general question for ggplot2 graphics and I'm not sure we can advise on exactly how to help with what you're asking for.

I would note that with ggsave you can specify the exact dimensions of the resulting plot, and you should be able to use that to get exactly the dimensions you want.
