### ISSUE TITLE
Reorder cells by expression value in DoHeatmap & Dendogram

### ISSUE THREAD

**Issue by summerrfair** [satijalab/seurat#3036]
Two questions RE: DoHeatmap

1. Is there a straight-forward way to re-order the cells by their level of feature expression (e.g. re-order the plot below by decreasing GFAP expression left-to-right? If so, can someone provide an example? 

2.  I subsetted my object to create another object that includes a single cluster. Instead of clustering this new object, I'd like to find out how the cells group based on their expression of markers of interest (e.g. with a heatmap dendogram). Is this functionality possible with DoHeatmap?

<img width="521" alt="image" src="https://user-images.githubusercontent.com/56205753/82366672-93d2a100-99e0-11ea-8434-de838afe196c.png">

**Comment by mxposed** [comment]
Hope this helps
https://stackoverflow.com/questions/52136211/how-to-reorder-cells-in-doheatmap-plot-in-seurat-ggplot2

**Comment by andrewwbutler** [comment]
Re point 2, `DoHeatmap` doesn't support these kinds of dendrogram plots. However, it's worth noting that in order to draw those dendrograms, the cells would still need to be clustered in some way so I'd just recommend re-clustering the new object in that scenario.

**Comment by Elo-mars** [comment]
Hi @summerrfair ,
could you manage to do it?
the link provided by @mxposed  doesn't help me ... 

I also have a DoHeatmap that I want to order from low to high expression on 1 gene (multiple genes on my heatmap, but we care about one in particular)

any help would be greatly appreciated :)

**Comment by Eomesodermin** [comment]
not very nice, and not particularly efficient but something like this might work and might help you get to where you want to be. 

# extract data for gene of interest
x <- temp.seurat@assays$originalexp@data["Ifng", ]

x <- t(x)
x <- as.data.frame(x)
order.index <- order(x$V1, decreasing = T)
cell.order <- rownames(x)[order.index]



DoHeatmap(temp.seurat,
          cells = cell.order,
          features = c("Ifng", "Tnf"))

**Comment by Elo-mars** [comment]
> not very nice, and not particularly efficient but something like this might work and might help you get to where you want to be.
> 
> extract data for gene of interest x <- temp.seurat@assays$originalexp@data["Ifng", ]
> 
> x <- t(x) x <- as.data.frame(x) order.index <- order(x$V1, decreasing = T) cell.order <- rownames(x)[order.index]
> 
> DoHeatmap(temp.seurat, cells = cell.order, features = c("Ifng", "Tnf"))

thanks @Eomesodermin ,

the 1st line was not working for me, so I did:

```
x<- FetchData(SAMPLE, vars = "Gene", use.scaled = TRUE) 
x <- as.data.frame(x)
head(x)
order.index <- order(x$Gene, decreasing = FALSE)
cell.order <- rownames(x)[order.index]
head(cell.order)
  
  DoHeatmap(object = SAMPLE, cells = cell.order,features=c(Gene,"xxx","yyy","zzz"), group.by = "Pain_score", label = TRUE, angle=45) 

```
and it worked :) 
thanks!

**Comment by kpcr29** [comment]
How can I modify this code to apply the cell order to multiple genes? I tried creating cell.order files for each gene and merged it to one file. But I am running into error. 
Are there alternative methods to achieve the same? I failed to do so using pheatmap and complexheatmap tools.
