### ISSUE TITLE
VlnPlot: Don't print geom_jitter()

### ISSUE THREAD

**Issue by romanhaa** [satijalab/seurat#304]
Hi,

This is just a suggestion/feature request. I'm printing a lot of violin plots and would love to continue exporting them as PDF. It would be fantastic if there was an option to not print all cells (geom_jitter) or at least just x% of them to not overload the image. I tried setting the dot size to 0 but they just become small instead of disappearing.

Thanks!

**Comment by AndyR2** [comment]
Use "NA" and you should get no dots

**Comment by romanhaa** [comment]
Ok thanks! But still it would be nice to have the option to only plot a fraction ;)
