### ISSUE TITLE
Time series dataset in two conditions

### ISSUE THREAD

**Issue by abhisheksinghnl** [satijalab/seurat#3040]
Dear members and author,

I have a scRNA-seq dataset in two conditions and across 3 different time points. I was wondering which of the Seurat vignettes would be most helpful. 

Could anyone of you direct me in the right direction. 

Many thanks in advance.

Best regards
Abhishek

**Comment by aubreyghoward** [comment]
I would recommend that you review the Guided tutorial, Multiple dataset integration (specifically the SCT method), and the Stimulated vs Control PBMCs, in that order. Due the large probable size of your final dataset, I think that the manipulations found within the Mouse Cell Atlas Vignette might also prove useful. The VIsualization and Cell cycle regression vignettes were also particularly helpful for our analysis of similar conditions. Lastly, I recommend that you review the methods in [Farnsworth et al. 2020](https://www.sciencedirect.com/science/article/pii/S0012160619304919?via%3Dihub) as well as [Soldatov et al., 2019](https://science.sciencemag.org/content/364/6444/eaas9536.editor-summary) for further help. Hope that this was useful.

**Comment by aubreyghoward** [comment]
also follow responses to #3019

**Comment by abhisheksinghnl** [comment]
Thank you for your reply :)

**Comment by yuhanH** [comment]
@aubreyghoward  Thanks for your help.
