### ISSUE TITLE
Loss of SCT features after merging

### ISSUE THREAD

**Issue by mairenileath** [satijalab/seurat#3041]
Hi,

Firstly, thanks for providing such a fantastic package and set of workflows.

Currently using Seurat package version 3.1.5.9003.
I'm attempting to merge a number of Seruat objects all with RNA and SCT assays. However after merging, I find that zero counts have not been added for features present in one object but not another only for the SCT assay. 

So looking at merged[['SCT']]@counts and merged[['SCT']]@data I see the expect number of features but looking at merged[['SCT']]@scale.data it appears that features not shared have been excluded. Should this be the case? Is there a way around this?

*EDIT* Just realised that this looks similar to #2999 which remains an open issue. To clarify further, I'm running SCTransform on samples individually, then merging but dropping @scale.data entries after doing this.

Thanks so much. Grateful for the help!

All the best,
M

**Comment by andrewwbutler** [comment]
Hi,

Yes, this should be the case for the scale.data slot of SCT assays. As mentioned in #2999, it is unclear what values should be present for those residuals in the scale.data matrix (you can't just fill with 0s - a 0 residual is not the same as a 0 count) so we opt to remove those features from the merged SCT assay.
