### ISSUE TITLE
UMAP inconsistency

### ISSUE THREAD

**Issue by yinshiyi** [satijalab/seurat#3042]
Seurat V3.1.2
DEGs and clusters remains the same, however, the cluster moves around compared to same script I ran one month ago.
did not modify r 
Thanks.

**Comment by aubreyghoward** [comment]
Different embedding seed perhaps? Also, did you update Seurat? that is also a likely cause we have observed.

**Comment by yinshiyi** [comment]
pancreas.integrated <- RunUMAP(pancreas.integrated, reduction = "pca", dims = 1:30)
i ran the default code, so i think the seed is either 42 or 42L, but neither of them matches with my previous plot.
I didnt update seurat

**Comment by timoast** [comment]
Did you update any other packages, for example uwot or umap-learn? https://github.com/satijalab/seurat/issues/2449
