### ISSUE TITLE
DefaultAssay

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#3043]
I am using vignette dealing with [integrating stimulated vs. control PBMC datasets](https://satijalab.org/seurat/v3.1/immune_alignment.html). I came across following step/line and I am wondering what this step does. I see gene expression level among clusters changes dramatically if I skip this step. Why is it important? How it affect the gene expression level and percentage of cells when visualized on DotPlot?

 >DefaultAssay(immune.combined) <- "RNA"

Thank you.

**Comment by timoast** [comment]
`DefaultAssay()` changes the currently active assay in the Seurat object. The Seurat object can store multiple independent assays, with the requirement that the same cells are present across assays. This can be used for different experimental methods that measure multiple data modalities per cell (eg, CITE-seq measures RNA and protein, SNARE-seq measures RNA and ATAC), or storing different processed forms of the data (eg, integrated data, log-normalized data, SCTransform-normalized data) within a single object.
