### ISSUE TITLE
Cannot install Seurat v3.2 for spatial vignette

### ISSUE THREAD

**Issue by amcgarry36** [satijalab/seurat#3044]
Hello,

I am trying to follow the spatial vignette. When I try to install Seurat v3.2 with the following command 

> devtools::install_github("satijalab/seurat", ref = "spatial")

It recommends updating all of the packages, then it comes up with an error. 

Downloading` GitHub repo satijalab/seurat@spatial

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: backports (1.1.6 -> 1.1.7) [CRAN]
5: tidyr     (1.0.3 -> 1.1.0) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
miniUI       (NA    -> 0.1.1.1) [CRAN]
shiny        (NA    -> 1.4.0.2) [CRAN]
spatstat     (NA    -> 1.64-1 ) [CRAN]
backports    (1.1.6 -> 1.1.7  ) [CRAN]
httpuv       (NA    -> 1.5.2  ) [CRAN]
xtable       (NA    -> 1.8-4  ) [CRAN]
sourcetools  (NA    -> 0.1.7  ) [CRAN]
fastmap      (NA    -> 1.0.1  ) [CRAN]
spatstat.... (NA    -> 1.17-0 ) [CRAN]
tidyr        (1.0.3 -> 1.1.0  ) [CRAN]
spatstat.... (NA    -> 1.4-3  ) [CRAN]
deldir       (NA    -> 0.1-25 ) [CRAN]
abind        (NA    -> 1.4-5  ) [CRAN]
tensor       (NA    -> 1.5    ) [CRAN]
polyclip     (NA    -> 1.10-0 ) [CRAN]
goftest      (NA    -> 1.2-2  ) [CRAN]
Installing 16 packages: miniUI, shiny, spatstat, backports, httpuv, xtable, sourcetools, fastmap, spatstat.utils, tidyr, spatstat.data, deldir, abind, tensor, polyclip, goftest
Installing packages into ‘C:/Users/amcga/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) unable to access index for repository https://mojaveazure.github.io/loomR/bin/windows/contrib/4.0:
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/windows/contrib/4.0/PACKAGES'

Can anyone else help me with this?

Best
Aisling

**Comment by PaulaNietoG** [comment]
I think it's a problem with loomR and R v 4.0... Installing loomR beforehand and running
`devtools::install_github("satijalab/seurat", ref = "spatial", dependencies = F)`
worked for me :)

**Comment by amcgarry36** [comment]
Hey,

Thanks for your suggestion! I tried this but appeared to get another error.

`> devtools::install_github("satijalab/seurat", ref = "spatial", dependencies = F)`

Downloading GitHub repo satijalab/seurat@spatial

√  checking for file 'C:\Users\amcga\AppData\Local\Temp\RtmpOKnJAf\remotes8ffc6e126ac6\satijalab-seurat-5070f35/DESCRIPTION' (356ms)
-  preparing 'Seurat': (354ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (499ms)
-  checking for empty or unneeded directories
-  building 'Seurat_3.1.4.9904.tar.gz'
   
Installing package into ‘C:/Users/amcga/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependencies 'miniUI', 'shiny', 'spatstat' are not available for package 'Seurat'
* removing 'C:/Users/amcga/Documents/R/win-library/4.0/Seurat'
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/amcga/AppData/Local/Temp/RtmpOKnJAf/file8ffc50d86fe5/Seurat_3.1.4.9904.tar.gz’ had non-zero exit status

Can anyone help?

**Comment by PaulaNietoG** [comment]
Hi, @amcgarry36 have you tried installing miniUI, shiny and spatstat **before** installing Seurat?

**Comment by amcgarry36** [comment]
Hi I just installed miniUI, shiny and spatstat and tried the command again: 

`devtools::install_github("satijalab/seurat",` ref = "spatial", dependencies = F)`

Downloading GitHub repo satijalab/seurat@spatial
√  checking for file 'C:\Users\amcga\AppData\Local\Temp\RtmpiqGDkp\remotes8f40781a3d6c\satijalab-seurat-5070f35/DESCRIPTION' (393ms)
-  preparing 'Seurat': (382ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (541ms)
-  checking for empty or unneeded directories
-  building 'Seurat_3.1.4.9904.tar.gz'
   
Installing package into ‘C:/Users/amcga/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'Seurat' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/amcga/Documents/R/win-library/4.0/Seurat'
* restoring previous 'C:/Users/amcga/Documents/R/win-library/4.0/Seurat'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\amcga\Documents\R\win-library\4.0\00LOCK-Seurat\Seurat\libs\x64\Seurat.dll to C:\Users\amcga\Documents\R\win-library\4.0\Seurat\libs\x64\Seurat.dll: Permission denied
* removing 'C:/Users/amcga/Documents/R/win-library/4.0/Seurat'
* restoring previous 'C:/Users/amcga/Documents/R/win-library/4.0/Seurat'
Error in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) : 
  (converted from warning) problem copying C:\Users\amcga\Documents\R\win-library\4.0\00LOCK-Seurat\Seurat\libs\x64\Seurat.dll to C:\Users\amcga\Documents\R\win-library\4.0\Seurat\libs\x64\Seurat.dll: Permission denied
Execution halted
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/amcga/AppData/Local/Temp/RtmpiqGDkp/file8f40720776a5/Seurat_3.1.4.9904.tar.gz’ had non-zero exit status

**Comment by mojaveazure** [comment]
@amcgarry36, I've updated the loomR repo so devtools should now not freak out when installing the spatial branch of Seurat. When doing your install, please make sure you're starting from a fresh R session with no packages attached and no objects in memory. R doesn't like it when you try to install a package that's already loaded (which is when you get: ERROR: cannot remove earlier installation, is it in use?).
