### ISSUE TITLE
Unable to deploy shiny app using seurat package to shiny.io

### ISSUE THREAD

**Issue by ntran95** [satijalab/seurat#3047]
Hi there,

I'm encountering the same error message that was previous mentioned in Issue #2716  when attempting to deploy my app to shiny.io despite installing the latest CRAN release of seurat 3.1.5, as suggested in Issue #3002 

Here's my error message:

> Error: Unhandled Exception: Child Task 735000534 failed: Error parsing manifest: Unable to determine package source for Bioconductor package Seurat: Repository must be specified

I've also attempted to set my repositories to Bioconductor as well to no avail.

Do you have any insights to a solution or help elucidate the error message? Any insights is greatly appreciated!

Here is my sessionInfo():

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS: /gpfs/packages/R/3.5.1/lib64/R/lib/libRblas.so
LAPACK: /gpfs/packages/R/3.5.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1  Matrix_1.2-14   tools_3.5.1     grid_3.5.1      lattice_0.20-35
>

**Comment by timoast** [comment]
Hi, we came across this [issue before](https://github.com/satijalab/seurat/issues/2716) and found it was due to the `biocViews` tag in our description file. We had added the tag so that bioconductor suggested package could be automatically installed using `devtools::install()`, but later found it can cause problems like this. We had meant to remove the tag earlier but I think there was some confusion and it wasn't actually removed. I have removed it now and the fix will be available on the develop branch shortly.

**Comment by ntran95** [comment]
Hi @timoast , thank you so much for your prompt response.

My error message was resolved using the github development version

``d> packageVersion("Seurat")``

> [1] ‘3.1.5.9003’

**Comment by Lobbii** [comment]
> Hi @timoast , thank you so much for your prompt response.
> 
> My error message was resolved using the github development version
> 
> `d> packageVersion("Seurat")`
> 
> > [1] ‘3.1.5.9003’

Hi did you install the GitHub development version? I

Here is my script for installation of Seurat in global.R, which produces same error as yours.
# 
install.packages('devtools')
devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')
library(Seurat)



DONE
Uploading bundle for application: 2338352...Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package lsei
Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package npsurv
DONE
Deploying bundle: 3180184 for application: 2338352 ...
Waiting for task: 735608171
  building: Processing bundle: 3180184
  building: Parsing manifest
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 735608173 failed: Error parsing manifest: Unable to determine package source for Bioconductor package Biobase: Repository must be specified

**Comment by ntran95** [comment]
@Lobbii 

Hi there,
yes the error message was resolved after I installed the github developmental version.
