### ISSUE TITLE
Integrate Seurat objects that are already "integrated"

### ISSUE THREAD

**Issue by Dzhan4** [satijalab/seurat#3049]
Hello,

I have a question about the validity of using the standard workflow (find anchors, integrate) on Seurat objects that are already combined or integrated. Essentially I'm trying to integrate publicly available scRNA datasets and for many of the datasets, I do not have individual batch level data. Most of these runs are done on 10X and I have some of the h5 files for samples, but for others, the data is just available as a combined Seurat object already. 

My issue is that some of the samples are FACS sorted, some are not, most libraries are constructed using 10X, but some are done using Smart-Seq2. I would like to batch correct if possible, but I don't have access to individual sample level data. 

I'm guessing it's inappropriate to enter the "combined" Seurat object as an input for integration? Should I just try to deconstruct the combined Seurat object into sample-level Seurat objects if it's available and then use that for integration? 

Thank you in advance!

**Comment by timoast** [comment]
If you want to integrated different datasets they need to be input as separate Seurat objects. You can use the `SplitObject()` function to split the object into a list of different Seurat objects based on metadata. If there is information somewhere relating each cell to the original dataset it came from, I'd suggest splitting the object based on that and then running the integration workflow
