### ISSUE TITLE
Clustering 

### ISSUE THREAD

**Issue by such-debt** [satijalab/seurat#3050]
I'm working with a txt file from GSE59739 which contain gene/reads as rows and cells as columns. I want to make it into a Seurat object and perform all of the same analyses in the tutorial. 

`table<- read.delim("file.txt")`
 
`sobject<- CreateSeuratObject(table, project = "SeuratProject", assay = "RNA", min.cells = 0, min.features = 0, names.field = 1, names.delim = "_", meta.data = NULL)`

I got this warning message: Warning message: In storage.mode(from) <- "double" : NAs introduced by coercion
 
`sobject[["percent.mt"]] <- PercentageFeatureSet(sobject, pattern = "^MT-")`

Then I get this error: Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  no 'dimnames[[.]]': cannot use character indexing

How can I get the original data into the correct format to proceed?

**Comment by timoast** [comment]
Does the count matrix have the expected structure after you read it in? Seurat requires that gene names are stored as the row names and cell names as the column names of the matrix. My guess would be that you need to add `row.names=1, header=TRUE` to your `read.table()` call.
