### ISSUE TITLE
Featureplot gene co-expression without scale

### ISSUE THREAD

**Issue by bioinfowinfo** [satijalab/seurat#3052]
Hi. 

I'm currently analysing a fairly large 10X dataset using Seurat ( as an aside it's great! ) and need to plot the co-expression of a number of genes on a UMAP. I understand that this can easily be done with Featureplot using `blend=T`, however I do not want the cells to be coloured in a scale according to expression level; I simply want cells expressing both genes to be coloured in a binary fashion e.g red for double positive, grey for single positives and double negatives.

Is this possible?

**Comment by yuhanH** [comment]
Sure. You can modify the expression value to the binary, and Blend Featureplot will show the binary way. I use pbmc_small as an example. 
You need to set the cutoff for the genes to convert to binary.
```
  pbmc_small[["RNA2"]] <- pbmc_small[["RNA"]]

  pbmc_small[["RNA2"]]@data["PPBP" , ] <- 0
  pbmc_small[["RNA2"]]@data["PPBP",    WhichCells(pbmc_small, expression = rna_PPBP > 2) ] <- 1
  
  pbmc_small[["RNA2"]]@data["PF4" , ] <- 0
  pbmc_small[["RNA2"]]@data["PF4",    WhichCells(pbmc_small, expression = rna_PF4 > 2) ] <- 1
  
  FeaturePlot(pbmc_small  , features = c("rna2_PPBP", "rna2_PF4" ), blend = T) 
  FeaturePlot(pbmc_small  , features = c("rna_PPBP", "rna_PF4" ), blend = T) 
  
```

**Comment by bioinfowinfo** [comment]
Thanks again for the reply.

To be more clear, I'm looking to only colour the double positives. For example in the iris plot [here](https://imgur.com/a/GHIvgnI) I would want to keep colouring only the yellow cells, and have everything else grey.

**Comment by yuhanH** [comment]
Get it. The blend plot right now just support the union expression. 
But you can do your own calculation. After you binarize the expression, you can calculate value for doulble positive cells, and then use `FeaturePlot` directly. 
For example
```
  pbmc_small[["RNA2"]] <- pbmc_small[["RNA"]]

  pbmc_small[["RNA2"]]@data["PPBP" , ] <- 0
  pbmc_small[["RNA2"]]@data["PPBP",    WhichCells(pbmc_small, expression = rna_PPBP > 2) ] <- 1
  
  pbmc_small[["RNA2"]]@data["PF4" , ] <- 0
  pbmc_small[["RNA2"]]@data["PF4",    WhichCells(pbmc_small, expression = rna_PF4 > 2) ] <- 1
  
 pbmc_small[["RNA2"]]@data["PPBP" , ] <-   pbmc_small[["RNA2"]]@data["PF4" , ]  *   pbmc_small[["RNA2"]]@data["PPBP" , ] 
  
  FeaturePlot(pbmc_small  , features = c("rna2_PPBP" ) ) 

```

**Comment by bioinfowinfo** [comment]
That's fantastic. Works great if a little slow; but that's a result of the size of my data set.

Thanks for the help.

**Comment by DadongZ** [comment]
Thanks for the codes. I used split.by=variable in the FeaturePlot() and it turned out the dot sizes are auto scaled for the two groups, though I have used pt.size =0.5. How can I force the two groups use same pt.size?
![size](https://user-images.githubusercontent.com/8431321/111384708-36e75c00-8680-11eb-9700-148c03fdcd64.png)
