### ISSUE TITLE
Getting parameters from pre-existing reduction (umap)

### ISSUE THREAD

**Issue by oh111** [satijalab/seurat#3053]
Hi there, 

I have a Seurat Object which has pca and umap reductions already performed. Is there a way to get ALL the parameters that were used for the reduction? 

Thanks!

**Comment by tuqiang2014** [comment]
you can do like this

Seurat::pbmc_small@commands

**Comment by oh111** [comment]
Hi--
Thanks for your response. 
1. With that command I get the error: `Error: 'Lung' is not an exported object from 'namespace:Seurat'`
2. If I just use Lung@commands, I get List(), when I go into the Seurat Object to look at the commands manually, there is nothing there. 
This Seurat Object is from https://www.tissuestabilitycellatlas.org/lung and the graph generated in R is the same as the virtual viewer. I am just looking for all the parameters that they've used to get the pca or umap!

**Comment by timoast** [comment]
The command history is normally stored in the `commands` slot as @tuqiang2014 pointed out. If the object was constructed in a non-standard way, the slot may not be filled correctly. I would look for the written methods or code for how the object was constructed by the original authors.
