### ISSUE TITLE
output genes from RunPCA

### ISSUE THREAD

**Issue by benxiahu** [satijalab/seurat#3054]
Hi,
  When I run RunPCA (RunPCA(data, npcs = 100, ndims.print = 1:5, nfeatures.print = 5)), it will print 5 positive and negrative genes for each PC, like this:
PC_ 1 
Positive:  KCNQ5, STXBP5L, MEG3, RALYL, RYR2 
Negative:  PTGDS, SLC1A3, NEAT1, FBXL7, PLP1 
PC_ 2 
Positive:  TUBB2A, CALM1, NEFL, YWHAH, TUBA1B 
Negative:  LRP1B, CTNNA2, LRRTM4, ERBB4, PTPRZ1 
PC_ 3 
Positive:  RP11-123O10.4, ZNF385D, GAD1, DLX6-AS1, GAD2 
Negative:  AC011288.2, FAM19A1, MLIP, SATB2, GPR98 
PC_ 4 
Positive:  ST18, PLP1, MBP, MOBP, CLDN11 
Negative:  CLDN5, FLT1, EBF1, ATP10A, EPAS1 
PC_ 5 
Positive:  PLP1, ST18, MBP, CLDN11, SLCO1A2 
Negative:  SLC1A2, GPR98, RNF219-AS1, GPC5, COL5A3

Howto get top 2000-5000 PCA loading genes ranked across significant PCs.
Best,

**Comment by timoast** [comment]
See the `Loadings()` function: https://rdrr.io/cran/Seurat/man/Loadings.html
