### ISSUE TITLE
missing features in SCT scale data of integrated object 

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#3056]
Is there a way to calculate SCT scale data of all features, separately?

So I integrate 5 objects using 5000 features, however, many genes are thus still unaccounted for in the [["SCT"]]@scale.data. Which is annoying for downstream analyses using DoHeatmap for example. 

Even if I use the all_features setting, it does not seem to include features that have zero counts in one of the 5 objects.

**Comment by yuhanH** [comment]
Hi,
You are right.  Pearson residues cannot be calculated for the genes that have zero counts across all cells within one individual object. But for the downstream analysis such as heatmap, you can use scale.data in RNA assay.
