### ISSUE TITLE
principal component analysis (PCA) of single cell samples which come from different libraries

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3058]
Hello,

I have 17 single cell samples which come from different libraries.

They are 8 healthy, 3 mild and 6 severe patients samples.

First, I want to do the principal component analysis (PCA) of these 17 samples to see whether the healthy samples can cluster together.

Which command I can use?

Thanks in advance for any great help!

Best,

Yue

**Comment by nicodemus88** [comment]
Hi @yueli711,
You can just merge all the samples into 1 huge Seurat object and run PCA on it. 
Please check out the vignettes and try it. 
Asking which command you can use is too general for others to provide guidance.
