### ISSUE TITLE
Is there a way to pull the genes expressed for specific cells in different clusters?

### ISSUE THREAD

**Issue by xihuiyin** [satijalab/seurat#3060]
Hello, I want to investigate the gene expression profiles of cells from various clusters that are expressing a specific gene. Is it possible to do this? Is there also a way to rank them by p-value?

**Comment by tuqiang2014** [comment]
i try  to understand  what you  mean.
+ specific gene  with  specific cell . you can  `?Seurat::subset`, filter cell by gene list  
+  you want to get  Cluster marker genes  .you can `?Seurat::FindMarkers`

**Comment by xihuiyin** [comment]
Hi, unfortunately, what I wanted is to find cells that are expressing a certain gene, i.e Tnfrsf1a, and then for all of the cells expressing Tnfrsf1a, I want to look at the genes that they are expressing.

**Comment by nicodemus88** [comment]
Hi @xihuiyin ,
You can just make a new Seurat object by subsetting for cells which express the certain gene you want.

`newSO <- subset(so, subset = TNFRSF1A > 0)`

Then you can look at their gene expression using the new Seurat object.
