### ISSUE TITLE
Vars.to.regress (SCTransform)

### ISSUE THREAD

**Issue by AlejandraRodelaRo** [satijalab/seurat#3061]
Hello,

In the vignettes for **SCTranform** the variables to regress include the mitochondrial content (percent.MT). Also, depending on the cell-cycle score you can also add to S.Score and G2M.Score to the list of variables to regress: 
 sc <- SCTransform(sc ,vars.to.regress = c("percent.MT", "S.Score", "G2M.Score"))

I have seen in other issues that researchers decide to include other variables such as nº Features, nº Counts or the percentage of ribosomal content: 
 sc <- SCTransform(sc,vars.to.regress = c("percent.MT","percent.ribo","nFeature_RNA","nCount_RNA", "S.Score", "G2M.Score"))

Until which point is useful to add nFeatures and nCounts as **vars.to.regress** ? Isn't SCTranform already normalizing based on the UMI count data? 
I would appreciate some general guidance on the variables to regress. 

Thank you!

**Comment by yuhanH** [comment]
HI, 
SCTransform is designed to eliminate the influence of sequencing depth. The nCount_RNA is used to construct the sct mode, so you don't need to put it into `vars.to.regress`. 
If you have interest, you can read the SCT paper to learn more about how it control those confound variables. https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1
