### ISSUE TITLE
spatialfeatueplot install

### ISSUE THREAD

**Issue by 117999** [satijalab/seurat#3062]
Hi, I am recently running the SeuratData for spatial transcriptome tutorial, and I am encountering the following question. After I have coded as described in the tutorial
devtools::install_github("satijalab/seurat", ref = "spatial") library(Seurat) devtools::install_github('satijalab/seurat-data') library(SeuratData) library(ggplot2) library(patchwork) library(dplyr) InstallData("stxBrain") ?stxBrain brain <- LoadData("stxBrain", type = "anterior1") plot2 <- SpatialFeaturePlot(brain, features = "nCount_Spatial") + theme(legend.position = "right")
it appears that the function SpatialFeaturePlot does not exist, so I am wondering, where the function lies and how to install it. Thank you

**Comment by tuqiang2014** [comment]
`SpatialFeaturePlot `is a  function  of  Seurat 3. So   check  your  install info  and  ` packageVersion("Seurat")`    and  then  `?Seurat::SpatialFeaturePlot `

**Comment by andrewwbutler** [comment]
Yep, check the installed version and perhaps try a fresh restart of R to be sure it's loading the correct version. The install commands you list should work thought to get all relevant spatial functionality.
