### ISSUE TITLE
Performing DEG analysis for just one gene between conditions for one cluster?

### ISSUE THREAD

**Issue by Volocinator** [satijalab/seurat#3063]
Hi all,

I have a Seurat object containing diseased and wild type cells. I have run a UMAP, and subsequently the FindMarkers function to find significant differentially expressed genes between the conditions in each UMAP cluster. My dataset however has returned very few significant genes, and so my approach now is to perform informed analysis using genes I know to be canonically upregulated and down regulated in the diseased model. Does Seurat allow for single gene differential expression testing?

Many thanks,

James

**Comment by tuqiang2014** [comment]
yes, you can  run  `?Seurat::FindMarkers`. and then   we can run  `wilcox，bimod，roc，t，negbinom，poisson，LR，MAST，DESeq2`  in  Seurat.

**Comment by k3yavi** [comment]
Hi @Volocinator ,

I am not sure I completely understand the motivation but the following command should work.

```
# downloading the pbmc_3k data from SeuratData
library(SeuratData)

# setting up the Seurat object and perform clustering.
pbmc3k <- NormalizeData(pbmc3k) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA() %>% FindNeighbors() %>% FindClusters()
pbmc3k

# perform DE on gene "GIMAP4" between cluster 1 and 2
FindMarkers(pbmc3k, ident.1 = "1", ident.2 = "2", features = "GIMAP4")

```
