### ISSUE TITLE
Error in names(x) <- value :    'names' attribute [1] must be the same length as the vector [0]

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3065]
Hello,

I have problem in upload my data.

Thank you in advance fr great help!

Best,

Yue

```
> D1<-read.csv(file='donor_82_01.csv', sep='\t',row.names=1, header=T)
> D2<-read.csv(file='donor_85_02.csv', sep='\t',row.names=1, header=T)
> colnames(D1)=paste0('D1_', colnames(D1))
Error in names(x) <- value : 
  'names' attribute [1] must be the same length as the vector [0]
```

[donor_82_01.zip](https://github.com/satijalab/seurat/files/4675426/donor_82_01.zip)

**Comment by andrewwbutler** [comment]
Hi,

This isn't really a Seurat issue but it looks like you've specified a tab delimiter (`sep='\t'`) on a csv file. Try changing to `sep = ','`.
