### ISSUE TITLE
merge eight files in *.csv format into one *.csv file

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3066]
Hello, 

I have eight samples in *.csv format.

How I can merge them together into one *.csv file and do the Seurat analysis？

Thanks in advance for great help!

Best,

Yue

**Comment by samuel-marsh** [comment]
Hi Yue,

Please see your previous post #3026

**Comment by yueli711** [comment]
Hello samuel-marsh,

Thank you so much for your quick response!

Thank yu again and really appreciated!

Best,

Yue

```
> a<-read.csv(file='donor_82_01.csv', sep=",", row.names=1, header=TRUE, as.is=T)
> b<-read.csv(file='donor_85_02.csv', sep=",", row.names=1, header=TRUE, as.is=T)
> ab<-merge(x=a, y=b)
Killed
```


[donor_82_01.zip](https://github.com/satijalab/seurat/files/4681241/donor_82_01.zip)
[donor_85_02.zip](https://github.com/satijalab/seurat/files/4681243/donor_85_02.zip)

**Comment by samuel-marsh** [comment]
Hi,

Without more info on system and the "Killed" message I'm not sure there is anything I can do.  I would say again though (as before #3026) that this seems to be more of a general R/personal system issue and not specific to Seurat, as issue is at the level of merging .csv files.  I would highly recommend posting to StackExchange about the issue as that is probably better forum for solving your particular issue.

Best!
Sam
