### ISSUE TITLE
SpatialFeaturePlot

### ISSUE THREAD

**Issue by Shintaroya** [satijalab/seurat#3067]
Hi, 

I'd like to set the same limit of scale in SpatialFeaturePlot to compare expression between samples.
For instance, the minimum is 0.0 and the maximum is 2.5.
Can I set them manually? 

Best,
Shintaroya

**Comment by jaisonj708** [comment]
Hi @Shintaroya, you can set them using the `min.cutoff` and `max.cutoff` parameters in SpatialFeaturePlot
