### ISSUE TITLE
TopFeatures function not working

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#3068]
Hi Seurat team,

I tried to call the `TopFeatures` function but I was unable to do it for more than 1 dimensions. 

```
## Working if only 1 dimension is specified
>TopFeatures(so, dim = 1, nfeatures = 10, balanced = TRUE)
$positive
[1] "LTB"        "RPS8"       "IL7R"       "AC010197.2" "CAMK4"     
$negative
[1] "NKG7"   "TYROBP" "GZMB"   "FGFBP2" "CCL5"  

## Not working if more than 1 dimension is requested
> TopFeatures(so, dim = 1:3, nfeatures = 10, balanced = TRUE)
Error in data[order(data, decreasing = TRUE), , drop = FALSE] : 
  subscript out of bounds
> TopFeatures(so, dim = c(1,2), nfeatures = 10, balanced = TRUE)
Error in data[order(data, decreasing = TRUE), , drop = FALSE] : 
  subscript out of bounds
```

I think it's most likely due to the **matrix ordering step** in the `Top` function embedded in `TopFeatures` where it sorts the whole matrix and then re-orders it. After ordering the data, I got a list of vectors which is equal to the number of cells in the matrix but I could not use it to subset the matrix. 

```
Top <- function(data, num, balanced){
  top <- if (balanced) {
    num <- round(x = num / 2)
    data <- data[order(data, decreasing = TRUE), , drop = FALSE]
    positive <- head(x = rownames(x = data), n = num)
```

I could not find any possible solution on how to sort a matrix with indexed vectors. Anyone have any idea how to solve this issue? 

Thank you very much.

**Comment by samuel-marsh** [comment]
Hi,

Not a direct solution to your question but is there reason why not to write a loop to iterate across the number of dimension you want TopFeatures for?

Best,
Sam

**Comment by nicodemus88** [comment]
@samuel-marsh Thank you for your suggestion. That was indeed what I did. I posted this question in haste as I initially thought the function orders the entire matrix before selecting features, but then I realized this was wrong. 

Anyway, I solved the issue and I will be closing this thread. Thank you!
