### ISSUE TITLE
Meaning of parameter "resolution"

### ISSUE THREAD

**Issue by LiJiaqi96** [satijalab/seurat#3069]
Hi,

Thanks for your contribution of the great Package Seurat.

While using, I am curious about the "resolution" parameter used in "FindClusters" function. Could you please briefly explain the how does this parameter affects the Louvain clustering used in Seurat? I would like to form an intuitive understanding of this parameter so there's no need for mathematical detail.

Thanks a lot!

**Comment by tuqiang2014** [comment]
more info  for  this    issues  
https://github.com/biolab/orange3/issues/3184

**Comment by LiJiaqi96** [comment]
Thanks for your suggestions. Does Seurat employ the strategy of Laplacian dynamics with the "resolution" parameter? Or it just implements as original Louvain algorithm did in (Blondel at al.)?

**Comment by andrewwbutler** [comment]
Hi,

Resolution is implemented as in the original algorithms.
