### ISSUE TITLE
Data reading problem

### ISSUE THREAD

**Issue by nunocr** [satijalab/seurat#3070]
Hello,

I'm new to R, and I'm trying to apply the Seurat clustering workflow from the tutorial to data obtained through single cell RNA sequencing.

I can't get past the Normalization and Feature Selection phases, which give me the following errors, respectively:

`> mySeuratObject <- NormalizeData(object = mySeuratObject)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Attempting to add a different number of cells and/or features`

and

`> mySeuratObject <- FindVariableFeatures(object = mySeuratObject, selection.method = 'vst', nfeatures = 2000, assay = "RNA")
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Cannot add more or fewer meta.features information without values being named with feature names`

When trying to find a cause for these issues, I noticed the data wasn't being loaded in the Seurat Object exactly like in the tutorial. More precisely, the rownames of the matrix weren't being loaded into the first element of Dimnames and the meta.features were NULL, as shown bellow:

![3](https://user-images.githubusercontent.com/15525793/82856307-8ac46100-9f05-11ea-92d4-9501191162f0.jpg)

To fix this, I applied the following steps:

````{r}
# Put rownames in Dimnames
mySeuratObject@assays$RNA@data@Dimnames[[1]] <- rownames(mySeuratObject.data)

# Put rownames in @meta.features
mySeuratObject@assays$RNA@meta.features <- data.frame(rownames(mySeuratObject.data), 0)
````

But I still get the same errors.

Am I doing something wrong? Could this be a problem related to the data I'm using?
I'm sending the files I'm using attached.

Thanks in advance!

[issue.zip](https://github.com/satijalab/seurat/files/4679756/issue.zip)

**Comment by nunocr** [comment]
[issue.zip](https://github.com/satijalab/seurat/files/4679754/issue.zip)

**Comment by timoast** [comment]
The problem is the way you're reading in the data, you're setting the first column to the gene name rather than the rownames as the gene names. You also log-transformed the counts before creating the object but then supplied the data as counts...this should work:

```r
mySeuratObject.data <- read.table("./counts.tab", header = TRUE, row.names = 1, sep = "\t")
mySeuratObject <- CreateSeuratObject(counts = mySeuratObject.data)
```

**Comment by nunocr** [comment]
It worked, thank you!
