### ISSUE TITLE
Data normalized with sctransform: integrating residuals vs. corrected counts

### ISSUE THREAD

**Issue by repeatpipettor** [satijalab/seurat#3071]
Dear developers,

The current workflow for [integrating datasets that have been normalized with sctransform](https://satijalab.org/seurat/v3.1/integration.html#sctransform) uses the Pearson residuals. However, the [sctransform vignette](https://satijalab.org/seurat/v3.1/sctransform_vignette.html) mentions that 

> You can use the corrected log-normalized counts for differential expression and integration. However, in principle, it would be most optimal to perform these calculations directly on the residuals (stored in the scale.data slot) themselves.

How different are the results obtained from integration of sctransform-normalized data using the residuals vs. the corrected counts? If one were interested in integrating the corrected log-normalized counts (stored in the `assays$SCT@count` slot) instead of the residuals, what workflow would you recommend?

Thanks very much.

**Comment by yuhanH** [comment]
Hi, 
We don't advice you to use the SCT corrected counts to do the integration.
 The counts are corrected by the sequencing depth of each batch, so sequencing depth within each batch is corrected for counts data. But when you do the integration between different batches, this corrected counts may not be proper to use. 
If you want to use `data` slot to integration, you would better use RNA assay. If you use SCT normalized data, residuals should be used for integration.

**Comment by pagarwal14** [comment]
Hi,
I have been confused about the difference between corrected and normalized counts and would greatly appreciate if you could provide an explanation.  I thought the "count" slot contains the raw counts (uncorrected and un-normalized) whereas the "data" slot contains the log-normalized counts.  Thanks.
