### ISSUE TITLE
FindMarkers avg_diff

### ISSUE THREAD

**Issue by Drosophilist** [satijalab/seurat#3074]
Dear Satija Lab,

In my analysis, the output of FindMarkers returns a data frame in which one of the columns has avg_diff instead of avg_logFC. I'm using the Roc test. To try to understand why this is happening I went to look at  /seurat/R/differential_expression.R and found the following:

 if (is.null(x = reduction)) {
    diff.col <- ifelse(
      test = slot == "scale.data" || test.use == 'roc',
      yes = "avg_diff",
      no = "avg_logFC"
    )
    de.results[, diff.col] <- total.diff[rownames(x = de.results)]
    de.results <- cbind(de.results, data.alpha[rownames(x = de.results), , drop = FALSE])
  } else {
    diff.col <- "avg_diff"
    de.results[, diff.col] <- total.diff[rownames(x = de.results)]
  }

From this, I got the idea that possibly FindMarkers could be using the scaled data matrix instead of the normalized data matrix. This left me a little bit worried since previously it has been mentioned that using scaled data for FindMarkers was inappropriate. https://github.com/satijalab/seurat/issues/62#issuecomment-300979805
I do not specify anything for the slot parameter, so I guess it should use the default slot data. 

Any idea why I have avg_diff instead of avg_logFC? I'm using Seurat version 3.1.5

Cheers

**Comment by satijalab** [comment]
Thanks for the question. Seurat is using the data slot for the ROC test, but the named column should indeed be avg_logFC. We will fix this, thanks for pointing out.

**Comment by Drosophilist** [comment]
@satijalab
Thank you so much for your answer. 
I'd also like to ask what is the purpose of pseudocount.use ? Why is this value necessary for the calculation of avg_logFC? 

Possibly the answer is really straightforward, I'm sorry, I'm new to single cell analysis.

Cheers,
Jose

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by Drosophilist** [comment]
I'm sorry to re-open the issue, but would love to get an answer to:
https://github.com/satijalab/seurat/issues/3074#issuecomment-639813399
Would this be possible?

@mojaveazure Thank you for solving the avg_diff issue.
Cheers

**Comment by duocang** [comment]
> @satijalab
> Thank you so much for your answer.
> I'd also like to ask what is the purpose of pseudocount.use ? Why is this value necessary for the calculation of avg_logFC?
> 
> Possibly the answer is really straightforward, I'm sorry, I'm new to single cell analysis.
> 
> Cheers,
> Jose

@Drosophilist 
In case people ask this. 

**simple answer**: Avoid zero-division error
**Tip**: set `pseudocount.use` as small as possible, ie. 0.01, otherwise it will cover up real DE.

Detail: 

```R
data.1 <- apply(X = data.use[genes.use, cells.1, drop = F], MARGIN = 1, 
        FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))
data.2 <- apply(X = data.use[genes.use, cells.2, drop = F], MARGIN = 1, 
        FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))
total.diff <- (data.1 - data.2)
```

if `x=0`, it happens that log(0) will cause an error.

No magic, just to avoid this case.
