### ISSUE TITLE
Difference in UMAP clustering for Pre-made Seurat Object from Scanpy (Python) and Seurat 

### ISSUE THREAD

**Issue by oh111** [satijalab/seurat#3075]
Hello!

I have a Seurat Object from [HCA](https://www.tissuestabilitycellatlas.org/lung).  The analysis they have performed for uMAP and PCA is through Python package Scanpy. I am trying to modify my Seurat UMAP analysis to match theirs. For this I have the following questions: 
1. Is there a way to get the specific parameters that they have used for their analysis for UMAP and PCA? 
2. After looking at their [code](https://github.com/elo073/TissStab/blob/master/10X-scanpy-lung_gh.ipynb), I have made the adjustments to all parameters except n.trees (default is 50 in Seurat). Is there a way to adjust this parameter [I located it to FindNeighbors, but I can't figure out how to change it]?
3. does the difference in clustering (within and between groups) matter?

Thanks for any information regarding this.

**Comment by timoast** [comment]
1. See https://github.com/satijalab/seurat/issues/3053
2. Not sure what parameter you're referring to here. There's no `n.trees` parameter in FindNeighbors or RunUMAP....there _is_ an `n_trees` parameter in `fftRtsne` from the [FItSNE](https://github.com/KlugerLab/FIt-SNE/blob/master/fast_tsne.R#L82) package
3. Matter in what way?
