### ISSUE TITLE
difficulty removing mitochondrial genes from integrated Read10X data

### ISSUE THREAD

**Issue by lpdmagee** [satijalab/seurat#3076]
Hi,

I'm attempting to use the standard integration workflow (vignette [here](https://satijalab.org/seurat/v3.1/integration.html)) to integrate Read10X data from a handful of files, which I've merged into a single Seurat object using the merge() function.

The issue is that I can't seem to eliminate the mitochondrial genes from the datasets once I've merged them. After splitting the merged data Seurat object into a list, I'm currently attempting to eliminate said genes in the same for loop used in the vignette to normalize the data and run findVariableFeatures:
<img width="834" alt="Screen Shot 2020-05-26 at 3 17 57 PM" src="https://user-images.githubusercontent.com/40338045/82955616-179e0780-9f64-11ea-8cc9-15a6bb47ffc1.png">

However, when I plot individual features of the integrated object, I find that mitochondrial genes are still present. I'm actually getting the same number of features without these two lines as I do with them, so I'm assuming the current method isn't actually doing anything. 

I should add that the reason I'm attempting to fix this issue is that I'm getting the following error when I attempt to merge all of the data from this "telo" set with data from another file, then findVariableFeatures on the merged object (the following screenshot is thus in a different file from the one above):
<img width="829" alt="Screen Shot 2020-05-26 at 3 24 01 PM" src="https://user-images.githubusercontent.com/40338045/82956111-eeca4200-9f64-11ea-89c9-8ba49fd23334.png">

In another thread (issue #2387), to this error was to further limit the expression matrix. So, besides being standard practice, I'm hoping that removing mitochondrial genes from the data will hopefully help to limit the overall matrix and solve the above issue in the merged data.

Grateful for any and all suggestions!

**Comment by nicodemus88** [comment]
Hi @lpdmagee ,
I'm not sure I understand what you mean, but the mitochondrial genes will be present even after normalization and finding variable features. The steps are not meant to remove the mitochondrial genes, but just to filter and retain, in your case, cells which expresses less than 5% mitochondrial genes.

**Comment by timoast** [comment]
Regressing out the percentage of mitochondrial counts from the dataset will not remove the mitochondrial genes from the dataset. I don't think this has anything to do with the second error from running `FindVariableFeatures`, can you open a new issue with the full code you're running that leads to this error, the output of `sessionInfo()`, and if possible a reproducible example?
