### ISSUE TITLE
GSVA or geneset analysis on integrated data?

### ISSUE THREAD

**Issue by ldr89** [satijalab/seurat#3078]
I am planning on integrating a couple of different scRNAseq dataset using Seurat's reciprocal PCA. Afterwards I would like to study differential expression of genesets (ideally using GSVA), and I was wondering if this is still possible using after data integration, since the integrated data will now be scaled? Thank you very much for your advice!

**Comment by timoast** [comment]
We recommend using the original, uncorrected measurements for differential expression (as indicated in the [FAQ](https://satijalab.org/seurat/faq.html) and several closed issues)
