### ISSUE TITLE
Adding metadata that classifies cells

### ISSUE THREAD

**Issue by nhend1441** [satijalab/seurat#3079]
I'm interested in classifying cells (from the same data set) based on whether they express a gene I'm interested in, then finding differentially expressed genes between these two classes. I'm thinking one way to do this is to add a metadata column to the Seurat object classifying the cells as +/- for the marker. I know how to create a new metadata column but I can't figure out how to make a column that classifies cells in this way. Is there a way to do this? Or maybe a better way to achieve what I'm attempting?

**Comment by nicodemus88** [comment]
Hi @nhend1441 ,
Maybe you can subset the cells you want first. Then extract the cell names followed by mutating a column in the original Seurat object metadata to mark these cells as positive.

```
## Make subset of cells expressing FOXP3
geneSO <- subset(so, subset = FOXP3 > 0)
## Get cell names
cellNames <- rownames(geneSO@meta.data)
## Mutate a column in original SO metadata
so$barcode <- rownames(so)
so@meta.data <- so@meta.data %>% mutate(FOXP3 = ifelse((so$barcode %in% cellNames), "Pos",  "Neg"))
```

**Comment by nhend1441** [comment]
Never mind, I figured it out.

**Comment by nicodemus88** [comment]
> Never mind, I figured it out.

Please post your solution here for reference by other users if it's different from what I suggested. I'm sure it will help other Seurat users as well.

**Comment by nhend1441** [comment]
Sorry, didn’t see that you responded when I closed the topic. I will try your solution later today and see if that works. Mine was much less elegant than yours but I can post it later as well if I can’t get your solution to work for me.

**Comment by nhend1441** [comment]
Sorry I didn’t see your original response when I closed the topic. Thanks for your suggestion. I didn’t post my solution because I’m pretty sure it’s a very roundabout way of doing it. I will try your solution later today and see if that works.

Thanks!

Nate

Sent from my iPhone

On May 28, 2020, at 4:45 AM, nicodemus88 <notifications@github.com> wrote:

﻿

Never mind, I figured it out.

Please post your solution here for reference by other users if it's different from what I suggested. I'm sure it will help other Seurat users as well.

**Comment by nhend1441** [comment]
Your solution seems to almost work but I'm getting hung up at the ##Get cell names step. I entered-

>Zs6@barcode<-rownames(Zs6@meta.data)

and get the following error message.

Error in (function (cl, name, valueClass)  : 
  ‘barcode’ is not a slot in class “Seurat”

**Comment by nicodemus88** [comment]
@nhend1441 , I guess you're trying to append a barcode slot in the metadata. You need to use the **`$ `**symbol, not `@` symbol. 

`Zs6$barcode <- rownames(Zs6@meta.data)`

**Comment by nhend1441** [comment]
Ah yes, that was a typo on my part. Thanks! As you can tell coding is not my specialty.

**Comment by christoforos-dimitropoulos** [comment]
> Hi @nhend1441 ,
> Maybe you can subset the cells you want first. Then extract the cell names followed by mutating a column in the original Seurat object metadata to mark these cells as positive.
> 
> ```
> ## Make subset of cells expressing FOXP3
> geneSO <- subset(so, subset = FOXP3 > 0)
> 
> ## Get cell names
> cellNames <- rownames(geneSO@meta.data)
> 
> ## Mutate a column in original SO metadata
> so$barcode <- rownames(so)
> so@meta.data <- so@meta.data %>% mutate(FOXP3 = ifelse((so$barcode %in% cellNames), "Pos",  "Neg"))
> ```

Hey, thanks for the reply. In case that one wants to annotate as positive the Foxp3>1 cells and as negative the Foxp3=0? How this would work? Because here with the ifelse() function you annotate the neg as the non-pos.

**Comment by pedrodcb** [comment]
I believe [this answer by atakanekiz on Biostars](https://www.biostars.org/p/408922/#9481647) is even more elegant. I've reformatted it here using your own Seurat object (so) and gene of interest (FOXP3) names:

```
poscells <- WhichCells(so, expression = FOXP3 > 0)

so$FOXP3_exp<- ifelse(colnames(so) %in% poscells, "Pos", "Neg")
```

@nicodemus88 your solution is good too but the following line did not work for me:
`so$barcode <- rownames(so)`

I don't know if I did something wrong but I go the following error with it:
`Error: Cannot add more or fewer cell meta.data information without values being named with cell names`

Cheers!
