### ISSUE TITLE
DoHeatmap with RNA vs Integrated Assay

### ISSUE THREAD

**Issue by merryberry2004** [satijalab/seurat#3081]
When I perform DoHeatmap using the Integrated assay, I get a proper-looking heatmap with values from -2 to 2. Meanwhile, if I use the RNA assay, the heatmap's scale runs from ~0 to 2 and therefore is predominantly the two extreme colors. Why is this, and how can I get the RNA assay heatmap to have a normal range of values? Should I be using the Integrated heatmap to visualized differential expression after CCA? I am normalizing and scaling the RNA data after integration, as well as finding markers using the RNA assay.

**Comment by timoast** [comment]
Can you include the full code that you're running?

**Comment by merryberry2004** [comment]
Baseline workflow:
```
obj.anchors <- FindIntegrationAnchors(object.list = c(obj1, obj2), dims = 1:30)
obj <- IntegrateData(anchorset = obj.anchors, dims = 1:30)
DefaultAssay(object = obj) <- "integrated" 
obj <- ScaleData(object = obj, verbose = FALSE)
obj <- RunPCA(object = obj, npcs = 30, verbose = FALSE)
obj <- FindNeighbors(obj, reduction = "pca", dims = 1:20)
obj <- FindClusters(obj, resolution = 0.5)
obj <- RunUMAP(object = obj, umap.method = "umap-learn",  metric = "correlation"
```

If I want to look at the de heatmap using the integrated assay I run the following:
```
var_genes <- VariableFeatures(obj)
DefaultAssay(obj) <- "RNA"
obj = SetIdent(object = obj, value = “labels”)
obj.markers %>% group_by(cluster) %>% top_n(2, avg_logFC)
DefaultAssay(object = obj) <- "integrated"
top10 <- obj.markers %>% group_by(cluster) %>% top_n(10, avg_logFC)
options(repr.plot.width = 25, repr.plot.height = 25)
DoHeatmap(object = obj, features = top10$gene)
```

If I want to look at the de heatmap using the RNA assay I run the following:
```
DefaultAssay(object = obj) <- "RNA"
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj = SetIdent(object = obj, value = “labels”)
var_genes <- VariableFeatures(obj)
obj.markers <- FindAllMarkers(object = obj, features = var_genes, min.pct = 0.25, thresh.use = 0.25)
obj.markers %>% group_by(cluster) %>% top_n(2, avg_logFC)
top10 <- obj.markers %>% group_by(cluster) %>% top_n(10, avg_logFC)
options(repr.plot.width = 25, repr.plot.height = 25)
DoHeatmap(object = obj, features = top10$gene)
```

**Comment by merryberry2004** [comment]
Since FindIntegrationAnchors() and IntegrateData() create an integrated assay with scaled data, I am wondering how exactly they create that scaled data and what parameters would be involved if you were to replicate that with ScaledData().

**Comment by timoast** [comment]
The code here looks fine to me, I would just make sure that all the features you're trying to plot in the heatmap have been scaled, as we only scale the variable features by default. We recommend using the uncorrected data for visualization, rather than the integrated assay.

> Since FindIntegrationAnchors() and IntegrateData() create an integrated assay with scaled data, I am wondering how exactly they create that scaled data and what parameters would be involved if you were to replicate that with ScaledData().

Not quite sure what you're asking here. The [paper](https://doi.org/10.1016/j.cell.2019.05.031) has details about how the integrated assay is created, in short it's created by subtracting cell-specific batch vectors from the expression vector of each cell in a query dataset. The scaled data is used for CCA, but is not otherwise used for defining the batch vectors.
