### ISSUE TITLE
the issue about subset function within seurat

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3082]
Hi @ALL，
     As of now i post, subset function indicate different cell number when i run it using below syntax,
    test1<-subset(combined1,subset=orig.ident==c('T19','T5','YX46'))
    test2<-subset(combined1,subset=orig.ident%in%c('T19','T5','YX46')) 
![image](https://user-images.githubusercontent.com/41668708/83089566-2eaa3a00-a0c9-11ea-9527-ea0ae8d6620d.png)
     The procedure of this funciton subset of seurat can work but error, however, the result that post above  display so different and  so weird.
     The purpose of this scripts that extract certainty sample subset that i interested, and  which syntax should be token for extract more than one sample in combined seurat, the first or second showing above?
     Any advices would be grateful.

**Comment by nicodemus88** [comment]
Hi @honghh2018 ,
There's nothing wrong with the function. It's just a syntax of base R for subsetting. 
Please use %in% instead of ==. 
Please refer to this explanation in stackoverflow for more explanation.

**Comment by timoast** [comment]
`%in%` and `==` are different operations, in this case you want to use `%in%`
