### ISSUE TITLE
Implementing clustree in my R code (New to coding)

### ISSUE THREAD

**Issue by Kedde92** [satijalab/seurat#3083]
Hello Seurat community 

I hope you can help me. I am totally new to coding, nevertheless, I have been given the task to analyze some scRNAseq data of zebrafish cardiomyocytes. I have followed the Seurat - Guided Clustering Tutorial and produced a tSNE plot. However, I would like to look into the resolution I use to cluster my cells. To this purpose, I would like to produce a clustering tree using CLUSTREE    (https://mran.microsoft.com/snapshot/2018-06-22/web/packages/clustree/vignettes/clustree.html), however, I have no idea how and where to implement it in my existing code (see below).

library(ggplot2)
library(cowplot)
library(Matrix)
library(Seurat)
library(dplyr)

#-----------------------------------------------------------------------------------------------------------------------------------
## Zebrafish_AR ##
AR <- Read10X(data.dir = "~/Desktop/ZF/AR/", gene.column = 1)
zf_AR <- CreateSeuratObject(counts = AR, min.cells = 5, min.features = 200,
                            project = "zf_AR")

#-----------------------------------------------------------------------------------------------------------------------------------
#Remove dead, dying, mutpul, empty and mutiple cell reads.
zf_AR[["percent.casp3"]] <- PercentageFeatureSet(zf_AR, pattern = "ENSDARG00000017905")
zf_AR[["percent.casp9"]] <- PercentageFeatureSet(zf_AR, pattern = "ENSDARG00000004325")
head(zf_AR@meta.data,5)

# plots to visualize where to set cut off values
VlnPlot(zf_AR, features = c("nFeature_RNA", "nCount_RNA","percent.casp3","percent.casp9"), ncol=5, pt.size = 0.05)

#remove cells
zf_AR <- subset(zf_AR, subset = nFeature_RNA > 200 & nFeature_RNA < 6500 & percent.casp3 < 0.01 & percent.casp9 < 0.01)

#-----------------------------------------------------------------------------------------------------------------------------------
#remove cells not expressing myl7 = ENSDARG00000019096,cmlc1 = ENSDARG00000032976 ,tnnt2a = ENSDARG00000020610
zf_AR <- subset(zf_AR, subset =  ENSDARG00000019096 > 1)
zf_AR <- subset(zf_AR, subset =  ENSDARG00000032976 > 1)
zf_AR <- subset(zf_AR, subset =  ENSDARG00000020610 > 1)
table(zf_AR$orig.ident)

#-----------------------------------------------------------------------------------------------------------------------------------
#Normalization
zf_AR <- NormalizeData(object = zf_AR, normalization.method = "LogNormalize", 
                             scale.factor = 1000)
#Most variable genes
zf_AR <- FindVariableFeatures(zf_AR, selection.method = "vst", nfeatures = 2000)

#scales data.
all.genes <- rownames(zf_AR)
zf_AR <- ScaleData(zf_AR, features = all.genes, vars.to.regress = "nCount_RNA")

#-----------------------------------------------------------------------------------------------------------------------------------
#Run linear dimensional reduction
zf_AR <- RunPCA(zf_AR, features = VariableFeatures(object = zf_AR))
print(zf_AR[["pca"]], dims = 1:5, nfeatures = 4)

#VizDimLoadings(zf_AR, dims = 1:5, reduction = "pca")

#-----------------------------------------------------------------------------------------------------------------------------------
#Examine how many dimensions to include in further analysis And run t-SNE
zf_AR_JackStraw <- JackStraw(zf_AR, num.replicate = 100, dims = 15)
zf_AR_JackStraw <- ScoreJackStraw(zf_AR_JackStraw, dims = 1:15)
JackStrawPlot(zf_AR_JackStraw, dims = 1:15)

ElbowPlot(zf_AR, ndims = 15)

#-----------------------------------------------------------------------------------------------------------------------------------
#clusters cells
zf_AR <- FindNeighbors(zf_AR, dims = 1:10)
zf_AR_res0 <- FindClusters(zf_AR, resolution = 0)
zf_AR_res01 <- FindClusters(zf_AR, resolution = 0.1)
zf_AR_res02 <- FindClusters(zf_AR, resolution = 0.2)
zf_AR_res03 <- FindClusters(zf_AR, resolution = 0.3)
zf_AR_res04 <- FindClusters(zf_AR, resolution = 0.4)
zf_AR_res05 <- FindClusters(zf_AR, resolution = 0.5)
#head(Idents(zf_AR), 20)

#-----------------------------------------------------------------------------------------------------------------------------------
#run t-SNE with 10 dims
zf_AR_res0 <- RunTSNE(object = zf_AR_res0, dims.use = 1:10, do.fast = TRUE, check_duplicates = FALSE)
zf_AR_res01 <- RunTSNE(object = zf_AR_res01, dims.use = 1:10, do.fast = TRUE, check_duplicates = FALSE)
zf_AR_res02 <- RunTSNE(object = zf_AR_res02, dims.use = 1:10, do.fast = TRUE, check_duplicates = FALSE)
zf_AR_res03 <- RunTSNE(object = zf_AR_res03, dims.use = 1:10, do.fast = TRUE, check_duplicates = FALSE)
zf_AR_res04 <- RunTSNE(object = zf_AR_res04, dims.use = 1:10, do.fast = TRUE, check_duplicates = FALSE)
zf_AR_res05 <- RunTSNE(object = zf_AR_res05, dims.use = 1:10, do.fast = TRUE, check_duplicates = FALSE)

#Produce tSNE Plot
DimPlot(zf_AR_res0)
DimPlot(zf_AR_res01)
DimPlot(zf_AR_res02)
DimPlot(zf_AR_res03)
DimPlot(zf_AR_res04)
DimPlot(zf_AR_res05)

Res0.1
![Resolution0 1](https://user-images.githubusercontent.com/66061442/83124902-19d4a300-a0d7-11ea-84fd-a8b960749cb6.png)

Res0.5
![resolution0 5](https://user-images.githubusercontent.com/66061442/83124923-1fca8400-a0d7-11ea-8610-ccee0b8e87ec.png)

I apologize for my trivial question but hope you can help me. 

Best Regards 
Kristian Andersen

**Comment by nicodemus88** [comment]
Hi @Kedde92 ,
You can just run `clustree` on your Seurat object directly. However, you need to run the clustering in the same Seurat object. 

I see you make a separate object for different clustering resolution, but you don't need to do that. You can run clustering in the same Seurat object and it will be stored in separate columns in the metadata. When plotting, you can access them by specifying which column you want your cluster resolution to be based on using the argument `group.by`.

```
## Clusters cells (I usually run them in increments of 0.2)
zf_AR <- FindNeighbors(zf_AR, dims = 1:10)
zf_AR <- FindClusters(zf_AR, resolution = c(0, 0.2, 0.4, 0.6, 0.8, 1)

## Run UMAP
zf_AR <- RunUMAP(zf_AR, dims = 1:10)

## Plot clusters (2 examples here)
p1 <- DimPlot(zf_AR, group.by = "RNA_snn_res.0.2") + ggtitle("Res 0.2")
p2 <- DimPlot(zf_AR, group.by = "RNA_snn_res.0.6") + ggtitle("Res 0.6")

## Plot clustering tree
clustree(zf_AR)
```
