### ISSUE TITLE
Negative expression in DotPlot

### ISSUE THREAD

**Issue by chjp** [satijalab/seurat#3084]
Hi,

Thank you guys making such a great tool for the single cell community.

After scale.data(), a dot plot would show that some gene have negative average expression in some sample, with examples shown in the figure [Cluster_markers.pdf](https://github.com/satijalab/seurat/files/4697433/Cluster_markers.pdf). Biologically, it is confusing. While a gene shows expression percentage >50% in a cluster, it has average negative value in the cluster. So it would be difficult to decide if that gene is a real marker gene of that cluster or not.

Could you provide some comments?

Thank you so much!

**Comment by timoast** [comment]
DotPlot uses the scaled data (mean 0 sd 1), so the negative values here correspond to clusters with expression below the mean expression across the whole dataset. This helps to visualize lowly expressing clusters and highly expressing clusters on the same scale.
