### ISSUE TITLE
Clustering BBKNN output

### ISSUE THREAD

**Issue by spromanos** [satijalab/seurat#3086]
Hello, 

I was wondering if you can offer a solution for the integration of BBKNN output with the Seurat workflow. BBKNN produces a cell x cell matrix of connectivities, on which one should be able to do clustering. However, currently, FindClusters requires for the matrix to be in S4 Graph format and its name to be present in names(object). 

Thanks!

**Comment by mojaveazure** [comment]
You can convert your matrix of connectivities to a `Graph` object with [`as.Graph`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/as.Graph); then store it in the `Seurat` object with `[[<-`

```R
object[["bbknn"]] <- as.Graph(bbknn_output)
```

Please note, both the row- and column names of your BBKNN output must be the same as the cells present in your `Seurat` object
