### ISSUE TITLE
JackStraw disabled for SCT

### ISSUE THREAD

**Issue by anaccsilva** [satijalab/seurat#3090]
I cannot run JackStraw anymore using SCT. 

I receive the following error:

Error in JackStraw(MSG12, num.replicate = 100) : 
  JackStraw cannot be run on SCTransform-normalized data.
         Please supply a non-SCT assay.

Any ideas?

**Comment by timoast** [comment]
This has been disabled for SCT assays as JackStraw doesn't really make sense for SCTransform-normalized data. See https://github.com/satijalab/seurat/issues/1871 for more information

**Comment by anaccsilva** [comment]
Thanks for the quick response. But in this case, what's the best method to decide the significant PCs? Would the ElbowPlot still be a good option?

**Comment by timoast** [comment]
Yes, you can use the elbow plot
