### ISSUE TITLE
RunTSNE - The following argments are not used: pca, learning rate

### ISSUE THREAD

**Issue by Haitham-Hajjo** [satijalab/seurat#3092]
Hi 
I'm trying to use RunTSNE function in Seurat 3.1.5. 
I'm interested in choosing the specific learning rate and to run the tsne analysis based on pca parameters. 
But I'm getting this warning: 
"RunTSNE - The following argments are not used: pca, learning rate" 
In addition, I'm trying to use the FIT-SNE algorithm (tsne.method = "FIt-SNE") but I'm getting this errot "Error: Could not find the following programs: FItSNE.exe"

Thanks for your help
Haitham

**Comment by timoast** [comment]
Can you provide the code you're running?

**Comment by Haitham-Hajjo** [comment]
This is the code I'm running: 

library(Seurat)
library(dplyr)
library(cowplot)
library(ggplot2)
library(SingleR)
library(scRNAseq)
library(scater)
library(scran)
library(Seurat)
library(dplyr)
library(cowplot)
library(ggplot2)
library(DoubletFinder)
library(sctransform)

SPF <- CreateSeuratObject(counts = SPF.data, project = "SPF", min.cells = 3, min.features = 500)
# Calculate % of mitochondrial genes 
SPF[["percent.mt"]] <- PercentageFeatureSet(SPF, pattern = "^mt-")
SPF <- subset(SPF, subset = nFeature_RNA > 500 & nFeature_RNA < 6000 & percent.mt < 5)
###### 
# Store MT percentage in object meta data 
SPF = PercentageFeatureSet(SPF, pattern = "^MT-", col.name = "percent.mt")
# Normzlize the data 
SPF <- NormalizeData(SPF, scale.factor = 50000)
# Identify Variale genes 
SPF <- FindVariableFeatures(SPF, selection.method = "vst", nfeatures = 2000)

DefaultAssay(SPF) <- "RNA"
all.genes = rownames(SPF)
SPF <- ScaleData(SPF, verbose = FALSE, features = all.genes)
#######
SPF <- RunPCA(SPF, npcs = 100, verbose = FALSE)

##### Run tSNE 
SPF <- RunTSNE(SPF, reduction = "pca", dims = 1:40, perplexity = 46, learning.rate = 388, tsne.method = "FIt-SNE")

**************** 
These are the messages I get: 
Warning: The following arguments are not used: pca, learning.rate
Error: Could not find the following programs: FItSNE.exe

I think the problem is with FItSNE, because when I run the same code but woth Rtsne it works. 

Thanks
Haitham

**Comment by timoast** [comment]
You need to install FItSNE: https://github.com/KlugerLab/FIt-SNE
