### ISSUE TITLE
Merge Question

### ISSUE THREAD

**Issue by vlcm2019** [satijalab/seurat#3094]
Hello,

Could you subset clusters from a Seurat Object and merge the subsetted clusters from two different Seurat objects? Any guidance would be extremely helpful.

I tried the above and I am getting the following error.

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Thank you.

**Comment by vlcm2019** [comment]
Hello Yuhan, Thank you for the response. I have included the scripts that used for merging with and without subsetting.  I only get the error when I merge after subsetting. I am not sure if I am doing something wrong. Thank you for your help.

**#with subsetting**
>load("~/sample1_final.Robj")

>sample1 <- subset(sample1, idents = c(0, 2, 8))
 
> load("~/sample2_final.Robj")

>sample2 <- subset(sample2, idents = c(0, 1, 3, 6))

> sample_merge <- merge(x = sample1, y = sample2, add.cell.ids = c("14-1236", "11-3345"), merge.data = TRUE)
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**#without subsetting**

> load("~/sample1_final.Robj")
> 
> load("~/sample2_final.Robj")
> 
> sample_merge <- merge(x = sample1, y = sample2, add.cell.ids = c("14-1236", "11-3345"), merge.data = TRUE)
> sample_merge
An object of class Seurat 
42926 features across 16059 samples within 2 assays 
Active assay: SCT (20564 features, 0 variable features)
 1 other assay present: RNA

**Comment by aubreyghoward** [comment]
#2831

**Comment by timoast** [comment]
I believe this is fixed as of d42126de4348f21d7bdad19fa08f5b47ced22bed. If not, please reopen.
