### ISSUE TITLE
SCTransform vs standard workflow with CCA normalization which one works well for lncRNA?

### ISSUE THREAD

**Issue by biobug16** [satijalab/seurat#3095]
Hi All,
I am trying to analyze lncRNAs from 10x data using Seurat and have tried SCTransform and standard workflow using CCA normalization both. The two methods give distinct clustering for lncRNAs, creating confusion for selecting the best one to pursue further. 
Does the performance of these method can be affected by less the number of cells capturing these lncRNA compared to mRNAs?
Any of you have related experience? I am looking forward to your suggestions.

Thanks

**Comment by satijalab** [comment]
The methods are slightly different, and so there will be some changes to the downstream clustering - but there is no reason (to our knowledge) to specifically choose one over the other in the context of lncRNA analysis.
