### ISSUE TITLE
Issue: how to add new cell ids to a particular subset of the orignal Seurat object after reclustering?

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#3096]
Hi all, 
I have a big Seurat object that represents the merge of two samples (object= Merged.big). 
At some point, I needed to subset cells of a particular cluster from the Merged.big object for further analysis (shown below).

`#subset cluster NPC (NPC1 = yn1)
NPC1 <-subset(Merged.big, ident="NPC-1", subset = geneA > 0 & geneB> 0)`

`table(NPC1$orig.ident)`

`#Create subsets of just YN1 cells
NPC1 <- SetIdent(NPC1, value = "orig.ident")`

`NPC1yn1 <- subset(NPC1, idents = 'yn1')`

`NPC1_cells <- WhichCells(NPC1yn1)`

` #check numbers for newest subset
table(NPC1yn1$orig.ident)`

#regular workflow
`NPC1yn1 <- NormalizeData(object = NPC1yn1)`
`NPC1yn1 <- ScaleData(object = NPC1yn1, features = all.genes)`
`NPC1yn1 <- FindVariableFeatures(NPC1yn1, selection.method = "vst", nfeatures = 4000)`
`NPC1yn1`
`table(NPC1yn1$orig.ident)`
`
After, PCA and re-clustering, I ended up with 4 clusters ("0", "1", "2", "3"), that I have renamed the clusters to ("NPCd",  "NPCa", "NPCb",  "NPCc"), shown below.

`NPC1yn1 <- RunPCA(NPC1yn1, features = VariableFeatures(object = NPC1yn1))`
`NPC1yn1 <- FindNeighbors(NPC1yn1, dims = 1:10)`
`NPC1yn1 <- FindClusters(NPC1yn1, resolution = 0.5)`
`NPC1yn1[["my.clustersNPC1yn1"]] <- Idents(object =NPC1yn1)`
 
#adding new cluster id
`NPC1yn1.cluster.ids <- c("NPCd", 
                     "NPCa",
                     "NPCb",
                     "NPCc")`
                 
`names(NPC1yn1.cluster.ids) <- levels(NPC1yn1)`
`NPC1yn1 <- RenameIdents(NPC1yn1, NPC1yn1.cluster.ids)`

Now, the problem is that have named the cluster, but not the cells in that particular cluster. 
Thus, when I export a TSV file, the columns (cells ids) have their original named (e.g.:
[1] "yn1_AAACCCAAGCTTGTGT" "yn1_AAACGCTAGCGACATG" "yn1_AAAGAACAGACTAAGT" "yn1_AAAGGGCTCATCGACA" "yn1_AAAGGGCTCGCTGTTC" "yn1_AAAGTCCAGAGAGCGG")

Is that a way to identify the cells by their new id? I mean, the cluster they belong to (for instance [1] "NPCa_AAACCCAAGCTTGTGT" "NPCb_AAACGCTAGCGACATG" "NPCa_AAAGAACAGACTAAGT" "NPCd_AAAGGGCTCATCGACA" so on)

I have tried to use `renameCells` but I have not been successful. 

In advance, I thank you very much for your time and  help. 
and thank you @satijalab for this great tool.

**Comment by timoast** [comment]
You can access the metadata for the object using the `[[` accessor, eg ``metadata <- object[[]]``. This is a dataframe that you can then save to a file using standard functions in R, and the row names are the cell names and columns are the metadata for each cell (eg, cluster or cell type labels)

**Comment by giovanegt** [comment]
thanks you very much
