### ISSUE TITLE
integration error

### ISSUE THREAD

**Issue by rosm101** [satijalab/seurat#3097]
Hi,

Sorry if this is a bit of a silly question, I've been following the vignettes for this but I'm getting an error come up with the FindIntegrationAnchors function and I'm not quite sure why. It might be I'm completely off with my thinking, but I merged my Seurat objects together (there's 12 in total) before suing the split function while normalising and finding variable features. After that when I use that list to find integration anchors it doesn't like the list I've created from the merged object for this. Am I inputting the wrong thing into the FindIntegrationFeatures function? 

I have put them into that as a list, which has worked but I didn't think ideal.

Kind regards,
Ross

> covid19.scRNA <- merge(x=HC100, y=list(HC51, HC52, M141, M142, M144, S143, S145, S146, S148, S149, S152), add.cell.ids = c("HC100", "HC51", "HC52", "M141", "M142", "M144", "S143", "S145", "S146", "S148", "S149", "S152"), project = "covid19_scRNA")

> covid.list <- SplitObject(object = covid19.scRNA, split.by = "ident")
> for (i in 1:length (x=covid.list)){
+     covid.list[[i]] <-NormalizeData(object = covid.list[[i]])
+     covid.list[[i]] <-FindVariableFeatures(object = covid.list[[i]], selection.method = "vst", nfeatures= 2000)
+ }

> immune.anchors <-FindIntegrationAnchors(object.list = covid.list, dims = 1:20)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Error in which(x = object.classes, useNames = TRUE) : 
  argument to 'which' is not logical

**Comment by timoast** [comment]
I'm not entirely sure what the issue is here, but it may have something to do with the merge/split step that you include (maybe because you split by "ident", and it's not clear what that is from the code).

There's no need to do this, you just need a list of objects and you have them as separate objects already. You could try for example:

```r
covid.list<- list(HC100, HC51, HC52, M141, M142, M144, S143, S145, S146, S148, S149, S152)

for (i in 1:length (x=covid.list)){
  covid.list[[i]] <-NormalizeData(object = covid.list[[i]])
  covid.list[[i]] <-FindVariableFeatures(object = covid.list[[i]], selection.method = "vst", nfeatures= 2000)
}

immune.anchors <-FindIntegrationAnchors(object.list = covid.list, dims = 1:20)
```

**Comment by rosm101** [comment]
Hi,

Thanks, I'll give this a try. I've had to put it on the back burner cause I've run into memory issues with my available computer, but I'll try this cause it will be useful in the future, thanks!

Kind regards,
Ross
________________________________
