### ISSUE TITLE
How to change the axis between x and y?

### ISSUE THREAD

**Issue by adistman** [satijalab/seurat#3098]
As I use the Seurat to analyse Scq-data， when I get the violin plot，I found that The X represents the "Identity"and the Y represents the "Expression Level", but I wan'na to change them with each other. So I adds the "+coord_flip()" following the "vlnplot" commond, and I find that only the last one figure changed X AND Y axis.  So will kindly enough to tell me how to change all of the violin plot Using commond? Thanks a lot!

**Comment by nicodemus88** [comment]
@adistman Use `&` instead of `+`. It will apply to all plots.

**Comment by adistman** [comment]
> @adistman Use `&` instead of `+`. It will apply to all plots.

Thank you very much , It worked perfectly!
