### ISSUE TITLE
How to handle more than 1 million of cells

### ISSUE THREAD

**Issue by EmanuelaUnimi** [satijalab/seurat#3099]
Hello everyone!
I have 
- a dgC Matrix, which contains gene counts for 1 331 984 cells, 
- a cell_annotate dataframe with cell ID on rownames and several features on columns (such as: embryo stage, embryo sex, etc)
- a gene_annotate dataframe with gene ID on rownames (such as ENSMUSG00000051951.5) and the respective common names in a column (for example, Xkr4 is the respective name of the previous)

Now, I would like to know how can I handle a so huge dgC matrix. My goal is to create a Seurat object with all the cells and then do downstream analysis. Is it better I subset the matrix? If yes, How?
I would also like to change names with the common ones. How can I do?

**Comment by zhiiiyang** [comment]
@EmanuelaUnimi, did you figure out how to work with 1 million cells by now? Just curious.

**Comment by saulvegasauceda** [comment]
Any updates?
