### ISSUE TITLE
PCASigGenes crashes if PCA count is higher than the number available

### ISSUE THREAD

**Issue by maximilianh** [satijalab/seurat#31]
When this happens:

    1: In JackStraw(nbt, num.replicate = 100, do.print = FALSE) 
    Number of PCs specified is greater than PCs available. Setting num.pc to 4 and continuing.

then this will crash (taken straight from the tutorial:

nbt.sig.genes=PCASigGenes(nbt,1:9,pval.cut = 1e-5,max.per.pc = 200)
    Error in `[.data.frame`(pvals.use, , pcs.use) : 
    undefined columns selected
    Calls: PCASigGenes -> PCASigGenes -> apply -> [ -> [.data.frame
    Execution halted

Can I find out how many PCs are actually available?

thanks!

**Comment by andrewwbutler** [comment]
You can look at the number of columns in the rotation matrix. 

`ncol(nbt@pca.rotation)`

Based on the JackStraw error message, it looks like you have 4 PCs.

**Comment by maximilianh** [comment]
Thanks! 

suggestion: when people run your tutorial with a different input matrix, it will fail at this step, because there are not enough PCs. The error message though doesn't make this clear at all. You could catch this error and print something or take the minimum of the current PC count and the supplied number of PCs instead of taking the supplied number of PCs at face value.

**Comment by andrewwbutler** [comment]
Yep, definitely a good idea. We will add this in a future update (or feel free to submit a pull request). 

Also, it looks like you're still using the old tutorial. Check out the website for a newer version (http://satijalab.org/seurat/pbmc-tutorial.html)
