### ISSUE TITLE
exporting subsets with metadata and top10 gene expression information

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#310]
Dear Seurat people, 
is there an easy way to export a cell subset with the metadata information for each cell, as well as keeping a selection of genes, as for example the top10 differentially expressed genes specifying the subset? 

Thansks a lot for your help! 
annecar

**Comment by satijalab** [comment]
Sorry for the slow reply, we actually have a slot (object@misc) that you can store anything. I've found this to be very useful for storing gene lists, exactly as you suggest.
