### ISSUE TITLE
Batch PercentageFeatureSet

### ISSUE THREAD

**Issue by SebRW** [satijalab/seurat#3100]
I have many seurat objects created from count matrixes downloaded from GEO.
I want to use the PercentageFeatureSet() function on each of them to calculate the %MT.

I tried : 
```
for (i in seu.list) {
  get(i)[["percent.mt"]] <- PercentageFeatureSet(get(i), pattern = "^MT-") 

```
but got the following error: 
Error in get(i) <- `*vtmp*` : could not find function "get<-"

How can I use PercentageFeatureSet() in loop?

**Comment by timoast** [comment]
```r
for (i in seu.list) {
  i[["percent.mt"]] <- PercentageFeatureSet(i, pattern = "^MT-")
}
```
