### ISSUE TITLE
Generic Error with Dims: Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : invalid character indexing

### ISSUE THREAD

**Issue by oh111** [satijalab/seurat#3101]
Hi there, 
I have a large Seurat Object which has been normalized and scaled. 
I am trying to use 'FindNeighbors' using the feature option. From my understanding, dims then has to be NULL. 
Each time, I get the following error: 
`Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : invalid character indexing`
This seems to be the case for any function that I don't want to use dims and instead want to use Features. 
The feature I want ("Subtype") is in the meta.data of the seurat object and present for every datapoint. 
Code: 
`Compiled.SOBJ<-FindNeighbors(Compiled.SOBJ, dims=NULL, features="Subtype")`

**Comment by satijalab** [comment]
We only support finding neighbors on molecular data (for example, gene expression in the RNA assay). We don't support finding neighbors on the basis of a metadata column.
