### ISSUE TITLE
doubts UMAP and FindNeighbors/FindClusters

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#3102]
Hi, I'm new on this kind of analysis so I have difficulties to understand what exactly this steps are doing. 
I've realized that in the [clustering tutorial](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html) you perform first the clustering and then de UMAP, but in the [integrating datasets tutorial](https://satijalab.org/seurat/v3.1/immune_alignment.html) you do it the other way around; first the UMAP and then the clustering. I though that the UMAP needed the clustering in order to do the representation? If not, what is the difference between this two steps?

Thank you in advance, 
Marta.

**Comment by samuel-marsh** [comment]
Hi Marta,

No the UMAP (or tSNE) don't need the clustering to create the dimensionality reduction visualization.  You can visualize this yourself in that as you change say the resolution parameter of FindClusters() you don't actually change the UMAP or tSNE but simply impact the clusters.  Also see: #2152 and I would also suggest https://osca.bioconductor.org/ which includes some more details in definition of various steps that are performed during single cell analyses and their uses.

Best,
Sam
