### ISSUE TITLE
Genes filtering prior to Normalization

### ISSUE THREAD

**Issue by galozs** [satijalab/seurat#3104]
Hi
I was wondering about why the gene filtering is done prior to the normalization of the Seurat obj.
If the normalization step is there for normalizing expression levels of the genes to the total expression in the cell, then I would think that removing genes prior to this step might affect the gene expression of the few cells that did expressed it. What am I missing?
Thanks!
Shani

**Comment by samuel-marsh** [comment]
Hi Shani,

What are you referring to when you say gene filtering?

Thanks,
Sam

**Comment by satijalab** [comment]
Thanks for the question. Yes, removing those genes may have a (miniscule) effect on the normalization. In the past, we've found that while the effect of removing these genes was very small, it was typically positive and helped to downweight the effect of outliers, but if you have any concerns you can set min.cells to 0.
