### ISSUE TITLE
how to get RNA/ATAC cell pairs

### ISSUE THREAD

**Issue by wangmhan** [satijalab/seurat#3105]
Hi, I tried to integrate scRNA and scATAC-seq data together. 
Would like to get not only the reliable anchor pairs but all anchor pairs.

the matrix I would like to have is:
 assay1 assay2 
 rna_cell1 atac_cell6
.....
rna_cellN atac_cellM
Could also be great if has an extra column gives scores to measure the reliability.

I have a look at some similar issues, but didn't find a clear instruction.
https://github.com/satijalab/seurat/issues/2220

Is it manageable? Thanks a lot!

**Comment by wangmhan** [comment]
Thanks for the reply.
I know the results are stored in @anchors, but it is after filtering.
what if I want to get all cell pairs?

**Comment by timoast** [comment]
If you want all cell pairs, you should turn off filtering in the anchor finding step by setting `k.filter=NA`

**Comment by wangmhan** [comment]
Thanks, it works.
