### ISSUE TITLE
Randomly downsample seurat object

### ISSUE THREAD

**Issue by williamsdrake** [satijalab/seurat#3108]
Hi Seurat Team,

Thanks for the wonderful package. I have two seurat objects, one with about 40k cells and another with around 20k cells. I would like to randomly downsample the larger object to have the same number of cells as the smaller object, however I am getting an error when trying to subset. I followed the example in [#243](https://github.com/satijalab/seurat/issues/243), however this issue used a previous version of Seurat and the code didn't work as-is. Here is the slightly modified code I tried with the error: 

```
# Object HV is the Seurat object having the highest number of cells
# Object PD is the second Seurat object with the lowest number of cells
# Compute the length of cells from PD
cells.to.sample <- length(PD@active.ident)

# Sample from HV as many cells as there are cells in PD
# For reproducibility, set a random seed
set.seed(12)
sampled.cells <- sample(x = HV@active.ident, size = cells.to.sample, replace = F)

# Subset Seurat object
HV.sub <- subset(x=HV, cells = sampled.cells)

```
The error after the last line is: 
**Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided**

Seurat version 3.1.4

Any help or guidance would be appreciated. Thank you

**Comment by timoast** [comment]
You should be able to run:

```r
downsampled.obj <- large.obj[, sample(colnames(large.obj, size = ncol(small.obj), replace=F))]
```

**Comment by williamsdrake** [comment]
Thank you Tim. If anybody happens upon this in the future, there was a missing ')' in the above code. This is what worked for me: 

`downsampled.obj <- large.obj[, sample(colnames(large.obj), size = ncol(small.obj), replace=F))]`

**Comment by kmshort** [comment]
> Thank you Tim. If anybody happens upon this in the future, there was a missing ')' in the above code. This is what worked for me:
> 
> `downsampled.obj <- large.obj[, sample(colnames(large.obj), size = ncol(small.obj), replace=F))]`

They actually both fail due to syntax errors, yours included @williamsdrake .
For the new folks out there used to Satija lab vignettes,  I'll just call large.obj pbmc, and downsampled.obj, pbmc.downsampled, and replace size determined by the number of columns in another object with an integer, 2999:

`pbmc.subsampled <- pbmc[, sample(colnames(pbmc), size =2999, replace=F)]`

I hope this helps someone.

**Comment by EdoPredi** [comment]
Hi everyone.

Just a quick question

> > Thank you Tim. If anybody happens upon this in the future, there was a missing ')' in the above code. This is what worked for me:
> > `downsampled.obj <- large.obj[, sample(colnames(large.obj), size = ncol(small.obj), replace=F))]`
> 
> They actually both fail due to syntax errors, yours included @williamsdrake .
> For the new folks out there used to Satija lab vignettes, I'll just call large.obj pbmc, and downsampled.obj, pbmc.downsampled, and replace size determined by the number of columns in another object with an integer, 2999:
> 
> `pbmc.subsampled <- pbmc[, sample(colnames(pbmc), size =2999, replace=F)]`
> 
> I hope this helps someone.

Hy Km Short...

I was trying to do the same and is used your code. The number of column it is reduced ( so the object). My question is... Is this randomized ? which command here is leading to randomization ? I managed to reduce the vignette pbmc from the from 2700 to 600. I ma just worried it is just picking the first 600 and not randomizing

**Comment by kmshort** [comment]
> Hy Km Short...
> 
> I was trying to do the same and is used your code. The number of column it is reduced ( so the object). My question is... Is this randomized ? which command here is leading to randomization ? I managed to reduce the vignette pbmc from the from 2700 to 600. I ma just worried it is just picking the first 600 and not randomizing

https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/sample
