### ISSUE TITLE
error when running MAST 

### ISSUE THREAD

**Issue by antomonta** [satijalab/seurat#3109]
Hi team,

I've been trying to use MAST using the following code `FindMarkers(obj, ident.1 = "2_1", ident.2 = "2_3", verbose = T, test.use = "MAST") `and got the following error: "Error in sanity_check_sca(obj) : 
  Assay in position 1, with name et is unlogged. Set `check_sanity = FALSE` to override and then proceed with caution."

I set the DefaultAssay to "RNA" as suggested in previous posts, but that didn't help. That code works of other similarly integrated objects when not indicating "ident.1" and "indent.2".

Thank you very much!

**Comment by satijalab** [comment]
We're taking a look into this (@k3yavi) - but can you confirm if this happens in any dataset analysis (ie. with pbmc3k) or if its specific to your dataset? Thanks!

**Comment by antomonta** [comment]
> We're taking a look into this (@k3yavi) - but can you confirm if this happens in any dataset analysis (ie. with pbmc3k) or if its specific to your dataset? Thanks!

Hi, I tried it on a different dataset and it worked both when running on the entire datasets and when indicating specific identities. It seems it was related to that one dataset. Do you know what the problem with that dataset could be?

Thank you very much for your help!

P.S. I forgot to set the DefaultAssay to RNA and MAST worked anyway on the integrated assay.

**Comment by k3yavi** [comment]
Hi @antomonta ,

Thanks for checking with the different dataset and we're glad to hear that it worked Ok.

Regarding the specific dataset you are working on, it's hard to say, if it's possible for you to share the object we can take a look ?

Email: seuratpackage@gmail.com
PS: Please let me know the subject of the email once you send the email.

**Comment by antomonta** [comment]
Hi Avi,

I sent the object in an email with the subject "GitHub MAST error Avi".

Thank you for your help.

Best,
Antonino Montalbano, PhD
Genomics Technologies, Lead
www.immunai.com

**Comment by k3yavi** [comment]
Hi @antomonta ,

Thanks for forwarding the data. Unfortunately, I can't replicate the error at my end using your data. The command I used & the logs I get are the following:

```
obj <- readRDS("~/github_MASTerror.rds")
obj

levels(obj)
markers <- FindMarkers(obj, ident.1 = "0", ident.2 = "1", verbose = T, test.use = "MAST")
```

```
> obj <- readRDS("~/github_MASTerror.rds")
> obj
An object of class Seurat 
29972 features across 9323 samples within 4 assays 
Active assay: integrated (1974 features, 1974 variable features)
 3 other assays present: RNA, CITE, SCT
 3 dimensional reductions calculated: pca, umap, tsne

> levels(obj)
[1] "0" "1" "2" "3" "4" "5" "6" "7" "8"

> markers <- FindMarkers(obj, ident.1 = "0", ident.2 = "1", verbose = T, test.use = "MAST")
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                              
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Refitting on reduced model...
                                                                                                                              
Done!
```

Also, I am not sure what's `2_1` and `2_3` in your command, may I ask which identity you used ?
Another thing to check would be are you using the latest version of the both Seurat and MAST ?

**Comment by antomonta** [comment]
Hi Avi,

That's great! I'm going to try again then.

I will update Seurat and MAST to the latest version.

"2_1" and "2_3" are clusters 2 sample 1 and 3, respectively. I tried to
identify differentially expressed genes between those two samples
specifically in that cluster of barcodes. To get those, I first subset for
cells from samples 1 and 3, create a new column where the cell type is
specified by cluster and sample name and run MAST for cluster 2.

Thank you again!

Best regards,


Antonino Montalbano, PhD
Genomics Technologies, Lead
www.immunai.com
