### ISSUE TITLE
MergeSeurat vs. RunCCA

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#311]
Dear all,

maybe it is a simple question but I have the impression that RunCCA and MergeSeurat do both merge 2 Seurat objects. I would like to combine >2 objects into one. Which method should I use? Is there any difference at all?

Thanks, Chris

**Comment by leonfodoulian** [comment]
Hi Chris,

You can check the documentations of the functions for more details, but both do very different jobs. `MergeSeurat()` simply merges two Seurat objects, yet this function can be used iteratively to merge multiple objects (more info by running `?Seurat::MergeSeurat` in R). 

On the other hand, RunCCA() and its implementation for multiple data sets, `RunMultiCCA()`, are alignment functions that will merge and remove batch effects from the datasets you would like to combine, hence allowing the identification of common clusters (and not dataset specific clusters). More details on how these functions work, as well as tutorials, can be found [here](http://satijalab.org/seurat/immune_alignment.html). You can also read the [preprint of the paper](https://www.biorxiv.org/content/early/2017/07/18/164889) where the method is described.

What to use will depend on what you want to do. If you have no batch effects (plotting the first 2 PCs, and colouring your cells by dataset will immediately reveal whether you have or not batch effects), there is no need to go through the CCA workflow. But if your aim is to combine and cluster datasets that were generated on multiple days, and sequenced on multiple lanes, then using `RunMultiCCA()` is a good idea.

Hope this helped!

Best,
Leon

**Comment by balthasar0810** [comment]
Thanks, Leon, for your kind reply. It has been good advice. I want to combine different treatments on the same tissue. I cannot completely rule out batch effects but will do pca. However, if I have say stimulated and not stimulated. Pca might show this. Can I still do Cca in such a case, e. g. align two different treatments with Cca or does this destroy internal structures and differences in gene expression? Thanks again, best, Christian

Envoyé de mon iPhone

Le 17 févr. 2018 à 09:42, Leon Fodoulian <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Chris,

You can check the documentations of the functions for more details, but both do very different jobs. MergeSeurat() simply merges two Seurat objects, yet this function can be used iteratively to merge multiple objects (more info by running ?Seurat::MergeSeurat in R).

On the other hand, RunCCA() and its implementation for multiple data sets, RunMultiCCA(), are alignment functions that will merge and remove batch effects from the datasets you would like to combine, hence allowing the identification of common clusters (and not dataset specific clusters). More details on how these functions work, as well as tutorials, can be found here<http://satijalab.org/seurat/immune_alignment.html>. You can also read the preprint of the paper<https://www.biorxiv.org/content/early/2017/07/18/164889> where the method is described.

What to use will depend on what you want to do. If you have no batch effects (plotting the first 2 PCs, and colouring your cells by dataset will immediately reveal whether you have or not batch effects), there is no need to go through the CCA workflow. But if your aim is to combine and cluster datasets that were generated on multiple days, and sequenced on multiple lanes, then using RunMultiCCA() is a good idea.

Hope this helped!

Best,
Leon

**Comment by leonfodoulian** [comment]
Hi again,

CCA does not change gene expression levels, nor does it return a matrix of batch corrected expression levels. Please check Rahul's answer in [issue #283](https://github.com/satijalab/seurat/issues/311#issuecomment-366430121). In your case, it is maybe a good idea to use CCA to identify common cell types between the stimulated and unstimulated cells, and maybe compare gene expression levels between both pools of cells within a given cell type. The paper I referenced in my earlier answer cover multiple cases where CCA can be used. You can also have a look at Andrew's slides that you can find in the following [web page](http://satijalab.org/scgd/), where you can also find a handful of interesting papers regarding batch correction and dataset alignment.

Best,
Leon

**Comment by balthasar0810** [comment]
Thanks again, Leon. This was very helpful.

Envoyé de mon iPhone

Le 17 févr. 2018 à 11:17, Leon Fodoulian <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi again,

CCA does not change gene expression levels, nor does it return a matrix of batch corrected expression levels. Please check Rahul's answer in issue #283<https://github.com/satijalab/seurat/issues/311#issuecomment-366430121>. In your case, it is maybe a good idea to use CCA to identify common cell types between the stimulated and unstimulated cells, and maybe compare gene expression levels between both pools of cells within a given cell type. The paper I referenced in my earlier answer cover multiple cases where CCA can be used. You can also have a look at Andrew's slides that you can find in the following web page<http://satijalab.org/scgd/>, where you can also find a handful of interesting papers regarding batch correction and dataset alignment.

Best,
Leon
