### ISSUE TITLE
Identifying differential expressed genes across conditions

### ISSUE THREAD

**Issue by NaomiCroft** [satijalab/seurat#3111]
Hello,
I am following the https://satijalab.org/seurat/v3.1/immune_alignment.html vignette. 

The most differentially expressed genes as seen on the comparative analysis plots with two treatment groups compared are not found by the command to print the most differential genes. Here is my script:

```
#Find all markers distinguishing a cluster in one treatment from the same cluster in diff treatment
fish.integrated$celltype.treatment <- paste(Idents(fish.integrated), fish.integrated$treatment, sep = "_")
fish.integrated$celltype <- Idents(fish.integrated)
Idents(fish.integrated) <- "celltype.treatment"
plasma.cell.response <- FindMarkers(fish.integrated, ident.1 = "14. Plasma cells_PreImm", ident.2 = "14. Plasma cells_VacD1", verbose = FALSE)
head(plasma.cell.response, n = 10)
```
cannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with tiescannot compute exact p-value with ties                    p_val  avg_logFC pct.1 pct.2   p_val_adj
LOC115538251 1.485693e-06 -0.3146607 1.000 0.806 0.002971386
LOC115560936 4.393599e-06 -0.3406264 0.895 0.111 0.008787199
LOC115558504 4.745610e-06 -0.7273937 0.895 0.139 0.009491220
nom1         5.582294e-06 -0.8442664 1.000 0.444 0.011164588
LOC115558271 9.255133e-06 -0.2728304 0.789 0.278 0.018510266
LOC115548546 9.742612e-06 -0.3540861 0.579 0.056 0.019485224
LOC115554019 1.145986e-05 -0.6043822 0.632 0.111 0.022919713
LOC115553373 1.266264e-05  0.4397637 0.842 0.306 0.025325272
knop1        1.542726e-05 -0.5600044 0.684 0.111 0.030854513
LOC115557162 1.837397e-05 -0.3597365 0.526 0.028 0.036747932

`Plasma.cells <- subset(fish.integrated, idents = "14. Plasma cells")
Idents(Plasma.cells) <- c("PreImm", "VacD1")
avg.Plasma.cells <- log1p(AverageExpression(Plasma.cells, verbose = FALSE)$RNA)
avg.Plasma.cells$gene <- rownames(avg.Plasma.cells)

genes.to.label = c("LOC115538251", "LOC115560936", "LOC115558504", "nom1", "LOC115558271", "LOC115548546", "LOC115554019", "LOC115553373", "LOC115553373", "knop1")
p9 <- ggplot(avg.Plasma.cells, aes(PreImm, VacD1)) + geom_point() + ggtitle("14. Plasma cells")
p9 <- LabelPoints(plot = p9, points = genes.to.label, repel = TRUE)
p9`

![image](https://user-images.githubusercontent.com/48726315/83852512-30e94580-a714-11ea-9fc3-8bbc42afc6fb.png)

Any suggestions?

Thanks for you time,
Naomi

**Comment by satijalab** [comment]
What is most likely happening is that the gene may be expressed in a small number of cells, or have outlier expression in just a few cells. This can cause it to appear to have a high expression in the 'pseudobulk', but will not return a statistically significant result when using FindMarkers. We would suggest trusting the Findmarkers output when there are discrepancies like this, but you can explore the individual genes in more detail to see what is going on. For example, please feel free to examine one of the genes that concerns you and to post a violin plot comparing the expression of any gene across conditions
