### ISSUE TITLE
question about PeakSeuratFromTransfer

### ISSUE THREAD

**Issue by angel-bee2018** [satijalab/seurat#3112]
Hi! I am attempting to calculate Differential Transcript Usage using a peak-level Seurat object made using PeakSeuratFromTransfer. I would like to know whether the peak counts contained in the peak-level object are normalised by the parent gene's expression levels during execution of PeakSeuratFromTransfer?

If not, how could I go about normalising each peak-level count by its parent gene expression?

Thanks! :)
Angel

**Comment by timoast** [comment]
What's PeakSeuratFromTransfer?

**Comment by angel-bee2018** [comment]
oh im so sorry i didn't realise it didn't belong to the Seurat package. closing now.
