### ISSUE TITLE
Cluster with a subset of samples and project another sample on the integrated model

### ISSUE THREAD

**Issue by mamtagiri** [satijalab/seurat#3113]
HI Guys,

One of my 9 samples seems like a bit of an outlier. So I am planning on clustering with 8 samples first. Is there a way to add this 9th sample back into the integrated model or project it on the model (without using its cell in the clustering but to just classify)

Let me know what you guys think or if any other suggestions

Thanks,
Mamta

**Comment by satijalab** [comment]
Its a biological decision that we leave up to the user -whether to integrate all datasets, or to transfer labels from a reference. If you use the latter, you can use our label transfer approach (FindTransferAnchors) to project the reference labels onto the query

**Comment by mamtagiri** [comment]
Hi,

When I see a good match between the 2 sets (as per cell types from TransferLabels), is there a way I can integrate those 2 to analyze them together (so they have normalized expression value comparable)?

Thanks,
mamta
