### ISSUE TITLE
Downsampling from each cluster

### ISSUE THREAD

**Issue by pankoj-das** [satijalab/seurat#3116]
Hi!
I'm trying to make a heatmap from my combined (ctrl+tretmt) data. I found 10 clusters with diffrent cell numbers. Now I want to subsample to make a uniform heatmap. How can I subsample to have same cell number for each cluster?

**Comment by nicodemus88** [comment]
@pankoj-das , it's in this vignette.
https://satijalab.org/seurat/v3.0/multimodal_vignette.html

Basically, the command is:
`cbmc.small <- subset(cbmc, downsample = 300)`

**Comment by raman91** [comment]
Hi, can i downsample proportion of cells (for example : 10% of cells in each cluster) instead of a fixed number of cells in each cluster. Thank you
