### ISSUE TITLE
DoHeatmap on slot metadata

### ISSUE THREAD

**Issue by jmzvillarreal** [satijalab/seurat#3118]
Hi all,
I was wondring if we can use somehow information stored in metadata to input it to the DoHeatmap function... It seems to only work with data, raw,data or sacle data.
Thanks in advance !
Best,
Jaime.

**Comment by andrewwbutler** [comment]
Hi Jaime,

This is not currently possible to do directly. A potential work-around would be to create a new `Assay` with the relevant meta.data information stored in one of the `Assay` data slots and then call `DoHeatmap` on that new `Assay`.
