### ISSUE TITLE
Cannot convert SingleCellExperiment to Seurat v3 object

### ISSUE THREAD

**Issue by paraish** [satijalab/seurat#3119]
Hi all,  new to single cell analysis so please forgive me if important information is missing. I'm trying to switch to using a clustering-based normalization method using Scran and Scater, which seems to be going fine. I end up with the following SingleCellObject "sce":
`class: SingleCellExperiment 
dim: 16576 2396 
metadata(0):
assays(3): counts normcounts logcounts
rownames(16576): AL627309.1 AP006222.2 ... PNRC2 SRSF10
rowData names(1): label
colnames(2396): AAACCTGAGACCCACC-1 AAACCTGAGACTACAA-1 ... TTTGTCACATCGACGC-1
  TTTGTCAGTTATTCTC-1
colData names(11): label sum ... subsets_Mt_percent total
reducedDimNames(0):
spikeNames(0):
altExpNames(0):`
Note that the "logcounts" was created manually using "log1p" to ensure that the natural log was used, which is what Seurat prefers (as I understand it).

However, when I try to convert this object into Seurat, I get the following error:
`> seurat = as.Seurat(sce)`
`Warning: Non-unique features (rownames) present in the input matrix, making unique`
`Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')`
`Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')`
`Error: Attempting to add a different number of cells and/or features`

I've tried manually importing the normalized counts into Seurat using CreateSeuratObject and seurat@data, but get the following error:

`> Seurat= CreateSeuratObject(counts = assay(sce, "counts"))`
`Warning: Non-unique features (rownames) present in the input matrix, making unique`
`Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')`
`> Seurat@data = assay(sce, "logcounts")`
`Error in (function (cl, name, valueClass)  : `
`  ‘data’ is not a slot in class “Seurat”`

I'm probably making a very silly mistake somewhere, but it's incredibly frustrating! Any help would be greatly appreciated!

**Comment by andrewwbutler** [comment]
Hi, 

The first error suggests that the "counts" and "logcounts" assays in the SingleCellExperiment object have different dimensions. Could you verify that those are the same? If that's not the problem and you're able to provide the object or subsampled version that reproduces the problem (either link here or email to abutler@nygenome.org), I can look into it further. 

For the manual import, you should try 

```R
 CreateSeuratObject(counts = assay(sce, "counts"), data = assay(sce, "logcounts"))
```

Generally, we don't recommend access the slots directly with `@`.In this case either directly provide the data to `CreateSeuratObject` or you could also use `SetAssayData` to set the data slot after creating the Seurat object.
