### ISSUE TITLE
 unable to load shared object '/storage/home/e/esb5324/R/x86_64-redhat-linux-gnu-library/3.5/png/libs/png.so'

### ISSUE THREAD

**Issue by esb5324** [satijalab/seurat#3120]
Hello,
I'm having some issues downloading Seurat. I used the command install.packages("Seurat") and got the following errors:
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/storage/home/e/esb5324/R/x86_64-redhat-linux-gnu-library/3.5/png/libs/png.so':
  libpng16.so.16: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package 'Seurat'
* removing '/storage/home/e/esb5324/R/x86_64-redhat-linux-gnu-library/3.5/Seurat'
Thanks in advance for your help!

**Comment by mojaveazure** [comment]
This is an issue with your installation of the [png](https://cran.r-project.org/web/packages/png/) package. I would suggest removing and reinstalling it before trying to install Seurat. If png is still broken after that, please contact the authors of that package for help.
