### ISSUE TITLE
ggplot themes apply to the last graph only in a series.

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#3123]
Hi all,
I am plotting several violin plots from a merged Seurat object (2 Seurat objects originally that were merged), and I noticed that after upgrade R to Version 1.2.5019  and Seurat to 3.1.5 the ggplot2 themes function apply only for the  last graph in a series of graphs. 

here is the code"
`VlnPlot(Merged.big, features = c("Sall1", "Rspo1","Cited1", "Six2", "Bmp7", "Eya1", "Crym", "Meox1", "Pax2"), pt.size = 0, split.by = "orig.ident") +
   theme(text = element_text(size = 50, face = "bold"))+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  theme(axis.title = element_text(size=25,face="bold")) +
    theme(axis.text.x = element_text(size=25, color="black")) +
    theme(axis.text.y = element_text(size=25, color="black")) +
    theme(legend.text=element_text(size=40, color="black")) +
    theme(legend.title=element_text(size=25, color="black")) +
    theme(axis.line.x = element_line(size=1.5, color="black")) +
    theme(axis.line.y = element_line(size=1.5, color="black"))`

here is the resulting plot.

![image](https://user-images.githubusercontent.com/58445209/84204311-928d1500-aa70-11ea-9473-1952c56f68ef.png)

Themes applied to the last graph only (Pax2). Does anyone have any idea why this is happening and how to fix? 

I do appreciate any help.

**Comment by chlee-tabin** [comment]
Instead of `+ theme(axis.line.y = element_line(size=1.5, color="black"))`, change to `& theme(axis.line.y = element_line(size=1.5, color="black"))`

also do not forget to put `library(patchwork)` to let it work.

**Comment by chlee-tabin** [comment]
```
VlnPlot(Merged.big, features = c("Sall1", "Rspo1","Cited1", "Six2", "Bmp7", "Eya1", "Crym", "Meox1", "Pax2"), pt.size = 0, split.by = "orig.ident") + 
theme(text = element_text(size = 50, face = "bold"))+ 
theme(axis.text.x=element_text(angle=45, hjust=1))+ 
theme(axis.text.x=element_text(angle=45, hjust=1))+
theme(axis.title = element_text(size=25,face="bold")) + 
theme(axis.text.x = element_text(size=25, color="black")) + 
theme(axis.text.y = element_text(size=25, color="black")) + theme(legend.text=element_text(size=40, color="black")) + theme(legend.title=element_text(size=25, color="black")) +
 theme(axis.line.x = element_line(size=1.5, color="black")) + 
theme(axis.line.y = element_line(size=1.5, color="black"))
```

I would change it to this:
```
library(pathwork)
VlnPlot(Merged.big, features = c("Sall1", "Rspo1","Cited1", "Six2", "Bmp7", "Eya1", "Crym", "Meox1", "Pax2"), pt.size = 0, split.by = "orig.ident")  &
theme(
    text = element_text(size=50, face = "bold"),
    axis.text.x = element_text( angle=45, hjust = 1, size=25, color="black" ),
    axis.text.y = element_text( size=25, color="black" ),
    axis.title    = element_text( size=25, face = "bold" ),
    legend.text = element_text( size=40, color="black"),
    legend.title = element_text( size=25, color="black"),
    axis.line.x = element_line(size=1.5, color="black"),
    axis.line.y = element_line(size=1.5, color="black"))
```

They key is replace the `+` to `&`.

**Comment by giovanegt** [comment]
It works great now. Thank you very much for the help!!!  @chlee-tabin
I will close this issue. I really appreciate your help.
