### ISSUE TITLE
Possibility of Integrating with different tissues from different donors?

### ISSUE THREAD

**Issue by Lesdormis** [satijalab/seurat#3127]
Dear Seurat Developers,

Sorry for this innocent question, but I really want to hear some advice and thoughts from the experts.
So we have a scRNA-seq data with Hashtag in three samples, all of them are CD4+ T cells from different donors, but one of them is collected from Lympho node samples, the other is collected from PBMC. 
I know it is a very bad experiment design, but it is like an exploratory experiment. I am wondering if we could integrate these three samples together and perform downstream analysis?

Thanks for any feedback!

**Comment by timoast** [comment]
You can certainly try it and see if the results make sense to you, it's hard to give specific advice without knowing much about the experiment or goal
