### ISSUE TITLE
integrating datasets with different references

### ISSUE THREAD

**Issue by abeliavskaia** [satijalab/seurat#3128]
Hi! 
I have sets of 10X data made from two close species, and I am aligning them against each genome. Is there a way to integrate data with different references? 
Thanks for the pipeline, btw, Seurat works wonderfully even for newbies like me :)

**Comment by jaisonj708** [comment]
It seems like you are trying to integrate data with different feature sets (correct me if I'm wrong). You will need to have a common set of features between your datasets for integration to work. Since your species are closely related, this shouldn't be a problem.
