### ISSUE TITLE
Preprocessing data for GSEA

### ISSUE THREAD

**Issue by jd10020** [satijalab/seurat#3129]
Hi Seurat team,

I am analyzing data from 10xgenemics where I have reached the point of using "Findmarkers" to define the different clusters after filtering, normalizing and scaling my data. However, now I want to process it so I can do pathway analysis using GSEA. I know I have to convert my data from each cluster into a .rnk file but I do not know how. I have looked at papers and several vignettes and still have not found anything. 

What would be the command for converting my data matrix in R for each cluster into a .rnk file? 
I found this code online:

# To prepare .rnk file
## Add a rank column using the following calculation, make sure to use p value, not padj.   
df$rank = -log10(df$pvalue) * sign(df$log2FoldChange)
## Order the rank by descending
df1 = df[order(df$rank, decreasing = TRUE),]
## Remove duplicate and subset GeneName and rank column
df1[which(duplicated(df1$SYMBOL)),]
df2 = df1[,c(9,10)]
df3 = (subset(df2, SYMBOL!="..." & SYMBOL!="..." & SYMBOL!="...")) <--------------
## Write to a .rnk file
write.table(df3, file=".txt", quote = FALSE, sep = "\t", row.names = FALSE, col.names = FALSE)

In the line I am pointing with the arrow what does SYMBOL!"..." mean? What should I fill there?

Thank you

**Comment by timoast** [comment]
I'm not familiar with the `.rnk` file, and since it's not part of the Seurat functionality I suggest you ask the GSEA developers instead.
