### ISSUE TITLE
Using categorical data as latent variable for MAST

### ISSUE THREAD

**Issue by leonfodoulian** [satijalab/seurat#313]
Hi,

I would like to use a categorical variable (i.e. batch) as latent variable for the MAST differential expression test. However, this throws me an error:

```R
>FindMarkers(object = object, ident.1 = "4", ident.2 = "7",
             random.seed = 1, test.use = "MAST", 
             latent.vars = c("nUMI", "batch"))
Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric
```

When I checked the code, it seems that the function is treating all latent variables as numeric as it is scaling these variables (code snippet from [line 1176 to 1178 in differential_expression.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/differential_expression.R#L1176-L1178)). One work around to fix this is to transform these categorical variables to numeric variables, but it just seems wrong to `scale` a categorical variable. Have you got any suggestion on how to treat these variables, and take them into account in the model matrix?

Thanks in advance!

Best,
Leon

**Comment by satijalab** [comment]
We corresponded by e-mail but adding the answer here as well. MAST does not currently support categorical variables for DE (hence we cannot in our MAST implementation as well), although one could modify their code to support this.

**Comment by leonfodoulian** [comment]
Great thanks! I nevertheless wrote a custom function implementing that, but I was not sure to what extent it made sense. Now that you say it, maybe using an alternative approach would be more sensical. Given that `Seurat` does not return corrected gene expression levels, do you think we can use any other parameter to account for differences in batch? `nGene` and `nUMI` are just not enough to account for large differences in gene expression levels, specifically across datasets. 

Thanks again in advance!

Best,
Leon

**Comment by leonfodoulian** [comment]
The answer to this question can be found in [issue #340](https://github.com/satijalab/seurat/issues/340).
