### ISSUE TITLE
Problem with average when using SCT method

### ISSUE THREAD

**Issue by semir2** [satijalab/seurat#3130]
Hi，
     Thanks you for great single cell RNA tool.  
     Now, I have a problem for heatmap with average expression of genes.  There was big different expression between SCT and RNA matrix(I got average expression by commands with AverageExpression). For example,
     RNA average expression of gene tdrd12:
> cluster.averages2$SCT['tdrd12',][20:21]
[1] 0.3653293 0.4671986
     SCT average expression of gene tdrd12:
> cluster.averages2$RNA['tdrd12',][20:21]
[1] 1.1543713 0.2838129
 
   It showed that RNA expression of gene tdrd12 cluster 20 is bigger than cluster21, while SCT expression of gene tdrd12 cluster 20 is smaller than cluster21. 

I could not undertand it, what is really different between SCT and RNA expression, and which one should be used for draw heatmap.

**Comment by saeedfc** [comment]
Hi,
Not from the developing team.
I guess you did SCTransform pipeline and did not do integration pipeline.
In the AverageExpression, did you mention the slot? 
When you perform the SCT pipeline, RNA assay only holds raw counts while the sctransformed, UMI corrected and log normalized values all get stored in SCT assay as described in the vignette part below:
 I just checked this with my data 

`identical(GetAssayData(so, assay = "RNA", slot = "data"), GetAssayData(so, assay = "RNA", slot = "counts"))`
and it returns TRUE meaning the dat aslot and counts slot of RNA assay holds the same matrix (raw count matrix)
Vignette says:-
_The results of sctransfrom are stored in the “SCT” assay. You can learn more about multi-assay data and commands in Seurat in our vignette, command cheat sheet, or developer guide.

pbmc[["SCT"]]@scale.data contains the residuals (normalized values), and is used directly as input to PCA. Please note that this matrix is non-sparse, and can therefore take up a lot of memory if stored for all genes. To save memory, we store these values only for variable genes, by setting the return.only.var.genes = TRUE by default in the SCTransform function call.
To assist with visualization and interpretation. we also convert Pearson residuals back to ‘corrected’ UMI counts. You can interpret these as the UMI counts we would expect to observe if all cells were sequenced to the same depth. If you want to see exactly how we do this, please look at the correct function here.
The ‘corrected’ UMI counts are stored in pbmc[["SCT"]]@counts. We store log-normalized versions of these corrected counts in pbmc[["SCT"]]@data, which are very helpful for visualization.
You can use the corrected log-normalized counts for differential expression and integration. However, in principle, it would be most optimal to perform these calculations directly on the residuals (stored in the scale.data slot) themselves. This is not currently supported in Seurat v3, but will be soon._

**Comment by timoast** [comment]
You shouldn't use the SCT assay for finding average expression, as the values are pearson residuals. The AverageExpression function by default assumes that the data slot contains log-transformed counts, and so takes the mean of the exponentiated value. This doesn't make sense for pearson residuals stored in the SCT assay. I would suggest using the RNA assay instead, and if you haven't run NormalizeData on the RNA assay set slot = "counts".

**Comment by semir2** [comment]
> Hi,
> Not from the developing team.
> I guess you did SCTransform pipeline and did not do integration pipeline.
> In the AverageExpression, did you mention the slot?
> When you perform the SCT pipeline, RNA assay only holds raw counts while the sctransformed, UMI corrected and log normalized values all get stored in SCT assay as described in the vignette part below:
> I just checked this with my data
> 
> `identical(GetAssayData(so, assay = "RNA", slot = "data"), GetAssayData(so, assay = "RNA", slot = "counts"))`
> and it returns TRUE meaning the dat aslot and counts slot of RNA assay holds the same matrix (raw count matrix)
> Vignette says,
> ** The results of sctransfrom are stored in the “SCT” assay. You can learn more about multi-assay data and commands in Seurat in our vignette, command cheat sheet, or developer guide.
> 
> pbmc[["SCT"]]@scale.data contains the residuals (normalized values), and is used directly as input to PCA. Please note that this matrix is non-sparse, and can therefore take up a lot of memory if stored for all genes. To save memory, we store these values only for variable genes, by setting the return.only.var.genes = TRUE by default in the SCTransform function call.
> To assist with visualization and interpretation. we also convert Pearson residuals back to ‘corrected’ UMI counts. You can interpret these as the UMI counts we would expect to observe if all cells were sequenced to the same depth. If you want to see exactly how we do this, please look at the correct function here.
> The ‘corrected’ UMI counts are stored in pbmc[["SCT"]]@CountS. We store log-normalized versions of these corrected counts in pbmc[["SCT"]]@DaTa, which are very helpful for visualization.
> You can use the corrected log-normalized counts for differential expression and integration. However, in principle, it would be most optimal to perform these calculations directly on the residuals (stored in the scale.data slot) themselves. This is not currently supported in Seurat v3, but will be soon **
> 
> I hope someone from the developing team will correct me if I am wrong

Thanks.
 I am appreciated for your help, your description helped me to understand how SCT works. Yes, I did performed the SCT pipeline with one sample, and in the AverageExpression, I did not  mention the slot.

**Comment by semir2** [comment]
> You shouldn't use the SCT assay for finding average expression, as the values are pearson residuals. The AverageExpression function by default assumes that the data slot contains log-transformed counts, and so takes the mean of the exponentiated value. This doesn't make sense for pearson residuals stored in the SCT assay. I would suggest using the RNA assay instead, and if you haven't run NormalizeData on the RNA assay set slot = "counts".

Many thanks.
Your answers  helped me to sove this problem and understand how SCT works.
