### ISSUE TITLE
Monocle v3 using Seurat

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#3131]
Hi, I am applying trajectory analysis on my Seurat object using Monocle v3.I want to use Seurat UMAP coordinates for my monocle. 
I attached my code as well. Could you please help me to fix this UMAP dimension issue.
[Issue.txt](https://github.com/satijalab/seurat/files/4750605/Issue.txt)

**Comment by satijalab** [comment]
Please checkout the feat/Monocle3 branch of seurat wrappers for an example on how to do this,  along with an example at https://github.com/satijalab/seurat-wrappers/blob/feat/monocle3/docs/monocle3.Rmd
