### ISSUE TITLE
converting sce object with delayed matrix to seurat object

### ISSUE THREAD

**Issue by janinemelsen** [satijalab/seurat#3133]
I would like to convert a single cell experiment object (imported as h5 file) to a seurat object by:

seurat <- as.Seurat(sce, counts="counts", data="logcounts")

_assignment of an object of class “DelayedMatrix” is not valid for slot ‘data’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE_

How can I solve this? I know how to read a h5 file directly into a seurat object, but I don't know how to convert sce to seurat.

**Comment by mojaveazure** [comment]
Seurat requires that the data be stored as either `matrix` or `dgCMatrix` objects. It appears as though your `SingleCellExperiment` object is using `DelayedMatrix` on the back-end, which Seurat does not support. To get your object into Seurat, you will need to convert all `Delayed*` objects within your `SingleCellExperiment` to standard data types.

**Comment by AidenSb** [comment]
Hi, @mojaveazure 
would you please elaborate on how we can convert all Delayed objects to standard data types that you mentioned? I couldn't find much on the internet, and I have this problem.

Thanks

**Comment by ycl6** [comment]
@AidenSb Below will change `counts` from `DelayedMatrix` to `dgCMatrix` data type.

```R
# Before
counts(sce)[1:5, 1:3] # <5 x 3> sparse matrix of class DelayedMatrix and type "integer"
class(counts(sce))    # DelayedMatrix

counts(sce) <- as(counts(sce, withDimnames = FALSE), "dgCMatrix")

# After
counts(sce)[1:5, 1:3] # 5 x 3 sparse Matrix of class "dgCMatrix"
class(counts(sce))    # dgCMatrix
```

**Comment by kaanokay** [comment]
Hi @AidenSb,

When I tried your code for conversion of DelayedMatrix to dgCMatrix, I encountered this error: "malformed slice 1
,slice stop less than slice start in slice 1, Error in getDataVec(dataset, indices, "JSON") : bad slices". 

Addition to that, when I subset DelayedMatrix as you made, I encountered the same error. My results after running class(counts(sce)) was like: 

[1] "DelayedMatrix"
attr(,"package")
[1] "DelayedArray"

What is your suggestion to figure out this error? 

Thanks.

**Comment by Ahmedalaraby20** [comment]
Hi @kaanokay, 
Did you manage to solve the issue?

**Comment by Marwansha** [comment]
hey,i have similar issue as am trying to convert my DelayedMatrix to dgCMatrix but get into an error,  my sce is large , and the ocnversion only work for small sce_objet, is there anyway to get around this 
thanks.

```
> sce@assays@data@listData$counts%>%str()
Formal class 'DelayedMatrix' [package "DelayedArray"] with 1 slot
  ..@ seed:Formal class 'DelayedSetDimnames' [package "DelayedArray"] with 2 slots
  .. .. ..@ dimnames:List of 2
  .. .. .. ..$ : int -1
  .. .. .. ..$ : chr [1:697321] "TTCAATCTCGAACCTA" "CGTAAGTTCACTCCGT" "GAGAGGTCACCCTATC" "GTGCACGAGTCGAAGC" ...
  .. .. ..@ seed    :Formal class 'DelayedSubset' [package "DelayedArray"] with 2 slots
  .. .. .. .. ..@ index:List of 2
  
  > assays(sce)$counts_dgC<- as(assay(sce, "counts"), "dgCMatrix")
Error in rbind(...) : negative extents to matrix
```
