### ISSUE TITLE
Different DE results - SCTransform - Integration

### ISSUE THREAD

**Issue by gskoufos** [satijalab/seurat#3136]
Hi Seurat team,

**Thanks for this amazing package!**

I have a question regarding DE analysis between two conditions. 

In my first attempt, I SCTransformed both samples, integrated them, performed clustering, cell type identification etc, switched to the RNA assay and performed DE analysis in a specific cell type between my conditions.

**As a result, I got 128 DE genes!**

Here is part of the code I used:

`wt <- SCTransform(wt, vars.to.regress = "percent.mt", verbose = F)`
`ko <- SCTransform(ko, vars.to.regress = "percent.mt", verbose = F)`
`both.conditions <- list(wt, ko)`
`features <- SelectIntegrationFeatures(object.list = both.conditions, nfeatures = 3000)`
`both.conditions <- PrepSCTIntegration(object.list = both.conditions, anchor.features = features, 
                                                               verbose = FALSE)`
`anchors <- FindIntegrationAnchors(object.list = both.conditions, normalization.method = "SCT", 
                                                         anchor.features = features, verbose = FALSE)`
`integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", 
                                              verbose = FALSE)`

`DefaultAssay(integrated) <- "integrated"`
`integrated <- RunPCA(integrated, npcs = 20, verbose = FALSE)`
`integrated <- RunUMAP(integrated, reduction = "pca", dims = 1:20)`
`integrated <- FindNeighbors(integrated, reduction = "pca", dims = 1:20, verbose = F)`
`integrated <- FindClusters(integrated, resolution = 0.6, verbose = F)`
`integrated.umap <- DimPlot(integrated, reduction = "umap", label = TRUE) + NoAxes()`

`DefaultAssay(integrated) <- "RNA"`
`de.genes <- FindMarkers(integrated, ident.1 = c1, ident.2 = c2, verbose = FALSE)`

In my second attempt, I followed the exact same steps but before switching to the RNA assay, I used the function NormalizeData() on the integrated object (similarly to https://satijalab.org/seurat/v3.0/integration.html)!

**As a result, I got 66 DE genes!**

Here is the last three lines of the code:

`integrated <- NormalizeData(integrated)`
`DefaultAssay(integrated) <- "RNA"`
`de.genes <- FindMarkers(integrated, ident.1 = c1, ident.2 = c2, verbose = FALSE)`

The lines before are identical to the code I posted previously!

Now I'm a bit confused about the (quantitative) differences in DE genes (128 vs 66)!

**Is this normal? I thought that if I switch to the RNA assay, normalization method wouldn't play a role in DE analysis!

If the differences are normal, which of the two ways is the correct one?** 

Thanks in advance!

**Comment by timoast** [comment]
This shouldn't be the case if `c1` and `c2` are not changed, are you able to provide a reproducible example? As a side note, you should **never** run `NormalizeData` on the integrated assay.
