### ISSUE TITLE
SCT and ALRA

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#3137]
Is it possible to use SCT and ALRA together in the same analytic pipeline? e.g., data imputation followed by normalization/scaling using SCT approach? If not, how do you suggest using ALRA in the Seurat-based analysis?

**Comment by satijalab** [comment]
It is not possible to combine the two approaches.  Any imputation/smoothing would violate the assumptions of the statistical models in SCTransform. We demonstrate how to work with ALRA in Seurat in our Seurat wrappers vignette.
