### ISSUE TITLE
use of AverageExpression function in Stimulated vs Control PBMCs

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#3138]
I am using your example vignette where you compare control and stimulated PBMCs.
I wanted to know and compare the expression level values of all the genes in cluster in both control and stimulated conditions.
 I am using `AverageExpression` function however it is giving me a gene expression list of various cluster in only one condition and  not sure which treatment condition. 
How can I generate a list of expression values of genes of a particular cluster with control and stimulated conditions

**Comment by timoast** [comment]
You need to first combine the clustering and treatment information as shown in the vignette, for example:

```r
immune.combined$celltype.stim <- paste(Idents(immune.combined), immune.combined$stim, sep = "_")
Idents(immune.combined) <- "celltype.stim"
AverageExpression(immune.combined)
```

**Comment by singcell** [comment]
@timoast Thank you for your response.
