### ISSUE TITLE
Node numbers cluster tree

### ISSUE THREAD

**Issue by beamaraba** [satijalab/seurat#3140]
Hi!

I just wanted to know what is the meaning of the node cluster number. Do they mean something? Why don't they start at 1 instead of 9 or any other number?

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

The leaf nodes should correspond to the current idents (these could be cluster numbers or character labels). The internal nodes are just the numbers returned from `hclust`. These will start from the number of leaf nodes + 1 and represent the nodes separating the groups at different levels of the hierarchical clustering.

**Comment by mariaimaz** [comment]
@andrewwbutler Does that mean the hierarchical clustering is divisive (top-down) rather than agglomerative? If I am misunderstanding and it builds a cluster tree from the bottom up, why would this make the numbers decrease rather than start with n+1 at the earliest node from the bottom?

**Comment by andrewwbutler** [comment]
No, as per the `hclust` docs, it's agglomerative . 
>This function performs a hierarchical cluster analysis using a set of dissimilarities for the n objects being clustered. Initially, each object is assigned to its own cluster and then the algorithm proceeds iteratively, at each stage joining the two most similar clusters, continuing until there is just a single cluster.
