### ISSUE TITLE
SCTransform information

### ISSUE THREAD

**Issue by rbioinfo** [satijalab/seurat#3143]
Hello,
I found this:

> The ‘corrected’ UMI counts are stored in pbmc[["SCT"]]@counts. We store log-normalized versions of these corrected counts in pbmc[["SCT"]]@data, which are very helpful for visualization.
> You can use the corrected log-normalized counts for differential expression and integration. However, in principle, it would be most optimal to perform these calculations directly on the residuals (stored in the scale.data slot) themselves. This is not currently supported in Seurat v3, but will be soon.
 
in the SCTransform vignette.

while in the integration vignette I found this:

```
DefaultAssay(pbmc.integrated) <- "RNA"
# Normalize RNA data for visualization purposes
pbmc.integrated <- NormalizeData(pbmc.integrated, verbose = FALSE)
```

If I use DefaultAssay(pbmc.integrated) <- "SCT" and then NormalizeData I can generate, for example, CPM using the corrected UMI counts and I can get them from obj[["RNA"]]@data in both cases: integration and single sample, while if I do not use NormalizeData I will work on log of the corrected UMI from SCT,  is it correct?

Is it better to use SCT values instead to change to RNA since all the workflow is based on SCT?

Why for the integration workflow you suggest to use RNA assay while in the single dataset mode you use the SCT values?

Thank you.

**Comment by jaisonj708** [comment]
This is probably a typo in our vignette. If you want to visualize data after integration of SCTransformed datasets, you are better off setting DefaultAssay to `SCT` instead of `RNA`.
