### ISSUE TITLE
Why the umap of rescaled subset data looks worse than that of total dataset?

### ISSUE THREAD

**Issue by Kailewang** [satijalab/seurat#3144]
Hi, 

I have a sample about 5k single cells, and I followed the tutorial to normalize data, find variable gene, scaledata and run PCA and umap. For a specific cell type such as fibroblast, it looks it has three distinct sub-clusters in the umap of the total dataset. 

However, I found those three distinct sub-clusters are not that clear after I subset fibroblast and rescale the data and run PCA and umap. I suppose the ScaleData is used to balance the dominate gene expression and increase the internal differences, and should show better of separation in high dimensional reduction plot like umap. But why it looks much worse? Does anyone know how to explain this? 

I know the scaled data is mainly used for high dimensional visualization, but if it worse than that, is it make sense to use the original scaled data (from the whole dataset) to run PCA and umap of subset data?

Thanks

**Comment by xhbkirby** [comment]
Hi @Kailewang Have you tried to re-find highly variable genes before scaling data on your subset dataset? The original highly variable genes for your whole dataset might not be the best to show heterogeneity when you only include the a specific cell type (in your case the fibroblasts).

**Comment by czlcaltech** [comment]
I agree with @xhbkirby. But in some situation, re-scale the subset dataset would also take risk of exaggerating noise in a dataset. The noise may cover the real biological significance. Sometimes, I just use the scaled data in the original database to perform PCA in subset dataset without rescaling.

**Comment by Kailewang** [comment]
Thanks, I did find re-scale the subset dataset greatly increases the noise signal when try to find the cell states differences. I skip rescale the data sometimes.

**Comment by duocang** [comment]
> Thanks, I did find re-scale the subset dataset greatly increases the noise signal when try to find the cell states differences. I skip rescale the data sometimes.

Hi @Kailewang 

How do you decide when you skip or keep re-scale? So to say, when is `sometimes` to you?

**Comment by Kailewang** [comment]
> > Thanks, I did find re-scale the subset dataset greatly increases the noise signal when try to find the cell states differences. I skip rescale the data sometimes.
> 
> Hi @Kailewang
> 
> How do you decide when you skip or keep re-scale? So to say, when is `sometimes` to you?

Hi @duocang 
My problem came from the integrated data sets. I changed the integration method to fastMNN, which doesn't need to scale the data before you do integration. It helped me to overcome that problem.
