### ISSUE TITLE
Error using Create Seurat Object 

### ISSUE THREAD

**Issue by rachel662** [satijalab/seurat#3148]
Hi, 
I have imported a txt counts file of scRNA seq data using read.table, and I can see that the data frame is fully loaded when I view it. 

However, when i go to create a Seurat object i get this error:   
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion

I looked at issue #1615 which suggested specifying the row.names = 1 argument, however when i try this upon reading the txt file into R I get this error: 
Error in read.table("GSE112903_uninf_lcmv_genesVcells.txt", header = TRUE,  : 
  duplicate 'row.names' are not allowed

Would anyone be able to advise me on how to fix these bugs?

**Comment by iSinedeus** [comment]
I responded in the other thread but just in case you didn't see it maybe Issue #1710 can help you.

**Comment by rachel662** [comment]
Thank you!
