### ISSUE TITLE
Visualization of arguments between replicates was lost in Seurat v3.1.5?

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#3149]
Hi all,
Previous versions of Seurat allowed one to visualized arguments between different replicates in DoHeatmap function with the code bellow. 
`DoHeatmap(object = cluster.averages, genes.use = PCTopGenes(object = pbmc, pc.use = 1, 
    do.balanced = TRUE), group.label.loc = "bottom", group.cex = 0)`
here is the fig
![heatmap](https://user-images.githubusercontent.com/58445209/84713196-18f19d00-af30-11ea-8e5f-bcb65eebf1a8.png)

Seurat v3.1.5 does not allow me to use the arguments `group.label.loc = "bottom"` and 
'group.label.roc = "TRUE"' 
 Returns message "unused argument". 

Now, the heatmap bellow, has three squares per cluster that represent the average expression of three different Seurat objects  (replicate 1, 2 and 3 Merged). 

The question is, how to add ids to each square in every cluster such as the heatmap above (bottom part of it)? I tried to splic.by original identity,  and it did not work. 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/58445209/84713402-800f5180-af30-11ea-96cd-90bc50001867.png">

I thank you very much

**Comment by andrewwbutler** [comment]
Hi,

The x axis labels correspond to the cell names so if after averaging your cell names look something like `UB_rep1` , you could restore the labels by adding ` + theme(axis.text.x = element_text())` to your plot and adjust the parameters within `element_text` as you like.

**Comment by giovanegt** [comment]
Thanks a lot! I appreciate your help.
