### ISSUE TITLE
Creating Seurat Object from Txt File Error

### ISSUE THREAD

**Issue by iSinedeus** [satijalab/seurat#3150]
Hello,

I am attempting to create a seurat object from a txt file but I am receiving the following message: Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion. The data from the initial txt file appears as such:

geneID  geneSymbol      NTH10-0616A     NTH11-0616A
1       A1BG    -0.848192830075538      -0.848192830075538
100     ADA     6.37629544131464        7.42094071975708
10000   AKT3    4.45607974331705        -1.09112388008517      

The NTH## are representative of unique cell IDs and continue on for many more columns I have just shown the first four here. When I run the following code:
counts <- read.table("file", row.names = 1, header = TRUE)
the table output is as such:
	
      geneSymbol     NTH10.0616A     NTH11.0616A
1	A1BG	-0.848192830	-0.84819283	-0.84819283
100	ADA	6.376295441	7.42094072	-1.11576636
10000	AKT3	4.456079743	-1.09112388	-1.09112388

When I run the following code is when I receive the warning message:
mydata_norm <- CreateSeuratObject(counts = counts, project = "mydata_scrnaseq")

The metadata slot of this object appears as such:
                orig.ident nCount_RNA nFeature_RNA
geneSymbol  mydata_scrnaseq         NA           NA
NTH10.0616A mydata_scrnaseq  1166.5945         2508
NTH11.0616A mydata_scrnaseq   703.2979         2455
NTH15.0616A mydata_scrnaseq  1616.3984         2621
NTH17.0616A mydata_scrnaseq -1686.2564         2029
NTH2.0616A  mydata_scrnaseq  -176.8017         2361

I understand this is an issue with the file not being formatted properly I was just wondering if there's a way to resolve the issues with the formatting to allow it to be loaded in properly? I also am a bit new to loading in txt files and I have tried it with another dataset that should work but after creating the seurat object I was not able to perform visualization from the data as I normally would. Is this something you should be able to do or is there limited data for these file types? I appreciate any help you may be able to offer.

Thank you

**Comment by rachel662** [comment]
Hi, I've had the same problem

**Comment by iSinedeus** [comment]
I think in my instance I need to actually set row.names = 2 although I then run into this issue you're having.  Issue #1710 seems to go into details in how to fix the row.names not being unique. But I end up then having the error:
Error in `.rowNamesDF<-`(x, value = value) : 
  missing values in 'row.names' are not allowed
when trying to make my row.names unique. This seems to suggest I have a missing value in this column but I'm not sure how to fix this. Hopefully that will help you some but maybe if anyone sees this and has a suggestion they could respond? The column has about 12000 rows so I'm not sure how to easily resolve any rows that may potentially contain NA after making the values unique.
