### ISSUE TITLE
DoHeatmap's  group.colors does not support named vector

### ISSUE THREAD

**Issue by chansigit** [satijalab/seurat#3151]
I noticed that the heatmap will display the color bar according to the order of elements in the vector. 

It would be favorable if 'group.colors' accepted a named vector like DimPlot.

In that way, we won't bother adjusting the order in the vector, simply pass the color palette vector used in DimPlot will solve the color issue; and the color strategy of DimPlot and DoHeatmap would be consistent.

**Comment by jaisonj708** [comment]
You can reorder the levels of the ident yourself, but we are also working on adding the requested functionality.

**Comment by chansigit** [comment]
Oh that would be great, thank you

**Comment by jaisonj708** [comment]
This is now available in the development version of Seurat. Install instructions can be found [here](https://satijalab.org/seurat/devinstall.html).
