### ISSUE TITLE
why be it used the sct assay counts that was batch-corrected matrix for differential expression analysis ? 

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3152]
Dear developer,
    It seem to weird that the batch-correct  count stored in sct assay ' named after counts',  can be it perform differential gene expression with this matirx? why should we calculate the batch-corrected count on sctranform workflow intead of standard integrated workflow.
    what the batch-corrected Negative Bionomial method function on the sctranform workflow?
    Any tips would be appreciated.

**Comment by satijalab** [comment]
I don't fully understand your question, but please see question 4 in our FAQ: https://satijalab.org/seurat/faq.html
