### ISSUE TITLE
Change shape of points in SpatialPlot

### ISSUE THREAD

**Issue by ph329** [satijalab/seurat#3153]
Hi, 

I was wondering if it is possible to change the shape of the points plotted by SpatialPlot (i.e from a circle to a square). I tried scale_shape_manual but it didn't work. I found [this comment](https://github.com/satijalab/seurat/issues/228) but it references the TSNEPlot function from a previous version of Seurat, which included a variable pt.shape which isn't found in SpatialPlot. Any help would be appreciated - thanks!

**Comment by mojaveazure** [comment]
It is not possible to change the shape of points in the spatial plots. Unlike standard dimensional reduction plots, spatial plots are showing the physical shape of the spots, which is why we decided not to support changing the shape on these plots.
