### ISSUE TITLE
how to get the full genes list for GSEA analysis?

### ISSUE THREAD

**Issue by Yinglei1** [satijalab/seurat#3156]
Hi,
I would like to do the GSEA between two different clusters. I tried to use this code(markers = FindMarkers(object = cluster, ident.1 = 0, only.pos = FALSE, verbose = T, logfc.threshold = 0, min.pct = 0,test.use = "wilcox")) to get the full genes list for the GSEA analysis, but there are about 300 genes missing finally when I used this code. 
Thanks in advance!

**Comment by timoast** [comment]
You can access the feature names using `rownames(object)`

**Comment by Yinglei1** [comment]
> You can access the feature names using `rownames(object)`

Hi, Thanks for your reply, I mean I would like to get all the gene sets which consisting of logFC and pvaule when comapring the different clusters, not only the gene nemes.

**Comment by ccruizm** [comment]
Hello! I was looking for the same and found the answer in issue  #532 (https://github.com/satijalab/seurat/issues/532). Hope that's you were looking for.

**Comment by Yinglei1** [comment]
> Hello! I was looking for the same and found the answer in issue #532 ('you can set the following parameters to -Inf: logfc.threshold, min.pct, and min.diff.pct'). Hope that's you were looking for.

Hi, I tried, it works! thanks a lot!!!
