### ISSUE TITLE
Understanding ST image data structure

### ISSUE THREAD

**Issue by anvaly** [satijalab/seurat#3158]
Hello! I am trying to work with ST image stored in the Seurat object.
```
# Load data
data_seurat <- Seurat::Load10X_Spatial(folder_path)
# Select low resolution coefficient
coefficient <- data_seurat@images$slice1@scale.factors$lowres
# Center coordinates for each barcode in the low resolution image
rows <- data_seurat@images$slice1@coordinates$imagerow * coefficient
cols <- data_seurat@images$slice1@coordinates$imagecol * coefficient
```

Now, I would like to get every pixel in the spot rather than just the center. To do that, I am trying to understand the spot information.
I see
- data_seurat@images$slice1@scale.factors$spot
- data_seurat@images$slice1@spot.radius
Digging into the code:
```
# Spot scale factor is the same as the high resolution image scale factor
data_seurat@images$slice1@scale.factors$spot <- scale.factors$tissue_hires_scalef
# Spot radius is the _fiducial_ diameter in the original resolution scaled down to the small resolution image divided by the width of the image (low resolution) in pixels
data_seurat@images$slice1@spot.radius <- scale.factors$fiducial_diameter_fullres * scale.factors$tissue_lowres_scalef / max(dim(x = image))
```

I feel like storing the original spot size spot_diameter_fullres from scalefactors_json.json would be hugely helpful here.

I am also curious about the rationale behind storing the values that currently exist in Seurat ST data structure - what am I missing here?

**Comment by andrewwbutler** [comment]
Hi Anna,

We only stored the spot radius for the low resolution image because that is the image we use for all the plotting functionality in Seurat.  Can you elaborate more on what you would need the `spot_diameter_fullres` for in the context of a Seurat analysis? We're not opposed to adding it in, just curious what you'd want to use it for.
