### ISSUE TITLE
How to get fasta file of a single gene from scRNA-seq

### ISSUE THREAD

**Issue by pankoj-das** [satijalab/seurat#3160]
Hello,
I'm having trouble getting fasta of a single gene from my scRNAseq data. I want to get sequence of one gene (e.g. NK1.1). What code I should run?

Thanks,
PK

**Comment by samuel-marsh** [comment]
Hi PK,

Seurat objects and their inputs don't actually contain the nucleotide sequence information you are looking for.  If you are looking for the full fasta sequence for a specific gene or transcript isoform you can find easily find those from ensembl or NCBI browsers.  If you are looking for the sequences for the reads that match those transcripts in your samples then you'll need to dig into the BAM file (assuming cell ranger output).  You visualize those reads and where they map using interactive tools like IGV.

Best,
Sam
