### ISSUE TITLE
resources for Seurat3 on 12 samples

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#3162]
Dear all, 

i would like for a piece of suggestion please about the resource needed for Seurat 3 running on 12 samples (each samples has 4000 - 5000 cells) : 

what would be the minimum RAM needed (it does not work on the full dataset shall i have a 64GB PC) ; 

and would you recommend to transfer all the data on Google Cloud, AWS, or on other platform ? 

thank you !

bogdan

**Comment by rschauner** [comment]
Is there a specific function you have memory issues with? I have a 64 GB MacBook Pro and I am currently doing an analysis with ~100k cells. Are you trying to use SCTransform?

**Comment by tanasa** [comment]
i believe that i should absolutely use the reference based integration : https://satijalab.org/seurat/v3.1/integration.html

i have been using the standard Seurat3 pipeline on 10 samples that does the pair-wise comparisons and i believe that took all the available RAM.

**Comment by rschauner** [comment]
Have you looked at this issue #1720, it may help. Without your code it is hard to suggest what to do, but if you are using the standard workflow (which calculates a ton of comparisons), try setting a dataset or a few as a reference. If you are already doing that, even though your data is not large, it might be computationally taxing on your computer, you might want to try the RPCA approach. I hope this helps.

**Comment by tanasa** [comment]
thank you :)
