### ISSUE TITLE
Problem with subsetting and proposed solution

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#3163]
Hello,

I've noticed when I run 'subset' that the resulting Seurat Object omits the 'RNA' assay in my data while retaining only the 'SCT assay. I realized the problem was related to the fact that the 'Count' slot only had dimNames specified for the features and not cells.... Is this an intended functionality of Seurat or not? I was able to circumvent this issue by preprocessing the Seurat object with the following helper function: 

`updateDimNames <- function(so){
  all.assays <- names(so@assays)
  for (i in 1:length(all.assays)){
    c.dim <- so@assays[[all.assays[i]]]@counts@Dimnames
    d.dim <- so@assays[[all.assays[i]]]@data@Dimnames
    
    if ((length(c.dim) == 1) & (length(d.dim) == 2)){
      if ((so@assays[[all.assays[i]]]@counts@Dim[1] == so@assays[[all.assays[i]]]@data@Dim[1]) & 
          (so@assays[[all.assays[i]]]@counts@Dim[2] == so@assays[[all.assays[i]]]@data@Dim[2])){
        so@assays[[all.assays[i]]]@counts@Dimnames <- so@assays[[all.assays[i]]]@data@Dimnames 
      }
    } else if ((length(d.dim) == 1) & (length(c.dim) == 2)){
      if ((so@assays[[all.assays[i]]]@counts@Dim[1] == so@assays[[all.assays[i]]]@data@Dim[1]) & 
          (so@assays[[all.assays[i]]]@counts@Dim[2] == so@assays[[all.assays[i]]]@data@Dim[2])){
        so@assays[[all.assays[i]]]@data@Dimnames <- so@assays[[all.assays[i]]]@counts@Dimnames
      }
    }
  }
  return(so)
}`

**Comment by NMikolajewicz** [comment]
> Hello,
> 
> I've noticed when I run 'subset' that the resulting Seurat Object omits the 'RNA' assay in my data while retaining only the 'SCT assay. I realized the problem was related to the fact that the 'Count' slot only had dimNames specified for the features and not cells.... Is this an intended functionality of Seurat or not? I was able to circumvent this issue by preprocessing the Seurat object with the following helper function:
> 
> `
> updateDimNames <- function(so){
> 
> # get all assays
> all.assays <- names(so@assays)
> 
> # ensure dim names are correctly specified
> for (i in 1:length(all.assays)){
> c.dim <- so@assays[[all.assays[i]]]@CountS@Dimnames
> d.dim <- so@assays[[all.assays[i]]]@DaTa@Dimnames
> 
> ```
> if ((length(c.dim) == 1) & (length(d.dim) == 2)){
>   if ((so@assays[[all.assays[i]]]@counts@Dim[1] == so@assays[[all.assays[i]]]@data@Dim[1]) & 
>       (so@assays[[all.assays[i]]]@counts@Dim[2] == so@assays[[all.assays[i]]]@data@Dim[2])){
>     so@assays[[all.assays[i]]]@counts@Dimnames <- so@assays[[all.assays[i]]]@data@Dimnames 
>   }
> } else if ((length(d.dim) == 1) & (length(c.dim) == 2)){
>   if ((so@assays[[all.assays[i]]]@counts@Dim[1] == so@assays[[all.assays[i]]]@data@Dim[1]) & 
>       (so@assays[[all.assays[i]]]@counts@Dim[2] == so@assays[[all.assays[i]]]@data@Dim[2])){
>     so@assays[[all.assays[i]]]@data@Dimnames <- so@assays[[all.assays[i]]]@counts@Dimnames
>   }
> }
> ```
> 
> }
> return(so)
> }`

**Comment by timoast** [comment]
> I've noticed when I run 'subset' that the resulting Seurat Object omits the 'RNA' assay in my data while retaining only the 'SCT assay

Can you provide a reproducible example for this?
