### ISSUE TITLE
SCT assay scale.data slot after merging Seurat objects and further analysis

### ISSUE THREAD

**Issue by xhbkirby** [satijalab/seurat#3165]
Hi,

I have a few SCTransform processed Seurat objects I'd like to merge (not integrate). These objects don't completely share the same cell types, and there're genes present in some but not all objects. When performing SCTransform on individual objects, I set `return.only.var.genes = FALSE` to have the same genes across the counts, data and scale.data slots within the SCT assay. However, after merging these object, it seems that the counts and data slots of the SCT assay contain the union of genes present in all of the objects, whereas the scale.data slot only contains genes that are shared by all the objects. After reading some of the posts like #1809, it seems that I have to make a matrix by manually merging the scale.data slots from each of the objects and replace the scale.data slot of the merged object.

So my first question is: For genes that are not commonly shared across all objects, what values should I set for these genes in the objects that don't express them? Should I set the scale.data values of such genes all to zero?

To explore the full diversity of the merged dataset, it's not ideal for me to use the intersect of HVGs of individual objects as input to run PCA or other dimensional reductions of the merged object. This is because using the intersect of HVGs might miss the important genes that define cell types that are only present in a few of the datasets. Ideally, I'd like to rerun `FindVariableFeatures` on the merged object, but based on the tutorial it looks like there's no standalone HVG finding function for SCTransform, and based on the posts in this forum the Seurat developers do not recommended to run SCTransform on a merged object.

So my second question is: Is there a workaround to find HVGs of the merged object based on the SCT assay? Or do I need to switch to the RNA assay, find HVGs, and then switch back to the SCT assay and run PCA using the HVGs obtained from the RNA assay? A third alternative might be simply using the union of the HVGs from individual objects?

**Comment by satijalab** [comment]
Thanks for the question, and I apologize as I know this is complex and difficult

The problem is that SCTransform calculates the deviation from the expected value, which is based on the population mean. If the population mean is 0, it does not make sense to assign a pearson residual. Usually this is not an issue (if the gene is not expressed, we just ignore it), but in your case - you are merging the object with another object, where the gene is expressed.

I'm not sure entirely how we would recommend proceeding. I suppose I would

1. Use the union of the HVG as you suggest
2. For the genes that aren't detected in one dataset, use a pearson residual (scale data) slot of 0.

Hope that helps-

**Comment by GouQiao** [comment]
> 

Hi xhbkirby

I also met the same problem for merging different objects .
Do you know how to make a matrix by manually merging the scale.data slots from each of the objects and replace the scale.data slot of the merged object?

Best

**Comment by MiTPenguin** [comment]
I assume you can just export the scale.data matrix from each of the object, and then merge them, resulting in one matrix of values and cell names, then manually replace the scale.data matrix. It's a bit tedious, but I'm sure there are some functions out there that's written for matrix merging.

I guess I am having trouble figuring out why someone might want to do this? Why not just take a union of all variable genes from each individual objects, merge the object, manually set the variable genes of the merged object to the union i.e. `VariableFeatures(seurat) <- union_HVG`, then run SCT?

I have not personally compared the approaches, but this seems like it would much more straightforward and get you to a similar result?

**Comment by ImNotaGit** [comment]
> Thanks for the question, and I apologize as I know this is complex and difficult
> 
> The problem is that SCTransform calculates the deviation from the expected value, which is based on the population mean. If the population mean is 0, it does not make sense to assign a pearson residual. Usually this is not an issue (if the gene is not expressed, we just ignore it), but in your case - you are merging the object with another object, where the gene is expressed.
> 
> I'm not sure entirely how we would recommend proceeding. I suppose I would
> 
> 1. Use the union of the HVG as you suggest
> 2. For the genes that aren't detected in one dataset, use a pearson residual (scale data) slot of 0.
> 
> Hope that helps-

@ChristophH For this issue, I would like to suggest a possible workaround, although I cannot decide whether it will work or work well in practice. Also, this will need to be implemented internally within the SCTransform function --

Basically, if something like log(x+1) is being modeled in the negative binomial regression, during regularization the model parameter vs gene mean trendline can be extrapolated to zero gene mean. Then the extrapolated model parameters can be used to correct the zero-expression genes to obtain their Pearson residuals. As said usually this is not necessary but for someone who is trying to integrate multiple datasets and do not want to lose some potentially important genes, this could be more reasonable than simply filling zeros for the missing Pearson residuals.

**Comment by RajneeshSrivastava** [comment]
> 



> Thanks for the question, and I apologize as I know this is complex and difficult
> 
> The problem is that SCTransform calculates the deviation from the expected value, which is based on the population mean. If the population mean is 0, it does not make sense to assign a pearson residual. Usually this is not an issue (if the gene is not expressed, we just ignore it), but in your case - you are merging the object with another object, where the gene is expressed.
> 
> I'm not sure entirely how we would recommend proceeding. I suppose I would
> 
> 1. Use the union of the HVG as you suggest
> 2. For the genes that aren't detected in one dataset, use a pearson residual (scale data) slot of 0.
> 
> Hope that helps-

Hi Team,
Is it possible to provide a pseudo code for 1 (and may be 2). Thank you in advance!
-Rajneesh
