### ISSUE TITLE
DoHeatmap in Integrated analysis

### ISSUE THREAD

**Issue by sallyey** [satijalab/seurat#3167]
Hi I've integrated 4 datasets following the integration vignette: https://satijalab.org/seurat/v3.1/immune_alignment.html

This is my workflow for the integrated analysis:

```
smc_list <- list(smc_wk0, smc_wk8, smc_wk16, smc_wk26)
smc.list <- lapply(X = smc_list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

smc.anchors <- FindIntegrationAnchors(object.list = smc.list, dims = 1:10, anchor.features = 2000)
smc.combined <- IntegrateData(anchorset = smc.anchors, dims = 1:10)
```

```
DefaultAssay(smc.combined) <- "integrated"
smc.combined <- ScaleData(smc.combined, verbose = FALSE)
smc.combined <- RunPCA(smc.combined,  verbose = FALSE) 
smc.combined <- RunUMAP(smc.combined, reduction = "pca", dims = 1:10)
smc.combined <- FindNeighbors(smc.combined, reduction = "pca", dims = 1:10)
smc.combined <- FindClusters(smc.combined, resolution = 0.4)

```
```
DefaultAssay(smc.combined) <- "RNA"
all.markers <- FindAllMarkers(smc.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
top5 <- all.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
smc.combined <- ScaleData(smc.combined, verbose = FALSE)
DoHeatmap(smc.combined, features = top5$gene, size = 2) + NoLegend() + 
  theme(text = element_text(size = 5), legend.title = element_text(size=10), legend.text=element_text(size=5))
```

But, somehow, when I perform "DoHeatmap", one cluster shows the expression is split in half (i.e yellow line is cut in half in this cluster: the first half of the yellow chunk is in the same line with cluster 10's and the other half of the yellow chunk is in cluster 1)

As you can see, I used "RNA" assay and also scaled the data once again for "RNA" assay for the heatmap.
I have also tried lots of different combination of other parameters: different number of feature selection, resolution, CC, and PC, but every heatmap still shows one cluster that has two populations.. 

Could you let me know what part of my code would cause this problem in heatmap?
Any idea is much appreciated. Thank you.

**Comment by satijalab** [comment]
I think the issue is that there are gene expression differences between your samples. This is normal, and its the reason why you want to perform integration. For visualization, you can try plotting markers that are conserved across the datasets.

You can use FindConservedMarkers to do this. You can see an example here: https://satijalab.org/seurat/v3.1/immune_alignment.html
