### ISSUE TITLE
Leidenalg: FindClusters with method='igraph' with default weights=NULL is not good: suggestions to fix it

### ISSUE THREAD

**Issue by therealgenna** [satijalab/seurat#3168]
Currently (Seurat v3.1.5, `Seurat:::RunLeiden`), using `method='igraph'` with the default of `weights=NULL` when calling `FindClusters(..., algorithm=4, ...)` is not working well, as it calls `igraph::graph_from_adjacency_matrix()` also with the default of `weighted=NULL`, which seems to drop all edge weights below 1 (I suppose it might use floor()); since all SNN weights are <=1, most of the edges are dropped yielding most of the vertices as singletons (which are later assigned to a nearby cluster with the default group.singletons=T of FindClusters.) 

The straightforward workaround is to pass `weights=T` in conjunction with `method='igraph'` - see Seurat:::RunLeiden. This produces clustering identical to the default `method='matrix'` (with the default `weights=NULL`).

Probably, the correct fix of the code would be to use `graph_from_adjacency_matrix(adjmatrix = object, weighted = TRUE)` inside `Seurat:::RunLeiden()` irrespective of passed argument `weights` being NULL or not. Presently, this is not the case.

However, the graph constructed by `igraph::graph_from_adjacency_matrix()` is by default directed (`mode='directed'`), and there is no way to change that via Seurat function arguments (need to change the code for that). I wonder why not use the `undirected` graph? This makes more sense to me, and has twice fewer edges (excl. diagonal); perhaps the method='matrix' code might need to be modified as well to be equivalent to method='igraph', weighted=T, mode='undirected' (or maybe not - see leiden:::leiden.matrix and leiden:::leiden.igraph).

`igraph::graph_from_adjacency_matrix(..., mode='undirected')` complains that matrix is not symmetric (which is not true - see below) and does not work, if passed Seurat Graph, but passing with explicitly set dimensions works:
```
tmp=dim(obj@graphs$RNA_snn)
snn_graph <- igraph::graph_from_adjacency_matrix(obj@graphs$RNA_snn[1:tmp[1],1:tmp[2]], mode='undirected', weighted=T)
```
Alternatively, can use mode='max' or or several other alternatives, if sure that the matrix IS symmetric.

```
Matrix::isSymmetric(obj@graphs$RNA_snn) # FALSE
# BUT:
all(Matrix::t(obj@graphs$RNA_snn)==obj@graphs$RNA_snn) # TRUE
tmp=dim(obj@graphs$RNA_snn)
Matrix::isSymmetric(obj@graphs$RNA_snn[1:tmp[1],1:tmp[2]]) # TRUE
```

**Comment by chlee-tabin** [comment]
I am just putting this link so that the same topic is linked together.

https://github.com/satijalab/seurat/issues/2817#issuecomment-609420154

**Comment by therealgenna** [comment]
There is also
#3055

**Comment by TomKellyGenetics** [comment]
Hi, I wrote the Leiden version of `FindClusters`. Thanks for the feedback.

I have raised a similar issue to propose changes related to this here: https://github.com/satijalab/seurat/issues/2574

Unfortunately, I haven't had time for this recently. I will try to check back on it soon. Some changes to the [`leiden`](https://github.com/TomKellyGenetics/leiden/issues/1) R package for performance are also being discussed.

**Comment by andrewwbutler** [comment]
Thanks for the bringing it up again. I don't really see a situation where we would want unweighted graphs here. I  agree that the current behavior with `method = "igraph"` and `weights = NULL` isn't ideal and I'd be in favor of either dropping the weights argument or at least defaulting to `TRUE`. Basically, I agree with what Tom's proposing in #2574. 

The point about the matrix not being symmetric I think is just an artifact of the object being of the `Graph` class and the symmetric method not being properly defined for that class. If you convert back to a matrix before passing to `igraph::graph_from_adjacency_matrix`, then `mode = "undirected"` should work as expected. 

It looks like native igraph support for leiden is in the works but in the short term I think those two changes (default to `weights = TRUE` and use `mode = "undirected`) would be good to implement. I can put together a together a PR for those if it sounds reasonable to you all (@TomKellyGenetics @therealgenna @chlee-tabin )

**Comment by TomKellyGenetics** [comment]
Thanks @andrewwbutler, happy to help on this but I don't have much time. Feel free to tag me in to help with or "review" the PR if you need a second opinion.

To clarify, using `weights = NULL` for the igraph method of [`leiden` ](https://github.com/TomKellyGenetics/leiden) is not necessarily "unweighted". If the graph is "wieghted" (i.e. has `set_edge_attr(graph, "weight", value = weights)`, `edge.attributes(graph)$weight`, or `E(graph)$weight`), then `leiden` will use these are weights. The "unweighted" computation only occurs if the `igraph` object (`Graph` class in this case) does not have weights as an edge attribute.

When we added the Leiden algorithm to `FindClusters` the R version of `leiden` did not support `weights` yet. I think the `Seurat` version (called by `FindClusters` with `algorithm = 4`) still defaults to unweighted graphs. I _agree_ that weighted graphs should be the default here. All that is needed to do this, is to ensure that a weighted graph is passed to `leiden.igraph`.

```{r}
graph <- graph_from_adjacency_matrix(adjacency_matrix, weighted = TRUE)
```

OR

```{r}
graph <- graph_from_adjacency_matrix(adjacency_matrix)
graph <- set_edge_attr(graph, "weight", value = weights)
```

You can explicitly pass `weights` to `leiden.igraph` but this is not necessary if the `igraph` object has a `weight` attribute.

For example:

```{r}
leiden(igraph_object, partition_type =  'RBConfigurationVertexPartition', weights = weight_params, resolution = 0.8)
```

As discussed with @vtraag [here](https://github.com/TomKellyGenetics/leiden/issues/1#issuecomment-650806493), a `community_leiden` function is being added to `igraph` directly. This will improve performance but have limited options compared to the Python version (it will only support 2 quality functions and undirected graphs). I will call these in `leiden` where possible to improve performance and retain the remaining arguments called via `reticulate`.

Once this becomes available, it should be possible to have a "soft" dependency on the Python `leidenalg` package. It would also be possible to call this version in `Seurat` if it is acceptable to changed the quality function to "modularity" or "CPM".

Note that changing the _quality function_ or making _weighted graphs default_ will **change default results** from the development version (and future releases) of `Seurat`. I'm okay with doing this as discussed in #2440 and proposed in #2574.

**Comment by therealgenna** [comment]
@andrewwbutler Thank you for taking are of that! That sounds good to me too; the only caveat is that I am not sure if switching to `mode='undirected'` will produce the exact same results as when using `FindClusters(..., method='matrix', ...)`, so perhaps `leiden:::leiden.matrix` will need to be updated? Not sure, but I am just saying that `FindClusters(..., method='matrix', ...)` and `FindClusters(..., method='igraph', ...)` should produce identical results in the end.

**Comment by therealgenna** [comment]
Another related comment regarding `method='matrix'`. In `Seurat:::RunLeiden(..., method='matrix')` converts passed object to a dense matrix with `matrix = {input <- as(object = object, Class = "matrix")}`. When it's too large I get an error 
```
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```
and therefore had to try `method='igraph'`. However, `leiden:::leiden.matrix` seems to be able to handle sparse matrices, at least in part. If the code part calculating weights there can be updated to work with sparse matrices as well maybe there will be no need for `method='igraph'` at all? I haven't looked deep into it, but this might be an option as well.

**Comment by TomKellyGenetics** [comment]
@therealgenna to clarify, [leiden](https://github.com/TomKellyGenetics/leiden) is a separate R package called as dependency of Seurat that I maintain. If there is an issue with `leiden.matrix` please report a separate issue on this repository to discuss in more details.

Note that the current version of [leiden 0.3.3](https://cran.r-project.org/web/packages/leiden/index.html) supports deriving edge weights from an non-zero adjacency matrix (see [code here](https://github.com/TomKellyGenetics/leiden/blob/master/R/leiden.R#L133-#L141) for details). Provided that a non-binary (sparse) matrix of values other than 0 and 1 is passed to it, specifying weights is not necessary.  

You can see here that Seurat does this as the `Seurat::Graph` class is a sparse `dgCMatrix`. So [`RunLeiden`](https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/clustering.R#L691) should do this when [called internally](https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/clustering.R#L85) by `FindClusters`.

```{r}
library("Seurat")
data(pbmc_small)
pbmc_small <- RunPCA(pbmc_small)
pbmc_small <- RunUMAP(pbmc_small)
pbmc_small <- FindNeighbors(pbmc_small)
pbmc_small@graphs$RNA_snn[1:6,1:6]
```

```
6 x 6 sparse Matrix of class "dgCMatrix"
               ATGCCAGAACGACT CATGGCCTGTGCAT GAACCTGATGAACC TGACTGGATTCTCA AGTCAGACTGCACA TCTGATACACGTGT
ATGCCAGAACGACT      1.0000000      0.8181818      0.4285714      0.6000000      1.0000000      1.0000000
CATGGCCTGTGCAT      0.8181818      1.0000000      0.4285714      0.4814815      0.8181818      0.8181818
GAACCTGATGAACC      0.4285714      0.4285714      1.0000000      0.2903226      0.4285714      0.4285714
TGACTGGATTCTCA      0.6000000      0.4814815      0.2903226      1.0000000      0.6000000      0.6000000
AGTCAGACTGCACA      1.0000000      0.8181818      0.4285714      0.6000000      1.0000000      1.0000000
TCTGATACACGTGT      1.0000000      0.8181818      0.4285714      0.6000000      1.0000000      1.0000000
```
```{r}
class(pbmc_small@graphs$RNA_snn)
```
```
[1] "Graph"
attr(,"package")
[1] "Seurat"
```

```{r}
sessionInfo()
```
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.1.5
```

I _think_ in this case, the issue is specific to the `igraph` methods for `FindClusters` as these were added later. The different handling of weights may explain why these return different results (as @chlee-tabin has pointed out before).

**Comment by therealgenna** [comment]
@TomKellyGenetics I agree with what you say. My last point was simply to say that when a non-binary sparse `dgCMatrix` matrix is passed to `leiden:::leiden.matrix` it will be converted (in leiden v 0.3.3) to a dense matrix for calculation of weights (when `weights=NULL`, which is passed default), so even _if_ the passed matrix will be sparse, there will be the conversion to dense matrix which will also give the `Cholmod error 'problem too large'` for large matrices (over ~45,000 cells?). 

So for the non-binary large matrix one presently has to use `method='igraph'` (currently, with `weights=T`). 

However, if `leiden:::leiden.matrix` could circumvent conversion to dense matrix for calculation of weights then `method='matrix'` would likely work just fine even for large `dgCMatrix` matrices (or Seurat's Graphs). There would be no need for the two methods:` 'matrix'` and `'igraph'`. Either one would work (but there may be some memory or time considerations perhaps; since `method='matrix'` and `method='igraph'` in `FindClusters` are just two technical ways to get to the exactly same result, ideally the specific choice should be under the hood.)

I am not saying that `leiden` has an issue, but I was just suggesting to Seurat folks this option - if they find it useful they might raise an issue on `leiden` github page. If I understand correctly, you wrote `leiden` package, as well as Seurat's `RunLeiden()` function. Please correct me if I am wrong. I also understand that things are in flux right now; I was just talking about the snapshot I see.

**Comment by TomKellyGenetics** [comment]
@therealgenna Thanks for the feedback. As discussed in previous issues pertaining to Leiden, it is not possible to pass a sparse matrix to Python via `reticulate`. Therefore we recommend the `method="igraph"` (which passes an edge list) for last datasets. I will look into whether weights can be supported with the matrix version of `leiden` but unfortunately, casting to dense matrix is necessary. See the relevant discussions here: #1645 #2438 #2440
