### ISSUE TITLE
DotPlot() color key scaled despite parameter scale=FALSE

### ISSUE THREAD

**Issue by tilofreiwald** [satijalab/seurat#3169]
Hi, I use this code to draw a DotPlot():

````
DotPlot(seu, assay = "RNA", features = marker.genes, group.by = cluster, scale = FALSE)
````
![image](https://user-images.githubusercontent.com/3132968/85342331-56b66e80-b4b8-11ea-8ccf-447484d90030.png)

I am wondering why the color key is still labeled as scaled despite the parameter `scale=FALSE`? If I change it to `scale=TRUE` the DotPlot itself looks different but the legend stays the same suggesting the scaling works but not the legend labeling.

Thanks!
Tilo

**Comment by satijalab** [comment]
the scale parameter refers to the possibility of z-scoring the underlying data. The color scale will change either way. We do support passing in a custom color scale to the function, if you want (for example), to only have blue dots: cols = c("blue", "blue")

**Comment by AndreaYCT** [comment]
@satijalab

How to have the scale for average expression in Seurat 4?

Many thanks
