### ISSUE TITLE
Regress out orig.ident in SCTransform 

### ISSUE THREAD

**Issue by vwtlin** [satijalab/seurat#3171]
Hi Seurat team,

Thanks for developing this fantastic tool. As in the standard workflow, orig.ident could usually be regressed out during the ScaleData step after integration.

However, SCTransform is performed before integration. Does it mean I could not regress orig.ident in the new method after integration?

I will be grateful if you could provide some advice. Thanks in advance.

Cheers,
Weitao

**Comment by vwtlin** [comment]
Hi Seurat team,

Thanks for developing this fantastic tool. As in the standard workflow, orig.ident could usually be regressed out during the ScaleData step after integration. 

However SCTransform is performed before integration. Does it mean I could not regress orig.ident in the new method after integration?

I will be grateful if you could provide some advice. Thanks in advance.

Cheers,
Weitao

**Comment by yuhanH** [comment]
HI, Weitao
You are right. After integration, SCT normalized data cannot be used to regress out orig.ident
But you can be regressed out some confound variables in the SCTransform step by `vars.to.regress`
