### ISSUE TITLE
metap giving "non-zero exit status"

### ISSUE THREAD

**Issue by ll-portes** [satijalab/seurat#3173]
Hi!

I was following the guided tutorial Stimulated vs Control PBMCs using RStudio. Everything running OK until last week. However, the function FindConservedMarkers stopped working now (in the same tutorial, I didn't modify anything). Its output is the message:

> Error: Please install the metap package to use FindConservedMarkers. This can be accomplished with the following commands: ---------------------------------------- install.packages('BiocManager') BiocManager::install('multtest') install.packages('metap') ----------------------------------------

I followed the instructions, but I got problems with `install.packages('metap')`:

> Warning messages:
> 1: In install.packages("metap") :
>   installation of package ‘sn’ had non-zero exit status
> 2: In install.packages("metap") :
>   installation of package ‘TFisher’ had non-zero exit status
> 3: In install.packages("metap") :
>   installation of package ‘metap’ had non-zero exit status

Then, I've tried `install.packages('sn')` and got:

> ERROR: dependency ‘mnormt’ is not available for package ‘sn’

Today I've tried a fresh R install and using `install('Seurat', dependencies = TRUE)`, I still got similar errors:

> Warning messages:
> 1: In install.packages("Seurat", dependencies = TRUE) :
>   installation of package ‘sn’ had non-zero exit status
> 2: In install.packages("Seurat", dependencies = TRUE) :
>   installation of package ‘hdf5r’ had non-zero exit status
> 3: In install.packages("Seurat", dependencies = TRUE) :
>   installation of package ‘TFisher’ had non-zero exit status
> 4: In install.packages("Seurat", dependencies = TRUE) :
>   installation of package ‘mutoss’ had non-zero exit status
> 5: In install.packages("Seurat", dependencies = TRUE) :
>   installation of package ‘metap’ had non-zero exit status

Please, would anyone have any advice?

**Comment by samuel-marsh** [comment]
Hi,

What version of R are you running?  What happens if you try and install the mnormt package that failed during sn installation attempt?

Best,
Sam

**Comment by ll-portes** [comment]
Thank you @samuel-marsh  for making me check that!
I was in version 3.6, and didn't notice that the path to the cran was commented in the /etc/apt/sources.list file (after Ubuntu update some months ago). 

mnormt needs R >4, and after updating R to 4 it's everything working fine!

Cheers,
Leo.

**Comment by Seda2022** [comment]
Hi,

Although I use R 4.1.2, I am having the same problem. Thank you so much in advance for any help!

Seda

Installing package into ‘/PHShome/se22/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
also installing the dependency ‘qqconf’

trying URL 'http://cran.rstudio.com/src/contrib/qqconf_1.2.3.tar.gz'
Content type 'application/x-gzip' length 519510 bytes (507 KB)
==================================================
downloaded 507 KB

trying URL 'http://cran.rstudio.com/src/contrib/metap_1.8.tar.gz'
Content type 'application/x-gzip' length 1097503 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

* installing *source* package ‘qqconf’ ...
** package ‘qqconf’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc -std=gnu11
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu11 accepts -g... yes
checking for gcc -std=gnu11 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu11 -E
checking for gcc... (cached) gcc -std=gnu11
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc -std=gnu11 accepts -g... (cached) yes
checking for gcc -std=gnu11 option to accept ISO C89... (cached) none needed
checking for pkg-config... yes
Package fftw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fftw3' found
Package fftw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `fftw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fftw3' found
configure: creating ./config.status
config.status: creating src/Makevars

fftwtools 0.9-10
================

compiler flags:  
link argument:   

** libs
g++ -std=gnu++11 -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG  -I'/opt/R/4.1.2/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/4.1.2/lib/R/include" -DNDEBUG  -I'/opt/R/4.1.2/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c jointlevel_fft_twosided.cpp -o jointlevel_fft_twosided.o
jointlevel_fft_twosided.cpp:10:10: fatal error: fftw3.h: No such file or directory
   10 | #include <fftw3.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [/opt/R/4.1.2/lib/R/etc/Makeconf:175: jointlevel_fft_twosided.o] Error 1
ERROR: compilation failed for package ‘qqconf’
* removing ‘/PHShome/se22/R/x86_64-pc-linux-gnu-library/4.1/qqconf’
Warning in install.packages :
  installation of package ‘qqconf’ had non-zero exit status
ERROR: dependency ‘qqconf’ is not available for package ‘metap’
* removing ‘/PHShome/se22/R/x86_64-pc-linux-gnu-library/4.1/metap’
Warning in install.packages :
  installation of package ‘metap’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpuh7Ea1/downloaded_packages’

**Comment by Seda2022** [comment]
My colleague helped me out to separately install qqconf, fftw3, metap through the terminal, as far as I could understand. Let me reach him if he can tell more about it. I am very new in R and this was too much for me to process.

Best,

**Comment by livialn** [comment]
Hi,

Im also new to R and coding in general, trying to transit from wet lab to
bioinformatics Thank you so much! I just managed to install fftw3 in the
terminal thanks to someone that posted a similar problem with a different
package and now everything seems to run fine. However, thank you so much
for your prompt response and being so willing to help!

Best,
Livia

**Comment by sdwien** [comment]
Dear all,
I just solved this problem on my machine (Ubuntu 20.04.4 LTS) installing the following two packages in the system terminal (outside R):
```
sudo apt install fftw3
sudo apt install libfftw3-dev
```

After that, 

`install.packages("metap")`

ran successfully.

Hope that helps.

Best, Sophia

**Comment by jingydz** [comment]
Hi, if I am not the root or the sudoer, how can I install fftw3 to deal with this problem? Any else solutions could you give?

**Comment by felixm3** [comment]
I was having similar issues installing `metap` getting the error

`jointlevel_fft_twosided.cpp:10:10: fatal error: fftw3.h: No such file or directory`

Since my R is in a conda environment, I exited the R program and used conda to install `fftw` by typing:

`conda install -c conda-forge fftw`

After that, going back to R and installing `metap` using `install.packages` as usual worked for me.
