### ISSUE TITLE
FindTransferAnchors error with subset of the reference

### ISSUE THREAD

**Issue by minhtran1309** [satijalab/seurat#3176]
Hi, 

I currently running the label transfer with my dataset and running into an issue when I use all the labels reference dataset to run `FindTransferAnchors` it works fine. 
However, there are some clusters that are not so relevant to the actual prediction data that I would like to subset out, it causes the error as follow
```
Error in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length
Traceback:

1. FindTransferAnchors(reference = subset_interest2, query = data, 
 .     query.assay = "RNA", normalization.method = "SCT", npcs = 50, 
 .     dims = 1:50, k.anchor = 5, k.filter = 200)
```
I searched around the closed issues that were relevant to  FindTransferAnchors but none of them provide the proper solution. 
I am using Seurat spatial  ‘3.1.5.9900’

**Comment by yuhanH** [comment]
Here, you should set `query.assay = SCT`. If you set  `normalization.method = "SCT" `, your query data should also be SCT normalized. 
Could you provide more information about the code you ran?

**Comment by minhtran1309** [comment]
Yup I tried `query.assay = SCT` already but it didn't work. 
However, after a massive upgrade to R 4.0.9 and Seurat packages, I was able to overcome the issue. I am not quite sure how I resolve my problem now.
