### ISSUE TITLE
Unable to use single color gradient for DotPlot() when using split.by

### ISSUE THREAD

**Issue by andrewni4313** [satijalab/seurat#3177]
Hi,

I am trying to use one color gradient for the entire dot plot while using split.by.
However, specifying only one color gradient for `cols` from RColorBrewer while using split.by results in an error:

```
DotPlot(tc.cd4, features = immune_genes[1:5], cols = "RdYlBu", split.by = "tumor")
Error in DotPlot(tc.cd4, features = immune_genes[1:5], cols = "RdYlBu", : Not enought colors for the number of groups
```

Passing the gradient in twice does not work either:

```
DotPlot(tc.cd4, features = immune_genes[1:5], cols = c("RdYlBu", "RdYlBu"), split.by = "tumor")
Error in col2rgb(colors, alpha = alpha) : invalid color name 'RdYlBu'
```

The desired result is this but with split.by defined:

`DotPlot(tc.cd4, features = immune_genes[1:5], cols = "RdYlBu")
`

![image](https://user-images.githubusercontent.com/45903831/85487846-53e07a00-b59b-11ea-9b16-7315d71e55dc.png)

If this can't be fixed quickly is there a workaround?

Thanks!

**Comment by satijalab** [comment]
Thanks. I think this is likely a bug on our part, we will take a look.

**Comment by jaisonj708** [comment]
This is now available in the development version of Seurat (installation instructions [here](https://satijalab.org/seurat/install.html#development). You can set `cols` to the name of a palette even when `split.by` is given.
