### ISSUE TITLE
Merging multi species

### ISSUE THREAD

**Issue by mamtagiri** [satijalab/seurat#3178]
Hi guys,

I have single cell data from 2 species that I would like to compare and contrast. Is the Seurat pipeline normalization and clustering good to handle that?  Do we need to be wary of anything in doing so? What would be the best way to evaluate the clustering considering multiple differences between the two as well as gene name differences.

Thanks,
Mamta

**Comment by satijalab** [comment]
This is a conceptually difficult issue that goes beyond the scope of our Github issues. We do support the ability to integrate datasets across species using our anchor-based integration workflows. This does rely on the assumption that at least some cell states are shared across species, and that there are shared gene names to facilitate alignment. That's probably the most that we can advise for the moment.
