### ISSUE TITLE
Integration of multiple datasets from different condition

### ISSUE THREAD

**Issue by Goultard59** [satijalab/seurat#3179]
Hello,

I'm trying to analyse a dataset of microglia across condition like in your tutorial : https://satijalab.org/seurat/v3.1/immune_alignment.html
I don’t know which methods is the best to integrate the data from different samples and from different conditions.
Is it better apply to SCTransform on the different samples or in the different conditions.
The use of the workflow described here : https://satijalab.org/seurat/v3.1/immune_alignment.html has an upregulation of genes in the stimulated condition.

Thanks,
Adrien.

**Comment by satijalab** [comment]
We suggest running SCTransform on each sample individually, even if the sample contains cells from different cell types or conditions.
