### ISSUE TITLE
Defining ratio of two genes 

### ISSUE THREAD

**Issue by del2007** [satijalab/seurat#318]
I'd like to run a DE test on the ratio of two genes between 2 groups (this ratio is biologically relevant in my data).  Any idea on how to define it and accomplish this? 

Or at least, is there a way to export the ratio values for each single cell from the gene plot where the 2 genes of interest have been plotted? 
Also, open to any other ideas on how to compare these ratios at single cell level. 
Many thanks!

**Comment by satijalab** [comment]
You can certainly extract the underlying data (for example, in object@data) and calculate these ratios, but we do not support doing DE in this way
