### ISSUE TITLE
Scaling in DoHeatmap for two cluster datasets

### ISSUE THREAD

**Issue by sophiecowman** [satijalab/seurat#3180]
I have a seurat object with 8 clusters. I subset this object to a new object with just two clusters. 

I ran AverageExpression followed by DoHeatmap to plot a heatmap for some genes I'm interested in. The problem is that the heatmap produced is only two colors (plus black for zero) with no gradient (scale bar has gradient). 

![image](https://user-images.githubusercontent.com/50600588/85630086-4f19d580-b630-11ea-83c1-f355888e0ac4.png)

I assume this is related to how the data is scaled. I read (in another post) that each gene is scaled individually, but not every gene will have the same highest or lowest scaled value, thus a gradient is created. If I am understanding this correctly, the above plot shouldn't be just the two colors. 

If anyone can shed some light on this I would appreciate that. I may have just understood it incorrectly. If there is any workaround to change the scaling that would be great too. 

Just an FYI, if I subset the data so it has two clusters there is a gradient in the colors. 

Thanks for your help!

**Comment by yuhanH** [comment]
You can modify `disp.min` and `disp.max` in `DoHeatmap` to get the color gradient in your case.

**Comment by sophiecowman** [comment]
I tried changing the disp.min and disp.max but this doesn't help the issue. The heatmap itself only has two colors, no gradient of colors representing the varied expression levels within the map. The legend of course does change with disp.min/max, but I still see no color gradient on the map itself, all negative values are solid purple, all positive is solid yellow, no gradient between these (e.g no blended color between black and yellow).

**Comment by yuhanH** [comment]
The default slot for `DoHeatmap` is scale.data. 
Could you check if the scale.data slot in your averaged object have different value?
