### ISSUE TITLE
Running Monocle3 and Seurat

### ISSUE THREAD

**Issue by sudiptaashe** [satijalab/seurat#3181]
I want to find cell trajectories in my dataset. I am using the Seurat and Monocle 3 from Satija lab
https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html
 I am getting the following error while finding the integration anchors-
anchors <- FindIntegrationAnchors(monocle_duct, reference = NULL , reduction = "rpca", dims = 1:30)

Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  
Error in which(x = object.classes, useNames = TRUE) : argument to 'which' is not logical

![error](https://user-images.githubusercontent.com/57572877/85637592-796f9100-b638-11ea-9a1c-913382feb848.png)

Session info-

![Session info](https://user-images.githubusercontent.com/57572877/85637227-7a53f300-b637-11ea-9f62-f811fc8d71f4.png)

I am not able to figure this error. I will appreciate any help with this.

I have also tried subsetting the three components out- the expression-metadata, cell_metadata and gene_metadata from the Seurat object and creating a cds object on Monocle 3 with the following code
expression_data <- whole_dataset_s[["RNA"]]@counts
cell_metadata <-  whole_dataset_s@meta.data
gene_metadata <- rownames(whole_dataset_s)
cds <- new_cell_data_set(expression_data,
                         cell_metadata = cell_metadata,
                         gene_metadata = gene_metadata)

But getting the following error-
Error: assert_that: length of assertion is not 1
5.stop("assert_that: length of assertion is not 1", call. = FALSE)
4.check_result(res)
3.see_if(..., env = env, msg = msg)
2.assertthat::assert_that(nrow(gene_metadata) == nrow(expression_data), msg = paste("gene_metadata must be NULL or have", "the same number of rows as rows", "in expression_data"))
1.new_cell_data_set(expression_data, cell_metadata = cell_metadata, gene_metadata = gene_metadata)

Any suggestions with either of these.

Thank you

**Comment by mojaveazure** [comment]
Can you provide a copy of the dataset, or a subset of the dataset that reproduces the bug? You can email me at phoffman@nygenome.org

**Comment by yulchen810** [comment]
Hi,
I have the same issue as you raised here.

This is the code and Error
> cds <- new_cell_data_set(Astrocyte@assays$RNA@counts,
+                          cell_metadata = Astrocyte@meta.data, 
+                          gene_metadata = rownames(Astrocyte[["RNA"]]))
Error: assert_that: length of assertion is not 1

 I'd like to know how you fixed that problem. Thank you very much.
Best

**Comment by apal6** [comment]
Hi 

I have the same error, how did you fix it? 

Thank you!
