### ISSUE TITLE
Top genes based on p_val_adj returns gives genes based on p_values

### ISSUE THREAD

**Issue by neelanjanvishnu** [satijalab/seurat#3182]
Hi Seurat team,
When I try to perform 
Seurat_obj.markers <- FindAllMarkers(Seurat_obj, min.pct = 0.25, logfc.threshold = 0.25)
top10 <- Seurat_obj.markers %>% group_by(cluster) %>% top_n(n = 10, wt = p_val_adj)
The top 10 genes I get are listed based on their p_values, but not on the basis of their adjusted p_values.
Is it possible to generate Seurat heatmap based on highest differentially expressed genes (lowest p_val_adj) and highest fold changes?

Thanks,
Neel

**Comment by timoast** [comment]
The Bonferroni multiple testing correction does not change the relative order of p-values, so ordering by p-value or adjusted p-value will give the same order.
