### ISSUE TITLE
Cannot install seurat v3.2 for spatial vignette

### ISSUE THREAD

**Issue by JoyOtten** [satijalab/seurat#3184]
Hi,

It seems that Seurat v3.2 can't be download anymore. I got this error:
> devtools::install_github("satijalab/seurat", ref = "spatial")
Downloading GitHub repo satijalab/seurat@spatial
✓  checking for file ‘/tmp/RtmpRe3vwT/remotesc066602ac4eb/satijalab-seurat-f4c5aa7/DESCRIPTION’ (998ms)
─  preparing ‘Seurat’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘Seurat_3.1.5.9900.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'

Instead of getting Seurat 3.2. I now get Seurat_3.1.5 and therefore I can't work anymore with the ST dataset. How could I fix this problem and are more people having this problem? It seems that it worked fine last week.

Thanks,
Joy

**Comment by mojaveazure** [comment]
Seurat versions in the 3.1.5.99XX range are the latest development versions of Seurat with spatial support. We've had bug fixes in the forms of Seurat 3.1.3, 3.1.4, and 3.1.5, with the spatial support being the development versions in the .99XX series (eg. Seurat spatial for 3.1.4 was 3.1.4.99XX). Once Seurat's spatial functions are rolled into the mainline codebase and released to CRAN, the version will jump to 3.2.0 (a version that indicates major functionality changes compared to the 3.1.X series). If you're using Seurat 3.1.5.9900, you should have full spatial functionality as it is (an all other Seurat versions in the 3.1.X.99XX series are) the beta for Seurat's spatial support.
