### ISSUE TITLE
wildcard support?

### ISSUE THREAD

**Issue by LuoJulia** [satijalab/seurat#3185]
Hi, I was just wondering if wildcards are supported in Seurat? For example, when selecting gene names for the features parameter in the DotPlot function. 
Perhaps something like `features=c("DNAJ*","HSPA5")`
Thanks!

**Comment by satijalab** [comment]
This is an interesting idea. One concern is that we might have feature names that include asterisks, or other regex symbols (for example, some HLA alleles contain an asterisk). We'll explore a bit, and if anyone has ideas on how to overcome this problem - please feel free to comment here

**Comment by tomashhurst** [comment]
This is a cool idea. We do something like this with our cytometry analysis workflows, but we usually don't have asterisks in the names to contend with. Probably easiest to create the vector of these gene names separately (i.e. not within the DotPlot function), as it can then be customised to work around the presence of an asterisk etc. That way once you have a vector of the desired genes, you can just provide that to DotPlot, without having to modify the function. I'll give it a shot with gene names when I get a chance.

**Comment by rsatija** [comment]
closing this as we decided not to support in the end due to this complexity.
