### ISSUE TITLE
Error with RenameCells and Merge after subsetting cells

### ISSUE THREAD

**Issue by Victor21v** [satijalab/seurat#3187]
I am unable to merge two datasets which at least share one cell ID. Merge function tries to change the names of the cell IDs, but anyway I get a "invalid 'row.names' length" error. If I merge two subsets with any common cell, I can merge the subsets.

One possible solution would be to rename the cells using RenameCell function, but I get the same error when I try to change the cell names for one subset which doesn't happen when I use that function on the whole dataset.

As an example, I create two subsets from the same SeuratObject:
sample_1_s<-subset(SeuratObject, subset= Phase=="S")[, sample(colnames(subset(SeuratObject, subset= Phase=="S")), size = 1000, replace=F)]
sample_2_s<-subset(SeuratObject, subset= Phase=="S")[, sample(colnames(subset(SeuratObject, subset= Phase=="S")), size = 1000, replace=F)]

When I try to rename the cells, I get the following error:

`RenameCells(sample_2_s,add.cell.id = "Sample-2")`
Error in `.rowNamesDF<-`(x, value = value): invalid 'row.names' length
Traceback:

1. RenameCells(sample_1_s, add.cell.id = "Sample_1")
2. RenameCells.Seurat(sample_1_s, add.cell.id = "Sample_1")
3. RenameCells(object = object[[assay]], new.names = new.cell.names)
4. RenameCells.Assay(object = object[[assay]], new.names = new.cell.names)
5. suppressWarnings(rownames(x = Misc(object = object, slot = "vst.out")$cell_attr) <- new.names)
6. withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
7. `rownames<-`(x = `*tmp*`, value = new.names)
8. `row.names<-`(`*tmp*`, value = value)
9. `row.names<-.data.frame`(`*tmp*`, value = value)
10. `.rowNamesDF<-`(x, value = value)
11. stop("invalid 'row.names' length")

As you can see, I have subsetted sampling the cells and getting 1000. If I try to merge the subsets, I get the same error. However, if I set my samples to 50 cells, I don't get the error on the merge function but I still cannot rename the cells from the subsets.

**Comment by yuhanH** [comment]
It seems that your data is SCT normalized. 
Could you please update your package to the latest develop version and re-run SCT. This bug should be solved. 
If still not work, I will reopen this issue.

**Comment by Victor21v** [comment]
How can I install the develop version? Can I do that with standard install.packages()? Using that function I have 3.1.5 version and the problem isn't still solved with that version.

Anyway, I can confirm you that is because of the SCT assay, since if I remove it and keep only the RNA slot, I can merge or rename cells properly. However, I can also tell you that if I try to rename the cells of the whole dataset without subsetting it and containing the SCT assay, I can do that without any problems. In short:

- Whole dataset: no problems using RenameCells. I can't try merge function on the whole dataset since I don't have enough computational power.
-Subsetted datasets: If I do a subset of cells, RenameCells doesn't work. If any cell ID in common between the two subsets to merge, it won't work. After deleting SCT assay from the dataset, RenameCells and merge function work perfectly.

**Comment by mojaveazure** [comment]
To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by Victor21v** [comment]
Thanks! The issue is completely fixed on the development version.
