### ISSUE TITLE
exporting normalized data

### ISSUE THREAD

**Issue by Xcubitor** [satijalab/seurat#319]
Is there a way to export the normalized expression data as a table? I can do that with scaled.data and of course raw.data but not the normalized data.

**Comment by leonfodoulian** [comment]
Hi,

The matrix in the `object@data` slot is a sparse matrix (i.e. `dgCMatrix`). You can export it as:

```R
as.matrix(object@data)
```

Best,
Leon

**Comment by Xcubitor** [comment]
Super! thanks Leon!

**Comment by DiracZhu1998** [comment]
Dear Seurat developer, 
Is there a way I can import a normalized data (a matrix earlier normalized by Seurat::NormalizeData followed by Seurat::ScaleData) to R and change it into a Seurat object?
Thanks a lot !
