### ISSUE TITLE
Spin off SNN, clustering into separate package?

### ISSUE THREAD

**Issue by willtownes** [satijalab/seurat#3190]
Seurat is a great tool but requires a large number of dependencies which can complicate installation. Some of the functionality such as the shared nearest neighbors (SNN) graph construction and potentially some of the clustering implementations may be of interest to folks who don't need all the single cell specific functionality. Would you all consider splitting off the SNN and/or clustering components into a separate package to enable it to be used for other applications without having to import the entirety of Seurat?

**Comment by satijalab** [comment]
Hi will- thanks for the feedback. Its true that there's a lot of functionality, and we are looking into splitting some parts off - though I'm not sure we'll do it for SNN clustering. Importantly, we'll make sure this is done in a way that doesn't break any existing code of workflows.
