### ISSUE TITLE
perform integration to find DEG between conditions of a single experiment

### ISSUE THREAD

**Issue by liqian-ma** [satijalab/seurat#3191]
This Vignette (https://satijalab.org/seurat/v3.1/immune_alignment.html) demonstrated the analysis of 2 different conditions in order to detect DEGs between conditions within the same clusters. In this case, the data were generated in two different runs. Is integration still a necessary step if the single-cell data of multiple treatment conditions were generated in one run?

Thank you very much for your help!

**Comment by yuhanH** [comment]
Hi, 
It depends how different cells from  multiple conditions are. Integration step is to call the common cell type across different conditions, and help you compare treatment effect for two similar cell types.
