### ISSUE TITLE
Error using latent.vars to regress out gender with MAST DE test

### ISSUE THREAD

**Issue by rtvest** [satijalab/seurat#3193]
I am analyzing 10x single nuclei RNAseq of human brain. I have added gender to the metadata with M or F as the values. However, when I attempt to do DE testing I'm getting an error.

`BEC_DEGs_All <- FindMarkers(HuVascAD.integrated.rPCA_DEG, ident.1 = c("2_AD","4_AD","5_AD"), ident.2 = c("2_Control","4_Control","5_Control"), verbose = T, latent.vars = "gender", test.use = "MAST)`

I get the following error when I run this

> Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric

When I run the code with wilcox test, I get a progress bar for regressing out gender, but it isn't incorporated since wilcox isn't compatible with latent.vars. I can also run the code with the poisson test, but I read this is incompatible with integrated objects.

`BEC_DEGs_All <- FindMarkers(HuVascAD.integrated.rPCA_DEG, ident.1 = c("2_AD","4_AD","5_AD"), ident.2 = c("2_Control","4_Control","5_Control"), verbose = T, latent.vars = "gender")`

> Warning: 'latent.vars' is only used for 'negbinom', 'poisson', 'LR', and 'MAST' tests
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 23s

Running the MAST DE test without latent.vars works just fine. Any ideas for what's going on?

**Comment by satijalab** [comment]
Thanks for posting this, we can took a look.

Before we do, can you confirm that the error persists if you have test.use = "MAST" (you are missing a quotation mark at the end)

**Comment by rtvest** [comment]
Oh my bad - that was just a mistake in copying the code over. Yes the error persists.

**Comment by jaisonj708** [comment]
It looks like MAST does not support regression of categorical variables, but it should work if you convert it to a numerical one (e.g, M as 0, F as 1)
