### ISSUE TITLE
cannot Install Seurat

### ISSUE THREAD

**Issue by rubenferrer** [satijalab/seurat#3195]
Hi, I am trying to install Seurat on R Studio and keep getting this message:

Fehler: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 kann shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so, 6): Symbol not found: _inflateValidate
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libz.1.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so

How could I solve this?

**Comment by timoast** [comment]
Try re-installing `png`

**Comment by rubenferrer** [comment]
It didn´t work

**Comment by timoast** [comment]
The error message indicates that you can't load the shared object for the png package, so you need to re-install it. If there are similar errors for other package, you need to do the same for those packages also
