### ISSUE TITLE
Warning messages with CreateSeuratObject

### ISSUE THREAD

**Issue by rachel662** [satijalab/seurat#3196]
Hi, 
I have downloaded a dataset of scRNA-seq data from GEO (counts and metadata file) and they look fine when I read them into R with read.delim (for counts) and read_xlsx (for metadata). However when i create a seurat object i get these warning messages? would anyone be able to explain them to me? (i've put the code and warning messages below 

code

#load counts and metadata files
counts <- read.delim("GSE112903_uninf_lcmv_genesVcells (1).txt", sep = "\t")
metadata <- readxl::read_xlsx("GSE112903_uninf_lcmv_metadata (1).xlsx")

#View metadata and counts files
View(counts)
View(metadata)

#create seurat object 
seurat <- CreateSeuratObject(counts = counts, min.cells = 3, min.features = 200, meta.data = metadata)

here are the warning messages

> seurat <- CreateSeuratObject(counts = counts, min.cells = 3, min.features = 200, meta.data = metadata)
Warning: Invalid name supplied, making object name syntactically valid. New object name is BarcodenGenenUMIorig.identpercent.mitopercent.rpsres.0.5protocolvar.ratio.pcaCC.labelCC.label.protocol; see ?make.names for more details on syntax validity
Warning message:
In CreateSeuratObject(counts = counts, min.cells = 3, min.features = 200,  :
  Some cells in meta.data not present in provided counts matrix.

**Comment by timoast** [comment]
This might be related to your overwriting of the `seurat` class by assigning the object to the variable name `seurat`. Does the same warning occur if you choose a different name?

**Comment by rachel662** [comment]
Hi, I get the same warning even if I use a different name

**Comment by timoast** [comment]
This works for me:

```r
library(Seurat)

counts <- read.delim("~/Downloads/GSE112903_uninf_lcmv_genesVcells.txt.gz", sep = "\t", check.names = FALSE)
metadata <- readxl::read_xlsx("~/Downloads/GSE112903_uninf_lcmv_metadata.xlsx")

metadata <- as.data.frame(metadata)
rownames(metadata) <- metadata$Barcode

obj <- CreateSeuratObject(counts = counts, min.cells = 3, min.features = 200, meta.data = metadata)
```

**Comment by rachel662** [comment]
Hi, this has got rid of the some cells in the meta.data are not present in the provided count matrix warning however i still get the one below  

Warning: Invalid name supplied, making object name syntactically valid. New object name is BarcodenGenenUMIorig.identpercent.mitopercent.rpsres.0.5protocolvar.ratio.pcaCC.labelCC.label.protocol; see ?make.names for more details on syntax validity

**Comment by wfma** [comment]
@rachel662 i got similar error while importing a dataset from from exprMatrix.tsv.gz and a meta.tsv file. I followed @timoast code and although it threw the same error my metadata is now working properly and under the seurat obj it shows the corresponding columns filled rather than NAs if I didnt transform it into a data.frame
