### ISSUE TITLE
Is it possible to determine if cells are clustered by samples and not by cell types using Seurat?

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#3197]
I am analyzing single-cell RNA-Seq data from 10x platform using Seurat.

I have couple of questions:

1) Is it possible to determine if cells are clustered by samples and not by cell types using Seurat. Which Seurat function can I use for this analysis?

2) If there is any simple tool available to remove this effect.

Thank you.

**Comment by timoast** [comment]
1. You can examine visually the distribution of cells originating from each sample in each cluster, or you can compute the proportion of each sample in each cluster. There is no function in seurat to do this, but you can do it easily with standard R functions (eg, `table(obj$sample, obj$cluster)`)
2. See the integration methods in Seurat

**Comment by singcell** [comment]
@timoast Thank you!
