### ISSUE TITLE
Integration error:  The following n features do not exist in all SCT models

### ISSUE THREAD

**Issue by akramdi** [satijalab/seurat#3198]
Hello everyone, 

I have 14 samples that I wish to integrate. 2 of these samples result from  a merge (performed SCTransform on each, then merged using `merge` command). 

Here's how samples were merged: 

```
> packageVersion("Seurat")
[1] ‘3.1.5’

sobj <- merge(sobj1, y = sobj2, add.cell.ids = c("S1", "S2"), project = mergedSampleName, merge.data = T)
#set variable features - otherwise the object has 0 variable features
VariableFeatures(sobj[["SCT"]]) <- rownames(sobj[["SCT"]]@scale.data)
```

However, once at the integration step, I get this error:

```
features=3000
features <- SelectIntegrationFeatures(sobj.list, nfeatures = features)
sobj.list <- PrepSCTIntegration(sobj.list, anchor.features = features, verbose = FALSE)

Error in scale.data[anchor.features, ] : subscript out of bounds
In addition: Warning messages:
1: In GetResidual(object = object.list[[i]], features = anchor.features,  :
  The following 30 features do not exist in all SCT models: MIR29B2CHG DOCK6 ABCC8 CYP46A1 ADCY1 SERHL2 ATCAY CXXC5 PCDHB10 AC008467.1 ....

```
I think this is due to the structure of merged samples (the error does not occur when merged samples are excluded), plus, the same behaviour was reported in another issue  _Originally posted by @dagarfield in https://github.com/satijalab/seurat/issues/1739#issuecomment-581442788_ 

Can anyone help me figure this out ? How can I make the integration run properly with these samples ?
Many thanks,

**Comment by yuhanH** [comment]
Hi, 
In your case, you don't need to merge tow objects. 
You can make a object list directly: `sobj.list <- list(sobj1, sobj2 )`, and then continue to do the integration.

**Comment by akramdi** [comment]
I think you misread my question. 
I do provide a list of objects  `sobj.list` for the integration . However, when the list contains an object resulting from a merge (let's say `sobj1` is a result of a merge; `sobj2`  is a typical individual sample), the integration cannot complete successfully (see error above).

Are merged objects  not meant to be used for integrations?

**Comment by yuhanH** [comment]
OK. Get it.  For the merged object, the SCT model parameters cannot be merged. 
One option is to run SCT again for the merged object.

**Comment by akramdi** [comment]
Ok that explains the error. Thank you.
