### ISSUE TITLE
How to extract cells expressing some genes from a certain Cluster for FindMarkers.

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#3199]
Hi, 
Seurat is a good tool for single-cell sequencing. But how do I extract cells that express one gene (eg.  MS4A1)and compare them with other groups. Crucially, these cells are not a specific cluster, but scattered in whole cell atlas. I sincerely hope to get your help. 
Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Please see the Seurat manual for the `subset` function.  I believe what you are looking for is the same as one of the examples from the manual:
`subset(x = pbmc_small, subset = MS4A1 > **CHOSE YOUR VALUE HERE**)`

Best,
Sam
