### ISSUE TITLE
Issue with an error in "FindAllMarkers" under certain conditions

### ISSUE THREAD

**Issue by alexgraehl** [satijalab/seurat#32]
I think this happens when only TWO clusters are identified from the data, but I haven't completely tracked it down.

The error is as follows:

     pos.markers <- Seurat::FindAllMarkers(r.dat, genes.use=r.dat@var.genes, only.pos=TRUE , min.pct=0.25, thresh.use=0.25, test.use="tobit", do.print=FALSE)

     Error in eval(expr, envir, enclos) : object 'avg_diff' not found

My guess is that this is related to the fact that while there are several checks for "is.null(...)" for gde and other objects, in this case, it's a data frame with no rows, but it isn't actually null. Maybe!

Browse[2]> gde
[1] p_val    avg_diff pct.1    pct.2   
<0 rows> (or 0-length row.names)

**Browse[2]> is.null(gde)
[1] FALSE**

I apologize for not having a more informative test case! It only happens in a small subset of my input data files, which are extremely large and inconvenient to test in stripped-down example form.

Note that the number of cells in each of the two input clusters is > 2000—I verified that there aren't any zero-size clusters, which is a problem I had been encountering previously.

    > system.time(pos.markers <- Seurat::FindAllMarkers(r.dat, genes.use=r.dat@var.genes, only.pos=TRUE , min.pct=0.25, thresh.use=0.25, test.use="tobit", do.print=FALSE))
    Error in eval(expr, envir, enclos) : object 'avg_diff' not found
    In addition: Warning messages:
    1: In is.na(p_val) :
      is.na() applied to non-(list or vector) of type 'NULL'
    2: In is.na(p_val) :
      is.na() applied to non-(list or vector) of type 'NULL'

    Enter a frame number, or 0 to exit   

    1: system.time(pos.markers <- Seurat::FindAllMarkers(r.dat, genes.use = r.dat@var.genes, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25, test.use = "tobit", do.print = FALSE
    2: Seurat::FindAllMarkers(r.dat, genes.use = r.dat@var.genes, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25, test.use = "tobit", do.print = FALSE)
    3: Seurat::FindAllMarkers(r.dat, genes.use = r.dat@var.genes, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25, test.use = "tobit", do.print = FALSE)
    4: subset(gde.all, avg_diff > 0)
    5: subset.data.frame(gde.all, avg_diff > 0)
    6: eval(e, x, parent.frame())
    7: eval(expr, envir, enclos)

**Comment by andrewwbutler** [comment]
It's a bit hard to say without a reproducible example but it's possible that with the parameters you've set, there are no marker genes. Try lowering you threshold cutoff (thresh.use) and see if that returns some genes.

**Comment by alexgraehl** [comment]
Thanks! That seems to have solved it!
