### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by glin32** [satijalab/seurat#320]
Hi, all

I have been trying to install Seurat with this error (didnt see this anywhere else, apologies if I had missed it). Am I missing something or another package?

> install.packages("Seurat")

  There is a binary version available but the source version
  is later:
       binary source needs_compilation
Seurat  2.2.0  2.2.1              TRUE

Do you want to install from sources the package which needs compilation?
y/n: y
installing the source package ‘Seurat’

trying URL 'https://cran.rstudio.com/src/contrib/Seurat_2.2.1.tar.gz'
Content type 'application/x-gzip' length 831227 bytes (811 KB)
==================================================
downloaded 811 KB

* installing *source* package ‘Seurat’ ...
** package ‘Seurat’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘Seurat’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Seurat’
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/lq/jk194j6915b6x551w8s6spvw0000gn/T/RtmpI9CMeK/downloaded_packages’
> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree

**Comment by andrewwbutler** [comment]
Hi,

It looks like you tried to install in the window between when we initially submitted out patch release and when the mac binaries finished building. These are finished now which should allow for an easier install if you try again.

**Comment by glin32** [comment]
Worked! Great thanks!
