### ISSUE TITLE
How to filter genes？

### ISSUE THREAD

**Issue by MMriran** [satijalab/seurat#3200]
Hi Seurat Team

     Thank you for your great tools！ I have a question :
After pca and tsne or umap analysis, how can I remove some genes from the seurat object？（ there is a “subsetdata” function in seurat package to select the cells, and is there some functions  that like “subsetdata” we can used to select the genes？ ）

Thanks!
MMrian

**Comment by timoast** [comment]
Please see the [subset](https://rdrr.io/cran/Seurat/man/subset.Seurat.html) function
