### ISSUE TITLE
remove duplicates in Seurat 3.1.5

### ISSUE THREAD

**Issue by yeroslaviz** [satijalab/seurat#3201]
Hi,

when running `RunTSNE` I'm getting the error message 

```
> e18 <- RunTSNE(e18)
Error in Rtsne.default(X = object, dims = dim.embed, ...) : 
  Remove duplicates before running TSNE.
```

But there is no parameter to check for duplications any more (or not).

Any idea how to run T-SNE?

thanks
Assa

**Comment by andrewwbutler** [comment]
Hi,

You can pass extra parameters through the `...` to the `Rtsne` call itself. E.g.

```R
RunTSNE(e18, check_duplicates = FALSE)
```
