### ISSUE TITLE
Combine clusters

### ISSUE THREAD

**Issue by Aitor91** [satijalab/seurat#3202]
Hello all,

I have a question for you. I have clusterized and done the analysis with Seurat. The results are great, so thank you for your excellent work.
However, I hope you can help me with a doubt that I have. I have 17 clusters named with each corresponding cell population's names, but I would like to combine 4 different subpopulations of monocytes in just one. The reason is that we are studying T cell subpopulations, so I do not what to distract the reader with monocytes.

I know that adjusting the resolution you can reduce or increase the cluster numbers, but can we combine clusters once the clustering is done?

Thank you again for your help and work.

Aitor

**Comment by samuel-marsh** [comment]
Hi Aitor,

Please see this vignette with the section on renaming clusters: [https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html).  Just use the same new name for each of the clusters you want to combine.

Best,
Sam

**Comment by Aitor91** [comment]
Done. Perfect. Thank you very much. I really appreciate it.

Aitor
