### ISSUE TITLE
How do I set identity to use Funcion (FindMarkers) based on user requests?

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#3204]
Hi,
Thanks for your answer to my previous question.  But maybe I didn't express my question clearly, you misunderstood my meaning.  My question is about "cluster5.markers <- **FindMarkers**(pbmc, **ident.1** = 5, **ident.2** =  3, min.pct = 0.25)".

For example, I mainly want to extract NK cells in pbmc expressing A genes(Maybe the gene is CST7 ) as **ident.1**.  Meanwhile, NK cells that do not express A genes act as **ident.2**. I want to use FindMarkers function to compare difference of those.  So, Can you help me with this problem.

I sincerely hope to get your help.

**Comment by jaisonj708** [comment]
Thanks for the clarification. Here's a solution for the example you posed:

1) Add positive expression of CST7 as a metadata feature: `obj <- AddMetaData(obj, metadata = FetchData(obj, 'CST7')>0, col.name = 'CST7pos')`

2) Then: `FindMarkers(obj, ident.1 = T, ident.2 = F, subset.ident = "NK", group.by = "CST7pos")`
