### ISSUE TITLE
Percent_mito is a flat line at zero

### ISSUE THREAD

**Issue by Aanchal85** [satijalab/seurat#3205]
I have a dataset that I am trying to analyse. So during the check mitochondrial content there is no violin plot generated for percent_mt but instead a flat line at zero.

![image](https://user-images.githubusercontent.com/61064514/86080517-167b6100-ba61-11ea-828c-4535d046e6d2.png)

Could you suggest what is wrong?

**Comment by KLlaing** [comment]
Hello, not a dev, but I had the same issue. 
I fixed it by replacing ^MT- in the code with ^mt-
In our case, I think its because zebrafish genes are formatted differently.
Hope it works for you.

**Comment by andrewwbutler** [comment]
Agreed. This will happen when none of the features in your dataset match the pattern provided  in `PercentageFeatureSet`. You likely need to change what is passed to the `pattern` parameter to fit your specific system/dataset.
