### ISSUE TITLE
PlotClusterTree  branch length problem~

### ISSUE THREAD

**Issue by Isaac861105** [satijalab/seurat#3206]
Hi:
  After I'm used BuildClusterTree in Seurat package to plot my data, the cluster tree branch length is too short like the example below: 
![Phylogenetic Analysis of Identity Classes](https://user-images.githubusercontent.com/67620171/86083181-211f1000-bacc-11ea-9189-2c92fc5f9acd.png)

The code that i use to plot this cluster tree is:
sample<-BuildClusterTree(sample)
Tool(object = sample, slot = 'BuildClusterTree')
PlotClusterTree(sample)

So, how can i change the branch length in PlotClusterTree?
Thank you for your kindly helping!

**Comment by timoast** [comment]
The branch lengths in the dendrogram correspond to the distance between cluster centroids in the PC space, so there's no parameter to change them. Very short branch lengths indicate that the clusters are very similar. If they're too small to view properly, I'd suggest increasing the size of the plot.
