### ISSUE TITLE
Integration Workflow

### ISSUE THREAD

**Issue by shefalipatel7** [satijalab/seurat#3207]
Hi,

Thank you for your great package. I had a quick question regarding the integration workflows and wanted to clarify, is there a minimal number of cells/matrix size that you need to have in order to perform integration? I know it works well with larger datasets, but I am trying to integrate some of my other subsets of cells and I'm having a hard time because when I use SplitObject, some of the matrices are very small (~10 cells).

In scenarios like these, what would you suggest to correct batch effects if integration cannot be performed? 

Thank you.

**Comment by timoast** [comment]
Yes, there is a minimum number of cells needed. Any of the k nearest neighbor-based methods won't work when k is not much smaller than the total number of cells in the dataset. For Seurat, this includes the integration methods, tSNE, UMAP, and clustering. You could try to get around this by merging the very small datasets into another dataset, or excluding them.
