### ISSUE TITLE
 Error in LogNorm

### ISSUE THREAD

**Issue by July233** [satijalab/seurat#3208]
when  I run this code:
my <- NormalizeData(my,normalization.method = "LogNormalize", scale.factor = 10000)

Error in LogNorm(data, scale_factor = scale.factor, display_progress = verbose) : 
  std::bad_alloc

Seurat3.0

**Comment by jaisonj708** [comment]
It seems like you don't enough memory available for the command. You can try removing unneeded objects from your R workspace.
