### ISSUE TITLE
Read10X_h5 from a file connection

### ISSUE THREAD

**Issue by vtosevski** [satijalab/seurat#3209]
Dear Seurat team,

I was wondering if it's possible to initialize seurat object from the file connection (CellRanger pipeline output is in the online repository accessible through API)? `Matrix::ReadMM` supports reading from connection objects and it used to be possible to read in the .mtx file, but now that is not straightforward anymore (as the files are .mtx.gz coming out of the cell ranger). `Seurat::Read10X_h5` function does not seem to support reading from a connection - is that correct? What other options do I have?

Thanks,
Vinko

**Comment by mojaveazure** [comment]
Hi Vinko,

`Read10X_h5` utilizes [hdf5r](https://hhoeflin.github.io/hdf5r/index.html) as the backend for reading data from an HDF5 file. I don't believe that hdf5r has the ability to read from a remote HDF5 file; if it doesn't, please feel free to file a feature request with the [hdf5r developers](https://github.com/hhoeflin/hdf5r). In the meantime, I'm afraid you'll have to download a local copy of the 10X HDF5 file and read from that.
