### ISSUE TITLE
How to subset on genes and preserve idents?

### ISSUE THREAD

**Issue by mkarikom** [satijalab/seurat#321]
A seurat object has been created and the usual SNN clustering pipeline steps are applied: NormalizeData, FindVariableGenes, ScaleData, RunPCA, FindClusters().  

StashIdent() has been used to preserve idents for interesting parameterizations of the embedding step.

Now it is necessary to analyze the cells again, but only on a subset of the genes.  Also, I need to retain access to the cell idents stored in the previous analysis.  What is the recommended way to do this?

Initially I tried: <seurat object>@raw.data <- <subset of the old matrix used in CreateSeuratObject()>, then re-running the entire pipeline, but this seems to be failing

**Comment by mojaveazure** [comment]
Hi Matt,

To subset on genes, you'll need to create a new Seurat object. Take your subset matrix and pass that to `CreateSeuratObject` for a new object. If you want to preserve idents, you can pull the ident column from the `meta.data` slot, use `AddMetaData` to add the idents to the new Seurat object, and use `SetAllIdent` to assign the identities.

For example,

```R
subset.matrix <- object1@raw.data[genes.use, ] # Pull the raw expression matrix from the original Seurat object containing only the genes of interest
object2 <- CreateSeuratObject(subset.matrix) # Create a new Seurat object with just the genes of interest
orig.ident <- object1@meta.data[, ident.use] # Pull the identities from the original Seurat object as a data.frame
object2 <- AddMetaData(object = object2, metadata = orig.ident) # Add the idents to the meta.data slot
object2 <- SetAllIdent(object = object2, id = ident.use) # Assign identities for the new Seurat object
```

Alternatively, you can use `TransferIdent` from the development version of Seurat; installation instruction are available [here](http://satijalab.org/seurat/devinstall.html)

**Comment by kathyushakov** [comment]
Hi,

Can you please also explain what is the difference between `StashIdent` and `SetAllIdent`?

Thanks!
Kathy

**Comment by satijalab** [comment]
You can use ?StashIdent for the package documentation. StashIdent saves the current cell identities for later retrieval, but does not change the identity. SetAllIdent sets the cell identities to a column from the object meta data.
