### ISSUE TITLE
Integrate three 10x scATAC samples problems

### ISSUE THREAD

**Issue by liuxuesunny** [satijalab/seurat#3210]
Hi There,
I am trying to integrate three 10x scATAC samples by harmony following the Vignettes, but after integration and running FindNeighbors and FindClusters, the clusters were not well separated and cells from different clusters (color labelled) joined each like the image below. I also attached the code below. Also, there was always a NA sample/cluster in there. A newbie needs help. Thanks.

![umap_E17_5_lutr](https://user-images.githubusercontent.com/67670176/86199087-0b323f00-bb0e-11ea-98bd-7b2bdd98bac4.jpg)

load("E17_5_7_lutr.rds")
load("E17_5_8_lutr.rds")
load("E17_5_9_lutr.rds")

E17_5_7_lutr$tech <- 'E17_5_7_lutr'
E17_5_7_lutr$celltype <- Idents(E17_5_7_lutr)

E17_5_8_lutr$tech <- 'E17_5_8_lutr'
E17_5_8_lutr$celltype <- Idents(E17_5_8_lutr)

E17_5_9_lutr$tech <- 'E17_5_9_lutr'
E17_5_9_lutr$celltype <- Idents(E17_5_9_lutr)

intersecting.regions <- GetIntersectingFeatures(
object.1 = E17_5_7_lutr,
object.2 = E17_5_8_lutr,
sep.1 = c(":", "-"),
sep.2 = c(":", "-")
)
peaks.use <- sample(intersecting.regions[[1]], size = 10000, replace = FALSE)

intersecting.regions <- GetIntersectingFeatures(
object.1 = unintegrated1_2,
object.2 = E17_5_9_lutr,
sep.1 = c(":", "-"),
sep.2 = c(":", "-")
)
peaks.use <- sample(intersecting.regions[[1]], size = 10000, replace = FALSE)

unintegrated12_3 <- MergeWithRegions(
object.1 = unintegrated1_2,
object.2 = E17_5_9_lutr,
assay.1 = 'peaks',
assay.2 = 'peaks',
sep.1 = c(":", "-"),
sep.2 = c(":", "-"),
)

unintegrated12_3 <- RunTFIDF(unintegrated12_3)
unintegrated12_3 <- FindTopFeatures(unintegrated12_3, min.cutoff = 50)
unintegrated12_3 <- RunSVD(unintegrated12_3, n = 30, reduction.name = 'lsi', reduction.key = 'LSI_')
unintegrated12_3 <- RunUMAP(unintegrated12_3, reduction = 'lsi', dims = 2:30, min.dist = 0.8)
DimPlot(unintegrated12_3, pt.size = 1.0) + ggplot2::ggtitle("Unintegrated")
DimPlot(unintegrated12_3, group.by = 'tech', pt.size = 1.0) + ggplot2::ggtitle("Unintegrated")
table(Idents(unintegrated12_3))

library(harmony)

E17_5_lutr <- RunHarmony(
object = unintegrated12_3,
group.by.vars = 'tech',
reduction = 'lsi',
assay.use = 'peaks',
project.dim = FALSE
)

E17_5_lutr <- RunUMAP(E17_5_lutr, dims = 2:30, reduction = 'harmony', min.dist = 0.8)
E17_5_lutr <- FindNeighbors(
E17_5_lutr,
reduction = 'harmony',
dims = 2:30
)
E17_5_lutr <- FindClusters(
E17_5_lutr,
algorithm = 3,
resolution = 1.3,
verbose = T
)
DimPlot(E17_5_lutr, pt.size = 1.0, label = T)

**Comment by timoast** [comment]
It's not clear from the code what's happening here (eg, unintegrated1_2 is not defined), so it's hard to say exactly what the issue is but my guess would be that the UMAP and clustering are not being computed from the same thing. I'd recommend re-starting your R session and running the code again being careful to ensure that you use the "harmony" dimension reduction for both clustering and UMAP, and ensure that you're grouping cells by the correct cluster identities when creating the plot. If this doesn't solve the issue, please re-open with a reproducible example.
