### ISSUE TITLE
fastMNN and DoHeatmap

### ISSUE THREAD

**Issue by Kailewang** [satijalab/seurat#3211]
Hi,

I tried to integrated several different single cell RNA-seq datasets using the wrapper of fastMNN in Seurat following the tutorial (https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/fast_mnn.html), I noticed there is no ScaleData step in the tutorial, does this mean fastMNN don't need to use the scaled data? 

However, when I try to plot the heatmap using DoHeatmap, I got the following error "Error in GetAssayData(object = object, slot = "scale.data")[genelist,  :  no 'dimnames' attribute for array". DeHeatmap required the scale.data, any suggestion about this?  Could I just scale the data after RunFastMM to get the scale.data slot, then used it for DoHeatmap? Thanks.

**Comment by andrewwbutler** [comment]
Hi,

The input to `fastMNN` is log normalized data (stored in the `data` slot in Seurat). If you want to plot a heatmap, you'll either need to run `ScaleData` to generate the `scale.data` slot, or specify the `slot = "data"` parameter in `DoHeatmap`, depending on what you want to display in your heatmap.
