### ISSUE TITLE
Using RNA assay for Differential Expression

### ISSUE THREAD

**Issue by KLlaing** [satijalab/seurat#3212]
Hi,
Thank you for such a user-friendly package and ongoing support!
I am comparing two datasets (two different conditions, same cell type), and although I have used the Integration Vignette to drive clustering etc, I understand that I should use RNA assay when doing differential expression analysis. Do I therefore need to apply a form of batch correction to the RNA assay? Or is it valid to use no batch correction when doing differential expression analysis?

Thanks,

**Comment by timoast** [comment]
You should not perform differential expression on batch-corrected data, instead you can include batch as a latent variable in the DE test (see the documentation for FindMarkers)
