### ISSUE TITLE
Is there a recommended number of highly variable genes?

### ISSUE THREAD

**Issue by xihuiyin** [satijalab/seurat#3213]
So I'm looking at the guide and I was wondering if the number of selected highly variable genes would have a big influence on the clustering quality:

```
# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)
```

I'm working with myeloid cell samples, and they are generally similar in terms of gene expression. Is there a recommended range for number of highly variable genes in general, or for more similar cell clusters, e.g. 10-20? Is there a number I should not go above? I understand that improving the resolution fixes some of the issue, but it is unable to resolve all of my difficulties in clustering/identifying different immune cell types.

**Comment by samuel-marsh** [comment]
Hi,

Yes, selection of highly variable genes does play part in the clustering quality.  However, the code chunk you pasted is not the selection of the number of highly variable genes but merely the selection of the genes to plot the names for on the `VariableFeaturePlot`.

In the case of the vignette the number of variable genes is selected in the following code chunk:
`pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)`

As you state the number of variable genes is going to be highly dataset specific depending on the number of cell types present, treatments, genotypes, etc.  This is something that you can experiment with to find optimal setting for your dataset.  I also suggest reading the manual for `FindVariableFeatures` to see other options when selecting variable features.

Best,
Sam
