### ISSUE TITLE
Two questions about rename cluster and find markers

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#3214]
Hi，
Thanks for your ongoing support and patience. I have two questions about using Seurat.
1.**Rename Cluster**:  I have a Cluster named microglia, but I want to rename the cells that simultaneously express KI67,PTPRS and NESTIN in microglia to proliferate microglia. What should I do?

2.**Find all markers distinguishing part of cluster 5 from clusters 8**
**markers <- FindMarkers(pbmc, ident.1 = "Experiment", group.by = 'sample', subset.ident = "2", ident.2 = 8, min.pct = 0.25),**
I want to compare the cells belonging to the Experiment group in Cluster 2 with Cluster 8. But when I run this code, I get an error**"Error in WhichCells.Seurat(object = object, idents = ident.2) : Cannot find the following identities in the object: 8"**

I sincerely hope to receive your reply. Thanks.

**Comment by andrewwbutler** [comment]
Hi,

1. One way to do this is to specify your thresholds to `WhichCells` and pass that vector of cells names to `SetIdent`. E.g.
```R
microglia.cells <- WhichCells(object, expression = KI67 > X & PTPRS > Y & NESTIN > Z)
object <- SetIdent(object, cells = microglia.cells, value = "microglia")
```

2. If you want to compare cluster 2 with cluster 8, you should specify `ident.1 = 2` and `ident.2 = 8` in `FindMarkers`, not `subset.ident`.
