### ISSUE TITLE
merging, DE analysis and clustering after integrate the data

### ISSUE THREAD

**Issue by kinali** [satijalab/seurat#3215]
Dear all,

I am having a hard time grouping and analyzing my data properly. I have 9 samples. Mainly, I have 3 conditions from 3 patients. I am trying to use the same conditions as a replicate. To do so, I integrated 3 same conditions for one patient and I repeated this process for all.

So in the beginning I had a data like this:
patient1 - C1,C2,C3
patient2 - C1,C2,C3
patient3 - C1,C2,C3

Then I integrated the data like this since I want to use the conditions as replicates:
patient1 - C1, patient2 - C1, patient3 - C1
patient1 - C2, patient2 - C2, patient3 - C2
patient1 - C3, patient2 - C3, patient3 - C3
Now I want to find clusters and DE genes between specific clusters,

For that, is merging all these again without integrating

patient1 - C1, patient2 - C1, patient3 - C1
patient1 - C2, patient2 - C2, patient3 - C2
patient1 - C3, patient2 - C3, patient3 - C3

Then find the clusters for all of them, then calculating DE genes using “RNA” slot is a good approach?
If you could suggest anything how to process all for further analysis, I would be grateful.

**Comment by timoast** [comment]
I don't 100% follow what you're trying to do here, but using the "RNA" assay with patient as a latent variable in the DE test is a good approach.
