### ISSUE TITLE
Error while running SpatialDimPlot(obj, interactive = TRUE)

### ISSUE THREAD

**Issue by sunkh1026** [satijalab/seurat#3216]
I've followed the [link](https://satijalab.org/seurat/v3.1/spatial_vignette.html) for analyzing 10X Visium data; however, it showed error as below. Please advise. Thanks!

`SpatialDimPlot(brain, interactive = TRUE)`
**Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments**

`sessionInfo()`
R version 3.6.1 (2019-07-05) 
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: CentOS Linux 7 (Core)  

locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         

attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       

other attached packages: [1] stxBrain.SeuratData_0.1.1 SeuratData_0.2.1          dplyr_1.0.0               patchwork_1.0.1           [5] ggplot2_3.3.2             Seurat_3.1.5.9900          

loaded via a namespace (and not attached):   [1] Rtsne_0.15            colorspace_1.4-1      deldir_0.1-25         ellipsis_0.3.1          [5] ggridges_0.5.2        rprojroot_1.3-2       fs_1.3.1              rstudioapi_0.11         [9] spatstat.data_1.4-3   farver_2.0.3          leiden_0.3.3          listenv_0.8.0          [13] remotes_2.1.1         ggrepel_0.8.2         RSpectra_0.16-0       fansi_0.4.1            [17] codetools_0.2-16      splines_3.6.1         polyclip_1.10-0       pkgload_1.1.0          [21] jsonlite_1.7.0        ica_1.0-2             cluster_2.1.0         png_0.1-7              [25] uwot_0.1.8            shiny_1.5.0           sctransform_0.2.1     compiler_3.6.1         [29] httr_1.4.1            backports_1.1.8       assertthat_0.2.1      Matrix_1.2-17          [33] fastmap_1.0.1         lazyeval_0.2.2        cli_2.0.2             later_1.1.0.1          [37] htmltools_0.5.0       prettyunits_1.1.1     tools_3.6.1           rsvd_1.0.3             [41] igraph_1.2.5          gtable_0.3.0          glue_1.4.1            RANN_2.6.1             [45] reshape2_1.4.4        rappdirs_0.3.1        Rcpp_1.0.4.6          spatstat_1.64-1        [49] vctrs_0.3.1           ape_5.4               nlme_3.1-144          lmtest_0.9-37          [53] stringr_1.4.0         globals_0.12.5        ps_1.3.3              testthat_2.3.2         [57] mime_0.9              miniUI_0.1.1.1        lifecycle_0.2.0       irlba_2.3.3            [61] devtools_2.3.0        goftest_1.2-2         future_1.17.0         MASS_7.3-51.4          [65] zoo_1.8-8             scales_1.1.1          promises_1.1.1        spatstat.utils_1.17-0  [69] parallel_3.6.1        RColorBrewer_1.1-2    curl_4.3              memoise_1.1.0          [73] reticulate_1.16       pbapply_1.4-2         gridExtra_2.3         rpart_4.1-15           [77] stringi_1.4.6         desc_1.2.0            pkgbuild_1.0.8        rlang_0.4.6            [81] pkgconfig_2.0.3       lattice_0.20-40       ROCR_1.0-11           purrr_0.3.4            [85] tensor_1.5            labeling_0.3          htmlwidgets_1.5.1     cowplot_1.0.0          [89] tidyselect_1.1.0      processx_3.4.2        RcppAnnoy_0.0.16      plyr_1.8.6             [93] magrittr_1.5          R6_2.4.1              generics_0.0.2        pillar_1.4.4           [97] withr_2.2.0           mgcv_1.8-28           fitdistrplus_1.1-1    survival_3.1-8        [101] abind_1.4-5           tibble_3.0.1          future.apply_1.6.0    crayon_1.3.4          [105] KernSmooth_2.23-15    plotly_4.9.2.1        usethis_1.6.1         grid_3.6.1            [109] data.table_1.12.8     callr_3.4.3           digest_0.6.25         xtable_1.8-4          [113] tidyr_1.1.0           httpuv_1.5.4          munsell_0.5.0         viridisLite_0.3.0     [117] sessioninfo_1.1.1

**Comment by dhtc** [comment]
I think it is caused by a minor mistake in https://github.com/satijalab/seurat/blob/72a0c7b61adcf1d6630db9e952bf8b0d4f979295/R/visualization.R#L2787. You can use ISpatialDimPlot and ISpatialFeaturePlot as substitute if you need interactive plot.

**Comment by andrewwbutler** [comment]
Thanks for reporting! This should be resolved now on the `develop` branch. For installation instructions, please see this [page](https://satijalab.org/seurat/install.html#development).
