### ISSUE TITLE
Downstream analysis after subsetting an already integrated object

### ISSUE THREAD

**Issue by younjung82** [satijalab/seurat#3217]
Hello Satija Team,

I have a question on downstream analysis after subsetting based on the clustering result.

I have 5 batches.
I first integrated all these 5 batches' data and did clustering.
After that, I subsetted the object to only include clusters of my interest and performed analyses such as DotPlot, Heatmaps, and DE analysis. My workflow is as below and I wonder if the workflow is correct. (especially step 6 and 7)

**1. Create 5 individual Seurat objects for the 5 batches. (named i.e. A, B, C, D, E)**
```
dataA <- CreateSeuratObject(count = A, min.cells = 3, min.features = 200)
dataA$line <- "line A"
dataA <- subset(x = A, subset=nFeature_RNA>200 & nFeature_RNA < 3000 & percent.mt < 10)
dataA <- NormalizeData(dataA)
dataA <- FindVariableFeatures(dataA)
```

> same on other batches. So I have dataA, dataB, dataC, dataD, and dataE ready.

**2. Integration of the 5 Seurat objects and ScaleData**

```
data.anchors <- FindIntegrationAnchors(object.list = list(dataA, dataB, dataC, dataD, dataE), dims = 1:30)
data.integrated <- IntegrateData(anchorset = data.anchors, dims = 1:30)
DefaultAssay(data.integrated) <- "integrated"
data.integrated <- ScaleData(data.integrated)
```

**3. Reductions and clustering**

```
data.integrated <- RunPCA(data.integrated, npcs = 50)
data.integrated <- FindNeighbors(data.integrated, dims = 1:20)
data.integrated <- FindClusters(data.integrated, resolution = 0.5)

data.integrated <- RunTSNE(data.integrated, dims = 1:20)
data.integrated <- RunUMAP(data.integrated, dims = 1:20)

```

**4. Plotting**

```
TSNEPlot(data.integrated)
UMAPPlot(data.integrated)
```

**5. Subsetting based on clustering**

> after clustering and plotting with TSNEPlot/UMAPPlot, I decided to get a subset that only contains cluster number 0, 3, 5, 8, and 9. 

`Sub.data <- subset(data.integrated, idents = c("0", "3", "5", "8", "9"))
`

**6. Extract raw count data (unnormalized data) of each batch**

`Sub.data.list <- SplitObject(Sub.data, split.by = "line")`

> --> I'm getting 5 Seurat objects by line (A, B, C, D, E) and they contain cluster 0, 3, 5, 8, and 9.

```
for (i in 1:length(Tri10x.MG.list)) {
Sub.data.list[[i]] <- GetAssayData(object = Sub.data.list[[i]], assay = "RNA", slot = "counts")
}
```
> --> Here I get unnormalized data of A, B, C, D, E but only containig the cells of cluster 0, 3, 5, 8,  and 9.

**7. Then repeat step 1 and 2 to make integrated Seurat object only with clusters 0, 3, 5, 8, 9 cells.**
**8. Do analyses such as DotPlot, Heatmap, and DE analysis**

Or do I just have to do like this?
```
Sub.data <- subset(data.integrated, idents = c("0", "3", "5", "8", "9"))
Sub.data <- FindVariableFeatures(Sub.data)
DefaultAssay(Sub.data) <- "integrated"
Sub.data <- ScaleData(Sub.data)

```

Thanks!

**Comment by timoast** [comment]
I don't think it makes sense to subset, split, then repeat the integration. You can just subset to the clusters you want and change the default assay to "RNA" for DE analysis and visualization.

**Comment by younjung82** [comment]
Thanks!
