### ISSUE TITLE
How to export expression level of cell type or cluster?

### ISSUE THREAD

**Issue by Eason-yeh** [satijalab/seurat#3218]
Hi, everyone, 
I want to export expression level of cell type or cluster, but I can't find where it is. 
Where can I find it? 
And, the FC is calculated by expression level, right? 
Thank you very much!

**Comment by timoast** [comment]
Hi, please see the `AverageExpression()` function. Fold change in the `FindMarkers()` function is computed from the `data` slot and assumes that the data is log-transformed.
