### ISSUE TITLE
as.Seurat creates unnecessary restraints on gene names

### ISSUE THREAD

**Issue by bharris12** [satijalab/seurat#3219]
Seurat won't let you use gene (feature) names with underscores. Currently it replaces them with dashes and throws a warning. It seems unnecessary to set constraints on the characters that can be used in gene names if you are not the ones giving the genes names. I would rather my data always have the actual gene name stored, even if the difference is between a dash and underscore. It creates many minor inconveniences for downstream analysis

**Comment by mojaveazure** [comment]
Underscores are reserved characters in Seurat as the delimiter between an [object key](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/Key) and feature name. We use this to allow full multi-modal data access, even when the data you want is contained in a [different assay](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/DefaultAssay). Keys also allow us to have duplicate feature names across assays, a limitation of Seurat 2.X; by disallowing underscores in feature names, we are able to tell what part of a feature name is a key and what part is not in various plotting and [data access](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/FetchData) functions.

AFAIK, the only inconvenience that switching underscores to dashes causes is requiring the use of backticks around feature names in a call to `subset` or `WhichCells` (see https://github.com/satijalab/seurat/issues/1212#issuecomment-470983294). If you notice any other times where dashes in feature names cause issues in Seurat, please let us know.

For more help using Seurat's multi-modal functionality, please check out the "Multi-Assay Features" tab of our [Seurat cheat-sheet](https://satijalab.org/seurat/essential_commands.html) and our [multi-modal vignette](https://satijalab.org/seurat/v3.1/multimodal_vignette.html)

**Comment by bharris12** [comment]
I understand why you did it, but would highly recommend that in a future release you switch the reserved character to something that isn't in gene names. A common analysis that would be affected would be enrichment based on the markers  you identify in Seurat. The gene names in the markers matrix will not match the ones in the references, be it GO or KEGG or whatever gene lists you are using. This will produce incorrect results and most people will never notice it.

**Comment by mcsimenc** [comment]
Disallowing characters in feature names creates inconvenience for us, simply because of the need to reference between all places these annotations exist. Is there any way to make Seurat honor feature names from cellranger output?

**Comment by Shians** [comment]
Seconding the comment above. When the feature names are used as a key for other annotation in an analysis, Seurat's forced change to the feature names requires additional conversions everywhere else. Surely there is a better technical solution to the array access problem that doesn't cause a warning in extremely common usage cases. Case in point, there are 100+ issues containing code with the warning, and it's just treated as normal when using Seurat.

**Comment by assaron** [comment]
I stumbled upon the same problem too and also think that using "_"  as a reserved separator wasn't the best option.

However, I understand it can't be easily changed now. Thus I wonder, if some workarounds can be implemented. Currently, I think about two things:

1) To save the original feature names and use them when returning features from a single assay. E.g. restore original feature names at the end of the FindMarkers function. These can be stored as a feature metadata column.

2) To preprocess feature names in FetchData, so that the original names can be used, e.g. in FeaturePlot. This should be pretty straightforward: just replace "_" with "-" in `vars` argument of FetchData implementations.

**Comment by pormr** [comment]
> 1. To save the original feature names and use them when returning features from a single assay. E.g. restore original feature names at the end of the FindMarkers function. These can be stored as a feature metadata column.

Yes, it's a good idea. At least, it would save users the effort of getting their hands dirty to find the actual feature names in HDF5 (.h5) matrices.
