### ISSUE TITLE
RunUMAP() with features can only pull data from "data" slot

### ISSUE THREAD

**Issue by krejciadam** [satijalab/seurat#3220]
Hi!
  In current Seurat (3.1.5), when` RunUMAP() `is called with `features` argument (i.e. not not performing UMAP on a dim. reduction, but directly on the data in an assay), it takes the `data` slot as input. I can see no straightforward way to make `RunUMAP()` use` scale.data` or some other slot instead, so I have to revert to some tricks, which is a bit ugly. 

Is there a simple way to pull data for `RunUMAP()` from a different slot that I'm missing? If not, could a simple "slot" argument be implemented? 

Thanks a lot!
Adam

**Comment by yuhanH** [comment]
You are right. Right now, you can only use data slot to RunUMAP. We will implement a `slot` input for RunUMAP. 
Thanks for pointing this out.

**Comment by yuhanH** [comment]
The slot option is added into `RunUMAP` in the develop branch. Please update to the latest develop branch. 
Thanks.

**Comment by krejciadam** [comment]
> The slot option is added into `RunUMAP` in the develop branch. Please update to the latest develop branch.
> Thanks.

Fantasctic! Thanks a lot!
