### ISSUE TITLE
AddModuleScore aggregated expression of control feature sets

### ISSUE THREAD

**Issue by liqian-ma** [satijalab/seurat#3221]
I am trying to understand how the module score is calculated:

I looked into the description and the source code. It looks like it is calculated by average expression of interested features in a cluster - a control expression. The control expression is calculated by randomly select n genes from each bin the interested gene is in, and taking the average. Do I understand it correctly? If so, why here we should subtract the average/aggregated, randomly selected control expression from the features average to calculate the module score, and why randomly selected genes from each bin can serve as control genes?

Thank you very much for your help!!

**Comment by ashuchawla** [comment]
Following

**Comment by jaisonj708** [comment]
We subtract expression of module features from a set of "matched" controls, since module score is meant to be a relative not absolute measure 

See issue #3253
