### ISSUE TITLE
Error using CreateSueratObject. Unused argument (raw.data = data)

### ISSUE THREAD

**Issue by hoytpr** [satijalab/seurat#3222]
I've used Suerat v. 2 before, but am having trouble getting started with version 3.1.5, in RStudio.
Two errors are seen:
`install.packages("Suerat")` works, and `library(Suerat)` works, but `library(SueratData)` gives error:
`Error in library(SeuratData) : there is no package called ‘SeuratData’`

When reading my own data after DropSeq:
```
data=read.table("Sample12/final.dge.summary.txt.gz",sep = "\t",header=T,row.names = 1)
dge <- CreateSeuratObject(raw.data = data, project="sample12")
Error in CreateSeuratObject(raw.data = data, project = "sample12") : 
  unused argument (raw.data = data)
```
Have tried restarting RStudio (version1.1.453). R has been restarted a few times. 
Any advice getting started is greatly appreciated!

**Comment by samuel-marsh** [comment]
Hi,

So the error for SeuratData means that package is not installed.  So you should install that directly:
`devtools::install_github('satijalab/seurat-data')`

There have been a number of changes to the calls of various functions between V2 and V3.1.5.  The new call for CreateSeuratObject is:
`dge <- CreateSeuratObject(counts = data, project="sample12")`

Thanks,
Sam

**Comment by hoytpr** [comment]
Thank-you! I have been reading and working the vignettes for days but somehow missed this clear change. I sincerely appreciate your help!
