### ISSUE TITLE
Statistical comparison of gene scores via AddModuleScore

### ISSUE THREAD

**Issue by Dzhan4** [satijalab/seurat#3224]
Hello,

I'm interested in demonstrating a difference in gene scores generated via AddModuleScore between two clusters. From a histogram view, the distribution of my gene scores appear roughly normal for each cluster. 

Would it be valid to perform a parametric test of means on these gene scores and interpret p-values as such?

Thanks in advance!

**Comment by satijalab** [comment]
We would probably suggest a non-parametric test like Wilcox for this, there's no guarantee that the. scores would follow a normal distribution.
