### ISSUE TITLE
How to use FeaturePlot only to see whether there is expression in  to show the data, not how much expression.

### ISSUE THREAD

**Issue by BeyondMyPast228** [satijalab/seurat#3225]
Hi，
Thanks very much for such an excellent R package. I have two question about **FeaturePlot.**

1. When I want to see the expression of CD8A in my data, can I plot the graph based on whether there is CD8A (**TRUE/FALSE**) but not how much the expression of CD8A.

2. I used Seurat to integrate three different single-cell samples. But I wanted to look at **both** the cluster in which the genes were expressed **and** the sample of the cell that expressed them. What can be done to solve this problem?

Thanks in advance. Sincerely hope to receive your reply

**Comment by yuhanH** [comment]
For the first question, you can generate a new variable representing CD8A positive and negative using your own cutoff, and visualize it by `DimPlot`. 

For your second question, you can use `VlnPlot` and add the variable with sample information to `split.by`.
For example,  `VlnPlot(pbmc_small, features = "IL7R", split.by = "groups")`
