### ISSUE TITLE
Differentially expressed genes between conditions

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#3227]
I  am using your comparing gene expression condition between treated and control conditions using your stimulated vs. control PBMC vignette. I wanted to get the list of differentially expressed gene between treated and control conditions with fold changes and p-values etc.
Please let me know how to determine this.

**Comment by timoast** [comment]
Please see the immune alignment vignette: https://satijalab.org/seurat/v3.1/immune_alignment.html
