### ISSUE TITLE
Seurat3 DimPlot inconsistency

### ISSUE THREAD

**Issue by mbk0asis** [satijalab/seurat#3228]
Hi!

I'm currently analysing a single cell RNA-seq data using Seurat3.1.5.

While analysing, I found that the UMAP/tSNE plots by DimPlot kept changing everytime I ran it even though I sat the seed.use for RunPCA and RunUMAP.

The code I used is below.

>nDim = 50
>mipsc <- RunPCA(mipsc, npcs = nDim, features = VariableFeatures(object = mipsc), seed.use = 123)
>ElbowPlot(mipsc, ndims = nDim)
>mipsc <- RunUMAP(mipsc, dims = 1:20, seed.use = 123) 
>DimPlot(mipsc)

Is there a bug in the code or other steps I must set a seed?

Thank you!

**Comment by yuhanH** [comment]
It is wired. Could you reproduce UMAP in our pbmc vignette?
https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

**Comment by mbk0asis** [comment]
Sorry for late reply.

It turned out I ran `RunUMAP` with selected cells using `CellSelector` previously, and accidentally(?) deleted the codes.

I think that's why I wasn't able to obtain the same UMAP in later trials.

I'm sorry for such confusion~~


Thank you!
