### ISSUE TITLE
TopCells retrieves duplicated cells in positive and negative

### ISSUE THREAD

**Issue by adomingues** [satijalab/seurat#3229]
I have encountered an unexpected issue with the function `TopCells`. I am retrieving the top cells for multiple principal components, and for the first one a cell is found in duplicate:

```R
x <- "PC_1"

cells <- TopCells(
      object = seo[["pca"]],
      dim = x,
      ncells = ncol(seo),
      balanced = TRUE
    )
cells$negative[cells$negative == "S46.D7"]
# [1] "S46.D7"
cells$positive[cells$positive == "S46.D7"]
# [1] "S46.D7"
```

I have also confirmed that there are no duplicated cells names in the matrix:

```R
ncol(seo)
# [1] 4047

colnames(seo)[duplicated(colnames(seo))]
# character(0)
```

Is this an expected output? I am a but surprised because this is the first it happens for one of our datasets. 

Cheers.

**Comment by yuhanH** [comment]
Right. Two things related to this question. 
First,  `ncells`  is the Number of cells to return, so when you want to return top cells, you may not use `ncol(seo)`, all cells. 
Second, I think your object has even number of cells. You set `balance` to TRUE and a too big `ncells` , so the cells are forced to be divided into two parts with equal cell number.
In the output, one cell is duplicated. 
We should fix this bug. Thanks for pointing this out.

**Comment by andrewwbutler** [comment]
This should be resolved now on the `develop` branch. For installation instructions, please see this [page](https://satijalab.org/seurat/install.html#development).
