### ISSUE TITLE
Selecting CCs using RunMultiCCA()

### ISSUE THREAD

**Issue by dandepledge** [satijalab/seurat#323]
Hi Team Seurat!

I'm trying to use RunMultiCCA() to compare and contrast datasets generated at different times in which batch effects appear very much present. However, I could do with a little input on whether the batch correction is being handled correctly. 

Here is an example. I have three datasets (A1, B1, and X). A1 and B1 are biological replicates (my controls) prepared and sequenced on different days. X is a treatment sample (same underlying heterogeneous cell population) prepared at the same time as B1. Following import and processing of data, I get this.

![test](https://user-images.githubusercontent.com/32496778/36502853-2cb06684-1719-11e8-9142-25e60a562b46.jpg)

While A1 and B1 look reasonably ok (at least between CC2 - CC7), X looks quite different. Would it be sensible to limit further processing to CC2 - CC4?

I've scoured the preprint (Butler et al) but the answer is not clear to me. I'd greatly appreciate any thoughts you can offer.

**Comment by satijalab** [comment]
Apologies for the slow response. The final version of the manuscript will be out soon and detail this.

For multiple alignment, in some cases in later CCs, we see that the CCs can have strong correlation in multiple (but not all) datasets. 

Unfortunately, as with PC selection, we can't give a perfect answer. Regardless of which way (or both) that you try the analysis, make sure that you always examine the underlying gene expression that drive the alignment and clustering (for example, with FindConservedMarkers), to ensure that the results are biologically sensible.
