### ISSUE TITLE
FindAllMarkers() Pseudocount.use parameter and Dotplot() scale interval

### ISSUE THREAD

**Issue by Drosophilist** [satijalab/seurat#3230]
Hello Satija lab,

I currently have two questions about the Seurat pipeline and would be incredibly grateful if you could help me figure them out.

1. I would like to ask you what is the purpose of the parameter pseudocount.use when calculating avg_logFC in FindAllMarkers()? 

2. How does Dotplot define the Average expression scale interval? Sometimes, but very consistently I get dot plots with -0.4 to 0.4, sometimes others with -1 to 2. How does Seurat decide upon which scale interval to use?

Cheers!

**Comment by satijalab** [comment]
1. We use a pseudocount to avoid havving a 0 in the denominator
2. The scale is based on the data itself. Different genes will have different values, depending on their distribution across cells.
