### ISSUE TITLE
Can SCTransform be used when comparing two conditions?

### ISSUE THREAD

**Issue by jenwallace** [satijalab/seurat#3231]
I am analyzing two conditions (many cell types) in a conceptually similar way to the Stimulated vs Control PMBCs vignette. I am wondering whether there is a reason that the standard normalization procedure rather than SCTransform is used in this case. Thanks!

**Comment by yuhanH** [comment]
Definitely, you can use SCTransform in the `Stimulated vs Control PMBCs vignette`.
You can use the similar inputs format in the SCT integration vignette.
