### ISSUE TITLE
FindIntegrationAnchors run time on data with many samples

### ISSUE THREAD

**Issue by jingzhangorg** [satijalab/seurat#3234]
Hello,

I am trying to follow the Seurat integration method (https://satijalab.org/seurat/pancreas_integration_label_transfer.html) to merge a single cell data >50 samples (on average >8k cells/sample). I used all cells as a reference. 

However,  the FindIntegrationAnchors step seems to run for a long time (>1day) for these samples. Would you like to suggest how to speed this step up?

Thank you!

**Comment by tuqiang2014** [comment]
you can use R package `future` to  parallel run `FindIntegrationAnchors `
https://www.jianshu.com/p/efd453c50219

**Comment by timoast** [comment]
You can enable parallelization by loading the future package (see https://satijalab.org/seurat/v3.1/future_vignette.html), and/or use reference based integration and reciprocal PCA rather than CCA (see https://satijalab.org/seurat/v3.1/integration.html)
