### ISSUE TITLE
Difference between vst and mvp option in the selection method for highly variable genes

### ISSUE THREAD

**Issue by thibui1996** [satijalab/seurat#3235]
Hi all,

I'm trying to understand what is the difference between the vst and mvp option in the selection method for highly variable genes so I can choose which option is best for my data. Basically, I'm trying to understand what kind of information each selection method highlights for future reference
I'm unsure what to look for yet from my data since I haven't had the data (sorry!)

**Comment by timoast** [comment]
This is described in the documentation for `FindVariableFeatures()`, run `?FindVariableFeatures` in R to read the documentation
