### ISSUE TITLE
AddModuleScore - differences depending on order of the clusters used

### ISSUE THREAD

**Issue by mplass** [satijalab/seurat#3236]
I'm using AddModuleScore to score different gene sets. If I change the order of the gene sets included in "features" list, the scores of them change (even though I use the same random seed and the same number of control features).

Does this make any sense?

## Example:
`featuresA <- list (a = c("Msl1","Gse1","Kmo"), b=c("Gins2","Zfp414","Mcm5"))`
`featuresB <- list (b = c("Gins2","Zfp414","Mcm5"),a = c("Msl1","Gse1","Kmo"))`

**note that features A and B contain the same gene sets (a,b), but in different order **

First we score the gene sets together
`obj <- AddModuleScore(object=obj, features = featuresA, name= "A",seed=42)`
`obj <- AddModuleScore(object=obj, features = featuresB,  name= "B",seed=42)`

then individually 
`obj <- AddModuleScore (object= obj, 
features= list(a = c("Msl1","Gse1","Kmo")),name="C",seed=42)`
`obj <- AddModuleScore (object= obj, 
features= list(b = c("Gins2","Zfp414","Mcm5")),name="D",seed=42)`

considering the genes that we used, 
A1==B2==C1, A2==B1==D1, 

this is the result:

`                   A1                  A2               B1          B2          C1         D1`
`cell1 -0.06675089  -0.3235628 -0.3566949 -0.05723754 -0.06675089 -0.3566949`
`cell2 0.02527180   -0.2136677   -0.2342846  0.04951313  0.02527180 -0.2342846`
`cell3 0.02698940  -0.2183677   -0.1996687  0.01595078  0.02698940 -0.1996687`
`cell4 0.35920187   -0.1968445   -0.1642374  0.43537652  0.35920187 -0.1642374`
`cell5 0.59140240   -0.2329293   -0.2209052  0.59663111  0.59140240 -0.2209052`
`cell4 0.08675952   -0.3688551   -0.3518588  0.07062373  0.08675952 -0.3518588`

Am I missunderstanding how AddModuleScore works?

Shouldn't these examples give me the same scoring for each cell?

Thanks!

**Comment by jaisonj708** [comment]
Even though you use the same random seed for `featuresA` and `featuresB`, the stochastic `sample` function is called on the "a" module first in `featuresA` and the "b" module first in `featuresB`, so there is still randomness .

But it's not a problem - A1==B2==C1 are all very similar, and A2==B1==D1 are also very similar
