### ISSUE TITLE
FindAllMarkers skips cluster

### ISSUE THREAD

**Issue by hilalga** [satijalab/seurat#3237]
Dear Seurat Team,

first of all thank you for making this tool. It's been a great help.

I have analysed a few datasets now without problem. I usually use the FindAllMarkers function to characterize my clusters. So far that has worked without a problem, but now it keeps skipping cluster 2. There is no progress bar to indicate that it calculates anything for that cluster like it does for the others and I get no output for this cluster. But I can't imagine that my cluster has no significant markers.

I used the following code:

`> object.markers <- FindAllMarkers(object, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)`

> Calculating cluster 0
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Calculating cluster 1
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Calculating cluster 2
Calculating cluster 3
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Calculating cluster 4
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%  elapsed=02s

Have you had this problem before? Any help would be much appreciated. Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but what happens if you run this instead?:
`object.markers <- FindAllMarkers(object, min.pct = 0.25, logfc.threshold = 0.25)`

Best,
Sam

**Comment by hilalga** [comment]
Hey Sam,

`object.markers <- FindAllMarkers(object, min.pct = 0.25, logfc.threshold = 0.25)` calculates all clusters. And I have checked the list, it only shows one marker that actually has a negative avg_logFC. So maybe that's it and `FindAllMarkers ` just doesn't show the calculation if it doesn't find anything. 

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Yeah, that makes sense.  I would consider looking at your clustering resolution and other parameters as the lack of distinguishing markers may indicate the cluster is not all that different from other clusters.

Best,
Sam

**Comment by hilalga** [comment]
I will check that out, thanks you!
