### ISSUE TITLE
How to go about with the integration of the samples?

### ISSUE THREAD

**Issue by yeroslaviz** [satijalab/seurat#3238]
my data set has 5 conditions with two duplicates each. When doing a the UMAP on the complete data set I can clearly see a batch effect based on the sample. 
my seurat object is as such

```
	orig.ident	nCount_RNA	nFeature_RNA		mitoRatio	cells	sample	condition
1	P10	4504	2254	…	0.1130107	P10_s1_AAACCCAAGAAACACT-1	P10_s1	P10
2	P10	831	595	…	0.1528279	P10_s1_AAACCCAAGAATCGAT-1	P10_s1	P10
3	P10	970	649	…	0.1730175	P10_s1_AAACCCAAGACCATTC-1	P10_s1	P10
4	P10	790	548	…	0.1620253	P10_s1_AAACCCAAGATGTTAG-1	P10_s1	P10
5	P10	777	535	…	0.1930502	P10_s1_AAACCCAAGCACTCGC-1	P10_s1	P10
6	P10	1013	677	…	0.142152	P10_s1_AAACCCAAGCTACTAC-1	P10_s1	P10
```
while the last column is the condition (with five factors) of each two samples (10 factors).

Would it make more sense to first integrate the two duplicates and afterwards look at the data to see if I still have a batch effect?
Or would it be better to integrate the data from the beginning on a sample-base ( and have 10 different cell types).

 Or would it be enough to only regress based on the `condition` or `sample`?

Thanks
Assa

![allSamples_SCT_filltered_DimPlot_TSNE](https://user-images.githubusercontent.com/8927555/86937764-ed815d00-c13f-11ea-8aef-52326864e51d.png)

**Comment by timoast** [comment]
It's hard to give specific advice like this without knowing anything about the specific experiment, I'd suggest trying different approaches and see what works for you, perhaps starting with integrating across replicates and then across conditions.
