### ISSUE TITLE
DGE analysis with MAST - pct1 vs pct2 differences

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#3240]
Hi Seurat team,

Thank you for developing Seurat. I have integrated about 8 data sets together and I am performing DGE analysis to identify cluster-specific gene expression differences across two conditions. I decided to run MAST test as suggested in the tutorial. I am performing two tests, one to identify positive genes upregulated in condition 1 and the other to identify positive genes unregulated in condition 2 (i.e. switching the oder of conditions). 

I have noticed that even though I do get different and unique genes unregulated in each condition, I noticed that the pct is a bit strange. For example, if I run MAST on condition 1 vs. condition 2, I get all genes with high pct in condition 1 compared to condition 2. However, If I switch the order, I get DEGs but the percentage is higher in condition 1 versus condition 2 (when I would expect the pct to be higher in 2 vs. 1). This happens almost all the time that I run this test!

Is this normal? Is this expected? Any help will be greatly appreciated.

Thanks!

**Comment by satijalab** [comment]
I don't think this is a bug in Seurat (though its possible), but I would encourage you to check a few things.

1. Make sure you are running DGE on the RNA assay

2. It sounds like you might have only.pos set to T, which returns markers that are specific to the first condition listed in FindMarkers. You can change this to F to fix.

If this doesn't solve your problem, please feel free to reopen and to send some of your example code.
