### ISSUE TITLE
Monocle3

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#3241]
Hi Seurat team,

Thank you for developing wrappers for Monocle3. I am trying to run Monocle3 on my Seurat object but I get an error when trying to run the following function: as.cell_data_set.

This is the error:

Error in as.cell_data_set(object) : 
  could not find function "as.cell_data_set"

Do you have any advice?  I have installed all dependencies.

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

The function `as.cell_data_set` is part of [Seurat Wrappers](https://github.com/satijalab/seurat-wrappers) package and not Seurat package. 
 Do you have the wrappers package installed and loaded? 

If you continue to have issues I suggest posting issue on the repo for Seurat Wrappers.

Best,
Sam
