### ISSUE TITLE
R Session Aborted after TransferData function

### ISSUE THREAD

**Issue by jasonsaunderswilliams** [satijalab/seurat#3242]
Hi, 

I am following the seurat vignette (https://satijalab.org/signac/articles/pbmc_vignette.html)

At the following stage, when loading the scRNA PBMC data R aborts.

```{r Load the pre-processed scRNA-seq data for PBMCs}
pbmc_rna <- readRDS("/data/Jason/ATAC-Seq/CELLRANGER_scATAC/1_4303Swansea_CS001/pbmc_10k_v3.rds")

transfer.anchors <- FindTransferAnchors(
  reference = pbmc_rna,
  query = pbmc,
  reduction = 'cca'
)

predicted.labels <- TransferData(
  anchorset = transfer.anchors,
  refdata = pbmc_rna$celltype,
  weight.reduction = pbmc[['lsi']],
  dims = 2:30
)

pbmc <- AddMetaData(object = pbmc, metadata = predicted.labels)
```

I ran the individual lines of code to see where it aborts and it is from predicted.labels.

Couldn't see that anyone else has had the same issue.

**Comment by timoast** [comment]
Please see https://github.com/timoast/signac/issues/177 and try the suggestions there
