### ISSUE TITLE
Error in installing Seurat v3.2/Spatial Vignette

### ISSUE THREAD

**Issue by guardacaccia** [satijalab/seurat#3243]
Running devtools::install_github("satijalab/seurat", ref = "spatial") ended up in the following error: "Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) unable to access index for repository https://mojaveazure.github.io/loomR/bin/macosx/contrib/4.0:
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/macosx/contrib/4.0/PACKAGES'"

The given URL's open pages with "404 page not found". Have the URL's changed since the publication of the Spatial analysis vignette (https://satijalab.org/seurat/v3.1/spatial_vignette.html)?

**Comment by samuel-marsh** [comment]
Hi,

From quick google search it appears this is probably related to internet proxies or firewalls that are causing issues with the installation.  Check out some solutions on these threads and see if any of them solve the issues:
[https://community.rstudio.com/t/unable-to-install-package-in-r-studio/15930](https://community.rstudio.com/t/unable-to-install-package-in-r-studio/15930)
[https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578](https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578)

Do you get the same error if you just try installing loomR directly?
`devtools::install_github(repo = "mojaveazure/loomR")`

Best,
Sam

**Comment by guardacaccia** [comment]
Hi,
Thanks for the quick answer. Disabling the secure download did not solve the issue and I'm able to install loomR directly, no issue there. As said above, if I copy the URL's given in the error message to a browser, they lead to empty pages and that's why I originally wondered if the URL's have changed.

**Comment by samuel-marsh** [comment]
Hi,

Are you installing from home network or institutional one with firewall and/or proxy?

**Comment by guardacaccia** [comment]
Institutional one. I already checked that my firewall (F-secure) preferences should not block R(studio) from accessing internet repos. I even disabled the firewall for a moment to try if it still had something to do with this but it did not solve the issue either. Any further ideas?

**Comment by samuel-marsh** [comment]
Hi,
My only other suggestion left based on what I've found online and without knowing a lot more specifics about the network you are on, would be attempting the installation from different network (preferably home network) to see if that resolves the issue.   Someone else from Dev team or community may have other suggestions too.  Sorry I couldn't be of more help!

**Comment by guardacaccia** [comment]
Sure, I can try this at home tomorrow. And no problem, thanks for trying.

If anyone else has any suggestions meanwhile I'm happy to receive them.

**Comment by mojaveazure** [comment]
There's a weird behavior in `remotes::install_github` where it requires that additional repositories provide binary directories for OS's that utilize R package binaries (Windows, macOS), even if R is configured to use source packages in addition to binaries (`getOption("pkgType") == "both"`) and you're not using packages provided by said other repositories (you aren't installing loomR, you don't need the loomR repository). What's even more weird is that remotes isn't using the `macosx/el-capitan/contrib` repository as that's what it should be using over `macosx/contrib`

I've added the dummy files to the loomR repository for `macosx/contrib`, using remotes to install the spatial branch of Seurat should work just fine now.
