### ISSUE TITLE
Logical Error when using FindIntegrationAnchors()

### ISSUE THREAD

**Issue by sahh04** [satijalab/seurat#3245]
Hello,

I am a high school student who is relatively new to both R and single-cell RNA-seq data/analysis, so I apologize in advance if anything here is a bit unclear. I am attempting to analyze two highly similar biological datasets, one done with 10x V2 and the other with 10x V3. I followed the methods outlined in the integration and label features tutorial and I was able to successfully split each of the two datasets by their main differential attributes, as well as scale and normalize the data. I have been able to do so using each of the four methods outlined in the integration and label transfer tutorial. However, in each case when attempting to use FindIntegrationAnchors(), I run into an "Error in which(x = object.classes, useNames = TRUE) : argument to 'which' is not logical". As a note, when running FindIntegrationAnchors(), the integration features are able to be computed and scaled for the provided objects, whereas the error is given as pairwise anchors are found. 

Do you have any suggestions as to what I can do to resolve this error? Any help would be greatly appreciated, and I'll do my best to clarify anything that was unclear if that's necessary.

**Comment by jaisonj708** [comment]
Are you passing a list with multiple objects as your first argument to `FindIntegrationAnchors`? It might help if you show the command you tried to run and/or the traceback.
