### ISSUE TITLE
SCTransform parallelization issue

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#3249]
Hello!

I've recently began working with larger seurat objects (>50 000 nuclei), and I've been receiving the following error when running SCtransform. 

> Error in unserialize(node$con) :
>   Failed to retrieve the value of MultisessionFuture (future_lapply-1) from cluster RichSOCKnode #1 (PID 15384 on localhost 'localhost'). The reason reported was 'error reading from connection'. Post-mortem diagnostic: No process exists with this PID, i.e. the localhost worker is no longer alive.
> Calls: <Anonymous> ... resolved -> resolved.ClusterFuture -> receiveMessageFromWorker
> 
> Execution halted
> ==> Resources used : cput=00:29:43,mem=41732516kb,vmem=56349616kb,walltime=01:13:27
> ==> Exit status    : 1

The issue seems to be related to the way that SCtransform is being parallelized. Is this something that you've encountered before? Do you have a recommended solution?

Thanks in advance,
NM

**Comment by timoast** [comment]
This indicates that the workers are killed, probably due to ram. Did you try increasing `future.globals.maxSize`? See https://satijalab.org/seurat/v3.1/future_vignette.html

**Comment by jgarces02** [comment]
Updated link -> https://satijalab.org/seurat/articles/future_vignette
