### ISSUE TITLE
Differential Expression Analysis using Standard Seurat Workflow

### ISSUE THREAD

**Issue by NathashaSelene** [satijalab/seurat#3250]
Hello, I am currently working on pancreatic islet dataset in which I would like to perform differential expression analysis on alpha and beta-cell of the pancreas then perform GO enrichment analysis to identified which categories were enriched. 

I performed differential expression analysis following Seurat standard workflow and used Bonferroni as multiple testing correction method. However I encountered trouble in interpreting the result. 

If I want to select genes that were up-regulated in condition 1, does it mean I need to filter the avg_log FC > 0 and vice versa for the downregulated genes?

my next question is regarding the correction method. I do notice that bonferroni correction method is very stringent and may result in high rate of false negative. In addition, I have a very small dataset (553 for alpha cells and 418 for beta cells)

I do notice that Seurat recommend bonferroni instead of BH correction procedure. Why is that? Also, do you have any recommendation for the appropriate correction method especially for small dataset? 

Thank you very much, your reply is very much appreciated. 

Nathasha

**Comment by satijalab** [comment]
1. Yes that is correct re avg_logFC
2. We purposefully take a stringent approach, with the aim of being conservative, but don't have any specific recommendations for different dataset sizes.
