### ISSUE TITLE
Exact fold-change number of logfc.threshold in FindAllMarkers()

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#3251]
I want to use the parameter "logfc.threshold" in  FindAllMarkers(). And I wonder what is the exact fold-change number.

For example, does "logfc.threshold = 0.4" refer to -0.39794 fold ?

**Comment by jaisonj708** [comment]
"logfc.threshold = 0.4" corresponds to a fold change of e^0.4 (around 1.5)

**Comment by grimwoo** [comment]
@jaisonj708 Thanks!
