### ISSUE TITLE
Computational formula of AddModuleScore()

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#3252]
Hi, I wonder the computational formula of AddModuleScore(), which could seem like (∑ given genes)/(∑ control genes). Could anyone tell me?

**Comment by jaisonj708** [comment]
The average expression of each module's features is subtracted by the average expression of a set of control features for each cell, and these control features are determined by a binning procedure (see [supplement](https://science.sciencemag.org/content/sci/suppl/2016/04/07/352.6282.189.DC1/Tirosh.SM.pdf) of Tirosh et al 2018 for more details)
