### ISSUE TITLE
Controls in module scores

### ISSUE THREAD

**Issue by justanotherimmunolgist** [satijalab/seurat#3253]
Ok, I get that the controls in a module score are randomly selected. But randomly selected from where? The description is not exactly intuitive for a wet lab biologist. Average expression of my "module" of genes - aggregated expression of control features, right? But for the controls: Are ALL genes (features) in a cell analyzed, grouped based average expression, control genes selected at random from these different expression stratifications, and used to compare to the module I listed? What exactly is "all analyzed features"?

If I want to see expression of a module across 3 experimental groups, are the control genes the same across all groups? Are they the same between cells? It sounds to me like the control genes themselves can differ, because a variety of expression level groupings is what's driving the the comparison to the module of interest. Is this correct? 

Would love some clarification on this. Thanks!

**Comment by jaisonj708** [comment]
You can refer to page 10 of the [supplement](https://science.sciencemag.org/content/sci/suppl/2016/04/07/352.6282.189.DC1/Tirosh.SM.pdf) for Tirosh et al 2018 for a detailed explanation.

Essentially, for each module gene, 100 control genes are selected with a similar average expression (i.e, these genes fall into a similar average expression 'bin' as the module gene). The set of control features will therefore be up to 100x larger than the set of module features. While the 100 genes are randomly selected and may differ if you re-run, it's large enough that the randomness should not matter. To be safe, you can increase the number of control genes selected  by setting `ctrl` param to >100.

**Comment by laijen000** [comment]
Hello! Is the "average expression" of the control feature set averaged within each cell? Or is it averaged across all the cells in the Seurat object? Thank you!

**Comment by Kensei-K** [comment]
> Hello! Is the "average expression" of the control feature set averaged within each cell? Or is it averaged across all the cells in the Seurat object? Thank you!

I'm confused about this point as well! 

Are the interested and control features averaged across all cells or just within each cluster?

**Comment by xiandxing** [comment]
Since I have the same problem, I have checked the original code in Seurat (https://github.com/satijalab/seurat/blob/master/R/utilities.R). And I'm sure that the control gene-sets are generated from the whole object (with rank of mean expression of all cells). Here comes up another problem. Do we need to calculate the module score split the whole seurat object into different group based on different conditions/datasets/technologies?
