### ISSUE TITLE
Differring plots in the ,,Integration and Label Transfer" Vignette with SCTransform Workflow 

### ISSUE THREAD

**Issue by marius-ju** [satijalab/seurat#3254]
Dear Seurat-Lab,

I am a beginner in scRNAseq and I am doing the great vignettes on your website, thanks a lot. I recently did the vignette ,,Integration and Label Transfer” with the standard workflow which worked after your advice #3175 to update the dataset. Now I ran into a second issue using the SCTransform Workflow in the same vignette as the UMAP plots look slightly different than those depicted on your website? Besides If I apply the SCTransform command I receive several warnings. I did this on a Linux Ubuntu 18.04 and Mac Catalina 10.15.5 computer nevertheless the plots and warnings remained 
the same.
Below are the typed in commands and warnings as well as error messages:

> library(Seurat)

> library(ggplot2)
> library(patchwork)
> library(SeuratData)
── Installed datasets ───────────────────────────────────── SeuratData v0.2.1 ──
✔ panc8   3.0.2                         ✔ pbmcsca 3.0.0
✔ pbmc3k  3.1.4    

────────────────────────────────────── Key ─────────────────────────────────────
✔ Dataset loaded successfully
❯ Dataset built with a newer version of Seurat than installed
❓ Unknown version of Seurat installed

> SeuratData::UpdateData('panc8')
> options(future.globals.maxSize = 4000 * 1024^2)
> data("panc8")
> pancreas.list <- SplitObject(panc8, split.by = "tech")

> pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
> for (i in 1:length(pancreas.list)) {
+     pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], verbose = FALSE)
+ }
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In dpois(y, mu, log = TRUE) : non-integer x = 56.874871
2: In dpois(y, mu, log = TRUE) : non-integer x = 59.384695
3: In dpois(y, mu, log = TRUE) : non-integer x = 43.494153
4: In dpois(y, mu, log = TRUE) : non-integer x = 84.541872
5: In dpois(y, mu, log = TRUE) : non-integer x = 60.648895
6: In dpois(y, mu, log = TRUE) : non-integer x = 61.919369
7: In dpois(y, mu, log = TRUE) : non-integer x = 63.196180
8: In dpois(y, mu, log = TRUE) : non-integer x = 87.339714
9: In dpois(y, mu, log = TRUE) : non-integer x = 70.993737
10: In dpois(y, mu, log = TRUE) : non-integer x = 69.677539
11: In dpois(y, mu, log = TRUE) : non-integer x = 93.028837
12: In dpois(y, mu, log = TRUE) : non-integer x = 54.389415
13: In dpois(y, mu, log = TRUE) : non-integer x = 80.401620
14: In dpois(y, mu, log = TRUE) : non-integer x = 106.311355
15: In dpois(y, mu, log = TRUE) : non-integer x = 101.806840
16: In dpois(y, mu, log = TRUE) : non-integer x = 68.368073
17: In dpois(y, mu, log = TRUE) : non-integer x = 64.479391
18: In dpois(y, mu, log = TRUE) : non-integer x = 49.489744
19: In dpois(y, mu, log = TRUE) : non-integer x = 95.921523
20: In dpois(y, mu, log = TRUE) : non-integer x = 103.299555
21: In dpois(y, mu, log = TRUE) : non-integer x = 121.925950
22: In dpois(y, mu, log = TRUE) : non-integer x = 95.921523
23: In dpois(y, mu, log = TRUE) : non-integer x = 91.594659
24: In dpois(y, mu, log = TRUE) : non-integer x = 101.806840
25: In dpois(y, mu, log = TRUE) : non-integer x = 69.677539
26: In dpois(y, mu, log = TRUE) : non-integer x = 80.401620
27: In dpois(y, mu, log = TRUE) : non-integer x = 131.773318
28: In dpois(y, mu, log = TRUE) : non-integer x = 69.677539
29: In dpois(y, mu, log = TRUE) : non-integer x = 59.384695
30: In dpois(y, mu, log = TRUE) : non-integer x = 83.154335
31: In dpois(y, mu, log = TRUE) : non-integer x = 80.401620
32: In dpois(y, mu, log = TRUE) : non-integer x = 84.541872
33: In dpois(y, mu, log = TRUE) : non-integer x = 69.677539
34: In dpois(y, mu, log = TRUE) : non-integer x = 63.196180
35: In dpois(y, mu, log = TRUE) : non-integer x = 54.389415
36: In dpois(y, mu, log = TRUE) : non-integer x = 74.983428
37: In dpois(y, mu, log = TRUE) : non-integer x = 65.769066
38: In dpois(y, mu, log = TRUE) : non-integer x = 72.316737
39: In dpois(y, mu, log = TRUE) : non-integer x = 54.389415
40: In dpois(y, mu, log = TRUE) : non-integer x = 87.339714
41: In dpois(y, mu, log = TRUE) : non-integer x = 60.648895
42: In dpois(y, mu, log = TRUE) : non-integer x = 54.389415
43: In dpois(y, mu, log = TRUE) : non-integer x = 43.494153
44: In dpois(y, mu, log = TRUE) : non-integer x = 65.769066
45: In dpois(y, mu, log = TRUE) : non-integer x = 76.327263
46: In dpois(y, mu, log = TRUE) : non-integer x = 80.401620
47: In dpois(y, mu, log = TRUE) : non-integer x = 120.320929
48: In dpois(y, mu, log = TRUE) : non-integer x = 70.993737
49: In dpois(y, mu, log = TRUE) : non-integer x = 63.196180
50: In dpois(y, mu, log = TRUE) : non-integer x = 90.168472
> pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 3000)
> pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features,
+     verbose = FALSE)
> pancreas.anchors <- FindIntegrationAnchors(object.list = pancreas.list, normalization.method = "SCT",
+     anchor.features = pancreas.features, verbose = FALSE)

> pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, normalization.method = "SCT",
+     verbose = FALSE)
Warning: Adding a command log without an assay associated with it
> pancreas.integrated <- RunPCA(pancreas.integrated, verbose = FALSE)
> pancreas.integrated <- RunUMAP(pancreas.integrated, dims = 1:30)
Warning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
This message will be shown once per session
12:56:27 UMAP embedding parameters a = 0.9922 b = 1.112
12:56:27 Read 6321 rows and found 30 numeric columns
12:56:27 Using Annoy for neighbor search, n_neighbors = 30
12:56:27 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
12:56:28 Writing NN index file to temp file /tmp/Rtmp2yIWXF/file2e783706ecd5
12:56:28 Searching Annoy index using 1 thread, search_k = 3000
12:56:30 Annoy recall = 100%
12:56:30 Commencing smooth kNN distance calibration using 1 thread
12:56:31 Initializing from normalized Laplacian + noise
Spectral initialization failed to converge, using random initialization instead
12:56:31 Commencing optimization for 500 epochs, with 277580 positive edges
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
12:56:38 Optimization finished
> plots <- DimPlot(pancreas.integrated, group.by = c("tech", "celltype"))
> plots & theme(legend.position = "top") & guides(color = guide_legend(nrow = 3, byrow = TRUE,
+     override.aes = list(size = 3)))

Below you can see the plots on your website (first) and the one I receive with my computer. They look similar but are not the same.

![SCTransform_Website_Pict](https://user-images.githubusercontent.com/66880775/87242309-c5d61180-c42b-11ea-857d-9f90ffce9aa8.png)

![SCTRansf_Pict1](https://user-images.githubusercontent.com/66880775/87242311-ca9ac580-c42b-11ea-9089-ae0374536939.png)

Below are my session Infos:

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] pbmcsca.SeuratData_3.0.0 pbmc3k.SeuratData_3.1.4  panc8.SeuratData_3.0.2
[4] SeuratData_0.2.1         patchwork_1.0.0          ggplot2_3.3.2
[7] Seurat_3.1.5.9008

loaded via a namespace (and not attached):
 [1] httr_1.4.1         tidyr_1.1.0        jsonlite_1.6.1     viridisLite_0.3.0
 [5] splines_3.6.3      leiden_0.3.3       assertthat_0.2.1   ggrepel_0.8.2
 [9] globals_0.12.5     pillar_1.4.4       lattice_0.20-41    glue_1.4.1
[13] reticulate_1.16    digest_0.6.25      RColorBrewer_1.1-2 colorspace_1.4-1
[17] cowplot_1.0.0      htmltools_0.5.0    Matrix_1.2-18      plyr_1.8.6
[21] pkgconfig_2.0.3    listenv_0.8.0      purrr_0.3.4        scales_1.1.1
[25] RANN_2.6.1         Rtsne_0.15         tibble_3.0.1       farver_2.0.3
[29] generics_0.0.2     ellipsis_0.3.1     withr_2.2.0        ROCR_1.0-11
[33] pbapply_1.4-2      lazyeval_0.2.2     cli_2.0.2          survival_3.1-12
[37] magrittr_1.5       crayon_1.3.4       fansi_0.4.1        future_1.17.0
[41] nlme_3.1-147       MASS_7.3-51.6      ica_1.0-2          tools_3.6.3
[45] fitdistrplus_1.1-1 data.table_1.12.8  lifecycle_0.2.0    stringr_1.4.0
[49] plotly_4.9.2.1     munsell_0.5.0      cluster_2.1.0      irlba_2.3.3
[53] compiler_3.6.3     rsvd_1.0.3         rlang_0.4.6        grid_3.6.3
[57] ggridges_0.5.2     RcppAnnoy_0.0.16   rappdirs_0.3.1     htmlwidgets_1.5.1
[61] igraph_1.2.5       labeling_0.3       gtable_0.3.0       codetools_0.2-16
[65] reshape2_1.4.4     R6_2.4.1           gridExtra_2.3      zoo_1.8-8
[69] dplyr_1.0.0        future.apply_1.5.0 uwot_0.1.8         KernSmooth_2.23-17
[73] ape_5.4            stringi_1.4.6      parallel_3.6.3     Rcpp_1.0.4.6

Do you have an idea what might be the reason for the different plots? Thanks a lot for your help.

**Comment by satijalab** [comment]
The exact location of points on a UMAP plot can chance across different computers and OSs. We do our best to minimize any randomness to the procedure by fixing the random seed, but some fluctuation across systems is inevitable, and nothing to worry about

**Comment by JunqiangWang** [comment]
Is there any better solution can make the figures the same?
