### ISSUE TITLE
Subset a cluster and assign new idents to the resulting clusters

### ISSUE THREAD

**Issue by elenichri** [satijalab/seurat#3256]
Hello,

I am trying to rename one of the idents of a Seurat object. The current idents are cell types based on an external clustering method. I need to subset one of the clusters, B_cells, into two more specific ones: CD10 B_cells and CD20 B_cells. I know which cells belong to each sub-cluster. But I cannot rename the respective elements of the metadata column. The B_cell elements that belong to sub-cluster CD10 B cells need to be renamed to CD10 B_cells and the B_cell elements that belong to CD20 B cells need to be renamed to CD20 B_cells. 

I tried with `SetIdent(object = mm0, cells = cell_Ids, value = 'CD10 B_cells')`
The new Ident is added to the Idents' names but not to the metadata column.

I thought of the `RenameIdents` function too, but it does not seem to work with subsets of clusters..it only renames the whole cluster. 

Any ideas on how to solve this problem?

Thank you very much!

**Comment by timoast** [comment]
You can assign the current cell idents to a new or existing metadata column using:

```r
obj$celltype <- Idents(obj)
```

where "celltype" is the name of the metadata column to create or modify

**Comment by laijen000** [comment]
Hi @elenichri , I have the same issue where I have a main Seurat object with many cell types, I subset it to get just the T cells and perform subclustering, annotate the subclusters (CD8, CD4, Treg), and then add these annotations back to the main Seurat object. Did you find a solution for this? Thank you for your help!

**Comment by elenichri** [comment]
Hi there!

I followed the suggestion that should apper on the issue as well..

You can assign the current cell idents to a new or existing metadata column
using:

obj$celltype <- Idents(obj)

where "celltype" is the name of the metadata column to create or modify


Did you try this?

**Comment by laijen000** [comment]
Ah I see, I realize I need to use SetIdent first as shown in your first post, then do obj$celltype <- Idents(obj). Thank you!
