### ISSUE TITLE
Hierarchical clustering dendrogram for integrated seurat object?

### ISSUE THREAD

**Issue by 4DtyU** [satijalab/seurat#3258]
Good morning,   Is it possible to create a dendrogram from an integrated seurat object? The following code throws an error:

*immune.combined <- BuildClusterTree(object = immune.combined, slot = "data")*

Error in hclust(d = data.dist) : NA/NaN/Inf in foreign function call (arg 10)

thanks in advance :)

**Comment by andrewwbutler** [comment]
Hi,

It should be possible. Can you post the code you used for integration?
