### ISSUE TITLE
CreateSeuratObject is very slow

### ISSUE THREAD

**Issue by davidfstein** [satijalab/seurat#3259]
I have a large expression matrix (~ 350,000 x 20,000). Using the CreateSeuratObject, takes an extremely long time, such that I'm not sure if it will ever complete. If I subset the data to 10,000 x 20,000, it takes 147 seconds to run.

I see in the Clustering of Mouse Cell Atlas vignette that the CreateSeuratObject function takes ~14 seconds for a matrix that is roughly comparable to the one I am attempting to load. I am working on a cluster node with 100 GB of RAM and I can allocate more memory if needed. Do you have any recommendation as to how I can successfully create this large object?

**Comment by timoast** [comment]
That's strange, what's the format of the input data you're using? Is it a dgCMatrix? 147 s is still unusually long, are you able to share the downsampled matrix? You can email a link to tstuart@nygenome.org

**Comment by davidfstein** [comment]
Its a data.frame. I read it in with the command:
```
data <- fread(file = "/path/mat.txt", header = TRUE, verbose = TRUE, showProgress = TRUE, data.table = FALSE)
```

I just sent the data to your email.

**Comment by timoast** [comment]
Thanks I'll take a look later, in the mean time I'm 99% sure this will be fixed by converting to a sparse matrix first

**Comment by davidfstein** [comment]
Haha ok, I'm giving it a shot now. I'll update if it works

**Comment by timoast** [comment]
I think it's actually because the way you read the data in keeps the gene names in a column of the dataframe, and so you have characters/NA where you should only have numeric values and that screws things up when it gets converted to matrix. If you set the rownames correctly and remove the column it runs pretty fast:

```r
data <- fread(file = "~/Downloads/axo_data.csv.gz", header = TRUE, verbose = TRUE, showProgress = TRUE, data.table = FALSE)
rownames(data) <- data$V1
data$V1 <- NULL
data$V1 <- NULL  # this column is repeated for some reason

obj <- CreateSeuratObject(counts = data)
```
