### ISSUE TITLE
FindConservedMarkers Error: cannot detect installed metap package

### ISSUE THREAD

**Issue by amdhome1** [satijalab/seurat#3262]
Hello,

Was working through the "Integrating stim vs ctrl PBMC datasets" [tutorial](https://satijalab.org/seurat/v3.1/immune_alignment.html), when I noticed I could not use the FindConservedMarkers function 

`nk.markers <- FindConservedMarkers(immune.combined, ident.1 = 6, grouping.var = "stim", verbose = FALSE)`

without receiving the error:

 ```

Error: Please install the metap package to use FindConservedMarkers.
This can be accomplished with the following commands: 
----------------------------------------
install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('metap')
----------------------------------------

```
I have installed the following packages, as per the recommended steps, to no avail. I have also tried restarting the R session, alternating to the development version of Seurat, and tested this on different machines (one MacOS, the other Windows).

I would like to know why this is, to also use on data outside of the tutorial.
Any insight would be greatly appreciated, Thank you.

**Comment by andrewwbutler** [comment]
Hi,

Can you please check that `metap` was installed successfully? 
```R
"metap" %in% installed.packages()
```

**Comment by amdhome1** [comment]
> ```r
> "metap" %in% installed.packages()
> ```

Hi,

This was the output:
```
"metap" %in% installed.packages()
[1] FALSE
```
I believe the issue was that Rtools wasn't installed - a quick fix of this seems to do the trick!

Thank you!
