### ISSUE TITLE
thresh.use in FindAllMarkers not in RDocumentation

### ISSUE THREAD

**Issue by aymanm** [satijalab/seurat#327]
is "thresh.use" parameter in FindAllMarkers (used in the tutorial) the same as logfc.threshold?
as I cannot find "thresh.use" in the documentation (https://www.rdocumentation.org/packages/Seurat/versions/2.1.0/topics/FindAllMarkers)

Thanks

**Comment by leonfodoulian** [comment]
Hi,

The short answer to your question is yes. Check also @andrewwbutler's answer in [issue #273](https://github.com/satijalab/seurat/issues/273).

Best,
Leon
