### ISSUE TITLE
Regressing out batch effects vs. data integration

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#3270]
Could you please clarify the differences between the following two methods for combining datasets:

method 1) 
- merge seurat objects from independent experiments
- perform SCTransform, with argument to regress out batch effects

method 2)
- perform SCTransform independently on samples from different experiments
- run integration (as outlined in your vignettes)

Do you expect the downstream result of either pipeline to be interchangeable, or do you see certain benefits to going with one approach over the other? 

Thanks in advance,
NM

**Comment by satijalab** [comment]
The results will certainly differ. Regressing is a reasonable approach, but it assumes that the 'batch effect' is the same for all cells. This is often not the case, which is why we developed methods for integration (where a specific correction vector is learned for each cell).
