### ISSUE TITLE
Questions regarding demultiplexing with HTOs

### ISSUE THREAD

**Issue by 14lwt1** [satijalab/seurat#3271]
Hi,
I have multiple single-cell RNASeq datasets (10X Chromium) that were also processed with hashtag oligos.
However, in most cases, I don't find multiplets to harbour more UMIs than singlets (please see attached violin plot for example).
Any explanation for this?
One rationale I have come up with is that perhaps the maximum number of transcripts detectable per gel bead is saturated in both singlets and doublets.

![rplot2_360](https://user-images.githubusercontent.com/59578221/87607875-2aef6880-c6b3-11ea-92bd-7fde7ab799b7.png)

**Comment by satijalab** [comment]
We don't always see that multiplets have more UMI than singlets, although that does often happen. As a sanity check to make sure the hashing and demultiplexing worked, you can use HTOHeatmap, or FeatureScatter (plot two hashtags against each other, you should see a mutually exclusive relationship). If that looks good, there is nothing to be concerned about.
