### ISSUE TITLE
compare metadata feature in FindMarkers()

### ISSUE THREAD

**Issue by llumdi** [satijalab/seurat#3272]
Hi, 
I would like to run a MAST test to compare treated vs control cells (not clusters). 

When running: 
hc6h_TLR7vsC <- FindMarkers(object = seurat_subset, ident.1 = "TLR7ago_iso_iso", ident.2 = "veh_iso_iso",
                            group.by = "treatment_compound_short", assay = "RNA", test.use = "MAST", 
                            min.pct = 0.10, return.thresh = 0.01, verbose=TRUE)

Error in .nextMethod(.Object = .Object, ... = ..., design = design) : 
  invalid name for slot of class “BayesGLMlike”: return.thresh

Is it possible to do pair-wise comparisons based on any metadata feature besides clusters? 
Thanks for your help,
Llucia

**Comment by vkavaka** [comment]
Hi Llucia,
you can assign new 'clusters', according to a column in your meta.data file.
You can do it with this function:
Idents(your object) <- 'name of the column in meta.data'
So the new groups would be the unique values from the column you choose.
