### ISSUE TITLE
IntegrateData memory not mapped

### ISSUE THREAD

**Issue by jefferyUstc** [satijalab/seurat#3274]
I encountered the same Error as #2386. No solution so far? Can you reopen the issue, [please?]

 *** caught segfault ***
address 0x2b22abdaa010, cause 'memory not mapped'

Traceback:
 1: RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names,     mat2_rownames = mat2.names, all_rownames = all.names)
 2: RowMergeSparseMatrices(mat1 = merged.data, mat2 = ValidateDataForMerge(assay = assays[[i]],     slot = "data"))
 3: merge.Assay(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],     merge.data = merge.data)
 4: merge(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],     merge.data = merge.data)
 5: merge.Seurat(x = object.1, y = object.2, merge.data = TRUE)
 6: merge(x = object.1, y = object.2, merge.data = TRUE)
 7: PairwiseIntegrateReference(anchorset = anchorset, new.assay.name = new.assay.name,     normalization.method = normalization.method, features = features,     features.to.integrate = features.to.integrate, dims = dims,     k.weight = k.weight, weight.reduction = weight.reduction,     sd.weight = sd.weight, sample.tree = sample.tree, preserve.order = preserve.order,     do.cpp = do.cpp, eps = eps, verbose = verbose)
 8: IntegrateData(anchorset = data_list.anchors, dims = 1:npc, features.to.integrate = overlap_genes)
An irrecoverable exception occurred. R is aborting now ...

**Comment by satijalab** [comment]
We can take a look at this, would you be able to send a copy of the object (or a Dropbox link) to 
Email: seuratpackage@gmail.com

**Comment by satijalab** [comment]
Please also include the commands you are trying to run that are causing an error

**Comment by zqun1** [comment]
I have the same problem. Have you solved the problem? @jefferyUstc 
 *** caught segfault ***
address 0x558c4e4cf000, cause 'memory not mapped'
