### ISSUE TITLE
No significant DEGs identified using MAST test - in all clusters tested 

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#3275]
Hi Seurat Team,

Thank you for developing Seurat. I am having trouble identifying significant DEGs using MAST test. This is how I am using this tool:

1. I anchored and integrated 12 data sets (from various time points) using Seurat 3
2. I sub-clustered fibroblasts only
3. I then identified 11 clusters of interest
4. I ran MAST test on normalized data from "RNA" assay to compare cluster 0 cells from condition "A" and "B" as follows:

Fib_all <- FindMarkers(Fib_all, ident.1 = "0_P1_A", ident.2 = "0_P1_B", only.pos = T, min.cells.group = 1, verbose = T, test.use = "MAST")

5. This returns a list of genes but none of them have significant adjusted P values - they all have a value of "1". I thought this was only an occurrence for this comparison but, to my surprise, I could not find significant DEGs using this criteria for all 11 clusters tested when comparing conditions "A" VS "B"; "B" VS "C"; or "A" VS "C" .

My questions are:

1. What affects DEG analysis in single cell data sets? 
2. Does sequencing depth, number of cells, or alignment efficiency have an effect on DEG analysis in single cell data sets?

**Comment by satijalab** [comment]
1. Make sure you are running DE on the RNA assay (not the integrated assay)
2. It is also possible that there are no DE genes between your clusters. Indeed, sequencing depth, cell number, and biological heterogeneity- all will affect this. If that is the case, it suggests that subclustering the fibroblasts is not appropriate.
3. Just to make sure this is not a MAST specific issue, do you get DEG when using other tests?
