### ISSUE TITLE
Error by trying to VlnPlot a feature: "Error in data[, feature] + noise: non-numeric argument to binary operator"

### ISSUE THREAD

**Issue by vkavaka** [satijalab/seurat#3276]
Hello, by trying to VlnPlot a feature, we are getting every time a following error:

> Error in data[, feature] + noise: non-numeric argument to binary operator
> Traceback:
> 
> 1. VlnPlot(object, features = "feature")
> 2. ExIPlot(object = object, type = ifelse(test = split.plot, yes = "splitViolin", 
>  .     no = "violin"), features = features, idents = idents, ncol = ncol, 
>  .     sort = sort, assay = assay, y.max = y.max, same.y.lims = same.y.lims, 
>  .     adjust = adjust, pt.size = pt.size, cols = cols, group.by = group.by, 
>  .     split.by = split.by, log = log, slot = slot, combine = combine)
> 3. lapply(X = features, FUN = function(x) {
>  .     return(SingleExIPlot(type = type, data = data[, x, drop = FALSE], 
>  .         idents = idents, split = split, sort = sort, y.max = y.max, 
>  .         adjust = adjust, cols = cols, pt.size = pt.size, log = log))
>  . })
> 4. FUN(X[[i]], ...)
> 5. SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents, 
>  .     split = split, sort = sort, y.max = y.max, adjust = adjust, 
>  .     cols = cols, pt.size = pt.size, log = log)

The only plot, that we can produce, is a HeatMap. In the attached file you can find the expression data from 'data' slot of working assay. You might find some negative values there due to previous integration of samples. Thank you very much for your help in advance!
[featureexpression.txt](https://github.com/satijalab/seurat/files/4936934/featureexpression.txt)

**Comment by satijalab** [comment]
We can take a look at this, would you be able to send a copy of the object (or a Dropbox link) to
Email: seuratpackage@gmail.com

please also include the FeaturePlot command you are running

**Comment by vkavaka** [comment]
Thanks you for your fast reply! I emailed you with a link for an rds file on dropbox and command, which we ran so far.

**Comment by jaisonj708** [comment]
You have a metadata column named "CD69," and our plotting functions usually search metadata before assays. If you rename this column, everything should work fine
