### ISSUE TITLE
CalcAligmentMetric in Seurat v3

### ISSUE THREAD

**Issue by nixstix** [satijalab/seurat#3278]
Hi Seurat team,

Thanks for the awesome package.

I was interested to know if there are plans to implement a `CalcAlignmentMetric` function in Seurat 3?

**Comment by satijalab** [comment]
We offer the MixingMetric and LocalStruct functions, which implement the metrics described in the V3 paper. Stay tuned for improved metrics in future releases as well!

**Comment by nixstix** [comment]
Oh this is great news! Thanks very much!
