### ISSUE TITLE
PlotClusterTree options

### ISSUE THREAD

**Issue by namelast** [satijalab/seurat#328]
I have tried to find the other options that could be passed to PlotClusterTree but I cannot find them. How can I customize the Cluster tree plot?

Using the calculated cluster.tree slot into ape::plot.phylo does not work.

Thanks

**Comment by andrewwbutler** [comment]
Hi,

You can pass any of the `plot.phylo` parameters from the ape package via the `...` in `PlotClusterTree`. For example:

```R
?ape::plot.phylo
PlotClusterTree(pbmc_small, edge.color = "red")
```

**Comment by namelast** [comment]
Thanks for the reply Andrew, however it does not seem to work for all options (e.g. direction and labels wither give error or are ignored). Editing the PlotClusterTree function to put the desired options in the plot.phylo function works, though.
