### ISSUE TITLE
FindMarkerGenes on Integrated Data

### ISSUE THREAD

**Issue by salehsereshki** [satijalab/seurat#3282]
Hi Seurat team,

I am working with 6 samples of scRNA data. I am trying to integrate these samples and then cluster, identify cell types, and DE analysis. In the vignettes for data integration and analysis, I saw that for DE analysis you said we need to set 'RNA' assay as default assay to compute the marker genes of clusters. My question is that when we have batch effect in our samples and the 'RNA' assay contains the expressions before the batch effect removal, how can we trust the results of DE analysis for 'RNA' assay. The results might be affected by the batch effects.

**Comment by timoast** [comment]
You can add batch as a latent variable in the model when performing DE (when using certain tests, eg the LR test).
