### ISSUE TITLE
problem not solved in issue #3248 labeled as bug

### ISSUE THREAD

**Issue by Coolchong** [satijalab/seurat#3283]
Thank you for looking into this question #3248 
but I still have some issues using averageexpression function. The average expression works fine without subsetting:
levels(x)<-c("Macrophage_lysmwt","Macrophage_lysmp21","Monocyte_lysmwt","Monocyte_lysmp21" )

avg<-AverageExpression(x,assay = "RNA",features = c("Il1a","Il1b","Vegfa"),return.seurat = T)
FetchData(avg,vars = c("Il1a","Il1b","Vegfa"),slot = "scale.data")
                                             Il1a         Il1b           Vegfa
Macrophage_lysmwt 0.5128832 -0.8978258 0.1544425
Macrophage_lysmp21 1.1419768 0.4970158 1.3454689
Monocyte_lysmwt -1.0056982 1.1664691 -0.8931231
Monocyte_lysmp21 -0.6491618 -0.7656592 -0.6067882

However, after subsettings it returned to same value again
Idents(x)<-"rawcelltype"
levels(x)
[1] "Macrophage" "Monocyte"
macs<-subset(x,idents = "Macrophage")
all.genes <- rownames(macs)
macs.scale <- ScaleData(macs, features = all.genes)
macs.scale$rawcelltype.genotype <- paste(macs.scale$rawcelltype, macs.scale$genotype, sep = "_")
Idents(macs.scale)<-"rawcelltype.genotype"
levels(macs.scale)<-c("Macrophage_lysmwt","Macrophage_lysmp21")
avg1<-AverageExpression(macs.scale,assay = "RNA",features = c("Il1a","Il1b","Vegfa"),return.seurat = T)
FetchData(avg1,vars = c("Il1a","Il1b","Vegfa"),slot = "scale.data")
                                               Il1a          Il1b       Vegfa
Macrophage_lysmwt -0.7071068 -0.7071068 -0.7071068
Macrophage_lysmp21 0.7071068 0.7071068 0.7071068

The data slot from both averages look the same, only the scale.data slot somehow changed, I don't understand why:
FetchData(avg,vars = c("Il1a","Il1b","Vegfa"),slot = "data")
                                              Il1a     Il1b        Vegfa
Macrophage_lysmwt 0.9392068 3.787149 0.9940962
Macrophage_lysmp21 1.2468417 3.922814 1.4296236
Monocyte_lysmwt 0.1966008 3.987926 0.6110288
Monocyte_lysmp21 0.3709517 3.800003 0.7157340

FetchData(avg1,vars = c("Il1a","Il1b","Vegfa"),slot = "data")
                                            Il1a         Il1b     Vegfa
Macrophage_lysmwt 0.9392068 3.787149 0.9940962
Macrophage_lysmp21 1.2468417 3.922814 1.4296236

Thanks again!

**Comment by andrewwbutler** [comment]
Hi,

The scaling here is occurring across your ident groups at the gene level (i.e. the columns of the matrix returned by `FetchData`). What it is doing is centering the vector of expression values by subtracting the mean and the scaling the expression level by dividing by their standard deviation (equivalent to running the `scale` function on a vector in base R). When you only have two values per column, this will result in exactly what you're seeing here. Scaling can be useful when you want to look at the relative levels of expression but when you only have two things to compare, the utility of the values themselves is limited.
