### ISSUE TITLE
Clustering of integrated data and cell type identification

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#3284]
Dear all,

I followed the vignette:
https://satijalab.org/seurat/v3.2/integration.html with SCTransform to integrate 9 SC datasets.

1. How do I run the usual clustering and marker gene calculation afterwards on the integrated data? Just the usual steps using the "integrated" assay?
2. Is there a method that tells me how many dims I should use to cluster my data? Like JackStraw for a single dataset?

Thanks, best, Chris

**Comment by timoast** [comment]
1. Yes, but use the RNA (uncorrected) assay for differential expression and visualization
2. See the pbmc3k tutorial: https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html

**Comment by balthasar0810** [comment]
Thanks, BUT:
2. you cant use the JackStraw on SCT data...

**Comment by timoast** [comment]
Correct. There are other methods suggested in the pbmc3k vignette that are applicable to SCT data

**Comment by balthasar0810** [comment]
OK :-( JackStraw was the only method that really worked in the past though...

**Comment by balthasar0810** [comment]
Sorry to ask once more:
If I work with an INTEGRATED assay (comprising 9 SC datasets) and I want to do 
1. differential gene expression between clusters (which are shared by all samples)
2. marker gene discovery,
I should work with the RNA assay? 
I do not understand the sense of this as there is no correction for percent.mito or UMI in this assay as far as I know...

Thanks for the replies in advance!
