### ISSUE TITLE
unlimited warning reached iteration limit in sctransform

### ISSUE THREAD

**Issue by MWRR** [satijalab/seurat#3285]
Hi 
I got hundreds of warning "reached iteration limit" when I run 

Sproject <- SCTransform(Sproject, vars.to.regress = c("percent.mt", "percent.rps", "percent.rpl", "percent.rrna", "nCount_RNA", "nFeature_RNA"), verbose = FALSE, return.only.var.genes = FALSE)

and the run was killed, and the same happened when I changed return.only.var.genes to TRUE. 
I checked all issues [#1426](https://github.com/satijalab/seurat/issues/1426), [#1378](https://github.com/satijalab/seurat/issues/1378), [#25](https://github.com/ChristophH/sctransform/issues/25), but no solution work.

I stuck at this and I could not move to the next step in my code, any help, please.

**Comment by scideas** [comment]
Although you won't be able to use the SCTransform algorithm, a bypass would be to run normal normlization and scaling prior to RunPCA()
The sequence would be: 
NormalizeData()
ScaleData(Sproject, vars.to.regress= c("percent.mt", "percent.rps", "percent.rpl", "percent.rrna", "nCount_RNA", "nFeature_RNA") )
RunPCA()
...
This at least worked for me when I was having issues.

**Comment by timoast** [comment]
This was addressed by @ChristophH in https://github.com/ChristophH/sctransform/issues/25. My guess would be that if you decreased the number of latent variables in the model you might see less of these cases where you can't reliably estimate theta, but Christoph or @yuhanH might be able to comment further
