### ISSUE TITLE
Dynamic link library R.dll issue during installation ? 

### ISSUE THREAD

**Issue by niduan07** [satijalab/seurat#3286]
Hi I have been trying to install Seurat on my Windows system. 

I followed as below: 

# Enter commands in R (or R studio, if installed)
install.packages('Seurat')
library(Seurat)

the first line is fine and retrieve: 

"package 'Seurat' successfully unpackaged and MD5 sums checked"
"The downloaded binary packages are in C:\...."

However, the second line retrieve error as: 

"The procedure entry point CAR0 could not be located in the dynamic link library R.dll." 

And I have tried to install with R3.6 or R4.0 and both of them would retrieve similar problem. 

Could anyone please help ? 

Thanks.

**Comment by Dragonmasterx87** [comment]
Over time you have installed multiple versions of R and which has resulted in library conflicts across multiple libraries on your system. Check the path of your current R library (Tools > Global Options...) and change it to point towards wherever your R libraries are stored, for your current R version. If this doesn't work, do a hard uninstall, remove all R libraries, restart your system, and install R afresh.

🐉

**Comment by niduan07** [comment]
Hi Dragon @Dragonmasterx87 , 

I just followed your advice and checked the R on my computer, and after clean and re-install my R package, I think I have solved the aforementioned "bug", thanks a lot for your help !
