### ISSUE TITLE
SCE to seurat:  invalid class “DimReduc” object: invalid object for slot "cell.embeddings" 

### ISSUE THREAD

**Issue by silvainp** [satijalab/seurat#3287]
Hi everyone,

I have an issue trying to transform my SingleCellExperiment data into Seurat. All analyses were performed on scran and I would like to do complementary work using Seurat. I don't understand the missing data and I got this error.

sce.seurat <- as.Seurat(sce, counts = "counts", data = "logcounts")
(counts are my raw counts and log counts the normalised/corrected one.)

Issue:
Error in validObject(.Object) : invalid class “DimReduc” object: invalid object for slot "cell.embeddings" in class "DimReduc": got class "data.frame", should be or extend class "matrix"

Any ideas? or another way to transform my data to Seurat?

Many thanks for your help.

**Comment by mojaveazure** [comment]
One or more of your reduced dimensions in your `SingleCellExperiment` object is a `data.frame`, not a `matrix`; Seurat requires that cell embeddings (`reducedDims` in the SCE world) are of class `matrix`, so you'll need to convert your reduced dimensions to matrices

**Comment by silvainp** [comment]
Thanks Paul,

Could you point me to a methods to do that?

Many thanks for your help.

Best,

Silvain

_____________________________
Silvain Pinaud, PhD
Research Associate
Tim Halim group
Cancer Research UK, Cambridge Institute
Li Ka Shing Centre, Robinson Way, Cambridge CB2 0RE, UK

**Comment by genecell** [comment]
Hi @silvainp, you can covert your data.frame object to matrix object using `as.matrix()`.
