### ISSUE TITLE
Extract individual plots from DimPlot (split.by)

### ISSUE THREAD

**Issue by mvis1231** [satijalab/seurat#3289]
Hi, 

I re-ran the integration on the previous integrated data and a new query dataset.

I've used SplitObject() and subset() functions to extract individual plots split by samples from Dimplot, but the functions seem to rearrange the colors for the populations of the query dataset. I am pretty sure this happens because I re-ran the integration on the previously integrated and the new query data.

When I only run the function, DimPlot(re.integrated, split.by = "sample", reduction = "umap", label = FALSE, label.size = 4, pt.size = 0.5), then the colors for all integrated datasets are uniform. 
However, I need to extract the individual plot, because the plots are all squeezed since there are 5 datasets. I have also tried using "combine = F" in DimPlot, but it only returned "Null", so it didn't work.

Could you please kindly let me know how I can extract the individual plot from DimPlot without using SplitObject() or subset() functions?

Thank you for your assistance in advance!

**Comment by samuel-marsh** [comment]
Hi,

With `DimPlot` you can provide vector of cells to the `cells` call in the function to plot only those cells.  Simply pull barcodes associated with a single sample and supply those to DimPlot and that should work.

Best,
Sam
