### ISSUE TITLE
Different Results Using FindClusters

### ISSUE THREAD

**Issue by dmoaks** [satijalab/seurat#329]
Hi,

I am running Seurat 2.2.1 and am getting different clustering results than when I had run the data set previously with the same settings. Before it was identifying 11 clusters and now it is finding 6 that don't line up all that well with the clusters you can see by eye in a tSNE plot. Unfortunately I'm not sure which version of Seurat I was using before, but can you think of any new modifications to this function that might be the cause of these results, or know what I might be doing wrong?

Thanks in advance,
Dan Moakley

**Comment by dmoaks** [comment]
An update...when I run FindClusters using PCA dimensions 1:10, the function returns the appropriate clusters. It also works when I run FindClusters using tSNE after running it previously using PCA, but returns jumbled results if I run it using tSNE the first time. If you know what the issue might be please help me understand so I don't have to worry about inaccurate results due to a problem with the clustering algorithm.

**Comment by satijalab** [comment]
The clustering and tSNE steps are independent (assuming you run both clustering and tSNE on input PCA dimensions). However, we typically use the same dimensions for both, and the results should agree visually, as both methods attempt to find structure in local neighborhoods.

It sounds like you are trying to run FindClusters directly on the tSNE, but using a precomputed tSNE from an old object. I'm not sure what is happening but you should just recalculate the tSNE here.
