### ISSUE TITLE
extract corrected UMI counts after SCTransform datasets integration

### ISSUE THREAD

**Issue by MagdalenaMat** [satijalab/seurat#3294]
Hi!
 I'd like to extract corrected UMI counts after I integrated 2 datasets using SCTransform integration workflow.
I tried

` integrated@assays$integrated@counts`

but this slot is empty.

my workflow:

`for (i in 1:length(data_list)) {
  data_list[[i]] <- SCTransform(data_list[[i]], verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = data_list, nfeatures = 3000)
data_list <- PrepSCTIntegration(object.list = data_list, anchor.features = features, 
                                    verbose = FALSE)

anchors <- FindIntegrationAnchors(object.list = data_list, normalization.method = "SCT", 
                                           anchor.features = features, verbose = FALSE)
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", 
                                     verbose = FALSE)`

**Comment by satijalab** [comment]
We do not (and in fact, cannot) compute corrected UMI counts after integration using SCTransform, which is why the slot is empty.
