### ISSUE TITLE
Creating Reference Dataset in Seurat from Large .csv

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#3295]
I am trying to use Seurat's anchor functions to predict cell identities using a reference data set.  My experimental data is from the temporal cortex.  The reference data I am using was downloaded from here: https://portal.brain-map.org/atlases-and-data/rnaseq/human-m1-10x.   I downloaded the 7 GB gene expression matrix .csv file.  This csv file is so large that R cannot create a seurat object from it.  I am looking for a fix to this issue, or perhaps a better way to predict cell identities using Seurat.   

> library(Seurat)
> library(dplyr)
> library(Matrix)
> library(ff)
> library(data.table)
> memory.limit(24000)
[1] 24000
> raw_counts<-fread(file="C:/Users/danie/Documents/csv.files/Reference Data/matrix.csv")
|--------------------------------------------------|
|==================================================|
> reference.data <- CreateSeuratObject(counts = raw_counts, project = "Reference_Data")
Error: cannot allocate vector of size 598 Kb

**Comment by samuel-marsh** [comment]
Hi,

Does the csv load successfully into R?  If so, then what happens if you convert it to sparse matrix format and then create Seurat object from sparse matrix?

Best,
Sam

**Comment by danielcgingerich** [comment]
@samuel-marsh , that is a good idea, thanks! 
The .csv loads successfully into R when I use fread().   I am still trying to convert to a sparse matrix but am having trouble.  Raw_counts is a data.table.  When using as(raw_counts, "sparseMatrix"), I get an error that R has no method of converting data.table to matrix.  So then I try to convert raw_counts to a regular matrix.  as.matrix(raw_counts)... and i get the familiar "cannot allocate vector of size ___" error again.  

raw_counts <- as(raw_counts, "sparseMatrix")
Error in as(from, "CsparseMatrix") : 
  no method or default for coercing “data.table” to “CsparseMatrix”
> as.matrix(raw_counts)
Error: cannot allocate vector of size 598 Kb

**Comment by timoast** [comment]
This indicates that you have an incredibly small memory limit (cannot allocate vector of size 598 Kb). How much RAM do you have? It is slightly confusing that you can read in the data.table but then can't convert to a matrix.

Can you also show the first few rows and columns of `raw_counts`?

**Comment by gegenhu** [comment]
I ran into this same issue with the same dataset. Again, I can successfully load this csv file into R with the fread package, but receive an error when converting the data.table directly to a sparse matrix in R (no method of converting data.table to matrix). When I try to convert the data.table to a regular matrix using as.matrix(raw_counts), I don't receive an error about the memory limit, but R freezes, even when running with high memory (256 GB on hpc).

**Comment by mollenkt** [comment]
We're aware of the issue at the Allen Institute and intending to release the data in a compressed/sparse format in the coming months. Hopefully others can identify a short-term fix, but I wanted to share that an update is coming.

**Comment by dwkolonay** [comment]
Hello- 

I have run into this issue with a different dataset. The published scRNA-Seq data is available as a .csv file, and I am unable to create a Seurat object from it. Should I convert this into a sparse matrix, and how would I do that? Thanks!

data <- read.csv('GSE126128_AllTimePoints_WT_10X.csv.gz', header=TRUE, row.names=1)
> gc()
            used   (Mb) gc trigger    (Mb)   max used    (Mb)
Ncells   3314190  177.0    9057754   483.8   26576823  1419.4
Vcells 885814724 6758.3 1661288511 12674.7 1661283293 12674.6
> pbmc <- CreateSeuratObject(counts = data, project = "775to975", min.cells = 3, min.features = 200)
Error: cannot allocate vector of size 1.2 Gb
