### ISSUE TITLE
Warning message when open library (Seurat) in R

### ISSUE THREAD

**Issue by taopeng1100** [satijalab/seurat#3296]
> library(Seurat)
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users\tpeng\AppData\Local\Continuum\anaconda3\envs\rstudio/python.exe": The system cannot find the file specified

**Comment by timoast** [comment]
This is a warning related to conda/anaconda, python, and reticulate and can be ignored unless you're planning to use the python functionality in Seurat (Leiden clustering and umap-learn)
