### ISSUE TITLE
Weird data distribution after SCT integration

### ISSUE THREAD

**Issue by ktrns** [satijalab/seurat#3297]
Hi there, 

We are working with Seurat and as a sequencing facility, we are analysing scRNA-seq data for our clients. We are currently incorporating support for multiple samples and have observed weird distributions after integrating SCT data. 

To visualise the effect of normalisation, we use the "data" slot and RLE plots. We randomly sample 100 cells, and calculate relative log expression as follows. For each gene, we calculate its median expression across all cells, and then calculate the deviation from this median for each cell. For each cell, we plot the median expression (black), the interquartile range (lightgrey), whiskers defined as 1.5 times the interquartile range (darkgrey), and outliers in blue/orange dependent on the sample of origin. Below are 2 RLE plots, before and after integration, using . 

<img width="596" alt="RLE_SCT" src="https://user-images.githubusercontent.com/9417927/88157283-d7c56a80-cc0a-11ea-8d80-364573426269.png">
<img width="607" alt="RLE_SCTintegrated" src="https://user-images.githubusercontent.com/9417927/88157294-dbf18800-cc0a-11ea-93e2-f9b5fcac1b73.png">

Do you have any idea, where this behaviour (top right, orange sample) comes from and whether this is acceptable? We can see this for multiple datasets. 

FYI: This is how we did the integration:
```
    # Find integration anchors for assay SCT
    integrate_SCT_features = SelectIntegrationFeatures(object.list=sc_objs, nfeatures=3000, assay=rep("SCT", length(sc)), verbose=FALSE)
    sc_objs = PrepSCTIntegration(object.list=sc_objs, anchor.features=integrate_SCT_features, verbose=TRUE)
    integrate_SCT_anchors = FindIntegrationAnchors(object.list=sc_objs, normalization.method="SCT", anchor.features=integrate_SCT_features, assay=rep("SCT", length(sc_objs)), verbose=FALSE)
    sc_objs = Seurat::IntegrateData(integrate_SCT_anchors, new.assay.name="SCTintegrated", normalization.method="SCT", dims=1:ndims, verbose=FALSE)
```

Many thanks in advance
Katrin

**Comment by satijalab** [comment]
Integrating samples with SCTransform works on the Pearson residuals (which have a very different distribution than the normalized data slot). I can see why the plot might seem weird, but this is not incorrect, or problematic.
