### ISSUE TITLE
Embedding output after Seurat v3 integration

### ISSUE THREAD

**Issue by LuckyMD** [satijalab/seurat#3298]
Hi,
Would you recommend working on the CCA-reduced space after integration? Or would you regard that as only an intermediate step in the integration process? And if it does make sense: how would I best go about accessing the integrated embeddings from a Seurat object?

**Comment by satijalab** [comment]
We typically view this as an intermediate step, because unique populations may mix together in the CCA, but remain separate after CCA-mediated anchor identification.

If you want to access the intermediate CCA emebddings, these are stored in the output of FindIntegrationAnchors

**Comment by LuckyMD** [comment]
Thanks for the info!

**Comment by RawanSO** [comment]
Hi,
I couldn't get the CCA embeddings from FindIntegrationAnchors object, Can you please help me with how to get them?
Thanks
