### ISSUE TITLE
Issue with FindMarkers

### ISSUE THREAD

**Issue by kevin199011** [satijalab/seurat#33]
I was running Seurat with some targeted sequencing data. My targeted sequencing data contains around 6000 cells and 300 genes. However, when I came to the step of finding differential markers, I have an error message:

Error in apply(object@data[genes.use, cells.1], 1, function(x) return(length(x[x >  : 
  dim(X) must have a positive length

I don't have this issue when running with example PBMC data or my own transcriptome data. I'm wondering is it because the total number of genes are too small? If so, how can I fix this issue? Thank you!

Kevin

**Comment by andrewwbutler** [comment]
Hi Kevin,

I would try lowering the cutoffs you're using. You may have weaker markers in your data.
