### ISSUE TITLE
Understanding pre-processing stesp 

### ISSUE THREAD

**Issue by mscastillo** [satijalab/seurat#330]
I am trying to understand all the processing steps with Seurat, but I am struggling in the earliest steps.

I don't understand how nUMI is calculated. It is close to the total number of UMI per cell, but not exactly the same:

```
 obj <- CreateSeuratObject( raw.data=UMI ) # Omiting filtering by minimum number of genes or cells, but matrix and Seurat object dimensions match
 nUMI <- apply( UMI,2,sum )
 sum( nUMI - obj@meta.data$nUMI ) == 0 # this is FALSE, most of the elements of this vector are zero, but some others are negative, in (-1,-50).
```

Then the log-normalization, if I don't got it wrong, is done like:

` log( scale*data/nUMI ) # I am using scale=median( nUMI ) and tried also max( nUMI ) to avoid negative values `

but this is not the output of:

` NormalizeData( object=obj, normalization.method="LogNormalize", scale.factor=scale )@data`

**Comment by leonfodoulian** [comment]
Hi,

`nUMI` is calculated as the total number of UMI counts per cell from the raw data without filtering. The code uses `colSums()` to calculate that, and can be found at [line 84 in preprocessing.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/preprocessing.R#L84). Practically, there shouldn't be any difference with what you are computing. I would however check the number of elements in `nUMI` and `object@meta.data$nUMI`. 

Regarding normalization, the code is written in _cpp_, and can be found at [lines 111 to 122 in data_manipulation.cpp](https://github.com/satijalab/seurat/blob/master/src/data_manipulation.cpp#L111-L122). An equivalent R code would be:

```R
log(x = (t(x = t(x = data)/colSums(x = data)) * scale.factor) + 1)
```

Hope this helped!

Best,
Leon

**Comment by mscastillo** [comment]
Thanks Leon!

I see... my error during the normalization was in the matrix multiplication (such a shame!).

However, the nUMI  is still different, even if I use colSums (have already checked that the number of elements are the same in both variables). Anyway, the impact of this differences after normalization is minimum (RMSE~1e-17).

Once again, thanks! :)
