### ISSUE TITLE
cols assigned alphabetically, instead of in level order, for factor features

### ISSUE THREAD

**Issue by jfass** [satijalab/seurat#3300]
I've defined a metadata 'sample' feature as a factor, with levels = c( "D0", "D6", "D13", "D35" ) ... but when I plot using, say:

```VlnPlot( object, features='sample', cols=c('green','purple','orange','cyan') )```

But this plots using D0 = green, D6 = cyan, D13 = purple, D35 = orange ... with the legend in that order, top to bottom. In other words, the legend order obey's the factor's level order, but the colors are getting assigned in _alphanumerical_ order of the levels.

This is with Seurat 3.2.0

**Comment by satijalab** [comment]
You can use the ReorderIdent function to set levels based on your own criterion.

**Comment by timoast** [comment]
Just to follow up, I was not able to reproduce this issue:

```r
library(Seurat)

levels(pbmc_small)
VlnPlot(pbmc_small, features='MS4A1', cols=c('green','purple','orange'))

levels(pbmc_small) <- c("1", "2", "0")
VlnPlot(pbmc_small, features='MS4A1', cols=c('green','purple','orange'))

# test alphanumeric metadata
pbmc_small$testgroup <- sample(c("D1", "D2", "D3"), ncol(pbmc_small), replace = TRUE)
Idents(pbmc_small) <- "testgroup"

levels(pbmc_small) <- c("D3", "D2", "D1")
VlnPlot(pbmc_small, features='LYZ', cols=c('green','purple','orange'))

levels(pbmc_small) <- c("D1", "D2", "D3")
VlnPlot(pbmc_small, features='LYZ', cols=c('green','purple','orange'))
```
