### ISSUE TITLE
Code to highlight the 2 datasets into two colors in the final integrated scRNAseq plot 

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#3301]
Hi! I'm new to programming and single-cell data analysis. Here, I used Seurat to integrate 2 scRNAseq datasets from GEO database. However, the Seurat vignettes don't have detailed tutorials on using GEO database. I was able to generate the integrated data and integrated plot, however, I don't know how to highlight the two datasets in the plot into two colors only such that I can visually recognize how they merged and clustered according to cell types (this is similar to the part of the vignette where different scRNAseq technologies were integrated and colored accordingly in the final plot).       

Could you please suggest what code I am lacking below?  

```
library(Seurat)
library(dplyr)
library(cowplot)
library(ggplot2)
library(patchwork)
library(Matrix)

##### DATASET 1------------------------------ FILE.TXT - TPM data -------------------------------------------######
          #Read scRNAseq expression data
          data_TCS <- read.table(file = "tpm_all_scp.txt.gz", sep = "\t", header=TRUE, row.names=1) 
          head(data_TCS)

          #Create Seurat object
          TCS <- CreateSeuratObject(counts = data_TCS, min.cells = 5, min.features = 200)
          TCS

          # standard log-normalization
          TCS <- NormalizeData(TCS, verbose = FALSE)

          # variable features
          TCS <- FindVariableFeatures(TCS, selection.method = "vst", nfeatures=2000)

######  DATASET 2---------------------------- FILE.CSV - TPM data --------------------------------------#####
          #Read scRNAseq expression data
          data_TCE <- read.csv(file = "GSE115978_tpm.csv.gz", sep = ",", header=TRUE, row.names=1) 
          head(data_TCE)

          #Create Seurat object
          TCE <- CreateSeuratObject(counts = data_TCE, min.cells = 5, min.features = 200) 
          TCE

          # standard log-normalization
          TCE <- NormalizeData(TCE, verbose = FALSE)

          # variable features
          TCE <- FindVariableFeatures(TCE, selection.method = "vst", nfeatures=2000)

######---------------------------- PERFORM THE INTEGRATION------------------------------------######

          TC.anchors <- FindIntegrationAnchors(object.list = list(TCE, TCS), dims = 1:20)
          TC.anchors
          TC.combined <- IntegrateData(anchorset = TC.anchors, dims = 1:20)

#####----------------------------- PERFORM INTEGRATED ANALYSIS--------------------------------######
#Now we can run a single integrated analysis on all cells!

          DefaultAssay(TC.combined) <- "integrated"
 
          # Run the standard workflow for visualization and clustering
          TC.combined <- ScaleData(TC.combined, verbose = FALSE)
          TC.combined <- RunPCA(TC.combined, npcs = 30, verbose = FALSE)

          # t-SNE and Clustering
          TC.combined <- RunUMAP(TC.combined, reduction = "pca", dims = 1:20)
          TC.combined <- FindNeighbors(TC.combined, reduction = "pca", dims = 1:20)
          TC.combined <- FindClusters(TC.combined, resolution = 0.5)
          TC.combined

          # Visualization
          p1 <- DimPlot(TC.combined, reduction = "umap")
          p2 <- DimPlot(TC.combined, reduction = "umap", label = TRUE)
          plot_grid(p1, p2)
```

Note: In the integrated plot, I hoped that I could make the left plot colored with two colors according to dataset origin, and the right plot as cell type reference. I was thinking of using "group.by = _____" function for the left plot, but I don't know what to put as an argument. 

![image](https://user-images.githubusercontent.com/68268222/88299575-16efda80-cd35-11ea-8fe6-dc077d50d0e7.png)

**Comment by cdarby** [comment]
See the Seurat `AddMetaData` function. You need to add metadata to both of the Seurat objects before integration - e.g. you would add a metadata field named "experiment.name" like:
`TCS <- AddMetaData(object = TCS, metadata = "TCS", col.name = "experiment.name")`
`TCE <- AddMetaData(object = TCE, metadata = "TCE", col.name = "experiment.name")`
Then, after integration, you can use "experiment.name" as the group.by field in your DimPlot.
