### ISSUE TITLE
Trouble shoot, Seurat recognize datafile

### ISSUE THREAD

**Issue by Abicumaran** [satijalab/seurat#3302]
Hi,

I am having R issues with having the csv file with my dataset get recognized by Seurat. Can someone please guide how can I get Seurat to import a csv file instead of a text file into R-studio? Can I follow the pbmc tutorial code, as it is, after importing the dataset if it is in the same table format? I want to visualize the clusters and heatmaps.

**Comment by cdarby** [comment]
If your data is in CSV format, first use `read.csv` to read in the file. Then use the Seurat function `CreateSeuratObject` to create a Seurat object. After that, you could follow the tutorial.

**Comment by Abicumaran** [comment]
Thank you! But the issue is with the read.csv. When I use this, I get the following error message:

Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed

The csv file is a gene expression matrix of column headers denoting cells and the rows corresponding to genes.

**Comment by cdarby** [comment]
If the first column of the csv file contains the gene names, did you supply `row.names=1` parameter to `read.csv`?

**Comment by Abicumaran** [comment]
Yes, I wrote this:

pbmc.data <- read.table(file = "C:/Users/15145/Desktop/GBM.csv", row.names=1)

**Comment by cdarby** [comment]
Then, based on the error message you received, there must be duplicate row names (gene names) in your data file?

**Comment by Abicumaran** [comment]
Thank you for your guidance, but no I checked and that doesn't seem to be the issue. Would it please be possible to email me where I could send the csv file and have your feedback? It is a pediatric brain cancer dataset, and your help would be a privilege. Alternately, I can drop the csv file here for you to check?

Email: uabicumaran@gmail.com

**Comment by cdarby** [comment]
You could email the data (or a link such as Dropbox where I can get it) to seuratpackage@gmail.com and I will look at it. Happy to help.

**Comment by Abicumaran** [comment]
You are so very kind. Thank you. I just emailed the file in Google drive. This is the data of a single patient (we have many more). Please acknowledge receipt.

Thank you.
