### ISSUE TITLE
Error in RenameCells #3183

### ISSUE THREAD

**Issue by jstraubhr** [satijalab/seurat#3303]
I am trying label transfer with

FindTransferAnchors(reference=scRNAseqobj, query=scATACobj, reference.assay='RNA', query.assay='RNA', reduction='cca')

The reference is an integration object, query a merged object

The error
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

occurs in one of the several RenameCells() calls. This function call works with the query but not with the reference. The FindTransferAnchors code loops through the object assays. When it gets to the SCT assay it does this

suppressWarnings(Misc(object, slot = "vst.set") <- lapply(X = Misc(object = object, slot = "vst.set"), FUN = function(x) {
    new.names.vst <- new.names[which(x = x$cells_step1 %in% Cells(x = object))]
    x$cells_step1 <- new.names.vst
    rownames(x = x$cell_attr) <- new.names.vst
    return(x)
}))

the 4th line (rownames...) it cannot do since new.names.vst is empty and throws the error.

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/3183#issuecomment-663267090
