### ISSUE TITLE
Cell selector - Any updates on how to get around not have SDMTools?

### ISSUE THREAD

**Issue by jbridge873** [satijalab/seurat#3306]
Hi Guys,

I would love to be able to use the Cell Selector function but don't know how to get around SDMTools?
There was mention late last year of a workaround?

Many thanks,

Jennifer

**Comment by andrewwbutler** [comment]
Hi Jennifer,

If you install the latest Seurat version (3.2) we've replaced the SDMTools functionality in `CellSelector` with a Shiny gadget. If you want to use an older version, you'll have to install SDMTools from the CRAN archive. 
```R
install.packages("https://cran.rstudio.com//src/contrib/Archive/SDMTools/SDMTools_1.1-221.2.tar.gz", repos = NULL)
```
