### ISSUE TITLE
Possibility of Swapping out Cell Embeddings in Seurat Object

### ISSUE THREAD

**Issue by danielg52** [satijalab/seurat#3309]
Hi,

I am curious if it is possible to replace the embedding dimensions created by RunPCA (and can be found with the line "Embeddings(object = pbmc, reduction = 'tsne')") with another set of embeddings created by a separate algorithm outside of Seurat.

Thanks.

**Comment by RegnerM2015** [comment]
Hi @danielg52 

Yes this is possible to swap out the **cell embeddings**. You can see what the cell embedding data looks by using the @reductions$pca@cell.embeddings handle on the Seurat object. 

For PCA embeddings:
`seurat_object@reductions$pca@cell.embeddings <- new.cell.embeddings`

For TSNE embeddings:
`seurat_object@reductions$tsne@cell.embeddings <- new.cell.embeddings`

**Comment by danielg52** [comment]
How would I convert my new embedding into the appropriate format in the Seurat object? The embedding I want in my Seurat is a data.frame class with 2 columns, each column representing a dimension.

Thanks

**Comment by timoast** [comment]
You should not modify the cell embeddings in an existing DimReduc object. Instead you can create a new DimReduc object using the `CreateDimReducObject()` function and add it to the Seurat object
