### ISSUE TITLE
pancreas_expression_matrix.rds file in integration

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3310]
Hello, 

I tried to use `https://satijalab.org/seurat/pancreas_integration_label_transfer.html`.

I have many *.csv files,for example: h1.csv, h2,csv, h3,csv, m1.csv, m2.csv, m3.csv. How I can combine all these *.csv files into one pancreas_expression_matrix before integration.

Thank you in advance for great help!

Best,

Yue

![Screenshot from 2020-07-26 21-17-16](https://user-images.githubusercontent.com/40526984/88494863-d9ce5700-cf85-11ea-83e6-5c7e3a882895.png)

**Comment by cdarby** [comment]
After creating a Seurat object from each of your CSV files, if you want to merge these objects together please refer to the `merge` function.
https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/merge.Assay

Note that this function does not perform any integration, which may not be what you want. It simply merges the objects.

**Comment by yueli711** [comment]
Hello cdarby,
Thank you so much for your great help!
If I want to use the following commands, how I can make the pancreas_expression_matrix.rds file?
Thank you again and really appreciated!
Best,
Yue

> pancreas.data <- readRDS(file = "pancreas_expression_matrix.rds")
> metadata <- readRDS(file = "pancreas_metadata.rds")
> pancreas <- CreateSeuratObject(pancreas.data, meta.data = metadata)

**Comment by Dragonmasterx87** [comment]
You might want to see this [Human Pancreas Atlas](https://github.com/Dragonmasterx87/Human-Pancreas-single-cell-RNA-expression-Atlas)

**Comment by yueli711** [comment]
Hello Dragonmasterx87, 

Thank you so much for your response!

I only want to know how I can combine multiple matrix into one pancreas_expression_matrix.

Where is pancreas_expression_matrix come from?

Thank you in advance for your great help!

Best,

Yue

     > pancreas.data <- readRDS(file = "pancreas_expression_matrix.rds")

**Comment by cdarby** [comment]
@yueli711 In the vignette you linked to in your original post, the example data files including "pancreas_expression_matrix.rds" are available by clicking on a hyperlink in the 2nd paragraph, which I reproduce here for your convenience.

https://www.dropbox.com/s/1zxbn92y5du9pu0/pancreas_v3_files.tar.gz?dl=1

**Comment by yueli711** [comment]
Hello cdarby,

Thank you so much for your quick response!

My question is: how I can combine multiple matrix into one pancreas_expression_matrix?

Thank you in advance for your great help!

Best,

Yue

**Comment by Dragonmasterx87** [comment]
@yueli711 There are multiple ways to do this. I would personally annotate and add metadata for specific datasets (change cell ids to reflect (dataset and sample info), then merge using Seurat [merging in Seurat](https://satijalab.org/seurat/v3.1/merge_vignette.html#:~:text=To%20merge%20more%20than%20two,PBMC%20tutorial%20(download%20here).) after completing this, I would just extract a gene expression matrix from the merged seurat object using something like whats shown here under 'Data Access': [Seurat Cheat sheet](https://satijalab.org/seurat/essential_commands.html)

```
# Retrieve or set data in an expression matrix ('counts', 'data', and 'scale.data') 

GetAssayData(object = pbmc, slot = "counts")
pbmc <- SetAssayData(object = pbmc, slot = "scale.data", new.data = new.data)
```

**Comment by Dragonmasterx87** [comment]
The above allows you to maintain a Seurat object and also extract a gene expression matrix for other purposes you have in mind.

**Comment by yueli711** [comment]
Hello Dragonmasterx87，

Thank yo so much for your great help!

Best,

Yue
