### ISSUE TITLE
 IntegrateData returns a bloated Seurat object

### ISSUE THREAD

**Issue by dariomel** [satijalab/seurat#3312]
following the procedure in [Integration and Label Transfer - SCTransform](https://satijalab.org/seurat/v3.1/integration.html#sctransform), and after calling `FindIntegrationAnchors`, I get
```R
class(s)
[1] "AnchorSet"
attr(,"package")
[1] "Seurat"

sapply(slotNames(s),function(i)object.size(slot(s,i)))
      object.list   reference.cells reference.objects       query.cells 
       1690841832                48                56                48 
          anchors           offsets   anchor.features           command 
           805656                64            192048        7806783080

object.size(s@command@call.string)
7806586984 bytes
```
Notice anything strange?
Then, after calling `IntegrateData`, I obviously get
```R
class(s)
[1] "Seurat"
attr(,"package")
[1] "Seurat"

sapply(slotNames(s),function(i)object.size(slot(s,i)))
      assays    meta.data active.assay active.ident       graphs    neighbors 
  2969142344      2058224          112      1221008           48           48 
  reductions project.name         misc      version     commands        tools 
          48          120           48          424   7807172400       807744 

object.size(s@commands[["FindIntegrationAnchors"]]@call.string)
7806586984 bytes
```

In other words, the `call.string` character vector for command `"FindIntegrationAnchors"` in the `Seurat` object returned by `IntegrateData` is consuming more than twice the amount of memory consumed by the assays in the same `Seurat` object. Is this really necessary?
The problem is in function `LogSeuratCommand`,

https://github.com/satijalab/seurat/blob/72a0c7b61adcf1d6630db9e952bf8b0d4f979295/R/objects.R#L1463

where [`deparse`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/deparse) returns the textual representation of one or more massive matrices.
It is possible that other functions may be returning bloated `Seurat` objects for the same reason.

**Comment by andrewwbutler** [comment]
Hi,

I agree that we wouldn't want the `call.string` to contain another copy of the matrices as characters but I haven't been able to reproduce what you're seeing here.

```R
> library(Seurat)
> library(SeuratData)
> data('panc8')
> pancreas.list <- SplitObject(panc8, split.by = "tech")
> pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
> pancreas.list <- lapply(X = pancreas.list, FUN = SCTransform, verbose = FALSE)  
There were 50 or more warnings (use warnings() to see the first 50)
> pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 3000)
> pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features, verbose = FALSE)
> pancreas.anchors <- FindIntegrationAnchors(object.list = pancreas.list, normalization.method = 'SCT', anchor.features = pancreas.features, verbose = FALSE)
> sapply(slotNames(pancreas.anchors),function(i)object.size(slot(pancreas.anchors,i)))
      object.list   reference.cells reference.objects       query.cells           anchors           offsets   anchor.features           command 
       1918248120                48                64                48           1223128                80            193200            198520 
> object.size(pancreas.anchors@command@call.string)
352 bytes
> pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, normalization.method = 'SCT', verbose = FALSE)
Warning: Adding a command log without an assay associated with it
> sapply(slotNames(pancreas.integrated),function(i)object.size(slot(pancreas.integrated,i)))
      assays    meta.data active.assay active.ident       graphs    neighbors   reductions       images project.name         misc      version     commands        tools 
  2262400464       922776          120       486824           48           48           48           48          120           48          424       590192      1225256 
> object.size(pancreas.integrated@commands[["FindIntegrationAnchors"]]@call.string)
352 bytes
```
The idea was just to store a string of the command that was run in that slot. `deparse` here is being called on one of the `call` objects returned by `sys.calls()`. These should be unevaluated function calls that just get converted to the equivalent text as strings. However, if there are situations where that could go wrong and end up unnecessarily duplicating data, we'd definitely want to fix that.

**Comment by dariomel** [comment]
you are right about your code example, but try calling `FindIntegrationAnchors` like this, which is the way I call it in my code:
```R
pancreas.anchors <- do.call("FindIntegrationAnchors",list(object.list = pancreas.list, normalization.method = 'SCT', anchor.features = pancreas.features, verbose = FALSE))
> sapply(slotNames(pancreas.anchors),function(i)object.size(slot(pancreas.anchors,i)))
```
You will notice that it takes a very long time to complete, compared to calling `FindIntegrationAnchors` without `do.call`, and returns a massive character vector in `pancreas.anchors@command@call.string`.
Actually, the first time you try using `do.call` as above it will fail with the following error:
```R
Error in deparse(expr = sys.calls()[[which.frame]]) : 
  no slot of name "assay.orig" for this object of class "Assay"
```
You can fix that with `panc8<-UpdateSeuratObject(panc8)` at the beginning of your code example.

**Comment by andrewwbutler** [comment]
Hmm, interesting. I guess we hadn't anticipated users calling Seurat functions in that manner with `do.call`. Is there a reason you prefer running functions with `do.call` rather than just with the function name? Currently, it seems the logging framework doesn't play nicely with that way of running things.

**Comment by dariomel** [comment]
I do have a reason to use `do.call`, but it is off-topic.
I will avoid using `do.call` with Seurat's functions, but you may want to document such limitation so that other users do not fall in the same trap.

**Comment by andrewwbutler** [comment]
Ok, I've modified the problematic section of `LogSeuratCommand` that you highlighted above to handle running the functions via `do.call()`. This is available now on the `develop` branch if you want to give it a try. Hopefully that resolves the issue.

**Comment by dariomel** [comment]
the proposed solution works, but only in the unlikely event that `do.call` is called directly from the global environment, i.e., interactively at the command line, because the new if-statement always checks the first call:
```R
LogSeuratCommand <- function(object, return.command = FALSE) {
  time.stamp <- Sys.time()
  object <- UpdateSlots(object = object)
  #capture function name
  which.frame <- sys.nframe() - 1
  if (which.frame < 1) {
    stop("'LogSeuratCommand' cannot be called at the top level", call. = FALSE)
  }
  if (as.character(x = sys.calls()[[1]])[1] == "do.call") {
    call.string <- deparse(expr = sys.calls()[[1]])
    command.name <- as.character(x = sys.calls()[[1]])[2]
  } else {
    command.name <- as.character(x = deparse(expr = sys.calls()[[which.frame]]))
    command.name <- gsub(pattern = "\\.Seurat", replacement = "", x = command.name)
    call.string <- command.name
    command.name <- ExtractField(string = command.name, field = 1, delim = "\\(")
  }
# ...
```
More likely is that `do.call` is called from within some function, in which case the `else` clause above is executed and the original problem resurfaces.
In this case one might think that the following would fix the problem,
```R
  if (as.character(x = sys.calls()[[sys.parent(1)]])[1] == "do.call")
```
but actually it doesn't because of the way that `do.call` invokes the given function.
Instead the following seems to successfully detect whether the caller of `LogSeuratCommand` was called through `do.call`:
```R
  if (as.character(x = sys.calls()[[sys.parent(1)-1]])[1] == "do.call")
```
but I wouldn't bet too much on it. Note that in this particular case `sys.parent(1) - 1 != sys.parent(2)`, because `do.call` introduces two extra frames.
It may be better to avoid using `do.call` altogether with Seurat functions, at least until Seurat switches to a more robust scheme for logging commands.
Indeed `do.call` is not the only problem. The following usage also breaks the current scheme:
```R
f <- PrepSCTIntegration
f(...)
FindIntegrationAnchors(...) # ERROR!
```

**Comment by timoast** [comment]
As a workaround, I've found that using `rlang::invoke()` rather than `do.call()` does not cause this problem

**Comment by timoast** [comment]
I will close this for now, I think the `rlang::invoke()` workaround is currently the best solution
