### ISSUE TITLE
unable to use ReadH5AD due to "Error duplicate 'row.names'"

### ISSUE THREAD

**Issue by guillemsanchezsanchez1996** [satijalab/seurat#3314]
Hello everyone,

I'm trying to use the thymus cell atlas data from Parker et al,2020 (Science) paper.
Processed data can be obtained from here --> https://zenodo.org/record/3572422

I'm trying to read the t cell h5ad file but seurat is not able to produce any object due to duplicate "row.names". I'm assuming tha this is because there are some genes listed with the same name...but i don't know how can I change this names, or how can I solve this problem without changing names

Any suggestions? Thank you for your help in advance!

Guillem

**Comment by mojaveazure** [comment]
Hi,

We are transitioning our support for AnnData/H5AD files to [SeuratDisk](https://github.com/mojaveazure/seurat-disk), our new package for interfacing `Seurat` objects with single-cell HDF5-based file formats. We would very much like it if you could give this a shot for reading in your data.

You can install SeuratDisk with the following:
```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")
```

A tutorial on how to read in AnnData/H5AD files via the h5Seurat intermediate can be found [here](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html). Greater detail about the new `Convert` mechanism can be found [here](https://mojaveazure.github.io/seurat-disk/reference/Convert.html)

If you come across any bugs in reading in your HDF5 files, please post them in mojaveazure/seurat-disk#1. Please note, there are some stipulations about the format of your AnnData/H5AD posted in https://github.com/mojaveazure/seurat-disk/issues/1#issue-619215532

**Comment by Vivianstats** [comment]
Hi Guillem, I am also trying to load this dataset into R and I wonder if you have figured out a solution?

mojaveazure,
I tried the SeuratDisk package with this dataset but encountered an error message. I posted the issue at https://github.com/mojaveazure/seurat-disk/issues/33.
