### ISSUE TITLE
FindNeighbors(): construct SNN graph in original feature space 

### ISSUE THREAD

**Issue by siyao-liu** [satijalab/seurat#3315]
Hi, 

I was just wondering if one can use FindNeighbors() function to construct SNN graph in the feature space not the PCA space? It seems to default to the PCA space and I can't change this default setting. Here is my code:

pbmc_small
# Compute an SNN on the gene expression level
pbmc_small <- FindNeighbors(pbmc_small, features = rownames(object = pbmc_small))

Error in `[[.Seurat`(object, reduction) :   Cannot find 'pca' in this Seurat object 

Thank you,
Siyao

**Comment by cdarby** [comment]
Yes, FindWeights can be run on an Assay, e.g. the "RNA" Assay in `pbmc_small`:

`FindNeighbors(pbmc_small[["RNA"]], features = rownames(pbmc_small))`
