### ISSUE TITLE
To UMAP like Scanpy

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#3316]
Not sure if this has been asked before, sorry if it has.

Is there a way to code for `DimPlot(seuratob, reduction = "umap")` to get graphics similar to those in scanpy?

```
rcParams['figure.figsize'] = 5, 5
sc.pl.umap(seuratob, color='clusters', add_outline=True, legend_loc='on data',
           legend_fontsize=12, legend_fontoutline=2,frameon=False,
           title='clustering of cells', palette='Set1')
```

Like code 9 here [scanpy tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/plotting/core.html)

![image](https://user-images.githubusercontent.com/39837140/88571408-37ed4f80-d003-11ea-85e9-5a5b0ab8b12a.png)
Thanks!

**Comment by satijalab** [comment]
We don’t currently support this kind of visualization. Probably the closest analogy is the schex package, which helps with overplotting issues in single-cell visualization. You can see more here (https://github.com/SaskiaFreytag/schex), and it’s supported in Seurat Wrappers
