### ISSUE TITLE
error in merge function

### ISSUE THREAD

**Issue by Diozao666** [satijalab/seurat#3318]
Hello
I'm trying to merge two Seurat objects with the following code:

`circBAL <- merge(x = circulating, y = BALF, add.cell.ids = c("circ", "BAL"), project = "circBAL")`

then I got this error message

`Error in `.rowNamesDF<-`(x, value = value) : 
  'row.names' com comprimento inválido`
"comprimento inválido" translates to "invalid length"

I assumed the error was that both objects did not have the same genes. So I used this instead:

`common.features <- intersect(rownames(circulating), rownames(BALF))
length(x = common.features)`

`circBAL <- merge(x = circulating[common.features, ], y = BALF[common.features, ], add.cell.ids = c("circ", "BAL"), project = "circBAL")`

the code ran for a while but I got the same error.

edit: I have also tried updating the objects
`UpdateSeuratObject(circulating)`
`UpdateSeuratObject(BALF)`

here are the objects:
> circulating
An object of class Seurat 
52722 features across 44721 samples within 2 assays 
Active assay: SCT (26361 features, 3000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
> BALF
An object of class Seurat 
25916 features across 66452 samples within 2 assays 
Active assay: RNA (23916 features, 2000 variable features)
 1 other assay present: integrated
 3 dimensional reductions calculated: pca, tsne, umap

Best,
Diogo

**Comment by timoast** [comment]
Does this work if you remove the SCT and integrated assays?

**Comment by JingleW** [comment]
> Does this work if you remove the SCT and integrated assays?

Hi, @timoast , could you please specify the code for removing the SCT and integrated assays? I met the same problem. Thank you.
