### ISSUE TITLE
Bug of RunTSNE with the process of fftRtsne function

### ISSUE THREAD

**Issue by helloicyvodka** [satijalab/seurat#3319]
Hi, I find that the FIt-sne has been updated to version 1.2. And this part of codes in fftRtsne may raised a bug. Please check, thanks!

`# check fast_tsne version
  ft.out <- suppressWarnings(expr = system2(command = fast_tsne_path, stdout = TRUE))
  if (grepl(pattern = '= t-SNE v1.1', x = ft.out[1])) {
    version_number <- '1.1.0'
  } else if (grepl(pattern = '= t-SNE v1.0', x = ft.out[1])) {
    version_number <- '1.0'
  } else {
    message("First line of fast_tsne output is")
    message(ft.out[1])
    stop("Our FIt-SNE wrapper requires FIt-SNE v1.X.X, please install the appropriate version from github.com/KlugerLab/FIt-SNE and have fast_tsne_path point to it if it's not in your path")
  }`

**Comment by saketkc** [comment]
Support for FIt-SNE 1.2+ was merged in the `develop` branch recently: https://github.com/satijalab/seurat/pull/3281/
It should be in the next release.
