### ISSUE TITLE
avg_logFC - natural log or log 2?

### ISSUE THREAD

**Issue by malosreet** [satijalab/seurat#332]
I could not find this information in the documentation, but maybe I missed it: for the FindMarkers and FindAllMarkers functions is the avg_logFC in base 2 or natural log?

**Comment by leonfodoulian** [comment]
Hi,

`avg_logFC` is returned in natural log. I guess that all log transformations in Seurat are performed using the natural log. Details on this can be found in the source code at [lines 171 to 173](https://github.com/satijalab/seurat/blob/master/R/differential_expression.R#L171-L173), and at [line 284 in differential_expression.R](https://github.com/satijalab/seurat/blob/master/R/differential_expression.R#L284). 

Best,
Leon
