### ISSUE TITLE
Read10X_h5 function is not usable in R 4.0.2

### ISSUE THREAD

**Issue by mariusjns** [satijalab/seurat#3320]
I have 10X data as h5 files.

If I do:
`sample <- Read10X_h5("file")`

Error: `Please install hdf5r to read HDF5 files`

But `BiocManager::install("rhdf5r")` gives
`Warning message:
package ‘rhdf5r’ is not available (for R version 4.0.2)`

Is there a work around this?

I have rhdf5 installed and `h5read()` can be used to create a list object that will look like this:
```
              group          name       otype  dclass      dim
0                 /        matrix   H5I_GROUP                 
1           /matrix      barcodes H5I_DATASET  STRING     6249
2           /matrix          data H5I_DATASET INTEGER 13620931
3           /matrix      features   H5I_GROUP                 
4  /matrix/features _all_tag_keys H5I_DATASET  STRING        1
5  /matrix/features  feature_type H5I_DATASET  STRING    33539
6  /matrix/features        genome H5I_DATASET  STRING    33539
7  /matrix/features            id H5I_DATASET  STRING    33539
8  /matrix/features          name H5I_DATASET  STRING    33539
9           /matrix       indices H5I_DATASET INTEGER 13620931
10          /matrix        indptr H5I_DATASET INTEGER     6250
11          /matrix         shape H5I_DATASET INTEGER        2
```
Can this somehow be loaded into a Seurat object?

**Comment by samuel-marsh** [comment]
Hi,

It appears you are missing the hdf5r package not rhdf5r package.  hdf5r is available on CRAN.  If you install from CRAN and then re-run `Read10X_h5` does that solve your issue?

Best,
Sam

**Comment by mariusjns** [comment]
You are right. I must have read that cross-eyed.

**Comment by millerkaplanlab** [comment]
I'm having the same issue with the Read10X function in R 4.1.0. I'm on a Mac and I have installed the hdf5r package using "brew install hdf5r" in the Terminal. However, when I run the command in R there is an error that I do not have the package installed. Can anyone help with this?

**Comment by samuel-marsh** [comment]
You need to install the R package called hdf5r.  Run `install.packages("hdf5r") from R session.

**Comment by millerkaplanlab** [comment]
I've done this as well and I get the following error: installation of package 'hdf5r' had non-zero exit status

install.packages("hdf5r") 
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: 'hdf5r'
Do you want to attempt to install these from sources? (Yes/no/cancel) yes
installing the source package 'hdf5r'

trying URL 'https://cran.rstudio.com/src/contrib/hdf5r_1.3.3.tar.gz'
Content type 'application/x-gzip' length 2217906 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

* installing *source* package ‘hdf5r’ ...
** package ‘hdf5r’ successfully unpacked and MD5 sums checked
** using staged installation
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking for grep that handles long lines and -e... /usr/bin/grep
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for h5cc... no
checking for h5pcc... no
checking for HDF5 libraries... no
configure: WARNING:
Unable to locate HDF5 compilation helper scripts 'h5cc' or 'h5pcc'.
Please specify --with-hdf5=<LOCATION> as the full path to h5cc or h5pcc.
HDF5 support is being disabled (equivalent to --with-hdf5=no).

configure: error: hdf5 does not seem to be installed on your platform.
  Please install the hdf5 library.
  The required HDF5 library files can be installed as follows:
      - Debian-based (e.g. Debian >= 8.0, Ubuntu >= 15.04): 'sudo apt-get install libhdf5-dev'
        - Old Debian-based (e.g Debian < 8.0, Ubuntu < 15.04): Install from source (see INSTALL)
        - OS X using Homebrew: 'brew install hdf5'
        - RPM-based (e.g Fedora): 'sudo yum install hdf5-devel'
ERROR: configuration failed for package ‘hdf5r’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/hdf5r’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/hdf5r’
Warning in install.packages :
  installation of package 'hdf5r' had non-zero exit status

The downloaded source packages are in
	'/private/var/folders/f9/29r1614112g1lb802853w2bh0000gn/T/RtmpeDnimY/downloaded_packages'

**Comment by samuel-marsh** [comment]
What is the output in terminal if you run:
`brew list`

**Comment by millerkaplanlab** [comment]
MacBook-Pro-5:~ Dina$ brew list
==> Formulae
gcc		hdf5		libmpc		openssl@1.1	szip
gettext		isl		libunistring	pcre		wget
gmp		libidn2		mpfr		swig		zstd

**Comment by samuel-marsh** [comment]
Have you tried removing the hdf5 formula and reinstalling it?  Seems like error of R not seeing the hdf5 installation on your system.

**Comment by samuel-marsh** [comment]
Also making sure to restart R after doing so.

**Comment by millerkaplanlab** [comment]
Yes, I have done this and still the same error....

**Comment by samuel-marsh** [comment]
Hmm sorry not sure I can be much more of help.  Given that the issue is actually hdf5r related I would suggest maybe posting an issue to that repo or checking out some of the other issues to see if there is solution posted to your issue.
https://github.com/hhoeflin/hdf5r/issues

Best,
Sam

**Comment by millerkaplanlab** [comment]
Thank you for trying to help! I'll check out those issues and hopefully find a solution...

**Comment by sabrinacamp2** [comment]
Hi @millerkaplanlab, 

I was just having this issue with the same error, and came across a solution posted on this [thread](https://github.com/hhoeflin/hdf5r/issues/94). it worked for me!

![image](https://user-images.githubusercontent.com/52207849/128406578-14d8818d-b2b9-4bfa-a90b-0f3d38162b0e.png)

Best,
Sabrina

**Comment by millerkaplanlab** [comment]
Hello @sabrinacamp2,

Thank you for trying to help with this. I just tried this and am still getting the non-zero exit status error. Not sure why this is so difficult to install. I didn't have this issue with my previous version of R.

**Comment by mreza-ef** [comment]
> You need to install the R package called hdf5r. Run `install.packages("hdf5r")` from R session.

worked for me! thanks
