### ISSUE TITLE
Error in VlnPlot: unused argument

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3321]
Hello, 

I want to use VlnPlot on a integrated SeuratObject: hc_mild_severe_integrated.

Thank  you in advance for great help!

Best,

Yue

     > VlnPlot(hc_mild_severe_integrated, features.plot = c("CXCL2", "IL1A"), group.by = "tech")
    Error in VlnPlot(hc_mild_severe_integrated, features.plot = c("CXCL2",  : 
    unused argument (features.plot = c("CXCL2", "IL1A"))

**Comment by samuel-marsh** [comment]
Hi,

The error is `features.plot` which is no longer the correct call in Seurat V3.  Using `features` instead should resolve this issue.

Best,
Sam

**Comment by yueli711** [comment]
Hello, samuel-marsh,

Thank you so much for your great help!

Use `features` instead of 'features.plot'.

Thank you again!

Best,

Yue
