### ISSUE TITLE
Replicate VlnPlot() with geom_violin()

### ISSUE THREAD

**Issue by phoebee-h** [satijalab/seurat#3322]
Hi, 
Thanks for developing Seurat, which is very user-friendly and convenient. My question had been asked several times before (maybe?), but I could not replicate the violin plot even if I follow the description: setting` scale = "width"` in **geom_violin()**. (https://github.com/satijalab/seurat/issues/297, https://github.com/satijalab/seurat/issues/335)
> Seurat's VlnPlot() function uses width as input to the scale argument of geom_violin() 

![image](https://user-images.githubusercontent.com/28743573/88638922-b672eb80-d0ee-11ea-8825-7ca39e3153ef.png)

See cluster0 (and so does cluster3, cluster5), why the density part shows in left with **geom_violin()** but not show with **VlnPlot()**? What else can I modify to get the same result?

**Left**
`vln_df = data.frame(FOXP3 = obj[["RNA"]]@data["FOXP3",], cluster = obj$seurat_clusters)`
`ggplot(vln_df, aes(x = cluster, y = FOXP3)) + geom_violin(aes(fill = cluster), trim=TRUE, scale = "width") + geom_jitter()`
**Right**
`VlnPlot(obj, features = "FOXP3")`

**Comment by yuhanH** [comment]
Actually, we add a small noise into data before VlnPlot.

https://github.com/satijalab/seurat/blob/72a0c7b61adcf1d6630db9e952bf8b0d4f979295/R/visualization.R#L6733-L6738


```
# seurat violin plot 
VlnPlot(pbmc_small, features = "PPBP", group.by = "groups")

#  violin plot without noise
vln_df = data.frame(PPBP =pbmc_small[["RNA"]]@data[ "PPBP", ], cluster = pbmc_small$groups)
ggplot(vln_df, aes(x = cluster, y = PPBP, fill = cluster)) + geom_violin( adjust =1,trim=TRUE, scale = "width")    + geom_jitter()

vln_df.2 <- vln_df
noise <- rnorm(n = length(x = vln_df.2[, "PPBP"])) / 100000
vln_df.2$PPBP <- vln_df.2$PPBP  + noise

# violin plot with noise
ggplot(vln_df.2, aes(x = cluster, y = PPBP, fill = cluster)) + geom_violin( adjust =1,trim=TRUE, scale = "width")    + geom_jitter()
```

**Comment by PWbio** [comment]
May I ask what is the purpose to add noise?
Here is the results that I follow your code. It does not seem to affect the density distribution of violin plot.
![plot_zoom_png-28](https://user-images.githubusercontent.com/64364411/105575494-0f25f700-5da7-11eb-962c-ec335da64263.png)

**Comment by ksaunders73** [comment]
Hello @yuhanH !

Why is the noise added? My statistics knowledge is a bit lacking, so I could be misunderstanding, but I think the noise makes "random deviates", which simulates randomness (that is normally distributed). I am not sure why the randomness should be represented in these plots though.

**Comment by yuhanH** [comment]
Hi, @ksaunders73 
Adding some noise just aims to make the Violin plot look better in particular when most cells have the same value.

**Comment by ksaunders73** [comment]
I see, thank you very much @yuhanH !
