### ISSUE TITLE
mixscape: Error in CellsByIdentities(object = object, cells = cells) 

### ISSUE THREAD

**Issue by brangiov** [satijalab/seurat#3323]
hello,

i am trying to use mixscape following the vignette, but i keep on getting the same error: 

```
x <- CalcPerturbSig(object = x, assay = "RNA", slot = "data", gd.class = "target_gene", nt.cell.class = "DUMMY", 
+                          reduction = "pca", ndims = 40, num.neighbors = 20, split.by = "orig.ident", new.assay.name = "PRTB")
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=31s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 36s
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided
```

I did this before `Idents(object = x) <- "target_gene"
` and `CellsByIdentities(x)` works fine. 

thanks in advance for helping!

**Comment by papal22e** [comment]
Hi
It's hard to tell what is going on here. Could you please provide an object so I can reproduce the error? You can downsample the object if it's too big.

**Comment by shahrozeabbas** [comment]
@brangiov If this hasn't been solved, I had issues with this....your `nt.cell.class` parameter needs to be set to an identity present in your 'target_gene' column.
