### ISSUE TITLE
HTO demux with TCR data alone

### ISSUE THREAD

**Issue by clairebio27** [satijalab/seurat#3324]
Our objective is  to test TCR Ab Oligos to define starting cell type, and also to Test the ability to pool samples with TCR Ab Oligos. 

We are using 10X for single cell  analysis and illumina for sequencing. We have used 8 different HTOs and have 9 samples . 
I have read one your nature Reports paper that also done similar analysis (though we don't have gene expression this time)

How can I do the HTOdemux and clonotype analysis using HTO/ADT and TCR fastqs alone.
Any help will be greatly appreciated

**Comment by yuhanH** [comment]
Seurat doesn't support TCR analysis now. 
Maybe you can try scRepertoire which can interact with Seurat object.  
https://github.com/ncborcherding/scRepertoire
