### ISSUE TITLE
plot kmeans cluster

### ISSUE THREAD

**Issue by ivonyao** [satijalab/seurat#333]
Can Seurat plot Kmeans cluster like tsne plot which similar of 10x Loupe software does of cellranger output?

**Comment by satijalab** [comment]
Though we don't use them often, we do have a DoKMeans and KMeansHeatmap function that can do this. Type ?KMeansHeatmap to see documentation and a short example in the package

**Comment by ivonyao** [comment]
Hi
Thanks for the help, I figured out. I actually want to see if I can display on tsne plot or aritifically determine how many clusters I want to do. It seems I figured out after a few try.
Best

Changfu Yao

Postdoctoral Scientist
Dr. Barry R. Stripp Lab
Department of Medicine
Cedars-Sinai Medical Center
AHSP 8600
127 S. San Vicente Blvd.
Los Angeles, CA 90048
Phone:  424-315-4333

**Comment by ivonyao** [comment]
I was trying to display the artificial clustering by kmeans on tsne plot, it does seem that after DoKMeans function then RunTSNE, it does the trick I want, and I am also able to find markers for this KMeans by using FindAllMarkers function. 
e.g.
tmp=KClustDimension(tmp, dims.use = c(1, 2), reduction.use = "tsne",
                k.use = 6, set.ident = TRUE, seed.use = 1)

tmp <- DoKMeans(tmp, k.genes = 6, do.plot=TRUE)

tmp <- RunTSNE(object = tmp,
               dims.use = 1:8,
               do.fast = TRUE)
TSNEPlot(tmp)
tmp.markers6 <- FindAllMarkers(object = tmp, only.pos = TRUE, min.pct = 0.25, 
                               thresh.use = 0.25)

**Comment by Ivalyne** [comment]
Hi.

Your method is highly helpful and I also got able to plot K-means clusters.

Here, I've one question.
Would you tell me the reason why did you run both of "KClustDimension" and "DoKMeans"?

Definitely yes, It works well. But it looks both of them are similar functions.

Best

**Comment by SaraAli83** [comment]
Hi, 

I'm new to Seurat and would be grateful for some advice regarding K means clustering as the default clustering method in Seurat fails to reveal a rare cell population which I can see very clearly in the loupe browser using the K means clustering method. I have the latest version of Seurat which doesn't seem to have the DoKMeans function mentioned in this thread. 
I tried to apply the following which is the method given in the package but it doesn't seem to work: 
 kmeans(x, centers, iter.max = 10, nstart = 1,
       algorithm = c("Hartigan-Wong", "Lloyd", "Forgy",
                     "MacQueen"), trace=FALSE)

Many thanks.

Sara
