### ISSUE TITLE
RenameCells #3183 #3303

### ISSUE THREAD

**Issue by jstraubhr** [satijalab/seurat#3333]
I am using Seurat Version 3.2.0.9004 which should contain the fix for this problem.

Yet, I get the same error.

In addition, when going through the integration workflow, using this same version, an error is thrown:

Finding all pairwise anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 14161 anchors

Error in if (positive[num] == negative[num]) { : 
  argument is of length zero

**Comment by timoast** [comment]
Please provide a reproducible example

**Comment by jstraubhr** [comment]
I don't think you want a 6.6Gb object to reproduce the error. I am downsampling and will check the error.

**Comment by andrewwbutler** [comment]
Hi,

Please try installing the latest `develop` branch (3.2.0.9005) or revert to the CRAN release (3.2.0). There was a small bug introduced in 9004 which would cause the error you're seeing.
