### ISSUE TITLE
Violinplot for genes not aligned 

### ISSUE THREAD

**Issue by xihuiyin** [satijalab/seurat#3334]
I'm trying to do a violinplot of two different genes for an integrated dataset. One of the genes has its expression data pulled RNA assay instead of the default search locations (`Warning: Could not find Tnfrsf1b in the default search locations, found in RNA assay instead`). However, doing a violinplot of the gene that was found in the default search location (Tnfrsf1a) has its zero value begin much higher up the y-axis than the one found in the RNA assay (Tnfrsf1b). 

![image](https://user-images.githubusercontent.com/36392508/88913136-3a26f800-d215-11ea-9b39-1a007fb62fc9.png)

Is there any way I can cut off the negative values for the left gene (Tnfrsf1a) and make its zero value start at the same location as the other gene (Tnfrsf1b)?

**Comment by Dragonmasterx87** [comment]
Generally, it is advised to plot normalized RNA data (as suggested by @timoast  in #1514), not integrated. Doing that for your Tnfrsf1a will solve the issue. Now you can change the default assay, or as of Seurat v3 and above, just direct VlnPlot to extract data from the RNA assay's data slot.

```
# Violin plots for gene expression. change gene value to look at diffrent genes
VlnPlot(object = yourseuratobjects, 
        features = c("Tnfrsf1a", "Tnfrsf1b"), 
        ncol = 2,
        slot = 'data',
        assay = 'RNA',
        cols = c("lightseagreen", # change colors to match your liking
                 "darkgreen",
                 "royalblue",
                 "red4",
                 "red",
                 "orange2",
                 "darkmagenta",
                 "seagreen",
                 "pink",
                 "purple"
                 ), y.max = 3, y.min = 0, pt.size = 1) # adjust y.min for plotting minimal y value
```

**Comment by yuhanH** [comment]
@Dragonmasterx87 , Thanks for your reply.  RNA assay is suggested to be used for gene expression visualization instead of integrated assay.
