### ISSUE TITLE
SpatialFeaturePlot

### ISSUE THREAD

**Issue by venchi9** [satijalab/seurat#3335]
I am trying to use this to analyse some spatial data but when I try to use it, I get this error:

Error in SpatialFeaturePlot(spatial, features = "EPCAM") :
could not find function "SpatialFeaturePlot"

I get a similar error for "SpatialPlot" and "SpatialDimPlot".

I have tried reinstalled Seurat.

When I type: ?SpatialFeaturePlot - it recognises the functions

I have previously used this function without any issues. I'm not sure what I'm doing wrong.

**Comment by andrewwbutler** [comment]
Hi,

Please try starting a fresh R session. To have the latest spatial functionality from a CRAN install, you should see `3.2.0` when you run `packageVersion("Seurat")`.

**Comment by venchi9** [comment]
Thanks.  I updated everything again and it started working.
