### ISSUE TITLE
dot plot difference between using assay="RNA" and not using this parameter.

### ISSUE THREAD

**Issue by sunliang3361** [satijalab/seurat#3338]
Hi, I just saw the dot plots for candidate genes which I would like to plot are really different, especially the percent expressed for each gene. In general, the gray dots in dot plot (without parameter assay="RNA") is bigger than the one in dot plot with this parameters. Could you let me know how you calculate "percent expressed"? FYI, The cell numbers of two condition for specific cell types are different. Thanks you.

**Comment by cdarby** [comment]
Per the documentation of DotPlot, when you omit the "assay" argument the active assay is used. Therefore in your object, different data is being plotted when you specify assay="RNA" vs. omit it. Percent expressed, or the size of the dot, is simply the percent of cells of a certain class that have > 0 value for a feature.

**Comment by sunliang3361** [comment]
Right, but based on the definition of PCT1 and PCT2, it's the cell percentage which have the candidate genes expressed (expression >0). So this percentage should be the same no matter we use assay="RNA" or "integrated", since the number of cells has the candidate gene expressed should not be changed. Right? look forward to more answers. thank you.

**Comment by cdarby** [comment]
Not necessarily. Integration corrects expression values and can change a 0 to a value > 0.

**Comment by sunliang3361** [comment]
This answered my confusion. Thank you.
