### ISSUE TITLE
Use SC transform for integrated data sets

### ISSUE THREAD

**Issue by cloitz2** [satijalab/seurat#3339]
Hello,

I am very impressed with the new SC transform code! I have used it for previously analyzed datasets and was pleasantly surprised by the new information I was able to obtain. With that said, I would like to use this new data modeling approach on datasets I have integrated. I have tried a few different ways (I tried doing SC transform before integration as well as after), but each time I get an error code. If you could please help me and supply the steps or code necessary I would really appreciate it!

**Comment by cdarby** [comment]
Please check the SCTransform tab in the integration vignette that shows the workflow for integration with SCTransform. https://satijalab.org/seurat/v3.2/integration.html

If you still have errors, please reopen this issue and include the sequence of commands you used and all error messages you receive.
