### ISSUE TITLE
Best way to visualize ClassifyCells output?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#334]
Hello Seurat Team,

I am wondering what's the best way to visualize the output of the ClassifyCells function.   I have 10X data from two conditions.  Say I have clustered the "cond1" cells into X clusters, and I wish to see where the "cond2" cells fall within the "cond1" clustering framework.  ClassifyCells seems to be the function suitable to try for this purpose.  As I understand it, the function will output a vector of "cond1" class IDs for the "cond2"cells as per my example.  I can imagine one way to visualize would then be to separately cluster the "cond2" cells, and then, color that tSNE plot using the ClassifyCells output classes.  That way, I will know which clusters of "cond2" are close to which clusters of "cond1".  Is there any other good way to visualize?

Secondly, would every new cell forcefully get assigned a class of "cond1"?  Is there a way to group those cells that don't fit well into any of the predefined clusters into a separate "unclassified" group?  Also, is it possible to set a threshold of some sort to control what goes into the "unclassified" bin?

I couldn't find an example for using this function in the Seurat tutorial, so any help would be appreciated!

Thanks a lot for any replies!

**Comment by satijalab** [comment]
Your first suggestion for visualization makes sense to me, and I apologize that we don't support thresholding on ClassifyCells at the moment.

**Comment by CodeInTheSkies** [comment]
Thank you for the reply!  Even without thresholding, is it possible to
"separately bin" those cells that don't fit well into any of the predefined
groups?
That would be great for my purposes.  Thanks again for any replies.
