### ISSUE TITLE
single cell integration clustered by dataset instead of celltype (apparently)

### ISSUE THREAD

**Issue by Diozao666** [satijalab/seurat#3340]
Hello

I have tried to integrate two scRNAseq datasets of immune cells of covid patients, one from broncheoalveolar fluid and one from blood. I have downloaded the rds files provided by the authors or in the cellxgene database. The authors have removed samples with high mitochondrial genes (pipelines were different, however) and I skipped this step. 

I tried to adapt this [vignette ](https://satijalab.org/seurat/v3.0/integration.html) like this

```
#integratedata
circulating <- SCTransform(circulating, verbose = FALSE, assay = "RNA")
BALF <- SCTransform(BALF, verbose = FALSE, assay = "RNA")
circBALF <- c(circulating, BALF)
circBALF.features <- SelectIntegrationFeatures(object.list = circBALF, nfeatures = 3000)
circBALF.list <- PrepSCTIntegration(object.list = circBALF, anchor.features = circBALF.features)
circBALF.anchors <- FindIntegrationAnchors(object.list = circBALF.list, normalization.method = "SCT", anchor.features = circBALF.features)
circBALF.integrated <- IntegrateData(anchorset = circBALF.anchors, normalization.method = "SCT")
circBALF.integrated
circBALF.integrated <- RunPCA(circBALF.integrated, verbose = FALSE)
circBALF.integrated <- RunUMAP(circBALF.integrated, dims = 1:50)
DimPlot(circBALF.integrated, reduction = "umap")
```
the umap reduction plot, however, shows no overlap (visually) between the datasets. Sure the origins of the samples are quite different, but I expected to see some overlap in the plot, as many of the cells found in each are supposed to be of the same types.
Are these reductions simply what they are or did I commit a mistake in the integration?

Best,
Diogo

**Comment by satijalab** [comment]
The code looks correct to us, this suggests that while there may be some biological similarity between cell types across samples, it was not strong enough for the method to facilitate integration.

I'm not sure there is much we can recommend at this stage, but you could take a look at the number of anchors discovered. If that is very low, again that suggests minimal ability to discover shared cell types.

**Comment by matasV99** [comment]
Dear Satijalab,

Could you elaborate which parameter of AnchorSet object we have to look at to check the number of anchors discovered?

Thanks,
Matas
