### ISSUE TITLE
Best practice to subset cells from combined object processed with SCTransform

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#3343]
Hi,

Thank you for developing and maintaining Seurat! I have a quick question regarding how to best subset cells from a combined object that was previously processed with SCTransform. This is what I did:

I combined 4 data sets with SCTransform
I identified the cluster I was interested in

To subset I followed this command that I found online:

DefaultAssay(OBJECT) <- "RNA"
OBJECT_SUB <- SubsetData(OBJECT, ident.use = c(7)) 
OBJECT_SUB <- FindVariableFeatures(OBJECT_SUB, selection.method = "vst", nfeatures = 3000)
DefaultAssay(OBJECT_SUB) <- "integrated"
OBJECT_SUB <- ScaleData(OBJECT_SUB, verbose = T)
OBJECT_SUB <- RunPCA(OBJECT_SUB, npcs = 100, verbose = FALSE)

OBJECT_SUB <- FindNeighbors(OBJECT_SUB, dims = c(1:25))
OBJECT_SUB <- RunTSNE(OBJECT_SUB, dims = c(1:25))
OBJECT_SUB <- FindClusters(OBJECT_SUB, resolution = 0.7)
DimPlot(object = OBJECT_SUB, reduction = "tsne", label = T, pt.size = 2, label.size=6)

To me it seemed OK, but then I realized that I was running FindVariableFeatures and ScaleData differently that SCTransform does it.

My question is, it this approach OK - and recommended by you?

Thank you!

**Comment by yuhanH** [comment]
If you still want to use `integrated` assay, you can RunPCA after you subset the object. 
```
DefaultAssay(OBJECT) <- "integrated"
OBJECT_SUB <- subset(OBJECT, idents = c(7))
OBJECT_SUB <- RunPCA(OBJECT_SUB, verbose = FALSE)

OBJECT_SUB <- FindNeighbors(OBJECT_SUB, dims = c(1:25))
OBJECT_SUB <- RunTSNE(OBJECT_SUB, dims = c(1:25))
OBJECT_SUB <- FindClusters(OBJECT_SUB, resolution = 0.7)

```
