### ISSUE TITLE
How get normalized data matrix file

### ISSUE THREAD

**Issue by srishastry123** [satijalab/seurat#3344]
Hello
Thanks for the tool

 I am using seurat for my single cell analysis , after the normalization method as below

mca <- NormalizeData(mca, normalization.method = "LogNormalize", scale.factor = 10000)
mca <- FindVariableFeatures(mca, selection.method = "vst", nfeatures =3000)

I have 1000 cells in my data,  wanted the output data matrix of  3000 * 1000 how can get this matrix can you please suggest me 
and what is the log SCALE used in this normalization method is it log10 or log2

**Comment by timoast** [comment]
```r
GetAssayData(object, slot = "data")
```

As stated in the documentation for `NormalizeData`, we use the natural log
