### ISSUE TITLE
Does Seurat use the natural log to calculate avg_logFC in FindAllMarkers?

### ISSUE THREAD

**Issue by ktrns** [satijalab/seurat#3346]
Hi! 

Thanks again for developing Seurat! 

I would like to ask you a question with regard to the `avg_logFC` output of `FindAllMarkers`. Is this average log FC calculated with base e, or base 2? 

I found the following code in `differential_expression.R`, and would like to ask if this is the correct place? It would mean that Seurat uses the natural log with base e:
```
 # feature selection (based on average difference)
  mean.fxn <- if (is.null(x = reduction) && slot != "scale.data") {
    switch(
      EXPR = slot,
      'data' = function(x) {
        return(log(x = rowMeans(x = expm1(x = x)) + pseudocount.use))
      },
      function(x) {
        return(log(x = rowMeans(x = x) + pseudocount.use))
      }
    )
  } else {
    rowMeans
  }
  data.1 <- mean.fxn(data[features, cells.1, drop = FALSE])
  data.2 <- mean.fxn(data[features, cells.2, drop = FALSE])

  total.diff <- (data.1 - data.2)
```

If this is correct, we will use `avg_logFC` to calculate an average log FC to the basis 2, since this seems more common and easier to understand. Maybe this is something for Seurat to change in the future? 

Best wishes and thanks again! 
Katrin

**Comment by cdarby** [comment]
Yes, you're correct, natural log is used.

Thank you for the suggestion to allow user customization of the function for calculating logFC in FindMarkers. While it's currently not available we'll discuss it.

**Comment by DiracZhu1998** [comment]
Hello, thanks for your reply!
I am wondering why using natural log in FindAllMarkers and using log2 in FindMarkers?
Best wishes.
Dirac
