### ISSUE TITLE
how can you regress out variation due to replicates in scRNA-seq? 

### ISSUE THREAD

**Issue by Marlo442** [satijalab/seurat#3347]
Hi! 
Hopefully, anyone can help me figure out how to handle replicates in scRNA seq data.

I have two conditions and for both conditions one replicate. The replicates were merged per condition, normalized and scaled. Finally, I integrated the two conditions to use for visualization and DE.  

I am now wondering how I can regress out the variation due to replicates (in the scale function)? something with vars.to.regress? linear regression?

**Comment by timoast** [comment]
It's a bit unclear at which analysis step you want to account for differences between batches. One option is performing integration between batches as shown in the integration vignettes. Another option for DE is including batch as a latent variable in the DE model (see the documentation for FindMarkers)
