### ISSUE TITLE
SCTransform duplicates data

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3348]
Running SCTransform adds a new assay with an `@counts` slot that essentially duplicates the information contained in the assay `SCTransform` was run from. Here's an example:

```
s_obj <- CreateSeuratObject(pbmc)
object.size(s_obj) %>% format(units="KB")
# 2214 Kb

s_obj <- SCTransform(s_obj)
object.size(s_obj) %>% format(units="KB")
# 6876 Kb

# replace counts with empty matrix
s_obj[["SCT"]]@counts <- matrix(rep(0,prod(dim(s_obj[["SCT"]]))),nrow=nrow(s_obj[["SCT"]])) %>% 
  as.sparse()
object.size(s_obj) %>% format(units="KB")
# 5869 Kb
```

I think it would be better to either not copy the coutns over to the new SCT-assay or even just add an `@SCT` slot to the assay SCTransform was run from to not duplicate data. In my real application, storing the count matrix a second time makes the Seurat-object 25% bigger than it should be.

**Comment by timoast** [comment]
1. The data is not duplicated, the data placed in the counts slot are essentially the corrected UMI counts obtained from the SCTransform models
2. The `do.correct.umi` parameter already controls whether the corrected UMI counts are computed and stored in the counts slot of the SCT assay, so you can control whether you want to store this information
3. Adding a specific slot to the assay class for SCT data would require that we modify all Seurat functions to control whether you want to use data stored in the `data` or `SCT` slot.

**Comment by frederikziebell** [comment]
Thanks for the clarification!
