### ISSUE TITLE
No cell names (colnames) names present in the input matrix

### ISSUE THREAD

**Issue by oliviajc** [satijalab/seurat#3350]
Hello, 

I ran read10X to load the data set containing genes.tsv, barcodes.tsv, and matrix.mtx. I received an error 
"Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features) : 
  No cell names (colnames) names present in the input matrix" when I try to run createseuratobject.

There is a previously closed post regarding this error and it was suggested that it is because the matrix has no rownames. However, when I compared the matrix.mtx I have to that I used for the tutorial, the layout is the same. Where do I add rownames to the matrix or how should this error be solved?

Thank you

**Comment by timoast** [comment]
You can assign rownames to a matrix in R using the `rownames<-` assignment operator, and similarly for colnames. See the R documentation (`?rownames`)
