### ISSUE TITLE
how to extract raw counts of a particular gene or cell?

### ISSUE THREAD

**Issue by tanpuekai** [satijalab/seurat#3353]
hi,
             i have a sample called "mySample", with N genes, M cells, and n valid values (n << (N*M)).
             i want to retrieve a vector of M values from a gene called "myGene", how can that be done?
             what extracting a vector of N values from a cell called "myCell"?

Thanks
Chan

**Comment by samuel-marsh** [comment]
Hi Chan,

You can use the `FetchData` function to get the info you are after.  I suggest checking out the manual entry for `FetchData` and the [Wiki page](https://github.com/satijalab/seurat/wiki) to understand that slot/data structure of Seurat objects.

Best,
Sam

**Comment by tanpuekai** [comment]
> Hi Chan,
> 
> You can use the `FetchData` function to get the info you are after. I suggest checking out the manual entry for `FetchData` and the [Wiki page](https://github.com/satijalab/seurat/wiki) to understand that slot/data structure of Seurat objects.
> 
> Best,
> Sam

Thanks Sam.
That is the neat solution I am looking for.

-Chan

**Comment by tanpuekai** [comment]
> Hi Chan,
> 
> You can use the `FetchData` function to get the info you are after. I suggest checking out the manual entry for `FetchData` and the [Wiki page](https://github.com/satijalab/seurat/wiki) to understand that slot/data structure of Seurat objects.
> 
> Best,
> Sam

Thanks Sam.
That is the neat solution I am looking for.

However, I found it only returns the normalised expression, but not the RAW data?

`gene1<- FetchData(mySample, vars = "myGene")
`

-Chan

**Comment by tanpuekai** [comment]
> > Hi Chan,
> > You can use the `FetchData` function to get the info you are after. I suggest checking out the manual entry for `FetchData` and the [Wiki page](https://github.com/satijalab/seurat/wiki) to understand that slot/data structure of Seurat objects.
> > Best,
> > Sam
> 
> Thanks Sam.
> That is the neat solution I am looking for.
> 
> However, I found it only returns the normalised expression, but not the RAW data?
> 
> `gene1<- FetchData(mySample, vars = "myGene") `
> 
> -Chan

Fixed now:

```
GENES<-rownames(mySample)
CELLs<-colnames(mySample)
names(mySample)
dim(x = mySample)
indMyGene<-which(GENES=="myGene")
indMyCell<-which(GENES=="myCell")

CountMyGeneMyCell<-GetAssayData(object = mySample, slot = 'counts')[indMyGene, indMyCell]

```


-Chan

**Comment by samuel-marsh** [comment]
Hi Chan,

Yes that works too.  To get the raw data using FetchData you just need to specify the correct slot like you did in the `GetAssayData` function.

Best,
Sam
