### ISSUE TITLE
%iff% operator in the DimPlot issue

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3355]
Hi  All,
     I want to customize the dimplot file with my project occurred error about operator %iff% in DimPlot. and then how can i fix this
  troublesome on this condition?
     any advice should be thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but maybe I can help.  What is the exact error you are receiving?  Are you trying to write edit `DimPlot` function as new custom function?

Best,
Sam

**Comment by honghh2018** [comment]
Hi @samuel-marsh, 
    thanks for reply.
    Yes, it is, i want to customize the dimplot function with what i need on my project. so the error occurred with %iff% operator not found when rewrite the dimplot function.
    Good work,
    hanhuihong

**Comment by samuel-marsh** [comment]
Hi,  

You need to create the `%iff%` function in order for that to work.  The `%iff%` function can be found in the utilities.R script but also posting here:
```
`%iff%` <- function(lhs, rhs) {
  if (!is.null(x = lhs)) {
    return(rhs)
  } else {
    return(lhs)
  }
}
```

Best,
Sam
