### ISSUE TITLE
dot plot cannot find the genes

### ISSUE THREAD

**Issue by sunliang3361** [satijalab/seurat#3357]
When I tried to DotPlot the gene of my interest by using RNA data, I found that my object cannot find my gene, see my error message below:
The following requested variables were not found: Kng1
Is this because this gene is not included in my object?  How to know how many genes from reference genome were included in Seurat object? Thank you so much

**Comment by samuel-marsh** [comment]
Hi,

To get list of all genes present in Seurat object you can simply run:
`gene_list <- rownames(object)`

Best,
Sam

**Comment by pavitsun** [comment]
What do you do if you find the gene on the gene list, but the dot-plot and/or DoHeatmap function says "No requested features found in the scale.data slot for the RNA assay"

**Comment by samuel-marsh** [comment]
Hi @pavitsun can you post the full code you are running?
