### ISSUE TITLE
sctransform for normalizing scATAC-seq gene activity matrix? 

### ISSUE THREAD

**Issue by RegnerM2015** [satijalab/seurat#3359]
Hi,

In reference to the following vigentte: https://satijalab.org/seurat/v3.2/atacseq_integration_vignette.html

I was wondering if it was valid to model the scATAC-seq gene activity matrix using sctransform? 

Instead of the traditional code: 
`DefaultAssay(pbmc.atac) <- "ACTIVITY"`
`pbmc.atac <- FindVariableFeatures(pbmc.atac)`
`pbmc.atac <- NormalizeData(pbmc.atac)`
`pbmc.atac <- ScaleData(pbmc.atac)`

One could use sctransform before transfering labels from scRNA-seq:
`pbmc.atac <- SCTransform(pbmc.atac, verbose = FALSE)`

Thanks in advance!

**Comment by timoast** [comment]
I don't think this would be a good idea. SCTransform models the count data using regularized negative binomial regression, with different models for genes expressed at different levels. This is not really the case when looking at the scATAC-seq gene activities, they are much more binary (accessible or not) and the concept of more "highly expressed" doesn't make much sense.

**Comment by RegnerM2015** [comment]
I agree. This method does not seem appropriate for scATAC-seq count data.
