### ISSUE TITLE
Finding Cell barcodes for specific clusters

### ISSUE THREAD

**Issue by Edenapple** [satijalab/seurat#336]
How do I find a list of cell barcodes for all cells in certain clusters from tSNE clustering in Seurat?

In my single cell sequencing analysis, some tSNE clusters has been identified as potential contaminants from the library preparation process, and I want to trim these cells from the fastq files and redo the single cell sequencing analysis.

**Comment by satijalab** [comment]
You can use WhichCells as detailed in http://satijalab.org/seurat/interaction_vignette.html

**Comment by balqees-mansour** [comment]
I have seurat object with cell names like this "884635" I did not find the cell barcodes,what is the solution ????
