### ISSUE TITLE
specifying upstream and downstream limits in Integration Analysis

### ISSUE THREAD

**Issue by sylestiel** [satijalab/seurat#3362]
Hi,

Please advice on how to specify the upstream coordinates where one wishes to include a very specic range as it would appear that this script does not utilize the conventional minus sign for Upstream of TSS versus plus sign for downstream of TSS.
So in the script if upstream= 2000 and downstream =0, I'm assuming it is searching for accessibility in the region spanning 2000 to 0.
However, I'm interested in the 100-2kb upstream WITHOUT the 2kb-0 upstream region. How then would i ensure that 2kb-0 region is being excluded if I set upstream to 100000-2000 and downstream =0.

Thank you!!!!

**Comment by timoast** [comment]
Please raise this issue in the Signac repository: https://github.com/timoast/signac
