### ISSUE TITLE
Expression values of individual samples in integrated object

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#3363]
I have performed single-cell experiments containing 3 WT and 3 KO samples and I used Seurat integration [vignette](https://satijalab.org/seurat/v3.1/immune_alignment.html) for comparing WT and KO conditions. I use `AverageExpression` function to get the expression values of genes in KO and WT samples. 
Now I want to determine the individual expression values of genes in each samples of KO and WT (from integrated Seurat object). I am wondering how can  I get individual expression values

Something like this:

-----------WT1--------- WT2---------WT3-------KO1----------KO2----------KO3
GAPDH----10------------15 ----------13--------- 5-------------17------------9
ACTB------10------------15 ----------13--------- 5-------------17------------9

Thank you

**Comment by jaisonj708** [comment]
You can set the Identities of your integrated object to the sample (WT1, WT2, etc). Then `AverageExpression` will automatically output a table of averages per sample as you'd like.
