### ISSUE TITLE
 *** caught segfault *** address (nil), cause 'memory not mapped': ATACseq integration vignette [cca reduction]

### ISSUE THREAD

**Issue by elhaam** [satijalab/seurat#3364]
Hi there, thanks for the helpful package!
I am using [ATACseq integration vignette](https://satijalab.org/seurat/v3.2/atacseq_integration_vignette.html) and I am facing the same problems as [3274](https://github.com/satijalab/seurat/issues/3274) and [2386](https://github.com/satijalab/seurat/issues/2386), as follows:

```
transfer.anchors <- FindTransferAnchors(reference = pbmc_rna, query = pbmc_atac, features = VariableFeatures(object = pbmc_rna), reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")
```
> Running CCA
>  *** caught segfault ***
> address (nil), cause 'memory not mapped'
> 
> Traceback:
>  1: Standardize(mat = object1, display_progress = FALSE)
>  2: RunCCA.default(object1 = data1, object2 = data2, standardize = TRUE,     num.cc = num.cc, verbose = verbose, )
>  3: RunCCA(object1 = data1, object2 = data2, standardize = TRUE,     num.cc = num.cc, verbose = verbose, )
>  4: RunCCA.Seurat(object1 = reference, object2 = query, features = features,     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,     verbose = verbose)
>  5: RunCCA(object1 = reference, object2 = query, features = features,     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,     verbose = verbose)
>  6: FindTransferAnchors(reference = pbmc_rna, query = pbmc_atac,     features = VariableFeatures(object = pbmc_rna), reference.assay = "RNA",     query.assay = "ACTIVITY", reduction = "cca")
> 
> Possible actions:
> 1: abort (with core dump, if enabled)
> 2: normal R exit
> 3: exit R without saving workspace
> 4: exit R saving workspace

My session info on the server:
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.4 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> other attached packages:
> [1] ggplot2_3.3.2 Seurat_3.2.0
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.2            tidyr_1.1.1           jsonlite_1.7.0
>  [4] viridisLite_0.3.0     splines_3.6.3         leiden_0.3.3
>  [7] shiny_1.5.0           ggrepel_0.8.2         globals_0.12.5
> [10] pillar_1.4.6          lattice_0.20-41       glue_1.4.1
> [13] reticulate_1.16       digest_0.6.25         polyclip_1.10-0
> [16] RColorBrewer_1.1-2    promises_1.1.1        colorspace_1.4-1
> [19] cowplot_1.0.0         htmltools_0.5.0       httpuv_1.5.4
> [22] Matrix_1.2-18         plyr_1.8.6            pkgconfig_2.0.3
> [25] listenv_0.8.0         purrr_0.3.4           xtable_1.8-4
> [28] patchwork_1.0.1       scales_1.1.1          RANN_2.6.1
> [31] tensor_1.5            later_1.1.0.1         Rtsne_0.15
> [34] spatstat.utils_1.17-0 tibble_3.0.3          mgcv_1.8-31
> [37] generics_0.0.2        ellipsis_0.3.1        withr_2.2.0
> [40] ROCR_1.0-11           pbapply_1.4-2         lazyeval_0.2.2
> [43] deldir_0.1-28         survival_3.1-12       magrittr_1.5
> [46] crayon_1.3.4          mime_0.9              future_1.18.0
> [49] nlme_3.1-147          MASS_7.3-51.6         ica_1.0-2
> [52] tools_3.6.3           fitdistrplus_1.1-1    data.table_1.13.0
> [55] lifecycle_0.2.0       stringr_1.4.0         plotly_4.9.2.1
> [58] munsell_0.5.0         cluster_2.1.0         irlba_2.3.3
> [61] compiler_3.6.3        rsvd_1.0.3            rlang_0.4.7
> [64] grid_3.6.3            ggridges_0.5.2        goftest_1.2-2
> [67] RcppAnnoy_0.0.16      rappdirs_0.3.1        htmlwidgets_1.5.1
> [70] igraph_1.2.5          miniUI_0.1.1.1        gtable_0.3.0
> [73] codetools_0.2-16      abind_1.4-5           reshape2_1.4.4
> [76] R6_2.4.1              gridExtra_2.3         zoo_1.8-8
> [79] dplyr_1.0.1           uwot_0.1.8            fastmap_1.0.1
> [82] future.apply_1.6.0    KernSmooth_2.23-17    ape_5.4
> [85] spatstat.data_1.4-3   stringi_1.4.6         spatstat_1.64-1
> [88] parallel_3.6.3        Rcpp_1.0.5            rpart_4.1-15
> [91] vctrs_0.3.2           sctransform_0.2.1     png_0.1-7
> [94] tidyselect_1.1.0      lmtest_0.9-37

My Linux system has 48 CPU cores (96 virtual processors with hyperthreading) and 1.5TB of RAM.
I also tried it on my personal MacBook in Rstudio but this line of code with "cca" reduction makes Rstudio crash with a fatal error.

Could you please help me with this?

p.n: I tried the solutions discussed in [this link](https://github.com/satijalab/seurat/issues/2259) but didn't help. I also tried setting the default assay for the scATAC-seq data to "RNA" as mentioned in [this answer](https://github.com/satijalab/seurat/issues/2247#issuecomment-553445323), but the error is not fixed.

**Comment by timoast** [comment]
How many features are shared between the assays that you're trying to integrate?

```r
length(intersect(rownames(pbmc_rna[["RNA"]]), rownames(pbmc_atac[["ACTIVITY"]])))
```

**Comment by elhaam** [comment]
Hi @timoast , thank you very much for your response! I checked my files and figured that pbmc_rna included Ensemble gene IDs while the other one had gene symbols. I converted the Ensemble IDs to gene names so now I have the following:

`
length(intersect(rownames(pbmc_rna[["RNA"]]), rownames(pbmc_atac[["ACTIVITY"]])))
`
[1] 13311

`
head(rownames(pbmc_rna[["RNA"]]))
`
[1] "CLCA4"   "GLT8D1"  "ATP2C1"  "IGF1"    "SLC38A5" "RALBP1" 

`
head(rownames(pbmc_atac[["ACTIVITY"]]))
`
[1] "DDX11L1"       "RP11-206L10.2" "LINC01128"     "FAM41C"        "RP11-54O7.16"  "RP11-54O7.3"  

My previous problem is solved, but now I get this error:

`
transfer.anchors <- FindTransferAnchors(reference = pbmc_rna, query = pbmc_atac, reduction = "cca", 
                                         features = VariableFeatures(object = pbmc_rna), 
                                         reference.assay = "RNA", query.assay = "ACTIVITY") 
`

> Error in if (length(x = features)/nfeatures < 0.1 & verbose) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In RunCCA.Seurat(object1 = reference, object2 = query, features = features,  :
  Running CCA on different assays


Would you please help me with this?
Thank you very much!

**Comment by timoast** [comment]
You need to run `FindVariableFeatures` on the `pbmc_rna` dataset prior to `FindTransferAnchors`. In this case, you're not providing any features to use when running the integration, which is why you see the error.
