### ISSUE TITLE
Problem with AverageExpression() even when using RNA method 

### ISSUE THREAD

**Issue by biobug16** [satijalab/seurat#3365]
Hi @timoast 
Thank you Seurat team for developing such a nice pipeline and making our life much easier.

By referring a recent post: [Problem with average when using SCT method #3130](https://github.com/satijalab/seurat/issues/3130), I am trying to calculate the average expression using 
`cluster.averages <- AverageExpression(test)
`
and referring RNA values to export its raw counts but getting "Inf" as its value for most of the genes.
Example:
>cluster.averages$RNA['EGFR','Tumor Cells']
[1] Inf

>cluster.averages$RNA['SEC61G','macrophage']
[1] Inf

>cluster.averages$RNA['SPP1',]
     T cell macrophage microglia Oligodendrocyte Tumor Cells
SPP1    Inf        Inf       Inf             Inf         Inf

 @timoast @saeedfc @semir2 can any of you please explain why I am getting this instead of an average read count?

Thanks

**Comment by yuhanH** [comment]
Hi, 
Have you normalized RNA counts before `AverageExpression`?
Would you mind to provide more codes you ran?
