### ISSUE TITLE
DoHeatmap for module scores

### ISSUE THREAD

**Issue by laijen000** [satijalab/seurat#3366]
Thank you for this wonderful tool!

I would like to know whether it is possible to plot module scores obtained by AddModuleScore() for a gene set of interest using DoHeatmap. I was able to plot module scores using FeaturePlot(), but DoHeatmap(seurat_object, features = 'genesetScore1') leads to the error: No requested features found in the scale.data slot for the SCT assay.

Thank you for your help!

**Comment by mojaveazure** [comment]
`DoHeatmap` can only plot feature expression levels, not values found in metadata (where module scores are kept). To get around this, you can save the module scores as an `Assay`, and visualize that. An example is posted below

```r
library(Seurat)
library(SeuratData)
InstallData("pbmc3k")
data('pbmc3k.final')
cd.features <- grep(pattern = '^CD', x = rownames(x = pbmc3k.final), value = TRUE)
pbmc3k.final <- AddModuleScore(object = pbmc3k.final, features = list(cd.features), name = 'cdfeatures')
pbmc3k.final[['cdmodule']] <- CreateAssayObject(data = t(x = FetchData(object = pbmc3k.final, vars = 'cdfeatures1')))
DoHeatmap(object = pbmc3k.final, features = 'cdfeatures1', assay = 'cdmodule', slot = 'data')
```

However, we're not sure that this visualization will work for what you need. Can you give it a try and let us know how it looks so that we can discuss optimizations to `DoHeatmap` for module scores

**Comment by laijen000** [comment]
Thank you! This worked great. After creating the assay as instructed above, I visualized the average module score for each cell type by doing seuratobject_avg <- AverageExpression(seuratobject, return.seurat=TRUE) and DoHeatmap(object = seuratobject_avg). 

On a related note, how can computing a module score be interpreted differently than just getting the average expression of my gene set of interest for each cell type? If I have a gene set and I want to see which cell type expresses this gene set the most, would you recommend using module scores or just computing the average normalized RNA expression? 

Thank you again!

**Comment by andrewwbutler** [comment]
The module score incorporates information about a "control" set of features. For details see `?AddModuleScore`. This will likely be a more robust representation than simply averaging but in many cases, they will likely tell you the same thing.

**Comment by areyoukidneyme** [comment]
> `DoHeatmap` can only plot feature expression levels, not values found in metadata (where module scores are kept). To get around this, you can save the module scores as an `Assay`, and visualize that. An example is posted below
> 
> ```r
> library(Seurat)
> library(SeuratData)
> InstallData("pbmc3k")
> data('pbmc3k.final')
> cd.features <- grep(pattern = '^CD', x = rownames(x = pbmc3k.final), value = TRUE)
> pbmc3k.final <- AddModuleScore(object = pbmc3k.final, features = list(cd.features), name = 'cdfeatures')
> pbmc3k.final[['cdmodule']] <- CreateAssayObject(data = t(x = FetchData(object = pbmc3k.final, vars = 'cdfeatures1')))
> DoHeatmap(object = pbmc3k.final, features = 'cdfeatures1', assay = 'cdmodule', slot = 'data')
> ```
> 
> However, we're not sure that this visualization will work for what you need. Can you give it a try and let us know how it looks so that we can discuss optimizations to `DoHeatmap` for module scores

I tried using these codes but when I run `DoHeatmap` it gives me this error:
` ` `
Error in DoHeatmap(object = pbmc3k.final, features = 'cdfeatures1', assay = 'cdmodule',  : 
  No requested features found in the data slot for the cdmodule assay.
` ` `

Can anyone help me with this?
