### ISSUE TITLE
bioinformation issue about doheatmap

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3367]
Hi @timoast and all,
     A few of cells  distrubuted  uncorrectly on doheatmap cluster , the pictures showing below,
![image](https://user-images.githubusercontent.com/41668708/89748931-4a35b600-daf8-11ea-87a2-431cf2180af0.png)
     How to extract those cells at the red frame on the picture showing above. i hope to reallocate those cells to firoblasts cluster indicated on above picture.
      Best,
      hanhuihong

**Comment by andrewwbutler** [comment]
Hi,

You can use the `WhichCells` function to gate out particular cells of interest in a manual way by setting certain thresholds/cutoffs.
