### ISSUE TITLE
AddModuleScore

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#3368]
Dear all,

I want to assign a module score. However, even though I pass the genes as a list to the funtion, I am getting scores for each single gene:
obj <- AddModuleScore(obj, features = features, name = module.name, assay = "SCT")

feature is a list:
> features 
[[1]]
 [1] "APAF1"   "ARHGDIB" "BIRC2"   "BIRC3"   "CASP1"   "CASP10"  "CASP2"   "CASP3"   "CASP4"   "CASP6"  
[11] "CASP7"   "CASP8"   "CASP9"   "DFFA"    "DFFB"    "GZMB"    "LMNA"    "LMNB1"   "LMNB2"   "PARP1"  
[21] "PRF1"    "XIAP"   

How can I get a joint score?

Thanks, Chris

**Comment by samuel-marsh** [comment]
Hi Chris,

What is the code you ran to create `features`?

Best,
Sam

**Comment by balthasar0810** [comment]
It was just reading in a text document:
module.name="Apoptosis"
geneset=read.table(file = "/Users/chhinze/Dropbox/COVID/Analyses/all_samples/clustering.all/apoptosis.txt", header = T)#, quote = F)
features=geneset[,1]
features=list("Necrosis"=as.character(features))

It now produced 1 score after giving a name to the list entry ("Necrosis") but creates a score called "Necrosis1" in the meta.data. Is this default behaviour?

Thanks, Chris

**Comment by samuel-marsh** [comment]
Hi Chris,

Yes, Seurat adds the "1" to the end of the name that you provide in the `AddModuleScore` function.  Glad your issue is resolved.

Best,
Sam

**Comment by balthasar0810** [comment]
Thanks, maybe you can add that a "named list" (?) must be provided to the docu...? Best, CHris
