### ISSUE TITLE
How to get MetaDE?

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#337]
Dear all,

as you know, FindConservedMarkers needs MetaDE. However, it has been removed from CRAN. What is the workaround?

Thanks, Chris

**Comment by kathyushakov** [comment]
You should use metap instead. See answer to issue #316

**Comment by balthasar0810** [comment]
Thanks but this does not work for me. When I import metap, I still get the error message:
"Error in FindConservedMarkers(kidney.combined, ident.1 = 5, grouping.var = "cond",  :
  Please install MetaDE (note Bioconductor dependencies) - learn more at https://cran.r-project.org/web/packages/MetaDE/index.html "

Thanks for your support!

----------
Dr. med Dipl.-Math. Christian Hinze

AG Schmidt-Ott
Max-Delbrück-Centrum
für Molekulare Medizin (MDC) Berlin-Buch
Robert-Rössle-Str. 10
13125 Berlin
Tel.: +49 30 9406 3240
christian.hinze@mdc-berlin.de

Medizinische Klinik mit Schwerpunkt Nephrologie
Charité - Universitätsmedizin Berlin
Campus Benjamin Franklin
Hindenburgdamm 30
12203 Berlin
Tel. +49 30 8445 2441
christian.hinze@charite.de<mailto:kai.schmidt-ott@charite.de>
________________________________
Von: katush [notifications@github.com]
Gesendet: Donnerstag, 1. März 2018 19:45
An: satijalab/seurat
Cc: balthasar0810; Author
Betreff: [ext] Re: [satijalab/seurat] How to get MetaDE? (#337)


You should use metap instead. See answer to issue #316<https://github.com/satijalab/seurat/issues/316>

**Comment by leonfodoulian** [comment]
Hi,

What is the version of the `Seurat` package you are using? You should probably update that to the latest version.

Best,
Leon

**Comment by balthasar0810** [comment]
My R version is 3.4.1, Seurat is 2.2.0. Thanks!!

----------
Dr. med Dipl.-Math. Christian Hinze

AG Schmidt-Ott
Max-Delbrück-Centrum
für Molekulare Medizin (MDC) Berlin-Buch
Robert-Rössle-Str. 10
13125 Berlin
Tel.: +49 30 9406 3240
christian.hinze@mdc-berlin.de

Medizinische Klinik mit Schwerpunkt Nephrologie
Charité - Universitätsmedizin Berlin
Campus Benjamin Franklin
Hindenburgdamm 30
12203 Berlin
Tel. +49 30 8445 2441
christian.hinze@charite.de<mailto:kai.schmidt-ott@charite.de>
________________________________
Von: Leon Fodoulian [notifications@github.com]
Gesendet: Freitag, 2. März 2018 22:12
An: satijalab/seurat
Cc: balthasar0810; Author
Betreff: [ext] Re: [satijalab/seurat] How to get MetaDE? (#337)


Hi,

What is the version of the Seurat package you are using? You should probably update that to the latest version.

Best,
Leon

**Comment by leonfodoulian** [comment]
Try updating to the latest version of `Seurat`, version 2.2.1. This should fix your problem.

Best,
Leon

**Comment by balthasar0810** [comment]
Recommended installation/update from within RStudio gives only 2.2.0

> update.packages("Seurat")
> packageVersion("Seurat")
[1] ‘2.2.0’

----------
Dr. med Dipl.-Math. Christian Hinze

AG Schmidt-Ott
Max-Delbrück-Centrum
für Molekulare Medizin (MDC) Berlin-Buch
Robert-Rössle-Str. 10
13125 Berlin
Tel.: +49 30 9406 3240
christian.hinze@mdc-berlin.de

Medizinische Klinik mit Schwerpunkt Nephrologie
Charité - Universitätsmedizin Berlin
Campus Benjamin Franklin
Hindenburgdamm 30
12203 Berlin
Tel. +49 30 8445 2441
christian.hinze@charite.de<mailto:kai.schmidt-ott@charite.de>
________________________________
Von: Leon Fodoulian [notifications@github.com]
Gesendet: Samstag, 3. März 2018 17:38
An: satijalab/seurat
Cc: balthasar0810; Author
Betreff: [ext] Re: [satijalab/seurat] How to get MetaDE? (#337)


Try updating to the latest version of Seurat, version 2.2.1. This should fix your problem.

Best,
Leon
