### ISSUE TITLE
Assay parameter in FindAllMarkers

### ISSUE THREAD

**Issue by Jayjay601** [satijalab/seurat#3372]
Hi,

Why do the following two methods return different results? Is setting the assay parameter in FindAllMarkers to "RNA" working the same way as setting the assay to RNA? 

1)
```
DefaultAssay(seurat.integrated)<-"RNA"
DE<-FindAllMarkers(seurat.integrated)

```

2) resulted in no genes with FC > 0
```
DefaultAssay(seurat.integrated)<-"SCT"
DE_SCT_setRNA<-FindAllMarkers(seurat.integrated,assay="RNA")
```

Thank you,

J

**Comment by andrewwbutler** [comment]
Hi,

Those should be equivalent.  Can you provide a reproducible example where they are different?

**Comment by Jayjay601** [comment]
Hi! I cleared everything and reran and I got the same results regardless of the DefaultAssay that was set to. 
Thank you!
