### ISSUE TITLE
Color cells based on the specific range of expression of a given gene

### ISSUE THREAD

**Issue by sumitava1992** [satijalab/seurat#3376]
Hi,
First of all, thank you for this great tool. I am new in this field and until now have managed to cluster the cells and annotate them. I have also used the "FeaturePlot" function of Seurat. My question is, is there any option so that I can color cells that have gene expression value above a certain limit(eg: cells expressing "KRT5" > 0.3 as "red"). 
Also is there any option to set a condition so that I can get 2 colors for high and low expression of a gene within a cluster( eg: if "KRT5"> 0.6 then "red" if "KRT5"< 0.2 then "blue").
Thank you

**Comment by jaisonj708** [comment]
In the first case, you can use the `cells.highlight` parameter of `DimPlot`.

In the second case, you might want to add a metadata column like `KRT5.level` with categorical expression values of high, low, or NA. Then: 

```
DimPlot(
  object = pbmcsca,
  group.by = 'KRT5.level',
  cols = list("high" = "red", "low" = "blue")
)
```
