### ISSUE TITLE
from Seurat to phemd

### ISSUE THREAD

**Issue by sdwien** [satijalab/seurat#3378]
Dear all,
is it possible to use a Seurat object with phemd ( https://www.bioconductor.org/packages/release/bioc/vignettes/phemd/inst/doc/phemd.html ), and if so, where to start? Unfortunately, this is not described in the phemd vignette; I also posted an issue there but did not get any reply, so maybe you can help me here?
Many thanks,
best,
Sophia

**Comment by mojaveazure** [comment]
According to the documentation of [`createDataObj`](https://rdrr.io/bioc/phemd/man/createDataObj.html), you can use a `SingleCellExperiment` object as input. As such, you should be able to convert your `Seurat` object to a `SingleCellExperiment` to read into PhEMD. As this package is not developed by the Seurat team, you will have to rely on the PhEMD developers for further support.
