### ISSUE TITLE
Error in names(x) <- valye :   'names' attribute [3] must be the same length as the vector [2]

### ISSUE THREAD

**Issue by July233** [satijalab/seurat#3379]
When I used seurat to intergrate ATAcseq and RNAseq data , I have an error.
scrip:
I used Genome Reference  GRCm38(mouse)
run:
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, 
                                            annotation.file = gtf_file, 
                                             seq.levels = c(1:19, "X", "Y"),
                                             upstream = 2000, 
                                            verbose = TRUE)
Then:
Error in names(x) <- valye :   'names' attribute [3] must be the same length as the vector [2]
Can you help me?very thanks

**Comment by timoast** [comment]
We now recommend using the Signac package for computing gene activities: https://satijalab.org/signac/

If you have to use the `CreateGeneActivityMatrix` function, rather than the newer methods in Signac, can you provide a reproducible example?

**Comment by July233** [comment]
> We now recommend using the Signac package for computing gene activities: https://satijalab.org/signac/
> 
> If you have to use the `CreateGeneActivityMatrix` function, rather than the newer methods in Signac, can you provide a reproducible example?

Thanks your answer.Then , I will use the signac method to try it. And, this approach(CreateGeneActivityMatrix) is adopted because of this example https://satijalab.org/signac/articles/pbmc_vignette.html
