### ISSUE TITLE
Cluster Label Colors for DarkTheme

### ISSUE THREAD

**Issue by rmaho31** [satijalab/seurat#338]
Hi,
 Kind of random but for the darkTheme with the TSNEplot function how can I make the identity labels show up white? 

Thanks

**Comment by satijalab** [comment]
Right now we don't support changing the cluster ID color labels. Its not a bad idea, but we likely won't have the bandwidth to implement in the near future. Would be great if you would consider a pull request.

**Comment by chansigit** [comment]
adding this line before DimPlot helps.

Tested in both V2 and V3

`update_geom_defaults("text", list(colour = "white"));`
