### ISSUE TITLE
Extracting cropped image and associated scalefactors

### ISSUE THREAD

**Issue by dgacquer** [satijalab/seurat#3380]
Dear all,

thanks for providing the Seurat package.

I am using the spatial version of Seurat and I would like to extract the 'cropped' image displayed by default with SpatialDimPlot and SpatialFeaturePlot along with the corresponding scalefactors / spot coordinates.

I have checked the structure of the Seurat object but the only image I could find is the 'tissue_lowres_image.png' default image and I could not find in the source code of 'spatial.R' where the image is actually cropped.

Is there a way to extract this information ?
  
Best regards,

David

**Comment by mojaveazure** [comment]
Hi David,

The cropping that happens is just adjusting the viewport to only show the spots, and not include the background. We do this on the fly with the [`GeomSpatial`](https://github.com/satijalab/seurat/blob/master/R/visualization.R#L5606:L5688) geom. As such, we don't actually compute a cropping or adjust the spot coordinates. Do you need this information for visualization purposes (in which case, you can just use the geom) or for something else?

**Comment by dgacquer** [comment]
Dear Paul,


Thanks for your answer.


I want to use SPOTlight
(https://github.com/MarcElosua/SPOTlight)
 to run spot deconvolution. This package takes a spatial seurat object as input.
However, the plotting function from SPOTlight uses 'tissue_lowres_image.png'
but does not provide any crop option, and a large fraction of my image does not contain tissue.
So I wanted to extract the cropped image from SpatialDimPlot and the corresponding point coordinates to use them as input for SPOTlight.


Now that I understand a bit more the structure of the spatial seurat object, I think I will write my own plotting function to crop the image and only select spots corresponding to tissue.


But I have another question regarding the spot radius.



From the function 'Read10X_Image'
in 'spatial.R', I see that the spot radius is obtained with :



unnormalized.radius
<-
scale.factors$fiducial_diameter_fullres
*
scale.factors$tissue_lowres_scalef


spot.radius
<-
unnormalized.radius
/ max(dim(x
=
image))


But from the 10X Genomics documentation :



fiducial_diameter_fullres: The number of pixels that span the diameter of a fiducial spot in
 the original, full-resolution image


spot_diameter_fullres: The number of pixels that span the diameter of a tissue spot in the original,
 full-resolution image


Should I use
'spot_diameter_fullres' instead of
'fiducial_diameter_fullres' since the tissue
spots are smaller than the fiducial spots ?



Thanks a lot for your help,


Best regards,


David

**Comment by mojaveazure** [comment]
For plotting the spots, you should use the tissue spot, as that's the spot you see colored on Seurat's plots. You can also just call `Radius` on an image object in your `Seurat object to get the proper point radius for each spot, since we take care of all the reading in and normalization of image data for you.
