### ISSUE TITLE
Creating larger groups from cell type specific markers

### ISSUE THREAD

**Issue by naoimhl** [satijalab/seurat#3381]
Hi all 

So I have worked trough a clustering tutorial for single cell, and I have identified 22 cell types in my data. I am now looking to create a column which groups some of these cell types into a larger category.

For example, I have "Interneuron" cell type labels in my meta data; 
Int1
int2
in3
in4
in5

I would like to create a separate column in the metadata labeling all cells with these labels as "Inter-neurons". 
Could someone help me figure out how to do this? Im relatively new to R so i know it might be super simple!!

**Comment by jaisonj708** [comment]
If your metadata column were named `CellType`, this would work:

`object[['CellType', drop=T]][object[['CellType', drop=T]] %in% paste0("int",1:5))] <- "Interneuron"`
