### ISSUE TITLE
How expression data is normalized in AverageExpression

### ISSUE THREAD

**Issue by sunliang3361** [satijalab/seurat#3382]
Hi, 
Based on the tutorial (https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/AverageExpression), the default setting will give a non-log space average values for each gene. Since all reads counts of each gene is log normalized. If one gene is lowly expressed, the normalized expression data can be negative values. In this case, the AverageExpression should have negative values for some genes. However, I found all average expression values are non negative. Can you tell how this averageExpression function normalize the gene expression for genes? Thank you.

**Comment by jaisonj708** [comment]
AverageExpression assumes the values in your `data` slot are log-normalized. By default, it will exponentiate these and return the average of the resulting values (i.e, non-log space). If your data was not log-normed, any negative values will become positive.
