### ISSUE TITLE
Genes lost in FindMarkers after normalization

### ISSUE THREAD

**Issue by LCBartelt** [satijalab/seurat#3383]
I am having an issue retaining genes in differential expression gene lists with `FindMarkers`. I created two cell populations based on presence/absence of a gene (Fos).

`Idents(Normdata, WhichCells(object = IHV_PvalbSeurat, expression = Fos > .5 & Celltypemarker > 0.5, slot = 'data')) <- 'fos.pos'
Idents(Normdata, WhichCells(object = IHV_PvalbSeurat, expression = Fos < .1 & Celltypemarker > 0.5, slot = 'data')) <- 'fos.neg'`

I am now trying to compute DE between the two populations - which seems to drop out genes of interest to me when performed from normalized vs. raw data.

`fosmarker <- FindMarkers(Normdata, ident.1 = 'fos.pos', ident.2 = 'fos.neg')`

Two genes which I would expect to see, are present with significant pvalues when computed from raw data, while they do not even show up when computed from normalized data (even though the list contains genes all the way up to pval = 1).

After normalization, I can still create violin plots of the genes which I have attached. Does anyone know why these genes do not show up in `FindMarkers` after normalization?? 

![excludedgenesRAW](https://user-images.githubusercontent.com/34760940/90322151-9466cf00-df1e-11ea-8749-1e0510d0bd84.PNG)
![excludedgenesNORM](https://user-images.githubusercontent.com/34760940/90322153-9761bf80-df1e-11ea-9d91-ecc35af0a1a4.PNG)

**Comment by AndyR2** [comment]
Is this an Sv3 integrated dataset? 
If so, and you type [your_object_name] and hit enter, you should see something like this
```
#obj
    An object of class Seurat 
    42875 features across 15365 samples within 3 assays 
    Active assay: RNA (21019 features, 0 variable features)
      2 other assays present: SCT, integrated
      3 dimensional reductions calculated: pca, tsne, umap`

#make RNA assay the default
DefaultAssay(obj)  <- "RNA"
obj_RNA <- NormalizeData(obj, verbose = FALSE)
```
