### ISSUE TITLE
regress ribosome genes, cell cycle genes and mitochondrial genes

### ISSUE THREAD

**Issue by mianmianyin** [satijalab/seurat#3387]
Hi ,
I plan to regress ribosome genes, cell cycle genes and mitochondrial genes in the  integrated  data
how can i regress those genes?

**pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, dims = 1:30)**

**Comment by jaisonj708** [comment]
You can use `ScaleData` with the `vars.to.regress` parameter set to the desired metadata columns.
