### ISSUE TITLE
Error when aligning subspace

### ISSUE THREAD

**Issue by dandepledge** [satijalab/seurat#339]
**I'm attempting to AlignSubspace with limited CCs**

_comparison.integrated <- CalcVarExpRatio(object = comparison.integrated, reduction.type = "pca", grouping.var = "cond", dims.use = c(2,3,5))

comparison.integrated <- SubsetData(comparison.integrated, subset.name = "var.ratio.pca", accept.low = 0.5)_

**While the prepping of the data seems to work, the following throws up an error**

_comparison.integrated <- AlignSubspace(comparison.integrated, reduction.type = "cca", grouping.var = "cond", dims.align = c(2,3,5))_

Rescaling group 1
[1] "Scaling data matrix"
  |==================================================================================================================================================| 100%
Rescaling group 2
[1] "Scaling data matrix"
  |==================================================================================================================================================| 100%
Rescaling group 3
[1] "Scaling data matrix"
  _|==================================================================================================================================================| 100%
Aligning dimension 2
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 03s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 03s
Aligning dimension 2
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
Aligning dimension 3
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
Aligning dimension 3
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
Aligning dimension 5
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 02s
Error in `[<-`(`*tmp*`, names(x = sort(x = cc.embeds[[g]][, cc.use])),  : 
  subscript out of bounds_

Any thoughts?

**Comment by dandepledge** [comment]
Turns out this issue can be resolved by specifying "check_duplicates = FALSE" under RunTSNE

**Comment by xbjie123** [comment]
Sorry, I meet the same problem. I still don't know how to deal with it. Could you explain it?

Best
Thanks,
BJ

**Comment by miko-798** [comment]
Same here, I keep getting 
`scaled.data[[i]][genes.use, ] : subscript out of bounds
`
or 
`Error during wrapup: subscript out of bounds`

Could someone explain the solution?
