### ISSUE TITLE
ggplot 

### ISSUE THREAD

**Issue by NaomiCroft** [satijalab/seurat#3390]
Hi,
I want to make a plot which colours the different sample origins. I have 11 samples, which are marked by adding _01, _02, _03 ... _11.

Below  have used this script to make samples "01", "02", "03", "04" from Fish 1 as red and the other samples as grey. I would like a third colour, so "01", "02", "03", "04" as red, "05", "06", "07", "08" as blue (for example) and the remaining samples grey.

Any suggestions would be greatly appreciated! 

```{r}
myPCA <- Embeddings(object = allsample.data.seurat[['umap']])

samples <- row.names(myPCA)
myPCA <- as.tibble(data.frame(id = samples, myPCA, row.names = NULL))
myPCA <- separate(myPCA, id, sep = "_", into = c("barcode", "sample"))

ggplot(myPCA, aes(UMAP_1, UMAP_2, colour = sample)) + geom_point()


myPCA$samples<- ifelse(myPCA$sample %in% c("01", "02", "03", "04"), "Fish 1", "Fish 2")


a <- ggplot(myPCA, aes(UMAP_1, UMAP_2, colour = samples)) + geom_point(size = 1, alpha = 0.2)
a + scale_colour_manual(values = c("grey", "red"))
```

**Comment by samuel-marsh** [comment]
Hi,

So you could do this with your ggplot code as well but can also be easily achieved within Seurat assuming that when you created object you specified the names parameter so that each barcode suffix (i.e. "_01" etc) is specified was assigned it's own orig.ident.

If that's the case then simply run:
```
fish1 <- c("01", "02", "03", "04")
fish2 <- c("05", "06", "07", "08")
fish3 <- c("09", "10", "11", "12")

# Add metadata
allsample@meta.data$sample[allsample@meta.data$orig.ident %in% fish1] <- "Fish 1"
allsample@meta.data$sample[allsample@meta.data$orig.ident %in% fish2] <- "Fish 2"
allsample@meta.data$sample[allsample@meta.data$orig.ident %in% fish3] <- "Fish 3"

# Plot by sample
DimPlot(allsample, group.by = "sample", cols = c("red", "blue", "grey"))
```

Best,
Sam

**Comment by NaomiCroft** [comment]
Thanks Sam!
I get this message when I try it
> allsample@meta.data$sample[allsample@meta.data$orig.ident %in% fish1] <- "Fish 1"
Error in allsample@meta.data$sample[allsample@meta.data$orig.ident %in%  : 
  object 'allsample' not found

I imagine this is a 'version' issue and I need to find the right word to use? Any ideas?

best wishes,
Naomi

**Comment by samuel-marsh** [comment]
Hi Naomi,

allsample is just whatever your object name is.  It's what I thought the name was in first post.

Best,
Sam

**Comment by NaomiCroft** [comment]
I see! :)
