### ISSUE TITLE
Regress out cell covariate after SCTransform already done

### ISSUE THREAD

**Issue by johnchamberlin** [satijalab/seurat#3391]
Hello,

I've noticed a few examples of regressing out cellular covariates (mitochondrial pct, cell cycle), but the utility of doing so is not clearly demonstrated. As such I'm trying to run an experiment with SCTransform() and different vars.to.regress options. However, the SCTransform() computation is quite slow, so my question is whether or not it is possible to run the various regression schemes on a pre-computed sctransformed object?

My understanding is that the SCT slot is generated, the optional regression step is performed, and then the values are centered. Is the centering step reversible, or, are the pre-regressed values stored somewhere in the final result?

Thanks

**Comment by jaisonj708** [comment]
Centering is not reversible, but you can simply run `SCTransform` with `do.center = FALSE`. Then you can regress out whatever you'd like on this pre-computed object using `ScaleData` (this time with `do.center = TRUE`). Something like:

```
obj[['SCT']]@scale.data <- ScaleData(
    obj[['SCT']]@scale.data,
    features = NULL,
    vars.to.regress = <vars.to.regress>,
    latent.data = <metadata with vars.to.regress>,
    model.use = 'linear',
    use.umi = FALSE,
    do.scale = FALSE,
    do.center = TRUE,
    scale.max = Inf,
    block.size = 750,
    min.cells.to.block = 3000
  )
```
