### ISSUE TITLE
Seurat FindMarkers avg_logFC for integrated dataset

### ISSUE THREAD

**Issue by pbpayal** [satijalab/seurat#3397]
Hi,

I am having trouble understanding the avg_logFC results of an integrated dataset (control and condition) in Seurat (3.1) for the FindMarkers pipeline.

gene_name p_val avg_logFC pct.1 pct.2 p_val_adj

gene1 0 -0.270265934 1 0.115 0

gene2 0 -0.332681178 1 0.167 0

gene3 7.25E-119 0.251635681 0.855 0.238 1.45E-115

gene4 2.10E-86 0.255847237 0.856 0.293 4.19E-83

gene5 2.84E-76 0.257140547 0.923 0.399 5.68E-73

pct.1 represents control in cluster1 and pct.2 represents condition in cluster 1.

According to Seurat vignettes - avg_logFC : log fold-chage of the average expression between the two groups. Positive values indicate that the feature is more highly expressed in the first group

What about negative values? For gene 1, avg_logFC is -0.2. Does that mean gene 1 is downregulated in control group in cluster 1? But why is percentage of cells expressed in gene1 more in control cells than condition cells?

Am I missing something?

Thanks
Payal

**Comment by AndyR2** [comment]
```
#first switch to RNA assay
DefaultAssay(objecti)  <- "RNA"
object_RNA <- NormalizeData(object, verbose = FALSE)

#then, find markers for every cluster compared to all remaining cells, report only the positive ones
object_RNA.markers <- FindAllMarkers(object_RNA, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```
ps.
there's plenty of discussion of why the RNA assay is appropriate here.   and, you're Q re: logFC is so basic, the Sv3 primer vignette is a place you should explore too.

**Comment by pbpayal** [comment]
Thank you. Can you please point me to discussions of why and how the "RNA" assay is different from "integrated" assay. That will be really helpful.

**Comment by AndyR2** [comment]
start here:
https://github.com/satijalab/seurat/issues/1717

**Comment by Paperplane1031** [comment]
I am confused about the two ways for normalizing in integrated dataset before findmarkers: whether I should log normalize the data in each dataset seurat object separately and then merge(merge data slot), or I should log normalize it in a whole merge object? I found the two way's findmarkers outcome(gene numbers, genes logFC and some gene names) are different. Could anyone help answer my questions? Thanks a lot.
