### ISSUE TITLE
New version only: dim(X) must have a positive length

### ISSUE THREAD

**Issue by maximilianh** [satijalab/seurat#34]
Hi, we used to be able to run a dataset through Seurat, but when we updated to the new version, we're getting this:

```
[1] "Calculating gene dispersion"
  |======================================================================| 100%
Warning message:
In KernSmooth::bkde2D(x, bandwidth = bandwidth, gridsize = nbin,  :
  Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'
[1] "Seurat: PCA"
Error in apply(data.use[pc.genes, ], 1, var) : 
  dim(X) must have a positive length
Calls: PCA -> PCA -> apply
Execution halted
```

**Comment by andrewwbutler** [comment]
Which version did you update from? Also, what were the actual commands that you ran to get this error?

**Comment by maximilianh** [comment]
Can you tell me how I can find out the seurat version or commit ID? It was
probably six months old.

**Comment by andrewwbutler** [comment]
You can run `packageVersion("Seurat")` to get the version number but if it's been that long, I'm pretty sure it was 1.2. It's a bit hard to tell exactly what's going wrong without your commands/data but I would guess that the gene list you're supplying to PCA() or PCAFast() is either empty or contains gene names that aren't in the data matrix.

**Comment by maximilianh** [comment]
Version 1.2.1

**Comment by maximilianh** [comment]
I'll follow up with a private email and send you the script and the data
file. We always use the same script, I just pasted from the tutorial.

**Comment by maximilianh** [comment]
Oh and of course many thanks for your quick replies!

**Comment by maximilianh** [comment]
This is what Andrew replied at the time, in case someone comes across this by searching for the error message (in which case we appreciate your comments below, BTW). 
----
It seems the problem is that you only have one variable gene (as input to PCA). We'll add a more informative error message for this case in a future update but for now, try relaxing you cutoffs in the MeanVarPlot() function or provide your own gene list (of more than one gene) to PCA.
