### ISSUE TITLE
FindConservedMarkers vs FindAllMarkers with different batches

### ISSUE THREAD

**Issue by khandarius** [satijalab/seurat#340]
Hi Seurat team,

I have aligned data from two batches with CCA and performed clustering. I was wondering if I could simply use FindAllMarkers with the batch passed as a latent variable to identify common cluster markers. Would you advise against this? What would be the disadvantages compared to FindConservedMarkers?

With best regards,
Darius

**Comment by satijalab** [comment]
Thanks for this good question. First, not all of our tests allow for adding in covariates (although we could probably increase this). Second, in some cases (for example, if batches consist of different technology types), the variance and noise models associated with the two batches could be quite different, as opposed to simply a mean shift which would be captured by a covariate.

I suppose I would therefore lean towards meta-analyses, but would be happy to hear what others think. The issue of mega vs. meta analysis is not unique to single cell analysis of course, and comes up in GWAS, etc.
