### ISSUE TITLE
fatal error while installing Seurat 3.2.0

### ISSUE THREAD

**Issue by mintlover** [satijalab/seurat#3401]
I am trying to install Seurat within RStudio on Mac.
install.packages('Seurat')
library(Seurat)
then my R session aborted with "R encounter a fatal error. The session was terminated".

R version is 3.6.3. Thank you.

**Comment by mojaveazure** [comment]
The image did not come through as attachments are stripped when replying to an issue via email

**Comment by mintlover** [comment]
![Screen Shot 2020-08-21 at 4 30 12 PM](https://user-images.githubusercontent.com/26310104/91515688-8d38ad00-e89e-11ea-80c6-c7749a776b94.png)
Here is the screenshot. Thanks.

**Comment by mojaveazure** [comment]
Are you able to load Seurat from the R console? Try opening R from the terminal and load Seurat from there. If it works, then there's an issue with RStudio. If not, then we can debug further.
