### ISSUE TITLE
Selectively clone parts of large seurat object?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#3402]
Hello,

I have a large multi-assay seurat object.  I'd like to subset this object to create a new one with just one assay and a subset of features.  I'd like to leave the original object intact.  I originally began with something like:

x <- subset(seuratObj, features = genesPresent)

This kept failing with the message: "Error: Under current subsetting parameters, the default assay will be removed. Please adjust subsetting parameters or change default assay".  I was able to debug this, and what I think is happening is that subset.Seurat fails on line 6094 with a 'cannot allocate vector of size X' message, which is just swallowed.  The effect is that all assays become NULL.

Is there another way to create a stripped-down object, which I could then subset by features?

Thanks,
Ben

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by bbimber** [comment]
thank you
