### ISSUE TITLE
Question: Experimental condition specific DEG for GO analysis

### ISSUE THREAD

**Issue by KatsuyukiNAKANISHI** [satijalab/seurat#3403]
Dear Seurat users and Seurat team,

(I'm a PhD student working on single cell data analysis for 1 year. I'm using a dataset which is obtained from nuclear-Drop-seq) 
I'm trying to calculate experimental condition specific DEG (differentially expressed genes) for GO analysis.
I applied "Tutorial: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses" work-flow.
I performed integration process among experimental conditions for clustering. Then, I switched to RNA slot for DE analysis between experimental conditions because it is recommended. 

In the analysis, I found integrated 2,000 genes can predict biological function more precisely at the same cell type rather than using whole genes (18,121). (in the RNA slot after NormalizeData)
I don't know why this result looks good. Should I use whole genes?
I'd like to hear some opinions from other users and Seurat developer team.

Thank you very much for your help.

Sincerely,

Katsu

**Comment by ektapathak08** [comment]
I am working on scRNA-seq for drop-seq platform. It is a GEO dataset . I have the two fastq files for each sample.
Can I use cell ranger(which is for 10X genomics) to generate count matrix  that can be used as an input to Seurat?

**Comment by yuhanH** [comment]
HI, @ektapathak08 
Sorry for the delayed reply...

for your first question, we would suggest you use all RNA genes to do the differential analysis. Maybe you can have a try on `FindConservedMarkers` which is also used in [stimulated vs. control PBMC  vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html). It may give me more meaningful differential genes. 

For the second question, you can use cellragner output to generate count matrix by `Read10X()` or `Read10X_h5()`
