### ISSUE TITLE
Exporting normalized counts to 10X barcodes, features, matrix files

### ISSUE THREAD

**Issue by golharam** [satijalab/seurat#3407]
Currently CellRanger-4 features file contains both gene_id and gene_symbol.   After using sc_transform, I want to save the normalized matrix back to text files.   Does Seurat offer this ability?

**Comment by carlosaya2** [comment]
follow up question. after this I get the counts (raw) for every cell, how can I group them by sample name or condition?

```
write.table(as.matrix(GetAssayData(object = DS06combinedfiltered, slot = "counts")), 
            '/SCRATCH/CITE-Seq/Timo_carlos_22/DS06_single_cell_analysis/ADT_counts_v3.csv', 
            sep = ',', row.names = T, col.names = T, quote = F)
```
thank you
