### ISSUE TITLE
invalid character indexing

### ISSUE THREAD

**Issue by xiaokang8002** [satijalab/seurat#3409]
Hi

I used 'FindMarkers' to find DEG between a specific cluster of cells with different treatment.
I defined the 'features' to gene A, it worked well (I wanted to know the adj p value of a specific gene).
However when I defined the 'features' to gene B, it showed error as follows:
Error in h(simpleError(msg, call)) : ... (some chinese charaters which meant: error when evaluating parameter 'x' when choosing method for function ‘rowSums’): invalid character indexing.
I checked that both gene A and gend B existed in the data/Seurat object.

Could anyone please clarify this?

Thanks in advance.

**Comment by tengdali-90** [comment]
how do you resolve it?

**Comment by tengdali-90** [comment]
I resolve it. it is wrong, because the genesymbol is not right
