### ISSUE TITLE
Control ClassifyCells?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#341]
Hello Seurat Team,

This is actually a followup of issue #334, but I opened another issue as that was closed.

I have another question about ClassifyCells.  Even without thresholding (as per your reply in issue #334), is it possible to somehow "separately bin" those cells that don't fit well into any of the input predefined groups? That would be great for my purposes. Thanks again for any replies.

**Comment by satijalab** [comment]
Thanks, this is an interesting feature request. Its not something we support at the moment, but could consider going forward.
