### ISSUE TITLE
Question differential expression between conditions for Visium Spatial Transcriptomics

### ISSUE THREAD

**Issue by JoyOtten** [satijalab/seurat#3410]
Dear Seurat team,

I have a question related to do a differential expression analysis pattern between newly assigned clusters, based on scRNA-seq incorporation. Currently there is only the possibility to visualise the difference within your sample however, I have a mouse left hemisphere dataset containing 16 samples wherein I have an experimental condition of 8 vs 8. I would like to do a differential expression analysis between the condition and thus comparing different samples. However, I have some troubles which kind of differential expression analysis methods I could use for that since I can get the SCT normalized count data out from these samples however for every sample my clusters has a slightly different number of spots. I tried to use FindMarkers however, that does not allow me to integrate different samples. Furthermore,  I looked into DEseq2 however, Deseq2 is only applicable for raw-data counts and not for normalized data. Do you have any ideas on which kind of method I could use for differential expression analysis between the same clusters for different samples? Currently I am looking into limma however, I am not convinced to use that. 

With kind regards,
Joy Otten

**Comment by satijalab** [comment]
We'd recommend the following manuscript: https://www.biorxiv.org/content/10.1101/713412v3.full , which discusses the use of different methods. I'll add that we do not recommend performing differential expression (either within or across samples), using integrated data

**Comment by JoyOtten** [comment]
Hi,

I am not using the integrated data. I only use the integrated data to redefine my clusters and I actually go forward with the original ST data. It is then possible to do a differential expression analysis between my groups (8 vs 8)?

Kind regards,
Joy
