### ISSUE TITLE
Appearance of cells in a cluster after the integration, which is not there in individual datasets

### ISSUE THREAD

**Issue by Gnosta** [satijalab/seurat#3411]
Hi I am Andrew and thank you for the amazing upkeep of the package!

I have a bit of a contradictiory results regarding integration and am hoping to receive some input-

We have four 10X datasets of in vitro tissues of two types (two replicates for each type): Type1) with cell type X combined and Type2) without cell type X.
We have verified in histology that cell type X is indeed present and not present for each type of tissue. 

When I run the Seurat pipeline on individual datasets they give the expected results. No cell type X cluster in samples where no cell type X was combined and cell type X cluster is present if we did combine it.

But when I merge the Type1 datasets and merge Type 2 datasets and integrate the Type1 and Type2 objects, there are significant number of cells in Type 2 that cluster with cell type X cluster. And these 'mis-clustered' cells do not have canonical markers of cell type X as the 'real' cell type X do. Furthermore, cell type x clusters very close to other cell types though it is identified as a separate cluster by Seurat.

And when I merge all four datasets (without integration) and run the rest of the pipeline, the cell type X is only present in Type 1 samples as would expect them to be and as I have observed in individual analyses.

My end goal is to compare differential gene expression between Type1 and Type2 that may have occured due to the introduction of cell type X. Thus the effort to integrate the data.

Would you kindly give us your thoughts?

I have tried: 
1) using vast range of dimension for running umap
2)tried increasing nfeatures from 3000 to 5000 when using SelectIntegrationFeatures function
**also there are only very few of the cell type X (78 cells in a total of 63,517 across the four datasets)

Below are the script used (two objects of same type was merge and SCTransformed, then the two merged/sct'ed objects were integrated):
`
####An Example of processing two objects, merging and SCtransforming
  ##A1
  
  ##Load packages
  ```{r}
library(dplyr)
library(Seurat)
library(ggplot2)
library(patchwork)
library(future)
plan("multiprocess", workers = 2)
options(future.globals.maxSize=39045728000)
```

##Load dataset for A1
```{r}
A1.data <- Read10X(data.dir = "/home/")
```

##Create a Seurat object
```{r}
A1.data <- CreateSeuratObject(counts = A1.data, project = "A1", min.cells = 3, min.features = 200)
A1.data

```

##Filter data
```{r}
A1.data[["percent.mt"]] <- PercentageFeatureSet(A1.data, pattern = "^MT-")
VlnPlot(A1.data, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size =0.1)
plot1 <- FeatureScatter(A1.data, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(A1.data, feature1   = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

A1 <- subset(A1.data, subset = nFeature_RNA > 600 & nFeature_RNA < 5000 & nCount_RNA < 30000 & percent.mt > 0.5 & percent.mt < 15)

VlnPlot(A1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size =0)
plot1 <- FeatureScatter(A1, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(A1, feature1   = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

##Add metadata
```{r}
A1[["An.ident"]] <- "A"
```

##Save filtered-raw dataset
```{r}
saveRDS(A1, file = "/home/")
```

##Clear cache
```{r}
rm(A1.data)
gc()
```

##A2

##Load dataset for A2
```{r}
A2.data <- Read10X(data.dir = "/home/atsong/projects/def-andelfin/10X/Backup_CellRanger_analysis/raw_matrices_only/Andrew_20052710000A2_MPS12345148_E11_9671/raw_feature_bc_matrix/")
```

##Create a Seurat object
```{r}
A2.data <- CreateSeuratObject(counts = A2.data, project = "A2", min.cells = 3, min.features = 200)
A2.data

```

##Filter data
```{r}
A2.data[["percent.mt"]] <- PercentageFeatureSet(A2.data, pattern = "^MT-")
VlnPlot(A2.data, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size =0.1)
plot1 <- FeatureScatter(A2.data, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(A2.data, feature1   = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

A2 <- subset(A2.data, subset = nFeature_RNA > 600 & nFeature_RNA < 5000 & nCount_RNA < 30000 & percent.mt > 0.5 & percent.mt < 15)

VlnPlot(A2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size =0.1)
plot1 <- FeatureScatter(A2, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(A2, feature1   = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
```

##Add metadata
```{r}
A2[["An.ident"]] <- "A"
```

##Save filtered-raw dataset
```{r}
saveRDS(A2, file = "/home/")
```

##Clear cache
```{r}
rm(A2.data)
gc()
```

##A merge and sct

##Merge datasets
```{r}
A <- merge(A1, y = A2, project = "A")
```

#SCTransform: scale and regress out tA effect of mitochondrial genes, and cell cycle genes
```{r}
rm(A1, A2)
gc()

s.genes <- cc.genes.updated.2019$s.genes
g2m.genes <- cc.genes.updated.2019$g2m.genes

#Need to normalize before cell cycle scoring

A <- NormalizeData(object = A, normalization.method = "LogNormalize", scale.factor = 1e4)

A <- CellCycleScoring(A, s.features = s.genes, g2m.features = g2m.genes, set.ident = T)

DefaultAssay(A) <- "RNA"

A <- SCTransform(A, vars.to.regress = c("percent.mt", "S.Score", "G2M.Score"), verbose = T)

```

#########How the two types were integrated

##Load package
```{r}
library(dplyr)
library(Seurat)
library(ggplot2)
library(patchwork)
library(cowplot)

```

##Read data: data are already filtered (equal parameters) and SCTransformed
```{r}
A <- readRDS(file = "/home/")

B <- readRDS(file = "/home/")

```

##Integration (dim value recommendation 10-50)
```{r}

DefaultAssay(A) <- "SCT"
DefaultAssay(B) <- "SCT"

reference.list <- list(A, B)

rm(A, B)
gc()

AB.integrated.features <- SelectIntegrationFeatures(object.list = reference.list, nfeatures = 3000)

reference.list <- PrepSCTIntegration(object.list = reference.list, anchor.features = AB.integrated.features, 
                                     verbose = T)

AB.integrated.anchors <- FindIntegrationAnchors(object.list = reference.list, normalization.method = "SCT", 
                                                 anchor.features = AB.integrated.features, verbose = T)
rm(reference.list)
gc()

AB.integrated <- IntegrateData(anchorset = AB.integrated.anchors, normalization.method = "SCT", 
                                verbose = T)

rm(AB.integrated.anchors)
gc()

```

`

**Comment by jaisonj708** [comment]
Using RPCA instead of the default CCA may resolve this issue. It is better at preserving variation within an isolated cell type (and variation between this isolated cell type and other cell types). Feel free to try various values for `k.anchor` (e.g, 5 (default), 10, 25) to see what produces the most reasonable result.
