### ISSUE TITLE
UpdateSymbolList via AddModuleScore search doesn't always return correct case

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#3413]
Hello,

I've noticed that when using search = TRUE for the AddModuleScore() function, UpdateSymbolList will return gene names that are in the object but they always seem to be returned as all-caps. Most mouse references use title case for gene names. The result is that the genes identified by the search option have to be added manually after changing the case. I was unable to find a case option to change this.

Thanks!

**Comment by mojaveazure** [comment]
As stated in the [documentation](https://rdrr.io/cran/Seurat/man/UpdateSymbolList.html), `UpdateSymbolList` searches the HUGO Gene Nomenclature Committee (HGNC) database for update gene symbols. The HGNC standard is to have gene symbols as all upper-case, so in this context, `UpdateSymbolList` is doing it's job correctly. At the moment, we don't support any other database, so for mouse genes, you'll have to update the gene symbols on your own. If you're okay with using HGNC names, then you can use [`CaseMatch`](https://rdrr.io/cran/Seurat/man/CaseMatch.html) to match the case between your updated symbol list and the names in your `Seurat` object prior to running `AddModuleScore`

```r
# Assume "genes" is a vector of gene symbols
genes <- UpdateSymbolList(genes)
genes <- CaseMatch(genes, match = rownames(object))
object <- AddModuleScore(object, features = genes, ...)
```
