### ISSUE TITLE
Why construct a SNN graph? / Help with JackStraw analysis 

### ISSUE THREAD

**Issue by Drosophilist** [satijalab/seurat#3416]
Hello Seurat team,

This is really an analysis question and not an issue. I have been wondering what is the advantage of constructing a SNN graph from the KNN before using the Louvain modularity optimization algorithm? Could we not perform the latter directly from the KNN? If you could give me some pointers or a paper to read about this I would be really grateful. I'm sorry if this is a really basic question. 

I would also really appreciate if you could help me understand the Jackstraw analysis. In the _'JackStrawData-class'_ , could you point to me where I can find the exact code to how the _'empirical.p.values'_ , _'fake.reduction.scores'_ , and _'overall.p.values'_ are calculated? What is the meaning of Theoretical [runif(1000)] in the jackstraw plot y axis?

**Update:** I have found the source code for calculating _'empirical.p.values'_ , _'fake.reduction.scores'_ , and _'overall.p.values'_ in https://github.com/cran/Seurat/blob/master/R/dimensional_reduction.R, but I am having a hard time understanding a few things:

**In JackRandom** - What is the purpose of _MatrixRowShuffle()_? I understand that it scrambles values in a matrix, but what is the consequence of doing this? 
Why is r2.use = 5 in _JackRandom()_, but in _Jackstraw()_ r2.use = dims
In the _JackRandom_ function will PCA only be calculated for 5 dimensions? or will this be overiden by the r2.use in _JackStraw()_ ? 

**In Jackstraw()** - How does the matrix _fake.val_ end up with the same number of features as the original PCA loadings matrix? What happens to the measures taken from the multiple replicates and how are they all fit into a single matrix?

In **ScoreJackStraw()** , I got a bit confused by the line of code of the proportion test used for the calculation of the overall p values. In the R documentation of _prop.test()_ the argument x, says "a vector of counts of successes, a one-dimensional table with two entries, or a two-dimensional table (or matrix) with 2 columns, giving the counts of successes and failures, respectively". I'm assuming in Seurat's code the "the counts of successes" is _length(x = which(x = pAll[, i] <= score.thresh))_ and the counts of failure is _floor(x = nrow(x = pAll) * score.thresh)_ . I understand the first, but why does multiplying the number of total genes by the score.thresh give us the number of failures?

**Lastly**, what are the null hypothesis for the statistical tests that generate the  _'empirical.p.values'_ and the _'overall.p.values'_ ?

I'm sorry for asking so many questions.

Cheers

**Comment by andrewwbutler** [comment]
Hi,

Yes, you could perform these graph based clustering methods directly on the KNN graph. One of the main advantages of constructing an SNN graph from the KNN is that SNN graphs tend to be more robust to noisy/spurious edges that can form with KNN graphs and the resulting clusters are generally more stable.

For the `JackStraw` questions, check out the supplemental info in [Macosko et al 2015](https://www.cell.com/fulltext/S0092-8674(15)00549-8#supplementaryMaterial) for more details/references but I'll try to answer some here.

**Re JackRandom**  `MatrixRowShuffle()` will randomly permute the values in the rows the matrix given. This is used to compute the empirical null distribution of scores. No, `r2.use=5` is only an internal default. It will always be overridden by the value from `JackStraw()`.

**Re JackStraw** the `fake.val` matrix will not have the same number of features as the original PCA loadings matrix. The rows of this matrix are the randomly sampled genes from each iteration and the columns are the PCs.

**Re ScoreJackStraw**  It's not the total number of failures, it's the expected number. We're in the first regime here of `prop.test`.
