### ISSUE TITLE
Seurat installation error

### ISSUE THREAD

**Issue by akshar371** [satijalab/seurat#3418]
When installing and loading Seurat, I get the following error:
```
library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in library.dynam(lib, package, package.lib):
 DLL ‘digest’ not found: maybe not installed for this architecture?
```
I tried to install 'digest' manually but receive a similar error.
```
library(digest)
Error: package ‘digest’ is not installed for 'arch = x64'
```

**Comment by mojaveazure** [comment]
There appears to be an issue with your installation of digest; I would suggest removing and reinstalling the digest package. If that fails, you should open an issue with [that package](https://github.com/eddelbuettel/digest).
