### ISSUE TITLE
Is there a way to combine samples other than 'merge' and how to crop out subclusters for further analysis?

### ISSUE THREAD

**Issue by Tousif-Azmain** [satijalab/seurat#3419]
Hi,
1. I have three samples that I have used to perform general QC. Next, I wanted to combine them and analyze them together. To do that, I have used 'merge' function. However, when I tried to scale the combined data I get ''Can not allocate vector of size xx mb''. I have tried with 2 samples and yet I ran out of memory. Is there any way to analyze more than one sample together without increasing the memory of my computer? I have already tried size.limit().
2. How can I analyze and generate a heatmap for subclusters/cell subtypes from a main cluster/cell type?  
Thank you in advance!

**Comment by nicodemus88** [comment]
Hi @Tousif-Azmain,
1) Please provide more information on your sample. How many cells are there per sample? I guess if it's really big, it would be impossible to do it on a normal laptop / PC, no? Would be better to do it on a cluster or server... 
2) Once you annotate the subcluster, you can just use subset the seurat object when doing the heatmap. 
`DoHeatmap(object = subset(so, subset = cluster == "ClusterA"))`

**Comment by RobertWhitener** [comment]
Tousif,

1.  I often would run into the Error after working in the same session for long periods of time, even with relatively small (<10,000 cells) datasets.  Not sure what exactly would cause it, but I found that completely terminating the R session and restarting would resolve the issue.  If you haven't tried that, I would give it a shot.
