### ISSUE TITLE
Error in FindClusters

### ISSUE THREAD

**Issue by tsofoon** [satijalab/seurat#342]
```R
> seurat.s1 <- FindClusters(object = seurat.s1, reduction.type = "pca", dims.use = 1:5, 
+                           resolution = 0.6, print.output = 0, save.SNN = TRUE)
Error in .Call("_Seurat_ComputeSNN", PACKAGE = "Seurat", nn_large, nn_ranked,  : 
  "_Seurat_ComputeSNN" not available for .Call() for package "Seurat"
```

What are the possible explanations for such error?

The error was not a java issue. Seurat 2.2.1 and R 3.4.3 were used.

**Comment by andrewwbutler** [comment]
It looks like you're using the development version. You can try the troubleshooting steps outlined [here](http://satijalab.org/seurat/devinstall.html) but I would generally recommend just using the latest CRAN version (via `install.packages`) for the most stable option.
