### ISSUE TITLE
Error when creating Seurat Object

### ISSUE THREAD

**Issue by rlu5027** [satijalab/seurat#3421]
Hi!

I have been running into an error when trying to use CreateSeuratObject. 
`so_prefilter   <- 
  Seurat::CreateSeuratObject(counts = raw_data,
    project = STUDYID, 
    min.cells = 3, 
    min.features = 100)`
`Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 'x' must be an array of at least two dimensions`

I created raw_data by running 
`raw_data <- 
  Seurat::Read10X(
    data.dir = "~/outs/filtered_feature_bc_matrix/"
   )`

I was not able to reproduce this error with a sample dateset, so I'm not sure if there might be a problem with my raw_data?

Thank you in advance for your help!

**Comment by mojaveazure** [comment]
The error is indicating that `raw_data` is not a matrix or matrix-like object. What is the output of the following?

```r
raw_data <- Seurat::Read10X( data.dir = "~/outs/filtered_feature_bc_matrix/" )
class(raw_data)
```

**Comment by rlu5027** [comment]
I ran those lines and got this output:
```r
> class(raw_data)
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"`
```

**Comment by andrewwbutler** [comment]
Hi,

Try either loading the `Matrix` package or `Seurat` with the `library` function first.

**Comment by rlu5027** [comment]
Hi,
I tried doing that, but I'm still getting the same error. I didn't get this error when using a sample data set provided by 10X Genomics. Could this error be caused by a failed cellranger aggr run?
Thanks!

**Comment by mojaveazure** [comment]
It could be, but is not something that we're able to diagnose without seeing the dataset. Could you share it with us either via a cloud hosting service or email it to us at phoffman@nygenome.org?

**Comment by jdime** [comment]
Hello @mojaveazure,

I'd like to follow-up / re-open this issue. I'm getting the same error with `CreateSeuratObject()` when the sample (mtx) to be loaded contains only one barcode in the barcodes.tsv.gz file.

I found [here](https://statisticsglobe.com/r-colsums-rowsums-error-must-be-array-two-dimensions) that this error is found when `colSums()` is called and the matrix has only one column, which is converted to a vector.

I'm wondering if this can be prevented modifying the Seurat code where this is used and where I can try to do that?

Thanks.

**Comment by eltonjrv** [comment]
Hello all,
Same here. Just getting  the same error on an apparently normal STARsolo output matrix.
ReadSTARSolo works fine, but then CreateSeuratObject doesn't, printing the same error message as above:
Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 'x' must be an array of at least two dimensions
Hope someone can shed a light.
Thanks

**Comment by jdime** [comment]
Hello @eltonjrv . Does your matrix also has only 1 cell?
If that's the case, a [suggestion from the Seurat developers](https://github.com/satijalab/seurat/issues/6621) was to merge it with other cells before trying to create the Seurat object. That's needed anyways for downstream steps, like finding anchors, etc, where working with 'samples' with only 1 cell wouldn't work. Indeed, I'm merging now any sample with <50 cells.

**Comment by eltonjrv** [comment]
Hi,
Thanks for your prompt attention.
No, it has actually thousands of cells. I think it must have something to do with the libraries being 10X v1 and maybe I kept some STARsolo parameters from v2, although the aligner finished successfully (generating the matrices) and the alignment rates are all over 70%.  I haven't experienced this CreateSeuratObject issue with any of either 10X v2 or SmartSeq STARsolo matrices that I generated.
I'll keep scrutinizing this, but please let me know if you come up with any ideas.
Thanks anyways,
Elton
