### ISSUE TITLE
Regress Cell Cycle Using SCtransform

### ISSUE THREAD

**Issue by cloitz2** [satijalab/seurat#3422]
Hello,

I'd like to regress out my cell cycling genes while performing SCtrans. I noticed that including var.to.regress into the SCtransform function did not work (I tried to do vars.to.regress = "CC.Difference" and vars.to.regress = c("S.Score", "G2M.Score"), if you could comment on why this can't be done using the SCtransform function I'd really appreciate it. Meanwhile I tried regressing out the cell cycle genes by using the PCA function and I also noticed that I could get the SCtransform function to regress out the cell cycling genes if I performed the regression after I had already done SCtrans once (so basically I did the SCtrans function twice). I'm worried though that both ways may not be correct. Also will regressing out the cell cycling genes using PCA not remove cell cycling genes from the RNA assay (If I'm not wrong I thought the data from the PCA function was only used for UMAPS etc)? If you could comment I'd also appreciate this as well! Below is the code for each of the above described methods. Thank you!

First method 
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

CE.data = Read10X(data.dir = "~/R/Datasets/CE/outs/filtered_feature_bc_matrix/")

CE <- CreateSeuratObject(counts = CE.data, project = "10X_wtCE")

CE[["percent.mt"]] <- PercentageFeatureSet(CE, pattern = "^MT-")

CE <- subset(x = CE, subset = nFeature_RNA > 2500 & percent.mt < 15)

CE <- SCTransform(CE, verbose = FALSE)

CE <- CellCycleScoring(object = CE, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
CE$CC.Difference <- CE$S.Score-CE$G2M.Score

CE <- RunPCA(object = CE, vars.to.regress="CC.Difference", verbose = FALSE)

Second method:
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

CE.data = Read10X(data.dir = "~/R/Datasets/CE/outs/filtered_feature_bc_matrix/")

CE <- CreateSeuratObject(counts = CE.data, project = "10X_wtCE")

CE[["percent.mt"]] <- PercentageFeatureSet(CE, pattern = "^MT-")

CE <- subset(x = CE, subset = nFeature_RNA > 2500 & percent.mt < 15)

CE <- SCTransform(CE, verbose = TRUE)

CE <- CellCycleScoring(object = CE, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
CE$CC.Difference <- CE$S.Score-CE$G2M.Score

CE = SCTransform(CE, vars.to.regress = "CC.Difference", verbose = TRUE)
CE = RunPCA(object = CE, verbose = TRUE)

**Comment by timoast** [comment]
> I noticed that including var.to.regress into the SCtransform function did not work 

In what way did it not work? Does it cause an error? If so, what is the error?

**Comment by cloitz2** [comment]
Hi timoast,

I apologize, I think I realized it is my dataset causing the issue. Hopefully, you'll still help me. I think the error is occurring because there are not enough cell cycling genes in my dataset? But this is strange because when I look at the markers for the clusters a bunch of cell cycling markers pop out...Below is my workflow.

Thank you!

Basically, I ran the code below and first I got an error when trying to do cell cycle scoring and then CC.Difference:

Warning: The following features are not present in the object: MLF1IP, not searching for symbol synonyms
Warning: The following features are not present in the object: FAM64A, HN1, not searching for symbol synonyms
Error: Insufficient data values to produce 24 bins.
Run `rlang::last_error()` to see where the error occurred.
> CE$CC.Difference <- CE$S.Score-CE$G2M.Score
Error: Cannot find 'S.Score' in this Seurat object

Then for ScTrans I get this error:

problem with second non-regularized linear regression; not all variables found in seurat object meta data; check vars.to.regress parameter



Code/workflow:
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

CE.data = Read10X(data.dir = "~/R/Datasets/CE/outs/filtered_feature_bc_matrix/")

CE <- CreateSeuratObject(counts = CE.data, project = "10X_wtCE")

CE[["percent.mt"]] <- PercentageFeatureSet(CE, pattern = "^MT-")

CE <- subset(x = CE, subset = nFeature_RNA > 2500 & percent.mt < 15)

CE <- CellCycleScoring(object = CE, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
CE$CC.Difference <- CE$S.Score-CE$G2M.Score

CE <- SCTransform(CE, vars.to.regress = "CC.Difference", verbose = FALSE)

rlang::last_trace()

**Comment by timoast** [comment]
The reason for this is that CellCycleScoring failed because you don't have enough of the cell cycle genes present in the dataset, and so there is no cell cycle score information in the object, and CC.Difference does not exist in the metadata. This should be solved by identifying the correct set of cell cycle genes for your dataset.
