### ISSUE TITLE
How do you match the standard Seurat object with the Seurat object from Velocyto?

### ISSUE THREAD

**Issue by BeyondMyPast228** [satijalab/seurat#3423]
Hi,
Thanks for developing this user-friendly tool . 
I have **two Seurat objects** from the same 10X data. One is the standard Seurat object after the Seurat normal process analysis, which contains the quality-controlled cells and cell type annotations. The other is the Seurat objects that come through **as. Seurat** after running Velocyto(RNA velocity analysis).   
Because **after Velocyto's processing**, the mRNA is divided into spliced and unspliced(There are some changes in the genes), and **an accurate annotation of the cell type cannot be made**. However,  the overall composition of the cell group is the same as before(**that means the cells are identical to the ones coming out of the 10X CellRanger pipeline**). Meanwhile, since the first Seurat object is accurately annotated, how do I match the second seurat object with the first one?(ps : Due to changes in genes and UMI, the filtering criteria for the first Seurat object are not applicable for the second Seurat object)
In additon : the origin data after velocyto processing,  the second Seurat object is given the same prefix and suffix, as shown in the figure below.
The first Seurat object: [
![image](https://user-images.githubusercontent.com/67768651/91288149-390cca80-e7c3-11ea-80a6-aeb64d39c478.png)
](url)
colnames(first object) : [
![image](https://user-images.githubusercontent.com/67768651/91288255-5f326a80-e7c3-11ea-95bb-0060e9a6bbe2.png)
](url)
The second seurat object: [
![image](https://user-images.githubusercontent.com/67768651/91288013-0d89e000-e7c3-11ea-88f8-daa50cdf24f1.png)
](url)
colnames(second object): [
![image](https://user-images.githubusercontent.com/67768651/91288382-82f5b080-e7c3-11ea-8225-5669ec0e2bdc.png)
](url)

I sincerely hope to get your kind reply.

**Comment by BeyondMyPast228** [comment]
In addition, the number of cells in the two seurat objects is the same before filtering.My goal is to expect the second seurat object to match the first seurat object (so I can annotate the latter exactly)

**Comment by mojaveazure** [comment]
Generally speaking, you can match and merge two `Seurat` objects as long as the cell names are the same. In your case, you would have to harmonize the cell names between the `Seurat` objects, then merge them together. The velocyto-processed data would exist in the `spliced` and `unspliced` assays, while the Seurat-processed data would exist in the `RNA` assay. However, you can also treat the `spliced` assay as a standard `RNA` assay, and after processing your data with velocyto, simply run Seurat's workflow on the `spliced` assay (see the [Estimating RNA Velocity using Seurat](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/velocity.html) and [Estimating RNA Velocity using Seurat and scVelo](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html) community vignettes for examples)
