### ISSUE TITLE
TCR and hash tag oligo analysis

### ISSUE THREAD

**Issue by clairebio27** [satijalab/seurat#3424]
I have performed a hash tag oligonucleotide sequencing for TCR data. I am having ADT (HTO),and TCR fastqs from 10 X and illumina.
I am new to this analysis, and any help to see how can I perform the HTO demux to these samples. I went through the tutorial for the same 
https://satijalab.org/seurat/v3.0/hashing_vignette.html

But in my case I dont have the RNA UMI count, so how can I replace that part?  how can i get the TCRs information after retrieving the tag quantification?

Any help is appreciated 
Claire

**Comment by timoast** [comment]
You can run HTO demux without RNA information, you will need to follow the vignette except creating the Seurat object using the HTO counts rather than RNA expression counts
