### ISSUE TITLE
Gene_symbol / Gene_id 

### ISSUE THREAD

**Issue by golharam** [satijalab/seurat#3426]
Situation
We are encountering an issue where the the features loaded in Seurat do not match the features from 10X raw counts after Seurat normalization.

Background
10X filtered raw counts features.tsv contains three columns: gene_id, gene_symbol, "Gene Expression".  

There are two ways we can load & normalize this data, by gene_symbol or gene_id:

1.  Gene_Symbol

We load the data using Read10X(data.dir=...) which then uses column two (gene_symbol) as the features.  We then normalize with:
PercentageFeatureSet(scRNAseq.data, pattern = "^MT-", col.name = "percent.mt")
SCTransform(...)

We then write out the seurat features, barcodes and matrix to text files that match the 10X format.  The features.tsv in this case has 3 columns: adjusted_gene_symbol, adjusted_gene_symbol, "Gene Expression"

This works as expected, however the resulting Seurat object contains 3 new genes there were not present in the 10X filtered counts output.  They are TBCE.1, MATR3.1, HSPA14.1.

This is because those genes each appear twice (there are two gene_ids for each symbol).  The original symbols are TBCE, MATR3, HSPA14.

2. The other way to load/normalize the data is by gene_id.  

We load the data using Read10X(data.dir=..., gene.column=1) which then uses column one (gene_id) as the features.  We then normalize with:

scRNAseq.data.gene_id <- CreateSeuratObject(counts=Read10X(data.dir=INPUT.PATH, gene.column=1))

Get the Mito genes and apply sctransform
mt_pattern <- "^MT-"
features <- read.delim(paste0(INPUT.PATH, "/features.tsv.gz"), header=FALSE)
mito.features <- features[grep(mt_pattern, features$V2), ]
mito.features <- as.vector(mito.features$V1)

scRNAseq.data.gene_id <- PercentageFeatureSet(scRNAseq.data.gene_id, features = mito.features, col.name = "percent.mt")
scRNAseq.data.gene_id <- SCTransform(scRNAseq.data.gene_id, vars.to.regress = "percent.mt", verbose = FALSE, return.only.var.genes = FALSE, conserve.memory = TRUE)

This also works as expected and the features stay the same.  We then write out the seurat features, barcodes and matrix to text files that match the 10X format.  The features.tsv in this case has 3 columns: gene_id, gene_id, "Gene Expression"

Assessment

When we use the normalized output by gene_symbol, this poses the problem that the gene_symbol has been changed and not in line with other annotation sources that also have the gene_symbol (e.g. TBCE.1 is not the same as TBCE).

The resulting features file has to be corrected to contain gene_id, gene_symbol, and "Gene Expression".  While this is fine an all, we find ourselves having to normalize two datasets.  Once with gene_id to get the correct output, and once by gene_symbol so that we can continue downstream analysis by gene_symbol.

Recommendation

Can Seurat maintain both gene_id and gene_symbol from 10X and/or not adjust the gene_symbol name when there are duplicates?  Ideally, we'd like to maintain both gene_id and gene_symbol in the end.

**Comment by mojaveazure** [comment]
R requires that rownames of data frames and matrices are unique. If you have duplicate rownames (feature names), you get the modification `.number` automatically on the R-level. This is an unavoidable side-effect of using R for analyses. If you want to keep the gene symbols in the `Seurat` object, you can add it to feature-level metadata; see https://github.com/satijalab/seurat/issues/2855#issuecomment-614733444 for more details

**Comment by Kedde92** [comment]
Hello @golharam 

Could you mabye explain to me how you correct your feature files to contain both Gene_symbols and Gene_names, when you run your Seurat using gene_ids? I am performning scRNAseq on Zebrafish cardiomyctes and get variating results depeing on rather I run Seurat using Gene_ids or Gene_names, due to the reason you so greatly described above. I have therefor chosen to run Seurat using Gene_ids, but i need the gene_symbols for downstream analysis. 

/Kristian
