### ISSUE TITLE
Labeling Samples

### ISSUE THREAD

**Issue by tyang39** [satijalab/seurat#3427]
Hello,

I have 3 different samples of the same tissue and I am wondering how I could label the different clusters on the TSNE plot with which samples they came from? Thank you.

**Comment by nicodemus88** [comment]
Hi @tyang39,
If you have a column in the metadata which specifies which cells comes from which sample, just group the clusters by that column using `group.by`.

`tsnePlot <- DimPlot(so, group.by = "orig.sample")`

If not, you need to prepare a column in the metadata which provides that information.
