### ISSUE TITLE
Differential Expression Not Returning All Genes

### ISSUE THREAD

**Issue by lothm2014** [satijalab/seurat#3428]
Hello, 

I am running differential expression using the FindMarkers function. I would like to return all the genes that are in the original counts matrix. My attempt to include all genes is the following:
```
A431DeResults<- FindMarkers(seuratObject2, ident.1 = 0, ident.2 = 2, logfc.threshold=0,  min.pct=0, 
min.diff.pct=0, thresh.test=0)
```
The result includes 16,171 genes, but there are ~26,000 genes in the counts matrix. How can I get results that include all of the genes?

**Comment by nicodemus88** [comment]
Hi @lothm2014,
Try changing some of the parameters as below:

`degRes <- FindMarkers(object = so, ident.1 = "Tx", ident.2 = "Ctrl", min.pct = -Inf, logfc.threshold = -Inf, min.cells.feature = 1, min.cells.group = 1)`

**Comment by xiaokang8002** [comment]
> 
> 
> Hi @lothm2014,
> Try changing some of the parameters as below:
> 
> `degRes <- FindMarkers(object = so, ident.1 = "Tx", ident.2 = "Ctrl", min.pct = -Inf, logfc.threshold = -Inf, min.cells.feature = 1, min.cells.group = 1)`

df <- FindMarkers(object, ident.1 = "cluster 12", ident.2 = "cluster 12", verbose = FALSE, logfc.threshold = -Inf,
                    min.pct = -Inf,min.cells.feature = 0,min.cells.group = 0)
I used the above code. the "object" had 23407 features. Why the "df" just had 2000 features?
Thanks a lot!

**Comment by nicodemus88** [comment]
Because the differential expression is performed on the original assay, while the `df` has only the number of variable features you used.

**Comment by xiaokang8002** [comment]
> 
> 
> Because the differential expression is performed on the original assay, while the `df` has only the number of variable features you used.

Hi nicodemus88,
Thanks for you prompt comment.
TLH.list <- lapply(X = TLH.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
Was it due to "nfeatures = 2000" in the above code?
Or could you tell me how to let "df" had all the genes of "object"?
Thanks!

**Comment by nicodemus88** [comment]
@xiaokang8002, 
Your data has all the genes (23,407 features), it's only that you have a subset of it as variable features, in this case 2000 features, which is used to perform dimensional reduction. 
When plotting or performing differential expression tests, the original assay (the `data` slot in `RNA` assay) is used so all genes are included.
