### ISSUE TITLE
Inquiry about the Featureplot for the genes which are not in the active integrated assay

### ISSUE THREAD

**Issue by pekjoonwu** [satijalab/seurat#3429]
Hi Seurat Team,

Thanks first for developing this amazing tool!

I had a integrated dataset which contained 9 samples and I just followed the guide to build the integrated dataset (So I had 2000 significant genes for it).  I have a question about the Featureplot. For the genes that are not in this 2000 significant gene list, how should I infer their integrated gene expression data so that I can plot the integrated gene expression pattern for these genes instead of plotting the count in the 'RNA' assay?

Thank you so much for the help!

**Comment by jaisonj708** [comment]
You can re-run integration and specify which features you'd like in the `features.to.integrate` parameter of `IntegrateData`
