### ISSUE TITLE
A question about FindMarekers（p_val_adj）

### ISSUE THREAD

**Issue by BeyondMyPast228** [satijalab/seurat#3430]
Hi，
Thanks for developing this tool. I have a question about P_val_adj after function **FindMarkers**. I found that some **p_val_adj** has a value of 1, does that mean this gene is not a differential gene. The specific schematic diagram is shown below:
[
![image](https://user-images.githubusercontent.com/67768651/91375481-67cf8300-e84d-11ea-9c71-f04097f90504.png)
](url)
I sincerely hope to get your reply.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully this can be helpful.  Yes the p adjusted values from `FindMarkers` are calculated using Bonferroni and a p adjusted value of 1 is not significant.  Not all of the genes returned by FindMarkers are significantly differentially expressed.  It is up to end user to decide on log fold change and p adjust value thresholds for their own work.  However, p adjusted value of 1 is definitely not significant.

Best,
Sam

**Comment by BeyondMyPast228** [comment]
@samuel-marsh Hi,thanks for your kind reply. Your answer settles my question.
