### ISSUE TITLE
how to read data from smart-seq2?

### ISSUE THREAD

**Issue by tanpuekai** [satijalab/seurat#3431]
hi,

went thru your wiki and your vignette page (https://satijalab.org/seurat/vignettes.html) but could not find a page that describes how to load data of various non-10x platforms into creating objects.

Pls advise on where to find such instructions.

Best
Chan

**Comment by samuel-marsh** [comment]
Hi Chan,

This question has been answered a couple times in github issues (see #1769 and others).  The `CreateSeuratObject` command requires either sparse of dense matrix where cells are columns and genes are rows but is not dependent on 10X data.  You should be able to read your data into R using the appropriate command for the type of data and then as long as cell names and gene names are part of that matrix, simply provide that environmental variable to `CreateSeuratObject`.

Basic example:
```
raw_data <- read.table("/path/to/file.tsv")
object <- CreateSeuratObject(counts = raw_data, ...)
```

Best,
Sam

**Comment by tanpuekai** [comment]
> Hi Chan,
> 
> This question has been answered a couple times in github issues (see #1769 and others). The `CreateSeuratObject` command requires either sparse of dense matrix where cells are columns and genes are rows but is not dependent on 10X data. You should be able to read your data into R using the appropriate command for the type of data and then as long as cell names and gene names are part of that matrix, simply provide that environmental variable to `CreateSeuratObject`.
> 
> Basic example:
> 
> ```
> raw_data <- read.table("/path/to/file.tsv")
> object <- CreateSeuratObject(counts = raw_data, ...)
> ```
> 
> Best,
> Sam

Thanks so much Sam.
Hope they can spell this out in the Wiki.
Coz other than loading data into the object, we also need to know that for smartseq2 only counts, but not FPKM were accepted, correct?

(sorry i googled several times but could not locate github issues on this.)

Chan

**Comment by mojaveazure** [comment]
As Sam said, all you need to create a `Seurat` object is a matrix of counts with cells as columns and features as rows. This is specified in the [help page](https://rdrr.io/cran/Seurat/man/CreateSeuratObject.html) for `CreateSeuratObject`

**Comment by erzakiev** [comment]
Is the sequencing depth normalization (e.g. `Seurat::NormalizeData`) step the same for SS2 data as for the 10x data?
