### ISSUE TITLE
ReadH5AD from a scvelo pipeline- no dimension reduction data imported

### ISSUE THREAD

**Issue by shambam** [satijalab/seurat#3433]
First up, I'm not a heavy Python/Scanpy user. I have data that I ran through scanpy/scvelo, and the source of the reads was from a "loompy fromfq" call. My adata looks like this after running everything:

>>> adata
AnnData object with n_obs × n_vars = 141723 × 2000 
    obs: 'TotalUMIs', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'n_genes', 'n_counts', 'velocity_self_transition', 'louvain'
    var: 'Accession', 'AccessionVersion', 'Aliases', 'CcdsID', 'Chromosome', 'ChromosomeEnd', 'ChromosomeStart', 'CosmicID', 'DnaBindingDomain', 'FullName', 'GeneType', 'HgncID', 'IsTF', 'Location', 'LocationSortable', 'LocusGroup', 'LocusType', 'MgdID', 'MirBaseID', 'OmimID', 'PubmedID', 'RefseqID', 'RgdID', 'UcscID', 'UniprotID', 'VegaID', 'means', 'dispersions', 'dispersions_norm', 'velocity_gamma', 'velocity_r2', 'velocity_genes'
    uns: 'louvain', 'neighbors', 'pca', 'velocity_graph', 'velocity_graph_neg', 'velocity_settings'
    obsm: 'X_pca', 'X_phate', 'X_umap', 'velocity_phate', 'velocity_umap'
    varm: 'PCs'
    layers: 'Ms', 'Mu', 'spliced', 'unspliced', 'velocity'

>>> adata.X
<141723x2000 sparse matrix of type '<class 'numpy.float32'>'
	with 29329393 stored elements in Compressed Sparse Row format>
>>> adata.raw
>>> 

My adata.X is populated, but adata.raw isn't (from what I gather). If I write this adata out to h5ad and try to read it into Seurat I get the following:

bm2<- ReadH5AD("adata.h5ad")

Pulling expression matrices and metadata
Data is unscaled
Merging feature-level metadata dataframes
Creating assay object
Storing X as data and raw as counts
No variable feature expression found in h5ad file
No dimensional reduction information found
Assembling Seurat object
No nearest-neighbor graph
Reading Ms into new assay, putting data into data
Reading Mu into new assay, putting data into data
Reading spliced into new assay, putting data into data
Reading unspliced into new assay, putting data into data
Reading velocity into new assay, putting data into data

As you can see it will not pull in the umap/phate/velocity_phate/velocity_umap data because according to the docs, adata.X is sparse and adata.raw is not filled.

My question is whether it is possible to force ReadH5AD to import this data anyway, and if not, whether this could be implemented in the future? The only workaround I had was to use ReadH5AD, and then use h5file to connect to the same h5ad file to extract and manually fill in the rest.

Any pointers welcome, and thanks.

**Comment by mojaveazure** [comment]
Hi,

We are transitioning our support for AnnData/H5AD files to [SeuratDisk](https://github.com/mojaveazure/seurat-disk), our new package for interfacing `Seurat` objects with single-cell HDF5-based file formats. We would very much like it if you could give this a shot for reading in your data.

You can install SeuratDisk with the following:
```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")
```

A tutorial on how to read in AnnData/H5AD files via the h5Seurat intermediate can be found [here](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html). Greater detail about the new `Convert` mechanism can be found [here](https://mojaveazure.github.io/seurat-disk/reference/Convert.html)

If you come across any bugs in reading in your HDF5 files, please post them in mojaveazure/seurat-disk#1. Please note, there are some stipulations about the format of your AnnData/H5AD posted in https://github.com/mojaveazure/seurat-disk/issues/1#issue-619215532
