### ISSUE TITLE
merging two datasets normalized using different scale factors

### ISSUE THREAD

**Issue by chriscda** [satijalab/seurat#3434]
I am trying to merge two datasets that used different scale factors. dataset1 was a matix labeled as TPM normalized. dataset2 was a matix of raw counts and I did log normalization using Seurat. Now I would like to merge these two. I suppose I should not just ignore their difference in the normalization step. What should I do before merging? Thanks!

**Comment by jaisonj708** [comment]
Ideally both are normalized the same way. If you have access to the raw counts for dataset1, I would suggest log-normalizing raw datasets 1+2. If not, you can TPM normalize raw counts for dataset2 (if you have raw reads). You can always use different normalization methods, but this may result in unexpected dataset-specific effects, especially if you only log one of the two datasets
