### ISSUE TITLE
Error during NormalizeData(): Attempting to add a different number of cells and/or features

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#3435]
I created a seurat object using the count matrix from my seurat object. However, I encountered an error during normalization. Could you please help me?
```
> sm <- read.csv(file = 'Spring-counts.csv', sep = '.', header = F)
> sm<-sm[,-1]
> nrow(sm)
[1] 1000
> ncol(sm)
[1] 9790
> Patient.object <- CreateSeuratObject(counts = sm, min.cells = 0)
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion
> Patient.object
An object of class Seurat 
1000 features across 9790 samples within 1 assay 
Active assay: RNA (1000 features, 0 variable features)
> Patient.object <- NormalizeData(Patient.object)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Attempting to add a different number of cells and/or features
```

**Comment by timoast** [comment]
This might be related to the warning about NAs being introduced. Can you show the first few entries of the `sm` matrix, and also what values are being converted to NA?

for example:

```r
sm[1:10,1:10]
sm.mat <- as.matrix(sm)
sm[[which(is.na(sm.mat))]]
```

**Comment by federicaress** [comment]
Hi everyone! I encountered the same problem, but I do not have any values converted to NA into my object.  What could I do to solve this issue? 
Thanks in advance!

**Comment by grimwoo** [comment]
@timoast 
Thanks for your early reply! I checked the matrix before saving and after reading, but I still got this error.
```
> matrix<-Our.object@assays$RNA@scale.data
> for (i in 1:nrow(matrix)) {
+     for (j in 1:ncol(matrix)) {
+         if (is.na(matrix[i,j])) {
+             print(paste('i:',i,', j:',j))
+             matrix[i,j]<-0
+         } else {
+             if (matrix[i,j]=='NA') {
+                 print(paste('i:',i,', j:',j))
+                 matrix[i,j]<-0
+             }
+         }
+     }
+ }
> 
#No NA was found in this matrix.
> write.table(x = matrix,file = 'Spring-counts.csv',row.names = F,col.names = F, sep = ",")
> matrix <- read.csv(file = 'Spring-counts.csv', sep = ',', header = F)
> matrix<-matrix[,-1]
> for (i in 1:nrow(matrix)) {
+     for (j in 1:ncol(matrix)) {
+         if (is.na(matrix[i,j])) {
+             print(paste('i:',i,', j:',j))
+             matrix[i,j]<-0
+         } else {
+             if (matrix[i,j]=='NA') {
+                 print(paste('i:',i,', j:',j))
+                 matrix[i,j]<-0
+             }
+         }
+     }
+ }
> Patient.object <- CreateSeuratObject(counts = matrix, min.cells = 0)
> Patient.object <- NormalizeData(Patient.object)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Attempting to add a different number of cells and/or features

**Comment by timoast** [comment]
@grimwoo please run the lines I posted above and show the output here

**Comment by grimwoo** [comment]
@timoast Thanks:

```
> sm[1:10,1:10]
   V1 V2 V3 V4 V5        V6 V7 V8       V9 V10
1   0  0  0  0  0 0.0000000  0  0 0.000000   0
2   0  0  0  0  0 0.0000000  0  0 0.000000   0
3   0  0  0  0  0 0.8611727  0  0 1.065229   0
4   0  0  0  0  0 0.0000000  0  0 0.000000   0
5   0  0  0  0  0 0.0000000  0  0 0.000000   0
6   0  0  0  0  0 0.0000000  0  0 0.000000   0
7   0  0  0  0  0 0.0000000  0  0 0.000000   0
8   0  0  0  0  0 0.0000000  0  0 0.000000   0
9   0  0  0  0  0 0.0000000  0  0 0.000000   0
10  0  0  0  0  0 0.0000000  0  0 0.000000   0
> sm.mat <- as.matrix(sm)
> sm[[which(is.na(sm.mat))]]
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```

**Comment by timoast** [comment]
This might be related to having no row names in the matrix. Can you set the rownames and see if that fixes the issue?

**Comment by grimwoo** [comment]
@timoast Thanks. I randomly named the row name of this matrix and the NormalizeData() function ran successfully!

**Comment by chenx9** [comment]
> I created a seurat object using the count matrix from my seurat object. However, I encountered an error during normalization. Could you please help me?
> 
> ```
> > sm <- read.csv(file = 'Spring-counts.csv', sep = '.', header = F)
> > sm<-sm[,-1]
> > nrow(sm)
> [1] 1000
> > ncol(sm)
> [1] 9790
> > Patient.object <- CreateSeuratObject(counts = sm, min.cells = 0)
> Warning message:
> In storage.mode(from) <- "double" : NAs introduced by coercion
> > Patient.object
> An object of class Seurat 
> 1000 features across 9790 samples within 1 assay 
> Active assay: RNA (1000 features, 0 variable features)
> > Patient.object <- NormalizeData(Patient.object)
> Performing log-normalization
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Error: Attempting to add a different number of cells and/or features
> ```

I GOT THE SAME ERROW
and here is my data
<img width="214" alt="1661610689676" src="https://user-images.githubusercontent.com/81292404/187034740-04544ee8-de97-4e90-856b-e656955ae1c7.png">
