### ISSUE TITLE
integrated different features matrix

### ISSUE THREAD

**Issue by skytguuu** [satijalab/seurat#3436]
Hi,

Recently, I am trying to integrated two datasets, but I met a problem that each dataset has different features (one is 22080, another is 22097).  When I try to integrate those two datasets, it reported an error:
###########################
Error: Object 1 assay - RNA has not been processed by PrepSCTIntegration. Please run PrepSCTIntegration prior to FindIntegrationAnchors if using assays generated by SCTransform.
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
###########################
my code is as followed:

################
ref.features <- SelectIntegrationFeatures(object.list = reference.list, nfeatures = 3000)
u1 <- FindIntegrationAnchors(object.list = reference.list, normalization.method = "SCT",anchor.features = ref.features, verbose = FALSE)
##############
Any help?

**Comment by mojaveazure** [comment]
>  Error: Object 1 assay - RNA has not been processed by PrepSCTIntegration. Please run PrepSCTIntegration prior to FindIntegrationAnchors if using assays generated by SCTransform.

You need to process all of your datasets with `SCTransform` and prepare them for SCT-based integration with `PrepSCTIntegration`if you want to use `normalization.method = "SCT"`; if you don't want to do this workflow, you can follow the "Standard Worflow" described in the [integration vignette](https://satijalab.org/seurat/v3.2/integration.html).
