### ISSUE TITLE
Where does ScaleData put results?

### ISSUE THREAD

**Issue by cebriggs7135** [satijalab/seurat#3438]
The tutorial (https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html) says:

_**pbmc <- ScaleData(pbmc, features = all.genes)
"The results of this are stored in pbmc[["RNA"]]@scale.data".**_

No matter what I do, I cannot seem to find the scaled data. Maybe I misunderstand what [["RNA"]] does. Is it creating a column named "RNA" or populating a column already there named "RNA"?
How do I view or extract that data? The command cheat sheet doesn't help me with this.

Also, this message saying there's no slot named scale.data is very confusing. There is a slot named scale.data, correct?:

_> head(pbmc@scale.data)
**Error in head(pbmc@scale.data) : 
  no slot of name "scale.data" for this object of class "Seurat"**_

(note: I'm self-taught in R)

**Comment by mojaveazure** [comment]
You can use `GetAssayData` to get the results of `ScaleData` by passing `slot = "scale.data"`; we encourage the use of data accessors over directly accessing data slots in the object.

```r
GetAssayData(pbmc, slot = "scale.data")
```

**Comment by cebriggs7135** [comment]
thanks.
