### ISSUE TITLE
RNA assay - no biological sense in Drosophila

### ISSUE THREAD

**Issue by Marlo442** [satijalab/seurat#3439]
Dear Prof Satija, 

As you recommend, I use the RNA assay to find differential expressed genes. Unfortunately, the differential expressed genes do not make biological sense in the RNA assay (I scale the data, find the variable features and normalize). When I perform differential expression on the integrated assay (I have 2 datasets per condition) it does make biological sense. 

Is this because I use the model organism Drosophila which has smaller/different cells? (and the parameters are set for human?)
Or is there another reason? And which assay should I trust now?

Thanks in advance! :)

**Comment by jaisonj708** [comment]
The differential expression results from RNA might be crowded with technical batch effects. It is fine to use the integrated assay if it is giving you more reasonable results

**Comment by Marlo442** [comment]
Thank you very much for this suggestion. Unfortunately, adding batch to latent.vars in findMarkers doesn't change much. 
Could you think of another reason? 

I noticed that between the datasets (Control and Stimulated) the amount of cells per cluster sometimes differs much.
Could this be the problem? That I see certain DE because certain clusters contain more cells in the stimulated condition?
