### ISSUE TITLE
Error in RidgePlot

### ISSUE THREAD

**Issue by baolichang** [satijalab/seurat#344]
Hi, I would like to make a ridge plot after running CellCycleScoring, but got the error:

```R
> RidgePlot(object = JY2_Ulf, features.plot = c("PCNA", "TOP2A", "MCM6", "MKI67"), 
+     nCol = 2)
Error in RidgePlot(object = JY2_Ulf, features.plot = c("PCNA", "TOP2A",  : 
  could not find function "RidgePlot"
```

How can I solve the issue? Thank you!

**Comment by andrewwbutler** [comment]
Hi,

To use RidgePlot, you'll need to update to a recent version of Seurat (v2.2.1).
