### ISSUE TITLE
Remove node labels on PlotClusterTree

### ISSUE THREAD

**Issue by jwiarda** [satijalab/seurat#3440]
Is there a way to remove the node labels from the phylogenetic tree produced through running BuildClusterTree() followed by PlotClusterTree() ? Supposedly you can pass additional arguments from plot.phylo into PlotClusterTree(); however, when you pass in the argument show.node.label = FALSE, the nodes still appear.

Example code: 

seuratobject <- BuildClusterTree(seuratobject, dims = 1:20, assay = 'PCA')
PlotClusterTree(seuratobject, show.node.label = FALSE)

![plot_zoom_png (1)](https://user-images.githubusercontent.com/52429136/91616247-ef4eec00-e94a-11ea-8fd4-59c65dd6f6dd.png)

**Comment by massisnascimento** [comment]
Running into the same issue

**Comment by andrewwbutler** [comment]
`PlotClusterTree` will always display the internal node labels currently. Here is a workaround though.

```R
# pull the tree
data.tree <- Tool(object = seuratobject, slot = "BuildClusterTree")
# plot the tree
ape::plot.phylo(x = data.tree, direction = "downwards")
```

**Comment by aubreyghoward** [comment]
After following this example, it is no longer possible to turn on the node labels after the tool command has been called. please advise

**Comment by JoanJong** [comment]
You could use `ape::nodelabels`:

`# pull the tree
data.tree <- Tool(object = seuratobject, slot = "BuildClusterTree")
# plot the tree
ape::plot.phylo(x = data.tree, direction = "downwards")
ape::nodelabels(frame = "circle)`
