### ISSUE TITLE
kill 9 installation error, no minconda or anaconda installed 

### ISSUE THREAD

**Issue by msherafatian** [satijalab/seurat#3443]
I have issue installing the development version of Seurat package. I also have the same issue installing Seurat wrappers. these are the errors I get from them:

@@@@development version of Seurat package:

*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 80121 Done echo 'tools:::.install_packages()'
80122 Killed: 9 | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Error: Failed to install 'Seurat' from GitHub:
(converted from warning) installation of package ‘/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T//RtmpMsHM2Z/file12e9fdfe7eab/Seurat_3.2.0.9019.tar.gz’ had non-zero exit status

@@@@seurat wrappers

Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo satijalab/seurat-wrappers@HEAD
✓ checking for file ‘/private/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T/RtmpAIl0pB/remotes717b1bae243e/satijalab-seurat-wrappers-1a025ad/DESCRIPTION’ ...
─ preparing ‘SeuratWrappers’:
✓ checking DESCRIPTION meta-information ...
─ checking for LF line-endings in source and make files and shell scripts
─ checking for empty or unneeded directories
─ building ‘SeuratWrappers_0.2.0.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'
Warning: invalid gid value replaced by that for user 'nobody'

installing source package ‘SeuratWrappers’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
sh: line 1: 29819 Killed: 9 R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T//RtmpfZCvaZ/file74744c823c9b'
ERROR: lazy loading failed for package ‘SeuratWrappers’
removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/SeuratWrappers’
Error: Failed to install 'SeuratWrappers' from GitHub:
(converted from warning) installation of package ‘/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T//RtmpAIl0pB/file717b684eab93/SeuratWrappers_0.2.0.tar.gz’ had non-zero exit status

I have no version of miniconda or anaconda installed on my mac.

**Comment by mojaveazure** [comment]
Hi Masih,

This is a difficult one to debug. Can you try from a fresh R session with no packages or objects loaded? Also, can you try running the installation from the terminal instead of RStudio? Finally, what is the output of `sessionInfo()`?
