### ISSUE TITLE
to to run RunPCA without ScaleData?

### ISSUE THREAD

**Issue by hsun-sudo** [satijalab/seurat#3444]
Dear Seurat group:

I normalized the matrix:
1) for each cell, use log CPM to normalize;
2) for each gene use zscore to normalize.
mydata_new_variant contains the top variant genes.

mydata_PCA<-RunPCA(mydata_log_zscore_clean,features=rownames(mydata_new_variant))

 then I RunPCA it show error: Error: no slot of name "scale.data" for this object of class "Seurat".  Is there any methods to skip this step?

Thanks very much.

**Comment by hsun-sudo** [comment]
The seurat version is 3.1.5

**Comment by andrewwbutler** [comment]
Hi,

`RunPCA` when called on a Seurat object operates on the `scale.data` slot of the assay. If you are going to use your own methods for normalization and scaling, you need to fill this matrix. You can use the function `SetAssayData` to do so. E.g.

```R
object <- SetAssayData(object, assay = assay, slot = "scale.data", new.data = zscored_data_matrix)
```
