### ISSUE TITLE
How I can describe ridgeplot?

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3445]
Hello,

I have a ridgeplot plot. How I can describe it?
The distribution of the expression level, the peak, or the outlier?

Thank you in advances for great help!

Best,

Yue
![Screenshot from 2020-08-31 00-27-21](https://user-images.githubusercontent.com/40526984/91682969-38f12f80-eb21-11ea-92cf-1fa89955e4c7.png)

**Comment by tanpuekai** [comment]
i think it is same as violin plot, except violin plot is symmetric.

**Comment by andrewwbutler** [comment]
Hi,

For further details on these kinds of plots, please see the introduction vignette for `ggridges` [here](https://wilkelab.org/ggridges/articles/introduction.html).
