### ISSUE TITLE
Improve color scale for DimHeatmap()

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3446]
In the output of `DimHeatmap()`, it is not clear which color corresponds to upregulation/downregulation, since there is no color scale. Internally, the function `SingleRasterMap()` is called with `colors = PurpleAndYellow()`, but this option cannot be called from `DimHeatmap()`. Example: `DimHeatmap(pbmc_small)`

**Comment by andrewwbutler** [comment]
Hi,

To return a plot with the scale, please use the `fast = FALSE` option. This will also return the plot as a ggplot object so you can customize color scales if you wish.
