### ISSUE TITLE
Option combine=FALSE in DimHeatmap() not working

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3447]
For example, `DimHeatmap(pbmc_small, dims=1:2, combine=FALSE)` results in one plot with two heatmaps, not two separate ones.

**Comment by mojaveazure** [comment]
You have to set `fast = FALSE`; by default, `DimHeatmap` uses base-R graphics for faster plotting. Base-R plots are not manipulable the same way ggplot2-based graphics are, and thus cannot be separated into a list of plot objects like we can with ggplot-based graphics. Setting `fast = FALSE` will result in slower plotting, but allow full manipulation with the ggplot2 ecosystem.

**Comment by frederikziebell** [comment]
Maybe then write in the documentation that `combine=FALSE` only works for `fast=TRUE`, because the current status leads to unexpected behaviour and the user has to find out this "trick" by him/herself.

**Comment by mojaveazure** [comment]
It is mentioned in the [return value](https://rdrr.io/cran/Seurat/man/DimHeatmap.html) part of the documentation.
