### ISSUE TITLE
assay slot ignored in FindNeighbors()?

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3449]
Running `FindNeighbors(pbmc_small, assay="xyz")` does not result in an error. I suspect the default assay is always used.

**Comment by mojaveazure** [comment]
`FindNeighbors` will run on dimensional reduction data instead of features unless `dims = NULL`; to generate a nearest neighbor graph, you would have to pass `dims = NULL` along with your assay of choice. This is reflected in the development version of the documentation.
