### ISSUE TITLE
DoHeatmap for subsets of cells / conditions

### ISSUE THREAD

**Issue by dandepledge** [satijalab/seurat#345]
Hi Team Seurat,

I'm using the heatmap function to visualise DE genes between cell types but I also know that several are differentially expressed within a cell type - according to experimental conditions.

As an example, I have several genes that are highly upregulated in one type of cells compared to all other (in which those genes are expressed at low levels only) but I am interested in plotting the relative expression of two experimental conditions within a specific cell type as a DE analysis tells me they differ.

In my current plots (which account for all cells), these differences are lost due to difference between cell types being bigger than the changes within my cell type of interest (see Fxyd1 and Serpine2 in the attached plot). 

Any thoughts on how I can redraw the heatmap to (i) pick a treatment condition as my baseline, and (ii) plot expression levels in other conditions relative to that - all within the specific cell type only?

![rplot01](https://user-images.githubusercontent.com/32496778/37124372-fcf2f3f8-2235-11e8-8fea-49e46a29bcfc.jpg)

**Comment by leonfodoulian** [comment]
Hi,

I don't think you can do that currently with Seurat. You might want to do that using a custom script. Also, since you want to plot fold changes between groups, you will not be able to plot expression levels within single cells using a heatmap as fold changes are calculated by pooling all cells from each of the conditions. However, you might want to consider doing that with a dot plot (similar to the `Seurat::DotPlot()` function).

Best,
Leon

**Comment by dandepledge** [comment]
Hi Leon,

Thanks for answering. The DotPlot() function is nice but last time I tried it only allows comparisons of two conditions. Has that been extended?

**Comment by leonfodoulian** [comment]
Hi,

Do you mean the `Seurat::SplitDotPlotGG()` function? If yes, then you are right, it can only take two conditions as input. However, for each cell, you can combine its corresponding cell type and condition manually and store that in your `object@meta.data` slot. Then you can simply pass this column as input to the `group.by` argument of the `Seurat::DotPlot()` function. However, I don't know how you will be able to plot fold changes in this case. I never tried that with Seurat. 

Hope this helped!

Best,
Leon
