### ISSUE TITLE
Error w/ FindNeighbors/FindClusters

### ISSUE THREAD

**Issue by agrubbs1** [satijalab/seurat#3450]
Hi all, 

I'm new here but spent a few hours troubleshooting with the other bioinformatics people in my department and we are all stuck. 

I am working through the 10X seurat tutorial and downloaded version 3.2 of seurat. (R version 4.0.2). 

When I run through the tutorial, I am getting the following message after FindClusters:
"Error in FindClusters.Seurat(pbmc, resolution = 0.5): 
Provided graph.name not present in Seurat object.

When we look at FindNeighbors, it gives an empty list.  
pbmc@neighbors it results
list()

All the associated R packages seem to have installed correctly and we have reinstalled Seurat through a few different methods. The pbmc data was downloaded today directly from the Seurat lab website. All the other commands in the tutorial are working fine up until that point. 

Thanks for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the dev team but could you please post the exact code that you have run?

Thanks,
Sam

**Comment by agrubbs1** [comment]
Sure!

library(Seurat)
library(dplyr)
library(patchwork)
pbmc.data <- Read10X(data.dir = "/.../filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <-FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc)
pbmc<- FindVariableFeatures(pbmc,selection.method = 'vst')
pbmc <- RunPCA(pbmc,npcs = 15)
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)

Thanks!
allison

**Comment by samuel-marsh** [comment]
Hi,

Thanks for posting you code.  It all looks ok.  Although two things (unrelated to the issue), one I assume you changed the file path for the data to your own file path and you don't create a percent.mt metadata column so subsetting on that is not going to have any effect.

Running your identical code I don't have any issues and can't reproduce your error.  What happens if you install the github develop branch of Seurat and run the code?

Best,
Sam
