### ISSUE TITLE
FindMarkers on integrated dataset

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#3451]
Dear all,

thanks for your magnificent Seurat package! But, I am having an integrated dataset with 11 samples and want to compute marker genes, some ident 1 vs. some ident 2. I have 3 assays, RNA, SCT and integrated. Which one should I use? I usually go for SCT because I think this is the assay where percent.mito and nUMI are regressed out but who knows...?

Thanks, Chris

**Comment by timoast** [comment]
See point 4 on the FAQ https://satijalab.org/seurat/faq.html
