### ISSUE TITLE
gsea/gsva on integrated datasets

### ISSUE THREAD

**Issue by jiayiliujiayi** [satijalab/seurat#3452]
Hi,

I’ve run an integration analysis and now want to perform a gsea and/or gsva. Which Assay would you recommend to be used?

Thank you very much for your insight!

Best, 
Jiayi

**Comment by timoast** [comment]
Since you need a set of differentially expressed genes for GSEA I guess your question is about which assay to use for DE. See number 4 on the FAQ https://satijalab.org/seurat/faq.html
