### ISSUE TITLE
Not possible to plot identity class in DimPlot() in a random order?

### ISSUE THREAD

**Issue by massisnascimento** [satijalab/seurat#3453]
Hi. I was wondering if there is a way to plot my identity classes in a way that one is not plotted over the other one, like in different layers. Using group.by or setting the active identity with Idents() render the same result:

![image](https://user-images.githubusercontent.com/66184172/91812158-7ae3a980-ebe5-11ea-91f5-f8c0b3c02ed1.png)

Is there a way to visualize these two identities as if they were in the same layer?
Thanks,

**Comment by samuel-marsh** [comment]
Hi,

I would suggest updating to the latest version of the develop branch.  They recently updated and merged a PR I made that directly addresses this issue.  See #3408.  New parameter for DimPlot is called `shuffle`.

Best,
Sam
