### ISSUE TITLE
VlnPlot of colSums(data) returns a distribution although invariant value of 10000 is expected

### ISSUE THREAD

**Issue by katsikora** [satijalab/seurat#3456]
Dear Seurat Devs,

this is a minor and a mildly entertaining issue, but by running 

<code>plotset[["colSums.data"]]<-colSums(expm1(as.matrix(GetAssayData(plotset,slot="data"))))
VlnPlot(plotset,"colSums.data") </code>

I get:

![colSums data perCluster VlnPlot](https://user-images.githubusercontent.com/7079932/91857765-a78cd500-ec68-11ea-8fc0-124e7524f616.png)

The good old boxplot for 

<code>boxplot(plotset[["colSums.data"]]$colSums.data~plotset[["ClusterNumber"]]$ClusterNumber)</code>

returns:

![boxplot](https://user-images.githubusercontent.com/7079932/91858219-2e41b200-ec69-11ea-9065-d18d48a7883e.png)

which is a better representation of the underlying data, as all cells have been normalized to the same default value 10000.

Seurat version 3.1.5.

Best,

Katarzyna

**Comment by cdarby** [comment]
Thank you for your question, Katarzyna. Your example where the data has a constant value showcases a feature of VlnPlot: this function adds jitter to the data plotted.

Best,
Charlotte
