### ISSUE TITLE
Subsetting clusters from FindNeighbors and FindClusters

### ISSUE THREAD

**Issue by gr8lawrence** [satijalab/seurat#3458]
Hi Seurat team,

We're interested in finding cluster-specific gene markers from the cluster outputs via FindClusters. We decide to only use the cells that are in the center of the clusters to reduce ambiguity. That requires us to subset the cells based on their "distance" (Euclidean distance or other distance metrics) to the cluster centers. However, being relatively new to Seurat, I was stuck at trying to understand where are such "distances" and the coordinates of the center of the clusters stored in the Seurat object. Can you point out a way that I can retrieve such information and manipulate the subsetting thereby? If no such direct outputs are stored (I know the SNN graph matrix is definitely there), can you point out a reference for the KNN + SNN clustering techniques you are using, including details for the distance metrics and how the algorithm makes decisions for the cluster membership of cells? 

Thank you,
Tianyi

**Comment by satijalab** [comment]
We do not store the coordinates of cluster centroids, though you can certainly calculate these manually.

For KNN, we use the RANN library by default (https://cran.r-project.org/web/packages/RANN/index.html), but also support calculation with annoy and different distance metrics if you'd like.

For SNN clustering, it depends on the algorithm you specify (Louvain, SLM, Leiden, etc.). You should be able to easily find references for each. you can use ?FindClusters or ?FindNeighbors for more info
