### ISSUE TITLE
What is the rationale behind choosing  nGene (gene count) threshold?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#346]
I am pretty lost how to set lower/upper cuttoff for filtering (function _FilterCells_) cells base on low/high gene count (_nGene_). How can I decide the threshold?

**Comment by leonfodoulian** [comment]
Hi,

This all depends on the distribution of the number of genes in your data. The idea is that cells having a low number of genes might represent low quality cells, or cell fragments. And you might want to get rid of these cells. The same question was asked in an earlier issue (please check [issue #259](https://github.com/satijalab/seurat/issues/259)).

Best,
Leon

**Comment by bishwaG** [comment]
Hi,
Thanks for your quick response. It is quite straight forward to know why cells with low gene counts are removed, but why cells with high gene counts also need removal? Are we removing outliers?

BR,
Bishwa

**Comment by leonfodoulian** [comment]
Hi Bishwa,

Regarding outliers with very high gene numbers, these might represent doublets, as doublets of different cell types elicit higher number of genes. 

Best,
Leon

**Comment by bishwaG** [comment]
Hi Leon,
Thanks a lot!! It helped a lot.

BR,
Bishwa
