### ISSUE TITLE
change the color of the plot

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3461]
Hello,

I want to change the healthy control into green color, and severe into red color.

Thanks in advance for any help!

Best,

Yue

```
> RidgePlot(Basal, features = c("MAFF"),group.by="tech") + theme(axis.title.y = element_blank())
Picking joint bandwidth of 0.0865
> RidgePlot(Basal, features = c("MAFF"), cols.use = c("green","blue","red"),group.by="tech") + theme(axis.title.y = element_blank())
Error in RidgePlot(Basal, features = c("MAFF"), cols.use = c("green",  : 
  unused argument (cols.use = c("green", "blue", "red"))
```
![Screenshot from 2020-09-02 06-01-07](https://user-images.githubusercontent.com/40526984/91968356-8963bb00-ece2-11ea-8092-e96ce8522cd2.png)

**Comment by samuel-marsh** [comment]
Hi,

As the error warning suggests you supplying argument that no longer exists (`cols.use`).  You can use the `cols` argument to set the colors for the groups.  I would suggest checking out the manual entries for various functions as those may answer your questions.

Best,
Sam

**Comment by Byronxy** [comment]
Hi, you can try scale_color_manual, which follows with `ggplot2` grammar.
Best,
Yi
