### ISSUE TITLE
No jitter for VlnPlot (I want jitter)

### ISSUE THREAD

**Issue by hello-it-me** [satijalab/seurat#3462]
I'm new to scRNA seq analysis and I'm currently following this tutorial https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html with a different dataset. I did try to use the dataset specified in the tutorial, but I kept getting an error message very early on in the tutorial:

> '>VlnPlot(pbmc2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Error in if (all(data[, feature] == data[, feature][1])) { : 
  missing value where TRUE/FALSE needed`

I don't have this issue with the dataset I'm using. I've gotten to the part where I'm generating violin plots of gene expression for each cluster. It looks like the majority of the dots/cells are not jittered and I can't figure out why. My plots are looking like this:
`VlnPlot(pbmc, features = c("Itgae", "Itgax", "Xcr1", "Cd8a"), pt.size=0.5, idents=6, log=TRUE)`
![Rplot](https://user-images.githubusercontent.com/63904639/91979762-3abf1c80-ecf4-11ea-810e-052c579cc7a7.png)

Any suggestions? Thank you!

**Comment by samuel-marsh** [comment]
Hi,

If you are receiving error message could you please post the full code that you are running prior to the error?  The same goes for your analysis where you are having trouble with `VlnPlot` function.

Thanks!
Sam

**Comment by hello-it-me** [comment]
> Hi,
> 
> If you are receiving error message could you please post the full code that you are running prior to the error? The same goes for your analysis where you are having trouble with `VlnPlot` function.
> 
> Thanks!
> Sam

Hi Sam, thanks for taking a look. I'm following the tutorial I linked in the post. Save for changing the genes or a couple of thresholds, everything is the same:

This is the dataset specified in the tutorial that I was getting an error with: https://s3-us-west-2.amazonaws.com/10x.files/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz

```
pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/")

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```
At this point I get that error above. 

Using another dataset (http://bioit2.irc.ugent.be/cdc2/download.php the fig3 count matrix data) I effectively did the same as above (when looking for the mito genes the pattern I looked for was "^mt-" since this dataset is mouse) and continued with the tutorial. I copied the lines of code that are pertinent for generating the violin plots:

```
pbmc <- subset(pbmc, subset = nFeature_RNA > 500 & nFeature_RNA < 4000 & percent.mt < 5)

all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))

ElbowPlot(pbmc)

pbmc <- FindNeighbors(pbmc, dims = 1:15)
pbmc <- FindClusters(pbmc, resolution = 0.5)

pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

VlnPlot(pbmc, features = c("Itgae", "Itgax", "Xcr1", "Cd8a"))
```

**Comment by samuel-marsh** [comment]
Hi,

In the case of your top code I am unfortunately, unable to recreate the error running the identical code.  What version of Seurat are you running and did you install from CRAN or github?

In the case of your bottom code you are missing a couple steps from the tutorial.  Those steps include:
--Normalization of the data
--In your code for PCA you have it set to use the variable features from the object but you don't have the code included to calculate the variable features first.

I believe those should solve your issues there.

Best,
Sam

**Comment by hello-it-me** [comment]
I am running 3.2.0 and I installed from CRAN. 

Thanks for catching that, I can't believe I missed the normalization. Aye ! 🥇 

I did do the calculation for the PCA, I just missed the line during the copy&paste (: 

Thanks, I just reran the code and there is jitter now!

**Comment by sbusbdj** [comment]
Hi, I had the same question with your first one. This is my code that I was getting an error with:

>`darmanis <- readRDS("darmanis.rds")
darmanis
#head(darmanis@colData$total_counts,5)
darmanis <- runPCA(darmanis)
darmanis.seurat <- as.Seurat(darmanis)

rownames(darmanis.seurat@meta.data) <- gsub("_","-",rownames(darmanis.seurat@meta.data))
darmanis.seurat[["percent.mt"]] <- PercentageFeatureSet(darmanis.seurat, pattern = "^mt-")
head(darmanis.seurat@meta.data,5)

VlnPlot(darmanis.seurat,features=c("total_features","total_counts", "percent.mt"), ncol=3)`

**Comment by sbusbdj** [comment]
Hi, I had the same question with your first one. This is my code that I was getting an error with:
`darmanis <- readRDS("darmanis.rds")
darmanis
#head(darmanis@colData$total_counts,5)
darmanis <- runPCA(darmanis)
darmanis.seurat <- as.Seurat(darmanis)

rownames(darmanis.seurat@meta.data) <- gsub("_","-",rownames(darmanis.seurat@meta.data))
darmanis.seurat[["percent.mt"]] <- PercentageFeatureSet(darmanis.seurat, pattern = "^mt-")
head(darmanis.seurat@meta.data,5)

VlnPlot(darmanis.seurat,features=c("total_features","total_counts", "percent.mt"), ncol=3)`

> Error in if (all(data[, feature] == data[, feature][1])) { : 
  missing value where TRUE/FALSE needed
