### ISSUE TITLE
Option ncol not working in FeaturePlot()

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3463]
For example, `FeaturePlot(pbmc_small,"nCount_RNA", split.by="RNA_snn_res.1", ncol=2)` shows 3 columns, not 2.

**Comment by timoast** [comment]
As stated in the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/FeaturePlot), the `ncol` parameter cannot be used if `split.by` is not `NULL`

**Comment by MarcElosua** [comment]
This worked for me to specify the number of rows and columns when using split by in FeaturePlot
```
FeaturePlot(pbmc_small,"nCount_RNA", split.by="RNA_snn_res.1") +
    patchwork::plot_layout(ncol = 2, nrow = 2)
```

**Comment by plijnzaad** [comment]
Can you please make this work?  MarcElosua's solution should not be needed, really.

**Comment by samuel-marsh** [comment]
Hi @plijnzaad,

I have implemented solution for this in my package scCustomize (see this link for specific example https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#split-feature-plots).  Other package features also detailed in vigenttes.

Given the way Seurat plots split plots controlling the ncol variable would not provide a clear visualization when plotting more than one feature.

Best,
Sam

**Comment by bio-visualisation** [comment]
@samuel-marsh 
Hi, is there any way to restrict to one legend for all split FeaturePlot_scCustom. Since all the scales are same I want to keep only one legend.
