### ISSUE TITLE
RPKM?

### ISSUE THREAD

**Issue by GitHubbit** [satijalab/seurat#3467]
Hi Seurat Team,

Our raw data is in RPKM - we have no way of obtaining the raw data, and we don't have the sequencing depth or gene lengths, so we cannot convert to TPM or any other unit reliably. 

(1) Could we still create a Seurat object with an RPKM matrix? 
(2) If so, should we LogNormalize() (or manually log transform it? And if so, using natural log?) and ScaleData()?
(3) Can we perform differential gene expression analysis, clustering, construct UMAPs, t-SNEs, and other plots as available in the Seurat package as normal?

Any advice on how to treat the data in RPKM is welcome. Thank you.

**Comment by Dragonmasterx87** [comment]
So you don't have gene counts? Raw counts or exon counts? Sometimes they can be hidden in the files that have RPKM/FPKM data....

**Comment by GitHubbit** [comment]
No unfortunately. I just have a matrix of RPKM values from a patient to work with.

**Comment by satijalab** [comment]
Yes, you can work off of FPKMs, and can use the standard Seurat workflow for downstream analysis
