### ISSUE TITLE
separate the figure

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3468]
Hello,

I have figure like this:

Ia that possible I can separate the figure into three: 1. healthy control,  2. mild,  3.  severe?

Thanks in advance for great help!

Beat,

Yue 

` DimPlot(Macrophage, reduction = "umap", group.by = "tech")`

![Screenshot from 2020-09-03 05-10-56](https://user-images.githubusercontent.com/40526984/92096347-c5f7eb00-eda4-11ea-936e-9b5a4da9bf7d.png)

**Comment by yueli711** [comment]
Hello samuel-marsh,

Thank you so much for your great help.

Is that possible can let the healthy_control as green color, mild as yellow color and severe as red color?

Thank you in advance for your great help!

Best,

Yue

 ` DimPlot(Macrophage, reduction = "umap",cols = c("cornflowerblue","green3","orangered"),split.by = "tech")`

![Screenshot from 2020-09-03 23-01-40](https://user-images.githubusercontent.com/40526984/92194758-73b4d980-ee39-11ea-9206-0dbd47e2715f.png)

**Comment by samuel-marsh** [comment]
Hi Yue,

Again this issue could be resolved by checking the manual entry for `DimPlot`.  In short when you plot a DimPlot it plots by active ident by default which is typically the cluster identity and it appears you only have one cluster, "Macrophage".  Therefore it only takes the first color that you use in the `cols` parameter.  If you want to color by the same meta data column that you used to split the plots you have to add `group.by` to the function as well.

Best,
Sam
