### ISSUE TITLE
Feature request for Dotplot

### ISSUE THREAD

**Issue by zhangchipku** [satijalab/seurat#3469]
Dear Seurat team,
Wonderful package!
For Dotplot function, the size of the dot is percent of cells expressed the feature and the color is average expression of the feature across all cells
After discussion with wet lab scientists, we are wondering if it is possible to let the color show average gene expression of only the cells that express the feature instead of averaging on all cells?

**Comment by satijalab** [comment]
We don't suggest this - as we do not recommend ignoring 0 values (see https://www.nature.com/articles/s41587-019-0379-5 for justification)

**Comment by zhangchipku** [comment]
In my defense, 
1, In dotplot, the percent of 0s are reflected by the dot size already, so we are not ignoring 0s. The color showing expression average of non-zero cells is more intuitive in this setting.
2, I suggest this feature to be implemented as an optional flag with default to OFF, so users can execise their own discretion.
