### ISSUE TITLE
FindConservedMarkers object@ident

### ISSUE THREAD

**Issue by hekselman** [satijalab/seurat#347]
Dear team!
First, let me thank you for the great CCA tutorial! Really helpful :)
Second, after using CCA with my data, when I get to FindConservedMarkers each of my clusters, I keep on getting this:

```R
Warning message:
In if (!ident.use.2 %in% object@ident) { :
  the condition has length > 1 and only the first element will be used
```

Is the object@ident used as background cells or something? What is the error exactly? I think it might have something to do with having the orig.ident set to 4 different identities: control1, control2, treatment1, treatment2. As you suggest in the tutorial, I set the "stim" column to either control or treatment only and I set the grouping.var to "stim", but it still gives me this error.

Have any idea what is the problem?
Thanks a head,
Dany.

**Comment by dandepledge** [comment]
FindConservedMarkers only allows comparison of two conditions. 

You can use FindMarkers (with all the same parameters) for comparing multiple conditions (e.g. ident.1=c(cond1,cond2), ident.2=c(ctrl1,ctrl2).

This was plaguing me yesterday so hope it saves you some time!

**Comment by hekselman** [comment]
The thing is that am investigating only 2 conditions! I just wonder whether the function tries to analyze and compare between the 4 replicants (2 in each condition) - something that I do not want want to happen.

**Comment by hekselman** [comment]
#I start from loading 2 treated replicants and 2 control replicants
load("treated1.Robj")
load("treated2.Robj")
load("control1.Robj")
load("control1.Robj")

#merging, scaling and finding variable genes for treated and control
treated <- MergeSeurat(treated1, treated2, add.cell.id1 = "t1", add.cell.id2 = "t2")
treated <- ScaleData(object = treated , vars.to.regress = c("orig.ident","nUMI"))
treated <- FindVariableGenes(object = treated , mean.function = ExpMean, dispersion.function = LogVMR, cex.use = 0.01, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5, do.plot=FALSE)
control <- MergeSeurat(control1, control2, add.cell.id1 = "c1", add.cell.id2 = "c2")
control <- ScaleData(object = treated , vars.to.regress = c("orig.ident","nUMI"))
control <- FindVariableGenes(object = treated, mean.function = ExpMean, dispersion.function = LogVMR, cex.use = 0.01, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5, do.plot=FALSE)

#like in the CCA tutorial
g.1 <- head(rownames(treated@hvg.info), 1000)
g.2 <- head(rownames(control@hvg.info), 1000)
genes.use <- unique(c(g.1, g.2))
genes.use <- intersect(genes.use, rownames(treated@raw.data))
genes.use <- intersect(genes.use, rownames(control@raw.data))

#then I change the orig.ident from treated1 and treated2 into Treated. Done the same for controls... I previously tried leaving the orig.ident and making a new column names "stim" like you did, and I still get this warning
treated@meta.data$orig.ident <- "Treated"
control@meta.data$orig.ident <- "Control"

#CCA analysis
Merged <- RunCCA(treated, control, genes.use = genes.use)
DimPlot(object = Merged, reduction.use = "cca", pt.size = 0.5, do.return = TRUE, group.by = "orig.ident")
MetageneBicorPlot(Merged, grouping.var = "orig.ident", dims.eval = 1:20)

#I chose 6 CCs (is this really the phase where I need to determine the CCs?)
Merged <- AlignSubspace(Merged, reduction.type = "cca", grouping.var = "orig.ident", dims.align = 1:6)
Merged <- RunTSNE(Merged, reduction.use = "cca.aligned", dims.use = 1:6)
Merged <- FindClusters(Merged, reduction.type = "cca.aligned", resolution = 0.6, dims.use = 1:6)

#markers for cluster 0 - that's when I get the error. I tried with and without determining the grouping.var, but what is it grouping for? What is this parameter's use?
Merged_markers_0 <- FindConservedMarkers(Merged, ident.1 = 0, grouping.var = "orig.ident", print.bar = TRUE)

**Comment by leonfodoulian** [comment]
Hi Dany,

This is simply a **warning**, and not an **error**. It is not related to the `grouping.var` argument. Provided that you set `ident.2` to `NULL`, and if you have many clusters in your dataset, your `ident.2` will be all identities except that specified in `ident.1`. Now, when [lines 680 to 682 in differential_expression.R ](https://github.com/satijalab/seurat/blob/f4da9c6e725ee9ee833d8ef60809e56e13b3062a/R/differential_expression.R#L680-L682) are being executed, and provided that `ident.2` has multiple levels, the test for the `if` statement is restricted to the first level in `ident.2`.

```R
> x <- c("a", "b", "c")
> idents <- c("a", "b", "c", "d")
> if (!x %in% idents) {
+   print("stop")
+ }
Warning message:
In if (!x %in% idents) { :
  the condition has length > 1 and only the first element will be used
```

However, a solution for this would be to test for all levels in `ident.2` by using the `all()` function in base R as follows (which does not give any warnings):

```R
> if (!all(x %in% idents)) {
+   print("stop")
+ }
```

If the function did not stop after the **warning**, there is usually nothing to worry about. But I guess it will be a good idea to update this statement in such a way that all identities in `ident.2` are tested.

Hope this helped!

Best,
Leon

**Comment by hekselman** [comment]
For now the results look very different from the PCA (i.e. the markers of the clusters I've found using this method don't seem even close to the clusters I've found both in treated and control separately using PCA).

**Comment by leonfodoulian** [comment]
Note that in this case, `Seurat::FindConservedMarkers()`, as its name denotes, finds markers that are conserved between the different groups. So you are not really doing differential expression in this case. And it is normal that the results be different because here you keep only what is common between the two groups. 

Best,
Leon

**Comment by leonfodoulian** [comment]
Update:

You are computing differential expression between the clusters within a condition, but for the same cluster between the conditions (i.e. stimulus and control groups).

**Comment by hekselman** [comment]
That's exactly what I am talking about :)
I clustered treated and control, separately:
-found markers of cluster x in treated, compared to the rest of the treated cells
-found markers of cluster x (same type of cells) in control, compared to the rest of the control cells....

Then when I compare the **common** markers of clusters x I've found, with the markers I've found using FindConservedMarkers function - they are different!
Let me know if I was clear enough :)

**Comment by MichaelPeibo** [comment]
Hi, 
I also tried FindConservedMarkers function, but I got this error, any suggestion?
`conservedMarker7.16=FindConservedMarkers(mda.tsne.1.2.PC20,ident.1 = 7,ident.2 = 16,grouping.var = "orig.ident") 
Error in apply(X = markers.combined[, pval.codes], MARGIN = 1, FUN = max) :
  dim(X) must have a positive length
`
BTW, what is the meaning of `grouping.var`?
Thanks in advance!

**Comment by satijalab** [comment]
FindConservedMarkers performs a meta-analysis, where DE is calculated between clusters for multiple conditions, and then combine the results of these tests using the metap package.

grouping.var specifies the variable name that specifies which condition (as opposed to which cluster), the cell is in

**Comment by MichaelPeibo** [comment]
i kind of got it what you mean @satijalab , if I have two conditions(such as batch, protocol, group), I can evaluate the conserved markers between these conditions; 

I thought this function find conserved genes between two clusters, which is wrong.

BTW, is there any way to find  conserved genes between two clusters, only for cells in one condition?
