### ISSUE TITLE
analyzing specific cell types is full of noise

### ISSUE THREAD

**Issue by Diozao666** [satijalab/seurat#3470]
Hello

Usually, when I generate clusters with all cell types and run differential expression analysis I get a really clear heatmap, with cells uniformly expressing genes that seem mostly specific to each cluster, which helps me to define cell types. However, when I select a specific cell type and subcluster them, let's say CD4 T cells, the heatmaps tend to be very noisy, regardless of the resolution I set up. This also happens if I run DE analysis between groups, using this specific cell type. Based on other biological information we have this does not make a lot of sense. I have seem that a few papers do not even show the entire heatmaps when this sort of analysis is done. Previous experience from bulk RNA-seq teached me to not trust only in the FDR/FC generated by DE analysis, but check the heatmaps and see if the DEGs look somewhat homogeneous. 

Is this a common issue? Am I missing other steps or is my results what they are?

**Comment by jaisonj708** [comment]
It is common to find poor substructure in cell types like CD4 T cells, given how sparse scRNAseq tends to be. For the same reason, you might not see 'homogenous' DEGs as you'd like (e.g, CD4 will not be present in a majority of your CD4 T cell cluster)

**Comment by timoast** [comment]
Just want to add that you might find better separation if you re-run FindVariableFeatures and ScaleData on the subset dataset

**Comment by Diozao666** [comment]
> Just want to add that you might find better separation if you re-run FindVariableFeatures, ScaleData, and PCA on the subset dataset

Oh, I did re run all these steps, along with TSNE or UMAP, but I did not run ScaleData again. Now I tried it again with ScaleData and my heatmap is still somewhat "wonky" but much, much better. Thank you very much

**Comment by dm8000** [comment]
> Just want to add that you might find better separation if you re-run FindVariableFeatures, ScaleData, and PCA on the subset dataset

is this recommended even if I integrated the dataset with SCT method? because the vignette says to not run ScaleData after integration
