### ISSUE TITLE
Can I use the function FindAllMarkers() to find DEG across samples instead of clusters?

### ISSUE THREAD

**Issue by wodanaz** [satijalab/seurat#3471]
I have a data object that looks like the table below and I would like to find DEGs for the group variable. is that possible?

Thanks!

> lvsc_8to15_umap[[]]
                     orig.ident nCount_RNA nFeature_RNA group nCount_SCT nFeature_SCT SCT_snn_res.0.5 seurat_clusters
AAACCCAAGGATGGCT.1_1      Integ       2404         1330  8HPF       2416         1330               5               5
AAACCCATCAGATGCT.1_1      Integ       3098         1650  8HPF       2878         1650               5               5
AAACGAACACATATGC.1_1      Integ       1857         1274  8HPF       2052         1274               5               5
AAACGAAGTACAGCGA.1_1      Integ       1446         1019  8HPF       1937         1024               5               5

**Comment by papal22e** [comment]
yes, you can do that. 

First set your idents to the group variable:
Idents(object) <- "group"

Then run FindAllMarkers: 
group.markers <- FindAllMarkers(object, assay = "RNA")

**Comment by wodanaz** [comment]
Thanks @papal22e  for the prompt response. It works!

Best,
Alejo
