### ISSUE TITLE
Tips for integrating datasets

### ISSUE THREAD

**Issue by dlmatera** [satijalab/seurat#3472]
I am trying to integrate 3 datasets but am only interested in a specific subtype (stromal) cells. So far I have followed the vignettes using SCTransform normalization and can successfully integrate the data. However, the fibroblast subtypes i am interested in (that exist in the 3 datasets alone) seem to be lost/mixed together after integration. Is there a way to optimize this beyond changing the # of variable features to consider? 

Also, i am doing the alignment just on the stromal cell population, would this be more accurate if I integrated in the presence of the entire dataset (with immune cells, epis, etc.)? I have not done this so far due to the computational burden.

Lastly - is there a guide anywhere beyond the vignettes that goes into more detail about how this integration works? (besides me digging into source code and googling terms & syntax i am unfamiliar with?)

Thanks for any help!

**Comment by jaisonj708** [comment]
You might want to check if fibroblast subtype markers are present in your anchor features. (They should be, if all 3 datasets contain these subtypes). If not, you can add them to the VariableFeatures of each object, re-scale, re-run PCA, and try integrating again.

For more info on Seurat v3 integration, see [Stuart*, Butler*, et al., Cell 2019  ](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8)
