### ISSUE TITLE
Errors on FindTransferAnchors()

### ISSUE THREAD

**Issue by candacelei** [satijalab/seurat#3473]
I am using Seurat_3.1.2. I had an error running FindTransferAnchors():

> reference.list

$N
An object of class Seurat
22829 features across 3987 samples within 1 assay
Active assay: RNA (22829 features)

$T
An object of class Seurat
22829 features across 1006 samples within 1 assay
Active assay: RNA (22829 features)

>query<-reference.list[["N"]]
>reference<-reference.list[["T"]]
>anchors<-FindTransferAnchors(reference = reference, query = query, dims=1:30)

Performing PCA on the provided reference using 0 features as input.
Error in irlba(A = t(x = object), nv = npcs, ...) :
  max(nu, nv) must be positive

What does this error exactly mean?

**Comment by timoast** [comment]
You need to run `FindVariableFeatures` on the reference dataset first.
