### ISSUE TITLE
list of genes that are driving formation of the clusters

### ISSUE THREAD

**Issue by aelyaderani** [satijalab/seurat#3474]
Hi,

Is there a way to get a  list of genes that are driving formation of the clusters between two cell population clusters? I assume during the initial clustering, the genes driving formation may not necessarily completely overlap with the DEGs generated by FindMarkers().
<img width="839" alt="seurat_q" src="https://user-images.githubusercontent.com/34661195/92185318-8105a000-ee08-11ea-9a68-6e4648fcfea3.png">

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can help.  Why is it your assumption that genes driving clustering will not be in the DEG list?  Those genes driving clustering will almost certainly show up as DEG in the list.  It is more likely that there will be genes that were not used in the clustering that are also different between the clusters.

It does depend slightly on your workflow but in general for most workflows you have defined either a set number of variable features across the entire dataset or a threshold by which to select variable features.  These features are then generally the ones used during PCA and then downstream clustering is based on PCA.  Therefore, the genes that drive this separation of clustering absolutely will be in that variable gene list and also will show up in DEG list from `FindMarkers`.  You can get copy of the genes in this list using:
`var_genes <- GetAssayData(object = object, slot = "var.features")`

However, as I mentioned there may be additional genes with smaller effects may not have been included in the variable features cutoff but could still be unique cluster markers.  You can examine this by looking at the results of `FindMarkers` and filtering for genes expressed in a certain % of ident.1 and below certain % in ident.2 and then comparing to the variable gene list.

Hope that helps.
Best,
Sam

**Comment by jaisonj708** [comment]
Sam's answer is correct. `FindMarkers` will give you the DEGs that "drive separation" of your clusters, and if you pass all features and lower cutoffs (eg `min.pct`), you are unlikely to miss any of the important features that distinguish your clusters.
