### ISSUE TITLE
Both "data" and "scale.data" slots in "integrated" assay are populated following SCTransform.

### ISSUE THREAD

**Issue by davidsanin** [satijalab/seurat#3476]
Hi!
I integrated several dataset following SCT normalisation using RPCA. The documentation for the "IntegrateData" function says that:
"If normalization.method = "LogNormalize", the integrated data is returned to the data slot and can be treated as log-normalized, corrected data. If normalization.method = "SCT", the integrated data is returned to the scale.data slot and can be treated as centered, corrected Pearson residuals."
As "SCT" was my normalization method, I would expect to only have data in the "scale.data" slot, however, there is also a matrix in the "data" slot. What are these values?
Inspecting them manually, I can see some genes where the expression levels are exactly the same across both slots and others where the relative difference between clusters is the same but the values are different. 
Thanks!

**Comment by jaisonj708** [comment]
The data slot contains the batch-corrected, but non-centered, Pearson residuals
