### ISSUE TITLE
Labeling samples based on sample ID

### ISSUE THREAD

**Issue by yuepheng1** [satijalab/seurat#3478]
Hello,

I want to label my TSNE plot based on my sample IDs and was wondering what I should do. All of my samples are derived from VSMCs and I want to differentiate each of the subpopulations within that cell type. We also currently don’t have anything in our meta data that helps to specify which cells comes from which sample. What I essentially want to do is create a column that derives from the barcode. Essentially I would like the barcode-1, barcode -2, etc to be sorted into group 1, group 2, etc. Thank you.

**Comment by jaisonj708** [comment]
You can add a metadata column and set this to the object's Idents. To add metadata based on the barcodes as you say, you can use a command like `Seurat:::ExtractField(string = 'barcode-1', delim = '-', field=2)` (returns `1`)
