### ISSUE TITLE
FastMatMult problem while performing ProjectPCA

### ISSUE THREAD

**Issue by namelast** [satijalab/seurat#348]
Hello, 

I am working with a large-ish dataset (43k cells, 24k genes) 10X Genomics dataset (Seurat object ~12 GB). When performing ProjectPCA, I encounter the following error:

```
Error in FastMatMult(m1 = data.use, m2 = cell.embeddings) : 
  std::bad_alloc
```

Do you have any idea on the cause? Is it a memory problem or some other reason? Any fix or workaround (either than getting more memory, if this is the problem)?

Thanks a lot for your help!

**Comment by mschilli87** [comment]
Without any further information, I share your guess: It looks like you run out of memory during the matrix multiplication. To confirm I suggest you monitor your memory usage while running the command (I can't tell you how as I don't know which operating system you are on).

Can you try with a subset of the data on the same machine and/or with the same data on a bigger (memory-wise) machine?

**Comment by namelast** [comment]
Dear Marcel, I was running the analysis on a linux laptop. Indeed, looking at memory usage, it looks like the calculation just requires more memory. I am looking for a higher memory machine now.

Thanks!
