### ISSUE TITLE
Can't get the umap coordinates of cells

### ISSUE THREAD

**Issue by throwaway123-problems** [satijalab/seurat#3480]
Ok so I'm new to sc analysis, be gentle...

I ran the following:
```

library(dplyr)
library(Seurat)
library(patchwork)

pbmc.data <- Read10X(data.dir = "/Volumes/oliver/Mac+work files/seurat_data/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)

pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2

all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
print(pbmc[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(pbmc, dims = 1:2, reduction = "pca")
DimPlot(pbmc, reduction = "pca")

pbmc <- RunUMAP(pbmc, dims = 1:10)
DimPlot(pbmc, reduction = "umap")



```

But then when I run the following to retrieve the UMAP coordinates using

```
pbmc_umap_coord <- pbmc@reductions$umap
pbmc_umap_coord2 <- as.data.frame(pbmc_umap_coord)

```

I get the following error:
Error in as.data.frame.default(pbmc_umap_coord) : 
  cannot coerce class ‘structure("DimReduc", package = "Seurat")’ to a data.frame

When I run:

`> View(pbmc_umap_coord)
`

I get:
Error in if (more || nchar(output) > 80) { : 
  missing value where TRUE/FALSE needed
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

Ultimately, what I'm trying to do is use a different data set where I perform UMAP on a dataset after I remove a set of genes. I want to then take the UMAP coordinates and then look for where the cells that are expressing various subsets of the genes I removed are located on the plot.
The idea is that the genes that I removed are highly variable/super sparsely expressed to begin with. So I want to perform UMAP dimensionality reduction without these genes. I then want to then visualize how cells expressing these genes are located on the UMAP plot without their influence. 

So I figured that if I remove UMIs for those genes and then create the Seurat object, perform UMAP and then pull the UMAP  coordinates, I can then just plot create simple plots using ggplot2 and coloring cells based on what genes they express.

**Comment by cdarby** [comment]
It seems like what you are looking for is the cell embeddings. These can be accessed by 
`pbmc[["umap"]]@cell.embeddings`
which can be converted to a data.frame using `as.data.frame` if you wish.

Take a look at the DimReduc-class documentation for more information on the slots in a DimReduc object (which is what you get from `pbmc[["umap"]]` or equivalently `pbmc@reductions$umap`. Also check out the Seurat DimPlot function that offers a lot of plotting functionality for Seurat objects with DimReducs, to see if it supports your plotting needs.
