### ISSUE TITLE
Ranking Clusters

### ISSUE THREAD

**Issue by npraju** [satijalab/seurat#3483]
So I want to do analyses by whole cluster (such as ranking clusters by a certain metric or by plotting the clusters in a scatterplot). I already have my seurat object that holds all of the gene expression data. How do I extract a secondary object out of my first object that holds only clusters and that I can add meta data to before visualizing?

**Comment by cdarby** [comment]
Thanks for your question @npraju . I'm assuming you want a new Seurat object with cells from one or more clusters. You can use the `subset` function to create a new Seurat object with some of the cells from your original Seurat object. Use the `idents` or `subset` parameter as the situation requires to select cells from certain clusters for later analysis and visualization. (If you're in Rstudio, type ?subset.Seurat to pull up the help text describing the subset.Seurat function and all its parameters).

If I misunderstood your goal, please feel free to re-open this issue and clarify your goal.
