### ISSUE TITLE
Does/Could AddModuleScore() use variable features?

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#3484]
Does/Could AddModuleScore() use variable features?

I found only the "assay = " parameter in the AddModuleScore() function. Could I calculate the score of features based on variable features found by FindVariableFeatures() after ScaleData(obj, vars.to.regress = c("S.Score", "G2M.Score"))?

Because I did want the cycling phase and its relative genes to influence the result of AddModuleScore, which means I did want those genes to be calculated in AddModuleScore even if the provided features include part of cycling genes.

And I wonder what is the default slot used by AddModuleScore()?

**Comment by grimwoo** [comment]
Could I run it as:

**Comment by samuel-marsh** [comment]
Hi,

Can you clarify your goal a little bit more?  What are you trying to calculate a module score of?

Even when you provide vars.to.regress those genes are still present in your object.  Additionally, the S.Score, G2M.score etc are module scores themselves not specific genes.  

Best,
Sam

**Comment by grimwoo** [comment]
@samuel-marsh 
Thanks to your early reply!
I have two cell types, A, B, and C, and their differentially expressed genes (DEs).
In my dataset, the average expression of DEs from each cell type was calculated by AddModuleScore. However, the score of the mother cell, A, is too high, and the other two scores (of B and C) were too low. Hence, I want to regress out the score of A, and then calculate the score of A, B, and C.

**Comment by timoast** [comment]
> In my dataset, the average expression of DEs from each cell type was calculated by AddModuleScore. However, the score of the mother cell, A, is too high, and the other two scores (of B and C) were too low. Because the score A is much higher than score B even in cell B, and same in cell C. Hence, I want to regress out the score of A, and then re-calculate the score of A, B, and C.

I wouldn't recommend doing this, sounds like you're trying to change the data to fit a certain result
