### ISSUE TITLE
Gene of interest disappeared after Seurat integration

### ISSUE THREAD

**Issue by liuweihanty** [satijalab/seurat#3485]
Hi there,
First of all thanks for the wonderful tool you developed!
I'm performing the standard integration procedures on my three Seurat object, they are a control sample, and two samples where my gene of interest is knocked down to a medium and low level, respectively. The procedures are

seu_list <- c(ctrl, KD1,KD2)
anchors <- FindIntegrationAnchors(object.list = seu_list, dims = 1:30, scale = FALSE,normalization.method = "LogNormalize")
kon.combined <- IntegrateData(anchorset = anchors, normalization.method = "LogNormalize",dims = 1:30)

However, after integration I couldn't find my gene of interest in the integrated data matrix kon.combined@assays$integrated@data. I thought the integration procedure captures the top 2000 most variable genes by default, I've also tried 3000 genes. Plus, my gene of interest is the gene I knocked down, so it should be the most variable gene actually, so it's super weird why it's not showing up after integration. Do you know why could this be the case? Thank you very much!

**Comment by cdarby** [comment]
It appears that your gene of interest was not selected in `FindIntegrationFeatures` as one of the 2000/3000 genes. Regardless, you can specify the features that will be present in the integrated data matrix separately. Use the `features.to.integrate` parameter in `IntegrateData`. (Note that the default is to use the features from anchor finding, which in your code snippet will be the result of FindIntegrationFeatures, which did not include your gene of interest.)
