### ISSUE TITLE
How to remove subject, batch and cell status variations at the same time using IntegrateData?

### ISSUE THREAD

**Issue by xwu302** [satijalab/seurat#3487]
Hi,

With the increasing sample size of my project, I found that I need to remove subject, batch and cell status variations for my current datasets. When I go back to check tutorial of integration, I found that 'panc8' example only used technique with one sample for integration, but inDrops dataset which contains multiple subjects is removed when running the tutorial. I guess that removing inDrops data in the tutorial is because this dataset contains subject effects as well, so before joining the correction of technique effects, it needs to correct subject effects at first, or it can't be overlaid well with other datasets.

I have some ideas on integration of my datasets, but I don't know if it's doable conceptually.

For example, I have 3 batches of sequencing run, each batch has 3 control + 3 stimulated samples being sequenced. I'm wondering if I could use IntegrateData to pull 3 biological replicates from the same batch and same condition to obtain subject effects corrected seurat object at first. Then, using 'integrated' slot of each subject-corrected seurat object to integrate three batches of control and stimulated samples, respectively, to correct batch effect. Finally, using the same idea to integrate control and stimulated samples to find conserved cell markers and so on.

Or do you have better idea to solve this problem?

Thanks and best,
Xin

**Comment by jaisonj708** [comment]
Your method should work fine - you are basically manually constructing the sample tree that `IntegrateData` automatically generates. But assuming your control samples are all more similar to each other than stimulated samples, and vice versa, `IntegrateData`'s default sample tree should also work fine (let us know if not).

Re: your comment on different kinds of technical effects (subject, batch, condition), these are all treated similarly by our method. It is not necessary to run separate integrations for each type of effect.
