### ISSUE TITLE
Typo fix AddModuleScore manual entry

### ISSUE THREAD

**Issue by samuel-marsh** [satijalab/seurat#3488]
Hi Seurat Team,

Just a note there is a typo in AddModuleScore documentation (missing a "t" in against):
https://github.com/satijalab/seurat/blob/86d33bff2a0197a987684e4749463f9060af2fc1/R/utilities.R#L19

Figured I'd submit issue rather than PR for such a small thing.

Best,
Sam

**Comment by mojaveazure** [comment]
Hi Sam,

Thanks for pointing this out. We've addressed this on the `develop` branch. For future reference, if you or anyone else notices small things like this, we more than welcome PRs to address them.
