### ISSUE TITLE
SCTransform use 

### ISSUE THREAD

**Issue by XiangyuYe** [satijalab/seurat#3489]
Hi,
    I am now using SCTransform() in data normalize and integration, but got confused in some points.
    Firstly, I am not sure whether I have got an overcorrect data, especially when it involved multiple samples data from the same object (like a CD45+ and CD45- cells pre-separated). May I first merge them separately? Secondly, it is recommended not to run ScaleData() after SCTransform() and IntegrateData(), but do.scale is also set FALSE as default. Was a scale process not necessary in such a workflow?
    What's more, it is declared that users would benefit by choose a higher PCs. But my dimension reduction outcomes does not follow a very stable line. Could I still feel free to choose a higher PCs？And it seems elbow and jackstraw would not be efficient methods for PCs choosing.
    It would be generous of you to offer me some advice. Thank you!

**Comment by jaisonj708** [comment]
SCTransform uses its 'scaling' procedure, the outcome of which are called Pearson residuals. So you do not need to run ScaleData again.
If you do not think your CD45+ and CD45- samples will have batch effects (or if you worry about over-correction), you can either merge or try RPCA which has slightly more conservative/stringent anchoring.
I don't completely understand your question about PCs - more PCs is usually better.
