### ISSUE TITLE
Subsetting cells expressing certain genes only

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#349]
Hi Seurat team,

I just started using Seurat about 2 weeks ago and I find it really powerful and user friendly. Thumbs up for the great work!

I wanted to ask how can I subset a group of cells expressing only a certain gene? For example, from my matrix, I want to extract an expression matrix of cells which only express, for example CADM1, for further analysis. 

Hope to hear back from you soon.
Thank you very much.

edit:
Sorry, another question here. I have a pool of cells separated into 2 groups, with and without stimulation. For this kind of data, should I use the Merge function or perform integrated CCA analysis? What is the difference in function for the both of them? 

Thank you very much.

**Comment by slukowski** [comment]
I came up with a workaround for my own work to do this. It looks for cells that are positive or negative for a given gene and you can subset based on that. Hope it helps!

```# 'dat' is the name of my Seurat object here. I've got 4 samples in this object.

# search for the gene in the expression matrix
grep('^Cd34', rownames(dat@data), value = FALSE)

# count how many cells express the gene (all non-zero expressing cells)
# in this case 'Cd34' is on row 931
length(which(dat@data[rownames(dat@data)[931], ] != 0))

# I make a dataframe that can house the metadata I'm interested in
sample.info <- data.frame(cell.names = dat@cell.names)

# I'm adding batch information based on the cell barcodes that have a suffix denoting the batch ID. Sometimes this could be a prefix, or it may need to be added manually if it's not there.
sample.info$batch = 'Unknown'
sample.info$batch[grep('-1', dat@cell.names)] <- 'Sample 1'
sample.info$batch[grep('-2', dat@cell.names)] <- 'Sample 2'
sample.info$batch[grep('-3', dat@cell.names)] <- 'Sample 3'
sample.info$batch[grep('-4', dat@cell.names)] <- 'Sample 4'

# add a column for pos/neg expressing cells
sample.info$Cd34 = 'Neg'
sample.info$Cd34[which(dat@data[rownames(dat@data)[931], ] != 0)] <- 'Pos'

# make the cell barcodes the rownames and I also convert the actual cell barcode column to 'character' here too
row.names(sample.info) <- sample.info$cell.names
sample.info$cell.names <- as.character(sample.info$cell.names)

# stash the original identifiers before changing them
dat <- StashIdent(dat, "OrigClusterID")

# add the new sample info to the object metadata
dat <- AddMetaData(object = dat, metadata = sample.info)
dat <- SetAllIdent(object = dat, id = "Cd34")

# subset only the positive cells
cd34.subset <- SubsetData(object = dat, ident.use = 'Pos')

```

**Comment by nicodemus88** [comment]
@slukowski 
Thank you for your reply.
It looks rather complex, but I will try it out. 
Thank you very much for your assistance.

**Comment by atakanekiz** [comment]
You can also use the following functions for this purpose:

`which(object@raw.data["gene_name",]>1`
`FilterCells(object, subset.names = "gene_name", low.thresholds = 1)`
`WhichCells(object, subset.name = "gene_name", accept.low = 0.001)`
`WhichCells(object, subset.name = "gene_name", accept.low = 0.1, use.raw=T)`
`SubsetData(object, subset.name = "gene_name", accept.low = 1)`

`accept.low` values might change from experiment to experiment, and can be changed based on the expression level you want to "gate".

**Comment by eoinrenal** [comment]
Is there a way to filter or subset based any one of number of genes? i.e. expresses Gene1 **or** Gene2 **or** Gene3 ?

using a vector of cells names and values in the above functions gives the cells which express Gene 1 **and** Gene 2 **and** Gene 3

**Comment by kmshort** [comment]
> Is there a way to filter or subset based any one of number of genes? i.e. expresses Gene1 **or** Gene2 **or** Gene3 ?
> 
> using a vector of cells names and values in the above functions gives the cells which express Gene 1 **and** Gene 2 **and** Gene 3

Seurat 3.1:
How to subset using OR, working on the raw counts slot in a seurat object (object):
WhichCells(object, slot = 'counts', expression = Gene1 > 0 | Gene2 > 0 | Gene3 > 0 )

How to subset using AND, working on raw counts as above.
WhichCells(object, slot = 'counts', expression = Gene1 > 0 & Gene2 > 0 & Gene3 > 0 )

obviously not using a vector of names though..
