### ISSUE TITLE
why the FindVariableFeatures function calculate the columns variable on seurat?

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3490]
Hi @all,
    It make me confuse that i found the FindVariableFeatures function generated the result that be similiar to 
    maligant_matrix[,apply(maligant_matrix,2,sd )>0.5]. it was weird. As far as i am concerned that the high variable feature should be 
    calculate features among all cells not a cell sd among all features.
     Why the FindVariableFeatures  function do like this?
      Best,
       hanhui

**Comment by timoast** [comment]
I'm not really understanding the question, but you can find the documentation for FindVariableFeatures [here](https://rdrr.io/cran/Seurat/man/FindVariableFeatures.html) and see the SCTransform paper for more information: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1
