### ISSUE TITLE
Miniconda Dependency Clarification

### ISSUE THREAD

**Issue by JenniferWUSTL** [satijalab/seurat#3492]
Hi all!  I decided to open a new issue to gain clarification on #2850 which has me and my coworkers concerned: Can you elaborate on what things can go wrong with having miniconda on your system? Is it some dependency issue or does it change my analysis (like pvalues, counts etc)?  We do not call R or Seurat from miniconda but we do have it present on our computer to manage Python environments.

**Comment by samuel-marsh** [comment]
Hi,

The developers may be able to comment more but this is from previous thread where they discussed potential issues:
https://github.com/satijalab/seurat/issues/3273#issuecomment-662614893

Best,
Sam

**Comment by timoast** [comment]
We have found miniconda can sometimes cause a variety of issues related to compiling R packages and crashing R. If you encounter issues when using or installing Seurat and you have miniconda installed, we'd suggest that you first try disabling miniconda. If you have Seurat working fine alongside miniconda, any analysis in Seurat will _not_ be affected.
