### ISSUE TITLE
R keeps crash when using MAST

### ISSUE THREAD

**Issue by Kailewang** [satijalab/seurat#3497]
Hi,

I tried to use MAST do DE analysis of different cells states in one of my cell type. Below was the command I used: 
```
obj_sub1 <- NormalizeData(object = obj_sub1, normalization.method = "LogNormalize", scale.factor = 10000, assay = "RNA")
obj_DEmast <- FindMarkers(obj_sub1, ident.1 = c(1), ident.2 = c(2:3), test.use = "MAST", assay = "RNA", logfc.threshold = 0, min.pct = 0)
```
However, the R or Rstudio keeps crash at step "Combining coefficients and standard errors". I tried different Seurat version: V3.1.4, V3.2, and different MAST version: V1.10, V1.12, V1.14, they keep crash. The current obj I tested has ~3200 cells, but when the obj is very small, it could pass sometimes. Here are some error message I got.

![Screen Shot 2020-09-09 at 17 15 30](https://user-images.githubusercontent.com/39105604/92757402-51e4b680-f353-11ea-8d98-959458a9b0ec.png)
![Untitled](https://user-images.githubusercontent.com/39105604/92757423-56a96a80-f353-11ea-8343-4e69238016c1.jpg)

By the way, I re-installed my Seurat recently, it works good when I used old v3.1.4 months ago. 

However, when I test the same obj on my laptop using Seurat v3.1.5, and MAST: v1.14. It could run through. 

Best,
Kaile

**Comment by jaisonj708** [comment]
It could be a RAM issue (but unlikely given how small your object is).

Can you try running with `logfc.threshold` > 0 and `min.pct` > 0, and let us know if the error persists?

**Comment by Kailewang** [comment]
Thanks for replying, I tried, it worked if I used pct=0.1 and 0.05, however, it still crash at pct=0.01.

**Comment by timoast** [comment]
I haven't been able to reproduce this (MAST version 1.14.0), I'd recommend re-installing MAST and see if that fixes the issue. If not, can you try to reproduce the issue with one of the datasets in [SeuratData](https://github.com/satijalab/seurat-data)?

**Comment by timoast** [comment]
This is the code that I ran:

```r
library(SeuratData)
library(Seurat)

data("panc8")

Idents(panc8) <- "celltype"

panc8 <- UpdateSeuratObject(panc8)

markers <- FindMarkers(
  object = panc8,
  ident.1 = "gamma",
  ident.2 = "beta",
  test.use = "MAST",
  assay = "RNA",
  logfc.threshold = 0,
  min.pct = 0
)
```
