### ISSUE TITLE
@metdata changed when updateSeuratObject from v2 to v3?

### ISSUE THREAD

**Issue by duocang** [satijalab/seurat#3498]
I process the data in v2 and v3 twice. The @metadata were identical.

When I tried to import/update the v2 Seurat object into v3, I find the @metada is changed (nCount_RNA and nFeatures_RNA).

I put the data in OneDrive, you can download it and try with the short code: [song.Robj](https://1drv.ms/u/s!AtjLM4-mbBLkxot2ousqFFux-T81Zg?e=NTQUpU)
The Seurat Object is named as AllData, created in V2.

```r
library(Seurat)

load("song.Robj")

v2 <- AllData
v3 <- UpdateSeuratObject(AllData)

v3.meta.data <- v3@meta.data
v2.meta.data <- AllData@meta.data

v2.meta.data$orig.ident <- row.names(v2.meta.data)
v3.meta.data$orig.ident <- row.names(v3.meta.data)

a <- merge(v2.meta.data, v3.meta.data)

different <- a[which(a$nUMI!=a$nCount_RNA), ]
different
```

**Simply updated from a V2 Seurat object, there is a difference.**

![image](https://user-images.githubusercontent.com/14146871/92805963-d8cc7a00-f3b9-11ea-884d-bd86c27a565b.png)

**Comment by samuel-marsh** [comment]
Hi,

Are you just referring to the columns nGene and nUMI being renamed to nFeatures_RNA and nCount_RNA?  That is expected behavior and the new default in Seurat V3+.

If that is not the issue could you please clarify what is changing?

Best,
Sam

**Comment by duocang** [comment]
> Hi,
> 
> Are you just referring to the columns nGene and nUMI being renamed to nFeatures_RNA and nCount_RNA? That is expected behavior and the new default in Seurat V3+.
> 
> If that is not the issue could you please clarify what is changing?
> 
> Best,
> Sam
Hi sam,

This is Song.
Thanks. I think I referred them (updated my question). Can you please indicate how they behave in the new version?

**Comment by samuel-marsh** [comment]
Hi Song,

Thanks for clarifying.  Can you please also post the code you are running?

Best,
Sam

**Comment by duocang** [comment]
> Hi Song,
> 
> Thanks for clarifying. Can you please also post the code you are running?
> 
> Best,
> Sam

Hi Sam ,

there is a example now.

**Comment by samuel-marsh** [comment]
Hi,

Thanks for adding info.  Afraid I'm gonna have to defer to the Dev team here though.  Not sure exactly what is happening to cause that issue.

Best,
Sam

**Comment by mojaveazure** [comment]
First, the cells you're comparing are different. Seurat v2.X allowed a larger number of cells in the raw counts than in the normalized data slots. Seurat v3 restricts the counts and data slots to be the same size. If you look at just the cells common between the two, then the numbers are much closer, but still not the same.
![image](https://user-images.githubusercontent.com/11035068/92962036-4b7f3900-f43e-11ea-88dd-0312d365b212.png)

This can be explained in how we construct `Seurat` objects: when running `CreateSeuratObject`, we allow filtering based on the number features detected per cell (`min.genes`/`min.features`) and the features detected in a certain number of cells (`min.cells`). In Seurat v2.X, we calculated the nUMI and nGene before filtering, while v3.X calculates nCount and nFeature after. Providing values to the `min.cells` and `min.genes` parameters when creating the v2 object (as was recommended) would explain the  discrepancies between the nUMI/nCount and nGene/nFeature

**Comment by duocang** [comment]
> umbers are much closer, but still not the same.



> First, the cells you're comparing are different. Seurat v2.X allowed a larger number of cells in the raw counts than in the normalized data slots. Seurat v3 restricts the counts and data slots to be the same size. If you look at just the cells common between the two, then the numbers are much closer, but still not the same.
> ![image](https://user-images.githubusercontent.com/11035068/92962036-4b7f3900-f43e-11ea-88dd-0312d365b212.png)
> 
> This can be explained in how we construct `Seurat` objects: when running `CreateSeuratObject`, we allow filtering based on the number features detected per cell (`min.genes`/`min.features`) and the features detected in a certain number of cells (`min.cells`). In Seurat v2.X, we calculated the nUMI and nGene before filtering, while v3.X calculates nCount and nFeature after. Providing values to the `min.cells` and `min.genes` parameters when creating the v2 object (as was recommended) would explain the discrepancies between the nUMI/nCount and nGene/nFeature

Hi Mojaveazure,

I have realized the `min.genes`/`min.features` did not work (the `nGene` and `nUMI` do not change) even I assign a non-zero value to min.genes`/`min.features` in `CreateSeuratObject` (v2.X), you explain this is because nUMI and nGene  are calculated before the filtering functionality. Then where do I see the result after filtering functionality?

Can I consider nUMI/nCount and nGene/nFeature are identical with different names? If so, I still do not get whey the difference happens.

**Comment by duocang** [comment]
@mojaveazure 

Thanks! I see the difference comes from late filter. But why being late in V2 and not in V3?

Any reason for this?
