### ISSUE TITLE
difference in FindMarkers of V2 and V3.

### ISSUE THREAD

**Issue by duocang** [satijalab/seurat#3499]
Hi.

I did the process on one data in version V2 and V3. (identical data, identical processes )

I have checked Seurat_obj@metadata in V2 and V3. `nUMI`, `nGenes` in V2 and `nCount_RNA`, `nFeatures_RNA` are identical. 

`FindMarkers` behaves differently.

```
blob.markers.V2 <- FindMarkers(Data_in_V2, ident.1 = "blob")
dim(blob.markers.V2)
# [1]5846         5
```

```
blob.markers.V3 <- FindMarkers(Data_in_V3,  ident.1 = "blob")
dim(blob.markers.V3)
# [1]. 5336       5
```

**Comment by andrewwbutler** [comment]
Hi,

Are the cells defined as "blob" the same between `Data_in_V2` and `Data_in_V3`?
