### ISSUE TITLE
Stack multiple vlnplot with same x axis

### ISSUE THREAD

**Issue by MichaelPeibo** [satijalab/seurat#350]
Hi, I got two plotting issues:
1) is there any way to stack them in the same x axis? such as some paper shows? figure below
![image](https://user-images.githubusercontent.com/32219336/37212176-42b9c1fa-23e9-11e8-8f3b-b2cb9d644fdd.png)

2) is there any way to remove the mask the point  used for plot(I tried to adjust point size, but `point.size.use=0` did not work....)
 
any suggestion? quite new to R, is that available to adjust them with ggplot2?

Thanks in advance!

**Comment by leonfodoulian** [comment]
Hi Michael,

> is there any way to stack them in the same x axis? such as some paper shows?

I know that your first question has been already answered in another post where you asked the exact same question (see the answer of @AndyR2 in issue #300). But I will also give an answer here, as this is now posted as a separate issue. It is true that many arrange their figures in Adobe Illustrator. However, there are ways to do that in R, but require several lines of code. If you are new to R, simply opt the Illustrator option, as doing these figures in R might be quite complicated. 

> is there any way to remove the mask the point used for plot(I tried to adjust point size, but `point.size.use=0` did not work....)

Regarding your second question, this has been already asked at least 2 times now in earlier issues. For an answer, please check issues #264 and #304.

Have a good one!

Best,
Leon

**Comment by MichaelPeibo** [comment]
Hi Leon,
Thanks for help!

I am trying to understand some parameters in VlnPlot().
1) what is function of adjuest.use?
I plot with this code
`pdf('Vlnplot.test.pdf')
VlnPlot(object = mda.tsne.1.2.PC20,ident.include = c(0,1,2,3,4),nCol=1,features.plot = c("SPON1","SHOX2","SPP1", "LMX1A","CDKN2A"), point.size.use=NA,
           size.y.use = 2, adjust.use=2)

dev.off()`
![image](https://user-images.githubusercontent.com/32219336/37237386-73e99e6c-244d-11e8-905d-72558ce57365.png)


Also I tried to set it to 1
![image](https://user-images.githubusercontent.com/32219336/37237390-7a18f0b2-244d-11e8-8504-1c26c932a478.png)

One thing to change seems to be the shape, can you explain a little bit about that?

2) And I was unable to change the font size of y scale, y.size.use is not working.....

**Comment by AndyR2** [comment]
![cex in r font size change](https://user-images.githubusercontent.com/33207886/37237449-39927898-240b-11e8-9e5e-3bce88dcb4fa.JPG)

**Comment by MichaelPeibo** [comment]
Hi Andy,
Thanks for help.

But I was still unable to change the font size by `cex.axis`, it seems to be not working in VlnPlot, how should I deal with it?
I tried to change  `pointszie` in pdf, not changing....

**Comment by mojaveazure** [comment]
@MichaelPeibo VlnPlot uses ggplot2 graphics, not base R graphics. The instructions posted by Andy are for base R plots and will not work with ggplot2-based plots. To gain greater control over the output of VlnPlot, pass `do.return = TRUE` to capture the output. 

```R
plot <- VlnPlot(object = mda.tsne.1.2.PC20,ident.include = c(0,1,2,3,4),nCol=1,features.plot = c("SPON1","SHOX2","SPP1", "LMX1A","CDKN2A"), point.size.use=NA, size.y.use = 2, adjust.use=2)
```

You can then add graphical modifications to the `plot` object as you would any ggplot object. Please see ggplot2's [excellent documentation](http://ggplot2.tidyverse.org/reference/) to learn what you can do and how you can do it. To learn more about what VlnPlot can do and what its parameters are, please see that function's [documentation](https://www.rdocumentation.org/packages/Seurat/versions/2.2.0/topics/VlnPlot).

**Comment by MichaelPeibo** [comment]
Hi, @mojaveazure I tried export ggplpt2, still, it was challenging for me to figuring out the grammar (always reporting error...), but I highly recommend tune the plot with Adobe Illustrator, reaaaaaly amazing and simple for a R rookie!

**Comment by RajneeshSrivastava** [comment]
I think its there in Seurat v3. Try enabling stack = T, flip=T in your VlnPlot code.
Do cross check, what your active Idents is.. :)
