### ISSUE TITLE
How to reorder the cell types in DotPlot?

### ISSUE THREAD

**Issue by jiansongatnih** [satijalab/seurat#3500]
![image](https://user-images.githubusercontent.com/30295563/92857054-277e1200-f3c2-11ea-87b4-e8d2f07f255b.png)

# reorder clusters
obj2@active.ident <- factor(obj2@active.ident, 
                            levels=c("Memory CD4 T", 
                                     "Naive CD4 T",
                                     "CD14+ Mono", 
                                     "Memory B", 
                                     "Naive B", 
                                     "CD8+ T", 
                                     "CD8+ T: 2", 
                                     "NK", 
                                     "FCGR3A+ Mono", 
                                     "Platelet", 
                                     "DC"))

This was suggested in a closed thread. I tried it, but got the following error message:
 
> DotPlot(merged_combined, features = myFeatures, dot.scale = 2) + RotatedAxis()
Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) :
invalid character indexing

Any suggestion on how to fix it? Thanks!

**Comment by mojaveazure** [comment]
You should be using `levels<-` to reorder levels of a `Seurat` object rather than reconstructing the factor; the following works to reorder clusters

```R
library(Seurat)
data("pbmc_small")
DotPlot(pbmc_small, features = c('CD79A', 'MS4A1'))
levels(pbmc_small) <- c('1', '0', '2')
DotPlot(pbmc_small, features = c('CD79A', 'MS4A1'))
```

**Comment by vim15** [comment]
Hello, I am trying to do the above change using levels, on a multiome dataset. But when I do : 

`levels(test) <- c('X' , 'Y', 'Z')`

I get this error : 

`Error: NA's generated by missing levels
`

I've checked that all 15 levels used in the original object are also defined in the re-arrangment I want but still running into the same issue.
