### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by bwray** [satijalab/seurat#3501]
Just a heads up that over at https://satijalab.org/seurat/install.html it says that you need R 3.4.0 or later to install Seurat, but now it requires (I think) 3.6. It wasn't available for 3.5.0 (error: package ‘Seruat’ is not available (for R version 3.5.0)) and I was able to install it after an R update. Thanks for maintaining this package!

**Comment by andrewwbutler** [comment]
Hi,

Thanks for letting us know! The install page has been updated accordingly.
