### ISSUE TITLE
argument features of FindTransferAnchors does not behave as documented

### ISSUE THREAD

**Issue by dariomel** [satijalab/seurat#3502]
the documentation for the `features` argument of function `FindTransferAnchors` says

> Features to use for dimensional reduction. If not specified, set as variable features of the reference object which are also present in the query.

But the latter statement is only true when `normalization.method` is "SCT", as evident in the code:
https://github.com/satijalab/seurat/blob/c23845d26f7b1b3fd038e661f8d144ea1d4c81e0/R/integration.R#L595-L596

I'm not sure why such convenience is limited to the "SCT" case, but it would be less confusing if the code and the documentation were consistent. Personally, I would just swap those two lines of code.

**Comment by cdarby** [comment]
Thanks for your comment @dariomel . Actually, this line from `FindTransferAnchors` sets features to the VariableFeatures of the reference if features parameter is NULL (which is the default value). It is not restricted to the "SCT" case. 

https://github.com/satijalab/seurat/blob/c23845d26f7b1b3fd038e661f8d144ea1d4c81e0/R/integration.R#L588

The line you highlighted in the "SCT" branch makes sure the features are present in the query.

**Comment by dariomel** [comment]
the following code reproduces the issue:
```R
library(Seurat)
library(SeuratData)
data("panc8")
s=SplitObject(panc8,split.by="tech")
s=s[c("celseq","celseq2","fluidigmc1","smartseq2")]
s=lapply(s,function(s) {
    s=NormalizeData(s,verbose=F)
    FindVariableFeatures(s,selection.method="vst",nfeatures=2000,verbose=F) })
a=FindIntegrationAnchors(object.list=s[c("celseq","celseq2")],dims=1:30)
r=IntegrateData(anchorset=a,dims=1:30)
a=FindIntegrationAnchors(object.list=s[c("fluidigmc1","smartseq2")],dims=1:30)
q=IntegrateData(anchorset=a,dims=1:30,new.assay.name="int")
a=FindTransferAnchors(reference=r,query=q,npcs=30,dims=1:30)
```
```
Performing PCA on the provided reference using 2000 features as input.
Projecting PCA
Finding neighborhoods
Finding anchors
	Found 2522 anchors
Filtering anchors
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': error in evaluating the argument 'x' in selecting a method for function 't': invalid character indexing
```
The very helpful diagnostic message from R clearly indicates that error comes from function `FilterAnchors`,
https://github.com/satijalab/seurat/blob/c23845d26f7b1b3fd038e661f8d144ea1d4c81e0/R/integration.R#L2007-L2011 
The error goes away when changing the last function call as follows
```R
a=FindTransferAnchors(reference=r,query=q,npcs=30,dims=1:30,
 features=intersect(rownames(r),rownames(q)))
```
Omitting the argument `new.assay.name="int"` in the second call to `IntegrateData` also avoids the error.
