### ISSUE TITLE
Heatmap expression values do not appear to match VlnPlot or FeaturePlot 

### ISSUE THREAD

**Issue by atgustin** [satijalab/seurat#3503]
Hello and thank you for all the work to maintain and evolve this amazing package.  

I have a cluster of cells that according to VlnPlot and FeaturePlot are expressing a set of genes at comparable levels to other nearby clusters, but when i visualize these genes with DoHeatmap this cluster no longer appears to have comparable levels.  

In the images below, I am interested in cluster zero.  

By VlnPlot - and to some extent feature plot as well -  it appears that cluster zero expresses similar levels of three genes as are expressed in clusters 16, 3, and 20.  

However, when looking at the same three genes by heatmap, cluster zero looks quite different (to my eye).  

I thought that perhaps the number of cells with high expression of these genes could be much fewer in cluster zero, but when I utilize DotPlot, the visualization also appears to disagree with the heatmap.

My fear is that I've misinterpreted the Violin or Feature plots, and this is leading to my confusion regarding the heatmap.
I'd like to develop a deeper understanding of dos and don'ts for comparing and contrasting plots as those above, and any time and suggestions you can offer will be greatly appreciated.

Thank you!

Andrew 

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/37525448/92989126-9de44800-f486-11ea-8e63-cc6c5826521b.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/37525448/92989312-3a5b1a00-f488-11ea-8142-49d43554643f.png">

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/37525448/92989320-4c3cbd00-f488-11ea-9627-1f78af0a05fc.png">

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/37525448/92989453-62974880-f489-11ea-9aa3-e9fdfacbfd5a.png">

**Comment by cdarby** [comment]
Thanks for your question Andrew @atgustin . I believe what is causing the visual discrepancy is that VlnPlot and FeaturePlot use the "data" slot by default and DoHeatmap uses the "scale.data" slot by default. Note that the scale on the first two plots are 0 to 5 and the scale on the third plot is -2 to 2. Different data is being visualized in the heatmap.
