### ISSUE TITLE
GroupCorrelation function and some other

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#3504]
Dear Seurat Team,

There are some functions included in the package which are not well demonstrated anywhere in the vignettes. It may be best to include a vignette regarding these functions as sometimes the help page of these functions do not clearly demonstrate what we can do with these functions. I came across GroupCorrelation function today. Still trying to figure out how best it can be used to extract information from the data.
As always thanks for this amazing tool.
Saeed

**Comment by andrewwbutler** [comment]
Hi Saeed,

The `GroupCorrelation` function was written for the [spatial vignette](https://satijalab.org/seurat/spatial_vignette.html) and is demonstrated in the dropdown section "How do results compare to log-normalization?". We found it useful here to look at how the normalized gene expression values  under different normalization schemes correlated with the number of UMIs (with the genes also grouped into broad expression expression bins). This essentially allows you to quickly run one of the analyses in the original [sctransform paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1#Sec2) - Fig 3c - but could be useful in more general contexts as well.
