### ISSUE TITLE
DimPlot of multiple group.by parameters - removing axes and legend

### ISSUE THREAD

**Issue by GreenGilad** [satijalab/seurat#3506]
When I try to plot a DimPlot with multiple `group.by`s only the last has no legend and no axes. The rest have them both

`DimPlot(subsample, group.by = c("column1","column2"), label=T) + NoLegend() + NoAxes()`

**Comment by samuel-marsh** [comment]
Hi,

The reason is that combined plots use patchwork package to plot them together.  Instead of using the `+` syntax from ggplot2 you can use the `&` syntax from patchwork.

`DimPlot(subsample, group.by = c("column1","column2"), label=T) & NoLegend() & NoAxes()`

Best,
Sam
