### ISSUE TITLE
How can we get baicode lasso in the HoverLocator

### ISSUE THREAD

**Issue by zh-Bian** [satijalab/seurat#3507]
the HoverLocator could use lasso to select cell easily, but how can we get the barcode of these selected cells. The function CellSelector() just has rectangle, it is not smooth and convenient.
Thank you ! @zeehio @troels

**Comment by mojaveazure** [comment]
`CellSelector` is implemented as a Shiny gadget, which does not have support for lasso selection. We are evaluating extension packages that will enable lasso selection, but do not yet have a working solution.

**Comment by denvercal1234GitHub** [comment]
Hi @mojaveazure - Is there any update on this feature? Also, the `CellSelector` does not work when I set `split.by` for `DimPlot()`

**Comment by vagabond12** [comment]
@mojaveazure  Hello, and you have not answer the question that how can we get the barcode of these selected cells  with  HoverLocator. Thank you.

**Comment by zhangdudu0** [comment]
@vagabond12 应该不可以选择的，因为HoverLocator是基于plotly写的，plotly不能返回

**Comment by zhangdudu0** [comment]
应该不可以选择的，因为HoverLocator是基于plotly写的，plotly不能返回
