### ISSUE TITLE
idedifiny mitochanrial genes with PercentageFeatureSet(XXX, pattern = "^mt-")

### ISSUE THREAD

**Issue by keksundso** [satijalab/seurat#3508]
Hello,
I am analyzing a single nuclei RNAseq and was surprised about the high amount of mitochondrial genes in my droplets (not a high percentage but still around 10-100 barcodes are associated with more than 20% mt-RNA.)

Now I was wondering what I am determining here. As far as I understand, it filters for all genes with a "mt-"prefix, which should be all genes ["residing on the mitochondria"](http://www.informatics.jax.org/mgihome/nomen/gene.shtml). However, what about genomic regions which are transferred from the mitochondria to the nucleus. Do those genes have a "mt-" Prefix, and if they would, could this quantitatively influence the amount, or is this negligible. 

Although, this is probably not the best place to ask this, thanks in advance.

**Comment by timoast** [comment]
Nuclear-encoded genes with homology to the mitochondrial genome do not start with the "MT-" prefix
