### ISSUE TITLE
trouble loading my dataset into Seurat 

### ISSUE THREAD

**Issue by catherine0521** [satijalab/seurat#3509]
I'm trying to analyze a textfile of scRNA seq data that's already in the genes x cell format,  not the 3 separate barcodes, genes, and then matrix input that the Seurat tutorial uses. 

I tried creating a Seurat object using the same code template as the tutorial, inserting my input genes x cell text file (named "Joost.data") as such: Joost <- CreateSeuratObject(counts = Joost.data)

However, while upon first glance, my Seurat object (which I named Joost)  has the same properties as the tutorial pbmc Seurat object, when I try to proceed with later steps in the tutorial, something is clearly wrong,
<img width="426" alt="Screen Shot 2020-09-14 at 5 12 46 PM" src="https://user-images.githubusercontent.com/71292992/93138781-89ce5f80-f6ad-11ea-861f-dd78dc93504a.png">

<img width="616" alt="Screen Shot 2020-09-14 at 5 13 08 PM" src="https://user-images.githubusercontent.com/71292992/93138795-98b51200-f6ad-11ea-87eb-4a3e0155d5e4.png">

**Comment by cdarby** [comment]
In the image you posted of the meta.data, it looks like the cell names are V1, V2 ... This suggests you may not have accounted for the first row/column of the matrix containing cell and/or gene names when reading in the file to make the "Joost.data" object. Check the rownames and colnames attributes of the "Joost.data" object and ensure they are the names you expect and not defaults.
