### ISSUE TITLE
object@raw.data instead of object@data as input to NormalizeData()

### ISSUE THREAD

**Issue by leonfodoulian** [satijalab/seurat#351]
Hello Rahul,

I just realised that `Seurat::NormalizeData()` takes `object@raw.data` as input rather than `object@data` (code at [lines 273 to 293 in preprocessing.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/preprocessing.R#L273-L293)). Is there any reason why this is the case? The reason why I'm asking is that the `object@data` that is created during `Seurat::CreateSeuratObject()`, and onto which many of the quality checks are run, is therefore meaningless. Moreover, setting to 0 all counts below the expression threshold (see [lines 76 to 82 in preprocessing.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/preprocessing.R#L76-L82)) is important for me as it removes a lot of noise in my data. But if normalisation is performed on the raw data, I end up keeping this noise in my expression matrix. Could you please elaborate on why the `@raw.data` instead of the `@data` slot is used for normalisation?

Thank you in advance!

Best,
Leon

**Comment by satijalab** [comment]
We view object@raw.data as a storage slot for the non-normalized data, upon which we perform normalization and return object@data. 

For the threshold problem you describe, you can either modify the raw data slot (which sets a threshold on the non-normalized reads) as you show in the code, in which case the modified counts will propogate through normalization.

Alternately, if you want to threshold on normalized counts, you can just write a few lines of code to modify object@data manually. Hope that helps!

**Comment by leonfodoulian** [comment]
Hi Rahul,

Thank you for your answer! I figured that maybe the best solution would be to filter out genes before creating the Seurat object, and then set `is.expr` to 0. 

Best,
Leon
