### ISSUE TITLE
Suppress peak at zero in Ridge Plots

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#3510]
Hi there,

Is there a way to suppress the peak at zero expression in a typical RidgePlot in Seurat?  Sometimes, for certain genes, I get a large peak at zero, which overshadows the other peaks.  It will be great to suppress the peaks at zero if possible.

Thanks!

![plot](https://user-images.githubusercontent.com/12577720/93148511-f7848680-f6c1-11ea-9ba8-7e18c8937e1c.jpg)

**Comment by timoast** [comment]
The ridge plot is a density plot, so removing the points at zero would artificially change the density distribution. If you're finding this is a problem you could explore other visualisation methods (VlnPlot for example)
