### ISSUE TITLE
Spatial experiments: estimate cell number per spot

### ISSUE THREAD

**Issue by sdwien** [satijalab/seurat#3512]
Dear all,
I was wondering if anyone has tried yet to integrate information from image analysis such as number of nuclei per spot into the analysis of Visium spatial data, such as using it for normalization of expression levels between spots?
I imagine that the number of nuclei information could be added in a new slot of the Seurat object and then plotted in a SpatialFeaturePlot.
Do you have any experience or ideas regarding this?
Best, Sophia

**Comment by cdarby** [comment]
Thanks for your question, Sophia @sdwien . You can definitely add external metadata to visualize using SpatialFeaturePlot (or using any other visualization function that groups by or plots metadata). Just use the `AddMetaData` function in Seurat to add the data to a Seurat object. Then specify that metadata column name as the `features` parameter in SpatialFeaturePlot.
