### ISSUE TITLE
Spatial experiments: "Neighbour" cells and spot coordinates

### ISSUE THREAD

**Issue by sdwien** [satijalab/seurat#3513]
Dear all,
another biological question that one might want to answer as part of a Visium spatial transcriptomics experiment, would be whether the "neighbour" spots of selected spots (e.g. selected based on expression of a marker gene) have something in common (basically a study of certain microenvironments inside the tissue).
I assume one would have to make use of the spot coordinates here. So far, I have managed to extract several types of coordinates:
```
# spot barcodes and coordinates for “slice1” are stored inside the Seurat object:
head(a1control1spatial@images$slice1@coordinates, 4)
                   tissue row col imagerow imagecol
AAACAAGTATCTCCCA-1      1  50 102     7835     9247
AAACAGCTTTCAGAAG-1      1  43   9     6909     2070
AAACCCGAACGAAATC-1      1  45 115     7162    10248
AAACCGGGTAGGTACC-1      1  42  28     6772     3536
# different function, different coordinates:
head(GetTissueCoordinates(a1control1spatial), 4)
                   imagerow  imagecol
AAACAAGTATCTCCCA-1 376.3510 444.17582
AAACAGCTTTCAGAAG-1 331.8710  99.43159
AAACCCGAACGAAATC-1 344.0237 492.25844
AAACCGGGTAGGTACC-1 325.2902 169.85030
```
In the first case, there are spot row and column coordinates, as well as - I assume - image coordinates in pixels (?) of the spot centers (?) .
I also understood from another post that the coordinates from GetTissueCoordinates are the ones used for plotting the SpatialFeaturePlots aso. They are quite different from the imagerow and imagecol coordinates, though.

For the purpose of extracting all "neigbour" spots for a cluster of interest, I would prefer to use the spot row and column coordinates. I would probably proceed as follows (if possible):
1. Subset the cluster of interest to a separate Seurat object
2. Extract barcodes and coordinates from this Seurat object
3. Generate a matrix of row and column coordinates for the neighbour spots starting from the coordinates of the spots of the Seurat object, neighbour being defined as same row as the spot in the object plus/minus one column or same column as the spot in the object plus/minus one row (not sure about the shift of coordinates between rows).
4. Extract from the original Seurat object the barcodes based on the neighbour spot coordinates from step 3 and make a new cluster out of them.
5. Plot both the original cluster of interest and the cluster of neighbours and analyse their expression profiles.

Not sure which Seurat functions or custom R code would be most suitable for each of these steps. I have not worked through all the tutorials yet, so please feel free to refer me to any of them if some of these steps are covered in one of them.
Any comments and suggestions are most welcome!
Many thanks for this very comprehensive and up-to-date tool.

Best,
Sophia

**Comment by FranziChiara** [comment]
Hi Sophia,
Have you found a way to access the spots?
I am dealing with a similar problem and would be glad for suggestions.
Thank you!

**Comment by sdwien** [comment]
Dear @FranziChiara  ,
I have looked at several possibilities, including the "neighbourhood" function from the STUtility package:
https://ludvigla.github.io/STUtility_web_site/Neighborhood.html
I have not had the occasion and the datasets for exploring this any further, but I keep watching out for new tools and for new functionalities of existing tools to make this type of analysis more straight forward.

So if anyone from the Seurat team or someone working with similar research questions has a nice workflow example, I would be happy to read about it.

Best, Sophia

**Comment by ayusyarif** [comment]
Hi,
I know that you can manually select the region of interest using the SPATA2 package. it is quite easy with the tutorial in their webpage. 
https://themilolab.github.io/SPATA2/

Best,
Ayu

**Comment by Gesmira** [comment]
Hi all, 
Closing this issue as it has been a while since it has been opened. If you continue to run into problems with the newer versions of Seurat or the suggested packages by @ayusyarif do not solve your issues, please feel free to reopen.

**Comment by rajdeepjha17** [comment]
Hi, I have been trying to get coordinates of a particular region of interest using SPATA2 (as @ayusyarif, was kind enough to point to), but I keep getting this error. Anyway to fix this?  

```
> asSPATA2(WT4, sample_name = "WT4", spatial_method = "Unknown", image_name = "Slice")
20:57:48 Setting up new `spata2` object.
20:57:48 Transferring data.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘asHistologyImaging’ for signature ‘"SlideSeq"’
```

Can anyone help me use this package on my CurioSeeker data? Any help would be highly appreciated!!

**Comment by ayuhutamisyarif** [comment]
You 

> Hi, I have been trying to get coordinates of a particular region of interest using SPATA2 (as @ayusyarif, was kind enough to point to), but I keep getting this error. Anyway to fix this?
> 
> ```
> > asSPATA2(WT4, sample_name = "WT4", spatial_method = "Unknown", image_name = "Slice")
> 20:57:48 Setting up new `spata2` object.
> 20:57:48 Transferring data.
> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘asHistologyImaging’ for signature ‘"SlideSeq"’
> ```
> 
> Can anyone help me use this package on my CurioSeeker data? Any help would be highly appreciated!!

Hi, 

do you have 10X Visium data? I found loupe browser better than SPATA in terms of manual annotation.

Best, 
Ayu
