### ISSUE TITLE
How to resolve Issue with PercentageFeatureSet of calculating/visualizing mitochondrial percentages

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#3514]
Hello! I encountered a problem in my 2 Seurat datasets/objects. Below, I showed the head() of these 2 datasets, and the violinplot after calculating the percentage of mitochondrial genes. The first dataset looks normal, but the second one looks weird (the x-axis became consisted of multiple datapoints!) Kindly help, your advice is greatly appreciated!
------------------------------------------------------------------------------------------------------------------------------------------------------
```
TCS <- CreateSeuratObject(counts = data_TCS, min.cells = 3, min.features = 200)
TCE <- CreateSeuratObject(counts = data_TCE, min.cells = 3, min.features = 200)
rm(data_TCS, data_TCE)

TCS$group <- "TCS"
TCE$group <- "TCE"

TCS[["percent.mt"]] <- PercentageFeatureSet(TCS, pattern = "^MT")
TCE[["percent.mt"]] <- PercentageFeatureSet(TCE, pattern = "^MT")
    pTCS <- VlnPlot(TCS, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol=3)
    pTCE <- VlnPlot(TCE, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol=3)
    pTCS
    pTCE
```

![image](https://user-images.githubusercontent.com/68268222/93356056-50dee800-f871-11ea-801f-e6709a7bd5a7.png)

![image](https://user-images.githubusercontent.com/68268222/93355826-0fe6d380-f871-11ea-9f0c-92f5271e89a0.png)

![image](https://user-images.githubusercontent.com/68268222/93355699-eded5100-f870-11ea-871d-2b7e6bec37d5.png)

**Comment by samuel-marsh** [comment]
Hi,

The reason is that the first Seurat object has just one value for `orig.ident` while the second object has many different values.  The violin plot just plots the mito percent x `orig.ident` on x-axis by default.  Can't specifically say why it's different between the two objects without knowing the code you ran to generate the data_TCS and data_TCE objects and what that raw data looks like.

Best,
Sam

**Comment by levinhein** [comment]
Hello, Sam. The data_TCS and data_TCE objects are just generated from reading the text/csv file of the gene expression data (code as shown below).

Is it okay if I (a) delete the column `orig.ident` or (b) just change this column into all the same thing? Is this olay or this will affect downstream analysis/applications?

```
#Read scRNAseq expression data
data_TCS <- read.table(file = "tpm_all_scp.txt.gz", sep = "\t", header=TRUE, row.names=1) #FILE.TXT - TPM data
data_TCE <- read.csv(file = "tumor_tpm.csv.gz", sep = ",", header=TRUE, row.names=1) #FILE.CSV - TPM data

# Create Seurat object, with filtering
TCS <- CreateSeuratObject(counts = data_TCS, project= "TCS.16K", min.cells = 3, min.features = 200)
TCE <- CreateSeuratObject(counts = data_TCE, project= "TCE.7K", min.cells = 3, min.features = 200)
```

**Comment by cdarby** [comment]
To set the Idents of a Seurat object to all the same thing, use the Idents function 
`Idents(TCS) <- "default"`
This will set the Idents all to the string "default" (unless you have a metadata column with the name "default", in which case, use a different string.)

**Comment by levinhein** [comment]
Thanks for this helpful tip @cdarby! Do you think this will affect further downstream analysis if I change the `orig.ident` column?

**Comment by cdarby** [comment]
As long as you set the Idents appropriately for each analysis you do, there shouldn't be an issue. Setting Idents does not change the orig.ident metadata column, and changing the orig.ident metadata column does not change the Idents.

**Comment by levinhein** [comment]
Hi @cdarby. It worked! Thank you so much for your help, I'm very happy! You are the best! 

`> pTCS
`![image](https://user-images.githubusercontent.com/68268222/95021290-b4a34680-06a2-11eb-8736-4954252783b4.png)

`> pTCE
`![image](https://user-images.githubusercontent.com/68268222/95021305-d43a6f00-06a2-11eb-8c16-fd40e145801c.png)
