### ISSUE TITLE
Installing Seurat 2.3.4

### ISSUE THREAD

**Issue by hugokitano** [satijalab/seurat#3516]
Hi, I am running into a problem installing Seurat 2.3.4 because of this orphaned dependency. The up to date version of Seurat works, but unfortunately does not run on the codebase I'm trying to use. Unfortunately, it doesn't work whether I change the dependencies parameters. Any quick workarounds?

(This post is similar to https://github.com/satijalab/seurat/issues/2377)

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Does installing old source package of SDMTools from CRAN archive solve the issue?  
[https://cran.r-project.org/src/contrib/Archive/SDMTools/](https://cran.r-project.org/src/contrib/Archive/SDMTools/)

best,
Sam

**Comment by hugokitano** [comment]
This works! Thank you!
