### ISSUE TITLE
shall I NormalizeData before IntegrateData ?scaleData after IntegrateData? 

### ISSUE THREAD

**Issue by docjim86** [satijalab/seurat#3517]
Cause FindIntegrationAnchors will implement scaling and normalization. So shall I NormalizeData before IntegrateData ?
And scaleData after IntegrateData? 
I did the following and got quite few markers from FindMarkers(intg_wt_ko,ident.1 = "Astrocytes_WT",ident.2 = "Astrocytes_KO",verbose = F). So any step went wrong? Thanks in advance!

```
WT <- NormalizeData(WT,verbose = F)
WT <- FindVariableFeatures(WT,selection.method = "vst",nfeatures = 2000)
VlnPlot(WT,features = c("nFeature_RNA","nCount_RNA","percent.mt"),ncol = 3)
KO <- NormalizeData(KO,verbose = F)
KO <- FindVariableFeatures(KO,selection.method = "vst",nfeatures = 2000)
wt_ko.integrated.anchors <- FindIntegrationAnchors(object.list = list(WT,KO),dims = 1:20)
intg_wt_ko <- IntegrateData(wt_ko.integrated.anchors,dims=1:20)
```

**Comment by timoast** [comment]
What assay did you use for `FindMarkers()`?

**Comment by docjim86** [comment]
Thanks for your reply,  @timoast . And here are my codes, and that mostly followed the guides from "https://satijalab.org/seurat/v3.0/immune_alignment.html". I pass the "intg_wt_ko" subject to FindMarkers() in the for loop. Thank you for further reply. Best regards.

`WT <- NormalizeData(WT,verbose = F)
WT <- FindVariableFeatures(WT,selection.method = "vst",nfeatures = 2000)
KO <- NormalizeData(KO,verbose = F)
KO <- FindVariableFeatures(KO,selection.method = "vst",nfeatures = 2000)
wt_ko.integrated.anchors <- FindIntegrationAnchors(object.list = list(WT,KO))
intg_wt_ko <- IntegrateData(wt_ko.integrated.anchors)
DefaultAssay(intg_wt_ko) <- "integrated"
intg_wt_ko <- ScaleData(intg_wt_ko,verbose=F)
intg_wt_ko <- RunPCA(intg_wt_ko,npcs=20,verbose=F)
intg_wt_ko <- RunUMAP(intg_wt_ko,reduction="pca",dims=1:20,verbose = F)
intg_wt_ko <- RunTSNE(intg_wt_ko,dims=1:20)
intg_wt_ko <- FindNeighbors(intg_wt_ko,reduction="pca",dims=1:20)
intg_wt_ko <- FindClusters(intg_wt_ko,resolution=0.8)
celltype <- data.frame(ClusterID=rownames(cellpredict), celltype=cellpredict$labels, stringsAsFactors = F)
celltype   # clusterID---celltype
write.csv(celltype,file = "clusterID_cellType.csv",quote = F,row.names = F)
refData <- MouseRNAseqData()   
ex_data <- GetAssayData(intg_wt_ko)
intg_clusters <- intg_wt_ko@meta.data$seurat_clusters
cellpredict <- SingleR(test = ex_data,ref = refData,method = "cluster",labels = refData$label.fine,clusters = intg_clusters,
                       assay.type.test = "logcounts",assay.type.ref = "logcounts")
celltype <- data.frame(ClusterID=rownames(cellpredict), celltype=cellpredict$labels, stringsAsFactors = F)

for (i in 1:nrow(celltype)) {
  intg_wt_ko@meta.data[which(intg_wt_ko@meta.data$seurat_clusters==celltype$ClusterID[i]),"celltype"] <- celltype$celltype[i]
}
celltype_14 <- unique(intg_wt_ko@meta.data$celltype)
DefaultAssay(intg_wt_ko) <- "RNA"

Idents(intg_wt_ko) <- paste(intg_wt_ko$celltype,intg_wt_ko$group,sep = "_")
cell_num <- as.data.frame(unlist(lapply(CellsByIdentities(intg_wt_ko), length)))
write.csv(cell_num,file = "cell_num_intg.csv",quote = F)


for (clltyp in celltype_14){
  clltyp.wt <- paste0(clltyp,"_WT")
  clltyp.ko <- paste0(clltyp,"_KO")
  DEG_filename <- paste0(str_replace(clltyp," ","-"),"_DEG.csv")
  DEG_markers <- FindMarkers(intg_wt_ko,ident.1 = clltyp.ko,ident.2 = clltyp.wt,verbose = F)
  DEG_sig <- DEG_markers[DEG_markers$p_val_adj<0.05,]
  write.csv(DEG_sig,file = DEG_filename,quote = F)
  print(c(clltyp,":",dim(DEG_sig)[1]))
  }

`

**Comment by timoast** [comment]
Ok so you use the RNA assay. The code here looks fine to me, so it doesn't look like there is any obvious technical reason why you don't find many differentially expressed genes between certain celltypes for WT and KO conditions

**Comment by docjim86** [comment]
> Ok so you use the RNA assay. The code here looks fine to me, so it doesn't look like there is any obvious technical reason why you don't find many differentially expressed genes between certain celltypes for WT and KO conditions

thanks!
