### ISSUE TITLE
Violin plot X axis

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#3518]
Hi! I was following the [guided clustering tutorial](https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html) and I was wondering how cells are ordered on the X axis of the violin plot and if their position on that axis has any meaning:
![image](https://user-images.githubusercontent.com/57805802/93471690-faff5400-f8f3-11ea-8cc9-8a868c4fa4b4.png)

Thanks for your work, I'm enjoying your software so far!

**Comment by cdarby** [comment]
No, the x-axis position is not meaningful and is only for visual effect 

(see https://ggplot2.tidyverse.org/reference/geom_jitter.html for more information on implementation)
