### ISSUE TITLE
Dotplot issue//Error: None of the provided identity class levels were found

### ISSUE THREAD

**Issue by chewla** [satijalab/seurat#3519]
I am having some issues with output from the dotplot function, but the error is inconsistent. I was able to successfully output my plot multiple times, but now it is showing the following error: None of the provided identity class levels were found. I thought maybe the proper library/packages were not loaded, but that didn't resolve the issues. any other possible suggestions? (Other functions that utilize my "object.integrated" are working just fine...) Thanks so much.

Idents(object.integrated) <- factor(Idents(object.integrated), levels = c("Cluster 0", "Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Cluster 5", "Cluster 6", "Cluster 7", "Cluster 8", "Cluster 9", "Cluster 10"))
markers.to.plot <- c("Cst3", "Selplg", "Jun", "Rhob", "Hmox1" , "Ifrd1", "H2-Eb1", "Apoe", "Ifit3", "Rtp4", "Cst7" , "Lgals3" , "Stmn1" , "Hmgb2", "Cxcl1", "Ccl7", "Pdc", "Rom1")

dot <- DotPlot(object.integrated, features = markers.to.plot, cols = c("blue", "red"), dot.scale = 5, split.by = "condition") + RotatedAxis()

**Comment by cdarby** [comment]
Thanks for your question @chewla . I suspect in the course of your manipulating the "object.integrated" object, `Idents(object.integrated)` were changed. If the metadata column containing the desired Idents is named "cluster" for example, you can set it as the Idents again using `Idents(object.integrated) <- "cluster"`.
