### ISSUE TITLE
Error in installing Seurat 2.2.0

### ISSUE THREAD

**Issue by ozgeevrim82** [satijalab/seurat#352]
Hi,
I want to use version 2.2.0 but having errors in installing it. This is the whole error message:
```
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Seurat.so] Error 1
ERROR: compilation failed for package ‘Seurat’
* removing ‘/Users/ozgetasdemir/Library/R/3.3/library/Seurat’
* restoring previous ‘/Users/ozgetasdemir/Library/R/3.3/library/Seurat’
Installation failed: Command failed (1)
```

Thanks in advance for any help!

**Comment by mojaveazure** [comment]
It looks you're missing your Fortran library. Try reinstalling R and your compilers as mentioned in #92 

You also may want to upgrade your operating system from OS X Mavericks to a more modern version of macOS, preferably Sierra or High Sierra but at the very least to El Capitan. This will allow you to use CRAN's precompiled binaries for Seurat 2.2.1, making the installation process much easier and faster.

**Comment by ozgeevrim82** [comment]
Thank you! This solved my problem.
