### ISSUE TITLE
Plotting multiple genes in the same FeaturePlot

### ISSUE THREAD

**Issue by Sergio-ote** [satijalab/seurat#3521]
Hi everyone!
I am using some small gene signatures (3-5 genes) to identify populations in my dataset using FeaturePlot(). I would like to get a plot like this one https://www.nature.com/articles/s42003-020-0922-4/figures/1 (Figure 1c), but so far I have not managed to sort it out.

I have already checked the Seurat visualization vignette, the option for 2 genes mentioned in #1343 (not suitable for more than 2 genes) and the average mean expression mentioned in #528. This last option would be fine, but I get a lot of noise in clusters that are unimportant for my signature because i.e. I get 3 very specific markers that are expressed only in my cluster of interest, but the 4th one is expressed in high levels in this specific cluster but in low levels in the rest of the clusters. When I plot I obtain a messy FeaturePlot where all the clusters look similar.

Is there a way to obtain this kind of plot using Seurat, or do I need another package? Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I would try and see if using module scores would accomplish what you are trying to do.  `AddModuleScore` can be used to see if expression of given gene set is enriched vs set of randomly selected (but based on expression bins) control genes.  This might help to clean up the plot as it sounds like the enrichment of the whole gene set would likely be cell type specific whereas one particular gene might also be expressed in other cell types.

Best,
Sam

A basic workflow would be something like:
```
cell_typeA_marker_gene_list <- list(c("Gene1", "Gene2", "Gene3", "Gene4"))
object <- AddModuleScore(object = object, features = cell_typeA_marker_gene_list, name = "cell_typeA_score")
FeaturePlot(object = object, features = "cell_typeA_score1")
```
*Note that gene list for `AddModuleScore` must be supplied in list class or coerced as part of function to list otherwise score will be created for each gene and not the gene set.  
Also note that you must add "1" to the end of whatever name you provided in `AddModuleScore` as this is automatically appended to the name provided in the new metadata column which stores the score.*

**Comment by Sergio-ote** [comment]
Thank you very much Samuel! I think you solved my problem. Could this approach be used for larger gene signatures? What are the limitations that I should be aware of?

**Comment by samuel-marsh** [comment]
HI,

You definitely can use for larger gene sets but I think getting too big could be an issue for couple reasons.  For one, given the sparsity of single cell data if your gene set is too large then it may not appear enriched via module score when biologically it may be.  The inverse is of course also true if your gene set is too small, then the number of cells with enriched scores may be too high.  If you want to know more about the method I suggest reading the original paper and methods that the function is derived from (Tirosh et al., 2016; see manual entry for more details).

Best,
Sam

**Comment by Yale73** [comment]
@samuel-marsh Hi,

I used exactly the same code as yours but found no matter how many genes I used, I got the same plot. Do you run the same issue or not? If not, can you help me with it?

This one used 50 genes
![50 genes](https://user-images.githubusercontent.com/50378244/129143343-13a1e5f4-31a2-47e1-896e-6aad158cdc46.png)

This one is 3 genes
![3-gens](https://user-images.githubusercontent.com/50378244/129143384-d01c41e9-f0b2-49e9-aa2a-41cbd44d5fd3.png)

Thanks,
Yale

**Comment by samuel-marsh** [comment]
Hi Yale,

Can you post the exact code that you ran for ID1 with either 50 or 3 genes?

Thanks,
Sam

**Comment by ksaunders73** [comment]
Heyo @Yale73! I am a noobie so take my word with a grain of salt heh, but maybe try setting min.cutoff and max.cutoff the same between your lists and see if that helps?

**Comment by Yale73** [comment]
@samuel-marsh 
The code for 3 genes
```
IL17_signature_gene_list <- list(c("CXCL13", "IL17F", "CCR6"))
object <- AddModuleScore(object = our, features = IL17_signature_gene_list, name = "ID")
FeaturePlot(object = our, features = "ID1", order=T)+
  scale_color_viridis(discrete = FALSE, option="turbo")
```

50 genes
```
IL17_signature_gene_list <-list(c("CXCL13","MTRNR2L12", "CD7", "MGAT4A", "FTH1", "LAYN", 
                                   "IL17F", "KLRB1", "GNLY", "CPM", "CTSH", "GBP5", "CLEC2B",
                                   "SOX4","GZMB","CD2","CEBPD", "ODF2L","LAG3", "LRRN3",
                                   "ARHGEF12","PTPN13","TNFAIP3","TRPS1","SNX9","METRNL","BTG1", 
                                   "JUN","TMIGD2", "SPOCK2","GABARAPL1","PMEPA1","HIST1H1E","RBPJ",
                                   "LINC01871","MAP3K4", "H1FX", "UBC","GALNT1","PNRC1","MUC20-OT1",
                                   "RPS26","GABPB1-AS1","CHN1","NAP1L4","PTMS", "F2R","DAPK2",
                                   "CTLA4","CCR6"))

object <- AddModuleScore(object = our, features = IL17_signature_gene_list, name = "IL17_signature_gene_list")
FeaturePlot(object = our, features = "IL17_signature_gene_list1", order=T)+
  scale_color_viridis(discrete = FALSE, option="turbo")
```
Today, when I reran the 50 one, I got an error: 

```
Error: None of the requested features were found: IL17_signature_gene_list1 in slot data
In addition: Warning message:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: IL17_signature_gene_list1
```

Thanks,
Yale

**Comment by Sergio-ote** [comment]
Hi  @Yale73,
you are saving the results of AddModuleScore() in the object "object" but then using the object "our" as an input for FeaturePlot(). Try with FeaturePlot(object = **object**, features = "IL17_signature_gene_list1"). Hope that solves your issue.

Best,
Sergio

**Comment by Yale73** [comment]
Hi @Sergio-ote,

Thanks for your response. It's the error used "object = object", I used the same object in my code. Please see the following and above code. 

```
object <- AddModuleScore(object = our, features = IL17_signature_gene_list, name = "IL17_signature_gene_list")
FeaturePlot(object = our, features = "IL17_signature_gene_list1", order=T)+
  scale_color_viridis(discrete = FALSE, option="turbo")
```

The issue is the list features are not added by` AddModuleScore()`.

Thanks,
Yale

**Comment by Yale73** [comment]
@Sergio-ote Hi,
You are totally right, I didn't notice I used object to` AddModuleScore()`. 
Now it works. Thanks for your help.

All the best,
Yale

**Comment by jimena2** [comment]
Has anyone encountered this error when trying this?

I ran this

```
cell_typeA_marker_gene_list <- list(c("Gene1", "Gene2", "Gene3", "Gene4"))
object <- AddModuleScore(object = object, features = cell_typeA_marker_gene_list, name = "cell_typeA_score")
FeaturePlot(object = object, features = "cell_typeA_score1")
```

and got:

```
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'
```

after trying to define object

**Comment by haseebz** [comment]
Did you try changing the `DefaultAssay(object) <- "RNA"`

**Comment by alexvnesta** [comment]
Same issue as jimena2 here:

> DefaultAssay(seurat_object) <- "RNA"
> cell_typeA_marker_gene_list <- list("KRT18", "KRT19", "KRT18", "KRT18")
> seurat_object <- AddModuleScore(object = seurat_object, features = cell_typeA_marker_gene_list, name = "cell_typeA_marker_gene_list")
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'


SessionInfo says Seurat_4.3.0

**Comment by jimena2** [comment]
@haseebz this worked for me, thank you!

**Comment by mtekman** [comment]
I was still getting the error about population size, but nothing in the thread worked. What did work was playing with the ctrl parameter.

```
sm <- AddModuleScore(sm, features = list(in_genes), name = "EMT_sig", ctrl = 50)
```
