### ISSUE TITLE
convert Seurat to loom error

### ISSUE THREAD

**Issue by latercomer** [satijalab/seurat#3523]
Hi,
     I want to convert Seurat to loom by as.loom, but I received an error report:
"Error in UpdateSlots(object = object) : object 'object' not found"
     How can I solve this problem？
     Thank you!

> cluster_iden
An object of class Seurat
17821 features across 81523 samples within 1 assay
Active assay: RNA (17821 features)
 3 dimensional reductions calculated: pca, tsne, umap

> cluster_iden_loom<-as.loom(x=cluster_iden)
Error in UpdateSlots(object = object) : object 'object' not found

**Comment by timoast** [comment]
What version of Seurat are you using? This appears to be fixed on the current release: https://github.com/satijalab/seurat/blob/master/R/objects.R#L2259

Also note that the `as.loom` functionality is being moved to [SeuratDisk](https://github.com/mojaveazure/seurat-disk)
