### ISSUE TITLE
Using dropEst output for Seurat

### ISSUE THREAD

**Issue by ADvorkinGheva** [satijalab/seurat#3524]
Greetings,

I have obtained some scRNAseq data from a repository and the data are in count.matrices.rds files, which appear to be created using dropEst with "-V" option, so each file contains "exon", "intron" and "spanning" (exon/intron spanning) lists of counts.
I was wondering if you could advise me on how to turn these lists into a Seurat object? I am used to have "counts", so I'm not sure how to obtain such data from these 3 lists - do I merge them and then use as.Seurat function to turn the result into a Seurat object? If so, how should I merge them?

Thank you very much for your help and advice!

Regards,
Anna

**Comment by levinhein** [comment]
Hi @ADvorkinGheva How did you proceed processing this? I downloaded public data with similar exon, intron, spanning ...count matrix data. I couldn't find exactly where on Seurat website a way to process this. Could you share how? Thank you!
