### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

### ISSUE THREAD

**Issue by aleksandrPi** [satijalab/seurat#3526]
I am having this error, when trying to do FindTransferAnchors on my scATAC with a published .rds from NCBI. Interestingly, if I do the same with my own scRNA data, there is no such problem. The problem persists both with the current and devel versions of Seurat, and only finally worked after down-grading to Seurat 3.1.1, however, this version is said to be incompatible with Signac v1.0, so not a solution for the time being... Any recommendations?

**Comment by andrewwbutler** [comment]
Hi,

Are you able to provide a reproducible example?

**Comment by HongyuanWu** [comment]
I have the same question and I do not know how to solve it.
here is my code:
rm(list=ls())
options(stringsAsFactors=F)
library(tidyverse) 
library(DESeq2)
exp <- read_tsv("symbol.BRCA.txt")
head(exp)
gene <- read_tsv("gene.txt",col_names = F) 
colnames(gene) = "Ensembl_ID"
gene_exp <- inner_join(exp,gene, by = "Ensembl_ID")
class(gene_exp)
gene_exp[1:4,1:4]
gene_exp1 <- gene_exp[!duplicated(gene_exp[,1]),]
metadata <- data.frame(TCGA_id =colnames(gene_exp1)[-1])
table(substring(metadata$TCGA_id,14,15))
sample <- ifelse(substring(metadata$TCGA_id,14,15)< 10,'tumor','normal')
metadata$sample <- as.factor(sample)
mycounts <- gene_exp1
dds <-DESeqDataSetFromMatrix(countData=mycounts, 
                             colData=metadata, 
                             design=~sample,
                             tidy=T)

**Comment by yxiao832** [comment]
I have the same issue

**Comment by yxiao832** [comment]
I updated seurate to a newer version and the problem solved.
