### ISSUE TITLE
Cannot plot UMAP projection for CITE-seq data

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#3528]
Hi all, 

  I read the Seurat vignette for multimodal analysis of single-cell RNA-seq data and wanted to cluster by the CITE-seq markers. My code was the following:

`
# Add Ab-seq data as a separate assay
dataset[["Abseq"]]<-CreateAssayObject(counts=mtx_abseq[,colnames(mtx_abseq) %in% rownames(dataset@meta.data)])
dataset<-NormalizeData(dataset, assay='Abseq', normalization.method='CLR')

# Scale data
DefaultAssay(dataset)<-"Abseq"
dataset<-ScaleData(dataset, features=rownames(dataset))

# Perform linear reduction
dataset<-RunPCA(dataset,
                features=rownames(dataset),
                reduction.name="pca.abseq",
                reduction.key="pca.abseq_",
                approx=F,
                verbose=T)

# Calculate distance matrix
abseq.data<-GetAssayData(dataset, `slot="data")`
abseq.dist<-dist(t(abseq.data))  
  
# Run UMAP
dataset[["umap.abseq"]]<-RunUMAP(abseq.dist, assay="Abseq", reduction.key="umap.abseq")

# Find clusters
dataset[["abseq_snn"]]<-FindNeighbors(abseq.dist)$snn
dataset<-FindClusters(dataset, resolution=0.6, graph.name="abseq_snn")

DimPlot(object=dataset, reduction="umap.abseq", label=T)`

The error I get is:
`Error in Embeddings(object = object[[reduction]])[cells, dims] : 
  subscript out of bounds`

Can someone help with this? Clusters are calculated normally.

**Comment by yuhanH** [comment]
We have updated our multi-modal vignette. We don't recommend run cell-cell distance here to generate UMAP. 
I would suggest you RunPCA on ADT data, and RunUMAP on protein PCA. 
You can check the detail here:https://satijalab.org/seurat/v3.2/multimodal_vignette.html
