### ISSUE TITLE
Confusing documentation for min.cells argument of FindMarkers

### ISSUE THREAD

**Issue by b-dawes** [satijalab/seurat#353]
I was running FindMarkers on a small smartseq dataset and realized that the min.cells parameter might be affecting my results and filtering out more genes than expected. However I noticed that changing it did not affect the results at all. I checked the source code and noticed the min.cells parameter is only used in the negative binomial test. Could the documentation be updated to reflect this?

**Comment by satijalab** [comment]
Thanks for the catch. This is a small bug, as we have min.cells also referring to the minimum number of cells in one of the groups. We will fix and update documentation next week
