### ISSUE TITLE
scATAC-seq data  visualization

### ISSUE THREAD

**Issue by Ping-lin14** [satijalab/seurat#3530]
Hi

I have a question.

After referring to the Seurat visualization methods again, I still don't understand how to use `DotPlot()` and `DoHeatmap()` to visualize the differentially accessible peaks in the ATAC analysis results.

Can someone teach me?

Thanks

**Comment by timoast** [comment]
We don't typically recommend using DotPlot or heatmaps to visualize the accessibility of individual peaks in scATAC-seq data. If you're interested in a small number of individual peaks, you could try the `CoveragePlot` function in [Signac](https://satijalab.org/signac/). Alternatively, if you have a group of coaccessible peaks that you'd like to visualize collectively, you could try averaging the counts for those peaks within each group and building a DotPlot / heatmap visualization. We don't currently have specific code examples for this, but we may consider adding them in future to the Signac website.
