### ISSUE TITLE
Error: package or namespace load failed for ‘Seurat’ in loadNamespace

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#3532]
Hello Seurat people
My goal is to load my Seurat object into R studio platform and run Monocle 3  for trajectory analysis. 
unfortunately, I can't open my Seurat object into the R environment after Loading the Monocle3.

My knowlege is limited for controling versions in R studio.   

1. Anyone has developed .yml file to run  both Monocle3 and Seurat woriking in conda environment 
2. Do you have any tips for olve this--- ggplot compilation issue (See below)

Need help if anyone encountered tis issue before

```{r}
library(monocle3)
library(Seurat)
```

Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘ggplot2’ 3.2.1 is already loaded, but >= 3.3.0 is required

sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /home/jay/anaconda3/envs/monocle4/lib/libopenblasp-r0.3.7.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=sv_SE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=sv_SE.UTF-8       LC_NAME=C                
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:
 [1] lazyeval_0.2.2              monocle3_0.2.1              SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.0
 [5] DelayedArray_0.12.0         BiocParallel_1.20.0         matrixStats_0.55.0          GenomicRanges_1.38.0      
 [9] GenomeInfoDb_1.22.0         IRanges_2.20.0              S4Vectors_0.24.0            Biobase_2.46.0            
[13] BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
 [1] bitops_1.0-6           fs_1.3.1               usethis_1.5.1          devtools_2.2.1         RcppAnnoy_0.0.16      
 [6] RColorBrewer_1.1-2     rprojroot_1.3-2        tools_3.6.1            backports_1.1.5        R6_2.4.1              
[11] KernSmooth_2.23-16     colorspace_1.4-1       withr_2.1.2            tidyselect_1.0.0       gridExtra_2.3        
[16] prettyunits_1.1.1      processx_3.4.1         curl_4.3               compiler_3.6.1         cli_2.0.1            
[21] desc_1.2.0             scales_1.1.0           callr_3.4.1            stringr_1.4.0          digest_0.6.23        
[26] XVector_0.26.0         pkgconfig_2.0.3        sessioninfo_1.1.1      rlang_0.4.4            rstudioapi_0.10      
[31] dplyr_0.8.4            RCurl_1.98-1.1         magrittr_1.5           GenomeInfoDbData_1.2.2 Matrix_1.2-18        
[36] Rcpp_1.0.3             munsell_0.5.0          fansi_0.4.1            viridis_0.5.1          lifecycle_0.1.0      
[41] stringi_1.4.3          yaml_2.2.1             MASS_7.3-51.5          zlibbioc_1.32.0        pkgbuild_1.0.6        
[46] Rtsne_0.15             plyr_1.8.5             grid_3.6.1             listenv_0.8.0          crayon_1.3.4          
[51] lattice_0.20-38        splines_3.6.1          cowplot_1.0.0          knitr_1.27             ps_1.3.0              
[56] pillar_1.4.3           future.apply_1.6.0     reshape2_1.4.3         codetools_0.2-16       pkgload_1.0.2        
[61] glue_1.3.1             remotes_2.1.0          testthat_2.3.1         gtable_0.3.0           RANN_2.6.1            
[66] purrr_0.3.3            future_1.18.0          assertthat_0.2.1       ggplot2_3.3.2          xfun_0.12            
[71] survival_3.1-8         viridisLite_0.3.0      tibble_2.1.3           memoise_1.1.0          cluster_2.1.0        
[76] globals_0.12.5         fitdistrplus_1.1-1     ellipsis_0.3.0         ROCR_1.0-11          
>

**Comment by Nur-Taz** [comment]
Have you tried updating/installing ggplot2 3.3.1?

**Comment by JayalalKJ** [comment]
Resolved with 
https://github.com/satijalab/seurat/issues/1658

**Comment by JayalalKJ** [comment]
Resolved it.
conda env create -f .yml 

 1. Copy following codes in to .yml file 2. conda activate monocle3     3. open rstudio and install seurat3 install packages (CRAN)


name: monocle3
channels:
  - r
  - ccb-sb
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.33.1=h53a641e_8
  - binutils_linux-64=2.33.1=h9595d00_16
  - bioconductor-annotate=1.64.0=r36_0
  - bioconductor-annotationdbi=1.48.0=r36_0
  - bioconductor-annotationfilter=1.10.0=r36_0
  - bioconductor-annotationforge=1.28.0=r36_0
  - bioconductor-batchelor=1.2.1=r36he1b5a44_0
  - bioconductor-beachmat=2.2.0=r36he1b5a44_0
  - bioconductor-biobase=2.46.0=r36h516909a_0
  - bioconductor-biocfilecache=1.10.0=r36_0
  - bioconductor-biocgenerics=0.32.0=r36_0
  - bioconductor-biocneighbors=1.4.0=r36he1b5a44_0
  - bioconductor-biocparallel=1.20.0=r36he1b5a44_0
  - bioconductor-biocsingular=1.2.0=r36he1b5a44_0
  - bioconductor-biomart=2.42.0=r36_0
  - bioconductor-biostrings=2.54.0=r36h516909a_0
  - bioconductor-biovizbase=1.34.0=r36h516909a_0
  - bioconductor-bsgenome=1.54.0=r36_0
  - bioconductor-category=2.52.0=r36_0
  - bioconductor-complexheatmap=2.2.0=r36_0
  - bioconductor-delayedarray=0.12.0=r36h516909a_0
  - bioconductor-delayedmatrixstats=1.8.0=r36_0
  - bioconductor-deseq2=1.26.0=r36he1b5a44_0
  - bioconductor-diffbind=2.14.0=r36he1b5a44_0
  - bioconductor-edger=3.28.0=r36he1b5a44_0
  - bioconductor-ensdb.hsapiens.v75=2.99.0=r36_6
  - bioconductor-ensembldb=2.10.0=r36_0
  - bioconductor-genefilter=1.68.0=r36hc99cbb1_0
  - bioconductor-geneplotter=1.64.0=r36_0
  - bioconductor-genomeinfodb=1.22.0=r36_0
  - bioconductor-genomeinfodbdata=1.2.2=r36_0
  - bioconductor-genomicalignments=1.22.0=r36h516909a_0
  - bioconductor-genomicfeatures=1.38.0=r36_0
  - bioconductor-genomicinteractions=1.20.0=r36_0
  - bioconductor-genomicranges=1.38.0=r36h516909a_0
  - bioconductor-ggbio=1.34.0=r36_0
  - bioconductor-go.db=3.10.0=r36_0
  - bioconductor-gostats=2.52.0=r36_0
  - bioconductor-graph=1.64.0=r36h516909a_0
  - bioconductor-gseabase=1.48.0=r36_0
  - bioconductor-gtrellis=1.18.0=r36_0
  - bioconductor-gviz=1.30.0=r36_0
  - bioconductor-hdf5array=1.14.0=r36h516909a_0
  - bioconductor-homo.sapiens=1.3.1=r36_7
  - bioconductor-interactionset=1.14.0=r36he1b5a44_0
  - bioconductor-iranges=2.20.0=r36h516909a_0
  - bioconductor-keggrest=1.26.0=r36_0
  - bioconductor-limma=3.42.0=r36h516909a_0
  - bioconductor-org.hs.eg.db=3.10.0=r36_0
  - bioconductor-organismdbi=1.28.0=r36_0
  - bioconductor-pcamethods=1.78.0=r36he1b5a44_0
  - bioconductor-protgenerics=1.18.0=r36_0
  - bioconductor-rbgl=1.62.1=r36he1b5a44_0
  - bioconductor-rgraphviz=2.30.0=r36he1b5a44_0
  - bioconductor-rhdf5=2.30.0=r36he1b5a44_0
  - bioconductor-rhdf5lib=1.8.0=r36h516909a_0
  - bioconductor-rhtslib=1.18.0=r36hdb70ac9_1
  - bioconductor-rsamtools=2.2.0=r36he1b5a44_0
  - bioconductor-rtracklayer=1.46.0=r36h516909a_0
  - bioconductor-s4vectors=0.24.0=r36h516909a_0
  - bioconductor-scater=1.14.0=r36he1b5a44_0
  - bioconductor-shortread=1.44.0=r36he1b5a44_0
  - bioconductor-singlecellexperiment=1.8.0=r36_0
  - bioconductor-somaticsignatures=2.22.0=r36_0
  - bioconductor-summarizedexperiment=1.16.0=r36_0
  - bioconductor-systempiper=1.20.0=r36_0
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2=r36_7
  - bioconductor-variantannotation=1.32.0=r36h516909a_0
  - bioconductor-viper=1.20.0=r36_0
  - bioconductor-xvector=0.26.0=r36h516909a_0
  - bioconductor-yapsa=1.12.0=r36_0
  - bioconductor-zlibbioc=1.32.0=r36h516909a_0
  - boost-cpp=1.70.0=ha2d47e9_1
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cfitsio=3.470=hb60a0a2_2
  - colormath=3.0.0=py_2
  - curl=7.68.0=hf8cf82a_0
  - cyrus-sasl=2.1.27=he38ecfd_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - expat=2.2.9=he1b5a44_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=he4413a7_1000
  - fonts-anaconda=1=h8fa9717_0
  - freetype=2.10.0=he983fc9_1
  - freexl=1.0.5=h14c3975_1002
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_16
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.5.1=h560c3f3_2
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_16
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=py37h6f030ca_1002
  - gmp=6.2.0=he1b5a44_1
  - graphite2=1.3.13=hf484d3e_1000
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_1
  - gstreamer=1.14.5=h36ae1b5_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_16
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=hf484d3e_1000
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.12=hec59c27_0
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.68.0=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgdal=2.4.2=h524de44_5
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.6.2=h303dfb8_1003
  - libntlm=1.4=h516909a_1002
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_1
  - libspatialite=4.3.0a=he1bb1e1_1029
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.2.1=h14c3975_2004
  - mpfr=4.0.2=he80fd80_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_0
  - numpy=1.18.1=py37h95a1406_0
  - openjdk=8.0.192=h14c3975_1003
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1f=h516909a_0
  - pandoc=2.9.1.1=0
  - pango=1.40.14=he752989_2
  - pcre=8.43=he1b5a44_0
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_1
  - proj4=6.1.0=he751ad9_2
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.7.6=h357f687_2
  - python_abi=3.7=1_cp37m
  - qt=5.6.3=h8bf5577_3
  - r-acepack=1.4.1=r36h9bbef5b_1004
  - r-amap=0.8_18=r36h6786f55_0
  - r-askpass=1.1=r36hcdcec82_1
  - r-assertthat=0.2.1=r36h6115d3f_1
  - r-backports=1.1.5=r36hcdcec82_0
  - r-base=3.6.1=h8900bf8_2
  - r-base64enc=0.1_3=r36hcdcec82_1003
  - r-base64url=1.4=r36hcdcec82_1003
  - r-batchtools=0.9.12=r36hcdcec82_0
  - r-beeswarm=0.2.3=r36h6115d3f_1002
  - r-bh=1.72.0_3=r36h6115d3f_0
  - r-bibtex=0.4.2.2=r36hcdcec82_0
  - r-biocmanager=1.30.10=r36h6115d3f_0
  - r-bit=1.1_15.1=r36hcdcec82_0
  - r-bit64=0.9_7=r36hcdcec82_1001
  - r-bitops=1.0_6=r36hcdcec82_1003
  - r-blob=1.2.1=r36h6115d3f_0
  - r-boot=1.3_24=r36h6115d3f_0
  - r-brew=1.0_6=r36h6115d3f_1002
  - r-broom=0.5.4=r36h6115d3f_0
  - r-cairo=1.5_10=r36hcdcec82_1
  - r-callr=3.4.1=r36h6115d3f_0
  - r-catools=1.18.0=r36h0357c0b_0
  - r-cellranger=1.1.0=r36h6115d3f_1002
  - r-checkmate=2.0.0=r36hcdcec82_0
  - r-circlize=0.4.8=r36h6115d3f_0
  - r-class=7.3_15=r36hcdcec82_1001
  - r-classint=0.4_2=r36h9bbef5b_0
  - r-cli=2.0.1=r36h6115d3f_0
  - r-clipr=0.7.0=r36h6115d3f_0
  - r-clisymbols=1.2.0=r36h6115d3f_1002
  - r-clue=0.3_57=r36h516909a_1
  - r-cluster=2.1.0=r36h9bbef5b_2
  - r-coda=0.19_3=r36h6115d3f_1
  - r-codetools=0.2_16=r36h6115d3f_1001
  - r-colorspace=1.4_1=r36hcdcec82_1
  - r-commonmark=1.7=r36hcdcec82_1001
  - r-config=0.3=r36h6115d3f_1002
  - r-corrplot=0.84=r36_1002
  - r-covr=3.4.0=r36h0357c0b_0
  - r-cowplot=1.0.0=r36h6115d3f_1
  - r-crayon=1.3.4=r36h6115d3f_1002
  - r-crosstalk=1.0.0=r36h6115d3f_1002
  - r-curl=4.3=r36hcdcec82_0
  - r-data.table=1.12.8=r36hcdcec82_0
  - r-dbi=1.1.0=r36h6115d3f_0
  - r-dbplyr=1.4.2=r36h6115d3f_1
  - r-deldir=0.1_25=r36h9bbef5b_0
  - r-dendextend=1.13.2=r36h6115d3f_0
  - r-deoptimr=1.0_8=r36h6115d3f_1002
  - r-desc=1.2.0=r36h6115d3f_1002
  - r-devtools=2.2.1=r36h6115d3f_0
  - r-dichromat=2.0_0=r36_2001
  - r-digest=0.6.23=r36h0357c0b_0
  - r-diptest=0.75_7=r36hcdcec82_1002
  - r-doparallel=1.0.15=r36h6115d3f_0
  - r-dplyr=0.8.4=r36h0357c0b_0
  - r-dqrng=0.2.1=r36h0357c0b_1
  - r-dt=0.12=r36h6115d3f_0
  - r-e1071=1.7_3=r36h0357c0b_0
  - r-ellipsis=0.3.0=r36hcdcec82_0
  - r-evaluate=0.14=r36h6115d3f_1
  - r-expm=0.999_4=r36hbf399a0_3
  - r-fansi=0.4.1=r36hcdcec82_0
  - r-farver=2.0.3=r36h0357c0b_0
  - r-fastmap=1.0.1=r36h0357c0b_0
  - r-flexmix=2.3_15=r36h6115d3f_1
  - r-fnn=1.1.3=r36h0357c0b_1
  - r-forcats=0.4.0=r36h6115d3f_1
  - r-foreach=1.4.7=r36h6115d3f_0
  - r-foreign=0.8_75=r36hcdcec82_0
  - r-forge=0.2.0=r36h6115d3f_1
  - r-formatr=1.7=r36h6115d3f_1
  - r-formula=1.2_3=r36h6115d3f_1002
  - r-fpc=2.2_5=r36h6115d3f_0
  - r-fs=1.3.1=r36h0357c0b_1
  - r-furrr=0.1.0=r36h6115d3f_1001
  - r-futile.logger=1.4.3=r36h6115d3f_1002
  - r-futile.options=1.0.1=r36h6115d3f_1001
  - r-future=1.16.0=r36h6115d3f_0
  - r-gdata=2.18.0=r36h6115d3f_1002
  - r-generics=0.0.2=r36h6115d3f_1002
  - r-getoptlong=0.1.8=r36h6115d3f_0
  - r-ggally=1.4.0=r36h6115d3f_1001
  - r-ggbeeswarm=0.6.0=r36_1002
  - r-ggplot2=3.2.1=r36h6115d3f_0
  - r-ggrastr=0.1.7=r36_1000
  - r-ggrepel=0.8.1=r36h0357c0b_1
  - r-ggsci=2.9=r36h6115d3f_1002
  - r-gh=1.1.0=r36h6115d3f_0
  - r-git2r=0.26.1=r36h5ca76e2_1
  - r-globaloptions=0.1.1=r36_0
  - r-globals=0.12.5=r36h6115d3f_0
  - r-glue=1.3.1=r36hcdcec82_1
  - r-gmodels=2.18.1=r36_1002
  - r-gplots=3.0.1.2=r36h6115d3f_0
  - r-gridbase=0.4_7=r36h6115d3f_1002
  - r-gridextra=2.3=r36h6115d3f_1002
  - r-grr=0.9.5=r36h0357c0b_1003
  - r-gtable=0.3.0=r36h6115d3f_2
  - r-gtools=3.8.1=r36hcdcec82_1003
  - r-haven=2.2.0=r36hde08347_0
  - r-hexbin=1.28.1=r36h9bbef5b_0
  - r-highr=0.8=r36h6115d3f_1
  - r-hmisc=4.3_0=r36h9bbef5b_0
  - r-hms=0.5.3=r36h6115d3f_0
  - r-htmltable=1.13.3=r36h6115d3f_0
  - r-htmltools=0.4.0=r36h0357c0b_0
  - r-htmlwidgets=1.5.1=r36h6115d3f_0
  - r-httpuv=1.5.2=r36h0357c0b_1
  - r-httr=1.4.1=r36h6115d3f_1
  - r-hunspell=3.0=r36h0357c0b_1001
  - r-hwriter=1.3.2=r36h6115d3f_1002
  - r-igraph=1.2.4.2=r36h6786f55_0
  - r-ini=0.3.1=r36h6115d3f_1002
  - r-irlba=2.3.3=r36h7fa42b6_2
  - r-iterators=1.0.12=r36h6115d3f_0
  - r-jpeg=0.1_8.1=r36hcdcec82_0
  - r-jsonlite=1.6.1=r36hcdcec82_0
  - r-kableextra=1.1.0=r36h6115d3f_1
  - r-kernlab=0.9_29=r36h0357c0b_0
  - r-kernsmooth=2.23_16=r36h9bbef5b_0
  - r-knitr=1.27=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_1002
  - r-lambda.r=1.2.4=r36h6115d3f_0
  - r-later=1.0.0=r36h0357c0b_0
  - r-lattice=0.20_38=r36hcdcec82_1002
  - r-latticeextra=0.6_29=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36hcdcec82_1
  - r-learnbayes=2.15.1=r36h6115d3f_1001
  - r-leidenbase=0.1.0=r36hc99cbb1_0
  - r-lifecycle=0.1.0=r36h6115d3f_0
  - r-limsolve=1.5.6=r36h9bbef5b_0
  - r-listenv=0.8.0=r36h6115d3f_0
  - r-lmtest=0.9_37=r36h9bbef5b_2
  - r-locfit=1.5_9.1=r36h516909a_1004
  - r-lpsolve=5.6.15=r36hcdcec82_0
  - r-lsei=1.2_0=r36h6e990d7_1004
  - r-lubridate=1.7.4=r36h0357c0b_1002
  - r-magrittr=1.5=r36h6115d3f_1002
  - r-markdown=1.1=r36hcdcec82_0
  - r-mass=7.3_51.5=r36hcdcec82_0
  - r-matrix=1.2_18=r36hcdcec82_0
  - r-matrix.utils=0.9.8=r36h6115d3f_0
  - r-matrixstats=0.55.0=r36hcdcec82_0
  - r-mclust=5.4.5=r36h9bbef5b_0
  - r-memoise=1.1.0=r36h6115d3f_1003
  - r-mgcv=1.8_31=r36hcdcec82_0
  - r-mime=0.9=r36hcdcec82_0
  - r-miniui=0.1.1.1=r36h6115d3f_1001
  - r-mixtools=1.1.0=r36hcdcec82_1003
  - r-modelr=0.1.5=r36h6115d3f_0
  - r-modeltools=0.2_22=r36h6115d3f_1002
  - r-mongolite=2.1.0=r36hcdcec82_1
  - r-monocle3=0.2.1=r36hc9558a2_0
  - r-munsell=0.5.0=r36h6115d3f_1002
  - r-nlme=3.1_144=r36h9bbef5b_0
  - r-nmf=0.21.0=r36h0357c0b_1003
  - r-nnet=7.3_12=r36hcdcec82_1003
  - r-odbc=1.2.2=r36h0357c0b_0
  - r-openssl=1.4.1=r36h9c8475f_0
  - r-packrat=0.5.0=r36h6115d3f_1001
  - r-patchwork=1.0.0=r36h6115d3f_0
  - r-pbapply=1.4_2=r36h6115d3f_0
  - r-pbmcapply=1.5.0=r36hcdcec82_0
  - r-pheatmap=1.0.12=r36h6115d3f_1
  - r-pillar=1.4.3=r36h6115d3f_0
  - r-pkgbuild=1.0.6=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_0
  - r-pkgload=1.0.2=r36h0357c0b_1001
  - r-pkgmaker=0.31=r36h6115d3f_0
  - r-pki=0.1_5.1=r36hcdcec82_1003
  - r-plogr=0.2.0=r36h6115d3f_1002
  - r-plotly=4.9.2=r36h6115d3f_0
  - r-plyr=1.8.5=r36h0357c0b_0
  - r-pmcmr=4.3=r36h6115d3f_1002
  - r-png=0.1_7=r36hcdcec82_1003
  - r-prabclus=2.3_2=r36h6115d3f_0
  - r-praise=1.0.0=r36h6115d3f_1003
  - r-prettyunits=1.1.1=r36h6115d3f_0
  - r-processx=3.4.1=r36hcdcec82_0
  - r-profvis=0.3.6=r36hcdcec82_1
  - r-progress=1.2.2=r36h6115d3f_1
  - r-promises=1.1.0=r36h0357c0b_0
  - r-proxy=0.4_23=r36hcdcec82_1
  - r-pryr=0.1.4=r36h0357c0b_1003
  - r-ps=1.3.0=r36hcdcec82_1001
  - r-pscl=1.5.5=r36h516909a_0
  - r-purrr=0.3.3=r36hcdcec82_0
  - r-quadprog=1.5_8=r36h9bbef5b_0
  - r-r.methodss3=1.7.1=r36h6115d3f_1002
  - r-r.oo=1.23.0=r36h6115d3f_0
  - r-r.utils=2.9.2=r36h6115d3f_0
  - r-r2d3=0.2.3=r36h6115d3f_1001
  - r-r6=2.4.1=r36h6115d3f_0
  - r-rann=2.6.1=r36h0357c0b_1
  - r-rappdirs=0.3.1=r36hcdcec82_1003
  - r-raster=3.0_12=r36h0357c0b_0
  - r-rcmdcheck=1.3.3=r36h6115d3f_2
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1002
  - r-rcpp=1.0.3=r36h0357c0b_0
  - r-rcppannoy=0.0.16=r36h0357c0b_0
  - r-rcpparmadillo=0.9.800.4.0=r36h0357c0b_0
  - r-rcppeigen=0.3.3.7.0=r36h0357c0b_0
  - r-rcpphnsw=0.2.0=r36h0357c0b_0
  - r-rcppparallel=5.0.0=r36h0357c0b_0
  - r-rcppprogress=0.4.2=r36h6115d3f_0
  - r-rcurl=1.98_1.1=r36hcdcec82_0
  - r-readr=1.3.1=r36h0357c0b_1002
  - r-readxl=1.3.1=r36h0357c0b_2
  - r-registry=0.5_1=r36h6115d3f_1
  - r-rematch=1.0.1=r36h6115d3f_1002
  - r-remotes=2.1.0=r36h6115d3f_1
  - r-reprex=0.3.0=r36h6115d3f_1
  - r-reshape=0.8.8=r36hcdcec82_1
  - r-reshape2=1.4.3=r36h0357c0b_1004
  - r-reticulate=1.14=r36h0357c0b_0
  - r-rex=1.1.2=r36h6115d3f_1001
  - r-rhpcblasctl=0.20_17=r36hcdcec82_0
  - r-rjava=0.9_11=r36hcdcec82_1
  - r-rjdbc=0.2_7.1=r36h6115d3f_0
  - r-rjson=0.2.20=r36h0357c0b_1001
  - r-rjsonio=1.3_1.4=r36h0357c0b_0
  - r-rlang=0.4.4=r36hcdcec82_0
  - r-rmarkdown=2.1=r36h6115d3f_0
  - r-rngtools=1.5=r36h6115d3f_0
  - r-robustbase=0.93_5=r36h9bbef5b_2
  - r-roxygen2=7.0.2=r36h0357c0b_0
  - r-rpart=4.1_15=r36hcdcec82_1
  - r-rprojroot=1.3_2=r36h6115d3f_1002
  - r-rsample=0.0.5=r36h6115d3f_0
  - r-rsconnect=0.8.16=r36h6115d3f_0
  - r-rspectra=0.16_0=r36h0357c0b_0
  - r-rsqlite=2.1.5=r36h0357c0b_0
  - r-rstudioapi=0.10=r36h6115d3f_2
  - r-rsvd=1.0.3=r36h6115d3f_0
  - r-rtsne=0.15=r36he1b5a44_1
  - r-rversions=2.0.1=r36h6115d3f_0
  - r-rvest=0.3.5=r36h6115d3f_0
  - r-scales=1.1.0=r36h6115d3f_0
  - r-segmented=1.1_0=r36h6115d3f_0
  - r-selectr=0.4_2=r36h6115d3f_0
  - r-sessioninfo=1.1.1=r36h6115d3f_1001
  - r-sf=0.7_6=r36h474ac88_3
  - r-shape=1.4.4=r36_1002
  - r-shiny=1.4.0=r36h6115d3f_0
  - r-sitmo=2.0.1=r36h0357c0b_1
  - r-slam=0.1_47=r36hcdcec82_0
  - r-snow=0.4_3=r36h6115d3f_1001
  - r-sourcetools=0.1.7=r36he1b5a44_1001
  - r-sp=1.4_1=r36hcdcec82_0
  - r-sparklyr=1.1.0=r36h6115d3f_0
  - r-spdata=0.3.3=r36h6115d3f_0
  - r-spdep=1.1_3=r36hc57f18f_1
  - r-speedglm=0.3_2=r36_1002
  - r-spelling=2.1=r36h6115d3f_1
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_1
  - r-survival=3.1_8=r36hcdcec82_0
  - r-sys=3.3=r36hcdcec82_0
  - r-testthat=2.3.1=r36h0357c0b_0
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-tidyr=1.0.2=r36h0357c0b_0
  - r-tidyselect=1.0.0=r36h6115d3f_0
  - r-tidyverse=1.3.0=r36h6115d3f_1
  - r-tinytex=0.19=r36h6115d3f_0
  - r-umap=0.2.4.1=r36h0357c0b_0
  - r-units=0.6_6=r36h0357c0b_0
  - r-usethis=1.5.1=r36h6115d3f_1
  - r-utf8=1.1.4=r36hcdcec82_1001
  - r-uwot=0.1.8=r36h0357c0b_0
  - r-vctrs=0.2.2=r36hcdcec82_0
  - r-vipor=0.4.5=r36h6115d3f_1002
  - r-viridis=0.5.1=r36h6115d3f_1003
  - r-viridislite=0.3.0=r36h6115d3f_1002
  - r-webshot=0.5.2=r36h6115d3f_0
  - r-whisker=0.4=r36h6115d3f_0
  - r-withr=2.1.2=r36h6115d3f_1001
  - r-xfun=0.12=r36h6115d3f_0
  - r-xml=3.98_1.20=r36hcdcec82_1
  - r-xml2=1.2.2=r36h0357c0b_0
  - r-xopen=1.0.0=r36h6115d3f_1002
  - r-xtable=1.8_4=r36h6115d3f_2
  - r-yaml=2.2.1=r36hcdcec82_0
  - r-zeallot=0.1.0=r36h6115d3f_1001
  - r-zoo=1.8_7=r36hcdcec82_0
  - readline=8.0=hf8c457e_0
  - rstudio=1.1.456=h6bb024c_1
  - sed=4.7=h1bed415_1000
  - setuptools=45.1.0=py37_0
  - spectra=0.0.11=py_1
  - sqlite=3.30.1=hcee41ef_0
  - texlive-core=20180414=hc8d0b01_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - tzcode=2019a=h516909a_1002
  - udunits2=2.2.27.6=h4e0c4b3_1001
  - unixodbc=2.3.7=h227dcee_1000
  - wheel=0.34.2=py_1
  - xerces-c=3.2.2=hea5cb30_1003
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.0.0
    - chardet==3.0.4
    - gast==0.2.2
    - google-auth==1.10.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - h5py==2.10.0
    - idna==2.8
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - protobuf==3.11.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.4.1
    - six==1.14.0
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - urllib3==1.25.7
    - werkzeug==0.16.0
    - wrapt==1.11.2
prefix: /home/bq_mkohnen/my-envs/kidneyenv
