### ISSUE TITLE
Scale data before differential expression analysis? 

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#3533]
The first part of issue #1421 was not addressed, unless I have missed something.  I have the same question.  It has to do with whether or not data needs to be scaled before DE analysis.  In the vignette "[integrated stimulated vs control PBMC datasets to learn cell-type specific responses](https://satijalab.org/seurat/v3.0/immune_alignment.html)", it appears that the data was not scaled before DE analysis, since the RNA assay was used. The original question on Github issue #1421 states: 

"I've noticed that ScaleData is only used once at the "integrated" assay right after FindIntegrationAnchors and IntegrateData . In the vignette, differential expression is performed with the "RNA" assay since this was set as the Default after integration (in the "Identify conserved cell type markers"), but the data is not scaled at this assay (example: @scale.data slot is not present in the RNA assay). Thus, does that mean that scaling the data at the RNA assay is not needed due to the integration steps? Or should scaling be performed prior to differential expression at this assay as well? (if so, this step is missing at the tutorial)."

**Comment by timoast** [comment]
You do not need to run ScaleData before running DE. The output of ScaleData (scaled and centered expression data) is typically used as the input to PCA, or for heatmap visualizations

**Comment by themangoscholar** [comment]
Will it be invalid to run DE analysis on scaled data? Specially for tests for which a normal distribution is assumed (like a basic T-test)?
