### ISSUE TITLE
Label clusters on FeatureScatter, with an equivalent to "label=T" option in Dimplot

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#3534]
Hi,

sorry if this was asked already, but did not find the solution: I would like to label clusters (and other groups) **on the plot** as in `FeatureScatter()`, with an equivalent of the "label=T" option in `DimPlot()`. 

#### On plot cluster labels in `DimPlot()`:
![image](https://user-images.githubusercontent.com/5101911/93898738-d3452d00-fcf3-11ea-8a58-c1e930d58ad6.png)

#### Only Legend seem to be possible in `FeatureScatter()`:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/5101911/93899980-2c619080-fcf5-11ea-926c-6ab96561363c.png">

1. Is there a solution in Seurat?
2. Does anyone have a hack solution, [eg along these lines ](https://stackoverflow.com/questions/51120412/adding-text-annotation-to-a-clustering-scatter-plot-tsne)

**Comment by andrewwbutler** [comment]
Hi,

You can use the `LabelClusters` function. E.g.

```R
p <- FeatureScatter(pbmc_small, "LYZ", "MS4A1") 
LabelClusters(p, id = "colors")
```

**Comment by vertesy** [comment]
Thank you!
