### ISSUE TITLE
Integrating with a reference that uses ENSEMBL IDs while samples use gene symbols

### ISSUE THREAD

**Issue by laijen000** [satijalab/seurat#3535]
I would like to use reference-based integration so that the established cell types in the reference can be transferred onto my new datasets. However, the reference dataset uses ENSEMBL IDs while my new datasets use gene symbols. Will this be problematic for reference based integration using the standard LogNormalization workflow? 

When I try to run SelectIntegrationFeatures on a list of objects including the reference and 3 new objects, I receive this error: 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'head': 'x' must be atomic

I wonder if the inconsistent gene names are the issue. Thank you for your advice on this!

**Comment by timoast** [comment]
The integration requires the same set of features to be present in both datasets, and named the same. To do the integration you will first need to ensure that the gene names match in both datasets
