### ISSUE TITLE
AverageExpression clarification

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#3536]
The lab I am in has started using AverageExpression more consistently and I have a question about how it works. In the description you say:

`Output is in log-space when return.seurat = TRUE, otherwise it's in non-log space. Averaging is done in non-log space.`

Does that mean that you average the count (raw) data and then log normalize the groups? If so why do you average the counts data and not the normalized data?

**Comment by jaisonj708** [comment]
By default (`return.seurat = FALSE`), we exponentiate values, average the exponentiated values (+1), and then take the log. We average in non-log space to avoid including biases that may be introduced by log-normalization.

**Comment by WendyZhangYing** [comment]
I am trying to understand how AverageExpression function is applied. 

For instance, from:  AverageExpression vs FindMarkers: difference in the avg_logFC #2423 
to get mean gene expression of all cells in a cluster (assuming : active ident  is "seurat_cluster", group.by = "ident" )
the code is like: 

avg.CD14.mono <- log1p(AverageExpression(CD14.mono, verbose = FALSE)$RNA)

If AverageExpression is log (average (exponentiated  $data )), then why use log1p after the AverageExpression? 
Thanks very much
