### ISSUE TITLE
issue about install(Seurat)

### ISSUE THREAD

**Issue by BeyondMyPast228** [satijalab/seurat#3537]
Hi，
Thanks for developing this user-friendly tool. Just now, i installed the Seurat ==3.2.1,but when i tried to library（Seurat），the error occured.
The error is:
Error: package or namespace load failed for ‘Seurat’ in get(method, envir = home):
 lazy-load database '/home/vip1/R/x86_64-pc-linux-gnu-library/3.6/Seurat/R/Seurat.rdb' is corrupt.

I sincerely hope you can help me.

**Comment by timoast** [comment]
Can you try clearing the R environment, reinstalling Seurat, and restarting R?
