### ISSUE TITLE
Single gene expression

### ISSUE THREAD

**Issue by MSALIST** [satijalab/seurat#3538]
I am quite new to scRNAseq analysis, so my question might be very trivial. I have transcriptomes of a mutant and wt condition, and besides looking into the DEGs, I would also like to export the statistics of the expression of one specific gene of interest (DEG or not) when compared between the two conditions (MUTvsWT). Is there a way to look into this? Thank you!!

**Comment by Dragonmasterx87** [comment]
Based of your question im not entirely sure if you know how to run DEG on a regular seurat object....also this has been answered before #325 .....but here is what you want to do for your current question:

```
# Unique genes across cell types
seurat.object <- whatever your seurat object is called

# First change to RNA assay
DefaultAssay(seurat.object) <- "RNA"

# Confirm by looking at your active identity
DefaultAssay(pancreas.integrated)

# The next line of code assumes you have a meta-data slot containing sample specific information, where mutant data set is 
# called 'mut' and wild type dataset is called 'wt'. This metadata slot is called 'mut_wt_metadata' change this to match what you # actually have.
seurat.object$sample.subtypes <- paste(Idents(seurat.object), seurat.object$mut_wt_metadata, sep = "_")
seurat.object$celltype <- Idents(seurat.object)
Idents(seurat.object) <- "sample.subtypes"

# Cluster 1 cells DEG between Mut and WT.
clust1.markers <- FindMarkers(seurat.object, 
                                ident.1 = "clust1_mut", ident.2 = "clust1_wt", 
                                logfc.threshold = 0.38, min.pct = 0.25, only.pos = FALSE, verbose = FALSE) # remove logfc and min.pct to 
                                                                                                                                                        # analyze all genes

# Look at the first 15 genes
head(clust1.markers, n = 15)

# Save in a defined location on your machine
write.csv(clust1.markers, '~/clust1.markers.csv')
```

Once you have run the above you should have a csv file that contains DEG data for cluster 1 between mut and wt. csv files can be opened in excel, or you can just click on the file in Rstudio to look at your genes.

Cheers,
🐲

**Comment by MSALIST** [comment]
Thank you so much for your quick and detailed response. However, I might have not formulated my question in the best way. The 'FindMarkers' function returns the list of DEGs, genes where the difference in expression (e.g. between the conditions) is statistically significant. But, I would like to have the same statistic for each gene, even if there is expression is statistically insignificant. I would like to see this for each gene in my dataset, but also for one single gene of interest. Thank you

**Comment by samuel-marsh** [comment]
Hi,

`FindMarkers` will return non-significant genes as well as significant.  As mentioned in the previous post to look at all genes you need to remove the logfc and min.pct thresholds so that the genes are included in the output.  If you are simply interested in looking at the results of single gene or small list of genes and whether the changes are significant or not you can supply that gene or list using `features = "gene_of_interest` inside the `FindMarkers` function.

Best,
Sam

**Comment by MSALIST** [comment]
Perfect!! Thank you very much!
