### ISSUE TITLE
Trajectories with Monocle 3 and Seurat - running plot_genes_in_pseudotime()

### ISSUE THREAD

**Issue by deliasoto** [satijalab/seurat#3539]
Hello,
I know it is not included in the vignette but it will be super useful to be able to plot single gene expression in pseudotime using plot_genes_in_pseudotime(). Unfortunately when I try to run plot_genes_in_pseudotime() in a cds generated from a Seurat object I get this error:

**Error: When label_by_short_name = TRUE, rowData must have a column of gene names called gene_short_name.**

I haven't done anything outside of the vignette. It seems we need to transfer the list of genes into the "gene_short_name" of the cell_data_set object. Any advice on how to do this?
I'll appreciate your comments, super thanks!!

**Comment by timoast** [comment]
Please direct questions about CellDataSet / Monocle3 to the Monocle 3 repository: https://github.com/cole-trapnell-lab/monocle3
