### ISSUE TITLE
Number of Cells for Each Cluster of TSNE?

### ISSUE THREAD

**Issue by kragrawa** [satijalab/seurat#354]
Hi,

I cannot figure out how to display the number of cells for each cluster. I want to display these values on my TSNE plot, but I do not see a parameter that will allow me to do so. If it can not be displayed on my TSNE plot, is there any other way I can get to know how many cells I have in each cluster? Thank you.

**Comment by b-dawes** [comment]
The cluster of each cell is stored in the `ident` slot of your object. If you your data is stored in an object `seurat`, you can access this slot with `seurat@ident`. If you want to see the count for each cluster, you can do that with R's `table` function. So this command should give you the info you want:
`table(seurat@ident)`

**Comment by mojaveazure** [comment]
`TSNEPlot` does not have a parameter for cell counts per cluster. If you'd like to label each cluster on the plot with the cluster ID, set `do.label = TRUE`; if you'd like a count of the number of cells in each cluster, use the [`table`](http://stat.ethz.ch/R-manual/R-patched/library/base/html/table.html) function to get counts of each cluster ID stored in the [`ident` slot](https://stat.ethz.ch/R-manual/R-devel/library/methods/html/slot.html).

**Comment by leonfodoulian** [comment]
Hi,

Here is a complete example of how to do both. It is very straightforward, and should work what ever the order of the levels in `object@ident`.

```R
# Calculate number of cells per cluster from object@ident
cell.num <- table(object@ident)

# Add cell number per cluster to cluster labels
ClusterLabels = paste("Cluster", names(cell.num), paste0("(n = ", cell.num, ")"))

# Order legend labels in plot in the same order as 'ClusterLabels'
ClusterBreaks = names(cell.num)

# Plot tSNE with new legend labels for clusters
TSNEPlot(object = object, do.return = T) +
  scale_colour_discrete(breaks = ClusterBreaks, 
                        labels = ClusterLabels) +
  labs(x = "t-SNE 1",
       y = "t-SNE 2")
```

Hope this helped!

Best,
Leon

**Comment by kragrawa** [comment]
Thank you all for the help!

**Comment by ahdee** [comment]
for seuret 3 you can use the Indents function. 
`table ( Idents(control4) )
`

**Comment by garimaloh** [comment]
Thanks ahdee
