### ISSUE TITLE
Dataset Integration & Merging The Count Matrix Gene Names

### ISSUE THREAD

**Issue by dlmatera** [satijalab/seurat#3540]
I have a quick question about the integrate functions in Seurat - how does the current approach handle merging the original count matrices and their corresponding gene names? 

For example in the first dataset there is ~ 40,000 features
![image](https://user-images.githubusercontent.com/65360421/94058176-b3bf0a80-fdae-11ea-9e50-ebb634f288fe.png)
and in the second dataset ~25,000 (and a third dataset has a feature count somewhere between these two)
![image](https://user-images.githubusercontent.com/65360421/94058255-cafdf800-fdae-11ea-8b1a-35a3a46fd948.png)
however after merging the 3 in accordance with the Seurat Vignette there is ~60k
![image](https://user-images.githubusercontent.com/65360421/94058366-e832c680-fdae-11ea-89b0-8fe70fc0535e.png)

does this mean that I am getting duplicate genes in my analyses? and is there a way around this? This also is affecting my DE analysis since the ~60k number is being used for the bonferroni correction (even if i reduce the total number of genes being tested by changing the thresholds in FindMarkers (increasing the LogFC cutoff, etc.)

**Comment by dlmatera** [comment]
I guess to elaborate - how does the integration framework in seurat handle merging datasets where some genes are not present in one of the datasets? And does it account for how some gene names are redundant?

Finally, when I output a full list of differentially expressed genes by opening up the filter settings on FindMarkers (Despite their being 59117 features), the output has ~30k rows, but the bonferroni correction is still using the 59117 number. Would it be better to manually create a corrected pvalue with the total number of rows?

**Comment by andrewwbutler** [comment]
It looks like the `Assay` that you are looking at is the "RNA" assay so this is independent of anything to do with the actual integration algorithms (those are located by default in the "integrated" `Assay`). If you're running the integration workflow though, the combined object will still contain the unintegrated expression data in the "RNA" `Assay`, which is what you're looking at here. If a feature is present in any of the three objects, it will be included in the "RNA" `Assay` matrices. For cells from objects that didn't originally contain that feature, the value in the merged "data" matrix will be 0. 

We chose to be conservative with the p-value correction here and correct based on all genes though provide the raw p-values if you wish to apply a different strategy. Part of the rational for this is in the docs for `FindMarkers`

> p-values should be interpreted cautiously, as the genes used for clustering are the same genes tested for differential expression.

**Comment by dlmatera** [comment]
I understand the assay used for DE analysis is not integrated like you said - but given that it is reccomended to use the RNA slot for FindMarkers, even in an integrated dataset, how does this function create a LogFC value if there is (in my case) 3 expression matrices, and thus 3 values for each gene? Just an average? And is this value weighted at all by the number of the cells from each induvidual dataset? 

I am asking because (most importantly) -I have ~500 genes that are duplicated in the FindMarkers output, for example for gene X there is a foldchange/pval from dataset#1, and an additional row for gene X which is from dataset #2 (but the name is one of aliases for it) with a different logFC/pval. I am wondering for consistency, how I would merge these together after the analysis? Or if the best route would be to try to modify the matrices before even creating a seurat object, but I of course would then have to redo the entire analysis.. 

Thanks

**Comment by timoast** [comment]
Any genes that are not named identically across experiments are assumed to be different. Seurat doesn't have any knowledge of a gene's aliases, so you will need to ensure that genes are named consistently across the datasets you're analyzing. You should modify the matrices before creating the Seurat object
