### ISSUE TITLE
Integration, SCTransform, and clustering

### ISSUE THREAD

**Issue by GHAStVHenry** [satijalab/seurat#3541]
Hey, I'm sorry if this has been answered before, but I couldn't find my exact question/answer in previous issues...

I have integrated the data using SCT assay as described in the vignette...

This includes using the integrated assay for RunPCA, and subsequent RunUMAP.

My question is... is it appropriate to use the reduction PCA that was calculated using the integrated assay for FindNeighbors and resulting FindClusters... or should RunPCA be recalculated using SCT assay first?

**Comment by dlmatera** [comment]
I believe you should use the integrated assay for all clustering/dim reduction, but if you want to explore DEGs, violin plots, etc. Seurat currently recommends using normalized data from the "RNA" assay. You can also include the batch as a latent variable when using FindMarkers to get DEGs, without this I believe you will still have batch effects for these downstream/nonclustering analyses
