### ISSUE TITLE
Add rastering option to DimPlot() and FeaturePlot()

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3542]
If there are many cells, Feature- and DimPlots can get quite large. It would be nice to have an option to raster the points using ggrastr::geom_point_rast().

**Comment by andrewwbutler** [comment]
Hi,

We do have the `AugmentPlot` function in Seurat which will try to do something similar to rasterize the points. However, this was implemented before `ggrastr` came out. Now that `ggrastr` is on CRAN, seems like that may be a better way of handling things. Thanks for the suggestion. We will look into it.

**Comment by saketkc** [comment]
`DimPlot` and `FeaturePlot` on the develop branch support rasterization now, with additional `raster=True` argument. Develop version can be installed using [these](https://satijalab.org/seurat/install.html) instructions.
