### ISSUE TITLE
problem with installing Seurat in R 4.0.2

### ISSUE THREAD

**Issue by SaraAli83** [satijalab/seurat#3543]
Hi, 

I had no problem running Seurat in a previous version of R. However, I had to upgrade it as I want to use a certain package which requires a newer version of R and now I can't seem to be able to install Seurat. I get the following message:

Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so, 6): Symbol not found: _inflateValidate
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libz.1.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/png/libs/png.so

any advice would be greatly appreciated!

**Comment by samuel-marsh** [comment]
Hi,

This appears to be an error with the png package and not Seurat.  I suggest trying to install the png package directly from CRAN and then trying to install Seurat.

Best,
Sam
