### ISSUE TITLE
Plotting a 3rd dimension (color by expression) for FeatureScatter

### ISSUE THREAD

**Issue by Roooosh** [satijalab/seurat#3544]
Hi Seurat team,
Thanks for developing a great package.

I was wondering if it's currently possible to color cells by the expression of a feature (pseudo-third dimension) in the FeatureScatter function.

Currently, I have been adding the genes of interest as columns in my meta.data and calling the group.by parameter for visualization. However, when I do this FeatureScatter treats the group.by parameter as a factor and expands the legend to all unique values. I can get around this converting the "colors" column into a numeric (as.numeric(as.character(colors)) in the returned ggplot2 object, but is there a more simpler/straightforward approach I might be overlooking?

Thanks!

**Comment by mojaveazure** [comment]
Seurat does not offer this functionality. However, you can generate this plot easily with `FetchData` and ggplot2

```R
# Load Seurat and ggplot2
library(Seurat)
library(ggplot2)
# Example dataset
data("pbmc_small")
# Pass the features of interest as the `vars` parameter to FetchData
data <- FetchData(pbmc_small, vars = c('LYZ', 'S100A8', 'MS4A1'))
# Use position = 'jitter' to apply a slight jitter to the points, makes it look nicer
# c('lightgrey', 'blue') are the standard FeaturePlot colors
# cowplot::theme_cowplot() is the the standard theme used in Seurat
ggplot(data = data) +
  geom_point(mapping = aes(x = LYZ, y = S100A8, color = MS4A1), position = 'jitter') +
  scale_color_gradientn(colors = c('lightgrey', 'blue')) +
  cowplot::theme_cowplot()
```
