### ISSUE TITLE
A request for Seurat official website data download.

### ISSUE THREAD

**Issue by BeyondMyPast228** [satijalab/seurat#3545]
Hi,
Thanks for developing this user-friendly tool. Recently, I am studying the analysis of spatial transcriptome data according to the Seurat website tutorial. But I have a problem about data downloads. The download link is shown below.
[
![image](https://user-images.githubusercontent.com/67768651/94219610-d4f03a00-ff19-11ea-91be-71f06bda03b0.png)
](url)
I intends to download this **allen_cortex.rds** to analysis. Unfortunately, I cannot open this download link.
Looking forward to your kind reply.

**Comment by saketkc** [comment]
Hi @BeyondMyPast228, the cortex dataset is hosted on Dropbox at https://www.dropbox.com/s/cuowvm4vrf65pvq/allen_cortex.rds
I can confirm the link is functional. Can you try again?

**Comment by BeyondMyPast228** [comment]
Hi@saketkc, Thanks for your reply. It may be due to network restrictions in my area.Can you send me a copy by email? my email is: 546401632@qq.com

**Comment by saketkc** [comment]
It's around 1GB so sharing on email would not be possible. Here's a Google drive link: 
https://drive.google.com/file/d/1oVTFoRUuLdjvj8x9vVNA4ju8FDabmsLe/view?usp=sharing

**Comment by BeyondMyPast228** [comment]
Thanks for your kind help.
