### ISSUE TITLE
Integration of multiple VISIUM slides + following integration with snSeq data

### ISSUE THREAD

**Issue by mbatiuk** [satijalab/seurat#3546]
Dear Seurat team

I have multiple VISIUM slices with different quality of tissue that I need to integrate with snRNA-Seq data to estimate tissue locations of known cell subtypes.

I've been following your spatial vignette: 
https://satijalab.org/seurat/v3.2/spatial_vignette.html

Previously integrated _each separate_ VISIUM slice separately with snRNA-SEQ reference to get probability scores. But am afraid this way might be biased by different tissue quality in different slices

The question: is there a way to integrate _first_ all VISIUM slices in 1 object to smooth any batch effects/tissue quality differences and then integrate with snRNA-Seq data?

Your spatial vignette mentions 'merge' function to merge different slices together, but this way it is not performing any integration, or am I wrong?

Or shall I proceed with your regular single cell integration pipeline and apply it on VISIUM data:
https://satijalab.org/seurat/v3.2/integration.html

As "SelectIntegrationFeatures", "PrepSCTIntegration", "FindIntegrationAnchors", "IntegrateData"

And then proceed with further integration with snRNA-Seq dataset as in spatial vignette?

Thanks a lot!

**Comment by timoast** [comment]
You should be able to follow the integration vignette treating the visium data just the same as scRNA-seq data
