### ISSUE TITLE
16 pool 10x run : Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#3547]
Hi ,

I'm trying to run 16 pools from 10X using the following script and getting the following error as shown below.
```
combined.list <- lapply(X = combined.list, FUN = function(x) {
  x <- PercentageFeatureSet(x, pattern = "^MT-", col.name = "percent.mt")
  x <- subset(x, subset = nFeature_RNA > 200 & nFeature_RNA < 5200 & percent.mt < 10)
  x <- SCTransform(x, vars.to.regress = "percent.mt", verbose = FALSE)

})


combined.anchors <- FindIntegrationAnchors(object.list = combined.list, dims = 1:20,,k.filter=50) #FindIntegrationAnchors
pbmc.combined <- IntegrateData(anchorset = combined.anchors, dims = 1:20)
DefaultAssay(pbmc.combined) <- "integrated"
pbmc.combined <- ScaleData(pbmc.combined, verbose = FALSE)
pbmc.combined <- RunPCA(pbmc.combined, npcs = 30, verbose = FALSE)

pbmc.combined <- RunUMAP(pbmc.combined, reduction = "pca", dims = 1:20)
pbmc.combined <- RunTSNE(pbmc.combined, reduction = "pca", dims = 1:20)
pbmc.combined <- FindNeighbors(pbmc.combined, reduction = "pca", dims = 1:20)
pbmc.combined <- FindClusters(pbmc.combined,resolution=1.0)
```

Merging dataset 7 13 11 16 6 14 into 15 8 5 9 12 10 1 2 4 3
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds
Calls: IntegrateData ... PairwiseIntegrateReference -> RunIntegration -> FindWeights
Execution halted

Advice to over come this issue is  highly appreciated and thanks in advance

**Comment by timoast** [comment]
You need to run `PrepSCTIntegration` before running `FindIntegrationAnchors`, and set `normalization.method="SCT"` in `FindIntegrationAnchors`

**Comment by bassanio** [comment]
Thanks for the reply and will let you know if that works for me . So that means I should remove ScaleData too from the syntax?

**Comment by bassanio** [comment]
Hi,

 I got the following error after adding the following commands to the existing code above
```
combined.features <- SelectIntegrationFeatures(object.list = combined.list, nfeatures = 3000)
combined.list <- PrepSCTIntegration(object.list = combined.list, anchor.features = combined.features,  verbose = FALSE)

```

Error in getGlobalsAndPackages(expr, envir = envir, globals = globals) : 
  The total size of the 6 globals that need to be exported for the future expression (‘FUN()’) is 7.20 GiB. This exceeds the maximum allowed size of 500.00 MiB (option 'future.globals.maxSize'). The three largest globals are ‘object.list’ (7.20 GiB of class ‘list’), ‘anchor.features’ (192.21 KiB of class ‘character’) and ‘FUN’ (51.16 KiB of class ‘function’).
Calls: PrepSCTIntegration ... getGlobalsAndPackagesXApply -> getGlobalsAndPackages
Execution halted

**Comment by timoast** [comment]
You need to increase `future.globals.maxSize`. See https://satijalab.org/seurat/v3.2/future_vignette.html

**Comment by bassanio** [comment]
Hi ,

I am getting new error after increasing the future.global.maxSize.
```
combined.list <- lapply(X = combined.list, FUN = function(x) {
  x <- PercentageFeatureSet(x, pattern = "^MT-", col.name = "percent.mt")
  x <- subset(x, subset = nFeature_RNA > 200 & nFeature_RNA < 4200 & percent.mt < 5)
  x <- SCTransform(x, vars.to.regress = "percent.mt", verbose = FALSE)
})


library(future)
plan("sequential")
options(future.globals.maxSize = 16000 * 1024^2)

combined.features <- SelectIntegrationFeatures(object.list = combined.list, nfeatures = 3000)
combined.list <- PrepSCTIntegration(object.list = combined.list, anchor.features = combined.features,  verbose = FALSE)
combined.list<- lapply(X = combined.list, FUN = RunPCA, verbose = FALSE, features = combined.features)

combined.anchors <- FindIntegrationAnchors(object.list = combined.list, normalization.method = "SCT", anchor.features = combined.features, verbose= FALSE,reduction = "rpca") 
combined <- IntegrateData(anchorset = combined.anchors, normalization.method = "SCT)

```
This is the error I am getting
```
Merging dataset 1 9 4 12 10 into 7 16 6 8 5 3 13 14 11 15 2
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  fast code path error starting vector near the null space; re-trying with fastpath=FALSE.
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  starting vector near the null space
Calls: IntegrateData ... RunIntegration -> RunPCA -> RunPCA.default -> irlba
Execution halted
```

And also I tried using 
```
plan("multiprocess", workers = 9)
```
which is freezing (It runs for hours and no output is shown) at the step "PrepSCTIntegration".  And If I use the same multiprocess at the beginning of the script the same happens for the SCT loop. Is this expected?

**Comment by bassanio** [comment]
I have created the current issue as  new ticket #3572

**Comment by ajwilk** [comment]
Fwiw, in situations where there are extremely few anchors that pass filtering (eg. very small datasets, poor integration, or both), the error from the OP:
```
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds
Calls: IntegrateData ... PairwiseIntegrateReference -> RunIntegration -> FindWeights
```
can be the first error to appear in the integration pipeline regardless of normalization method used. Would recommend also checking the number and quality of anchors as well as anchor filtering parameters
