### ISSUE TITLE
Subsetting replicates from single Seurat object

### ISSUE THREAD

**Issue by jkim1000** [satijalab/seurat#3549]
I have an integrated seurat object file containing single cell RNA sequencing data across two different experimental conditions from a recent paper. Unfortunately, I don't have access to the raw data but I was wondering if it was possible for me to parse out the object based on the experimental condition and analyze the dataset separately? In other words, I am trying to "unintegrate" the object and to individually analyze the dataset based on the experimental condition without the raw data.

**Comment by cdarby** [comment]
Please check out the Seurat function `subset` . You can create a new Seurat object based on cell names or the value of a feature/metadata/ident.
