### ISSUE TITLE
Rationale for CLR transformation in ADT counts

### ISSUE THREAD

**Issue by benslack19** [satijalab/seurat#3550]
My question has more to do with the rationale and philosophy of using centered log ratio (CLR) transformation for ADT data. From the Biorxiv version of the Stoeckius et al., 2017 paper: "Since each ADT count for a given cell can be interpreted as part of a whole (all ADT counts assigned to that cell), and there are only 13 components in this experiment, we treated this data type as compositional data and applied the centered logratio (CLR) transformation." My questions are:

- Why would only 13 components matter? What is a theoretical cutoff for the number of components where CLR wouldn't be appropriate?
- Why can't log transformation (like what's commonly used for RNA-seq) be used for ADT data?
- Conversely, why isn't CLR transformation applied to RNA-seq data? (I may have partly found an answer to this from [this string](https://github.com/satijalab/seurat/issues/1818): "The CLR method will output a dense matrix, so it may cause a memory issue.")

I attempted to look at this more closely myself by plotting ADT data from the Stuart 2019 paper. Below are ridge plots for CD11a following the `NormalizeData` function but with different normalization methods. On the left, the data is with using `normalization.method = "CLR"`, while on the right is with `normalization.method = "LogNormalize"`.

![image](https://user-images.githubusercontent.com/20425799/94329900-dd755e80-ff73-11ea-8b5f-a3a6dfd377ff.png)

By looking at the x-scale, it's clear that the "noisy" counts with CLR normalized data are brought closer to zero (but not below zero as acknowledged [here](https://github.com/satijalab/seurat/issues/2624). What's interesting is that the group identified as 16 above has lower LogNormalized counts than most groups, but this difference is lost with the CLR normalization.

My interpretation of this is that noise is meant to "look the same" across different groups, which might help better see signal. This seems to be better appreciated in visualizations like ridge plots and tSNE or UMAP plots. Other general reasons for transformations are so that assumptions can be met before performing statistical analysis (like differential expression), but are there examples of statistical analysis on transformed ADT data? Otherwise, I assume that CLR is better for the purposes of visualization and interpretation.

I appreciate your thoughts on your rationale and philosophy for CLR.

**Comment by tomsing1** [comment]
Great questions! I am not an expert, and cannot provide the answer. *But* I you might find this very accessible open-access review by [Quinn et al](https://academic.oup.com/bioinformatics/article/34/16/2870/4956011) useful. 

It highlights e.g. the difference between "transformations" and "normalization" when dealing with compositional data, specifically discussing RNA-seq data.

**Comment by yuhanH** [comment]
@tomsing1  Thanks for showing the excellent review paper!
I think the paper explain greatly about the rationale for the CLR normalization. 
Let me answer your questions briefly. 
For your first question, in our WNN preprint (https://www.biorxiv.org/content/10.1101/2020.10.12.335331v1), we have a pbmc CITEseq with over 200 proteins, and we also apply CLR normalization to it. 
For the second one, due to the unspecific binding background signal, log-normalization doesn't work well in ADT data. 
For the third one, dense matrix is an issue but CLR doesn't work for the counts data containing zero.
