### ISSUE TITLE
label-annotated heatmap using DoHeatmap

### ISSUE THREAD

**Issue by MingwuDuan** [satijalab/seurat#3554]
Hi there,
  does anyone know how this disease- and subject ( donors and patients )-annotated heatmap is plotted? Can Seurat::DoHeatmap sort cells of heatmap into labels? What arguments should be used?
  Thanks in advance!
![捕获](https://user-images.githubusercontent.com/58070294/94417655-edc74c80-01b2-11eb-813f-dc1c5d698914.PNG)

**Comment by Dragonmasterx87** [comment]
Please see #2201 enjoy 😄 

🐉

**Comment by MingwuDuan** [comment]
@Dragonmasterx87 that's very helpful to me, thanks!
