### ISSUE TITLE
DEG expression after SCT normalization and integration question

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#3555]
Hi Satija lab members, in follow-up on [https://github.com/satijalab/seurat/issues/1421](url)

considering this:

> The challenge is that these models can be different from one dataset to another. The model SCTransform learns in one dataset may not be directly applicable to the model learned in another. Out of caution, we therefore do not suggest performing DE on the SCT assay when comparing different datasets.

Would this explain the following?
I have used corrected UMI counts from the [["SCT"]] slot and this works brilliantly. Only now, I integrated two datasets (5 healthy samples, 5 sick samples). When I compare the healthy to the sick for DEG, I basically get housekeeping genes that are differentially expressed and I really don't know what happened. SCT should normalize all of this...

So in more detail what I did:
integrate 5 healthy and check DEG between clusters using SCT: works fine
integrate 5 sick and check DEG between clusters using SCT: works fine

downsample these 10 to 1500 cells per sample and integrate, check DEG between clusters using SCT: works fine BUT when I compare healthy vs sick inside a cluster, the read depth is uneven and I get housekeeping genes.

Is this because the SCT models of healthy and sick are simply not to be combined?

Thanks for all the much-appreciated support.

Nicolaas

**Comment by dlmatera** [comment]
*Not a Satija Lab member

My understanding is that the SCTransform correction factor that Seurat uses to essentially back calculate corrected UMI counts is not absolute but relative&based on the model? As a result it would make sense that housekeeping genes in different datasets are receiving different correction factors and thus have different final counts. Maybe check the expression matrix for cells that do cluster together but are in different datasets (if that happens at all) - if what I said above is true and the correction factors are relative, the ratio of GeneX:Housekeeping gene should be consistent, even if the raw counts are not.

**Comment by jaisonj708** [comment]
SCT regression models from one dataset may not apply to another, since datasets may have different distributions of cell states (e.g, this may manifest as different cell type proportions). Therefore we generally recommend running DE on the `RNA` assay.
