### ISSUE TITLE
Questions about Visium Workflow

### ISSUE THREAD

**Issue by cloitz2** [satijalab/seurat#3556]
Hello,

I am using the Seurat Spatial Vignette/code to process Visium data that we plan to publish (we will of course be citing the Satija lab in our work). Considering the importance of the validity of our data, I would just like to ask a few questions/clarify my workflow is correct.

To begin, we would like to compare a control vs. a treatment that we analyzed with the new Visium technique. There was a discrepancy in thickness between the control vs treatment tissue slices so I first integrated the datasets and then used the SCtransform function on the integrated dataset.  Can you comment on whether you think this workflow is appropriate or whether I should do something different? Our main goal is to compensate for differences in tissue thickness and not have biased DEGS due to thickness.

Next I performed SCtransform in the integrated dataset and then ran through RunPCA, Findneighbors, Findclusters. I noticed that the "SCT" assay was used in the Spatial vignette and I'd just like to check that my understanding of the different assays is correct. The "Spatial" assay contains all the counts obtained from the Visium slide, the "integrated" assay contains the two (control and treatment) datasets, but only what has been created based on the anchors chosen and the SCT dataset is the "normalized" integrated set? Or am I wrong? Also is there a way to combine both datasets without using anchors which keeps all data for both sets?

Also, for certain key genes that we are interested in, I noticed that they will show up in a dotplot or violin plot but not in the DEGs (after using FindAllMarkers with logfc set to 0 and minpct set to 0), can you explain why this may be? Also is the "SCT" assay the most appropriate to use for the dotplots and FindAllMarkers? When should the different assays be used, or once SCtransform is completed should the default assay always be "SCT"?

Here is my workflow/code:

##Load in datasets##
Control = Load10X_Spatial(data.dir = "~/R/Datasets/Selected_spots_visium/Control/outs", filename = "filtered_feature_bc_matrix.h5", assay = "Spatial", slice = "slice2", filter.matrix = TRUE)                

D_25 = Load10X_Spatial(data.dir = "~/R/Datasets/Selected_spots_visium/25D/outs", filename = "filtered_feature_bc_matrix.h5", assay = "Spatial", slice = "slice2", filter.matrix = TRUE)                

##Remove mitchondrial genes##
Control[["percent.mt"]] <- PercentageFeatureSet(Control, pattern = "^MT-")
Control <- subset(x = Control, subset = percent.mt < 15)

D_25[["percent.mt"]] <- PercentageFeatureSet(D_25, pattern = "^MT-")
D_25 <- subset(x = D_25, subset = percent.mt < 15)

##Label two different datasets
Control$treat <- "Control"
D_25$treat <- "D_25"

##Integrate both datasets##
anchors <- FindIntegrationAnchors(object.list = list(Control, D_25), dims = 1:50)
integrated <- IntegrateData(anchorset = anchors, dims = 1:50)

##"Normalize"/process/cluster
integrated = SCTransform(integrated, assay = "Spatial", verbose = TRUE)
integrated <- RunPCA(integrated, assay = "SCT", verbose = TRUE)
integrated <- FindNeighbors(integrated, reduction = "pca", dims = 1:40)
integrated <- FindClusters(integrated, resolution = 0.35, verbose = TRUE)
integrated <- RunUMAP(integrated, reduction = "pca", dims = 1:40)

##Separate "treatments"##
integrated$celltype.treat <- paste(Idents(integrated), integrated$treat, sep = "_")
integrated$celltype <- Idents(integrated)
Idents(integrated) <- "celltype.treat"

##Find Degs##
DefaultAssay(object = integrated) = "SCT"
integrated_Degs_LT_0_minpct_DBP = FindAllMarkers(integrated, assay = "SCT", min.pct = FALSE, logfc.threshold = 0)

Thank you very much!!

**Comment by jaisonj708** [comment]
Normalization by SCTransform should account for differences in tissue thickness (in the same way that normalization regresses out the effect of sequencing depth in non-spatial RNA seq). If you suspect that there are also batch effects, you may integrate, but we would recommend doing this after normalizing your data, not before.

Your understanding of the assays is correct, and we recommend running differential expression tests on `SCT` rather than `integrated`.

An absolute difference in expression between groups does not always imply statistical significance. If you would like to see the p-values for more genes, you can increase the `return.thresh` parameter in `FindAllMarkers`.
