### ISSUE TITLE
No Negative clusters HTO hashing

### ISSUE THREAD

**Issue by clairebio27** [satijalab/seurat#3557]
HI ,

I was trying to do the HTOdemux for the cell hash data. I have loaded the 10X count matrix and following the Demux vignette for demultplexing the HTOs. I have 7 HTOs in the sample and used follo: command to demux,
pbmc.hashtag <- HTODemux(pbmc.hashtag, assay = "HTO", positive.quantile = 0.99)
Also tried with different   positive.quantile like 0.90, 0.85, but all the run produced "Singlets" and "Doublets" only. I did not get any "Negative" cells. 

Question: Does it mean the data dont' have any Negative cells? or any issu ein my parameters?

One sample demux threw the error "Cells with zero counts exist as a cluster". When I run the average expression, I have the following results:
HTO1-TotalSeqC	9.2644393
HTO2-TotalSeqC	10.1120357
HTO3-TotalSeqC	10.3835237
HTO4-TotalSeqC	3.6104597
HTO5-TotalSeqC	0.6597748
HTO6-TotalSeqC	0.4624217
HTO7-TotalSeqC	41.8568070

from the related search in the forum, I understand that HTO5 and HTO6 do have very low cell counts and need to remove from processing. 
Question: Do you have any built in function to remove those HTOs from the Seurat object?

Thanks,
Claire

**Comment by frederikziebell** [comment]
If I understand the code in `HTODemux()` correctly, then you get this error if there is _at least one_ HTO in _any_ of the clusters where all counts of this HTO are zero. The rationale is that all p-values would be zero when testing against this null distribution. Maybe the method could be improved if one instead would test against the union of all other clusters.

**Comment by torkencz** [comment]
Thank you for the suggestion we'll look into it.
