### ISSUE TITLE
differential expression between two different clusters in two groups

### ISSUE THREAD

**Issue by thugib** [satijalab/seurat#3558]
I have a Seurat object that by anchoring has combined a control ("minus") and treatment ("plus") sc experiments. When clustered, the treatment ("plus")  has a cluster of cells (we will call it cluster # 2) in which no cells appear in the control. I think that this cluster having cells only in the treatment condition (cluster 2) is comprised of cells reprogrammed by the treatment, and I would like to do differential expression between these cells unique to the treatment condition with a cluster that has cells in both control and treatment (say, cluster # 1). 

My Seurat object has an added metadata called "treatment", that can be one of two values;  "plus" or "minus". 

So, I can do differential expression between "plus" and "minus" for a single cluster (cluster # 1) that has cells in both control and treatment. For that, I used:
``` 
ABCpm.DESeq2 <- FindMarkers(ABCpm, ident.1 = "plus", group.by = "treatment", subset.ident = "1", test.use = "DESeq2")
```
How could I compare cluster #2 in the "plus" treatment with cluster #1 in the "minus" treatment ?

**Comment by jaisonj708** [comment]
I would recommend re-defining your idents. e.g, instead of having two separate metadata data factors for treatment and cluster, combine them into 1_plus, 1_minus, 2_plus, etc
