### ISSUE TITLE
How to fix the "NA" values in merged Seurat objects

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#3559]
Hi. After integrating the 2 Seurat objects "TCE.7K" and "TCS.16K" datasets, which both have a response column with values "R" and "NR", I visualized it by `group.by()` and `split.by()` function. However, a new group of datapoints "NA" exists only in visualization. Where did this come from, are these trash information, and how can I get rid of them if they not useful? Please, may I ask for your help?

**VISUALIZATION OF CLUSTERING ACCORDING TO GROUPS**
```
A <- DimPlot(TC.combinedFINAL, reduction = "umap", label = TRUE) #2 datasets integrated
B <- DimPlot(TC.combinedFINAL, reduction = "umap", group.by = "dataset") #visualize accdg to dataset origin
C <- DimPlot(TC.combinedFINAL, reduction = "umap", split.by = "response") #visualize accdg to response
```

**VISUALIZATIONS REVEAL AN "NA" GROUP OF DATAPOINTS(?)**

**FIGRUE A:**
![image](https://user-images.githubusercontent.com/68268222/94650378-28eb8c00-0329-11eb-87c9-f2c04a99ce05.png)

**FIGURE B:**
![image](https://user-images.githubusercontent.com/68268222/94650422-3f91e300-0329-11eb-9e35-a455087760a4.png)

**FIGURE C:**
![image](https://user-images.githubusercontent.com/68268222/94650566-8bdd2300-0329-11eb-8758-6d3cc4cc3cce.png)

**CHECKING FOR UNIQUE CATEGORIES INSIDE THE COLUMNS**
```
> table(TC.combinedFINAL@meta.data$dataset)
 TCE.7K TCS.16K 
   7186   15300 

> table(TC.combinedFINAL@meta.data$response)
   NR     R 
10190 12296 
```

**CHECKING THE SOURCE OF "NA" FROM THE DATAFRAME/SEURAT OBJECT**
 ```

>names(TC.combinedFINAL@meta.data) #check what are all columns 
[1] "orig.ident"             "nCount_RNA"             "nFeature_RNA"           "cell_id"                "dataset"               
[6] "response"               "integrated_snn_res.0.5" "seurat_clusters" 

which(TC.combinedFINAL@meta.data$orig.ident == NA)
which(TC.combinedFINAL@meta.data$nCount_RNA == NA)
which(TC.combinedFINAL@meta.data$nFeature_RNA == NA)
which(TC.combinedFINAL@meta.data$cell_id == NA)
which(TC.combinedFINAL@meta.data$dataset == NA)
which(TC.combinedFINAL@meta.data$response == NA)
which(TC.combinedFINAL@meta.data$integrated_snn_res.0.5" "seurat_clusters == NA)
```

 **ALL OF THESE THE OUTPUT IS:** 
`integer(0)
`

**Comment by timoast** [comment]
Your checks here aren't accurate. `table` will exclude NA values by default, and `NA == NA` will return `NA`. The proper way to check if a value is `NA` in R is with the `is.na()` function. If you run `sum(is.na(TC.combined$response))` my guess would be that it returns a non-zero value.

**Comment by levinhein** [comment]
Hi @timoast thanks for your reply! My apologies, I'm just very new in R in and bioinformatics. 

I ran the following to my integrated Seurat object and here are the outputs. Indeed, the `sum(is.na())` function returned a 991, as shown below. May I ask for your help on what should be the next step that I should do? Thank you in advance!


`> is.na(TC.combinedFINAL@meta.data)
`![image](https://user-images.githubusercontent.com/68268222/95020817-04344300-06a0-11eb-92f8-8166d79efa33.png)

`> is.na(TC.combinedFINAL@meta.data$response)
`![image](https://user-images.githubusercontent.com/68268222/95020849-3f367680-06a0-11eb-9d0b-8548be4fdf78.png)

`> sum(is.na(TC.combinedFINAL@meta.data$response))
`![image](https://user-images.githubusercontent.com/68268222/95020925-a2c0a400-06a0-11eb-8ba8-b96c6f2efe05.png)
