### ISSUE TITLE
Website correction about R version

### ISSUE THREAD

**Issue by bwray** [satijalab/seurat#3562]
It seems like Seurat won't install in R >= 4.0.0. There are dependencies that maybe aren't available when installing with the latest versions of R (at least on macOS and Linux). Downgrading to R 3.6.3 resolved this for me.

**Comment by timoast** [comment]
I am using Seurat on macOS and linux with R 4.0.1 so can confirm that it does install and works.

**Comment by mojaveazure** [comment]
I'm able to install Seurat v3.2.2 (latest release) on Ubuntu 18.04 and 20.05 and Debian 10 Buster under R 4.0.0, 4.0.1, and 4.0.2; please provide the error message that you're seeing.

**Comment by bwray** [comment]
I retract, sorry about that. I was getting errors about certain dependencies not loading, though I can't remember exactly which ones were giving me the error. I reinstalled R 4.0.2 to reproduce the errors, but I was then able to install Seurat successfully. Probably a ghost or something.
