### ISSUE TITLE
Mapping top 10 clonotypes

### ISSUE THREAD

**Issue by betsleve** [satijalab/seurat#3564]
Hello I am trying to map the top 10 expanded clonotypes on my UMAP. I used this to identify the top 10 clonotypes
top10_clonotype <- table(Object$clonotype_id)
top10_clonotype <- as.data.frame(top10_clonotype)
top10_clonotype <- slice_max(top10_clonotype, order_by = top10$Freq, n=11)
I then ran 
DimPlot(AD007, reduction = "umap", cells.highlight=top10)
while i did get some cells highlighted in the umap it was not completely correct. For example the top clonotype was expanded 22 times yet only one dot showed up instead of 22. Do you have any suggestions? Thank you!

**Comment by jaisonj708** [comment]
Could you post the complete code? You don't initialize the `top10` object here.

**Comment by betsleve** [comment]
Yes sorry. Here is the whole code I am using

`AD007.data <- Read10X(data.dir = "/Users/Desktop/AD007")
AD007S <- CreateSeuratObject(counts=AD007.data, Project="MOGAD",min.cells = 2,
                            min.features = 200)



#####
#Adding the Clonotype as metadata ####
AD007S_clonotype<- read.csv("/Users/Desktop/AD007vdj/outs/filtered_contig_annotations.csv")

#Subset to get the clonotype ID and barcode
AD007S_clonotype<- AD007S_clonotype[,c("barcode","raw_clonotype_id")]
#Remove duplicates
AD007S_clonotype <- AD007S_clonotype[!duplicated(AD007S_clonotype$barcode),]
#Setting the rownames/colnames(colnames have to match up with metadata name)
rownames(AD007S_clonotype)<- AD007S_clonotype[,1]
AD007S_clonotype[,1]<-NULL
names(AD007S_clonotype)[names(AD007S_clonotype) == "raw_clonotype_id"] <- "clonotype_id"
#Setting the metadata
AD007S$clonotype_id<- "none"
View(AD007S_clonotype)
AD007S <- AddMetaData(object = AD007S, metadata = AD007S_clonotype)
AD007S$clonotype_id
n_distinct(AD007S$clonotype_id)

AD007S$clonotype_id <- as.factor(AD007S$clonotype_id)
str(AD007S@meta.data$clonotype_id)

View(AD007S)
##finding top 10 clonotype
top10_clonotype <- table(AD007S$clonotype_id)
top10_clonotype <- as.data.frame(top10_clonotype)
top10_clonotype <- slice_max(top10_clonotype, order_by = top10$Freq, n=11)
View(top10)
top10 <- slice_max( as.vector(unlist(top10)), n=11)



#####




### preprocessing
  ## [[]]- adds meta data to the seurat object
AD007S[["percent.mt"]] <- PercentageFeatureSet(AD007S, pattern = "^MT-")
     
AD007 <-subset(AD007S, subset= nFeature_RNA>200 & nFeature_RNA <6000 & nCount_RNA >100 & nCount_RNA < 20000 & percent.mt <10)


##normalization
AD007 <- NormalizeData(AD007)

## high cell to cell variation n= 20000
AD007 <- FindVariableFeatures(AD007, selection.method = "vst", nfeatures = 2000)
top10 <-head(VariableFeatures(AD007),10)

##scaling so highly expressed genes dont dominate
all.genes <- rownames(AD007)
AD007 <- ScaleData(AD007, features = all.genes)
unwanted_genes <- grep(pattern = "^HLA*|^IGHV*|^IGHJ*|^IGHD*|^IGKV*|^IGLV*|^TRBV*|^TRBD*|^TRBJ*|^TRDV*|^TRDD*|^TRDJ*|^TRAV*|^TRAJ*|^TRGV*|^TRGJ*", x = AD007@assays$RNA@var.features, value = T)
remove_genes <- AD007@assays$RNA@var.features %in% unwanted_genes
AD007@assays$RNA@var.features = AD007@assays$RNA@var.features[!remove_genes]

AD007 <- RunPCA(AD007, features = VariableFeatures(object = AD007))
AD007 <- JackStraw(AD007, num.replicate = 100)
AD007 <- ScoreJackStraw(AD007, dims = 1:20)
ElbowPlot(AD007)

## clustering
AD007 <- FindNeighbors(AD007, dims = 1:16)
AD007 <- FindClusters(AD007, resolution = 0.5)
AD007 <- RunUMAP(AD007, dims = 1:16)
`

Thank you!

**Comment by jaisonj708** [comment]
It looks like `top10` is a vector of features, but you are then passing this as the `cells.highlight` parameter in `DimPlot`. You should only pass cell names or indices here.
