### ISSUE TITLE
FindTransferAnchors for cell type annotation - question

### ISSUE THREAD

**Issue by jgamache014** [satijalab/seurat#3566]
Does it matter if reference and query datasets are pre-processed in the same way prior to running FindTransferAnchors? As in the example below, if the query has been normalized, scaled, and has variable features identified, should that also be done to the reference? 

I am also wondering - if the query dataset is integrated but the reference is not, should the 'RNA' assay be specified for the query when running FindTransferAnchors?

```
reference_seurat <- NormalizeData(object = reference_seurat)
reference_seurat <- FindVariableFeatures(object = reference_seurat, selection.method = 'vst', nfeatures = 2000)
reference_seurat <- ScaleData(reference_seurat)

query_seurat <- NormalizeData(object = query_seurat)
query_seurat <- FindVariableFeatures(object = query_seurat, selection.method = 'vst', nfeatures = 2000)
query_seurat <- ScaleData(query_seurat)

##prediction###
sim.anchors <- FindTransferAnchors(reference = reference_seurat, query = query_seurat,
                                   dims = 1:30)
##replace Group with the actual column name from meta
predictions <- TransferData(anchorset = sim.anchors, refdata = reference_seurat$Group,
                            dims = 1:30)
query_seurat <- AddMetaData(object = query_seurat, metadata = predictions)
```

(Note: this code was taken from https://github.com/qianhuiSenn/scRNA_cell_deconv_benchmark/blob/master/Scripts/Seurat_sample_usage.R, "Evaluation of Cell Type Annotation R Packages on Single Cell RNA-seq Data", Huang et al., bioRxiv)

**Comment by jaisonj708** [comment]
`FindTransferAnchors` will automatically apply the same scaling transformation to your query that was applied to your reference. As far as normalization, you should use the same method for both your query and reference (i.e, if SCTransform was applied to one, use it for the other as well). It is okay to use an integrated dataset as your query.

**Comment by jgamache014** [comment]
Thank you! A few follow-up questions:

The only way I could get this to work was using project.query = TRUE (I think because I had more cells in the query than reference). I also had to specify "RNA" for query.assay because when I specified "integrated", I got the error message `Error in irlba(A = t(x = object), nv = npcs, ...) : max(nu, nv) must be positive` when FindTransferAnchors() attempted to run a PCA on the integrated data. I read that this error is due to lack of running FindVariableFeatures(), but 2000 var.features were already stored in the integrated data slot. **Why couldn't a PCA be run on the integrated dataset?** 

My "RNA" assay data was made by normalizing raw counts and running FindVariableFeatures() on individual samples before integration. After integration, there were no var.features stored in the RNA data slot - **why is that** (Also, if you normalize individual samples before integration, is the data stored in the "RNA" assay of the integrated Seurat object normalized, or do you have to re-normalize it?) 

Because I could not run FindTransferAnchors() with the "integrated" data and because there were no var.features in my "RNA" data slot after integration, I ran FindVariableFeatures() again on the compiled RNA data, then scaled the RNA data. This was the only way I could get FindTransferAnchors() to run. With project.query = TRUE, a PCA was run on the query (normalized, var.feat, scaled "RNA" data of an integrated Seurat object) and projected onto the reference, right? **If my query was already scaled, did FindTransferAnchors() automatically re-scale it?** 

In the future, I want to run DE analyses with the wilcoxon rank sum test on my query dataset. I read that it is not advised to use "integrated" assay data for this because that violates an assumption of this statistical test that samples need to independent of one another. So I will need to use the "RNA" assay data, which has been now been scaled in order to get FindTransferAnchors() to work. **Is there a way to specify normalized unscaled "RNA" data for DE analyses using FindMarkers()? Or is it recommended to duplicate the raw counts in a new assay and normalize those for FindMarkers()?**

**Comment by jgamache014** [comment]
Thank you! I cannot re-open the issue for my follow-up questions, so to
make sure you see them I will also post them here:

The only way I could get this to work was using project.query = TRUE (I
think because I had more cells in the query than reference). I also had to
specify "RNA" for query.assay because when I specified "integrated", I got
the error message Error in irlba(A = t(x = object), nv = npcs, ...) :
max(nu, nv) must be positive when FindTransferAnchors() attempted to run a
PCA on the integrated data. I read that this error is due to lack of
running FindVariableFeatures(), but 2000 var.features were already stored
in the integrated data slot. Why couldn't a PCA be run on the integrated
dataset?

My "RNA" assay data was made by normalizing raw counts and running
FindVariableFeatures() on individual samples before integration. After
integration, there were no var.features stored in the RNA data slot - why
is that (Also, if you normalize individual samples before integration, is
the data stored in the "RNA" assay of the integrated Seurat object
normalized, or do you have to re-normalize it?)

Because I could not run FindTransferAnchors() with the "integrated" data
and because there were no var.features in my "RNA" data slot after
integration, I ran FindVariableFeatures() again on the compiled RNA data,
then scaled the RNA data. This was the only way I could get
FindTransferAnchors() to run. With project.query = TRUE, a PCA was run on
the query (normalized, var.feat, scaled "RNA" data of an integrated Seurat
object) and projected onto the reference, right? If my query was already
scaled, did FindTransferAnchors() automatically re-scale it?

In the future, I want to run DE analyses with the wilcoxon rank sum test on
my query dataset. I read that it is not advised to use "integrated" assay
data for this because that violates an assumption of this statistical test
that samples need to independent of one another. So I will need to use the
"RNA" assay data, which has been now been scaled in order to get
FindTransferAnchors() to work. Is there a way to specify normalized
unscaled "RNA" data for DE analyses using FindMarkers()? Or is it
recommended to duplicate the raw counts in a new assay and normalize those
for FindMarkers()?
