### ISSUE TITLE
Gene Expression Values in Seurat Data

### ISSUE THREAD

**Issue by Bettariccardo** [satijalab/seurat#3567]
Hello, i have a question for you,

Is it possible to visualize expression values for each gene in my dataset (2000 cells x 16000 genes), without cluster the cells?

If the answer is positive, where is data stored inside the Seurat Object?

I need this information for GO analysis and i want to use only the genes that are over expressed.

Thanks in advance for you time

Riccardo

**Comment by mojaveazure** [comment]
See [`FeaturePlot`](https://rdrr.io/cran/Seurat/man/FeaturePlot.html) and [`FetchData`](https://rdrr.io/cran/Seurat/man/FetchData.html)
