### ISSUE TITLE
UMAP object with RunUMAP(return.model=T)?

### ISSUE THREAD

**Issue by mdidish** [satijalab/seurat#3570]
Dear,

I just saw that there is a `return.model` argument from Seurat 3.2.1 in the `Run.UMAP()` function.
This creates a new slot `seurat.objet@reductions$umap@misc$model`.

Is it possible to extract an umap object from this slot?
The goal would be to project a new dataset on the UMAP as suggested here: https://github.com/satijalab/seurat/issues/810

Thank you.
Marc

**Comment by mdidish** [comment]
ok it works with the `reduction.model` argument:
```
Exp1.integrated <- RunUMAP(Exp1.integrated, reduction = "pca", dims = 1:12, verbose = F, return.model = T)
Exp2.integrated <- RunUMAP(Exp2.integrated, reduction = "pca", dims = 1:12, verbose = F, reduction.model = Exp1.integrated@reductions$umap)
```

I have two questions:

1/ Are we agree that I have to normalize each dataset with SCtransform independently (each dataset containing a control experiment and a treatment experiment)?

2/ Is it possible to "integrate" the second dataset (Exp2.integrated) into the first (Exp1.integrated), in order to be able to easily plot UMAPs and other comparative plots (for example with `split.by`)?

In any case a big thank you for this very informative function!

**Comment by SiyiWanggou** [comment]
Should we firstly combine Exp1.integrated and Exp2.integrated for PCA to get the same dims? I found the dims from the two obejcts are different. It is hard to project Exp2 to Exp1 UMAP precisely. Is there any suggestion? Thanks.

**Comment by mdidish** [comment]
@SiyiWanggou In my case, I have integrated two datasets (control and treatment) in Exp1.integrated, and we have identified several clusters of interest and their evolution with the treatment.

Now, I would like to project two other control and treatment datasets with a gene KO on this UMAP, to visualize the effect of this KO on previously studied clusters (I don't want to start all over by integrating the 4 datasets and doing a new clustering).

The problem is that the function provided by Seurat gives amazing results. I have done many tests, and each time there are very few cells projected on cluster '0' (the one with the most cells).
Mainly, I did a test by reprojecting the same dataset, and again there is almost no cell projected on this cluster '0'.

In [this vignette](https://cran.r-project.org/web/packages/umap/vignettes/umap.html), the data is projected onto itself with very good results. So it would be interesting to create a UMAP object from the Seurat object as suggested [here](https://github.com/satijalab/seurat/issues/810), to be able to use this package, but I have not found a solution for the moment.

I still hope that authors of Seurat will suggest some solution.

**Comment by marcRDM** [comment]
@mdidish, I am having the same issue (very few cells projected onto my most abundant reference cluster), did you find a way to hack this..?

**Comment by mdidish** [comment]
No I didn't find a solution.
I see a new vignette with a paragraph about "Project each query cell onto a previously computed UMAP visualization", but I didn't try yet :
https://satijalab.org/seurat/v4.0/reference_mapping.html

If you try it, can you tell us if you have a better result ?

**Comment by marcRDM** [comment]
@mdidish, I just gave it a go and it gives better results indeed! ("better" = closer to what I was expecting)

**Comment by mdidish** [comment]
thank you for your feedback, I have to try with my data

**Comment by yuhanH** [comment]
HI, @mdidish 
sorry for the delay.  i think our new [single modality mapping vignette](https://satijalab.org/seurat/articles/integration_mapping.html) can solve your questions. 
It is not necessary to use SCTransform to do the mapping. 

For the treatment analysis, we would suggest you use Integration for the treated and untreated cells. 
You can follow this [vignette](https://satijalab.org/seurat/articles/integration_introduction.html) which did a comparison of PBMC in resting and interferon-stimulated state.
