### ISSUE TITLE
Error in irlba(A = t(x = object), nv = npcs, ...) : starting vector near the null space + multiprocess

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#3572]
Hi ,

```
combined.list <- lapply(X = combined.list, FUN = function(x) {
  x <- PercentageFeatureSet(x, pattern = "^MT-", col.name = "percent.mt")
  x <- subset(x, subset = nFeature_RNA > 200 & nFeature_RNA < 4200 & percent.mt < 5)
  x <- SCTransform(x, vars.to.regress = "percent.mt", verbose = FALSE)
})


library(future)
plan("sequential")
options(future.globals.maxSize = 16000 * 1024^2)

combined.features <- SelectIntegrationFeatures(object.list = combined.list, nfeatures = 3000)
combined.list <- PrepSCTIntegration(object.list = combined.list, anchor.features = combined.features,  verbose = FALSE)
combined.list<- lapply(X = combined.list, FUN = RunPCA, verbose = FALSE, features = combined.features)

combined.anchors <- FindIntegrationAnchors(object.list = combined.list, normalization.method = "SCT", anchor.features = combined.features, verbose= FALSE,reduction = "rpca") 
combined <- IntegrateData(anchorset = combined.anchors, normalization.method = "SCT)

```
This is the error I am getting
```
Merging dataset 1 9 4 12 10 into 7 16 6 8 5 3 13 14 11 15 2
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  fast code path error starting vector near the null space; re-trying with fastpath=FALSE.
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  starting vector near the null space
Calls: IntegrateData ... RunIntegration -> RunPCA -> RunPCA.default -> irlba
Execution halted
```

And also I tried using 
```
plan("multiprocess", workers = 9)
```
which is freezing (It runs for hours and no output is shown) at the step "PrepSCTIntegration".  And If I use the same multiprocess at the beginning of the script the same happens for the SCT loop. Is this expected?

**Comment by bassanio** [comment]
hi can some one please help me on this issue

**Comment by sbdaxia** [comment]
Hi there! 

Unfortunately I am also running into the same issue. I have a dataset of 34 samples with ~50K cells in total. I have previously tried to use the SCTransformation based integration workflow to integrate the samples and ran into the following error
```
Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:535
Calls: IntegrateData ... validObject -> anyStrings -> isTRUE -> validityMethod
Execution halted
``` 
I tried reference-based integration and It worked but I really preferred not to select a reference dataset for my integration. So I changed my pipeline to the RPCA based integration method + SCTransform normalization (with no reference).

Here is the code I used to initiate the integration process:

```
suppressMessages(suppressWarnings(for (i in 1:length(split_seurat)) {
  split_seurat[[i]] <- NormalizeData(split_seurat[[i]], verbose = FALSE)
  split_seurat[[i]] <- CellCycleScoring(split_seurat[[i]], g2m.features=g2m_genes, s.features=s_genes, , verbose = FALSE)
  split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = c("mitoRatio"), , verbose = FALSE)
  split_seurat[[i]] <- FindVariableFeatures(split_seurat[[i]], verbose = FALSE)
}))

integ_features <- SelectIntegrationFeatures(object.list = split_seurat, 
                                            nfeatures = 3000) 

split_seurat <- lapply(X = split_seurat, FUN = function(x) {
    x <- RunPCA(x, features = integ_features, verbose = FALSE)
})

split_seurat <- PrepSCTIntegration(object.list = split_seurat, 
                                   anchor.features = integ_features,
                                   verbose = FALSE)

suppressMessages(integ_anchors <- FindIntegrationAnchors(object.list = split_seurat, 
                                        normalization.method = "SCT", 
                                        anchor.features=integ_features,
                                        reduction = "rpca",
                                        dims = 1:50))

suppressMessages(seurat_integrated <- IntegrateData(anchorset = integ_anchors, 
                                   normalization.method = "SCT",
                                   dims = 1:50))
```

But then I run into the same error described by @bassanio, it occurs near the end of the integration process:
```
Integrating data
Merging dataset 16 17 4 12 26 14 into 25 27 22 24 8 23 15 2 13 3 34 33 11 21 9 10 19 20 5 29 6 31 32 30 18 7
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  fast code path error starting vector near the null space; re-trying with fastpath=FALSE.
Error in irlba(A = t(x = object), nv = npcs, ...) :
  starting vector near the null space
Calls: IntegrateData ... RunIntegration -> RunPCA -> RunPCA.default -> irlba
Execution halted
```

It seems like these errors are due to the large number of samples I have (34), as the pipeline worked fine when I try to integrate a portion of the samples (24).

My session info:
```
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /n/app/openblas/0.2.19/lib/libopenblas_core2p-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Seurat_3.2.2.9012

loaded via a namespace (and not attached):
 [1] httr_1.4.2            tidyr_1.1.2           jsonlite_1.7.1
 [4] viridisLite_0.3.0     splines_4.0.1         leiden_0.3.5
 [7] shiny_1.5.0           ggrepel_0.8.2         globals_0.14.0
[10] pillar_1.4.7          lattice_0.20-41       glue_1.4.2
[13] reticulate_1.18       digest_0.6.27         polyclip_1.10-0
[16] RColorBrewer_1.1-2    promises_1.1.1        colorspace_2.0-0
[19] cowplot_1.1.0         htmltools_0.5.0       httpuv_1.5.4
[22] Matrix_1.2-18         plyr_1.8.6            pkgconfig_2.0.3
[25] listenv_0.8.0         purrr_0.3.4           xtable_1.8-4
[28] patchwork_1.1.0       scales_1.1.1          RANN_2.6.1
[31] tensor_1.5            later_1.1.0.1         Rtsne_0.15
[34] spatstat.utils_1.17-0 tibble_3.0.4          mgcv_1.8-31
[37] generics_0.1.0        ggplot2_3.3.2         ellipsis_0.3.1
[40] ROCR_1.0-11           pbapply_1.4-3         lazyeval_0.2.2
[43] deldir_0.2-3          survival_3.1-12       magrittr_2.0.1
[46] crayon_1.3.4          mime_0.9              future_1.20.1
[49] parallelly_1.21.0     nlme_3.1-148          MASS_7.3-51.6
[52] ica_1.0-2             tools_4.0.1           fitdistrplus_1.1-1
[55] data.table_1.13.2     lifecycle_0.2.0       matrixStats_0.57.0
[58] stringr_1.4.0         plotly_4.9.2.1        munsell_0.5.0
[61] cluster_2.1.0         irlba_2.3.3           compiler_4.0.1
[64] rsvd_1.0.3            rlang_0.4.8           grid_4.0.1
[67] ggridges_0.5.2        goftest_1.2-2         RcppAnnoy_0.0.17
[70] htmlwidgets_1.5.2     igraph_1.2.6          miniUI_0.1.1.1
[73] gtable_0.3.0          codetools_0.2-16      abind_1.4-5
[76] reshape2_1.4.4        R6_2.5.0              gridExtra_2.3
[79] zoo_1.8-8             dplyr_1.0.2           uwot_0.1.9
[82] fastmap_1.0.1         future.apply_1.6.0    KernSmooth_2.23-17
[85] spatstat.data_1.5-2   stringi_1.5.3         spatstat_1.64-1
[88] parallel_4.0.1        Rcpp_1.0.5            rpart_4.1-15
[91] vctrs_0.3.5           sctransform_0.3.1     png_0.1-7
[94] tidyselect_1.1.0      lmtest_0.9-38
```

So I am wondering if there is a viable way to integrate large number of samples without specifying a reference?

Thank you so much for your help!

Bing

**Comment by saketkc** [comment]
Hi Bing, can you try reducing the dimensions for `IntegrateData` to say 30 and see if that helps?

**Comment by sbdaxia** [comment]
Hi Saket, thank you for your recommendation. I tried `IntergrateDate` with 30 dimensions and ran into the same error. Error message shown below

```
Integrating data
Merging dataset 16 17 4 12 26 14 into 25 27 22 24 8 23 15 2 13 3 34 33 11 21 9 10 19 20 5 29 6 31 32 30 18 7
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  fast code path error starting vector near the null space; re-trying with fastpath=FALSE.
Error in irlba(A = t(x = object), nv = npcs, ...) :
  starting vector near the null space
Calls: IntegrateData ... RunIntegration -> RunPCA -> RunPCA.default -> irlba
Execution halted
```

Do you have any other thought on how to get around this issue?

Thank you!

Bing

**Comment by saketkc** [comment]
If you are able to reproduce this with a small dataset that you can share with me at schoudhary@nygenome.org, I can take a look. What version of Seurat are you using?

**Comment by sbdaxia** [comment]
I will try to recreate the error with a smaller file and and share it with you via Dropbox soon. I was using Seurat_3.2.2.9012 since this is the development version of Seurat that was recommended in the RPCA integration vignette. My complete session info can be found in the initial post I made.

Thank you!

**Comment by sbdaxia** [comment]
Hi @saketkc!

Sorry about the delay on my end. I tried to reproduce the error as you suggested using a smaller dataset. So I generated a mini dataset from the original dataset (34 samples of 1-2k cells/sample) by randomly sampling 100 cells per sample and then performed the RPCA based integration process as I did with the original dataset. However, I was not able to reproduce the error as the integration actually worked on the mini dataset. So the error mentioned above seems to be specific to a large dataset with many samples and many cells per sample.

To note, when I ran the  following command to prepare for integration
```
split_seurat <- lapply(X = split_seurat, FUN = function(x) {
  x <- RunPCA(x, features = integ_features, verbose = FALSE)
})
```
I encounter the following warning message:
```
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
```

Do you have any recommendation as to how to proceed? Happy to share the large original dataset if needed.

Thank you!

Best,
Bing

**Comment by vertesy** [comment]
Hello @sbdaxia, did you find any solution?

There is also no logical reference datasets in my case.
1. I have 38 10X datasets, normalize them old school (not SCT)
2. I calculate the `anchors` (rPCA, CCA both work)
3. `IntegrateData` fails every time after running multicore for several hours

Tried and did not help:
1.  Calculate Anchor set with reverse pCA
2. Reduce the nr. of genes to ~2500 in `features.to.integrate` (in `IntegrateData`).
3. Reduce the dimensions from 50 to 30 in `features.to.integrate` (in `IntegrateData`).

**Comment by sbdaxia** [comment]
Hi @vertesy, I was not able to directly resolve the issue.

Here are a few things that I did:
1. I performed reference-based integration by selecting 1 sample from each condition to make up the set of references.
2. Then I subset the whole dataset and ran SCT-based integration on the smaller datasets and compared the integration with the reference-based integration on the complete dataset.

One thing I was considering doing was a hierarchical integration but there has been some debate about whether that approach is actually valid.

Hope this helps!

**Comment by vertesy** [comment]
Thanks @sbdaxia! 

I will keep retrying the rPCA, if fails, 
then I will try "merge" (stupid merge) biological replicates first, then CCA datasets together.
The reference based is totally unjustified in my case, so that's a last option. Thanks again!

cheers!
