### ISSUE TITLE
get information of avg_logFC,pct,p value from FindSpatiallyVariableFeatures

### ISSUE THREAD

**Issue by icanwinwyz** [satijalab/seurat#3575]
Hi,
Thanks for developing Seurat, such a great tool for single cell data analysis.

I am working on the spatial transcritpome data and using "FindSpatiallyVariableFeatures" to find clusters specific markers. However, it seems like I can only retrieve the gene name based on the tutorials. I am wondering which function that I can use to get the information of avg_logFC,pct,p value like  "FindAllMarkers"? Thanks.

Joe

**Comment by mojaveazure** [comment]
You need to use `FindMarkers` or `FindAllMarkers` to get the information you need. `FindSpatiallyVariableFeatures` simply finds features that have spatially-constrained variability in expression and reports said features.
