### ISSUE TITLE
Regress out variables in integrated data

### ISSUE THREAD

**Issue by fisherj-2212** [satijalab/seurat#3579]
I am working with data integrated using the standard method. The integrated data is comprised of three objects, one of which seems to be generally lower quality than the others. I am unsure if trying to regress out variables on the integrated object during data scaling is sensible. Although the integration has worked well for mixing my different samples for downstream clustering, the metadata for mitochondrial content, number of features, and possible confounding variables retains batch-specific differences.

For example, I have one sample with generally higher mitochondrial content than the others (I think due to technical effects), and a higher quality cell from that data might have similar mitochondrial content to a lower quality cell in the other samples. If this is the case, then does the model fitting in the linear regression really make sense? My inclination is that mitochondrial content isn't working as a proper proxy for cell quality if certain cells have generally higher or lower values just by virtue of the batch they came from. I can see similar concerns for other variables – if a particular run of an experiment happens to pick up a generally higher number of genes relative to others because of technical effects, should that difference be carried forward into the linear regression?

**Comment by jaisonj708** [comment]
It seems that you are still seeing batch effects in your metadata post-integration. This is normal because only the feature data and not the metadata are corrected during the integration process. For example, if one of your samples has higher mitochondrial content than the others, the percent.mito metadata field will not change, but expression levels of mitochondrial genes will be batch-corrected.

**Comment by fisherj-2212** [comment]
Yes, I'm aware the expression values are adjusted and that isn't my concern. I'm also aware that the metadata isn't corrected - that _is_ my concern. If my understanding is correct, the mitochondrial ratio is commonly computed as a proxy for general cell quality, and is something one might consider using in regression via the function ScaleData to prevent cells clustering by quality. If I were to do so, I would be using batch effected metadata. I am uncertain about the impact of the batch effect on the regression, and am wondering if the sensible thing is to avoid regressing out batch-effected variables for integrated data.

**Comment by jaisonj708** [comment]
There is no need to regress out sample-specific attributes like percent.mito after integration, since batch correction takes care of this at the feature level.

**Comment by fisherj-2212** [comment]
Ok, thank you. I've seen others doing this, and I notice cells clustered by quality post-integration, so I wasn't sure.
