### ISSUE TITLE
Question: demultiplex mix of HTO samples from two 10x lanes

### ISSUE THREAD

**Issue by m3lorra** [satijalab/seurat#3580]
Hello, 

I have a question regarding to the use of hashtag antibodies. I wonder if is it possible to use hashtag antibodies (HTO) to tag different samples, mix samples together and run them in two separate lanes from one 10x chip. 

I’m not sure if Seurat will be able to demultiplex the samples or if I will need to provide some additional information.

I could load everything into one lane, but we are able to afford two 10x lanes in order to keep a low multiplet rate. 

Thanks!

**Comment by papal22e** [comment]
Hi,

You can certainly do that! From each lane you will get separate cDNA + HTO libraries.  Once sequenced and mapped, you can use HTOdemux to demultiplex your samples from each library prior to merging them and performing downstream analyses.

I hope this helps!

**Comment by m3lorra** [comment]
Great! Thank you. 
I talked to one rep from 10x and he said that it will be tricky to demultiplex the samples so I was confused. 
So using the "[Demultiplex Cell Hashing data](https://satijalab.org/seurat/v3.2/hashing_vignette.html)" tutorial should be fine then.
