### ISSUE TITLE
ProjectDim or ProjectCellEmbeddings for query/reference projection

### ISSUE THREAD

**Issue by bdj34** [satijalab/seurat#3581]
Hello and thank you for such a great tool!

I am new to this and am trying to figure out how to project the pca dimensional reduction of a reference onto a query dataset. 
First, I create and run pca on a seurat object called 'reference', which contains several datasets. Then, I integrate using Harmony so that I have a Harmony reduction.

`reference <- RunHarmony(reference, c('Tech', 'Donor'), theta=c(1, 2),
                          reference_values = "sample3")`
`reference <- RunUMAP(reference, reduction = "harmony", dims = 1:30)`
`reference <- FindNeighbors(reference, reduction = "harmony", dims = 1:30) %>% FindClusters()`
`DimPlot(reference, group.by = c("Donor", "Tech", "ident"), ncol = 3)` 

Once I execute the above code (which produces no errors), I can visualize the integrated reference dataset mapped to two dimensions. Now, with that embedding (keeping the reference where it is in that pca and umap space), I wish to add on the next samples, another seurat object called 'query', and analyze the new dataset in the space of the principal components of the reference. For this, I would try to use the function ProjectCellEmbeddings, as follows:

`ProjectCellEmbeddings(reference, query)`

Once I have that working, I plan to integrate again in pca-space using Harmony. However, the ProjectCellEmbeddings function is not available from the version of Seurat I currently have downloaded ("other attached packages: [1] Seurat_3.2.2 harmony_1.0  Rcpp_1.0.5 " from 'sessionInfo()') or the development version ("other attached packages: [1] Seurat_3.2.2.9002 harmony_1.0       Rcpp_1.0.5" from 'sessionInfo()'). I tried to copy the function from the documentation, but it gives me the error: 

`> ProjectCellEmbeddings(reference, query)`
`Projecting PCA`
`Error in reference.assay %||% DefaultAssay(object = reference) : 
  could not find function "%||%"`

So, I try to correct by defining the function "%||%" (found somewhere in someone else's question: #1328):

`'%||%' <- function(lhs, rhs) {
  if (!is.null(x = lhs)) {
    return(lhs)
  } else {
    return(rhs)
  }
}`

The above may very well be wrong (or I may not have the right version installed), so I'm not sure where the next error comes from, but running "ProjectCellEmbeddings" again gives me another error:

`Error in rowMeans(x = reference.data) : 
  'x' must be an array of at least two dimensions `

Essentially, I'm a bit stumped now and I'm not sure if ProjectCellEmbeddings is the right function to use for what I'm trying to do, or if ProjectDim fits it better. I see that, in a similar question (#1102), ProjectCellEmbeddings is recommended. Do the two functions perform similar tasks or am I mistaken in my understanding? Also, is there a version where ProjectCellEmbeddings is available? I'd appreciate any suggestions in implementing this process. It seems to be a slightly different process than the standard integration, but my collaborators would like to see the reference data umap projection remain unchanged when adding and integrating new samples. Thanks again!

**Comment by timoast** [comment]
`ProjectCellEmbeddings` is an internal function, and is not exported or intended for users to call directly. `ProjectDim` also does something different to what you want here. I'd suggest taking a look at the new [reference mapping vignette](https://satijalab.org/seurat/v4.0/reference_mapping.html), you should be able to do what you're asking using `MapQuery` (or `FindTransferAnchors(); IntegrateEmbeddings(); ProjectUMAP()`)
