### ISSUE TITLE
After merging datasets using the SCTransform method what is the suggested method for finding variable genes for further analysis?

### ISSUE THREAD

**Issue by ms3389** [satijalab/seurat#3582]
Hi, I followed the vignette for Integration and Label Transfer here: https://satijalab.org/seurat/v3.2/integration.html#reference-based

The vignette doesn't seem to work on my dataset as it seems that post integration the variable features disappear from the integrated Seurat object. What would be the correct way to reacquire them? Should I ran find variable features on the object? Should I rerun SCTransform on the corrected counts? Should I use the union or intersection of variable features from individual objects?

Thanks so much

**Comment by jaisonj708** [comment]
For some reason it seems you've lost VariableFeatures in your object, which are normally set to the anchor features used during the integration procedure. You can re-compute the anchor features by running `SelectIntegrationFeatures` on the original object list, but you should not re-run `SCTransform` on any integrated data.
