### ISSUE TITLE
 How to change the figs' font size

### ISSUE THREAD

**Issue by adistman** [satijalab/seurat#3584]
when I finished the vlnplot fig, I want to change the lab fonts' size, what should I do?

**Comment by timoast** [comment]
The plots returned by Seurat are ggplot objects, so you can use standard ggplot2 functions to adjust aspects of the plot. See https://ggplot2.tidyverse.org/reference/theme.html and https://statisticsglobe.com/change-font-size-of-ggplot2-plot-in-r-axis-text-main-title-legend

**Comment by dkcoxie** [comment]
Will add that if the default `combine = TRUE` is used for the VlnPlot, then the added theme only seems to be applied to the second plot. Using `combine = FALSE` and then applying the theme with the new font size to each output plot seems to get the desired behavior.

**Comment by samuel-marsh** [comment]
Hi @dkcoxie 

That is expected behavior due to differences between ggplot2 objects and patchwork objects.  To apply themes to all plots in patchwork you simply use `&` instead of `+`.

Best,
Sam

**Comment by dkcoxie** [comment]
Hi Sam - thank you for the clarification and for the appropriate syntax for theme application for patchwork.
