### ISSUE TITLE
Is there a way to combine multiple genes in VlnPlot graphics?

### ISSUE THREAD

**Issue by ryandikdan** [satijalab/seurat#3585]
I have a rather simple question I couldn't find the answer to. Is there a way to combine multiple genes into a single VlnPlot. For example, instead of looking for the expression of CD7 look for the expression of CD7+CD8? If there isn't a simple way to do this could you point me in the right direction then for doing it manually? Thanks

**Comment by Dragonmasterx87** [comment]
Hi @ryandikdan you can do the following:

```
plot1 <- VlnPlot(
  object = YOURSEURATOBJECT,
  log = FALSE,
  features = c("CD7", "CD8"),
  pt.size = 1,
 ) + NoLegend()
plot1
```

OR

```
plot2 <- VlnPlot(
  object = YOURSEURATOBJECT,
  log = FALSE,
  features = c("CD7", "CD8"),
  pt.size = 1,
  stack = true
 ) + NoLegend()

plot2
plot1|plot2
```

For more on Seurat visualizations please look [here](https://satijalab.org/seurat/v3.0/visualization_vignette.html).

Cheers,
🐉

**Comment by ryandikdan** [comment]
I have not been able to get your code to work as written.
No matter how I rearrange those it is only showing me graphs for either gene counts alone, but spaced on top of each other. I'm interested in a single plot which shows the gene counts for 2 genes added together.

**Comment by Dragonmasterx87** [comment]
Sorry, I don't know how to do that. @ryandikdan  I'm confused as to what your motivation would be to additively show the expression of two genes though. Maybe one of the devs can help you.

**Comment by timoast** [comment]
Seurat does not have methods to visualise the sum of two genes on a violin plot. You could look at using the [Nebulosa](https://github.com/powellgenomicslab/Nebulosa) R package, which allows you to look at a joint density distribution for two features.

**Comment by ryandikdan** [comment]
Just in case anyone else is wondering the same thing. I was able to do this by generating a new "gene" that was simply the sum of other genes and then add this "gene" in. After analysis I pulled it out again. Theoretically I don't think this new gene will change the PCA, etc. that much since it's just a linear combination of the already existing genes and the results seem to work as expected. If someone wants the code for this I can find where I put it and post it!

**Comment by michal-zuk** [comment]
> 
> 
> Just in case anyone else is wondering the same thing. I was able to do this by generating a new "gene" that was simply the sum of other genes and then add this "gene" in. After analysis I pulled it out again. Theoretically I don't think this new gene will change the PCA, etc. that much since it's just a linear combination of the already existing genes and the results seem to work as expected. If someone wants the code for this I can find where I put it and post it!

@ryandikdan I would be really grateful if you found the code for combining multiple genes into one, do you happen to still have it saved somewhere?

**Comment by bounlu** [comment]
@ryandikdan I want the code. thanks.

**Comment by ryandikdan** [comment]
Sure, it just some R manipulation. So first load in the data, then make a new variable containing the combination of genes you require, Rbind that together and proceed with Creating the Seurat Object as normal. Note that the variable name us use (in this case 'name' will be what the new gene is called). See code below:
```
sang_data<-Read10X_h5("C:/data.h5")
name <- pbmc_data['LYZ',]+pbmc_data['MS4A1',]
pbmc_data_combined<-rbind(pbmc_data, name)

pbmc<-CreateSeuratObject(pbmc_data_combined)
```
