### ISSUE TITLE
No function named "SetDimReduction"

### ISSUE THREAD

**Issue by suny1994** [satijalab/seurat#3587]
<Hi, I am reproducing a script using Seurat=3.2.1 with R. The script may correspond to an early version of Seurat and it calls a function named "SetDimReduction". But now the error shows that there is no function named "SetDimReduction">

```r
#obj <- SetDimReduction(object = obj, reduction.type = "pca", slot = "key", new.data = "PC")
```
What new function should I use ? Whether the data form of ouput remains unchanged? Any suggestions? Thanks.

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/wiki/DimReduc

The way to add a `DimReduc` object in Seurat v3 is the `[[` assignment operator. For example:

```r
object[['pca']] <- pca_dimreduc
```
