### ISSUE TITLE
Seurat analyzes Perturb-seq

### ISSUE THREAD

**Issue by benxiahu** [satijalab/seurat#3588]
Hi,
   Seurat can anlayze scRNA-seq. I am wonder whether Seurat also handles with Perturb-seq, like this work: https://www.biorxiv.org/content/10.1101/791525v1.

**Comment by Dragonmasterx87** [comment]
Yes, I believe so. You can first extract cell-by-perturbation info using [MIMOSCA](https://github.com/asncd/MIMOSCA) and then load the UMI count matrix into Seurat and process like any other. The BioRXIV paper claims they used Seurat v2.2, and you can judge by the plots that it has to be Seurat.
