### ISSUE TITLE
Cannot run PCA on integrated data

### ISSUE THREAD

**Issue by jgamache014** [satijalab/seurat#3589]
I created an integrated Seurat object by normalizing and running FindVariableFeatures() on 20 individual samples, then running FindIntegrationAnchors() and IntegrateData(). The integrated dataset is very large (over 100K cells). After scaling the integrated data, I get the following error when attempting to run a PCA:

```
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
Calls: RunPCA ... RunPCA -> RunPCA.Assay -> RunPCA -> RunPCA.default -> irlba
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 2000 features requested have zero variance (running reduction without them): HTR2C, RELN, THSD7B, AC012405.1... [... truncated]
Execution halted

```
I see that many others have had a similar issue and the only solution I've found, which is probably sub-optimal, is to replace 'NA' values in the matrix with '0', re-scale, and re-run PCA, as done [here](https://github.com/satijalab/seurat/issues/1788#issuecomment-611429570). This works, but are there any better solutions?

**Comment by timoast** [comment]
The fact that 2000 features (which is probably all the features input to the PCA) have zero variance suggests something has gone wrong at some point in the workflow. Can you provide the full code you're running?

**Comment by jgamache014** [comment]
```
## Make combined.integrated dataset and scale

combined.anchors <- FindIntegrationAnchors(object.list = combined.list) # combined.list is a vector of Seurat objects
combined.integrated <- IntegrateData(anchorset = combined.anchors, dims = 1:30)
all.genes <- rownames(combined.integrated)
combined.integrated <- ScaleData(combined.integrated, features = all.genes)

## Find variable features in RNA assay data

combined.integrated <- FindVariableFeatures(combined.integrated, assay = “RNA”, selection.method = "vst", nfeatures = 2000)

## Scale RNA assay data

all.genes <- rownames(combined.integrated)
combined.integrated <- ScaleData(combined.integrated, assay = “RNA”, features = all.genes)

## Annotate cell types

reference_dataset <- readRDS('reference.rds')
transfer.anchors <- FindTransferAnchors(reference = reference_dataset, query = combined.integrated, query.assay = "RNA",  project.query = TRUE, dims = 1:30) # only way I could get this to work was set project.query = TRUE and use “RNA” assay data from query that had been varfeat and scaled
predictions <- TransferData(anchorset = transfer.anchors, refdata = reference_dataset$CellType, dims = 1:30)
combined.integrated <- AddMetaData(object = combined.integrated, metadata = predictions)

## Scale integrated assay data and run PCA

all.genes <- rownames(combined.integrated)
combined.integrated <- ScaleData(combined.integrated, features = all.genes, assay = "integrated")
combined.integrated <- RunPCA(combined.integrated, assay = "integrated") # this did not work

## Replace "NA" values in matrix with zero

combined.integrated@assays$integrated@data@x[is.na(combined.integrated@assays$integrated@data@x)] <- 0

## Rescale integrated data

all.genes <- rownames(combined.integrated)
combined.integrated <- ScaleData(combined.integrated, features = all.genes, assay = "integrated")
saveRDS(combined.integrated, '/gpfs/fs1/data/chiba-faleklab/Parallel_ADRC_Prelim_RNA/combined_integrated_labeled_rescaled.rds')

## Run PCA on integrated assay data

combined.integrated <- RunPCA(combined.integrated, assay = "integrated")
saveRDS(combined.integrated, '/gpfs/fs1/data/chiba-faleklab/Parallel_ADRC_Prelim_RNA/combined_integrated_labeled_rescaled_PCA.rds')
```

The inability to run a PCA on the original integrated data must have been why FindTransferAnchors() did not work with project.query = FALSE.

**Comment by jgamache014** [comment]
I also ran FindVariableFeatures() on each individual Seurat object in combined.list prior to integration.

**Comment by timoast** [comment]
If there are `NA` values in the integrated matrix, that would indicate a larger issue that should be investigated and may be the cause of the later problems. Do you have `NA` values in any of the matrices prior to integration?

**Comment by uncia-nkl** [comment]
Hi, I have also encountered the same error for a few of my datasets. Not sure if it is due to the same reason.

I did a little digging around. The 'integrated' assay data slot would have NaNs for a few cells. The affected cells turns out to have '0' for all of the 100 KNN distances calculated, which then causes the weighted distance to be NaNs possibly due to the division by 0, and that affects the downstream. [I hope I understood the calculations properly]. The function I last traced back to was NNHelper but I have no idea why all 100 distances are 0. 

Out of the 123 affected cells in the dataset I tested, there is one other particular cell that does not have NaNs for the weighted distance but eventually returns NaNs in the integrated data slot but I do not understand yet why it does so. 

Hope my observations might be able to help a little.

**Comment by jgamache014** [comment]
I think the problem was that I used `all.genes <- rownames(combined.integrated)` , when in fact this was not all of the genes. Since the integrated assay was the default, it only took the 2000 variable genes for this. These were the only genes that were scaled.

**Comment by jgamache014** [comment]
It turns out that the scale.data slot of the integrated assay was all zero values. To determine why this is, I ran 

`int.data.matrix <- as.matrix(combined.integrated@assays$integrated@data)
which(int.data.matrix=="NaN", arr.ind = TRUE)
`

This indicated that for just 2 cells in the whole matrix, all 2000 genes had "NaN" values in the integrated data. Why did this happen?

**Comment by uncia-nkl** [comment]
I am not sure why but it does sound similar to what I have encountered as well. I noticed that having a larger number of batches to integrate will more likely produce that error. Given the same dataset and using all cells, a group of eg. 10 batches could run without a problem but a group of eg. 40 batches will not run.

**Comment by timoast** [comment]
Were there any non-numeric values in the original count matrix? Can you check that this issue still happens with the current Seurat release (v4)?

**Comment by jgamache014** [comment]
Hi Tim - apologies for the late reply. I did not check for non-numeric values in the original count matrix, but this issue did not happen with Seurat v4.
