### ISSUE TITLE
Batch effects and RunMultiCCA

### ISSUE THREAD

**Issue by dandepledge** [satijalab/seurat#359]
I'm currently exploring batch effects using distinct libraries of the same heterogeneous cell populations (libraries made and sequenced on different days). 

Most the variation is linked to changes in expression of ribosome protein encoding genes and mitochondrial genes which suggests to me that the degree of 'damage' inflicted on the cells varies between prep. 

I'm worried these are biasing the output of RunMultiCCA so I am wondering if there is a way of excluding those genes from analyses? Originally I used to use MergeSeurat and then regress out those gene sets (while controlling for batch) but I can't seem to replicate this using RunMultiCCA.

Looking through the RunMultiCCA documentation, I assume it uses scaled data but it is not specified (unlike RunCCA in which user can define this)?

**Comment by satijalab** [comment]
RunMultiCCA does use the scaled data from each object independently. This means you can regress out unwanted sources of variation independently in each batch (for example, cell cycle, as we do in the hematopoietic analysis, or MT genes as you suggest), and then integrate the datasets.
