### ISSUE TITLE
Calculating Absolute Gene Expression Level

### ISSUE THREAD

**Issue by jechan23** [satijalab/seurat#3590]
Hello! I've generated a table of all differentially expressed genes pertaining to my cluster 13 compared to all other clusters. However, I also want to add a column of absolute gene expression levels for these differentially expressed genes. I know that there are many visualization tools like Violin plot to plot absolute cluster expression levels for a gene (like expression level from 1-4), but is there a way I can have absolute expression levels added as a column to my data frame of differentially expressed genes? I was thinking of a function like FetchData, but I don't know how to manipulate the function for the 1000+ genes associated with my cluster.

**Comment by cdarby** [comment]
I am not completely sure what you mean by "absolute expression" - please feel free reopen the issue and clarify if neither of these suggestions apply.

- If you want to calculate the average expression of the genes in cluster 13, the rest of the dataset, and/or the entire dataset, take a look at the `AverageExpression` Seurat function. This function operates on the dataset's Idents and as the name suggests calculates the average expression values for the desired features. The results you get can be added to your dataframe.
- If you want the expression values for certain genes for just cells in cluster 13, make a new Seurat object with the desired cells and features using the Seurat `subset` function. Then access the desired data matrix with the `GetAssayData` function.
