### ISSUE TITLE
 duplicate 'row.names' are not allowed error in FindIntegrationAnchors

### ISSUE THREAD

**Issue by rahulnutron** [satijalab/seurat#3591]
Dear Seurat Team,

Thank you for the awesome package!

I am using development versions of scTransform and Seurat V3. I am trying to integrate several datasets all processed with scTransform. However, 
in FindIntegrationAnchors there is an error keep coming. It is related to common cell names, however RenameCells is also not working. 

**First error:**
###################################
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
####################################

To solve the above problem I checked the rownames of each dataset to find duplicate values using, e.g

> any(duplicated(rownames(A.dataset@assays$SCT)))
[1] 
FALSE

However, all returned false. Then I tried to make the gene names unique 
Integrated.features <- make.unique(integrated.features)

After this, I input it to FindIntegrationAnchors, but still the problem was there. I also tried to use RenameCells for every dataset, however this also returned the same error (duplicate 'row.names' are not allowed). Finally I removed the duplicate cells using functions _setdiff_ followed by _subset_.  This solved the problem, although I don't know why it cant automatically rename the cells and how duplicate cells are related to   _'row.names' are not allowed_.

I will be grateful if you could help me on that.

Regards,
Rahul

**Comment by jaisonj708** [comment]
Could you share the command you are using, and the result of printing each of your objects?

**Comment by Junru-max-pitt** [comment]
Hi,

I meet the same issue. There is no duplicated feature name and cell name in the integrated object (SCTransfom integration workflow). However , the function() **RenameCells** and **FindIntegrationAnchors** in Seraut V3.2 do not work and provide the error: duplicate 'row.names' are not allowed. 

Interestingly, the function **FindIntegrationAnchors** can work in Seurat V4.0 but **RenameCells** still not work.

Just wondering if you have any advice. I can provide the integrated Seurat object if you want to test it.

Regards,
Junru
