### ISSUE TITLE
Find(All)Markers pct.1 pct.2 threshold?

### ISSUE THREAD

**Issue by Firedrops** [satijalab/seurat#3593]
Hi,

I'm aware that the definition for pct.1 and pct.2 are the "The percentage of cells where the gene is detected in the respective group", but what is the threshold to qualify as 'detected'? Is it simply 1? 

And is this threshold an adjustable variable?

**Comment by cdarby** [comment]
The threshold to qualify as "detected" is > 0. This value is not currently adjustable by the user.
