### ISSUE TITLE
R studio server crash running FindClusters using Leiden algorithm

### ISSUE THREAD

**Issue by msalaciak** [satijalab/seurat#3594]
Hi,

Using R studio server (installed on a ubuntu machine, connected through web via my mac...I am admin on both systems) I am working with 1 pbmc dataset, everything works correctly (following the clustering tutoral).

Now I am integrating another 5 pbmc datasetsfor a total of 6 following the Integrating stimulated vs. control PBMC, everything is working well until I have to use FindClusters().

each dataset is not more than 3.5k cells, the total size of the combined pbmc integrated object is 1.9 gb.

The error I get is that R studio server crashes with this error "the previous r session was abnormally terminated due to an unexpected crash" 

I am running this 
`pbmc.combined <- FindClusters(pbmc.combined,resolution = 1.2,algorithm="4")`

but if I change back to default algorithm, such as 
`pbmc.combined <- FindClusters(pbmc.combined,resolution = 1.2)`

it works perfectly.

Not sure what could be causing this error / bug?

help is appreciated :) thanks!

UPDATE EDIT:

I'm thinking this bug could be related to calling  'leidenalg' and 'igraph' python packages.

**Comment by mojaveazure** [comment]
Pinging @TomKellyGenetics

**Comment by TomKellyGenetics** [comment]
I’ll look into it. Have you had any issues running PCA on the integrated dataset? Which dimension reduction are you using?

I suspect the crash is due you insufficient memory. Please try it on a system with more resources or run the “igraph” method.

`pbmc.combined <- FindClusters(pbmc.combined,resolution = 1.2,algorithm="4", method = “igraph”)`

This is now the default behaviour as discussed with @andrewwbutler but older versions of Seurat will default to passing a sense matrix which has poorer performance. As @timoast is aware, there will be support for `igraph::community_leiden` in R soon which should also improve performance (and remove Python dependancy for some parameters).

**Comment by TomKellyGenetics** [comment]
To clarify I think this issue is related to #1645 which has been addressed already.

**Comment by msalaciak** [comment]
Hi Tom, thanks for replying with insightful information.

No issues running PCA on the integrated dataset, using PCA for `findNeighbors()` and `runUMAP()`

I thought it would be insufficient memory but this system has 32gb, running ubuntu with r server installed so there is no throttle on memory that I know of.  Using Scanpy's `scanpy.tl.leiden` had no issues, so I do think trying `method="igraph"` will be useful. I won't be able to try it for a week or so, so I will get back to you.

**Comment by TomKellyGenetics** [comment]
Ok please try this and let us know if it resolved the issue. It passes a list of edges to Python rather than a dense adjacency matrix. The difference in memory requirements is substantial. I've noticed similar errors from RStudio from memory-intensive jobs.

**Comment by msalaciak** [comment]
Will be trying it this weekend...sorry for the delay

**Comment by TomKellyGenetics** [comment]
No problem, I've released an update to the leiden package in the meantime but I think not necessary to install it for this. I will test the development version of [igraph](https://github.com/igraph/rigraph/tree/dev) to improve performance and let you know if it is relevant or changes are needed to Seurat to support it. However, I think in this case passing an edge list with `method="igraph"` should fix the issue.

**Comment by msalaciak** [comment]
Hi, 
sorry for the late reply. I finally tested it again and it seemed to work without adding `method="igraph`. Thanks for your help!
