### ISSUE TITLE
Create spatial Seurat object without SpaceRanger output

### ISSUE THREAD

**Issue by ph329** [satijalab/seurat#3595]
Hi, I was wondering if you have advice on how to create a spatial Seurat object without using the SpaceRanger output data - for example, from published data using the pre-Visium ST technology. Is there a way to create a spatial object with just the counts matrix, image, and the pixel coordinates for each spot? It seems that right now the only way to create a spatial object is using Load10X_Spatial with the SpaceRanger output folder. 

Thank you!

**Comment by mojaveazure** [comment]
While we don't have a single function that takes in data already read into R, you can tell Seurat about your image data by making your own `VisiumV1` object. The image data contains the following information:

- `image`: an array (we use `png::readPNG`) that can be cast to either a `rasterGrob` (`rasterGrob`) or `raster` (`as.raster`) object
- `scale.factors`: a `scale.factors` object (see `?scalefactors`) that contains the full resolution, fiducial full resolution, high-resolution, and low-resolution scale factors
- `coordinates`: the coordinates for each spot, should have at least two columns named `imagerow` and `imagecol` for the Y and X axes respectively. Spot names should be the rownames
- `spot.radius`: the radius for the spots in the image, we calculate this as the `(fiducial diameter * low-resolution scale factor) / max(dim(image array))`

```R
img <- new(
  Class = 'VisiumV1',
  image = image # an array with the image data
  scale.factors = scalefactors() # scale factors
  coordinates = coordinates # data frame with rows as spots and columns as axes
  spot.radius = radius # radius size
)
```

You can use the function [`Read10X_Image`](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L1215-L12600) as a starting point for reading your data in

**Comment by cadyyuheng** [comment]
Hi @mojaveazure ,

I'm also trying to create a spatial Seurat from scratch. While your hints above are quite straightforward to me for the term `image` and `coordinates`. However, I still don't quite get what `scale.factors` are other than it is a separate object. As I look into `scalefactors` function, I noticed `scalefactors` is defined by `spot`, `fiducial`, `hires`, and `lowres` values. From the doc, I don't fully understand what those values mean and how I could generalize them for my own data and image. Would you mind elaborating a bit more? I really appreciate your help!

**Comment by jr-leary7** [comment]
In case anyone else finds it helpful I did find a solution to this issue for Visium V1 data. i was trying to convert the mouse brain data from [this `squidpy` tutorial](https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_visium_hne.html) and ran into several issues. The complete code I used is below. First, read the data into Python:

```python
# import libraries 
import scanpy as sc
import pandas as pd
import anndata as ad
import squidpy as sq
# load image and expression data 
img_brain = sq.datasets.visium_hne_image()
ad_brain = sq.datasets.visium_hne_adata()
# add image data to AnnData object 
for scale in [1.0, 2.0]:
    feature_name = f'features_summary_scale{scale}'
    sq.im.calculate_image_features(ad_brain,
                                   img_brain.compute(),
                                   features='summary',
                                   key_added=feature_name,
                                   n_jobs=4,
                                   scale=scale)
ad_brain.obsm['features'] = pd.concat([ad_brain.obsm[f] for f in ad_brain.obsm.keys() if 'features_summary' in f], axis='columns')
ad_brain.obsm['features'].columns = ad.utils.make_index_unique(ad_brain.obsm['features'].columns)
# write AnnData object to h5ad file 
ad_brain.write_h5ad('../Data/ad_brain.h5ad')
```

Then, in R:

```r
# load packages 
library(dplyr)
library(hdf5r)
library(Seurat)
library(anndata)
library(reticulate)
# read h5ad object into R
ad_brain <- read_h5ad("../Data/ad_brain.h5ad")
# transform normalized counts back into raw counts & create Seurat object 
data_mtx <- as.matrix(ad_brain$X)
lib_sizes <- ad_brain$obs$total_counts
counts_mtx <- exp(data_mtx) - 1
counts_mtx <- sweep(counts_mtx, 1, lib_sizes / 1e4, "*")
counts_mtx <- as(round(t(counts_mtx)), "CsparseMatrix")
seu_brain <- CreateSeuratObject(counts_mtx, 
                                assay = "Spatial",
                                meta.data = ad_brain$obs,
                                min.cells = 0, 
                                min.features = 0)
seu_brain@project.name <- "coronal"
# add image data to Seurat object 
coord_df <- data.frame(imagecol = ad_brain$obsm$spatial[, 1], 
                       imagerow = ad_brain$obsm$spatial[, 2])
rownames(coord_df) = ad_brain$obs_names
img_array <- ad_brain$uns$spatial$V1_Adult_Mouse_Brain$images$lowres
fiducial_diameter <- ad_brain$uns$spatial$V1_Adult_Mouse_Brain$scalefactors$fiducial_diameter_fullres
lores_sf <- ad_brain$uns$spatial$V1_Adult_Mouse_Brain$scalefactors$tissue_lowres_scalef
spot_radius <- (fiducial_diameter * lores_sf) / max(dim(img_array))
hires_sf <- ad_brain$uns$spatial$V1_Adult_Mouse_Brain$scalefactors$tissue_hires_scalef
spot_diameter <- ad_brain$uns$spatial$V1_Adult_Mouse_Brain$scalefactors$spot_diameter_fullres
seu_brain@images[["coronal"]] <- new(Class = "VisiumV1",
                                     assay = "Spatial", 
                                     image = img_array, 
                                     key = "image_", 
                                     coordinates = coord_df, 
                                     scale.factors = scalefactors(spot = spot_diameter, 
                                                                  fiducial = fiducial_diameter, 
                                                                  hires = hires_sf, 
                                                                  lowres = lores_sf), 
                                     spot.radius = spot_radius)
```

Then you can proceed as normal to normalization, SVG identification, clustering, etc.
