### ISSUE TITLE
error in Dimplot (Error in plot.window(...) : need finite 'ylim' values)

### ISSUE THREAD

**Issue by 1874Mercury** [satijalab/seurat#3597]
Hi, 
I was using the "Dimplot" function for visualization after clustering cells and run umap, the error i got is:
`Error in plot.window(...) : need finite 'ylim' values
Calls: plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf`

I printed the umap coordinates, it seems there is no wrong during cluster and dimensional reduction, i don't know how to fix this bug:
![image](https://user-images.githubusercontent.com/38136332/95825509-8b9a4a00-0d63-11eb-8dca-b3fe8f6f48e0.png)

**Comment by cdarby** [comment]
Thanks for your question, @1874Mercury . Please provide the full sequence of commands you used in Seurat to process the object and any errors/warnings output, as well as the DimPlot command(s) you tried that caused the error.

**Comment by 1874Mercury** [comment]
```
library(Seurat)
library(ggplot2)
library(patchwork)
folders = list.files('./samples/')

sc.list = lapply(folders,function(folder){

        readRDS(paste('./samples/', folder, sep = ''))

})

sc.features <- SelectIntegrationFeatures(object.list = sc.list, nfeatures = 3000)
sc.list <- PrepSCTIntegration(object.list = sc.list, anchor.features = sc.features, verbose = FALSE)

sc.anchors <- FindIntegrationAnchors(object.list = sc.list, normalization.method = "SCT", anchor.features = sc.features, verbose = FALSE)
sc.integrated <- IntegrateData(anchorset = sc.anchors, normalization.method = "SCT", verbose = FALSE)

sc.integrated <- RunPCA(sc.integrated, verbose = FALSE)

sc.integrated <- FindNeighbors(sc.integrated, dims = 1:30)
sc.integrated <- FindClusters(sc.integrated, resolution = 0.6)
sc.integrated <- RunUMAP(sc.integrated, dims = 1:30)

plot('cluster.pdf')
plots <- DimPlot(sc.integrated, , reduction = "umap")
plots
dev.off()  
 ```

**Comment by cdarby** [comment]
Your line "plot('cluster.pdf')" is not the correct way to save the plot to PDF and is causing the error. It is very likely the DimPlot command will have no errors. Look into the "ggsave" function for example for saving a plot to PDF.
