### ISSUE TITLE
SCTransform - return.only.var.genes option

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#3598]
Hi, I've done this simple analysis so far:
```
library(Seurat)
library(dplyr)
raw <- read.table("count_table_ILCs.txt", header=TRUE, row.names=1)
dge <- CreateSeuratObject(raw, project = "ILCs_Seurat")
dge <- subset(dge, subset = nCount_RNA < 600000)
dge <- SCTransform(dge, return.only.var.genes = FALSE)
```
Despite setting the `return.only.var.genes` option to `FALSE`, the number of genes on the normalize matrix if fewer than in the original one:
```
> length(rownames(dge[["RNA"]][]))
[1] 59609
> length(rownames(dge[["SCT"]][]))
[1] 24077
```
So I was wondering what is this option actually doing.

Thanks for your amazing job!
Marta.

**Comment by jaisonj708** [comment]
This is likely due to the `min_cells` (default = 5) threshold for SCTransform, which removes features expressed in `< min_cells` cells. Because SCTransform learns a regression model at the level of individual features, features with a very low number of counts must be discarded.

**Comment by MartaBenegas** [comment]
In order to test it further, I've performed both SCTransform with `return.only.var.genes` set to `FALSE` and `TRUE`, and the 
resulting number of genes are the same using the two options:
```
raw <- read.table("count_table_ILCs.txt", header=TRUE, row.names=1)
dge <- CreateSeuratObject(raw, project = "ILCs_Seurat")
dge <- SCTransform(dge, new.assay.name = "SCTallgenes", return.only.var.genes = FALSE)
dge <- SCTransform(dge, new.assay.name = "SCTonlyvar", return.only.var.genes = TRUE)
> length(rownames(dge[["RNA"]][]))
[1] 59609
> length(rownames(dge[["SCTallgenes"]][]))
[1] 28485
> length(rownames(dge[["SCTonlyvar"]][]))
[1] 28485
```
So, I've repeated the test adding the `min.cells = 5` to the `CreateSeuratObject()` function, and the number of genes in the original matrix and the two normalized ones is the same:
```
raw <- read.table("count_table_ILCs.txt", header=TRUE, row.names=1)
dge <- CreateSeuratObject(raw, project = "ILCs_Seurat", min.cells = 5)
dge <- SCTransform(dge, new.assay.name = "SCTallgenes", return.only.var.genes = FALSE)
dge <- SCTransform(dge, new.assay.name = "SCTonlyvar", return.only.var.genes = TRUE)
> length(rownames(dge[["RNA"]][]))
[1] 28485
> length(rownames(dge[["SCTallgenes"]][]))
[1] 28485
> length(rownames(dge[["SCTonlyvar"]][]))
[1] 28485
```
I've also performed the same steps with the PBMC data from the [clustering tutorial](https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html) and the results are the same than using my count table:
```
pbmc.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k")
pbmc <- SCTransform(pbmc, new.assay.name = "SCTonlyvar", return.only.var.genes = TRUE)
pbmc <- SCTransform(pbmc, new.assay.name = "SCTallgenes", return.only.var.genes = FALSE)
> length(rownames(pbmc[["RNA"]][]))
[1] 32738
> length(rownames(pbmc[["SCTallgenes"]][]))
[1] 12572
> length(rownames(pbmc[["SCTonlyvar"]][]))
[1] 12572
```
With `min.cells = 5` :
```
pbmc.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells=5)
pbmc <- SCTransform(pbmc, new.assay.name = "SCTonlyvar", return.only.var.genes = TRUE)
pbmc <- SCTransform(pbmc, new.assay.name = "SCTallgenes", return.only.var.genes = FALSE)
> length(rownames(pbmc[["RNA"]][]))
[1] 12572
> length(rownames(pbmc[["SCTallgenes"]][]))
[1] 12572
> length(rownames(pbmc[["SCTonlyvar"]][]))
[1] 12572
```
**So I was wondering: apart from filtering, is the `return.only.var.genes` really filtering the variable genes? Do these results mean that all the genes present in both samples are variable?**

**Comment by jaisonj708** [comment]
As we mention in the documentation, `return.only.var.genes` determines which Pearson residuals (in `scale.data` slot) are computed. The `rownames` function refers to the data slot.

**Comment by MartaBenegas** [comment]
Yeah, now the results are different! 
```
> dge <- SCTransform(dge, return.only.var.genes = TRUE, variable.features.n = 3000, do.scale = FALSE, do.center = TRUE, assay="RNA", new.assay.name = "SCT")
> dge2 <- SCTransform(dge, return.only.var.genes = FALSE, variable.features.n = 3000, do.scale = FALSE, do.center = TRUE, assay="RNA", new.assay.name = "SCT")
> length(rownames(GetAssayData(object = dge, slot = 'scale.data')))
[1] 3000
> length(rownames(GetAssayData(object = dge2, slot = 'scale.data')))
[1] 28485
```

Thank you very much for your help :)

**Comment by Greysun109** [comment]
Who closed this because this is clearly still an issue?
