### ISSUE TITLE
VlnPlot formatting issue

### ISSUE THREAD

**Issue by AHPool** [satijalab/seurat#360]
Hi ,

I am writing with a quick question regarding formatting of violin plots (VlnPlot) in Seurat 2.2. Namely - is there a simple way to change the line width (stroke width?) of these plots without having to export a vector graphics form of the plot and doing in manually in Illustrator? The only parameter I found in the documentation that could offer a way is the "adjust.use"  but it wasn't clear in the documentation how to appropriately implement that option.

I also tried the do.return=T and attempted to modify the aesthetic parameters of the ggplot2 object, however with no success.

Thanks in advance and thank you for maintaining this awesome tool!

A.

**Comment by andrewwbutler** [comment]
Hi,

We don't have a specific parameter for this in Seurat so to change this, you need to return the ggplot object and modify it as follows:

```r
p = VlnPlot(pbmc_small, "LYZ", do.return = T)
p$layers[[1]]$aes_params$size = 2
p
```
