### ISSUE TITLE
Using custom distance function for FindNeighbors

### ISSUE THREAD

**Issue by elmir-ma** [satijalab/seurat#3602]
Hi, I was wondering if there is a way to use custom distance function as input in FindNeighbors function. At the moment there are only 4 options in Seurat. Thank you.

**Comment by cdarby** [comment]
I assume you're looking at the "annoy.metric" parameter - we use the Annoy library for approximate nearest neighbor finding and the four distance functions provided are those available in that library. Therefore use of a custom distance function in FindNeighbors for "annoy.metric" is not available.
But this suggestion may address your issue: you can compute neighbors based on a distance matrix with the "distance.matrix = TRUE" argument to FindNeighbors. This distance matrix can be computed with whatever custom distance function you want.
