### ISSUE TITLE
Integrating sc and sn data

### ISSUE THREAD

**Issue by jad362** [satijalab/seurat#3603]
Hi- I was just wondering if you have tried integrating single nuclear and single cell data together and what level of success you have had if so? Your vignettes seem to indicate the processing of single nuclear should not be incredibly different from single cell on its own, but what about when trying to put the two technologies together?

Thanks for the help!

**Comment by Dragonmasterx87** [comment]
I guess the devs didnt reply because based of @satijalab 's talk today the new WNN method is available now ([here](https://satijalab.org/seurat/v4.0/weighted_nearest_neighbor_analysis.html)).

**Comment by timoast** [comment]
@jad362 you can certainly use the integration methods to integrate single-cell and single-nuclei RNA-seq data. I haven't tried it myself, but there's no reason why it wouldn't work.

@Dragonmasterx87 the question of how to integrate scATAC-seq and scRNA-seq is slightly different, but we did it in our 2019 paper (https://doi.org/10.1016/j.cell.2019.05.031). Basically you can create an estimate of "gene activity" from the ATAC-seq signal and use it as a proxy for gene expression. See the vignette here: https://satijalab.org/seurat/v3.2/atacseq_integration_vignette.html

**Comment by Dragonmasterx87** [comment]
Sorry I completely missed that! Thanks for the clarification Tim.
