### ISSUE TITLE
How to add 10x feature_linkage.bedpe to Signac object

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#3607]
Hello!

I have data from the 10x multiomic assay. I would like to add the feature_linkage.bedpe file that is output from the cellranger ARC pipeline to the Links in my Signac object. It looks like Links() requires a Granges object as input. Since the bedpe file is a 13 column file with 2 sets of locations, I am unsure how to format properly. I'm sorry if this is obvious! 

Thank you so much for your help! Josephine

**Comment by timoast** [comment]
Please raise this issue in the [Signac](https://github.com/timoast/signac) repository
