### ISSUE TITLE
CoveragePlot error when used with object containing chromvar assay

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#3608]
Hello!

When I use the CoveragePlot function with an object that contains a 'chromvar' assay, I receive the following error: Error: Cannot find 'nCount_chromvar' in this Seurat object

When I use a previous version of the object that does not contain the chromvar assay, I do not get an error. I tried re-creating the chromvar assay, but I never get 'nCount_chromvar' created.

Thanks! Josephine

**Comment by timoast** [comment]
Please raise this issue in the [Signac](https://github.com/timoast/signac) repository, and include the full code you're running
