### ISSUE TITLE
Seurat Alignment CCA 10x

### ISSUE THREAD

**Issue by kragrawa** [satijalab/seurat#361]
Hi, 
I would like to perform CCA analysis on my 10x data sets. However, I do not have gene expression matrices, is there a way I can make the expression matrices or another input I can use? I also wanted to align 10 samples, is there anyway I could align 10 samples at once? The tutorial only has two samples, so I was wondering if this process was limited to only 2 samples. Thank you!

**Comment by andrewwbutler** [comment]
Hi,

How to generate the gene expression matrices is a bit upstream of any Seurat processing but there are several available tools for doing so. [Cell Ranger](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger) is the software that 10X specifically provides. 

We provide a [workflow](https://www.dropbox.com/s/aji4ielg8gc70vj/multiple_pancreas_workflow.R?dl=1) on the [website](http://satijalab.org/seurat/get_started.html) demonstrating an example with 4 datasets showing how the alignment procedure can be extended to more than two datasets.
