### ISSUE TITLE
Azimuth: No feature names (rownames) present in the input matrix

### ISSUE THREAD

**Issue by algebio** [satijalab/seurat#3610]
Hi

I have transformed a SeqGeq .csv file into a .rds file using this R script:

raw_counts<-read.table("export_SRH020.csv",sep=",")
head(raw_counts)

# Save an object to a file
saveRDS(raw_counts, file = "my_SRH020.rds")

But I got an error message when I try to use the .rds file in the Azimuth web app. Could anyone help me identify what I'm doing wrong? .rds file attached
[my_SRH020.zip](https://github.com/satijalab/seurat/files/5385777/my_SRH020.zip)

Regards
Juan

**Comment by mojaveazure** [comment]
As Charlotte said in #3606:

> Ensure that the row names are genes and the column names are cell names - the first row and/or first column should NOT be the names

Your matrix has feature names as the first column (not rownames) and cell IDs as the first row (not the colnames)

**Comment by algebio** [comment]
Thank you Paul for your answer.

I'm sorry. I don't understand how to edit the csv to get the rds right. I have tried in several ways but I have no experience with Seurat. Could you please edit one csv so I can use it as a model for my dataset?

This is the R code and one csv:
[export_SRH015b.zip](https://github.com/satijalab/seurat/files/5386668/export_SRH015b.zip)

raw_counts<-read.table("export_SRH015b.csv", fill = F, header = T, nrows = 473,
         col.names = paste0("V", seq_len(ncol)))
# Save an object to a file
saveRDS(raw_counts, file = "my_SRH015b.rds")
