### ISSUE TITLE
CellCycleScoring issue

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#3612]
Hi @SeuratLabs,
     I get a question , when runing the CellCycleScoring on the integrated sample. and i want to regress the impact of cell cycle genes.
     I wonder which running can be selected on integrated analysis.
     Whether or not I was runing the CellCycleScoring for each sample before data integrated or after the data integrated.
     The code showing below,
      ###Runing the CellCycleScoring before integrated 
       pancreas.list <- lapply(X = pancreas.list, FUN = function(x) {
  x <- CellCycleScoring(x, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
  x <- ScaleData(x, vars.to.regress = c("S.Score", "G2M.Score"), features = features)
  x <- RunPCA(x, features = features, verbose = FALSE)
})
      ###Runing the CellCycleScoring after integrated
      anchors <- FindIntegrationAnchors(object.list = pancreas.list, reduction = "rpca", 
                                  dims = 1:30)
Integrated <- IntegrateData(anchorset = anchors, dims = 1:30)

#Now proceed with downstream analysis (i.e. visualization, clustering) on the integrated dataset. Commands are identical to the standard wor
kflow.
Integrated<-CellCycleScoring(x, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
Integrated <- ScaleData(Integrated,vars.to.regress = c("S.Score", "G2M.Score") )
   Just like the codes showing above, i cannot select the code with my integrated data analysis to remove the cell cycle impact without your help.
    Any advices would be appreciated.
    Best,
    hanhuihong

**Comment by honghh2018** [comment]
Hi @All,
    Can anyone hear this question ?wait for the reply.

**Comment by ktrns** [comment]
Hi @honghh2018 

If I understand your question correctly, this issue might be your answer: https://github.com/satijalab/seurat/issues/2277

Best 
Katrin

**Comment by honghh2018** [comment]
Hi @ktrns ,
      Sorry for the unclear description.
      As my case, i want to remove the cell cycle influence for data integrated of clustering, so, should i run the CellCycleScoring function before samples integrated or after the integrated. if i run before data integrated, it would be run CellCycleScoring  for each sample and running integrated workflow to merge multiple sample into one.      
      Based above issue, which way should i token. runing  CellCycleScoring before integrated or after?
      Best,
      hanhuihong

**Comment by torkencz** [comment]
Hi,

I would recommend cell cycle regression before integration on the individual samples. If you try the other route as well you can compare the scores and see if you see a significant difference.
