### ISSUE TITLE
3 or more modalities integration by Weighted Nearest Neighbor Analysis

### ISSUE THREAD

**Issue by Junru-max-pitt** [satijalab/seurat#3614]
Hi Seurat developers,

Congratulations on the latest update of Seurat 4.0!

I'm just noticed from the pre-print in biorxiv that the Weighted Nearest Neighbor Analysis can be easily applied to 3 or more modalities integration. However, it seems that the function FindMultiModalNeighbors only support 2 modalities right now. Do you have any suggestions in the case of integrated 3 or more (e.g. RNA, ADT, mutation, and chromatin accessibility) modalities? 

Even a rough idea would be helpful!

Thanks,
Junru

**Comment by satijalab** [comment]
Thanks! yes we are actively working on extending this to 3 modalities. Its not a complicated extension of the method, but just something we are finalizing the implementation of. Please stay tuned!
