### ISSUE TITLE
ADT assay in Feature Plot

### ISSUE THREAD

**Issue by JenniferWUSTL** [satijalab/seurat#3617]
Good afternoon,

I have a cite-seq dataset.  When I call a FeaturePlot on some datasets the features are listed as "adt_CD56-TotalSeqC" but on other datasets (generated from the same matrices) the features are listed as "ADT_CD56-TotalSeqC".  Is there any reason why "ADT" is capitalized in some cases?  Is this a sign of an underlying issue? Or a harmless bug?

Thank you!

**Comment by mojaveazure** [comment]
Whether it's `adt_` or `ADT_` depends on the [key](https://rdrr.io/cran/Seurat/man/Key.html) of the ADT assay for a given object. You can see the keys for all keyed components (assays, dimensional reduction, spatial images) of a `Seurat` object using the `Key` function

```R
> library(Seurat)
> data(pbmc_small)
> pbmc_small
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features, 20 variable features)
 2 dimensional reductions calculated: pca, tsne
> Key(pbmc_small)
    RNA     pca    tsne 
 "rna_"   "PC_" "tSNE_" 
```
