### ISSUE TITLE
About violin plot

### ISSUE THREAD

**Issue by mhorie25** [satijalab/seurat#3619]
Hello 
My scRNA-seq paper with data analyzed by Seurat ver 3.0 was on major revise now.
The reviewer asked a question like below.
"When creating violin plots, the method used to create the smoothed curve should be specified (e.g. kernel density estimator ?"
I could not figure out it from the vignette. Could you tell me about the violin plot in detail?
Thank you,

**Comment by cdarby** [comment]
Internally, Seurat VlnPlot function uses the ggplot2 package's geom_violin function. Internally, ggplot2 geom_violin uses the ggplot2 stat_ydensity function. Please find the documentation describing the default kernel for this function here. https://www.rdocumentation.org/packages/ggplot2/versions/1.0.1/topics/stat_ydensity
