### ISSUE TITLE
Importing Public Data from Illumina BaseSpace Sequence Hub

### ISSUE THREAD

**Issue by Edenapple** [satijalab/seurat#362]
I would like to test public data from Illumina BaseSpace Sequence Hub on Seurat.
I am using public data from
NextSeq 550: SureCell WTA3 DP (PBMC samples)
Analysis: SureCell RNA Single-Cell 01/12/2018 1:47:05
Sample: PBMC_DP_C1S2

It looks something like this:

[test.xlsx](https://github.com/satijalab/seurat/files/1810539/test.xlsx)

Is there anyway to import this in Seurat without transforming the table?

**Comment by leonfodoulian** [comment]
Hi,

You most probably have to transform the data from long to wide format yourself. You can use the following code (which you can implement in a function, for easier use):

```R
# Load required packages
require(reshape2)
require(xlsx)

# Read file in '.csv' format
d <- read.csv(file = "test.csv")
# OR in '.xlsx' format
d <- xlsx::read.xlsx(file = "test.xlsx", sheetIndex = 1)

# Convert data frame from long to wide format
# Set 'GeneId' as rownames()
# Remove 'GeneId' from the data frame
d <- transform(reshape2::dcast(data = d, formula = GeneId ~ CellId),
               row.names = GeneId,
               GeneId = NULL)
```
You can also use `tidyr::spread()`, but `tibble` is just a mess when you work with data frames with `rownames`. 

Best,
Leon
