### ISSUE TITLE
Seurat 4 reveal?

### ISSUE THREAD

**Issue by kmshort** [satijalab/seurat#3620]
Hi,

So with Seurat 4.0 going BETA, what's the difference, changes, improvements, bugfixes?
I'm sorry but I can't find any readme or anything.

thanks
K

**Comment by samuel-marsh** [comment]
Hi,

Please see here: [https://satijalab.org/seurat/v4_changes.html](https://satijalab.org/seurat/v4_changes.html)

Best,
Sam
