### ISSUE TITLE
Removing zero values on violin plot

### ISSUE THREAD

**Issue by ConorSmithTCD** [satijalab/seurat#3621]
Hi, 
I was just wondering is it ok to remove the zero values/cells with very low expression from the violin plot? I seem to have quite a few data points above zero, but the high number of data points at zero mean there is no shape to my violin plot. When I remove the lowly expressed cells it becomes easier to visualise the data. Is it reasonable to set this lower threshold for visualisation purposes. 
![Screenshot 2020-10-20 at 09 54 34](https://user-images.githubusercontent.com/63306140/96563775-440f4300-12ba-11eb-813b-0c608b6bd63b.png)
![Screenshot 2020-10-20 at 09 55 02](https://user-images.githubusercontent.com/63306140/96563830-55584f80-12ba-11eb-8e91-4dfad4bdbeb0.png)

**Comment by cdarby** [comment]
There is nothing inherently wrong with plotting only a subset of cells, if it helps your analysis. (Based on the images you uploaded, you seem to have done this successfully already, and it can be quite useful where most of the points are zeros like your example shows.) You should of course clearly indicate that you have omitted cells and how you chose the cells to omit when using such plots to communicate your results.

**Comment by christoforos-dimitropoulos** [comment]
> Hi,
> I was just wondering is it ok to remove the zero values/cells with very low expression from the violin plot? I seem to have quite a few data points above zero, but the high number of data points at zero mean there is no shape to my violin plot. When I remove the lowly expressed cells it becomes easier to visualise the data. Is it reasonable to set this lower threshold for visualisation purposes.
> ![Screenshot 2020-10-20 at 09 54 34](https://user-images.githubusercontent.com/63306140/96563775-440f4300-12ba-11eb-813b-0c608b6bd63b.png)
> ![Screenshot 2020-10-20 at 09 55 02](https://user-images.githubusercontent.com/63306140/96563830-55584f80-12ba-11eb-8e91-4dfad4bdbeb0.png)

Hello, may I ask how did you plot only the cells with expression value > 0? Thanks!
