### ISSUE TITLE
Problem with "percent.mt"

### ISSUE THREAD

**Issue by pabloatria18** [satijalab/seurat#3624]
Hello,

I am trying to analyze some data and when I run the code:
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

I get this:
Warning message:
In FetchData(object = object, vars = features, slot = slot) :
  The following requested variables were not found: percent.mt

I have not being able to find what the problem is.

Thank you

**Comment by samuel-marsh** [comment]
Hi,

Are you following the tutorial?  The percentage of mitochondrial reads is not an inherent characteristic and needs to be calculated.  You can find that code in the tutorial and here below:
`pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")`

Best,
Sam

**Comment by pabloatria18** [comment]
Hello Sam,
Thank for your help,

I did follow it but I keep having issues,
Now it says

Warning message:
In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :
  All cells have the same value of percent.mt.

**Comment by samuel-marsh** [comment]
What species data are you working with?  Are you using the data in the tutorial?  If using different species with different prefix for mitochondrial genes you will need to change the pattern.  i.e. for mouse `pattern = "^mt-"`

Best,
Sam

**Comment by pabloatria18** [comment]
It worked now! Thank you very much!
