### ISSUE TITLE
Fail to parallel using Seurat 3.5

### ISSUE THREAD

**Issue by hfl112** [satijalab/seurat#3627]
Hi developers,
I have set the multiprocess and ram using future and checked it.
```
> plan("multiprocess", workers = 15)
> #set maximum allowed size of global variable to 50GB
> options(future.globals.maxSize = 50000 * 1024^2)
```

```
multiprocess:
- args: function (expr, envir = parent.frame(), substitute = TRUE, lazy = FALSE, seed = NULL, globals = TRUE, workers = 15, gc = FALSE, earlySignal = FALSE, label = NULL, ...)
- tweaked: TRUE
- call: plan("multiprocess", workers = 15)
```

`/bioware/source/R-3.5.0/bin/exec/R --slave --no-restore -e parallel:::.slaveRSOCK() --args MASTER=localhost PORT=11689 OUT=/dev/null SETUPTIMEOUT=120 TIMEOUT=2592000 XDR=TRUE`

But when I ran normalization or findcluster, the cpus is still 1. Can this parallelization fit in Seurat2(R version 3.5)?

Thanks.

**Comment by timoast** [comment]
This is a feature of Seurat >=v3, not available in Seurat v2
