### ISSUE TITLE
Issues installing Seurat v4

### ISSUE THREAD

**Issue by juan-quintana2020** [satijalab/seurat#3628]
Hi,

I've been trying to instal the beta version of Seurat v4 as indicated here: https://satijalab.org/seurat/v4.0/reference_mapping.html

But it seems I keep getting the same error as below:

"remotes::install_github("satijalab/seurat", ref = "release/4.0.0")
Downloading GitHub repo satijalab/seurat@release/4.0.0
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                            
2: CRAN packages only                             
3: None                                           
4: RcppArmad... (0.9.900.3.0 -> 0.10.1.0.0) [CRAN]
5: data.table   (1.13.0      -> 1.13.2    ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
RcppArmad... (0.9.900.3.0 -> 0.10.1.0.0) [CRAN]
data.table   (1.13.0      -> 1.13.2    ) [CRAN]
Installing 2 packages: RcppArmadillo, data.table
Warning in download.file(url = paste0(repos, "/PACKAGES.rds"), destfile = dest,  :
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'
Warning in download.file(url = paste0(repos, "/PACKAGES.gz"), destfile = tmpf,  :
  cannot open URL 'https://mojaveazure.github.io/loomR/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'

  There is a binary version available but the source version is later:
                   binary     source needs_compilation
RcppArmadillo 0.9.900.3.0 0.10.1.0.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/data.table_1.13.2.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  (converted from warning) cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/data.table_1.13.2.tgz': HTTP status was '404 Not Found'
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) download of package ‘data.table’ failed "

I have tried installing everything separately, including what's been proposed here: https://github.com/satijalab/seurat/issues/3273#issuecomment-660654642 but everything seems to fail. 

I was wondering if there are any updates on this? Can somebody help with this?

**Comment by preetida** [comment]
I have the same exact issue. 
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] ggrepel_0.8.2      Rcpp_1.0.5         lattice_0.20-41   
 [4] ica_1.0-2          listenv_0.8.0      zoo_1.8-8         
 [7] digest_0.6.26      lmtest_0.9-38      mime_0.9          
[10] R6_2.4.1           plyr_1.8.6         ggridges_0.5.2    
[13] httr_1.4.2         ggplot2_3.3.2      pillar_1.4.6      
[16] rlang_0.4.8        rstudioapi_0.11    irlba_2.3.3       
[19] miniUI_0.1.1.1     leiden_0.3.3       Matrix_1.2-18     
[22] reticulate_1.16    splines_4.0.3      Rtsne_0.15        
[25] igraph_1.2.6       munsell_0.5.0      shiny_1.5.0       
[28] compiler_4.0.3     httpuv_1.5.4       pkgconfig_2.0.3   
[31] globals_0.13.1     htmltools_0.5.0    tidyselect_1.1.0  
[34] tibble_3.0.4       RANN_2.6.1         codetools_0.2-16  
[37] matrixStats_0.57.0 fitdistrplus_1.1-1 future_1.19.1     
[40] crayon_1.3.4       dplyr_1.0.2        later_1.1.0.1     
[43] MASS_7.3-53        grid_4.0.3         jsonlite_1.7.1    
[46] xtable_1.8-4       gtable_0.3.0       lifecycle_0.2.0   
[49] magrittr_1.5       scales_1.1.1       KernSmooth_2.23-17
[52] future.apply_1.6.0 pbapply_1.4-3      ROCR_1.0-11       
[55] promises_1.1.1     ellipsis_0.3.1     generics_0.0.2    
[58] vctrs_0.3.4        cowplot_1.1.0      RcppAnnoy_0.0.16  
[61] RColorBrewer_1.1-2 tools_4.0.3        glue_1.4.2        
[64] purrr_0.3.4        parallel_4.0.3     fastmap_1.0.1     
[67] survival_3.2-7     colorspace_1.4-1   cluster_2.1.0     
[70] patchwork_1.0.1   
```

**Comment by whiteorchid** [comment]
> remotes::install_github("satijalab/seurat", ref = "release/4.0.0")
Downloading GitHub repo satijalab/seurat@release/4.0.0
✔  checking for file ‘/tmp/Rtmpx1zQWX/remotes53f67d47b535/satijalab-seurat-def4e41/DESCRIPTION’ (1.2s)
─  preparing ‘Seurat’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (450ms)
─  checking for empty or unneeded directories
─  building ‘Seurat_3.9.9.9003.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '~/soft/R-4.0.3/library/Rtsne/libs/Rtsne.so':
  libgfortran.so.5: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘Seurat’

**Comment by jeffsun905** [comment]
Failed to install to R.4.0.2 in MAC with following error at the end.

*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 96979 Done                    echo 'tools:::.install_packages()'
     96980 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/ym/pqx8y0t15tb9jwbk0m32_g6dtktzn3/T//Rtmpa3b95P/file17a8d1ce94224/Seurat_3.9.9.9003.tar.gz’ had non-zero exit status

**Comment by cdarby** [comment]
@juan-quintana2020 Your error was in the installation of data.table 1.13.2 from CRAN. I confirm that I am able to download and install this version of the package today. In any case, you could opt to skip updating this package.

**Comment by cdarby** [comment]
@preetida If you had the same data.table 1.13.2 problem as the original poster, please try again and/or skip updating the package. If you had a different problem, please open another issue with the error messages you receive during installation

**Comment by juan-quintana2020** [comment]
@cdarby Thanks for coming back to me - I had some troubles trying again, but it only worked when deleting anaconda/miniconda from my Library folder. Not sure why it doesn't work when Anaconda is installed. Thanks a lot for your help!
