### ISSUE TITLE
Rstudio not loading reading raw folder location when using Seurat

### ISSUE THREAD

**Issue by VP0521** [satijalab/seurat#3629]
I am trying to load raw files using Read 10X command but it says the following error:
Expression matrix file missing. Expecting matrix.mtx

All the file prefixes I removed it and now has the names: barcodes.tsv, genes.tsv, and matrix.mtx

Please help me with this!

**Comment by timoast** [comment]
Did you generate these files using cellranger? If so, you shouldn't modify the outputs (decompress or change file names). The function is designed to read the files as they're output by cellranger
