### ISSUE TITLE
Displaying/pulling out only cells from control or stimulated groups

### ISSUE THREAD

**Issue by IOnceWasLegend** [satijalab/seurat#363]
So I've followed the tutorial, performed the CCA analysis, and have a Seurat object made up of control and stimulated cells (immune.combined). As part of this, prior to the CCA, I stored the original identity of the dataset in meta.data. For control cells, I used ctrl@meta.data$stim <- "CTRL" ; and for stim cells, used stim@meta.data$stim <- "STIM".

I was able to run the CCA analysis on immune.combined and generate a TSNE plot, but now I have two questions.

1) How do I display ONLY control or ONLY stimulated cells in this TSNE plot? 

2) How would I pull out gene expression data for ONLY control or ONLY stimulated cells? I know I can generate a table for all cells using as.matrix(immune.combined@scale.data), but how would I generate a table like this for only one treatment group? Or, even better, how could I generate a gene expression table with each cell labeled based on its original treatment group?

Thanks for the help; it's very much appreciated!

**Comment by leonfodoulian** [comment]
Hi,

The answers to both of your questions come up a lot in the issues of this GitHub page. One way to do it is to create a specific Seurat object for each of the conditions. This way, you can do both of the things you aim at doing at once.

```R
# Store the cluster identities in a new column in 'object@meta.data'
object <- Seurat::StashIdent(object = object, save.name = "clusterID")

# Set the experimental condition as cell identity
object <- Seurat::SetAllIdent(object = object, id = "stim")

# Subset data for 'CTRL' cells
object.CTRL <- Seurat::SubsetData(object = object, ident.use = "CTRL")

# Subset data for 'STIM' cells
object.STIM <- Seurat::SubsetData(object = object, ident.use = "STIM")

# Restore identities stored in 'object@meta.data$clusterID'
object.CTRL <- SetAllIdent(object = object.CTRL, id = "clusterID")
object.STIM <- SetAllIdent(object = object.STIM, id = "clusterID")

# Display on tSNE plot either 'CTRL' or 'STIM' cells
TSNEPlot(object = object.CTRL)
TSNEPlot(object = object.STIM)
```
Hope it helped!

Best,
Leon
