### ISSUE TITLE
Clarification of Normalization method employed in Seurat

### ISSUE THREAD

**Issue by sylestiel** [satijalab/seurat#3630]
Hi,
According to the Seurat Vignette,
"LogNormalize"  normalizes the feature expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000 by default), and log-transforms the result.
In the Help feature within R it says the following
LogNormalize: Feature counts for each cell are divided by the total counts for that cell and multiplied by the scale.factor. This is then natural-log transformed using log1p.

Very confusing Verbiage. 

Can anyone break it down for me.

Thanks!

**Comment by giovanegt** [comment]
Hi, 
Actually, I  have the same issue regarding the definition of Normalization in Seurat. 
I found somewhere the following equation. 

![image](https://user-images.githubusercontent.com/58445209/96791060-650c8c80-13bd-11eb-911e-effe9afb9402.png)

So, I think, it fits best the second definition posted above. 

Again,  I am not a statistician, but the following is the way I understand it

(geneX counts in cellA)/(total counts in cellA) = X  then,

X*10000 = Xn.    then,    log2(Xn) = geneX normalized counts

Any help is appreciated

**Comment by satijalab** [comment]
1. Divide each cell by the total number of molecules measured in the cell
2. Multiply that number by a scaling factor (i.e. 10000
3. Add 1, and take a natural log

**Comment by cstubben** [comment]
I don't think a pseudocount (Add 1) is used by NormalizeData?   This returns the same normalized values in the data slot for me
```
c1 <- as.matrix(GetAssayData(srt, slot="count")[, 1:3])
x <- t(log1p( t(c1)/ colSums(c1) *10000))
```

**Comment by PedroMilanezAlmeida** [comment]
> I don't think a pseudocount (Add 1) is used by NormalizeData? This returns the same normalized values in the data slot for me
> 
> ```
> c1 <- as.matrix(GetAssayData(srt, slot="count")[, 1:3])
> x <- t(log1p( t(c1)/ colSums(c1) *10000))
> ```

`> ?log1p`

log1p(x) computes log(1+x) accurately also for ∣x∣≪1.
