### ISSUE TITLE
adding gene count to FindMarkers data table?

### ISSUE THREAD

**Issue by aelyaderani** [satijalab/seurat#3632]
when running FindMarkers, How can I add two more column showing the total expression count for each gene in pct.1 and pct.2? 

FOR example,
<img width="517" alt="Screen Shot 2020-10-21 at 8 27 38 PM" src="https://user-images.githubusercontent.com/34661195/96821003-f559ca00-13db-11eb-9e04-35101e748ad0.png">

I'd like to add 2 more columns giving me the expression count for each of those genes, Within pct.1 and pct.2.
for example add 2 columns, call them pct.1_count and ptc.2_count, and each one would have the gene count from each group.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully this can be helpful.  So I'm not sure what you are looking for here in terms of expression count when `FindMarkers` is providing values for clusters.  The total count across all cells in a cluster is going to be dependent on both number of cells and the expression level so on its own may not be the most informative metric.

Do you mean the average expression of the gene in the given clusters that you supplied to `ident.1` and `ident.2`?  In that case you can simply take the gene list returned by `FindMarkers` and use that as input for `AverageExpression`.  Then pull the values for the two clusters of interest in your given `FindMarkers` output dataframe and merge them.  You can rename new columns using standard base R or tidyverse/dplyr functions.

Best,
Sam

**Comment by aelyaderani** [comment]
@samuel-marsh Problem with this is that the AverageExpression is pulled from all the Cells in group Ident.1 and ident.2... in other words if the marker is only present in 30% of the cells and 0 counts in the other 70% of the cells, the AverageExpression will most likely be 0.0000... which can be miss leading. I wish there was a way to pull Average Expression from only the 30% of the cell population, that are expressing the Gene :(

**Comment by cdarby** [comment]
AverageExpression does not currently support excluding 0 values from the calculation of the average. I would suggest writing a few lines of code to the effect of:
For each cluster:
  Use `FetchData` to select the cells in that cluster, and the desired features from the desired slot.
  Calculate the average of each feature, excluding zero values.
  Add this information to your data.frame.
