### ISSUE TITLE
Adding new rows in the Seurat object

### ISSUE THREAD

**Issue by hiraksarkar** [satijalab/seurat#3633]
Hi, 

I am trying to add new rows to the existing seurat objects. In other words, I am trying to use the [merge](https://satijalab.org/seurat/v3.1/merge_vignette.html) feature but instead of adding cells, I want to add new genes to the object. My naive search got me to this old issue https://github.com/satijalab/seurat/issues/256 but I am not sure accessing objects with `@` is a good idea or not.

Thanks

**Comment by satijalab** [comment]
Thanks for the question. Unfortunately we don't support adding features after the object has been created. Doing so could throw off a lot of assumptions about normalization, etc. - so its something we have not pursued. We suggest creating a new object in this case.

**Comment by Dazcam** [comment]
There are edge case usages for this, and it can be done, but you need to create a new Seurat object for it to work.

For example, when plotting a set of stacked violin plots for a set of genes across multiple datasets, if one of the genes it not present at all in one of the datasets (maybe it was removed during filtering) no row is produced in relevant stacked violin plot for the missing gene. If you then want to plot your stacked vln plots side by side, to read across the rows for each gene, the rows in the plot with the missing gene will be out of sync with the others.

Here is the solution to add the row using Seurat 5, and BPCells. Note that you have to first convert the BPCells `counts` and `data` slots back to `in memory` format first.

```r
message("Converting BPCells counts and data matrix to in memory format first ...")
  
message("Count matrix ...")
adult_object[["RNA"]]$counts <- as(object = adult_object[["RNA"]]$counts, Class = "dgCMatrix")
  
message("Data matrix ...")
adult_object[["RNA"]]$data <- as(object = adult_object[["RNA"]]$data, Class = "dgCMatrix")
  
# Create empty row for gene
th_mat <- as(MatrixExtra::emptySparse(nrow = 1, ncol = ncol(adult_object)), "dgCMatrix")
rownames(th_mat) <- 'TH'

# Join empty row to count and data slots
new_counts <- rbind(adult_object[["RNA"]]$counts, th_mat)
new_data <- rbind(adult_object[["RNA"]]$data, th_mat)
obj_meta <- adult_object@meta.data

# Check counts before and after
message("Counts old: ", nrow(adult_object[["RNA"]]$counts), " ; Counts new: ", nrow(new_counts))
message("Data old: ", nrow(adult_object[["RNA"]]$data), " ; Data new: ", nrow(new_data))

# Create new Seurat obj and add data slot 
new_obj <- CreateSeuratObject(counts = new_counts, meta.data = obj_meta)
new_obj[["RNA"]]$data <- new_data
```
