### ISSUE TITLE
variable vers.to.regress 

### ISSUE THREAD

**Issue by NDUFB11** [satijalab/seurat#3634]
Hello everyone, 
In my scRNA-sequencing data I have two conditions included in the variable library that I want to compare and find differences.
I get different outputs by including or omitting the variable library in vars.to.regress (sctransform code) and it's not clear weather or not this should be included. I saw that people add many more variables like percentage of mtDNA, nFeature_RNA and so on. Can you tell me what is the best way and the most reliable variable to add during this normalization step? What if I completely exclude variables? 

Thank you 

-P

**Comment by satijalab** [comment]
We can't recommend on a single strategy that is best for all cases. One option is to explore your dataset with unsupervised analyses, like PCA, without regressing on any variables. If you see that there are PCs that are strognly correlated with - for example, mtDNA, that would suggest that adding this variable in the regression would help
