### ISSUE TITLE
Clusters and Ab-seq 

### ISSUE THREAD

**Issue by NDUFB11** [satijalab/seurat#3635]
Hello guys, 

I analyze scRNA-sequencing data from Rhapsody platform which includes the Ab-oligo-sequencing. 
I'd like to make UMAP clusters based only on the gene transcript level and find out where the Ab-seq-oligo are distributed among clusters,
is it possible to do that? 

thank you 

-P

**Comment by satijalab** [comment]
Yes, please take a look at https://satijalab.org/seurat/v3.1/multimodal_vignette.html

**Comment by NDUFB11** [comment]
> Yes, please take a look at https://satijalab.org/seurat/v3.1/multimodal_vignette.html

Thank you for the link, 
I'm thinking If it's right to split apart the informations that we get from the transcriptome with informations that we have from the Ab-seq oligo, Ideally I think the more informations we have of each cells the more we are able to define a cell population ,
What do you think? 
thank you

**Comment by NDUFB11** [comment]
Thank you for the link, 

I wonder if splitting the informations in two parts is a good practice to better define clusters.
I think that the more informations I have the better the clusters are defined, means if I have informations from the RNA-seq and Ab-seq altogether it's better to have only the RNA-seq to make clusters and then look for the membrane markers later on, 

what do you think? 

Thank you 

-P
