### ISSUE TITLE
ADT data lost after SplitObject

### ISSUE THREAD

**Issue by sopenaml** [satijalab/seurat#3637]
Hi I'm currently analyzing a data set that contains cell hashing, CITE-Seq,  gene expression and gene expression. To do so, I'm trying to follow what's suggested on your pre-print (https://www.biorxiv.org/content/10.1101/2020.10.12.335331v1). I've demultiplexed my data, added the ADT and VDJ data, and now I'm trying to partitioned the dataset into x groups, each corresponding to one of the original samples. To do so I've used `SplitObject`, however, after doing it I've lost the ADT assay while the HTO assay is kept. Is this something expected of `SplitObject`?. If that's the case, how do you suggest doing the partition of data into groups corresponding to original samples? 
Thank you very much, 
Miriam

**Comment by andrewwbutler** [comment]
Hi Miriam,

`SplitObject` should not be removing any assays by default. Could you provide a reproducible example where this is occurring?

**Comment by sopenaml** [comment]
Hi Andrew,

I found the problem. My CITE-Seq data had the following format "CD25-TAGGTCCTACCGGG"  as features names, which was quite annoying to use in FeaturesPlot and other functions, so I had changed the features names after creating the Seurat object, which I have found out that it was the cause of my problem. I went back and changed the name features before creating the Seurat object and that solved my problem. Thank you and sorry to have troubled you.

Kind regards,

Miriam
________________________________
