### ISSUE TITLE
Overlapping labels in `DimPlot`

### ISSUE THREAD

**Issue by hiraksarkar** [satijalab/seurat#3638]
Hi, 

Is there a way to control how the labels appear on the clusters in `DimPlot`

```
options(repr.plot.height = 7, repr.plot.width = 7)
DimPlot(object = query, reduction = "proj.umap", group.by = "predicted.id", label = TRUE) + NoLegend()
```
![image](https://user-images.githubusercontent.com/9473877/97064911-b2345e00-1577-11eb-8889-8546ec62147d.png)

The labels on the cluster sometimes overlap each other and hard to figure out. 

Thanks

**Comment by cdarby** [comment]
Try `DimPlot(... repel=TRUE)`
