### ISSUE TITLE
difference between FindAllMarkers and FindMarkers

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#364]
Hi,
I have a question about the difference of this 2 functions.

If I want to find all of the markers for each clusters I will use **FindAllMarkers** right?
_exemple: all_markers <- FindAllMarkers(object = pbmc)
head(x = all_markers)_

BUT, if I use **FindMarkers**, and I search for each identity (without ident.2),
_exemple: markers <- FindMarkers(object = pbmc_small, ident.1 = 3)
head(markers)_

 will it be the same result?
I mean if I am looking for markers for my "identity 3" in both results, I will have the same?

**Comment by leonfodoulian** [comment]
Hi,

Yes, the results should be the same. `Seurat::FindAllMarkers()` uses `Seurat::FindMarkers()`. The corresponding code can be found at [lines 329 to 419 in differential_expression.R](https://github.com/satijalab/seurat/blob/f4da9c6e725ee9ee833d8ef60809e56e13b3062a/R/differential_expression.R#L329-L419). You can also double check by running the function on a subset of your data. 

Best,
Leon

**Comment by camilliano** [comment]
Thanks for your answer!

others question which is related,
when you run **FindMarkers**, in the output, you will have _"p_val, avg_logFC, pct.1, pct.2, p_val_adj"_ etc. 
_exemple: cluster0.markers <- FindMarkers(object = object, only.pos = TRUE, ident.1 = 0, min.pct = 0.25)
print(x = head(x = cluster0.markers, n = 10))_

What is the difference between **pct.1 and pct.2**? What do they mean?

**Comment by leonfodoulian** [comment]
Hi,

`pct.1` and `pct.2` correspond to the proportion of cells expressing the gene of interest. `pct.1` would be for `ident.1` cells, and `pct.2` for `ident.2` cells (if `NULL`, then it corresponds to the proportion of cells from all non `ident.1` clusters). 

Best,
Leon
