### ISSUE TITLE
How to show gene expression more clearly with FeaturePlot？

### ISSUE THREAD

**Issue by BeyondMyPast228** [satijalab/seurat#3641]
Hi，
Thanks for developing this user-friendly tool. I have a question about FeaturePlot.
In my single-cell mRNA sequencing data, i  have some genes with lower expression values. When I wanted to use FeaturePlot to show gene expression, I often couldn't see which cells expressed this gene and which didn't. Just like the below picture:
[
![image](https://user-images.githubusercontent.com/67768651/97139811-44b24880-1796-11eb-94c6-d763521ca73e.png)
](url)
On the right side of the figure, there is a legend that divides the color levels according to different expressions. Can I customize a threshold below which light color(eg: grey) is displayed, and above which a color(eg: red) with absolute difference is displayed. That means black or white.
I sincerely hope to get your kind reply.

**Comment by cdarby** [comment]
Thanks for your question! I think the `min.cutoff` and/or `max.cutoff` arguments for `FeaturePlot` might be helpful to you. You could also use the `cells` argument to plot only some of your cells (e.g. omit cells with a lower/zero value). I'm not sure what you mean by "black or white" but you can change the `cols` argument to be a gradient between whichever colors you want.
