### ISSUE TITLE
How to extract the mapping score following the Azimuth workflow?

### ISSUE THREAD

**Issue by friedue** [satijalab/seurat#3642]
Hi,

I've followed the Azimuth workflow [described on your website](https://satijalab.org/seurat/v4.0/reference_mapping.html) and then read the description of your Azimuth app where you distinguish between prediction scores and mapping scores. Following the workflow outside the app on my machine, I only see one type of score in the metadata of the resulting object (after `MapQuery()`) though:

```
anchors <- FindTransferAnchors(
		  reference = ref.data,  query = srt,
		  normalization.method = "SCT",
		  reference.reduction = "pca",
		  dims = 1:50
		  )
> srt <- MapQuery( anchorset = anchors, query = srt, reference = ref.data,
 refdata = list(celltype.l1 = "celltype.l1",  celltype.l2 = "celltype.l2",  predicted_ADT = "ADT"  ),
 reference.reduction = "pca",  reduction.model = "wnn.umap" )
> srt[[]] %>%names
[1] "orig.ident"                  "nCount_RNA"                 
[3] "nFeature_RNA"                "nCount_SCT"                 
[5] "nFeature_SCT"                "predicted.celltype.l1.score"
[7] "predicted.celltype.l1"       "predicted.celltype.l2.score"
[9] "predicted.celltype.l2"      
```

Can you tell me how to obtain the mapping scores as well?

Thank you,

Friederike

**Comment by cdarby** [comment]
You're right - MapQuery does not calculate the mapping score shown in the app. To calculate mapping score, you can run the `MappingScore` function in Seurat on the object returned from `FindTransferAnchors` (which you've named "anchors"). See documentation for more information.

**Comment by friedue** [comment]
Hi,

thanks for the quick reply.

```
> ms <- MappingScore(anchors)
Error in if (ncol(x = query.neighbors) < ksmooth) { : 
  argument is of length zero
```

Any leads on what could be causing the error?

**Comment by cdarby** [comment]
This might be a bug - MappingScore _should_ be able to automatically compute the neighbors if they don't exist - but you can get around it for now by adding the parameter "mapping.score.k=100" in FindTransferAnchors. 

You can compute and add it directly to the metadata of the query as follows:

```
query <- AddMetaData(
  object = query,
  metadata = MappingScore(anchors = anchors),
  col.name = "mapping.score"
)
```

I'll see if we can show an example of using the MappingScore function in the vignette you linked to.

**Comment by friedue** [comment]
I hunted down the code in the Azimuth app and used the following command:

```
 ms <- MappingScore(
				                     anchors = anchors@anchors,
				                     combined.object = anchors@object.list[[1]],
				                     query.neighbors =  slot(object = srt, name = "neighbors")[["query_ref.nn"]],
				                     query.weights = Tool(object = srt, slot = "TransferData")$weights.matrix,
				                     query.embeddings = Embeddings(object = srt),
				                     ref.embeddings = Embeddings(object = ref.data),
				                     nn.method = "annoy",
				                    # n.trees = n.trees
				                   )
```

Any details on what each parameter actually does, would be appreciated. E.g. what's the significance of the weights matrix?

**Comment by cdarby** [comment]
This complex syntax is for optimization purposes in the app. You should call `MappingScore(anchors=anchors)` on the AnchorSet object and you will get the same result. (All those parameters are basically just "disassembling" the anchors, query, and reference, for optimization purposes only.)

**Comment by friedue** [comment]
Ah, good to know. Nevertheless, this helped get rid of the initial error message, so I'm sticking with it for now.
