### ISSUE TITLE
How to choose values for 'dims.list' in FindMultiModalNeighbors function

### ISSUE THREAD

**Issue by sopenaml** [satijalab/seurat#3646]
I'm trying to follow your vignette for **WNN**. However I'm having problems to run `FindMultiModalNeighbors`. I believe my problem is due to the `dims.list` value.  In your vignette you only mention the following:  "We specify the dimensionality of each modality (similar to specifying the number of PCs to include in scRNA-seq clustering), but you can vary these settings to see that small changes have minimal effect on the overall results", but it's not mentioned how to select the values. My data is comprised of 24 samples, some of which have a small number of cells. For one of the samples with low number of cells, I've tried reducing the dims.list values with no success,  `FindMultiModalNeighbors`produces the the error below: What does the error refer to? and,  How can I best set the dims.list values ? 
```
samp
An object of class Seurat 
33559 features across 54 samples within 3 assays 
Active assay: ADT (13 features, 13 variable features)
 2 other assays present: RNA, HTO
 3 dimensional reductions calculated: tsne, pca, apca
> FindMultiModalNeighbors(samp, 
+                         reduction.list = list("pca", "apca"), 
+                         dims.list =  list(1:5, 1:5), 
+                         modality.weight.name = "RNA.weight")
Calculating cell-specific modality weights
Finding 20 nearest neighbors for each modality.
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Calculating kernel bandwidths
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Finding multimodal neighbors
  |                                                  | 0 % ~calculating  Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length
```

**Comment by yuhanH** [comment]
Hi, Sopenaml
If the sample only has 54 cells, the WNN method may not be proper to use, because the neighbor of each cell may not be very different. 
If you want to run it, you can set `knn.range` to 54 which is set to 200 by default. 
Since you have 24 samples, you can integrated their RNA and ADT separately, and then run WNN for these two integrated assays.
