### ISSUE TITLE
Spatial Function Issue with Interactive Plot. 

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#3648]
Hi, 
I am not sure if this is a bug, but I have saw others comment on it too. I am using the brain vignette for now.

This is the code that is giving an error: 

> ISpatialDimPlot(brain, interactive = TRUE)
Error in ISpatialDimPlot(brain, interactive = TRUE) : 
  unused argument (interactive = TRUE)
> 
> SpatialDimPlot(brain, interactive = TRUE)
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments

I have installed the latest Seurat and then I installed developmental version and started a new session again in RStudio also each time. 

I still get the same error. I tried changing the code slightly with an 'I' into the SpatialDimPlot function as you see above. 
Has anyone else overcame this issue? 
Please let me know as I cant move past it. 
Many thanks.

**Comment by cdarby** [comment]
Try `ISpatialDimPlot(brain)`. (There is no "interactive" argument to `ISpatialDimPlot` function which is the cause of the first error you report.)
