### ISSUE TITLE
How to map the query data to the existing UMAP coordination which is not derived from WNN?

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [satijalab/seurat#3649]
Hello,

We have an integrated Seurat object which is set to be the reference for our studies. It only contains one modality, scRNA-seq, therefore has nothing to do with WNN.

We would like to simply project our query data on to the UMAP of this reference, yet the Seurat4 vignettes provided seem to require that the users to recalculate the reference UMAP based on WNN neighborhood information. 

Is there a possibility to just project the query data on the existing UMAP? We have done label transfer using Seurat3, but it is desired to have query data sharing the same UMAP visualization.

Thank you!

**Comment by torkencz** [comment]
This function is not supported yet, but we will be working on it in the future. For now the functionalities supported can be found in the Seurat integration vignettes.
