### ISSUE TITLE
Highly variable genes in RunMultiCCA

### ISSUE THREAD

**Issue by dandepledge** [satijalab/seurat#365]
I've been thinking about highly variable genes and the use of RunMultiCCA.

 In your tutorial with the four pancreatic datasets you select the top 1000 highly variable genes are then filter for those present in more than one sample. I'm pretty sure the rationale for this is that different technologies and sequencing depths may result in the detection of rare cellular subtypes. This also controls for (techonology-related) batch effects as highly variable genes in just one dataset are discarded.

If I were to flip this on it's head and perform an analysis of several repeat datasets (same technology, multiple preparations, different batches), would'nt it make sense to require that highly variable genes are present in all datasets, the rationale being that having datasets from 3 or 4 different batch would negate a lower filtering level (e.g. a requirement for HVG to be present in two or more datasets)?

I'm also wondering what the specific definition of a highly variable gene is - how much should it vary across a dataset and is there any way of extracting this information? I'm curious as to whether it would be possible to plot a 'highly variable gene value' against the number of datasets it appears in to determine the potential strength of effect.

**Comment by satijalab** [comment]
In theory yes, it would make sense for genes to be highly variable in all datasets. however, we found that as the number of datasets increases, this can be limiting, particularly as  there are thresholds involved (as you point out). We suggest taking the union in the manuscript, or when there are many datasets, requiring the gene to be variable in some percentage of the datasets, but we would be happy to hear feedback on what is working well for users.
