### ISSUE TITLE
Small change in `Read10X_h5` related to CellRanger versioning logic

### ISSUE THREAD

**Issue by sjfleming** [satijalab/seurat#3653]
I would love to change the line 
https://github.com/satijalab/seurat/blob/fe93b05745e55ec2f66e3f0b4c4196aad9f4d5a7/R/preprocessing.R#L1155

to
```R
    if (hdf5r::existsGroup(infile, 'matrix')) {
```

**Why?**

I think this logic for determining CellRanger h5 version is more robust.  I also develop a tool that produces CellRanger-format h5 files as outputs (https://github.com/broadinstitute/CellBender), which are to be loaded in Seurat.  However, since my tool is written in python and saves files using PyTables, the files have a `PYTABLES_FORMAT_VERSION` attribute regardless of whether the format is v2 or v3.  This change would allow Seurat to load these files seamlessly, and the change should not have any drawbacks.

Please let me know if I can / should make a pull request, and how you like to handle code contributions.

**Comment by andrewwbutler** [comment]
Hi,

That seems reasonable to me. If you could make a PR to the `develop` branch with the change, we can get that merged in.

**Comment by sjfleming** [comment]
Thank you!!!  I will do that.
