### ISSUE TITLE
non-zero exit status during installation process of seurat v4.0 

### ISSUE THREAD

**Issue by tn00992786** [satijalab/seurat#3656]
When installing the seurat4.0 present the non-zero exit 

# Enter the commands in R (or R studio, if installed)
remotes::install_github("satijalab/seurat", ref = "release/4.0.0")
停止執行
ERROR: lazy loading failed for package 'Seurat'
* removing 'C:/Users/user/Documents/R/win-library/4.0/Seurat'
* restoring previous 'C:/Users/user/Documents/R/win-library/4.0/Seurat'
錯誤: Failed to install 'Seurat' from GitHub:
  (從警告轉換成) installation of package ‘C:/Users/user/AppData/Local/Temp/RtmpaaWZ7D/file3387b4b61f/Seurat_3.9.9.9008.tar.gz’ had non-zero exit status

**Comment by mojaveazure** [comment]
There's a bug in certain versions of R for Windows that prevent Rcpp from loading (see RcppCore/Rcpp#1100); please update your R installation to a newer version of R (I'm using R 4.0.3; you may need to uninstall previous versions of R to get RStudio to recognize the new R version).

If you are unable to update your R version, you can try one of the alternate Rcpp installation methods described in the issue linked above.
