### ISSUE TITLE
Cell cycle regression 

### ISSUE THREAD

**Issue by sumin-jang** [satijalab/seurat#3659]
Hi, 
I am trying to regress out the cell cycle related gene expression variations. 
I am running something similar to this:

 s <- CreateSeuratObject(raw.data = temp)
  s <- NormalizeData(object = s)
  s <- ScaleData(object = s)
  s <- CellCycleScoring(object = s, s.genes = s.genes, g2m.genes = g2m.genes, set.ident = TRUE)
  s <- ScaleData(object = s,  vars.to.regress = c("S.Score","G2M.Score"))

and every time get this error:
Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 1 worker of 1 failed to connect.

**Comment by samuel-marsh** [comment]
Hi,

This appears to be an error related the to parallel package (`makePSOCKcluster` is function from that package).  If you unload that package from environment does that solve the issue?

Best,
Sam

**Comment by sumin-jang** [comment]
Hi Sam,

I tried unloading it using detach, but it says:
Warning message:
‘parallel’ namespace cannot be unloaded:
  namespace ‘parallel’ is imported by ‘pbapply’, ‘Seurat’, ‘fpc’, ‘BiocGenerics’, ‘ape’, ‘snow’ so cannot be unloaded 

Are there any other ways to unload this package ?

Thanks,
Sumin

**Comment by samuel-marsh** [comment]
Hi Sumin,

So it appears that BioCGenerics loads parallel when that package is loaded.  I'm not sure why parallel is throwing the error here and maybe the devs can help understand why.  However, if you restart environment and load Seurat without the BiocGenerics package loaded and that should solve issue in short term.

Best,
Sam

**Comment by sumin-jang** [comment]
Hi Sam,

I wasn’t loading BiocGenerics separately before; I tried to detach it anyway but it says it’s not loaded. 
Is there another trick I could try while this issue gets resolved?

Sumin

**Comment by samuel-marsh** [comment]
Hi Sumin,

Try restarting your R session and just loading Seurat and your object and running the code without any other packages.  My guess is that another package that you are loading before analysis is loading the BioCgenerics or parallel package and causing the issue.

Best,
Sam

**Comment by sumin-jang** [comment]
Hi Sam,

I’ve been doing that and the problem still persists; I don’t think it’s some weird interference with another package. I’ve also tried using older versions of Seurat and it still freezes at the same function. 

Thanks 

Sumin

**Comment by samuel-marsh** [comment]
Closing since no response.  Please respond here in future if the issue is still causing problems.
