### ISSUE TITLE
SUGGESTION: Vignette 'Seurat - Guided Clustering Tutorial'

### ISSUE THREAD

**Issue by HenrikBengtsson** [satijalab/seurat#366]
Just some quick feedback on 'Seurat - Guided Clustering Tutorial' (Compiled: January 16, 2018) at http://satijalab.org/seurat/pbmc3k_tutorial.html:

* Instead of proposing to use `save()`, I'd suggest to use `saveRDS()`.  Contrary to `load()` which will overwrite any existing variables, `readRDS()` allows the user can reload a saved object to whatever variable name they prefer, e.g. `pbmc2 <- readRDS("...")`.

* You have to examples of `save()` with different filename extensions (`*.Robj` and `*.rda`).  I suggest to use `saveRDS()/loadRDS()` with filename extension `*.rds`.

PS. I like you're recent updates and appreciate that you're now distributing via CRAN.

**Comment by HenrikBengtsson** [comment]
And a small cleanup suggestion:  Drop `library(Matrix)` from
```r
library(Seurat)
library(dplyr)
library(Matrix)
```
since `Seurat` now attaches that by default.

**Comment by andrewwbutler** [comment]
Thanks for the suggestions. We've updated the tutorials to be more consistent with this.
