### ISSUE TITLE
Cannot Call 'CalcPerturbSig'

### ISSUE THREAD

**Issue by sabbas786** [satijalab/seurat#3664]
Hello,

I am working with the developmental installation of Seurat in an effort to use the CalcPerturbSig function, but am unable to call the function. I receive this error:

`Seurat::CalcPerturbSig()
Error: 'CalcPerturbSig' is not an exported object from 'namespace:Seurat'`

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] remotes_2.2.0         splitstackshape_1.4.8 dplyr_1.0.2           ggplot2_3.3.2         data.table_1.13.2     Seurat_3.9.9.9003   

Thanks in advance.

**Comment by papal22e** [comment]
Hello,

The development version does not contain mixscape-related functions. You can install the mixscape branch with the following command: `remotes::install_github("satijalab/seurat", ref = "mixscape")`. 
For additional guidance on how to run mixscape here's the most recent vignette from our website: [mixscape](https://satijalab.org/seurat/v3.2/mixscape_vignette.html).

Best,
Efi

**Comment by sabbas786** [comment]
I apologize, I thought it was in fact the developmental version that had Mixscape available. I installed Seurat using the command you mentioned, from Github. As you can see in the session info, I am running RV4 and SeuratV3.9. 

I was able to solve the issue by downgrading R to 3.6 and then retrying with `remotes::install_github("satijalab/seurat", ref = "mixscape")`. It seems running with R V4 does not work. 

Thanks.
