### ISSUE TITLE
Integration workflow doubts

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#3665]
Hi Seurat Team, first of all thanks for your work!

I was trying to come up with an Integration workflow and, after reading related issues, I have a few questions:

1. In issue #1778 you recommend calculating cell cycle scores on the RNA assay and regressing on the integrated assay, whereas in issues #2050 and #1836 the user proposes to regress out the cell cycle scores on the SCTransform step prior to integration and you say this procedure is valid too. Which would be the best way to proceed? 

2. Is it necessary to perform the SelectIntegrationFeatures() and PrepSCTIntegration() steps prior to integration when using SCTransform() as stated in [this](https://satijalab.org/seurat/v3.0/integration.html) tutorial? I can't see why it is so, and other users don't mention it on their workflows.

3. In your [integration tutorial](https://satijalab.org/seurat/v3.2/immune_alignment.html), you switch to "RNA" assay to perform DE analysis, but this could produce erratic results since it is not normalized, right?. I've read that in issue #1836 you recommend not to re-run a normalization on the integrated assay, but to use the SCT assay calculated prior to integration. However, as pointed in issue #2023 :
> One problem I can see with using the SCT assay after integration is that the SCT normalization was done separately for each sample, which is likely to introduce batch effects down the line.

so @jdrnevich proposes to, on the integrated object, switch to "RNA" assay, normalize it and continue the analysis. This step makes more sense to me since at this point you have all raw data together with the cluster identity obtained with the integrated data. However, which of the two approaches would you recommend? Moreover, @jdrnevich proposes to use NormalizeData() and ScaleData() on the "RNA" assay, would it be correct to use SCTransform again?

In overall, the workflow that I would follow and I want to corroborate is:

1. Create all seurat objects.
2. Perform the quality-check and filtering for each one of them.
3. Calculate the percentage of mitochondrial genes and cell cycle scores if wanted.
4. Normalize each dataset separately with SCTransform. Regress out percentage of mito genes and cell cycle score at this point. 
5. Prepare for integration with SelectIntegrationFeatures() and PrepSCTIntegration(). 
6. Integrate datasets. 
7. Run PCA, UMAP, FindClusters, FindNeighbors on integrated assay.
8. Switch to "RNA" assay and normalize it with SCTransform. 
9. Continue with the DE analysis.  

Thanks in advance!

PS: I've added more information to issue #3598, I will be very grateful if you could please take a look (I've pointed it out because, since it is closed, I don't know if you will see it).

**Comment by jdrnevich** [comment]
@MartaBenegas I agree that the SCTransform() is a better normalization than NormalizeData() + ScaleData(). The only reason I suggested the latter is ease of object manipulation - that method will put the normalized data inside the RNA assay (IIRC) rather than over-writing the SCT assay. I suppose you could create a separate object at this step. I haven't had to do this much because most of the experiments I've analyzed have not shown any shifts due to library so I haven't bothered to do the integration step. I am just getting started teaching a workshop on single cell data analysis, so I'll be getting into the gory details again this month.

**Comment by jaisonj708** [comment]
1) It is fine to compute cell cycle scores on either SCT or RNA, as long as it is normalized (i.e, run NormalizeData if you want to use the RNA assay). I think you may be confusing RNA with unnormalized data. Keep in mind that both SCT and RNA assays contain some version of raw counts and normalized counts.

2) Yes, in most cases it is necessary to run SelectIntegrationFeatures and PrepSCTIntegration, since your SCT assay may not immediately contain the residuals for all of your integration features. 

3) See (1)

Here is a modified version of your workflow: 

1) Create all seurat objects.
2) Perform the quality-check and filtering for each one of them.
3) Calculate percent.mito.
4) Normalize each dataset separately with SCTransform. Regress out percent.mito if desired.
5) Calculate cell cycle scores.
6) Prepare for integration with SelectIntegrationFeatures() and PrepSCTIntegration().
7) Integrate datasets.
8) ScaleData, regressing out cell cycle score if desired 
9) Run PCA, UMAP, FindClusters, FindNeighbors on integrated assay.
10) Switch to "SCT" assay and continue with the DE analysis.

**Comment by MartaBenegas** [comment]
Thank you very much to both of you!
Still, it is not very clear to me what would be the best procedure in **question 3**. Now I know that the RNA assay holds normalized data too (yes, I was confusing it), but I still don't know if it's fine to use the normalized slot (whether it is the "RNA" or "SCT") to perform the DE analysis. As we've pointed out, this normalization is made on each object separately prior to integration, so we wonder if this could affect the DE analysis. 
For now, I'm going to stick to the workflow you've made but I hope you can clarify this!

**Comment by jaisonj708** [comment]
Our DE functions will automatically choose the `counts` (unnormalized) or `data` slot (normalized) depending on which is appropriate for the specified DE test (Wilcox by default), so you do not need to worry about which to choose.

**Comment by Tushar-87** [comment]
>     1. Keep in mind that both SCT and RNA assays contain some version of raw counts and normalized counts.

This statement is very confusing. Did you mean: "same version of raw counts" and not  "some version" right?

If this is true, then it should be applicable only to raw counts. RNA assay does not have normalized data after SCT transform. The normalized counts are in SCT assay. Moreover, RNA assay has counts for all features while SCT assay has only variable features unless defaults are changed.

I checked RNA assay before and after SCT transform. As expected it is unchanged and the normalized counts are captured in newly formed SCT assay (although not all features are present here).

For DE, I normalized RNA assay with NormalizeData() after SCT transform, Integration and usual clustering steps. The data slot of the RNA assay now has normalized values. This should be fine, right?

@jaisonj708

**Comment by jdrnevich** [comment]
No, I did mean "some version". Maybe "raw" counts was the poor word choice. Both the RNA and SCT assays have slots for `counts` , `norm` and `scaled.data`. RNA's `counts` contain the original raw counts while SCT's `counts` contain corrected counts. RNA's `norm` and `scaled.data` will not have any data unless you run the older `NormalizeData(), FindVariableFeatures(), ScaleData()` functions as you have figured out. This should be fine for DE testing, except that the SCTransform normalization method is supposed to be superior to the older method. However, if you were integrating your samples before clustering and UMAP, the SCTransform was done separately for each sample and so those values cannot be used for DE

**Comment by nasjr08** [comment]
Hello, 
As a follow up to this thread, I have performed the integration more or less in line with what has been put here:

Create all seurat objects.
Perform the quality-check and filtering for each one of them.
Calculate the percentage of mitochondrial genes .
Normalize each dataset separately with SCTransform. Regress out percentage of mito genes and cell cycle score at this point.
Prepare for integration with SelectIntegrationFeatures() and PrepSCTIntegration().
Integrate datasets.
Run PCA, UMAP, FindClusters, FindNeighbors on integrated assay.
Switch to "RNA" assay and normalize it  both using  SCTransform and NormalizeData() + ScaleData().
Continue with the DE analysis/cluster markers either by using the "RNA" or "SCT" assays

....What I am concerned about is that it was mentioned here that performing SCtransform after integration will overwrite the SCT assay originally in the integrated seurat object. What I want to know is it appropriate to do the SCtransform after integration and is the overwritten data significant? I Did this as I felt it is important to get the pearson's residuals based on the cells, not just those of cells produced in the individual unintegrated datasets( I assume what would be overwritten is the SCT assay data of each unintegrated  sample merged together after integration... correct?).

Any help would be appreciated!

**Comment by lkqnaruto** [comment]
> No, I did mean "some version". Maybe "raw" counts was the poor word choice. Both the RNA and SCT assays have slots for `counts` , `norm` and `scaled.data`. RNA's `counts` contain the original raw counts while SCT's `counts` contain corrected counts. RNA's `norm` and `scaled.data` will not have any data unless you run the older `NormalizeData(), FindVariableFeatures(), ScaleData()` functions as you have figured out. This should be fine for DE testing, except that the SCTransform normalization method is supposed to be superior to the older method. However, if you were integrating your samples before clustering and UMAP, the SCTransform was done separately for each sample and so those values cannot be used for DE

Do you mean if SCTransform applied to each sample separately before integration as follows, then DE cannot use SCT assay and it would be better to use RNA assay instead ?

1. sample1 <- SCTransform(sample1)
    sample2 <- SCTransform(sample2)
    sample3 <- SCTransform(sample3)
2. Integrating 3 samples together

**Comment by jdrnevich** [comment]
Normalizing samples separately can artificially increase differences between them so in general statistical terms is a bad idea. Additionally, the integration removes sample-to-sample differences so samples will cluster together and co-locate on UMAP. However, when you do DE, those differences are what you are trying to find so you do not want to DE on separately normalized, integrated SCT. You could maybe make two different Seurat objects, 1 to get clustering and UMAP (separate SCT, integrated) and the second to do DE (combined SCT, no integration). The cluster calls and the UMAP embeddings could be transferred from the first to the second, although I have not actually done this before.

**Comment by MartaBenegas** [comment]
Now I'm really confused about how to proceed with a typical preprocessing -> clustering -> DE analysis when having multiple samples. 

What @jdrnevich says about using another Seurat object (with a combined normalization and without integration) for DE makes sense to me. The cluster calls can be easily transferred just by setting the Idents() of this object with the identities obtained with the integrated object. However, it would be really nice if a collaborator can shed some light on it. Please @jaisonj708 @andrewwbutler @mojaveazure or someone else. Maybe we are missing a step during the integration.

In addition, at the beginning of this thread @jaisonj708 proposed this workflow for regressing cell cycle genes when the data is SCTransform-normalized:
> Here is a modified version of your workflow:
> 1. Create all seurat objects.
> 2. Perform the quality-check and filtering for each one of them.
> 3. Calculate percent.mito.
> 4. Normalize each dataset separately with SCTransform. Regress out percent.mito if desired.
> 5. Calculate cell cycle scores.
> 6. Prepare for integration with SelectIntegrationFeatures() and PrepSCTIntegration().
> 7. Integrate datasets.
> 8. ScaleData, regressing out cell cycle score if desired
> 9. Run PCA, UMAP, FindClusters, FindNeighbors on integrated assay.
> 10. Switch to "SCT" assay and continue with the DE analysis

However, in the new integration [manual](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1), on the "Performing integration on datasets normalized with SCTransform" section, it says:
> When running sctransform-based workflows, including integration, do not run the ScaleData() function

So I'm not sure what is the best way to proceed and I came up with some questions:
1. Why not regress cell cycle scores when SCTransform-normalizing the data? as it is done with the percentage of mitochondrial genes.
2. Why is it necessary to compute a cell cycle scoring and not a "mitochondrial scoring"? 

Thanks in advance,
Marta.
