### ISSUE TITLE
Question: avg_diff same as avg_logFC?

### ISSUE THREAD

**Issue by ozgeevrim82** [satijalab/seurat#367]
Hi,
I am using the Seurat 2.2.1 and previously used 2.2.0. While running FindAllMarkers, with version 2.2.0 we would get avg_diff column. Now with version 2.2.1, it is not existing and avg_logFC column is created. I am wondering if avg_diff and avg_logFC is giving the same values. How is avg_logFC calculated? 
Thanks!

**Comment by leonfodoulian** [comment]
Hi,

Yes, they are the same. As to how they are calculated, please check the codes at [lines 171 and 173](https://github.com/satijalab/seurat/blob/f4da9c6e725ee9ee833d8ef60809e56e13b3062a/R/differential_expression.R#L171-L173), and [line 284 in differential_expression.R](https://github.com/satijalab/seurat/blob/f4da9c6e725ee9ee833d8ef60809e56e13b3062a/R/differential_expression.R#L284). Just in case, it is the difference in the mean expression level between the 2 groups, for each gene. 

Best,
Leon

**Comment by ozgeevrim82** [comment]
Hi,
Thanks for the help!
Best,
Ozge
