### ISSUE TITLE
RNA and protein weights for PBMC multimodal atlas

### ISSUE THREAD

**Issue by ryland-mortlock** [satijalab/seurat#3670]
Hello, I am enjoying getting to know Seurat v4, thanks for all of your hard work!

I am working with the h5 file for your multimodal PBMC atlas from your recent pre-print, and I wanted to check out the RNA and protein weights for different cell types within the full atlas, as you did when illustrating the WNN approach on Bone Marrow dataset in figure 2B of your pre-print. 

It seems like the RNA.weight is not stored in the metadata and I am wondering if there is anywhere I can find this information without re-running your Weighted Neighbor Analysis on this large dataset? Thanks!

**Comment by yuhanH** [comment]
Hi, 
we didn't store the RNA and protein information, but you can calculate it by the following script.
```
obj <- FindMultiModalNeighbors(object = obj,  
                              reduction.list = list("pca", "apca"),
                              dims.list = list(1:40, 1:50),
                              k.nn = 30,
                              knn.range = 500, 
                              modality.weight = "RNA_weight" )
```
Protein weight is 1 - RNA weight.

**Comment by ryland-mortlock** [comment]
Thank you for clarifying!
