### ISSUE TITLE
New feature to compare non-unique cluster sizes of two (or more) conditions

### ISSUE THREAD

**Issue by strawberry789** [satijalab/seurat#3672]
Is it possible to establish a new feature to compare the sizes of clusters between two (or more) conditions from 10X data?  This will be useful if the two conditions do not generate unique clusters, but have different cluster sizes.  Wonder how to make these differences in cluster sizes statistically significant?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but I believe what you are describing is differential abundance between clusters.  I would recommend checking out this vignette: [https://osca.bioconductor.org/multi-sample-comparisons.html#differential-abundance](https://osca.bioconductor.org/multi-sample-comparisons.html#differential-abundance).  While not the only solution/method to analyze such composition effects it gives some nice background and ideas for this type of analysis.

Best,
Sam

**Comment by strawberry789** [comment]
Hi Sam,

Thanks a lot for the recommendation.  It helps a lot.

**Comment by TomKellyGenetics** [comment]
The "propeller" function implements this and supports Suerat objects. https://github.com/Oshlack/speckle

**Comment by jaisonj708** [comment]
Looks like this issue has been resolved.
