### ISSUE TITLE
Adding lognormalized data to metadata

### ISSUE THREAD

**Issue by alectika** [satijalab/seurat#3674]
Dear Seurat users,

How can I add my lognormalized expression values to my metadata in order to plot them with other visualization tools? I want to create a grouped boxplot with ggplot for a gene with the same expression values as in Seurat's violin plots. I could only manage to do it with count numbers in my metadata. As far as I know, Seurat doesn't have boxplot function.

Thanks!

**Comment by timoast** [comment]
You can use the `GetAssayData()` function to extract the normalized data matrix from the Seurat object. You could then add the relevant rows of the expression matrix to a dataframe if you need to create plots with other visualization tools
