### ISSUE TITLE
intergrated bulk RNA and  scRNA using Seurat

### ISSUE THREAD

**Issue by crystal0721** [satijalab/seurat#3675]
hello,
   Thanks for   this  great work of Seurat. While we wonder if we cound use Seurat to  intergrated bulk RNA data and single RNA Data,  if we could, how much samples of buk RNA should have?
    We had  only  22 samples of  bulk RNA and  about 6000 cells of scRNA, while when we used  Seurat to intergrated the two data, we got the following error  at FindTransferAnchors analysis:
`Projecting PCA
Finding neighborhoods
Error in nn2(data = dims.cells1.self, k = k + 1, eps = eps) :
  Cannot find more nearest neighbours than there are points`

And we  search for this  question ，some one suggest  should  adjust  k.anchor， we used  the lower  values and got the same error.So We don‘t know how to solve  this  problem and ask for help，thanks very much and looking for your apply.

**Comment by jaisonj708** [comment]
Seurat was not designed to be used for integrating or transferring bulk RNA-seq with scRNA-seq data, but you can give it a try. Assuming that you are using the scRNA-seq data as your reference and the bulk data as your query (treating each of your 22 samples as a cell), `FindTransferAnchors` should work as long as you set your `k` parameters to be <22. If you are still having trouble, feel free to your object to seuratpackage@gmail.com.

**Comment by crystal0721** [comment]
Thanks very much for your apply. While I have tried  as you said and stilled have trouble.  We  found some used the downsampleMatrix of DropletUtils to  downsample bulk RNA and then intergrated with scRNA，may be could. We are trying.
