### ISSUE TITLE
How to do ridgeplot for feature names with "underscores" , such as "adt_Rat_IgG1"?

### ISSUE THREAD

**Issue by jimklarry** [satijalab/seurat#3676]
I try doing Ridgeplot for features in Adt data. The features that have underscore in names don't get recognized or plotted.

The following requested variables were not found: Rat_IgG1, Rat_IgG2a, Armenian_Hamster_IgG_Isotype_Ctrl

How can I plot these features, either in FeaturePlot or RidgePlot?

Thanks.

**Comment by RobertWhitener** [comment]
Have you checked 'Rat-IgG1', 'Rat-IgG2a', etc?

I always get a notice when creating a new Seurat object that underscores '_' in feature names are converted into dashes '-' in feature names.

Robert
