### ISSUE TITLE
v4- WNN cluster resolution 

### ISSUE THREAD

**Issue by shefalipatel7** [satijalab/seurat#3677]
Hi,

For the new WNN analysis, I noticed that when using FindClusters with this method usually produces more clusters in total than the previous methods in Seurat v2 and v3. I know there was a suggested resolution parameter based on the number of cells total number of cells, and I wanted to see if there was an optimal resolution to apply when using the WNN as to not overcluster the data. Any help or tips would be appreciated!

**Comment by jaisonj708** [comment]
It is difficult to suggest a single optimal resolution parameter. In fact, for any increase in resolution (within reasonable limits), you will likely find meaningful biological sub-clusters emerge as well as clusters that form based on uninteresting variation or noise, so it is always a tradeoff. You can vary your resolution parameter between 0.5 and 2 in increments of 0.25 and pick the one that best reflects the clusters / cell types you believe are in your data.
