### ISSUE TITLE
Adding metadata column to a Seurat Object

### ISSUE THREAD

**Issue by RobertWhitener** [satijalab/seurat#3679]
Hi,

I have a Seurat object of RNAseq data comprised of 10 donors (and multiple Seurat objects comprising the individual cell types identified in the dataset).  

After doing some analysis I am thinking it makes sense to stratify the donors into one of three Categories.

Therefore, without deleting the donor information, I'm trying to add a new column of meta data to the Seurat object to note which of the three categories each cell belongs to.  For example:

Donor1 is Cat1
Donor2 is Cat3
Donor3 is Cat2
Donor4 is Cat2
Donor5 is Cat1
Donor6 is Cat3
etc.

I would like to be able to perform DESeq analysis by Category within each cell type, and plot expression data (Vlnplot, Dotplot, and Heatmap) by said category.

Any help is appreciated!
Robert

**Comment by RobertWhitener** [comment]
I figured out a way to do this, but still wondering if there is an easier/faster way.

`
object$seurat_cluster <- object@active.ident                     # stash cluster ID into new metadata column
object@active.ident <- object@DONORID                         # copy DONORID to @active.ident
categories <- c('Cat1','Cat3','Cat2','Cat2','Cat1','Cat3' ...)     # make a list of the categories 
DONORIDS <- levels(object@DONORID)                           # make a list of the donors
names(categories) <- DONORIDS                                       # rename the values in the list
object <- RenameIdents(object, categories)                       # rename object@active.ident  
object$STAGES <- object@active.ident                              # copy to a new metadata column
object@active.ident <- object$seurat_cluster                    # restore the original cluster ids
`

After this, I have the original seurat_cluster number as the active.ident, and also have the "stage" designation.  Making a table of object$DONORID x object$STAGES indicates everything was assigned correctly.

**Comment by samuel-marsh** [comment]
Hi,

May be an easier/better way but assuming your Donor IDs are stored either in orig.ident or different column in meta data.  Then you could do something like the following:
```
Cat1 <- c("1", "2")
Cat2 <- c("3", "4")
object@meta.data$Category[object@meta.data$orig.ident %in% Cat1] <- "Cat1"
object@meta.data$Category[object@meta.data$orig.ident %in% Cat2] <- "Cat2"
```

Best,
Sam

**Comment by RobertWhitener** [comment]
Hi Sam,

Yes, the Donor IDs are in a separate column in the meta data.  Thank you for that.  Your method is the one I initially was trying, but never managed to get correct.  Still trying to wrap my head around coding.

Thanks!
Robert
