### ISSUE TITLE
color scale legend to SplitDotPlotGG

### ISSUE THREAD

**Issue by alectika** [satijalab/seurat#368]
Hi,

I am using Seurat tutorial for stimulated and control PBMCs. I want to use SplitDotPlotGG function for my selected genes. In the graph, there is a legend for dot scale but color scale legend is missing. I have tried to add one but I couldn't succeed. Can anyone help me?

**Comment by leonfodoulian** [comment]
Hi,

This should be updated in a future release of Seurat. If you'd like to adapt the function yourself, you should find all you need in the following 2 pull requests: [#306](https://github.com/satijalab/seurat/pull/306) and [#307](https://github.com/satijalab/seurat/pull/307).  

Best,
Leon

**Comment by leonfodoulian** [comment]
Maybe you could also [install the development version of Seurat](http://satijalab.org/seurat/devinstall.html) (I am, however, not aware to what extent this is recommended).

**Comment by alectika** [comment]
Hi Leon,

Thank you so much for your answer!
