### ISSUE TITLE
Assigning cell type

### ISSUE THREAD

**Issue by YhGa** [satijalab/seurat#3681]
Hi all,

Recently I tried to learn single cell data analysis. Thanks for your excellent tool. 

Now I follow your tutorial to repeat the results as shown in the “Guided tutorial --- 2,700 PBMCs” part. Here I have a question about the cell type. In your last step, “Assigning cell type identity to clusters”, how did you make the assignment? Can one marker gene represent the corresponding cluster? In addition, is there any literature or website on the marker genes of the cell type? For me, the species I focus on is livestock and the tissue is also PBMC. Do you have any idea assigning cell type identity to clusters?

Thanks,
Yahui

**Comment by timoast** [comment]
This comes from reading the literature and identifying gene markers for different cell types. Alternatively, if you have a reference dataset with annotated cell types for the same tissue, you can try transferring cell type labels to the query dataset using the [integration methods](https://satijalab.org/seurat/v3.2/integration.html) in Seurat.
