### ISSUE TITLE
Error in CLR normalization with merged runs

### ISSUE THREAD

**Issue by ankushs0128** [satijalab/seurat#3684]
HI, 

I have different runs scRNA seq and scCiteSeq (run1,run2, and run3) merged together.  
Using Normalization CLR  with margin 2 is throwing an error on the runUMAP step. 
I am normalizing the HTO data before merging as, without normalization, quite a few cells (approx 40-50%) are computed as negatives. 
Could you please add some information on how to use normalization on CLR on merged data sets?
 

```
CD4T <- NormalizeData(CD4T, 
normalization.method = 'CLR',
margin = 2) %>%  ScaleData() %>% RunPCA(reduction.name = 'apca')

CD4T_integrated <- FindMultiModalNeighbors(
CD4T, reduction.list = list("pca", "apca"), 
dims.list = list(1:20, 1:10), 
modality.weight.name = "RNA.weight", 
verbose = TRUE
)

CD4T_integrated <- RunUMAP(
CD4T_integrated, nn.name = "weighted.nn", 
reduction.name = "wnn.umap", 
reduction.key = "wnnUMAP_"
)

```
`Error in x2set(Xsub, n_neighbors, metric, nn_method = nn_sub, n_trees, : Non-finite entries in the input matrix`

Thanks in Advance

**Comment by yuhanH** [comment]
i am wondering if you set default assay to ADT, when you run 
```
CD4T <- NormalizeData(CD4T, 
normalization.method = 'CLR',
margin = 2) %>%  ScaleData() %>% RunPCA(reduction.name = 'apca')
```

**Comment by ankushs0128** [comment]
Yes, I did set ADT as default assay

**Comment by yuhanH** [comment]
I see. Could you generate a ADT UMAP from apca?
