### ISSUE TITLE
seurat v4 how to Integrate datasets before Reference Mapping

### ISSUE THREAD

**Issue by SlatitudeChou** [satijalab/seurat#3686]
I have tried seurat v4 Reference Mapping.
But my datasets need integarate first because of the batch effect.
I run the SCT workflow to integrate my datasets as below:
SCTransform()
SelectIntegrationFeatures()
PrepSCTIntegration()
FindIntegrationAnchors()
IntegrateData()
anchors <- FindTransferAnchors(   reference = reference,   query = mydatasets,   normalization.method = "SCT",   reference.reduction = "spca",   dims = 1:50 )

but it reported error in the next step :
mydatasets <- MapQuery(   anchorset = anchors,   query = mydatasets,   reference = reference,   refdata = list(     celltype.l1 = "celltype.l1",     celltype.l2 = "celltype.l2",     predicted_ADT = "ADT"   ),   reference.reduction = "spca",    reduction.model = "wnn.umap" )

Then I  tried the workflow without integration:
mydatasets <- SCTransform(mydatasets, verbose = FALSE)
anchors <- FindTransferAnchors(   reference = reference,   query = mydatasets,   normalization.method = "SCT",   reference.reduction = "spca",   dims = 1:50 )
mydatasets <- MapQuery(   anchorset = anchors,   query = mydatasets,   reference = reference,   refdata = list(     celltype.l1 = "celltype.l1",     celltype.l2 = "celltype.l2",     predicted_ADT = "ADT"   ),   reference.reduction = "spca",    reduction.model = "wnn.umap" )

It worked well and it didn't seem like existing batch effect. But I'm not sure.
Should I integrate before Reference Mapping? Which assay should I use to mapping?
OR I don't need to integrate in this situation.

**Comment by jaisonj708** [comment]
What error were you receiving in `MapQuery`? A traceback would be helpful

In general, it is best to remove batch effects in your reference prior to mapping. Otherwise, technical effects may influence which anchors are formed and not formed.

**Comment by SlatitudeChou** [comment]
> What error were you receiving in `MapQuery`? A traceback would be helpful
> 
> In general, it is best to remove batch effects in your reference prior to mapping. Otherwise, technical effects may influence which anchors are formed and not formed.

as below:
object has three already ,RNA SCT integrated
Defaultassay is SCT

Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l1_ to predictionscorecelltypel1_
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predictionscorecelltype.l2_ to predictionscorecelltypel2_
Transfering 224 features onto reference data
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from predicted_ADT_ to predictedADT_
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Thank you

**Comment by yuhanH** [comment]
Hi, 
It may be a bug related to `RenameCells`.  You could update the lates ` release/4.0.0 ` branch. It should be fixed.

Except for the integration step, you can also try to normalize and map each batch individually to the reference, and then merge those objects after mapping.
