### ISSUE TITLE
Seurat v4.0 beta bug found with clustering

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#3687]
Hello all!

Great job with the latest Seurat 4.0 beta, the multimodal integration analyses are incredibly useful. I just wanted to report a bug I noticed when running weighted nearest neighbor analysis, as described your [vignette](https://satijalab.org/seurat/v4.0/weighted_nearest_neighbor_analysis.html)

I found that if the cells in the two assays intended for integration are not ordered identically (i.e., cell 1, 2, ... n, in both assays), then the integration is performed poorly and the clustering is nonsensical. See below for results: 

cells arranged identically: 
![image](https://user-images.githubusercontent.com/46906473/98251911-59859d80-1f47-11eb-9fbe-babe371c5f7c.png)

cells not arranged identically: 
![image](https://user-images.githubusercontent.com/46906473/98252014-791cc600-1f47-11eb-82c2-7f760b6d1935.png)

**Comment by andrewwbutler** [comment]
Hi,

Can you provide some code + data to reproduce what you're seeing here? How are you determining/changing "cell order"?
