### ISSUE TITLE
Analyse cluster separation

### ISSUE THREAD

**Issue by mstemmer** [satijalab/seurat#3688]
I was wondering about a good way to describe the degree of cluster separation one can see after running UMAP. Ideally I would like to get some kind of quantification on the "clusterdnes" of my dataset.

Does someone have a good idea to describe this? Maybe the adjusted Rand index (ARI) or normalized mutual information (NMI) could be useful metrics, but was not really sure how to use these with seurat. Also they would need some kind of ground truth, which might be tricky to get with single cell data...

Would appreciate any ideas or directions!

**Comment by NMikolajewicz** [comment]
I've previously used silhouette widths to assess how well defined the clusters are, and this has had varying success depending on what data set I was working with!

**Comment by mstemmer** [comment]
Thanks @NMikolajewicz !
That's a good idea. Here is a useful link for others interested in this [silhouette_analysis](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html)

Looks like this is useful when comparing and assessing different resolutions within the same dataset. However for comparing two independent datasets this might not be ideal. Any ideas on this?

**Comment by jaisonj708** [comment]
You can compute the silhouette coefficient for each of your clusters and take the mean across clusters. This is basically a measure of intra-cluster vs (nearest) inter-cluster distance. See the `silhouette` function in R's `cluster` package for more details.
