### ISSUE TITLE
How to change the x-y scale in the TSNEplot?

### ISSUE THREAD

**Issue by xbjie123** [satijalab/seurat#369]
Hi,

Here I have different groups of data, I want to keep these plots at the same level of scales in the TSNE plot. However, I couldn't find any parameters related to it.  Does someone achieve this? It's very helpful.
Thanks for that.

Best
BJ

**Comment by leonfodoulian** [comment]
Hi,

To my understanding, t-SNE axis scales are in arbitrary units. In my humble opinion, it would be much easier, and would make more sense, to completely remove the scales from the plots.

```R
TSNEPlot(object = object, do.return = TRUE) + 
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
```

If you insist on rescaling the plots, you should be able do that using `ggplot2::scale_x_continuous()` and `ggplot2::scale_y_continuous()`. You should also be able to find the cell embeddings on the two first tSNE axes in `object@dr$tsne@cell.embeddings`. Simply set `do.return = TRUE` and you can handle these plots as standard `ggplot2` objects. 

Hope that helped!

Best,
Leon

**Comment by xbjie123** [comment]
Dear Leon,

Thanks very much. In fact, the purpose of this is to make it comparable for these TSNE plots. So maybe I could merge these different samples together and do TSNE plot again. But I'm not sure if this is better to  do it. Do you have any other suggestions? 

Best
BJ

**Comment by leonfodoulian** [comment]
Hi BJ,

I don't know what you mean when you say _'to make it comparable for these TSNE plots'_. If you aim at comparing samples to each other, you can use [Seurat's CCA pipeline](http://satijalab.org/seurat/immune_alignment.html). Regarding what you want to do, I suggest you read more about tSNE axes in the posts [here](https://stats.stackexchange.com/questions/254090/what-are-the-axes-of-a-t-sne-scatterplot) and [here](https://www.reddit.com/r/MachineLearning/comments/2bdxdf/what_are_the_axes_in_tsne/).

Best,
Leon

**Comment by xbjie123** [comment]
Hi Leon,

Right. I am trying to use the CCA. But I get the error when I run `AlignSubspace`, there is an error
 ```
"Error in object@dr[[i]]@cell.embeddings[cells.use, , drop = FALSE] :
  subscript out of bounds" 
```
I also noticed there are some people with the same problem. But I didn't find a effective resolvement. So now I am using the [MergeSeurat](https://davetang.org/muse/2018/01/24/merging-two-10x-single-cell-datasets/) to do this. 
And it's a great helpful for your links about tSNE axes. 

Thanks very much.
BJ

**Comment by xbjie123** [comment]
Hi Leon,

Right. I am trying to use the CCA. But I get the error when I run `AlignSubspace`, 
```
"Error in object@dr[[i]]@cell.embeddings[cells.use, , drop = FALSE] :
 subscript out of bounds" 
```
I also noticed there are some people with the same problem. But I didn't find an effective resolvement. So now I am using the [MergeSeurat](https://davetang.org/muse/2018/01/24/merging-two-10x-single-cell-datasets/) to do this.
And it's a great helpful for the links about tSNE axes.

Thanks very much.
BJ
