### ISSUE TITLE
Filetring HTOs before demux

### ISSUE THREAD

**Issue by clairebio27** [satijalab/seurat#3691]
Hi ,

Thank you for this very useful tool.
I am demuxing the HTO(sequenced with TCR), alone using the Seurat vignette (4 HTOs per experiment) . The count matrix I was  built based on a script (correcting (HMdistance 1, and collpsing to cell ranger white list , (I tried with cite-seq results  too) ) and taking UMI count from the same to build the matrix input for Seurat. 
Following is the command used,
pbmc.hashtag <- CreateSeuratObject(counts =  hto.data)
pbmc.hashtag[["HTO"]] <- CreateAssayObject(counts =  hto.data)
pbmc.hashtag <- NormalizeData(pbmc.hashtag, assay = "HTO", normalization.method = "CLR")
pbmc.hashtag <- HTODemux(pbmc.hashtag, assay = "HTO", positive.quantile = 0.99) 

But the ridge plot shows , the HTOs are not well classified (attached). I know that I need to play with different pos.quant values, but it doesn't seem to improve the deconvolution. it doesn't seems improved my results

When we do with RNA data, from the paper it is clear that you have set UMI “cutoff as 200, So  here when I do HTO demux alone, can I set the same? or which will be the best way?

But at the same time I build the count matrix using cell ranger feature barcode count matrix and tried demux with same commands as above worked well, (It is noted that cellranger count matrix has tossed out a  lot of cells, and the final deconvoluted mapping to TCR clonotypes resulted to 50%  ) though the clonotype distribution and and assignment was in agreement with the experiment plan. 

Thanks for any help.
Claire
![EXP20000469_Sample_01_HTO_heatmap](https://user-images.githubusercontent.com/68902463/98310835-f7a35300-1f9b-11eb-9593-b5039ab2a3c6.png)
![EXP20000469_Sample_01_HTO_ridgeplot](https://user-images.githubusercontent.com/68902463/98310836-f7a35300-1f9b-11eb-9e7c-4869f2e40c81.png)

[files.zip](https://github.com/satijalab/seurat/files/5498374/files.zip)

**Comment by clairebio27** [comment]
To add on this query, I am getting ~0.7 million reads out of  total 970383  reads are with the UMI count =1. Does it affecting my analysis?

**Comment by timoast** [comment]
It will definitely help if you remove all the empty droplets from the dataset, it looks like you have a lot of negative cells. You could use the cellranger output or filter based on a UMI cutoff
