### ISSUE TITLE
SCTransform + CellCycleScoring raises error: Insufficient data values to produce 24 bins

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#3692]
Hi Seurat Team!
As we've pointed out on issue #3665, I was calculating cell cycle scores after normalizing each dataset with the following code:
```
library(Seurat)

raw <- read.table("~/count_table_subset.txt", header = TRUE, row.names = 1)
sobject <- CreateSeuratObject(raw)

metadata <- read.table("~/cell_type_relationship_subset.txt", sep="\t", row.names = 1)
sobject <- AddMetaData(sobject, metadata, col.name="type")


sobjects.list <- SplitObject(sobject, split.by = "type")

for (i in 1:length(sobjects.list)){
  # NORMALIZATION
  sobjects.list[[i]] <- SCTransform(sobjects.list[[i]], new.assay.name = "SCT")
  #CELL CYCLE SCORES
  cell_cycle_genes <- read.csv(file = "~/cell_cycle_subset.txt", sep = "\t", quote = "")
  g2m.genes <- as.character(cell_cycle_genes[cell_cycle_genes$phase=="G2/M",2])
  s.genes <- as.character(cell_cycle_genes[cell_cycle_genes$phase=="S",2])
  sobjects.list[[i]] <- CellCycleScoring(sobjects.list[[i]], s.features = s.genes,
                        g2m.features = g2m.genes,
                        set.ident = TRUE, assay="SCT")
}
```
But it raises this error:
```
Error: Insufficient data values to produce 24 bins. Run `rlang::last_error()` to see where the error occurred.
6. stop(fallback)
5. signal_abort(cnd)
4. abort(glue("Insufficient data values to produce {n} bins."))
3. cut_number(x = data.avg + rnorm(n = length(data.avg))/1e+30, n = nbin, labels = FALSE, right = FALSE)
2. AddModuleScore(object = object, features = features, name = name, ctrl = min(vapply(X = features, FUN = length, FUN.VALUE = numeric(length = 1))), ...)
1. CellCycleScoring(sobjects.list[[i]], s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE, assay = "SCT")
```
Although the cell cycle genes are present in the dataset:
```
> s.genes %in% rownames(sobjects.list[[1]][["SCT"]][])
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> g2m.genes %in% rownames(sobjects.list[[1]][["SCT"]][])
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> s.genes %in% rownames(sobjects.list[[2]][["SCT"]][])
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> g2m.genes %in% rownames(sobjects.list[[2]][["SCT"]][])
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```
I've tried setting `min.cells` to 1 and 3 on `CreateSeuratObject()` function as suggested in issue #1227 but it didn't work. 

However, if I run `NormalizeData()` instead of `SCTransform()` it doesn't produce any error. I thought that it doesn't matter which method do I use as long as data is normalized before computing cell cycle scores? #1679
I could run `NormalizeData()` before `CellCycleScoring()`, but I wouldn't like to have the normalized data on the "RNA" assay (it can't be stored in another slot). How can I solve this problem? 

**PS:  I've added more information to issue #3598 and another question to issue #3665. I will be very grateful if you could please take a look!** (I've pointed it out because, since it is closed, I don't know if you will see it).

**Comment by jaisonj708** [comment]
Hi, I've responded to your follow-ups on those 2 issues.

This error has been discussed in #1227. It seems that you do not have sufficient data to produce 24 bins. This may only be an issue with SCTransform because it includes a mandatory filtration step. To address your question about NormalizeData - I am not sure whether you want to add normalized data to a separate assay or remove the normalized data entirely. In the latter case, you can fill the `data` slot with NULLs, and in the former case, you can simply duplicate or rename the `RNA` assay.

**Comment by MrModenait** [comment]
Apologies to re-open the thread @jaisonj708 but I am having the same issue and hence I would like to check whether my solution is viable. Like you commented, the cause of my error message was not lack of normalization but rather too small datasets. In the old workflow I ran `CellCycleScore` on a large dataset between `IntegrateData` and `ScaleData`; in the new workflow the refressing out cell cycle score before the integration and therefore I was attempting to run `CellCycleScore` on each of the small datasets.
Hence I can only regress out cell cycle score after `SCTransform` and `IntegrateData`. When I come to do this, should I repeat `SCTransform` or run a traditional `ScaleData`? 
Many thanks in advance for your feedback!

**Comment by frederikziebell** [comment]
I have the exact same issue as @MrModenait: I have a small dataset and computing cell cycle scores produces the error because is seems that in the internal call of `cut_number()` there are less than 24 distinct data values. @jaisonj708, could you please re-open this issue?

**Comment by MrModenait** [comment]
Dear @frederikziebell, I was eventually able to solve this problem drawing on inspiration from issue #1679. What I realised I had to do was to LogNormalize the data in my `RNA` assay before running `CellCycleScoring`. The integration went well without further problems. This is what I did:

```
#Run CellCycleScoring on each dataset using "alternate workflow"
for (i in 1:length(My_Dataset_List)) {
  My_Dataset_List[[i]] <- NormalizeData(My_Dataset_List[[i]], verbose = FALSE)
  My_Dataset_List[[i]] <- CellCycleScoring(My_Dataset_List[[i]],
                                         s.features = cc.genes$s.genes,
                                         g2m.features = cc.genes$g2m.genes,
                                         set.ident = TRUE)
  My_Dataset_List[[i]]$cc_difference <- My_Dataset_List[[i]]$S.Score - My_Dataset_List[[i]]$G2M.Score
}

My_SCT_Dataset_List <- list(1,2,3,4) #Prepare new list

#run SCTransform on each object separately, normalising according to cell cycle
for (i in 1:length(My_Dataset_List)) {
  My_SCT_Dataset_List[[i]] <- SCTransform(My_Dataset_List[[i]], 
                                           assay = 'RNA',
                                           new.assay.name = 'SCT',
                                           vars.to.regress = c('percent.mt', 'nFeature_RNA', 'nCount_RNA', "cc_difference"),
                                           return.only.var.genes = F)
  head(My_SCT_Dataset_List[[i]])
}
```

P.S. I see you're a keen cyclist too!

**Comment by denvercal1234GitHub** [comment]
Hi @MrModenait - Thanks for posting the code. But wouldn't this be you are normalizing the data already normalize because you use SCTransform() on RNA assay that you had already NormalizeData on RNA asay?

**Comment by MrModenait** [comment]
Hi @denvercal1234GitHub and thanks for your question. I don't think it should be a problem since I have specified `assay = 'RNA'` in the input for `SCTransform`, and according to issue #2993 the function always uses the `counts` slot which includes raw UMI counts. See also [this line](https://github.com/satijalab/seurat/blob/b51801bc4b1a66aed5456473c9fe0be884994c93/R/preprocessing.R#L1224) from the `SCTransform` function which is refereced too in the previous issue.

**Comment by gringer** [comment]
For anyone else who is seeing this issue even after doing minimum cell filtering, I have also encountered this error for data I had created manually via CreateSeuratObject on long-format count data from Rhapsody/SevenBridges that I had wide-pivotted into a table, then converted into a matrix.

Digging into the R code, I created the following functions that included more console output:

```
AddModuleScore <-
function (object, features, pool = NULL, nbin = 24, ctrl = 100,
    k = FALSE, assay = NULL, name = "Cluster", seed = 1, search = FALSE,
    ...)
{
    if (!is.null(x = seed)) {
        set.seed(seed = seed)
    }
... [code omitted] ...
    pool <- pool %||% rownames(x = object)
    data.avg <- Matrix::rowMeans(x = assay.data[pool, ])
    data.avg <- data.avg[order(data.avg)]
    cat("Data range:", range(data.avg, na.omit=TRUE), "\n");
    cat("Cutting data of length", length(data.avg), "into", nbin, "bins\n");
    data.cut <- cut_number(x = data.avg + rnorm(n = length(data.avg))/1e+30,
        n = nbin, labels = FALSE, right = FALSE)
    names(x = data.cut) <- names(x = data.avg)
    ctrl.use <- vector(mode = "list", length = cluster.length)
    cat("Processing clusters\n");
    for (i in 1:cluster.length) {
        features.use <- features[[i]]
        for (j in 1:length(x = features.use)) {
            ctrl.use[[i]] <- c(ctrl.use[[i]], names(x = sample(x = data.cut[which(x = data.cut ==
                data.cut[features.use[j]])], size = ctrl, replace = FALSE)))
        }
    }
    ctrl.use <- lapply(X = ctrl.use, FUN = unique)
    ctrl.scores <- matrix(data = numeric(length = 1L), nrow = length(x = ctrl.use),
        ncol = ncol(x = object))
    for (i in 1:length(ctrl.use)) {
        features.use <- ctrl.use[[i]]
        ctrl.scores[i, ] <- Matrix::colMeans(x = assay.data[features.use,
            ])
    }
    features.scores <- matrix(data = numeric(length = 1L), nrow = cluster.length,
        ncol = ncol(x = object))
    for (i in 1:cluster.length) {
        features.use <- features[[i]]
        data.use <- assay.data[features.use, , drop = FALSE]
        features.scores[i, ] <- Matrix::colMeans(x = data.use)
    }
    features.scores.use <- features.scores - ctrl.scores
    rownames(x = features.scores.use) <- paste0(name, 1:cluster.length)
    features.scores.use <- as.data.frame(x = t(x = features.scores.use))
    rownames(x = features.scores.use) <- colnames(x = object)
    object[[colnames(x = features.scores.use)]] <- features.scores.use
    CheckGC()
    DefaultAssay(object = object) <- assay.old
    return(object)
}


CellCycleScoring <-
    function (object, s.features, g2m.features, ctrl = NULL, set.ident = FALSE, ...) {
        name <- "Cell.Cycle"
        features <- list(S.Score = s.features, G2M.Score = g2m.features)
        cat("Collecting ctrl\n");
        if (is.null(x = ctrl)) {
            ctrl <- min(vapply(X = features, FUN = length, FUN.VALUE = numeric(length = 1)))
        }
        cat("Adding module score\n");
        object.cc <- AddModuleScore(object = object, features = features,
                                    name = name, ctrl = ctrl, ...)
        cat("Finding matching columns\n");
        cc.columns <- grep(pattern = name, x = colnames(x = object.cc[[]]),
                           value = TRUE)
        cc.scores <- object.cc[[cc.columns]]
        rm(object.cc)
        CheckGC()
        cat("Setting assignments\n");
        assignments <- apply(X = cc.scores, MARGIN = 1, FUN = function(scores,
                                                                       first = "S", second = "G2M", null = "G1") {
            if (all(scores < 0)) {
                return(null)
            }
            else {
                if (length(which(x = scores == max(scores))) > 1) {
                    return("Undecided")
                }
                else {
                    return(c(first, second)[which(x = scores == max(scores))])
                }
            }
        })
        cat("Merging scores\n");
        cc.scores <- merge(x = cc.scores, y = data.frame(assignments),
                           by = 0)
        colnames(x = cc.scores) <- c("rownames", "S.Score", "G2M.Score",
                                     "Phase")
        rownames(x = cc.scores) <- cc.scores$rownames
        cc.scores <- cc.scores[, c("S.Score", "G2M.Score", "Phase")]
        object[[colnames(x = cc.scores)]] <- cc.scores
        cat("Setting idents\n");
        if (set.ident) {
            object[["old.ident"]] <- Idents(object = object)
            Idents(object = object) <- "Phase"
        }
        return(object)
    };
```

Which produced the following output:

```
> pbmc.filtered <- CellCycleScoring(pbmc.filtered, s.features = s.genes, g2m.features = g2m.genes);                                                                                        
 Collecting ctrl
 Adding module score
 Data range: NA NA
 Cutting data of length 24446 into 24 bins
 Error in `cut_number()` at /tmp/SevenBridges_analysis.r!urUVjb:77:4:
 ! Insufficient data values to produce 24 bins.
 Run `rlang::last_error()` to see where the error occurred.
 Warning messages:
 1: In min(x) : no non-missing arguments to min; returning Inf
 2: In max(x) : no non-missing arguments to max; returning -Inf
```

So... I then noticed that Matrix::rowMeans wasn't omitting NA values when calculating means, and I considered adding that in, but then I realised that there was a more fundamental issue: my data included NA values.

It would have been great if Seurat had reported this earlier, rather than it becoming an obscure `! Insufficient data values to produce 24 bins.` error in some less-used code. It seems like there are a few Seurat functions that don't expect (and can't handle) NA values.

I had sort-of noticed this earlier when merging three datasets, producing NA values for all data in the `nCount_RNA` and `nFeature_RNA` metadata slots, but I thought it was something relating to the merge, rather than the data itself (and manually calculated these and added them back into the structure).

To make this less of a time-consuming and confusing error in the future, I recommend Seurat do one of the following (in decreasing order of effort):

* Change all the functions to be able to handle NA values in the data
* Convert NA values to 0 when creating a Seurat object, and report something like `NA values seen in input data; converting to 0`
* Detect NA values in the dataset provided to CreateSeuratObject, and stop with an error like `Error: data contains NA values`
