### ISSUE TITLE
Why split the combined object into a list for analysis #3592

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#3697]
Can you please explain the same in more detailed for the issue  #3592

**Comment by yuhanH** [comment]
SCTransform is used to eliminate the sequencing depth cofounding effects in the gene expression. 
In the `panc8`, it has scRNA data from many technologies. For different technologies, the relation between sequencing depth and gene expression are different, so we cannot model them all together by SCTransform. 

But when we split the object into a list, each element in the list represents only one technology, so we can apply SCTransform to it and get proper gene residuals.

If you feel that you want more detailed information, I can reopen the issue.

**Comment by bassanio** [comment]
@yuhanH : Thank you for the explanation. I have one more question of SCT with Seurat 4. If I am using the same pac8 dataset for the PBMC mapping using Seurat 4 how will I split the data and do SCT transform?

**Comment by yuhanH** [comment]
Hi, 
do you mean pbmcsca seurat data?
You can split the object by sequencing technologies. 
```
library(SeuratData)
pbmcsca
obj.list <- SplitObject(object = pbmcsca, split.by = "Method")

```

panc8 contains 8 Pancreas dataset. They should not be mapped to the pbmc reference.

**Comment by bassanio** [comment]
@yuhanH : I understand. I have multiple runs (4-5) from 10x with 16 pools each from different populations with 2 time series.The library preparation, sequencing was done on different days. and  So I need to combine them and remove the batch effects too. So I was thinking the same split method "BY SAMPLE" before mapping to pmbc. Idea  is to see cell population difference between population and during time series

**Comment by bassanio** [comment]
@yuhanH : Just adding to the above response. Currently I am running my above data like this for SCTransform i.e I have made one single object without splitting
```
pag.combined <- SCTransform(
  object = combined,
  assay = "RNA",
  method = 'glmGamPoi',
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
  do.scale = FALSE,
  do.center = TRUE
)
```
So what I understand is that I should change the same to like this.
```
combined.list <- SplitObject(combined, split.by = "SAMPLE")
pag_combined.list <- lapply(X = pag_combined.list, FUN = function(x) {
x <- SCTransform(
  object = x,
  assay = "RNA",
  method = 'glmGamPoi',
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
  do.scale = FALSE,
  do.center = TRUE
)
```
Can you also specify what other changes should I need to make for other downstream steps like 'FindTransferAnchors', MapQuery, AddMetaData as normally its Seurat object which we provide but now its a list of SCT I have

Appologies for a long and restless questions
