### ISSUE TITLE
Set range for color legend in SpatialFeaturePlot

### ISSUE THREAD

**Issue by nbpeterson3** [satijalab/seurat#3698]
Hello,

I would like to make the color scale equivalent across features when the max gene expression is different, similar to what was asked in [#1841](https://github.com/satijalab/seurat/issues/1841).  For example, Gene A has a range of 0-4, Gene B has a range of 0-2, and Gene C has a range of 0-1.  Currently, the spatial plots have the color red assigned to these different max expression values, so visually inspecting the plots is misleading.  I would like to force Genes B and C to use a scale of 0-4 so that all three genes have the same colors representing the same expression levels.

I do not believe the arguments 'min.cutoff' and 'max.cutoff' are sufficient here, because setting a max.cutoff of 4 does not affect the scale of Gene B or Gene C.  If you set a max.cutoff of 1, you lose the information of Gene A and Gene B (i.e., anything above 1 is displayed as red).

I tried to use the scale_color_gradientn function as suggested in #1841, but that didn't seem to work.  Suggestions or workarounds are greatly appreciated.

Thank you,
N

**Comment by andrewwbutler** [comment]
Hi,

You should be able to use `scale_fill_*` (e.g. `scale_fill_gradientn`, `scale_fill_manual`, etc...) to modify the colors in the `SpatialFeaturePlots` depending on what exactly you want to show.

**Comment by franciscogrisanti** [comment]
I'm also struggling with this, @andrewwbutler could you help me set up a working example?
`
SpatialFeaturePlot(object, 
                   features = c("Celltype_1_proportion"), 
                   pt.size.factor = 1.5,
                   ncol = 1)`

What should be the + ggplot2::scale_fill_gradientn() parameters to set up the scale bar from 0 to 1?

**Comment by franciscogrisanti** [comment]
Nevermind I managed to do it with 

`+ ggplot2::scale_fill_continuous(limits = c(0.0,1.0),, breaks = c(0.0, 0.5, 1.0))`

**Comment by ivingan01** [comment]
does anyone know how to make this work for a merged seuratobject? When i apply this fix, it only works on the last specimen plotted, the other samples in the same seurat object still hold their own color scale

**Comment by gucascau** [comment]
I also struggle with this. The scale can only work on the last specimen, any suggestion?

**Comment by gucascau** [comment]
It works. Thanks. however, I'm still struggling with this the color scale. 

 > & scale_fill_continuous(limits = c(0.0,1.0),, breaks = c(0.0, 0.5, 1.0)) # give a good scale way and all the figures scaled very well, but we can only set up two colors with high and low adjustments. 

Is there a further way to set up three colors or similar color combination in the SpatialFeaturePlot? I would be greatly appreciated if any one can help. Thanks

**Comment by chiwwong** [comment]
If there is a way to set the range while keeping the default color scheme? The color/ fill gone after setting `limits`

**Comment by boothbyi** [comment]
To maintain the Seurat color scheme with new limits:

`
# pulled from the Seurat source code--requires package RColorBrewer
SpatialColors <- colorRampPalette(colors = rev(x = brewer.pal(n = 11, name = "Spectral")))

SpatialFeaturePlot(object,  features = c("Celltype_1_proportion")) &
    scale_fill_gradientn(limits=c(0, 1), colours=SpatialColors(n=100))
`

**Comment by nina-hahn** [comment]
Dear all, 

I am facing a similar problem. It is possible to adjust the min and max limits as suggested earlier.  However, I aim to use a for loop to automatically create SpatialFeaturePlots for various features. Then, I can not manually set the min and max limits, since they differ between the features. Is there a workaround to solve this problem? Where do I find the maximum expression values of each gene in the seurat object? This would help to e.g. define the maximum scale fill limit to 80% of rthe respective feature expression. 

Best Nina
