### ISSUE TITLE
Installation issues with "invalid command line option"

### ISSUE THREAD

**Issue by ARChakravarthy** [satijalab/seurat#37]
Hi there, 

I just tried to install Seurat and the installation fails with the following error.

> * installing *source* package 'Seurat' ...
> ** libs
> 
> *** arch - i386
> g++ -m32 -std=c++0x -I"E:/R-3.2.2/include" -DNDEBUG    -I"E:/R-3.2.2/library/Rcpp/include" -I"E:/R-3.2.2/library/RcppEigen/include" -I"E:/R-3.2.2/library/RcppProgress/include" -I"d:/RCompile/r-compiling/local/local320/include"  -g -std=c++11 -Wall -pedantic   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
> cc1plus.exe: error: unrecognized command line option '-std=c++11'
> make: *** [RcppExports.o] Error 1
> Warning: running command 'make -f "Makevars" -f "E:/R-3.2.2/etc/i386/Makeconf" -f "E:/R-3.2.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="Seurat.dll" OBJECTS="RcppExports.o data_manipulation.o"' had status 2
> ERROR: compilation failed for package 'Seurat'
> * removing 'E:/R-3.2.2/library/Seurat'

Any pointers re: fixing this? 

Thank you.

**Comment by andrewwbutler** [comment]
It looks like you're using an older compiler. You're going to need one with c++11 support. The latest Rtools should come with one that works.

**Comment by IMEx35** [comment]
Hi guys, 

l am new to Seurat and l am trying to install it on a Windows PC (running windows 10 pro).

When l get to the stage when l have to install Seurat in R the following error keeps popping up. I have reinstalled everything at this point and still it hasnt worked. Is anyone able to assist?

> install_github("satijalab/seurat")
Error in install_github("satijalab/seurat") : 
  could not find function "install_github"
> library(Seurat)
Error in library(Seurat) : there is no package called ‘Seurat’

Thank you

**Comment by andrewwbutler** [comment]
Hi,

You need the devtools package for the `install_github` function. See the [installation page](http://satijalab.org/seurat/install.html#installation-on-windows) for Windows specific installation instructions.

**Comment by IMEx35** [comment]
Hi Andrew, 

I had installed the devtools package already as per instructions but it wasnt working. 
After a bit of snooping l found this link  https://github.com/satijalab/seurat/issues/40  and l am in the process of installing some packages with Bioconductor  from the code shown on this page 

https://bioconductor.org/biocLite.R


l am now getting the following message:

installation path not writeable, unable to update packages: boot, cluster, foreign, lattice, MASS, Matrix, mgcv, nlme, rpart, survival

Is there an alternative to individually installing these packages.

Thank you

**Comment by andrewwbutler** [comment]
Looks like a permissions issue. One solution would be to run R as "an administrator" and then try updating those packages.

**Comment by IMEx35** [comment]
Hey, Andrew l have changed the permissions but l am still getting the following error:

compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA1/R/R-341.1/etc/i386/Makeconf" -f "C:/PROGRA1/R/R-341.1/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="Seurat.dll" OBJECTS="RcppExports.o data_manipulation.o"' had status 2
ERROR: compilation failed for package 'Seurat'

removing '\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/Seurat'
Installation failed: Command failed (1)
Is there anyone with useful information on how l can get past this,

Thank you

**Comment by andrewwbutler** [comment]
Do you have the most recent version of Rtools installed?

**Comment by IMEx35** [comment]
Yes Andrew, the Rstudio is now aborting the session.

**Comment by IMEx35** [comment]
Yes Andrew, Rstudio is now aborting the session.

I am using Windows 10 pro on a Lenovo T460s

**Comment by IMEx35** [comment]
Good day Andrew, been running the installation for about 3 hours to this stage and then the following error is coming up. Rstudio did not terminate the session this time. Thank you 👍 


Installing 1 package: VGAM
Installing package into ‘\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.uni-muenster.de/bin/windows/contrib/3.4/VGAM_1.0-4.zip'
Content type 'application/zip' length 4619042 bytes (4.4 MB)
downloaded 4.4 MB

package ‘VGAM’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ian.mbano\AppData\Local\Temp\Rtmp29LoJC\downloaded_packages
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/ian.mbano/AppData/Local/Temp/Rtmp29LoJC/devtools33d0623875ec/satijalab-seurat-15b0c9a"  \
  --library="\\fs01/users/redirectedfolders/ian.mbano/My  \
  Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'Seurat' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/Rcpp/include" -I"\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/RcppEigen/include" -I"\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/RcppProgress/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -g -std=c++11 -Wall -pedantic   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:23: fatal error: RcppEigen.h: No such file or directory
 #include <RcppEigen.h>
                       ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="Seurat.dll" OBJECTS="RcppExports.o data_manipulation.o"' had status 2
ERROR: compilation failed for package 'Seurat'
* removing '\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/Seurat'
Installation failed: Command failed (1)
Error: invalid version specification ‘NA’
In addition: Warning message:
In utils:::packageDescription(packageName, fields = "Version") :

**Comment by andrewwbutler** [comment]
Sorry for all the hassle. Now it looks like you're missing RcppEigen. You should be able to install that with a normal `install.packages` command though.

**Comment by IMEx35** [comment]
Good day Andrew, l have proceeded to install RcppEigen using the function you stated, l tried to resume the Seurat installation and this is what l am getting both in R and Rstudio:

> install.packages("RcppEigen")
Installing package into ‘\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.uni-muenster.de/bin/windows/contrib/3.4/RcppEigen_0.3.3.3.0.zip'
Content type 'application/zip' length 2667478 bytes (2.5 MB)
downloaded 2.5 MB

package ‘RcppEigen’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\ian.mbano\AppData\Local\Temp\RtmpK056Tv\downloaded_packages
> install_github("satijalab/seurat")
Downloading GitHub repo satijalab/seurat@master
from URL https://api.github.com/repos/satijalab/seurat/zipball/master
Installing Seurat
Installing 1 package: dplyr
Installing package into ‘\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.uni-muenster.de/bin/windows/contrib/3.4/dplyr_0.7.2.zip'
Content type 'application/zip' length 2881437 bytes (2.7 MB)
downloaded 2.7 MB

package ‘dplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\ian.mbano\AppData\Local\Temp\RtmpK056Tv\downloaded_packages
"C:/PROGRA~1/R/R-34~1.1/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ian.mbano/AppData/Local/Temp/RtmpK056Tv/devtools1d802a571874/satijalab-seurat-15b0c9a" --library="\\fs01/users/redirectedfolders/ian.mbano/My  \
  Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'Seurat' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/Rcpp/include" -I"\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/RcppEigen/include" -I"\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/RcppProgress/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -g -std=c++11 -Wall -pedantic   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:23: fatal error: RcppEigen.h: No such file or directory
 #include <RcppEigen.h>
                       ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="Seurat.dll" OBJECTS="RcppExports.o data_manipulation.o"' had status 2
ERROR: compilation failed for package 'Seurat'
* removing '\\fs01/users/redirectedfolders/ian.mbano/My Documents/R/win-library/3.4/Seurat'
Installation failed: Command failed (1)
> library(Seurat)
Error in library(Seurat) : there is no package called ‘Seurat’
>
