### ISSUE TITLE
error with find cluster

### ISSUE THREAD

**Issue by ravdu02-liu** [satijalab/seurat#3700]
Error in samd9l.A1 - FindClusters(samd9l.A1) : 
  non-numeric argument to binary operator

I have four hashtag sample multiplex and sequenced together. I am subsetting each group and running clustering with it. for first two group it works well but last two group I get these error. could you please help me with this. thank you!

**Comment by timoast** [comment]
Can you provide the full code?

**Comment by ravdu02-liu** [comment]
I have four hashtag sample sequence in one lane (Hashtag, RNA and ADT, TotalseqA). I create a Seurat object first and subset data for each hashtag. RNA clustering went well for all of them but for two ADT it did not work. we have used 8 ADT antibody. 

here is the code:
proj.I4 <- SubsetData(prom, ident.use = "BP1011-I4-N(-)")
proj.I4

#Clustering on ADT
DefaultAssay(proj.I4) <- "ADT"
proj.I4 <-FindVariableFeatures(proj.I4, assay = "ADT", selection.method = "vst")
proj.I4 <- RunPCA(proj.I4, assay ="ADT", verbose = FALSE, nfeatures = 8)
proj.I4 <- JackStraw(proj.I4)
proj.I4 <- ScoreJackStraw(proj.I4, dims = 1:6)
JackStrawPlot(proj.I4, dims = 1:6)
ElbowPlot(proj.I4)
samd9l.I4 <- RunUMAP(proj.I4, reduction = "pca", assay = "ADT", dims = 1:6)

**Comment by timoast** [comment]
You need to normalize and scale the ADT data, and should set all ADTs as the variable features since there are only 8, rather than running FindVariableFeatures (which is designed for RNA data). See an example analysis here: https://satijalab.org/seurat/v3.2/multimodal_vignette.html

**Comment by ravdu02-liu** [comment]
I am still getting same error. it works with two hashtag data. but not with other two. could you please tell me which data set is used by **Findcluster**. I can check if there is non-numeric argument.
