### ISSUE TITLE
Why there are unexpected dots in seurat vlnplots when add geom_boxplot() behind?

### ISSUE THREAD

**Issue by zenghh1226** [satijalab/seurat#3703]
Why there are unexpected dots in Seurat vlnplots when I set pt.size=0 and add geom_boxplot? How can I remove them? Just like the third column in the picture below(I don't have my own plot at hand so I find similar pic online).
![80321531-c3c8c300-87eb-11ea-96bc-9f08201cceca](https://user-images.githubusercontent.com/67954435/98570700-ade5a000-22ee-11eb-8c7e-b4fbf544ed3c.png)

VlnPlot (object, feature="CD4",pt.size=0)+geom_boxplot(width=0.2, fill="white").

**Comment by kleurless** [comment]
Boxplots also sometimes show dots, they can be seen as outliers to your data "within the box". 

From what I can see from the plot, is that CPM is generally not expressed in identity 6 as the median (thick black line) is shown at 0. There are, however, some cells that do express CPM, they are seen as outliers, hence the black dots between expression of 1-3.
This is also the case in identity 0, the median expression is again 0, but the number of cells that do express CPM is larger.

**Comment by zenghh1226** [comment]
Thanks! The black blots are exactly outliers and when I set the outlier.alpha = 0 the black dots disappear.
