### ISSUE TITLE
subset spatial data

### ISSUE THREAD

**Issue by kkang7** [satijalab/seurat#3704]
Hi Seurat team,

I am having trouble with the subset function in spatial data analysis. I am going through the tutorial and the example is 

-------- copy and paste from the tutorial-----------------
 
\# now remove additional cells, use SpatialDimPlots to visualize what to remove
\# SpatialDimPlot(cortex,cells.highlight = WhichCells(cortex, expression = **image_imagerow** > 400 |
\# **image_imagecol** < 150))
cortex <- subset(cortex, **anterior1_imagerow** > 400 | **anterior1_imagecol** < 150, invert = TRUE)

------ end of copy -------------

My question is where the feature name **anterior1_imagerow** (and the **image_imagerow** in the line above) comes from? I know the image has features **imagerow** and **imagecol** but there is no **anterior1_imagerow** as I can tell.  
How is this feature name **anterior1_imagerow**  generated? 

Thank you!

Best,
Kai

**Comment by andrewwbutler** [comment]
Hi Kai,

The Seurat object in that tutorial has the `Image` object named as `anterior1`. You can verify this with `Images(cortex)`. This has the corresponding key `anterior1_` which is used in that subset function to subset the `imagerow` and `imagecol` features for the `anterior1` image. Basically, it's subsetting based on the `imagerow` and `imagecol` features you're seeing, just being explicit to ensuring it's pulling from the correct image.

**Comment by jefferyUstc** [comment]
Hi, for this question mentioned above, we can subset the seurat object via`imagerow` or `imagecol` by adding the prefix `anterior1 _`, however, how can i subset the  seurat object via`row` or `col`?  for example, i tried this, but i did not work.

```
cortex <- subset(brain, anterior1_row > 20, invert = FALSE)
```

**Comment by Yukaixu666** [comment]
I mean, if you want to identify the exact position, you have to understand what is meaning of the "anterior1_", that is the image_key, therefore, if you want to subset the part of image, you can change anterior1_ to your "image_key"_. 
<img width="503" alt="1721911581(1)" src="https://github.com/user-attachments/assets/90fe628b-eab1-4f0a-bc7b-2ca212a24b4a">

**Comment by jiw181** [comment]
I also have problem with subset function in the tutorial. The image is there, but run into a FetchData Error. Any suggestions? Thank you!

```
> cortex
An object of class Seurat 
48721 features across 1401 samples within 2 assays 
Active assay: SCT (17668 features, 3000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: Spatial
 2 dimensional reductions calculated: pca, umap
 1 spatial field of view present: anterior1
> Images(cortex)
[1] "anterior1"
> cortex <- subset(cortex, anterior1_imagerow > 400 | anterior1_imagecol < 150, invert = TRUE)
Error in `FetchData()`:
! None of the requested variables were found: 
Run `rlang::last_trace()` to see where the error occurred.
> 
```

**Comment by jiw181** [comment]
Here is what I got if I use the key "slice1_". What does it mean by "no longer fetchable"?
```
cortex <- subset(cortex, slice1_imagerow > 400 | slice1_imagecol < 150, invert = TRUE)
Error in `FetchData()`:
! Spatial coordinates are no longer fetchable with FetchData
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `FetchData()`:
! Spatial coordinates are no longer fetchable with FetchData
---
Backtrace:
    ▆
 1. ├─base::subset(...)
 2. └─SeuratObject:::subset.Seurat(...)
 3.   ├─SeuratObject::WhichCells(...)
 4.   └─SeuratObject:::WhichCells.Seurat(...)
 5.     ├─SeuratObject::FetchData(...)
 6.     └─SeuratObject:::FetchData.Seurat(...)
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
```

**Comment by InternetExplorerBoy** [comment]
> Here is what I got if I use the key "slice1_". What does it mean by "no longer fetchable"?
> 
> ```
> cortex <- subset(cortex, slice1_imagerow > 400 | slice1_imagecol < 150, invert = TRUE)
> Error in `FetchData()`:
> ! Spatial coordinates are no longer fetchable with FetchData
> Run `rlang::last_trace()` to see where the error occurred.
> > rlang::last_trace()
> <error/rlang_error>
> Error in `FetchData()`:
> ! Spatial coordinates are no longer fetchable with FetchData
> ---
> Backtrace:
>     ▆
>  1. ├─base::subset(...)
>  2. └─SeuratObject:::subset.Seurat(...)
>  3.   ├─SeuratObject::WhichCells(...)
>  4.   └─SeuratObject:::WhichCells.Seurat(...)
>  5.     ├─SeuratObject::FetchData(...)
>  6.     └─SeuratObject:::FetchData.Seurat(...)
> Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.
> ```

Hi @jiw181,

I got the same error message. Currently, I'm working with Visium data which have two sections on each capture area. In two samples, I need to remove the spots of one of the two sections, as they were cut at a different thickness by mistake. The simplest way I could think off, is subsetting the Seurat Object based on <image_key>_imagecol. From previous work, I can confirm that the way it is described in the vignette worked in Seurat v4.0.3. If FetchData is no longer able to fetch spatial coordinates in Seurat v5, there must be an alternative way for subsetting the data based on spatial coordinates. However, I haven't found a workaround yet. Have you found a solution for you yet? If so, I would be very grateful if you could post it here.

**Comment by PollyHung** [comment]
@InternetExplorerBoy 
Hi, don't know if you still need that function but this is how I did it 

```
## Subset out anatomical regions -----------------------------------------------
## add a step to append coordinates 
brain_coordinates <- data.frame(cells = brain@images$slice1$centroids@cells, 
                                spatial_coord_x = brain@images$slice1$centroids@coords[, 1], 
                                spatial_coord_y = brain@images$slice1$centroids@coords[, 2])
brain@meta.data$cells <- rownames(brain@meta.data)
brain@meta.data <- merge(brain@meta.data, brain_coordinates, by = "cells")
rownames(brain@meta.data) <- brain@meta.data$cells

## Subset cortex 
cortex <- subset(brain, idents = c(2, 6, 0, 7, 3)) # now this is not perfect as there are cells that we do not desire 

## Use Interactive Plotting to locate the coordinates you want to crop 
# SpatialDimPlot(cortex, crop = TRUE, label = TRUE, interactive = TRUE) 
cells <- cortex@meta.data %>% 
  dplyr::filter(spatial_coord_x < 7360 & spatial_coord_y > 3230) %>% 
  dplyr::filter(!(seurat_clusters == 3 & spatial_coord_y > 7700 & spatial_coord_x > 4730)) %>% 
  dplyr::filter(!(seurat_clusters == 2 & spatial_coord_y > 6000 & spatial_coord_x > 5000))

## Subset the cortex by cell id 
cortex <- subset(cortex, cells = cells$cells)
p9 <- SpatialDimPlot(cortex, crop = FALSE, label = TRUE, pt.size.factor = 2, label.size = 2)
p10 <- SpatialDimPlot(cortex, crop = TRUE, label = TRUE, pt.size.factor = 3, label.size = 2)
```
Essentially just add the spatial coordinates to the `meta.data` dataframe, and then do subset normally. However must be careful that the coordinate system is a little bit messed up (?) like in the diagram below column 1 of `brain@images$slice1$centroids@coords` which I assumed x-axis is actually on y-axis, and column 2 is real x-axis coordinates. But I guess if you just explore by interactive plotting `SpatialDimPlot(cortex, crop = TRUE, label = TRUE, interactive = TRUE)` you'd quickly know how it works. 

<img src="https://github.com/user-attachments/assets/0de829ee-4649-4816-a04a-a79ea89b1d8c" alt="Picture 1" width="400" />
