### ISSUE TITLE
Question about subseting Seurat object

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#3705]
Hello. I tried subsetting /removing clusters 7, 10, 14, and 16 and yet when I check it via table(), these are still there although they are zeroes. I would like to remove the clean like 7, 10, 14, and 16 will not be shown anymore.

FinalMelanomaData100 <- subset(FinalMelanomaData100, idents = c("Cluster 7", "Cluster 10", "Cluster 16", "Cluster 16"), invert = TRUE)

But, I want all the rows in meta.data associated with these clusters' cells all gone. How is this done? When I do UMAP, the supposedly gone labels still appear in the legend, but no cluster formed.

![image](https://user-images.githubusercontent.com/68268222/98652211-42471580-2376-11eb-8e06-90d7deb5dc46.png)

**Comment by kleurless** [comment]
Looks like your clusters aren't named "Cluster x". You have to use the correct names, try the following:

`finalobject <- subset(object, idents = c("7", "10", "14", "16"), invert = TRUE)`

**Comment by yuhanH** [comment]
@kleurless Thanks for your reply. I agree with your solution.
