### ISSUE TITLE
Customizing nFeature threshold based on QC metric plot

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#3706]
Hello. I am going to integrate two scRNA-seq datasets. Below is the QC metrics (dataset 1 above panel, dataset 2 below panel).

If I follow the standard subsetting of nFeatures <2500, I'm left with few hundreds number of cells out of thousands, which I am not sure if I did the right way for this dataset. 

**I wonder if I can have a custom nFeature threshold based on this QC plot? May I ask what should be the best nFeature_RNA cutoff and why?** 

To my untrained eye, I assume that most of the cells in dataset 1 are in nFeature ~ 3500-4000. And in dataset 2, most of the cells are in  nFeature ~5000-5500, although there are still lots of cells beyond. 

**Standard way of filtering low quality cells:**
TCS <- subset(TCS, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

![image](https://user-images.githubusercontent.com/68268222/98652435-93efa000-2376-11eb-90db-516c8ed4fa5c.png)

**Comment by samuel-marsh** [comment]
Hi,

There is no standard values for these thresholds.  They will vary depending on the cell types being analyzed, the sensitivity of the single cell technology used, sequencing depth, and other factors.  It is up to end user to select the thresholds for their own datasets.

Best,
Sam
