### ISSUE TITLE
Meaning of counts, data and scale.data slots in SCTransformed data

### ISSUE THREAD

**Issue by plijnzaad** [satijalab/seurat#3711]
It is my understanding that in SCTranformed data `scale.data` are the Pearson Residuals (as per the publication); `counts` are count-like data, back-transformed from the Negative Binomial model to median transcript count per cell. But what is the `data` slot then? Is it the the LogNormalized version of the `counts` slot? If that is true, I would expect 
`sum(exp(srat@assays$SCT@data[,i])-1)` to be the same number for each `_i_`, but that appears not to be the case.

**Comment by jaisonj708** [comment]
Yes, `data` always contains the log-normed version of `counts`. If you run `expm1` on the data slot and take row sums, it should be identical to the row sums of the counts. There might be some edge cases (eg if you have fractional counts) where this might not be exactly true. Feel free to send your object to seuratpackage@gmail.com if you are concerned about this
