### ISSUE TITLE
Annotating cell type with an integrated reference?

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#3713]
Hello,

I have ~20 samples from human cortex that I want to annotate, around 70000 cells total.  I found a reference from the Allen Brain Institute that uses the same protocol (10X) and same tissue (cortex) as my reference.  This reference also has a similar number of cells to my queries.  However, the reference comes from multiple samples.  When using this reference to annotate cell types, how do I avoid its batch effects?   I see a few solutions: 
1) I could separate the reference by sample and perform separate instances of `FindTransferAnchors()`.  Then I could look for consistency between cell type labels, and filter out cells with highly inconsistent labelling.  Perhaps I could take an average of each prediction.score. per cell type per cell.  
2) I could integrate the reference samples, and then perform `FindTransferAnchors()` using the integrated reference on my normalized query samples.  

I would like to know what you think would be the best approach for using a reference that comes from multiple samples, @timoast 

Thanks!

**Comment by jaisonj708** [comment]
Integration can improve your reference reduction and, as a result, anchor finding in `FindTransferAnchors`. Therefore we recommend integrating, though your consensus method would probably work too.
