### ISSUE TITLE
NAs in UMAP visualization

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#3714]
Hi ,
      I opened an old Seurat object and I see an ident level in the UMAP labeled as "NA" (see figure). I checked again in 
the object metadata, however there are no such cells.

`unique(bloodataset$seurat_clusters)
 [1] 0  7  14 2  6  9  1  13 12 3  4  16 5  8  17 11 10 15
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17`

`> sum(is.na(bloodataset$seurat_clusters))
[1] 0`

![image](https://user-images.githubusercontent.com/39677623/98880036-1e272980-2487-11eb-94a0-b64e508676ad.png)
![image (1)](https://user-images.githubusercontent.com/39677623/98880038-1f585680-2487-11eb-9fa5-d27998b530de.png)

I have not seen it before and I suspected something version-related? Is there something obvious that I am missing?

**Comment by jaisonj708** [comment]
By default, the `Idents` will be plotted, not a column from metadata. Try: `Idents(bloodataset) <- 'seurat_clusters'`
