### ISSUE TITLE
RNA vs SCT vs integrated assay

### ISSUE THREAD

**Issue by liron27** [satijalab/seurat#3715]
Hi,
I was hoping one can clarify the difference between RNA vs SCT vs integrated assay and when to use each. I have been using the following code to integarte samples and after that I would like to run non matrix factorization (NMF) on a specific cluster. Which assay should I use for the count matrix for NMF to use? (pmbc.integrated@assay$SCT@counts? pmbc.integrated@assay$RNA@counts? pmbc.integrated@assay$Integrated@counts

pbmc.list <- SplitObject(pbmcsca, split.by = "Method")
for (i in names(pbmc.list)) {
    pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], verbose = FALSE)
}
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features)
pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT", 
    anchor.features = pbmc.features)
pbmc.integrated <- IntegrateData(anchorset = pbmc.anchors, normalization.method = "SCT")

pbmc.integrated <- RunPCA(object = pbmc.integrated, verbose = FALSE)
pbmc.integrated <- RunUMAP(object = pbmc.integrated, dims = 1:30)

pbmc.integrated <- FindNeighbors(pbmc.integrated, reduction = "pca", dims = 1:30)
pbmc.integrated<- FindClusters(pbmc.integrated, resolution = 0.5)

specific.cluster<- which( pmbc.integrated$seurat_clusters == 1)
specific.cluster.count <- pmbc.integrated@assay$SCT@counts[,specific.cluster]

**Comment by jaisonj708** [comment]
If your method expects a counts matrix, I would use the raw counts in `RNA`. If it expects normalized datas, then use the `data` slot in `SCT`. You probably don't want to use the integrated data for NNMF since some values are slightly negative.

**Comment by zh-zhang1984** [comment]
Hi, everyone 
which package do you suggest to run the NMF? Is there a convinient way to seamlessly run the NMF from seurat object?

**Comment by ceesu** [comment]
Hello, I'm wondering should we still use the `data` slot to get the corrected normalized counts from SCT assay, even if we used `vars.to.regress` when running `SCTransform`?
