### ISSUE TITLE
running FindVariableFeatures after SCTransform()ing data yields different VariableFeatures

### ISSUE THREAD

**Issue by plijnzaad** [satijalab/seurat#3716]
After `SCTransform()`ing data, you get 3000 VariableFeatures 'for free', namely the top-3000 genes from `obj@assays$SCT@meta.features[,'sct.residual_variance']`. If you then run `FindVariableFeatures()` on this Seurat object you get a different set of features. I think this the wrong, or at least confusing and unspecified behaviour that will go unnoticed by many users. 

(I reported this as a documentation issue, see #3710, but I  can't change labels so I'm replacing it with this).

**Comment by andrewwbutler** [comment]
Hi,

Thanks for bringing this up. I agree that this could potentially be confusing for users that are used to the standard log normalization workflow and then switch to using `SCTransform`. We are working on implementing a formal definition for `Assay`s created via running `SCTransform` that should enable more clarity in this particular scenario. Essentially, currently we don't recommend running `FindVariableFeatures` on an `Assay` created with `SCTransform` but the plan is to redefine `FindVariableFeatures` for the new `SCTAssay` class to basically just pull N features from the `sct.residual_variance`, thus hopefully enabling consistent behavior and limiting the chances for unintentional misuse here.

**Comment by plijnzaad** [comment]
Thanks, that clarifies things. In case people find it useful, I use the code below in the mean time, it returns the exact same features as calling `VariableFeatures()` on a freshly `SCTransform`()ed object. Cheers, P.

```
SCTVariableFeatures <- function(obj, n=3000) {
  resid.var <- obj@assays$SCT@meta.features$sct.residual_variance
  names(resid.var)<- rownames(obj@assays$SCT@meta.features)
  names(sort(resid.var, decr=TRUE)[1:n])
}

VariableFeatures(srat) <- SCTVariableFeatures(srat, 3000) ## in case it was overwritten

```

**Comment by yuhanH** [comment]
Thanks. It is fixed in the released seurat v4
