### ISSUE TITLE
To do cell cycle regression should I run ScaleData on all genes or only HVGs?

### ISSUE THREAD

**Issue by weishwu** [satijalab/seurat#3717]
I have two questions regarding cell cycle regression:

1. Since the HVGs do not necessarily contain all cell cycler marker genes, there seems to be two approaches by my search:
(1). Combine the HVGs and the cell cycle genes and use this list as the "feature" in IntegrateData().
(2). Use all genes as the "feature" in IntegrateData().
I guess it does not matter to use either way but I'd like to confirm.

2. After running CellCycleScoring(), run ScaleData() to regress out cell cycle heterogeneity. At this step, should I set "feature" to be all genes or HVGs? 

Thanks.

**Comment by jaisonj708** [comment]
1) Either would probably be fine. The most important/variable cell cycle genes should be in your HVGs anyways.
2) Set `features` to whatever you would like to use for your downstream analysis. I would recommend HVGs rather than the full feature set.
