### ISSUE TITLE
label transfer from clusters with uneven cell numbers

### ISSUE THREAD

**Issue by bsierieb1** [satijalab/seurat#3718]
Hi,

I am transferring labels between two data sets from different species. The reference contains some large (~1,000 cells) and some small (~100 cells) clusters. After label transfer, there is not a single query cluster that is predominantly assigned a label of a small reference clusters. Instead, all query clusters, regardless of their size, are assigned labels of large reference clusters.

Is this the result of uneven representation of cell types in the reference? Could you recommend any strategy to deal with this?

Thanks!

**Comment by timoast** [comment]
It sounds like this would depend a lot on the clustering resolution in the query dataset. You could instead just look at the predicted.id for each cell in the query, regardless of the cluster identities
