### ISSUE TITLE
SCTransform error on one dataset: Error in h(simpleError(msg, call)) :

### ISSUE THREAD

**Issue by rrchai** [satijalab/seurat#3720]
I have three datasets from one patient but three conditions. `SCTransform` will go through the first two data, but not work for a third data. 
```
a <- CreateSeuratObject(counts = Read10X(data.path), 
                     project = a, min.cells = 3, min.features =200) 
a <- PercentageFeatureSet(a, pattern = "^MT-", col.name = "percent.mt")  
a <- subset(a, subset = nFeature_RNA > min.feature.rna & nFeature_RNA < max.feature.rna & percent.mt < pct.mito)  
a <- SCTransform(a, vars.to.regress = "percent.mt", verbose = FALSE)
```
Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 17425 by 3869
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 3869 cells
  |=================================================================== |  50%

Error message:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

Three datasets were used the same code to create the seurat object. I tried both v.4 and v.3 `Seurat` and the same error appeared.

Thank you for help.

**Comment by jaisonj708** [comment]
This error can be resolved by using the `develop` branch of [sctransform](https://github.com/ChristophH/sctransform/tree/develop)

**Comment by rrchai** [comment]
> This error can be resolved by using the `develop` branch of [sctransform](https://github.com/ChristophH/sctransform/tree/develop)

Thanks for reply. I notice this answer, too. However, I was not able to install the `develp` branch:

```
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sctransform.so] Error 1
ERROR: compilation failed for package ‘sctransform’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sctransform’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sctransform’
Error: Failed to install 'sctransform' from GitHub:
  (converted from warning) installation of package ‘/var/folders/l6/2lxkc2wx4_j6w9n9y1ryfh_m0000gn/T//RtmpFmdZLl/file8692ba7284f/sctransform_0.3.1.9002.tar.gz’ had non-zero exit status
```

**Comment by jaisonj708** [comment]
You can try cloning the sctransform repo, switching to the develop branch, and then running `devtools::load_all(<path to repo>)`

**Comment by jaisonj708** [comment]
Or see #3663

**Comment by rrchai** [comment]
> Or see #3663

Thank you for the reply, the error message above is from using `remotes::install_github("ChristophH/sctransform@develop")`. 

I tried the way you suggest, but not working.

`git clone https://github.com/ChristophH/sctransform.git; cd sctransform`
`git checkout develop`
`R -e devtools::load_all("./sctransform")`
```
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c utils.cpp -o utils.o
E> clang++ 
[...]
```

**Comment by rrchai** [comment]
> > Or see #3663
> 
> Thank you for the reply, the error message above is from using `remotes::install_github("ChristophH/sctransform@develop")`.
> 
> I tried the way you suggest, but not working.
> 
> `git clone https://github.com/ChristophH/sctransform.git; cd sctransform`
> `git checkout develop`
> `R -e devtools::load_all("./sctransform")`
> 
> ```
> Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
>   System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
> E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
> E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -UNDEBUG -Wall -pedantic -g -O0 -fdiagnostics-color=always -c utils.cpp -o utils.o
> E> clang++ 
> [...]
> ```

The issue can't be solved by:

- downgrade sctransform to **v. 0.3**. `install.packages("https://cran.r-project.org/src/contrib/Archive/sctransform/sctransform_0.3.tar.gz", repos=NULL, type="source")`
- **Plus**, downgrade the `seurat` to `v3`, since `v4` requires `sctransform` >= 3.1.

After downgrading packages, the SCTransform will not produce the same error and work fine. However, I do not know the difference between `v3` and `v3.1`.  Hope others can answer this in the future~
