### ISSUE TITLE
Skipped Exon Analysis

### ISSUE THREAD

**Issue by vitamindlab** [satijalab/seurat#3721]
Has anyone attempted to utilize the SICILIAN or SZS pipelines recently published on BioRxiv for skipped exon annotation of 10x Gemonics datasets. I am wondering if these tool are compatible with Seurat?

Thanks!

Here are the Githbub repository for each:
https://github.com/juliaolivieri/SZS_pipeline/
https://github.com/salzmanlab/SICILIAN

**Comment by satijalab** [comment]
We have not - but would encourage the authors, if interested, to submit a pull request to Seurat Wrappers demonstrating how to use their tool on a Seurat object
