### ISSUE TITLE
How to access the plotted matrix including the order of cells/genes from DoHeatmap

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#3723]
Hello All,

I'm sure this is very simple, but I'm kind of stumped after looking at the output object of the DoHeatmap function.  I just want to extract the exact matrix, as plotted by DoHeatmap.  How can I do that?

Thanks a lot for any answers!

**Comment by andrewwbutler** [comment]
Hi,

`DoHeatmap` plots values stored in the `scale.data` slot of the object which can be accessed with `GetAssayData(object, assay = assay, slot = "scale.data")`. You could also pull the values from the ggplot object itself if you want.

```R
p <- DoHeatmap(object, features = features)
p$data
```
