### ISSUE TITLE
Inconsistency between violin plot and average expression results

### ISSUE THREAD

**Issue by vlink** [satijalab/seurat#3724]
Dear community,

First, I would like to thank the Seurat developer for developing such an amazing tool for scRNA-seq analysis!

I recently encountered some strange results in my analysis and wanted to get some input from you if this is a bug or another issue?

I ran single cell RNA-seq with HTO hashtags in two different lanes (same treatments, but different mice per lane) and used SCTransform to merge them. 
Here is my pipeline:
 * SCTransform
 * SelectIntegrationFeatures
 * PrepSCTIntegration
 * FindIntegrationAnchors
 * IntegrateData
 * RunPCA
 * FindNeighbors
 * FindClusters
 * RunUMAP

Now I want to look at average expression of genes that were significantly different between clusters to create heat maps etc.

When I run AverageExpression on a Seurat object selected for a cluster, I get strange expression results: 
 > avg_exp <- AverageExpression(cluster4, features = c("Areg"), add.ident = "replicates")
> avg_exp$RNA:
rep1: 0.8124837
rep2: 0.2247828
rep3: 108369.9
rep4: 0.6141012

But as you can see on the attached violin plot, rep3 does not have much more expression of this gene than the other replicates. The results don't change when I log normalize them, however it seems to make more sense when looking at the SCT data, although I was under the impression that this data is normalized and should not be used for calculation of average expression.

<img width="682" alt="Areg_violon_plot" src="https://user-images.githubusercontent.com/4139496/99154596-0ca87200-267f-11eb-8a2b-ed5fa07b9ee9.png">

>avg_exp$SCT:
rep1: 0.296875
rep2: 0.08474576
rep3: 0.2804878
rep4: 0.3125

I am running this code on a MacBook Pro with Mojave (10.14.6). I attach the output from sessionInfo() and uploaded my Seurat object to my google drive (https://drive.google.com/file/d/1nSm67iKAi7RT4IdafIqSoET1k1ncVNKL/view?usp=sharing)

Thanks, 

Verena

[sessionInfo.txt](https://github.com/satijalab/seurat/files/5541274/sessionInfo.txt)

**Comment by andrewwbutler** [comment]
Hi,

When you run `AverageExpression` on the RNA assay here, it is averaging based on the `data` slot, assuming the data has been log normalized. This does not appear to be the case with the data object posted here. If you normalize the data with `NormalizeData(object, assay = "RNA")` prior to running `AverageExpression`, the values should look more reasonable.
