### ISSUE TITLE
Why FindAllMakers outputs more genes than @data total genes?

### ISSUE THREAD

**Issue by rrchai** [satijalab/seurat#3725]
Hi,

I am just trying to understand the `FindAllMarkers`, so I ran it on the integrated data and default assay is 'integrated'. (I know I should run the 'RNA/SCT' assay)
``` 
markers <- FindAllMarkers(integ.object, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
nrow(markers)
# The total makers I got is more than 6k. 
```

I think the `FindAllMarkers` will just use 'data/count' . However, I found that total genes of the 'integrated@data' are only 3000, which makes sense because we set 3000 features. 

```
integ.object@assays$integrated@data %>% nrow 
# 3000
```
Also, I found there are ~3K genes are not in the 'RNA's data. The total RNA's data has 20k genes. I am pretty confused how `FindAllMarker/FindMarker` work and why it will output the genes are not in the 'data' assay?
```
length(setdiff(rownames(markers), rownames(integ.object@assays$RNA@data)))
# ~3k not even in the RNA@data
```

Anyone knows the reason of this? It might be a naive question. Thank you for the help.

**Comment by jaisonj708** [comment]
FindAllMarkers uses the data slot by default, but tests each of your cell types / idents, so number of rows in the output > total number of genes. Furthermore, if there is a feature that is differentially expressed in 2+ idents, FindAllMarkers will append ".1", ".2" etc to the rownames such that they are unique. That is why you are seeing a large `setdiff`set.

**Comment by rrchai** [comment]
> FindAllMarkers uses the data slot by default, but tests each of your cell types / idents, so number of rows in the output > total number of genes. Furthermore, if there is a feature that is differentially expressed in 2+ idents, FindAllMarkers will append ".1", ".2" etc to the rownames such that they are unique. That is why you are seeing a large `setdiff`set.

Thanks for the explanation!
