### ISSUE TITLE
DoHeatMap error

### ISSUE THREAD

**Issue by merriman0931** [satijalab/seurat#3727]
> top5 <- Data_XXX %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
Error in UseMethod("group_by_") : 
  no applicable method for 'group_by_' applied to an object of class "Seurat"

Running into this issue with generating heat maps since update. Any help would be appreciated.

**Comment by liuxl18-hku** [comment]
It would also be helpful to show your `sessionInfo()`.

From `group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)` of your code, I assume you are trying to get top DE genes from `Seurat::FindAllMarkers()` output, which, base on the [latest piece of code](https://github.com/satijalab/seurat/blob/c23845d26f7b1b3fd038e661f8d144ea1d4c81e0/R/differential_expression.R#L146), should be a basic `data.frame`, not a complex `Seurat` object. It would also be helpful to double-check the type of `Data_XXX` by `class(Data_XXX)`

**Comment by mojaveazure** [comment]
Can you provide the code leading up to the error, along with your `sessionInfo()` as suggested by Xingliang? Seurat doesn't use the function `group_by_` anywhere in its codebase, so I'm not sure if this is something we can fix without more context.
