### ISSUE TITLE
Demultiplexing 

### ISSUE THREAD

**Issue by rh707** [satijalab/seurat#3728]
I am trying to demultiplex my data following the "Demultiplex cell hashing data" vignette. The output files from cell ranger are: barcodes.tsv, features.tsv and matrix.tsv. 

In the first step of the vignette where the UMI matrix and hashtag count matrix are loaded in, I am unsure which of my files are equivalent and how to load them in as they are not in RDS format. 

Thanks!

Rob

**Comment by yuhanH** [comment]
You can use `Read10X` to load your cell ranger output. 
```
input_file <- Read10X(dir)
```
