### ISSUE TITLE
FindAllMarkers not working on reformatted sce object

### ISSUE THREAD

**Issue by nasjr08** [satijalab/seurat#3729]
Hello,

I recently created a Seurat object from an SingleCellExperiment object using the as.Seurat() function. this object contains the relevant TSNE, normalised counts etc. In the cell metadata (column data), I have a column called 'label' with the clusters that each cell belonged to (assigned prior to reformatting).  I was curious to see if I can use the Seurat::Findmarkers function to derive markers using previously assigned cluster of cells. 

When I use Findmarkers using the following code: 
cluster12.markers <- FindMarkers(seurat.sc, ident.1 = 'c12', min.pct = 0.25, group.by = 'label')
It works perfectly fine.

When I use FindAllMarkers using the following code:
FindAllMarkers(seurat.sc, min.pct = 0.25, logfc.threshold = 0.25,group.by = 'label')

I get an error: 
Calculating cluster SingleCellExperiment
No DE genes identifiedThe following tests were not performed: When testing SingleCellExperiment versus all:
	Cannot find the following identities in the object: SingleCellExperiment

I understand that it is likely that the function does not know what to group cells by, but my questions are:
1. Is there an arugment in the FindAllMarkers function that allows me to define the 'label' column as the reference cell grouping.
2. is it even possible to use this function on a pre-defined column?
3. if not, how is it possible for FindMarkers to work and not FindAllMarkers

Cheers,

Naseer Basma

**Comment by bioguy2018** [comment]
Hello,
I am having similar question so I am wondering if you ever found a solution?

**Comment by nasjr08** [comment]
Hey,
So I have not worked extensively using Seurat since, but at the time I played around with it, and I think I figured it out.
Obviously when you change sce to seurat, the identities are not saved. you need to therefore provide the identities to the seurat object using the idents() function. So what I would do is save the column corresponding to the cluster labels (I assume it can be anything though like cell identities) as the idents(seurat.sc):

seurat.sc <- as.Seurat(sce)
tmpIdent <- seurat.sc$Cluster
ident(seurat.sc) <- tmpIdent

Give a go and see if it works for you. I believe this then worked for the findallmarkers function. Note that when you convert seurat object to sce, it adds  a new column to the metadata called 'idents'  containing this information.
