### ISSUE TITLE
Error in RPCA workflow to integrate data

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#3730]
Dear all,

I am following exactly the commands in the vignette for reciprocal PCA from https://satijalab.org/seurat/v3.2/integration.html.
I have a list with 13 samples (ca. 130k cells). However, after:
anchors <- FindIntegrationAnchors(object.list = sample.list, reference = c(4, 11), reduction = "rpca", 
                                  dims = 1:30)

I am always getting this error:
Computing 2000 integration features
Scaling features for provided objects
Computing within dataset neighborhoods
Finding anchors between all query and reference datasets
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds
Calls: FindIntegrationAnchors ... my.lapply -> lapply -> FUN -> t -> .handleSimpleError -> h
Execution halted

What is the problem?? Sorry, also did not find anything by googling it. Best, Chris

**Comment by andrewwbutler** [comment]
Hi Chris,

I'm not sure from this what the problem is. Are you able to share an example that we could run to reproduce the issue?

**Comment by vertesy** [comment]
I got the same error:

```r
tic(); anchors <- FindIntegrationAnchors(object.list = ls.Seurat, dims = 1:50, reduction = "rpca"); toc(); say();
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=05s
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
```
