### ISSUE TITLE
Does Load10X_Spatial allow data from more samples/replicates?

### ISSUE THREAD

**Issue by elimereu** [satijalab/seurat#3732]
Dear Seurat community, 

thanks for all your work! I'm writing here because I'm trying to apply the function Load10X_Spatial with data coming from different replicates. I saw in the function help, the input data.dir can be used to load a directory path or a vector to load several data directories. However, this last option seems don't work. 
Please, see my code in the attached screenshot.
<img width="680" alt="Schermata 2020-11-16 alle 19 27 55" src="https://user-images.githubusercontent.com/20638667/99292966-41b0f200-2842-11eb-9008-66944152d842.png">

**Comment by mojaveazure** [comment]
Hi Elisabetta,

This is an error in the documentation; `Load10X_Spatial` can only take one `data.dir`, not a vector. We will update the documentation accordingly; thanks for catching this!

**Comment by mojaveazure** [comment]
The documentation has been updated in the latest development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by royfrancis** [comment]
For those are here lost as I was, I used the following in place of the above code for spatial data and it seems to work.

```
s1 <- Load10X_Spatial("data/raw/P19002_2345/outs/",slice="s1")
s2 <- Load10X_Spatial("data/raw/P19002_2365/outs/",slice="s2")
s1$orig.ident <- "s1"
s2$orig.ident <- "s2"
ss <- merge(s1,s2)
Idents(ss) <- ss$orig.ident
```
