### ISSUE TITLE
How to restrict CPU usage in FindAllMarkers

### ISSUE THREAD

**Issue by genecell** [satijalab/seurat#3735]
Dear Seurat team,

When I run FindAllMarker function, sometimes this function will use all available CPUs in my server, could you please give me some advices on how to restrict the CPU usage in FindAllMarkers function, thank you!

Best regards,
MD

**Comment by andrewwbutler** [comment]
Hi,

Do you have some sort of `future` plan (other than sequential) enabled when this happens?

**Comment by genecell** [comment]
> Hi,
> 
> Do you have some sort of `future` plan (other than sequential) enabled when this happens?

Hi,

Thank you for your rapid reply!
I did not use `future` plan, I run MAST, Wilcoxon, roc, Poisson, and negbinom at the same time, and I need to check whether the CPU usage problem arises from MAST or not. I heard from others that MAST may have this problem.

**Comment by timoast** [comment]
This is a MAST issue, rather than Seurat. See https://github.com/RGLab/MAST/issues/136

**Comment by genecell** [comment]
> This is a MAST issue, rather than Seurat. See [RGLab/MAST#136](https://github.com/RGLab/MAST/issues/136)

Got it! Thank you!

**Comment by xf78** [comment]
I've tried setting `options("mc.cores"=4)` to limit the CPU utilization of FindAllMarker in ATAC project , but it doesn't work, referring to the relevant reply https://github.com/HenrikBengtsson/future/issues/343 of the future package, set the following environment variable in ~/.bashrc, it worked for me.

```
#### Here try to set the number of threads to 4 for all acceleration underlying frameworks
export OPENBLAS_NUM_THREADS=4
export OMP_NUM_THREADS=4
export NUM_THREADS=4
export MKL_NUM_THREADS=4
```
