### ISSUE TITLE
Questions about Visualization of 2-genes combination or more when doing the DE analysis

### ISSUE THREAD

**Issue by lovebaboon1989** [satijalab/seurat#3736]
Hi there,
I am now doing the DE analysis on RGC scRNA dataset, and after performing the 'FindMarker' function, I'd like to see whether a 2-marker combination or 3-marker combination shall show a clear difference between my interested cluster and the others, in a 'DotPlot' function.
Could you please tell me is there any parameter in the 'DotPlot' function that enables me to choose a combination of 2 markers (a+b+) as one single dot? Because in my dataset, one single marker may not distinguish one cluster from the others quite well.
Another further question is, if we can do a 2-marker combination in the 'DotPlot' function, that is marker a+b+, can we do this combination: a+b-?
Many thanks and looking forward to your kind reply. The ideal dotplot figure is shown as folows, adapted from one paper.
![1605593637(1)](https://user-images.githubusercontent.com/58609479/99353334-41c8e600-2872-11eb-9c32-1d35b017a784.png)

Best,
Weiqian

**Comment by jaisonj708** [comment]
We do not enable this specific functionality, but you can add these combinations to your metadata, and then pass the metadata column names to `features` in `DotPlot`

**Comment by lovebaboon1989** [comment]
> We do not enable this specific functionality, but you can add these combinations to your metadata, and then pass the metadata column names to `features` in `DotPlot`



> We do not enable this specific functionality, but you can add these combinations to your metadata, and then pass the metadata column names to `features` in `DotPlot`

Hi, thanks for the reply, I would try it.
