### ISSUE TITLE
aligne multiple datasets? 

### ISSUE THREAD

**Issue by annecar** [satijalab/seurat#374]
Hi, 
in your paper, you mention that "Multiple datasets can be easily aligned if they can be split into two overall groups, and future extensions using multiple CCA[1, 2] will enable arbitrary numbers of datasets to be aligned." Is this extension already available? 
I have been aligning multiple datasets by aligning one after the other; nevertheless, I end up with a huge Seurat object. Is this at all an option? Or do you see a problem in doing this? 
Thanks 
annecar

**Comment by leonfodoulian** [comment]
Hi,

Yes, it is implemented by Seurat's `RunMultiCCA()` function. You can find more details, and a tutorial of how this works, in the last two sentences of the first paragraph on [this page](http://satijalab.org/seurat/immune_alignment.html).

Best,
Leon

**Comment by annecar** [comment]
Greatm tahnsk a lot! This is very helpful. I will stry it asap. 

annular




CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by annecar** [comment]
Hi Leon 
i am trying to run your script for alignement, evrything works, but i get an error when executing 

cl1.markers <- FindConservedMarkers(Pat1_5, ident.1 = 1, grouping.var = "batch",
+                                     print.bar = FALSE)



Fehler in FindConservedMarkers(Pat1_5, ident.1 = 1, grouping.var = "batch",  : 
  Please install MetaDE (note Bioconductor dependencies) - learn more at https://cran.r-project.org/web/packages/MetaDE/index.html

When going to CRAN there is a notice that MetaDE is no longer availble. 
And by the way, can i use any variable for grouping that i have stored in meta.data or do i need to SetAllIdentities to the variable required before?

Tanks a lot! 
Anne

CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by mojaveazure** [comment]
@annecar Please see #316 for details about MetaDE and its replacement, metap.

**Comment by annecar** [comment]
HI 
i have installed "metap" AND updated Seurat to 2.2.1. 
This does not help, i am still getting the error 

Please install MetaDE (note Bioconductor dependencies) - learn more at https://cran.r-project.org/web/packages/MetaDE/index.html

what else can i try? 

Thanks….

CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by annecar** [comment]
solution found! 




CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de
