### ISSUE TITLE
does AddModuleScore work on LogNormalized or SCTransformed data?

### ISSUE THREAD

**Issue by plijnzaad** [satijalab/seurat#3742]
does `AddModuleScore()` work on `RNA`  or `SCT` assay data? My hunch is that it uses the `RNA` assay, but I think  I would prefer it to use `SCT` data, because the latter is properly variance-stabilized.

**Comment by shahrozeabbas** [comment]
You can specify the assay in the function call per the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/AddModuleScore), but I think by default it requires the user to specify something because it's set to `NULL`.

**Comment by jaisonj708** [comment]
The user's answer is correct - you can specify the `SCT` assay as a parameter

**Comment by fahmadimoughari** [comment]
Hi,

Sorry to reopen this issue. What is the preferred (or more correct) assay to be used for AddModuleScore function? SCT or RNA?
