### ISSUE TITLE
Availability of new CITE-seq reference dataset with log normalization?

### ISSUE THREAD

**Issue by deborah-chasman** [satijalab/seurat#3743]
Hello!

I'm excited to try mapping one of my datasets to your new CITE-seq PBMC reference dataset. However, my dataset is all T cells, and Azimuth is unable to map it. I think this is because applying SCT normalization to my T-cell-only dataset removes the variation that distinguishes T cells from other cell types, which makes them look quite different from the reference T cells.

Is there a raw or log-normalized version of the new reference dataset available? Or would you be able to recommend a different strategy? 

I wonder if I could subset the T cells from the SCT-reference, re-scale them, and then rebuild the WNN - and then try mapping my dataset to it.

Thanks for your time and for sharing this great resource with us.

**Comment by jaisonj708** [comment]
Azimuth likely fails on your T cell dataset because of an insufficient "pseudobulk score", which assesses the similarity of your dataset to our PBMC multimodal reference. You can manually download our reference, optionally subset the T cells, and map onto your query, instead of using the app.
