### ISSUE TITLE
Errors on FindTransferAnchors

### ISSUE THREAD

**Issue by caiquanyou** [satijalab/seurat#3744]
When running the FindTransferAnchors Function and get the error below：（data had normalized and scaled and run the FindVariableFeatures）
Error：
> anchors <- FindTransferAnchors(reference = E135_Visium, reduction = 'cca',query = E135_sc80)
Running CCA
Merging objects

Error in RowMergeMatricesList(mat_list = all.mat, mat_rownames = all.rownames,  (Seurat_script.R#25): std::bad_alloc
Show stack trace

**Comment by caiquanyou** [comment]
memory issue， solved

**Comment by abartlett004** [comment]
How did you solve it? I am getting the same error but with the IntegrateData function. Weirdly, only about 50% of my RAM is in use when it crashes.

**Comment by hk20013106** [comment]
> memory issue， solved

This is very important information and help me solve the problem too.

**Comment by ConDem94** [comment]
How did you solve this issue? I am trying to merge multiple Seurat objects but getting the same error

RowMergeMatricesList std::bad_alloc

Is there a way to fix this error?
