### ISSUE TITLE
Error: Problem with `filter()` input `..1`.

### ISSUE THREAD

**Issue by Qtasnim** [satijalab/seurat#3745]
Hello seurat community... 

I am currently running seurat package in Rstudio and I'm using pbmc3k dataset. 

- Seurat objects setup went like this: 

```
> library(Seurat)
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union
> 
> library(cowplot)

```

- Everything after went smoothly until trying to find markers for every cluster compared to all remaining cells: 

```
>pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
>pbmc.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)
```

To which I get an error after calculating the clusters that says: 

```
Error: Problem with `filter()` input `..1`.
x object 'avg_logFC' not found
i Input `..1` is `top_n_rank(2, avg_logFC)`.
i The error occurred in group 1: cluster = "0".
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'avg_logFC' not found
i Input `..1` is `top_n_rank(2, avg_logFC)`.
i The error occurred in group 1: cluster = "0".
Backtrace:
  1. dplyr::group_by(., cluster)
  2. dplyr::top_n(., n = 2, wt = avg_logFC)
 21. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.
```

What seems to be the problem? 
I tried to setup library(dplyr) again if the filter function is masked but the same error appears. 

Thank you very much in advance..

**Comment by shahrozeabbas** [comment]
Just at a quick glance, seems like you haven't defined `avg_logFC` before supplying it to the `wt` parameter in `top_n`. [Documentation](https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/top_n) says that that parameter is optional, so you could try to run that line without specifying `wt` and see if it works.

**Comment by Qtasnim** [comment]
@shahrozeabbas  Thank you for your prompt reply....

I think wt is defined in top_n() function by default, but I did try without wt and unfortunately still didn't work 

`pbmc.markers %>% group_by(cluster) %>% top_n(2, avg_logFC)`

I do think filter() function is ok because %>% object is recognized! 

Is there anything else I can try?

Thank you very much in advanced.

**Comment by shahrozeabbas** [comment]
What I meant to say was that `avg_logFC` does not seem to be defined anywhere and you are supplying it to `wt` so it might not be able to recognize `avg_logFC`. What you can try is this below:

`pbmc.markers %>% group_by(cluster) %>% top_n(2)`

**Comment by Qtasnim** [comment]
@shahrozeabbas Thank you for your reply...

It did work!!! Thank you very very very much!!
And I did try something else that just worked, apparantely `avg_log2FC` is defined in the function but not `avg_logFC`. 

Again, thanks a lot. 

I will close the issue now :)
