### ISSUE TITLE
as.Seurat() from SCE requires both counts and logcounts to be defined (why logcounts?)

### ISSUE THREAD

**Issue by ZacharyDeBruine** [satijalab/seurat#3746]
Here's a reproducible example:

```
library(scRNAseq)
sce <- LaMannoBrainData("mouse-embryo")
seurat <- as.Seurat(sce)
# Error: No data in provided assay - logcounts
```
Seurat doesn't accept the sce object without a `logcounts` in the assay slot. 

So let's calculate `logcounts` and add it to the assay slot.

```
counts <- assay(sce, "counts")
libsizes <- colSums(counts)
size.factors <- libsizes/mean(libsizes)
logcounts(sce) <- log2(t(t(counts)/size.factors) + 1)
seurat <- as.Seurat(sce)
seurat
# An object of class Seurat 
# 24377 features across 1907 samples within 1 assay 
# Active assay: RNA (24377 features, 0 variable features)
```
That works!

But if we don't want to run logcounts (i.e. I want to run Seurat SCTransform instead), we can trick Seurat into accepting an sce object where the logcounts slot is the counts slot:

```
library(scRNAseq)
sce <- LaMannoBrainData("mouse-embryo")
logcounts(sce) <- assay(sce, "counts")
seurat <- as.Seurat(sce)
seurat
# An object of class Seurat 
# 24377 features across 1907 samples within 1 assay 
# Active assay: RNA (24377 features, 0 variable features)
```

That's my workaround, but I shouldn't have to do that.  There should be a check in the as.Seurat() function for logcounts, and if it exists then logcounts should be incorporated into the converted Seurat object.

I note that when `logcounts == counts`, Seurat seems to be smart and leave out logcounts in the converted object. This is a bit wierd. So there is an explicit check in the function for `logcounts == counts` but no explicit option to not include `logcounts` in as.Seurat?

**Comment by satijalab** [comment]
Thanks - you can overcome this by passing data = NULL into the as.Seurat call. This is described in the docs, but we should also pass a warning that describes how to fix the problem and will update

**Comment by wfma** [comment]
came here via google because of the same issue. 

for newbies like me in the future, this worked perfectly for me:

```
seurat.obj <- as.Seurat(sce, data = NULL)
```

**Comment by Christ14n97** [comment]
I don't know why `as.Seurat` does not work for me. I got the message:

Error in UseMethod(generic = "as.sparse", object = x) :
no applicable method for 'as.sparse' applied to an object of class "c('DelayedMatrix', 'DelayedArray', 'DelayedUnaryIsoOp', 'DelayedUnaryOp', 'DelayedOp', 'Array', 'RectangularData')"

**Comment by Grace1206** [comment]
> I don't know why `as.Seurat` does not work for me. I got the message:
> 
> Error in UseMethod(generic = "as.sparse", object = x) : no applicable method for 'as.sparse' applied to an object of class "c('DelayedMatrix', 'DelayedArray', 'DelayedUnaryIsoOp', 'DelayedUnaryOp', 'DelayedOp', 'Array', 'RectangularData')"

I met the same question, have you already solved that questioin?

**Comment by pengli-arg** [comment]
> > I don't know why `as.Seurat` does not work for me. I got the message:
> > Error in UseMethod(generic = "as.sparse", object = x) : no applicable method for 'as.sparse' applied to an object of class "c('DelayedMatrix', 'DelayedArray', 'DelayedUnaryIsoOp', 'DelayedUnaryOp', 'DelayedOp', 'Array', 'RectangularData')"
> 
> I met the same question, have you already solved that questioin?

I met the same question, have you already solved that questioin?
