### ISSUE TITLE
Clustering subsetted cells from a previously integrated dataset

### ISSUE THREAD

**Issue by mistrm82** [satijalab/seurat#3749]
Hello Seurat Team,

I realize that there are many posts/issues on this topic and after having read through them I have still not found a satisfying answer. 

I have a dataset with 8 samples and two sample groups (4 replicates in each group). For the full dataset I carried out the standard integration + clustering workflow as described in the tutorials. Now I want to subset the cells to keep those from a few clusters and then re-cluster them.
 
One of the issues I found conclude with:
"I would not recommend repeating the integration on a subset of the cells, using the integrated assay computed on the full dataset should be sufficient for subclustering."

_Originally posted by @timoast in https://github.com/satijalab/seurat/issues/1547#issuecomment-495681165_

This along with other posts I have come across lead me to believe that I should do the following:

Take the full integrated dataset. 
Subset it to keep cells in select clusters. 
Re-cluster the cells without performing any additional normalization and integration.

Is this correct?

And if so, what is the reason for not integrating on a subset of cells?
 Intuitively, it makes more sense to me to take the raw counts for the subset and run it through the full workflow again to get new clusters. I would love to hear more on why this is not the way to go.

Thanks so much in advance!
Meeta

**Comment by jaisonj708** [comment]
You can certainly integrate cell subsets. But as Tim mentioned, it is usually sufficient to simply subset the integrated output (i.e, re-integrating may or may not be worth the extra time/effort).
