### ISSUE TITLE
About "bimod" test in FindMarkers and FindAllMarkers

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#375]
Hi Seurat Team,

I would like to get your response on the validity of the "bimod" test.  I realize that now Seurat defaults to the Wilcox test to find markers, but also provides options to choose the "bimod" test, which was the previous default.  The thing is, I have been using Seurat well before the Wilcox default, and so, have a lot of the marker genes identified for my data using the "bimod" test.  So, I am hesitant to change now, at least for the dataset that I am working on.  So, I would like to know, to what extent the Wilcox test is better, and in what way?

Would the markers identified be significantly different?  Has your team carried out any comparison studies between "bimod" and Wilcox?  What was the primary reason to switch to the Wilcox default?

Essentially, what I would like to know is, is it OK to stick to the "bimod" test for convenience, considering that I have already used it extensively for my analysis so far?

Would really appreciate your opinion and advice on this!

**Comment by leonfodoulian** [comment]
Hi,

You might find your answers in [this paper](https://www.nature.com/articles/nmeth.4612).

Best,
Leon
