### ISSUE TITLE
Seurat(v3) Integration on multiple dataset

### ISSUE THREAD

**Issue by parvathisudha** [satijalab/seurat#3752]
I am planning to integrate single cell datasets of more than 15 samples with each having 2 conditions using Seurat v3. For this, should I analyze (QC, Clustering etc) each dataset seperately before integrating them?

Can anyone suggest the best way to perform this analysis?

**Comment by jaisonj708** [comment]
You can run QC on each individual dataset, but you certainly do not need to cluster beforehand. Feel free to refer to our Integration and Label Transfer vignette [here](https://satijalab.org/seurat/v3.2/integration.html)

**Comment by parvathisudha** [comment]
Hi, I have a question related to performing QC and normalization for individual samples prior to integration using SCTransform. For the normalization, do I have to use SCTransform on individual samples or will it be okay if we use log normalization?
