### ISSUE TITLE
Remove some cell types from the clusters

### ISSUE THREAD

**Issue by maryam1717** [satijalab/seurat#3755]
Greetings,

I have single-cell sequencing data from three different Patients. I annotated the cell types for each cluster using SingleR and Celldex libraries and added the labels to the metadata in the Seurat object.

I want to remove cell types from clusters that don’t appear anywhere or are very low everywhere but I don't have any clue. (for example, the number of B cell is 0 in cluster 1 and I want to remove it)

Any recommendation or solution would be appreciated.

**Comment by timoast** [comment]
Not sure what you mean. If there are zero B cells, what do you want to remove exactly?

See the [`subset`](https://rdrr.io/cran/Seurat/man/subset.Seurat.html) function documentation for information about removing cells from a Seurat object

**Comment by maryam1717** [comment]
> Not sure what you mean. If there are zero B cells, what do you want to remove exactly?
> 
> See the [`subset`](https://rdrr.io/cran/Seurat/man/subset.Seurat.html) function documentation for information about removing cells from a Seurat object
I need to show the number of cell types per cluster in the heatmap but I don't want zero cell types in my heatmap. for example cluster 1 has b cell, t cell , macrophage, ..., and the number of b cell is zero.I want to remove it and show the rest of the cell types in the heatmap.

**Comment by maryam1717** [comment]
more information:
 View(table(seurat$SingleR.labels,seurat$seurat_clusters))
![image](https://user-images.githubusercontent.com/64159480/99848700-8908ec80-2b7a-11eb-8dbb-2a6a9fd73b96.png)
as you can see we have many celltypes which are zero in cluster 0 , i want to remove them.

**Comment by maryam1717** [comment]
@timoast I added more information.

**Comment by timoast** [comment]
This is a more generic R programming issue, rather than anything specific to Seurat. There are several ways to achieve this, you could start by looking at the dplyr package: https://dplyr.tidyverse.org/
