### ISSUE TITLE
Regression creates a batch effect

### ISSUE THREAD

**Issue by hekselman** [satijalab/seurat#376]
Dear team,
Shortly, I get a batch effect after regressing out the effect of an experiment.

After merging all my replicates from my experiment, I run this, to give them new identities:
```
Merged <- RenameIdent(object = Merged, old.ident.name = "r1", new.ident.name = "ex1")
Merged <- RenameIdent(object = Merged, old.ident.name = "r2", new.ident.name = "ex1")
Merged <- RenameIdent(object = Merged, old.ident.name = "r3", new.ident.name = "ex1")
Merged <- RenameIdent(object = Merged, old.ident.name = "r4", new.ident.name = "ex1")
Merged <- RenameIdent(object = Merged, old.ident.name = "r5", new.ident.name = "ex2")
Merged <- RenameIdent(object = Merged, old.ident.name = "r6", new.ident.name = "ex2")
Merged <- RenameIdent(object = Merged, old.ident.name = "r7", new.ident.name = "ex2")
Merged <- RenameIdent(object = Merged, old.ident.name = "r8", new.ident.name = "ex2")

```
And then I regress the effect of these identities, using this:
`Merged <- ScaleData(object = Merged, vars.to.regress = "ident", genes.use = Merged@var.genes)
`

I make sure that Merged@ident contains ex1/ex2 values, BUT I clearly see a **new** batch effect that did not appear before regression on tSNE graph. Could you explain how come? :O

Thanks in advance, Idan.

**Comment by hekselman** [comment]
I have to add (if it wasn't clear) that the new batch effect is by experiment - the effect that I actually tried to regress out...

**Comment by satijalab** [comment]
Of course this is not the outcome we would hope for, but unfortunately we cannot diagnose or debug the exact reason. If you see significant differences in cell type composition between experiments, this can cause challenges for regression-based batch correction, and we would instead suggest alternative methods for data integration.
