### ISSUE TITLE
Follow-up on clustering subsetted cells from a previously integrated dataset

### ISSUE THREAD

**Issue by marypiper** [satijalab/seurat#3760]
Hi Seurat Team,

Thank you for the wonderful tools and vignettes and being so responsive to user questions! I use your tools and vignettes frequently as a consultant and instructor. We greatly appreciate all of the work you all are doing for the analysis of single-cell data. I have a question that follows up on issue #3749 (https://github.com/satijalab/seurat/issues/3749) regarding subsetting and integration of a previously integrated dataset. Your response to re-integrating a subset was: "You can certainly integrate cell subsets. But as Tim mentioned, it is usually sufficient to simply subset the integrated output." 

In the past I have re-integrated my subsets, which seems like it would allow for greater delineation of subclusters by using the most variant genes present only in the subsetted cells for alignment. Is this thinking correct? 

However, my main question is: Is there any time that re-integrating the subsets would be deleterious to the analysis rather than just not necessary? Do you have any examples where re-integrating would cause incorrect alignment or a poor analysis? 

Thank you for your help,
Mary

**Comment by timoast** [comment]
Since the integration methods are neighbor-based, they assume a certain minimum number of cells. If you subset the object to contain very few cells, it could adversely affect the integration results

**Comment by marypiper** [comment]
Hi @timoast, thanks for your response! I anticipated your answer and was wondering about a good rule-of-thumb about datasets that would be too small. I realize every dataset has different sources and degrees of variation, which would affect the number of cells that would be too few to perform an accurate integration; however, in general, is there an average number of cells per cluster which would be considered too small (e.g. datasets with less than X number of cells on average would likely not integrate accurately)?

**Comment by timoast** [comment]
It's difficult to advise on a specific number of cells below which the integration will not work well, all I can really say is to keep in mind that this can be an issue for small datasets, and you could try setting the value of `k` slightly lower in those cases.
