### ISSUE TITLE
ScaleData still gives me an empty scale.data slot

### ISSUE THREAD

**Issue by dearzoo** [satijalab/seurat#3761]
Hello Seurat Team,
First of all, thanks for the great package.
I'm one of the heavy users of Seurat.
Today I tried to plot a heatmap using the DoHeatmap function so I performed ScaleData on my RNA array at first.

The code I wrote is as below;

DefaultAssay(tri.subset) <- "RNA"
NormalizeData(tri.subset)
all.features <- rownames(tri.subset)
ScaleData(tri.subset, features = all.features)

It ran ok but when I checked my RNA assay -> data -> scale.data, it's still empty.
I used DoHeatmap quite often and didn't have this issue before. I always ran ScaleData before doing DoHeatmap and it worked. Can you tell me what I need to do?

Thanks.

**Comment by samuel-marsh** [comment]
Hi,

You need to save the commands that you are running back to object:
```
tri.subset <- NormalizeData(tri.subset)
all.features <- rownames(tri.subset)
tri.subset <- ScaleData(tri.subset, features = all.features)
```

Best,
Sam

**Comment by dearzoo** [comment]
Thanks!
