### ISSUE TITLE
loomR should be removed from suggested packages

### ISSUE THREAD

**Issue by mjsteinbaugh** [satijalab/seurat#3762]
Since [loomR](https://github.com/mojaveazure/loomR) isn't on CRAN yet, Seurat can fail to install when suggested packages are included:

```r
options(warn = 2L)
BiocManager::install(pkgs = "Seurat", dependencies = TRUE)
```

```
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'Seurat'
Error: (converted from warning) dependency ‘loomR’ is not available
```

**Comment by saketkc** [comment]
Seurat is hosted on CRAN (and not on Bioconductor). To install:

```
install.pacakges("Seurat")
```

See [this](https://satijalab.org/seurat/install.html) page for instructions on installing the development version.

**Comment by saketkc** [comment]
Sorry, I misunderstood the issue. My apologies. We are working on a fix and will keep you posted.

**Comment by mojaveazure** [comment]
Hi Michael,

You should be able to force Seurat to install with all dependencies by setting `type = 'source'`. The downside is that this will take longer as all packages will need to compile from source. If you're on macOS or Linux, you will need to have the HDF5 library installed (hdf5r provides the HDF5 library on Windows).

As an aside, we are aware that loomR not being on CRAN or Bioc is a pain point (it causes headaches for building new releases of Seurat as well). We are working to address this, but unfortunately, it'll likely be sometime in early 2021 before this gets fully resolved. We apologize for the inconvenience.

**Comment by mjsteinbaugh** [comment]
Thanks @saketkc and @mojaveazure , no worries, I just added loomR via GitHub in my install recipe prior to installing to Seurat, to avoid this issue. Just wanted to give you a heads up in case anybody else hits this issue. CRAN/Bioconductor submissions are a process.

**Comment by mjsteinbaugh** [comment]
Also, setting up a [drat repo](https://eddelbuettel.github.io/drat/) is really useful for packages that aren't available on CRAN yet. Have you tried this in the Satija Lab yet? It's totally awesome. I have [one here](https://github.com/acidgenomics/drat) for my [Acid Genomics](https://acidgenomics.com) packages, which I'm still working on getting up on Bioconductor.
