### ISSUE TITLE
Is raw RNA read count matrix available for pbmc_multimodal.h5seurat?

### ISSUE THREAD

**Issue by logstar** [satijalab/seurat#3763]
I wonder if the raw read count matrix for `pbmc_multimodal.h5seurat` is available for downloading. I assume the `pbmc_multimodal.h5seurat@assays$SCT@counts` are sctransform corrected UMI counts, because the sum of the corrected read counts are different from `pbmc_multimodal.h5seurat@meta.data$nCount_RNA`.

I downloaded `pbmc_multimodal.h5seurat` at https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat .

Thanks.

**Comment by satijalab** [comment]
We are in the process of uploading the count data to GEO, and will post the link here when ready. @yuhanH

**Comment by yuhanH** [comment]
Hi,
Sorry for the delay. Our raw count matrices are released in GEO. 
You can find them in this link: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378
