### ISSUE TITLE
Interoperability between single-cell object with multiple assays + How-to?

### ISSUE THREAD

**Issue by danmoore1987** [satijalab/seurat#3764]
Dear Seurat team,

With Seurat's v4 multimodal power demonstration, it would now be really useful if lets say "as.SingleCellExperiment" function allowed multiple assays to be included.

If someone already has a script to do so, would you please be willing to share it? 

Thank you! :)

**Comment by torkencz** [comment]
Thank you for your suggestion. I added code to handle multiple assays and it will likely be an update in a later release of Seurat.

**Comment by eliascrapa** [comment]
Hi, 

I updated to Seurat 4.0.3 and like I understand it added the possibility to export all Assays to a SCE from a Seurat object with as.SingleCellExperiment. I have two assays RNA and ATAC. Added like described in the Multiome Vignette. However, I am not able to export both at once. I can choose both separately with assay="" but not together.
