### ISSUE TITLE
Merging and filtering multiple datasets

### ISSUE THREAD

**Issue by goncik** [satijalab/seurat#3765]
Hi, 

I have three sc-RNA seq (10X) datasets, all from different labs, all primary samples, 2 of them with 3 prime kit and 1 with 5 prime kit. What would be the best way to merge and filter these samples before running Harmony for integration? 

I tried merging all the samples and filtering afterwards, but one dataset has more cell counts than the other and fitting the threshold for all samples seems to be too strict for the other dataset. 

Should I filter each sample one by one and merge later? Or merge each dataset within itself and filter, and making a list of the 3 dataset and continue? 

Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully this is helpful, others may have different thoughts.  I would say to be honest there isn't really one right answer here necessary and will depend on datasets in questions and the magnitude of differences between the datasets and other batch factors in addition to differences in technology.  In my opinion, if you want to set some upper and lower bounds of QC filtering before analysis/integration but there is difference between datasets I would probably say to do your filtering on per dataset (not per sample) basis and then proceed with analysis.  That should help to account for some issues but still allow control over filtering.  

Best,
Sam

**Comment by goncik** [comment]
Dear Sam, 

Thank you very much for your answer and time. 

Best,
G
