### ISSUE TITLE
Maximum number of features returned by SelectIntegrationFeatures() is 4500?

### ISSUE THREAD

**Issue by mcsimenc** [satijalab/seurat#3767]
Hi and thanks for such a useful R package. I am integrating three Seurat objects and noticed that when I ask for `nfeatures` greater than 4500 in `SelectIntegrationFeatures()` I always get 4500 features. Is this limit intentional and if so why is there such a limit?

For example, I have three Seurat objects, D10, D12, and D14. If I look at what features they have in common I get:
```
> length(intersect(intersect(rownames(D10), rownames(D12)), rownames(D14)))
[1] 18128
```

but when I ask for more than 4500 features I get:
```
> length(SelectIntegrationFeatures(list(D10, D12, D14), nfeatures = 5000))
[1] 4500
```

Thanks!

Matt

**Comment by jaisonj708** [comment]
The integration features must also be in at least one of your object's `VariableFeatures`

**Comment by mcsimenc** [comment]
My object doesn't have a slot called `VariableFeatures`. Can you explain what you mean?
