### ISSUE TITLE
Problem with FindConservedMarkers

### ISSUE THREAD

**Issue by pabloatria18** [satijalab/seurat#3769]
Hello

I don't know if this is a problem with my data, but when I run FindConservedMarkers I get genes with really different pvalues, instead of getting values of 0 or closer to 0.
Does this mean that those specific cluster do not have conserved markers?

Thank you

**Comment by andrewwbutler** [comment]
Hi,

I don't know what exactly you mean by "really different pvalues" but if you are getting results with larger p-values, that does suggest that those genes in those specific clusters might not be conserved across what ever grouping variable you're looking at.
