### ISSUE TITLE
Regress out or remove cell with high abundence genes?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#377]
My data seems to have high globin gene count as the sample is from blood. Is it a good idea to remove those globin genes or to regress out their expression?

**Comment by satijalab** [comment]
If this is an issue related to a very small number of contaminating genes, we would suggest making sure these genes are not part of the set passed for dimensionality reduction.

**Comment by bishwaG** [comment]
Thanks for the reply. I am using CCA approach for my data. I excluded globin genes from CCA analysis. However, I got those none interesting genes as cluster markers. Do I have to exclude gene.remove in the functions RunTSN and FindClusters?
```

gene.remove <- c("HBA1", "HBA2", "HBB", "HBD", "HBE1", "HBG1", "HBG2", "HBM", "HBQ1", "HBZ", "MB")

## Highly variable genes
hvg.d <- rownames(x = head(x = aml.d@hvg.info[! rownames(aml.d@hvg.info) %in% gene.remove,] , n = 1000))
hvg.cr <- rownames(x = head(x = aml.cr@hvg.info[! rownames(aml.cr@hvg.info) %in% gene.remove,], n = 1000))
hvg.union <- union(x = hvg.d, y = hvg.cr)
aml <- RunCCA(object = aml.d, object2 = aml.cr, genes.use = hvg.union)
```
