### ISSUE TITLE
Failed installation of Loom branch in google Colab R environment

### ISSUE THREAD

**Issue by erikjskie** [satijalab/seurat#3770]
I am using google colab R environment  ([https://colab.to/r](https://colab.to/r))  and have been using the master branch Seurat build successfully, however, I have a dataset with ~200k cells and Colab has a memory limit of 25gb so I don't believe I would be able to process that much data with that little memory without using Loom (at least I haven't been able to successfully, even after adding the optimizations from your mouse atlas tutorial, suggestions are welcome!).

Following the MCA_Loom tutorial I successfully installed LoomR, but when I run the install for the loom branch I get the following:

command: `devtools::install_github(repo = 'satijalab/seurat', ref = 'loom')`

output: `Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) package ‘multtest’, 'SDMTools' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Traceback:

1. devtools::install_github(repo = "satijalab/seurat", ref = "loom")
2. pkgbuild::with_build_tools({
 .     ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
 .         rlang::warn))
 .     {
 .         remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
 .             auth_token = auth_token, host = host)
 .         install_remotes(remotes, auth_token = auth_token, host = host, 
 .             dependencies = dependencies, upgrade = upgrade, force = force, 
 .             quiet = quiet, build = build, build_opts = build_opts, 
 .             build_manual = build_manual, build_vignettes = build_vignettes, 
 .             repos = repos, type = type, ...)
 .     }
 . }, required = FALSE)
3. install_remotes(remotes, auth_token = auth_token, host = host, 
 .     dependencies = dependencies, upgrade = upgrade, force = force, 
 .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
 .     build_vignettes = build_vignettes, repos = repos, type = type, 
 .     ...)
4. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
 .     stop(remote_install_error(remotes[[i]], e))
 . })
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)`

I was able to fix this by installing multtest through bioconductor: `BiocManager::install('multtest')`
SDMTools is retired from cran so I had to pull from archives where I took the most recent version (2019-11-30): `devtools::install_url("https://cran.r-project.org/src/contrib/Archive/SDMTools/SDMTools_1.1-221.2.tar.gz")`

running the install again throws a new error (note: this time install takes considerably longer before throwing error ~20 minutes): 

`Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpIlEONU/file4162e89e4c/Seurat_2.3.1.tar.gz’ had non-zero exit status
Traceback:

1. devtools::install_github(repo = "satijalab/seurat", ref = "loom")
2. pkgbuild::with_build_tools({
 .     ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
 .         rlang::warn))
 .     {
 .         remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
 .             auth_token = auth_token, host = host)
 .         install_remotes(remotes, auth_token = auth_token, host = host, 
 .             dependencies = dependencies, upgrade = upgrade, force = force, 
 .             quiet = quiet, build = build, build_opts = build_opts, 
 .             build_manual = build_manual, build_vignettes = build_vignettes, 
 .             repos = repos, type = type, ...)
 .     }
 . }, required = FALSE)
3. install_remotes(remotes, auth_token = auth_token, host = host, 
 .     dependencies = dependencies, upgrade = upgrade, force = force, 
 .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
 .     build_vignettes = build_vignettes, repos = repos, type = type, 
 .     ...)
4. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
 .     stop(remote_install_error(remotes[[i]], e))
 . })
5. tryCatchList(expr, classes, parentenv, handlers)
6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
7. value[[3L]](cond)`

I took a look at the github for the loom branch and it looks like it's still on Seurat V2 while the other branches are on V3. I tried installing the seurat 2.3.1 version to see if it was a version compatibility issue, but that was successful: `devtools::install_version(package = 'Seurat', version = package_version('2.3.1'))` but that of course does not have any loom methods.

I am not a developer, is it an incompatability with R 4.0.3? Is it not recognizing the two dependencies I had to install separately?  any help would be much appreciated!

Here is the code altogether
```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("multtest")
# Install devtools from CRAN
install.packages("devtools")
# Use devtools to install hdf5r, loomR, and SDMTools
devtools::install_github(repo = "hhoeflin/hdf5r")
devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
devtools::install_url("https://cran.r-project.org/src/contrib/Archive/SDMTools/SDMTools_1.1-221.2.tar.gz")
devtools::install_github(repo = 'satijalab/seurat', ref = 'loom')
```

and here is the environment information:
`R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] multtest_2.46.0     Biobase_2.50.0      BiocGenerics_0.36.0

loaded via a namespace (and not attached):
 [1] pillar_1.4.6        compiler_4.0.3      BiocManager_1.30.10
 [4] prettyunits_1.1.1   base64enc_0.1-3     remotes_2.2.0      
 [7] tools_4.0.3         testthat_3.0.0      digest_0.6.27      
[10] pkgbuild_1.1.0      uuid_0.1-4          pkgload_1.1.0      
[13] lattice_0.20-41     jsonlite_1.7.1      evaluate_0.14      
[16] memoise_1.1.0       lifecycle_0.2.0     rlang_0.4.8        
[19] Matrix_1.2-18       IRdisplay_0.7.0     cli_2.1.0          
[22] IRkernel_1.1.1      curl_4.3            repr_1.1.0         
[25] withr_2.3.0         desc_1.2.0          fs_1.5.0           
[28] devtools_2.3.2      stats4_4.0.3        grid_4.0.3         
[31] rprojroot_1.3-2     glue_1.4.2          R6_2.5.0           
[34] processx_3.4.4      fansi_0.4.1         survival_3.2-7     
[37] sessioninfo_1.1.1   pbdZMQ_0.3-3.1      callr_3.5.1        
[40] magrittr_1.5        MASS_7.3-53         splines_4.0.3      
[43] backports_1.2.0     ps_1.4.0            ellipsis_0.3.1     
[46] htmltools_0.5.0     usethis_1.6.3       assertthat_0.2.1   
[49] crayon_1.3.4       `

**Comment by saketkc** [comment]
You do not need the `loom` branch for Seurat. For Seurat v3, you can simply install it from cran:
```
install.pacakges("Seurat")
```
For installing from develop branch or v4 checkout the [installation](https://satijalab.org/seurat/install.html) page.

`loomR` has a walkthrough [tutorial](https://satijalab.org/loomR/loomR_tutorial.html) which might be useful.
