### ISSUE TITLE
Using what parameters to prepare data for preranked GSEA

### ISSUE THREAD

**Issue by MingwuDuan** [satijalab/seurat#3771]
Dear Seurat team,
I have 3 lung tissue samples from 3 patients and 3 samples from 3 healthy donors, cells of which are labelled as 'disease' and 'control' at lung_combined@meta.data$clinical_groups, respectively. I want to perform GSEA(Gene Set Enrichment Analysis) at cluster level (e.g. monocyte) between two clinical_groups, so I have used codes as follows:
`Result<-FindMarkers(lung_combined,
assay = "RNA",
slot = "data",
subset.ident = 'monocyte',
group.by = "clinical_groups",
ident.1 = "disease",
ident.2 = "control",
test.use = "wilcox",
logfc.threshold = -Inf,
min.pct = -Inf,
min.diff.pct = -Inf)`
then I use rownames(Result) and Result[,'avg_logFC'] which are both sorted to do downstream analysis. I am wondering whether it is correct to set subset.ident = levels(lung_combined) to perform GSEA at global level (cell types ignored). A useful tool called "presto" ( https://github.com/immunogenomics/presto ) could perform GSEA at cluster level, so may I conduct global GSEA data preparation with it using codes like
`wilcoxauc(lung_combined, group_by ='clinical_groups')`? Thanks in advance!
Best,
Mingwu DUAN

#3129

**Comment by satijalab** [comment]
You can perform either GSEA after identifying cluster-specific DE genes, or DE genes when considering all cells (which would be similar to running a bulk RNA-seq experiment and then performing GSEA on DE genes)- depending on your specific question of interest.
