### ISSUE TITLE
preprocessing before or after integration?

### ISSUE THREAD

**Issue by dm8000** [satijalab/seurat#3775]
Hello Seurat team.

I would like to integrate a few published datasets. I would like to know if I should remove doublets, cells with high MT content and etc before or after integration. Simply for convenience I have considered integrating preprocessed data, as some authors make their Seurat objects available or because their expression matrices are in formats I am not comfortable with. These authors used different preprocessing methods/thresholds. Moreover, because I am interested on mitochondrial genes, different MT% cutoffs concern me (5-15%). I would like to know if you believe this will significantly affect the results.

Best,
Diogo

**Comment by jaisonj708** [comment]
QC is generally done prior to integration in order to avoid anchoring based on less significant information like MT reads. Major changes in the MT threshold will change results a bit - as an example, if you retain too many mitochondrial reads, your data may cluster based on MT content
