### ISSUE TITLE
reference mapping for integrated dataset

### ISSUE THREAD

**Issue by pkuerten** [satijalab/seurat#3777]
Hi, I am trying to reference map a previously integrated dataset. I have already updated the different packages following the suggestions at https://github.com/satijalab/seurat/issues/3686 and https://github.com/satijalab/seurat/issues/2590

If I follow the BMNC vignette, I get no errors but I am not able to merge(reference, projected) for novel cluster discovery. I get a "Error in umi.assay.old[[j]] : subscript out of bounds".

Looking at the cell assignment, I can see some novel cell types in my data which are being wrongly assigned.

I have three questions.

1) Is there a way to use the integrated data instead of the RNA per sample data for reference mapping? 
2) Any advice on novel cell type detection following BMNC vignette.
3) What is the expected impact of using a subset of celltypes in the projected data? 

Thank you for your guidance.

**Comment by yuhanH** [comment]
Do you use SCT normalization for the query dataset?
For this bone marrow reference, you can only use log-normalization now.

For your three question, 1. integrated data should be mapped to the reference. But your integrated objects have to be normalized by the same method with the reference. 
2. When you merge query ref.spac and reference spca embeddings together,  you can runUMP on this merged object. If you can find a clusters only composed of query cells, then that cluster should be a novel population. 
You can find a similar figure SuppFig 8G in our preprint, https://www.biorxiv.org/content/10.1101/2020.10.12.335331v1
3. We are working on this situation now. We will update some functions for the sub-population mapping. Stay tuned!

 If you still meet errors for mapping integrated data to our reference, i will reopen this issue.
