### ISSUE TITLE
sample label in DimPlot

### ISSUE THREAD

**Issue by MjelleLab** [satijalab/seurat#3778]
I am plotting a Seurat object and wonder how to label the samples in the output plot. I have a total of 5 samples across 1000 cells, and want to show which sample the different clusters belong. For instance if one clusters is mainly from one samples
My samples are stored as a vector in `sample`.

`DimPlot(pbmc, reduction = "umap")`

**Comment by waterrivers** [comment]
Try 
Dimplot(pbmc, reduction = "umap", group.by = "orig.ident")
