### ISSUE TITLE
Error when attempting to specify "features" in AverageExpression() - "arguments imply different number of rows"

### ISSUE THREAD

**Issue by kstoltz1** [satijalab/seurat#3779]
Hi everyone, 

I'm attempting to use the AverageExpression() function to get the average expression for a select number of genes, which I have populated into a gene list:
```
gene_list <- c("Cxcr4", "Aicda", "Foxp1", "Cd83", "Bcl2a1", "Mir155hg", "Cd40", "Lmo2", "Irf4", "Prdm1", "Xbp1", "Ccr6")
```
When I attempt to run the AverageExpression function: 
```
cluster.averages <- AverageExpression(immune.combined, assay = 'RNA', features = gene_list)
```
I get the following error: 

_"Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 12, 11"_

From what I can gather, it's an error with a cbind function within the AverageExpression() function, but I'm a novice at R coding, I do not know how to fix it.

Here's the traceback - 
```
> traceback()
6: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
5: data.frame(..., check.names = FALSE)
4: cbind(deparse.level, ...)
3: (function (..., deparse.level = 1) 
   .Internal(cbind(deparse.level, ...)))(structure(list(), .Names = character(0), row.names = c("Cxcr4", 
   "Aicda", "Foxp1", "Cd83", "Bcl2a1", "Mir155hg", "Cd40", "Lmo2", 
   "Irf4", "Prdm1", "Xbp1", "Ccr6"), class = "data.frame"), `0` = c(Cxcr4 = 0.29354....)
2: do.call(cbind, data.all)
1: AverageExpression(immune.combined, assay = "RNA", return.seurat = T, 
       features = gene_list)
```

Also, it seems like somebody else ran into a similar issue with a different Seurat function, but the issue was never resolved, and is now closed:
[https://github.com/satijalab/seurat/issues/766](url)

**Comment by shahrozeabbas** [comment]
I dealt with this a while back, might have to dig up the code, but you have to make sure your `scale.data` assay contains the genes you want...I think. Either that or try to specify the slot to pull the averages from. The [documentation](https://rdrr.io/github/satijalab/seurat/man/AverageExpression.html) sets the default slot as `data`, which means it should be fine, but worth a shot. Does your object contain gene names in all caps?

**Comment by andrewwbutler** [comment]
Hi, 

Are you able to run the function without specifying the `features` parameter?

**Comment by kstoltz1** [comment]
Hi @andrewwbutler Yes I was able to successfully run it without the features parameter. In fact, I ended up working around the issue by just selectively plotting my genes of interest downstream.

**Comment by andrewwbutler** [comment]
Glad to hear you found a work around. We are also working on an updated `AverageExpression` as well which should improve many aspects of this function and hopefully resolves this as well.
