### ISSUE TITLE
Identify differential expressed genes across conditions (genes.to.label)

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#378]
Hi!

I have a question about the _Tutorial: "Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses"_.

At the end, in this part _"Identify differential expressed genes across conditions"_, it's possible to plot the average expression of both the stimulated and control conditions. 

We can show this specific gene that we previously add to thanks to this object: `genes.to.label1`.

Is there a way to automatically write all of the differential genes accross conditions, and not add them to `genes.to.label1` ? (for example, a mix between this plot and the `FindMarkers` function that we use just after).

Thanks!

**Comment by satijalab** [comment]
We do not have a function for this at the moment, as it only takes two consecutive lines of code, but please feel free to submit a pull request if you feel it would be helpful.
