### ISSUE TITLE
Error while creating Seurat Object

### ISSUE THREAD

**Issue by ADvorkinGheva** [satijalab/seurat#3781]
Greetings,

When trying to create a Seurat Object using barcodes.tsv, genes.tsv and matrix.mtx files, I encounter the following error message:

```data_dir <- "folder in which the barcodes.tsv, genes.tsv and matrix.mtx files are located"

new_data <- Read10X(data.dir = data_dir,gene.column=1)
data_object<-CreateSeuratObject(counts = new_data,project = "new", min.features=200)
Warning: Non-unique cell names (colnames) present in the input matrix, making unique
Error in validObject(.Object) : 
  invalid class “Assay” object: 1: invalid object for slot "counts" in class "Assay": got class "numeric", should be or extend class "AnyMatrix"
invalid class “Assay” object: 2: invalid object for slot "data" in class "Assay": got class "numeric", should be or extend class "AnyMatrix"
```

I am not sure if it is a bug, but I could not find any information on what I should do in this situation.
I have other samples represented by similar files, and they all run well and I can create Seurat Objects from them. I tried to compare this problematic matrix.mtx file to the others and could not see any prominent issue.

I will greatly appreciate any advice on what I should do in order to be able to create a Seurat object from this matrix.mtx file (using the barcodes.tsv and genes.tsv files too, of course).

Thank you!

Regards,
Anna

**Comment by ADvorkinGheva** [comment]
Greetings,

I am closing the issue, since I have discovered that the file I was loading was corrupted. Once I fixed that issue, everything worked well.

Regards,
Anna

**Comment by noelletnw** [comment]
Hello,

I am also having this same problem. How were you able to fix your issue? Would greatly appreciate any advice. As you said, all of my other files work well and I can't see any differences between the two files.
