### ISSUE TITLE
Shiny app and seurat object

### ISSUE THREAD

**Issue by abhisheksinghnl** [satijalab/seurat#3782]
Dear authors &b community,

My apologies, this is really not an issuer with Seurat but I cannot get my head around with what is wrong with my shiny script that it is not working. As you all are much experienced users and can help, therefore posting here.

Below is my shiny script where it uses my seurat objects stored in .rds files

```
library(shiny)
library(shinythemes)
library(Seurat)
library(ggplot2)
library(gridExtra)
library(egg)
library(RColorBrewer)
library(shinyWidgets)

# Getting the file names
rdsfiles <- list.files("/temp2/data", pattern = "\\.rds$")

# Define UI for dataset viewer application
ui <- shinyUI(fluidPage(theme = shinytheme("cerulean"), pageWithSidebar(
    
    # Application title
    headerPanel("Shiny App with multiple datasets"),
    # Sidebar with controls to select a dataset and specify the number
    # of observations to view
    sidebarPanel(
        selectInput("dataset", "Choose a dataset:", 
                    choices = rdsfiles),
    ),
    
    # Show a summary of the dataset and an HTML table with the requested
    # number of observations
    mainPanel(
        tabsetPanel(
            tabPanel('UMAP', plotOutput("umap")),
            tabPanel('Gene', plotOutput("gene"))
            
        ))
    
)))

# Define server logic required to summarize and view the selected dataset
server <- shinyServer(function(input, output) {
    
    # Return the requested dataset
    datasetInput <- reactive({
        df <- readRDS(paste0("/temp2/data/", input$dataset))
        return(df)
    })
    
    # Generate a UMAP of the dataset
    output$umap <- renderPlot({
        dataset <- datasetInput()
        plot(input$dataset, reduction = "umap")
        
    })

    # Generate a Feature of the dataset
    output$gene <- renderPlot({
        dataset <- datasetInput()
        FeaturePlot(dataset, reduction = "umap")
        
    })
    
})


shinyApp(ui, server)
```

Unfortunately the code is unable to render UMAP and Feature plot and shows error "Error: cannot find umap in seurat object"

while the umap is present in seurat object.

I am not sure what I am doing wrong or how can I fix this. 

Kindly help.

**Comment by andrewwbutler** [comment]
Hi,

There are a number of issues with the implementation here. For instance, in the `server` function, you try to render the UMAP plot with `plot` rather than `DimPlot`. Also, your input to that function is `input$dataset` when you probably want just `dataset`. It also looks like you're pulling all available .rds files in your temp2/data/ directory. I would double check that the the .rds that is selected is actually a Seurat object and that that specific Seurat object contains UMAP coordinates.
