### ISSUE TITLE
Seurat V4 MapQuery issue

### ISSUE THREAD

**Issue by JLTrincado** [satijalab/seurat#3784]
Dear auhors,

I was eager to test the new Reference Mapping on Seurat v4. I had a reference and my query dataset and I ranUMAP using  return.model = TRUE and umap.method = "uwot-learn" as commented in #3668, but I got the following error:

```
library(Seurat)
library(ggplot2)
library(patchwork)

###load the Reference
load(file="/scratch/devel/jtrincado/MSC/misc/Seurat4.obj.Wolock.MSC.RData")
Seurat.obj

###load the Query
load(file="/scratch/devel/jtrincado/MSC/misc/9_ALL_BM_Infant.removingDEGbatch.v2.RData")
all_data_f2

anchors <- FindTransferAnchors(
  reference = Seurat.obj,
  query = all_data_f2,
  normalization.method = "LogNormalize",
  reference.reduction = "pca",
  dims = 1:14
)

Projecting cell embeddings
Finding neighborhoods
Finding anchors
	Found 281 anchors
Filtering anchors
	Retained 55 anchors


all_data_f2 <- MapQuery(
  anchorset = anchors,
  query = all_data_f2,
  reference = Seurat.obj,
  refdata = "cell_type",
  reference.reduction = "pca", 
  reduction.model = "umap"
)

Finding integration vectors
Finding integration vector weights
Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length
```

What could be the reason?

Thanks again for your time and congratulations for your work.

Juan L.

**Comment by sherriying** [comment]
Hi, 
I encounter the same problem. Would very appreciate if someone can help with. Many thanks! 
/Sherry

**Comment by Rohitarora21** [comment]
I am also running into the same issue.

**Comment by andrewwbutler** [comment]
Hi,

A reproducible example either on your data or a publicly available dataset would be very helpful here. If you could post a download link here or email to abutler@nygenome.org, I can look into this further.

**Comment by JLTrincado** [comment]
Dear authors,

thanks for your answer. I was reducing the size of my original query (20k cells) for creating a reproducible example. My reference has 3k cells. If I downsample the query to 5k then it seems to work. For bigger numbers, it returns the same error. It's not possible to query with a much higher number of cells? Why is this?

Thanks again.

Best,

Juan L.

**Comment by andrewwbutler** [comment]
Hi Juan,

There's no obvious reason why it would work for 5k but not 20k. Happy to try to debug further with whatever data you can share though.

**Comment by yuhanH** [comment]
Hi, Juan
I think it results from the stored weighted matrix. Could you check if your query object has `TransferData` in `tools` slot?
You can just delete it, and then the error should be fixed. 
`query.obj@tools$TransferData <- NULL`
In our latest branch, we don't store the weighted matrix any more, so it may not happen if you re-run all the pipeline.

**Comment by nilesh-iiita** [comment]
By setting neighbor's numbers to 10 it worked for me.
`alldata.int <- IntegrateData(anchorset = alldata.anchors, dims = 1:30, new.assay.name = "CCA", k.weight=10)`

**Comment by Jintram** [comment]
> By setting neighbor's numbers to 10 it worked for me.
> `alldata.int <- IntegrateData(anchorset = alldata.anchors, dims = 1:30, new.assay.name = "CCA", k.weight=10)`

I had the same issue, this indeed solved it. (I'll need to read up a bit to understand what this does though.)

**Comment by xiangmingcai** [comment]
I met the same issue. I tuned the parameter of k.weight to be smaller than the smallest sample size in these seurat objects. It did work!

**Comment by thodison** [comment]
> By setting neighbor's numbers to 10 it worked for me. `alldata.int <- IntegrateData(anchorset = alldata.anchors, dims = 1:30, new.assay.name = "CCA", k.weight=10)`

Very good! Thank you!
