### ISSUE TITLE
Change weights for each modality in FindMultiModalNeighbors

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#3785]
Hello!

I am wondering if it is possible to change how much weight is assigned to each modality in the function FindMultiModalNeighbors. The documentation -- "For each cell, we calculate its closest neighbors in the dataset based on a weighted combination of RNA and protein similarities." Broader question -- how is the "weighted combination" determined? 

Thank you!
Josephine

**Comment by yuhanH** [comment]
Hi, 
You can use `FindModalityWeights` function to get a ModalityWeights object, and you can change the modality weight in it. 
For example, 
```
bm.weight <- FindModalityWeights(object = bm, 
                reduction.list = list("pca", "apca"),
                dims.list = list(1:30, 1:18))
bm.weight@first.modality.weight
```
You can find the modality weight in the `first.modality.weight`. You can change it. 
Then, run `FindMultiModalNeighbors `

```
bm <- FindMultiModalNeighbors(object = bm, 
                  modality.weight = bm.weight,  
                  reduction.list = list("pca", "apca"), 
                  dims.list =NULL)

```
But we don't suggest you change the weights manually.
You can find detailed information about weight calculation in our preprint, https://www.biorxiv.org/content/10.1101/2020.10.12.335331v1
