### ISSUE TITLE
Keeping "negative" cells from hashed samples (to overload 10X channel)?

### ISSUE THREAD

**Issue by LJimenezGracia** [satijalab/seurat#3787]
Good afternoon!

I've started working in a new project in which we performed sample cell hashing (with CSP) in order to overload the 10X GEM channel with ~20,000 cells and easily detect and discard doublets [not to multiplex different samples and avoid batch-effects].
After running cellranger v5, we recovered ~14,000 cells, and I further performed the demultiplexing with HTODemux(). Around 10,000 cells were classified as singlets (71%), ~1600 as doublets (11%) and up to 2500 cells as negative, which corresponds with the 18%. 
I immediately filtered out doublets cells, but I was wondering if negative cells could be kept and considered in the downstream analysis in this specific case? And so, increasing the sample size we are working with.

I am aware that cells classified as negative are the ones in which almost no antibody has bound. Then, assuming that both the antibody and the experiment worked fine, might have their membrane compromised and therefore, can be considered poor-quality cells. However, after performing assessing both singlets and negative cells by several QC metrics (such as counts, features, %MT, %RB), I found out that both cell groups show a similar distribution. Moreover, if negative cells are included together with singlets in the clustering, they are found to be perfectly intermixed in the UMAP.

So, after sharing these results, I will repeat the same question... Would you consider the option of keeping the negative cells in the downstream analysis? Do you have any evidence/experience in keeping the negative cells in this specific situation?

Thank you very much for you help,

Laura

**Comment by timoast** [comment]
Unless you have a reason to think that there were unlabelled cells in the hashing experiment, it doesn't make sense to retain any "cells" that don't have a HTO, since they must be background empty droplets. Your issue might be that the cutoff used to classify cells as positive vs negative for a hash is too high, which would result in positive cells falsely being labelled as negative. You can try changing the parameters in `HTODemux` or `MULTIseqDemux ` to see if you can improve the results

**Comment by massonix** [comment]
Hi @timoast,

I have experienced the same issue as Laura in some of our samples. However, in this case we have a reason to believe that the hashing protocol was suboptimal. Since we also used this protocol to increase our target recovery (not to exclude batch effects), we have solid reasons to keep the negative cells in our dataset. The greatest impact this will have is an increased doublet rate, which hopefully we can mitigate with scrublet.

**Comment by Ruismart** [comment]
hi, sorry to find this issue from nearly two years ago but no more discussion. 
I have some similar cases and also want to recover more singlets from the 'negative' cells. Taking with them for downstream, similar QC distribution, clustering and annotation could be done. 

here 'negative' might not be true 'empty wells' which could be efficiently filtered in cell-calling step(cellranger workflow).
here 'negative' might be some inefficiently-binding (for hashtags) cells, I have tried two ways to recover them:

a. run one more HTODemux for 'negative' only object, you could certainly get some proportion of 'Singlets' from it again. but I don't think it's reasonable, and if you check the counts/cutoff distribution, it could be visually not significant

b. range 'quantile' parameter in demux() (like, 0.50,0.51,...,0.99), then plot distribution for 'q'/doublets/negative/singlets(tag separately), combine with the counts distribution of each tag, you may be able to select a more suitable cutoff for each tag then manually build the metadata column depending on those cutoffs

**Comment by Ruismart** [comment]
hi, I have updated my practical code for this issue, with details like custom function to build the metadata,
               https://github.com/Ruismart/Spp1-DAM/tree/main/RNAseq/single/  s0.rmd  s0.html  '::check demux/demultiplexing'   
                 though the published datasets might not be the best examples, the code to process is complete
                (they are not bad enough to have to do the modification, and more like case 1.(ii) rather than (i) )
                 some considerations:   

                     1. not only range (i) q0.50~0.99, but also (ii) q0.9900~0.9999 
                           (i) for hashtags with inefficiently-binding
                           (ii) learned from more datasets, seems sometimes the background signals would increase biasedly, creating more doublets
                             
                     2. ranged 'quantile' in Demux() for reference only, the manual cutoffs could be determined individually based on the counts distribution, 
                           especially when one or two samples are very bad then the modeling could be much worse,  
                           a good cutoff should be around the knee point, actually plotting the distribution by sort(counts, decreasing = T) could be better to visualize

                     3. three figures help to do the decision, 'what's good' might be empirical
                           results of ranged 'q'
                           distribution of FB counts
                           tsne of 'max_ID' and 'filtered_ID'

               still, the default q0.99 could be an optimal choice at most times, but you may not always get the very standard data in research works, 
               there're many kinds of reasons: tissue/cell state, reagent quality,  technical operations in library preperation and sequencing et al.
               this little modification could be very helpful,        

               in addition, because the doublets/singlets/negatives are determined once globally, 
               if you want to recover more singlets for one bad sample/tag from negtives by decreasing its count cutoff, 
               you would also increase doublets for all other tags, vice versa !
               the moving degree should be carefully compared,  
               or we might could say, all cells around the cutoffs are unconfident !

               a better way to do the modification might be local modeling on the tsne to do local trimming,
               I've considered this more complicated process a little, however the current method is good enough for me now
