### ISSUE TITLE
MultiModal Data integration

### ISSUE THREAD

**Issue by sharmasiddhartha231** [satijalab/seurat#3788]
Not so much an issue but a question. I am handling Multiome Data and wanted to integrate the samples together and analyze as one. I have previously worked with snATAC data using Signac which allows for integration. I looked around in Seurat and I saw that I could integrate snRNA but is there a way to integrate the Multiome data as a whole instead of doing it individually since Seurat supports Multimodal analysis.

**Comment by yuhanH** [comment]
Hi, 
Currently, we suggest you integrate each modality individually, and then perform WNN method on two integrated assays.

**Comment by ifanirene** [comment]
Hello @yuhanH. I'd like to follow up on this question. To perform this analysis, do we have start by treating the two assays (RNA & ATAC) separately, and create individual seurat objects for them? I wonder if you integrate only SeuratObject[["RNA"]] from different samples, whether you will lose the SeuratObject[["ATAC"]] modality.

**Comment by yuhanH** [comment]
Hi, @ifanirene 
You will not lose `ATAC` modality / assay in the RNA integration step. But after you integrated RNA and want to integrate ATAC, the integrated ATAC assay may overwrite the integrated RNA assay if you don't set `assay` correctly in the integration workflow.

**Comment by ifanirene** [comment]
Hi @yuhanH,

Thanks for the reminder about setting the assay. I tried a few different workflows. As most of us will have to integrate more than two multimodality datasets, I feel it would be easiest to build the seurat object with both `RNA` and `ATAC` filtered and normalised for integration. When integrating the `RNA` assay, a merged (but not integrated) `ATAC` assay would appear in the resulting object (am I correct?). We will then have to use Harmony workflow on the `ATAC` modality.

**Comment by SammiLyu** [comment]
Hi @yuhanH,

I am running into the same confusion about what the current best practice for integrating multimodal datasets is. Any suggestion from you is much appreciated!
