### ISSUE TITLE
interpatient variability

### ISSUE THREAD

**Issue by silvafisherjess** [satijalab/seurat#3789]
I am new to analysis. I am processing scRNA seq myeloma samples. I would like to look at interpatient variability and then DE for cell type. Not sure how to do this. This is as far as I have gotten, Not what to do next? Do I need to pull out cell types I want?

> library (Seurat)
> library (patchwork)
> MM <- readRDS("~/Desktop/MM_scRNA-seq/SeuratObj_all_cells_in_18_MMRF_samples_celltype.rds")
> MM
MM <- NormalizeData(MM, normalization.method = "LogNormalize", scale.factor = 10000)
DefaultAssay(MM) <- "RNA"
> Idents(MM) <-”ori_ct”
Idents levels(MM)
DimPlot(MM)
all.markers <- FindAllMarkers(object = MM)
all.markers <- FindAllMarkers(MM, min.pct = 0.25, logfc.threshold = 2)

**Comment by silvafisherjess** [comment]
Will this give me the correct analysis output:
> subset(MM, idents = c("Plasma", "B Cell"))
An object of class Seurat 
54205 features across 4907 samples within 2 assays 
Active assay: RNA (33538 features, 0 variable features)
1 other assay present: SCT
2 dimensional reductions calculated: pca, umap
> Idents(MM) <-"ori_ct"
> Subsetall.markers <- FindAllMarkers(MM, min.pct = 0.25, logfc.threshold = 2)

**Comment by timoast** [comment]
Please see the documentation on the Seurat website, particularly the [immune alignment vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html)

**Comment by silvafisherjess** [comment]
I get an error "

> Patient.list <- SplitObject(MM1, split.by = "sample_id")
Error: vector memory exhausted (limit reached?)
In addition: There were 11 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: Not a validObject(): no slot of name "assay.orig" for this object of class "Assay"
2: Not a validObject(): no slot of name "assay.orig" for this object of class "Assay"
3: Not a validObject(): no slot of name "assay.used" for this object of class "Graph"
4: Not a validObject(): no slot of name "assay.used" for this object of class "Graph"
5: Not a validObject(): no slot of name "global" for this object of class "DimReduc"
6: Not a validObject(): no slot of name "global" for this object of class "DimReduc"
7: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand"
8: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand"
9: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand"
10: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand"
11: Not a validObject(): no slot of name "assay.used" for this object of class "SeuratCommand"

**Comment by timoast** [comment]
What's the output of `class(MM1)` and `packageVersion("Seurat")`?

**Comment by silvafisherjess** [comment]
S3, MM1 21320 rows and 11 columns.

I cleared environment on R studio and got this far.
> library (Seurat)
> library (patchwork)
> MM1 <- readRDS("~/Desktop/MM_scRNA-seq/SeuratObj_all_cells_in_18_MMRF_samples_celltype.rds")
> MM1
An object of class Seurat 
54205 features across 21320 samples within 2 assays 
Active assay: SCT (20667 features, 3000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
> DefaultAssay(MM1) <- "RNA"
> Patient.list <- SplitObject(MM1, split.by = "sample_id")
> Patient.list <- lapply(X = Patient.list, FUN = function(x) {
+     x <- NormalizeData(x)
+     x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
+ })
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
>patient.anchors <- FindIntegrationAnchors(object.list = patient.list, dims = 1:20)
Merging objects
Finding neighborhoods
Finding anchors
	Found 1820 anchors
Filtering anchors
	Retained 1544 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=23m 40s
There were 30 warnings (use warnings() to see them)

> Patient.combined <- IntegrateData(anchorset = Patient.anchors, dims = 1:20)
Error: vector memory exhausted (limit reached?)

**Comment by silvafisherjess** [comment]
pretty big files---
MM1 5.3gb
patient.list  11.5gb
patient anchors 11.9gb,
