### ISSUE TITLE
Problem about dispersion

### ISSUE THREAD

**Issue by July233** [satijalab/seurat#3790]
I used the codes to choose HVG genes by
                            `object <- FindVariableFeatures(object, 
                             selection.method = "dispersion", 
                             nfeatures = 2000)`.
But can I filter genes by dispersion_empirical/dispersion_fit like monocle2?I just see parameters mean and dispersion in Seraut.
Thanks for your reply

**Comment by andrewwbutler** [comment]
Hi,

There are two other options to `FindVariableFeatures` (`vst` and `mean.var.plot`) which select genes in a manner that try to take into account a relationship between mean and dispersion. For details, please see the function help page.
