### ISSUE TITLE
Get p_val avg_logFC from a specific gene between conditions

### ISSUE THREAD

**Issue by pabloatria18** [satijalab/seurat#3792]
Hello.
I am running a differential expression analysis between two conditions.
I have 10 clusters.

I am using this code to obtain the differentially expressed genes between conditions within the same clusters.

subsetclust$celltype.stim <- paste(Idents(subsetclust), subsetclust$group, sep = "_")
subsetclust$celltype <- Idents(subsetclust)
Idents(subsetclust) <- "celltype.stim"
b.interferon.response <- FindMarkers(subsetclust, ident.1 = "0_control", ident.2 = "0_loaded", verbose = FALSE)
head(b.interferon.response, n = 30)

My question is, I need to check the p_val and avg_logFC of some genes that do not appear using this code, that I assume are not DE between conditions.
Also, I would like to get the p_val and avg_logFC of specific genes comparing just conditions and no specific clusters.
Can someone help me which code I need to use?

Thank you!

**Comment by jaisonj708** [comment]
To get DE results for all genes, you can set thresholds in `FindMarkers` (e.g, set`logfc.threshold` to 0). To run DE on conditions rather than cell type clusters, you can temporarily set the object's Idents to the condition.

**Comment by pabloatria18** [comment]
Thanks!!

**Comment by mabaoweibbq** [comment]
logfc.threshold is based on log2 or loge？

**Comment by mabaoweibbq** [comment]
> To get DE results for all genes, you can set thresholds in `FindMarkers` (e.g, set`logfc.threshold` to 0). To run DE on conditions rather than cell type clusters, you can temporarily set the object's Idents to the condition.

logfc.threshold is based on log2 or loge？
