### ISSUE TITLE
R package 'Seurat' crashes with openMP error

### ISSUE THREAD

**Issue by elhaam** [satijalab/seurat#3793]
Hi all,

I am trying to load Seurat in RStudio, but my Rstudio crashes when running library(Seurat). I am facing the same problem mentioned [here](https://github.com/satijalab/seurat/issues/2769); I tried all the recommended solutions, and none have worked for me so far. BTW, I don't have r-miniconda on my computer to follow[ this link](https://stackoverflow.com/questions/63045994/r-package-seurat-crashes-with-openmp-error)'s solution. Here is the error I got when trying in the command line:

```
> library(Seurat)
OMP: Error #15: Initializing libomp.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. 
That is dangerous, since it can degrade performance or cause incorrect results. 
The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, 
e.g. by avoiding static linking of the OpenMP runtime in any library. 
As an unsafe, unsupported, undocumented workaround you can set the environment variable 
KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that 
may cause crashes or silently produce incorrect results. 
For more information, please see http://openmp.llvm.org/
Abort trap: 6
```

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.3
```

Could someone please help? I tried uninstalling and installing again as someone has recommended it, but it didn't help.

p.n: I know an unsafe solution can be Sys.setenv("KMP_DUPLICATE_LIB_OK" = "TRUE") based on the error, but I am not sure if that makes my analysis using Seurat unreliable or wrong.

**Comment by andrewwbutler** [comment]
Hi,

This seems to be an issue with your installation of OpenMP. There are a number of potential solutions described in this thread

https://github.com/dmlc/xgboost/issues/1715

Can you see if any of those resolve the issue?

**Comment by denvercal1234GitHub** [comment]
Hi @andrewwbutler - Thanks for pointing to the thread. 

I tried to delete the `/Users/clusteredatom/miniforge3/envs/tensorflowc/lib/libomp.dylib` as suggested here (https://github.com/dmlc/xgboost/issues/1715), but then, it caused another error `Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: The h5py Python package is required to save and load models`

Do you have any other suggestions?
