### ISSUE TITLE
scATACseq+scRNASEQ analysis :Error in `rownames<-`(`*tmp*`, value = genes_step1) 

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#3796]
With reference to the issue #3776  I made changes to the RNA reference based mapping. 
```
RNAQUERY <- SCTransform(
  +   object = RNAQUERY,
  +   assay = "RNA",
  +   method = 'LogNormalize',
  +   residual.features = rownames(x = reference$map),
  +   ncells = 2000,
  +   n_genes = 2000,
  +   do.correct.umi = FALSE,
  +   do.scale = FALSE,
  +   do.center = TRUE
  + )
```
Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 12356 by 668
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 668 cells
|======================================================================| 100%
Error in `rownames<-`(`*tmp*`, value = genes_step1) : 
  attempt to set 'rownames' on an object with no dimensions
Calls: SCTransform -> do.call -> vst -> get_model_pars -> rownames<-
  Execution halted

**Comment by timoast** [comment]
As stated in the previous issue, you need to log-normalize the RNA data. Here you're still trying to run SCTransform. `LogNormalize` is not one of the options for the `method` argument in `SCTransform`. See the vignette here for an example of how to do this analysis: https://satijalab.org/signac/articles/pbmc_vignette.html#integrating-with-scrna-seq-data-1

**Comment by bassanio** [comment]
@timoast  : cell identities for my RNA data is done using reference mapping to PBMC. and in the pipeline :https://satijalab.org/seurat/v4.0/reference_mapping.html they ask to do SCTransform and can I change that?

**Comment by timoast** [comment]
How you define cell identities in the RNA dataset is separate to how you perform scATAC/ scRNA integration

**Comment by bassanio** [comment]
@timoast :Sorry I didn't understood .  I  used the reference based method to identify the cells and to do so the vignettes want to use the SCT as the reference is normalized using SCT . Also in the[ Integration-scrna-seq-data ](https://satijalab.org/signac/articles/pbmc_vignette.html#integrating-with-scrna-seq-data-1)the identifies of RNAseq  data is done [manually](https://github.com/satijalab/Integration2019/blob/master/preprocessing_scripts/pbmc_10k_v3.R) . So does that mean I should not use the [ Mapping to multimodal reference datasets](https://satijalab.org/seurat/v4.0/reference_mapping.html) for RNAseq data?
