### ISSUE TITLE
Hi, I have just stared using Seurat v4.0 and I'm having trouble with the CreateSeuratObject command. The error message reads: Error in CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3,  :    could not find function "CreateSeuratObject"      Could you please help me troubleshoot this one?

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#3798]
Issue with CreateSeuratObject

**Comment by nikita421** [comment]
Hi, I have just stared using Seurat v4.0 and I'm having trouble with the CreateSeuratObject command. The error message reads: Error in CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3,  :    could not find function "CreateSeuratObject"      
Could you please help me troubleshoot this one?

**Comment by bassanio** [comment]
Have you loaded Seurat after successful installation. Try running the below command
```
library(Seurat)
pbmc3k <-CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3)
```
if the above didn't worked . run below command and post here
```
sessionInfo()
```
P.S: it will be great if you can post the tittle in comment session and comment as tittle
