### ISSUE TITLE
integrate the different batches multimodal single-cell data

### ISSUE THREAD

**Issue by zh-Bian** [satijalab/seurat#3799]
could I use FindIntegrationAnchors() function to integrate the different batches single cell data, which had been used Weighted Nearest Neighbor Analysis to combine the RNA and ADT ? If  I could, whether the progress for integrate is using WNN to combine the data for each batch, and then use FindIntegrationAnchors() to integrate the different seurat.obj togerther? If not, could you please give me some advice for integrate the different batch multimodal single cell data. Thank  you!  @troels @mxposed @zeehio @smoe @maximilianh

**Comment by yuhanH** [comment]
Hi, 
You can integrate your RNA and ADT data by the integration anchor work flow separately.
Then, you will have an integrated RNA assay and integrated protein assay. You can apply WNN method to these two integrated assays by constructing integrated RNA PCA and integrated ADT PCA.
