### ISSUE TITLE
Suggestion: scale bar for the inidividual-gene-expression "FeaturePlot" plots

### ISSUE THREAD

**Issue by alexgraehl** [satijalab/seurat#38]
Hi!

I've been making a lot of use of the "FeaturePlot(...)" function to show expression of specific genes in various cells.

I notice that, as far as I can tell, the results are SCALED so that the gene's highest-expression-cell is shown as the maximum color (e.g., "red").

So the brightest possible red in one gene (like "GAPDH") might be extremely high (thousands of reads), whereas a red in another gene might be only a few dozen reads.

I would like to suggest that a "legend" color bar would be extremely useful for getting a sense of the actual expression values involved! I was unfortunately not able to figure out a reasonable way to add this option, although I suspect it would probably involve some additions to the "SingleFeaturePlot(...)" function in Seurat.R (https://github.com/satijalab/seurat/blob/master/R/seurat.R).

 Alex

**Comment by andrewwbutler** [comment]
Good suggestion! The ability to add the scale bar is now in the latest version (1.4.0.8). Just set the parameter `no.legend = FALSE. `
