### ISSUE TITLE
Dotplot code issue

### ISSUE THREAD

**Issue by guillemsanchezsanchez1996** [satijalab/seurat#3801]
Hello,

I would like to generate a figure like this with the dotplot function[...]

![dotplot](https://user-images.githubusercontent.com/59885051/101382581-68e66680-38b8-11eb-9bab-bf96a3c37704.PNG)

[...]with the empty circle and use the viridis scale to fill it. I think that a simple scale_fill does not work and I have to slightly modify the dotplot function (the part of ggplot // geom_point) to be able to generate this type of graph. 

I am really new to this and I have tried modifying your code for the dotplot function. I just did this minor change:
geom_point(mapping = aes_string(shape = 21, colour = "black", size = 'pct.exp', fill = color.by, stroke = 1))

The problem is that R does not recognize the "% II% " character that you use to specify the assay in the dotplot function...

1) Any suggestions regarding the code?
2) Is there an easiest way to generate this plot? 

Thanks in advance,

Guillem

**Comment by ktrns** [comment]
Hi @guillemsanchezsanchez1996, 

I was about to submit an issue with regard to the DotPlot function and saw your post. What exactly is your question? Isn't the DotPlot function already doing what you'd like to do? Or you are saying that you'd like to use another colour scheme?

I am just tried this: 
```
Seurat::DotPlot(sc, features=genes) + 
        scale_colour_gradient2(low="steelblue", mid="lightgrey", high="darkgoldenrod1")
```
and it works. Might try this or `scale_colour_gradientn`?

Best wishes
Katrin

**Comment by ktrns** [comment]
Also see issue #3807. 

Best wishes
Katrin

**Comment by guillemsanchezsanchez1996** [comment]
> Hi @guillemsanchezsanchez1996,
> 
> I was about to submit an issue with regard to the DotPlot function and saw your post. What exactly is your question? Isn't the DotPlot function already doing what you'd like to do? Or you are saying that you'd like to use another colour scheme?
> 
> I am just tried this:
> 
> ```
> Seurat::DotPlot(sc, features=genes) + 
>         scale_colour_gradient2(low="steelblue", mid="lightgrey", high="darkgoldenrod1")
> ```
> 
> and it works. Might try this or `scale_colour_gradientn`?
> 
> Best wishes
> Katrin

Dear Katrin,

Thank you for your answer and suggestion for 3 color scales! But I don't have a problem with the colour scale, in my case I want to fill the dots from the legend with white color and then fill those dots with the colour scale (like in the figure i added at the beginning of this issue: white dot with black line as border and fill them with the scale colour). To do this change I think we should modifiy the ggplot function contained in the seurat dotplot function. I'm asking if somebody knows how to do this in a simple way or knows a way to change the dotplot code to generate the modified plot that I want.

Best,

Guillem

**Comment by ktrns** [comment]
So the difference to the original `DotPlot` is that you want a black outer line to the dots, and you want the dots in the legend to be white rather than black? 

Sounds like you have to play around with the `ggplot` object, first to get a black outline for the dots inside the DotPlot, and second to get the according dots in the legend. 

How about these ones?
https://stackoverflow.com/questions/10437442/place-a-border-around-points
https://stackoverflow.com/questions/19506630/control-point-border-thickness-in-ggplot

**Comment by tilofreiwald** [comment]
@guillemsanchezsanchez1996 this is what I used to replicate the design above in case it helps:

````R
DotPlot(seu, features = markers) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="magma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))
````

**Comment by todaroroad** [comment]
> @guillemsanchezsanchez1996 this is what I used to replicate the design above in case it helps:这是我用来复制上面的设计的，以防有帮助：
> 
> ```r
> DotPlot(seu, features = markers) +
>   geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
>   scale_colour_viridis(option="magma") +
>   guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))
> ```

you 
S
A
V
E
me
bro
