### ISSUE TITLE
"'x' must be atomic" error when finding integration anchors using reference dataset from object.list

### ISSUE THREAD

**Issue by parkmd0522** [satijalab/seurat#3803]
Hello Seurat team!

I'm getting the same error when I'm attempting to run FindIntegrationAnchors using the ‘Reference-based’ integration option on a set of samples following SCTransformation

`> immune.anchors <- FindIntegrationAnchors(object.list = immune.list, normalization.method = "SCT", anchor.features = immune.features, reference = reference_dataset, verbose = TRUE)
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
> traceback()
6: stop("'x' must be atomic")
5: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4: sort.default(x = reference)
3: sort(x = reference)
2: unique(x = sort(x = reference))
1: FindIntegrationAnchors(object.list = immune.list, normalization.method = "SCT", 
       anchor.features = immune.features, reference = reference_dataset, 
       verbose = TRUE)`

_Originally posted by @awaickm1 in https://github.com/satijalab/seurat/issues/1296#issuecomment-533547051_

**Comment by andrewwbutler** [comment]
Hi,

What is `reference_dataset` here? It should be set to the _index_ of the object(s) in the `immune.list` you want to use as the reference.

**Comment by parkmd0522** [comment]
reference_dataset was defined as a subset of the immune.list object.
The same format was followed as in the vignette (https://satijalab.org/seurat/v3.2/integration.html)
a.k.a. reference_dataset <- which(names(pbmc.list) == "10x Chromium (v3)")

In place of "10x Chromium (v3)", I replaced it with the IDs that I wanted to use as the reference.

**Comment by andrewwbutler** [comment]
Hmm, are you able to share a reproducible example?
