### ISSUE TITLE
Allow a diverging colour gradient for DotPlot, rather than a two colour gradient

### ISSUE THREAD

**Issue by ktrns** [satijalab/seurat#3807]
Hi there, 

I was wondering if it would make sense to modify the DotPlot function such that we provide a  diverging 3-colour gradient if `scale=TRUE`. Values go from `-` to `+` but currently the gradient allows for 2 colours, which is a bit confusing. 

I have solved this for now by adding 
```
scale_colour_gradient2(low="steelblue", mid="lightgrey", high="darkgoldenrod1")
```

to the ggplot2 object, which helps the interpretation of the plot. 

Best wishes
Katrin

**Comment by timoast** [comment]
Hi Katrin, the solution you've suggested here is the correct one, and was part of our motivation in returning `ggplot` objects that could be modified by the user. I don't think we need to change the default in this case, and users can modify the plots if they want a different color scale
