### ISSUE TITLE
FindIntegrationAnchors - Warning

### ISSUE THREAD

**Issue by parvathisudha** [satijalab/seurat#3808]
I am integrating 20 Seurat objects using SCTransform. While running the FindIntegrationAnchors, I am getting a warning message. Will this affect the analysis?

`object.anchors <- FindIntegrationAnchors(object.list = object.list, normalization.method = "SCT", anchor.features = object.features, verbose = FALSE)`
Warning messages:
1: In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
2: UNRELIABLE VALUE: Future (‘future_lapply-1’) unexpectedly generated random numbers without specifying argument '[future.]seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option 'future.rng.onMisuse' to "ignore". 

Thanks
Parvathi.

**Comment by timoast** [comment]
These warnings can be ignored (see #3622)

**Comment by natalkon** [comment]
Can this warning also be ignored after those steps of fast integration using reciprocal PCA (RPCA) pipeline (Seurat version ‘4.1.1’)?

```
DefaultAssay(samples_integrated) <- "integrated"
samples_integrated <- ScaleData(samples_integrated, verbose = FALSE)
samples_integrated <- RunPCA(samples_integrated, npcs = 50, verbose = FALSE)
samples_integrated <- RunUMAP(samples_integrated, reduction = "pca", dims = 1:50)
samples_integrated <- FindNeighbors(samples_integrated, reduction = "pca", dims = 1:50)
samples_integrated <- FindClusters(samples_integrated, resolution = 0.5)
```

**Comment by KoichiHashikawa** [comment]
@timoast 
Could you help confirm the question from @ilcink ?
I wonder the same question.

Thanks!
