### ISSUE TITLE
IntegrateData error

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#3809]
Hi,

I am really a bit desperate right now. I am running the Seurat Integration and Label transfer pipeline with method RPCA (https://satijalab.org/seurat/v3.2/integration.html) exactly as posted in the vignette. I have 12 samples. The script used to work fine for another object.

However, after:
data.int <- IntegrateData(anchorset = anchors, dims = 1:30)

I am getting:
Building integrated reference
Merging dataset 11 into 4
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Warning: Adding a command log without an assay associated with it
  |                                                  | 0 % ~calculating  Integrating dataset 1 with reference dataset
Error in GetAssayData(object = object, assay = umi.assay, slot = "counts")[new_features,  :
  no 'dimnames' attribute for array

I have the impression, it tries to access features that are not present in an assay. However, all objects are scaled and all anchor.features are in each obj@assays$RNA@scale.data, data and counts slots. RNA is also the active assay.

Any suggestions? 
Thanks, best, Christian

**Comment by balthasar0810** [comment]
I solved the issue in the following way:
I calculated SCTransform before the data integration steps on all samples (I don't need this for data integration but other downstream processes...). However, I set the default assay to RNA afterwards and followed the vignette. It seems to me that IntegrateData somehow wanted to access the scale.data slot of SCT assays with features which was not present. I think this because everything worked fine after I just skipped SCTransform before. This is just my hypothesis for this problem, I am not sure...

**Comment by torkencz** [comment]
Hi balthasar0810,

Yeah that was probably it. You can also specify which normalization you want to use in FindIntegrationAnchors normalization.method = c("LogNormalize", "SCT"). In that case you might not have to skip the SCTransform. Let me know if that works.

**Comment by Xicici-Yan** [comment]
@torkencz
Hi torkencz, I specified normalization.method, but it does not work.
```
Error in GetAssayData(object = object, assay = umi.assay, slot = "counts")[features_to_compute, : no 'dimnames' attribute for array
```
my code is 
```
hepatocyte.re.list <- lapply(X=hepatocyte.re.list, FUN = function(x) {
    x<-RunPCA(x,verbose=FALSE)
}) 
Anchors.default <- FindIntegrationAnchors(
  object.list = hepatocyte.re.list,
  reference=c(1,4),
  reduction="rpca",
  dims=1:30,
  normalization.method = 'SCT',
  anchor.features = ftr2anchor,
  k.anchor = 5,
  k.filter = 300,
  k.score = 30)
hepatocyte.CCA <- IntegrateData(
  anchorset = Anchors.default,
  normalization.method = 'SCT',features.to.integrate=SCTanchor2
)
