### ISSUE TITLE
Making custom reference atlas to use MapQuery (Advice on FindVariableFeatures & SCT)

### ISSUE THREAD

**Issue by acousticus** [satijalab/seurat#3810]
Dear Seurat Developers,

Firstly thank you for the excellent package and vignettes.
I would like to make my own 'reference atlas' by integrating 2 (or or more) reference datasets. 
I would then like to use this to map cell labels onto a query dataset (which is also an SCT transformed integrated object)
The slimmed down script below (based on a few vignettes) runs fine until: FindTransferAnchors
At which point I see the error:
"Error: Cannot find 'pca' in this Seurat object"
The code runs successfully if I uncomment "#reference <- FindVariableFeatures(object = reference)"
However, from posts I've read (eg these https://github.com/satijalab/seurat/issues/2778, https://github.com/satijalab/seurat/issues/3716,    https://github.com/satijalab/seurat/issues/2172), I understand you do not recommend running FindVariableFeatures on an SCT integrated object?
    
My questions are: 
1. What is your recommended best practice in generating a custom reference atlas from multiple datasets (eg. using SCT) for use with Seurat V4's 'MapQuery' to annoate a query dataset?
2. If you recommend to avoid performing FindVariableFeatures on the SCT derived reference 'atlas', is there an alternative method you would recommend?
3. Is there an alternative recommended way to solve the above problem without uncommenting "reference <- FindVariableFeatures(object = reference)." 

Many thanks
```
#remotes::install_github("satijalab/seurat", ref = "release/4.0.0")
library(Seurat)
library(tidyverse)

atlas_1 <- read_rds(atlas_1_file)
atlas_2 <- read_rds(atlas_2_file)

to_integrate <- list(atlas_1 = atlas_1, atlas_2 = atlas_2)
to_integrate <- map(to_integrate, SCTransform, method = 'glmGamPoi') 

to_integrate_features <-SelectIntegrationFeatures(object.list = to_integrate)
to_integrate <- PrepSCTIntegration(object.list = to_integrate, anchor.features = to_integrate_features)
to_integrate_anchors <- FindIntegrationAnchors(object.list = to_integrate, normalization.method = "SCT", anchor.features = to_integrate_features, dims = 1:30)

reference <- IntegrateData(anchorset = to_integrate_anchors, normalization.method = "SCT") 
DefaultAssay(object = reference) <- 'SCT'
#reference <- FindVariableFeatures(object = reference)
reference <- RunPCA(object = reference)
reference <- FindNeighbors(object = reference)
reference <- FindClusters(object = reference)
reference <- RunUMAP(object = reference, dims = 1:50, return.model=TRUE)

query_dataset <- read_rds(query_dataset_file)
DefaultAssay(object = query_dataset) <- 'SCT'

common_features = all_common_genes <- lapply(list(reference,query_dataset), row.names) %>% Reduce(intersect, .) 

anchors <- FindTransferAnchors(
  reference = reference,
  query = query_dataset,
  normalization.method = "SCT",
  reference.reduction = "pca",
  dims = 1:50,
  features = common_features
)
```

**Comment by satijalab** [comment]
1. We recommend following the integration vignettes online, you can then use the integrated object as a reference for MapQuery. We are adding additional examples very soon (perhaps as soon as later today, on the label transfer vignette).

2. You can use SelectIntegrationFeatures as you do above to identify features that are consistently variable across datasets. You could also take the union of variable features if you wish.

3. The issue seems to be that you are using the SCT assay as the default reference assay instead of the integrated assay.

**Comment by acousticus** [comment]
Thanks very much for your advice

To try and make my initial question brief I hadn't gone in to detail about how I arrived at the code:
I used the following vignette to create an integrate reference atlas: https://satijalab.org/seurat/v3.2/integration.html#sctransform. 
The only deliberate modification I made (as far as I'm aware) was to add in: 
```
method = 'glmGamPoi'
```

I used this vignette for label transfer with MapQuery: 
https://satijalab.org/seurat/v4.0/reference_mapping.html

I had originally tested the script with the default assay as "Integrated" in both the reference and query datasets, which gave the following error when trying to run FindTransferAnchors():
```
Error: Given query.assay (integrated) has not been processed with SCTransform. Please either run SCTransform or set normalization.method = 'LogNormalize'.
```
To try and solve this I therefore switched the default assay to "SCT" in both reference and query datasets which then gave the error described above in i the initial post: 
```
Error: Cannot find 'pca' in this Seurat object.
```

Is there a way to ammend my FindTransferAnchors() call so it is able to identify the SCT assay while in integrated mode?

Thanks
