### ISSUE TITLE
Setting min.cells and min.features in CreateSeuratObject

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#3812]
Hi there, 

I know that min.cells sets the threshold for genes to only take the genes that are present in at least a specified number of cells.
And, min.features sets the thresholds for cells that express at least a specified number of genes. 

But would any one mind explaining the rationale to choose the values for min.cells and min.features?

I tried to make histograms of the 4 values below to hopefully set the thresholds:
counts_per_cell (column sum),
genes_per_cell (column sum for only when the count is >0),
counts_per_gene (row sum), and 
cells_per_gene (row sum for when the count >0)

I also ranked each cell by the number of genes expressed by cell. Does anyone have another idea how to set these thresholds?

Thank you very much for your help!

**Comment by timoast** [comment]
The values to choose will depend on the dataset in question. Generally, I use a lower value (retain more cells and features) when creating the object, and subsequently filter cells based on where they fall on the count distribution as well as other QC metrics
