### ISSUE TITLE
How to get the list of gene names in the anchors which was used to integrate data sets?

### ISSUE THREAD

**Issue by torumatsuura** [satijalab/seurat#3813]
To whom it may concern,
I'm using "CellCycleScoring" for other gene sets to analyze "Integrated data". Since "features" in the integrated gene sets are only genes which were used as "anchors" for data integration, most of genes in the gene sets are not present in the object. The result is like below.

> tongue_all.integrated <- CellCycleScoring(tongue_all.integrated, s.features = morning.genes, g2m.features = night.genes, set.ident = TRUE)
Warning: The following features are not present in the object: Arntl, Clock, Nfil3, Cry1, Rorc, E1f2ak1, Eif2b2, Cars2, Gars, Ears2, Qars, Yars, Sars, Rpl34, Rps23, Rps24, Rps27, Mrpl52, Ppp1r11, Ppp2r5a, Ppp2r5b, Prkab1, Gapdh, Prkaa1, Prkaca, Aldoa, Cox4i1, Ube3b, Gdi1, not searching for symbol synonyms
Warning: The following features are not present in the object: Nr1d1, Nr1d2, Dbp, Per1, Per2, Per3, Tef, Cry2, Eif2b3, E1f4a3, E1f4g1, E1f4a1, Eif5, Eif6, Rpl5, Rpl14, Rpl9, Rpl8, Rps6kb2, Rps6, Rps5, Mrpl12, Mrpl20, Naca, Sumo1, Cenpb, Rad50, Cox15, Anxa6, Bloc1s3, Ap4b1, Mfsd3, Slc15a4, Slc25a26, Slc25a38, Slc35f5, Csf1, not searching for symbol synonyms

To prevent this, I'd like to pick features from genes in the anchors. Is there any way to show or output the gene names in "anchors"? I tried like below, but it didn't work. Any help would be appreciated. Best,

> md0_12 <- tongue_all.anchors
> data_to_write_out <- as.data.frame(as.matrix(md0_12))
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector

**Comment by torkencz** [comment]
Hi torumatsuura. 

You should be able to write out the features present in anchors via md0_12@anchor.features. You might also want to look at gene symbol synonyms. Let me know how it goes.

**Comment by torumatsuura** [comment]
It works！ Thank you for your advice.
