### ISSUE TITLE
List of hashing barcodes from demultiplexing pipeline

### ISSUE THREAD

**Issue by ibseq** [satijalab/seurat#3814]
hi all, 
given the demultiplexing pipeline, how can I get a list of the samples barcodes separated by hashing antibodies? including duplets and singlets?

thanks
ibseq

**Comment by timoast** [comment]
The sequence of the hashing barcode needs to be known ahead of time. It should be recorded in the experiment which barcode was used for which sample

**Comment by ibseq** [comment]
Hi 
I know this,but the demultiplexing pipeline is splitting the samples for each hashing antibodies: how can I get the separated samples list? I did the pipeline and I can see the plots showing my three samples , but I need a list where the original list (3 samples all together ) has been split into the three samples. I hope I’m making sense !

Thanks! 
Irene

**Comment by timoast** [comment]
I don't 100% understand what you're asking, but the `HTODemux` function will add a `HTO_maxID ` variable to the object metadata containing the results of the HTO demultiplexing (shown in the [vignette](https://satijalab.org/seurat/v3.2/hashing_vignette.html))

**Comment by ibseq** [comment]
Thanks Tim
maybe I didn’t explain clearly myslef 
For example given the R command below 
 Idents(pbmc.hashtag) <- "HTO_classification.global"
VlnPlot(pbmc.hashtag, features = "nCount_RNA", pt.size = 0.1, log = TRUE)
how can I save on my desktop a cvs file listing barcodes corresponding to the different populations? Isn’t the final goal to be able to identify the samples based on hashing antibodies? But I can only see a graph using this pipeline and I was wondering how can you also have a cvs showing for example HTO-A: list of barcodes....HTO-B: list of barcodes ...
Or to make simple : how can I extrapolate the demultiplexed samples from seurat

I hope it makes sense ! 
ibseq

**Comment by timoast** [comment]
I see, you're asking how to extract the metadata from a Seurat object. This can be done using the `[[` operator, for example `md <- object[[]]`. That will return a dataframe that you can write to file using functions in R (eg, `write.table`).

**Comment by ibseq** [comment]
Thanks Tim. 
Any chance you can give the example based on the published  pipeline ?

Thanks
ibseq

**Comment by timoast** [comment]
An example of how to write a dataframe to file? I think you can find that in the documentation for `write.table`

**Comment by ibseq** [comment]
Thanks Tim
my mistake , I wasn’t using $ after my object 
Sorted now 

ibseq
