### ISSUE TITLE
VlnPlot in Seurat

### ISSUE THREAD

**Issue by kumarRBK** [satijalab/seurat#3815]
When creating VlnPlot it shows different results than my DEG list (specifically avg_logFC). I would like to know which values are used by VlnPlot in Seurat?

For example : the Below data is from my DEG result between KO and WT but when I make VlnPlot show the difference between these genes expression in KO/WT, it shows entirely different. I don't know where I made mistake.

  Gene| p_val | avg_logFC | pct.1 | pct.2 | p_val_adj
-- | -- | -- | -- | -- | --
Mt1 | 8.43E-87 | 1.37847681 | 0.912 | 0.73 | 2.62E-82
Mgp | 1.17E-77 | 1.74844464 | 0.72 | 0.416 | 3.63E-73
Gsn | 5.30E-69 | 1.27900544 | 0.675 | 0.344 | 1.64E-64

code used: VlnPlot(immune.combined1,features = c('Mt1','Mgp','Gsn'), split.by = 'orig.ident')
output shown below
[Rplot02.pdf](https://github.com/satijalab/seurat/files/5679970/Rplot02.pdf)

Dear All, Please help in this regard. Your help is greatly appreciated. Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

Can you please post the code used to generate the DEG too?

Thanks,
Sam

**Comment by timoast** [comment]
I don't think there's anything wrong here, this is just a difference between visual perception and the returned statistic

**Comment by kumarRBK** [comment]
Thanks @timoast , But when we want to draw a VlnPlot it shows an entirely different output. I just wonder which data VlnPlot takes as input. Is there any other possible way to exhibit expression differences between KO and WT? Please suggest. Thank you very much!

**Comment by timoast** [comment]
I wouldn't describe the output as "entirely different." By default VlnPlot uses data stored in the `data` slot in the assay, which typically contains normalized counts

**Comment by kumarRBK** [comment]
Thanks @timoast. I meant the plot is not exactly described avg.Log2FC from DEG.
