### ISSUE TITLE
Loss of features with WNN analysis on integrated data 

### ISSUE THREAD

**Issue by shefalipatel7** [satijalab/seurat#3816]
Hi,

I wanted to use WNN analysis on my integrated data and followed the suggestion from issue #3645 I followed the integration workflow for my RNA and ADT assay. I then applied the WNN method to those integrated assays. However, I am noticing that I lose many key RNA and ADT features in the integrated assay (such as I cannot find CD3 or CD4 in T cell data, which is odd). I have used Seurat v3 with this data and did not encounter this issue, so I'm wondering if there is a key step I am missing with the WNN analysis portion that could be leading to this loss of features. I attached a part of my code where I perform WNN analysis on the integrated data. The steps for integration I used are the exact same commands as those provided in the vignette. Thank you for your help! 

```
DefaultAssay(all.integrated) <- 'RNA'
var <- FindVariableFeatures(all.integrated)

DefaultAssay(all.integrated) <- 'RNA.integrated'
all.integrated <- ScaleData(all.integrated, features=var@assays$RNA@var.features)
all.integrated <- RunPCA(all.integrated, features=var@assays$RNA@var.features)

DefaultAssay(all.integrated) <- 'ADT'
var <- NormalizeData(all.integrated)
VariableFeatures(all.integrated) <- rownames(all.integrated[["ADT.integrated"]])

DefaultAssay(all.integrated) <- 'ADT.integrated'

all.integrated <- ScaleData(all.integrated) 

all.integrated <- RunPCA(all.integrated, reduction.name = 'apca')
```

**Comment by yuhanH** [comment]
Hi,
You may not include those genes in your integration process. 
Could you provide your RNA and ADT integration scripts?
