### ISSUE TITLE
How to find marker genes characteristic for a group of specified identities vs another identity?

### ISSUE THREAD

**Issue by natalkon** [satijalab/seurat#3817]
Dear Seurat Team, 
I would like to ask, how to find marker genes, equally present in all x groups vs another group:

The object gets 5 metadata subgroups:
```
obj <- RenameIdents(obj, 
                     "cells_expressing_Genes_LMN"= "group1", 
                     "cells_expressing_Genes_XYZ" = "group2" ,
                     
                     "cells_expressing_Gene_C" = "group3",                       
                     "cells_expressing_Gene_D" = "group4",
                     "cells_expressing_Gene_E" = "group5")
obj[["group"]] <- Idents(object = obj)
```

Seurat cluster is selected:
```
Idents(obj)<-"seurat_clusters"
obj<-subset(obj, idents=1)
```

This function "FindMarkers"
```
DefaultAssay(obj) <- "RNA"
obj.markers <- FindMarkers(obj, ident.1 = c("group3", "group4", "group5"), ident.2 = "group2")
```
would produce genes that make group 3/4/5 different from group 2, but after making feature plots split.by "group" it  becomes clear, that most of the differences come strongly only from one of the groups (group 3 or 4 of 5 separately), but not from all three (3, 4, 5) together vs group 2.

How to find genes that make group 3/4/5 different from group 2, so that these genes are present in each of groups 3, 4, 5 and absent in group 2?

It would be nice to have something like a FindConservedMarkers function
```
DefaultAssay(obj) <- "RNA"
Idents(obj)<-"seurat_clusters"
obj.markers <- FindConservedMarkers(obj, ident.1 = 1, grouping.var = "group", verbose = FALSE)
```
but here selecting the grouping.var = "group" would find conserved markers for all 5 groups, 
whereas I would need it only for group 3, 4, 5 compared to group 2.

Thank you!

**Comment by k3yavi** [comment]
Hi @natalkon ,

Thanks for reaching out.  One way to achieve what you want is to use the `FindMarkers` function with each combination of the groups (3/4/5) against group 2 and later take the intersection of the features marked as DE by each group-combination. Another potential way would be to use the `FindConservedMarkers` function on a modified Seurat object with only the subset of the relevant groups of interest. Hope it helps !

**Comment by natalkon** [comment]
Thank you, @k3yavi !

I already tried the second option that you have suggested like that

```
Idents(obj)<-"group"`
obj.subset<-subset(comb, idents=c("group3", "group4", "group5", "group2"))
obj.subset.markers <- FindConservedMarkers(obj.subset, ident.1 = c("group3", "group4", "group5"), grouping.var = "s", verbose = FALSE)
```
P.S. "s" is a single variable present in all four groups (not like stim/ctrl, but just one state), so that I get a 
'Warning: Only a single group was tested'
then a list of genes.
As I wrote above, I have checked those ones selected with log2FC>1 one by one in feature plots split by group,
and each of them comes from either group 3, or group 4 or group 5 versus group 2.

Does it mean that these three groups are very heterogeneous and have nothing in common that makes them altogether different from group 2?

**Comment by k3yavi** [comment]
Hi @natalkon ,

I was thinking in the lines of 
```
FindConservedMarkers(obj.subset, ident.1 = c("group2"), grouping.var = "s", verbose = FALSE)
```

but if this doesn't work you can also try taking the intersection of the features by performing FindMarker on each combination of the groups.

**Comment by natalkon** [comment]
@k3yavi thank you!
