### ISSUE TITLE
What are the advantages and disadvantages of the tests for differential expression provided in FindAllMarkers function? 

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#3820]
Hi, Seurat lab,

Thank you so much for your beautiful work.

I would like to ask, what is the major difference among those test methods (eg. wilcox, roc ) provided in FindAllMarkers function? 

First, I see most of users chose the default Wilcoxon test method to identify differentially expressed genes among cluster, while a few people (in some literatures) selected the “roc” method to do this without explaining the reason. In your [past vignette](https://satijalab.org/seurat/seurat_clustering_tutorial_part2.html), you described that ROC test, though not a statistical test, is often very useful for finding clean markers. Did you compare this method with others? But when I compared ROC and wilcox test on my single cell data, I actually couldn’t find the obvious advantage of ROC method in finding clean markers than wilcox.

Second, what are the advantages and disadvantages of the tests for differential expression? And how to choose a suitable method based on the aim or data type of users? 

Could you clarify it and give me some advice? Please forgive me for my ignorance in statistics.

Hope for your answer.

**Comment by liuxl18-hku** [comment]
I am also interested in this topic, but also think that Seurat guys may not be the right person to do the comparison as different methods have their own strong/weak points, and may apply to different contexts. For example, when you have some confounding factors to take care, LR method may be a good option.

Also there was a comprehensive comparison for a wide range of sc DE methods published in Nature Methods: https://www.nature.com/articles/nmeth.4612

Hope it is helpful to you.

bless~
Xingliang

**Comment by Sophia409** [comment]
@liuxl18-hku Hi, really thank you for your answer. I will read this paper and search similar ones for a comparison.
