### ISSUE TITLE
Read10X - invalid dimnames given for “dgTMatrix” object

### ISSUE THREAD

**Issue by bmanzato** [satijalab/seurat#3821]
I'm trying to load the output of scrna alignment into a datamatrix with `Read10X`. 

`datamatrix <- Read10X(data.dir = data_dir , gene.column = 1, unique.features = TRUE)`

`Error in dimnamesGets(x, value): invalid dimnames given for “dgTMatrix” object
Traceback:

1. Read10X(data.dir = data_dir, gene.column = 1, unique.features = TRUE)
2. `colnames<-`(x = `*tmp*`, value = cell.names)
3. `dimnames<-`(`*tmp*`, value = dn)
4. `dimnames<-`(`*tmp*`, value = dn)
5. dimnamesGets(x, value)
6. stop(gettextf("invalid dimnames given for %s object", dQuote(class(x))), 
 .     domain = NA)`

Here the files that I am using:

head barcodes.tsv 
0
1
2
3
4
5
6
7
8
9

head matrix.mtx 
%%MatrixMarket matrix coordinate real general
273	142446	8021967
1	2	13.8348
1	7	2.32566
1	8	5.55682
1	9	15
1	10	116
1	11	93.9063
1	12	9.54031
1	14	59.3033

head genes.tsv 
ENSMUST00000000266.8
ENSMUST00000000514.10
ENSMUST00000000834.3
ENSMUST00000001027.6
ENSMUST00000001166.13
ENSMUST00000001171.12
ENSMUST00000001172.11
ENSMUST00000001284.12
ENSMUST00000001339.5
ENSMUST00000001724.11 

From what I understand from documentation file formats are correct.

I would greatly appreciate if someone could indicate me what I am missing

**Comment by k3yavi** [comment]
Hi @bmanzato ,

> From what I understand from documentation file formats are correct.

I am assuming you checked that the number of lines in the file `barcodes.tsv` is 273 and `genes.tsv` is 142446 ? I can't access the drive link you sent earlier.

**Comment by bmanzato** [comment]
Yes, the number of lines is 273 and 142446.

**Comment by k3yavi** [comment]
Over the top of my head, things should work. I might need access to the data to help .

**Comment by bmanzato** [comment]
I've shared an item with you:

matrix.mtx
https://drive.google.com/file/d/1kBp1yzwZVsxgE1_YyQVQGImAxEEgOuaX/view?usp=sharing&invite=CLGcmOcE&ts=5fda1a0c

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by bmanzato** [comment]
Can you open them now?

**Comment by bmanzato** [comment]
matrix.mtx
<https://drive.google.com/file/d/1jf7tnkj4yu6tPxMW39nzowwRCix2w94b/view?usp=drive_web>

**Comment by k3yavi** [comment]
Got it, thanks

**Comment by k3yavi** [comment]
Can you also share the genes and the barcodes file ?

**Comment by bmanzato** [comment]
Hi, do you have any news about the potential problem regarding the data /
file formats? As I mentioned, I solved using Convert from h5ad to h5Seurat
and then I loaded it with Load5Seurat, and it seems to create the Seurat
objects correctly. Now that I want to merge multiple seurat objects I get
another error that I really can't solve. I was thinking that maybe if I
create the Seurat object in another way (with Read10X) maybe this error
won't happen, so it would be very helpful if you have found something in
the meantime? Let me know, thank you for your time

**Comment by k3yavi** [comment]
https://github.com/satijalab/seurat/issues/3821#issuecomment-746387163

The mtx file looks Ok @bmanzato , I think it's something with the the other files -- genes or barcodes file. Like I said above, it'd be great if you can forward those files as well.

**Comment by bmanzato** [comment]
Hi, sorry I thought I sent them already. You should see them now?

**Comment by k3yavi** [comment]
I am not sure I understand, see them where ? The link you shared previously has just the mtx file.

**Comment by bmanzato** [comment]
barcodes : https://drive.google.com/file/d/1Gpk6sbQGWCoox01Ox3twW1zSqC22jzDi/view?usp=sharing

genes : https://drive.google.com/file/d/1gQGMn_pYTYz5JZcC27xZw55JyBQ0pG0P/view?usp=sharing

**Comment by k3yavi** [comment]
All right, two things.
1).  I am not quite sure how was the `mtx` file generate but the format of the file is barcode-by-gene where the Read10x (like 10x files) expects gene-by-barcode format. If you transpose the matrix it's working.
2). The gene file has only one field so like `Read10X("~/test/", gene.column = 1)` you might have to explicitly specify the index of the column in the genes file.

Once you fix the above two things, it should work.

**Comment by liuweihanty** [comment]
@k3yavi Thanks for the answer! I had the same question as my gene file also just contain one field(one column with gene names), what do you mean by "**2). The gene file has only one field so like Read10X("~/test/", gene.column = 1) you might have to explicitly specify the index of the column in the genes file.**"?  Thanks!

**Comment by bclopesrs** [comment]
Hi everyone: I'm running the code below and I'm getting the following error:
**### Error in dimnamesGets(x, value) : invalid dimnames given for “dgTMatrix” object**
Does someone have any ideia to fix that? I appreciate!


**### CODE**
barcodes <- read.csv2(file = "/ihome/myname/GSE158380_cells.csv.gz",
                      header = F)

features <- read.csv2(file = "/ihome/myname/GSE158380_features.csv.gz",
                     header = F)

mtx <- Matrix::readMM("/ihome/myname/GSE158380_raw_count_matrix.mtx.gz")

colnames(mtx) <- barcodes[,1]
rownames(mtx) <- make.unique(features$V1)
mtx[1:5, 1:5]


### **OUTPUT**
5 x 5 sparse Matrix of class "dgTMatrix"
              
[1,] . . . 3 .
[2,] . . . . .
[3,] . . . . .
[4,] . . . . .
[5,] . . . . .

**Comment by neurohugo** [comment]
I just found a partial solution of this.
barcode[1,1] was "cells"
therefore, running  
colnames(mtx) <- barcodes[-1,1]
fixed the problem. 
However, features has only 22597 rows and the matrix has 31040 rows..
