### ISSUE TITLE
ReadH5AD - object of type 'environment' is not subsettable

### ISSUE THREAD

**Issue by bmanzato** [satijalab/seurat#3822]
Hello,

I'm trying to read a h5ad format into R. The file is the output of kb_python pipeline with smartseq technology then converted to h5ad. 

`>four_cells <- ReadH5AD(file = "/Users/benedettamanzato/Desktop/LUMC/GSE115746/GSE115746_7311.h5ad")`
Pulling expression matrices and metadata
Data is unscaled
Error in file[["obs"]][] : 
  object of type 'environment' is not subsettable

From what I understand from documentation https://www.rdocumentation.org/packages/Seurat/versions/3.0.0/topics/ReadH5AD there is a difference between sparse and dense matrices. How can I "scale" the data?

and how can this
`Error in file[["obs"]][] : 
  object of type 'environment' is not subsettable` 
be solved? From what I read from another issue it has something to do with scanpy version, but I generated the file directly from kb pipeline (by adding --h5ad).

Thank you for any suggestion

**Comment by bmanzato** [comment]
and also what does it mean type 'environment' is not subsettable ?

**Comment by camerongw** [comment]
Hey, did you find a solution for this issue? I've noticed that a few others have had this problem and have offered a lot of solutions but none have worked for me so far.

**Comment by bmanzato** [comment]
Hi, no not yet @camerongw
