### ISSUE TITLE
Issue while Integrating 20 seurat objects SCT

### ISSUE THREAD

**Issue by parvathisudha** [satijalab/seurat#3823]
Hi,

I am not able to integrate 20 Seurat objects together, which is nearly 146,000 cells.  
I am using SCTransform, in Seurat 3.2.1

Can you please suggest some solutions?

Code:
```
options(future.globals.maxSize = 100000 * 1024^2)
myeloma.integrated <- IntegrateData(anchorset = object.anchors, normalization.method = "SCT", verbose = TRUE)

```

even tried: , dims = 1:pa$dims as mentioned in #1029 (Seurat3.0 Finding integration vectors: long vectors not supported yet)
Log file: 
.......
Integrating data
Merging dataset 13 17 7 5 18 1 2 into 14 4 12 20 6 8 16
Extracting anchors for merged samples
Finding integration vectors
Error in validityMethod(as(object, superClass)) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:522
Calls: source ... validObject -> anyStrings -> isTRUE -> validityMethod
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
Execution halted

**Comment by torkencz** [comment]
Hi,
This issue is discussed over here:
https://github.com/satijalab/seurat/issues/1029
You also might want to explore reference based integration or reciprocal PCA based integration.
