### ISSUE TITLE
MT percentages higher than 100%

### ISSUE THREAD

**Issue by dm8000** [satijalab/seurat#3824]
Hello Seurat team

I am trying to integrate 3 datasets with SCT transform. 2 of these data sets are raw and 1 is pre-processed. I decided to use the same pre-processing used in this third dataset after integration, which is gene number between 200 and 6,000, UMI count > 1,000 and mitochondrial gene percentage < 0.1 (the BALF dataset). I assumed as long they are pre-processed the same way this should not be an issue.

However
1. percent.mt seems to be higher than 100% in the BALF dataset
2. when I run the line

`circBALFflu.pred.integrated <- subset(circBALFflu.pred.integrated, subset = nFeature_RNA > 200 & nFeature_RNA < 6000  & nCount_RNA > 1000 & percent.mt < 10)`

the BALF dataset vanishes (because of issue 1 I assume).

the plots
https://ibb.co/BLXszyk

**Comment by torkencz** [comment]
Hi, 

I would also assume that the nCountRNA >1000 also should remove the BALD cells. You seem to be having mostly mitochondrial reads in that dataset.
