### ISSUE TITLE
-1_1 in barcode, not able to recocnize data in immunoarch

### ISSUE THREAD

**Issue by aleofifi** [satijalab/seurat#3826]
Hi , Love Seurat!

I have a problem when I do cluster with 10x data with anchoring the barcodes get a -1_1 ending instead if -1 and I can't use immunoarch for vdj analysis connected to the Seurat clustering. Is there any way you whould propose to go around this. Have trying separating the objects but doesn't seem to work?

Best regards, Andri

**Comment by k3yavi** [comment]
Hi @aleofifi ,

Is it possible for you to share the script and/or the data you are using, it'll help resolve the issue better.
