### ISSUE TITLE
Expression per FeaturePlot doesn't match expression matrix

### ISSUE THREAD

**Issue by mcsimenc** [satijalab/seurat#3827]
Hi, I'm analyzing the [data published here](https://www.biorxiv.org/content/10.1101/2020.06.29.178863v1.full) and I am looking at where certain genes are expressed in a UMAP cloud. Here is an example using `FeaturePlot(datSeurat, features = g, cols = c("lightgrey", "blue", "red"), slot = "scale.data")`:
![image](https://user-images.githubusercontent.com/7388518/102136630-7c408700-3e0e-11eb-80e5-9eefeac7f604.png)
![image](https://user-images.githubusercontent.com/7388518/102136873-d7727980-3e0e-11eb-84a8-fd269cd1d2e0.png)

It looks like the gene is moderately expressed across all cells in the dataset. However if I pull out the expression values for a particular cluster and summarize them, the numbers don't match the scale in the feature plot:
```
exprMat = datSeurat@assays$integrated@scale.data
annotations = datSeurat@meta.data$celltype.anno
gene = exprMat[which(rownames(exprMat) == "AT5G66815"), which(annotations == "Cortex")]
summary(gene)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-1.8925 -0.6000 -0.5069 -0.5076 -0.4578 10.0000 
```

As is apparent from the summary, most of the scaled expression values fall below 0, but in the feature plot most of the cells in this and most other clusters are at about 2. In contrast feature plots for other genes show mostly gray cells with expression value summaries like the one above. Does anyone know what could be going on here?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can help.  The reason is because you are supplying 3 colors to the `cols` parameter which means that everything will be binned into a 1-3 scale regardless of overall expression.  Also unless you set `order = TRUE` you are likely to be masking many points due to density of most UMAP plots.

Best,
Sam

**Comment by mcsimenc** [comment]
Hi Sam,

I don't think giving `cols` 3 colors is causing this issue because using two colors like this
```FeaturePlot(datSeurat, features = g, cols = c("lightgrey", "blue"), slot = "scale.data")```
makes a plot where most cells are shown with intermediate expression also:
[AT5G66815_Shahan_scRNAseq_featurplot_twoColor.pdf](https://github.com/satijalab/seurat/files/5713428/AT5G66815_Shahan_scRNAseq_featurplot_twoColor.pdf)

However for some genes feature plots look as expected, like this:
[AT2G28660_Shahan_scRNAseq_featureplot_threeColors.pdf](https://github.com/satijalab/seurat/files/5713433/AT2G28660_Shahan_scRNAseq_featureplot_threeColors.pdf)

**Comment by samuel-marsh** [comment]
Hi,

So for AT5G66815 that new graph actually looks like it resembles the data in the scale.data matrix (your original issue) with values around or just below zero.  What is your rationale for plotting `FeaturePlot` from the scale.data slot?

Best,
Sam

**Comment by mcsimenc** [comment]
I was under the impression that scale.data was being plotted by default so I put it in to be explicit. It does look like the values match the scale but I don't understand why the scale is blue at 0 when in the unscaled data expression for this gene in most cells is 0:
```
m = datSeurat@assays$RNA@data
a = datSeurat@meta.data$celltype.anno
gene = m[which(rownames(m) == g), which(a == "Cortex")]
summary(gene)

    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 0.00000  0.00000  0.00000  0.01323  0.00000 19.00000
```

Shouldn't the scale be gray for cells with no expression?

Thanks,

Matt

**Comment by samuel-marsh** [comment]
No scale.data is not default, see:
[https://github.com/satijalab/seurat/blob/b56d194939379460db23380426d3896b54d91ab6/R/visualization.R#L962](https://github.com/satijalab/seurat/blob/b56d194939379460db23380426d3896b54d91ab6/R/visualization.R#L962)

I don't think you really want to plot `FeaturePlot` from scale.data really.

Best,
Sam

**Comment by mcsimenc** [comment]
Ah ok, thanks. However, the feature plots look exactly the same when using the default slot.

**Comment by yuhanH** [comment]
HI, @mcsimenc 
when you set `cols`, the color scale legend is changed. But you can get the correct legend scale value without `cols` setting. ```
FeaturePlot(datSeurat, features = g,  slot = "scale.data")
```

**Comment by mcsimenc** [comment]
Thanks @yuhanH .

I guess my question is then, why are most of the expression values negative?
```

**Comment by yuhanH** [comment]
If you run `ScaleData` with default parameters,  the value in the scale.data is centered and scaled. It means, for each gene, its mean is 0 and variance is 1.

**Comment by mcsimenc** [comment]
Yes but in that latest example summary expression values are from from `FetchData` which defaults to the data slot. I think the transformation happened during the integration step, which I think it might make interpretation of `DotPlot` results problematic since `DotPlot` thresholds at 0 to determine whether a gene is expressed or not for calculating percent of cells with expression in clusters. And if all negative expression values represent "no expression" then coloring of cells in the plot made by `FeaturePlot` doesn't accurately represent expression.

**Comment by yuhanH** [comment]
What normalization method you used?

**Comment by mcsimenc** [comment]
SCTransform

**Comment by yuhanH** [comment]
When you run sctransform on a RNA assay, Pearson residuals are stored in the scale.data in SCT assay, so it may have negative Pearson residuals.  In the data slot of SCT assay, it has sequencing-depth-corrected log transformed data, and this value is positive. 
When you integrated SCT-normalized objects, the scale.data and data slots in the integrated assay are both integrated  Pearson residuals.
We suggest you plot gene expression using RNA assay or SCT assay.

**Comment by mcsimenc** [comment]
Thank you for the explanation @yuhanH!

**Comment by duocang** [comment]
> Yes but in that latest example summary expression values are from from `FetchData` which defaults to the data slot. I think the transformation happened during the integration step, which I think it might make interpretation of `DotPlot` results problematic since `DotPlot` thresholds at 0 to determine whether a gene is expressed or not for calculating percent of cells with expression in clusters. And if all negative expression values represent "no expression" then coloring of cells in the plot made by `FeaturePlot` doesn't accurately represent expression.

Hi @mcsimenc 
I still do not get why it has negative value in the legend. As it is clear that `FeaturePlot` takes `data` slot (`SCT` assay by default if ran by `SCTransform`).

**Comment by duocang** [comment]
Hi @yuhanH 

If I have an integrated object, does it make sense to set `SCT` as the default assay and to use it for `FeaturePlot`?

**Comment by yuhanH** [comment]
hi @duocang 

You are right. When you have an integrated object, you would better use RNA or SCT assay (not integrated assay) to do visualization.
