### ISSUE TITLE
Help importing Smartseq GEO dataset

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#3828]
Hello!

Thanks in advanced for your help and for making this extremely useful program! :)

I am trying to analyze a GEO dataset. Its scRNAseq data from Smartseq2, from five 2nd trimester human fetal livers and 3 uninjured adult human livers. - https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130473

I downloaded the two available files:
GSE130473_Series_count_matrix.csv.gz 
GSE130473_Series_feature_matrix.csv.gz

I loaded them into Seurat and was able to generate Seurat objects:
`liver_tissue <- read.csv(file = "~/Downloads/GSE130473/GSE130473_Series_count_matrix.csv.gz")
liver_tissue = CreateSeuratObject(counts = liver_tissue)
`

I've analyzed quite a bit of 10x datasets, but this Smartseq2 dataset is really different. I'm a little but stuck and had two questions about using Smartseq2 data in Seurat. 
- the count_matrix and feature_matrix files are separate, how do I merge them? 
- Each individual cell is labeled as "Human fetal liver (A12_102#169)", "Human fetal liver (A2_102#15)", "Human adult liver (A3_201#40)", etc. Whats the easiest way to handle this type of data?

Thanks!

**Comment by saketkc** [comment]
`GSE130473_Series_feature_matrix.csv.gz ` appears to be a metadata file. The first row are cell ids which have '#' which need to be substituted by '.'  to match the cell names in the counts matrix.

```r
counts <- read.csv("./GSE130473_Series_count_matrix.csv.gz", row.names=1)
metadata <- read.csv("./GSE130473_Series_feature_matrix.csv.gz", row.names=1)
rownames(metadata) <- gsub("#",".", rownames(metadata))
seu <- CreateSeuratObject(counts = counts, meta.data=metadata)
```
