### ISSUE TITLE
Single cell RNA-DGE by markers

### ISSUE THREAD

**Issue by Dexiao211** [satijalab/seurat#3829]
@satijalab , would appreciate your response on the issues below. 
I have two single cell seq samples and I want to run DEG for 2 samples based on a MARKER. I want to compare genepos from sample 1 to genepos from sample 2. I read Issuse #1890 and combined data using:
>ctrl <- Read10X(data.dir = "D:/10x/chen5/")
>ctrl <- CreateSeuratObject(counts = ctrl, min.cells = 3, min.features = 200, project = "Ctrl")
>ctrl$tbi <- "CTRL"
>ctrl <- NormalizeData(ctrl, verbose = FALSE)
>ctrl <- FindVariableFeatures(ctrl, selection.method = "vst", nfeatures = 2000)
>tbi <- Read10X(data.dir = "D:/10x/chen6/")
>tbi <- CreateSeuratObject(counts = tbi, min.cells = 3, min.features = 200, project = "Tbi")
>tbi$tbi <- "TBI"
>tbi <- NormalizeData(tbi, verbose = FALSE)
tbi <- FindVariableFeatures(tbi, selection.method = "vst", nfeatures = 2000)
>immune.anchors <- FindIntegrationAnchors(object.list = list(ctrl, tbi), dims = 1:20)
>immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)
>Idents(immune.combined, WhichCells(object = immune.combined, expression = Aqp4 > 1, slot = 'data')) <- 'ast.pos'
>Idents(immune.combined, WhichCells(object = immune.combined, expression = Aqp4 <= 1, slot = 'data')) <- 'ast.neg'
>Idents(immune.combined) <- paste0(Idents(immune.combined), immune.combined$???)

I know I should type in simple ID rather than ???, but I do not know what my sample ID is.  How to know my sample ID or can I add sample ID to objects?
Thanks.

**Comment by andrewwbutler** [comment]
Hi,

I assume by sample ID you mean distinguishing `ctrl` from `tbi` here? If you add a meta.data column before integrating that identifies them (e.g. `ctrl$sample <- "ctrl"` , `tbi$sample <- "tbi"`) this will be preserved post merge/integration and you can separate based on that.
