### ISSUE TITLE
Reading H5 file in Seurat

### ISSUE THREAD

**Issue by AndoYutaro** [satijalab/seurat#3830]
I want to analyze the H5 file data.
But I couldn’t read the data in Seurat.
It seems that the H5 file cannot be read in R.
Is it possible to change the format of the H5 file and have it read by the R package?
Please tell me how to do it such as usages.

**Comment by samuel-marsh** [comment]
Hi,

The H5 should be able to be read into R without issue.  To read H5 file just use the `Read10X_h5` command

Best,
Sam

**Comment by AndoYutaro** [comment]
Dear Sam,

Thank you very much!
I was able to load the file successfully.

Best regards,
Ando

**Comment by torkencz** [comment]
Yep, the Read10X_h5 command should work.
