### ISSUE TITLE
Recommended DE method for cluster marker identification with one latent variable

### ISSUE THREAD

**Issue by lc822** [satijalab/seurat#3831]
Hi,

I would like to identify markers for my scRNA-seq clusters using the `FindMarkers()` command with "donor" as a latent variable (comparison of one cluster vs. all other cells, positive markers only).  This leaves me with the options of 'LR', 'negbinom', 'poisson', or 'MAST'.  I have seen the negbinom approach used most frequently, however in some of my initial analyses the LR method appeared to give the most meaningful results.  For example, when I compared CD4+ and CD8+ clusters, CD8A and CD8B came up as enriched in the CD8+ cluster using LR but not negbinom.  It seems that negbinom does not work well when the expression is zero in one of the groups.

I would really like to get some expert opinion on which method is most appropriate for this setting.  In particular I have been torn between using the negbinom and LR approach, and I wasn't sure what the advantages/disadvantages of each were?

Best wishes,
Lucy

**Comment by saketkc** [comment]
Hi Lucy, it's hard to make a recommendation for DE test. See Figure 5 of this [paper](https://www.nature.com/articles/nmeth.4612) and [this paper](https://www.nature.com/articles/s41467-020-19894-4) for a comparison on different metrics.

**Comment by denvercal1234GitHub** [comment]
Hi @lucygarner - Did you end up using LR test for adjusting for the donor variability?
