### ISSUE TITLE
Loading Data from GEO datasets

### ISSUE THREAD

**Issue by Piyalsaha** [satijalab/seurat#3832]
I have gone through the whole guideline of Seurat to analyze scRNAseq dataset.
But I am not sure how to load the data in seurat using R from geo datasets.
For example, I downloaded GSE1313191 data from geo database. It contains two files:
1. GSE131391_cell_barcodses.txt
2. GSE131391_count_matrix.txt

Please, someone, help me out here

**Comment by willmonty14** [comment]
So every output of CellRanger (the pipeline often used to analyze scRNA-seq data, and the easiest one to upload into Seurat) should have three files - cell barcodes, count matrix, and features. Are you sure that this data was analyzed using CellRanger?

**Comment by samuel-marsh** [comment]
Hi,

So all you need to create Seurat object is a gene x cell matrix (See manual entry for `CreateSeuratObject`.  If the cell barcodes and count matrix are separate then all you have to do is create a combined dataframe/matrix in R with gene matrix and then add the barcodes as column names.  Then simply provide that combined matrix to `CreateSeuratObject`.

There is no need to have a CellRanger output to create Seurat Object.

Best,
Sam
