### ISSUE TITLE
Loading data from UMI counts

### ISSUE THREAD

**Issue by mgr98** [satijalab/seurat#3834]
I have UMI counts (got them from someone else in this format) Please see attached screenshot.  

Is there a simple way to create a Seurat object from it? Please help, I am stuck. 

I have tried breaking it into a matrix.mtx, genes.tsv, and barcodes.tsv files as shown in the tutorial with no luck. Any help would be appreciated. . 

<img width="816" alt="Screen Shot 2020-12-15 at 3 41 17 PM" src="https://user-images.githubusercontent.com/62923042/102270436-f98df980-3eeb-11eb-8486-fb4a786cf35f.png">

**Comment by torkencz** [comment]
Hi,
IN<-read.delim(file = "file you are showing") (you can also do read table)
SerObj<-CreateSeuratObject(counts = IN)
