### ISSUE TITLE
Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#3835]
Hello,

There have been a couple instance where people reported the warning "Warning: Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.". It happens when labeling a DimPlot. In one of those threads you suggested upgrading the seurat version, which seems to sometimes fix it. I have seen this warning on and off myself. If you google this message, you'll see it in all kinds of demo vignettes people post. It's also on a vignette from your site from Nov 2020, which seems to suggest this isnt something fixed in newer versions. I realize a warning isnt an error, but do you have any idea what causes this? I originally thought some property of the Idents/group.by column might cause this (i.e. it's data-dependent and therefore tough to reproduce), but I dont have a great answer. This is the recent example I came across:

https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_02_dim_reduction.html

Again, it doesnt seem to harm functionality but it a pretty consistent warning.

**Comment by torkencz** [comment]
Hi,
Thank you for pointing that out, we will try to fix it with later updates of Seurat.

**Comment by bbimber** [comment]
If you didnt already see this, the culprit is this code, in GetXYAesthetics

https://github.com/satijalab/seurat/blob/b56d194939379460db23380426d3896b54d91ab6/R/visualization.R#L5728
