### ISSUE TITLE
integration and sct

### ISSUE THREAD

**Issue by bettycatherine** [satijalab/seurat#3837]
Hi,
I am using SCTransform as weill as integration with CCA, MNN and Liger, and encountered couple of questions. I have searched the issues and cannot find similar ones. I have two species and two experiments, I have to integrate all of them since I observed great batch effect among them. I used SCTransform because this method seem fo perform better for my datasets.

1. I noticed that if I integrated experiments first and species second, the integreated experiments showed more batch effect than treat them four simultaneously.

2. I used fastmnn and I found that the heatmap was abnormal from all the tutorials, as follows, Is that normal or there is something wrong with my code?
![image](https://user-images.githubusercontent.com/22362094/102425081-97e2a200-4047-11eb-8a29-9f905ff73b28.png)

My code is this (sp represent species and ex represent experiment):
merged <- merge(spa.exa, y =c(spa.exb,spb.exa,spb.exb), add.cell.ids = c("spa_exa,,","spa_exb,", "spb.exa,","spb.exb,"), project = "cross-species")
aaa <- stringr::str_split(colnames(merged),',', simplify = T)[,1] 
names(aaa) <- colnames(merged) 
merged <- AddMetaData(object = merged, metadata = aaa, col.name = 'aaa')
list <- SplitObject(merged, split.by = 'aaa')
for (i in 1:length(list)) {
    list[[i]] <- SCTransform(list[[i]], verbose = FALSE)
}
combined <- RunFastMNN(object.list = list)

3. I used liger, and observed difference between doing SCT before merge species  and after merge. 
Results from doing sct before merge:
![image](https://user-images.githubusercontent.com/22362094/102425599-982f6d00-4048-11eb-99b7-e28608843236.png)
Between two experiments:
![image](https://user-images.githubusercontent.com/22362094/102425737-e3e21680-4048-11eb-9286-60c225fc3f08.png)

Results from doing sct after merge (I don't know why this one looks like this, but the pattern is similar to previouse fastmnn ):
![image](https://user-images.githubusercontent.com/22362094/102425780-f78d7d00-4048-11eb-9440-2951a187f246.png)
Btween two experiment:
![image](https://user-images.githubusercontent.com/22362094/102425814-0aa04d00-4049-11eb-9539-db980ef68f01.png)

 Here is my code:
##a.sct before merge
spa.exa <- SCTransform(spa.exa, vars.to.regress = "percent.mt", verbose = FALSE)
spa.exb <- SCTransform(spa.exb, vars.to.regress = "percent.mt", verbose = FALSE)
spb.exa <- SCTransform(spb.exa, vars.to.regress = "percent.mt", verbose = FALSE)
spb.exb <- SCTransform(spb.exb, vars.to.regress = "percent.mt", verbose = FALSE)
merged <- merge(spa.exa, y =c(spa.exb,spb.exa,spb.exb), add.cell.ids = c("spa_exa,","spa_exb,", "spb_exa,","spb_exb,"), project = "cross-species")
aaa <- stringr::str_split(colnames(merged),',', simplify = T)[,1] 
names(aaa) <- colnames(merged) 
merged <- AddMetaData(object = merged, metadata = aaa, col.name = 'aaa')
combined <- RunOptimizeALS(merged, k = 20, lambda = 5, split.by = "aaa")
combined <- RunQuantileNorm(combined, split.by = "aaa")

##b. sct after merge
merged <- merge(spa.exa, y =c(spa.exb,spb.exa,spb.exb), add.cell.ids =c("spa_exa,","spa_exb,", "spb_exa,","spb_exb,"), project = "cross-species")
merged <- SCTransform(merged, vars.to.regress = "percent.mt", verbose = FALSE)

aaa <- stringr::str_split(colnames(merged),',', simplify = T)[,1] 
names(aaa) <- colnames(merged) 
merged <- AddMetaData(object = merged, metadata = aaa, col.name = 'aaa')
combined <- RunOptimizeALS(merged, k = 20, lambda = 5, split.by = "aaa")
combined <- RunQuantileNorm(combined, split.by = "aaa")

I am new to scRNA, so forgive me to be suspicious about every step, I want to know is I am doing correct and what is the best combination for situation as mine. 

Any help will be highly apreciated!

Best,

Xue

**Comment by jaisonj708** [comment]
Answering your questions in order,
1) this is almost equivalent to manually specifying the integration sample tree. If the sample tree you specify is different from the one computed in the function, there might be a minor difference in integration results
2) I'm not sure what dataset you are using for this, since the fastmnn tutorials were done using publicly available datasets (PBMC I believe). If you have a personal dataset and would like us to try and diagnose an issue, feel free to send it to seuratpackage@gmail.com
