### ISSUE TITLE
Adjust documentation for clearer instruction

### ISSUE THREAD

**Issue by thyagoleal** [satijalab/seurat#3838]
https://github.com/satijalab/seurat/blob/b56d194939379460db23380426d3896b54d91ab6/man/CreateSeuratObject.Rd#L61

I was receiving this warning when using this function:
```
Warning message:
In CreateSeuratObject.default(mt, names.field = 1, names.delim = "_",  :
  Some cells in meta.data not present in provided counts matrix
```
Setting the row.names of df to the cells names fixed the problem. Therefore, I suggest changing this line in the documentation to read: 

Additional cell-level metadata to add to the Seurat object. Should be a data.frame where the rows are cell names and the columns are additional metadata fields. Row.names should match column names of counts matrix.

**Comment by timoast** [comment]
Sure, this will be added to the next release
