### ISSUE TITLE
Error in cc.loadings[[g]] : subscript out of bounds

### ISSUE THREAD

**Issue by Crystalli2018** [satijalab/seurat#384]
This is my first time to use Seurat. My goal is to compare samples in two conditions. I run into the same "subscript out of bounds" error while running the following commands in R on linux. Any suggestions on how to fix the problem? Thanks. Crystal

Command 1:

```R
p3 <- MetageneBicorPlot(lung.combined, grouping.var = "lung_PA", dims.eval = 1:dim_max,
+     display.progress = FALSE)
Rescaling group 1
```

Command 2:

```R
lung.combined <- AlignSubspace(lung.combined, reduction.type = "cca", grouping.var = "lung_PA",
+     dims.align = 1:20)
Rescaling group 1
[1] "Scaling data matrix"
  |======================================================================| 100%
Aligning dimension 1
Error in cc.loadings[[g]] : subscript out of bounds
```

**Comment by Crystalli2018** [comment]
Tried Dim_max=5 or 10 or 20 or 30, none worked.

**Comment by araksm** [comment]
Hi, I have faced the same issue today. I'm using Seurat_2.3.1.
How could I solve the problem?
Many thanks,
Araks

**Comment by leonfodoulian** [comment]
Hello Araks,

Could you please share the code you are using?

Best,
Leon
