### ISSUE TITLE
Can I use "SCT" assay to run SingleR ?

### ISSUE THREAD

**Issue by rrchai** [satijalab/seurat#3840]
Hi,

I know the `SingleR` requires the logCOUNTS, so using `RNA@data` slot is definitely okay. I wonder if I can use `SCT@data` for singleR. To my understanding, the `SCT@data` did more than log transformation?  Can you please help me understand the difference of "data" slot between "SCT" and "RNA" assay? 

Thank you in advance!

**Comment by torkencz** [comment]
Hi,

If you are taking the standard route of NormalizeData it applies a standard normalization of the feature expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000 by default), and log-transforms the result. In the case where you are using sctransform, that replaces NormalizeData, ScaleData, and FindVariableFeatures.  Results are saved in a new assay (named SCT by default) with counts being (corrected) counts, data being log1p(counts), scale.data being pearson residuals; sctransform::vst intermediate results are saved in misc slot of new assay.
If you want to understand how that specific transformation works I suggest you look at https://rawgit.com/ChristophH/sctransform/supp_html/supplement/variance_stabilizing_transformation.html
