### ISSUE TITLE
Why does SCTransform not save Residuals in 'data' Slot?

### ISSUE THREAD

**Issue by dg520** [satijalab/seurat#3841]
Hi Seurat Team,

Thanks for developing and maintaining this great tool.
I have a question for SCTransform: SCTransform now saves `log1p`-transformed counts (either raw counts or SCT-corrected counts) in the 'data' slot in the 'SCT' assay. But it seems this slot is not used anywhere in the downstream analysis. For most cases where we want to use normalized data, `GetResidual` has to be re-called to re-generate the (Pearson) residuals. 

I know Seurat takes care of calling `GetResidual` for most downstream analysis such as data integration. But is it handy to put (Pearson) residuals directly in the 'data' slot where the normalized data is supposed to be, for easy access of normalized expression under some customized scenarios? Or do I misunderstand something and actually `log1p`-transformed counts in 'SCT' assay are very useful?

Best,
Dadi

**Comment by jaisonj708** [comment]
The `data` slot in SCT is directly analogous to the `data` slot in RNA (or any other assay) -- it represents the log-normalized version of `counts`. In the case of SCT, these counts have been inferred from the residuals, but they should be fairly similar to RNA counts. The `data` slot may useful for plotting or differential expression.

For most downstream analysis (dimensional reduction) you will use the residuals in `scale.data` just as you would with the RNA assay. Residuals for your most variable features are computed by default in `SCTransform`.
