### ISSUE TITLE
Integrating heterogenous and homogeneous samples

### ISSUE THREAD

**Issue by sbdaxia** [satijalab/seurat#3842]
Hi,

I am wondering if Seurat can be used to integrate a highly heterogenous sample with a highly homogeneous sample? Or does Seurat assume some level of heterogeneity in all samples used for integration?

The reason I ask is that recently I performed an analysis on my dataset, with integration, clustering, and cell type annotation. Then after the analysis, I decided to subset out the stem cell population from a group of samples and integrate these "stem cells" alone with all the other heterogeneous samples (I used the annotation from the initial analysis to subset my raw data and went through the pipeline of SCTransform normalization, integration and clustering). I was expecting the these stem cells to cluster tightly together on the UMAP but instead I see that samples supposedly comprised of pure stem cells still showed a rather dispersed UMAP pattern. I checked the stem cell marker expression and they are highly expressed in my stem cell only sample so I think they are indeed stem cells but they are not clustered tightly as I expected.

One additional note is that I had to drop the `k.filter` parameter because my stem cell only sample had much less cells than the other samples (~1/10). 

So I am wondering if Seurat is suitable to integrate highly heterogenous with highly homogeneous samples.

Thank you!

**Comment by torkencz** [comment]
Hi,

I think you should be fine as long as your stem cells did not cluster with other cells you were not expecting them to cluster with. In UMAP you might want to change the number of neighbors you look at for instance. Also, I would make sure when you find clusters it is separate. UMAP is a visualization tool that can trick you depending on the parameters you feed it.

**Comment by sbdaxia** [comment]
Hi,

Thanks for answering this question. The issue is that I am seeing cells from the stem cell cluster of one sample gets dispersed into other clusters when I redid the integration and clustering using just stem cells from 1 sample with other heterogeneous samples. It almost seemly the algorithm is assuming heterogeneity in the stem cell sample and forced it to cluster with other cell types that shouldn't exist in this homogeneous sample.

Thank you!

Best,
Bing
