### ISSUE TITLE
Integration of Multi-Modal Data across Datasets

### ISSUE THREAD

**Issue by JenniferWUSTL** [satijalab/seurat#3843]
Good evening, thank you for the updated Seurat v4 package.  I am excited to use it and have a question similar to issue #3799 @yuhanH .  I previously integrated my RNA assay following the integration workflow, and now want to integrate my ADT assay and input into `FindMultiModalNeighbors`, however, after integration of my ADT assay, my previously computed `PCA` and `ScaleData` are now gone.  How do I maintain two batch corrected assays with reduction information as input into `FindMultiModalNeighbors`? Thank you!

Confirmation of integrated RNA assay, scaled data, and PCA:
```
Command(object)
[1] "FindIntegrationAnchors"       "PairwiseIntegrateReference"  
[3] "ScaleData.integrated"         "RunPCA.integrated"           
[5] "JackStraw.integrated.pca"     "ScoreJackStraw"              
[7] "FindNeighbors.integrated.pca" "RunTSNE"                     
[9] "FindClusters"           
```     
Integrating ADT assay:
```
DefaultAssay(object) <- "ADT"
VariableFeatures(object) <- subset_adt
scrna.list2 <- SplitObject(object, split.by = "Donor")
anchors <- FindIntegrationAnchors(object.list = scrna.list2, assay = c("ADT", "ADT"), anchor.features = subset_adt, k.filter = NA)
scrna.int <- IntegrateData(anchorset = anchors, new.assay.name = "integrated.adt", dims = 1:26, k.weight = 26)
scrna.int <- RunPCA(scrna.int, reduction.name = "apca", approx = FALSE)
scrna.int <- FindMultiModalNeighbors(scrna.int, reduction.list = list("pca", "apca"), dims.list = list(1:13, 1:27), modality.weight.name = "RNA.weight")
Calculating cell-specific modality weights
Error: Cannot find 'pca' in this Seurat object
> Command(scrna.int)
[1] "FindIntegrationAnchors"   "withCallingHandlers"     
[3] "ScaleData.integrated.adt" "RunPCA.integrated.adt" 
```

**Comment by yuhanH** [comment]
Hi, 
The previous reduction may be delete in the `IntegrateData` process. 
The easiest way is to add them from the original object. 
`scrna.int[["pca"]] <- object[["pca"]]`
If there are some conflicts, you would better to use `CreateDimReducObject` to add pca to the integrated object. 
`scrna.int[["pca"]] <- CreateDimReducObject( )`

**Comment by JenniferWUSTL** [comment]
Thank you @yuhanH ! The scaled data assay for the integrated RNA is also deleted during ADT integration. How can I add that data back? With cell cycle regression, rescaling can take several days. Thank you and merry Christmas!

**Comment by yuhanH** [comment]
Hi @JenniferWUSTL 
During the integration process, the scale.data is easily to be lost, because in `merge` function, we usually delete the scale.data. 

One easy way is to first integrate RNA and protein separately by two objects. Then, you can create an integrated ADT `assay` in the integrated RNA `object`.

**Comment by jessielyons** [comment]
Hi @JenniferWUSTL ,

What command did you use to address YuhanH comment? How did you first integrate RNA with protein so that "integrated" assay dosen't get overwritten by "integrated_adt" assay?

**Comment by JenniferWUSTL** [comment]
Hi @jessielyons! I did the RNA integration like normal, and then used a copy of that same seurat object to run the integrated_adt assay.  Then, I added the integrated_RNA assay to my Seurat object with the integrated_adt assay with the following commands, where integrated is the RNA integrated assay:

```
DefaultAssay(scrna.int) <- "integrated" # seurat object with integrated_adt but has deleted scale.data and pca for integrated RNA
DefaultAssay(object) <- "integrated" # same seurat object but without integrated adt so has all integrated RNA slots intact.
scrna.int[["pca"]] <- object[["pca"]]
scale.data.rna <- GetAssayData(object, slot = "scale.data", assay = "integrated")
scale.data.rna <- as.matrix(scale.data.rna)
scrna.int <- SetAssayData(scrna.int, slot = "scale.data", assay = "integrated", new.data = scale.data.rna)

```
Let me know if you have trouble with this, and I can send more details.  Good luck!
