### ISSUE TITLE
Lets examine a few genes in the first thirty cells

### ISSUE THREAD

**Issue by howardchen0810** [satijalab/seurat#3844]
I can successfully run this code as following:
library(Seurat)
library(dplyr)
library(patchwork)

pbmc.data <- Read10X(data.dir = "pbmc3k/filtered_gene_bc_matrices/hg19")

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

However, when I want to look at the count matrix by using this command:
pbmc.data[c("CD3D", "TCL1A", "MS4A1"), 1:30]

Error popped up like this: 
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

Could you suggest me how to fix it? Thanks!!!

**Comment by torkencz** [comment]
Hi,

I Honestly would use GetAssayData(object = pbmc, slot = "counts")[c("CD3D", "TCL1A", "MS4A1"), 1:30]
