### ISSUE TITLE
After integration with SCTransform, needs it additional RNA scaling process? 

### ISSUE THREAD

**Issue by 0717cyj** [satijalab/seurat#3847]
Dear.

Thanks for your recommendation. 
(https://github.com/satijalab/seurat/issues/3839)
It will be helpful for me.
However, I have some questions about it.

After Integration with SCTransform as vignettes,
if I use RNA slot for DE, needs it additional scaling processing after integration in RNA assay?

It seems to be a very confusing process for me . I'm sorry to ask you again. 

Please confirm that below process is acceptable analysis process.

Integration with SCTransform (in each data set, as vignettes in SAJITA LAB) -> defaultassay:integrated --> PCA & findclusters --> (question is "Needs it additional scaling processing in this step?") --> defaultassay:RNA --> findmarkers (etc.)

Thank you again for your help.

**Comment by yuhanH** [comment]
Hi, 

If you want to use RNA for DE, you don't need to `scale` RNA slot, but you need to run `NormalizeData` on RNA slot. 
You need to log-transform RNA counts to the data.slot. Usually, we use RNA data.slot to find DE.
