### ISSUE TITLE
Select characteristic points at anatomic tissue locations and highlight them in tSNE or UMAP diagrams

### ISSUE THREAD

**Issue by EternalEnvy10** [satijalab/seurat#3848]
Hi,
    I recently performed a spatial transcriptome analysis using Seurat. For spots in the anatomical organization, I want them to be highlighted in the cluster diagram to see which clusters these points are closer to. Is there a way to do this?

Best wishes,
Zhaonian

**Comment by yuhanH** [comment]
`cells.highlight` in `DimPlot` can be used to highlight cells you need. 
You can use `WhichCells` to get the cells that you want to highlight, and put them to `cells.highlight`
