### ISSUE TITLE
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 

### ISSUE THREAD

**Issue by tn00992786** [satijalab/seurat#3849]
I have referred the issue before :
1. https://github.com/satijalab/seurat/issues/2761
2. https://github.com/satijalab/seurat/issues/2387
Still could not solve the problem. 

Following code:
data1<- readRDS(file = "~/1.rds") 
data2<- readRDS(file = "~/2.rds") 
data12<-merge(data1,data2)
nrow(data12)
[1] 2000
ncol(data12)
[1] 4188
data12 <- RunPCA(data12, nfeatures.print = 4)

Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.
data12 <- FindVariableFeatures(data12, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'

Thanks for anyone who can solve this. 
Stay health 
Z

**Comment by saketkc** [comment]
Hi, Have you run the `NormalizeData()` function prior to `FindVariableFeatures()`? Also, your data has just 2000 features in total (`nrow(data12)`), so `nfeatures=2000` is redundant.
