### ISSUE TITLE
Can I integrate data from two separately integrated datasets for the second time? 

### ISSUE THREAD

**Issue by veralow1990** [satijalab/seurat#3850]
Greetings!
I extracted partial datasets from two original Seurat datasets which were integrated separately.
Can I re-perform FindIntegrationAnchors and IntegrateData on the new datasets to generate a new Seurat object?
Many thanks for your help!

**Comment by torkencz** [comment]
Hi, 
I think it depends. I would not integrate imputed values for instance, but integration on counts values should be worth a try.
