### ISSUE TITLE
Separating a cluster into two samples

### ISSUE THREAD

**Issue by Piyalsaha** [satijalab/seurat#3852]
Hello!
I have a count matrix that contains cell samples from non-smoker and smokers. Is there any way to separate these samples within the clusters using Seurat? Thanks in advance

**Comment by k3yavi** [comment]
Hi @Piyalsaha ,

Thanks for reaching out. Are the cells annotated ? If yes then you can use the `group.by =` flag in the `DimPlot` command to separate the two categories in the umap plots.
