### ISSUE TITLE
Integrate and then merge with other datasets?

### ISSUE THREAD

**Issue by yjlee0331** [satijalab/seurat#3853]
Hello, I was wondering if the following could work:

Let's say I have a dataset that consists of conditions A, B, C, and D. For whatever reason, I have 4 technical replications of condition D. In order to remove batch effects, I would like to integrate D and then merge the integrated dataset with A, B, and C. Is this a sound/feasible thing to do? I'd like to refrain from integrating A, B, C, D, D, D, D in the case that this masks sources of variation that are due to the different conditions, as opposed to true batch effects between technical replicates.

Thank you so much for the package and the continued support!

**Comment by torkencz** [comment]
Hi,
The problem with integrating an already integrated dataset is that you would have to try to do it on imputed values, which is not recommended. I would first try to integrate everything and compare with the unintegrated merged data you have. See how much variation you are losing. Alternatively, I would try integrating A,B,C,D1; A,B,C,D2.. etc. and see what is shared between these integrated objects. Hope this helps.
