### ISSUE TITLE
How do I remove cells with a UMI of 0?

### ISSUE THREAD

**Issue by JeonghanSeo** [satijalab/seurat#3854]
Hi, 
I made a data matrix using the 'Read10X' funcion like this:

```sample.data <- Read10X(data.dir = sample.dir)```
```sample.data # (33538 x 4780)```

Then, I want to remove the cells where gene1 and gene2 are expressed as 0 at the same time.

In general, the matrix knows that the row is the gene and the column is the cell.

![image](https://user-images.githubusercontent.com/17999083/102847469-c13f6b80-4455-11eb-869d-71d3d501f6c1.png)

What I want is below.

![image](https://user-images.githubusercontent.com/17999083/102847907-d5d03380-4456-11eb-97af-537040e4f0c0.png)

Then I try to create a seurat object.

Any help would be appreciated.

Best regards,

**Comment by k3yavi** [comment]
Hi @JeonghanSeo ,

Something like following can help achieve what you want'.

```
# get submatrix with two genes
genes <- sample.data[ c("Gene1", "Gene2"),  ]

# find cells with non zero expression
keep.cells <- colnames(genes[, colSums(genes) != 0])

# filter big matrix.
sample.data <- sample.data[, keep.cells]
```
