### ISSUE TITLE
Using public dataset, how to define the stim or ctrl?

### ISSUE THREAD

**Issue by yzh37545** [satijalab/seurat#3855]
Hi Seurat team,

I want to re-analyze a GEO dataset using the new version Seurat. It only includes a UMI count table containing both healthy and patient's data. Is there any way I could define the "meta.data$stim" group by the column names?

Thank you so much!

**Comment by k3yavi** [comment]
hi @yzh37545 ,

I think you need to extract the cell-wise annotation from the previous object and assign it to the new object using 
`new.object$stim <- annotation`.
