### ISSUE TITLE
Cell cycle scoring using for Lineage Identification

### ISSUE THREAD

**Issue by Hemantcnaik** [satijalab/seurat#3857]
Hello, 

Thank you for tools, which is very helpfull. I just have a question as we are segregating cells based on cell cycle score using cellcyclescore function we have to provide marker genes specific to cell cycle, using same strategy lineage specific genes, Can we segregate cells according to lineage (https://www.biorxiv.org/content/10.1101/2020.03.08.982694v1)

**Comment by timoast** [comment]
Hi, you can use the `AddModuleScore` to compute a per-cell score for a set of genes, which might help in visualising the combined expression patterns of several genes at once
