### ISSUE TITLE
What do AverageExpression Inf values mean?

### ISSUE THREAD

**Issue by CaroSegami** [satijalab/seurat#3858]
I know a similar issue was raised before, but I didn't understand it quite well.
I have a Surat Object created using SCTransform:

102092 features across 4176 samples within 6 assays 
Active assay: integrated (2500 features, 2500 variable features)
 5 other assays present: spliced, unspliced, ambiguous, RNA, SCT
 2 dimensional reductions calculated: pca, umap

When trying to follow this vignette: https://satijalab.org/seurat/v3.2/immune_alignment.html
Specifically when trying to Identify differential expressed genes across conditions and using the AverageExpression function I notice that I have some Inf values for a few genes in some of my clusters.

First of all I would like to know exactly how is the Average Expression calculated? Is it the mean of counts of reads across cells per clusters? How is it possible that an Inf value exists?

I saw that one of the previous suggestions is to LogNormalize before but having done the normalization with SCTransform should I still try that? 

Cheers,

Carolina

**Comment by saketkc** [comment]
Hi Carolina,

Yes, use `LogNormalize` before running `AverageExpression` as suggested previously.
