### ISSUE TITLE
How to use parallel on RStudio?

### ISSUE THREAD

**Issue by rrchai** [satijalab/seurat#3859]
Hi,

I am using `Seurat 4.0`. However, I am not able to enable the parallelization using future with [seurat instruction](https://satijalab.org/seurat/v3.0/future_vignette.html). I found [page](https://satijalab.org/signac/articles/future.html) saying that  

```
Note that as of future version 1.14.0, forked processing is disabled when running in RStudio. To enable parallel computing in RStudio, you will need to select the “multisession” option.
```

So I tried to use `plan("multisession")`on RStudio on Mac, but it did not work out.

Can you please provide example of how to use parallel on RStudio for seurat function, e.g. `FindIntegrationAnchors`? 

Thank you in advanced!

**Comment by andrewwbutler** [comment]
Hi,

What exactly do you mean by "did not work out" ? Setting `plan("multisession")` should enable it to work in Rstudio.
