### ISSUE TITLE
Rename Genes Clarification

### ISSUE THREAD

**Issue by Oscar-Wu-UTSW** [satijalab/seurat#3860]
For the RenameGenes function in Seurat utils, how exactly does one manipulate the code to replace the dimnames with a new set of genes? I have a csv file containing the new names for all 28,444 genes in the original Seurat object, and would like to replace them with those names. In other words, what exactly does one change for "ls.Seurat" and "HGNC.updated.genes$Suggested.Symbol"? Thanks so much!
(Below is the code for the Seurat function provided by @vertesy)

RenameGenesSeurat <- function(obj = ls.Seurat[[i]], newnames = HGNC.updated[[i]]$Suggested.Symbol) { # Replace gene names in different slots of a Seurat object. Run this before integration. Run this before integration. It only changes obj@assays$RNA@counts, @data and @scale.data.
  print("Run this before integration. It only changes obj@assays$RNA@counts, @data and @scale.data.")
  RNA <- obj@assays$RNA

  if (nrow(RNA) == length(newnames)) {
    if (length(RNA@counts)) RNA@counts@Dimnames[[1]]            <- newnames
    if (length(RNA@data)) RNA@data@Dimnames[[1]]                <- newnames
    if (length(RNA@scale.data)) RNA@scale.data@Dimnames[[1]]    <- newnames
    # if (length(obj@meta.data)) rownames(obj@meta.data)          <- newnames
  } else {"Unequal gene sets: nrow(RNA) != nrow(newnames)"}
  obj@assays$RNA <- RNA
  return(obj)
}
# RenameGenesSeurat(obj = SeuratObj, newnames = HGNC.updated.genes$Suggested.Symbol)

**Comment by samuel-marsh** [comment]
Hi,

This function isn't a part of Seurat package.  I suggest you post your question to the appropriate GitHub repo for more information.

Best,
Sam
