### ISSUE TITLE
integer limit for Read10X

### ISSUE THREAD

**Issue by neocaleb** [satijalab/seurat#3862]
I want to load a large-scale single cell data using Read10X. But there is an error message as follows:

Error in scan(file, nmax = 1, what = what, quiet = TRUE, ...) : 
  scan() expected 'an integer', got '4512447254'

I think there is a limit for integer variable. When I cut the data, it works. 
Do you have any plan for modifying Read10X to allow scRNA-seq data larger than the integer limit?

**Comment by andrewwbutler** [comment]
This seems like it could be an issue with the file. When you say cut the data, what exactly do you mean? Are you able to read in the matrix file on it's own using something like `data.table::fread`?
