### ISSUE TITLE
Projecting Query Cells to Existing DimReduc UMAP -- no model present

### ISSUE THREAD

**Issue by jebard** [satijalab/seurat#3864]
I'm working on integrating a query set to a public dataset UMAP projection. There is currently no DimReduc model stored in their Seurat object -- is it possible to compute a UMAP model without generating a new set of umap coordinates? (I understand this step is done using the RunUMAP(.... return.model=T) -- can you do this retroactively to existing datasets?

The goal is to preserve the previously reported structure and overlay new data onto it. I'm able to generate a new UMAP and transfer labels, but ideally we want to keep the previous umap coordinates. 

Thanks for any tips,
Jonathan

**Comment by yuhanH** [comment]
Hi, 
Do you know the initial parameters for your previous UMAP?
Here are necessary parameters: `n_epochs`, `alpha`, `negative_sample_rate`, `gamma`, `approx_pow`, `spread`, `min_dist`, `metric`.
If you `RunUMAP` by seurat, those initial parameters can be found, and then we can create the umap model using the cells umap coordinates and those parameters.

**Comment by jebard** [comment]
Hello Yuhan,
Thanks for following up. I'm currently working on the data objects provided by Hauser et. al. RData object can be found here -- 
https://figshare.com/articles/dataset/Postnatal_SMG_Integrated_rds/13157726

Looking into the data, i've found some of the required fields but i'm not sure how to find all of the fields you are interested in... any ideas?

> postnatal@commands[["RunUMAP.integrated.pca"]]
Command: RunUMAP(smg.p.integrated, reduction = "pca", dims = 1:30)
Time: 2020-10-03 19:52:20
dims : 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 
reduction : pca 
assay : integrated 
umap.method : uwot 
n.neighbors : 30 
n.components : 2 
metric : cosine 
learning.rate : 1 
min.dist : 0.3 
spread : 1 
set.op.mix.ratio : 1 
local.connectivity : 1 
repulsion.strength : 1 
negative.sample.rate : 5 
uwot.sgd : FALSE 
seed.use : 42 
angular.rp.forest : FALSE 
verbose : TRUE 
reduction.name : umap 
reduction.key : UMAP_

**Comment by yuhanH** [comment]
HI, 
I put an example in the below.  
`umap` reduction is the umap with returned model, and `umap.new` has the umap model that I reset. 
in the end, you can see p1 and p2 are the same. 
 ![image](https://user-images.githubusercontent.com/29529544/107834836-6fd0a000-6d65-11eb-9f87-577d56a5a154.png)
```
library(SeuratData)
data("pbmcsca")
pbmc.ref <- subset(pbmcsca, subset = Method == "10x Chromium (v3)"  )
pbmc.ref <- NormalizeData( pbmc.ref )%>%FindVariableFeatures()%>%ScaleData()%>%RunPCA()%>%RunUMAP(dims=1:30, return.model = T)


pbmc.query  <- subset(pbmcsca, subset = Method == "10x Chromium (v2)" )
pbmc.query <- NormalizeData(pbmc.query)

anchors <- FindTransferAnchors(
    reference = pbmc.ref,
    query = pbmc.query,
    reference.reduction = 'pca',
    features = rownames(x = pbmc.ref[["pca"]]@feature.loadings),
    dims = 1:30,
    nn.method = "annoy",
    k.filter = NA,
    verbose = TRUE
  )
  

pbmc.query.1 <- MapQuery(
    reference = pbmc.ref,
    query = pbmc.query ,
    anchorset = anchors,
    refdata = list(celltype = "CellType"),
    reference.reduction = "pca",
    reduction.model = "umap"
  )


# set embeddings
pbmc.ref[["umap.new"]] <- CreateDimReducObject(embeddings = pbmc.ref[["umap"]]@cell.embeddings, key = "UMAPnew_")

# set UMAP models
umap.new.model <- list()
umap.new.model$n_epochs <- 500
umap.new.model$alpha <-1
umap.new.model$method <- "umap"
umap.new.model$negative_sample_rate <- 5
umap.new.model$gamma <- 1
umap.new.model$approx_pow <- 0
umap.new.model$metric$cosine <- list()
umap.new.model$embedding <- pbmc.ref[["umap.new"]]@cell.embeddings
ab_param <- uwot:::find_ab_params(spread = 1, min_dist = 0.3)
umap.new.model$a <- ab_param["a"]
umap.new.model$b <- ab_param["b"]
pbmc.ref[["umap.new"]]@misc$model <- umap.new.model
 

pbmc.query.2 <- MapQuery(
  reference = pbmc.ref,
  query = pbmc.query ,
  anchorset = anchors,
  refdata = list(celltype = "CellType"),
  reference.reduction = "pca",
  reduction.model = "umap.new"
)
p1 <- DimPlot(pbmc.query.1, reduction = "ref.umap",group.by = "predicted.celltype", label = T) + NoLegend() + ggtitle("return model")
p2 <- DimPlot(pbmc.query.2, reduction = "ref.umap", group.by = "predicted.celltype", label = T) + NoLegend()+ ggtitle("set model")
library(patchwork)
p1+p2
```

**Comment by cedmo001** [comment]
Hi @yuhanH,


> 
> pbmc.query.2 <- MapQuery(
>   reference = pbmc.ref,
>   query = pbmc.query ,
>   anchorset = anchors,
>   refdata = list(celltype = "CellType"),
>   reference.reduction = "pca",
>   reduction.model = "umap.new"
> )

Thank you for you help on this issue! I'm trying to something similar, where I have the original embeddings from a UMAP and would like to maintain the structure of the UMAP as my reference and project onto it. 

It looks like I can map my query onto the reference (pbmc.query.1 onto pbmc.ref) but when I try to run pbmc.query.2 I get the following error:
Error in if (n.cells < k.param) { : argument is of length zero

Just wondering if you can help figure out what is happening? 

Best Wishes, 
C

**Comment by YichaoOU** [comment]
Hello,

How to find these parameters?

```
umap.new.model <- list()
umap.new.model$n_epochs <- 500
umap.new.model$alpha <-1
umap.new.model$method <- "umap"
umap.new.model$negative_sample_rate <- 5
umap.new.model$gamma <- 1
umap.new.model$approx_pow <- 0
```

Thanks,
Yichao

**Comment by cedmo001** [comment]
Hey @YichaoOU,

I found them here:

SeuratObject@reductions[["umap"]]@misc[["model"]]

Best, 
C

**Comment by ernohanninen** [comment]
Hi @cedmo001 ,
You need to specify the number of neighbors with n_neighbors parameter when setting the umap model

`sobj_ref[["umap_new"]] <- CreateDimReducObject(embeddings = sobj_ref[["umap"]]@cell.embeddings, key = "UMAPnew_", assay='integrated')

# set UMAP models
umap_new_model <- list()
umap_new_model$n_epochs <- 500
umap_new_model$alpha <-1
umap_new_model$method <- "umap"
umap_new_model$negative_sample_rate <- 5
umap_new_model$gamma <- 1
umap_new_model$approx_pow <- 0
umap_new_model$n_neighbors <- 30
umap_new_model$metric$cosine <- list()
umap_new_model$embedding <- sobj_ref[["umap_new"]]@cell.embeddings
ab_param <- uwot:::find_ab_params(spread = 1, min_dist = 0.3)
umap_new_model$a <- ab_param["a"]
umap_new_model$b <- ab_param["b"]
sobj_ref[["umap_new"]]@misc$model <- umap_new_model`
