### ISSUE TITLE
Is there any limits of cells # for integration?

### ISSUE THREAD

**Issue by rrchai** [satijalab/seurat#3868]
Hi,

I am working on the multiple samples data. After I have done QC, some samples only have 100+ cells. I tried to integrate the data using 'SCT' + 'rpca' method. It did not work during the `FindIntegrationAnchors` step:
```idx[i, ] <- res[[i]][[1]] : number of items to replace is not a multiple of replacement length```

The error can be resolved if the sample size is large enough (Have not tried the limit). Is there any limit to do integration or is there any way to fix this problem? (I am thinking to merge small samples and then do integration?)

Thank you

**Comment by rrchai** [comment]
I found the answer #3760. So there is the limit, but I do not how many. What's the resolution to do integration on small samples?

**Comment by timoast** [comment]
For very small datasets, this was not the use-case that the integration algorithm was designed for, and so I'd recommend exploring other approaches in those cases, or merging small datasets into larger ones if the batch effect is small.
