### ISSUE TITLE
Error using as.loom

### ISSUE THREAD

**Issue by justin-malin** [satijalab/seurat#3869]
Hi, 

I'll start with a big thanks to the Seurat team for great support and ever-expanding functionality and inter-operability for what was already a really useful tool.

I am getting errors trying to convert a seurat object to a .loom file.

> library(SeuratDisk)
> immune.combined.loom <- as.loom(immune.combined)
Error in loomR::create(filename = filename, data = data[feature.order,  : 
  unused arguments (feature.attrs = as.list(x = meta.feature), transpose = TRUE, calc.count = FALSE, max.size = max.size, verbose = verbose)
In addition: Warning message:
as.loom is being moved to SeuratDisk
For more details, please see https://github.com/mojaveazure/seurat-disk/tree/feat/loom 
> immune.combined
An object of class Seurat 
19381 features across 1380 samples within 1 assay 
Active assay: RNA (19381 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap

I didn't find a solution in any of the related issues or replies.

Thanks,
Justin

**Comment by mojaveazure** [comment]
Hi Justin,

Try installing the `feat/loom` branch of SeuratDisk to gain support for the new `as.loom`

```R
remotes::install_github('mojaveazure/seurat-disk', ref = 'feat/loom')
immune.combined.loom <- SeuratDisk::as.loom(immune.combined)
```

This will become the default way to create loom files from `Seurat` objects in the future; if it doesn't work, reopen this issue and let me know so we can get it working for you.

**Comment by hayfre** [comment]
Hi, the install you suggested doesn't seem to be working. Please see the error:

`> remotes::install_github('mojaveazure/seurat-disk', ref = 'feat/loom')
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref feat/loom

  Did you spell the repo owner (`mojaveazure`) and repo name (`seurat-disk`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.`

**Comment by justin-malin** [comment]
Hi,

If I remember correctly, I was able to install following instructions given in the vignette for conversion to/from loom:<https://satijalab.org/seurat/v3.2/conversion_vignette.html>
remotes::install_github(repo = 'mojaveazure/loomR', ref = 'develop')

**Comment by ccruizm** [comment]
Hello,

I am having the same problem than @hayfre. Any news how to solve it? Thanks

**Comment by ccruizm** [comment]
It seems the branch was deleted (https://github.com/mojaveazure/seurat-disk/pull/38). How to save loom files on the newest version of Seurat (v4)?
Thanks in advance!

**Comment by MartinaCardinali** [comment]
> It seems the branch was deleted ([mojaveazure/seurat-disk#38](https://github.com/mojaveazure/seurat-disk/pull/38)). How to save loom files on the newest version of Seurat (v4)?
> Thanks in advance!

Hi, I solved the problem by installing the general SeuratDisk:

remotes::install_github('mojaveazure/seurat-disk')

Then you will load the library

library(SeuratDisk)

and convert to loom file with SeuratDisk::as.loom(seurat_object, filename = "file.loom")

**Comment by topafzd** [comment]
@MartinaCardinali 
Thanks for your sharing. I solved this problem following your suggestion by installing SeuratDisk.
