### ISSUE TITLE
This bug can be fixed by downgrading the sctranform package to the old version, v0.3.0. This works well for me.

### ISSUE THREAD

**Issue by Sandra9518** [satijalab/seurat#3870]
This bug can be fixed by downgrading the sctranform package to the old version, v0.3.0. This works well for me.  

> install.packages("v0.3.0.tar.gz", repos = NULL, type="source")

_Originally posted by @zjzace in https://github.com/satijalab/seurat/issues/3618#issuecomment-719421866_

**Comment by Sandra9518** [comment]
Hi, I have tried to install the package, but I got the following error. Do you have any idea? Thanks!

> install.packages("v0.3.0.tar.gz", repos = NULL, type="source")
Warning: invalid package ‘v0.3.0.tar.gz’
Error: ERROR: no packages specified
Warning in install.packages :
 installation of package ‘v0.3.0.tar.gz’ had non-zero exit status

**Comment by timoast** [comment]
To install the previous release of a package (eg, SCTransform) the correct code is:

```r
devtools::install_version(package = 'stransform', version = package_version('0.3.0'))
```
