### ISSUE TITLE
DoHeatmap cells error

### ISSUE THREAD

**Issue by dm8000** [satijalab/seurat#3872]
Hello Seurat team

I got a very large dataset (160 thousand cells). To do a heatmap, I made a list of randomly sampled cells (random.cells), and ran the code (here I only selected 2 cells to test the code).

`plot <- DoHeatmap(circBALFflu.pred.integrated, features = DEGs$gene, assay = "RNA2", cells = random.cells) + theme(text = element_text(size = 8))`

I got the error message

```
Error in data.frame(group = sort(x = group.use), x = x.divs) : 
  arguments imply differing number of rows: 13, 14
In addition: Warning message:
In DoHeatmap(circBALFflu.pred.integrated, features = DEGs$gene,  :
  The following features were omitted as they were not found in the scale.data slot for the RNA2 assay: GNAS, CALM3, H3F3A, OAZ1, NAP1L1, FERMT3, TAGLN2, CTSA, TGFB1, OST4
```

I am mostly concerned about the first error (I scaled the data with the top 6000 most variable features, but DE was performed on all genes). When I run the code without selecting the cells, the code runs, but gives me a blank heatmap (probably because the number of cells).

**Comment by torkencz** [comment]
Hi, 
I would try to run DoHeatmap with the label=FALSE option, also I would remove from my list the genes that are not in your RNA2assay. Does the problem persist if you sample more cells? e.g. 500,1000. It could also be the influence of how many clusters you have. You should also look at how many genes you are trying to plot.  These are my initial thoughts, but can reopen if it persists (in that case I will need a little more information about the data and a traceback).

**Comment by dm8000** [comment]
I ran the code the label=FALSE with 500 randomly selected cells of each cluster and it worked. Thanks!
