### ISSUE TITLE
Demultiplex VDJ data

### ISSUE THREAD

**Issue by amufaamo** [satijalab/seurat#3873]
Hi, I have scTCR fastq and hashtag fastq of 10x Genomics. We don't have scRNA-seq fastq. Can we demultiplex scTCR data?

**Comment by k3yavi** [comment]
Hi @amufaamo ,

Thanks for reaching out. Unfortunately, it's not clear to me what kind of demultiplexing you are talking about ? Is it like the experiment based HTO hashes or you are talking about fastq demultiplexing ? If the former I think you can use the `HTODemux` command to demux the experiment.

**Comment by yuhanH** [comment]
You can align your HTO fastq feature-barcode by Cellranger or [Alevin](https://combine-lab.github.io/alevin-tutorial/2020/alevin-features/). Then you can use `HTODemux` or follow our cell [hashing vignette](https://satijalab.org/seurat/v3.2/hashing_vignette.html) to demultiplex your cells.

**Comment by amufaamo** [comment]
Sorry my question was not so clear.

If I have scRNA-seq + scVDJ-seq + hashtag feature barcode fastqs, I can
demultiplex scRNA-seq and scVDJ-seq into samples. But I have
only scVDJ-seq + hashtag feature barcode fastqs. So can I demultiplex
scVDJ-seq fastq?

2021年1月9日(土) 3:06 Yuhan Hao <notifications@github.com>:

**Comment by yuhanH** [comment]
If the cell barcodes are the same, you can demultiplex your scVDJ-seq

**Comment by amufaamo** [comment]
Thank you so much. I will try it.

2021年1月12日(火) 22:59 Yuhan Hao <notifications@github.com>:

**Comment by csweeney225** [comment]
I am trying to do the same thing but am also unable to find a way of demultiplexing my V(D)J data with Seurat. I have 10X Chromium data (5' gene expression, V(D)J and hashtag for multiplexing). I can see the vignette for how to demultiplex the gene expression data, which all makes sense. 

How do I demultiplex the V(D)J data? What V(D)J output file from Cell Ranger should I use?
