### ISSUE TITLE
Idenifying Location of Specific Variants on UMAP FeaturePlots

### ISSUE THREAD

**Issue by sahh04** [satijalab/seurat#3878]
Hi, 

I was wondering if it is possible to identify the specific location of a variant or barcode in a UMAP plot? I have a tsv file with barcodes that correspond to specific mutations and I was trying to find a way in which I could find the cells in a UMAP plot that correspond to each of those barcodes?

**Comment by timoast** [comment]
See the `cells.highlight` parameter in `DimPlot` https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/DimPlot
