### ISSUE TITLE
FindMarkers calculates wrong fold-changes when not using Log-Normalization

### ISSUE THREAD

**Issue by Martin-Fahrenberger** [satijalab/seurat#3879]
Hi Seurat-Team,

Thank you for all your work to make single-cell data analysis more accessible.

Issue:

Running FindMarkers() to calculate differential expression, results in wrong fold-changes when any normalization method other than "LogNormalize" was used in the steps before.

FindMarkers() assumes that gene-expression values in the slot "data" are log1p() transformed, and transforms them back using expm1() before calculating the avg_logFC values.  (see line 557 of differential_expression.R)

However this is not true when e.g. relative-counts normalization was used in a previous step ( i.e. NormalizeData(data, normalization.method = 'RC') ). In this case the expression values are wrongfully expm1-transformed, resulting in wrong avg_logFC values.

This behavior is not documented as far as i can tell.

Code Example using the workflow from the 'Guided Clustering Tutorial' (https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html)
```r
library(Seurat)
download.file('https://cf.10xgenomics.com/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz', 'pbmc3k_filtered_gene_bc_matrices.tar.gz')
untar('pbmc3k_filtered_gene_bc_matrices.tar.gz')

pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19/")

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

pbmc.log <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc.rc <- NormalizeData(pbmc, normalization.method = "RC", scale.factor = 10000)

pbmc.log <- FindVariableFeatures(pbmc.log, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc.log)
pbmc.log <- ScaleData(pbmc.log, features = all.genes)
pbmc.log <- RunPCA(pbmc.log, features = VariableFeatures(object = pbmc.log))
pbmc.log <- FindNeighbors(pbmc.log, dims = 1:10)
pbmc.log <- FindClusters(pbmc.log, resolution = 0.5)


pbmc.rc$seurat_clusters <- pbmc.log$seurat_clusters
Idents(pbmc.rc) <- pbmc.rc$seurat_clusters
Idents(pbmc.log) <- pbmc.log$seurat_clusters

cluster1.markers.log <- FindMarkers(pbmc.log, ident.1 = 1, min.pct = 0.25)
head(cluster1.markers.log$avg_logFC, n = 5)
#[1] 0.8373872 0.8921170 0.6436286 0.8147082 0.6253110

cluster1.markers.rc <- FindMarkers(pbmc.rc, ident.1 = 1, min.pct = 0.25)
head(cluster1.markers.rc$avg_logFC, n = 5)
#[1] -29.17163 -77.11944 -27.70286 -40.98704 -85.14630

```
As you can see the calculated avg_logFC values are very different, even though we are comparing the same cells. 

One can manually reconstruct the correct as well as the wrong calculations:

```r
top_genes <- rownames(head(cluster1.markers.log, n = 5))

data_group_1 <- log(1 + rowMeans(expm1(as.data.frame(GetAssayData(subset(pbmc.log, subset = seurat_clusters == 1), slot = 'data')[top_genes,]))))
data_group_2 <- log(1 + rowMeans(expm1(as.data.frame(GetAssayData(subset(pbmc.log, subset = seurat_clusters != 1), slot = 'data')[top_genes,]))))

logfcs_log <- data_group_1 - data_group_2
logfcs_log
#     IL32       LTB      CD3D      IL7R      LDHB 
#0.8373872 0.8921170 0.6436286 0.8147082 0.6253110 

data_group_3 <- log(1 + rowMeans(expm1(as.data.frame(GetAssayData(subset(pbmc.rc, subset = seurat_clusters == 1), slot = 'data')[top_genes,]))))
data_group_4 <- log(1 + rowMeans(expm1(as.data.frame(GetAssayData(subset(pbmc.rc, subset = seurat_clusters != 1), slot = 'data')[top_genes,]))))

logfcs_rc_wrong <- data_group_3 - data_group_4
logfcs_rc_wrong
#     IL32       LTB      CD3D      IL7R      LDHB 
#-29.17163 -77.11944 -27.70286 -40.98704 -85.14630 

data_group_5 <- log(1 + rowMeans(as.data.frame(GetAssayData(subset(pbmc.rc, subset = seurat_clusters == 1), slot = 'data')[top_genes,])))
data_group_6 <- log(1 + rowMeans(as.data.frame(GetAssayData(subset(pbmc.rc, subset = seurat_clusters != 1), slot = 'data')[top_genes,])))

logfcs_rc_correct <- data_group_5 - data_group_6
logfcs_rc_correct
#     IL32       LTB      CD3D      IL7R      LDHB 
#0.8373872 0.8921170 0.6436286 0.8147082 0.6253110 

```

**Comment by andrewwbutler** [comment]
Thanks for bringing this up. We'll work on a fix and update here.

**Comment by Martin-Fahrenberger** [comment]
Hi Seurat Team,
congratulations on publishing Version 4 of Seurat!

However, as far as I can tell this issue has been carried over and is still present in Version 4 of Seurat, can you maybe give an update regarding the progress on this?

I do feel like this is an important issue which may lead to wrong fold-change results being published (if this has not happened already).

**Comment by andrewwbutler** [comment]
Hi @Martin-Fahrenberger ,

Sorry for the delayed response on this. This should be fixed now on the develop branch (v4.0.1.9004). Install instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1).

**Comment by Martin-Fahrenberger** [comment]
Hi Andrew,

Thank you for fixing the issue! The test case above now returns the correct results for both normalizations.

One small thing I noticed while testing this and comparing to the pbmc3k data:
In the new v4 tutorial there is a typo in https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

Due to, what I guess ares some small changes upstream between v3 and v4 the clusters 1 and 2 in the pbmc3k data set change identity. You account for this by setting ident.1=2 instead of 1 to keep the tutorials comparable however it still says cluster 1 in the comment above and the naming of the variables, which could be confusing:

`# find all markers of cluster 1`
`cluster1.markers <- FindMarkers(pbmc, ident.1 = 2, min.pct = 0.25)
head(cluster1.markers, n = 5)`

I didn't want to open a separate issue over this, just thought I d mention it.

Thanks again for the fix and all the great work with Seurat.

Martin

**Comment by andrewwbutler** [comment]
Yep, that's exactly what happened and thanks for pointing out the comment! We'll update the vignette soon to hopefully avoid any confusion here.
