### ISSUE TITLE
Use of cell.highlight for dimplots

### ISSUE THREAD

**Issue by sahh04** [satijalab/seurat#3880]
Hi, 

I was wondering if cell.highlight can be used to specifically highlight cells that correspond to a specific variant that is in a csv or tsv file that contains a list of specific variants. For instance, would it be possible to use WhichCells to find the cells that correspond to specific variants and then pass the result of that to cells.highlight or would I be required to do something different? I apologize if I am not entirely clear about what I'm trying to do, as I am a high school student with limited experience with Seurat, so I can clarify if necessary.

**Comment by saketkc** [comment]
If your variant information  exist in the metadata you could choose to highlight it using (this is just one way of doing it): 

```
var1_cells <- WhichCells(integrated, idents = c("variant1")
var2_cells <- WhichCells(integrated, idents = c( "variant2")
DimPlot(seurat_object, label=T,  cells.highlight= list(var1_cells, var2_cells), cols.highlight = c("blue", "red"), cols= "grey")
```

See the [WhichCells documentation](https://rdrr.io/cran/Seurat/man/WhichCells.html) for more details.

**Comment by sahh04** [comment]
When I checked the metadata, I got something that looked like this: 
![Screenshot 2021-01-26 191730](https://user-images.githubusercontent.com/68067698/106050433-30435c00-60b5-11eb-9246-9d5ba20f2f3b.png) 

However, when I input any variant (even ones listed in the screenshot) into which cells, I get an error saying that they are not found. Is there something I am missing here or doing incorrectly, as I also checked the WhichCells documentation for reference?

**Comment by saketkc** [comment]
It's not there in the metadata. If it is a dataframe with rownames as cell barcodes, you need to add it to the object using [AddMetaData](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/AddMetaData). See [this vignette](https://satijalab.org/seurat/v2.4/interaction_vignette.html) for some examples.
