### ISSUE TITLE
low resolution of dots in plots

### ISSUE THREAD

**Issue by aquiilla** [satijalab/seurat#3881]
Hello,

I had some issues for graph visualization since I have updated R to R4.0.3.
As you can see in the attached images, the resolution of dots in FeatureScatter graph and UMAP plot are really low. 
If you zoom into each dot, the dots do not look like a circle. 
Then I re-installed previous version of R, but this issue still exists.
I would be really appreciated if someone could help me to solve this issue.

Best,
Akira

<img width="412" alt="Screen Shot 2021-01-03 at 6 49 15 PM" src="https://user-images.githubusercontent.com/36237304/103484222-b1307000-4df5-11eb-811a-69f08290d264.png">
<img width="631" alt="Screen Shot 2021-01-03 at 6 49 39 PM" src="https://user-images.githubusercontent.com/36237304/103484223-b55c8d80-4df5-11eb-91cc-7396d6f3e163.png">

**Comment by saketkc** [comment]
Hi Akira, 

The rasterization is switched on by default if you have more than 50k points being plotted. You can switch it off by providing additional argument `raster=FALSE`.

**Comment by aquiilla** [comment]
Thanks for your help! It worked!

On Jan 3, 2021, at 11:01 PM, Saket Choudhary <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Akira,

The rasterization is switched on by default if you have more than 50k points being plotted. You can switch it off by providing additional argument raster=FALSE.
