### ISSUE TITLE
Why graph-based algorithm instead of others?

### ISSUE THREAD

**Issue by jasperhyp** [satijalab/seurat#3882]
E.g., for spatially-resolved data, won't spatial clustering algorithms work better (haven't tested)?

**Comment by timoast** [comment]
The clustering method used will depend to some extend on your goals. If you want to define clusters purely on spatial position then it would make sense to cluster based on physical distance. Typically this is not the goal, and we want to use gene expression information to group the cells. A discussion of the best clustering method to use for single-cell analysis is a bit broad for a Seurat github issue, but there is plenty of discussion of this topic in the literature (eg: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6134335)
