### ISSUE TITLE
Using categorical latent variable for MAST

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#3884]
Hi,

I have a question similar to that in #313.  I would like to use "donor" as a latent variable for MAST analysis in Seurat.  According to the discussion and my attempts, it appears this is not possible as it is categorical rather than numeric.  However, the MAST vignette appears to use a categorical latent variable.  Is this specific to Seurat that a categorical latent variable can't be used for MAST?

Many thanks for the help,
Lucy

**Comment by mojaveazure** [comment]
Hi Lucy,

This should be doable in Seurat by passing the name of the metadata column to the `latent.vars` argument of `FindMarkers`; an example is provided below using a dataset from [SeuratData](https://github.com/satijalab/seurat-data) and a dummy categorical latent variable.

```R
library(Seurat)
library(SeuratData)
data("pbmc3k.final")
pbmc3k.final$groups <- sample(c("g1", "g2"), ncol(pbmc3k.final), replace = TRUE)
x <- FindMarkers(pbmc3k.final, ident.1 = "B", latent.vars = "groups", test.use = "MAST")
```

Let me know if this doesn't work for you or you notice something off about the results.

**Comment by lc822** [comment]
Dear Paul,

Thank you for the response.  I had to adapt the code slightly probably due to version issues (Seurat v3.1.5 and SeuratData v0.2.1).  This might also explain why I am still having issues with using MAST (v1.16.0) in FindMarkers.

Running the following, I am getting the same error as I was with my data:
```
data("pbmc3k")
pbmc3k$groups <- sample(c("g1", "g2"), ncol(pbmc3k), replace = TRUE)
Idents(pbmc3k) <- "seurat_annotations"
x <- FindMarkers(pbmc3k, ident.1 = "CD8 T", latent.vars = "groups", test.use = "MAST")
```

> Error in colMeans(x, na.rm = TRUE) : 'x' must be numeric

Is this something that has been updated in a later version of Seurat?  I am currently reluctant to update for my current project.

Best wishes,
Lucy

**Comment by mojaveazure** [comment]
Hi Lucy,

Ah, yeah we fixed this in the latest version of Seurat (v3.2.3). If you don't want to upgrade your version of Seurat globally, we do provide versioned Docker images that you can use for this one step. You'd have to save your object out as an Rds file, read it in in the Docker version of Seurat, run `FindMarkers`, and save the markers table back out

The following instructions work on macOS and Linux, assuming you have Docker installed

```R
# Using your local Seurat, save your object out
dir.create(file.path(Sys.getenv("HOME"), "seuratdata"))
saveRDS(seurat_object, file.path(Sys.getenv("HOME"), "seuratdata", "object.Rds"))
```

```shell
# In the terminal; for macOS, you can omit the `sudo`
sudo docker pull satijalab/seurat:3.2.3
sudo docker run -it --rm -v $(realpath ${HOME}/seuratdata):/seuratdata satijalab/seurat:3.2.3
```

```R
# In the Docker version of Seurat
# MAST should be installed already
library(Seurat)
seurat_object <- readRDS("/seuratdata/object.Rds")
x <- FindMarkers(seurat_object, ident.1 = "your ident", latent.vars = "donor", test.use = "MAST")
write.table(x, "/seuratdata/mast_markers.tsv", quote = FALSE, sep = "\t", col.names = TRUE, row.names = TRUE)
```

The markers should be available on your local computer at `~/seuratdata/mast_markers.tsv`, which you should be able to read back in with your local Seurat installation

**Comment by lc822** [comment]
Great thank you, I'll give this a go

**Comment by GAgafencu** [comment]
@lucygarner Did the solution provided by @mojaveazure work?
@mojaveazure - I have been trying to use the orig.ident (a variable containing the ID of each donor, ei. batch in my case) as the latent.vars and I get the following warning after sunning this command:

`oetjen_MAST_ageing_DEGs <- FindMarkers(Oetjen_Tcell_subset, ident.1 = ">=66yo", ident.2 = "<=40yo", test.use = "MAST", logfc.threshold = 0, only.pos = F, latent.vars = "orig.ident")`

Warning message:
In .nextMethod(object = object, value = value) :
  Coefficients orig.identB, orig.identC1, orig.identC2, orig.identCk, orig.identF, orig.identG, orig.identH, orig.identJ, orig.identL, orig.identM, orig.identO, orig.identP, orig.identQ, orig.identS1, orig.identS2, orig.identSk1, orig.identSk2, orig.identU, orig.identW are never estimible and will be dropped.

I think this might have to do with how probably the design matrix for the GLM behind MAST takes into account the orig.ident categorical variable, as none of my samples have cells assigned to both ident.1 = ">=66yo" and ident.2 = "<=40yo".

Is there a way to use the Seurat's implementation of MAST and perform differential gene expression in a scenario as described above, in which a batch covariate is used as the  latent.vars parameter?

Thanks a lot for your help,
Grigore

**Comment by lucygarner** [comment]
Hi @GAgafencu,

I decided to update my Seurat to 3.2.3 in the end to make life easier.

Best wishes,
Lucy

**Comment by GAgafencu** [comment]
Hi @lucygarner,

Thanks for the update on how you dealt with this problem. I'm curious if you got a biologically sound list of differential gene expressed genes using the Seurat-implemented MAST with the donor covariate after updating Seurat to 3.2.3.
I'm using for my analyses Seurat 4.0.1, so my error might be related to that, but I'll await @mojaveazure's reply on this issue.

Best wishes,
Grigore

**Comment by lucygarner** [comment]
Hi Grigore,

The list seemed ok to me and matched well with what I got using Wilcoxon and logistic regression, so I am happy with it.

Best wishes,
Lucy

**Comment by GAgafencu** [comment]
Hi Lucy,

Thank you for your feedback on your experience using this differential gene expression methodology. I'm planning to use it in a similar way as soon as I get to the bottom of that warning message.

Best wishes,
Grigore

**Comment by saketkc** [comment]
@brainfo Please see the [MAST paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0844-5) for details.
