### ISSUE TITLE
Label transfer error: vst.set.old[[j]] : subscript out of bounds

### ISSUE THREAD

**Issue by idk89** [satijalab/seurat#3885]
Hi all,
I am using label transfer on my query "allcombined" of 12.9GB with reference as the new 2700pbmc data available at the website.

ref <- LoadH5Seurat("pbmc_multimodal.h5seurat")
>anchors <- FindTransferAnchors(reference = ref, query = allcombined, dims = 1:30)
Performing PCA on the provided reference using 5000 features as input.
Projecting PCA
Error in vst.set.old[[j]] : subscript out of bounds>

The above error is showing. Can someone please help me correct it and get the labels transfered.
I understand my query is a large dataset , still I have to perform this transfer on the allcombined dataset. Please suggest how to fix this.

Thanks!

**Comment by idk89** [comment]
Can some please help me.

**Comment by yuhanH** [comment]
Could you provide more scripts about your normalization?

**Comment by idk89** [comment]
Here is my script:

allC<- merge(H20, y = c(S1, S7, S8,S9, S19, S26,S27,S81, S77, S78, S80, S85, S86, S87, S88,S89,S90,S100,S128,H21), add.cell.ids = c("H20","S1", "S7", "S8","S9", "S19", "S26","S27","S81", "S77", "S78", "S80", "S85", "S86", "S87", "S88","S89","S90","S100","S128","H21"), project = "Headings")
allcombined<- NormalizeData(allC)
allcombined<- FindVariableFeatures(allcombined, selection.method = "vst", nfeatures = 3000)
allcombined<- ScaleData(allcombined, verbose = FALSE)
allcombined <- RunPCA(allcombined, npcs = 30, verbose = FALSE)
allcombined <- RunHarmony(allcombined, group.by.vars = 'Headings')
allcombined <- RunUMAP(allcombined, reduction="harmony", dims = 1:15)
ref <- LoadH5Seurat("pbmc_multimodal.h5seurat")
anchors <- FindTransferAnchors(reference = ref, query = allcombined, dims = 1:30)

Please guide. Thanks!

**Comment by yuhanH** [comment]
HI, 
Our reference is SCTransform normalized, so your query should be normalized in the same way. 
You would better follow our [mapping vignette](https://satijalab.org/seurat/v4.0/reference_mapping.html)
The fist tab `PBMC` shows you how to normalize and map one sample to our PBMC reference. 
The second tab `BMNC` shows you how to map multiple objects to the reference object. It suggests you normalize and map your samples one by one to the reference.

**Comment by idk89** [comment]
@yuhanH 
I have even tried SCTransform, still same error:

allcombined<- SCTransform(allC, vars.to.regress = "percent.mt", verbose = FALSE)
allcombined <- RunPCA(allcombined, vmerged = FALSE)
allcombined<- RunHarmony(allcombined, group.by.vars = 'Headings', assay.use = 'SCT')
allcombined <- RunUMAP(allcombined, reduction = "harmony", dims = 1:20)
ref <- LoadH5Seurat("pbmc_multimodal.h5seurat")
anchors <- FindTransferAnchors(reference = ref, query = allcombined, dims = 1:30)

Please guide. Thanks!

Also tried: 
> anchors <- FindTransferAnchors(reference = ref,query =allcombined,max.features = 2000,normalization.method = "SCT",dims= 1:18)

still same error:
Error in vst.set.old[[j]] : subscript out of bounds>

**Comment by yuhanH** [comment]
Two things. 
First, if your samples have strong batch effect, you cannot run SCTransform for all of them together. It violets the assumption in the sctransform. 
You need to split them and normalize them one by one. 

```
object.list <- SplitObject(allcombined, split.by = "orig.ident")
for (i in 1:length( object.list )) {
    object.list[[i]] <- SCTransform(object.list[[i]], verbose = FALSE)
}
```
Then, using the following command to `FindTransferAnchor`
```
anchors <- FindTransferAnchors(
  reference = reference,
  query = object.list[[i]],
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50
)
```


But for testing, you can use one of your object. You can set `H20` to `pbmc3k` and follow the [mapping vignette](https://satijalab.org/seurat/v4.0/reference_mapping.html)

**Comment by idk89** [comment]
For the first step: I get:

for (i in 1:length( object.list )) {
+   object.list[[i]] <- SCTransform(object.list[[i]], verbose = FALSE)
+ }
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Suggestions please

**Comment by yuhanH** [comment]
Is default assay of `object.list[[i]]` is RNA?

**Comment by idk89** [comment]
Yes.
> object.list[[i]]
An object of class Seurat 
21404 features across 10773 samples within 1 assay 
Active assay: RNA (21404 features, 0 variable features)

**Comment by yuhanH** [comment]
It is a sctransform-version related error. Could you update your sctransform to the latest version, `0.3.2`. 
Also, i would suggest you update our latest release/4.0.0 branch.

**Comment by idk89** [comment]
Even with updated one the error persists.

**Comment by yuhanH** [comment]
That is weird with this sctransform error. If you're able to share the reproducible data (either a download link here or feel free to email directly at yhao@nygenome.org), I can take a look to try and see what happened here.

**Comment by idk89** [comment]
Dear Yuhan,

I have mailed you ( at yhao@nygenome.org) the full R Script along with the RDS file, I am working on.

Here is the Error that I got again.

anchors <- FindTransferAnchors(
+   reference = ref,
+   query = object.list[[i]],
+   normalization.method = "SCT",
+   dims = 1:50
+ )
**Error in vst.set[[x]] : subscript out of bounds**

Please help.
