### ISSUE TITLE
FindIntegrationAnchors on 500k cells

### ISSUE THREAD

**Issue by TapsiS** [satijalab/seurat#3889]
I have 50 samples that I analyzed in 2 batches (~25 samples each, ~250K cells each). Now I am trying to integrate them both. I tried the rpca method with batch 1 as the reference object, but the FindIntegrationAnchors step gets stuck (i.e it keeps on running in parallel mode for 10 hours) without giving any errors/warnings. 

Is there a better way of doing the integration of 2 large datasets with ~250k cells each? I am on a 3T server. Am I doing something incorrectly since the "Finding anchors ..." is really stuck.

```
> head(reference.list)
$b1
An object of class Seurat
33538 features across 251179 samples within 1 assay
Active assay: RNA (33538 features, 4811 variable features)

$b2
An object of class Seurat
33538 features across 320616 samples within 1 assay
Active assay: RNA (33538 features, 4789 variable features)
```
The FindIntegrationAnchors is stuck on "Finding all pairwise anchors".

```
Using a multicore process with 20 cores

finding anchors....4/8
Computing 2500 integration features
Scaling features for provided objects
Finding all pairwise anchors

Using a sequential process

Finding anchors between all query and reference datasets
  |                                                  | 0 % ~calculating  Finding neighborhoods
```

**Comment by timoast** [comment]
Hi, I'd suggest trying reciprocal PCA projection (`reduction="rpca"), which should scale to more cells better than CCA. You can also use rpca in combination with reference-based integration.

**Comment by TapsiS** [comment]
An update on the above issue - I tried rpca + reference integration and the step was completed in 2 days.

**Comment by dlmatera** [comment]
how many cores did you use for parallelization/total gb of ram? I have a similar dataset I am having trouble with

**Comment by TapsiS** [comment]
20 cores on a 2TB server.

**Comment by kaizen89** [comment]
Try setting `dims=1:50` in `FindIntegrationAnchors and `IntegrateData`
