### ISSUE TITLE
Option to scales for area vs. radius in DotPlot() and other improvements

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#389]
Hi,

(1) I'm using DotPlot frequently and noticed that genes that are expressed in relatively small, but still  significant, percentages of cells (say 30% in a given cluster) often have very tiny dots. When comparing to a much bigger dot showing 90% expression, these tiny dots gives the visual impression that the target gene is not expressed, even though 30% expression is already quite a lot in Dropseq/10x UMI datasets. 

I think this is due to the use of `p + scale_radius()` in the `DotPlot()` function, which makes the dot size quadratically smaller for less frequently expressed genes. According to [the ggplot2 documentation](https://ggplot2.tidyverse.org/reference/scale_size.html), `p + scale_size()` might be a better option for visualizing the percentage of cells expressed.

> The size aesthetic is most commonly used for points and text, and humans perceive the area of points (not their radius), so this provides for optimal perception.

So I would suggest adding the option to use `p + scale_size()` in DotPlot() arguments. 

(2) Adding the min and max percentage for scaling the dot size. Sometimes when plotting a few less frequent genes, if the max percentage of all selected genes in all clusters is, say 58%, then the dot with the largest size will correspond to 58%. It would be nice to be able to set `p + scale_radius(limits = c(min.pct=0, max.pct=1))` in DotPlot() arguments to ensure consistency.

(3) The actual default value of `dot.min = 0` does not match the text in the documentation: 
> The fraction of cells at which to draw the smallest dot (default is 0.05). 

Thanks,
Yueqi

**Comment by satijalab** [comment]
We agree with these comments, and will update in a future release (feel free to submit a PR if you have a moment as well :). We will clarify documentation as well.

**Comment by yueqiw** [comment]
Thanks! I don't think I'll have time for the PR, but I look forward to the update!
