### ISSUE TITLE
Integrate 4 samples from CITE-SEQ (RNA+ADT)

### ISSUE THREAD

**Issue by jimklarry** [satijalab/seurat#3890]
Hi Seurat team, I need to integrate multiple samples from  CITE-SEQ which is RNA and ADT (50 Ab). The multi-modal vignette is only for one sample (https://satijalab.org/seurat/v4.0/weighted_nearest_neighbor_analysis.html). I tried the following but am very confused about how to run downstream analyses. How I can combine integrated ADT with integrated RNA? For my cell ranger 5.0 run, I had a combined run for RNA and ADT so each sample contains counts from both RNA as well as ADT. Please guide how can I create Seurat objects and normalize RNA and ADT and combine integrated RNA with integrated ADT as was done for one sample in the Seurat vignette.

remotes::install_github("satijalab/seurat", ref = "release/4.0.0")
remotes::install_github("jlmelville/uwot")
library(Seurat)
require(cowplot)
require(dplyr)
dataset_loc <- "~/CITESEQ/CellRanger5.0"
ids <- c("Sample1_RNAplusADT","Sample2_RNAplusADT","Sample3_RNAplusADT","Sample4_RNAplusADT")

d10x.data <- sapply(ids, function(i){
  print(file.path(dataset_loc,i))
  d10x <- Read10X(file.path(dataset_loc,i))
  print(d10x)
  d10x
})

rna.data <- do.call("cbind", d10x.data["Gene Expression",])
adt.data <- do.call("cbind", d10x.data["Antibody Capture",])

dim(rna.data)
#[1] 35000 20000
dim(adt.data)
#[1]   50 17280

# Is the following way of creating seurat object correct?
rna.seurat = CreateSeuratObject(counts = rna.data)
#Warning: Non-unique cell names (colnames) present in the input matrix, making unique

adt.seurat = CreateSeuratObject(counts = adt.data)
#Warning: Non-unique cell names (colnames) present in the input matrix, making unique
#Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')

# Is this the correct way of integrating and normalizing RNA data from all 4samples?
rna.seurat <- NormalizeData(rna.seurat) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()

# how do I now integrate ADT datasets together?

**Comment by jimklarry** [comment]
Alternatively, I can do this but not sure how to proceed with any downstream (normalization, integration) from after I create the d10x.data object.

d10x.data <- sapply(ids, function(i){
  print(file.path(dataset_loc,i))
  dcite <- Read10X(file.path(dataset_loc,i))
  d10x<- CreateSeuratObject(counts = dcite$`Gene Expression`)
  d10x[['Protein']] = CreateAssayObject(counts = dcite$"Antibody Capture")
})

d10x.data
$Sample1_RNAplusADT
An object of class Seurat 
36738 features across 4822 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
 1 other assay present: Protein

$Sample2_RNAplusADT
An object of class Seurat 
36738 features across 2323 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
 1 other assay present: Protein

$Sample3_RNAplusADT
An object of class Seurat 
36738 features across 4591 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
 1 other assay present: Protein

$Sample4_RNAplusADT
An object of class Seurat 
36738 features across 5527 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
 1 other assay present: Protein

**Comment by yuhanH** [comment]
Hi, 
You can use our integration vignette to integrate both RNA and ADT assays separately. https://satijalab.org/seurat/v3.2/integration.html

For protein integration, you can use CLR to normalize protein data, 
`NormalizeData(bm, normalization.method = 'CLR', margin = 2)`, and follow our [integration vignette](https://satijalab.org/seurat/v3.2/integration.html) to integrate ADT data.  Reciprocal PCA is suggested to integrate ADT data.

**Comment by gabsax** [comment]
Hi @yuhanH,
I have a related question. I have also tried to integrate multiple CITE-SEQ samples from 3 different batches using RPCA. 
I have tried to combine the two seurat objects (one with integrated assay for RNA the other one with integrated for ADT) but he merge() function doesn't work.

I have also tried  in the same seuratobject to integrate first the RNA assay and then the ADT,  but after doing SplitObject() and all the RPCA integration pipeline again  in order to create the new integrated assay for ADT, the integrated assay for RNA previously created doesn't work for downstream analysis.

Hope you can help me out with this, the integration vignette of Seurat works fine but it doesn't say how to combine the integrations coming from different assays.

**Comment by yuhanH** [comment]
Hi, @gabsax 
I would suggest you integrate ADT and RNA in two different objects first. Then, we can create new assays in the integrated RNA object, and add adt related assays there. 
```
integrated_seurat_rna[["IADT"]] <- integrated_seurat_adt[["integrated"]]
integrated_seurat_rna[["pca.adt"]] <- integrated_seurat_adt[["pca"]]
integrated_seurat_rna[["umap.adt"]] <- integrated_seurat_adt[["umap"]]
 ```

**Comment by gabsax** [comment]
Thank you very much @yuhanH 
Everything works now!

**Comment by VitorAguiar** [comment]
Hi @yuhanH,

```
For protein integration, you can use CLR to normalize protein data,
NormalizeData(bm, normalization.method = 'CLR', margin = 2), and follow our [integration vignette](https://satijalab.org/seurat/v3.2/integration.html) to integrate ADT data. Reciprocal PCA is suggested to integrate ADT data.
```

It seems to me that the integration returns either Log Normalized or SCT values. But CLR is recommended for ADT data. I cannot apply CLR manually because the batch-corrected counts are not returned by the integration function. What do you recommend to normalized the integrated ADT data?

**Comment by yuhanH** [comment]
Hi, @VitorAguiar 
You can follow log normalization integration workflow for the CLR normalized ADT data.

**Comment by zincfingers89** [comment]
Hi, 

related to this query - apologies if Ive misunderstood. 

If I use the rcpa method to integrate my ADT data, should I also use the same method to integrate the RNA data?

then once Ive done this combine the data as suggested above:
integrated_seurat_rna[["IADT"]] <- integrated_seurat_adt[["integrated"]]
integrated_seurat_rna[["pca.adt"]] <- integrated_seurat_adt[["pca"]]
integrated_seurat_rna[["umap.adt"]] <- integrated_seurat_adt[["umap"]]

and THEN perform the standard workflow of:
 ScaleData(integrated, verbose = FALSE)
RunPCA(integrated, verbose = FALSE) 
RunUMAP(integrated, dims = 1:30)

is this correct?

thanks

**Comment by yuhanH** [comment]
hi @zincfingers89 
You don't have to use the same integration method for RNA and proteins.  
The amount and quality of proteins in your panel will determine whether you scale protein. You should scale protein expression before and after integration if you have a small high-quality panel.  While you have a large panel, some of proteins don't work well. Then you would better only center and scale protein data.
```
FindIntegrationAnchors(scale = FALSE)
ScaleData(do.scale = FALSE,  do.center = TRUE)
```

**Comment by zincfingers89** [comment]
@yuhanH thanks very much!

**Comment by ghoeltzel38** [comment]
> Hi, You can use our integration vignette to integrate both RNA and ADT assays separately. https://satijalab.org/seurat/v3.2/integration.html
> 
> For protein integration, you can use CLR to normalize protein data, `NormalizeData(bm, normalization.method = 'CLR', margin = 2)`, and follow our [integration vignette](https://satijalab.org/seurat/v3.2/integration.html) to integrate ADT data. Reciprocal PCA is suggested to integrate ADT data.

Hey yuhanH ! - tried following you suggestion but when i get to this step: anchors <- FindIntegrationAnchors(object.list = bm40k.list, reference = c(1, 2), reduction = "rpca", 
    dims = 1:30)
bm40k.integrated <- IntegrateData(anchorset = anchors, dims = 1:30) it seems the ionly possible normalization inputs are SCT and LogNormalize and on top of that even if i dont set a value fro thsi, when i run the code below, i get the following error.

```

raw_pimmune_ADT = CreateSeuratObject(counts = raw_pimmune_biopsy@assays$ADT$counts,
                                        project = "pimmune_ADT",
                                        meta.data = raw_pimmune_biopsy@meta.data)


column_sums = colSums(df > 0)
adt_barcodes = names(which(column_sums > 0))
no_adt_barcodes = names(which(column_sums == 0))

raw_pimmune_ADT  = subset(raw_pimmune_ADT, cells = adt_barcodes)
raw_pimmune_ADT_list = SplitObject(raw_pimmune_ADT, split.by = "orig.ident")

raw_pimmune_biopsy_ADT_norm_list = lapply(X = raw_pimmune_ADT_list, FUN = function(x){
  
  x = NormalizeData(x, normalization.method = 'CLR', margin = 2, verbose = T) %>% ScaleData(features = rownames(x), verbose = TRUE) %>% RunPCA(features = rownames(x), verbose = T)
                                                                   
  return(x)
  
})


features = SelectIntegrationFeatures(object.list = raw_pimmune_biopsy_ADT_norm_list)

anchors = FindIntegrationAnchors(object.list = raw_pimmune_biopsy_ADT_norm_list, reference = c(1, 2), anchor.features = features, scale = F, reduction = "rpca", verbose = T)

anchors = FindIntegrationAnchors(object.list = raw_pimmune_biopsy_ADT_norm_list, reference = c(1, 2), anchor.features = features, scale = F, reduction = "rpca", verbose = T)
Computing within dataset neighborhoods
  |                                                  | 0 % ~calculating  Error in Embeddings(object = object.list[[x]][[nn.reduction]])[, dims] : 
  subscript out of bounds



```
i was trying to integrate ADT data from multiple different samples  but keeps telling me subscrpt is out of bounds

any help would be appreciated

**Comment by ghoeltzel38** [comment]
turns our one of my samples had much fewwer ADT counts across a range of proteins, and so only had 6 PCs which was outside the default number of dimensions.

my separate question is - if i have ADT data and RNA data. and i want to integrated and normalize them separately, but some of the samples have low quality ADT despite high quality RNA. low quality in this case meaning either no ADT data at all or VERY few PCs that do not align with the number of PCs from the other samples, if i remove those samples to normalize and integrate the ADT data, is that ok? can i then integrate those and reinsert them back into the RNA seurat object to create a composite GEX/ADT object and then run the WNN analysis according to this tutorial? or is this extremely problematic / biased given some of the cells/samples have both GEX and ADT while others (but a small minority) only have GEX?
