### ISSUE TITLE
Can I use SCT function to integrate a scaled dataset with an unscaled dataset?

### ISSUE THREAD

**Issue by yuanxiao1988** [satijalab/seurat#3891]
Hello, I am new to Seurat.

Recently, I want to use SCTransform to do some integration analysis.

**My question is: Can I use SCT function to integrate a scaled dataset(value within -1~1) with an unscaled dataset?**

**Comment by yuhanH** [comment]
HI,
SCTransform normalizes `counts` data, so scaled dataset doesn't work in SCTransform.
