### ISSUE TITLE
Reduce the size of a Seurat Object - ScaleData

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#3892]
Dear Seurat Team,

I am struggling to keep the Seurat object within my memory / RAM limit.

I have the following CCA integrated dataset (41 datasets, each downsampled). 

```r
An object of class Seurat 
28690 features across 82000 samples within 2 assays 
Active assay: RNA (26690 features, 0 variable features)
 1 other assay present: integrated
 3 dimensional reductions calculated: pca, umap, tsne
```

### Obervation

- This I can save into a 8GB `.Rds` object. 

- After I calculate `ScaleData()` for the RNA assay the `.Rds` object becomes 26GB.  Exact sizes _in memory_ :

```r
# p$'variables.2.regress'  = NULL
> print(object.size(combined.obj), units = "auto")
7.8 Gb

tic(); combined.obj <- ScaleData(combined.obj, assay = "RNA", verbose = T, vars.to.regress = p$'variables.2.regress'); toc()
> print(object.size(combined.obj), units = "auto")
24.1 Gb

tic(); combined.obj <- ScaleData(combined.obj, assay = "integrated", verbose = T, vars.to.regress = p$'variables.2.regress'); toc()
> print(object.size(combined.obj), units = "auto")
24.1 Gb
```

### Questions

1. Why is the `combined.obj@assays$RNA@scale.data` so huge? 
   1. I guess it's not a sparse matrix, and stored as a normal matrix.
2. How can I make it smaller?
3. It is also not clear to me why adding ScaleData/integrated does not change the size at all. (Its only 2000 genes, but still)

### Trying to solve it

- I am aware of `DietSeurat()`, but this works by removing slots – would not be my goal.
- Rounding up the numbers in `@scale.data` did not help 

```r
rounded.scdat <- round(combined.obj@assays$RNA@scale.data, digits = 2)
view.head(rounded.scdat)
combined.obj@assays$RNA@scale.data <- rounded.scdat
print(object.size(combined.obj), units = "auto")
24.1 Gb
```

- I am surprised that eliminating most digits did not decrease the object size. This rounding to save size works well when saving matrices into .csv files.
    -  This is also[ observed here](https://stackoverflow.com/questions/38652697/r-reducing-digits-precision-for-saving-ram), although not explained why. I guess the way R stores this classes of values.

```r
# BEFORE
> view.head(combined.obj@assays$RNA@scale.data)
CTGATCCCACAAGCCC-1_1 AGAATAGAGTAAGTAC-1_1
AL627309.1          -0.10839875          -0.10839875
AL669831.5          -0.35907276          -0.35907276
LINC00115           -0.09303572          -0.09303572
FAM41C              -0.02871722          -0.02871722
AL645608.7          -0.16244730          -0.16244730
AL645608.1          -0.04892921          -0.04892921
SAMD11              -0.13318995          -0.13318995
NOC2L               -0.44912416          -0.44912416
KLHL17              -0.13462563          -0.13462563
AL645608.8          -0.08671774          -0.08671774

# AFTER
> view.head(round(combined.obj@assays$RNA@scale.data, digits = 2))
CTGATCCCACAAGCCC-1_1 AGAATAGAGTAAGTAC-1_1
AL627309.1                -0.11                -0.11
AL669831.5                -0.36                -0.36
LINC00115                 -0.09                -0.09
FAM41C                    -0.03                -0.03
AL645608.7                -0.16                -0.16
AL645608.1                -0.05                -0.05
SAMD11                    -0.13                -0.13
NOC2L                     -0.45                -0.45
KLHL17                    -0.13                -0.13
AL645608.8                -0.09                -0.09
```

- Unfortunately, scale data cannot be not easily hacked into a sparse matrix:

```r
tbx <- table(rounded.scdat[1:5000, 1:5000])
sorted.values.scaledata <- sort(tbx, decreasing = T)
head(sorted.values.scaledata)
# pie(sorted.values.scaledata)
```
_If you round up to 1 digit (behind 0), and subtract 0.1,  28% of the values are 0. I guess still not worth to store as sparse matrix._

**I would really appreciate some help to reduce the size of the Seurat object into a manageable size. Thanks!**

On: `Seurat               * 3.2.2    2020-09-26`

**Comment by satijalab** [comment]
The Scale Data slot is primarily used for computing dimensional reductions (i.e. PCA). If your goal is to reduce object size, the best approach is to remove the ScaleData slot (for example using DietSeurat). If you need to recompute PCA later, you can always rerun ScaleData.

**Comment by Jaimelan** [comment]
This is still unadressed 5 years after
