### ISSUE TITLE
NormalizeData function doesn't do anything

### ISSUE THREAD

**Issue by bieniu777** [satijalab/seurat#3893]
Hello,

I've never had this problem before but it seems like the NormalizeData function, even though it ran, didn't do anything.
I created a Seurat object from a Single Cell Experiment object (data imported using scRNAseq package)

import Zilionis's data (creates a sce object)
`Zilionis.human <- ZilionisLungData("human")`

create a seurat object from sce object 
`counts <- Zilionis.human@assays@data@listData$counts`
`Zilionis.Seurat <- CreateSeuratObject(counts = counts)`

I couldn't add the metadata file in the code above, I kept getting some errors (metadata was in: Zilionis.human@colData@listData)

I've actually been having problems with AddMetaData function since forever - because even though it would always run - I never saw any metadata in my seurat object after.

So here I've been adding metadata one by one, e.g.
`Zilionis.Seurat[["tissue"]] <- Zilionis.human@colData@listData$Tissue`

And this was fine. 

Then, I wanted to lognormalise my data (for now both "counts" and "data" slots look identical)

I used the following code:
`NormalizeData(Zilionis.Seurat, normalization.method = "LogNormalize", scale.factor = 10000)`

It ran as usual, but when I inspected the seurat object counts and data were still the same (usually the "x" under Dimnames of "data" changes when log-normalised).
I don't understand why it doesn't work.

I tried logging the data differently, manually:

`Log_data <- log(counts +1)`
`Zilionis.Seurat <- SetAssayData(object = Zilionis.Seurat, slot = "data", new.data = Matrix(Log_data, sparse = TRUE))`

But that creates an error:
Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

Any ideas why LogNormalisation doesn't seem to do anything?

**Comment by samuel-marsh** [comment]
Hi,

It appears you aren't saving the object with log normalization.  You need to run:
`Zilionis.Seurat <- NormalizeData(Zilionis.Seurat, normalization.method = "LogNormalize", scale.factor = 10000)`

Best,
Sam

**Comment by bieniu777** [comment]
Hi Sam, 

Such a silly mistake, thank you very much!

You also solved my problem with the AddMetaData at the same time

Kamila
