### ISSUE TITLE
Interpreting Combined Datasets

### ISSUE THREAD

**Issue by adtisch** [satijalab/seurat#3894]
I have a few questions about interpreting merged and integrated datasets.

First, I have an analysis comparing diseased cells with controls, and there are three times as many cells from the diseased samples as from the controls. Some of the sub-clusters from the analysis contain an overwhelmingly high proportion of either the diseased or control cells, but how can one be sure that these patterns are biological in origin and not the product of either the difference in sample sizes or the integration protocol used to put them together.

Second, and unrelated to the first question, I have a set of previously annotated datasets that are now integrated together. I am curious as to why some of the cells in the integration have clustered with cells of types different than their original annotation. For example, all of my B cells appear coherently and without batch effect in a definite cluster, but a modest number appear 'sprayed' across the UMAP.

Finally, in the individual samples before merging or integrating, I have noticed that a few cells are assigned one cluster by the normal unsupervised clustering method:

obj <- FindNeighbors(obj, dims = 1:21)  
obj <- FindClusters(obj, resolution = 0.5) 

... but appear in the UMAP among a different cluster, and I am wondering about a possible explanation for this.

Thank you

**Comment by torkencz** [comment]
Hi,
For your first question I would see how the visualization of the unintegrated merged data compares to the integrated data, also patterns present in the analysis of your individual data should also be present after integration. Second, it could be that you have cells that are "mixed" duplicates and therefore cluster with other cell types or that they are lower quality. I would look at the QC, read depth etc. Finally, the algorithms for learning clusters and visualizations tools (UMAP, tSNE etc.) can pick up on different signals. I can imagine QC would help here too. Hope this helps
