### ISSUE TITLE
Some genes missing from overall analysis

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#3895]
I followed the basic vignette for pbmcs, and I noticed that I am missing some genes post Umap production.  I cannot find these genes with featureplots, so I output a csv of all of the rownames, and genes that I know are there because I can find them in bam files and the cloupe browser are missing. Is there any way to fix this issue. I did scale the data with all genes, so I'm unsure why they're missing from analysis.

**Comment by timoast** [comment]
Are those genes present in the count matrix? Is the total number of cells with >0 counts for those genes greater than the `min.cells` cutoff used in `CreateSeuratObject()`?
