### ISSUE TITLE
DEG analysis, logFC different between for the same gene (wilcox, poisson)

### ISSUE THREAD

**Issue by aelyaderani** [satijalab/seurat#3896]
I ran DEG analysis on the same dataset using 4 different tests (T-test, Wilcox, Poisson, Negbinom)
the logFC value was the same for the each gene using T-test and Wilcox, but different when i used Poisson and Negbinom. They were all ran on the RNA assay. I was going through your source code and it looks like Poisson and Negbinom handle the expression fold differently. Is that because Poisson and Negbinom are setup to handle latent variables? 
![Screen Shot 2021-01-07 at 1 51 37 PM (2)](https://user-images.githubusercontent.com/34661195/103973134-f4f3e400-512b-11eb-85b3-5d3ee273272a.png)

**Comment by k3yavi** [comment]
Hi @aelyaderani ,

May I ask are did you normalize the data before running the differential expression methods ? It's possible that the two group of methods are using normalize / unnormalized data.
