### ISSUE TITLE
Manipulate DimPlot legend

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#3899]
Is there a way to manipulate the legend easily? I need to put everything in one column.

I manage to decrease the size by using
DimPlot(myseuratobject) +  theme_classic(base_size = 4)

But, it yields two columns and it drives me bananas. I have been searching for hours because I do not master the ggplot2 code well, I just cant make it work... It seems like the legend is fixed in a two-column box no matter what you do

![image](https://user-images.githubusercontent.com/48249789/104041751-caf8fb00-51d9-11eb-923c-2af4efee8ca5.png)

**Comment by saketkc** [comment]
All visualizations in Seurat return a ggplot object, so you can easily manipulate the legend using [guides](https://ggplot2.tidyverse.org/reference/guides.). You can request `ncol` to be 1.

```
DimPlot(pbmc)  +  guides(color = guide_legend(override.aes = list(size=4), ncol=1) )
```

**Comment by NicolaasVanRenne** [comment]
Thanks, however, for VlnPlot this does not seem to work. Still two columns. Any idea?

**Comment by yulchen810** [comment]
Hi, 
how can I move the legend to righter, it covered Astrocyte letters, here show only Astrocy
Thank you!
![1710313790213](https://github.com/satijalab/seurat/assets/43404279/44fe7815-dc77-48cd-8acd-a74810a9a8df)
