### ISSUE TITLE
FindClusters not writing out the correct output text file

### ISSUE THREAD

**Issue by MiTPenguin** [satijalab/seurat#39]
I am having trouble with the FindClusters command. Whenever I run it, it always complains that it couldn't find the output text file. The file is not generated, as far as I could tell. The edge text file is generated, however.

I've tried specify temp.file.location, but it still gives me the same issue. Have tried updating R and all packages (including Seurat) and still gives me the same issue.

**Comment by andrewwbutler** [comment]
Could you post the error message in full?

**Comment by MiTPenguin** [comment]
Figured it out! Turned out I had to update the Java on my machine
