### ISSUE TITLE
FindTransferAnchors for large PBMC

### ISSUE THREAD

**Issue by elachtarajax** [satijalab/seurat#3900]
Hello,
I am attempting to annotate a dataset with 60,000 PBMC (RNA-seq) derived cells using your reference 'pbmc_rna' data. 

I used the following code (note project.query =T) but only 11 anchors were identified.
` transfer.anchors <- FindTransferAnchors(reference = pbmc_rna, 
                                        query = data2, 
                                        features = VariableFeatures(object = pbmc_rna), 
                                        reference.assay = "RNA",
                                        query.assay = "RNA", 
                                        project.query = TRUE,
                                        reduction = "pcaproject")`

So when creating predictions, I must run (k.weight < # anchors) 

`predictions <- TransferData(anchorset = transfer.anchors, 
                            refdata = pbmc_rna$celltype,
                            k.weight = 10)`

The query cell predictions appear to be strong, with most of them having scores near 1.. but the annotation appears flawed. I was expecting ~10 cell types from my clustering analyses, but only 3 poorly distributed ones were found.

I tried running the code without `project.query = TRUE,` but only recovered 8 anchors, and ran into a manifold of errors.

What parameter settings do you suggest for finding better anchors? Attached is a picture of the cluster vs the annotation.

**Comment by elachtarajax** [comment]
[clusters.pdf](https://github.com/satijalab/seurat/files/5788441/clusters.pdf)

**Comment by elachtarajax** [comment]
[tsne.pdf](https://github.com/satijalab/seurat/files/5788443/tsne.pdf)

**Comment by yuhanH** [comment]
Hi, 
When you saw small number of anchors, it mainly means something wrong happened in `FindTransferAnchors` step. Some questions about your workflow. 
What is your `pbmc_rna`? 
How are your query and reference normalized? 
Does your pbmc have all major cell types?

I would suggest you try our seurat v4 [mapping vignette](https://satijalab.org/seurat/v4.0/reference_mapping.html).

**Comment by satijalab** [comment]
If your dataset is human PBMC, then it is strange that you are not identifying a large number of anchors. We have not seen this issue even if using a different technology, or diseased dataset.

Most likely it is a minor technical issue, for example your genes are named differently than our reference (our reference uses upper-case names), or there is a mistake in normalization. As Yuhan suggested, also make sure you are following the commands in the mapping vignette.

if you continue to run into problems, please reopen this issue, and we can disucss you sending us a bit of your data to troubleshoot.

**Comment by elachtarajax** [comment]
Hello,
I used the pbmc.rna you provided from (https://satijalab.org/seurat/v3.2/atacseq_integration_vignette.html). 
I normalized, found variable features, and scaled with the defaults as presented in the above vingette.
Still only getting 11 anchors... 
Should I use the mapping vingette data instead? 
Best,
Emily

**Comment by yuhanH** [comment]
HI, @elachtarajax 
Right. You would better use our [mapping vignette](https://satijalab.org/seurat/v4.0/reference_mapping.html), which contains a better reference dataset. Just make sure that you need to normalize your query data by SCTransform.

**Comment by elachtarajax** [comment]
`# Process singlet data
data <-  CreateSeuratObject(counts = singlets_data, project = "CD4", meta.data = meta.data)

# store mitochondrial percentage in object meta data
data <- PercentageFeatureSet(data, pattern = "^MT-", col.name = "percent.mt")

# run sctransform 
data_sc <- SCTransform(data, vars.to.regress = "percent.mt", verbose = FALSE)

# Load in Reference  (pbmc_rna)
reference <- LoadH5Seurat("~/pbmc_multimodal.h5seurat")

# Find Transfer Anchors
anchors <- FindTransferAnchors(
  reference = reference,
  query = data_sc,
  normalization.method = "LogNormalize",
  reduction = "pcaproject",
  dims = 1:10 
)
`
Now getting this error after following the steps ( I tried using the default parameters and got other errors.)
Error in vst.set.old[[j]] : subscript out of bounds
Calls: FindTransferAnchors -> merge -> merge.Seurat -> merge -> merge.Assay

**Comment by elachtarajax** [comment]
I have my data saved as the sctransformed seurat object, perhaps it would help to see the data?

**Comment by yuhanH** [comment]
hi,  @elachtarajax
You may need to use the same parameters used in the vignette. What error you get when you use the below scripts. 

```
anchors <- FindTransferAnchors(
  reference = reference,
  query = data_sc,
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50
)
```

**Comment by elachtarajax** [comment]
Error in FindTransferAnchors(reference = reference, query = data2, normalization.method = "SCT",  : 
  unused argument (reference.reduction = "spca")
Execution halted

**Comment by yuhanH** [comment]
i think you haven't installed seurat4.  
You can install it by this: `remotes::install_github("satijalab/seurat", ref = "release/4.0.0")`
