### ISSUE TITLE
using seurat multimodal reference data to annotate another CITESEQ dataset

### ISSUE THREAD

**Issue by jimklarry** [satijalab/seurat#3901]
<I have my own ADT data and I do not want my ADT data to be replaced by imputed "predicted_ADT" data. "MapQuery is a wrapper around three functions: TransferData, IntegrateEmbeddings, and ProjectUMAP. TransferData is used to transfer cell type labels and impute the ADT values" Is their a way to improve this functionality by allowing user to not overwrite user ADT data with reference ADT data?>

<pbmc3k <- MapQuery(
  anchorset = anchors,
  query = pbmc3k,
  reference = reference,
  refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca", 
  reduction.model = "wnn.umap"
)>

**Comment by yuhanH** [comment]
Hi, 
You ADT data should not be overwrite by the `predicted_ADT`.  Your final object should have both `ADT` and `predicted_ADT` assays. Could you show me the assays in your object?

You can also change predicted ADT assay name in `MapQuery`
```
pbmc3k <- MapQuery(
anchorset = anchors,
query = pbmc3k,
reference = reference,
refdata = list(
celltype.l1 = "celltype.l1",
celltype.l2 = "celltype.l2",
REFADT = "ADT"
),
reference.reduction = "spca",
reduction.model = "wnn.umap"
)
```
