### ISSUE TITLE
h5ad to Seurat Object

### ISSUE THREAD

**Issue by ihgighigh** [satijalab/seurat#3905]
Thank you for creating a very useful tool to convert h5ad files to Seurat objects!

Many h5ad files seem to be of the type 'compound', which precludes successful conversion into Seurat, most notably in metadata transfer (cell type annotations and other annotations are converted from names to numbers).

Could you please indicate how to alter such datasets for a totally successful data conversion?

Any file from this link could be used as an example:
https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728

Thanks!

**Comment by mojaveazure** [comment]
AnnData uses the compound datatypes for versions 0.6 and older. You can update your H5AD file by reading in your H5AD file with AnnData 0.7 or newer and writing it back out to a new H5AD file. SeuratDisk should be able to read in this new H5AD file
