### ISSUE TITLE
All the clusters turn blue by the FeaturePlot

### ISSUE THREAD

**Issue by AndoYutaro** [satijalab/seurat#3907]
When I do the FeaturePlot, I occasionally get an error message which says "All cells have the same value (~number~) of (~gene name~)" and all the clusters turn blue on the figure. Why is this? Please tell me the reason and how to solve it.

**Comment by torkencz** [comment]
Hi, I can imagine that you are specifying a constant feature. In that case feature plot cannot create a color gradient based on your data. I recommend you pull expression values that you are trying to plot across cells to see if the warning makes sense. Another easy visualization would be via the VlnPlot feature.
