### ISSUE TITLE
sample 1 contribute most to cluster 1

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#3910]
what shall I do when the majority of cells in cluster 1 came from sample 1?
what shall I do? is that mean I have batch effect?

**Comment by torkencz** [comment]
It is very likely a batch effect. Also depends on what you are trying to integrate it with and what is the relative heterogeneity of that sample. Seeing as you asked a related question in https://github.com/satijalab/seurat/issues/3911 I will close this issue. Could you provide more information there?
