### ISSUE TITLE
Manipulate VlnPlot legend

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#3912]
following issue 3899

I cannot manipulate the VlnPlot legend with the guides command you taught me in [issue 3899](https://github.com/satijalab/seurat/issues/3899#)

What am I doing wrong? It just won't budge... If it were to be like DimPlot, this should work but it doesnt

VlnPlot(myseuratobject)  +  guides(color = guide_legend(override.aes = list(size=4), ncol=1) )

Thank you so much

**Comment by torkencz** [comment]
Hi, I see. I think it could be due to you specifying the wrong aesthetic here. Can you try guides(fill = guide_legend(override.aes = list(size=4), ncol=1) ). If it does not work I can reopen the issue.

**Comment by erzakiev** [comment]
@NicolaasVanRenne  I also had problems modifying specifically the `VlnPlot`s and I think it's due to the fact that it's a combination plot via `patchwork` (assuming you show multiple parameters like `nFeature`, `nCount`, `mt%`, etc), and thus needs to be treated as such
