### ISSUE TITLE
WNN and the SLM algorithm

### ISSUE THREAD

**Issue by rseurinc** [satijalab/seurat#3913]
I have been running WNN on a large CITEseq data set of over 370000 cells. I integrated the approach in our current pipeline where we used harmony for integration. So as input for the umap and clustering I use the harmony corrected components.
I have no issues with creating the graph, but when running the SLM clustering algorithm the code seems to freeze. I get no error, but the computational and memory load shows the computations have stopped. I first though that this was a scalability issue due to the large number of cells, but it seems driven by the number of dimensions. If I use 30/30 it works, if I increase the number of dimensions it no longer works.

Any suggestions or thoughts?

Ruth

**Comment by yuhanH** [comment]
Hi,  Ruth
we haven't met this issue before. 
Could you show those two UMAPs with 30/30 and more dims? 
Could you also compare the non-zero elements in those two SNN graphs?
