### ISSUE TITLE
VariableFeaturePlot Error: Unknown command for finding variable features

### ISSUE THREAD

**Issue by duocang** [satijalab/seurat#3917]
Hi.

I have met an issue of `VariableFeaturePlot`, the data was processed by `SCTransform`.

```r
data <- readRDS("data.rds")
VariableFeaturePlot(data)
```
Error: Unknown command for finding variable features: 'SCTransform.unspliced_RNA'

I do not really get ideas of the error.

I have uploaded the data in OneDrive: https://1drv.ms/u/s!AtjLM4-mbBLkx9AqLKTG_c3yD-E26g?e=Bylwr3

Thanks!

**Comment by saketkc** [comment]
Since this was processed through SCT, you would want to specify `selection.method` to be `sct`. Also, it seems SCT was run with all the features.

```r
> obj <- readRDS("GSM4625993_sc_1_COPILOT.rds")
> obj
An object of class Seurat 
133961 features across 9759 samples within 6 assays 
Active assay: SCT (21844 features, 21844 variable features)
 5 other assays present: RNA, spliced_RNA, unspliced_RNA, spliced_SCT, unspliced_SCT
 2 dimensional reductions calculated: pca, umap

> VariableFeaturePlot(obj, selection.method = "sct")
```
 
![image](https://user-images.githubusercontent.com/682153/104763793-74894080-5734-11eb-927e-d34003ec7b9e.png)
