### ISSUE TITLE
VlnPlot split.by missing values

### ISSUE THREAD

**Issue by gilstel** [satijalab/seurat#3918]
Hello All

I have 4 samples and have renamed clusters so that I have 10 cell types (T cell, Cancer etc).  I would like to be able to compare the expression level of a single feature (gene) across all cell types (clusters) and samples.  I created the "cell type" identity.
VlnPlot gives this option so I used the following code
``` R
VlnPlot(object = obj.clust, features = "Cd40", assay = "RNA", slot = "data", pt.size = 2.5, group.by = "orig.ident", split.by = "cell.type", split.plot = FALSE)
```

![image](https://user-images.githubusercontent.com/50887514/104238803-2ccb9600-5462-11eb-8476-09606531fecc.png)

The resulting plot displays 4 violin plots, in green, for some cell types (e.g. T cell, Cancer, Fib etc) which present the 4 samples.  In other cases, only 3 violin plots are created (e.g DC and B cell) in red and only 2 in other cases (e.g. EC etc).

I understand that some of the samples are simply missing any values for a given cell type.  I would like the observer to understand which sample is missing altogether from a cell type.  In the case of DCs and since the rotated histogram is too thin so that we cannot see the color, we do not have any information about the sample identity that is missing.  Obviously I can find which is missing by looking at the data itself, but I am looking for a quick solution for displaying all the information on the plot.

In addition, the split.plot parameter could not be set to true since and I received the following warning - 
Split violin is only supported for <3 groups, using multi-violin.
There was no difference whether I used 
``` R
split.plot = TRUE or FALSE
```
I assume the warning message results from some missing values for some cell types.

Anticipated thanks,
Gil

**Comment by torkencz** [comment]
Hi, 
If I were trying to do this I would try to stack these plots by your split sample parameter (if I understand correctly those overlap between cell types). That way you could display samples that are missing by having an empty plot. I know there is a stacked=T or false option, but that is for features. I am thinking along the lines of 
https://divingintogeneticsandgenomics.rbind.io/post/stacked-violin-plot-for-visualizing-single-cell-data-in-seurat/
As for the split plot parameter that only works when you are comparing two things (splits the violin in two),  I'll refer you to https://github.com/satijalab/seurat/issues/3569 to see why.
I hope this helps and let me know how it goes.

**Comment by BrianLohman** [comment]
Hello,

I have this same problem. The legend is alphabetical so that doesn't help infer which violin is which when there are no colors (all of the plots circled in green in your example). It would be great it there was a way to label the violins in each of the plots. So far I haven't been able to find a way to do this. Does anyone know if this is possible? 

Cheers
