### ISSUE TITLE
FeatureScatter() is missing "raster" parameter

### ISSUE THREAD

**Issue by krejciadam** [satijalab/seurat#3921]
Hi!
  I noticed that for more than 50 000 cells, `FeatureScatter()` is plotted in the raster fashion. There is no way to influence this behavior, i.e. turn it on for less cells or off for more cells. I think a `raster` parameter like `DimPlot()` has would be nice here.

Thanks!

**Comment by saketkc** [comment]
Thanks for reporting this. This has been fixed in SeuratV4 and is currently in the `release/4.0.0` branch.
