### ISSUE TITLE
aggregate row counts 

### ISSUE THREAD

**Issue by bmanzato** [satijalab/seurat#3922]
I have a seuratObject, rownames are gene names, not unique in the list, colnames are sample ids.

```
counts <- GetAssayData(seuratObject, assay="RNA", slot="data")
genes <- c("Dmd")
counts <- as.matrix(counts[rownames(counts) %in% genes, ])

# prepare your metadata
metadata <- seuratObject[[]]
metadata <- metadata[rownames(metadata) %in% colnames(counts), ] 

# These can then be used as input to ComplexHeatmap.
heatmap(counts,col = c("cornflower blue","green","red"))
```

What I get is a heat map with n rows (number of times Dmd gene is repeated in the list), what I would like to get is a single row in which all the counts are summed. I think it should be something with rowSums, but I don't know how to apply this to the plot. Does anyone know how to achieve this?

**Comment by torkencz** [comment]
Hi,
I might have misunderstood what you are asking (I tried to replicate it as best as I could). If you are trying to have one row with the sums of all pulled genes I would just use colSums and just plot that with ComplexHeatmap.
