### ISSUE TITLE
Corrected SCT counts and Pearson residuals

### ISSUE THREAD

**Issue by faraz89** [satijalab/seurat#3923]
I have a fundamental question in my head which I am trying to resolve:

1. As I understand SCT corrected 'counts' slot has been corrected for sequencing depth. I notice the manual is refraining from calling this SCT 'counts' slot as normalised counts. Why is that? 

2. What would happen if I input already **sequencing depth corrected** counts prior to running SCTransform? How would that affect the person residuals calculations for GLM model using sequencing depth as covariate? I am assuming If all the cells are already corrected for sequencing depth prior to running SCTransform, that shouldn't be problem and wouldn't break the model. As the calculations are estimated by pooling information across genes that are expressing at similar levels.

Please let me know.

Many thanks,
Faraz.

**Comment by saketkc** [comment]
1. That's correct: corrected counts here reflect counts that have been adjusted for sequencing depth. Seurat uses pearson residuals for all downstream tasks and not the corrected counts. 
2. You are right. If the counts have already been corrected for sequencing depth, the coefficient of UMI covariate in the GLM would be near zero. The pearson residual variance in both cases will be equivalent:

```{r}
vst.3k.glmgampoi <- vst(umi = pbmc3k.allcounts, 
                        method = 'glmGamPoi',
                        return_corrected_umi = T,
                        verbosity = 0)
pbmc3k.correctedcounts <- vst.3k.glmgampoi$umi_corrected

vst.3kcorrected.glmgampoi <- vst(umi = pbmc3k.correctedcounts,
                                 method = 'glmGamPoi',
                                 verbosity = 0)

gene_attr <- vst.3k.glmgampoi$gene_attr
gene_attr$gene <- rownames(gene_attr)
p.1 <- residualVarPlot(gene_attr, "residual_variance") + ggtitle("pbmc3k raw")

gene_attr <- vst.3kcorrected.glmgampoi$gene_attr
gene_attr$gene <- rownames(gene_attr)
p.2 <- residualVarPlot(gene_attr, "residual_variance") + ggtitle("pbmc3k umi-corrected")
    
p.1 | p.2
```
![image](https://user-images.githubusercontent.com/682153/104752951-549e5080-5725-11eb-863d-1c64754173b8.png)

**Comment by duocang** [comment]
Hi.  @saketkc 
You said that:
>That's correct: corrected counts here reflect counts that have been adjusted for sequencing depth. Seurat uses pearson residuals for all downstream tasks and not the corrected counts.

Concerning what you mentioned that `Seurat` takes `sct@scale.data` for downstream instead of corrected counts. Does it mean that `Pearson residuals` more or less work as expression (relatively)? 

Or the downstream you mean does not take expression.

I once got a reply from [ChristophH ](https://github.com/ChristophH/sctransform/issues/95#issuecomment-781239799). He said he would use `SCT@data` as expression which is on an absolute scale, not relative (like `scale.data`).

>`Pearson residuals` states how many standard deviations the observed count is above or below what one would expect if that gene was expressed at a constant level across all cells.
>As expression I would use the normalized counts (counts slot of SCTransform output) or the log1p-transformed normalized counts (data slot of SCTransform output). Both are on an absolute scale and not relative (like scale.data).


**Simply, I would like to know that if I want to compare one gene in two cells. Which data slot is better?**

**Comment by saketkc** [comment]
@erzakiev As we show in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9) pearson residuals are variance stabilized and useful for downstream processing (including PCA/neighbor finding/dimensionality reduction but not for DE). We do recommend using the corrected counts for DE (which as we show in the paper gives more true positives controlling for the same FDR). Hope this clarifies things. But in summary:

- Use pearson residuals for identifying variable features; PCA; dimensionality reduction; integration
- Use corrected counts for DE/visualization of marker genes

A vignette with this exact workflow is [here](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html).
