### ISSUE TITLE
merge splitObject

### ISSUE THREAD

**Issue by fritzherbert** [satijalab/seurat#3927]
Hi!
I have used the function splitObject to split my singlecell RNA seq data based on sample.

I would like to merge this object again in order to split it based on batch instead! How would I best go about that? 

I know I can reassign every seurat object in my list to its own object and then merge these all together with the merge function but sadly my laptop only has 8GB of RAM and gives me the error : Vector limit reached

Is there another way I could unsplit this object without it leading to overload my RAM capacity? 

For reference my object is currently 8.5GB big.

Thank you in advance

**Comment by timoast** [comment]
For merging Seurat objects, use the `merge` function. If you're running out of RAM, you should clear some objects from your R environment. For example, do you still have the original un-split object in the environment? Remove objects using `rm` and force RAM to be cleared using `gc()`
