### ISSUE TITLE
Using Seurat v4 pbmc dataset from preprint as a reference in Integration

### ISSUE THREAD

**Issue by ryandikdan** [satijalab/seurat#3928]
I want to use the pbmc reference from the h5seurat file in your Seurat v4 preprint paper https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat 
as a reference in Integration, but when I try to run PrepSCTIntegration, it give the error

`
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features)

Error in scale.data[anchor.features, ] : 
  no 'dimnames' attribute for array
In addition: Warning message:
In GetResidual(object = object.list[[i]], features = anchor.features,  :
  SCT model not present in assay`
I have loaded the h5suerat called pbmc via LoadH5Seurat and I imported the other data from the HCA PBMC raw data (before I saw that you made a SeuratData version). They both have SCT and it is their defaults. Am I doing anything wrong? Thanks.

**Comment by yuhanH** [comment]
This question is the same with https://github.com/satijalab/seurat/issues/3929. I will answer this question in https://github.com/satijalab/seurat/issues/3929.

**Comment by ryandikdan** [comment]
Woops accidentally submitted it twice.
