### ISSUE TITLE
Can't Integrate with PBMC standard from v4 preprint

### ISSUE THREAD

**Issue by ryandikdan** [satijalab/seurat#3929]
I want to use the pbmc reference from the h5seurat file in your Seurat v4 preprint paper https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat 
as a reference in Integration, but when I try to run PrepSCTIntegration, it give the error

`
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 3000)
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features)

Error in scale.data[anchor.features, ] : 
  no 'dimnames' attribute for array
In addition: Warning message:
In GetResidual(object = object.list[[i]], features = anchor.features,  :
  SCT model not present in assay`
I have loaded the h5suerat called pbmc via LoadH5Seurat and I imported the other data from the HCA PBMC raw data (before I saw that you made a SeuratData version). They both have SCT and it is their defaults. Am I doing anything wrong? Thanks.

**Comment by yuhanH** [comment]
There is no easy way that you can do integrate your object to the reference. 
One way you can do is to start from the RNA raw counts of our pbmc data.
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378
You can split the 3P RNA matrix by donor_time, and then add your objects together to do the integration. 
You can set all samples from time0 as reference in the `FindIntegrationAnchors`

**Comment by ryandikdan** [comment]
Is this because integration requires the raw RNA counts as well as SCT?

**Comment by yuhanH** [comment]
In the SCT assay, the value are not batch effect removed, so you cannot integrate the reference as one object with your objects. But you can use RNA counts of the reference to do the integration. 
[The Mapping vignette](https://satijalab.org/seurat/v4.0/reference_mapping.html) provides alternate way to analyze your query data using our reference.

**Comment by ryandikdan** [comment]
Oh this is exactly what I was looking for, it's a bit hard to keep up with the changing times, but thanks so much!
