### ISSUE TITLE
Two questions about clustering

### ISSUE THREAD

**Issue by Zig-E-Stardust** [satijalab/seurat#3932]
Hey fellas,
I have a couple of questions related to clustering - one specific and one general.
The specific question: 
The attached UMAP plot contains some cells which are categorized as belonging to cluster X, while I think they belong to cluster Y (based on their location and on signature gene expression). As an example, I've marked a few cells whose color (turquoise) indicates they were categorized as belonging to cluster 2, while, in reality, I believe they are more similar to the cells in cluster 3. How can I fix such issues? The only way I managed to do it was by drastically increasing the value of the "resolution" in "FindClusters", but the degree of increase that was needed resulted in creating many dozens of clusters, so, that doesn't seem like a good option.
Anyway, here's the code I've used to generate this UMAP:
`> combined_D4 <- RunPCA(combined_D4, npcs = 30)
> combined_D4 <- RunUMAP(combined_D4, reduction = "pca", dims = 1:20)
> combined_D4 <- FindNeighbors(combined_D4, reduction = "pca", dims = 1:20)
> combined_D4 <- FindClusters(combined_D4, resolution = 0.1)
> DimPlot(combined_D4, reduction = "umap", label = TRUE)`

The general question:
At the risk of showing that my knowledge in the field is limited... What's the best way for determining the values that should be used for "npcs" and "dims" in the above functions?

Cheers,
Omer
![UMAP](https://user-images.githubusercontent.com/56075189/104593876-a33de300-5670-11eb-86e7-c39b73b2ec06.png)

**Comment by timoast** [comment]
See the section "Determine the 'dimensionality' of the dataset" in the PBMC vignette: https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html
