### ISSUE TITLE
Subset error number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#3936]
I have an annoying error and I cant find the cause.
I have an object merged using different samples, I appended the sample name to cell names to avoid duplicate cell names.
The issue is that when I try to subset the object e.g.
```
subset(merge, subset=orig.ident=="L-T2")
number of items to replace is not a multiple of replacement length
```
The subsetted object has less cells than expected
```
length(WhichCells(merge, expression=orig.ident=="L-T2"))
[1] 3911
```
What is weird
```
length(colnames(merge)[merge$orig.ident=="L-T2"])
[1] 4038
```
I checked that there are no duplicated cell names and no NAs.
```
anyDuplicated(colnames(merge))
table(is.na(colnames(merge)))
[1] 0
FALSE 
21710 
```
Has anyone encountered this before?
The current workaround is:
```
merge@active.ident <- factor(merge$orig.ident)
length(colnames(subset(merge, idents="L-T2")))
[1] 4038 
```

**Comment by jaisonj708** [comment]
This is an error thrown by `subset`, perhaps because it is encountering something that cannot be properly subsetted. Can you post the full traceback?

**Comment by GBeattie** [comment]
I would like to add I also see this problem intermittently, unfortunately I can't re-open the issue. Here is my example (637 cells when filtering metadata, but only 255 when subsetting with same parameters), happy to provide more info if needed.

```
> nrow(FetchData(seu, vars = c("cluster.id", "Patient")) %>% filter(cluster.id == "CD8.Trm", Patient == "LTX019"))
[1] 637
> subset(seu, subset = cluster.id == "CD8.Trm" & Patient == "LTX019")
An object of class Seurat 
36707 features across 255 samples within 2 assays 
Active assay: RNA (19582 features, 2000 variable features)
 1 other assay present: SCT
 1 dimensional reduction calculated: umap
Warning message:
In cells.idents["NA"] <- names(x = which(x = is.na(x = Idents(object = object)[cells]))) :
  number of items to replace is not a multiple of replacement length
```

**Comment by MeganS92** [comment]
Hi, I also have this same problem where I am losing cells after subsetting due to the NA values. I have been trying to search through many threads to resolve this to no avail. Could we please get some help? Thanks.

**Comment by laurentbartolo** [comment]
For me doing
Ident(seurat.object)<-"the metadata your are subsetting on"
before running the subset function solve the problem
