### ISSUE TITLE
Best practice with FindTransferAnchors() for SCT Integrated reference and query objects?

### ISSUE THREAD

**Issue by acousticus** [satijalab/seurat#3937]
Hi Seurat Developers,

Sorry for a similar post to my previous issue (https://github.com/satijalab/seurat/issues/3810). I am opening this as I have a related question.

I would like to performing label transfer from one 'atlas' object made of multiple labelled reference datasets, integrated with ```IntegrateData(normalization.method = "SCT")``` to a query object also made with ```IntegrateData(normalization.method = "SCT")``` from data without cell labels. 

In brief, ```FindTransferAnchors(normalization.method = 'LogNormalize')``` will work when both assays are set to 'integrated.' However this seems counterintuitive as they were normalised with SCT?

```FindTransferAnchors(normalization.method = 'SCT', features = common_features)``` will work when both assays are set to 'SCT' and I define the common features.

**I am wondering what is the most appropriate option for analysis? I would have thought it's best to use the 'integrated' assay with normalization.method = 'SCT', but this does not work.** Below is some example code and the errors it generates.

Many thanks in advance for your help, and for the excellent package.

...

I make two integrated objects: 
- 'atlas' based on integrated multiple reference datasets with cells labelled 
- 'patients_integrated' object which is made up of unlabelled query cells

```
library(Seurat)
library(tidyverse)

SCT_integrate_wrapper <- function(objects_to_integrate){
    to_integrate <- map(objects_to_integrate, SCTransform, method = 'glmGamPoi')
    integration_features <- SelectIntegrationFeatures(object.list = to_integrate, nfeatures = 3000)
    to_integrate <- PrepSCTIntegration(object.list = to_integrate, anchor.features = integration_features)
    integration_anchors <- FindIntegrationAnchors(object.list = to_integrate, normalization.method = "SCT", anchor.features = integration_features)
    integrated <- IntegrateData(anchorset = integration_anchors, normalization.method = "SCT")
    integrated <- RunPCA(integrated)
    integrated <- RunUMAP(integrated, dims = 1:30, return.model=TRUE)
    return(integrated)
}

references = list(ref_1,ref_2,ref_3)
atlas <- SCT_integrate_wrapper(references)

patients = list(patient_1,patient_2)
patients_integrated <- SCT_integrate_wrapper(patients)
```

I try to run FindTransferAnchors() to proceed with MapQuery()
```
DefaultAssay(atlas) <- 'integrated'
DefaultAssay(patients_integrated) <- 'integrated'
anchors <- FindTransferAnchors(reference = atlas, query = patients_integrated, dims = 1:30) 
```
This works, but the, default is normalization.method = 'LogNormalize'. Is this appropriate given the ref and query datasets were generated with SCTransform integration?

If I add in ```normalization.method = "SCT"``` I get this error. 
```
DefaultAssay(atlas) <- 'integrated'
DefaultAssay(patients_integrated) <- 'integrated'
anchors <- FindTransferAnchors(reference = atlas, query = patients_integrated, dims = 1:30, normalization.method = "SCT") 
# Error: Given query.assay (integrated) has not been processed with SCTransform. Please either run SCTransform or set normalization.method = 'LogNormalize'.
```

I then change both object assays to SCT...
```
DefaultAssay(atlas) <- 'integrated'
DefaultAssay(patients_integrated) <- 'SCT'
anchors <- FindTransferAnchors(reference = atlas, query = patients_integrated, dims = 1:30, normalization.method = "SCT")
# Error: Given reference.assay (integrated) has not been processed with SCTransform. Please either run SCTransform or set normalization.method = 'LogNormalize'.
```
```
DefaultAssay(atlas) <- 'SCT'
DefaultAssay(patients_integrated) <- 'SCT'
anchors <- FindTransferAnchors(reference = atlas, query = patients_integrated, dims = 1:30, normalization.method = "SCT")
# Error: No features to use in finding transfer anchors. To troubleshoot, try explicitly providing features to the features parameter and ensure that they are present in both reference and query assays.
```

The following code will run successfully
```
DefaultAssay(atlas) <- 'SCT'
DefaultAssay(patients_integrated) <- 'SCT'
common_features <- lapply(list(atlas,patients_integrated), row.names) %>% Reduce(intersect, .) 
anchors <- FindTransferAnchors(reference = atlas, query = patients_integrated, dims = 1:30, normalization.method = "SCT", features = common_features)
```

**Comment by jaisonj708** [comment]
As of now, you can only run our transfer workflow with `normalization.method = SCT` when both query and reference have been SCTransformed. I suggest using the default `normalization.method` if you are trying to transfer from one integrated object to another.

**Comment by Wnivers** [comment]
Hello,

I have exactly the same issue.

What do you mean by " using the default normalization.method if you are trying to transfer from one integrated object to another."?
Do you mean using "LogNormalize" ?

Thank you.
