### ISSUE TITLE
StackedViolin plot 

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#3938]
I made a stacked violin plot with 16 different clusters. I have also attached the figure. 
Here is the code:

#Stacked violine plots

modify_vlnplot<- function(obj, feature, pt.size = 0, 
                          plot.margin = unit(c(-0.75, 0, -0.75, 0), "cm"),
                          ...) {
  p<- VlnPlot(obj, features = feature, pt.size = pt.size, ... )  + 
    xlab("") + ylab(feature) + ggtitle("") + 
    theme(legend.position = "none", 
          axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(),
          axis.title.y = element_text(size = rel(1), angle = 0), 
          axis.text.y = element_text(size = rel(1)), 
          plot.margin = plot.margin ) 
  return(p)
}
extract_max<- function(p){
ymax<- max(ggplot_build(p)$layout$panel_scales_y[[1]]$range$range)
return(ceiling(ymax))
}
StackedVlnPlot<- function(obj, features,
pt.size = 0,
plot.margin = unit(c(-0.75, 0, -0.75, 0), "cm"),
...) {
plot_list<- purrr::map(features, function(x) modify_vlnplot(obj = obj,feature = x, ...))
# Add back x-axis title to bottom plot. patchwork is going to support this?
plot_list[[length(plot_list)]]<- plot_list[[length(plot_list)]] +
theme(axis.text.x=element_text(angle = 45, hjust = 1, vjust = 1),
axis.ticks.x = element_line())
# change the y-axis tick to only max value
ymaxs<- purrr::map_dbl(plot_list, extract_max)
plot_list<- purrr::map2(plot_list, ymaxs, function(x,y) x +
scale_y_continuous(breaks = c(y)) +
expand_limits(y = y))
p<- patchwork::wrap_plots(plotlist = plot_list, ncol = 1)
return(p)
}
StackedVlnPlot(obj = S1, features = features)

Now, I want to make a plot with 5 coloumns instead of 16 coloumns. Four selected clusters/coloumns and one last column conatining total/average expression of rest (12) of clusters. Please tell me how I can do this. Thanks in advance, looking forward for a positive response.  

[27Nov_Stacked_Violine_M.pdf](https://github.com/satijalab/seurat/files/5824643/27Nov_Stacked_Violine_M.pdf)

**Comment by timoast** [comment]
Unfortunately we don't have the bandwidth to write custom code for users, so this is beyond the scope of the Seurat issues. I suggest you ask for help on a general support forum such as bioinformatics stack exchange, biostars, etc.
