### ISSUE TITLE
Why cluster marker genes disappeared/appeared in VLnPlot with less or more clusters defined?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#3939]
Hi there, 

I tune the number of variable genes in RunPCA(), and resolution in FindCluster(), and obtained different cluster results. My question is why some marker genes in VLnPlot(), which takes input from all genes (and not just marker genes or just variable genes), lost or gained expression with less or more clusters? Shouldn't this marker gene stay the same at expression level regardless of the number of clusters I obtained?

Would you mind helping me to find the mistakes in my codes below and to understand this issue? 

Thank you so much for your help!

**When more clusters got defined, there is this gene shown up in VLnPlot. Also, do these clusters look right? Some are so tiny and not sure if they are already real.**

![image](https://user-images.githubusercontent.com/62179082/104828589-ef507980-5862-11eb-8d5e-4490d91b6c9b.png)

![image](https://user-images.githubusercontent.com/62179082/104852466-15bdf580-58f3-11eb-815c-ef27b22b0260.png)

![image](https://user-images.githubusercontent.com/62179082/104853293-bd3d2700-58f7-11eb-971f-334597726b9f.png)

**When I have less clusters, the pink gene above, for example, now shows no expression level across clusters in VLnPlot** While other genes that did not show the expression on this plot, now do in certain clusters.

![image](https://user-images.githubusercontent.com/62179082/104860029-2f763180-5921-11eb-8639-10985f4f2e2f.png)

```
cd8.data <- Read10X(data.dir = "/t1-data/user/qnguyen/DATA/scRNASeq/ANALYZED/")
cd8_sct <- CreateSeuratObject(counts = cd8.data, min.cells = 9, min.features = 20)
cd8_sct <- PercentageFeatureSet(cd8_sct, pattern = "^MT-", col.name="percent.mt")
cd8_sct <- subset(cd8_sct, subset = nFeature_RNA > 20 & nFeature_RNA < 4000 & percent.mt < 25)

# default = 3000 variable genes
# default = do.scale=FALSE and do.center=TRUE
cd8_sct <- SCTransform(cd8_sct, vars.to.regress = "percent.mt", verbose = FALSE, variable.features.n=5000)

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
cd8_sct <- CellCycleScoring(cd8_sct, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

cd8_sct <- RunPCA(cd8_sct, features = c(s.genes, g2m.genes))

cd8_sct$CC.Difference <- cd8_sct$S.Score - cd8_sct$G2M.Score

# Setting do.scale=TRUE, recentering by setting do.center=TRUE
cd8_sct <- ScaleData(cd8_sct, vars.to.regress = "CC.Difference", features = rownames(cd8_sct), do.scale=TRUE, do.center=TRUE)

cd8_sct <- RunPCA(cd8_sct, features = c(s.genes, g2m.genes))
DimPlot(cd8_sct)

cd8_sct <- RunPCA(cd8_sct, verbose = FALSE)

# Using max PCs 50
cd8_sct <- RunUMAP(cd8_sct, dims = 1:50, verbose=FALSE)

cd8_sct <- FindNeighbors(cd8_sct, dims = 1:50, verbose=FALSE)

# Set resolution = 1.5
cd8_sct <- FindClusters(cd8_sct, verbose=FALSE, resolution = 1.5)
DimPlot(cd8_sct, label = TRUE)

cd8_sct.markers <- FindAllMarkers(cd8_sct, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
VlnPlot(cd8_sct, features = "ICOS")





```

**Comment by timoast** [comment]
I would not expect to get the same differential expression results if you use different groupings of cells (different clustering results). You are changing the comparisons you make, so it makes sense that the fold change and p-value will also change.
