### ISSUE TITLE
Integration while preserving cross-sample variance

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#3941]
I will try to explain as clear as possible, bear with me.   I am trying to annotate cell types of ~200k cells.  I am using a reference of ~80K cells.  This reference is composed 14 different datasets from the same tissue region.  7 datasets come from donor 1, and 7 datasets come from donor 2.  I want to integrate the reference datasets together, to remove batch effects from the anchor finding process.  I read from [this paper](https://pubmed.ncbi.nlm.nih.gov/31178118/)  that the integration vectors are the differences between corresponding gene counts of separate samples, and they are assumed to represent batch effects.  This does not distinguish between differences in expression due to batch vs differences in expression due to cross sample variance, which lead me to this idea:
What if we did a "stratified" integration of the reference datasets?  What I mean is that we integrate all of donor 1 datasets together, and integrate all of donor 2 datasets together.  That way we can get rid of some batch effects but still keep the differences between donors untouched.  Then simply merge the integrated assays into one dataset.  To merge datasets, it is important that both integrations use the same features to integrate. This would require the use of `SelectIntegrationFeatures` before integration, pulling a user-specified number of common variable features from all 14 datasets.

This would preserve transcriptomic differences between donor 1 and 2 that are due to genotype, environment etc.  and might cast a wider net when finding transfer anchors for cell-type annotation.

**Comment by timoast** [comment]
Yes, that sounds like a reasonable approach. You can effectively decide which differences to remove based on how you design the integration. I would still recommend using the raw (non-corrected) data for differential expression, and including batch as a latent variable.

**Comment by danielcgingerich** [comment]
@timoast thanks for you response!  I plan on integrating the reference dataset this way, only to use for cell type annotation.  I will be sure to use the raw non-corrected data for DE analysis as recommended unless other methods become available
