### ISSUE TITLE
Cell Hashing and WNN

### ISSUE THREAD

**Issue by yw2875** [satijalab/seurat#3942]
Hi there,

First of all, thank you guys for the amazing package and updates!

I am trying to analyze a CITE-seq data set of a library prepared with a few of the barcoded antibodies and the hashtags for the sample souce.

And when I am trying to analyze the data, I managed to create a project with both the RNA and ADT assays. However, I am stuck because I want to incorporate my antibody information but exclude the hashtag information when I am running the PCA(the hashtags are in all of the PCs right now).

Alternatively, I have tried another route that I was trying to subset the cells with one of the hashtags frist, but it went like:
DefaultAssay(CD3) <- 'ADT'
VlnPlot(object = CD3, features = c("Hashtag2-TotalSeqC"))
Hashtag2<- subset(x = CD3, "Hashtag2-TotalSeqC" > 1.5)
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found: 

Could you guys kindly help me with the problem? Thank you so much!

Best regards,
Flora

**Comment by yuhanH** [comment]
HI, 
I would suggest you create a `HTO` assay which is used to do the demultiplexing. You can follow this [hashing vignette](https://satijalab.org/seurat/v3.2/hashing_vignette.html).
For the subset function, `Hashtag2<- subset(x = CD3, subset = Hashtag2-TotalSeqC > 1.5)` when you remove `"` on the gene, it should work.

**Comment by yw2875** [comment]
Hi,

Thans for the prompt reply!

For the " part, I tried both with and without ", I have also tried adt_Hashtag2-TotalSeqC and "adt_Hashtag2-TotalSeqC". Seemed not working.

For the hasing vignette, I looked at it. I guess my problem is, the file that I have in hand is h5 file. The assay I have right now is a combination of some of the markers+hashtag. So if I directly use HTODemux(), I would be incoporating some of the markers I do not want. And where I am stuck right now is, I cannot seperate the hashtag from other markers.

Sorry for the complication.

**Comment by yuhanH** [comment]
hi, 
the subset may be the same situation with this issue https://github.com/satijalab/seurat/issues/3666
We will fix it soon. You use this way to get the cells you need. 
```
select.cells <-   Cells(obj)[which(obj[["ADT"]]@data["Hashtag2-TotalSeqC" ,] > 1.5)]
obj.sub <- subset(obj, cells = select.cells )
```

For the hashing issue, you can set your `adt.features` and `hto.features` manually, and then separate the h5-ADT matrix into two matrices.

**Comment by yw2875** [comment]
Hi!

Thank you for the kind and patient reply!

I tried to solve the problem with the answer from another issue #1936. And I managed to do it with the following code:
CD3 <- CreateSeuratObject(counts = cd3.data$`Gene Expression`)
#check the row names in the antibody capture
rownames(cd3.data$`Antibody Capture`)
# adt and hto are vectors of the feature names for ADT and HTO
ADTs <- cd3.data$`Antibody Capture`@Dimnames[[1]][1:7]
ADT <- cd3.data$`Antibody Capture`[ADTs, ]
HTOs <- cd3.data$`Antibody Capture`@Dimnames[[1]][8:9]
HTO <- cd3.data$`Antibody Capture`[HTOs, ]
# Confirm that the HTO have the correct names
rownames(ADT)
rownames(HTO)

Again, thanks so much!

Flora

**Comment by yw2875** [comment]
<img width="472" alt="Screen Shot 2021-01-17 at 9 14 17 PM" src="https://user-images.githubusercontent.com/77592803/104868456-00ec5c80-5909-11eb-9795-e66407979c4b.png">
