### ISSUE TITLE
Salvaging questionable results from HTODemux?

### ISSUE THREAD

**Issue by amyh25** [satijalab/seurat#3943]
Hello, 

I was hoping that you could help me use Seurat to demultiplex hashtag antibodies in a sample, after sequencing and mapping. One sample which I am attempting to demultiplex using HTODemux does not look like the demultiplexing worked well and I'm not sure what parameters to change or other methods that I could try to improve it. 

The sample has two HTOs, and HTODemux was run on CLR normalized data with the default parameters, except that the positive.quantile threshold was set to 0.9. I've attached the violin plot showing the RNA counts, the FeaturePlot showing the expression of the two HTOs, and the ridge plots. 

![vln_ncount_rna_sample_f1](https://user-images.githubusercontent.com/69822551/104874433-fa69df00-5920-11eb-8114-b7804b7bb05b.png)

![sample_f1_hash ID_hashtag1_hashtag2](https://user-images.githubusercontent.com/69822551/104874382-d1494e80-5920-11eb-9ef6-192378bfe4a9.png)

![ridge_hto_sample_f1_hash ID](https://user-images.githubusercontent.com/69822551/104874600-4ddc2d00-5921-11eb-84c0-1bdc6c34e81e.png)

We also ran samples with three HTOs, and the demultiplexing didn't have the triangular artifact observed in the FeaturePlot, and the demultiplexing seemed more reasonable. My questions are: 

- Does the clustering method implemented by the HTODemux algorithm work when there are only two HTOs?
- Is it reasonable to trust these results? 
- If not, is there another reasonable method for demultiplexing the samples? For instance, manually "gating" the samples to assign cell ID?
- If the problem is with the sequencing itself, what could be done in future to improve the quality for better demultiplexing?

Thank you in advance!

**Comment by torkencz** [comment]
Hi,

HTODemux should be able to work if there are two HTOs so I would trust these results. I think something went wrong with your staining as your data does not separate well. I personally like to calculate an entropy measure and plot on cells as an alternative visualization method, but I don't know if it will help here.

**Comment by AnaHowellsFerreira** [comment]
Hi torkencz, 

I looked at 2 posts where you suggested the same strategy of calculating shannon entropy. Could you share an example of how you did it and what kind of insight you got from calculating entropy? 

Throughout the QC, I noticed how antibody binding was suboptimal for my experiment, so I played with HTOdemux() parameter percent.quantile to maximize singlets, keeping in mind the changes in negative and doublet calls. I just want to make sure I am not "cherry picking". I think optimizing the pq was recommended, especially considering biology is different for cell type, treatment, etc, but nonetheless, I would like to be able to justify my choice. 
Thank you!!
