### ISSUE TITLE
Availability of scale.data slot in multi-modal PBMC dataset

### ISSUE THREAD

**Issue by keshav-motwani** [satijalab/seurat#3947]
Hi!

I was going through your tutorial here: https://satijalab.org/seurat/v4.0/reference_mapping.html with data from https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat. 

I was wondering whether the Pearson residuals from the SCTransform normalization are available somewhere for this dataset? I do not see them in object@assays$SCT@scale.data (it is a 0 x 0 matrix). Additionally, I cannot regenerate it from the raw counts matrix, as the only data I see is the SCTransform-corrected count matrix (object@assays$SCT@counts), and the log1p version of this (object@assays$SCT@data). 

If this data isn't currently available (either the raw counts, or Pearson residuals, or both), if that could be made available I think it would be extremely useful for the community!

Thanks,
Keshav

**Comment by yuhanH** [comment]
Hi,
In order to keep our reference object as a small size object, the RNA counts and SCT residuals are not stored there.  
You can find the RNA counts in the below link:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378
