### ISSUE TITLE
Inconsistent Background Expression

### ISSUE THREAD

**Issue by schulzett** [satijalab/seurat#3949]
We are performing a simple control vs stimulated analysis of single cell data from the same tissue. Great care was taken to ensure that the samples were both handled the same. For many genes of interest when split by condition we see there is expression in nearly all cells for one dataset, but more unique to clusters in the other. This effect can also be seen in the differential gene expression analyses per cluster with the pct1 vs. pc2 values as shown in image. This effect can also be seen when examining for gene expression (splitting by treatment condition) using the FeaturePlot function. We are curious if this is common or perhaps an issue/artifact being introduced during data normalization or integration?

![image](https://user-images.githubusercontent.com/35879921/105068589-bcff7180-5a46-11eb-84d4-7a743d06926c.png)

![image](https://user-images.githubusercontent.com/35879921/105069044-1f587200-5a47-11eb-875d-b3b4ebfb5a0a.png)

Notice in above images the expression of a gene can be seen in nearly all cells in one condition, but more cluster specific in the other. The same effect is also seen in the table where pct1 cells contain more instances of expression for a gene where pct2 is much lower. All feedback is much appreciated. Thank you!!

**Comment by dnev1551** [comment]
@schulzett I am very interested in this too. Hopefully, @satijalab can give a quick explanation for this phenomenon! Thanks, @satijalab !!!

**Comment by timoast** [comment]
> We are curious if this is common or perhaps an issue/artifact being introduced during data normalization or integration?

Are you running DE on integrated data here? If so that would explain why there could be a shift in corrected expression values. We do not recommend using integrated data for DE, as explained in previous issues.

**Comment by dnev1551** [comment]
@timoast thanks for the response! Do you recommend we use SCTransform as opposed to just normal normalization? We are noticing cell differentiation and it is causing us a headache in clustering and cell identity! Thanks!

**Comment by Tomer9w** [comment]
Hi
Having similar issues.. Did you end up understanding why/how it happened and fixed it? @dnev1551 @schulzett
