### ISSUE TITLE
Error in using FindIntegrationAnchors and SCTransform with 'RPCA' workflow

### ISSUE THREAD

**Issue by lovebaboon1989** [satijalab/seurat#3950]
Hi there, I used 'SCTransform' before using 'FindIntegrationAnchors' to deal with multiple datasets. When there are only 2 datasets to deal with, the code runs well; While when there are 10 datasets for integration, there is an Error after running 'FindIntegrationAnchors' function: 
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=05s
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds

And here is my code:
#######################################################
data1 <- Read10X(data.dir = "D:/new_ma/2020-S-20-1009_RGC_ON_scRNAseq/1__cellranger_output/MsON1mpi-1/raw_feature_bc_matrix/")
data2 <- Read10X(data.dir = "D:/new_ma/2020-S-20-1009_RGC_ON_scRNAseq/1__cellranger_output/MsON1mpi-2/raw_feature_bc_matrix/")
pbmc1 <- CreateSeuratObject(counts = data1, project = "MsON1mpi-1", min.cells = 5, min.features = 500)
pbmc2 <- CreateSeuratObject(counts = data2, project = "MsON1mpi-2", min.cells = 5, min.features = 500)
pbmc1 <- PercentageFeatureSet(pbmc1, pattern = "^mt-", col.name = "percent.mt")
pbmc1 <- PercentageFeatureSet(pbmc1, pattern = "^Rp[sl]", col.name = "percent.ribo")
pbmc2 <- PercentageFeatureSet(pbmc2, pattern = "^mt-", col.name = "percent.mt")
pbmc2 <- PercentageFeatureSet(pbmc2, pattern = "^Rp[sl]", col.name = "percent.ribo")

merged<-merge(pbmc1,pbmc2)

pbmc.list <- SplitObject(merged, split.by = "orig.ident")
for (i in 1:length(pbmc.list)) {
  pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], vars.to.regress = c("nFeature_RNA", "nCount_RNA","percent.mt", "percent.ribo"))
  pbmc.list[[i]] <- RunPCA(object = pbmc.list[[i]], verbose = FALSE)
  
}
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 5000)
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features)
pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT", 
                                       anchor.features = pbmc.features,reduction = "rpca")
###########################################################
I would repeat my question as: The code runs well when there are only 2 datasets for integration (data1,data2), but when there are 10 datasets to integrate (data1~data10), the Error above emerges.
I noticed that people had the same situation as me: Issue #3730 （Error in RPCA workflow to integrate data）, hoping that now this bug we met with can be solved. Many thanks.

**Comment by yuhanH** [comment]
I think the issue is related to the `RunPCA` step. You should set `pbmc.features` and then `RunPCA`
```
for (i in 1:length(pbmc.list)) {
pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], vars.to.regress = c("nFeature_RNA", "nCount_RNA","percent.mt", "percent.ribo"))
}
pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 5000)
pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features)

for (i in 1:length(pbmc.list)) {
pbmc.list[[i]] <- RunPCA(object = pbmc.list[[i]], verbose = FALSE, features = pbmc.features)
}
pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT",
anchor.features = pbmc.features, reduction = "rpca")
```
If it doesn't work, I will open this issue.

**Comment by lovebaboon1989** [comment]
> I think the issue is related to the `RunPCA` step. You should set `pbmc.features` and then `RunPCA`
> 
> ```
> for (i in 1:length(pbmc.list)) {
> pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], vars.to.regress = c("nFeature_RNA", "nCount_RNA","percent.mt", "percent.ribo"))
> }
> pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list, nfeatures = 5000)
> pbmc.list <- PrepSCTIntegration(object.list = pbmc.list, anchor.features = pbmc.features)
> 
> for (i in 1:length(pbmc.list)) {
> pbmc.list[[i]] <- RunPCA(object = pbmc.list[[i]], verbose = FALSE, features = pbmc.features)
> }
> pbmc.anchors <- FindIntegrationAnchors(object.list = pbmc.list, normalization.method = "SCT",
> anchor.features = pbmc.features, reduction = "rpca")
> ```
> 
> If it doesn't work, I will open this issue.

Hi Yuhan,
Thanks for the reply, I adapted exactly the same code you provided but unfortunately it does not work, and the error happens in the 1st round  of the 1st for loop, and it seems that the function 'SelectIntegrationFeatures' cannot proceed, and the error information is:
error: The following assays have not been processed with SCTransform:
 object: 2 - assay: RNA
 object: 3 - assay: RNA
 object: 4 - assay: RNA
 object: 5 - assay: RNA
 object: 6 - assay: RNA
 object: 7 - assay: RNA
 object: 8 - assay: RNA
 object: 9 - assay: RNA
 object: 10 - assay: RNA
In another version of the code, I wrote as follows:
for (i in 1:length(pbmc.list)) {
  pbmc.list[[i]] <- SCTransform(pbmc.list[[i]], vars.to.regress = c("nFeature_RNA", "nCount_RNA","percent.mt", "percent.ribo"))
  pbmc.features <- SelectIntegrationFeatures(object.list = pbmc.list[[i]], nfeatures = 5000)
  pbmc.list[[i]] <- PrepSCTIntegration(object.list = pbmc.list[[i]], anchor.features = pbmc.features)
  }
Unfortunately, there is also an error in the 1st round of the 1st for loop:
Error in as.list.default(X) : no method for coercing this S4 class to a vector

So this could not work...

**Comment by ahdee** [comment]
@lovebaboon1989 thanks - I tried this on the panc8 dataset. But it fails during the IntegrateData, can you help me with this? 

```

library(Seurat)
library(SeuratData)
library(SeuratWrappers)

library (panc8.SeuratData )
data("panc8")
# my is ver 4  so  I need to update the data 
panc8<-UpdateSeuratObject(panc8)
 


# preprocess set 

pancreas.list <- SplitObject(panc8, split.by = "tech")

pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]


for (i in 1:length(pancreas.list)) {
   pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], vst.flavor = "v2", verbose = TRUE  ) 
}



pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 5000)
pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features)

for (i in 1:length(pancreas.list)) {
  pancreas.list[[i]] <- RunPCA(object = pancreas.list[[i]], verbose = FALSE, features = pancreas.features)
}

pancreas.anchors <- FindIntegrationAnchors(object.list = pancreas.list, normalization.method = "SCT",
                                       anchor.features = pancreas.features, reduction = "rpca")



pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, dims = 1:30, normalization.method = "SCT")
```

ERROR 
```
Integrating data
Error in validObject(.Object) : 
  invalid class “Assay” object: Keys must be a one-length character vector

```

**this is my enviroment:** 
Seurat_4.3.0  
SeuratData_0.2.2
panc8.SeuratData_3.0.2     
SeuratObject_4.9.9.9091

**Comment by Tolupeter** [comment]
I have similar error please can you help me out. 
integrated.ov <- IntegrateData(anchorset = anchors.ov, normalization.method = "SCT", dims=1:30)
Warning: Different cells and/or features from existing assay SCT
Warning: Different cells and/or features from existing assay SCT
Warning: Different cells and/or features from existing assay SCT
Warning: Different cells and/or features from existing assay SCT
Merging dataset 3 into 4
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Error in validObject(.Object) : 
  invalid class “Assay” object: Keys must be a one-length character vector

**Comment by ahdee** [comment]
@Tolupeter for me all the errors went away after I upgraded to the latest 4.9 aka ver 5.  I think there is something really strange with how the internals are stored across different version so make sure also that you are using the correct seurat storage.  Its really strange how if you look through the various issues on the git sometimes downgrading helps and sometimes upgrading does. 
Moroever you could also try to run `PrepSCTFindMarkers`.

**Comment by wangkpro** [comment]
> @Tolupeter for me all the errors went away after I upgraded to the latest 4.9 aka ver 5. I think there is something really strange with how the internals are stored across different version so make sure also that you are using the correct seurat storage. Its really strange how if you look through the various issues on the git sometimes downgrading helps and sometimes upgrading does. Moroever you could also try to run `PrepSCTFindMarkers`.

Me too
