### ISSUE TITLE
Mixscape RunMixscape Error message

### ISSUE THREAD

**Issue by shengyongniu** [satijalab/seurat#3951]
I'm using mixscape to process Perturb-seq data. When I run the RunMixscape function, I get the following error message:
`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowMeans': incorrect number of dimensions`

Any suggestion? Note: I found that this error message can be avoided by increasing the logfc.threshold value; however, it will also ignore the genes with low signal. What's the cause of this error message? Is there a better way to adjust to the lower threshold?

**Comment by epapalexi** [comment]
Hi, it's hard to know what is going on here.  If you could provide the code and some data to replicate this error, I can take a look.

**Comment by shengyongniu** [comment]
I use the Perturb-seq data from here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2396858
Here are my codes:

`## Load packages.
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(scales)
library(dplyr)
library(reshape2)
library(tidyr)

rawdata <- Read10X(data.dir = "/data_folder")
seurat_object = CreateSeuratObject(counts = rawdata)
seurat_object <- subset(seurat_object, cells=sample(Cells(seurat_object), 5000))
custom_theme <- theme(
  plot.title = element_text(size=16, hjust = 0.5), 
  legend.key.size = unit(0.7, "cm"), 
  legend.text = element_text(size = 14))

DefaultAssay(object = seurat_object) <- 'RNA'
seurat_object <- NormalizeData(object = seurat_object) %>% FindVariableFeatures() %>% ScaleData()

seurat_object <- RunPCA(object = seurat_object)

seurat_object <- RunUMAP(object = seurat_object, dims = 1:20)


CBC_GBC_dict <- read.csv(file = 'GSM2396858_k562_tfs_7_cbc_gbc_dict.csv', header = FALSE)
CBC_list <- strsplit(CBC_GBC_dict$V2, split = ", ")
CBC_list

vector_of_GBC <- vector()
datalist = list()
for (i in 1:length(CBC_GBC_dict$V1)){
  datalist[[i]] <- rep(CBC_GBC_dict$V1[i], length(CBC_list[[i]]))
}
vector_of_GBC = unlist(datalist)
table(vector_of_GBC)
CBC_list <- unlist(CBC_list)
names(vector_of_GBC) <- CBC_list
intersect_GBC_seurat <- vector_of_GBC[intersect(names(seurat_object$orig.ident),names(vector_of_GBC))]
seurat_object <- seurat_object[,names(intersect_GBC_seurat) ]

intersect_GBC_seurat[grepl("INTERGENIC",intersect_GBC_seurat, fixed=TRUE)] <- "NT"
intersect_GBC_seurat[grepl("p_sg",intersect_GBC_seurat, fixed=TRUE)] <- "Perturbed"
seurat_object$crispr <- factor(intersect_GBC_seurat)

intersect_GBC_seurat_gene <- vector_of_GBC[intersect(names(seurat_object$orig.ident),names(vector_of_GBC))]

tmp <- sapply(strsplit(intersect_GBC_seurat_gene, "_"), "[", 2) 
tmp <- sub("^sg", "", tmp)
tmp <- sub("INTERGENIC[0-9]*$", "NT", tmp)
seurat_object$gene <- as.factor(tmp)


seurat_object<- CalcPerturbSig(
  object = seurat_object, 
  assay = "RNA", 
  slot = "data", 
  gd.class ="gene", 
  nt.cell.class = "NT", 
  reduction = "pca", 
  ndims = 20, 
  num.neighbors = 20, 
  new.assay.name = "PRTB")


DefaultAssay(object = seurat_object) <- 'PRTB'


VariableFeatures(object = seurat_object) <- VariableFeatures(object = seurat_object[["RNA"]])
seurat_object <- ScaleData(object = seurat_object, do.scale = F, do.center = T)

seurat_object <- RunPCA(object = seurat_object, reduction.key = 'prtbpca', reduction.name = 'prtbpca')

seurat_object <- RunUMAP(
  object = seurat_object, 
  dims = 1:20, 
  reduction = 'prtbpca', 
  reduction.key = 'prtbumap_', 
  reduction.name = 'prtbumap')


tmp <- sub("p_INTERGENIC[0-9]*$", "NT", intersect_GBC_seurat_gene)
seurat_object$NT <- as.factor(tmp)

Idents(seurat_object) <- "NT"
seurat_object <- RunMixscape(
  object = seurat_object, 
  assay = "PRTB", 
  slot = "scale.data", 
  labels = "gene", 
  nt.class.name = "NT", 
  min.de.genes = 1, 
  iter.num = 40, 
  de.assay = "RNA",
  logfc.threshold = 0.1,
  verbose = T)`

Thank you!

**Comment by epapalexi** [comment]
Hi,

I downloaded the data and ran your script but I cannot replicate the error message from above. Can you share with me your `sessionInfo()`? Maybe I can figure out what's going on from there.

Thanks,
Efi
