### ISSUE TITLE
FindNeighbors/FindClusters k value

### ISSUE THREAD

**Issue by Rafaelsoler13** [satijalab/seurat#3953]
Hi! 

What is the best method to determine the best k.param for both FindNeighbors and FindClusters? I have seen different methods to determine the 'dimensionality' of the dataset, but none of them to determine the value of k. Is there any way?

Thanks :)

**Comment by torkencz** [comment]
Hi,

I wish I could give you precise method we use. At this moment we do not support an adaptive k method. We recommend the default k=20 for most datasets. As a rule of thumb you do not want to have a higher k than the number of cells in your least populated cell type.
