### ISSUE TITLE
Error: Feature names of counts matrix cannot be empty

### ISSUE THREAD

**Issue by SylPsych** [satijalab/seurat#3954]
Hi, 

I am trying to create a Seurat object using the file attached, but keep getting the error message "Error: Feature names of counts matrix cannot be empty". Both colnames and rownames have been formatted to show dashes (-) instead of dots (.) or underscore (_). The dimension of my count matrix is 17495 x 6847. "CreateSeuratObject" seems to work when I use a subset of the matrix with a dimension 8778 x 6847.

Please, can you help with this?

**Comment by howtofindme** [comment]
> Hi,
> 
> I am trying to create a Seurat object using the file attached, but keep getting the error message "Error: Feature names of counts matrix cannot be empty". Both colnames and rownames have been formatted to show dashes (-) instead of dots (.) or underscore (_). The dimension of my count matrix is 17495 x 6847. "CreateSeuratObject" seems to work when I use a subset of the matrix with a dimension 8778 x 6847.
> 
> Please, can you help with this?

same problem,how do you sovled it?
