### ISSUE TITLE
How to determine where filtered-out cells lie on the cluster results and its impact on variable genes?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#3955]
Hi there, 

I hope to examine what the cells that I removed (using thresholds in subset()) are in terms of where they are on the cluster if I included them and whether they contribute to the top variable genes. Thank you so much for your help!

```
# cd8_sct_filteredout is cells that are actually filtered out 
cd8_sct_filteredout <- subset(cd8_sct_all_filtered, subset = nFeature_RNA <= 20 & nFeature_RNA >= 4000 & percent.mt >= 25)

# cd8_sct is cleaned data having certain cells filtered out
cd8_sct_cleaned <- subset(cd8_sct_all_filtered, subset = nFeature_RNA > 20 & nFeature_RNA < 4000 & percent.mt < 25)

```
1. To determine whether any of the variable genes generated by SCTransform() using the cd8_sct_all object belongs to any of the genes in the cells of the cd8_sct_filteredout object: 

2a. Do I just do SCTransform() on the cd8_sct_all, then do an If statement to see whether any of the resulting variable genes matches with the gene I have in the cd8_sct_filteredout object? Is VariableFeatures(cd8_sct_all) == cd8_sct[] the right conditional part of this if statement? 

2b. How can I identify which cells the unioned genes belong to? 

3. If I ran RunPCA(), RunUMAP(), FindNeighbors(), then FindClusters() for cd8_sct_all object, how can I identify/visualize where all or certain cells of the cd8_sct_filteredout object fall on the DimPlot(cd8_sct_all)?

**Comment by timoast** [comment]
I don't fully understand what the goal is here, if you removed the cells prior to identifying variable genes and clusters, then they don't contribute at all and they aren't located anywhere in the reduced dimension space. If you really wanted to you could project the removed cells onto the UMAP to visualise them in the same space using the MapQuery function
