### ISSUE TITLE
How to subset() Seurat object by donor ID barcodes?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#3956]
Hi there, 

Question #1693 suggests to use subset() to subset any given set of cells or features from a Seurat object. I hope to subset my data by donor ID. 

This is how my count matrix looks, the column has an ending with a number "......-1" which refers to donor 1, and "....-2" for donor 2, and so on. 

<img width="744" alt="Screen Shot 2021-01-21 at 12 16 00 PM" src="https://user-images.githubusercontent.com/62179082/105350011-6e86da00-5be2-11eb-9926-d7e3cb74ed9d.png">

Should I subset() the count matrix right after I do Read10X(), or subset() the Seurat object after I CreateSeuratObject()? Because question #246 suggests to use colnames(object@data), but there is no slot of name data for Seurat object.

And, would you mind helping me with the code to subset() the Seurat object by the last ending number of the column name? 

Thank you very much for your help!

**Comment by samuel-marsh** [comment]
Hi,

When you create the Seurat Object if you set `names.field = 2` the Seurat object will assign orig.ident based on the barcode suffix.  Then you can easily use subset by ident before proceeding with clustering or by orig.ident if you have already processed (and thus changed the active ident).

Best,
Sam

**Comment by denvercal1234GitHub** [comment]
Thank you very much, Sam!

**Comment by denvercal1234GitHub** [comment]
Hi @samuel-marsh - I am so sorry to bother you again, but after I set names.field = 2 in CreateSeuratObject(). Now, every function I do to this new Seurat object, for example, when I VlnPlot(myobject, features = "percent.mt"), it automatically separates the graphs by donors. 

How can I set it such that for any function, I can decide when to use data from all 3 donors combined, and when to use data from each donor? 

Thank you so much for your help!

<img width="362" alt="Screen Shot 2021-01-22 at 1 01 18 AM" src="https://user-images.githubusercontent.com/62179082/105431357-57c99d00-5c4d-11eb-83df-79be590e6783.png">

**Comment by samuel-marsh** [comment]
Hi,

So Seurat will plot by whatever the active identity is by default in most cases.  Prior to clustering that is the orig.ident by default.  If you want to plot all of the samples together you can simply pass a new active ident with the same value across all of the cells.  

In terms of analysis if you plan on analyzing these samples together then I would recommend either keep them together in the same object in running the normal pipeline or if you want can separate them and use integration pipelines if you think that is more appropriate for your particular analysis.

Best,
Sam

**Comment by timoast** [comment]
@denvercal1234GitHub Please see the documentation and vignettes available at https://satijalab.org/seurat/vignettes.html
