### ISSUE TITLE
How to optimize dataset integration? 

### ISSUE THREAD

**Issue by dlmatera** [satijalab/seurat#3957]
Hello all,

I have two quick questions about the dataset integration features

1) I have one dataset with ~30k genes and another with ~40k (this also has noncoding regions profiled, etc.) - since the algorithm will create a new slot with all genes (and will set the ~10k not in dataset1 to an expression value of zero), will this interfere with integration? In other words, will the integration be more accurate if I remove the excess genes from dataset2 prior to integration? For example if gene X is in all macrophages in dataset2 but not in sampled at all in dataset1, will this interfere with integration? Or does the algorithm just take into account genes that have been sampled across datasets? 

2)I am only interested in 3 cell populations but my raw datasets have ~15, should i run integration on a reduced dataset just for the cells of interest (using metadata from prior analyses i can pre-filter the datasets before integration to just contain cells of interest)? Or would increased statistical power from merging the entire datasets together be better for removing batch effects? 

Thanks!

**Comment by timoast** [comment]
1: Only genes measured in both datasets will be used. See the `anchors.features` and `features.to.integrate` arguments in `FindIntegrationAnchors()`
2: I'd suggest trying both ways and deciding which works best for you
