### ISSUE TITLE
Could not find function "PCElbowPlot"

### ISSUE THREAD

**Issue by knightsUCF** [satijalab/seurat#3958]
I am using Seurat 4.0. I am getting this message:

Error in PCElbowPlot(pbmc) : could not find function "PCElbowPlot"

**Comment by samuel-marsh** [comment]
Hi,

`PCElbowPlot` was deprecated after Seurat V2.  Seurat V3+ uses the function `ElbowPlot`.

Best,
Sam

**Comment by knightsUCF** [comment]
Thank you!
