### ISSUE TITLE
batch effect and integration

### ISSUE THREAD

**Issue by liuweihanty** [satijalab/seurat#3959]
Hello, I'm wondering could Seurat's integration procedure remove batch effect among samples? I know there was a batch effect removing procedure based on CCA in the previous version of Seurat but couldn't find the step to remove batch effect in the integration tutorial: https://satijalab.org/seurat/v3.0/integration.html.

Much thanks!

**Comment by torkencz** [comment]
Hi, 
You should be able to remove batch effects using the standard workflow where you anchor between the datasets that have batch effects between them.
