### ISSUE TITLE
DE in Treated x Control comparison - all genes are up-regulated in the control

### ISSUE THREAD

**Issue by balmantkelly** [satijalab/seurat#3960]
Hello,

I have a single-cell RNA-seq experiment with control and treated samples.
My control sample has significantly less cells compared with the treated samples.
I did the DE expression analysis to find genes differentially expressed between the two conditions. For this analysis I used the "RNA assay" values not the integrated one.

For my surprise, all the DE genes for all the clusters had a negative logFC, which means they have a higher expression value in the control compared with the treated sample.

My questions are: 
- would the different number of cells between the two samples being causing this weird result?
- Would this be due to any kind of normalization? Is it possible the normalization is "increasing" the expression values in the control sample because of the lower number of cells in the sample?\

Thanks!

**Comment by dnev1551** [comment]
We are having the same issue, we have also posted a few days ago n the issues; no response yet, but if get one there, I would watch for it! https://github.com/satijalab/seurat/issues/3949 @satijalab

**Comment by dnev1551** [comment]
@balmantkelly will you let us know if you receive a response as well? Thank you! Please include @schultzett

**Comment by jaisonj708** [comment]
Would you mind posting your code? A follow up to our questions on #3949 would also help us better assess what went wrong

**Comment by Tomer9w** [comment]
Hi
Having similar issues.. Did you end up understanding why/how it happened and fixed it? @balmantkelly
