### ISSUE TITLE
Why there are NA in vst.variance.expected and .standardized for some variable genes?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#3962]
Hi there, 

I used FindVariableFeatures() on a Seurat object. Then, access the statistics for them as below. But when I check, there were some genes that had NA as their variance.expected and variance.standardized. Would you mind explaining why that is the case? 

Also, if I don't set nfeatures in FindVariableFeatures() or in SCTransform(), it will automatically find the max number of variable genes from my Seurat object? If so, shouldn't we always use this automatically-calculated number of variable genes for RunPCA()?

Thank you very much for your help!

```
# genes_excluded_by_mincells has dimension of 19095
genes_excluded_by_mincells <- FindVariableFeatures(genes_excluded_by_mincells, selection.method = "vst", nfeatures = 19000)

stats_genes_excluded_by_mincells <- genes_excluded_by_mincells[["RNA"]]@meta.features
```

<img width="497" alt="Screen Shot 2021-01-22 at 9 16 44 AM" src="https://user-images.githubusercontent.com/62179082/105471359-8d44a980-5c92-11eb-8385-3d817fe7f822.png">

**Comment by timoast** [comment]
Are there any non-numeric values in your input data (NA, NaN, Inf, character, logical, etc)

**Comment by denvercal1234GitHub** [comment]
I see. Thank you so much! After I filtered out these values, it worked as expected. 

I am still unclear about the nfeatures argument of these functions. If I set nfeatures in FindVariableFeatures() or in SCTransform() equal to the total number of genes, it seems to automatically find the max number of variable genes from my Seurat object. If so, shouldn't we always use this automatically-calculated number of variable genes for RunPCA() instead of picking a number, 2000, 3000 etc.?

**Comment by yuhanH** [comment]
HI, 
What do you mean max number of variable genes? I think if you set `variable.features.n` larger than your counts matrix, it will return all genes as variable genes. For example, 
```
pbmc_small
pbmc_small <- SCTransform(pbmc_small)
length(VariableFeatures(pbmc_small)) == nrow(pbmc_small[["SCT"]]@data)
```
There are no good ways to set the most correct number of variable genes. Based on our experience, we find that 2K or 3K top variable genes are good enough to detect the heterogenous populations in the data.

**Comment by denvercal1234GitHub** [comment]
Hi @yuhanH Thank you for your response. However, in my data above which has 19,095 genes where I set the variable.features.n = 19,000, FindVariableFeatures() automatically gives me 5,264 variable genes. I did not use SCTransform() in this case.
