### ISSUE TITLE
DimPlot Error - Error :[[<- defined for objects of type "S4" only for subclasses of environment

### ISSUE THREAD

**Issue by bapoorva** [satijalab/seurat#3964]
Hi,
I have an application built in shiny that uses the Seurat package. I'm using DimPlot to view the tSNE and UMAP plots within the application. This app works perfectly fine on my local machine.  But when i host it on shiny-server, the plots don't display and I'm getting this error

 `Error :[[<- defined for objects of type "S4" only for subclasses of environment`

There are no issues loading the dataset because it plots Featureplots, Violinplots and Ridgeplots just fine on the shiny server, but not tsne/umap or heatmap. It's weird because everything was working fine until I updated the seurat version. Any ideas  ?

There is a duplicate of this issue on Biostars because I wasn't sure if this is a Seurat issue or a shiny server issue.

**Comment by k3yavi** [comment]
Hey @bapoorva , 

it's hard to say without looking at the object but can you double check the `DefaultAssay` of the object is what you wan;t ?

**Comment by bapoorva** [comment]
I have about 120 datasets on there. Some set to RNA, some to SCT assay. But I also have the backend code to pull data from the right assay for different functionalities. It is just the plots that is having an issue.

**Comment by bapoorva** [comment]
I'd updated seurat from 3.0.2 to the cran version (3.2.2) when I started having this issue. Uninstalling and reinstalling Seurat with all the dependencies didn't work either. Weirdly enough, updating uwot and installing the v4.0 beta fixed it.

**Comment by balthasar0810** [comment]
I am having the same issue. Updated Seurat to 3.2.3 this morning. DimPlot(SeuObj), which worked without a problem before, produces: 
DimPlot Error - Error :[[<- defined for objects of type "S4" only for subclasses of environment

How can this be resolved?

**Comment by koenvandenberge** [comment]
@k3yavi Having same issue, here's a reproducible example using `Seurat_3.2.3`:

```
atac <- CreateSeuratObject(counts = matrix(rnbinom(1e4, size=2, mu=2), nrow=1e2, ncol=1e2,
                                           dimnames=list(paste0("peak",1:100), paste0("cell",1:100))), 
                           assay = "ATAC", 
                           project = "10x_ATAC")
```

**Comment by bapoorva** [comment]
Updating Seurat to version 4.0 worked for me

**Comment by k3yavi** [comment]
Thanks for confirming this, I am not sure why I can't replicate the error on my end @koenvandenberge , can you try `UpdateSeuratObject` ?

**Comment by koenvandenberge** [comment]
Thanks for the response @k3yavi. Note that I can't run `updateSeuratObject` as I'm getting the error when I try to create the Seurat object using the code shared above.
In the development v4 version, that code works, but then I'm running into the issue of #3980.

**Comment by balthasar0810** [comment]
I found the origin of the error on my side: it always happens after loading SeuratDisk. After detaching SeuratDisk and reloading Seurat, everything works fine again. Best, CHris

**Comment by Meimei2** [comment]
I am having the same issue when creat the seurat object of the example pbmc data Using CreateSeuratObject function. Signac 1.1.1 and Seurat 3.2.3 was used. The error information are :
Error in `[[<-`(`*tmp*`, "orig.ident", value = idents) : 
  [[<- defined for objects of type "S4" only for subclasses of environment
I try to update the Seurat into version 4.0.0 to solve this problem, however, it doesn't work. 
How  to solve this problem? 
Thanks!

**Comment by timoast** [comment]
@Meimei2 try reinstalling Signac

**Comment by Meimei2** [comment]
@timoast Reinstall Signac 1.1.1 again, but I am still confront of the same error message...

**Comment by timoast** [comment]
@Meimei2 try running in a new R session, and if you still have issues raise an issue in the Signac repo

**Comment by Meimei2** [comment]
@timoast I still have this issue, and I have to re-install the signac v0.2.5 to bypass this problem.

**Comment by mirifax** [comment]
I have the same issue, but installing signac v0.2.5 or older versions of Seurat does not solve it.

**Comment by carmensandoval** [comment]
Sme issue, and @balthasar0810's answer worked for me. 

library(pacman)
p_unload(SeuratDisk)
p_unload(Seurat)
p_load(Seurat) # I'm using 3.2.0
```
`updated_object <- UpdateSeuratObject(old_object)` now works where previously it gave me the error:

```
[[<- defined for objects of type "S4" only for subclasses of environment
```

**Comment by balthasar0810** [comment]
Glad you could solve it. It seems to me that it is a general annoying issue when loading certain packages. I identified DESeq2 and SeuratDisk so far....

**Comment by dengyj-2019** [comment]
The Seurat method for [[<- was unregistered due to a method conflict. To resolve this, reload the package:
unloadNamespace("Seurat")
library(Seurat)
