### ISSUE TITLE
Seurat library error

### ISSUE THREAD

**Issue by hahia** [satijalab/seurat#3966]
Hello, I installed the SeuratV4, but when I library the package, there has an error
![image](https://user-images.githubusercontent.com/49113803/105622399-65994100-5e4c-11eb-89ac-60bd2331bf33.png)

sessioninfo
![image](https://user-images.githubusercontent.com/49113803/105622410-8a8db400-5e4c-11eb-9c89-d98cf0483d86.png)

**Comment by samuel-marsh** [comment]
Hi,

This appears like it might be error with the Rtsne package and not Seurat itself.  What happens if you just try and load the Rtsne package?

Best,
Sam

**Comment by hahia** [comment]
> Hi,
> 
> This appears like it might be error with the Rtsne package and not Seurat itself. What happens if you just try and load the Rtsne package?
> 
> Best,
> Sam

Hello, library(Rtsne) also have the same error
![image](https://user-images.githubusercontent.com/49113803/105929086-cf4e6080-6081-11eb-968d-8b1ef1e2d712.png)

**Comment by samuel-marsh** [comment]
Hi,

It seems the error is on Rtsne side then.  I suggest posting to their github repo for help solving the issue.

Best,
Sam
