### ISSUE TITLE
Slot containg do.scale output for filtering by z score

### ISSUE THREAD

**Issue by cebriggs7135** [satijalab/seurat#3967]
How can I extract a gene by cell matrix of z scores from a Seurat object? ie. What slot contains the "do.scale" output?
My goal is to screen datasets to generate a list of ONLY those datasets in a database containing my gene of interest exhibiting a [z-score] of at least 2.0 in a minimum of say 100 cells. This is useful to people who want to look at all cells in a database (all organs, cell types, etc) expressing a gene of interest above a selected threshold.

**Comment by saketkc** [comment]
You can use `GetAssayData(object, slot = "scale.data")` on an assay of interest (`assay=x`).

**Comment by cebriggs7135** [comment]
But that just gets me this:
> x<-GetAssayData(object=pbmc, slot = "scale.data")
> head(x)
              AAACATACAACCAC-1 AAACATTGAGCTAC-1 AAACATTGATCAGC-1 AAACCGTGCTTCCG-1 AAACCGTGTATGCG-1
              AAACGCACTGGTAC-1 AAACGCTGACCAGT-1 AAACGCTGGTTCTT-1 AAACGCTGTAGCCA-1 AAACGCTGTTTCTG-1
              AAACTTGAAAAACG-1 AAACTTGATCCAGA-1 AAAGAGACGAGATA-1 AAAGAGACGCGAGA-1 AAAGAGACGGACTT-1
              AAAGAGACGGCATT-1 AAAGCAGATATCGG-1 AAAGCCTGTATGCG-1 AAAGGCCTGTCTAG-1 AAAGTTTGATCACG-1
              AAAGTTTGGGGTGA-1 AAAGTTTGTAGAGA-1 AAAGTTTGTAGCGT-1 AAATCAACAATGCC-1 AAATCAACACCAGT-1....................

**Comment by saketkc** [comment]
x is a gene x cell matrix. You can visualize the first few entries as follows:

```r
> sd <- GetAssayData(pbmc_small, slot="scale.data")
> sd[1:5, 1:5]
         ATGCCAGAACGACT CATGGCCTGTGCAT GAACCTGATGAACC TGACTGGATTCTCA AGTCAGACTGCACA
IGLL5        -0.1934952     -0.1934952     -0.1934952     -0.1934952     -0.1934952
S100A8       -0.7048050     -0.7048050     -0.7048050     -0.7048050     -0.7048050
S100A9       -0.7639656      0.9016133      0.8935721     -0.7639656     -0.7639656
HLA-DPB1     -1.0399941     -1.0399941     -1.0399941     -1.0399941     -1.0399941
HLA-DQA1     -0.6717070     -0.6717070     -0.6717070      1.2439601     -0.6717070
```

**Comment by cebriggs7135** [comment]
That works but why doesn't this work:
> sdx <- GetAssayData(pbmc, slot="scale.data")
> sdx[1:5, 1:5]
Error in sdx[1:5, 1:5] : subscript out of bounds

**Comment by cebriggs7135** [comment]
Got it! Thanks.
