### ISSUE TITLE
Question about IntegrateData in scvelo

### ISSUE THREAD

**Issue by lh12565** [satijalab/seurat#3968]
Hi, I have some samples with batch effects, and I want to use SeuratWrappers to run scvelo. I wonder if the following code is correct:

```R
#R
samples<-c("P1.loom","P2.loom","P3.loom","P4.loom","P5.loom")
ldat<-list()
for(i in samples){
	bm <- ReadVelocity(file = i)
	bm <- as.Seurat(x = bm)
	bm[["RNA"]] <- bm[["spliced"]]
	bm <- SCTransform(bm)
	ldat[[i]]<-bm
}

seu.features <- SelectIntegrationFeatures(object.list = ldat, nfeatures = 3000)
ldat <- PrepSCTIntegration(object.list = ldat, anchor.features = seu.features)
seu.anchors <- FindIntegrationAnchors(object.list = ldat, normalization.method = "SCT", 
 anchor.features = seu.features, reference = 1)
seu <- IntegrateData(anchorset = seu.anchors, normalization.method = "SCT")

seu <- RunPCA(seu)
seu <- RunUMAP(seu, dims = 1:30)
seu <- FindNeighbors(seu, dims = 1:30)
seu <- FindClusters(seu)
DefaultAssay(seu) <- "integrated"
SaveH5Seurat(seu, filename = "bms.h5Seurat")
Convert("bms.h5Seurat", dest = "h5ad")
```
```python
#In Python
import scvelo as scv
adata = scv.read("bms.h5ad")
adata
```
If it is wrong, what should I do to run scvelo with batch effects?
Thanks!

**Comment by torkencz** [comment]
Hi there is currently no consensus of how to run scvelo with batch effects. Your code seems fine to me. I would also refer you to https://github.com/theislab/scvelo/issues/163 where they discuss this issue.

**Comment by lh12565** [comment]
> Hi there is currently no consensus of how to run scvelo with batch effects. Your code seems fine to me. I would also refer you to [theislab/scvelo#163](https://github.com/theislab/scvelo/issues/163) where they discuss this issue.

Thanks, @torkencz. I have one more question. Some tools to remove batch effect only return tsne or umap coordinates, such as MNN or Harmony. I wonder if I can use no corrected spliced and unspliced expression matrix with the corrected umap/tsne to run scvelo. Thanks!
