### ISSUE TITLE
Combining integrated objects from diverse sample types

### ISSUE THREAD

**Issue by ag2021-git** [satijalab/seurat#3969]
I'm curious how people suggest approaching the following.

We have samples from four developmental tissue types. Each tissue has 3 10X runs from different donors, so 12 10X altogether. Each sample contains a mixture of epithelial cells of various subtypes (including progenitors) and other stromal things such as fibroblasts/lymphocytes.

I started by integrating all cells separately for each of the four tissue types with the SCTransform workflow and it produces nice sensible clusters with separate stromal cells. Within the epithelial cells there are various clusters of subtypes which make perfect biological sense.

The trouble comes when trying to "integrate" (and maybe that is not the best word for it) those epithelial cells across the different tissue types. They tend to end up in one big smear, with clusters that don't make biological sense and have cells from each of the tissue types mixed up. Of course the batch correction is deliberately trying to remove differences. But it seems to be wiping out the biological signal too, I guess because it is deliberately seeking the common features between the epithelial cells. 

The way I have approached it is to take the four initial integrated clusterings from the four different tissue types, pull out the epithelial clusters from each, and then re-SCTransform and integrate. But this strategy does not seem to be working and I wondered if anyone had encountered a similar type of analysis? I've  tried just integrating every cell from scratch with similar results.

**Comment by jaisonj708** [comment]
From what I understand, you get expected clusters when integrating distinct donors, but not when integrating distinct tissue types. This is somewhat unsurprising since CCA will find common sources of variation. RPCA is a bit more conservative so I would suggest trying that. We don't recommend re-running SCTransform after integration.
