### ISSUE TITLE
Error when scaling data - attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by bapoorva** [satijalab/seurat#397]
Hi,

I'm using the seurat pipeline to analyze my single cell data and I'm following the documentation. However I am getting this error in the ScaleData step

```
pbmc <- ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito"))

Error in cmpCallArgs(place[-c(1, 2)], cb, ncntxt) : 
  attempt to set an attribute on NULL
```

I've used the same pipeline for the same dataset before and it ran without an issue. I checked the seurat object pbmc and I don't see any NULL's. Am i looking at the wrong thing ? How do I fix this ?

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Try upgrading R to the latest version (3.4.4). There seems to be issues sometimes with using the precompiled binaries distributed via CRAN with older versions of R.

**Comment by bapoorva** [comment]
Thank you. That will probably work. But I had trouble upgrading my R. So I ended up downgrading my Seurat version to 2.2.0 instead and it worked.

**Comment by odagliyan** [comment]
using R 3.4.4 fixes ScaleData() problem, but not FindVariableGenes is giving the following error:

Error in linbin2D(x, gpoints1, gpoints2) : object 'F_lbtwod' not found

**Comment by mojaveazure** [comment]
@odagliyan Please see #70 for FORTRAN issues
