### ISSUE TITLE
FindAllMarkers in Two different datasets 

### ISSUE THREAD

**Issue by kumarRBK** [satijalab/seurat#3970]
Hi All,

I have different datasets (biological replicates) which contain KO1/WT1 and KO2/WT2. I would like to know how to do FindAllmarkers after integrating and batch-effect removed and dataset (I want to find FindAllMarkers within each datasets KO1 Vs WT1  and KO2 Vs WT2).

Please help! Thanks

**Comment by torkencz** [comment]
Hi,

Running FindAllMarkers on the integrated data is not recommended. I would run it within each of your datasets and then compare or run FindConservedMarkers and have you biological replicates marked as variable for iding the two groups. I would use this for reference https://www.biostars.org/p/409790/.
