### ISSUE TITLE
Differential expression analysis using multiple controls & mutliple stimulated datasets

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#3971]
I was wondering about how to incorporate a sample weighing factor into DE analysis.  We have multiple datasets for contol vs. stimulated which we want to compare for DE analysis.  As such, each sample has a different number of cells of each cell type.  My lab wants to make sure we are weighing each sample evenly in the differential analysis.  If, for each sample, we used a weight factor of:

(expected cell count of sample x) / (actual cell count of sample x) 
i.e.
(total cell count / number of samples) / (actual cell count of sample x) 

What are your thoughts on multiplying each normalized count value by the sample weight factor before doing DE analysis?  Im not sure if this is the proper way to use a weighting factor

**Comment by jaisonj708** [comment]
I wouldn't recommend modifying the counts. The DE tests in `FindMarkers` currently don't accept a per-cell scaling factor, but you refer to the [Muscat](https://github.com/HelenaLC/muscat) package for help with this. A less ideal solution - run DE on samples independently and take the intersection of the results.
