### ISSUE TITLE
IntegrateData() Not Running

### ISSUE THREAD

**Issue by rebeccawuu** [satijalab/seurat#3972]
I'm trying to run IntegrateData() and it keeps returning 
`Extracting anchors for merged samples
Finding integration vectors
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
Calls: IntegrateData ... RunPCA -> RunPCA.Assay -> RunPCA -> RunPCA.default -> irlba
Execution halted `

I've looked at previous issues (https://github.com/satijalab/seurat/issues/1698) that have talked about this same problem but the way they fixed their problem didn't fix mine...

Below is my code:

```
Zhou.anchors <- FindIntegrationAnchors(object.list = list(AD1, AD2, AD3, AD4, AD5, AD6, AD7, AD8, AD9, AD10, AD11,C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10), dims = 1:20)

Zhou.combined <- IntegrateData(anchorset = Zhou.anchors, dims = 1:20)
```

**Comment by saketkc** [comment]
Can you confirm if you ran `FindVariableFeatures` and `NormalizeData` as in this [vignette](https://satijalab.org/seurat/v3.0/integration.html)? It will be useful if you could paste your code here.

**Comment by rebeccawuu** [comment]
Hi yes of course:

`Zhou<-c("AD1", "AD2", "AD3", "AD4","AD5",  "AD6","AD7", "AD8", "AD9", "AD10", "AD11", 
         "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11"
         ,"P1","P2", "P3", "P4","P5", "P6", "P7",  "P8","P9", "P10")

Norm_variable<-function(Seuratdata, method='vst',feat=2000){
  #Normalize Data
  Seuratdata <- NormalizeData(Seuratdata)
  
  #Identifying variable genes for downstream analysis, method=vst, #features=2000
  Seuratdata <- FindVariableFeatures(object = Seuratdata,selection.method = method, nfeatures = feat)
  return(Seuratdata)}

 for (i in 1:length(Zhou)){
   txt<-paste(Zhou[i], '<-Norm_variable(', Zhou[i],')', sep="")
   eval(parse(text=txt))
 }

Zhou.anchors <- FindIntegrationAnchors(object.list = list(AD1, AD2, AD3, AD4, AD5, AD6, AD7, AD8, AD9, AD10, AD11,C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10), dims = 1:20)

Zhou.combined <- IntegrateData(anchorset = Zhou.anchors, dims = 1:20)
`

**Comment by saketkc** [comment]
Thanks! Does this also happen if you reduce the pca dimensions to say 10 (or lower?)

**Comment by rebeccawuu** [comment]
Hello,

I haven't tried reducing the dimensions to 10 or lower since I'm trying to replicate this study to use their data [(](https://www.pnas.org/content/117/41/25800#sec-8) for my own research. They indicated "For integrative analysis, we followed the workflow described in the Seurat guided analysis. We first log-normalized the filtered matrixes and identified highly variable features for each sample using the FindVariableFeatures function with the parameters selection.method = vst, and nfeatures = 1000. To integrate all 21 samples, we identified features for anchoring the samples using the FindIntegrationAnchors function with the parameter dims = 1:20 and used the identified anchors to integrate the dataset using the IntegrateData function with the parameter dims = 1:20. We subsequently scaled the integrated matrix and performed linear dimensional reduction using the RunPCA function with the parameter npcs = 50." under their methods section. But I get stuck at the IntegrateData section.

**Comment by saketkc** [comment]
Thanks! If you could point me to the publication (and datasets), I can try reproducing it at my end. But another thing that would be worth ensuring is the number of features in each object - do you have similar # of features across the datasets?.

**Comment by rebeccawuu** [comment]
Hi, sorry about that I thought I linked the paper in my previous comment! But the paper is: https://www.pnas.org/content/117/41/25800 (Title: "Single-nucleus transcriptome analysis reveals dysregulation of angiogenic endothelial cells and neuroprotective glia in Alzheimer’s disease" by Lau et al.), the data is here https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE157827.

Thanks so much for looking into this for me!

**Comment by saketkc** [comment]
Sorry for the delay, I will be taking a look at this soon.

**Comment by saketkc** [comment]
Very sorry for the extreme delay. I was able to integrate the dataset without any issues. Feel free to reopen if you face any issues.

![image](https://user-images.githubusercontent.com/682153/129465656-05d8a73e-c40b-425a-80ac-aae7bb80e456.png)


```r
suppressPackageStartupMessages({
  library(Seurat)
  library(patchwork)
})
root_dir <- "~/data/GSE157827/"
files <- list.files(root_dir, pattern = "*_matrix.mtx.gz")
counts <- list()
for (f in files) {
  fprefix <- gsub(pattern = "_matrix.mtx.gz", replacement = "", x = f)
  counts[[fprefix]] <- ReadMtx(mtx = file.path(root_dir, f), cells = file.path(root_dir, paste0(fprefix, "_barcodes.tsv.gz")), features = file.path(root_dir, paste0(fprefix, "_features.tsv.gz")))
}

objects_list <- list()
for (name in names(counts)) {
  cm <- counts[[name]]
  obj <- CreateSeuratObject(counts = cm, min.cells = 1, min.features = 1)
  obj <- RenameCells(object = obj, add.cell.id = name)
  obj$dataset <- name
  obj <- SCTransform(obj, method = "glmGamPoi", verbose = FALSE)
  objects_list[[name]] <- obj
}

features <- SelectIntegrationFeatures(object.list = objects_list, nfeatures = 3000)
objects_list <- PrepSCTIntegration(object.list = objects_list, anchor.features = features)
objects_list <- lapply(X = objects_list, FUN = RunPCA, verbose = FALSE, features = features)
saveRDS(objects_list, file.path(root_dir, "objects_list.rds"))

anchors <- FindIntegrationAnchors(
  object.list = objects_list,
  normalization.method = "SCT",
  anchor.features = features,
  dims = 1:30,
  reduction = "rpca",
  reference = c(1, length(objects_list)),
  k.anchor = 5
)
saveRDS(anchors, file.path(root_dir, "anchors.rds"))
combined.sct <- IntegrateData(anchorset = anchors, normalization.method = "SCT", dims = 1:30)
combined.sct <- RunPCA(combined.sct, verbose = FALSE)
combined.sct <- RunUMAP(combined.sct, reduction = "pca", dims = 1:30)
saveRDS(combined.sct, file.path(root_dir, "GSE157827_integrated.rds"))
p1 <- DimPlot(combined.sct, reduction = "umap", group.by = "dataset")
p1
ggsave(file.path(root_dir, "GSE157827_integrated.png"))
```

**Comment by WJRDW** [comment]
Hi saketkc,

I was looking through this issue because I had a bad_alloc() error trying to integrate 28 different scRNA datasets with Seurat. My way of working was completely the same as described above by you, except for this line of code:
> objects_list <- lapply(X = objects_list, FUN = RunPCA, verbose = FALSE, features = features) where you rerun the PCAs of the separate objects using the integration features identified before.
I added this piece of code, and now the integration works fine!

I could not find this line of code in any of the integration vignettes on the Seurat website, so I was wondering if you could shed some light on why you added it here and how it impacts the analysis?

Thank you very much!

Best,
W
