### ISSUE TITLE
Export Seurat Visium data for 10X Loupe browser

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#3973]
I know there have been more than one requests to enable Seurat's export for Loupe browser. But none seemed to have mentioned 10X Visium data. 
Could someone provide a solution to export a Seurat object containing Visium data into some format that Loupe browser can load?

Thanks

**Comment by jaisonj708** [comment]
If someone in the community would like to export Seurat objects to Loupe/.cloupe files, we would be more than happy to review the pull  request but I don't think we have the bandwidth to do this ourselves. 

Are there features in Loupe (e.g, interactivity) that you would like to use in particular? We can potentially add support in Seurat, depending on what you are looking for

**Comment by brianpenghe** [comment]
I think the nice thing about Loupe is that it doesn't require bioinformatic background. So our collaborators can just interactively view the data without needing to code. Maybe Seurat can release a Seurat-viewer that have a nice GUI without needing to code?

**Comment by jaisonj708** [comment]
A dataset exploration GUI is not a bad idea and something we will consider releasing in the future. Thanks for your input!

**Comment by dkcoxie** [comment]
FYI - 10x released a package (`[LoupeR](https://www.10xgenomics.com/support/software/loupe-browser/latest/tutorials/introduction/lb-louper)`) for generating .cloupe outputs from Seurat objects.
