### ISSUE TITLE
How to load both ADT and RNA data when using as.Seurat

### ISSUE THREAD

**Issue by Yale73** [satijalab/seurat#3976]
Hi Seurat team,

I am using a package to find doublets in my single-cell data, which needs a SingleCellExperiment object. I transferred the Seurat object with RNA and ADT data to the SingleCellExperiment object to label the doublets. But after it is done, I transferred the SingleCellExperiment object back to the Seurat object. I found I can only load "RNA" or "ADT" data. Is there any way I can load both data when transferring them?

Thanks,
Yale

**Comment by k3yavi** [comment]
Hi @Yale73 ,

Thanks for reaching out. May I ask how are you transferring the SingleCellExperiment object to  Seurat object ?
One way is to explicitly add the "RNA" assay, given "ADT" is already present in the `old.object` is as following:
`adt.object[["RNA"]] <- CreateAssayObject(counts = rna.matrix)`
