### ISSUE TITLE
FindIntegrationMarkers Error when using RCPA & SCTransform

### ISSUE THREAD

**Issue by dlmatera** [satijalab/seurat#3978]
I am getting the error below when attempting to integrate 3 datasets, my code is analogous to what is used in the vignettes. This error does not occur when I use normal CCA (but R crashes when using that method due to the size of my datasets, even with 120gb of RAM) - any suggestions? 
![image](https://user-images.githubusercontent.com/65360421/106003281-0b80c180-6080-11eb-996e-727df4909a17.png)

```r
# insert reproducible example here
```

**Comment by dlmatera** [comment]
> Hi,
> Could you provide the scripts you used?

I updated to the latest version of Rstudio/seurat and the above error went away, however, now I am getting the following error when I use FindIntegrationMarkers (for RCPA or RCPA w/ ref based integration):

![image](https://user-images.githubusercontent.com/65360421/106310461-95bc5780-6231-11eb-85af-3414f907d3fc.png)


Script:
library(Seurat)
library(ggplot2)
library(patchwork)
setwd('/home/dlmatera/Integration #2 1-21-2021')
options(future.globals.maxSize = 55000 * 1024^2)

# ======================================
# Load Datasets after QC
# ======================================
ildrf<-readRDS(file="Reyfman v3+sct.rds")
ildb<-readRDS(file="ildb+sct.rds")
ildr<-readRDS(file="ildr+sct#1.rds")

ildrf<-SCTransform(ildrf)
ildb<-SCTransform(ildb)
ildr<-SCTransform(ildr,conserve.memory=TRUE, ncells=100000)

saveRDS(ildb,file="ildb+sct+cellsofinterest.rds")
saveRDS(ildr,file="ildr+sct+cellsofinterest.rds")
saveRDS(ildrf,file="ildrf+sct+cellsofinterest.rds")

data.list <- c(ildb, ildr, ildrf)
remove(ildb,ildr,ildrf)

data.features <- SelectIntegrationFeatures(object.list = data.list, nfeatures = 3000)

data.list<- lapply(X = data.list, FUN = function(x) {
    x <- RunPCA(x, verbose = FALSE)
})

data.list <- PrepSCTIntegration(object.list = data.list, anchor.features = data.features, verbose = TRUE)

# ====================================================================
# Integrate via pearson residuals 
# ====================================================================
data.anchors <- FindIntegrationAnchors(object.list = data.list, normalization.method = "SCT", reduction="rpca", dims=1:30, reference=c(2),
                                                                        anchor.features = data.features, verbose = TRUE)
ild <- IntegrateData(anchorset = data.anchors, normalization.method = "SCT",dims=25, verbose = TRUE) #create a new combined seurat, DO NOT scale this data

**Comment by yuhanH** [comment]
Hi, 
You need to set anchor.features when you run PCA, and also run PrepSCTIntegration before RunPCA. 
For example, 

```
data.features <- SelectIntegrationFeatures(object.list = data.list, nfeatures = 3000)

data.list <- PrepSCTIntegration(object.list = data.list, anchor.features = data.features, verbose = TRUE)

data.list<- lapply(X = data.list, FUN = function(x) {
x <- RunPCA(x, features = data.features, verbose = FALSE)
})
```

Another issue is in the `IntegrateData`.  In most cases, you would use the same dims with `FindIntegrationAnchors`.  Even though you want to change the dims,  `dims=25` means only use one dimension.  

```
ild <- IntegrateData(anchorset = data.anchors, normalization.method = "SCT",dims=1:30, verbose = TRUE)
```

If the error still exists, i will reopen the issue.
