### ISSUE TITLE
Removing cell cycle effect using CCA?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#398]
I am using CCA to combine two data-sets of same origin. Is it possible to regress out cell cycle effect in CCA work-flow? If yes, how can it be done?

**Comment by mojaveazure** [comment]
Please see our cell-cycle regression vignette [here](http://satijalab.org/seurat/cell_cycle_vignette.html). The cell-cycle gene list is also included in Seurat as a named list, and accessible with

```R
library(Seurat)
data('cc.genes')
cc.genes
```

**Comment by bishwaG** [comment]
Thanks!
