### ISSUE TITLE
Alternatives to PCA before FindNeighbors and FindClusters

### ISSUE THREAD

**Issue by vvoorr** [satijalab/seurat#3981]
Hello,

The clustering function "FindNeighbors" and "FindClusters" requires one to perform PCA to reduce the dimensionality of the transcriptome matrix (done by the "RunPCA" function), which saves the PCA results in the attribute "SeuratObject@reductions$pca". As I would like to try my own algorithms other than PCA, I wonder if it is possible to add an attribute of my own low-dimenion-data-matrix to the SeuratObject, and feed it to "FindNeighbors" and "FindClusters" to reconstruct the clusters? 

Many thanks.

**Comment by timoast** [comment]
You can add your own custom dimension reductions using the `CreateDimReducObject()` function and the `[[<-` assignment operator, eg `object[['new_dr']] <- CreateDimReducObject(...)`. You can then use this reduction as input to `FindNeighbors`
