### ISSUE TITLE
Integrateing multi-samples

### ISSUE THREAD

**Issue by skyfall-lyc** [satijalab/seurat#3984]
Hi, everyone!
I have 30 samples with a total of about 150,000 cells. These samples can be divided into 3 different groups on average. The differences between the groups are huge, and the differences within the groups are relatively small. When I used the "Reference-based" method for integration, two of the samples, which were all T cells, was assigned to the myeloid and epithelial cell population. Therefore, I wonder whether it is possible to integrate the samples in the group first, and then perform the re-integration of the 3 RDS between the groups?

**Comment by timoast** [comment]
Yes you can do that, and is equivalent to providing a custom sample tree
