### ISSUE TITLE
Altering 3D plotting

### ISSUE THREAD

**Issue by mckaelaautumn** [satijalab/seurat#3985]
Hi, I have been able to analyze my data in 3D plotting in R Studio using plot_ly, but I would like to view the data by meta.data we added under "body_region" instead of by "seurat_clusters". I have been unable to alter the script successfully. It doesn't work, or I just get all my points one color.
Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of the Dev Team but hopefully can be helpful.  Could you please post the full code that you running?  Also it seems for your description as if this isn't necessary a Seurat issue but one with plotly?

Best,
Sam

**Comment by timoast** [comment]
It sounds like this is not an issue with Seurat, but with some custom code you're using. I'd suggest seeking help on more general support forums (stackoverflow, etc).
