### ISSUE TITLE
Differential expression on a subset of genes.

### ISSUE THREAD

**Issue by jakalssj3** [satijalab/seurat#3986]
Hello Seurat Team,

I'd like to exclude certain genes from the differential expression test using FindMarkers function. For this purpose I used 'features' parameter to provide a reduced set of genes. What I found is that results of such analysis (logFC, p value) do not differ from those of running FindMarkers using all genes. Is that to be expected? Should I rather generate a new object with a reduced gene set and then re-normalize the data before running FindMarkers?

**Comment by yuhanH** [comment]
HI, 
What method you used for the differential analysis? If you use default method, `wilcox`,  the logFC, p value should not be changed. Using wilcox, the logFC, p value are calculated independently for all genes. 

You can generate a reduced gene assay and run `FindMarkers`. It will change the adjusted p value, and the logFC, p value should remain the same.
