### ISSUE TITLE
Matrix::colSums error with Seurat

### ISSUE THREAD

**Issue by ahussain01** [satijalab/seurat#3988]
Hi,

I am having some trouble analysing single-cell data, especially with the following code:

genes_per_cell <-Matrix::colSums(h5_seurat1>0)

I get the following error when I run the code:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'colSums': comparison (6) is possible only for atomic and list types

I have created my SeuratObject, did an initial filtering and now according to the paper whose clustering I am trying to reproduce, I need to do:
create locally estimated scatter plot smoothing curve was fit to the UMI by gene curve, and those cells that were found with s.d. > 2 distant were removed.

I am guessing here, I need to count the number of genes expressed in each cell, take the average and remove cells that express far too many genes or far too few.
But I have a problem running the above code.

I am quite new to scRNAseq analysis and following the steps as in the vignette:
https://broadinstitute.github.io/2019_scWorkshop/data-wrangling-scrnaseq.html#goal-1

Thanks for the help.

**Comment by yuhanH** [comment]
Hi, 
Is the `h5_seurat1` a seurat object? If so, you need to run `colSums` on a counts or data slot, rather than seurat object. 
```
counts.matrix <- GetAssayData(object = h5_seurat1,  slot = "counts")
data.matrix <-  GetAssayData(object = h5_seurat1,  slot = "data")
```
