### ISSUE TITLE
latest Seurat v4 breaks Mapping to multimodal reference datasets vignette

### ISSUE THREAD

**Issue by orrzor** [satijalab/seurat#3989]
Hello Seurat team,

The latest Seurat v4 github version update breaks the vignette in https://satijalab.org/seurat/v4.0/reference_mapping.html. I think the problem has to do with the reference multimodal object and whether it has a SCTModel.list slot. I saw recent changes in the function `ValidateParams_FindTransferAnchors` that are probably causing this.

Here is the error.

> anchors <- FindTransferAnchors(reference = reference, query = pbmc3k, normalization.method = "SCT", reference.reduction = "spca", reference.assay = "SCT", dims = 1:50)
Error: Given reference assay (SCT) doesn't contain a reference SCT model.
Query assay is a SCTAssay. You can set recompute.residuals to FALSE to use Query residuals to continue the analysis

I checked that there is no SCTModel.list slot in the reference object.

> length(x = slot(object = reference[[reference.assay]], name = "SCTModel.list"))
[1] 0

I was using R v4.0.0 and Seurat v3.9.9.9038. The code works for me in Seurat v3.9.9.9036. 

Thanks a lot for all the updates- Orr

**Comment by yuhanH** [comment]
Hi, 
We will update our reference object very soon. 
Currently, when you can set `recompute.residuals = FALSE`, it should work.

**Comment by orrzor** [comment]
thanks a lot Yuhan!
