### ISSUE TITLE
Difference between Merge function & CCA analysis

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#399]
Hi to the Seurat team,

I have a pool of cells separated into 2 groups, with and without stimulation. For this kind of data, should I use the Merge function or perform integrated CCA analysis? What is the difference in function for the both of them?

Thank you very much.

**Comment by leonfodoulian** [comment]
Hi,

This issue is a duplicate of [issues #311](https://github.com/satijalab/seurat/issues/311) that you can find in the [closed issues on this GitHub page](https://github.com/satijalab/seurat/issues?q=is%3Aissue+is%3Aclosed). 

Best,
Leon

**Comment by nicodemus88** [comment]
@leonfodoulian 
Thank you for informing me. I didn't realize that. 
I will close this topic.
