### ISSUE TITLE
inconsitent automatic naming of cells when reading multiple 10X data sets

### ISSUE THREAD

**Issue by jan-glx** [satijalab/seurat#3990]
https://github.com/satijalab/seurat/blob/b56d194939379460db23380426d3896b54d91ab6/R/preprocessing.R#L1063
should probably read `if (length(data.dir) < 2) {`

**Comment by andrewwbutler** [comment]
I see, so the cells from the first directory getting processed wouldn't have the prepended number where as the rest would. We will fix and post here when updated. Thanks!
