### ISSUE TITLE
Using Seurat with multi-modal data: filter genes from "RNA" assay while keeping "HTO" assay in the filtered object 

### ISSUE THREAD

**Issue by behyag** [satijalab/seurat#3992]
hi, 
I have an object with both "RNA" and "HTO" assays. I want to remove features (genes) which are expressed in fewer than 3 cells. when I subset based on that, I loose the "HTO" assay! could you please recommend a solution? thanks. 

kept.genes <- rownames(obj@assays$RNA)[ Matrix::rowSums(obj) >= 3]
new.obj <- subset(obj, features = kept.genes)
#An object of class Seurat 
17177 features across 1783 samples within 1 assay 
Active assay: RNA (17177 features, 1754 variable features)
I have tried with the key() but still didn't work! 

Key(rownames(obj@assays$RNA)[ Matrix::rowSums(obj@assays$RNA)]) <- "key1_"
new.obj <- subset(obj, subset = `key1_` >= 3)

however, when I subset cells based on gene numbers, it works!!! but the genes I want to get rid of (expressed in fewer than 3 cells) are still there! but the new.obj has both "RNA" and "HTO" assays. 
new.obj <- subset(obj, subset = nFeature_RNA > 500 & nFeature_RNA < 8000)

thank you for your advice!

**Comment by yuhanH** [comment]
Hi, 
`subset` features may not work smoothly under many situations. The best way is to recreate the assay with new features. 
```
obj[["RNA"]] <- CreateAssayObject(counts = obj[["RNA"]]@counts[kept.genes , ] )
```
