### ISSUE TITLE
Integration workflow questions with SCTransform and batch_var parameter

### ISSUE THREAD

**Issue by goncik** [satijalab/seurat#3993]
Hi, 

I have 3 datasets to integrate (all from the same conditions and technologies but from different labs and primers) and I follow Seurat integration pipeline with SCTransform. 

1) Merge the objects.
2) Create a list from the merged object with SplitObject() splitting by "Dataset". 
3) Run SelectIntegrationFeatures() on the object list
4) Run PrepSCTIntegration()
5) Run FindIntegrationAnchors()
6) Run IntegrateData()

This integration works perfectly fine. Then, I do rest of the workflow and subset my Myeloid cells. 

For the Myeloid cells (subset), I see there is a batch effect -patients are clustered separately- and I want to run integration pipeline again with SCTransform, but this time using batch_var parameter and setting it to "Patient". (I didn't use this parameter in the above steps).

In here #3657 it is recommended to not split the object if batch_var parameter is gonna be used. However, I'm confused because since I will not use SplitObject(), my object is not a list and the steps 3,4 and 5 requires a list as an input. 

1) What would you recommend me to do as next steps? 
2) What if I don't use batch_var parameter and split my object by Patient before running SCTransform? 

PS. I tried splitting by Dataset again for the Myeloid cells and I still had the batch effect. 

Thank you very much!

**Comment by jaisonj708** [comment]
You can always split your object after running SCTransform with batch as a latent variable. Also note that you don't have to merge and split to create your list in step 3, you can just create your list: `list(<obj1>,<obj2>...)`

If you still see a batch effect, you can increase the `k.anchor` parameter in `FindIntegrationAnchors`

**Comment by goncik** [comment]
Thank you for your reply. 

May I ask you which one would you suggest? And what is the difference between splitting the object by patient without batc_var parameter vs using batch_var parameter and splitting the object later by Dataset?
