### ISSUE TITLE
Issue with nCount: RNA vs SCT

### ISSUE THREAD

**Issue by RajneeshSrivastava** [satijalab/seurat#3994]
Hi Team,

I am integrating 25 samples using Seurat.
Briefly, here are the steps for my analysis (following Seurat tutorials. Thanks for that!):
Load data >>> get "mt.percent" >>> subset  >>> SCT transform >>> data integration 

#SCT code
```
#subset
for (i in 1:length(sample.list)) {
    sample.list[[i]] <- subset(sample.list[[i]], 
                            subset = nFeature_RNA > 200 & 
                            nFeature_RNA < 5000 & percent.mt < 15 & 
                            nCount_RNA < 25000 & nCount_RNA > 2000)
                                }
```
```
#SCTansform
for (i in 1:length(sample.list)) {
    sample.list[[i]] <- SCTransform(sample.list[[i]],
                                    vars.to.regress = "percent.mt",
                                    verbose = FALSE)
                                }

sample.features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures=2000)
sample.list <- PrepSCTIntegration(object.list = sample.list, anchor.features = sample.features, verbose = FALSE)
sample.anchors <- FindIntegrationAnchors(object.list = sample.list, normalization.method = "SCT", anchor.features = sample.features, verbose = TRUE)
sample.integrated <- IntegrateData(anchorset = sample.anchors, normalization.method = "SCT", verbose = TRUE)
```
Just trying to understand what is actually happening after SC transform. I am wondering, if the distribution of nCounts (density plot) shown below is expected to be varying this much in nCount_SCT compared to nCount_RNA or am I doing anything wrong here?

plot(density(sample25@meta.data$**nCount_RNA**))
![image](https://user-images.githubusercontent.com/34284131/106325904-99f46f00-6249-11eb-9c79-8d7fa17a0cb1.png)

plot(density(sample25@meta.data$**nCount_SCT**))
![image](https://user-images.githubusercontent.com/34284131/106325991-bf817880-6249-11eb-8dd1-cd529b274a93.png)

A supplementary question. After SCT, VlnPlot provides discrete expression datapoints. I found exactly same issue as mentioned in #1623 (https://github.com/satijalab/seurat/issues/1623). where Dr. Yuhan mentioned "You could choose scale.data slot in the violin plot."  If possible, please elaborate on how to make use of "scale.data" after SCT. Not sure, if this behavior of VlnPlot function is expected for SC Transformed object.

Many thanks in advance!
Rajneesh

**Comment by timoast** [comment]
See #2101
