### ISSUE TITLE
failure in installations on windows 10

### ISSUE THREAD

**Issue by pfizer1234** [satijalab/seurat#40]
On window 10, I installed R 3.3.2. Then follow the instruction described in http://satijalab.org/seurat/install.html

>  library(devtools)
> install_github("satijalab/seurat")
Downloading GitHub repo satijalab/seurat@master
from URL https://api.github.com/repos/satijalab/seurat/zipball/master
Error: running command '"C:/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2

I google around hours and hours, and cannot get any clue.
Any help is deeply appreciated.

**Comment by andrewwbutler** [comment]
Have you tried reinstalling Rtools?

**Comment by fulxie** [comment]
I encountered the same issue with you.
follow the guide and you will successfully install seurat on windows 10
0. Instll R-3.3.2
 
1. install Rtools
install Rtools from https://cran.r-project.org/bin/windows/Rtools/
32-bit : C:\Program Files\R\R-3.3.2\bin\i386
64-bit : C:\Program Files\R\R-3.3.2\bin\x64

2. install devtools
install.packages("devtools")
library(devtools)

3. bioconductor:
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite(c("foreach",  "ModelMetrics", "segmented",  "sn",  "lfa",  "foreach",  "kernlab",  "trimcluster",  "robustbase",  "diptest",  "prabclus",  "flexmix",  "mclust","mvtnorm","car" ))
4. install seurat
install_github("satijalab/seurat")
library(Seurat)

if you still fail on step 4, read the error message, and use biocLite() to install the necessary packages, then try step 4 again.
