### ISSUE TITLE
Creating cell IDs for different datasets for RunMultiCCA

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#400]
Hi to the seurat team,

I am trying to run RunMultiCCA() using 4 datasets. I checked back on the multiple dataset tutorial and past issues ( issue #270 and #290 ) and I know I have to create unique names for cells from different datasets when creating the initial Seurat object.

However, what I couldn't find is how do I do that? It's not mentioned in the tutorial. I browsed the documentations for CreateSeuratObject but I'm not sure how to do that. Do I use the 'names.field' and 'names.delim' parameter?

I tried specifying the 'names.field' parameter to different name for different datasets but I got several warning messages. 

```R
s1 <- CreateSeuratObject(raw.data = s1.data, min.cells = 3, min.genes = 200, project = "S1", names.field = "S1")
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In FUN(X[[i]], ...) : NAs introduced by coercion
2: In FUN(X[[i]], ...) : NAs introduced by coercion
3: In FUN(X[[i]], ...) : NAs introduced by coercion
4: In FUN(X[[i]], ...) : NAs introduced by coercion
5: In FUN(X[[i]], ...) : NAs introduced by coercion
```

Can you guide me on how do I insert unique cell identifiers for each dataset during the initial Seurat object creation?

Hope to hear back from you soon. Thank you.

**Comment by nicodemus88** [comment]
@mojaveazure Thank you for your reply. I managed to run RunMultiCCA now.
I will close this topic now.

**Comment by ptrcalmeida** [comment]
Hi, I was able to add the unique prefixes to each of the 4 indivual 10X datasets that I'm working with prior to CreateSeuratObject using the following, as suggested in #270 :
colnames(x = s1.data) <- paste('S1', colnames(x = s1.data), sep = '_')

It works great: A1_AAACCTGCACGACGAA

However, I still get an error when running RunMultiCCA: 
lung.integrated <-RunMultiCCA(ob.list, genes.use=genes.use, num.ccs = 1)

**Error in MergeSeurat(object1 = combined.object, object2 = object.list[[i]],  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names**

Help, please? More info attached. Thank you!

[RunMultiCCA error.txt](https://github.com/satijalab/seurat/files/2042011/RunMultiCCA.error.txt)

**Comment by leonfodoulian** [comment]
Hi,

I guess you still have duplicated cell names. You can check that with the following codes:

```R
any(duplicated(x = colnames(x = s1.data))) # check if there are duplicated cell names
sum(duplicated(x = s1.data)) # count the number of duplicated cell names
```
Best,
Leon

**Comment by ptrcalmeida** [comment]
Thank you, Leon. 
This is what I runing prior to CreateSeuratObject:
colnames(x = normal1.data) <- paste('A1', colnames(x = normal1.data), sep = '_')
colnames(x = tumor1.data) <- paste('B1', colnames(x = tumor1.data), sep = '_')
colnames(x = normal2.data) <- paste('C2', colnames(x = normal2.data), sep = '_')
colnames(x = tumor2.data) <- paste('D2', colnames(x = tumor2.data), sep = '_')

This is what I see after running the code lines you provided:
> any(duplicated(x = colnames(x =tumor1.data))) # check if there are duplicated cell names
**[1] FALSE**
> sum(duplicated(x = tumor1.data)) # count the number of duplicated cell names
**Error in duplicated.default(x = tumor1.data) : 
  duplicated() applies only to vectors**
> any(duplicated(x = colnames(x =tumor2.data))) # check if there are duplicated cell names
**[1] FALSE**
> sum(duplicated(x = tumor2.data)) # count the number of duplicated cell names
**Error in duplicated.default(x = tumor2.data) : 
  duplicated() applies only to vectors**

Not sure what I am doing wrong. Thank you so much for your help!

**Comment by leonfodoulian** [comment]
Sorry my code was wrong:

```R
sum(duplicated(x = colnames(x = s1.data))) # count the number of duplicated cell names
```

Best,
Leon

**Comment by leonfodoulian** [comment]
In any case, it seems that you don't have duplicated names. To make sure that it is not a bug related to previous versions of Seurat, can you please share your `sessionInfo()`?

Best,
Leon

**Comment by ptrcalmeida** [comment]
Hi Leon, did you have a chance to look at the sessioninfo?

**Comment by leonfodoulian** [comment]
Hi @ptrcalmeida,

I have checked your `sessionInfo()`, but I am not aware of issues related to `Seurat::RunMultiCCA` in Seurat v2.3.0. Can you update Seurat to the latest version and see if that works?

Best,
Leon

**Comment by ptrcalmeida** [comment]
I will do that. Thank you.

**Comment by ptrcalmeida** [comment]
It didn't work with the newest Seurat version, unfortunately.
