### ISSUE TITLE
 *** caught segfault *** address 0x20, cause 'memory not mapped'

### ISSUE THREAD

**Issue by urielrosen** [satijalab/seurat#4002]
Hi ,

when loading Seurat 3.9.9.9024 in R/4.0.0 I get the below error :
when loading seurat on R/3.6.0 on the same server it works , tried to reinstall seurat but got the same error ,
any suggestions ?

> library(Seurat)

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE)
 7: (function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>),     error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
17: asNamespace(ns)
18: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
19: loadNamespace(package, lib.loc)
20: doTryCatch(return(expr), name, parentenv, handler)
21: tryCatchOne(expr, names, parentenv, handlers[[1L]])
22: tryCatchList(expr, classes, parentenv, handlers)
23: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
24: library(Seurat)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by SkadiEye** [comment]
The same happened to me.

**Comment by urielrosen** [comment]
Hi ,

I found the solution on your github thread.


Thanks,
Uriel.

**Comment by urielrosen** [comment]
Hi ,

Please remind me which package I need to install to overcome the segfault error  ?


Thanks,
Uriel.


From: Uriel Rosen
Sent: Monday, February 8, 2021 9:58 AM
To: 'satijalab/seurat' <reply@reply.github.com>; satijalab/seurat <seurat@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [satijalab/seurat] *** caught segfault *** address 0x20, cause 'memory not mapped' (#4002)

Hi ,

I found the solution on your github thread.


Thanks,
Uriel.

**Comment by timoast** [comment]
This should be solved by re-installing Seurat, please reopen if you still have issues with the latest Seurat release
