### ISSUE TITLE
FindTransferAnchors doesn't work with SCT normalized reference in Seurat 4.0.0

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [satijalab/seurat#4007]
The code works for Seurat v3.9.9, yet once upgraded to v4.0.0, it gives such error.

code:
rc.anchors <- FindTransferAnchors(reference = rc.integrated, query = rep_5, normalization.method = "SCT", npcs = 50 ,dims = 1:50, features = intersect(rownames(rc.integrated),rownames(rep_5)))

Error message:
Error in as.data.frame.default(x): cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame
Traceback:

1. FindTransferAnchors(reference = rc.integrated, query = rep_5, 
 .     normalization.method = "SCT", npcs = 50, dims = 1:50, features = intersect(rownames(rc.integrated), 
 .         rownames(rep_5)), reduction = "pcaproject")
2. ValidateParams_FindTransferAnchors(reference = reference, query = query, 
 .     normalization.method = normalization.method, recompute.residuals = recompute.residuals, 
 .     reference.assay = reference.assay, reference.neighbors = reference.neighbors, 
 .     query.assay = query.assay, reduction = reduction, reference.reduction = reference.reduction, 
 .     project.query = project.query, features = features, npcs = npcs, 
 .     l2.norm = l2.norm, dims = dims, k.anchor = k.anchor, k.filter = k.filter, 
 .     k.score = k.score, max.features = max.features, nn.method = nn.method, 
 .     n.trees = n.trees, eps = eps, approx.pca = approx.pca, mapping.score.k = mapping.score.k, 
 .     verbose = verbose)
3. as(object = reference[[reference.assay]], Class = "SCTAssay")
4. asMethod(object)
5. merge(x = vst.res[[1]], y = vst.res[2:length(x = vst.res)])
6. merge.default(x = vst.res[[1]], y = vst.res[2:length(x = vst.res)])
7. merge(as.data.frame(x), as.data.frame(y), ...)
8. as.data.frame(x)
9. as.data.frame.default(x)
10. stop(gettextf("cannot coerce class %s to a data.frame", sQuote(deparse(class(x))[1L])), 
  .     domain = NA)

**Comment by andrewwbutler** [comment]
Hi,

**Short answer**
Rerun your code to regenerate the reference and query objects and then `FindTransferAnchors` should work in with the v4 update.

**Longer answer** 
As part of the v4 update, we changed how we represent the output of SCT assays to better store and handle the sctransform model parameters. This comes into play at several levels in your situation. First, when integrating SCT objects, we store the model parameters for the reference dataset onto which the additional datasets are integrated. This is likely missing if you ran with an earlier beta version of 3.9.9. Then, when using `TransferData` with `normalization.method = "SCT"`, in the first part of that function, we project the query into the reference space. We've updated `TransferData` to make use of these learned sctransform parameters to transform the query data before that projection step. While not strictly necessary as you could use the sctransform residuals computed independently on the query, we recommend transforming based on the reference first. If you wanted to circumvent this, you could set `recompute.residuals = FALSE`. If you want to try to update your existing objects to work in the new framework (without rerunning), we do provide the `UpdateSeuratObject` and `UpdateSCTAssays` functions which you could run on the reference and query before `FindTransferAnchors` but this would also necessitate setting `recompute.residuals = FALSE` in `FindTransferAnchors`. However, this would give you different results than regenerating the reference/query as the query transformation wouldn't be applied here in `FindTransferAnchors`. TLDR - we generally would just recommend regenerating here as in the short answer.

**Comment by Hsu-Che-Wei** [comment]
Hi Andrew,

Thank you for the answer!
We generally don't want to rerun the integration for reference because we prefer the way Seurat does integration in version 3.1.5, the resulting UMAP looks much more reasonable since the ordination recapitulates the morphological arrangement of our tissue types and captures the continuous nature of cell differentiation in our system. Is there a way to run reference-based integration as version 3.15 with Seurat4?

Best,
Che-Wei

**Comment by Hsu-Che-Wei** [comment]
Hi Andrew,

I just tried out the function UpdateSCTAssays, seems that it only works with individual samples and doesn't work with integrated object, it gives the same error as FindTransferAnchors:
Error in as.data.frame.default(x): cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame
Traceback:

1. UpdateSCTAssays(rc.integrated)
2. as(object = object[[assay]], Class = "SCTAssay")
3. asMethod(object)
4. merge(x = vst.res[[1]], y = vst.res[2:length(x = vst.res)])
5. merge.default(x = vst.res[[1]], y = vst.res[2:length(x = vst.res)])
6. merge(as.data.frame(x), as.data.frame(y), ...)
7. as.data.frame(x)
8. as.data.frame.default(x)
9. stop(gettextf("cannot coerce class %s to a data.frame", sQuote(deparse(class(x))[1L])), 
 .     domain = NA)

Is there a way to do UpdateSCTAssays with integrated object without rerunning integration with Seurat4?
