### ISSUE TITLE
issue downloading Seurat 4.0

### ISSUE THREAD

**Issue by elevendoky** [satijalab/seurat#4008]
Hello I have tried to download the new Seurat 4.0 from cran. I keep getting the error `Error in install.packages : cannot remove prior installation of package ‘RcppAnnoy’` . I have also tried updating my already installed Seurat package and have gotten the same error. 
I have tried `remove.packages()` command but nothing has worked. Does anyone have any idea how to fix this?

**Comment by satijalab** [comment]
Take a look at this page, which suggests some troubleshooting options for a similar problem:
https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi

In particular, launching R without any startup files should fix your problem. Feel free to reopen this issue if that doesn't work (please do let us know)
