### ISSUE TITLE
Normalization Stopped Working

### ISSUE THREAD

**Issue by knightsUCF** [satijalab/seurat#4009]
Hi, recently the normalization function stopped working:

`pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)`

Not sure why, but this was just working a few days ago. Now the error reads:

Error in NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000) : 
  unused arguments (pbmc, normalization.method = "LogNormalize", scale.factor = 10000)

Thank you

**Comment by torkencz** [comment]
Hi, can you post the whole code you are running?

**Comment by knightsUCF** [comment]
This is just the standard example that is not working. I'm not sure what changed between last time when this was working just a few days ago.

```
library(dplyr)
library(Seurat)
library(patchwork)
library(Matrix)


pbmc.data <- Read10X(data.dir = "data/filtered_gene_bc_matrices/hg19")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "ProjectName", min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
```

**Comment by torkencz** [comment]
Hi,
Unfortunately, I cannot reproduce the error you have. The fact that it was working for you before makes me think that maybe something updated or a file got moved by accident. I would try maybe reinstalling/updating the package to see if the problem persists. Sorry I could not be more hepful.
