### ISSUE TITLE
Standardized variance for homogeneous cell populations

### ISSUE THREAD

**Issue by mtbiegler** [satijalab/seurat#4012]
Hi there, 

I have scRNAseq samples from a novel cell line that is very homogeneous, to the point that ribosomal genes or cell cycle markers not otherwise regressed are showing up in the top 2000 variable genes, influencing dimplot projection and clustering to dilute the impact of other variable genes. This makes the umap and feature plots very diffuse (perhaps not a problem), but cells with biologically relevant genes (i.e. cell type markers for spontaneous differentiation) are not neighboring together. 

I am wondering if there is are rules that can be applied to selecting "highly variable genes" based on the standardized variance (SV) and mean, for instance applying a cutoff at SV=2 or selecting all features above particular genes you would otherwise want to regress as opposed to an arbitrary number cutoff (2000). I have tried this, getting only 400 top variable genes, as opposed to 2000, and the cells are projecting and clustering better cell type expression profiles (see below). From reading the methods in the biorxiv paper however, I am not sure whether this selection is appropriate or justified. Curious if instead it would be better to use more comprehensive gene lists for initial regression.

Attached are a few images of the variability plots with 2000 and ~400 "high variability genes", and feature plots of the top variable gene as an example.

![VarFeats_2000_zoom](https://user-images.githubusercontent.com/65682331/106656750-1b5d4180-6569-11eb-98a3-fba8bc485b5d.png)
![VarFeats_396_zoom](https://user-images.githubusercontent.com/65682331/106656746-1ac4ab00-6569-11eb-8941-fa8a45cded8b.png)

**Comment by satijalab** [comment]
we wouldn't recommend a specific 'cutoff' for residual variance. when running SCT, genes are weighted in downstream PCA by their residual variance. therefore - after ranking by residual variance - we can often include many more genes (3,000 or more), since the additional genes contribute lower weight and are therefore less likely to have any deleterious effects after inclusion.
