### ISSUE TITLE
Conversion of loom to seurat object doesn't function as expected based on conversion_vignette.Rmd

### ISSUE THREAD

**Issue by jeremycfd** [satijalab/seurat#4013]
Attempting to coerce a loom object to a seurat object as suggested in the conversion_vignette.Rmd vignette produces a error.

```r
> l6.immune <- connect(filename = "./l6_r1_immune_cells.loom", mode = "r")
> l6.immune
Class: loom
Filename: /SSD/l6_r1_immune_cells.loom
Access type: H5F_ACC_RDONLY
Attributes: CreationDate, last_modified
Listing:
       name    obj_type  dataset.dims dataset.type_class
  col_attrs   H5I_GROUP          <NA>               <NA>
 col_graphs   H5I_GROUP          <NA>               <NA>
     layers   H5I_GROUP          <NA>               <NA>
     matrix H5I_DATASET 14908 x 27998          H5T_FLOAT
  row_attrs   H5I_GROUP          <NA>               <NA>
 row_graphs   H5I_GROUP          <NA>               <NA>
> l6.seurat <- as.Seurat(l6.immune)
Error in UseMethod(generic = "as.Seurat", object = x) : 
  no applicable method for 'as.Seurat' applied to an object of class "c('loom', 'H5File', 'H5RefClass', 'R6')"```

**Comment by finjen** [comment]
Hi, did you solve this issue or found an alternative way? Having the same problem. Thanks.

**Comment by pvtodorov** [comment]
This fails for me as well with the same error, using several of the L6 loom files.

**Comment by samuel-marsh** [comment]
Hi All,

Not member of dev team but hopefully can be helpful.  Can you confirm what versions of Seurat and SeuratDisk you are using when getting this error?

Best,
Sam

**Comment by janinemelsen** [comment]
I am having the same issue, using Seurat 4.0.1

**Comment by samuel-marsh** [comment]
Hi @janinemelsen can you confirm what version of SeuratDisk package you are using?

Best,
Sam

**Comment by janinemelsen** [comment]
Hi Sam,

SeuratDisk is not loaded at all, only SeuratObject (v4.0.0).

Best Janine

**Comment by janinemelsen** [comment]
Thanks! It works now for me via the loadLoom function of SeuratDisk.

Best,

Janine
