### ISSUE TITLE
Error in cmpCallArgs(place[-c(1, 2)], cb, ncntxt)

### ISSUE THREAD

**Issue by odagliyan** [satijalab/seurat#402]
I have upgraded to Seurat 2.3.0 , but I am having this error at ScaleData function step. This was working with the previous version of Seurat. Any suggestions?

```R
Error in cmpCallArgs(place[-c(1, 2)], cb, ncntxt) :
    attempt to set an attribute on NULL
Calls: ScaleData ... h -> cmpComplexAssign -> cmpSetterCall -> cmpCallArgs
Execution halted
```

I used this command to run ScaleData.
```R
seurat_mat <- ScaleData(object = seurat_mat, vars.to.regress = c("nUMI", "percent.mito"))
```

**Comment by bapoorva** [comment]
I had the same issue. Please refer to this

#397

**Comment by odagliyan** [comment]
thanks, but now it gives an error at FindVariableGenes as:

Error in linbin2D(x, gpoints1, gpoints2) : object 'F_lbtwod' not found

**Comment by mojaveazure** [comment]
See #70 for Fortran errors.
