### ISSUE TITLE
merging two seurat objects 

### ISSUE THREAD

**Issue by rachel662** [satijalab/seurat#4023]
Hi there,  I have two datasets that I would like to merge together, They are both already clustered and annotated. If I merge them, will the identities of the clusters be preserved? or how can i preserve these identities for further downstream ligand-receptor analysis?

**Comment by timoast** [comment]
Yes, the metadata information is preserved after merging Seurat objects

**Comment by rachel662** [comment]
Thanks for your quick response,
When the Seurat objects are merged, are all counts for all genes in both datasets preserved too?
