### ISSUE TITLE
SCTransform for clinical samples

### ISSUE THREAD

**Issue by zinagood** [satijalab/seurat#4024]
Hi Team Seurat,

I'm working on a set of clinical samples, where sample quality varies a lot among samples, and some of the samples contain different cell types. As a result, a lot of critical genes get lost when SCTransform is applied to samples individually, even when using "return.only.var.genes = FALSE". As many samples are sequenced together, is there a reason to *not* do SCTransform on merged data? The largest source of batch effects is related to sequencing depth, and so SCTransform appears to solve this. If not, what is the best alternative approach?

Thanks!

**Comment by satijalab** [comment]
if you sequence samples on the same platform (i.e. all with 10x genomics), you should be able to run SCTransform after merging, even if there are differences in sequencing dept.
