### ISSUE TITLE
Why Rownames and gene of cluster markers are not the same?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4025]
Hi everyone, 

Would anyone mind explaining why the rownames of the cluster makers are different than the gene names in the gene column, after I ran FindAllMarkers()? 

- Someone said it is because Seurat add cluster number to the gene names in #1980, but from the picture below, it does not seem to be the case for me. 
- #1544 seems to suggest to use object$gene instead of the rownames(object) of the FindAllMarkers() output?

A second question I have is, if I ran DotPlot of the object setting features = these genes that have different names, I got an error like this #2363. Why cannot we graph the data using SCT Assay? I thought DotPlot graph the scale.data from SCT Assay...

Thank you very much in advance for your help! 

![image](https://user-images.githubusercontent.com/62179082/106946177-af253e00-6720-11eb-9694-35b9ef7ec7e8.png)

**Comment by saketkc** [comment]
> Someone said it is because Seurat add cluster number to the gene names in #1980, but from the picture below, it does not seem to be the case for me.

`FindAllMarkers` returns a data frame whose rows need to be unique. This is acheived by appending a .1,.2,... (`make.unique()`) to gene names when the same gene is a marker for more than one cluster (when comparing against rest of the clusters). The gene names are indeed in the `gene` column. You can see this using `pbmc_small` dataset:

```r
> all.markers <- FindAllMarkers(object = pbmc_small)
> all.markers[105:110,]
                p_val avg_log2FC pct.1 pct.2    p_val_adj cluster   gene
VDAC3    9.715813e-03  1.2395661 0.361 0.136 1.000000e+00       0  VDAC3
FCER1G   9.842809e-03 -0.8290634 0.389 0.705 1.000000e+00       0 FCER1G
S100A8.1 1.433291e-14  6.2442495 0.960 0.091 3.296570e-12       1 S100A8
TYMP.1   4.773015e-13  3.1898437 1.000 0.164 1.097793e-10       1   TYMP
S100A9.1 3.854118e-12  5.4310717 0.880 0.164 8.864472e-10       1 S100A9
LYZ.1    9.328867e-11  3.0350946 1.000 0.473 2.145639e-08       1    LYZ
```

This should also answer your second question.

**Comment by torkencz** [comment]
Funny started answering too, as far as I know you should use object$gene. Rownames are supposed to be unique for a df so likely they are numbered in order. We generally recommend to use the RNA assay for DotPlot. There is a discussion about this here : https://www.biostars.org/p/395951/.

**Comment by denvercal1234GitHub** [comment]
Thank you all!
