### ISSUE TITLE
Gene names converted to "NA" when using gene not in default assay in dotplot

### ISSUE THREAD

**Issue by shengqh** [satijalab/seurat#4028]
When I tried to draw dotplot with curated gene list, there was one 'NA' in the end of genes in X axis.  For example, I tried to draw two genes "TRIM32" and "SPAAR" in dotplot. "TRIM32" was displayed correctly in figure. However, "SPAAR" was replaced by 'NA'
![error](https://user-images.githubusercontent.com/2760757/106963577-63659b00-6706-11eb-9a48-f755aa84c354.png)

Here is the warning message:
```
Warning: Could not find SPAAR in the default search locations, found in RNA assay instead
```

I uploaded error.rds which was compressed as [error.zip](https://github.com/satijalab/seurat/files/5928874/error.zip).

```r
sobj=readRDS('error.rds')
DotPlot(sobj, features=c("TRIM32", "SPAAR"))
```

**Comment by saketkc** [comment]
Thanks for sharing the object. We recommend you visualize expression int the original RNA space. Your default assay is set to integrated which causes DotPlot to pull values from the integrated assay. You would instead want to plot the original RNA values:

```
DotPlot(sobj, features=c("TRIM32", "SPAAR"), assay = "RNA")
```
Both of these features are not expressed:

```r
> rna <- GetAssayData(object = sobj,assay = "RNA", slot = "counts" )
>  sum(rna["SPAAR",])
[1] 0
>  sum(rna["TRIM32",])
[1] 0
```
