### ISSUE TITLE
use.imputed

### ISSUE THREAD

**Issue by verma014** [satijalab/seurat#403]
Hi, I am testing out imputation for single cell using MAGIC and scImpute. A handy place to store the output for these is in obj@imputed. Several commands allow for the "use.imputed =TRUE" parameter such as VlnPlot. 
It looks FindMarkers also allows for "use.imputed" however the results do not seem to change. Any thoughts on how to get differentially expressed genes using the values from obj@imputed?

An alternative to this is to use the imputed values as the raw data or scaled data. However, I would like to retain the PCAs and cluster to that I can perform direct comparisons between the imputed and non-imputed values. 
Any other strategies or thoughts about organizing the data with the imputation would also be appreciated. 
Thanks!

**Comment by satijalab** [comment]
We agree - and are updating a couple functions to work off of imputed data, stored in the impute slot.

However, we would suggest caution when performing downstream analyses (particularly, dimensional reduction, clustering, or differential expression) on imputed data.

**Comment by verma014** [comment]
Thanks for the warning on using imputed data for downstream analyses. I'm cautiously optimistic about imputed data and look forward to the update to make resting it easier. I'm keeping my fingers crossed for a small Frequently Requested Vignette as well.
Regards
