### ISSUE TITLE
FeaturePlot using a column in meta.features to select gene for plotting

### ISSUE THREAD

**Issue by vitkl** [satijalab/seurat#4034]
Hi Seurat team

I am using ENSEMBL id as row names but I would like to be about to use FeaturePlot calling genes by symbol stored in assay's meta.features. It is implemented in scanpy but I was not able to find how to do this in Seurat. This effectively means that I need to copy large objects & rename rownames to gene symbols. Would be great to have that feature (sorry if it already exists and I missed it).

Thanks!

**Comment by saketkc** [comment]
Hi @vitkl, sorry for the delayed response. This is currently not supported, but we are considering supporting related features in a future version of Seurat.

**Comment by sailseem** [comment]
wish this can be done, it will be really helpful

**Comment by rsatija** [comment]
Apologies that we've decided not to support this. Plotting is already quite complex, since there are multiple assays and slots that a user can choose to pull data from. Adding the ability to also pull from alternate feature names would cause additional complications and bugs as well.
