### ISSUE TITLE
IntegrateData() all NaN values 

### ISSUE THREAD

**Issue by decapicone** [satijalab/seurat#4036]
I love it when this happens! so awesome to have all NaN values for data analysis!

```
rna.atac.anchors <- FindIntegrationAnchors(integration.list, reference = length(integration.list), 
                                           normalization.method = 'LogNormalize', reduction = 'cca', dims = 1:30)

rna.atac.int <- IntegrateData(anchorset = rna.atac.anchors, normalization.method = 'LogNormalize')

rna.atac.int <- ScaleData(rna.atac.int)
rna.atac.int <- RunPCA(rna.atac.int, assay = 'integrated')

Error in irlba(A = t(x = object), nv = npcs, ...) :
  max(nu, nv) must be positive
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 1158 features requested have zero variance (running reduction without them): [every single feature! :-) ]

rna.atac.int@assays$integrated@data 
THSD7B   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
FGF13    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
ZNF804B  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
IL1RAPL2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
HECW1    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
TLL1     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
SULF1    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
BTBD11   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
COL25A1  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
..................... the list goes on

```

Whats wrong here?

**Comment by decapicone** [comment]
I believe the issue was that I had multiple assays in each object with unmatched names, even though I tried specifying `assay =` in the integration function.  I deleted all unused assays with `object[['assay.name']] <- NULL` and then renamed the assays in both objects to the same name with `object <- RenameAssays(object, old.name = new.name)`  Then I integrated the new objects.  Be sure to save each object so that you still have old assays if you need them

**Comment by gdcfy** [comment]
> I believe the issue was that I had multiple assays in each object with unmatched names, even though I tried specifying `assay =` in the integration function. I deleted all unused assays with `object[['assay.name']] <- NULL` and then renamed the assays in both objects to the same name with `object <- RenameAssays(object, old.name = new.name)` Then I integrated the new objects, which only contained the single renamed assay. Be sure to save each object so that you still have old assays if you need them

Hello! among this question, is there any specific code example?
