### ISSUE TITLE
Combining reciprocal PCA with reference-based integration and SCTransform normalization

### ISSUE THREAD

**Issue by parvathisudha** [satijalab/seurat#4037]
Hi, 

I am trying the reciprocal PCA for integration of 26 samples (~186K cells). Seurat tutorial recommend combining reciprocal PCA with reference-based integration or SCTransform normalization. I have two questions. 
1) Will it okay, if I use reciprocal PCA with reference-based integration and SCTransform normalization? 
2) My samples are from two conditions. Is it recommended to use the control samples as reference? Or the reference can be any sample/samples from the object.list?

Also, I believe since using SCT, I should not use "ScaleData" for the samples.

Thank you,
Parvathi.

**Comment by yuhanH** [comment]
HI, 
You can use rpca + reference-based inegration + SCTransformation. 
We would suggest you use control samples as reference in the integration, if you have control samples. 
For `ScaleData`, you are right. When you use SCT, we depend on residual variance to do the downstream analysis, so we don't want to use  `ScaleData` which will make all genes variance to 1.
