### ISSUE TITLE
Is there a way to do integration as Seurat 3.1.5 with Seurat 4.0.0?

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [satijalab/seurat#4041]
We noticed that the way Seurat does integration in Seurat 3.1.5 is different from the version after 3.1.5.
Since for our system, the resulting UMAP of 3.1.5 integration makes a lot more sense, is there a way to do integration as Seurat 3.1.5 with Seurat 4.0.0?

**Comment by Hsu-Che-Wei** [comment]
<img width="372" alt="Screen Shot 2021-02-08 at 8 29 59 AM" src="https://user-images.githubusercontent.com/44936028/107164064-1d4f5680-69e8-11eb-8a6d-fc528e9de140.png">
<img width="372" alt="Screen Shot 2021-02-08 at 8 30 08 AM" src="https://user-images.githubusercontent.com/44936028/107164067-204a4700-69e8-11eb-9532-e45956972fb2.png">

These are the UMAPs obtained by the same integration pipeline using v3.1.5 and v4.0.0 respectively, the color indicates three transcriptionally distinct and continuous developmental states, yet only in the v3.1.5, the ordination of UMAP captures the expected developmental direction, we don't want to lose the ability to obtain such UMAP when adapting to v4.0.0, since the new reference mapping function requires the users to rerun the integration process. Would you please indicate what you have modified in the code so that I can possibly reverse it in v4.0.0?

Thank you very much!

Che-Wei

**Comment by andrewwbutler** [comment]
I would caution against reading to much in to the UMAP plots. If you want to reproduce an analysis from an earlier version, you will need to use that version of the software (and of its dependencies - e.g. UMAP). We provide a number of docker images [here](https://hub.docker.com/r/satijalab/seurat) to enable this. It is not possible to reproduce exactly the results from a v3.1.5 analysis using v4.0.0.
