### ISSUE TITLE
Question about Demultiplexing

### ISSUE THREAD

**Issue by ReInPea** [satijalab/seurat#4046]
Hi I'm a med student who want to learn about scRNA-Seq.

In my lab, We will make new project about scRNA-Seq about Pemphigus.

So now I learn about HTO Demultiplexing.

We don't have HTO Data so I learn using open source data.

I downloaded GSE132798 data and loaded to R and make some code refer to Demultiplexing with hashtag oligos (HTOs)

But It doesn't work.

```
rna <- Read10X("C:/Users/localadmin/Desktop/Project/Seraut/GSE132798_RAW/19003")
hto <- Read10X("C:/Users/localadmin/Desktop/Project/Seraut/GSE132798_RAW/GSM3892347_AW19004",gene.column = 1)

hash <- CreateSeuratObject(counts = rna, min.cells = 3, min.features = 200)

hash <- NormalizeData(hash)
hash <- FindVariableFeatures(hash, selection.method = "mean.var.plot")
hash <- ScaleData(hash, features = VariableFeatures(hash))

hash[['HTO']] <- CreateAssayObject(counts = hto[, colnames(x = hash)])
```

This is what I made and error code is 

> hash[['HTO']] <- CreateAssayObject(counts = hto[, colnames(x = hash)])
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

How can I adjust the code? or how can I make RDS file like satija provide (pbmc_hto_mtx.rds)

I'm sorry to question like this easy problem. and thanks for any feedback.

**Comment by torkencz** [comment]
Hi,
Unfortunately, I do not see your data but based on the error I think I would would intersect your cell names first.
joint.bcs <- intersect(colnames(rna), colnames(hto))
Subset RNA and HTO counts by joint cell barcodes
filt.umis <- rna[, joint.bcs]
filt.htos <- as.matrix(hto[, joint.bcs])
And then create the Seurat object. I will close this for now but let me know if it works/does not work and I can try to help further.
