### ISSUE TITLE
FindMarkers with Negative Binomial, Poisson or DESeq2: offset the log of library size done under the hood?

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [satijalab/seurat#4048]
For the methods of ```FindMarkers``` that use count data (e.g., negative binomial, Poisson or DESeq2), I just wonder whether they offset the log of library size under the hood.

On a related note, given that SCTransform saves the ‘corrected’ UMI counts ("interpret these as the UMI counts we would expect to observe if all cells were sequenced to the same depth" in [here](https://satijalab.org/seurat/archive/v3.0/sctransform_vignette.html)), using ```assay = "SCT"``` and ```slot = "counts"``` in ```FindMarkers``` should take care of differences in library size per cell if the methods above do NOT offset log lib.size?

Any help would be much appreciated.

**Comment by jaisonj708** [comment]
I'm assuming by "offset" you mean normalizing/somehow accounting for library size. The DE methods you mention are robust to changes to library size (ie, library size or a function of library size is included in the DE model). So there is no need to "correct" counts before running these DE methods, it would actually be discouraged.

**Comment by PedroMilanezAlmeida** [comment]
That is not true. Neither Poisson nor negative binomial inherently model library size. Indeed, one needs to model exposure explicitly to account for differences in things like time or area of observation (or library size, as in the case of scRNA-Seq, https://en.wikipedia.org/wiki/Poisson_regression#%22Exposure%22_and_offset).

With this sentence "So there is no need to "correct" counts before running these DE methods, it would actually be discouraged." are you saying that SCTransform should not be used when performing DE analysis given that SCTransform "corrects" the counts?

**Comment by duocang** [comment]
@PedroMilanezAlmeida 

It has been mentioned too many times that  `RNA` is the one for `FindMarkers` but no specific reasons were given (maybe I do not find them).

Do you try to compare the result ever?
