### ISSUE TITLE
subset() function giving error in v4.0.0

### ISSUE THREAD

**Issue by aditisk** [satijalab/seurat#4049]
Hello,

I recently switched to version 4.0.0 and I am running into issues using the subset() function. 

Here is my command and the output:

>cd8_pbl = subset(cd8,subset = Type == "PBL")
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided
 >table(cd8@meta.data$Type)

 > PBL   TIL 
25739 29291

The same syntax works for me in v3. Is there a different syntax for v4 for subsetting ? Thanks a lot.

**Comment by andrewwbutler** [comment]
Hi,

The syntax for `subset` hasn't changed. Do you happen to have a variable in the environment also called `"Type"` at the time of calling `subset`?

**Comment by aditisk** [comment]
Hi @andrewwbutler,

I don't think I have another variable called "Type" in the environment. I tried once again and the syntax works for v3.1.5 but still gives me an error in v4.0.0.

**Comment by andrewwbutler** [comment]
Hmm, that is strange. Are you able to provide data for a reproducible example? A somewhat more verbose way of subsetting which should be equivalent:

```R
pbl.cells <- Cells(cd8)[which(x = cd8$Type == "PBL")]
cd8_pbl <- subset(cd8, cells = pbl.cells)
```
