### ISSUE TITLE
RunPCA and JackStraw warnings (irlba did not converge)

### ISSUE THREAD

**Issue by malosreet** [satijalab/seurat#405]
Hello Seurat team,

I used the RunPCA function with my data-set and got the following warning:
```R
> All_batches_filt <- RunPCA(All_batches_filt, pc.genes = All_batches_filt@var.genes, do.print = FALSE, pcs.compute = 100, maxit = 200)

Warning in irlba(A = t(x = data.use), nv = pcs.compute, ...) :
  did not converge--results might be invlaid!; try increasing work or maxit
```
Initially I was not providing any maxit, but based on the warning message I provided a higher maxit and this resolved the problem. However, when I tried to use the JackStraw function, I got the same warning message:
```R
> All_batches_filt <- JackStraw(All_batches_filt, num.pc = 100, num.replicate = 100, do.print = FALSE, prop.freq = 0.05)
Warning in irlba(A = t(x = data.use), nv = pcs.compute, ...) :
  did not converge--results might be invlaid!; try increasing work or maxit
Warning in irlba(A = t(x = data.use), nv = pcs.compute, ...) :
  did not converge--results might be invlaid!; try increasing work or maxit
Warning in irlba(A = t(x = data.use), nv = pcs.compute, ...) :
```
Basically for every permutation it is trying, it gives the warning message because the irlba function does not converge. I tried to set maxit to fix the problem as before, but the JackStraw function does not allow passing arguments for irlba like the RunPCA function. Would it be possible to provide this feature? Has anyone else experienced this problem?

Thanks for your help!

Malosree

**Comment by leonfodoulian** [comment]
Hi,

I have proposed a PR that adds a `maxit` argument to `Seurat::JackStraw()`. The argument defaults to 1000 as in `irlba::irlba()`.  Once the PR is accepted, you should be able to download the development version of Seurat as described [here](http://satijalab.org/seurat/devinstall.html).

Best,
Leon

**Comment by leonfodoulian** [comment]
My bad! The PR corresponds to #407.

**Comment by malosreet** [comment]
I thought the default maxit for irlba was 100, but thank you for creating the PR!

**Comment by leonfodoulian** [comment]
You can check the default parameters by running `?irlba::irlba` on R.

```R
irlba(A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,
  tol = 1e-05, v = NULL, right_only = FALSE, verbose = FALSE,
  scale = NULL, center = NULL, shift = NULL, mult = NULL,
  fastpath = TRUE, svtol = tol, smallest = FALSE, ...)
```

Have a nice one!

Best,
Leon
