### ISSUE TITLE
SCTransform on individual batches or merged Assay to do PCA?

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#4051]
Hi,

I have an integration pipeline involving both Seurat Integration and Harmony for data obtained from Clinical Samples. Samples all run on 10x. They are all the same tissue, only disease conditions vary.
Seurat Integration works great for the full data set of unsorted cells (>115k cells in 30 10x runs). I followed the standard sctransform integration workflow in your vignette.

But when I do subsetting of particular cell types (such as Myeloid cells); Harmony seemed to work better in my case. Basically, Seurat integration helps me choose the major cell types and then for detailed zoomed analysis, I intend to use harmony.

So, this is how I thought I could go. FYI, Harmony developers [suggested](https://github.com/immunogenomics/harmony/issues/41) that SCTransform pipeline is fine for harmony as harmony doesn't care about how we reach up until PCA. That is the part I would like to get your suggestion on. The same thread extensivley discuss this.
```
#Integration by Sample done using SCTransform Integration
>Integrated_Seu
An object of class Seurat 
52373 features across 116547 samples within 3 assays 
Active assay: RNA (26010 features, 0 variable features)
  2 other assays present: SCT, integrated
  2 dimensional reductions calculated: pca, umap

Myeloid_cells <- WhichCells(Integrated_Seu, idents=  c(1,2,3))

>length(Myeloid_cells)
[1] 14816

```
**#1st method**
```
Mye_Seu <- subset(Seu, cells = Myeloid_cells)

Mye_Seu <- SCTransform(Mye_Seu, vars.to.regress = "percent.mt", assay = "RNA")
Mye_Seu <- RunPCA(Mye_Seu, npcs = 100)
Mye_Seu <- RunHarmony(Mye_Seu)
var_features_comb_sct <- VariableFeatures(Mye_Seu)


```
**#2nd method**
```
Mye_Seu_list <- SplitObject(Mye_Seu, split.by = "Sample")
for(i in 1:length(Mye_Seu)){
  Mye_Seu <- SCTransform(Mye_Seu_list[[i]], vars.to.regress = "percent.mt", assay = "RNA")
}
var_features_ind_sct <- SelectIntegrationFeatures(Mye_Seu_list, nfeatures = 3000)
Mye_Seu <- merge(Mye_Seu_list[[1]], Mye_Seu[2:length(Mye_Seu)])
```
As merging will not carry over the Variable features;
```
VariableFeature(Mye_Seu) <- var_features_ind_sct
Mye_Seu <- RunPCA(Mye_Seu, npcs = 100)
Mye_Seu <- RunHarmony(Mye_Seu)
```
Surprisingly, the difference in the variable features detected in these methods were very different. Out of 3000,only 1133 were common

```
> length(setdiff(var_features_comb_sct, var_features_ind_sct))
[1] 1867
```

Thanks and Kind regards,
Saeed

**Comment by saketkc** [comment]
Hi @saeedfc, The difference in variable features is expected. [SelectIntegrationFeatures](https://www.rdocumentation.org/packages/Seurat/versions/4.0.0/topics/SelectIntegrationFeatures) will select a list of features by ranking them based on how many datasets they are found to be variable in.

In your first method, you are asking SCTransform to identify variable features in myeloid subpopulation. In your second method, you are using SCTransform + Integration to identify features that best help you integrate. But they are very different things.

Please reopen if I misunderstood your question.

**Comment by saeedfc** [comment]
HI Saket,

Got your point. I that case, what would be the best strategy to get to uncorrected PCA (to be batch corrected later using harmony)?, 
1) Do SCTransform individually on each batch and then combine variable features identified in each batch and add it to the merged object before doing PCA?

```
Mye_Seu_list <- SplitObject(Mye_Seu, split.by = "Sample")
var_features <- list()
for(i in 1:length(Mye_Seu)){
  Mye_Seu <- SCTransform(Mye_Seu_list[[i]], vars.to.regress = "percent.mt", assay = "RNA")
  var_features[[i]] <- VariableFeatures(Mye_Seu_list[[i]])
}
var_features<-unlist(var_features)
Mye_Seu <- merge(Mye_Seu_list[[1]], Mye_Seu[2:length(Mye_Seu)])
VariableFeatures(Mye_Seu) <- unique(unlist((var_features)))
Mye_Seu <- RunPCA(Mye_Seu)
Mye_Seu <- RunHarmony(Mye_Seu, "Sample")
```

2) Or merge raw counts and go with standard SCTransform pipeline until PCA?

```
# Mye_Seu ##Merged Object
DefaultAssay(Mye_Seu) <- "RNA"
Mye_Seu <- SCTransform(Mye_Seu)
Mye_Seu <- RunPCA(Mye_Seu)
Mye_Seu <- RunHarmony(Mye_Seu, "Sample")

```
Thanks for your time,
Saeed

**Comment by poconnel3** [comment]
> HI Saket,
> 
> Got your point. In that case, what would be the best strategy to get to uncorrected PCA (to be batch corrected later using harmony)?,
> 
> 1. Do SCTransform individually on each batch and then combine variable features identified in each batch and add it to the merged object before doing PCA?
> 
> ```
> Mye_Seu_list <- SplitObject(Mye_Seu, split.by = "Sample")
> var_features <- list()
> for(i in 1:length(Mye_Seu)){
>   Mye_Seu <- SCTransform(Mye_Seu_list[[i]], vars.to.regress = "percent.mt", assay = "RNA")
>   var_features[[i]] <- VariableFeatures(Mye_Seu_list[[i]])
> }
> var_features<-unlist(var_features)
> Mye_Seu <- merge(Mye_Seu_list[[1]], Mye_Seu[2:length(Mye_Seu)])
> VariableFeatures(Mye_Seu) <- unique(unlist((var_features)))
> Mye_Seu <- RunPCA(Mye_Seu)
> Mye_Seu <- RunHarmony(Mye_Seu, "Sample")
> ```
> 
> 1. Or merge raw counts and go with standard SCTransform pipeline until PCA?
> 
> ```
> # Mye_Seu ##Merged Object
> DefaultAssay(Mye_Seu) <- "RNA"
> Mye_Seu <- SCTransform(Mye_Seu)
> Mye_Seu <- RunPCA(Mye_Seu)
> Mye_Seu <- RunHarmony(Mye_Seu, "Sample")
> ```
> 
> Thanks for your time,
> Saeed

Hi Saeed, 

I am having the same issue as you. Which approach did you decide to go with/which worked better? I am leaning towards option #2.
