### ISSUE TITLE
DoHeatmap function: how to remove "identity" legend but leave and adjust "expression" legend?

### ISSUE THREAD

**Issue by Florencia1805** [satijalab/seurat#4052]
Hi all, 

Perhaps a very basic question, but for the purpose of using my heatmap for an article figure: when I use DoHeatmap(), how do I remove the "identity" legend without also removing the "expression" legend? When I use NoLegend(), both disappear of course. 

In addition, how can I adjust the text size of the "expression" legend so that it is still readable when I reduce the size of my heatmap?

Many thanks in advance,
Florencia

**Comment by andrewwbutler** [comment]
Hi,

The plots return by `DoHeatmap()` are ggplot objects so they can be manipulated using the native tooling ggplot2 provides. For your cases, you can selectively remove legends using `guides` and change text sizes with `theme`. E.g.

```R
library(Seurat)
library(ggplot2)
DoHeatmap(pbmc_small) +
   guides(fill = FALSE) + 
   theme(legend.text = element_text(size = 15), 
         legend.title = element_text(size = 15))
```
