### ISSUE TITLE
scRNA-seq integration 

### ISSUE THREAD

**Issue by behyag** [satijalab/seurat#4053]
Hi Andrew 
Thank you so much for the reply 
The results are still reproducible between the two pipelines, sorry for the incorrect allegation 
I, however, struggle to reproduce the integration results from my "NormalizeData + FindVariableFeatures preprocessing" when running your SCTransformation pipeline. I do not know if it is expected that the output is different between the two pipelines or maybe you have some tips to obtain the same results? 
Kindest regards, 
Peter

_Originally posted by @RolantusdataExp in https://github.com/satijalab/seurat/discussions/4017#discussioncomment-348709_

**Comment by andrewwbutler** [comment]
Hi,

To limit duplication, please keep discussions in the discussion section.
