### ISSUE TITLE
scRNA-seq integration , FindIntegrationAnchors()

### ISSUE THREAD

**Issue by behyag** [satijalab/seurat#4054]
hi satijalab, 

 I have two questions about scRNA-seq integration: 

1. what is the default normalization method for FindIntegrationAnchors() ? "LogNormalize" or "SCT" if it's nit set as in the guidelines?

2. I have two datasets that I want to integrate (intact & treated) I have split them in the first part of integration by "condition" which is already added to the metadata of my merged object:

condition.list <- SplitObject(my_merged_obj, split.by = "condition")

is is possible to use the "intact" list /dataset as the reference for FindIntegrationAnchors() ? if yes, how should I set this parameter of the function? reference = ??

thank you for your help!
/Behzad

**Comment by saketkc** [comment]
> what is the default normalization method for FindIntegrationAnchors() ? "LogNormalize" or "SCT" if it's not set as in the guidelines?

Default is LogNormalize

> is possible to use the "intact" list /dataset as the reference for FindIntegrationAnchors() ? if yes, how should I set this parameter of the function? reference = ??

Please see [this vignette](https://satijalab.org/seurat/articles/integration_large_datasets.html) for an example.
