### ISSUE TITLE
FindTransferAnchors reference.reduction question - NULL vs pca

### ISSUE THREAD

**Issue by cGauthi** [satijalab/seurat#4055]
I'm running the Mapping and Annotating Query datasets vignette and have run into output difference when changing the reference.reduction parameter in the FindTransferAnchors step.  I'm trying both because there are differences between the [Mapping and Annotating Query Datasets vignette](https://satijalab.org/seurat/articles/integration_mapping.html) and the [Multimodal Reference Mapping vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html).

The Mapping and Annotating Query Dataset has it left as NULL while the Multimodal Reference Mapping sets it to 'spca'.  Two calls I have used are as follows (I've used pca instead of spca):

`anchors1 <- FindTransferAnchors(reference = seurat_reference, query = query_filtered, normalization.method = 'SCT', dims = 1:30) `

`anchors2 <- FindTransferAnchors(reference = seurat_reference, query = query_filtered, normalization.method = 'SCT', reference.reduction = 'pca', dims = 1:30)`

Followed by
`query_filtered <- MapQuery(anchorset = anchors1, reference = seurat_reference, query = query_filtered, refdata = list(cluster = 'seurat_clusters'), reference.reduction = 'pca', reduction.model = 'umap')`

`ref_umap <- DimPlot(seurat_reference, reduction = 'umap', group.by = 'seurat_clusters', label = TRUE, repel = TRUE) + NoLegend() + ggtitle('Reference clusters')`

`query_umap <- DimPlot(query_filtered, reduction = 'ref.umap', group.by = 'predicted.cluster', label = F, label.size = 3, repel = T) + ggtitle('Query transferred clusters')`

`ref_umap + query_umap`

The difference has caused a pretty large difference in the outputs which I guess should be expected.  But I'm wondering which one is more correct?  They both use the same baseline inputs but the query data is mapped very differently as a final output based on that one parameter.

**Comment by Ruismart** [comment]
hi, I'm searching other issues for FindTransferAnchors(), I think the source code in integration.R line 630-650 may help ~

**Comment by timoast** [comment]
If `reference.reduction` is NULL, then a new PCA will be computed on the reference and used for the PCA projection with the query. If you specify "pca," then the existing PCA dimension reduction in the reference object is used. We will update the documentation for FindTransferAnchors to better explain this.

**Comment by dpwlek1997** [comment]
Hi cGauthi, i am facing the same question here. Were you able to figure out the answer? 

Thanks!
