### ISSUE TITLE
Best way to run FindTransferAnchors() with multiple query datasets

### ISSUE THREAD

**Issue by decapicone** [satijalab/seurat#4056]
I have 23 snRNA datasets from brain tissue.  These datasets were integrated and results were very good.  

The reference dataset is from 14 different 10X runs from two individuals which were also integrated into one.  There was a presentation from satija lab somewhere online (I forget where) where they showed that integrated datasets can be used for a reference.

My question, however, concerns the query datasets.  I see 3 different ways to run `FindTransferAnchors`
1) Run `FindTransferAnchors `between integrated reference (14 datasets) and integrated query (23 datasets)
2) Run `FindTransferAnchors `between integrated reference (14 datasets) and merged query (23 datasets, uncorrected batch effects)
3) Individually run `FindTransferAnchors `between the integrated reference (14 datasets) and each query dataset one at a time, and then combine `predicted.labels` obtained from `TransferData`.  

My opinion is that option 3 is the best. I feel that option 2 introduces batch effects to the CCA reduction used for `FindTransferAnchors`

**Comment by yuhanH** [comment]
Hi, 
Right. I vote for option3 as well. 
In the second part of the [mapping vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html#example-2-mapping-human-bone-marrow-cells-1), we mapped multiple batches of HCA bone marrow to our bone marrow reference batch by batch.
