### ISSUE TITLE
Unimodal UMAP Projection - Mapquery

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#4057]
Hello,

Thank you for this great new tool. I am wondering whether it is possible to use an existing tSNE embedding I have produced for my reference data set and want to keep to project query data sets using the MapQuery function unimodal UMAP projection?

I have two reference data sets on which I want to project query data sets but I do not want to change the embedding I already have. Is this possible to do?

Thank you.

**Comment by yuhanH** [comment]
HI, 
Currently, we don't support project new cells to tSNE plot. The umap projection method mainly depends on [uwot](https://github.com/jlmelville/uwot) .
