### ISSUE TITLE
TSCAN: Pseudo-time reconstruction and evaluation in single-cell RNA-seq analysis  

### ISSUE THREAD

**Issue by Yukii3o** [satijalab/seurat#4060]
Hey everyone, 
i'm new to single-cell RNA-seq analysis and to coding with R ! 
After using TSCAN for pseudotime reconstruction on a seurat object, i wanted to combine the TSCAN results and my seurat object but i didn't know how to ! Any help would be appreciated !! 
Thank you !

**Comment by k3yavi** [comment]
Hey @Yukii3o ,

Thanks for reaching out. We currently don't have support built-in for the TSCAN's pseudotime construction.
However, please check [this](https://github.com/satijalab/seurat-wrappers/blob/master/R/monocle3.R) function where we are using Monocle3 for transferring pseudotime. In case you are able to build the infrastructure around TSCAN, please feel free to make a PR to the `seurat-wrappers` repo.
