### ISSUE TITLE
merge takes very long

### ISSUE THREAD

**Issue by linzhangTuesday** [satijalab/seurat#4061]
Hi I am trying to merger three scATAC seq samples, following merging after creating a common peak set from the Signac vignette(https://satijalab.org/signac/articles/merging.html) 

My objects are ~250k features across ~30k,6k and 5k samples respectively.

The merging is taking near an hour now and have not finished.

Any suggestions on that?

**Comment by timoast** [comment]
Please try using the version on the develop branch of Signac
