### ISSUE TITLE
WNN: multi sample integration

### ISSUE THREAD

**Issue by mamtagiri** [satijalab/seurat#4064]
Hi guys.. I have read up a few similar question in the issue section but wanted to conform the workflow for using WNN on multi sample multimodal data.

Process each sample/assay separately 
Use findanchors to integrate both RNA and ADT assay separately 
run WNN on the integrated assay

Please let me know if my understanding is correct and I can implement this for my data.

Thanks so much!!

**Comment by yuhanH** [comment]
right. You can integrate each modality separately. Then, perform WNN on both integrated assay. 
Just need to make sure the integrated assay name for two modalities are different.

**Comment by mamtagiri** [comment]
Thanks! I named the art integrated assay as "integrated.adt" . however, still after running all of the RNA integration parameters as well as assay gets overwritten.
I tried merging integrated RNA assay from another object, but it still doesn't add the "reduction" information. When I tried to just use object[["pca"]], it still doesn't work.

Any suggestion how to fix that?

**Comment by yuhanH** [comment]
You can integrate RNA and ADT using two objects, obj1 and obj2. 
Then, you can create integrated.adt assay, and adt.pca in the obj1 to fill up the integrated value from obj2.

**Comment by jessielyons** [comment]
Hi @mamtagiri , can you share your code WNN on multi sample multimodal data? Seurat has no vignette on it and it's very confusing on how to do this.

**Comment by jessielyons** [comment]
Hi @yuhanH , so I tried to follow the notes here and separately ran FindIntegrationAnchors and separate pca for each modalities. So I have two objects (RNA with 'pca' reduction and ADT with 'apca' reduction). What do I need to do with these two separate seurat objects before I run "FindMultiModalNeighbors" for wnn? @yuhanH I didn't follow what you mean by "Then, you can create integrated.adt assay, and adt.pca in the obj1 to fill up the integrated value from obj2."? Please help with the command line, thanks a lot.

**Comment by jessielyons** [comment]
Hi @yuhanH  and @mamtagiri , what is the best way to add assay from one seurat object to another? I get error when I try to run the following.

RNA.object[["integrated.adt"]] <- CreateAssayObject(counts = ADT.object[["integrated"]])
Error in UseMethod(generic = "as.sparse", object = x) : 
  no applicable method for 'as.sparse' applied to an object of class "Assay"

**Comment by mamtagiri** [comment]
Hey @jessielyons 
I had done the follow and it had worked for me, where Ileal_60kAdt.rds is my ADT assay processed separately and saved and Integratedadt.rds is my rNA assay processed separately and saves.

cite<-readRDS("Ileal_60kAdt.rds")
adt<-readRDS("Integratedadt.rds")
DefaultAssay(cite2) <- "integrated"
DefaultAssay(adt) <- "integrated.adt"
cite2[["integrated.adt"]]<-adt[["integrated.adt"]]
cite2[["adt.pca"]]<-adt[["apca"]]
