### ISSUE TITLE
Generating a Reference dataset for mapping

### ISSUE THREAD

**Issue by sylestiel** [satijalab/seurat#4065]
Hi,

How can i generate a **reference dataset for mapping** for the **multi-omic assay** analysis. What file types would I need to generate them. Would we use scRNA seq dataset files deposited in GEO (for e.g. genes, matrix and counts). I do not understand what LoadH5 Seurat means? I did glance at the vignette but I feel confounded. Should I be running some of this using Seurat first?

Care to shed some light or furnish some pointers.

**Comment by andrewwbutler** [comment]
Hi,

Please see the [Weighted Nearest Neighbor](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html) vignette for an example of how to generate a multimodal Seurat object. `LoadH5Seurat` simply loads in our precomputed reference object into R.
