### ISSUE TITLE
SCT and integrated assay missing when running saverds on integrated object 

### ISSUE THREAD

**Issue by RolantusdataExp** [satijalab/seurat#4072]
This issue is assumably super simple to fix, but can't figure a way my self. 
For some reason I can't save the data found in the assays SCT and integrated when running saveRDS. 
The assays simply says "S4 (Seurat::SCTassay) S4 object of class SCTassay" in the saved object 
In the object I run saveRDS on include data in both these assays, so it seems like some kind of bug.. 

I am running the newest Seurat version

**Comment by andrewwbutler** [comment]
Hi,

Can you post the output of `sessionInfo()` after you get this error?

**Comment by RolantusdataExp** [comment]
I fix my issue by simple downgrading to version 3.2.3
