### ISSUE TITLE
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric, : invalid 'x'

### ISSUE THREAD

**Issue by xihuiyin** [satijalab/seurat#4073]
Hello, I am trying to run the following code for my integrated object and I get this error:
```
all.list <- SplitObject(all.combined, split.by = "mice")

all.list <- lapply(X = all.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
```

When I try to debug, it tells me this:
```
Called from: simpleLoess(y, x, w, span, degree = degree, parametric = parametric, 
    drop.square = drop.square, normalize = normalize, statistics = control$statistics, 
    surface = control$surface, cell = control$cell, iterations = iterations, 
    iterTrace = control$iterTrace, trace.hat = control$trace.hat)
Error during wrapup: unimplemented type (29) in 'eval'

Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error during wrapup: INTEGER() can only be applied to a 'integer', not a 'unknown type #29'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart


```
May I know what went wrong here? I tried looking at previous issues but the answers were not really helpful.
Thanks!

**Comment by xihuiyin** [comment]
For some reason this code works when I have less than 5 datasets. I wonder if it has to do with my datasets being too large?

**Comment by saketkc** [comment]
You should be running this on the `RNA` assay (by specifying `assay="RNA"`) and not the integrated assay (which I am assuming is the default assay here).

**Comment by Yale73** [comment]
@xihuiyin Have you fixed it? I don't think it is because of large datasets, as I still got the error after I downsampled the datasets to smaller ones. 

BTW, the `assay="RNA" `doesn't help. 


Thanks,
Yale

**Comment by saketkc** [comment]
Can you post the code here @xihuiyin? Thanks!

**Comment by qiaolei-code** [comment]
I meet this problem,I know the answer.Our data is FALSE.I will give a example,I hope my answer can deal with your problem.
some data that cells numbers is very fewer,so the data isn't use IntegrateData to deal. 
> head(Hepatocytes1)
                        orig.ident nCount_RNA nFeature_RNA
HCC08P_AAACCTGTCTCTGCTG     HCC08P       9090         2433
HCC08P_AAACCTGTCTTAACCT     HCC08P       7116         2393
HCC08P_AAACGGGCAAGTAATG     HCC08P       8865         2499
HCC08P_AAACGGGCAGGAATCG     HCC08P       8368         2341
HCC08P_AAACGGGGTAATCACC     HCC08P       6973         2203
HCC08P_AAACGGGGTCTCGTTC     HCC08P       4988         1807
HCC08P_AAAGATGCAGCTGTGC     HCC08P       7045         2078
HCC08P_AAAGATGCAGTGGAGT     HCC08P       4984         1903
HCC08P_AAAGCAATCCAGGGCT     HCC08P       9453         2880
HCC08P_AAAGTAGAGCCCAACC     HCC08P       4196         1786
> table(Hepatocytes1$orig.ident)

HCC03N HCC04N HCC05N HCC06N HCC07N HCC07P HCC08N HCC08P HCC09N HCC10N
   281     70      7    122     12     11      1    776      5      6
> Hepatocytes.list <- SplitObject(Hepatocytes1, split.by = "orig.ident")
> # perform standard preprocessing on each object
> for (i in 1:length(Hepatocytes.list)) {Hepatocytes.list[[i]] <- NormalizeData(Hepatocytes.list[[i]],verbose = FALSE)
 Hepatocytes.list[[i]] <- FindVariableFeatures(Hepatocytes.list[[i]], selection.met                                                                                                               = "vst",nfeatures = 2000, verbose = FALSE)}
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  invalid 'x'
>   Hepatocytes.list[[1]] <- NormalizeData(Hepatocytes.list[[1]],verbose = FALSE)
>   Hepatocytes.list[[2]] <- NormalizeData(Hepatocytes.list[[2]],verbose = FALSE)
>   Hepatocytes.list[[3]] <- NormalizeData(Hepatocytes.list[[3]],verbose = FALSE)
>   Hepatocytes.list[[4]] <- NormalizeData(Hepatocytes.list[[4]],verbose = FALSE)
>   Hepatocytes.list[[5]] <- NormalizeData(Hepatocytes.list[[5]],verbose = FALSE)
>   Hepatocytes.list[[6]] <- NormalizeData(Hepatocytes.list[[6]],verbose = FALSE)
>   Hepatocytes.list[[7]] <- NormalizeData(Hepatocytes.list[[7]],verbose = FALSE)
>   Hepatocytes.list[[8]] <- NormalizeData(Hepatocytes.list[[8]],verbose = FALSE)
>   Hepatocytes.list[[9]] <- NormalizeData(Hepatocytes.list[[9]],verbose = FALSE)
>   Hepatocytes.list[[10]] <- NormalizeData(Hepatocytes.list[[10]],verbose = FALSE)
> Hepatocytes.list[[1]] <- FindVariableFeatures(Hepatocytes.list[[1]], selection.metho                                                                                                                          = "vst",nfeatures = 2000, verbose = FALSE)
> Hepatocytes.list[[2]] <- FindVariableFeatures(Hepatocytes.list[[2]], selection.metho                                                                                                                         Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  invalid 'x'
> Hepatocytes.list[[2]] <- FindVariableFeatures(Hepatocytes.list[[2]], selection.metho                                                                                                                         Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  invalid 'x'
> Hepatocytes.list[[3]] <- FindVariableFeatures(Hepatocytes.list[[3]], selection.metho                                                                                                                         Warning messages:es = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -0.86326
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.00032968
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -0.86326
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.018157
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.031008
> Hepatocytes.list[[4]] <- FindVariableFeatures(Hepatocytes.list[[4]], selection.metho                                                                                                                         Warning messages:es = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -1.867
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.32289
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  0
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
> Hepatocytes.list[[5]] <- FindVariableFeatures(Hepatocytes.list[[5]], selection.metho                                                                                                                         > = "vst",nfeatures = 2000, verbose = FALSE)
>
> Hepatocytes.list[[6]] <- FindVariableFeatures(Hepatocytes.list[[6]], selection.metho                                                                                                                         Warning messages:es = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -0.71423
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.00023274
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -0.71423
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.015256
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
> Hepatocytes.list[[7]] <- FindVariableFeatures(Hepatocytes.list[[7]], selection.metho                                                                                                                         Warning messages:es = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -0.79307
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.00022269
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -0.79307
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.014923
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
> Hepatocytes.list[[8]] <- FindVariableFeatures(Hepatocytes.list[[8]], selection.metho                                                                                                                         Warning messages:es = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -1.0608
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.00037768
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -1.0608
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.019434
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
> Hepatocytes.list[[9]] <- FindVariableFeatures(Hepatocytes.list[[9]], selection.metho                                                                                                                         Warning messages:es = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -1.0974
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.00033014
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -1.0974
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.01817
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
> Hepatocytes.list[[10]] <- FindVariableFeatures(Hepatocytes.list[[10]], selection.met                                                                                                                         Warning messages:ures = 2000, verbose = FALSE)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -2.108
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.3227
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1.0296e-27
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.090619
>
> Hepatocytes.list
$HCC08P
An object of class Seurat
23831 features across 776 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC08N
An object of class Seurat
23831 features across 1 samples within 1 assay
Active assay: RNA (23831 features, 0 variable features)

$HCC05N
An object of class Seurat
23831 features across 7 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC04N
An object of class Seurat
23831 features across 70 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC03N
An object of class Seurat
23831 features across 281 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC09N
An object of class Seurat
23831 features across 5 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC10N
An object of class Seurat
23831 features across 6 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC07P
An object of class Seurat
23831 features across 11 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC07N
An object of class Seurat
23831 features across 12 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)

$HCC06N
An object of class Seurat
23831 features across 122 samples within 1 assay
Active assay: RNA (23831 features, 2000 variable features)
