### ISSUE TITLE
FindAllMarkers added suffices to gene names!

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#4075]
There seems to be a problem about the data.frame output from FindAllMarkers()
Some genes occur more than once because it is a marker in more than one cell types. And these genes' names were made unique to become row.names. 

Is there a way to save gene names in a column instead of in a data.frame format?

![image](https://user-images.githubusercontent.com/4110443/107821797-f9d43500-6d74-11eb-82ea-936482bec047.png)

**Comment by saketkc** [comment]
`FindAllMarkers` does return gene name in a new column. Please see a related issue and response [here](https://github.com/satijalab/seurat/issues/4025#issuecomment-774187399).
