### ISSUE TITLE
VlnPlot vs PercentageFeatureSet expression level

### ISSUE THREAD

**Issue by Jeff87075** [satijalab/seurat#4078]
Hi I'm trying to set a hard threshold to define cells as either high or low expression and was wondering is the expression level shown in VlnPlot() the same as the number obtained from PercentageFeatureSet() in the meta data? I tried plotting the values in the meta data by conventional ggplot and compared it with the violin plot and it looks to be the same, but would appreciate more clarification on what exactly is the difference in the values obtained from the different functions, thanks!

**Comment by Jeff87075** [comment]
I also found out that the output for violin plot seems to change after I run PercentageFeatureSet(), this is the code I used:
```
VlnPlot(df, "MS4A1")
df[["MS4A1"]] = PercentageFeatureSet(try, "MS4A1")
VlnPlot(df, "MS4A1")
```
And the output for before is:
![image](https://user-images.githubusercontent.com/78546899/107854652-51979c80-6e58-11eb-978d-2534bff12c15.png)
And after running PercentageFeatureSet() is: 
![image](https://user-images.githubusercontent.com/78546899/107854655-55c3ba00-6e58-11eb-9eb3-779ffb3dba97.png)
Is there some sort of change in the data used to do the violin plot if I run certain functions to the seurat object?

**Comment by andrewwbutler** [comment]
Hi, 

What's happening here is that when you run

```R
object[["MS4A1"]] = PercentageFeatureSet(object, "MS4A1")
```

It stores a new column in meta.data called `MS4A1` with the results of `PercentageFeatureSet`. Then when you run `VlnPlot`, it has to decide whether you want to plot the gene expression values or the meta.data field and the precedent for an "unkeyed" value like this is to first look in meta.data. Generally, to avoid confusion, I'd recommend not having a meta.data field with the same name as an Assay feature but if there is an overlap, to retrieve a plot with expression data you can append the `Assay` key. For example:
```R
VlnPlot(object, "rna_MS4A1")
```
