### ISSUE TITLE
FindMarkers error when using features

### ISSUE THREAD

**Issue by jelicana** [satijalab/seurat#4079]
![genes](https://user-images.githubusercontent.com/60859104/107854080-90413e80-6de7-11eb-8aef-2eb359a0b451.jpg)
Hello!

I have 3 groups (ba, be, ec) with 1 sample in each. Assuming there is no batch, I have just merged them together and did analysis like in this tutorial https://satijalab.org/seurat/articles/pbmc3k_tutorial.html.

Now, I'm trying to run FindMarkers between two samples (be and ec) but only on selected list of genes that I have imported as csv file. List contains 938 genes. 

I keep getting this error: **Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid or not-yet-implemented 'Matrix' subsetting**

Below is the code that I used

```
library(Seurat)
celldata_ba <- Read10X(data.dir = "/Volumes/data/outs/outs_ba/filtered_feature_bc_matrix/")
celldata_be <- Read10X(data.dir = "/Volumes/data/outs/outs_be/filtered_feature_bc_matrix/")
celldata_ec <- Read10X(data.dir = "/Volumes/data/outs/outs_ec/filtered_feature_bc_matrix/")

ba <- CreateSeuratObject(counts = celldata_ba, project = "ba", min.cells = 3, min.features = 200)
be <- CreateSeuratObject(counts = celldata_be, project = "be", min.cells = 3, min.features = 200)
ec <- CreateSeuratObject(counts = celldata_ec, project = "ec", min.cells = 3, min.features = 200)

#merged seurat object
oneobject <- merge(ba, y = c(be, ec), add.cell.ids = c("ba", "be", "ec"), project = "CA")

oneobject[["percent.mt"]] <- PercentageFeatureSet(oneobject, pattern = "^MT-")
oneobject <- subset(oneobject, subset = nFeature_RNA > 200 & nFeature_RNA < 4000 & percent.mt < 1.5)
oneobject <- NormalizeData(oneobject, normalization.method = "LogNormalize", scale.factor = 10000)
oneobject <- FindVariableFeatures(oneobject, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(oneobject)
oneobject <- ScaleData(oneobject, features = all.genes)
oneobject <- RunPCA(oneobject, features = VariableFeatures(object = oneobject))
oneobject <- FindNeighbors(oneobject, dims = 1:10)
oneobject <- FindClusters(oneobject, resolution = 0.5)

#differentially expressed genes

Idents(oneobject) <- "orig.ident"
DefaultAssay(oneobject)  <- "RNA"
DEG <- FindMarkers(oneobject, ident.1 = "be", ident.2 = "ec", verbose = FALSE,
                   min.pct = 0.25, logfc.threshold = 0.25, features = genes)
```

**Comment by jaisonj708** [comment]
To diagnose the issue you should:
-insure 'be' and 'ec' are both in the Idents of your object
-decrease min.pct and logfc.threshold in case these thresholds are filtering out all of your specified genes
-insure `genes` is a vector and not some other object

**Comment by jelicana** [comment]
@jaisonj708  thanks for replying! Nothing from above solved the error. Now, when `genes` is a vector I get this error: **Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid character indexing**
 
What I have noticed is that only some genes from the `genes` list give me this error. For example, I have tried to run the code with the first 10 genes from the list and it worked, and when I extended list to the first 20 it gave me error again. I went checking gene by gene, and found out that gene X at place 17 was the issue. When I removed it, it worked again. 
But I cannot go gene by gene and figure out which ones give me this error for the whole list of several hundred genes.

**Comment by chenxy19** [comment]
> @jaisonj708 thanks for replying! Nothing from above solved the error. Now, when `genes` is a vector I get this error: **Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid character indexing**
> 
> What I have noticed is that only some genes from the `genes` list give me this error. For example, I have tried to run the code with the first 10 genes from the list and it worked, and when I extended list to the first 20 it gave me error again. I went checking gene by gene, and found out that gene X at place 17 was the issue. When I removed it, it worked again.
> But I cannot go gene by gene and figure out which ones give me this error for the whole list of several hundred genes.

maybe you can try `features=intersect(rownames(SeuratObject), YourGeneList)`. Mine worked this way.
