### ISSUE TITLE
Reference based Integration

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#4080]
Hi,

I have 12 Samples I would like to integrate. However, I can only go up to 10 without error due to the size of the datasets and have to resort to reference based integration. 

My question is, I can do integration with up to 10 out of 14 as reference datasets and only 4 as query sets. Would having 10 as reference and 4 as query be 'better' than 4 as reference and 10 as query? If I understand correctly, the more references you have, more comparisons are made, right? So having more number of reference datasets should help better integration (assuming variation among the datasets)?

Thanks and Kind regards,
Saeed

**Comment by satijalab** [comment]
In general, its helpful to have more references - if you have the computational power to include more, I do suggest you try to.

However, we've had great results integrating dozens of datasets even if just a few are specified as the reference. In general, its helpful if the datasets you specify as references comprise the full set cell states that are present in all datasets (admittedly, you may not know this at the onset).
