### ISSUE TITLE
SCT assay 

### ISSUE THREAD

**Issue by liron27** [satijalab/seurat#4081]
Hi,

I am running integration of multiple datasets using the SCT transform on each. I have the following questions:

1. In order to perform differential expression analysis, should I use DefaultAssay(object) <-"RNA" or DefaultAssay(object) <-"SCT" prior to FindMarkers(object)?

2. Same as question 1, but with AddModuleScore. What assay should be the default prior to using this function?

3. I would like to use the batched-corrected integrated expression matrix for other downstream analyses. Should I be using object@assays$RNA@data or object@assays$SCT@data?

Thanks!!

**Comment by saketkc** [comment]
> In order to perform differential expression analysis, should I use DefaultAssay(object) <-"RNA" or DefaultAssay(object) <-"SCT" prior to FindMarkers(object)?

We [recommend](https://github.com/satijalab/seurat/discussions/4032) that you use the RNA assay for differential analysis. 

> Same as question 1, but with AddModuleScore. What assay should be the default prior to using this function?

You can use either here.

> I would like to use the batched-corrected integrated expression matrix for other downstream analyses. Should I be using object@assays$RNA@data or object@assays$SCT@data?

The batch corrected data is in the `integrated` assay. The answer to this depends on the context. If you are doing DE, we recommend that it be done on the raw counts and not the integrated assay.

**Comment by liron27** [comment]
Thank you! Just to clarify - you recommend differential gene expression on
the RAW count (object@assay$RNA@counts) and not on the normalized one
(object@assay$RNA@data)? Usually DE is performed on some normalized version.

Thanks

**Comment by saketkc** [comment]
The slot depends on the exact test you are using. `DESeq2` for example will use the `counts` slot.
See [documentaion](https://rdrr.io/cran/Seurat/man/FindMarkers.html) for other examples.

**Comment by liron27** [comment]
Thank you! I would like to perform DE between datasets while taking into
account batch effect. That’s why I’m first integrating the data to minimize
the batch effect and after that perform DE. If I am using the raw counts or
any other normalized version that doesn’t take into account the batch
effect, then what is the purpose of performing the integration prior if I
am any way using the original uncorrected data?

**Comment by saketkc** [comment]
The aim of integration here would be to define the common celltypes across your batches (after you perform clustering on the integrated data). Next, you will use the RNA assay to perform differential expression analysis between these clusters (celltypes). For example, you can use logistic regression here with batch added as an additional covariate (latent variable): `FindMarkers(test.use="LR", and latent.vars="batch")`

**Comment by liron27** [comment]
Thanks so much!

Liron

**Comment by qoiopipq** [comment]
@saketkc 

I'm having the same problem. Integration works, great clustering results. When I tried to do DE using RNA assay by setting FindMarkers(test.use="LR", latent.vars="batch"), those highly DEGs (with >2FC) are still separated because of batch effect.

@liron27  Does it work for you?
