### ISSUE TITLE
Identification of cell types

### ISSUE THREAD

**Issue by nii825** [satijalab/seurat#4083]
I loaded my 10x dataset in the form of barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz. There are 2 datatypes for gene expression and antibody capture. I have formed clusters based on the barcode and also the tags. I further want to see the cells types among the clusters but there is no details of the various cell types.

The tutorial with 10X genomics data manually annotated the clusters with cell types but i want to generate mine directly from the data. How do I go about it?

**Comment by timoast** [comment]
I'm not sure what you mean exactly by "generate mine directly from the data," but there are a few different ways of annotating cell types in a single-cell dataset. One is a supervised analysis, which you mentioned, where you assign clusters to cell types based on prior knowledge of marker genes. Another is to transfer cell type annotations from a pre-annotated reference dataset. We demonstrate both methods in vignettes on the Seurat website.
