### ISSUE TITLE
Error in FindMarkers using MAST

### ISSUE THREAD

**Issue by liron27** [satijalab/seurat#4084]
Hi, 

I am running the following code:

de <- FindMarkers(object, ident.1 = "one", ident.2 = "two", verbose = FALSE, test.use = "MAST", latent.vars = "model")

and getting the following error:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': (subscript) logical subscript too long

Interestingly using the same command with different test there is no error. 

de <- FindMarkers(object, ident.1 = "one", ident.2 = "two", verbose = FALSE, test.use = "negbinom", latent.vars = "model")

Any suggestions?

**Comment by jaisonj708** [comment]
What kind of variable is `model` (continuous or discrete)? If discrete, #3884 may be of help?
