### ISSUE TITLE
Integration with SCTransform

### ISSUE THREAD

**Issue by aide-mm** [satijalab/seurat#4085]
Hello,

Thank you all for the very useful vignettes. I am working with time course data of the same tissue and using the same technology. One sample was done at a separate time and sequenced deeper than the rest so there seems to be a batch effect. To correct for this I have tried a few things with Seurat v 4.0.0:

1. I merged all samples and did SCT on the merged data: screg<- SCTransform(screg, vars.to.regress = "nCount_RNA", verbose = FALSE, return.only.var.genes = FALSE). I used return.only.var.genes = FALSE because I was losing key developmental genes when I did the SCT normalization. The PCA showed one sample away from the rest even after normalization.
2. I tried doing a normal integration and used features.to.integrate to use all genes: screg1.combined <-  IntegrateData(anchorset = screg1.anchors, features.to.integrate = all_features). The PCA looks much better here but once sample is still clustering away from the rest, so I wanted to try integration with SCTransform to make sure the variance I am seeing is real
3. I am having a similar issue to #2590. When I do the integration I am losing important genes even if I use all_features in IntegrateData. This was my code:

screg2.list <- SplitObject(screg2, split.by = "time")
screg2.list <- lapply(X = screg2.list, FUN = function(x) {
  x <- SCTransform(x, return.only.var.genes = FALSE)
})
features <- SelectIntegrationFeatures(object.list = screg2.list, nfeatures = 3000)
screg2.list <- PrepSCTIntegration(object.list = screg2.list, anchor.features = features)
screg2.list <- lapply(X = screg2.list, FUN = RunPCA, features = features)
screg2.anchors <- FindIntegrationAnchors(object.list = screg2.list,normalization.method = "SCT", dims = 1:30,
                                         anchor.features = features, reduction = "rpca")
all_features <- rownames(x = screg2[["RNA"]]@counts)
screg2.combined <-  IntegrateData(anchorset = screg2.anchors, normalization.method = "SCT", features.to.integrate = all_features)

> nrow(screg2.combined[["integrated"]]@scale.data)
[1] 3640
> length(all_features)
[1] 36059

Thanks!

**Comment by yuhanH** [comment]
HI, 
I cannot reproduce this error.  Could you have a try on the `ifnb` example? 

```
LoadData("ifnb")

ifnb.list <- SplitObject(ifnb, split.by = "stim")
ifnb.list <- lapply(X = ifnb.list, FUN = SCTransform, method = "glmGamPoi")
features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
ifnb.list <- lapply(X = ifnb.list, FUN = RunPCA, features = features)


immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT", 
                                         anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 20)
all.feature <- rownames(ifnb[["RNA"]]@counts)
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT", dims = 1:30, features.to.integrate = all.feature)
nrow(immune.combined.sct[["integrated"]]@scale.data)
```

> nrow(immune.combined.sct[["integrated"]]@scale.data)
[1] 12099

**Comment by jperera1** [comment]
@yuhanH, I was encountering similar problems with Integration in my own analysis and I tried your sample code and the R session aborted once more. Do you have any thoughts about what the issue might be? 

Here's the link to my Issue page:

**Comment by duocang** [comment]
> HI,
> I cannot reproduce this error. Could you have a try on the `ifnb` example?
> 
> ```
> LoadData("ifnb")
> 
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
> ifnb.list <- lapply(X = ifnb.list, FUN = SCTransform, method = "glmGamPoi")
> features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
> ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
> ifnb.list <- lapply(X = ifnb.list, FUN = RunPCA, features = features)
> 
> 
> immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT", 
>                                          anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 20)
> all.feature <- rownames(ifnb[["RNA"]]@counts)
> immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT", dims = 1:30, features.to.integrate = all.feature)
> nrow(immune.combined.sct[["integrated"]]@scale.data)
> ```
> 
> > nrow(immune.combined.sct[["integrated"]]@scale.data)
> > [1] 12099

Hi @yuhanH 
you used `SCTransform` in ` ifnb.list <- lapply(X = ifnb.list, FUN = SCTransform, method = "glmGamPoi")`. In the official tutorial: [Introduction to scRNA-seq integration](https://satijalab.org/seurat/articles/integration_introduction.html), `Noramlized` was used.

I have followed the code with `NormalizData` and `SCTransform` respectively. Different results but both look OK for me.


How do I select?

**Comment by yuhanH** [comment]
Hi @duocang 
The SCT integrated result doesn't look right. Could you post the scripts you used for SCT integration?
Thanks.

**Comment by duocang** [comment]
@yuhanH 

```r
```{r fig.width=10, fig.height=4}
# load dataset
LoadData("ifnb")

# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(ifnb, split.by = "stim")

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- SCTransform(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = ifnb.list)

immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)
# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)

# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- SCTransform(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)
# Visualization
p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
DimPlot(immune.combined, reduction = "umap", split.by = "stim")

DefaultAssay(immune.combined) <- "RNA"
nk.markers <- FindConservedMarkers(immune.combined, ident.1 = 6, grouping.var = "stim", verbose = FALSE)
head(nk.markers)
```
```

**Comment by yuhanH** [comment]
Hi, @duocang 
I notice that some of the above steps are not accurate....

1. SCT will find variable genes after calculating residuals. You should not run FindVariableFeatures after SCTransform. 
```
# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    x <- SCTransform(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
```

2. You need to set the normalization method in both `FindIntegrationAnchors` and `IntegrateData` functions. 
```
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)
# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)
```

3. After you run integration, you don't need to re-run SCTransform. 
```
DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- SCTransform(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
```
I would suggest you follow the code in our [integration vignette]( https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1).  SCT-normalized integration is in the second section.

**Comment by duocang** [comment]
@yuhanH 

ah, I see. I missed the second part of the vignette. Thanks for pointing it out.

I have searched for one `subset` answer for a while. Maybe you can help me by your thought：Should I run `SCTransform` againi when subsetting an integrated by SCT-normalized integration.

For example
```r
LoadData("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")
ifnb.list <- lapply(X = ifnb.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT",
    anchor.features = features)
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")

# subsetting happens here for sepcific cells
cell.target <- c(...)
seu.ONE <- subset(immune.combined.sct, cells= cells.target)
```
Should I run `SCTransform` on `seu.ONE`?

**Comment by AndreaYCT** [comment]
Hi, @yuhanH 

I am running Integration using SCT as well. 
I have two questions:
(1) Should I run RunPCA, RunUMAP, FindNeighbors, and FindClusters on Integrated data?
(2) Should I run SCT after remove some cluster from Integrated data?

**Comment by Blackerrrrr** [comment]
I want to know how the SplitObject() split the object? base on what?

Fot this example :  ifnb.list <- SplitObject(ifnb, split.by = "stim")

I just don't know if I use other samples, how can I split them by stim or time for example.
