### ISSUE TITLE
Annotation options for multimodal ATAC+GEX analysis

### ISSUE THREAD

**Issue by sylestiel** [satijalab/seurat#4086]
Is it okay to use GeneActivity() function to Identify Anchors and then proceed to label transfer for multiomic assay?

For one, Azimuth has just 1 dataset  and the Reference Mapping vignette seems to require the availability of a reference dataset to run against our query dataset.

**Comment by timoast** [comment]
If you have multiome data where you measured DNA accessibility and gene expression in the same cell, there's no need to compute gene activities using the DNA accessibility data (since you've measured the actual gene expression)
