### ISSUE TITLE
FindMarkers: LogFC threshold question

### ISSUE THREAD

**Issue by crowngillian** [satijalab/seurat#4088]
Hello Seurat team,

I'm using the "FindMarkers" function to calculate out the DEGs between two group of cells. The command line I wrote is : 

DEGs <- FindMarkers(obj, ident.1 = "ident1", ident.2 = "ident2", logfc.threshold = 0.25, verbose = FALSE). 

Here I understand the default "logfc.threshold" for calculation is 0.25. I'd like to adjust it based on the nature of our experiments. But in the generated dataframe, I found a column named "Log2FC" instead of "LogFC". I'd like to clarify that if the argument "logfc.threshold" actually refers to "Log2FC" rather than "LogFC", which make quite a difference when detering the threshold based on the FC values in our experiments. 

Thanks,
G.W.

**Comment by jaisonj708** [comment]
Yes, `logfc.threshold` thresholds exactly the values you see in the `FindMarkers` logfc output column, so by default this is a threshold on base 2 log fold-change
