### ISSUE TITLE
re-clustering

### ISSUE THREAD

**Issue by kathush** [satijalab/seurat#409]
Hello Seurat community,

Does anyone have experience with re-clustering clusters from Seurat objects? 
I am planning to subset cells expressing a certain genes using `SubsetData`.  What would be the required steps before running another round of `FindClusters` and `RunTSNE`?

Thank you for any advise!

**Comment by leonfodoulian** [comment]
Hi @kathush,

I am sorry for the notice, but I don't see how the title of the issue and the raised issue are connected? 

Best,
Leon

**Comment by kathush** [comment]
Sorry, just noticed it too..

**Comment by leonfodoulian** [comment]
Regarding your question, simply pass the cluster ID of the cells you'd like to re-cluster to the `ident.use` argument of `Seurat:: SubsetData()`, and create a new object with that. Then, you have to re-compute variable genes, scale the data, reduce the dimension and run clustering (pretty much exactly as what you did during the initial step). Once you get your clusters, you can then re-set the identity of the cells from each of the sub-clusters using the `Seurat::SetIdent()` function.

Hope that helps!

Best,
Leon

**Comment by kathush** [comment]
Helps a lot! Thanks so much! Will give it a go, looks straight forward! 

Best,
Kathy

**Comment by brianpenghe** [comment]
I don't quite agree with recalculating variable genes. Because in that way you already change the clustering criteria, don't you?
