### ISSUE TITLE
understand AverageExpression in detail

### ISSUE THREAD

**Issue by WendyZhangYing** [satijalab/seurat#4090]
I am trying to understand how AverageExpression function is applied.

For instance, from: AverageExpression vs FindMarkers: difference in the avg_logFC #2423
to get mean gene expression of all cells in a cluster (assuming : active ident is "seurat_cluster", group.by = "ident" )
the code is like:

avg.CD14.mono <- log1p(AverageExpression(CD14.mono, verbose = FALSE)$RNA)

If AverageExpression is log (average (exponentiated $data )), then why use log1p after the AverageExpression?
Thanks very much

**Comment by satijalab** [comment]
Average expression does not return logged data (we say in the documentation that averaging is done in non-logged space)
