### ISSUE TITLE
Seurat v4 Reference Mapping - Possible to keep original DR from SingleCellExperiment without model from Seurat?

### ISSUE THREAD

**Issue by jonasns** [satijalab/seurat#4091]
Hi there,

I have been trying to use your reference mapping for an experiment originally analyzed using the SingleCellExperiment (sce) class. I start by transferring my sce to Seurat:

```
sce_reference.seurat <- as.Seurat(sce_reference, counts = "counts", data = "exprs")
```

This works well, and I can plot my previous UMAP with Seurat:

```
DimPlot(sce_reference.seurat, reduction = "UMAP", group.by = "sample_id")
```

Below two code chunks works to map my sce_test to the sce_ref, but I do not get the sce_test onto the sce_ref UMAP:

```
anchors <- FindTransferAnchors(
  reference = sce_reference.seurat,
  query = sce_testRef.seurat,
  normalization.method = "LogNormalize",
  reference.reduction = NULL,
  features = rownames(sce_reference),
  npcs = 10,
  dims = 1:10,
  recompute.residuals = FALSE, #https://github.com/satijalab/seurat/issues/3989
  approx=FALSE, #https://github.com/satijalab/seurat/issues/1963
  k.filter=NA #https://github.com/satijalab/seurat/issues/1889
)
```

```
sce_testRef.seurat_transf <- MapQuery(
  anchorset = anchors,
  query = sce_testRef.seurat,
  reference = sce_reference.seurat,
  refdata = list(
    celltype.l1 = "cluster_id",
    celltype.l2 = "xshift"
  ),
  new.reduction.name = "ref.umap"
)
```

When adding:
reduction.model = "UMAP" 
to the MapQuery code I get the error:
"Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first"
which previously has been resolved here: https://github.com/satijalab/seurat/issues/3615 by saying that I need to add 
return.model=TRUE
to my code when running DR in Seurat. But since my DR comes from the SingleCellExperiment I am not able to do this. 

I know it's maybe a long shot, but do you have any suggestions on how I can keep my original DR without having to re-DR in Seurat?

Kind regards,
Jonas

**Comment by yuhanH** [comment]
Hi, 
the problem is that your `UMAP` reduction doesn't have umap model there, so it cannot be used for projection. 
If you know the initial parameters for umap, you can create a umap model. You can follow this issue https://github.com/satijalab/seurat/issues/3864

**Comment by singlece** [comment]
Hello. I used the same codes as you mentioned in #3864 to create UMAP.new. However, I got the problems below and I don't know what it means. Could you give me some hints? Thanks! 

Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
  |                                                  | 0 % ~calculating  
Integrating dataset 2 with reference dataset
Finding integration vectors
Integrating data
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04s  
Error in if (n.cells < k.param) { : argument is of length zero
