### ISSUE TITLE
Selecting "beginning" of the biological process???

### ISSUE THREAD

**Issue by sikh09** [satijalab/seurat#4092]
Hi
I am trying to apply monocle3 to my single-cell data (without time series). So, I have a problem deciding the beginning of the
biological process. I have "sox2" high expressing cells (High sox2 population) and sox2 low expressing cells (Low sox2 population) and 2 populations of "prl". Our hypothesis is that sox2 are the stem cells and they are differentiating into prolactin populations.
If I use "Sox2" as a starting point of trajectory I got pseudotime from low expressing sox2 popultaion (See figure).
[starting_point.pdf](https://github.com/satijalab/seurat/files/5995357/starting_point.pdf)

What is the appropriate way to find the beginning of the trajectory? should I use "sox2" high expressing cells as beigbing of my biological process?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but this seems like a question about monocle/trajectory inference and not Seurat really.  I think you might have better luck getting answer from the Monocle Devs with this question [https://github.com/cole-trapnell-lab/monocle3](https://github.com/cole-trapnell-lab/monocle3) or Monocle documentation/tutorial [https://cole-trapnell-lab.github.io/monocle3/](https://cole-trapnell-lab.github.io/monocle3/).  Could also try Bioinformatics forum (Biostars) or Seurat Discussions [https://github.com/satijalab/seurat/discussions](https://github.com/satijalab/seurat/discussions).  

Personally though I think this is extremely tricky and there's isn't necessarily a single answer for non-time series based experiments or without some a priori knowledge of the biological system/differentiation process.  As you said you have some hypothesis so you could see how that looks but as far as I'm aware there is not a metric that necessarily states how accurate a starting point is in pseudotime.  You may want to check out RNA Velocity based methods (velocyto, scVelo) that do not have same requirement to set a starting point (but have additional caveats themselves as with any technique).

Best,
Sam
