### ISSUE TITLE
rPCA vs CCA

### ISSUE THREAD

**Issue by lizhaozhi** [satijalab/seurat#4093]
Hi, 

I have not find any answer here. I have seen people use CCA integration or rPCA integration. Which one should I choose?

I read this from Stuart*, Butler*, et al., Cell 2019 [Seurat V3]
![image](https://user-images.githubusercontent.com/46610946/108227537-fd1c4780-710b-11eb-9cd7-1a23d0184bcf.png)

Thank you

**Comment by timoast** [comment]
The screenshot you've attached answers this question
