### ISSUE TITLE
Read10X to read files that are not named as barcodes.tsv, features.tsv, matrix.mtx

### ISSUE THREAD

**Issue by luenhchang** [satijalab/seurat#4096]
Hi,
I have seen most examples that use `Read10X(dir.data=folder_path)` where the folder_path contains three files barcodes.tsv, features.tsv, matrix.mtx

But my downloaded files are like
GSM4138110_HNSCC_1_PBMC_barcodes.tsv 
GSM4138110_HNSCC_1_PBMC_genes.tsv    
GSM4138110_HNSCC_1_PBMC_matrix.mtx

Is there any possibility to read these files as their original names?

I can certainly change the file names to barcodes.tsv, features.tsv, matrix.mtx but this is not a good programming practice.

Thanks

**Comment by samuel-marsh** [comment]
Hi,

I just submitted PR to Seurat team to add functionality to `Read10X` #4101.  You can check out the code and run function yourself if you want to try in meantime or can wait for response from Seurat Team as they may alter my PR as needed.

Best,
Sam

**Comment by luenhchang** [comment]
Thanks Sam

**Comment by samuel-marsh** [comment]
Happy to help!

**Comment by satijalab** [comment]
Thanks @samuel-marsh . we'll look at the PR and appreciate the effort as this is a feature i've wanted myself

**Comment by saketkc** [comment]
Hi @luenhchang and @samuel-marsh, thanks for your patience. We now have a function `ReadMtx` in the [develop](https://satijalab.org/seurat/articles/install.html)  branch that allows reading any 10X-like files. Some examples are below. Hopefully this addresses your problem. We are thinking about more generic ways to load GEO files into Seurat easily and might have more automated support for it in the future. 

Example1: [GEO link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132044)

```r
mtx <- "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE132044&format=file&file=GSE132044%5Fmixture%5Fhg19%5Fmm10%5Fcount%5Fmatrix%2Emtx%2Egz"
cells <- "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE132044&format=file&file=GSE132044%5Fmixture%5Fhg19%5Fmm10%5Fcell%2Etsv%2Egz" 
features <- "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE132044&format=file&file=GSE132044%5Fmixture%5Fhg19%5Fmm10%5Fgene%2Etsv%2Egz"

counts <- ReadMtx(mtx = mtx, cells = cells, features = features, feature.column = 1)
```

Example2: [GEO link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126836)
```r
mtx <- "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE126nnn/GSE126836/suppl/GSE126836_SN_MD5828_matrix.mtx.gz"
features <- "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE126nnn/GSE126836/suppl/GSE126836_SN_MD5828_genes.csv.gz"
cells <- "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE126nnn/GSE126836/suppl/GSE126836_SN_MD5828_barcodes.csv.gz"
counts1 <- ReadMtx(mtx = mtx, cells = cells, features = features, 
                   feature.column = 1, skip.cell = 1, skip.feature = 1)

```
Example 3: Local

```r
mtx <- "~/data/pbmc10k/filtered_feature_bc_matrix/matrix.mtx.gz"
cells <- "~/data/pbmc10k/filtered_feature_bc_matrix/barcodes.tsv.gz"
features <- "~/data/pbmc10k/filtered_feature_bc_matrix/features.tsv.gz"
counts <- ReadMtx(mtx = mtx, cells = cells, features = features)
```
