### ISSUE TITLE
Suggestion: support for summing multiple genes in FeaturePlot

### ISSUE THREAD

**Issue by rcw1** [satijalab/seurat#41]
First off, thanks for making such a great package for single cell analysis!

For the FeaturePlot function, it would be useful to collapse all of the individual tSNE plots for each gene into one 'master' tSNE plot in which the cell color was determined by the sum of expression of the individual genes. 

This would be especially nice for users with multiple sources of single cell data (i.e. Fluidigm, 10X, other Dropseq methods) that may not cluster on the same plot due to technical issues, and would allow modules/clusters from one dataset to be more easily related to another dataset. 

Thanks for considering!

**Comment by andrewwbutler** [comment]
While not quite what you're describing, we do have some new options for visualizations that you can checkout [here](http://satijalab.org/seurat/visualization_vignette.html)

**Comment by rcw1** [comment]
Fantastic, thanks - very excited about v2.0
Rob
