### ISSUE TITLE
Changing the color of the outlier dots in a violin plot?

### ISSUE THREAD

**Issue by pjlmac** [satijalab/seurat#4104]
Hi, I'm trying to change the color of my outlier dots in a Violin plot that I'm working on. In using a dataset that I'm putting together, I use the following code (note, I've removed a few pieces of my output)...

`VlnPlot(MyDataSet, assay="RNA", features="GeneOfInterest", split.by = "ConditionalVariable", cols = c("red","blue"))`

And I get this...
![image](https://user-images.githubusercontent.com/11742340/108425714-d4c64300-7208-11eb-8758-fcd9498dce0d.png)

I would like the dots that overlap with the red violins to be red, and the dots that overlap with the blue violins to be blue. Any help would be greatly appreciated! Thanks!

**Comment by andrewwbutler** [comment]
HI,

Unfortunately, that functionality is not supported in `VlnPlot`. You can kind of roughly piece it together with a couple extra lines.

```R
p + geom_jitter(mapping = aes(color = split), data = p$data, position = position_jitterdodge(jitter.width = 0.4, dodge.width = 0.9))
```
