### ISSUE TITLE
 MapQuery errors  when Seurat V3 objects used in V4 reference mapping

### ISSUE THREAD

**Issue by Winnie09** [satijalab/seurat#4106]
Hi,

Thanks for developing seurat v4. It is a really helpful tool. I have two Seruat v3 objects obj1 and obj2 both have dimension-reduction slots pca, harmony, and umap. They are both integrative objects of several samples. I would like to apply seurat v4  forMultimodal reference mapping. FindTransferAnchors() gave outputs successfully, but  MapQuery() returned errors.  Changing "pca" to "umap" or "harmony" did not work. Could you suggest a way to solve this? Thank you!

Here is my code:
```
library(Seurat)
library(ggplot2)
library(patchwork)
library(here)
setwd(here())
obj1 <- readRDS('obj1.rds')
obj2 <- readRDS('obj2.rds')

obj1$RNA@var.features <- rownames(obj1$RNA@scale.data)
obj2$RNA@var.features <- rownames(obj2$RNA@scale.data)

anchors <- FindTransferAnchors(
   reference = obj1,
   query = obj2,
   normalization.method = "LogNormalize",
   reference.reduction = "pca",
   dims = 1:30
 )

ct = readRDS('ct.rds')

res <- MapQuery(
  anchorset = anchors,
  query = obj2,
  reference = obj1,
  refdata = ct,
  reference.reduction = "pca", 
  reduction.model = "umap"
)
```

Errors:

> Projecting cell embeddings
> Finding neighborhoods
> Finding anchors
> 	Found 8914 anchors
> Filtering anchors
> 	Retained 565 anchors
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Predicting cell labels
> Integrating dataset 2 with reference dataset
> Finding integration vectors
> Integrating data
> 
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Predicting cell labels
> Integrating dataset 2 with reference dataset
> Finding integration vectors
> Integrating data
> Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from ref.pca_ to refpca_
> Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from ref.pca_ to refpca_
> Warning: All keys should be one or more alphanumeric characters followed by an underscore '_', setting key to refpca_
> Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first
> Execution halted

**Comment by timoast** [comment]
Your UMAP does not have the model stored, so you can't project new data onto that UMAP. You'll need to compute a new reference UMAP setting `return.model=TRUE` in `RunUMAP()`

**Comment by Yale73** [comment]
@timoast Hi Tim, I used the method you described and made the plot, but I found the ID label is messy (right part), especially cluster 36. Can you help me solve it? 

(The left plot is the reference while the right part is the data to match)

![image](https://user-images.githubusercontent.com/50378244/116954784-c30c0d80-ac45-11eb-94e7-38c454f7e4df.png)

Thanks,
Yale

**Comment by JeremyCCChen** [comment]
Here is the the arguments of **umap.method** in RunUMAP (Seurat 5.2)

> umap.method:
> 
> uwot:
> Runs umap via the uwot R package
> 
> uwot-learn:
> Runs umap via the uwot R package and return the learned umap model
> 
> umap-learn:
> Run the Seurat wrapper of the python umap-learn package


The solution to this issue is to set: 
`umap.method = ‘uwot-learn’`
However, it returns:

> Warning message:
> In RunUMAP.default(object = data.use, reduction.model = reduction.model,  :
>   'uwot-learn' is deprecated. Set umap.method = 'uwot' and return.model = TRUE

Therefore, setting **return.model = TRUE** is perfectly fine (umap.method = 'uwot' is default) as Timoast commented above.


Here is my workflow and it works perfectly.

> obj_ref <- RunUMAP(obj_ref, dims = 1:30, reduction = "integrated.scvi",return.model=T, umap.method = 'uwot')
> obj_query <- RunUMAP(obj_query, dims = 1:30, reduction = "integrated.scvi",return.model=T, umap.method = 'uwot')
> obj.anchors  <- FindTransferAnchors(reference = obj_ref, query = obj_query, dims = 1:50,
>                                     reference.reduction = "pca",project.query = T)
> obj_query<- MapQuery(anchorset = obj.anchors, reference = obj_ref, query = obj_query,
>                      refdata = list(celltype = "celltype"), reference.reduction = "pca", reduction.model = "umap")
> p1 <- DimPlot(obj_ref, reduction = "umap", group.by = "celltype", label = TRUE, label.size = 3,
>               repel = TRUE) + NoLegend() + ggtitle("Reference annotations")
> p2 <- DimPlot(obj_query, reduction = "ref.umap", group.by = "predicted.celltype", label = TRUE,
>               label.size = 3, repel = TRUE) + NoLegend() + ggtitle("Query transferred labels")
> p1 + p2
