### ISSUE TITLE
FindTransferAnchors error in SCT assay

### ISSUE THREAD

**Issue by l-magnificence** [satijalab/seurat#4109]
query object is a SCT integrated data in seurat version 3.2.0
reference object is a SCT normalized data in seurat version 3.2.0
When I use FindTransferAnchors function in seurat version 3.9.9, it report error: Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame
Due to different version of seurat, I apply UpdateSCTAssays function to old version seurat object, but it dosen't work

```
DefaultAssay(query)<-"SCT"
DefaultAssay(reference )<-"SCT"
reference <- RunUMAP(reference , reduction = "pca", dims = 1:15, 
                                  n.neighbors = 30L, n.components = 2L,
                                  min.dist = 0.5, spread = 1, assay = "SCT",
                                  return.model = T)
anchors <- FindTransferAnchors(
                                  reference = reference ,
                                 query = query,
                                 normalization.method = "SCT",
                                 reference.reduction = "pca",
                                 dims = 1:10
)
```
Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame

```
query<- UpdateSeuratObject(query)
query<- UpdateSCTAssays(query)
```
Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame

How to solve it?
Thanks!

**Comment by yuhanH** [comment]
HI, 
Not sure why `UpdateSCTAssays` fails.  
Would you mind to send your query object to me?  My email is yhao@nygenome.org

**Comment by l-magnificence** [comment]
I rerun the SCTransform and integration of query object in seurat version 4.0.0, then do the FindTransferAnchors function between query and  reference, it works well.
I think the function UpdateSCTAssays may do error in a SCTransform integrated datatsets from old version seurat.

**Comment by yuhanH** [comment]
Right.  It seems that your stored SCT model is not compatible with `UpdateSCTAssays`.
It will be appreciated if you could send just your old stored SCT model to me `object[["SCT"]]@misc`, and we can have a chance to figure out why `UpdateSCTAssays` failed. Thanks.

**Comment by l-magnificence** [comment]
I have send  the old stored SCT model to your email. Hoping it can be helpful for you
code:
DefaultAssay(query )<-"SCT"
tmp<-query[["SCT"]]@misc
saveRDS(tmp,file = "~/tmp.rds")

**Comment by yuhanH** [comment]
Thanks. I think the models can be converted to SCT model class. 
For your old object, you can try to use `UpdateSeuratObject` and then use `UpdateSCTAssays`

**Comment by DKaukonen** [comment]
Hi,

No I do not set any var.to.regress

In both datasets, there are multiple samples (for i in 1:10). The basic framework after creating the Seurat object was as follows.

```
reference_data <- SCTransform(reference_data, verbose = FALSE)
assign(paste0("sample.",i,".data"), reference_data)
```

Then I integrate all of the samples as follows.

```
options(future.globals.maxSize=30000*1024^2, future.seed =TRUE) #Increase memory allowance

reference.features <- SelectIntegrationFeatures(object.list = lapply(ls(pattern = "sample"),get), nfeatures = 2000)
reference.list <- PrepSCTIntegration(object.list = lapply(ls(pattern = "sample"),get), anchor.features = reference.features, verbose = FALSE)

reference.anchors <- FindIntegrationAnchors(object.list = reference.list, normalization.method = "SCT", anchor.features = reference.features, verbose = FALSE, dims =1:30)
reference.combined <- IntegrateData(anchorset = reference.anchors, normalization.method = "SCT",verbose = FALSE, dims = 1:30) 
```

After the PCA and uMAP, determining clusters and identifying cluster markers (following the standard workflow) it is:

```
DefaultAssay(reference.combined) <- "SCT" # 'Integrated' does not work
reference.combined <- UpdateSeuratObject(reference.combined)
```

Which yields

> Validating object structure
> Updating object slots
> Ensuring keys are in the proper strucutre
> Ensuring feature names don't have underscores or pipes
> Object representation is consistent with the most current Seurat version

`UpdateSCTAssays(reference.combined)`

> Error in as.data.frame.default(x) : 
>   cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame

Same error for` anchors <- FindTransferAnchors(reference = reference.combined, query = experiment.combined , normalization.method = "SCT")`

In case you need it
sessionInfo()

> R version 4.0.5 (2021-03-31)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.2 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fi_FI.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=fi_FI.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=fi_FI.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=fi_FI.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] ggtree_2.4.1       future_1.21.0      clustree_0.4.3     ggraph_2.0.5       ggplot2_3.3.2      dplyr_1.0.5        cowplot_1.1.1      Matrix_1.3-2       SeuratObject_4.0.0 Seurat_4.0.1      
> 
> loaded via a namespace (and not attached):
>   [1] Rtsne_0.15            colorspace_2.0-0      deldir_0.2-10         ellipsis_0.3.1        ggridges_0.5.3        aplot_0.0.6           spatstat.data_2.1-0   leiden_0.3.7          listenv_0.8.0         farver_2.1.0          graphlayouts_0.7.1    ggrepel_0.9.1         fansi_0.4.2          
>  [14] codetools_0.2-18      splines_4.0.5         polyclip_1.10-0       jsonlite_1.7.2        ica_1.0-2             cluster_2.1.1         png_0.1-7             uwot_0.1.10.9000      ggforce_0.3.3         shiny_1.6.0           sctransform_0.3.2     spatstat.sparse_2.0-0 BiocManager_1.30.12  
>  [27] compiler_4.0.5        httr_1.4.2            rvcheck_0.1.8         assertthat_0.2.1      fastmap_1.1.0         lazyeval_0.2.2        later_1.1.0.1         tweenr_1.0.2          htmltools_0.5.1.1     tools_4.0.5           igraph_1.2.6          gtable_0.3.0          glue_1.4.2           
>  [40] RANN_2.6.1            reshape2_1.4.4        Rcpp_1.0.6            scattermore_0.7       vctrs_0.3.7           ape_5.4-1             nlme_3.1-152          lmtest_0.9-38         stringr_1.4.0         globals_0.14.0        mime_0.10             miniUI_0.1.1.1        lifecycle_1.0.0      
>  [53] irlba_2.3.3           goftest_1.2-2         MASS_7.3-53.1         zoo_1.8-9             scales_1.1.1          tidygraph_1.2.0       spatstat.core_2.0-0   promises_1.2.0.1      spatstat.utils_2.1-0  parallel_4.0.5        RColorBrewer_1.1-2    reticulate_1.18       pbapply_1.4-3        
>  [66] gridExtra_2.3         rpart_4.1-15          stringi_1.5.3         tidytree_0.3.3        rlang_0.4.10          pkgconfig_2.0.3       matrixStats_0.58.0    lattice_0.20-41       ROCR_1.0-11           purrr_0.3.4           tensor_1.5            treeio_1.14.3         patchwork_1.1.1      
>  [79] htmlwidgets_1.5.3     tidyselect_1.1.0      parallelly_1.24.0     RcppAnnoy_0.0.18      plyr_1.8.6            magrittr_2.0.1        R6_2.5.0              generics_0.1.0        DBI_1.1.1             pillar_1.5.1          withr_2.4.1           mgcv_1.8-34           fitdistrplus_1.1-3   
>  [92] survival_3.2-10       abind_1.4-5           tibble_3.1.0          future.apply_1.7.0    crayon_1.4.1          KernSmooth_2.23-18    utf8_1.2.1            spatstat.geom_2.0-1   plotly_4.9.3          viridis_0.5.1         grid_4.0.5            data.table_1.14.0     digest_0.6.27        
> [105] xtable_1.8-4          tidyr_1.1.3           httpuv_1.5.5          munsell_0.5.0         viridisLite_0.3.0

**Comment by yuhanH** [comment]
Hi, @DKaukonen 
Not sure where the bug is. 
Would you mind to send your reference object, `reference.combined`, to me? My email is yhao@nygenome.org. Thanks

**Comment by DKaukonen** [comment]
Hi,

The object is over 15GB in size. At the moment I have no reliable method to transfer it. Are there any other options?

-Damien

**Comment by DKaukonen** [comment]
Hi,

It goes down to 9.8 GB (from 16.7GB). There are 3 assays: RNA, SCT, and Integrated. 9 ncRNA-seq samples
