### ISSUE TITLE
Is it possible to use different filtering cutoff for two different identity classes?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#411]
For my data it looks like I have to use different filtering cut-off for each identity class. Is it possible to do that?
![image](https://user-images.githubusercontent.com/27332974/38676454-bd6a0704-3e63-11e8-86b1-931984fc869d.png)

**Comment by leonfodoulian** [comment]
Hi @bishwaG,

One way of doing this would be to split your Seurat object into two objects by identity using `Seurat::SubsetData`, perform your filtering, and then merge the two objects again using `Seurat::MergeSeurat`.

Best,
Leon

**Comment by bishwaG** [comment]
Hi @leonfodoulian 
Thanks! It worked like a charm.
