### ISSUE TITLE
Why MT genes still appear in top PCs after percent.mt were already regressed?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4110]
Hi there, 

Related to #3926 and #3945, I thought if I regressed out the percent.mt variable, then wouldn't the mitochondrial gene "heterogeneity [would] not contribute to PCA or downstream analysis" as stated in the tutorial (even though the tutorial is for cell cycle genes)? 

I know the regression does not remove the genes, but I should not see them on my top PCs because these PCs will be used for clustering.

Would anyone help me understand why I still found a good number of MT genes making up the top PCs after I runPCA()? 

Thank you so much for your help!

**Comment by satijalab** [comment]
Regressing mitochondrial gene content should mitigate the contribution of MT-heterogeneity to downstream analysis, but we unfortunately cannot guarantee that it will remove it entirely.

Just to confirm that you are indeed performing regression, you should see that MT-genes appear on a lower PC after regression than before. 

If you also have a subset of cells with extremely high MT percentages (that should really be filtered out by QC), you can remove these cells in an upstream QC step, which can also mitigate this.
