### ISSUE TITLE
Applying FDR procedure to DEGs e.g. Benjamini-Liu, Query number of comparisons?

### ISSUE THREAD

**Issue by SimoCR** [satijalab/seurat#4112]
Hi, 

I am currently trying to apply an FDR procedure to the DEGs I have obtained using MAST manually (I understand alternatives to the Bonferroni correction are not supported). To do this I need to understand/know the number of comparisons made?

The data I am using is an integration of a specific sub population (endothelial cells) from multiple datasets. I have not integrated all of the original datasets together as the file would be too big for me to work with.

In my DEGs list obtained from this subset dataset if I calculate the number of comparisons used in the Bonferroni correction (applied by default) that was implemented in Seurat by dividing the Bonferonni corrected P values by the original uncorrected P value that suggests that the correction was for 51,300 comparisons.

If I query the dataset I am using it returns the following:

Active assay: RNA (51300 features...)

My queries are the following:

**1. Is the 51300 features number preserved from the original integrated datasets? i.e.  is it a combination of all the detected features from all the original rds files? Could the number in my subset data rds be much lower than this number?** 

**2. Can the number of comparisons be determined in my specific dataset? Obviously it makes a big difference when applying Benjamini-Liu manually?** 

Is it likely that in the subset data that the true number of detected features in these cells is lower and therefore for applying a Benjamini-Liu approach the number of comparisons is less than this 51300. Hence, how do I find this out?

I have run FindMarkers with all defaults off e.g. logFC.threshold = 0, min.pct= 0 etc. and my list of genes on the same dataset is ~20K. So not 51300. (I can appreciate that FindMarkers is not designed to detect all genes so recognize this method is not likely to be accurate).

I hope the above is clear enough for someone to understand and would appreciate anyones insight on this. 

Thanks, 

Simon

**Comment by satijalab** [comment]
Thanks for the question, I think I do understand.

In our opinion, the number of comparisons represents the number of features that could be DE across the dataset. I think its reasonable for this to be the total number of features that have non-zero values in the data. If a feature is measured in one dataset, but totally missing in another, I would expect that you would call this a DE gene. 

I believe the 51,300 number would represent the full set of genes that were detected across all datasets, and this would a conservative but reasonable number to adopt
