### ISSUE TITLE
HTO Count Matrix Creation in Seurat

### ISSUE THREAD

**Issue by fouerghi** [satijalab/seurat#4116]
Is it possible to create a HTO count matrix in Seurat? I have my filtered feature matrix file (containing the features, barcodes and the matrix files) and I have a list of the seven hashtags I have used. You recommended using CITE-seq-Count in the pipeline, but it has some bugs due to the new version. I was hoping there would be a way to get the HTO count matrix just using Seurat and using the 10x filtered feature matrix and the list of hashtags I have.

**Comment by timoast** [comment]
No, the filtered feature barcode matrix does not contain the hashing counts and Seurat does not do any quantification. There are several other tools that you could use for this, for example: Cellranger, Alevin, or Kallisto
