### ISSUE TITLE
Attempting to create .csv file for genes to determine cell types using xcell

### ISSUE THREAD

**Issue by pvimal** [satijalab/seurat#412]
I have tried to create a .csv file using the following code: write.csv(seuratobj.data1@dr$tsne@cell.embeddings, file = paste("tSNECoordinates",sep = "_", collapse = NULL))
which I can then put into the xcell program (http://xcell.ucsf.edu/) to determine the cell types of my clusters. Is there any method or alternate to xcell to do this besides attempting to decode the gene heat maps/expression for each cluster?

Thanks in advance!

**Comment by satijalab** [comment]
You can view the documentation and vignettes on the website (for example, the visualization vignette) to learn more about plotting heatmaps, finding DE genes, etc.
