### ISSUE TITLE
Does setting a higher FindClusters() resolution simply divide a big cluster into smaller clusters?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4120]
Hi there, 

From running the data with different resolutions and various discussions, e.g., #476, it seems that setting a higher resolution will give more clusters. And, from the discussion of Blondel at al in orange3 forum (https://github.com/biolab/orange3/issues/3184), "increasing the parameter value will produce a larger number of smaller, more well-defined clusters" 

Would anyone mind confirming that increasing the resolution argument will only divide up a big cluster into smaller clusters, hence having more clusters, and not something fancier than that? 

Because when I color the cells from 2 small clusters (with higher resolution) that appear to be split from a big cluster (with lower resolution), this seems true; however, the sum of cells from these 2 small clusters do not equal the number of cells of the big cluster. 

Thank you for your help!

**Comment by torkencz** [comment]
Hi,

Unfortunately, if I understand FindClusters correctly the answer is not as deterministic. A lot of these community finding algorithms are randomly seeded and some of the cells you are trying to cluster might be noisy, therefore hard to cluster. While these algorithms will find sub structures within your original data with high accuracy, I would not expect the cells to add up perfectly. If you took the original cluster and then subclustered would be a different case. I hope this helps and if anyone else wants to add info feel free to comment.

**Comment by timoast** [comment]
Just want to add that the graph-based clustering methods will be deterministic if using the same seed, which is done by default in Seurat. The resolution parameter is part of the modularity cost function used, and so it does _not_ correspond to simply dividing larger clusters into smaller ones. See this [paper](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.74.016110) for more information about the cost function and the resolution parameter (gamma in the equation in the paper), and the section "Multiresolution methods" on the modularity [wiki page](https://en.wikipedia.org/wiki/Modularity_(networks))

**Comment by DiracZhu1998** [comment]
Hi there,
The parameters setting is “reasonable” but arbitrary in scRNA-seq workflow.
Top PCs capture the dominant factors of heterogeneity in the data set, in other words, the biological process and attribute in an orchestrated manner. By comparison, random technical or biological noise is expected to affect each gene independently. This motivates the use of the earlier PCs in our downstream analyses, which concentrates the biological signal to reduce computational work and remove noise simultaneously.
To evaluate how many HVGs, dimensions, and resolutions we choose nfeature range from 2k to 6k, PCA dim 10 to 60, resolution from 0.2 to 1.2, select favored dim used in FindNeighbors and RunUAMP/RunTSNE, and check:
1). PCA elbow, PCA dim heatmap, cell inheritance robustness (by R library clustree)
2). UMAP plot showing batch effect, cell quality effect
3). Whether Clustering cell ratio similar between replicates
4). Reclustering projection ratio (e.g., u r interested in glia, subset them and re-integrate, plot original clustering annotation projected to reclustered cluster ratio)
5). Top markers of each cluster expression heatmap are distinct or not.
6). If u r working with model organism, u may evaluate clustering quality by doing correlation between bulk RNA-seq of each cell type and plot to see if there is correlation gap which can reflect clustering purity.
