### ISSUE TITLE
Error with updating Seurat object from v1.X to version 2.X

### ISSUE THREAD

**Issue by achowdary1** [satijalab/seurat#4123]
I'm trying to analyze a Seurat object that was created in 2019. I have the RDS file stored and attempted to update it while on the latest Seurat version (v4). 

```
sets <- readRDS("~/Desktop/macrophages/project/data.rds")
sets.new <- UpdateSeuratObject(sets)
Error: We are unable to convert Seurat objects less than version 2.X to version 3.X
Please use devtools::install_version to install Seurat v2.3.4 and update your object to a 2.X object
```
I was able to downgrade to Seurat v2.3.4 and attempted to rerun similar code to update my Seurat object. I received another error.  

```
packageVersion("Seurat")
[1] ‘2.3.4’
sets <- readRDS("~/Desktop/macrophages/project/data.rds")
sets.new <- UpdateSeuratObject(sets)
Error in initialize(value, ...) : 
  trying to get slot "raw.data" from an object of a basic class ("list") with no slots
```
I checked on here but was not able to find anyone with this specific error while trying to update Seurat objects. Here's what my old Seurat object looks like in R. I'm thinking it has something to do with the raw data not being in the correct format? I also wasn't able to access any of the elements from the RDS file. Any help would be greatly appreciated!

 ![image](https://user-images.githubusercontent.com/75513073/108654518-7611fb00-748e-11eb-9e39-c22a2d921616.png)

**Comment by andrewwbutler** [comment]
Hi,

Are you trying to update multiple Seurat objects at once here? It looks like `sets.old` is a list of 3 Seurat objects? If that's the case, can you try updating each one separately?

**Comment by achowdary1** [comment]
Hi Andrew –

Thanks for your response. How would I go about doing that? I tried and still got the same error. How would I go about splitting up the Seurat object?

`data.v1 <- UpdateSeuratObject(data[0])`

**Comment by andrewwbutler** [comment]
Hi,

To subset a specific list element, try using the double bracket (instead of single) operator. E.g

```R
set1 <- UpdateSeuratObject(sets[[1]])
```
