### ISSUE TITLE
DimPlot cannot color correctly

### ISSUE THREAD

**Issue by liuweihanty** [satijalab/seurat#4124]
Hi there, I was trying to use Dimplot to do a simple visualization of my data. The identity I used is a column called "label_coarse" stored in metadata, and is of data type "chr", I used the code below

Idents(seu.integrated) <- "label_coarse"
DimPlot(seu.integrated, group.by = "label_coarse",reduction = "umap"),

and the following error pops up:
Error: Must request at least one colour from a hue palette.

do you know how to resolve this? Thank you very much in advance!

**Comment by jaisonj708** [comment]
Please check to make sure all items in `label_coarse` have a value

**Comment by CarlottaHS** [comment]
Hi! I also run into the same error.

I am setting the Idents back to the originally created `seurat_cluster` column:
`Idents(combined) <- "seurat_clusters"`
`DimPlot(object = combined, reduction = "umap")`
Resulting in: `ERROR while rich displaying an object: Error: Must request at least one colour from a hue palette.`

I checked my meta.data columns or NA or empty entries:
`allmisscols <- sapply(combined@meta.data, function(x) all(is.na(x) | x == '' ))`
`allmisscols`
Resulting in:
`orig.ident
    0
nCount_RNA
    0
nFeature_RNA
    0
sampleName
    0
percent.mt
    0
RQ_GEX
    0
area
    0
disease
    0
vaccine
    0
RNA_snn_res.0.8
    0
seurat_clusters
    0
sub.cluster
    0
cell_type
    0
total_count
    0
count_cell_type
    0
frequency_cell_type
    0
subject
    0 `

So as far as I am aware my meta.data has no missing value.

Do you know how to resolve this? 
Thanks already in advance!

**Comment by KinSimon96** [comment]
Hey,

Facing the same problem, but only violin plots. Did someone find the way to fix it ?

Thanks,
Simon

**Comment by CarlottaHS** [comment]
I solved the error in the same way as @ncalistri did. 
Now I make sure to keep the row names in the object, when I manipulate the metadata. One has to be especially careful when using functions from the tidyverse suite as that then typically happens.
