### ISSUE TITLE
DEG analysis between datasets? 

### ISSUE THREAD

**Issue by Seandelao** [satijalab/seurat#4127]
Hello, I have a very naive/simple question. 

I have two datasets (Seurat objects) that I want to do differential gene expression on based on the dataset (i.e. in vitro derived cell type A vs. in vivo derived cell type A). My current workflow is to take both objects, extract raw counts and create two Seurat objects that I then merge into one, then do standard workflow (normalization, PCA, etc.), this way the normalization and everything is happening on the counts from each dataset together. 

I am then mapping back cluster information from the original two objects into a metadata column in the new object, and then doing differential gene expression analysis as such: 
Markers = FindMarkers(merged, ident.1 = InVitro_Epithelial, ident.2 = InVivo_Epithelial). 

I was wondering if this type of analysis is appropriate? I could batch correct them together, but since DEG analysis after batch correction is still performed on the RNA assay and I am not interested in performing DEG analysis across the merged clusters, it seems to me that batch correction would not be needed? Would batch effects seriously hamper my DEG analysis regardless? 

Thanks so much!

**Comment by softmiaa** [comment]
Could I perform the DEG analysis on the integrated assay? Thanks!

**Comment by timoast** [comment]
@Seandelao Sure, that sounds reasonable. However, rather than extracting the counts from each object, combining them, and making a new object, you could just merge the different Seurat objects using the `merge()` function. 

@softmiaa Do not use the integrated assay for DEG analysis

**Comment by softmiaa** [comment]
@timoast Thank you so much! However , I don't known why we can't use integrated assay to do this analsis? I saw that there was still difference in the gene expression level between  two clusters from these sample.

**Comment by softmiaa** [comment]
@timoast Thank you so much! However , I don't known why we can't use integrated assay to do this analsis? I saw that there was still difference in the gene expression level between  two clusters from these samples.
