### ISSUE TITLE
Data integration on two harmony corrected assays?

### ISSUE THREAD

**Issue by qrzhang** [satijalab/seurat#4129]
Hi Seurat group,

Thanks for developing such a powerful and user-friendly tool. 

See the attached figure. I have one sc-RNAseq data and one scATAC-seq data. Both of them have a strong batch effect. So, I have applied the function `Runharmony` to both assays and got the corrected harmony embeddings. Harmony works pretty well. And then, I integrated the scRNA-seq data and scATAC_seq gene activity data into one by using the following codes. However, I noticed that the `data` slots are used to do the integration instead of the corrected harmony embeddings, and the strong batch effect showed again in the integrated data. 

So, I'm wondering what's the best strategy to integrate two Harmony corrected assays instead of the original `data` slots?

Will appreciate any help :)

```r
transfer.anchors <- FindTransferAnchors(
     reference = data.rna, 
     query = data.atac, 
     features = VariableFeatures(object = data.rna), 
     reference.assay = "RNA", 
     query.assay = "ACTIVITY", 
     reduction = "cca")

genes.use <- VariableFeatures(data.rna)
refdata <- GetAssayData(data.rna, assay = "RNA", slot = "data")[genes.use, ]

imputation <- TransferData(
    anchorset = transfer.anchors,
    refdata = refdata, 
    weight.reduction = data.atac[["harmony"]], 
    dims = 1:30)

data.atac[["RNA"]] <- imputation

coembed <- merge(x = data.rna, y = data.atac)
``` 

![image](https://user-images.githubusercontent.com/19705471/108779696-4407a400-7535-11eb-9680-4a10a721e8e8.png)

**Comment by timoast** [comment]
There's no way to use the harmony-corrected low-dimensional coordinate to do multimodal integration between scRNA-seq and scATAC-seq, other than using the harmony-corrected coordinates to define anchor weights (which you do here). To find anchors between RNA and ATAC, we run CCA on the gene activity (ATAC) and gene expression (RNA) matrices, which identifies shared sources of variation between the two experiments.

If you have multiple scATAC and scRNA-seq datasets that you want to integrate, I'd suggest following the [vignette](https://satijalab.org/seurat/articles/atacseq_integration_vignette.html) on the Seurat website, and when you get to the step "[coembedding scRNA/scATAC](https://satijalab.org/seurat/articles/atacseq_integration_vignette.html#co-embedding-scrna-seq-and-scatac-seq-datasets-1)", run Harmony on the PCA that contains both the RNA and ATAC cells.

**Comment by Li-ZhiD** [comment]
I have several snRNA-seq from multiple donors (batch), snRNA_dat. I downloaded harmony integrated scRNA-seq as reference, scRNA_dat, and I want to transfer labels to snRNA_dat by using FindTransferAnchors and TransferData. 
I want to know how to do it? need set 'weight.reduction = snRNA_dat[["harmony"]]'? or should I transfer labels one by one?
