### ISSUE TITLE
Re-normalize, scale and regress RNA Assay counts to visualize gene expression in SCTransform workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4130]
Follow up on #4082, I understand we need to normalize the counts of the RNA Assay for visualization (especially when there are differences in sequencing depth between samples). 

But, would anyone mind helping me understand the confusion below? Thank you very much for your advice!

**1. If I have been following the SCTransform() workflow, should I NormalizeData() and ScaleData() and regressing out variables (percent.mt, cell cycle genes) again on my Seurat object before any plotting, in addition to setting assay="RNA"?**

**2. If I just want to show which clusters have a gene being more highly expressed in DotPlot, which of the following plots I should show?**

Option 1. Performed SCTransform(), DotPlot(setting assay = "SCT"):
![image](https://user-images.githubusercontent.com/62179082/108794295-69b89b80-757d-11eb-8eb2-bf7f18eb0a36.png)

Option 2. Performed SCTransform(), did not do NormalizeData(setting assay = "RNA"), did not ScaleData(assay = "RNA"), just did DotPlot(setting assay = "RNA")
![image](https://user-images.githubusercontent.com/62179082/108794524-bd2ae980-757d-11eb-99b2-7cf04db3a406.png)

Option 3. Performed SCTransform(), then NormalizeData(setting assay = "RNA"), did not ScaleData(assay = "RNA"), then DotPlot(setting assay = "RNA")
<img width="233" alt="Screen Shot 2021-02-23 at 2 21 56 AM" src="https://user-images.githubusercontent.com/62179082/108794620-e8153d80-757d-11eb-805c-eb0d26e52db0.png">

**3. When I checked my RNA counts and data slot (shown below), how do we know when the counts slot have been normalized?**

I am confused because looking at the images below (RNA and SCT Assays):

- For RNA Assay, the counts and data (which is supposed to be log-normalized) are the same 
- For SCTAssay, the counts and data are also the same, and are the same to those in RNA Assay (even though I did perform SCTransform())

<img width="554" alt="Screen Shot 2021-02-23 at 2 00 54 AM" src="https://user-images.githubusercontent.com/62179082/108793236-f7df5280-757a-11eb-8683-2c8e08bfed6e.png">

<img width="910" alt="Screen Shot 2021-02-23 at 2 01 41 AM" src="https://user-images.githubusercontent.com/62179082/108793280-147b8a80-757b-11eb-9115-70b659846a97.png">

**Comment by jaisonj708** [comment]
We recommend your option 3 plot for visualization. ScaleData should not change the output of DotPlot. The equality of the counts and data slots in your SCTassay can be resolved by changing the `do.correct.umi` parameter.
