### ISSUE TITLE
Estimate memory needed to merge Seurat objects

### ISSUE THREAD

**Issue by luenhchang** [satijalab/seurat#4132]
Hi,
An Error: cannot allocate vector of size 8.5 Gb occurred when I tried to merge two Seurat objects using

```
# Merge all Seurat objects as a single Seurat object
memory.size() ### Checking your memory size
# 8385.05 MB
memory.limit() ## Checking the set limit
#[1] 16165
memory.limit(size=56000) ### expanding your memory _ here it goes beyond to your actually memory. This 56000 is proposed for 64Bit.

dim(GSM4138162_HD_1_PBMC)
#[1] 33694  2445
dim(GSM4138168_HD_1_Tonsil)
#[1] 33694  3325
dim(GSM4138163_HD_2_PBMC)
#[1] 33694  2436

seurat.merged <- merge(x= GSM4138162_HD_1_PBMC, y=c(GSM4138168_HD_1_Tonsil)
                       ,add.cell.ids=c("HD_1_PBMC","HD_1_Tonsil"))
```
From the other posts, this error is due to insufficient memory.

I am wondering if there is a possibility to estimate the memory needed to run the `merge` function based on the size of input files (i.e., barcodes.tsv, genes.tsv, matrix.mtx) or the dimension of individual Seurat objects? 

Thanks!
Chang

**Comment by timoast** [comment]
It might be possible to estimate the object size based on the size of the input files, but I don't think this is a high priority for us right now.
