### ISSUE TITLE
Error when merging subsets (from an integrated seurat object)

### ISSUE THREAD

**Issue by VolSapiens** [satijalab/seurat#4133]
Hi Seurat Team,

I have a quick question hope you can help. I created an integrated Seurat object (Vehicle and Treat) following your SCTransform workflow under the Integration and Label Transfer section on your website. I would like to create two subsets from the integrated Seurat object based on certain gene expressions (high, low). I want to use the integrated object as a parent object because I don't want to lose cell identities (cluster names). Briefly, I try to see DEGs between high and low expression states within Vehicle, Treat, and both conditions. Please see the error showing up when I merge subsets.

```
sample.integrated <- readRDS("~/Desktop/Seurat_Combined.rds")

new.cluster.ids <- c("I", "S","RC","DC","CS","KO","CS","H","uC","RC","MC","MC","DC","H")
names(new.cluster.ids) <- levels(sample.integrated)
sample.integrated <- RenameIdents(sample.integrated, `0` = "I", `1` = "S", `2` = "RC", 
                                  `3` = "DC", `4` = "CS", `5` = "KO", `6` = "CS", `7` = "H", 
                                  `8` = "uC", `9` = "RC", `10` = "MC", `11` = "MC", 
                                  `12` = "DC", `13` = "H")

DefaultAssay(sample.integrated) <- "RNA"
sample.integrated <- NormalizeData(sample.integrated, verbose = FALSE)

summary(FetchData(object = sample.integrated, vars = "Nasp"))
summary(FetchData(object = sample.integrated, vars = "Tomm5"))

NT_High <- subset(sample.integrated, subset = Nasp > 1.6 & Tomm5 > 0.5)   
NT_Low <- subset(sample.integrated, subset = Nasp < 0.83 & Tomm5 < 0.3)

NT.integrated <- merge(x = NT_High, y = NT_Low, add.cell.ids = c("High", "Low"), project = "MyProject")

   Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

``` 
If I were able to create a merged object (such as NT.integrated), I was going to run this kind of function:

`DEG1 <- FindMarkers(NT.integrated, ident.1 = "NT_High", ident.2 = "NT_Low", assay = "RNA", logfc.threshold = 0.25, test.use = "MAST", only.pos = F)`

Additionally, I also tried to rename clusters in both subsets by giving a prefix assuming I can get rid of the error, and also can make further comparisons within or among samples, but it failed again.

```
High.ids <- c("I", "S", "RC", "DC", "CS", "KO", "uC", "MC", "H")
newHigh.ids <- c("I_High", "S_High", "RC_High", "DC_High", "CS_High", "KO_High", "uC_High", "MC_High", "H_High")
names(newHigh.ids) <- levels(NT_High)
NT_High <- RenameIdents(NT_High, newHigh.ids)
levels(NT_High)

Low.ids <- c("I", "S", "RC", "DC", "CS", "KO", "uC", "MC", "H")
newLow.ids <- c("I_Low", "S_Low", "RC_Low", "DC_Low", "CS_Low", "KO_Low", "uC_Low", "MC_Low", "H_Low")
names(newLow.ids) <- levels(NT_Low)
NT_Low <- RenameIdents(NT_Low, newLow.ids)
levels(NT_Low)

NT.integrated <- merge(x = NT_High, y = NT_Low, add.cell.ids = c("High", "Low"), project = "MyProject")

   Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

```
Any thoughts or suggestions would be appreciated.
Thanks

**Comment by torkencz** [comment]
Hi, you need to make sure the matrix rownames are unique in your Seurat objects that you are trying to merge. You can do this with the make.unique function. Let me know if this helps. If not I may need a little more info to help you about the objects you are trying to merge.
