### ISSUE TITLE
Installation on old version of R

### ISSUE THREAD

**Issue by LMayhew** [satijalab/seurat#4134]
I am using:
R version 3.6.2 (2019-12-12)
It cant be helped, IT controls what version we are using.
When I try to install.packages('seurat') I get the error:

package ‘seurat’ is not available (for R version 3.6.2)

I can try to install an archived version, and have tried several.  Which archived version will work with R 3.6.2?
Thanks!

**Comment by timoast** [comment]
The package name should be "Seurat" not "seurat"

Seurat v3.2.3 was the last release that supported R >=3.6.0, you can download the source from the CRAN archive:

```r
devtools::install_version(package = 'Seurat', version = package_version('3.2.3'))
```
