### ISSUE TITLE
 CellSelector not selecting cells

### ISSUE THREAD

**Issue by justin-malin** [satijalab/seurat#4135]
Hello, 

I have used CellSelector successfully in the past (Seurat v2 and possible v3 ), but in recent months ( v3, v4), I'm unable to get it to capture the cells I'm selecting with the mouse. Not sure if it's related,  but the interactive behavior of CellSelector when I run it has changed. 

On Rstudio (Mac), when I ran CellSelector successfully in the past,  the plot would appear in the "Plots" window, which I would then interact with. Now, when I run CellSelector, it opens instead in "Viewer."

For example:

![image](https://user-images.githubusercontent.com/47457105/108909463-95299d80-75f2-11eb-8116-b4feaea7b5ef.png)

If I use my mouse to select a group of cells from this image and click "Done", the image in "Viewer" disappears and appears in "Plots." However, the vector where the cell barcodes should be saved is empty:

![image](https://user-images.githubusercontent.com/47457105/108909735-e89beb80-75f2-11eb-991c-cad78a525fd1.png)

I have tried re-installing Seurat, R and Rstudio but the behavior hasn't changed. I'd appreciate any suggestions on how to get this to work.

Thanks,
Justin

**Comment by mojaveazure** [comment]
The new `CellSelector` is supposed to show up in the viewer pane; we made this change to use Shiny as the backend for `CellSelector` as the previous package we used as orphaned and archived. For the Shiny implementation, are you clicking points or clicking and dragging a box to select cells?

**Comment by justin-malin** [comment]
Yes, I was clicking. I see dragging a box works. Thanks!
Is there any way to get an arbitrary non-rectangular shape?

**Comment by mojaveazure** [comment]
At the moment, no. We are looking into ways to add support for non-rectangular selection, similar to how `CellBrowser` used to work, but don't have any updates on that at the moment.
