### ISSUE TITLE
Removing mitochondria-enriched clusters

### ISSUE THREAD

**Issue by TiongSun** [satijalab/seurat#4138]
Hi all,

After clustering with high resolution, I found a small cluster that cannot be annotated. After running FindAllMarkers function, I found that the cluster enriched in only mitochondrial genes (only mitochondrial genes have very low p-values). I highly suspect that the cluster contains only dead cells. Although I use percent.mt < 25 filter in the previous step (according to a paper), it might not filter out all dead cells. I am trying to avoid filtering out too many cells if I set percent.mt filter too low. 

My question is, at this stage, is it scientifically acceptable or a common practice to manually remove the cluster that I highly suspect consisting of only dead cells? 

Thank you for any advice.

Best wishes,
TS

**Comment by jaisonj708** [comment]
Removing cells is a common practice in QC so it should be fine as long as you note this. You can also keep the cluster and label with 'dead', 'mito-enriched' or similar.
