### ISSUE TITLE
Individual replicate gene expression values using `AverageExpression` function

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#4139]
I have performed single-cell experiment containing 3 Ctrl and 3 treatment (T) samples and I used Seurat integration vignette for comparing Ctrl and T conditions. I use `AverageExpression` function to get the expression values of genes in Ctrl and T samples in various clusters. However `AverageExpression` displays the combined expression values of all Ctrl and T samples for each cluster.

 I want to determine the individual expression values of genes separately for each samples of Ctrl and T (from integrated Seurat object). I am wondering how can I get individual expression values

Something like this:

**Cluster 1**
-----------Ctrl1--------- Ctrl2---------Ctrl3-------T1----------T2----------T3
GAPDH----10------------15 ----------13--------- 5-------------17------------9
ACTB------10------------15 ----------13--------- 5-------------17------------9

**Cluster 2**
-----------Ctrl1--------- Ctrl2---------Ctrl3-------T1----------T2----------T3
GAPDH----10------------15 ----------13--------- 5-------------17------------9
ACTB------10------------15 ----------13--------- 5-------------17------------9

Is it possible to get this info from integrated data?

Thank you

**Comment by timoast** [comment]
`AverageExpression()` will compute the average expression in groups of cells defined by whichever grouping variable you request (by default the active cell identities ("Idents")). To compute averages among different groups, change the `group.by` parameter to a grouping variable in the metadata that groups the cells in the way you want. For example, you can combine the ctrl and treatment information with the sample information to create a new grouping variable:

```r
object$treatment_sample <- paste(object$treatment, object$sample, sep = "_")
avg <- AverageExpression(object, group.by = "treatment_sample")
```
