### ISSUE TITLE
FeatureHeatmap Data to Use

### ISSUE THREAD

**Issue by xhbkirby** [satijalab/seurat#414]
Hi,

I understand that in the "FeatureHeatmap" function Seurat uses the scaled data to draw the plot. My first question is that if I include some regression when performing "ScaleData", "FeatureHeatmap" will take the regressed and scaled data, correct? My other question is whether there's a way to ask the "FeatureHeatmap" to use the normalized rather than the scaled data to draw the plot? Thanks!

Haibin

**Comment by satijalab** [comment]
Hi - right now there is not a way to do this, but we agree that FeatureHeatmap needs to be rewritten with more flexibility. Will occur in a future release.
