### ISSUE TITLE
Integration of multiple seurat objects / FindIntegrationAnchor error 

### ISSUE THREAD

**Issue by jurtlest** [satijalab/seurat#4143]
Hello All, 

I've browsed multiple Seurat vignettes as well as github posts about integration. However I still lack a full and clear understanding of the absolute process of integration of multiple sequencing samples of different condition. (Could also be due to there isn't a best practice for such application)

I'm hoping that some of you can share your insights in approaching such issue.

Currently I have 8 DGE matrix (from dropseq) of wild type mouse scSeq data and 5 10x human scSeq data( 4 control vs 1 stim). I've successfully compared analysis between the 5 human samples, however I'm looking to integrate all of the human data together with the mice sc data so that I can cross identify the cell types in the human samples as there's more documentation and study done in mice.

My question is from a computational standpoint how should this be handled ?? 
1. integrate all mouse data and human data separately into integrated_mice and integrated_human. Then integrate those two seurat objects again ?? 
2. integrate all mouse and human data into an seurat object all together ? 

My code for approach 1 is as below:

## Make Seurat object of human and mice scSeq data from 10x and dge matrix. Then Run SCT on Each Sample and save. 
oe_files <- list.files("/scSeq_mice", full.names=T)
for(j in 1:length(oe_files)) {
  var_file                 <- oe_files[j]
  var_file_name            <- basename(var_file) %>% gsub(".rds","",.)
  message(paste0("Processing Sample ",j," of ",length(oe_files)," - ", var_file_name))
  #Read10X for 10X outputs, readRDS for moe.rds files
  ifelse(  grepl(   "Moe" , var_file_name),   
  data_dge                 <- readRDS(var_file),
  data_dge                 <- Read10X(data.dir = var_file))
  data_seu                 <- CreateSeuratObject(counts = data_dge, project = var_file_name, min.cells = 3, min.features = 200) %>% 
                                PercentageFeatureSet(pattern = "^MT-", col.name = "percent.mt")
  data_seu                 <- SCTransform(data_seu, vars.to.regress = c("percent.mt"), verbose = T, variable.features.n = 3000)
  saveRDS( data_seu, file = paste0("/seurat_obj/Seu_", var_file_name, ".rds"))
} 

### All the chunks below are ran twice. Once to merge Mice_oe, another to merge Human_oe
oe_files <- list.files("/seurat_obj", "Mice_oe_", full.names = T) 
oe_files <- list.files("/seurat_obj", "Human_oe", full.names = T) 

data_list <- NULL
for(j in 1:length(oe_files)) {
  var_file                 <- oe_files[j]
  var_file_name             <- basename(var_file) %>% gsub(".rds", "", .)
  data_list <- append( data_list, readRDS(var_file))
}

integrate <- function(data_list){
    data_features <- SelectIntegrationFeatures(object.list = data_list, nfeatures = 3000)
    data_list <- PrepSCTIntegration(object.list = data_list, anchor.features = data_features)
    data_anchors <- FindIntegrationAnchors(object.list = data_list, 
                                           normalization.method = "SCT", 
                                           anchor.features = data_features, 
                                           verbose = TRUE)
    data_integrated <- IntegrateData(anchorset = data_anchors, 
                                         normalization.method = "SCT", 
                                         verbose = TRUE)
    data_integrated <- RunPCA(data_integrated, verbose = FALSE)
    data_integrated <- RunUMAP(data_integrated, dims = 1:30)
    return(data_integrated)
}

data_integrated <- integrate(data_list)
saveRDS(data_integrated, file = "/seurat_obj/integrated_data.rds")

##Integrate the integrated_mice and integrated_human 

data_list <- NULL
data_list <- append(data_list, integrated_mice)
data_list <- append(data_list, integrated_human)
data_seu <- SCTransform(data_list[[1]], vars.to.regress = c("percent.mt"), verbose = T, variable.features.n = 3000)
data_seu <- SCTransform(data_list[[2]], vars.to.regress = c("percent.mt"), verbose = T, variable.features.n = 3000)

#### This step causes error 
data_integrated <- integrate(data_list)

Looks to be caused by FindIntegrationAnchors having no anchors retained..
Finding all pairwise anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 60 anchors
Filtering anchors
        Retained 0 anchors
Extracting within-dataset neighbors
Warning message:
In RunCCA.Seurat(object1 = object.1, object2 = object.2, assay1 = "ToIntegrate",  :
Warning message:
In RunCCA.Seurat(object1 = object.1, object2 = object.2, assay1 = "ToIntegrate",  :
  Fewer than 50 features used as input for CCA.
Error in hclust(d = dist.mat) :
  NA/NaN/Inf in foreign function call (arg 10)
Calls: IntegrateData ... PairwiseIntegrateReference -> BuildSampleTree -> hclust
Execution halted

I understand this is quite a long post to post, and I appreciate any of you sharing your insights!

**Comment by andrewwbutler** [comment]
Hi,

My guess for what's going on here is that you haven't converted the gene names between human and mouse to be equivalent (note the difference in capitalization). Typically, the way I have done this in the past is to just convert all the mouse genes to uppercase to match the human gene names before creating the mouse Seurat objects.

Your other point about the order of integration is a bit more complicated. I would recommend trying both strategies. It's likely that they will yield similar results as the integration algorithm will merge together similar datasets first and so in practice you'll end up creating intermediate human integrated and mouse integrated objects that then get merged in the last step. You could also specifically enforce this behavior through the `sample.tree` parameter.

**Comment by jurtlest** [comment]
Thanks for pointing that out Andrew! 
I've did some reading about converting the gene names between human and mouse using biomaRt. However, the current method that I've found is to convert it by using the count table itself via 
hoe.raw <- GetAssayData(integrated_hoe,slot="data")

Is there a more straightforward way in converting all the gene names in human object within the seurat sample ?? Perhaps I'm just missing something obvious? 

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Yep, currently the best way to do this would be to pull out the counts matrix, rename, and create a new Seurat object (note that the slot here should be `"counts"`). The ability to rename features in a Seurat object is not currently supported but is something we are thinking about the best way to facilitate in the future.

**Comment by jurtlest** [comment]
Thanks Andrew !
