### ISSUE TITLE
merge objects without RUNumap on the merged object

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#4144]
Hi, 
I need to merge four Seurat objects which they had their own UMAP embedding, when I merge them, did the umpa embedding included in the new object or I have to runumap in the merged object?

Thank you

**Comment by yuhanH** [comment]
Hi, 
You can set the umap reduction name to `merge.dr`  in `merge` function.
`merge( merge.dr = c("umap"))`
