### ISSUE TITLE
sctransform RunPCA error

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#4145]
Hello all,

I had a quick question about SCTransform. It's the same as issue #2852 
I'm not sure I understand the comment from Andrew "You can either set the variable features of the merged SCT assay yourself (to something like the intersection or union of the individual object's variable features) or provide this vector of features to RunPCA itself."
Can someone please help me with this? I'm not a person who codes regularly so if someone has the code that can help me get past the RunPCA problem, that would be great help. Thanks!
-Nikita

**Comment by yuhanH** [comment]
HI, 
You can use `SelectIntegrationFeatures` to select variable genes for the merged sct object. 
Here is an example:
```
obj.merge <- merge(x = obj.list[[1]], y = obj.list[2:length(obj.list)])
obj.features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 2000)
VariableFeatures(obj.merge[["SCT"]]) <- obj.features
```
