### ISSUE TITLE
Referencing axes data of VariableFeaturePlot?

### ISSUE THREAD

**Issue by mr-september** [satijalab/seurat#4147]
I have 2 questions regarding `VariableFeaturePlot`.

1. Is there an easy way to reference the y and x axes values? I want to do something like finding mean, variance, etc. of this data. I have been digging through Seurat's R source code, but this is a little too advanced for me, and I've gotten stuck at references to `HVFInfo` and `hvf.info`.
2. Is it possible to reference these values BEFORE `FindVariableFeatures`? In practice, I want the "Standardized Variance" and "Average Expression" values of the entire dataset, regardless of whether they were deemed `variable` or `non-variable` by `FindVariableFeatures`. If this can't be done, then I suppose there's no harm applying `FindVariableFeatures` first, extracting the axes data, then re-running`FindVariableFeatures` with my new `nfeatures` value?

**Comment by saketkc** [comment]
If you are looking for only mean and variance values, you can specify `nfeatures` to be the total number of features in your dataset. There are different ways that "standardized variance" can be calculated in Seurat, but given your interest in mean and variance you can simply use the `vst` approach

```r
pbmc_small <- FindVariableFeatures(pbmc_small, nfeatures = dim(pbmc_small)[1], selection.method = "vst")
head(HVFInfo(pbmc_small))
            mean    variance variance.standardized
MS4A1     0.3875   1.0251582             0.8983463
CD79B     0.6000   1.2810127             0.4731134
CD79A     0.7000   4.3645570             1.0862810
HLA-DRA  13.4250 725.4626582             0.9730883
TCL1A     0.3000   0.8708861             1.3558627
HLA-DQB1  1.7125  16.4099684             0.9948343
```

If you are planning to do something downstream, it might be advisable to not set all the features to be variable features.
