### ISSUE TITLE
Error using FindConservedMarkers 

### ISSUE THREAD

**Issue by masummers** [satijalab/seurat#415]
Hi, 

Im running the CCA analysis pipeline on 2 datasets. Everything works fine however when i run FindConservedMarkers for each cell cluster i get the following error:

#Cluster0 markers
>Cluster0_markers <- FindConservedMarkers(combined.data, ident.1 = 0, grouping.var = "protocol", 
                                          print.bar = FALSE)
Warning messages:
1: In if (!ident.use.2 %in% object@ident) { :
  the condition has length > 1 and only the first element will be used
2: In if (!ident.use.2 %in% object@ident) { :
  the condition has length > 1 and only the first element will be used

It seems to generate a gene list fine for each cluster, however i cant find the cause of this error and im not sure if this is impacting the resulting list.

Any help or guidance is appreciated

**Comment by leonfodoulian** [comment]
Hi,

Please refer to issue #347.

Best,
Leon

**Comment by masummers** [comment]
Brilliant! I now understand.
Much appreciated.

Cheers.
