### ISSUE TITLE
'Joint RNA and ATAC analysis: 10x multiomic' vignette error

### ISSUE THREAD

**Issue by ryandikdan** [satijalab/seurat#4152]
While following the 'Joint RNA and ATAC analysis: 10x multiomic' vignette, there appears to be a missing argument when using the RunUMAP command. What is written in the vignette is 

```# build a joint UMAP visualization
pbmc <- RunUMAP(
  object = pbmc,
  nn.name = "wknn",
  assay = "RNA",
  verbose = TRUE
)
```

But this resulted in the error message:

```
Warning: The following arguments are not used: reduction.model, return.model, n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
Error in py_call_impl(callable, dots$args, dots$keywords) :
  TypeError: simplicial_set_embedding() missing 3 required positional arguments: 'densmap', 'densmap_kwds', and 'output_dens'
```

I got it to work by following the RunUMAP command from the 'Weighted Nearest Neighbor Analysis' vignette which was

```
pbmc<- RunUMAP(pbmc, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
```

Perhaps only reduction key was needed. This does necessitate that the following DimPlot call be changed from 

```
DimPlot(pbmc, label = TRUE, repel = TRUE, reduction = "umap") + NoLegend()
```

to 

```
DimPlot(pbmc, label = TRUE, repel = TRUE, reduction = "wnn.umap") + NoLegend()
```

although I guess you could change the name of the reduction in the RunUMAP function as well.

There was also a bit of incongruence with the command above it

```
pbmc <- FindMultiModalNeighbors(
  object = pbmc,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)
```

modality.weight.name appears to be changed anyway and naming it RNA.weight is a bit misleading since the function actually generates SCT.weight and peaks.weight. Perhaps that argument can just be removed then.

Otherwise the vignette was a great tool. With the noted corrections I was able to get the last image, which is quite beautiful.

**Comment by timoast** [comment]
Thanks for reporting, we'll update this soon. Note that this refers to the [Signac](https://github.com/timoast/signac) vignette, rather than Seurat

**Comment by ryandikdan** [comment]
Oh woops, I couldn't find the Signac github page. Thanks, I'll post some other stuff there then haha.
