### ISSUE TITLE
IntegrateData Segfault

### ISSUE THREAD

**Issue by JARawlins** [satijalab/seurat#4154]
While attempting to do RNAseq analysis on a large dataset on our server with the following configuration, we get a segmentation fault from the IntegrateData function. The same issue is not encountered when the same data is separated and ran individually, so I wonder if there is some kind of memory management issue in IntegrateData or one of the routines that it calls. If sample data is necessary, I may be able to scrub it a bit to not give away too much information on our lab's work and post it.

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Platform: x86_64-conda-linux-gnu (64-bit) 

**Error:**
*** caught segfault ***
address 0x7f6c940bf000, cause 'memory not mapped'

Traceback:
 1: subCsp_rows(x, i, drop = drop)
 2: x[i = i, , drop = TRUE]
 3: x[i = i, , drop = TRUE]
 4: eval(call, parent.frame())
 5: eval(call, parent.frame())
 6: callGeneric(x, i = i, , drop = TRUE)
 7: data.use1[anchors1, ]
 8: data.use1[anchors1, ]
 9: FindIntegrationMatrix(object = merged.obj, integration.name = integration.name,     features.integrate = features.to.integrate, verbose = verbose)
10: RunIntegration(filtered.anchors = filtered.anchors, normalization.method = normalization.method,     reference = object.1, query = object.2, cellnames.list = cellnames.list,     new.assay.name = new.assay.name, features.to.integrate = features.to.integrate,     features = features, dims = dims, weight.reduction = weight.reduction,     k.weight = k.weight, sd.weight = sd.weight, eps = eps, verbose = verbose)
11: PairwiseIntegrateReference(anchorset = anchorset, new.assay.name = new.assay.name,     normalization.method = normalization.method, features = features,     features.to.integrate = features.to.integrate, dims = dims,     k.weight = k.weight, weight.reduction = weight.reduction,     sd.weight = sd.weight, sample.tree = sample.tree, preserve.order = preserve.order,     eps = eps, verbose = verbose)
12: IntegrateData(anchorset = Tcell.anchors, dims = 1:30, features.to.integrate = all_genes)

**Surrounding code:**
#Create list of objects to integrate
Tcell.list <- c(X) Omitted for privacy

#Run normalization on each object separately
for (i in 1:length(Tcell.list)) {
  Tcell.list[[i]] <- NormalizeData(Tcell.list[[i]], verbose = FALSE)
  Tcell.list[[i]] <- FindVariableFeatures(Tcell.list[[i]], selection.method = "vst", 
                                             nfeatures = 2000, verbose = FALSE)
}

#Check if transgene is included in each object
 XX14_genes <- row.names(XX14)
 is.element("transgene", XX14_genes)

#Check if transgene is included in all_genes list
#returns list of all genes
all_genes <- lapply(Tcell.list, row.names) %>% Reduce(intersect, .)
is.element("transgene", all_genes)

Tcell.anchors <- FindIntegrationAnchors(object.list = Tcell.list, anchor.features = 2000, dims = 1:30)
#default for anchor.features is 2000 --> calls SelectIntegrationFeatures

#Look at anchor features
anchor_object <- Tcell.anchors
vector_of_anchor_features <- anchor_object@anchor.features
vector_of_anchor_features

is.element('transgene', vector_of_anchor_features)

Tcell.integrated <- IntegrateData(anchorset = Tcell.anchors, dims = 1:30, features.to.integrate = all_genes)

**Comment by saketkc** [comment]
Hi,

For larger datasets we make some recommendations in this [vignette](https://satijalab.org/seurat/articles/integration_large_datasets.html). Can you try running it with the recommended options? Feel free to reopen if you encounter issues.
