### ISSUE TITLE
DoHeatmap with additional annotation

### ISSUE THREAD

**Issue by cimbusch** [satijalab/seurat#416]
Dear Seurat team,

using the DoHeatmap function I would like to plot some annotations on top of the clusters: for example from which sample that cell originated from ("orig.ident") keeping the clustering pattern for example by "res.0.8". I did not find such an option, and started changing the ggplot in DoHeatmap but not successful so far.

Is there are good way performing this visualization with Seurat?

Cheers,
   Charles

**Comment by satijalab** [comment]
We don't support exactly this request. However, you can use the CombineIdent function, which assigns each cell an identity based on two features in the metadata. For example, you could say

object = CombineIdent(object, "res.0.8", "orig.ident")

Now, when the heatmap is plotted, it will segregate cells both by cluster, and by originating sample.

**Comment by hekselman** [comment]
Just to add, it would be amazing if you had this function. It can be seen in SCENIC package:

[(https://htmlpreview.github.io/?https://github.com/aertslab/SCENIC/blob/master/inst/doc/Step3.2_BinaryNwActivity.html)]

I haven't been able to implement it too unfortunatly.
