### ISSUE TITLE
CreateSeuratObject not recognizing gene names/features

### ISSUE THREAD

**Issue by bkalishneuro** [satijalab/seurat#4160]
Hello,
I read in 10X data using Read10X. This matrix contains gene names (e.g. "Eif3a") as row names and counts in columns. I then try to create a seurat object using the command below, but it does not seem to recognize the gene names as features. So, my resultant seurat object (FinalGroup_Unfiltered) only has 1 feature. However, the gene names are still present in seuratobject@assays$RNA. What is the problem that the genes are not being converted to features in creating the object?

cd_comb <- Read10X(data.dir = "/n/scratch3/users/b/btk4/Eunha/cd45_aggr/outs/count/filtered_feature_bc_matrix")
save(cd_comb,file="CD45_cd_comb.Robj")
FinalGroup_Unfiltered <- CreateSeuratObject(counts = cd_comb, project = "CD45", min.cells = 3, min.features = 200)

 Thanks very much,
Brian

**Comment by bkalishneuro** [comment]
Just to clarify, this same problem occurs if I use the simple command

FinalGroup_Unfiltered <- CreateSeuratObject(counts = cd_comb)

Genes are still present in the seurat object, but not identified as features. If  'FinalGroup_Unfiltered' is the seurat object, then the following is true:

> head(FinalGroup_Unfiltered)
An object of class Seurat 
1 features across 95644 samples within 1 assay 
Active assay: RNA (1 features, 0 variable features)
> ncol(FinalGroup_Unfiltered)
[1] 95644
> nrow(FinalGroup_Unfiltered)
[1] 32285

**Comment by timoast** [comment]
Can you show the output of the following:

```r
dim(cd_comb)
class(cd_comb)
ncol(FinalGroup_Unfiltered)
now(FinalGroup_Unfiltered)
```
