### ISSUE TITLE
Should I merge and/or integrate for these datasets?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4161]
Hi everyone, 

Let's say I sorted two populations of T cells from the same tissue from 3 different donors, based on a surface protein marker (called X): Xnegative and Xpositive. I also sorted T cells from blood from these same donors, using the same surface protein marker. Then, I sequenced these 4 datasets:
1. Xnegative tissue
2. Xpositive tissue
3. Xnegative blood
4. Xpositive blood

**My goals are:**
1. To explore different cell subsets of Xpositive cells, because we hypothesize these cells perform certain functions that are different from Xneg populations in tissue
2. To explore if there are the same cell subsets present in blood and in tissue 

**I have 2 questions:** 
1. Would anyone mind helping me understand which of the following approaches make(s) the most sense?
2. From discussions about merge and integration (#3631, #3894, #3941), if I know there is huge between-donor variation in how the cells cluster when doing typical analysis on the tissue data from 3 donors, should I not merge donors, and instead, I should do integrate for each of my 4 datasets: the 3 donor data for Xneg tissue, then integrate 3 donor data for Xpos tissue, etc.? But then, is it appropriate to do comparative integrated analysis between/among already-integrated datasets?

Thank you very much for your insight! 

**For goal 1,** 
[Approach 1] Integrate the Xneg tissue dataset and Xpos tissue dataset and do a comparative analysis to find cell subsets that are shared and unique between the Xneg and Xpos populations in tissue. I will follow the Introduction to [scRNA-seq integration vignette](https://satijalab.org/seurat/articles/integration_introduction.html). 

Do the same for Xneg and Xpos blood data.

**For goal 2,** 
[Approach 2] Merge Xneg tissue and Xpos tissue data. Merge Xneg blood and Xpos blood data. Do comparative integrated analysis between the 2 merged datasets.

[Approach 3] Integrate all 4 datasets, and do a comparative analysis. 

[Approach 4] Integrate Xneg tissue and Xpos tissue data. Then, integrate Xneg blood and Xpos blood data. Then, do comparative analyses between the tissue integrated data and the blood integrated data.

**Comment by torkencz** [comment]
Our general answer to your title can be found in the Discussion: https://github.com/satijalab/seurat/discussions/3998

For your particular case I think the plan you laid out for goal 1 sounds good. For goal 2 I see approach 1 and 2 being better than 4. For your second question, it is dependent on how much between donor variation you see. The only thing that you have to remember is that we recommend using the raw (non-corrected) data for differential expression analyses, and including batch as a latent variable.
