### ISSUE TITLE
Seurat 4.0 error subsetting genes with "-" dashes

### ISSUE THREAD

**Issue by wgk51** [satijalab/seurat#4164]
Receiving the following error when I try to use subset to filter based on expression of genes with "-" in the name. 

Both this:
> DefaultAssay(data) <- "RNA"
> data <- subset(x = data, subset = "Hbb-bs" <=7)

And this: 
> DefaultAssay(data) <- "RNA"
> data <- subset(x = data, subset = Hbb-bs <= 7)

Yield this error:
> Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
>   None of the requested variables were found: 

Previous threads have noted that surrounding the gene name with quotes resolved this in Seurat 3.0, however that is not working in 4.0. For genes that I can successfully subset based on expression (i.e. those whose names don't have dashes), I am no longer able to subset by expression when adding quotation marks.

Any advice would be much appreciated!

**Comment by bassanio** [comment]
Try using the "`" 
```
TCEB3-AS1  <-subset(data, subset = `TCEB3-AS1` > 1 )
```
