### ISSUE TITLE
Would doing DE analysis on normalized RNA Assay counts miss the adjustment of cell cycle scores & percent.mt in SCT integration workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4166]
Hi there, 

From #3665 workflow suggested by @jaisonj708, I built my integration workflow as below: 

1. Create all seurat objects
2. QC and filter each object. 
3. Calculate percent.mt on raw counts 
4. Normalize each object by SCTransform(): Regress out percent.mt variable; scale = TRUE, center = TRUE
5. Normalize each object by NormalizeData() setting assay = "RNA" but keep defaul assay being SCTAssay
6. Calculate cell cycle scores on SCT Assay normalized counts for each object 
7. Make a list of all objects 
8. Run SelectIntegrationFeatures(), PrepSCTIntegration, and FindIntegrationAnchors() of the list of objects 
9. IntegrateData()
10. ScaleData() to regress cell cycle scores on integrated object, setting scale = FALSE, center = FALSE
11. RunPCA(), RunUMAP(), FindNeighbors(), and FindCluster() on Integrated Assay
12. Switch to RNA Assay 
13. Perform DE analysis on the integrated object on RNA Assay

My question is with the workflow above, where only the data from SCT Assay are adjusted for percent.mt and cell cycle scores, **wouldn't our DE results (which is done on RNA Assay) miss the adjustment of percent.mt (done on SCT Assay data) and cell cycle scores (which was done on Integrated Assay data in integration workflow and on SCT Assay data on regular non-integrated workflow)?** 

And, if it would, should I instead calculate cell cycle scores on RNA Assay (after doing NormalizeData() of the RNA Assay raw counts) before doing SCTransform() to regress both the cell cycle scores and percent.mt at step 4 (and hence eliminating step 10), as suggested by #3692)? But even so, doing DE on RNA Assay would still miss these adjustments...

Thank you for your help!

**Comment by jaisonj708** [comment]
Please refer to earlier issues on this subject such as #2180.
