### ISSUE TITLE
Add count total column (or logCount) to FindMarkers result output

### ISSUE THREAD

**Issue by gringer** [satijalab/seurat#4167]
I've been asked to generate MA plots for the differential expression comparisons that I'm doing. One statistic that is missing from the Seurat FindMarkers results that is present in the DESeq2 results is the mean gene/transcript expression, which is used for the X axis on an MA plot (on a log scale).

I propose that a suitable proxy for this is the *total* gene/transcript count, pulled from the RNA count data. The effort required to add this data myself is not large, but things work out nicer (i.e. I get fewer bugs in my code) if I don't have to go through intermediate lookup tables to do my calculations:

    geneLogSums <- log2(rowSums(GetAssayData(data.seurat, "counts", "RNA")));
    results$logSum <-geneLogSums[results$gene];

With that information, I can produce MA and volcano plots:

        results %>%
            ggplot() +
            aes(x=logSum, y=avg_log2FC, col=p_val_adj) +
            geom_point()
        ggsave("MAPlot.png", width=11, height=8);
        results %>%
            ggplot() +
            aes(x=avg_log2FC, y=1/p_val_adj, col=logSum) +
            scale_y_log10() +
            geom_point() +
        ggsave("VolcanoPlot.png", width=11, height=8);

![VolcanoPlot](https://user-images.githubusercontent.com/856314/109573834-344f1780-7b54-11eb-918f-50abc9cc2c12.png)
![MAplot](https://user-images.githubusercontent.com/856314/109573865-3618db00-7b54-11eb-941c-bd8da333a757.png)

**Comment by mojaveazure** [comment]
Hi David,

This is an excellent suggestion; we don't have the bandwidth to implement this now, but would be happy to entertain a PR that adds a gene count column to the results of `FindMarkers`

**Comment by MaxGreil** [comment]
Hi @mojaveazure ,

I would like to take on this issue. Can you please explain what needs to be done here?

**Comment by gringer** [comment]
@MaxGreil in [this](https://github.com/satijalab/seurat/blob/0905a17c0802ca5646c1ff034bcfbbdd0eeb16d1/R/differential_expression.R#L922) function (or a more appropriate called function inside that function), add an additional column to the output that represents the total expression count per feature.

My guess is that the calculation would be best made near [this line](https://github.com/satijalab/seurat/blob/0905a17c0802ca5646c1ff034bcfbbdd0eeb16d1/R/differential_expression.R#L532).

**Comment by rsatija** [comment]
Apologies that we will not be supporting this. I can see cases where having the total counts for cells in each condition would be useful, but it is likely to be in a minority of cases - and can be addressed using the code you describe above even if not in Seurat
