### ISSUE TITLE
Seurat v4 Reference Mapping: Overlapping of clusters

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#4168]
I have got 16 pools from 10X with multiple samples and I have followed the Multimodal reference mapping(PBMC). When I try to highlight/Subset the Clusters are overlapping. Is this normal ? Is there a better method to make the fine clusters.

**Plotting of 2 Clusters in the Reference**
```
reference <- LoadH5Seurat("~/Downloads/pbmc_multimodal.h5seurat")
Idents(reference)<-reference$celltype.l1
RCD4T <- WhichCells(reference, idents = c("CD4 T"))
RCD8T <- WhichCells(reference, idents = c( "CD8 T"))
DimPlot(reference, label=T,reduction = "wnn.umap", group.by = "celltype.l1", cells.highlight= list(RCD4T, RCD8T), cols.highlight = c("darkblue", "darkred"), cols= "grey")

```

![Reference](https://user-images.githubusercontent.com/11612433/109616881-2945b880-7b4f-11eb-95e1-fda9f3a51866.png)

============================================================================================
**Plotting of the MyData**
```
CD4T <- WhichCells(MyData, idents = c("CD4 T"))
CD8T <- WhichCells(MyData, idents = c( "CD8 T"))
DimPlot(MyData, label=T,reduction = "ref.umap", group.by = "predicted.celltype.l1", cells.highlight= list(CD4T, CD8T), cols.highlight = c("darkblue", "darkred"), cols= "grey")
```

![MyData](https://user-images.githubusercontent.com/11612433/109616913-32368a00-7b4f-11eb-9c90-c704d323b19c.png)

=======================================================================================
Below is the Commands I used to run the analysis.  
```
reference <- LoadH5Seurat("pbmc_multimodal.h5seurat")

MyData<- merge(Pool1.1, y=c(Pool2.1, Pool3.1, Pool4.1, Pool5.1,Pool6.1,Pool7.1,Pool8.1,Pool9.1,Pool10.1,Pool11.1,Pool12.1,Pool13.1,Pool14.1,Pool15.1,Pool16.1), project= "AllSamplesCombined")
MyData <- PercentageFeatureSet(MyData, pattern = "^MT-",col.name = 'percent.mt',assay = "RNA")

# Remove filtered cells from the query
MyData<- subset(MyData, subset = nFeature_RNA > 200 & nFeature_RNA < 5200 & percent.mt < 10)

MyData <- SCTransform(
  object = MyData,
  assay = "RNA",
  method = 'glmGamPoi',
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
  do.scale = FALSE,
  do.center = TRUE
)

dim(MyData)

anchors <- FindTransferAnchors(
  reference = reference,
  query = MyData,
  k.filter = NA,
  reference.assay = "SCT",
  query.assay = "SCT",
  reference.reduction = "spca",
  normalization.method = "SCT",
  dims = 1:50,
  n.trees = 20,
  mapping.score.k = 100
)

MyData <- MapQuery(
  anchorset = anchors,
  query = MyData,
  reference = reference,
  refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca", 
  reduction.model = "wnn.umap"
)

MyData <- AddMetaData(
  object = MyData,
  metadata = MappingScore(anchors = anchors),
  col.name = "mapping.score"
)

```

**Comment by yuhanH** [comment]
HI, 
It doesn't look right. Two suggestions. 
I would suggest you download the `updated reference object` containing the reference SCT model . The reference SCT model may solve this issue. You can download it [here](https://atlas.fredhutch.org/nygc/multimodal-pbmc/).
The second one is that you can try to map your pool object individually. They may have some strong batch effects which may result in the bad mapping results. You can follow the second bone marrow mapping example in our [vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html#example-2-mapping-human-bone-marrow-cells-1) in which the query objects are mapped individually.

**Comment by bassanio** [comment]
Okey I a downloading the new seurat object and will rerun on it first and then will follow the individual mapping method

**Comment by bassanio** [comment]
@yuhanH : I have downloaded the new reference :https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat 
and rerun the analysis but got this error 
```
 anchors <- FindTransferAnchors(
+   reference = reference,
+   query = combined,
+   k.filter = NA,
+   reference.assay = "SCT",
+   query.assay = "SCT",
+   reference.reduction = "spca",
+   normalization.method = "SCT",
+   dims = 1:50,
+   n.trees = 20,
+   mapping.score.k = 100
+ )
```

Error: Given reference.assay (SCT) has not been processed with SCTransform. Please either run SCTransform or set normalization.method = 'LogNormalize'. Execution halted

**Comment by yuhanH** [comment]
Hi,  
I think you need to update the [seurat-disk](https://github.com/mojaveazure/seurat-disk). The old version cannot load SCTAssay.

**Comment by bassanio** [comment]
@yuhanH : Yes, it works now. I have to update seurat-disk and seurat. Said that Update of the seurat reference did not removed the issue but it worsened it.  So I will  try the batch effect method too

![Rplot](https://user-images.githubusercontent.com/11612433/110375879-f37f6300-806b-11eb-96f5-36c8192ca2c5.png)

**Comment by yuhanH** [comment]
What is the batch effect method? Do you mean map them one by one ?

**Comment by bassanio** [comment]
@yuhanH : Yes I Meant that. Below is the command I ran and it seems failed to find ref.umap in its result
```
combined_batches <- SplitObject(combined, split.by = "ID")

combined_batches <- lapply(X = combined_batches, FUN = SCTransform, verbose = FALSE)

anchors <- list()
for (i in 1:length(combined_batches)) {
  anchors[[i]] <- FindTransferAnchors(
    reference = reference,
    query = combined_batches[[i]],
   k.filter = NA,
  reference.assay = "SCT",
  query.assay = "SCT",
  reference.reduction = "spca",
  normalization.method = "SCT",
  dims = 1:50,
  n.trees = 20,
  mapping.score.k = 100
  )
}

for (i in 1:length(combined_batches)) {
  anchors[[i]] <- MapQuery(
  anchorset = anchors[[i]],
  query = combined_batches[[i]],
  reference = reference,
  refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca", 
  reduction.model = "wnn.umap"
)
}

Merged_Combined_Batch<- merge(combined_batches[[1]], combined_batches[2:length(combined_batches)], merge.dr = "ref.umap")

```
Warning: The DimReduc ref.umap is not present in all objects being merged. Skipping and continuing.

```
DimPlot(Merged_Combined_Batch, reduction = "ref.umap", group.by =  "predicted.celltype", label = TRUE, repel = TRUE, label.size = 3) + NoLegend()
```
Error: Cannot find 'ref.umap' in this Seurat object

**Comment by yuhanH** [comment]
It's wired. Could you check if the individual object has correct mapping?  
You can use the same function you used before but for individual object. 
```
DimPlot(combined_batches[[i]], label=T,reduction = "ref.umap", group.by = "predicted.celltype.l1", cells.highlight= list(CD4T, CD8T), cols.highlight = c("darkblue", "darkred"), cols= "grey")
```

**Comment by bassanio** [comment]
@yuhanH  :

```
Merged_Combined_Batch<- merge(pag.combined_batches[[1]], pag.combined_batches[2:length(pag.combined_batches)], merge.dr = "ref.umap")
```

Warning: The DimReduc ref.umap is not present in all objects being merged. Skipping and continuing.

**Comment by yuhanH** [comment]
Right. It seems that not all individual objects in your `pag.combined_batches` have `ref.umap`. 
Could you find which object doesn't have `ref.umap`? 

Additionally, If it is ok for you, i would suggest you send the objects to me and it may be easier for me to find the bugs. 
my email: yhao@nygenome.org

**Comment by bassanio** [comment]
@yuhanH : I have send the data

**Comment by yuhanH** [comment]
Thanks for sharing the data. It seems that some specific pools in your data have conflicts between mapped UMAP position and predicted cell types. Those conflicted cells usually have low prediction score. 
You validate their cell annotations in the unsupervised analysis as well.

**Comment by gepmat** [comment]
Hi, 
I have exactly the same problem with the overlap, did you in the end found any solution?

Thanks

**Comment by bassanio** [comment]
@gepmat : Basically we removed any cells with low predicted score
```
Data.filtered <- subset(Data, subset = predicted.celltype.l1.score > 0.7)
```
