### ISSUE TITLE
Why does Dotplot reverse the expression level direction of genes when split.by "condition" in SCT integration workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4169]
Hi there, 

Following up on #4045, DotPlot of the integrated object appears to have a complete opposite direction of expression for all genes when split.by condition across clusters in the SCT-transformed integration workflow.

I set default assay = RNA after running FindClusters of the integrated object, did NormalizeData(assay = RNA), and for all plotting, setting assay argument = RNA. 

An example of this is below for the same marker, when I compared results from various types of plots. 

**Would anyone mind explaining to me what I did incorrectly and why there is such a difference between these plots of the same data? And, how can I verify which one is correct?**

Thank you for your help!

**FeaturePlot:** 
<img width="575" alt="Screen Shot 2021-03-02 at 8 56 41 AM" src="https://user-images.githubusercontent.com/62179082/109623596-36ee4480-7b35-11eb-8280-d140e0f106a7.png">

**VlnPlot:** 
![image](https://user-images.githubusercontent.com/62179082/109624950-ac0e4980-7b36-11eb-9558-6a2d99f6a1a0.png)

**RidgePlot (group by donor 1, 2, 3):** 
<img width="200" alt="Screen Shot 2021-03-02 at 9 32 27 AM" src="https://user-images.githubusercontent.com/62179082/109628063-3906d200-7b3a-11eb-9165-526eb277f938.png">

**DotPlot:**
<img width="143" alt="Screen Shot 2021-03-02 at 9 40 16 AM" src="https://user-images.githubusercontent.com/62179082/109629015-4e303080-7b3b-11eb-827d-b80fff2c1673.png">

**Comment by jaisonj708** [comment]
I can't seem to reproduce this on my end. Can you send an example object to seuratpackage@gmail.com, or demonstrate on a publicly avail dataset from `SeuratData`?

**Comment by denvercal1234GitHub** [comment]
Hi @jaisonj708 - I emailed you the object. Thank you very much again for your help!

**Comment by jaisonj708** [comment]
This gives the result you probably want:
```
cxcr5_integrated_test[['new.ident']] <- paste0(cxcr5_integrated_test[['integrated_snn_res.0.6', drop=T]], '_', cxcr5_integrated_test[['R5_status', drop=T]])
DotPlot(cxcr5_integrated_test, group.by='new.ident', features='CXCR5', assay='RNA')
```


(The behavior you were seeing is due to the fact that `split.by` changes how expression is scaled)
