### ISSUE TITLE
FindMarkers/FindAllMarkers issues with large datasets (v2.3)

### ISSUE THREAD

**Issue by malosreet** [satijalab/seurat#417]
Hello Seurat team,

I recently started using v2.3 of Seurat and it solved several problems I was previously facing with a large dataset. However, when I tried to use the FindAllMarkers function it only returned markers for the two largest clusters (~10000 and 27000 cells respectively). I tired various combinations of tests and thresholds with the same result. 

Next I tired to use the FindMarkers function individually for my clusters to try to understand the source of the problem. Here are the results: 

```R
> Astros_1_markers <- FindMarkers(All_batches_filt_merge_v3, ident.1 = "Astros_1", logfc.threshold = 0.10, test.use = "bimod", only.pos = TRUE)
Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> Excit_4_markers <- FindMarkers(All_batches_filt_merge_v3, ident.1 = "Excit_4", logfc.threshold = 0.10, test.use = "bimod", only.pos = TRUE)
   |++++++++                                          | 16% ~10m 02s
> Oligos_2_markers <- FindMarkers(All_batches_filt_merge_v3, ident.1 = "Astros_1", logfc.threshold = 0.10, test.use = "negbinom", only.pos = TRUE)
Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> Excit_9_markers <- FindMarkers(All_batches_filt_merge_v3, ident.1 = "Excit_9", logfc.threshold = 0.10, test.use = "negbinom", only.pos = TRUE)
   |++                                                | 2 % ~06h 49m 52s
```

As you can see above I got a "problem too large error" for two of the clusters I tried whereas the function started working fine for the other two. In fact, the two clusters for which the function works are the two large clusters mentioned above. For every other cluster I get the same error message. 

I suspect that when the small cluster is being compared to the rest of the cells (~78000 total), the remaining group of cells for comparison is too large and this is resulting in the error. For the larger clusters, the remaining group of cells is not too large to handle and so the error is bypassed. This would explain why FindAllMarkers returned markers only for the two large clusters. It doesn't explain why FindAllMarkers did not return any error message. 

Any suggestions for dealing with this issue would be very welcome. Thank you for your help!

Malosree

**Comment by satijalab** [comment]
I would suggest setting max.cells.per.ident to solve this. DE results should stay relatively fixed for very large clusters, and this will help address memory issues
