### ISSUE TITLE
Warning at FindVariableFeatures 

### ISSUE THREAD

**Issue by bun12** [satijalab/seurat#4173]
Hi, 

We use Seurat v3.2.2 and got this warning. 
What's wrong with this?

 > CT <- FindVariableFeatures(CT, selection.method = "vst", nfeatures =
2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
 Warning message:
1:  simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
 :
   pseudoinverse used at -0.32924
2:  simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
 :
   neighborhood radius 0.50533
3:  simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
 :
   reciprocal condition number  5.2661e-015
4:  simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
 :
   There are other near singularities as well. 0.090619

**Comment by timoast** [comment]
Please see https://github.com/satijalab/seurat/issues/2387

**Comment by xinxinStarXu** [comment]
hello, I met this situation, too. But I dont't konw why and whether this would influence the subsequent analysis. 
Have you solve this problem? 
Thank you very much!

**Comment by ahsv** [comment]
This appears to be a different issue than #2387 \:

As far as I can tell, these errors are related to the loess implementation used by both `Seurat` and `scanpy` - the tricks used by loess to speed up computations fail when the data are ill-conditioned in some way. 

Several other links where this is discussed: https://github.com/scverse/scanpy/issues/1504 (and the link mentioned there: https://github.com/has2k1/scikit-misc/issues/9), https://discourse.scverse.org/t/error-in-highly-variable-gene-selection/276.  

Suggestions from those links (that have also worked for me, after some testing/playing around with parameters):

* Remove genes that are only expressed in a small number of cells before running `FindVariableFeatures`.
    * Usually, the loess fit will not be affected for genes of medium to high mean by doing this (so the default behavior is preserved to some degree). 
    * This has the effect of removing many of the duplicated points from the mean-variance plot e.g. the points corresponding to the genes that are expressed with a count of 1 in exactly one cell.
    *  Judging by [this StackOverflow post](https://stackoverflow.com/questions/38864458/loess-warnings-errors-related-to-span-in-r), the issue is probably the duplicated values of gene mean. The loess implementation seems to work best with more-or-less unique values of x. That also suggests that adding a bit of jitter to the gene means would quash the warnings.  [The follow-up post](https://stackoverflow.com/questions/38948553/jittering-effects-on-loess) cannot confirm that a bit of jitter does the trick, but I haven't gone through their code in detail.  [One of the issues linked above](https://github.com/has2k1/scikit-misc/issues/9#issuecomment-725997364) gives a toy example where jitter fixes the problem.
    
* Increase the loess.span parameter 
    * This has the effect of smoothing the mean-variance curve in a more heavy-handed manner, essentially sharing information between genes whose differences in mean are larger than the default.  The effects of this on the final HVG selected will vary on a dataset-by-dataset basis.
