### ISSUE TITLE
legend disappeared when using split.by parameter in FeaturePlot 

### ISSUE THREAD

**Issue by chansigit** [satijalab/seurat#4174]
The legend is supposed to appear in every split panels

![image](https://user-images.githubusercontent.com/18084613/109776506-99326c80-7c3d-11eb-945c-58d4ed000aa2.png)
`FeaturePlot(seu, features = "percent.mt",split.by="stim", order=T) +theme(legend.position = c(0.1,0.2))`

**Comment by samuel-marsh** [comment]
Hi,

This is due to the fact that Seurat uses patchwork package to organize multiple plots.  Instead of the "+" syntax from ggplot2 you just need to use "&", otherwise only the final plot in the series will be modified.
```
FeaturePlot(seu, features = "percent.mt",split.by="stim", order=T)  & theme(legend.position = c(0.1,0.2))
```

Best,
Sam
