### ISSUE TITLE
Issue with Motif analysis (Multiome dataset)

### ISSUE THREAD

**Issue by vim15** [satijalab/seurat#4176]
Hello, 

I'm running a motif analysis on a human multiome dataset which I've called 'sconly'.
This analysis run perfectly well last week, but for some reason now it keeps failing. I'm pasting below what I had originally done (which worked) and what I am doing now, which is causing a failure. 

Previously did (worked): 

```

DefaultAssay(sconly) <- "ATAC"


pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE)
)

sconly <- AddMotifs(
  object = sconly,
  genome = BSgenome.Hsapiens.UCSC.hg38,
  pfm = pfm
)

Pou1f1_peaks <- FindMarkers( object = sconly, ident.1 = '6', ident.2 = c('1','2', '3', '4', '5', '0'), only.pos = TRUE, test.use = 'LR')

top.Pou1f1.peak <- rownames(Pou1f1_peaks[da_peaks$p_val < 0.005, ])

enriched.motifs <- FindMotifs(
  object = sconly,
  features = top.Pou1f1.peak)
```

Then when trying to do the below : 

```
DefaultAssay(sconly) <- "ATAC"

base_peaks <- FindMarkers(object = sconly, ident.1 = '0', ident.2 = c('1','2', '3', '4', '5', '6'), only.pos = TRUE, test.use = 'LR')


top.base.peaks <- rownames(base_peaks[da_peaks$p_val < 0.005, ])

enriched.motifs <- FindMotifs(
  object = sconly,
  features = top.base.peaks)
```

It fails, and I get this error : 

`Selecting background regions to match input sequence characteristics
Matching GC.percent distribution
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
  'x' contains missing values`

What is even more baffling, is that when I re-run code chunk #1 which previously worked, it now throws the same error.

**Comment by vim15** [comment]
Sorry, I'm an idiot, found out what was wrong when not changing 'da_peaks'.

**Comment by jiangpuxuan** [comment]
Hello,
I met the same problem. Have you made it?
I would like to have your help.
Thank you！
