### ISSUE TITLE
Error message converting sce object to Seurat object 

### ISSUE THREAD

**Issue by bananabrad1** [satijalab/seurat#4177]
Hi,

I'm getting an error message when I run the following code:
obj<- as.Seurat(sce)
Warning: Non-unique features (rownames) present in the input matrix, making unique
Error: Attempting to add a different number of cells and/or features

The dimensions of the two assays in sce are both 29736 x 719. The look identical to me otherwise as well apart from the log transformation. 

Where else could this error be coming from? I installed seurat very recently so I doubt the version is outdated. 

My sce object otherwise has these dimensons: 

class: SingleCellExperiment 
dim: 29736 719 
metadata(0)
assays(2): counts logcounts
rownames(29736)
rowData names(6)
colnames(719)
colData names(40)
reducedDimNames(2): PCA UMAP 
altExpNames(0)

Please let me know what you think!

Thanks

**Comment by torkencz** [comment]
Hi,

It think what the main problem here is that SingleCellExperiment objects support duplicate row names and Seurat does not. I would remove them and then the transform should work.
