### ISSUE TITLE
Exporting matrix from Seurat Object

### ISSUE THREAD

**Issue by tomallison24** [satijalab/seurat#418]
Hey guys!

First thanks for Seurat its mega! I am having a problem though in trying to extract the gene expression matrix from the Seurat object. I am using the RunMultiCCA function to use the new method to eliminate the batch effect of different sequencing runs, but we have a pipeline in which we run the tSNE separately. Thus, I need the scale.data after it has been aligned according to the CCAs, and before FindClusters function, but not sure which slot to find it in.

Thanks in advance

Tom

**Comment by satijalab** [comment]
We do not modify the scaled dat during CCA. If you want to run tSNE separately, you can export the aligned CC dimensions (using GetCellEmbeddings). This is the matrix we use for tSNE and clustering in Seurat.
