### ISSUE TITLE
Multimodal data analysis - data loading

### ISSUE THREAD

**Issue by strawberry789** [satijalab/seurat#4180]
Hello,

I'm following the multimodal data vignette (https://satijalab.org/seurat/articles/multimodal_vignette.html#load-in-the-data-1) and trying to load nanopore data files that ran through the SiCeLoRe pipeline (output txt files).  I converted the isomatrix.txt file to a csv.gz file and tried to load in the data using the following command:

cbmc.adt <- as.sparse(read.csv(file = "path/filename.csv.gz", sep = ",", 
    header = TRUE, row.names = 1))

But I got this error:

Error in read.table(file = file, header = header, sep = sep, quote = quote, : duplicate 'row.names' are not allowed

I thought the repeated gene names was the issue, but when I changed the row.names to 2 (where the second column is the transcript ID), I still get the same error.

Please advise how I should resolve this issue.

Thank you!

**Comment by timoast** [comment]
I'd suggest removing the `row.names=1` parameter and manually assigning unique row names after the data is loaded into R
