### ISSUE TITLE
Seurat Analysis Pipeline leads to background expression on TSNE

### ISSUE THREAD

**Issue by nasjr08** [satijalab/seurat#4182]
Hello,

I have attempted using the integration pipeline suggested by this Seurat Vignette: https://satijalab.org/seurat/archive/v3.0/immune_alignment.html

I had actually created a single Seurat object which included all my samples that was used to do the initial filtration. I then split each sample by the sample name and SCtransformed separately. I then followed the standard workflow:

split_srt <- SplitObject(sample.merge, split.by = "Sample.Name")

for (i in 1:length(split_srt)) {
    split_srt[[i]] <- NormalizeData(split_srt[[i]], verbose = TRUE)
    split_srt[[i]] <- SCTransform(split_srt[[i]], vars.to.regress = c("percent.MT"))
}

integ_features <- SelectIntegrationFeatures(object.list = split_srt, 
                                            nfeatures = 3000) 

split_srt <- PrepSCTIntegration(object.list = split_srt, 
                                   anchor.features = integ_features)

integ_anchors <- FindIntegrationAnchors(object.list = split_srt, 
                                        normalization.method = "SCT", 
                                        anchor.features = integ_features)

seurat_integrated <- IntegrateData(anchorset = integ_anchors, 
                                   normalization.method = "SCT")

I then Ran PCA and TSNE, and determined cluster markers:

seurat_integrated <- FindNeighbors(seurat_integrated,dims = 1:30)
seurat_integrated <- FindClusters(seurat_integrated, resolution = 0.5)

Merged.markers <- FindAllMarkers(seurat_integrated, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
top_markers <- Merged.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC)

The clustering itself appears to be great. The problem is that when I plot the cluster markers, something clearly isn't right as all cells have a baseline expression of all markers:

![image](https://user-images.githubusercontent.com/44295629/110021177-51d1dc00-7d22-11eb-9692-96b684fd82e8.png)

![image](https://user-images.githubusercontent.com/44295629/110021483-affebf00-7d22-11eb-9d10-a995bd812958.png)

Am I better off using a different assay (perhaps the RNA assat or the SCT assay that is automatically created by sctransform?) for plotting gene expression? 

Or am I supposed to do the Sctransformation on all the samples in single Seurat object prior to then splitting and then integrating the data?

**Comment by timoast** [comment]
As stated in many previous issues, we do not recommend using the integrated data for visualisation or differential expression

**Comment by nasjr08** [comment]
Hi. Yes apologies for not fishing that out. I did realize that after going through some of the previous issues. Apologies for not closing the issue.
