### ISSUE TITLE
Average expression comparisons between different clusters.

### ISSUE THREAD

**Issue by CaroSegami** [satijalab/seurat#4185]
Hello!

I have calculated Average Expression for my clusters by subsetting each cluster. Now I want to know if its correct to compare the expression values between the clusters. For example I have the metadata of which genes sit on X , can I take the mean of expression of genes in X in cluster 1 and compare it with the mean of genes in X of cluster 2?
I just want to know if this is correct or if I should just stick to only compare autosomes/X ratios for example.

Cheers,

Carolina

**Comment by jaisonj708** [comment]
As long as you are comparing the same feature set and using the same method for computing average expression, I don't see any problem with what you are proposing. How you interpret the result is up to you and more of a biological question than a technical one.
