### ISSUE TITLE
Why FindMarkers uses total gene number instead of number of tests for Bonferroni correction?

### ISSUE THREAD

**Issue by weishwu** [satijalab/seurat#4186]
Hi,

One feature in FindMarkers that has been puzzling me is why it keeps using the total number of genes for multi-test correction, ignoring the actual number of tests which is affected by the min.pct cutoff. No matter what min.pct cutoff I use, it only affects the genes reported, but adj_p_val stays the same, and the ratio between the output adj_p_val and the p_val always equals to the total number of genes unless adj_p_val caps at 1. My understanding of Bonferroni multi-test correction is that it multiplies the p-value by the number of tests. The min.pct is to limit the testing to the genes that pass an expression threshold, so it seems to make more sense to use the number of tested genes for Bonferroni correction. 

I wonder if it's legitimate to apply my own multi-test correction using only the filtered gene set (with min.pct>0.1 only and no log2FC cutoff).

Thanks.

**Comment by timoast** [comment]
Please see https://github.com/satijalab/seurat/issues/4112
