### ISSUE TITLE
Why could I be having only NAs for p_val and p_val_adj in Seurat DGE analysis?

### ISSUE THREAD

**Issue by charlesgwellem** [satijalab/seurat#4188]
I am doing a differential gene expression analysis to find out genes that are differentially expressed in one cell type from the lung in two conditions, control and idipathic pulmonary fibrosis (IPF). In total I have 152538 cells. Can anyone help me provide a hint to understand why only NAs get returned for the pvalues and adjusted pvalues?

```

table(seurat$group)

Control     IPF 
  64652   87886 

degs <- FindMarkers(seurat, 
                            ident.1 = "IPF",
                            ident.2 = "Control")
head(degs) 

         p_val  avg_logFC pct.1 pct.2 p_val_adj
SPP1        NA  1.2721607 0.390 0.125        NA
FN1         NA  1.1768771 0.741 0.409        NA
CRIP1       NA  1.0484934 0.938 0.832        NA
CCL18       NA  0.9830185 0.734 0.469        NA
S100A10     NA  0.5799861 0.965 0.902        NA
VIM         NA  0.5666287 0.992 0.964        NA
```

**Comment by torkencz** [comment]
Hi,
From the top of my head I think you might not have group labels loaded as Idents. Idents(seurat) <- seurat$group. If that does not work I can reopen and I might need further information to reproduce your results. I would also try to manually load in a gene and do a test to see what it results in.
