### ISSUE TITLE
Installing an older version of Seurat 

### ISSUE THREAD

**Issue by denertekin** [satijalab/seurat#4190]
Hi, 
I am trying to install an older version of seurat (v3.1) and have been running into issues. 
i use remotes::install_version("Seurat", version = "3.1.0"), it starts installing and then stops with an error:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'multtest'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'Seurat'
* removing 'C:/Users/uqdertek/Documents/R/win-library/4.0/Seurat'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘C:/Users/uqdertek/AppData/Local/Temp/Rtmpsr0zKa/remotes50788725635/Seurat’ had non-zero exit status

Thank you! 
Deniz

**Comment by samuel-marsh** [comment]
Hi Deniz,

Not member of dev team but hopefully can help.  The issue appears to be with installation of multtest package.  Try installing Seurat again after installing multtest directly from BioConductor:
`BiocManager::install('multtest')`

Best,
Sam

**Comment by denertekin** [comment]
Hi Sam, 
thank you very much! that fixed it.

Best. Deniz
