### ISSUE TITLE
 FindNeighbors and FindClusters are not found while performing integration on datasets normalized with SCTransform?

### ISSUE THREAD

**Issue by Statekeylablin** [satijalab/seurat#4191]
https://satijalab.org/seurat/articles/integration_rpca.html
Is it unnecessary？Or some other things? I'm confused about that. I would appreciate for your reply.

**Comment by yuhanH** [comment]
Hi, 
I am not sure fully what steps you are asking.  
This [rpca vignette](https://satijalab.org/seurat/articles/integration_rpca.html) provides you with some alternate ways to do integration on large-scale dataset.  
If you want to find clusters in the SCT-normalized integrated object, you need to run `FindNeighbors` and `FindClusters` same with  log-normalized workflow.
