### ISSUE TITLE
Columns order of the input count table affects the results

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#4192]
Hi Seurat Team! I'm really liking your work so far :)

I've encountered that changing the column order of the input count table (that is, the order of the cells) produces different results. Here's the toy dataset I've used to reproduce the result: [subset_ILCs_100.txt](https://github.com/satijalab/seurat/files/6100210/subset_ILCs_100.txt) , and here's my code:
```
library(Seurat)
raw <- read.table("/data/transfcounts_performance_test/subset_ILCs_100.txt", header=TRUE, row.names=1)
s.object <- CreateSeuratObject(raw, min.cells = 1)
s.object <- SCTransform(s.object)
s.object <- RunPCA(s.object)
s.object <- FindNeighbors(s.object, dims = 10, k.param = 10)
s.object <- FindClusters(s.object)
## write the output in a file
for (i in 1:length(ident)){
  ident <- data.frame(s.object$seurat_clusters)
  cname <- paste("cluster", ident[[i]], sep="_")
  ident[[i]] <- cname
}
write.table(ident, file="/home/biobam/Downloads/cluster_ident.txt", quote=FALSE, sep="\t")
```
And for sorting the columns (and thus changing the order) I've added the following lines previous to create the Seurat object:
```
cells.sorted <- sort(colnames(raw))
raw <- raw[,cells.sorted]
```
Here's how the output files look like:
```
biobam@marta:~/Downloads$ head -n4 cluster_ident.txt 
SRR2088319	cluster_4
SRR2088439	cluster_6
SRR2088318	cluster_2
SRR2088317	cluster_1
biobam@marta:~/Downloads$ head -n4 cluster_ident_sorted.txt 
SRR2088300	cluster_2
SRR2088301	cluster_5
SRR2088302	cluster_1
SRR2088303	cluster_0
```
Being the `cluster_ident.txt` the output created with the original table and the `cluster_ident_sorted.txt` the one created with the sorted table. And if I count how many cells are in each cluster:
```
biobam@marta:~/Downloads$ cat cluster_ident.txt | cut -f2 | sort | uniq -c
     19 cluster_0
     17 cluster_1
     17 cluster_2
     14 cluster_3
     12 cluster_4
     12 cluster_5
      9 cluster_6
biobam@marta:~/Downloads$ cat cluster_ident_sorted.txt | cut -f2 | sort | uniq -c
     22 cluster_0
     19 cluster_1
     16 cluster_2
     15 cluster_3
     14 cluster_4
     14 cluster_5
```
We can see that there's a difference in both the number of clusters produced and the number of cells in each one, even using the same parameters during the analysis. 

### So my questions are:
1. What is causing these differences?
2. Is it possible to mitigate them?

Thanks in advance,
Marta.

**Comment by timoast** [comment]
This is expected, as reordering the columns equates to a different random initialisation of the graph clustering algorithm.

> What is causing these differences?

The graph-based clustering algorithm (Louvain, SLM, Leiden, etc.) is non-deterministic. Identical results across different runs of the algorithm are obtained by setting the same random seed. Changing the order of the cells will change the order that nodes are visited during the local moving phase of the algorithm and will potentially change the final cluster identities of cells.

> Is it possible to mitigate them?

To achieve identical clustering results you need to order cells the same and set the same random seed (random seed is set by default in the function)

**Comment by MartaBenegas** [comment]
Thank you very much for your answer :)
