### ISSUE TITLE
Cell Embedding from CCA

### ISSUE THREAD

**Issue by yuw444** [satijalab/seurat#4194]
Hi,

I'm very confused about how CCA will give the result of cell embedding. In my understanding, CCA is doing the dimension reduction in the direction of genes, the result should be the number of genes multiply # of CCV. I could be very wrong, please let me know your thoughts.

Thanks

**Comment by torkencz** [comment]
Hi,
We use CCA to find cell embedding which project the cells into highly correlated subspaces. To get the gene loadings, we multiply the original scaled data (input to CCA) by these cell embeddings to get loadings per dimension. I hope this helps.
