### ISSUE TITLE
What is the correct way to remove a slot from a given assay?

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#4195]
I want to remove the `data` and `scale.data` slot from `spliced` and `unspliced` assays but I get this error
```
object@assays$unspliced@data <- NULL
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class "NULL" is not valid for @'data' in an object of class "Assay"; is(value, "AnyMatrix") is not TRUE
```
DietSeurat also doesn't support removing `data` slot.
```
DietSeurat(
object,
counts = TRUE,
data = FALSE,
scale.data = FALSE,
features = NULL,
assays = c("RNA","spliced","unspliced"),
dimreducs = NULL,
graphs = NULL)
Error in DietSeurat(object, counts = TRUE, data = FALSE, scale.data = FALSE,  : 
  data = FALSE currently not supported
```

**Comment by timoast** [comment]
You can't remove the data, but if you really want to save space in the object you could overwrite it as a sparse matrix containing all zeros. For example:

```r
library(Seurat)

empty_matrix <- sparseMatrix(dims = c(nrow(pbmc_small),ncol(pbmc_small)), i={}, j={})
empty_matrix <- as(empty_matrix, "dgCMatrix")
dimnames(empty_matrix) <- dimnames(pbmc_small)
pbmc_small <- SetAssayData(pbmc_small, slot = "data", new.data = empty_matrix)
```

Be aware that basically all the functions in Seurat assume that you haven't done this. 

Scale data can be removed using DietSeurat or by setting it to an empty matrix using the `SetAssayData()` function as shown above.
