### ISSUE TITLE
TransferData with pre-normalized data

### ISSUE THREAD

**Issue by JoshuaHess12** [satijalab/seurat#4198]
Hi,

I am using Seurat's data transfer method on a data set that has already been pre-processed and normalized. The only options for input normalization ("data.normalization") in Seurat's "TransferData" function are "LogNormalize" or "SCT". Is normalization built into the TransferData function? If so, how could one transfer data without including this extra step (e.g. for already normalized data sets).

Thanks in advance for any help.

**Comment by yuhanH** [comment]
HI, 
The normalization is not built in TransferData. If you data is normalized, you can run `FindTransferAnchor` directly. You can follow this [integration vignette](https://satijalab.org/seurat/articles/integration_mapping.html). 
In the `Cell type classification using an integrated reference` section, you can find the code for cell annotations transfer steps.
