### ISSUE TITLE
subset does not work with SeuratObject class

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#4199]
I created my SeuratObject using merging different seurat objects using merge.dr option in merge function
`new_object=merge(x, y=list(z,u),merge.data = TRUE, merge.dr = c('pca','umap'))`

When I try to subset the new using subset function:
`new_object1 <- subset(x = new_object, subset = sampletype == "DKD" ,idents=NULL)`

I got 
```
Error in CellsByIdentities(object = object, cells = cells) :
  Cannot find cells provided
```

**Comment by timoast** [comment]
Can you confirm that you have cells present with a metadata variable called "sampletype" with the value "DKD"?
