### ISSUE TITLE
is.expr for filtering cells and genes 

### ISSUE THREAD

**Issue by KaiyangZ** [satijalab/seurat#42]
Hi, 

I noticed that for filtering (function **Setup**), you first filter out cells with less than _min.genes_ genes detected using raw data and then do log-normalization, then filter out genes based on the normalized data. 
Does this mean that the parameter **is.expr** is the same threshold for raw data when filtering cells, and also for normalized data when filtering genes? If so, why? 

Thanks in advance for your help!

The corresponding codes:

            object@is.expr <- is.expr
            num.genes <- colSums(object@raw.data > **is.expr**)
            num.mol=colSums(object@raw.data)
            cells.use <- names(num.genes[which(num.genes > min.genes)])
            object@data <- object@raw.data[, cells.use]
            if (do.logNormalize) {
              object@data=LogNormalize(object@data,scale.factor = total.expr)
            }
            #to save memory downstream, especially for large object
            if (!(save.raw)) object@raw.data <- matrix();
            genes.use <- rownames(object@data)
            if (min.cells > 0) {
              num.cells <- rowSums(object@data > **is.expr**)
              genes.use <- names(num.cells[which(num.cells >= min.cells)])
              object@data <- object@data[genes.use, ]

**Comment by andrewwbutler** [comment]
Good catch. That second filtering wouldn't do much after normalizing and scaling. The Setup function has been updated in v1.4.0.9 so that **is.expr** will be checked against the raw data when filtering cells as well. Thanks!
