### ISSUE TITLE
Plot results for FindMarkers 

### ISSUE THREAD

**Issue by masummers** [satijalab/seurat#420]
Hi Seurat, 
Im running FindMarkers on my CCA dataset and can generate a gene list different between conditions/clusters (see below code).

```R
> macrophage.response <- FindMarkers(combined.data, ident.1 = "Macrophage_Sample1", ident.2 = "Macrophage_Sample2", print.bar = FALSE)
> head(macrophage.response, 30)
```

Im wondering how can I generate a heatmap visualising these differentially expressed genes for this cluster? 

Any advice or guidance appreciated.
Best regards.

**Comment by satijalab** [comment]
you can use DoHeatmap with a user-defined set of genes. ?DoHeatmap will pull up the documentation
