### ISSUE TITLE
Can SCT be used to normalize data before feeding it into a deep learning algorithm classifier?

### ISSUE THREAD

**Issue by giovanegt** [satijalab/seurat#4200]
Hi all, 
First off, thank you for your time and attention. Any thoughts are welcome
I am using Seurat workflow to get the data I need, my concern is whether SCT would be best suited for my purposes.

I am trying to consolidate several datasets into a big object. 
The goal is to create a big dataset and to classify the different cell types in it.
Then, this dataset will be  fed into a deep learning algorithm. 
Once  trained, the AI algorithm can be used to automatically classify cells in our model organism.
I will briefly describe our methodology and then present the issues I am facing

First,  I want to separate all different cell types present in my  (large) dataset to train the AI algorithm. 
Also, I need to minimize batch effects across different samples and different developmental time points, and ensure cells with same type end up in the same cluster, regardless of the sample of origin.  
Here is my workflow
1-  I first merged 15 datasets into a Merged.big object 
2- QC metrics and trimmed down low quality cells
3- I integrated the object into a massive integrated.Obj. 
4- To integrate the Merged.big object,  I run the reciprocal PCA tutorial. I could not use SCT integration tutorial because I ran out of memory before finish the procedure (Also, it appeared to me, that reciprocal PCA gave a quite nice result at the end)
 Below is the code I used.

``
#all other packages needed were already **loaded**
library(future)
library(future.apply)
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 40000 * 1024^2)

Merged.big.list <- SplitObject(Merged.big, split.by = "orig.ident")
Merged.big.list <- future_lapply(X = Merged.big.list, FUN = function(x) {
    x <- NormalizeData(x, verbose = FALSE)
    x <- FindVariableFeatures(x, verbose = FALSE, selection.method = "vst", nfeatures = 4000)
})
features <- SelectIntegrationFeatures(object.list = Merged.big.list)
Merged.big.list <- future_lapply(X = Merged.big.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})
anchors <- FindIntegrationAnchors(object.list = Merged.big.list, 
    reduction = "rpca", 
    k.anchor = 10,
    dims = 1:30)
saveRDS(Merged.big.integrated, file = "/Merged.big.integrated.RDS")

Merged.big.integrated <- IntegrateData(anchorset = anchors, dims = 1:30)
Merged.big.integrated <- ScaleData(Merged.big.integrated, verbose = FALSE)
Merged.big.integrated <- RunPCA(Merged.big.integrated, verbose = FALSE)
Merged.big.integrated <- RunUMAP(Merged.big.integrated, dims = 1:30)

Merged.big.integrated <- FindNeighbors(Merged.big.integrated, reduction = "pca", dims = 1:30)
Merged.big.integrated <- FindClusters(Merged.big.integrated, resolution = 0.6)

DimPlot(Merged.big.integrated, group.by = "orig.ident")
saveRDS(Merged.big.integrated, file = "/Merged.big.integrated.RDS")
``
Quick note, Harmony, did not improved the integration I had with Seurat. Therefore, I kept the Seurat integrated object.

Now, after integration, I ended up with a Merged.big.integrated object with roughly 75,000 cells (about 10GB in size). 
Then, I subset specific cell types based on known markers 

``
DefaultAssay(Merged.big.integrated) <- "RNA"
Merged.big.integrated <- NormalizeData(Merged.big.integrated, verbose = FALSE)
NPA <- subset(Merged.big.integrated, subset = geneA>0 & GeneB>0)
NPA <- subset(NPA, subset = GeneC==0)
NPA <- subset(NPA, subset = GeneD==0)
``
Next, I used the following code to generate the files I need for the AI algorithm.

NPA <- SCTransform(NPA, verbose = FALSE)
NPA <- data.frame(NPA@assays$SCT@data)
NPA<- t(NPA)
write.csv(NPC, file="~/NPA.csv")

After reading a couple of issues on data normalization I am starting to question myself whether I should run the SCTransform function on the data set I will be feeding into the AI algorithm (it appeared to me it would be good since this method has become very popular, it is very good to normalize across samples, and allows you to look at the residues of the regression ). 

Also, I am using the information stored at  Object@assays$SCT@data. However, I am now also questioning whether it wouldn't be better to use the residues stored at the scaled.data slot of the SCT assay. 

I apologize for the long description. But the questions are.
1- Should I run SCTransform on the subset dataset (e.g.NPA)? Or should I Run NormalizeData and ScaleData on the RNA assay and use this information instead? (SCT vs NormalizeData and ScaleData on the RNA assay)

2- If SCT, Should I use the log1p corrected count (NPA@assays$SCT@data) or should I use the residues stored at (NPA@assays$SCT@scale.data)? Which one would better reflect differences in cell types? I thought since the corrected log1p counts are used for DE tests they would also suit me well here.  Is this a correct way of thinking? 

Thoughts are appreciated. 
Thanks for your time and help

**Comment by saketkc** [comment]
Hi,

I will answer your questions below. But I will just say a few words if your end goal is to do supervised classification on new query cells. [Azimuth](https://azimuth.hubmapconsortium.org/) was designed with very similar goals in mind. It requires an annotated "reference" (which in your case would be your integrated object) and then uses supervised PCA to annotate the query cells. The website has links to references and associated documentation for generating the references.

> 1- Should I run SCTransform on the subset dataset (e.g.NPA)? Or should I Run NormalizeData and ScaleData on the RNA assay and use this information instead? (SCT vs NormalizeData and ScaleData on the RNA assay)

It's not entirely clear if your goal here to predict this subpopulation of cells. I will explain the general idea behind SCTransform.
SCTransform tries to learn the relationship between gene mean and dispersion.  By running it on a subset, you are forcing SCtransform to learn this relationship on a somewhat homogenous cell population (thus limiting the global mean - dispersion relationship you would want to learn)

> 2- If SCT, Should I use the log1p corrected count (NPA@assays$SCT@data) or should I use the residues stored at (NPA@assays$SCT@scale.data)? Which one would better reflect differences in cell types? I thought since the corrected log1p counts are used for DE tests they would also suit me well here. Is this a correct way of thinking?

The corrected counts (stored in slot="counts" of assay="SCT") or log1p counts (stored in slot="data") reflect counts after adjusting for the library size. However, the pearson residuals (slot="scale.data") are not comparable across datasets so any algorithm that relies on pearson residuals only for prediction is likely to give spurious results. Current version of Seurat allows storing the SCT model learned on one dataset which you can then use to calculate pearson residuals on a query dataset (instead of learning it from scratch). This is useful if you have for example a subset of cells you want to map.

**Comment by giovanegt** [comment]
Thank you for your answer,
There are still a few points I would like to clarify.
Azimuth uses the information at the assay = "RNA". Then,  supervised PCA to scale variable genes based on their importance.
 How azimuth accounts for Batch effects across samples of different labs or generated with different technologies or with different sequencing depth? I found the pancreas dataset results in the tutorial to be quite interesting.

Azimuth, or any other available classifier,  relies on a reference dateset which is not currently available for my model system (at least not without debate and disagreements). This is one reason we are building it in a unbiased way (unbiased related to different view points in the field). 

Also, we want to learn how cells change fate over distinct developmental times. which I think is not currently available in Azimuth. Having said that, one of our ideas is to compare our results against against well-known classifiers such as Azimuth, Garnet and so on. Therefore, I thank you for the comments.

Although our  general idea is classification of different cell types, we also would like to learn more about subpopulations within  specific clusters. Hence the idea of run SCT on the cell subset. 

Again, thanks for the reply, I appreciate the help and your time
