### ISSUE TITLE
Reorder levels from dimplot to dittobarplot

### ISSUE THREAD

**Issue by JaviTankian** [satijalab/seurat#4201]
I have a very naive question regarding dittoBarplolt representation. I want to use the same order and colours in the UMAP and dittoBarplot (figure below), but i can´t. Do yoy know how can I apply the order and the colours of the UMAP figure in celltype proportion figure?

![figure](https://user-images.githubusercontent.com/32361535/110516676-3132c900-810a-11eb-9e56-9a4130948eed.jpg)

Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can be helpful.  Two solutions depending on which you prefer.  First, would be to post on the github for the dittoSeq package as dittoBarPlot is not a Seurat function and those devs can better assist you there.  The other solution would be to change the order of DimPlot legend to match dittoBarPlot.  This can be achieved by re-leveling the factor order of the Idents in Seurat object to the desired order.

Best,
Sam

**Comment by JaviTankian** [comment]
Thank you very much Sam. I would like to keep the same order than Dimplot. I have tried to change the order in dittoSeq but it is not clear. I also posted this question in github for the dittoSeq package as you recomended me.

Very best

Javier

**Comment by Dragonmasterx87** [comment]
So guys you are going to laugh, but the way I do this is get percentages and then just copy them into Prism and make graphs there.

**Comment by samuel-marsh** [comment]
Hi Javier,

Sounds good, looks like dittoSeq devs have gotten back to you so hopefully that's helping solve your issue.  

@Dragonmasterx87 haha totally get it, I've been known to do that too on occasion.

As an aside just as my own personal opinion I dislike the stacked barplot for displaying this kind of information for two reasons.  First, there is not an effective way top convey variance in the proportions between samples within a group on these plots and therefore it is hard to understand what differences are truly meaningful (statistically) and which may be driven by an outlier sample or two (and practically speaking making a single plot for every single sample make even make it more difficult sometimes).  Second, is that this kind of visualization often suffers when it comes to smaller clusters and gaining any meaningful information from the small slivers they occupy on plot is very difficult but depending on the data may be very important.

There is also larger issue of whether simple proportions of cells actually convey the meaningful differences in cell type abundances/how to perform differential abundance analysis but that's whole other topic ;).

Best,
Sam

**Comment by Varix** [comment]
@samuel-marsh I think you have proposed a true issue with this approach, however, what do you recommend as an alternate solution? I sometimes also use stacked plots but with counts and not percentages. but that is still a stacked bar plot.
