### ISSUE TITLE
Transfer feature-level metadata from SingleCellExperiment in as.Seurat.SingleCellExperiment function

### ISSUE THREAD

**Issue by lianos** [satijalab/seurat#4205]
Currently (Seurat v4.0.0, SeuratObject v4.0.0) there is no feature-level metadata that transfers over to a `Seurat` object from a `SingleCellExperiment` when we call `seu <- as.Seurat(mySingleCellExperiment)`.

I'm not very familiar with the Seurat codebase and the structure of the Seurat object itself, but it looks like injecting this code chunk in [between lines 1072 and 1073](https://github.com/satijalab/seurat/blob/29e7eb7ba08519e34406ed03d323dec8787ff225/R/objects.R#L1072-L1073) here might do the trick:

```r
assays[[1L]] <- AddMetaData(
  assays[[1L]],
  as.data.frame(SingleCellExperiment::rowData(x), row.names = rownames(assays[[1L]])))
```

**Comment by torkencz** [comment]
Thank you for your suggestion. I added the code snippet and will likely be an update in a later release of Seurat.
