### ISSUE TITLE
Coverage Plot for gene counts

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#4206]
Hi Devs,

Is it possible to create a figure similar to F1G in this [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7263511/). Where one has a genome track, RNA counts, and annotated Gene symbols underneath? I feel this is something that can be achieved with codes from Signac, yet this is a question related to gene counts so I posted it here. Thanks for the help!

**Comment by timoast** [comment]
Hi @Dragonmasterx87, this should be possible to do in Signac if you created something similar to a scATAC-seq fragment file using the aligned cDNA reads. However, if you don't need to split the coverage plot by cell type or cluster, you could just make a bigwig file from the scRNA-seq BAM file and visualise the coverage using other tools developed for bulk data, like an IGV or UCSC browser or Gviz / ggbio in R. If you _do_ need to split cells by cluster, but maybe don't care so much about being able to interactively split the cells and view different regions, you could split the BAM file by cluster using [sinto](https://github.com/timoast/sinto) and create a separate bigwig for each BAM file.

**Comment by Dragonmasterx87** [comment]
Thanks Tim, will update once I get a plot.
