### ISSUE TITLE
Question about FindVariableFeatures

### ISSUE THREAD

**Issue by Vivianstats** [satijalab/seurat#4207]
Hello Seurat developers, 

I would like to know for the three options (disp, vst, and mvp) in the FindVariableFeatures function, whether gene expression mean and standard deviation are calculated using raw counts, or normalized and log-transformed counts? This is not clear in the function documentation, so it would be really helpful if you can clarify.

Thank you!

**Comment by Dragonmasterx87** [comment]
Hi @Vivianstats from the `FindVariableFeatures` function RDocumentation entry [here](https://www.rdocumentation.org/packages/Seurat/versions/4.0.0/topics/FindVariableFeatures) it says:

_"......All mean/variance calculations are not performed in log-space, but the results are reported in log-space - see relevant functions for exact details."_

Also please look at Jared's response [here](https://www.biostars.org/p/406388/).

Taken together, it appears that all calculations are performed on raw counts.

I'm not a Seurat dev, please also wait for a valid response from someone from the satija lab.

🐲

**Comment by Vivianstats** [comment]
Hi Dragonmasterx87,

Thank you for sharing the information! It seems clear that the calculations are performed before log-transformation, but I still wonder whether they are based on raw counts or library-size normalized ones.

**Comment by rschauner** [comment]
Also not a Seurat dev, but thought I could get you your answer. (TL;DR: it's the counts by default)

One helpful thing besides `?FindVaraibleFeatures` is `View`ing the functions themselves by just running `View(FindVariableFeatures)`, however, this yields slightly unhelpful output:

```
function (object, ...) 
{
  UseMethod(generic = "FindVariableFeatures", object = object)
}
```

So then taking a look I figured out the best method to pull will be the method for the `Assay` class in Seurat. So using `View( getS3method("FindVariableFeatures", "Assay"))` I found this in the function call:

```
  if (selection.method == "vst") {
    data <- GetAssayData(object = object, slot = "counts")
    if (IsMatrixEmpty(x = data)) {
      warning("selection.method set to 'vst' but count slot is empty; will use data slot instead")
      data <- GetAssayData(object = object, slot = "data")
    }
  }
```

So unless counts is empty, FindVariableFeatures are based on counts, not normalized data in the data slot. Hope this helps!

**Comment by saketkc** [comment]
If you are using the `SCTransform` based workflow, the variable features are set to ones with the highest pearson residuals. The default `FindVariableFeatures` on RNA uses the raw counts to choose the variable features (using the mean-variance relationship).
