### ISSUE TITLE
Barcode file missing. Expecting barcodes.tsv.gz

### ISSUE THREAD

**Issue by algebio** [satijalab/seurat#4208]
Hi (not sure this is a bug, please correct if mistaken)

I'm running the multimodal_vignette.Rmd but I got stack in one of the last chunks of code to run. (# Loading data from 10X multi-modal experiments). I downloaded two featured filtered files with format h5 and tar.gz from [here](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_10k_protein_v3) and I stored them in a folder with same path as the next line requires.

When I run the next line, I get this error: 

pbmc10k.data <- Read10X(data.dir = '../data/pbmc10k/filtered_feature_bc_matrix/') 

Error in Read10X(data.dir = "C:/Users/njo47/OneDrive - Newcastle University/Documents/Seurat/data/pbmc10k/") : Barcode file missing. Expecting barcodes.tsv.gz
2.
stop("Barcode file missing. Expecting ", basename(path = barcode.loc))
1.
Read10X(data.dir = "C:/Users/njo47/OneDrive - Newcastle University/Documents/Seurat/data/pbmc10k/")

How do I get or download tsv.gz files?

Thank you for your help.

Regards
Juan

**Comment by samuel-marsh** [comment]
Hi Juan,

Not member of dev team but hopefully can be helpful.  If you have the H5 files you can just use the `Read10X_h5` function instead of `Read10X`.

Best,
Sam

**Comment by algebio** [comment]
Hi Sam

Great answer. Thank you for your help!

Regards
Juan
