### ISSUE TITLE
DotPlot for cells from a cluster

### ISSUE THREAD

**Issue by kogolts** [satijalab/seurat#4209]
Hi, 
Is it possible to make a dotplot for cells from a selected cluster so that I could visualize the co-expression of the markers within the cells of the target cluster?

Thank you!

**Comment by denvercal1234GitHub** [comment]
You can use Idents argument of DotPlot() to select a certain cluster to plot. You can also use CellSelector feature to manually create a cluster for further analysis and visualization. See: https://satijalab.org/seurat/articles/visualization_vignette.html
