### ISSUE TITLE
FindClusters() resolution paramater no effect

### ISSUE THREAD

**Issue by jelicana** [satijalab/seurat#4214]
Hello!

I have 5 experimental groups with 3 samples in each (15 samples total, more than 100,00 cells).
After loading in the data and making seurat object and QC for each sample individually, I merged them 3 by 3 to get 5 seurat objects that represents each group (merge function).

Then I merged those 5 seurat objects into one seurat object and did the analysis following tutorial from Satija lab.

oneobject <- NormalizeData(oneobject)
oneobject <- FindVariableFeatures(oneobject)
all.genes <- rownames(oneobject)
oneobject <- ScaleData(oneobject, features = all.genes)
oneobject <- RunPCA(oneobject, features = VariableFeatures(object = oneobject))
oneobject <- FindNeighbors(oneobject, dims = 1:20)
oneobject <- FindClusters(oneobject, resolution = 1.5)
oneobject <- RunUMAP(oneobject, dims = 1:20)

I got UMAP that overlaps a lot (no difference between groups), I tried to increase the resolution paramater in FindClusters() function, but it doesn’t change the result even when I put 0.000001 or 5.5 (tried various values).

Any idea why changing resolution does not change umap at all?

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you confirm what you mean by "does not change umap at all?".  You mean that even after changing the resolution the number of clusters remains the same?

Best,
Sam
