### ISSUE TITLE
UMAP dimplot changed after R version was updated from R.4.0.2 to R.4.0.4. How can I fix it?

### ISSUE THREAD

**Issue by mnakaya5** [satijalab/seurat#4217]
I ran Dimplot (reduction = "umap") on R.4.0.2 with Seurat v3, however, the umap plot was changed after R version was updated to R.4.0.4 with seurat v4. I tried the previous R version and old Seurat as well to fix the plot as the old one and nothing changed....If I road the previous rds file, the umap plot showed the same as old, however, if I try to make umap with the same data, it cannot be reproduced. I have no idea to reproduce the same umap now. Could you support me to solve this issue? (e.g. python version effects on, some packages should be adjusted etc.)

**Comment by timoast** [comment]
If you ran `RunUMAP()` with default parameters, you should check that you have the same version of the [uwot](https://github.com/jlmelville/uwot) package installed as you used previously. 

If you ran `RunUMAP()` with `umap.method = "umap-learn"`, then you need to check the version of the Python umap-learn package.

In Seurat v4 we also changed the default neighbour-finding method, which could also change the results if you ran UMAP on a pre-computed neighbour graph.

**Comment by mnakaya5** [comment]
Thank you for your instruction I tried to install the old version uwot package as your advice but still, there is an error.  I read the issue on the other threads but still cannot succeed although Rtools was installed properly. (Path is correct.)
I did a few commands to install. but all errors were the same as below. What are the problems?

> devtools::install_version("uwot", version="0.1.9")
Downloading package from url: https://cran.ism.ac.jp/src/contrib/Archive/uwot/uwot_0.1.9.tar.gz
Installing package into ‘C:/Users/mikan/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'uwot' ...
** package 'uwot' successfully unpacked and MD5 sums checked
** using staged installation
** libs
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/R-40~1.4/include" -DNDEBUG -I../inst/include/ -I'C:/Users/mikan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppProgress/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/dqrng/include'     -DSTRICT_R_HEADERS -DRCPP_NO_RTTI   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/R-40~1.4/include" -DNDEBUG -I../inst/include/ -I'C:/Users/mikan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppProgress/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/dqrng/include'     -DSTRICT_R_HEADERS -DRCPP_NO_RTTI   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c connected_components.cpp -o connected_components.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/R-40~1.4/include" -DNDEBUG -I../inst/include/ -I'C:/Users/mikan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppProgress/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/dqrng/include'     -DSTRICT_R_HEADERS -DRCPP_NO_RTTI   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c nn_parallel.cpp -o nn_parallel.o
In file included from nn_parallel.cpp:6:
nn_parallel.h:80:64: error: wrong number of template arguments (4, should be 5)
              typename UwotAnnoyDistance::Distance, Kiss64Random>
                                                                ^
In file included from nn_parallel.h:29,
                 from nn_parallel.cpp:6:
C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include/annoylib.h:845:9: note: provided for 'template<class S, class T, class Distance, class Random, class ThreadedBuildPolicy> class AnnoyIndex'
   class AnnoyIndex : public AnnoyIndexInterface<S, T,
         ^~~~~~~~~~
In file included from nn_parallel.cpp:6:
nn_parallel.h: In constructor 'NNWorker<UwotAnnoyDistance>::NNWorker(const string&, const std::vector<double>&, std::size_t, std::size_t, std::size_t)':
nn_parallel.h:89:11: error: request for member 'load' in '((NNWorker<UwotAnnoyDistance>*)this)->NNWorker<UwotAnnoyDistance>::index', which is of non-class type 'int'
     index.load(index_name.c_str());
           ^~~~
nn_parallel.h: In destructor 'NNWorker<UwotAnnoyDistance>::~NNWorker()':
nn_parallel.h:93:11: error: request for member 'unload' in '((NNWorker<UwotAnnoyDistance>*)this)->NNWorker<UwotAnnoyDistance>::index', which is of non-class type 'int'
     index.unload();
           ^~~~~~
nn_parallel.h: In member function 'void NNWorker<UwotAnnoyDistance>::operator()(std::size_t, std::size_t)':
nn_parallel.h:104:13: error: request for member 'get_nns_by_vector' in '((NNWorker<UwotAnnoyDistance>*)this)->NNWorker<UwotAnnoyDistance>::index', which is of non-class type 'int'
       index.get_nns_by_vector(fv.data(), n_neighbors, search_k, &result,
             ^~~~~~~~~~~~~~~~~
make: *** [C:/R-40~1.4/etc/x64/Makeconf:229: nn_parallel.o] Error 1
ERROR: compilation failed for package 'uwot'
* removing 'C:/Users/mikan/Documents/R/win-library/4.0/uwot'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘C:/Users/mikan/AppData/Local/Temp/Rtmp4g3A3h/remotes408811ce2636/uwot’ had non-zero exit status
> library(devtools)
> library(RCurl)
> packageurl <- "https://cran.r-project.org/src/contrib/Archive/uwot/uwot_0.1.9.tar.gz"
> install.packages(packageurl, repos=NULL, type="source")
Installing package into ‘C:/Users/mikan/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/Archive/uwot/uwot_0.1.9.tar.gz'
Content type 'application/x-gzip' length 95756 bytes (93 KB)
downloaded 93 KB

* installing *source* package 'uwot' ...
** package 'uwot' successfully unpacked and MD5 sums checked
** using staged installation
** libs
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/R-40~1.4/include" -DNDEBUG -I../inst/include/ -I'C:/Users/mikan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppProgress/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/dqrng/include'     -DSTRICT_R_HEADERS -DRCPP_NO_RTTI   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/R-40~1.4/include" -DNDEBUG -I../inst/include/ -I'C:/Users/mikan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppProgress/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/dqrng/include'     -DSTRICT_R_HEADERS -DRCPP_NO_RTTI   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c connected_components.cpp -o connected_components.o
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/R-40~1.4/include" -DNDEBUG -I../inst/include/ -I'C:/Users/mikan/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppProgress/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include' -I'C:/Users/mikan/Documents/R/win-library/4.0/dqrng/include'     -DSTRICT_R_HEADERS -DRCPP_NO_RTTI   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c nn_parallel.cpp -o nn_parallel.o
In file included from nn_parallel.cpp:6:
nn_parallel.h:80:64: error: wrong number of template arguments (4, should be 5)
              typename UwotAnnoyDistance::Distance, Kiss64Random>
                                                                ^
In file included from nn_parallel.h:29,
                 from nn_parallel.cpp:6:
C:/Users/mikan/Documents/R/win-library/4.0/RcppAnnoy/include/annoylib.h:845:9: note: provided for 'template<class S, class T, class Distance, class Random, class ThreadedBuildPolicy> class AnnoyIndex'
   class AnnoyIndex : public AnnoyIndexInterface<S, T,
         ^~~~~~~~~~
In file included from nn_parallel.cpp:6:
nn_parallel.h: In constructor 'NNWorker<UwotAnnoyDistance>::NNWorker(const string&, const std::vector<double>&, std::size_t, std::size_t, std::size_t)':
nn_parallel.h:89:11: error: request for member 'load' in '((NNWorker<UwotAnnoyDistance>*)this)->NNWorker<UwotAnnoyDistance>::index', which is of non-class type 'int'
     index.load(index_name.c_str());
           ^~~~
nn_parallel.h: In destructor 'NNWorker<UwotAnnoyDistance>::~NNWorker()':
nn_parallel.h:93:11: error: request for member 'unload' in '((NNWorker<UwotAnnoyDistance>*)this)->NNWorker<UwotAnnoyDistance>::index', which is of non-class type 'int'
     index.unload();
           ^~~~~~
nn_parallel.h: In member function 'void NNWorker<UwotAnnoyDistance>::operator()(std::size_t, std::size_t)':
nn_parallel.h:104:13: error: request for member 'get_nns_by_vector' in '((NNWorker<UwotAnnoyDistance>*)this)->NNWorker<UwotAnnoyDistance>::index', which is of non-class type 'int'
       index.get_nns_by_vector(fv.data(), n_neighbors, search_k, &result,
             ^~~~~~~~~~~~~~~~~
make: *** [C:/R-40~1.4/etc/x64/Makeconf:229: nn_parallel.o] Error 1
ERROR: compilation failed for package 'uwot'
* removing 'C:/Users/mikan/Documents/R/win-library/4.0/uwot'
Warning message:
In install.packages(packageurl, repos = NULL, type = "source") :
  installation of package ‘C:/Users/mikan/AppData/Local/Temp/Rtmp4g3A3h/downloaded_packages/uwot_0.1.9.tar.gz’ had non-zero exit status
