### ISSUE TITLE
sample integration vs dataset integration

### ISSUE THREAD

**Issue by dm8000** [satijalab/seurat#4218]
Hello

I have noticed that articles integration is performed not only between datasets, but also between samples. This makes me question that if I want to integrate multiple datasets, integration between samples of each dataset is also necessary.

So if I want to use SCT integration of multiple datasets, should I first integrate the samples of each dataset, and only then integrate each dataset? Alternatively, could I merge all datasets, split by sample and then integrate each sample?

**Comment by torkencz** [comment]
Hi,

If I understand correctly you are asking the question we talk about in https://github.com/satijalab/seurat/discussions/3998
It is difficult to answer this without seeing your data. Both strategies you list should work, so you should try them out and see which suits your data the best.
