### ISSUE TITLE
Error with spatstat version 2.0

### ISSUE THREAD

**Issue by mihem** [satijalab/seurat#4221]
Hi,

after upgrading spatstat to the most recent version 2.0-1. https://cran.r-project.org/web/packages/spatstat/index.html, I get

`Error: package or namespace load failed for ‘Seurat’: object ‘markvario’ is not exported by 'namespace:spatstat'`

Downgrading spatstat to an earlier version, works as a workaround

`devtools::install_version("spatstat", version = "1.64-1", repos = "http://cran.us.r-project.org")`

Best,
Mischko

**Comment by baj12** [comment]
disabling upgrade after installing 1.64-1 helped for me.

```
devtools::install_github(repo = 'satijalab/seurat', dependencies = TRUE, ref = 'develop', upgrade='never')
```

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting. Going to close this issue just to consolidate responses in https://github.com/satijalab/seurat/issues/4226.

We are aware of this issue and working on submitting a fix to CRAN. In the meantime, this issue has been resolved on the develop branch of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
