### ISSUE TITLE
spatstat::markvario moved to spatstat.core in latest spatstat release

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#4222]
Hello,

Seurat depends on spatstat, including markvario(). spatstat just pushed a new release to cran (2.0-1). In spatstat 1.64-2, markvario is exported. In 2.0-1, markvario() is moved to spatstat.core. Would you consider updating seurat's DESCRIPTION to peg a specific spatstat version, or updating to 2.0-1? 

While existing R enlistments are fine, if anyone updates packages there's nothing to indicate in the code that Seurat 4 is incompatible with the latest spatstat. We noticed this b/c our github actions testing broke, which pulls the latest versions of packages.

Thanks

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting. Going to close this issue just to consolidate responses in https://github.com/satijalab/seurat/issues/4226.

We are aware of this issue and working on submitting a fix to CRAN. In the meantime, this issue has been resolved on the develop branch of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
