### ISSUE TITLE
Error: package or namespace load failed for ‘Seurat’:  object ‘markvario’ is not exported by 'namespace:spatstat'

### ISSUE THREAD

**Issue by star0044** [satijalab/seurat#4226]
I recently installed Seurat 4.0 along with R 4.0.4 on my Macbook Pro running OSX Big Sur v11.1.

I was able to load the Library(Seurat) and run multiple analyses.
It worked well until I installed the "limma" package to speed up the find clusters, and I selected "Yes" when it asked, Do you want to install from sources the package which needs compilation? (Yes/no/cancel)

Now I get the following error message when I try to load the Library(Seurat)

Error: package or namespace load failed for ‘Seurat’:
 object ‘markvario’ is not exported by 'namespace:spatstat'

I uninstalled R and re-installed and I re-installed R studio and re-installed Seurat and re-installed limma, but I'm still getting the error.

How can I fix this?

**Comment by kalmSveta** [comment]
I have a similar issue:
At first I was getting this error while installation of Seurat. But then I installed earlier version of spatstat. Th installation of Seurat finished successfully after that. But calling library(Seurat) provokes the same error now

**Comment by rekren** [comment]
I have faced with the same issue, too.
Downgrading the `spatstat` package or re-installing `Seurat` didn't work in my case, too.
Looking for a way the fix this issue.

**Comment by lldelisle** [comment]
Hi,
I got the same issue. `spatstat` just changed its package structure: `spatstat::markvario` become `spatstat.core::markvario`.
I also noticed that:
```
remove.packages(grep("spatstat", installed.packages(), value = T))
.rs.restartR()
devtools::install_version("spatstat", version = "1.64-1")
```
Solved the issue.

**Comment by stela2502** [comment]
AGH - had the same problem and also thought about installing from github, but then used 1.64-2 which obviously is the broken one. Thank you!

**Comment by star0044** [comment]
Thanks for the help,
The solution suggested  by Ildeslisle also solved my problem

remove.packages(grep("spatstat", installed.packages(), value = T))
.rs.restartR()
devtools::install_version("spatstat", version = "1.64-1")

Just a note, need to also be sure spatstat doesn't get automatically updated when installing other packages like SingleR and Scater

**Comment by zijianni** [comment]
Bioconductor sent me an email saying my package (depending on Seurat) was unable to build or install, and the error is exactly the same here and has been reported at #4222

**Comment by kokitsuyuzaki** [comment]
I got the same issue. 
My Bioconductor packages scTensor and scTGIF cannot be built with the error message below.

```
Error: package or namespace load failed for ‘Seurat’:
 object ‘markvario’ is not exported by 'namespace:spatstat'
Error: package ‘Seurat’ could not be loaded
Execution halted
```

**Comment by stela2502** [comment]
The spatstat people answered this:

"I'm sorry, but this is not a bug. The function has been moved to a sub package and the maintainer of Seurat has been informed and needs to update the package. The error will go away when this is done. Did you report the error to the maintainer?"

I have copied this answer here to finish up this discussion with as much info as I have.

Looking forward to the Seurat fix.

**Comment by vd4mmind** [comment]
I still have not been able to solve this. Tried to downgrade `statspat` but that did not help. I am on the Rstudio server and tried to create a new `.libPaths()` so as to install the downgraded package in a specific location and run it in my project followed by `Seurat` install and library load but that did not solve the issue. Unsure at this moment it's better to wait for Seurat maintainers to push their changes and wait or is there some other workaround that I might not be knowing?

**Comment by mojaveazure** [comment]
Hi all,

We are aware of this issue and working on submitting a fix to CRAN. In the meantime, this issue has been resolved on the `develop` branch of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1).

**Comment by demomwu** [comment]
> Hi,
> I got the same issue. `spatstat` just changed its package structure: `spatstat::markvario` become `spatstat.core::markvario`.
> I also noticed that:
> 
> ```
> remove.packages(grep("spatstat", installed.packages(), value = T))
> .rs.restartR()
> devtools::install_version("spatstat", version = "1.64-1")
> ```
> 
> Solved the issue.

excuse me ,i wonder how to "changed its package structure: spatstat::markvario become spatstat.core::markvario"?

**Comment by apelonero-GladstoneInstitutes** [comment]
> Hi all,
> 
> We are aware of this issue and working on submitting a fix to CRAN. In the meantime, this issue has been resolved on the `develop` branch of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1).

Thanks! Dev version fixed this for me. Out of curiosity, what is the go-to recommendation here? I see two solutions (as of today, prior to the CRAN update):

1. reinstall previous working version of spatstat (`devtools::install_version("spatstat", version = "1.64-1")` or similar)
2. install the latest dev release of Seurat (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1))

I ask since I know a few folks who kind of insist on running CRAN-flavor Seurat. Wondering what to tell them should they ask for some help 👍

**Comment by andrewwbutler** [comment]
Hi everyone,

An updated version (4.0.1) of Seurat is now available on CRAN and should resolve this issue. If you were having trouble installing previously, please try again with `install.packages("Seurat")`.

**Comment by JHYSiu** [comment]
Hi. I tried installing Seurat again (after deleting all the old spatstat packages). I'm now getting this error.

Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘spatstat’. 

If I then try to install the spatstat package, I get the original error back.

**Comment by skashin** [comment]
Hi Andrew

  Will you be able to submit a fix for the Seurat v3.2.3 to CRAN as well?

Thanks,
Seva

**Comment by andrewwbutler** [comment]
Hi Seva,

If you want to run Seurat v3.2.3, you will need to install the older version of `spatstat` as described in the thread above.

**Comment by skashin** [comment]
Hi Andrew,

  Right, I did this manually, and that works.

  But wouldn't it make sense to modify Imports in the v3.2.3 version, so
that instead of spatstat, you have
spatstat (== 1.64-1)?

Thanks,
Seva

**Comment by mojaveazure** [comment]
CRAN's policies prevent us from changing already-released versions. Moreover, CRAN does not allow pegging dependency versions to specific versions. The only management of dependencies we have is specifying minimum versions as R/CRAN has adopted a forward-looking model for dependency resolution (we have to be compatible with the latest-released version of each of our dependencies, and in some cases must be compatible with the development version as well).

If you wish to use an older version of Seurat, you will have to make sure that the versions of Seurat's dependencies you use are compatible with the version of Seurat you use. We unfortunately cannot provide more assistance than that.

**Comment by skashin** [comment]
Hi Paul,

 Thanks for your explanations!

 Maybe you could give a fair warning to the v3 users in the "Install
previous versions of Seurat", since anyone running
remotes::install_version("Seurat", version = "3.2.3") is very likely to hit
this error.

Best,
Seva
