### ISSUE TITLE
Normalization Error: Cannot add different number of cells than already present 

### ISSUE THREAD

**Issue by jurtlest** [satijalab/seurat#4228]
Hi All, 

I'm recently in the process of combining both mice and human scdata. However, I'm running into an error 
(Error: Cannot add different number of cells than already present ) on the normalization step. 

I've read multiple issue pulls and etc and still have no idea why it's occurring. I've checked the seurat object itself and see that the original number of cells 59824 matches with the object[['integrated']] number as seen below. 

The plan is to complete the NormalizeData, scaleData, FindVariableGenes on both mice and human datasets separately followed by intersect to run RunCCA. 

In short the moe object is created by SCT and integrating multiple runs of 10X. (I've removed the SCT and RNA assays as their cell count was previously not matching)

> moe
An object of class Seurat
3000 features across 59824 samples within 1 assay
Active assay: integrated (3000 features)
 2 dimensional reductions calculated: pca, umap
> moe[['integrated']]
Assay data with 3000 features for 59824 cells
Top 10 variable features:
 Bpifa1, Rgs5, Apoe, Reg3g, Olfr536, Sult1c1, Wfdc18, Olfr1507, Olfr727,
Scgb1c1
> moe <- NormalizeData(moe, normalization.method = "LogNormalize", scale.factor = 10000)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Cannot add a different number of cells than already present

Any of your expertise and help is greatly appreciated !!

**Comment by k3yavi** [comment]
Hi @jurtlest ,

Thanks for reaching out. It's not obvious to me what might be going wrong, is it possible for you to share the code/data you are using to perform the analysis ?

**Comment by RuiyuRayWang** [comment]
Hi, @Justice-Lu 
Take a closer look at the [integration vignette](https://satijalab.org/seurat/articles/integration_introduction.html).
If your DefaultAssay is set to 'integrated', you don't run NormalizeData() on the moe object. The vignette skips NormalizeData() and FindVariableFeatures(), and directly run from ScaleData().
The NormalizeData() only works is you're on other assays, i.e. 'RNA'.
