### ISSUE TITLE
Issue with 'imagerow' and 'imagecol' coordinates while adding/deleting spots

### ISSUE THREAD

**Issue by jnmark** [satijalab/seurat#4235]
Hello,

I am trying to remove some spots from a Seurat object based on a list (ListToRemove), for which I am essentially doing: seurat_object_deleted <- seurat_object_filtered[, !colnames(seurat_object_filtered) %in% ListToRemove]
However, this doesn't remove the spots from the 'imagerow' and 'imagecol' in seurat_object_deleted@images

Additionally, I am also trying to add back in some spots based on a list again (ListToAdd), for which I am doing: seurat_object_added <- seurat_object_original[, colnames(seurat_object_original) %in% ListToAdd]. This trims down the 'imagerow' and 'imagecol' in seurat_object_added@images to reflect the spots to be added.

seurat_object_original was filtered using subset = nCount_Spatial > X to result in seurat_object

My final goal is to merge the two using seurat_object_combined <- merge(seurat_object_deleted, y = seurat_object_deleted). The issue is:

1. Depending on the order of the objects in merge, the 'imagerow' and 'imagecol' only retain the coordinates of the first object.
2. Subsequently, when I try to use SpatialFeaturePlot to plot the spatial counts of seurat_object_combined, the plot doesn't reflect the spots in the second object.

The spots I want to add/delete cannot be achieved using a filter/subsetting based on a cluster etc., which is why it needs to be done manually.

Any thoughts on how this can be resolved? Really appreciate the help, thanks!

**Comment by torkencz** [comment]
Hi,

Unfortunately to my knowledge merging images via merging objects is not supported currently within Seurat. We will work on adding it in once our bandwidth allows.
