### ISSUE TITLE
Dotplot cannot show split.by colors

### ISSUE THREAD

**Issue by Lesdormis** [satijalab/seurat#4236]
Hi there, quick question here, why does my dotplot couldn't show the split color here even though I have provided with 3 more colors?
Here is my code:

DotPlot(obj.harm, features = c("TGFB1","TGFB2","TGFB3"),group.by = "celltype1",split.by = "site",cols = c("red", "blue", "green"),assay = "RNA")

and here is my figures:
![image](https://user-images.githubusercontent.com/30546732/111230092-fbb64000-8621-11eb-90a2-5925e1611d2a.png)

Thanks!
Best

**Comment by jaisonj708** [comment]
Hi, I was not able to reproduce this. Can you demonstrate on a publicly available dataset from `SeuratData` or send an object to seuratpackage@gmail.com?

Does the same issue occur when using a palette (eg, 'BrBG') instead of specifying colors?

**Comment by tovahmarkowitz** [comment]
Hi, I had the same problem with colors with the split.by dotplot. Using the palette instead solved the problem for me.
