### ISSUE TITLE
Scaling ("nUMI" or "percent.mito" ?) 

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#424]
Hi, 
Following the standard seurat routine at the scaling I set:

```R
read2 <- ScaleData(object = read1, vars.to.regress = c("nUMI", "percent.mito"))
```

, but I don’t really understand what is happening here; how will the data be regressed by _both_ variables?
What if I have larger percent.mito (partially for technical, but also for biological reasons, due to high metabolic activity)? Shall I only choose?:

```R
read3 <- ScaleData(object = read1, vars.to.regress = c("nUMI”))
```

When I do, I see some MT_ genes appearing among the HVGs. Which one should be the right approach in your opinion?

Thank you!
P

**Comment by satijalab** [comment]
Unfortunately we can't give detailed advice on any particular analysis. The regression with two variables works by constructing a linear model with two predictors.

One approach is to attempt dimensional reduction without regression, and to see if any of the components are highly correlated with technical features (like sequencing depth, or MT-percentage). If so, regression may be an appropriate step.
