### ISSUE TITLE
Integration of several multimodal datasets

### ISSUE THREAD

**Issue by alitinet** [satijalab/seurat#4241]
Hi,

I want to run Seurat v4 on several CITE-seq datasets, what would be the appropriate pipeline? As far as I understand, there's no way to specify batches in the `FindMultiModalNeighbors()` function? So ideally I want to get a WNN graph corrected for batch effects. Thanks!

**Comment by yuhanH** [comment]
Hi, 
You can do the batch correction in RNA and ADT modality respectively, and run WNN analysis for the batch-corrected RNA and ADT.  This is a similar issue: https://github.com/satijalab/seurat/issues/3890
