### ISSUE TITLE
FeaturePlot fixed pt.size with split.by

### ISSUE THREAD

**Issue by DadongZ** [satijalab/seurat#4242]
I am following this issue https://github.com/satijalab/seurat/issues/3052
I used split.by=variable in the FeaturePlot() and it turned out the point sizes are auto scaled for the two groups, though I have used pt.size =0.5. How can I force the two groups use same pt.size?

![size](https://user-images.githubusercontent.com/8431321/111388132-2a193700-8685-11eb-893c-519c492639f6.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  It looks like the issue actually might be that the plot on the right is being rasterized due to the number of points while the plot on the left is not.  What happens if you add `raster = FALSE` to the function?

Best,
Sam

**Comment by DadongZ** [comment]
Thanks! This is what I am looking for.
