### ISSUE TITLE
FindIntegrationAnchors - Error 'x' must be atomic 

### ISSUE THREAD

**Issue by jurtlest** [satijalab/seurat#4248]
I'm currently in the effort of combining mice and human scSeq datasets. I've done it multiple times but the mice and human cluster always struggles to intermingle. Hence I'm following another vignette here [https://satijalab.org/seurat/articles/integration_large_datasets.html](url)

I came across perhaps a bug in FindintegrationAnchors() ? I've seen a few posts in the past regarding to such bug but wasn't clearly addressed. 

> anchors <- FindIntegrationAnchors(object.list = data_list, reference = reference.list, reduction = "rpca", dims = 1:50)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=10s
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=18s
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :
  'x' must be atomic
> traceback()
6: stop("'x' must be atomic")
5: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4: sort.default(x = reference)
3: sort(x = reference)
2: unique(x = sort(x = reference))
1: FindIntegrationAnchors(object.list = data_list, reference = reference.list,
       reduction = "rpca", dims = 1:50)
`

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)
Matrix products: default
BLAS/LAPACK: /gpfs/fs1/data/common/seurat/miniconda3/envs/seurat31/lib/libopenblasp-r0.3.7.so
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
[1] dplyr_0.8.3  Seurat_3.1.0
loaded via a namespace (and not attached):
 [1] nlme_3.1-141        tsne_0.1-3          bitops_1.0-6
 [4] RcppAnnoy_0.0.13    RColorBrewer_1.1-2  httr_1.4.1
 [7] sctransform_0.2.0   tools_3.6.1         backports_1.1.5
[10] R6_2.4.0            irlba_2.3.3         KernSmooth_2.23-15
[13] uwot_0.1.4          lazyeval_0.2.2      colorspace_1.4-1
[16] npsurv_0.4-0        tidyselect_0.2.5    gridExtra_2.3
[19] compiler_3.6.1      plotly_4.9.0        caTools_1.17.1.2
[22] scales_1.0.0        lmtest_0.9-37       ggridges_0.5.1
[25] pbapply_1.4-2       stringr_1.4.0       digest_0.6.21
[28] R.utils_2.9.0       pkgconfig_2.0.3     htmltools_0.4.0
[31] bibtex_0.4.2        htmlwidgets_1.5.1   rlang_0.4.0
[34] zoo_1.8-6           jsonlite_1.6        ica_1.0-2
[37] gtools_3.8.1        R.oo_1.22.0         magrittr_1.5
[40] Matrix_1.2-17       Rcpp_1.0.2          munsell_0.5.0
[43] ape_5.3             reticulate_1.13     lifecycle_0.1.0
[46] R.methodsS3_1.7.1   stringi_1.4.3       gbRd_0.4-11
[49] MASS_7.3-51.4       gplots_3.0.1.1      Rtsne_0.15
[52] plyr_1.8.4          grid_3.6.1          parallel_3.6.1
[55] gdata_2.18.0        listenv_0.7.0       ggrepel_0.8.1
[58] crayon_1.3.4        lattice_0.20-38     cowplot_1.0.0
[61] splines_3.6.1       SDMTools_1.1-221.1  zeallot_0.1.0
[64] pillar_1.4.2        igraph_1.2.4.1      future.apply_1.3.0
[67] reshape2_1.4.3      codetools_0.2-16    leiden_0.3.1
[70] glue_1.3.1          lsei_1.2-0          metap_1.1
[73] data.table_1.12.4   RcppParallel_4.4.4  vctrs_0.2.0
[76] png_0.1-7           Rdpack_0.11-0       gtable_0.3.0
[79] RANN_2.6.1          purrr_0.3.2         tidyr_1.0.0
[82] future_1.14.0       assertthat_0.2.1    ggplot2_3.2.1
[85] rsvd_1.0.2          survival_2.44-1.1   viridisLite_0.3.0
[88] tibble_2.1.3        cluster_2.1.0       globals_0.12.4
[91] fitdistrplus_1.0-14 ROCR_1.0-7
`

**Comment by yuhanH** [comment]
Hi, 
Could you post the scripts you used containing normalization steps?

**Comment by jurtlest** [comment]
Hi Yuhan, 

The following codes are my steps leading up to finding anchors. 
merged_data.rds basically consist of multiple 10X and dropseq-dge seurat objects and combined simply by using merge(). 

``
data <- readRDS("/data/matsunamilab/justice/scSeq_Brann/seurat_obj/merged/merged_data.rds")
data <- GetAssayData(data, slot = "data")
data <- CreateSeuratObject(counts = data, project = "merged_trans", min.cells = 100, min.features = 500)
data <- SampIdent(data)

data_list <- SplitObject(data, split.by = "orig.ident")

data_list <- lapply(X = data_list, FUN = function(x) {
    x <- NormalizeData(x, verbose = FALSE)
    x <- FindVariableFeatures(x, verbose = FALSE)
})

features <- SelectIntegrationFeatures(object.list = data_list)
data_list <- lapply(X = data_list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})

#Using moe_0105 and Patient 1 as reference for anchors 
reference.list <- data_list[c("Moe_0105","Patient_1")]
anchors <- FindIntegrationAnchors(object.list = data_list, reference = reference.list, reduction = "rpca", dims = 1:50)

**Comment by yuhanH** [comment]
Have you changed the mouse gene name to match the human gene name? At lease, upper case the mouse gene name.

**Comment by jurtlest** [comment]
Yes, I have a gene list of homologs between human and mice. And only the genes that matches to the list are retained. And all human genes have been translated to lowercase

**Comment by yuhanH** [comment]
I think your ` reference = ` input is not correct. The input should be the number index of your reference object in the data_list. 
In your case, it should be `grep( pattern = "Moe_0105|Patient_1", x =  names(data_list)) `. 
If it still doesn't work, I will reopen this issue.

**Comment by jurtlest** [comment]
I did check the object 'reference'. And it does properly hold the 2 seurat objects of Moe_0105 and Patient _1. Or is the object reference NOT supposed to be an array of seurat object ?

**Comment by yuhanH** [comment]
right. The input of `reference` should be the index instead of a seurat object list.

**Comment by jurtlest** [comment]
Hi Yuhan,

Thank you so much for you prompted input and expertise. I have successfully integrated my objects. However, I have a last and rather more specific question. 

My goal is to intermingle and integrate the mice and human cluster together for further downstream analysis. However it seems like no matter how I integrate the samples together they still find their way to cluster away from each other as below. Could the problem stem from me using both human AND mice samples as the anchor references as you've pointed out above ?? 
![Capture](https://user-images.githubusercontent.com/69311740/111844422-6644d580-88d9-11eb-84be-96aaed5ada16.PNG)

Is there a more efficient way in fully integrating the 2 specie clusters ? I'm really trying to replicate the previously published satija lab fig. 4 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6700744/) 
![seufig](https://user-images.githubusercontent.com/69311740/111844433-6b098980-88d9-11eb-9b66-6d51719d06e0.PNG)

**Comment by yuhanH** [comment]
HI, @jurtlest 
For the multiple species integration, CCA will give you much better results than rpca.

**Comment by jurtlest** [comment]
Understood. I was originally pursuing RunCCA, but shortly realized that Seruatv3 no longer supports AlignSubSpace hence I resorted to integration. 

But I will proceed and try "CCA" in the FindIntegrationAnchors and hopefully see some difference ! 

Thank you so much Yuhan, you're awesome !

**Comment by AnwarKhan345** [comment]
Hello ~ I have two scRNA matrices and I want to integrate both the datasets. I am facing an error of x must be an atomic vector. Kindly help. 

Here is the script: 

matrix_3p=read.csv(file = "Data_patient_46_A.csv",header = TRUE,row.names = NULL)
rownames(matrix_3p)=matrix_3p$Patient.A
matrix_3p=matrix_3p[,-c(1,2)]

matrix_3p[is.na(matrix_3p)]=0
matrix_3p = as.data.frame(matrix_3p)

matrix_5p=read.csv(file = "Data_patient_45_B.csv",header = TRUE,row.names = NULL)
rownames(matrix_5p)=matrix_5p$Patient.B 
matrix_5p=matrix_5p[,-c(1,2)]

matrix_5p[is.na(matrix_5p)]=0
matrix_5p = as.data.frame(matrix_5p)

srat_3p   <- CreateSeuratObject(matrix_3p,project = "PATIENT_46")
srat_5p   <- CreateSeuratObject(matrix_5p,project = "PATIENT_45")

pbmc_list <- list()
pbmc_list[["PATIENT_46"]] <- srat_3p
pbmc_list[["PATIENT_45"]] <- srat_5p

for (i in 1:length(pbmc_list)) {
  pbmc_list[[i]] <- NormalizeData(pbmc_list[[i]], verbose = F)
  pbmc_list[[i]] <- FindVariableFeatures(pbmc_list[[i]], selection.method = "vst", nfeatures = 2000, verbose = F)
}

d=grep( pattern = "srat_3p|srat_5p", x =  names(pbmc_list))

pbmc_anchors    <- FindIntegrationAnchors(object.list = pbmc_list, reference = d,verbose = F)
