### ISSUE TITLE
SampleUMI removes row names and column names

### ISSUE THREAD

**Issue by ekernf01** [satijalab/seurat#425]
The title says it all. If you'd like, I could put in a pull request making `SampleUMI` preserve the dimnames. 

P.S. My lab recently finished a project and I had the opportunity to upgrade to Seurat 2.0. Love the new version! Session info is below.

```

 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-04-19                  

<other packages>
 Seurat            * 2.3.0      2018-03-23 CRAN (R 3.4.4)
<other packages>

```

**Comment by satijalab** [comment]
Thats great! Yes please do submit a PR and we'll accept

**Comment by kaizen89** [comment]
I think this is still present on v3
