### ISSUE TITLE
MultiCCA in Seurat 4.0.4

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#4254]
I am trying to duplicate my supervisor's code to introduce myself to Seurat and R.

I need to conduct a multiCCA analysis which she was able to do in Seurat 3.x using:

`Wittmann <- RunMultiCCA(object.list = Wittmann.list, genes.use = genes.use, num.cc=30)`

When I try to run the same line of code in Seurat 4.0.4, I get 

`Error in RunMultiCCA(object.list = Wittmann.list, genes.use = genes.use,  : 
  could not find function "RunMultiCCA"`

I know that Seurat uses RPCA instead of CCA but that is restricted to 2 object only and I need to compare more than three. Any idea how to do this in the new version of Seurat?

**Comment by timoast** [comment]
`RunMultiCCA` has been deprecated and now removed from Seurat, if you need to use that function you will need to install an  older Seurat release (v2). However, we support the integration of any number of datasets using the data integration methods available in the current Seurat release. Please see the online vignettes for information: https://satijalab.org/seurat/articles/integration_introduction.html
