### ISSUE TITLE
Add double-dipping-adjusted p-value to cluster results

### ISSUE THREAD

**Issue by gringer** [satijalab/seurat#4256]
A [new paper](https://arxiv.org/abs/2012.02936) as come out that claims to have found an approach that corrects for cluster definition bias when determining the likelihood of fit for a clustered dataset. It would be useful to include this statistic in the clustering results to help with determining a reasonable clustering of single-cell datasets.

The algorithm is implemented as an experimental R package, [`clusterpval`](http://www.lucylgao.com/clusterpval/AnyCluster.html); a tutorial for calculating clustered p-value on arbitrary datasets using this package is described [here](http://www.lucylgao.com/clusterpval/AnyCluster.html).

However, I'm not sure how I could get this working on our own single cell data. The tutorial mentions the calculating function using Monte Carlo sampling expects "a clustering function that takes a (*n* * *p*) numeric data matrix as input, and outputs integer assigments to clusters 1 through *k*", which will be run lots of times (e.g. 10,000) on a slightly-modified input dataset in order to generate distributions of the difference statistic.

Are the *FindNeighbors* / *FindClusters* functions fast enough to allow this to be done?

**Comment by satijalab** [comment]
This is a great idea and I really like this paper, but right now the workflow is not fast enough to run thousands of times to efficiently perform this correction procedure. We're exploring other ways to either implement this efficiently or achieve a similar goal, and will add to this issue if we have any updates

**Comment by joseph-siefert** [comment]
Any updates on this?
