### ISSUE TITLE
subscript out of bounds error in FindIntegrationAnchors

### ISSUE THREAD

**Issue by ucsdhusky** [satijalab/seurat#4262]
I am trying to analyze Covid 19 data sets from 17 different labs. When I was trying to find integration anchors, with the following code: 

```
pbmc.anchors=FindIntegrationAnchors(object.list=pbmc.list,anchor.features=features,reduction="rpca")
```
It shows the following error:
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=12s  
Computing within dataset neighborhoods
  |                                                  | 0 % ~calculating  Error in Embeddings(object = object.list[[x]][[nn.reduction]])[, dims] : 
  subscript out of bounds

How should I modify this? Thanks for your help.

**Comment by torkencz** [comment]
I would need a little more information to see what is wrong here. Here are some ideas of what could be happening:
Maybe you have shared cell names between the data sets? Seurat should however automatically check for that now (depending on what version you have). https://github.com/satijalab/seurat/issues/921 . Are your anchor features shared across all of you datasets? Alternatively, you can also try to change the number of dimensions used in each step and see how that goes.

**Comment by denvercal1234GitHub** [comment]
@ucsdhusky - Did you find the solutions?

**Comment by PingjunChen** [comment]
@ucsdhusky @torkencz  - Any solutions for this issue? On my data, I tried "cca" for the parameter **reduction**; it works but very slow. But when I changed the **reduction** parameter to "rpca", then obtained this "subscript out of bounds" error. Even in the previous operation **RunPCA**, I specified the embedded feature number of all batches to be the same by specifying the parameter **npcs**.

**Comment by dgagler** [comment]
@torkencz @PingjunChen @ucsdhusky I was having the same problem as you guys and was able to successfully run FindIntegrationAnchors() by specifying the number of dims to use to match the number of dims I used in my prior SCTransform PCA runs.

```
anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT", reduction = "rpca",
    anchor.features = features, dims = 1:20)
```
