### ISSUE TITLE
Using Monocle2, try to label the cell in each cluster based on the different orig.indent.

### ISSUE THREAD

**Issue by cli35** [satijalab/seurat#4264]
Hello, everyone,
I have a question on determine the cells that coming from two different origin.ident.
So i have combined two seurat project and the loaded into monocle2, and I got the pData as below:

orig.ident nCount_RNA nFeature_RNA percent.mt RNA_snn_res.0.5
B2.12W_AAACCCAGTTCCCACT-1 Mice EVAT 10x genomics 10568 3289 1.012491 0
B2.12W_AAACGAAGTTAGGCTT-1 Mice EVAT 10x genomics 8806 2998 1.601181 1
B2.12W_AAACGAATCATCGCCT-1 Mice EVAT 10x genomics 9874 3163 1.336844 B4.12W_AAACGAAGTTAGGCTT-1 Mice EVAT 10x genomics 8806 2998 1.601181 1
B4.12W_AAACGAATCATCGCCT-1 Mice EVAT 10x genomics 9874 3163 1.336844 0

which one group is B2.12W and the other is B4.12W, representing wt and ko
so I want to demonstrate the cell distribution on the cluster based on the orid.data, how could I do it?

**Comment by timoast** [comment]
Please ask this in the Monocle repository: https://github.com/cole-trapnell-lab/monocle-release
