### ISSUE TITLE
feature in SCT missing (return.only.var.genes=FALSE)

### ISSUE THREAD

**Issue by GHAStVHenry** [satijalab/seurat#4269]
SCTransform with `return.only.var.genes=FALSE`

but SCT assay has 11375 features not present in RNA assay

**Comment by ktrns** [comment]
SCTransform has a hidden parameter `min_cells` that determines the number of cells in which a gene needs to be expressed, or else it is excluded. 

See also here:
https://github.com/satijalab/seurat/issues/2128

Best
Katrin

**Comment by saketkc** [comment]
Hi @GHAStVHenry, as mentioned in the previous comment, `SCTransform` filters genes based on how many cells it is expressed in (to correctly estimate the dispersion parameter, this needs to be at least 3 but the default is 5). You can reduce `min_cells`, and set method to `method="glmGamPoi"`, if you want to retain most of the genes.
