### ISSUE TITLE
Installing v3.6.1

### ISSUE THREAD

**Issue by efitzgerald763** [satijalab/seurat#4271]
Hello, thank you for the great package! I want to reinstall version 3.6.1 to revisit some analysis I carried out using that version but I can't see it on CRAN. Any help on installing this would be much appreciated!

**Comment by Dragonmasterx87** [comment]
Hi @efitzgerald763 for a second I was like whoa did I miss something? I'm not a Seurat dev, but will try and help you. So Seurat wents from v3.2.3 to v4.0.0, to my knowledge 3.6.1 doesn't exist. I think you may be referring to R v3.6.1.

Anyway, generally if you want to install archived version 3 releases of Seurat you can use the following:
`# Replace X.X with version numbers`
`remotes::install_version("Seurat", version = "3.X.X")`

Also, look [here](https://satijalab.org/seurat/articles/install.html) for more info, and here for info on Seurat [versions/releases](https://github.com/satijalab/seurat/releases).

Hope that helps.

**Comment by efitzgerald763** [comment]
Me making a silly mistake is usually the answer, thanks for your help!!

**Comment by Dragonmasterx87** [comment]
> Me making a silly mistake is usually the answer, thanks for your help!!

Not at all @efitzgerald763 none of us were born knowing how to use R. Glad I was able to help. Cheers.
