### ISSUE TITLE
Inconsistent spot size for Spatial transcriptomics spatial plots

### ISSUE THREAD

**Issue by simoncmo** [satijalab/seurat#4272]
```r
# insert reproducible example here
```
Hi Satijalab Seurat team,

I found that the spot size is inconsistent across multiple integrated samples/slices using `SpatialPlot` function family. Currently ad-hoc solution for me is to plot them separately and set different `pt.size.factor` by eyeballing the size of the spots on each sample. I was wondering if there's a way to set the spot size to be a consistent value across samples/slices in the same integrated obj?
Some quick background for those sample slices, I'm currently using are 10x Visium system for my data and the inconsistency is observed on slices with various tissue coverages. i.e. slice with similar tissue coverage area also shows different spot size under the same `pt.size.factor` parameter sometimes.

Thanks,
Simon

**Comment by timoast** [comment]
The size of the spot plotted by default corresponds to the physical size of the spot in the experiment. If you have different physical spot sizes in relation to the size of the image taken, these would be plotted as different sized spots in Seurat. We have discussed internally and we want to keep this behaviour as it is, so I'd recommend adjusting the `pt.size.factor` manually if you really want the spot sizes to be similar across different spatial experiments.
