### ISSUE TITLE
Integrated spatial developmental analysis

### ISSUE THREAD

**Issue by simoncmo** [satijalab/seurat#4273]
Hi Seurat team,

I would appreciate some advice on the analysis strategy of Spatial data.
I have a spatial dataset with multiple developmental time points and is interested in
1. Finding temporal dependent expression patterns among all them 
2. I also have 2 conditions for each time points, and would also like to compare the difference between 2 condition at each time point.

For these purposes. What integration method would you recommend? The Spatial vignette only have workflow for 'merge' based integration, but in the integrated analysis for scRNA-seq vignette, anchor-based method was used to eliminate technical and batch effect. [https://satijalab.org/seurat/articles/integration_introduction.html](url) I was wondering if merge based workflow would be suffice in Spatial data for the downstream DE analysis?
Also since the dataset is large, would RPCA serve the purpose in lieu of anchor based method is the later to large to be obtained computationally?

Thanks,
Simon

**Comment by andrewwbutler** [comment]
Hi Simon,

If you have significant technical batch effects, the same anchoring workflow as in the scRNA-seq vignette can be used here to try and remove this effect to identify equivalent cell populations.  Generally, the same considerations that you have for RNA apply here for spatial datasets. If your dataset is large you can consider trying the RPCA workflow. This is still an anchor based workflow, the main difference is the dimensional reduction step used in determining the anchors (rpca vs cca) but you can read more about this [here](https://satijalab.org/seurat/articles/integration_large_datasets.html).
