### ISSUE TITLE
How to RenameCells() for only cells in a certain idents?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4275]
Hi there, 

I hope to change the cell name (barcode, rownames of my Seurat object) but specifically when the cells belong to a certain criteria of a meta.data column, e.g. orig.ident. 

Would anyone mind helping me with this? RenameCells() would only allow us to add pre-fix to all cells. 

Thank you so much for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team and there may be better solution.  But you could always use `SplitObject` based on the factor you are interested in and then automate the renaming by using `RenameCells` in an apply or map function with another list of names to add to each and then merge it all back together.

As side note though what is the rationale for changing the cell names based on a metadata column?  They don't modify any of the downstream analyses and are really just a unique id more than anything else.

Best,
Sam

**Comment by denvercal1234GitHub** [comment]
Thank you @samuel-marsh for your response! I will give it a try. 

The reason is because I have 3 donors that were merged into 1 Seurat object. The cell names (barcodes) has _1 at the end corresponding to donor 1, _2 for donor 2, and _3 for donor 3. 

In order for me to combine this Seurat object with scRepertoire clonotype data, I need to have a way to differentiate which data belong to which donor and ensure the barcodes between the Seurat object and the clonotype object are exactly the same.

**Comment by samuel-marsh** [comment]
Hi,

Ok that makes sense.  But doesn't the "_X" provide differentiating value?  Each donor already has its own identity specified in barcode.

Best,
Sam

**Comment by timoast** [comment]
I also don't understand what the goal is exactly, but the functionality exists in `RenameCells()` if you want to do it (use the `new.names` parameter)
