### ISSUE TITLE
Incompatibility with new umap-learn version

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#4276]
Hi Seurat team! 
I've installed the umap-learn package by: `pip3 install umap-learn`, which installs the umap-learn version 0.5.1. However, when I try to run the UMAP, it raises the following error:
```r
> raw <- read.table("/data/subset_ILCs_100.txt", row.names=1, header=TRUE)
> s <- CreateSeuratObject(raw)
> s <- SCTransform(s)
> s <- RunPCA(s)
> s <- FindNeighbors(s, graph.name="SNN", dims=1:20)
> s <- FindClusters(s, graph.name="SNN") 
> s <- RunUMAP(s, graph="SNN", umap.method="umap-learn")
Warning: The following arguments are not used: reduction.model, return.model, n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: simplicial_set_embedding() missing 3 required positional arguments: 'densmap', 'densmap_kwds', and 'output_dens'
```
Searching for this error, I've encountered that the problem may be due to changes between version 0.4.6 to versions > 0.5.0 ([link](https://github.com/theislab/scanpy/issues/1579)).

So I've installed the umap-learn v. 0.4.6 specifically by `pip3 install umap-learn==0.4.6` and it raises this error:
```r
> s <- RunUMAP(s, graph="SNN", umap.method="umap-learn")
Warning: The following arguments are not used: reduction.model, return.model, n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Error in RunUMAP.Graph(object = data.use, reduction.model = reduction.model,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).
```
Which I couldn't solve with previous solutions (#1020). I would prefer not to use conda to install it since I'm working on a docker and it would make the image much heavier. 

For now, I'm using the "uwot" method and it works fine. However, I was wondering what's the difference between the two methods and if it influences the results or not since the "umap-learn" method can be computed on graphs and the "uwot" not and, moreover, the "uwot" method needs the number of dimensions to use. 

My session info:
```r
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/local/R-4.0.4/lib/libRblas.so
LAPACK: /usr/local/R-4.0.4/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4
```
Operating system: Ubuntu 20.04 inside a Docker image.

My toy dataset: 
[subset_ILCs_100.txt](https://github.com/satijalab/seurat/files/6197543/subset_ILCs_100.txt)

Thanks for your work,
Marta.

**Comment by andrewwbutler** [comment]
Hi,

We have now updated Seurat to be compatible with umap-learn >= 0.5.0 on the `develop` branch (install instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)). Generally, uwot and umap-learn are interchangeable though there are some small implementation differences. You can read more about these on the uwot page [here](https://github.com/jlmelville/uwot/).
