### ISSUE TITLE
Excluding highly expressed genes for the calculation of the size factor for log normalisation

### ISSUE THREAD

**Issue by ktrns** [satijalab/seurat#4277]
Dear all, 

I am wondering whether you already have an option to exclude very highly expressed genes for the calculation of the normalisation (size) factor for each cell that is used for log normalisation?

I could not find anything related, but wanted to make sure before I incorporate Scanpy into my Seurat workflow. 
https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.normalize_total.html#scanpy.pp.normalize_total
(exclude_highly_expressed)

Best wishes and many thanks in advance
Katrin

**Comment by jaisonj708** [comment]
We don't have a function to do this but you can easily achieve this using `subset`. In general, a method like SCTransform is able to normalize data well for genes of both high and low expression.
