### ISSUE TITLE
no method for coercing this S4 class to a vector

### ISSUE THREAD

**Issue by somnathtagore** [satijalab/seurat#4278]
Hello,
I am trying to do run 'IntegrateData' function and getting the following error:

Computing 2000 integration features
Scaling features for provided objects
Finding all pairwise anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 4287 anchors
Filtering anchors
        Retained 2072 anchors
Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Error in as.character.default(new("Seurat", assays = list(RNA = new("Assay",  :
  no method for coercing this S4 class to a vector
Calls: saveRDS -> paste0 -> as.character -> as.character.default
Execution halted

-------------------------------------------------------------------------------
There are 2 samples (seurat objects, normalized) that I am trying to integrate: data_sample_1_seurat.rds and data_sample_2_seurat.rds 

-------------------------------------------------------------------------------
The code that I am using is:

pat_list <- c('sample_1','sample_2')

# Load objects
for (pat in pat_list) {
  assign(pat, readRDS(paste0('/home/ubuntu/','data_',  pat, '_seurat.rds')))
}

# Create object.list for integration
object.list <- NULL
for (obj in grep('SCLC_', ls(), value = T)) {
  object.list <- c(object.list, eval(parse(text = obj)))
}

# Find integration anchors
anchors <- FindIntegrationAnchors(object.list = object.list, dims = 1:30)

# Integrate data sets
seu <- IntegrateData(anchorset = anchors, dims = 1:30)

**Comment by timoast** [comment]
Can you show the output of `lapply(object.list, class)`? Also, is this the full code you're running? I'm confused because the call stack starts with `saveRDS` which is not in the code here
