### ISSUE TITLE
Differential expression for a cell cluster belonging to multiple replicates

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#4281]
Dear Seurat Team, 

I have several different datasets that represent 12 different replicates. The replicates are from different ages. The cell clusters dont easily distinguish on a plot by age, although there looks like some different genes are expressed in a given cluster but might be age  (replicate) dependent. Since I have 12 replicates, for a defined cluster, is there an easy way to extract out genes based on the replicates they came from? I tried looking at the immuno achors tutorial and that seems to be okay for 2 kinda data/replicates. The replicates and named cell clusters are stored as meta data. Any help would be appreciated. 
Many thanks.

**Comment by jaisonj708** [comment]
You can combine these into 1 metadata field, e.g:
``` object[['new.metadata']] <-  paste0(object[['cluster',drop=T]], '_', object[['replicate',drop=T]])```
