### ISSUE TITLE
Error of Installing the V3.2.3 seurat

### ISSUE THREAD

**Issue by Chen-Guanming** [satijalab/seurat#4283]
Hi all:
I have some problem in installing the old version seurat.
I tested many different methods to solve the problem but I can't. 
Would you help me?
Thanks!
 
my version information:
> sessionInfo()
  R version 3.6.0 (2019-04-26)
  Platform: x86_64-redhat-linux-gnu (64-bit)
  Running under: CentOS Linux 7 (Core)

  Matrix products: default
  BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
  
  locale:
   [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
   [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
  
  attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods   base     
  
  loaded via a namespace (and not attached):
   [1] BiocManager_1.30.10 processx_3.5.0      compiler_3.6.0      R6_2.5.0            assertthat_0.2.1    cli_2.3.1          
   [7] prettyunits_1.1.1   tools_3.6.0         glue_1.4.2          crayon_1.4.1        remotes_2.2.0       callr_3.5.1        
  [13] ps_1.6.0            pkgbuild_1.2.0      rlang_0.4.10       

when I used the code(remotes::install_version("Seurat", version = "3.2.3")), I will get the below information:

Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/Seurat/Seurat_3.2.2.tar.gz
Skipping 5 packages ahead of CRAN: abind, base64enc, colorspace, xtable, png
Installing package into ‘/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘Seurat’ ...
** package ‘Seurat’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c ModularityOptimizer.cpp -o ModularityOptimizer.o
ModularityOptimizer.cpp: In function ‘std::shared_ptr<ModularityOptimizer::Network> ModularityOptimizer::matrixToNetwork(IVector&, IVector&, DVector&, int, int)’:
ModularityOptimizer.cpp:761:7: warning: unused variable ‘n1_max’ [-Wunused-variable]
   int n1_max = *std::max_element(node1.cbegin(), node1.cend());
       ^
ModularityOptimizer.cpp:762:7: warning: unused variable ‘n2_max’ [-Wunused-variable]
   int n2_max = *std::max_element(node2.cbegin(), node2.cend());
       ^
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RModularityOptimizer.cpp -o RModularityOptimizer.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c data_manipulation.cpp -o data_manipulation.o
data_manipulation.cpp: In function ‘Eigen::SparseMatrix<double, 0, int> RowMergeMatricesList(Rcpp::List, Rcpp::List, std::vector<std::basic_string<char> >)’:
data_manipulation.cpp:151:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int j = 0; j < mat_vec.size(); j++) {
                                     ^
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c integration.cpp -o integration.o
integration.cpp: In function ‘Eigen::SparseMatrix<double, 0, int> FindWeightsC(Eigen::SparseMatrix<double, 0, int>, Rcpp::NumericVector, Eigen::MatrixXd, std::vector<std::basic_string<char> >, std::vector<std::basic_string<char> >, Eigen::MatrixXd, Eigen::VectorXd, double, double, bool)’:
integration.cpp:30:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=0; i<anchor_cells2.size(); ++i){
                                     ^
integration.cpp:48:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for(int j=0; j<mnn_idx.size(); ++j){
                                   ^
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c snn.cpp -o snn.o
gcc -m64 -std=gnu99 -I"/usr/include/R" -DNDEBUG  -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppEigen/include" -I"/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/RcppProgress/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c valid_pointer.c -o valid_pointer.o
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o Seurat.so ModularityOptimizer.o RModularityOptimizer.o RcppExports.o data_manipulation.o integration.o snn.o valid_pointer.o -L/usr/lib64/R/lib -lR
installing to /home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
Warning: namespace ‘Seurat’ is not available and has been replaced
by .GlobalEnv when processing object ‘pbmc_small’
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘markvario’ is not exported by 'namespace:spatstat'
Execution halted
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/home/chengm/R/x86_64-redhat-linux-gnu-library/3.6/Seurat’
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘/tmp/Rtmp6vTn2y/remotes292c375d71990/Seurat’ had non-zero exit status

**Comment by skashin** [comment]
Hi,

  I am getting the same error. Is there an easy way to fix it?

Thanks,
Seva

**Comment by Chen-Guanming** [comment]
Hi,


I not sure whether you are the same error with me, but you can see the #4226 which may be can help you if you error is&nbsp;Error: object ‘markvario’ is not exported by 'namespace:spatstat'.&nbsp;&nbsp;You can follow the method of user lldelisle, but you must not update packages when you install Seurat, because this error maybe happen due to the package&nbsp;spatstat changed the package structure.
&nbsp;
best wish,
Chen
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Seva ***@***.***&gt;;
Date: &nbsp;Wed, Mar 31, 2021 06:18 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: &nbsp;Re: [satijalab/seurat] Error of Installing the V3.2.3 seurat (#4283)

&nbsp;



 
Hi,
 
I am getting the same error. Is there an easy way to fix it?
 
Thanks,
 Seva

**Comment by skashin** [comment]
Hi Chen,

  Thanks, I will give it a try!

Best,
Seva
