### ISSUE TITLE
why Scale data with vars.to.regress = nCount_RNA

### ISSUE THREAD

**Issue by lizhaozhi** [satijalab/seurat#4285]
HI,

I have a question. I have seen people use ScaleData() with vars.to.regress = "nCount_RNA" which represent regress out the number of UMIs in cells. 
However, in the NormalizeData(). I thought the algorithm already divided by the nCount_RNA (number of UMIs in cells). 

**Why people regress out "nCount_RNA" again in ScaleData() when you already taken care of this in NormalizeData()?**
* ScaleData() was based on @ data slot instead of @ count slot.

Thanks

**Comment by jaisonj708** [comment]
Regressing out nCount-RNA is essentially another method of normalization, but if you want to model the effects of sequencing depth on counts, we strongly recommend using SCTransform instead.
