### ISSUE TITLE
IntegrateEmbeddings and Error: Cannot find assay

### ISSUE THREAD

**Issue by jogiles** [satijalab/seurat#4294]
Hello!

I have 2 Seurat objects from 2 experiments:
Exp 1: 10x scRNA-seq. Two assays slots: RNA, SCT
Exp 2: 10x multiome. Several assay slots: RNA, SCT, peaksList1, peaksList2, genomeBins.

I want to use the UMAP (and clusters) from the exp 1 (scRNA-seq) as a reference for the scRNA-seq data in the multiome data (experiment 2).

```r
DefaultAssay(scRNA) <- "SCT"
DefaultAssay(multi) <- "SCT"

scRNA <- RunUMAP(object = scRNA, dims = 1:48, seed.use = 123, return.model = TRUE)

anchors <- FindTransferAnchors(reference = scRNA, query = multi, normalization.method = "SCT",reference.reduction = "pca", query.assay = "SCT")

multi <- IntegrateEmbeddings(anchorset = anchors, reference = scRNA, query = multi, new.reduction.name = "ref.pca")
```

Error: Cannot find assay 'peaksList1' in this Seurat object

Even if I remove the peaksList1 assay -- I still get the same error!

Any help would be greatly appreciated!

Thank you!!!!

**Comment by timoast** [comment]
Can you try updating Seurat and Signac, then restarting R and see if you still have this issue?

**Comment by jogiles** [comment]
Updating each of the packages solved the issue. Thank you!
