### ISSUE TITLE
How to extract gene names expressed by at least 10% of cells in a cluster?

### ISSUE THREAD

**Issue by bieniu777** [satijalab/seurat#4295]
Hello,

I have a Seurat object with defined clusters. I need to extract a list of all genes that are expressed by at least 10% of cells in my cluster. I need to repeat it for every cluster that I have, separately.

I know one code that could potentially extract genes expressed by at least 10% of cells from the whole Seurat:

```
genes.to.keep <- Matrix::rowSums(Monocyte.integrated@assays$RNA@counts > 0) >= floor(0.1 * ncol(Monocyte.integrated@assays$RNA@counts))
counts.sub <- Monocyte.integrated@assays$RNA@counts[genes.to.keep,]
```
But this is not what I want. And I'm not sure how to modify it to include cluster names (assuming it's correct). I store the cluster names in the metadata variable called "cluster_names".

I would appreciate any help

BW

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can be helpful.  One way to do it would be to use the `FindMarkers` function but just set the various threshold parameters so low that the returned dataframe just contains all of the genes in dataset.  Can then easily just filter result on pct.1.

Best,
Sam
