### ISSUE TITLE
Why analysis DEGs/ markers or calculating gene expression level using un-integrated data?

### ISSUE THREAD

**Issue by DiracZhu1998** [satijalab/seurat#4297]
Dear developer, 

    Why analysis DEGs/ markers or calculating gene expression level using un-integrated data? 
I didn't figure it out. May you explain it?

Best wishes.

**Comment by andrewwbutler** [comment]
Hi,

Please see [this](https://github.com/satijalab/seurat/discussions/4000) discussion thread.
