### ISSUE TITLE
A strange phenomenon in the process of cluster analysis

### ISSUE THREAD

**Issue by Dragonlongzhilin** [satijalab/seurat#4299]
I analyzed my data with following code:
set.seed(101)
T.cells <- RunPCA(T.cells, verbose = FALSE)
set.resolutions <- seq(0.2, 1.2, by = 0.1)
T.cells <- RunHarmony(object = T.cells, group.by.vars = "orig.ident", assay.use="SCT", dims = 1:30, verbose = FALSE)
T.cells <- FindNeighbors(T.cells, dims = 1:30, reduction = "harmony", verbose = FALSE)
T.cells <- FindClusters(T.cells, resolution = set.resolutions, verbose = FALSE)
T.cells <- RunUMAP(T.cells, reduction = "harmony", dims = 1:30, verbose = FALSE, min.dist = 0.15)

I found that the clustering result produced by running the code for the first time was
![image](https://user-images.githubusercontent.com/33304280/112851695-cf98c580-90dd-11eb-883d-57938a665b60.png)

The confusing thing was that when I re-run this code , I get the following different result:
![image](https://user-images.githubusercontent.com/33304280/112851216-58fbc800-90dd-11eb-91b1-e8a1197de269.png)
After the second execution, no matter how many times it was repeated, the clustering result was not change and remain the same as the second time.
I don‘t know why？

**Comment by torkencz** [comment]
The explanation off the top of my head for this that I can think of is that you did not run set.seed(101) the first time but afterwards you did. That will keep you UMAP, tSNE etc. consistent.

**Comment by Dragonlongzhilin** [comment]
I have carefully confirmed that I did run the set.seed(101) in the first execution. I guess the problem may come from RunHarmony, but I haven’t found a certain reason yet.
