### ISSUE TITLE
Weighted Nearest Neighbor Analysis for only 2 CITE-seq Abs

### ISSUE THREAD

**Issue by Shinlee419** [satijalab/seurat#4301]
Hi, I am trying to learn the Weighted Nearest Neighbor Analysis Vignette and analyze our CITE-seq data. But since we only used two CITE-seq antibodies, I cannot really get another dimensional reduction for the "ADT" in the Vignette. Thus I don't know how to apply the FindMultiModalNeighbors function, for which I think two dimensional reductions are needed. (the runPCA does not work for my two Abs sequencing results). Does anyone know any other way to get around the second dimensional reduction and use the Abs reads directly for wnn? Thanks a lot!

![Screen Shot 2021-03-29 at 14 58 48](https://user-images.githubusercontent.com/79279783/112885910-45ca0780-909f-11eb-8468-96738579aa73.png)

**Comment by yuhanH** [comment]
HI @Shinlee419 
The WNN method doesn't work for the small number of antibody panel.  You may concatenate the two normalized adts to the RNA data.
