### ISSUE TITLE
not getting same subpopulations as original authors after integration

### ISSUE THREAD

**Issue by dm8000** [satijalab/seurat#4302]
Hello

I have been trying to integrate a few adipocyte datasets. When I get their available data and cluster the cells, I usually get similar subpopulations as they did. However, I tried to integrate them with a few other datasets, but these subpopulations are apparently being lost. I have tried it by following the vst and SCT integration tutorials, but cell groups that were quite separated on each datasets are very close after integration regardless. I have tried increasing the number of features and PCs (which worked on individual datasets). I'm out of ideas for tuning it.

**Comment by jaisonj708** [comment]
This sounds like over-integration, but I am surprised that you are losing entire cell populations. I would follow our vignettes line-by-line to diagnose the issue (perhaps using log-normalization to start). If it's still an issue, using RPCA instead of CCA should help with this.
