### ISSUE TITLE
Export Seurat Data into 1 csv file and select specific clusters of interest

### ISSUE THREAD

**Issue by aliciahillturner** [satijalab/seurat#4305]
I am trying to export my data from Seurat by cell cluster. The below code works so far, but it exports each cluster into a separate .csv file and I need it all in 1 csv file. In addition, there are 11 clusters total but I only want to extract 5 of the clusters (i.e. Ductal1, Ductal2, Macrophage1, Macrophage2, Macrophage3), so I am also unsure how to do that!

"Patients" is my Seurat object for reference!

#Exporting as Counts File

meta.data.cluster <- unique(Idents(Patients))

for(group in meta.data.cluster) { group.cells <- WhichCells(object = Patients, idents= group) data_to_write_out <- as.data.frame(GetAssayData(Patients,slot = 'counts')[,group.cell]) write.table(data_to_write_out,row.names=TRUE,col.names=TRUE, file = paste0(group, "_cluster_countfile.txt"), sep='\t', quote=F) }

In addition, here is a screenshot of my Seurat Object:
![image](https://user-images.githubusercontent.com/73973890/113015686-c9d9c900-914b-11eb-9459-a80b18bb388e.png)

I am new to coding so any help would be greatly appreciated!

**Comment by aliciahillturner** [comment]
This worked perfectly! Thanks so much @samuel-marsh this was a huge help!

**Comment by samuel-marsh** [comment]
Happy to help!
