### ISSUE TITLE
HELP! Integrated scRNA and spatial analysis question

### ISSUE THREAD

**Issue by cvw462** [satijalab/seurat#4306]
Hi Seurat Team,

I'm at a novice in ngs analysis so this might be a silly question but I'd love your input. As the title implies, my goal is to integrate scrna and spatial data. But the scrna dataset was not processed using Seurat but instead was log-normalized using edgeR and cells were clustered and visualized using KNNPM and tSNE plots. 
In order to do the integration, my understanding is that I need the rds file (expression matrix + metadata) from the scrna dataset, is this correct? 
Currently from the scrna anaylsis,I just have the cell cluster metadata file (cell ID, tsne values, and description of cluster ID). I'm super stumped on what steps do I need to take to go from metadata to Seurat object? So I can integrate it with spatial information.

Thank you so much!

**Comment by jaisonj708** [comment]
If you have the expression matrix (say `mtx`) and metadata matrix/dataframe (say `md`), all you need to do is load these into your R session and use the command `CreateSeuratObject(mtx, meta.data=md)`. If you only have a metadata file without an expression matrix or at least a dimensional reduction like PCA, it would not make sense to create a Seurat object.
