### ISSUE TITLE
Conversion of seurat object to loom doesn't function

### ISSUE THREAD

**Issue by wajm** [satijalab/seurat#4309]
Attempting to convert a seurat object to a loom object as suggested in the conversion_vignette.Rmd vignette produces a error.

> packageVersion("Seurat")
[1] ‘4.0.1’
> packageVersion("loomR")
[1] ‘0.2.1.9000’
> packageVersion("hdf5r")
[1] ‘1.3.3’

> pt.loom <- as.loom(patient, filename = "pt.loom", verbose = FALSE)
Error in as.loom(patient, filename = "pt.loom", verbose = FALSE) :   could not find function "as.loom"

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can be helpful.  See most up to date vignette detailing the SeuratDisk package for conversions involving loom format.
[https://satijalab.org/seurat/articles/conversion_vignette.html](https://satijalab.org/seurat/articles/conversion_vignette.html)

Best,
Sam

**Comment by wajm** [comment]
> Hi,
> 
> Not member of Dev team but hopefully can be helpful. See most up to date vignette detailing the SeuratDisk package for conversions involving loom format.
> https://satijalab.org/seurat/articles/conversion_vignette.html
> 
> Best,
> Sam

yes, I've already checked. but not working as.loom function.

**Comment by samuel-marsh** [comment]
Hi,

Do you have the SeuratDisk package installed in loaded in the environment?

Best,
Sam

**Comment by wajm** [comment]
> Hi,
> 
> Do you have the SeuratDisk package installed in loaded in the environment?
> 
> Best,
> Sam

Sorry, I don't realize the dependancy of SeuratDisk package.
Thanks.

**Comment by samuel-marsh** [comment]
No problem!
