### ISSUE TITLE
Convert RNA Velocity into Seurat object

### ISSUE THREAD

**Issue by cvw462** [satijalab/seurat#4310]
Hi All,

I'm trying to integrate scrna seq with spatial data. Is it possible to convert RNA velocity (rdata) into a seurat object ? 

Thanks again!

**Comment by saketkc** [comment]
Hi @cvw462, iit is certainly possible to do celocity analysis in Seurat, see this [vignette](https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/velocity.html). I am not sure if this answers your question, feel free to reopen.
