### ISSUE TITLE
[FindConservedMarkers] conserved markers shared by 2 celltypes?

### ISSUE THREAD

**Issue by hartmannmark** [satijalab/seurat#4313]
Hello, 

I want to use the `FindConservedMarkers` function to characterise the similarity between selected celltypes and identify shared marker genes, respectively.

For this purpose I define `Idents(obj) <- "celltype"`.

But I am not sure, what to use for the grouping variable, which needs to be defined. 

```
cons <- FindConservedMarkers(obj, 
                                       ident.1 = "celltype.1", 
                                       ident.2 = "celltype.2", 
                                       grouping.var = ??)
```

When I define the grouping variable with a variable that is shared by both celltypes, just to get the function running, I get the message: 
**Warning: Only a single group was tested**

Also the marker gene list is way longer than expected.

I guess I am doing something substantially wrong and would appreciate any help a lot! 
Thanks in advance.

**Comment by hartmannmark** [comment]
P.S. When I run 

`FindConservedMarkers(obj, 
                                   ident.1 = "celltype.1", 
                                   ident.2 = "celltype.2", 
                                   grouping.var = "group", 
                                   verbose = TRUE)`

the readout is obviously the DEGs between the two celltypes rather than the similarities.

**Comment by torkencz** [comment]
Hi,

This explains pretty well when to use Find Conserved markers: https://www.biostars.org/p/409790/ . In this case I am not fully sure why you use it. If you have a shared change (e.g.: Stimulation, drug treatment etc.) then you can apply this function and for the grouping variable add the shared change. If you are trying to find shared markers between cell type 1 and 2 I would just create a group with both cell types included as one category and compare them to the rest of the cells (or other groups you want compared).

**Comment by garrettb44** [comment]
Hi there. Sorry for reopening this issue, but I have a question regarding your answer @torkencz. 

I want to perform something similar, ie. find common markers between 2 clusters in my dataset. If I were to use code such as:

conservedmarkers <- FindMarkers(SeuratObjects, ident.1 = c(1,2), ident.2 = c(3,4,5,6,7,8), min.pct = 0.25)

If there were markers that were significantly enriched in cluster 1, but not in cluster 2 couldn't that sway this analysis? If a marker had high enough expression in cluster 1 could it compensate for an absence of expression in cluster 2? I hope this makes sense!

Thanks!!
