### ISSUE TITLE
IntegrateData() Output

### ISSUE THREAD

**Issue by wolf5996** [satijalab/seurat#4317]
Thank you for creating this amazing scRNA-Seq analysis toolkit.

In the documentation of the **IntegrateData()** function, you state the following:

> Returns a Seurat object with a new integrated Assay. If normalization.method = "LogNormalize", the integrated data is returned to the data slot and can be treated as log-normalized, corrected data. If normalization.method = "SCT", the integrated data is returned to the scale.data slot and can be treated as centered, corrected Pearson residuals.

I have specified **normalization.method = "SCT"**. After integration, I check the **data** slot of the integrated assay, and I find that it is not empty. What exactly is returned in that slot?

Also, what operation do I need to apply to acquire the corrected, normalized **(but not log-transformed)** counts after integration?

The reason I am asking is that I need the untransformed count matrix in downstream pseudotime analysis using slingshot and tradeSeq.

**Comment by be16242** [comment]
To continue my analysis, I have checked the density of the counts in the **data** slot of the **integrated assay**, and they seem to be log1p-normalized, corrected counts (likely the same output as specifying the **normalization.method = "LogNormalize"**). To reverse the log transformation and obtain the corrected, untransformed counts, I have applied the **expm1()** on the **data** slot and assigned the output to the empty **counts** slot of the **integrated assay**.

Please do let me know if I have got this wrong.

**Comment by jaisonj708** [comment]
After integration using SCT-normalized counts, the `data` slot will contain non-centered Pearson residuals and the `scale.data` slot will contain the centered residuals.

Transforming post-integration residuals to corrected counts is not supported/tested, but if you absolutely have to do this, refer to the `sctransform::correct_counts` function in the SCT case or use `expm1` in the log case. Again, this is not necessarily encouraged.

**Comment by wolf5996** [comment]
@jaisonj708 Thank you very much for the quick reply. I do have a few follow-up questions:
1. How should I use `sctransform::correct_counts` to transform post-integration residuals to corrected counts? What inputs do I need to pass in? I have looked at the documentation but couldn't figure it out. Would you mind providing an example.
2. `expm1()` would reverse the transformation if `normalisation.method = "LogNormalize"` argument of `FindIntegrationAnchors()` and `IntegrateData()`. Is that correct?
3. During the integration pipeline for **SCTransform**, the Seurat vignette states that `normalisation.method = "SCT"` should be set in the `FindIntegrationAnchors()` and `IntegrateData()`. What would happen if I do not specify this argument? What would happen if I leave it for the default value of `normalisation.method = c("LogNormalize","SCT")`? To clarify, here is my code according to the Seurat Vignette:
```
##SCTransform, Integration features, and preparation of data for integration
HCC1806.list <- lapply(X = HCC1806.list, FUN = SCTransform, method = "glmGamPoi")
features <- SelectIntegrationFeatures(object.list = HCC1806.list, nfeatures = 3000)
HCC1806.list <- PrepSCTIntegration(object.list = HCC1806.list, anchor.features = features)
HCC1806.list <- lapply(X = HCC1806.list, FUN = RunPCA, features = features)


##Integration Anchors and Data Integration
HCC1806.anchors <- FindIntegrationAnchors(object.list = HCC1806.list,
                                          anchor.features = features,
                                          dims = 1:30,
                                          reduction = "rpca",
                                          k.anchor = 5,
                                          normalization.method = "SCT")

HCC1806I <- IntegrateData(anchorset = HCC1806.anchors, 
normalization.method = "SCT")
```
Here is the code that I suggest (the only difference is that `normalization.method` is deleted or commented out):
```
##SCTransform, Integration features, and preparation of data for integration
HCC1806.list <- lapply(X = HCC1806.list, FUN = SCTransform, method = "glmGamPoi")
features <- SelectIntegrationFeatures(object.list = HCC1806.list, nfeatures = 3000)
HCC1806.list <- PrepSCTIntegration(object.list = HCC1806.list, anchor.features = features)
HCC1806.list <- lapply(X = HCC1806.list, FUN = RunPCA, features = features)


##Integration Anchors and Data Integration
HCC1806.anchors <- FindIntegrationAnchors(object.list = HCC1806.list,
                                          anchor.features = features,
                                          dims = 1:30,
                                          reduction = "rpca",
                                          k.anchor = 5,
#                                          normalization.method = "SCT")

HCC1806I <- IntegrateData(anchorset = HCC1806.anchors, 
# normalization.method = "SCT")
```
Does removing the `normalization.method = "SCT"` argument above affect how these functions work or can Seurat infer the normalisation method used implicitly? The reason I am asking is that running this code above (without the `normalization.method` argument) produces an integrated assay that has a data slot populated with log-transformed counts, which I could easily reverse using `expm1()`. The benefit of doing this to using the standard LogNormalize pipeline is that I could take advantage of better normalisation with SCT, and I would be able to obtain the corrected count matrix easily with `expm1()` (as opposed to working with `sctransform::correct_counts`, which I am not comfortable with).

**Comment by shivUSF** [comment]
Did you find the solution which actually worked?

**Comment by pranavm2109** [comment]
Hello @jaisonj708 I have a very quick question: if while integrating multiple Seurat object that had been processed until and including the NormalizeData() phase with the log normalization method, if I were to not specify anything in the IntegrateData()'s normalization.method parameter, will there be values returned in the counts slot and the data slot? If so, will the counts values be integrated and the data values be integrated AND normalized? Just wanted to clarify.

**Comment by bioshot-dotcom** [comment]
Related to this discussion, it is not clear which is the real default value of the normalization.method parameter. It seems to me that LogNormalized values are returned in the data slot, but if it is like this it is not clear in the documentation in my opinion.
