### ISSUE TITLE
extracting normalized counts using different methods - not a duplicate of how to extract counts

### ISSUE THREAD

**Issue by amjass12** [satijalab/seurat#4319]
Hi, 

I have been extracting normalized counts from my seurat objects as follows:

`norm_counts<-as.data.frame(object[['RNA']]@data)`

I have noticed in the documentation, the (convenience?) function is `GetAssaydata`

but have also noticed others extract as follows `object@assay[['RNA']]@data`

I have tested each way with ALL producing identical dataframes (as determined by base R function `identical()`)

Is one method preferred over the others? as in - can one lead to erroneous extraction of the data, or are all ok ways of doing it? I have had no issues with extracting normalized counts, but slightly confused at the different ways it can be done. 

thanks

**Comment by jaisonj708** [comment]
`GetAssayData` might be the cleanest, but they're all the same, so you can choose whatever floats your boat
