### ISSUE TITLE
Workflow for subclustering a SCTransform-normalized integrated object

### ISSUE THREAD

**Issue by GailleJoo** [satijalab/seurat#4320]
Hi Seurat Team @yuhanH @timoast @satijalab 

Below are the procedures I summarized for subclustering a SCTransform-normalized integrated object, but I'm not sure they're correct or not.

**Approach 1:**  
Just re-run PCA, UMAP, FindNeighbors and FindClusters for simplification:
1. Subset the SCTransform-normalized integrated object
2. Run PCA on the subset integrated assay
3. Run UMAP, FindNeighbors and FindClusters using the new PC dimensions

**Approach 2:**  
Re-run SCTransform to identify better variable features to describe the subset clusters without integration:
1. Subset the SCTransform-normalized integrated object
2. Run SplitObject to split the the subset object into a list of samples
3. Run SCTransform seperately for each sample using the RNA assay
4. Run SelectIntegrationFeatures to select new variable features
5. Run PCA on the subset integrated assay using the new set of variable features
6. Run UMAP, FindNeighbors and FindClusters using the new PC dimensions

**Approach 3:**  
Re-run SCTransform and integration if the subset clusters still contain many heterogeneities:
1. Subset the SCTransform-normalized integrated object
2. Run SplitObject to split the the subset object into a list of samples
3. Run SCTransform seperately for each sample using the RNA assay
4. Run SelectIntegrationFeatures to select new variable features
5. Run PrepSCTIntegration, FindIntegrationAnchors and IntegrateData to integrate all datasets using the new set of variable features ()
6. Run PCA on the subset integrated assay using the new set of variable features
7. Run UMAP, FindNeighbors and FindClusters using the new PC dimensions

My questions are:
1. Will these three approaches work? especially approach 1 and 2. What's your suggestion about subclustering a SCTransform-normalized integrated object?
2. If re-run SCTransform after subsetting the object, should re-run integration or not? In my opinion, if don't re-run integration, the scaled data stored in subset integrated assay for dimensional reduction would not be changed. So, for approach 2, just the intersection between the new and previous variable features will be used for dimensional reduction.

Thanks!

**Comment by jaisonj708** [comment]
Re-running SCTransform or at least re-centering Pearson residuals is probably a good idea. While the underlying model for technical noise shouldn't change after you subset, SCTransform learns genewise dispersion parameters and centers the data, which is kind of analogous to "scaling" before PCA. So re-doing this step could be helpful. As you correctly point out, re-running SCT will also help you identify a better set of variable features. In practice, this may or may not not make a huge difference in the amount of biological variation you pick up. (If it does make a noticeable difference, re-running integration might also be a good idea.)
