### ISSUE TITLE
FindVariableFeatures algorithm computation understanding

### ISSUE THREAD

**Issue by matth786** [satijalab/seurat#4322]
Hi, I would like to understand the algorithm behind
`FindVariableFeatures(pbmc,` selection.method = "vst", nfeatures = `2000)`

My understanding : This function compute a score for each gene to select the 2000 bests for the next step, the PCA. For a gene, the more variability in the counts matrix for each cells the better. The Seurat Algorithm is described in the following paper : https://www.biorxiv.org/content/biorxiv/early/2018/11/02/460147.full.pdf
page 12 : Feature Selection for better dataset

What I understand :

1. For each gene they compute the mean and variance of not normalized UMI and apply log10 for var and mean
2. If we plot var in function of mean we should have something similar to a line so they perform a polynomial regression (order 2)
3. they recompute an other variance using mean and the last regression

if you follow the tutorial https://satijalab.org/seurat/archive/v3.2/pbmc3k_tutorial.html just before FindVariableFeatures you can display first line of count matrix :

    `data_counts <- GetAssayData(object = pbmc, slot = "counts")`
    `print(head(data.frame(data_counts ), 1))`

which gives u a line with AL627309.1 and nine counts with 1 in each count

just after you can display the results of FindVariableFeatures:

`print(head(HVFInfo(object = pbmc),23))`

which gives u

    mean variance variance.standardized
    AL627309.1 0.0034116755 0.0034013253 0.9330441
    AP006222.2 0.0011372252 0.0011363627 0.9924937
    RP11-206L10.2 0.0018953753 0.0018925002 0.9627290

How can have a mean and a variance of 0.0034 with an array of [1,1,1,1,1,1,1,1,1] ? mean([1,1,1,1,1,1,1,1,1]) = 1 log10(1) = 0
i have seen a part of the source code here : https://rdrr.io/cran/Seurat/src/R/preprocessing.R but it doesn't help me
it is a technical question but if someone have an idea of how mean and var is computed it will be a pleasure to understand.

Kind regards

Matt

**Comment by timoast** [comment]
> How can have a mean and a variance of 0.0034 with an array of [1,1,1,1,1,1,1,1,1] ? mean([1,1,1,1,1,1,1,1,1]) = 1 log10(1) = 0

You're only looking at the first few cells here, there are many more. Here's a reproducible example computing the mean and variance for the first gene in the pbmc3k dataset manually and with `FindVariableFeatures()`:

```r
library(Seurat)
library(SeuratData)
data("pbmc3k")

gene1counts <- GetAssayData(pbmc3k, assay = "RNA", slot = "counts")[1, ]
mean(gene1counts)
# 0.003333333
var(gene1counts)
# 0.003323453
pbmc3k <- FindVariableFeatures(pbmc3k)
head(HVFInfo(pbmc3k))
```
```
                     mean    variance variance.standardized
AL627309.1    0.003333333 0.003323453             0.9294859
AP006222.2    0.001111111 0.001110288             0.9977442
RP11-206L10.2 0.001851852 0.001849107             0.9621691
RP11-206L10.9 0.001111111 0.001110288             0.9977442
LINC00115     0.006666667 0.006624676             0.9022607
NOC2L         0.106666667 0.158310485             0.7780061
```
