### ISSUE TITLE
puzzled result of functions CellCycleScoring and FindMarkers

### ISSUE THREAD

**Issue by duocang** [satijalab/seurat#4326]
Hi.

Vignette [Cell-Cycle Scoring and Regression](https://satijalab.org/seurat/articles/cell_cycle_vignette.html) has presented a great example to perform cell cycle assignment.

**I go one step more to test the correctness of functions `CellCycleScoring` and `FindMarkers`. I found negative results and it puzzles me now.**

```r
marrow <- CellCycleScoring(marrow, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
marrow <- RunPCA(marrow, features = c(s.genes, g2m.genes))
```

**I use `FindMarkers` to compare/calculate the marker genes between `G1` and `S`-`G2M` cells.**

```r
markers <- FindMarkers(marrow, ident.1 = "G1", ident.2=c("S", "G2M"))
g1 <- markers %>% filter(pct.1>0.9 & pct.2 < 0.7)
g1
```
```r
[1] p_val     avg_logFC pct.1     pct.2     p_val_adj
<0 rows> (or 0-length row.names)
```
I found that almost all `markers` are present in `G1` cells, also in `S`-`G2M` cells. It indicates that `FindMarkers` did not give me any specific genes for `G1` cells but we start with cells in different cycles by `CellCycleScoring` ( `g1.genes`, `G2M.genes`).

What is happening? How should I decipher the coupling between `pct.1` and `pct.2` from `FindMarkers`?
<img src="https://user-images.githubusercontent.com/14146871/113491182-2849d300-94cf-11eb-88ff-8abb1bb10b71.png" alt="image" style="zoom:30%;" />

**Comment by jaisonj708** [comment]
You may want to check the `data` slot in your object. These outputs indicate that your data matrix is not sparse at all and that all/most values are non-zero.
