### ISSUE TITLE
Integrating Data:  Keeping All Features in the integrated assay

### ISSUE THREAD

**Issue by RobertWhitener** [satijalab/seurat#4327]
Hi,

I'm currently working through integrating two Seurat Objects (DATASET_1 and DATASET_2) to do a joint analysis. These are two datasets that have a *wide* variety of cell types

However, I'm running into some issues.

Machine:
Windows 10 machine, RStudio, Seurat v 4.0.1, R version 4.0.3, up to date dependencies

```{r Merge, Anchor, and Integrate}
MERGED <- merge(x = DATASET_1, y = DATASET_2, merge.data = TRUE)

MERGED_LIST <- SplitObject(MERGED, split.by = "DATASET")

for (i in 1:length(MERGED_LIST)) {
    MERGED_LIST[[i]] <- NormalizeData(MERGED_LIST[[i]], verbose = FALSE)
    MERGED_LIST[[i]] <- FindVariableFeatures(MERGED_LIST[[i]], selection.method = "vst", nfeatures = 2000, verbose = FALSE)
}

MERGED_ANCHORS <- FindIntegrationAnchors(object.list = MERGED_LIST, dims = 1:30)

MERGED <- IntegrateData(anchorset = MERGED_ANCHORS, dims = 1:30, new.assay.name = 'integrated')

#Set default to the integrated data
DefaultAssay(MERGED) <- "integrated"
```

The first issue, is that after integrating and setting the DefaultAssay to "integrated", 
```
VariableFeaturePlot(MERGED)  
```
returns:  Error:  Unable to find highly variable feature information for method VST.

AND
```
VariableFeaturePlot(MERGED, assay = 'integrated')  
```
does the same, but

```
head(VariableFeatures(MERGED))

#and

head(MERGED@assays$integrated@var.features)
```
clearly indicate there are genes listed.

This is fine, since I don't really need to plot that right now.  So I continued with Scaling, etc:

```
MERGED <- ScaleData(MERGED, features = all_genes)
MERGED <- RunPCA(MERGED, verbose = FALSE)
MERGED <- FindNeighbors(MERGED, dims = 1:21, verbose = FALSE)
MERGED <- FindClusters(MERGED, verbose = FALSE, resolution = 0.1) 
MERGED <- RunUMAP(MERGED, dims = 1:21, verbose = FALSE)
```

However, further downstream in the analysis, when trying to look at some marker genes to do cell type classification, I'm running into issues where some marker genes that very much should be variable, are not being found in the integrated data.

For example, PECAM1 is found within the integrated data and causes no issues, but both PTPRC and PDGFRA are "not found in the integrated data", and was only found in the RNA assay, while 

This is causing issues in visualizing the data when trying to graph signature genes: 

```
DotPlot(MERGED, features = c('PTPRC','PECAM1','PDGFRA'), col.min = 0, col.max = 3.0, cluster.idents = FALSE) + 
  coord_flip() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
        axis.title.y = element_blank(),
        panel.background = element_rect(fill = 'transparent', color = NA),
        plot.background = element_rect(fill = 'transparent', color = NA)
        )
```

Outputs a DotPlot that has only two features, 'PECAM1', and 'NA', where the 'PTPRC' and 'PDFGRA' dots are drawn on top of each other. (below)

![image](https://user-images.githubusercontent.com/47307011/113612509-cd19fc80-9604-11eb-9ed5-42a90c521150.png)

So I did some investigating:
```
> 'PECAM1' %in% DATASET_1@assays$RNA@counts@Dimnames[[1]]
[1] TRUE

> 'PECAM1' %in% DATASET_2@assays$RNA@counts@Dimnames[[1]]
[1] TRUE

> 'PECAM1' %in% MERGED@assays$integrated@counts@Dimnames[[1]]
[1] FALSE

> 'PECAM1' %in% MERGED@assays$integrated@var.features
[1] TRUE

> 'PTPRC' %in% DATASET_1@assays$RNA@counts@Dimnames[[1]]
[1] TRUE

> 'PTPRC' %in% DATASET_2@assays$RNA@counts@Dimnames[[1]]
[1] TRUE

> 'PTPRC' %in% MERGED@assays$integrated@counts@Dimnames[[1]]
[1] FALSE

> 'PTPRC' %in% MERGED@assays$integrated@var.features
[1] FALSE

> length(rownames(MERGED@assays$RNA))
[1] 41079
> length(rownames(MERGED@assays$integrated))
[1] 2000
```

So it looks like the Integration is only keeping the highly variable genes (2,000), instead of scaling "all_genes", as I would normally do.

Am I doing something wrong?  Any help with getting this sorted out would be greatly appreciated.  Right now, this is only a test run, as I will be integrating much larger datasets in the future and just wanted to get familiar with this process.

**Comment by timoast** [comment]
> returns: Error: Unable to find highly variable feature information for method VST.

See https://github.com/satijalab/seurat/issues/4018

> So it looks like the Integration is only keeping the highly variable genes (2,000), instead of scaling "all_genes", as I would normally do.

This is the normal (and documented) behaviour. See the documentation for `IntegrateData()`, in particular the `features.to.integrate` parameter. Note that we don't recommend using the integrated data for differential expression or visualization

**Comment by aj088** [comment]
@timoast Hi, I am also having integrated data that only keeps top 2000 variable features. I wonder if what data you suggest to use for differential expression or visualization? Thanks
