### ISSUE TITLE
Read in TPM count table from GEO for use in Seurat pipeline

### ISSUE THREAD

**Issue by DRSEI** [satijalab/seurat#4328]
I'm an R beginner trying to learn how to analyze single-cell seq data using Seurat tools. I wanted to try to work with a published Smart-seq2 count dataset available via GEO:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120575

I've encountered three errors trying to load this data into R: 1. melonoma<- read.table("GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt", sep = "\t")#row.names=1)
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 16293 elements

so I changed to  > melonoma<- read.table("GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt", sep="\t", header=T, row.names=1)

I got this error
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 16293 elements

then i chnage to melonoma<- read.table("GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt",sep=",",header=T,row.names=1)

no error but when i run dim(melonoma) 
i have 55738 gene but no cells 
[1] 55738     0

I am unable to read any TPM txt file from GEO for using the Seurat pipeline. So does anybody have any tips on how to load in large single-cell seq TPM txt or CSV files for use in the Seurat pipeline? 

Thank you!

**Comment by Dragonmasterx87** [comment]
Hi @DRSEI first of all I am not a Seurat dev,

It seems this is a R related issue not an issue with Seurat, but I will help you since this is your first issue ever 😃 
First of all please look here to read more on [reading data](https://www.datacamp.com/community/tutorials/r-data-import-tutorial) types into R.

Now I'm not sure why there is a missing row, but when you perform `fill = TRUE` it seems like a dataframe is created fine.
Here is what I did:

```
# Reading GSE120575 into R
GSE120575 <- read.table("~/GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt", fill = TRUE, header = TRUE, sep = "")
dim(GSE120575)
```

The output of `dim(GSE120575)` is:
```
dim(GSE120575)
[1] 55738 16291
```

```
# Looking at a limited form of the data:
GSE120575[1:10, 1:10]
         A10_P3_M11 A11_P1_M11 A11_P3_M11 A11_P4_M11 A12_P3_M11 A12_P6_M11 A2_P1_M11 A2_P4_M11 A3_P1_M11 A3_P3_M11
Pre_P1       Pre_P1     Pre_P1     Pre_P1     Pre_P1     Pre_P1     Pre_P1    Pre_P1    Pre_P1    Pre_P1    Pre_P1
TSPAN6         0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
TNMD           0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
DPM1           0.00       9.24       0.00       7.99       0.00       0.00      0.00      0.00      8.44      0.00
SCYL3          0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
C1orf112       0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
FGR            0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      8.24      0.00
CFH            0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
FUCA2          0.00       0.00       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
GCLC           0.00       1.01       0.00       0.00       0.00       0.00      0.00      0.00      0.00      0.00
```

The creator knows what this "Pre_P1 is :) but im guessing the cell names and genes are okay. Since all the gene names are there I think it should be okay for you (the lengths of the gene dims are the same as what you have).

If you wanto get rid of this Pre_P1 nonsense use this:

```
GSE120575 <- GSE120575[-c(1), ]
dim(GSE120575) # check data
[1] 55737 16291 # different number of genes same number of cells
```

Cheers,
🐲

**Comment by DRSEI** [comment]
Thank you so much this is very useful

**Comment by saketkc** [comment]
Thanks @Dragonmasterx87!   The default workflows in Seurat assume you have a counts matrix to start off with. If you are using a TPM matrix, the data is already normalized so you can skip normalization. See https://github.com/satijalab/seurat/issues/668 and linked issues for details.

**Comment by Dragonmasterx87** [comment]
sorry @saketkc  you are absolutely right should have mentioned that as well.
