### ISSUE TITLE
Repetitive error with Seurat methods

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#4330]
Dear all,

I repeatedly see error messages likes this one when working with Seurat:
[[<- defined for objects of type "S4" only for subclasses of environment

This happens after loading certain packages (SeuratDisk, DESeq2). I posted this already: #4227 and #3964.
Apparently, quite some users experienced this and I can tell you that it is quite annoying. Usually, I could solve it by unloading another package as mentioned. But sometimes it is not clear which additionally loaded package is causing this. Is this behaviour of Seurat with other packages solved in the newest version?

Thx, Chris

**Comment by vertesy** [comment]
Just encountered it too. No fix so far.

**Comment by timoast** [comment]
Can you include the output of `sessionInfo()`?

You could also try re-installing SeuratDisk and see if that solves the issue

**Comment by balthasar0810** [comment]
I will post a sessionInfo() output as soon as the error reappears. As I said, it occurs randomly. Sometimes it is associated with the loading of certain packages (SeuratDisk, DESeq2) and sometimes it can be resolved by unloading them. Right now, it work fine with both of them loaded...

Anyways: What does this error mean??? Does it mean that some S4 method is overwritten by the method of another package? Is this a name conflict thing?


Best, Chris

**Comment by timoast** [comment]
I am not entirely sure what causes this error, but in my experience it has been a result of a situation such as the following:

1. Install package A that defines a class X
2. Install a second package B defines class Y that inherits from X
3. Update package A that moves the class definition of X and moves the definition to a new package C
4. Package B gets very confused about where the class X is defined and gives this error

This happened with Seurat v4 as the SeuratObject class definition was moved to a separate package. However, there is a simple fix for this which is re-installing any packages that use the class whose definition has moved.
