### ISSUE TITLE
Scaling with SCTransform

### ISSUE THREAD

**Issue by lvlahos343** [satijalab/seurat#4331]
In the default arguments of SCTransform, the default arguments center the data but do not scale it. Given this choice, is the `scale.data` object generated from the SCTransform appropriate to use either in downstream machine learning analyses (i.e. classification) or as an internally normalized gene expression signature for GSEA? Or should SCTransfrom be run with `scale.data = True` for these applications? 

A similar question was asked in the issue linked below w.r.t. downstream PCA, with an answer linking to a paper on biorxiv. I couldn't find a concrete explanation for why scaling was not performed by default in the SCTransform function in that paper, however.

https://github.com/satijalab/seurat/issues/1777

**Comment by saketkc** [comment]
`scale.data` in SCT assay are pearson residuals. We do not recommend using these for classification tasks downstream since they are not comparable across datasets (unless you use the same SCT model - the gene mean to dispersion relationship across datasets).
