### ISSUE TITLE
Seurat 4 Installation Problem in Ubuntu 20.04

### ISSUE THREAD

**Issue by robin1-2** [satijalab/seurat#4333]
Hi, I am trying to install Seurat in Ubuntu 20.04. 
I got these messages and severel others similar to these. 

ERROR: dependencies ‘sctransform’, ‘RcppEigen’ are not available for package ‘SeuratObject’
* removing ‘/usr/local/lib/R/site-library/SeuratObject’
Warning in install.packages :
  installation of package ‘SeuratObject’ had non-zero exit status
ERROR: dependencies ‘igraph’, ‘irlba’, ‘leiden’, ‘lmtest’, ‘png’, ‘Rtsne’, ‘sctransform’, ‘SeuratObject’, ‘spatstat.core’, ‘spatstat.geom’, ‘uwot’, ‘RcppEigen’ are not available for package ‘Seurat’
* removing ‘/usr/local/lib/R/site-library/Seurat’
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpCGrIgy/downloaded_packages’

----
SessionInfo: 

R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=tr_TR.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=tr_TR.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=tr_TR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=tr_TR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5

**Comment by timoast** [comment]
It looks like some dependencies failed to install (sctransform, RcppEigen, SeuratObject), can you try getting those installed first and then see if you still have any issues installing Seurat?

**Comment by martings** [comment]
Failure to install SeuratObjects breaks everything.

SeuratObject requires these devs to be installed: `sudo apt install libgeos-dev`

And then install in R

```
install.packages("rgeos")
install.packages("SeuratObject")
```

work for me

**Comment by Hui-XiangZhang** [comment]
> Failure to install SeuratObjects breaks everything.
> 
> SeuratObject requires these devs to be installed: `sudo apt install libgeos-dev`
> 
> And then install in R
> 
> ```
> install.packages("rgeos")
> install.packages("SeuratObject")
> ```
> 
> work for me

For Mac it is  “brew install geos”
