### ISSUE TITLE
dimplot as table

### ISSUE THREAD

**Issue by rojinsafavi** [satijalab/seurat#4334]
I was wondering if there is a way to get the output of this analysis as a table?

![image](https://user-images.githubusercontent.com/19545198/113934833-12782e80-97ab-11eb-8900-708f768b67bd.png)

**Comment by liuxl18-hku** [comment]
Not sure all, but most of Seurat plot is based on ggplot2 (+ patchwork).

To get the table you want, we can get the data.frame used for ggplot2. A general idea of doing that was suggetsed by @mojaveazure in (this post)[https://github.com/satijalab/seurat/issues/257#issuecomment-354324002].

But for DotPlot (based on figure you attached, thought you said DimPlot in the title), a more specific way could be:

```r
library(Seurat)
library(tidyverse)

gg_data <- DotPlot(...)@data # not run

# the Seurat::DotPlot contains two pieces of information in each dot: (Scaled) Average Expression and Percent Expressed)

# 1. table for Average Expression (by default, Seurat::DotPlot using scaled value for that
scaled_avg_exp_table <- gg_data %>% select(c("id", "feature.plot", "scaled.avg.exp")) %>% reshape2::dcast(., id ~ feature.plot, valur.var = "scaled.avg.exp")

# 2. table for Percent Expressed
exp_pct_table <- gg_data %>% select(c("id", "feature.plot", "exp.pct")) %>% reshape2::dcast(., id ~ feature.plot, valur.var = "exp.pct")
``` 

The variable name in `gg_data` may not be exactly what they should look like, but I think they are self-explanatory, good luck.

bless~
Xingliang
