### ISSUE TITLE
Package Request: Add Seurat wrapper to R Targetopia

### ISSUE THREAD

**Issue by TomKellyGenetics** [satijalab/seurat#4335]
<img src="https://user-images.githubusercontent.com/5493325/113976201-b4674c00-987b-11eb-9189-3b671866abff.png" width="200" height="200" />

The [targets](https://docs.ropensci.org/targets/) R package on [ ROpenSci GitHub](https://github.com/ropensci/targets) is a Make-like pipeline toolkit to make reproducible pipelines in R (which superceeds [drake](https://github.com/ropensci/drake)). A Seurat targets package would be greatly beneficial to extend Seurat functionality to run reproducible single-cell analysis. Would it be possible to add a Seurat-based package for single-cell analysis to the [R Targetopia](https://wlandau.github.io/targetopia/packages.html)? I'd be open to contribute but Seurat core developers may have better ideas on how to implement this and support future features in development.

**Comment by saketkc** [comment]
Thanks @TomKellyGenetics for suggesting this! While we don't have the bandwidth in the team to do this, we will be happy to provide support you if you decide to pursue this!

**Comment by TomKellyGenetics** [comment]
Thanks for considering it. I wish I could but I'm quite busy with other projects at the moment as well. I will update this thread if I have time later. Of course, I'd be interested to know if anyone else tries doing it.

**Comment by timoast** [comment]
Closing this for now as no one will be actively working on it. Feel free to comment if/when this is implemented.
