### ISSUE TITLE
Comparing clusters of two different populations sequenced from different biological samples

### ISSUE THREAD

**Issue by amr15** [satijalab/seurat#434]
Hi,

I have samples from two different biological regions, and am hoping to integrate them.  When I use CCA to merge them, as expected, I find that if there were x different clusters of cell type A in sample one and y different clusters of cell type B in sample 2, in the merged sample there are z different clusters of cell type A (based on marker genes).  If I'm looking to compare the x different clusters of cell type A in sample one to the y different clusters of cell type A in sample 2, do you recommend merging the raw UMI matricies from both samples and clustering? 

Thanks!
Anu

**Comment by satijalab** [comment]
If you have pre-defined clusters based on independent analysis of the two datasets, you can use MergeSeurat to merge the datasets, and then perform differential expression testing

**Comment by amr15** [comment]
Thanks! Just wondering if this is still fair if I expect there to be a subset of the cells in one sample in the other sample.  MergeSeurat separates the samples by tissue of origin, and it's unclear if this is a batch effect or biological.  Canonical correlation analysis to combine the samples matches up similar cell types (ex: endothelial cells) from each sample nicely.

**Comment by tulikakakati** [comment]
Hi,
Please correct me, if I am wrong.
I have two different samples of scRNAs (Normal and Disease). First I created two seurat objects (n and d) and then merged them using merge(n,d).  I used the merged_object further for differential expression analysis after clustering.  I used FindMarkers(merged_object, ident.1 = id, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE) function to find the marker genes for each cluster represents the differentially expressed genes. 
My queries to you are as follows:
1. the cell clusters composed of cells from both normal and disease samples. So do the markers we found from these clusters signify the differentially expressed genes between normal and disease cells or between different clusters of merged objects.

Thank you
