### ISSUE TITLE
# of UMIs per feature

### ISSUE THREAD

**Issue by SJayYang** [satijalab/seurat#4343]
Is there a function to find the number of UMIs per feature? Or a place within the Seurat object where I could find the UMI per cell per feature?

**Comment by saketkc** [comment]
You can plot the raw counts using FeaturePlot:

```r
VlnPlot(object = pbmc_small, features = 'LYZ', split.by = 'groups', assay = "RNA", slot = "counts")
```

The values themselves can be obtained using:
```r
cm <- GetAssayData(pbmc_small, assay="RNA", slot="counts")
cm["LYZ",]
```

Total UMIs per cell is in `nCount_RNA`:

```r
pbmc_small$nCount_RNA
```

**Comment by SJayYang** [comment]
Just to confirm, the unique # of UMIs corresponds exactly to the read count for a gene, correct?

**Comment by saketkc** [comment]
This depends on your input. This is assuming, your input was UMI to start off with - Seurat does not convert read counts to UMIs.

**Comment by SJayYang** [comment]
Thank you for your help!
