### ISSUE TITLE
question for parameter (ident.1 ) in function FindMarkers 

### ISSUE THREAD

**Issue by BMEngineeR** [satijalab/seurat#4344]
Hi Seurat Team,

FindMarkers function (Seurat V.3.2.2) provides a very flexible way to calculate DEGs between different cell group comparisons. For sample, I can directly use cell ID to specify group 1 (controlled by ident.1) and group 2 (controlled by ident.2). However, I found if I provide character(0) as ident.1 value, the program will continue to run and will not be aborted. 
Here is the code. my.2_5.object.layer2 is a group of cells.
![image](https://user-images.githubusercontent.com/26455910/114119712-2f028c80-98b9-11eb-906e-ad308e84c034.png)
![image](https://user-images.githubusercontent.com/26455910/114119987-a9331100-98b9-11eb-9d4e-d98d022f5a36.png)
However, If I use NULL as input of ident.1, the program will be aborted.
Here are the code and output.
![image](https://user-images.githubusercontent.com/26455910/114124952-81e14180-98c3-11eb-8270-b8d5aa9b7389.png)

Q1. Why it will still run if ident.1 does not have any cells?
Q2. Which cells are chosen in such a comparison?

Thank you!

**Comment by jaisonj708** [comment]
This follows the behavior of `WhichCells` which seems to use all cells if `character(0)` is passed into `idents`
