### ISSUE TITLE
RunUMAP seed.use 

### ISSUE THREAD

**Issue by shexiaolu** [satijalab/seurat#4345]
Thanks for your great job in this package Seurat!
I have met some questions when I use the RunUMAP()
I need to change the  UMAP graph to make it better to present.But no matter how I change the seed.use ,the plot remains the same .This is my code below:
`RunUMAP(NKT,reduction = 'harmony',dims = 1:20,min.dist = 0.5,seed.use = 123)`
really appreciated for your reply!

**Comment by saketkc** [comment]
Hi @shexiaolu,  I am unable to reproduce this issue with Seurat v4.0.1:

```r
pbmc_small <- RunUMAP(object = pbmc_small, dims = 1:5, seed.use=42)
DimPlot(object = pbmc_small, reduction = 'umap')
```
![image](https://user-images.githubusercontent.com/682153/114192864-f6e06580-991b-11eb-9c27-a1de51d3867f.png)

```r
pbmc_small <- RunUMAP(object = pbmc_small, dims = 1:5, seed.use=420)
DimPlot(object = pbmc_small, reduction = 'umap')
```

![image](https://user-images.githubusercontent.com/682153/114192966-12e40700-991c-11eb-9b05-d903810d3266.png)

P.S. The goal of `seed.use` is to ensure reproducibility.
