### ISSUE TITLE
Using WNN on data gene expression data along with CITE-seq data

### ISSUE THREAD

**Issue by vkjain0006** [satijalab/seurat#4347]
Hi all,

I have this issue of running Gene expression data along with other CITE-seq data. We have 20 samples sequenced via CITE-seq method and other 12 samples which are just gene expression and no protein data available for them. 
We could successfully run WNN analysis on first 20 samples, but when we integrate all 32 samples together, then protein info doesn't show up. Only assays that are shown are:- RNA and integrated and ADT one is not there, but it's there when I used only CITE-seq data. 

Is there a way I can integrate all 32 samples and still retain protein info of the 20 samples, and then run WNN on all 32 samples ?

Would creating a pseudo protein data for the 12 samples with 0 counts in it, be a good idea ? So that I can run WNN then on all 32 samples.

Please share your thoughts and if there's a way to run get around this issue. 

Thanks!

**Comment by torkencz** [comment]
Hi WNN is supposed to be run co-assay data, so your samples which have no ADT are going to bias it. I am not sure if creating a pseudo protein data is the right way to go. You might want to consider running WNN on the CITE-seq data and then projection you RNA only samples onto it. Alternatively, you could impute ADT for the RNA only data and then do WNN, but that might bias your results towards the CITE-seq samples.

**Comment by vkjain0006** [comment]
Thanks @torkencz for your reply and sharing how we should go about it. 
As per the suggestion , we would go ahead with projecting cells with protein data on all combined data and see where we have that cells expressing particular protein in a combined data. 
We might miss using WNN as such, but that's okay since we need all the data to go ahead with.
