### ISSUE TITLE
memory allocation error in CreateSeuratObject / CreateAssayObject

### ISSUE THREAD

**Issue by micans** [satijalab/seurat#4348]
Hi, below is a bug report for very large data.  The byte count reported in the exit message is suggestive of some sort of calculation going wrong, possibly due to mixing integer types at a low level. The data is very large, but we consistenly have the setting where the code works flawlessly for a sparse matrix with X entries (here X=752160877), and fails consistenly when there are approximately 25% more entires (here 1030941338). When it fails, the error message is `'Realloc' could not re-allocate memory (18446744065871126528 bytes)` -- this number seems weirdly large.  Actually this seems very similar to (this issue)[https://github.com/Rdatatable/data.table/issues/2777] where the cause was _just an overflow to negative then cast to size_t, that's why compiler was ok with it._
Our context below.

In our [cellatac](https://github.com/cellgeni/cellatac) pipeline we get this error:

```
Error in asMethod(object) :
  'Realloc' could not re-allocate memory (18446744065871126528 bytes)
Calls: CreateSeuratObject -> CreateAssayObject -> as -> asMethod
Execution halted
```
We get it consistently if we allow our input to grow too large. The input is described by
- number of genomic windows (200000 in this case)
- number of cells (91614 in this case)
- number of entries in the sparse matrix (1030941338 in this case)

The code works (consistently) if we limit the genomic windows to 100k. In that case the numbers listed are 100000, 91614, and 752160877.
The matrix is read using

```
f_binary_mat <- readMM(file = 'mmtx/filtered_window_bc_matrix.mmtx.gz')
regions.names = read.delim('mmtx/regions.names', header = FALSE, stringsAsFactors = FALSE)
cell.names = read.delim('mmtx/cell.names', header = FALSE, stringsAsFactors = FALSE)
colnames(f_binary_mat) = cell.names$V1
rownames(f_binary_mat) = regions.names$V1

### Make binary: 1 if there is any Tn5 cut site for each single barcode that map within each window
if( class(f_binary_mat) != 'ngTMatrix')
  f_binary_mat@x[f_binary_mat@x > 0] <- 1

### Load cell calling from cellranger
metadata <- read.csv(file = 'singlecell.csv', header = TRUE, row.names=1, sep="\t")

### Creating a Seurat object using the windows/cell matrix
so <- CreateSeuratObject(
  counts = f_binary_mat,
  assay = 'peaks',
  project = 'ATAC',
  min.cells = 1,
  meta.data = metadata
)
```

sesionInfo():

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux bullseye/sid

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1
```

**Comment by timoast** [comment]
What is the class of the matrix you're supplying to `CreateSeuratObject()`? Do you still get this error if you convert it to a `dgCMatrix` first (`mat <- as(object = mat, Class = "dgCMatrix")`)?

**Comment by micans** [comment]
Hi @timoast thanks very much for helping out. It took a while to run our case. Your suggestion made all the difference. Our class was `ngTMatrix`. After changing to loading of the matrix market file using `as(readMM(file = 'mmtx/filtered_window_bc_matrix.mmtx.gz'), "dgCMatrix")` we no longer experienced the memory error. Hence I'll close this. There is an issue somewhere in R or a library related to matrix loading and mixing C integer types I think, but this is not the place for that. Additionally it is very plausible that it's better to use the column format than the triplet format for large data.

**Comment by conniecl** [comment]
Find another solution to that problem, leave here if anybody face the same problem:
https://stackoverflow.com/questions/59636034/convert-large-r-data-frame-to-dgcmatrix
