### ISSUE TITLE
C stack usage  512918629072 is too close to the limit

### ISSUE THREAD

**Issue by montenegrina** [satijalab/seurat#4349]
I installed UMAP via:
 pip install umap-learn --user
...
Successfully built umap-learn pynndescent

I run this on Ubuntu:
ulimit -n
1024

I run these commands:

> datasets.integrated <- ScaleData(datasets.integrated, verbose = FALSE)
> datasets.integrated <- RunPCA(datasets.integrated, npcs = 30, verbose = FALSE)
> datasets.integrated <- RunUMAP(datasets.integrated, reduction = "pca", dims = 1:30)
UMAP(angular_rp_forest=True, dens_frac=0.0, dens_lambda=0.0,
     local_connectivity=1, metric='correlation', min_dist=0.3, n_neighbors=30,
     verbose=True)
Construct fuzzy simplicial set
Sat Apr 10 12:53:26 2021 Finding Nearest Neighbors
Sat Apr 10 12:53:26 2021 Building RP forest with 10 trees
**Error: C stack usage  512918629072 is too close to the limit**
> datasets.integrated <- FindNeighbors(datasets.integrated, reduction = "pca", dims = 1:30)
Computing nearest neighbor graph
Computing SNN
**Error: C stack usage  512943807184 is too close to the limit**
> datasets.integrated <- FindClusters(datasets.integrated, resolution = 0.5)
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 11989
Number of edges: 492030

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.9270
Number of communities: 18
Elapsed time: 1 seconds
> p1 <- DimPlot(datasets.integrated, reduction = "umap", group.by = "orig.ident")
Error in `[[.Seurat`(object, reduction) : 
  **Cannot find 'umap' in this Seurat object**

**> sessionInfo()**
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /software/linux-el7-x86_64/tools/lapack-3.9.0/build/lib/libblas.so.3.9.0
LAPACK: /software/linux-el7-x86_64/tools/lapack-3.9.0/build/lib/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C   

**Currently Loaded Modules:**
  1) compilers/gcc-7.1.0   2) tools/lapack-3.9.0   3) compilers/r-3.6.3   4) compilers/python-3.7.3

```r
# insert reproducible example here
```
Data sets are these: https://drive.google.com/file/d/195PbqGXla0hn5PSp8pc7MdCZqfd_29ov/view?usp=sharing

My code is this:

data_dir_1 <- file.path("datasets", "hcc")
sample1_data <- Read10X(data.dir = data_dir_1)
HCC_sample <- CreateSeuratObject(counts = sample1_data, project = "HCC")

data_dir_2 <- file.path("datasets", "healthy")
sample2_data <- Read10X(data.dir = data_dir_2)
healthy_sample <- CreateSeuratObject(counts = sample2_data, project = "Healthy")

#healthy_mt
healthy_sample[["percent.mt"]] <- 
  PercentageFeatureSet(healthy_sample, pattern = "^MT-")
VlnPlot(healthy_sample, features = 
          c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

#HCC_mt
HCC_sample[["percent.mt"]] <- 
  PercentageFeatureSet(HCC_sample, pattern = "^MT-")
VlnPlot(HCC_sample, features = 
          c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

#filter_out
healthy_sample <- subset(healthy_sample, subset = nFeature_RNA > 200 
                         & nFeature_RNA < 2500 & percent.mt < 30)
HCC_sample <- subset(HCC_sample, subset = nFeature_RNA > 200 
                     & nFeature_RNA < 2500 & percent.mt < 30)

datasets.list <- list(healthy_sample, HCC_sample)

datasets.list <- lapply(X = datasets.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = datasets.list)

datasets.anchors <- FindIntegrationAnchors(object.list = datasets.list, anchor.features = features)
datasets.integrated <- IntegrateData(anchorset = datasets.anchors)

#datasets.list <- list(healthy_sample, HCC_sample)
#for (i in 1:length(datasets.list)) {
#    datasets.list[[i]] <- SCTransform(datasets.list[[i]], verbose = FALSE)
#}
#datasets.features <- SelectIntegrationFeatures(object.list = datasets.list, nfeatures = 3000)
#datasets.list <- PrepSCTIntegration(object.list = datasets.list, anchor.features = datasets.features, 
#    verbose = FALSE)
#datasets.anchors <- FindIntegrationAnchors(object.list = datasets.list, normalization.method = "SCT", 
#    anchor.features = datasets.features, verbose = FALSE)
#datasets.integrated <- IntegrateData(anchorset = datasets.anchors, normalization.method = "SCT", 
#    verbose = FALSE)

#lognormalize
datasets.integrated <- ScaleData(datasets.integrated, verbose = FALSE)
datasets.integrated <- RunPCA(datasets.integrated, npcs = 30, verbose = FALSE)
datasets.integrated <- RunUMAP(datasets.integrated, reduction = "pca", dims = 1:30)
datasets.integrated <- FindNeighbors(datasets.integrated, reduction = "pca", dims = 1:30)
datasets.integrated <- FindClusters(datasets.integrated, resolution = 0.5)

**Comment by saketkc** [comment]
Hi @montenegrina, it seems you are using an older version of Seurat. Seurat v3.1.0 onwards supports running umap natively using the `uwot` package. You can consider upgrading.

I have seen this error in the past and my best guess is the `reticulate <-> python` bridge causing the stacks error. You can also consuder seeting your stack limit to unlimited before invoking R.

```
ulimit -s unlimited
```
