### ISSUE TITLE
comparsion of two batch dataset with SCTransfrom

### ISSUE THREAD

**Issue by Shiywa** [satijalab/seurat#4351]
Hi, I have a question about DEGs detection of two batch datasets. Firstly, we used `integrate` function to integrate two dataset to get same cell types between two datasets. When I want to do DEGs, should I do a new `SCTransform` according to the marge counts matrix in `RNA`? i just found that `data` from `SCTransform` separatelly don't have a good performance , but when I do a new `SCTransfrom` according to the merge count, it perfromed great.

how do you like it? 

regards !

**Comment by saketkc** [comment]
We recommend using the` RNA` assay or the `data` lot of `SCT` assay for DEGs. The pearson residuals are not comparable across the two datasets directly. Also see https://github.com/satijalab/seurat/discussions/4032
