### ISSUE TITLE
Raw data is tar.gz. Error message: "Expecting barcodes.tsv.gz"

### ISSUE THREAD

**Issue by algebio** [satijalab/seurat#4352]
Hello

I am trying to run this pipeline: https://satijalab.org/seurat/articles/pbmc3k_tutorial.html.

I have downloaded the raw data (which is a .tar.gz file) from the link in the first paragraph "The raw data can be found here." 

When I run the line: 
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/")

I get the error:
Error in Read10X(data.dir = "C:/Users/njo47/OneDrive - Newcastle University/Documents/Seurat/clustering") : Barcode file missing. Expecting barcodes.tsv.gz

Am I doing something wrong?

Thank you for your help.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Are the barcodes, genes, and matrix files found at the file path: "C:/Users/njo47/OneDrive - Newcastle University/Documents/Seurat/clustering"?  Can you also post what version of Seurat you are running?  I'm able to load the files without issue.

Best,
Sam

Best,
Sam

**Comment by algebio** [comment]
Hi Sam

I only get one .tar.gz file when I click the link "here" in the first paragraph in  https://satijalab.org/seurat/articles/pbmc3k_tutorial.html. The file is in the correct path. Seurat version is 4.0.0

How many files do you get from that same link?

Thank you for help.
Regards
Juan

**Comment by samuel-marsh** [comment]
Hi Juan,

That is zipped archive.  You need to unzip the download before supply path to `Read10X`.

Best,
Sam

**Comment by algebio** [comment]
My god! How much I have to learn.....

Thank you Sam.

**Comment by samuel-marsh** [comment]
No problem!  happy to help!
