### ISSUE TITLE
problem with data scaling

### ISSUE THREAD

**Issue by rmsalatino** [satijalab/seurat#4354]
Hello Seurat team, 
I am having an issue with data scaling while performing some basic analysis for a pilot experiment,
I get the following error:

**> endo2B_norm <- RunPCA(endo2B_norm, features = VariableFeatures(endo2B_norm))
Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Data has not been scaled. Please run ScaleData and retry**

but I made sure to scale the data during the normalization step,

**> endo2B_norm <- NormalizeData(endo2B, normalization.method = "LogNormalize", scale.factor = 10000)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|**

and I tried several scaling method as well but all eventually resulted into the same error.

Any suggestion or advice on how to solve this issue would be really appreciated!

Thank you!
roberto

**Comment by samuel-marsh** [comment]
Hi Roberto,

`ScaleData` and `NormalizeData` perform different functions (you can see more descriptions in the manual entries for each function).  If you run `ScaleData` before PCA but normalization and finding variable genes does that solve your issue?  See approach in basic clustering tutorial here: [https://satijalab.org/seurat/articles/pbmc3k_tutorial.html](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html)

Best,
Sam

**Comment by rmsalatino** [comment]
Hi Sam,
Thank you for the suggestion, yes that solved the issue.
best
roberto

**Comment by samuel-marsh** [comment]
Glad to help!!
