### ISSUE TITLE
a question about examine expression of genes across different samples after integration

### ISSUE THREAD

**Issue by liuweihanty** [satijalab/seurat#4356]
Hello,

I have three scRNA seq samples corresponding to a WT control(kon1),gene A midium level knock down(Kon2) and Low level knock down(kon3). My goal is to integrate the three samples, and see if indeed the average expression of gene A is lower in the knock down samples comparing to WT. Therefore, I SCTransformed my individual samples and performed integration followed your tutorial:

kon1.sct <- SCTransform(kon1,verbose = FALSE)
kon2.sct <- SCTransform(kon2,verbose = FALSE)
kon3.sct <- SCTransform(kon3,verbose = FALSE)
sct.list <- list(kon1.sct,kon2.sct,kon3.sct)
sct.features <- SelectIntegrationFeatures(object.list = sct.list,nfeatures = 3000)
sct.list <- PrepSCTIntegration(object.list = sct.list, anchor.features = sct.features, 
    verbose = FALSE)
sct.anchors <- FindIntegrationAnchors(object.list = sct.list, normalization.method = "SCT", 
    anchor.features = sct.features, verbose = FALSE)
kon.comb.sct <- IntegrateData(anchorset = sct.anchors, normalization.method = "SCT", 
    verbose = FALSE)

Then, I thought since I want to examine the expression of gene A across three samples, I need to normalize on the integrated seurat object, so I did:

DefaultAssay(kon.comb.sct) <- "RNA"
kon.comb.sct <- NormalizeData(kon.comb.sct, verbose = FALSE)

Is this the correct way to integrate individual samples and examine the expression of a single gene across the samples? Thank you very much!

**Comment by yuhanH** [comment]
HI, 
You scripts look correct for me. You can also compare the gene expression across your samples by `split.by` parameters in `FeaturePlot` and `VlnPlot`.  

One more thing you can is to set the first object (WT control) as the reference in the integration. 
```
FindIntegrationAnchors(object.list = sct.list,
 normalization.method = "SCT",
reference = 1,
anchor.features = sct.features, verbose = FALSE)
```
[Reference-based integration vignette](https://satijalab.org/seurat/articles/integration_large_datasets.html) explain the settings in more detail.
