### ISSUE TITLE
Error from IntegrateData function 

### ISSUE THREAD

**Issue by makarov-ccf** [satijalab/seurat#4357]
Hello,

We are trying to integrate Seurat objects from large dataset (~50 samples, over 500000 cells ).
To optimize the process, we are following the Parallelization in Seurat with future as explained at
https://satijalab.org/seurat/archive/v3.0/future_vignette.html

plan("multiprocess", workers = 4)

We are using big memory node (800GB RAM, 16 cores) and reserve the whole node, but having an error message as below.

Smaller sets ran without problems.

What could be a reason?

Thank you

```
_Error: Failed to retrieve the result of MulticoreFuture (future_lapply-4) from the forked worker (on localhost; PID 176261). Post-mortem diagnostic: No process exists with this PID, i.e. the forked localhost worker is no longer alive.
In addition: Warning message:
In mccollect(jobs = jobs, wait = TRUE) :
  1 parallel job did not deliver a result
Execution halted
Error while shutting down parallel: unable to terminate some child processes
slurmstepd: error: Detected 26 oom-kill event(s) in step 49118.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler._
```

**Comment by saketkc** [comment]
Hi @makarov-ccf, we make some recommendations for large datasets in this [vignette](https://satijalab.org/seurat/articles/integration_large_datasets.html). In short, we recommend RPCA and reference-based integration for such datasets. Would you be able to run your samples using the recommendations from this vignette? Feel free to reopen if you still face any issues.

**Comment by neurojacob** [comment]
Hi--I would like to reopen this topic. 

I too am having this issue, also using a multi-core (16) node with >100 GB of RAM.

I am trying to integrate ~20 datasets and have already tried to use the reference-based integration, as well as RPCA, to no avail. In both cases, I still get the same error:

"Warning message in mccollect(jobs = jobs, wait = TRUE):
"1 parallel job did not deliver a result"
Error: Failed to retrieve the result of MulticoreFuture (future_lapply-4) from the forked worker (on localhost; PID 17327). Post-mortem diagnostic: No process exists with this PID, i.e. the forked localhost worker is no longer alive"

It works when serialized using plan(sequential), but fails with any number of multicore workers. The maximum RAM size in future is also set to an incredibly large number (larger than would ever be used). 

If you have any insights at all or thoughts on troubleshooting, I would very much appreciate the help!

**Comment by iichelhadi** [comment]
I am having a similar issue with trying to integrate a large scRNA seq dataset but I am using scTransform for normalisation instead
