### ISSUE TITLE
Error in FindIntegrationAnchors- Please specify a maximum dimensions that is less than the number of cells in any object (4)

### ISSUE THREAD

**Issue by das2000sidd** [satijalab/seurat#4358]
Hi

I am working on integrating a labelled single cell RNA seq cell atlas with an unlabelled one. I am wondering how do I determine the value of max.features when integrating two single cell RNA seq datasets?

Below is the code I am using:

epithelial = Read10X(data.dir="/projects/b1025/sdi0596/Covid19_Single_Cell_RNASeq_project/filtered_matrices_count/epithelial/filtered_feature_bc_matrix/",gene.column=1,cell.column=1)
habermann = Read10X(data.dir="/projects/b1025/sdi0596/Covid19_Single_Cell_RNASeq_project/filtered_matrices_count/Habermann_Single_Cell_Data/",gene.column=1,cell.column=1)

data.list=c(epithelial,habermann)
# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = data.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})  
  
## Perform integration
immune.achors= FindIntegrationAnchors(object.list = ifnb.list,max.features = 200,verbose = TRUE)

Error in FindIntegrationAnchors(object.list = ifnb.list, max.features = 200,  : 
  Max dimension too large: objects 1, 2 contain fewer than 30 cells. 
 Please specify a maximum dimensions that is less than the number of cells in any object (4).

Regarding the dimension of these objects, the epithelial one is 33538 x 49109 and the habermann is 33694 x 220213. 
Any insights would be highly helpful.

Thank you.

**Comment by torkencz** [comment]
This was pretty well answered here:
https://bioinformatics.stackexchange.com/questions/15720/error-in-findintegrationanchors-seurat-package
 so I will close it.
