### ISSUE TITLE
Cluster by predefined set of genes or predefined metadata

### ISSUE THREAD

**Issue by cBioPort** [satijalab/seurat#4359]
I have two related questions:

In a seurat obj that I am subsetting from a larger one, can you confirm if the order of steps to cluster by predefined set of genes is correct:
gene.names.vector <- c("list of genes of interest")
obj <- subset(pmbc, idents =c("idents of interest")
obj<-NormalizeData(aml_pt1)
obj<-FindVariableFeatures(object=obj) #?Do I need to provide list of  genes of interest here? or should I just avoid using this line
obj <- ScaleData(obj) 
obj <- RunPCA(object=obj, features = gene.names.vector) #should I provide the gene vector here?
obj <- FindNeighbors(obj, dims=1:20,reduction = "pca") 
 obj <- FindClusters(object = obj, resolution = 0.3)
obj <- RunUMAP(obj,reduction = "pca",dims=1:20) #will this object be clusters based on the genes of 

In another Seurat object, with generated metadata containing pathway scores of ~100 pathways, how can I reclusters the object to identify clusters based on the pathway scores rather than the genes? I can transpose the metadata and create a Seurat object, however, I will then lose the gene info pertinent to each cell.

**Comment by saketkc** [comment]
You can assign your pre-computed list to be "variable features" skipping the `FindVariableFeatures` step if you want:

```r
obj <- NormalizeData(aml_pt1)
VariableFeatures(obj ) <- gene.names.vector
obj <- ScaleData(obj)
```

**Comment by cBioPort** [comment]
Thanks for the response. However,  in other response, there was a suggestion not to run VariableFeatures(obj) and instead, go to 
obj <- RunPCA(object=obj, features= gene.names.vector)
Or do you recommend to do both ? Variable(Features(obj) <-gene.names.vector
then again under RunPCA?

**Comment by saketkc** [comment]
[RunPCA](https://satijalab.org/seurat/reference/runpca) uses variable features by defaullt so specifying the argument is redundant.
