### ISSUE TITLE
Modify seurat_cluster labels

### ISSUE THREAD

**Issue by geek123456789** [satijalab/seurat#4360]
I have a dataset which I used the FindNeighbors and then the FindClusters function. And I get 5 different clusters: 0, 1, 2, 3, 4. This information is stored in the Suerat object metadata (object$seurat_clusters), a such:

`>object$seurat_clusters`
`CACCACTGTTATGCGT-1 CACCACTTCAATCACG-1 CACCACTTCCCAGGTG-1 CACCACTTCTGCTGTC-1 `
 `                0                          0                  1                  0 `
`CACCAGGAGAACTCGG-1 CACCAGGAGCCCAGCT-1 CACCAGGAGTACTTGC-1 CACCAGGAGTCACGCC-1 `
  `               4                  3                  3                  1 `
`CACCAGGCAAGCCGTC-1 CACCAGGCAGGAATCG-1 CACCAGGTCACAGTAC-1 CACCTTGAGATCTGAA-1 `
   `              1                  0                  1                  0 `
`CACCTTGAGCTGCCCA-1 CACCTTGAGGTGCAAC-1 CACCTTGCAAACGCGA-1 CACCTTGGTAGAAAGG-1 `
    `             0                  0                  1                  0 `
`Levels: 0 1 2 3 4`

In my data  have three different conditions and in my next steps i join all the conditions into a unique seurat object. The problem is all the different conditions have the same name for their clusters (0,1,2,3,4,5...).

I want to be able to change this clusters labels to something else, for example for the condition 1 I would like to change seurat_cluster = 0 to seurat_cluster = C1_0, seurat_cluster = 1 to seurat_cluster = C1_1 ...

 I found the function:
`object <- RenameIdents(object = object,  '0' = 'C1_0', '1' = 'C1_1', '2' = 'C1_2', '3' = 'C1_3', '4' = 'C1_4')`

But this function doesn't modify the @meta.data, how can I do this?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Yes, the `RenameIdents` function only changes the active identity of the object.  To store those identities in meta data you can use command:
```
object[["name_of_meta_column"]] <- Idents(object)
```

Two things worth noting.  First, the `seurat_clusters` meta data column is overwritten whenever you run `FindClusters` so even if you rename the clusters if that is the meta data column that you use it will be overwritten when you do your combined analysis so if you want to preserve this information you should chose your own name for the new meta data column.

Second, after you combine the objects even if cells are same cell type/class as cells in other objects when you do combined analysis they may cluster different based on the presence of the cells (and therefore gene expression) from the other objects.  So what clusters they used to be part of may or may not be relevant depending on your goals in analysis.

Best,
Sam

**Comment by geek123456789** [comment]
Hi Sam, 
thank you for your answer and your advice, I think the best option for me is to add a new meta data column with the information I need!

**Comment by saketkc** [comment]
Thanks @samuel-marsh. 

@geek123456789 You can define a new metadata column after clustering:

```r
object$my_cluster <- paste(object$condition, object$seurat_cluster, sep="_")
```
