### ISSUE TITLE
Seurat v4: broken link on cell browser documentation

### ISSUE THREAD

**Issue by BingbingYuan** [satijalab/seurat#4361]
In the Seurat version 4 documentation ( https://satijalab.org/seurat/articles/v4_changes.html ), the **here** link at bottom of the page is broken. 
"
ExportToCellbrowser and StopCellbrowser moved to SeuratWrappers, see details **here**
"
**here** points to cellbrowser documentation from SeuratWrappers: 
https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/cellbrowser.html

**Comment by mojaveazure** [comment]
This should now be fixed, thanks
