### ISSUE TITLE
Problem in Visualizing ADT CITE-Seq data in FeatureScatter-plot

### ISSUE THREAD

**Issue by AlexanderPic** [satijalab/seurat#4362]
Hello,
Thank you very much for all your vignettes - they've been really useful!

We are trying to visualize the ADT data from a cite-seq experiment. 
We used 2 antibodies CD45.1 and CD45.2 to label and track two genetically identical mouse cell populations. 
Clustering all cells according to RNA-expression works fine.
However, visualizing the two populations on a FeatureScatter using CD45.1 and CD45.2 produces a plot, that seems overnormalized or overscaled. 

Here is the code (we mainly followed the vignette):

```{r}
# read cite-seq data
MAC_0h <- Read10X(data.dir = paste0(path_raw_cite_sec, "MAC_0h/filtered_feature_bc_matrix/"))

# extract RNA and ADT asssay
MAC_0h.rna <- MAC_0h$`Gene Expression`
MAC_0h.adt <- MAC_0h$`Antibody Capture`
all.equal(colnames(MAC_0h.rna), colnames(MAC_0h.adt))

# create seurat object with RNA counts
MAC_0h_obj <- CreateSeuratObject(counts = MAC_0h.rna, project = "MAC_0h")

# create a new assay to store ADT information
adt_assay <- CreateAssayObject(counts = MAC_0h.adt)

# add this assay to the previously created Seurat object
MAC_0h_obj[["ADT"]] <- adt_assay

DefaultAssay(MAC_0h_obj) <- "RNA"

MAC_0h_obj <- subset(x = MAC_0h_obj, subset = nFeature_RNA > 200)
MAC_0h_obj <- NormalizeData(MAC_0h_obj)
MAC_0h_obj <- FindVariableFeatures(MAC_0h_obj)
MAC_0h_obj <- ScaleData(MAC_0h_obj)
MAC_0h_obj <- RunPCA(MAC_0h_obj, verbose = FALSE)
MAC_0h_obj <- RunUMAP(MAC_0h_obj, dims = 1:30)
DimPlot(MAC_0h_obj, label = TRUE)
MAC_0h_obj <- FindNeighbors(MAC_0h_obj, dims = 1:30)
MAC_0h_obj <- FindClusters(MAC_0h_obj, resolution = 0.3, verbose = FALSE)

# Feature scatter on un-normalized data
FeatureScatter(MAC_0h_obj, feature1 = "adt_CD45.2", feature2 = "adt_CD45.1")
```
![Rplot02](https://user-images.githubusercontent.com/82457911/114578485-34772280-9c7d-11eb-9008-ca7e61197b59.png)

```{r}
# normalize ADT data
DefaultAssay(MAC_0h_obj) <- "ADT"
MAC_0h_obj_adt_norm<- NormalizeData(MAC_0h_obj, normalization.method = "CLR", margin = 2)

# Feature scatter on normalized data
FeatureScatter(MAC_0h_obj_adt_norm, feature1 = "adt_CD45.2", feature2 = "adt_CD45.1")
```

this is the picture we get after running FeatureScatter on the normalized ADT-data:

![Rplot01](https://user-images.githubusercontent.com/82457911/114576087-1ad4db80-9c7b-11eb-8cea-5b4cbcb3c6b2.png)

We get a similar plot when we run ScaleData additionally to NormalizeData:

```{r}
MAC_0h_obj_adt_norm_scaled<- ScaleData(MAC_0h_obj_adt_norm , assay = "ADT", verbose = F)
FeatureScatter(MAC_0h_obj_adt_norm_scaled, feature1 = "adt_CD45.2", feature2 = "adt_CD45.1", slot = 'scale.data')
```
![Rplot03](https://user-images.githubusercontent.com/82457911/114581535-13fc9780-9c80-11eb-9e2c-473baff00034.png)

Of course we would rather expect a CD45.1+ CD45.2- and vice versa a  CD45.1- CD45.2+ population.
Have you got any ideas what could have gone wrong? I'm quite new to analysing cite-seq data and I don't know if anyone's had similar problems with CITE-Seq ADT-data.

I am happy to share more information if needed!

Thank you very much for your help,
Alexander

**Comment by jaisonj708** [comment]
This seems like more of an experimental rather than an analysis question - your unnormalized FeatureScatter plot indicates that most of your cells have at least some positive expression of both antibodies. This can sometimes happen due to low signal / antibody quality.  You can also try CLR(margin=1) normalization to make this look a bit better on the analysis side.
