### ISSUE TITLE
Reverting the NormalizeData() output

### ISSUE THREAD

**Issue by gorkemkose** [satijalab/seurat#4363]
Hi, I'm trying to use an annotated single-cell data as a reference dataset, and I know that the platform that I pull the dataset has used NormalizeData() function by Seurat. But I needed the expression matrix as a count-level, untransformed matrix rather than a matrix with normalized values. Is there any way to revert the NormalizeData() function and supply the normalized/transformed matrix and get the count-level matrix back? 

Any help would be much appreciated. Thanks!

**Comment by gorkemkose** [comment]
What I mean is applying a back transformation. Is that possible?

**Comment by timoast** [comment]
This blog post by Valentine Svensson might be useful to you: https://www.nxn.se/valent/2018/10/25/unscaling-scaled-counts-in-scrna-seq-data

I'd recommend finding the original count matrix if you can, maybe by contacting the authors.
