### ISSUE TITLE
AddModuleScore to score the cells and assign each cell to the gene set 

### ISSUE THREAD

**Issue by miriammagallon** [satijalab/seurat#4365]
Hi!

I obtained different sets of genes associated with a differentiation process from a different analysis. I would like to use AddModuleScore to score the cells and assign each cell to the gene set (differentiation stage) that better represents it.
In order to do so, we would score each cell with each gene set and then compare the scores to assign the best. 
As per our understanding of how scores are computed, we think that they are not directly comparable but need a normalization step. Is this correct?

Our intention is to divide the score of each cell/geneset by the mean expression of the gene set across all cells to account for the binning process. Is this correct? 

Would you recommend a different strategy to compare genesets scores and assign cell identities?

Thanks!

**Comment by jaisonj708** [comment]
Normally PCA/neighbor-finding followed by clustering or some kind of trajectory analysis will be able to identify differentiation groups.  But if you want to use pre-defined modules, I would recommend L2-norming each group of module scores before making any comparisons.
