### ISSUE TITLE
Azimuth produces different subset frequencies than reference mapping workflow in Seurat

### ISSUE THREAD

**Issue by b-russell5** [satijalab/seurat#4367]
I have tried mapping my query lymphocyte dataset to the PBMC reference atlas using both the Azimuth app and the Seurat Reference Mapping workflow in R as described in [this](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html) vignette. However, between the two approaches, I am seeing significantly different results in the frequency of cells that are mapping to a given subset. For example, when using Azimuth ~1000 cells map to the "NK Proliferating" cluster at Level 2 granularity, but when using the Seurat reference mapping workflow only ~500 cells map to this cluster at the same level of granulairty. Also, in the Seurat reference mapping workflow, cells map to subsets that don't appear at all in the Azimuth results. The QC thresholds for both approaches were kept consistent.

As I currently understand, Azimuth and the Seurat reference mapping workflow should produce very similar results. Can you provide any insight as to why I am seeing these variations? Is one approach more 'reliable' than the other?

For reference, my Seurat code is as follows:
```
#load reference dataset
pbmc_reference <- LoadH5Seurat("./pbmc_multimodal.h5seurat")

#prepare query dataset
query[["percent.mt"]] <- PercentageFeatureSet(query pattern = "^MT-")
query <- subset(query, subset = nFeature_RNA > 500 & nFeature_RNA < 8000 &
               nCount_RNA > 499 & nCount_RNA < 80000 
               & percent.mt < 15)
query <- SCTransform(query, verbose = FALSE)

pbmc_reference <- FindNeighbors(
  object = pbmc_reference,
  reduction = "spca",
  dims = 1:50,
  graph.name = "spca.annoy.neighbors", 
  k.param = 50,
  cache.index = TRUE,
  return.neighbor = TRUE,
  l2.norm = TRUE
)

anchors <- FindTransferAnchors(
  reference = pbmc_reference,
  query = query,
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50
)

query <- MapQuery(
  anchorset = anchors,
  query = query,
  reference = pbmc_reference,
  refdata = list(
    celltype.l2 = "celltype.l2",
    celltype.l3 = "celltype.l3",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca",
  reduction.model = "wnn.umap"
)
```

**Comment by jaisonj708** [comment]
FindAllMarkers has a `return.thresh` parameter set to 0.01, whereas FindMarkers doesn't. You can increase this threshold if you'd like more genes / want to match the output of FindMarkers

**Comment by jaisonj708** [comment]
For exact reproducibility you should use the script we provide in the Downloads tab on Azimuth. There are some key differences with what you've run, such as our normalization method (reference-based SCTransform).
