### ISSUE TITLE
latent.vars not working for MAST 

### ISSUE THREAD

**Issue by akr2151** [satijalab/seurat#4368]
I get identical results when including or excluding latent variables for MAST differential expression analysis with FindMarkers. I've tried several combinations and the results I get are identical. Might have a formatting issue

Check1<-FindMarkers(final,ident.1 = "HET",ident.2 = "WT",logfc.threshold = 0.25,min.pct=0.25,latent.vars = c("percent.mt","nCount_RNA","batch"),test.use = "MAST")
Check2<-FindMarkers(final,ident.1 = "HET",ident.2 = "WT",logfc.threshold = 0.25,min.pct=0.05,latent.vars = "batch",test.use = "MAST")
Check3<-FindMarkers(final,ident.1 = "HET",ident.2 = "WT",logfc.threshold = 0.25,min.pct=0.05,test.use = "MAST")

Batch is just randomly generated 0s and 1. Each time the outputs are identical and I've tried regressing on every variable in metadata. Is this a typo on my end or a bug? I saw there was a latent variable bug corrected last December.

**Comment by tcikezu** [comment]
@akr2151 I've created a test case, but I find that these checks produce different results. I'm using Seurat 4.0.1

```
library(Seurat)
library(SeuratData)
SeuratData::InstallData('pbmc3k')
data(pbmc3k)

pbmc3k@meta.data[['percent.MT']] <- PercentageFeatureSet(pbmc3k, pattern = '^MT-')
pbmc3k@meta.data[['batch']] <- runif(ncol(pbmc3k@meta.data)) > 0.5
Idents(pbmc3k) <- pbmc3k$seurat_annotations
DefaultAssay(pbmc3k) <- 'RNA'
pbmc3k <- NormalizeData(pbmc3k)
Check1.B_vs_CD8_T <- FindMarkers(pbmc3k,
                                 ident.1='B',
                                 ident.2='CD8 T',
                                 assay = 'RNA',
                                 slot = 'data',
                                 test.use='MAST',
                                 latent.vars=c('percent.MT', 'nCount_RNA', 'batch'),
                                 min.pct=0.25,
                                 logfc.threshold=0.25
                                 )
Check2.B_vs_CD8_T <- FindMarkers(pbmc3k,
                                 ident.1='B',
                                 ident.2='CD8 T',
                                 assay = 'RNA',
                                 slot = 'data',
                                 test.use='MAST',
                                 latent.vars=c('batch'),
                                 min.pct=0.25,
                                 logfc.threshold=0.25
                                 )
Check3.B_vs_CD8_T <- FindMarkers(pbmc3k,
                                 ident.1='B',
                                 ident.2='CD8 T',
                                 assay = 'RNA',
                                 slot = 'data',
                                 test.use='MAST',
                                 min.pct=0.25,
                                 logfc.threshold=0.25
                                 )

head(Check1.B_vs_CD8_T)
head(Check2.B_vs_CD8_T)
head(Check3.B_vs_CD8_T)

> head(Check1.B_vs_CD8_T)
                p_val avg_log2FC pct.1 pct.2     p_val_adj
CD74    1.818230e-256   3.545590 1.000 0.838 2.493520e-252
HLA-DRA 1.115415e-242   4.722363 1.000 0.332 1.529681e-238
CCL5    3.590038e-166  -4.781878 0.142 0.985 4.923378e-162
NKG7    1.517802e-145  -5.006739 0.087 0.970 2.081513e-141
CD79A   7.309482e-144   4.360488 0.936 0.018 1.002422e-139
IL32    5.515632e-132  -3.819646 0.099 0.963 7.564137e-128
> head(Check2.B_vs_CD8_T)
                p_val avg_log2FC pct.1 pct.2     p_val_adj
CD74    2.413446e-254   3.545590 1.000 0.838 3.309799e-250
HLA-DRA 2.072957e-241   4.722363 1.000 0.332 2.842853e-237
CCL5    7.548405e-169  -4.781878 0.142 0.985 1.035188e-164
NKG7    6.452020e-145  -5.006739 0.087 0.970 8.848300e-141
CD79A   4.334309e-141   4.360488 0.936 0.018 5.944071e-137
IL32    2.989509e-136  -3.819646 0.099 0.963 4.099813e-132
> head(Check3.B_vs_CD8_T)
                p_val avg_log2FC pct.1 pct.2     p_val_adj
CD74    9.385471e-254   3.545590 1.000 0.838 1.287123e-249
HLA-DRA 6.916987e-241   4.722363 1.000 0.332 9.485955e-237
CCL5    7.131852e-169  -4.781878 0.142 0.985 9.780622e-165
NKG7    1.071113e-144  -5.006739 0.087 0.970 1.468924e-140
CD79A   6.318293e-141   4.360488 0.936 0.018 8.664907e-137
IL32    3.390832e-136  -3.819646 0.099 0.963 4.650187e-132

```

**Comment by akr2151** [comment]
Hey,

Thanks for reply, I meant to follow up. All of the genes were the same, but the p-values were different. The size of differences in my sample were just robust to batch effects. Sorry for not letting you know sooner and thank you for looking into this anyways.

Best,
Andrew

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Tadafumi Clark Ikezu ***@***.***>
Sent: Tuesday, April 20, 2021 8:51:15 AM
To: satijalab/seurat ***@***.***>
Cc: Ressler, Andrew ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [satijalab/seurat] latent.vars not working for MAST (#4368)


@akr2151<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_akr2151&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=_kz_oWQHf1kEBeagPQZ5ac4uWFd4oSTmhY4TCk3hNEU&m=ZbFKNRTGqHK6V4Pv90xvpNDqUMi9OqKFtNU-jx8OuWI&s=1Y5qb6obdgibfdkrsEsaEEuz-n2RHcfsq4DBVVWPP1Y&e=> I've created a test case, but I find that these checks produce different results. I'm using Seurat 4.0.1

library(Seurat)
library(SeuratData)
SeuratData::InstallData('pbmc3k')
data(pbmc3k)

***@***.***[['percent.MT']] <- PercentageFeatureSet(pbmc3k, pattern = '^MT-')
***@***.***[['batch']] <- ***@***.***)) > 0.5
Idents(pbmc3k) <- pbmc3k$seurat_annotations
DefaultAssay(pbmc3k) <- 'RNA'
pbmc3k <- NormalizeData(pbmc3k)
Check1.B_vs_CD8_T <- FindMarkers(pbmc3k,
                                 ident.1='B',
                                 ident.2='CD8 T',
                                 assay = 'RNA',
                                 slot = 'data',
                                 test.use='MAST',
                                 latent.vars=c('percent.MT', 'nCount_RNA', 'batch'),
                                 min.pct=0.25,
                                 logfc.threshold=0.25
                                 )
Check2.B_vs_CD8_T <- FindMarkers(pbmc3k,
                                 ident.1='B',
                                 ident.2='CD8 T',
                                 assay = 'RNA',
                                 slot = 'data',
                                 test.use='MAST',
                                 latent.vars=c('batch'),
                                 min.pct=0.25,
                                 logfc.threshold=0.25
                                 )
Check3.B_vs_CD8_T <- FindMarkers(pbmc3k,
                                 ident.1='B',
                                 ident.2='CD8 T',
                                 assay = 'RNA',
                                 slot = 'data',
                                 test.use='MAST',
                                 min.pct=0.25,
                                 logfc.threshold=0.25
                                 )

head(Check1.B_vs_CD8_T)
head(Check2.B_vs_CD8_T)
head(Check3.B_vs_CD8_T)

> head(Check1.B_vs_CD8_T)
                p_val avg_log2FC pct.1 pct.2     p_val_adj
CD74    1.818230e-256   3.545590 1.000 0.838 2.493520e-252
HLA-DRA 1.115415e-242   4.722363 1.000 0.332 1.529681e-238
CCL5    3.590038e-166  -4.781878 0.142 0.985 4.923378e-162
NKG7    1.517802e-145  -5.006739 0.087 0.970 2.081513e-141
CD79A   7.309482e-144   4.360488 0.936 0.018 1.002422e-139
IL32    5.515632e-132  -3.819646 0.099 0.963 7.564137e-128
> head(Check2.B_vs_CD8_T)
                p_val avg_log2FC pct.1 pct.2     p_val_adj
CD74    2.413446e-254   3.545590 1.000 0.838 3.309799e-250
HLA-DRA 2.072957e-241   4.722363 1.000 0.332 2.842853e-237
CCL5    7.548405e-169  -4.781878 0.142 0.985 1.035188e-164
NKG7    6.452020e-145  -5.006739 0.087 0.970 8.848300e-141
CD79A   4.334309e-141   4.360488 0.936 0.018 5.944071e-137
IL32    2.989509e-136  -3.819646 0.099 0.963 4.099813e-132
> head(Check3.B_vs_CD8_T)
                p_val avg_log2FC pct.1 pct.2     p_val_adj
CD74    9.385471e-254   3.545590 1.000 0.838 1.287123e-249
HLA-DRA 6.916987e-241   4.722363 1.000 0.332 9.485955e-237
CCL5    7.131852e-169  -4.781878 0.142 0.985 9.780622e-165
NKG7    1.071113e-144  -5.006739 0.087 0.970 1.468924e-140
CD79A   6.318293e-141   4.360488 0.936 0.018 8.664907e-137
IL32    3.390832e-136  -3.819646 0.099 0.963 4.650187e-132

**Comment by tcikezu** [comment]
I think this is working as it should. Fold changes and p-values are computed independently -- see [line 706](https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/differential_expression.R#L706) where fold change is computed, [line 727](https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/differential_expression.R#L727) where p-values are computed. Setting latent.vars will affect p-values, and that affects the ordering of the genes, but not what genes are tested or what the log fold changes are.
