### ISSUE TITLE
Different results between FindMarkers and FindAllMarkers

### ISSUE THREAD

**Issue by GBeattie** [satijalab/seurat#4369]
Hi,

When I started my analysis I had not realised that FindAllMarkers was available to perform DE between all the clusters in our data, so I wrote a loop using FindMarkers to do the same task. I have recently switched to using FindAllMarkers, but have noticed that the outputs are very different.

Here is my loop:

```
Idents(seu.int) <- "seurat_clusters"
markers.pos = data.frame()
for (i in levels(Idents(seu.int))){
  markers <- FindMarkers(seu.int, ident.1 = i, grouping.var = "ident", verbose = T, only.pos = T, logfc.threshold = 0.25)
  dat <- markers %>% rownames_to_column(var="Gene_ID")
  dat["Cluster_ID"] <- i

  df <- data.frame(dat)
  markers.pos <- rbind(markers.pos,df)
}
```

And here is my FindAllMarkers command:
`markers.pos.2 <- FindAllMarkers(seu.int, only.pos = T, logfc.threshold = 0.25)`

From my understanding they should output the same lists of genes and DE values, however the loop outputs ~15,000 more genes (lots of duplicates of course), and doesn't report DE mitochondrial genes, which is what we expect from the data, while we do see DE mito genes in the FindAllMarkers output (among many other gene differences).

The most probable explanation is I've done something wrong in the loop, but I can't see any issue. Any light you could shed on how I've gone wrong would be greatly appreciated!

Thanks,

Gordon

**Comment by jaisonj708** [comment]
FindAllMarkers has a `return.thresh` parameter set to 0.01, whereas FindMarkers doesn't. You can increase this threshold if you'd like more genes / want to match the output of FindMarkers
