### ISSUE TITLE
version 3.9.9.9024 different results from 4.0.1?

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#4370]
Hi just a short question: I made analyses based on the v4beta version (3.9.9.9024). However, now I went up to 4.0.1 and the data integration is not reproducible: the dimensionality reduction plots clusters slightly differently - which is just terrifying because I was about to submit a paper and now I cannot reproduce the data myself. Is the 3.9.9.9024 available somewhere? 

Help (!!!!)

**Comment by NicolaasVanRenne** [comment]
On the same issue: why are the UMAP plots different in 3.9.9.9024 VS 4.0.1?

:(

**Comment by timoast** [comment]
You can install the previous version of Seurat from GitHub using `remotes::install_github()` with the parameter `ref` used to give the specific commit that you want to install.
