### ISSUE TITLE
Warning: Invalid name supplied

### ISSUE THREAD

**Issue by chen-single** [satijalab/seurat#4374]
Thanks for the tool!
When I run RunHarmony I meet a warning ：Warning: Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity
Will it affect the follow-up analysis?

**Comment by timoast** [comment]
The `RunHarmony()` function is not actually part of Seurat, but is part of the Harmony package. Please raise this issue in the Harmony repository: https://github.com/immunogenomics/harmony
