### ISSUE TITLE
How to call Seurat objects in loops and functions

### ISSUE THREAD

**Issue by ElyasMo** [satijalab/seurat#4375]
Dear Sir or Madam,
I am trying to summarize the codes that I am writing in my pipeline by using loops and functions. I have porblem in calling the Seurat objects from a list. I have also tried get function in loops by still it does not work. 
As an example:
In the first chunck, you can add the MT genes to metadata, however, in the second chunck, in spite of not facing with error, the MT genes cannot be added to metadata.

Any solutions would be greatly appreciated.

```r
CR_control_1[["percent.mt"]] <- PercentageFeatureSet(CR_control_1, pattern = "^MT-")
CR_sample_1[["percent.mt"]] <- PercentageFeatureSet(CR_sample_1, pattern = "^MT-")
CR_sample_1_density[["percent.mt"]] <- PercentageFeatureSet(CR_sample_1_density, pattern = "^MT-")
HE_control_1[["percent.mt"]] <- PercentageFeatureSet(HE_control_1, pattern = "^MT-")
HE_sample_1[["percent.mt"]] <- PercentageFeatureSet(HE_sample_1, pattern = "^MT-")
HE_control_2[["percent.mt"]] <- PercentageFeatureSet(HE_control_2, pattern = "^MT-")
HE_sample_2[["percent.mt"]] <- PercentageFeatureSet(HE_sample_2, pattern = "^MT-")
```
```r
li <- list(CR_control_1,CR_sample_1, CR_sample_1_density, HE_control_1, HE_sample_1, HE_control_2,HE_sample_2)
li2 <- lapply(li,function(X) {X[["percent.mt"]] <- PercentageFeatureSet(X, pattern = "^MT-"); X} )
```

**Comment by timoast** [comment]
I wasn't able to reproduce this:

```r
library(Seurat)
l <- list(pbmc_small, pbmc_small)
lapply(l, function(x) {colnames(x[[]])})
```

```
[[1]]
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8" "letter.idents"   "groups"         
[7] "RNA_snn_res.1"  

[[2]]
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8" "letter.idents"   "groups"         
[7] "RNA_snn_res.1"  
```

```r
l <- lapply(l, function(x) {x[['mt']] <- PercentageFeatureSet(x, pattern = "^MT"); x})
lapply(l, function(x) {colnames(x[[]])})
```
```
[[1]]
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8" "letter.idents"   "groups"         
[7] "RNA_snn_res.1"   "mt"             

[[2]]
[1] "orig.ident"      "nCount_RNA"      "nFeature_RNA"    "RNA_snn_res.0.8" "letter.idents"   "groups"         
[7] "RNA_snn_res.1"   "mt"             
```

**Comment by ElyasMo** [comment]
Thank you for the response and sorry if it was not clear enough.
Here is what I mean exactly.
I would like to add the percentage of mitochondrial gene to my metadata of seurat object. The script to do that would be : 
```r
CR_control_1[["percent.mt"]] <- PercentageFeatureSet(CR_control_1, pattern = "^MT-")
CR_sample_1[["percent.mt"]] <- PercentageFeatureSet(CR_sample_1, pattern = "^MT-")
```
Now I want to do it with lapply and functions but what I receive is a list of Seurat objects as you exactly have shown in your example. What I want to do is to save the changes in the same Seurat object. So, after applying the:
```r
li <- list(CR_control_1,CR_sample_1)
li2 <- lapply(li,function(X) {X[["percent.mt"]] <- PercentageFeatureSet(X, pattern = "^MT-"); X} )
```
I do not want to have a list of the results but I want it to be added to CR_control_1 and CR_sample_1 seurat objects. In other words, I want to have the results separately in my global environment. So by checking the:
```r
CR_sample_1$percent.mt
CR_control_1$percent.mt
```
It should be operational while it is not at the moment. Briefly, how to save the changes with lappy function in the same seurat object that has been used for the calculations. 
Thank you very much

**Comment by timoast** [comment]
Unfortunately that's not how R works
