### ISSUE TITLE
Implement DensMAP

### ISSUE THREAD

**Issue by lldelisle** [satijalab/seurat#4378]
Hi,
I was wondering if you were planing to implement DensMAP as a parameter for UMAP from sklearn:
https://umap-learn.readthedocs.io/en/latest/densmap_demo.html
I can also write a PR if nobody is already doing it on your side.

**Comment by andrewwbutler** [comment]
Hi @lldelisle ,

We'd be happy to incorporate a PR with this functionality if you have the bandwidth to put one together.

**Comment by erosix** [comment]
I would really like to have densMAP for Seurat. *.* Any way this can be implemented soon?

**Comment by lldelisle** [comment]
Hi,
I just wrote #4630 ...

**Comment by andrewwbutler** [comment]
This functionality is now available on the `develop` branch. Please see installation instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)
