### ISSUE TITLE
Cell Hashing Demultiplexing

### ISSUE THREAD

**Issue by fouerghi** [satijalab/seurat#4379]
Hi, 

I have hashed 8 samples together and I have used the Seurat function HTODemux() to demultiplex the samples. Unfortunately it seems like two of the antibodies I have used (HTO 2 and HTO 6) bound nonspecifically to HTO 8 and HTO 3. So when I am using the HTODemux function, the cutoff reads for HTO 2 and HTO 6 are pretty low which means that a lot of cells that should have been assigned as singlets to HTO 8 and HTO 3 that have a low number of reads of HTO 2 or HTO 6 that the cutoff reads for those two HTOs also get classified as positive for HTO 2 or HTO 6, so they get classified as doublets. I was hoping I can recover those cells that were classified as doublets HTO 8 + HTO 2 or HTO 6 and HTO 3 + HTO 2 or HTO 6. I was thinking of applying some sort of ratio to the doublets where if over 50% of the total reads for cell come from the reads for a single HTO, then it is probably a singlet for that HTO. This would mainly rescue cells that were classified as HTO 8 and HTO 2 or 6 doublets (that have for example 1300 reads for HTO 8, but 20 reads for HTO 2 which makes them positive for both). Is there any approach that you think would be worth applying to rescue some of these doublets and include them in our analysis?

**Comment by torkencz** [comment]
Hi,
This is a difficult question as you don't want to include cases of real doublets from your data. I would recommend doing your fraction approach and seeing if the distribution has a bimodality to it (take cases which have low HTO2 and HTO6 reads). Calculating a HTO diversity measure such as Shannon entropy across HTO-s can also help. Also, visualizing on a UMAP and seeing if you have clusters with high entropy/fraction may also inform you on which cells to keep. Good luck.
