### ISSUE TITLE
Support for large matrices

### ISSUE THREAD

**Issue by ctrhodes** [satijalab/seurat#4380]
As mentioned in issue #1644, the sparse matrices used for count data cannot hold more than 2^32-1 non-zero elements. Is there any support for interaction with on-disk objects (i.e. loom) with Seurat V4?

Using SeuratDisk and/or loomR this would seem doable, but all options I've seen regarding hdf5 support on the Seurat and SeuratDisk websites suggests data is loaded from a hdf5 object and converted to a sparse matrix (not viable for matrices > 2^32-1 non-zero elements) prior to creating a Seurat object.

Last, as mentioned in issue #1868, the loom branch of Seurat that had functionality for loom objects ( i.e. NormalizeData(object = 'path/to/loom.loom', overwrite = TRUE, display.progress = FALSE) ) appears outdated and at least one dependency is no longer on CRAN.

If there is documentation for this type of functionality could you please point to it?

**Comment by timoast** [comment]
This is a longer-term goal that we are working on, but we do not currently support on-disk computation or other sparse matrix formats in Seurat

**Comment by sscien** [comment]
Is this issue still not being fixed?

**Comment by zhanghao-njmu** [comment]
You can try to use the modified version https://github.com/zhanghao-njmu/seurat which I have created a pull request #6527. 

I change the integration matrix format to ["spam"](https://cran.r-project.org/web/packages/spam/index.html) or ["spam64"](https://cran.r-project.org/web/packages/spam64/index.html) to process matrices with more than 2^31-1 non-zero elements. 

**However, it is important to note that processing large data requires sufficient memory.** 
I tested the modified version on the data with more than **200,000 cells**. The maximum memory used during the calculation was **1TB**.

**Comment by shahrozeabbas** [comment]
Hi @zhanghao-njmu would you be able to make the same changes to Signac for scATAC-seq? Might be a huge ask, but would be super helpful, thanks!
