### ISSUE TITLE
Seurat_v4 MapQuery inconsistent colors for each cell type compare with ref

### ISSUE THREAD

**Issue by lijiacd985** [satijalab/seurat#4386]
Hi there,

I exactly followed the tutorial on line https://satijalab.org/seurat/articles/integration_mapping.html.

There is no error through all the scripts.

However, I got the result UMAPs, as you can see that the Query transferred labels is not consistent with ref in colors.

[WTy_ref-Wo1_map.anno.pdf](https://github.com/satijalab/seurat/files/6339332/WTy_ref-Wo1_map.anno.pdf)

I also checked the VlnPlot for cell type markers, which is consistent with ref.

Could you please help on this?

Thanks,

Best,

Jia

**Comment by timoast** [comment]
Please include the full code you're running and the output of `sessionInfo()`
