### ISSUE TITLE
How do I color UMAP by sample id?

### ISSUE THREAD

**Issue by algebio** [satijalab/seurat#4387]
Hi

Sorry for this very basic question, I am quite new to Seurat. I tried to find the answer before asking with no much success here. 

I am using the Seurat v4 pipeline "Using Seurat with multimodal data". I have used 4 samples from my own data which I have merged into a Seurat object. Now I am trying to color the UMAP by sample id so I can check for batch effect. 

I would appreciate any help by sharing the code missing in the pipeline to color by sample or by sharing any link to any tutorial to learn this.

Thanks in advance.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  To find out how to do things like this with different functions I suggest checking out the manual entries for the various functions you are interested in.  In this case you are looking for the `group.by` parameter for `DimPlot`.

Best,
Sam
