### ISSUE TITLE
could not find function "as.loom" Traceback:

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#4388]
I was trying to convert my Seurat object into loom:

```
library(loomR)
tempS.loom <- as.loom(tempS,
            filename="5k.loom",
            verbose=FALSE)
```

But then got this error:
`Error in as.loom(tempS, filename = "5k.loom", : could not find function "as.loom"
Traceback:`

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Please see conversion vignette and SeuartDisk package for loom conversion.  [https://satijalab.org/seurat/articles/conversion_vignette.html](https://satijalab.org/seurat/articles/conversion_vignette.html).

Best,
Sam

**Comment by nsleep** [comment]
Try install SeuratDisk package.
```remotes::install_github("mojaveazure/seurat-disk")```
