### ISSUE TITLE
Mapquery between an Unknown Dataset and Annotated Dataset

### ISSUE THREAD

**Issue by dg520** [satijalab/seurat#4389]
Thanks providing the nice tutorial materials for Seurat v4. 

**Description of situation:** I'm trying to figure out cell types in a 2D-cultured cell line by comparing to an annotated in vivo data. Biologically, we know this 2D-cultured cell line should enrich for the early stage cells. The reference annotation contains multiple cell types, and early stage cells are not the largest population. In another word, the query and the reference do not have the same cell types. 

**Workflow and results:** I tried to do this via `MapQuery` approach [here](https://satijalab.org/seurat/articles/integration_mapping.html). And I applied `project.query = T` in `FindTransferAnchors`, as my query set has ~30,000 cells while the reference set has ~10,000 cells. There are only ~100 anchors detected between query and reference. Considering the query only contains a small population of cells in the reference, this seems to make sense for me. In addition, the prediction from the `TransferData` step has assigned 2D cells with "early stage" tags as expected. 

However, those "early stage" 2D cells distributed so differently in the ref.UMAP space, compared to those reference cells. Please see the figure below:

![test1](https://user-images.githubusercontent.com/18011036/115452000-e23d8080-a1eb-11eb-8a33-301b2191b0a0.png)

My questions are:
1. Is the prediction result from `TransferData` robust? 
2. Why the projected UMAP and the prediction from `TransferData` don't agree each other? Is it because of limited number of anchors?
3. Is `MapQuery` approach suits this task? Or should I take a marker-driven approach instead?
 
I attached my code here:
```
#both srt.ref and srt.query has been normalized via SCTransform

srt.ref = RunUMAP(srt.ref, dims = 1:30, reduction = "pca", return.model = TRUE, verbose = FALSE)

srt.anchors = FindTransferAnchors(reference = srt.ref, query = srt.query, normalization.method = "SCT", dims = 1:30, project.query = T)

srt.query = TransferData(anchorset = srt.anchors, reference = srt.ref, query = srt.query, refdata = list(celltype = "Annotation"))
srt.query = IntegrateEmbeddings(anchorset = srt.anchors, reference = srt.ref, query = srt.query, new.reduction.name = "ref.pca")
srt.query = ProjectUMAP(query = srt.query, query.reduction = "ref.pca", reference = srt.ref, reference.reduction = "pca", reduction.model = "umap")

p1 = DimPlot(srt.ref, reduction = "umap", group.by = col.celltype, label = TRUE, label.size = 3, repel = TRUE) + ggtitle("Reference") + NoLegend() + xlim(c(-10,15)) + ylim(c(-15,10))
p2 = DimPlot(srt.query, reduction = "ref.umap", group.by = "predicted.celltype", label = TRUE, label.size = 3, repel = TRUE) + ggtitle("Query") + xlim(c(-10,15)) + ylim(c(-15,10))
p1 + p2
```

**Comment by timoast** [comment]
Have you tried this with `project.query=FALSE`? Even though you have more cells in the query, if the reference is more diverse you're probably better off projecting the query onto the reference PCA.

**Comment by dg520** [comment]
@timoast Really appreciate your insight!

And I apologize that I made a mistake in the original post: the figure I there was actually generated using `project.query = FALSE`. 
And below I attached the figure generated using `project.query = TRUE`:
![test1](https://user-images.githubusercontent.com/18011036/115806969-bc63d780-a3b5-11eb-99ac-1865f3ac8ed2.png)

With the projection onto the query PCA, the query and reference have a comparable distribution now. However, the label transfer seems to be a bit weird. The "Early" cell are everywhere, overlaying the space belonging to "NPC" and "Ex_cor" in the reference UMAP space. A quick summary of transferred label here:
```
> table(srt.query$predicted.celltype)

Astro Early  Endo   NPC 
    1 34242   911   542 
``` 

I tried to check if the outliers of "Early" reference cells drove the projection. I hidden the cells other than "Early" in the reference UMAP space to examine outliers of "Early" population. Howver, I didn't find any cell distributing as an outlier (figure attached below). 

![test2](https://user-images.githubusercontent.com/18011036/115807938-7f004980-a3b7-11eb-8411-e53b9b70c67d.png)
 
Could you please give my some suggestions why the "Early" labels have been assigned to cells in other areas in the projected UMAP?  Thanks a lot!

**Comment by timoast** [comment]
Which version of Seurat are you using? Can you show the output of `sessionInfo()`?

**Comment by dg520** [comment]
@timoast Here is my version information:
```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] circlize_0.4.12       pheatmap_1.0.12       ape_5.4-1             ClusterMap_0.1.0      org.Mm.eg.db_3.12.0  
 [6] org.Hs.eg.db_3.12.0   annotate_1.68.0       XML_3.99-0.6          GO.db_3.12.1          GOstats_2.56.0       
[11] graph_1.68.0          Category_2.56.0       Matrix_1.3-2          AnnotationDbi_1.52.0  IRanges_2.24.1       
[16] S4Vectors_0.28.1      Biobase_2.50.0        BiocGenerics_0.36.0   ggrepel_0.9.1         WGCNA_1.70-3         
[21] fastcluster_1.1.25    dynamicTreeCut_1.63-1 RColorBrewer_1.1-2    corrplot_0.84         ggplot2_3.3.3        
[26] matrixStats_0.58.0    sctransform_0.3.2     SeuratObject_4.0.0    Seurat_4.0.1   
```

Not sure if this helps but my query data is an integrated data from three `SCTransform` normalized datasets. Please see the code below for integration process to generated query data:
```
DefaultAssay(merged)="RNA"
srt.list = SplitObject(merged, split.by = "Batch")
srt.list = lapply(srt.list, FUN = SCTransform, vars.to.regress = NULL, method = 'offset')
features = SelectIntegrationFeatures(srt.list, nfeatures = 3000)
srt.list = PrepSCTIntegration(srt.list, anchor.features = features)
srt.list = lapply(srt.list, FUN = RunPCA, features = features, verbose = FALSE)
srt.anchors = FindIntegrationAnchors(srt.list, normalization.method = "SCT", anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 20)
srt.combined = IntegrateData(anchorset = srt.anchors, normalization.method = "SCT", dims = 1:30)

srt.combined = RunPCA(srt.combined, verbose = FALSE)
srt.combined = RunUMAP(srt.combined, reduction = "pca", dims = 1:30, return.model = TRUE)

srt.query = srt.combined
```
I checked the `DefaultAssay` of query used for label transfer is indeed "integrated".

**Comment by yuhanH** [comment]
Hi, 
In the mapping workflow, you'd better not set `project.query = TRUE` and you can leave it as FALSE by default.
I think the issue may result from the missing parameter in `reference.reduction`.  You need to set `reference.reduction = 'pca'` in `FindTransferAnchors`.
```
srt.anchors = FindTransferAnchors(reference = srt.ref, query = srt.query, normalization.method = "SCT", dims = 1:30, reference.reduction = 'pca' )
```

**Comment by dg520** [comment]
@yuhanH Thanks heaps for your suggestion. Setting `reference.reduction = "pca"` made the result much better and more convincing. 
![test3](https://user-images.githubusercontent.com/18011036/115914581-22953c80-a440-11eb-99e5-22e37f2ced36.png)

I thought  `reference.reduction = "pca"` was the default, as in `?FindTransferAnchors` it says: 
```
reference.reduction Name of dimensional reduction to use from the reference if running the pcaproject workflow. Optionally enables reuse of precomputed reference dimensional reduction. If NULL (default), use a PCA computed on the reference object.
```
But I just realized upon your suggestion that the default value actually is set as `pcaproject` instead during the function initiation.

Thanks again for your help! @timoast @yuhanH .

**Comment by yuhanH** [comment]
hi, @dg520 
Right. `project.query = TRUE` mainly means that you project your reference cells to the query PCA.
