### ISSUE TITLE
Should I SCTransform after each subset()?

### ISSUE THREAD

**Issue by duocang** [satijalab/seurat#4392]
Hi.

There is a `Seurat` object with 5000 cells and 20k genes from one experiment, I used `SCTransform` to normalize it.

For DE analysis, I used `subset(seu.obj, cells=cortex.cells)` to get a smaller `Seurat` object for `FindMarkers` and `DoHeatmap` of certain cell types.

Should I run `SCTransform` each time after using `subset`?

**Comment by timoast** [comment]
Please see https://github.com/satijalab/seurat/issues/4320 and https://github.com/satijalab/seurat/discussions/4032
