### ISSUE TITLE
Removal of HTO sample from Seurat Object

### ISSUE THREAD

**Issue by gorrymc** [satijalab/seurat#4396]
I am trying to completely remove a sample that was included in the matrix.mtx , barcode and feature files 
that were provided to me.  In my case, all samples were eventually placed in the hash.ID slot.

A teaching example would be 
Demultiplexing with hashtag oligos (HTOs)

This example provides for the analysis of 8 HTO samples (HTO-A, HTO-B, etc)  Is there something that could be 
done to delete, filter, block etc. the HTO-E data from any analysis that is done?  Most of the available information
that I have been able to find deals with single cells or clusters that have been created.
 
Thanks

Mike

**Comment by samuel-marsh** [comment]
Hi Mike,

Not member of dev team but hopefully can be helpful.  You can use the `subset` command to filter objects based on a desired parameter (see manual entry for more info).  In this case if `hash.id` is the name of the `meta.data` column specifying the hash you want to remove then:
```
obj <- subset(x = obj, subset = hash.id == "HTO-E", invert = TRUE)
```

Or if the hash.id is the active ident in the object you can also use:
```
obj <- subset(x = obj, idents = "HTO-E", invert = TRUE)
```

Best,
Sam

**Comment by gorrymc** [comment]
Yes. Thank you.

I worked on getting the HTO-E sample removed and keeping the remaining 7 samples. Then I checked
if the FIND functions produced altered conclusions.  This let me deal with my less than optimal data 
and remove samples that needed to be rerun.  

Mike
