### ISSUE TITLE
Errors in subset with specific genes which name starts with number

### ISSUE THREAD

**Issue by Bongjun86** [satijalab/seurat#4397]
I have been started with Seurat since about two month ago.

I am trying to subset my seuratobject with specific genes using code below

```
object_subset <- subset(x = object, subset = 2810417H13Rik > 0)
```

However, it doesn't work with error message "Error: unexpected symbol in... "

In same case, with another gene such as Mki67 instead of 2810417H13Rik, the code works well.

I made FeaturePlot, DotPlot, and VlnPlot with the gene, 2810417H13Rik. It means the information of gene, 2810417H13Rik, is in my object.

Would you please let me know how to do?

In my think, it might be due to the name of gene, 2810417H13Rik, starts with several numbers. In the R script, 2810417 marked with blue among 2810417H13Rik.

**Comment by yuhanH** [comment]
Hi, 
I agree with you that this error is due to the name of gene. You can use extract those cells name and subset the object based on the cell name. 
```
select.cells <- Cells(object)[ which( object[["RNA"]]@data["2810417H13Rik" ,] > 0   ) ]
object <- subset(object, cells =  select.cells)
```
