### ISSUE TITLE
PCs not calculated correctly in FastPCA() from irlba() output?

### ISSUE THREAD

**Issue by sriesenfeld** [satijalab/seurat#44]
Hi Rahul et al, 
As far as I can tell, in FastPCA(), the object@pca.rot is computed as the matrix of left singular vectors:
pca.obj = irlba(t(pc.data),nv = pcs.compute,...)
...
object@pca.rot=data.frame(pca.obj$u[,1:pcs.store],row.names = colnames(pc.data));

However, the projected data matrix, which is what is stored in object@pca.rot by the regular PCA() function, should be computed by multiplying the left singular vector matrix (the U matrix) by the actual singular values. 

I am not sure why Seurat did not just use the wrapper function prcomp_irlba(), but if you look at the code for that function in
https://github.com/cran/irlba/blob/master/R/prcomp.R
you can see that the return value called "x" in the returned list is computed as the product I am referring to:

s <- do.call(irlba, args=args)
....
ans <- c(ans, list(x = s$d * s$u))

The matrix x is what Seurat typically stores in object@pca.rot, as that is what tSNE, etc, operates on.

A separate point: I really think the documentation for Seurat should make it much more evident that when the PCA() function is run with default arguments (i.e., rev.pca==FALSE) (as it should normally be called, since the genes are indeed the variables), the Seurat object stores the projected data matrix, which is called "x" by prcomp(), in the object@pca.rot slot, while it stores the eigenvector matrix, which is called "rotation" by prcomp(), in the object@pca.x slot. This non-conventional naming scheme should be made clear without forcing people to do a lot of digging in the code, since it is very confusing otherwise.

**Comment by satijalab** [comment]
Hi Sam - we agree that slots storing PCA information were confusing and poorly named. We've fixed these issues in the most recent release, along with the irlba issue you raised. We now explicitly include a weight.by.var flag that addresses the irlba vs. prcomp issue you described as well.
