### ISSUE TITLE
How to explain and interpret discrepancies between UMAP and clustering?

### ISSUE THREAD

**Issue by miscellaneousj** [satijalab/seurat#4400]
I'm using Seurat v3.2.0. Sometimes I find that a single cluster identified by FindClusters() is separated into two or more spatially separated groups on the UMAP (see attached example 1 - the two distinct groups of cluster 6 cells are encircled). (For clarity, I will refer to spatial clusters on the UMAP as 'groups' and SNN graph-based clustering as clusters.) I've tried to find the differences between these clusters by increasing the clustering resolution parameter, but sometimes even increasing the resolution as high as 5.0 isn't enough to discriminate the two (or more) groups, and meanwhile other more homogenous-looking groups on the UMAP have split into 100 different clusters. Even isolating a problematic cluster for subclustering (example 2), I am unsure what is causing the discrepancy as I have to set the resolution parameter very high to discriminate clusters that are clearly separated on the UMAP and findmarkers reveals minimal differences.

Obviously different algorithms will produce different results, but I'm so far unable to find any insight into why this happens and my attempts to alter various parameters to harmonise the UMAP and clustering results have not been successful. I'd really appreciate any information or advice on this to better understand my data and these algorithms.

```
library(Seurat)
DefaultAssay(seu.obj) <- "integrated"
seu.obj <- ScaleData(seu.obj, verbose = FALSE)
seu.obj <- FindVariableFeatures(seu.obj, selection.method = "vst", nfeatures = 3000)  

seu.obj <- RunPCA(seu.obj, npcs = 50, verbose = FALSE)  

seu.obj <- RunUMAP(seu.obj, dims = 1:20)
seu.obj <- FindNeighbors(seu.obj, dims = 1:20)
seu.obj <- FindClusters(seu.obj, resolution = 0.7)

DimPlot(seu.obj, reduction = "umap", 
 pt.size=1, label.size=5,
  label=TRUE, ncol=4) +
 NoLegend() 

DefaultAssay(seu.obj) <- "RNA"
markers <- FindAllMarkers(seu.obj, only.pos = T, min.pct = 0.25,
   logfc.threshold = 0.25)

```

![splitclusterexample1](https://user-images.githubusercontent.com/70999233/115701031-ec04e680-a399-11eb-946c-ccf38f8e67c2.png)
![splitclusterexample2](https://user-images.githubusercontent.com/70999233/115701035-ed361380-a399-11eb-86cf-0aa2e385b299.png)

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/1081

You can also try different community detection methods by changing the `algorithm` parameter in `FindClusters()`

**Comment by yesitsjess** [comment]
Hi, did you find an answer to this? I'm experiencing something similar (Louvain and SLM show the same UMAP split cluster)
