### ISSUE TITLE
MixscapeLDA Error - mixscape

### ISSUE THREAD

**Issue by pmb59** [satijalab/seurat#4401]
Dear Seurat developers
Any idea why I might be getting the error below? I'm using Seurat_4.0.1 
thanks

> sub <- MixscapeLDA(
  object = sub, 
  #ndims.print = 1:3,
  #nfeatures.print = 5,
  assay = "RNA", 
  pc.assay = "PRTB", 
  labels = "gene", 
  nt.label = "NT", 
  npcs = 10, 
  logfc.threshold = 0.1, 
  verbose = T)
Ctcf
Finding new perturbation gene set
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Ctcf
Error in `$<-.data.frame`(`*tmp*`, "lda_cluster_label", value = c("Ctcf",  : 
  replacement has 3519 rows, data has 0

**Comment by epapalexi** [comment]
Hi Pedro,

I am not sure what is going on here. Can you please share the full code and some data that I can replicate the error with?

Efi
