### ISSUE TITLE
differential analysis using batch information

### ISSUE THREAD

**Issue by rtyags** [satijalab/seurat#4403]
Hi, we have a case-control design with replicates that I want to use for differential gene analysis. I understand that while I can use seurat3 integration to find clusters and visualize the data, the resulting transformed values shouldn't be used for DE. However, I did not see any option in "FindMarkers" which would help in using the batch information to increase the power of DE identification. I have seen it being mentioned that MAST can be used with batch information, but I can't find how to do this when I use "MAST" method with "FindMarkers".

**Comment by torkencz** [comment]
Hi I would recommend using a FindConservedMarkers with your case-control metadata variable used as the group.by variable.
