### ISSUE TITLE
The dimensions of 'data slot matrix' in SCT assay and spatial assay are different. 

### ISSUE THREAD

**Issue by ZhenyiWangTHU** [satijalab/seurat#4404]
Hi Seurat team,
I used Seurat v.3.2.1 to analyze a 10X spatial data as your vignette(https://satijalab.org/seurat/archive/v3.2/spatial_vignette.html). And I fetched the matrices in 'data slot' of SCT assay and spatial assay. But I noticed that the number of rows(genes) of the matrix fetched from the SCT assay is less than that from the spatial assay. I'd like to know how does 'SCTransform' function filter genes in the 'data slot matrix'(not 'scale.data slot')? Thank you!
Regards,
Zhenyi

**Comment by timoast** [comment]
Please see the documentation for `Seurat::SCTransform()` and `sctransform::vst()`

**Comment by ZhenyiWangTHU** [comment]
> Please see the documentation for `Seurat::SCTransform()` and `sctransform::vst()`

Thank you for your quick response, but I didn't see any context in the documentation that can answer my question.
Maybe I didn't make my question clear before, please see the codes and outputs below:
**code:** dim(as.matrix(GetAssayData(object=sub_breastCancer,slot='data',assay = "Spatial")))
**output:** 36601, 543
**code:** dim(as.matrix(GetAssayData(object=sub_breastCancer,slot='data',assay = "SCT")) )
**output:** 21187, 543
I want to know why these two dimensions are different. Thanks again.
