### ISSUE TITLE
FindAllMarkers gives different results when SCT data slot and RNA data slot is used

### ISSUE THREAD

**Issue by Jay-Leung** [satijalab/seurat#4408]
Hi, 

I would like to check what the differences are between the SCT data slot and RNA data slot. From what I understand, the data slot in SCT assay stores lognormalised counts as well, which ideally should be the same as RNA data slot if I run NormalizeData right? I did not do any integration and just used SCTransform for normalization and regression of cycling/mito genes. 

However, when I used RunAllMarkers with RNA data slot, I got 5402 variables, whereas using SCT data slot it returned 7807 variables..

Thanks for clarifying!

**Comment by saketkc** [comment]
The data slot does store lognormalized counts, however these counts have been corrected for sequencing depth.
You can verify tihs using `pbmc_small`:

![image](https://user-images.githubusercontent.com/682153/116724450-abffbe00-a9ae-11eb-873e-9fe12bb57980.png)

**Comment by Jay-Leung** [comment]
Thanks for clarifying - I am aware of the difference between the counts slot in SCT and RNA, but with regards to the data slots in both assays, what are the differences? Wouldn't the data slot in the RNA assay already have normalised for sequencing depth, prior to the normalized data being stored? Thanks!

**Comment by saketkc** [comment]
The data slot in RNA is simply `log1p(normalized_counts)` while in SCT this is `log1p(corrected_counts)`.  The normalized_counts are corrected for sequencing depth by using a "scale factor" approach - divide counts by total sequencing depth and scale it to 10k before log transformation. Does this make sense?

**Comment by Jay-Leung** [comment]
So the RNA data slot contains the log1p(normalized_counts), where normalization was done using the classical "scale factor" approach, whereas in the SCT data slot, it contains log1p(corrected_counts), where corrected counts are reverse calculated using the Pearson's residuals - am I correct?

In that case, wouldn't it be more ideal to do FindAllMarkers and DE analysis using the SCT data slot, since it also stabilizes the variance for the genes? Thanks!
