### ISSUE TITLE
Cannot color cells with 0 expression in certain color

### ISSUE THREAD

**Issue by Leran10** [satijalab/seurat#4409]
Hi, ![image](https://user-images.githubusercontent.com/17597071/116121633-6e392780-a686-11eb-9c77-92058503f07e.png)
I'm trying to use FeaturePlot() function, but when there is a gene has 0 existence in all cells (the right most one), that plot was colored to a dark scale which I expected it to be all gray. 

My command is:
feature.plot <- FeaturePlot(combined.all, features = c("Ifnlr1","Ifnl2","Ifnl3","Stat1","Isg15","Murine-astrovirus-STL1","Murine-astrovirus-STL5"), split.by = "modified.ident", cols = c( "gray","red"),reduction = "tsne")

I saw similar questions and one answer was to modify the cols = c( "gray","red") parameter to cols = c( "gray","gray"), however in that case other plots would not be able to correctly colored.

Is there anyway that I can have the figures combined and also have the correct colors for any scenarios?

Also, I cannot get the legend show up when I use combine = TRUE parameter, is there anyway that I could have a legend show in the combined plot?

Thanks so much!
Leran

**Comment by timoast** [comment]
What version of Seurat are you using? Can you show the output of `sessionInfo()`?
