### ISSUE TITLE
JackStraw use all cores?

### ISSUE THREAD

**Issue by z5ouyang** [satijalab/seurat#441]
Just noticed that jackStraw ignore "do.par" and "num.cores", but use all cores.
Could you please confirm this? Using Seurat 2.3.0

Thanks

**Comment by leonfodoulian** [comment]
Hi,

This shouldn't be the case. The only thing to keep in mind is that if `do.par = TRUE`, and `num.cores = 1`, then it will use half of the available cores of the machine. You can check the code at [lines 91 to 107 in jackstraw.R](https://github.com/satijalab/seurat/blob/cfc2f29b448cd92204099264d3b6cf9737a82e85/R/jackstraw.R#L91-L107).

Best,
Leon

**Comment by mschilli87** [comment]
@leonfodoulian wrote
> The only thing to keep in mind is that if do.par = TRUE, and num.cores = 1, then it will use half of the available cores of the machine.

This is good to know. :open_mouth: 
I think it's a nice but hidden feature.

Just in case, to avoid future confusion, I suggested to warn in that case: https://github.com/satijalab/seurat/pull/444

**Comment by z5ouyang** [comment]
The code is running on a cluster, it definitely used all the cores, when I run "JackStraw". Not sure how could I show it?
I also noticed, that after I terminated the JackStraw, all R-processes started by JackStraw is still there (not using any core), unless I quite from R environment. Then if I get in R environment again, all those process just showed up (not using any core either), even I didn't save the environment during last quite. If I run "parallel::detectCores()", all processes will be gone.
Any suggestions?

**Comment by z5ouyang** [comment]
![screenshot from 2018-04-27 13-03-42](https://user-images.githubusercontent.com/30639029/39382837-c6faa76a-4a1b-11e8-899d-0adb90ed2db1.png)
![screenshot from 2018-04-27 13-02-48](https://user-images.githubusercontent.com/30639029/39382838-c7102928-4a1b-11e8-8369-ad39f24b8a6a.png)

**Comment by z5ouyang** [comment]
![screenshot from 2018-04-27 13-09-38](https://user-images.githubusercontent.com/30639029/39383181-24617bd0-4a1d-11e8-9f42-4f1121e541be.png)
![screenshot from 2018-04-27 13-10-21](https://user-images.githubusercontent.com/30639029/39383157-13c4e460-4a1d-11e8-93e4-420c70f3b249.png)
![screenshot from 2018-04-27 13-13-25](https://user-images.githubusercontent.com/30639029/39383167-1887d5b6-4a1d-11e8-98eb-ea812b60cb28.png)
![screenshot from 2018-04-27 13-13-57](https://user-images.githubusercontent.com/30639029/39383172-1b478dbe-4a1d-11e8-8cc1-edeb5fab84ac.png)

**Comment by z5ouyang** [comment]
ok, I think it is not the seurat issue, but how our server was set up. Thanks all for help.
