### ISSUE TITLE
Is there any way to make the blended graph "binary"? 

### ISSUE THREAD

**Issue by nkomarov1410** [satijalab/seurat#4410]
I am trying to show co-expression of 2 genes but it appears that the scales of expression are very different. For example: 

![ppk23_pain_featureplot copy](https://user-images.githubusercontent.com/81174134/116227799-ce969a80-a754-11eb-9a2c-8920da99aa5f.png)

I have the same cell (circled) expressing the first gene weakly, and the second gene strongly . 

If I add blend=T, then the cell doesn't show up: 

![ppk23_pain_featureplot_blend](https://user-images.githubusercontent.com/81174134/116228071-1cab9e00-a755-11eb-9fda-9a33cc9e1989.png)

I think the issue is that the scale is normalised in the blend mode, but would it be possible to have the "scale" as binary? i.e. if expressed (any amount) then blue, if not expressed then grey. 

I don't want to see relative expression, I just want to see any co-expression 

Thanks in advance!

**Comment by andrewwbutler** [comment]
Hi,

That functionality isn't currently built into `FeaturePlot` but you could get something similar by simply creating a binarized assay and plotting that instead. E.g.

```R
library(Seurat)
library(SeuratData)

FeaturePlot(pbmc3k.final, c("CD3D", "CD3E"), blend = TRUE)
dat <- GetAssayData(object = pbmc3k.final[["RNA"]], slot = "data")
dat[dat>0] <- 1
pbmc3k.final[["binary"]] <- CreateAssayObject(data = dat)
DefaultAssay(pbmc3k.final) <- "binary"
FeaturePlot(pbmc3k.final, c("CD3D", "CD3E"), blend = TRUE)
```
