### ISSUE TITLE
data integration with missing markers

### ISSUE THREAD

**Issue by ttsunmeng** [satijalab/seurat#4412]
I need some urgent help in integrating my datasets. I have three targeted scRNAseq datasets each with different number of genes sequenced. So when I used the integration methods I found for the non-overlapping genes they either were estimated by a range of counts or assign straight zeros on that. It does not always the same way and I actually prefer to have the non-overlapping genes estimated as a range instead of assigning all zeros. How could I work with it? Does it have anything to do with the order of the datasets they try to integrate? I tried to change the order and found it is still the same. I also tested on both rPCA and CCA methods and found they choose alternative ways for the non-overlapping genes, which are not consistent. Is there a good way to handle this estimation on non-overlapping/missing gene counts?

**Comment by timoast** [comment]
Hi, not sure what you mean exactly that the missing values are estimated by a range of counts. Can you include the code you're running? To run the integration, common features must be present across the datasets to be integrated.

**Comment by timoast** [comment]
You're looking at the integrated data here, so it's effectively imputing the expression of the missing features (since you first merge and split the datasets, the missing features are filled with 0). We don't recommend using the integrated data for visualization, or differential expression.
