### ISSUE TITLE
 Sc-atac with Sc-rna  integration problem

### ISSUE THREAD

**Issue by ahmadsam66** [satijalab/seurat#4416]
Hello

I have tried to integrate sc-atac with sc-rna. Using following tutorial of Signac, I used similar code  below to give label to our clusters :
```
new.cluster.ids <- c("Naive CD4 T", "CD14+ Mono", "Memory CD4 T", "B", "CD8 T", "FCGR3A+ Mono", 
    "NK", "DC", "Platelet")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
```

https://satijalab.org/signac/articles/mouse_brain_vignette.html

However I faced with the error subclass is not found :
```
predicted.labels <- TransferData(
  anchorset = transfer.anchors,
  refdata = allen_rna$subclass,
  weight.reduction = brain[['lsi']],
  dims = 2:30
)
```

How can I introduce subclass label for my scRNA object ?

Thanks.

**Comment by timoast** [comment]
The `refdata` parameter specifies the data in the reference dataset to be transferred to the query, and will of course vary depending on the specific dataset you are using. See the documentation for `TransferData()` for more information
