### ISSUE TITLE
VariableFeaturePlot - residual variance threshold excluding some genes as variable features

### ISSUE THREAD

**Issue by oe98** [satijalab/seurat#4417]
Hello, I was wondering if anyone could help me understand why some features are not being chosen as variable features despite passing the set residual variance cut-off value. 

The plot below was generated from an object after running SCTransform in Seurat with 

`SCT <- SCTransform(object = seurat, verbose = TRUE, variable.features.n = NULL, variable.features.rv.th = 1.3, return.only.var.genes = FALSE)

VariableFeaturePlot(SCT)`

[variable_feature_plot_odd.pdf](https://github.com/satijalab/seurat/files/6398301/variable_feature_plot_odd.pdf)

Some features (70 in total) have a greater residual variance than 1.3, but aren't being chosen as variable features for downstream analysis and I can't work out the reasoning for this. Thank you!

**Comment by saketkc** [comment]
Hi @oe98, I am not able to replicate this at my end. Would it be possible to send the object to schoudhary@nygenome.org?
You can anonymize the gene-cell information if you wish.
