### ISSUE TITLE
how is seurat computing logcounts?

### ISSUE THREAD

**Issue by gabrielet** [satijalab/seurat#4418]
I left a question in BioStar about how is seurat computing **logcounts**. I hope to get an answer here, because there is something which I am not getting.

So, I happen to have single cell data from BD Rhapsody technology. What I do is to load the raw count data, i.e. the count matrix, using the `CreateSeuratObject()` function. At this point, using the function `as.SingleCellExperiment()` I obtain an `sce` object that I can use for downstream analysis.

Point is that when I look and the `sce` object, it has two assays, one containing the counts and the other containing the **logCounts**.

I am wondering from where those **logCounts** are coming and if they are reliable and I can use them as they are? Is there a normalisation step somewhere into the two mentioned function that I am missing?

To give an idea of the code:

```
# remove cell indexes, i.e. first column, and transpose matrix with raw data
transposed <- t(rawD[, -1])

# set colnames using the cells indexes
colnames(transposed) <- rawD$Cell_Index
# set row names as gene names, i.e. colnames(rawD)
rownames(transposed) <- featNames

# create Seurat object
cMatrix <- CreateSeuratObject(counts=transposed)

# and transform it into a SingleCellExperiment
# https://satijalab.org/seurat/v3.1/conversion_vignette.html
abSce <- as.SingleCellExperiment(cMatrix)
```

Now `abSce` contains the mysterious **logCounts**:

```
class: SingleCellExperiment 
dim: 23159 2380 
metadata(0):
assays(2): counts logcounts
rownames(23159): A1cf A26c3 ... n.TYgta3 n.TYgta8
rowData names(0):
colnames(2380): 656575 253547 ... 779118 760123
colData names(5): orig.ident nCount_RNA nFeature_RNA ident antiB
reducedDimNames(0):
altExpNames(0):
```

I also just found out that:

```
all(assay(mergedSce, "logcounts") == assay(mergedSce, "counts")) 
[1] TRUE
```

which basically means that the **logcount** assay is not an actual **logcount** but it's a simple copy of **counts**

Am I right? If yes, then why creating it?

**Comment by timoast** [comment]
You didn't run any normalization here, so the `data` slot is indeed un-normalized counts. If you ran `NormalizeData` this would not be the case

**Comment by gabrielet** [comment]
Thank you for your reply. I just wanted to add that the actual problem here is, as I see it, the documentation that does not explicitly mention you must normalise the data found in the **logcounts** assay. Indeed, if I create a singleCellExperiment from a Seurat object and I find myself with a **logcounts** assay, I may just assume that the function performed the necessary normalisation steps. But, that didn't happen and the normalisation should be performed in another step.

**Comment by HaikuoLi** [comment]
> 

Thanks for pointing out this question which I also encountered and found this issue very helpful.
