### ISSUE TITLE
SCTransform on a subset of transcripts?

### ISSUE THREAD

**Issue by nmshahir** [satijalab/seurat#4428]
Hello,
Is it possible to perform SCTransform on a subset of transcripts? I have human and non-human transcripts and I wish to treat them seperately.

Thank you!

**Comment by JoyOtten** [comment]
Hi,

If you divided your transcripts by ID you can subset the transcripts with SplitObject(data, split.by = ID) and then perform SCTransform separately. I hope this will help you.

**Comment by nmshahir** [comment]
> Hi,
> 
> If you divided your transcripts by ID you can subset the transcripts with SplitObject(data, split.by = ID) and then perform SCTransform separately. I hope this will help you.

So my understanding of SplitObject is that it splits the original Seurat object by cell? And that's not what I wish to do. I want to normalize human transcripts and non-human transcripts seen in the cells separately.
