### ISSUE TITLE
Hi, is it possible to run integration analysis on multiple multiome dataset using WNN approach. if so, can you please provide some tips.

### ISSUE THREAD

**Issue by khandaud15** [satijalab/seurat#4429]

**Comment by yuhanH** [comment]
Hi,
You can do the batch correction in RNA and ATAC modality respectively, and run WNN analysis for the batch-corrected RNA and ATAC. This is a similar issue: https://github.com/satijalab/seurat/issues/3890
The ATAC integration workflow is in the [vignette](https://satijalab.org/signac/articles/integration.html) in Signac. 
Also, we are working on a multimodal anchor framework which uses one set of multimodal anchors to correct both RNA and ATAC. Stay tuned.
