### ISSUE TITLE
To compare three genotypes, should I do an integrated analysis?

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#443]
Hi group!

Thanks a lot for your toolkit Seurat, it is amazing! I would like to know your opinion about somthing I am concerned about. I have done single-cell RNA seq in cortex from three differente genotypes (two control and one experimental mice) to compare one population of neurons. The experiments were done 4 different days, but each of these days all three genotypes were run to avoid batch effect as possible. Then, data from all cells from each genotype were mixed and three datasets were constituted. Now, I am concerned about whether I should perform a basic analysis taking all datasets together, do the filtering, normalization, scaling and so on and then cluster grouped by genotype; or I should perform an integrated analysis, where I filter, normalize and scale each dataset separatly and then integrate datasets to also cluster by genotype and look for shared and different populations between genotypes. I think I should do this last option but maybe I am wrong. 
What would you recommend?

Thanks a lot in advance!
Best,
Marina

**Comment by satijalab** [comment]
In general, we suggest running our integration workflow when shared subpopulations across datasets  are not identifiable under a standard workflow. Particularly when the batch or sample-dependent effects are small (in comparison to the biology), they may not play a significant role in the analysis.

For example, in our PBMC integration vignette, each condition (stimulated and control data) consists of cells from multiple patients. However, the patient-specific batch effect is very small, and does not confound the downstream analysis, so we only integrate across conditions.

**Comment by mvalenzuelav** [comment]
So, should I try to do both analysis and compare if shared populations are identifiable by both of them? 
In case I decide to do only the integrated one, would this be valid or may I be losing something?
Thanks!
