### ISSUE TITLE
How can we speed up FindMarkers

### ISSUE THREAD

**Issue by KANG-BIOINFO** [satijalab/seurat#4434]
Hi,

Thanks for the awesome package for single-cell analysis. I was using FindAllMarkers function and found the marker identification is relatively slower than the corresponding function of Scanpy. Usually for a data with tens of thousands cells (e.g. 50K cells), this function would take more than 10 minutes to finish. I tried to use future for parallel computation, but the improvement is not very big. May I ask if there're plans for improvement of the running speed for FindAllMarkers?

Thanks!

**Comment by timoast** [comment]
https://github.com/satijalab/seurat/discussions/4433
