### ISSUE TITLE
After filtering, HTODemux Error: Cells with Zero counts exist as a cluster.

### ISSUE THREAD

**Issue by rschauner** [satijalab/seurat#4435]
It seems like this issue has popped up a few times with #3557 and #2549. I updated Seurat and Bioconductor to the latest version. I have ~30 different libraries and want to demultiplex all of them. Previously my code has worked, but due to some issues I have to filter each library individually. On at least one of the libraries I get the error "Cells with zero counts exist as a cluster."

I then decided to filter the data:
```{r}
x <- GetAssayData(test, "counts")
cells <- colnames(x[ , colSums(x) != 0])
feats <- names((rowSums(x) != 0) == TRUE)
test[feats, cells] %>% NormalizeData(normalization.method = "CLR") %>% HTODemux()
```
After this, I still get the same error, but have verified that there are no features with zero counts and there are no cells with no counts. What could be the problem?

**Comment by torkencz** [comment]
Can you provide more information on your test data? Are you using the HTO assay?

**Comment by rschauner** [comment]
Yes, I confirmed today that the HTO assay is active. My test data is one library of my experimental data.

**Comment by jaisonj708** [comment]
If you'd like you can share your object (or a subsampled / dummy version that reproduces the issue) with us at seuratpackage@gmail.com.

**Comment by rschauner** [comment]
Hi, I just sent over two objects, one that successfully worked and one that hasn't (the object referenced above).

**Comment by jaisonj708** [comment]
Looking at your object, it seems like the HTO assay is empty- is this what you intended?  It would also help if you could share the code you ran and the associated error

**Comment by rschauner** [comment]
Interesting, I just checked and object[["HTO"]]@counts returns a sparse matrix on my end. If this isn't the case I might have to send you the data again (maybe a different way). I don't remember exporting the objects, maybe I didn't run the normalization prior to exporting? `N9[["HTO"]]@data |> dim()` gives me [4, 11514]. 

All I ran was `seurat <- NormalizeData(seurat, normalization.method = "CLR")` followed by `seurat <- HTODemux(seurat)` Where `seurat` one of the two objects I sent over.

**Comment by saketkc** [comment]
Do you still need help with this @rschauner?

**Comment by rschauner** [comment]
I don't think I do. I somehow worked around it.

**Comment by lwlive** [comment]
I have encountered  the sam question "Cells with Zero counts exist as a cluster". I found  some of the hashtags expressed little counts.  After I remove the hashtags with liitle count, the problems has been solved. Hope can help some of us.

**Comment by dxldxl123** [comment]
> 我不认为我这样做。我以某种方式解决了它。

Hi，May I ask how do you solve this problem?

**Comment by dxldxl123** [comment]
> 我遇到了 sam 问题“计数为零的单元格以集群形式存在”。我发现一些主题标签表示的计数很少。在我删除了带有 liitle count 的主题标签后，问题就解决了。希望可以帮助我们中的一些人。

Hi，May I ask how do you solve this problem?

**Comment by lwlive** [comment]
> > 我遇到了 sam 问题“计数为零的单元格以集群形式存在”。我发现一些主题标签表示的计数很少。在我删除了带有 liitle count 的主题标签后，问题就解决了。希望可以帮助我们中的一些人。
> 
> Hi，May I ask how do you solve this problem?


Hi， sorry for my late reply. 
for example, ten hash tags  were used to labeling eight different cell clusters. Then two or more hashtags ( some hashtags may fail in labeling cells) would have few counts or far less than the other hashtags. This kind of hashtags should be remove before  creating Seurat object.   It means it's necessary to compute the sum of the column in Antibody Capture matrix and remove hashtags with low reads counts.

wish my answer help you!

**Comment by dxldxl123** [comment]
> > > 我遇到了 sam 问题“计数为零的单元格以集群形式存在”。我发现一些主题标签表示的计数很少。在我删除了带有 liitle count 的主题标签后，问题就解决了。希望可以帮助我们中的一些人。
> > 
> > 
> > Hi，May I ask how do you solve this problem?
> 
> Hi， sorry for my late reply. for example, ten hash tags were used to labeling eight different cell clusters. Then two or more hashtags ( some hashtags may fail in labeling cells) would have few counts or far less than the other hashtags. This kind of hashtags should be remove before creating Seurat object. It means it's necessary to compute the sum of the column in Antibody Capture matrix and remove hashtags with low reads counts.
> 
> wish my answer help you!

Hi, May I ask how you define which hashtag should be deleted？Do we have any standard of this？

**Comment by lwlive** [comment]
> > > > 我遇到了 sam 问题“计数为零的单元格以集群形式存在”。我发现一些主题标签表示的计数很少。在我删除了带有 liitle count 的主题标签后，问题就解决了。希望可以帮助我们中的一些人。
> > > 
> > > 
> > > Hi，May I ask how do you solve this problem?
> > 
> > 
> > Hi， sorry for my late reply. for example, ten hash tags were used to labeling eight different cell clusters. Then two or more hashtags ( some hashtags may fail in labeling cells) would have few counts or far less than the other hashtags. This kind of hashtags should be remove before creating Seurat object. It means it's necessary to compute the sum of the column in Antibody Capture matrix and remove hashtags with low reads counts.
> > wish my answer help you!
> 
> Hi, May I ask how you define which hashtag should be deleted？Do we have any standard of this？

There is no standard for this because I only encountered this problem once. The hashtags which have few counts or far less than the other hashtags should be deleted. It's better to show us the total counts for each hashtags.

> > > > 我遇到了 sam 问题“计数为零的单元格以集群形式存在”。我发现一些主题标签表示的计数很少。在我删除了带有 liitle count 的主题标签后，问题就解决了。希望可以帮助我们中的一些人。
> > > 
> > > 
> > > Hi，May I ask how do you solve this problem?
> > 
> > 
> > Hi， sorry for my late reply. for example, ten hash tags were used to labeling eight different cell clusters. Then two or more hashtags ( some hashtags may fail in labeling cells) would have few counts or far less than the other hashtags. This kind of hashtags should be remove before creating Seurat object. It means it's necessary to compute the sum of the column in Antibody Capture matrix and remove hashtags with low reads counts.
> > wish my answer help you!
> 
> Hi, May I ask how you define which hashtag should be deleted？Do we have any standard of this？

Hi, There is no standard for this because I only encountered this problem once.  In my opinion, the hashtags which have few counts or far less than the other hashtags should be deleted.  It's better to show the total number of counts for each hashtag.
