### ISSUE TITLE
$ operator not defined for this S4 class when using CreateSeuratObject

### ISSUE THREAD

**Issue by lkqnaruto** [satijalab/seurat#4439]
I'm trying to load the 10X data using Read10X function, and these data are from the Cellranger 5.0 count. I read about the documentation of Read10X, where it says that for output from CellRanger >= 3.0 with multiple data types, creating Seurat Object is slightly different. For output from CellRanger >= 3.0 with multiple data types as follows :

data_dir <- 'path/to/data/directory'
list.files(data_dir) # Should show barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz**
data <- Read10X(data.dir = data_dir)
seurat_object = CreateSeuratObject**(counts = data$`Gene Expression`)**

I tried this code, but it turns out that doesn't work, and shows: "$ operator not defined for this S4 class", obviously problem comes from the "$", does anyone have the same problem as me before? how to solve it?

R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

**Comment by k3yavi** [comment]
Hi @lkqnaruto ,

Can you check if `seurat_object = CreateSeuratObject(counts = data)`, solved the problem ?

**Comment by lkqnaruto** [comment]
yes, it does solve the problem, thank you for the reply. But I was wondering what's the difference between them, it looks like "counts = data$Gene Expression" and "counts = data" peform slightly different. My 10X output feature file contains three columns where the third column is "Gene Expression"

**Comment by k3yavi** [comment]
I think Read10x is returning a matrix and the `$` operator can't be used on that. I am glad to hear it works.
