### ISSUE TITLE
FindNeighbors function doesn't work for the Seurat Object/ Seurat 4.0.1

### ISSUE THREAD

**Issue by DespinaBB** [satijalab/seurat#4442]
Hello,

I am having an issue with the FindNeighbors function, I am running a script I have ran before many times smoothly but since yesterday I am getting an error every time I run this: hBM_norm<- FindNeighbors(hBM_norm, dims = 1:25)
The error message is this: 
hBM_norm<- FindNeighbors(hBM_norm, dims = 1:25)
Computing nearest neighbor graph
Computing SNN
Error in validObject(.Object) : 
  invalid class “Graph” object: superclass "Mnumeric" not defined in the environment of the object's class

I am using: 
R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Platform: x86_64-apple-darwin17.0 (64-bit)

This is my code: 

#install.packages("cellranger")
library(cellranger)
#install.packages("Seurat")
library(Seurat)
library(ggplot2)

hBM <- Read10X("~/Desktop/cr_count_Healthy_filtered_feature_bc_matrix /")
rownames(hBM [["Antibody Capture"]]) <- gsub(pattern = "_TotalA", replacement = "", 
                                                    x = rownames(hBM [["Antibody Capture"]]))
hBM_norm <- CreateSeuratObject(counts = hBM[["Gene Expression"]],
                                       project = "DBA_CITEseq", 
                                       min.cells = 3,      
                                       min.features = 200, 
                                       names.delim = "-",  
                                       names.field = 2)    
hBM_norm <- RenameIdents(hBM_norm, '1' = 'hBM')
hBM_norm[["sample"]] <- Idents(hBM_norm)
hBM_norm <- NormalizeData(hBM_norm)

#hBM_norm[["ADT"]] <- CreateAssayObject(hBM[["Antibody Capture"]][, colnames(hBM_norm)])
#hBM_norm <- NormalizeData(hBM_norm, assay = "ADT", normalization.method = "CLR")

hBM_norm <- FindVariableFeatures(hBM_norm)
hBM_norm <- ScaleData(hBM_norm)
hBM_norm <- RunPCA(hBM_norm, verbose = FALSE)
ElbowPlot(hBM_norm, ndims = 50)
hBM_norm<- FindNeighbors(hBM_norm, dims = 1:25) -ERROR-
hBM_norm <- FindClusters(hBM_norm, resolution = 0.8)
hBM_norm<- RunUMAP(hBM_norm, dims = 1:50, seed.use = 4867)

DimPlot(hBM_norm, label = TRUE, pt.size = 1, group.by = "sample") + NoLegend() 
DimPlot(hBM_norm, label = TRUE, pt.size = 1, group.by = "seurat_clusters")

All my packages are updated, I uninstalled Seurat and re installed it again just in case but that didn't help. 
Please let me know if you have any clue what is up!
Thanks!

**Comment by BarryDigby** [comment]
#4436

**Comment by DespinaBB** [comment]
Thanks!
