### ISSUE TITLE
about batch correction

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#4443]
Dear all,

i would appreciate your comments, and advises on the following please :

<> we do have a two batches of scRNA-seq in CTRL (batch 1 and batch2), and two batches of scRNA-seq in STIM conditions (batch1 and batch2) (the batches were generated at an interval of 1-2 months between each other);

<> we had to integrate/combine those two batches of CTRL, and those two batches of STIM, in order to have a sufficient number of cells in each cluster, and to call conserved and differential markers;

the question would be : when we do batch correction with RPCA, or other algorithms, would these algorithms correct also the fact that the two batches of CTRL and the two batches of STIM were produced at different time points and integrated in a CTRL matrix and in a STIM matrix ?

thanks a lot,

-- bogdan

**Comment by jaisonj708** [comment]
The integration will try to remove differences between nearest neighbors in your two datasets, so if you have differences related to time point, those differences will be eliminated/reduced after integration.

**Comment by tanasa** [comment]
Dear Jason, thank you very much !
