### ISSUE TITLE
Create seurat object from data frame

### ISSUE THREAD

**Issue by ML1990-Lab** [satijalab/seurat#4444]
Hi Seurat team,

thanks for the very informative tool!

I've downloaded a published dataset that have been formatted as matrix where genes are listed in a dedicated column, as well as the cell IDs, as here:

   Feature AAACCTGAGACGCACA_lung AAACCTGAGATGCCTT_lung AAACCTGCAACTGGCC_lung AAACCTGCACATTAGC_lung
1:   Sox17             0.0000000              0.000000              0.000000              1.656833
2:  Mrpl15             0.9467373              0.000000              1.402331              0.000000
3:  Lypla1             0.0000000              2.029095              0.000000              1.656833
4:   Tcea1             0.9467373              0.000000              0.000000              0.000000
5: Atp6v1h             0.0000000              0.000000              0.000000              0.000000

I am not a bioinformatician, so probably it will be an easy solution, but when I try to build the seurat object it works, but I am not able to move forward.

> seuratObject <- CreateSeuratObject(counts = dataMatrix[, -"Feature"])
> seuratObject
An object of class Seurat
3972 features across 11174 samples within 1 assay
Active assay: RNA (3972 features, 0 variable features)
> seuratObject <- NormalizeData(seuratObject)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error: Attempting to add a different number of cells and/or features

Many thanks,
Mattia

**Comment by k3yavi** [comment]
Hi @ML1990-Lab ,

This might be related to https://github.com/satijalab/seurat/issues/3435, please try adding rownames to your dataMatrix and check if helps.
