### ISSUE TITLE
Creating seurat object using .txt file

### ISSUE THREAD

**Issue by Estachen** [satijalab/seurat#4446]
As the title suggests, I'm trying to analyze a publicly available dataset. How would I go about doing that?

I've tried ```data <- read.table("2021-05-06_TCGA_GBM_expression.txt", sep = "\t", header = TRUE)```
followed by ```data_seurat <- new("seurat", raw.data = data)``` note that this data has already gone through QC, I just need to perform analyses (heatmap, etc.). 

Trying to perform ```VlnPlot(data_seurat, "AURKA")``` or ```FeaturePlot(data_seurat, "AURKA")``` results in "Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "seurat"

A quick search led to the suggestion to ```data_seurat_new <- UpdateSeuratObject(data_seurat)``` which gives the error: "Error in if (slot(object = object, name = "version") >= package_version(x = "2.0.0") &&  : 
  missing value where TRUE/FALSE needed"
  
  Now I'm stuck... Any and all input is appreciated!

**Comment by timoast** [comment]
Have you looked at any of the vignettes on the Seurat website? They give examples of how to create a Seurat object. The function you need is `CreateSeuratObject()`, you should not construct the class directly using `new()`

**Comment by Estachen** [comment]
Dear Tim,

I should have been more clear in formulating my question. I have this supposed RNA-seq (processed data), which is in a .txt format. So I only wanted to make it into a Seurat object to perform further analyses. I am not sure how to analyze such data - I am unsure as to what has been performed and in what state the file is. It looks sth like this when I load it into R:
 
![Screen Shot 2021-05-10 at 12 05 16 PM](https://user-images.githubusercontent.com/72927094/117643083-4ff42100-b188-11eb-98d4-cc92980a108a.png)

I am only used to working with .h5 files from scratch and the seurat package is the most comfortable to use for me. I am aware that the file may not be in the "correct" format or that another package may be more ideal to perform analysis with. If you could kindly let me know! Or shall I post another thread?
