### ISSUE TITLE
errors when using MapQuery()

### ISSUE THREAD

**Issue by Yale73** [satijalab/seurat#4450]
Hi Seurat team,

I am using one of my Seurat objects as a reference and map a new object (PMA) to match the original one. As our data is immune cells from non-lymphoid tissues. I following the example 2 in this vignette: https://satijalab.org/seurat/articles/integration_mapping.html

Here is my code. 

```
### load reference and new object
reference
PMA
### then run mapping
reference <- RunUMAP(reference, reduction.name = "harmony", umap.method="uwot-learn", **return.model = TRUE**, dims = 1:32)
DimPlot(reference, group.by = "ID", reduction = "umap") 


reference <- ScaleData(reference, assay = 'RNA')
reference <- FindNeighbors(reference)
reference <- RunSPCA(reference, assay = 'RNA', graph = 'RNA_nn')

reference <- FindNeighbors(
  object = reference,
  reduction = "spca",
  dims = 1:32,
  graph.name = "spca.annoy.neighbors", 
  k.param = 50,
  cache.index = TRUE,
  return.neighbor = TRUE,
  l2.norm = TRUE
)

PMA.batches <- SplitObject(PMA, split.by = "hash.ID")
PMA.batches <- lapply(X = PMA.batches, FUN = NormalizeData, verbose = FALSE)

anchors <- list()
for (i in 1:length(PMA.batches)) {
  anchors[[i]] <- FindTransferAnchors(
    reference = reference,
    query = PMA.batches[[i]],
    k.filter = NA,
    reference.reduction = "spca", 
    reference.neighbors = "spca.annoy.neighbors", 
    dims = 1:32
  )
}


```
All the above steps work, but when I ran the following steps, 
```
for (i in 1:length(PMA.batches)) {
  PMA.batches[[i]] <- MapQuery(
    anchorset = anchors[[i]], 
    query = PMA.batches[[i]],
    reference = reference, 
    refdata = list(
      celltype = "ID", 
      predicted_ADT = "ADT"),
    reference.reduction = "spca",
    reduction.model = "umap"
  )
}
```
I got error:
 `Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first`

But I have run this step at the very beginning and I also used the new version seurat

```
[1] dittoSeq_1.2.6        patchwork_1.1.1       ggplot2_3.3.3         SeuratDisk_0.0.0.9013
[5] SeuratObject_4.0.0    Seurat_4.0.1     
```

Thanks for your help.

All the best,
Yale

**Comment by yuhanH** [comment]
HI, Yale
Here are some potential parts you may need to change. 
1. In RunUMAP, what does `**` mean in your case? You don't need to set umap.method and only set return.model to `TRUE`. 
```
reference <- RunUMAP(reference, reduction.name = "harmony", return.model = TRUE, dims = 1:32)
```
2. Does your reference have batch effect? If so, you need to build the graph based on the batch-corrected dimensional reduction. 
```
reference <- FindNeighbors(reference, reduction = "harmony", dims = 1:32)
```
3. We suggest you use SNN graph to learn the SPCA. 
```
reference <- RunSPCA(reference, assay = 'RNA', graph = 'RNA_snn')
```
Then, I think it should ok. If it doesn't fix the issue, I will reopen it.
