### ISSUE TITLE
Invalid character Indexing for Merge two Seurat Obj.

### ISSUE THREAD

**Issue by Fiona-Pan** [satijalab/seurat#4452]
Hi there,
    I'm having issues merging two Seurat objects with a count matrix as initial input, 
    the error message shows: 
    please help

```
Binding matrix rows
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
Calls: merge ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows -> intI
In addition: Warning messages:
1: In merge.ChromatinAssay(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],  :
  Some fragment files are not valid or not indexed.
            Removing invalid files from merged ChromatinAssay
2: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr4_gl000193_random, chrUn_gl000222, chrUn_gl000235
  - in 'y': chr6_ssto_hap7, chrUn_gl000214
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
Execution halted
```

![image](https://user-images.githubusercontent.com/55969398/117596687-7610c580-b176-11eb-8e5c-2d0eba2ac21f.png)

```r
p1<-readRDS("../CSV/L1-pmat.rds")
p2<-readRDS("../CSV/L2-pmat.rds")

s1<-read.table(
  file = "../file/Library_20190731_001_singlecell.csv", 
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]
s1<-s1[s1$passed_filters > 100, ]

s2<-read.table(
  file = "../file/Library_20190731_002_singlecell.csv", 
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]
s2<-s2[s2$passed_filters > 100, ]

f1 <- CreateFragmentObject(
  path = "../file/Library_20190731_001_fragments.tsv.gz", 
  cells = rownames(s1)
)

f2 <- CreateFragmentObject(
  path = "../file/Library_20190731_002_fragments.tsv.gz", 
  cells = rownames(s2)
)

c1<-CreateChromatinAssay(counts = p1, sep = c(":", "-"),fragments = f1)
counts1<-CreateSeuratObject(c1, assay = "ATAC",meta.data = s1)


c2<-CreateChromatinAssay(counts = p2, sep = c(":", "-"),fragments = f2)
counts2<-CreateSeuratObject(c2, assay = "ATAC",meta.data = s2)


counts1$dataset <- 'WT'
counts2$dataset <- 'KD'

# ------------ ERROR HERE --------------------
combined <- merge(
  x = counts1,
  y = counts2,
  add.cell.ids = c("WT","KD")
)
# --------------ERROR HERE ------------------

combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(combined)
combined <- RunUMAP(combined, dims = 2:50, reduction = 'lsi')

```

sessioninfo()
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4

```

**Comment by torkencz** [comment]
Hi, 
It seems like there are a couple of things going on here. But the primary problem is that your two objects same to have a different set of row names. I would see what intersect(row.names(counts1),row.names(counts2)) outputs and then subset your two objects to a common set of features. This vignette might also help https://satijalab.org/signac/articles/merging.html .  I would also validate fragments when you create you fragment object, because there is something happening there. I'll close this for now but I can reopen if problem continues.

**Comment by Mingjiang-git** [comment]
Hi ，

![image](https://user-images.githubusercontent.com/75767091/166862396-058fe524-a75a-4833-9684-e77c9b4f9e2c.png)

Feature names cannot have underscores ('_'), replacing with dashes ('-')

**Comment by Mingjiang-git** [comment]
> Hi there, I'm having issues merging two Seurat objects with a count matrix as initial input, the error message shows: please help
> 
> ```
> Binding matrix rows
> Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
>   invalid character indexing
> Calls: merge ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows -> intI
> In addition: Warning messages:
> 1: In merge.ChromatinAssay(x = assays.merge[[1]], y = assays.merge[2:length(x = assays.merge)],  :
>   Some fragment files are not valid or not indexed.
>             Removing invalid files from merged ChromatinAssay
> 2: In .Seqinfo.mergexy(x, y) :
>   Each of the 2 combined objects has sequence levels not in the other:
>   - in 'x': chr4_gl000193_random, chrUn_gl000222, chrUn_gl000235
>   - in 'y': chr6_ssto_hap7, chrUn_gl000214
>   Make sure to always combine/compare objects based on the same reference
>   genome (use suppressWarnings() to suppress this warning).
> Execution halted
> ```
> 
> ![image](https://user-images.githubusercontent.com/55969398/117596687-7610c580-b176-11eb-8e5c-2d0eba2ac21f.png)
> 
> ```r
> p1<-readRDS("../CSV/L1-pmat.rds")
> p2<-readRDS("../CSV/L2-pmat.rds")
> 
> s1<-read.table(
>   file = "../file/Library_20190731_001_singlecell.csv", 
>   stringsAsFactors = FALSE,
>   sep = ",",
>   header = TRUE,
>   row.names = 1
> )[-1, ]
> s1<-s1[s1$passed_filters > 100, ]
> 
> s2<-read.table(
>   file = "../file/Library_20190731_002_singlecell.csv", 
>   stringsAsFactors = FALSE,
>   sep = ",",
>   header = TRUE,
>   row.names = 1
> )[-1, ]
> s2<-s2[s2$passed_filters > 100, ]
> 
> f1 <- CreateFragmentObject(
>   path = "../file/Library_20190731_001_fragments.tsv.gz", 
>   cells = rownames(s1)
> )
> 
> f2 <- CreateFragmentObject(
>   path = "../file/Library_20190731_002_fragments.tsv.gz", 
>   cells = rownames(s2)
> )
> 
> c1<-CreateChromatinAssay(counts = p1, sep = c(":", "-"),fragments = f1)
> counts1<-CreateSeuratObject(c1, assay = "ATAC",meta.data = s1)
> 
> 
> c2<-CreateChromatinAssay(counts = p2, sep = c(":", "-"),fragments = f2)
> counts2<-CreateSeuratObject(c2, assay = "ATAC",meta.data = s2)
> 
> 
> counts1$dataset <- 'WT'
> counts2$dataset <- 'KD'
> 
> # ------------ ERROR HERE --------------------
> combined <- merge(
>   x = counts1,
>   y = counts2,
>   add.cell.ids = c("WT","KD")
> )
> # --------------ERROR HERE ------------------
> 
> combined <- RunTFIDF(combined)
> combined <- FindTopFeatures(combined, min.cutoff = 20)
> combined <- RunSVD(combined)
> combined <- RunUMAP(combined, dims = 2:50, reduction = 'lsi')
> ```
> 
> sessioninfo()
> 
> ```
> R version 4.0.4 (2021-02-15)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.2 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> locale:
>  [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
>  [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
>  [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.4
> ```
Hi ，
Feature names cannot have underscores ('_'), replacing with dashes ('-')
