### ISSUE TITLE
How can DoHeatmap include genes that are not expressed

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#4453]
Hi,
Thanks for developing this user-friendly tool. I have an question about **DoHeatmap fuction**. 

I found out that **DoHeatmap** can only plot based on VariableFeatures. How do I use the DoHeatmap  when comparing some custom genes(including **some zero expression genes**).

I sincerely hope I can get your help.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  So `DoHeatmap` is based on what genes are present in the `scale.data` slot.  By default with either `ScaleData` or `SCTransform` pipelines the only genes that are present in that slot are the variable features (this provides both speed and object size advantages).  If you would like all genes to be present in that slot you can run this code for `ScaleData` (as shown in basic tutorial):
```all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
```
or if using `SCTransform` you can add the parameter: `return.only.var.genes = FALSE`.

If a gene has no expression in any cell in your dataset than it will not be included in the object and thus you can't plot that gene using any of the plotting features.

Best,
Sam
