### ISSUE TITLE
Object avg_log2FC not found 

### ISSUE THREAD

**Issue by JXHighseek** [satijalab/seurat#4454]
Hello! I was working with the PBMC Guided Clustering Tutorial and when I was running the code to group pbmc.markers by cluster, I encountered the following error: 

```r
# Original code: 
pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)

# Error message
# Error: Problem with `filter()` input `..1`.
# x object 'avg_log2FC' not found
# Input `..1` is `top_n_rank(2, avg_log2FC)`.
# The error occurred in group 1: cluster = "0".
```

I believe I followed everything on the website properly up till this point, could anyone let me know how to correct this? Thanks so much!

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  Can you provide the output of `sessionInfo()`?  

Thanks,
Sam

**Comment by RunzheWang** [comment]
I know what's wrong, you just need to change 'wt = avg_log2FC' to 'wt = avg_logFC'

**Comment by samuel-marsh** [comment]
@RunzheWang yes depending on the version of Seurat being used that is most likely the issue.  Hence asking for `sessionInfo()` to determine package versions.
