### ISSUE TITLE
seurat v4 wnn ON MULTIOME

### ISSUE THREAD

**Issue by khandaud15** [satijalab/seurat#4455]
Hi, I am trying to run seurat v4 on multiome dataset
I am getting an unexpected error 
" Error in .make_assembly_report_URL(assembly_accession) : 
  don't know where to find assembly report for GCF_000001405.38
Calls: seqlevelsStyle<- ... .get_NCBI_chrom_info_from_accession -> fetch_assembly_report -> .make_assembly_report_URL

can you please help me out whats wrong

**Comment by timoast** [comment]
Please include the full code you're running and the output of `sessionInfo()`
