### ISSUE TITLE
seurat WNN multiome

### ISSUE THREAD

**Issue by khandaud15** [satijalab/seurat#4457]
Hi, 
I am running seurat wnn on the multiome dataset, 
I when it on the cellranger arc result that were produced without use any gex and atac cuttoof, the seurat wnn works fine
whereas when I am using the seuart wnn on the cellranger arc results produced by giving extra cammand of filters for gex and atac, 

I am getting this error. seems like something is wrong with the frag file produced from cellranger

Checking for 6967 cell barcodes

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: validateCells(fragments = filepath, cells = cells, find_n = find_n,     max_lines = max.lines, verbose = verbose)
 2: ValidateCells(object = frags, verbose = verbose, ...)
 3: CreateFragmentObject(path = fragments, cells = cells, validate.fragments = validate.fragments,     verbose = verbose, ...)
 4: CreateChromatinAssay(counts = atac_counts, sep = c(":", "-"),     genome = "hg38", fragments = frag.file, min.cells = 10, annotation = annotations)
An irrecoverable exception occurred. R is aborting now ...

can you please help me to resolve the issue

Thanks

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/609
