### ISSUE TITLE
Which normalization to use for single cell/ nuclei sequencing data?

### ISSUE THREAD

**Issue by Kabriya12** [satijalab/seurat#4463]
I am reading through the different ways to do normalization for single cell seq data.

Using seurat I first used NormalizeData, but then I found out that you can use scTransform or scNorm. But I'm not sure under which conditions, or what types of data distributions each one is supposed to be used.

**Comment by saketkc** [comment]
For UMI-based data, we recommend [SCTransform](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1). There are arguments in the paper and this [presentation](https://drive.google.com/file/d/1mbFNhQYHlVsKThIuhDfe_ouz-FkHdpGo/view) as why it achieves normalization in true sense over log normalization or scale factor based approaches, though it might be possible in some cases to get a practically equivalent normalization (for what matters downstream) using `LogNorm`.

**Comment by Kabriya12** [comment]
OK thank you. I do have UMI-based data, but single nuclei sequenced, so it should be fine to use scTransform right (thats what im using)
and presentation helps make sense thanks
