### ISSUE TITLE
Help with Cite-seq analysis

### ISSUE THREAD

**Issue by NaniNaniOkotta** [satijalab/seurat#4468]
Hello.
I recently got Cite-seq data and I'm having problems analyzing it. I wanted to start with this vignette (https://satijalab.org/seurat/articles/multimodal_vignette.html), but the files that they gave me are different. Basically, I have all the data of rna and adt in the same files (I have a folder with 3 files: features, barcode and matrix) and in the tutorial they start with 2 different csv files. 

How can I go from the files I have to the ones used in the tutorial.

Thanks

**Comment by jarchana09** [comment]
Hi,
I am not affiliated with the developers, however, you could have a look at this part of the vignette: [https://satijalab.org/seurat/articles/multimodal_vignette.html#loading-data-from-10x-multi-modal-experiments-1](https://satijalab.org/seurat/articles/multimodal_vignette.html#loading-data-from-10x-multi-modal-experiments-1) which describes how to load data from 10X Genomics multimodal experiments, assuming that your data are raw/filtered matrices that have been processed using CellRanger.
Thank you.

**Comment by torkencz** [comment]
Yes, I would follow the https://satijalab.org/seurat/articles/multimodal_vignette.html#loading-data-from-10x-multi-modal-experiments-1 vignette.

**Comment by NaniNaniOkotta** [comment]
Yes! That really helped.
Thanks a lot
