### ISSUE TITLE
Use is.expr for dotplots

### ISSUE THREAD

**Issue by b-dawes** [satijalab/seurat#447]
Currently the dot size is set by the percent of cells with greater than 0 counts. Could this be changed to the percent of cells with greater than is.expr counts?

This should be doable by changing the line:
```R
pct.exp = PercentAbove(x = expression, threshold = 0)
````
to:
```R
pct.exp = PercentAbove(x = expression, threshold = object@is.expr)
```

**Comment by mojaveazure** [comment]
When creating a Seurat object with `CreateSeuratObject`, we [change any values](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L76-L82) less than `is.expr` to 0, so using `object@is.expr` instead of 0 shouldn't change the plot.

**Comment by b-dawes** [comment]
Okay, that makes sense. There's a user in my lab who's using data that was normalized outside of Seurat so genes below that threshold haven't been zeroed out. So this only affects running Seurat in a non-standard way like this. Thanks for clarifying.
