### ISSUE TITLE
Monocle errors: Assays not in SingleCellExperiment object and different cluster results with cluster_cells(resolution)

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4477]
Hi there, 

My Seurat object has already been fully processed with SCTransform() workflow for clustering and DEG analysis.
 
<img width="566" alt="Screen Shot 2021-05-14 at 10 24 54 PM" src="https://user-images.githubusercontent.com/62179082/118333186-36920280-b503-11eb-9b09-6f3912c3f2de.png">

I am now trying to run Monocle following this tutorial for my Seurat object below: http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html

But, I encountered 2 issues: 

(1) When I ran cluster_cells(cds) function, the UMAP now does not match the UMAP of clusters that I had (I now have less clusters). I tried to change the resolution parameter in cluster_cells() without success. Is there a way to obtain the same clusters as when I performed clustering in the typical SCTransform() in Seurat? Because I am happy with the clusters I obtained previously and want to now find the trajectory for these same cluster cells.

(2) At the subset step, I had an error as shown. 

<img width="884" alt="Screen Shot 2021-05-14 at 10 29 05 PM" src="https://user-images.githubusercontent.com/62179082/118333542-ccc62880-b503-11eb-9a70-e429c6bac542.png">

Would you mind helping me resolve these issues? 

Thank you for your help!

**Comment by timoast** [comment]
1. No, it's a requirement in Monocle3 that you run their own clustering
2. The parameters `counts = "counts", data = "logcounts"` should be part of the `as.Seurat()` function call not the `subset()` function
