### ISSUE TITLE
Dotplot of same scale with different amount of genes or cells

### ISSUE THREAD

**Issue by erikagucciardo** [satijalab/seurat#4481]
Hi and thank you for this great package!
I was wondering whether there is a way to have a constant scaling of different dot plots where different number of genes and cells are being plotted (i.e. the size of the plot will change based on the number of genes/cells plotted, but the axes ticks will have the same distance between each other). This will help to e.g. have consistent plots across Figures.

Cheers!

**Comment by samuel-marsh** [comment]
Hi @erikagucciardo as plots produced in Seurat are ggplot2 based you can easily save different size figures (depending on number of factors plotted) using the height and width parameters of [`ggsave`](https://ggplot2.tidyverse.org/reference/ggsave.html).  Additionally, if you save in vector based format you can also edit spacing manually (though much more tediously) in post-R vector based design program (i.e. Illustrator, Affinity Designer, etc).

Best,
Sam

**Comment by erikagucciardo** [comment]
Hi you all! I found the solution; adding coord_equal().

 `DotPlot(object, features=c("CD3E", "CD3D"))+coord_equal()`

**Comment by erikagucciardo** [comment]
Thank you for the new feature of grouped gene list!

Now I can't seem to be able to have coord_equal() work to have same distance between ticks in x axis and y axis. It throws the following error "coord_fixed doesn't support free scales". Any fix for this?
