### ISSUE TITLE
elbow plot on umap components

### ISSUE THREAD

**Issue by mea2712** [satijalab/seurat#4482]
Is there a way to get an elbow plot for umap components? I'm getting the error 'No standard deviation info stored for umap'
I would like to run umap on my variable features and pca, allowing for more than 2 umap components and then cluster on the umap reduced dimension. How can I asses how many umap components to use for the clustering?

Thanks!

**Comment by timoast** [comment]
There is no equivalent concept of an elbow plot for UMAP. You could potentially look at the reconstruction error from the inverse UMAP transform (https://umap-learn.readthedocs.io/en/latest/inverse_transform.html) but this is not something we support in the Seurat software. We also don't typically recommend clustering on the UMAP dimension reduction.
