### ISSUE TITLE
Unable to merge large datasets

### ISSUE THREAD

**Issue by xihuiyin** [satijalab/seurat#4483]
Hi, I am currently trying to merge 16 large datasets across different conditions and time points for integration using the code 
`all.merged <- merge(x = wt.merged,
             y = utx.merged, 
             add.cell.id = c("WT","UTX")
             )`

However, I consistently receive the error "Error in RowMergeMatrices(mat1 = mat1, mat2 = mat2, mat1_rownames = mat1.names,  : std::bad_alloc". Merging a subset of these datasets seem to work but merging them further does not. 

I have 16G of memory so memory shouldn't be an issue here. Restarting R and clearing unneeded objects does not seem to help at all. I have also performed QC filtering ahead of merging to try to cut down on the sizes of the datasets but it doesn't work. I was wondering if anyone has an idea what should be done.

EDIT: I tried integration without merging, this error also appears during the IntegrateData step

**Comment by timoast** [comment]
> I have 16G of memory so memory shouldn't be an issue here

This is almost certainly the issue if you have 16 large single-cell datasets that you want to analyze. I'd suggest trying this on a machine with more RAM
