### ISSUE TITLE
sctransform technical question

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#4484]
Do you scTransform to nullify sequencing depth differences between groups or within groups? Is it appropriate to normalize using scTransform each of the10X files individually and then merge?

**Comment by saketkc** [comment]
Hi @nikita421,It is not clear what is meant be groups here, but it is perfectly okay to apply SCTransform individually to each experiment for doing integration, transfer etc.  We recommend running SCTransform individually to account for dataset (and platform) specific technical noise. If the libraries were prepared in similar fashion and were processed using the same technology (say Chromium V2), then it would not make a huge difference even if you were to apply SCTransform after merging.

**Comment by nikita421** [comment]
Hi @saketkc , thanks for your response. Sorry I should have been more clear. We have 3 samples in condition 1 and 3 samples in condition B. When we checked the mean reads/cell for the 6 samples, condition 1 has almost ~50,000 for each sample but condition B has ~20,000 in each sample. The libraries were prepared using same technology. We think this is probably causing issues with our dotplots. I wonder if doing scTransform between groups might help normalize the sequencing depth issue. Please let me know if my question makes more sense now or if you need more details. Thanks again!

**Comment by saketkc** [comment]
Hi @nikita421, SCTransform should be able to handle such scenarios (this was also the goal behind developing it).

**Comment by nikita421** [comment]
Sounds good, thanks a lot!
