### ISSUE TITLE
Cannot color cells with 0 expression in another color

### ISSUE THREAD

**Issue by JH1606-code** [satijalab/seurat#4485]
Hello,

I use the FeaturePlot function to color the single cells in my UMAP by their single gene count. To separate the control and stimulated sample I use split.by.

Cells with zero counts should be colored in gray and cells that contain the specific gene should be colored bluish depending on the gene count.

Now I have the problem, if only one of the two samples contain cells that carry a specific gene, then all cells in the UMAP of the sample where none of the cells contain the gene are completely colored in blue instead of gray. This problem has been described before, and you should update the version of the Seurat package. What I also did (see SessionInfo). 

The problem does not occur if both samples have cells that contain the gene. In that case, the cells with zero number are correctly colored gray and the cells containing the gene are colored bluish.

Here is my code:

FeaturePlot(object =immune.combined, features =  "ZFHX4", label = TRUE, label.size = 7, order = TRUE, slot = "counts", split.by = "stim", pt.size = 0.4) & theme(legend.position = "top", legend.text = element_text(size = 7.5), legend.title = element_text(size = 8)) 

Here is my SessionInfo:

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] remotes_2.3.0               rmarkdown_2.8               kableExtra_1.3.4.9000       knitr_1.31                 
 [5] DESeq2_1.30.1               SummarizedExperiment_1.20.0 MatrixGenerics_1.2.1        matrixStats_0.58.0         
 [9] GenomicRanges_1.42.0        GenomeInfoDb_1.26.4         IRanges_2.24.1              S4Vectors_0.28.1           
[13] ggsignif_0.6.1              broom_0.7.5                 rstatix_0.7.0               writexl_1.3.1              
[17] tidyr_1.1.3                 ggpubr_0.4.0.999            xlsx_0.6.5                  reshape2_1.4.4             
[21] magrittr_2.0.1              data.table_1.14.0           tibble_3.1.0                metap_1.4                  
[25] multtest_2.46.0             Biobase_2.50.0              BiocGenerics_0.36.1         randomcoloR_1.1.0.1        
[29] ggplot2_3.3.3               cowplot_1.1.1               RCurl_1.98-1.3              sctransform_0.3.2          
[33] patchwork_1.1.1             SeuratObject_4.0.0          Seurat_4.0.1                dplyr_1.0.5                
[37] imguR_1.0.3                

The first plot is a correct one and the second plot one with the bug.

I would be really happy about a feedback!

![image](https://user-images.githubusercontent.com/84003107/118594140-361a9580-b7a9-11eb-8179-7a9b04fdd563.png)
![image](https://user-images.githubusercontent.com/84003107/118594193-49c5fc00-b7a9-11eb-92de-ba7c9fcfa8f3.png)

**Comment by mhkowalski** [comment]
Hello,

Apologies for the late response. Can you please try adding `  cols=c("lightgrey", "lightgrey")` as an argument to `FeaturePlot` ?

**Comment by JH1606-code** [comment]
Hi, 

no problem. 
I tried this already. But I use the parameter split.by = "condition" with cols = c("grey", "blue"). So when I set cols to cols = c("grey", "grey") then both conditions will be colored in grey although cells in one condition show an expression of the specific gene and should be colored in blue.

**Comment by mhkowalski** [comment]
Hi, I see. I will look into it further, but in the mean time you could split the object by condition and use patchwork to display the 2 plots together. 

For example, 

```
library(patchwork) 
obj.list <- SplitObject(immune.combined, split.by="stim")
p1 <- FeaturePlot(object =obj.list[[1]], features = "ZFHX4", cols=c("grey", "grey")) 
p2 <- FeaturePlot(object =obj.list[[2]], features = "ZFHX4") 
p1 | p2
```

**Comment by JH1606-code** [comment]
Thanks, I will do that!

**Comment by JH1606-code** [comment]
Hi,

I don't know if the bug is fixed but you can try the solution that mhkowalski gave me. 

library(patchwork) 
obj.list <- SplitObject(immune.combined, split.by="stim")
p1 <- FeaturePlot(object =obj.list[[1]], features = "ZFHX4", cols=c("grey", "grey")) 
p2 <- FeaturePlot(object =obj.list[[2]], features = "ZFHX4") 
p1 | p2

It worked fine for me!

**Comment by relleona** [comment]
The output of feature plots is like a list of plots, so I found that you can actually replace the list of plots that has a value 0. 

list_features = c("ZFHX4", "a1H", "a2HM", "APOL1")
cols = c("light_grey", "light_grey")

  # Create and save feature plots with customized parameters
  feature_plots <- FeaturePlot(object, 
                               features = list_features, 
                               ncol = 3, 
                               cols=cols)   # Set custom colors
  
  # Modify the color scale for when plots is all 0s
  for (i in seq_along(feature_plots)) {
   #Index into the data within the list
    current_plot <- feature_plots[[i]]$data
    #Name of the feature in that data 
    feature_name <- list_features[[i]]
    if ( all(current_plot[[feature_name]] == 0) ) {
      # If all values are 0, set all points to light gray
      feature_plots[[i]] <- FeaturePlot(object, 
                                        features = feature_name, 
                                        ncol = 3, 
                                        cols=c(cols[[1]],cols[[1]]))
    }
  }

I hope that helps
