### ISSUE TITLE
How to analyse (or correct) wetting failure sample?

### ISSUE THREAD

**Issue by qoiopipq** [satijalab/seurat#4486]
We’ve recently sequenced four 10X 3’ GEX samples, we found one of them potentially with wetting failure issue. Cellranger count summary for this sample shows 11k cells, 12K mean reads per cell,  ~800 median genes per cell, ~2k median UMI per cell.
 
In comparison to the other three samples, we have 3k-5k cells, 30k-40k mean reads per cell, and 1.3k-1.5k median genes per cell, 3.5k-4k median UMI per cell. We expect these four samples to show similar range of the stats. And we want to compare gene expression between first two samples vs last two samples. As you can see, the sample with wetting failure issue has high cell number, low reads/UMI/gene counts per cell.
 
In terms of downstream data analysis of this sample, can you suggest a way to exclude low quality cells? For example, keeping cells with upper quantile of UMI and gene counts per cell will help (which could include doublets)? And probably perform integration step to correct techical problem?  I know it’s bit hard to tell which are good quality cells.

Thanks!

**Comment by torkencz** [comment]
Hi,
It will be difficult to identify which are the relatively high quality cells vs doublets. You might want to try scrublet https://github.com/swolock/scrublet and see if you can identify potential doublets.
