### ISSUE TITLE
Should I rerun the integration analysis if I removed some cells/samples from my data?

### ISSUE THREAD

**Issue by lkqnaruto** [satijalab/seurat#4489]
HI

I have run the integration analysis on my 4 sample control group data to give cell type annotation using SingleR. And after that I realized that some of the label assignment appears to be low quality cell type. I guess it is because SingleR didn't perform well on those cells, therefore I decide to remove those cell samples. So, I wonder whether I need to rerun the integration analysis (Using SCTransform) on the updated RNA essay after I remove those cells/samples from my data?

Many thanks.

**Comment by jaisonj708** [comment]
If it's not too time prohibitive, it might help (or at least won't hurt) to re-run normalization+integration. Getting rid of low-quality cells can increase the amount of important information capture in your dimensional reduction, and it can also reduce the number of aberrant anchors that form during the integration procedure (e.g, fewer cells anchor to doublets).
