### ISSUE TITLE
maximal number of DLLs reached 

### ISSUE THREAD

**Issue by topherconley** [satijalab/seurat#449]
If you could find a way to not attach so many libraries so that I would not get this error:

> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.4/site-library/yaml/libs/yaml.so':
  `maximal number of DLLs reached...

There has got to be a genuine solution to this problem. At present, combining Seurat with other packages attached to the workspace does not play nicely. Is there something you can do in managing the NAMESPACE or something so this doesn't happen?

**Comment by mojaveazure** [comment]
Unfortunately, we cannot decrease the number of DLLs Seurat loads. However, you can increase the number of DLLs you have loaded. In you're `~/.Renviron` file, set `R_MAX_NUM_DLLS` to be something greater than 100 (the default), eg. `R_MAX_NUM_DLLS=200`

**Comment by topherconley** [comment]
Thanks!

**Comment by mschilli87** [comment]
@mojaveazure:
> Unfortunately, we cannot decrease the number of DLLs Seurat loads.

Maybe [the import package](https://github.com/smbache/import) could be used to use functions from other package within Seurat without pulling them in completely.
As a disclaimer I should add that I have never tried this and probably even when not attaching the packages namespace to to the global one that wouldn't help here as the DLL might still need to be loaded (I have no clue how this works internally in R). But is there really no way to statically link in part of a packge into another one in R?
