### ISSUE TITLE
Error in readMM(file = matrix.loc) : file is not a MatrixMarket file

### ISSUE THREAD

**Issue by Nocooper** [satijalab/seurat#4491]
I want to load a PBMCdata(single cell data from Seurat - Guided Clustering Tutorial )  using Read10X. But there is an error message as follows:

`Error in readMM(file = matrix.loc) : file is not a MatrixMarket file`

Used this RScript
`seurat.data <- Read10X(file.path(sample_data_dir, "filtered_feature_bc_matrix"))
`

How can I solve this issue?

**Comment by SeZuNo** [comment]
Hi there, 
Check the header of the matrix file, MatrixMarket has a specific format. Specifically the header of the matrix itself, notice the values are separated by tabulations. Hope it helps!

**Comment by saketkc** [comment]
What is the output of:

```
gzcat sample_data_dir/filtered_feature_bc_matrix/matrix.mtx.gz | head
```

**Comment by Nocooper** [comment]
Thank you for your answer. I have solved it. My problem was caused by the wrong compression method，restar compression ，use `tar -cvf matirx.mtx.gz  matrix.mtx` can read
