### ISSUE TITLE
Why the cell barcodes changes using data.frame

### ISSUE THREAD

**Issue by chenxofhit** [satijalab/seurat#4492]
https://github.com/Teichlab/cellphonedb/issues/312#issue-894933704

**Comment by chenxofhit** [comment]
test_counts <- as.matrix(dha.subset@assays$RNA@data)
head(test_counts) then it ouputs:
[https://user-images.githubusercontent.com/1176815/118748079-c500de00-b88d-11eb-97db-1b553148ce6c.png](url)
and :
test_counts <- as.matrix(dha.subset@assays$RNA@data)
test_counts <- data.frame(Gene=rownames(test_counts), test_counts,stringsAsFactors = F)
I append the first column named Gene for further mice gene name transferring to human gene name in my case.
head(test_counts) then it outputs:
[https://user-images.githubusercontent.com/1176815/118748213-05f8f280-b88e-11eb-8fa2-984cb38b3799.png](url)

When looking carefully, the cell barcodes changes from AAACCCAAGGAGTATT-1_3 to AAACCCAAGGAGTATT.1_3, what causes this result? Maybe the issue should not be here, but I wonder if anyone know.

**Comment by timoast** [comment]
This is due to default parameters in `data.frame()`, not anything Seurat is doing.

```r
> data.frame("a-b" = 1)
  a.b
1   1
> data.frame("a-b" = 1, check.names = FALSE)
  a-b
1   1
```
