### ISSUE TITLE
Integrate data error

### ISSUE THREAD

**Issue by GHAStVHenry** [satijalab/seurat#4493]
Same as error #4427 but this time with single cell GEX (not spatial this time).

`sc10x <- IntegrateData(anchorset=sc10x.anchors,normalization.method="SCT",verbose=FALSE)`
yields:
```
Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length
```

Integrating 7 datasets
* 2 samples ~= 7000 cells
* 2 samples ~= 3000 cells
* 2 samples ~= 1000 cells
* 1 sample ~= 277 cells

5000 integration features found and in use.

Using SCT and rpca (1:50 dims), but this exact code and datasets worked previously when I had less harsh filtering (more cells) before this.

This is the whole relevant commands:
```
  for (i in 1:length(sc10x.l)){
    sc10x.l[[i]] <- SCTransform(sc10x.l[[i]],variable.features.n=5000,return.only.var.genes=FALSE,vars.to.regress=c("nFeature_RNA","percent.mito"),verbose=FALSE,assay="RNA")
  }
  
  sc10x.features <- SelectIntegrationFeatures(object.list=sc10x.l,nfeatures=5000)
  sc10x.l <- PrepSCTIntegration(object.list=sc10x.l,anchor.features=sc10x.features,verbose=FALSE)

  sc10x.l <- lapply(sc10x.l,FUN=function(x) { RunPCA(x,features=sc10x.features,npcs=50,verbose=FALSE) })
  
  sc10x.anchors <- FindIntegrationAnchors(object.list=sc10x.l,normalization.method="SCT",anchor.features=sc10x.features,verbose=FALSE,reduction="rpca",dims=1:50)

  sc10x <- IntegrateData(anchorset=sc10x.anchors,normalization.method="SCT",verbose=FALSE)
```

NOTE: `k.weight=50` works in IntegrateData... if you tell me that that is so because of the rpca method with 50 dims, I'll understand, but how come this all worked without setting `k.weight` (so default =100) when I used more cells from these same samples?

**Comment by jaisonj708** [comment]
As a diagnostic could you try finding integration anchors and re-running `IntegrateData` without your 277-cell sample? The issue may be due to a very small number of anchors being found between this sample and the others.

**Comment by GHAStVHenry** [comment]
Confirmed, removal of the 277-cell sample did work with default `k.weight` parameter.

I'm not sure where in the IntegrationAnchorSet object is the number of anchors actually found...

So is this a:

- [ ] run with `k.weight=30` situation
or
- [ ] remove this sample because it does not contain enough cells to calculate anchors for accurate integration

?

Thanks!

**Comment by GHAStVHenry** [comment]
Any comment?
