### ISSUE TITLE
Saving uwot model to file 

### ISSUE THREAD

**Issue by ilyakorsunsky** [satijalab/seurat#4495]
Dear Team, 

I would like to save the uwot model to file after RunUMAP, so that I can cache the Seurat object, load it, and map data back into the same UMAP space later. The snippet of code below is how I planned to do this: 

```
obj <- RunUMAP(obj, umap.method = 'uwot', return.model = TRUE)
uwot::save_uwot(obj@reductions$umap@misc$model, save_uwot_path)
```

However, this command does not work because the saved uwot model requires the nn_index field. This field is removed in line 1383 of dimensional_reduction.R, reproduced below in context. 

```
if (return.model) {    
umap.output$nn_index <- NULL    
umap.model <- umap.output    
umap.output <- umap.output$embedding  
}
```

Would it be possible to retain nn_index in this function to allow caching the uwot object for future use? 

Thanks for your help and a wonderful tool! 

Best, 
Ilya

**Comment by yuhanH** [comment]
HI, Ilya
You are right.  In seurat, we delete the c++ pointers in in the umap model. 
C++ pointers cannot be stored with R objects together, and it needs to be stored separately. 
If you want to store and use those index, you can use some functions from `uwot` directly. 
`save_uwot`, `load_uwot`, `umap`
