### ISSUE TITLE
"Mapping and Annotating Query Dataset" Vignettes = automatic cell type annotation like SingleR? 

### ISSUE THREAD

**Issue by lkqnaruto** [satijalab/seurat#4496]
I have went through the "Mapping and Annotating Query Dataset" Vignettes, and am wondering whether what "Mapping and Annotating Query Dataset" does is actually cell type annotation given a reference dataset like SingleR does? I'm quite confused. Sorry for the silly question.

**Comment by timoast** [comment]
Yes, the method transfers cell labels and/or continuous data from a reference to query dataset. See the [paper](https://doi.org/10.1016/j.cell.2019.05.031) for a full description
