### ISSUE TITLE
How to get report of average and percentage gene expression from a list of genes across entire dataset instead of per cluster

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4497]
I found code from https://github.com/satijalab/seurat/issues/3521 which has allowed me to plot a list of genes onto one dotplot or featureplot, instead of having separate featureplots for each gene. 

nkfocuslist <- list(c("FOS", "TNFAIP3", "NR4A1", "CCL4", "RASGRP2", 
                      "PARVB", "NR4A2"))
sobj <- AddModuleScore(object = sobj, features = nkfocuslist, name = "NK_Focus_List")  
FeaturePlot(object = sobj, features = "NK_Focus_List1")
![image](https://user-images.githubusercontent.com/62159599/118905500-6f562100-b8e1-11eb-9972-fc0dd7d4f175.png)

From https://github.com/satijalab/seurat/issues/1888 I found you can get the percentage and average gene expression from dotplot information. I would like to do something similar to the above where I can get the gene expression across the whole dataset instead of the expression per cluster:

a <- DotPlot(object = sobj, features = c("FOS", "TNFAIP3", "NR4A1", "CCL4", "RASGRP2",
"PARVB", "NR4A2"))
a$data
![image](https://user-images.githubusercontent.com/62159599/118905679-d1af2180-b8e1-11eb-9b8c-5e5a2d432982.png)

In addition, is there a way to get the p-values associated with these expression values? As well as set thresholds for either? 

Hopefully this makes sense, and thanks for reading!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully this helps.  In terms of getting the average expression I suggest taking look at `AverageExpression` function.

Alternatively you can run a modified version of the code used to create the `DotPlot`
https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/visualization.R#L3462-L3476

The modified version to perform across an entire seurat object would simply be:
```
# PercentAbove function to environment
PercentAbove <- function(x, threshold) {
  return(length(x = x[x > threshold]) / length(x = x))
}
# Pull data on features of interest
data.features <- FetchData(object = obj_name, vars = c("Gene1", "Gene2", etc))
# Calculate average expression (NOTE can also be done simply using `AverageExpression` function.
avg.exp <- apply(X = data.features, MARGIN = 2, FUN = function(x) {return(mean(x = expm1(x = x)))})
# Calculate % expressing
pct.exp <- apply(X = data.features, MARGIN = 2, FUN = PercentAbove, threshold = 0)
# combine the data
combined_avg_pct <- list(avg.exp = avg.exp, pct.exp = pct.exp)```
```

I'm not sure what you mean by p-values associated with these values.  p-value is based on statistical test and if you are performing these calculations across the whole dataset then you aren't comparing them to anything.

Best,
Sam

**Comment by ksaunders73** [comment]
@samuel-marsh This worked! Thanks so much for your help!!

**Comment by samuel-marsh** [comment]
@ksaunders73 Happy to help!
