### ISSUE TITLE
Explanation of CreateSeuratObject's cell discarding for cells with zero expression

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#450]
Hi Seurat equipment,

I just have one doubt with the creation of Seurat object: when I run CreateSeuratObject to three different matrices I have (three different genotypes), without any filtering (no min.cells neither min.genes), I obtain that the total number of genes I have at the begining are stored but there are a different number of cells stored (like losing cells due to some filtering).

```R
table(genotype) #this is the variable that differentiate between genotypes
genotype 
Flox- Flox+    WT 
 3979  3169  2381

#These are the three matrices and they have the same amount of cells that appears in genotype 
WT <- counts[,(genotype=="WT")]
Floxplus <- counts[,(genotype=="Flox+")]
Floxminus <- counts[,(genotype=="Flox-")]

#But when a create the Seurat object, they change! WT:2231; Flox+:2911; Flox-:3600.
data.WT <- CreateSeuratObject(raw.data = WT, project = "WT_control") 
data.Floxplus <- CreateSeuratObject(raw.data = Floxplus, project = "Flox+_control")
data.Floxminus <- CreateSeuratObject(raw.data = Floxminus, project = "Flox-_experimental")
```

Is this function doing some filtering without specifying it? In the help it is said that you can make "some optional filtering" so I guess it is not doing it. Do you know what is happening?

Thank you very much in advance.

Best,
Marina

**Comment by leonfodoulian** [comment]
Hi Marina,

Are you sure that all cells express at least 1 gene? Could you please paste the outputs of the following codes?

```R
length(x = which(x = colSums(x = WT) == 0))
length(x = which(x = colSums(x = Floxplus) == 0))
length(x = which(x = colSums(x = Floxminus) == 0))
```

Best,
Leon

**Comment by mvalenzuelav** [comment]
Hi Leon,
Ok, now I understand; the function is discarding all cells with zero counts in total without applying any filtering. That was what I was asking: if it was doing any filtering without specifying. All right, now numbers fit:
> length(x = which(x = colSums(x = WT) == 0))
[1] 150
> length(x = which(x = colSums(x = Floxplus) == 0))
[1] 258
> length(x = which(x = colSums(x = Floxminus) == 0))
[1] 379

Thanks a lot!

Just one more thing, could you tell me what do you think about issue #443? I still feel not sure about what to do. Thanks again :)
