### ISSUE TITLE
R session aborted when drawing plot

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#4500]
Hello All,

Suddenly, I have a problem using seurat. When I draw plots, R session is always aborted. Funny thing is I used a few hours ago....

![image](https://user-images.githubusercontent.com/52641420/118962124-0386bd80-b9a0-11eb-97a1-099d3510216e.png)

I tried any other plot such as Vlnplot, dimplot and jackstraw plot. But result was same.
I also downloaded R, Rstudio and Rstudio-server again but nothing changed...

Are there anyone who knows this problem?

**Comment by timoast** [comment]
See https://github.com/rstudio/rstudio/issues/9373
