### ISSUE TITLE
Seurat Data Integration - Excess genes and samples

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#4501]
Hello,

I am trying to reproduce some Seurat data as practice.

A post-doc in the lab used Seurat (v 2.x) to integrate their datasets which resulted in 17196 genes across 14196 samples (mouse). Using the same datasets, when I integrate them using Seurat (v 4.0.1) I am left with 30692 features across 73164 samples.

Can someone please explain why I am getting more genes than what mice even have? My integration code:

```
#loading data 
KO4.data <- Read10X(data.dir = "/home/ali/Dokumente/R Practise/E18.5_rawdata/222862_KO4/filtered_gene_bc_matrices/mm10")
KO4 <- CreateSeuratObject(counts = KO4.data, project = "KO4")
KO5.data <- Read10X(data.dir = "/home/ali/Dokumente/R Practise/E18.5_rawdata/222864_KO5/filtered_gene_bc_matrices/mm10")
KO5 <- CreateSeuratObject(counts = KO5.data, project = "KO5")
WT2.data <- Read10X(data.dir = "/home/ali/Dokumente/R Practise/E18.5_rawdata/220574_WT2/filtered_gene_bc_matrices/mm10")
WT2 <- CreateSeuratObject(counts = WT2.data, project = "WT2")
WT3.data <- Read10X(data.dir = "/home/ali/Dokumente/R Practise/E18.5_rawdata/221929_WT3/filtered_gene_bc_matrices/mm10")
WT3 <- CreateSeuratObject(counts = WT3.data, project = "WT3")
WT4.data <- Read10X(data.dir = "/home/ali/Dokumente/R Practise/E18.5_rawdata/222863_WT4/filtered_gene_bc_matrices/mm10")
WT4 <- CreateSeuratObject(counts = WT4.data, project = "WT4")

#MERGING BATCHES
alle_wittmann <- merge(KO4, y = c(KO5, WT2, WT3, WT4), add.cell.ids = c("KO4", "KO5", "WT2", "WT3", "WT4"), project = "alle")
alle_wittmann[["percent.mt"]] <- PercentageFeatureSet(alle_wittmann, pattern = "^mt-") #mt for mouse MT for human

#subset raw data
alle_wittmann <- subset(alle_wittmann, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

# split the dataset based of sample for batch correction
alle.list <- SplitObject(alle_wittmann, split.by = "sample")

features <- SelectIntegrationFeatures(object.list = alle.list)
anchors <- FindIntegrationAnchors(object.list = alle.list, anchor.features = features)
alle <- IntegrateData(anchorset = anchors)

alle.list <- lapply(X = alle.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = alle.list, nfeatures = 2000,fvf.nfeatures = 2000)
anchors <- FindIntegrationAnchors(object.list = alle.list, anchor.features = features)
alle <- IntegrateData(anchorset = anchors)
```

**Comment by saketkc** [comment]
What is the output of:
```r
union( union(rownames(KO4), rownames(WT2)),
           union(rownames(WT4), 
                     union(rownames(KO5), rownames(WT3)) ))
```

the `merge` function will set the features missing in any of the datasets to zero with the final set being the union of all features.

**Comment by AAA-3** [comment]
I get a list of 1000 genes followed by

`[ reached getOption("max.print") -- omitted 27692 entries ]`

**Comment by saketkc** [comment]
Sorry, I meant taking the `length(union())`. In any case, the gene names are different between your dataset if this number is larger than total genes in any of the dataset. A conservative way would be to start with the intersection of all features.

Hope that answers your question.

**Comment by AAA-3** [comment]
Thank you for this! The length(union()) is the same as the number of features of each sample - so I assume the integration worked fine and the difference in features can be attributed to the updated method of integration in Seurat v4.0.1.

However, I am still confused why there is a difference between the number of samples in the integrated dataset. Any thoughts?
