### ISSUE TITLE
Find markers for after using FindSubcluster function. 

### ISSUE THREAD

**Issue by xx789** [satijalab/seurat#4502]
Hi, Seurat team. 

  I have been using the "Find subclusters under one cluster" function released in Seurat V4, which is very cool. Link here: https://satijalab.org/seurat/reference/findsubcluster

  I got two questions: 

 1. How can I find the markers for each sub-cluster? For example, I sub-clustered cluster 9 into 9_0 and 9_1. 
 
(1) When I run the FindAllMarkers function as copied below, it still returned me the cluster 9 markers, rather clusters 9_0 and 9_1. 

### object4.markers <- FindAllMarkers(object = scrna2.int, features = VariableFeatures(scrna2.int, assay = 'integrated'),
                                                                                only.pos = TRUE, 
                                                                                min.pct = 0.1, 
                                                                                logfc.threshold = 0.25, 
                                                                                assay = 'integrated', 
                                                                                slot = c('data'))

(2) When I run FindMarkers function as copied below, it cannot find 9_0 and cluster 9_1. 

### cluster2.markers <- FindMarkers(pbmc, ident.1 = 9_1, min.pct = 0.25)

2. Can we expand the "Find subclusters under one cluster" to "Find subclusters under multiple clusters simultaneously"? 

Many thanks!

**Comment by saketkc** [comment]
Taking an example from the documentation
```r
# Take all cells in cluster 9 and find markers that separate cells in the '9_0' group (metadata
# variable 'group')
markers <- FindMarkers(pbmc_small, ident.1 = "9_0", group.by = 'sub.cluster', subset.ident = "9")

```

For finding subclusters of all clusters, you can run `FindSubCluster` on each cluster separately storing the sublcusters in a relevant new column in the metadata:

```r
pbmc_small <- FindSubCluster(pbmc_small, "2", graph.name = "mygraph", subcluster.name = "subcluster2")
pbmc_small <- FindSubCluster(pbmc_small, "3", graph.name = "mygraph", subcluster.name = "subcluster3")
```
