### ISSUE TITLE
Is filtering by score from FindIntegrationAnchors recommended while doing integrative analysis

### ISSUE THREAD

**Issue by das2000sidd** [satijalab/seurat#4503]
Hi

When I am using to seurat to integrate two datasets, I was wondering what is the interpretation of the score as shown below?

   cell1 cell2 score dataset1 dataset2
1       1     1  0.70        1        2
2       1 29129  0.40        1        2
3       1  6109  0.60        1        2
4       2     2  0.50        1        2

Also is it recommended to filter by this value?

Thank you so much for the answer to my questions.

**Comment by timoast** [comment]
We don't typically recommend doing this, the score is incorporated into the integration method such that low scoring anchors are given lower weight. However, if you wanted to try filtering based on score and see how it impacts the integration results, you can do so using the `subset` function setting `score.threshold`
