### ISSUE TITLE
FindClusters

### ISSUE THREAD

**Issue by zym826** [satijalab/seurat#4516]
dt <- FindClusters(object = dt,resolution = 0.5)
Error in FindClusters.Seurat(object = dt, resolution = 0.5) : 
  Provided graph.name not present in Seurat object

**Comment by timoast** [comment]
Can you include the full code you're running and output of `sessionInfo()`?

**Comment by zym826** [comment]
sorry,I know what wrong I am.Before I run FindClusters,I don't wrong FindNeighbors
