### ISSUE TITLE
Reference mapping with a user-defined reference + query dataset

### ISSUE THREAD

**Issue by hbandukw** [satijalab/seurat#4519]
Hello,

I am really interested in using either Azimuth or the Seurat package for mapping my dataset to a reference. However, It is unclear to me if the reference itself can be user-defined or not? Please let me know, thanks!

**Comment by timoast** [comment]
No, the reference in the Azimuth web app cannot be user-defined. If you want to do label transfer using your own reference, see the [mapping vignette](https://satijalab.org/seurat/articles/integration_mapping.html)

**Comment by hbandukw** [comment]
Are there any size contraints for either the reference or query datasets?

**Comment by timoast** [comment]
We do not set a size constrain in the software, any constraints will be determined by your hardware (available RAM) and R

**Comment by hbandukw** [comment]
Thanks a lot for the info!
