### ISSUE TITLE
RunMultiCCA failed on 500K cells 10x genomics RNA-seq data

### ISSUE THREAD

**Issue by shouguog** [satijalab/seurat#452]
I have 32 samples, each one has ~15K cells sequenced by 10Xgenomics.

When I run RunMultiCCA for alignment (with ~700 highly variable genes), the program was killed. Could you please give me some suggestions? Is it a memory problem?

Thank you

**Comment by shouguog** [comment]
library(Seurat)
rm(list=ls())
obj_list<-list()
for(sample in 1:32){
  cat(sample); cat("\n");
  S.data <- Read10X(data.dir = paste("../SfivePrimeR2GRCh38_", sample, "/outs/filtered_gene_bc_matrices/GRCh38/", sep=""))
  colnames(S.data)<-paste("S", sample, "_", colnames(S.data), sep="")
  S <- CreateSeuratObject(raw.data = S.data, project = paste("S", sample, sep=""), min.genes = 200)
  obj_list[[sample]]<-S
}

###we merge healthy and get the highly variable genes
##7,8,15,16,23,24,32
S.healthy<-obj_list[[7]]
S.healthy<-MergeSeurat(S.healthy, obj_list[[8]])
S.healthy<-MergeSeurat(S.healthy, obj_list[[15]])
S.healthy<-MergeSeurat(S.healthy, obj_list[[16]])
S.healthy<-MergeSeurat(S.healthy, obj_list[[23]])
S.healthy<-MergeSeurat(S.healthy, obj_list[[24]])
S.healthy<-MergeSeurat(S.healthy, obj_list[[32]])
S.healthy<-FindVariableGenes(S.healthy,x.high.cutoff = 8, y.cutoff = 0.75)
vargenes<-S.healthy@var.genes
####Let us scale data
for(sample in 1:32){
  cat(sample); cat("\n");
  obj_list[[sample]]<-ScaleData(NormalizeData(obj_list[[sample]]), genes.use = S.healthy@var.genes)
}


save(S.healthy, obj_list, file="step0.Obj")
####Let us run the alignment
#load("step0.Obj")
rm(S.healthy)
obj_merge<-RunMultiCCA(obj_list, genes.use = vargenes, num.ccs = 10)
cat("calculattion finished")
save(S.healthy, obj_list, obj_merge, file="step1.Obj")

**Comment by andrewwbutler** [comment]
It is likely that you are running into memory limits at that scale. What was the error message and how much memory do you have to work with?

**Comment by satijalab** [comment]
As suggested this is a memory issue for doing alignments of this scale, especially greater than 250k cells, which do require unreasonable amounts of memory. This will be improved in the near future, as we recognize that massive datasets of this scale are (excitingly!) becoming increasingly common.
