### ISSUE TITLE
scaled data question

### ISSUE THREAD

**Issue by lwhitmore** [satijalab/seurat#4523]
Hello, 
I have a question about scaled data. Why is a gene getting a scaled value that is not 0 if it is not expressed.

counts  :
![Capture1](https://user-images.githubusercontent.com/18075489/119195401-7132f800-ba39-11eb-9d58-ba7e9fec1c84.PNG)

RNA assay data slot:
![Capture2](https://user-images.githubusercontent.com/18075489/119195754-fcac8900-ba39-11eb-9768-0fb7ffe6effb.PNG)

Integrated assay scale data:
![Capture3](https://user-images.githubusercontent.com/18075489/119195821-15b53a00-ba3a-11eb-91be-b737b57f80c3.PNG)

Help in understanding why this is happening would be great!

Thanks, 
Leanne

**Comment by timoast** [comment]
Please include the full code you're running

**Comment by lwhitmore** [comment]
sample.list <- list(
    "CD4-T-cell_M_8hr_D1" = G001$seurat, "CD4-T-cell_M_IFNb_8hr_D1" = G002$seurat,
    "CD4-T-cell_HIV_8hr_D1" = G003$seurat, "CD4-T-cell_HIV_IFNb_8hr_D1" = G004$seurat,
    "CD4-T-cell_M_8hr_D2" = G005$seurat, "CD4-T-cell_M_IFNb_8hr_D2" = G006$seurat,
    "CD4-T-cell_HIV_8hr_D2" = G007$seurat, "CD4-T-cell_HIV_IFNb_8hr_D2" = G008$seurat
)

immune.anchors <- FindIntegrationAnchors(object.list = sample.list, dims = 1:20)
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)

immune.combined <- ScaleData(immune.combined,
    vars.to.regress = "percent.mt",
    features = all.genes, verbose = FALSE
)

DefaultAssay(immune.combined_sd) <- "integrated"
Idents(immune.combined_sd) <- immune.combined_sd$orig.ident
VlnPlot(immune.combined_sd, features = c("hiv-positive"), slot = "scale.data") + theme(legend.position = "none")
ggsave(file.path("5.FinalFigs", "Fig6b_HIV_Vlnscaled.png"), width = 6, height = 5, dpi = 500)
ggsave(file.path("5.FinalFigs", "Fig6b_HIV_Vlnscaled.svg"), width = 6, height = 5, dpi = 500)
ggsave(file.path("5.FinalFigs", "Fig6b_HIV_Vlnscaled.pdf"), width = 6, height = 5, dpi = 500)

**Comment by timoast** [comment]
So here you're plotting integrated data, not the original data. You need to instead look at the original uncorrected data

**Comment by lwhitmore** [comment]
right this is my question why is the integrated scaled data making it look like this gene is expressed when is not.
