### ISSUE TITLE
RunPCA function issue. vignettes/pbmc3k_tutorial.Rmd

### ISSUE THREAD

**Issue by jjacob12** [satijalab/seurat#4525]
Hi,
I have an issue that's related to **https://github.com/satijalab/seurat/issues/2962**
I'm an R novice. I'm working through the guided clustering tutorial (https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) and am stuck trying to run the PCA transformation code, wheareas all prior code works fine. The error message is pasted at the bottom. I'm running this code on the filtered (FindVariableFeatures using default arguments) PBMC dataset:

Seurat 4.0.1
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)
MacOS Big Sur 11.3.1

```{r}
pbmc <- RunPCA(pbmc) # 'pbmc' here is the processed gene matrix - using 'subset', 'Normalizedata', 'FindVariableFeatures', and 'ScaleData'

```
Error in PrepDR(object = object, features = features, verbose = verbose) : Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Could you please post the full code that you are running.  At first glance this doesn't appear to be related to that previous issue but simply that `FindVariableFeatures` has not been run prior to PCA.

Best,
Sam

**Comment by jjacob12** [comment]
Hi Sam,
Thanks for getting back to me. After trying several things, including shutting down RStudio, re-opening it and running each code chunk again, the PCA function worked. So, all sorted for now. 

Thanks,
John
