### ISSUE TITLE
SpatialDimPlot cannot adjust opacity whith 'alpha' parameter

### ISSUE THREAD

**Issue by xjs1996** [satijalab/seurat#4526]
Hi, thanks for offering such a good tool for spatial RNA_seq analysis~ I have a problem with 'SpatialDimPlot', and information attached below.
Code: SpatialDimPlot(mySeuratObjest, alpha = c(0.1,1))
Plot:
![图片](https://user-images.githubusercontent.com/31275922/119291442-0411a380-bc81-11eb-874c-07ec3dbfe185.png)

Is there something wrong?Looking forward for your reply!

**Comment by vkjain0006** [comment]
I have the same issue, alpha parameter just doesn't work with SpatialDimPlot function. It does work well with SpatialFeautrePlot function and their you do see tissue being visible.

**Comment by timoast** [comment]
As a workaround you can adjust the `alpha` parameter in the resulting `ggplot` object, for example:

```r
p <- SpatialDimPlot(brain)
p$mapping$alpha <- 0 # can set any number here
p
```
<img width="468" alt="Screen Shot 2021-05-28 at 12 54 57 PM" src="https://user-images.githubusercontent.com/4591688/120017477-eb242d80-bfb3-11eb-9165-d782d13f422e.png">

**Comment by timoast** [comment]
Or you can set

```r
p$layers[[1]]$aes_params$alpha <- 0.2  # any value 0-1
```

for more control on the degree of transparency

**Comment by andrewwbutler** [comment]
Hi,

This should be possible to control now on the `develop` branch by setting the `alpha` parameter to a single value (per plot). E.g.

```R
SpatialDimPlot(object, alpha = 0.5)
```

See installation instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1). Let us know if that doesn't resolve the issue.

**Comment by xjs1996** [comment]
Hi,

Sorry for late reply, I tried all the solution you provided above, they work and solved my problem perfectly, thank you so much~ But I failed to install develop version Seurat for network error "schannel: failed to receive handshake, SSL/TLS connection failed", sorry that I cannot test if the alpha parameter works or not now. 
I have another suggestion for "LinkedDimPlot": It will be very helpful if you can highlight the spot which mouse is hanging over both in the spatiadimlplot and dimplot.

Best regards.

**Comment by timoast** [comment]
Closing this for now since the original issue is solved. Adding a point showing the mouse position in the linked plot is, I think, much more complicated to implement and is a low priority currently
