### ISSUE TITLE
question: how to generate expression matrix files from 10x data?

### ISSUE THREAD

**Issue by shendong124** [satijalab/seurat#453]
I am currently trying to analyze 2 samples acquired from 10x, one control and one stimulated PBMC as indicated in this tutorial: http://satijalab.org/seurat/immune_alignment.html

For this example, I was wondering how you generated the xxx_expression_matrix.txt.gz files from the 10X outputs?
I’m looking at the files “immune_control_expression_matrix.txt.gz” and “immune_stimulated_expression_matrix.txt.gz” from the tutorial.
Thank you very much for your help,
Shen

**Comment by leonfodoulian** [comment]
Hi Shen,

If you want to read 10X samples in R, simply use the `Seurat::Read10X()` function. 

Best,
Leon

**Comment by xiaocong3333** [comment]
I have the same question. After I used the Read10X() function, how can I distinguish the two samples from each other as I read them at the same time?
