### ISSUE TITLE
Error on using Reciprocal PCA integration with SCTransform normalization 

### ISSUE THREAD

**Issue by ysu2015** [satijalab/seurat#4530]
Hi, 
I have a 16 samples, 200k cells dataset, would like to use RPCA integration with SCT normalization. I follow the step by step workflow provided in the seurat website, but get an error "Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:535 Calls: IntegrateData ... validObject -> anyStrings -> isTRUE -> validityMethod". I assumed this referred to too large dataset to handle. Is there any way to work around? I remembered mentioned somewhere that in SeuratV3, could do 2X8, integrate 8 datasets first, then integrated the 2 pre-integrated dataset again. I am not quite sure whether it is a probable way to do and how to do it. Any suggestion and help is appreciated. Thank you so much in advance.

Y

**Comment by yuhanH** [comment]
HI, 
In your rpca integration, do you set any reference object?

**Comment by ysu2015** [comment]
To YuhanH,

No. I just follow the scripts on the Seurat web. https://satijalab.org/seurat/articles/integration_rpca.html
Any suggestions?

Yijing

**Comment by ysu2015** [comment]
I actually request 500GB in our HPC, and it still not enough??

Y

**Comment by yuhanH** [comment]
Hi, 
Sure. You can have a loot at our tips for large datasets integration: https://satijalab.org/seurat/articles/integration_large_datasets.html
Generally, you can set one or two objects as a reference, and then other batches will be corrected based on the reference you set.

**Comment by ysu2015** [comment]
Cool, thank you so much. I will give a try.

Y
