### ISSUE TITLE
Too small number of anchors

### ISSUE THREAD

**Issue by semir2** [satijalab/seurat#4533]
Hi, Thanks for your great tools.

I am using it  integration spatial and scRNA, but there is a problems with it, when i use FindTransferAnchors function to find anchors, 40 anchors have been find, and I changed different par  and no more than 100 anchors could be find.
`
ref <- readRDS(ref_file) %>% SCTransform(assay = "RNA", verbose = FALSE) %>% RunPCA(verbose = FALSE)
spatial <- readRDS(rds_file) %>%  SCTransform( assay = "RNA", verbose = FALSE) %>% RunPCA(verbose = FALSE)
anchors <- FindTransferAnchors(reference = ref, query = spatial, normalization.method = "SCT",features =rownames(ref))
`
![image](https://user-images.githubusercontent.com/46958122/119450463-8031e700-bd66-11eb-82ea-b244449201e1.png)

So why I got so small number of anchors, Is there someting wrong with my code?

**Comment by timoast** [comment]
Please include the complete code and output of `sessionInfo()`

**Comment by timoast** [comment]
Please include the complete code
