### ISSUE TITLE
Which Assay to use before converting Seurat object to other object classes?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4534]
Hi there, 

Following up on issues #3883, #3764, and #3119, would anyone mind informing me when we need to set the Assay to 'RNA' versus 'SCT' in the conversion of Seurat object to SingleCellExperiment or Monocle object? My aim is to not have to do the data QC and regressing-out of cells and genes again. 

1. Is it correct that if I want to use SCTransform-ed data in another (non-Seurat) package, I should set assay=SCT when converting, and if I want to simply use the raw counts and log-normalized counts of my Seurat object in other pipeline, I will set assay=RNA? 

2. as.SingleCellExperiment() appears to transfer all assays and associated reduced dimensions whereas as.cell_data_set() for Monocle, this is not the case, but there are still counts and logcounts that get transferred which appear to be the same regardless if it were from RNA or SCT. For example, if I want to use UMAP generated by Seurat in Monocle, I should set assay = SCT during conversion, even though the actual counts and logcounts are the same?

Thank you for your help!

**When I set assay=SCT and do as.SingleCellExperiment conversion:**

<img width="614" alt="Screen Shot 2021-05-25 at 3 29 40 PM" src="https://user-images.githubusercontent.com/62179082/119515741-0867ba80-bd6e-11eb-9710-09f812403880.png">

**When I set assay=RNA and do as.SingleCellExperiment conversion:**

<img width="613" alt="Screen Shot 2021-05-25 at 3 33 57 PM" src="https://user-images.githubusercontent.com/62179082/119516391-a065a400-bd6e-11eb-83a2-91fe5d7cb3a0.png">

**When I set assay=SCT and do as.cell_data_set() conversion:**
<img width="595" alt="Screen Shot 2021-05-25 at 3 36 02 PM" src="https://user-images.githubusercontent.com/62179082/119516755-ecb0e400-bd6e-11eb-80db-f59ed5d6fd47.png">

**When I set assay=RNA and do as.cell_data_set() conversion:**
<img width="570" alt="Screen Shot 2021-05-25 at 3 44 43 PM" src="https://user-images.githubusercontent.com/62179082/119518102-21716b00-bd70-11eb-818b-ef2077bf018b.png">

**Comment by torkencz** [comment]
Hi, 
Issues with converting assays should now be fixed in the develop version of Seurat. Use instructions here to install (https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1). You can convert all of your assays and then switch between alternate experiments in the sce object.
