### ISSUE TITLE
stack VlnPlot with dots

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [satijalab/seurat#4536]
Dear Seurat team, I need to make a stacked violin plot, each one ploting a different feature.  But I would like to  keep seeing the points that correspond to the individual cells. I'm not sure why when I put TRUE on the stack, the points can no longer be seen, not even when putting a very large number to pt.size.
Could you help me to make a stacked violin plot with dots included in each plot?

My plot:
VlnPlot(subset,assay = "RNA", features = features,stack=TRUE,group.by = "Stanley_Profile", pt.size = 1, fill.by='ident', flip=TRUE)+stat_summary(fun.y = median, geom='point', size = 18, colour = "black", shape = 95)

BEst regards,
Sofia

**Comment by torkencz** [comment]
Hi, VlnPlot is ggplot based so I would just add +geom_point() to the end. In this case it worked:
data(pbmc_small)
fn<-head(row.names(pbmc_small))
VlnPlot(pbmc_small,assay = "RNA", features = fn,stack=TRUE,group.by = "groups", pt.size = 1, fill.by='ident', flip=TRUE)+geom_point()
I can reopen if it does not work in your case.

**Comment by sofiapuvogelvittini** [comment]
Hi thanks for your answer. Using geom_point() the dots appear, but just in a "line" in the middle of the violins, so its not possible discriminate two cells with same expression value.

[DEGS_Ast_2.pdf](https://github.com/satijalab/seurat/files/6574760/DEGS_Ast_2.pdf)

**Comment by torkencz** [comment]
+ geom_jitter() might work.
