### ISSUE TITLE
Seurat SCT based Transformtaion error

### ISSUE THREAD

**Issue by khandaud15** [satijalab/seurat#4539]
Hi, 
I am trying to do integration of scrna seq dataset using SCT based transformation and Anchors finding through CCA, I have approx 180K cells, at the time of Finding anchors, I always get an error.
Error in subCsp_rows(x, i, drop = drop) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: IntegrateData ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows

but if try the same script on cells less than 100k, it works fine. can you please help me whats I am doing wrong here? 

Thanks

**Comment by saketkc** [comment]
For larger datasets, we recommend the RPCA [workflow](https://satijalab.org/seurat/articles/integration_rpca.html) or [reference based integration](https://satijalab.org/seurat/articles/integration_large_datasets.html), can you give it a try? Feel free to reopen if there are any followup questions. I would also check how much RAM is available, this would definitely require at least 16 - 24 Gb.
