### ISSUE TITLE
Integrating single cell and ATAC Seq data

### ISSUE THREAD

**Issue by vkjain0006** [satijalab/seurat#4540]
Need suggestion on integrating single cell and ATAC seq data, when we have control and treatment samples available for both. 
If it would be 1 samples in each I believe it's pretty straight forward to integrate the samples together based on available vignette

https://satijalab.org/seurat/articles/atacseq_integration_vignette.html

But for integrating RNA  with ATAC seq where there are 2 samples each, I am wondering which approach should I use :-

1. Separately integrate control  RNA with control ATAC seq and treat  RNA  with treat ATAC seq and then compare difference between the two integrated sets.

2. Integrate control and treat of RNA seq and similarly control and treat of ATAC seq and then use this integrated data to integrate RNA and ATAC seq together. 

Not completely sure which approach should be the right one, or their is some another way to integrate this which I am missing. 
Please share your thoughts/suggestions. 

Thanks

**Comment by torkencz** [comment]
Hi, I think both approaches should work, although I am leaning towards first integrating cross modalities (1) and then doing the comparison between control and treatment. If you can identify shared clusters across modalities you could integrate between ATAC-ATAC (https://satijalab.org/signac/articles/integrate_atac.html) and RNA-RNA and see if the clusters are preserved.
