### ISSUE TITLE
Hashtag Reads Per Cell

### ISSUE THREAD

**Issue by jamesboot** [satijalab/seurat#4541]
Hello, we have some 10X data which we are currently troubleshooting. The data contains 6 different hashtags and when processed through the 10X cellranger pipeline we found only 2 out of 6 hashtags were detected. Consequently I have run the hashtag data through CITEseq-count to see if the problem can be recreated, or if more hashtags can be detected. 

I've then imported the hashtag output from CITEseq-count and the gene expression output for each cell into Seurat and generated a Seurat object. I've generated ridgeplots to see the expression of each hashtag in the various cell populations which has been very useful and have extracted a matrix with the normalised expression of each hashtag for each cell barcode which has also been very useful. 

However I was wondering if it is possible to extract the number of reads for each hashtag for each cell barcode in a similar way as the matrix of normalised expression for each hashtag for each cell barcode? Any help would be much appreciated!

**Comment by torkencz** [comment]
I may be misunderstanding your question (in which case I can reopen), but your HTO counts should be available through your HTO assay counts slot. You can access that via GetAssayData().
