### ISSUE TITLE
UpdateSymbolList generates wrong symbols

### ISSUE THREAD

**Issue by apredeus** [satijalab/seurat#4545]
Dear Seurat team, 

It seems like `UpdateSymbolList` uses a logic that results in erroneous changes to some gene symbols. 

There are quite a few genes for which official HGNC symbol co-insides with a symbol that was used for *another* gene in the past. The function automatically changes these. For example, HBM is a current name for "hemoglobin subunit mu", and an old name for "LDL receptor related protein 5", which are two totally different genes (https://www.genenames.org/tools/search/#!/?query=HBM). The function, however, converts HBM to LRP5. Similar thing happens to HBG1 and quite a few other genes.

I think there needs to be a check if gene symbol exists in the newest version - and if it does, the symbol should not be changed.

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting! We've made some fixes/updates to this function which hopefully resolve this problem. Please try installing the `develop` branch (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)) and see if that fixes the issue for you.
