### ISSUE TITLE
lose important marker genes after SCTransform

### ISSUE THREAD

**Issue by thugib** [satijalab/seurat#4547]
>  I am looking for a bit of expert advice. We are studying the stem cell niche in plant root. In this niche are a very few cells that are quiescent center cells. It is central to our study to identify these cells.  We have 4-5 marker genes for these cells. When I count the number of cells expressing each of these genes, then before normalization each gene is expressed in 4 to 1 cell(s). After SCTransform, there are zero cells that express either of these genes. In other words, there are no cells that express any of these genes. 

 >    Could you suggest any tweaking of the SCTransform parameters that might prevent the loss of expression of these genes during normalization ?

**Comment by saketkc** [comment]
Hi @thugib, SCTransform by default filters out genes that are expressed in <5 cells, so I am guessing that is what is happening here. You can reduce this threshold by doing `SCTransform(min_cells=3)`. You can additionally install after installing [glmGamPoi](https://bioconductor.org/packages/release/bioc/html/glmGamPoi.html) for speeding up the overall estimation and do `SCTransform(min_cells=3, method="glmGamPoi")`.

**Comment by thugib** [comment]
Thank you very much for your help. This information will help us a lot.
