### ISSUE TITLE
Can't able to install Seurat in Rstudio

### ISSUE THREAD

**Issue by Sleeplab2** [satijalab/seurat#4550]
I need to install seurat new version. I have tried by direction of Satija Lab guideline and by different youtube video. I have install R and R studio and R tool kit. I am very new in programming and have not much knowledge. That is what I got after commend. What should I do now. Please help.

[](R version 4.1.0 (2021-05-18) -- "**Camp Pontanezen**"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
> install.packages("seurat")
Installing package into ‘C:/Users/tosh/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘seurat’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  Perhaps you meant ‘Seurat’ ?
> install.packages("Seurat")
Installing package into ‘C:/Users/tosh/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/Seurat_4.0.2.zip'
Content type 'application/zip' length 2760190 bytes (2.6 MB)
downloaded 2.6 MB

package ‘Seurat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\tosh\AppData\Local\Temp\RtmpsvsY5N\downloaded_packages)
Please help anybody to install seurat properly. Thank you so much in advance.

**Comment by wanaga3166** [comment]
Hi Sleeplab2,

You need to do `install.packages("Seurat")`. You wrote: `install.packages("seurat")`. It's case sensitive.

**Comment by Sleeplab2** [comment]
> Hi Sleeplab2,
> 
> You need to do `install.packages("Seurat")`. You wrote: `install.packages("seurat")`. It's case sensitive.

**Comment by Sleeplab2** [comment]
Thank you Wanaga for your guidance. I have not basic knowledge on computer language. I already corrected that mistake, change my working directory but always Error .Fed-up from last few days, I don't able to create Seurat object. This software for who understand computer language. Not little bit user friendly for biologist who have not idea about computer knowledge. Never suggest for anyone.
