### ISSUE TITLE
do I need to select intersect gene for integration?

### ISSUE THREAD

**Issue by hansong798** [satijalab/seurat#4553]
Hello! 
Now, I'm in integration step for single cell data using Seurat.

My data have different number of genes for each and i got a question for this.
I'm trying to integrate data using FindIntegrationAnchors() and IntegrateData() function.
If the number of  genes in A data is 1000 and another is 1300, these functions return integrated data having 1500 genes, which are total genes from two data.

In this case, 
Isn't it necessary to extract the data so that both data contain only common genes?
Or are gene values which is not included in one data estimated by imputation?

Thank you and hopefully this makes sense.

**Comment by timoast** [comment]
Please see the `SelectIntegrationFeatures()` function and `anchor.features` parameter in `FindIntegrationAnchors()`. It's not necessary to subset the objects so that they only contain common features
