### ISSUE TITLE
Converting an RDS object created by seurat V4 to an RDS format that V3 can read ？

### ISSUE THREAD

**Issue by chanchan-wu** [satijalab/seurat#4555]
RDS files generated with the new Seurat version(v4.0.1) cannot be read with previous versions (3.1 in my case). Is updating R and Seurat (along with accompanying packages) the only solution? Is there any way to change an RDS object created by V4 to an RDS format that V3 can read ？

**Comment by timoast** [comment]
We don't support backwards conversion of the Seurat object from v4 to v3, I'd suggest updating Seurat if you can, or you can create a new v3 object from the count matrix and metadata present in the v4 object
