### ISSUE TITLE
How can I remove the legend for cell identity but not expression color bar using Doheatmap?

### ISSUE THREAD

**Issue by shoma-tsubota** [satijalab/seurat#4557]
Hi all, I used DoHeatmap to see a set of gene expression in different cell types identified. With default setting, it returns label and legend for identified cell types (identity). I want to remove it from legend. But I also want to keep color bar for expression levels.
Could you teach me how to do it? Can I do it in DoHeatmap or ggplot2?

**Comment by royfrancis** [comment]
You can control the legends individually. Here is an example:

    DoHeatmap(ss, features = m1$gene)

![Screenshot from 2021-06-03 14-15-03](https://user-images.githubusercontent.com/5083500/120643466-7dc24200-c476-11eb-9b19-1ab5ca94258e.png)

    DoHeatmap(ss, features = m1$gene)+
      guides(colour=FALSE)

![Screenshot from 2021-06-03 14-15-52](https://user-images.githubusercontent.com/5083500/120643483-81ee5f80-c476-11eb-991c-599ac6aff56e.png)

    DoHeatmap(ss, features = m1$gene)+
      guides(fill=FALSE)

![Screenshot from 2021-06-03 14-16-14](https://user-images.githubusercontent.com/5083500/120643490-8581e680-c476-11eb-83fb-7cb4f6a461bb.png)

    DoHeatmap(ss, features = m1$gene)+
      theme(legend.position="none")

![Screenshot from 2021-06-03 14-16-59](https://user-images.githubusercontent.com/5083500/120643500-89156d80-c476-11eb-9bb9-b601e2ccb2be.png)

**Comment by shoma-tsubota** [comment]
Thanks a lot Roy Francis!! I was not understand which was for color and fill.
