### ISSUE TITLE
How to set the `ctrl` parameter in `AddModuleScore` ?

### ISSUE THREAD

**Issue by sarahbonnin** [satijalab/seurat#4558]
Hello,

I am using the `AddModuleScore` function on a set of genes/features. 

I was wondering how to set the `ctrl` parameter? Does it have to do with how many genes/features I set as `features`?

I see that it is set at 100 by default, while in some examples I saw it is set at 5, and I didn't find information on how to optimally choose it. Shall I most of the time leave it at 100? Is it very critical?

Thank you so much for the great package!

**Comment by jaisonj708** [comment]
100 is usually a safe choice for `ctrl`. With a lower value of `ctrl`, you'll be comparing each feature in your module to a smaller set of "control" features, which might increase the noise of your score estimate. You can always increase `ctrl` beyond 100, but there may be minimal benefit.

**Comment by sarahbonnin** [comment]
Thank you so much! 100 it is, then.
