### ISSUE TITLE
WISH: show() for seurat object to be more informative

### ISSUE THREAD

**Issue by HenrikBengtsson** [satijalab/seurat#456]
In Seurat 2.3.0, print:ing (= `show()`:ing for S4 objects) a seurat object outputs something like:
```r
> fit  ## calls print(fit), which calls show(fit)
An object of class seurat in project 1237 
 14058 genes across 9249 samples.
```

It would be informative if `show()` for seurat objects also reported on what steps has been performed, e.g.
```r
> names(fit@calc.params)
[1] "CreateSeuratObject"   "NormalizeData"        "ScaleData"            "RunMultiCCA"
[5] "RunPCA"              "BuildSNN"             "FindClusters.res.0.6
```

**Comment by satijalab** [comment]
Apologies for the very slow reply. We appreciate the feedback and agree - this will be added to an upcoming version.
