### ISSUE TITLE
Indeed really strange error

### ISSUE THREAD

**Issue by kim881030** [satijalab/seurat#4560]
Hi, folks. 

I tried to merge all samples into one combined object but one cannot be merged but appeared "SeueratProject" (Check the figure)

<img width="1276" alt="스크린샷 2021-05-28 오전 10 31 23" src="https://user-images.githubusercontent.com/63928679/120388173-c8b64b00-c2f8-11eb-8429-1102a732de9e.png">

Here is the code that I used. I loaded the Seurat library

# Basic step 
> JSS1.data <- Read10X(data.dir = "/blue/zhangw/my.kim/sjogren/JSS/outs/per_sample_outs/JSS_1/count/sample_feature_bc_matrix/")
> JSS2.data <- Read10X(data.dir = "/blue/zhangw/my.kim/sjogren/JSS/outs/per_sample_outs/JSS_3/count/sample_feature_bc_matrix/")

.......

> HC1.data <- Read10X(data.dir = "/blue/zhangw/my.kim/sjogren/HC/outs/per_sample_outs/HC_1/count/sample_feature_bc_matrix/")
> HC2.data <- Read10X(data.dir = "/blue/zhangw/my.kim/sjogren/HC/outs/per_sample_outs/HC_2/count/sample_feature_bc_matrix/")
> HC3.data <- Read10X(data.dir = "/blue/zhangw/my.kim/sjogren/HC/outs/per_sample_outs/HC_3/count/sample_feature_bc_matrix/") # There should be no typo here.

# make objects
> JSS1 <- CreateSeuratObject(counts = JSS1.data$`Gene Expression`, project = "JSS1")
> JSS1$Subset <- "JSS"
> JSS2 <- CreateSeuratObject(counts = JSS2.data$`Gene Expression`, project = "JSS2")
> JSS2$Subset <- "JSS"
> JSS3 <- CreateSeuratObject(counts = JSS3.data$`Gene Expression`, project = "JSS3")
> JSS3$Subset <- "JSS"
> JSS4 <- CreateSeuratObject(counts = JSS4.data$`Gene Expression`, project = "JSS4")
> JSS4$Subset <- "JSS"

.....

> HC1 <- CreateSeuratObject(counts = HC1.data$`Gene Expression`, project = "HC1")
> HC1$Subset <- "HC"
> HC2 <- CreateSeuratObject(counts = HC2.data$`Gene Expression`, project = "HC2")
> HC2$Subset <- "HC"
> HC3 <- CreateSeuratObject(counts = HC3.data$`Gene Expression`, prooect = "HC3")
> HC3$Subset <- "HC" 
> HC4 <- CreateSeuratObject(counts = HC4.data$`Gene Expression`, project = "HC4")
> HC4$Subset <- "HC"

#
> JSS.BIG <-merge(JSS1, y = c(JSS2, JSS3, JSS4, Non_JSS1, Non_JSS2, Non_JSS3, Non_JSS4, HC1, HC2, HC3, HC4, BP1, BP2, BP3, BP4, BPRP1, BPRP2, BPRP3, BPRP4), add.cell.ids = c("JSS1", "JSS2", "JSS3", "JSS4", "Non_JSS1", "Non_JSS2", "Non_JSS3", "Non_JSS4", "HC1", "HC2", "HC3", "HC4", "BP1", "BP2", "BP3", "BP4", "BPRP1", "BPRP2","BPRP3","BPRP4"), project = "JSS.ALL")

#
> JSS.BIG[["percent.mt"]] <- PercentageFeatureSet(JSS.BIG, pattern = "^MT-")
> VlnPlot(JSS.BIG, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0) 

As you notice, the HC3 subset is missing and appears as SeuratObject at the end. Also, there no error found while running these codes.

Have you ever happened to you before? 
* I tried to normalize individual files before merging, but it did not work.
* Output of table(JSS.BIG[[]]$orig.ident) did not contained HC3
* I also uploaded metadata information.
<img width="1018" alt="스크린샷 2021-05-30 오전 9 54 37" src="https://user-images.githubusercontent.com/63928679/120388970-d3bdab00-c2f9-11eb-8767-d03e0f3fa05e.png">

Thank you in advance.

**Comment by kim881030** [comment]
I'm so sorry to bother you. Yes. You're right. The issue has been solved. I appreciate it.

**Comment by kim881030** [comment]
Closed.

**Comment by samuel-marsh** [comment]
No worries, glad to help!
