### ISSUE TITLE
Biomarker and Barcode

### ISSUE THREAD

**Issue by Gamegon** [satijalab/seurat#4562]
Is there any way by which we can compare the cluster cells with their respective biomarker as well as barcode.

So I have a dataset, it has markers, barcodes defined but no cell types. I want to get the cluster cells with their biomarkers and barcodes from datasets.

**Comment by torkencz** [comment]
Hi,

I might be misunderstanding what you are asking. If you want to compare markers of clusters of cells doing a heatmap on DE genes that you defined based on your clustering should help. For further info I would refer you to https://satijalab.org/seurat/articles/pbmc3k_tutorial.html. If that is not what you are asking could you elaborate and I can reopen.

**Comment by Gamegon** [comment]
Hi,

Actually I was able to cluster the cells from the same platform you provided but the problem is I want to look for barcodes specific to a gene or biomarker in the data.

would it be possible to get that information from .txt based dataset.
