### ISSUE TITLE
SCTransform Analysis

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#4565]
Loving this software and support! Some quick questions:

1. Can we use SCTransform to run TSNE instead of UMAP?
2. When we want to `RunPCA()`, `RunTSNE()`, `FindNeighbors()`,  `FindClusters()`, should it be run on the SCT or integrated assay? I assume it is the integrated assay...
3. When I want to run FinMarkers() we revert back to the RNA assay? I found #1928 which said that we still need to normalise and scale the raw data ...is this still correct for the latest version?
4. When would it be appropriate to use the SCT assay on SCTransormed data?

**Comment by jaisonj708** [comment]
Hi, thanks for your questions-
1) Absolutely, you can run PCA on your SCTransformed counts followed by any nonlinear dimreduc including TSNE
2) If you are integrating different datasets, then it is best to use the `integrated` assay for downstream processing. This should automatically be your object's `DefaultAssay` after running integration, so there is no need to specify parameters in most cases.
3) Yes you should specify `assay="RNA"` in `FindMarkers`. It is necessary to normalize your data for default FindMarkers usage. Scaling your data is not necessary but normally you will end up doing this anyways for downstream processing (e.g, scaling -> dimension reduction -> clustering -> annotation).
