### ISSUE TITLE
Log normalisation for spatial data

### ISSUE THREAD

**Issue by royfrancis** [satijalab/seurat#4571]
The example from the vignette shows the group correlation for log-normalized and sctransform-normalized to be different.

```
brain <- LoadData("stxBrain", type = "anterior1")

brain <- SCTransform(brain, assay = "Spatial", return.only.var.genes = FALSE, verbose = FALSE)
brain <- NormalizeData(brain, verbose = FALSE, assay = "Spatial")

brain <- GroupCorrelation(brain, group.assay = "Spatial", assay = "Spatial", slot = "data", do.plot = FALSE)
brain <- GroupCorrelation(brain, group.assay = "Spatial", assay = "SCT", slot = "scale.data", do.plot = FALSE)

p1 <- GroupCorrelationPlot(brain, assay = "Spatial", cor = "nCount_Spatial_cor") + ggtitle("Log Normalization") + 
  theme(plot.title = element_text(hjust = 0.5))
p2 <- GroupCorrelationPlot(brain, assay = "SCT", cor = "nCount_Spatial_cor") + ggtitle("SCTransform Normalization") + 
  theme(plot.title = element_text(hjust = 0.5))
p1 + p2
```

![](https://satijalab.org/seurat/articles/spatial_vignette_files/figure-html/norm.test3-1.png)  
**Fig 1**: Same figure from the vignette.  

I noticed that the **slot** argument is different in `GroupCorrelation()` step. So, I reran it using "data" in both steps as well as "scale.data" in both steps.

![Screenshot from 2021-06-03 13-38-51](https://user-images.githubusercontent.com/5083500/120640796-2cfd1a00-c473-11eb-8507-511928e9b79d.png)  
**Fig2**: Using **data**.

![Screenshot from 2021-06-03 13-42-11](https://user-images.githubusercontent.com/5083500/120640818-32f2fb00-c473-11eb-8d19-134762a5d9b5.png)  
**Fig 3**: Using **scale.data**.

Turns out it's not dramatically different from the first figure. `scTransform()` does seem to be doing a better job.

But a different story for my data. Smaller sample size though (451 spots compared to 2696 for the brain data used in the vignette).

![group-cor-data](https://user-images.githubusercontent.com/5083500/120640504-dabbf900-c472-11eb-926b-5193e17d2838.png)  
**Fig 4**: Using **data**. `scTransform()` doesn't make a big difference?

![group-cor-scale data](https://user-images.githubusercontent.com/5083500/120640555-e9a2ab80-c472-11eb-8c54-36fc53e1ccd2.png)  
**Fig 5**: Using **scale.data**. Not sure what's going on.

Is it better to run `scTransform()`? If `scTransform()` doesn't make a big difference, is it ok to stick to log normalization? It is less headache overall in downstream steps.

**Comment by saketkc** [comment]
I agree with your observations, it is possible that log normalization and SCTransform give comparable results (correlation/UMAPs..) if the variations appearing from sequencing depth are minimal. SCTransform based workflow require only minor modification (usually one command and an argument) downstream. Feel free to reopen with any follow up questions.
