### ISSUE TITLE
Seurat analysis

### ISSUE THREAD

**Issue by sadaf1995** [satijalab/seurat#4572]
Hi everyone, 

I recently started using R and Seurat tutorials for single cell analysis and I'm now using feature plots to compare the markers' expression in clusters. I have to check all 20 top markers in each cluster, so I run one featureplot for first 10 and another for the second 10 top so that it's better visible. How can I do it automatically? I mean how can I define for instance that ok first show me the feature plot of the the first top 10 markers and then second top 10 without writing the genes manually one by one. 

Thanks in advance

**Comment by samuel-marsh** [comment]
Hi,

Are your marker genes in a vector or in the output data.frame of `FindMarkers`?

Best,
Sam

**Comment by sadaf1995** [comment]
> Hi,
> 
> Are your marker genes in a vector or in the output data.frame of `FindMarkers`?
> 
> Best,
> Sam

Hi,

I'm not sure if I got correct, but I guess output dataframe of findmarkers. So basically I isolated the population of interest, reclustered them again and found all genes and then top 20s.

**Comment by sadaf1995** [comment]
> Hi,
> 
> Are your marker genes in a vector or in the output data.frame of `FindMarkers`?
> 
> Best,
> Sam
I use command below:
FeaturePlot(Endothelial_cells, reduction = 'umap', label = T, features = c('genes')) and I write the gens manually, so I was wondering how to do it more efficiently

**Comment by samuel-marsh** [comment]
Hi,

Ok well here is very basic manual way using example using data from basic tutorial vignette (obviously specific parameters you provide to `FindAllMarkers` and other functions are up to you.):
```
# Run FindAllMarkers
pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

# Group output by cluster and filter for top XX markers per cluster
top20_markers <- pbmc.markers %>%
  group_by(cluster) %>%
  top_n(n = 20, wt = avg_log2FC)

# Extract gene names for given cluster
clu0 <- top20 %>% 
  filter(cluster == "0") %>% 
  pull(gene)

# First 10 genes
FeaturePlot(pbmc, label = T, features = clu0[1:10])

# Second 10 genes
FeaturePlot(pbmc, label = T, features = clu0[11:20])
```

Best,
Sam
