### ISSUE TITLE
RNA assay is lost when converting back to Seurat object with as.Seurat

### ISSUE THREAD

**Issue by thugib** [satijalab/seurat#4575]
I want to use decontX from the celda package, but it takes a SingleCellExperiment object, so I convert my Seurat object to a sce object; run decontX; then convert back to a Seurat object with as.Seurat. However, when I convert back to a Seurat object and run SCTransform I get the following error ( I have done this with previous versions of Seurat and celda and it has worked fine.) :

_Error in GetAssay.Seurat(object = object, assay = assay) : 
  RNA is not an assay present in the given object. Available assays are: **originalexp**  (I added the bold type.)_

  When comparing my original Seurat object to the conveted-back-to_Seurat object, I can see that where in my original Seurat object there is : 

_..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "SeuratObject"] with 8 slots_

in the converted-back-to-Seurat object is :

 _..@ assays      :List of 1
  .. ..$ **originalexp**:Formal class 'Assay' [package "SeuratObject"] with 8 slots_  (I added the bold type.)

Would this be as easy as just changing 'originalexp' to 'RNA' ?   
And, if so, how would I do this ?

  I am using Seurat 4.0.2.9004 and SeuratObject 4.0.1

**Comment by saketkc** [comment]
Can you try updating to latest dev version of Seurat with instructions [here](https://satijalab.org/seurat/articles/install.html) and see if the latest fix addresses your issue?

**Comment by thugib** [comment]
HI saketks, 
   Thanks for your help.
    I followed the commands on the URL you gave me to install the development version of Seurat and I now have Seurat_4.0.2.9004 and I still get the same results. I will put my sessionInfo at the end.

 **I did notice that when I load Seurat I get the following message: 
library(Seurat)
> Registered S3 method overwritten by 'spatstat.geom':
  method     from
  print.boxx cli 

> " Attaching package: ‘Seurat’

> The following object is masked from ‘package:SummarizedExperiment’:

>    Assays (There are two asterisks immediately after the word Assays, but including them messes up the markdown..)
   
   Normally, with a masked function I think you need to specify the package with the command, something like Seurat::SCTransform() instead of just SCTtransform(), but I do not know what to do in the case of a masked object.  

My commands are: 

library(Seurat)
library(celda)
Aminus <- Read10X(data.dir = "/home/March_21_2Am/filtered_feature_bc_matrix")
Am <- CreateSeuratObject(counts = Aminus)
Am <- PercentageFeatureSet(Am, pattern = "^ATM", col.name = "percent.mt")
Am.sce <- as.SingleCellExperiment(Am)
Am.sce.dcX <- decontX(Am.sce)
Am.dcX.seurat <- as.Seurat(Am.sce.dcX)
Am.dcX.mincells1 <- SCTransform(Am.dcX.seurat, method = "glmGamPoi", vars.to.regress = "percent.mt", min_cells=1, verbose = FALSE)

After the last command, I get the following:
_Error in GetAssay.Seurat(object = object, assay = assay) : 
  RNA is not an assay present in the given object. Available assays are: originalexp_

The original Seurat object, Am, has:
_Formal class 'Seurat' [package "SeuratObject"] with 13 slots_
  _..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "SeuratObject"] with 8 slots_

The converted to SingleCellExperiment object, Am.sce has: 
_Formal class 'SingleCellExperiment' [package "SingleCellExperiment"] with 9 slots_
... 
 ..@ assays             :Formal class 'SimpleAssays' [package "SummarizedExperiment"] with 1 slot
  .. .. ..@ data:Formal class 'SimpleList' [package "S4Vectors"] with 4 slots

After running decontX, Am.sce.dcX:
_Formal class 'SingleCellExperiment' [package "SingleCellExperiment"] with 9 slots_
...
  _..@ assays             :Formal class 'SimpleAssays' [package "SummarizedExperiment"] with 1 slot
  .. .. ..@ data:Formal class 'SimpleList' [package "S4Vectors"] with 4 slots_

Then converting back to Seurat object, Am.dcX.seurat:
_Formal class 'Seurat' [package "SeuratObject"] with 13 slots
  ..@ assays      :List of 1
  .. ..$ originalexp:Formal class 'Assay' [package "SeuratObject"] with 8 slots_


sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] glmGamPoi_1.4.0             celda_1.8.1                 SingleCellExperiment_1.14.1 Seurat_4.0.2.9004          
 [5] SummarizedExperiment_1.22.0 Biobase_2.52.0              GenomicRanges_1.44.0        GenomeInfoDb_1.28.0        
 [9] IRanges_2.26.0              S4Vectors_0.30.0            BiocGenerics_0.38.0         MatrixGenerics_1.4.0       
[13] matrixStats_0.59.0          SeuratObject_4.0.1         

loaded via a namespace (and not attached):
  [1] utf8_1.2.1                 reticulate_1.20            tidyselect_1.1.1           htmlwidgets_1.5.3         
  [5] grid_4.1.0                 combinat_0.0-8             BiocParallel_1.26.0        Rtsne_0.15                
  [9] munsell_0.5.0              ScaledMatrix_1.0.0         codetools_0.2-18           ica_1.0-2                 
 [13] statmod_1.4.36             scran_1.20.1               future_1.21.0              miniUI_0.1.1.1            
 [17] withr_2.4.2                colorspace_2.0-1           rstudioapi_0.13            ROCR_1.0-11               
 [21] assertive.base_0.0-9       tensor_1.5                 listenv_0.8.0              GenomeInfoDbData_1.2.6    
 [25] polyclip_1.10-0            rprojroot_2.0.2            parallelly_1.25.0          vctrs_0.3.8               
 [29] generics_0.1.0             R6_2.5.0                   doParallel_1.0.16          ggbeeswarm_0.6.0          
 [33] rsvd_1.0.5                 RcppEigen_0.3.3.9.1        locfit_1.5-9.4             bitops_1.0-7              
 [37] spatstat.utils_2.1-0       gridGraphics_0.5-1         DelayedArray_0.18.0        assertthat_0.2.1          
 [41] promises_1.2.0.1           scales_1.1.1               beeswarm_0.4.0             gtable_0.3.0              
 [45] beachmat_2.8.0             globals_0.14.0             processx_3.5.2             goftest_1.2-2             
 [49] rlang_0.4.11               splines_4.1.0              lazyeval_0.2.2             spatstat.geom_2.1-0       
 [53] reshape2_1.4.4             abind_1.4-5                httpuv_1.6.1               tools_4.1.0               
 [57] ggplot2_3.3.3              ellipsis_0.3.2             spatstat.core_2.1-2        RColorBrewer_1.1-2        
 [61] ggridges_0.5.3             Rcpp_1.0.6                 plyr_1.8.6                 sparseMatrixStats_1.4.0   
 [65] zlibbioc_1.38.0            purrr_0.3.4                RCurl_1.98-1.3             ps_1.6.0                  
 [69] prettyunits_1.1.1          dbscan_1.1-8               rpart_4.1-15               deldir_0.2-10             
 [73] pbapply_1.4-3              viridis_0.6.1              cowplot_1.1.1              zoo_1.8-9                 
 [77] ggrepel_0.9.1              cluster_2.1.2              magrittr_2.0.1             RSpectra_0.16-0           
 [81] data.table_1.14.0          magick_2.7.2               scattermore_0.7            lmtest_0.9-38             
 [85] RANN_2.6.1                 fitdistrplus_1.1-5         patchwork_1.1.1            mime_0.10                 
 [89] xtable_1.8-4               gridExtra_2.3              compiler_4.1.0             scater_1.20.0             
 [93] tibble_3.1.2               KernSmooth_2.23-20         crayon_1.4.1               htmltools_0.5.1.1         
 [97] mgcv_1.8-36                later_1.2.0                tidyr_1.1.3                MCMCprecision_0.4.0       
[101] DBI_1.1.1                  assertive.files_0.0-2      MASS_7.3-54                assertive.numbers_0.0-2   
[105] Matrix_1.3-4               cli_2.5.0                  assertive.types_0.0-3      metapod_1.0.0             
[109] igraph_1.2.6               pkgconfig_2.0.3            plotly_4.9.3               scuttle_1.2.0             
[113] spatstat.sparse_2.0-0      foreach_1.5.1              vipor_0.4.5                dqrng_0.3.0               
[117] XVector_0.32.0             stringr_1.4.0              callr_3.7.0                digest_0.6.27             
[121] sctransform_0.3.2          RcppAnnoy_0.0.18           spatstat.data_2.1-0        leiden_0.3.8              
[125] enrichR_3.0                uwot_0.1.10                edgeR_3.34.0               DelayedMatrixStats_1.14.0 
[129] curl_4.3.1                 shiny_1.6.0                rjson_0.2.20               lifecycle_1.0.0           
[133] nlme_3.1-152               jsonlite_1.7.2             BiocNeighbors_1.10.0       viridisLite_0.4.0         
[137] limma_3.48.0               fansi_0.5.0                pillar_1.6.1               lattice_0.20-44           
[141] fastmap_1.1.0              httr_1.4.2                 pkgbuild_1.2.0             survival_3.2-11           
[145] glue_1.4.2                 remotes_2.4.0              png_0.1-7                  iterators_1.0.13          
[149] multipanelfigure_2.1.2     bluster_1.2.1              assertive.properties_0.0-4 stringi_1.6.2             
[153] BiocSingular_1.8.0         dplyr_1.0.6                irlba_2.3.3                future.apply_1.7.0

**Comment by JTpath** [comment]
I have a similar issue, converting to and from SCE duplicates the data. If I normalise the data in scran, that ends up in the `originalexp` assay and the `RNA` assay only has counts.

Thanks for your help

``` r
library(Seurat)
#> Registered S3 method overwritten by 'spatstat.geom':
#>   method     from
#>   print.boxx cli
#> Attaching SeuratObject
library(hdf5r)
url <-
  "https://cf.10xgenomics.com/samples/cell-exp/6.0.0/Brain_3p_LT/Brain_3p_LT_filtered_feature_bc_matrix.h5"
tmp_filename <- tempfile()
download.file(url, tmp_filename)
seu <- Read10X_h5(tmp_filename, use.names = TRUE)
#> Warning in sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x =
#> counts[]), : 'giveCsparse' has been deprecated; setting 'repr = "T"' for you
seu <- CreateSeuratObject(seu)
sce <- as.SingleCellExperiment(seu)
seu2 <- as.Seurat(sce)
seu
#> An object of class Seurat 
#> 36601 features across 626 samples within 1 assay 
#> Active assay: RNA (36601 features, 0 variable features)
sce
#> class: SingleCellExperiment 
#> dim: 36601 626 
#> metadata(0):
#> assays(2): counts logcounts
#> rownames(36601): MIR1302-2HG FAM138A ... AC007325.4 AC007325.2
#> rowData names(0):
#> colnames(626): AATCACGAGATCACCT-1 AATCACGAGCCTCTTC-1 ...
#>   TTTGTTGTCCCAACTC-1 TTTGTTGTCCTTATCA-1
#> colData names(4): orig.ident nCount_RNA nFeature_RNA ident
#> reducedDimNames(0):
#> altExpNames(1): RNA
seu2
#> An object of class Seurat 
#> 73202 features across 626 samples within 2 assays 
#> Active assay: RNA (36601 features, 0 variable features)
#>  1 other assay present: originalexp
```

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Europe/London               
 date     2021-06-07                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version    date       lib source                                 
 abind                  1.4-5      2016-07-21 [1] CRAN (R 4.0.2)                         
 assertthat             0.2.1      2019-03-21 [1] CRAN (R 4.0.2)                         
 backports              1.2.1      2020-12-09 [1] CRAN (R 4.0.2)                         
 Biobase                2.50.0     2020-10-27 [1] Bioconductor                           
 BiocGenerics           0.36.1     2021-04-16 [1] Bioconductor                           
 BiocManager            1.30.15    2021-05-11 [1] CRAN (R 4.0.2)                         
 bit                    4.0.4      2020-08-04 [1] CRAN (R 4.0.2)                         
 bit64                  4.0.5      2020-08-30 [1] CRAN (R 4.0.2)                         
 bitops                 1.0-7      2021-04-24 [1] CRAN (R 4.0.2)                         
 cachem                 1.0.5      2021-05-15 [1] CRAN (R 4.0.2)                         
 callr                  3.7.0      2021-04-20 [1] CRAN (R 4.0.2)                         
 cli                    2.5.0      2021-04-26 [1] CRAN (R 4.0.2)                         
 clipr                  0.7.1      2020-10-08 [1] CRAN (R 4.0.2)                         
 cluster                2.1.2      2021-04-17 [1] CRAN (R 4.0.2)                         
 codetools              0.2-18     2020-11-04 [1] CRAN (R 4.0.5)                         
 colorspace             2.0-1      2021-05-04 [1] CRAN (R 4.0.2)                         
 cowplot                1.1.1      2020-12-30 [1] CRAN (R 4.0.2)                         
 crayon                 1.4.1      2021-02-08 [1] CRAN (R 4.0.2)                         
 data.table             1.14.0     2021-02-21 [1] CRAN (R 4.0.2)                         
 DBI                    1.1.1      2021-01-15 [1] CRAN (R 4.0.3)                         
 DelayedArray           0.16.3     2021-03-24 [1] Bioconductor                           
 deldir                 0.2-10     2021-02-16 [1] CRAN (R 4.0.2)                         
 desc                   1.3.0      2021-03-05 [1] CRAN (R 4.0.2)                         
 devtools               2.4.2      2021-06-07 [1] CRAN (R 4.0.5)                         
 digest                 0.6.27     2020-10-24 [1] CRAN (R 4.0.2)                         
 dplyr                  1.0.6      2021-05-05 [1] CRAN (R 4.0.2)                         
 ellipsis               0.3.2      2021-04-29 [1] CRAN (R 4.0.2)                         
 evaluate               0.14       2019-05-28 [1] CRAN (R 4.0.1)                         
 fansi                  0.5.0      2021-05-25 [1] CRAN (R 4.0.2)                         
 fastmap                1.1.0      2021-01-25 [1] CRAN (R 4.0.2)                         
 fitdistrplus           1.1-5      2021-05-28 [1] CRAN (R 4.0.5)                         
 fs                     1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                         
 future                 1.21.0     2020-12-10 [1] CRAN (R 4.0.3)                         
 future.apply           1.7.0      2021-01-04 [1] CRAN (R 4.0.2)                         
 generics               0.1.0      2020-10-31 [1] CRAN (R 4.0.2)                         
 GenomeInfoDb           1.26.7     2021-04-08 [1] Bioconductor                           
 GenomeInfoDbData       1.2.4      2021-01-17 [1] Bioconductor                           
 GenomicRanges          1.42.0     2020-10-27 [1] Bioconductor                           
 ggplot2                3.3.3      2020-12-30 [1] CRAN (R 4.0.2)                         
 ggrepel                0.9.1      2021-01-15 [1] CRAN (R 4.0.2)                         
 ggridges               0.5.3      2021-01-08 [1] CRAN (R 4.0.2)                         
 globals                0.14.0     2020-11-22 [1] CRAN (R 4.0.2)                         
 glue                   1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                         
 goftest                1.2-2      2019-12-02 [1] CRAN (R 4.0.2)                         
 gridExtra              2.3        2017-09-09 [1] CRAN (R 4.0.2)                         
 gtable                 0.3.0      2019-03-25 [1] CRAN (R 4.0.2)                         
 hdf5r                * 1.3.2      2020-03-25 [1] CRAN (R 4.0.1)                         
 highr                  0.9        2021-04-16 [1] CRAN (R 4.0.5)                         
 htmltools              0.5.1.1    2021-01-22 [1] CRAN (R 4.0.2)                         
 htmlwidgets            1.5.3      2020-12-10 [1] CRAN (R 4.0.3)                         
 httpuv                 1.6.1      2021-05-07 [1] CRAN (R 4.0.2)                         
 httr                   1.4.2      2020-07-20 [1] CRAN (R 4.0.2)                         
 ica                    1.0-2      2018-05-24 [1] CRAN (R 4.0.2)                         
 igraph                 1.2.6      2020-10-06 [1] CRAN (R 4.0.2)                         
 IRanges                2.24.1     2020-12-12 [1] Bioconductor                           
 irlba                  2.3.3      2019-02-05 [1] CRAN (R 4.0.2)                         
 jsonlite               1.7.2      2020-12-09 [1] CRAN (R 4.0.2)                         
 KernSmooth             2.23-20    2021-05-03 [1] CRAN (R 4.0.2)                         
 knitr                  1.33       2021-04-24 [1] CRAN (R 4.0.2)                         
 later                  1.2.0      2021-04-23 [1] CRAN (R 4.0.2)                         
 lattice                0.20-44    2021-05-02 [1] CRAN (R 4.0.2)                         
 lazyeval               0.2.2      2019-03-15 [1] CRAN (R 4.0.2)                         
 leiden                 0.3.8      2021-05-24 [1] CRAN (R 4.0.5)                         
 lifecycle              1.0.0      2021-02-15 [1] CRAN (R 4.0.2)                         
 listenv                0.8.0      2019-12-05 [1] CRAN (R 4.0.2)                         
 lmtest                 0.9-38     2020-09-09 [1] CRAN (R 4.0.2)                         
 magrittr               2.0.1      2020-11-17 [1] CRAN (R 4.0.2)                         
 MASS                   7.3-54     2021-05-03 [1] CRAN (R 4.0.2)                         
 Matrix                 1.3-4      2021-06-01 [1] CRAN (R 4.0.2)                         
 MatrixGenerics         1.2.1      2021-01-30 [1] Bioconductor                           
 matrixStats            0.59.0     2021-06-01 [1] CRAN (R 4.0.2)                         
 memoise                2.0.0      2021-01-26 [1] CRAN (R 4.0.2)                         
 mgcv                   1.8-36     2021-06-01 [1] CRAN (R 4.0.2)                         
 mime                   0.10       2021-02-13 [1] CRAN (R 4.0.2)                         
 miniUI                 0.1.1.1    2018-05-18 [1] CRAN (R 4.0.2)                         
 munsell                0.5.0      2018-06-12 [1] CRAN (R 4.0.2)                         
 nlme                   3.1-152    2021-02-04 [1] CRAN (R 4.0.5)                         
 parallelly             1.25.0     2021-04-30 [1] CRAN (R 4.0.2)                         
 patchwork              1.1.1      2020-12-17 [1] CRAN (R 4.0.2)                         
 pbapply                1.4-3      2020-08-18 [1] CRAN (R 4.0.2)                         
 pillar                 1.6.1      2021-05-16 [1] CRAN (R 4.0.2)                         
 pkgbuild               1.2.0      2020-12-15 [1] CRAN (R 4.0.2)                         
 pkgconfig              2.0.3      2019-09-22 [1] CRAN (R 4.0.2)                         
 pkgload                1.2.1      2021-04-06 [1] CRAN (R 4.0.5)                         
 plotly                 4.9.3      2021-01-10 [1] CRAN (R 4.0.2)                         
 plyr                   1.8.6      2020-03-03 [1] CRAN (R 4.0.2)                         
 png                    0.1-7      2013-12-03 [1] CRAN (R 4.0.2)                         
 polyclip               1.10-0     2019-03-14 [1] CRAN (R 4.0.2)                         
 prettyunits            1.1.1      2020-01-24 [1] CRAN (R 4.0.2)                         
 processx               3.5.2      2021-04-30 [1] CRAN (R 4.0.2)                         
 promises               1.2.0.1    2021-02-11 [1] CRAN (R 4.0.2)                         
 ps                     1.6.0      2021-02-28 [1] CRAN (R 4.0.3)                         
 purrr                  0.3.4      2020-04-17 [1] CRAN (R 4.0.2)                         
 R6                     2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                         
 RANN                   2.6.1      2019-01-08 [1] CRAN (R 4.0.2)                         
 rappdirs               0.3.3      2021-01-31 [1] CRAN (R 4.0.2)                         
 RColorBrewer           1.1-2      2014-12-07 [1] CRAN (R 4.0.2)                         
 Rcpp                   1.0.6      2021-01-15 [1] CRAN (R 4.0.2)                         
 RcppAnnoy              0.0.18     2020-12-15 [1] CRAN (R 4.0.2)                         
 RCurl                  1.98-1.3   2021-03-16 [1] CRAN (R 4.0.2)                         
 remotes                2.4.0      2021-06-02 [1] CRAN (R 4.0.2)                         
 reprex                 2.0.0      2021-04-02 [1] CRAN (R 4.0.2)                         
 reshape2               1.4.4      2020-04-09 [1] CRAN (R 4.0.2)                         
 reticulate             1.20       2021-05-03 [1] CRAN (R 4.0.2)                         
 rlang                  0.4.11     2021-04-30 [1] CRAN (R 4.0.2)                         
 rmarkdown              2.8        2021-05-07 [1] CRAN (R 4.0.5)                         
 ROCR                   1.0-11     2020-05-02 [1] CRAN (R 4.0.2)                         
 rpart                  4.1-15     2019-04-12 [1] CRAN (R 4.0.5)                         
 rprojroot              2.0.2      2020-11-15 [1] CRAN (R 4.0.2)                         
 rstudioapi             0.13       2020-11-12 [1] CRAN (R 4.0.2)                         
 Rtsne                  0.15       2018-11-10 [1] CRAN (R 4.0.2)                         
 S4Vectors              0.28.1     2020-12-09 [1] Bioconductor                           
 scales                 1.1.1      2020-05-11 [1] CRAN (R 4.0.2)                         
 scattermore            0.7        2020-11-24 [1] CRAN (R 4.0.2)                         
 sctransform            0.3.2.9006 2021-05-21 [1] Github (ChristophH/sctransform@73e2e3e)
 sessioninfo            1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                         
 Seurat               * 4.0.2.9005 2021-06-07 [1] Github (satijalab/seurat@01a8a0c)      
 SeuratData             0.2.1      2021-06-07 [1] Github (satijalab/seurat-data@b59556b) 
 SeuratObject         * 4.0.1      2021-05-08 [1] CRAN (R 4.0.2)                         
 shiny                  1.6.0      2021-01-25 [1] CRAN (R 4.0.3)                         
 SingleCellExperiment   1.12.0     2020-10-27 [1] Bioconductor                           
 spatstat.core          2.1-2      2021-04-18 [1] CRAN (R 4.0.2)                         
 spatstat.data          2.1-0      2021-03-21 [1] CRAN (R 4.0.3)                         
 spatstat.geom          2.1-0      2021-04-15 [1] CRAN (R 4.0.2)                         
 spatstat.sparse        2.0-0      2021-03-16 [1] CRAN (R 4.0.2)                         
 spatstat.utils         2.1-0      2021-03-15 [1] CRAN (R 4.0.2)                         
 stringi                1.6.2      2021-05-17 [1] CRAN (R 4.0.2)                         
 stringr                1.4.0      2019-02-10 [1] CRAN (R 4.0.2)                         
 styler                 1.4.1      2021-03-30 [1] CRAN (R 4.0.2)                         
 SummarizedExperiment   1.20.0     2020-10-27 [1] Bioconductor                           
 survival               3.2-11     2021-04-26 [1] CRAN (R 4.0.2)                         
 tensor                 1.5        2012-05-05 [1] CRAN (R 4.0.2)                         
 testthat               3.0.2      2021-02-14 [1] CRAN (R 4.0.2)                         
 tibble                 3.1.2      2021-05-16 [1] CRAN (R 4.0.2)                         
 tidyr                  1.1.3      2021-03-03 [1] CRAN (R 4.0.3)                         
 tidyselect             1.1.1      2021-04-30 [1] CRAN (R 4.0.2)                         
 tinytex                0.32       2021-05-29 [1] CRAN (R 4.0.2)                         
 usethis                2.0.1      2021-02-10 [1] CRAN (R 4.0.2)                         
 utf8                   1.2.1      2021-03-12 [1] CRAN (R 4.0.2)                         
 uwot                   0.1.10     2020-12-15 [1] CRAN (R 4.0.2)                         
 vctrs                  0.3.8      2021-04-29 [1] CRAN (R 4.0.2)                         
 viridisLite            0.4.0      2021-04-13 [1] CRAN (R 4.0.5)                         
 withr                  2.4.2      2021-04-18 [1] CRAN (R 4.0.5)                         
 xfun                   0.23       2021-05-15 [1] CRAN (R 4.0.2)                         
 xtable                 1.8-4      2019-04-21 [1] CRAN (R 4.0.2)                         
 XVector                0.30.0     2020-10-28 [1] Bioconductor                           
 yaml                   2.2.1      2020-02-01 [1] CRAN (R 4.0.2)                         
 zlibbioc               1.36.0     2020-10-28 [1] Bioconductor                           
 zoo                    1.8-9      2021-03-09 [1] CRAN (R 4.0.2)                         

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

```

</details>

**Comment by andrewwbutler** [comment]
Hi,

I believe these conversion issues should be resolved now on the `develop` branch. Please try installing (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)) and see if that fixes the problem.

**Comment by JTpath** [comment]
Awesome, thank you

**Comment by thugib** [comment]
It is working very well now. Thank you very much !
