### ISSUE TITLE
How to CreateSeuratObject out of a S4 class of ExpressionSet/ Geodata file

### ISSUE THREAD

**Issue by jazzljazz** [satijalab/seurat#4577]
Hey out there, 
I am new to Rstudio and Seurat, but I can already load in my own data and analyze it.

Now I want to reanalyze/ have a deeper look into the following data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE109816
I already learned that I can load the geodata files by:

if (!requireNamespace("BiocManager", quietly = TRUE)) + install.packages("BiocManager")
BiocManager::install(version = "3.13")
BiocManager::install("GEOquery")
expressionSet <- getGEO("GSE109816")
expressionSet <- expressionSet[[1]]

My question is now, how can I create a Seurat object out of this Expression Set object so that I can further plot tSNE plots and so on? Or do I have to load in other data btw. I think the data is already clusterd and annotated - so can I maybe directly load the UMAP etc. plots?
In the other issues where people loaded geodata into r and used seurat, people had mtx or tar files available in geodata. But for this acesscion number, I can't find any of these files, which is why I am a little bit lost.

Thank you really much in advance!

**Comment by saketkc** [comment]
You can create a counts matrix from the Supplementray files present in the GEO record:

```r
counts <- data.table::fread("https://ftp.ncbi.nlm.nih.gov/geo/series/GSE109nnn/GSE109816/suppl/GSE109816_normal_heart_umi_matrix.csv.gz")
counts_m <- as.matrix(counts, rownames = 1)
> counts_m[1:5, 1:5]
         SC_92563_0_69 SC_92563_0_17 SC_92563_0_23 SC_92563_0_12 SC_92563_0_18
TSPAN6               0             0             0             0             0
TNMD                 0             0             0             0             0
DPM1                 0             0             0             0             0
SCYL3                0             0             0             0             0
C1orf112 
> object <- CreateSeuratObject(counts=counts_m)
```

**Comment by jazzljazz** [comment]
Thank you very much for your fast and helpful reply, @saketkc ! :) And sorry for the late response!
