### ISSUE TITLE
Pairwise differential expression analysis from integrated object

### ISSUE THREAD

**Issue by geekbio** [satijalab/seurat#4579]
Hi Seurat Team,

           I have successfully integrated my dataset (A, B, and C), now I am trying to do a pairwise comparison of A vs B, B vs C, and A vs C. What is the best way to do this pairwise comparison? or Do I have to integrate two datasets at a time and then calculate the differential expression?  Please let me know. Thanks.

**Comment by jaisonj708** [comment]
Differential expression tests should generally use the `RNA` assay as input, so no pairwise integrations are necessary for DE.
