### ISSUE TITLE
Plotting multiple modules on a single spatial image

### ISSUE THREAD

**Issue by Loudon85** [satijalab/seurat#4581]
Hello good afternoon,

Firstly massive fan of the Satijalab vignettes and all the help you provide!

I was wondering whether it is possible to spatially plot two independent "gene modules" on the same spatial image.

i.e plot "module A" (genes "A", "B", "C") and "module B" (genes "E", "F", "G") via addmodulescore function and then display these on a single spatial image (as opposed to two separate images)...this would obviously allow you to spatially assess how module A and B interacted.

many thanks for your thoughts.

best wishes

Kevin

**Comment by mojaveazure** [comment]
Hi Kevin, this is not currently possible, but is on our roadmap for improvements to spatial visualizations. Unfortunatley, we don't yet have a timeline for when this will roll out to the general public
