### ISSUE TITLE
Feature and sample dependency

### ISSUE THREAD

**Issue by Toby132** [satijalab/seurat#4583]
What is the assumption with regards to feature and sample dependence? Does a feature have to be independent from another for proper analysis? Furthermore does a sample have to be independent from another sample?

**Comment by jaisonj708** [comment]
Features and samples (cells) will be dependent/correlated (e.g, measure of CD3E expression in a given cell will certainly not be independent from CD3D expression). Maybe you want to add a new feature to your assay that is a function of other features? In this case, you likely don't need to do this given that downstream analyses like PCA is already based on linear combinations of features.  Not sure if this is helpful, but feel free to open another issue describing your specific scenario.
