### ISSUE TITLE
Question: Where do different functions obtain their data

### ISSUE THREAD

**Issue by Jeff87075** [satijalab/seurat#4589]
Hi, I just wanted to ask where different functions obtain the data exactly to generate the output expression level for genes and what do these matrices in the assay component actually represent? As I understand after looking through other posts and browsing the source code a bit:
1) The functions calculating average log fold change like ```FindMarkers()``` default to ```GetAssayData()``` which obtains the ```data``` matrix in the assay component
2) But the ```PercentageFeatureSet()``` function uses the ```counts``` matrix inside the assay component
3) Also also then where do the plotting functions such as ```VlnPlot()``` obtain their expression level from? 
I'm a bit confused about what's the difference between the ```counts```, ```data```, and ```scale.data``` matrices inside the assay component, thanks a lot!

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but wiki can probably help you here.  [https://github.com/satijalab/seurat/wiki/Seurat](https://github.com/satijalab/seurat/wiki/Seurat).

Best,
Sam

**Comment by Jeff87075** [comment]
Thanks for the help @samuel-marsh! However, is there any guidance on question 3, as in what data is used in plotting functions such as ```VlnPlot()``` and ```FeaturePlot()```  to obtain the expression level?

**Comment by samuel-marsh** [comment]
Hi,

That depends on what parameters you set in those functions.  See their manual entries for more info and default parameters.  The defaults for both in this case is the `data` slot.

Best,
Sam

**Comment by torkencz** [comment]
Yes the default is the data slot for those functions.
