### ISSUE TITLE
Multiple hashtags for a singlet

### ISSUE THREAD

**Issue by typan149** [satijalab/seurat#4590]
Hello, new to seurat. My cells were labeled with 1 of 3 tissue-specific hashtag, and after combining the tissues, labeled with 2 more specific cell marker hashtags. So combination of the types- 1 tissue hashtag + 1or2 marker hashtags should still be singlet, but I think based on looking at metadata, these are considered as doublets. Is there a method to change the classification of a doublet so I can filter them out?

**Comment by torkencz** [comment]
Hi. As far as I know there is no built in method that would suit your particular data. If I understand correctly your individual hashtags would be the combination of your 1-3 tissue labels with your 1-2 cell marker labels, so you are doing a "combinatorial indexing" of sorts. In this case I would concatenate the tissue and cell labels and count those categories (e.g. T1C1 = 1 if T index 1=has hashtag reads and C index has hashtag reads etc.). Afterwards you can run the demultiplexing pipeline, without your singlets being mistakenly considered as doublets.
