### ISSUE TITLE
Error when converting Seurat objects to SingleCellExperiment objects

### ISSUE THREAD

**Issue by qiuli848** [satijalab/seurat#4593]
Hi, when I was converting Seurat objects to SingleCellExperiment objects, an error consistently occurred. I also used the pbmc3k Seurat objects as an example, the error remained. The error was reported as follows:

Error in value[[3L]](cond) : 
  invalid subscript 'e' in 'altExp(<SingleCellExperiment>, type="character", ...)':
  'RNA' not in 'altExpNames(<SingleCellExperiment>)'

```r
download.file("https://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz",
              "pbmc3k_filtered_gene_bc_matrices.tar.gz")
untar("pbmc3k_filtered_gene_bc_matrices.tar.gz")

data <- Seurat::Read10X("filtered_gene_bc_matrices/hg19/")
query_seur <- Seurat::CreateSeuratObject(data)
query_sce <- Seurat::as.SingleCellExperiment(query_seur)
```

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/4531, https://github.com/satijalab/seurat/issues/4524
