### ISSUE TITLE
selecting data points in a specific portion of the UMAP

### ISSUE THREAD

**Issue by Toby132** [satijalab/seurat#4597]
I have created a UMAP project with both PCA and UMAP reduction on the data, and then plotted the individual plots onto the plot, but how to select the points in a specific coordinate location

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I believe you are looking for function `CellSelector` which will allow you to manually select an area of the plot.

Best,
Sam

**Comment by torkencz** [comment]
Yes. CellSelector will allow you to manually select an area of the plot. Alternatively, you have to specify coordinates by which you want to select cells in your UMAP or PCA. This would be based on the dim coordinates stored in your object.

**Comment by denvercal1234GitHub** [comment]
Hi @torkencz - Thanks for your suggestion. `CellSelector` does not work for `DimPlot(setting split.by)`. You mind advising us how to pull the UMAP coordinates of a given cell?

**Comment by denvercal1234GitHub** [comment]
To get UMAP coordinates, use ```FetchData(Object, vars = c("ident", "UMAP_1", "UMAP_2")))```
