### ISSUE TITLE
BuildClusterTree using reductions other than PCA

### ISSUE THREAD

**Issue by malosreet** [satijalab/seurat#4598]
In Seurat 4.0.1, the BuildClusterTree function builds the dendrogram based on PCA if the argument "dims" is provided. It would be useful to be able to specify the name of the reduction to use (for example a reduction returned by Harmony). It should be very easy to implement and I imagine it may be useful to other users as well. 

Thanks!

**Comment by timoast** [comment]
You probably need to change the size of the plotting device

**Comment by timoast** [comment]
We have now added a `reduction` parameter to `BuildClusterTree()`, which is currently available on the develop branch. See the [website](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1) for installation instructions
