### ISSUE TITLE
More info about ValidateClusters? 

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#460]
Hello Seurat Team,

I would like to use the function ValidateClusters to see if some of the smaller clusters should be merged in my data.  As per the tutorial's advice, I have over-clustered by adjusting the resolution parameter.  However, I'm unable to find more information about this function other than the default help page, which is short.  It will be great if someone can throw some more light on how exactly this function works, i.e., validates the clusters.  I would like to understand it fully before using it.

Many thanks!

**Comment by andrewwbutler** [comment]
This is still a largely untested function but the basic idea was to compute the how connected every pair of clusters is and for clusters that are more connected than some threshold (defined by `min.connectivity` ), build a classifier to try to distinguish the two clusters. If the classification accuracy was lower than some threshold (`acc.cutoff`), we would then merge the two clusters and repeat. Probably not the best solution to the problem of overclustering but something we had been playing around with a one point to try to justify merging clusters together.

**Comment by CodeInTheSkies** [comment]
Thank you for the explanation!  So, is this function being actively worked on, to test and improve?  In other words, in a later release of Seurat, are there plans to make this a mainstream function?

Alternatively, do you have any other suggestions for finalizing a set of clusters after playing around with the resolution parameter?  I have tried a range of values from 0.2 to 4 and, of course, I'm getting significantly more number of clusters with increasing resolution.  What I am not clear about, is how to make a decision.

Any tips would be greatly appreciated!

Thanks a lot.

**Comment by andrewwbutler** [comment]
We are still thinking about ways of addressing this problem and any improvements that we do come up with will certainly be integrated into Seurat. Finalizing a set of clusters tends to be a very dataset-specific problem and often requires domain knowledge of the system you're studying. You might find the [clustree package](https://cran.r-project.org/web/packages/clustree/index.html) from @lazappi to be helpful in making this decision as well.
