### ISSUE TITLE
Error Gene Activities 

### ISSUE THREAD

**Issue by marianogabitto** [satijalab/seurat#4600]
This is the code to reproduce the error. 
rna = [genes x cell] matrix with corresponding columns and rows labels with gene names and barcodes.
atac = [peaks x cell] matrix with corresponding columns and rows labels with peaks "chr1-869583-870360" and barcodes.

rna = CreateSeuratObject(rna)
rna <- NormalizeData(rna)
rna <- FindVariableFeatures(rna)
rna <- ScaleData(rna)
rna <- RunPCA(rna)
rna <- RunUMAP(rna, dims = 1:30)

atacb = CreateChromatinAssay(counts=atac, sep=c("-", "-"))
atacc = CreateSeuratObject(atacb)
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotations) <- "UCSC"
genome(annotations) <- "hg38"
Annotation(atacc) <- annotations

atac <- RunTFIDF(atac)
atac <- FindTopFeatures(atac, min.cutoff = "q0")
atac <- RunSVD(atac)
atac <- RunUMAP(atac, reduction = "lsi", dims = 2:30, reduction.name = "umap.atac", reduction.key = "atacUMAP_")

var_rna <- FindVariableFeatures(object = rna,nfeatures = 5000)
gene.activities <- GeneActivity(atac, features = var_rna)

ERROR:
Extracting gene coordinates
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector arguments

gene.activities <- GeneActivity(atac, features = var_rna, sep=c("-", "-") )

ERROR:
Extracting gene coordinates
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector arguments

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I believe the error is due to the fact that `var_rna` is a Seurat Object and not a vector of genes as required by `features` parameter.  If you want to pull the variable features from Seurat Object you can use:
```
var_feat <- VariableFeatures(object = obj)
```

Best,
Sam

**Comment by marianogabitto** [comment]
I was missing the fragment file which is needed to compute the gene activities matrix.
