### ISSUE TITLE
installing older version of Seurat - miniconda conflict 

### ISSUE THREAD

**Issue by AmelZulji** [satijalab/seurat#4605]
Dear Seurat team, 

Seems like conda prevents installation of older seurat versions. After removing conda problem seems to be solved. However, im wondering whether there is a way to install older version of Seurat while having conda installed on machine. 

I am on macOS Catalina (v10.15.7)

Regards,
Amel

**Comment by pcallen225** [comment]
Hey Amel, I'm not part of the Seurat team but may be able to help. When installing an older version of a package you should be able to use `conda search r-seurat` which will give you all the versions of the Seurat package available as long as bioconda is in your list of channels. From there you would install the conda package using `conda install -c bioconda r-seurat=<version_of_interest>`. If that doesn't work, you may need to remove all dependencies of the r-seurat package before trying again or create a new environment and start fresh. I hope this helps!
