### ISSUE TITLE
Confirming workflow post-integration on SCTransform normalized data

### ISSUE THREAD

**Issue by anjkris** [satijalab/seurat#4610]
Sorry if this question has been asked before, but I just wanted to confirm.

The relevant vignette (https://satijalab.org/seurat/articles/integration_introduction.html) says that "Now that the datasets have been integrated, you can follow the previous steps in this vignette identify cell types and cell type-specific responses." To clarify, for SCTransformed datasets, this means that I would have to runPCA, runUMAP, FindNeighbors and FindClusters all on the "SCT" data, correct? (The vignette does not mention running FindNeighbors and FindClusters).

Secondly, if I wanted to perform any DE analysis, I would switch assay to "RNA", NormalizeData (but not ScaleData) and then use FindMarkers, etc, correct?

Thank you!

**Comment by timoast** [comment]
Post-integration, you should use the integrated assay for dimension reduction and clustering. For differential expression, you should use the RNA assay

**Comment by duocang** [comment]
> Post-integration, you should use the integrated assay for dimension reduction and clustering. For differential expression, you should use the RNA assay

Hi @timoast 

I understand `FindMarkers` is run on `RNA` assay, `data` slot.  The question is if data was processed by `SCT`, then `RNA@counts` and `RNA@data` are the same. Does it mean `FindMarkers` run on raw read count? 

I feel odd to run `FindMarkers` on raw read count.

**Comment by mauritsunkel** [comment]
@duocang Hi, I believe to NormalizeData or not to is dependent which test you use with any of the FindMarker type functions afterwards.
