### ISSUE TITLE
Removing Immunoglobulin features from single-cell RNA data

### ISSUE THREAD

**Issue by Yurany2908** [satijalab/seurat#4612]
Hi everyone, 

I am working with single-cell RNA data from plasma cells from different patient samples. I already used the workflow described in your website for individual samples and all samples together. In the last case, I observed that the distribution of each sample is driven by the predominant immunoglobulin transcript detected in each case. 

I have check different ways to assess quality metrics and remove cell-barcodes with low or high number of UMIs, high percentage of mitochondrial transcript, etc., as recommended. However, I have not found how I can mask/remove specific features (in my case immunoglobulins) from the data. 

I would like to know if you have a way to mask (or remove?) these transcripts for each case. 

Any info, comment or suggestion will be highly appreciated it. 

Yurany

**Comment by anjkris** [comment]
Not part of the Seurat team, but perhaps you can regress out immunoglobulin genes using SCTransform in the same way the Seurat tutorial mentions regressing out percent.mito?

**Comment by jaisonj708** [comment]
You can add regress out Ig gene expression in `SCTransform` or `ScaleData`. Alternatively you can just remove those features if you see that all the unwanted variation is coming from the Ig's themselves rather than any correlated features.
