### ISSUE TITLE
How would you integrate in a common embedding multiome, scRNA and scATAC -seq?

### ISSUE THREAD

**Issue by marianogabitto** [satijalab/seurat#4614]
Would you use the wknn graph as a reference and then transfer data to the graph ? How about scATAC, would you first compute activities?

**Comment by timoast** [comment]
If you want all three in a single embedding, you will need to compute gene activities for the scATAC-seq and integrate with the scRNA/multiome datasets.

**Comment by marianogabitto** [comment]
Tim,
    a follow up question. Would you run FindIntegrationAnchors on RNA/Mult/GeneAct or would you use FindTransferAnchors? Where is a link to the difference between both functions?

Thanks
