### ISSUE TITLE
Reading this file into Seurat

### ISSUE THREAD

**Issue by beginner984** [satijalab/seurat#4615]
Hello

I found a link in which there is a mat thing and I read the paper and I am certain this is single cell data for ovarian cancer

https://figshare.com/s/711d3fb2bd3288c8483a

I am wondering how I read and convert `ascites_scRNAseq_data.mat` file in this link to a Seurat object

I tried

```
> list.files()
[1] "ascites_scRNAseq_data.mat"
> 
> pbmc.data <- Read10X(data.dir = getwd())
Error in Read10X(data.dir = getwd()) : 
  Barcode file missing. Expecting barcodes.tsv.gz
> 
```

Any help please?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  `Read10X` is only for input files formatted in the output from Cell Ranger.  If this is a matrix with cells in columns and genes in rows then you can directly supply this matrix to `CreateSeuratObject`.

Best,
Sam

**Comment by jaisonj708** [comment]
The user answer is correct- you can read in the .mat file as a matrix and pass it to `CreateSeuratObject`.

**Comment by beginner984** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. `Read10X` is only for input files formatted in the output from Cell Ranger. If this is a matrix with cells in columns and genes in rows then you can directly supply this matrix to `CreateSeuratObject`.
> 
> Best,
> Sam

Thank you so much

Actually the file was not a Seurat mat file rather a Matlab file which finally I could write that as csv file but one file for raw read count per gene and one file just for row name (cells for four samples)

Because of duplicate row names, Matlab did not write that as a unified file :(

Any way this the files

https://www.dropbox.com/s/slkhspz7lgdgph6/ascites.csv?dl=0

https://www.dropbox.com/s/iq8lt7qrh7hdtq8/ascitesRownames.csv?dl=0


I tried 

```
> a=read.csv("ascites.csv")
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
> b=read.csv("ascitesRownames.csv")
> View(b)
> View(a)
> rownames(a)=b
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘logical(0)’ 
> 
```

My ultimate goal is having a Seurat object of this file 

Please may you help me in this? Because there are 4 patients so cells seems duplicates and I am not able to read the file 

The is not cell barcode file
