### ISSUE TITLE
p_val equal to 0

### ISSUE THREAD

**Issue by yang-qingxin** [satijalab/seurat#4616]
I am doing the difference analysis. When I got the results, I found some genes with the p_val equal to 0. What does that mean?
<img width="420" alt="image" src="https://user-images.githubusercontent.com/71535886/121645650-066c5e00-cac7-11eb-9527-cd3f64cc1528.png">

**Comment by jaisonj708** [comment]
This is probably due to the limited number of decimal places that can be displayed (or maybe the limited precision of floating point numbers).  Either way, the adjusted p-values are very close to 0 and indicate significance!

**Comment by yang-qingxin** [comment]
Thank you very much
