### ISSUE TITLE
editing cell cycle gene names in cc.genes $s.genes and cc.genes$g2m.genes

### ISSUE THREAD

**Issue by asub77** [satijalab/seurat#4617]
I am a new user of Seurat, with basic coding skills. I wanted to perform a regression of cell cycle genes and followed the instructions in the vignette posted at https://satijalab.org/seurat/articles/cell_cycle_vignette.html. However, the gene annotation of my scRNAseq Seurat object is in lower case and the cell cycle genes loaded with Seurat are in uppercase. Is there a way to edit these genes and create a list that matches my gene annotation syntax? Thank you.

**Comment by akstks** [comment]
Not a developer but I believe I can help. 

You probably have mouse data, so you want to change the cc.genes that are : "MCM2", "MCM7" etc. to "Mcm2", "Mcm7" etc.

Is that right?

The easiest solution I have used, is through the stringr package:
`library(stringr)` 
or 
`install.packages("stringr")` if you don't have it already 

Then: 
```
m.s.genes <- str_to_title(cc.genes.updated.2019$s.genes)
m.g2m.genes <- str_to_title(cc.genes.updated.2019$g2m.genes)
```
So for the cell cycle scoring you would use: 

`object <- CellCycleScoring(object, g2m.features = m.g2m.genes, s.features = m.s.genes)`

Keep in mind however that this only changes the capitalization of the letters, keeping only the first one as a upper case and the other ones as lower case. While that is fine in many cases, you cannot always map 1:1 human to mouse genes just by changing to lower case, but for now cell cycle scoring will probably run fine.

**Comment by jaisonj708** [comment]
You can change the case of the cell cycle scoring genes (as user suggested), or change the case of your object features by rerunning `CreateSeuratObject` on a matrix with updated rownames.  Instead of converting by changing case, you can also find mouse/human homologs using the `bioMart` package.
