### ISSUE TITLE
Merging Biological replicates and confounders

### ISSUE THREAD

**Issue by pandeyravi15** [satijalab/seurat#462]
Hi

I have 3 biological replicates from 10X genomic data. I want to do pool all of them and remove confounders like batch effect, cell cycle effect, nGene and nUMI. So I can merge three objects using merge Seurat. Then I am removing these 3 factors:
```R
ScaleData(object = control.combined, vars.to.regress = c("batchid", "nUMI", "percent.mito"))
```
So, should  I regress out cell cycle effect after this step or combined that in this step, but how? Also, where I can find S and G2M phase cell cycle genes for mouse to use here for cell cycle regression.

Thanks.

**Comment by mojaveazure** [comment]
Whether or not you should regress out cell cycle effects depends on your data. For actually regressing out cell cycle effects, please see #398

**Comment by leonfodoulian** [comment]
@mojaveazure,

It would be helpful to include in Seurat also a list of mouse cell cycle gene names. I have quickly created a list and stored it in `.rds` format (see _mouse_cell_cycle_genes.rds_), that you can find below.
[mouse_cell_cycle_genes.zip](https://github.com/satijalab/seurat/files/1984737/mouse_cell_cycle_genes.zip)

Included also is the function I used to convert human gene names to mouse gene names (see _ConvertHumanGeneListToMM.R_), as well as the script that I used to get these genes (see _get_mouse_cell_cycle_genes.R_). 

I never regressed for cell cycle, so I am not sure to what extent my gene list is valid.

Hope this helps!

Best,
Leon

**Comment by pandeyravi15** [comment]
@mojaveazure 
So, I need to first check for each datasets whether I have to regress cell cycle effects by PCA plot mentined in your cell-cycle regression vignette. If cell cycle effect is there, than in that case what would be best workflow?For e.g.,if I follow this:
1. merge all seurat object
2. scaled out batch effect, nGene, percent.mito,
3. cellscoring on scaled data
4. again scaled out cell cycle effect
5. downstream analysis

is that would be good?

Also, why only S and GEM phase cell cycle genes are considered?

**Comment by pandeyravi15** [comment]
[Cellcycleeffect_oldR1.pdf](https://github.com/satijalab/seurat/files/1984990/Cellcycleeffect_oldR1.pdf)
If PCA plot for cell cycle genes looks like attached figure, that is mean I do not need to remove cell cycle effect, right?

**Comment by mojaveazure** [comment]
We consider S- and G2M-phase genes as these are the cycling genes. If a cell isn't expressing these genes, then the cell is likely in G1-phase, or not cycling. Furthermore, by scoring on these genes, we can regress out all cell cycle signal or only the cycling/uncycling status (see `Alternate Workflow` in the cell cycle vignette). As for whether you should regress out cell cycle effects, you can run `ScaleData` on your scored object and store it in a new object. That way, you can compare the PCA plots and use the object that produces the better plot.

**Comment by pandeyravi15** [comment]
Okay, so my question is when to do this step: before filtering out cell and scaling out for batch effect, percent.mito or after that?

**Comment by mojaveazure** [comment]
Ideally, at the same time. ScaleData scales and regress data stored in the `data` slot and stores the results in the `scale.data` slot. If you'd like to do this in separate steps, you would first scale on other effects, then pass that matrix to `ScaleData` in the `data.use` argument.

```R
control.combined <- ScaleData(object = control.combined, vars.to.regress = c("batchid", "nUMI", "percent.mito"))
# Pass whatever gene list you're using, could be cc.genes$s.genes and cc.genes$g2m.genes
control.combined <- CellCycleScoring(object = control.combined, s.genes = s.genes, g2m.genes = g2m.genes)
# Could also use difference between scores. See Alternate Workflows of cell cycle scoring vignette
control.combined <- ScaleData(object = control.combined, data.use = control.combined@scale.data, vars.to.regress = c("S.Score", "G2M.Score"))
```

**Comment by pandeyravi15** [comment]
Okay, thanks.

Will you recommend to do just do homolog search for cell cycle genes for mouse as @leonfodoulian suggested or do you have genes specific for mouse

**Comment by mojaveazure** [comment]
We currently do not provide specific genes other than the ones in the `cc.genes` list. I'd suggest using @leonfodoulian's approach.

**Comment by vondoRishi** [comment]
@mojaveazure It would be nice if "data.use = control.combined@scale.data" can be highlighted in the Cell-cycle vignette itself. I have noticed this only after 3 months.
Thanks

**Comment by Sophia409** [comment]
@mojaveazure @vondoRishi  In seuratV3.0, there is no data.use parameter in ScaleData.If I didn't use `data.use = control.combined@scale.data ` in separate steps, does it has any bad effects? Or what should I do?
```
control.combined <- ScaleData(object = control.combined, vars.to.regress = c("batchid", "nUMI", "percent.mito"))
# Pass whatever gene list you're using, could be cc.genes$s.genes and cc.genes$g2m.genes
control.combined <- CellCycleScoring(object = control.combined, s.genes = s.genes, g2m.genes = g2m.genes)
# Could also use difference between scores. See Alternate Workflows of cell cycle scoring vignette
control.combined <- ScaleData(object = control.combined, vars.to.regress = c("S.Score", "G2M.Score"))
```
