### ISSUE TITLE
SCT transform integrated data and differential analysis 

### ISSUE THREAD

**Issue by lhremark** [satijalab/seurat#4620]
Hello,
I am curious about performing DE analysis after using SCT transform on integrated data set.
I have three different time-points ("conditions") that I integrated and then normalized using SCT transform. 
I then wanted to look at differential gene expression in a specific cluster comparing two of the time-points.

My understanding is that for DE it is better to use "RNA" and not the "SCT". However is it best practice to then normalize "RNA" before performing analysis.  I also saw in another post that confounders can be addressed by logistic regression test.

For example is this correct?

DefaultAssay(my.integrated) <- "RNA"
my.integrated <- NormalizeData(my.integrated, verbose = FALSE)
res <- FindMarkers(my.integrated, ident.1 = "Day5", ident.2 = "Control",group.by = 'group', subset.ident = "6",test.use = "LR")

**Comment by saketkc** [comment]
The answer depends on which slot and which test you are using for running the DE analysis. You can run DE on SCT corrected counts if the SCT model is the same across all the experiments (or they have similar median sequencing depth). You can also run DE on the data slot as in the example you provided. In most cases, the top markers will more or less be the same. Feel free to reopen with any followup questions.
