### ISSUE TITLE
'problem too large' error in IntegrateData function

### ISSUE THREAD

**Issue by sqreb** [satijalab/seurat#4621]
Hello!
We tried to use seurat to analyze a data set with a total of 1 million cells, but unfortunately we encountered a problem when merging the data. 

We first tried to use the `merge` function to merge single-cell data from different samples, but an 'problem too large' error occurred. We searched [seurat issues](https://github.com/satijalab/seurat/issues/3650) and found that you recommend the [RPCA workflow](https://satijalab.org/seurat/archive/v3.2/integration.html) to handle large data sets. So we try to use demo code 
 in RPCA workflow for data merging, but unfortunately this error still appears. 

Can you give us some help? Thank you in advance for your help!

## Code
<pre>
seruat_obj_li <- list()
for(fname in args$input){
  load(fname)
  seruat_obj_li[[fname]] <- seuratSCE
}
features <- SelectIntegrationFeatures(object.list = seruat_obj_li)
seruat_obj_li <- lapply(seruat_obj_li, FUN = function(x, features) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
}, features=features)
anchors <- FindIntegrationAnchors(
  object.list = seruat_obj_li, 
  reduction = "rpca",
  dims = 1:50)
seuratSCE <- IntegrateData(anchorset = anchors, dims = 1:50)
</pre>

## Error
<pre>
...
Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 32360 anchors
Error in .cbind2Csp(x, y) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: IntegrateData
Execution halted
</pre>

**Comment by yuhanH** [comment]
Hi, 
How many replicates (`length(seruat_obj_li)` ) do you have? 
If you have many replicates, setting a reference object will effectively save memory usage. 
You can find the detailed explanation about reference-based integration. https://satijalab.org/seurat/articles/integration_large_datasets.html
Also it seems that you still use seurat3. We highly recommend you to upgrade it to seurat4.
