### ISSUE TITLE
Lazily ScaleData on some features?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#4624]
Hello,

Our default process is to run ScaleData on the ~2000-3000 top variable genes, since this is an expensive step. Downstream steps, like DE, with often identify other features of interest not in those 2-3K. When running DoHeatmap(), the default is to pull from the scaled data slot. Are there any gotchas or problems with lazily scaling specific features (i.e. if we identify other features, ScaleData specifically on those and modify the scaled data slot). This seems like a common issue people must hit with DoHeatMap? Alternately, are people tending to move toward other heatmap packages (pheatmap, etc) that might scale data at time of generating the heatmap? 

Thanks

**Comment by yuhanH** [comment]
Hi, 
When you plot your genes of interest, you can re-run `ScaleData` for those genes and then plot heatmap. 

```
obj <- ScaleData( object = obj, features = select.features)
```
