### ISSUE TITLE
Merging multiple Seurat objects fail (Error in RowMergeMatricesList)

### ISSUE THREAD

**Issue by sh105** [satijalab/seurat#4629]
I'm trying to merge multiple Seurat (3.2.3) objects but I keep getting an error that I'm unable to understand.
However, I can merge 2 objects, but no more than 2.

Error:
```
Error in RowMergeMatricesList(mat_list = all.mat, mat_rownames = all.rownames,  :
  vector::reserve
Calls: merge ... merge.Assay -> RowMergeSparseMatrices -> RowMergeMatricesList
```

Dummy code:
```
library(Seurat)

obj1 = "/Ren_mtx0/1_preprocessing/seurat_post-qc.rds"
obj2 = "/Ren_mtx2/1_preprocessing/seurat_post-qc.rds"
obj3 = "/Ren_mtx1/1_preprocessing/seurat_post-qc.rds"

obj1 = readRDS(obj1)
obj2 = readRDS(obj2)
obj3 = readRDS(obj3)

seurat = merge(x = obj1, y = c(obj2, obj3), add.cell.ids = c("mtx0", "mtx2", "mtx1"), project = "merged")

# I have also tried
seurat = merge(x = obj1, y = list(obj2, obj3), add.cell.ids = c("mtx0", "mtx2", "mtx1"), project = "merged")
```

Description of each Seurat object:
```
An object of class Seurat
18341 features across 499802 samples within 1 assay
Active assay: RNA (18341 features, 0 variable features)

An object of class Seurat
17272 features across 462496 samples within 1 assay
Active assay: RNA (17272 features, 0 variable features)

An object of class Seurat
19153 features across 499825 samples within 1 assay
Active assay: RNA (19153 features, 0 variable features)
```

Any hint on what might be happening?

Thanks for your help.

**Comment by torkencz** [comment]
Hi, It seems to me that the problem is that your objects don't have the same set of feature to combine. Maybe updating to the latest Seurat version should be able to handle this. Alternatively, you could recreate your objects (or just an assay within the object) with a shared set of genes. You seem to be following the vignette 
https://satijalab.org/seurat/articles/merge_vignette.html well otherwise.

**Comment by maqingyue** [comment]
Has the author's problem been solved? I have the same problem as you. If I can get an answer, I will be very honored.
