### ISSUE TITLE
Increasing stringency of SCTransform clip.range

### ISSUE THREAD

**Issue by repeatpipettor** [satijalab/seurat#4631]
Hello,

Is there a limit to which we can increase the stringency of the clip ranges when running SCTransform? I initially ran it with the following parameters, and noticed that my dataset has an outlier gene with a very large residual variance when I use the default clipping range:

```
data = SCTransform(data,
                do.scale=FALSE,
                do.center=FALSE,
                variable.features.n = 5000,
                return.only.var.genes = FALSE,
                clip.range = c(-sqrt(x = ncol(x = data[["RNA"]])/30),
                               sqrt(x = ncol(x = data[["RNA"]])/30)))
```
![image](https://user-images.githubusercontent.com/65935088/122090801-2ad17e80-cdd6-11eb-980a-a4e7f7402f51.png)

I therefore tried more stringent clip ranges (based on your answers to this this previous issue ([https://github.com/satijalab/seurat/issues/2414])), increasing the denominator in +-sqrt(number.of.cells/30). However, the variance of this outlier gene does not change at all. 
![image](https://user-images.githubusercontent.com/65935088/122090865-36bd4080-cdd6-11eb-8482-8ce5a37a3119.png)

Additionally, this is the mean-variance plot for the same dataset with if I normalize the data with NormalizeData instead:
![image](https://user-images.githubusercontent.com/65935088/122090906-43419900-cdd6-11eb-89a2-e56d14dc9e11.png)

Any thoughts on whether/how I can impose more stringent clip ranges, or alternatives to increasing robustness to this outlier gene so that I can use these residuals as input to PCA, would be greatly appreciated. This outlier gene is expressed in many cells in my data, so neither a min.features nor a min.cells filter helps. 

Thanks in advance for your help. I am using Seurat_3.1.4.9019.

**Comment by saketkc** [comment]
The default clipping range is [-sqrt(n/30). sqrt(n/30)]. It might be less stringent in certain scenarios (if there are batch effects for example). You can reduce the range to [-5.5] or [-10,10], `clip.range = c(-5, 5)` or look at the min/max residuals using `min/max(GetAssayData(obj, assay="SCT", slot="data")` and decide the range based on this.
