### ISSUE TITLE
which is best option: excluding selected genes during dimension reduction or regress out the selected genes during scaling  

### ISSUE THREAD

**Issue by sameerh** [satijalab/seurat#4637]
Hi,
I am analyzing 10x single cell data. I do the general steps such as:
1. loading samples.
2. Normalising
3. scaling the data
4. dimension reduction

For the samples i am analyzing, i have a set of genes belonging to a single gene family that have varying expression between individuals. However, this gene family is also important for my study. 
My worry is that if these gene are highly varying in expression, will they drive cells expressing them to form different clusters? In such a scenario, i was thinking of two options:
1. should i regress it out while scaling?
2. exclude these gene during dimension reduction?
Which one should i follow to get more meaningful clusters?

Thanks in advance!
Sameer

**Comment by saketkc** [comment]
Hi @sameerh, If these genes are indeed variable (and as you point out also of biological interest) you would want to keep them as is. The idea behind regressing (say for example mitochondrial percentage) is to remove the variation arising from a feature that is not of biological importance. If you expect a huge difference in sequencing depths across cells, we recommend you try the [SCTransform workflow](https://satijalab.org/seurat/articles/sctransform_vignette.html).
