### ISSUE TITLE
Error: Cannot find 'subclass' in this Seurat object

### ISSUE THREAD

**Issue by dwmurray8** [satijalab/seurat#4638]
Hi everyone,

Please bear with me as I am quite new to this sort of work. Thanks in advance for your help. 

I have worked through this vignette: https://satijalab.org/seurat/v3.2/spatial_vignette.html

I am now trying to follow this workflow with my own data. I'm running into a problem while integrating single-cell data with the spatial data. This problem is perhaps somewhat similar to issue #3618. Below is my code:

```
> #Anchor-based approach enables probabilistic transfer of annotations from a reference to a query set
> anchors <- FindTransferAnchors(reference = human, query = rest, normalization.method = "SCT")
Normalizing query using reference SCT model
_Warning: Adding image data that isn't associated with any assay present
Performing PCA on the provided reference using 1820 features as input.
Projecting cell embeddings
Finding neighborhoods
Finding anchors
	Found 162 anchors_
> predictions.assay <- TransferData(anchorset = anchors, refdata = human$subclass, prediction.assay = TRUE, 
+                                   weight.reduction = rest[["pca"]], dims = 1:30)
```
_Error: Cannot find 'subclass' in this Seurat object_

Please let me know if you need more information and forgive me if I haven't formatted this post properly.

**Comment by dgroso** [comment]
Hello,

Any updates on this? Having the same issue with the "subclass" slot for a particular Seurat object I am working with. Are the cell types stored in "subclass" annotated manually? How can I add "subclass" to the meta data? Thanks in advance

**Comment by Goluvini** [comment]
Hello, 
             I am having the same issue when I am trying to integrate snATAc with snRNA there is this error of subclass not found 
> predicted.labels <- TransferData(
+     anchorset = transfer.anchors,
+     refdata = allen_rna$subclass,
+     weight.reduction = all_atac[['lsi']],
+     dims = 2:30
+ )
Error: Cannot find 'subclass' in this Seurat object
