### ISSUE TITLE
Mitochondria cutoff standard in SCTransform

### ISSUE THREAD

**Issue by sjinu37** [satijalab/seurat#4642]
Hello, 

I used mitochondria proportion cutoff as 5% for quality control. However, I noticed SCTransform use the mitochondria information, thus I'm wondering whether it is good to use mitochondria proportion cutoff standard before SCTransform or not.

Best,
Jinwoo Shin

**Comment by saketkc** [comment]
You can regress out mitochondrial content (or any other covariate) in SCTransform:

```{r}
pbmc <- PercentageFeatureSet(pbmc, pattern = "^MT-", col.name = "percent.mt")
pbmc <- SCTransform(pbmc, vars.to.regress = "percent.mt", verbose = FALSE)
```

The goal of cutoff pre-regression is to filter out outlier cells. You can retain more cells if you don't filter, though cells with high mitochondrial content might not have strong biological signal.
