### ISSUE TITLE
Gene expression data used for violin plot 

### ISSUE THREAD

**Issue by mvis1231** [satijalab/seurat#4651]
Hi, 
I used SCTransform to integrate the two samples, and I created the violin plot to see the difference in gene expression between the samples. The code was:

`VlnPlot(SCTintegrated, split.by = "sample", features = c("gene1", "gene2", "gene3"), pt.size = 0, combine = FALSE)`

The plot is for visualization, and now I was wondering if I can get the gene expression data for each sample that was used to create the violin plot. 
Is there any way for me to get the information?

Any help will be much appreciated. Thank you!

**Comment by saketkc** [comment]
You can get the data for any slots using [GetAssayData](https://rdrr.io/cran/SeuratObject/man/AssayData.html):

```{r}
normalized_data <- GetAssayData(object, assay="SCT", slot="data")
```

**Comment by mvis1231** [comment]
Thanks for the response, Saketkc!

However, how can I get the normalized data per sample? Do I need to merge the assay data with the metadata that has the sample information?
