### ISSUE TITLE
FindTransferAnchors: Invalid character indexing

### ISSUE THREAD

**Issue by myh014** [satijalab/seurat#4652]
I am new to using Seurat, and am attempting to use it to analyze a Single-Cell Dataset. I've had a number of errors popping up here and there as I adapted existing workflows to analyze my data, but this is the first that is causing serious issues that I have not been able to get around.

**The issue**
When using this line of code...
**ter.anchors <- FindTransferAnchors(reference = ref, query = ter,features = intersect(rownames(ref),rownames(ter)), dims = 1:20)**

I end up with the following error with the associated traceback...
_Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE): invalid character indexing

Traceback:

1. FindTransferAnchors(reference = ref, query = ter, features = intersect(rownames(ref), rownames(ter)), dims = 1:20)
2. DietSeurat(object = query, assays = query.assay, dimreducs = reference.reduction, features = features, scale.data = TRUE)
3. subset(x = object[[assay]], features = features.assay)
4. subset.Assay(x = object[[assay]], features = features.assay)
5. GetAssayData(object = x, slot = "counts")[features, cells, drop = FALSE]
6. GetAssayData(object = x, slot = "counts")[features, cells, drop = FALSE]
7. subCsp_ij(x, i, j, drop = drop)
8. intI(i, n = d[1], dn[[1]], give.dn = FALSE)
9. stop("invalid character indexing")_

This issue appears to have come up before, although under different contexts, and a previous solution (project.query = TRUE) did not work (likely because I am not in a situation where my query dataset is not substantially larger than my reference).

**Some background:**
My Reference is an Integrated Dataset from 6 x 10X Single-Cell Runs. My Query is a Dataset from 1 x 10X Single-Cell Run. I have already set the default assays respectively to "integrated" and "RNA".

Both have already been filtered to remove data from mouse cells, cells with excessively high mitochondrial DNA, and multiplets.

**Comment by yuhanH** [comment]
hI @myh014 
Could you post all the scripts you used and the `session_info()`?
