### ISSUE TITLE
group

### ISSUE THREAD

**Issue by zym826** [satijalab/seurat#4653]
I have a question,I want to group Seurat object by cell name. What function do I use .
My idea was to assign the names of these groups to orig.ident by referring to the last few special characters of the cell names  
But I don't know  how to do that

**Comment by saketkc** [comment]
You can define a new metadata column:

```{r}
seu_obj$mycol <- substr(Cells(seu_obj), 10, 13) # define mycol as  a group define by barcode characters in positions 10-13
Idents(seu_obk) <- 'mycol'
```
