### ISSUE TITLE
custom variable features list for data integration?

### ISSUE THREAD

**Issue by ijuric** [satijalab/seurat#4657]
Hi all,
Is it possible to define a custom variable features list for data integration?

This is the relevant code snippet I have now for data integration

sf <- SelectIntegrationFeatures(object.list = sl_integrate, nfeatures = 3000)
sl_integrate <- PrepSCTIntegration(object.list = sl_integrate, anchor.features = sf)
sl_integrate = lapply(X = sl_integrate, FUN = RunPCA, features = sf)
sample.anchors <- FindIntegrationAnchors(object.list = sl_integrate, anchor.features = sf, normalization.method = "SCT", reduction = "rpca", reference = ref_set)
sample.integrated <- IntegrateData(anchorset = sample.anchors, normalization.method = "SCT", verbose = TRUE)

Instead of SelectIntegrationFeatures I’d like to define my own list of genes and feed it in PrepSCTIntegration directly.

Long version:
I’m analyzing large bladder tumor dataset which has clearly distinct uroepithelial and immune compartments, but after clustering, clusters in immune compartment contain mixed cell populations. (for example, half of the cluster are CD8 and half are CD4 T cells). 
From previous work, we know good marker genes for different cell populations, and which are not selected among variable features, and we’re hoping that if those are used in variable features list, we might get better separation.
The idea is to ‘spike in’ the default variable features list (obtained by FindVariableFeatures function) with additional genes and check if that helps with clustering.
For some samples, we have very low number of cells in immune compartment, so splitting dataset in two compartment, then finding variable feature for each compartment and reintegrating data is challenging.

**Comment by torkencz** [comment]
Hi, what you are saying sounds good to me. You provide the integration step any pre defined set of genes via the anchor features variable.
