### ISSUE TITLE
Which slot of default assay does subset() use?

### ISSUE THREAD

**Issue by ka-lw** [satijalab/seurat#4658]
Hi All. 
I'm running a fairly standard sc-RNAseq pipeline in Seurat but I have a question about the subset() function and how it interacts with a seurat object after SCTransform. I run:

`
mice<- SCTransform(mice, verbose = FALSE)  ; 
mice<-subset (x = mice, Cd4 <= 0.3)
`

My question is - assuming that after SCTransform() the default assay is SCT - which slot in that assay does subset use? Counts, data or scale.data? This issue was touched upon in #2551, and based on a response there I think the answer may be that it uses the data slot but if anyone could shed more light that would be fantastic. 

Thanks.

```
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.4      SeuratObject_4.0.2 Seurat_4.0.3     
```

**Comment by yuhanH** [comment]
You are right. `subset` will use your default assay and data slot when you use gene expression condition. 
`subset` calls `WhichCells` function.  You can find detailed descriptions in `WhichCells`
