### ISSUE TITLE
lost dimension reduction after SCE conversion

### ISSUE THREAD

**Issue by lindsaynhayes** [satijalab/seurat#4659]
In the Seurat <-> SCE vignette (https://satijalab.org/seurat/articles/conversion_vignette.html) the dimension reduction is retained and `plotPCA` works. However, I am having trouble keeping getting the PCA mapping to transfer over to SCE for a downstream analysis. (data is SCTransform & integrated with rpca & dim reduction done on Integrated data)

UPDATE: Turns out its the same as for the UMAP

```
reducedDim(SCE, "PCA", withDimnames=TRUE) <- Seurat_Object[['pca']]@cell.embeddings
reducedDim(SCE, "UMAP", withDimnames=TRUE) <- Seurat_Object[['umap']]@cell.embeddings
```

**Comment by jamdili1** [comment]
Did you ever find out the solution? my PCA is transfer as a reducedDim but not the UMAP which I want to use for slingshot. thanks
