### ISSUE TITLE
Changing colours on VlnPlot

### ISSUE THREAD

**Issue by NGuslund** [satijalab/seurat#4668]
Hi,
 I have made a stacked VlnPlot as seen below
![image](https://user-images.githubusercontent.com/85682207/122729453-7a51f780-d279-11eb-8835-1ba392a30ab2.png)

Using this script
VlnPlot(Bcell.integrated,features=Bcellgenes, pt.size = 0, stack=T, flip=T, assay = "RNA") + NoLegend() 

However, the I want the colours to be the same vertically across the same cluster, not horizontally across the gene. So for example one colour for all of cluster 0

Thanks for your time,
Naomi

**Comment by torkencz** [comment]
Hi, in ggplot you would have to change the fill option in the aesthetics. Here I think you have to change fill.by = "feature" to fill.by = to the identity variable (might have to create a metadata column for this). Let me know if this worked.

**Comment by NGuslund** [comment]
Thank you that worked! 
![image](https://user-images.githubusercontent.com/85682207/123599069-184f4000-d7ed-11eb-94b7-e62c70c438f2.png)
VlnPlot(Bcell.integrated,features=Bcellgenes, pt.size = 0, stack=T, flip=T, assay = "RNA", fill.by = 'ident', cols = palette) + NoLegend()
