### ISSUE TITLE
Group names differ between DimPlot and ggplot_build

### ISSUE THREAD

**Issue by dputhier** [satijalab/seurat#4669]
Dear all,
I'm interested in extracting seurat color palette from an object returned by Dimplot. I looked at issue #257 which propose a solution using ggplot_build. However, when I apply this solution I end up with group labels that differ between the Seurat object and the ggplot object returned by Dimplot.  

Data can be obtained from the link below if you want to check.
https://we.tl/t-DYD5nr3KQg

		library(Seurat)
		library(dplyr)
		# Loading
		load("~/Downloads/my_obj.RData")

		# Don't have a "ident" slot.
		# Result is "Levels: 0 1 2 3 4 5 6 7 8 9"
		# So "zero-based"
		my_obj@active.ident 

		# DimPlot
		# plotting dp show groups named as 0 1 2 3 4 5 6 7 8 9
		dp <- DimPlot(my_obj, reduction = "umap")

		# Extracting group to color mapping
		g <- ggplot_build(dp)
		distinct(g$data[[1]][,c("colour","group")])

		# Here result is "one-based"
		#     colour group
		# 1  #39B600     4
		# 2  #00BF7D     5
		# 3  #F8766D     1
		# 4  #A3A500     3
		# 5  #00BFC4     6
		# 6  #00B0F6     7
		# 7  #D89000     2
		# 8  #9590FF     8
		# 9  #E76BF3     9
		# 10 #FF62BC    10

My question is whether there is any alternative to get group to color mapping ensuring that everything is properly ordered whatever the group/level names.

Best

**Comment by yuhanH** [comment]
HI, 
You can set the levels of active idents to match the color order. 
```
Idents(my_obj) <- factor( Idents(my_obj) , levels = c( "order of group") )
```

**Comment by dputhier** [comment]
Thank you for your response. However, this does not really answer the question. Here you propose a way to reorder the group levels. My question is how to extract automatically group to color mapping. Or alternatively, what is the internal rule to convert "zero-based" levels into "one-based level" which may be just adding 1 but could be problematic as we are dealing with factors...

**Comment by jaisonj708** [comment]
The group column in the object from ggplot_build refers to the (one-based) factor position, so to get the color mapping for the _n_ th ident, refer to the row with group=n
