### ISSUE TITLE
SelectIntegrationFeatures() returning error "no applicable method for 'VariableFeatures' applied to an object of class "SCTAssay""

### ISSUE THREAD

**Issue by jctac** [satijalab/seurat#4671]
Hello,

I'm working in Seurat v3.1.5, and I'm using v3.1.5 SCTransform'd objects in order to comply with the requirements of Signac's VeniceMarker().  While doing the integration workflow on eight Seurat objects, the SelectIntegrationFeatures() method returns the following error.

Error in UseMethod(generic = "VariableFeatures", object = object) : 
  no applicable method for 'VariableFeatures' applied to an object of class "SCTAssay"

The integration workflow previously worked fine under the same conditions, but I was then using much smaller Seurat objects;  the current Seurat objects are about 1.5GB each in the R environment.  Could the object size be the reason why SelectIntegrationFeatures() no longer works?

```r
all.sample.list <- list(s1, s2, s3, s4, s5, s6, s7, s8)
features <- SelectIntegrationFeatures(object.list = all.sample.list, nfeatures = 3000)
```

Thanks!

**Comment by yuhanH** [comment]
HI, 
SCTAssay is an implementation in Seurat 4, so it seems that there are some conflicts between difference versions of package. 
You would better update Seurat and SeuratObject both to the latest versions, 4.0.3 and 4.0.2. 
If the latest version still has this issue, I will reopen it.
