### ISSUE TITLE
Unable to regress out cell cycle using latent.vars in FindMarkers()

### ISSUE THREAD

**Issue by reberya** [satijalab/seurat#4672]
Hello,

First off, thank you for this great tool - it truly is peak of the field and the vignettes are wonderful!

The issue/question I'm having today deals with use of the latent.vars variable i nthe FindMarkers() function. I'm seeing significant effects of cell cycle between my 2 primary clusters of interest with most of the cells scored as G2M/S phase belonging to 1 cluster while the other cluster is a mixture of G1/G2M/S (image below). Ideally I'd like to regress out these differences in my differential expression to see what genes remain. However, when I run the below code attempting to use latent.vars to regress out the S.Score and G2M.Score I get identical output. I've tried using different methods like MAST or using latent.vars = "S.Score" but I still get identitcal output. I'm using the most recent version of Seurat as well.

Any advice, thoughts, or alternative analysis approaches would be much appreciated. Thank you!

```
# No variables regressed out
test1 <- FindMarkers(data, ident.1 = "0", ident.2 = "1", random.seed = 1, assay = 'RNA', method = 'LR')

# Cell cycle regressed out
test2 <- FindMarkers(data, ident.1 = "0", ident.2 = "1", random.seed = 1, assay = 'RNA', method = 'LR', latent.vars = c("S.Score", 'G2M.Score'))


> table(test1==test2) 
TRUE
4730

```

![image](https://user-images.githubusercontent.com/19393296/122781349-b6875700-d27d-11eb-85b8-730f4bcdeed8.png)

**Session info:**
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] UCell_1.0.0        Matrix_1.3-4       remotes_2.3.0      openxlsx_4.2.3     magrittr_2.0.1     data.table_1.14.0  stringr_1.4.0     
 [8] dplyr_1.0.6        plyr_1.8.6         SeuratObject_4.0.2 Seurat_4.0.3

**Comment by mhkowalski** [comment]
Hi, 

Can you try using the `test.use = 'LR'` argument rather than `method = 'LR' ` ?  For instance, 

`test2 <- FindMarkers(data, ident.1 = "0", ident.2 = "1", random.seed = 1, assay = 'RNA', test.use = 'LR', latent.vars = c("S.Score", 'G2M.Score'))
`

**Comment by reberya** [comment]
This solved the problem - thank you for the easy fix. I must have read the vignettes incorrectly.
