### ISSUE TITLE
reduction parameter in DimPlot

### ISSUE THREAD

**Issue by samsong57** [satijalab/seurat#4673]
Dear Seurat team,

I am using R version 4.0.0 running Seurat_4.0.1 

I am processing a scRNAseq dataset. Attempted to visualise a sample using DimPlot. The following code produces two different outputs:

``` 
DimPlot(my_data)

Dimplot(my_data, reduction = 'umap')

```

![image](https://user-images.githubusercontent.com/86247835/122786624-683d7c80-d2ac-11eb-9c19-f843a703ab0e.png)

![image](https://user-images.githubusercontent.com/86247835/122786650-6f648a80-d2ac-11eb-8f6f-a505c87100d6.png)

In both cases I get a graph with 5 clusters and the axes are labelled 'umap_1' and 'umap_2' but the layout is different. Does explicitly specifying 'umap' for reduction automatically change some umap parameters?

Thanks in advance

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  For your instance can you provide the full code that you ran prior to plotting?  Also are you able to provide reproducible example of the tissue using example dataset from SeuratData package?

Best,
Sam
