### ISSUE TITLE
Clustering by individual tissue population post integration of two datasets

### ISSUE THREAD

**Issue by das2000sidd** [satijalab/seurat#4675]
Hi Seurat Developers

Sorry if this question has been asked. Post batch correction and integration of two datasets, where cells of multiple different tissue types are present, I want to run clustering on cells of corresponding tissue types between the two datasets. Should I simply subset the integrated object to get each tissue type, scale the data and run PCA and then run clustering on it? 

Thanks so much for the clarifications.

**Comment by torkencz** [comment]
Hi, This is similar to https://github.com/satijalab/seurat/issues/2539. Yes, you should subset, scale and run PCA.

**Comment by das2000sidd** [comment]
Thank you again for sharing that link!
