### ISSUE TITLE
Seurat integration addressing different cell types

### ISSUE THREAD

**Issue by ttsunmeng** [satijalab/seurat#4679]
I am trying with Seurat integration (both CCA and rpca) on my targeted mRNA-seq (600 immune related genes). I have both DC and stromal cells as rare cell population aside from T and B cells based on both their surface marker and my FACS sorting distinguished by their sample tags. Before integration I can see them very well, but after integration they are not standing out anymore. For example, the rare population's T cell marker seems to be increased to a higher level and they become part as the T cell population in the UMAP as well. 

I understand that there is no perfect integration algorithm. I am trying to optimize my current strategy in addressing this. Could I do a subset of each cell type and then integrate on their own? Or even just do two populations separately, one with only the rare cell population without the integration, the other population with integration? Are there any good suggestions in this situation? Thanks a lot!

**Comment by jaisonj708** [comment]
You can try reference-based integration if one of your samples has all or a majority of the populations of interest, that will likely lead to better results. But yes, if all else fails you can try to merge all samples or perform a combination of merges and integrations.
