### ISSUE TITLE
To add cluster information and cell number information for selected genes

### ISSUE THREAD

**Issue by sameerh** [satijalab/seurat#4684]
Hi,
I would like to extract Genes, cluster, number of cells in cluster, number of cells expressing the gene and count from the seurat object as a dataframe. Could anyone help or suggest me some hints to acheive this?
I tried something like this 
FetchData(object, c("ident", "orig.ident" ,"nFeature_RNA", c('list of interested genes')), slot = 'count')
I would like to group_by ident and sum the count for each genes belonging to the respective cluster.

Thanks!

**Comment by torkencz** [comment]
Hi. The number of cells in the cluster can be easily counted via summary(Idents(object)).  As for counting the number of genes per cluster I would create a binary matrix based on the counts matrix and then aggregate based on cells in a cluster column wise. This does something similar: https://hbctraining.github.io/scRNA-seq_online/lessons/pseudobulk_DESeq2_scrnaseq.html. Hope this helped.
