### ISSUE TITLE
Best normalization

### ISSUE THREAD

**Issue by nsbc6** [satijalab/seurat#4685]
Hi all!

I was performing a **data integration** from three patients using the Seurat functions proposed in this tutorial: https://satijalab.org/seurat/articles/integration_rpca.html. I did it exploring SCTransform() and NormalizeData() ways. It is obvious that I see differences between both types. However, what would be the best normalization type to this aim?

Thanks in advance.

**Comment by saketkc** [comment]
We recommend SCTransform and you can find the motivation in this [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1). Though it is possible that you might arrive at similar results using log-normalization, particuarly when the sequencing depth variation is not a huge driver of differences across celltypes.
