### ISSUE TITLE
SCTransform (v. 0.3.2.9007 and v.0.3.2) not working with small TPM dataset

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4686]
I am getting the same error from https://github.com/satijalab/seurat/issues/3618 when running the default line from the SCTransform tutorial:

```
sobj <- PercentageFeatureSet(sobj, pattern = "^MT\\.", col.name = "percent.mt")
sobj <- SCTransform(sobj, vars.to.regress = "percent.mt", verbose = TRUE)
```

```
warning: solve(): system is singular; attempting approx solution
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed

14: In sqrt(1/i) : NaNs produced
15: In theta.ml(y = y, mu = fit$fitted) : iteration limit reached
16: In theta.ml(y = y, mu = fit$fitted) : iteration limit reached
17: In theta.ml(y = y, mu = fit$fitted) : iteration limit reached
18: In theta.ml(y = y, mu = fit$fitted) : iteration limit reached
19: In theta.ml(y = y, mu = fit$fitted) : iteration limit reached
20: In trigamma(th + y) : NaNs produced
21: In trigamma(th) : NaNs produced
```

I am running this on multiple datasets and the line from the tutorial works fine, so I wonder if it is because this one is TPM-transformed and very small, with only 549 cells.
 
![image](https://user-images.githubusercontent.com/62159599/123151126-c1cab600-d428-11eb-8d88-b7d348463b68.png)

I tried both downloading the developer version (`remotes::install_github("ChristophH/sctransform@develop"`) and using the `glmGamPoi `method like https://github.com/satijalab/seurat/issues/3618 suggested, and I get a different error now that I am not sure how to interpret:

```
remotes::install_github("ChristophH/sctransform@develop")
devtools::install_github("const-ae/sparseMatrixStats")
BiocManager::install("glmGamPoi")
library(glmGamPoi)
library(sctransform)
library(sparseMatrixStats)

sobj <- PercentageFeatureSet(sobj, pattern = "^MT\\.", col.name = "percent.mt")
sobj <- SCTransform(sobj, vars.to.regress = "percent.mt", verbose = TRUE, method = 'glmGamPoi')
```

```
Error in handle_design_parameter(design, data, col_data, reference_level) : 
  The model matrix:
        Intercept log_umi
BC01_02         1       6
BC01_03         1       6
BC01_04         1       6
BC01_05         1       6
BC01_06         1       6
BC01_08         1       6
seems degenerate ('matrix_rank(model_matrix) < ncol(model_matrix)'). Some columns are perfectly collinear. Did you maybe include the same coefficient twice?
```

![image](https://user-images.githubusercontent.com/62159599/123151447-153d0400-d429-11eb-84bb-2c0a685d9dd1.png)

Thank you for reading and I hope this makes sense!

**Comment by ChristophH** [comment]
It seems like all cells have the same total (looks like 1M which makes sense if it is TPM) and as a result the design matrix per gene is degenerate as shown above. 
The data has already been normalized (to TPM), so you should not use that as input to sctransform. 
You could either 
1) create raw counts by reversing the TPM-normalization assuming the lowest non-zero count per cell is one
2) use the TPM normalized counts directly without re-normalizing in Seurat (https://github.com/satijalab/seurat/issues/171)

**Comment by ksaunders73** [comment]
Hello @ChristophH ! Thank you very much for your reply! Would you happen to know how to reverse the TPM normalization? My understanding of how TPM is calculated is based on this site (https://btep.ccr.cancer.gov/question/faq/what-is-the-difference-between-rpkm-fpkm-and-tpm/ ) - assuming this is correct, I assume you would work backwards (literally starting by multiplying by the "per million" scaling factor, but I am not sure how to find that scaling factor, and if that is a valid approach that would actually reverse the TPM calculation. I am also not sure how to apply that reversal calculation to all of the columns in the matrix.

**Comment by rsatija** [comment]
You can try this particular code, but please note that this only works if the original TPMs were created using UMI data. 

umi_matrix <- apply(tpm_matrix,MARGIN = 2,FUN = function(x) x=x/sort(x[x>0])[1])

**Comment by ksaunders73** [comment]
Thank you very much for your help @rsatija !
