### ISSUE TITLE
FindMarkers: Limma for large datasets, sparse vs dense matrix as an input to the Wilcoxon test.

### ISSUE THREAD

**Issue by marlena-D4C** [satijalab/seurat#4689]
Hi

I have two questions regarding the _FindMarkers_ function. I am using R version=4.0.4 and Seurat version=4.0.3. 

First question is about the package used to calculate the Wilcoxon rank-sum test inside _FindMarkers_. I saw in _differential_expression.R_ that if the number of cells is not too large Wilcoxon is calculated using the **Limma** package. Otherwise the **Stats** package is used. I'm guessing this is done on purpose and I might be missing something but I wonder what is the exact reason for this choice? At least in the test I've done, it seems that the Limma version of Wilcoxon is often much faster and was able to accelerate computations significantly for larger datasets.  I wonder if your experience is different here or if there is another reason for choosing the Stats package? 

Second, it looks like Seurat always operates on a sparse matrix (_dgCMatrix_ in particular), even if a dense matrix is given during creation of the Seurat object. I noticed that passing a dense matrix into the Wilcoxon test (_Limma_ package) makes the calculation about twice as fast.  Is there any special reason why a sparse matrix is used in this case?

Thank you for your help and support. I look forward to hearing from you.

**Comment by saketkc** [comment]
Hi @marlena-D4C, thanks for your question. 

Your first question is answered in this [comment](https://github.com/satijalab/seurat/issues/2950#issuecomment-632769038). In short with large number of cells, limma encounters an overflow issue.

Regarding the second question, your observation is indeed correct and pertains to PR #4662, which we are looking into.
