### ISSUE TITLE
quality control

### ISSUE THREAD

**Issue by zym826** [satijalab/seurat#4691]
Hello! I have a question about quality control.I want to use housekeeping genes to quality control,but I don't know what function I can use it. My goal is that I want to use a function that can obtain the average expression of housekeeping gene in each cell, so cells with low expression levels were removed .Could you help me? Thanks!

**Comment by lzmcboy** [comment]
On Seurat website has an *Interaction tips* page, you can find a tutorial about how to compute the average expression.

``` R
# How can I calculate the average expression of all cells within a cluster?
cluster.averages <- AverageExpression(pbmc)
head(cluster.averages[["RNA"]][, 1:5])


# Return this information as a Seurat object (enables downstream plotting and analysis) First,
# replace spaces with underscores '_' so ggplot2 doesn't fail
orig.levels <- levels(pbmc)
Idents(pbmc) <- gsub(pattern = " ", replacement = "_", x = Idents(pbmc))
orig.levels <- gsub(pattern = " ", replacement = "_", x = orig.levels)
levels(pbmc) <- orig.levels
cluster.averages <- AverageExpression(pbmc, return.seurat = TRUE)
cluster.averages
```
Then you can use `subset()` function to  sampling the subset with housekeeping gene expression.

``` R
# Can I create a Seurat object based on expression of a feature or value in object metadata?
subset(pbmc, subset = MS4A1 > 1)
```

**Comment by torkencz** [comment]
Hi, AverageExpression and subset should do the trick.

**Comment by zym826** [comment]
Thank you
