### ISSUE TITLE
Accessing cell-specific modality kernel bandwidths (sigma) and K-NN

### ISSUE THREAD

**Issue by akshayMpatel** [satijalab/seurat#4694]
I need to compute the affinity, theta, between any two cells i,j.  In order to hand-code this, I need the kernel bandwidth sigmas and the 1-nn for each cell in each modality.  

How do I access this data after running FindMultiModalNeighbors()? 

Better yet, would be an available function to compute the affinity between two arbitrary cells in a given modality?.  

Many thanks

**Comment by yuhanH** [comment]
Hi, 
You can set `return.intermediate = TRUE` in the `FindMultiModalNeighbors` function. Then, all related parameters will be stored in the `Misc(object = object, slot = "modality.weight")`.

**Comment by akshayMpatel** [comment]
Dear Yuhan, 

Many thanks for the response.  I ran `return.intermediate = TRUE` in the `FindMultiModalNeighbors` function.  But `Misc(object = cbmc, slot = "modality.weight")` yielded 
```
A ModalityWeights object containing modality weights between RNA and ADT assays 
 This can be used as input to FindMultiModelNeighbors.
```
I tried 
```
Misc(cbmc, slot = "params")
Misc(cbmc, slot = "score.matrix")
```
...
objects from the ModalityWeights Class. 
and just got `NULL` as output. 

I'm sorry I'm a bit new to this, could you show me explicitly how to print out the initial non-weighted modality-specific knns and the kernel widths used in the affinity calculation?

Much appreciation

**Comment by yuhanH** [comment]
Hi, 
You can find those two sigmas by the following command:
```
model <- obj@misc$modality.weight
# sigma for PCA
model@params$sigma.list$pca
# sigma for adt PCA
model@params$sigma.list$apca
```

**Comment by akshayMpatel** [comment]
Many thanks, this works.
