### ISSUE TITLE
Bulk expression data not reproducible in single-cell dataset

### ISSUE THREAD

**Issue by aoifgri** [satijalab/seurat#4696]
Hello, I have analysed the expression of a group of genes in a bulk dataset across time-points and found it correlates with the expected expression. However when I then analysed these genes in a single-cell dataset of the same region and time-points the average expression is different than expected. Is there a way the single-cell data should be normalised or processed, outside of the standard pipeline, to more accurately reflect the bulk data expression?

**Comment by torkencz** [comment]
Hi, without knowing the biological question you are working on my primary intuition is that there is no alternate way of analyzing your single-cell data to represent the same results you have in your bulk analysis without biasing it. You might want to see if psudo-bulk results recapitulate bulk experiments as sample heterogeneity might be biasing things.
