### ISSUE TITLE
How to access initial within-modality K-NN graphs?

### ISSUE THREAD

**Issue by akshayMpatel** [satijalab/seurat#4697]
In connection with #4694...

After setting `return.intermediate = TRUE` in` FindMultiModalNeighbors`, I have found the sigmas for each modality using

`cbmc@misc$modality.weight@params$sigma.list
`
Many thanks.  

However, I can't seem to find the initial K-NN matrix ( for computation of affinity theta_modality(i,j) which requires the 1st within-modality neighbor, ie K-NN_modality,i,1  ).  I've tried 
```
> cbmc@misc$modality.weight@params$k.nn
[1] 20

> cbmc@graphs
# yields only multimodal NN graphs
```
Can you please show me how to access the desired K-NN graph?

Much appreciation,
Akshay

**Comment by yuhanH** [comment]
hi @akshayMpatel 
the initial KNN graphs are not stored. You can create them by `FindNeighbors` and set `return.neighbor = TRUE`.
For example,
```
obj <- FindNeighbors(obj, reduction = 'pca', dims = 1:30, return.neighbor = TRUE  graph.name = c('pca.nn'))
obj <- FindNeighbors(obj, reduction = 'apca', dims = 1:20, return.neighbor = TRUE,  graph.name = c('apca.nn'))

```

**Comment by akshayMpatel** [comment]
Many thanks Yuhan.

Please note this returns the cell itself as its 1st NN.  So in effect, it returns (k.param-1) NNs.
