### ISSUE TITLE
How to access theta_modality(i,j) values directly for all cells?

### ISSUE THREAD

**Issue by akshayMpatel** [satijalab/seurat#4698]
In connection with #4697 and #4694 

Many thanks, Yuhan, for your help.  

My ultimate goal is to be able to compute theta_modality(i,j) ( eg theta_rna(i,j) ) between any two cells. Are these affinities stored explicitly somewhere in the Seurat4 object?  And if so, how can I access them?

Thanks

**Comment by yuhanH** [comment]
HI, 
When you set `return.intermediate` to TRUE, all the parameters will be stored in the `misc`.
For example
```
bm <- FindMultiModalNeighbors(
  bm, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:18),
return.intermediate = TRUE
)
model <- bm@misc$modality.weight

# four kernels for RNA and ADT

model@score.matrix$within_impute_kernel$pca
model@score.matrix$within_impute_kernel$apca
model@score.matrix$cross_impute_kernel$pca
model@score.matrix$cross_impute_kernel$apca
```

**Comment by akshayMpatel** [comment]
Hi @yuhanH ,

Unfortunately it seems these are the not the thetas I’m interested in. If I’m correct, these are the thetas that are computed between a cell i and it’s jth (within-|cross-modal) nearest neighbor, ie theta(i, knn_ij). 

I’m actually interested in computing the theta between any two cells in a modality, i and j, ie theta(i,j).  

eg if I were to take element 

`model@score.matrix$within_impute_kernel$pca[i,j]`

I would get theta between i and jth knn for i within the ‘pca’ modality, instead of the theta between i and j cells in the ‘pca’ modality, which is what I want for all modalities. 

Please instruct.  

Many thanks

**Comment by yuhanH** [comment]
I see. You want to calculate kernel of all cells. There are two approaches. 
1. You can set the `k.nn` to `ncol(object - 1)` in the function `Seurat:::FindModalityWeights`.  Then it should return full nn graph. But this method may not work when the number of cells is big. 
2. You can modify the itself `Seurat:::FindModalityWeights` to meet your needs.
