### ISSUE TITLE
Feature Request : Contrastive PCA 

### ISSUE THREAD

**Issue by 1eesh** [satijalab/seurat#470]
May be interesting to try and integrate cPCA ( https://github.com/abidlabs/contrastive ) into seurat.

**Comment by satijalab** [comment]
We agree, and are fans of this work and method. It should not be too difficult to do using reticulate. We don't have a lot of bandwidth at the moment, but could help get things started. @abidlabs or @1eesh if you have any interest in contributing, let us know

**Comment by satijalab** [comment]
Closing this issue for now. If others are interested in helping to implement, please re-open
