### ISSUE TITLE
Error in .order_seqlevels(chrom_sizes[, "chrom"]) :    !anyNA(m31) is not TRUE 

### ISSUE THREAD

**Issue by JasonOSS** [satijalab/seurat#4701]
Hi, 

I am trying to re-run an analysis that was running fine last week on Seurat V4.

In this part:

Now add in the ATAC-seq data
we'll only use peaks in standard chromosomes

grange.counts <- StringToGRanges(rownames(atac_counts), sep = c(":", "-"))
grange.use <- seqnames(grange.counts) %in% standardChromosomes(grange.counts)
atac_counts <- atac_counts[as.vector(grange.use), ]
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
**seqlevelsStyle(annotations) <- 'UCSC'**
genome(annotations) <- "mm10"

There is now this error message that appears:

Error in .order_seqlevels(chrom_sizes[, "chrom"]) :    !anyNA(m31) is not TRUE 

Is it due to an update of some package or is there an explanation for this error ?

Thanks

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/687
