### ISSUE TITLE
How to get genes correlated with principal components

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4713]
Hello! 

I'm piggy-backing off of https://github.com/satijalab/seurat/issues/1311 and https://github.com/satijalab/seurat/issues/519, and wanted to find the genes correlated with the principal components. 

I tried this code, but I don't know how to resolve the error of `gene` and `x` not being the same length:

```
matrix <- GetAssayData(object = sobj)
matrix_mod<-as.matrix(matrix)
gene <- Loadings(sobj, reduction = "pca") #gets PC info
gene<-as.matrix(gene)
gene<-as.numeric(gene[,1]) #takes PC_1, for ex.
correlations<-apply(matrix_mod,1,function(x){cor.test(gene,x)})

corresults <- sapply(correlations, unlist)
write.csv(corresults, file = "PC_1correlatedgenes.csv")
```

![image](https://user-images.githubusercontent.com/62159599/124025760-7713e580-d9b6-11eb-986e-ad4ee9f0b55a.png)

Hopefully this makes sense, and thanks for reading!

**Comment by torkencz** [comment]
Hi you might need to subset your matrix to only genes that are in the PC loadings. So maybe matrix <- GetAssayData(object = sobj)[row.names(gene),] .

**Comment by ksaunders73** [comment]
Hello @torkencz ! I tried both of the following and unfortunately get the same error:


```
matrix <- GetAssayData(object = sobj)[row.names(gene),] 
#same code as in question
```

```
#same code as in question
gene <- Loadings(sobj[row.names(gene),], reduction = "pca") #gets PC info
#same code as in question
```

```
> correlations<-apply(matrix_mod,1,function(x){cor.test(gene,x)})

Error in cor.test.default(gene, x) : 
  'x' and 'y' must have the same length
Called from: cor.test.default(gene, x)
```
