### ISSUE TITLE
Visualization of genomic regions

### ISSUE THREAD

**Issue by JasonOSS** [satijalab/seurat#4715]
Hi,
Trying to analyse some sc_multiomic RNA+ATAC mouse data.
I followed the vignette for Seurat V4 and was able to plot UMAP for RNA, ATAC and WNN.

Now, I am trying to visualize genomic region using:

```
CoveragePlot(tcells, region = 'CD8A', features = 'CD8A', assay = 'ATAC', expression.assay = 'SCT', peaks = FALSE)
```

I am getting this error:

Error in names(file.to.object) <- cellmap : 
  attempt to set an attribute on NULL

Any idea on how I can solve this error ?

Thanks

**Comment by timoast** [comment]
Can you include the full code you're running and the output of `sessionInfo()`?

**Comment by JasonOSS** [comment]
Hi,

it seems the issue was related to this issue: https://github.com/satijalab/seurat/issues/4701#issue-931867508

Currently, linking sc-ATACseq analysis to the mm10 annotation does not work.
I simply linked the analysis to mm39 instead and it fixed both issues.

Thanks anyway for your help.
