### ISSUE TITLE
Mixscape - CalcPerturbSig Errors

### ISSUE THREAD

**Issue by townsk** [satijalab/seurat#4716]
Hi there, 

I've attempted to use mixscape to assign perturbation status for two separate CRISPR-based ECCITE-seq dataset and I'm running into this error in both cases. 

eccite.all <-CalcPerturbSig( eccite, assay = "RNA", slot = "data", gd.class = "MULTI_ID", nt.cell.class = "Negative", reduction = "pca", ndims = 20, split.by = "HTO_maxID", new.assay.name = "PRTB")

Where MULTI_ID indicated the guide RNA identity of the cell and HTO_maxID the protein antibody marker that distinguishes donor lines in this case.

Processing HTO2
Error in nt_mtx[, 1:ndims] : subscript out of bounds

Appreciate any help!
Thanks

**Comment by epapalexi** [comment]
Hi,

Are the your NT cells labeled as "Negative" in the "MULTI_ID" metadata column?Can you try this and let me know if it's TRUE or FALSE `any(eccite$MULTI_ID == "Negative")`? Also, did you run `RunPCA` prior to running `CalcPerturbSig` and if you did how many number of dimensions did you specify?

**Comment by townsk** [comment]
I resolved this issue, but was also wondering if there are any ways to modify the Mixscape function to work for CRISPR activation studies. The example is only for KO assignment and was just wondering. 

Thanks!
