### ISSUE TITLE
Does k.param in FindNeighbors have to match the n.neighbors in RunUMAP?

### ISSUE THREAD

**Issue by zqun1** [satijalab/seurat#4717]
Since both parameters define the number of neighboring points, is it recommended to set both parameters the same? The default values for these two parameters in FindNeighbors (20) and RunUMAP (30) are different. However, in another post, @timoast  mentioned setting these two parameters the same.  
 #1081

**Comment by timoast** [comment]
It does not have to match, but if you want to ensure that the UMAP representation and clustering results are as consistent as possible it's a good idea to use the same number of nearest neighbors when building the neighbor graph for clustering and for UMAP.
