### ISSUE TITLE
Where does ScaleData store results?

### ISSUE THREAD

**Issue by poryaparvizi** [satijalab/seurat#472]
Hello,

As I understand, In seurat package normalizations and corrections cause the change in the "object@Data" matrix. 
I have tried your tutorial: https://satijalab.org/seurat/pbmc3k_tutorial.html
However, the mentioned matrix before and after ScaleData (with vars.to.regress) is same.
Am I missing something?

Best

**Comment by mojaveazure** [comment]
Please read the [documentation for ScaleData](https://www.rdocumentation.org/packages/Seurat/versions/2.3.1/topics/ScaleData).

**Comment by poryaparvizi** [comment]
Sorry, I understand it now. However, do you recommend to use scaled values in differential expression analysis such as monocle? Because there are negative values in the scale.data.

**Comment by mojaveazure** [comment]
Please read our [FAQ](https://satijalab.org/seurat/faq), point number seven.
