### ISSUE TITLE
Vertical break lines between certain features

### ISSUE THREAD

**Issue by Tau-Data-Science** [satijalab/seurat#4720]
Is there currently a way to include vertical breaklines between certain features (in my case genes)? I plot the ten strongest genes of each of 10 clusters of cells. I want to add small white horizontal lines after each of the ten Genes to make them easily distinguishable. 

I did not find an easy way to do this and I am not proficient enough to code it myself. There was a similar issue #844 where I unfortunately did not understand the solution offered. I wasn't able to add a Group anywhere in the source code of DoHeatmap that allowed me to make these incissions with facet_grid.

Any help is apprecciated!

**Comment by k3yavi** [comment]
Hi @Tau-Data-Science ,

The function basically returns a ggplot object which you can customize. May be check if the recommendations from [here](https://stackoverflow.com/questions/9694452/how-to-place-divisions-between-facet-grid-lines) helps ?

**Comment by Tau-Data-Science** [comment]
Hi @k3yavi ,

Thanks for the suggestion. In the meantime I realized that the function returns a ggplot object. Nevertheless, I wasn't able to make breaklines between every ten (or so) genes.

**Comment by k3yavi** [comment]
Yea, it is surprisingly tricky to post process the ggplot object to draw separators in the facet_grid. In my quick search there is not an obvious way to achieve this and unfortunately we are short in cycles to explore this in details, however we are open to reviewing and merging a pull request if you are able to solve this. Thanks again for reaching out and good luck !
