### ISSUE TITLE
FindTransferAnchors error between SCT and integrated objects.

### ISSUE THREAD

**Issue by tangybat** [satijalab/seurat#4721]
Hello, I'm trying to transfer labels from an integrated dataset to an SCT normalized dataset. Because the reference dataset is a collection of public datasets, it is a very large file (48Gb) so I am using UCLA's Hoffman2 Cluster node network to compute the data. Seurat version is 4.0.3 and R version is 4.0.2. 

```r
anchors <- FindTransferAnchors(reference = lungs.integrated, query = seuratObject, normalization.method = "SCT", recompute.residuals = T, dims = 1:30, reference.assay="integrated", query.assay="SCT",  features=rownames(seuratObject[["SCT"]]))

Error in slot(object = reference[[reference.assay]], name = "SCTModel.list") : no slot of name "SCTModel.list" for this object of class "Assay"
Calls: FindTransferAnchors -> ValidateParams_FindTransferAnchors -> slot
Execution halted
```

Any help is appreciated. Thank you!

**Comment by yuhanH** [comment]
It seems that your reference object, `lungs.integrated`, doesn't have the SCT model stored. 
Could you have a check if  `lungs.integrated[['SCT']]@SCTModel.list` has a SCT model?
If not, you can either re-run the integration for your lungs.integrated, or just set `recompute.residuals = FALSE` in `FindTransferAnchors`.
