### ISSUE TITLE
Why is a highly uniquely expressed gene not being detected as significant marker? Error in FindAllMarkers?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4726]
### Discussed in https://github.com/satijalab/seurat/discussions/4706

<div type='discussions-op-text'>

<sup>Originally posted by **denvercal1234GitHub** June 30, 2021</sup>
Hi there, 

When I plotted a gene on RNA Assay, it is evident that this gene is highly expressed, but it was not being identified as a significant marker for that cluster using wilcox test in FindAllMarkers().

Does it mean the choice of wilcox test for DEG of my data (SCTransformed-ed) is not ideal? 

Thank you for your help!

<img width="610" alt="Screen Shot 2021-06-30 at 12 50 00 AM" src="https://user-images.githubusercontent.com/62179082/123881665-1b594600-d93d-11eb-94f0-37b03e94b077.png">
</div>

**Comment by saketkc** [comment]
Being discussed in the discussion linked.
