### ISSUE TITLE
What is log counts in as.SingleCellExperiment

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#4727]
After converting the seurat object to singelcellexpeiment format 
```
pbmc.sce <- as.SingleCellExperiment(pbmc)
assayNames(pbmc.sce)
```
[1] "counts"    "logcounts"

Logcounts in the assay is it 
1) counts slot in the SCT? or 
2) data slot in the SCT ?

secondly while converting the seuratobject to see should we need to change the defaultassay to 'RNA' ?

**Comment by torkencz** [comment]
Hi, as.SingleCellExperiment should be able to handle multiple assay conversion so setting DefaultAssay should not matter. Generally logcounts should be the data slot.
