### ISSUE TITLE
mitochondrial mapping percentage error

### ISSUE THREAD

**Issue by shawez** [satijalab/seurat#4728]
Hi, 
I  want to remove mitochondrial gene from public data availabl ein TSV format (GSE16555). 
I tried to store mitochondrial percentage in object meta data using the follwoing code:

**p007t <- read.table("GSM5075660_p007t.tsv.gz",  sep = '\t', header = TRUE, row.names = 1)
colnames(p007t) <- gsub(".","_", colnames(p007t), fixed = TRUE)
seuratData <- CreateSeuratObject(counts = p007t , min.cells = 3, min.features = 300)
seuratData <- PercentageFeatureSet(seuratData, pattern = "^MT-", col.name = "percent.mt")
mt <- as.data.frame(seuratData@meta.data)**

It added one column to my metadata but all the values are Zero.
I was wondering if it is not possible to calculate mitochondrial percentage from TSV format  ?

Any idea?

thanks
Shawez

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the dev team but hopefully can be helpful.  If the percentage is all zeros the most likely explanation is that the mitochondrial genes matching the pattern you provided are not present.  

What is the result if you run the following code:
`grep(pattern = "^MT-", x = rownames(seuratData), value = TRUE)`

Best,
Sam

**Comment by shawez** [comment]
Hi Sam,

Thanks for your help. 

Outcome is: 
**> grep(pattern = "^MT-", x = rownames(seuratData), value = TRUE)
character(0)**

It means mitochondrial genes % calculation is not possible ?

Actually I need to merge this data to other datasets and then calculate mitochondrial genes % but now the merged data also showing only Zero % due to this single data.

Any suggestions?

thanks
Shawez

**Comment by samuel-marsh** [comment]
Hi Shawez,

So yes what this means is that there are no genes matching the pattern you supplied in your dataset.  It is possible the original authors removed them.  You may also want to manually examine the dataset in case the genes are annotated with different pattern for some reason.

How are you merging your single cell data?  This should not effect the calculation of other mitochondrial gene % from other datasets where the genes are present as long as all genes are maintained during the merge.

Best,
Sam

**Comment by shawez** [comment]
Hi Sam,

I am simply using _merge_ function from R.
for example:
 d <- merge(dataMatrix1, dataMatrix2, by= "Feature")

I also checked before merging the datasets:

**> grep(pattern = "^MT-", x = rownames(seuratData1), value = TRUE)
 [1] "MT-ND3"  "MT-ND4L" "MT-ND4"  "MT-TH"   "MT-TS2"  "MT-ND5"  "MT-ND6"  "MT-TE"   "MT-CYB"  "MT-TT"   "MT-TP"   "MT-RNR2"
[13] "MT-TL1"  "MT-ND1"  "MT-TI"   "MT-TQ"   "MT-TM"   "MT-ND2"  "MT-TW"   "MT-TN"   "MT-TC"   "MT-TF"   "MT-TY"   "MT-CO1" 
[25] "MT-RNR1" "MT-TS1"  "MT-TD"   "MT-CO2"  "MT-ATP8" "MT-ATP6" "MT-CO3"**

**> grep(pattern = "^MT-", x = rownames(seuratData2), value = TRUE)
character(0)**

And for the merged data:
**> grep(pattern = "^MT-", x = rownames(seuratObject), value = TRUE) 
character(0)**

I lost over 5000 genes after merging the datasets.

**> dim(dataMatrix1)**
[1] 17405   933
**> dim(dataMatrix2)**
[1] 17972  2045
**> dim(d)**
[1] 12707  2976

Maybe I lost all the mitochondrial genes ?
This is the only possibility I see now. 

what do you think?
Thank you.

Best,
Shawez

**Comment by samuel-marsh** [comment]
Hi Shawez,

So the default behavior of `merge` as detailed in function description is:
```
all.x
logical; if TRUE, then extra rows will be added to the output, one for each row in x that has
no matching row in y.  These rows will have NAs in those columns that are usually
filled with values from y.  The default is FALSE, so that only rows with data from
both x and y are included in the output.
```

That is why you are "losing" genes.  I would suggest either modifying parameters of merge on the dataframes or you could merge Seurat Objects.

Best,
Sam

**Comment by shawez** [comment]
Hi Sam,

As you suggested, Merging Seurat Objects worked for me. 

> seuratData.combined <- merge(seuratData1, y = seuratData2, add.cell.ids = c("d1", "d2"), project = "PBMC12K")
> grep(pattern = "^MT-", x = rownames(seuratData.combined), value = TRUE)
 [1] "MT-ND3"  "MT-ND4L" "MT-ND4"  "MT-TH"   "MT-TS2"  "MT-ND5"  "MT-ND6"  "MT-TE"   "MT-CYB"  "MT-TT"   "MT-TP"   "MT-RNR2"
[13] "MT-TL1"  "MT-ND1"  "MT-TI"   "MT-TQ"   "MT-TM"   "MT-ND2"  "MT-TW"   "MT-TN"   "MT-TC"   "MT-TF"   "MT-TY"   "MT-CO1" 
[25] "MT-RNR1" "MT-TS1"  "MT-TD"   "MT-CO2"  "MT-ATP8" "MT-ATP6" "MT-CO3"

Thank you very much for your help. 

Best
Shawez

**Comment by samuel-marsh** [comment]
Hi Shawez,

Glad to help.  As noted in your previous reply only one of the 3 datasets has the mitochondrial genes included so all values will still be zero for the other datasets unless data is reprocessed.

Best,
Sam

**Comment by shawez** [comment]
Hi Sam,

True, One data is still missing mitochondrial genes and I need to get raw fastq files to mapp again.
Now at least I can further go ahead with the available options like Merging Seurat Objects before I get it.
Thanks again for your help.
Best,

Shawez
