### ISSUE TITLE
Removing trailing in 10x multiome data

### ISSUE THREAD

**Issue by vinothkr11** [satijalab/seurat#4732]
When we work with 10x single modal data and use Read10x, a feature called "strip. suffix" removes the trailing -1 in the cell barcodes. Unfortunately, the Read10x_h5 that is used to input multiome data doesn't come with this feature. So what is the best way to remove the trailing -1 in the cell barcodes for this 10x multiome data?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So you should just be able to use `gsub` and replace manually after reading the H5 file into R.

Believe that something like this should be fine (Note there may be hidden issue here I'm missing as to why this is not a parameter included in the `Read10X_h5` function itself.)
```
mat <- Read10X_h5("~/Downloads/pbmc_unsorted_3k_filtered_feature_bc_matrix.h5")

# gsub to replace any instances of "-ANYDIGIT" with nothing.
mat[[1]]@Dimnames[[2]] <- gsub(pattern = "\\-[[:digit:]]", replacement = "", x = mat[[1]]@Dimnames[[2]])
mat[[2]]@Dimnames[[2]] <- gsub(pattern = "\\-[[:digit:]]", replacement = "", x = mat[[2]]@Dimnames[[2]])
```

Best,
Sam

**Comment by torkencz** [comment]
Yes, gsub should be able to fix your issue. We can look into adding a parameter to the function itself as well.
