### ISSUE TITLE
Normalizing each sample prior to HTOdemux or merge and normalize?

### ISSUE THREAD

**Issue by sdr08** [satijalab/seurat#4733]
Hi,

I was given two samples, WT and KO, each with 2 hashtag samples and one without a hashtag (not to lose precious sample I'm told). My question is, should I be normalizing each sample separately and run HTOdemux or merge the two samples, normalize and run HTOdemux? I plan to use two different positive.quantile values, 0.99 to identify singlets and a lower threshold to identify the negative population.

Thank you

**Comment by yuhanH** [comment]
I think it may not have a big effect. But the safest way is to run HTOdemux separately. After demultiplexing, you then merge those samples.
