### ISSUE TITLE
Dose it have any effect on RunoptimizeALS if the scale.data have negative values？

### ISSUE THREAD

**Issue by WellJoea** [satijalab/seurat#4735]
What are the effects on RunoptimizeALS If the scale.data with negative values are scaled by ScaleData(do.center = FALSE) after CCA batch?
When using liger to integrate multi-species, the batches in each species cannot be removed.
So, if CCA is used for correcting the batches in each species among samples and then use the CCA matrix with negative value as the input of optimizeALS, Is there any effect on final result？

**Comment by rsatija** [comment]
Liger uses non-negative matrix factorization, so you cannot use scaled values (which contain negative values) as input to this procedure.
