### ISSUE TITLE
Error with RunPCA 

### ISSUE THREAD

**Issue by zhli12** [satijalab/seurat#4736]
Hi,

When I'm trying to use RunPCA using a set of pre-selected genes using the line `obj= RunPCA(obj, features =features)`,

after the warning
```
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
```
I received the error

```
Error in pca.results$u %*% diag(pca.results$d) : 
  non-conformable arguments
```

I searched online but didn't find any similar issues online. The features I use come from my previous analysis rather than the `FindVariableFeatures` function; however, I'm not sure how this is related to the error above. Any help would be really appreciated!

**Comment by liuxl18-hku** [comment]
How many features can be found in ur obj

```r
intersect(rownames(obj), features)
```

It seems that you have too small number of features to run partial SVD.

bless~

**Comment by zhli12** [comment]
All features I used are present in the rownames of the Seurat object `obj`, but a few are lowly expressed

> How many features can be found in ur obj
> 
> ```r
> intersect(rownames(obj), features)
> ```
> 
> It seems that you have too small number of features to run partial SVD.
> 
> bless~

**Comment by liuxl18-hku** [comment]
My understanding is seurat use scaled expression of features provided to do PCA, a more valid check would be:

```r
intersect(
    features,
    rownames(GetAssayData(obj, slot = "scale.data"))
)
```

**Comment by zhli12** [comment]
> ```r
> intersect(
>     features,
>     rownames(GetAssayData(obj, slot = "scale.data"))
> )
> ```

Thank you! Using the "scale.data", there are only two shared features. Would scaling automatically reduce the size of the expression matrix in Seurat?

**Comment by liuxl18-hku** [comment]
Yes @zhli12 , by default they only take [variable genes](https://www.rdocumentation.org/packages/Seurat/versions/4.0.3/topics/ScaleData), but you can provide customized genes by setting `features` param.

**Comment by yuhanH** [comment]
Hi @zhli12 
Could you post the scripts of steps before RunPCA? How many cells and features in your `scale.data` slot?

**Comment by zhli12** [comment]
> Hi @zhli12
> Could you post the scripts of steps before RunPCA? How many cells and features in your `scale.data` slot?

I'm using data from elsewhere which is already normalized and scaled. I solved the problem by re-scaling the data after forcing the features I need to be variable features. Thank you!
