### ISSUE TITLE
Assays  after using  as.SingleCellExperiment

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#4737]
As per the #4727 the reply for this issue seurat will be able to handle multiple assay but after conversation I could only see 2 assay in sce while original seurat object has 5 (shown below) .

Secondly I hope counts slot after conversion (sce) is the raw count data ?
```
pbmc@assays
$RNA
Assay data with 20330 features for 80660 cells
First 10 features:
 RP11-34P13.7, FO538757.2, AP006222.2, RP4-669L17.10, RP5-857K21.4, RP11-206L10.9, LINC00115, FAM41C,
SAMD11, NOC2L 

$SCT
SCTAssay data with 19230 features for 80660 cells, and 16 SCTModel(s) 
First 10 features:
 RP11-34P13.7, FO538757.2, AP006222.2, RP4-669L17.10, RP5-857K21.4, RP11-206L10.9, LINC00115, FAM41C,
SAMD11, NOC2L 

$prediction.score.celltype.l1
Assay data with 8 features for 80660 cells
First 8 features:
 Mono, CD4 T, CD8 T, NK, B, other T, other, DC 

$prediction.score.celltype.l2
Assay data with 31 features for 80660 cells
First 10 features:
 CD14 Mono, CD4 TCM, CD8 Naive, NK, CD8 TEM, CD16 Mono, B intermediate, CD4 Naive, CD4 CTL, B naive 

$predicted_ADT
Assay data with 228 features for 80660 cells
First 10 features:
 CD39, Rat-IgG1-1, CD107a, CD62P, TCR-2, CD30, CD31, CD34, CD35, CD36 
```
**converting the seurat object to singelcellexpeiment format**
```
pbmc.sce <- as.SingleCellExperiment(pbmc)
assayNames(pbmc.sce)
```
[1] "counts" "logcounts"

**Comment by torkencz** [comment]
Hi, counts contain the raw counts slot and logcounts the data slot of your assay. You assays should be stored under AlternateExperiments in your sce object. We will be adding to this function to handle sct assays better. Let me know if that clarified things for you and I can reopen.
