### ISSUE TITLE
Differential expression analysis using 'FindMarkers' on datasets containing treatment and replicate groups

### ISSUE THREAD

**Issue by deepakramanujam** [satijalab/seurat#4738]
I am analysing a large dataset containing several different treatment groups and replicate groups. Is there a way to also include a second factor (here, replicates) in the model for DE analysis?

**Comment by jaisonj708** [comment]
You can specify these metadata with the `latent.vars` parameter, but note that only some DE methods are based on statistical models (the default, wilcoxon, is  nonparametric).  You might want to look into the poisson or MAST options.
