### ISSUE TITLE
How to plot module score onto a UMAP still colored by cluster

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4740]
Hello! 

This may be a weird question, but is there a way to add an additional color variable denoting the module score, to a UMAP that's already colored by cluster?

So like this beautiful work of art:

![image](https://user-images.githubusercontent.com/62159599/124955647-d25c5e00-dfdc-11eb-9b56-b57c2d66acd4.png)

Here's a module score example from this same Chung paper:

```
tnbclist <- list(c("FABP7", "TSPAN8", "CYP4Z1", "HOXA10", "CLDN1",
                   "TMSB15A", "C10ORF10", "TRPV6", "HOXA9", "ATP13A4",
                   "GLYATL2", "RP11-48O20.4", "DYRK3", "MUCL1", "ID4", "FGFR2",
                   "SHOX2", "Z83851.1", "CD82", "COL6A1", "KRT23", "GCHFR",
                   "PRICKLE1", "GCNT2", "KHDRBS3", "SIPA1L2", "LMO4", "TFAP2B",
                   "SLC43A3", "FURIN", "ELF5", "C1ORF116", "ADD3", "EFNA3",
                   "EFCAB4A", "LTF", "LRRC31", "ARL4C", "GPNMB", "VIM", 
                   "SDR16C5", "RHOV", "PXDC1", "MALL", "YAP1", "A2ML1",
                   "RP1-257A7.5", "RP11-353N4.6", "ZBTB18", "CTD-2314B22.3", "GALNT3",
                   "BCL11A", "CXADR", "SSFA2", "ADM", "GUCY1A3", "GSTP1",
                   "ADCK3", "SLC25A37", "SFRP1", "PRNP", "DEGS1", "RP11-110G21.2",
                   "AL589743.1", "ATF3", "SIVA1", "TACSTD2", "HEBP2"))
sobj <- AddModuleScore(object = sobj, features = tnbclist, name = "TNBC_List") 
FeaturePlot(object = sobj, features = "TNBC_List1", min.cutoff = 0) 
```

I've tried this:

`DimPlot(sobj, reduction = "umap", group.by = c("idents", "TNBC_List1"))`

but then it would have way too many colors (as it would try to plot each value of the module score `TNBC_List1`. 

The closest I can get is this, but there are no cluster border outlines so it's hard to tell exactly what cluster is which and how far the clusters extend:

` moduleplot <- FeaturePlot(object = sobj, features = "TNBC_List1", order = TRUE, min.cutoff = 0, label = TRUE, repel = TRUE)`

![image](https://user-images.githubusercontent.com/62159599/124956088-40088a00-dfdd-11eb-94ef-e5e98bf18faa.png)

I believe the answer lies in appending a color variable through ggplot2, like a (`moduleplot + ggplot(color = "TNBC_List1")`) but I don't know exactly how to do that (as you seem to have to add colors into the plot itself rather than something you can add after the plot has been made, if that makes sense.

Thank you for reading!

**Comment by timoast** [comment]
The points can only be colored by one thing, so I don't think what your asking is really possible (color by cluster and module score?)

One option is a feature plot with labels shown, as you showed. Another option is a violin plot, or separate plots side-by-side

**Comment by ksaunders73** [comment]
Hello @timoast ! Do you think there is a way to add an outline of the clusters within FeaturePlot() through ggplot2 or do you think that is also something not really possible?
