### ISSUE TITLE
Subset cells by ADT expression

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [satijalab/seurat#4741]
Hey,

I am using the subset function if I want to make an object with e.g cells that express a specific gene as follows:

`subset(x = pbmc, subset = Klrk1> 1)`
However I would like to subst based the expression of an ADT marker so whenever I try the following I get an error.

```
DefaultAssay(seu_fin)<-"Protein"
NKG2Dprot<-subset(x = seu_fin, subset = NKG2D-TotalSeqC > 1) 
Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells,  : 
  None of the requested variables were found: 
```
I also tried the same with quotes ("NKG2D-TotalSeqC") but I got the same error

Is there a way to subset my cells according to ADT markers?

Thanks a lot

**Comment by samuel-marsh** [comment]
Hi Erin,

Not member of dev team but hopefully can be helpful. The error seems to be related to not finding the variable in the object. What is the result if you run the following code:
`grep(pattern = "NKG2D-TotalSeqC", x = rownames(ALL_CELLS[["Protein"]]), value = TRUE)`

Best,
Sam

**Comment by christoforos-dimitropoulos** [comment]
Running the code you suggested: 

```
> grep(pattern = "NKG2D-TotalSeqC", x = rownames(seu_fin[["Protein"]]), value = TRUE)
 [1] "NKG2D-TotalSeqC"
```

**Comment by samuel-marsh** [comment]
Hi,

So the issue is actually due to the "-" in the name of protein you are trying to subset on.

The solution is to use backticks and the assay key in order to subset (see https://github.com/satijalab/seurat/issues/2463#issuecomment-570100398).  You don't even need to switch the default assay either.

Here is reproducible validation of the solution using SeuratData bmcite dataset.

```
bmcite_obj <- bmcite.SeuratData::bmcite

Assays(bmcite_obj)
[1] "RNA" "ADT"

bmcite_obj_sub <- subset(x = bmcite_obj, subset = CD127-IL7Ra > 1.5)
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found: 

# Now for the solution:
bmcite_obj_sub <- subset(x = bmcite_obj, subset = `adt_CD127-IL7Ra` > 1.5)
```

Best,
Sam
