### ISSUE TITLE
How to plot UMAP of subclusters after `FindSubClusters`?

### ISSUE THREAD

**Issue by strawberry789** [satijalab/seurat#4745]
I ran `FindSubClusters` and was able to find the markers for each subcluster, but how to plot the UMAP of the subclusters?

`epi <- FindSubCluster(
    object = seurat_integrated0.05,
    cluster = "cluster0",
    graph.name = "test",
    subcluster.name = "0",
    resolution = 0.2,
    algorithm = 1
)`

However, when I plot the UMAP, it gives the original cluster UMAP, not the subclusters:

`DimPlot(epi, group.by = c("sample", "ident"))`

Thanks.

**Comment by strawberry789** [comment]
I was able to plot the UMAP, but I'm having trouble plotting the featureplot.

How can I label the subclusters, and not only the clusters in the featureplot?

Thanks.

**Comment by strawberry789** [comment]
And I cannot rename the subclusters with `RenameIdents`

**Comment by strawberry789** [comment]
sorry for the series of comments, but I also encounter another plotting issue:

How can I plot a `DoHeatmap` with all subclusters using this code:

`DefaultAssay(epi) <- "SCT"
top10 <- epi.upmarkers %>%
    top_n(n = 10, wt = avg_log2FC)
DoHeatmap(epi, features = top10$gene) `

where epi.upmarkers represent the markers for all subclusters, as only the markers for each subcluster could be determined by:

`epi.upmarkers <- FindMarkers(epi, ident.1 = "0", group.by = 'group', subset.ident = "subset")`

**Comment by yuhanH** [comment]
i think most of your questions can be solved by changing the default `Idents`. You can change sub.cluster to the default Idents and all those functions will be linked to sub.cluster. 
```
Idents(obj) <- "sub.cluster"
```
