### ISSUE TITLE
Data Structure 

### ISSUE THREAD

**Issue by Leob44** [satijalab/seurat#4747]
Hello, 

I have a question regarding data structure in Seurat found in the pbmc tutorial. I was wondering what was contained in the vector x called: "pbmc@assays[["RNA"]]@counts@x" ?

Thanks 
Leo

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I'm not sure what part of the vignette you are referring to but the counts slot in Seurat object is a dgCMatrix matrix.  For more on how dgCMatrix data is stored and what components of dgCMatrix are I suggest this blog post: https://www.r-bloggers.com/2020/03/what-is-a-dgcmatrix-object-made-of-sparse-matrix-format-in-r/.  For more on Seurat object structure I suggest checking out the github wiki: https://github.com/satijalab/seurat/wiki.

Best,
Sam
