### ISSUE TITLE
Help with SetIdents

### ISSUE THREAD

**Issue by sistia01** [satijalab/seurat#4749]
I am working on correcting a function that (I believe) used a previous version of Seurat. 

DEAnalysis<-function(scdata,id,path){
  exprObj<-CreateSeuratObject(raw.data=as.data.frame(scdata), project = "DE")
  exprObj2<-SetIdent(exprObj,ident.use=as.vector(id))
  for (i in unique(id)){
    de_group <- FindMarkers(object=exprObj2, ident.1 = i, ident.2 = NULL, 
                            only.pos = TRUE, test.use = "bimod")
  }
}

I am unable to correct the SetIdent function. I know that it was changed to Idents(object = object) <- "new.idents" but this is not working for me because I am using "id" as the labels which does not seem to be possible with the changes in the function? Is there another way that I could correct this function?

This is the error that I am getting: Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: CycISC

More information: These are the levels for exprObj: [1] "CycISC"    "NonCycISC" "TA"        "Goblet"    "Paneth"    "Ent"       "PreEnt"   [8] "Tuft"      "EE"

**Comment by k3yavi** [comment]
Hi @sistia01 ,

Thanks for reaching out to us. I think you can skip setting the `Idents` all together and just provide `group.by="id"` in the FindMarker function, if "id" is in the SeuratObject.
