### ISSUE TITLE
Checking batch effect after integration

### ISSUE THREAD

**Issue by mvis1231** [satijalab/seurat#4750]
Hi 

I integrated the five datasets that were individually SCTransformed.

I understand that the integration removed some degree of batch effects between the datasets, but I wanted to double check if there are any remaining batch effects.

Is there a way to check the batch effects other than using "DimPlot" with group.by? For example, box plot, numeric table, etc.
I am using DimPlot but I need more methods to show/explain whether or not there are batch effects after the integration.

Any help will be much appreciated. Thank you.

**Comment by yuhanH** [comment]
You can check local inverse Simpson’s Index (LISI) among the neighbors in the batch corrected space. Basically check if the batches are mixed well within the local neighborhood.  
Harmony uses this metric to measure the batch effect: https://www-nature-com.proxy.library.nyu.edu/articles/s41592-019-0619-0
