### ISSUE TITLE
VlnPlot split

### ISSUE THREAD

**Issue by alisik33** [satijalab/seurat#4751]
Good morning, this is my first question in github.
I'm generating VlnPlots in Seurat 3, splitting 2 groups. My previous plots were split side-by-side (not within the same violin),
I need to do the same version to add more graphs and keep them consistent. 
When I'm trying to restore the old behaviour of a single split violin by split.plot = TRUE, I get an error message (below).
How can I fix it?

Error in VlnPlot(WT.only.2, c("Gpr34"), split.by = "treatment", split.plot = TRUE, group.by = "cell_names_broad",  : 
  unused argument (split.plot = TRUE).

**Comment by k3yavi** [comment]
Can you share the session_info of your environment ? It looks like you are using older version of Seurat, hard to say.

**Comment by alisik33** [comment]
> Can you share the session_info of your environment ? It looks like you are using older version of Seurat, hard to say.

I'm currently using: (“Seurat”, version = “3.1.4”) instead of Seurat 4.0.

**Comment by mojaveazure** [comment]
The `split.plot` argument was introduced in Seurat v3.2.0; you'll need to upgrade your version of Seurat to enable this functionality
