### ISSUE TITLE
WNN and Spatial Transcriptomics

### ISSUE THREAD

**Issue by lima1** [satijalab/seurat#4754]
Hi,

in your Cell WNN paper, you mention in the Discussion that spatial coordinates could be used as well. Is this something you already did and recommend under some circumstances over the default workflow in the spatial vignette? Sorry if I missed a discussion about this.

Thanks,
Markus

**Comment by yuhanH** [comment]
Hi @lima1 
When the spatial information and transcription have general agreement information, you can apply the WNN on it. 
If those two source of information have many conflicts, it is hard to apply WNN method.
