### ISSUE TITLE
How to integrate my data

### ISSUE THREAD

**Issue by Leob44** [satijalab/seurat#4757]
Hello dear bioinformaticians

I have a question regarding my scRNAseq dataseq : 
Ok so I have a dataset divided into two assays: one classical scRNAseq (7000 cells 30000 markers ) and one antibody capture assay in which we used specific antibody tag for each individual (4 different individuals). 

How can I split the data in 4, one for each individual in order to test for diffferences between them?

**Comment by k3yavi** [comment]
Hi @Leob44 ,

Thanks for reaching out. Please check [this](https://satijalab.org/seurat/archive/v3.1/hashing_vignette.html) vignette for more information,
