### ISSUE TITLE
Resolution parameter meaning and effects

### ISSUE THREAD

**Issue by asmagen** [satijalab/seurat#476]
Hello

I was wondering how does the resolution parameter affect the phenograph algorithm? What does it do? I don't see this parameter in the original implementation so I'm not sure.

Thanks in advance

**Comment by andrewwbutler** [comment]
Hi,

The default clustering algorithm is the Louvain algorithm. You can read more about it in [_Blondel et al, 2008_](https://arxiv.org/abs/0803.0476). In general, a higher value of resolution will give you more clusters.

**Comment by DiracZhu1998** [comment]
Hi there, 
The parameters setting is “reasonable” but arbitrary in scRNA-seq workflow. 
Top PCs capture the dominant factors of heterogeneity in the data set, in other words, the biological process and attribute in an orchestrated manner. By comparison, random technical or biological noise is expected to affect each gene independently. This motivates the use of the earlier PCs in our downstream analyses, which concentrates the biological signal to reduce computational work and remove noise simultaneously. 
To evaluate how many HVGs, dimensions, and resolutions we choose  nfeature range from 2k to 6k, PCA dim 10 to 60, resolution from 0.2 to 1.2, select favored dim used in FindNeighbors and RunUAMP/RunTSNE, and check:
1). PCA elbow, PCA dim heatmap, cell inheritance robustness (by R library clustree)
2). UMAP plot showing batch effect, cell quality effect
3). Whether Clustering cell ratio similar between replicates
4). Reclustering projection ratio (e.g., u r interested in glia, subset them and re-integrate, plot original clustering annotation projected to reclustered cluster ratio)
5). Top markers of each cluster expression heatmap are distinct or not.
6). If u r working with model organism, u may evaluate clustering quality by doing correlation between bulk RNA-seq of each cell type and plot to see if there is correlation gap which can reflect clustering purity.
