### ISSUE TITLE
How to apply colour scale to a DotPlot when split.by is being used

### ISSUE THREAD

**Issue by NiallTUCD** [satijalab/seurat#4760]
Hi there, I am using DotPlots to show the differences in expression between certain clusters in my groups. I want to apply a color scale that shows the differences clearly such as the gradient "Blues" in RColorBrewer however when this is run, the scale goes from a dark color for low expression to a lighter color for high expression. Below is the code I am using: 

DotPlot(data, features = features, scale.max = 100,  scale.min = 0.05, cols = "Blues", idents = c("1", "2", "3"), split.by = "orig.ident") + coord_flip() &
  theme(legend.position = "right",
            axis.text = element_text(size = 10),
            axis.title = element_text(size = 10),
            legend.text = element_text(size = 10), 
            legend.title = element_text(size = 10)) + RotatedAxis()

Is there a way to make it so that low expression is a light color while high expression is dark while using this color palette? I've played around with other code but haven't been able to get it working. I'm quite new to making graphs this way so any help is greatly appreciated. Thanks!
Niall

**Comment by k3yavi** [comment]
Hi @NiallTUCD ,

Thanks for reaching out to us. Does swapping `cols = "Blues"` with `cols=c("blue", "white")` helps ?

**Comment by NiallTUCD** [comment]
Hi Avi, thanks for getting back to me. I tried that and I got an error saying "Not enough colors for the number of groups". I assume this is because I am using the split.by function meaning I have 4 groups and when using cols=c() I would have to assign four colors, one for each group. However when I do this, there is no expression bar in the legend. 

One possible way I could get around this is to use cols = c(), assign four colors and then in a DotPlot where split.by is not used, assign cols = c() with the second color being the same as is used in the split.by graph. In that case, would the default color for low expression be a shade of grey? 

Obviously this is not ideal as I would prefer to use proper code to make the split.by DotPlot.

**Comment by k3yavi** [comment]
Hi @NiallTUCD ,

you can try `cols=c(rep("blue",4), "white")` and check if that works.

**Comment by hartmannmark** [comment]
> Hi @NiallTUCD ,
> 
> you can try `cols=c(rep("blue",4), "white")` and check if that works.

Sorry to open this up again... I've got the same problem and, unfortunately, this didn't work for me, too.

**Comment by QueenieBear** [comment]
> cols=c(rep("blue",4), "white")

me too, same problem when using split.by

**Comment by utkinaira** [comment]
> Hi @NiallTUCD ,
> 
> you can try `cols=c(rep("blue",4), "white")` and check if that works.

Also facing this issue, let me know if you have found a solution. 
Thanks!

**Comment by SandyKroh** [comment]
For me it worked when using  "RdBu" as cols.
