### ISSUE TITLE
Can densMAP (in development version) yield reproducible clustering?

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#4762]
densMAP seems to work (hallelujah!) but the clustering is not reproducible. If I run the same pipeline twice over, the clustering is similar yet different. Is there a way to make it reproducible?

thanks,

 Nicolaas

ps command I run is:
 RunUMAP(MySeuratObject, dims = 1:UMAP.dimensions, densmap=TRUE)

**Comment by k3yavi** [comment]
Hi @NicolaasVanRenne ,

I think it's unrelated to Seurat and rather the feature/issue of generating low dimensional embeddings using UMAP as it can result in different looking (although topologically similar)  clusters  in multiple runs of the same data. Although you can try setting the seed like `set.seed(12)` and check if that helps.

**Comment by NicolaasVanRenne** [comment]
Thanks for replying @k3yavi ,

However, I always apply set.seed as you mentioned. It does not work to make densMAP reproducible. Getting reproducible plots is important to me - as I would prefer my analyses to be reproducible...

Maybe @lldelisle can help here? As she wrote the code if I understood from #4630 

Any thoughts?

Nicolaas

**Comment by lldelisle** [comment]
Hi,
I am sorry. I cannot really help. Apparently the seed is set in python by:
https://github.com/satijalab/seurat/blob/421f472dd6ce4650c458436fd20e86e15adea628/R/dimensional_reduction.R#L1268-L1270
And it is set to 42 by default:
https://github.com/satijalab/seurat/blob/421f472dd6ce4650c458436fd20e86e15adea628/R/dimensional_reduction.R#L1681
...
Sorry...
