### ISSUE TITLE
Trouble converting single cell experiment object to Seurat object

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4763]
Hello!

I know there have been several issues posted about this (e.g. https://github.com/satijalab/seurat/issues/4556 and https://github.com/satijalab/seurat/issues/837 (though I think the latter is outdated for Seurat v3 right? I can't find the particular function it uses). I know there is also the conversion vignette (https://satijalab.org/seurat/articles/conversion_vignette.html) but I am still not sure what I am doing wrong.

Here is the information on my single cell experiment object:
![image](https://user-images.githubusercontent.com/62159599/125357356-2644ab00-e32d-11eb-8dae-40d2092b0e67.png)

I have tried the following and got the following errors:

```
sobjbatch <- as.Seurat(sobjSCE, counts = "reconstructed", data = NULL)

Error in UseMethod(generic = "as.sparse", object = x) : 
  no applicable method for 'as.sparse' applied to an object of class "c('LowRankMatrix', 'DelayedMatrix', 'DelayedArray', 'DelayedUnaryIsoOp', 'DelayedUnaryOp', 'DelayedOp', 'Array', 'RectangularData')"
```

I also tried installing the development version and the same errors result
```
package.version("Seurat")
[1] "4.0.3.9008"
```

Thanks for reading!

**Comment by k3yavi** [comment]
Hi @ksaunders73 ,

It seems the counts matrix in the singleCellExperiment object you have is a DelayedMatrix object ? Currently we don't support Delayed array/matrix based operation but we'd let you know once we have a support for this feature. If the matrix size is reasonable you can always create a Seurat object from a dense or sparse matrix.

**Comment by WilliamMWei** [comment]
@k3yavi @ksaunders73 Hi, I'm encountering with the same problem. Could I ask if there is any updates?

**Comment by NajlaAbassi** [comment]
Hi, are there any updates? because I run into the same error. I'm using version 5.0.3
