### ISSUE TITLE
Extremely large theta values when manually computed (seurat bmcite30k dataset)

### ISSUE THREAD

**Issue by akshayMpatel** [satijalab/seurat#4768]
I want to compute theta manually between any two cells (i,j) by taking precomputed variables from the bm seurat object.  I presume it is not intended to get extremely large values, which I do for RNA for example max value 4.28e+23.  

This is how I compute the theta :

I preprocess 50 pcs for RNA and 20 pcs for ADT exactly as in the [vignette](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html). 

```
...
bm <- FindMultiModalNeighbors(bm, reduction.list = list("pca", "apca"), 
                              dims.list = reduced_dim, return.intermediate = TRUE)

pcs_rna <- Embeddings(bm, reduction = "pca")[, reduced_dim[[1]]]
pcs_adt <- Embeddings(bm, reduction = "apca")[, reduced_dim[[2]]]

weights_rna <- bm$RNA.weight
weights_adt <- bm$ADT.weight

sigmas_rna <- bm@misc$modality.weight@params$sigma.list$pca
sigmas_adt <- bm@misc$modality.weight@params$sigma.list$apca

knn_rna <- FindNeighbors(bm, reduction = 'pca', dims = reduced_dim[[1]], return.neighbor = TRUE,  
                              graph.name = c('pca.nn'), k.param = 21)
knn_adt <- FindNeighbors(bm, reduction = 'apca', dims = reduced_dim[[2]], return.neighbor = TRUE,  
                              graph.name = c('apca.nn'), k.param = 21)
# remove first knns because it is the cell itself (possiblly unintended behavior, and reason why k.param=21 instead of 20)

labels <- bm@meta.data$celltype.l2
numCells <- length(labels)

euclid <- function(a, b) sqrt(sum((a - b)^2))

theta_rna <- matrix(0.0, nrow=numCells, ncol=numCells)
theta_adt <- matrix(0.0, nrow=numCells, ncol=numCells)

# for all cells i, j
   theta_rna[i,j] <- exp( -max(euclid(pcs_rna[i,], pcs_rna[j,]) - euclid(pcs_rna[i,], knn_rna[i,1]), 0.0)/
                                      (sigmas_rna[i] - euclid(pcs_rna[i,], knn_rna[i,1]))
                                    )
   # same for adt

```

- Easiest Solution: Can I access theta_ij (between arbitrary cells) from the Seurat Object?
- Am I extracting the necessary values from the seurat object correctly?
- I assume that the indices of the pcs_rna and pcs_adt and the other values (sigmas...) refer to the same cells?
- ...How to solve this?

Many thanks

**Comment by yuhanH** [comment]
HI @akshayMpatel 
This issue shows you how to extract theta value from the model https://github.com/satijalab/seurat/issues/4698
The detailed function we used to calculate modality weights is `Seurat:::FindModalityWeights`. 
 All the intermediate value can be found `modality@score.matrix` and `modality@params`.
