### ISSUE TITLE
About improve cluster using node attributes

### ISSUE THREAD

**Issue by AmyTanJ** [satijalab/seurat#4770]
I have used Seurat::FindClusters( ) getting a cluster. Now I have samples' attributes and I want to add it to the network improving intial network cluster. Do Seurat have this function?

Looking forward to your reply.

**Comment by k3yavi** [comment]
Hi @AmyTanJ ,

May be you can try splitting the object based on the attributes first and then perform clustering on individual samples ? It's hard to guess what you wan't to do but unfortunately I don't see a way to add the attributes post clustering.
