### ISSUE TITLE
Add image.alpha parameter to SpatialDimPlot and SpatialFeaturePlot

### ISSUE THREAD

**Issue by alberto-valdeolivas** [satijalab/seurat#4771]
Hello!

First of all, many thanks for developing, updating and actively maintaining this great package!

I am working with some Spatial Transcriptomics data and I would like to know if some improvements can be added regarding the visualization of this kind of data. 

In particular, I would like to know if it is possible to include the `image.alpha` parameter in the functions `SpatialDimPlot `and `SpatialFeaturePlot`. The `SpatialPlot `function contains this parameter and I find it really practical in terms of  a more clear visualization of the results. 

Many thanks and best regards,
Alberto.

**Comment by andrewwbutler** [comment]
Hi Alberto,

Thanks for the suggestion! We've added the `image.alpha` parameter to both `SpatialDimPlot` and `SpatialFeaturePlot` now in the develop branch. Please see install instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1).

**Comment by SevtapYasinoglu** [comment]
Hi Alberto, 

Thanks for the info! I am also working on spatial data and I was wondering how to get rid of the H&E staining color. I have tried to install the development version, but it failed. Do I have to install an older version of R before I try to install the development version of Seurat? I get this:

# Enter commands in R (or R studio, if installed)
> # Install the remotes package
> install.packages('remotes')
Installing package into ‘\\vf-lumc-home.lumcnet.prod.intern/lumc-home$/sayasinoglu/MyDocs/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/remotes_2.4.0.zip'
Content type 'application/zip' length 394611 bytes (385 KB)
downloaded 385 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\sayasinoglu\AppData\Local\Temp\RtmpCO7HXZ\downloaded_packages
> remotes::install_github(repo = 'satijalab/seurat', ref = 'develop')
Downloading GitHub repo satijalab/seurat@develop
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: later  (1.2.0 -> 1.3.0) [CRAN]
5: httpuv (1.6.1 -> 1.6.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: library(Seurat)
Enter one or more numbers, or an empty line to skip updates: 3
√  checking for file 'C:\Users\sayasinoglu\AppData\Local\Temp\RtmpCO7HXZ\remotes8fe0254369b2\satijalab-seurat-acadb5d/DESCRIPTION' (456ms)
-  preparing 'Seurat': (364ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'Seurat' ...
   ** using staged installation
   ** libs
   /mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG  -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/Rcpp/include' -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/RcppEigen/include' -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/RcppProgress/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -fdiagnostics-color=always -c ModularityOptimizer.cpp -o ModularityOptimizer.o
   In file included from ModularityOptimizer.cpp:23
   ModularityOptimizer.h:159:2:warning: tra ';-Wpedantic
    };
     ^
   ModularityOptimizer.cpp:86:3:warning: tra ';-Wpedantic
    {};
      ^
   ModularityOptimizer.cpp:165:22:warning: tra ';-Wpedantic
    Network::Network() {};
                         ^
   ModularityOptimizer.cpp:n constructor 'ModularityOptimizer::Network::Network(int, DVector*, std::vector<std::vector<int> >&, DVector*)
   ModularityOptimizer.cpp:204:3:warning: is 'foruse does not guard... [-Wmisleading-indentation
      fore_t j = 0; j < edge[0].size(); j++)
      ^~~
   ModularityOptimizer.cpp:216:5:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
        for <= nNodes; i++)
        ^~~
   ModularityOptimizer.cpp:n member function 'ModularityOptimizer::Clustering ModularityOptimizer::Network::identifyComponents()
   ModularityOptimizer.cpp:387:9:warning: is 'foruse does not guard... [-Wmisleading-indentation
            for l = firstNeighborIndex[node[k]]; l < firstNeighborIndex[node[k] + 1]; l++)
            ^~~
   ModularityOptimizer.cpp:395:11:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
              k
              ^
   ModularityOptimizer.cpp:377:3:warning: is 'foruse does not guard... [-Wmisleading-indentation
      for i = 0; i < nNodes; i++)
      ^~~
   ModularityOptimizer.cpp:399:5:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
        clusteringrClustersByNNodes();
        ^~~~~~~~~~
   ModularityOptimizer.cpp:n member function 'ModularityOptimizer::Network ModularityOptimizer::Network::createSubnetwork(const ModularityOptimizer::Clustering&, int, IVector&, IVector&, IVector&, DVector&) const
   ModularityOptimizer.cpp:429:7:warning: is 'foruse does not guard... [-Wmisleading-indentation
          for k = firstNeighborIndex[j]; k < firstNeighborIndex[j + 1]; k++)
          ^~~
   ModularityOptimizer.cpp:436:9:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
            subnetworktNeighborIndex[i + 1] = subnetwork.nEdges;
            ^~~~~~~~~~
   ModularityOptimizer.cpp:t global scope:
   ModularityOptimizer.cpp:453:4:warning: tra ';-Wpedantic
      };
       ^
   ModularityOptimizer.cpp:458:27:warning: tra ';-Wpedantic
      resolution(resolution){};
                              ^
   ModularityOptimizer.cpp:n member function 'int ModularityOptimizer::VOSClusteringTechnique::removeCluster(int)
   ModularityOptimizer.cpp:710:3:warning: is 'foruse does not guard... [-Wmisleading-indentation
      for j = 0; j < clustering->nClusters; j++)
      ^~~
   ModularityOptimizer.cpp:721:5:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
        if= 0)
        ^~
   ModularityOptimizer.cpp:723:7:warning: is 'foruse does not guard... [-Wmisleading-indentation
          for j = 0; j < network->nNodes; j++)
          ^~~
   ModularityOptimizer.cpp:726:9:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
            ifster == clustering->nClusters - 1)
            ^~
   ModularityOptimizer.cpp:n member function 'void ModularityOptimizer::VOSClusteringTechnique::removeSmallClusters(int)
   ModularityOptimizer.cpp:740:5:warning: is 'foruse does not guard... [-Wmisleading-indentation
        for k = 0; k < vosClusteringTechnique.clustering->nClusters; k++)
        ^~~
   ModularityOptimizer.cpp:747:7:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
          if= 0)
          ^~
   ModularityOptimizer.cpp:n function 'std::shared_ptr<ModularityOptimizer::Network> ModularityOptimizer::matrixToNetwork(IVector&, IVector&, DVector&, int, int)
   ModularityOptimizer.cpp:764:3:warning: is 'foruse does not guard... [-Wmisleading-indentation
      fore_t i = 0; i < node1.size(); i++)
      ^~~
   ModularityOptimizer.cpp:771:5:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
        IVectortNeighborIndex(nNodes + 1);
        ^~~~~~~
   ModularityOptimizer.cpp:783:5:warning: is 'foruse does not guard... [-Wmisleading-indentation
        fore_t i = 0; i < node1.size(); i++)
        ^~~
   ModularityOptimizer.cpp:796:7:note: .this statement, but the latter is misleadingly indented as if it were guarded by the 'for
          ifularityFunction == 1)
          ^~
   ModularityOptimizer.cpp:761:7:warning: used variable 'n1_max-Wunused-variable
      int n1_maxtd::max_element(node1.cbegin(), node1.cend());
          ^~~~~~
   ModularityOptimizer.cpp:762:7:warning: used variable 'n2_max-Wunused-variable
      int n2_maxtd::max_element(node2.cbegin(), node2.cend());
          ^~~~~~
   /mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG  -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/Rcpp/include' -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/RcppEigen/include' -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/RcppProgress/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -fdiagnostics-color=always -c RModularityOptimizer.cpp -o RModularityOptimizer.o
   RModularityOptimizer.cpp:9:10:fatal error: igen.h: No such file or directory
    #include <RcppEigen.h>
             ^~~~~~~~~~~~~
   compilation terminated.
   make: *** [C:/PROGRA~1/R/R-41~1.1/etc/x64/Makeconf:245: RModularityOptimizer.o] Error 1
   ERROR: compilation failed for package 'Seurat'
-  removing 'C:/Users/SAYASI~1/AppData/Local/Temp/RtmpmASocf/Rinst279819633ca6/Seurat'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'Seurat' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> /mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG  -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/Rcpp/include' -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/RcppEigen/include' -I'\\vf-lumc-home.lumcnet.prod.intern/lumc-homesayasinoglu/MyDocs/R/win-library/4.1/RcppProgress/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -Wall -pedantic -fdiagnostics-color=always -c RModularityOptimizer.cpp -o RModularityOptimizer.o
E> RModularityOptimizer.cpp:9:10:fatal error: igen.h: No such file or directory
E>  #include <RcppEigen.h>
E>           ^~~~~~~~~~~~~
E> compilation terminated.
E> make: *** [C:/PROGRA~1/R/R-41~1.1/etc/x64/Makeconf:245: RModularityOptimizer.o] Error 1
E> ERROR

And, after this warning updating app packages gave also the same errors in the end:
These packages have more recent versions available. 
It is recommended to update all of them. 
Which would you like to update?

How can I solve this problem?

Best,
Sevtap

**Comment by andrewwbutler** [comment]
Hi Sevtap,

This looks like an issue with your toolchain setup for compiling on Windows. This update is now part of the latest CRAN release (4.0.4) so the easiest solution now is to just install from there with the normal `install.packages("Seurat")`
