### ISSUE TITLE
multi-sample comparison in seurat v4, alternative workflow to RunMultiCCA

### ISSUE THREAD

**Issue by dienerpatrick** [satijalab/seurat#4772]
I have a dataset with multiple patients, each patient as a seurat object. Later I want to split the patients in two groups (different treatment) to then compare them. I need to run batch correction between the patients. I wanted to do this with RunMultiCCA, but the function is not available anymore. How could I do this? Thanks!

**Comment by timoast** [comment]
Please see https://satijalab.org/seurat/articles/integration_introduction.html
