### ISSUE TITLE
common genes integration for different datasets

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#4773]
Dear Seurat team, 

Datasets that I have generated have about 21K transcripts/genes (as per features.tsv tile). I noticed the other very similar datasets with the same cell clusters as mines goes to just over 50K transcripts. Which means in the end, that very similar cell clusters from the two labs are different in 3-dimensional plots because the other one has detected other types of RNA molecules. 
Is there a way to combine them where I can only focus on common features between the different datasets. 
Many thanks once again.

**Comment by torkencz** [comment]
Hi, you should be able to combine datasets via the function merge (https://satijalab.org/seurat/articles/merge_vignette.html), which should be able to handle different number of transcripts. If that doesn't work you can subset to a shared set of transcripts and use our integrations vignettes downstream of that.
