### ISSUE TITLE
Differential Expression Doubts

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#4774]
Hi Seurat Team!
I have some doubts regarding how Differential Expression Analysis is done in Seurat. 

1. When comparing the expression of two clusters, is it using cells as if they were replicates or using a pseudobulk approach (that is, aggregating the counts of all the cells belonging to the same cluster)?
2. In `FindMarkers()` function, if no `ident.2` is specified how is the DE genes list obtained? I mean, if no `ident.2` is specified, the `ident.1` is tested against all the rest of the cells together? or against each other clusters one after the other? In the latter case, which genes are kept as differentially expressed in the output list? are those that appear DE in all comparisons?
3. Why is it necessary the `FindConservedMarkers()` function? I think I don't understand what the `grouping.var` parameter is doing. For example, if I have a dataset with "control" and "stim" conditions and I want to obtain the DE genes for cluster "1", why not perform just the `FindMarkers()` specifying `ident.1="1"`? The cluster "1" will contain both "control" and "stim" cells anyways, isn't it? 
4. After using `FindConservedMarkers()` (screenshot from your [tutorial](https://satijalab.org/seurat/archive/v3.1/immune_alignment.html)):
![image](https://user-images.githubusercontent.com/57805802/125648393-524e4ff9-dfb4-4c9f-8213-092474c92b7c.png)
why p-values and other statistics are separated in CTRL and STIM? 
5. How are the DE genes obtained for each cluster using the `FindAllMarkers()` function? It's a question similar to question 2.

Please let me know if I didn't explain any of my questions clearly. Thank you very much,
Marta.

**Comment by liuxl18-hku** [comment]
Not team member, but would like to share my thoughts and appreciate team members' comments:

I was not updated to Seurat V4, knowledge is based on V3 usage.

> When comparing the expression of two clusters, is it using cells as if they were replicates or using a pseudo bulk approach (that is, aggregating the counts of all the cells belonging to the same cluster)?

It's not. Each cell was treated individually and usually we will get very significant P-value due to the high power.

> In FindMarkers() function, if no ident.2 is specified how is the DE genes list obtained? I mean, if no ident.2 is specified, the ident.1 is tested against all the rest of the cells together? or against each other clusters one after the other? In the latter case, which genes are kept as differentially expressed in the output list? are those that appear DE in all comparisons?

It's one vs all the other test.

> Why is it necessary the FindConservedMarkers() function? I think I don't understand what the grouping.var parameter is doing. For example, if I have a dataset with "control" and "stim" conditions and I want to obtain the DE genes for cluster "1", why not perform just the FindMarkers() specifying ident.1="1"? The cluster "1" will contain both "control" and "stim" cells anyways, isn't it? After using FindConservedMarkers() ... why p-values and other statistics are separated in CTRL and STIM?

By default, if we use `FindMarkers` by setting `ident.1 = "1"`, resulted markers will include DE genes between conditions ("control" and "stim"), which is confounding in this scenario. If Seurat V3, we can try to regress out this confounding effect (if it is not mixed with variability of un-supervised clusters, that's why integration and batch effect correction is required before clustering) by using alternative DE approach allowing us to include confounding factors as latent variables `latent.vars` when built the model. I assume `FindConservedMarkers` was designed for the similar reason.

> How are the DE genes obtained for each cluster using the FindAllMarkers() function? It's a question similar to question 2.

`FindAllMarkers` is running one vs all the other DE for all clusters.

bless~

**Comment by MartaBenegas** [comment]
> By default, if we use FindMarkers by setting ident.1 = "1", resulted markers will include DE genes between conditions ("control" and "stim"), which is confounding in this scenario. If Seurat V3, we can try to regress out this confounding effect (if it is not mixed with variability of un-supervised clusters, that's why integration and batch effect correction is required before clustering) by using alternative DE approach allowing us to include confounding factors as latent variables latent.vars when built the model. I assume FindConservedMarkers was designed for the similar reason.

Oh okay, I think I get it. I hadn't in mind that the DE is performed with the RNA assay which doesn't have the corrections introduced by the integration analysis. So yes, in spite of being labeled with the same cluster name cells will have variation due to their condition, right?

Thank you very much for your responses! I also hope that a team member can corroborate them. 
Marta.

**Comment by jaisonj708** [comment]
The user's answers seem to be correct! And yes, FindConservedMarkers will help you take into the variation due to condition (e.g, tests whether a feature is DE between clusters across all/most conditions).

**Comment by denvercal1234GitHub** [comment]
Hi @jaisonj708 and @liuxl18-hku - So I understand correctly, so performing `FindConservedMarkers()` with `grouping.var = variable` is the same as doing FindMarkers() with `latent.vars = variable` right? Thank you so much!
