### ISSUE TITLE
How can I choose a clustering scheme in FindAllMarkers function

### ISSUE THREAD

**Issue by zh-zhang1984** [satijalab/seurat#4775]
Hi, 
I found the FindMarkers() function has a group.by option to select a clustering scheme; but THE FindAllMarkers did not have such an option. I have many clusters by running the following chunk:
```
SeuratIntegrate <- FindClusters(
  SeuratIntegrate, resolution = c(0.4, 0.6, 0.8, 1.0, 1.4)
  )
```
In FindMarkers() I can do:
```
MinorMarkers <- FindMarkers(
  SeuratIntegrate,ident.1 = c("20","19"),
  min.cells.group = 2,
  group.by = 'integrated_snn_res.0.4'
)
```

**Comment by k3yavi** [comment]
Hi @zh-zhang1984 ,

Thanks for the question. You can reset the `Idents(SeuratIntegrate)` with the metadata from `integrated_snn_res.0.4` to achieve that.

**Comment by AlbertoFabbri93** [comment]
Can you add the `group.by` option to `FindAllMarkers`? I find that way more intuitive because it keeps the parameter within the function and it keeps the function consistent in how it works even if you move it to another part of the program.
