### ISSUE TITLE
FindIntegrationAnchors fails if at least one of the Seurat objects contain chromatin assay

### ISSUE THREAD

**Issue by skilpinen** [satijalab/seurat#4776]
For certain validation purposes I followed this:
https://satijalab.org/seurat/articles/integration_introduction.html

And here is code that failed:
s.data.list <- list(s.data.mm, s.data.nmm)
brain.anchors <- FindIntegrationAnchors(object.list = s.data.list, anchor.features = features)
Scaling features for provided objects
Loading required package: Signac

Attaching package: ‘Signac’

The following object is masked from ‘package:Seurat’:

    FoldChange

Error in as.vector(x, mode) : 
  cannot coerce type 'closure' to vector of type 'any'
----

s.data.mm contains meni assays, including chromatin ones but active assay in both objects is RNA
> s.data.mm
An object of class Seurat 
400067 features across 2248 samples within 5 assays 
Active assay: RNA (32285 features, 3000 variable features)
 4 other assays present: peaks_count, peaks, Activity, RNA_est
 4 dimensional reductions calculated: lsi, umap, pca, wnn.umap

However, if I do this:
s.data.list <- list(CreateSeuratObject(s.data.mm[['RNA']]), s.data.nmm)

and then carry on with the same code it goes through. Don't know if it is known issue or not, or bug at all, but nevertheless it was bit surprising.

**Comment by timoast** [comment]
Can you show the output of:

```r
sapply(s.data.nmm@assays, class); sapply(s.data.mm@assays, class)
```

and also show the output of `sessionInfo()`
