### ISSUE TITLE
CellCycleScoring not recognizing my list of cell cycle genes

### ISSUE THREAD

**Issue by dtatarakis** [satijalab/seurat#478]
I am trying to assign cell-cycle scores to the cells in my scRNA-seq dataset, but I am having problems with the CellCycleScoring() function in Seurat. I am working with zebrafish cells, so I cannot use the stock cc.genes list that is available in seurat. therefore I made my own list and followed the rest of the instructions in the vignette.

I made a vector zfcc.genes using ReadLines() 

It contains 90 genes that are markers of s phase or g2/m phase in zebrafish. I then  split it into two other vectors for s-phase and g2m phase genes:
```R
zfs.genes <- zfcc.genes[1:41]
zfg2m.genes <- zfcc.genes[42:90]
```
When I run my command:
```R
zf_cells <- CellCycleScoring(object = zf_cells, s.genes = zfs.genes, g2m.genes = zfg2m.genes, set.ident = TRUE)
```
I get this series of errors:

```R
Error in AddModuleScore(object = object, genes.list = genes.list, enrich.name = enrich.name, : The following gene lists do not have enough genes present in the object: S.Score exiting...The following gene lists do not have enough genes present in the object: G2M.Score exiting... In addition: Warning message: In AddModuleScore(object = object, genes.list = genes.list, enrich.name = enrich.name, : Could not find enough genes in the object from the following gene lists: S.Score Attempting to match case...Could not find enough genes in the object from the following gene lists: G2M.Score Attempting to match case...
```
The list of genes I made is slightly shorter than the one provided with seurat. By about 4 genes. Is it really looking for the exact number of genes in the stock list? I don't see why this would be the case. Shouldn't you be able to build your own list of genes? I think I'm misunderstanding the problem.

**Comment by leonfodoulian** [comment]
Hi,

Could you please check if any of those genes is present in your `object@data` slot? 

```R
length(x = which(x = zfs.genes %in% rownames(x = zf_cells@data)))
length(x = which(x = zfg2m.genes %in% rownames(x = zf_cells@data)))
```
Best,
Leon

**Comment by colmbc** [comment]
I had the same issue because the CC.genes list is uppercase and my 10x output is "Sentence case" leaving 0 intersections. I converted cc.genes with stringr to match the correct format as shown below. 

library(stringr)
cc.genes <- str_to_title(cc.genes)

**Comment by lengfei5** [comment]
I have a naive question about how you found those cell cycle markers for S and G2/M phases, manually curated ??  I am wondering if there is an easy way. BTW I am working on C. elegans. Thanks.

**Comment by ChengTao2017** [comment]
Hi,
dtatarakis,how do you define the cell cycle marker genes in zebrafish,I also analysis zebrafish single cell rna seq data?
Best,
Tao
