### ISSUE TITLE
Set random seed to downsample data in subset function

### ISSUE THREAD

**Issue by aress212** [satijalab/seurat#4784]
Hey, I am downsampling data using subset function --> subset(Seuratobj, downsample = 50) to do burden analysis and i want to see if burden analysis is robust to different sets of cells. I set distinct random seeds, but it doesn't seem to change downsample function. Is there a way to set random seed within subset function? Something like subset(obj, downsample = 20, randomseed = TRUE)

**Comment by saketkc** [comment]
You can pass a seed to subset function: `subset(obj, donsample=10, seed=42)`.
