### ISSUE TITLE
Integration when conditions are confounded by sample processing times?

### ISSUE THREAD

**Issue by aelhossiny** [satijalab/seurat#4785]
Hi, first thank you for such an incredible package! It's really fantastic

So, I have a multiple samples that I am trying to integrate for downstream analysis. The problem that, each condition was processed at separate time point (date), so after merging all samples into one seurat object and then do the integration where the I am splitting the dataset according to the time point, everything becomes one big blob in the UMAP plot, where cells are evenly distributed. I justed wanted to make sure if the integration steps assumes the cell population is similar across batches? and that now I am removing the biological difference in the integration step? or can it batch-correct biologically distinct batches/samples?

Thank you!

**Comment by jaisonj708** [comment]
If your developmental time points are significantly different but mixing after integration, I would try running with RPCA instead of CCA. Usually this results in more conservative integration.

**Comment by aelhossiny** [comment]
That gave better results. Thank you!
