### ISSUE TITLE
Cannot open seurat website

### ISSUE THREAD

**Issue by ryrl9703** [satijalab/seurat#4788]
https://satijalab.org/seurat/  cannot open for a long time.

**Comment by WesDe** [comment]
Hi,

Not a dev here, but I'm able to open it (Firefox, Linux distribution).  Which OS and web browser are you using ? It may be related to your web browser. Try to update it or to use another web browser.

Best,
WesDe

**Comment by saketkc** [comment]
The website is up and has not had issues recently. You can check the status [here](https://downforeveryoneorjustme.com/satijalab.org?proto=https)

**Comment by ryrl9703** [comment]
Windows-Bing
Thanks
