### ISSUE TITLE
Multiple batch effects in integration data

### ISSUE THREAD

**Issue by WesDe** [satijalab/seurat#4789]
Hi,

Thank you for the great tool you provide to the community ! I am trying to integrate multiple datasets from a same tissue (healthy, disease, fetal, adult, organoid). However batch effect correction varied from datasets based on the publication they come from. I was wondering how to handle these batch effects, do i need to :
1. take care of each batch effect between samples from the same publication before integration 
2. let SCTransform take care of this for me without setting a specific value to var.to.regress
3. set specific value to var.to.regress such as every parameters used in publication (i.e : percent.mt, RNA count, cell cycle score...)
4. Run 1,2,3 and identify which solution fits the best with expected results because my question is dependent datasets  ?

Best,
WesDe

**Comment by timoast** [comment]
It's difficult to say which approach is the best without seeing the datasets and the batch effects that exist between them. Basically, I'd suggest option 4.
