### ISSUE TITLE
overcluster in WNN / Cluster with 2 or 3 cells 

### ISSUE THREAD

**Issue by denoqo** [satijalab/seurat#4793]
Hi @yuhanH,

Congrats on your recent WNN paper!

I met an issue about using WNN. 
The clustering result output has over 100 clusters and many of them only have 2 or 3 cells.

**Graph**: FindMultiModalNeighbors()
**Normalization**: Log10 for RNA and CLR for ADT
**Integration**: FindIntegrationAnchors()
**UMAP**: RunUMAP(nn.name = "weighted.nn")
**Cluster** resolution: 2

I have tried several times to run it and adjust the resolution. But the issue stays the same for WNN. 

Thanks for you time!

![image](https://user-images.githubusercontent.com/44283017/125971153-29a891e9-0ff9-47db-b3fa-1ddd96005a35.png)

**Comment by yuhanH** [comment]
HI, @denoqo 
Thanks for your interests and reporting this issue. It seems that your data is big.  The clustering issue results from too many isolated groups (too sparse) in the SNN graph. I think when you can increase k.nn to 30, it should be resolved. Also, you would better set knn.range  to 500. 
```
 FindMultiModalNeighbors( k.nn = 30,  knn.range = 500)
```
Please let me know if it works.

**Comment by denoqo** [comment]
Thanks a lot, Yuhan!
Let me try it know and I’ll let you know.

**Comment by denoqo** [comment]
Hi @yuhanH,

I still got over a hundred clusters after adjusting the recommended parameter.
Looks like the is an error in the "reduction.list" too?

`> bm_satija_nn@commands$FindMultiModalNeighbors`
`Command: FindMultiModalNeighbors(integrated_seurat, reduction.list = list("pca", "pca.adt"),  k.nn = 30, knn.range = 500,   modality.weight.name = "RNA.weight")`
`reduction.list : Error in cat(names(params[p]), ":", params[[p]], "\n") : 
  argument 3 (type 'list') cannot be handled by 'cat'`

Thank you.

**Comment by yuhanH** [comment]
Hi, @denoqo 
What is the `dim.list` you set?
Generally, it's weird....If you could send your object to me, it will be much easier for me to figure out the reason. 
My email is `yhao@nygenome.org`.   Thanks.

**Comment by denoqo** [comment]
Thanks a lot for the kind reply.

Below is the dim.list:
dims.list = list(1:50, 1:31)

I was thinking if it's because we don't have enough antibodies.

**Comment by yuhanH** [comment]
HI, @denoqo 
I don't think the clustering issue results from the number of antibodies. 
When you don't have many antibodies in this dataset, you can use 1:10 or 1:15 for your ADT PCA. 
If your dataset is sensitive, you can just send the RNA pca cell embeddings and ADT pca cell embeddings. Thanks.

**Comment by jjoung** [comment]
Hi all,

For my dataset (RNA+ATAC), increasing the number of neighbors (testing increments up to 300) reduced the number of clusters but did not fix the problem. Changing prune.SNN to 1/20 fixed it.

**Comment by yuhanH** [comment]
HI @jjoung 
You are right.
If you decrease the SNN prune cut-off, it will make the SNN graph more connected.   It is a nice suggestion.  Thanks.

**Comment by denoqo** [comment]
Decreasing prune.SNN to 1/20 worked for me and reduced the cluster numbers. 
Thanks a lot for the kind sharing and help, @jjoung and @yuhanH.
