### ISSUE TITLE
How to Add Module Score to Portion of Object

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4794]
Hello! 

Essentially I'm wanting to keep my old UMAP, but only want to apply a module score to just one cluster instead of across the entire object without subsetting the cluster and then applying the module score to that subsetted cluster, if that makes sense.

What I have:

```
tnbclist <- list(c("FABP7", "TSPAN8", "CYP4Z1", "HOXA10", "CLDN1",
                   "TMSB15A", "C10ORF10", "TRPV6", "HOXA9", "ATP13A4",
                   "GLYATL2", "RP11-48O20.4", "DYRK3", "MUCL1", "ID4", "FGFR2",
                   "SHOX2", "Z83851.1", "CD82", "COL6A1", "KRT23", "GCHFR",
                   "PRICKLE1", "GCNT2", "KHDRBS3", "SIPA1L2", "LMO4", "TFAP2B",
                   "SLC43A3", "FURIN", "ELF5", "C1ORF116", "ADD3", "EFNA3",
                   "EFCAB4A", "LTF", "LRRC31", "ARL4C", "GPNMB", "VIM", 
                   "SDR16C5", "RHOV", "PXDC1", "MALL", "YAP1", "A2ML1",
                   "RP1-257A7.5", "RP11-353N4.6", "ZBTB18", "CTD-2314B22.3", "GALNT3",
                   "BCL11A", "CXADR", "SSFA2", "ADM", "GUCY1A3", "GSTP1",
                   "ADCK3", "SLC25A37", "SFRP1", "PRNP", "DEGS1", "RP11-110G21.2",
                   "AL589743.1", "ATF3", "SIVA1", "TACSTD2", "HEBP2"))
sobj <- AddModuleScore(object = sobj, features = tnbclist, name = "TNBC_List") 
FeaturePlot(object = sobj, features = "TNBC_List1", order = TRUE, min.cutoff = 0, label = TRUE, repel = TRUE) 
```

![image](https://user-images.githubusercontent.com/62159599/125980407-497e0413-4a25-4c28-b237-bfae1bc63e7b.png)

What I would like (only color the TNBC cells' module score expression):

![image](https://user-images.githubusercontent.com/62159599/125980929-2bcfada2-04cc-4320-bde5-ab9ef778b9f6.png)

I tried specifying the cluster I want in the AddModuleScore() step, and in the FeaturePlot() step, but I am not sure where to go from here. 

```
#just subsets the entire object and then applies the module score to it
sobj <- AddModuleScore(object = (subset(x = sobj, idents = "TNBC (Basal-like)")), features = tnbclist, name = "TNBC_List", search = TRUE) 
``` 

![image](https://user-images.githubusercontent.com/62159599/125982508-c7bd7f71-b7ff-4c6c-b2bb-cff42017a519.png)

```
sobj@meta.data$Cluster <- Idents(sobj)
sobj <- AddModuleScore(object = sobj@meta.data$Cluster, features = tnbclist, name = "TNBC_List", search = TRUE)  

> Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "factor"
```

```
#Doesn't change plot if just set the features equal to "TNBC_List1"
TNBC <- FeaturePlot(object = sobj, features = c("TNBC_List1", "Cluster"== "TNBC (Basal-like)"), order = TRUE, label = TRUE, min.cutoff = 0) 

> Warning message:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: FALSE
```

Thanks for reading!

**Comment by yuhanH** [comment]
Hi, @ksaunders73 
What is your motivation of plotting module score only in one cluster? One easy way is to set other cells' module score to zero...

**Comment by ksaunders73** [comment]
I just wanted to more closely analyze the module score in a particular cluster (here, I want to see the module score's expression in the TNBC cluster). Does that make sense? How do you set other cells' module score to zero?

**Comment by yuhanH** [comment]
You can select the cells not belonging to your target cluster and set them to zero. 
```
# assume cluster 1 is what you want
other.cells <- WhichCells(object = obj, idents = 1, invert = TRUE)
obj$module.score[ other.cells ] <- 0
```

**Comment by ksaunders73** [comment]
This worked. Thank you so much for your help @yuhanH !

**Comment by samuel-marsh** [comment]
@ksaunders73 as note though even when setting the score of the other cells to 0 the score you get for your targeted cluster is still effected by the by the composition of the dataset overall.  See this example from the UCell package:
https://carmonalab.github.io/UCell/UCell_Seurat_vignette.html#compare-to-addmodulescore-from-seurat

You may want to read their paper for more info on their alternative method:
https://www.sciencedirect.com/science/article/pii/S2001037021002816?via%3Dihub

Best,
Sam

**Comment by ksaunders73** [comment]
Hello @samuel-marsh, I'll keep that in mind, thank you for the suggestion!
