### ISSUE TITLE
Multiple cluster created for same cell type

### ISSUE THREAD

**Issue by shubham7193** [satijalab/seurat#4795]
I am trying to analyze single-cell data from mouse retinal cells. After clustering, UMAP and Findallmarkers(), two clusters are reported to have the same marker set. Is it normal in analysing such data sets? How can I merge these clusters if required?

**Comment by timoast** [comment]
Choosing the correct level of clustering resolution is typically something that needs to be determine through a supervised analysis, involving looking at the differentially expressed genes that can be confidently identified for each group of cells. Another important point to consider is what cells you are using as the comparison group in your differential test. By default, all other cells are used. This may result in similar markers being identified across some cell types. Directly contrasting the more similar clusters in a differential test may allow you to identify genes that distinguish the clusters.
