### ISSUE TITLE
How can I subset my Seurat object based on equivalent metadata in two columns?

### ISSUE THREAD

**Issue by noelletnw** [satijalab/seurat#4796]
Hello!

I hope I am phrasing this correctly, and I apologize in advance if I'm not, as I'm very new to all this!

I have a merged Seurat object where I have two classes of metadata, barcodes.library and barcodes.virus.  For example, the metadata would look something like this:

  barcodes.library barcodes.virus
1 A NA
2 NA A
3 B NA 

I want to subset my data so that I only take the cells where the data in barcodes.library is also found in barcodes.virus. So, in this above example, I would only want cell 1 as it is also found in barcodes.virus.

I have tried the following:

`DF <- subset(DF, DF@meta.data$barcodes.library == testing@meta.data$barcodes.virus)`

But get the following error:

```
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found: 
```

I have also tried putting in `` surrounding the two conditions, as seen in another posted question,  but got the same error.
I also tried the same idea using WhichCells, as below:

`WhichCells(DF,DF@meta.data$barcodes.virus == DF@meta.data$barcodes.virus)`

But got the following error:
```
Error in CellsByIdentities(object = object, cells = cells, ...) : 
  Cannot find cells provided
```

Any help would be greatly appreciated! I apologize if this is an obvious/more R syntax related question. Thank you!

**Comment by Dragonmasterx87** [comment]
Hi @noelletnw ,

It seems like you have already looked at possible solutions. Luckily I have some free time, so let's try and troubleshoot your challenge.

So, the way I would do this is:
1. Look and see if you even have cells that are overlapping. I like to use FetchData for this its a cool way to 'observe' your data
and also in some instances extract, but over time I have grown to only use this function to 'observe'

```
# Assuming the df is the name of your seurat object, which contains two metadata columns
# called barcodes.library and barcodes.virus
table(x = FetchData(df, vars = c('barcodes.library', 'barcodes.virus')

# the output of the above will be a table, which will contain all unique barcodes.library entries and a how many
# corresponding barcodes.virus entries there are in successive columns. Something like this:

                   barcodes.virus
barcodes.library   A     NA
A                  0      1
B                  0      1
NA                 1      0

# the above gives you an idea of whether you even have the cells you want to look at.
```


2. Now the subsetting part, is EZ. Seurat has powerful subsetting capabilities. May God bless the developers.
```
x1 <- subset(df, subset = (barcodes.library == c("A", "B")) & (barcodes.virus == "A", "B")) # keeps only A and B in both metadata
x2 <- subset(df, subset = (barcodes.library != c("NA")) & (barcodes.virus != "NA")) # removes all cells having a NA, probably 
# better to use this function as you probably have many more identities than just A and B
```

If after running `x2 <- subset(df, subset = (barcodes.library != c("NA")) & (barcodes.virus != "NA"))` you get the error:
`Error: No cells found` then that means you dont have any cells which are overlapping (both having a virus barcode and a library barcode)

Hope that helps!

Best,

🐉

**Comment by noelletnw** [comment]
Hi there!

Thanks so much for the help! I ended up doing it in a slightly (and albeit much more complicated way, but a result is a result). Basically I used %in%  to generate a column of TRUE/FALSE, and then subset my dataset where that metadata of overlapping barcodes was TRUE.

Thanks for showing me a different way of looking at it :)
