### ISSUE TITLE
Problem with converting R object file to matrix file

### ISSUE THREAD

**Issue by ychun04** [satijalab/seurat#4797]
When trying to extract tSNE and UMAP coordinates, tSNE worked with the same code but UMAP is giving me this error.

My code:
`UMAP <- New_Tiss@reductions[["umap"]]@cell.embeddings`

Error:
`Error: trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots`

Any idea how to make this work? Any help would be greatly appreciated. Thank you !

**Comment by timoast** [comment]
Do you have a dimension reduction named "umap" in the object?

**Comment by ychun04** [comment]
> Do you have a dimension reduction named "umap" in the object?

I'm not sure, but I downloaded the "facs_Kidney_seurat_tiss.Robj" file from Tabula Muris. I'm new to Seurat so I'm not really sure. sorry
