### ISSUE TITLE
ERROR: compilation failed for package 'Seurat'

### ISSUE THREAD

**Issue by muhe1985** [satijalab/seurat#48]
Dear there, I am trying to install Seurat in R studio for 3.2.5 version of R

after install install_github("satijalab/seurat")
I got hte error below...
Can you take a look when you get a chance?

Thank you so much!

** arch - i386
g++ -m32 -std=c++0x -I"C:/PROGRA~1/R/R-32~1.5/include" -DNDEBUG    -I"C:/Users/Wenduo/Documents/R/win-library/3.2/Rcpp/include" -I"C:/Users/Wenduo/Documents/R/win-library/3.2/RcppEigen/include" -I"C:/Users/Wenduo/Documents/R/win-library/3.2/RcppProgress/include" -I"d:/RCompile/r-compiling/local/local323/include"  -g -std=c++11 -Wall -pedantic   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
cc1plus.exe: error: unrecognized command line option '-std=c++11'
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-32~1.5/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.5/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="Seurat.dll" OBJECTS="RcppExports.o data_manipulation.o"' had status 2
ERROR: compilation failed for package 'Seurat'
* removing 'C:/Users/Wenduo/Documents/R/win-library/3.2/Seurat'
Error: Command failed (1)

**Comment by andrewwbutler** [comment]
Hmm, have you tried updating to the latest version of R and RTools?
