### ISSUE TITLE
MergeSeurat with multiple samples

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#480]
Hi,

I am trying to merge 10 Seurat objects into a single object without any batch correction. I am using the following function. 

```R
combined <- Reduce(function(x,y){MergeSeurat(x,y)}, object_list)
Error in MergeSeurat(x, y) : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names
```

However, each object has unique cell names already. Is there a way to get past this or is there another method to merge these objects?

Thanks,

Bibaswan

**Comment by mojaveazure** [comment]
The check that throws this error is `any(object1@cell.names %in% object2@cell.names)`, so I'm guessing you have duplicates somewhere. What is the output of the following?
```R
all.cell.names <- unlist(x = sapply(X = object_list, FUN = function(obj) {return(obj@cell.names)}))
cell.name.counts <- table(all.cell.names)
any(cell.name.counts > 1)
cell.name.counts[cell.name.counts > 1]
```

**Comment by mojaveazure** [comment]
What happens if you run this in a for loop?
```R
combined <- object_list[[1]]
for (i in 2:length(x = object_list)) {
  combined <- MergeSeurat(object1 = combined, object2 = object_list[[i]])
}

**Comment by ghoshal** [comment]
I get the following error in running this loop.

 Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

**Comment by ghoshal** [comment]
I solved the issue. I assigned the unique cell identifiers to cell.names, colnames(data) and row names (meta.data) slots. However, the colnames(onj@raw.data) slots remained the same as before and couldn't create the required matrix. Now MergeSeurat is working great.

Thanks,

Bibaswan

**Comment by ghoshal** [comment]
Hi,

I just noticed that using the following code when I am merging the obj@data and obj@raw.data slots are exactly same whereas I have normalized expression values in obj@data slot. 

combined <- object_list[[1]]
for (i in 2:length(x = object_list)) {
  combined <- MergeSeurat(object1 = combined, object2 = object_list[[i]])
}

Please let me know what I can do to solve this.

**Comment by satijalab** [comment]
You need to rerun NormalizeData after merging.

**Comment by ghoshal** [comment]
Hi,

I have normalized the individual samples using a combination of different methods and want to use this normalized data in the obj@data slot after merging and not do the Seurat normalization. Is this possible?

Biba

**Comment by satijalab** [comment]
We don't support this natively in Seurat. However you can use RowMergeSparseMatrices to merge the matrices on the obj@data slots, and place this merged matrix in merged.object@data

**Comment by ghoshal** [comment]
Awesome thanks
