### ISSUE TITLE
strip.suffix usage

### ISSUE THREAD

**Issue by jjyotikataria** [satijalab/seurat#4800]
Why is strip.suffix required while reading 10Xdata? What purpose it is used for?

@troels @mxposed @smoe @zeehio @maximilianh

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The parameter isn’t required but optional, in fact the default for the parameter is `FALSE.`

Best,
Sam

**Comment by andrewwbutler** [comment]
I'll just add that as per the docs:
>  strip.suffix    Remove trailing "-1" if present in all cell barcodes.
