### ISSUE TITLE
FindIntegrationAnchors error: Error in idx[i, ] <- res[[i]][[1]]

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4803]
I'm piggy-backing off of https://github.com/satijalab/seurat/issues/3930. I got the error they got, except when running FindIntegrationAnchors(). 

```
combo <- merge(sobj_tnbc, y = c(sobj_ER, sobj_her, sobj_lumb), add.cell.ids = c("TNBC", "ER", "HER","ERHER"))
head(combo@meta.data)

combo.split <- SplitObject(combo, split.by = "Patient")

combo.split <- lapply(X = combo.split, FUN = function(x) {
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = combo.split)
combo.split <- lapply(X = combo.split, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, npcs = 10, verbose = FALSE)
})

immune.anchors <- FindIntegrationAnchors(object.list = combo.split, anchor.features = features, 
                                         reduction = "cca", dims = 1:10)

> Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length
In addition: Warning message:
In FilterAnchors(object = object.pair, assay = assay, slot = slot,  :
  Number of anchor cells is less than k.filter. Retaining all anchors.

```
My dataset is very small (549 cells) and also TPM normalized, so I have a feeling that has something to do with it:

![image](https://user-images.githubusercontent.com/62159599/126079503-8536a9f5-f651-40d0-8e96-b9af43b1c67b.png)

![image](https://user-images.githubusercontent.com/62159599/126079550-01ca9100-36d5-4a10-b53d-a020d472f0b2.png)

I tried setting the k.anchor and k.filter to 10 (smaller than the smallest sample of 11), and the warning goes away, but the error remains

```
immune.anchors <- FindIntegrationAnchors(object.list = combo.split, anchor.features = features, 
                                         reduction = "cca", dims = 1:10, k.anchor = 10, k.filter = 10)
> Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length
```

Thanks for reading!

**Comment by ksaunders73** [comment]
I also want to add that I tried integrating this tiny dataset with five other much larger datasets (the next smallest of the five has around 1500 cells, and the largest has around 47k cells), and I think it is definitely the size of the dataset that is the issue and not the normalization, because when I removed this tiny 549 cell dataset, I was able to integrate the other 5 together (despite one of the 5 being FPKM normalized, but being larger at around 1700 cells).

**Comment by yuhanH** [comment]
hi @ksaunders73 
Could you have a try that `k.filter = NA` and leave k.anchor to default setting?

**Comment by ksaunders73** [comment]
Hello @yuhanH! This worked to get the FindIntegrationAnchors() working, but I had to change the k.weight parameter in IntegrateData() to smaller than the smallest numbered sample, or else I get the error from https://github.com/satijalab/seurat/issues/3930

**Comment by yuhanH** [comment]
Hi @ksaunders73 
You are right. In the `IntegrateData` function, we built a weight matrix between anchor cells and all other cells (k.weight). 
If the object has too few cells, it may end up with an error. Also, when the object with few cells, it will violate many assumptions in our integration framework.

**Comment by ksaunders73** [comment]
Thank you very much for your help @yuhanH !

**Comment by yuhanH** [comment]
Hi, @BridgeLeeH 
Maybe you can merge the small objects into the bigger one.

**Comment by vsarsani** [comment]
mapping.score.k = 80 solved it for me
