### ISSUE TITLE
Counting the no. of features/genes in the Seurat object

### ISSUE THREAD

**Issue by jjyotikataria** [satijalab/seurat#4804]
Hi @troels @mauriziopaul @smoe @maximilianh 

I downloaded the pbmc guided tutorial data and ran the following commands-

 pbmc.data <- Read10X(data.dir = "F:\\pbmc3k_filtered_gene_bc_matrices\\filtered_gene_bc_matrices\\hg19")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

Output:
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features, 0 variable features)

But when I observe the actual filtered folder: 
I did wc -l * to check the no. of lines; looks like there are 2700 barcodes corresponding to 2700 single cells but why the no. of features don't match? It shows 13714 in the Seurat object but with counting the no. of lines, it shows 32738.

  2700 barcodes.tsv
   32738 genes.tsv
 2286887 matrix.mtx

I checked with unique genes also, they don't match.

**Comment by mauriziopaul** [comment]
Hi @jjyotikataria,

I believe the count of lines in `genes.tsv` is equal to the number of unique ensembl IDs or features in the reference, but the count of features in your Seurat object is equal to the number of genes passing a threshold (nonzero expression in 3 or more cells).

```{R}
expression_matrix <- ReadMtx("filtered_gene_bc_matrices/hg19/matrix.mtx", cells="filtered_gene_bc_matrices/hg19/barcodes.tsv", features="filtered_gene_bc_matrices/hg19/genes.tsv")
nrow(expression_matrix)
# 32738
nrow(expression_matrix[rowSums(expression_matrix>0)>=3, ])
# 13714
```

I hope this helps.

Best,

Paul
