### ISSUE TITLE
Seurat graph class

### ISSUE THREAD

**Issue by samsong57** [satijalab/seurat#4806]
Apologies for a likely obvious question for some

How do I find out more about the structure of the Seurat graph class? Specifically I am trying to learn about the contents of the wsnn graph produced after `FindMultiModalNeighbours` accessed at `seurat_obj@graphs$wsnn`. 

This has several slots including `seurat_obj@graphs$wsnn@i`, `seurat_obj@graphs$wsnn@p` etc.. and I am trying to find their meaning

I have looked in:

 https://cran.r-project.org/web/packages/Seurat/Seurat.pdf

This said:

"Description
For more details, please see the documentation in SeuratObject 

See Also
    SeuratObject::Graph-class"

I tried `?SeuratObject` and `SeuratObject::Graph-class` on R but no luck

Thanks in advance for any help

**Comment by andrewwbutler** [comment]
Hi,

The docs for the `Graph` class can be found with `?SeuratObject::Graph`. It's essentially just a sparse matrix (`dgCMatrix`) with an extra option slot to keep track of what data was used to produce the `Graph`.  The `@i` and `@p` slots are coming from the `Matrix` class.
