### ISSUE TITLE
NormalizeData function not working on split dataset

### ISSUE THREAD

**Issue by noelletnw** [satijalab/seurat#4811]
Hello!

I am currently trying to analyze a dataset that I used split.by on to split by conditions. Before splitting, I can normalize the data and find variable features, but after splitting I get the following error:

Error in as(object = data, Class = "dgCMatrix") : 
  no method or default for coercing “list” to “dgCMatrix”

I've run this analysis on other datasets before and not had this problem, and from what I can tell the datasets seem the same. Here is what I did so far to get to this point. I have 28 samples, so I tried to simplify as much as possible to still get the point across, but I apologize in advance for the length:

#load in data
`data.2716.Cre.PBS <- Read10X(data.dir = "xx")
data.2716.Cre.PBS.viral <- Read10X(data.dir = "xx")
data.2716.dCre.PBS <- Read10X(data.dir = "xx")
data.2716.dCre.PBS.viral <- Read10X(data.dir = "xx)`

#convert data to Seurat object
`data.2716.Cre.PBS.full <- CreateSeuratObject(counts =data.2716.Cre.PBS, project = "2716", min.cells = 10)
data.2716.Cre.PBS.viral.full <- CreateSeuratObject(counts =data.2716.Cre.PBS.viral, project = "2716", min.cells = 10)
data.2716.dCre.PBS.full <- CreateSeuratObject(counts =data.2716.dCre.PBS, project = "2716", min.cells = 10)
data.2716.dCre.PBS.viral.full <- CreateSeuratObject(counts =data.2716.dCre.PBS.viral, project = "2716", min.cells = 10)`

#isolate cell barcodes
`barcodes.2716.Cre.PBS.full <- rownames(data.2716.Cre.PBS.full@meta.data)
barcodes.2716.Cre.PBS.viral.full <- rownames(data.2716.Cre.PBS.viral.full@meta.data)
barcodes.2716.dCre.PBS.full <- rownames(data.2716.dCre.PBS.full@meta.data)
barcodes.2716.dCre.PBS.viral.full <- rownames(data.2716.dCre.PBS.viral.full@meta.data)`

#convert barcode lists to dataframes to append as metadata
`barcodes.2716.Cre.PBS.full <- data.frame(barcodes.2716.Cre.PBS.full, row.names = barcodes.2716.Cre.PBS.full)
barcodes.2716.Cre.PBS.viral.full <- data.frame(barcodes.2716.Cre.PBS.viral.full, row.names = barcodes.2716.Cre.PBS.viral.full)
barcodes.2716.dCre.PBS.full <- data.frame(barcodes.2716.dCre.PBS.full, row.names = barcodes.2716.dCre.PBS.full)
barcodes.2716.dCre.PBS.viral.full <- data.frame(barcodes.2716.dCre.PBS.viral.full, row.names = barcodes.2716.dCre.PBS.viral.full)`

#append barcodes as metadata to Seurat object
`data.2716.Cre.PBS.full$barcode.library <- barcodes.2716.Cre.PBS.full
data.2716.Cre.PBS.viral.full$barcode.virus <- barcodes.2716.Cre.PBS.viral.full
data.2716.dCre.PBS.full$barcode.library <- barcodes.2716.dCre.PBS.full
data.2716.dCre.PBS.viral.full$barcode.virus <- barcodes.2716.dCre.PBS.viral.full`

#merge replicates (I have 28 samples, so above has been shortened for simplicity. I merged the replicates into cre.PBS, cre.PBS.virus, dCre.PBS, and dCre.PBS.virus here)

#Remove cells that have more than 5% mito genes and that are > 2 stdev above the mean number of nCount_RNA (UMIs)
`cre.pbs[["percent.mt"]] <- PercentageFeatureSet(cre.pbs, pattern = "^mt-")
dCre.pbs[["percent.mt"]] <- PercentageFeatureSet(dCre.pbs, pattern = "^mt-")
cre.pbs.virus[["percent.mt"]] <- PercentageFeatureSet(cre.pbs.virus, pattern = "^mt-")
dCre.pbs.virus[["percent.mt"]] <- PercentageFeatureSet(dCre.pbs.virus, pattern = "^mt-")`

`cre.pbs.filtered <- subset(cre.pbs, subset = nCount_RNA < (mean(cre.pbs$nCount_RNA)+3*sd(cre.pbs$nCount_RNA)) & percent.mt<5)
dCre.pbs.filtered <- subset(dCre.pbs, subset = nCount_RNA < (mean(dCre.pbs$nCount_RNA)+3*sd(dCre.pbs$nCount_RNA)) & percent.mt<5)
cre.pbs.virus.filtered <- subset(cre.pbs.virus, subset = nCount_RNA < (mean(cre.pbs.virus$nCount_RNA)+3*sd(cre.pbs.virus$nCount_RNA)) & percent.mt<5)
dCre.pbs.virus.filtered <- subset(dCre.pbs.virus, subset = nCount_RNA < (mean(dCre.pbs.virus$nCount_RNA)+3*sd(dCre.pbs.virus$nCount_RNA)) & percent.mt<5)`

#merge Cre and dCre into singular data set
`PBS <- merge(cre.pbs.filtered, y = dCre.pbs.filtered)
PBS.virus <- merge(cre.pbs.virus.filtered, y = dCre.pbs.virus.filtered)`

#find cells from library that were infected with virus and append to Seurat object (here I am subsetting only a portion of my `sequenced cells based on overlapping barcodes)
overlap.barcodes.PBS <- (PBS.final@meta.data$barcode.library %in% PBS.final@meta.data$barcode.virus)

PBS.final$overlapping.barcodes <- overlap.barcodes.PBS`

#subset only those cells that were infected by virus into new Seurat object
`Idents(PBS.final) <- "overlapping.barcodes"

PBS.final.viral <- subset(PBS.final, idents = "TRUE")`

#split by condition for integrated analysis
`PBS.final.viral.split <- SplitObject(PBS.final.viral, split.by = "virus")`

#NormalizeData
`PBS.final.viral.split <- NormalizeData(PBS.final.viral.split)`

I have run NormalizeData  on PBS.final and PBS.final.viral before splitting, and do not have any issues running it. The DefaultAssay for the split PBS.final.viral dataset is 'RNA'.

Alternatively, would it be legitimate to run the normalization before splitting the dataset? I'm fine doing this way, but would like to understand the error nonetheless.

Thank you so much for your help!

**Comment by andrewwbutler** [comment]
Hi,

You are getting this error because `NormalizeData` expects a Seurat object to be passed to the `object` parameter (the first parameter), where as you are passing a **list** of Seurat objects. If you want to run `NormalizeData` on a list of objects, you'll need to use something like `lapply`. E.g.

```R
PBS.final.viral.split <- lapply(X = PBS.final.viral.split, FUN = NormalizeData)
```
In this case, it doesn't really matter if you run `NormalizeData` before or after splitting the object into a list of objects as that function operates on a per-cell level. You will get the same results either way.
