### ISSUE TITLE
MapQuery() error

### ISSUE THREAD

**Issue by JPGranizo** [satijalab/seurat#4812]
Hi! 

I am facing a similar issue as reported in  #3930  and #4803 when using FindTransferAnchors and  MapQuery as detailed in the Multimodal Mapping Vignette from Seurat 4:

This error appears after running MApQuery().
`Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length`

Some of my samples have very low cell numbers (N=49), which is why I assume that the error could possibly fixed in a similar manner as reported in #3930 by decreasing, for example, k.filter argument, which is by default 200.

anchors <- list()
 for (i in 1:length(batches)) {
   anchors[[i]] <- FindTransferAnchors(
     reference = reference,
     query = batches[[i]],
    normalization.method = "SCT",
     k.filter = NA,
     reference.reduction = "spca", 
     reference.neighbors = "spca.annoy.neighbors", 
     dims = 1:50,
     k.filter = 40
   )
 }

When defining k.filter = 40 as in the example above, I get the following error message:

`Error in FindTransferAnchors(reference = reference, query = batches[[i]],  : 
  formal argument "k.filter" matched by multiple actual arguments`

I would appreciate any advice how to get this working.
Thank you very much

**Comment by mhkowalski** [comment]
Hi- you have the k.filter argument twice, which is why you are getting the error about multiple arguments. Can you try removing either the `k.filter=NA`  or the `k.filter=40` argument?

**Comment by JPGranizo** [comment]
Thanks! This resolved the error `formal argument "k.filter" matched by multiple actual arguments`.

But independent of k.filter setting, similar to reports in #3930 and #4803 I have still the problem with the following error when running MapQuery() : ` Error in idx[i, ] <- res[[i]][[1]] : number of items to replace is not a multiple of replacement length`

Any ideas how to solve that? The code I used is copied below following the Multimodal Mapping Vignette from Seurat 4:

anchors <- list()
for (i in 1:length(batches)) {
  anchors[[i]] <- FindTransferAnchors(
    reference = reference,
    query = batches[[i]],
    normalization.method = "SCT",
    k.filter = 45,
    reference.reduction = "spca", 
    reference.neighbors = "spca.annoy.neighbors", 
    dims = 1:50
  )
}


for (i in 1:length(batches)) {
  batches[[i]] <- MapQuery(
    anchorset = anchors[[i]], 
    query = batches[[i]],
    reference = reference, 
    refdata = list(
      celltype.l1 = "celltype.l1",
      celltype.l2 = "celltype.l2", 
      predicted_ADT = "ADT"),
    reference.reduction = "spca",
    reduction.model = "wnn.umap"
  )
}

**Comment by yuhanH** [comment]
Hi, @JPGranizo 
do you still see the error when you set k.filter to NA?

**Comment by JPGranizo** [comment]
Hi @yuhanH
yes,  I still get the error when k.filter=NA. This problem only occurs if there are small batches of about 50 cells. 
For now, I combined the data to larger "batches", which are not completely pure. But at least the error is not coming up any more. It would be great if there is a solution, however, to also integrate smaller batches.

**Comment by yuhanH** [comment]
HI, @JPGranizo 
Glad that you get the solution. Here is a similar issue https://github.com/satijalab/seurat/issues/4803
Generally, if the object containing few cells, you may consider to leave them outside the integration framework. 
Since our framework uses many KNN steps, very small batches will be hard to be integrated.
