### ISSUE TITLE
Cluster/UMAP inconsistency after CITE-seq integration

### ISSUE THREAD

**Issue by Jpol07** [satijalab/seurat#4815]
I have several CITE-seq samples that I want to integrate. Each sample used the same panel of 23 antibodies.

I have used the very useful forum post #3890 to perform the following steps:

### Integrate samples based on RNA (after QC pre-processing)

`seurat.list <- lapply(seurat.list, SCTransform)`

`features <- SelectIntegrationFeatures(seurat.list, nfeatures=3000)`
`seurat.list<- PrepSCTIntegration(seurat.list, anchor.features = features)`
`immune.anchors <- FindIntegrationAnchors(seurat.list, normalization.method = "SCT",
anchor.features = features, dims = 1:50, reduction = "rpca", k.anchor = 20)`
`immune.combined.sct.rpca <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT", dims = 1:50)`

 `set.seed(42)`
`immune.combined.sct.rpca <- ScaleData(immune.combined.sct.rpca, verbose = FALSE)`
`immune.combined.sct.rpca <- RunPCA(immune.combined.sct.rpca, npcs = 50, verbose = FALSE)`

### Integrate samples based on ADTs

`seurat.list<- lapply(seurat.list function(x) {
  DefaultAssay(x) <- 'ADT'
  VariableFeatures(x) <- rownames(x)
  NormalizeData(x, assay='ADT', normalization.method = 'CLR', margin=2) 
  } )`

`features <- rownames(seurat.list[[1]][['ADT']])`
`immune.anchors.adt <- FindIntegrationAnchors(object.list = seurat.list, normalization.method = "LogNormalize",
    anchor.features = features, dims = 1:10, reduction = 'rpca', k.anchor =20)`
`immune.combined.adt <- IntegrateData(anchorset = immune.anchors.adt, normalization.method = "LogNormalize", dims=1:10)`

`immune.combined.adt <- ScaleData(immune.combined.adt, verbose = FALSE)`

### Integrate RNA and ADT using WNN

`immune.combined.sct.rpca[["IADT"]] <- immune.combined.adt[["integrated"]]`
`immune.combined.sct.rpca <- RunPCA(immune.combined.sct.rpca, assay='IADT', npcs = 10, reduction.name = 'pca.IADT')`

`immune.combined.wnn.rpca <-  FindMultiModalNeighbors(immune.combined.sct.rpca, reduction.list = list('pca','pca.IADT'), dims.list = list(1:50, 1:10))`

`immune.combined.wnn.rpca <- RunUMAP(immune.combined.wnn.rpca, nn.name = 'weighted.nn', reduction.name = 'wnn.umap', reduction.key = 'wnnUMAP_')`
`immune.combined.wnn.rpca <- FindClusters(immune.combined.wnn.rpca, graph.name = 'wsnn', algorithm=1, resolution=0.5, verbose = F,random.seed = 2021)`

#Visualise clusters on UMAP:

`DimPlot(immune.combined.wnn.rpca, reduction= 'wnn.umap', label=T)`

![image](https://user-images.githubusercontent.com/87704607/126331530-900698d9-5df3-4ad4-900a-903035345214.png)

The concern I have is that cluster 7 and 0 are intermixed on the UMAP, in fact cluster 7 (green) is also found above 1 and 3. I understand there is never perfect agreement between cluster assignment and UMAP visualisation but I have never seen this type of appearance before. Furthermore, when using `FindConservedMarkers()` to look for DE genes, I cannot find any reliable markers for clusters 0 or 7 for example. 

I have tried varying cluster resolution, cluster algorithm and PC dims. **So next I am trying to understand more deeply the underlying process here. I understand that the WNN algorithm produces a KNN graph that can be used as input downstream for clustering and as input to UMAP. However, in the code above the input to `RunUMAP` is the neighbour-class object 'weighted.nn' and the input to `FindClusters` is the graph-class object 'wsnn'. How are 'weighted.nn` and `wsnn` related to one another? I can see the `weighted.nn` object contains, for each cell, distances of the 20 nearest cells, but I can't seem to relate this to the output I see in the graph-class object**

Any help appreciated, apologies for the long post

**Comment by yuhanH** [comment]
Hi, 
`weighted.nn` is the weighted KNN. `wsnn` is the shared nearest neighbors from `weighted.nn`.
One suggestion to figure out cluster0 and 7. You can split the integrated objects and then perform WNN and UMAP individually. Then you can see if cluster0 and 7 still have similar issues.

**Comment by Jpol07** [comment]
Hi Yuhan, thank you for explaining the `weight.nn` vs `wsnn` disparity 

I will proceed with your suggestion, but can you explain a little more what you mean when you say 'split the integrated objects'? How should I split them?

Thanks again

**Comment by nandini0910** [comment]
Hi @Jpol07! I have two questions regarding your analysis.
1. Did you run scTransform before integrating the data?
2. Is it okay to run ScaleData() on the resulting integrated seurat object like you did for both modalities (ADT and RNA)?
