### ISSUE TITLE
AddModuleScore() Error on integrated dataset: Error in sample.int(length(x), size, replace, prob) :    cannot take a sample larger than the population when 'replace = FALSE'

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4819]
Hello!

I am wanting to run AddModuleScore() to an integrated dataset (I used the non-SCTransform pipeline), but it returns the following error:

```
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'
```

Here is what I did to integrate the dataset:

```
combo <- merge(Dataset1, y = c(Dataset2, Dataset3, Dataset4, Dataset5, Dataset6), 
               add.cell.ids = c("1", "2", "3", "4", "5", "6"))
head(combo@meta.data)

mito.genes <- grep(pattern = "^MT\\.", x = rownames(combo@assays[["RNA"]]), value = TRUE)
print(mito.genes)
mito.genes <- grep(pattern = "^MT-", x = rownames(combo@assays[["RNA"]]), value = TRUE)
print(mito.genes)

combo.split <- SplitObject(combo, split.by = "Patient")

combo.split <- lapply(X = combo.split, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = combo.split)
combo.split <- lapply(X = combo.split, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, npcs = 10, features = features, verbose = FALSE)
})

immune.anchors <- FindIntegrationAnchors(object.list = combo.split, anchor.features = features, 
                                         reduction = "cca", dims = 1:10, k.anchor = 10)
immune.combined <- IntegrateData(anchorset = immune.anchors, k.weight = 50)

DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 50, verbose = FALSE)

immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:17)
immune.combined <- FindClusters(immune.combined, resolution = 1)
umap.method = 'umap-learn'
metric = 'correlation'
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:17)


#module score ---------------------------------------------------------------------------------

tnbclist <- list(c("FABP7", "TSPAN8", "CYP4Z1", "HOXA10", "CLDN1",
                   "TMSB15A", "DEPP1", "TRPV6", "HOXA9", "ATP13A4",
                   "GLYATL2", "RP11-48O20.4", "DYRK3", "MUCL1", "ID4", "FGFR2",
                   "SHOX2", "Z83851.1", "CD82", "COL6A1", "KRT23", "GCHFR",
                   "PRICKLE1", "GCNT2", "KHDRBS3", "SIPA1L2", "LMO4", "TFAP2B",
                   "SLC43A3", "FURIN", "ELF5", "C1ORF116", "ADD3", "EFNA3",
                   "EFCAB4A", "LTF", "LRRC31", "ARL4C", "GPNMB", "VIM", 
                   "SDR16C5", "RHOV", "PXDC1", "MALL", "YAP1", "A2ML1",
                   "RP1-257A7.5", "RP11-353N4.6", "ZBTB18", "CTD-2314B22.3", "GALNT3",
                   "BCL11A", "CXADR", "SSFA2", "ADM", "GUCY1A3", "GSTP1",
                   "ADCK3", "SLC25A37", "SFRP1", "PRNP", "DEGS1", "RP11-110G21.2",
                   "AL589743.1", "ATF3", "SIVA1", "TACSTD2", "HEBP2"))

immune.combined <- AddModuleScore(object = immune.combined, features = tnbclist, name = "TNBC_List", search = TRUE)  
```

My datasets range from about 1500 to 47k cells, and all are in counts format except for one which is FPKM normalized.

Thanks for reading!

**Comment by ksaunders73** [comment]
Setting the assay to RNA allowed it to run, but shouldn't the integrated assay be used?

**Comment by heineike02** [comment]
I had this issue too - but setting the assay to RNA did not allow it to run.  Does anyone know more about what causes this error?

**Comment by ksaunders73** [comment]
@heineike02 if you used SCT setting the assay to SCT worked for me

**Comment by heineike02** [comment]
I didn't try that but thanks for the advice.  I did increase my features all the way to 80 (increasing to 85 broke it again for me), so I still think it is something about the number of genes available in each expression level bin.

**Comment by yuhanH** [comment]
Hi, @ksaunders73 
I also suggest you set the assay to RNA. Could you have a check if all genes you listed existed in your RNA assay?

**Comment by ksaunders73** [comment]
@yuhanH Sure! How do you do that?

**Comment by yuhanH** [comment]
`setdiff(tnbclist[[1]], rownames( immune.combined[['RNA]] ) )`
The above command can return the genes not in the RNA assay.

**Comment by ksaunders73** [comment]
Hello @yuhanH ! They are all in my assay except three of the genes

```
setdiff(tnbclist[[1]], rownames( immune.combined[['RNA']] ) )

[1] "DEPP1"         "RP11-48O20.4"  "CTD-2314B22.3"
```

**Comment by yuhanH** [comment]
You can remove these three genes from your list and then have a try on  `AddModuleScore `

**Comment by ksaunders73** [comment]
Hello @yuhanH ! 

Sorry for the late reply, but the module score works as long as I set the assay to `RNA`, and does not work even if I remove the genes not present if the assay isn't `RNA` (in my case, that would be the `integrated `assay)

**Comment by yuhanH** [comment]
Hi, @ksaunders73 
You are right. If you use `integrated` assay, your target genes should be all in the integrated assay. 
We suggest you use RNA assay to do these similar downstream analysis.

**Comment by ice4prince** [comment]
> Hi, @ksaunders73 You are right. If you use `integrated` assay, your target genes should be all in the integrated assay. We suggest you use RNA assay to do these similar downstream analysis.

Hi YuhanH,

I have the same issue. I have rename the 'integrated' assay to 'RNA' assay and confirmed that all the gene markers are in my data. However, I still have this problem. Please help me out!

Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'

**Comment by wjyin01** [comment]
> > Hi, @ksaunders73 You are right. If you use `integrated` assay, your target genes should be all in the integrated assay. We suggest you use RNA assay to do these similar downstream analysis.
> 
> Hi YuhanH,
> 
> I have the same issue. But my data is a CyTOF data. I have assay CyTOF and integrated. I have rename the 'integrated' assay to 'RNA' assay and confirmed that all the gene markers are in my data. However, I still have this problem. Does that because CyTOF data is different from RNA data? Please help me out!
> 
> Error in sample.int(length(x), size, replace, prob) : cannot take a sample larger than the population when 'replace = FALSE'

Hi, I have the same issue. Have you solved it now?

**Comment by xz289** [comment]
I got the same issue with CYtof data, the same error with seurat v5.
Any updates for this issue?

**Comment by theheking** [comment]
I found that it is due to the combination of the arguments nbin and ctrl. Nbin means the number of bins to aggregate expression and ctrl is the number of features from the same bin. If you have your nbins * ctrl is higher than the number of features in your RNA assay.
