### ISSUE TITLE
How to retrieve total gene numbers per cluster

### ISSUE THREAD

**Issue by sameerh** [satijalab/seurat#4820]
Hi,

 I am able to get the number of cells per cluster. But I would like to get the number of genes per cluster. Can anyone suggest me how to do this?

Thanks!

**Comment by saketkc** [comment]
I assume by number of genes per cluster you mean number of expressed genes per cluster. The `nFeature_RNA` column in `object@meta.data` has this information for individual cells.

**Comment by sameerh** [comment]
Thanks Saketkc!
I get the number of genes per cell. But wanted to know if there is a quick way to get number of genes per cluster from seurat.
