### ISSUE TITLE
how to merge subset back to previous integrated data

### ISSUE THREAD

**Issue by lxcfuji** [satijalab/seurat#4821]
Hi 
I have a large dataset that has 10 clusters (cell type 1, 2...9,X), and I subset one of the clusters (cell type X) to perform another rounds of clustering and identified 3 cell types (cell type 1,2,3) which is also shown in my large dataset (NOT new cell types). 
Now, I want to merge my sub-cluster back to previous data with assigned cell types, what is the best way to do it? Should I use integration?

**Comment by andrewwbutler** [comment]
Hi,

It sounds like just merging the subset back in with `merge`  is what you are looking for here. For a longer discussion on integration versus merging, see [this](https://github.com/satijalab/seurat/discussions/3998) post.
