### ISSUE TITLE
Best practice to demultiplex samples labeled with two or more HTOs?

### ISSUE THREAD

**Issue by naity** [satijalab/seurat#4822]
Hi Seurat team,

The `HTODemux` function works great for datasets where each sample is labeled with one HTO. I was wondering what's the best way to demultiplex samples labeled with 2 or more HTOs? 

For samples labeled with 2 HTOs, I could get away with using the "doublets" identified by `HTODemux` that are positive for 2 HTOs. However, `HTODemux` would not be able to flag real doublets that could be positive for 4 or more hashtags as it generates classifications with at most 2 HTOs.

I would love to hear your thoughts and suggestions on this. 

Thanks very much,
Yuan

**Comment by yuhanH** [comment]
hi 
Do you mean you used two HTOs to label one sample? 
If so, maybe you can merge those two HTOs into one HTO and get the singlets for this merged HTO. Then split the merged HTO into two individual HTOs and run `HTODemux` again.
