### ISSUE TITLE
How to perform unsupervised cluster analysis in one selected cluster

### ISSUE THREAD

**Issue by JoaoGabrielMoraes** [satijalab/seurat#4823]
Hello, 

I have identified 23 clusters in my dataset. I believe that one of these "23 clusters" consist of more than one cell type, so I would like to select this one cluster for further analysis. More specifically, I would like to perform unsupervised cluster analysis only on this selected cluster to evaluate whether I can break it down in few more clusters of interest. 

Any suggestions on how to do that? 

Thank you very much!

**Comment by jaisonj708** [comment]
You can subset out the cluster and re-cluster (and optionally re-run PCA and other preprocessing steps before reclustering)
