### ISSUE TITLE
How to solve these two warning messages? (Problem conducting Integration tutorial)

### ISSUE THREAD

**Issue by Wooseok-Kim98** [satijalab/seurat#4824]
1. Warning in if (is.na(desc)) { :
    the condition has length > 1 and only the first element will be used
2. Warning in theta.ml(y = y, mu = fit$fitted): iteration limit reached

When knitting code from "Introduction to scRNA-seq integration(https://satijalab.org/seurat/articles/integration_introduction.html)
hundreds of these two warning messages above appeared.

Is there any additional codes for eliminating those warnings?

the zip file contains RMD and HTML files

[scRNA_Study.zip](https://github.com/satijalab/seurat/files/6860515/scRNA_Study.zip)

**Comment by saketkc** [comment]
This is a warning and not an error and indicates the theta esimation procedure for negative binomial does not reach convergence (and is mostly harmless). For a faster estimation when running SCTransform, we recommend installing [glmGamPoi](https://bioconductor.org/packages/release/bioc/html/glmGamPoi.html) and running `SCTransform(object, method="glmGamPoi")`.
