### ISSUE TITLE
Compare different replicates via pseudo-bulk PCA

### ISSUE THREAD

**Issue by ms-gx** [satijalab/seurat#4825]
We have scRNA data of 8 different conditions and every condition has two biological replicates which in turn have 2 technical replicates (8x2x2). Now I want to check that the four replicates (2x2) from every condition are similar (compared to the other sampels).

My idea is to (1) generate pseudo-bulk counts and then (2) run a PCA on the counts to see if the replicates cluster nicely.

First question: Do you have another idea on how to compare the biological/technical replicates than the one stated above?

Second question: How would you recommend to do the (1) pseudo-bulk step and (2) the PCA step on the pseudo-bulk data? Or different: is there already something in place?

**Comment by saketkc** [comment]
You could also start by creating a merged seurat object and doing one round of preprocessing and clustering to see if there are indeed batch effects. Doing a PCA on pseudobulk counts should also be able to capture this. 

For pseudobulking counts, you can use [AggregateExpression](https://satijalab.org/seurat/reference/aggregateexpression) resulting in 32 pseudobulks with associated metadata and then run it through standard seurat processing to get the PCA.
