### ISSUE TITLE
Split dotplot

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#4826]
I was wondering whether it is possible to plot this split dotplot (in this case, half of a dot represents mRNA levels while the other half about protein)?
![image](https://user-images.githubusercontent.com/4110443/126654762-9de9bb40-ade5-4131-b6d3-410e36b5f986.png)

This is useful in two places: 1. when we are visualizing mRNA and protein levels of a same group of genes 2. when we are comparing two conditions (control PBMC vs stimulated PBMC etc.). Because it would avoid duplicating the gene/cell type names and save half the space compared to this one:
![image](https://user-images.githubusercontent.com/4110443/126655187-3aaf5c3d-3122-47a3-9864-48eb5ea47142.png)

Thanks

**Comment by jaisonj708** [comment]
Yes you can do this by passing a named list of features
See here for an example: https://github.com/satijalab/seurat-private/pull/338

**Comment by brianpenghe** [comment]
Your link doesn't work. Could you fix it? Thanks
