### ISSUE TITLE
FindVariableFeature() during data integration

### ISSUE THREAD

**Issue by aelhossiny** [satijalab/seurat#4828]
Hi awesome Seurat folks! 

So I have a thought regarding the datasets integration [vignette](https://satijalab.org/seurat/articles/integration_introduction.html). I saw that you split the object to `CTRL` and `STIM`, then you selected HVG in both datasets then used `SelectIntegrationFeatures` afterwards to select features that are repeatedly variable across datasets. I am quite confused here whether we are ignoring genes that are variable between conditions (CTRL and STIM). I mean, imagine a case in which a gene might be consistent and not detected as HVG within a condition, however it's highly variable between conditions. Since I have a similar case, in which my batches/datasets are the different conditions, wouldn't it be better to first detected HVG between datasets and form which we `SelectIntegrationFeatures()`?

**Comment by saketkc** [comment]
Hi @aelhossiny, the rationale to focus on variable features is to focus on features that define the biological state in a dataset. The Integration step looks for anchors between the two datasets that essentially correspond to same biological state. If a feature is variable across (but not within) the datasets, it is more reflective of contributing to different biological states (and hence not a useful feature for defining anchors).

**Comment by aelhossiny** [comment]
Yes, that makes sense now! Thank you!
