### ISSUE TITLE
Label transfer between seurat objects

### ISSUE THREAD

**Issue by jd10020** [satijalab/seurat#4829]
Hi,

I have previously annotated a scRNAseq dataset from 5 patients at 3 different timepoints which was of the whole transcriptome using the 10x genomics platform. Now, in order to increase the resolution of my analysis I have the same data from the same cells/ timepoints/ patients but this time we used the targeted platform of 10x Genomics. Now when I am annotating the data I wanted my cells to have the same annotation as in the whole transcriptome data. I wanted to know how can I transfer the cell names from my whole transcriptomic data to the targeted data when they are 2 separate seurat objects. I was thinking maybe to get a matrix with cell IDs and their respective annotation and then transfer this to the targeted data as the cell IDs remain the same. If that is possible how can I do it?

I look forward to hearing from you.

Diego

**Comment by saketkc** [comment]
If I understand it correctly, the barcodes remain the same between the targeted and the original scRNA experiment. In that case, you should be able to simply extract the metadata from the first experiment, for example the `seurat_clusters` as: `original_seurat_object@meta.data[, c('seurat_clusters'), drop=FALSE]` and then add it to the new object: 

```
common_barcodes <- intersect(colnames(new_obj), colnames(original_seurat_object))
new_obj <- AddMetaData(new_obj, metadata=original_seurat_object@meta.data[common_barcodes, c('seurat_clusters'), drop=FALSE])
```
