### ISSUE TITLE
MultiCCA vs RunCCA

### ISSUE THREAD

**Issue by dingying85** [satijalab/seurat#483]
![screenshot from 2018-05-18 14-18-35](https://user-images.githubusercontent.com/5166102/40258438-25f3732a-5ae1-11e8-8887-0e312b1376e8.png)

Hi Seurat Developpers,

I tried to use MultiCCA to combine three blood scRNASEQ samples and it does not seem to align very well. I use 30 CCA's. I am wondering is running MultiCCA on sample a, b,c equivalent to running RunCCA on a and b first then running RunCCA on a+b and c? Will later be better aligned?

Do you have any suggestions on how to improve alignment? What is the maximum datasets MultiCCA can handle well and give good alignment results? Thanks in advance.

**Comment by andrewwbutler** [comment]
Hi,

I would recommend looking more closely into your selection of CCs. Perhaps try lowering the number you're including. It would also be worth investigating the gene set you're using for CCA.

`RunMultiCCA` on a+b+c is not going to be the same as `RunCCA` on a+b then c. For more than two datasets, you should be using `RunMultiCCA`.
