### ISSUE TITLE
cluster resolution change causes cells from different clusters to join

### ISSUE THREAD

**Issue by fataltes** [satijalab/seurat#4830]
Hi,

when I run FindClusters for different resolutions I get cells clustered in different clusters in lower resolution put in the same cluster in higher resolution. This is certainly unexpected but do you have any explanations about it?

the way I look at the distribution of original clustering (with lower resolution) into new clustering (with higher resolution) is through this piece of code:
as.data.frame(cls) %>% group_by(V1, V2) %>% summarise(cnt = n()) %>% group_by(V1) %>% mutate(dist = round(cnt/sum(cnt), 2))

Assuming V1 and V2 are cluster labels on the same cells for different clustering resolutions (for example .5 and .7)

Thank you

**Comment by jaisonj708** [comment]
This can happen when your clusters aren't particularly significant, ie. at a certain point increasing the resolution leads to somewhat arbitrary clusters. Unfortunately clustering algos can't easily output statistical significance, but you can see which resolution best matches your biological expectations and leads to meaningfully distinct clusters (as judged by DE or some other method)
