### ISSUE TITLE
Clustering with Integration method

### ISSUE THREAD

**Issue by WesDe** [satijalab/seurat#4831]
Hello,

I am trying to integrate two sn-RNA sequencing (40K and 18K cells from 10X Chromium and DropSeq technology) together in order to obtain a reference for spatial transcriptomics deconvolution. 

![Clust0](https://user-images.githubusercontent.com/18364708/126759477-26df8d27-2dc3-4177-b225-8ab6b278be86.png)

However I am having issue with the integration and clustering result.  I expected to obtain plenty of overlapping cluster between the data.

![Clust_1](https://user-images.githubusercontent.com/18364708/126757141-485ecd41-9ac2-47f2-9300-528b7a20d173.png)

I also checked the annotation from both data to see if my integration was relevant with former annotation. 

![Clust_2](https://user-images.githubusercontent.com/18364708/126758204-04231643-f361-4c06-aee1-1e4eba8c5b3b.png)

The comparison between clustering result and former annotation for the first data (40K cells) seems relevant but it doesn't seem right with the second data. Cells from the same annotation are not clustered together

![Clust_3](https://user-images.githubusercontent.com/18364708/126759540-2553d86b-f21d-488d-aae4-b4fdfe45a500.png)

I tried a lot of parameters (different var.to.regress, resolution, npcs) but it did not improve the result. I have tried to integrate other data and I had no issue to integrate them with the first data.

In the publications, the first data has been analyzed with Seurat while the second one has been analyzed with Pangoda2. 

If you have some pointers to share in order to help me to understand what is going on or what i did wrong.
Best,
WesDe

**Comment by saketkc** [comment]
Hi @WesDe, would you be able to copy the code you used for integration here?

**Comment by WesDe** [comment]
Hi @saketkc,
Sure.

`
# Load library
library(Seurat)
library(magrittr)
library(dplyr)

# Read file
K1 <- readRDS("K1.rds")
K1$id <- "K_1"

K2_r<-read.table("K2.tsv.gz",header=T,row.names=1)
 ##Convert it to a SeuratObject
K2<-CreateSeuratObject(counts=K2_r,project = "K_2",min.cells = 3,min.features = 400)
K2$id <- "K_2"
K2$orig.ident<-as.factor(unlist(lapply(colnames(kidney.Lake),function(x) unlist(strsplit(x,"_"))[1]))) #Had to change orig.ident to get sample id because annotated cluster information were stored there
K2$celltype<-strsplit(attr(x = kidney.Lake$orig.ident, which = "names") , "_", fixed=T)%>% sapply( "[", 1 )

kidney.list<-c(K1,K2)

# SCT
print("Run SCT through lapply")
kidney.list <- lapply(X = kidney.list, FUN = function(x) {
  x <- SCTransform(x, method="glmGamPoi", vars.to.regress = c('nFeature_RNA', 'nCount_RNA', 'orig.ident'), verbose = FALSE,variable.features.n = 5000)
  s.genes <-cc.genes$s.genes
  g2m.genes<-cc.genes$g2m.genes
  x <- CellCycleScoring(x,  s.features = s.genes,  g2m.features = g2m.genes,  assay = 'SCT',  set.ident = TRUE)
  x <- SCTransform(x,assay = "RNA", method = "glmGamPoi", vars.to.regress = c('nFeature_RNA', 'nCount_RNA', 'orig.ident','S.Score', 'G2M.Score'), verbose = FALSE,variable.features.n = 5000)

})

# Integration
print (" SeletIntegrationFeature")
features <- SelectIntegrationFeatures(object.list = kidney.list, nfeatures = 5000)
print (" PrepSCTIntegration")
kidney.list <- PrepSCTIntegration(object.list = kidney.list, anchor.features = features)
print("RunPCA through lapply")
kidney.list <- lapply(X = kidney.list, FUN = RunPCA, features = features,npcs=150)
print (" FindIntegrationAnchors")
kidney.anchors <- FindIntegrationAnchors(object.list = kidney.list, normalization.method = "SCT", anchor.features = features,dims=1:150,reduction = "rpca")
print (" Integrated data")
kidney.combined.sct <- IntegrateData(anchorset = kidney.anchors, normalization.method = "SCT",dims=1:150)
print (" PCA")
kidney.combined.sct <- RunPCA(kidney.combined.sct, npcs=150, verbose = FALSE)
kidney.combined.sct <- RunUMAP(kidney.combined.sct, reduction = "pca", dims = 1:150)
kidney.combined.sct <- FindNeighbors(kidney.combined.sct, dims = 1:150)# dims is associated with the PCs, can also be change
kidney.combined.sct <- FindClusters(kidney.combined.sct, resolution = 1)
# Visualization
DimPlot(kidney.combined.sct, reduction = "umap", pt.size = 0.5,label=TRUE,cols=smycols2) + NoLegend()
DimPlot(kidney.combined.sct, reduction = "umap", group.by = "id", pt.size = 0.5,label=TRUE,cols=smycols2) + NoLegend()
DimPlot(kidney.combined.sct, reduction = "umap", group.by = "celltype", pt.size = 0.5,label=TRUE,cols=smycols2) + NoLegend()
DimPlot(kidney.combined.sct, reduction = "umap", group.by = "celltype",split.by="id", pt.size = 0.5,label=TRUE,cols=smycols2) + NoLegend()

saveRDS(kidney.combined.sct, file = "Integrated_data.rds")`

**Comment by saketkc** [comment]
Are the orig.ident here donors? You should not be regressing out `nFeature_RNA` and `nCount_RNA`. SCT model is designed to handle these as covariates, internally.

```
x <- SCTransform(x, method="glmGamPoi", vars.to.regress = c('nFeature_RNA', 'nCount_RNA', 'orig.ident'), verbose = FALSE,variable.features.n = 5000)

```

**Comment by WesDe** [comment]
The second datasets is composed of 47  samples from 27 different experiments and 15 different individuals. So some samples come from the same individual but not the same tissue location.

**Comment by saketkc** [comment]
Were you able to try my suggestion above?

**Comment by WesDe** [comment]
Hi,

Sorry for the late reply. I was able to try your suggestion, I also added some variation in parameters based on what I have found in different issues.  Among them, I have reduced npcs to 30, change k.anchors value to 40 and add return.only.var.genes = F in the SCTransform.

Results are far better than previous analysis, I have more aligned cluster between the two samples. 

![KCA_La2](https://user-images.githubusercontent.com/18364708/127816780-8d32199e-7222-48c2-96e3-e270bc00dc91.png)

However cells of the left sample are more dispersed than the right sample and so the original cluster they are associated with.

![KCA_La3](https://user-images.githubusercontent.com/18364708/127816906-92d2ead9-9735-47b5-b5eb-87f7f9379de6.png)

I am still trying to identify which parameters I need to customize to improve the clustering.

**Comment by saketkc** [comment]
If you can email me your objects at schoudhary@nygenome.org, I will be happy to take a look. You can choose to anonymize the genes if you wish.

**Comment by WesDe** [comment]
I improved the result by removing sample that contained less than 150 cells.

![Dataset1](https://user-images.githubusercontent.com/18364708/128670371-add85cb3-ba93-43f0-b63c-5446ced6369c.png)

However cluster in the second dataset are still dispersed.

![Dataset2](https://user-images.githubusercontent.com/18364708/128670419-44322af8-381c-4106-a449-88befca37cc1.png).

I send you information about my analysis.

Thanks for you help

**Comment by WesDe** [comment]
I read a recent post about using Harmony for the batch correction. I tried and the clustering was better than before.

![Harmony1](https://user-images.githubusercontent.com/18364708/128832301-b12e6af2-3a65-4fe5-8b64-2aee56fbf486.png)

However cell type from the K2 are still dispersed. I guess it can be expected because the original data was processed through pagoda2 and not Seurat.

![Harmony2](https://user-images.githubusercontent.com/18364708/128832326-21ac0683-21bc-430c-9df1-e2050d99f705.png)

**Comment by saketkc** [comment]
Thanks, I'll take a look.

**Comment by rsatija** [comment]
I'll just add that the visual dispersion of the cluster is not something to be concerned about. When you integrate a small dataset with a larger one, the cells from the small dataset will (by definition) need to occupy a larger visual component of the UMAP plot.

These integration results look reasonable. If you're interested, you can also integrate the dataets by mapping to our kidney Azimuth reference at:
https://azimuth.hubmapconsortium.org/ (see Human - Kidney)
