### ISSUE TITLE
Violin Plot - plot equal cell number question

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [satijalab/seurat#4834]
Hey,
I have two questions regarding plotting using the VlnPlot() function:
In the following plot for example I plotted a selected gene across all of my clusters and I chose ascending order in terms of averege expression level. However comparing the visualization in cluster 1 vs cluster 6 vs cluster 0 one cannot really tell which cluster shows higher expression of the gene because in both cases most of the cells show zero expression and as a result there are no violin bodies formed.
![image](https://user-images.githubusercontent.com/60395255/126777147-40b84a91-5f88-4ac8-82a9-cd30ff7fd5c7.png)

What would you suggest in order to avoid this? Here are some thoughts:

-I was wondering if there is a way to plot equal number of cells within all the clusters, so that one doenst get misled by the fact that more dots are shown for a cluster (without this reflecting the avg expression level in the cluster as is the case here for cluster 6 and 0)
-or if I can plot only the cells with expression >0 in order to get the violin distribution within the positive cells only?

I would appreciate any input, 
thanks a lot!

**Comment by jaisonj708** [comment]
You can always run differential expression tests between two clusters if you'd like to assess significance. I don't think any manipulations of the visualization would help reveal significant differences. And I would keep all cells rather than subsetting to positive expression only (the 0s are important given the high sparsity of single cell data). Overall DE might be the best option here

**Comment by christoforos-dimitropoulos** [comment]
> You can always run differential expression tests between two clusters if you'd like to assess significance. I don't think any manipulations of the visualization would help reveal significant differences. And I would keep all cells rather than subsetting to positive expression only (the 0s are important given the high sparsity of single cell data). Overall DE might be the best option here

Thanks for your reply. I was wondering how one can behave for features that dont pop up as DE genes, what would be the best way to visualise differences in the expression?
