### ISSUE TITLE
Show cluster by condition and samples

### ISSUE THREAD

**Issue by amufaamo** [satijalab/seurat#4837]
I have four samples (Control1, Control2, Case1, Case2). I want to merge these data, and show UMAP colored by samples (4 colors) and conditions(2 conditions). How can I show the UMAP?

**Comment by WesDe** [comment]
Hi,

Not a dev here but you can use the option split.by and group.by in the Dimplot command. You can see some examples [there](https://satijalab.org/seurat/articles/integration_introduction.html). 

Best,
WesDe

**Comment by amufaamo** [comment]
OK, thank you.
