### ISSUE TITLE
Should you remove genes in the integration pipeline

### ISSUE THREAD

**Issue by BiostormSilver** [satijalab/seurat#4838]
Hi, I'm working with single cell RNA-seq data for 6 different datasets ( 3 WT and 3 KO biological replicates), I'm using the general integration pipeline to cluster the data and then perform DE and some other downstream analyses. However, the pipeline doesn't say whether or not you should filter genes and if you do when and how. Removal of genes after initial creation of the object is supposedly not meant to be done as in https://github.com/satijalab/seurat/issues/147, however I don't know if that should apply to datasets at the start of the integration pipeline. 

I'm not sure if leaving in genes that are not expressed in many cells if any affects the analysis, however I want to perform an analysis afterwards using MAGIC and the package seems to need the lowly expressed genes to be filtered out.

So, can you clarify whether or not gene removal should be performed, the effect leaving genes in would have and if it should be done then how.

**Comment by torkencz** [comment]
Hi, integration should be dependent on the features you provide as your integration features. You do not have to remove genes from your object necessarily. Once you have your clusters defined based on the integrated dataset you can always go back to your original objects with your integrated annotations and do downstream analysis on those for instance (without losing  genes that you want to keep in).
