### ISSUE TITLE
TCR analysis with Seurat

### ISSUE THREAD

**Issue by beginner984** [satijalab/seurat#4839]
Hello all

I have **_scRNA-seq 10x PBMCs_** of cancer survivors (cancer free after 5 years) and controls. 

My boss has asked me

T cell analysis – differences between samples (scRNAseq)
Can we identify a/b or g/d pairs for individual T cells

Is there anyway to do TCR analysis just by having scRNA-seq data from using Seurat or I need TCR sequencing data itself?

Thank you so much for any link, idea, tutorial, paper, etc

**Comment by yuhanH** [comment]
Hi
Seurat doesn't have the function to impute TCR based on the scRNA-seq data. You may need to try some other packages. 
Thanks.
