### ISSUE TITLE
FeatureHeatmap: subset clusters plotted

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#484]
@leonfodoulian
(could be part of #121)?

expecting this script:
```R
FeatureHeatmap(x, features.plot = c("Aqp4"), idents.use = c("1","12"), pt.size = .5)
```
to return a plot of Aqp4 expression, showing only clusters 1 and 12. However, all clusters shown in graph. How is ident.use being used? How do I define a specific set of clusters to be plotted?

metadata looks like:

```R
> head(x@meta.data)
                         nGene nUMI orig.ident replicate sex percent.mito res.1
Z1_F_F1_AAAGCAAAGGCGCTCT  2066 4527         Z1        F1   F   0.09277667     6

> head(x@ident)
Z1_F_F1_AAAGCAAAGGCGCTCT Z1_F_F1_AAAGTAGAGGCGATAC Z1_F_F1_AAAGTAGGTTCAGACT Z1_F_F1_AACCATGTCTATCCTA 
                       6                        6                        9                       14 
 Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16  
```

**Comment by leonfodoulian** [comment]
@AndyR2,

Should be fixed when PR #494 gets accepted and merged. You can then install the [development version of Seurat](https://satijalab.org/seurat/devinstall.html). 

Best,
Leon
