### ISSUE TITLE
Regarding text alignment in stacked violin plot

### ISSUE THREAD

**Issue by jjyotikataria** [satijalab/seurat#4840]
I have plotted data qc for my three samples and it appears to me that when I am trying to align the qc variables name to be straight and horizontal, it is disturbing the alignment of whole text in the plots. 

Command used:
VlnPlot(merged_obj,group.by = "orig.ident", stack=T,features = feats, pt.size = 0.1) & theme(axis.text.y = element_text(size = rel(2)),axis.text.x = element_text(size = rel(2)),axis.ticks.x = element_line(size = rel(2))) +theme(axis.title = element_text(size=30)) + theme(axis.text.x = element_text(size=30, color="black")) + theme(axis.text.y = element_text(size=30, color="black"))+ theme(legend.text=element_text(size=20, color="black")) + theme(legend.title=element_text(size=30, color="black"))+theme(text = element_text(size = 30, face = "bold")) 

Can we make it parallel to the graph's x axis? @troels @mxposed @zeehio @smoe @maximilianh 

nGene    nUMI   percent.mt  percent.rb

![image](https://user-images.githubusercontent.com/58770228/126898850-ac02e2c6-7ed3-4086-81e1-3eb4e8e140f8.png)

**Comment by saketkc** [comment]
Since ploitting functions in Seurat return ggplot2 objects, you can modify them downstream. In this case you would want to change the `angle` of your `element_text', see examples here: https://ggplot2.tidyverse.org/reference/guide_axis.html
