### ISSUE TITLE
Which slot to use for subsetting positive cells after SCTransform?

### ISSUE THREAD

**Issue by arvand1992** [satijalab/seurat#4843]
Hi, 
I'm trying to get the subset of cells that are positive for specific gene marker after performing SCTransform (e.g. Cd4). 
However, using the following codes give me different number of positive cells: 

DefaultAssay(sueratobject) <- "SCT"
subset (x = seuratobject, Cd4>0, slot="data") --> 470 cells
subset (x = seuratobject, Cd4>0, slot="scale.data") --> 650 cells

I'm wondering which one is more accurate representative of the Cd4 positive cells, "data" or "scale.data" slot?

Thank you.

**Comment by liuxl18-hku** [comment]
Assume you are using default transformation method `sctransform::vst()` with default paramters, the resulted pearson residuals are stored in `scale.data` slot, the `data` slot is log-transformed (`log1p`) of original or corrected (if `do.correct.umi` was set) UMI counts.

Not sure under which context you want `Cd4 > 0`. If you want to keep cells with __Cd4 expressed__ and __concern about the sequencing depth bias between libraries__, you may use `count` slot with `do.correct.umi` set. But pls be noted that, based on my understanding, Seurat is not using this count (as well as the `log1p` transformed) in downstream analysis  #3923.

Using "RNA" assay may be a more straightforward approach to exclude "unexpressed" cells.

bless~

**Comment by saketkc** [comment]
`subset (x = seuratobject, Cd4>0, slot="scale.data") --> 650 cells` would end up exlcuding all cells where the pearson residual (scale.data slot) is <0. If you want to exclude cells where the "expression" of CD4 is zero, you would want to use the count lot of SCT assay or the RNA assay. I agree with @liuxl18-hku's response. Regarding using SCT corrected counts for downstream analysis, you could do that by specifying the `assay` in any downstream function (such as FindMarkers).
