### ISSUE TITLE
DietSeurat Not Removing Assays

### ISSUE THREAD

**Issue by oerin18** [satijalab/seurat#4844]
Hello,

I'm very new to scRNA-seq (started a month ago for my internship) and I've been analyzing a dataset using Seurat (Version 4.0.3) to cluster and analyze pancreatic islets. I integrated my datasets using `SCTransform` and the integration vignette, created and merged clusters based on expectations of pancreatic cell types, and used `Subset` to pull out my Beta-cell cluster for further sub-clustering. I'm currently trying to "reintegrate" my data to redo subclustering (I know it's not recommended, but my subclusters seem to be suffering from batch effect) and I want to clear the SCT and Integrated Assays so I can start off from a clean slate. However, despite using `DietSeurat`, I'm still able to see the assays when I click on the object in the environment tab. And when I just open the object in Console, it shows it as the same. I've written what I see below (forgive the formatting, I'm new to github as well):

>**DietSeurat(test.beta.subclusters, counts = TRUE, data = TRUE, scale.data = FALSE, assays = "RNA")**
An object of class Seurat 
21044 features across 630 samples within 1 assay 
Active assay: RNA (21044 features, 0 variable features)
**>test.beta.subclusters**
An object of class Seurat 
39107 features across 630 samples within 3 assays 
Active assay: RNA (21044 features, 0 variable features)
 2 other assays present: SCT, integrated
 2 dimensional reductions calculated: pca, tsne
 
Does anyone else have this issue and/or know how to fix it? Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  The issue is just that you need to save object back to environment like other steps.
```
test.beta.subclusters  <- DietSeurat(test.beta.subclusters, counts = TRUE, data = TRUE, scale.data = FALSE, assays = "RNA")
```

Best,
Sam

**Comment by oerin18** [comment]
Thank you so much, Sam! It worked perfectly.

**Comment by samuel-marsh** [comment]
Happy to help!
