### ISSUE TITLE
Differential gene expression testing on a specific set of genes

### ISSUE THREAD

**Issue by EAC-T** [satijalab/seurat#4846]
Hi all,

Is there a way to do differential testing on a specific set of genes? 
I did some pathway analysis and found that let's say 1 pathway is significantly different between my 2 clusters, this pathway has around 100 genes, can I now do DGE on those 100 only? is that even valid statistically ?

Thanks

**Comment by liuxl18-hku** [comment]
Pass your candidate gene list to `features = ` parameter of `FindMarkers()`. Some of genes may not pass the pre-filter of the function: `logfc.threshold = 0.25` and `min.pct = 0.1`.

bless~

**Comment by yuhanH** [comment]
As @liuxl18-hku mentioned, you can set your features in `features =` parameter of `FindMarkers()`
Thanks for your reply.
