### ISSUE TITLE
Why inputting the same variable features (or scale.data) with different order would cause different output in RunPCA() ?

### ISSUE THREAD

**Issue by ZhuoliHuang** [satijalab/seurat#4848]
RunPCA will be run using the variable features which must be present in the scaled data for the PCA assay by defult. 

If we input the same set of variable features with different order (e.g. set1:gene A, gene B, gene C; set2: gene C, gene B, gene A),the output cell.embeddings matrix of RunPCA() would be totally different.

Similarly, If we input the same scale.data matrix with different  column(cell) order ,the output cell.embeddings matrix of RunPCA() would be totally different.

Why inputting the same variable features (or scale.data) with different order would cause different output in RunPCA() ?

**Comment by andrewwbutler** [comment]
Hi,

`RunPCA` by default uses an approximate algorithm (`irlba`) for computing the PCs. We do not sort/order the matrix based on gene or cell names before running it so providing these in different orders could result in a sign flip for some PC embeddings but I wouldn't expect them to be "totally different". Can you provide a reproducible example where you observe "totally different" results?

**Comment by ZhuoliHuang** [comment]
> Hi,
> 
> `RunPCA` by default uses an approximate algorithm (`irlba`) for computing the PCs. We do not sort/order the matrix based on gene or cell names before running it so providing these in different orders could result in a sign flip for some PC embeddings but I wouldn't expect them to be "totally different". Can you provide a reproducible example where you observe "totally different" results?

Thanks for your reply.  The description of "totally different"  result was improper, but it actually has some differences except for the sign flip.  This can be tested with pbmc_small dataset in Seurat as following script:
`library(Seurat)
data.matrix <- as.matrix(pbmc_small@assays$RNA@counts)
data.matrix_2 <- data.matrix[,sample(colnames(data.matrix),80)]
table(data.matrix == data.matrix_2[,colnames(data.matrix)])

pbmc_small_1 <- CreateSeuratObject(counts = data.matrix)
pbmc_small_1 <- NormalizeData(pbmc_small_1, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_small_1 <- FindVariableFeatures(pbmc_small_1, selection.method = "vst")
pbmc_small_1 = ScaleData(pbmc_small_1)
pbmc_small_1 <- RunPCA(pbmc_small_1, verbose = FALSE)

pbmc_small_2 <- CreateSeuratObject(counts = data.matrix_2)
pbmc_small_2 <- NormalizeData(pbmc_small_2, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_small_2 <- FindVariableFeatures(pbmc_small_2, selection.method = "vst")
pbmc_small_2 = ScaleData(pbmc_small_2)
pbmc_small_2 <- RunPCA(pbmc_small_2, verbose = FALSE)

mtx1 <- as.matrix(pbmc_small_1@reductions$pca@cell.embeddings)
mtx2 <- as.matrix(pbmc_small_2@reductions$pca@cell.embeddings)

table (mtx2[row.names(mtx1),] == mtx1)
table (round(mtx2[row.names(mtx1),],3) == round(mtx1,3))
table (abs(mtx2[row.names(mtx1),]) == abs(mtx1))
table (round(abs(mtx2[row.names(mtx1),]),3) == round(abs(mtx1),3))
table (round(abs(mtx2[row.names(mtx1),]),10) == round(abs(mtx1),10))`

**Comment by ZhuoliHuang** [comment]
> Hi,
> 
> `RunPCA` by default uses an approximate algorithm (`irlba`) for computing the PCs. We do not sort/order the matrix based on gene or cell names before running it so providing these in different orders could result in a sign flip for some PC embeddings but I wouldn't expect them to be "totally different". Can you provide a reproducible example where you observe "totally different" results?

**Thank you for your reply. The description of 'totally different' result is improper, but  it actually has some differences except for the sign flip. This can be reproduced with following R script:**

```
library(Seurat)
data.matrix <- as.matrix(pbmc_small@assays$RNA@counts)
data.matrix_2 <- data.matrix[,sample(colnames(data.matrix),80)]
table(data.matrix == data.matrix_2[,colnames(data.matrix)])

pbmc_small_1 <- CreateSeuratObject(counts = data.matrix)
pbmc_small_1 <- NormalizeData(pbmc_small_1, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_small_1 <- FindVariableFeatures(pbmc_small_1, selection.method = "vst")
pbmc_small_1 = ScaleData(pbmc_small_1)
pbmc_small_1 <- RunPCA(pbmc_small_1, verbose = FALSE)

pbmc_small_2 <- CreateSeuratObject(counts = data.matrix_2)
pbmc_small_2 <- NormalizeData(pbmc_small_2, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_small_2 <- FindVariableFeatures(pbmc_small_2, selection.method = "vst")
pbmc_small_2 = ScaleData(pbmc_small_2)
pbmc_small_2 <- RunPCA(pbmc_small_2, verbose = FALSE)

mtx1 <- as.matrix(pbmc_small_1@reductions$pca@cell.embeddings)
mtx2 <- as.matrix(pbmc_small_2@reductions$pca@cell.embeddings)

table (mtx2[row.names(mtx1),] == mtx1)
table (round(mtx2[row.names(mtx1),],3) == round(mtx1,3))
table (abs(mtx2[row.names(mtx1),]) == abs(mtx1))
table (round(abs(mtx2[row.names(mtx1),]),3) == round(abs(mtx1),3))
table (round(abs(mtx2[row.names(mtx1),]),10) == round(abs(mtx1),10))
```

**Comment by andrewwbutler** [comment]
Thanks for the example. These kinds of differences are expected when using `irlba` on matrices with different column orders. E.g.

```R
set.seed(2)
mat1 <- matrix(rnorm(1:10000), 100)
col.order <- sample(1:ncol(mat1), ncol(mat1))
mat2 <- mat1[, col.order]

res1 <- irlba(mat1)$v[col.order, ]
res2 <- irlba(mat2)$v
table(res1 == res2)
head(res1-res2)
```
If you want reproducible results, I would recommend not adjusting the input data orderings.
