### ISSUE TITLE
Why are G1/S genes from Tirosh et al. designated as S-phase markers in Seurat?

### ISSUE THREAD

**Issue by ms-gx** [satijalab/seurat#4849]
`cc.genes$s.genes` from Seurat are identical to the G1/S-Phase markers form Tirosh et al. as far as I understand (https://science.sciencemag.org/highwire/filestream/677381/field_highwire_adjunct_files/9/aad0501_Table_S5.xlsx).

So my questions:

1) Why do you designate them as S-phase markers?

2) In the manual you say (https://satijalab.org/seurat/articles/cell_cycle_vignette.html#assign-cell-cycle-scores-1): 

> First, we assign each cell a score, based on its expression of G2/M and S phase markers. These marker sets should be anticorrelated in their expression levels, and cells expressing neither are likely not cycling and in G1 phase.

 -> What is the reasoning behind this? Because it is in contrast to the G1/S-phase designation from the Tirosh et al. paper, isn't it?

**Comment by rsatija** [comment]
Thanks for the question. In our opinion, the Tirosh cell cycle genes that are G1/S phase are most representative of S-phase, as they are heavily enriched for DNA synthesis genes. Cells that have not passed the G1/S checkpoint are unlikely to express these genes at high levels. But it is a question of semantics to some degree (the G2/M phase genes are likely most representative of M phase as well).
