### ISSUE TITLE
Finding genes expressed in one cluster but absent in another cluster

### ISSUE THREAD

**Issue by manjumoorthy95** [satijalab/seurat#4850]
I would like to know if we can find those genes that are expressed in 1 cluster but absent in another cluster ( or maybe absent in rest all clusters ) ?

**Comment by torkencz** [comment]
Hi, you should use FindMarkers and FindAllMarkers. Documentation can be found here: https://www.rdocumentation.org/packages/Seurat/versions/4.0.3/topics/FindAllMarkers
https://satijalab.org/seurat/reference/findmarkers .
