### ISSUE TITLE
Change Cluster Names get Different DE

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#4851]
Hello,

I have kept all of my clusters the same after normalization and such.  I have only changed the names around. Every-time I change names, I get different expression values when I do DE within each cluster between conditions.  I use the FindAllMarkers command, so I'm unsure why this is changing if the names of other clusters are being changed.  Thank you.

**Comment by aelias1** [comment]
I would like to add that some of the clusters I do understand will change as I combine names, but those that I have not changed the names of at all I'm confused as to why they changed.  For example Astrocyte_1 has different expression values now that I disentangled the Neuron cluster into a few different subtypes and renamed them.

**Comment by andrewwbutler** [comment]
Hi,

Can you clarify your question with some reproducible code examples? Renaming clusters should not change DE results.

**Comment by aelias1** [comment]
Hi Andrew,

My code was initially:

new.cluster.idsZhou <- c("MFOL_1", "Neuron", "Neuron", "Mature Oligodendrocyte", "Neuron", "Astrocyte_3", "Neuron", "Microglia", "Neuron", "Neuron",
                      "Neuron", "OPC_1", "Neuron", "Neuron", "Neuron", "Immune Cells", "Neuron", "Neuron", "Neuron", "Neuron",
                      "Neuron", "MFOL_2", "Neuron", "Neuron", "Neuron", "Neuron", "MFOL_3", "Neuron", "Neuron", "Neuron",
                      "Neuron", "Neuron", "Neuron", "Neuron", "VLMC", "Neuron", "Neuron", "Neuron", "Neuron", "Neuron",
                      "Neuron", "Neuron", "Neuron", "Neuron", "Neuron", "Vascular Endothelium", "Neuron", "Neuron", "COP", "Neuron",
                      "Neuron", "Astrocyte_1", "Immature Neuron", "Pericyte", "Neuron", "Neuron", "Neuron", "Neuron", "Neuron", "Neuron",
                      "Neuron", "OPC_2", "Neuron", "Neuron", "OPC_3", "Neuron", "Astrocyte_2", "Neuron")
names(new.cluster.idsZhou) <- levels(Zhou)
Zhou <- RenameIdents(Zhou, new.cluster.idsZhou)
DimPlot(Zhou, reduction = "umap", label = TRUE, pt.size = 0.5, label.size=2.5, repel = TRUE)


Zhou$celltype.condition <- paste(levels(Zhou), Zhou$orig.ident, sep = "_")
Idents(Zhou) <- "celltype.condition"

diff.condition.Astrocyte1 <- FindMarkers(Zhou, ident.1 = "Astrocyte_1_WT5XAD_Zhou_Male", ident.2 = "Astrocyte_1_WT_Zhou_Male", verbose = FALSE)
head(diff.condition.Astrocyte1, n = 15)
write.csv(diff.condition.Astrocyte1, file="Zhou_DEbyAge_Male_Astrocyte1_June232021.csv")
 

for example.

My updated code separated out all of the neuron clusters into individual cell types:

new.cluster.idsZhou <- c("MFOL_1", "L2/3 IT", "L6 IT", "Mature Oligodendrocyte", "L6 CT", "Astrocyte_3", "Sst", "Microglia", "L5 IT", "L5 IT",
                          "L4", "OPC_1", "L6 IT", "L4", "L2/3 IT", "Immune Cells", "PValb", "L5 IT", "L5 IT", "L4",
                          "L5 IT", "MFOL_2", "Lamp5", "Sst", "Vip", "NP", "MFOL_3", "Meis2", "L6 IT", "Lamp5",
                          "L2/3 IT", "L4", "L6b", "L5 PT", "VLMC", "L5 IT", "Vip", "L6b", "L6 IT", "Lamp5",
                          "VLMC", "Sst", "L4", "Vip", "L5 IT", "Vascular Endothelium", "L6 IT", "L5 IT", "COP", "L4",
                          "Unknown", "Astrocyte_1", "Immature Neuron", "Pericyte", "Sst", "Unknown", "PValb", "PValb", "Unknown", "PValb",
                          "L5 PT", "OPC_2", "Lamp5", "Sst", "OPC_3", "L5 PT", "Astrocyte_2")
names(new.cluster.idsZhou) <- levels(Zhou)
Zhou <- RenameIdents(Zhou, new.cluster.idsZhou)
DimPlot(Zhou, reduction = "umap", label = TRUE, pt.size = 0.5, label.size=2.5, repel = TRUE)

diff.condition.Astrocyte1 <- FindMarkers(Zhou, ident.1 = "Astrocyte_1_WT5XAD_Zhou_Male", ident.2 = "Astrocyte_1_WT_Zhou_Male", verbose = FALSE)
head(diff.condition.Astrocyte1, n = 15)
write.csv(diff.condition.Astrocyte1, file="Zhou_DEbyAge_Male_Astrocyte1_July272021.csv")
 

Now even though I didn't touch the Astrocyte_1 cluster, the DE values are different.  Thank you so much! The first chunk of code was all that was changed throughout all of the process.

**Comment by andrewwbutler** [comment]
Hi,

It looks like you have different vector lengths for the first and second `new.cluster.idsZhou` (67 vs 68).  I'm not sure what the original number of idents that you want to rename is but these should match.
