### ISSUE TITLE
Combining 

### ISSUE THREAD

**Issue by behrouzsh** [satijalab/seurat#4853]
Hello Seurat team,
Thanks for your work on developing seurat, I have a question:
I am working on Two Different datasets from different single cell technologies, 
each technology provides two sets of datasets for control vs treatment. So
tech1:
control: dataset1, dataset2, dataset3
treatment: dataset1, dataset2, dataset3
tech2:
control: dataset1, dataset2, dataset3
treatment: dataset1, dataset2, dataset3
Ideally I want to combine treatments together and compare those to control.
I am merging dataset1, dataset2, dataset3 in each control and integrate between control1+control2. 
I also do the same for treatment.
I am able to do batch effect removal in the control and treatment successfully, meaning cell types in the two technologies are clustered together. 
but when I want to integrate the two integrated control and treatment seurat objects, I am not able to do the batch effect removal. There are three assays (RNA, SCT and integrated) in each control and treatment objects and none of them can do batch effect removal. That means there is no overlap between clusters in the two technologies. So control and treatment in one technology is in the left and control and treatment in another technology is on the right hand side of umap. This should not happen and at least the control clusters should have overlaps between the two technologies. 
Any help or suggestions about the process of integration of the two integrated object is greatly appreciated.
This is the process for integration of control and treatment seurat objects.

```r
# -------------------------------------------------------------------
# -------------------------------------------------------------------
# -------------------------------------------------------------------
DefaultAssay(integrate.integrated_stage_3.normal) <- "integrated" # or "RNA" or "SCT"
DefaultAssay(integrate.integrated_stage_3.tumor) <- "integrated" # or "RNA" or "SCT"
integrate.list <- c(integrate.integrated_stage_3.normal, integrate.integrated_stage_3.tumor)
for (i in 1:length(integrate.list)) {
    integrate.list[[i]] <- SCTransform(integrate.list[[i]], method = "glmGamPoi",  #verbose = FALSE)
}
# -------------------------------------------------------------------
# -------------------------------------------------------------------
# -------------------------------------------------------------------
integrate.features <- SelectIntegrationFeatures(object.list = integrate.list, nfeatures = 3000)
integrate.list <- PrepSCTIntegration(object.list = integrate.list, anchor.features = integrate.features, 
    verbose = TRUE)
integrate.anchors <- FindIntegrationAnchors(object.list = integrate.list, normalization.method = "SCT", anchor.features = integrate.features, verbose = TRUE)
integrate.integrated_stage_3 <- IntegrateData(anchorset = integrate.anchors, normalization.method = "SCT", 
    verbose = TRUE)
# -------------------------------------------------------------------
# -------------------------------------------------------------------
# -------------------------------------------------------------------
DefaultAssay(integrate.integrated_stage_3) <- "integrated"
integrate.integrated_stage_3 <- RunPCA(integrate.integrated_stage_3, verbose = FALSE)
integrate.integrated_stage_3 <- RunUMAP(integrate.integrated_stage_3, dims = 1:40, verbose = FALSE)
integrate.integrated_stage_3 <- FindNeighbors(integrate.integrated_stage_3, dims = 1:40, verbose = FALSE)
integrate.integrated_stage_3 <- FindClusters(integrate.integrated_stage_3, resolution = 0.5, verbose = FALSE) 
```

**Comment by timoast** [comment]
Rather than creating two separate integrated datasets and then trying to integrate them, I'd suggest first creating a list of all the objects you want to combine and running integration on that list. You can provide a sample tree if you want to control the order that objects are integrated (this would effectively allow you to first integrate all of the treatment and all of the control, then combine those).
