### ISSUE TITLE
Simpler way to get from Seurat object to creating DESeq2 object?

### ISSUE THREAD

**Issue by learning-MD** [satijalab/seurat#4856]
As someone who is still a relative novice with R, I really appreciate the user-friendliness of Seurat and what it allows me to do. I've been able to perform QC, cluster, and annotate my data based on the vignettes provided.

One question I had is: Is there a simple way to go from a merged Seurat object (e.g. containing 8 samples, 4 control and 4 disease) to a DESeq2 object for pseudobulk DEG analysis? I've been going through the excellent Harvard Chan tutorials, along with Seurat vignettes, (https://github.com/hbctraining/scRNA-seq_online/blob/master/lessons/pseudobulk_DESeq2_scrnaseq.md) but am struggling with some of the base R that seems to be required.

I've searched through a number of message boards and in the Seurat GitHub, but haven't come across this specific question - I apologize in advance if I somehow missed it. Thanks!

**Comment by torkencz** [comment]
Hi, you can use DEseq2 within Seurat to perform differential expression on given categories of cells (pseudobulk). You just need to set test.use="DEseq2" in FindMarkers or FindAllMarkers. You also have to have DEseq2 installed.

**Comment by ollieeknight** [comment]
Heya,

As it's my impression DESeq2 is pseudobulk testing, is there a way to specify which samples contribute towards the two conditions we're testing using this function? for example, sample1,sample2 are control, sample3,sample4 are stim

Best

Ollie
