### ISSUE TITLE
difference between data and scale.data slot of SCT transformed object

### ISSUE THREAD

**Issue by liuweihanty** [satijalab/seurat#4863]
Hi there! Just wondering what exactly is the difference between data and scale.data slot of a SCT transformed object, and which slot contains the normalized count? Thanks!

**Comment by saketkc** [comment]
For SCT assay:

- counts = corrected (effect of library size removed) counts 
- data = log1p(counts)
- scale.data = pearson residuals

See documentation [here](https://satijalab.org/seurat/reference/sctransform)

**Comment by liuweihanty** [comment]
Thank you very much @saketkc  for the reply! May I ask a follow up question:  I want to use the SCT data slot to calculate a cell-cell euclidean distance. However when I checked my data slot, I notice there are some 0s(picture attached). But since data slot is log1p() transformed already, shouldn't there be no 0s?  Thank you very much!
![Screenshot 2021-08-03 at 11 01 59](https://user-images.githubusercontent.com/43444815/128048268-79d8a6c4-2c65-4e63-82d5-7997f951612e.png)

**Comment by saketkc** [comment]
Hi @liuweihanty, data slot has 0s because these are `log1p` values of counts (zerors remain as such). As long as the distance matrix you are using is based on difference between two cells, the values wouldn't matter (0.001-0.001=0).

**Comment by liuweihanty** [comment]
@saketkc I see, thank you a lot!
