### ISSUE TITLE
Regress out cell cycle genes NOT affect final PCA or UMAP?

### ISSUE THREAD

**Issue by YichaoOU** [satijalab/seurat#4865]
Hello,

Following the cell cycle tutorial [here](https://satijalab.org/seurat/archive/v3.1/cell_cycle_vignette.html), after Re-Scaled the data by regressing out cell cycle differences (code below), I can see the PCA plot before and after are different (figure below).

```
merged_obj$CC.Difference <- merged_obj$S.Score - merged_obj$G2M.Score
merged_obj <- ScaleData(merged_obj, vars.to.regress = "CC.Difference",verbose=T,features = rownames(merged_obj),block.size=10000)
```

![image](https://user-images.githubusercontent.com/19987406/127618741-51096e76-aac2-4601-9bc4-6fe002a0f07a.png)

However, remember the above PCA plots were generated based on S and G2M genes, in the end, we should still use the old HVGs to make PCA plots and UMAP plots, right? So I did that, and found the UMAP plot is not changed. I think it is because the only difference between before and after cell cycle removal is this `ScaleData`. So I did take a look at `scale.data`, values are somewhat changed, but it didn't seem to affect PCA on HVGs and thus will not change UMAP. 

I attached the code below. I just want to know if I didn't anything wrong. 

Thanks,
Yichao

[cell_cycle.pdf](https://github.com/satijalab/seurat/files/6905889/cell_cycle.pdf)

**Comment by timoast** [comment]
In your code you regressed out the difference between the G2M and S phase scores, and I think the results are consistent with that (the main difference you see is G1 vs G2M/S phase cells). If you also want to remove the difference between cycling and non-cycling cells, you can regress out the cell cycle scores themselves (as shown in the linked vignette).

**Comment by YichaoOU** [comment]
@timoast 

Thanks for the quick reply. So `in the end, we should still use the old HVGs to make PCA plots and UMAP plots, right? `. The answer is Yes?

Thanks,
Yichao

**Comment by timoast** [comment]
Yes you should still use the variable genes for your analysis, not the cell cycle genes
