### ISSUE TITLE
How to flip the coordinates of dotplot

### ISSUE THREAD

**Issue by sameerh** [satijalab/seurat#4866]
Hi,
When plot seurat dotplot, i have the genes on x-axis and clusters on y axis. As the number of genes is very large, i would like to have the gene on y-axis rather than on x-axis. I tried coord_flip() to do this but did not work.
Do anyone has any suggestion on how to do this?

Thank you.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you post the full code you are running for `DotPlot`?  When I run following it works to flip the axes.

```
pbmc <- pbmc3k.SeuratData::pbmc3k.final
p1 <- DotPlot(pbmc, features = c("CD3E", "AIF1"))
p2 <- DotPlot(pbmc, features = c("CD3E", "AIF1")) + coord_flip()
p1+p2
```

![image](https://user-images.githubusercontent.com/38284410/127658141-5c71004b-eb97-4cd1-96dd-17f3ece54dd1.png)


Best,
Sam

**Comment by sameerh** [comment]
Thanks Sam! I tried the same by adding + coord_flip()at the end. My code is:
DotPlot(seurat_integrated, group.by = "Clustertype" , features = DEGs_identified, dot.min= 0.1, dot.scale = 5) + coord_flip()
I will try it once again.

**Comment by sameerh** [comment]
It worked for me. Thank you. I restarted R and came like a bang!

**Comment by sameerh** [comment]
Back again.
I tried to modify my script little bit use the average expression than Z-scaled coloring.
`DEGs_dotplot_splitSPEX <- DotPlot(seurat_integrated, assay = 'RNA',  features = DEGsNonspidroins_identified,  group.by = "GeneExpression" , cols = c("blue", "red"),dot.min= 0.1, dot.scale = 5) 
 DEGs_dotplot_splitSPEX$layers[[1]] <- NULL # remove original geom_point layer where the color scale is hard-coded to use scaled average expression
 DEGs_dotplot_splitSPEX <- DEGs_dotplot_splitSPEX + 
  geom_point(mapping = aes_string(size = 'pct.exp', color = 'avg.exp')) +
  guides(color = guide_colorbar(title = 'Average Expression')) + 
  theme(axis.text.x = element_text(angle=70)) 
DEGs_dotplot_splitSPEX <- plot(DEGs_dotplot_splitSPEX + labs(x="Genes", y= "Groups"))  + coord_flip()`

The cord_flip() did not work. Can you suggest me possible solution for this?

Thanks!

**Comment by saketkc** [comment]
@sameerh You can turn of the scaling by specifiying `scale=FALSE`. See documentation [here](https://satijalab.org/seurat/reference/dotplot)
