### ISSUE TITLE
Subseting cluster counts - negative values?

### ISSUE THREAD

**Issue by alhadjil** [satijalab/seurat#4871]
Hi,

I have analysed my dataset based on the very informative tutorial https://satijalab.org/seurat/articles/pbmc3k_tutorial.html 
I identified the clusters and assigned them to a cell-type. After that I want to extract the cell-type/cluster counts for pseudobulk differential gene expression analysis. For that I used `bcells.raw.data <- as.matrix(GetAssayData(all.combined, slot = "data")[, WhichCells(all.combined, ident = "B cells")])` based on these interaction tips https://satijalab.org/seurat/archive/v3.0/interaction_vignette.html. Interstingly, I had to change the `slot` to `"data"`, rather than to `"counts"`, as recommended in the tutorial. My matrix has negative values, which makes it hard for me to proceed with DESEq2 for DEG. Why would I have negative values? Is that expected? 

Any ideas? Thank you!

**Comment by MrModenait** [comment]
Dear @alhadjil,
Thank you for your question. May I ask you which assay you are pulling data from? May I also see your full code?
Best Regards,
Gustav C.

**Comment by alhadjil** [comment]
Dear @MrModenait,

thanks for your reply.

I use following dataset: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE145307

First I create for each of the 10x runs a Seurat Object, here only one example

> S1_D1 <- Read10X(data.dir = "../GSE145307_RAW/GSM4314548/")
> S1_D1 <- CreateSeuratObject(counts = S1_D1, project = "S1_D1", min.cells = 3, min.features = 200)

I then merge the objects that belong to the same condition. There are two conditions, which I label PRIMARY and SECONDARY.

> PRIMARY <- merge(P1_D1, y = c(P1_D3, P2_D1, P2_D5, P3_D1, P3_D2), add.cell.ids = c("P1_D1", "P1_D3", "P2_D1", "P2_D5", "P3_D1", "P3_D2"), project = "PRIMARY DENV")
> PRIMARY$stim <- "Primary DENV"
> PRIMARY[["percent.mt"]] <- PercentageFeatureSet(PRIMARY, pattern = "^MT-")
> VlnPlot(PRIMARY, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
> PRIMARY <- subset(PRIMARY, subset = nFeature_RNA > 200 & nFeature_RNA < 3000)
> PRIMARY <- NormalizeData(PRIMARY, normalization.method = "LogNormalize", scale.factor = 10000)
> PRIMARY <- NormalizeData(PRIMARY)
> PRIMARY <- FindVariableFeatures(PRIMARY, selection.method = "vst", nfeatures = 2000)

I then find anchors and integrate the two conditions

> find.anchors <- FindIntegrationAnchors(object.list = list(PRIMARY, SECONDARY), dims = 1:30)
> all.combined <- IntegrateData(anchorset = find.anchors, dims = 1:30)
> DefaultAssay(all.combined) <- "integrated"

The I scale , run pca, find neighbors and clusters

> all.combined <- ScaleData(all.combined, verbose = FALSE)
> all.combined <- RunPCA(all.combined, npcs = 30, verbose = FALSE)
> all.combined <- RunUMAP(all.combined, reduction = "pca", dims = 1:30)
> all.combined <- FindNeighbors(all.combined, reduction = "pca", dims = 1:30)
> all.combined <- FindClusters(all.combined,  resolution = 0.2)
> p1 <- DimPlot(all.combined, reduction = "umap",  group.by = "stim", label = FALSE, order = c("Primary DENV", "Secondary DENV"), cols = c("#ffa100", "#34567B")) + theme(title = NULL)
> p1[[1]]$layers[[1]]$aes_params$alpha = 1 
> plot(p1)
> p2 <- DimPlot(all.combined, reduction = "umap", label = TRUE) + NoLegend()
> plot_grid(p1, p2)
> DimPlot(all.combined, reduction = "umap", split.by = "stim")

Finally I want to extract the raw counts of a cluster, which ends up in a matrix with negative numbers.

> raw.data <- as.matrix(GetAssayData(all.combined, slot = "data")[, WhichCells(all.combined, ident = "1")])

**Comment by MrModenait** [comment]
Dear @alhadjil,

Thank you for your data. I have not looked through all of your code, but my hypothesis is that you are extracting data from the `Integrated` data assay. Are you familiar with Seurat assays? Each assay contains different slots such as `counts`, `data` and `scale.data`. The `Integrated` data is a heavily "corrected" assay and therefore has negative expression values, unlike the `RNA` assay which is what you are looking for. Your question has been answered before in these forums in [June 2019](https://github.com/satijalab/seurat/issues/1717) and in [July 2020](https://github.com/satijalab/seurat/issues/3334).
In brief, add DefaultAssay(all.combined) <- "RNA" before the final line of code to get you back to the main assay. Or set `assay = "RNA"` within `GetAssayData()`. The choice of `slot` is left up to you: if I recall correctly, `counts` is the number of mRNA reads, `data` is the logarithmed-and-normalised mRNA count (great for most plots) and `scale.data` is the expression but where each gene has been adjusted to a mean of 0 (great for `DoHeatmap`).  
Hope this helped!

Best Regards,
Gustav C.

**Comment by torkencz** [comment]
Hi, the data slot should be the log normalized data. In your case you need to switch back to your original RNA assay as opposed to the integrated, corrected assay. You can do that with the DefaultAssay (all.combined)<-"RNA" command.

**Comment by amisztak** [comment]
Ah, thank you!
Indeed, upon closer look there is 109 cells with negative values. 

Maybe someone will benefit from that:

Even though my assay says 'RNA' it is actually integrated data. Integration may introduce negative values to counts. Therefore, cytotrace may not be suitable for such datasets.

**Comment by amisztak** [comment]
> Hi, the data slot should be the log normalized data. In your case you need to switch back to your original RNA assay as opposed to the integrated, corrected assay. You can do that with the DefaultAssay (all.combined)<-"RNA" command.

Yes, I could do that if this was my data. Unfortunately all I have is dieted Seurat object with integrated data as RNA assay. Thanks for the suggestion anyhow :)
