### ISSUE TITLE
Diff between avg_log2FC and avg_diff in Seurat v4.0.3 FindMarkers()

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#4875]
Hi,

I was wondering whether someone could explain the difference between the `avg_log2FC` and `avg_diff` columns in the `FindMarkers()` output.  From my reading, the output of `FindMarkers()` gives an `avg_log2FC` column if run on the "data" slot and an `avg_diff` column when run on the "scale.data" slot.  I have generated a Seurat object with custom data in the "scale.data" slot, so I would like to fully understand the calculation.  It looks like `mean.fxn` is different depending on the input slot.

Is it just that the data in the "data" slot is already log transformed so this needs to be accounted for in `mean.fxn`?

```
mean.fxn <- mean.fxn %||% switch(
    EXPR = slot,
    'data' = function(x) {
      return(log(x = rowMeans(x = expm1(x = x)) + pseudocount.use, base = base))
    },
    'scale.data' = rowMeans,
    function(x) {
      return(log(x = rowMeans(x = x) + pseudocount.use, base = base))
    }
  )
```

Best wishes,
Lucy

**Comment by yuhanH** [comment]
HI,
You are right. Since data slot is mainly the log-normalized counts data, when we average those value, we first use `expm1` to convert to counts, then average (`rowMeans`), then `log` back.
