### ISSUE TITLE
Latent variables not accounted for in fold change calculation

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#4878]
Looking through the source code for differential expression, it appears that latent variables are only included in the p value calculations.  I believe they need to be considered in calculating fold change as well.  

My first thought is to use the residuals from a hurdle model (counts ~ latent.vars).   What are your thoughts?

**Comment by liuxl18-hku** [comment]
Not team member. Some thoughts for discussion purpose. My understanding is fold-change is a ratio of average counts or average normalized counts. Negative residuals may have some problems to calculate the average value.

Another possible approach is get "corrected" counts by reversing the regression model and then calculate fold-change based on "corrected" counts, but seems that not many people fancy that way.

**Comment by danielcgingerich** [comment]
@liuxl18-hku Ah, I see why taking fold change of residuals would be problematic.  To add on to your suggestion, I think that calculating fold change of the corrected counts would essentially yield the fold change due to latent variables alone, rather than the variables of interest. 
This could be useful as a null model though.  The true fold change could perhaps be calculated by dividing fold change of original normalized counts by the fold change of the corrected counts.  
FC = FC.counts / FC.corrected.counts

not sure though

**Comment by rsatija** [comment]
For model-based approaches, we could in princple compute corrected counts using the regression residuals, and then report the log-FC post correction. This is not a standard step in most workflows, and to avoid confusion, we currently report the logFC based on the original data in the assay.
