### ISSUE TITLE
AddModuleScore Not Seeing Features

### ISSUE THREAD

**Issue by oerin18** [satijalab/seurat#4881]
Hello--I'm new to scRNA-seq and using R, and I've been analyzing a dataset using Seurat (Version 4.0.3). Currently, I'm trying to attribute a score to each cell based on specific pathways using `AddModuleScore`. I've been able to attribute a score to each cell, but every gene set I input inevitably leads to this error: `Warning: The following features are not present in the object`. I've attempted to integrate all of the features (using the steps of the SCTransform Vignette) into my object before doing this, and I think I had some success with a single feature, I'm still missing some features when applying the score (I should also mention that `features.to.integrate` won't accept all of these genes, even if present in the object, but some definitely made it through). From what I know, at least one of the features left out is present within my Seurat object (though, I can't say it is expressed).

I also have some additional questions about using the `AddModuleScore` function.

My questions are as listed:

1. Why would features not be integrated into the dataset and then not used for `AddModuleScore`? Is there a way to avoid this? And is there a way for me to get a list of the genes left out (if the list is truncated in the error message)?
2. Is the SCT or RNA assay better to use for attributing this score? 
3. Is it recommended to use AddModuleScore for features only upregulated in a pathway or only downregulated so that they don't "cancel" each other out?
4. Would excluding genes because they are not seemingly present in the object hurt the validity of my data analysis using this score?

Below is my code, starting from SCTransform:

>allos.list <- lapply(X = allos.list, FUN = function(x){
    x <- SCTransform((x), variable.features.n = 3000, return.only.var.genes = FALSE) 
})

>generated.int.features <- SelectIntegrationFeatures(object.list = allos.list, nfeatures = 3000)

>allos.list.prep <- PrepSCTIntegration(object.list = allos.list, anchor.features = generated.int.features)

>allos.anchors <- FindIntegrationAnchors(object.list = allos.list.prep, normalization.method = "SCT", anchor.features = generated.int.features)

>comp.int.features <- c(generated.int.features, pro_genes, upr_genes, mat_genes)

>allo.smerged <- IntegrateData(anchorset = allos.anchors, normalization.method = "SCT", features.to.integrate = comp.int.features)

>allo.smerged <- RunPCA(allo.smerged, npcs = 30, verbose = FALSE)

>allo.smerged <- FindNeighbors(object = allo.smerged)

>allo.smerged <- FindClusters(object = allo.smerged, resolution = 0.5)

>allo.smerged <- RunTSNE(allo.smerged, reduction = "pca", dims = 1:9)

>DefaultAssay(allo.smerged) <- "RNA" 

>allo.smerged <- NormalizeData(object = allo.smerged, assay = "RNA")

>allo.smerged <- ScaleData(object = allo.smerged, assay = "RNA")

>uprtest <- list(upr_genes)

>allo.smerged <- AddModuleScore(allo.smerged, features = uprtest, assay = "SCT", name = "upr_score", search = TRUE)

>Warning: The following features are not present in the object: ASNS, CEBPB, EEF2, EIF4E, EXOSC2, H2AX, IARS1, MTREX, NFYB, NHP2, NPM1, PSAT1, RPS14, TARS1, TUBB2A, XBP1, YWHAZ, attempting to find updated synonyms
  |============================================================================================| 100%
>Found updated symbols for 1 symbols

Please let me know if you have any suggestions (relating to this issue or my code in general)--I appreciate all the help I can get. Thank you all so much.

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question. 

1. The reason certain genes might not be appearing in your SCT assay is if they are expressed in a very low number of cells (see #3598 for more details). 

Assuming all of these genes are in your RNA assay, you could check how many cells are expressing each gene by `rowSums(allo.smerged[['RNA']][upr_genes,]>0)`

 To see a list of features that are not included in your integrated assay you could try something like `setdiff(upr_genes, rownames(allo.smerged[['integrated']]))`. 

2. We recommend using the RNA assay to calculate `AddModuleScore`

3.  If you have some sort of a priori reason to split genes into two sets that seems valid, but I would not recommend doing this based on the direction of change that you observe. For example, if you have 50% of genes that are upregulated in a pathway and 50% of genes that are downregulated in a pathway, it doesn't make sense to take the half of genes that are upregulated and then say that the pathway is upregulated.

4. It's reasonable to exclude genes that you aren't detecting in your data, although if this is a large proportion of the genes in your pathway, I would question if your score is really representative of that pathway.
