### ISSUE TITLE
Numbering of clusters

### ISSUE THREAD

**Issue by JFourquet** [satijalab/seurat#4884]
Hi,
Are the clusters numbered from the cluster with the most cells (cluster 0) to the one with the least cells (cluster 8 if I have for example a total of 8 clusters)?
I obtained my clusters with FindClusters and my UMAP with RunUMAP.
Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Yes the default numbering scheme is ordered by cluster size.  You can check this by running:
```
num_cells <- table(obj_name@active.ident)
num_cells
```

Here's example with pbmc3k dataset from Seurat Data:
```
pbmc <- pbmc3k.SeuratData::pbmc3k %>% 
  SCTransform() %>% 
  RunPCA() %>% 
  FindNeighbors() %>% 
  FindClusters() %>% 
  RunUMAP(dims = 1:10)

num_cells <- table(pbmc@active.ident)
num_cells

  0   1   2   3   4   5   6   7   8   9  10 
628 482 369 353 227 160 152 151 132  33  13 
```

Best,
Sam

**Comment by JFourquet** [comment]
Thanks a lot Sam !
Best,
Joanna
