### ISSUE TITLE
How to set multiple reference datasets for FindIntegrationAnchors()

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4889]
Hello! 

I've seen three vignettes on reference based integration, and each have three different ways to set reference datasets, but I am not sure how to implement them. 

I want to set `10X Genomics Chromium Single Cell 3' v1, v2` and `10X Genomics Chromium Single Cell 3' v3` as the reference sets.

![image](https://user-images.githubusercontent.com/62159599/128080243-c94e4c53-a87d-4478-b3dc-30f5b30e2002.png)

Up until `FindIntegrationAnchors()`, here is what I have run (note: these are all counts formatted datasets):

```
combo <- merge(dataset1, y = c(dataset2, dataset3), 
               add.cell.ids = c("dataset1", "dataset2", "dataset3"))

combo.list <- SplitObject(combo, split.by = "Capture.Method")

for (i in 1:length(combo.list)) {
  combo.list[[i]] <- NormalizeData(combo.list[[i]], verbose = FALSE)
  combo.list[[i]] <- FindVariableFeatures(combo.list[[i]], selection.method = "vst", nfeatures = 2000,
                                          verbose = FALSE)
}

```
The first method I've seen comes from https://satijalab.org/seurat/articles/integration_large_datasets.html and uses the following way to specify their reference sets.

```
anchors <- FindIntegrationAnchors(object.list = bm280k.list, reference = c(1, 2), reduction = "rpca",
    dims = 1:50)
```

I am not sure how to specify the  `10X Genomics Chromium Single Cell 3' v1, v2` and `10X Genomics Chromium Single Cell 3' v3` sets in a numerical way though. 

The second method I've seen comes from https://satijalab.org/seurat/archive/v3.0/integration.html and uses the following way to specify their reference sets:

```
reference_dataset <- which(names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3"))
```

When I try this though, I get the following error:

```
combo.anchors <- FindIntegrationAnchors(object.list = combo.list, reference = reference_dataset, dims = 1:30)

Error in which(x = object.classes, useNames = TRUE) : 
  argument to 'which' is not logical
In addition: Warning message:
In max(reference) : no non-missing arguments to max; returning -Inf

```

The third method comes from https://satijalab.org/seurat/articles/integration_mapping.html and does the following:

```
reference.list <- combo.list[c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3")]
```

But then I get this error:

```
combo.anchors <- FindIntegrationAnchors(object.list = combo.list, reference = reference.list, dims = 1:30)

Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
```

I should note that I want to do reference based integration in such a manner that I can eventually visualize both the reference and the query datasets on a single UMAP (which is why I'm not using the MapQuery method as it cannot do so as suggested in https://github.com/satijalab/seurat/issues/2246, but please correct me if I am misunderstanding what was said in that issue). I want to use reference-based integration in general because I want to have the datasets with the largest number of cells as the "guide" by which the rest of the datasets are integrated in order to not have the sparsity from datasets with smaller numbers of cells skew the clustering. Hopefully that makes sense.

Thanks for reading!

**Comment by ksaunders73** [comment]
I think I forgot this line: 
`features <- SelectIntegrationFeatures(object.list = combo.list)
`

including it works:

```
combo <- merge(dataset1, y = c(dataset2, dataset3), 
               add.cell.ids = c("dataset1", "dataset2", "dataset3"))

combo.list <- SplitObject(combo, split.by = "Capture.Method")

for (i in 1:length(combo.list)) {
  combo.list[[i]] <- NormalizeData(combo.list[[i]], verbose = FALSE)
  combo.list[[i]] <- FindVariableFeatures(combo.list[[i]], selection.method = "vst", nfeatures = 2000,
                                          verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = combo.list)

reference_dataset <- which(names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3"))

combo.anchors <- FindIntegrationAnchors(object.list = combo.list, anchor.features = features, reference = reference_dataset, dims = 1:30)

```

except for one of my sets to be integrated, it leads to this error (see https://github.com/satijalab/seurat/issues/4897)

**Comment by yuhanH** [comment]
Hi, 
Here is a way to find the numerical position of your selected reference. 
```
ref <-   c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3")

# return reference name
grep(paste(ref , collapse="|"),   names(combo.list)  , value = TRUE ) 
# return reference position
grep(paste(ref , collapse="|"),   names(combo.list)) 

```
