### ISSUE TITLE
Where does FindClusters store identities?

### ISSUE THREAD

**Issue by ryanshan0129** [satijalab/seurat#489]
Hi Seurat developers, 

I am trying to use silhouette function to find the optimum k and the resolution. How can I extract the cell identity when I pass a vector of values to the resolution parameter? 
```R
pbmc_small <- FindClusters(
  object = pbmc_small,
  reduction.type = "pca",
  resolution = c(0.4, 0.8, 1.2),
  dims.use = 1:10,
  save.SNN = TRUE
)
```
I tried to look into the `pbmc_small@calc.params` and they are separated by FindClusters.res.0.4, FindClusters.res.0.8 and FindClusters.res.1.2. But I don't know if it is way to extract different clusterings by resolution parameters.

Many thanks

**Comment by ryanshan0129** [comment]
Oh actually all the identities by different resolutions were stored in metadata, didn't think of that. But it still takes a long time to pass different k(s) for evaluating in silhouette function.

**Comment by mojaveazure** [comment]
Just so others browsing questions see this clearly: `FindClusters` stores the identities in `object@meta.data`, under columns `res.##` where `##` is the resolution passed.
