### ISSUE TITLE
How to determine whether a gene is significantly expressed in a dataset

### ISSUE THREAD

**Issue by fritzherbert** [satijalab/seurat#4890]
I have been looking at a specific family of genes in my single-cell data set using Seurat. Similarly to the previous question posed here: https://bioinformatics.stackexchange.com/questions/5046/find-a-cutoff-value-for-genes-that-are-expressed-in-single-cell-rna-seq 

I am unsure when I can consider a gene to be truly expressed or when is the expression I see only an artifact. i.e in how many cells does my gene have to be expressed in to count as "real"? 

Is there a specific statistical test I can perform on my set of genes? 

Thank you in advance, 

Fritz

**Comment by liuxl18-hku** [comment]
In the case of QC, truly expressed genes were believed to be more frequently detected, but the cut-off for cell frequency and expression abundance to be "detected" are various from dataset to dataset. In seurat, a basic QC for "expressed" genes are genes with UMIs count >0 in >= 3 cells. This is the most relax one, but people tends to be relax at this stage to include as many cells and genes for downstream analysis. But it depends, I've seen people using cell frequency cut-off like >= 10 cells, >= 50 cells, or >=N% of cells, all these depend on the dataset and strengency.

In above case, there is no statistical test required, therefore "significantly expressed" does not apply. But my another guess about your request would be gene set "enrichment", that is, you are interested in whether the your gene set is more expressed comparing to random (not necessary artefacts), that's different with basic QC, `Seurat::AddModuleScore` implemented one model used for this kind of enrichment analysis mentioned in [some publication](http://science.sciencemag.org/content/sci/suppl/2016/04/07/352.6282.189.DC1/Tirosh.SM.pdf). Basic idea is, different genes have different absolute abundance, this is biology. It's not fair to use same background distribution for all genes in the enrichment analysis. People used bin-based approach, that is, only compare forthground genes with background genes with similar expression abundance (falling into same abundance based bin).

bless~

**Comment by saketkc** [comment]
There is no perfect answer as to what should be the right cutoff. If by "artifact", you imply that the observed expression is essentially transcriptional noise, you would generally observe such noise in a _small_ proportion of cells. You can use the pct.1 and pct.2 fields in `FindMarkers` to estimate the proportion of cells that "express" a gene in a celltype (have non-zero counts conditional on how upstream pre-processing was performed).
