### ISSUE TITLE
Warning: Invalid name supplied

### ISSUE THREAD

**Issue by chen-single** [satijalab/seurat#4893]
Thanks for the tool!
When I run RunHarmony I meet a warning ：Warning: Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity
 I find this is beacus "ProjectDim" function ,Will it affect the follow-up analysis and Why does this happen? 
![image](https://user-images.githubusercontent.com/82649505/128152687-2afdb774-5083-47b8-892c-350d960d7c64.png)

**Comment by andrewwbutler** [comment]
Hi,

This warning can be ignored. You don't need to include `Seurat::` before the function call (`ProjectDim`). The warning looks like it's coming from the logging commands which store the name of the function call and it doesn't like the double colon.

**Comment by lucygarner** [comment]
Thanks, I am getting this error as well.
