### ISSUE TITLE
Using SCTransform and Harmony

### ISSUE THREAD

**Issue by learning-MD** [satijalab/seurat#4896]
Hi, I've searched around for this specific topic and came across a couple of old threads, but without any definitive answers.

Is there a reasonable way to use SCTransform and Harmony together for a multi-sample analysis (e.g. 5 control and 5 disease)? I've previously only used the NormalizeData(), etc, workflow but as I learn more about SCTransform, it seems like I should be using that instead. The workflow I have in mind is:

1. Create SeuratObject for each sample.
2. SCTransform each sample individually (and regressing out mitochondrial percentage).
3. After SCTransform, merge the 10 samples together (using the merge function).
4. Run Harmony for batch correction.
5. Clustering, marker identification, cluster annotation, and downstream analyses.

Is that a reasonable way to approach this? Thanks!

**Comment by ksaunders73** [comment]
I've seen people saying that it's fine (https://github.com/immunogenomics/harmony/issues/41), but only really one paper (https://www.nature.com/articles/s42003-020-01476-1.pdf?proof=t) mentioning the two together (but I could have missed others). This paper seems to be following this tutorial https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/harmony.html - not using SCTransform right before RunHarmony like I think you're wanting to do? You're wanting to do something along the lines of this right?

```
SCTransform(object1)
SCTransform(object2)
combo<- merge(object1, object2)
combo <- RunHarmony(combo, group.by.vars = "Method")

```

So if you need a citation, you may have some difficulty. I also would like to know more about this and hear other peoples' thoughts though!

**Comment by learning-MD** [comment]
@ksaunders73, that's what I was thinking of doing. I've also seen others comment on here about merging all samples together and using SCTransform on the merged data, with the addition of vars.to.regress = "sample_ID". I'm not sure if that latter would work well or not. Like you, I've had trouble finding citations. So, I'm hoping those with more experience with this may chime in for guidance.

**Comment by saketkc** [comment]
You can use SCTransform and Harmony in this way (alternate approaches are also possible):
```{r}
data("pbmcsca")

pbmcsca.list <- SplitObject(pbmcsca, split.by="Method")
pbmcsca.list <- lapply(X = pbmcsca.list, 
                       FUN = SCTransform, 
                       method = "glmGamPoi", 
                       return.only.var.genes = FALSE)
var.features <- SelectIntegrationFeatures(object.list = pbmcsca.list, nfeatures = 3000)

pbmcsca.sct <- merge(x = pbmcsca.list[[1]], y = pbmcsca.list[2:length(pbmcsca.list)], merge.data=TRUE)
VariableFeatures(pbmcsca.sct) <- var.features
pbmcsca.sct <- RunPCA(pbmcsca.sct, verbose = FALSE)
pbmcsca.sct <- RunHarmony(pbmcsca.sct, assay.use="SCT", group.by.vars = "Method")
pbmcsca.sct <- RunUMAP(pbmcsca.sct, reduction = "harmony", dims = 1:30)
pbmcsca.sct <- FindNeighbors(pbmcsca.sct, reduction = "harmony", dims = 1:30) %>% FindClusters()
DimPlot(pbmcsca.sct, group.by = c("Method", "ident", "CellType"), ncol = 3)
```
![image](https://user-images.githubusercontent.com/682153/128538800-a988c345-2747-4b1b-a480-0dc5bf18c170.png)
in fact if you compare this with standard log normalization approach, you would notice that the NK cells cluster separate a bit more distinctively using this approach.

**Comment by anemartinezlarrinaga2898** [comment]
I know the issue is closed but if you follow @saketkc workflow in the SCT assay you only have 2000 genes, so then If you want to subset from this combination of doing SCT+Harmony, your matrix will only have 2000 genes.  Is there anyway of having the SCT assay with all the genes present?

**Comment by saketkc** [comment]
You can do `SCTransform(object, return.only.var.genes = FALSE)` to return residuals for all genes.

**Comment by javiers1983** [comment]
Hi @saketkc 

Related to your answer:

1)

Does: 
`SplitObject(pbmcsca, split.by="Method")`
and
`pbmcsca.sct <- RunHarmony(pbmcsca.sct, assay.use="SCT", group.by.vars = "Method")`

Should **always** have the same parameters ? ie `split.by="Method"` and `group.by.vars = "Method"`.

2)

I'm working with samples from five patients. For each patient I have healthy tissue and tumoral tissue (paired data). So the total is 10 samples.

My aim is to integrate these samples to analyze differences between healthy and tumor tissues within specific cell types, such as immune cells.

Given the potential batch effects from different patients, I'm unsure about the best parameters for integration. Can I do:

```
seurat_obj <- SplitObject(seurat_obj, split.by = "patient_id")  
seurat_obj <- lapply(X = seurat_obj, 
                     FUN = SCTransform, 
                      method = "glmGamPoi", 
                     return.only.var.genes = FALSE)
...                    
                     
seurat_obj <- RunHarmony(seurat_obj,
                         assay.use = "SCT",
                         group.by.vars = "patient_id")      
```

By using `split.by = "patient_id", the objects in `The seurat_obj` are composed of 2 samples (normal and tissue). Is it a problem for `SCTransform` or `SCTransform` should aways be applied for each sample separately ?

**Comment by RobinPranter** [comment]
I would like to integrate in across **two separate sources of technical variation** (smart-seq3 plate and embryo from which the cells are collected) this can apparently be done in `RunHarmony()` by setting `group.by.vars = c("plateID", "sampleID")`. **But how then should normalization and variable gene selection (using `SCTransform()`) be done?**
