### ISSUE TITLE
FindIntegrationAnchors() Error: Error in which(x = object.classes, useNames = TRUE) :    argument to 'which' is not logical

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4897]
Hello!

This is piggybacking off of https://github.com/satijalab/seurat/issues/3097. I have loaded in my datasets in the following way:

```
combo <- merge(dataset1, y = c(dataset2, dataset3), 
               add.cell.ids = c("dataset1", "dataset2", "dataset3"))

combo.list <- SplitObject(combo, split.by = "Capture.Method")

for (i in 1:length(combo.list)) {
  combo.list[[i]] <- NormalizeData(combo.list[[i]], verbose = FALSE)
  combo.list[[i]] <- FindVariableFeatures(combo.list[[i]], selection.method = "vst", nfeatures = 2000,
                                          verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = combo.list)

reference.list <- which(names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3"))

combo.anchors <- FindIntegrationAnchors(object.list = combo.list, anchor.features = features, reference = reference.list, dims = 1:30)


Error in which(x = object.classes, useNames = TRUE) : 
  argument to 'which' is not logical
In addition: Warning message:
In max(reference) : no non-missing arguments to max; returning -Inf
```

On selecting which datasets to use as the reference, I do run into this warning message:

```
reference.list <- which(names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3"))

Warning message:
In names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2",  :
  longer object length is not a multiple of shorter object length
```

All of the datasets are in counts format - though one was originally in a .h5 format - and here are the breakdowns per technology:
![image](https://user-images.githubusercontent.com/62159599/128390678-65ae138e-98c5-49d6-831e-60d2ea8d538e.png)

What's strange is that this code worked for another set of datasets, so I am not sure what is going wrong. The only difference is the presence of a .h5 file in this set, so I wonder if that is it?

Thanks for reading!

**Comment by yuhanH** [comment]
HI, 
```
reference.list <- which(names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2", "10X Genomics Chromium Single Cell 3' v3"))
```
This above line may not work properly. reference.list may not be a correct number.
If you compare `names(combo.list)` with one string,  it can work. 
```
reference.1 <- which(names(combo.list) == c( "10X Genomics Chromium Single Cell 3' v3"))
reference.2 <- which(names(combo.list) == c("10X Genomics Chromium Single Cell 3' v1, v2",))
reference.list <- c(reference.1, reference.2)
```
Also, you can use `grep` to find the reference index https://github.com/satijalab/seurat/issues/4889. 
Then, if you still meet this issue, I will reopen this.

**Comment by ksaunders73** [comment]
Hello @yuhanH! This worked, thank you very much for your help!
