### ISSUE TITLE
Highly Variable Genes and scale.data

### ISSUE THREAD

**Issue by elimereu** [satijalab/seurat#49]
Dears, 

Thank you for having developed this wonderful tool. 
I’m new in Seurat Package and I need to run it during my work. 
I’m also really interested in understand how it works and the idea behind it, so I have a couple of questions. 

1. The function RegressOut is very useful to correct for batch effects or other undesired aspects. It’s not clear to me why z-scores of residuals are saved in the scale.data slot. 
I know they represent the error during the model fitting, but how they're reflecting gene expressions in order to use them to cluster cells? Which is their relationship with scaled.data?

2. Why do you compute highly variable genes (in the function MeanVarPlot) using the log Normalised matrix instead of a corrected matrix (I expect you should get after RegressOut a matrix with fitted values)?
In this way, highly variable genes could contain some genes affected by undesired aspect like batch or others. 

Thanks in advance. 

Bests, 

Elisabetta

**Comment by satijalab** [comment]
This is a great question. Currently our method for defining variable genes is based purely on variance/mean relationships in expression, and does not take into account confounding factors. One reason for this is that the @scale.data frame equally weights high and low expressed genes (to provide equal weight for dimensionality reduction), but this creates problems in determining variable genes.

We know this is not ideal, but it does require developing new statistical methods that can effectively model the expected level of noise for a 'nonvariable' gene. We have solutions now for UMI data that address this, and hope to release soon.
