### ISSUE TITLE
Allen human brain scRNASeq dataset as .rds ?

### ISSUE THREAD

**Issue by alhadjil** [satijalab/seurat#4903]
Hi,

I was going throught the vignette for spatial analysis https://satijalab.org/seurat/archive/v3.2/spatial_vignette.html and I was wondering if you know where I can download the Allen Human Brain scRNASeq reference dataset as an `.rds` or how I could load it as a SeuratObject, similar to what was provided in this vignette for the mouse version of the allen map.

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Hi not member of dev team but hopefully can be helpful.  You can find data from Allen here (https://portal.brain-map.org/atlases-and-data/rnaseq).  I'm not sure they are all available as RDS Seurat objects given they may have been analyzed differently.  But the different pieces: gene expression, metadata, annotation, 2D coordinates etc are all there and they can then be assembled into Seurat object that preserves all of the information from the Allen analyses without needing to reanalyze the data.

Best,
Sam

**Comment by alhadjil** [comment]
> 
> 
> Hi,
> 
> Hi not member of dev team but hopefully can be helpful. You can find data from Allen here (https://portal.brain-map.org/atlases-and-data/rnaseq). I'm not sure they are all available as RDS Seurat objects given they may have been analyzed differently. But the different pieces: gene expression, metadata, annotation, 2D coordinates etc are all there and they can then be assembled into Seurat object that preserves all of the information from the Allen analyses without needing to reanalyze the data.
> 
> Best,
> Sam

Hi Sam,
thanks for your reply. I know how to create a SeuratObject, but how to I do I get the cell-type annotations?

**Comment by samuel-marsh** [comment]
Hi,

The download tabs for each dataset also contain a meta data table that contains cell type annotations.  You can then either add the full meta data or just the annotation to Seurat object `@meta.data` and then can make that the active ident for ease in plotting.

Best,
Sam

**Comment by andrewwbutler** [comment]
In the vignette, there is also a link to directly download an Rds for the allen cortex data ([here](https://www.dropbox.com/s/cuowvm4vrf65pvq/allen_cortex.rds?dl=1)).

**Comment by alhadjil** [comment]
> 
> 
> In the vignette, there is also a link to directly download an Rds for the allen cortex data ([here](https://www.dropbox.com/s/cuowvm4vrf65pvq/allen_cortex.rds?dl=1)).

This is the mouse cortex. I'm asking for the human...

**Comment by antoine4ucsd** [comment]
Hello
were you able to find or create a human brain reference dataset? 
thank you!

**Comment by me-orlov** [comment]
Hi [antoine4ucsd](https://github.com/antoine4ucsd), any luck?! I don't think there is one, but I haven't looked as closely as I ought.
