### ISSUE TITLE
Should you use AddModuleScore() to plot expression of one gene?

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#4904]
Hello!

So that I can compare gene expression to each other, I've been using `AddModuleScore()`, and then z-score transforming the module score, and plotting that using `FeaturePlot()`. The code is as follows:

```
tnbclist <- list(c("FABP7", "TSPAN8", "CYP4Z1", "HOXA10", "CLDN1",
                   "TMSB15A", "C10ORF10", "TRPV6", "HOXA9", "ATP13A4",
                   "GLYATL2", "RP11-48O20.4", "DYRK3", "MUCL1", "ID4", "FGFR2",
                   "SHOX2", "Z83851.1", "CD82", "COL6A1", "KRT23", "GCHFR",
                   "PRICKLE1", "GCNT2", "KHDRBS3", "SIPA1L2", "LMO4", "TFAP2B",
                   "SLC43A3", "FURIN", "ELF5", "C1ORF116", "ADD3", "EFNA3",
                   "EFCAB4A", "LTF", "LRRC31", "ARL4C", "GPNMB", "VIM", 
                   "SDR16C5", "RHOV", "PXDC1", "MALL", "YAP1", "A2ML1",
                   "RP1-257A7.5", "RP11-353N4.6", "ZBTB18", "CTD-2314B22.3", "GALNT3",
                   "BCL11A", "CXADR", "SSFA2", "ADM", "GUCY1A3", "GSTP1",
                   "ADCK3", "SLC25A37", "SFRP1", "PRNP", "DEGS1", "RP11-110G21.2",
                   "AL589743.1", "ATF3", "SIVA1", "TACSTD2", "HEBP2"))

sobj <- AddModuleScore(object = sobj, features = tnbclist, name = "TNBC_List") 
sobj$TNBC_List1<- (sobj$TNBC_List1- mean(sobj$TNBC_List1)) / sd(sobj$TNBC_List1)
FeaturePlot(object = sobj, features = "TNBC_List1", min.cutoff = 0) 

```

However, I don't know how to do this if I just want to plot one gene, which is usually done by just running FeaturePlot(). 
`FeaturePlot(object = sobj, features = "FABP7", min.cutoff = 0) 
`

I could just make a module score including just one gene, and then doing the above, but is this still valid? 

Hopefully this makes sense, and thanks for reading!

**Comment by rsatija** [comment]
If you just want to plot one gene, then as you say, you should use the FeaturePlot function. If you want to plot z-scored values, you can scale the gene with ScaleData, and then set slot='scale.data' as an argument to FeaturePlot
