### ISSUE TITLE
ReadMtx -> Cannot find expression matrix

### ISSUE THREAD

**Issue by rpe230** [satijalab/seurat#4905]
I am attempting to use the ReadMtx function to import single-cell data that was previously run through kallisto & bustools.  When I attempt the ReadMtx functions it produces the error: Cannot find expression matrix

Here is a screenshot of my code and the results
<img width="676" alt="Screen Shot 2021-08-08 at 7 50 15 PM" src="https://user-images.githubusercontent.com/88349255/128649292-5cda8c78-2a86-42a6-9a86-4ffdb7e21c85.png">
<img width="652" alt="Screen Shot 2021-08-08 at 7 51 16 PM" src="https://user-images.githubusercontent.com/88349255/128649323-52e8cb09-4e22-4f2e-b04c-3cea89fcaaee.png">

I have tried the code with the gzip version of the files as well with the same results and I am using Seurat version 4.0.3.  Any suggestions on how to resolve this?

**Comment by liuxl18-hku** [comment]
Is your working directory `getwd()` same as `data_dir`, if not, my understanding is `ReadMtx()` doesn't know where your data files are located. You may try:

```r
setwd(data_dir)
# then run ReadMtx() using your command
```

or concatenate the `data_dir` as prefix of each file 

```r
expression_matrix <- ReadMtx(
    mtx = paste0(data_dir, "/matrix.mtx",
    features = paste0(data_dir, "/genes.tsv",
    cells = paste0(data_dir, "/barcodes.tsv"
)
```

Good luck~

**Comment by rpe230** [comment]
That solved my issue! Thank you!!
