### ISSUE TITLE
'igraph', 'leiden', 'rsvd' are needed for the installation of old version Seurat V3.0-V3.2, but they are not available for R3.6.0-R3.6.3  

### ISSUE THREAD

**Issue by crebli** [satijalab/seurat#4906]
The old version Seurat V3.0-V3.2 were able to be installed easily via CRAN 1 years ago when they were released. Now the old versions were not able to be available from CRAN, but should be downloaded and installed via remotes. For example,

remotes::install_version("Seurat", version = "3.1.2")
remotes::install_version("Seurat", version = "3.2.2")
.............................
ERROR: dependencies 'igraph', 'leiden', 'rsvd' are not available for package 'Seurat'
* removing 'C:/Program Files/R/R-3.6.3/library/Seurat'
Warning messages:
1: package ‘rsvd’ is not available (for R version 3.6.3) 
2: In i.p(...) : installation of package ‘igraph’ had non-zero exit status
3: In i.p(...) : installation of package ‘leiden’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘C:/Users/user/AppData/Local/TEMP_~1/Rtmp0GgP4M/remotes4a8472d23f/Seurat’ had non-zero exit status

ERROR: dependencies 'igraph', 'leiden', 'rsvd' are not available for package 'Seurat'
* removing 'C:/Program Files/R/R-3.6.3/library/Seurat'
Warning messages:
1: package ‘rsvd’ is not available (for R version 3.6.0) 
2: In i.p(...) : installation of package ‘igraph’ had non-zero exit status
3: In i.p(...) : installation of package ‘leiden’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘C:/Users/user/AppData/Local/TEMP_~1/Rtmp0GgP4M/remotes4a8472d23f/Seurat’ had non-zero exit status

The issue were reproducible.

```r
# insert reproducible example here
```

**Comment by samuel-marsh** [comment]
Hi,

In the same way that you can install the older version of Seurat you can also install older versions of those packages that are compatible with older versions of R.  You can see what versions are available by viewing CRAN archive package for the packages (e.g, https://cran.r-project.org/src/contrib/Archive/rsvd/).

Best,
Sam

**Comment by crebli** [comment]
Yes. I have installed these packages one by one as you suggested. package "rsvd" V1.0.2 was downloaded and installed. Seurat v3.1.5 is able to be installed in R3.6.3.While Seurat v3.2.2 is still hard to be installed to R3.6.3. 
Thank you!
















At 2021-08-09 21:05:01, "Samuel Marsh" ***@***.***> wrote:

Hi,

In the same way that you can install the older version of Seurat you can also install older versions of those packages that are compatible with older versions of R. You can see what versions are available by viewing CRAN archive package for the packages (e.g, https://cran.r-project.org/src/contrib/Archive/rsvd/).

Best,
Sam

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by samuel-marsh** [comment]
Hi,

What do you mean that 3.2.3 is hard to be installed?

Best,
Sam

**Comment by crebli** [comment]
Sorry，I have resolved this today. It is a problem of spatstat. When I installed a version of spatstat_1.64-1 and then the problem was resolved. Thanks!  













At 2021-08-10 18:55:44, "Samuel Marsh" ***@***.***> wrote:

Hi,

What do you mean that 3.2.3 is hard to be installed?

Best,
Sam

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by samuel-marsh** [comment]
glad to hear!
