### ISSUE TITLE
Issue with RunPCA

### ISSUE THREAD

**Issue by JE001** [satijalab/seurat#4909]
Hello,

I am trying to use the clustering workflow to analyze a small dataset of <500 cells. I am able to successfully set up the Seurat object by merging two previously created Seurat objects:

AGNL020_CD8_VDJ <- readRDS(file = "/Volumes/Kohlmeier_lab/Lab Members/Jennifer/Human Lung Project/Bioinformatics/scRNAseq_Analysis/AGNL020_CD8_VDJ.rds")
> AGNL020_CD8_VDJ@meta.data$donor <- "AGNL020"
> 
> AHBO103_CD8_VDJ <- readRDS(file = "/Volumes/Kohlmeier_lab/Lab Members/Jennifer/Human Lung Project/Bioinformatics/scRNAseq_Analysis/AHBO103_CD8_VDJ.rds")
> AHBO103_CD8_VDJ@meta.data$donor <- "AHBO103"
> Flu <- merge(AGNL020_CD8_VDJ, AHBO103_CD8_VDJ)

> Flu
An object of class Seurat 
36628 features across 473 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
 1 other assay present: ADT
> 

However, after normalizing the data, identifying the highly variable features, and scaling the data, I get the following error message when I try to use the RunPCA function:

> Flu <- RunPCA(Flu, features = VariableFeatures(object = Flu))
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive

I believe the issue is arising from the FindVariableFeatures or ScaleData step, as after running FindVariableFeatures there are 2000 variable features:

> FindVariableFeatures(Flu, selection.method = "vst")

An object of class Seurat 
36628 features across 473 samples within 2 assays 
Active assay: RNA (36601 features, 2000 variable features)
 1 other assay present: ADT

Whereas after running ScaleData there are 0:

> all.genes <- rownames(Flu)
> Flu <- ScaleData(Flu, features = all.genes)

> Flu
An object of class Seurat 
36628 features across 473 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
 1 other assay present: ADT

A very similar issue was identified by another user (https://github.com/satijalab/seurat/issues/1788), but a solution was not found in the thread.

Thank you very much for your help.

**Comment by liuxl18-hku** [comment]
You possibly need to save the object after identifying HVG:

```r
Flu <- FindVariableFeatures(Flu, selection.method = "vst")
```

**Comment by JE001** [comment]
Thank you for the easy fix, and sorry for the inconvenience!
