### ISSUE TITLE
Error in defining sample.tree, is there any example out there?

### ISSUE THREAD

**Issue by behrouzsh** [satijalab/seurat#4913]
Is there any example on how sample.tree should be defined in the inegrateData?
I have implemented that as sample.tree = c("A", "B", "C", "D") and sample.tree = c(A, B, C, D), where A, B, C and D are seurat objects, but in both cases I get this error:
Error in 1:nrow(x = sample.tree) : argument of length 0

**Comment by andrewwbutler** [comment]
Hi,

The `sample.tree` parameter takes the form of a matrix where each row represents one of the pairwise integration steps.  Negative numbers here specify a dataset, positive numbers indicate results of integrating that given row. E.g.

```
-2, -3  # integrate datasets 2 and 3
1, -1 # then integrate the results of row 1 with dataset 1
```

**Comment by timoast** [comment]
We've now updated the documentation for `IntegrateData()` to include an example of the format needed for the `sample.tree` parameter and a bit more explanation.
