### ISSUE TITLE
data presentation under FindMarkers

### ISSUE THREAD

**Issue by Leonrunning** [satijalab/seurat#4914]
Hi Seurat Team,

On the tutorial of version 4.0.3 (https://satijalab.org/seurat/articles/pbmc3k_tutorial.html), the data was presented as avg_log2FC under the FindMarkers function. The counts were normalized using the LogNormalize function, that is to say, they should be in the format of avg_logFC instead of log2. Is there any error here? The outputs of FindMarkers under 4.0.3 are all in the format of log2, which confuse me a lot.

thanks

Leon

**Comment by samuel-marsh** [comment]
Hi Leon,

Not member of dev team but hopefully can be helpful.  So I think you are mixing up two different aspects.  The data is log normalized using `LogNormalize` when you run the `NormalizeData` function in that tutorial before proceeding with downstream analysis and the normalized data is used for many of the gene expression plotting functions.

However in `FindMarkers` what is being reported is the log fold change between the groups that are being compared.  The fold change is calculated and log2 transformed by default.  If you want you can change what base is used for this transformation using rhe `base` parameter, although log2 is fairly standard in transcriptomics analysis.

Best,
Sam

**Comment by Leonrunning** [comment]
> Hi Leon,
> 
> Not member of dev team but hopefully can be helpful. So I think you are mixing up two different aspects. The data is log normalized using `LogNormalize` when you run the `NormalizeData` function in that tutorial before proceeding with downstream analysis and the normalized data is used for many of the gene expression plotting functions.
> 
> However in `FindMarkers` what is being reported is the log fold change between the groups that are being compared. The fold change is calculated and log2 transformed by default. If you want you can change what base is used for this transformation using rhe `base` parameter, although log2 is fairly standard in transcriptomics analysis.
> 
> Best,
> Sam

Hi Sam.

Yes, you are right. Sorry, I mixed it up when I was writing for this. In the previous versions, the base was set to show logFC. Would please let me know the options for the 'base' parameter or where can i find it?

thanks
Leon

**Comment by Leonrunning** [comment]
> Hi Leon,
> 
> Not member of dev team but hopefully can be helpful. So I think you are mixing up two different aspects. The data is log normalized using `LogNormalize` when you run the `NormalizeData` function in that tutorial before proceeding with downstream analysis and the normalized data is used for many of the gene expression plotting functions.
> 
> However in `FindMarkers` what is being reported is the log fold change between the groups that are being compared. The fold change is calculated and log2 transformed by default. If you want you can change what base is used for this transformation using rhe `base` parameter, although log2 is fairly standard in transcriptomics analysis.
> 
> Best,
> Sam

Hi Sam, 

Sorry, i misunderstand. I got it now.

thanks

Leon
