### ISSUE TITLE
Mixscape CalcPertubSig Error

### ISSUE THREAD

**Issue by JH1606-code** [satijalab/seurat#4918]
Hi all,

I use mixscape to evaluate a CRISPR screen. The CRISPR screen is based on the 10X pipeline and currently contains only one replicate. After loading the data, pre-processing and normalizing it, I wanted to use the CalcPertubSig function. 

_DefaultAssay(object = TF_obj) <- 'RNA'_
_TF_obj <- NormalizeData(object = TF_obj) %>% FindVariableFeatures() %>% ScaleData()_
_TF_obj <- RunPCA(TF_obj)#, npscs = 30, verbose = FALSE)_
_TF_obj <- RunUMAP(TF_obj, dims = 1:30 )_
_DimPlot(TF_obj, reduction = "umap", label = TRUE, pt.size = 0.2, label.size = 7)_

_TF_obj<- CalcPerturbSig(_
  _object = TF_obj,_
  _assay = "RNA",_
  _slot = "data",_
  _gd.class ="target_gene",_ 
  _nt.cell.class = "NTC_Safe",_
  _reduction = "pca",_
  _ndims = 20,_ 
  _num.neighbors = 20,_ 
 _new.assay.name = "PRTB", verbose = TRUE)_

For the input of "gd.class" and "nt.cell.class" I followed the tutorial (https://satijalab.org/seurat/articles/mixscape_vignette.html) where their used the target gene names for gd.class (in my case "target_gene" and the guide-RNA_IDs for nt.cell.class (where the Non-Target-Control are named NT  instead of NT_1 to NT_9 which are stored in long form in guide_ID in the tutorial) . In my case this is NTC_Safe (NTC -> Non-target-control and Safe -> Safe_Cutter). Here I stored only NTC and Safe instead of NTC-1 to NTC-10 and Safe-1 to Safe-10, which are stored in gRNA_ID.

But always when I try to run CalcPerturbSig the following error occurs:

**Processing rep1
Error in nn2(data = numeric(0), query = c(-0.0571836490105477, -3.04771606918094,  : 
  Cannot find more nearest neighbours than there are points**

Do you have any idea where this error comes from?  I would be really happy about a feedback!

In the screenshot you can get better idea how my meta.data looks like: 
![image](https://user-images.githubusercontent.com/84003107/128981825-9aaf63bf-ec5f-4de1-b027-401de5adf8e3.png)

**Comment by kaanokay** [comment]
Hi @JH1606-code,

I wonder whether you solved this problem? I have also one replicate and got the same error.

Bw.

**Comment by JH1606-code** [comment]
Hi,

yes I fixed this problem. I had to write nt.cell.class = "NTC" instead of nt.cell.class = "NTC_Safe".

Hope this helps!

Best

**Comment by kaanokay** [comment]
Hi,

As I understand, if we have only one replicate for cells, its possible to use this function without any issues, right?

**Comment by JH1606-code** [comment]
Yes.

**Comment by kaanokay** [comment]
Thank a lot.

Bw.
