### ISSUE TITLE
Explanation of these plots in detail

### ISSUE THREAD

**Issue by jjyotikataria** [satijalab/seurat#4919]
@troels @mxposed @zeehio @smoe @maximilianh 
Could you please explain in detail what all information could be derived from this analysis detail? 
I am anticipating very less outliers obtained after the filtering step with user defined subsetting of Seurat object. Also, nGene and nUMI should be positively correlated, is that what is highly recommended? And the reverse in nUMI vs percent.mt graph?

![image](https://user-images.githubusercontent.com/58770228/128984560-3e4dbfdb-17b1-4a54-9acb-a17719f92b7b.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.

What do you mean by less outliers and what filtering have you performed?  It's hard to interpret what is going on without knowing what code has been run.  If you can post any relevant code with your issues it will aid in interpretation.

Yes you do expect number of genes and number of UMIs per cell to be positively correlated.  What version of Seurat are you using though (the nUMI and nGene notation are from much older <v3 versions).

The correlation metric in the percent.mt graph is not really the important metric.  What you are looking for is whether perhaps there are cells with very low UMI counts and very high mitochondrial percentages that may indicate damaged cells or generally the overall percentage of percent.mt across the dataset as assessment of quality of cells (although it can also change for biological reasons).

Best,
Sam

**Comment by jjyotikataria** [comment]
seurat_obj <- CreateSeuratObject(counts = seurat_data,
                                     min.cells = 3,
                                     min.features = 200,
                                     project = sample_name)

merged_obj <- PercentageFeatureSet(merged_obj, "^MT-", col.name = "percent_mito")
merged_obj <- PercentageFeatureSet(merged_obj, "^RP[SL]", col.name = "percent_ribo")

merged_obj@meta.data <- merged_obj@meta.data %>%
     dplyr::rename(nUMI = nCount_RNA,
                   nGene = nFeature_RNA,
                   percent.mt = percent_mito,
                   percent.rb = percent_ribo)

pbmc <- subset(merged_obj, subset = nGene > 2500 & nGene < filt1 & percent.mt < 10)

@samuel-marsh
