### ISSUE TITLE
How can i visualize TSNE by cell.id. instead of cluster?

### ISSUE THREAD

**Issue by kysbbubbu** [satijalab/seurat#492]
Hello

Thank you for developing so wonderful program to analysis single cell RNAse.

I merged two datasets using Mergeseurat command
And before clustering, i want to see the TNSE plots by cell.id.
How can i visualize TSNE by cell.id. instead of cluster?

Thanks

**Comment by AndyR2** [comment]
DimPlot function 

for example
DimPlot(x, reduction.use = "tsne", group.by = "cell.id" ).  

This assumes you have a column 'cell.id@meta.data'

**Comment by leonfodoulian** [comment]
@AndyR2,

The column should be present as `object@meta.data$cell.id`.

Best,
Leon

**Comment by kysbbubbu** [comment]
Thanks! @AndyR2 @leonfodoulian 
I used below command to merge and visualization 

DimPlot(merge, reduction.use = "tsne", group.by = "orig.ident" )
