### ISSUE TITLE
What is the best way to add assay from one seurat object to another? 

### ISSUE THREAD

**Issue by jessielyons** [satijalab/seurat#4922]
RNA.object[["integrated.adt"]] <- CreateAssayObject(counts = ADT.object[["integrated"]])
Error in UseMethod(generic = "as.sparse", object = x) :
no applicable method for 'as.sparse' applied to an object of class "Assay"

**Comment by jessielyons** [comment]
And what's the best way to add reduction 'apca" from one seurat object into another?

**Comment by jessielyons** [comment]
Hi @yuhanH ,
When I used,
RNA.object[["integrated.adt"]] <- CreateAssayObject(data = ADT.object@assays$integrated@data), then my "integrated" assay got overwritten.

I don't understand your comment in this post https://github.com/satijalab/seurat/issues/3843

Can you please provide some commands for "Hi @JenniferWUSTL
During the integration process, the scale.data is easily to be lost, because in merge function, we usually delete the scale.data.

One easy way is to first integrate RNA and protein separately by two objects. Then, you can create an integrated ADT assay in the integrated RNA object."?

**Comment by yuhanH** [comment]
hi @jessielyons 
I don't think your above code will overwrite the integrated assay in `RNA.object`.
Here are suggested scripts:
```
adt.data <- GetAssayData(object =  ADT.object[['integrated']], slot = 'data')
RNA.object[["integrated.adt"]] <- CreateAssayObject(data = adt.data )
Default(RNA.object) <- "integrated.adt"

## if you have a large ADT panel, set do.scale = FALSE
RNA.object <- ScaleData(RNA.object)

RNA.object <- RunPCA(RNA.object,  reduction.name = 'pca.adt', reduction.key = 'PCadt_' )
```
Then you should have an integrated ADT assay and related PCA dimensional reduction. Hope this can work.

**Comment by jessielyons** [comment]
Hi @yuhanH , thanks. I modified as per your instructions. However, now when I run the FindMultiModalNeighbors command, I get a warning message. Is this warning message acceptable? Please let me know.

Now, my RNA.object is:
An object of class Seurat 
30870 features across 20077 samples within 4 assays 
Active assay: integrated (2000 features, 2000 variable features)
 3 other assays present: RNA, ADT, integrated.adt
 2 dimensional reductions calculated: pca, adt.pca

rnaadt.comb  <- FindMultiModalNeighbors(
+   RNA.object , reduction.list = list("pca", "adt.pca"), 
+   dims.list = list(1:30, 1:18), modality.weight.name = "RNA.weight"
+ )
Constructing multimodal KNN graph
Constructing multimodal SNN graph
Warning message:
In FindMultiModalNeighbors(RNA.object, reduction.list = list("pca",  :
  The number of provided modality.weight.name is not equal to the number of modalities. integrated.weight integrated.weight are used to store the modality weights

**Comment by yuhanH** [comment]
Hi, 
That's fine.  The assay used in `adt.combined[['apca']]` is integrated. 
You just need to change the assay of `RNA.object[['adt.pca']]` to integrated.adt
```
RNA.object[['adt.pca']]@assay.used <-  "integrated.adt"
```

**Comment by jessielyons** [comment]
Hi @yuhanH ,

OK I made the change as you suggested.

Now after running FindMultiModalNeighbors, RunUMAP and RunClusters, I got clusters. Now, I want to create a heatmap of top ADT features that associate with these clusters. and I get the error message:

DoHeatmap(immune.combined , features = "CD35", assay = "integrated.adt")
 "No requested features found in the scale.data slot for the integrated.adt assay."

Only the data slot exists. Should I have carried over scale.data slot as well? Please guide, thanks so much again.

**Comment by jessielyons** [comment]
@yuhanH , perhaps I need to re-run scaledata on ADT after combining even though I ran scaling and PCA after integration of ADT alone.

**Comment by yuhanH** [comment]
Right. You can re-scale your ADT data in the `ADT assay` for the heatmap instead of integrated.adt assay.

**Comment by sky5198** [comment]
I have tried the above code (modified with my own object and assay):

adt.data <- GetAssayData(object = atac.object[['peaks']], slot = 'data')
rna.object[["peaks"]] <- CreateAssayObject(data = adt.data )

but I get the error: 
Error in `[[<-`:
! Cannot add new cells with [[<-
Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()
<error/rlang_error>
Error in `[[<-`:
! Cannot add new cells with [[<-
---
Backtrace:
    ▆
 1. ├─methods (local) `[[<-`(`*tmp*`, "peaks", value = `<Assay[,5532]>`)
 2. └─SeuratObject (local) `[[<-`(`*tmp*`, "peaks", value = `<Assay[,5532]>`)
Run rlang::last_trace(drop = FALSE) to see 1 hidden frame.


Does anyone have any suggestions?
