### ISSUE TITLE
Incorrect FindMarkers Function for Tutorial Titled "Using Seurat for Multimodal Data"

### ISSUE THREAD

**Issue by LieselWong** [satijalab/seurat#4926]
Hi! I was looking through this tutorial "https://satijalab.org/seurat/articles/multimodal_vignette.html", and I noticed in the Identify Cell Surface Markers for scRNA-seq Clusters, the FindMarkers function was run on cluster 5 instead of cluster 6. I believe the function should be run on cluster 6 since the commenting in the code refers to "this cluster", or the cluster that was found to have CD19 as a marker. I was wondering if this was intentional or not? I listed the code I'm looking at below! Thank you : )

we can also identify alternative protein and RNA markers for this cluster through differential expression
adt_markers <- FindMarkers(cbmc, ident.1 = 5, assay = "ADT")
rna_markers <- FindMarkers(cbmc, ident.1 = 5, assay = "RNA")

**Comment by timoast** [comment]
Thanks for pointing this out, this does indeed seem to be a mistake in the vignette. We will correct this soon.
