### ISSUE TITLE
Issues Installing Older Versions of Seurat

### ISSUE THREAD

**Issue by mannakade** [satijalab/seurat#4928]
Hello, I'm working with a team to reproduce some data from an older paper which uses R v3.6.2 and Seurat v3.1.2. When we try to install we get the output

 installation of package ‘C:/Users/gabri/AppData/Local/Temp/Rtmp2bbjP3/remotes43a0e0a47a/Seurat’ had non-zero exit status

and

Error in library(Seurat) : there is no package called ‘Seurat’

The code I've been running is:

library(Seurat)
install.packages('remotes')
install.packages("Seurat")
remotes::install_version(package = 'Seurat', version = package_version('3.1.2'))
library(Seurat)

We've tried all the update options to no avail either. Is there any way to install this older version or is it out of date?

**Comment by timoast** [comment]
Is there a more specific/complete error log you can provide?

There are also docker images available for each Seurat release going back to version 3.1.1, which might provide an easier way to use older versions of the package: https://hub.docker.com/r/satijalab/seurat/tags?page=1&ordering=last_updated

**Comment by mannakade** [comment]
The complete error for the remotes portion is

The downloaded source packages are in
	‘C:\Users\gabri\AppData\Local\Temp\Rtmp2bbjP3\downloaded_packages’
Installing package into ‘C:/Users/gabri/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependencies 'rsvd', 'SDMTools' are not available for package 'Seurat'
* removing 'C:/Users/gabri/Documents/R/win-library/3.6/Seurat'
Warning messages:
1: In i.p(...) :
  installation of package ‘colorspace’ had non-zero exit status
2: In i.p(...) : installation of package ‘utf8’ had non-zero exit status
3: In i.p(...) : installation of package ‘fansi’ had non-zero exit status
4: In i.p(...) : installation of package ‘tibble’ had non-zero exit status
5: In i.p(...) :
  installation of package ‘C:/Users/gabri/AppData/Local/Temp/Rtmp2bbjP3/remotes43a0e0a47a/Seurat’ had non-zero exit status

**Comment by samuel-marsh** [comment]
Hi,

See https://github.com/satijalab/seurat/issues/4906#issuecomment-895205425.  Just need to install archive versions of those other dependencies (ERROR: dependencies 'rsvd', 'SDMTools' are not available for package 'Seurat') as well before installing Seurat.

Best,
Sam

**Comment by mannakade** [comment]
Thank you Sam!
I installed the archived versions. For anyone else who may have this issue in the future, run

remotes::install_version("SDMTools", "1.1-221")


packageurl <- "https://cran.r-project.org/src/contrib/Archive/rsvd/rsvd_1.0.0.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

and Seurat v3.1.2 should be able to install properly afterwards.

Thank you once again!
