### ISSUE TITLE
FindTransferAnchors query reduction argument?

### ISSUE THREAD

**Issue by Brawni** [satijalab/seurat#4929]
Hello!

I would like to input the batch-corrected reduction I get from harmony for my query when running `FindTransferAnchors` but I can see this option is available only for the reference data (`reference.reduction`). What is the reason for that? 

Thanks!

**Comment by yuhanH** [comment]
HI
In the `FindTransferAnchors`, we project query cells to the reference dimensional reduction space (such as PCA), and then find anchors, transfer cell annotations or different expression profile. 
If you really need to use your query reduction, you can first project reference cells to the query PCA space, and then use the reference projected embeddings and query feature loadings to construct a `reference.reduction` for your reference.

**Comment by Brawni** [comment]
@yuhanH Sorry Im lost, can you give me an example of the code I should write to do that?
Also wouldn't be desirable to add an argument to specify the query reduction space for this function?

**Comment by yuhanH** [comment]
HI @Brawni 
Sorry for the confusion.  If you just want to use the query PCA, you can set `project.query = TRUE` in `FindTransferAnchors`.

**Comment by Brawni** [comment]
Thanks for prompt reply but I don't think this is what I'm looking for. My query dataset has a batch that I removed using harmony and I would like to make sure to use this reduction space instead of PCA when calling `FindTransferAnchors`. I don't see an argument to specify the reduction type for the query as there is for the reference so Im wondering if there is a way to do it, and if yes how?

**Comment by yuhanH** [comment]
I see. The steps may be a little complicated.
1. Center and standardize your reference gene expression based on mean and sd in your query data.
2. Project the scaled reference data to the query harmony feature loadings to obtain reference cell embeddings
3. Set the reference cell embeddings and query harmony feature loadings together as a dimensional reduction in your reference. 
```
reference[['harmony']] <- CreateDimReducObject(embeddings = ref.embeddings, loadings = Loadings(query[['harmony']]), assay = referece.assay, key = 'Harmony_')

```
4. Then, set 'harmony' as `reference.reduction` in the `FindTransferAnchors`.

**Comment by sallyseullee-0821** [comment]
Hi @yuhanH
I am currently trying to do a similar thing - mapping query Seurat corrected by Harmony onto a reference data that has not been corrected by Harmony. I am pretty new to Seurat + Harmony. The reference mapping tutorial does not seem to involve obtaining reference cell embeddings. What can I do to map the query (harmony) on to reference data? Thank you very much!
