### ISSUE TITLE
Change axis titles in DotPlot 

### ISSUE THREAD

**Issue by TeaByrd** [satijalab/seurat#4931]
Hey guys,

I'm wondering if there's any easy way to customize the axis titles/labels from the typical "Feature" and "Identity" to for example "Gene" and "Cluster" in the DotPlot function?
 
My code: 
`DotPlot(PRO,features = marker,cols = c("blue","red"), dot.scale = dot_size)+RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),axis.text.y=element_text(size=7))
`
My result:
![test markergene_Dotplot](https://user-images.githubusercontent.com/63348378/129328645-a50b773d-cfcb-40af-b330-14c8d82ae56c.png)

Best,
Thomas

**Comment by yuhanH** [comment]
Sure. You can use xlab and ylab to change the name of axis labels.
```
 + xlab('Cluster') +  ylab('Gene)
```

**Comment by TeaByrd** [comment]
hey it's me again, 
Sorry I couldn't figure it out and it gave me only errors, but where do I exactly put  `+ xlab('Cluster') +  ylab('Gene)` in command: `DotPlot(PRO,features = marker,cols = c("blue","red"), dot.scale = dot_size)+RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),axis.text.y=element_text(size=7))` ?

It's always giving me: 
`Error in xlab("test") : could not find function "xlab"

Best regards and thank you so much,
Thomas
`

**Comment by yuhanH** [comment]
hi @TeaByrd 
I cannot reproduce this error. Your code should work. 
```
DotPlot(pbmc_small,features = c('PPBP', 'VDAC3'),cols = c("blue","red"), dot.scale = 4)+

RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),axis.text.y=element_text(size=7))+ 

xlab('X')+ ylab('Y')
```
![image](https://user-images.githubusercontent.com/29529544/132891148-d0798f79-a901-40ce-b73b-3f2371b000c4.png)

**Comment by TeaByrd** [comment]
Are you loading any other package than:

```
library(dplyr)
library(Seurat)
library(patchwork)
```
in your session?

Im using Seurat 4 and R 4.1.0.

Best

**Comment by TeaByrd** [comment]
Nevermind, I was missing the `tidyverse` library. Now it's working! 
Best
