### ISSUE TITLE
Error in differential expression after reference mapping

### ISSUE THREAD

**Issue by beginner984** [satijalab/seurat#4932]
Hello

I need help please

I havd a Seurat object of PBMCs comes from 10X multiome's 3' poly-A capture (scRNA-seq&ATAC-seq)

After reading `filtered_gene_bc_matrices` of each sample, I extracted `scRNA-seq` part from multiome by

```
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices")

pbmc.data$`Gene Expression`

```
Anyway I merged these for my samples I made total pbmc as

```
> pbmc
An object of class Seurat 
26388 features across 11754 samples within 1 assay 
Active assay: RNA (26388 features, 0 variable features)
> 

> unique(pbmc$samples)
[1] "PN0252_0001" "PN0252_0002" "PN0252_0003" "PN0252_0004" "PN0252_0005" "PN0252_0006"
[7] "PN0252_0008"
> 

> unique(pbmc$Condition)
[1] "control" "cancer" 
> 

```

Using `Azimuth` script downloaded after running shiny app on my data, I mapped my pbmc on the reference PBMC so now I have

```
> query
An object of class Seurat 
53099 features across 11754 samples within 6 assays 
Active assay: refAssay (26388 features, 4841 variable features)
 5 other assays present: RNA, prediction.score.celltype.l2, prediction.score.celltype.l1, prediction.score.celltype.l3, impADT
 2 dimensional reductions calculated: integrated_dr, proj.umap
> 

Idents(query) <- query@meta.data$predicted.celltype.l2

> unique(Idents(query))
 [1] CD4 TCM           CD8 TEM           CD14 Mono         CD8 Naive         MAIT             
 [6] B intermediate    dnT               cDC2              Plasmablast       NK               
[11] pDC               CD4 Naive         CD16 Mono         B naive           ILC              
[16] Treg              NK_CD56bright     CD4 TEM           CD8 TCM           HSPC             
[21] cDC1              CD4 Proliferating
22 Levels: CD4 TCM CD8 TEM CD14 Mono CD8 Naive MAIT B intermediate dnT cDC2 Plasmablast ... CD4 Proliferating

DimPlot(query)

```
![Rplot38](https://user-images.githubusercontent.com/43682980/129356526-2e41867b-bd46-4b42-92a4-222c24a4c310.png)

I was going to do `differential expression between two groups (cancer/control in metadata)` but says no Treg cells while I am seeing Treg cells in the active ident.

```
>Treg.markers <- FindMarkers(query, ident.1 = "Treg", min.pct = 0.25,group.by = "Condition")
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: Treg
> 

```

I have attached the script from Azimuth here

Thanks for any help

[azimuth_analysis.txt](https://github.com/satijalab/seurat/files/6982386/azimuth_analysis.txt)

Am I right in reference mapping when my data comes from multiome?

**Comment by timoast** [comment]
Here you're grouping by condition rather than the predicted cell type (predicted.celltype.l2). There's no cells classified as "Treg" in the "Condition" variable, which is why you see this error. Setting `group.by="predicted.celltype.l2"` should solve this.

**Comment by beginner984** [comment]
Sorry I need differential expressed genes for Treg cell type, so does `group.by="predicted.celltype.l2"` returns this ?

**Comment by timoast** [comment]
The `group.by` argument tells the function which metadata column the requested cell identities are in (`ident.1` and `ident.2`). If you want to run DE on cells classified as "Treg" and this information is stored in a metadata column called "predicted.celltype.l2", then you need to set `group.by = "predicted.celltype.l2"`

**Comment by beginner984** [comment]
Sorry I get this error for plotting heatmap

By the way I get this error for do heatmap
```

> pbmc.markers %>%
+     group_by(cluster) %>%
+     top_n(n = 10, wt = avg_log2FC) -> top10
Error in group_by(., cluster) : object 'pbmc.markers' not found

> treg_markers %>%
+     group_by(predicted.celltype.l2) %>%
+     top_n(n = 10, wt = avg_log2FC) -> top10
Error: Must group by variables found in `.data`.
* Column `predicted.celltype.l2` is not found.
Run `rlang::last_error()` to see where the error occurred.
```

I don't know what I put for group by
