### ISSUE TITLE
Point shape become square in tSNE/UMAP plots

### ISSUE THREAD

**Issue by Jiam1ng** [satijalab/seurat#4933]
I have used Seurat 3.2.3 to analyze my single-cell datasets. And for twice (two different datasets), I met the problem that the point shape in tSNE/UMAP plots become square, and I didn't change any parameters about the point shape. But last week I got a normal circle one in another dataset. The enviroment, R session and code to generate the plot are exactly the same. Is there any possible reasone can this be for? Thank you so much!

**Comment by yuhanH** [comment]
What are the cell number for your different objects?  
When the number of cells is bigger than 100,000 , the shape of cells may become square because of rasterizing points to increase the speed. I would also suggest you upgrade your Seurat to our latest version.

**Comment by saketkc** [comment]
Just to follow up on @yuhanH's suggestion, you can pass `raster=FALSE` if you want to disable the rasterization option. Feel free to reopen if there are still issues.

**Comment by Jiam1ng** [comment]
@saketkc @yuhanH Thank you so much for the suggestion, I known what is going on now.
