### ISSUE TITLE
System configuration suggestion to run large integration jobs

### ISSUE THREAD

**Issue by aditisk** [satijalab/seurat#4936]
Hello,

We are trying to run integration on ~1M cells. We are using the computing cluster on campus and submitting jobs to run this step (RStudio keeps crashing). We have now reached a point where the job doesn't complete due the error mentioned below.

`Error: cannot allocate vector of size 662.6 Gb`

Our system admin asked to check for any configuration suggestions you might have to overcome this issue. Thanks a lot.

**Comment by saketkc** [comment]
For large datasets, we have some recommendations [here](https://satijalab.org/seurat/articles/integration_large_datasets.html) which might be useful. Also, it would be useful to know at what step you get this error. In some cases this might happen at the SCTransform step which can be prevented by passing it `conserve.memory=TRUE`.

**Comment by aditisk** [comment]
Hi @saketkc, sorry for the late response. We are trying the recommendations in the link for our dataset and they seem to be working without an error so far. We will soon be adding more samples, if we run into any issue again I will re-open this ticket or submit a new one as needed. Thanks a lot for your help.
