### ISSUE TITLE
Rename cells of each orig.ident after integration

### ISSUE THREAD

**Issue by Sa753** [satijalab/seurat#4937]
Dear,

I integrated 6 seurat objects and want to add a certain prefix to the name of each sample after integration?. Is that possible please?.

Rename.cells() function adds a prefix to all cells? and I want to add a prefix to the cell name corresponding to the sample name.

Thank you

**Comment by torkencz** [comment]
Hi. I would just take your individual datasets, take the cell names from the metadata in each row.names(object[[]]). Create a data frame with the row names as the original names and a variable as the new names (use paste or paste0 for that). Row bind between the each of these data frames (far each datasets) and the add to your integrated object with AddMetaData.
