### ISSUE TITLE
DEG list using FindAllMarkers for 4 different conditions

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#4938]
Hello All,

I have a very basic question about using FindAllMarkers. I have single cell data for 3 genetically engineered mouse models (GEMM) and 1 wild type (WT)/control mouse and I'm trying to get DEG lists. Because we don't specify ident.1 and ident.2 when using FindAllMarkers, in the output list, it specifies the cluster number in the column "cluster" but how do I know if its comparing WT mouse with 3 GEMM or if its comparing one of my GEMM with WT and rest of the 2 GEMM? 
Should I subset each of the GEMM single cell data with WT mouse data and then use FindMarkers? I'm not sure what's the correct way to get DEG list for each cluster. I'm new coding so any help is greatly appreciated. Thanks!
-Nikita

**Comment by mhkowalski** [comment]
Yes, FindAllMarkers compares each cluster to all of the other cells in the dataset. So the results for cluster 1  will be comparing all of the cells in  cluster 1 regardless if they are WT or GMM to all other cells. 

If you'd like to compare GEMM vs WT within each cluster, I would recommend subsetting that cluster using the `subset` function.  You can then change the Idents of that object to reflect the WT/GEMM status and run `FindMarkers` with  `ident.1="GEMM", ident.2="WT"`.
