### ISSUE TITLE
different platform integration

### ISSUE THREAD

**Issue by hansong798** [satijalab/seurat#4942]
Hello, seurat team.

i am integrating datasets from two different single cell sequencing platform.

I tried to do it using "rpca" and "SCT" and when i compated the umap of them, two methods completely made different plots.

Like this situation, which one is best suitable for integrating multi platform data ?

**Comment by saketkc** [comment]
I am not sure I understand. You can use rpca to do integration on SCTransformed objects. Did you mean rpca vs CCA? It would be helpful to have a bit more context (and code).
