### ISSUE TITLE
Different version of seurat objects

### ISSUE THREAD

**Issue by hahahah-single** [satijalab/seurat#4949]
My Seurat objects are generated by Seurat v3.0.2 but for some reason I had to use Seurat v3.2.1 for some analysis such as “FindNeighbors” “FindClusters” “RunUMAP” , Can I use objects are generated by Seurat v3.0.2 directly and  not recalculate the pca matrix？I tried to test the demo data pbmc_small,the result is as follows.
![image](https://user-images.githubusercontent.com/82649505/129669369-79aea586-bb01-47fc-813f-fdd606f3efaa.png)

**Comment by timoast** [comment]
Yes, you can analyze v3.0.2 objects using Seurat v3.2.1.

Major version changes (v2.X, v3.X, v4.X) require that you update the Seurat object, which can be done using `UpdateSeuratObject()`

**Comment by hahahah-single** [comment]
Hi @timoast Thank you very much for your answer, so  can I understand that for the use of seurat in the small version(v3.X), each object can be used in different version?  For example if  I  can analyze objects are generated by Seurat v3.2.2 using Seurat v3.1.5 for some common operations？
