### ISSUE TITLE
applying a signature to a specific cluster of cells

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#495]
Hello,
I would like to apply a signature of M1/M2 macrophages ( a set of genes discriminating the two cell types) to a specific cluster to check whether there is a specific enrichment of one of the two.
Any suggestion on how to proceed?
Thanks
Paolo

**Comment by satijalab** [comment]
This is a similar problem as scoring cells into cell cycle phases based on previously identified signatures. See the AddModuleScore function, and our cell cycle vignette:

https://satijalab.org/seurat/cell_cycle_vignette.html

**Comment by batis2ta** [comment]
Sorry may be a strange question but how do you do the clustering when you have 3 Modulescores?

**Comment by thetapper** [comment]
Hi @paolo-kunderfranco, you need to wrap your genelist-vector into a list to get one combined score instead of individual scores for each gene. Hope that's what you meant.

For example:
```
gene.list = c("STAT3", "STAT5A", "RORC")

seurat.data = AddModuleScore(
  object = seurat.data,
  genes.list = list(gene.list),
  enrich.name = 'my_mod_score'
)
```
