### ISSUE TITLE
Spatial Data Pixels to um

### ISSUE THREAD

**Issue by sylvia-science** [satijalab/seurat#4952]
Hi,

I need to convert pixels to um in my spatial data. Is there any place this info is stored in the Seurat object? I was also thinking I could get the conversion by checking the distance between two neighbouring cells and assuming it's equal to 55um.

**Comment by mojaveazure** [comment]
Hi Sylvia,

Sorry for the late response. We do not have the ability to convert pixels to µm; you can possibly use a tool like ImageJ to accomplish this task
