### ISSUE TITLE
Can you public the repo of this site?

### ISSUE THREAD

**Issue by DawnEve** [satijalab/seurat#4954]
In fact, I could not open this site for a long time, for some unknown reason. I once saved an old version locally nowadays.

I think I can read it locally if it is a static website.
So could you kindly provide the repo of seurat website, so I can read more update information?

**Comment by timoast** [comment]
The Seurat vignette code is public and is part of this repository: https://github.com/satijalab/seurat/tree/master/vignettes

**Comment by DawnEve** [comment]
I know this Rmd files, but I cannot see images in these tutorials, its hard to imagine the result of these code.
