### ISSUE TITLE
Getting csv.gz file in the format which is accepted by Seurat

### ISSUE THREAD

**Issue by sameehan2301** [satijalab/seurat#4959]
Hello all,
I am trying to analyze a dataset which is already published in a paper and when I downloaded and imported the csv.gz file in RStudio, I found that the columns were as shown in the attached screenshot. The first column (CellId) contains the same cell barcode for ~ 6000 rows. The second column (GeneId) has like ~6000 genes which keep on repeating for one cell and then the next cell. The third column is the Count.
<img width="783" alt="Screen Shot 2021-08-16 at 6 45 43 PM" src="https://user-images.githubusercontent.com/64989134/129984296-38fd1d7e-6c63-4dbe-9bf8-48ed1080ffec.png">

When I contacted the authors of the dataset, they send me the following code to convert the csv.gz file to a matrix which is accepted in Seurat (to CreateSeuratObject function). 

make_to_readcounts_matrix<-function(readscsv){
  temp<-with(readscsv, sparseMatrix(i = as.numeric(CellId), j=as.numeric(GeneId), x=Count,dimnames=list(levels(CellId), levels(GeneId))))
  return(temp)
}

However, I have not be able to make the code work in order to get the matrix which is acceptable for Seurat. Can someone please assist me? Thank you !!

**Comment by torkencz** [comment]
Hi, off the top of my head it might be that in your read csv the columns are not factors at the moment, therefore the as.numeric fuction cannot assign a number to them. I would do readcsv$CellId<-as.factor(readcsv$CellId) and readcsv$GeneId<-as.factor(readcsv$GeneId). Things should work from there. If this doesn't solve your problem I can reopen (please include error message in that case).
