### ISSUE TITLE
subSet cluster and Jackstrow function

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#496]
Hello,
I would like to subset cells belonging only to a specific cluster as:
```R
C_subset_0<-SubsetData(C,ident.use=0,do.clean=TRUE)
```
then I started back with filtering, normalization, find variable genes, scale data and runPCA,
When I determine statistically significant principal components through JackStrawPlot function I noticed that the PC are not ordered by increase significance, in details the first two are significant, then up to PC12 not, and then back the PC13 is significant, why? 
How do I selected components to FindClusters? 
Is there something I did wrong?
Many Thanks,
paolo

**Comment by leonfodoulian** [comment]
Hi,

I don't think there is anything wrong with what you are doing. I also have cases where this happens. My approach is to select those PCs that are significant using a forward selection approach (stop at the PC where the subsequent one is not significant).

Best,
Leon

**Comment by paolo-kunderfranco** [comment]
Thanks Leon, so even if the PC13 is significant, I consider only the first two?
paolo

**Comment by leonfodoulian** [comment]
@paolo-kunderfranco,

I can not say which approach is more correct than the other. Some people simply select PCs based on the variance they explain, others use the elbow method (implemented in the `Seurat::PCElbowPlot()` function). I stick to using `Seurat::JackStraw()` and find that the forward selection approach is often robust in selecting the most informative PCs.

Best,
Leon
