### ISSUE TITLE
Cannot open the main website "https://satijalab.org/seurat" to access documentation.

### ISSUE THREAD

**Issue by puyiyi** [satijalab/seurat#4960]
I cannot open the website "https://satijalab.org/seurat" with my google chrome in China now. I have opened and browsed it yesterday.
Please help me check the reason.

Regards
Yiyi

**Comment by saketkc** [comment]
The website is up and [running](https://downforeveryoneorjustme.com/satijalab.org?proto=https). You can find the Rmd for vignettes [here](https://github.com/satijalab/seurat/tree/develop/vignettes)

**Comment by caoqiuyu** [comment]
> I cannot open the website "https://satijalab.org/seurat" with my google chrome in China now. I have opened and browsed it yesterday. Please help me check the reason.
> 
> Regards Yiyi

I can't get this website open either, can you open it up now?

**Comment by wu1997-shu** [comment]
> > I cannot open the website "https://satijalab.org/seurat" with my google chrome in China now. I have opened and browsed it yesterday. Please help me check the reason.
> > Regards Yiyi
> 
> I can't get this website open either, can you open it up now?

and one
