### ISSUE TITLE
UMAP of TRA/B sequences

### ISSUE THREAD

**Issue by cgraham13** [satijalab/seurat#4962]
Hello,

I have output from a single cell sequencing run that has both the VDJ and gene expression data. For the same cells, we also used a hybrid capture approach to sequence the TCR sequences. I have compared the TCR sequences across the two approaches and I have found a list of TRA and TRB cdr3 sequences that overlap. For the TRA sequences, there are 101 cells that were identified in both approaches. From here, I would like to use dimplot to look at a UMAP of where these cells fall in the clustering. 

I have used the code below to integrate the vdj and gene expression data:

```r
tcr <- read.csv(paste("/Users/carlygraham/Dropbox/BramsonLab/scRNAseq-Feb16/Multi_TAC_Output_v2/vdj/", "filtered_contig_annotations.csv", sep=""))

tcr <- tcr[!duplicated(tcr$barcode), ]

# Only keep the barcode and clonotype columns. 
# We'll get additional clonotype info from the clonotype table.
tcr <- tcr[,c("barcode", "raw_clonotype_id")]
names(tcr)[names(tcr) == "raw_clonotype_id"] <- "clonotype_id"

# Clonotype-centric info.
clono <- read.csv(paste("/Users/carlygraham/Dropbox/BramsonLab/scRNAseq-Feb16/Multi_TAC_Output_v2/vdj/","clonotypes.csv", sep=""))

# Slap the AA sequences onto our original table by clonotype_id.
tcr <- merge(tcr, clono[, c("clonotype_id", "cdr3s_aa")])

# Reorder so barcodes are first column and set them as rownames.
tcr <- tcr[, c(2,1,3)]
rownames(tcr) <- tcr[,1]
tcr[,1] <- NULL

# Add to the Seurat object's metadata.
scRNAseq.seurat <- AddMetaData(object=scRNAseq.seurat, metadata=tcr)

```

This effectively gives me a seurat object with the cdr3 as metadata 

> head(scRNAseq.seurat$cdr3s_aa)
                                                         AAACCTGAGCGTGTCC-1 
                        "TRB:CASGRTGTYEQYF;TRA:CAAREGDKIIF;TRA:CASDAGNMLTF" 
                                                         AAACCTGAGGCTCAGA-1 
          "TRB:CASSVPPGNTEAFF;TRA:CALSEGGLMYSGGGADGLTF;TRA:CAVGHSSGSARQLTF" 
                                                         AAACCTGAGTGCGATG-1 
                                   "TRB:CSGKEGGMGTEAFF;TRA:CALSDRGSGNTPLVF" 
                                                         AAACCTGCAAAGTGCG-1 
"TRB:CASSEWGRGDTQYF;TRB:CASSHASIGNNEQFF;TRA:CAVRDQGRLMF;TRA:CAVTVNTNAGKSTF" 
                                                         AAACCTGCAAGGGTCA-1 
                                    "TRB:CASSRGWRQETQYF;TRA:CAAPINFGNEKLTF" 
                                                         AAACCTGCACGCGAAA-1 
                "TRB:CASSPTGRDNTEAFF;TRA:CAYGPPPAGNMLTF;TRA:CGAVNSGGYQKVTF" 

From here is there a way to pull out some of the cells and display them on the UMAP? 

Ex. pull out the cells with TRA:CAYGPPPAGNMLTF and TRA:CAAREGDKIIF?

Thanks!

**Comment by timoast** [comment]
Hi, you can use the [`WhichCells()`](https://www.rdocumentation.org/packages/SeuratObject/versions/4.0.2/topics/WhichCells) function to find cells matching a desired metadata value, and then highlight those cells on the UMAP using `cells.highlight` parameter in `DimPlot()`.

example:

```R
cells.highlight <- WhichCells(obj, expression = cdr3s_aa == "TRA:CAYGPPPAGNMLTF" | cdr3s_aa == "TRA:CAAREGDKIIF")
DimPlot(obj, cells.highlight = cells.highlight)
```

**Comment by cgraham13** [comment]
Thanks for the quick response! 

Unfortunately, that doesn't quite work at I need to highlight cells with a partial match. For example the cdr3s_aa column for the first cell above has "TRB:CASGRTGTYEQYF;TRA:CAAREGDKIIF;TRA:CASDAGNMLTF" so the code you have provided doesn't find any cells.
