### ISSUE TITLE
FindMarkers: Gate the threshold for pct.1 and pct.2

### ISSUE THREAD

**Issue by alicekao1118** [satijalab/seurat#4965]
Hi,

I wonder if Seurat could gate gene's expression when doing the calculation of pct.1 or pct.2 in FindMarkers function. For my example below, group 2 has a great portion of cell expressing this gene, but the expression level is very low. (x-axis indicates each cell, y axis was the data extracted from the "object@assays$integrated$scale.data" (in my understanding, it's the normalized expression data)

I'd like to remove the low expression cell from counting into pct.2, is that possible?

<img width="903" alt="Screen Shot 2021-08-20 at 2 56 28 PM" src="https://user-images.githubusercontent.com/82248085/130193176-beaa0061-9997-4803-bf04-09c59acc9e49.png">

Thank you so much!!

Alice

**Comment by rsatija** [comment]
You can use the `min.pct` and `min.dif.pct` arguments to `FindMarkers` to gate on percentages (documentation for both parameters is in `?FindMarkers`

**Comment by alicekao1118** [comment]
Yes, I've tried to adjust `min.pct `and `min.dif.pct`, but I think it won't help to gating percentages, the gating percentages I mean here is the number of cell counting into pct.2, not using the result to gate the percentage.

To be clear, in the picture shown above, how do I remove those low-expression cells from counting into pct.2? Since I'm not sure if it's background or other reason.
