### ISSUE TITLE
How to change the font size in DoHeatmap

### ISSUE THREAD

**Issue by mengfeich** [satijalab/seurat#4971]
I was trying to change the size of the gene name under DoHeatmap, but I got the warning message that could not find function "theme", but I just installed the ggthemes.

Here are my codes, thanks in advance.

library(ggthemes)
DoHeatmap(pbmc, features = top10$gene) + theme(axis.text.y = element_text(size = 5))
Error in theme(axis.text.y = element_text(size = 5)) :
could not find function "theme"

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  ggthemes is package containing extra themes and geoms for ggplot2.  The `+ theme(...)` is part of ggplot2 package.

Best,
Sam

**Comment by mengfeich** [comment]
I do have ggplot2 package, but it still returns the error could not find the function "theme"

**Comment by samuel-marsh** [comment]
can you paste the output of `sessionInfo()`?
