### ISSUE TITLE
Exporting Seurat Clusters, genotype, Cell IDs in one CSV?

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#4974]
Hello!

I have seen codes on how to extract cell clusters and IDs for certain cells and to write them as separate files, but I was wondering if it is possible to extact the Cell IDs and corresponding `Clustername` and `genotype` (both in the `metadata`) all in CSV?
![image](https://user-images.githubusercontent.com/68068335/130364191-81e07968-0fd9-4bfb-8c69-b1f50d0e2b57.png)

I managed to export the Clusters and genotypes without CellID which is not what I wanted...anyone have ideas?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Since meta.data slot is just a data.frame you can manipulate it as you would any data.frame.  In order to do what you are asking you could run the following:
```
library(dplyr)
library(tibble)
library(Seurat)

export_df <- obj@meta.data %>% 
  rownames_to_column("barcodes") %>%
  select(barcodes, genotype, Clustername)

write.csv(export_df, "/path/to/file.csv")
```

Best,
Sam

**Comment by AAA-3** [comment]
Will try that! I just ended up exporting the whole metadata table and manipulated it in excel LOL
