### ISSUE TITLE
create spatial object from nono-10x data

### ISSUE THREAD

**Issue by cadyyuheng** [satijalab/seurat#4993]
Hello,

I'm also trying to create a spatial Seurat from scratch. While your hints in #3595 are quite straightforward to me for the term image and coordinates. However, I still don't quite get what scale.factors are other than it is a separate object. As I look into scalefactors function, I noticed scalefactors is defined by spot, fiducial, hires, and lowres values. From the doc, I don't fully understand what those values mean and how I could generalize them for my own data and image. Would you mind elaborating a bit more? I really appreciate your help!

**Comment by mojaveazure** [comment]
The scale factors serve as a link between the coordinates and the image data. There are four scaling factors that 10X provides, but we generally only use the `lowres` factor. If you're using your own, non-10X data, simply create a fake `scalefactors` object with `scalefactors`, making sure that you use the correct factor for `lowres`. If you coordinates match 1:1 with your image, then your lowres scale factor would be 1
