### ISSUE TITLE
ERROR:FindAllMarkersNode

### ISSUE THREAD

**Issue by mplass** [satijalab/seurat#50]
The function FindAllMarkersNode crashes when the node from where to start is not set.

FUNCTION CALL:
all.markers.node <- FindAllMarkersNode(nbt, only.pos = TRUE, min.pct = 0.25,  min.diff.pct=0.25,thresh.use = 0.25)

ERROR:
Error in set.ifnull(node, tree$edge[1, 1]) : object 'tree' not found

I think the problem is the tree variable name and tree$edge[1, 1] should be object@cluster.tree[[1]]$edge[1,1]

**Comment by mschilli87** [comment]
@mplass: If you don't here back from the dev's (I didn't, even after sumitting a pull request with a fix), we can try to fix it in my fork so at least you can install a working version.

@nukappa: Should we consider moving one of our forks to @rajewsky-lab, merge in the other(s) and maintain our own Seurat fork with these kind of fixes?

**Comment by mplass** [comment]
If you think you can do it guys, fine by me!

**Comment by mschilli87** [comment]
@mplass: I applied your suggested fix (see https://github.com/mschilli87/seurat/commit/9dbdd53557fda9aceda1c092d61f9e2688d4cae0).

You can test it by re-installing Seurat from the [corresponing branch](https://github.com/mschilli87/seurat/tree/mplass_fix) of [my fork](https://github.com/mschilli87/seurat):

```r
require(devtools)
devtools::install_github("mschilli87/seurat@mplass_fix")
```

Note that you will have re-load Seurat or start a new R session to start using the new version.

Let me me know how you testing goes.

**Comment by mplass** [comment]
Thanks!

**Comment by andrewwbutler** [comment]
Thanks for the bug report and subsequent fix! This is now been corrected in our version as well.
