### ISSUE TITLE
VlnPlot split by

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [satijalab/seurat#5006]
Hey everyone,
I have a question regarding the VlnPlot function. In the previous Seurat versions when one used both split by and group by arguments, would get a plot like this:
![image](https://user-images.githubusercontent.com/60395255/130971555-9d4ac6b3-af1a-4eaf-bd52-5ce6593062f9.png)
With the latest update, when I use both arguments I get a plot like this one:
![image](https://user-images.githubusercontent.com/60395255/130971982-e005ed79-a1b2-49bb-8e94-3fd725fcad17.png)

Is there a way to visualize the plot similar to the first one in the newest seurat version?
Thanks a lot!

**Comment by danyama312** [comment]
Hi there,

I am having another problem now with making split violin plots using VlnPlot.

When running the code below I get the following plot where the two split distributions are separated, while I would like them to be connected. Any ideas why? 

`VlnPlot(olig, features="MA0804.1", split.by = "subcluster_name", split.plot=TRUE, pt.size=0)`

![image](https://user-images.githubusercontent.com/93013930/167421791-16d37194-4730-4f4c-ab76-1bd7ccf58b9e.png)

Thanks!

**Comment by coffeeCowLu** [comment]
> 

use group.by = 'group', group only contain one group.
