### ISSUE TITLE
How can I get tSNE_3 from seurat object?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#501]
I would like to use first three dimensions of tSNE to visualize in 3D plot. Is it possible to get tSNE_3 from Seurat object.

Extracting tSNE_1 and tSNE_2 using FetchData works but not with tSNE_3.

```R
FetchData(sObj, c('tSNE_1','tSNE_2','tSNE_3'))
Error in FetchData(sObj, c("tSNE_1", "tSNE_2", "tSNE_3")) : 
  Error: tSNE_3 not found
```

**Comment by mschilli87** [comment]
@bishwaG: Did you set `dim.embed = 3` when running `RunTSNE`?

**Comment by bishwaG** [comment]
@mschilli87 Thanks! Did not expect to be that easy :)
