### ISSUE TITLE
CreateSeuratObject() Warning message: In storage.mode(from) <- "double" : NAs introduced by coercion

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#5015]
Hello. Can anyone help me convert this "Matrix table with raw gene counts for every gene and every cell" into Seurat object? The public data source is accessed from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4616047

Using this code below, I encounter a warning that affects downstream processing:

```
#Read scRNAseq expression data
Object.data <- read.table(file = "GSM4616047_scRNA-Seq_of_enriched_monocytes_matrix.txt.gz", sep = "", header=TRUE, row.names=1, as.is=T) 

head(Object.data)
```
![this](https://user-images.githubusercontent.com/68268222/131242031-238401f7-ff36-4345-b329-d261eae51948.png)

```
#Create Seurat object
Object <- CreateSeuratObject(counts = Object.data, min.cells = 3, min.features = 200)

Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion
```
The previous issues raised did not solve my concern. Thank you!

**Comment by torkencz** [comment]
Thanks @samuel-marsh, I think that should work for this issue.
