### ISSUE TITLE
How to correlate two module scores together

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#5019]
Hello!

I am fairly new to R, so maybe this is more obvious, but how do you find correlations between two module scores? Borrowing from https://github.com/satijalab/seurat/issues/1311 and https://github.com/satijalab/seurat/issues/519, I have this so far:

```
matrix <- GetAssayData(object = comparison)
matrix_mod<-as.matrix(matrix)
module1<-as.numeric(comparison@meta.data$"module_score1")
module2<-as.numeric(comparison@meta.data$"module_score2")
correlations<-apply(matrix,1,function(x){cor.test(module1, module2)})

corresults <- sapply(correlations, unlist)
corresults <- t(corresults)
write.csv(corresults, file = "module1-2_correlation.csv")
```

However, when I open the file, the t statistics all have the same value, as do the confidence levels, so I don't think I did it right.

Thanks for reading!

**Comment by mhkowalski** [comment]
Maybe  I don't understand what you are trying to do here, but finding the correlation between 2 module scores will result in one correlation (and one t-statistic). In the issues you mention, the users were trying to find the correlation of a module score with multiple genes.  Also, you could simply do `cor.test(module1, module2)`.  

Feel free to reopen if this does not address your question.

**Comment by ksaunders73** [comment]
Hello @mhkowalski ! 

Is there a way to compute it for each cell? Or essentially see which genes from each module score are correlated with each other? If that makes sense.
