### ISSUE TITLE
Question on fit assessment using Seurat

### ISSUE THREAD

**Issue by jamesdalg** [satijalab/seurat#5020]
I read your paper that looks at overdispersion here: https://www.biorxiv.org/content/10.1101/2021.07.07.451498v1.full.pdf
In this particular paper, a main point is the assessment of fit and overdispersion. I am unaware of any clear function from which I can determine goodness of fit (e.g. χ^2, AIC, etc) for the individual models as well as a measure of overdispersion (θ in the paper). I have a time series dataset and I'm trying a lot of different methods to see what works best, but I need something to measure by in order to know which method to select. Diagnostic plots could be really helpful as well. Also, I'm not here to critique the paper at all; I'm just trying to assess the fit of the model and determine what's best for my particular use case.

**Comment by saketkc** [comment]
The goal in our paper was to ask if Poisson is indeed a good fit for the model. We used a chi-square statistic calculated on GLM (poisson family, log link) [residuals](https://www.jstor.org/stable/1390802) to ask if the observed distribution indeed follows a chi-squared distribution. The goal here was to ask if Poisson distribution is sufficient to explain the heterogeneity in observed counts (higher deviation from expected Chi-squared indicates it isn't).

You can use AIC/BIC/WAIC for model selection (Poisson vs NB). Tests for overdispersion are in Cameron and Trivedi, Journal of Econometrics, 1990.

**Comment by jamesdalg** [comment]
Thanks very much for the response. The issue isn't to understand the paper. I understand it completely. It was really well written and pretty straightforward. Using the package, how exactly do I find the AIC of the models that Seurat generates? I'm attempting to select the best model, but I can't know which actually has the best fit because there is no inherent model assessment functionality in the package.

**Comment by saketkc** [comment]
Right, so this will need to be done out of Seurat. I am not sure I understand your goals, but if you are looking to asses two models, here's how you would do it (not that in SCTransform, we fit just one model): 

```r
m1 <- MASS::glm.nb(gene_umi ~ offset(log(libsize) )
m2 <-  MASS::glm.mb(gene_umi ~ offset(log(libsize) + batch_var)
aic(m1, m2)
```

**Comment by saketkc** [comment]
Also to clarify, the goal of SCTransform is not to find the "best fit", the goals is to learn the overall model of technical noise, which is where the regularized NB helps. Some motivation in [the slides here](https://drive.google.com/file/d/1mbFNhQYHlVsKThIuhDfe_ouz-FkHdpGo/view)
