### ISSUE TITLE
Can I compare gene expression between genes in the DoHeatmap function?

### ISSUE THREAD

**Issue by fritzherbert** [satijalab/seurat#5028]
Hi,

I use AverageExpression and DoHeatmap to generate my heatmaps. I have recently read the following article: http://stanstrup.github.io/heatmaps.html   that stated that heatmaps are sometimes only scaled by row and not by column. I would like to compare expression levels between genes in my heatmap. Is that already possible in the DoHeatmap function or do I need to perform additional steps ? If so which ?

Thank you!

**Comment by liuxl18-hku** [comment]
`DoHeatmap()` by default use `slot = "scale.data"`. The data is more suitable for comparison cross cells.

Based on my understanding, there is __no directly available__ expression matrix scaled by column. There are many ways, one possible way is extract "un-scaled" expression matrix and perform scaling and heatmap visualization by ourselves.

The "unscaled" expression matrix is located at `obj@assays$RNA@data`, where `obj` is your seurat object. It's a sparse matrix, you may need to convert it to dense one by `as.matrix()` for some heatmap R package, for example [pheatmap](https://cran.r-project.org/web/packages/pheatmap/index.html).

A minimum demon could be like this:

```r
library(Seurat)
library(pheatmap)

# pls load your seurat object first

exp_dense <- as.matrix(obj@assays$RNA@data)
pheatmap(exp_dense, scale = "column")
```

**Comment by yuhanH** [comment]
HI @liuxl18-hku 
Thanks for your reply. I totally agree with you. 
Add one point. In `ScaleData`, we scale each gene's expression across all cells.
