### ISSUE TITLE
Unexpected behavior for 'subset' function (== vs %in%)

### ISSUE THREAD

**Issue by mass-a** [satijalab/seurat#5032]
I have noticed some unexpected behavior for the subset function on Seurat objects.
This is related to subsetting on multiple values of a discrete metadata field, in the case someone (accidentally or not) uses the `==` operator instead of `%in%`. Consider the following example using your pmbc 3k dataset from the tutorials:
```
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19/")

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc
```
```
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features, 0 variable features)
```
Now I invent some categorical metadata with three possible values:
```
pbmc$celltype <- "type1"
pbmc$celltype[1:1000] <- "type2"
pbmc$celltype[1001:2000] <- "type3"
table(pbmc$celltype)
```
```
type1 type2 type3 
  700  1000  1000 
```
A correct way of subsetting the Seurat object for two of three cell types would be the `%in%` operator:
```
use.in <- subset(pbmc, subset = celltype %in% c("type1","type2"))
table(use.in$celltype)
```
```
type1 type2 
  700  1000 
```
An incorrect way of subsetting the data would be to use the `==` operator. However, instead of throwing an error or  a warning, the query returns half of the cells for each class:
```
use.eq <- subset(pbmc, subset = celltype == c("type1","type2"))
table(use.eq$celltype)
```
```
type1 type2 
  350   500 
```

I find this behavior a bit bizarre, and since there are no warnings a user may think they have subset their cells correctly.
I know one should not use `==` in this case, but people will make this kind of mistake time and again (see e.g. [this issue](https://github.com/carmonalab/ProjecTILs/issues/18)). Perhaps adding a warning would be enough as a heads-up?

Thanks for reading,
-massimo

**Comment by mojaveazure** [comment]
This is not a bug, but a replication of standard R behavior. Because we try to replicate standard R behavior, especially with regards to data frame-like functionality, this is not something we can correct. Users should be comfortable with base-R functionality when using Seurat

```R
> df <- data.frame(celltype = rep_len('type1', 2700))
> df$celltype[1:1000] <- 'type2'
> df$celltype[1001:2000] <- 'type3'
> table(df$celltype)

type1 type2 type3 
  700  1000  1000 
> dd <- subset(df, celltype == c('type1', 'type2'))
> table(dd$celltype)

type1 type2 
  350   500 
```
