### ISSUE TITLE
Few cells remains after QC

### ISSUE THREAD

**Issue by beginner984** [satijalab/seurat#5034]
Hello Seurat Team

I have 3' multiome 10X

I use this tutorial https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html of WNN

```
library(Seurat)
library(Signac)
library(EnsDb.Hsapiens.v86)
library(dplyr)
library(ggplot2)

# the 10x hdf5 file contains both data types. 
inputdata.10x <- Read10X_h5("filtered_feature_bc_matrix.h5")

# extract RNA and ATAC data
rna_counts <- inputdata.10x$`Gene Expression`
atac_counts <- inputdata.10x$Peaks

# Create Seurat object
pbmc <- CreateSeuratObject(counts = rna_counts)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

# Now add in the ATAC-seq data
# we'll only use peaks in standard chromosomes
grange.counts <- StringToGRanges(rownames(atac_counts), sep = c(":", "-"))
grange.use <- seqnames(grange.counts) %in% standardChromosomes(grange.counts)
atac_counts <- atac_counts[as.vector(grange.use), ]
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "hg38"

frag.file <- "atac_fragments.tsv.gz"
chrom_assay <- CreateChromatinAssay(
  counts = atac_counts,
  sep = c(":", "-"),
  genome = 'hg38',
  fragments = frag.file,
  min.cells = 10,
  annotation = annotations
)
pbmc[["ATAC"]] <- chrom_assay
```

You are seeing the number of my cells before QC

```
> pbmc
An object of class Seurat 
103009 features across 26473 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
1 other assay present: ATAC
>
``` 

```
VlnPlot(pbmc, features = c("nCount_ATAC", "nCount_RNA","percent.mt"), ncol = 3,
        log = TRUE, pt.size = 0) + NoLegend()
```
![Rplot](https://user-images.githubusercontent.com/43682980/131835425-650fc258-ae5d-4b5d-918e-7f3a0560e595.png)

But after QC I am losing most my cells 

```
pbmc <- subset(
  x = pbmc,
  subset = nCount_ATAC < 7e4 &
    nCount_ATAC > 5e3 &
    nCount_RNA < 25000 &
    nCount_RNA > 1000 &
    percent.mt < 20
)

> pbmc
An object of class Seurat 
103009 features across 3713 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
1 other assay present: ATAC
>

```

You think losing these number of cells is normal? I have been trying another thresholds like 

```
pbmc <- subset(
  x = pbmc,
  subset = nCount_ATAC < 7e4 &
    nCount_ATAC > 500 &
    nCount_RNA < 10000 &
    nCount_RNA > 200 &
    percent.mt < 20
)
```

But no big difference

```
> pbmc
An object of class Seurat 
103009 features across 10685 samples within 2 assays 
Active assay: RNA (36601 features, 0 variable features)
1 other assay present: ATAC
>

```

Please help me I am really puzzeled here

**Comment by mhkowalski** [comment]
It seems that both the `percent.mt < 20`  filtering parameter will remove most of your cells based on the violin plots you show above. I  would suggest increasing that threshold (and also `nCount_ATAC < 7e4` ) in order to keep more cells.

**Comment by beginner984** [comment]
Thank you, my samples are highly contaminated with MT genes, does keeping these genes interfere in my results? Sorry you meant I should keep `nCount_ATAC < 7e4` ?

**Comment by mhkowalski** [comment]
You could try increasing `nCount_ATAC < 7e4` as well. High MT gene  expression might be an indicator of poor sample quality or a lot of dying cells. I would not remove the mitochondrial genes, but I would keep this in mind as you analyze your data.  For example, you might notice that in downstream analyses that cells with high MT gene expression may cluster together.

**Comment by beginner984** [comment]
Thank you so much

Please look at the answer here

https://bioinformatics.stackexchange.com/questions/16447/help-with-seurat-qc-ambiguity/16455#16455

People believe I better remove MT genes

I am puzzled at this point because your concept also seems reasonable

**Comment by mhkowalski** [comment]
Hi, 

The author of this answer refer to removing cells with percent.mt threshold exceeding a certain amount, _not_ the mitochondrial genes themselves. If it were me, I would start with a more lenient threshold and investigate these cells, and potentially remove these cells in your downstream analyses if they seem to be low quality.

**Comment by beginner984** [comment]
Thank you so much once more

As you are considering below, my samples seem to have high percentage of MT genes
![Hqj48](https://user-images.githubusercontent.com/43682980/132074575-6f8c486a-d208-4a9d-bbed-1f141c223492.png)

So you think I should be more relaxed in removing `percent.mt < 20` to something like `percent.mt < 10`
