### ISSUE TITLE
Seurat Object for Monocle3   ('data' must be of a vector type, was 'NULL')

### ISSUE THREAD

**Issue by Leonrunning** [satijalab/seurat#5036]
Hi there,

I am working on pseudotime analysis of a Seurat 4.0.4 object using Monocle3. The UMAP and clustering information were kept. While the pseudotime can be plotted, I am stuck with the "find_gene_modules" function. The error message is attached below.

It used to work well when I was using Seurat 3 on another project. If I re-analyze the Seurat data with Monocle "preprocess" and "cluster_cell" functions, the "find_gene_modules" function works. However, I want to keep the UMAP information of Seurat as that is different with the output of Monocle3.

I would be really appreciated if anyone can provide some solutions.

thanks

"Code: gene_module_df <- find_gene_modules(Test.cds[pr_deg_ids,], resolution=0.01,random_seed=2)"
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

**Comment by Leonrunning** [comment]
> Hi, could you provide some info about your cds and the session you are running?

Hi,

My cds is converted from a Seurat V4.0.4 object processed by scTransform. To overcome the issues with this new version or the outcomes of scTransform, the DietSeurat was used. After transformation, the cds project was used for pseudotime analysis in Monocle3 without going through the "preprocess" function. It was processed directly with "cluster_cell", "learn_graph", "order_cells" and "learn_graph" functions following the vignette of Monocle3, which all works fine. 

The issue occurs at the session of "differential expression analysis" << "find modules of co-regulated genes". Here more codes are attached for your references.

thanks for your help

####DietSeurat
Test_Diet <- DietSeurat(Test, counts=TRUE, data=TRUE,  dimreducs = "umap")
Test_Diet[["UMAP"]] <- Test_Diet[["umap"]]
#####Transformation to cds and do the pesudotime
Test.cds <- as.cell_data_set(Test_Diet)
Test.cds <- cluster_cells(cd=Test.cds,reduction_method = "UMAP")
Test.cds <- learn_graph(Test.cds,use_partition = TRUE)
Test.cds <- order_cells(Test.cds, reduction_method = "UMAP")
plot_cells(cds = Test.cds, label_cell_groups = FALSE, color_cells_by = "pseudotime", show_trajectory_graph = TRUE, label_branch_points = TRUE, label_leaves = TRUE, label_roots = TRUE)


Test.cds <- estimate_size_factors(Test..cds)
Test.cds@rowRanges@elementMetadata@listData[['gene_short_name']] <- rownames(Test.cds[['RNA']])

#####find gene modules
Test.cds.test_res <- graph_test(Test..cds, neighbor_graph = 'principal_graph', cores = 4)
pr_deg_ids <- row.names(subset(Test.cds.test_res, q_value < 0.05))


#######The error occurs here
gene_module_df <- find_gene_modules(Test.cds[pr_deg_ids,], resolution=0.01,random_seed=2)

"Code: gene_module_df <- find_gene_modules(Test.cds[pr_deg_ids,], resolution=0.01,random_seed=2)"
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), :
'data' must be of a vector type, was 'NULL'

**Comment by troks27** [comment]
Same issue as @Leonrunning

**Comment by rsatija** [comment]
Closing as this is a monocle3 issue (though it can arise after Seurat conversion), with a solution posted [here](https://www.biostars.org/p/424556/)
