### ISSUE TITLE
How to approach to find unique markers for a cluster

### ISSUE THREAD

**Issue by Deepesh123gupta** [satijalab/seurat#5037]
Hello, 

I have a question about selecting a unique cluster marker from an integrated SeuratObject. 

Let us assume that I have 4 clusters i.e. A, B, C, D where A, B represent cell type A while C,D represent cell type B. To find unique markers for cell type A , I dig into DEGs (list from FindAllMarkers) and found markers (gene x and gene y) for those. But Later I realized that these markers are also visible in the cell type B clusters using DotPlot (C,D)[50-75% cell expressed but expression level is half in B cell type that around]

1) Do we consider gene x and gene y unique markers for cell type A?
2) if not, what are the criteria to find unique markers from a cluster ?

Thanks

**Comment by torkencz** [comment]
Hi,
There is not full proof way of identifying marker genes and it takes some iterations until you find the right ones. Generally, when looking at the output of FindALLMarkers, I would suggest looking for marker genes with large differences in expression between pct.1 and pct.2 and larger fold changes. For instance if pct.1 = 0.90 and pct.2 = 0.80 and had lower log2 fold changes, that marker might not be as strong of a candidate. However, if pct.2 is 0.1 instead, then it would be a lot more exciting. In your case I would do a follow up by clumping the clusters A and B vs C and D together and then doing FindMarkers. It might result in showing the same marker you mentioned. A marker for a cluster is preferably only expressed in that cluster alone, however the example you provided could be the best case for your data.
