### ISSUE TITLE
number of dimensions  during and after integrating data

### ISSUE THREAD

**Issue by ineshidalgoprados** [satijalab/seurat#5041]
Hi! I integrated two scRNAseq datasets together with the CCA method using FindIntegrationAnchors and IntegrateData before Scaling the data. I saw that the default in the FindIntegrationAnchors function is dims = 1:30. However, at that point, I don't know the dimensionality of my integrated dataset, since the RunPCA comes next.

Should the number of dimensions (dims) be the same while integrating the data (FindIntegrationAnchors) and for RunPCA, FindNeighbors and RunUMAP?

thanks so much!!

**Comment by torkencz** [comment]
Hi,
IntegrateData is supposed to give back the same high dimensional data that you provided it with (so in the case of https://satijalab.org/seurat/articles/integration_introduction.html, your variable features across all of the cells you are trying to integrate). Afterwards you reduce those further via PCA on which you run FindNeighbors, RunUMAP (so in the example 30 dims).
