### ISSUE TITLE
Error converting Summarized experiment to .sce object

### ISSUE THREAD

**Issue by Stole31** [satijalab/seurat#5042]
We are trying to convert a SummarizedExperiment from La manno et al 2021 (part of the data) from RDS to seurat SCE 
it gives us this error 
test <- readRDS(file = "Forebrain_SumExp_LaManno.RDS")
test.sce <- as.SingleCellExperiment(test)
Error in UseMethod(generic = "as.SingleCellExperiment", object = x) : 
  no applicable method for 'as.SingleCellExperiment' applied to an object of class "c('SummarizedExperiment', 'RectangularData', 'Vector', 'Annotated', 'vector_OR_Vector')" 
  
  Any idea how to proceed ? we are using Seurat 4 for this.

**Comment by samuel-marsh** [comment]
Hi,

not member of dev team but hopefully can be helpful.  The `as.SingleCellExperiment` function is for converting Seurat objects to SCE objects so will not work converting non-Seurat objects to SCE.

See this post for converting SummarizedExperiment to SCE:  https://support.bioconductor.org/p/9139142/

Best,
Sam

**Comment by torkencz** [comment]
Yes, it needs to be applied to a Seurat object.
