### ISSUE TITLE
Is it possible to swap the order? Violin in front of dots.

### ISSUE THREAD

**Issue by ms-gx** [satijalab/seurat#5043]
Is it possible to swap the order? Violin in front of dots.

_Originally posted by @ms-gx in https://github.com/satijalab/seurat/issues/1497#issuecomment-912462077_

**Comment by torkencz** [comment]
Hi, I do not think it is possible to switch order within Seurat, but since it is based in ggplot I would plot the data directly myself do geom_dotplot first followed by geom_violing, which should work for this. Also the alpha parameter can be helpful here. If it does not work can reopen.
