### ISSUE TITLE
Using different version of seurat 

### ISSUE THREAD

**Issue by hahahah-single** [satijalab/seurat#5044]
My Seurat objects are generated by Seurat v3.2.1 but for some reason I had to use Seurat v3.1.0 for some analysis such as “FindNeighbors” “FindClusters” "subset",Can I use it Seurat v3.1.0 directly?I tried the analysis and no errors were reported. I want to ask if there is anything to pay attention to？Or in the minor version changes（V3.X）, the different versions are actually not very different and can be shared.Or in the minor version changes, the different versions are actually not much different. Data that is not spatial omics can be used with each other for some simple analysis such as “subset”,“FindClusters”.

**Comment by saketkc** [comment]
Version history is available [here](https://satijalab.org/seurat/news/index.html). I would suggest sticking to one version of Seurat (preferably latest - newer versions have improvements and bugfixes).

**Comment by hahahah-single** [comment]
@saketkc Thank you very much for your answer, so can I understand that for the use of seurat in the small version(v3.X), each object can be used in different version if Related functions are not updated ？Just using “FindNeighbors” “FindClusters” "subset" ，can old version Seurat （v3.1.x）be applied to new version objects（v3.2.x）？

**Comment by saketkc** [comment]
The objects themselves can be used across major releases (all Seurat 3.x.x objects are compatible with Seurat 3.y.z).
