### ISSUE TITLE
Duplicate cell names - RunMultiCCA

### ISSUE THREAD

**Issue by ptrcalmeida** [satijalab/seurat#505]
Hi, I was able to add the unique prefixes to each of the 4 indivual 10X datasets that I'm working with prior to CreateSeuratObject using the following, as suggested in #270 :
colnames(x = s1.data) <- paste('S1', colnames(x = s1.data), sep = '_')

It works great: A1_AAACCTGCACGACGAA

However, I still get an error when running RunMultiCCA:
lung.integrated <-RunMultiCCA(ob.list, genes.use=genes.use, num.ccs = 1)

Error in MergeSeurat(object1 = combined.object, object2 = object.list[[i]], :
Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names

Help, please? More info attached. Thank you!

[RunMultiCCA error.txt](https://github.com/satijalab/seurat/files/2042012/RunMultiCCA.error.txt)

**Comment by leonfodoulian** [comment]
Hi,

This issue is a duplicate of issue #400. I have already provided two code lines to check whether you have duplicated cell names in #400.

Best,
Leon

**Comment by ptrcalmeida** [comment]
Thank you, Leon!
