### ISSUE TITLE
MapQuery

### ISSUE THREAD

**Issue by YuliaInn** [satijalab/seurat#5050]
I am following [this tutorial](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html). My code is:
```
pred.anchors <- FindTransferAnchors(reference = hcc_human, query = HCC2_S4,
                                    dims = 1:20, reference.reduction = "pca", k.filter = NA)

HCC2_S4 <- MapQuery(anchorset = pred.anchors, reference = hcc_human, query = HCC2_S4,
                          refdata = list(celltype = "cell_type"), reference.reduction = "pca", reduction.model = "umap")
p1 <- DimPlot(hcc_human, reduction = "umap", group.by = "cell_type", label = TRUE, label.size = 3,
              repel = TRUE) + NoLegend() + ggtitle("Reference annotations (human integrated)")
p2 <- DimPlot(HCC2_S4, reduction = "ref.umap", group.by = "predicted.celltype", label = TRUE,
              label.size = 3, repel = TRUE) + NoLegend() + ggtitle("Query transferred labels (HCC2_S4 9000)")
p1 + p2
```
However, the majority of my querry cells are not there. I have ~15000 cells in the query dataset and ~7000 cells in reference set

![HCC2_S4mappedAll](https://user-images.githubusercontent.com/54861076/132057198-551bdf22-6230-4aa2-9123-f56c2b79de70.png)

then I visualized the cells from both datasets and it looks like all the cells are there

```
hcc_human$id <- 'reference'
HCC2_S4$id <- 'query'
refquery <- merge(hcc_human, HCC2_S4)
refquery[["pca"]] <- merge(hcc_human[["pca"]], HCC2_S4[["ref.pca"]])
refquery <- RunUMAP(refquery, reduction = 'pca', dims = 1:20)
DimPlot(refquery, group.by = 'id', shuffle = TRUE)
```
![query_refHCC2_S4](https://user-images.githubusercontent.com/54861076/132057392-f18455b3-55af-4322-ab36-d0053e70287c.png)

Why aren't all the cells from my query dataset shown in the first image? Does it mean that the majority of the cells were not mapped? Also, why the colors in reference and query umaps are not consistent?

**Comment by timoast** [comment]
`MapQuery()` does not remove cells, so you should have the same number of cells before and after running the function. You can check this using the `ncol()` function. It might appear that there are less cells compared to the reference because the query is projected onto the reference UMAP, and may not span the entire reference UMAP space. The plots shown do not display the density of points, so it's impossible to say which has less or more points.
