### ISSUE TITLE
how to delete cells manuallly?

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#5051]

**Comment by FADHLyemen** [comment]
I want to delete these cells in R, how to do that in Seurat?

Thank you
![image](https://user-images.githubusercontent.com/23288387/132060137-af0729c1-c674-4934-adef-23ebddfc5640.png)

**Comment by timoast** [comment]
You can remove cells in a Seurat object using the `subset()` function, or the `[` operator, for example

```r
cells.keep <- head(colnames(pbmc_small))
pbmc_small[, cells.keep]
```
```
An object of class Seurat 
230 features across 6 samples within 1 assay 
Active assay: RNA (230 features, 20 variable features)
 2 dimensional reductions calculated: pca, tsne
```
```r
subset(pbmc_small, cells = cells.keep)
```
```
An object of class Seurat 
230 features across 6 samples within 1 assay 
Active assay: RNA (230 features, 20 variable features)
 2 dimensional reductions calculated: pca, tsne
```

**Comment by FADHLyemen** [comment]
@timoast 
I know how to use subset, I am asking how subset cells in an interactive form such as the above figure?

**Comment by timoast** [comment]
You can use the `CellSelector()` function to interactively select cells
