### ISSUE TITLE
Disease vs. control comparison for multiple tissues (HTO multiplexed) and biological replicates

### ISSUE THREAD

**Issue by Mushin** [satijalab/seurat#5052]
I'm trying to get some advice on how to best analyse my dataset. Apologies if a similar question has been asked before - I couldn't find this situation by searching.

The study design is as follows:
- n = 4 disease and n = 3 control animals (biological replicates)
- For each animal, I have a single sequenced 10X library
- Each 10X library was produced from cells from 4 different tissues (HTO multiplexed)

I would like to compare disease vs. control on a per tissue level, as well as with all cells combined, but I'm not clear on which order the steps should be performed. So far I have performed the following steps:

_Individually for each 10X library:_
- Normalise with SCTransform
- Demultiplex according to [this](https://satijalab.org/seurat/articles/hashing_vignette.html)
- Subset to keep only the singlet cells according to HTO signal (this helped to minimise time and RAM usage when integrating)

_Integrating the samples:_
- Integrate all samples according to [this](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1)

This is where I'm up to. So my questions are:
- Is what I've done correct?
- If not correct - how should I do it differently? e.g., subset by tissue (HTO) before integration?
- What are the next steps to perform my analysis?

Thanks for any tips you can provide.

**Comment by timoast** [comment]
Yes, this is a reasonable approach. 

> What are the next steps to perform my analysis?

This obviously depends what your goals are, but I'd suggest taking a look at the [PBMC vignette](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) for examples of how to do basic clustering, annotation, and differential expression. You can also look at the [integration vignette](https://satijalab.org/seurat/articles/integration_introduction.html) to see how to do disease vs healthy comparisons
