### ISSUE TITLE
Scaling multiple times in HTO vignette

### ISSUE THREAD

**Issue by hannasj** [satijalab/seurat#5053]
I'm trying to follow the hashing vignette https://satijalab.org/seurat/articles/hashing_vignette.html
First the whole Seurat object is scaled
pbmc.hashtag <- ScaleData(pbmc.hashtag, features = VariableFeatures(pbmc.hashtag))
later, once each cell has been assigned a HTO and doublets and negative have been removed, the data are scaled again
pbmc.singlet <- subset(pbmc.hashtag, idents = "Singlet")
pbmc.singlet <- ScaleData(pbmc.singlet, features = VariableFeatures(pbmc.singlet))
Please could you explain why is this and whether it matters?

**Comment by timoast** [comment]
Scaling subtracts the mean and divides by standard deviation. If you remove cells from the object, mean and SD will change. After subsetting, we therefore re-scale the data.
