### ISSUE TITLE
Read10X_h5 errors?

### ISSUE THREAD

**Issue by AidanMar** [satijalab/seurat#5055]
I have some sc-ATAC data from 10x genomics which gives a filtered_peak_bc_matrix.h5 output file. When attempting to follow the tutorial (https://satijalab.org/signac/articles/pbmc_vignette.html), which reads this file in I run:
```
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v75)
library(ggplot2)
library(patchwork)
set.seed(1234)
Attaching SeuratObject
ReadH5AD(filename = "/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5")
```

alternatively, I have also downloaded the test data in the tutorial, and ran: 
counts <- Read10X_h5(filename = "atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5")

In both cases I get the following error output:

```
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../../src/H5F.c in H5Fopen(): line 509: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: ../../../src/H5Fint.c in H5F__open(): line 1400: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: ../../../src/H5Fint.c in H5F_open(): line 1615: unable to lock the file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #003: ../../../src/H5FD.c in H5FD_lock(): line 1640: driver lock request failed
        class: HDF5
        major: Virtual File Layer
        minor: Can't update object

    error #004: ../../../src/H5FDsec2.c in H5FD_sec2_lock(): line 941: unable to lock file, errno = 5, error message = 'Input/output error'
        class: HDF5
        major: File accessibilty
        minor: Bad file ID accessed

```

All files have read permissions and I have checked the file path is correct (multiple times).

Any help with this would be deeply appreciated.

Best,
Aidan

**Comment by timoast** [comment]
The correct function to read the hdf5-format output of cellranger is `Read10X_h5()`, not `ReadH5AD()`.

Does `Read10X_h5("/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5")` work?

If not, what does `file.exists("/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5")` return?

**Comment by AidanMar** [comment]
Hi there. The file does indeed exist. I get:
```
> file.exists("/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5")
[1] TRUE
```
And apologies for creating confusion with ReadH5AD. I actually tried Read10x_h5 previously and that lead me to try ReadH5AD, because of the error that it output. Running Read10X_h5 as you said gives:

```
> counts <- Read10X_h5(filename = "/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5") 
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../../src/H5F.c in H5Fopen(): line 509: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: ../../../src/H5Fint.c in H5F__open(): line 1400: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: ../../../src/H5Fint.c in H5F_open(): line 1615: unable to lock the file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #003: ../../../src/H5FD.c in H5FD_lock(): line 1640: driver lock request failed
        class: HDF5
        major: Virtual File Layer
        minor: Can't update object

    error #004: ../../../src/H5FDsec2.c in H5FD_sec2_lock(): line 941: unable to lock file, errno = 5, error message = 'Input/output error'
        class: HDF5
        major: File accessibilty
        minor: Bad file ID accessed

```

**Comment by timoast** [comment]
It looks like this is an issue with hdf5r reading the file...can you try using hdf5r directly to read the file and see if you have any errors?

eg:

```r
library(hdf5r)
infile <- H5File$new(filename = filename, mode = "r")
names(infile)
print(infile)
```

**Comment by AidanMar** [comment]
Tried this: 

```
infile <- H5File$new(filename = "/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5", mode = "r")
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../../src/H5F.c in H5Fopen(): line 509: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: ../../../src/H5Fint.c in H5F__open(): line 1400: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: ../../../src/H5Fint.c in H5F_open(): line 1615: unable to lock the file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #003: ../../../src/H5FD.c in H5FD_lock(): line 1640: driver lock request failed
        class: HDF5
        major: Virtual File Layer
        minor: Can't update object

    error #004: ../../../src/H5FDsec2.c in H5FD_sec2_lock(): line 941: unable to lock file, errno = 5, error message = 'Input/output error'
        class: HDF5
        major: File accessibilty
        minor: Bad file ID accessed
```

I know the file exists with that ID, and I know it is not corrupted because received it from a collaborator and the md5sums checkout. Any ideas? These H5AD errors are beyond my knowledge.

**Comment by timoast** [comment]
I'm not sure, you could try reinstalling hdf5r and also HDF5 itself. Beyond that, I think you should ask the hdf5r authors instead: https://github.com/hhoeflin/hdf5r

**Comment by suanzaoren** [comment]
Hi Aidan,Has your problem been solved?I had the same problem reading in single-cell sequencing data as you did.I'm desperate for your help.
Best Wish,
Zerun Song

**Comment by suanzaoren** [comment]
> Tried this:
> 
> ```
> infile <- H5File$new(filename = "/home/ma/a/asm119/outs/filtered_peak_bc_matrix.h5", mode = "r")
> Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
>   HDF5-API Errors:
>     error #000: ../../../src/H5F.c in H5Fopen(): line 509: unable to open file
>         class: HDF5
>         major: File accessibilty
>         minor: Unable to open file
> 
>     error #001: ../../../src/H5Fint.c in H5F__open(): line 1400: unable to open file
>         class: HDF5
>         major: File accessibilty
>         minor: Unable to open file
> 
>     error #002: ../../../src/H5Fint.c in H5F_open(): line 1615: unable to lock the file
>         class: HDF5
>         major: File accessibilty
>         minor: Unable to open file
> 
>     error #003: ../../../src/H5FD.c in H5FD_lock(): line 1640: driver lock request failed
>         class: HDF5
>         major: Virtual File Layer
>         minor: Can't update object
> 
>     error #004: ../../../src/H5FDsec2.c in H5FD_sec2_lock(): line 941: unable to lock file, errno = 5, error message = 'Input/output error'
>         class: HDF5
>         major: File accessibilty
>         minor: Bad file ID accessed
> ```
> 
> I know the file exists with that ID, and I know it is not corrupted because received it from a collaborator and the md5sums checkout. Any ideas? These H5AD errors are beyond my knowledge.

Hi Aidan,Has your problem been solved?I had the same problem reading in single-cell sequencing data as you did.I'm desperate for your help.
Best Wish,
Zerun Song

**Comment by Greysun109** [comment]
I am also having the same issue.



<html>
<body>
<div class="GNVWDDMDLID ace_constant" style="white-space: pre; display: inline; overflow-wrap: break-word; word-break: break-word; color: rgb(197, 6, 11); font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span>Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: ../../src/H5F.c in H5Fopen(): line 620: unable to open file
        class: HDF5
        major: File accessibility
        minor: Unable to open file

    error #001: ../../src/H5VLcallback.c in H5VL_file_open(): line 3522: open failed
        class: HDF5
        major: Virtual Object Layer
        minor: Can't open object

    error #002: ../../src/H5VLcallback.c in H5VL__file_open(): line 3351: open failed
        class: HDF5
        major: Virtual Object Layer
        minor: Can't open object

    error #003: ../../src/H5VLnative_file.c in H5VL__native_file_open(): line 97: unable to open file
        class: HDF5
        major: File accessibility
        minor: Unable to open file

    error #004: ../../src/H5Fint.c in H5F_open(): line 1990: unable to read superblock
        class: HDF5
        major: File accessibility
        minor: Read failed

    error #005: ../../src/H5Fsuper.c in H5F__super_read(): line 405: file signature not found</span></div><span style="color: rgb(0, 0, 0); font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-line; background-color: rgb(230, 230, 230); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="GNVWDDMDMID stack_trace" aria-hidden="true" style="margin-top: 0.5em; margin-left: 0.3em; color: rgb(0, 0, 0); font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: pre-line; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: block;">
4. | H5File.open(filename, mode, file_create_pl, file_access_pl)
-- | --


</div>
</body>
</html>

**Comment by dfgao** [comment]
I have the same problem. I have found that keeping the data in a directory with full access can solve this problem.
