### ISSUE TITLE
different platform integration

### ISSUE THREAD

**Issue by hansong798** [satijalab/seurat#5057]
Hello, seurat team.

i am integrating datasets from two different single cell sequencing platform.

I tried to do it using "rpca" and "cca" on SCTransformed data and when i compared the umap of them, two methods completely made different plots.

Like this situation, which one is best suitable for integrating multi platform data ?

**Comment by akramdi** [comment]
Hello, 

I'm not from seurat team but I think CCA workflow is more suitable for integrations across sequencing platforms, at least this is what I understood from the [vignette](https://satijalab.org/seurat/articles/integration_rpca.html).

It'll be nice to have a confirmation though :)

Best,

**Comment by timoast** [comment]
In general, we recommend reciprocal PCA for integrating across batches where the same technology was used (eg, multiple 10x scRNA-seq samples), and CCA for cases where the differences between batches is expected to be much larger (across technologies, across species, across modalities, etc). However, this recommendation is just intended as a starting point, and if you're finding that rPCA isn't working well for integrating particular datasets you could certainly try CCA.
