### ISSUE TITLE
Merging objects returns different number of features

### ISSUE THREAD

**Issue by andynkili** [satijalab/seurat#5059]
Using this [seurat vignette](https://satijalab.org/seurat/articles/merge_vignette.html), I want to merge 2 objects (2 sequencing runs from the same sample).
Here is what I have done:
```
sample1.data <-Read10X("sample1/filtered_feature_bc_matrix/")
sample2.data <-Read10X("sample2/filtered_feature_bc_matrix/")

sample1 <- CreateSeuratObject(counts = sample1.data, project = 'Brain', min.cells = 3, min.features = 200)
sample2 <- CreateSeuratObject(counts = sample2.data, project = 'Brain', min.cells = 3, min.features = 200)

sample.merged <- merge(sample1, y = c(sample2), add.cell.ids = c("sample1", "sample2"))
```

I end up with a merged object containing 13022 features and 919 samples.

However when I merge using the code below:
```
data.dir= c("sample1/filtered_feature_bc_matrix/","sample2/filtered_feature_bc_matrix/")
names(data.dir)=c("sample","sample")

sample.data2 <- Read10X(data.dir = data.dir)
sample.merged2 <- CreateSeuratObject(counts = sample.data2, project = "Brain", min.cells = 3, min.features = 200)
```
This time the merged object has 13832 features and 919 samples.

How come, using the same samples and values for "min.cells" and "min.features" parameters, those 2 merging methods return a different number of genes?
What is the difference between those 2 merging methods and which one should I use?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The reason has to do with the `min.cells` parameter and how you created the objects.  

In scenario 1 you created two objects and therefore each library was checked and features expressed in less than 3 cells in each library was removed.  Then the resulting objects were merged.
In scenario 2 you created a single object containing both libraries.  In this case only features that were expressed in less than 3 cells across all cells in these two libraries were removed (hence more features at the end).

In terms of which is better that is going to depend on your preference and some experimental parameters.  e.g., are the two libraries sequenced to equal depths?  Do they contain the same proportional representation of cell types?  Are you analyzing this sample with even more samples?  etc

In general (though absolutely are exceptions and again I think it depends on dataset) I personally think either performing filtering on the level of a single biological replicate or across all biological replicates in given experiment is the way to do it.  So in this case I'd say scenario #2 or even merging all matrices in analysis together before creating Seurat object.

Best,
Sam

**Comment by andynkili** [comment]
Sam,

My supervisor had exactly the same take on that issue but we were not 100% sure that the difference only resided in the filtering parameters.

Thank you for your thought on this.

Best,
Andy

**Comment by samuel-marsh** [comment]
Hey Andy,

Ya I mean that's the only thing that makes sense to me.  You could check yourself by digging into raw counts in matrix but nothing else should be effecting it as far as I see.

Best,
Sam

**Comment by andynkili** [comment]
Sam,

Thanks for the suggestion!
I checked the raw count matrix (getting the number of rows and columns matching my filter parameters) and indeed the difference comes from filtering both objects before merging and filtering the merged object.

Thank you for your insight,
Andy
