### ISSUE TITLE
"Gating" marker-positive cells for downstream analysis

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#506]
Hello,

I was wondering if there is a way to gate the cells based on their expression of specific markers (e.g. CD3+CD4+) and analyze these cells further between various conditions (e.g. treatment vs control etc.)

I realize that `FindClusters` would most likely result in a distinct clustering of T cells that can be used for comparisons between conditions, but sometimes it may not be as straightforward. I think a gating method like in flow cytometry would be really helpful in this context. I think 10x's Loupe browser allows such gating. Would it be possible to implement something like this in Seurat?

Related to this, is there a plan to have a feature that converts a Seurat object to a `.loupe` format for exploring in the Loupe browser? This would be helpful for labs that are not R-savvy.

Thank you very much in advance for all the assistance!

**Comment by satijalab** [comment]
You can use the do.identify argument to draw polygon gates and select individual cells on a dimensional reduction plot (or a gene/gene plot) for downstream analysis. You can also use FilterCells to set quantitative gates.
