### ISSUE TITLE
Error when running UMAP

### ISSUE THREAD

**Issue by zhli12** [satijalab/seurat#5060]
When I'm trying to run UMAP for a dataset that is SCTranformed, I had error saying

```

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': error in evaluating the argument 'x' in selecting a method for function 't': invalid character indexing
```

I'm using R version 4.1.1 on macOS system. I have used `RunUMAP` successfully a couple of times before and this is the first time I saw the error. Does anyone have any idea about what might be the cause? Thanks!

**Comment by t-carroll** [comment]
Looks like a similar issues mentioned over in #3618: https://github.com/satijalab/seurat/issues/3618#issuecomment-785185592. Does updating SeuratDisk and sctransform clear it?

**Comment by yuhanH** [comment]
@t-carroll  Thanks for your reply.  I agree with you. 
@zhli12 , you can first install the latest SeuratDisk. 
Then you can update your objects by the following lines:
```
obj <- UpdateSeuratObject(obj)
obj <- UpdateSCTAssays(obj)
```
