### ISSUE TITLE
Loading SeuratObject

### ISSUE THREAD

**Issue by mannakade** [satijalab/seurat#5062]
Hello!

I'm currently updating an old code from Seurat v3.1.2 & R v3.6.2 to work on the most recent versions of each. Recently I've been getting the message "Loading required package: SeuratObject" as I run code in various spots, it doesn't really appear to be associated with any one command. Once this message appears in console, the code stops running. I restarted R and tried install.packages("SeuratObject") as well as installing Seurat at the start of the code since a previous thread mentioned that may help but still get the message. 

**Here is the code I'm currently running up to where I get the message:**
install.packages("Seurat")
library(Seurat)
library(xlsx)
install.packages("SeuratObject")

install.packages('BiocManager')
#BiocManager::install('multtest')
install.packages('metap')

#######load data
skin.integrated <- readRDS ("~/skin_integrated.rds")

### Find Cluster markers---conserved markers
DefaultAssay(skin.integrated ) <-"RNA"
for (i in 0:20){
  marker_i <- FindConservedMarkers(skin.integrated, ident.1 = i, grouping.var = "STIM", verbose = TRUE, test.use = "MAST")
  tab  <- paste0("Cluster", " ", i)
  write.xlsx(marker_i, file = "G:/IMQ-OXA/FindConservedMarker.xlsx", sheetName = tab, append = TRUE)
}

**And here is the console when I run my whole code (it stops once I hit the loading message even tough the code continues for another 23 lines):**
> install.packages("Seurat")
Installing package into ‘C:/Users/gabri/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/Seurat_4.0.4.zip'
Content type 'application/zip' length 2779102 bytes (2.7 MB)
downloaded 2.7 MB

package ‘Seurat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\gabri\AppData\Local\Temp\Rtmpi8g40z\downloaded_packages
> library(Seurat)
Attaching SeuratObject
> library(xlsx)
> install.packages("SeuratObject")
Error in install.packages : Updating loaded packages
> 
> install.packages('BiocManager')
Error in install.packages : Updating loaded packages
> #BiocManager::install('multtest')
> install.packages('metap')
Installing package into ‘C:/Users/gabri/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/metap_1.4.zip'
Content type 'application/zip' length 683258 bytes (667 KB)
downloaded 667 KB

package ‘metap’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\gabri\AppData\Local\Temp\Rtmpi8g40z\downloaded_packages
> 
> 
> #######load data
> skin.integrated <- readRDS ("~/skin_integrated.rds")
> 
> 
> 
> ### Find Cluster markers---conserved markers
> DefaultAssay(skin.integrated ) <-"RNA"
> for (i in 0:20){
+   marker_i <- FindConservedMarkers(skin.integrated, ident.1 = i, grouping.var = "STIM", verbose = TRUE, test.use = "MAST")
+   tab  <- paste0("Cluster", " ", i)
+   write.xlsx(marker_i, file = "G:/IMQ-OXA/FindConservedMarker.xlsx", sheetName = tab, append = TRUE)
+ }

Restarting R session...

Loading required package: SeuratObject

**Comment by mannakade** [comment]
Suppose I should mention versions, R v4.1.1 & Seurat v4.0.3

**Comment by timoast** [comment]
This is just a message saying that a required package is being attached, I don't think this is an error or anything to worry about.

**Comment by mannakade** [comment]
Hi, I've left the code to run overnight & nothing happens, it just waits for the package to "load" but never does.

**Comment by timoast** [comment]
I'd suggest restarting R and clearing the environment, and updating your packages and see if you still have any problems. It's unusual that you see the error `Error in install.packages : Updating loaded packages` when trying to run `install.packages()`. If you keep seeing this error, that's a general R issue unrelated to Seurat and I'd suggest seeking help on a general R support forum like stackoverflow.
