### ISSUE TITLE
Obtaining cluster markers from WNN

### ISSUE THREAD

**Issue by elengss** [satijalab/seurat#5063]
Dear all,

I am trying to follow the WNN vignette here https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html

After the steps below, I would like to annotate my clusters, hence I need to know the markers which best represent each cluster.

pbmc <- FindMultiModalNeighbors(pbmc, reduction.list = list("pca", "lsi"), dims.list = list(1:50, 2:50)) pbmc <- RunUMAP(pbmc, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_") pbmc <- FindClusters(pbmc, graph.name = "wsnn", algorithm = 3, verbose = FALSE)

So I go on to do

allmarkers <- FindAllMarkers(pbmc)

However, I am unsure how to interpret the findings. Below is the allmarkers object, which is calculated from ATAC assay counts, since the last default assay was set to "ATAC" with DefaultAssay(pbmc) <- "ATAC". Is there any way to find the genes or chromatin peaks most associated with the clusters coming out from the WNN graph that combines both RNAseq and ATACseq?

Thanks in advance.

> head(allmarkers)
                                p_val avg_log2FC pct.1 pct.2 p_val_adj cluster
chr1-186828497-186829311 1.242405e-06 -0.4548612 0.025 0.162 0.1287653       0
chr1-42462733-42463616   6.747624e-06 -0.3321175 0.130 0.302 0.6993372       0
chr19-11505637-11505933  1.287234e-05  0.3955261 0.365 0.210 1.0000000       0
chr3-112858127-112859021 1.368274e-05 -0.4490370 0.065 0.202 1.0000000       0
chr9-129482422-129483279 1.468715e-05  0.4140303 0.300 0.154 1.0000000       0
chr7-18221372-18222277   1.476420e-05 -0.5840315 0.025 0.135 1.0000000       0
                                             gene
chr1-186828497-186829311 chr1-186828497-186829311
chr1-42462733-42463616     chr1-42462733-42463616
chr19-11505637-11505933   chr19-11505637-11505933
chr3-112858127-112859021 chr3-112858127-112859021
chr9-129482422-129483279 chr9-129482422-129483279
chr7-18221372-18222277     chr7-18221372-18222277

**Comment by yuhanH** [comment]
HI, 
You can find both ATAC and RNA markers based on the same multimodal clusters. 
```
allmarkers.rna <- FindAllMarkers(pbmc, assay = 'RNA)
allmarkers.atac <- FindAllMarkers(pbmc, assay = 'ATAC')
```
