### ISSUE TITLE
Error with PercentageFeatureSet

### ISSUE THREAD

**Issue by EleniStylianou** [satijalab/seurat#5064]
Even though my Aligned.to.Transcriptome.out.bam file appears to contain mitochondrial genes I get a message telling me all the cells in my human single cell RNA seq Seurat object have the same value of percent.mt. (i.e. zero) when I use PercentageFeatureSet. I would appreciate any suggestions you may have.
Thank you.
Eleni

**Comment by samuel-marsh** [comment]
Hi Eleni,

Not member of dev team but hopefully can be helpful.  What is the output of the following code for your Seurat object (swapping out the pattern depending on what species you are analyzing):
```
grep(pattern = "^mt-", x = rownames(obj_name), value = TRUE)
```

Best,
Sam

**Comment by EleniStylianou** [comment]
Hi Sam,
Thank you for your quick reply. If I put in the above code the answer I get is character(0). Can you offer any explanation?
Best,
Eleni

**Comment by samuel-marsh** [comment]
So what that means is that in your Seurat Object no genes with those patterns are present.  What happens if you run same code on the raw matrix used to create the Seurat object.  Just replace `obj_name` with the matrix name.

**Comment by EleniStylianou** [comment]
The raw matrix used to create the Seurat object also gives character(0). 

Can you advise as to how I verify that my Aligned.toTranscriptome.out.bam file contains mitochondrial genes? Do I need to check that the STAR Solo alignment I ran successfully mapped mitochondrial genes?

I did the following to check my Aligned.toTranscriptome.out.bam.file after sorting it,
samtools idxstats Aligned.toTranscriptome.out.sorted.bam | cut -f1 | grep -v MT | xargs samtools view -b Aligned.toTranscriptome.out.sorted.bam > MT_output.bam - this produced a 0.3GB file.

Thank you very much for your input.

**Comment by samuel-marsh** [comment]
I'd advise posting this to STAR repo to get better idea of what is going on.  I'm not as well versed with sorting through BAM files and the outputs from STARsolo.  As far as Seurat is concerned these cells don't express any of these genes because they aren't present in the matrix so that's why percent values are all 0.

**Comment by EleniStylianou** [comment]
Ok, thank you very much.
