### ISSUE TITLE
Cluster ID numbers are not continuous after subsetting seurat object and redo clustering

### ISSUE THREAD

**Issue by Leran10** [satijalab/seurat#5065]
Hi,

I tried to subset the Seurat object and extract a specific cell type, after doing that, Here is my code:

```
# subset Seurat to only Epithelial cells
subset.Epithelial <- subset(x = combined.all, idents = "Epithelial cells")

subset.Epithelial <- FindVariableFeatures(subset.Epithelial, selection.method = "vst", nfeatures = 2000)
subset.Epithelial <- ScaleData(subset.Epithelial, verbose = FALSE)

# run tsNE
subset.Epithelial <- RunTSNE(object = subset.Epithelial)

# tSNE plot
Epithelial.clusters.tsne <- DimPlot(subset.Epithelial, reduction = "tsne",group.by = "seurat_clusters",label = TRUE)
```

But the cluster IDs in the result t-sne plot are not continuous (Cluster 6 ,13, 16 are missing):

![image](https://user-images.githubusercontent.com/17597071/132917639-94bbd823-a886-4ed1-aa80-ab4ba750506f.png)

Is there something that I did was wrong?

Thanks!
Leran

**Comment by timoast** [comment]
You didn't re-do clustering here, only computed a new tSNE
