### ISSUE TITLE
Extract gene list: Seurat

### ISSUE THREAD

**Issue by Deepesh123gupta** [satijalab/seurat#5066]
![image](https://user-images.githubusercontent.com/62347074/132966547-cfaaf101-886a-416c-bc81-2114ee86f1f6.png)

Hello, 

I have three group to compare in Venn diagram. Numbers are list of gene in the dataset I would like to pull out actual genes list from labelled X and Labelled Y region using R. 

Thanks Folks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you provide some more info on how this relates to Seurat and what you are trying to do?  What do you mean by pull out genes?  How did you create this Venn diagram?

Best,
Sam

**Comment by torkencz** [comment]
Hi, as @samuel-marsh said this is not necessarily a Seurat question as it seems to me you are using ggVenndiagram. I recommend you use the process_region_data() function in https://github.com/gaospecial/ggVennDiagram.
