### ISSUE TITLE
Interactive DoHeatmap

### ISSUE THREAD

**Issue by jjyotikataria** [satijalab/seurat#5067]
My plots are not getting plotted in rmarkdown when I am using the following commands to generate DoHeatmap. Could you please help me out?

plttt <- htmltools::tagList()
jj <- 1

p13<-DoHeatmap(data, features = top5.markers$gene,draw.lines=F, size=1, angle=90, group.colors=colors30)+ scale_fill_gradientn(guide="colourbar",colors = c("blue", "white", "red"))+ theme(axis.title.x.top =element_text(angle = 90, vjust = 0.5, hjust=1),plot.title = element_text(hjust = 0.5))+ ggtitle(title_name) + theme(plot.title = element_text(hjust = 0.5, vjust=0.5))
plttt[[jj]] <- as_widget(ggplotly(p13,tooltip = c("text")))
jj <- jj + 1

**Comment by jjyotikataria** [comment]
@troels @mxposed @zeehio @smoe

**Comment by mxposed** [comment]
Could you please stop tagging me? Thank you

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  If you just try and render plot as `DoHeatmap` without processing it through ggplotly and htmltools does that work?  If so then the error is not coming from the Seurat side of things and I suggest you post in the appropriate repo for the function that is causing issue.

Best,
Sam

**Comment by jjyotikataria** [comment]
@samuel-marsh Yes, its working for me with without plotly.

**Comment by samuel-marsh** [comment]
Then this is plotly issue and not Seurat so I would suggest posting there.

Best,
Sam

**Comment by torkencz** [comment]
Yes this is a plotly issue.
