### ISSUE TITLE
read 10*

### ISSUE THREAD

**Issue by chenx9** [satijalab/seurat#5068]
when i want to read 10*files,i get   Error in Read10X(data.dir = dir) :  Barcode file missing. Expecting barcodes.tsv.gz
here are my dir 
> dir
                  GSM4157068_Sample_6_N3 
  "D:/GSE140231//GSM4157068_Sample_6_N3" 
                  GSM4157069_Sample_7_N4 
  "D:/GSE140231//GSM4157069_Sample_7_N4" 
                  GSM4157070_Sample_8_N5 
and  I made sure that each subfolder contained the following three files : barcodes.tsv, genes.tsv, matrix.mtx

I would like to know what the problem is. I would appreciate it if you could help me solve it

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  It looks you might be missing trailing slash at the end of folder names for one.  Also looks like you are loading data from GEO.  If the files have prefixes and are not simply named "barcodes.tsv" then `Read10X` function won't work.  You can check out `ReadMtx` as alternative too.

Best,
Sam
