### ISSUE TITLE
Subsetting seurat object does not remove factor levels from the meta data

### ISSUE THREAD

**Issue by m0nib** [satijalab/seurat#5069]
Hi,

When subsetting a seurat object the meta data retains the factor levels, how can the seurat object meta data be re-leveled?

As an example:

hlca <- readRDS("./data/human_lung_atlas.rds")

> unique(hlca@meta.data[["dataset_origin"]])
 [1] habermann_2020  adams_2020      reyfman_2019    deprez_2020     mayr_2020       madissoon_2020  delorey_2021    lukassen_2020   morse_2019      travaglini_2020
Levels: adams_2020 delorey_2021 deprez_2020 habermann_2020 lukassen_2020 madissoon_2020 mayr_2020 morse_2019 reyfman_2019 travaglini_2020

and after subset:
hlca <- subset(x = hlca, subset = dataset_origin %in% c("adams_2020", "habermann_2020", "morse_2019", "reyfman_2019"))

> unique(hlca@meta.data[["dataset_origin"]])
[1] habermann_2020 adams_2020     reyfman_2019   morse_2019    
Levels: adams_2020 delorey_2021 deprez_2020 habermann_2020 lukassen_2020 madissoon_2020 mayr_2020 morse_2019 reyfman_2019 travaglini_2020

Any help with this please.

Thank  you
Best regards
Monib

**Comment by samuel-marsh** [comment]
Hi Monib,

Not member of dev team but hopefully can be helpful.  As quick fix after you have subsetted your data you can run:
```
hlca@meta.data$dataset_origin <- droplevels(hlca@meta.data$dataset_origin)

# check successful
levels(hlca@meta.data$dataset_origin)
```

This should drop nonexistent levels.

Best,
Sam

**Comment by m0nib** [comment]
Hi Sam,

Thank you for your reply and it worked. Another question if you could help with

When i read the rds file of the human lung dataset and subsetting when i run the command
Idents(hlca)

I get the following (only showing part of the output)

                           HD66_CCTAGCTCAGACGCTC_1 
lung_mapped_cellxgene_var_index_fixed_remixed_clean 
 [ reached getOption("max.print") -- omitted 578897 entries ]
Levels: lung_mapped_cellxgene_var_index_fixed_remixed_clean

Is this a normal response? and what should the idents be?

Thank you

Best regards
Monib

**Comment by timoast** [comment]
Please see the documentation for `Idents()`: https://www.rdocumentation.org/packages/SeuratObject/versions/4.0.2/topics/Idents

**Comment by IsmailFreeman** [comment]
Hi Seurat Team,
A relevant (but very basic) question:
Why there are factor levels in Seurat objects and what does it mean exactly? For example looking at the bm object {obtained from:  InstallData("bmcite"); bm <- LoadData(ds = "bmcite")} there is a Factor with two levels "a" and "b" in bm@meta.data[["orig.ident"]].  What is the purpose of these two? What does happen in downstream analysis if I remove these identities?

**Comment by IsmailFreeman** [comment]
Hi Seurat Team,
A relevant (but very basic) question:
Why there are factor levels in Seurat objects and what does it mean exactly? For example looking at the bm object {obtained from:  InstallData("bmcite"); bm <- LoadData(ds = "bmcite")} there is a Factor with two levels "a" and "b" in bm@meta.data[["orig.ident"]].  What is the purpose of these two? What does happen in downstream analysis if I remove these identities?

**Comment by michael-kotliar** [comment]
Might be useful to drop the unused levels
```R
refine_metadata_levels <- function(seurat_data){
    for (i in base::colnames(seurat_data@meta.data)){
        if (base::is.factor(seurat_data@meta.data[[i]])){
            base::print(base::paste("Re-evaluating levels for a factor column", i))
            base::print(
                base::paste(
                    "before:", base::paste(base::levels(seurat_data@meta.data[[i]]), collapse=", ")
                )
            )
            seurat_data@meta.data[[i]] <- base::droplevels(seurat_data@meta.data[[i]])  # need to drop levels of the removed values
            base::print(
                base::paste(
                    "after:", base::paste(base::levels(seurat_data@meta.data[[i]]), collapse=", ")
                )
            )
        }
    }
    return (seurat_data)
}
```
