### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Anupriya014** [satijalab/seurat#507]
Hello Authors @satijalab 

I am unable to install 'Seurat' by any method. I tried installing by : 
1) `install.packages('Seurat')`
Got this error : 

```R
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'httpuv'
ERROR: lazy loading failed for package 'crosstalk'
* removing '/home/anupriya/R/x86_64-pc-linux-gnu-library/3.5/crosstalk'
ERROR: dependency 'crosstalk' is not available for package 'plotly'
* removing '/home/anupriya/R/x86_64-pc-linux-gnu-library/3.5/plotly'
ERROR: dependency 'plotly' is not available for package 'Seurat'
* removing '/home/anupriya/R/x86_64-pc-linux-gnu-library/3.5/Seurat'

The downloaded source packages are in
	'/tmp/Rtmpm2SfOv/downloaded_packages'
Warning messages:
1: In install.packages("Seurat") :
  installation of package 'crosstalk' had non-zero exit status
2: In install.packages("Seurat") :
  installation of package 'plotly' had non-zero exit status
3: In install.packages("Seurat") :
  installation of package 'Seurat' had non-zero exit status
```
------------
2) `git clone https://github.com/satijalab/seurat.git`
asks me to install plotly and eventually, crosstalk .
When I try to install crosstalk it asks me to install 'httpuv'  by : 
`R CMD INSTALL httpuv`
I get this error : 
```R
/usr/local/lib/R/etc/Makeconf:168: recipe for target 'callbackqueue.o' failed
make: *** [callbackqueue.o] Error 1
ERROR: compilation failed for package 'httpuv'
* removing '/home/anupriya/R/x86_64-pc-linux-gnu-library/3.5/httpuv'
```
Please help me out. Thanks in advance!

**Comment by mojaveazure** [comment]
What OS and R version are you using?

**Comment by Anupriya014** [comment]
Hi @mojaveazure .
Thanks for replying. Below are the details : 

Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by Anupriya014** [comment]
Hello @mojaveazure 

I changed my gcc to gcc-5 and make its priority more than other gcc with this command :  
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 70 --slave /usr/bin/g++ g++ /usr/bin/g++-5

Now  'gcc --version' gives me : 
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

After this in R 3.5 , I ran 'install.packages("httpuv")' , still I'm getting some error like this : 

/usr/lib/R/etc/Makeconf:168: recipe for target 'callbackqueue.o' failed
make: *** [callbackqueue.o] Error 1
ERROR: compilation failed for package 'httpuv'
* removing '/home/anupriya/R/x86_64-pc-linux-gnu-library/3.4/httpuv'

The downloaded source packages are in
	'/tmp/RtmpetG7l5/downloaded_packages'
Warning message:
In install.packages("httpuv") :
  installation of package 'httpuv' had non-zero exit status
