### ISSUE TITLE
Obtaining SCTransform-normalized and integrated counts for all genes

### ISSUE THREAD

**Issue by jasminelmah** [satijalab/seurat#5077]
Hello Seurat Team! I have two questions. 

1. I am interested in obtaining the SCTransformed Pearson residuals, SCT-corrected UMI counts, and the corrected integrated gene counts (ie the counts of genes produced after integrating samples, as resulting from the data integration workflow [here](https://satijalab.org/seurat/articles/integration_introduction.html). Is the following correct?
Where the Seurat object has been named combined.sct:
> combined.sct[["SCT"]]@scale.data = SCT Pearson residuals
> combined.sct[["SCT"]]@counts = SCT-corrected UMI counts
> combined.sct[["integrated"]]@scale.data = corrected integrated gene counts

2. My goal is to get all three above types of data for my entire gene set (ie run SCTransform and IntegrateData on all genes, just like in issue [#2270](https://github.com/satijalab/seurat/issues/2270)). I noticed that the number of features in combined.sct[["SCT"]]@scale.data and combined.sct[["integrated"]]@scale.data was always less than the total number of genes in my original matrix, despite setting `return.only.var.genes = FALSE` in `SCTransform()` and `features.to.integrate = all_genes` in `IntegrateData`. Why? How do I obtain the SCT Pearson residuals and integrated gene counts for my entire gene set?

Below is a reproducible example:
> LoadData("ifnb")
> seurat.obj.list <-  SplitObject(ifnb, split.by="stim")
> #SCTransform normalize
> seurat.obj.list <- lapply(X = seurat.obj.list, FUN = function(x){ x<- SCTransform(x, return.only.var.genes = FALSE, residual.features=NULL)})
> features <- SelectIntegrationFeatures(object.list = seurat.obj.list, nfeatures=3000)
> seurat.obj.list <- PrepSCTIntegration(object.list = seurat.obj.list, anchor.features = features)
> #find integration anchors
>anchors <- FindIntegrationAnchors(object.list = seurat.obj.list, normalization.method = "SCT", anchor.features = features)
>#make character vector of all gene names
>seurat.obj.ex <- seurat.obj.list[[1]]
>all_genes <- seurat.obj.ex@assays[["RNA"]] %>% row.names()
>#integrate data
>combined.sct <- IntegrateData(anchorset = anchors, normalization.method = "SCT", k.weight=30, features.to.integrate = all_genes)

I realize Seurat is probably filtering genes out by design. I just need a little help understanding how and why. Again, my goal is to obtain corrected values for my entire gene set. Thanks for your help!

**Comment by GabyBG** [comment]
I think the default by SCTransform is asking for min_cells = 5. You can try to add this parameter and lower the number of cells required to see if it helps.

seurat.obj.list <- lapply(X = seurat.obj.list, FUN = function(x){ x<- SCTransform(x, return.only.var.genes = FALSE, residual.features=NULL, min_cells = 1)})

**Comment by jasminelmah** [comment]
Thanks @GabyBG. That would probably help with minimizing the number of cells dropped and I'll give that a try. I am interested in minimizing the number of features or genes dropped however. Any ideas?

**Comment by GabyBG** [comment]
min_cells refers to: how many cells need to be expressing the gene at least, for SCT transform not to get rid of the gene. Does that make sense? This parameter is not getting rid of cells but genes with low presence.

Seurat is calling sctransform, so any other hidden parameters can be found in here:
https://github.com/ChristophH/sctransform

https://github.com/satijalab/seurat/issues/2128

**Comment by jasminelmah** [comment]
Thank you for clearing that up @GabyBG! I didn't know SCTransform well enough to know that. I'll give it a try!

**Comment by jasminelmah** [comment]
Adjusting `min_cells=1` for  did help - instead of only retaining 16% (70/443) of my genes, I now retain 65% (289/443). That's great! It looks like these 298 genes were selected as variable features by `SelectIntegrationFeatures`, so it seems that only variable features are being retained in the `combined.sct[["SCT"]]@scale.data` and `combined.sct[["integrated"]]@scale.data` slots. What setting am I missing...?

**Comment by saketkc** [comment]
[PrepSCTIntegration](https://satijalab.org/seurat/reference/prepsctintegration) will only return objects with the appropriate scale.data slots containing only the required `anchor.features`.

For SCTransform, you can retain more genes be setting `min_cells=1` and `method="glmGamPoi"`.
