### ISSUE TITLE
How to extract a particular resolution cluster & save it as seurat object

### ISSUE THREAD

**Issue by Ankita-1211** [satijalab/seurat#5078]
I ran seurat find cluster using looping through mutiple resolutions. My serurata@metadata look like this.
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

  | orig.ident | nCount_RNA | nFeature_RNA | percent.mt | nCount_SCT | nFeature_SCT | SCT_snn_res.0.1 | seurat_clusters | SCT_snn_res.0.2 | SCT_snn_res.0.3 | SCT_snn_res.0.4 | SCT_snn_res.0.5 | SCT_snn_res.0.6 | SCT_snn_res.0.7 | SCT_snn_res.0.8 | SCT_snn_res.0.9 | SCT_snn_res.1.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AACACACTCGACGAGA | SeuratProject | 4462 | 2071 | 0.05445988 | 6629 | 2093 | 0 | 2 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0
AACAGGGTCAGAATAG | SeuratProject | 19959 | 4112 | 0.09183827 | 8600 | 2649 | 0 | 3 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0
AACCTGAAGATGGTCG | SeuratProject | 6301 | 1925 | 0.09458816 | 7062 | 1900 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 1 | 1 | 1

</body>

</html>

I want to make single seurat object from this data , one for each resolution so as to use it for some downstream work.

**for resolution 0.1**
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

  | orig.ident | nCount_RNA | nFeature_RNA | percent.mt | nCount_SCT | nFeature_SCT | SCT_snn_res.0.1
-- | -- | -- | -- | -- | -- | -- | --
AACACACTCGACGAGA | SeuratProject | 4462 | 2071 | 0.05445988 | 6629 | 2093 | 0
AACAGGGTCAGAATAG | SeuratProject | 19959 | 4112 | 0.09183827 | 8600 | 2649 | 0
AACCTGAAGATGGTCG | SeuratProject | 6301 | 1925 | 0.09458816 | 7062 | 1900 | 0

</body>

</html>

**for resolution 0.2**
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

  | orig.ident | nCount_RNA | nFeature_RNA | percent.mt | nCount_SCT | nFeature_SCT | seurat_clusters | SCT_snn_res.0.2
-- | -- | -- | -- | -- | -- | -- | -- | --
AACACACTCGACGAGA | SeuratProject | 4462 | 2071 | 0.05445988 | 6629 | 2093 | 2 | 1
AACAGGGTCAGAATAG | SeuratProject | 19959 | 4112 | 0.09183827 | 8600 | 2649 | 3 | 1
AACCTGAAGATGGTCG | SeuratProject | 6301 | 1925 | 0.09458816 | 7062 | 1900 | 0 | 0
AACGGGATCGTTATCT | SeuratProject | 8283 | 2632 | 0.07376554 | 7964 | 2597 | 1 | 0
AACTTCTGTATCATGC | SeuratProject | 3349 | 1393 | 0.05195581 | 6495 | 1501 | 3 | 1
AACTTCTGTGCGCTCA | SeuratProject | 8133 | 2224 | 0.07832288 | 7861 | 2200 | 1 | 0

</body>

</html>

**Comment by mhkowalski** [comment]
Thanks for your question. I would not recommend making multiple seurat objects for this purpose, as the only thing that is changing here is which clustering you'd like to use. To use different resolutions for downstream analysis, you can simply change the Idents of the object, such as `Idents(seurat_object) = seurat_object$SCT_snn_res.0.2`, etc.
