### ISSUE TITLE
Changing colors for SpatialFeaturePlot

### ISSUE THREAD

**Issue by li-shimin** [satijalab/seurat#5082]
Hello,

Thank you so much for this incredibly useful package!

I am having some issues with changing the colors of the points in my plot.
Below is the code I have right now:

p <- SpatialFeaturePlot(norm, features = c("CD3D", "PAX8"))
p + scale_colour_gradient(low = "white", high = "red") 

however, the colors are not changing. 

Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What is you use scale_fill_gradient?  See #3698 

Best,
Sam

**Comment by torkencz** [comment]
Or scale free continuous. See https://github.com/satijalab/seurat/issues/3698 .
