### ISSUE TITLE
MergeSeurat Question

### ISSUE THREAD

**Issue by GHHenryUTSW** [satijalab/seurat#509]
Does MergeSeurat only merge raw.data?

I'm trying to combine two different Seurat objects which have had full analysis done one them, just to do tSNE and cluster together, but be able to retain the stored Idents previously saved.

**Comment by satijalab** [comment]
We do not support this at the moment, but may modify in a future release. You can copy identities from the previous objects after merging using the SetIdent function (TransferIdent also enables this).
