### ISSUE TITLE
Is there a way to find shared genes in a single cluster?

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#5093]
Hello!

The only function I can think of in Seurat to find shared genes is `FindConservedMarkers()`, but it requires two groups. Is there a way to find conserved genes within just one cluster? As in, find the shared genes among all the cells labeled as (e.g.) "B cells"?

Thank you for reading!

**Comment by WesDe** [comment]
Hi,

Not a dev there but are you looking for genes that define a specific cluster such as "B cells" ? From [vignette](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html), you can access to this information through:
`cluster2.markers <- FindMarkers(pbmc, ident.1 = 2, min.pct = 0.25)`
Where ident.1 is the cluster you are looking for.

Hope it helps you.
WesDe

**Comment by torkencz** [comment]
Hi. FindAllMarkers and FindMarkers will highlight the markers that are shared amongst cells within a group relative to others. Potentially, you could do sub clustering within a cell type and  call markers that are not differentially expressed between those. That would highlight markers that are not necessarily DE with other cell types.

**Comment by ksaunders73** [comment]
Hello @WesDe and @torkencz ! This is both very helpful information, thank you very much for your replies!
