### ISSUE TITLE
error in pca analysis in seurat

### ISSUE THREAD

**Issue by rohit131** [satijalab/seurat#5094]
Hi,
Will you please explain why I am facing this error while I was doing scRNA analysis? and how should I overcome this?
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))
![image](https://user-images.githubusercontent.com/49091127/133765949-ba3fb6e6-4af9-4654-9132-de132f1533e6.png)

**Comment by timoast** [comment]
Please include the code you're running

**Comment by rohit131** [comment]
![image](https://user-images.githubusercontent.com/49091127/133872430-b5dfc3f2-8c8d-470f-94c4-f06f735bc28a.png)

**Comment by timoast** [comment]
Please include the full code, not as a screenshot
