### ISSUE TITLE
Impact on different R languages

### ISSUE THREAD

**Issue by hahahah-single** [satijalab/seurat#5097]
The data I obtained from public data is the seurat object created with R4.0.2, seurat3.2.2, can I continue to use the R3.6.3 environment for analysis. The seurat version remains unchanged. Is there any impact on different R languages?

**Comment by timoast** [comment]
Generally a change in R version does not create major user-visible changes. You can see the release notes for R here: https://cran.r-project.org/doc/manuals/r-devel/NEWS.html

**Comment by hahahah-single** [comment]
hi @timoast I can now read in the data smoothly for analysis, so can I continue to use R3.63 for analysis? Do you have relevant tests

**Comment by timoast** [comment]
The latest release of Seurat depends on R >=4.0.0 (because several of our dependencies do). You can install past versions of Seurat following instructions here: https://satijalab.org/seurat/articles/install.html#install-previous-versions-of-seurat-1

> Do you have relevant tests

Not sure what you're asking for

**Comment by hahahah-single** [comment]
hi @timoast    The public data is only created with Seurat 3.2.2.2, so should I use 3.6.3 for direct analysis? Would you like to ask if you compare different versions of R with the same version of Seurat, what are the differences and any suggestions?

**Comment by timoast** [comment]
You can use Seurat v3.2 with R v3.6.3. I don't expect major differences in analysis results based on the version of R that you use but we have not systematically quantified the difference in output for various analysis steps using difference versions of R

**Comment by hahahah-single** [comment]
thanks @timoast  So I directly use r3.6.3 to analyze the seurat object created by r4.02. Is such an operation feasible?

**Comment by timoast** [comment]
Yes
