### ISSUE TITLE
Issue with SplitObject and SCTransform 

### ISSUE THREAD

**Issue by pje1217** [satijalab/seurat#5099]
Hello, 

Thank you for developing an awesome tool like Seurat. It is so nice to have such a great tool for scRNAseq analysis. 

I am trying to run SCTransform on my seurat object "combined.filtered_2" (4.6 GB, about 200,000 cells).
Below are the codes I am having trouble running. 

**all.list <- SplitObject(combined.filtered_2, split.by = "sampleNames")**

**for (i in 1:length(x = all.list)) {
        all.list[[i]] <- PercentageFeatureSet(object = all.list[[i]], pattern = "^mt-", col.name = "percent.mt")
        all.list[[i]] <- SCTransform(all.list[[i]], vars.to.regress = c("percent.mt"), verbose = FALSE,return.only.var.genes=FALSE)
}**

I get this error message after running SplitObject (first line of codes) but I still get "all.list":
### number of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement lengthnumber of items to replace is not a multiple of replacement length

After this, I tried to run the next code (SCTransform). 
I get a message "iteration limit reached" repeated for about 15 mins and then I get this error message:
### Error in `[.data.frame`(cell_attr, , c(latent_var, batch_var, latent_var_nonreg)) : undefined columns selected

I am not sure what the issue is with SCTransform. Could you help me resolve this issue? Thank you!

**Comment by saketkc** [comment]
Can you try the suggestions in #5098?
