### ISSUE TITLE
SubsetCells returns cell.names or object

### ISSUE THREAD

**Issue by d93espinoza** [satijalab/seurat#51]
The SubsetCells function's documentation states that it returns a Seurat object. However, the code shows that it returns a vector of cell names if it finds valid cells to return, and it returns the input Seurat object if there are no cells fitting the desired subset definition.

**Comment by andrewwbutler** [comment]
You're absolutely right. SubsetCells should probably be deprecated. For this kind of functionality, I would recommend using either WhichCells and/or SubsetData for now.
