### ISSUE TITLE
Order of functions SCTransform & merge

### ISSUE THREAD

**Issue by ms-gx** [satijalab/seurat#5107]
I have 8 samples originating from different conditions of a cell line. For every  condition I have two biological replicates. So hence 2x8=16 samples.

I already determined that I do NOT want to perform integration, since it is "over-integrating" some cell states.

However, I was testing what happens if I:
1) Do first merge the samples and then perform SCTransform
or
2) First perform SCTransform on the 16 samples individually and then do the merge (What I think is in general the right way to do it. Do you agree?)

Now I see that it makes virtually no difference  which order I pick. The UMAP/tSNE lock almost identical & I get the same clusters with almost the same ratio of cells.

Is this often the case? And what does it tell me about my samples?

Or is there a potential error on my side if I see almost no difference?

**Comment by saketkc** [comment]
If there are no sufficient batch effects across samples, and the technology for all 16 samples are the same, it would not make much difference if you run SCTransform on the entire 16 samples object or on each object individually (which is what you observed too).

The recommendation to learn SCTransform on each sample individually is to ensure the model SCTransform learns of technical noise is specific to the dataset (assuming the different samples have varied technical noise), which doesn't seem to be the case in your samples.
