### ISSUE TITLE
Integrating 2 Multiome objects

### ISSUE THREAD

**Issue by vim15** [satijalab/seurat#5108]
Hello,

Firstly, thank you for all the amazing work you are doing and all the support that you provide to the community!
You have made so much accessible to so many with all of the tools and detailed vignettes you produce!

Sorry if I have missed this, if I did I would be grateful if you could point me towards the right direction. I was wondering what the best way is to integrate 2 multiome objects to be able to directly compare them, each of which contains an RNAseq Assay and a Chromatin assay (and an added wnn assay).

Not sure if there is a more standardised way to do this or if you would have something to recommend. A vignette would be great 😅
Thank you!

**Comment by torkencz** [comment]
Hi,

The discussion https://github.com/satijalab/seurat/discussions/4015 talks about this. At the moment we don't have a method to integrate multiome objects with WNN directly, but it is coming soon. We recommend integrating based on the transcriptome data and then doing downstream analysis from there.
