### ISSUE TITLE
Import UMAP/TSNE projection from cLoupe

### ISSUE THREAD

**Issue by chrismahony** [satijalab/seurat#5113]
I have an output file from CLoupe which has UMAP-1 and UMAP-2 coordinates for each barcode in a CSV.

I have made my Seurat object using the same cells, how can I import this information to recreate the UMAP projection in Seurat?

Thanks
Chris

[projectionUMAP.csv](https://github.com/satijalab/seurat/files/7202553/projectionUMAP.csv)

**Comment by samuel-marsh** [comment]
Hi,

So you will also need the cluster assignments from loupe to the corresponding barcodes in order to plot with the same cluster assignments.  But to add the UMAP coordinates:

```
# Read in data
UMAP_coordinates <- read.csv("~/Downloads/projectionUMAP.csv", stringsAsFactors = F, header = T, row.names = 1)

# change period in colnames to _
colnames(UMAP_coordinates) <- gsub(pattern = "\\.", replacement = "_", x = colnames(UMAP_coordinates))

# conver to matrix
UMAP_coordinates_mat <- as(UMAP_coordinates, "matrix")

# Create DimReducObject and add to object
OBJ_NAME[['UMAP']] <- CreateDimReducObject(embeddings = UMAP_coordinates_mat, key = "UMAP_", global = T, assay = "RNA")
```

Best,
Sam

**Comment by chrismahony** [comment]
Thanks, this makes sense, but I get the following error:

Error in CreateDimReducObject(embeddings = UMAP_coordinates_mat, key = "UMAP_", : Please ensure all column names in the embeddings matrix are the key plus a digit representing a dimension number

And this looks OK:

> head(UMAP_coordinates_mat)
     Barcode              UMAP_1          UMAP_2
[1,] "AAACCCAAGGTCGCCT-1" " -6.419446000" "-2.931856e+00"
[2,] "AAACCCAGTCATTGCA-1" " -3.437857000" " 5.469496e+00"
[3,] "AAACCCAGTCGAGCTC-1" " -0.702293750" "-5.717474e+00"
[4,] "AAACCCAGTGACTGAG-1" "-11.496453000" " 2.907400e+00"
[5,] "AAACGAAGTAGAGCTG-1" "  5.176882300" "-5.710409e+00"
[6,] "AAACGAAGTATGGAAT-1" "-11.302428000" " 2.817776e+00"

**Comment by samuel-marsh** [comment]
Hi,

Did you read the csv in using the `read.csv` code I posted?  It looks like your input file still has the barcodes as column.  The code I posted should move the barcodes column to rownames.

Best,
Sam

**Comment by chrismahony** [comment]
Sorry, I have done this now.

It seems to run, but I have this:

longer object length is not a multiple of shorter object lengthError: All cells in the object being added must match the cells in this object

I have 8390 cells in my Seurat object and 8565 in my UMAP_coordinates. What the best way to filter out the one that don’t appear in both? I have tried a few ways but with no success.

Thanks for the help,
Chris

**Comment by samuel-marsh** [comment]
Hi,

It depends which way you want to filter.  I believe the UMAP and analysis done by cell ranger is dependent on all of the cells and all of the genes being present so it's not technically accurate if you remove cells or genes when creating Seurat object.  So just set the `min.cells` and `min.features` parameters to 0 and that should do it.

As another note in my experience the UMAP/analysis done by cell ranger on my datasets has never seemed that good (as result of automated nature of it likely) and fact that you are not performing much filtering of the dataset before analysis/clustering so overall I'm not sure how much weight I'd put in the results output in cLoupe file.

Best,
Sam

**Comment by chrismahony** [comment]
Thanks for this, I tried:

srt[['UMAP']] <- CreateDimReducObject(embeddings = UMAP_coordinates_mat, key = "UMAP_", global = T, assay = "RNA", min.cells = 0, min.features = 0)

but I get:

Error in CreateDimReducObject(embeddings = UMAP_coordinates_mat, key = "UMAP_",  :
  unused arguments (min.cells = 0, min.features = 0)

Probably I have not set this up properly?

Thanks
Chris

**Comment by samuel-marsh** [comment]
Hi,

So the `min.cells` and `min.features` parameters should be used with `CreateSeuratObject`.  That will turn off filtering of the Seurat object so that all cells and genes are maintained when object created.

Best,
Sam

**Comment by chrismahony** [comment]
Thanks for this.

When I do this, I then have problems adding my cluster labels.

Do you know the best way to filter out cells that don’t appear in my Seurat objet and UMAP projection matrix?

Thanks
Chris
________________________________

**Comment by samuel-marsh** [comment]
Hi Chris,

Can you send the lengths of barcodes in the raw matrices: gex, cluster annotation, and umap coordinates?

Best,
Sam

**Comment by samuel-marsh** [comment]
That way can figure out what is best path forward by understanding where the differences lie.

**Comment by samuel-marsh** [comment]
Is str the seurat object or the raw matrix after `Read10X`.

What doesn't make sense to me is why the cluster annotation and the UMAP coordinates have difference numbers of cells present?  That shouldn't be possible.  I would double check files are correct.  If they are both the outputs from loupe then something seems wrong as I'm not sure how you can annotate cells that aren't present in the UMAP coordinates file.

Best,
Sam

**Comment by chrismahony** [comment]
Str is the Seurat object. The raw matrices are:

length(colnames(srt1.data))
[1] 3200
> length(colnames(srt2.data))
[1] 5697

Then I did CreateSeuratObject on these and merged.

I have just exported the cluster info again from loupe and I have:
9035 cells (including unlabelled)
9032 cells (excluding unlabelled)

My UMAP position csv directly from Loupe also has 9035 cells.

And the extract of the R code I used to match barcodes to cluster ID:

s=str_split_fixed(clstr$Barcode,"-",2)
head(s)
table(s[,2])

s=cbind(s,NA)
head(s)
s[s[,2]==1,3]="WT"
s[s[,2]==2,3]="mutant"
head(s)

clstr$Barcode=paste0(s[,3],"_",s[,1],"-1")

head(clstr)
table(clstr$dHSPCs.spink2.2)

***@***.***) %in% clstr$Barcode)
table(clstr$Barcode %in% ***@***.***) )


***@***.***),clstr$Barcode),2])
head(srt$cell_type)

table(srt$cell_type,useNA = "ifany")

Thanks
Chris

**Comment by samuel-marsh** [comment]
So again there seems to be something weird because adding the totals from your samples 1 and 2 gets only (5697+3200 =8897) which is less than the total included in UMAP and clustering.  The primary issue you are having is because cell number doesn't match.  So need to figure out what's going wrong there.

As I mentioned earlier when creating Seurat objects for this you need to set `min.cells` and `min.features` to 0.  Otherwise cells will be filtered during object creation.

Best,
Sam

**Comment by chrismahony** [comment]
Thanks.

I have tried this with min.cells and min.features to 0 when I create the Seurat object and I have 8897 cells.

I then add cluster labels as before.

When I run the code you sent my UMAP_coordinates has 9035 cells. So I do:

UMAP_coordinates2 <- ***@***.***$RNA),]

UMAP_coordinates2 now has 8897 cells.

I then run:

UMAP_coordinates_mat_new <- as(UMAP_coordinates, "matrix")
srt[['UMAP']] <- CreateDimReducObject(embeddings = UMAP_coordinates_mat_new, key = "UMAP_", global = T, assay = "RNA")


and get:

Error: All cells in the object being added must match the cells in this object


Thanks and appreciate all the help!
Chris

**Comment by samuel-marsh** [comment]
Hi Chris,

So yes this is overall problem that doesn't make sense.  Your cells file has less cells than the loupe file UMAP and cluster assignment coordinates.

Something is going wrong here.  Before moving any of these files into Seurat they need to have same number of cells or at least a clear rationale for filtering.  

It doesn't make sense that the raw number of cells (from `Read10X`) is less than the number of cells in the UMAP coordinates.  That's why I suggest checking the underlying data again first because something seems to be going wrong there.

It also doesn't really make sense to filter the UMAP/cluster assignments to match the raw cell number because those cluster assignments and UMAP coordinates are based on all cells being present.  So if you were to filter them to match the number of raw cells then they wouldn't be valid representations of the data anymore.

Hope that makes sense.
Best,
Sam

**Comment by chrismahony** [comment]
Thanks again for looking into this.

I am not sure what the problem is. I have replotted the UMAP and tSNE plts in Seurat from the object and this gives me a good plot that I should be able to use.

Many thanks again for the help,
Chris
