### ISSUE TITLE
Aligning data to custom genomes - can’t find GFP

### ISSUE THREAD

**Issue by jvelghe** [satijalab/seurat#5115]
Hi, I aligned our dataset to a reference genome like I usually do through the CellRanger process. The only difference is this time it is a custom genome, the only difference is that we added GFP. 

At the end of the CellRanger pipeline, we can see that GFP is expressed in the loupe browser as expected, so it looks like our data properly aligned to the reference genome. 

When moving the data to Seurat however, we don't see any GFP expression. I couldn't find anything that might explain why it isn't being picked up in the Seurat codes that could explain why. It's as if it was aligned to the reference genome, but GFP was just ignored. I've been looking into this for a while but can't figure out why it wouldn't be showing up in Seurat, can anyone help with this?

Thank you,
Jane

**Comment by samuel-marsh** [comment]
Hi Jane,

Not member of dev team but hopefully can be helpful.  Two questions, what did you set the `min.cells` and `min.features` parameters to when using `CreateSeuratObject`?

Second, what is the output of the following code where MATRIX_NAME is whatever you named the raw data matrix read in using `Read10X`.  Also swap out "GFP" with the exact name (and capitalization) that you used in your custom reference genome.
```
grep(pattern = "GFP", x = rownames(MATRIX_NAME), value = TRUE)
```

Best,
Sam

**Comment by torkencz** [comment]
Hi Jane, like @samuel-marsh said it could have been filtered out via min.cells and min.features. I can reopen this in case that does not solve the problem.
