### ISSUE TITLE
Annotation using markers genes as reference

### ISSUE THREAD

**Issue by andynkili** [satijalab/seurat#5116]
I would like to use markers genes (resulting from FindAllMarkers) as a reference.
The idea would be to compute a similarity matrix between the marker genes of my to-be-annotated data and the marker genes of the reference. The result would be a heatmap of similarity score between clusters from my data and the reference.

Any thoughts/ideas?

Is there some kind of built-in function that would at least compare two marker gene dataframe?

**Comment by akstks** [comment]
Not a member of the dev team, but as far as I know there is no function to do this built in Seurat. 

However I personally like using SingleR, which is great for reference-based annotation. 
Take a look here to see if you could utilize such an approach:

http://bioconductor.org/books/release/SingleRBook/annotation-diagnostics.html#based-on-marker-gene-expression

**Comment by andynkili** [comment]
Actually, I have already looked into singleR and have used it.
I have been looking for a way to use the marker genes as an reference with singleR, in vain.
From the singleR book, it seems you can get the marker gene expression as an output to visualize the different profile expression but I don't see anything in the book related to using the marker gene expression as a reference (input) to annotate a original dataset.

That is the reason I am trying to come up with another way for annotating a dataset by comparing its marker gene expression with an other one from an already annotated dataset.

The idea here would be to compute a similarity (cosine, euclidean, ....) between the marker gene expression of 2 datasets, cluster-wise.
Let's say, each marker gene expression (or Seurat's FindAllMarkers output) is a dataframe (one for the reference and one for the dataset to annotate).
My first guess is that I need to aggregate both dataframes by cluster. 
After that I would get the intersection of the genes from both dataframes.
But then, how can I compute a similarity between 2 clusters (from each dataframe) based on their genes that have multiple variables (p.val,   p.val.adj, pct.1, pct2 and avg_log2FC)?
Another idea would be: computing the similarity between 2 clusters (from each dataframe) based on their genes using only 1 variable, but which one should I choose? p.val? avg_log2FC?

**Comment by mhkowalski** [comment]
Hi,

You are correct that Seurat does not have this functionality built in. One downside of this approach is that it would require you to label cells at the cluster level (i.e. all cells in cluster 1 of the query will have the same predicted annotation), so this might not be robust to different resolutions of clustering. You could try annotating individual cells in your query dataset using your reference with the ```FindTransferAnchors()``` and ```TransferData()``` workflow, as shown [here](https://satijalab.org/seurat/articles/integration_mapping.html)

If you are interested, you could merge your reference and query datasets together and use the ```FindConservedMarkers()``` function (see [here](https://satijalab.org/seurat/articles/integration_introduction.html) for an example) to check that your original gene markers are still coming up when you group by dataset. This combines the p-values in both dataset using the MetaDE R package to make sure that genes are differentially expressed in both the reference and the query. I'm happy to provide more details or clarification if this is something you are interested in, please reopen the issue if that is the case.
