### ISSUE TITLE
ADT integration with small number of features

### ISSUE THREAD

**Issue by mvis1231** [satijalab/seurat#5118]
Hi, 
I have been trying to integrate 3 samples of ADT from CITE-seq data to run WNN analysis on both integrated RNA and integrated ADT objects.
Since my data has only 5 features in each sample (the total number of cells from the 3 samples are about 12,000), I have been dealing with some problems along with the standard integration.

My code was:
```
adt.list <- list(obj1,obj2,obj3) ## where all of the objects were normalized using NormalizeData(each obj, assay = "ADT", normalization.method = "CLR", margin = 2) and also variable features were selected from VariableFeatures(each obj) <- rownames(each obj[["ADT"]]). Default assay has been set to ADT for all samples
features <- SelectIntegrationFeatures(object.list = adt.list, nfeatures = 5)
anchors_ADT <- FindIntegrationAnchors(object.list = adt.list, anchor.features = features, dims = 1:4, k.filter = NA, max.features = 5)
integrated_ADT <- IntegrateData(anchorset = anchors_ADT, new.assay.name = "integratedADT", dims = 1:4, k.weight = 4)
```
(Trying to set k.filter = NA and k.weight = 4 due to the small number of features)

While running IntegrateData() I have error saying,

> Merging dataset 3 into 1
> Extracting anchors for merged samples
> Finding integration vectors
> Warning in irlba(A = t(x = object), nv = npcs, ...) :
>   You're computing too large a percentage of total singular values, use a standard svd instead.
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 2 into 1 3
> Extracting anchors for merged samples
> Finding integration vectors
> **Error in irlba(A = t(x = object), nv = npcs, ...) : 
>   max(nu, nv) must be positive**

And even before this error, the FindIntegrationAnchors() gave me warning that:

> Finding all pairwise anchors
>   |                                                  | 0 % ~calculating  Warning in RunCCA.Seurat(object1 = object.1, object2 = object.2, assay1 = "ToIntegrate",  :
>   Fewer than 50 features used as input for CCA.
> Running CCA
> Merging objects
> Finding neighborhoods
> Finding anchors
> 	Found 11630 anchors
>   |+++++++++++++++++                                 | 33% ~17s          Warning in RunCCA.Seurat(object1 = object.1, object2 = object.2, assay1 = "ToIntegrate",  :
>   Fewer than 50 features used as input for CCA.
> Running CCA
> Merging objects
> Finding neighborhoods
> Finding anchors
> 	Found 12824 anchors
>   |++++++++++++++++++++++++++++++++++                | 67% ~08s          Warning in RunCCA.Seurat(object1 = object.1, object2 = object.2, assay1 = "ToIntegrate",  :
>   Fewer than 50 features used as input for CCA.
> Running CCA
> Merging objects
> Finding neighborhoods
> Finding anchors
> 	Found 11668 anchors
>   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=25s

Could you please help me resolve this issue?

Thanks a lot!

**Comment by yuhanH** [comment]
If you only integrate the first and third objects, do you still meet this error?
