### ISSUE TITLE
Retrieve GenePlot legend?

### ISSUE THREAD

**Issue by veghp** [satijalab/seurat#512]
GenePlot() colors the cells by their id. Is there a way to know what the colors represent, via a legend or some other way?

**Comment by satijalab** [comment]
You can set do.hover=T, to hover over individual points and see information about individual cells

**Comment by veghp** [comment]
Thank you for the quick reply. Unfortunately this solution cannot be saved into a file.

**Comment by amayer21** [comment]
Hello,
Is there now a solution to this?
It would be nice to be able to add a legend on the plot when ploting different populations in different colors.
Thank you very much,
All the best,
Alice

**Comment by andrewwbutler** [comment]
Hi,

In Seurat v3, `GenePlot` is now `FeatureScatter` and returns a ggplot object that you can manipulate as you would any other ggplot object. By default it now includes the legend.

**Comment by amayer21** [comment]
Thank you very much! Looking forward to it!
