### ISSUE TITLE
How to generate a raw count matrix

### ISSUE THREAD

**Issue by li-shimin** [satijalab/seurat#5120]
Hello, 
I would like to generate a raw count matrix of my data in my SeuratObject. I've attached an example of what it should look like with a matrix of genes (rows) vs cells (columns). I understand that you can extract the features using rownames() but how do I find which genes are associated with which cells?

![sampleMatrix](https://user-images.githubusercontent.com/89268537/134519870-afd0f203-a76a-48fd-b600-80d6ebacf805.PNG)

Thank you for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I believe the function you are looking for is `GetAssayData`.  You can then specify which assay and which slot you want to pull values from depending on desired data.

Best,
Sam

**Comment by li-shimin** [comment]
Thank you! That is exactly what I needed.
