### ISSUE TITLE
MapQuery: Cell type classification and UMAP projection of query Inconsistent with reference UMAP

### ISSUE THREAD

**Issue by hbandukw** [satijalab/seurat#5122]
Hello,

When using MapQuery with a reference atlas for analyzing my query datasets, I get the following results:

Query dataset 1:
![image](https://user-images.githubusercontent.com/20444993/134561274-35739e6d-fd44-44f4-b335-b124f4bac9ba.png)

Query dataset 2:
![image](https://user-images.githubusercontent.com/20444993/134562155-d7468573-1372-4b25-a78c-a80d0a485ef2.png)

# Question 1
I am confused as to why cells with the same label don't appear together on the UMAP e.g. shouldn't all the query cells annotated as "FAPs (Adipogenic)" appear **together** and relatively in the same location as the original reference UMAP?

 If I am not mistaken, this behaviour is displayed in the example posted on Seurat's integration-mapping vignette (https://satijalab.org/seurat/articles/integration_mapping.html) i.e. all alpha cells appear together and in the same location as the reference UMAP. 

![image](https://user-images.githubusercontent.com/20444993/134561996-7c5c8929-c6bd-4061-8563-dfe23d9a30c6.png)

# Question 2
 A lot of the cell labels do not make any biological sense. Is there any way to trace what genes are contributing to the labelling? 

# Question 3
The vignette mentions that "IntegrateEmbeddings() is used to integrate reference with query by correcting the query’s projected low-dimensional embeddings". 
Since I am not specifying what embedding to use for the query, I was wondering what the default is? 

Version Info
Seurat_4.0.4 

Code
```
# Found Anchors 
anchors <- FindTransferAnchors(reference = ref, query = query,
                                   dims = 1:30, reference.reduction = "harmony")

# Re-ran UMAP to return model 
ref <- RunUMAP(ref, dims = 1:30, reduction = "harmony", return.model = TRUE, reduction.name = "UMAPharmonyv2", reduction.key = "UMAPharmonyv2_")

# MapQuery for Reference mapping
query <- MapQuery(anchorset = anchors, reference = ref, query = query,
                      refdata = list(celltype = "harmony_factorIDs"), reference.reduction = "harmony", reduction.model = "UMAPharmonyv2")
```
 
Thanks in advance!

**Comment by yuhanH** [comment]
Q1: It doesn't look right. Could you post the scripts you used for generating reference and mapping query?
Did you do any subet on the reference object after RunUMAP?
Q2: when we fix Q1, we can go back to check the genes. 
Q3: query cells are projected into your reference reduction, harmony.

**Comment by hbandukw** [comment]
Hi,

1) Generating Reference
The reference was generated by a colleague, they used Harmony (https://github.com/immunogenomics/harmony) for integration and the code is available here: https://github.com/mckellardw/scMuscle/blob/main/R_scripts/scMuscle_github_v1.R. 
With respect to whether the reference object was subsetted after RunUMAP:
The associated paper (https://www.biorxiv.org/content/10.1101/2020.12.01.407460v2.full#F8) says the following 

_"After preprocessing and quality filtering, we merged the datasets and performed batch-correction with three tools, independently-Harmony (github.com/immunogenomics/harmony) (v1.0), Scanorama (github.com/brianhie/scanorama) (v1.3), and BBKNN (github.com/Teichlab/bbknn) (v1.3.12). We then used Seurat to process the integrated data. After initial integration, we removed the noisy cluster (Fig. S4) and re-integrated the data using each of the three batch-correction tools."_

If this information isn't adequate, I can reach out to the colleague.


2) Mapping query:
The code was mapping my query was posted in my last comment:

```
Mus.ref <-  LoadH5Seurat(nameofRef)
Mus.query <- readRDS(nameofQuery)
Mus.query = UpdateSeuratObject(Mus.query)

# Found anchors
Mus.anchors <- FindTransferAnchors(reference = Mus.ref, query = Mus.query,
                                   dims = 1:30, reference.reduction = "harmony")

# Re-ran UMAP to return model
Mus.ref <- RunUMAP(Mus.ref, dims = 1:30, reduction = "harmony", return.model = TRUE, reduction.name = "UMAPharmonyv2", reduction.key = "UMAPharmonyv2_")

# MapQuery
Mus.query <- MapQuery(anchorset = Mus.anchors, reference = Mus.ref, query = Mus.query,
                      refdata = list(celltype = "harmony_factorIDs"), reference.reduction = "harmony", reduction.model = "UMAPharmonyv2")

```
Do you need anything other than this?

**Comment by yuhanH** [comment]
HI, 
the code looks good for me. 
It will be much easier for me to figure it out if you can send me the reference object: yhao@nygenome.org
Thanks.

**Comment by hbandukw** [comment]
Ok, I will confirm with the colleague and get back to you. Thanks!

**Comment by hbandukw** [comment]
Hi @yuhanH, I have shared the reference object via google drive. Let me know if you can access it.

Thanks!

**Comment by yuhanH** [comment]
hi @hbandukw 
Thanks for sharing. I get it.

**Comment by yuhanH** [comment]
hi @hbandukw 
Currently, harmony reduction doesn't work well for mapping strategy.   Because the feature loadings in harmony are not orthogonal matrix,  projection query cells to the reference harmony space doesn't work under our current settings. 
We will explore the possibilities to incorporate harmony into our mapping method.

**Comment by sabrinacamp2** [comment]
Are there any updates on incorporating Harmony into the mapping method? I think many folks would find this useful since most datasets need some version of batch correction and Harmony is a popular choice.

**Comment by yuhanH** [comment]
Hi, @sabrinacamp2 
Sure. You can use harmony for the mapping method now. 
Either you can install harmony devel branch [immunogenomics:devel](https://github.com/immunogenomics/harmony/tree/devel) or you can change the feature loadings of harmony following this step: https://github.com/immunogenomics/harmony/pull/144

**Comment by sabrinacamp2** [comment]
Hi,

Thanks for the response. If the harmony feature loadings are replaced with non-harmony adjusted loadings (in my case, LSI components), wouldn't this cause issues? I'm imaging a situation where pre-harmony the top features separating the cells are dataset-specific ones, but after harmony features separating the cells are biologically relevant.

**Comment by yuhanH** [comment]
hi @sabrinacamp2 
harmony just correct the embeddings and does not really generates a batch-effect-free feature loadings, so you don't need to worry about that situation. 
In seurat mapping, after the query is projected to the reference PCA, there's still a batch correction step.

**Comment by erzakiev** [comment]
What if I want to project to an existing embedding which is not UMAP? Say, if the reference used PHATE 
mapping? Is there a workaround?
