### ISSUE TITLE
Ident. 1 vs Ident. 2 in FindMarkers() Function

### ISSUE THREAD

**Issue by sameehan2301** [satijalab/seurat#5127]
Hello all,
I hope everyone is doing good. I had a question regarding the position of ident.1 and ident.2 in the FindMarkers function while performing DEG. To give some context, I have two groups - Control and Disease. 
Based on this, could someone please let me know what is the correct way to place these two groups as ident.1 or ident.2?
Would Control be ident.1 or ident.2 and similarly, Disease be ident.1 or ident.2?
I tried reversing the order and checking if it makes any difference, and it does. The genes that are downregulated when Control is ident.1 are upregulated if Control is set as ident.2.
I would really appreciate it if someone can explain the correct way to do this as I assume, it is really important before looking at up or downregulated genes. 
Thank you,
Regards,
Sam.

**Comment by torkencz** [comment]
Hi, if you are comparing two groups ident.2 will be your reference ( I assume control for you). If you leave it blank it will compare to all other groups. You can very easily look at this if you plot the expression of your markers that you get from findMarkers.

**Comment by sameehan2301** [comment]
Thank you for the comment. However, the interpretation would be - 
1. Control = ident.2 and Disease = ident.1 - If a gene has a negative avg_log2FC value, then it could be interpreted as that gene is downregulated in Control as compared to the Disease?
2. If I put Control = ident.1 and Disease = ident.2 then a gene with negative avg_log2FC value would be interpreted as that gene is downregulated in Disease as compared to Control?

I am interested in understanding the interpretation of the avg_log2FC values as well when ident.1 and ident.2 are changed.
Thank you for your help!
Regards,
Sam.

**Comment by torkencz** [comment]
1. Log2FC positive: Disease is upregulated relative to control, negative log2FC: disease is downregulated relative to control. 
2. Log2FC positive: Control is upregulated relative to disease, negative log2FC: control is downregulated relative to disease.

**Comment by AipingZhang** [comment]
[](url
<img width="887" alt="Screenshot 2022-05-31 at 21 37 27" src="https://user-images.githubusercontent.com/66343257/171186961-88fb9edb-831f-45a4-841d-c28a5f2e1351.png">
)
<img width="746" alt="Screenshot 2022-05-31 at 21 38 51" src="https://user-images.githubusercontent.com/66343257/171187214-41b61ffa-6633-4ff6-9ae2-6613d753b024.png">

[](url)

Hi, I have a question about negative and positive avg_log2FC.
Here, it seems Ccl9 was upregulated in the LN group, but why the avg_log2FC is negative?
