### ISSUE TITLE
Filter cells/clusters by Z-score threshold for a gene of interest

### ISSUE THREAD

**Issue by cebriggs7135** [satijalab/seurat#5129]
sdx <- GetAssayData(pbmc_small, slot="scale.data")
gives me the cell-by-gene matrix of the Z-scores.

Once I have Z-score matrices for a selection of datasets (e.g. different tissues or disease states), I want to:
-Filter the datasets based on max |Z-score| for my gene of interest.
-Filter a selected dataset to show me just those cells in which my gene of interest had a |Z-score| above some threshold.
-Filter clusters in a selected dataset to show me just those clusters in which my gene of interest had a |Z-score| above some threshold.

**Comment by yuhanH** [comment]
HI,
you can directly find your target cells on the matrix sdx and then `subset` the object  by cells directly. 
For example, 
```
sdx <- GetAssayData(pbmc_small, slot="scale.data")
target <- c("S100A8", "S100A9")

select.cells <-   Cells(pbmc_small)[which(colSums(sdx[target,]) > 3)]
pbmc_small.sub <- subset(pbmc_small, cells = select.cells )
```

**Comment by cebriggs7135** [comment]
@yuhanH Thanks. 
That's almost it. I don't want the Z-scores to be summed so a slight tweak to your code gives me exactly what I want - just the cells in which my gene of interest is expressed at Z>2 (for instance):

select.cells <- Cells(seurat_object)[which(sdx[target,] > 2)]

Thanks again.
