### ISSUE TITLE
changing axis labels

### ISSUE THREAD

**Issue by elengss** [satijalab/seurat#5131]
Hi there,
Many thanks for all your help.
I'm trying to remove the word 'anndata' from the labels from DotPlot function

plot<-DotPlot(object = so, features = inter, split.by = 'new_clust', cols = c("#0000FF","#F0000F","#FF000F","#FFF00F","#FFFF0F","#00000F","#F0F00F","#F000FF","#F00F0F","#0F000F","#0FFF0F","#0FFF00"))

> head(so[['new_clus']])
                                                  new_clus
AAACCTGCACCCATGG-1-CARTP00G1LI_AMP lymphoid tissue inducer
AAACCTGTCACTTATC-1-CARTP00G1LI_AMP             colonocytes
AAACCTGTCGCTTGTC-1-CARTP00G1LI_AMP             colonocytes
AAACCTGTCTGCAGTA-1-CARTP00G1LI_AMP                 T cells

However, the y axis labels look like this. Do you know of any way I can get rid of the word 'anndata'? Thanks

![image](https://user-images.githubusercontent.com/85126449/134770841-51422a3c-7979-4270-8cf0-b821b910265d.png)

**Comment by mhkowalski** [comment]
If you view `head(Idents(so)`, do you see AnnData come up? The `split.by` parameter is typically used when you are trying to depict expression by 2 levels of information, such as cell type identity and sample. In this case, you should use `group.by='new_clust' ` instead of `split.by='new_clust'  `.
