### ISSUE TITLE
Data Integration and FindingMarkers

### ISSUE THREAD

**Issue by chitcode** [satijalab/seurat#5132]
Hi,

We are analyzing multiple Spatial Visuim datasets from independent experiments (but similar tissue sections). We followed the Seurat data integration pipeline [normalized individual datasets using SCTransform(), followed by SelectIntegrationFeatures(), PrepSCTIntegration(), FindIntegrationAnchors(normalization.method = "SCT",...), and IntegrateData(normalization.method = "SCT",...)]. As expected, we are not observing any batch effect in the clusters after using the integrated data.

Question: As a next step, for finding the marker genes using FindMarkers() and FindConservedMarkers() functions, which assay should be used? Should it be "integrated", "SCT" or "RNA"?

In the article https://satijalab.org/seurat/articles/integration_introduction.html , "RNA" is set as the default assay before running FindConservedMarkers() function. The motivation of data integration is to bring different datasets to the same reference scale so that they can be compared. Then, why shouldn't we use the "integrated" data for finding the conserved genes?

Thanks.

**Comment by saketkc** [comment]
Please see the relevant [discussion](https://github.com/satijalab/seurat/discussions/4000)
