### ISSUE TITLE
Error in WhichCell( ) and subset( ) with the gene has "-"in

### ISSUE THREAD

**Issue by swaggggyzhao** [satijalab/seurat#5133]
Hi,

I see there is a same question in 2019 but it was closed and there is unanswered question saying backticks didn't work in Seurat 4.  So I want to create a new one to remind you.
I'm using a Seurat version 4.0.3. I was trying to set up a second idents by the gene expression >0 or =0.
I did : 
        AC5_LH3_PC$group[WhichCells(AC5_LH3_PC, expression="Ighv7-1" > 0, idents = "AC5_GE" )]="C3d_MMPC"
and had the error : 
        Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
          None of the requested variables were found:

Plus, I already confirmed that I have lots of cells expressing this gene.  

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Have you tried backticks yourself?  Using SeuratData I can confirm backticks work for me with `WhichCells` with Seurat 4.0.4.

```
library(Seurat)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
test <- WhichCells(pbmc, expression=`MT-ND1` > 0)
length(test)
[1] 2496

test <- WhichCells(pbmc, expression=`MT-ND1` > 3)
length(test)
[1] 1178
```

Best,
Sam

**Comment by samuel-marsh** [comment]
Awesome!  Glad it worked!!
