### ISSUE TITLE
Perform SCT and then merge while keeping variable features

### ISSUE THREAD

**Issue by ms-gx** [satijalab/seurat#5135]
I have several samples.

If I first do perform
1) `SCTransform`
on them individually and then
2) `merge`,
I loose the variable features and can not do PCA. Can merge not preserve the variable features in this case from SCT-Step?

What is the ideal way to add the VariableFeatures after the merge? Run `SCTransform` again? But then I would do SCT on the merged samples which I do not want...

**Comment by mhkowalski** [comment]
Hi, 

You can simply set the VariableFeatures to the features in the scale.data slot of the merged SCT assay, which by default includes only the residuals from variable features.  Please see #2814.
