### ISSUE TITLE
showing subsets on tSNE plot

### ISSUE THREAD

**Issue by doctorjb77** [satijalab/seurat#514]
What would be the best way to show a subset (i.e. different samples) in a tSNE plot, while maintaining the overall structure of the tSNE plot generated using the merged data (including colors for the original clusters). thanks

**Comment by terooatt** [comment]
I was trying to do this as well. Any help figuring this out will be really great. Thanks

**Comment by satijalab** [comment]
You can use the do.highlight argument in DimPlot that will maintain the overall structure, in the plot, but highlighting individual cells with a different color.

This cannot simultaneously maintain the colors in the original plot, to ensure that you can clearly see the newly highlighted cells.
