### ISSUE TITLE
question regarding exporting data from Seurat package

### ISSUE THREAD

**Issue by khaled406** [satijalab/seurat#5140]
I want to extract log normalised data and I wonder which option in “slot” to use ? is it “data”, “scale.data”, or “counts”?. I’m confused and I really want to understand what kind of data I’m extracting using each of these options.

I use this command: 

WhichCells(pbmc, idents = "5") Cluster5.data <- as.matrix(GetAssayData(pbmc, assay = "RNA", slot = "data")[, WhichCells(pbmc, ident = "5")]) write.table(cluster5.data, "/Users/Desktop/10X_data/cluster5.csv")

Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team of dev team but hopefully can be helpful.  If you want to learn more about inside of Seurat object structure I suggest checking out the wiki https://github.com/satijalab/seurat/wiki.  Specifically I believe this section is what you are looking for https://github.com/satijalab/seurat/wiki/Assay#slots.

Best,
Sam

**Comment by khaled406** [comment]
> Hi,
> 
> Not member of dev team of dev team but hopefully can be helpful. If you want to learn more about inside of Seurat object structure I suggest checking out the wiki https://github.com/satijalab/seurat/wiki. Specifically I believe this section is what you are looking for https://github.com/satijalab/seurat/wiki/Assay#slots.
> 
> Best,
> Sam

Many thanks I will take a look :)
