### ISSUE TITLE
cell clusters overlapping

### ISSUE THREAD

**Issue by Toby132** [satijalab/seurat#5146]
The seurat UMAP clustering algorithm clusters my cell data as multiple types within a single blob. As in there is 4 seurat clusters within one large space, and when I use my own labels, the clusters overlap. Is it possible to get the large blob identity in seurat and then cluster that embedding externally to do some sort of population testing/counting?

**Comment by yuhanH** [comment]
Hi, 
You may decrease the resolution parameter in the `FindClusters`.  The low resolution value can give you bigger clusters. 
Or you can directly merge those 4 small clusters into a big one.
