### ISSUE TITLE
export cell cycle scoring output

### ISSUE THREAD

**Issue by leiliang98** [satijalab/seurat#5149]
In the Cell-Cycle Scoring and Regression vignette:
https://satijalab.org/seurat/archive/v3.1/cell_cycle_vignette.html

After running the following command:
marrow <- CellCycleScoring(marrow, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

Is there a way to write out the output (marrow) as a csv file? Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  In this scenario marrow is a Seurat Object.  Are you just interested in writing the results of scoring to csv?  If so you can write the data.frame contained in meta.data slot to csv file as you would with any data frame.

Best,
Sam

**Comment by leiliang98** [comment]
Hi Sam,
I am interested in the scores, phase assignment and identities etc. Is there a code I can try? I am using R. Thanks

**Comment by samuel-marsh** [comment]
Hi,

After completing cell cycle scoring you can run the following.  I would suggest familiarizing yourself with some base R or tidyverse style R data manipulation as this is pretty straightforward.

```
library(tidyverse)
library(Seurat)

meta_df <- OBJ_NAME@meta.data %>% 
  rownames_to_column("barcodes") %>% 
  select(barcodes, S.Score, G2M.Score, Phase)

write.csv(x = meta_df, file = "PATH")
```

Best,
Sam

**Comment by leiliang98** [comment]
Thanks Sam, that solves it. I am a wet lab scientist in training and am analyzing my first ScRNAseq dataset. It is fascinating how much the technology has advanced and I am learning as it goes. Best

**Comment by samuel-marsh** [comment]
No problem!  That's how I started too.  I learned ton by doing tutorials and online books just focused on using R that have were really invaluable in understanding what to do once I got to scRNAseq analysis itself.  Best of luck!!

Sam
