### ISSUE TITLE
DEenrichRPlot

### ISSUE THREAD

**Issue by cadyyuheng** [satijalab/seurat#5151]
Hello,

I notice there's this DEenrichRPlot function included in the Seurat package, yet I didn't find any tutorial that covers it. As I was giving it a shot, I got an error as below, and wonder if I could get any help from the developers. I really appreciate it!

```
DEenrichRPlot(object = ctrl.test, ident.1 = "Basal_1",ident.2 = "Basal_2",enrich.database = "BP",max.genes = 50)
```
```
Error in do.call(what = cbind, args = pos.er) : 
second argument must be a list
```

**Comment by mhkowalski** [comment]
I believe the problem is that "BP" is not an EnrichR database. Can you try with `enrich.database = "GO_Biological_Process_2013" `, or one of databases here? https://maayanlab.cloud/Enrichr/#libraries

**Comment by cadyyuheng** [comment]
Thanks a lot, @mhkowalski! It worked, and the list of databases is also very helpful:)

**Comment by evchambers** [comment]
This can also be caused by not loading the enrichr package 1st.
