### ISSUE TITLE
Integration of 4 samples from CITE-SEQ (RNA+ADT) - Normalization of ADT in different function call

### ISSUE THREAD

**Issue by RM83** [satijalab/seurat#5154]
I have a follow-up question on a closed issue https://github.com/satijalab/seurat/issues/3890
I have four samples with RNA + ADT (10 ab) and I am trying to integrate the RNA and ADT separately using the recommendations stated in https://github.com/satijalab/seurat/issues/3890 and https://github.com/satijalab/seurat/issues/5089. My question is related to ADT data normalization. I understood why CLR is preferred for normalizing the ADT data. But, for FindIntegrationAnchors() and IntegrateData() we can only use either LogNormalize or SCT. Is it ok to use CLR in the function NormalizeData() and LogNormalize in the functions  FindIntegrationAnchors() and IntegrateData()? If yes, why?

Thank you so much for developing Seurat.

**Comment by yuhanH** [comment]
Hi,
You can use `LogNormalize` for in `FindIntegrationAnchors`. `LogNormalize` in `FindIntegrationAnchors` mainly means that you are going to correct expression in the data slot, while SCT in `FindIntegrationAnchors` is designed to correct SCT residuals.

**Comment by RM83** [comment]
Please also confirm if I need to use LogNormalize in the function IntegrateData() while my original normalization in the function NormalizeData() was CLR ! If yes then how can I get the benefit of doing CLR normalization, which is appropriate for ADT data? Because, eventually I am going to do clustering based on the LogNormalize data, not the CLR based normalized data. I am confused. Please shed light on it. I appreciate your prompt reply and help.

**Comment by yuhanH** [comment]
HI, 
When you set `LogNormalize` in `FindIntegrationAnchors`,  it will not re-normalize your data. It will still use you CLR-normalized data as the input. `FindIntegrationAnchors` and `IntegrateData` are used to get rid of the batch effects in your data instead of re-normalizing your input data, so, after integration, you are using corrected CLR-normalized data to do the downstream analysis.

**Comment by RM83** [comment]
I appreciate your help. Thank you so much.
