### ISSUE TITLE
Bringing subcluster information back to metadata

### ISSUE THREAD

**Issue by khsaleh88** [satijalab/seurat#5156]
Hi, 

I'm trying to bring information of my subcluster analysis back to the metadata, I followed this and it worked for me:
https://github.com/satijalab/seurat/issues/1748
However, I have multiple sub-cluster analysis, and I would like them to appear all on one DimPlot. would that be at all possible? Would appreciate the help!
Thank you!

**Comment by yuhanH** [comment]
hi 
You can select those sub-cluster cells and add one by one to a new cluster. 
For example, 
```
# Generate a new column called sub_cluster in the metadata
pbmc_small$sub_cluster <- as.character(Idents(pbmc_small))

# Change the information of cells containing sub-cluster information
pbmc_small$sub_cluster[Cells(pbmc_small.c1)] <- paste("c1",Idents(pbmc_small.c1))
pbmc_small$sub_cluster[Cells(pbmc_small.c2)] <- paste("c2",Idents(pbmc_small.c2))
pbmc_small$sub_cluster[Cells(pbmc_small.c3)] <- paste("c3",Idents(pbmc_small.c3))
```
