### ISSUE TITLE
Changing Files to Seurat Format

### ISSUE THREAD

**Issue by ayaanza29** [satijalab/seurat#5157]
This is the format I have right now of some scRNA sequencing data:

![Screenshot (2)](https://user-images.githubusercontent.com/91754746/135668644-3796b8d1-1899-48f5-9514-63f8aff122d9.png)

In order to utilize Seraut I need to convert this to a Seruat object by creating three files in the format show below, Matrix.mtx, barcodes.tsv, and genes.tsv or features.tsv. Is this correct? 

![Screenshot (6)](https://user-images.githubusercontent.com/91754746/135668653-b69d8bc4-d112-4234-a17d-9a71281fb118.png)

![Screenshot (7)](https://user-images.githubusercontent.com/91754746/135668699-b1b3c001-e53d-4328-9f44-2a3563e1ac4e.png)

![Screenshot (8)](https://user-images.githubusercontent.com/91754746/135668709-b310f2bf-c6a2-4b33-8251-f506f1ee39c1.png)

So far I have had no success in creating a seraut object, can anyone explain how to do this in a simple way, I am new to R. I would greatly appreciate any help, thanks!

**Comment by yuhanH** [comment]
hi,
If you don't have too many cells, you can still create seurat object by your format.  
You can load your data by read.csv or read.table into R, and then create a matrix only with gene counts. Next, you need to transpose the matrix to make sure that each row is a gene and each column is a cell. Lastly, make row name of the matrix be gene names and column name be cell names. 
You can use this processed matrix to create seurat object.
