### ISSUE TITLE
Geneplot visualilzation by cluster not by original identity

### ISSUE THREAD

**Issue by kysbbubbu** [satijalab/seurat#516]
Hello

I merged two datasets.
I use below script for visualization, and the result shows each cells grouped by clustering by t-SNE.
```R
merge <- AddModuleScore(object = merge, genes.list = proliferative.score, enrich.name = "proliferative.score")
merge <- AddModuleScore(object = merge, genes.list = invasive.score, enrich.name = "invasive.score")
GenePlot(object = merge, gene1 = "proliferative.score1", gene2 = "invasive.score1", used.scaled = TRUE, do.hover = TRUE)
```
However, i also want to visualize geneplot grouped by original identity, but `group.by = ....` script did not work, is there any solution for this? 

Best regards thank you

**Comment by satijalab** [comment]
Apologies, group.by should be the solution for this. If its not working, we'll fix in the next release.

In the meantime (suppose you want to group by batch), you can see GenePlot(SetAllIdent(object, "batch", ...) as an equivalent solution

**Comment by andrewwbutler** [comment]
This functionality is now available in Seurat v3 in `FeatureScatter` (formerly `GenePlot`).
