### ISSUE TITLE
Frequency of the gene expression in Seurat

### ISSUE THREAD

**Issue by yueli89** [satijalab/seurat#5164]
Hello,

Thank you for developing so nice software!

I can go through all the code from here: https://satijalab.org/seurat/archive/v3.0/visualization_vignette.html.

My question is: Is that possible that I can get the frequency of one gene in one cluster?

Thank you in advance for your great help!

Best Regards,

Yue
![屏幕快照 2021-10-05 10 07 51](https://user-images.githubusercontent.com/88724190/135949190-6ed939c1-e081-49e7-bda9-c117734088b9.png)

**Comment by timoast** [comment]
See the `VlnPlot()` function
