### ISSUE TITLE
Question on ScaleData

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#5167]
Hi,
I was wandering wheter `ScalaData` was performed on library normalized data or on logNormalized data. If it is the latter case, I find it unintuitive to standardize (scale and center) data that it in log scale. Could someone comment on this?
Thank you

**Comment by saketkc** [comment]
Scaling and centering are common operations before you apply any downstream dimensionality reduction methods (such as PCA). The goal here to center and scale the gene expression to give _equal_ weights to each gene in downstream analysis (which would otherwise be driven by highly expressed genes).

**Comment by kaizen89** [comment]
@saketkc sorry my question was not clear enough. I do understand the utility of scaling but I do no not know whether it is done on the library size normalized data before or after log transformation.
