### ISSUE TITLE
The "order" argument in DimPlot() does not work?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5169]
Hi, 

I aim to plot my clusters in a particular order to avoid the smaller clusters get buried by cells of larger cluster; however, the "order" parameter does not seem to work properly (the legend suggests cluster 21, then 17, then 16 ... was plotted instead)

Would you mind helping me identify potential issues here?

Thank you for your help. 

color23 is a vector of particular colors I want to use. 

```
DimPlot(seurat_object, label = F, cols = color23, group.by = NULL, order = c("22", "20", "12","18","0","1","2","3","9","10","14","19","13","4","5","6","7","8","11","15","16","17","21"))
```
<img width="107" alt="Screen Shot 2021-10-05 at 6 47 44 PM" src="https://user-images.githubusercontent.com/62179082/136075881-60ce4557-1754-4678-a513-0c0481cf44e8.png">

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.   As specified in the manual entry: `Provide either a full list of valid idents or a subset to be plotted last (on top)`.  So the final entry in the list will be plotted on top of the others.  I believe this is functioning as described.

Best.
Sam

**Comment by denvercal1234GitHub** [comment]
Ah I see. Thank you!

**Comment by AlbertoFabbri93** [comment]
I am not sure if I should open a new issue or using this one is okay.

I am having the same issue described above but I believe I am setting the parameters correctly, this is my code:

```r
# Print UMAP with final cell types
other_cells_dormant_proliferative_sct_plot <- DimPlot(
  object = breast_cancer_patients_other_dp_cells,
  group.by = "proliferative_dormant_cell_state",
  reduction = "sct_umap_patients",
  cols = palette_cell_types,
  raster = TRUE,
  raster.dpi = c(1500, 1000),
  pt.size = 3,
  order = c("Neither", "Proliferative", "Dormant"),
) +
  labs(title = "Dormant & proliferative cells") +
  theme_classic(base_size = 10) &
  NoAxes()
other_cells_dormant_proliferative_sct_plot
```

And this is a zoomed-in part of the plot I get:

<img width="1218" height="1164" alt="Image" src="https://github.com/user-attachments/assets/4093640e-a724-4c57-8b29-0485be62bb18" />

As you can see the dormant and proliferative cells are not in front of the other cells...
