### ISSUE TITLE
Best practices workflow

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#517]
Hello,

Amazing software which keeps getting better and better! For somebody coming from the bench though, the advanced features are a bit overwhelming at times. Especially changing even one parameter can result in wildly different outcomes making it difficult to decide which way to go. Different vignettes currently available may also be using different parameters for the similar type of analysis steps making it tough to understand which parameters should be always used and what others are needed for a certain kind of experimental design.

What would you think about creating a "best practices" document that outlines analysis steps and when to use them. Following points, in particular, would be very useful:

1- Cautions to take when analysis of heterogeneous cell populations (e.g. tumor-infiltrating immune cells)
2- When not to use percent.mito and nUMI cutoffs during pre-processing?
3- When and when not to regress out percent.mito and nUMI effects?
4- When and when not to regress out cell cycle genes
5- What is a recommended approach for clustering (how to decide which clustering is good)

Thank you very much not only for generating this software but also for always being helpful to comments here!

**Comment by satijalab** [comment]
The diversity of single cell data types (sparse, deep, full length), and systems (fully differentiated adult, actively differentiating), means that there is not a single list of best practices that we can enumerate.

Please also see https://satijalab.org/scgd/ for additional resources beyond our vignettes on the website, and documentation in the software package.
