### ISSUE TITLE
Pre-processing CITE-seq (ADT) data

### ISSUE THREAD

**Issue by tmms1** [satijalab/seurat#5175]
Hello

Thank you for developing seurat and providing useful workflows that are easy to follow. 

I want to use seurat to analyze single cell RNA-seq data with feature barcoding (10X). I think my starting point should be the vignette "Multimodal analysis". While reading that vignette, I was wondering if the ADT data should be preprocessed like the gene expression data. If so, could you offer some guidelines? 

Thanks in advance.

--
With kind regards
Tim

**Comment by tmms1** [comment]
Hi

Thank you very much for the quick reply. 

The vignette is clear, but it is recommended to preprocess the data? For example, should I remove cells with very low expression of ADT.

--
With kind regards
Tim

**Comment by oshiomah1** [comment]
Following up with Tim's question are there recommneded thresholds for ADT data filtering? Is something like median adjusted filtering recommended?
