### ISSUE TITLE
No cell names (colnames) names present in the input matrix

### ISSUE THREAD

**Issue by chenx9** [satijalab/seurat#5184]
Hello, I have downloaded the data file "dge.txt.gz", the matrix is opened as follows.When I read it into R as a matrix without cell and gene names, I wondered how I could extract the cell and gene names from it and then create the Seurat object smoothly. Or how do I read it correctly？

%%MatrixMarket matrix coordinate integer general

%%GENES | 0610005C13Rik | 0610007P14Rik | 0610009B22Rik | 0610009E02Rik | 0610009L18Rik...
%%GENES | 4932431P20Rik | 4932435O22Rik | 4932438A13Rik | 4932438H23Rik | 4932441J04Rik...
...
%%CELL_BARCODES | P60SNRep1P1_GCGCGACCAACT | P60SNRep1P1_CGTCCTACCGCT | P60SNRep1P1_CGCACGTCTTCC | 
%%CELL_BARCODES | P60SNRep1P1_TCTATATTTGGT | P60SNRep1P1_TTTAGCGGAATT | P60SNRep1P1_GATCAAGAGGAA |

**Comment by samuel-marsh** [comment]
Hi,

not member of dev team but hopefully can be helpful.  What is the output of the following:
```
library(data.table)

raw_dge <- fread(file = FILE_PATH, header = T, stringsAsFactors = F, data.table = F)

head(raw_dge)[1:5]
```

Best,
Sam
