### ISSUE TITLE
How do I check if the RPCA integration was successful?

### ISSUE THREAD

**Issue by smk5g5** [satijalab/seurat#5185]
I used rpca integration and then did clustering. After doing clustering I used 'RNA assay' for calling DEG's once I called the DEG's I visualized them on the dotplot using the integrated assay on the sample metadata and It seems that the DEG's of the clusters are actually separating by technique. sch18 to sch22 (which are a different technique to the rest of the samples) are separating by technique from the rest? Does that mean that the rpca integration was not successful? What can be a robust way to make sure of it?

Thanks!
![sch_subclus_dotplot_top15DEGs bySample_OCT12](https://user-images.githubusercontent.com/6811915/137027783-2d91b1a3-fa01-4f34-bbc4-4a6372729b8d.jpg)

**Comment by timoast** [comment]
To assess the performance of integration we typically look at two metrics described in the [integration paper](https://doi.org/10.1016/j.cell.2019.05.031): dataset mixing and local structure preservation. See the paper for full discussion. More practically, you might look at a 2-dimensional visualization and assess whether equivalent cell types across batches are intermixed in the low-dimension space, and if clusters contain a mixture of cells from different batches.
