### ISSUE TITLE
gene co-expression analysis single cell

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#519]
Dear All,
I would like now to go deeper in the analysis. I extracted only cells belonging to a cluster of interest, highly expressing a transcription factor of interest.
Now I would like to check in all my cells (n=700) which are the top genes with an high positive correlation value with respect to my gene of interest,

up to now I tried
```R
matrix<-subset0_STIM@data
matrix_mod<-as.matrix(matrix)
gene<-as.numeric(matrix_mod["gene of interest",])
correlations<-apply(matrix_mod,1,function(x){cor(gene,x)})
```

and it seems working,but other suggestions are highly appreciated,
Best

**Comment by satijalab** [comment]
This is a correct solution for identifying highly correlated genes. If you have a module of genes (as we use, for example, with CellCycleScoring), you can use AddModuleScore

**Comment by CroixJeremy2** [comment]
Hello,
I have the same question as @mlwarrior as the results from the code above are not the same between data and scale.data. Plus, is this code OK for Seurat v5?
```
matrix<-subset0_STIM[["RNA"]]$data
matrix_mod<-as.matrix(matrix)
gene<-as.numeric(matrix_mod["gene_of_interest",])
correlations<-apply(matrix_mod,1,function(x){cor(gene,x)})
```
Thanks in advance for your response,
