### ISSUE TITLE
Output description of FindMarkers: avg_logFC

### ISSUE THREAD

**Issue by annahyan** [satijalab/seurat#5190]
Hi, 
Thanks for developing the Seurat toolbox and for maintaining it! 
I've noticed, that the Value section of FindMarkers help page says:

* avg_logFC: log fold-chage of the average expression between the two groups. Positive values indicate that the gene is more highly expressed in the first group

However, I checked the expressions of features in the groups with the RidgePlot and it seems that positive values indicate that the gene is more highly expressed in the second group. Please let me know if I'm doing something wrong, otherwise changing the docs would be helpful.

Thanks,
Anna

**Comment by cswoboda** [comment]
You should post the plots and the code you used for clarity, but if you're saying that you the ridge plot is further to the right in group 2 compared to group 1, and you are sure ident.1 was equal to group 1 and ident.2 was equal to group 2 and the logfc value is positive, it's technically possible a group would have a higher overall average expression across all cells in group 1 but you get a peak in group 2 I guess. If you can send the code and the plots I could better assist, but I'm sure the documentation is correct
