### ISSUE TITLE
Error Converting to loom file

### ISSUE THREAD

**Issue by AshoorH** [satijalab/seurat#520]
Hi, 

I am trying to convert Seurat object to loom file, when I run the provided example I got the following error: 

```R
> library(loomR)
Loading required package: R6
Loading required package: hdf5r
Loading required package: iterators
Loading required package: itertools
> library(Seurat)
Loading required package: ggplot2
Loading required package: cowplot

Attaching package: ‘cowplot’

The following object is masked from ‘package:ggplot2’:

    ggsave

Loading required package: Matrix
> data('pbmc_small')
> lfile = Convert(from = pbmc_small, to = 'loom', filename = 'small.loom')
Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns 
This is to maintain compatibility with other loom tools 
Error in dataset_create_pl$set_chunk(chunk_dims) : 
  In RToH5_INTEGER can't convert type of object passed

```
May you advise on this issue? 

Thanks
Haitham

**Comment by mojaveazure** [comment]
This should be fixed in the development version of loomR. Install it with the following:

```R
devtools::install_github(repo = 'mojaveazure/loomR', rep = 'develop')
```

**Comment by araksm** [comment]
Hi,

I'm trying to convert my Seurat version 1.4 object to loom format using loom R.
So I update my object by 
> updatedObject <- UpdateSeuratObject (seurat1.4object).

Then I'm converting it to loom by
> lfile = Convert(from = updatedObject, to = 'loom', filename = 'output.loom')

>Transposing input data: loom file will show input columns (cells) as rows and input rows (genes) as columns 
>This is to maintain compatibility with other loom tools 
>  |==============================================| 100%
>Error in new.loom$add.layer(layer = layers) : 
>  All layers must have 1811 rows for cells and 49568 columns for genes

I guess it is caused since my updatedObject@raw.data and updatedObject@scale.data are of different dimensions (the number of rows (genes) is different). So I was wondering are raw.data and scale.data supposed to have the same size?  If not, how could I fix that? Should I simply remove additional rows from the updatedObject@raw.data?

Thank you,
Araks

**Comment by mojaveazure** [comment]
Hi Arkas, please try updating your version of Seurat by installing the loom branch
```R
devtools::install_github(repo = 'satijalab/seurat', ref = 'loom')
```

**Comment by araksm** [comment]
Thank you Paul!  It works now without any errors and generates the loom file.
Next, I try to review it in the loom-viewer and am getting another error:

>::1 - - [2018-06-27 17:25:43] "GET /loom HTTP/1.1" 200 767 0.058537
>/Users/u0114327/anaconda/lib/python3.6/site-packages/numpy/lib/arraysetops.py:200: RuntimeWarning: invalid value encountered in not_equal
>  flag = np.concatenate(([True], aux[1:] != aux[:-1]))
>/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_utils.py:93: RuntimeWarning: invalid value encountered in isnan
>  vals[np.isnan(vals)] = 0
>[2018-06-27 17:25:49,372] ERROR in app: Exception on /loom/project/output.loom [GET]
>Traceback (most recent call last):
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_utils.py", line 122, in np_to_list
>    if safe_conversion[i]:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>    raise value
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_server.py", line 54, in cache_func
>    response = make_response(view(*args, **kwargs))
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_server.py", line 223, in send_fileinfo
>    attributes = loom_server.datasets.JSON_attributes(project, filename)
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_datasets.py", line 626, in JSON_attributes
>    attributes, last_mod = expander.attributes(False)
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_expand.py", line 227, in attributes
>    rowAttrs = {key: metadata_array(arr) for (key, arr) in ds.ra.items()}
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_expand.py", line 227, in <dictcomp>
>    rowAttrs = {key: metadata_array(arr) for (key, arr) in ds.ra.items()}
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_utils.py", line 147, in metadata_array
>    _data, _data_type = np_to_list(array)
>  File "/Users/u0114327/anaconda/lib/python3.6/site-packages/loom_viewer/loom_utils.py", line 127, in np_to_list
>    return (vals.tolist(), "string")
>AttributeError: 'list' object has no attribute 'tolist'
> ::1 - - [2018-06-27 17:25:49] "GET /loom/Atros3/output.loom HTTP/1.1" 500 412 0.419597

I'm using 
Python 3.6.0 :: Anaconda 4.3.1 (x86_64)
loom v0.32.2

Is there a compatibility issue?

Thank you,
Araks

**Comment by mojaveazure** [comment]
Hi Arkas,

I'm not sure, I haven't use the loom viewer before. I would recommend asking the Linnarsson lab about it to see if they can diagnose why you're getting this error, then we can look at if it's something on their end or ours.
