### ISSUE TITLE
General question on normalization

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#521]
Hello Seurat Team,

I have been using the default LogNormalization in Seurat for my datasets so far, although I have had other groups/collaborators with whom we share methodologies and insights trying out other normalization methods, such as scater, SCNorm, etc.  I would like to stick to what Seurat uses, and only change whenever Seurat improves/changes its default normalization.  This is mainly for convenience of my workflow, and also because I am deep into advanced analysis at this point and closer to publication stage, and do not wish to redo things from the beginning at this stage for my current datasets.

So, my question is:  what is your team's current recommendation as far as normalization is concerned?  Are you soon going to deviate from the default global library-size normalization to something more sophisticated?  Is that actually warranted?

I have a lot of pressure from my biologists and collaborators to change, but I don't know yet whether I should.  So, any insights, and justifications to stick to Seurat's current defaults would be great!

I would also like to mention that, I DO regress out cell-cycle, nUMI, and %Mito effects after normalization.

Thanks a tonne, for any inputs.

**Comment by satijalab** [comment]
We suggest you check out Christoph's recently created sctransform package (https://github.com/ChristophH/sctransform), which implements an approach to preprocessing based on a regularized negative binomial distribution. This is not fully implemented in Seurat yet, but is easy to try, and we'd be happy to hear your feedback on whether it improves your downstream biological analysis.
