### ISSUE TITLE
FindtransferAnchors and MapQuery : Harmony reduction for reference doesnt work

### ISSUE THREAD

**Issue by NK-HD** [satijalab/seurat#5222]
Dear Seurat Team and Community,

we are currently trying to map new datasets onto a preexisting seurat object. To generate this reference object we used harmony.
No we were following your vignette: https://satijalab.org/seurat/articles/integration_mapping.html to map/project our new datasets on the reference using:

New.anchors <- FindTransferAnchors(reference = oldrefernce , query = new_seu_obj , reference.reduction = "harmony")

however we get the following error:
_Projecting cell embeddings
Finding neighborhoods
Finding anchors
	Found 25 anchors
Filtering anchors
	Retained 0 anchors_

so that we cant continue with mapquery

Both objects are of similar size (~ 20k cells)

before we mapped both (reference and new dataset) succesfully to your provided BM-reference (https://satijalab.org/seurat/articles/multimodal_reference_mapping.html). 

Would you maybe be able to assist us with troubleshooting this? Did we use the harmony reduction wrong or is there no way to use it in this setting?

Thank you very much in advance!
Appreciate your help!!!
Best,
Niklas

**Comment by yuhanH** [comment]
HI, 
Here is a similar issue: https://github.com/satijalab/seurat/issues/5122
Because the feature loadings in harmony is not an orthogonal matrix, projection query cells to the reference harmony space doesn't work under our current settings.
