### ISSUE TITLE
How to pass graph in BuildClusterTree function?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#5223]
Hi,

In Seurat 4.0, the BuildClusterTree function builds tree based on graph connectivity between clusters if the argument "graph" is provided.  But what should I pass to the "graph"? Could you give me some examples? Where I can find it?

Thanks!

**Comment by yuhanH** [comment]
You can just add the graph name to the `graph` parameter in `BuildClusterTree`.
One example:
```
data("pbmc_small")
pbmc_small
pbmc_small <- NormalizeData(pbmc_small) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
pbmc_small <- FindNeighbors(pbmc_small, dims = 1:30)
Graphs(pbmc_small)
 
pbmc_small <- BuildClusterTree(object = pbmc_small, graph = "RNA_snn" )
Tool(object = pbmc_small, slot = 'BuildClusterTree')
```
