### ISSUE TITLE
How to access theta_modality(i,j) values directly for all cells?

### ISSUE THREAD

**Issue by akshayMpatel** [satijalab/seurat#5225]
Hello @yuhanH, 

If I use option 1, won't it still compute theta values between cell i average all other cells, and not between cell i and cell j?  (As in the first attached equation?). Also if the cells number is large, is there a way to parallelize (eg with futurizing)?

To be clear I want to compute theta_rna(r_i,r_j) and theta_protein(p_i,p_j) in the second attached equation.  

Images are from the paper. 

For option 2. since there is no documentation within the function `Seurat:::FindModalityWeights` please advise on exactly how I can extract computation of theta (as previously described) between any two cells in a given modality.  

<img width="481" alt="Bildschirmfoto 2021-06-08 um 15 08 37" src="https://user-images.githubusercontent.com/837627/138638460-8998da61-be6c-4add-961d-893e39e557ad.png">

<img width="587" alt="Bildschirmfoto 2021-06-08 um 16 13 53" src="https://user-images.githubusercontent.com/837627/138638461-23d3efc1-965b-45a8-aac5-c32c5ef2f32e.png">

Many thanks

_Originally posted by @akshayMpatel in https://github.com/satijalab/seurat/issues/4698#issuecomment-950537908_

**Comment by yuhanH** [comment]
Hi, 
When you set ` return.intermediate` in `FindMultiModalNeighbors` to TRUE, the modality weights related parameters will be stored in `Misc(object = bm, slot = "modality.weight" )`. 

```
library(Seurat)
library(SeuratData)
bm <- LoadData(ds = "bmcite")

DefaultAssay(bm) <- 'RNA'
bm <- NormalizeData(bm) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
DefaultAssay(bm) <- 'ADT'
VariableFeatures(bm) <- rownames(bm[["ADT"]])
bm <- NormalizeData(bm, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')

bm <- FindMultiModalNeighbors(
  bm, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:18),  
  return.intermediate = TRUE
)


modality.weight <- Misc(object = bm, slot = "modality.weight" )
weighted.nn <- Seurat::MultiModalNN(
  object = bm,
  k.nn = 20,
  modality.weight = modality.weight,
  knn.range = 200,
  verbose = TRUE
)
```

Then if you want to use this modality.weight to calculate the multimodal distance of all cells, you can have a look at `Seurat::MultiModalNN`.  In this function, we first find 200 KNNs for RNA and protein separately and then calculate the multimodal distance within those one-modality neighbors. 
Here are the main steps to calculate weighted multimodal distance. 
```
nn_weighted_dist <- lapply(
    X = 1:reduction.num,
    FUN = function(r) {
      lapply(
        X = 1:query.cell.num,
        FUN = function(x) {
          exp(-1*(nn_dist[[r]][[x]] / sigma.list[[r]][x] ) ** kernel.power) * modality.weight.value[[r]][x]
        }
      )
    }
  )
  nn_weighted_dist <- sapply(
    X = 1:query.cell.num,
    FUN =  function(x) {
      Reduce(
        f = "+",
        x = lapply(
          X = 1:reduction.num,
          FUN = function(r) nn_weighted_dist[[r]][[x]]
        )
      )
```
