### ISSUE TITLE
features.to.integrate drop features

### ISSUE THREAD

**Issue by pavsol** [satijalab/seurat#5226]
Hi,

I am using the SCtranform integration pipeline for six datasets. I need to preserve 1700 features that are not in the output of SelectIntegrationFeatures(), Thus, I use features.to.integrate with IntegrateData function, however, only 660 of these features appear in the output. I also tried to use only the features that are present in all to-be-integrated objects which resulted in ~1400 features but I got the same output (660 features again). Another thing I tried is to calculate Pearson residuals for all genes in all objects with GetResiduals(). No change in the output. Do you have any idea what may be wrong?

Code:

all_features <- SelectIntegrationFeatures(all_list, nfeatures = 3000)
all_list <- PrepSCTIntegration(object.list = all_list, anchor.features = all_features, assay = "SCT")
all_anchors <- FindIntegrationAnchors(object.list = all_list, normalization.method = "SCT", anchor.features = all_features)
all_integrated <- IntegrateData(all_anchors, new.assay.name = "integrated", normalization.method = "SCT", features.to.integrate = keep.features)

keep.features is a vector of gene IDs of which ~300 are present in all_features
Seurat 4.0.5

Thank you for any help,
Pavel

**Comment by pavsol** [comment]
Hi,

you have the point. Only the features that are in all individual objects remain in the integrated object. I was confused because when I tested this, I used a union of the features in individual objects but it actually keeps the intersection of them.

Thus, now we know which features are dropped. My following question would be whether there is a way how to preserve the features that are in some of the individual objects (but not all) instead of dropping them? The idea is to simply have zeros for the samples that do not contain respective features.

Thank you

**Comment by mhkowalski** [comment]
I would not recommend doing this, because this will introduce a batch effect in any downstream analyses if you have a gene with non-zero counts in some datasets but only zero counts in other datasets. You could always check the original, unintegrated dataset if there is a particular feature you are interested in.
