### ISSUE TITLE
FindMarkers() gets stuck when logfc.threshold and min.pct are set to less stringent values

### ISSUE THREAD

**Issue by l-cli** [satijalab/seurat#5227]
Hi,

I am currently running the FindMarkers() function on a Seurat object that has 36601 genes and ~18000 cells with the following setup:
```
Idents(t) <- "time.ident"
zero_one <- FindMarkers(t, 
                          ident.1 = "1hr", 
                          logfc.threshold = 0.2, 
                          min.pct = 0,
                          ident.2 = "0hr", 
                          test.use = "LR",
                          verbose = TRUE)
```

Our goal is to compare the cells that are in the "1hr" group with the "0hr" group. The problem is when we tried to run the codes above, the program was stuck and did not produce any output after waiting for more than 48hrs. We are using Future to generate multiple threads, and the codes above were run with 6 workers simultaneously. Moreover, when we tried a logfc.threshold of 0.25 and default min.pct, we were able to see some output, but we want to include all the genes instead of just a subset. We would appreciate any suggestions on how to solve this issue, thank you!

**Comment by mhkowalski** [comment]
Hi, ```FindMarkers``` should support parallel processing, as shown [here](https://satijalab.org/seurat/archive/v3.0/future_vignette.html). Can you provide the code you are using to run future?

Apologies if you did this already but it's not quite clear to me.  Did you try running with min.pct = 0.1 with future, in which case the run time should be less than 15 minutes?

**Comment by l-cli** [comment]
Hi! Here are the codes we used to run future:
```
# set threads and parallelization
plan("multisession", workers = 6)
options(expressions = 20000)
options(future.globals.maxSize = 21474836480)
```

We did run min.pct = 0.1 without running future, and it took us about a day to finish running.

**Comment by jzhou88** [comment]
Hi Seurat people,

The same thing happens here. I have a FindMarkers job that took about 6 hours for Seurat v3 with 16 cores to complete. Now, using Seurat v4 with 16 cores, the same job takes forever to finish. If possible, would you please check this issue? Thanks.

Best,
J

**Comment by tilofrei** [comment]
Hey, maybe checkout [presto](https://github.com/immunogenomics/presto): It significantly speeds up DEG calculation with the Wilcox test for me and [is integrated through Seurat wrappers](https://github.com/satijalab/seurat-wrappers/blob/master/docs/presto.md).

**Comment by saketkc** [comment]
Hi @tilofrei You are using "LR" based test which is expected to be slow (particularly with low thresholds such as 0.2 that you have). You could switch to wilcoxon test (which is also the default).

**Comment by flde** [comment]
I have the same problems on 10.000 x 65.000 genes x cells matrix running with 200G and 42 CPU. The job dies with out of memory handler while using the wilcoxon test ptc.1=0 (Seurat v4). Maybe I am ignorant but is this expected?
