### ISSUE TITLE
Using RenameCells with sparse matrices

### ISSUE THREAD

**Issue by lazappi** [satijalab/seurat#523]
Opening this as an issue after @nbahlis commented on #510 

Hello,
when using RenameCells I get the error "invalid dimnames given for "dgCMatrix" object "
Does RenameCells work with sparse matrices?

thanks

**Comment by lazappi** [comment]
Hi @nbahlis

Are you able to provide a reproducible example that causes the error?

I tried the following code using a sparse matrix and didn't have any problems. 

```{r}
library(Seurat)
data("pbmc_small")
sparse_data <- as(pbmc_small@raw.data, "dgCMatrix")
pbmc_sparse <- CreateSeuratObject(sparse_data)
RenameCells(pbmc_sparse, add.cell.id = "TEST")
```

The Seurat developers might have more of an idea what the problem could be here.

**Comment by nbahlis** [comment]
thank you Luke, 
Mia Culpa. There was an error in my matrix. Code is fine
