### ISSUE TITLE
AverageExpression to compare expression of two genes

### ISSUE THREAD

**Issue by n1tian** [satijalab/seurat#5237]
Hi all,

I'm trying to find out which one of the two genes of my interest is expressed at higher level in each cluster of my samples. I calculated the average expression of the two genes in each cluster using AverageExpression(), slot = "data", and compared these values. Is this a valid method?

Thank you!

**Comment by mhkowalski** [comment]
Yes, although you may also want to look at some visualizations like `VlnPlot` in order to see the distribution of values in addition to the mean.
