### ISSUE TITLE
SpatialDimPlot shape 16

### ISSUE THREAD

**Issue by Dimitri-Sid** [satijalab/seurat#5239]
Could it be possible to replace the current shape of the spots to shape 16 so that there is no stroke whatsoever?

**Comment by andrewwbutler** [comment]
Hi,

You can pass `stroke = 0` to `SpatialDimPlot` to remove the stroke.

**Comment by Dimitri-Sid** [comment]
Hi, 

As far as I can tell, that does not completely remove the black border, stroke=0 is just the smallest possible setting of border width.  Please see image 1 showing Seurat SpatialDimPlot output w/ stroke parameter set to 0, versus another tool's output to appreciate the difference. The black borders around the circles make it really difficult to plot multiple panels together. 

Seurat, stroke=0
![image](https://user-images.githubusercontent.com/22621258/139535352-3c86a576-4731-4ff6-8efd-5b97473b286d.png)

No border (scanpy): 
![image](https://user-images.githubusercontent.com/22621258/139535495-4b8ae00c-4705-49e9-80be-fab2af31dcb2.png)

**Comment by andrewwbutler** [comment]
Ahh, I see. The border still shows up if you're saving to a vector graphic output (e.g. pdf) with `stroke = 0`. It seems setting `stroke = NA` removes it for all output types though. Could you give that a shot?

**Comment by Dimitri-Sid** [comment]
this worked great - thanks so much!

> Ahh, I see. The border still shows up if you're saving to a vector graphic output (e.g. pdf) with `stroke = 0`. It seems setting `stroke = NA` removes it for all output types though. Could you give that a shot?
