### ISSUE TITLE
Standard AUC classifier

### ISSUE THREAD

**Issue by cartal** [satijalab/seurat#524]
Hi, 

Can you please share how does the Standard AUC classifier works? 
It has been given me nice results but I am not really sure what its inner works are in Seurat. 

This is to make my method sections more transparent! 

Thanks in advance.

**Comment by satijalab** [comment]
This attempts to perform classification on the basis of a single gene, using AUC as a metric of classification. Some basic information at https://en.wikipedia.org/wiki/Receiver_operating_characteristic
