### ISSUE TITLE
Cannot use images from object converted from .h5ad to .h5seurat [Spatial Transcriptomics]

### ISSUE THREAD

**Issue by akstks** [satijalab/seurat#5242]
Hello dear Seurat developers,

I have been using Seurat for a while now analyzing scRNA-seq data, and wanted to try out some spatial analysis to familiarize myself with that topic of transcriptomics. 

I found this publicly available dataset that has 4 samples (A1, B1, C1, D1) that have been processed with Python pipelines:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE171351

Sadly, they do not provide the raw data to create a Seurat object from scratch, so I converted the .h5ad provided object to an .h5Seurat object as instructed through the Seurat Disk package. 

Loading the object with LoadH5Seurat produced a Large Seurat object
`spatial <- LoadH5Seurat(GSE171351_combined_visium.h5seurat)`

 however: 
`spatial@images` is empty and what appears to be the image embeddings are found in
`spatial@reductions[["spatial"]]@misc`

Here is a picture of the RStudio view panel to get a better look:

![misc](https://user-images.githubusercontent.com/80491255/139253837-37862ff5-a765-4cd9-86b1-aeea1a49a426.png)

Since these appear to be already analyzed data, I wanted to just look at SpatialFeaturePlots for various genes, but I cannot seem to figure out how to do that, without the images being in the "correct" place, or of class "VisiumV1". 

Do you have any ideas on how to proceed? I am really new to the spatial aspect so any help would be much appreciated!

**Comment by hbzxm** [comment]
@akstks Did you find the solution?

**Comment by cellphone12** [comment]
It seems to record the location of each cell in meta.data.

**Comment by cellphone12** [comment]
> It seems to record the location of each cell in meta.data.

**Comment by rsatija** [comment]
Apologies that we cannot support this. The complexity of spatial data types is too great that we cannot support generic conversion of spatial h5ad to seurat files. You can recreate a Seurat object from the spatial transcriptomic datasets in order to utilize the Seurat-spatial toolkit

**Comment by Carissimo** [comment]
Did you resolve this issue? I have the same problem with stereoseq spatial data

**Comment by JiahaoWongg** [comment]
I met error when read `h5seurat` file.

```
Convert("GSE171351_combined_visium.h5ad", "h5seurat", overwrite = TRUE, assay = "RNA")
seurat_obj <- LoadH5Seurat("GSE171351_combined_visium.h5seurat")

Validating h5Seurat file
Initializing RNA with data
Adding counts for RNA
Adding feature-level metadata for RNA
Adding reduction spatial
Adding cell embeddings for spatial
Adding miscellaneous information for spatial
Error in if (!x[[i]]$dims) { : the condition has length > 1
``` 
Why did I encounter this error？thanks.
