### ISSUE TITLE
FeaturePlot() with split.by does not seem to have the same scaling for all subplots

### ISSUE THREAD

**Issue by abayegan** [satijalab/seurat#5243]
```r
# insert reproducible example here
```

**Comment by olneykimberly** [comment]
so what is the solution?

**Comment by samuel-marsh** [comment]
Hi @olneykimberly for now (or for future) you can use `FeaturePlot_scCustom` from scCustomize package.  See this vignette: https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html for more info.  When using `split.by` it will preserve scale across plots.

Best,
Sam

**Comment by samuel-marsh** [comment]
For future reference this issue was also fixed within Seurat with 4.1 release.

https://github.com/satijalab/seurat/blob/master/NEWS.md#seurat-410-2022-01-14

**Comment by ShanshuoZHU** [comment]
> 



> 



> Hi @olneykimberly for now (or for future) you can use `FeaturePlot_scCustom` from scCustomize package. See this vignette: https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html for more info. When using `split.by` it will preserve scale across plots.
> 
> Best, Sam

Hi @samuel-marsh , now I am trying to use FeaturePlot_scCustom, When using`split.by` and only have one feature , I find that when I using if I set 'na_cutoff = NA', the scale is not kept the same across plots for some features and all the scale legends will be displayed. but if donot set 'na_cutoff = NA', the scale will be preserved and only 1 scale legend displayed. why the na_cutoff setting affects the scale and how can I avoid that? Thanks a lot.

![Picture3](https://github.com/satijalab/seurat/assets/124776861/0f92bbe4-cd01-4198-99b1-6bc29c4b6b10)
