### ISSUE TITLE
How to compute distance between any two cells in one modality

### ISSUE THREAD

**Issue by akshayMpatel** [satijalab/seurat#5246]
Hi, 
When you set ` return.intermediate` in `FindMultiModalNeighbors` to TRUE, the modality weights related parameters will be stored in `Misc(object = bm, slot = "modality.weight" )`. 

```
library(Seurat)
library(SeuratData)
bm <- LoadData(ds = "bmcite")

DefaultAssay(bm) <- 'RNA'
bm <- NormalizeData(bm) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
DefaultAssay(bm) <- 'ADT'
VariableFeatures(bm) <- rownames(bm[["ADT"]])
bm <- NormalizeData(bm, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')

bm <- FindMultiModalNeighbors(
  bm, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:18),  
  return.intermediate = TRUE
)


modality.weight <- Misc(object = bm, slot = "modality.weight" )
weighted.nn <- Seurat::MultiModalNN(
  object = bm,
  k.nn = 20,
  modality.weight = modality.weight,
  knn.range = 200,
  verbose = TRUE
)
```

Then if you want to use this modality.weight to calculate the multimodal distance of all cells, you can have a look at `Seurat::MultiModalNN`.  In this function, we first find 200 KNNs for RNA and protein separately and then calculate the multimodal distance within those one-modality neighbors. 
Here are the main steps to calculate weighted multimodal distance. 
```
nn_weighted_dist <- lapply(
    X = 1:reduction.num,
    FUN = function(r) {
      lapply(
        X = 1:query.cell.num,
        FUN = function(x) {
          exp(-1*(nn_dist[[r]][[x]] / sigma.list[[r]][x] ) ** kernel.power) * modality.weight.value[[r]][x]
        }
      )
    }
  )
  nn_weighted_dist <- sapply(
    X = 1:query.cell.num,
    FUN =  function(x) {
      Reduce(
        f = "+",
        x = lapply(
          X = 1:reduction.num,
          FUN = function(r) nn_weighted_dist[[r]][[x]]
        )
      )
```

_Originally posted by @yuhanH in https://github.com/satijalab/seurat/issues/5225#issuecomment-954954586_

**Comment by akshayMpatel** [comment]
Hi @yuhanH 

This does not answer the question. 

1) Let me clarify.  
I do not want the multimodal distance value. I want the unimodal distance because I want to selectively turn modalities on and off in the multimodal distance computation. If I only have the final multimodal distance, I cannot go back and remove a modality from the calculation.  

So I want the distance between any two cells in one modality. For example, θ_rna(r_i, r_j) in the following equation from the paper...
![image](https://user-images.githubusercontent.com/837627/139507416-e789e6c0-2cc0-49fb-a862-9b0974f4f937.png)

I tried to compute this manually, using components of the equation from the Seurat structure, for example, sigma, the knn_1 from FindNeighbors(), etc, but my values were exploding for some reason. So I wonder about a way to extract/compute these unimodal distances directly from the Seurat object. 

2) Maybe the problem is that you are using a different equation to compute distances than I am (from the paper). Are they the same?

You compute it this way. 

`exp(-1*(nn_dist[[r]][[x]] / sigma.list[[r]][x] ) ** kernel.power) * modality.weight.value[[r]][x] `
?

I am using following from the paper. 

![image](https://user-images.githubusercontent.com/837627/139509992-bf9ff911-ab5f-4cbb-95c2-4ba7d19154ed.png)

Yours looks different.  Where is the subtraction of the distance(cell, knn_1) from sigma in the denominator?  Why is it raised to a kernel power?  

3) Let's just solve this. If I gave you RNA pca's for cells r_i and r_j , please provide code to compute the distance theta between those cells in RNA space.

4) You say distance.  Isn't this a similarity?  That is, the exp(-1*...) shrinks as the d() increases.

Please leave this issue open until it is resolved. It seems I have to repeat myself when creating a new issue, and this is about the 5th issue for the same original problem. 

Many thanks.

**Comment by yuhanH** [comment]
Dear @akshayMpatel 
If you feel the issue is not resolved, you can always re-open the issue and don't need to create new issues. 
I will use the bmcite as the example to show you how to calculate theta_RNA, theta_ADT and theta_weighted and weighted distance in the `weighted.nn`.
First, cluster RNA and ADT individually and run `FindMultiModalNeighbors` with `return.intermediate = TRUE`
```
data("bmcite")
bm <- LoadData(ds = "bmcite")
DefaultAssay(bm) <- 'RNA'
bm <- NormalizeData(bm) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()

DefaultAssay(bm) <- 'ADT'
VariableFeatures(bm) <- rownames(bm[["ADT"]])
bm <- NormalizeData(bm, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')
bm <- FindMultiModalNeighbors(
  bm, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:18),  return.intermediate = TRUE
)
```

Check the first neighbor for cell1 and its distance. 
```
bm[['weighted.nn']]@nn.idx[1, 1]
bm[['weighted.nn']]@nn.dist[1, 1]
```
Then you can see the first neighbor for cell1 is cell21408 and their multimodal distance is 0.1458.
You can use the below scripts to calculate this multimodal distance between cell1 (i) and cell21408 (j).
```
i = 1
j = 21408
# nearest distance, sigma and weights  of cell1 (i) in terms of RNA PCA and ADT PCA
pca.nearest.dist <- bm@misc$modality.weight@params$nearest.dist$pca
pca.sigma <- bm@misc$modality.weight@params$sigma.list$pca
pca.weights <- bm@misc$modality.weight@modality.weight.list$pca

apca.nearest.dist <- bm@misc$modality.weight@params$nearest.dist$apca
apca.sigma <- bm@misc$modality.weight@params$sigma.list$apca
apca.weights <- bm@misc$modality.weight@modality.weight.list$apca

# l2 norm pca and apca embeddings
pca.emb <- L2Norm(bm[['pca']]@cell.embeddings[,1:30])
apca.emb <- L2Norm(bm[['apca']]@cell.embeddings[,1:18])

# theta RNA, theta adt
# when we stored the sigma, the nearest neighbor's distance was already subtracted.
rna_similarity <- exp(-1*ReLu(sqrt(sum((pca.emb[i,] - pca.emb[j,])**2)) - pca.nearest.dist[i]) / pca.sigma[i])
adt_similarity <- exp(-1*ReLu(sqrt(sum((apca.emb[i,] - apca.emb[j,])**2)) - apca.nearest.dist[i]) / apca.sigma[i])

# theta weighted
multimodal_similarity <- rna_similarity*pca.weights[i] + adt_similarity*apca.weights[i]
# multimodal distance
multimodal_dist <- sqrt(x = MinMax(data = (1 - multimodal_similarity) / 2, min = 0, max = 1))
```
You can find that this multimodal_dist is equal to 0.1458
I hope this time your issue can be solved.

**Comment by akshayMpatel** [comment]
Dear @yuhanH 
Oh my apologies, I couldn't find a way to reopen an issue so I assumed it wasn't possible. How can I do that? 

I cannot run the above code, because it cannot find L2Norm function, despite installing STvEA and including it as a library. There is some cosine normalizing in this L2 Norm implementation that I am not sure how to do myself. How to solve this issue? 

Many thanks,
Akshay

**Comment by yuhanH** [comment]
Hi, 
For the multimodal_dist, we followed the correlation distance metric used in [rdist](https://www.rdocumentation.org/packages/rdist/versions/0.0.5/topics/rdist) package. 

The above scripts used many internal functions. You can git clone seurat locally and then use `devtools::load_all("~/seurat")` to load all seurat functions.

**Comment by akshayMpatel** [comment]
Hi @yuhanH 

When I run 
```
...
DefaultAssay(bm) <- 'ADT'
VariableFeatures(bm) <- rownames(bm[["ADT"]])
bm <- NormalizeData(bm, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')
...
```

I get 
```
...
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
PC_ 1 
Positive:  CD3, CD28, CD27, CD127-IL7Ra, CD278-ICOS, CD4, CD8a, CD161, CD25, CD45RO 
...
PC_ 5 
Positive:  CD4, CD38, CD123, CD16, CD34, CD45RA, CD56, CD278-ICOS, CD28, CD197-CCR7 
	   CD27, CD3 
Negative:  CD45RO, CD8a, CD69, CD161, CD79b, CD19, CD25, CD57, CD14, CD11a 
	   CD127-IL7Ra, HLA.DR 
Warning messages:
1: Requested number is larger than the number of available items (25). Setting to 25. 
2: Requested number is larger than the number of available items (25). Setting to 25. 
3: Requested number is larger than the number of available items (25). Setting to 25. 
4: Requested number is larger than the number of available items (25). Setting to 25. 
5: Requested number is larger than the number of available items (25). Setting to 25. 
6: Cannot add objects with duplicate keys (offending key: PC_) setting key to original value 'apca_' 

```
I believe this is leading to unwanted results in my subsampling analysis pipeline.

**Comment by akshayMpatel** [comment]
@yuhanH 
Since this is CITE-seq data, do you recommend using RunSPCA()? Which graph should be used?

**Comment by yuhanH** [comment]
@akshayMpatel sorry that i missed this question....
For CITE-seq data, you would better use WSNN for the graph input of RunSPCA to get the supervised low dimensional representation of RNA.
