### ISSUE TITLE
Error in rpca at IntegrateData : number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by Sa753** [satijalab/seurat#5248]
Dear Team,

This issue was opened and closed before here but it wasn't answered.
https://github.com/satijalab/seurat/issues/3936 

I integrate SCTransformed data using RPCA then I subset certain clusters. I split the integrated object then rerun SCTransform, RunPCA, SelectIntegrationFeatures, PrepSCT, FindIntegrationAnchors and IntegrateData. I get stuck at IntegrateData where I get the above error and can't proceed forward.

Would you please help?

Thanks

**Comment by jiayiliujiayi** [comment]
@Sa753 Did you finally resolve it?  I'm encountering the exact same issue.  Thanks!

**Comment by ajynair** [comment]
I also got similar error with my dataset integration. When I removed two samples with less than 120 cells and removed the old 'integrated' assay in the seurat object, this error went away. Just noting it here.
