### ISSUE TITLE
AverageExpression for biomarkers after SCTransformation and integraion

### ISSUE THREAD

**Issue by qibaotu** [satijalab/seurat#5249]
Hello,

I was running Seurat (version 4) on a set of scRNA-seq data from five samples. I did SCTransformation, integration and clustering. After that, I tried to plot heatmap of biomarkers for identified clusters, and I was using the AverageExpression function to get the expression of biomarkers. 
My question is that should I use the SCTransformed residual or the original UMI count for the AverageExpression function? I found some similar questions (#4991, #2413) , but got more and more confused. And I would really appreciate if you could help.

Here is my code:

![image](https://user-images.githubusercontent.com/11671499/139710830-91ffc2a0-5e25-4151-8b71-130a778556cd.png)

![image](https://user-images.githubusercontent.com/11671499/139710941-4132fe48-90f2-4b34-93c7-3d19866d79be.png)

Thanks!

**Comment by saketkc** [comment]
The "data" slot of SCT assay has `log1p(corrected counts)` which  you can use for visualizing overall expression. The residuals are in the `scale.data` slot which are not as interpretable. You can also switch to the RNA assay, run `NormalizeData()` and use the data slot to visualize. This will usually be very concordant with the SCT corrected values, unless one of the groups had very different sequencing depth. See related discussion [here](https://github.com/satijalab/seurat/issues/5009#issuecomment-907426252).

**Comment by qibaotu** [comment]
Hi @saketkc , thanks very much for the clarification, very appreciated!
