### ISSUE TITLE
Issue with 'TopTFs' implimentation

### ISSUE THREAD

**Issue by vim15** [satijalab/seurat#5250]
Hello, 

I'm running through your WNN [vigniette ](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html#wnn-analysis-of-10x-multiome-rna-atac-1) and have gotten down to the point about idetnifying interesting TFs based on their expression and their motif accessibility based on multiome data. 

I've run Chromvar and all the steps as outlined in the vignette and all of them execute with no errors. This includes the making of the TopTFs function. When I run the actuall function on one of the clusters, eg : 

`head(topTFs("StemCells"), 3)
`

I get the following error : 

` Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'head': Can't join on `x$gene` x `y$gene` because of incompatible types.
i `x$gene` is of type <character>>.
i `y$gene` is of type <double[,4337]>>.`

Do you know what is causing this or how I can resolve it? 
Thank you.

**Comment by torkencz** [comment]
It seems like ctmarkers_rna and ctmarkers_motifs gene column have different types. I would check if the filtering within the function maybe removes all data when you run it line by line.
