### ISSUE TITLE
problems running Seurat 4 on scATAC data preprocessed with ChromVAR

### ISSUE THREAD

**Issue by InaMariaDeutschmann** [satijalab/seurat#5251]
Hi,

we are running Seurat 4.0 to integrate a joint profiling of scRNA and scATAC (scCAT-seq data). The scATAC data are already preprocessed by the authors with chromVAR. Does it makes sense that we run on them TFIDF and SVD as suggested in your tutorial? Or it would be better to run PCA directly on the output of chromVAR?

If the second solution is the correct one, when using PCA with commands

```
mySeuratObj <- ScaleData(mySeuratObj)
mySeuratObj <- RunPCA(mySeuratObj)
mySeuratObj <- RunUMAP(mySeuratObj, reduction = 'pca', dims = 1:my_dimension, reduction.name = "umap.atac", reduction.key = "atacUMAP_") 
mySeuratObj <- FindMultiModalNeighbors(mySeuratObj, reduction.list = list("pca", "pca"), dims.list = list(1:my_dimension, 1:my_dimension), knn.range = my_knn_range) 
```
we get the following error: 
```
Error in cross_impute_dist[[r]]/modality_sd.list[[r]] : non-numeric argument to binary operator
```

Thanks in advance!

**Comment by yuhanH** [comment]
HI,
If you only have chromVAR data, you can run ScaleData and RunPCA. 
You need to give a new PCA name for the chromVAR PCA.  
```
mySeuratObj <- RunPCA(mySeuratObj,  reduction.name = "pca.atac",   reduction.key = "PCatac_")
mySeuratObj <- RunUMAP(mySeuratObj, reduction = 'pca.atac', dims = 1:my_dimension, reduction.name = "umap.atac", reduction.key = "atacUMAP_") 
mySeuratObj <- FindMultiModalNeighbors(mySeuratObj, reduction.list = list("pca", "pca.atac"), dims.list = list(1:my_dimension, 1:my_dimension), knn.range = my_knn_range) 
```
However, it will be best if you can run SVD on the original peaks data instead of using chromVAR data.
