### ISSUE TITLE
Number of cells of a cluster expressing a certain gene missing

### ISSUE THREAD

**Issue by RobinVroman** [satijalab/seurat#5252]
Hi, 

I am trying to see how many cells are in each cluster, for now I do this with: 
`table(Idents(object))`

I use 
`data.frametable(Idents(object))`
to be able to calculate with the values of each cluster. (eg 15 clusters)

When I look at the expression of a particular gene of interest (GOI) via making a subset:
(I want to know how many cells in each cluster express GOI).
`objectGOI <- subset(x = object, subset = GOI > 0.1)`
``data.frametable(Idents(objectGOI))``

This last datatable has sometimes then missing levels (eg only 12 clusters).
I guess when there is no expression of GOI in a certain cluster it is omitted. 

Is there a way to prevent this, so I have always the same table lay out? (with the full 15 clusters, and zero's when there is no expression).

Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This is more of base R thing than it is Seurat in that unused factor levels are dropped.  There is post-hoc solution though if you want to do it using method you proposed.  Simply use `full_join` from dplyr and make sure that your first dataframe is the one that contains all of the applicable idents and the idents not in the second dataframe will be assigned NA.

```
df1 <- data.frame(table(Idents(obj)))

sub_obj <- subset(obj, subset = GENE > 0.1)

df2 <- data.frame(table(Idents(sub_obj)))

df_merged <- full_join(df1, df2, by = "Var1")
```

Best,
Sam

**Comment by RobinVroman** [comment]
Thanks Sam, this helped me out!
