### ISSUE TITLE
Unify gene names when cross species integration analysis

### ISSUE THREAD

**Issue by whongfeiHK** [satijalab/seurat#5256]
Dear all,

I am doing cross species integration sc analysis between human and rat. However I found gene naming rules is different between them. For example, SNAI2 in human sample but Snai2 in rat, and also the '_' and '-', and may other differnet rules. I think this may cased by different refdata.gtf in cellranger. There are seems only one gtf named R_nor6.0 for Rat.

Before rename in R directly, may I ask you some better suggestions for that? I hope some of you may have handled this problem successfully. Many thanks.

Dale

**Comment by saketkc** [comment]
Hi Dale, our recommendation would be to name the orthologous genes with a common name before creating the seurat objects. You can use [ensembl](https://www.ensembl.info/2009/01/21/how-to-get-all-the-orthologous-genes-between-two-species/) to get a list of one-to-one orthologs. A lot of these genes can be handled by capitalizing the mouse gene names. The "_" in features is replaced with "-" when the object is created.
