### ISSUE TITLE
Does SEURAT automatically uses the scale.data slot?

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#526]
Dear all,

if running PCA, cluster and tsne analyses, does Seurat automatically uses the scale.data slot if present (if you ran ScaleData before)?

Thanks, Christian

**Comment by leonfodoulian** [comment]
Hi,

PCA is computed on the scaled data. Clustering and tSNE use the PCA data. 

Best,
Leon

**Comment by balthasar0810** [comment]
Thanks for the quick reply. If you do not do ScaleData, PCA uses the data slot instead? Best, Chris

----------
Dr. med Dipl.-Math. Christian Hinze

AG Schmidt-Ott
Max-Delbrück-Centrum
für Molekulare Medizin (MDC) Berlin-Buch
Robert-Rössle-Str. 10
13125 Berlin
Tel.: +49 30 9406 3240
christian.hinze@mdc-berlin.de

Medizinische Klinik mit Schwerpunkt Nephrologie
Charité - Universitätsmedizin Berlin
Campus Benjamin Franklin
Hindenburgdamm 30
12203 Berlin
Tel. +49 30 8445 2441
christian.hinze@charite.de<mailto:kai.schmidt-ott@charite.de>
________________________________
Von: Leon Fodoulian [notifications@github.com]
Gesendet: Mittwoch, 6. Juni 2018 01:05
An: satijalab/seurat
Cc: balthasar0810; Author
Betreff: [ext] Re: [satijalab/seurat] Does SEURAT automatically uses the scale.data slot? (#526)


Hi,

PCA is computed on the scaled data. Clustering and tSNE use the PCA data.

Best,
Leon

**Comment by leonfodoulian** [comment]
`Seurat::RunPCA()` requires scaled data. Otherwise, it throws the following error:

```R
Error in GetAssayData(object, assay.type = assay.type, slot = "scale.data") : 
  Object@scale.data has not been set. Run ScaleData() and then retry.
```

Best,
Leon

**Comment by balthasar0810** [comment]
Thanks. Strange. It did not threw this error.

Envoyé de mon iPhone

Le 6 juin 2018 à 15:21, Leon Fodoulian <notifications@github.com<mailto:notifications@github.com>> a écrit :


Seurat::RunPCA() requires scaled data. Otherwise, it throws the following error:

Error in GetAssayData(object, assay.type = assay.type, slot = "scale.data") :
  Object@scale.data has not been set. Run ScaleData() and then retry.

Best,
Leon

**Comment by leonfodoulian** [comment]
It might be related to differences in the versions of Seurat. I am using the latest release (v2.3.1). Or maybe you have had computed the scaled data before hand (which is very easy to check: `object@scale.data` should return `NULL` if not run). You can check the source codes for more details:

1. Lines 64 to 68 in dimensional_reduction.R

https://github.com/satijalab/seurat/blob/96d07d80bc4b6513b93e9c10d8a9d57ae7016f9f/R/dimensional_reduction.R#L64-L68

2. Line 44 in dimensional_reduction_internal.R

https://github.com/satijalab/seurat/blob/96d07d80bc4b6513b93e9c10d8a9d57ae7016f9f/R/dimensional_reduction_internal.R#L44

3. Lines 51 to 56 in multi_modal.R

https://github.com/satijalab/seurat/blob/cfc2f29b448cd92204099264d3b6cf9737a82e85/R/multi_modal.R#L51-L56

Best,
Leon

**Comment by balthasar0810** [comment]
Thank you!

Envoyé de mon iPhone

Le 6 juin 2018 à 15:50, Leon Fodoulian <notifications@github.com<mailto:notifications@github.com>> a écrit :


It might be related to differences in the versions of Seurat. I am using the latest release (v2.3.1). Or maybe you have had computed the scaled data before hand (which is very easy to check: object@scale.data<mailto:object@scale.data> should return NULL if not run). You can check the source codes for more details:

  1.  Lines 64 to 68 in dimensional_reduction.R

https://github.com/satijalab/seurat/blob/96d07d80bc4b6513b93e9c10d8a9d57ae7016f9f/R/dimensional_reduction.R#L64-L68

  1.  Line 44 in dimensional_reduction_internal.R

https://github.com/satijalab/seurat/blob/96d07d80bc4b6513b93e9c10d8a9d57ae7016f9f/R/dimensional_reduction_internal.R#L44

  1.  Lines 51 to 56 in multi_modal.R

https://github.com/satijalab/seurat/blob/cfc2f29b448cd92204099264d3b6cf9737a82e85/R/multi_modal.R#L51-L56

Best,
Leon
