### ISSUE TITLE
Get the total number of expressed genes in each cluster

### ISSUE THREAD

**Issue by DKaukonen** [satijalab/seurat#5260]
Hi,

In my lab we are doing a differential expression analysis within each cell cluster between two conditions. We are interested to see what percentage of total genes expressed in the cluster are significantly differentially expressed. In order to do this, I would need the feature count for each cluster, as I imagine that not all features from the overall dataset are present in each cluster.

Is there a way to get the number of genes expressed (nFeature) for each cluster? I have looked around here and other forums and cannot seem to find a good starting place. Perhaps my search words are not adequate.

The best I could come up with was subsetting the Seurat object by cluster and doing a total feature count there, but I am not sure if subsetting actually removes all of the features not present in the cluster. I also have ~80 clusters, so this does not seem like a viable approach. Does anyone have a better suggestion or at least a better place to get started?

Thank you.

**Comment by yuhanH** [comment]
`Is there a way to get the number of genes expressed (nFeature) for each cluster? `
You can select those cells and then check the rowsum of count matrix from those cells. 
I take the `pbmc_small` as an example
```
# three clusters
table(pbmc_small$RNA_snn_res.1)
cluster.set <- unique(pbmc_small$RNA_snn_res.1)
# overall nFeature
sum(rowSums(pbmc_small[['RNA']]@counts) != 0)

# nFeature for each cluster
sapply(X = cluster.set, function(c) {
  cells.c <- WhichCells(object = pbmc_small, expression = RNA_snn_res.1 == c)
  nFeature.c <- sum(rowSums(pbmc_small[['RNA']]@counts[, cells.c ]) != 0)
  return(nFeature.c)
}
)

```
