### ISSUE TITLE
Running all 10x ATAC analysis based on Seurat's re-computed peaks?

### ISSUE THREAD

**Issue by AidanMar** [satijalab/seurat#5263]
Hi there,

In 10x multiomic Vignette  ([https://satijalab.org/signac/articles/pbmc_multiomic.html#peak-calling-1](url)) 10x ATAC multiome data you recommend re-computing the peaks rather than using the ones computed by CellRanger. My questions are 1) In this case, would you recommend performing QC on the ATAC data based on the original or the re-computed peak profiles? If the recomputed peaks are more accurate, presumably it's better to use the latter 2) In the ATAC Vignette (ie not the multiomic Vignette but this one [https://satijalab.org/signac/articles/pbmc_vignette.html](url)) the recomputation of peaks is not included as an additional step. To the best of my understanding, the ATAC protocol and the multiome protocol should give more or less the same ATAC data, and as such the recomputation of peaks should also be performed in the standard ATAC protocol. Is this correct?

Thanks for your time, these tools are really great!

Best wishes,
Aidan

**Comment by timoast** [comment]
>  1) In this case, would you recommend performing QC on the ATAC data based on the original or the re-computed peak profiles? If the recomputed peaks are more accurate, presumably it's better to use the latter

In our experience, it doesn't matter much whether you use the cellranger peaks or MACS2 peaks for QC. The peak calls are more important for downstream analysis such as differential accessibility and motif enrichment.

> 2) In the ATAC Vignette (ie not the multiomic Vignette but this one https://satijalab.org/signac/articles/pbmc_vignette.html) the recomputation of peaks is not included as an additional step. To the best of my understanding, the ATAC protocol and the multiome protocol should give more or less the same ATAC data, and as such the recomputation of peaks should also be performed in the standard ATAC protocol. Is this correct?

Yes, both are showing analysis of DNA accessibility data. You can certainly re-compute peaks with scATAC-seq data using MACS2 and use these for downstream analysis. We don't demonstrate this step in the PBMC vignette for simplicity, but we have a separate vignette showing how to do the peak calling: https://satijalab.org/signac/articles/peak_calling.html
