### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by yuan596** [satijalab/seurat#5264]
hello,I can 't see the codes of the functions.For example, I want to know the RunUMAP function.does it use supervised umap method by the uwot package?

**Comment by samuel-marsh** [comment]
Hi,

All of the raw R source code can be found in the R section of the repo.

https://github.com/satijalab/seurat/tree/master/R

**Comment by yuhanH** [comment]
Thanks for your reply. @samuel-marsh 
Also, you can check RunUMAP function by `Seurat:::RunUMAP.default`. 
We use supervised umap function in uwot package.

**Comment by yuan596** [comment]
The data don't have the time,how can you use&nbsp;Dynamic Time Warping to align the data?
