### ISSUE TITLE
Changing titles of feature gene lists on DotPlots

### ISSUE THREAD

**Issue by vlau0847** [satijalab/seurat#5265]
Apologies I couldn't find the answer from all previous issue posts.

I wasn't able to find how to modify the name of the gene lists I've defined from features (e.g. Naive memory, Effector ,etc). Here you can see they're too big/clipped, and I'd like to have them 45 degree angled and smaller.
This happens even when I export the figure via ggsave.

Thanks in advance!

```
features = list("Naive Memory" = Naive_memory, "Effector" = Effector, "Exhausted" = Exhausted, "IFNy-Stimulated" = IFN_stimulated, "Cycling" = Cycling, "Resident Memory" = Resident_Memory)

DotPlot(Tcells, assay = "SCT", features = features, group.by = "seurat_clusters", cols = "Spectral", dot.scale = 4) +
     theme(axis.text.x = element_text(angle = 90, size = 9), legend.text = element_text(size = 12), legend.title = element_text(size = 12))
```

<img width="638" alt="Screenshot 2021-11-04 at 16 00 24" src="https://user-images.githubusercontent.com/78752821/140374753-f9f5bf7b-0b85-4f7c-b811-f0493b55b154.png">

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Since these plots are all ggplot2 based you can modify them as such.  In order to modify those facet labels both in terms of angle and size you can do the following:

```
DotPlot(obj, features = features) + theme(strip.text.x = element_text(angle = 45, size = XX))
```

Best,
Sam

**Comment by vlau0847** [comment]
Perfect!
Thank you!
