### ISSUE TITLE
Can I open the  the seurat4.Rdata with seurat3?

### ISSUE THREAD

**Issue by lwlive** [satijalab/seurat#5266]
I have performed analysis with seurat4 with R 4.0.5. I want to perform  monocle3 analysis which can only support R3.6. So I installed Seurat3 based on  R3.6.3. But when I  open the .Rdata  produced by Seurat4 with Seurat3, It does not work. Is there any way to solve this incompatible? Thanks!

**Comment by torkencz** [comment]
I would convert the Seurat object to a CellDataSet object using the as.cell_data_set() function from SeuratWrappers. Do it on the Seurat 4 object in R 4.0.5, then use monocle on that with R 3.6.
