### ISSUE TITLE
Error in irlba(A = t(x = object), nv = npcs, ...) :   BLAS/LAPACK routine 'DLASCL' gave error code -4

### ISSUE THREAD

**Issue by Dicky666520** [satijalab/seurat#5267]
Hi,
I am meeting a qusetion when I run the step " pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))", and it is  reported the error as follows : 

Error in irlba(A = t(x = object), nv = npcs, ...) :
  BLAS/LAPACK routine 'DLASCL' gave error code -4

How to solve this , please ?

My data is like this 
An object of class Seurat
23320 features across 18539 samples within 1 assay
Active assay: RNA (23320 features, 2000 variable features)

thank you so much

**Comment by yuhanH** [comment]
Hi,
Does this RunPCA error only happen on your pbmc dataset or for any datasets?
Could you reproduce this error using pbmc3k from [SeuratData](https://github.com/satijalab/seurat-data)?

**Comment by levinhein** [comment]
Hi @Dicky666520 Have you ever resolved this specific RunPCA error in irlba...? May I know how you resolved it? Any help is appreciated. Thank you.
