### ISSUE TITLE
issue with FindVariableGenes with do.recalc = FALSE

### ISSUE THREAD

**Issue by AlexGenshaft** [satijalab/seurat#527]
In my code (copied below), I run the FindVariableGenes command to both calculate variable genes initially and then twice right after to capture the plot with and without the genes labeled with text. The second two times I run with the flag do.recalc = FALSE. When I was returning these function calls to overwrite the seurat object (I've since stopped doing that), the variable gene list was changed to a different list of genes with the same length. This would drastically change the output of any function ran over variable genes subsequently (ie PCA, tsne, etc). Am I using the do.recalc flag improperly? Could you clarify this flag in the documentation? Thanks so much.

My calls are as follows:
y.cutoff.seurat = 0.5
x.cutoff.seurat = 0.15
data.all.seurat = FindVariableGenes(data.all.seurat, x.low.cutoff= x.cutoff.seurat, y.cutoff= y.cutoff.seurat, do.text=FALSE, do.recalc =TRUE)
pdf(paste0(sub_dir,"MeanVarPlot_nonames.pdf"), useDingbats = FALSE)
data.all.seurat = FindVariableGenes(data.all.seurat, x.low.cutoff= x.cutoff.seurat, y.cutoff= y.cutoff.seurat, do.text=FALSE, do.recalc = FALSE)
abline(h=y.cutoff.seurat, col = 'red')
abline(v=x.cutoff.seurat, col = 'red')
dev.off()
length(data.all.seurat@var.genes)

pdf(paste0(sub_dir,"MeanVarPlot_names.pdf"), useDingbats = FALSE)
data.all.seurat = FindVariableGenes(data.all.seurat, x.low.cutoff= x.cutoff.seurat, y.cutoff=y.cutoff.seurat, do.text=TRUE, do.recalc = FALSE)
abline(h=y.cutoff.seurat, col = 'red')
abline(v=x.cutoff.seurat, col = 'red')
dev.off()
length(data.all.seurat@var.genes)

**Comment by andrewwbutler** [comment]
Hi Alex,

Thanks for point this out. You were using the flag correctly but the list wasn't being set properly the second time you ran it with default parameters. It should be fixed now in the develop branch.
