### ISSUE TITLE
SCtransform does not work on all samples

### ISSUE THREAD

**Issue by rythi4** [satijalab/seurat#5270]
I am working with a dataset that consists of 48 samples which each contain between 159 and 662 cells. These samples need to be integrated, but when I run SCtransform on certain samples. I get the following error, which I do not understand:

```
r in estimate_overdispersions_fast(y, mean, model_matrix, do_cox_reid_adjustment,  : 
  Evaluation error: all(is.finite(mean)) is not TRUE.
```

There does not seem to be a clear correlation between the number of cells and whether the sample has to be excluded in order to be able to run SCtransform. 

The code I run is the following:

```
object_list <- SplitObject(seurat_object, split.by = "SAMPLE")

object_list <- lapply(X = object_list, FUN = SCTransform, verbose = TRUE, assay = "RNA", method = "glmGamPoi")
#or#
object_list$EXAMPLE <- SCTransform(object_list$EXAMPLE, assay = "RNA", method = "glmGamPoi")
```

**Comment by saketkc** [comment]
Do you have NAs in any of your counts matrices? You should see all TRUEs with this:
```r
lapply(X = object_list, FUN = function(obj) any(anyNA(GetAssayData(object = obj, assay="RNA", slot="counts"))))
```
The issue is during parameter estimation, which requires counts to start off with. You can check if all your count values are integers using:

```r
lapply(X = object_list, FUN = function(obj) all(round(GetAssayData(object = obj, assay="RNA", slot="counts") ) == GetAssayData(object = obj, assay="RNA", slot="counts")))
```

**Comment by rythi4** [comment]
I tried both the functions you wrote. The first one gives me all FALSEs, and the second one gives me all TRUEs, yet I still get the error.

**Comment by saketkc** [comment]
Since the datasets are smaller, can you try with the default estimation method, i.e. don't pass `method="glmGamPoi"`?

**Comment by rythi4** [comment]
That works 
Thank you!
