### ISSUE TITLE
Batch effects in ADT not resolved with CLR

### ISSUE THREAD

**Issue by redekarnr** [satijalab/seurat#5271]
I'm analyzing single cell data with multiple modalities (RNA, ADT) from 16 samples from first batch of sequencing and another 16 samples from second batch of sequencing. The count data every sample was normalized and scaled (log normalized for RNA assay, CLR normalization for ADT assay). For sample integration both assays were normalized and scaled in same manner across all 32 samples, prior to multimodal integration. 

Problem: The batch effects in ADT assay are not being resolved with CLR normalization. Log normalization instead of CLR somewhat improves the integration, but it is not right method of normalization for ADT assay (See graphics below).

I am interested in getting some recommendations to eliminate these batch effects in ADT assay data. 
![Picture1](https://user-images.githubusercontent.com/64104024/140530499-afd26287-8340-42e4-b11c-2f9d9c5c7bea.png)

My code was divided into multiple files, but here is short summary of relevant commands:
```
# Per library:
fileInput = Read10X_h5(file)
so = CreateSeuratObject(fileInput[[1]])
so[['CITESeq']] = CreateAssayObject(counts=fileInput[[2]])
so = NormalizeData(soC,assay="CITESeq",normalization.method="CLR")
so = ScaleData(so, assay="CITESeq")
so = RenameCells(so, add.cell.id = "S1") 

# Then low quality cells filtered here... code not included

so = SCTransform(so)
so <- RunPCA(so, VariableFeatures(so), do.print = TRUE, pcs.print = 1:5, genes.print = 0,verbose=F, npcs = 30)

#for sample integration with RNA assay, created list of 32 combined so objects ("reference.list") processed as above.

for (i in 1:length(x = reference.list)) {
  reference.list[[i]] = NormalizeData(reference.list[[i]], verbose = FALSE)
  reference.list[[i]] = FindVariableFeatures(reference.list[[i]], selection.method = "vst", nfeatures = nAnchors, verbose = FALSE)
}
reference.features <- SelectIntegrationFeatures(reference.list, nfeatures = 3000)
for (i in 1:length(x = reference.list)) {
  reference.list[[i]] = ScaleData(reference.list[[i]], reference.features, verbose = FALSE)
  reference.list[[i]] = RunPCA(reference.list[[i]], reference.features, verbose = FALSE)
}

reference.anchors = FindIntegrationAnchors(reference.list, reduction = "rpca", dims = 1:30, anchor.features = reference.features)
combinedObj = IntegrateData(anchorset = reference.anchors, new.assay.name = "integratedRNA", dims = 1:30, normalization.method = "SCT")
combinedObj = ScaleData(combinedObj, verbose = FALSE)
combinedObj = RunPCA(combinedObj, verbose = FALSE)

#ADT assay normalized for combined object
combinedObj = NormalizeData(combinedObj, assay= "CITESeq", normalization.method = 'CLR', margin = 2, verbose = FALSE)
reference.features = rownames(combinedObj[["CITESeq"]])
combinedObj = ScaleData(combinedObj, assay= "CITESeq", verbose = FALSE)
combinedObj = RunPCA(combinedObj, assay= "CITESeq", reduction.name = 'ADTpca', features = reference.features, verbose = FALSE)

#Multimodal integration (RNA and ADT)
DefaultAssay(combinedObj) <- "integratedRNA"
multimode.integrated <- FindMultiModalNeighbors(
  combinedObj, reduction.list = list("pca", "ADTpca"), 
  dims.list = list(1:30, 1:30), modality.weight.name = c("intRNA.weight", "intADT.weight"))

multimode.integrated <- RunUMAP(multimode.integrated, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
```

**Comment by timoast** [comment]
Hi @redekarnr, please include the full code you're running

**Comment by redekarnr** [comment]
@timoast code is now provided

**Comment by yuhanH** [comment]
Hi @redekarnr 
CLR itself cannot get rid of ADT batch effects. You need to use `FIndIntegrationAnchor` workflow to remove ADT batch effects. You can use rpca + integration anchor to correct ADT batch effects. 
Also, for the protein analysis, we recommend to use CLR normalization with margin  = 2.
`so = NormalizeData(soC,assay="CITESeq",normalization.method="CLR", margin = 2)`
