### ISSUE TITLE
DotPlot error in fetchdata

### ISSUE THREAD

**Issue by nayaracleite** [satijalab/seurat#5273]
Hello, 

I'm trying to do a DotPlot and I'm getting the following error:
![image](https://user-images.githubusercontent.com/48688017/140581153-380b95f8-2a4b-4149-9e79-27dca18ae782.png)

When I try to do a FeaturePlot, it works fine. 

![image](https://user-images.githubusercontent.com/48688017/140581480-53b10b8b-2837-48ee-836e-cea0d1243ed2.png)

```r
Idents(seurat_integrated) <- factor(Idents(seurat_integrated), levels = c("Ductal", "Beta ND",
    "Alpha", "Acinar", "Mesenchymal", "Beta T1D", "Immune", "Neuron"))
features <- c("INS", "NKX6-1", "GCG", "ARX", "CPA1", "COL1A1", "RAC2", "SPP1", "SOX10",
    "CHGA")
DotPlot(seurat_integrated, features = features, cols = c("blue", "red"), dot.scale = 8, split.by = "group") +
    RotatedAxis()
```

**Comment by mhkowalski** [comment]
Hi, do you have the integrated assay set as default? If so, it might be because the features you are looking to plot are not in the integrated assay (you can read more here #1198). We recommend using the RNA assay rather than the integrated assay for downstream analyses , so I would add ```assay = "RNA" ``` to your ```DotPlot()``` command.

**Comment by timoast** [comment]
Closing this now, `DotPlot()` uses scaled data so those features may not have been scaled or may not be in the assay you're using.

**Comment by WilliamMWei** [comment]
> Closing this now, `DotPlot()` uses scaled data so those features may not have been scaled or may not be in the assay you're using.

Hi excuse me for this but could I ask where could I find the information of which levels of the processed data do each visualizing function retrieve? Thank you so much
