### ISSUE TITLE
0x2ac2bfc79ba8 seurat memory not mapped

### ISSUE THREAD

**Issue by dalaplan1002** [satijalab/seurat#5276]
Hi,

I am trying to perform single cell RNA sequencing using Seurat. I have two conditions wild type and KO and I am using the pipeline integrating datasets. I have the error which says " 0x2ac2bfc79ba8 seurat memory not mapped" . Can you please help me to solve this error.
Thank you.

**Comment by yuhanH** [comment]
hi @dalaplan1002 
You need to provide more details about the scripts you run and what steps you met this error.
