### ISSUE TITLE
Issue when load package

### ISSUE THREAD

**Issue by XiaohanLuDuke** [satijalab/seurat#5277]
Hi all, I got this error message. Not sure what happened. Anyone could help? Thanks!!!!

Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘igraph’

**Comment by samuel-marsh** [comment]
Hi,

Not meber of dev team but hopefully can be helpful.  If you install the igraph package and then try to reload package does that solve the issue?

Best,
Sam

**Comment by XiaohanLuDuke** [comment]
> Hi,
> 
> Not meber of dev team but hopefully can be helpful. If you install the igraph package and then try to reload package does that solve the issue?
> 
> Best, Sam

Thank you, Sam.
No, I tried to install "igraph" and then reload Seurat and it showed another error:

Error in library("Seurat") : there is no package called ‘Seurat’

**Comment by samuel-marsh** [comment]
Hi,

So that means that Seurat is also not installed.  Try restaring R and installing Seurat.

**Comment by XiaohanLuDuke** [comment]
Hi Sam,
I just follow your suggestions. But it still show the error message.
Here is what I 

> Hi,
> 
> So that means that Seurat is also not installed. Try restaring R and installing Seurat.

Hi Sam,
I just follow your suggestions. But it still show the error message :Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘igraph’

Here the details what I ran, could you have a look?

> install.packages("Seurat")
also installing the dependencies ‘igraph’, ‘lmtest’


  There are binary versions available but the source versions are later:

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) yes
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/Seurat_4.0.5.tgz'
Content type 'application/x-gzip' length 3570682 bytes (3.4 MB)
==================================================
downloaded 3.4 MB


The downloaded binary packages are in
	/var/folders/tt/1sgsl33n0hq6b_mqb22zh2tjb875z6/T//Rtmptjuule/downloaded_packages
installing the source packages ‘igraph’, ‘lmtest’

trying URL 'https://cran.rstudio.com/src/contrib/igraph_1.2.8.tar.gz'
Content type 'application/x-gzip' length 2394934 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/src/contrib/lmtest_0.9-39.tar.gz'
Content type 'application/x-gzip' length 229650 bytes (224 KB)
==================================================
downloaded 224 KB
* installing *source* package ‘igraph’ ...
** package ‘igraph’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... clang -mmacosx-version-min=10.13
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang -mmacosx-version-min=10.13 accepts -g... yes
checking for clang -mmacosx-version-min=10.13 option to enable C11 features... none needed
checking whether the compiler supports GNU Fortran... no
checking whether gfortran -mmacosx-version-min=10.13 accepts -g... no
checking whether the compiler supports GNU C++... yes
checking whether clang++ -mmacosx-version-min=10.13 -std=gnu++14 accepts -g... yes
checking for clang++ -mmacosx-version-min=10.13 -std=gnu++14 option to enable C++11 features... none needed
checking how to run the C++ preprocessor... clang++ -mmacosx-version-min=10.13 -std=gnu++14 -E
checking for rintf... yes
checking for finite... yes
checking for expm1... yes
checking for rint... yes
checking for log2... yes
checking for logbl... yes
checking for snprintf... yes
checking for log1p... yes
checking for round... yes
checking for fmin... yes
checking for stpcpy... yes
checking for clang -mmacosx-version-min=10.13 options needed to detect all undeclared functions... none needed
checking whether isfinite is declared... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking whether stpcpy is declared... yes
checking for sys/times.h... yes
checking for net/if.h... yes
checking for netinet/in.h... yes
checking for net/if_dl.h... yes
checking for sys/sockio.h... yes
checking for sys/un.h... yes
checking for sys/socket.h... yes
checking for sys/ioctl.h... yes
checking for sys/time.h... yes
checking for sys/file.h... yes
checking for struct sockaddr.sa_len... yes
checking for xml2-config... /usr/bin/xml2-config
checking for xmlSAXUserParseFile in -lxml2... yes
checking for libxml/parser.h... yes
checking for __gmpz_add in -lgmp... no
checking how to run the C preprocessor... clang -mmacosx-version-min=10.13 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for glp_read_mps in -lglpk... no
configure: creating ./config.status
config.status: creating src/Makevars.tmp
config.status: creating src/Makevars
config.status: creating src/config.h
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -DIGRAPH_THREAD_LOCAL=/**/ -DNDEBUG -Iprpack -I. -Iinclude -DPRPACK_IGRAPH_SUPPORT -fPIC  -Wall -g -O2  -c DensityGrid.cpp -o DensityGrid.o
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -DIGRAPH_THREAD_LOCAL=/**/ -DNDEBUG -Iprpack -I. -Iinclude -DPRPACK_IGRAPH_SUPPORT -fPIC  -Wall -g -O2  -c DensityGrid_3d.cpp -o DensityGrid_3d.o
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -DIGRAPH_THREAD_LOCAL=/**/ -DNDEBUG -Iprpack -I. -Iinclude -DPRPACK_IGRAPH_SUPPORT -fPIC  -Wall -g -O2  -c NetDataTypes.cpp -o NetDataTypes.o
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -DIGRAPH_THREAD_LOCAL=/**/ -DNDEBUG -Iprpack -I. -Iinclude -DPRPACK_IGRAPH_SUPPORT -fPIC  -Wall -g -O2  -c NetRoutines.cpp -o NetRoutines.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c SuiteSparse_config/SuiteSparse_config.c -o SuiteSparse_config/SuiteSparse_config.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c adjlist.c -o adjlist.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c arpack.c -o arpack.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c array.c -o array.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c atlas.c -o atlas.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c attributes.c -o attributes.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c basic_query.c -o basic_query.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c bfgs.c -o bfgs.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c bigint.c -o bigint.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c bignum.c -o bignum.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c bipartite.c -o bipartite.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -DUSING_R -I. -Iinclude -Ics -Iplfit -ISuiteSparse_config -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Wall -g -O2 -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"1.2.8\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fPIC  -Wall -g -O2  -c blas.c -o blas.o
blas.c:71:59: error: too few arguments to function call, expected 12, have 11
                 VECTOR(*x), &inc, &beta, VECTOR(*y), &inc);
                                                          ^
./igraph_blas_internal.h:60:1: note: 'dgemv_' declared here
void igraphdgemv_(char *trans, int *m, int *n, igraph_real_t *alpha,
^
blas.c:112:57: error: too few arguments to function call, expected 12, have 11
                 (igraph_real_t*)x, &inc, &beta, y, &inc);
                                                        ^
./igraph_blas_internal.h:60:1: note: 'dgemv_' declared here
void igraphdgemv_(char *trans, int *m, int *n, igraph_real_t *alpha,
^
2 errors generated.
make: *** [blas.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status
* installing *source* package ‘lmtest’ ...
** package ‘lmtest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c pan.f -o pan.o
make: gfortran: No such file or directory
make: *** [pan.o] Error 1
ERROR: compilation failed for package ‘lmtest’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/lmtest’
Warning in install.packages :
  installation of package ‘lmtest’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/tt/1sgsl33n0hq6b_mqb22zh2tjb875z6/T/Rtmptjuule/downloaded_packages’
> library("Seurat")
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘igraph’

**Comment by samuel-marsh** [comment]
Hi,

So this looks like you are missing compiler components needs to properly compile the igraph and lmtest packages.  I would recommend installing required gfortran, clang, and other tools as described on CRAN R Download pages.  If you still have trouble after that I would recommend posting in the repos for igraph and/or lmtest as the issue is more to do with installation of those packages.

Best,
Sam

**Comment by XiaohanLuDuke** [comment]
> Hi,
> 
> So this looks like you are missing compiler components needs to properly compile the igraph and lmtest packages. I would recommend installing required gfortran, clang, and other tools as described on CRAN R Download pages. If you still have trouble after that I would recommend posting in the repos for igraph and/or lmtest as the issue is more to do with installation of those packages.
> 
> Best, Sam

Thanks so much!
Hannah

**Comment by XiaohanLuDuke** [comment]
> > Hi,
> > So this looks like you are missing compiler components needs to properly compile the igraph and lmtest packages. I would recommend installing required gfortran, clang, and other tools as described on CRAN R Download pages. If you still have trouble after that I would recommend posting in the repos for igraph and/or lmtest as the issue is more to do with installation of those packages.
> > Best, Sam
> 
> Thanks so much! Hannah

I have tried to removed the R and Rstudio from my computer and reinstalled them. I then reopen the software, and install the packages again. No error showed up. Hope this could help if you have same problem as mine.
