### ISSUE TITLE
Error in validityMethod(as(object, superClass)) :  long vectors not supported yet

### ISSUE THREAD

**Issue by cliang-huanglab** [satijalab/seurat#5278]
When I run the scRNA-seq integration ，I have encountered this error. How do I resolve it

**Here are my concrete results**
Integrating data
Merging dataset 9 8 3 into 4 13 6 17 11 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 2 7 14 12 15 18 into 4 13 6 17 11 1 9 8 3
Extracting anchors for merged samples
Finding integration vectors
Error in validityMethod(as(object, superClass)) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537
Calls: IntegrateData ... validObject -> anyStrings -> isTRUE -> validityMethod
Execution halted

**Comment by k3yavi** [comment]
Hi @cliang-huanglab ,

The error is most probably due to the overall size of data after the merge, can you try merging a subset of data and check if you still get similar error ?

**Comment by zhanghao-njmu** [comment]
You can try to use the modified version https://github.com/zhanghao-njmu/seurat which I have created a pull request #6527. 

I change the integration matrix format to ["spam"](https://cran.r-project.org/web/packages/spam/index.html) or ["spam64"](https://cran.r-project.org/web/packages/spam64/index.html) to process matrices with more than 2^31-1 non-zero elements. 

**However, it is important to note that processing large data requires sufficient memory.** 
I tested the modified version on the data with more than **200,000 cells**. The maximum memory used during the calculation was **1TB**.
