### ISSUE TITLE
HTO_maxID column in meta.data

### ISSUE THREAD

**Issue by johnmous** [satijalab/seurat#5279]
I have a quastion on the meaning of the `HTO_maxID` column, added to the metadata by `HTODemux`. Intuitively, it must be the HTO ID with the maximum number of counts for that cell. Which can be confirmed for my dataset, except for the case of doublets. In cells marked as doublets  `HTO_maxID` is not the HTO with the most counts.

My questions:
1. Can you give the definition of the `HTO_maxID` column?
2. How do you explain the unexpected values observed in this field for the case of doublets? Are we dealing with a bug that needs further investigation?

**Comment by torkencz** [comment]
Hi,
HTO max ID should contain the name of hashtag with the highest signal. Do you mind posting an example of when it is not?

**Comment by torkencz** [comment]
Going to close this now. Can reopen in case of example.
