### ISSUE TITLE
Bandwidth selection method for SCTransform

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#5280]
I believe the SCT algorithm could implement cross validation in selecting a bandwidth for the parameter kernel regressions.  I would use the function `npregbw()` from the `np `package.  I find the regressions look less sensitive to outliers in some cases.  Am I understanding correctly?

If `model.params` is a `data.frame` of the parameters for each gene model (intercept, B0, B1, theta)

```
bw.int <- npregbw(model.params$intercept ~ model.params$gene.mean, bwmethod = 'cv.aic', gradients = T)
bw.b0 <- npregbw(model.params$b0 ~ model.params$gene.mean, bwmethod = 'cv.aic', gradients = T)
etc. etc.
```
This would take longer than default method

**Comment by saketkc** [comment]
Thanks @danielcgingerich, this is a great suggestion. Do you have an example use case where the default bandwidth does not do well? We also filter out outliers before fitting, but curious to know if there are cases the default filtering doesn't work as well. In our recent [preprint](https://www.biorxiv.org/content/10.1101/2021.07.07.451498v1), we propose an updated model where only the intercept needs to be regularized, which might potentially also be useful here.
