### ISSUE TITLE
How to subset for Transcription Factors?

### ISSUE THREAD

**Issue by Jingchen1996** [satijalab/seurat#5281]
How does one subset the dataset for only transcription factors in R for a heatmap?

**Comment by timoast** [comment]
You can subset the genes present in the object using the `subset()` function or the `[` operator, for example:

```r
library(Seurat)
subset(pbmc_small, features = head(rownames(pbmc_small)))
```

**Comment by timoast** [comment]
If you specifically want to show TFs in a heatmap there's not really any need to subset the object, you can just choose the genes to plot in the heatmap using the `features` parameter in `DoHeatmap()`
