### ISSUE TITLE
Merge two overlapping subsets without renaming cells?

### ISSUE THREAD

**Issue by oliviagoldman** [satijalab/seurat#5282]
I have two subsets that I've filtered in different ways, and would like to combine them for further analysis. There are overlapping cells, and when I attempt to merge, it will rename the cells.

Is there anyway I can combine the subsets so that the duplicated objects are not renamed, and just eliminated? Thank you!

```
newObject <- merge(dat.subset1, dat.subset2)
_Warning message:
In CheckDuplicateCellNames(object.list = objects) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names._
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  If I'm understanding correctly you you have two objects that have some of the same cells.  What I would recommend doing so that you don't double the cells or have to rename them is:

```
library(dplyr)

# Pull cell names
cells1 <- colnames(obj1)
cells2 <- colnames(obj2)

# Identify shared cells between both objects
shared_cells <- intersect(x = cells1, y = cells2)

# Create Obj1 minus shared cells
obj1_minus <- subset(obj1, cells = shared_cells, invert = TRUE)

# Merge objects
merged <- merge(obj1_minus, obj2)
```

Best,
Sam
