### ISSUE TITLE
AverageExpression documentation seems incorrect

### ISSUE THREAD

**Issue by AohRveTPV** [satijalab/seurat#5283]
Seurat 4.0.5 `AverageExpression` documentation says "Returns a matrix with genes as rows, identity classes as columns."  However, with default parameters it seems to return a list not a matrix.  The list has a matrix in its "RNA" element.

The example code is the following:
```
data("pbmc_small")
head(AverageExpression(object = pbmc_small))
```

But `head` here just returns the same thing (the list containing a matrix) as when you don't use `head`.

I'm not an R expert so I may be missing something.  Thank you.

**Comment by saketkc** [comment]
Thanks for reporting. The function is designed that way to handle multiple assays and hence returns a list (unless return.seurat=TRUE). Though, we could definitely improve the documentation in the next release.
