### ISSUE TITLE
Not adequate normalization to deal with batch effect

### ISSUE THREAD

**Issue by YOU-k** [satijalab/seurat#5284]
Hi, 
I tried to regress out cell cycling effect and used harmony to integrate, and then did the clustering. Here are my codes: 
`srt_tumor <- NormalizeData(srt_tumor)
srt_tumor <- CellCycleScoring(srt_tumor, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

srt_tumor <- FindVariableFeatures(srt_tumor, selection.method = "vst")
srt_tumor <- ScaleData(srt_tumor, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(srt_tumor))

srt_tumor <- RunPCA(srt_tumor, features = VariableFeatures(srt_tumor),dims=1:25)
#devtools::install_github("immunogenomics/harmony")
library(harmony)
srt_tumor <- RunHarmony(srt_tumor, c("patient","Phase"))`

And then I would like to find the marker genes for each cluster. 
However, I found that for some clusters the marker genes are calculated driven by one batch of cells, which means that only a particular batch of cells expresses the marker gene relatively higher in a cluster.
(the resolution is at a relatively high level, and this can not be fixed by increasing the resolution)

I think this is caused by not adequate normalization. So at this stage, do you recommend that I use `sctransform` instead, and regress out batch effect with cell cycling score as well?

Happy to know your suggestion.
Cheers,
Chloe

**Comment by torkencz** [comment]
I think trying to regress batch and cell cycle with sctransform would be a good next step.
