### ISSUE TITLE
No seurat_annotation in seurat Object for my data

### ISSUE THREAD

**Issue by AyaOsama-pro** [satijalab/seurat#5285]
Hi everyone!
 I ran the seurat clustering and sctransform on my data till I reached RUNPCA and RUNUMAP but unlike the pbmc3k data,I don't get seurat-annotation in the output seurat object. 
consequently when I run levels(pbmc) I get the cell names, but for mydata I only get "SeuratProject". And then can't run differential analysis.
What could be the problem please?
Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the dev team but hopefully can be helpful.  So the seurat_annotation column in that object from SeuratData is a manual annotation as described in tutorial:
https://satijalab.org/seurat/articles/pbmc3k_tutorial.html#assigning-cell-type-identity-to-clusters-1

Annotation needs to be done manually or using supervised tools.

Best,
Sam

**Comment by AyaOsama-pro** [comment]
Thank you so much Sam.
That's really helpful.
