### ISSUE TITLE
Cutoff for raw counts for a gene of interest

### ISSUE THREAD

**Issue by deepamgp235** [satijalab/seurat#5286]
Hi, 
I have my zebrafish single-cell sequencing data and had some conceptual doubts. The idea is to check, for a particular gene of interest, how many cells have raw reads more than a certain value. After this, I would want to subset these cells and dive deeper into the analysis. The doubt is what should be my cutoff for the number of reads? I looked at quantile distribution, and 85% of the cells have zero counts. This is something that I would expect as the gene is just expressed in a subset of the population. But I feel quite unsure about including all the cells with 1 or more than one read count. So, I am a bit unsure about how to approach this issue and are there any practices that are standard in the field?

**Comment by torkencz** [comment]
Hi, I am not sure if there is a standard in the field is. My answer is going to be broad as I cannot see how your data looks. I would judge which cells to include by looking at the distribution of reads across the particular gene you are looking at. If you have a lot of cells with just one read I would set a higher threshold.
