### ISSUE TITLE
question about dotplots and pct.exp

### ISSUE THREAD

**Issue by jrgehlha** [satijalab/seurat#5287]
Hi all - question about dotplot. To work around the way the default layout works in dotplot in presenting a two group comparison I tried subsetting by experimental group (CTRL vs EXP for example) and then I would edit them in illustrator.  However, it looks like the pct.exp dots are generated dynamically per plot and not standardized between plots - eg 20% in one is not 20% in another.  I included the code and results below.  My goal is to do a two group (ctrl vs experimental) for particular cell types - the default grouping in dotplot is "interleaved" and I'd rather have them in more a "column" based format, if that makes sense.  Any suggestions to better accomplish this would be greatly appreciated, as this approach appears to have issues. 

#Expression Dotplot showing expression by clusters and quick comparison; only display by "state"
DefaultAssay(combined) <- "RNA"
markers.to.plot <- c( "AREG")
subset.combined <- subset(combined, idents=c( "1", "4", "6", "7","11", "12","16","18"), subset = (state == "CTRL"))
DotPlot(subset.combined, features = rev(markers.to.plot), dot.scale = 8) + 
  RotatedAxis() +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="viridis") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white")))

![Capture](https://user-images.githubusercontent.com/94058461/141125777-52c3c319-a18a-4247-8ba6-3624c1ab2fe6.PNG)

**Comment by torkencz** [comment]
Hi. I think the easiest way to get your Exp and Ctr on the same scale would be to use split.by on your original data and then edit in illustrator. I'll close this, but can reopen in case further questions pop up regarding this.
