### ISSUE TITLE
'CreateSeuratObject' Function Not Working in R-Program Studio on Anaconda Platform/Does Seurat Work With Single-Cell RNA Sequencing Data

### ISSUE THREAD

**Issue by STEMContractor01** [satijalab/seurat#5288]
Hello Satija Lab on GitHub,

I have some questions about the Seurat Package on the R Program software. I have been trying to complete the Guided Clustering Tutorial on your website. I am using R-Studio (Version 4.1.0) on the Anaconda Platform.

I have already talked with the 10X Genomics Company and they told me contacting your laboratory on GitHub would be best.

I have been trying to use the 'CreateSeuratobject' function to analyze data from a Single-Cell RNA Sequencing CSV file.

However, when I try to do this I cannot utilize the 'CreateSeuratobject'.

1. Are there additional libraries or packages that need to be installed in order to utilize the 'CreateSeuratobject' function?

2. Do you recommend just uploading the file instead of connecting to a file directory/folder to complete the Seurat Analysis?

3. Does Seurat work with CSV files? If not, would the CSV files have to be transformed into a matrix of some kind? Does your laboratory have any coding examples of Seurat working with Single-Cell RNA Sequencing CSV files?

If you could please contact me back regarding this, I would greatly appreciate it. I am trying to help out a colleague with this.

Thank You,

Darrell Robinson
iResearch Institute
Email: drobinson@iresearchcorp.com

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  In order to help figure out the issues can you please post the full code that you are running and exact error that you are receiving?

Thanks,
Sam

**Comment by STEMContractor01** [comment]
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::valid()
BiocManager::install("Bioconductor")
Warning message:
9 packages out-of-date; 0 packages too new


BiocManager::install("biocLite", force = TRUE)
BiocManager::install("dplyr", force = TRUE)
BiocManager::install("Seurat", force = TRUE)
BiocManager::install("patchwork", force = TRUE)
BiocManager::install("hdf5r", force = TRUE)

library(dplyr)
library(Seurat)
library(patchwork)
packageVersion('Seurat')
library(hdf5r)

wd <-setwd('C:/Users/drobin21.BU/Desktop')
getwd()
wd

#Loading the SC3CRISPROne Dataset

CRISPR.data <- Read10X_h5('SC3_v3_NextGem_DI_CellPlex_CRISPR_A549_30K_Multiplex_count_raw_feature_bc_matrix.h5')
CRISPR <- CreateSeuratObject(counts = CRISPR.data, project = "CRISPROne", min.cells = 3, min.features = 200)
colnames(CRISPR.data)
Result: NULL

setNames(CRISPR.data, c("Row","CMOSeven","CMOEight","CMONine","CMOTen","CMOEleven","CMOTwelve","Multiplet","Blanks","Assignment_Probability"))
Error in names(object) <- nm : 
  'names' attribute [10] must be the same length as the vector [3]


setnames(CRISPR.data, c("Row","CM7","CM8","CM9","C10","C11","C12","Mpt","Blk","Prb"))
Error in names(object) <- nm : 
  'names' attribute [10] must be the same length as the vector [3]

**Comment by samuel-marsh** [comment]
Hi,

So the issue is occurring because of the nature of the data.  I recognized this as 10X sample data and so downloaded myself.  When you run `Read10X_h5` it prints message:
`Genome matrix has multiple modalities, returning a list of matrices for this genome` to let you know that it is returning a list of matrices because of the presence of multiple modalities in the data (see description of `Read10X_h5` function.  Therefore to create a Seurat Object of the gene expression data for instance you would do the following:

```
CRISPR.data <- Read10X_h5('SC3_v3_NextGem_DI_CellPlex_CRISPR_A549_30K_Multiplex_count_raw_feature_bc_matrix.h5')

CRISPR <- CreateSeuratObject(counts = CRISPR.data$`Gene Expression`, project = "CRISPROne", min.cells = 3, min.features = 200)
OR
CRISPR <- CreateSeuratObject(counts = CRISPR.data[[1]], project = "CRISPROne", min.cells = 3, min.features = 200)

Best,
Sam
```

**Comment by STEMContractor01** [comment]
Hello Sam!

Thank you so much! That worked perfectly!

I just had one more question for you.

Have you tried to use Seurat for datasets that are outside of the Satija Laboratory or 10X Genomics Company Databases?

If so, do you personally recommend creating a HDF5 file out of those datasets?

Also, if there is some way I could provide a contribution or assist in anyway, please let me know!

Thank you so much again!!!

Respectful Regards,

Darrell Robinson
Email: drobinson289@gmail.com

**Comment by samuel-marsh** [comment]
Hi Darrell,

Yes I regularly use public and my own data.  HDF5 is nice due to the advantages of the format but in order to use either `Read10X` or `Read10X_h5` the data need to be in the specific format generated by 10X Genomics Cell Ranger tool.  So just being and HDF5 file is not sufficient.

If you want to make Seurat object from a matrix, data.frame, etc you simply need to provide an matrix, dataframe, etc with cell names/barcodes as columns and features/genes as rows.  So you can import that data using whatever function you need and then providing that matrix to `CreateSeuratObject`.

Best,
Sam

**Comment by STEMContractor01** [comment]
Hello Sam,

Do you recommend a tutorial link or example on how to do that?

Thank You & Best,

Darrell

**Comment by samuel-marsh** [comment]
Hi Darrell,

A tutorial on which part exactly?

Best,
Sam

**Comment by timoast** [comment]
@STEMContractor01 the `CreateSeuratObject()` function accepts as input a matrix or sparse matrix, we have examples of how to construct the Seurat object on the website (https://satijalab.org/seurat/articles/get_started.html), and there are examples you can find online to see how to read a matrix into R from a file if you don't have data in the 10x Cellranger format.
