### ISSUE TITLE
How to integrated the scRNA or scATAC and multiomics data?

### ISSUE THREAD

**Issue by Dragonlongzhilin** [satijalab/seurat#5290]
Seurat and Signac are nice tool to analysis single cell dataset. 
Recently, I encountered a problem regarding the integration of multiple types of data. 
I have serveral sample involving scRNA, scATAC and multi-omics(snRNA+snATAC) detected by 10X genomics, and want to integrate them to analysis.
But I am confused about how to integrate these data reasonably.

My envisioned plan is as follows:
With multi-omics as the center, RNA and ATAC are respectively integrated in sequence (scRNA+snRNA; scATAC+snATAC), and then the wnn method is used to integrate RNA and ATAC.
Is this plan feasible?

**Comment by torkencz** [comment]
Hi,
The best course of action should be what you've suggested. Integration across multi omics experiments on RNA-RNA and ATAC-ATAC then the RNA-ATAC integration. As a personal experience RNA-RNA tends to be a little more reliable so I would trust that more.

**Comment by Dragonlongzhilin** [comment]
Thanks for your reply!

**Comment by RosaDeSa** [comment]
Hi @Dragonlongzhilin, I am facing a similar challenge. Have you solved it, then?
