### ISSUE TITLE
Using the SCTransform integrated "data" slot as corrected counts for downstream pseudotime analysis

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#5291]
Hi,

I would like to know whether it would be reasonable to use the "data" slot from the integrated assay after SCTransform integration as corrected counts for downstream pseudotime analysis.  The pseudotime analysis software that I plan to use (SCORPIUS) reduces the dimensionality of the data using LMDS (Landmark Multi-Dimensional Scaling) with spearman correlation as the distance metric.  It then performs k-means clustering, identifies the shortest path between cluster centres, and fits a curve to the data using principal curves.

The information in the "Value" section for `IntegrateData()` made me wonder whether this was acceptable.

> Returns a Seurat object with a new integrated Assay. If normalization.method = "LogNormalize", the integrated data is returned to the data slot and can be treated as log-normalized, corrected data. If normalization.method = "SCT", the integrated data is returned to the scale.data slot and can be treated as centered, corrected Pearson residuals.

Best wishes,
Lucy

**Comment by saketkc** [comment]
Hi @lucygarner, you can treat the corrected pearson residuals in this case analogously to the log-normalized, corrected data.
