### ISSUE TITLE
Error in h(simpleError(msg, call)) :  error in evaluating the argument 'envir' in selecting a method for function 'mget': object 'org.Mm.egSYMBOL2EG' not found

### ISSUE THREAD

**Issue by XiaohanLuDuke** [satijalab/seurat#5293]
Code I ran as below and the error happened. 

enes =as.vector(modelX[,1])
entrezIDsPT <- mget(genes, org.Mm.egSYMBOL2EG, ifnotfound=NA )
entrezIDsPT <-as.character(entrezIDsPT)
modelX=cbind(modelX,entrezID=entrezIDsPT)
write.table(modelX,file="modelX_gene.txt", sep="\t", quote=F, row.names=F)

_

> Error in h(simpleError(msg, call)) :  error in evaluating the argument 'envir' in selecting a method for function 'mget': object 'org.Mm.egSYMBOL2EG' not found_

_

Waiting for some suggestion online now, appreciate it!!!

**Comment by saketkc** [comment]
Closing this as it is not related to Seurat. Aside, you might try importing `org.Mm.eg.db` first.

**Comment by XiaohanLuDuke** [comment]
> Closing this as it is not related to Seurat. Aside, you might try importing `org.Mm.eg.db` first.

Thanks!
