### ISSUE TITLE
How to determine a cell state based on a known set of genes, as in the Cell-Cycle Scoring and Regression tutorial

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#5299]
Hi,
Thanks for developing this user-friendly tool. I have an analysis question about the **determination of the cell state**, like the tutorial of **Cell-Cycle Scoring and Regression**.

I have four gene sets that represent different cell states. I want to see what state the cells are in my single-cell data. In my scenario, a cell might be in a single state, or in two states, or not in four states. But I don't know how to do it, and I think this analysis is similar to 
**Cell-Cycle Scoring and Regression**. In my search, I found that function **AddModuleScore**  might help me,but i don't know how to achieve it.

Another puzzle is how to determine a cell belongs to a state and how thresholds/cutoff value are determined.

Could you please give me some useful suggestions and examples to help me realize this idea.

**Comment by mhkowalski** [comment]
Yes,  using ```AddModuleScore``` seems reasonable for this task. You can see an example of this by looking at the documentation for the function, ```?AddModuleScore``` . 

As to how to choose a cutoff, it is a bit hard to say without having access to your data or understanding these cell states. You might look at the distribution of the scores of each state and choose a cutoff heuristically if there is a clear bimodal distribution of that score.  You might use ```RidgePlot()```, as show in the cell cycle vignette, to visualize the distribution of the module scores.
