### ISSUE TITLE
add customized clustering info to seurat object 

### ISSUE THREAD

**Issue by crazyhottommy** [satijalab/seurat#530]
Hi,

With the scaled (regressed) seurat object, how can I add K-means clustering or hierarchical clustering info to it?

```r
# Create and setup Seurat objects for each dataset
WM115 <- CreateSeuratObject(raw.data = WM115.data, project = "WM115")
WM115 <- FilterCells(WM115, subset.names = c("nGene", "percent.mito"), 
    low.thresholds = c(500, -Inf), high.thresholds = c(Inf, 0.15))

WM115 <- NormalizeData(WM115)
WM115 <- FindVariableGenes(WM115 do.plot = F, display.progress = F)

## always scale z score for PCA
WM115<- ScaleData(object =WM115, vars.to.regress = c("nUMI", "percent.mito"))

# graph based clustering
WM115 <- FindClusters(WM115,
    resolution = 0.6, dims.use = 1:10)

## how to add k-means and others?
....

```
Thanks!

Tommy

**Comment by crazyhottommy** [comment]
essentially I want to cluster single cells using k-means and color the points in the tsne plot. now the clustering is based on a graph-based (KNN) method, and do differentially expression based on the k-means clusters

**Comment by crazyhottommy** [comment]
Thank you! this helped!

**Comment by thomasveith** [comment]
I am trying to do something similar

```
# Add our clonal groupings
katoiii_s@meta.data$membership <- membership

# Set cell identity to sample identity
katoiii_s <- SetIdent(object = katoiii_s, value = "membership")

# tSNE plot
katoiii_s <- TSNEPlot(object = katoiii_s, group.by = "membership")
```
And I get the error: 

```
Error in `[[.Seurat`(object, reduction) : 
  Cannot find 'tsne' in this Seurat object
```

**Comment by ibseq** [comment]
Hi 
can we import  customised clustering info from 10x (csv file with each barcode assigned to a cell type = cluster) into seurat, if yes, how can this be done?

thanks
ib

**Comment by bounlu** [comment]
@crazyhottommy 

You can also do like:

`object$kmeans_10 = kmeans(x = object@reductions[["pca"]]@cell.embeddings, centers = 10, iter.max = 100, nstart = 100)$cluster`
