### ISSUE TITLE
Warning: The following arguments are not used: row.names with CreateSeuratObject

### ISSUE THREAD

**Issue by MWRR** [satijalab/seurat#5300]
When I run CreateSeuratObject as follow
seurat_matrix <- CreateSeuratObject (cov_mat, min.cells = 10, min.features =200, names.field = 1, names.delim = "-"), 
It is worked fine, but I got the warning: The following arguments are not used: row.names
the data was

[1] 33538 85144
3 x 3 sparse Matrix of class "dgTMatrix"
                            AAACCCAAGGGCAATC-1    AAACCCAAGGTGCCAA-1     AAACCCACAAGAATGT-1
MIR1302-2HG                  .                                                         .                               .
FAM138A                          .                                                         .                               .
OR4F5                               .                                                         .                               .  
 
I couldn't figure out why I got the warning.

**Comment by timoast** [comment]
This warning can be ignored. I have opened a pull request in the SeuratObject package to avoid the warning: https://github.com/mojaveazure/seurat-object/pull/32

**Comment by timoast** [comment]
This has now been fixed in the latest version of SeuratObject (4.0.4)

**Comment by MWRR** [comment]
> This has now been fixed in the latest version of SeuratObject (4.0.4)

Thanks, I will upgrade to the version 4.0.4
