### ISSUE TITLE
Error running FindIntegrationAnchors

### ISSUE THREAD

**Issue by XUTONG-GONG** [satijalab/seurat#5301]
Hi! I encountered the following error running FindIntegrationAnchors

Here's the command:
ifnb.list <- SplitObject(filtered_seurat, split.by = "sample")
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
  x <- SCTransform(x, vars.to.regress = c("mitoRatio"))
})

integ_features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000) 
split_seurat <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = integ_features)
integ_anchors <- FindIntegrationAnchors(object.list = split_seurat, 
                                        normalization.method = "SCT", 
                                        anchor.features = integ_features)

Output:
[...]
Filtering anchors
        Retained 6836 anchors
  |+++++++++++++++++++++++++++++++++++++++           | 77% ~16h 42m 51s  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 18945 anchors
Filtering anchors
        Retained 15034 anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 15785 anchors
Filtering anchors
        Retained 12598 anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 16615 anchors
Filtering anchors
        Retained 13418 anchors
Running CCA
Error in irlba(A = mat3, nv = num.cc) :
  BLAS/LAPACK routine 'DLASCLS' gave error code -4

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2

Random number generation:
 RNG:     Mersenne-Twister
 Normal:  Inversion
 Sample:  Rounding

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
 [1] radiant.data_1.4.1 dplyr_1.0.7        tidyr_1.1.4        lubridate_1.8.0
 [5] ggplot2_3.3.5      magrittr_2.0.1     stringr_1.4.0      purrr_0.3.4
 [9] patchwork_1.1.1    cowplot_1.1.1      SeuratObject_4.0.3 Seurat_4.0.5

**Comment by saketkc** [comment]
Hi @XUTONG-GONG, hopefully this has been solved given it's been open for long. Please create a new issue if you are still facing issues.
