### ISSUE TITLE
How to subset Seurat object by gene if a "-" is present in the gene name?

### ISSUE THREAD

**Issue by ondina-draia** [satijalab/seurat#5302]
Hello,
I'm currently analyzing a single-cell dataset and I want to subset my seurat object in function of the expression of a gene
Normally I'm doing it like this, following the [Seurat Command list](https://satijalab.org/seurat/articles/essential_commands.htmll):
`subset(x = pbmc, subset = MS4A1 > 3)`

Well, the issue is that I want to subset the seurat object by using the expression of _Hba-a1_, I know the gene is expressed because the gene appears on the featureplot. But when I'm trying to subset it, the following error appears _"None of the requested variables were found"_. I highly suspect the "-" in the name is the problem, how can I deal with this? Any suggestions?

**Comment by samuel-marsh** [comment]
Hi,

not member of dev team but hopefully can be helpful.  See #5133.  Need to add back ticks around gene symbol.

Best,
Sam

**Comment by ondina-draia** [comment]
Oh thank you very much, I didn't noticed this issue, it's exactly the information I needed
