### ISSUE TITLE
Joint analysis of multiple samples from multi-modal data - integration problem vs harmony

### ISSUE THREAD

**Issue by TerezaClarence** [satijalab/seurat#5305]
Dear Seurat Team,

I would like to ask for suggestions how to approach analysis of multimodal data. I have multiple different samples (conditions ~ donors) for joint snRNA+snATAC and I am trying to find the best way how to analyse the data altogether (not separately). 
Currently:
1. merges samples, then filter (so that I am left with the same cells that meet filtering criteria for both RNA and ATAC) and create a single multimodal Seurat object (with ATAC and RNA assays)
2. split object into two - RNA separately (snRNAf) and ATAC separately (snATACf)
3.  perform data integration on RNA object (I aim to integrate the samples by orig.ident):
      3.1 `SplitObject` into list of objects based on `orig.ident`
      3.2 `NormalizeData` and `FindVariableFeatures` for each items in the list of objects
      3.3 Select features that are repeatedly variable across datasets for integration
      3.4 Perform integration based on anchors (`FindIntegrationAnchors`)
      3.5 Create  'integrated' assay in the RNA object and set it as default 
       3.6 `ScaleData;RunPCA;RunUMAP;FindNeighbours;FindClusters `on the integrated RNA object

4. perform data integration on ATAC object:
        4.1 `SplitObject` into list of objects based on `orig.ident`
        4.2 `RunTFIDF/FindTopFeatures `for each item in the list
        4.3 Select features that are repeatedly variable across datasets for integration
        4.4 `FindIntegrationAnchors `and LSI embedding by `IntegrateEmbedding`
        4.5 Create  'integrated' assay in the RNA object and set it as default 
        4.6 `RunUMAP;FindNeighbours;FindClusters on the integrated ATAC objec`t

5. perform WNN analysis on the integrated ATAC and RNA objects? or shall I then perform another integration RNA + ATAC object to join them together?

I am basically dealing with a problem of _**what and when merge vs integrate; normalize vs scale etc**_. 

I want to look at all the samples together as a single multimodal object, however without any integration I do observe strong donor or sex effect which is reduced if I integrate samples based on Seurat/Signac tutorials.  Such integration is always for each modality separately. I am wondering if it is possible to perform sample integration of multimodal object without actually splitting into RNA and ATAC assay. 

Alternatively, I would like to try Harmony instead of classical integration, however I am not sure how to approach this on multimodal object - shall I run Harmony separately on ATAC and RNA assay within the joint object? 

Thank you so much for any suggestions and ideas!

Best regards,
Tereza

**Comment by timoast** [comment]
If you have multimodal data, where RNA + ATAC is being measured in the same cell, you should not split into separate assays.

What I would suggest doing is first quantifying the same set of peaks across all of the ATAC assays and then merging the multimodal objects (see https://satijalab.org/signac/articles/merging.html), and check whether there is a batch effect that you need to deal with.

If there is a batch effect, you can find anchors using either of the modalities, and then use the same set of anchors to integrate both the RNA data using `IntegrateData()` (or integrate the RNA PCA embeddings using `IntegrateEmbeddings()`) and the ATAC LSI embeddings using `IntegrateEmbeddings()`.

**Comment by TeodoraTockovska** [comment]
> If you have multimodal data, where RNA + ATAC is being measured in the same cell, you should not split into separate assays.
> 
> What I would suggest doing is first quantifying the same set of peaks across all of the ATAC assays and then merging the multimodal objects (see https://satijalab.org/signac/articles/merging.html), and check whether there is a batch effect that you need to deal with.
> 
> If there is a batch effect, you can find anchors using either of the modalities, and then use the same set of anchors to integrate both the RNA data using `IntegrateData()` (or integrate the RNA PCA embeddings using `IntegrateEmbeddings()`) and the ATAC LSI embeddings using `IntegrateEmbeddings()`.

Hi @timoast,

How could you differentiate between batch effects of real biological signals? I have samples that were sequenced at the same time (10X sc-multiome) and I aligned ATAC using common peak sets and I merged the data. Then I normalized and clustered ATAC and GEX (the usual workflows for GEX and ATAC processing using Seurat v5 and Signac v1.13.0). It is my understanding that batch effects shouldn't be present if samples are sequenced at the same time. Can I send you my UMAP figures and get your opinion? 

Thanks,
Teodora
