### ISSUE TITLE
When to split seurat objects before SCTransform

### ISSUE THREAD

**Issue by pje1217** [satijalab/seurat#5306]
Hello, thank you for developing a great tool for the analysis. 

I have a question about when to split seurat objects before SCTransform. 
There have been similar questions, but I wasn't 100% sure what is the correct approach. 

I have a dataset with 108 samples with 18 different conditions (6 replicates for each condition). 
The samples were processed in three different days (36 samples/day), which I expect that there might be a batch effect based on this. 

My question is :
1. Should I perform SCTransform on a merged object (all cells from all 108 samples) for downstream analysis? or
2. Should I split object by sample (108 sample), perform SCTransform, then merge?
3. Should I split object by condition (18 different condition), perform SCTransform, then merge?

It seems like SCTransform function can correct for the sequencing depth at a per-cell level, I was not sure if it's necessary to split object by sample before performing SCTransform. But I also saw a vignette that splits object by stimulation status and then normalize (https://satijalab.org/seurat/articles/integration_introduction.html) so I wanted to know what is the recommended approach. 

I would appreciate your answer on this. Thank you very much!

**Comment by saketkc** [comment]
You can go with option 2, i.e. run SCTransform on each sample individually before merging. Though, it is quite possible that you would get very similar results with the other two options, if there are no significant batch effects. The motivation behind splitting is to learn a sample specific noise model for normalization.
