### ISSUE TITLE
marker genes DE analysis

### ISSUE THREAD

**Issue by rojinsafavi** [satijalab/seurat#5308]
Hello,

the result that I'm getting from DE analysis is a bit weird. For example, YBX1 is showing up as significant, but it is actually expressed in all the cell

```
M = FindMarkers(scRNA_ex, ident.1 = 'cluster1', ident.2 = c(all other clusters ),only.pos = T,test.use = "roc")
```

<img width="389" alt="Screen Shot 2021-11-17 at 10 47 09 AM" src="https://user-images.githubusercontent.com/19545198/142263153-9523f86c-589a-4c23-849b-3bfb7534614b.png">
s.

**Comment by saketkc** [comment]
To filter out genes that are very specific to one population, you can use the `pct.1` or `min.diff.pct` parameter. Setting a high value of `min.diff.pct` will filter out genes that are expressed in both the clusters (though might still be differentially expressed).
