### ISSUE TITLE
FindSubCluster - graph.name

### ISSUE THREAD

**Issue by pchopr4** [satijalab/seurat#5311]
Hi,

I was trying to analyze a cluster using the FindSubCluster function (Seurat_4.0.1). I'm not sure if I am using the graph.name parameter correctly. Here is my code and error:

    > sobj@commands$FindClusters$graph.name
    [1] "integrated_snn"

    > sobj1 <- FindSubCluster(sobj,cluster=3,graph.name="integrated_snn",resolution=0.3)
    Error: Cannot find 'integrated_snn' in this Seurat object

What do I need to use for the graph.name argument?

Thanks!

**Comment by yuhanH** [comment]
Hi, 
You need to check what graph exists in your object. `Graphs(sobj1)`. 
If `sobj1` is a subset of `sobj`, usually the SNN graph will be lost in the `subset` process.  You can create a new SNN graph for `sobj1`. 
```
sobj1[["integrated_snn"]] <- sobj[["integrated_snn"]][Cells(sobj1), Cells(sobj1)]
```
