### ISSUE TITLE
Downsampling Seurat Object

### ISSUE THREAD

**Issue by bari89** [satijalab/seurat#5312]
Hi Seurat Team,

I have a seurat object with 5 conditions and 9 cell types defined.
I would like to randomly downsample each cell type for each condition. What would be the best way to do it?

Example
Conditions: ctrl1, ctrl2, ctrl3, exp1, exp2
Cell types: Micro, Astro, Oligo, Endo, InN, ExN, Pericyte, OPC, NasN

ctrl1 Micro 1000 cells
ctrl2 Micro 1000 cells
ctrl3 Micro 1000 cells
exp1 Micro 1000 cells
exp2 Micro 1000 cells
ctrl1 Astro 1000 cells
ctrl2 Astro 1000 cells
ctrl3 Astro 1000 cells
exp1 Astro 1000 cells
exp2 Astro 1000 cells

etc..

Thanks!

**Comment by mhkowalski** [comment]
This is more of a general R question than a question directly related to Seurat, but i will try to give you an idea. The ```slice_sample()``` function in the dplyr package is useful here. If you make a dataframe containing the barcodes, conditions, and celltypes,  you can sample 1000 cells within each condition/ celltype.  For instance, you might do something like this: 

``` 
df <- data.frame(condition=obj$condition, cell_type=obj$cell_type)
df$barcode <- rownames(df)
df %>% group_by(condition, cell_type) %>% slice_sample(n=1000) #  sample w/i each condition/celltype
```
