### ISSUE TITLE
Centered log ratio calculation: mismatch between numerator & denominator

### ISSUE THREAD

**Issue by tomsing1** [satijalab/seurat#5315]
https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/preprocessing.R#L2391

I noticed that the CLR calculation uses the log1p function, but also excludes all zeros from the numerator of the ratio `x[x > 0]` . That doesn't happen in the denominator: `length(x = x)`. 

Given that `log1p(0)` is defined, can the function be simplified to:

```
return(log1p(x = x / (exp(x = sum(log1p(x = x), na.rm = TRUE) / length(x = x))))) 
```
?

**Comment by yuhanH** [comment]
Hi @tomsing1 
Thanks for pointing this out. We will improve this soon.

**Comment by rsatija** [comment]
We actually had included this to make the function code a bit clearer, since the output is the same either way we will keep as-is. thanks!
