### ISSUE TITLE
Can't replicate avg_diff values from FindMarkers() with scale.data slot

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#5316]
Hi,

I am storing some custom data within the "scale.data" slot of my Seurat object.  This data is not scaled or log-transformed.  I am trying to calculate the fold change in these values between one group of cells and another.  I did this manually using `AverageExpression()` and then performing `log2(average_condition1/average_condition2)`.  

When I use `FindMarkers()` with the "scale.data" slot, I get very different results for the fold change.  Could you tell me the exact calculation that I would need to do with my `AverageExpression()` output to replicate the `FindMarkers()` fold change values please?  I see that you have included a pseudocount but adding this didn't seem to generate the same values either.

Best wishes,
Lucy

**Comment by ghalasz** [comment]
Hi Lucy,
I'm not part of this project, but noticed the same thing. I'll put in a pull request at some point (or you can!), but I believe there's actually a bug in the FoldChange() function, on line 956 of https://github.com/satijalab/seurat/blob/master/R/differential_expression.R

`      return(log(x = rowMeans(x = expm1(x = x)) + pseudocount.use, base = base))
`

Seems the expm1 part should be (base^x - 1).
Best,
Gabor

**Comment by mhkowalski** [comment]
Hi, 

Running ```FindMarkers()``` on the "scale.data" slot calculates the average difference between the two groups, not the logFC. Therefore, you could do 

```average_condition1-average_condition2``` to replicate the results from ```FindMarkers()```.
