### ISSUE TITLE
Does performing SCTransform workflow on loom object mirror cluster assignments obtained in regular SCTransform-ed Seurat object?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5318]
Hi @mojaveazure - Thank you very much for the suggestion in issue #3423 (considering the spliced assay in the loom object as "RNA assay" and rerun the Seurat SCTransform workflow on this loom object (if my "normal" Seurat object was performed under SCTransform for clustering/DEG analysis)). 

Would you mind helping me clarify the following points? Thank you again for your help. 

1. You mentioned "However, you can also treat the spliced assay as a standard RNA assay, and after processing your data with velocyto, simply run Seurat's workflow on the spliced assay (see the Estimating RNA Velocity using Seurat and Estimating RNA Velocity using Seurat and scVelo community vignettes for examples)." Which processings by velocyto you referred to here? Did you mean the "preliminary filtering" they have, e.g., vlm.filter_cells (here: http://velocyto.org/velocyto.py/tutorial/analysis.html)? 

2. I have individual loom objects created by velocyto for each sample. I planned to merge them into 1 loom object, using loompy (http://velocyto.org/velocyto.py/tutorial/cli.html#merging-multiple-samples-lanes-in-a-single-file). I would then ReadVelocity() and as.Seurat() then do all the SCTransform() to get a h5ad with spliced/unspliced info in it (http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html). 

Would doing the SCTransform() on the combined loom objects produce the same cell cluster assignment as what obtained when doing Seurat clustering from cellranger counts? And if they are not, how can I be sure that the trajectories obtained reflect what happening in clusters obtained from regular Seurat clustering of cellranger counts? 

3. I have seen others recommending to extract exisiting Seurat metadata then merge it with the loom spliced/unspliced data. For example: https://smorabit.github.io/tutorials/8_velocyto/, or https://github.com/basilkhuder/Seurat-to-RNA-Velocity#generating-loom-files. Which approach is "more appropriate" ?

**Comment by saketkc** [comment]
SCTransform on spliced+unspliced counts sounds like a reasonable approach here. cellranger counts in older cellranger version used to be just spliced counts - so that is something would want to keep in mind. Closing this as the questions are very broad and not specific to seurat.
