### ISSUE TITLE
How to get both differentially expressed and non-differentially expressed genes in a cluster?

### ISSUE THREAD

**Issue by sdavoudi1** [satijalab/seurat#532]
Hi,

I'm trying to run GSEA enrichment analysis on one of the clusters of my RNA seq results and to do that, I need to create a ranked file for all of the genes expressed in that cluster (both the differentially AND non-differentially expressed genes).

Using the FindMarkers() function will only give me the differentially expressed genes with significant p-values. How do I get all the other genes that are non-significant?

Thanks!

**Comment by kathush** [comment]
Hi sdavoudi1, 
Did you find a solution for this issue? I'm also interested in running a similar analysis. 
Thanks!

**Comment by andrewwbutler** [comment]
Hi,

To perform differential gene expression via `FindMarkers` without gene filtering, you can set the following parameters to `-Inf`: `logfc.threshold`, `min.pct,` and `min.diff.pct`. 
e.g:

```r 
FindMarkers(object = object, ident.1 = 0, ident.2 = 1,
 logfc.threshold = -Inf, min.pct = -Inf, min.diff.pct = -Inf )
```
