### ISSUE TITLE
How to run FindMarkers after SCTransform

### ISSUE THREAD

**Issue by weishwu** [satijalab/seurat#5321]
Hi,

I'm confused by which assay and slot I should use for FindMarkers after SCTransform and Integration. I searched the related Issues and saw different answers. In the old normalization method which uses "NormalizeData", it is clear to use slot "data" in assay "RNA", because the normalized data is stored in "data". However, with SCTransform, the slots "data" and "counts" are exactly the same in the assay "RNA".

I've seen posts in which @satijalab recommended using the assay "RNA" instead of "SCT" for FindMarkers. Is this still the best practice?

And if I run FindMarkers with the default settings (method = 'wilcox', slot = 'data'), should I first run NormalizeData to convert the slot "data" (in assay "RNA") to normalized counts?

For Visium data, should I then use the assay "Spatial" slot "data" for FindMarkers, and also first run NormalizeData to "fix" the "data" slot under assay "Spatial"? In the Visium analysis vignette (https://satijalab.org/seurat/articles/spatial_vignette.html) FindMarkers is run directly on the object (I guess this by default uses "SCT" assay?). Is this contradictory to the newest recommendation?

Thanks, and sorry if I overlooked any existing documentation that already explained this.

**Comment by torkencz** [comment]
Hi,

Sorry about the confusion. Probably results from running on the SCT should be similar to RNA, but would recommend clustering first and for find marker use SCTransform data. (see https://github.com/satijalab/seurat/issues/1501). If you go the RNA route definitely normalize and scale before running FindMarkers. These should hold true for Visium data as well.
Note that the absolute best way to do this is to run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data.

**Comment by weishwu** [comment]
Thanks @torkencz for your response!

When you said "If you go the RNA route definitely normalize and scale before running FindMarkers", did you suggest I should use the "scale.data" slot in the "RNA" assay to run FindMarkers? However, the default slot to use is "data" when the method is "wilcox" (default). It says in this thread that @scale.data is inappropriate for DE test: https://github.com/satijalab/seurat/issues/62

Here is another post where someone recommended against using @scale.data:
https://www.biostars.org/p/406388/

Thanks.
