### ISSUE TITLE
How to remove an assay for memory saving?

### ISSUE THREAD

**Issue by QqQss** [satijalab/seurat#5322]
Hello, I want to delete one named as 'integrated' assay in my big Seurat object.
I have tried the code:
```
seu@assays$integrated <- NULL
seu <- subset(seu, idents=c("C1"))
```
the first command runs OK, but the second subset command returned an error like:
_Error: Cannot find assay 'integrated' in this Seurat object_

So, what is the correct command for my purpose?

**Comment by timoast** [comment]
```
obj[["assay"]] <- NULL
```

Note that you can't remove the active assay (change the active assay using `DefaultAssay()` first)
