### ISSUE TITLE
Integration of Seurat Objects produces extra features

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#5323]
Hello! I have separate 10X genomic runs that I wanted to integrate:

b1ko1: 12980 features across 2754 samples
b1wt1; 12794 features across 2462 samples 
b1wt2: 12958 features across 1547 samples
b1het1: 12622 features across 931 samples
b2het2: 14481 features across 3185 samples
b2wt3: 14694 features across 3360 samples
b3het3: 14097 features across 2080 samples
b3ko2: 14165 features across 3985 samples

Merging them gives me 15390 features across 20304 samples

When I integrate my merged data I get more features than the above. 
Normal integration: 17390 features across 18932 samples 
SCTransform: 32511 features across 18932 samples

Can someone please explain why this happens?

**Comment by timoast** [comment]
When you print the object summary it shows the total number of features across all assays present in the object. One gene could result in multiple feature if it is represented in multiple assays. For example, running SCTransform will create a new SCT assay, integration will create a new integrated assay.
