### ISSUE TITLE
Should I do batch-correction or only merge for these datasets, following cellranger aggr?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5328]
Related to the issue #4161, I sorted 2 populations of the same cell type from the same tissue from 3 different donors, based on a surface protein marker (called X): Xnegative and Xpositive. 

For each donor, the 2 cell populations Xneg and Xpos were sequenced separately. 

I then used cellranger aggr to combine the data from all 3 donors within Xpos with depth normalization. A similar procedure was done for Xneg data. 

**I expect the Xneg cells differ biologically from the Xpos cells. But, Xpos cells can derive from Xneg cells and vice versa.** So, **if my goal is to find all the cell subsets that are Xpos that function differently or that they could derive from Xneg cells**, I decided to merge Xneg and Xpos Seurat objects together (after I QC each object separately), then perform the SCTransform on the merged Seurat object. 

**My goal is not to find cell subsets that are shared between Xneg and Xpos, and how they differ.**

This decision was made because Discussion #3998 suggests that "it may not be necessary to perform integrative analysis, particularly in cases where there are not expected to be substantial batch effects or biological differences across samples. In these cases, users can begin each analysis by merging the datasets together (using the merge command), and proceed with the standard analysis workflow."

**However, in my case, I expect that Xneg and Xpos cells are biologically different.** I understand "The Seurat integration procedure aims to identify shared cell populations across different datasets, and ensure that they group together after integration. This enables the frequency and gene expression profiles of these populations to be effectively compared in downstream analysis." 

Discussion #3998 says "Users can apply clustering and visualization to see if cells from the same biological subpopulations group together across datasets. If so, there is no need to perform integrative analysis. However, if cells cluster primarily by their dataset of origin as opposed to their biological state, we suggest applying our Seurat integration workflow." **In my case, Xpos cells do cluster away from Xneg cells**, so it seems I do not need to do Seurat integration and just merge them. But, **in my case, the "dataset of origin" (Xpos versus Xneg) is also the "biological state."**

**My questions:** 
In issue #4161, @torkencz suggests that I could "Integrate the Xneg tissue dataset and Xpos tissue dataset and then do a comparative analysis to find cell subsets that are shared and unique between the Xneg and Xpos populations" **1. But, If I integrate Xneg and Xpos data together, when viewing UMAP by X_status, Xneg suddenly has the same cell cluster patterns as in the Xpos clustering and Xneg cells cluster together with Xpos cells, which I guess is expected of the integration goal. But, does that mean I have lost the ability to identify cell subsets that exist in Xpos that might not exist in Xneg?** (ie the integration masks over the biological effect of the X marker?)

Another user #4372 asked whether integration in Seurat is different from batch correction. I think batch correction is part of the Integration in Seurat. **2. So, in my case, should I just do batch correction when I merge the Xpos and Xneg data, e.g., using fastMNN, then not do Seurat integration?** 

Thank you so much for your help!

Discussed in https://github.com/satijalab/seurat/discussions/3998

**Comment by rsatija** [comment]
There is no easy answer to your question, especially as your experimental design has two different conditions in two different experiments, as you say. I think the discussion you reference goes through these points. It sounds like you do not expect cells to share a biological state, so I would not suggest performing either batch correction or integration.
