### ISSUE TITLE
Percent (Pct.exp in legend in DotPlot and SplitDotPlot) is off by factor 100

### ISSUE THREAD

**Issue by dpleone** [satijalab/seurat#533]
The legend for DotPlot (and SplitDotPlot) showing the percent of cells (in the group/cluster) expressing a given marker is displayed as (0.0, 0.25, 0.50, 0.75, 1.00) instead of (0, 25, 50, 75, 100). It's cosmetics, I know, but it would be nice if you guys could fix this.
It's also visible in the tutorials, e.g.:
https://satijalab.org/seurat/immune_alignment.html
(scroll down about 60% of the page to the SplitDotPlot)

Thanks for the great work!

**Comment by andrewwbutler** [comment]
This has been updated now on the develop branch ([installation instructions](https://satijalab.org/seurat/devinstall.html)).
