### ISSUE TITLE
Unable to show Y axis units on RidgePlot

### ISSUE THREAD

**Issue by anandsku** [satijalab/seurat#5331]
This may be a noob question. I am trying to get RidgePlot to show Y axis ticks and tick labels. I tried doing the following:

`yy=RidgePlot(P0LR1,features = c("Foxp2"),group.by ="orig.ident")+theme(axis.line.y = element_line(),axis.text = element_text()) 
`
But that does not seem to be working. My plot looks like this:

![image](https://user-images.githubusercontent.com/43101976/143323778-49380e41-1d15-4093-bb21-f6cc9c811530.png)

How can I get it to show the Y axis tick labels?

**Comment by k3yavi** [comment]
Hi @anandsku ,

Can you try `theme(axis.text.y = element_text())` and check if that helps ?

**Comment by anandsku** [comment]
Hello @k3yavi ,
                      I tried the said solution. I does not bring up Y tick labels:

`RidgePlot(R1,features = c("Foxp2"),group.by ="orig.ident")+theme(axis.line.y = element_line(),axis.text.y = element_text())
`

![image](https://user-images.githubusercontent.com/43101976/145070979-4c181ffa-1e2b-4897-9f99-c9142c01b639.png)

P.S. The plot looks different because its a different data set

**Comment by yuhanH** [comment]
Hi @anandsku 
This issue actually is more related to `ggridges` package. 
[Here]( https://cran.r-project.org/web/packages/ggridges/vignettes/gallery.html) are some examples from `ggridges`. It seems that no easy way to show Y ticks in the ridge plots from `ggridges`
