### ISSUE TITLE
why I loss half of my genes when ScaleData?

### ISSUE THREAD

**Issue by FionaMoon** [satijalab/seurat#5334]
Hi,
I got some trouble, when I do the following command and I got warning like that 
`DotPlot(object = data,assay = "RNA", features = unique(stage_marker$Proerythroblast))`
> Warning: Found the following features in more than one assay, excluding the default. We will not include these in the final data frame: HBG2, HBB, RPS6, RPLP1, TFRC, TPT1, RPL8, GNB2L1, AHSP, EEF2, RPS4X, RPL11, RPL37A, FTL, HBG1, PRDX2, RPL3, RPL30, RPS8, BLVRB, ACTB, RPS5, RPS11, RPS18, RPL18
Error in FetchData(object = object, vars = features, cells = cells) : 
  None of the requested variables were found (10 out of 25 shown): HBG2, HBB, RPS6, RPLP1, TFRC, TPT1, RPL8, GNB2L1, AHSP, EEF2

 I'm very sure these genes are in my data and I back to check my Seuratobject .
Then ,I found my data has 8402x5745 . But my scale data only has 3000x5745.
Why this happen and what should I do to solve this problem?

 Thank you for you help.

**Comment by akstks** [comment]
Hello, 
You probably ran `ScaleData()` with default parameters, which only performs scaling and centering for the highly variable genes (in your case 3000). 

You could try something like this, which will scale all of your genes (n=8402):

`data <- ScaleData(data, assay='RNA', features = rownames(data))` 

This will take longer however, and your object's size will be increased so depending on your memory limit, it may not finish. (For reference a 6 GB Seurat object [20000x50000] turned into 15 GB in my case).

You could also explicitly state which genes you want to include in the scaling. 
For example:
If `var.features` is an object containing your 3000 var.genes you can make an extra object containing the above genes that popped up in your error, concatenate and pass these to `ScaleData()`

`extra.features <- c('HBG2', 'HBB', 'RPS6', 'RPLP1', 'TFRC', 'TPT1', 'RPL8', 'GNB2L1', 'AHSP', 'EEF2')`
`final.features <- c(var.features, extra.features)`
`data <- ScaleData(data, assay = 'RNA', features = final.features)`

Best of luck!

**Comment by FionaMoon** [comment]
I've solved this problem, thank you so much!

**Comment by FionaMoon** [comment]
I have an another try by using `data <- FindClusters(data, resolution = c(0.2))`  instead of
 `data <- FindClusters(data, resolution = c(seq(0,1.4,0.2)))`
then , suprisingly, `DotPlot(object = data,assay = "RNA", features = unique(stage_marker$Proerythroblast))` work well.
So the warning means I shouldn't set more than one resolution ?
> Warning: Found the following features in more than one assay

**Comment by timoast** [comment]
This should not have anything to do with the clustering resolution. You should make sure that you're using the correct assay to generate the plot (eg, RNA vs SCT vs integrated). Some features may be present in multiple assays.
