### ISSUE TITLE
Bug when running integration

### ISSUE THREAD

**Issue by kelvinlee760948065** [satijalab/seurat#5337]
##---------------------------------------------------------------------------------
seurat_list <- SplitObject(seurat_obj,split.by="orig.ident") %>%
  lapply(function(x){
    x %>% NormalizeData() %>%
      FindVariableFeatures(selection.method="vst",nfeatures=2000) %>%
      ScaleData(features=rownames(seurat_obj),
                vars.to.regress=c("nFeature_RNA", "nCount_RNA"))
    })

#CCA integration

seurat_obj <- FindIntegrationAnchors(object.list=seurat_list,
                                     anchor.features=2000)

seurat_obj <- IntegrateData(anchorset = seurat_obj,dims = 1:30)
##---------------------------------------------------------------------------------

There is an error while running FindIntegrationAnchors:
##---------------------------------------------------------------------------------
......
  |++++                                              | 6 % ~01h 44m 15s  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 1467 anchors
Filtering anchors
        Retained 296 anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 69 anchors
Filtering anchors
        Retained  anchors
Error in `[.data.frame`(anchor.df, , 2) : undefined columns selected
##---------------------------------------------------------------------------------

Do you know what's the matter with my codes?

**Comment by kelvinlee760948065** [comment]
I ran the same script, it returned different results:
![3f2795cb808940ff7b36d6f27f73048](https://user-images.githubusercontent.com/71078929/143858964-2f0f3662-eed9-4668-a99c-0e5e1c07196d.png)
![5c55a6ba54917715aee263d7c9d817f](https://user-images.githubusercontent.com/71078929/143858981-9acd5d86-d91d-4b88-b682-553081784f9f.png)

**Comment by kelvinlee760948065** [comment]
I tried to run FindIntegrationAnchors in small set of seurat objects:
![3f2795cb808940ff7b36d6f27f73048](https://user-images.githubusercontent.com/71078929/143861240-630aff45-c880-47d2-aafb-348c1aba5a11.png)
![5c55a6ba54917715aee263d7c9d817f](https://user-images.githubusercontent.com/71078929/143861268-492aef8a-9889-480c-8f06-0dd18a2e0829.png)
at the first time I can run the script successfully, but at the second time, it fails.

**Comment by torkencz** [comment]
Hi. Interesting. I think it fails because you retain 0 anchors. I would run it with a different dataset (maybe more cells) where you can anchor the object list together. I can reopen this if that doesn't work.

**Comment by kelvinlee760948065** [comment]
您的邮件我已收到，但如果重要通知请以我亲自回复收到为准！感谢！
