### ISSUE TITLE
Cluster cells based on certain set of genes

### ISSUE THREAD

**Issue by sameehan2301** [satijalab/seurat#5338]
Hello all,
I hope everyone is doing good. I wanted to know whether it is possible to cluster some cells together with a predefined set of genes? I have a set of genes (around 300) that I know are different between my study groups. Therefore, I was wondering whether there is any method of using these genes to separate a few clusters of cells that show differences in the expression of these genes?

Maybe some other method of analysis (other than Seurat) would help me do this?
Please help!
Thank you,
Regards,
Sam.

**Comment by saketkc** [comment]
Most of the downstream tasks in Seurat depend on the set of variable features. You can define your set of variable features as:
```r
VariableFeatures(object) <- c("gene1", "gene2", .., "gene300")
```
