### ISSUE TITLE
Is there any way to correct or normalize sequencing depth?

### ISSUE THREAD

**Issue by hansong798** [satijalab/seurat#5340]
Hello, seurat team,

I integrated two different 10X single cell RNA-seq dataset which were published.
When I looked at nCount of dataset, first group and second group have similar total counts, but third one looks like strongly different.
first group and second group is from same one dataset but third box is from another. 
So, when i run FindMarkers, there is no DEGs between first and second group but too many DEGs between first and third group.

![image](https://user-images.githubusercontent.com/85104781/143987671-68d1a079-1d04-49e2-a9f9-2fa488498f02.png)

I guess this would be caused by sequencing depth.
So i tried to correct this effect by "vars.to.regress = c("nCount_RNA")"  argument in ScaleData function.

`data<- ScaleData(data, vars.to.regress = c("nCount_RNA"), features = rownames(data))`

My question is,
1. Is this right way to correct sequencing depth? or is there other right way to resolve this problem?

2. If this is right, how can i use this regressed out data for FindMarkers function?

**Comment by saketkc** [comment]
I would recommend running the SCTransform [workflow](https://satijalab.org/seurat/articles/integration_introduction.html) for integration and  using the`data` slot of SCTransform to perform DE. The data slot of SCTransform stores log of  corrected counts (effect of sequencing depth has been regressed out). This would reduce the number of false positives, but given the way the current version of SCTransform corrects counts (by replacing it with median sequencing depth at the correction depth), there might still be a few left. We have an update coming that address this caveat, soon. 

Feel free to reopen with any follow up questions.
