### ISSUE TITLE
How to get each gene counts in a cluster

### ISSUE THREAD

**Issue by Jane-96-45** [satijalab/seurat#5342]
Hi everyone!
I'm working on analyzing clusters and I wonder if there is anyway to get the list of gene counts in each cluster.
I know that I can get the gene counts with VlnPlot, but it is only for one gene in each cluster. 
```
p <- VlnPlot(object = object ,  features = "gene")
p2 <- p$data %>% group_by(ident) %>% summarize(counts = sum(gene, na.rm = TRUE))
```
For example, if I have 200 genes in cluster 1, is there any way that I can get a data frame with each gene and its count in this cluster?
Or how can I do a loop with this code？I‘m bad at coding so I don't know if it is possible.
I would like to get a result similar like this, or maybe just one cluster:
```
              cluster0   cluster1   cluster2  
 gene1          783.     2331.        234.
 gene2          122.     2732.        661.
 gene3          983.     1752.       2331.
 .......
```

**Comment by mhkowalski** [comment]
Hi, the function you are looking for is ```AverageExpression()```. For instance you can do, 

```AverageExpression(object, features= genes, group.by="ident", slot = "counts" )```

The default here is to use the data slot, so if you want the raw counts than you can change to ```slot="counts"```, as above.
