### ISSUE TITLE
What is the difference between MapQuery(FindTransferAnchors) and IntegrateData(FindIntegrationAnchors) ?

### ISSUE THREAD

**Issue by weipingz** [satijalab/seurat#5347]
What is the difference between MapQuery(FindTransferAnchors) and IntegrateData(FindIntegrationAnchors) ? 
If I have two data, and I integrated them, can I use MapQuery to verify the results of integration ?

**Comment by timoast** [comment]
The `MapQuery()` function runs `TransferData()`, `CorrectEmbeddings()`, and `ProjectUmap()` (see https://github.com/satijalab/seurat/discussions/5320). This can be used to transfer categorical and/or continuous data from a reference to query dataset, and to project the query onto an exiting reference UMAP.

`IntegrateData()` corrects the expression matrix across multiple different datasets.

You can find out more about these methods in this paper: https://doi.org/10.1016/j.cell.2019.05.031

> If I have two data, and I integrated them, can I use MapQuery to verify the results of integration ?

No, you can't use `MapQuery()` to validate integration results, the methods are essentially the same.

**Comment by weipingz** [comment]
> The `MapQuery()` function runs `TransferData()`, `CorrectEmbeddings()`, and `ProjectUmap()` (see #5320). This can be used to transfer categorical and/or continuous data from a reference to query dataset, and to project the query onto an exiting reference UMAP.
> 
> `IntegrateData()` corrects the expression matrix across multiple different datasets.
> 
> You can find out more about these methods in this paper: https://doi.org/10.1016/j.cell.2019.05.031
> 
> > If I have two data, and I integrated them, can I use MapQuery to verify the results of integration ?
> 
> No, you can't use `MapQuery()` to validate integration results, the methods are essentially the same.

Thank you very much for your reply. I may not have made myself clear. Firstly, I integrated two data (FindIntegrationAnchors).  And then,  I subset each data from integrated result. I use the original RNA assay of each data and use MapQuery to get the  corresponding cluster's (dataA_cluster0 and dataB_cluster0) percentage of the number of cells. For example, DataA_cluster0 contain 0.9 DataB_cluster0 and 0.1 DataB_cluster3. If DataA_cluster0 contain 0.3 DataB_cluster0 and 0.7 DataB_cluster3, we We think the result of this integration is bad. Therefore,  I need to change the parameters of integration. Do you think this is feasible ?
