### ISSUE TITLE
the meaning of the options for DoHeatmap

### ISSUE THREAD

**Issue by sophienl** [satijalab/seurat#5355]
Hi,
what are the "data", "raw.data" for slot parameter in DoHeatmap? also how can I set the range for expression bar, e.g [-3, 3]? otherwise, for different set of genes, the coloring range will be different.

**Comment by mhkowalski** [comment]
This merely controls which slot you are plotting (the raw counts vs normalized data versus the scaled data). The default is scale data, which is the data after centering and scaling each gene by its standard deviation.  If you want to decrease the range of scale data you can set the scale.max parameter in ScaleData (see #1166 ), as the default is 10.
