### ISSUE TITLE
Using custom gene set for integration and clustering

### ISSUE THREAD

**Issue by XUTONG-GONG** [satijalab/seurat#5359]
Hi Seurat Team,
I was hoping to perform clustering analysis on my dataset using a custom gene set instead of the most variable features. Is it correct to use this custom gene set for both rPCA integration and clustering? Or should I still use the most variable features for integration and the custom gene set for clustering? 
I've tried the second option by setting features=custom.gene.set in runPCA, but the resulting UMAP looks very similar to the plot when I used all genes for clustering. 
Thanks in advance!

**Comment by timoast** [comment]
Yes you can use a custom set of genes, does not need to be most variable genes
