### ISSUE TITLE
UMAP non-determinism/variation

### ISSUE THREAD

**Issue by sejiro** [satijalab/seurat#536]
Looks like UMAP is not correctly picking up on the set seed of the R environment. 
Additionally it does not seem that supplying a random_state=x parameter to the function call provides fidelity. 

See the following issue: https://github.com/lmcinnes/umap/issues/27

**Comment by mojaveazure** [comment]
I wouldn't expect UMAP to be able to pick up R's seed, as these are different environments. Running UMAP within R uses the [reticulate](https://cran.r-project.org/web/packages/reticulate/index.html) package to call UMAP's Python code from within R. Reticulate doesn't automatically pass R's random seed to Python, so there's no reason to expect UMAP to pick up R's random seed. However, this would be a good thing to allow users to set.

As for the issue with `random_state`, that seems to be an issue with UMAP itself, not Seurat.

**Comment by sejiro** [comment]
I wasn't sure about the implementation and was assuming that the seed should be passed over automatically or could be set in the function call with random_state. Glad to see there's nothing unexpected occurring. Thank you for the clarification.
