### ISSUE TITLE
VlnPlot not accurately recapitulating correct cells from specified identities and cluster

### ISSUE THREAD

**Issue by ammawla** [satijalab/seurat#5360]
Had a dataset in which I wanted to generate violin plots of only two of many identities. More than one clustering approach was run, and the identities of relevance were set through 'integrated_snn_res.0.9'.

The line of code below did not accurately pull the cells associated with the identities, determined after counting the number of points in Illustrator and comparing against the total number of cells between the two. 
 
VlnPlot(object = full.object, features = gene[i], group.by = 'integrated_snn_res.0.9', idents=c('0','2'))

This occurred using Seurat v4.0.5. 

Took a look at the documentation and was unsure what would cause the discrepancy. 

Working solution was to subset the full object and run VlnPlot without specifying identities or clusters, and this appears to have solved the issue.

**Comment by liuxl18-hku** [comment]
There possibly be multiple reasons for some dots are missed on the plot, for example, which assay are you using for the plotting, is there any NAs in the plotting data.

Not familiar with AI, but we can use `ggplot_build()` of tidyverse package to extract the exact visualization data (e.g. coodinates) of geom_points() used in `VlnPlot()`

```r
library(SeuratData)
InstallData("pbmc3k")
data("pbmc3k")

tmp.g <- VlnPlot(
  pbmc3k,
  features = "ITGB2",
  pt.size = 1,
  group.by = "seurat_annotations",
  slot = "data",
  combine = FALSE
)

# as we set combine = FALSE in the VlnPlot(), the tmp.g will be a list with the length equal to the number of features you want to plot, here is 1
gg_obj <- tmp.g[[1]]
# > class(gg_obj)
# [1] "gg"     "ggplot"
library(tidyverse)
gg_build <- ggplot_build(gg_obj)
# visual data for geom_violin() and geom_points()
> length(gg_build$data)
[1] 2
# visual data for geom_points()
head(gg_build$data[[2]])

# from here you can check x and y coordinates to see whether all dots are plotted
#      fill             y        x PANEL group shape colour size alpha stroke
# 1 #D39200  1.370958e-05 2.082168     1     2    19  black    1    NA    0.5
# 2 #00BA38  1.999994e+00 4.332704     1     4    19  black    1    NA    0.5
# 3 #D39200  3.631284e-06 2.066959     1     2    19  black    1    NA    0.5
# 4 #93AA00  1.000006e+00 3.109235     1     3    19  black    1    NA    0.5
# 5 #619CFF  2.000004e+00 7.147347     1     7    19  black    1    NA    0.5
# 6 #D39200 -1.061245e-06 1.617203     1     2    19  black    1    NA    0.5
```

**Comment by ammawla** [comment]
Thank you for this. It shouldn't have been the assay, as the default assay was set to RNA and there were no NA values. I'm going to try your suggested approach on the old results to see what was being missed. However, to the best of my knowledge at this time, it appears it simply wasn't utilizing all the cells from the two clusters. Just not sure where the disconnect was within the function.

> There possibly be multiple reasons for some dots are missed on the plot, for example, which assay are you using for the plotting, is there any NAs in the plotting data.
> 
> Not familiar with AI, but we can use `ggplot_build()` of tidyverse package to extract the exact visualization data (e.g. coodinates) of geom_points() used in `VlnPlot()`
> 
> ```r
> library(SeuratData)
> InstallData("pbmc3k")
> data("pbmc3k")
> 
> tmp.g <- VlnPlot(
>   pbmc3k,
>   features = "ITGB2",
>   pt.size = 1,
>   group.by = "seurat_annotations",
>   slot = "data",
>   combine = FALSE
> )
> 
> # as we set combine = FALSE in the VlnPlot(), the tmp.g will be a list with the length equal to the number of features you want to plot, here is 1
> gg_obj <- tmp.g[[1]]
> # > class(gg_obj)
> # [1] "gg"     "ggplot"
> library(tidyverse)
> gg_build <- ggplot_build(gg_obj)
> # visual data for geom_violin() and geom_points()
> > length(gg_build$data)
> [1] 2
> # visual data for geom_points()
> head(gg_build$data[[2]])
> 
> # from here you can check x and y coordinates to see whether all dots are plotted
> #      fill             y        x PANEL group shape colour size alpha stroke
> # 1 #D39200  1.370958e-05 2.082168     1     2    19  black    1    NA    0.5
> # 2 #00BA38  1.999994e+00 4.332704     1     4    19  black    1    NA    0.5
> # 3 #D39200  3.631284e-06 2.066959     1     2    19  black    1    NA    0.5
> # 4 #93AA00  1.000006e+00 3.109235     1     3    19  black    1    NA    0.5
> # 5 #619CFF  2.000004e+00 7.147347     1     7    19  black    1    NA    0.5
> # 6 #D39200 -1.061245e-06 1.617203     1     2    19  black    1    NA    0.5
> ```
