### ISSUE TITLE
Number of dimensions of rPCA for FindIntegrationAnchors()

### ISSUE THREAD

**Issue by liuxl18-hku** [satijalab/seurat#5361]
If we found 10 PCs is capturing dominating variability of reference dataset (say, based on `ElbowPlot()` output), then when we tried to project another query dataset to the reference dataset in the reciprocal pca of finding anchors for integration, is 10 still a good number.

Bascially, I am talking about:

```r
FindIntegrationAnchors(, dims = is_ok_to_use_10_here, normalization.method = "SCT", reduction = "rpca")
```

Thank you very much for your help!

**Comment by yuhanH** [comment]
HI, 
I think it is valid to use top 10 PC for the integration. You can also evaluate the integrated results.
