### ISSUE TITLE
import clusters generated in 10x Genomics Loupe browser

### ISSUE THREAD

**Issue by sdwien** [satijalab/seurat#5365]
Dear Seurat Team,
we have run a 10x Visium experiment, and would like to import information on clusters that were generated manually in Loupe browser (based on spatial characteristics) into Seurat.
I can export from Loupe a list of barcodes and the corresponding (manually assigned) identifiers:

```
barcode,id
AAACATACAGTACC-1,Monocytes
AAACCGTGTCGTGA-1,Monocytes
AAACATACCATTCT-1,Mature Ery
AAACATACTCGCAA-1,Mature Ery
AAACCGTGGCCATA-1,Mature Ery
```
I browsed through several of your vignettes and tutorials but did not find a description of this use case in particular: How can I add this information into the SeuratObject (e.g. after `SCTransform`)?
Many thanks for your suggestions,
best,
Sophia

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can simply use the `AddMetaData` function to add the table you got from Loupe to the object@meta.data slot.  Then use `Idents` function to set the that column as the active identity when you want to perform plotting, DE, etc.

Best,
Sam
