### ISSUE TITLE
Can I use Seurat to identify the specific cell types in stimulation group compared to control group

### ISSUE THREAD

**Issue by liweimingsci** [satijalab/seurat#5366]
I have a stimulation and control single cell RNA-seq data sets. From the manual of Seurat software, what I understand is that stimulation and control groups own the same cell types when doing cell clustering and identifying by Seurat. However, if the stimulation group have its own specific cell type, how can it report this using Seurat? Thanks for your help.

**Comment by torkencz** [comment]
I don't fully understand the question. When comparing a stimulated vs control group the comparison should be in the same general cell types across the two conditions. You can then look at generally conserved markers or cell type specific ones, once you identified corresponding cell types between the conditions.

**Comment by liweimingsci** [comment]
Thanks very much for your reply.
