### ISSUE TITLE
how to subset desired data from FeaturePlot()

### ISSUE THREAD

**Issue by ClarkGregg** [satijalab/seurat#537]
I have a large dataset containing more then ten thousand cells. I ran the whole workflow as demonstrated at the website. Here is the thing, I sub divided T cells into CD4+ and CD8+ respectively, then I used FeaturePlot to plot CD4 gene and CD8 gene to see their corresponding distributions in the two clusters. During my use of FeaturePlot(), I set do.hover = T to interactively explore the data, but I don't know how to extract the cell names(eg. barcode sequences) from the plot. Can anyone help?

Thanks in advanced

**Comment by andrewwbutler** [comment]
If you want to visually select cells in the plot, you can use the `do.identify` option in `FeaturePlot`. The more programmatic option though is to use the `WhichCells` function to return a subset of cell names that meet your selection criteria.
