### ISSUE TITLE
Creating Transparent UMAP plots

### ISSUE THREAD

**Issue by Hsutton157** [satijalab/seurat#5371]
Hello, 
I would like to create UMAPs from seurat and export them with transparent backgrounds.

my current code looks like this

clusterumap<-DimPlot(immune.clean, reduction = "umap", pt.size = .01, cols = col_cluster)+
  theme(legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "transparent",
                                       color = NA))

ggsave("UMAP.png", plot= clusterumap, width=10, height=10,  dpi=300, bg = "transparent")

theme() combined with bg = "transparent" in ggsave normally works to create plots with transparent backgrounds, but I can't seem to get it to work with plots generated by dimplot.
I was wondering if anyone else has seen this problem or know a solution. I'm fairly new to plotting in R

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This appears to be an issue related to patchwork package.  Even though it is only return a single plot in order to get the transparency to work you need to use `&` instead of `+`.  Then running your exact code worked for me.

Best,
Sam

**Comment by Hsutton157** [comment]
That worked!
Thanks so much!
