### ISSUE TITLE
subset and got NA values

### ISSUE THREAD

**Issue by bitcometz** [satijalab/seurat#5372]
hello,
I use the function to subset data based on idents, I did subset but got NA values for chr columns:
code:
```R
cel <- intersect( PRO1@meta.data$Cell.Barcode , rownames(meta) )
ttt  <- subset(x = PRO1, idents = cel, invert = FALSE)
```

before:

![image](https://user-images.githubusercontent.com/13601652/145161113-840751a8-c377-4c84-9059-6f4b006eaee9.png)

After:

![image](https://user-images.githubusercontent.com/13601652/145161069-393d3335-7b98-4dab-a6ec-d79c0e5efb7e.png)

another example:
![image](https://user-images.githubusercontent.com/13601652/145166341-f9c0f870-219b-488b-bacf-ad048fc7ead3.png)

Could you help with this problem?

Thanks !!!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Since you are subsetting on a cell barcode is there are reason by not to use the `cells` parameter in `subset` instead of `idents`?  Does the same error occur if you use the `cells` parameter?

Best,
Sam

**Comment by bitcometz** [comment]
Thanks !!! @samuel-marsh 

After I add the code:
```
PRO1 <- RenameCells(PRO1, new.names = PRO1@meta.data$Cell.Barcode)
```

Both `cells` and `idents` work well .
