### ISSUE TITLE
MapQuery unable to exit when wrong input is inputted

### ISSUE THREAD

**Issue by Chengwei94** [satijalab/seurat#5373]
When using the mapquery function with wrong inputs such as not returning umap model in the previous step or putting the wrong columns in the refdata variable, the function just shows the error and the function get stuck there, instead of ending the function.  I have to kill my R process everytime to exit.

**Comment by torkencz** [comment]
Can you provide more information on the session you are running and maybe the code as well.

**Comment by yuhanH** [comment]
We also notice that if you put wrong input into `MapQuery`, it will be ending normally. We are working on it.

**Comment by yuhanH** [comment]
hi @Chengwei94 
In the latest version seurat (4.0.6), when you put wrong input, `MapQuery` should just return the error info.
