### ISSUE TITLE
Cell cycle gene regression whilst performing RPCA integration

### ISSUE THREAD

**Issue by rcrueda** [satijalab/seurat#5374]
In line with this issue  #2177, I am trying to perform integration with RPCA at the same time as cell cycle regression but I am not sure in which scaling steps cell cycle regression should happen.

My code is as follows:

seurat.list <- SplitObject(seurat, split.by = "orig.ident")

seurat.list <- lapply(X = seurat.list, FUN = function(x) {
x <- NormalizeData(x)
x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 3000)
x <- CellCycleScoring(x, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
})

features <- SelectIntegrationFeatures(object.list = seurat.list, nfeatures = 2000)
seurat.list <- lapply(X = seurat.list, FUN = function(x) {
x <- ScaleData(x, features = features, verbose = FALSE, **vars.to.regress = c("S.Score", "G2M.Score")**)
x <- RunPCA(x, features = features, verbose = FALSE)
})

immune.anchors <- FindIntegrationAnchors(object.list = seurat.list, anchor.features = features, reduction = "rpca")
immune.combined <- IntegrateData(anchorset = immune.anchors)

DefaultAssay(immune.combined) <- "integrated"

immune.combined <- ScaleData(immune.combined, verbose = FALSE , **vars.to.regress = c("S.Score", "G2M.Score")**)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)

immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:20)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:20)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)

DefaultAssay(immune.combined) <- "RNA"

seurat <- immune.combined
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat, features = rownames(seurat))

I have 3 different scaling steps. Is it correct to use CC gene regression before integration and before cell clustering and not in the RNA compartment?

Would it otherwise be fine to do CC regression only after integration and before cell clustering? 

Thanks!

**Comment by torkencz** [comment]
Personally, I would do cell cycle regression in the ScaleData step on each object, before integration, not after on the immune combined.
