### ISSUE TITLE
Adding geom to a grouped VlnPlot 

### ISSUE THREAD

**Issue by simonmfr** [satijalab/seurat#5375]
Hi,

when adding a geom to a grouped VlnPlot post-hoc, changes only seem to apply to the last group/column. 

Here is the code:

```r
    VlnPlot(seurat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rps"), ncol = 4, group.by = "brain_region", pt.size = 0.0) + geom_jitter(size= 0.1, alpha = 0.1)
```

![Rplot01](https://user-images.githubusercontent.com/70199914/145202083-d96b2ec1-47c1-4b9a-9813-afb373b03c34.png)

Any advice is appreciated!

```r
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] DropSeq.util_2.0   Matrix_1.3-4       SeuratObject_4.0.3 Seurat_4.0.5       data.table_1.14.2  forcats_0.5.1      stringr_1.4.0     
 [8] dplyr_1.0.7        purrr_0.3.4        readr_2.1.0        tidyr_1.1.4        tibble_3.1.6       ggplot2_3.3.5      tidyverse_1.3.1

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  The reason is because Seurat uses patchwork package to arrange multiple plots.  Instead of using the `+` from ggplot2 simply use `&` when adding post plot theming.

Best,
Sam

**Comment by simonmfr** [comment]
Perfect, thanks a lot.
