### ISSUE TITLE
NA values for mitochondrial gene percentage 

### ISSUE THREAD

**Issue by zahramesri** [satijalab/seurat#5376]
I am running Seurat on publicly available dataset of ~400k cells. More than 80% of the cells are returned as NA when I use percentageFeatureSet(object, pattern = "^MT-").
How should I interpret these result? Does this mean the 80% of cells are of poor quality or have no mitochondrial content? 

Any help would be greatly appreciated. 
Zahra

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Returning NA is strange.  Do you have any NA values in the input matrix or for any of the gene names?  When no genes matching pattern are found for given cell Seurat returns 0 values and not NA.  You can test this by running pattern that mismatches species:

```
library(Seurat)

pbmc <- pbmc3k.SeuratData::pbmc3k.final

# Use wrong pattern for human samples
pbmc <- PercentageFeatureSet(object = pbmc, pattern = "^-mt", col.name = "test")

head(pbmc@meta.data, 5)
               orig.ident nCount_RNA nFeature_RNA seurat_annotations percent.mt RNA_snn_res.0.5 seurat_clusters test
AAACATACAACCAC     pbmc3k       2419          779       Memory CD4 T  3.0177759               1               1    0
AAACATTGAGCTAC     pbmc3k       4903         1352                  B  3.7935958               3               3    0
AAACATTGATCAGC     pbmc3k       3147         1129       Memory CD4 T  0.8897363               1               1    0
AAACCGTGCTTCCG     pbmc3k       2639          960         CD14+ Mono  1.7430845               2               2    0
AAACCGTGTATGCG     pbmc3k        980          521                 NK  1.2244898               6               6    0

```

Best,
Sam

**Comment by zahramesri** [comment]
All MT genes do exist in my data.

**Comment by zahramesri** [comment]
Update: The data was not downloaded intact. Thank you for your help!

**Comment by TeodoraTockovska** [comment]
> Update: The data was not downloaded intact. Thank you for your help!

Hi, could you explain by what you mean that it wasn't downloaded intact? I am running into the same issue.

**Comment by ijeomameremikwu** [comment]
@zahramesri I am also running into the same issue, as I get NA values after doing x[["percent.mt"]] <- PercentageFeatureSet(x, pattern = "^mt-"). How did you fix this?

**Comment by TeodoraTockovska** [comment]
@ijeomameremikwu I wanted to provide an update on the issue. The reason why there are NaN values is because there are 0 values for the nCount slot, and there are 0 mitochondrial gene counts for the barcode. The calculation for the mitochondrial percentage is (x$nCount_RNA/x$percent.mt)*100. If the numerator and denominator are both 0, then that results in NaN. I suggest removing those barcodes after the mitochondrial percentage calculation.

**Comment by ijeomameremikwu** [comment]
@TeodoraTockovska yes thank you! I realized that there was no nCount_RNA column. I fixed this issue, by first calculating the nCount_RNA with this x[["nCount_RNA"]] <- colSums(x = x, slot = "counts"), before x[["percent.mt"]] <- PercentageFeatureSet(x, pattern = "^mt-"). Thanks.
