### ISSUE TITLE
Unable to convert ADT assay from Seurat object to h5ad 

### ISSUE THREAD

**Issue by aditisk** [satijalab/seurat#5377]
Hello Seurat team,

I am trying to convert my Seurat object to h5ad using SeuratDisk (converting to h5Seurat as an intermediate file and then to h5ad). I was able to successfully convert the RNA assay counts but I would like to do the same with ADT counts.

I tried to change the DefaultAssay to ADT before running the conversion functions but that doesn't seem to work. Is there a way I could incorporate both RNA and ADT counts in the h5ad file ?

Thanks

**Comment by torkencz** [comment]
At the moment the best solution would be to create a separate assay that contains the concatenated RNA and ADT counts assays and then convert.
