### ISSUE TITLE
How to extract part of gene matrix that has been used in clustering?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#538]
Hi
I have used 15 dimensions in FindClusters(). Is it possible to fetch gene matrix with cells and genes that account for those 15 dimensions only? I would like to get "regressed-out" matrix.

**Comment by andrewwbutler** [comment]
The "regressed-out" matrix (the matrix resulting from running `ScaleData`  with variable(s) specified in `vars.to.regress` is stored in `object@scale.data`.  However, if you're using 15 dimensions it sounds like you're using the results of something like PCA for clustering. This matrix can be accessed with `GetCellEmbeddings`.
