### ISSUE TITLE
[Spatial] Image object removal after subsetting. Fetch all images coordinates

### ISSUE THREAD

**Issue by simoncmo** [satijalab/seurat#5380]
I run into an issue when subsetting merged spatial transcriptomics objects. My workflow involves first merging all the slices to create the graph, then subset/splitting it into groups of Seurat objects. The issue I have so far is the image object and keys remain in the new objects and when using `SpatialPlot` family functions, the slices that got subsetted out will still be plotted but are empty plots.
My current workaround is to set the `images` parameter in `SpatialPlot` functions but would love to know if there’s a way to just remove them completely.
I tried `Key<-` but there’s no implementation for the Seurat object itself. 

Also a related but different question. 
Is there a function or `FetchData` implementation to extract the coordinate information from multiple images?
`FetchData(obj, var = ‘imagerow’)` doesn’t seem to work for me.
`FetchData(obj var = ‘{key}_imagerow’)` would work to find the coordinate for that particular slice, but spots from ALL other slices in the object will be returned as `NA`. Ideally, I would love to have just one "imagerow" column that have all the coordinated information.
The goal I have in mind is to grab a table with features + coordinates variables (e.g. ‘imagerow’, ’imagecol’) in column and barcode of all spots in the Seurat object in rows.

Thank you!!

Simon

**Comment by torkencz** [comment]
Hi, unfortunately as far as I know the best way of currently doing this is to set the images parameter.

**Comment by simoncmo** [comment]
Found out I can fix the empty image issue by removing them from the `@images` slot
Creating this snippet when dealing with the missing `medium_umi` slot issue in SCTModel object but that's a separate story.

Currently using this snippet to clean the `images` slot in case anyone ever needs this.
Hope this can be handled in `SplitObject` or `subset` so this won't be need in the future. 
Thanks!
```
# Cleaning empty objects
# General purpose
clean_seurat_obj_list = function(obj_list, attirbute_to_check){
	if(missing(attirbute_to_check)) {stop("Need attributes to check for cleaning")}
	# Object type
	obj_type = class(obj_list[[1]])[[1]]

	# Count
	obj_size = map(obj_list, function(object){
		nrow(slot(object, attirbute_to_check)) 
	}) %>% unlist 

	# Remove empty
	if(length(obj_size ==0)  != 0 ){
		message(str_glue('Removing {length(obj_size ==0)} empty object from the {obj_type} object list'))
		obj_list = obj_list[obj_size!=0]
		message(str_glue('{length(obj_list)} {obj_type} object(s) left'))
	}
	obj_list
}


# For images slot
clean_seurat_image_list = function(img_list){
	clean_seurat_obj_list(obj_list = img_list, attirbute_to_check = 'coordinates')
}

# API to clean empty Suerat image
fix_seurat_image = function(obj){
	# Check first 
	if(is.null(Images(obj))){
		message('No Images in this obj. Not a ST object')
		return(obj)
	}

	# clean image
	obj@images = clean_seurat_image_list(obj@images)
	return(obj)
}

# To use. obj is the seurat obj to clean.
obj_fixed = fix_seurat_image(obj)

```
