### ISSUE TITLE
Spatial analysis: Comparing gene expression between biological replicates

### ISSUE THREAD

**Issue by LucyTe** [satijalab/seurat#5383]
Hi,

I am having difficulty working out best practices for the following:

1. I have 10X Visium mouse brain data for 3 different conditions - 3 replicates per condition and two tissue sections per mouse. I am trying to understand the best way to approach gene expression analysis given this data.

2. As an extension of Q1, a few samples harbour minor damage and the capture area for each sample differs slightly i.e. some samples capture regions were smaller/larger; e.g. some samples did not capture the entire cerebellum. I'm unsure the best way to deal with this and appreciate any input.

The difference in the number of spots captured is mostly similar between samples with the largest difference being around 1000 spots.

So far, I have run a standard integration pipeline using SCT, combining all samples. Running FindAllMarkers on the integrated object did well identifying most major anatomical structures. I tried subsetting the data to include a few clusters defining known regions (e.g. thalamus) that were captured in all samples, and then ran FindAllMarkers on this subset data, however the results did not seem meaningful.

I am having alot of trouble understanding how best to proceed and greatly appreciate any guidance. Thanks for making such a great package!

**Comment by mojaveazure** [comment]
I'm not sure what your issue is; however, I would recommend using the standard workflow `NormalizeData` &rarr; `FindVariableFeatures` &rarr; `ScaleData` instead of `SCTransform` for Visium data
