### ISSUE TITLE
Setting higher dpi/resolution in rasterized plots

### ISSUE THREAD

**Issue by rdchow** [satijalab/seurat#5388]
I really like the new raster=TRUE setting in DimPlot/FeaturePlot, but many of my colleagues are wondering if we could increase the resolution/dpi of the resulting rasterized points. 

My understanding is that DimPlot uses the geom_scattermore() function, which has a default pixel setting of (512,512). Could you implement another setting into DimPlot that allows us to set the pixel dimensions to something higher, which gets passed to geom_scattermore()? Thanks!

**Comment by samuel-marsh** [comment]
@rdchow I think this makes lot of sense!!  I just submitted PR to the devs that would add this parameter where needed #5391.

Best,
Sam

**Comment by saketkc** [comment]
This should be addressed by #5392  and is now in the develop branch. You can see the installation instructions [here](https://satijalab.org/seurat/articles/install.html)
