### ISSUE TITLE
Azymuth PBMC reference vs pbmc_multimodal.h5seurat reference

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5393]
Hi,

is the Azymuth PBMC reference different from the pbmc_multimodal.h5seurat reference ?

I loaded the Azymuth ref and the object shows
> reference
$map
An object of class Seurat 
5228 features across 36433 samples within 2 assays 
Active assay: refAssay (5000 features, 0 variable features)
 1 other assay present: ADT
 2 dimensional reductions calculated: refUMAP, refDR
$plot
An object of class Seurat 
1 features across 24760 samples within 1 assay 
Active assay: RNA (1 features, 0 variable features)
 1 dimensional reduction calculated: refUMAP

while pbmc_multimodal.h5seurat shows the following
> reference
An object of class Seurat 
20957 features across 161764 samples within 2 assays 
Active assay: SCT (20729 features, 5000 variable features)
 1 other assay present: ADT
 6 dimensional reductions calculated: apca, aumap, pca, spca, umap, wnn.umap

Thanks

**Comment by yuhanH** [comment]
HI
Right.  `pbmc_multimodal.h5seurat` and  Azimuth mapped reference are not exactly the same. 
In order to speed up the Azimuth mapping, we downsampled  `pbmc_multimodal.h5seurat` to generate the Azimuth mapped reference. 
If you map your cells locally,  you would better use `pbmc_multimodal.h5seurat` .

**Comment by mimisikai** [comment]
recurring vector memory exhausted error when loading pbmc_multimodal.h5seurat. Working on a 16GB laptop, can you advice? Thanks.

**Comment by yuhanH** [comment]
hi @mimisikai 
Maybe you can just load SCT assay from the object.
