### ISSUE TITLE
Unbalanced number of DEG between conditions

### ISSUE THREAD

**Issue by Maggi-Chen** [satijalab/seurat#5394]
Hi, I have been working on differential expression gene analysis and found that there are always more down-regulated genes than up-regulated genes.
I have two samples, one is control and the other is treated. They are sequenced separately, so I assume there are some batch effects. I integrated these two samples as guided in the tutorial:
```
pbmc_merge = merge(pbmc_n262d, y=c(pbmc_n26v), add.cell.ids=c("NP26_T",'NP26_C'), project="PBMCMerge")
pbmc_merge.list <- SplitObject(pbmc_merge, split.by = "Info")
pbmc_merge.list <- lapply(X = pbmc_merge.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = pbmc_merge.list, nfeatures = 3000)
pbmc_merge.list <- PrepSCTIntegration(object.list = pbmc_merge.list, anchor.features = features)
immune.anchors <- FindIntegrationAnchors(object.list = pbmc_merge.list, normalization.method = "SCT",
                                         anchor.features = features)
immune.combined <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")
immune.combined <- RunPCA(immune.combined, verbose = FALSE, npcs = 50)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:50)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:50)
immune.combined <- FindClusters(immune.combined, resolution = 0.4)
```

And then I used FindMarkers to compute DEGs between two conditions:
```
Idents(immune.combined)='Info'
deg1=FindMarkers(immune.combined, ident.1 ='treatment', ident.2 = 'control', assay = 'RNA', min.pct=0.5)
#deg.all=FindMarkers(immune.combined, ident.1 ='treatment', ident.2 = 'control', assay = 'RNA', min.pct=0.2, logfc.threshold = 0)
```
This leads to 618 up-regulated genes and 1447 down-regulated genes. I tried subset to each cluster and always observed more down-regulated genes. (I also tried using 'SCT' assay, and there were 9 up-regulated and 1604 down-regulated DEGs.) Other tests (bimod, roc, DESeq2) returned more down-regulated DEGs as well.

I set logfc.threshold as 0 and min.pct as 0.2 to check the folder change of all expressing genes. Based on the distribution of log2FC, it seems like in general, most genes have lower expression level in treatment than control sample (the peak is shifting left from 0).
![image](https://user-images.githubusercontent.com/38887640/146360709-16e664f4-8baf-4bf6-ad90-6f888d5bd467.png)

I computed the average expression level in each sample with AverageExpression and made a scatterplot with the average expression level in control and treatment. There are too many dots so it may be hard to tell, but the regression line suggests that overall the expression levels in control is higher than in treatment.
```
test=AverageExpression(immune.combined, assays = 'RNA')
test=data.frame(test$RNA)
ggplot(test,aes(x=control, y=treatment))+geom_point()+xlim(0,150)+ylim(0,150)+
  geom_smooth(method = 'lm')+theme_bw()+xlab('Expression in Control')+  ylab('Expression in Treatment')
```
![image](https://user-images.githubusercontent.com/38887640/146361388-717df564-2bb1-4049-a847-301700b4ed11.png)

So, I think this might be the reason why I got more down-regulated DEGs. Since the DEGs were computed from the RNA counts, I don't think normalization or scale would help. Is there anything I should do to correct the batch effect and get balanced DEGs?

Thanks,
Maggi

**Comment by torkencz** [comment]
Hi, this is difficult. From what I am seeing the number of DEGs you are getting looks okay. Also you are getting upregulated genes so that is encouraging as well. You can experiment with regressing the two conditions, but that would risk losing relevant genes. I would quantify what percent of genes have a significantly lower expression and the distribution of expression differences to see if it is truly universal. Also, if you have multiple cell types I would look into findConservedMarkers. These are my primary suggestion regarding this, can reopen if need be.

**Comment by yzhan937** [comment]
Hi Maggi, I meet the same issue with my two-condition scRNA dataset. Do you have any idea now about how to correct the batch effect?
