### ISSUE TITLE
Seurat package ScaleData

### ISSUE THREAD

**Issue by BhaktiDwivedi** [satijalab/seurat#540]
Hi,

I am using your R package 'Seurat' to analyze scRNA-seq data from lung cancer cell line. The tutorials have been very helpful in understanding the scRNA-seq workflow.

I have few questions I was wondering if you can please help me provide your insight on the use of ScaleData function.

Basically,
    I have filtered cells by library size, # of expressed features, and proportion of mitochondrial reads
    I have filtered genes with no expression or low expression counts among cells.
    I have normalized the data using scran R package

I want to regress out the data on the cell cycle and mitochondrial genes using your ScaleData functionality. Here, can I use scran normalized data as an input in ScaleData function to scale and remove unwanted source of variation? Is there any way I can input additional cell cycle genes (e.g, cell cycle process) to regress out, for which I may not know the G1/S or G2/M phase genes as you have shown in your example (https://satijalab.org/seurat/cell_cycle_vignette.html) to compute the cell cycle phase scores?

Appreciate your help and feedback. Thank you.

Regards,
Bhakti

**Comment by andrewwbutler** [comment]
The `ScaleData` function operates on the `object@data` slot so you could fill that slot with the results of scran normalization. 

The `AddModuleScore` function can be  used to calculate supervised module scores for any gene list. The `CellCycleScoring` function uses this under the hood if you want an example of how to use it.
