### ISSUE TITLE
FindSubCluster in Seurat

### ISSUE THREAD

**Issue by Pedramto89** [satijalab/seurat#5405]
I want to find the subclusters in one of my clusters of interest; I found this option but shows some error while I'am trying to run it.

**Code:**

```{r}
FindSubCluster(
  datasets.integrated,
  "1",
  graph.name = "integrated_nn",
  subcluster.name = "EC",
  resolution = 0.5,
  algorithm = 1)
```

**Error:**

Error in WhichCells.Seurat(object = object, idents = cluster) : 
  Cannot find the following identities in the object: 1

**Comment by liuxl18-hku** [comment]
A quick check would be `table(Idents(datasets.integrated))` to see whether "1" is one of the major cluster ids or not.

**Comment by Pedramto89** [comment]
It finally worked. I added the graph.name to the FindCluster command. Now, I have two subclusters in one of my clusters of interest. How can I get the differentially expressed genes between these two subclusters?
![EC_clusters](https://user-images.githubusercontent.com/85902042/146666495-45cdc517-85a0-49b9-88ea-ae443401943e.png)

**Comment by mhkowalski** [comment]
Hi, 

You can do use the `FindMarkers` command, specifying the names of the subclusters you would like to compare and the name of the variable containing the subclustering information. 

For example, 
`de.genes <- FindMarkers(datasets.integrated, ident.1="0_0", ident.2="0_1", group.by="EC_subclusters")`
