### ISSUE TITLE
what assay is correct, RNA vs SCT?

### ISSUE THREAD

**Issue by hansong798** [satijalab/seurat#5406]
Hello, seurat team!

Thanks for your applicable and amazing tool,,!
I have a question for comparing gene expression among groups.

I read and understood from your tutorial that SCTransform corrects batch effects and useful method to integrate multiple dataset.
So i used SCT assay for comparing the gene expression of Interferon gamma and got left figure.
but when I changed default assay SCT to RNA, the result is right side figure, which gives totally different results.

![image](https://user-images.githubusercontent.com/85104781/146766186-87b51173-8ece-4f62-9ccb-51132f9c5423.png)  ![image](https://user-images.githubusercontent.com/85104781/146766491-a0b8efce-73e5-4445-b799-9f78aff21f15.png)

In this case, which assay is appropriate and why these two assays gives different result like this?

**Comment by torkencz** [comment]
I would use the RNA assay instead of the SCT assay. This gives an overview to why : https://www.biostars.org/p/395951/
