### ISSUE TITLE
PrepSCTIntegration - re-compute SCT missing features 

### ISSUE THREAD

**Issue by flde** [satijalab/seurat#5408]
Dear Seurat Team, 

I run the SCT integration workflow with samples from two condition (ctr/stim). Since I know there are different cell types within the sorts I want to keep all variable features from both condition respectively for integration. 

When I run SelectIntegrationFeatures the maximum number of variable feature it returns me is 3594 and everything runs smoothly. 

However, the number of unique combined variable features from the SCT assay is 3763. But when I use those 3763 features with PrepSCTIntegration it fails with the Error (full message below) `Error in scale.data[anchor.features, ]: subscript out of bounds.` 

My guess is that PrepSCTIntegration is not able to restore some SCT residuals from the 3763 and SelectIntegrationFeatures is aware of that e.g. sorting those features out. However, that is worrisome because I think those features might be actually defining cell types which are unique to a condition. Can you give me some clarification on what is going on, please? 

I very much appreciate your feedback! 

Best wishes and happy holidays, Flo

`Error in scale.data[anchor.features, ]: subscript out of bounds
Traceback:

1. PrepSCTIntegration(object.list = so, anchor.features = unique(c(VariableFeatures(so[["NaCl"]]), 
 .     VariableFeatures(so[["CpG"]]))), verbose = FALSE)
2. my.lapply(X = 1:length(x = object.list), FUN = function(i) {
 .     obj <- GetResidual(object = object.list[[i]], assay = assay[i], 
 .         features = anchor.features, replace.value = ifelse(test = is.null(x = sct.clip.range), 
 .             yes = FALSE, no = TRUE), clip.range = sct.clip.range, 
 .         verbose = FALSE)
 .     scale.data <- GetAssayData(object = obj, assay = assay[i], 
 .         slot = "scale.data")
 .     obj <- SetAssayData(object = obj, slot = "scale.data", new.data = scale.data[anchor.features, 
 .         ], assay = assay[i])
 .     return(obj)
 . })
3. future_xapply(FUN = FUN, nX = nX, chunk_args = X, args = list(...), 
 .     get_chunk = `[`, expr = expr, envir = envir, future.envir = future.envir, 
 .     future.globals = future.globals, future.packages = future.packages, 
 .     future.scheduling = future.scheduling, future.chunk.size = future.chunk.size, 
 .     future.stdout = future.stdout, future.conditions = future.conditions, 
 .     future.seed = future.seed, future.lazy = future.lazy, future.label = future.label, 
 .     fcn_name = fcn_name, args_name = args_name, debug = debug)
4. withCallingHandlers({
 .     values <- local({
 .         oopts <- options(future.rng.onMisuse.keepFuture = FALSE)
 .         on.exit(options(oopts))
 .         value(fs)
 .     })
 . }, RngFutureCondition = function(cond) {
 .     idx <- NULL
 .     uuid <- attr(cond, "uuid")
 .     if (!is.null(uuid)) {
 .         for (kk in seq_along(fs)) {
 .             if (identical(fs[[kk]]$uuid, uuid)) 
 .                 idx <- kk
 .         }
 .     }
 .     else {
 .         f <- attr(cond, "future")
 .         if (is.null(f)) 
 .             return()
 .         if (!isFALSE(f$seed)) 
 .             return()
 .         for (kk in seq_along(fs)) {
 .             if (identical(fs[[kk]], f)) 
 .                 idx <- kk
 .         }
 .     }
 .     if (is.null(idx)) 
 .         return()
 .     f <- fs[[idx]]
 .     label <- f$label
 .     if (is.null(label)) 
 .         label <- "<none>"
 .     message <- sprintf("UNRELIABLE VALUE: One of the %s iterations (%s) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to \"ignore\".", 
 .         sQuote(.packageName), sQuote(label))
 .     cond$message <- message
 .     if (inherits(cond, "warning")) {
 .         warning(cond)
 .         invokeRestart("muffleWarning")
 .     }
 .     else if (inherits(cond, "error")) {
 .         stop(cond)
 .     }
 . })
5. (function() {
 .     oopts <- options(future.rng.onMisuse.keepFuture = FALSE)
 .     on.exit(options(oopts))
 .     value(fs)
 . })()
6. value(fs)
7. value.list(fs)
8. resolve(y, result = TRUE, stdout = stdout, signal = signal, force = TRUE)
9. resolve.list(y, result = TRUE, stdout = stdout, signal = signal, 
 .     force = TRUE)
10. signalConditionsASAP(obj, resignal = FALSE, pos = ii)
11. signalConditions(obj, exclude = getOption("future.relay.immediate", 
  .     "immediateCondition"), resignal = resignal, ...)`

**Comment by flde** [comment]
Sorry, i got it. PrepSCTIntegration fails because some genes of one condition are not present in the RNA assay of the other condition. Therefore PrepSCTIntegration can't re-compute the SCT residuals. Closing the issue now.

**Comment by denvercal1234GitHub** [comment]
Hi @flde -- When you merge the objects, did you set merge.data=T? I guess you set merge.data=F because you indicated you reran SCTransform() again on the merged object...

**Comment by denvercal1234GitHub** [comment]
Hi @flde - When you rerun SCTransform() on your split objects from the merged object, did you set `do.scale=F, do.center=T`?

**Comment by AlonsoOga** [comment]
Hi,

I am currently trying the same as @flde and I am passing a list of intersected Variable Features from all the datasets I am integrating. However, I am getting the same error as he is describing. Since i am intersecting all the lists, there is no way these genes are present in only one dataset and not in the rest. I had previous success with this approach but it seems that it is not working anymore. Any thoughts?

**Comment by flde** [comment]
I just want to add that I think running SCT on the merged data from different source (stimulation, patients, machines etc.) is not an valid approach. There would be mixed effects SCT can not distinguish from the bias (e.g. sequencing depth) you actually want to remove from each data set prior integration. 

@AlonsoOga Do you intersect the Variable Features from the SCT slot of each data set and pass this vector of features to anchor.features of PrepSCTIntegration? That should definitely work.

**Comment by AlonsoOga** [comment]
Hi @flde 

I run SCT on each individual object when I am building the list of the different Seurat objects. SCT v2 helps with the differences in sequencing depth. Then we proceed with integration. 

I do intersect the variable features from the SCT slot of each dataset and then pall this vector of features to anchor.features in PrepSCTIntegration. I am also puzzled by this issue but it doesn't seem to be working.

**Comment by matasV99** [comment]
Hi @flde,
I also did exactly as @AlonsoOga , but I still get the error. Here is the code, where .big files are merged samples that were individually processed using SCT v2:

P1.big <- readRDS(file = "P1.big")
P2.big <- readRDS(file = "P2.big")

brain.list <- c(P1.big,P2.big)

var_ft3000 <- SelectIntegrationFeatures(brain.list, nfeatures = 3000, verbose = TRUE,
                                        assay = c("SCT","SCT"))

brain.list <- PrepSCTIntegration(object.list = brain.list, assay = "SCT", anchor.features = var_ft3000)


Thank you!!!
Matas
