### ISSUE TITLE
How to interpret negative value in "integrated" assay data slot

### ISSUE THREAD

**Issue by sherriying** [satijalab/seurat#5409]
Hi, 

Firstly, I would like to thank you for developing great tool to analysing scRNA-seq data! 

I have a question about if the negative value is interpretable in the "integrated" assay data slot. If I understand correctly, the negative values result from subtracting the batch effect factors. But do you know if the negative value could be consider as normalised relative expression value as well? And can I rank the genes in each cell based on these integrated data (consider data as expression value)? 
Many thanks and looking forward to your reply!

Regards,
sherry

**Comment by saketkc** [comment]
See an earlier [answer](https://github.com/satijalab/seurat/issues/2525#issuecomment-583455265).
