### ISSUE TITLE
Which R to use and how to change plotting order in FeatureHeatmap?

### ISSUE THREAD

**Issue by alectika** [satijalab/seurat#541]
Hi,
I have two problems. One is the problem about proper R version for Seurat. In your website, it is recommended to use R 3.4.1 but I had error during the data scaling. Then I upgraded R to 3.5.0 (because I got error that saying R has builded under version R 3.5.0), but I still had problems with the additional packages like ggplot2 and Matrix. Which R version do you recommend me to use?
The second thing is I want to change the plotting order for FeatureHeatmap. Is this possible? I could only do this for DimPlot.

**Comment by mojaveazure** [comment]
We use a variety of R versions, mainly 3.4.4 and 3.5.0; if you have issues with packages loading under a specific R version, try reinstalling that package. Keep your R libraries for 3.4.X and 3.5.X separate from one another, as packages cannot be moved between minor versions of R. For example, if you're installing Seurat under 3.4.1, install Seurat and **all** of it's dependent packages under 3.4.1

As for changing plotting order for FeatureHeatmap, there [currently is no way to change plot order](https://www.rdocumentation.org/packages/Seurat/versions/2.3.2/topics/FeatureHeatmap).
