### ISSUE TITLE
4.0.6 issue with MAST (doesn't happen in 4.0.5)

### ISSUE THREAD

**Issue by lauren-fish** [satijalab/seurat#5419]
Hi, I recently updated R/Bioconductor/Seurat and started having an issue with the FindMarkers function when I specify test.use = "MAST"

MuSK_BMP_satcell_genes <- FindMarkers(cellbender.sct, ident.1 = "10_D3", ident.2 = "10_WT", test.use = "MAST")

The test runs, says "Done!" and then returns "$ operator is invalid for atomic vectors" 

Someone else was having this issue and posted about it on the MAST GitHub: https://github.com/RGLab/MAST/issues/170, and I am able to work around this by using Seurat 4.0.5. The MAST issue has some more example code including a traceback and example session info. Now that I've installed 4.0.5 I can't reproduce the error (and I have a meeting today I need to prepare data for using the FindMarkers function), but I could go through and redownload 4.0.6 to reproduce the issue and copy/paste session info, error, and traceback sometime after Christmas if that would be helpful!

**Comment by AohRveTPV** [comment]
I'm also experiencing this problem with 4.0.6, for what it's worth.  Will revert to 4.0.5.

**Comment by RobertWhitener** [comment]
I will also chime in as this is happening for me as well.

**Comment by jctac** [comment]
same here

**Comment by saketkc** [comment]
This should have been fixed in `develop` branch. Can you try it from there?
https://satijalab.org/seurat/articles/install.html

Feel free to reopen if there are followup issues.
