### ISSUE TITLE
Seurat  consensus matrix 

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#542]
Hi guys,
I was wondering whether Seurat package output or save somewhere a matrix of cells similarity (distance) as some other R packages do, any suggestion?

Example:

![](https://d2ufo47lrtsv5s.cloudfront.net/content/sci/early/2018/04/25/science.aar4362/F5.large.jpg?width=800&height=600&carousel=1)

Best,
Paolo

**Comment by satijalab** [comment]
We save, in sparse format, the SNN graph that is used for clustering (if you set save.snn=T in FindClusters). Otherwise, we do not store cell similiarity/distance matrices.
