### ISSUE TITLE
FindTransferAnchors error: "..no slot of name "SCTModel.list" for this object of class "Assay"" while the object was SCTransformed

### ISSUE THREAD

**Issue by llai7** [satijalab/seurat#5422]
Related issue: [https://github.com/satijalab/seurat/issues/4721](url)

I am trying to do reference mapping with integrated reference object (SCTransform) and SCTransform but not integrated query object. I followed the vignettes here: [https://satijalab.org/seurat/articles/integration_mapping.html#dataset-preprocessing-1](url) but even though all objects were SCTransform I kept getting the error message: `Error in slot(object = reference[[reference.assay]], name = "SCTModel.list") : 
  no slot of name "SCTModel.list" for this object of class "Assay"`

I have tried what was suggested in the related issue attached above with `recompute.residuals = FALSE` still getting the same error message and I've tried updating different packages but couldn't get it to work. One guess I have is that my reference object was run using Seurat 3.1.0 and now the package has been updated to v4 there might be incompatibility between objects but I can't be sure. I would really appreciate it if someone can take a look at the error and see what other options I have besides re-run the integration!

**Code:** 
`sample.anchors <- FindTransferAnchors(reference = sarc_only_UMAP, query = sample.query,
                                        dims = 1:20, reference.reduction = "pca",
                                      normalization.method = "SCT",recompute.residuals = FALSE)
`

**Session information:**
`> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.5.2

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SeuratDisk_0.0.0.9019 SeuratObject_4.0.4    Seurat_4.0.6         

loaded via a namespace (and not attached):
  [1] nlme_3.1-152          matrixStats_0.61.0    spatstat.sparse_2.1-0
  [4] bit64_4.0.5           RcppAnnoy_0.0.19      RColorBrewer_1.1-2   
  [7] httr_1.4.2            sctransform_0.3.2     tools_4.1.1          
 [10] utf8_1.2.2            R6_2.5.1              irlba_2.3.5          
 [13] rpart_4.1-15          KernSmooth_2.23-20    uwot_0.1.11          
 [16] mgcv_1.8-36           lazyeval_0.2.2        colorspace_2.0-2     
 [19] withr_2.4.3           tidyselect_1.1.1      gridExtra_2.3        
 [22] bit_4.0.4             compiler_4.1.1        cli_3.1.0            
 [25] hdf5r_1.3.5           plotly_4.10.0         labeling_0.4.2       
 [28] scales_1.1.1          lmtest_0.9-39         spatstat.data_2.1-2  
 [31] ggridges_0.5.3        pbapply_1.5-0         goftest_1.2-3        
 [34] stringr_1.4.0         digest_0.6.29         spatstat.utils_2.3-0 
 [37] pkgconfig_2.0.3       htmltools_0.5.2       parallelly_1.30.0    
 [40] fastmap_1.1.0         htmlwidgets_1.5.4     rlang_0.4.12         
 [43] shiny_1.7.1           farver_2.1.0          generics_0.1.1       
 [46] zoo_1.8-9             jsonlite_1.7.2        ica_1.0-2            
 [49] dplyr_1.0.7           magrittr_2.0.1        patchwork_1.1.1      
 [52] Matrix_1.3-4          Rcpp_1.0.7            munsell_0.5.0        
 [55] fansi_0.5.0           abind_1.4-5           reticulate_1.22      
 [58] lifecycle_1.0.1       stringi_1.7.6         MASS_7.3-54          
 [61] Rtsne_0.15            plyr_1.8.6            grid_4.1.1           
 [64] parallel_4.1.1        listenv_0.8.0         promises_1.2.0.1     
 [67] ggrepel_0.9.1         crayon_1.4.2          miniUI_0.1.1.1       
 [70] deldir_1.0-6          lattice_0.20-44       cowplot_1.1.1        
 [73] splines_4.1.1         tensor_1.5            pillar_1.6.4         
 [76] igraph_1.2.10         spatstat.geom_2.3-1   future.apply_1.8.1   
 [79] reshape2_1.4.4        codetools_0.2-18      leiden_0.3.9         
 [82] glue_1.6.0            data.table_1.14.2     png_0.1-7            
 [85] vctrs_0.3.8           httpuv_1.6.4          gtable_0.3.0         
 [88] RANN_2.6.1            purrr_0.3.4           spatstat.core_2.3-2  
 [91] polyclip_1.10-0       tidyr_1.1.4           scattermore_0.7      
 [94] future_1.23.0         ggplot2_3.3.5         mime_0.12            
 [97] xtable_1.8-4          later_1.3.0           survival_3.2-11      
[100] viridisLite_0.4.0     tibble_3.1.6          cluster_2.1.2        
[103] globals_0.14.0        fitdistrplus_1.1-6    ellipsis_0.3.2       
[106] ROCR_1.0-11    `

**Comment by saketkc** [comment]
Can you paste your full code here?

**Comment by llai7** [comment]
> Can you paste your full code here?

Hi, yes please see the following, `Objects` contains multiple Seurat objects after CreateSeuratObject using the most updated version of Seurat and `sarc_only_UMAP` was the previously ran integrated object using Seurat 3.1.0:

```
library(Seurat)
library(dplyr)
library(Matrix)
library(ggplot2)
library(sctransform)
library(cowplot)
library(SeuratObject)

Objects <- readRDS("original.rds")

#normalization
for (file in 1:length(Objects)){
        Objects[[file]] <- SCTransform(Objects[[file]], verbose = FALSE)
}

sarc_only_UMAP <- readRDS("inte_celltype.rds")
sample.query <- normed
sample.anchors <- FindTransferAnchors(reference = sarc_only_UMAP, query = sample.query,
                                        dims = 1:20, reference.reduction = "pca",
                                      normalization.method = "SCT",recompute.residuals = FALSE)
```

**Comment by yuhanH** [comment]
HI @llai7 
Since your reference is generated in Seurat3, you just need to update your object. 
```
sarc_only_UMAP <- UpdateSeuratObject(sarc_only_UMAP)
sarc_only_UMAP <- UpdateSCTAssays(sarc_only_UMAP)
```
Then it should work.

**Comment by llai7** [comment]
> HI @llai7 Since your reference is generated in Seurat3, you just need to update your object.
> 
> ```
> sarc_only_UMAP <- UpdateSeuratObject(sarc_only_UMAP)
> sarc_only_UMAP <- UpdateSCTAssays(sarc_only_UMAP)
> ```
> 
> Then it should work.

Hi Yuhan thank you for your reply, but this is what I got running those lines:

```
> sarc_only_UMAP <- UpdateSeuratObject(sarc_only_UMAP)
Validating object structure
Updating object slots
Ensuring keys are in the proper strucutre
Ensuring feature names don't have underscores or pipes
Updating slots in RNA
Updating slots in SCT
Updating slots in integrated
Updating slots in integrated_nn
Setting default assay of integrated_nn to integrated
Updating slots in integrated_snn
Setting default assay of integrated_snn to integrated
Updating slots in pca
Updating slots in umap
Setting umap DimReduc to global
No assay information could be found for FindIntegrationAnchors
Warning: Adding a command log without an assay associated with it
No assay information could be found for PairwiseIntegrateReference
Warning: Adding a command log without an assay associated with it
Setting assay used for RunPCA.integrated to integrated
Setting assay used for FindNeighbors.integrated.pca to integrated
No assay information could be found for FindClusters
Warning: Adding a command log without an assay associated with it
Setting assay used for RunUMAP.integrated.pca to integrated
Object representation is consistent with the most current Seurat version
> sarc_only_UMAP <- UpdateSCTAssays(sarc_only_UMAP)
Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("SCTModel", package = "Seurat")’ to a data.frame
```

**Comment by yuhanH** [comment]
Would you mind to send your reference object to me? My email is yhao@nygenome.org
It will be much easier for me to debug this issue. Or you can also re-normalize your reference in Seurat4

**Comment by yuhanH** [comment]
Thanks for sending this object. There is a bug in `UpdateSCTAssays`. Currently, you can use `as` to convert integrated assay from `Assay` to `SCTAssay`.   Because it was integrated in Seurat3, reference SCT-model is not stored in the integrated assay. `recompute.residuals = FALSE` is needed. 
```
# update object and then convert Assay to SCTAssay
sarc_only_UMAP<- UpdateSeuratObject(sarc_only_UMAP)
sarc_only_UMAP[['integrated']] <- as(object = sarc_only_UMAP[['integrated']] , Class = "SCTAssay")

DefaultAssay(sarc_only_UMAP) <- "integrated"
sample.anchors <- FindTransferAnchors(
reference = sarc_only_UMAP, 
query = sample.query, 
dims = 1:20, 
reference.reduction = "pca", 
normalization.method = "SCT",
recompute.residuals = FALSE
)
```

**Comment by llai7** [comment]
> Thanks for sending this object. There is a bug in `UpdateSCTAssays`. Currently, you can use `as` to convert integrated assay from `Assay` to `SCTAssay`. Because it was integrated in Seurat3, reference SCT-model is not stored in the integrated assay. `recompute.residuals = FALSE` is needed.
> 
> ```
> # update object and then convert Assay to SCTAssay
> sarc_only_UMAP<- UpdateSeuratObject(sarc_only_UMAP)
> sarc_only_UMAP[['integrated']] <- as(object = sarc_only_UMAP[['integrated']] , Class = "SCTAssay")
> 
> DefaultAssay(sarc_only_UMAP) <- "integrated"
> sample.anchors <- FindTransferAnchors(
> reference = sarc_only_UMAP, 
> query = sample.query, 
> dims = 1:20, 
> reference.reduction = "pca", 
> normalization.method = "SCT",
> recompute.residuals = FALSE
> )
> ```

Hi Yuhan,

Thank you so much for trying to debug for me! I tried the code and got an error message:
```
Validating object structure
Updating object slots
Ensuring keys are in the proper strucutre
Ensuring feature names don't have underscores or pipes
Updating slots in RNA
Updating slots in SCT
Updating slots in integrated
Updating slots in integrated_nn
Setting default assay of integrated_nn to integrated
Updating slots in integrated_snn
Setting default assay of integrated_snn to integrated
Updating slots in pca
Updating slots in umap
Setting umap DimReduc to global
No assay information could be found for FindIntegrationAnchors
Warning: Adding a command log without an assay associated with it
No assay information could be found for PairwiseIntegrateReference
Warning: Adding a command log without an assay associated with it
Setting assay used for RunPCA.integrated to integrated
Setting assay used for FindNeighbors.integrated.pca to integrated
No assay information could be found for FindClusters
Warning: Adding a command log without an assay associated with it
Setting assay used for RunUMAP.integrated.pca to integrated
Object representation is consistent with the most current Seurat version
Error: No features to use in finding transfer anchors. To troubleshoot, try explicitly providing features to the features parameter and ensure that they are present in both reference and query assays.
Execution halted
```

**Comment by yuhanH** [comment]
The error seems to result from your query object.
Could you show me the scripts you run?

**Comment by llai7** [comment]
> The error seems to result from your query object. Could you show me the scripts you run?

Dear yuhan, 

I resaved my query object and it seems to work now! Thank you so much for your help, much appreciate it!! :)
