### ISSUE TITLE
Why the most suitable UMAP PCs for my scRNA-seq dataset is only Three?

### ISSUE THREAD

**Issue by jiangpuxuan** [satijalab/seurat#5423]
At first we knew that the `UMAP` plot for germ cells (`scRNA-seq`) always appeared continuous, like this:
![image](https://user-images.githubusercontent.com/81287604/147467941-a9d0b809-f6d7-4e69-8647-34c8c35b0c3c.png)

I have a single cell transcriptome dataset of fish testis (nearly `95%` germ cells), and I should set the PCs for UMAP to only `3` to ensure the plot appeared normally continuous. When the PCs come to `4` or higher, the topological structure will be twisted and cracked, so it can not provide the knowledge of the pseudotime of germ cells developing at all.

Here is the plot when `PCs=3`:
![image](https://user-images.githubusercontent.com/81287604/147468090-e20c53d8-b383-44c6-9637-d9cdf891c5a8.png)
![image](https://user-images.githubusercontent.com/81287604/147468099-2ccee5fa-072e-4648-957d-5db9cc026b69.png)

The first plot indicates the `3` samples  (m10, m30, m60) which consists of the dataset.

Here is the plot when `PCs=4` and `10`:
![image](https://user-images.githubusercontent.com/81287604/147468139-78ceb3d1-ba1a-41b7-9be4-adb6ef134719.png)
![image](https://user-images.githubusercontent.com/81287604/147468193-01a9d622-80e6-479c-a150-3cf6ba544080.png)

Thank you for your help!

**Comment by torkencz** [comment]
Hi,

While I cannot perfectly answer you question I can give you some pointers. I assume you determined the dimensionality of your data with some method, like Jackstraw. That will tell you how many PCs your data should have. I would next look at the what genes the PC loading correlate with to see if any of the higher components make sense biologically. Also you could see how these components influence the clusters you are observing. I hope this helped a little. I can reopen if you have more questions.

**Comment by jiangpuxuan** [comment]
> 

Thank you for your help. 
Now I assumed that there are too many doublets in my dataset. Compared to the normal GEM, non-hetero-doublets have similar expression pattern but higher expression levels. Because of these  non-hetero-doublets, my UMAP  became branched rather than normally continuous.
The cells in my sample are mainly distributed in 10~14 um in diameter. The recommended cell diameter for 10x RNA-seq is 30um. That sounds like my cells are prone to form doublets.
