### ISSUE TITLE
In the single data and the integrated data, the results of AddModuleScore are inconsistent

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#5425]
Hi, seurat team :
       Thanks for developing this user-friendly tools. I met a question when i running the **AddModuleScore function**. I have **four gene sets**, each representing a different state. In a integrated single-cell data, I ran the AddModuleScore function so that each cell got four different scores. But when i split the integrated data into single ones, again using the same gene sets and parameters, I got a very inconsistent result.
       My code are : 
**tumor<- AddModuleScore(tumor, features = list(a), nbin = 30, ctrl = 100, name = 'A', assay = 'RNA')**
tumor <- AddModuleScore(tumor, features = list(b), nbin = 30, ctrl = 100, name = 'B', assay = 'RNA')
tumor <- AddModuleScore(tumor, features = list(c), nbin = 30, ctrl = 100, name = 'C', assay = 'RNA')
tumor <- AddModuleScore(tumor, features = list(d), nbin = 30, ctrl = 100, name = 'D', assay = 'RNA')

I know it's normal to get different scores based on different controls. But a single sample is part of a integrated sample, and the scores obtained in integrated samples **vary greatly** from those obtained in a single sample, resulting in the cell states that are significant in integrated samples **is not significant** in a single sample. 

Another question is how to determine **the number of bin in AddModuleScore.**

Seurat version : 4.0.5

I sincerely to get your help. Thanks

**Comment by saketkc** [comment]
Can you post your entire code here?

**Comment by Rui-Jing** [comment]
@saketkc Hi, Thanks for your reply. I have seven single-cell sample. 
#Integrated 7 samples
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
P11.data <- Read10X(data.dir = "/data/jr/P11/outs/filtered_feature_bc_matrix/")
P12.data <- Read10X(data.dir = "/data/jr/P12/outs/filtered_feature_bc_matrix/")
P13.data <- Read10X(data.dir = "/data/jr/P13/outs/filtered_feature_bc_matrix/")
P14.data <- Read10X(data.dir = "/data/jr/P14/outs/filtered_feature_bc_matrix/")
P15.data <- Read10X(data.dir = "/data/jr/P15/outs/filtered_feature_bc_matrix/")
P16.data <- Read10X(data.dir = "/data/jr/P16/outs/filtered_feature_bc_matrix/")
P17.data <- Read10X(data.dir = "/data/jr/P17/outs/filtered_feature_bc_matrix/")
# Initialize the Seurat object with the raw (non-normalized data).
P11 <- CreateSeuratObject(counts = P11.data, project = "P11")
P12 <- CreateSeuratObject(counts = P12.data, project = "P12")
P13 <- CreateSeuratObject(counts = P13.data, project = "P13")
P14 <- CreateSeuratObject(counts = P14.data, project = "P14")
P15 <- CreateSeuratObject(counts = P15.data, project = "P15")
P16 <- CreateSeuratObject(counts = P16.data, project = "P16")
P17 <- CreateSeuratObject(counts = P17.data, project = "P17")
#Merge tumor sample 
all <- merge(P11, 
                  y = c(P12, P13, P14, P15, P16, P17), 
                  add.cell.ids = c("P11", "P12", "P13", "P14", "P15", "P16", "P17"), 
                  project = "Tumor")

# Add number of genes per UMI for each cell to metadata_clean
all$log10GenesPerUMI <- log10(all$nFeature_RNA) / log10(all$nCount_RNA)

# Compute percent mito ratio
all$mitoRatio <- PercentageFeatureSet(object = all, pattern = "^mt-")
all$mitoRatio <- all@meta.data$mitoRatio / 100
all$sample <- all@meta.data$orig.ident
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
all <- CellCycleScoring(all, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

#cell-filtered
filtered_seurat <- subset(x = all, 
                          subset= (nCount >= 500) & 
                            (nFeature >= 250) & 
                            (log10GenesPerUMI > 0.80) & 
                            (mitoRatio < 0.15))
# run sctransforma
filtered_seurat <- SCTransform(filtered_seurat, vars.to.regress = c("S.Score", "G2M.Score", "mitoRatio), verbose = FALSE)

filtered_seurat <- RunFastMNN(object.list = SplitObject(filtered_seurat, split.by = "sample"))
filtered_seurat <- RunUMAP(filtered_seurat, reduction = "mnn", dims = 1:30)
filtered_seurat <- RunTSNE(filtered_seurat, reduction = "mnn", dims = 1:30, verbose = T)
filtered_seurat <- FindNeighbors(filtered_seurat, reduction = "mnn", dims = 1:30)
filtered_seurat <- FindClusters(filtered_seurat,resolution = 0.8)

#Extract tumor cells from filtered_seurat and AddModuleScore
**tumor <- subset(x = filtered_seurat, idents = c(“microenvironment cell”))
> tumor
An object of class Seurat 
41962 features across 22155 samples within 2 assays 
Active assay: SCT (20981 features, 0 variable features)
 1 other assay present: RNA
 3 dimensional reductions calculated: mnn, umap, tsne**

**meta_module <- read.table(file = '/home/zfzf/meta_module_only.csv',header = F,sep = ',')**
**a <- meta_module$V1[1:35]
b <- meta_module$V1[36:130]
c <- meta_module$V1[131:225]
d <-meta_module$V1[226:273]
tumor<- AddModuleScore(tumor, features = list(a), nbin = 30, ctrl = 100, name = 'A', assay = 'RNA')
tumor <- AddModuleScore(tumor, features = list(b), nbin = 30, ctrl = 100, name = 'B', assay = 'RNA')
tumor <- AddModuleScore(tumor, features = list(c), nbin = 30, ctrl = 100, name = 'C', assay = 'RNA')
tumor <- AddModuleScore(tumor, features = list(d), nbin = 30, ctrl = 100, name = 'D', assay = 'RNA')**

#Single cell sample
P11.data <- Read10X(data.dir = "/data/jr/P11/outs/filtered_feature_bc_matrix/")
Then,using the standard **pbmc3k_tutoria**l to clustring, resolution in FindClusters is 0.8.
tumor_P11 <- subset(x=p11,idents = c(“microenvironment cell”))
> tumor_P11
An object of class Seurat 
16176 features across 1284 samples within 1 assay 
Active assay: RNA (16176 features, 2000 variable features)
 3 dimensional reductions calculated: pca, umap, tsne

**tumor_P11<- AddModuleScore(tumor_P11, features = list(a), nbin = 30, ctrl = 100, name = 'A', assay = 'RNA')
tumor_P11 <- AddModuleScore(tumor_P11, features = list(b), nbin = 30, ctrl = 100, name = 'B', assay = 'RNA')
tumor_P11<- AddModuleScore(tumor_P11, features = list(c), nbin = 30, ctrl = 100, name = 'C', assay = 'RNA')
tumor_P11 <- AddModuleScore(tumor_P11, features = list(d), nbin = 30, ctrl = 100, name = 'D', assay = 'RNA')**

It is worth mentioning that the tumor cells in the single sample are basically the same as those in the integrated sample

**Comment by saketkc** [comment]
Sorry, I am not sure I understand fully, but I think I understand that the module score calculations from your integrated dataset and individual dataset do not match perfectly. The discrepancy in module score when calculated on an integrated object v/s in an individual object could arise from how the feature sets change on integration (for example your P11 dataset has 16176 features while the integrated dataset has more possibly because some features are only present in a subset (or only one) of datasets). [AddModuleScore](https://satijalab.org/seurat/reference/addmodulescore) when calculating a score, first bins the provided features on averaged expression, and then randomly selects control features from each bin to be subtracted. Having a different number of features (in integrated v/s individual dataset) can result in slightly different scores.

**Comment by Prakrithi-P** [comment]
Hi, 
  Is it ideal to compute module score on integrated counts or raw counts?

Thanks,
Prakrithi
