### ISSUE TITLE
integration file 

### ISSUE THREAD

**Issue by Liripo** [satijalab/seurat#5428]
https://github.com/satijalab/seurat/blob/8da35ba8dc2d60f504f7cf276efd684dc19a418c/R/integration.R#L270-L281

I don't really understand future either, so I'd like to ask for advice.
It seems that this will copy all the object.list to other sessions, resulting in a large memory usage.

I don't know if I can change it to the following？
```R
dim_list <- lapply(object.list,function(x){
  x[[nn.reduction]])[, dims]
})
internal.neighbors <- my.lapply(dim_list, FUN = function(x) {
    NNHelper(data = Embeddings(object = x, k = k.neighbor + 1, method = nn.method, 
             n.trees = n.trees, eps = eps)
})
````

There is also the fact that futrue_lapply has some parameters such as future.chunk.size, will it be considered to expose them?

**Comment by timoast** [comment]
Whether objects are copied in memory depends on the future plan set. If you use `plan(multicore)`, it will use forked processes that use shared memory, if you set `plan(multisession)` it will create background R sessions that duplicate things in memory. If you use `plan(sequential)`, it's just using one process and so nothing will be duplicated in memory either.

In this case, I think we could extract the smaller embedding matrix before running the parallelized section to potentially reduce memory usage as you suggest.

**Comment by rsatija** [comment]
Closing for now, as we discuss in other issues we are re-evaluating how to perform parallelization in Seurat v5 that more efficiently process memory
