### ISSUE TITLE
Splitting Seurat object by chemistry

### ISSUE THREAD

**Issue by cmpadil** [satijalab/seurat#5432]
I am relatively new using Seurat. 

I have a single Seurat object with combined chemistries: 3PV2, 3PV3, 5PV1, and 5PV2. I would like to analyze the 19 samples from the 3P chemistries only but I am having difficulty separating out this data. 

I have tried subsetting the Seurat object by orig.idents (the samples from 3P chemistries) but somehow I lose cells in the process when I do this. I also tried splitting the data by chemistries before merging only the 3P data but I lose the reductions and the dimplot looks very different from the combined Seurat object. 

##creating subset of Seurat Object##
name <- subset (object, idents = orig.idents == c(list of samples), invert = FALSE 

##Split by chemistry then tried to merge 3P chemistries##
M <- SplitObject (object, split.by = "chemistry") 

##4 elements separate: 3PV2, 3PV3, 5PV1, 5PV2##

##Merging 3PV2 and 3PV3, I lose the reduction data##
MM <- merge (M$`3PV2`, M$`3PV3`)

Is there a simple way to pull out just the 3P chemistries containing 19 samples for separate analysis?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I think issue with subset is probably because of syntax you are using `==` when you should be using `%in%`.

Does running this work?
`name <- subset (object, idents = orig.idents %in% c(list of samples), invert = FALSE)`

Best,
Sam

**Comment by cmpadil** [comment]
Hi Sam,

Thanks for the assistance! Yes, thank you it worked. I made a tweak but it finally created a sub seurat object. 

name <- subset (object, orig.ident %in% c("list of samples"), invert = FALSE)

For my edification, could you briefly explain how %in% is utilized in Seurat?

Thanks again!
Cristina

**Comment by samuel-marsh** [comment]
Hi Cristina,

This is base R difference in == vs %in%.  See here for one explanation: https://stackoverflow.com/questions/42637099/difference-between-the-and-in-operators-in-r

best,
Sam

**Comment by torkencz** [comment]
Yes %in% should work in this case.
