### ISSUE TITLE
Azimuth annotations don't match the Seurat clusters

### ISSUE THREAD

**Issue by alvingao90** [satijalab/seurat#5435]
Hi All,

Thanks for the nice programs, Seurat and Azimuth.

Here, I have a confusing question. I used Azimuth to annotate the clusters recognized by Seurat, but the Azimuth result does not perfectly match the Seurat cluster, as shown in the figure below.

![result](https://github.com/alvingao90/seurat/blob/main/result.png)

It seems weird that B cells and DCs mixed with each other. The cell type annotation seems not to match well with the clustering result (I took the cattle PBMC as the query data).

Do you have any suggestions about this?

Thanks,
Alvin

**Comment by alvingao90** [comment]
>

**Comment by saketkc** [comment]
Your figure is not showing up for some reason, but see an earlier [answer](https://github.com/satijalab/seurat/issues/4367#issuecomment-821462891) for the reason. For follow up questions about Zimuth, please open an issue in the Azimuth repository.
