### ISSUE TITLE
Where does Seurat store variable gene information?

### ISSUE THREAD

**Issue by GHHenryUTSW** [satijalab/seurat#544]
Ran RunCCA/AlignSubspace, then when execute FindVariableGenes, @genes.hvg results in Error: no slot of name "genes.hvg" for this object of class "seurat"

**Comment by mojaveazure** [comment]
Hi Gervaise, the [Seurat object](https://www.rdocumentation.org/packages/Seurat/versions/2.3.2/topics/seurat) doesn't have a slot called `genes.hvg`; [as seen in the docs](https://www.rdocumentation.org/packages/Seurat/versions/2.3.2/topics/FindVariableGenes), `FindVariableGenes` stores the variable genes in the `var.genes` slot, with the means and dispersion values stored in  the `hvg.info` slot.

**Comment by mojaveazure** [comment]
I can't replicate that:

```R
> data("pbmc_small")
> pbmc1 <- SubsetData(object = pbmc_small, cells.use = pbmc_small@cell.names[1:40])
> pbmc2 <- SubsetData(object = pbmc_small, cells.use = pbmc_small@cell.names[41:80])
> pbmc1@meta.data$group <- "group1"
> pbmc2@meta.data$group <- "group2"
> pbmc_cca <- RunCCA(object = pbmc1, object2 = pbmc2)
Running CCA
Merging objects
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Scaling data matrix
  |=============================================================| 100%
> pbmc_cca <- AlignSubspace(object = pbmc_cca, reduction.type = "cca", grouping.var = "group", dims.align = 1:2)
Rescaling group 1
Scaling data matrix
  |=============================================================| 100%
Rescaling group 2
Scaling data matrix
  |=============================================================| 100%
Aligning dimension 1
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
Aligning dimension 2
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
> pbmc_cca@var.genes
 [1] "LTB"       "EAF2"      "PIK3IP1"   "KHDRBS1"   "SRSF7"    
 [6] "S1PR4"     "LYAR"      "SATB1"     "IL17RA"    "POP7"     
[11] "ZNF330"    "COPS6"     "PPBP"      "HIST1H2AC" "TALDO1"   
[16] "ACRBP"     "VDAC3"     "GNLY"      "PTGDR"     "ARHGDIA"  
[21] "PCMT1" 
> pbmc_cca <- FindVariableGenes(object = pbmc_cca, do.plot = FALSE)
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> pbmc_cca@var.genes
 [1] "LTB"       "EAF2"      "CD19"      "KIAA0125"  "CYB561A3" 
 [6] "IGLL5"     "PIK3IP1"   "KHDRBS1"   "CCR7"      "ACSM3"    
[11] "SRSF7"     "S1PR4"     "LYAR"      "SATB1"     "IL17RA"   
[16] "POP7"      "ZNF330"    "COPS6"     "PPBP"      "PF4"      
[21] "HIST1H2AC" "TALDO1"    "CA2"       "ACRBP"     "TSC22D1"  
[26] "VDAC3"     "GNLY"      "PTGDR"     "ARHGDIA"   "PCMT1"    
[31] "S100B" 
```
The `var.genes` slot is different, and therefore populated by FindVariableGenes after running RunCCA/AlignSubspace.

**Comment by GHHenryUTSW** [comment]
Donno what to tell you, it's not populating for me. It's OK, I just pulled the genes by slicing the @hvg.info with my cutoffs.

Thanks,
Gervaise

**Comment by brianpenghe** [comment]
> Ran RunCCA/AlignSubspace, then when execute FindVariableGenes, @genes.hvg results in Error: no slot of name "genes.hvg" for this object of class "seurat"

In Seurat3 it's stored at 
Object@assays$RNA@var.features

![bitmoji](https://render.bitstrips.com/v2/cpanel/154399c8-7f57-4aa1-9dbf-1fde827ed584-4c0edd69-002f-4ee5-9171-2ca626e1370d-v1.png?transparent=1&palette=1&width=246)

**Comment by ptranvan** [comment]
> > Ran RunCCA/AlignSubspace, then when execute FindVariableGenes, @genes.hvg results in Error: no slot of name "genes.hvg" for this object of class "seurat"
> 
> In Seurat3 it's stored at Object@assays$[RNA@var.features](mailto:RNA@var.features)
> 
> ![bitmoji](https://camo.githubusercontent.com/57e32a25ac0b40625dc1083822000e096613ad7dc409c9b5fbf2fd89d60ebda5/68747470733a2f2f72656e6465722e6269747374726970732e636f6d2f76322f6370616e656c2f31353433393963382d376635372d346161312d396462662d3166646538323765643538342d34633065646436392d303032662d346565352d393137312d3263613632366531333730642d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)

Where is it now in seurat 5 ?

**Comment by shenmaya** [comment]
This is probably not the most direct way but you can find this info through the meta.data using the `var.features` column. If the gene was not selected as a HVG it'll be NA and if it was selected as a HVG it'll be the gene name. The following code works for me: `Object@assays$RNA@meta.data$var.features[!is.na(Object@assays$RNA@meta.data$var.features)]`

I am also curious if there is a more direct way.

**Comment by samuel-marsh** [comment]
`var_gene <- VariableFeatures(object = OBJ_NAME)`

**Comment by mluciarr** [comment]
Hi I am having some problems running MOFA because of the disappearance of the `var.feature` slot in the RNA assay. Does anyone know who to create the `var.feature `slot manually? Because MOFA only detects var.feature as `Object@assays$RNA@var.features` not in the metadata. 
I would really appreciate your help! 
Thank you very much!!

**Comment by samuel-marsh** [comment]
Hi,

If you object has Assay5 assays you need to convert them to Assay assays.  I have a helper function in my package scCustomize `Convert_Assay` to make it easy.  See here: https://samuel-marsh.github.io/scCustomize/articles/Object_Conversion.html#convert-seurat-assay-type-within-an-object

Best,
Sam

**Comment by mluciarr** [comment]
Hi @samuel-marsh 
Thank you so much for your reply! I did it and it worked perfectly. :) 
Best!

Lucia

**Comment by apal6** [comment]
Hi,

I am trying to run a package but I get an error which is more about the seurat object, 
error:
`Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in as.vector(x): no slot of name "var.features" for this object of class "Assay5"`

<img width="463" alt="Screenshot 2024-05-06 at 10 23 11 AM" src="https://github.com/satijalab/seurat/assets/127814354/3bb05336-20fc-43d3-96bd-fb088d70e37f">

I am trying to run the following package : [https://carmonalab.github.io/ProjecTILs.demo/tutorial.html]
I am not sure why it is not recognising the variable. What do you suspect? 

Thank you
