### ISSUE TITLE
number of features in the FindVariableFeatures function

### ISSUE THREAD

**Issue by sitr1014** [satijalab/seurat#5440]
Hi, I know the default number of features to be returned in the FindVariableFeatures() is 2000 but I am wondering if there is a specific justification for this number? Or in the real analysis, what should I look for by tuning this parameter? Thanks!

**Comment by torkencz** [comment]
Hi,

I think this parameter is a little arbitrary. One way that I would imagine you could be a little specific would be by taking the top n% of the the mean expression-variance plot. Alternative could be seeing if the variance has an elbow if you plot it.
