### ISSUE TITLE
Question: Remove batch effect in scA&T Data

### ISSUE THREAD

**Issue by Thorged** [satijalab/seurat#5444]
Hi, I am currently working with a multiome dataset (sc ATAC+RNA, 10x platform)  but struggle to deal with batch effects between samples (supposedly no biological differences). I ran batch correction in RNA & ATAC respectively & was wondering if there is amultimodal anchor framework or a better approach to do it in general?

Thanks a lot for the amazing seurat and signac packages!

**Comment by mhkowalski** [comment]
Hi, as mentioned in #5305 , you could try finding anchors using one of the modalities and using the same set of anchors to integrate both the ATAC and RNA.
