### ISSUE TITLE
extracting data from dataset

### ISSUE THREAD

**Issue by cardinLL** [satijalab/seurat#5449]
Hi All, 

The function "rownames" and "colnames" extract row and column labels from the dataset. 

For some specific purpose, I need to extract a column of strings from a dataset that doesn't seem compatible with the two functions above. It looks like this: 
![a657987e438d9d8d0697b492eb20257](https://user-images.githubusercontent.com/97207965/148486994-f2cba1f6-99f4-4634-961a-9f94dc39ed0d.png)

And after running colnames it reports null. 
![7e50e3ee229abf6b5c71c2f48c872f2](https://user-images.githubusercontent.com/97207965/148487055-7196d451-2267-4b8d-87ff-b703d6882ec6.png)

I just wonder if there is any way to extract the first column of this dataset! Any suggestions will be highly appreciated! 

thanks

Best, 

Max

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I'm little confused as to what you are trying to do and how it relates to Seurat.  The object you are looking at "addset" doesn't appear to be a Seurat object.  Can you elaborate more on what you are trying to do and what you did so far?

Thanks.
Sam

**Comment by cardinLL** [comment]
> 



> Hi,
> 
> Not member of dev team but hopefully can be helpful. I'm little confused as to what you are trying to do and how it relates to Seurat. The object you are looking at "addset" doesn't appear to be a Seurat object. Can you elaborate more on what you are trying to do and what you did so far?
> 
> Thanks. Sam

Hi, 

The Seurat object itself is from GSE154659_C57_Raw_counts and all the necessary steps of sn-RNA-seq analysis have been performed. I just need to analyze the data according to cell name and experiment type. This picture is a dataset extracted from where these two identities are written. Due to its syntax, I cannot sort the cells and experiment type just with it. So I am trying to extract the first column containing cell names and experiment types before I perform any further analysis on it. 

Best, 

Max

**Comment by samuel-marsh** [comment]
What component of the data is the addset object?

**Comment by cardinLL** [comment]
> What component of the data is the addset object?

active.ident

**Comment by timoast** [comment]
It looks like you just have a vector here, which would not have rownames or column names. I'm not quite sure what the goal is but you should seek support in a more general R programming forum (eg StackOverflow)
