### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by IlariaPalmi** [satijalab/seurat#5453]
Dear all,
I am running Seurat in a R environment created in conda. I am following Seurat tutorial to analyse my data

>library(Seurat)
>library(dplyr)
>library(patchwork)
>library(ggplot2)

After reading the data, and creating Seurat object, I am doing some QC.
When I run

>plot=VlnPlot(Mydata, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
>plot

I do not get any Figure window or any plot. Is there a package I am missing to install?
Thanks for your help.

**Comment by saketkc** [comment]
I am assuming this is outside Rstudio and maybe the system doesn't have an X window enabled, in which case you can always save your plot by `ggsave(plot = plot, filename="plot.png")`
