### ISSUE TITLE
CITE-Seq ADT integration problem.

### ISSUE THREAD

**Issue by wajm** [satijalab/seurat#5456]
hi,
I have 5 dataset integration for CITE-Seq (4 CITEseq with 8 abs and 1 CITEseq with 4 abs).
First I've done RNA integration using RPCA.
then I'll try to do ADT integration separately using following code.

DefaultAssay(all.adt) <- "ADT"

all.list.adt <- SplitObject(all.adt, split.by = "orig.ident")

all.list.adt <- lapply(X = all.list.adt, FUN = function(x) {
    	 x <- NormalizeData(x, normalization.method = 'CLR', margin = 2)
		 x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features.adt <- SelectIntegrationFeatures(object.list = all.list.adt)

all.list.adt <- lapply(X = all.list.adt, FUN = function(x) {
    x <- ScaleData(x, features = features.adt, verbose = FALSE)
    x <- RunPCA(x, features = features.adt, verbose = FALSE)
})

Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  did not converge--results might be invalid!; try increasing work or maxit
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.

anchors.adt <- FindIntegrationAnchors(object.list = all.list.adt, anchor.features = features.adt, reduction = 'rpca', 
	                                  normalization.method = "LogNormalize", dims=1:3)

but from here make some errors like this.

Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=06s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 782 anchors
  |+++++                                             | 10% ~20s          Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 901 anchors
  |++++++++++                                        | 20% ~21s          Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 973 anchors
  |+++++++++++++++                                   | 30% ~18s          Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 1108 anchors
  |++++++++++++++++++++                              | 40% ~16s          Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 439 anchors
  |+++++++++++++++++++++++++                         | 50% ~13s          Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 861 anchors
  |++++++++++++++++++++++++++++++                    | 60% ~11s          Projecting new data onto SVD
Projecting new data onto SVD
Error in rbind(Embeddings(object = object.1[[reduction]]), Embeddings(object = object.2[[reduction]])) : 
  number of columns of matrices must match (see arg 2)

Any solution for this?

**Comment by yuhanH** [comment]
Could you have a try this ADT integration without the 4-Abs dataset?
Then we can figure out where the error is.

**Comment by fahmadimoughari** [comment]
I get the same error. The error arises in FindIntegrationAnchors step. I have got 10 snRNA-seq samples, and I used the following codes:
`
			# get features
			features <- SelectIntegrationFeatures(
				object.list = sample.list, 
				nfeatures = 2000
			);
			# prepare for integration
			sample.list  <- PrepSCTIntegration(
				object.list = sample.list, 
				anchor.features = features
			);
			# find integration anchors
			anchors <- FindIntegrationAnchors(
				object.list = sample.list,
				anchor.features = features,
				normalization.method = "SCT",
				reduction = "rpca",
				dims = 1:20
			);` 
And the error is:
`Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 378 anchors
  |++                                                | 2 % ~01m 22s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 407 anchors
  |+++                                               | 4 % ~01m 24s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 617 anchors
  |++++                                              | 7 % ~01m 24s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 185 anchors
  |+++++                                             | 9 % ~01m 18s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 215 anchors
  |++++++                                            | 11% ~01m 13s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 261 anchors
  |+++++++                                           | 13% ~01m 11s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 274 anchors
  |++++++++                                          | 16% ~01m 08s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 339 anchors
  |+++++++++                                         | 18% ~01m 05s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 335 anchors
  |++++++++++                                        | 20% ~01m 04s      Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 171 anchors
  |++++++++++++                                      | 22% ~01m 01s      Projecting new data onto SVD
Projecting new data onto SVD
Error in rbind(Embeddings(object = object.1[[reduction]]), Embeddings(object = object.2[[reduction]])) : 
  number of columns of matrices must match (see arg 2)`

**Comment by fahmadimoughari** [comment]
> I get the same error. The error arises in FindIntegrationAnchors step. I have got 10 snRNA-seq samples, and I used the following codes:
> 
> > 
> 
> ```
> 		features <- SelectIntegrationFeatures(
> 			object.list = sample.list, 
> 			nfeatures = 2000
> 		);
> 		# prepare for integration
> 		sample.list  <- PrepSCTIntegration(
> 			object.list = sample.list, 
> 			anchor.features = features
> 		);
> 		# find integration anchors
> 		anchors <- FindIntegrationAnchors(
> 			object.list = sample.list,
> 			anchor.features = features,
> 			normalization.method = "SCT",
> 			reduction = "rpca",
> 			dims = 1:20
> 		);`` 
> ```
> 
> And the error is:
> 
> > Computing within dataset neighborhoods
> > |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s
> > Finding all pairwise anchors
> > |                                                  | 0 % ~calculating  Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 378 anchors
> > |++                                                | 2 % ~01m 22s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 407 anchors
> > |+++                                               | 4 % ~01m 24s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 617 anchors
> > |++++                                              | 7 % ~01m 24s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 185 anchors
> > |+++++                                             | 9 % ~01m 18s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 215 anchors
> > |++++++                                            | 11% ~01m 13s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 261 anchors
> > |+++++++                                           | 13% ~01m 11s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 274 anchors
> > |++++++++                                          | 16% ~01m 08s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 339 anchors
> > |+++++++++                                         | 18% ~01m 05s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 335 anchors
> > |++++++++++                                        | 20% ~01m 04s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Finding neighborhoods
> > Finding anchors
> > Found 171 anchors
> > |++++++++++++                                      | 22% ~01m 01s      Projecting new data onto SVD
> > Projecting new data onto SVD
> > Error in rbind(Embeddings(object = object.1[[reduction]]), Embeddings(object = object.2[[reduction]])) :
> > number of columns of matrices must match (see arg 2)``

I resolved this issue by rerunning RunPCA on each individual sample and setting all the num.pc as the same number.
