### ISSUE TITLE
subsetting generates NA in other columns

### ISSUE THREAD

**Issue by zedzedwhy** [satijalab/seurat#5457]
`test = subset(ss2.seurat, ident = "Sub_Cluster")
> test$Tissue
  Tmy-2-32-20180305   Tmy-4-26-20180305   Tmy-5-21-20180305   Tmy-5-39-20180305   Tmy-6-13-20180305 
                 NA                  NA                  NA                  NA                  NA 
>
> test1 = subset(seuratObj, ident = "CD8 T")
> test1$aggregate
W380370 W380378 W380386 W380393 W380395 W380401 W380410 W380417 W380418 W380422 W380432 W380433 
   "SS"    "SS"    "SS"    "SS"    "SS"    "SS"    "SS"    "SS"    "SS"    "SS"    "SS"    "SS" 
`
The raw data is fine, but when I subset the seurat object by "Sub_Cluster" and then look at another column, "Tissue", the values all become NA (as compared with another seurat object). 
And when I run DimPlot in ss2.seurat, the error is "Must request at least one colour from a hue palette." I guess somehow the values of the idents become NA in the process. 
Can anyone help? Thanks.

**Comment by mhkowalski** [comment]
Can you confirm that there are not NA values in your original object's tissue meta data? Please paste the output of ```sum(is.na(ss2.seurat$Tissue))```
