### ISSUE TITLE
RunPCA.default bug when `rev.pca=FALSE, approx=FALSE, weight.by.var = FALSE`

### ISSUE THREAD

**Issue by jinziyang010** [satijalab/seurat#5458]
**Code segment 1**
```r
if (weight.by.var) {
  cell.embeddings <- pca.results$x
} else {
  cell.embeddings <- pca.results$x / (pca.results$sdev[1:npcs] * sqrt(x = ncol(x = object) - 1))  # HERE
}
```

This code is copied from function `RunPCA.default` in Seurat releases version 4.0.6, which produces wrong result for `cell.embeddings` when `weight.by.var = FALSE`.
Here give my example, suppose one matrix named `tmp.a`. I run PCA by using function `prcomp`.
```
tmp.a <- matrix(c(3,2,4,11,1,4,-2,22,-1,0,-5,20), 4, 3)  # 4 observations
tmp.a<- scale(tmp.a, center = TRUE, scale = FALSE)
pca.results <- prcomp(tmp.a)
```
By using the code provided in **code segment 1**, I get something like the `cell.embeddings` like
```
pca.results$x / (pca.results$sdev[seq_along(pca.results$sdev)] * sqrt(x = nrow(tmp.a) - 1))
#          [,1]        [,2]        [,3]
#[1,]  -0.2585008 -0.05756193  0.82453865
#[2,]  -1.6775687 -2.37576235 -0.01288034
#[3,] -13.4365327  0.06501603 -0.12261293
#[4,]   0.8513863  0.15651976 -0.02535528
```
But the item in row 2 and 3 of PC1 is not corrected, it should be `c(-0.1688457, -0.4240399)` but now it's `c(-1.6775687, -13.4365327)`. This can be checked by getting PCA by function `irlba` or `svd`, given as
```
tmp.a <- matrix(c(3,2,4,11,1,4,-2,22,-1,0,-5,20), 4, 3)  # 4 observations
tmp.a<- scale(tmp.a, center = TRUE, scale = FALSE)
svd(tmp.a)$u
#$u
#          [,1]        [,2]        [,3]
#[1,] -0.2585008 -0.05756193  0.82453865
#[2,] -0.1688457 -0.74492548 -0.40813865
#[3,] -0.4240399  0.64596766 -0.39104472
#[4,]  0.8513863  0.15651976 -0.02535528
```

So, I propose my solution for change **code segment 1** as
```
if (weight.by.var) {
  cell.embeddings <- pca.results$x
} else {
  cell.embeddings <- t(t(pca.results$x) / (pca.results$sdev[1:npcs] * sqrt(x = ncol(x = object) - 1)))
}
```

**Comment by eturkes** [comment]
Interesting find @jinziyang010, I'm wondering what the status of this is? I see its closed as completed but I don't see a commit. I also don't see the change implemented in the master nor develop branch.

**Comment by jinziyang010** [comment]
Yes, nothing was done for this. In default settings of function `RunPCA.default`, this bug will not affect any of the results.
