### ISSUE TITLE
Why my house keeping gene expression levels are related to nFeature_RNA?

### ISSUE THREAD

**Issue by jiangpuxuan** [satijalab/seurat#5459]
I used the` SCTransform` pipline, and used `RNA` data to do `MAGIC`.
Then I found that the expression levels of  housekeeping gene ACTB and GAPDH of every cluster, have some correlation to the nFeature_RNA.
Here are my plots.
<img width="350" alt="ed032a3bc5c98c59512525183b6c763" src="https://user-images.githubusercontent.com/81287604/148684483-850fa78b-9a71-4a48-bc5c-6f6b58ee42b8.png">

<img width="350" alt="d7aefc84265bad3803d242eb26dad3d" src="https://user-images.githubusercontent.com/81287604/148684489-7cea0f0c-e5a0-4f6c-bec7-f4e3cd62ce3e.png">

'IGDB25506' is ACTB, while 'IGDB15683' is GAPDH.

Thank you for your help!

**Comment by saketkc** [comment]
When using SCTransform, the `data` slot contains the normalized expression (log1p of corrected counts after regressing out library size effects). Can you post your full code here?
