### ISSUE TITLE
subset and got invalid character indexing error 

### ISSUE THREAD

**Issue by ozlembahar** [satijalab/seurat#5468]
Hi,

In the QC step I was filtering out low quality cells via simple subset function:
filtered_seurat <- subset(merged_seurat, 
                          subset = (nUMI >= 500) & 
                            (nGene >= 500) & 
                            (mitoRatio < 0.10) & 
                            (log10GenesPerUMI > 0.80))

And got this error: 

Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) :  invalid character indexing

I am not sure what is wrong and any help or suggestion will be appreciated!
[sessionInfo.txt](https://github.com/satijalab/seurat/files/7839277/sessionInfo.txt)

Best,
Bahar

**Comment by samuel-marsh** [comment]
Hi,

Assuming that your columns are named as provided in code above then try:

```
filtered_seurat <- subset(merged_seurat, subset = nUMI >= 500 & nGene >= 500 & mitoRatio < 0.10
 & log10GenesPerUMI > 0.80)
```

Best,
Sam

**Comment by samuel-marsh** [comment]
What version of Seurat are you using and what version was used to create the Seurat object?

**Comment by ozlembahar** [comment]
I am using the latest version (4.0.6) and used the same version to create the Seurat object.

**Comment by samuel-marsh** [comment]
Can you post the full code you are running from object creation to filtering?

**Comment by ozlembahar** [comment]
Hi,
Thanks a lot! Here is the code:

install.packages('Seurat')
install.packages('Matrix')

require(Seurat)
require(ggplot2)
require(patchwork)
require(sctransform)
require(tidyverse)
require(Matrix)
require(scales)
require(cowplot)
require(RCurl)
require(readr)
require(dplyr)

# Create an individual Seurat object for each sample
for (file in c("s1_tp1_rep1_dm6_UMI.Matrix.txt", "s2_tp2_rep1_dm6_UMI.Matrix.txt", "tp2_r2_dm6_UMI.Matrix.txt")){
  seurat_data <-read_table(paste0("raw_data_tp1_tp2/", file))
  seurat_obj <- CreateSeuratObject(counts = seurat_data, 
                                   min.features = 500, 
                                   project = file)
  assign(file, seurat_obj)
}




# Check the metadata in the new Seurat objects
head(s1_tp1_rep1_dm6_UMI.Matrix.txt@meta.data)
head(s2_tp2_rep1_dm6_UMI.Matrix.txt@meta.data)
head(tp2_r2_dm6_UMI.Matrix.txt@meta.data)

#Merge these objects together into a single Seurat object.
#This will make it easier to run the QC steps for both sample groups together 
#and enable us to easily compare the data quality for all the samples.
merged_seurat <- merge(x = s1_tp1_rep1_dm6_UMI.Matrix.txt, 
                       y = c(s2_tp2_rep1_dm6_UMI.Matrix.txt, tp2_r2_dm6_UMI.Matrix.txt),
                       project="file",
                       add.cell.ids = c("S1TP1", "S2TP2", "S2TP2r"))
merged_seurat

# Check that the merged object has the appropriate sample-specific prefixes
head(merged_seurat@meta.data)
tail(merged_seurat@meta.data)

# Explore merged metadata
View(merged_seurat@meta.data)
#orig.ident: sample identity  
#nCount_RNA: the number of UMIs (unique molecular identifiers-barcodes) per cell
#nFeature_RNA: the number of genes detected per cell

#Pre-processing workflow

##### 1-Calculate the number of genes detected per UMI: #####
# Add number of genes per UMI for each cell to metadata
merged_seurat$log10GenesPerUMI <- log10(merged_seurat$nFeature_RNA) / log10(merged_seurat$nCount_RNA)
##### 2-Calculate mitochondrial ratio #####
# To compute percent mito ratio first retrieve dmel genome annotations
# Install and Connect to AnnotationHub
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("AnnotationHub")
require(AnnotationHub)

ah <- AnnotationHub()

# Access the Ensembl database for organism
ahDb <- query(ah, 
              pattern = c("Drosophila melanogaster", "EnsDb"), 
              ignore.case = TRUE)

# Check versions of databases available
ahDb %>% 
  mcols()


# Acquire the latest annotation files
id <- ahDb %>%
  mcols() %>%
  rownames() %>%
  tail(n = 1)

# Download the appropriate Ensembldb database
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("ensembldb")
require(ensembldb)

edb <- ah[[id]]



# Extract gene-level information from database

annotations <- genes(edb, 
                     return.type = "data.frame")                

# Select annotations of interest
annotations <- annotations %>%
  dplyr::select(gene_id, gene_name, gene_biotype, seq_name, description, entrezid)

View(annotations)    

# Extract IDs for mitochondrial genes
mt <- annotations %>%
  dplyr::filter(seq_name == "mitochondrion_genome") %>%
  dplyr::pull("gene_id")


# Create metadata dataframe
metadata <- merged_seurat@meta.data


# Add cell IDs to metadata
metadata$cells <- rownames(metadata)

head(metadata$cells)
# Create sample column
metadata$sample <- NA
metadata$sample[which(str_detect(metadata$cells, "^S1TP1_"))] <- "S1TP1"
metadata$sample[which(str_detect(metadata$cells, "^S2TP2_"))] <- "S2TP2"
metadata$sample[which(str_detect(metadata$cells, "^S2TP2r_"))] <- "S2TP2r"


# Rename columns
metadata <- metadata %>%
  dplyr::rename(seq_folder = orig.ident,
                nUMI = nCount_RNA,
                nGene = nFeature_RNA)

#Add gene IDs to the count
gene_ids <- seurat_data$GENE
rownames(merged_seurat@assays$RNA@counts) <- gene_ids


# Number of UMIs assigned to mitochondrial genes
metadata$mtUMI <- Matrix::colSums(merged_seurat@assays$RNA@counts[which(rownames(merged_seurat@assays$RNA@counts) %in% mt),], na.rm = T)

# Ensure all NAs receive zero counts
metadata$mtUMI[is.na(metadata$mtUMI)] <- 0

# Calculate of mitoRatio per cell
metadata$mitoRatio <- metadata$mtUMI/metadata$nUMI


# Add metadata back to Seurat object
merged_seurat@meta.data <- metadata
view(merged_seurat@meta.data)
colnames(merged_seurat@meta.data)
# Create .RData object to load at any time
save(merged_seurat, file="data/merged_seurat.RData")


## Assessing the quality metrics in data/QC.rmd
    #Cell counts
    #UMI counts per cell
    #Genes detected per cell
    #UMIs vs. genes detected
    #Mitochondrial counts ratio
   

#load .RData object 
require(miceadds)
load.Rdata(file="data/merged_seurat.RData", "merged_seurat")

#Filter out low quality reads 
filtered_seurat <- subset(merged_seurat, subset = nUMI >= 500 & nGene >= 500 & mitoRatio < 0.10
 & log10GenesPerUMI > 0.80)

**Comment by ozlembahar** [comment]
Hi, I just realized that i am able to subset for nGene and nUMI but not for mitoRatio and log10GenesPerUMI. Not sure if this helps.

**Comment by timoast** [comment]
@ozlembahar what version of Seurat are you using? The `nGene` and `nUMI` columns suggests this might be a v2 object

**Comment by ozlembahar** [comment]
Hi Sam,

Thanks a lot for your suggestions and help. It seems there was actually an issue with my raw data. After checking for NAs, I was able to run subset function without any problems.

Also thanks a lot for adding Drosophila option. It saves a lot of time :) 

Best,
bahar

**Comment by samuel-marsh** [comment]
Glad it worked!!

No problem I actually got couple other requests for it coincidentally at the same time so worked out well!!  Hope you like the package!

Best,
Sam
