### ISSUE TITLE
Feature Request: GetIdent()

### ISSUE THREAD

**Issue by wyattmcdonnell** [satijalab/seurat#547]
Hi there!

The `SetAllIdent()` function is super useful, and it would be great if at some point in the future a similar function `GetIdent()` could be incorporated. Especially as larger datasets such as those from HCA begin to roll out, such a function would be good for users to check that they're matching the right identity before making a huge plot, doing differential expression, etc. 

Skeleton code for this function could be as simple as an alias to something like this: 

```R
unique(seurat.object@ident)
```

Or more complex by using output from above command, and seeing which vector in `seurat.object@meta.data` has unique levels that match. 

Thank you so much!

**Comment by mt1022** [comment]
I am considering writing a simple `GetIdent` function. Here is how it looks like:
```r
GetIdent <- function(object, uniq = TRUE, cells.use = NULL){
    ident <- object@ident
    if(!is.null(cells.use)){
        ident <- ident[names(ident) %in% cells.use]
    }
    if(uniq){
        unique(ident)
    }else{
        ident
    }
}
```
This function will return unique `ident` by default and allows specifying the subset of cells to look at. Are there any other features that should be incorporated?

**Comment by wyattmcdonnell** [comment]
Hi @mt1022 thanks for considering this! I don't have any other thoughts on extra things to incorporate, but maybe @mojaveazure, @andrewwbutler, or others do?

**Comment by mt1022** [comment]
Fine. If no other requirements, I'll try to make a PR on open souce Fridy.
