### ISSUE TITLE
FindTransferAnchors differences between Seurat v3.2.3 and v4.0.4 using SCT

### ISSUE THREAD

**Issue by ClmtHua** [satijalab/seurat#5471]
Hello, 

I re-ran former analysis involving `FindTransferAnchors(reference, query, normalization.method = "SCT") ` I've done using Seurat v3.2.3 with the new version of Seurat v.4.0.4. 
Surprisingly, the results have changed a lot towards the conclusion I expect more but I would like better understand why. 
What I observe is that Seurat v4 find less anchors than v3 (~ 1000 vs ~4000). I suspect that the results with v4 does not suffer from the strong size imbalance in my reference dataset (in v3, I observe a bias toward the most abundant cell types in my reference dataset). I did not observe such difference when using `normalization.method = "LogNormalize"` between v3 and v4.

By looking into the release note, the main change between Seurat v4 and v3 for this function is 

> When using normalization.method='SCT' in FindTransferAnchors(), normalize query using reference SCT model when possible.

Could you explain the rationale behind this change (I did not find any related issue in github) ? If there are any references/publications that have motivated this change ? If it match with the size imbalance issue that is common in supervised ML algorithm ?

Thanks in advance for your attention and thanks for your tool !

**Comment by saketkc** [comment]
hi @ClmtHua The rationale for this change was to make the query pearson residuals more "amenable" to the reference residuals. This is particularly beneficial if the query dataset has only one or a subset of celltypes as compared to the reference dataset. So in short, the changes you observed between V3 and V4 are expected (but for the better). Hope this helps!
