### ISSUE TITLE
Repating analysis from Seurat v4.0.2 on Seurat v4.0.6 didn't work

### ISSUE THREAD

**Issue by JPcerapio** [satijalab/seurat#5472]
**Hello guys,
So it's been some years now that I'm working on single cell analysis and with Seurat.
But after the v4 release I'm just having problems to repeat or re-do some analysis that I did before using v3.**

**This is an example of my code on v4.0.2 that do not work on v4.0.6**

Samples.list <- list(A1.rmOtl,A2.rmOtl,P_YOPOD.rmOtl, A3.rmOtl, A4.rmOtl, A5.rmOtl,A6.rmOtl,A7.rmOtl)
for (i in 1:length(Samples.list)) {
    Samples.list[[i]] <- NormalizeData(Samples.list[[i]], verbose = FALSE)
    Samples.list[[i]] <- FindVariableFeatures(Samples.list[[i]], selection.method = "vst", 
        nfeatures = 3000, verbose = FALSE)
}

Samples.anchors <- FindIntegrationAnchors(object.list = Samples.list)

Samples.integrated <- IntegrateData(anchorset = Samples.anchors)

**I already have the integrated object from v4.0.2, however by runing this pipline in v4.0.6 I have this error after runing FindIntegrationAnchors**

> Samples.anchors <- FindIntegrationAnchors(object.list = Samples.list)
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 73 anchors
Filtering anchors
	Retained  anchors
Erreur dans `[.data.frame`(anchor.df, , 2) : 
  colonnes non définies sélectionnées

**I also tried to moified what you guys change from V4.0.2 to V4.0.6** 
**- Default neighbor finding algorithm changed from “rann” to “annoy”**
**And I have the same error.**

> Samples.anchors <- FindIntegrationAnchors(object.list = Samples.list,nn.method ="rann")
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 73 anchors
Filtering anchors
	Retained  anchors
Erreur dans `[.data.frame`(anchor.df, , 2) : 
  colonnes non définies sélectionnées

**I hope you could let me know what other changes could be giving this error, or if should modify my code for this "new" version of Seurat.** 

**Thank you in advance,**
**Jp**

**Here it is my Session Info:**

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.19.so
LAPACK: /usr/lib/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=fr_FR.utf8        LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.utf8     
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.utf8    
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] future_1.23.0         SeuratDisk_0.0.0.9019 ggplot2_3.3.5        
[4] SeuratObject_4.0.4    Seurat_4.0.6         

loaded via a namespace (and not attached):
  [1] nlme_3.1-153           matrixStats_0.61.0     spatstat.sparse_2.1-0 
  [4] bit64_4.0.5            RcppAnnoy_0.0.19       RColorBrewer_1.1-2    
  [7] httr_1.4.2             sctransform_0.3.2.9011 tools_4.1.2           
 [10] utf8_1.2.2             R6_2.5.1               irlba_2.3.5           
 [13] rpart_4.1-15           KernSmooth_2.23-20     uwot_0.1.11           
 [16] mgcv_1.8-38            DBI_1.1.2              lazyeval_0.2.2        
 [19] colorspace_2.0-2       withr_2.4.3            tidyselect_1.1.1      
 [22] gridExtra_2.3          bit_4.0.4              compiler_4.1.2        
 [25] cli_3.1.0              hdf5r_1.3.5            plotly_4.10.0         
 [28] scales_1.1.1           lmtest_0.9-39          spatstat.data_2.1-2   
 [31] ggridges_0.5.3         pbapply_1.5-0          goftest_1.2-3         
 [34] stringr_1.4.0          digest_0.6.29          spatstat.utils_2.3-0  
 [37] pkgconfig_2.0.3        htmltools_0.5.2        parallelly_1.30.0     
 [40] fastmap_1.1.0          htmlwidgets_1.5.4      rlang_0.4.12          
 [43] shiny_1.7.1            generics_0.1.1         zoo_1.8-9             
 [46] jsonlite_1.7.2         ica_1.0-2              dplyr_1.0.7           
 [49] magrittr_2.0.1         patchwork_1.1.1        Matrix_1.4-0          
 [52] Rcpp_1.0.7             munsell_0.5.0          fansi_1.0.0           
 [55] abind_1.4-5            reticulate_1.22        lifecycle_1.0.1       
 [58] stringi_1.7.6          MASS_7.3-54            Rtsne_0.15            
 [61] plyr_1.8.6             grid_4.1.2             parallel_4.1.2        
 [64] listenv_0.8.0          promises_1.2.0.1       ggrepel_0.9.1         
 [67] crayon_1.4.2           miniUI_0.1.1.1         deldir_1.0-6          
 [70] lattice_0.20-45        cowplot_1.1.1          splines_4.1.2         
 [73] tensor_1.5             pillar_1.6.4           igraph_1.2.11         
 [76] spatstat.geom_2.3-1    future.apply_1.8.1     reshape2_1.4.4        
 [79] codetools_0.2-18       leiden_0.3.9           glue_1.6.0            
 [82] data.table_1.14.2      png_0.1-7              vctrs_0.3.8           
 [85] httpuv_1.6.5           gtable_0.3.0           RANN_2.6.1            
 [88] purrr_0.3.4            spatstat.core_2.3-2    polyclip_1.10-0       
 [91] tidyr_1.1.4            scattermore_0.7        assertthat_0.2.1      
 [94] mime_0.12              xtable_1.8-4           later_1.3.0           
 [97] survival_3.2-13        viridisLite_0.4.0      tibble_3.1.6          
[100] cluster_2.1.2          globals_0.14.0         fitdistrplus_1.1-6    
[103] ellipsis_0.3.2         ROCR_1.0-11

**Comment by yuhanH** [comment]
Hi
It seems that there might be too few anchors left after filtering.
You can set k.filter to NA to skip the filter anchor steps. 
`FindIntegrationAnchors(object.list = Samples.list,  k.filter = NA  )`

**Comment by JPcerapio** [comment]
Hello @yuhanH,
sorry for the delay in answering, effectively the problem is coming for the low numbers of anchors left.
But, I already run this analysis in a previous version of R **(v4.0.5)** and it worked perfectly, since I pass this version **4.0.6,** and even in the actual version **4.1.2**, this analysis didn't work.

So, my fast solution was until now to keep using **R v4.0.5**, and test if it work again in some of the new versions of R.

I don't know what have changed from 4.0.5 to the latest version, that it did not find anchors using Seurat.

And as you suggest "k.filter = NA" works, but the **number of anchors between the 2 versions of R is just amazing**:

Number of anchors found by "FindIntegrationAnchors" in

**R v4.0.5 looks like:**
> Samples.anchors <- FindIntegrationAnchors(object.list = Samples.list)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10544 anchors
Filtering anchors
	Retained 1969 anchors
  |++                                                | 4 % ~24m 46s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10184 anchors
Filtering anchors
	Retained 1872 anchors
  |++++                                              | 7 % ~23m 55s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 17484 anchors
Filtering anchors
	Retained 2957 anchors
  |++++++                                            | 11% ~38m 60s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 8450 anchors
Filtering anchors
	Retained 1825 anchors
  |++++++++                                          | 14% ~32m 36s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10993 anchors
Filtering anchors
	Retained 2812 anchors
  |+++++++++                                         | 18% ~34m 04s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10085 anchors
Filtering anchors
	Retained 2908 anchors
  |+++++++++++                                       | 21% ~31m 18s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9097 anchors
Filtering anchors
	Retained 2598 anchors
  |+++++++++++++                                     | 25% ~27m 06s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 12583 anchors
Filtering anchors
	Retained 3976 anchors
  |+++++++++++++++                                   | 29% ~26m 45s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 12329 anchors
Filtering anchors
	Retained 3249 anchors
  |+++++++++++++++++                                 | 32% ~25m 36s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9807 anchors
Filtering anchors
	Retained 2555 anchors
  |++++++++++++++++++                                | 36% ~23m 37s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9211 anchors
Filtering anchors
	Retained 2513 anchors
  |++++++++++++++++++++                              | 39% ~21m 20s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 13290 anchors
Filtering anchors
	Retained 3178 anchors
  |++++++++++++++++++++++                            | 43% ~20m 26s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 12536 anchors
Filtering anchors
	Retained 3184 anchors
  |++++++++++++++++++++++++                          | 46% ~19m 13s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9938 anchors
Filtering anchors
	Retained 2648 anchors
  |+++++++++++++++++++++++++                         | 50% ~17m 37s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10464 anchors
Filtering anchors
	Retained 2347 anchors
  |+++++++++++++++++++++++++++                       | 54% ~15m 59s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9636 anchors
Filtering anchors
	Retained 1856 anchors
  |+++++++++++++++++++++++++++++                     | 57% ~14m 16s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 14607 anchors
Filtering anchors
	Retained 2636 anchors
  |+++++++++++++++++++++++++++++++                   | 61% ~13m 33s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 13916 anchors
Filtering anchors
	Retained 2481 anchors
  |+++++++++++++++++++++++++++++++++                 | 64% ~12m 16s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 11212 anchors
Filtering anchors
	Retained 1871 anchors
  |++++++++++++++++++++++++++++++++++                | 68% ~10m 49s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 11248 anchors
Filtering anchors
	Retained 2318 anchors
  |++++++++++++++++++++++++++++++++++++              | 71% ~09m 25s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 11525 anchors
Filtering anchors
	Retained 2133 anchors
  |++++++++++++++++++++++++++++++++++++++            | 75% ~08m 07s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 8444 anchors
Filtering anchors
	Retained 1896 anchors
  |++++++++++++++++++++++++++++++++++++++++          | 79% ~06m 45s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 11384 anchors
Filtering anchors
	Retained 2352 anchors
  |++++++++++++++++++++++++++++++++++++++++++        | 82% ~05m 42s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 11048 anchors
Filtering anchors
	Retained 2316 anchors
  |+++++++++++++++++++++++++++++++++++++++++++       | 86% ~04m 34s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9734 anchors
Filtering anchors
	Retained 1711 anchors
  |+++++++++++++++++++++++++++++++++++++++++++++     | 89% ~03m 24s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9469 anchors
Filtering anchors
	Retained 2000 anchors
  |+++++++++++++++++++++++++++++++++++++++++++++++   | 93% ~02m 14s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9632 anchors
Filtering anchors
	Retained 2002 anchors
  |+++++++++++++++++++++++++++++++++++++++++++++++++ | 96% ~01m 06s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10506 anchors
Filtering anchors
	Retained 2184 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=30m 36s



**and in R v4.1.2 (k.filter=NA):**
> Samples.anchors <- FindIntegrationAnchors(object.list = Samples.list, k.filter=NA)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 70 anchors
  |++                                                | 4 % ~03m 20s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 65 anchors
  |++++                                              | 7 % ~03m 00s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 75 anchors
  |++++++                                            | 11% ~03m 16s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 81 anchors
  |++++++++                                          | 14% ~02m 56s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 53 anchors
  |+++++++++                                         | 18% ~02m 54s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 60 anchors
  |+++++++++++                                       | 21% ~02m 46s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 112 anchors
  |+++++++++++++                                     | 25% ~02m 34s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 90 anchors
  |+++++++++++++++                                   | 29% ~02m 30s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 51 anchors
  |+++++++++++++++++                                 | 32% ~02m 21s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 61 anchors
  |++++++++++++++++++                                | 36% ~02m 12s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 106 anchors
  |++++++++++++++++++++                              | 39% ~02m 01s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 264 anchors
  |++++++++++++++++++++++                            | 43% ~01m 56s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 155 anchors
  |++++++++++++++++++++++++                          | 46% ~01m 48s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 63 anchors
  |+++++++++++++++++++++++++                         | 50% ~01m 43s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 235 anchors
  |+++++++++++++++++++++++++++                       | 54% ~01m 36s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 51 anchors
  |+++++++++++++++++++++++++++++                     | 57% ~01m 28s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 152 anchors
  |+++++++++++++++++++++++++++++++                   | 61% ~01m 21s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 137 anchors
  |+++++++++++++++++++++++++++++++++                 | 64% ~01m 16s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 219 anchors
  |++++++++++++++++++++++++++++++++++                | 68% ~01m 08s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 70 anchors
  |++++++++++++++++++++++++++++++++++++              | 71% ~01m 02s      Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 76 anchors
  |++++++++++++++++++++++++++++++++++++++            | 75% ~57s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 60 anchors
  |++++++++++++++++++++++++++++++++++++++++          | 79% ~48s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 176 anchors
  |++++++++++++++++++++++++++++++++++++++++++        | 82% ~40s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 57 anchors
  |+++++++++++++++++++++++++++++++++++++++++++       | 86% ~32s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 73 anchors
  |+++++++++++++++++++++++++++++++++++++++++++++     | 89% ~24s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 60 anchors
  |+++++++++++++++++++++++++++++++++++++++++++++++   | 93% ~16s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 105 anchors
  |+++++++++++++++++++++++++++++++++++++++++++++++++ | 96% ~08s          Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 76 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03m 40s

Thanks
