### ISSUE TITLE
"orig.ident" as latent variable for MAST

### ISSUE THREAD

**Issue by RMOsborn012** [satijalab/seurat#5477]
I am having trouble passing "orig.ident" for the ``` latent.vars``` argument in ``` FindMarkers ``` using the MAST method. The consensus from reading #313, #3884, and #4084 was to update Seurat, but I am using a later version than what was suggested at the time (currently using version 4.0.6).

I am using the following code.

```r
de <- FindMarkers(object, ident.1 = "one", ident.2 = "two", verbose = FALSE, test.use = "MAST", latent.vars = "orig.ident")
```

I am getting the following error with no output.

```r
Done!
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In .nextMethod(object = object, value = value) :
  Coefficients orig.identD258m are never estimible and will be dropped.
```

Not sure if this makes a difference, but the "D258m" in the error is one of my fourteen original identities. All of the identities are formatted the same way with different numbers (D***m). However, "D258m" is not the first or last identity in the metadata column or numerically. 

```r
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SeuratObject_4.0.4          Seurat_4.0.6                MAST_1.16.0                
 [4] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0 Biobase_2.50.0             
 [7] GenomicRanges_1.42.0        GenomeInfoDb_1.26.7         IRanges_2.24.1             
[10] S4Vectors_0.28.1            BiocGenerics_0.36.1         MatrixGenerics_1.2.1       
[13] matrixStats_0.61.0         
```

**Comment by GouQiao** [comment]
> I am having trouble passing "orig.ident" for the ` latent.vars` argument in `FindMarkers` using the MAST method. The consensus from reading #313, #3884, and #4084 was to update Seurat, but I am using a later version than what was suggested at the time (currently using version 4.0.6).
> 
> I am using the following code.
> 
> ```r
> de <- FindMarkers(object, ident.1 = "one", ident.2 = "two", verbose = FALSE, test.use = "MAST", latent.vars = "orig.ident")
> ```
> 
> I am getting the following error with no output.
> 
> ```r
> Done!
> Error: $ operator is invalid for atomic vectors
> In addition: Warning message:
> In .nextMethod(object = object, value = value) :
>   Coefficients orig.identD258m are never estimible and will be dropped.
> ```
> 
> Not sure if this makes a difference, but the "D258m" in the error is one of my fourteen original identities. All of the identities are formatted the same way with different numbers (D***m). However, "D258m" is not the first or last identity in the metadata column or numerically.
> 
> ```r
> > sessionInfo()
> R version 4.0.5 (2021-03-31)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] SeuratObject_4.0.4          Seurat_4.0.6                MAST_1.16.0                
>  [4] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0 Biobase_2.50.0             
>  [7] GenomicRanges_1.42.0        GenomeInfoDb_1.26.7         IRanges_2.24.1             
> [10] S4Vectors_0.28.1            BiocGenerics_0.36.1         MatrixGenerics_1.2.1       
> [13] matrixStats_0.61.0         
> ```

I got same Error: $ operator is invalid for atomic vectors.
Did you figure out how to deal with this?

**Comment by saketkc** [comment]
This must have been fixed in the `develop` branch. Can you try with the latest develop?
https://satijalab.org/seurat/articles/install.html

Feel free to reopen if there are followup issues.
