### ISSUE TITLE
Interpretation of 'percent expressed' in Dot plot

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#5480]
Hello :)

I have one question about interpretation of dot plot.

In dot plot, we can see two parameters. One is 'Average expression', the other is 'Percent expressed'.

I'm confusing about 'percent expressed' meaning. I understand "How many cells were expressed in specific cluster". In this case, how can it calculated such as "expressed" ? If expression of one cell is more than 0, is it counted expressed cell? I want to know detailed cutoff. Because ratio of expressed cell in our study is crucial, I want to change cutoff setting of percent expressed whether it is possible!

Thank you in advance!

Best,
Dahun

**Comment by dahun73** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. Yes the calculation is based on any cell with counts greater than 0. You can find relevant source code here:
> 
> https://github.com/satijalab/seurat/blob/8da35ba8dc2d60f504f7cf276efd684dc19a418c/R/visualization.R#L3505-L3506
> 
> https://github.com/satijalab/seurat/blob/8da35ba8dc2d60f504f7cf276efd684dc19a418c/R/utilities.R#L1121-L1123
> 
> Unfortunately, for DotPlot setting a threshold is currently possible.
> 
> Best, Sam

Hello Sam,

Thank you so much!! You saved me twice!!

At last sentence,  you mean that it is impossible for setting a threshold in dotplot, right?

Thank you for your kind explanation, again. 

Best,
Dahun

**Comment by yuhanH** [comment]
Thanks @samuel-marsh  for your clear explanation. 

HI @dahun73      The threshold for the percentAbove in DotPlot is fixed as 0. The percent expressed can only means percent of above-zero cells.
