### ISSUE TITLE
Which slot to calculate gene-gene similarity matrix?

### ISSUE THREAD

**Issue by PartickXu** [satijalab/seurat#5484]
I have two spatial seq sample, one condition and one control. I want to make a transcriptome-wide correlation matrix to detect some gene modules, and further distinguish their origin of anatomy or disease by average expression on spatial. Which slot and assay should I use for this work? 
I have used raw counts data, normalized data (which seems will not be affected when merged), and three slot of SCTransformed assay including correlated counts, data, scale.data. All these data result in a sparse pattern heatmap. Count data will give me a heatmap with much more positive pixel than negative, so I tried to use normalized or scaled data. And these two kind of data contribute to a heatmap with balance but sparse pattern, even after I cut the number of genes by many approach (findvariablefeatures, set lowest expressed spots number, cut variation of non-zero count, set variable.features.rv.th in sctransform, etc.) to make a heatmap  more informative.
Questions:
1. Which slot and assay should I use for this work? 
2. If SCT assay is suitable, should I rerun sctransform after merged? 
3. Should I integrate two sample and use integrated data for making gene-gene similarity matrix? 
Thank you so much.
<img width="699" alt="Screenshot 2022-01-13 at 00 34 55" src="https://user-images.githubusercontent.com/11521358/149182232-3c47adfb-ab04-4af2-8442-7e82d715478c.png">
The picture shows a heatmap built by sct data slot (not scale.data), about 9000 genes, sctransformed after merged (not cca or rpca, just merged).

**Comment by torkencz** [comment]
Hi, while I have no definite answer for you I would likely use the counts or the normalized counts (sct or standard pipeline would work as well, probably run sct before merging). If you have strong batch effects then you can try using integration to group cells together, but we do not advise to use the integrated data to id GRNs. There are also other established methods for this that I would search for.
