### ISSUE TITLE
Duplicate cell name error in MergeSeurat tutorial

### ISSUE THREAD

**Issue by matthew-langley** [satijalab/seurat#549]
Seurat version: 2.3.2 
R version: 3.5.0

Issue:
I attempted to run the code provided in the ["Seurat - Combining Two 10X Runs" tutorial](https://satijalab.org/seurat/merge_vignette.html), but got the following error:
```
> library(Seurat)
> 
> pbmc4k.data <- Read10X(data.dir = "pbmc4k_filtered_gene_bc_matrices/filtered_gene_bc_matrices/GRCh38/")
> pbmc4k <- CreateSeuratObject(raw.data = pbmc4k.data, project = "PBMC4K")
> 
> pbmc8k.data <- Read10X(data.dir = "pbmc8k_filtered_gene_bc_matrices/filtered_gene_bc_matrices/GRCh38/")
> pbmc8k <- CreateSeuratObject(raw.data = pbmc8k.data, project = "PBMC8K")
> pbmc.combined <- MergeSeurat(object1 = pbmc4k, object2 = pbmc8k, add.cell.id1 = "4K", add.cell.id2 = "8K", project = "PBMC12K")
Error in MergeSeurat(object1 = pbmc4k, object2 = pbmc8k, add.cell.id1 = "4K",  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names
```

The error message disagrees with the command, since both `add.cell.id1 = "4K"` and `add.cell.id2 = "8K"` were provided.

**Comment by andrewwbutler** [comment]
Hi Matthew,

This should be fixed now on the develop branch ([installation instructions](https://satijalab.org/seurat/devinstall.html)).
