### ISSUE TITLE
Genes removed during data integration?

### ISSUE THREAD

**Issue by cv55** [satijalab/seurat#5493]
Hello, I want to integrate 5 datasets in one and estimate the expression of specific genes. After I do the integrations a lot of the genes I am interested in are removed, even though they are present in the filtered datasets.

Any explanation what causes this?

**Comment by yuhanH** [comment]
One possible explanation is that your target genes are not the variable genes for all datasets. 
But you can add your target genes into the anchor.features in the `FindIntegrationAnchors`.
