### ISSUE TITLE
Average expression across multiple clusters of interest.

### ISSUE THREAD

**Issue by NewtontheNeuron** [satijalab/seurat#5495]
Hello,

I am trying to compute the average expression across multiple clusters for a particular gene of interest. I have developed some code to use the data stored in the @assays$RNA@data slot of my Seurat object as well as some information from other slots as well. However, my calculated average expression is always less than the Average Expression calculated by Seurat. Furthermore, the average expression Seurat calculates if far greater than maximum of all the raw data. Unfortunately, I could not replicate that last issue with the pbmc data set but I hope you can appreciate that there is a discrepancy.

Bellow, I have shared a similar minimal reproducible code using the pbmc data set. The first part is the analysis pipeline from [the pbmc3k tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) just so I can have some clusters to average. The second part is the code that I developed to compute the average.

Part 1
```R
# This is a minimaly reproducible version of my average expression calcualtion error

library(dplyr)
library(Seurat)
library(patchwork)

pbmc.data <- Read10X(data.dir = "../../../../Neuroscience - MSc/single cell RNA seq/filtered_gene_bc_matrices/hg19") # change the path
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- JackStraw(pbmc, num.replicate = 100)
pbmc <- ScoreJackStraw(pbmc, dims = 1:20)   
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
```

Part 2
```R
# This is where my question starts. I am trying to average the gene expression
# across multiple clusters of interest for a given set of transcripts
# Bellow is the code I used to do that

GeneofInterest <- 'CD83'
GeneIndicies <- match(GeneofInterest, unlist(pbmc@assays$RNA@data@Dimnames[1]))
CellIndicies <- which(unlist(pbmc@meta.data$seurat_clusters) %in% c('0', '1'))
Transcript_exp <- GetAssayData(pbmc, assay = 'RNA', slot = 'data')[GeneIndicies, CellIndicies]
raw.avg <- mean(Transcript_exp)
# gives similar info to the avg.exp collumn in the dotplot$data
seu.avg <- AverageExpression(pbmc, assays = 'RNA', features = GeneofInterest)
calc.avg <- mean(0.3227995, 0.645101)
max.exp <- max(unlist(pbmc@assays$RNA@data@x))
match(max.exp, unlist(pbmc@assays$RNA@data@x))
#The maximum expression level from the raw data is:
max.exp
#The average caluclated from the raw data is:
raw.avg
#The averages calculated from by Seurat is:
seu.avg # This gives the average for all 9 clusters
#Therfore it would be
seu.avg <- mean(unlist(seu.avg)[c(1,2)]) # This gives the average for only the clusters 0 and 1
# The average that I calculated with the raw values is always less than
# the average calculated by seurat
seu.avg > raw.avg
```

My issue is similar but not the same as the following two issues:

- [issues 2798](https://github.com/satijalab/seurat/issues/2798)
- [issues 1480](https://github.com/satijalab/seurat/issues/1480)

My issue differs because I am not looking for the scaled average expression here.

Please let me know what assistance you can give me. Is there another way to do compute the averages across multiple clusters without just taking an average of averages (that would be challenging statistically)?

I am using R v3.6.1 Seurat v3.2.2

**Comment by mhkowalski** [comment]
Hi, 

If you want to calculate the average across two clusters of interest, you should not take the average of the two cluster averages, as the clusters contain different numbers of cells and therefore will not result in the same answer as how you calculate in ```raw.avg``` . 

Furthermore, running ```AverageExpression``` on the data slot exponentiates the features prior to averaging, as noted in the function documentation. Therefore, if you want to match the results from ```AverageExpression```, you should do something like
```mean(expm1(Transcript_exp))```

**Comment by NewtontheNeuron** [comment]
Hi,

Thank you for your answer. I tried your suggestion and the output now makes more sense to me. After doing some reading and looking at some old issues with `expm1` as the search term. I get now that the raw counts are actually (log e) + 1 transformed. Therefore, the `expm1` takes them out of (log base e) +1 scale.

It seems there were a lot of old questions that are quite similar (i.e. asking about the log and normalization). Perhaps someone could compile them into a webpage explaining them.

Anyway, thanks again for  your answer.
