### ISSUE TITLE
reference model in SCTransform

### ISSUE THREAD

**Issue by LidiaML** [satijalab/seurat#5499]
Dear Seurat developers and users,

I have encountered an unexpected behaviour when providing a reference model to SCTransform. If I understood correctly, we should be able to compute the residuals for an input object using a precomputed SCT model without estimating the parameters of the regression model from the input itself. If this is correct, I should obtain exactly the same residuals if I provide to SCTransform both a reference model and the same input that I used to fit the model. This seems not to be the case. I obtain highly concordant results (average correlation coefficient around 0.99) but not exactly the same. Am I missing something?

My objective is to use a subset of genes to estimate the regression parameters, store the model, and use it to get the residuals for the whole dataset. Is this the best way of proceeding?
 
Find below a reproducible example, in which I would expect to obtain the same residuals in seu_sct1 and seu_sct2.

Thank you in advance!

```
library('Seurat')
library('SeuratData')

InstallData("pbmc3k")
LoadData("pbmc3k")

seu <- pbmc3k
genes_cell_count <- rowSums(GetAssayData(seu, assay="RNA", slot="count") >= 0.01)
genes <- rownames(seu)[genes_cell_count >= 5] #13,714 -> 12,572
seu <- subset(seu,features=genes) 

seu_sct1<- SCTransform(seu, verbose = TRUE,return.only.var.genes = FALSE)
sct.model <- seu_sct1@assays$SCT@SCTModel.list$model1
seu_sct2 <- SCTransform(seu,reference.SCT.model =sct.model,verbose=TRUE,return.only.var.genes = FALSE)

comp <- diag(cor(as.matrix(GetAssayData(seu_sct1, assay="SCT", slot="data")),as.matrix(GetAssayData(seu_sct2, assay="SCT", slot="data"))))

```

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
