### ISSUE TITLE
Change subtitle when using DimPlot with split.by = "orig.ident"

### ISSUE THREAD

**Issue by cjhatch** [satijalab/seurat#5510]
Hi, 

Thanks so much for this amazing tool! I am using the code below to use DimPlot with split.by to visualize data side by side. I would like to be able to change the text size of the subtitles (i.e. CTRL and STIM), but I am unable to accomplish this through changing the plot.title or plot.subtitle element_text. Is there a way to do this without outputting individual plots and manually formatting with patchwork?

Thanks!

```{r}
DimPlot(immune.combined, reduction = "umap", label = F, pt.size = 2, split.by = "stim")  +
  theme(
    plot.subtitle = element_text(face = "bold", size = 20),
    plot.title = element_text(size = 24)
  )
```
![Screen Shot 2022-01-17 at 7 14 56 PM](https://user-images.githubusercontent.com/65783882/149864657-21d7862a-74ad-438d-b99b-d075cc3cc667.png)

**Comment by yuhanH** [comment]
You can use `strip.text.x` to control the font of splitted variable names (CTRL and STIM)
`theme(strip.text.x = element_text(size = 20, face = "bold") )`

**Comment by cjhatch** [comment]
Wonderful that worked, thank you so much!
