### ISSUE TITLE
Cannot figure out how to remove sample

### ISSUE THREAD

**Issue by rbutleriii** [satijalab/seurat#5511]
I can't figure out how to drop a sample from a SeuratObject by name, i.e.
```
sc <- subset(sc, select = -`B365_377_TTTACGTGTGCATACT-1`)
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  That looks like a barcode, are you trying to remove a specific cell from the object or a sample?

Best,
Sam

**Comment by rbutleriii** [comment]
A specific cell

**Comment by rbutleriii** [comment]
Great, thanks!
