### ISSUE TITLE
High-confidence threshold for mapping score 

### ISSUE THREAD

**Issue by orange-whale** [satijalab/seurat#5513]
Hi

I have a single-cell dataset, which I have annotated using reference-mapping as described in the seurat Mapping and annotating query datasets vignette. 

I would like to select the cells that are represented with high confidence by the reference, which threshold do you recommend to use for the mapping score, to select cells these cells?

**Comment by mhkowalski** [comment]
Hi, 

We don't recommend a particular threshold, but you could inspect the distribution of the prediction score by looking at a violin plot of the prediction scores by cell type and choose a threshold based off of this. If there are cell types that are low scoring, you may want to inspect expression of some marker genes to see if you believe the annotations.
