### ISSUE TITLE
Reproducible visualizations tSNE and UMAP

### ISSUE THREAD

**Issue by kramerrs** [satijalab/seurat#5514]
Would it be possible to distribute the visualizations in a more reproducible friendly manner?

We have been trying to reproduce UMAP and tSNE plots from Seurat.  This is not a simple set the seed problem.  We can reproduce the plots on the same platform setting seeds.  The problem appears to be some combination of software package versions and underlying hardware implementations.  We have been trying to use renv and or Conda with Docker containers.  However, a sticking point is that the UMAP algorithm used by Seurat is in a python package, so while we are able to compile R packages to a numerical standard Blas, Lapack, libfortran etc.  We have to figure out some way to get Python installed via reticulate to also use the same packages, and the python packages seem to have conflicting numerical libraries like libfortran.

How hard would it be to use the Uwot package or something similar that doesn't require all of these python dependencies, as well as provide some unit tests to ensure that the packages are functioning to a standard in the installation.

I am writing for this feature, because our group was thinking that most of the single Cell publications will have similar reproducibility problems.

**Comment by timoast** [comment]
As Sam correctly pointed out, `uwot` is the default method used by Seurat. I'll update the documentation since it currently says "To run, you must first install the umap-learn python..." which is only true if you want to use `umap-learn` and might be the reason for the confusion

**Comment by kramerrs** [comment]
Hi All, thank you Sam's comment was very helpful.  Unfortunately we are using an older version of Seurat for non-technical reasons.  I would like to know when that change was made.  My documentation currently says umap-learn.  We will be able to upgrade in the near future, hopefully.  I gather that it was actually UMAP-learn in Seurat 3 for example.

**Comment by samuel-marsh** [comment]
Hi @kramerrs uwot was added as default method in Seurat 3.1.0 (2019-08-20) [Release Notes Here](https://github.com/satijalab/seurat/blob/master/NEWS.md#seurat-310-2019-08-20).

Best,
Sam

**Comment by kramerrs** [comment]
It looks like 3.1.4 version we are using is with uwot, so unfortunately we are still observing cross platform issues reproducing the tSNE and UMAP.  Though it is good to know that I can isolate that issue.

**Comment by samuel-marsh** [comment]
Hmmm are all other package versions the same?  Are any other steps of the pipeline using steps requiring communication out to other python packages?

Best,
Sam

**Comment by kramerrs** [comment]
Hi Sam,

I think the point of the article is that we have gone to some lengths to try to reproduce these tSNE and UMAP, which happen to be very sensitive to reproduce exactly, including: installing same OS in a docker container, installing exact packages and builds(600+) packages underlying libraries etc.  The sprawling nature of Seurat means there are over one hundred dependencies.  Furthermore, depending on the platform there may be non-deterministic numerical threaded routines, BLAS and LAPACK, which we have attempted to recreate when possible, though the python installs have their own set of duplicated numerical routines.  While, in general we can manage this, the sense is that Seurat packages are not very reproducible, by your average single Cell biologist, and the package structure itself bears some responsibility for this.

One thing that I can think of to help if there were some sort of unit tests.  For example, the base package provides tools::testpackage that we have been using to trouble shoot the R compilation.  Maybe also something like sessionInfo, to provide key packages for reproducing the libraries, specifically for Seurat.

**Comment by timoast** [comment]
Minor differences in numerical precision due to different hardware can propagate into larger differences in the result of stochastic algorithms like tSNE and UMAP. This is not something specific to Seurat.

Seurat does include unit tests (not for every function, but we do have tests for RunTSNE and RunPCA), you can find these in the `tests` directory and run them using `devtools::test()`.

**Comment by kramerrs** [comment]
Not to quibble, but I want it understood.  It is the combination of numerically sensitive algorithms and extensive dependencies that makes Seurat especially difficult to work with and get reproducible results, something that an unsuspecting audience consuming the results of an analysis, or even analysts not especially inclined to nuance of numerical routines may not be either understanding of or comfortable with.  I will look into the unit tests though, thank you.

**Comment by VisuMap** [comment]
A more meaningful requirement for reproducibility is: similar input data should yield similar results. In this sense any attempt to just fix the execution environment won't work. The issue needs to be addressed at the side of the algorithm.
