### ISSUE TITLE
Control for cell cycle effect on FastMNN integrated scTransformed data  

### ISSUE THREAD

**Issue by gsmuir** [satijalab/seurat#5518]
Control for cell cycle effect on FastMNN integrated scTransformed data 

I’m trying to use the RunFastMNN wrapper to integrate multiple samples. I can regress out the cell cycle effect using scTransform in the merged dataset (top row), however, after integration with MNN, the cell cycle effect is very strong (bottom row).  

I see advice in #4187 is to calculate cell cycle scores using the integrated data, and then using ScaleData to regress out the scores. My understanding is that you should not use ScaleData after using scTransform as this will overwrite the scTransform model residuals. 

So my question is how can I integrate my samples with FastMNN whilst controlling for the cell cycle effect?

Thanks,

![fMNN_example](https://user-images.githubusercontent.com/56965298/150173119-8d852b5f-8f9f-4277-a920-6d08a2948bec.png)

```
features <- SelectIntegrationFeatures(object.list = seu.set, selection.method = "vst", nfeatures = num.variable.features)
seu.set <- PrepSCTIntegration(object.list = seu.set, anchor.features = features)
seu.set <- Reduce(merge,seu.set)
seu.set <- SCTransform(
	seu.set, 
	return.only.var.genes = F, 
	verbose = T, 
	vars.to.regress = c("G2M.Score", "S.Score"),
	assay = "RNA",
	new.assay.name = "SCT",
	variable.features.n = num.variable.features
)
seu.set <- RunPCA(seu.set, verbose = F,assay = "SCT")
seu.set <- RunUMAP(seu.set, dims = 1:n.integration.dimensions, return.model = T, umap.method = 'uwot')

seu.pdx <- RunFastMNN(
	object.list = SplitObject(
		DietSeurat(seu.set),
		split.by = "orig.ident"
	),
	verbose = T, 
	reconstructed.assay = "mnnreconstructed",
	features = num.variable.features
)

seu.pdx[["mnn"]] <- CreateDimReducObject(Embeddings(seu.pdx, reduction = "mnn"), assay = "SCT")
seu.pdx <- RunUMAP(seu.pdx, reduction = "mnn", dims = 1:n.integration.dimensions, return.model = T, umap.method = 'uwot')
seu.pdx <- FindNeighbors(seu.pdx, reduction = "mnn", dims = 1:n.integration.dimensions)
seu.pdx <- FindClusters(seu.pdx, resolution = 0.35)

p1.merged <- DimPlot(seu.set, label = T,group.by = "Phase") & NoLegend() &  ggtitle(paste0("Phase merged"))
p2.merged <- DimPlot(seu.set, group.by = "orig.ident") & NoLegend() & ggtitle(paste0("orig.ident merged"))

p1.integrated <- DimPlot(seu.pdx, label = T,group.by = "Phase") & NoLegend() & ggtitle(paste0("Phase fastMNN"))
p2.integrated <- DimPlot(seu.pdx, group.by = "orig.ident") & NoLegend() & ggtitle(paste0("orig.ident fastMNN"))

fmnn.plots  <- CombinePlots(list(p1.merged, p2.merged, p1.integrated, p2.integrated ),ncol = 2)
fmnn.plots
```

**Comment by rsatija** [comment]
Unfortunately we do not support this. When using Seurat v5 integration functions (such as CCA or RPCA integration), you can first correct for cell cycle, and then when performing integration - it will preserve this correction. However, fastMNN correction reruns dimensional reduction, which will remove the cell cycle correction.
