### ISSUE TITLE
The size of the cell embedding matrix is not the same size as the number of cells  in the UMAP 

### ISSUE THREAD

**Issue by Toby132** [satijalab/seurat#5519]
I have used Seurat to create a UMAP of the cells to show the separation in low dimensional space, and everytime I have done this, the size of the 2D embedding is the same size as the number of cells. Except this time, the embedding is missing approximately 1000 cells in the dataset. I was wondering why these cells did not have the coordinates of the embedding in the UMAP?

**Comment by timoast** [comment]
Can you provide a reproducible example?
