### ISSUE TITLE
Finding clusters from WNN (combined RNA/ATAC), not from RNA or ATAC clusters separately 

### ISSUE THREAD

**Issue by annamarie67** [satijalab/seurat#5523]
Hello, 
I am writing this question as a follow up to #5063 because the given answer did not answer what the question was asking, and I still have the same question.
I am trying to follow the WNN vignette here https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html
After the steps below, I would like to annotate my clusters based on the WNN clusters. 

H3_RNA <- FindMultiModalNeighbors(H3_RNA, reduction.list = list("pca", "lsi"), dims.list = list(1:16, 2:16))
H3_RNA <- RunUMAP(H3_RNA, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
H3_RNA <- FindClusters(H3_RNA, graph.name = "wsnn", algorithm = 3, verbose = FALSE, resolution = 3)

Then I moved on to plot the UMAPs:
p1 <- DimPlot(H3_RNA, reduction = "umap.rna", label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("RNA")
p2 <- DimPlot(H3_RNA, reduction = "umap.atac", label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("ATAC")
p3 <- DimPlot(H3_RNA, reduction = "wnn.umap", label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("WNN")
p1+p2+p3

There are clear differences between the cluster output for RNA, ATAC, and WNN for my personal dataset. I would like to use the genes from the WNN clusters for my annotations. 

However, If I do the following, I believe I am only getting markers from the RNA portion of the analysis/ RNA generated clusters, and not the WNN clusters. The same concern would be present with only doing ATAC markers. 

allmarkers.rna <- FindAllMarkers(H3_RNA, assay = 'RNA', only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
allmarkers.atac<- FindAllMarkers(H3_RNA, assay = 'ATAC')

My PI suggested that I set the default assay to WNN, however, WNN is not an assay in the H3_RNA seurat object. 
allmarkers.wnn <-FindAllMarkers(H3_RNA, assay ='WNN') (doesn't work)

Is there any way to find the genes associated with the clusters coming out from the WNN graph?

**Comment by timoast** [comment]
The WNN clustering is a set of cell identities, not an assay. You can set the `group.by` parameter in `FindMarkers()` to specify how the cells are being grouped together (eg, use the WNN clusters or something else). If you don't set the `group.by` parameter, the cells are grouped by the active identities, which you can see by running `Idents()` on the Seurat object. So basically the answer to the previous issue was correct: to find markers among the same groups of cells using different assays, change the `assay` parameter in `FindMarkers()` while leaving the cell groupings the same.
