### ISSUE TITLE
Incorporating subcluster information back to metadata

### ISSUE THREAD

**Issue by shanisa11** [satijalab/seurat#5524]
I've analyzed a couple of scRNA-seq libraries using the Seurat vignette and labeled the clusters according to specific cell markers. The original object is named `data.integrated`

For some of the clusters, I've noticed more than one cell type, so I created a subcluster named `immune.subcluster `and labeled the subclusters separately:

```
immune.subcluster <- subset(data.integrated, idents = c("6", "9","11","13"))
immune.subcluster <- FindNeighbors(immune.subcluster, dims = 1:10)
immune.subcluster <- FindClusters(immune.subcluster, resolution = 0.5)
immune.subcluster <- RenameIdents(object = immune.subcluster, '0' = 'Cd8T Cells', "1" = "Cd4T Cells", "2" = "Adipocytes", "3" = "ILC2", "4" = "NK Cells", "5" = "NKT Cells",  "7" = "T Cells", "11" = "B Cells")
immune.subcluster <- RenameIdents(object = immune.subcluster, '6' = "Treg Cells", '8' = "unspesific", '9' = "unspecific", '10' = "unspesific")
immune.subcluster <- RenameIdents(object = immune.subcluster, 'unspecific' = "unknown")
```
Now, I want to replace clusters 6,9,11,13 in the original object with the 9 subclusters I previously labeled on `immune.subcluster`.  How can I replace the old clusters with the new ones?

I assume I need to create a loop that finds the cell barcode and replaces its ident accordingly, but I am not sure how to access that information through metadata.

I already used the solution offered in issue #1748, but it only adds the subcluster metadata to the original object and not actually replace the clusters

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What do you mean by replace the clusters?  You have already renamed the clusters in your active identity so I'm curious what you are trying to replace?

Best,
Sam

**Comment by shanisa11** [comment]
If I am running a DimPlot for the original object, it still shows clusters 6,9,11,13 labeled as such.
Only if I add "group.by", I get the subclusters I labeled. 

I want to remove clusters 6,9,11,13 and replace them with the subset I've labeled.
S

**Comment by samuel-marsh** [comment]
What do you use for `group.by` to get them to display correct with `DimPlot`?

**Comment by shanisa11** [comment]
immune cluster is the subcluster I've labled 

```
data.integrated$immune_cluster <- as.character(Idents(data.integrated))
data.integrated$immune_cluster[Cells(immune.subcluster)] <- paste(Idents(immune.subcluster))
DimPlot(data.integrated, group.by = "immune_cluster", split.by = "orig.ident", label = TRUE, reduction = "tsne")
```

**Comment by samuel-marsh** [comment]
Hi,

So you've created meta.data column already with the information so you just need to transfer to the active identity right?

```
Idents(data.integrated) <- "immune_cluster"
```

Or am I missing something?

Best,
Sam

**Comment by shanisa11** [comment]
It worked!  that's exactly the code line I was looking for.
thank you so much

**Comment by samuel-marsh** [comment]
Happy to help!
