### ISSUE TITLE
Rebuild pkgdown site for v4.1

### ISSUE THREAD

**Issue by samuel-marsh** [satijalab/seurat#5525]
Hi Seurat Team,

Minor thing, and may already be in progress but just thought I'd post heads up if not but https://satijalab.org/seurat/ still reads v4.0.6.  Just needs pkgdown build and deploy for new updates.

Thanks again for everything you do!
Sam

**Comment by timoast** [comment]
Thanks, we're having an issue right now with the server we use to build the website. Hopefully we'll have it fixed soon and website updated.

**Comment by samuel-marsh** [comment]
Sounds good!
