### ISSUE TITLE
Analysis of cell hashing data - treated vs. untreated

### ISSUE THREAD

**Issue by lschachtner** [satijalab/seurat#5529]
Hello,

I recently performed a 10x Genomics cell hashing experiment using 8 hashtags to label 2 treatments at 4 different timepoints. I'm wanting to compare treated vs. untreated cells at each time-point, but was wondering if I actually need to perform integration on my dataset? I've been following the "Introduction to scRNA-seq integration" vignette, as that is the only example in which stimulated vs. unstimulated cells are compared. 

All of my samples were hashtagged and ran in a single lane of a 10x chip, then sequenced as a single library, so I'm curious as to whether integration actually needs to be performed since there should be no batch effects.

Please reply with any suggestions for my analysis. Thank you!

Best,
Logan

**Comment by mhkowalski** [comment]
Hi, 

Thanks for the question.  The purpose of the integration is to allow you to identify similar cell types in both conditions, and then analyze the effect of the treatment in those cell types. Are similar cell types clustering together from the treated vs untreated cells? Integration would be useful here if, for instance, you have one cluster of cell type A from the treated condition and another separate cluster of cell type A from the untreated condition. 

If you are happy with the cell type annotations in the unintegrated dataset, then it seems to me that it is ok to proceed without integration.
