### ISSUE TITLE
spatial inference parallization

### ISSUE THREAD

**Issue by ccshao** [satijalab/seurat#553]
Several steps in the process of spatial inferece are quite slow, namely `AddImputedScore`, 
`FitGeneK`, `InitialMapping`. I found `sapply` is used internally in these functions, would be possible to use `mcapply` instead?
Thanks!

**Comment by mojaveazure** [comment]
While we are actively looking into parallelizing various aspects of Seurat, we cannot use `mclapply`. Please see #457 for details about parallelization and the specific requirements for parallelization in Seurat.

**Comment by ccshao** [comment]
The packages `future` and `future.apply` make the parallelization steps quite easy. Simply replacing the `sapply` with `future_sapply` will speed up the analysis.
