### ISSUE TITLE
Re-integrate after subset?

### ISSUE THREAD

**Issue by aelhossiny** [satijalab/seurat#5532]
So I am analyzing a scRNA seq from homogenized tissue from different samples, I've two questions here, 
1 - Do I integrate by sample or by sequencing run? I have no information whether the samples were processed differently or not before sequencing, but I have information if they were ran on the same sequencing run or not.

2- This is the main confusing thing for me, After I finish the integration and clusters labelling, I will be interested in specific cluster/cell-type for further analysis. The question is, to re-cluster this subset, where do I start from? Do I need to set the `DefaultAssay(object)="RNA"` and follow the same integration steps? Or do I use the integrated count matrix as input for normalization, scaling, PCA, ..? 

My understanding is that the integration aligns the cells globally across different samples, I am not sure when I subset if I need to repeat this as cells should now have different correlations scale relative to the global one.

Thank you!

**Comment by torkencz** [comment]
Hi. I would integrate based on the information you have, so the sequencing run. As for your second question I would suggest.
Subset the cells
Find variable features in the subset using the RNA assay
Run ScaleData on the integrate assay on the new set of variable features
Run PCA on the integrated assay using the new set of variable features
Run FindNeighbors and FindClusters using the new PC dimensions
