### ISSUE TITLE
How to structure a Vlnplot with multiple individual plots?

### ISSUE THREAD

**Issue by blusoldier001** [satijalab/seurat#5533]
I'm trying to make a Violin Plot with multiple individual plots, but I'm not sure how to specify how many I want on each row, and how many rows I would like. For some reason, it seems to be locked to 3 rows no matter how many individual plots I want. I'm relatively new to Seurat, so if there's already documentation about how to do this, it would also be helpful.

Here's what my code looks like right now:

VlnPlot(object = database, 
        features = interested_features,
        split.by = "identity",
        group.by = "group",
        pt.size = 0.2,
        combine = T) + 
  theme(legend.position = 'right')
warnings()

I've attached an example of what my violin plots look like at the moment. What I'm trying to do is have 2 rows with 4 plots each.
![error](https://user-images.githubusercontent.com/35697422/150601216-3d028bf8-42da-477a-9b56-e22c70475942.png)

**Comment by timoast** [comment]
Did you try setting the `ncol` parameter?

**Comment by blusoldier001** [comment]
Thank you! I think I got it now.
