### ISSUE TITLE
columns suppressed when using map 

### ISSUE THREAD

**Issue by HediaTnani** [satijalab/seurat#5539]
Hi, 

When I read 10x data for multiple samples :
`obj.ls <- in.list %>% map( ~ paste0(.x,"/filtered_feature_bc_matrix")) %>% map( ~ Read10X(.x)) %>% map( ~ CreateSeuratObject(.x,min.features = 100, project = samplesName))`

I'm getting `[[ suppressing 72 column names ‘AAACCCAGTAGAGGAA-1’, ‘AAACCCATCAAGTAAG-1’, ‘AAACCCATCATGGAGG-1’ ... ]]
   [[ suppressing 72 column names ‘AAACCCAGTAGAGGAA-1’, ‘AAACCCATCAAGTAAG-1’, ‘AAACCCATCATGGAGG-1’ ... ]]`.

Is it something that we should expect? why is it removing columns?

What's the best way to read 10x data from multiple samples?

**Comment by torkencz** [comment]
Hi, I am not a 100% sure but would check if you have duplicate cell names between the samples. It is a little more cumbersome but I generally try to read in sample by sample and then merge, just to make sure I do renaming.
