### ISSUE TITLE
Comparing Multiple samples after merging

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#554]
Hi,

I want to plot the similarity/dissimilarity between multiple samples after merging them using MergeSeurat and PCA. Is there a way to do this already in Seurat?

Thanks,

Biba

**Comment by ghoshal** [comment]
The MetageneBicorPlot works with CCs only. Can it be made to work with PCs?

**Comment by satijalab** [comment]
You can use PCElbowPlot for PCA. We don't have methods to examine global similarity/dissimilarity between multiple samples as you suggest, but will in the future.

**Comment by jdime** [comment]
Hello,
Are there any news on implementation of a method to examine global similarity between multiple samples?
Also are there an equivalents for functions AlignSubspace() and CalcAlignmentMetric() from Seurat v2 in v3?
Thanks.
