### ISSUE TITLE
The batch effect showing in doheatmap png

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#5540]
Dear developer,
        I am confused that the batch effect was so strong that it can not be removed from all samples by the integration algorithm including CCA, SCTranform, rpca, harmony, FastMNN.
       The batch effect heatmap showing below:
       
![1643076999(1)](https://user-images.githubusercontent.com/41668708/150898399-3551f241-03a7-4ea6-bce4-ae8a195d736c.png)
      What can i do for this conditions? how can i normlize this issue?
Any advices would be appreciated.
Best,

Hanhuihong

**Comment by honghh2018** [comment]
Had any advices for this issue?

**Comment by torkencz** [comment]
Could you give more information on what you are trying to correct?

**Comment by wenkaiyan-kevin** [comment]
Hi, is your problem solved?

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉
