### ISSUE TITLE
How to do a multiplot of individual violin plots of 277 ADTs 

### ISSUE THREAD

**Issue by carlosaya2** [satijalab/seurat#5541]
Hi all, 

I have data from 277 ADTs and I would like to plot them all in individual violin plots but combined in the same figure. 

I have created a list with the 277 ADTs ids and the used the following code:
```{r}
 VlnPlot(DS06combinedfiltered, features = c(list2), ncol = 5, group.by = "cond")  
```
however, I get the following plot:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/61134130/150919101-72c49868-2f84-40ae-b679-786b08c5cc9f.png">

I tried adding + plot_grid and not success.

the goal is to get something like this but for 277 instead of 5.
 
<img width="925" alt="image" src="https://user-images.githubusercontent.com/61134130/150919533-2b152456-dec2-4195-8e4d-7bdf52e47911.png">

I will highly appreciate any help/guidance

cheers

Carlos

**Comment by torkencz** [comment]
Hi. In this case I would advise you to just get the normalized ADT data (FetchData or GetAssayData),merge with your metadata features, reformat the matrix into long format and plot with ggplot.
