### ISSUE TITLE
IntegrateData : Error: Feature names of counts matrix cannot be empty

### ISSUE THREAD

**Issue by AnnaAntonatouPap** [satijalab/seurat#5548]
Hello,

I am trying to integrate zebrafish with human data! I already found orthologs and replace zebrafish gee names with the human ones ! Considering gene names look fine! I managed to find anchors BUT when I am running  `IntegrateData ` I am resceiving the following error ` Error: Feature names of counts matrix cannot be empty`

I checked with the following command if I have any empty rowname in both the datasets, but I don't have 
`any(rownames(anchors@object.list[[1]]@assays$RNA@counts)==" ")
`

Any help will be really appreciated
Anna

**Comment by yuhanH** [comment]
Hi @AnnaAntonatouPap 
How do you change the zebrafish gene name? do you generate a new assay?

**Comment by AnnaAntonatouPap** [comment]
I renamed the genes and the feature names and then I re run all the steps that i need ( e.g normalization etc ) should I just create a new seurat obj with the  edited-human gene names-countmatrix and the meta data ?

**Comment by yuhanH** [comment]
It is highly suggested you use `CreateAssayObject()` to create a new assay with new feature names.

**Comment by AnnaAntonatouPap** [comment]
hmm ok ok I will try it in a bit! Hopefully it will work!

Thanks a lot :)

**Comment by AnnaAntonatouPap** [comment]
Hey again, so the idea of creating a new object worked but when I am running the integration function I receive the following error 
```
Merging dataset 2 into 1
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
Error: C stack usage  7975860 is too close to the limit
```

**Comment by yuhanH** [comment]
Hi @AnnaAntonatouPap 
Have you tried to restart your R session?  How many cells you are going to integrate?
