### ISSUE TITLE
gene set expression analysis using addModuleScore()

### ISSUE THREAD

**Issue by andynkili** [satijalab/seurat#5549]
I am interested in cells expressing both a specific gene and a gene set:
I used the code from [#3521](https://github.com/satijalab/seurat/issues/3521):
```
geneSet_list <- list(geneSet)
object <- AddModuleScore(object = object, features = geneSet_list , name = "geneSet")
```

After adding the score to the object metadata, I do a FeaturePlot with the specific gene and the gene set to check their co-expression:
`FeaturePlot(object, c('specificGene',  'geneSet1'), blend = TRUE, label = T, pt.size = 2)`

Some cells seem to express both but it's hard to tell with the shades of colors, even playing with the blend threshold and choosing different palette.
To overcome the view issue, I did:
`DimPlot(object, cells.highlight= WhichCells(object,expression = specificGene>0 & geneSet1>0))`

However after reading [#522](https://github.com/satijalab/seurat/issues/522), I realized that my way of doing this might be wrong since I am using the gene set score as if it was gene count .
Since the score of gene set is unitless and reflects the likeliness of the gene set being more expressed that expected, it cannot give any information on the level of expression of the gene set, can it?

If so, would it be an other way of assessing the level of co-expression of the specific gene and the gene set?

**Comment by mhkowalski** [comment]
Thanks for your question. Yes, the module score represents relative expression. If gene A is highly expressed across all cells, the module scores assess whether a given cell expresses gene A more often than other highly expressed genes. Therefore, if the module score is high, it indicates these genes are expressed. If the module score is low, it might mean that these genes are expressed but not more so than in other cells. 

I would recommend looking at co-expression of the specific gene and each member of the gene set. To quantify this, you could calculate the correlation of expression of the specific gene with each member of the gene set.

**Comment by gt7901b** [comment]
@mhkowalski  will you please elaborate on how to calculate the correlation of expression of the specific gene with each member of the gene set and check co-expression of the specific gene and each member of the gene set?  thanks

**Comment by denvercal1234GitHub** [comment]
@gt7901b @mhkowalski Did you guys have any update on how to calculate the correlation of expression for a given gene? Thanks in advance for your help!

**Comment by RajneeshSrivastava** [comment]
Hi @mhkowalski and @samuel-marsh,

I am trying to understand the calculations powered in the "AddModule Score" function of seurat. Luckily, I got a [post](https://www.waltermuskovic.com/2021/04/15/seurat-s-addmodulescore-function/) that explains the fundamentals very well. 

To compute the score, I used the script for 4 known signature genes (of my cell type of interest - labeling "cell_typeA" to trace back) as suggested (https://github.com/satijalab/seurat/issues/3521). When I use the snippet, it adds on to 4 score (i guess for individual gene) columns appended to metadata viz. cell_typeA_score1, cell_typeA_score2, cell_typeA_score3, cell_typeA_score4. (tested for 100 genes, gave 100 score columns suffixed "1"..."100")

Please help me understand on adding "1" (for instance - cell_typeA_score"1") and its significance over other (Why not 2 /3 / 4?)
Are these scores computed gene-wise (and appended)? If, so how AddModuleScore is computing the **cumulative enrichment**?

I am sure, I might be missing something in the function, please clarify.

Again thank you so much, Seurat team and kudos to seurat5!

With regards,
Rajneesh

**Comment by samuel-marsh** [comment]
Hi Rajneesh,

So you need the gene set to be of class `list` in order to be scored together.  Otherwise it will create one score for each gene.  The numeral is simply that.  It starts at 1 and goes up.  So if you have list of two vectors they will be suffixed 1 and 2.

To score a set of genes you run (let’s call them T cell genes) you would run something like the following:

```
t_genes <- c(“gene1”, “gene2”, “gene3”, etc)

obj <- AddModuleScore(pbmc, features = list(t_genes), name="T_Score")

```

Best,
Sam

**Comment by RajneeshSrivastava** [comment]
Try this
Mito_Genes <- list(**c**("Mt-ND1" , "Mt-ND2", "Mt-COX1" , "Mt-COX2" , "Mt-ATP8", "Mt-ATP6" , "Mt-COX3" , "Mt-ND3" , "Mt-ND4L", "Mt-ND4" , "Mt-ND5" , "Mt-ND6" , "Mt-CYTB" ))

**Comment by samuel-marsh** [comment]
Yes as @RajneeshSrivastava mentions you need to format as a list in order to get score for combined set of genes.  I will also note that module score and percent mito counts will not necessarily yield complementary values depending on expression levels of each individual mito gene.

Best,
Sam
