### ISSUE TITLE
Integration for biological replicates

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#5553]
Hello :)

I have a question for integration of biological replicates. I already read some questions about this(#4753). However, I can't understand fully now.

In this approches, how do I discriminate replicates? I think I should assign replicates at first. However, I couldn't find such process. I have 4 samples(Control 1, Case 1, Control 2 and Case 2)

In my thought, brief steps are like this:
1. assign replicates and samples
2. normalize count
3. integration
4. dimensional reduction
5. down stream analysis(such as DE analysis)

I think there are many approches exist in this case. I want to hear all your suggestions!

Thank you for reading.

Best,

Dahun

**Comment by mhkowalski** [comment]
Hi, 

Yes, there are several possible approaches here. As mentioned in #4753, you could use your 2 Control's as a reference, in which case I would use the following steps:
  1. Normalize all 4 samples separately
  2. Integrate the 2 control samples
  3. Integrate each case sample with the integrated control object, as shown [here](https://satijalab.org/seurat/articles/integration_mapping.html) 
  4. dimension reduction
  5. downstream analysis

Hope this is helpful!
