### ISSUE TITLE
How to do cell annotation?

### ISSUE THREAD

**Issue by Leran10** [satijalab/seurat#5554]
Hi,

I used Seurat to do clustering, then singleR to do cell annotation. In this annotation, I got multiple cell types such as B cells and T cells and Epithelial cells. I'm only interested in Epithelial cell, so I subset the Seurat object to only keep Epithelial cell. Then I redo clustering on Epithelial cell cluster. Here is the new clusters Seurat generated:

![image](https://user-images.githubusercontent.com/17597071/151414770-3083bdea-34f6-4d7c-b07f-816f4936dd3a.png)

I want to assign cell names to each cluster, but I'm not sure how to do this on the further clustered data (I don't think I can use singleR again, because if SingleR can annotate these clusters, it should have done that at the first time I used it.)

I used seurat to calculate the gene expression in each cluster and hoping to get cell type based on the gene expression information. The gene expression table looks like this:

![image](https://user-images.githubusercontent.com/17597071/151414896-9b82dd60-d0b5-4aac-9519-b3a415efb22d.png)

So my question is, does anybody know how to do cell annotation on these sub clusters? Is there any reference database that I can use to find cell names based on the gene expressions?

Thanks so much! 
Leran

**Comment by jarchana09** [comment]
Hi, I am not a member of the development team, but perhaps this may be helpful.  Looking through literature would be the most helpful, especially for studies that have performed single cell RNA sequencing on epithelial cells could be helpful to get a list of markers for cell type annotation. Not sure what type of tissue you are working with. If it is epithelial cells from lungs, the Lung Gene Expression Analysis web portal has a few markers that may help: [https://research.cchmc.org/pbge/lunggens/tools/lung_at_glance.html?tab=cell&species=Mouse&cell=T001](https://research.cchmc.org/pbge/lunggens/tools/lung_at_glance.html?tab=cell&species=Mouse&cell=T001) .  Another resource that may help is the CellMarker database [(http://biocc.hrbmu.edu.cn/CellMarker/)](http://biocc.hrbmu.edu.cn/CellMarker/) .  If its cells from kidney, the NHLBI site on RNA-seq Analysis of Mouse Whole Kidney which has a few markers listed [https://esbl-nhlbi-nih-gov.ezproxy.bu.edu/Databases/MouseWK/WKMarkers.html](https://esbl-nhlbi-nih-gov.ezproxy.bu.edu/Databases/MouseWK/WKMarkers.html) may help . An article on scRNA seq describing intestinal epithelial cells [(https://www.nature.com/articles/nature24489)](https://www.nature.com/articles/nature24489), and one on mouse mammary epithelial cells [(https://breast-cancer-research.biomedcentral.com/articles/10.1186/s13058-021-01445-4)](https://breast-cancer-research.biomedcentral.com/articles/10.1186/s13058-021-01445-4) . Hope these resources can get you started. Thank you.

**Comment by torkencz** [comment]
Perfect resources. Thank you @jarchana09

**Comment by Michae-lab-Waterloo** [comment]
I've faced a similar challenge with epithelial cell subtype annotation. While the resources @jarchana09 shared are excellent starting points, I'd like to add another approach that's been helpful for me with complex epithelial subtypes.

I recently started using mLLMCelltype ([https://github.com/cafferychen777/mLLMCelltype),](https://github.com/cafferychen777/mLLMCelltype),) which takes a different approach to annotation by leveraging multiple large language models to interpret gene expression patterns. It's particularly useful for these subclustering scenarios where traditional reference-based methods like SingleR might not have the granularity needed.

For your epithelial subclusters, you could:

1. Run mLLMCelltype with a specific prompt about epithelial subtypes in your tissue of interest
2. Cross-validate with the marker databases mentioned by @jarchana09
3. Visualize key markers using DotPlot() to confirm the annotations

The tool integrates well with Seurat objects and provides detailed reasoning for each annotation, which helps with understanding why certain clusters are assigned specific subtypes.

Here's a simplified example:
```R
library(mLLMCelltype)
results <- interactive_consensus_annotation(
  your_epithelial_seurat_obj,
  tissue_name = "your_tissue", # e.g., "lung", "intestine", etc.
  models = c("claude-3-7-sonnet-20250219", "gpt-4o", "gemini-2.5-pro"),
  api_keys = list(
    anthropic = "your_anthropic_key",
    openai = "your_openai_key",
    google = "your_google_key"
  )
)
