### ISSUE TITLE
Co-embedding scRNA-seq and scATAC-seq datasets: problem with DimPlot

### ISSUE THREAD

**Issue by chrismahony** [satijalab/seurat#5555]
Hi

I have scATAC-seq and scRNA-seq data that I am analysing side-by-side and trying to integrate the two data sets for better visualisation. However, when I try DimPlot I get a strange plot, could you help? Thanks

My code is below:

`gene.activities <- GeneActivity(atac_cicero, features = VariableFeatures(rna))
atac_cicero[["ACTIVITY"]] <- CreateAssayObject(counts = gene.activities)
DefaultAssay(atac_cicero) <- "ACTIVITY"
atac_cicero <- NormalizeData(atac_cicero)
atac_cicero <- ScaleData(atac_cicero, features = rownames(atac_cicero))

transfer.anchors <- FindTransferAnchors(reference = rna, query = atac_cicero, features = VariableFeatures(object = rna),
    reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")
genes.use <- VariableFeatures(rna)

refdata <- GetAssayData(rna, assay = "RNA", slot = "data")[genes.use, ]
imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, weight.reduction = atac_cicero[["lsi"]],
    dims = 2:30)
atac_cicero[["RNA"]] <- imputation
coembed <- merge(x = rna, y = atac_cicero)
coembed <- ScaleData(coembed, features = genes.use, do.
[Dimplot.pdf](https://github.com/satijalab/seurat/files/7953766/Dimplot.pdf)
scale = FALSE)
coembed <- RunPCA(coembed, features = genes.use, verbose = FALSE)
coembed <- RunUMAP(coembed, dims = 1:30)
DimPlot(coembed, group.by = c("orig.ident"))`

**Comment by chrismahony** [comment]
[Dimplot.pdf](https://github.com/satijalab/seurat/files/7953778/Dimplot.pdf)
Dimplot should now be attached, thanks

**Comment by chrismahony** [comment]
I manage to solve this by setting the default assay to RNA for both objects.

with the coembeded object, how accurate would it be to run FindClusters/FindAllMarkers for further analysis? Or is this merged on coembedding mainly for visualisation?

thanks

**Comment by timoast** [comment]
I'd recommend using the transferred cell type/cluster labels rather than doing joint clustering on the RNA and imputed RNA. As for DE between imputed RNA and the RNA, I wouldn't recommend doing that. One is derived from the other in this case.
