### ISSUE TITLE
Cannot change cell names from a combined Multiomics Seurat object:

### ISSUE THREAD

**Issue by LucaTucciarone** [satijalab/seurat#5556]
This is the code I am running:
`samples.bc = Multiomics$samples
head(samples.bc)
head(colnames(Multiomics))
new.names = paste0(samples.bc, "_", Cells(Multiomics))
head(new.names)
RenameCells(Multiomics, new.names = new.names)
head(Cells(Multiomics))`

This is the output of the code:
`AAACAGCCAACTAGAA-8'MM_662'AAACAGCCAACTAGGG-2'MM_664'AAACAGCCAAGCCAGA-2'MM_664'AAACAGCCAAGCTTAT-2'MM_664'AAACAGCCAATTTGGT-1'MM_667'AAACAGCCACAAAGCG-1'MM_667'
'AAACAGCCAACTAGAA-8''AAACAGCCAACTAGGG-2''AAACAGCCAAGCCAGA-2''AAACAGCCAAGCTTAT-2''AAACAGCCAATTTGGT-1''AAACAGCCACAAAGCG-1'
'MM_662_AAACAGCCAACTAGAA-8''MM_664_AAACAGCCAACTAGGG-2''MM_664_AAACAGCCAAGCCAGA-2''MM_664_AAACAGCCAAGCTTAT-2''MM_667_AAACAGCCAATTTGGT-1''MM_667_AAACAGCCACAAAGCG-1'
An object of class Seurat 
154440 features across 31310 samples within 2 assays 
Active assay: peaks (117839 features, 117839 variable features)
 1 other assay present: RNA
 7 dimensional reductions calculated: pca, harmony.rna, umap.rna, lsi, harmony.atac, umap.atac, umap.wnn
'AAACAGCCAACTAGAA-8''AAACAGCCAACTAGGG-2''AAACAGCCAAGCCAGA-2''AAACAGCCAAGCTTAT-2''AAACAGCCAATTTGGT-1''AAACAGCCACAAAGCG-1'`

As you see the code runs, and Seurat just "ignores" what I asked him to do. I've also tried with:
`RenameCells(Multiomics, add.cell.id = Multiomics$samples)`
And the same happens. 

What am I doing wrong?
please let me know, 
Luca

**Comment by k3yavi** [comment]
Hi @LucaTucciarone ,

Are you saving the objects returned by the function `RenameCells` into a new/old variable ? The function does not performs an in-place modification.

**Comment by LucaTucciarone** [comment]
OH MY GOD, that was so dumb from my end. Yeah it worked
