### ISSUE TITLE
Count the number of clusters (without providing labels)

### ISSUE THREAD

**Issue by wcwr** [satijalab/seurat#5557]
Seurat's `LabelClusters` function is very useful for labeling clusters starting solely from X/Y coordinates of a given dimensionality reduction result - even outside of Seurat :

```
library(umap)
library(Seurat)
my_umap <- umap(iris[,c(1:4)])
my_umap <- as.data.frame(my_umap$layout)
my_umap$id <- iris$Species
colnames(my_umap) <- c("x","y", "id")

p <- ggplot(my_umap, aes(x=x,y=y,color=id)) + geom_point()

LabelClusters(plot=p, id='id', color="black")
```

![image](https://user-images.githubusercontent.com/80007059/151627773-3d2d59ae-3513-40f4-b460-5b1e2687afb1.png)

However, I have a need to detect total # of clusters from these data (without providing labels). By this I mean first detecting how many clusters exist (which I realize may need some sort of user input / selection of K). Maybe here we would see 5 clusters instead of 3 :

![image](https://user-images.githubusercontent.com/80007059/151628239-5dd9f991-fed0-4ab6-8e31-1dd09dbf5b3a.png)

This could be useful for things like cancer subtype detection; a user has 5 cancers but there are 6 clear discrete clusters, potentially indicating one of the cancers has a distinct subtype.

**Comment by rsatija** [comment]
You can modify the resolution parameter of FindClusters to increase or decrease the granularity of clustering, which I believe is what you are referring to here.
