### ISSUE TITLE
How can I map my in-house CITE-Seq query to pbmc_multimodal.h5seurat reference using both scRNA count and ADT count ?

### ISSUE THREAD

**Issue by qicheng-ma** [satijalab/seurat#5559]
Dear Seurat Team,

In https://satijalab.org/seurat/articles/multimodal_reference_mapping.html, the query pbmc3k only has scRNA data.
How can I map my in-house CITE-Seq query to pbmc_multimodal.h5seurat reference using both scRNA count and ADT count ?
How should I change the following code to map in-house CITE-Seq query with the same 228 ADT counts as the reference:

anchors <- FindTransferAnchors(
  reference = reference,
  query = pbmc3k,
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50
)

pbmc3k <- MapQuery(
  anchorset = anchors,
  query = pbmc3k,
  reference = reference,
  refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca", 
  reduction.model = "wnn.umap"
)

Thanks in advance!

**Comment by yuhanH** [comment]
Hi
in our mapping method, you cannot map the cells using RNA and protein together.  
You can map your cells to our reference by only RNA or only protein.
