### ISSUE TITLE
When should I perform CCA batch correction for cell subsets?

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#556]
Hi all,

I am performing single cell analysis for 8 PBMC samples in 2 different conditions (healthy and diseased). I am interested in analyzing the DE genes in a subset of cells - in this case, NK cells. 

So in this case, when should I perform the CCA for batch correction? Which of these 2 below are more accurate?

1) Perform clustering for each sample separately, subset out NK cells and combine the NK subsets for CCA and analyze again for DE genes between conditions
2) Combine all 8 PBMC samples for CCA, then subset out NK cells for analysis for DE genes between conditions

Thank you very much.

**Comment by satijalab** [comment]
We recommend first performing the analysis under the standard workflow. If the subtypes cluster together across batches, there is no need to run CCA or any integration workflow.

If there is a significant batch effect that is removed by CCA, this is a situation very similar to our vignette, and we suggest (2)
