### ISSUE TITLE
export ADT counts per sample not per cell 

### ISSUE THREAD

**Issue by carlosaya2** [satijalab/seurat#5561]
hi, 

I would like to export raw ADT counts from my Seurat object which CITESeq data  of 3 conditions and 2 assays (RNA and ADT (n=277). 

I have used the following code, but it generates the counts per cell and I need the counts per sample or per condition. how I could do it?

```
 write.table(as.matrix(GetAssayData(object = DS06combinedfiltered, slot = "counts")), 
            '/SCRATCH/CITE-Seq/Timo_carlos_22/DS06_single_cell_analysis/ADT_counts_v3.csv', 
            sep = ',', row.names = T, col.names = T, quote = F)
```

I would highly appreciate any help that can be provided. 

Cheers

Carlos

**Comment by mhkowalski** [comment]
Hi,

You can use the `AverageExpression()` function to average expression values per sample, such as 

```  
avg.counts <- AverageExpression(object = DS06combinedfiltered , slot = "counts", 
 assay="ADT", group.by="condition") 
```

If you'd like to have the total counts (and not the average counts), you would have to multiply by the number of cells in each condition. 

```
n <-  table(DS06combinedfiltered$condition) #get number of cells per condition
sweep(avg.counts$ADT, MARGIN=2, n, `*`) #multiply by number of cells to get total counts per condition
```
