### ISSUE TITLE
Speed up FindTransferAnchors()

### ISSUE THREAD

**Issue by DennisFeige** [satijalab/seurat#5564]
Hi all,

I currently try to take over cluster annotations from a reference dataset of ca. 150k cells onto my dataset of 100k cells with the FindTransferAnchors() function. The process takes quite long,especially the "Filtering Anchors" step. I am already using "rpca" and in for the list of functions being able to be parallized only FindIntegrationAnchors() is listed (https://satijalab.org/seurat/articles/future_vignette.html). 
Does anyone have an idea how to spead up the function or set the arguments of the function so the function runs faster?

Best and thanks for your help,
Dennis

**Comment by torkencz** [comment]
Hi, some of the Seurat functions can be sped up via the use of future. However, I do not think it works with FindTransferAnchors. Unfortunately, I do not know of any other ways to speed things up with that particular function.
