### ISSUE TITLE
Seurat v4  IntegrateData error 

### ISSUE THREAD

**Issue by AnnaAntonatouPap** [satijalab/seurat#5566]
I am currently working with single cell data from human and zebrafish both from brain tissue!
My assignment is to integrate them! So the steps I have followed until now :

1. Find human orthologs for zebrafish genes in biomart 
2. kept only the one2one 
3. subset the zebrafish Seurat object based on the orthlogs and replace the names with the human gene names 
4. Create an new Object for zebrafish and run Normalization anad FindVariableFeatures

5. Then use this object with my human object for integration 

   **Human object: 20620 features across 2989 samples

   Zebrafish object: 6721 features across 6036 samples**

  
   
 ```
 features <- SelectIntegrationFeatures(object.list = double.list)
    
  anchors <- FindIntegrationAnchors(object.list = double.list,
                              anchor.features = features,
                              normalization.method="LogNormalize", 
                              nn.method="rann")    
```
 

 This identifies 2085 anchors! 
 I used nn.method="rann" because if I use the default I have this error 

    Error: C stack usage  7973252 is too close to the limit

  Then I am running the integration like this 

```
ZF_HUMAN.combined <- IntegrateData(anchorset = anchors,  
                                   new.assay.name = "integrated")
```
 
and the error I am receiving is like this 

```
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 9265 anchors
Filtering anchors
	Retained 2085 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=22s  
```

To solve this I tried to play around with the arguments in FindIntegrationAnchors 
e.g i used l2.norm=F! The only things that changed is the number of anchors which decreased 

**I am wondering if the usage of nn.method="rann" at FindIntegrationAnchors messing things up 
ANY help will be appreciated because I am struggling for a long time with that, I don't know what else to do**

**Comment by mhkowalski** [comment]
Hello, 

Could you please post the full output? I do not see an error message from what you have posted.

**Comment by AnnaAntonatouPap** [comment]
Hey sorry :/ it was an error like this` Error: C stack usage  7973252 is too close to the limit`

I solved it tho, it was just necessary to run in a cluster 
  
I will update the post in case anybody has the same problem in the future 

Thanks anyway ,
Anna

**Comment by mhkowalski** [comment]
Ok thanks. Closing the issue now.
