### ISSUE TITLE
SCTv2 recommendations

### ISSUE THREAD

**Issue by Sethupathy-Lab** [satijalab/seurat#5567]
Hi,

I recently have been going through the new [SCTransform v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html). In the vignette, a new FindMarkers workflow is introduced using the SCT assay. All previous advice was to use the RNA assay for differential expression (DE) and visualization of gene expression, but based on the examples in this vignette, would you suggest using this new workflow for DE and gene expression comparisons? Does using the SCT assay affect the assumptions of any of the possible tests that can be used for DE?

Thanks for your help!
Matt

**Comment by saketkc** [comment]
We do recommend using the updated workflow for DE as we show in Figure 4 of the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9) - updated approach results in improved performance (over lognorm or other normalization based approach followed by DE). We used wilcoxon test on log of corrected counts, but you can also run DE directly using corrected counts (in the [supplmentary](https://static-content.springer.com/esm/art%3A10.1186%2Fs13059-021-02584-9/MediaObjects/13059_2021_2584_MOESM1_ESM.pdf) we also show performance using MAST and DESeq2).

**Comment by Sethupathy-Lab** [comment]
Thank you!

**Comment by rbutleriii** [comment]
@saketkc I had been looking at Fig S23 and was curious why `Deseq2` wasn't included in the SCTv2 tutorial despite it seemingly delivering the higher TPR while remaining left of the associated FDR cutoff? 

For my project, I have a batch variable to include as a `latent.vars` (which I cannot do with Deseq2, correct?) so in that case it seems like the best approach is to use the SCTv2 corrected counts (with batch effects in `vars.to.regress`) which still had observed FDR to the left of FDR cutoff in all cases.

**Comment by saketkc** [comment]
@rbutleriii Sure, you could try DESeq2 with corrected counts + other batch variables. In tutorials we try to minimize external dependencies (unless the performance with default (here wilcoxon) is poor).
