### ISSUE TITLE
SCENIC after MapQuery

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5568]
Hi,

I have a 4 samples (PBMC) representing CNTR, PERTa, PERTb, PERTb_after_PERTa.

I downloaded your PBMC multimodal reference and did the following steps (after QC, etc): 
1) Merge the 4 samples (with ref.umap) into combined obj using merge
2) SCTransform - UMAP on the combined obj
3) FindTransferAnchors on the combined obj
4) MapQuery on the combined obj
5) Differential Expression across groups (e.g. PERTa vs CNTR, etc) using FindConservedMarkers on the combined obj

I have a couple of questions:

1) Is reference mapped combined obj free of potential batch effects at this point ? or should I have first 'integrated' the individual samples, instead of merging them, and then do reference mapping for annotation ?

2) I am interested in following up with SCENIC. I would run it on the (batch corrected ??) combined obj to look into differential regulation. What matrix in the combined obj should I use, RNA@data, SCT@data or integrated@data ?
The  integrated@data matrix includes only 3K genes

Thanks

**Comment by gianfilippo** [comment]
Hi,

I actually realized that the TransferData function does not modify the the query expression data, so, I should not use the simply combined obj for Differential Expression across groups or SCENIC.

A more appropriate approach could be:
1) ref map each sample to the reference for annotation.
QUESTION: how does the ref mapping handles cells that may not be represented in the reference ?

2) Integrate the samples 
3) set DefaultAssay(obj) <- "integrated"
4) Differential Expression with FindConservedMarkers on "integrated" obj
5) export obj$integrated@data to file for SCENIC analysis

Does this seem reasonable ?

Thanks

**Comment by torkencz** [comment]
Hi, 
1. You will likely know if you have a cell type that is not in the reference from the low mapping scores.
2. We don't advise doing differential expression on the integrated assay. https://github.com/satijalab/seurat/issues/1717
3. If I remember correctly SCENIC requires counts matrices as an input. You might want to consider correcting for batch effect downstream via Harmony. However, I would open an issue with them.

Hope this helps in figuring out your analyses.
