### ISSUE TITLE
Four CITE-seq data with poorly overlapping ADTs: how to normalize and scale the ADT matrix with batch correction after integrating the RNA matrices

### ISSUE THREAD

**Issue by RM83** [satijalab/seurat#5569]
Hi Seurat team,
I can't integrate RNA and ADT assays using WNN because of very low number of ADTs (n=1) overlapped in all four samples. So, I integrated the four samples using RNA data. Now I have these assays - Integrated (active assay), RNA, ADT, and SCT. I also have two reductions: pca and umap.
My question is:
Is it appropriate to normalize and scale the ADT matrix using CLR? If yes, how would it be batch corrected? Because the ADT matrix contains raw expression data for all the cells from the four samples.

Thank you in advance for reading the issues.

**Comment by mhkowalski** [comment]
Hi, 

I would recommend normalizing your ADT matrix with CLR prior to merging your 4 samples. These will not be batch corrected, but it does not seem possible to do batch correction if you only have 1 overlapping ADT between your samples. 

Hope this helps.
