### ISSUE TITLE
merge expression and pct of multiple genes in one

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#557]
Dear All,
I would like to visualize in my clusters avg.exp.scale and pct.exp through a DotPlot of a set of genes, but I would like to output only one column, that should average the avg.exp.scale and pct.exp of all genes, for example

I created a list of genes 
```R
mhc.genes <- grep(pattern = "^H2-", x = rownames(x = subset_tac_4_weeks_res12@data), value = TRUE)
```
now I would like to plot with DotPlot function the average values of all genes present in my list, any suggestion?

Best
Paolo

**Comment by leonfodoulian** [comment]
Hi,

Please refer to issue [#528](https://github.com/satijalab/seurat/issues/528) for an example of how to do this. You can easily replace `Seurat::FeaturePlot()` with Seurat::DotPlot().

Best,
Leon
