### ISSUE TITLE
Hi. I am new to R and  i am trying to learn. I have done integration analysis on my datasets which is Healthy and diseased samples. At the end point of tutorial where we can find differentially expressed genes across same cluster in different condition(differential expression in B cells in diseased vs healthy) . What i found is that for all the clusters when i did this differential expression across the conditions i am having more or less same genes up-regulated in diseased clusters with different avg log2FC.What does it mean?.Di i am making some mistake or its ok?if some one can help me in sorting this issue out i will be very thankful.i am attaching the codes as well

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#5571]
[](url)
[CODE.FILE.docx](https://github.com/satijalab/seurat/files/7991524/CODE.FILE.docx)

**Comment by zara03** [comment]
Hi
Can I get to know like how are overclustered like I did all the default not setting resolution up and in default SCT assay it is 0.8.
Kindly correct me and tell possible solution please

Zehra Syeda, Ph.D  [A button for name playback in email signature] <https://www.name-coach.com/zehra-syeda>
Postdoctoral Associate
Department of Internal Medicine
Yale School of Medicine
Hepar Lab
https://medicine.yale.edu/profile/syeda_zehra/

From: Samuel Marsh ***@***.***>
Date: Thursday, February 3, 2022 at 10:22 AM
To: satijalab/seurat ***@***.***>
Cc: Syeda, Zehra ***@***.***>, Author ***@***.***>
Subject: Re: [satijalab/seurat] Hi. I am new to R and i am trying to learn. I have done integration analysis on my datasets which is Healthy and diseased samples. At the end point of tutorial where we can find differentially expressed genes across same cluster...

Hi,

Not member of the dev team but hopefully can be helpful. Unfortunately, this is going to be highly dataset specific and can't necessarily say that anything in particular is "wrong" or a "mistake". One aspect that could be effecting things though is if the data is over clustered and the clusters aren't as unique therefore the markers between multiple clusters might be more similar. Could also be the type of biology you are analyzing.

Best,
Sam

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsatijalab%2Fseurat%2Fissues%2F5571%23issuecomment-1029100549&data=04%7C01%7Csyeda.zehra%40yale.edu%7Ced8b1bcb61bb46d64c6b08d9e72901a0%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637794985593710292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OIvHm76neikGUOPXOxwcT9GPDNjeiW7Mu2MvWiXrFWw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW7NJLBUVMPGRNFIINIYCXTUZKMTVANCNFSM5NNYE4MA&data=04%7C01%7Csyeda.zehra%40yale.edu%7Ced8b1bcb61bb46d64c6b08d9e72901a0%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637794985593710292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l4392HIpTALtlHaEpnoNDKgIFb2rixmA10B1ebxTayw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csyeda.zehra%40yale.edu%7Ced8b1bcb61bb46d64c6b08d9e72901a0%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637794985593710292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l12bC0Tf8Q9gU61%2B2Ea%2FA8FB1pZ2huTG5gsH87Lbdc8%3D&reserved=0>.

**Comment by zara03** [comment]
Thank you so much for the response. Actually I just wanted to make sure that if we integrate by integration tutorial do the results are true? Or could be erroneous. As I understand it differs varies from dataset to dataset but as new into scRNA seq I wanted to ask this.
I asked bioinformatician he told they don’t do this integration.They just do normal clustering and find out top 50 genea in clusters of interest and then compare those 2 clusters in different condition.
Like cluster A vs all in WT then find markers choose top 50 upregulated or downregulated depending on question. Then do same with KO like cluster A vs all then take these genes and do IPA?
Is this approach also right?
Sorry for botheration but I want to make sure I am in right direction.

Zehra Syeda, Ph.D  [A button for name playback in email signature] <https://www.name-coach.com/zehra-syeda>
Postdoctoral Associate
Department of Internal Medicine
Yale School of Medicine
Hepar Lab
https://medicine.yale.edu/profile/syeda_zehra/

From: Samuel Marsh ***@***.***>
Date: Thursday, February 3, 2022 at 11:04 AM
To: satijalab/seurat ***@***.***>
Cc: Syeda, Zehra ***@***.***>, Author ***@***.***>
Subject: Re: [satijalab/seurat] Hi. I am new to R and i am trying to learn. I have done integration analysis on my datasets which is Healthy and diseased samples. At the end point of tutorial where we can find differentially expressed genes across same cluster...

Hi,

So the best thing you can do is look at cluster specific marker genes for your dataset and try different resolutions based on your knowledge of biology and what the dataset looks like. The number of highly variable genes, number of PCs used creating the neighbor graph, and resolution will all impact the end result. It's up to end user to evaluate the parameters and select the optimal choice for their dataset. All of them are going to be highly variable depending on source of data, number of conditions, batches, differential cell type abundance, heterogeneity of cell states/substates, etc. I suggest familiarizing yourself with other resources in the field and other papers doing single cell analysis. If possible too suggest reaching out to bioinformatician at your institute to get advice if they are willing/able.

Best,
Sam

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsatijalab%2Fseurat%2Fissues%2F5571%23issuecomment-1029143164&data=04%7C01%7Csyeda.zehra%40yale.edu%7C952d8dd651504d79b0b308d9e72ee216%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637795010812399093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7QW1vBcddGgzUYpfarOeOZ5x0YRmDzPCHtvZSsWcPH8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW7NJLFD6LDFOJJLRSNXZ53UZKRRPANCNFSM5NNYE4MA&data=04%7C01%7Csyeda.zehra%40yale.edu%7C952d8dd651504d79b0b308d9e72ee216%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637795010812399093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2IJ5MmDjnYkf1aeXhUEO6qqCHkyf5nFTLilq1EQ3i9I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csyeda.zehra%40yale.edu%7C952d8dd651504d79b0b308d9e72ee216%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637795010812399093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hhqQIzZb2wYsd2vfmqMiK74zqbgt5X%2FqDHfrGHtnbZk%3D&reserved=0>.

**Comment by torkencz** [comment]
Hi, 
There are no unanimously "correct" ways of doing integration. Like @samuel-marsh said I would do some reading (there are several benchmarking and lit summary papers out there discussing integration) to see what suits your biological question specifically. I would advise doing multiple approaches and then comparing to see if the results agree and make sense. I wish I could give you a more concrete answer, but unfortunately the answer is problem specific.
