### ISSUE TITLE
Case vs Control Differential expression Question

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5573]
Hi,

I am trying to test for differential expression between 2 samples (PBMCs activated vs PBMCs control). I integrated the samples first, then set DefaultAssay to "integrated" before running FindMarkers between the same cell types in the two samples.

However, reading through the issues, it seems to have been suggested to set DefaultAssay to "RNA" for differential expression after integration.

As I understand, the RNA slot contains the original data, before integration.
The question is why one would bother integrating the data is the differential expression relies on uncorrected data ?
Also, how is any bias accounted for ?

Thanks

**Comment by torkencz** [comment]
Hi this is covered in this issue:
https://github.com/satijalab/seurat/issues/1717
To summarize. Grouping cells together correctly via batch correction enables more precise results in the downstream analyses. However, we don't advise using the corrected data as the batch correction might mask actual biological results. What is important is to identify similar cells that will average out batch effects in downstream analyses.
