### ISSUE TITLE
Comparing DEGs between conditions

### ISSUE THREAD

**Issue by shanisa11** [satijalab/seurat#5576]
Hi,

I have scRNA-seq data I've analyzed and clustered, and I want to create a volcano plot for DEGs between conditions. 
For example - one condition is room temperature, and the other is 4c cold exposure.
I want to find the Differentially expressed genes between  COLD  treated mice and  RT  animals across a specific cluster.

How can I do that?

**Comment by mhkowalski** [comment]
Hello, 

As in the documentation for `FindMarkers()`, you could do something like the following, where `condition` is the variable that contains information about COLD vs RT and cluster 2 is the cluster of interest. 

`FindMarkers(obj, ident.1 = "COLD", group.by = 'condition', subset.ident = "2")
`
