### ISSUE TITLE
How to select a representative image for SpatialDimPlot when working with multiple slices?

### ISSUE THREAD

**Issue by swokybio** [satijalab/seurat#5577]
Hello, 

I have Visium data from 16 animals and 2 treatments (8 per treatment) that I am analyzing with Seurat. I have loaded the data, ran SCTransform, edited the orig.ident, merged the datasets, and performed dimensional reduction and clustering analysis on the merged dataset. 

My question now is how can I select specific tissue images to map the merged data using the SpatialDimPlot function? I would like to select one reference image of each treatment (healthy and disease) to plot the identified clusters in my merged object. 

I guess I am struggling to find where the Visium images are stored within my Seurat Object to be able to specify selected images to be plotted. 

Thank you in advance for your help!

**Comment by yixudong** [comment]
Have you solved your problem？Thank you in advance for your help!
