### ISSUE TITLE
Issue with running seqlevelsStyle(annotations) <- "UCSC"

### ISSUE THREAD

**Issue by epiBioCore** [satijalab/seurat#5578]
Hi,

I am working on [weighted_nearest_neighbor_analysis.Rmd](https://github.com/satijalab/seurat/blob/master/vignettes/weighted_nearest_neighbor_analysis.Rmd).
When I get to run this part:
seqlevelsStyle(annotations) <- "UCSC"

I receive the following error:
Error in .order_seqlevels(chrom_sizes[, "chrom"]) : 
  !anyNA(m32) is not TRUE

I am very new in bioinformatics as well as R.... I would appreciate it if anybody could help me to resolve this issue.

Thank you,
Sara

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/826
