### ISSUE TITLE
Different percentage of detected cells between DotPlot and FindMarkers function

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#5579]
Hello everyone :)

I have one question about percentage of detected cell.

In my analysis, I should check percentage of detected cell. So, I used two functions. One is **DotPlot** and the other is **FindMarkers**.

For those two functions, we can see percentage of expressed cell. 

I tried to check some specific genes whether percentage of expressed cell is compatible for those two functions.

```
clu7_DEG <- FindMarkers(object = inte.combined, ident.1 = 'Control', ident.2 = 'Case',group.by = "orig.ident",
                        subset.ident = 7, logfc.threshold = 0.5,test.use = "wilcox")
```
![image](https://user-images.githubusercontent.com/52641420/152461695-ccfb1302-1b5a-4793-b782-402b5e4fca66.png)

So, we can see pct.1 and pct.2 for 'Ccnd2' gene.

In dotplot, however, 'percent expressed' is not compatible with pct.1 and pct.2 for FindMarkers.

![image](https://user-images.githubusercontent.com/52641420/152463948-4a68f2d0-c7a8-40ae-ba19-77867081dead.png)

I think those two values should be compatible but they are not. I don't know why they are so different...

Thank you for reading.

Best,
Dahun

**Comment by mhkowalski** [comment]
Hello, 

I agree that these 2 values should be the same. Are you sure you are using the same 2 groups for these calculations? I say this because your DotPlot has "As3mtd2d3" as the label, but you specify "Case" in your code for `FindMarkers()`

**Comment by dahun73** [comment]
> Hello,
> 
> I agree that these 2 values should be the same. Are you sure you are using the same 2 groups for these calculations? I say this because your DotPlot has "As3mtd2d3" as the label, but you specify "Case" in your code for `FindMarkers()`

Thank you for reply :)
Oh, I’m sorry for confusing. Yes, it is same. I edited code right before because these are our collaborators’ data. Original code is ‘As3mtd2de’ in ident.2.

**Comment by pranithavangala** [comment]
@dahun73 the problem potentially is coming having different order or cells in meta.data slot compared to the RNA$data slot. Check that.

**Comment by aditisk** [comment]
Hi @dahun73, were you able to solve this problem? I'm encountering a similar issue while using Seurat v5.

@pranithavangala, I checked the number of cells, and they are the same, the order also appears to be the same in the metadata and the RNA$data slot. Do you have any other suggestions ?

Thanks

**Comment by Shawn-Xu** [comment]
I have the same question . The `Percent expressed` from DotPlot and pct from FindMarkers is too different. I think the results should be more consistent.
