### ISSUE TITLE
Different colored UMAPs in Unimodal UMAP projection

### ISSUE THREAD

**Issue by dhivyaa-6** [satijalab/seurat#5582]
I used the Unimodal UMAP projection to map an integrated query (integrated 2 condition seurat object) to the reference (integrated 6 condition seurat object). The clusters are not colored the same between the ref and the query transferred labels plus clusters 11,16, and 21 looks different in the query. How do I go about fixing the colors for the 2 UMAPs to match, and is there an explanation for those three clusters that are different in the query UMAP?

      all.combined <- RunUMAP(all.combined, reduction = "pca", dims = 1:30, 
      verbose = FALSE,return.model = T)

       all_gender.combined <- MapQuery(anchorset = gender.anchors, 
       reference = all.combined, query = all_gender.combined,   refdata = list(celltype = 
      "seurat_clusters"), reference.reduction = "pca", reduction.model = "umap")

       p1 <- DimPlot(all.combined, reduction = "umap", group.by = "seurat_clusters", label 
       = TRUE, label.size = 3,  repel = TRUE) + NoLegend() + ggtitle("Reference annotations")

      p2 <- DimPlot(all_gender.combined, reduction = "ref.umap", group.by = 
     "predicted.celltype", label = TRUE,  label.size = 3, repel = TRUE) + NoLegend() + 
      ggtitle("Query transferred labels")

      p1 + p
![Capture](https://user-images.githubusercontent.com/39684241/152546392-6df856a8-00f1-4fdf-9e2b-b66fbbfd2baa.JPG)
2

**Comment by yuhanH** [comment]
HI, 
You can set both `seurat_clusters` in all.combined and `predicted.celltype` in all_gender.combined as two factors with the same level.  Then, these two UMAP will show the matched colors. 

```
levels.set = c(xxxx)
all.combined$seurat_clusters <- factor(all.combined$seurat_clusters,
 levels = levels.set )

all_gender.combined$predicted.celltype <- factor(all_gender.combined$predicted.celltype,
 levels = levels.set )

```
