### ISSUE TITLE
Visualization of spatial data

### ISSUE THREAD

**Issue by shabs24** [satijalab/seurat#5583]
Thanks for the wonderful tools that makes analysis easy. I have few queries regarding the visualization of spatial analysis. 
(1) Is there a way to increase the size of the dot in the legend of dimplot. I have tired changing the legend size using thener but it does not alter the dot size. 
(2) I am trying to plot nCount_Spatial on a merged object from spatial data with two slices . It plots both the slices but when I try to change the legend size, it changes on the second slice but not first slice. Here is the code and the plot
SpatialFeaturePlot(OA_merge_cl4, features = "nCount_Spatial") + theme(legend.title = element_blank(),legend.key.size = unit(1, 'cm'))
![image](https://user-images.githubusercontent.com/17478233/152566155-43bd7d09-ccd7-46a4-b288-a0306a9a21ad.png)

**Comment by mojaveazure** [comment]
`SpatialFeaturePlot` returns a patchworked ggplot2 object, so you need to use patchwork's methods for editing the theme across all component plots: https://patchwork.data-imaginist.com/articles/guides/annotation.html

**Comment by shabs24** [comment]
Thanks for you reply. Is it possible to plot each slice separately. Since there are two spatial data set merged, SpatialFeaturePlot outputs two plots together. Thanks fro your help.

**Comment by sunta3iouxos** [comment]
Hi @mojaveazure  I am using ```combine = FALSE``` to do as you describe.
1. how can then change the plot options for each one of those. 
2. should I use then the same "patchwork" ggplot2 option to reconstruct the initial plot?
Is there a better way to plot the files in this list?
Thank you
