### ISSUE TITLE
SCTransform v2 glmGamPoi option

### ISSUE THREAD

**Issue by rbutleriii** [satijalab/seurat#5585]
For the [tutorial](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for SCTransform v2, glmGamPoi is installed, but `method = "glmGamPoi"` isn't called in the rest of the tutorial.

Is it run by default when calling `vst.flavor="v2"`? I am guessing no b/c man is it slow 😉

**Comment by saketkc** [comment]
`vst.flavor="v2"` does use `glmGamPoi`. Do you have an example I can take a look at?

**Comment by rbutleriii** [comment]
Ok, just double checking. The job timed out on my cluster where it didn't before with SCTv1 + glmGamPoi. I am likely misremembering how long it ran before.

It is a big dataset based off of allen brain inst mouse cortex from #5295. Although, now that I think of it, I changed the filtering a bit so the number of cells went from ~418k to ~460k.

In terms of the function documentation, when I dug deeper into `?sctransform::vst` it spells it out

**Comment by Joy8Liu** [comment]
Hi, there is a same issue I've encountered. I'd like to ask this problem for help.
I've installed 'glmGamPoi', and the answer to `'glmGamPoi' %in% installed.packages()` is True.

But when I run the code `Pre3 <- SCTransform(Pre3, verbose = FALSE)`, 
The response is the following information:

**`vst.flavor` is set to 'v2' but could not find glmGamPoi installed.
Please install the glmGamPoi package for much faster estimation.
--------------------------------------------
install.packages('BiocManager')
BiocManager::install('glmGamPoi')
--------------------------------------------
Falling back to native (slower) implementation.**

I wonder how I can resolve this problem. Thank you so much for your help in advance.
