### ISSUE TITLE
RBC contamination and low fraction reads per cell

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#5586]
Hi all, I have been trying to sort pancreatic cells for single cell seq but post sorting, when we look at the cells on the scope, they look like RBC's along with the epithelial cells from pancreas. However, we are not 100% sure if they are RBC's or small progenitor-like population. I have sequenced some of my samples before and we got this warning message from cell ranger output file, that reads "ambient RNA" or sometimes "low fraction reads per cell". Is it possible that RBC contamination might be resulting in these warning messages since they are anucleated and don't really have mRNA? Or if someone knows what are the other reasons we might be getting these warning messages, could you please let me know. Is there a way we can selectively read the epithelial cell transcripts or get rid of RBC transcripts using Seurat package at any step? Thanks!

**Comment by torkencz** [comment]
Hi, you might want to ask cell ranger regarding the warning messages. You can identify low quality cells using the Seurat package and could potentially identify RBCs by finding related markers. https://www.biostars.org/p/469978/
