### ISSUE TITLE
integrated defaultAssay issue

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5587]
Hi,

I may be doing something wrong, but after I integrate my samples, if I set DefaultAssay to RNA (say to plot a UMAP of uncorrected samples) and then I set DefaultAssay back to integrated, I am unable to plot the UMAP of the corrected samples, and keep plotting the uncorrected UMAP.

run sequence:
IntegrateData
RunPCA
RunUMAP
DefaultAssay -> RNA
DimPlot
DefaultAssay -> integrated
DimPlot

Am I missing something ?

Thanks

**Comment by yuhanH** [comment]
Hi, @gianfilippo 
In the `DimPlot`, you can set `reduction` to the integrated umap name.
