### ISSUE TITLE
Integrated analysis with Seurat vignette and Harmony as batch correction

### ISSUE THREAD

**Issue by GreyRockIQ** [satijalab/seurat#5588]
Hello
I am seeing very large difference in cluster cells in Integrated analysis with Seurat vignette and Harmony as batch correction for my dataset.
The image that comes without integration before Harmony is same as integration obtained with Seurat integration vignette alone. The number of variable clusters across conditions disappeared with Harmony integration.  How should I take decision to conclude which one is correct? 
Thanks
GreyRock

**Comment by yuhanH** [comment]
Hi @GreyRockIQ 
Could you post your scripts and the results? Otherwise, no good way to conclude which way is better.
