### ISSUE TITLE
Question: VlnPlot axis formatting

### ISSUE THREAD

**Issue by mdhe1248** [satijalab/seurat#559]
Hi, 
I ran VlnPlot for four genes. So, I obtained four panels in one figure. Each panel showed clusters in the x-axis and the expression level of the given gene in the y-axis.
I have several questions: 
1) How could I change the fontsize of ticklabels?
2) How could I change axis label names? For example, I would like to write "Cluster" instead of "Identity".
3) How could I change the arrangement of panels? I obtained 3 panels in the first row and 1 panel in the second row. I would like to make 2-by-2 panel array.

For the first two questions, I tried the below. I didn't have any luck.
```R
p1 = VlnPlot(object = obj, features.plot = c("gene1", "gene2", "gene3", "gene4"), size.x.use = 8, size.y.use = 8, size.title.use = 9, do.return = TRUE) 
p1 + theme(axis.text.x = element_text(size = 8)) + xlab("Cluster")
```

Best,
Jerry

**Comment by andrewwbutler** [comment]
Hi Jerry,

You can pass `return.plotlist = TRUE` as an argument to get back a list of the ggplot objects that you can then modify as you were trying above. To combine them into a grid, we use `cowplot::plot_grid` internally which allows you to specify the number of rows/columns.

**Comment by atchen** [comment]
Hi Andrew,

Do you mind providing an example of how you would use `cowplot::plot_grid` to get a 2x2 plot? I also have the same question as Jerry.

**Comment by leonfodoulian** [comment]
Hi @atchen,

Simply refer to [this website](https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html) for a comprehensive tutorial on how to use `cowplot::plot_grid()`. For a 2x2 plot, simply specify `ncol = 2` (or `nrow = 2`). 

Best,
Leon

**Comment by atchen** [comment]
Thanks. I used the following code, and it works perfectly.

`plot_grid(VlnPlot(object=obj, features.plot = 'gene1'), 
          VlnPlot(object=obj, features.plot = 'gene2'),
          VlnPlot(object=obj, features.plot = 'gene3'),
          VlnPlot(object obj, features.plot = 'gene4'),
          ncol=2)`

**Comment by mdhe1248** [comment]
Thanks all! I will also work on plotting.

**Comment by mdhe1248** [comment]
@atchen 
It has been a while, but in case somebody is interested I am writing; Just for convenience, you could try this: 
```R
genes.viz = c("gene1", "gene2", "gene3", "gene4")
p = VlnPlot(object = obj, features.plot = genes.viz, do.return = TRUE, return.plotlist = TRUE) #Store plot objects in `p`.
```
(optional) Then, we maybe format individual plots.  For example,
```R
p1 <- list() 
for (i in seq_along(p)){
    #Change x and y tick label font size.
    p1[[i]] = p[[i]] + theme(axis.text.x = element_text(size = 8), axis.text.y = element_text(size = 8)) 
}
```
Then plot using `plot_grid`
```R
plot_grid(plotlist = p1, ncol = 2) #display all vlnplots. Notice that I used `p1`
```
