### ISSUE TITLE
Determine if normalization has been performed?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#5590]
When you create a seurat object, the data slot for an assay is always non-null, whether or not normalization has been performed. Is there a programmatic way to determine whether normalization has been performed? I think one could test whether:

all(seuratObject[[assayName[[@counts ==  seuratObject[[assayName[[@data)

but this seems inefficient. Can one more directly figure this out? Thanks in advance.

**Comment by bbimber** [comment]
Here is one idea that seems to work. Would you be able to comment on whether this should be a reliable method to test this?
```
.HasNormalizationBeenPerformed <- function(seuratObj, assayName = 'RNA'){
  return(!identical(seuratObj@assays[[assayName]]@counts, seuratObj@assays[[assayName]]@data))
}
```

**Comment by yuhanH** [comment]
Hi, usually counts and data slots are both sparse matrix. You can direct compare their non-zero value. 
```
pbmc_small[['RNA']]@counts@x == pbmc_small[['RNA']]@data@x
```
But for a real check, you can just look some top value in the `pbmc_small[['RNA']]@data@x`. If it is normalized, it will not be all integers.
