### ISSUE TITLE
integrate or not integrate before mapping to a reference ?

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5592]
Hi,

I find different results when mapping to a reference (your PBMC reference) if I map my samples one by one or first integrate then map.

As far as I understand, mapping to a reference is relying on normalized/scaled data (SCT slot in my case), not the integrated slot.

I assume the differences I see may be due to differences arising from normalization/scaling based on a single sample or multipel samples together?

Also, given the difference, which approach is expected to produce better mapping ?

Thanks

**Comment by yuhanH** [comment]
Hi @gianfilippo 
Map your samples one by one is suggested.  Mapping to a SCT-normalized reference is replying on counts matrix. It will use reference SCT model to normalize your query samples.
