### ISSUE TITLE
FindConservedMarkers giving error when N of cells < min.cells.group

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5594]
Hi,

when I run FindConservedMarkers, I see that is one of the groups has 0 cells, it is skipped by the FindConservedMarkers function, with a warning.

If one of more groups have a N of cells < min.cells.group, then the function ends abruptly with an error.

Thanks

**Comment by gianfilippo** [comment]
Similar error also in the latest release
Error in marker.test[[i]] : subscript out of bounds

when all the groups do not have enough cels

**Comment by gianfilippo** [comment]
Hi, sorry, I was away. Let me see if I can extract a subset and recreate the error.

**Comment by saketkc** [comment]
thanks!
