### ISSUE TITLE
Difference between ClusterTree and DotPlot with cluster.idents 

### ISSUE THREAD

**Issue by tarzua** [satijalab/seurat#5600]
First time analyzing scRNA-seq data, so might be an obvious solution issue.

After using SCTransform to normalize two sets and integrate them, I got to an interesting DotPlot with some selected genes and wanted to find the hierarchical clustering using those genes as the features. That worked as far as reordering the cluster on the plot, so I wanted to add a tree plot with it using just the BuildClusterTree, giving the same genes as features. That works but does not match the DotPlot order. I understand they are likely doing different things, so I was wondering if there is a way to get a phylogenetic tree of the same output the cluster.idents argument in the DotPlot function has? Any help is appreciated!

```
mito<- c("UBL5", "MDH2", "ATF4", "PDHA1", "RNF5")

DefaultAssay(combined) <- "RNA"
DotPlot(combined, features = mito, dot.min = 0.01, cols = c("RdBu"), dot.scale = 10, cluster.idents = TRUE) +
  coord_flip() + xlab("Genes") + ylab("Cluster")

DefaultAssay(combined) <- "SCT"
combined.tree <- BuildClusterTree(object = combined, features = mito)
PlotClusterTree(combined.tree)

```
I also tried using the RNA assay but that gives no tree just a single line with the clusters.

![DotPlot](https://user-images.githubusercontent.com/99217196/152871125-ed9a2b50-193d-47c7-b88e-9722aec3c7ee.png)
![ClusterTree](https://user-images.githubusercontent.com/99217196/152871127-72b212c5-1421-46c1-a4cd-5afa822725d2.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  It's not a directly Seurat solution but my package scCustomize offers a Clustered DotPlot that I think might be something like what you are looking for.  See vignette on package website for details on function use and optional parameters:
https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#clustered-dotplots

Best,
Sam

**Comment by rsatija** [comment]
+1 to the previous solution, but also not that DotPlot performs clustering on a scaled matrix (see the lines of code below from visualization.R). We had not originally intended the output to be the same as BuildClusterTree, though I can see why this might be valuable.

```
    mat <- scale(x = mat)
    id.levels <- id.levels[hclust(d = dist(x = mat))$order]
```
