### ISSUE TITLE
issue with scale in feature plot

### ISSUE THREAD

**Issue by carlosaya2** [satijalab/seurat#5603]
Hi Seurat support team,

I came across an issue with the scale when plotting CD31 across three conditions, using the feature plot function, but not when using Vlnplot function. I have performed CLR normalisation and arcsin transformation in two different Seurat objects and they are showing the same issue. To generate both plots, I am using the code below. I tried the keep.scalefunction to see if it changed the scale but it did not. I think the right scale is the one used by vln plot. I just found this one by serendipity but I now wonder if the same will happen to some of my 277 ADTs. for the other ones I checked, the scale of the feature lot and vlnplot match.    

```
p5 <- VlnPlot(positives.DS06, features = c("ADT_anti-human-cD31"), ncol = 1, slot = 'data', group.by = c("cond")) + theme(legend.position = 'none')
p6 <- FeaturePlot(positives.DS06, features =  c("ADT_anti-human-cD31"), ncol = 1, split.by = "cond", reduction = 'umap', slot = 'data') + theme(legend.position = 'right')
q3 <- plot_grid(p5,p6, rel_widths =c(1,3)) 
```
The CLR normalised data looks like this:
![image](https://user-images.githubusercontent.com/61134130/152945083-064eac8e-49d9-4de4-a947-d874a08df8a7.png)

and the arcsin transformed data like this:
![image](https://user-images.githubusercontent.com/61134130/152945145-acca4026-5c2a-4644-b7d2-de6ae5408eaa.png)

and this is the log of the counts: 
![image](https://user-images.githubusercontent.com/61134130/152948480-4f62c1ad-4038-4898-937d-b3f43b4eb348.png)

and this is the feature plot of counts
![image](https://user-images.githubusercontent.com/61134130/152948807-552c3a85-11ca-4d4b-a240-e1d0ff517e1e.png)

I would highly appreciate your help on how to solve this issue. 

Thank you heaps, 

Carlos

**Comment by rsatija** [comment]
I'm not able to reproduce this issue. Using the cbmc dataset on SeuratData, if I run

```
FeaturePlot(cbmc,"adt_CD3",slot = 'counts')
```

The scale is correct (0...3000, same scale as the counts from the Violin plot).

Please make sure you are specifying `slot=counts`, if that does not solve the problem please re-open this issue
