### ISSUE TITLE
Subset function issue

### ISSUE THREAD

**Issue by hzhong9** [satijalab/seurat#5604]
Hi, when using the subset function

object<-subset(object, cells  =WhichCells(object, idents = "GM"))
 
it prompted:

Error in `[[<-`(`*tmp*`, dimreduc, value = tryCatch(expr = subset.DimReduc(x = x[[dimreduc]], : [[<- defined for objects of type "S4" only for subclasses of environment

What is this error? How might this issue be resolved?
R version 3.6.3
"x86_64, linux-gnu"
Seurat_3.2.3       
SeuratObject_4.0.0

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Have you tried updating to current version of Seurat (if possible)?  I have run the following code with Seurat 4.0.6 and pbmc3k object with no errors.  If updating the package and object doesn't solve the issue then it would seem like there might be an issue with your specific object.

Best,
Sam

```
library(Seurat)

pbmc <- pbmc3k.SeuratData::pbmc3k.final

pbmc <- UpdateSeuratObject(pbmc)

pbmc$sample_id <- sample(c("sample1", "sample2", "sample3", "sample4", "sample5", "sample6"), size = ncol(pbmc), replace = TRUE)

Idents(pbmc) <- "sample_id"

pbmc <- subset(pbmc, cells = WhichCells(pbmc, idents = "sample1"))
```

**Comment by hzhong9** [comment]
Hi Sam,

Many thanks for sharing your analysis and your suggestions! Yes, updating to current version of Seurat is optimal. In the end, it was a memory issue, as the object was quite big. Once the system memory had been released, subsetting was run successfully.

Thanks again for your helps.

Best,

Hang

**Comment by yuhanH** [comment]
@samuel-marsh  Thanks again for your help!

**Comment by 98xy** [comment]
Hi,
Here comes the same issue again, while I find the main conflict is between Seurat 3.2.3 and SeuratObject. How to solve it without changing the version of R and Seurat?

`Error in `[[<-`(`*tmp*`, dimreduc, value = tryCatch(expr = subset.DimReduc(x = x[[dimreduc]],  : 
  [[<- defined for objects of type "S4" only for subclasses of environment`

Thanks a lot for your help!
