### ISSUE TITLE
Best way to differentiate highly similar clusters

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#5606]
Hello!

I am trying to find what is different between two very similar clusters. I have a list of genes which are supposed to mark one specific cluster, but it is showing nearly the same expression in both clusters. Assuming the gene list is correct, I am not sure where to go from here, because both clusters, when subset from an integrated dataset, continue to cluster together when reclustered (I did reintegrate them so that could be why). I also tried regressing out the genes resulting from a FindMarkers() run between these two clusters in order to highlight the expression of the list in one cluster without the noise the other highly similar cluster may be showing, but again, they are showing the same expression of this gene list. 

Is finding and then regressing out the genes with similar expression between them the right approach? What is the best method in Seurat to find differences between highly similar clusters? I admit this may come from my weaker math background and not understanding the complexities mathematically speaking of this question.  

Hopefully this makes sense and thanks for reading!

**Comment by mhkowalski** [comment]
Hi, 

I'm not sure I entirely understand what you are asking. If the expression of your list of genes is the same in both clusters, this list of genes is probably not useful in differentiating these two clusters.The best way to differentiate why 2 clusters are separate is to run FindMarkers(). You may need to lower the logfc.threshold parameter if these clusters are highly similar. 

If they are truly distinct clusters, they should cluster separately both before and after subsetting your integrated data. Are you using the same variable to split your data in both rounds of integration? 

Hope this is helpful.
