### ISSUE TITLE
Define minimum of features to build a cluster?

### ISSUE THREAD

**Issue by butterberg** [satijalab/seurat#5607]
FindallMarkers returns only few markers (~10) for some clusters . What value in which function (FindNeighbors, FindClusters?) do I have to adjust in what way so that these cells are merged with nearest clusters instead of building a cluster of their own.  By reducing the resolution, this cluster still shows up. Can I somehow tell the script the minimum of features required to build a cluster? Appreciate anykind of suggestions!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  As far as I'm aware there is not parameter to adjust based on number of features unique per cluster.  Clusters could be defined by gradients of expression and/or many other factors of expression and as such I can imagine might be difficult to try and implement a parameter to define number of unique factors as unique can mean many different things in this type of data.  It is up to the end user to determine optimal settings for what can be controlled, # of HVGs, # of PCs, Resolution etc.

Additionally, final clusters following neighbor graph and Louvain/Leiden clustering do not necessarily need to be treated as hard and final.  It is all going to depend on what downstream analyses you are going to perform and what you visualization you want to show and the specifics of each particular dataset.  Therefore if for your particular downstream analysis/visualization you have deeply examined two clusters and believe that they should be merged you can simply rename the identities and merge those two (or more clusters) before running your particular analysis.

Best,
Sam

**Comment by torkencz** [comment]
Hi,
As far as I know you cannot choose the number of features that are specific to a cluster. You can adjust cluster size, but that will be very specific to your biological sample.
