### ISSUE TITLE
Default violin plot keeps returning split examples which differ from documentation example

### ISSUE THREAD

**Issue by BobvanSchendel** [satijalab/seurat#5609]
I'm analyzing a dataset from a Quijada et al. paper where I'm attempting to find the top n neurotrophic factors. I found these and try to plot them in a single violin plot like in the example on this page: https://satijalab.org/seurat/articles/visualization_vignette.html
![violinplot](https://user-images.githubusercontent.com/37450255/153240986-f05f8849-1cc6-44cc-bb6e-b9e451d0bd1a.png)
I want to have all the violins for the genes in 1 plot so to speak but can't seem to get this to work.

Additionally my Ridge plots look quite different from the example on the aforementioned page: 
![ridgeplot example](https://user-images.githubusercontent.com/37450255/153241492-10ef5bcc-68ea-4eb3-ae04-6c43c41a4c09.png)

I'm pretty sure I'm using the last version of Seurat as packageVersion('Seurat') returns 4.1.0.

Is there something goofy I'm missing?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but can you please provide the code you are running?

Can you also clarify what you mean by in one plot for the violin plots?

Best,
Sam

**Comment by BobvanSchendel** [comment]
In my script I'm doing a call to VlnPlot like so:
`VlnPlot(after_data_merged, features=top_n)`
and that's the weird thing. I'm using a normal Seurat object generated from some scRNAseq data and I'm calling VlnPlot in the exact same way as in the vignette I mentioned.
I tried using a different set of features, thinking it may have been that but that got me nowhere

I meant that I want the features to visualize to be in the same plot, such as in the LYZ part of [this image](https://satijalab.org/seurat/articles/visualization_vignette_files/figure-html/visualization_smorgasbord-2.png) found on [this page](https://satijalab.org/seurat/articles/visualization_vignette.html)
 I attempted the same on a different PC with (roughly) the following code):
`dataset = Read10X(data.dir = location)`
`seurat.obj = CreateSeuratObject(counts = dataset, min.cells = min_cells_parameter, min.features = min_features_parameter)`
`VlnPlot(seurat.obj, features = head(rownames(seurat.obj)))`

**Comment by samuel-marsh** [comment]
Hi,

I'm still a little confused as to what you mean for Violin plots.  Do you mean like how x-axis has the different cell types?

Best,
Sam

**Comment by BobvanSchendel** [comment]
Yes. In my case I want specific features, such as the Bsg and Nenf features of my dataset on the x-axis instead of the cell types in the example.

**Comment by samuel-marsh** [comment]
Sorry I'm still a little confused.  In the Violin plots of the vignette there are not multiple features on one x-axis.  So I'm not sure how your violin plots are different from those in vignette other than the vignette data is grouped by cluster and yours appears grouped by project.

**Comment by BobvanSchendel** [comment]
I found a solution, this issue can be closed
