### ISSUE TITLE
Gene Synonyms appearing in both up and downregulated hits from FindMarkers()

### ISSUE THREAD

**Issue by ksaunders73** [satijalab/seurat#5610]
Hello! 

So I am very confused about this. I was running FindMarkers() between two groups, and I got these results:

```
                p_val avg_log2FC pct.1 pct.2     p_val_adj
ATP5E   1.973680e-183   1.872929 0.667 0.072 1.379208e-178
ATP5F1E 3.703167e-105  -2.093624 0.083 0.713 2.587773e-100
```

According to GeneSymbolThesaurus() (as well as looking up the genes on GeneCards), these genes are synonyms:

> GeneSymbolThesarus("ATP5E")
  |=====================================================================| 100%
    ATP5E 
"ATP5F1E" 
> GeneSymbolThesarus("ATP5F1E")
  |=====================================================================| 100%
Warning: The following symbols had no synonyms: ATP5F1E
NULL

I am not sure how to interpret this result, and unfortunately I am not sure how to provide a reproducible result without sharing data which I am not allowed to heh.

Thanks for reading!

**Comment by samuel-marsh** [comment]
Hi

Not member of dev team but hopefully can be helpful.  Was the object created from multiple experiments?  If so it could be possible that one experiment as aligned using older reference annotation and therefore has old symbol ATP5E whereas another used up to date annotation and has the current symbol ATP5F1E.  It does seem strange that they go in completely opposite directions if they are in same cluster though but maybe there is dataset specific reason for that...

In a quick search I couldn't find any gene previously named ATP51FE so my guess is either differential alignment between datasets or a mistake but can't be sure without more details.  

Best,
Sam

**Comment by ksaunders73** [comment]
Hi @samuel-marsh ,

That makes sense, I am integrating from multiple experiments done in different years so that is probably it. Do you happen to know of ways to deal with these annotation differences?

**Comment by samuel-marsh** [comment]
Hi @ksaunders73 unfortunately you will need to rename the features from the experiments prior to creating Seurat object to that all experiments have the same feature name set.  You'll need to update analysis too because as your Find Markers example shows it's possible that HVGs and other steps were based on features Seurat thought we different but are actually the same gene.

Best,
Sam

**Comment by torkencz** [comment]
Yeah renaming features should work here.

**Comment by ksaunders73** [comment]
Thank you both for your help, @samuel-marsh @torkencz !
