### ISSUE TITLE
MergeSeurat function issue

### ISSUE THREAD

**Issue by ShuyangXu** [satijalab/seurat#562]
Hi,
There may be a little bug in *MergeSeurat*.  Here *MergeSeurat* uses *RenameCells* to change cell names, then it checks whether there is any duplicate names in *cell.names* slot.
```
  if (!missing(x = add.cell.id1)) {
    object1 <- RenameCells(object1, add.cell.id = add.cell.id1, for.merge = TRUE)
  }
  if (!missing(x = add.cell.id2)) {
    object2 <- RenameCells(object2, add.cell.id = add.cell.id2, for.merge = TRUE)
  }
  if (any(object1@cell.names %in% object2@cell.names)) {
    stop("Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names")
  }
```
But in *RenameCells*, when **for.merge** is TRUE, object will be returned before *cell.names* slot is changed. So it's impossible that *MergeSeurat* passes duplication check, even though argument 'add.cell.id*' is provided. 
Maybe argument **for.merge** is unnecessary? 
```
  colnames(object@raw.data) <- new.rawdata.names
  rownames(object@meta.data) <- new.cell.names
  if (for.merge) {
    return(object)
  }

  object@cell.names <- new.cell.names
  colnames(object@data) <- new.cell.names
```

**Comment by andrewwbutler** [comment]
Please see #549.
