### ISSUE TITLE
How to use vlnplot to present a part of cell types

### ISSUE THREAD

**Issue by mengfeich** [satijalab/seurat#5621]
I used vlnplot to generate plots showing only 3 of 16 clusters which compared two conditions last September, but I got the following message when I tried to repeat it yesterday. Can anyone help me out? Thank you.

Warning messages:
1: In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :
  All cells have the same value of Cd200.
2: In max(data[, feature][is.finite(x = data[, feature])]) :
  no non-missing arguments to max; returning -Inf
3: In min(data[, feature]) :
  no non-missing arguments to min; returning Inf

Here is my process:
###Rename the clusters:
Lung.combined <- RenameIdents(Lung.combined, `0` = "CD86 B", `1` = "Ly6g NPs", `2` = "NK", `3` = "Cd8a T", `4` = "Cd68 Mac", `5` = "CD4 T", `6` = "CD11b Mac", `7` = "Ly6c2 Mac", `8` = "Activated T", `9` = "CD20 B", `10` = "CD11c DCs", `11` = "CD25 Treg", `12` = "CD11c Mac", `13` = "ILcs", `14` = "Mast cells", `15` = "CD79a B", `16` = "Ly6c Mac")
DimPlot(Lung.combined, label = TRUE)

###create a column in the meta.data slot to hold both the cell type and conditions 
Lung.combined$celltype.Lung17m <- paste(Idents(Lung.combined), Lung.combined$Lung17m, sep = "_")
Lung.combined$celltype <- Idents(Lung.combined)
Idents(Lung.combined) <- "celltype.Lung17m"

###Violin plots show gene expression (reads) across 16 clusters. This step works.
plots <- VlnPlot(Lung.combined, features = c("Cd200", "H2-Aa"), split.by = "Lung17m", group.by = "celltype", pt.size = 0.1, slot = "counts", combine = FALSE)
wrap_plots(plots = plots, ncol = 1)

**The warning message come from this step:**
###Violin plots show gene expression (reads) in 3 clusters
VlnPlot(Lung.combined, features = "Cd200", split.by = "Lung17m", group.by = "celltype",  idents = c("Cd68 Mac", "CD11c Mac", "CD11c DCs"), pt.size = 0.1, slot = "counts", combine = FALSE)

**Comment by k3yavi** [comment]
Hi @mengfeich ,

It's a warning message and according to the text `All cells have the same value of Cd200.`, it literally means that in your dataset that gene has same count across cells. You can potentially verify this with the input data for the same to sanity check if that's true.
