### ISSUE TITLE
VlnPlot color jitter/dots to match fill.by

### ISSUE THREAD

**Issue by mbartl13** [satijalab/seurat#5622]
Hi- I want to color dots in the VlnPlot as the fill color to more easily distinguish the outliers between two groups, I tried modifying with ggplot2 mods but got "NULL" as the response. I'm most interested in comparing the number of cells that express SLAMF1 between my two groups detected/undetected so if another representation method is recommended happy to take suggestions. 

`VlnPlot(seurat_object, 
        features = c("SLAMF1"), 
        split.by = "cells_of_interest", 
        group.by = "old.ident2", 
        fill.by="cells_of_interest",
        pt.size = 1,
        combine = FALSE, 
        log=TRUE)+geom_point(aes(colour="cells_of_interest"))
`
![image](https://user-images.githubusercontent.com/73361524/153896932-06424457-768f-4860-bef4-7f3c7cd1b691.png)

Thanks!

**Comment by saketkc** [comment]
One way to do this would be to set pt.size to 0 and then use `geom_jitter`. Here's an example without using the split option:

```r
p <- VlnPlot(object = pbmc_small, features = 'PC_1', pt.size = 0) 
p + geom_jitter(mapping = aes(color = ident), data = p$data)
```

**Comment by yulchen810** [comment]
Hi, 
Does anyone know the default colors used for the legend, I'd like to change the legend text but remain the same color used as the default.  Thank you very much!
![截图20240318120845](https://github.com/satijalab/seurat/assets/43404279/26f17b26-4c27-42ee-8214-16dd8fff527e)

Best,
