### ISSUE TITLE
Using reference dataset cell type prediction score to weigh anchors

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#5626]
Annotating cell types of scRNA/scATAC data sets from previously annotated reference data sets relies on the accuracy of the reference predictions.  I think that the prediction score of the reference anchor cells should also be considered in the weighting procedure.  

For example, imagine a query cell is equidistant from two reference anchors and they have equal weight.  However, one reference anchor has a prediction score max of 0.99, and the other 0.5.  The reference with more confident prediction score should be given more weight.  

The way I would do this is perhaps multiplying the anchor weights by the prediction score max.  Or to account for a cells prediction score distribution, I would multiply the anchor cell weight by the information content of its prediction scores, calculated the same way as sequence logo letter height: 
log2(i possible cell types) + sum(prediction_score_i * log2(prediction_score_i) )

Using information content would account for cells that have evenly distributed prediction scores, favoring cells with one very high prediction score over cells with two or more moderate prediction scores

**Comment by torkencz** [comment]
Hi, Thank you for your suggestion. In Seurat you can transfer continuous annotations so you could transfer the prediction score of the refence anchor cells as well.
