### ISSUE TITLE
Add cell labels to DoHeatmap without adding color code group bar

### ISSUE THREAD

**Issue by Minoo-ASTY** [satijalab/seurat#5629]
How can I add cell labels on top of the DoHeatmap withou having color groupbar for cell identities? In another sitaution also be able to add cell labels below the group bar which is made by clusters identity?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  In terms of labeling the groups without the group bar you can do that by setting the colors of the bar to "NA".

```
num_idents <- length(unique(Idents(object = pbmc)))
na_colors <- rep("NA", num_idents)

DoHeatmap(object = pbmc, features = gene_list, group.bar = T, label = T, group.colors = na_colors)
```

For your second question when you say label cells.  Do you mean label the specific line that correspond to specific cells for every cell in the plot?

Best,
Sam

**Comment by Minoo-ASTY** [comment]
Thanks for your response. Yes, I meant labelling each column in the heatmap, and each column represent a cell then it would be cell names at the top or bottom of the heatmap. as long as your solution removes the color bar from the top, it prints the identity legend next to the heatmap. What I did to solve this problem used a another code to be able to manipulate the output of heatmap, which is like below:

```

mat<- pbmc[["RNA"]]@data[gene_list, ] %>% as.matrix()

## scale the rows
mat<- t(scale(t(mat)))

cluster_anno<- srat@meta.data$cluster_anno

## make the black color map to 0. the yellow map to highest and the purle map to the lowest
col_fun = circlize::colorRamp2(c(-1, 0, 3), c("#FF00FF", "black", "#FFFF00"))
sample_order<-  colnames(mat)
# plot the heatmap
library(ComplexHeatmap)
meheatmap1<-Heatmap(mat, name = "Expression",  
        column_split = factor(cluster_anno),
        cluster_columns = F,
        show_column_dend = FALSE,
        cluster_column_slices = F,
        column_title_gp = gpar(fontsize = 8),
        column_gap = unit(0.5, "mm"),
        cluster_rows = F,
        show_row_dend = FALSE,
        col = col_fun,
        row_names_gp = gpar(fontsize = 4),
        column_title_rot = 90,
        top_annotation = HeatmapAnnotation(foo = anno_block(gp = gpar(fill = scales::hue_pal()(9)))),
        show_column_names = T,
        use_raster = TRUE,
        raster_quality = 4,column_order = sample_order,row_names_side = "left")

draw(meheatmap1)
```

**Comment by samuel-marsh** [comment]
Hi,

Yes that is non-Seurat way to solve it.  You could easily simplify it too by just pulling from the scale.data slot instead of scaling after pulling from the data slot.

Best,
Sam
