### ISSUE TITLE
Subsetting seurat object to re-analyse specific clusters 

### ISSUE THREAD

**Issue by lmacdonald12** [satijalab/seurat#563]
Hi there, 

I have been using Seurat to do analysis of my samples which contain multiple cell types and I would now like to re-run the analysis only on 3 of the clusters, which I have identified as macrophage subtypes. I subsetted my original object, choosing clusters 1,2 & 4 from both samples to create a new seurat object for each sample which I will merged and re-run clustersing for comparison with clustering of my macrophage only sample. 

```R
#Identities are "cluster_sampleNo"
actA <-SubsetData(object = syno.combined, ident.use="1_139")
actB<-SubsetData(object = syno.combined, ident.use="2_139")
active <- MergeSeurat(actA, actB)
actC<-SubsetData(object = syno.combined, ident.use="4_139")
active <- MergeSeurat(active, actC)

remA<-SubsetData(object = syno.combined, ident.use="1_149")
remB<-SubsetData(object = syno.combined, ident.use="2_149")
remission <- MergeSeurat(remA, remB)
remC<-SubsetData(object = syno.combined, ident.use="4_149")
remission <- MergeSeurat(remission, remC)

active <- NormalizeData(object = active)
active <- ScaleData(object = active)
active <- FindVariableGenes(object = active, do.plot = FALSE)

remission <- NormalizeData(object = active)
remission <- ScaleData(object = active)
remission <- FindVariableGenes(object = active, do.plot = FALSE)

#Take the union of the top 2k variable genes in each dataset for alignment 
hvg.active <- rownames(x = head(x = active@hvg.info, n = 2000))
hvg.remission <- rownames(x = head(x = remission@hvg.info, n = 2000))
hvg.union <- union(x = hvg.active, y = hvg.remission)

#Make merged object
syno.combined <- RunCCA(object = active, object2 = remission, genes.use = hvg.union, add.cell.id1 = "Active", add.cell.id2 = "Remission")

syno.combined <- AlignSubspace(syno.combined, reduction.type = "cca", grouping.var = "sample", 
    dims.align = 1:20)
```
However, when i try to perform the alignment i get the following error..
`Error in cc.loadings[[g]] : subscript out of bounds`

Can you help me with this? or suggest another approach?

Cheers,
Lucy

**Comment by andrewwbutler** [comment]
Hi Lucy,

The `grouping.var` needs to refer to a meta.data column that distinguishes which of the two groups each cell belongs to that you're trying  to align. In`syno.combined@meta.data` is there a column called `sample`? If not, an easy modification to the workflow above would be to add something like the following before `RunCCA`: 

```R
active@meta.data$sample <- "active"
remission@meta.data$sample <- "remission"
```

**Comment by lmacdonald12** [comment]
Hi Andrew,

Yeah I made the sample column it doesn’t seem to make a difference. Any other ideas how I would go about it?

Cheers
Lucy

On 26 Jun 2018, at 21:14, Andrew Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lucy,

The grouping.var needs to refer to a meta.data column that distinguishes which of the two groups each cell belongs to that you're trying to align. Insyno.combined@meta.data<mailto:syno.combined@meta.data> is there a column called sample? If not, an easy modification to the workflow above would be to add something like the following before RunCCA:

active@meta.data$sample <- "active"
remission@meta.data$sample <- "remission"

**Comment by andrewwbutler** [comment]
Could you provide a reproducible example or if possible the data (or a subset of the data that reproduces the issue)?

**Comment by satijalab** [comment]
Try setting do.clean=T when running SubsetData, this should fix the problem.

When we run SubsetData, we have (by default) not subsetted the raw.data slot as well, as this can be slow and usually unnecessary. This can in some cases cause problems downstream, but setting do.clean=T does a full subset.

We recognize this is a bit confusing, and will fix in future releases.
