### ISSUE TITLE
SCT vst.flavor in FindIntegrationAnchors

### ISSUE THREAD

**Issue by BiotechPedro** [satijalab/seurat#5634]
Hi Seurat team!

When performing integration on datasets normalized with SCTransform I want to ensure if internally it uses recently developed "v2" as vst.flavor. If not, is there a way to set a parameter in FindIntregrationAnchors() or are you working on it? 

Thanks a lot!

Pedro

**Comment by saketkc** [comment]
No parameters need to be adjusted for using the `vst.flavor='v2'` outside of `SCTransform`. See this [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for a complete workflow including integration and differential expression.
