### ISSUE TITLE
Creating spatial Seurat object from count matrix

### ISSUE THREAD

**Issue by shabs24** [satijalab/seurat#5635]
I want to create a spatial Seurat object from a published data. The authors have submitted the matrix count, the low res image, tissue position list. I am able to load the image  using the  Read10X_Image() function. How do I load the count data as it is not in h5 format and integrate the image and  count matrix.

Any suggestions?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I would check out these other posts to see if their solutions can help you navigate object creation.
#3595 #2790 #4993

Best,
Sam
