### ISSUE TITLE
Duplicate cell names - RunMultiCCA After CreateSeuratObject

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#564]
Hi,

#400 is suitable before CreateSeuratObject function, but actually now I am running an analysis on a subSet of cluster extracted form a multi-experiment.

I subset data of desired clusters in all my 4 groups, now I would like to re-run FindVariableGenes() and ScaleData().
Actually when i run RunMultiCCA I got the Duplicate cell names issue,

can I resolve it somehow ?

Many Thanks
Paolo

**Comment by andrewwbutler** [comment]
Hi Paolo,

Try ensuring the cells in all the objects have unique cell names with `RenameCells` function before `RunMultiCCA`.

**Comment by paolo-kunderfranco** [comment]
There is no `RenameCells `function,
do you mean `RenameIdent `? Any suggestion how to use it?

**Comment by paolo-kunderfranco** [comment]
Yes I am using version 2.2, I'll update version,
Thanks
Paolo

**Comment by yueqiw** [comment]
@paolo-kunderfranco 

I manually added prefixes to the cell names in each matrix and it solved the duplicate cell name issue for me. No need to remove cells. 
Try the code in the following post: 
https://github.com/satijalab/seurat/issues/624#issuecomment-407581042
