### ISSUE TITLE
Add glmGaiPoi to seurat docker image

### ISSUE THREAD

**Issue by koetjen** [satijalab/seurat#5641]
Would like to have glmGaiPoi installed in seurat docker file to enable sctransform options conveniently

**Comment by saketkc** [comment]
Thanks for the suggestion. We are in the process of adding it.

**Comment by mojaveazure** [comment]
{glmGamPoi} has been added to the `satijalab/seurat:latest`, `satijalab/seurat:4.1.0`, and `satijalab/seurat:develop` Docker images
