### ISSUE TITLE
Error during merge call with Seurat objects

### ISSUE THREAD

**Issue by BobvanSchendel** [satijalab/seurat#5642]
I have a big Seurat object composed of multiple integrated datasets of scRNAseq data.
For marking some specific subsets I uset SplitObject to split it into pieces (split per source dataset).
I want to merge the datasets back together with a call to 'merge':
`complete_data_labeled_part = merge(x=complete_data_labeled[1], y=complete_data_labeled[2])`
This give me the following error:
`Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class 'structure("Seurat", package = "SeuratObject")' to a data.frame`
I've seen some similar issues on here referring to the version of the Seurat objects being V2 instead of V3 but I'm running Seurat V4 so I don't understand how this an be an issue for me.

packageVersion('Seurat') returns 4.1.0

Running UpdateSeuratObject doesn't remove the error and give me the message 'Object representation is consistent with the most current Seurat version' so that seems to not be the problem.

I also tried using the MergeSeurat function just to see what happened and it gave me the expected error: 'Could not find function "MergeSeurat"'

I'm not really sure how to approach this, am I missing something simple?

**Comment by timoast** [comment]
Did you load the Seurat package? Can you include the full code?

**Comment by BobvanSchendel** [comment]
Yes. I use pretty much this:
`install.packages('Seurat')
library(Seurat)`

There's a lot of superfluous code in my script right now but I will share the relevant parts:
```# other installs and imports
install.packages('Seurat')
library(Seurat)
complete_data_labeled = LoadH5Seurat(paste(data_directory, 'complete_integrated_labeled.h5Seurat', sep='')) \
complete_data_labeled = perform_clustering(complete_data_labeled, default_dimensionality, default_clustering_resolution)
complete_data_labeled = SplitObject(complete_data_labeled, split.by = 'source')
complete_data_labeled = lapply(complete_data_labeled, FUN=add_stage_name)
complete_data_labeled = lapply(complete_data_labeled, FUN=UpdateSeuratObject)
complete_data_labeled_part = merge(x=complete_data_labeled[1], y=complete_data_labeled[2])
```

Here 'perform_clustering' and 'add_stage_name' are my own functions but commenting them out does not fix the issue.

**Comment by timoast** [comment]
Maybe try: 

```r
complete_data_labeled_part = merge(x=complete_data_labeled[[1]], y=complete_data_labeled[[2]])
```

**Comment by BobvanSchendel** [comment]
Well, that seems to work. I could have sworn I used double brackets before but alas.
Thanks for the speedy responses!
