### ISSUE TITLE
Delete data with NA gene

### ISSUE THREAD

**Issue by chentongouc** [satijalab/seurat#5643]
Many genes in my counts data are named Na, which is because the genome annotation file is not perfect. I'm hesitant to delete these data. If deleted, I'm afraid to miss some special genes that have not been annotated
If I want to delete it, how to do?
Thank you very much.

**Comment by samuel-marsh** [comment]
Hi,

not member of dev team but hopefully can be helpful.  I think this is not so much a Seurat related question as it is a bioinformatics question that is due to the aligner used and the annotation of your organism of study.  I would suggest posting to a more general bioinformatics focused forum like biostars might be more helpful for this specific question.

Best,
Sam

**Comment by chentongouc** [comment]
I sincerely thank you for your reply. What command should I use if I want to delete these data?

**Comment by samuel-marsh** [comment]
Hi,

There are many ways to filter dataframe or matrix in R.  The tidyverse way with dataframe would be using `filter()`.  You can find many stackexchange posts and other resources for more details on how to filter data in R.

Best,
Sam

**Comment by chentongouc** [comment]
Thank you very much,It's very kind of you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "satijalab/seurat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [satijalab/seurat] Delete data with NA gene (Issue #5643)





 
Hi,
 
There are many ways to filter dataframe or matrix in R.  The tidyverse way with dataframe would be using filter().  You can find many stackexchange posts and other resources for more details on how to filter data in R.
 
Best,
 Sam
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
