### ISSUE TITLE
Can't download dataset 

### ISSUE THREAD

**Issue by SynatKeam** [satijalab/seurat#5644]
Dear All, 

I am now in multimodal data analysis and I am wondering whether anyone has experienced not being able to download the dataset. 

![Multinomial dataset](https://user-images.githubusercontent.com/86950372/154786087-211d09c8-764d-4d6a-9f3c-f26dfeeff1a1.JPG)

I have attempted a few times, but has not been directed to the link. have a good day!

Kind regards,

synat

**Comment by mhkowalski** [comment]
Hi, 

They seemed to work for me. Can you try copying and pasting these links into your internet browser? Note that this will download the files, not redirect you to a webpage. 

ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE100nnn/GSE100866/suppl/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv.gz

ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE100nnn/GSE100866/suppl/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv.gz
