### ISSUE TITLE
Error 1 compilation failed for "RcppTOML" when install.packages("Seurat") is run

### ISSUE THREAD

**Issue by yechoi942** [satijalab/seurat#5650]
Hi,
I'm trying to install Seurat on my R version 4.0.2.
When I run the command `install.packages("Seurat")`, I get the following error messages:

```
make: *** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’
* removing ‘/z/yechoi/R/x86_64-pc-linux-gnu-library/4.0/RcppTOML’
ERROR: dependency ‘RcppTOML’ is not available for package ‘reticulate’
* removing ‘/z/yechoi/R/x86_64-pc-linux-gnu-library/4.0/reticulate’
ERROR: dependency ‘reticulate’ is not available for package ‘leiden’
* removing ‘/z/yechoi/R/x86_64-pc-linux-gnu-library/4.0/leiden’
ERROR: dependencies ‘leiden’, ‘reticulate’ are not available for package ‘Seurat’
* removing ‘/z/yechoi/R/x86_64-pc-linux-gnu-library/4.0/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpHb0Eca/downloaded_packages’
Warning messages:
1: In install.packages("Seurat") :
  installation of package ‘RcppTOML’ had non-zero exit status
2: In install.packages("Seurat") :
  installation of package ‘reticulate’ had non-zero exit status
3: In install.packages("Seurat") :
  installation of package ‘leiden’ had non-zero exit status
4: In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status
```

I've tried running `install.packages("RcppTOML")` but the following message pops up:

 ```
                                                                ^
make: *** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’
* removing ‘/z/yechoi/R/x86_64-pc-linux-gnu-library/4.0/RcppTOML’

The downloaded source packages are in
	‘/tmp/RtmpHb0Eca/downloaded_packages’
Warning message:
In install.packages("RcppTOML") :
  installation of package ‘RcppTOML’ had non-zero exit status
```

As I am not coding-savvy, I need some help in understanding what's happening and how to resolve this issue.

Thanks,
Yehyun

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  As this issue appears to be with RcppTOML and not Seurat I would suggest posting issue in repository for that package and hopefully maintainers can help you resolve the issue.

Best,
Sam

**Comment by ladyjkalx** [comment]
I'm also having the same issue with R 4.1.2.

Thanks,
Robin

**Comment by yechoi942** [comment]
It turns out that my OS (Redhat 7) was not compatible with the newest devtoolsets any more.
My issue has been resolved with following instructions here: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/
Hopefully your issue can be resolved with this as well.

Regards,
Yehyun

**Comment by yxj17173** [comment]
try to install reticulate_1.4, skip RcppTOML

**Comment by saketkc** [comment]
You can try starting a fresh R session with Rcpp not loaded and update RcppTOML as suggested in this [answer](https://stackoverflow.com/a/70991515).

**Comment by NateByers** [comment]
How was this closed/resolved? I have the same issue. No amount of updating of Rcpp or RcppTOML is helping me.

**Comment by nadavrap** [comment]
> try to install reticulate_1.4, skip RcppTOML
@yxj17173, there is no such version of reticulate. The latest is 1.26 (https://github.com/rstudio/reticulate/releases).

**Comment by george-hall-ucl** [comment]
> > try to install reticulate_1.4, skip RcppTOML

> @yxj17173, there is no such version of reticulate. The latest is 1.26 (https://github.com/rstudio/reticulate/releases).

There is such a version (although I don't know why it isn't tagged on GitHub). These are all the versions on CRAN: https://cran.r-project.org/src/contrib/Archive/reticulate/.

It can be installed from there with:
`install.packages("https://cran.r-project.org/src/contrib/Archive/reticulate/reticulate_1.4.tar.gz", repos=NULL, type="source")`.
