### ISSUE TITLE
Steps to do for a UMAP plot but with a subset of features

### ISSUE THREAD

**Issue by SHADJIA** [satijalab/seurat#5652]
Hello,

I work with your package to analyse scRNA seq datas. I'm trying to find the minimum number of gene markers needed to define subsets of Treg cells. I tried a tool in Python and found a certain number of genes. To check wether I get the same clusters, I did a subset of the initial SeuratObject by specifiying the identified genes as features. Then, I performed "FindNeighbors", "FindClusters" and "RunUMAP". Typically, I find the same plot between the one with 2000 HVGs and the one with 50 genes identified. 

The steps are they correct? I didn't run PCA as the dimension is already reduced. But, I don't know which dims to use for the FindNeighbors and RunUMAP steps. 

Thank you in advance

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  To be able to evaluate things you should post the full code you are running.

However, one thing right off the bat is that you do need to re-run PCA.  By default Seurat will use the variable features for PCA.  However, if you are reducing the variable features without re-running PCA then it’s not using correct variable features which is then what subsequent steps FindNeighbors, FindClusters, and RunUMAP are iteratively based on.

Best,
Sam

**Comment by SHADJIA** [comment]
Hello Samuel-Marsh,

Thanks first of all for your quick reply. 

As I said, I don't want to use variable features choosen by seurat for my downstream analysis. I want to use my "customized genes list". The number of features used is little (50 rather than 2000 HVG) so when I run PCA, I get warning messages:
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  did not converge--results might be invalid!; try increasing work or maxit.

My logic is PCA is used to reduce the dimension but with my minimal number of genes the dimension is already reduced. Therefore, I don't rerun PCA and proceed to FindNeighbors, etc.  

Am I correct?

Regards,
Sha

**Comment by samuel-marsh** [comment]
Hi Sha,

Could you please provide the full code that you are running?

Thanks!
Sam

**Comment by SHADJIA** [comment]
exptreg_seurat <- readRDS("exp_treg_seurat.rds") #complete Seurat object

treg_markers <- FindAllMarkers(exptreg_seurat)

#NSForest 2.0

data_exptreg_nsf2.0 <- read.csv("NSForest_v2_topResults.csv", header =T, sep = ",")
stacked_data_exptreg_nsf2.0 <- cbind(data_exptreg_nsf2.0[5], stack(data_exptreg_nsf2.0[6:11]))
stacked_data_exptreg_nsf2.0 <- subset(stacked_data_exptreg_nsf2.0, stacked_data_exptreg_nsf2.0$values != "nan" & stacked_data_exptreg_nsf2.0$values != "NaN")
minimum_marker_exptreg_nsfv2 <- unique(stacked_data_exptreg_nsf2.0$values)
minimum_marker_exptreg_nsfv2 <- gsub("_", ".", minimum_marker_exptreg_nsfv2)# minimum gene marker identified by NSF (50)

nsfv2_exptreg <- subset(exptreg_seurat, features = minimum_marker_exptreg_nsfv2)
nsfv2_exptreg <- FindNeighbors(nsfv2_exptreg, dims = 1:30, verbose = F)#dims of complete Seurat object used
nsfv2_exptreg <- FindClusters(nsfv2_exptreg, resolution = 1.2, verbose = F)
nsfv2_exptreg <- RunUMAP(nsfv2_exptreg, dims = 1:30, verbose = F)

Idents(nsfv2_exptreg) <- nsfv2_exptreg@meta.data$seurat_clusters
Idents(exptreg_seurat) <- exptreg_seurat@meta.data$seurat_clusters
DimPlot(nsfv2_exptreg, reduction = "umap", label =  T, repel = T)|DimPlot(exptreg_seurat, reduction = "umap", label =  T, repel = T)

**Comment by SHADJIA** [comment]
> exptreg_seurat <- readRDS("exp_treg_seurat.rds") #complete Seurat object
> 
> treg_markers <- FindAllMarkers(exptreg_seurat)
> 
> #NSForest 2.0
> 
> data_exptreg_nsf2.0 <- read.csv("NSForest_v2_topResults.csv", header =T, sep = ",") stacked_data_exptreg_nsf2.0 <- cbind(data_exptreg_nsf2.0[5], stack(data_exptreg_nsf2.0[6:11])) stacked_data_exptreg_nsf2.0 <- subset(stacked_data_exptreg_nsf2.0, stacked_data_exptreg_nsf2.0$values != "nan" & stacked_data_exptreg_nsf2.0$values != "NaN") minimum_marker_exptreg_nsfv2 <- unique(stacked_data_exptreg_nsf2.0$values) minimum_marker_exptreg_nsfv2 <- gsub("_", ".", minimum_marker_exptreg_nsfv2)# minimum gene marker identified by NSF (50)
> 
> nsfv2_exptreg <- subset(exptreg_seurat, features = minimum_marker_exptreg_nsfv2) nsfv2_exptreg <- FindNeighbors(nsfv2_exptreg, dims = 1:30, verbose = F)#dims of complete Seurat object used nsfv2_exptreg <- FindClusters(nsfv2_exptreg, resolution = 1.2, verbose = F) nsfv2_exptreg <- RunUMAP(nsfv2_exptreg, dims = 1:30, verbose = F)
> 
> Idents(nsfv2_exptreg) <- [nsfv2_exptreg@meta.data](mailto:nsfv2_exptreg@meta.data)$seurat_clusters Idents(exptreg_seurat) <- [exptreg_seurat@meta.data](mailto:exptreg_seurat@meta.data)$seurat_clusters DimPlot(nsfv2_exptreg, reduction = "umap", label = T, repel = T)|DimPlot(exptreg_seurat, reduction = "umap", label = T, repel = T)

Here the code.

Thank you
Sha

**Comment by samuel-marsh** [comment]
Ok so I think there are a couple issues.

For one with the way you are subsetting you are removing all of the genes except those 50.  Is that what you intend to do?  Or do you want to keep all of the genes in the object but only use those 50 genes for the dim reduc and clustering steps?

If want to keep all of the genes but only use a subset of the genes for the dim reduc and clustering then one way to do it would be following:
```
# Create new of object
nsfv2_exptreg <- exptreg_seurat

# Change the variable features to only be the 50 genes of interest
VariableFeatures(nsfv2_exptreg) <- minimum_marker_exptreg_nsfv2

# Now proceed with next steps
```


Regardless of whether you are removing all but 50 genes or keep all genes but manually setting variable features you need to re-run certain steps because of how they build off each other based on their function defaults and how they are built using variable features in the first place (again unless defaults are altered).  These steps are:
```
# Re-run ScaleData and PCA as by default they will use the features from the variable features slot.  This is why not re-running these is problematic after subsetting the data or changing the variable features.
nsfv2_exptreg <- ScaleData(nsfv2_exptreg)
nsfv2_exptreg <- RunPCA(nsfv2_exptreg)

# Re-run FindCluster, FindNeighbors, RunUMAP
dims_use <- 1:XX
nsfv2_exptreg <- FindNeighbors(nsfv2_exptreg, dims = dims_use)
nsfv2_exptreg <- FindClusters(nsfv2_exptreg, resolution = X.XX)
nsfv2_exptreg <- RunUMAP(nsfv2_exptreg, dims = dims_use)
```

I would also suggest that you probably need to run the last 3 steps of FindNeighbors, FindClusters, RunUMAP iteratively over at least a variety of dims and variety resolutions and combinations of the two as changing those could significantly alter the results (there are many other parameters you could also adjust as well, see function documentation).

Best,
Sam

**Comment by SHADJIA** [comment]
Hello Sam,

First, sorry for the late reply. I tried today your suggestion. I still get a warning message for the step RunPCA but with the dimensions and the resolution set at the lowest level, I get a comparable UMAP.
Thank you very much for your advice.

Regards,
Sha
