### ISSUE TITLE
new user, can't execute library(Seurat) without colorspace error

### ISSUE THREAD

**Issue by PaulKingsley** [satijalab/seurat#5653]
First time using RStudio, R, and trying to use https://satijalab.org/seurat/articles/pbmc3k_tutorial.html
Initial instructions are 
library(dplyr)
library(Seurat)
library(patchwork)

Successfully did install.packages for each. Successfully did library(dplyr). But library(Seurat) repeatedly fails with this error. 

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘colorspace’

When I try to install.packages("colorspace") I get an error at the end

* installing *source* package ‘colorspace’ ...
** package ‘colorspace’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
ERROR: compilation failed for package ‘colorspace’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/colorspace’
Warning in install.packages :
  installation of package ‘colorspace’ had non-zero exit status

library(Seurat) continues to fail.

How to solve? Thank you, Paul Kingsley

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This isn't an error with Seurat really but general one for many packages in R that in this case is erroring with the colorspace package.  You need to make sure that you have Xcode command line tools installed.  See basic install instructions here: https://mac.install.guide/commandlinetools/4.html

If you continue to have issues I suggest posting on more general R forum (i.e. stackexchange, etc) for help with installation and compilation issues.

Best,
Sam

**Comment by PaulKingsley** [comment]
Thank you!
I’ll look into that.

PDK Mobile

On Feb 23, 2022, at 12:34 PM, Samuel Marsh ***@***.***> wrote:

﻿

Hi,

Not member of dev team but hopefully can be helpful. This isn't an error with Seurat really but general one for many packages in R that in this case is erroring with the colorspace package. You need to make sure that you have Xcode command line tools installed. See basic install instructions here: https://mac.install.guide/commandlinetools/4.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__mac.install.guide_commandlinetools_4.html&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=nVe2aC0WyZ6Z1ONnzjKqA5yB2eB1NsRkPiEz-DowB4s&m=wnun7mm0gSHnuEh51FC67sJfcHkq5FB72lxIUHSiS-o&s=LRR5mlibrpdVJSwYUR2kLZcKwSaabhljIGmNhmMxQCI&e=>

If you continue to have issues I suggest posting on more general R forum (i.e. stackexchange, etc) for help with installation and compilation issues.

Best,
Sam

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_satijalab_seurat_issues_5653-23issuecomment-2D1049033681&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=nVe2aC0WyZ6Z1ONnzjKqA5yB2eB1NsRkPiEz-DowB4s&m=wnun7mm0gSHnuEh51FC67sJfcHkq5FB72lxIUHSiS-o&s=PtETgXL28-ibJqyEYxrNumYHwr6zjlSkjepWTEvhZw0&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX5IQUALH6CUXPIHEFUKEZDU4ULBFANCNFSM5PE6H5NA&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=nVe2aC0WyZ6Z1ONnzjKqA5yB2eB1NsRkPiEz-DowB4s&m=wnun7mm0gSHnuEh51FC67sJfcHkq5FB72lxIUHSiS-o&s=csB4bm5Wx977QUw1XU3Ikn_ZqJCO2JNkA0bA51KddKU&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=nVe2aC0WyZ6Z1ONnzjKqA5yB2eB1NsRkPiEz-DowB4s&m=wnun7mm0gSHnuEh51FC67sJfcHkq5FB72lxIUHSiS-o&s=wF9MA0jYpC79C8Yewyn4rWn7B9W_f1urhX5ZdBIGWIA&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=nVe2aC0WyZ6Z1ONnzjKqA5yB2eB1NsRkPiEz-DowB4s&m=wnun7mm0gSHnuEh51FC67sJfcHkq5FB72lxIUHSiS-o&s=p_MxYrtS_MdCUFSFDgcQOScvEBpU-Ung_qHDOegNzAU&e=>.
