### ISSUE TITLE
"batch_var" in SCTransform and Harmony

### ISSUE THREAD

**Issue by z5ouyang** [satijalab/seurat#5655]
@saketkc
I was using your proposed procedure between SCTransform and Harmony blow. And worked OK for integrating layout (UMAP/tSNE). However the sequence depths among samples are not justified due to applying SCTransform on each individual sample independently. Thus, the violin plot on adjusted UMI shows sample separation.
What's your thought on applying SCTransform on all of them but provide "batch_var" which is a new option in sctransform 0.3.3.

Thanks in advance.

#4896

You can use SCTransform and Harmony in this way (alternate approaches are also possible):
```{r}
data("pbmcsca")

pbmcsca.list <- SplitObject(pbmcsca, split.by="Method")
pbmcsca.list <- lapply(X = pbmcsca.list, 
                       FUN = SCTransform, 
                       method = "glmGamPoi", 
                       return.only.var.genes = FALSE)
var.features <- SelectIntegrationFeatures(object.list = pbmcsca.list, nfeatures = 3000)

pbmcsca.sct <- merge(x = pbmcsca.list[[1]], y = pbmcsca.list[2:length(pbmcsca.list)], merge.data=TRUE)
VariableFeatures(pbmcsca.sct) <- var.features
pbmcsca.sct <- RunPCA(pbmcsca.sct, verbose = FALSE)
pbmcsca.sct <- RunHarmony(pbmcsca.sct, assay.use="SCT", group.by.vars = "Method")
pbmcsca.sct <- RunUMAP(pbmcsca.sct, reduction = "harmony", dims = 1:30)
pbmcsca.sct <- FindNeighbors(pbmcsca.sct, reduction = "harmony", dims = 1:30) %>% FindClusters()
DimPlot(pbmcsca.sct, group.by = c("Method", "ident", "CellType"), ncol = 3)
```
![image](https://user-images.githubusercontent.com/682153/128538800-a988c345-2747-4b1b-a480-0dc5bf18c170.png)
in fact if you compare this with standard log normalization approach, you would notice that the NK cells cluster separate a bit more distinctively using this approach.

_Originally posted by @saketkc in https://github.com/satijalab/seurat/issues/4896#issuecomment-894360415_

**Comment by saketkc** [comment]
In v2, when merging datasets across sequencing depths, we perform correction using minimum of the median sequencing depths. The corrected counts (post `PrepSCTFindMarkers`) can then be used for visualization as we show in this [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html).
