### ISSUE TITLE
help with UMAP on ADT

### ISSUE THREAD

**Issue by carlosaya2** [satijalab/seurat#5656]
Hi,  

I would like to perform UMAP on ADT alone. 

I run PCA first with the following code:

```
DS06combinedfiltered <- RunPCA(DS06combinedfiltered, features = rownames(DS06combinedfiltered), reduction.name = "pca_adt", reduction.key = "pca_adt_", 
               verbose = FALSE)
```

then I tried to do the umap using the following code:

```
DS06combinedfiltered <- RunUMAP(DS06combinedfiltered, assay = "ADT", dims= (1:20), reduction = "pca_adt", reduction.key = "adtUMAP_", slot = "data") %>% FindNeighbors() %>% FindClusters()
```
but it prompts with the following error

09:51:14 Optimization finished
Computing nearest neighbor graph
Computing SNN
Error in FindClusters.Seurat(.) : 
  Provided graph.name not present in Seurat object

I checked the Seurat object but the only graph names are SCT.snn and SCT.nn, which are derived from the RNA assay.  

I will highly appreciate your help 

Cheers

Carlos

**Comment by mhkowalski** [comment]
Before running these steps, change the default assay to "ADT" by running
`DefaultAssay(DS06combinedfiltered) <- "ADT"`

 This will ensure that you are using the ADT assay in each step. You can refer to this [vignette](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html) if you need more assistance.
