### ISSUE TITLE
Plotting tSNE graphs in subsets of data side-by-side

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#566]
Hello,

I performed `multiCCA` analysis and aligned 4 separate 10x data files. After finding clusters, I'd like to show tSNE plots of 4 subsets side by side while keeping the coloring consistent. This is to visually appreciate the changes in overall clusters between conditions. What I'm trying to achieve is much like `facet_wrap` function of `ggplot2` package, I think. Is there a way of doing this via `TSNEPlot` function?

**Comment by andrewwbutler** [comment]
Hi, 

You can return the ggplot objects from `TSNEPlot` by passing the `do.return` argument as `TRUE`. These can then be combined in whatever manner you want. As an example:
```R
p1 <- TSNEPlot(object = subset1, do.return = TRUE)
p2 <- TSNEPlot(object = subset2, do.return = TRUE)
cowplot::plot_grid(p1, p2)
```

**Comment by atakanekiz** [comment]
I see. Can you please let me know how I can divide the aggregated Seurat object to subsets to use in this way?

**Comment by andrewwbutler** [comment]
You can either use the `SubsetData` function if you want separate objects or you can pass subsets of cell names to `TSNEPlot` itself via the `cells.use` parameter.

**Comment by atakanekiz** [comment]
Worked beautifully, thanks! For other users who might have a similar question, I'm sharing my code below:

```
young_wt_tsne <- TSNEPlot(combined, do.label = F, cells.use = grep("young_wt", combined@cell.names, value = T),
                        pt.size = 0.4, plot.title = " Young (wt)", no.legend = T, do.return = T)
aged_wt_tsne <- TSNEPlot(combined, do.label = F, cells.use = grep("aged_wt", combined@cell.names, value = T),
                         pt.size = 0.4, plot.title = " Aged (wt)", no.legend = T,do.return = T)




pdf("tsne_comparison.pdf")
cowplot::plot_grid(young_wt_tsne, aged_wt_tsne)
dev.off()

```
