### ISSUE TITLE
Same value of blacklist_ratio.

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#5661]
Why do I get this message? What could be the reason that all cells have the same value of blacklist_ratio?

Warning message:
In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :
  All cells have the same value of blacklist_ratio.

**Comment by torkencz** [comment]
Hi. Based on what I can see the feature you are trying to plot (blacklist_ratio) has all of the same values. You can check that in your metadata. It could be that you have no overlapping features with blacklisted regions, but I cannot be sure without seeing the data. Can reopen if necessary.
