### ISSUE TITLE
error in running FindVariableGenes

### ISSUE THREAD

**Issue by hongyeting** [satijalab/seurat#5665]
similar error in [Error in seq.int(rx[1L], rx[2L], length.out = nb) : 'to' must be a finite number #1090] but not exactly same with mine

error occurs there:
ovary <- FindVariableGenes(object = ovary,
                           mean.function = ExpMean, 
                           dispersion.function = LogVMR, 
                           x.low.cutoff = 0.1, 
                           x.high.cutoff = 5, 
                           y.cutoff = 0.4)

I get this:
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in seq.int(rx[1L], rx[2L], length.out = nb) : 
  'to' must be a finite number
Calls: FindVariableGenes -> cut -> cut.default
Execution halted

It's strange because I am repeating the result of other paper, using nearly the same code. I really can't find out where the problem is.
Please help me solve this!

**Comment by yuhanH** [comment]
Hi 
It seems you used previous version of Seurat. 
In the current version, `FindVariableGenes` is changed to `FindVariableFeatures()`.  You may need to find what exact Seurat version that the paper used and re-run the scripts.
