### ISSUE TITLE
Batch correcting additional datasets onto existing seurat object.

### ISSUE THREAD

**Issue by MiTPenguin** [satijalab/seurat#5672]
Hello, I am working on a set of immune cell data, generated using droplet-based protocol. Previously, I followed the SCT + CCA batch correction vignette, and got a pretty well corrected data set, where known phenotypes are pretty well separated, but there aren't too many sample-specific clusters. Seems like an okay trade-off between preserving interesting biology and removing batch effects.

So this resulting seurat object has an "integrated" assay (also an RNA and an SCT assay) that's active by default. I have collected additional data that I want to integrate into this existing seurat object, but I'm not finding a lot of info on the correct way to do it. 

Re-integrate everything with CCA is going to take too much time and memory, so I was hoping to use the existing integrated seurat object as a reference, and apply rpca to integrate the new data onto it. 

I am unclear on the details of how to implement this, though. I assume I have to SCT + PCA process each of the new data set separately, and them in a list along with the already integrated seurat object. I assume, since I want to integrate onto the PCA space of an integrated dataset, I have to keep the active assay of the already integrated seurat object as "integrated," while other new datasets would have active assay of "SCT". Is this correct? Then do I still have to run PrepSCTIntegration? 

When I tried to do this, the resulting integrated object ends up with a bunch of NaN in the data slot, corresponding to the number of cells added in the new unintegrated dataset. The genes exist in all of the data sets that I'm using. 

Any help would be greatly appreciated!

**Comment by yuhanH** [comment]
Hi @MiTPenguin 
You can have a look at this [mapping vignette](https://satijalab.org/seurat/articles/integration_mapping.html). It shows the steps to map new query data to the integrated reference. 
You only need to add `normalization.method = 'SCT'` in `FindTransferAnchors`. You can also check this [PBMC mapping vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html) which uses SCTransform.
