### ISSUE TITLE
non model organisms do cell communication analysis

### ISSUE THREAD

**Issue by chentongouc** [satijalab/seurat#5674]
My research object is fish. Can I use cellphone for cell communication analysis or Transcription factor analysis? Thank you.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev tream but hopefully can be helpful.  This isn't actualy a Seurat-related question.  I would recommend posting on the repositories for those packages to get response from the authors.  As note though those packages are based on ligand receptor interactions that are based on data from a given species.  If your organism is not one of those with curated database to base analysis on the your results are dependent on how much homology there is between genes and conservation there is between signaling pathways.

Best,
Sam
