### ISSUE TITLE
Difficulties with "Expression by groups analysis"

### ISSUE THREAD

**Issue by Rashidul1990** [satijalab/seurat#5678]
Hi,

I have total 7 datasets ( "Donor1", "Donor2", "Donor3","Tumor1","Tumor2","Tumor3","Tumor4") and I want to perform analysis as follows:- 

1. All samples together
2. All donors (Donor1+Donor2+Donor3) vs All tumor (Tumor1+Tumor2+Tumor3+Tumor4)
3. All donors vs Tumor1
4. All donors vs Tumor2
5. All donors vs Tumor3
6. All donors vs Tumor4

So first of all,  I have merged my 7 samples as --

alldata.Merged <- merge(Donor1, y = c(Donor2, Donor3,Tumor2ECObj,Tumor4SEObj,Tumor12MIXObj,Tumor13SEObj), add.cell.ids = c("Donor1", "Donor2", "Donor3","Tumor1","Tumor2","Tumor3","Tumor4"))

and then I have performed all the required steps( e.g., QC, normalization, feature selection, etc..) and then in the Visualization step, I am facing difficulties in viewing expression by groups.

DimPlot(immune.combined, reduction = "umap", split.by = "orig.ident")
DimPlot(immune.combined, reduction = "umap", group.by = "orig.ident")

When I split by  "orig.ident" then I get output for all individual samples but could not find the way to perform analysis as follows-
Could anyone please suggest how should I split or group to get output as 

2. All donors (Donor1+Donor2+Donor3) vs All tumor (Tumor1+Tumor2+Tumor3+Tumor4)
3. All donors vs Tumor1
4. All donors vs Tumor2
5. All donors vs Tumor3
6. All donors vs Tumor4

Many thanks and best regards,
Rashidul

**Comment by mhkowalski** [comment]
Hi, 

You could make a metadata variable for each comparison you would like to do. For instance, to compare all donors vs all tumors, you could make a variable called `donor_status`, as follows.

```
immune.combined$donor_status <- NA
immune.combined$donor_status[immune.combined$orig.ident %in% c("Donor1", "Donor2", "Donor3")] <- "Donor"
immune.combined$donor_status[immune.combined$orig.ident %in% c("Tumor1","Tumor2","Tumor3","Tumor4")] <- "Tumor"
DimPlot(immune.combined, reduction = "umap", group.by = "donor_status")
```
(You will need to replace "Donor1", etc with whatever string corresponds to "Donor1" in the `orig.ident` variable.
