### ISSUE TITLE
MergeSeurat fails with 'undefined columns selected'

### ISSUE THREAD

**Issue by mebbert** [satijalab/seurat#568]
Hi,

I posted code a while back that I used to merge multiple samples (#432). `MergeSeurat` from that same code now fails (after updating to `2.3.2`) with the following error:

> Error in `[.data.frame`(object2@raw.data, , object2@cell.names) : undefined columns selected

Really appreciate your help.

**Comment by mebbert** [comment]
I was just looking into the `RenameCells` code. It looks like `RenameCells` returns the object (when merging) before setting `object@cell.names <- new.cell.names`

**Comment by andrewwbutler** [comment]
Sorry for the inconvenience. We're aware of this bug (#549) and have fixed it in the develop branch if you want to try that. Downgrading is also an option as you pointed out until we can push an update to CRAN.
