### ISSUE TITLE
Get count matrix from integrated Seurat object

### ISSUE THREAD

**Issue by SHADJIA** [satijalab/seurat#5686]
Hello Seurat admins and users,

I'm new to data analysis using Seurat. For my project, I have to figure out minimum number of genes to characterize cell subsets. For that, I apply different algorithms to choose a subset of features then try the clustering step using Seurat. For every algorithm, I need a gene count matrix by default. Now, I'm going to apply the algorithms on a integrated dataset. How can I get the count matrix from the integrated Seurat object? Usually, I extract it from the count slot after the QC analysis if I need raw data or from data slot for normalized one. 
Can I extract the same way from the integrated Seurat object?

Sorry if my question is redundant or "childish" and I thank you all for your help.

Regards,
Sha

**Comment by timoast** [comment]
We do not compute any integrated version of the count matrix, only the normalized data matrix

https://github.com/satijalab/seurat/issues/5454
https://github.com/satijalab/seurat/issues/2065
