### ISSUE TITLE
Differentially expressed genes of a cluster for each condition of integrated analysis?

### ISSUE THREAD

**Issue by sdavoudi1** [satijalab/seurat#569]
Hi,

I had a question regarding extracting the differentially expressed genes of a cluster for each of the conditions of an integrated analysis. For clarity, I'll give an example from the sample integrated analysis on the Seurat website (https://satijalab.org/seurat/immune_alignment.html).

How would I use the FindMarkers function (or any other function) if I wanted to know the differentially expressed genes of the "B cells" among the "Stimulated" condition. I _don't_ want to compare the B cells in the stimulated condition to the B cells in the control condition. Basically, after using the integrated analysis to cluster the stimulated and control cells, I want to assume the control cells don't exist, and I only care about the differentially expressed genes in the B cells compared to all the other cell types of the Stimulated condition. How do I tell the FindMarkers function to only focus on the "stimulated" group?

Thanks in advance for your help!

**Comment by atakanekiz** [comment]
I think somebody needs to double check my answer but I think you can use the following approaches:


1) Select the cells from the populations of interest (i.e. B cell cluster and the rest of the cells). You can use `WhichCells` function that looks something like this:

```
Stim_B_cells <- WhichCells(integrated_object, ident = "B cells",  subset.name = "cond", accept.value = "stim"

Stim_non_B_cells <- WhichCells(integrated_object, ident = grep("B cells", levels(integrated_object@ident), invert = TRUE, value = TRUE, subset.name = "cond", accept.value = "stim"

FindMarkers(integrated_object, ident.1 = Stim_B_Cells, ident.2 = Stim_non_B_cells)
```
Where the variable `cond` and its values `stim` and `unstim` are added as metadata during preprocessing steps.



2) Subset the `stimulated` Seurat object from after integrated analysis. Then copy the cluster identity information for the subsetted cells and run the `FindMarkers` function as follows:

```
FindMarkers(stim_object, ident.1 = "B cells")
```

The default value of `ident.2` is `NULL` which equates to comparing the `ident.1` with the rest of the cells.

**Comment by satijalab** [comment]
This is correct- we cover this at the end of the integrated vignette : https://satijalab.org/seurat/immune_alignment.html
