### ISSUE TITLE
Mito Ratio for Single Cell Analysis

### ISSUE THREAD

**Issue by Skrueger09** [satijalab/seurat#5693]
Hi,
I am trying to complete the quality control check on a public dataset.  I downloaded the files from NCBI Geo due to Read10x not working (getting an error that states "Expecting barcodes.tsv file" even though all three files are in the location.  
#Feature Counts with Seruat Read10x for Control Samples using GEO Accession https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE140816
mtxctl <- "GSE140816_CTL_matrix/GSE140816_CTL_matrix.mtx"
cellsctl <- "GSE140816_CTL_matrix/GSE140816_CTL_barcodes.tsv"
featuresctl <- "GSE140816_CTL_matrix/GSE140816_CTL_genes.tsv"
countsctl <- ReadMtx(mtx = mtxctl, cells = cellsctl, features = featuresctl, feature.column = 1)

#Feature Counts with Seruat Read10x for Experimental Samples using GEO Accession https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE140816
mtxexp <- "GSE140816_EXP_matrix/GSE140816_EXP_matrix.mtx"
cellsexp <- "GSE140816_EXP_matrix/GSE140816_EXP_barcodes.tsv"
featuresexp <- "GSE140816_EXP_matrix/GSE140816_EXP_genes.tsv"
countsexp <- ReadMtx(mtx = mtxexp, cells = cellsexp, features = featuresexp, feature.column = 1)

# Turn count matrix into a Seurat object Control (output is a Seurat object)
ctrl <- CreateSeuratObject(counts = countsctl, project = "Zhang", min.cells = 3, min.features = 200)
ctrl
# Turn count matrix into a Seurat object Experimental (output is a Seurat object)
exp <- CreateSeuratObject(counts = countsexp, project = "Zhang", min.cells = 3, min.features = 200)
exp
# Create a merged Seurat object
ctrl_new = AddMetaData(ctrl, "Control", col.name = "Replicate")
exp_new = AddMetaData(exp, "Experimental", col.name = "Replicate")
ctrl_new2 = AddMetaData(ctrl, "Control", col.name = "Condition")
exp_new2 = AddMetaData(exp, "Experimental", col.name = "Condition")

org.combined = merge(ctrl_new2, y = exp_new2,
                     add.cell.ids = c('Control', "Experimental"), project = "Zhang")

head(org.combined@meta.data)

My issue arises with the Mitoratio part.  I tried using 
org.combined$mitoRatio <- PercentageFeatureSet(object = org.combined, pattern = "^MT-")
org.combined$mitoRatio <- org.combined@meta.data$mitoRatio / 100

My read out is: 
<img width="590" alt="Screen Shot 2022-03-04 at 1 46 38 PM" src="https://user-images.githubusercontent.com/100965543/156831528-ae9aedca-37e5-4933-bd59-1e06809b0baf.png">

So I try calculating Mitoratio myself using the following: 
ah <- AnnotationHub()
ahDb <- query(ah, 
              pattern = c("Mus musculus", "EnsDb"), 
              ignore.case = TRUE)
# Check versions of databases available
ahDb %>% 
  mcols()

# Acquire the latest annotation files
id <- ahDb %>%
  mcols() %>%
  rownames() %>%
  tail(n = 1)
# Download the appropriate Ensembldb database
edb <- ah[[id]]

# Extract gene-level information from database
annotations <- genes(edb, 
                     return.type = "data.frame")

# Select annotations of interest
annotations <- annotations %>%
  dplyr::select(gene_id, gene_name, gene_biotype, seq_name, description, entrezid)

View(annotations) 

mt <- annotations %>%
  dplyr::filter(seq_name == "MT") %>%
  dplyr::pull(gene_name)
 
metadata$mtUMI <- Matrix::colSums(counts[which(rownames(counts) %in% mt),], na.rm = T)
metadata$mitoRatio <- metadata$mtUMI/metadata$nUMI

And I get the following read out:
<img width="670" alt="Screen Shot 2022-03-04 at 1 49 30 PM" src="https://user-images.githubusercontent.com/100965543/156831825-51da50b0-96d0-4284-b366-3c8081a2a4e0.png">

The code past this point is successful but the mitochondrial data reads as zero.  So I am wondering what I am doing wrong with the Seurat data or mitochondrial ratio.  Any help would be greatly appreciated.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  The issue both times is that you are using the human mitochondrial gene prefix (^MT-) but your data is from mice.  The mouse prefix regexp is (^mt-).  This code runs fine for me:

```
OBJ_NAME[["mitoRatio"]] <- PercentageFeatureSet(object = OBJ_NAME, pattern = "^mt-")
OBJ_NAME[["mitoRatio"]] <- OBJ_NAME@meta.data$mitoRatio / 100
```


Also as fyi the reason why you get the error of `Expecting barcodes.tsv` is because the files have a prefix and `Read10X` expects the file to have no prefix.  ReadMtx works well but as fyi another solution you can use for GEO files easily is using function `Read10X_GEO` from my scCustomize package (vignette [here](https://samuel-marsh.github.io/scCustomize/articles/Read_and_Write_Functions.html#import-10x-genomics-or-10x-styled-single-directory-with-file-prefixes)).  Allows for you to read all samples simultaneously and specify single file path.  Each item in the resulting list will be labeled with the file prefix.

```
# Will automatically detect and read in all sets of files within a folder and create list of sparse matrices
raw_list <- Read10X_GEO(data_dir = "~/path_to_files")

# Merge data and add cell ids
raw_merged <- Merge_Sparse_Data_All(matrix_list = raw_list, add_cell_ids = c('Control', "Experimental"))

# Create Seurat Object
OBJ_NAME <- CreateSeuratObject(counts = raw_merged, project = "Zhang", min.cells = 3, min.features = 200)
```

Best,
Sam

**Comment by torkencz** [comment]
Hi as @samuel-marsh said the issue is the capitalization of MT in human relative to mouse. If issue persists I can reopen.
