### ISSUE TITLE
Question for integration spatial data with single-cell data

### ISSUE THREAD

**Issue by Huimin721** [satijalab/seurat#5694]
Dear Team,

I 'm applying your integration pipeline to predict cell types within spots of spatial data. I first integrated several replicates of spatial data, then use a reference to perform the prediction with single-cell data. However, do the pipieline [FindTransferAnchors](https://satijalab.org/seurat/reference/FindTransferAnchors.html) and [TransferData](https://satijalab.org/seurat/reference/TransferData.html) use the original gene expression data or the integrated 2000 features data? Thanks so much.

**Comment by mhkowalski** [comment]
Hi, 

You should use  RNA (or SCT) to do use  `FindTransferAnchors` and `TransferData`, not the integrated data.
