### ISSUE TITLE
Error running FindBridgeTransferAnchors

### ISSUE THREAD

**Issue by ccruizm** [satijalab/seurat#5697]
Good day!

I have been testing the new bridge integration. I have a reference dataset (RNA), bridge (RNA+ADT), and CyTOF. I wanted to follow a similar approach as you showed in Fig. 5 of your latest manuscript (https://doi.org/10.1101/2022.02.24.481684). However, I have not succeeded as it seems it is only optimized for ATAC datasets for the moment. 

Initially, I had problems running `PrepareBridgeReference` since the default values are precisley to integrate ATAC data. I changed it to:
```
obj.rna.ext <- PrepareBridgeReference(reference = reference,
                                      bridge = obj.multi, 
                                      bridge.query.assay = 'ADT',
                                      reference.reduction = "pca",
                                      reference.dims = 1:50,
                                      normalization.method = "LogNormalize"
)
```
Using ADT in `bridge.query.assay` allows running the function.
```
Warning message:
“735 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 1265 features.”
Projecting cell embeddings

Finding neighborhoods

Finding anchors

	Found 41062 anchors

Warning message:
“`invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `inject()` instead.
This warning is displayed once per session.”
Finding integration vectors

Finding integration vector weights


Integrating dataset 2 with reference dataset

Finding integration vectors

Integrating data

Warning message:
“UNRELIABLE VALUE: One of the ‘future.apply’ iterations (‘future_lapply-1’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify 'future.seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use 'future.seed = NULL', or set option 'future.rng.onMisuse' to "ignore".”
Computing nearest neighbor graph

Computing SNN

Generating normalized laplacian graph

Performing eigendecomposition of the normalized laplacian graph

Smoothing peaks matrix

Performing eigendecomposition

Constructing Bridge-cells representation
```
 However, once I go to the next step, `FindBridgeTransferAnchors` I get the following error:
```
Warning message:
“Cannot add objects with duplicate keys (offending key: rna_), setting key to 'adt_'”
Finding Transfer anchors

Transform cells to bridge graph laplacian space

Warning message in FindBridgeAnchor(object.list = list(extended.reference@reference, :
“No weights stored between query and bridge obejcts.Please set store.weights to TRUE in MapQuery”
Constructing Bridge-cells representation

Error: Cannot find 'ref.slsi' in this Seurat object
Traceback:

1. FindBridgeTransferAnchors(extended.reference = obj.rna.ext, query = obj.cytof, 
 .     reduction = "pcaproject", dims = 1:50)
2. FindBridgeAnchor(object.list = list(extended.reference@reference, 
 .     query), bridge.object = extended.reference@bridge, object.reduction = c(reference.reduction, 
 .     paste0("ref.", bridge.query.reduction)), bridge.reduction = c(bridge.ref.reduction, 
 .     bridge.query.reduction), anchor.type = "Transfer", reference.bridge.stored = TRUE, 
 .     verbose = verbose)
3. BridgeCellsRepresentation(object.list = object.list[[query]], 
 .     bridge.object = bridge.object, object.reduction = object.reduction[[query]], 
 .     bridge.reduction = bridge.reduction[[query]], bridge.assay.name = bridge.assay.name, 
 .     laplacian.reduction = laplacian.reduction, laplacian.dims = laplacian.dims, 
 .     verbose = verbose)
4. Misc(object.list[[i]][[object.reduction[[i]]]], slot = "ref.dims")
5. object.list[[i]][[object.reduction[[i]]]]
6. `[[.Seurat`(object.list[[i]], object.reduction[[i]])
7. stop("Cannot find '", i, "' in this Seurat object", call. = FALSE)
```

Of course, I do not have a LSI dimension. I looked at the source code and it seems the bridge integration is only implemented on ATAC so far. How could I make it work for CyTOF as well, please?

Finally, I would also like to know whether I need to apply an additional normalization method for the CyTOF data. I used Arcsinh transformation to normalize the fcs files. I read in another thread that a normalization method using CLR could be utilized as employed for the ADT data (https://github.com/satijalab/seurat/issues/3751). What would be the correct way to perform the bridge integration with CITE-seq?

Thanks in advance!

**Comment by yuhanH** [comment]
Hi,
Bridge integration wrapper now implements the PCA projection which can be used for cytof mapping. Please install the latest `feat/dictionary` branch. 

Here is an example for CytoF-bridge-RNA integration. 
First, you need to make sure the matched proteins have the same name in CytoF and CITE-seq. 
Then get the shared proteins, `adt.feature` and set it as the variable features in the cite-seq and center it in the scale.data slot. Depending on your normalization method, you can set `scale` to TRUE or FALSE.

```
scale = FALSE
DefaultAssay(obj.multi) <- 'ADT'
adt.feature <- intersect(rownames(obj.multi[['ADT']]), rownames(obj.cytof ))
VariableFeatures(obj.multi) <-  adt.feature
obj.multi <- ScaleData(obj.multi, features = adt.feature, do.scale = scale)
```
Next, choose the number of dimensions in the RNA and protein projection. For the RNA projection, you need to set the reference reduction name in ` reference.reduction` in `PrepareBridgeReference`.  Supervised PCA for the ADT will be calculate inside `PrepareBridgeReference`.  Then anchors between RNA and Cytof are calculated.


```
dims.adt <- 1:20
dims.rna <- 1:30

ref.extend <- PrepareBridgeReference(reference = obj.rna,
                      normalization.method = 'LogNormalize',
                       bridge = obj.multi,
                       reference.reduction = 'integrated_dr', 
                       reference.dims = dims.rna,
                       bridge.query.assay = 'ADT',
                      supervised.reduction = 'spca',
                      bridge.query.features = adt.feature
                       )
 
anchor <- FindBridgeTransferAnchors(extended.reference = ref.extend,
                                    query = obj.cytof, 
                                    reduction = 'pcaproject',
                                    scale = scale, 
                                    dims = dims.adt)
```
Now that you can use `anchor` and RNA reference to transfer labels and project cytof cells to RNA umap by `MapQuery`.
```
obj.cytof <- MapQuery(anchorset = anchor, 
                      reference = obj.rna,
                      query = obj.cytof, 
                      refdata = list(l1 =  'celltype.l1',
                                     l2 = 'celltype.l2'),
                      reduction.model = 'umap'  )
```

**Comment by ccruizm** [comment]
Works like a charm! thank you very much!!! 

Last question, how could I perform the co-embedding of reference and query as shown in Fig 5C?

**Comment by yuhanH** [comment]
You can merge the object and merge the umap dimensional reduction. 
for example
```
reference$id <- 'reference'
query$id <- 'query'
refquery <-  merge(reference, query)
refquery[["umap"]] <- merge(reference[["umap"]], pbmc3k[["ref.umap"]])
DimPlot(refquery, group.by = 'id', shuffle = TRUE)
```

**Comment by yuhsinhsieh-josch** [comment]
Hi there,

I follow the vignette for bridge integration: https://satijalab.org/seurat/articles/bridge_integration_vignette.html using my ATAC dataset as query. 
 I encountered an error while running the FindBridgeTransferAnchors, 
```
bridge.anchor <- FindBridgeTransferAnchors(extended.reference = obj.rna.ext, 
                                           query = obj.atac,
                                           reduction = "lsiproject",
                                           dims = dims.atac)
```
the error is as following
```
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 1760 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in ValidateParams_IntegrateEmbeddings_TransferAnchors(anchorset = anchorset,  : 
  The set of cells used as a reference in the AnchorSet does not match the set of cells provided in the reference object.
```
Also replicate the same error with the 10x scATAC-seq ref query.
Similar error have been described here `Error with IntegrateEmbeddings` #619
but there is no clear solution.
I would appreciate any feedback! Thank you!

SessionInfo
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] EnsDb.Hsapiens.v86_2.99.0 ensembldb_2.18.4          AnnotationFilter_1.18.0  
 [4] GenomicFeatures_1.46.5    AnnotationDbi_1.56.2      Biobase_2.54.0           
 [7] GenomicRanges_1.46.1      GenomeInfoDb_1.30.1       IRanges_2.28.0           
[10] S4Vectors_0.32.4          BiocGenerics_0.40.0       MetBrewer_0.2.0          
[13] BuenColors_0.5.6          MASS_7.3-58.1             data.table_1.14.2        
[16] harmony_0.1.0             Rcpp_1.0.9                ggplot2_3.3.6            
[19] dplyr_1.0.10              SeuratDisk_0.0.0.9019     Signac_1.8.0.9000        
[22] sp_1.5-0                  SeuratObject_4.1.2        Seurat_4.1.1.9001        

```

**Comment by Maojie6509** [comment]
Hi,  I had problems running MapQuery,  "Error in MapQuery(anchorset = anchor, reference = obj.rna, query = obj.cytof,  : 
  The assay used to create the anchorset does not match anyof the assays in the reference object." .

**Comment by Maojie6509** [comment]
Hi, I had problems running MapQuery, 
"Error in MapQuery(anchorset = anchor, reference = obj.rna, query = obj.cytof, :
The assay used to create the anchorset does not match anyof the assays in the reference object."                                                      

Here is my code
 `
scale = FALSE
DefaultAssay(obj.multi) <- 'ADT'
adt.feature <- intersect(rownames(obj.multi[['ADT']]), rownames(obj.cytof ))
VariableFeatures(obj.multi) <-  adt.feature
obj.multi <- ScaleData(obj.multi, features = adt.feature, do.scale = scale)

dims.adt <- 1:5
dims.rna <- 1:10

ref.extend <- PrepareBridgeReference(reference = obj.rna,
                                     normalization.method = 'LogNormalize',
                                     bridge = obj.multi,
                                     #reference.reduction = 'integrated_dr', 
                                     reference.reduction = 'pca', 
                                     reference.dims = dims.rna,
                                     bridge.query.assay = 'ADT',
                                     supervised.reduction = 'spca',
                                     bridge.query.features = adt.feature
)

anchor <- FindBridgeTransferAnchors(extended.reference = ref.extend,
                                    query = obj.cytof, 
                                    reduction = 'pca',
                                    scale = scale, 
                                    dims = dims.adt)

obj.cytof <- MapQuery(anchorset = anchor, 
                      reference = obj.rna,
                      query = obj.cytof, 
                      refdata = list(l1 =  'seurat_clusters'),
                      reduction.model = 'umap'  )`

**Comment by leeanapeters** [comment]
Hi, I have the same issue as above with MapQuery. Is there a known solution?

Thanks!

**Comment by nicolasnunez83** [comment]
Dear Seurat team,

I'm working on integrating CyTOF and CITE-seq data using the bridge integration functionality in the Seurat package. I'm running into an issue with the PrepareBridgeReference function and was hoping you could provide some guidance.

The error I'm encountering is:

Error in match.arg(arg = value, choices = Assays(object = object)) : 
  'arg' should be one of "SCT", "ADT"

I've tried the following steps to resolve the issue:
1. Set the default assay of the obj.bridge Seurat object to "ADT" as discussed above. (Using "pbmc_multimodal_2023.rds”).
2. Create a new Seurat object that combines the obj.rna.ref (“SCT data from pbmc_multimodal_2023.rds and with a new dataset). 
3. Here some information:

> ref.extend <- PrepareBridgeReference(reference = obj.rna.ref,
+                                      normalization.method = 'LogNormalize',
+                                      bridge = obj.bridge,
+                                      reference.reduction = 'integrated_dr', 
+                                      reference.dims = dims.rna,
+                                      bridge.query.assay = 'ADT',
+                                      supervised.reduction = 'spca',
+                                      bridge.query.features = adt.feature
+ )
> obj.rna.ref
An object of class Seurat 
14875 features across 7355 samples within 1 assay 
Active assay: RNA (14875 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 3 dimensional reductions calculated: pca, umap, spca
> obj.bridge
An object of class Seurat 
20957 features across 161764 samples within 2 assays 
Active assay: ADT (228 features, 28 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: SCT
 6 dimensional reductions calculated: apca, aumap, pca, spca, umap, wnn.umap
> adt.feature
 [1] "CD39"    "TIGIT"   "CD4-1"   "CD3-1"   "CD27"    "CD25"    "CD45RA"  "CD56-1"  "CD45RO"  "CD11b-1" "CD38-1"  "CD152"   "CD206"  
[14] "IgD"     "CD127"   "CD279"   "CD278"   "CD274"   "CD95"    "CD16"    "CD14"    "CD19"    "CD8"     "HLA-DR"  "CD103"   "CD57"   
[27] "CD244"   "CD21"   

However, I'm still encountering the same error. I'm using the latest version of the Seurat package, but I wanted to check if there are any updates or fixes in that branch that could help resolve my problem.

Thank you in advance for your help. I'm looking forward to hearing from you.

Best regards,
Nicolás
