### ISSUE TITLE
Creating a New Object for a Subset of my MetaData

### ISSUE THREAD

**Issue by pcitrano3** [satijalab/seurat#5698]
Hello! I am still in the early stages of learning R and Seurat and have come across an issue using subset. Essentially, what I need to do is to create an object that contains only a subset of the cells in the dataset for standard Seurat processing and analysis. So far, I was able to identify the cells in my metadata: 

`# Adding Rbfox3 status to Metadata
> poscells <- WhichCells(cck, expression = Rbfox3 > 0)
> cck$RBFOX3_status <- ifelse(colnames(cck) %in% poscells, "RBFOX3_POS", "RBFOX3_NEG")
`

However, now I am stuck trying to create an object containing only the cells that are "RBFOX3_POS". Does anyone know how I can do this? I tried to play around with subset but I do not know how exactly I can subset out the cells I am interested in.

**Comment by Oakento** [comment]
Hi, sorry to reopen this thread.

I find that calling `subset` will only remove rows in meta.data but still keep respective rows in assays.

Use the case above, if `OBJ` has 10000 cells, then we will have `nrow(SUB_OBJ) = 10000` and `nrow(SUB_OBJ@meta.data) = 1234`

Wondering if there is a way to remove rows in the assays as well.
