### ISSUE TITLE
Issue with FindMarkers

### ISSUE THREAD

**Issue by eitanwin** [satijalab/seurat#57]
Hi,

I have a problem running FindMarkers to compare a single sample with a group of cells:

Error in apply(object@data[genes.use, cells.1], 1, function(x) return(length(x[x >  : 
  dim(X) must have a positive length

Can you assist?

**Comment by andrewwbutler** [comment]
Try updating to the latest version (1.4.0.13).

**Comment by andrewwbutler** [comment]
Closing for now. Please reopen if the issue persists in v2.0
