### ISSUE TITLE
RunHarmony warning "Invalid name supplied, making object name syntactically valid"

### ISSUE THREAD

**Issue by ashaked** [satijalab/seurat#5703]
Hello:
I'm following the example:
http://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/docs/SeuratV3.html

When running harmony:

options(repr.plot.height = 2.5, repr.plot.width = 6)
pbmc <- pbmc %>% 
    RunHarmony("stim", plot_convergence = TRUE)

I got the warnings:
"Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony"

However, there is no new object named "ProjectDim.RNA.harmony", and I can continue the rest of the commands without issue. How can I fix this?

Thank you!

**Comment by longmanz** [comment]
Hello @ashaked,
Could you please try running your codes without using pipes (`%>%`) in R? Does it still output a warning message?
Best,
Longda

**Comment by shabs24** [comment]
I am running into same issue after installing new version of R where all the warnings are converted into error.

Error: (converted from warning) Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity

Here is the code:
SeuratObject<- NormalizeData(SeuratObject, verbose = FALSE) 
SeuratObject<-FindVariableFeatures(SeuratObject, selection.method = "vst", nfeatures = 2000) 
SeuratObject<-ScaleData(SeuratObject, verbose = FALSE) 
SeuratObject<-RunPCA(SeuratObject, pc.genes = SeuratObject@var.genes, npcs = 50, verbose = FALSE)
SeuratObject<-RunHarmony(SeuratObject, "orig.ident", plot_convergence = TRUE)
SeuratObject<-FindNeighbors(SeuratObject, reduction = "harmony", dims = 1:20)
SeuratObject<-FindClusters(SeuratObject, resolution = 0.5) 
SeuratObject<- RunUMAP(SeuratObject, dims = 1:20)

I cannot run the FindNeighbors and FindClusters (as I am not able to run the command before)

Any suggestions?
