### ISSUE TITLE
Aligning canonical correlation vectors

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#5704]
Hi,

I am wondering how exactly the canonical correlation vectors are aligned after CCA is done during FindTransferAnchors()

Your publication "comprehensive integration of single cell data" says L2 normalization is applied to the embeddings. So basically rbind(svd$u, svd$v) is divided by the sqrt's of sum of squared columns

Your publication "Integrating single-cell transcriptomic data across different conditions, technologies, and species" a few years earlier goes way more in depth and involves using 'metagenes' and dynamic time warping to align the vectors (methods subsection: "alignment of two canonical correlation vectors").  This is not mentioned in the most recent paper.  

The source code looks like L2 normalization is applied.  What happened to the old method?  

I do not have a preference, I am just trying to understand how this works because I want to use CCA embeddings for a certain task

**Comment by schae211** [comment]
I haven't seen your issue, but I basically have the same question: https://github.com/satijalab/seurat/discussions/5712

**Comment by timoast** [comment]
> Your publication "Integrating single-cell transcriptomic data across different conditions, technologies, and species" a few years earlier goes way more in depth and involves using 'metagenes' and dynamic time warping to align the vectors (methods subsection: "alignment of two canonical correlation vectors"). This is not mentioned in the most recent paper.

It's not mentioned because those steps are not used in the Seurat v3 integration method.

The current Seurat integration method (used in the FindTransferAnchors and FindIntegrationAnchors functions) is described in Stuart & Butler et al. (2019), and uses CCA followed by L2 normalization to project a pair of dataset into a shared low dimension space, then finds pairs of mutual nearest neighbors in that space, as described in the methods for that paper.

**Comment by danielcgingerich** [comment]
@timoast why was the old method dropped?

**Comment by timoast** [comment]
@danielcgingerich you can see a comparison of the performance of the two methods in the Seurat v3 paper: https://doi.org/10.1016/j.cell.2019.05.031

**Comment by schae211** [comment]
Are you referring to the comparisons between Seurat v2 and Seurat v3, e.g. in Figure 2?

**Comment by timoast** [comment]
> Are you referring to the comparisons between Seurat v2 and Seurat v3, e.g. in Figure 2?

Yes
