### ISSUE TITLE
AverageExpression discrepancy

### ISSUE THREAD

**Issue by malosreet** [satijalab/seurat#571]
I think there is a discrepancy in the values returned by AverageExpression when using the "data" slot when there are some identities which contain only a single cell.  When there is a single cell for an identity, and the "data" slot is selected, the log normalized values are returned corresponding to that single cell. For all other identities (with more than one cell), the function uses mean(expm1(x)) which gives the non-log normalized averages. 

This is related to #193

**Comment by andrewwbutler** [comment]
Thanks for bringing this up! It's been addressed in #573 and should be fixed now on the develop branch ([install instructions](https://satijalab.org/seurat/devinstall.html)).
