### ISSUE TITLE
Failed to install 'Seurat' from GitHub

### ISSUE THREAD

**Issue by yh154** [satijalab/seurat#5713]
Dear Seurat developper, 

I am trying to install Seurat from github following the Analysis of Image-based Spatial Data in Seurat vignette. I got an error message seems related to SeuratObject version, but I can't find a SeuratObject with the required version. 

library(remotes)
remotes::install_github("satijalab/seurat", "feat/imaging", quiet = TRUE)
Error: Failed to install 'Seurat' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
E>   namespace ‘SeuratObject’ 4.0.4 is being loaded, but >= 4.0.999.9009 is required
E> Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
E> Execution halted
E> ERROR: lazy loading failed for package ‘Seurat’
E> * removing ‘/private/var/folders/l4/fzjpws9j71l8k7c5y_rcwx380000gq/T/RtmpEAtBlT/Rinst133b635132309/Seurat’
E>       -----------------------------------
E> ERROR: pack

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] remotes_2.2.0      SeuratObject_4.0.4 Seurat_4.1.0      

Thanks!
yh

**Comment by ajwilk** [comment]
Also experiencing this error

**Comment by ajwilk** [comment]
Dependency issue can be resolved by first installing the ```feat/imaging``` branch of `SeuratObject`: 
```remotes::install_github("mojaveazure/seurat-object", "feat/imaging", quiet = TRUE)```

**Comment by mojaveazure** [comment]
If you run `remotes::install_github("satijalab/seurat", ref = "feat/imaging", upgrade = TRUE)`, you will automatically get the correct version of SeuratObject installed
