### ISSUE TITLE
When using SCTransform v2, clusters conflict with canonical markers.

### ISSUE THREAD

**Issue by WuRAFY** [satijalab/seurat#5714]
Hi seurat team, firstly thanks for the splendid tool. 

But recently I ran into a confusing problem when using sctransfrom v2. This is the cluster result. 
![7 (M0T$XWJX~GW LE8LWG_V](https://user-images.githubusercontent.com/64182733/157466918-e6998b25-3931-41fd-9723-0be8177a441c.png)
The main problem is between cluster 0 (mostly epithelial cells) and cluster 1(mostly B cells). When dying cells with some canonical markers, it seems some epithelial cells are assigned to cluster 1 (B cell cluster).  The problematic part is circled. A tool "cellassign" which assign type to individual cell rather cluster also indicate the same problem.
![IQ}M65KI21@S%RYB63$K CP](https://user-images.githubusercontent.com/64182733/157467233-3d62ddcf-2028-4fca-8989-e38514169e11.png)
And higher cluster resolution does not help. This is the result of increasing the resolution to 0.8 from 0.5.
![图片2](https://user-images.githubusercontent.com/64182733/157468434-70421c3b-32db-47ae-a557-bc6b38b5095f.png)
But when using another workflow without sctransform (mostly pbmc guided tutorial but integrating datasets with harmony), such problem would not happen. Cells in figure below have been assigned to specific cell types. B cell and epithelial clusters separate pretty  well.
![}{_ UT_EO)FBJ33~8MT6Z%7](https://user-images.githubusercontent.com/64182733/157470147-dd942aaf-9be9-45a3-a6aa-beafca8c1c5c.png)
These results come from integrated analysis of 3 lung cancer samples. This is the code.
```
##This is the quality control part for single sample, doublets have been removed by doubletfinder
mat=Read10X(path)
seu_object=CreateSeuratObject(counts=mat,min.genes=200,project=sample)
seu_object[["percent.mt"]]=PercentageFeatureSet(seu_object,pattern="^MT-")
seu_object=subset(seu_object,subset=nFeature_RNA>200&percent.mt<20)
seu_object=SCTransform(seu_object, vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE) %>%
    RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE)
```
```
##This is the integrated analysis
features=SelectIntegrationFeatures(object.list = obj_list, nfeatures = 3000)
obj_list=PrepSCTIntegration(object.list = obj_list, anchor.features = features)
anchors=FindIntegrationAnchors(object.list = obj_list, normalization.method = "SCT",
    anchor.features = features)
combined_object=IntegrateData(anchorset = anchors, normalization.method = "SCT")
combined_object=RunPCA(combined_object,npcs=60,verbose = FALSE)
combined_object=RunUMAP(combined_object,reduction="pca",dims=1:60)
combined_object=FindNeighbors(combined_object,reduction="pca",dims=1:60)
combined_object=FindClusters(combined_object,resolution=0.5)
```
Are there any mistakes or settings to be changed?
Many thanks,
FY

**Comment by saketkc** [comment]
Hi @WuRAFY, would you be able to share the objects and the code to reproduce this with me? My email is schoudhary@nygenome.org

**Comment by WuRAFY** [comment]
> Hi @WuRAFY, would you be able to share the objects and the code to reproduce this with me? My email is [schoudhary@nygenome.org](mailto:schoudhary@nygenome.org)

Thank you for your reply, I will talk with the PI to see how much we can share with you.

**Comment by saketkc** [comment]
Thanks! You can also anonymize the gene names if you wish. Alternatively, does this also happen with LogNormalization + IntegrateData workflow?

**Comment by WuRAFY** [comment]
> Thanks! You can also anonymize the gene names if you wish. Alternatively, does this also happen with LogNormalization + IntegrateData workflow?

Due to time difference, I have to try lognormalize and reply later. Sorry for keeping you waiting.

**Comment by saketkc** [comment]
No worries, and no rush of course.

**Comment by WuRAFY** [comment]
> Thanks! You can also anonymize the gene names if you wish. Alternatively, does this also happen with LogNormalization + IntegrateData workflow?

![PK921G$TTRW()66`(5__51Y](https://user-images.githubusercontent.com/64182733/158032296-935c71f5-02d9-4f3a-869c-aeac26466841.png)
```
obj_list <- lapply(X = obj_list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
features <- SelectIntegrationFeatures(object.list = obj_list)
anchors <- FindIntegrationAnchors(object.list = obj_list, anchor.features = features)
combined_object <- IntegrateData(anchorset = anchors)
DefaultAssay(combined_object)="integrated"
combined_object=ScaleData(combined_object,verbose=FALSE)
combined_object=RunPCA(combined_object,npcs=61,verbose = FALSE)
combined_object <- RunUMAP(combined_object, reduction = "pca", dims = 1:61)
combined_object <- FindNeighbors(combined_object, reduction = "pca", dims = 1:61)
combined_object <- FindClusters(combined_object, resolution = 0.5)
```
This is the result and code of lognormalization workflow. The B cell cluster and epithelial do not mix. Later I will organize the code and data then send them to you.
Thank you for your patience.

**Comment by biliopo** [comment]
So what caused this weird problem? sctransform v2 caused this? I am so curious about this. @saketkc
