### ISSUE TITLE
Integrating data Error: Cannot add more or fewer cell meta.data information without values being named with cell names

### ISSUE THREAD

**Issue by aimanbarki** [satijalab/seurat#5715]
I am trying to integrate after using SCT transform and reciecing the following error: "Integrating data Error: Cannot add more or fewer cell meta.data information without values being named with cell names" 

.list <- SplitObject(merged_seurat_filtered, split.by = 'orig.ident') #normalization
for(i in 1:length(S.list)){
  S.list[[i]] <- SCTransform(object = S.list[[i]], verbose = TRUE)
  }
SCT_features <- SelectIntegrationFeatures(object.list = S.list, nfeatures = 3000)
S.list <- PrepSCTIntegration(object.list = S.list, anchor.features = SCT_features)
SCT_anchors <- FindIntegrationAnchors(object.list = S.list, normalization.method = "SCT" , anchor.features = SCT_features)
SCT_integrated <-IntegrateData(anchorset = SCT_anchors, normalization.method =  "SCT" )

**Comment by yuhanH** [comment]
Could you post all print out message from `FindIntegrationAnchors` and `IntegrateData`?
