### ISSUE TITLE
SetAllIdent() no longer reorders @ident factor levels

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#572]
Hi,

I reinstalled Seurat from the develop branch. Previously, SetAllIdent() automatically reorders the factor levels in @ident (e.g. "1", "2", "3"). Now it doesn't do the reordering anymore, so running the same DoHeatmap and DotPlot function after SetAllIdent gives different cluster ordering. I think it's due to this change: e4ca4452c1f901b5a41417737396c4ede2be1a47. `gdata::drop.levels(x, reorder=TRUE, ...)` does factor reordering by default.

**Comment by mojaveazure** [comment]
Thanks for catching! This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](http://satijalab.org/seurat/devinstall).

**Comment by satijalab** [comment]
Closing - fix should now be on CRAN
