### ISSUE TITLE
AddModuleScore for CITEseq data?

### ISSUE THREAD

**Issue by klgoss** [satijalab/seurat#5722]
Is it possible to run the AddModuleScore function using CITEseq data instead of gene expression data? For example... 

`DefaultAssay(obj) <- "ADT"
a <- list(c("CD45RAadt", "CD4adt", "CD25adt", "CD69adt"))
obj <- AddModuleScore(obj, features = a, name = "a", seed = 1)`

Running this gave me an error: 
`Error in sample.int(x, size, replace, prob) : cannot take a sample larger than the population when 'replace = FALSE'`

**Comment by timoast** [comment]
How many proteins did you measure with CITE-seq? The `AddModuleScore()` function needs a set of control features per expression bin, it's unlikely you have enough proteins quantified to run the function with the default parameter settings

**Comment by klgoss** [comment]
> How many proteins did you measure with CITE-seq? The `AddModuleScore()` function needs a set of control features per expression bin, it's unlikely you have enough proteins quantified to run the function with the default parameter settings

There are 28 proteins. I've adjusted the "ctrl" parameter and get "Error in ctrl.use[[i]] : subscript out of bounds".

**Comment by timoast** [comment]
The `nbin` parameter would also need to be reduced
