### ISSUE TITLE
Function documentation for image based spatial data are all 404

### ISSUE THREAD

**Issue by BAevermann** [satijalab/seurat#5723]
Hello, 
at https://satijalab.org/seurat/articles/spatial_vignette_2.html
The function documentation is 404. 
Click any of: 
[LoadVizgen()](https://satijalab.org/seurat/reference/ReadVizgen.html) 
[LoadNanostring](https://satijalab.org/seurat/reference/ReadNanostring.html)
[LoadAkoya](https://satijalab.org/seurat/reference/ReadAkoya.html)

**Comment by AustinHartman** [comment]
Hi Brian - thanks for pointing this out. This is because these functions only exist on the `feat/imaging` branch of seurat. Eventually this will be resolved once we merge these changes into the master branch but for now please use `?LoadVizgen` to view documentation.
