### ISSUE TITLE
What do the "x" and "i" variables represent in the counts slot of the RNA assay ?

### ISSUE THREAD

**Issue by berenice-dugue** [satijalab/seurat#5728]
Hello,

I'm sorry to disturb you but I can't seem to find information about what do the variables i and x from the counts slot of the RNA assay represent ? (in a Seurat Object)

I'm guessing that the "i" variable represent the number of ARN copies for each gene in each cell (as it's an integer) but what do the "x" represent ?

Many thanks for your help,

Bérénice

**Comment by saketkc** [comment]
They are not specific to Seurat and come from sparseMatrix format. You can read about them [here](https://www.rdocumentation.org/packages/Matrix/versions/1.4-0/topics/sparseMatrix).
