### ISSUE TITLE
More generalizable way of merging Seurat objects?

### ISSUE THREAD

**Issue by smk5g5** [satijalab/seurat#5729]
Hi,

I am writing a workflow where I read in the 10x directories and sample name information from the command line. I am stuck on how I can merge the objects programmatically. The usual way of merging objects is like this as given in the Seurat vignette.

`pbmc.big <- [merge](https://rdrr.io/r/base/merge.html)(pbm[c](https://rdrr.io/r/base/c.html)3k, y = [c](https://rdrr.io/r/base/c.html)(pbmc4k, pbmc8k), add.cell.ids = c("3K", "4K", "8K"), project = "PBMC15K")`

But I need to do it something like this :

`scrna_GEX <- merge(x=scrna_GEX.list[[1]],y=scrna_GEX.list[[2:length(sample_names)]],add.cell.ids = sample_names,project=project_name)`

Where sample_names contains the vector of sample names and scrna_GEX.list contains individual seurat objects from each list.

Obviously, the above code does not work and throws in an error which looks like this :

`Error in scrna_GEX.list[[2:length(sample_names)]] :
  recursive indexing failed at level 2
Calls: merge -> merge.Seurat`

**Comment by saketkc** [comment]
The second argument should be a list of objects (not [[..]]):

```r
scrna_GEX <- merge(x=scrna_GEX.list[[1]],  y=scrna_GEX.list[2:length(sample_names)], add.cell.ids = sample_names, project=project_name)
```

**Comment by smk5g5** [comment]
Ahh! my bad. Thank you for the prompt reply!
