### ISSUE TITLE
evaluation of clustering 

### ISSUE THREAD

**Issue by YuliaInn** [satijalab/seurat#5730]
I used two different methods for dimensionality reduction before Seurat clustering. Here are UMAP visualization plots for each of my pipelines. One is denser than another, but still, both pipelines clustered cells of the same type together. What is the best way to compare the results in this case?

![cellTypes_corEx_dimplot](https://user-images.githubusercontent.com/54861076/157951589-7e557b60-137c-43ac-bacf-c024dd94e1de.png)
![umap_cell_types](https://user-images.githubusercontent.com/54861076/157951629-45264b42-bdac-4cd5-98d6-11388ad542ab.png)

**Comment by torkencz** [comment]
I think generally best approach would be to calculate the n nearest neighbors in the two dimensionality reduction and then compare for the same cells.
