### ISSUE TITLE
How to rename metadata columns?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5732]
Hi there, 

What is the recommended way to rename the metadata columns of a Seurat object?

So far I do:

```
colnames(Seurat_obj@meta.data)[index.of.column] <- "new.name"
```

Thank you so much!

**Comment by jan-glx** [comment]
Apparently, copying to new name, then deleting the original column:  https://github.com/satijalab/seurat/issues/1479
