### ISSUE TITLE
Do we need "PrepSCTIntegration" before FindTransferAnchors in TransferData workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5733]
Hi there, 

I am following the tutorial for TransferData (https://satijalab.org/seurat/articles/integration_mapping.html) between a ref and query scRNA-seq. Both were SCTransform-ed separately. 

1. In the Integration tutorial, we needed to do PrepSCTIntegration() before doing FindIntegrationAnchors(). I understand we do not modify expression of the query in the TransferData workflow, but could anyone confirm whether we need to do something similar to PrepSCTIntegration() before doing FindTransferAnchors()?

2. In the FindTransferAnchors(), there is an argument for scale query data with default = TRUE. But I remember @saketkc said not to do ScaleData() for SCTransformed data. Should we set this to FALSE here?

Thank you very much for your help!

**Comment by yuhanH** [comment]
Hi @denvercal1234GitHub 
You are right.  Before `FindTransferAnchors`, you don't need to run `PrepSCTIntegration` which is specific designed for `FindIntegrationAnchors `
In `FindTransferAnchors`, when you set `normalization.method = SCT`, `scale` parameter input will be not considered.
