### ISSUE TITLE
Are markers differentiating among TransferData-ed clusters the same as markers that responsible for cell label transfer?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5734]
Hi there, 

I performed the TransferData workflow to transfer the cell type annotations from my ref scRNA-seq data onto the query data. I now aim to identify which genes that were responsible for the cell type label transfer for these annotations in the query data. 

1. If I perform FindAllMarkers of the query Seurat object after setting Idents() <- "predicted.id" (i.e., setting the cluster assignment from the TransferData), are these DEG markers the genes responsible for the cell label transfer from the ref dataset? 

2. Should the DEG markers found in 1 (i.e., of the query data) necessarily be found at all in respective clusters of the reference data? And, if so, are they necessarily the DEGs of clusters in the reference data?

Thank you for your help!

**Comment by mea2712** [comment]
Hey,
piggy backing here for clarification. When transfering cell type labels from a reference to a query:
1) To get the features used in the query to get the labels assigned I can switch the identities of the query to "predicted.id" and use FindAllMarkers()
2) How do I get the features used from the reference? Do I use FindAllMarkers() too and then look at the intersection?
