### ISSUE TITLE
Should I rerun SCTransform(vst.flavor = "v2")?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5737]
Hi there, 

In my pipeline, 
Step 1: I normalized the data by SCTransform(scale = FALSE, center = FALSE, vst.flavor = "v2")
Step 2: Calculated cell cycle gene scores on SCTransform-ed data - 
Step 3: Switched back to RNAssay and performed SCTransform(scale = TRUE, center = TRUE, regressing out percent.mt and cc.difference). 
Step 4: Switched back to SCT Assay to RunPCA and do clustering

The issue is that at Step 3, I forgot to also set vst.flavor = "v2" as in Step 1. Should I rerun my pipeline? 

Thank you very much for your help!

**Comment by saketkc** [comment]
I would recommend keeping the vst flavor consistent across your workflow.
