### ISSUE TITLE
How to install Seurat 4.1.0.9004 version? 

### ISSUE THREAD

**Issue by arielyh** [satijalab/seurat#5739]
I'm trying to use the function LoadAkoya() from this page https://satijalab.org/seurat/articles/spatial_vignette_2.html#human-lymph-node-akoya-codex-system-1
But my current 4.1.0 version of Seurat doesn't have this function. The instruction is using 4.1.0.9004 version, how can I install this version? 
Thank you very much.

**Comment by AustinHartman** [comment]
You can install the branch of Seurat containing the new spatial functions using `remotes::install_github("satijalab/seurat", "feat/imaging")`

**Comment by arielyh** [comment]
Hi Austin, 
I installed Seurat using your feat/imaging commend. But when I load Seurat, it says:
library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘SeuratObject’ 4.0.4 is already loaded, but >= 4.0.999.9009 is required
Should I upgrade SeuratObject version, too? What's the commend for upgrading SeuratObject? Thanks.

**Comment by arielyh** [comment]
NVM, I restarted R and now Seurat can be loaded. SeuratObject is 4.0.999.9011 and Seurat is 4.1.0.9004. And the LoadAkoya() function worked. 
Thank you so much.

**Comment by margaritaaparina** [comment]
Good day, I had this problem as well
Error in LoadAkoya(filename = "/brahms/hartmana/spatial_vignette_data/LN7910_20_008_11022020_reg001_compensated.csv",  :could not find function "LoadAkoya"
I have tried this command   remotes::install_github("satijalab/seurat", "feat/imaging")  but it is not running entirely. Could there be other possibilities?
