### ISSUE TITLE
FindAllMarkers not giving top genes for clusters 0 and 1

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#574]
Hi,

Whenever I am running the FindAllMarkers I am not getting the top genes for clusters 0 and 1. This is consistently happening irrespective of the data set.

This is the code.

```R
kidney_combined.markers <- FindAllMarkers(object = kidney_combined, only.pos = TRUE, min.pct = 0.1, return.thresh = 0.05, logfc.threshold = 0.25, test.use = "wilcox")
```

Thanks,

Bibaswan

**Comment by andrewwbutler** [comment]
This is not reproducible on the included testing dataset (`pbmc_small`). 

```R
library(dplyr)
m <- FindAllMarkers(object = pbmc_small, only.pos = TRUE,
                    min.pct = 0.1, return.thresh = 0.05, 
                    logfc.threshold = 0.25, test.use = "wilcox")
m %>% group_by(cluster) %>% top_n(2, avg_logFC)
```
```
# A tibble: 8 x 7
# Groups:   cluster [4]
     p_val avg_logFC pct.1 pct.2 p_val_adj cluster gene  
     <dbl>     <dbl> <dbl> <dbl>     <dbl> <fct>   <chr> 
1 8.32e- 4      3.74 0.207 0      1.91e- 1 0       CCR7  
2 2.08e- 2      4.76 0.103 0      1.00e+ 0 0       IGLL5 
3 1.36e- 4      3.29 0.31  0.02   3.13e- 2 1       FCER1A
4 2.45e- 3      3.60 0.172 0      5.64e- 1 1       ZNF330
5 2.11e-12      4.49 0.667 0      4.86e-10 2       AKR1C3
6 3.25e- 5      4.14 0.25  0      7.48e- 3 2       S100B 
7 1.86e-15      6.13 0.9   0.014  4.27e-13 3       PF4   
8 2.46e-15      6.31 1     0.043  5.67e-13 3       PPBP 
```

Perhaps your thresholds are too stringent for those clusters in your particular dataset.

**Comment by ghoshal** [comment]
Hi, 

Yes this is true. It is working for other datasets. But for some it is not. The only thing is that it is always clusters 0 and 1. This has been consistent. Hence, I was wondering if you have any idea why that might be. If the thresholds are too high then that can impact all clusters rater than just the 1st two.

**Comment by chlee-tabin** [comment]
This might be due to the size of the cluster 0 and 1 being the biggest and second biggest cluster, thus having somehow more variability, so the threshold could affect differently to other clusters.

**Comment by satijalab** [comment]
This is not a Seurat issue, but may reflect that the largest clusters in the data may be the least poorly defined - either due to small size, or low sequencing depth. It may also reflect the possibility that a large number of cell barcodes are associated with ambient RNA.
