### ISSUE TITLE
Importance of 'scale' in DotPlot

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#5742]
Our lab wants to include dot plots in a figure to illustrate magnitude of differential expression.  Dot plots were created for a few genes comparing two groups: disease vs normal.  

`DotPlot(rna, features =genes.use, idents = c('disease', 'normal'))`

The dotplots produced looked amazing, with clear distinction between upregulated and downregulated DEGs.  (sorry for blurry image)
![image](https://user-images.githubusercontent.com/65676131/158488640-e6710611-c58d-4e4b-a73a-5433b9016e1f.png)

However, I realized this was because of scaling (`scale = T` by default), and not representative of actual diff expression magnitude.  when you only have two groups, the resulting numbers are always 0.707 and -0.707 (sd = 1).  Its binarizing the plot

I feel like this could go unnoticed by many people, as it happened in our case.  So I wanted to mention it

**Comment by timoast** [comment]
Hi @danielcgingerich, I agree this can definitely lead to misleading results, and becomes more extreme as the number of groups gets lower. I've added a warning message to DotPlot that will now be displayed when plotting <5 groups.

**Comment by danielcgingerich** [comment]
@timoast I did not see this until now, thanks!

**Comment by denvercal1234GitHub** [comment]
@danielcgingerich - Would you mind elaborating a bit more on the technical bias by DotPlot (setting scale=T) you kindly pointed out? Thank you so much.
