### ISSUE TITLE
in Seurat 4.1 version FindVariableFeatures takes a long time and use >100 cores

### ISSUE THREAD

**Issue by MinBio** [satijalab/seurat#5745]
I am running FindVariableFeatures step with Seurat v4.1.0. but it is hanging there for a long time and using >100 cpus in the second step "Calculating feature variances of standardized and clipped values" . I am not sure what's going on here.  Could you help me with it?

Thank you in advance!

**Comment by yuhanH** [comment]
hi @MinBio 
Sorry for the late reply. We haven't met the issue before. Could you provide us a reproducible example?

**Comment by equator8848** [comment]
Hi, I meet this problem in Seurat 5.2.1 too, the same code in different Linux server cost time differ sharply.
```
a <- qs::qread("/home/equator/seurat-demo/tmp.qs")
system.time(Seurat::FindVariableFeatures(a))
```
I don't know if other R packages will affect Seurat.
