### ISSUE TITLE
Reverse PCA

### ISSUE THREAD

**Issue by yutongo** [satijalab/seurat#5748]
Hi, thanks for the helpful package!

After RunPCA, the scaled VariableFeatures have been dimensionally reduced to several PCs. 

Could you also provide the way to reconstruct the VariableFeatures from a small number of PCs (i.e. 𝑘 eigenvectors)?
Have the mean and variance of each gene been stored using ScaleData so that I can map the scaled data back to normalized data?

Thank you!

**Comment by yuhanH** [comment]
You can use `Seurat:::RowMeanSparse()` and `Seurat:::RowVarSparse()` to fast calculate the mean and variation of variable genes in the data slot.
However, it will be hard to perfectly reconstruct the data slot from PCA in default settings, because `ScaleData` has a clip setting `scale.max = 10`.

**Comment by yutongo** [comment]
> You can use `Seurat:::RowMeanSparse()` and `Seurat:::RowVarSparse()` to fast calculate the mean and variation of variable genes in the data slot. However, it will be hard to perfectly reconstruct the data slot from PCA in default settings, because `ScaleData` has a clip setting `scale.max = 10`.

Hi yuhanH,

Thank you for the quick response!

For the Seurat:::RowMeanSparse() and Seurat:::RowVarSparse(): which version of Seurat you mentioned? I didn't find the exact function in Seurat 4.0.2. I can use other similar functions if vars.to.regress=NULL .

Could you provide the option to save the mean and variance during ScaleData?


For the PCA: I get that the perfect reconstruct is hard. Could you provide the exact package Seurat used for PCA or the option to save eigenvectors?

Thanks!

**Comment by yuhanH** [comment]
They are in the latest Seurat (Version 4.1.0). We don't store the mean and variation in `ScaleData`. 
To have a better reversible reconstruction, you can set `scale.max ` to a very big value or you can scale you data by your own scale function and then put output in the `scale.data` slot. 
In default setting, we use `irlba` for PCA. You can find more documentation by `?RunPCA`. You can also directly check our  `RunPCA` function `Seurat:::RunPCA.default`

**Comment by yutongo** [comment]
> They are in the latest Seurat (Version 4.1.0). We don't store the mean and variation in `ScaleData`. To have a better reversible reconstruction, you can set `scale.max ` to a very big value or you can scale you data by your own scale function and then put output in the `scale.data` slot. In default setting, we use `irlba` for PCA. You can find more documentation by `?RunPCA`. You can also directly check our `RunPCA` function `Seurat:::RunPCA.default`

 Thank you!
