### ISSUE TITLE
Assay for sPCA in multimodal reference mapping

### ISSUE THREAD

**Issue by chenyixue09** [satijalab/seurat#5750]
Dear Seurat team,

I have a question on the assay to use in multimodal reference mapping.

We have integrated a few CITE-seq datasets using WNN following the suggestion on 
https://github.com/satijalab/seurat/issues/3890#issuecomment-787598143

RNA and protein was integrated in two objects. Briefly, we ran SCTransform() on RNA expression in each sample, and integrated RNA assays using anchor-based workflow. Then we normalized protein expression in each sample using CLR method, identified variable proteins, and integrated protein assays using anchor-based workflow. FindMultiModalNeighbors() was run on 20 PCs from RNA and 15 PCs from protein.

The query data is a number of scRNA-seq samples. Which assay shall I use in RunSPCA() for the integrated reference?
Variable features are from the integrate assay so sPCA does not work on SCT or RNA assay. Shall I set the variable features to SCT before running RunSPCA(). Or shall I run sPCA on the integrated assay?

Thank you!

**Comment by yuhanH** [comment]
Hi
In theory, you would better use the integrated residuals to perform sPCA.  sPCA is going to capture the gene variation direction that have maximally dependence on the multimodal SNN graph.  Variable features in the integrated assay are from the variable genes in the SCT.
If you run sPCA on the SCT assay residuals, you would observe some batch effects in the sPCA embeddings.
