### ISSUE TITLE
Correct way to run DESeq2 in FindMarkers on an integrated data

### ISSUE THREAD

**Issue by coralzhang** [satijalab/seurat#5751]
Hi, I am having a question about the correct way of using DESeq2 feature in the function FindMarkers, in my case on an integrated object. 
I went through the NormalizeData and FindVariableFeatures for each of my three original data object, and then used the FindIntegrationAnchors and IntegrateData to create the integrated object. 
So the point I want to emphasize is that at this point, the default assay is the "integrated" assay for my integrated object. I checked, and for my integrated object, the counts slot is empty and data has the 2000 selected variable genes in there. Since I did run the ScaleData on this integrated object, my scale.data is also filled. When I tried to run the FindMarers using DESeq2 using the following code, I get error 
`> FindMarkers(integ.obj, ident.1 = group.high , ident.2 = group.0, test.use="DESeq2")
`

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid or not-yet-implemented 'Matrix' subsetting
`
After looking at the content of my integrated object, I realize that this could be because that the DESeq2 requires raw counts, but the default "integrated" assay  does not have that. So I switched the default assay by 
`>     DefaultAssay(integ.obj)  <- "RNA"`

Then, the same FindMarkers code above worked for me. 
Also, I found that the wilcox and DESeq2 provided very different DE genes, so this triggers my question of if I have used DESeq2 correctly and if there are any guidelines for dealing with this discrepancy? Also, do I need to manually add the `slot="counts" `for the DESeq2 option in FindMarkers?  Thank you very much!

**Comment by saketkc** [comment]
DESeq2 requires counts, so you should switch to RNA assay. DE should not be performed on integrated assay irrespective of the choice of DE test.

**Comment by coralzhang** [comment]
Thank you for your answer. Could you please help clarify more on "DE should not be performed on integrated assay". I just want to confirm that it is still ok to run DE on an integrated object, just has to be on the RNA assay of the integrated object, correct? Thanks!

**Comment by ElyasMo** [comment]
This is my question as well. Any helps would be appreciated. After integrating the datasets, Find markers in integrated assay gives weird Volcano plots. If I understood correctly, you said we should use RNA assay for DE, but my question is that if we change to RNA assay, the information there is not corrected based on the two datasets using anchor based method. So, can we trust the DE provided from RNA assay?

**Comment by saketkc** [comment]
You should use RNA or SCT assay to run differential expression analysis. In case of RNA assay  the data needs to be LogNormalized (which is also the first step if you used LogNormalization for integration), in case of SCT assay, the data slot already stores the corrected counts.

**Comment by ElyasMo** [comment]
> You should use RNA or SCT assay to run differential expression analysis. In case of RNA assay the data needs to be LogNormalized (which is also the first step if you used LogNormalization for integration), in case of SCT assay, the data slot already stores the corrected counts.

Thanks for the reply. I see your point but here is my question. We do the data integration to remove the unknown batch effects between to datasets e.g. scRNAseq data. The corrected data would be stored in integrated assay in a new count and scale.data slot. The normalization that we do in data integration step are being done for each of the datasets independently and the data correction is being done using the anchor-based method. So, if we do not use the "integrated" assay for DEGs, does it mean that we are using again the uncorrected data and the DEGs could be due to the batch effects between two datasets. 

To make it more clear, if we do not use the "integrated" assay, why would be do the data integration when simply we can merge two datasets and do the DEGs?

**Comment by mesposit** [comment]
>  Also, do I need to manually add the `slot="counts" `for the DESeq2 option in FindMarkers? Thank you very much!

If you run ?FindMarkers in R and check the "slot" argument, it gives you the following information:
Slot to pull data from; note that if test.use is "negbinom", "poisson", or "DESeq2", slot will be set to "counts"

This makes sense as the DESeq2 method uses unnormalized counts as input (see vignette for further information: http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#why-un-normalized-counts)
