### ISSUE TITLE
Load processed .RDS matrix and metadata file as Seurat object

### ISSUE THREAD

**Issue by KinSimon96** [satijalab/seurat#5757]
Hello, 

I've downloaded `GSE139555_all_integrated.rds.gz`  and `GSE139555_all_metadata.txt.gz` from [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE139555) through R and I would like to convert them to a ready-to-use Seurat object. This comes from multiple samples that have been normalized/integrated, and umap coordinates/ident/patient/... are provided in the metadata file.

Here is the normalized matrix:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/57133275/158992616-baf83310-da13-43bf-acd8-eaa84ac16e07.png">

Here is the metadata file:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/57133275/158992810-f573aa3c-23ce-455a-bbed-72e3fbe45c7a.png">
 
Would you have a trick to turn them into a Seurat object ?

Many thanks in advance!
Simon

**Comment by yuhanH** [comment]
Hi
you can use `obj <- CreateSeuratObject(counts = matrix , meta.data =  meta)` to generate a seurat object.
Then use `CreateDimReducObject(embeddings = meta[,c('UMAP_1','UMAP_2')], key = 'UMAP_', assay = 'RNA')` to add the umap coordinates.

**Comment by Elo-mars** [comment]
thanks @yuhanH for showing how to simply, and elegantly, add the metadata to a Seurat object! (not a matrix of gene per cell for me, but the barcode-features-matrix files)

now, when I'm trying to add umap coordinates (I download also an available dataset and I also have the UMAP_1 and  UMAP_2 in the metadata txt file), I first have an error

> invalid class “DimReduc” object: invalid object for slot "cell.embeddings" in class "DimReduc": got class "data.frame", should be or extend class "matrix"


now I just opened my metadata like this and transformed into matrix

```
meta=read.table("metadata.txt", sep="\t", header=TRUE)
rownames(meta) <- meta[,1]
meta[,1] <- NULL
head(meta)
```

>                                                     Segment Sex Time Type Unique_ID nGene  nUMI    UMAP_1
> H1_S5.GTCACGGCATTTCACT       NA   F   NA   NA        S5  1069  1529  1.831810
> H1_S5.CGATCGGTCGTTTGCC       NA   F   NA   NA        S5  3482 11561  1.641810
> H1_S20.ACATCAGAGCCAACAG      NA   F   NA   NA       S20  5267 10259 -4.095062
> H1_S9.GTCCTCATCTCTAGGA       NA   F   NA   NA        S9  1157  1575  2.672162
> H1_S4.ATCACGATCAACACAC       NA   F   NA   NA        S4  5155  9444  0.677732
> H1_S5.TACGGATTCAAACGGG       NA   F   NA   NA        S5  6175 13122  1.712561
>                                                      UMAP_2  LABEL
> H1_S5.GTCACGGCATTTCACT   1.014331 PIMN_3
> H1_S5.CGATCGGTCGTTTGCC  -2.930424 PIMN_3
> H1_S20.ACATCAGAGCCAACAG  2.058985 PEMN_1
> H1_S9.GTCCTCATCTCTAGGA   5.349984 PIMN_1
> H1_S4.ATCACGATCAACACAC   2.706116 PIMN_2
> H1_S5.TACGGATTCAAACGGG   1.985193 PIMN_2
> 

```
metamat=as.matrix(meta)
CreateDimReducObject(embeddings = metamat[,c('UMAP_1','UMAP_2')], key = 'UMAP_', assay = 'RNA') 

```

it does output this:

> A dimensional reduction object with key UMAP_ 
>  Number of dimensions: 2 
>  Projected dimensional reduction calculated:  FALSE 
>  Jackstraw run: FALSE 
>  Computed using assay: RNA 

but my Seurat object is still without "reduction:umap"
so if I do a DimPlot
I have this error:


> Error: Unable to find a DimReduc matching one of 'umap', 'tsne', or 'pca', please specify a dimensional reduction to use

can you maybe help me?

thanks!

Elodie

**Comment by Elo-mars** [comment]
I found this:

https://github.com/satijalab/seurat/issues/1284#issuecomment-476862322

        You can use `[[` to add a `DimReduc` object to a Seurat object

```R
dr <- CreateDimReducObject(...)
seurat.object[['pca']] <- dr
```

_Originally posted by @mojaveazure in https://github.com/satijalab/seurat/issues/1284#issuecomment-476862322_


kinda solved it - my DimPlot is a little weird, but I think I'm close

**Comment by yuhanH** [comment]
hi @Elo-mars 
Right. You can create a dimensional reduction by `[[`
```
obj[['umap']] <- CreateDimReducObject(embeddings = metamat[,c('UMAP_1','UMAP_2')], key = 'UMAP_', assay = 'RNA') 

```
