### ISSUE TITLE
FindMarkers between two clusters, one much larger than the other (unequal size) and max.cells.per.ident parameter

### ISSUE THREAD

**Issue by behyag** [satijalab/seurat#5758]
hi Seurat Team! 
I have a question about Findmarkers() between two groups with very unequal sample sizes! I have a dataset of two conditions wt / KO and the KO cells are 3 times more than the wt, so in every cluster, KO cells are naturally higher in numbers. I did DE between the two conditions per cluster, using FindMarkers() and one concern is that the size difference can affect the DEG results? 
> cluster1_DEG <- FindMarkers(obj, ident.1 = "cluster1_KO", ident.2 = "cluster1_wt", only.pos = FALSE) 
(with other parameters as default) 
One way is to use max.cells.per.ident parameter and set is to the smaller (wt) cell number in each cluster. 
e.g, if there are KO=1080 cells and WT=450 cells in cluster 1, then:
> cluster1_DEG <- FindMarkers(obj, ident.1 = "cluster1_KO", ident.2 = "cluster1_wt", max.cells.per.ident=450,  only.pos = FALSE) 
Q1. does it make sense? 
Q2.  if it does, how does Seurat do down-sampling? is it random? then every time I run this, I might get different DEG list with different p.values? then should I set.seed= some.value ? or  random.seed= some value or the default 1? 

any advice or feedback is truly appreciated! 

many thanks.

**Comment by torkencz** [comment]
As far as I know Seurat does not do sample size correction when doing DE. See https://github.com/satijalab/seurat/issues/1340 . I would do both and see what DEG change with different sample sizes.

**Comment by behyag** [comment]
hi Kristof and thank you for your reply! 
Could you please comment on my second question Q2, regarding random down-sampling and the seed? 
I guess the default set.seed=1 should be OK, right? 

many thanks!
