### ISSUE TITLE
"Insufficient data values to produce 24 bins" in SCT v2 issue persisted 

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#5760]
Hi there, 

In issues #3692 and #1227, it was suggested the issue can be resolved by setting min.cell=1 and calculate the cell cycle gene scores on SCTransform-ed object. 

Nevertheless, the issue still persisted with SCT v2 model 

Would you mind helping me to resolve this issue? 

Thank you very much for your help. 

<img width="850" alt="Screen Shot 2022-03-19 at 3 46 57 PM" src="https://user-images.githubusercontent.com/62179082/159128109-f22699e5-06e7-465a-8eba-7d9c5fbe8d81.png">

**Comment by saketkc** [comment]
This is coming from `CellCycleScoring` and is not something specific to SCT v2. This is likely arising from the fact that a lot of genes in your object have low average expression. Have you tried creating your object with a more stringent min.cells cutoff (say like 10 or 20)?

**Comment by denvercal1234GitHub** [comment]
Thank you @saketkc for your response. In this example, I used miQC to remove low-quality cells instead of manually setting thresholds for nCounts, nFeatures and percent.mt. So, should I still use min.cells in the CreateSeuratObject() even if I used miQC?

**Comment by saketkc** [comment]
If you can share a reproducible example, I can try to debug. My email is schoudhary@nygenome.org

**Comment by denvercal1234GitHub** [comment]
Solved by setting a more stringent min.cells
