### ISSUE TITLE
Finding variable features after using SCTransform separately on each sample

### ISSUE THREAD

**Issue by gilstel** [satijalab/seurat#5761]
In a previous correspondence #5667 you wrote -
> If you are using SCTransform, `NormalizeData` and `ScaleData` are not required (this is also mentioned in the SCTransform [vignette](https://satijalab.org/seurat/articles/sctransform_vignette.html)). You should also not be regressing `nCount_RNA`, and **ideally SCTransform should be run on each sample separately** (to learn the sample specific noise model). You can check for batch effects by coloring the merged samples (after running SCTransform) on their batch. It appears that integration might be necessary here (you can confirm).

It seems that you recommend to always run SCTranform separately on each sample, even if I am not planning on integrating data.  Is this correct?
If I always run SCTransform separately, each sample will get its own variable features and after merging, the variable features will be deleted automatically.  What is the best way to generate variable features for the merged samples (after separate SCTransform)?  When I try to use FindVariableFeatures on the merged object, I get the following error - 

Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-

I can use SelectIntegrationFeatures on the separate sample list before I merge the objects but I am not sure this is correct

Thanks,
Gil

**Comment by saketkc** [comment]
Yes, we do recommend running SCTransform on each object separately. For selecting variable features, you could either take an intersection or select using [SelectIntegrationFeatures](https://satijalab.org/seurat/reference/selectintegrationfeatures) and then set `VariableFeatures(merged_object) <- my_integration_features`.

**Comment by denvercal1234GitHub** [comment]
Hi @saketkc - Did you mean to use HVFInfo() on each of the SCTransform-ed objects, then take the intersection of the two vectors of the variable features? Thank you for your input.

**Comment by saketkc** [comment]
No, as I mentioned you can use `SelectIntegrationFeatures`: 
> Choose the features to use when integrating multiple datasets. This function ranks features by the number of datasets they are deemed variable in, breaking ties by the median variable feature rank across datasets. It returns the top scoring features by this ranking.

**Comment by denvercal1234GitHub** [comment]
Hi @saketkc , so even if I just merged the two objects that were SCTrasnform-ed (and not integrating them), I could still use SelectIntegrationFeatures()?

**Comment by saketkc** [comment]
Yes

**Comment by denvercal1234GitHub** [comment]
Thank you so much!
