### ISSUE TITLE
Why not add shuffle function to Featureplot?

### ISSUE THREAD

**Issue by vagabond12** [satijalab/seurat#5762]
Why not add shuffle function to Featureplot?

Many expressed genes were buried

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So the points are shuffled by default in `FeaturePlot` but if you want to order the points by expression level you can just set the parameter `order = TRUE`.

Best,
Sam

**Comment by vagabond12** [comment]
I have tried many times, the expression signal of some genes were always buried. And I believe that the points are not shuffled by default in FeaturePlot, and there is no method to set shuffle in Featureplot. Meanwhile, I have 65,000 cells in my Seurat object, if only hundreds or thousands of cells, or gene expression pattern was similar among samples, you may not find that the points are not shuffled.  Thank you, and I am waiting for the answer from the dev team.

**Comment by samuel-marsh** [comment]
Hi,

Sorry I'm little confused by your explanation.  Yes technically the points are not shuffled and are just in the order they are in the object.  But on average when viewed at gene level this accounts for a "random" positioning of expressing and non-expressing cells.  If we were to shuffle the points randomly as the shuffle parameter does in `DimPlot` this won't necessarily solve the issue of genes being buried because it would still result in expressing cells being behind non-expressing ones.  However, the `order` parameter does solve this issue.  Here is example of two plots.  I've increased the point size to exaggerate the effect here.

```
pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

FeaturePlot(object = pbmc, features = "CD8A", pt.size = 2)
FeaturePlot(object = pbmc, features = "CD8A", order = T, pt.size = 2)
```

![image](https://user-images.githubusercontent.com/38284410/159906294-1491f8a7-1086-4271-9555-78774c9354d3.png)
![image](https://user-images.githubusercontent.com/38284410/159906321-7039f480-dd1b-4073-a11b-83827eb0e149.png)


As you can see in first plot there are some points that buried while in the second plot with `order = TRUE` they are all brought to the front.  If the points were randomly shuffled you might get a plot that looked slightly better than the first one but on average would still likely have points buried.  Hence using `order` is the solution to ensure you see the expressing cells in front of the background.

Best,
Sam

**Comment by vagabond12** [comment]
Hi,
I have explained clearly. You do not have so many samples from different individuals, so you could not make the buried effect.
I do not know where the confedence you have is from. And you have already waste so much time of mine.
OK,
this is the buried effect.
![捕获](https://user-images.githubusercontent.com/24886447/160042476-61c62e85-f420-499e-b324-0e78adf2aed1.PNG)


this is the order=T effect
![image](https://user-images.githubusercontent.com/24886447/160042561-bd9d966c-7842-43d9-aea9-721cc21e9d7c.png)


this is the shuffle effect that I made myself that took me a lot of time by ordering the order of cells randomly

![image](https://user-images.githubusercontent.com/24886447/160042615-c42eeee7-b296-42d0-ac08-22ce30696807.png)


But I need shuffle function in the featureplot without any extra job of mine.

**Comment by timoast** [comment]
> I do not know where the confedence you have is from. And you have already waste so much time of mine.

@vagabond12 This type of attitude towards other people who are volunteering their time to help you is not acceptable on this forum. Please refrain from making any comments like this in the future.  Sam has been extremely helpful in providing support for this issue and many others.

**Comment by samuel-marsh** [comment]
Thank you @timoast.

Respectfully I will add one more comment on the shuffling issue.  As I mentioned before and can be seen in your shuffled example this also results in significant number of buried cells and therefore I don't believe gives accurate representation of where the gene is expressed across the dataset (compared to ordered plot).  If the ordered plot is difficult to understand visually given the number of samples and cells I would suggest that another visualization method (VlnPlot, Heatmap, or something like density plots from Nebulosa) might be more appropriate for the information you are trying to convey.

Best,
Sam

**Comment by john-j-oh** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. So the points are shuffled by default in `FeaturePlot` but if you want to order the points by expression level you can just set the parameter `order = TRUE`.
> 
> Best, Sam

Thank you so much Sam!

I've been trying to figure out why `shuffle` on `FeaturePlot` function was not working - obviously for data representation reasons, it's not right. Your explanation on `order` parameter was expertly explained and I figured it out immediately!

**Comment by kaizen89** [comment]
I agree that adding a `shuffle` parameter would improve the visualisation, plotting the cells by their default order is problematic as usually cells coming from different samples after merging would not be ordered randomly. Shuffling the cells would still burry some expression but would give a nice idea of the proportion of expressing cells. Using `order=T` could make it look like 100% of the cells are positive for a given marker. Therefore I think shuffling would be closer to reality.

**Comment by ShanshanHe-44** [comment]
> Thanks @samuel-marsh for your always enormous help! @vagabond12 Please avoid the inappropriate attitude in our forum as Tim mentioned.
> 
> I also agree with Sam's point. @vagabond12 You may consider using other methods for your visualization. But if you still insist to use shuffled feature plot, you can try the following scripts. Basically, you can put the cell order in the `cells` parameter in the `FeaturePlot`.
> 
> ```
> library(SeuratData)
> data('pbmc3k')
> pbmc3k <- NormalizeData(pbmc3k)%>%FindVariableFeatures()%>%ScaleData()%>%RunPCA()
> pbmc3k <- RunUMAP(pbmc3k, dims = 1:30)
> 
> 
> features <- 'IL7R'
> cells.order.1 <- names(sort(pbmc3k[['RNA']]@data[features,]))
> cells.order.2 <- names(sort(pbmc3k[['RNA']]@data[features,], decreasing = T))
> cells.order.random <- sample(Cells(pbmc3k))
> 
> p1 <- FeaturePlot(pbmc3k, features = features, reduction = 'umap', cells = cells.order.1)
> p2 <- FeaturePlot(pbmc3k, features = features, reduction = 'umap', cells = cells.order.2)
> p3 <- FeaturePlot(pbmc3k, features = features, reduction = 'umap', cells = cells.order.random)
> 
> p1+p2+p3
> ```
> 
> ![image](https://user-images.githubusercontent.com/29529544/161299190-d2aac314-dee6-4279-8531-01757f4c096d.png)

Thanks for sharing! I think randomising the cells order gives the same result as shuffling, but like kaizen said, an extra shuffle parameter would be much easier!
