### ISSUE TITLE
AddModuleScore() with spatial data

### ISSUE THREAD

**Issue by lsudupe** [satijalab/seurat#5765]
I am using AddModuleScore() in my spatial data without problems. When I get the results, it doesn't make sense if I compare them with other enrichment score methods. I am using the integrated assay of my spatial data, should I use the SCT or Spatial assays instead?

Are there extra considerations to take when using this function with spatial data?

**Comment by yuhanH** [comment]
Hi
You can use either SCT or Spatial assays for the module score, just not using `integrated assay`.
Could you show a specific example with your scripts?

**Comment by lsudupe** [comment]
Hi
Thank you for your response. I am using the integrated assay. Could you explain to me the difference between using this function with the integrated assay or the others please?

a <- AddModuleScore(a, features = B, assay = "integrated", name = "geneSetB_")

**Comment by torkencz** [comment]
We generally do not recommend doing statistics on imputed values as they can be negative etc. Doing calculations on those values is much more risky and I would advise sticking to the raw data but using the labels derived via the integration.

**Comment by lsudupe** [comment]
Thank you @torkencz !!

**Comment by rxy712** [comment]
Thanks for all the information here. I am also using AddModuleScore() on the spatial data. If using SCT assay, it will use values in the data slot which will be normalized data but not batch corrected data. It that OK considering the batch effect?
