### ISSUE TITLE
Split Seruat Object by Condition

### ISSUE THREAD

**Issue by Skrueger09** [satijalab/seurat#5768]
Hi,
I am reprocessing data from a published experiment following the Seurat workflow.  I have ran into an error (see below) when working on splitting the seruat object by condition.  
<img width="832" alt="Screen Shot 2022-03-22 at 10 57 31 AM" src="https://user-images.githubusercontent.com/100965543/159523458-09371645-13e2-4e08-81b9-c939855e848c.png">

It is giving a NULL matrix error and it is not letting me progress through with more analysis.  Any suggestions would be greatly appreciated.  

Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you post full code you are running? 

Best,
Sam

**Comment by Skrueger09** [comment]
Hey @samuel-marsh .  Here is part of my code, that is preceding the issue:
#Create metadata_filtered dataframe
metadata_filtered = filtered_seurat@meta.data
head(metadata_filtered)

# Normalize the counts
seurat_phase <- NormalizeData(filtered_seurat)

# Download cell cycle genes for organism at https://github.com/hbc/tinyatlas/tree/master/cell_cycle. Read it in with:
cc_file = getURL("https://raw.githubusercontent.com/hbc/tinyatlas/master/cell_cycle/Mus_musculus.csv")
cell_cycle_genes = read.csv(text = cc_file)
cell_cycle_markers = dplyr::left_join(cell_cycle_genes, annotations, by = c("geneID" = "gene_id"))
#Acquire the S phase genes
s_genes = cell_cycle_markers %>%
  dplyr::filter(phase == "S") %>%
  pull("gene_name")
#Acquire the G2M phase genes
g2m_genes = cell_cycle_markers %>%
  dplyr::filter(phase == "G2/M") %>%
  pull("gene_name")

#Score cells for cell cycle
seurat_phase = CellCycleScoring(seurat_phase, g2m.features = g2m_genes,
                                s.features = s_genes) 
#View cell cycle scores and phases assigned to cells
head(seurat_phase@meta.data)

seurat_phase = FindVariableFeatures(seurat_phase,
                                    selection.method = "vst",
                                    verbose = FALSE)
# Perform PCA
#Scale the counts
seurat_phase = ScaleData(seurat_phase)
seurat_phase = RunPCA(seurat_phase)

# Plot the PCA colored by cell cycle phase
DimPlot(seurat_phase,
        reduction = "pca",
        group.by = "Phase",
        split.by = "Phase")
# Plot the PCA colored by cell cycle phase Condition
DimPlot(seurat_phase,
        reduction = "pca",
        group.by = "Phase",
        split.by = "Condition")

#Set working space on how much RAM to use
options(future.globals.maxSize = 8000 * 1024^2)

# Split seurat object by condition to perform cell cycle scoring and SCT on all samples
split_seurat <- SplitObject(filtered_seurat, split.by = "Condition")
split_seurat <- split_seurat[c("ctrl", "exp")]


for (i in 1:length(split_seurat)) 
  {
  split_seurat[[i]] <- NormalizeData(split_seurat[[i]], verbose = TRUE)
  split_seurat[[i]] <- CellCycleScoring(split_seurat[[i]], g2m.features=g2m_genes, s.features=s_genes)
  split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = c("mitoRatio"))
}

**Comment by timoast** [comment]
Are you sure that both "ctrl" and "exp" were present in `split_seurat`? If they weren't you will end up with `NULL` in your list of objects and would explain the later error

**Comment by mhkowalski** [comment]
Closing because of no response. Please reopen if you have additional follow-ups.
