### ISSUE TITLE
Applicability of runCCA?

### ISSUE THREAD

**Issue by lololiam** [satijalab/seurat#577]
Hi, 

I have a small dataset of ~30 manually isolated cells that I would like to merge to a larger, annotated dataset that should contain cells similar to these, if not the same.

I was looking at the workflows here: 
https://hemberg-lab.github.io/scRNA.seq.course/comparingcombining-scrnaseq-datasets.html
and here:
https://satijalab.org/seurat/immune_alignment.html

I am worried runCCA may not be appropriate due to the first link throwing out dataset-specific cell types prior to aligning, and every cell type in the reference dataset besides one would be dataset-specific.

If this is not possible, is there another way I can approach this to get expression information from my small dataset?

Thanks,
Liam

**Comment by satijalab** [comment]
Unfortunately our integration workflow is unlikely to be applicable to relatively small datasets of <100 cells, you could try some of the classification approaches outlined in the link above
