### ISSUE TITLE
RPCA integration - R session aborted

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#5771]
Hi,

I am trying to integrate my adult brain data (11 samples = tot 50K cells) with fetal data (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE119212, 30K cells) using RPCA integration. When it's at the last integration step 
_"Integrating data
Merging dataset 1 8 into 7 9 11 5 6 4 3 2 10
Extracting anchors for merged samples
Finding integration vectors"_

I get the error R session aborted.

How can I solve this?

thanks!

This is my code:
`myse.list <- SplitObject(myse, split.by = "sample")
myse.list <- lapply(X = myse.list, FUN = SCTransform, method = "glmGamPoi")
features <- SelectIntegrationFeatures(object.list = myse.list, nfeatures = 3000)
myse.list <- PrepSCTIntegration(object.list = myse.list, anchor.features = features)
myse.list <- lapply(X = myse.list, FUN = RunPCA, features = features)

myse.anchors <- FindIntegrationAnchors(object.list = myse.list, normalization.method = "SCT",
    anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 20)
myse.combined.sct <- IntegrateData(anchorset = myse.anchors, normalization.method = "SCT", dims = 1:30)`

**Comment by longmanz** [comment]
Hi @giorgiatosoni,
You may try the latest SCTransform v2 (Seurat >= v4.0.6; https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) and see if it fixes the problem. Just change your second command to:
`myse.list <- lapply(X = myse.list, FUN = SCTransform, method = "glmGamPoi", vst.flavor = "v2")`

**Comment by giorgiatosoni** [comment]
> Hi @giorgiatosoni, You may try the latest SCTransform v2 (Seurat >= v4.0.6; https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) and see if it fixes the problem. Just change your second command to: `myse.list <- lapply(X = myse.list, FUN = SCTransform, method = "glmGamPoi", vst.flavor = "v2")`

Thank you! Unfortunately still crashing during the integration.

**Comment by yuhanH** [comment]
HI @giorgiatosoni 
I would suggest you set some `reference` in the `FindIntegrationAnchors` which can avoid some computational expensive steps. Here are [Tips for integrating large datasets](https://satijalab.org/seurat/articles/integration_large_datasets.html). 
Also, you can try our new integration framework:  [Atomic sketch integration](https://satijalab.org/seurat/articles/atomic_integration.html),  which is designed for large scale data integration.

**Comment by yuhanH** [comment]
Hi @giorgiatosoni 
Since i haven't got new information about this issue, I will close it now. If you still meet this problem, I will reopen it.
