### ISSUE TITLE
PCA with gene list

### ISSUE THREAD

**Issue by jimena2** [satijalab/seurat#5773]
I would like to run PCA on a list of genes but it seems that I can only use 

VariableFeatures(object = srt_merged)

as an input to features

The code I would like to run would look something like:
srt_merged <- RunPCA(object = srt_merged, assay = "SCT", npcs = 50, features=c('GENE_1','GENE_2','GENE_3'))

Any suggestions?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can run PCA supplying your own feature list instead of using the variable features.  See documentation here: https://satijalab.org/seurat/reference/runpca

Best,
Sam

**Comment by jimena2** [comment]
Hi thanks! Do you perhaps have an example of the code you wood use to run PCA with genes "CD4, CD3E, and CD8A"?

**Comment by torkencz** [comment]
You can give a set of features to RunPCA (features parameter).
