### ISSUE TITLE
Cell count from each sample in integrated analysis

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#5775]
I wanted to determine if the number of particular cell type in a cluster is increasing or decreasing with the treatment. I am using stimulated vs. control PBMC datasets vignette for this analysis.

Question:
I use code below to get the counts in each cluster and treatment condition BUT it shows cell numbers/count from all samples together. I want to know the cell counts in individual samples OR contribution of number of cells from each samples.

`table(Idents(immune.combined), immune.combined$stim)`

Thank you

**Comment by torkencz** [comment]
Hi. It may be easiest to subset cells to one specific sample and run your code. This can either be done with the subset function or by sub setting the metadata data frame of your object. Hope this is helpful.

**Comment by samuel-marsh** [comment]
Hi @singcell 

You could also consider using this function from my package scCustomize.  It will work using any column in the @meta.data slot: https://samuel-marsh.github.io/scCustomize/articles/Statistics.html#cells-per-identity

Best,
Sam

**Comment by singcell** [comment]
Thank you all for your replies!
@samuel-marsh Your package is what exactly I wanted for this question!
