### ISSUE TITLE
Please review PR for SeuratData

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#5778]
Hello,

This PR has been open since December and there hasnt been any comment. I'm sorry to double-post, but this issue is growing as a problem.

https://github.com/satijalab/seurat-data/pull/45

When you load SeuratData, there are a series of warnings logged, as reported here:

https://github.com/satijalab/seurat-data/issues/41

While this is just a warning, github actions has begun to interpret this loading as an error and is failing to load SeuratData. Granted, I can and probably am going to debug this; however, fixing the root problem, which is a bug in SeuratData, is a very minor fix.

Thank you for looking into this.

**Comment by mojaveazure** [comment]
Done, thanks for the fix and apologies for the delayed response!
