### ISSUE TITLE
How to change the cell order of the Seurat object?

### ISSUE THREAD

**Issue by vagabond12** [satijalab/seurat#5779]
How to change the cell order of the Seurat object?

In Seurat 2 or 3, SubsetData select cells and reorder cells according to cell identities. However, in Seurat 4, subset function could replace SubsetData to some point, but it does not change the cell order.

As column order of the input count table affects the results (#4192), so in Seurat 4, is there a method that could change the cell order of the Seurat object?
Thank you.

**Comment by yuhanH** [comment]
Hi 
There is not easy way to change the cell order now. But you can make a new seurat object with the cell order you need. 
We will incorporate the cell order changing functionality in the future.
