### ISSUE TITLE
splitdotplotGG Error in mutate_impl(.data, dots) :

### ISSUE THREAD

**Issue by sarahwajid** [satijalab/seurat#578]
Hi we have run the immune alignment vignette with success using the vignette provided dataset.
Now when we try to run the same vignette with our own dataset, we get stalled at the splitdotplotGG function with this error (see code, error and traceback):

```R
SplitDotPlotGG(cca_3dpf, genes.plot = "cdc20",
               cols.use = c("blue", "red"), x.lab.rot = T,
               plot.legend = T, dot.scale = 8, do.return = T,
               grouping.var = "treat")
 
Error in mutate_impl(.data, dots) :
  Evaluation error: subscript out of bounds.
In addition: Warning message:
Expected 2 pieces. Additional pieces discarded in 12 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].
 
traceback()
 
13: stop(list(message = "Evaluation error: subscript out of bounds.",
        call = mutate_impl(.data, dots), cppstack = NULL))
12: .Call(`_dplyr_mutate_impl`, df, dots)
11: mutate_impl(.data, dots)
10: mutate.tbl_df(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey",
        palette.use))(20)[avg.exp.scale])
9: mutate(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey",
       palette.use))(20)[avg.exp.scale])
8: function_list[[i]](value)
7: freduce(value, `_function_list`)
6: `_fseq`(`_lhs`)
5: eval(quote(`_fseq`(`_lhs`)), env, env)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
2: data.to.plot %>% separate(col = id, into = c("ident1", "ident2"),
       sep = "_") %>% rowwise() %>% mutate(palette.use = colorlist[[ident2]],
       ptcolor = colorRampPalette(colors = c("grey", palette.use))(20)[avg.exp.scale]) %>%
       unite("id", c("ident1", "ident2"), sep = "_")
1: SplitDotPlotGG(cca_3dpf, genes.plot = "cdc20", cols.use = c("blue",
       "red"), x.lab.rot = T, plot.legend = T, dot.scale = 8, do.return = T,
       grouping.var = "treat")
```

Any ideas on what might be setting off this error in our dataset?

**Comment by sarahwajid** [comment]
RESOLVED. PSA:
Apparently it turned out that you cannot have an underscore (_) in your 'stim' name ids

ctrl@meta.data$stim <- "CTRL"
stim@meta.data$stim <- "STIM"

we used "3dpf_untreated" and "3dpf_ablated"
and that setoff that error.
you're welcome.

**Comment by jasontclee** [comment]
Just to add to this, I also experienced the same error, but the underscores were part of the names I labelled my clusters with (I did not have any underscores with the 'stim' name IDs). After amending the names of the clusters, the issue went away.

**Comment by KoichiHashikawa** [comment]
I have the same error even though I do not have any underscore in my stim name ids and cluster names in tSNE.
Error in mutate_impl(.data, dots): Evaluation error: subscript out of bounds.
Traceback:

1. SplitDotPlotGG(Data.combined, genes.plot = rev(markers.to.plot), 
 .     cols.use = c("blue", "red"), x.lab.rot = T, plot.legend = T, 
 .     dot.scale = 8, do.return = T, grouping.var = "stim")
2. data.to.plot %>% separate(col = id, into = c("ident1", "ident2"), 
 .     sep = "_") %>% rowwise() %>% mutate(palette.use = colorlist[[ident2]], 
 .     ptcolor = colorRampPalette(colors = c("grey", palette.use))(20)[avg.exp.scale]) %>% 
 .     unite("id", c("ident1", "ident2"), sep = "_")
3. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
4. eval(quote(`_fseq`(`_lhs`)), env, env)
5. eval(quote(`_fseq`(`_lhs`)), env, env)
6. `_fseq`(`_lhs`)
7. freduce(value, `_function_list`)
8. function_list[[i]](value)
9. mutate(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey", 
 .     palette.use))(20)[avg.exp.scale])
10. mutate.tbl_df(., palette.use = colorlist[[ident2]], ptcolor = colorRampPalette(colors = c("grey", 
  .     palette.use))(20)[avg.exp.scale])
11. mutate_impl(.data, dots)
