### ISSUE TITLE
FeaturePlot doesn't work with discrete metadata columns

### ISSUE THREAD

**Issue by yeastce11** [satijalab/seurat#5782]
Hi!

I was trying to get feature plots with a column from `meta.data` as a feature, but it looks like there is a problem when the values in the column are discrete. The `DimPlot` seems to be too crowded when grouped by sample, so it would be great to be able to split into several plots but still keep all the cells in each plot. Ideally, I'd like to have 5 different plots (the number of samples) with cells that are colored if they belong to a particular sample and ones that don't to be gray.

Here is the call and the error that I've got:

```
FeaturePlot(data, features="sample")
> ERROR while rich displaying an object: Error: Discrete value supplied to continuous scale
```
And this is how the DimPlot looks like currently:
![image](https://user-images.githubusercontent.com/102174642/160030699-c78f1b06-af41-4b20-8f87-68c3af2ae5fc.png)

**Comment by yeastce11** [comment]
Update: I'm currently dealing with this by creating dummy columns with 0s and 1s for each categorical value of the sample column and then using these as features.

**Comment by yuhanH** [comment]
Hi @yeastce11 
Right. `FeaturePlot` only supports for the continuous variables. `DimPlot` is used to visualize categorical variables. 
Glad to know that you solved this issue.  
In you case, you can alternatively convert 5-class variables into 5 one-hot vectors and then visualize by `DimPlot`
