### ISSUE TITLE
FetchData() does not find variables added to seurat object

### ISSUE THREAD

**Issue by IsmaelMaza** [satijalab/seurat#5786]
Hello!

I'm learning to use Seurat for my project but I have some issues in how to add data to the SeuratObject so it can be found by FetchData() and other functions.

Currently, I am trying to add some cell type information I have in a data frame to my Seurat object but when I use FetchData() to extract the information it says that it cannot find the variable I added.

I recreated the problem with the `data("pbmc_small")` and made a mock data frame with cluster information. 

My cluster data frame has fewer cells than the Seurat Object and some of the barcodes aren't in the Seurat object.
```
library(Seurat)
library(dbplyr)

data("pbmc_small")

cluster <- data.frame(ID = sample(rownames(pbmc_small@meta.data), size = 40), 
                      cluster = rep( c("Epithelial_cells",  "Goblet_cells", "Mast_cells", "Cholangiocytes")))

pbmc_small[["ID"]] <- rownames(pbmc_small@meta.data)

subset_pbmc_small <- subset(pbmc_small, subset = ID %in% cluster$ID)

#My data frame has some barcodes that aren't in the Seurat object so the following code is
#just grabbing the information from the ones I do have in the Seurat object. 
#In this example, it doesn't do much but I added it in case my problem is in this step

subset_pbmc_small_data <- subset_pbmc_small@meta.data
cluster_with_seurat_barcodes <- cluster[cluster$ID %in% subset_pbmc_small_data$ID,] 

#joinning by barcode (Cells) and adding the meta data back to the Seurat object
subset_pbmc_small_data <- left_join(subset_pbmc_small_data, cluster_with_seurat_barcodes)
subset_pbmc_small <- AddMetaData(subset_pbmc_small, subset_pbmc_small_data$cluster, col.name = "Cell_type")
```
Now that the data is inside the Seurat Object I try to use FetchData() to extract the values but it doesn't find the variable
```
Mast_cells <- FetchData(subset_pbmc_small, vars = "Mast_cells")
#Error in FetchData(subset_pbmc_small, vars = "Mast_cells") : 
  #None of the requested variables were found: Mast_cells

#If I look for elements that were already in the object it works fine, for example:
CD79A <-FetchData(subset_pbmc_small, vars = "CD79A") #works
```
My variables are also not detectable with other functions like VlnPlot()

```
VlnPlot(subset_pbmc_small, features = "CD79A", group.by = "Mast_cells")
Error: Cannot find 'Mast_cells' in this Seurat object
```
I have tried to preserve the order and rows of the element in the Seurat so I can add them. I also tried `subset_pbmc_small@meta.data <- subset_pbmc_small_data` instead of AddMetaData() but it doesn't work.

Am I adding the data in the wrong section of the Seurat?
Is there something I need to do before adding extra information?

 I'm happy to provide any further information in case I'm missing any to make my question clear. (I'm still new to posting in Github)

Thank you for your help!

**Comment by yuhanH** [comment]
Thanks Sam for your reply!
Hi @IsmaelMaza 
I am not sure what you are trying to do using `FetchData`.  Like sam mentioned, `Mast_cells` is not a variable,  but is a value in `Cell_type` variable.

> `subset_pbmc_small@meta.data <- subset_pbmc_small_data`
 You can only add data.frame to the `meta.data` instead of the entire seurat object. 
 
You can find more descriptions about `AddMetaData` by  `?SeuratObject::AddMetaData()`.  
Or if you want to get some specific cells, you can try `WhichCells`. In your above example, you get MAST cells by this line
```
WhichCells(object = subset_pbmc_small, expression = Cell_type == 'Mast_cells')
```
FetchData() is used to retrieve dat. You can add conditions after you get the data by `FetchData`.
