### ISSUE TITLE
FindMarkers() and low expressed genes

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#5788]
Hi,

When you use FindMarkers() to find markers of cell types -if I understood correctly- you find genes that are more expressed in that cell type against all the other cell types. logFC and pct1 and pct2 give you indications on how more certain genes are "enriched" in the cell type of interest against the other. 

The problem is that sometimes these genes that pop up as markers are more expressed in the cell type of interest when compared to the other cell types, **but still very low expressed, and so not good markers.**

Is there a way to:
1) set a minimum number of counts for the cell type of interest when running FindMarkers()
2)Visualize the number of counts per gene, per cell type?

For 2) I was trying this method (https://www.biostars.org/p/420841/) but 
write.table(pbmc@assays[["RNA"]]@counts, file='Gene_Count_per_Cell.tsv', quote=FALSE, sep='\t', col.names = TRUE)
gives me the error 
_Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102_

Thank you!

**Comment by jsim91** [comment]
Do the function arguments "min.pct" and "min.diff.pct" not meet your needs? At default, "min.pct" is set to 0.1 which would suggest only genes found in 10% of the cells for any one of the populations being compared are considered. Have you tried increasing this threshold? 

You can always run the function with default values then subset the resulting data frame using the pct.1 and/or pct.2 columns to meet your needs. If you haven't already, I would recommend looking at the function documentation which goes into more detail about the function's inputs and outputs. `?FindMarkers`

**Comment by giorgiatosoni** [comment]
> Do the function arguments "min.pct" and "min.diff.pct" not meet your needs? At default, "min.pct" is set to 0.1 which would suggest only genes found in 10% of the cells for any one of the populations being compared are considered. Have you tried increasing this threshold?
> 
> You can always run the function with default values then subset the resulting data frame using the pct.1 and/or pct.2 columns to meet your needs. If you haven't already, I would recommend looking at the function documentation which goes into more detail about the function's inputs and outputs. `?FindMarkers`

min.pct and pct.1/pct.2 just give an indication of how many cells express the markers but they don't filter for low expression: e.g I can set min.pct to 0.2 and I will get genes found in 20% of the cells, but they can still be very low expressed (in terms of counts in these >20% cells).

**Comment by jsim91** [comment]
I might need correcting here but that's probably fine, although not ideal. An increased sequencing depth will always find you more reads. It's possible that 100% of those cells are expressing the gene but the depth of sequencing only allowed for the instrument to detect the top 20% of expressers. Again, someone correct me if I'm off here.

**Comment by jsim91** [comment]
Also the error you got was likely due to R's inability to allocate enough memory to convert the sparse RNA count matrix to dense format for writing to disk. If you really want to write the entire RNA assay count matrix to disk I would consider the `writeMM` function from the Matrix package.

**Comment by saketkc** [comment]
`FindMarkers` uses normalized data - so things can be differentially expressed even if their absolute counts are low. With shallow sequenced datasets (most of the scRNA-seq datasets) - this is a feature and not a bug. For working with counts matrices, you can use `writeMM` to write the [writeMM](https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/externalFormats.html) function as suggested above.
