### ISSUE TITLE
Suggestions needed for integrating multiple datasets

### ISSUE THREAD

**Issue by huhayahoo** [satijalab/seurat#5789]
(i) I am following a workflow as follows. Kindly let me know if this is correct..

(ii) Secondly, if I use SCTransform() is it necessary or advantageous to regress nUMIs using 
vars.to.regress = c("CC.Score","MitoPercent", "nUMIs") or  not? 

(iii) Thirdly, I have run into a problem where when I try to integrate 44 samples using rpca and reference based integration, clusters are sample specific..i.e. most of all cells in a cluster belong to a SINGLE sample..how, do I overcome this? Should I not use reference based integration as samples are likely to be very different?? or should I try cca instead of rpca??

These are all human patient single nuclei data..I did remove all mitogenes from the matrix as presence of mito reads is just technical contamination and have no biological meaning in in single nuclei RNA seq as compared to single cell RNA seq where they denote apoptotic cell etc.  Kindly let me know how you would proceed in this scenario.

Below is my partial workflow for question (i)

Read10X() & CreateSeuratObject() : to create a Seurat object for each sample

merge()                                           : to merge all Seurat objects into a single Seurat object

PercentageFeatureSet()                  : to calculate percent mito for all cells in all samples

subset()                                           : to perform QC

SplitObject()                                   : to split the merged Seurat object back into individual samples

NormalizeData()                             : using RNA assay...normalized counts stored in $RNA@data (for all features)

CellCycleScoring()                          : using $RNA@data

SCTransform()                                : optional regression if desired (vars.to.regress = c("CC.Score","MitoPercent")...SCT assay  
                                                         with (i) UMI corrected counts in $SCT@counts (for all variable features)
                                                                 (ii) ln(1p) UMI corrected counts  in SCT@data (for all variable features)
                                                                 (iii) scaled counts (Pearson residuals) in scale.data (for only top 3000 variable features
                                                                 (iv) variable features in vars.features (list of top 3000 variable features)

RunPCA(), RunUMAP(), DimPlot()  :  in DImPlot(), use split.by="Sample" to see if samples have different looking UMAP (batch 
                                                          effects)..if so, we need to integrate

integration_features()                    : to find a common set of 3000 variable features for integrating all samples

PrepSCTIntegration()                     : to calculate Pearson residuals for missing features (since each sample has different set of top 
                                                         3000 variable features for which Pearson residuals were calculated, the Pearson residuals for 
                                                         missing integration features need to be calculated)

FindIntegrationAnchors()              : to find anchor cells between samples
                                                        (use reduction = "rpca" if samples are not very different,
                                                         use reduction = "cca" if samples are very different,
                                                         and/or reference = c(...) if data set is large

IntegrateData()                              : to integrate all samples (has data for only 3000 integration features)..this assayonly used for 
                                                        visualization purposes, not Differential expression etc

RunPCA(), RunUMAP(), DimPlot()  : Since we batch corrected expression values, we perform PCA and UMAP again...in DimPlot(), 
                                                         use split.by="Sample" to see if samples have similar looking UMAP (no batch effects)

FindNeighbors()                             : to create kNN and SNN graphs using PCA

FindClusters()                                 : to identify clusters

DimPlot()                                       : in DimPlot(), use split.by="Sample" and/or group.by="Sample"...clusters shouldn't be entirely 
                                                         sample specific i.e. all/most cells in a cluster shouldn't come from ONLY one sample

Thank you

**Comment by saketkc** [comment]
> (ii) Secondly, if I use SCTransform() is it necessary or advantageous to regress nUMIs using
vars.to.regress = c("CC.Score","MitoPercent", "nUMIs") or not?

You do not need to regress out nUMIs.


> Thirdly, I have run into a problem where when I try to integrate 44 samples using rpca and reference based integration, clusters are sample specific..i.e. most of all cells in a cluster belong to a SINGLE sample..how, do I overcome this? Should I not use reference based integration as samples are likely to be very different?? or should I try cca instead of rpca??

When using SCT based workflow, we recommend running SCT on each object before merging (it is not clear from your enlisted steps if this is what you are doing versus running SCTransform on the entire object). You can follow [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for an example workflow with two "samples". With 44 datasets, we recommend using reference based or rpca based integration. See [this vigentte](https://satijalab.org/seurat/articles/integration_large_datasets.html) for examples.

Hope this helps. You can reopen with any follow up questions.
