### ISSUE TITLE
Non-reproducible results with cluster numbering in FindClusters()

### ISSUE THREAD

**Issue by skilpinen** [satijalab/seurat#5792]
Problem is this:
Some time ago we used this quite standard process (peaks assay from scATAC):
s.data <- RunUMAP(object = s.data, reduction = 'lsi', dims = 2:30, min.dist=0.05, spread=1.1)
s.data <- FindNeighbors(object = s.data, reduction = 'lsi', dims = 2:30)
s.data <- FindClusters(object = s.data, verbose = FALSE, algorithm = 4, resolution = 1)
DimPlot(object = s.data, label = TRUE, pt.size=1.2) + NoLegend()

with Seurat 4.0.5, Signac 1.4.0, leiden_0.3.9. Set.seed() was set.

This resulted in a certain number for each cluster obviously. Now we tried to run the same code on another machine, same architecture (Intel Mac), and same OS, but with some differences in conda env and in packages. Anyhow, we did install there specifically same Seurat, Signac, and leiden versions. Nevertheless, what happens is that umap projection itself is exactly the same, but no matter what we do, cluster numbers are assigned differently. A same number of clusters and all, but the decision of which number is given to which cluster is different.

Where this code goes to get this numbering? Something we haven't been able to standardize between the machines. We have been reading the source code but yet not found a reason for this.

It is quite a big problem now as our student can't take the project into his computer to carry on with it.

**Comment by skilpinen** [comment]
We further narrowed this down, same does not happen with algorithm=1 (Louvain), thus the difference seems to originate from Leiden. Any info on what else needs to be same version than just leiden_0.3.9 in R? I guess this goes then to python side?

**Comment by jsim91** [comment]
I see that you set the seed but can you replicate another simple pseudorandom process across these two machines? Try `set.seed(123); sample(1:100,20)`. If run on both machines, do you get the same result?

**Comment by rsatija** [comment]
Cluster numbers are assigned by the size of the clusters. If there is a minor difference in the clustering solution, then there can be differences in the exact assignment of clusters. Especially when calling Leiden (which calls a python subpackage), the python version and installation must be identical to return numerically identical results.
