### ISSUE TITLE
DifferentialExpression and vars.to.regress

### ISSUE THREAD

**Issue by wang-research** [satijalab/seurat#580]
Hi,

I have a confusing question. As far as I know, Seurat uses NormalizedData (stored at the ‘data’ slot) for differential expression analysis and finding markers for each cluster. I wonder why it doesn’t use that have been done by regressing out annoying factors such as nUMI, sample index (batch effect). I can understand it doesn’t use the centered and scaled data.

Could someone give me some arguments about not using that have been regressed out confounding factors?

Thank you very much!

**Comment by satijalab** [comment]
You can use the MAST DE test to perform differential expression while correcting for 'unwanted' sources of variation.
