### ISSUE TITLE
annotation, label transfer and unimodal UMAP projection: usage in harmony-integrated umap based on SCT

### ISSUE THREAD

**Issue by realzehuali** [satijalab/seurat#5802]
Thanks for any help!
The unimodal UMAP projection tutorial is used in CCA-integrated umap based on RNA
Could you show me how to use unimodal UMAP projection in harmony-integrated umap based on SCT?
Thanks for any help!

**Comment by yuhanH** [comment]
Here is an example about mapping query data to harmony-integrated umap. https://github.com/immunogenomics/harmony/pull/144
You need to add the PCA feature loadings to the harmony feature loadings.
