### ISSUE TITLE
loop through celld IDs when running FindMarkers()

### ISSUE THREAD

**Issue by chrismahony** [satijalab/seurat#5804]
My Seurat object has the following IDs in aggr$cm_clusters:
[1] "DN2"      "dHSPCs"   "eryProg"  "ery"      "macs"     "neutr"    "NKTcells" "Bcells"   "multi"    "kidney"  
[11] "endo"     "DN1"   

I am trying to set up a loop so that FindMarkers will run compare MUT vs WT in each cluster ID:

Idents(aggr) <- aggr$cm_clusters
for (i in c(DN2, neutr, ery)){
    marker_i <- FindMarkers(aggr,
                ident.1 = "MUT",
                ident.2 = "WT",
                verbose = TRUE,
                group.by="sample",
                subset.ident = i)
    assign(paste0("inmunes.", i), marker_i)
}

But so far nothing has worked. If you could help I would really appreciate it, thanks,
Chris

**Comment by torkencz** [comment]
Hi, from what I am seeing maybe doing for (i in levels(as.factor(aggr$cm_clusters)){ etc.} should work. I think you need to be looping through a vector of strings. Let me know if this works.
