### ISSUE TITLE
FeatureScatter x-axes is unreadable

### ISSUE THREAD

**Issue by nhatas** [satijalab/seurat#5805]
I am following the Seurat pbmc3k tutorial and am running into an issue when using `FeatureScatter`. The X axes font is too big and is causing the values to be unreadable due to overlap.

My code I am running is:
```
plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt", pt.size = 0.1)
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", pt.size = 0.1)
plot1 + plot2
```

Below is the output I am receiving in RStudio:
![image](https://user-images.githubusercontent.com/53345425/161132194-a350ccd5-99eb-4e39-a3ab-5110248dbcd2.png)

Any help would be appreciated. Thank you

**Comment by torkencz** [comment]
I would change the axis text angle. You can just use +theme(axis.text.x=element_text(angle=90,hjust=1)).
