### ISSUE TITLE
Load10X_Spatial_Mtx

### ISSUE THREAD

**Issue by johnyaku** [satijalab/seurat#5806]
It would be useful to have a variant on `Load10X_Spatial()` that could construct a count matrix from an MTX directory rather than an `.h5` file, which is not always available. This could either be implemented by a new function - say `Load10X_Spatial_Mtx()` - or by providing additional options and functionality to `Load10X_Spatial`.

See [this issue thread](https://github.com/Swarbricklab-code/BrCa_cell_atlas/issues/3) for a discussion of this problem and an example code snippet of how a spatial Seurat object can be constructed in the absence of an `.h5` file.

**Comment by mojaveazure** [comment]
You can use `Read10X` to read in the MTX files and `Read10X_Image` to read in the image data; you will then have to create the `Seurat` object yourself and add the image to said object

```R
# Load in expression data and create a Seurat object
counts <- Read10X("/path/to/10x_dir")
object <- CreateSeuratObject(counts)
# Load in the image data
img <- Read10X_Image("/path/to/10x_image_dir")
# Correct the image data to match the Seurat object
img <- img[Cells(object)]
DefaultAssay(img) <- DefaultAssay(object)
# Add the image to the object
object[["slice"]] <- img
```

While we don't have plans to build a version of `Load10X_Spatial` that works on MTX files, we would welcome a PR to include such functionality

**Comment by ElyasMo** [comment]
I wrote a function that do the job (reading in the spatial data as a Seurat object directly from raw count matrix and spatial folder of spaceranger output).

You can install it as a R package called ST.mtx from my github:

https://github.com/ElyasMo/ST.mtx
