### ISSUE TITLE
Dotplot

### ISSUE THREAD

**Issue by raman91** [satijalab/seurat#5807]
![qGBLg](https://user-images.githubusercontent.com/8286779/161178016-05991472-36d4-4247-9789-3cb162a2d64a.jpg)

Hi, I want to create a dot plot (multiple entry for each feature side by side) as attached in seurat. Is it possible to do this in seurat? 
Thanks

**Comment by yuhanH** [comment]
HI
You can do similar things by Violin plot.
```
VlnPlot(pbmc_small, features = 'LTB', group.by = 'groups', split.by = 'letter.idents')
```
![image](https://user-images.githubusercontent.com/29529544/161277635-8aa49743-3f23-488e-867b-e090a8ed9385.png)

**Comment by yuhanH** [comment]
Do you mean a stack violin plot? or a condition-grouped dot plot?

For the stack violin plot, you can try this script.
```
library(ggplot2)
VlnPlot(pbmc_small, features = c('LTB', 'GNLY'), group.by = 'RNA_snn_res.1', stack = T , flip = T)
```
For the condition-grouped dot plot, you can have a look at this vignette. https://satijalab.org/seurat/articles/integration_introduction.html
