### ISSUE TITLE
Analysing 2 datasets with different nFeature_RNA profile

### ISSUE THREAD

**Issue by julierodor** [satijalab/seurat#5808]
Hi,
We have 2 datasets: dtp and dtm. In addition to having difference in their number of cells (2000 vs 28000 cells), I have also noticed they have a different profile of nFeature_RNA (and nCount). dtm have nFeature_RNA ranging from 500 to 2500 while dtp have most cells with nFeature around 500.
I am not sure what is the reason for this difference. Can it be technical? low quality sample? low quality library?
Is there a way to analyse these 2 datasets together? I have tried merging the datasets, integration and integration based on SCTranform with vars.to.regress="nFeature_RNA".
The UMAP and clustering looks ok but most cluster markers have a lower expression in dtp. I suspect it might be linked to the difference in nFeature.
Any suggestion on how to analyse these datasets? Any suggestion on how to troubleshoot the sequencing if we want to repeat the experiment?
Julie

![image](https://user-images.githubusercontent.com/22321838/161228166-1384768e-4e53-4f09-8165-1a1485c25b42.png)

**Comment by saketkc** [comment]
The difference in sequencing depth can arise from a variety of technical (+biological) factor. While it is hard to comment without knowing the full context, your enumerations cover the possible explanation. 
I would recommend running SCTransform separately on the two datasets using the `v2` workflow as in this [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), which covers normalization, differential expression and visualization for two different libraries (similar to your use case). You do not need to regress nCount_RNA or nFeature_RNA.
