### ISSUE TITLE
What is drawn first in tSNE plot?

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#581]
Dear all,

even though I can influence the order in the legend of a tSNE plot by introducing factor levels, it seems that this does not influence the order of plotting. I am trying to show the distribution of one sample (red dots) in the context of all other cells (grey dots) in a tSNE. But I can hardly see them because they seem to be overpainted by the other samples (grey dots).

How can I fix this? Thanks!! Chris

**Comment by leonfodoulian** [comment]
Hi,

The easiest solution is to reorder the rows of the `ggplot2` data. Obviously, in your case, you should replace the `plot$data$ident` by the relevant column name in the `ggplot2` data.

```R
require(Seurat)

# Plot t-SNE and return ggplot2 object
plot <- TSNEPlot(object = pbmc_small, do.return = TRUE)

# Order ggplot2 data rows by 'ident'
plot$data <- plot$data[order(plot$data$ident), ]

# Display plot
plot
```

Hope that helps!

Best,
Leon

**Comment by balthasar0810** [comment]
Thanks, Leon, you are the fastest!!!

----------
Dr. med Dipl.-Math. Christian Hinze

AG Schmidt-Ott
Max-Delbrück-Centrum
für Molekulare Medizin (MDC) Berlin-Buch
Robert-Rössle-Str. 10
13125 Berlin
Tel.: +49 30 9406 3240
christian.hinze@mdc-berlin.de

Medizinische Klinik mit Schwerpunkt Nephrologie
Charité - Universitätsmedizin Berlin
Campus Benjamin Franklin
Hindenburgdamm 30
12203 Berlin
Tel. +49 30 8445 2441
christian.hinze@charite.de<mailto:kai.schmidt-ott@charite.de>
________________________________
Von: Leon Fodoulian [notifications@github.com]
Gesendet: Sonntag, 1. Juli 2018 13:36
An: satijalab/seurat
Cc: balthasar0810; Author
Betreff: [ext] Re: [satijalab/seurat] What is drawn first in tSNE plot? (#581)


Hi,

The easiest solution is to reorder the rows of the ggplot2 data. Obviously, in your case, you should replace the plot$data$ident by the relevant column name in the ggplot2 data.

require(Seurat)

# Plot t-SNE and return ggplot2 object
plot <- TSNEPlot(object = pbmc_small, do.return = TRUE)

# Order ggplot2 data rows by 'ident'
plot$data <- plot$data[order(plot$data$ident), ]

# Display plot
plot

Hope that helps!

Best,
Leon
