### ISSUE TITLE
In Situ Sequencing

### ISSUE THREAD

**Issue by rocketeer1998** [satijalab/seurat#5813]
Hi there. Thanks for your excellent work!  Now that the pipeline for MERFISH has been invented and benchmarked, I'd like to know when an analysis pipeline used for in situ sequencing (ISS) will be available because ISS and MERFISH are quite similar.

**Comment by AustinHartman** [comment]
Hi, the latest version of Seurat on CRAN provides support for multiple image-based spatial transcriptomic methods. If there is a particular method of type of data you are having trouble loading into a Seurat object, feel free to open a separate issue.
