### ISSUE TITLE
Mismatch results between seurat data using ENSEBML gene id and mouse gene symbol

### ISSUE THREAD

**Issue by karouro** [satijalab/seurat#5816]
Hi. I'm a beginner of scRNAseq analysis.
I have four scRNAseq count data of mice cells generated from ICell8 system.
Each count data include 55,367 unique gene features. 
Then, using ENSEMBL gene id and mouse gene symbol respectively, I created seurat object, integrated the data, and performed the integrated analysis according to the vignette.

The both seurat objects using ENSEMBL gene id and mouse gene symbol are the same except for the feature name. However, the results of the integrated analysis are not the same.
Could you please give me some help?

> seurat_Tcell.combined <- ScaleData(seurat_Tcell.combined, verbose = FALSE)
> seurat_Tcell.combined <- RunPCA(seurat_Tcell.combined, npcs = 50, verbose = FALSE)
> seurat_Tcell.combined <- RunUMAP(seurat_Tcell.combined, reduction = "pca", dims = 1:15)
16:43:00 UMAP embedding parameters a = 0.9922 b = 1.112
16:43:00 Read 4545 rows and found 15 numeric columns
16:43:00 Using Annoy for neighbor search, n_neighbors = 30
16:43:00 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
16:43:00 Writing NN index file to temp file /tmp/Rtmpl1OVKq/file24960c18110
16:43:00 Searching Annoy index using 1 thread, search_k = 3000
16:43:01 Annoy recall = 100%
16:43:02 Commencing smooth kNN distance calibration using 1 thread
16:43:05 Initializing from normalized Laplacian + noise
16:43:05 Commencing optimization for 500 epochs, with 192558 positive edges
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
16:43:10 Optimization finished
> seurat_Tcell.combined <- RunTSNE(seurat_Tcell.combined, reduction = "pca", dims = 1:15, seed.use = 1, 
+                                  perplexity = 30, max_iter = 1000, theta = 0.5, eta = 200, num_threads = 0)
> seurat_Tcell.combined <- FindNeighbors(seurat_Tcell.combined, reduction = "pca", dims = 1:15)
Computing nearest neighbor graph
Computing SNN
> seurat_Tcell.combined <- FindClusters(seurat_Tcell.combined, resolution = 1.0)
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 4545
Number of edges: 175092

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.7511
Number of communities: 11
Elapsed time: 0 seconds

> seurat_Tcell2.combined <- ScaleData(seurat_Tcell2.combined, verbose = FALSE)
> seurat_Tcell2.combined <- RunPCA(seurat_Tcell2.combined, npcs = 50, verbose = FALSE)
> seurat_Tcell2.combined <- RunUMAP(seurat_Tcell2.combined, reduction = "pca", dims = 1:15)
16:43:34 UMAP embedding parameters a = 0.9922 b = 1.112
16:43:34 Read 4545 rows and found 15 numeric columns
16:43:34 Using Annoy for neighbor search, n_neighbors = 30
16:43:34 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
16:43:34 Writing NN index file to temp file /tmp/Rtmpl1OVKq/file2496e0c4115
16:43:34 Searching Annoy index using 1 thread, search_k = 3000
16:43:35 Annoy recall = 100%
16:43:36 Commencing smooth kNN distance calibration using 1 thread
16:43:38 Initializing from normalized Laplacian + noise
16:43:38 Commencing optimization for 500 epochs, with 192538 positive edges
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
16:43:43 Optimization finished
> seurat_Tcell2.combined <- RunTSNE(seurat_Tcell2.combined, reduction = "pca", dims = 1:15, seed.use = 1,
+                                   perplexity = 30, max_iter = 1000, theta = 0.5, eta = 200, num_threads = 0)
> seurat_Tcell2.combined <- FindNeighbors(seurat_Tcell2.combined, reduction = "pca", dims = 1:15)
Computing nearest neighbor graph
Computing SNN
> seurat_Tcell2.combined <- FindClusters(seurat_Tcell2.combined, resolution = 1.0)
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 4545
Number of edges: 176550

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.7521
Number of communities: 10
Elapsed time: 0 seconds

seurat_Tcell.combined is a seurat object that have ENSEMBL id, and seurat_Tcell2.combined is a one that have gene symbol.
I confirmed that there are no duplications in gene features.

Thanks!

**Comment by saketkc** [comment]
Are the input matrices exactly the same? You can generally have multiple gene ids associated with a gene symbol. Also, the only difference I can see above is in the number of clusters (which can be for multiple reasons including starting from different number of input features). If you can provide a more complete code example (with plots), that would help.

**Comment by karouro** [comment]
[Rplot01.pdf](https://github.com/satijalab/seurat/files/8590232/Rplot01.pdf)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
