### ISSUE TITLE
Subsetting Seurat object based on HTO counts matrix

### ISSUE THREAD

**Issue by sloanlewis** [satijalab/seurat#5817]
Hi, 

Is there a way I can subset my seurat object based on the expression of one/a few of my HTO barcodes?
For example, I would want to have the new object have >1000 counts from either HTO-A, HTO-B, OR HTO-C.
Any guidance is appreciated! Thanks!

**Comment by yuhanH** [comment]
hi 
Sure. You can use `WhichCells` to select what cells you need and use `subset` to get the match seurat object.
For example, i only want cells with GNLY RNA counts bigger 2. 
```
pbmc_small.sub <- subset(pbmc_small, cells =  WhichCells(pbmc_small,expression = GNLY > 2,  slot = "counts"))
pbmc_small.sub[['RNA']]@counts['GNLY',]
```
