### ISSUE TITLE
Analysis of Differential Expression Using Batch-Integrated Datasets

### ISSUE THREAD

**Issue by HumzaHemani** [satijalab/seurat#5818]
Hi,

We want to perform differential expression of integrated single-cell data. Is it appropriate to use the integrated values for this, or would the dependencies between data points integration introduces make it inappropriate to use for differential expression, and therefore we should use unintegrated data?

Thanks!

**Comment by torkencz** [comment]
We recommend doing all DE on unintegrated data, but with the clusters identified via the integration.
