### ISSUE TITLE
Error with ImageDimPlot

### ISSUE THREAD

**Issue by Chengwei94** [satijalab/seurat#5819]
Hi, I am trying out the new image spatial toolkit with my own dataset, and I met with some problems

wt1.crop <- Crop(seurat_ns[["fov1"]], x = c(-6000, 0), y = c(-25000, -30000))
seurat_ns[["fov_wt1"]] <- wt1.crop
DefaultBoundary(seurat_ns[["fov_wt1"]]) <- "centroids"
DefaultAssay(seurat_ns) <- "Nanostring"
ImageDimPlot(seurat_ns, fov = "fov_wt1", group.by = "seurat_clusters")

> ImageDimPlot(seurat_ns, fov = "fov_wt1", group.by = "seurat_clusters")
Error in df[df$cell %in% cells, , drop = FALSE] : 
  incorrect number of dimensions

I have checked the Cells(seurat_ns) and Cells(fov_wt1) and they overlap
Addon: It seem that the error is with the underscore in the assay name, since theres a str_split by underscore in the code (Not sure if its intended) 

Furthermore , I found that the LoadNanostring needs the segmentation file to work. Is there a way to obtain the segmentation file  from the images?

**Comment by An17aV0** [comment]
Hello @alikhuseynov , 
I ran into this issue with my Xenium data today.
Molecules would not plot using ImageDimPlot if the names(seurat_obj@images) contained underscores. I don't get an error; it just doesn't plot the specified molecules. It worked when I renamed the fovs.

I am using 
Seurat_5.3.0      
SeuratObject_5.1.0

**Comment by EduardGhemes-ICR** [comment]
> Hello [@alikhuseynov](https://github.com/alikhuseynov) , I ran into this issue with my Xenium data today. Molecules would not plot using ImageDimPlot if the names(seurat_obj@images) contained underscores. I don't get an error; it just doesn't plot the specified molecules. It worked when I renamed the fovs.
> 
> I am using Seurat_5.3.0 SeuratObject_5.1.0

Hi all,

I confirm that molecules are not plotted if the fov have underscores. By replacing the underscores with dashes, the ImageDimPlot function plots the molecules as expected.
