### ISSUE TITLE
FeaturePlot Issue

### ISSUE THREAD

**Issue by rylandmortlock** [satijalab/seurat#582]
Hi, I am using Seurat to analyze large bone marrow datasets from the Human Cell Atlas - https://preview.data.humancellatlas.org/.

I have a Seurat object for a single patient with the results of PCA and tSNE stored in the object and I am trying to create a feature plot based on canonical B cell markers:
```R
filename <- 'bm1_object_PCA_tSNE.rds'
bm <- readRDS(filename)
FeaturePlot(object = bm, features.plot = c("MS4A1", "CD79A", "CD79B", "IGKC"),
            cols.use = c("grey", "blue"), reduction.use = "tsne")
```
Here is the error I get:
```R
Error in data.expression[vars.all[gene.check], cells.use, drop = FALSE] : 
  invalid or not-yet-implemented 'Matrix' subsetting
```
The problem should not be in the tSNE because I can create a tSNE plot with no issues. And I checked that all of the features I plotting have expression within scaled data. any help is appreciated. 

I have the most recent version of Seurat.

**Comment by mojaveazure** [comment]
This is happening in `FetchData`, not `FeaturePlot`; can you run `FetchData` on each of your features independently of one another?

**Comment by rylandmortlock** [comment]
Thanks for the quick reply! I can run FetchData on each of my features independently. If I run it on the 4 genes that I want to display in a feature plot:

MS4A1 <- FetchData(object = bm, vars.all = 'MS4A1', use.scaled = TRUE)
CD79A <- FetchData(object = bm, vars.all = 'CD79A', use.scaled = TRUE)
CD79B <- FetchData(object = bm, vars.all = 'CD79B', use.scaled = TRUE)
IGKC <- FetchData(object = bm, vars.all = 'IGKC', use.scaled = TRUE)

Then, I get the expected result: 4 matrices, each 1 (gene) x 39658 (cells)

**Comment by rylandmortlock** [comment]
Also, in case it helps, the FeaturePlot function works when my features.plot is a Principal Component such as 'PC1' or a piece of metadata such as 'nGene'. The error only occurs when the command passed to features.plot is a gene name or vector of gene names.

**Comment by mojaveazure** [comment]
Can you try running through all combinations of these genes? What's going wrong is `FetchData` isn't able to handle multiple genes, not dimensional reductions or anything in `object@meta.data`; I don't know if this is generally multiple genes or certain combinations of genes. You can use the following powerset function to generate all combinations of genes; please run `FetchData` on each entry in the resulting list.

```R
powerset <- function(x) {
  x <- unlist(x = x, recursive = TRUE)
  x <- lapply(
    X = 1:length(x = x),
    FUN = function(m) {
      return(as.list(x = as.data.frame(x = combn(x = x, m = m))))
    }
  )
  x <- unlist(x = x, recursive = FALSE, use.names = FALSE)
  x <- lapply(X = x, FUN = as.vector)
  return(x)
}
```

**Comment by rylandmortlock** [comment]
Thanks for the help. Running FetchData on all combinations of my 4 genes from the powerset function works fine for any combination. Yet the FeaturePlot function still does not work. Even for a single gene, the FeaturePlot function does not work with the same error message.

**Comment by rylandmortlock** [comment]
I still have not resolved this issue - I'm not sure if it is due to the size of the dataset, but it just seems FeaturePlot function does not want to work for genes.

In case anyone is having the same issue, I wrote the following workaround to just add the expression of genes of interest to the metadata then create the feature plot. 

`# Load object
bm <- readRDS(filename)

# Set gene list (what genes we want to feature plot)
my.genes <- c('MS4A1','CD79A','CD79B','IGKC')
my.genes2 <- c('MS4A1.','CD79A.','CD79B.','IGKC.') # Dot is added so FeaturePlot can recognize it in metadata not the gene name

#Fetch data
my.data <- as.data.frame(FetchData(object = bm, vars.all = my.genes, use.scaled = TRUE))
colnames(my.data) <- my.genes2

# Add metadata
bm <- AddMetaData(object = bm, metadata = my.data)

# Feature plot
pdf(plot_name)
FeaturePlot(object = bm, features.plot = my.genes2,
            cols.use = c("grey", "blue"), reduction.use = "tsne")
dev.off()`

**Comment by XiaoliMa** [comment]
Hi, I am using seurat to run three thousands cells. I used the command: FeaturePlot(object = pbmc, features.plot = "GL2", do.hover = FALSE), everything was fine and I can get nice figures. When I run (object = pbmc, features.plot = "GL2", do.hover = TRUE), there is nothing report, why cannot I get a interactive graph?

**Comment by leafyes** [comment]
@XiaoliMa Have you solved the problem in not plotting the interactive graph ? I also have this problem, Could you help me?
