### ISSUE TITLE
Hos is computed the Average Gene expression from the cell counting?

### ISSUE THREAD

**Issue by vbianco283** [satijalab/seurat#5826]
Hello, let's assume I have a file with the number of transcript counts (nCount_RNA) per cell of given gene "A"; that all the cell belong to the same identity class and that are clean data (removed empty droplets or other stuff)
What the function AverageExpression() does is just to compute the ratio between the total number of transcript counts of the gene "A" and the total number of cells ?
I'm asking because I tried to compute "by hand" (with awk and bash scripting) the gene expression and I get different results with respect to what I get with AverageExpression().
thanks in advance for any help

Best

V

**Comment by longmanz** [comment]
Hi, 
By default, the AverageExpression() uses the "data" slot to calculate the average. Since you are calculating the average based on the raw counts, to obtain the same results, you will need to set the slot to "counts" in AverageExpression().
