### ISSUE TITLE
compatibility with an upcoming version of `scattermore`

### ISSUE THREAD

**Issue by exaexa** [satijalab/seurat#5827]
Hello!

I'm opening this issue as a notification, because Seurat is listed [here](https://cran.r-project.org/package=scattermore) among the packages that use `scattermore` for plotting. @teri934 has been working on some new cool functions for scattermore (much more plotting flexibility, complete removal of overplotting artifacts, beautiful density plots, faster rendering of high-DPI big points, point shapes and lines, possibilities for parallel processing, ...) which involved a rather complete rewrite of the package. I thought it would be useful to check with package users before we release the new version, so that there's time to either report issues/incompatibilities or install proper version bounds to avoid an incompatible dependency upgrade.

The change is being prepared in a [pull request here](https://github.com/exaexa/scattermore/pull/10), and the new version can be installed from [this repository](https://github.com/teri934/scattermore), e.g. using `devtools::install_github('teri934/scattermore')`. The **API should be backwards compatible** and (after we merge a few more fixes) the performance should be on-par or better than with ye old scattermore. So I expect minimal disturbance to other packages, but better check twice :]

In case you find any problems with the new version, please report either here or in the `scattermore` repository so that we can make sure the upcoming release doesn't break anything. I hope to upload it to CRAN in less than a month, versioned as `scattermore-1.0` (the current version is `0.8`). If everything seems okay to you, feel free to close this issue.

Thanks & best!
-mk

**Comment by saketkc** [comment]
Thanks @exaexa for keeping us informed. We will check with the latest version once it is up.

**Comment by exaexa** [comment]
@saketkc perfect :] The new version is now merged in `master`, we will continue improving it towards a CRAN release sometime next month.

**Comment by saketkc** [comment]
No issues after merging https://github.com/satijalab/seurat/commit/b98aad116e104bb6bed60227269634543380f74a so closing this. Thanks @exaexa!

**Comment by exaexa** [comment]
Perfect, thanks for confirm!
