### ISSUE TITLE
visualization of spatial transcriptome data

### ISSUE THREAD

**Issue by Shiywa** [satijalab/seurat#5830]
well, thanks for your work of ST data. I have a problem about visualization. when I used the function `SpatialFeaturePlot` to visualization a part of ST data, it seems to force the figure to a square, which makes the figure looks incongruous. this problem disappears when I use a Seurat version:4.0.1 but appears after using newer version.

regards

**Comment by AustinHartman** [comment]
Hi, thanks for raising this. In 4.0.2 a change was made to fix the aspect ratio of spatial plots to 1. It sounds like that was actually counterproductive in your case. Are you able to provide a small reproducible example or some screenshots of plots before and after this change was made?
