### ISSUE TITLE
Workflow for integration of multiome Seurat objects

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#5831]
Hi all, 
First of all, thanks for the wonderful Seurat & Signac package! 

I was wondering what is the proper workflow for integration of multiple Seurat objects of multiome data. I have 4 cell sorted populations which was processed with the 10X Multiome kit to generate joint GEX and ATAC libraries. I referred mainly to issue #4015 in which @timoast mentioned that we can integrate the data directly based on the RNA assay. 

My questions thus are: 

1. I processed all 4 of my populations according to the steps in the joint RNA/ATAC analysis (https://satijalab.org/signac/articles/pbmc_multiomic.html) then proceed to integration based on RNA assay; meaning that the WNN has been computed for each dataset. Is this the proper step? 
2. Or I should stop at GEX and ATAC data processing --> integrate all samples by RNA assay --> integrate LSI embeddings? Is this possible? I find that the integration only works on either RNA or ATAC alone. Is there any way we can integrate and use both of the RNA and ATAC data? 
3. Since my dataset is from the same sample, just different populations, is there any need for integration? Or is just merging the samples together followed by calculation of WNN sufficient? 

Thank you! ^^

**Comment by torkencz** [comment]
Hi. At this moment we do not have a method to integrate ATAC and RNA at the same time. I would advise to integrate on the RNA assay and use that to link your datasets together (maybe use integration on your LSI embedding as a sanity check that things worked). As for your last question that is very dependent on how things look after merging. If your cell types align pretty well then there is less of a need for integration.

**Comment by nicodemus88** [comment]
> Hi. At this moment we do not have a method to integrate ATAC and RNA at the same time. I would advise to integrate on the RNA assay and use that to link your datasets together (maybe use integration on your LSI embedding as a sanity check that things worked). As for your last question that is very dependent on how things look after merging. If your cell types align pretty well then there is less of a need for integration.

@torkencz Thank you very much for your reply!

In that case, can I first integrate the RNA data only, then integrate the ATAC data only, and then join the 2 assays together? 

Or 1 other idea I have is to integrate the RNA data only and use that for transcriptome analysis... Next, integrate the ATAC data only, and then bring over the UMAP coordinates from RNA object so that I have the same UMAP structure for ATAC analysis... Would that be reasonable? 

Thank you!

**Comment by jiy11170** [comment]
Hi

> > Hi. At this moment we do not have a method to integrate ATAC and RNA at the same time. I would advise to integrate on the RNA assay and use that to link your datasets together (maybe use integration on your LSI embedding as a sanity check that things worked). As for your last question that is very dependent on how things look after merging. If your cell types align pretty well then there is less of a need for integration.
> 
> @torkencz Thank you very much for your reply!
> 
> In that case, can I first integrate the RNA data only, then integrate the ATAC data only, and then join the 2 assays together?
> 
> Or 1 other idea I have is to integrate the RNA data only and use that for transcriptome analysis... Next, integrate the ATAC data only, and then bring over the UMAP coordinates from RNA object so that I have the same UMAP structure for ATAC analysis... Would that be reasonable?
> 
> Thank you!

Hi tokencz, I am also having similar issue. Could you share me which workflow you found it to be most reasonable? Thank you!
