### ISSUE TITLE
FindVariableFeatures VST

### ISSUE THREAD

**Issue by nservant** [satijalab/seurat#5832]
Here there, 

I just realised that the VST method to select most variable genes is run on the (raw) `@counts` while all others methods are run on (normalized) `@data`.

See
```
   if (selection.method == "vst") {
        data <- GetAssayData(object = object, slot = "counts")
       (...)
    }
    else {
        data <- GetAssayData(object = object, slot = "data")
    }

```

I was wondering what is the rational for that ? and if anyone knows if this is the same in `scanpy` ?
Many thanks

**Comment by phoebee-h** [comment]
Hi, 
I am the user, not from Satija's lab. 
The `@data` stored the normalized value, which could be computed by several method such as: "LogNormalize", "CLR", "RC" or maybe "SCT". For example, if you use "CLR", the MARGIN was set as 1, which means the value was normalized through genes; while "LogNormalize", it computes by each cell.

I think the development team used the `@counts` (raw count) to prevent the misleading value. You can see that the log was taken afterward. 
https://github.com/satijalab/seurat/blob/8da35ba8dc2d60f504f7cf276efd684dc19a418c/R/utilities.R#L1027

Hope this helps. 
Phoebe

**Comment by yuhanH** [comment]
Thanks @phoebee-h  for your nice help. 
Using counts or data slot highly depends how the Find Variable methods are assumed. The detailed description of VST can be found in the method section of [seurat v3 paper](https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub).
In the scanpy [pbmc vignette](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html), they identified variable genes before normalization data as well.
