### ISSUE TITLE
Antibody Hashtag demultiplexing in different samples

### ISSUE THREAD

**Issue by it-tes** [satijalab/seurat#5833]
Hi All, 

I have a question regarding on how to deal with distinct samples with hashtags for specific cell populations. For each sample a library has been prepared separately.
Example: 
sample 1: hash A,B,C
sample 2: hash A,B,C
sample 3: hash A,B,C,D
sample 4: hash A,B,C,E

when performing cellranger count I considered all the feature hashtags for all the samples, but realised that there could be a bias in detecting the presence of false positive hash (example hash D in sample 1 e sample 2), this yield to many doublets when performing HTOdemux. 
Would you suggest to consider only the sample-specific hashtag from the beginning, or for a possible contamination issue I should keep all the hashtag?

Thank you for your time

**Comment by timoast** [comment]
You should demultiplex each hashed experiment separately, since cross-experiment doublets are not possible.
