### ISSUE TITLE
AnnData to Seurat Conversion Error: Error in Convert(pbmc_ad, to = "seurat") :    could not find function "Convert"

### ISSUE THREAD

**Issue by francofelix** [satijalab/seurat#5834]
Hi all, I am having some issues with using Convert while trying to convert anndata from scanty over to a Seurat object. It seems I am able to access anndata through reticulate, and can then pull the the anndata file. Once I try to covert the data to a Seurat object, the convert function can't be found. 

I kept the same df/object names as the tutorial to keep it simple, however the .hfad file is different. I get the dame issue when I download the tutorial data and give it a go.

`install.packages("Convert")
library(anndata)
library(scater)
library(Seurat)
library(cowplot)
library(reticulate)
library(loomR)
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")

ad <- import("anndata", convert = FALSE)
pbmc_ad <- ad$read_h5ad("Seurat.h5ad")
pbmc3k <- Convert(pbmc_ad, to = "seurat")

> ad <- import("anndata", convert = FALSE)
> pbmc_ad <- ad$read_h5ad("Seurat.h5ad")
> pbmc3k <- Convert(pbmc_ad, to = "seurat")
Error in Convert(pbmc_ad, to = "seurat") : 
  could not find function "Convert"
`

**Comment by mojaveazure** [comment]
You must attach SeuratDisk before calling it with
```R
library(SeuratDisk)
```
Also note, `Convert` does not work on files read in via reticulate; it works on the H5AD files and [converts them](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html) to h5Seurat files. You can then read in the h5Seurat file with `LoadH5Seurat`
