### ISSUE TITLE
Percentage of cells expressing a gene per cluster per condition

### ISSUE THREAD

**Issue by pbpayal** [satijalab/seurat#5835]
Hello,

Is there a way to extract and plot the percentage/number of cells expressing a certain gene per cluster and per condition?
I have combined dataset, with two conditions. I am able to do find percentage of cells expressing gene per cluster, but I also want to get per condition. "id" = the clusters that have been identified

```
features = "gene"
a <- DotPlot(object = immune.combined, features = features)
a$data
ggplot(a$data, aes(x=id, y=pct.exp, fill=id)) +
  geom_col() +
  facet_wrap(~features.plot)
```

Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  While not Seurat directly you can use the `Percent_Expressing` function from my package scCustomize: https://samuel-marsh.github.io/scCustomize/articles/Statistics.html#percent-of-cells-expressing-features

Best,
Sam

**Comment by pbpayal** [comment]
Thank you Sam. Its a really nice package and it helped me to look more closely into the numbers.

However, I found a solution using Seurat itself. 

```
a <- DotPlot(object = immune.combined, features = features, split.by = "stim")
a$data
ggplot(a$data, aes(x=id, y=pct.exp, fill=id)) +
  geom_col() +
  facet_wrap(~features.plot)

```
