### ISSUE TITLE
Label Transfer using Allen M1 and Allen MTG as references

### ISSUE THREAD

**Issue by ChristinaSteyn** [satijalab/seurat#5836]
Good day, 

I have searched and cannot seem to find the problem I am encountering in any previous issues. I have run label transfer on my seurat object (comprising of 10 snRNAseq datasets from the temporal cortex) using both the Allen primary motor cortex (M1) dataset and the Allen middle temporal gyrus (MTG) dataset as a reference. When I use the M1 dataset, all of the nuclei receive an annotation whereas using the MTG dataset results in some nuclei receiving an NA annotation and these appear to be scattered across just about every cluster. I am wondering if there are any parameters I could play with either in the FindTransferAnchors function or the TransferData function that might prevent this from happening? Any advice would be much appreciated!

Kind regards, 
Christina.

**Comment by saketkc** [comment]
Can you provide a bit more context? The 'NA` annotation issue is probably because some cells in your reference are labelled as NA. The M1 dataset is also hosted on [Azimuth](https://azimuth.hubmapconsortium.org/references/#Human%20-%20Motor%20Cortex) where you can simply upload a seurat object.

**Comment by ChristinaSteyn** [comment]
Thank you very much for your assistance. That was correct and I managed to fix the problem by removing the NA annotations from the reference.
