### ISSUE TITLE
Assay for AddModuleScore

### ISSUE THREAD

**Issue by ktong25** [satijalab/seurat#5841]
Hi Seurat team, 

I am wondering which assay (e.g., RNA, SCT or integrated) should be used for AddModuleScore function, especially for an integrated dataset. In previous issues, I have seen answers using RNA or SCT assay (e.g., #4081) or integrated assay (e.g., #1831 ), and it is recommended that for integrated assay, all features should be used when doing integration. 

In issue #4187, it is recommended to calculate cell cycle score (which is based on AddModuleScore) using integrated assay and then regress out cell cycle variation based on integrated assay using ScaleData(). I am also wondering whether using AddModuleScore() to calculate scores for certain gene sets of interest should be done before or after regressing out cell cycle variation here. 

I am also curious if SCT assay would be more appropriate than RNA assay after SCTransform v2 has been released. 

Thank you!

**Comment by torkencz** [comment]
I would recommend RNA and SCT assay as opposed to the integrated assay as imputed values run the risk of masking actual gene  set enrichments. I've not seen comparisons whether RNA and the SCT assay are more adequate for AddModuleScore calculations.
