### ISSUE TITLE
Label transfer: Which assay should I assign to an integrated query dataset when performing "FindTransferAnchors"?

### ISSUE THREAD

**Issue by auroramaurizio** [satijalab/seurat#5843]
Dear all,
thank you for developing such a useful resource.
I am performing label transfer from an integrated reference dataset to an integrated query dataset. Which assay should I impose to the query dataset when performing "FindTransferAnchors"? RNA or integrated? And why? 

I tried both and the prediction slightly change (I assigned integrated to the reference in both tests).

e.g. 

## test1

DefaultAssay(datasetA) = "integrated"
DefaultAssay(datasetB)="integrated"

TI.anchors <- FindTransferAnchors(reference = datasetA, query = datasetB,
                                  dims = 1:30)
predictions <- TransferData(anchorset = TI.anchors, refdata = Idents(datasetA),
                            dims = 1:30)

## test2

DefaultAssay(datasetA) = "integrated"
DefaultAssay(datasetB)="RNA"

TI.anchors <- FindTransferAnchors(reference = datasetA, query = datasetB,
                                  dims = 1:30)
predictions <- TransferData(anchorset = TI.anchors, refdata = Idents(datasetA),
                            dims = 1:30)

Could you kindly explain me when it's advised to use one assay or another during label transfer?
Thank you a lot,
Best,
Aurora

**Comment by saketkc** [comment]
It really depends on what your datasetA is - are there multiple donors/batches that have huge batch effects and hence need to be integrated? If so, you should use the integrated assay for the reference. If not, you can use the RNA or SCT assay.
