### ISSUE TITLE
raster always enabled in VlnPlot

### ISSUE THREAD

**Issue by jhjiang2020** [satijalab/seurat#5845]
Hi,

Just a quick note that there's a bug in `SingleExIPlot` which always turns on rasterization even when `raster=FALSE`. 

```r
  if (PackageCheck('ggrastr', error = FALSE)) {
    # Set rasterization to true if ggrastr is installed and
    # number of points exceeds 100,000
    if ((nrow(x = data) > 1e5) & !isFALSE(raster)){
      message("Rasterizing points since number of points exceeds 100,000.",
              "\nTo disable this behavior set `raster=FALSE`")
    }
    raster <- TRUE
  }
```

![image](https://user-images.githubusercontent.com/75499605/162995984-02690163-c951-4bdd-b0ae-93e5e12f0d90.png)

**Comment by samuel-marsh** [comment]
@jhjiang2020 not member of dev team but just sent PR to dev team to address this issue.

Best,
Sam
