### ISSUE TITLE
does Seurat 4 support FindMarkers using @assays$SCT@scale.data yet?

### ISSUE THREAD

**Issue by wuy33** [satijalab/seurat#5847]
tried to do DGE analysis using @assays$SCT@scale.data with FindMarkers in Seurat 4, however, keeping getting error of "Error in ValidateCellGroups(object = object, cells.1 = cells.1, cells.2 = cells.2,  : Cell group 1 is empty - no cells with identity class ", but the function will run if using RNA count data. I assume Seurat 4 FindMarkers still hasn't integrated to support using SCT scale data? If not, do i just do what has been suggested using RNA count after "NormalizeData"? But isn't Log normalization a bad choice for high expressed genes?

**Comment by yuhanH** [comment]
Hi @wuy33 
We don't suggest you use sct residuals directly to find differential genes when you run the integration. 
You need to run `NormalizeData` on RNA assay before performing differential analysis.

**Comment by saketkc** [comment]
Hi @wuy33, just to add, with v2 regularization you can use the `data` (not the `scale.data`) slot for DE. This [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) shows a related example with two different conditions.
