### ISSUE TITLE
CPM for top genes expressed

### ISSUE THREAD

**Issue by vero18791** [satijalab/seurat#5848]
Hi,

I am just wondering if there is a possibility to extract the top 100 genes just using CPMs and without doing any kind of DE analysis? I am really new to the field and for now all the codes that I have seen are using DE for finding markers or top genes.

Thanks so much!

Best,

**Comment by saketkc** [comment]
I assume you mean top variable features (these are not necessarily the most expressed genes). You can use the [FindVariableFeatures](https://satijalab.org/seurat/reference/findvariablefeatures) function.
