### ISSUE TITLE
Problem with read10X function: 10X data contains more than one type and is being returned as a list containing matrices of each type.

### ISSUE THREAD

**Issue by hakurashiori** [satijalab/seurat#5849]
HI peers,
I'm trying to load 10X data with the required types: barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz; but there was a message saying "10X data contains more than one type and is being returned as a list containing matrices of each type". 
<img width="995" alt="Screen Shot 2022-04-13 at 10 36 16" src="https://user-images.githubusercontent.com/103548302/163088691-baf80aaf-1488-4be2-8268-7d93e75d0969.png">

I tried to figure out the problem and I found that the feature data showed like this:
<img width="969" alt="Screen Shot 2022-04-13 at 10 27 38" src="https://user-images.githubusercontent.com/103548302/163087619-1f1e9af2-49f7-4b94-ab81-05aac4935aff.png">
It seems that the feature name gene expression is separated into to columns while it should be one column for read10X function to run; I'm not sure if this is the key problem and I've been stuck because there is a NULL for dim(pbmc.data) 
<img width="226" alt="Screen Shot 2022-04-13 at 10 43 57" src="https://user-images.githubusercontent.com/103548302/163089696-7dfda197-3769-4d40-8d61-d9b74c65985f.png">
and the following analysis returned many errors.
I'm still trying but I'm really confused, and I would like to ask how it can be fixed;

Thank you in advance!
Shiori

**Comment by timoast** [comment]
As the message says, your data contains multiple assays, each with its own cell x feature matrix, and so the function is returning a list of matrices. You can access each element of the list to get the individual matrices. Example here: https://satijalab.org/signac/articles/pbmc_multiomic.html

**Comment by errcricket** [comment]
@timoast  -- I am having a similar issue but in my case, I am using SoupX to remove contaminant RNA.  I tried manually removing the peak info in the features file and now there is a new error. Rather than introducing new errors by altering 10X output, how can I access the Gene Expression data only?

**Comment by jdmontenegro** [comment]
BTW, this problem also arises if you have gene_names that contain "|" in them. I just had the same error, but after replacing all the "|" with "_" in the features.tsv.gz, read10X works like a charm.

**Comment by jimmyuab** [comment]
> As the message says, your data contains multiple assays, each with its own cell x feature matrix, and so the function is returning a list of matrices. You can access each element of the list to get the individual matrices. Example here: https://satijalab.org/signac/articles/pbmc_multiomic.html

Could you please resend this link?I got same problem, Need your help.Thanks

**Comment by jimmyuab** [comment]
> setwd("E:/single2022/analysis_results_individual_samples/DB_HM_TAC/filtered_feature_bc_matrix")
> SRR780<-Read10X(data.dir = "E:/single2022/analysis_results_individual_samples/DB_HM_TAC/filtered_feature_bc_matrix/")
10X data contains more than one type and is being returned as a list containing matrices of each type.

**Comment by shihsama** [comment]
You‘d better check each feature file. I also encountered such problem, and  the rub is this (see the screenshot)
![screenshot](https://github.com/satijalab/seurat/assets/151040982/1f1d0b43-0954-4d97-8272-ae936bca276c)
