### ISSUE TITLE
NA as pvalues returned for some genes from all.markers <- FindMarkers(patient.control, ident.1 = "mg1", ident.2 = "control1", test.use = "DESeq2", max.cells.per.i dent = 50)

### ISSUE THREAD

**Issue by qicheng-ma** [satijalab/seurat#5851]
Dear Seurat Team,

I found that NA as pvalues returned for some genes (e.g. CSNK1G3)

CSNK1G3 NA      0.0162821874297161      0.136   0.127   NA:

..........
> all.markers <- FindMarkers(patient.control, ident.1 = "mg1", ident.2 = "control1", test.use = "DESeq2", max.cells.per.ident = 50)
converting counts to integer mode
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
> head(all.markers )
                p_val avg_log2FC pct.1 pct.2    p_val_adj
RPS27    9.526229e-16  0.9006943 1.000 1.000 1.741966e-11
RPS28    3.868344e-15  0.9642409 0.993 1.000 7.073654e-11
RPS21    2.298133e-13  0.9047165 0.993 0.995 4.202366e-09
RPL41    1.740115e-11  0.8519134 0.993 0.995 3.181975e-07
RPS29    2.651101e-09  1.0408690 0.986 0.985 4.847803e-05
HLA-DPA1 1.384004e-07  1.0477319 1.000 0.995 2.530789e-03
> write.table(all.markers,file=args[9], quote = FALSE, row.names = TRUE, col.names = TRUE,  sep = "\t" )
> saveRDS(patient.control, file =  args[10] )

I appreciate your help!

**Comment by longmanz** [comment]
Hi, 
Do you also see NA when you switch to other test.use methods ? If not, it might be an issue from DESeq2 package (e.g., see https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#pvaluesNA).

**Comment by qicheng-ma** [comment]
There is no NA value if I used  test.use = "MAST"
