### ISSUE TITLE
Relationship between use.umi in ScaleData and normalization

### ISSUE THREAD

**Issue by agreco92** [satijalab/seurat#5853]
Hi,
First a bit of context: I am trying to regress out some variable using umi-based methods because it has the advantage of returning non-negative scaled values, which are required for some downstream steps in my analysis that require non-negativity. 

I am trying to understand how the functionality (now included in ScaleData) relates to normalization when using negative binomial or poisson models.
In particular, it's not clear to me how "corrected" count data gets normalized after regression. Does it go through a library size normalization? Or simply through a log1p transformation (as the warning message  `failed for gene XXX; falling back to scale(log(y+1))` seems to imply)? I couldn't find a detailed account in the documentation. 

Related to this, is there a way to use other functionalities in Seurat to achieve the same goal (regress-out + normalization + non-negative values)? I suspect that sctransform might be of help here, but I'm not sure of what steps to follow.
 
Thanks a lot for your help!

**Comment by saketkc** [comment]
`ScaleData` is primiarliy designed for LogNormalization based workflow. In SCTransform, to estimate the "corrected counts", we [reverse](https://github.com/satijalab/sctransform/blob/7e9c9557222d1e34416e8854ed22da580e533e78/R/denoise.R#L199) the regression model by replacing the values of latent variables by their median values essentially estimating (by default) what would be the counts if all cells were to be sequenced to a median sequencing depth. You can pass `vars.to.regress = c('mt.percent')` to additionally regress out `mt.percent` or any other latent variable. Passing in a `batch_var` is currently not supported in`SCTransform` but here is a [workflow](http://htmlpreview.github.io/?https://github.com/satijalab/sctransform/blob/supp_html/supplement/batch_correction.html) demonstrating how to do it using sctransform.
