### ISSUE TITLE
DEG analysis between cell types

### ISSUE THREAD

**Issue by TM9013** [satijalab/seurat#5854]
Hello. - Hello.

Thank you for this useful tool.
I am trying to find DEG using findmarkers.
I am using data from cells of differentiation model.
I have added a line "type" to the metadata of the seurat object and named them day0, day1, etc. What code should I use to get the DEG for day0 and others?
I have tried adding the phrase group.by="type" but it does not work.

Here is the content of the seurat object I am using.

![image](https://user-images.githubusercontent.com/94793688/163398920-1b7454bf-3ce9-486b-98fa-8fa2371e6530.png)

Thank you in advance.

**Comment by mojaveazure** [comment]
`FindMarkers` has a [`group.by` argument](https://satijalab.org/seurat/reference/findmarkers#arguments) and should work. If not, please reopen this issue and provide the code you're running and a reproducible example.

`FindAllMarkers` does not have a `group.by` argument, so you'll have to set the active identity class ahead of time
```R
# Save existing identities, optional
object$stash <- Idents(object)
# Set the "type" column to be the active identity class
Idents(object) <- "type"
# Run FindAllMarkers
markers.all <- FindAllMarkers(object)
# Optionally restore the previous identity classes
Idents(object) <- "stash"
```

**Comment by TM9013** [comment]
Thank you very much for your kind attention.
My apologies. I was using FinAllMarkers. 
As you pointed out, specifying the ident worked. 

Thanks!
