### ISSUE TITLE
When using FindClusters, why the number of clusters may decrease as the resolution increases?

### ISSUE THREAD

**Issue by wddyzxxx** [satijalab/seurat#5861]
Hello, Seurat team members, I am a junior undergraduate. I was analysing the umi count data of 46 single cells (each one with 24506 features), when I found that, as the parameter resolution of FindClusters increases, the number of clusters first got bigger but then became fewer.
I use clustree to visualize the whole process. I want to know why this phenomenon happens. And here is the picture.
![clutree](https://user-images.githubusercontent.com/90907990/163658742-39416c58-62c0-41af-a6d9-02cfb20a0900.png)

And here below  is part of the FindClusters information showed on my screen:

`Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.0165
Number of communities: 32
Elapsed time: 0 seconds
30 singletons identified. 2 final clusters.
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 46
Number of edges: 736

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.0050
Number of communities: 32
Elapsed time: 0 seconds`

Thanks!

(P.S. This is the first time that I've put a question here. And English is not my mother language, so I don't know if I describe the question clearly.)

**Comment by timoast** [comment]
I think what happens here is that you end up with all cells in their own cluster, and then we try to merge singletons (clusters composed of one cell) into the neighbouring cluster with the highest connectivity, which in this extreme case results in only 2 final clusters of cells.

This clustering method is nearest-neighbor-based, and it works optimally when the total number of cells in the dataset is substantially larger than the value of k (number of nearest neighbors used). When you have only 46 cells, you can start to see some weird results like this.

**Comment by wddyzxxx** [comment]
Thank you for your explanation. I think I have a better understanding of the parameter k and the nearest-neighbor-based method.
