### ISSUE TITLE
Trouble with intersect function for single cell analysis data

### ISSUE THREAD

**Issue by hakurashiori** [satijalab/seurat#5862]
Hi,
I try to select cell barcodes detected by both RNA and HTO and I use the intersect function, but it showed empty of the value;
I've checked the entry information
<img width="843" alt="Screen Shot 2022-04-16 at 22 20 23" src="https://user-images.githubusercontent.com/103548302/163678548-6217b576-cc83-40ee-9344-dd1e962e5c5a.png">
<img width="999" alt="Screen Shot 2022-04-16 at 22 20 46" src="https://user-images.githubusercontent.com/103548302/163678566-f7a8725d-e68b-4b77-ac2c-0b16f157f353.png">
however when I tried to do intersect, the result showed that it was empty..
<img width="888" alt="Screen Shot 2022-04-16 at 22 22 32" src="https://user-images.githubusercontent.com/103548302/163678648-59233217-9ccf-494d-84f8-3e30efefb1d8.png">

and I have check there is no problems with the intersect function, it worked for general entries just like below
<img width="292" alt="Screen Shot 2022-04-16 at 22 25 51" src="https://user-images.githubusercontent.com/103548302/163678783-916d82d2-7f13-4f39-a05f-6d38c19c254b.png">

I have no idea with this problem;
Is there any method to deal with it?
Thanks a lot!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  It appears the colnames you are comparing are inherently different.  One set has barcode suffix and the other does not.  I would check:

`any(colnames(obj1) %in% colnames(obj2))`

just to be sure there aren’t any overlaps.  If that returns FALSE then I’d suggest checking the underlying data as to the lack of barcode suffixes.

Best,
Sam

**Comment by hakurashiori** [comment]
Hi Sam,
Yeah it indeed returns FALSE.. 
Actually I found it strange about the difference between the two data by the suffixes initially but I wondered why the data are different because the data are originally generated by Cellranger (barcodes&features&matrix) and I have no idea how it could be lack of barcode suffixes, it's really confusing.. I don't know if the problems are about the raw data or the codes QQ 

Thank you very much!
Best regards,
Shiori
