### ISSUE TITLE
Issue with scaling of the average expression between two groups

### ISSUE THREAD

**Issue by vkavaka** [satijalab/seurat#5864]
Dear Seurat team,

we noticed, that by creating the average heatmap out of the object with only two groups, the scaled values remain the same in the binary matter regardless of the genes they are measured for. 

We created the average expression by the function:
object_av <- AverageExpression(object, assay = "RNA", return.seurat = TRUE, verbose = FALSE)

The heatmap in the next step:
heatmap <- DoHeatmap(object_av, features = genes, draw.lines = FALSE, size = 7, raster = FALSE) + 
        theme(text = element_text(size = 20, face = "bold"))

Any ideas how to scale the values in the non-binary matter between two groups? We thought to plot in this case not the scale.data slot, but rather the normalized slot (data). However, it diminishes the value of heatmaps and plotting the z-scores on itself.

**Comment by vkavaka** [comment]
Here the screenshot of the output with the issue:
<img width="355" alt="Screenshot 2022-04-17 at 19 01 41" src="https://user-images.githubusercontent.com/62178768/163724830-9d2762b6-3651-4ade-a600-41a623333fc3.png">

**Comment by saketkc** [comment]
The default for [DoHeatmap](https://satijalab.org/seurat/reference/doheatmap) is to use `scale.data` slot, you can pass `slot="data"` for plotting the unscaled values.
