### ISSUE TITLE
Redo normalization after removal of contaminating genes

### ISSUE THREAD

**Issue by barbarashih** [satijalab/seurat#5866]
I am wondering if I need to redo the NormalizeData and ScaleData steps after removing contaminating genes (such as the haemoglobin genes). Whether I redo the steps appears to make a fair bit of difference to some of the gene expression that I want to compare across sample types (one of my sample type consistently have lower read count per cell).
Also, I am wondering if it is reasonable to put a contaminating gene down as a latent.vars. I am seeing a large amount of contamination from genes highly expressed by other cell types (and should not be expressed in my cell type of interest) that they dominate the results from FindMarkers when I attempted to compare a specific cluster of cells across sample types.

**Comment by torkencz** [comment]
Hi. Yes you can choose to remove those genes and then renormalize or you can include such genes as latent variables after calculating their relative percentage of reads via PercentageFeatureSet().
