### ISSUE TITLE
Analysis of Image-based Spatial Data in Seurat--aspect ratio distorted

### ISSUE THREAD

**Issue by qinxiaoy** [satijalab/seurat#5869]
The aspect ratio in the output of [ImageDimPlot](https://satijalab.org/seurat/reference/ImageDimPlot.html) is distorted... It would be very helpful to fix this.
![image](https://user-images.githubusercontent.com/52108219/164126122-2a4b885c-2412-4633-a946-15aa129d9595.png)

**Comment by AustinHartman** [comment]
Thanks for raising the issue, I think this is a very good suggestion. For now I would recommend using `coord_fixed(ratio = 1)` from ggplot2 to fix the aspect ratio:
`ImageDimPlot(vizgen.obj, fov = "s2r1", cols = "polychrome", axes = TRUE) + coord_fixed(ratio = 1)`

**Comment by AustinHartman** [comment]
There's now an `ImageDimPlot` parameter called `coord.fixed` which defaults to `TRUE` and will fix the aspect ratio to 1
