### ISSUE TITLE
RNA contamination from drop seq single cell rna seq data

### ISSUE THREAD

**Issue by roofya** [satijalab/seurat#587]
I'm wondering if there is a way to remove the effect of rna contamination of some genes? For some genes which is also the markers of one type of cells, is expressed in most of the cells. Thank you so much for your help. 

Best

**Comment by amisharin** [comment]
https://github.com/constantAmateur/SoupX
https://www.biorxiv.org/content/early/2018/04/20/303727

**Comment by roofya** [comment]
SoupX is a pre-processing method.  As such, there are no functions to load Seurat objects as the input.

**Comment by mschilli87** [comment]
This could change with https://github.com/satijalab/seurat/issues/586 :wink:

**Comment by leonfodoulian** [comment]
Hi @roofya,

For the moment, you can extract the required data from the corresponding slot from the Seurat object (i.e. `object@raw.data` or `object@data`, if you need raw or normalised data, respectively), input the data to SoupX, and then replace the data in the Seurat object. 

Best,
Leon

**Comment by roofya** [comment]
@leonfodoulian 
What is the function in SoupX should I  put object@raw.data as input in SoupX? Thank you

**Comment by leonfodoulian** [comment]
Hi @roofya,

I have never used SoupX, so I don't know what functions should be used. You can refer to the documents and webpages that @amisharin shared with you. You can also refer to their [vignette](https://github.com/constantAmateur/SoupX/tree/master/vignettes) that you can find in their GitHub page. This, nevertheless, goes beyond the scope of the Seurat package.

Best,
Leon
