### ISSUE TITLE
Question about invalid parameters

### ISSUE THREAD

**Issue by hahahah-single** [satijalab/seurat#5870]
My Seurat version is 3.2.2.When I use FindNeighbors function I find a parameters:force.recalc = FALSE,But I don't know what this is for ,it is not passed a variable when using FindNeighbors .I use TRUE or FALSE, the returned results seem to be the same when I use different PCs many times.I would like to ask if this parameter has no practical effect？

**Comment by yuhanH** [comment]
Thanks for pointing this out. We will remove this parameter soon.

**Comment by hahahah-single** [comment]
Thanks @yuhanH So setting force.recalc = FALSE or force.recalc = TRUE when using FindNeighbors  function will not affect the final result,is this correct?

**Comment by hahahah-single** [comment]
Hi everyone , So setting force.recalc = FALSE or force.recalc = TRUE when using FindNeighbors function will not affect the final result,is this correct?

**Comment by yuhanH** [comment]
right. There are no difference.
