### ISSUE TITLE
DotPlot average expression legend with split.by funciton

### ISSUE THREAD

**Issue by alisonmoe** [satijalab/seurat#5871]
Is there a way to have both average expression legends on a DotPlot when using the split.by function for Seurat v4? From previous posts (#1541) it looks like it was available in Seurat v2 but not v3.

**Comment by saketkc** [comment]
This is currently not supported. I will close this for now, but you can try one of the suggestions in [this answer](https://github.com/satijalab/seurat/issues/2487#issuecomment-655526414).
