### ISSUE TITLE
Doheatmap scalebar never shows negative values

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#5874]
Hello! May I ask for your help please? I have seen the examples of other people that when they conduct Doheatmap(), their scalebar reflects a negative to positive range. In my case, it is always zero to positive even though the result of my FindMarkers() has both negative and positive avglog2FC. 

`head(SEURAT)
`![image](https://user-images.githubusercontent.com/68268222/164512107-760a6157-5d4b-4ac7-bfb6-6f9b2022096f.png)

`SEURAT_MARKERS <- FindAllMarkers(SEURAT, only.pos = F, min.diff.pct = 0.10) 
`![image](https://user-images.githubusercontent.com/68268222/164512428-756c0afc-4d79-4900-ac16-311641c8f45b.png)

`SEURAT@assays$RNA@scale.data <- scale(SEURAT@assays$RNA@data, scale = TRUE)
`
`top <- head(SEURAT_MARKERS, 30)
`
`DoHeatmap(SEURAT, features = top$gene, label = TRUE) + theme(axis.text.y = element_text(size = 10)) + scale_fill_gradientn(colors = c("green", "black", "red"))`
![image](https://user-images.githubusercontent.com/68268222/164513065-8220e948-cdbe-4446-84ab-172eb7a16aeb.png)

As you can see, there were negative fold change values, but here in the Doheatmap(), the scalebar always shows zero to positive range. All genes with negative FC are all colored green only which is zero I the color scale. 

Anyone who can help, please? Thank you!

**Comment by saketkc** [comment]
You can use `scale_fill_continuous(breaks = c(-2,-1, 0,1,2,3), type = "viridis")` for a possible color scheme and control over breaks or pass `breaks =  c(-2,-1, 0,1,2,3)` to your existing gradient command.

**Comment by levinhein** [comment]
Hi @saketkc Thank you for your reply.

Unfortunately, it is still the same. What could have gone wrong?

`DoHeatmap(SEURAT, features = top$gene, label = TRUE) + scale_fill_continuous(breaks = c(-2,-1, 0,1,2,3), type = "viridis")`


RESULT:

![image](https://user-images.githubusercontent.com/68268222/165115892-d4ca2e76-6b57-4c89-93c6-e8f1017e01d6.png)

**Comment by saketkc** [comment]
Can you try with `scale_fill_continuous(breaks = c(-.5, 0,1,2,3), type = "viridis")` - basically using the minimum in your dataset as one of the breakpoints.

**Comment by levinhein** [comment]
Hello, Tried that too and still the same, does not reflect the negative foldchange pattern.


`DoHeatmap(SEURAT, features = top$gene, label = TRUE) + scale_fill_continuous(breaks = c(-.5, 0,1,2,3), type = "viridis")
`
![image](https://user-images.githubusercontent.com/68268222/165118234-380547bf-da8c-402b-a1ae-984a6fc83f7a.png)

**Comment by saketkc** [comment]
What does the distribution of scale.data values look like? Here's an example with `pbmc_small`
```
hist(GetAssayData(pbmc_small, assay="RNA", slot="scale.data"))
```

**Comment by levinhein** [comment]
Here. What does this mean?

`hist(GetAssayData(SEURAT, assay="RNA", slot="scale.data"))`

![image](https://user-images.githubusercontent.com/68268222/165120914-ba5b7c36-7d20-4095-8e3b-d77eed9ff905.png)

**Comment by saketkc** [comment]
To clarify, `DoHeatmap` is not plotting log fold changes, but scaled expression value by default (you can specify which slot to plot using the `slot` parameter). The above histogram shows a lot of the negative values in scale.data are near zero (which is also what the heatmap shows).
