### ISSUE TITLE
Data Imputation using ALRA

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5877]
Hi,

I am looking at the ALRA wrapper for data imputation. As far as I can understand, imputation is done on normalized data (SCT assay), while count data (i.e. RNA assay) is untouched.

As far as I understand, this may help for data integration and clustering, but cluster markers (i.e. differential expression between clusters) rely on the RNA assay, which is not affected by the imputation. So, what is the expected improvement in markers identification ? mostly from potentially better defined clusters ? 

Thanks

**Comment by saketkc** [comment]
I think this question is better suited for [ALRA repo](https://github.com/KlugerLab/ALRA), but the general goal here is find a more structured representation of the data while preserving the zeros.
