### ISSUE TITLE
Cell cycle scoring and regression

### ISSUE THREAD

**Issue by ktong25** [satijalab/seurat#5880]
Hi Seurat team,

Thank you for offering such a great tool for single-cell analysis!

The way Seurat's CellCycleScoring() works is that it uses AddModuleScore() to calculate module scores for S and G2M phases for each cell, using a list of S and G2M phase marker genes, and then assign each cell a cell cycle phase by (1)if S score > G2M score, then this cell is S phase (2)if S score < G2M score, then G2M phase (3)if both scores < 0, then G1 phase. The way that AddModuleScore() works is that the score for a given gene list for a given cell is the average expression of this gene list in this cell subtracted by the average expression of a control gene list in this cell, which is selected by binning all genes into (by default) 24 bins according to their average expression levels (averaged across all cells) and then for each gene in the given gene list, taking (by default) 100 control genes from the same bin and combine all these control genes to form the control gene list (after removing duplicate genes). 

I have two questions regarding this procedure:

- When assigning a cell cycle phase to a given cell, if both S and G2M scores are < 0, then it is G1 phase. I am wondering if this could cause some "false-positive" G1 cells, because it might happen that if you also have a G1 marker gene list and calculate G1 score for the given cell, it might also be < 0, and in that case, the cell cycle phase of this cell might be "undecided". Would it be better to have a marker gene list for each of G1, S, G2M phases (or even G1, S, G2, M phases) and calculate their scores for each cell and then select the cell cycle phase with the highest score as the assigned phase, but if all scores are below 0 then assign that cell as "undecided". 

- I feel that the module score that AddModuleScore() calculates depends highly on the selection of control gene list, which in turn highly depends on the cells (or cell composition) in the dataset, because you bin genes based on their average expression levels across all the cells in the dataset. I am wondering, for example, if I have a dataset containing two cell types (both may contain all cell cycle phases), each with very different gene expression profile, meaning that the average expression level of each gene would mean quite differently for the two cell types, then binning genes based on all cells and calculating cell cycle scores based on that would be kind of problematic. It might be better to calculate cell cycle score and assign cell cycle phase for each cell type separately, but when it comes to regressing out cell cycle scores for all cells, this approach would also face the problem that cells are regressed out using scores calculated using different control gene lists, which sounds inconsistent across all cells. I am wondering what is your suggestion on how to calculate and regress out cell cycle scores for a dataset containing two very different cell types (or, for multiple datasets with different cell compositions)?

Thank you!

**Comment by rsatija** [comment]
Thanks for reaching out.

For (1), it is certainly true that there is a potential for false positive G1 calls, but this is why we also provide the score outputs themselves in addition to the calls. You can certainly create additional more granular scores if you like.

For (2), we followed the approach originally described in Tirosh et al, but there are more complex ways that one could calculate a control gene set (including different control genes selected for different cells). If someone does try this and finds any improvement, we would be happy to implement

**Comment by fernandatrancoso** [comment]
Hi! I tried creating additional scores by modifying the CellCycleScoring function to accept more gene lists/ score more phases, but somehow I always get the following error associated to when CellCycleScoring calls AddModuleScore :
Error in base::colMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

But since AddModuleScore seems to call the features set in CellCycleScoring, I don't understand this error. Could you please give an example of how to add more scores/phases to the function? It would be very useful for distinguishing cells that have stationary phases or undergo meiosis 😄
