### ISSUE TITLE
Error in UseMethod(generic = "DefaultAssay", object = object) :    no applicable method for 'DefaultAssay' applied to an object of class "c('data.frame', 'list', 'oldClass', 'vector', 'OptionalList')"

### ISSUE THREAD

**Issue by mbartl13** [satijalab/seurat#5882]
I am getting an error after adding a column to meta data and UpdateSeuratObject as suggested (https://github.com/satijalab/seurat/issues/1946) did not work.

` meta<- tibble::tribble(~orig.ident,  ~sample_name,1, "dn1",2, "d14",  3, "d28",4, "d90")` 
` meta$orig.ident <- as.factor(meta$orig.ident)`
` OBJ_meta <- OBJ@meta.data %>% select(orig.ident) %>% rownames_to_column("barcodes")`
`full_new_meta <- full_join(x = OBJ_meta, y = meta) %>% column_to_rownames("barcodes") %>% select(-orig.ident)`
`DimPlot(OBJ_meta, group.by = "sample_name")`
_Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "c('data.frame', 'list', 'oldClass', 'vector', 'OptionalList')"_

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  According to code you pasted above OBJ_meta is a dataframe:
`OBJ_meta <- OBJ@meta.data %>% select(orig.ident) %>% rownames_to_column("barcodes")`

Therefore, you can plot using `DimPlot`.  Furthermore according the code you posted you didn't actually add the new meta data information to the object so plotting by sample name also wouldn't work.  If there is more code that you did not post please include all so issue can be diagnosed.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi,

Just confirming if this is still an issue or whether it is solved?

Best,
Sam

**Comment by mbartl13** [comment]
Thanks- apologies yes!
________________________________

**Comment by samuel-marsh** [comment]
No worries!  Thanks for responding!!
