### ISSUE TITLE
SC Transform Seurat integration

### ISSUE THREAD

**Issue by PilanEli** [satijalab/seurat#5883]
Hi,

The SC Transform function must be applied only between datasets or also when we integrate conditions from the same dataset. 
Example: I'm working with the Introduction to scRNA-seq integration vignette in a dataset with 2 conditions (control and tumor). In this case should I use the SCTransform function?

_Originally posted by @PilanEli in https://github.com/satijalab/seurat/discussions/5863#discussioncomment-2587318_

**Comment by saketkc** [comment]
We recommend applying SCTransform to each condition separately. See [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for an example.

**Comment by PilanEli** [comment]
Ok, thanks very much!

Best regards!
