### ISSUE TITLE
discrepancy between cells in ref.mapped and query spaces

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#5885]
Hi,

I followed the Multimodal reference mapping(PBMC). When I represent my data in the query space, I can see a lot of mixing between cell types identified by ref mapping. 
My expectation is that cells classified as specific cell types should be close to each other also in the query space, not intermixed with other cell types.
Below I am showing the l1 classification (l2 is worse) and after filtering out cells using a classification score cut-off. I should add that the score for l1 classification is generally quite high 
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.2652  0.8475  0.9352  0.8950  0.9867  1.0000 

Attached are the original, flt is l1.score>0.5, flt1 is l1.score>0.8475, flt1 is l1.score>0.9352

What do you suggest ? Perhaps I am looking at this the wrong way.

I have 4 objects corresponding to cntr PBMCs, pert1 PBMCs, pert2 PBMCs, pert1+pert2 PBMCs
I ref map each individually
My sequence of steps is as follow:
createSeuratObjectfromCellRanger
SCTransform(x, method="glmGamPoi", verbose = T, vst.flavor = "v2")
LoadH5Seurat
FindTransferAnchors(reference = reference, query = x, normalization.method = "SCT", reference.reduction = "spca", dims = 1:50)
MapQuery(anchorset = anchors, query = pbmc, reference = reference, refdata = refdata, reference.reduction = "spca", reduction.model = "wnn.umap")

SelectIntegrationFeatures(object.list = pbmc, nfeatures = 3000)
PrepSCTIntegration(object.list = pbmc, anchor.features = features)
RunPCA(x, features = features, verbose = FALSE)
RunUMAP(x, reduction = "pca", dims = 1:50, reduction.name = "umap")
FindIntegrationAnchors(object.list = pbmc, normalization.method = "SCT", anchor.features = features, , reduction = "cca",
                                           reference = 1, dims = 1:30)
IntegrateData(anchorset = anchors.cca, normalization.method = "SCT", dims = 1:30)
RunPCA(pbmc.combined.cca, npcs=50, verbose = FALSE)
RunUMAP(pbmc.combined.cca, reduction = "pca", dims = 1:50, reduction.name = "integrated_umap")
DimPlot(pbmc.combined.rpca, group.by = "predicted.celltype.l1", reduction="integrated_umap", label=T) + NoLegend()

Thanks
Gianfilippo

[Archive.zip](https://github.com/satijalab/seurat/files/8557955/Archive.zip)

**Comment by rsatija** [comment]
Thanks for sending - looking through your plots the mixing between cell types in the query space does not appear to be significant. B/Mono/DC/NK/T cells generally do separate well, and even CD4 (orange), and CD8 (green) T cells appear well separated. I think the issue is that there are a few outlier CD8 T cells (potentially doublets or difficult to cl assify cells) that skew the position of the label. These results seem quite reasonable
