### ISSUE TITLE
Error in Using RunSPCA

### ISSUE THREAD

**Issue by carversh** [satijalab/seurat#5886]
Hi, I am trying to integrate a dataset with a reference and having issues with running SPCA on the reference dataset. Any assistance would be greatly appreciated!
```
reference <- readRDS(file = "allen_2019_motor_cortex_ref.rds")
reference <- SCTransform(reference, verbose = FALSE)
seu <- FindVariableFeatures(object = reference)

reference <- RunPCA(reference,  dims = 1:50, features = VariableFeatures(object = seu), return.model=TRUE)
reference <- RunTSNE(reference,  dims = 1:50, features = VariableFeatures(object = seu), return.model=TRUE)
reference <- RunSPCA(
  reference,
  features = VariableFeatures(object = seu),
  npcs = 50,
  reduction.name = "spca",
  reduction.key = "SPC_")
```
Error in RunSPCA.Seurat(reference, features = VariableFeatures(object = seu), : Graph is not provided
Traceback:

1. RunSPCA(reference, features = VariableFeatures(object = seu), 
 .     npcs = 50, reduction.name = "spca", reduction.key = "SPC_")
2. RunSPCA.Seurat(reference, features = VariableFeatures(object = seu), 
 .     npcs = 50, reduction.name = "spca", reduction.key = "SPC_")
3. stop("Graph is not provided")

If I add the graph attribute with a name, like the following:
```
reference <- RunSPCA(
  reference,
  features = VariableFeatures(object = seu),
  npcs = 50,
  reduction.name = "spca",
  reduction.key = "SPC_",
  graph='rna')
```
It gives me the following error: 
Error: Cannot find 'rna' in this Seurat object
Traceback:

1. RunSPCA(reference, features = VariableFeatures(object = seu), 
 .     npcs = 50, reduction.name = "spca", reduction.key = "SPC_", 
 .     graph = "rna")
2. RunSPCA.Seurat(reference, features = VariableFeatures(object = seu), 
 .     npcs = 50, reduction.name = "spca", reduction.key = "SPC_", 
 .     graph = "rna")
3. object[[graph]]
4. `[[.Seurat`(object, graph)
5. stop("Cannot find '", i, "' in this Seurat object", call. = FALSE)

**Comment by carversh** [comment]
Hi just wanted to bump this error message with SPCA?

**Comment by yuhanH** [comment]
Hi, 
SPCA is supervised by a symmetrical graph. You need to specify what graph you are going to use. 
Also, if your reference is one scRNA-seq, SPCA is not necessary to use and reference PCA can be used directly. 
Because in this case, the graph is built based on PCA cell embeddings, it will not add more information for SPCA.
