### ISSUE TITLE
Graphing option in DEenrichRPlot

### ISSUE THREAD

**Issue by qjtang12** [satijalab/seurat#5887]
Hello,

I was using the **DEenrichRPlot** function from **mixscape.R**. The parameter **p.val.cutoff** is using adjusted pvalue as cutoff to select the list of pathways, which is perfect. However, when making the plot, the y-axis is showing the -log10 of the unadjusted pvalue. In this case, some pathways on the plot will have a pvalue that is greater than 0.05 (-log10 less than 1.3). This makes the graph a little bit confusing. 

I am wondering if a feature can be added to let users to chose what to plot as y-axis, either unadjusted pvalue, or adjusted pvalue that is used for the cutoff.

Thank you very much.

**Comment by mhkowalski** [comment]
Hello, 

Sorry for the delayed response. We no longer support this function in Seurat, so I would recommend using other tools for pathway analysis in R, such as clusterprofiler.
