### ISSUE TITLE
Error - Spectral initialization failed to converge, using random initialization instead

### ISSUE THREAD

**Issue by Zaein** [satijalab/seurat#5888]
Hey all,

With the latest R studio update I am now getting an error when I run RunUMAP. Previously, I have had no problems.

This error occurs when I run...
`sc <- RunUMAP(sc, dims = 1:15, verbose = FALSE)` and the error is "Spectral initialization failed to converge, using random initialization instead". 

This results in a Umap that is different from the one that I have been working with. The error does not appear when I set verbose = TRUE but the umap is still different than what it was previously.

If anyone knows what this error means and how to fix it I would greatly appreciate it!

I don't know how much of my code would be useful but I can post it if it will help. Just let me know!

**Comment by Zaein** [comment]
Okay, so the issue is with Seurat version 4.1. When I updated R I also updated Seurat. Previously, I had been using version 4.0.6 and when I revert back to that version things work as expected.

I would like to use the new version though so if anyone could help me with my problem it would be much appreciated!

**Comment by torkencz** [comment]
Hi, 
this is likely not a Seurat issue but an update with how the uwot package is run. If you have your previous object you could just get the UMAP coordinates from that object.
