### ISSUE TITLE
AddModuleScore 

### ISSUE THREAD

**Issue by jopeptid** [satijalab/seurat#5889]
Hi there. Seurat is unbelievably useful.

I have a named feature lists I want to calculate a ModuleScore from e.g

feature.lst = list(genesX = c("gene1","gene2",...), genesY = c("gene3","gene4",...), genesZ = c("gene5","gene6",...))

seu = AddModuleScore(seu, name = names(feature.lst), features = feature.lst, assay = "RNA", search = F)

Seurat creates following columns in seu@meta.data: genesX1, genesY2, genesZ3. 
It would be great if Seurat would not append a numerator if a named list with unique valid names is provided.

I know this is a minor request and can be easily worked around but it would make the function just a bit more user-friendly.

**Comment by torkencz** [comment]
Thank you for the suggestion. We'll look into it for the next update.
