### ISSUE TITLE
convert seurat visium objects to scanpy data format

### ISSUE THREAD

**Issue by hzongyao** [satijalab/seurat#5891]
Hi satijalab,

I want to know how to convert seurat visium objects to scanpy data format，Thnak you ！

**Comment by timoast** [comment]
Please see https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html

**Comment by cf98** [comment]
> Please see https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html

Hi, this function doesn't work for Visium SeuratObjects. Would love know if there's a function to do this. Thanks!

**Comment by howtofindme** [comment]
> > Please see https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html
> 
> Hi, this function doesn't work for Visium SeuratObjects. Would love know if there's a function to do this. Thanks!

hi,
have you solved it? i met the same problem

**Comment by royfrancis** [comment]
Any updates here?

**Comment by kamanso** [comment]
Any update?

**Comment by dajunlee** [comment]
Hi, I met the same problem while using Visium data.
@satijalab, when converting seurat visium data to anndata format, the image file & coordinate information are missing. 
Can you please update on this issue?
