### ISSUE TITLE
segfault on sctransform v2

### ISSUE THREAD

**Issue by simpakkk** [satijalab/seurat#5892]
I am trying to run sctransform v2 on a cluster, after installing the development version of Seurat/updating packages as indicated in the vignette here: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html 

When I try to run SCTransform, I get a segfault error. Any idea what is causing this to happen? This is true using my own data or the dataset from the tutorial above. I am copying/pasting the traceback I receive but I have edited out 2x long strings of characters that are far too long to post and have replaced them with "[long string........]".

`library(Seurat)
library(patchwork)
library(tidyverse)
library(SeuratData)

> # load dataset
> LoadData("ifnb")
# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(ifnb, split.by = "stim")An object of class Seurat 
14053 features across 13999 samples within 1 assay 
Active assay: RNA (14053 features, 0 variable features)
> # split the dataset into a list of two seurat objects (stim and CTRL)
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
> ctrl <- ifnb.list[["CTRL"]]
> stim <- ifnb.list[["STIM"]]
> ctrl <- SCTransform(ctrl, vst.flavor = "v2", verbose = FALSE)

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: DelayedMatrixStats::colSums2(Y)
 2: DelayedMatrixStats::colSums2(Y)
 3: validate_Y_matrix(Y)
 4: glm_gp_impl(data_mat, model_matrix = des$model_matrix, offset = des$offset,     size_factors = size_factors, overdispersion = overdispersion,     do_cox_reid_adjustment = do_cox_reid_adjustment, subsample = subsample,     verbose = verbose)
 5: glmGamPoi::glm_gp(data = umi, design = as.formula(new_formula),     col_data = data, offset = log_umi, size_factors = FALSE)
 6: fit_glmGamPoi_offset(umi = umi_bin_worker, model_str = model_str,     data = data_step1, allow_inf_theta = exclude_poisson)
 7: ...future.FUN(...future.X_jj, ...)
 8: FUN(X[[i]], ...)
 9: lapply(seq_along(...future.elements_ii), FUN = function(jj) {    ...future.X_jj <- ...future.elements_ii[[jj]]    assign(".Random.seed", ...future.seeds_ii[[jj]], envir = globalenv(),         inherits = FALSE)    ...future.FUN(...future.X_jj, ...)})
10: (function (...) {    ...future.globals.maxSize.org <- getOption("future.globals.maxSize")    if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {        oopts <- options(future.globals.maxSize = ...future.globals.maxSize)        on.exit(options(oopts), add = TRUE)    }    {        lapply(seq_along(...future.elements_ii), FUN = function(jj) {            ...future.X_jj <- ...future.elements_ii[[jj]]            assign(".Random.seed", ...future.seeds_ii[[jj]],                 envir = globalenv(), inherits = FALSE)            ...future.FUN(...future.X_jj, ...)        })    }})()
11: do.call(function(...) {    ...future.globals.maxSize.org <- getOption("future.globals.maxSize")    if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {        oopts <- options(future.globals.maxSize = ...future.globals.maxSize)        on.exit(options(oopts), add = TRUE)    }    {        lapply(seq_along(...future.elements_ii), FUN = function(jj) {            ...future.X_jj <- ...future.elements_ii[[jj]]            assign(".Random.seed", ...future.seeds_ii[[jj]],                 envir = globalenv(), inherits = FALSE)            ...future.FUN(...future.X_jj, ...)        })    }}, args = future.call.arguments)
12: eval(quote({    do.call(function(...) {        ...future.globals.maxSize.org <- getOption("future.globals.maxSize")        if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {            oopts <- options(future.globals.maxSize = ...future.globals.maxSize)            on.exit(options(oopts), add = TRUE)        }        {            lapply(seq_along(...future.elements_ii), FUN = function(jj) {                ...future.X_jj <- ...future.elements_ii[[jj]]                assign(".Random.seed", ...future.seeds_ii[[jj]],                   envir = globalenv(), inherits = FALSE)                ...future.FUN(...future.X_jj, ...)            })        }    }, args = future.call.arguments)}), new.env())
13: eval(quote({    do.call(function(...) {        ...future.globals.maxSize.org <- getOption("future.globals.maxSize")        if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {            oopts <- options(future.globals.maxSize = ...future.globals.maxSize)            on.exit(options(oopts), add = TRUE)        }        {            lapply(seq_along(...future.elements_ii), FUN = function(jj) {                ...future.X_jj <- ...future.elements_ii[[jj]]                assign(".Random.seed", ...future.seeds_ii[[jj]],                   envir = globalenv(), inherits = FALSE)                ...future.FUN(...future.X_jj, ...)            })        }    }, args = future.call.arguments)}), new.env())
14: eval(expr, p)
15: eval(expr, p)
16: eval.parent(substitute(eval(quote(expr), envir)))
17: base::local({    do.call(function(...) {        ...future.globals.maxSize.org <- getOption("future.globals.maxSize")        if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {            oopts <- options(future.globals.maxSize = ...future.globals.maxSize)            on.exit(options(oopts), add = TRUE)        }        {            lapply(seq_along(...future.elements_ii), FUN = function(jj) {                ...future.X_jj <- ...future.elements_ii[[jj]]                assign(".Random.seed", ...future.seeds_ii[[jj]],                   envir = globalenv(), inherits = FALSE)                ...future.FUN(...future.X_jj, ...)            })        }    }, args = future.call.arguments)})
18: base::withVisible(base::local({    do.call(function(...) {        ...future.globals.maxSize.org <- getOption("future.globals.maxSize")        if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {            oopts <- options(future.globals.maxSize = ...future.globals.maxSize)            on.exit(options(oopts), add = TRUE)        }        {            lapply(seq_along(...future.elements_ii), FUN = function(jj) {                ...future.X_jj <- ...future.elements_ii[[jj]]                assign(".Random.seed", ...future.seeds_ii[[jj]],                   envir = globalenv(), inherits = FALSE)                ...future.FUN(...future.X_jj, ...)            })        }    }, args = future.call.arguments)}))
19: base::withCallingHandlers({    ...future.value <- base::withVisible(base::local({        do.call(function(...) {            ...future.globals.maxSize.org <- getOption("future.globals.maxSize")            if (!identical(...future.globals.maxSize.org, ...future.globals.maxSize)) {                oopts <- options(future.globals.maxSize = ...future.globals.maxSize)                on.exit(options(oopts), add = TRUE)            }            {                lapply(seq_along(...future.elements_ii), FUN = function(jj) {                  ...future.X_jj <- ...future.elements_ii[[jj]]                  assign(".Random.seed", ...future.seeds_ii[[jj]],                     envir = globalenv(), inherits = FALSE)                  ...future.FUN(...future.X_jj, ...)                })            }        }, args = future.call.arguments)    }))    future::FutureResult(value = ...future.value$value, visible = ...future.value$visible,         rng = !identical(base::globalenv()$.Random.seed, ...future.rng),         started = ...future.startTime, version = "1.8")}, condition = base::local({    c <- base::c    inherits <- base::inherits    invokeRestart <- base::invokeRestart    length <- base::length    list <- base::list    seq.int <- base::seq.int    signalCondition <- base::signalCondition    sys.calls <- base::sys.calls    `[[` <- base::`[[`    `+` <- base::`+`    `<<-` <- base::`<<-`    sysCalls <- function(calls = sys.calls(), from = 1L) {        calls[seq.int(from = from + 12L, to = length(calls) -             3L)]    }    function(cond) {        is_error <- inherits(cond, "error")        ignore <- !is_error && !is.null(NULL) && inherits(cond,             NULL)        if (is_error) {            sessionInformation <- function() {                list(r = base::R.Version(), locale = base::Sys.getlocale(),                   rngkind = base::RNGkind(), namespaces = base::loadedNamespaces(),                   search = base::search(), system = base::Sys.info())            }            ...future.conditions[[length(...future.conditions) +                 1L]] <<- list(condition = cond, calls = c(sysCalls(from = ...future.frame),                 cond$call), session = sessionInformation(), timestamp = base::Sys.time(),                 signaled = 0L)            signalCondition(cond)        }        else if (!ignore && TRUE && inherits(cond, c("condition",         "immediateCondition"))) {            signal <- TRUE && inherits(cond, "immediateCondition")            ...future.conditions[[length(...future.conditions) +                 1L]] <<- list(condition = cond, signaled = base::as.integer(signal))            if (TRUE && !signal) {                muffleCondition <- function (cond, pattern = "^muffle")                 {                  inherits <- base::inherits                  invokeRestart <- base::invokeRestart                  is.null <- base::is.null                  muffled <- FALSE                  if (inherits(cond, "message")) {                    muffled <- grepl(pattern, "muffleMessage")                    if (muffled)                       invokeRestart("muffleMessage")                  }                  else if (inherits(cond, "warning")) {                    muffled <- grepl(pattern, "muffleWarning")                    if (muffled)                       invokeRestart("muffleWarning")                  }                  else if (inherits(cond, "condition")) {                    if (!is.null(pattern)) {                      computeRestarts <- base::computeRestarts                      grepl <- base::grepl                      restarts <- computeRestarts(cond)                      for (restart in restarts) {                        name <- restart$name                        if (is.null(name))                           next                        if (!grepl(pattern, name))                           next                        invokeRestart(restart)                        muffled <- TRUE                        break                      }                    }                  }                  invisible(muffled)                }                muffleCondition(cond, pattern = "^muffle")            }        }        else {            if (TRUE) {                muffleCondition <- function (cond, pattern = "^muffle")                 {                  inherits <- base::inherits                  invokeRestart <- base::invokeRestart                  is.null <- base::is.null                  muffled <- FALSE                  if (inherits(cond, "message")) {                    muffled <- grepl(pattern, "muffleMessage")                    if (muffled)                       invokeRestart("muffleMessage")                  }                  else if (inherits(cond, "warning")) {                    muffled <- grepl(pattern, "muffleWarning")                    if (muffled)                       invokeRestart("muffleWarning")                  }                  else if (inherits(cond, "condition")) {                    if (!is.null(pattern)) {                      computeRestarts <- base::computeRestarts                      grepl <- base::grepl                      restarts <- computeRestarts(cond)                      for (restart in restarts) {                        name <- restart$name                        if (is.null(name))                           next                        if (!grepl(pattern, name))                           next                        invokeRestart(restart)                        muffled <- TRUE                        break                      }                    }                  }                  invisible(muffled)                }                muffleCondition(cond, pattern = "^muffle")            }        }    }}))
20: doTryCatch(return(expr), name, parentenv, handler)
21: tryCatchOne(expr, names, parentenv, handlers[[1L]])
22: tryCatchList(expr, classes, parentenv, handlers)
23: base::tryCatch({    base::withCallingHandlers({        ...future.value <- base::withVisible(base::local({            do.call(function(...) {                ...future.globals.maxSize.org <- getOption("future.globals.maxSize")                if (!identical(...future.globals.maxSize.org,                   ...future.globals.maxSize)) {                  oopts <- options(future.globals.maxSize = ...future.globals.maxSize)                  on.exit(options(oopts), add = TRUE)                }                {                  lapply(seq_along(...future.elements_ii), FUN = function(jj) {                    ...future.X_jj <- ...future.elements_ii[[jj]]                    assign(".Random.seed", ...future.seeds_ii[[jj]],                       envir = globalenv(), inherits = FALSE)                    ...future.FUN(...future.X_jj, ...)                  })                }            }, args = future.call.arguments)        }))        future::FutureResult(value = ...future.value$value, visible = ...future.value$visible,             rng = !identical(base::globalenv()$.Random.seed,                 ...future.rng), started = ...future.startTime,             version = "1.8")    }, condition = base::local({        c <- base::c        inherits <- base::inherits        invokeRestart <- base::invokeRestart        length <- base::length        list <- base::list        seq.int <- base::seq.int        signalCondition <- base::signalCondition        sys.calls <- base::sys.calls        `[[` <- base::`[[`        `+` <- base::`+`        `<<-` <- base::`<<-`        sysCalls <- function(calls = sys.calls(), from = 1L) {            calls[seq.int(from = from + 12L, to = length(calls) -                 3L)]        }        function(cond) {            is_error <- inherits(cond, "error")            ignore <- !is_error && !is.null(NULL) && inherits(cond,                 NULL)            if (is_error) {                sessionInformation <- function() {                  list(r = base::R.Version(), locale = base::Sys.getlocale(),                     rngkind = base::RNGkind(), namespaces = base::loadedNamespaces(),                     search = base::search(), system = base::Sys.info())                }                ...future.conditions[[length(...future.conditions) +                   1L]] <<- list(condition = cond, calls = c(sysCalls(from = ...future.frame),                   cond$call), session = sessionInformation(),                   timestamp = base::Sys.time(), signaled = 0L)                signalCondition(cond)            }            else if (!ignore && TRUE && inherits(cond, c("condition",             "immediateCondition"))) {                signal <- TRUE && inherits(cond, "immediateCondition")                ...future.conditions[[length(...future.conditions) +                   1L]] <<- list(condition = cond, signaled = base::as.integer(signal))                if (TRUE && !signal) {                  muffleCondition <- function (cond, pattern = "^muffle")                   {                    inherits <- base::inherits                    invokeRestart <- base::invokeRestart                    is.null <- base::is.null                    muffled <- FALSE                    if (inherits(cond, "message")) {                      muffled <- grepl(pattern, "muffleMessage")                      if (muffled)                         invokeRestart("muffleMessage")                    }                    else if (inherits(cond, "warning")) {                      muffled <- grepl(pattern, "muffleWarning")                      if (muffled)                         invokeRestart("muffleWarning")                    }                    else if (inherits(cond, "condition")) {                      if (!is.null(pattern)) {                        computeRestarts <- base::computeRestarts                        grepl <- base::grepl                        restarts <- computeRestarts(cond)                        for (restart in restarts) {                          name <- restart$name                          if (is.null(name))                             next                          if (!grepl(pattern, name))                             next                          invokeRestart(restart)                          muffled <- TRUE                          break                        }                      }                    }                    invisible(muffled)                  }                  muffleCondition(cond, pattern = "^muffle")                }            }            else {                if (TRUE) {                  muffleCondition <- function (cond, pattern = "^muffle")                   {                    inherits <- base::inherits                    invokeRestart <- base::invokeRestart                    is.null <- base::is.null                    muffled <- FALSE                    if (inherits(cond, "message")) {                      muffled <- grepl(pattern, "muffleMessage")                      if (muffled)                         invokeRestart("muffleMessage")                    }                    else if (inherits(cond, "warning")) {                      muffled <- grepl(pattern, "muffleWarning")                      if (muffled)                         invokeRestart("muffleWarning")                    }                    else if (inherits(cond, "condition")) {                      if (!is.null(pattern)) {                        computeRestarts <- base::computeRestarts                        grepl <- base::grepl                        restarts <- computeRestarts(cond)                        for (restart in restarts) {                          name <- restart$name                          if (is.null(name))                             next                          if (!grepl(pattern, name))                             next                          invokeRestart(restart)                          muffled <- TRUE                          break                        }                      }                    }                    invisible(muffled)                  }                  muffleCondition(cond, pattern = "^muffle")                }            }        }    }))}, error = function(ex) {    base::structure(base::list(value = NULL, visible = NULL,         conditions = ...future.conditions, rng = !identical(base::globalenv()$.Random.seed,             ...future.rng), started = ...future.startTime, finished = Sys.time(),         session_uuid = NA_character_, version = "1.8"), class = "FutureResult")}, finally = {    {        {            NULL            base::assign(".Random.seed", c(10403L, [long string.....]), ..future.oldEnvVars))    base::Sys.unsetenv(diff)})
24: eval(expr, envir = envir, enclos = baseenv())
25: eval(expr, envir = envir, enclos = baseenv())
26: run.UniprocessFuture(future)
27: run(future)
28: run.Future(future)
29: run(future)
30: future(expr, substitute = FALSE, envir = future.envir, stdout = future.stdout,     conditions = future.conditions, globals = globals_ii, packages = packages_ii,     seed = future.seed, label = labels[ii])
31: future_xapply(FUN = FUN, nX = nX, chunk_args = X, args = list(...),     get_chunk = `[`, expr = expr, envir = envir, future.envir = future.envir,     future.globals = future.globals, future.packages = future.packages,     future.scheduling = future.scheduling, future.chunk.size = future.chunk.size,     future.stdout = future.stdout, future.conditions = future.conditions,     future.seed = future.seed, future.label = future.label, fcn_name = fcn_name,     args_name = args_name, debug = debug)
32: future_lapply(X = index_lst, FUN = function(indices) {    umi_bin_worker <- umi_bin[indices, , drop = FALSE]    if (fix_intercept | fix_slope) {        mu_bin_worker <- mu_bin[indices, , drop = FALSE]        model_pars_bin_worker <- model_pars_bin[indices, , drop = FALSE]        intercept_bin_worker <- model_pars_bin_worker[, "(Intercept)"]        slope_bin_worker <- model_pars_bin_worker[, "log_umi"]    }    if (method == "poisson") {        return(fit_poisson(umi = umi_bin_worker, model_str = model_str,             data = data_step1, theta_estimation_fun = theta_estimation_fun))    }    if (method == "qpoisson") {        return(fit_qpoisson(umi = umi_bin_worker, model_str = model_str,             data = data_step1))    }    if (method == "nb_theta_given") {        theta_given_bin_worker <- theta_given_bin[indices]        return(fit_nb_theta_given(umi = umi_bin_worker, model_str = model_str,             data = data_step1, theta_given = theta_given_bin_worker))    }    if (method == "nb_fast") {        return(fit_nb_fast(umi = umi_bin_worker, model_str = model_str,             data = data_step1, theta_estimation_fun = theta_estimation_fun))    }    if (method == "nb") {        return(fit_nb(umi = umi_bin_worker, model_str = model_str,             data = data_step1))    }    if (method == "glmGamPoi") {        if (fix_slope | fix_intercept) {            if (packageVersion("glmGamPoi") < "1.5.1") {                stop("Please install glmGamPoi >= 1.5.1 from https://github.com/const-ae/glmGamPoi")            }            return(fit_overdisp_mle(umi = umi_bin_worker, mu = mu_bin_worker,                 intercept = intercept_bin_worker, slope = slope_bin_worker))        }        return(fit_glmGamPoi(umi = umi_bin_worker, model_str = model_str,             data = data_step1, allow_inf_theta = exclude_poisson))    }    if (method == "glmGamPoi_offset") {        return(fit_glmGamPoi_offset(umi = umi_bin_worker, model_str = model_str,             data = data_step1, allow_inf_theta = exclude_poisson))    }}, future.seed = TRUE)
33: get_model_pars(genes_step1, bin_size, umi, model_str, cells_step1,     method, data_step1, theta_given, theta_estimation_fun, exclude_poisson,     fix_intercept, fix_slope, use_geometric_mean, use_geometric_mean_offset,     verbosity)
34: vst(vst.flavor = "v2", umi = new("dgCMatrix", i = c(20L, ([long string......]), verbosity = 0, return_cell_attr = TRUE,     return_gene_attr = TRUE, return_corrected_umi = TRUE, n_cells = 5000)
35: do.call(what = "vst", args = vst.args)
36: SCTransform(ctrl, vst.flavor = "v2", verbose = FALSE)

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /gpfs/fs02/apps/R/4.0.2/lib64/R/lib/libRblas.so
LAPACK: /gpfs/fs02/apps/R/4.0.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ifnb.SeuratData_3.1.0 SeuratData_0.2.1      forcats_0.5.1        
 [4] stringr_1.4.0         dplyr_1.0.8           purrr_0.3.4          
 [7] readr_2.1.2           tidyr_1.2.0           tibble_3.1.6         
[10] ggplot2_3.3.5         tidyverse_1.3.1       patchwork_1.1.1      
[13] SeuratObject_4.0.4    Seurat_4.1.0.9006    

loaded via a namespace (and not attached):
  [1] Rtsne_0.16            colorspace_2.0-3      deldir_1.0-6         
  [4] ellipsis_0.3.2        ggridges_0.5.3        fs_1.5.2             
  [7] rstudioapi_0.13       spatstat.data_2.2-0   leiden_0.3.10        
 [10] listenv_0.8.0         ggrepel_0.9.1         fansi_1.0.3          
 [13] lubridate_1.8.0       xml2_1.3.3            codetools_0.2-16     
 [16] splines_4.0.2         polyclip_1.10-0       jsonlite_1.8.0       
 [19] broom_0.8.0           ica_1.0-2             cluster_2.1.0        
 [22] dbplyr_2.1.1          png_0.1-7             uwot_0.1.11          
 [25] shiny_1.7.1           sctransform_0.3.3     spatstat.sparse_2.1-1
 [28] compiler_4.0.2        httr_1.4.2            backports_1.1.10     
 [31] assertthat_0.2.1      Matrix_1.4-1          fastmap_1.1.0        
 [34] lazyeval_0.2.2        cli_3.3.0             later_1.3.0          
 [37] htmltools_0.5.2       tools_4.0.2           igraph_1.3.1         
 [40] gtable_0.3.0          glue_1.6.2            RANN_2.6.1           
 [43] reshape2_1.4.4        rappdirs_0.3.3        Rcpp_1.0.8.3         
 [46] scattermore_0.8       cellranger_1.1.0      vctrs_0.4.1          
 [49] nlme_3.1-148          lmtest_0.9-40         spatstat.random_2.2-0
 [52] globals_0.14.0        rvest_1.0.2           mime_0.12            
 [55] miniUI_0.1.1.1        lifecycle_1.0.1       irlba_2.3.5          
 [58] goftest_1.2-3         future_1.25.0         MASS_7.3-51.6        
 [61] zoo_1.8-10            scales_1.2.0          spatstat.core_2.4-2  
 [64] hms_1.1.1             promises_1.2.0.1      spatstat.utils_2.3-0 
 [67] parallel_4.0.2        RColorBrewer_1.1-3    reticulate_1.24      
 [70] pbapply_1.5-0         gridExtra_2.3         rpart_4.1-15         
 [73] stringi_1.7.6         rlang_1.0.2           pkgconfig_2.0.3      
 [76] matrixStats_0.62.0    lattice_0.20-41       ROCR_1.0-11          
 [79] tensor_1.5            htmlwidgets_1.5.4     cowplot_1.1.1        
 [82] tidyselect_1.1.2      parallelly_1.31.1     RcppAnnoy_0.0.19     
 [85] plyr_1.8.7            magrittr_2.0.3        R6_2.5.1             
 [88] generics_0.1.2        DBI_1.1.0             withr_2.5.0          
 [91] pillar_1.7.0          haven_2.5.0           mgcv_1.8-31          
 [94] fitdistrplus_1.1-8    survival_3.1-12       abind_1.4-5          
 [97] future.apply_1.9.0    modelr_0.1.8          crayon_1.5.1         
[100] KernSmooth_2.23-17    utf8_1.2.2            spatstat.geom_2.4-0  
[103] plotly_4.10.0         tzdb_0.3.0            grid_4.0.2           
[106] readxl_1.4.0          data.table_1.14.2     reprex_2.0.1         
[109] digest_0.6.29         xtable_1.8-4          httpuv_1.6.5         
[112] munsell_0.5.0         viridisLite_0.4.0    
`

**Comment by saketkc** [comment]
Does this also happen if you try this is a new R session (after restarting your old session?)

**Comment by simpakkk** [comment]
Yep it is happening with a new session via R --vanilla and also after I close/re-enter the cluster.

**Comment by saketkc** [comment]
You will need to update to `glmGamPoi >= 1.5.1` - it should ideally print an error if you have a lower version.

**Comment by simpakkk** [comment]
I updated to glmGamPoi 1.8.0, but it was difficult (not automatically updating).
If someone else is having trouble, make sure to install directly from: 'https://bioconductor.org/packages/3.15/bioc/src/contrib/glmGamPoi_1.8.0.tar.gz'

Regardless of the update, and also reinstalling Seurat, I am getting an error at the same place...now it is simply installing Seurat v4.1.1 from devtools::[install_github](https://devtools.r-lib.org/reference/remote-reexports.html)("satijalab/seurat", ref = "develop") ; unsure if this is correct?

Info is below (FYI, I cannot use a version of R higher than 4.0.2 in this system at the moment - any chance this is an issue?)

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /gpfs/fs02/apps/R/4.0.2/lib64/R/lib/libRblas.so
LAPACK: /gpfs/fs02/apps/R/4.0.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmGamPoi_1.8.0    patchwork_1.1.1    sp_1.4-7           SeuratObject_4.1.0
[5] Seurat_4.1.1      

loaded via a namespace (and not attached):
  [1] plyr_1.8.7                  igraph_1.3.1               
  [3] lazyeval_0.2.2              splines_4.0.2              
  [5] listenv_0.8.0               scattermore_0.8            
  [7] usethis_2.1.5               GenomeInfoDb_1.24.2        
  [9] ggplot2_3.3.5               digest_0.6.29              
 [11] htmltools_0.5.2             fansi_1.0.3                
 [13] magrittr_2.0.3              memoise_2.0.1              
 [15] tensor_1.5                  cluster_2.1.0              
 [17] ROCR_1.0-11                 remotes_2.4.2              
 [19] globals_0.14.0              matrixStats_0.62.0         
 [21] spatstat.sparse_2.1-1       prettyunits_1.1.1          
 [23] colorspace_2.0-3            ggrepel_0.9.1              
 [25] dplyr_1.0.9                 callr_3.7.0                
 [27] crayon_1.5.1                RCurl_1.98-1.2             
 [29] jsonlite_1.8.0              progressr_0.10.0           
 [31] spatstat.data_2.2-0         survival_3.1-12            
 [33] zoo_1.8-10                  glue_1.6.2                 
 [35] polyclip_1.10-0             gtable_0.3.0               
 [37] zlibbioc_1.34.0             XVector_0.28.0             
 [39] leiden_0.3.10               DelayedArray_0.14.1        
 [41] pkgbuild_1.3.1              future.apply_1.9.0         
 [43] BiocGenerics_0.34.0         abind_1.4-5                
 [45] scales_1.2.0                DBI_1.1.0                  
 [47] spatstat.random_2.2-0       miniUI_0.1.1.1             
 [49] Rcpp_1.0.8.3                viridisLite_0.4.0          
 [51] xtable_1.8-4                reticulate_1.24            
 [53] spatstat.core_2.4-2         stats4_4.0.2               
 [55] htmlwidgets_1.5.4           httr_1.4.2                 
 [57] RColorBrewer_1.1-3          ellipsis_0.3.2             
 [59] ica_1.0-2                   pkgconfig_2.0.3            
 [61] uwot_0.1.11                 deldir_1.0-6               
 [63] utf8_1.2.2                  tidyselect_1.1.2           
 [65] rlang_1.0.2                 reshape2_1.4.4             
 [67] later_1.3.0                 munsell_0.5.0              
 [69] tools_4.0.2                 cachem_1.0.6               
 [71] cli_3.3.0                   generics_0.1.2             
 [73] devtools_2.4.3              ggridges_0.5.3             
 [75] stringr_1.4.0               fastmap_1.1.0              
 [77] goftest_1.2-3               processx_3.5.3             
 [79] fs_1.5.2                    fitdistrplus_1.1-8         
 [81] purrr_0.3.4                 RANN_2.6.1                 
 [83] pbapply_1.5-0               future_1.25.0              
 [85] nlme_3.1-148                mime_0.12                  
 [87] brio_1.1.3                  compiler_4.0.2             
 [89] plotly_4.10.0               curl_4.3.2                 
 [91] png_0.1-7                   testthat_3.1.4             
 [93] spatstat.utils_2.3-0        tibble_3.1.6               
 [95] stringi_1.7.6               ps_1.3.4                   
 [97] desc_1.4.1                  rgeos_0.5-9                
 [99] lattice_0.20-41             Matrix_1.4-1               
[101] vctrs_0.4.1                 pillar_1.7.0               
[103] lifecycle_1.0.1             spatstat.geom_2.4-0        
[105] lmtest_0.9-40               RcppAnnoy_0.0.19           
[107] data.table_1.14.2           cowplot_1.1.1              
[109] bitops_1.0-7                irlba_2.3.5                
[111] GenomicRanges_1.40.0        httpuv_1.6.5               
[113] R6_2.5.1                    promises_1.2.0.1           
[115] KernSmooth_2.23-17          gridExtra_2.3              
[117] IRanges_2.22.2              parallelly_1.31.1          
[119] sessioninfo_1.2.2           codetools_0.2-16           
[121] MASS_7.3-51.6               assertthat_0.2.1           
[123] pkgload_1.2.4               SummarizedExperiment_1.18.2
[125] rprojroot_2.0.3             withr_2.5.0                
[127] sctransform_0.3.3           GenomeInfoDbData_1.2.3     
[129] S4Vectors_0.26.1            mgcv_1.8-31                
[131] parallel_4.0.2              grid_4.0.2                 
[133] rpart_4.1-15                tidyr_1.2.0                
[135] Rtsne_0.16                  Biobase_2.48.0             
[137] shiny_1.7.1

SessionInfo():
other attached packages:
[1] glmGamPoi_1.8.0    patchwork_1.1.1    sp_1.4-7           SeuratObject_4.1.0
[5] Seurat_4.1.1      

----
Error again:

> library(Seurat)
library(Attaching SeuratObject
Attaching sp
> library(patchwork)
> library(glmGamPoi)
> library(ggplot2)
> # install dataset
> InstallData("ifnb")
Warning: The following packages are already installed and will not be reinstalled: ifnb
> # load dataset
> LoadData("ifnb")
An object of class Seurat 
14053 features across 13999 samples within 1 assay 
Active assay: RNA (14053 features, 0 variable features)
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
> ctrl <- ifnb.list[["CTRL"]]
> stim <- ifnb.list[["STIM"]]
> ctrl <- SCTransform(ctrl, vst.flavor = "v2", verbose = FALSE)

 *** caught segfault ***
address 0x231000030, cause 'memory not mapped'

Traceback:
 1: DelayedMatrixStats::colMeans2(exp(offset_matrix))
 2: DelayedMatrixStats::colMeans2(exp(offset_matrix))
 3: mean(DelayedMatrixStats::colMeans2(exp(offset_matrix)))
 4: estimate_dispersions_by_moment(Y, model_matrix, offset_matrix)
 5: estimate_dispersions_roughly(Y, model_matrix, offset_matrix = offset_matrix)
 6: glm_gp_impl(data_mat, model_matrix = des$model_matrix, offset = offset,     size_factors = size_factors, overdispersion = overdispersion,     overdispersion_shrinkage = overdispersion_shrinkage, ridge_penalty = ridge_penalty,     do_cox_reid_adjustment = do_cox_reid_adjustment, subsample = subsample,     verbose = verbose)
 7: glmGamPoi::glm_gp(data = umi, design = as.formula(new_formula),     col_data = data, offset = log_umi, size_factors = FALSE)
 8: fit_glmGamPoi_offset(umi = umi_bin_worker, model_str = model_str,     data = data_step1, allow_inf_theta = exclude_poisson)
.....
36: vst(vst.flavor = "v2", umi = new("dgCMatrix",...[long string]....
37: do.call(what = "vst", args = vst.args)
38: SCTransform(ctrl, vst.flavor = "v2", verbose = FALSE)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

Selection: 1
R is aborting now ...
Segmentation fault (core dumped)

**Comment by saketkc** [comment]
Are you running this on a cluster? If it is on an interactive session, how much memory are you requesting?

**Comment by simpakkk** [comment]
Yep it is on a cluster and it is interactive - I was requesting 150gb memory.  So I tried submitting a non-interactive job requesting 250gb memory (max allowed). This job exited also though.

 MEMLIMIT
  244.1 G 

MEMORY USAGE:
MAX MEM: 1.6 Gbytes;  AVG MEM: 1 Gbytes

Got the following output above.

**Comment by saketkc** [comment]
Sorry, I am unable to reproduce this. Does this also happen on your local machine? The memory requirement does not seem to be the one causing trouble here - it looks like it has to do with the installation on the cluster but I am unsure what it is.

**Comment by simpakkk** [comment]
No it doesn't happen locally - it is definitely cluster related.
I tried deleting all packages (except base/recommended) and then re-installing absolutely everything from scratch. Then it suddenly worked - once on the tutorial dataset, and once on my own data.
I continued with my workflow (from there, RPCA integration --> RunUMAP() --> FindNeighbors()) and tried to perform SCTransform again downstream after subsetting, and it came back with segfault once more. Tested on the tutorial dataset again and the same thing happened.

...so I can try re-installing everything again and see if that fixes the problem again. But doing this every single time would be seriously annoying. 

Any ideas based on the above info?

**Comment by saketkc** [comment]
Does the cluster installation use conda for installing R and packages?

**Comment by saketkc** [comment]
Closing this as we haven't heard back. Feel free to reopen if you have any lingering issues.

**Comment by KC-Lan** [comment]
Hi, 
I also faced a similar problem (R session aborted) using glmGamPoi 1.0.0 and R 4.0.2.
Refer to the reply from @saketkc  `You will need to update to glmGamPoi >= 1.5.1`, I also tried to run SCTransform v2 using different version of glmGamPoi (1.8.0, 1.4.0 and 1.2.0), but none of it worked with my own data.
But when I changed to use `R 4.2.0 (glmGamPoi_1.8.0)`, it works well without any problem.

**Comment by simpakkk** [comment]
Yeah this still happens to me - I had it working for a while but now it is back the way it was before...
Unfortunately I can't update R - that would be the easiest solution for sure...

I think it has to be something else in Bioconductor which is causing issues - I am forced to use Bioconductor 3.12 because of the old version of R, and I need to update packages (like glmGamPoi) manually when required...
