### ISSUE TITLE
Importing UMAP projection from loupe 10x to Seurat

### ISSUE THREAD

**Issue by Victoriat0618** [satijalab/seurat#5893]
Hi there. I know that Loupe Browser 6 has a new feature where it can export a CSV file of the projection's barcode and coordinates. I'm wondering if there's a way to add this to the Seurat object? Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  See this comment on previous post (https://github.com/satijalab/seurat/issues/5113#issuecomment-923966351)

Best,
Sam

**Comment by Victoriat0618** [comment]
thanks. Will def take a look at it
