### ISSUE TITLE
Remove -MT genes 

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#5895]
Hi,

I would like to remove all the -MT genes from my dataset to reduce noise. As far as I understand is better to do this prior to creating the SeuratObject. I'm trying to remove all the -MT rows from the matrix but when I check for percent.mt after creating the SeuratObject the result is not 0%. Could someone suggest a way to remove MT- genes? Thank you!!

This is the code I tried: 

```
matrix_dir = "C:/Users/......"
barcode.path <- paste0(matrix_dir, "barcodes.tsv.gz")
features.path <- paste0(matrix_dir, "features.tsv.gz")
matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
mat <- readMM(file = matrix.path)
feature.names <- read.delim(features.path,
                           header = FALSE,
                           stringsAsFactors = FALSE)
barcode.names <- read.delim(barcode.path,
                           header = FALSE,
                           stringsAsFactors = FALSE)
colnames(mat) = barcode.names$V1
rownames(mat) = feature.names$V2

mat[-which(grepl("^MT-",mat@Dimnames[[1]])),]    #remove rows containing MT- from matrix



myse <- CreateSeuratObject(counts = mat, project = "myse")
myse[["percent.mt"]] <- PercentageFeatureSet(myse, pattern = "^MT-")

```

**Comment by giorgiatosoni** [comment]
> I am not part of the Seurat Team, but I think is a good idea to use the MT genes as a measurement of cell stress before removing MT genes. In any case, this previous issue explains how to remove genes from a Seurat object. [# Delete specific gene](https://github.com/satijalab/seurat/issues/2610)

That's true, thanks for the suggestion!
I'm trying to integrate my human dataset with a previously published one, using Harmony for integration. I expect to find more or less the same cell types however, I noticed that when I plot pecent.mt in the UMAP my dataset contains higher mt% and I'm afraid same cell types across datasets are clustering apart because of a technical difference in mt%. How can I correct for this?

Thanks!

**Comment by torkencz** [comment]
Yeah you can remove the MT genes or regress them out later.
