### ISSUE TITLE
hdf5r library

### ISSUE THREAD

**Issue by tanasa** [satijalab/seurat#5898]
Is there any other way to read h5 data beside 10X_h5 function ?

We need the package "hdf5r" in order to read the h5 data. 

On a workstation that it is on EC2, I do get the following error : 

```
> library("hdf5r")
Error: package or namespace load failed for ‘hdf5r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/lalala/R/x86_64-pc-linux-gnu-library/4.0/hdf5r/libs/hdf5r.so':
  libhdf5_hl.so.200: cannot open shared object file: No such file or directory
``

 and dyn.load() does not help.

`dyn.load("/usr/local/hdf5/lib/libhdf5.so.200")`

What shall I do ?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  In Seurat that is the only function to read in H5 data and it looks like there was issue in the installation of that package on your workstation.  Have you tried removing and reinstalling hdf5r?  Do you get same error?  

I know other packages also have functions to read 10X h5 data but if they are also based on hdf5r (I don't know if this is case) then they will also not work.

If the installation of hdf5r fails again I suggest posting in their repository for help resolving the installation issue.

Best,
Sam

**Comment by torkencz** [comment]
Yeah, I would first try to removing and reinstalling hdf5r. If it fails I would suggest posting in their repository.

**Comment by Pedramto89** [comment]
Hi
I also have the same problem. 
This is the error:
`** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘hdf5r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/pedram.torabian/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-hdf5r/00new/hdf5r/libs/hdf5r.so':
  libhdf5_hl.so.100: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/pedram.torabian/R/x86_64-pc-linux-gnu-library/4.2/hdf5r’
 
The downloaded source packages are in
       ‘/tmp/RtmpqYJWw9/downloaded_packages’
Warning message:
In install.packages("hdf5r") :
  installation of package ‘hdf5r’ had non-zero exit status`
