### ISSUE TITLE
Install and run UMAP with R (Seurat)

### ISSUE THREAD

**Issue by MichaelStreuber** [satijalab/seurat#590]
Hi ,

Concerning the last new feature in Seurat “UMAP”, I have a question:
I directly tried to run Umap with alignment data but I got an error (“Could not find function “RunUmap”). I used the commands below to install and run UMAP:
```R
.libPaths("C:/R-libs2")

library(Seurat)
library(dplyr)
library(Matrix)

Install.packages('umap')
library(umap)

immune.combined <- RunUMAP(immune.combined, reduction.use = "cca.aligned", dims.use = 1:20, 
                           do.fast = T)
```
I am using R Version 3.4.4.
Have I forgotten to install something?

Best,
Michael

**Comment by mojaveazure** [comment]
What version of Seurat are you using (run `packageVersion('Seurat')`)? Also, can you check the capitalization of your command? The error looks like you're calling `RunUmap`, but the function is [`RunUMAP `](https://www.rdocumentation.org/packages/Seurat/versions/2.3.3/topics/RunUMAP); R is a case-sensitive language, so getting the capitalization in a function name correct is imperative.

**Comment by satijalab** [comment]
In addition to the capitalization issue, please note that for Seurat, umap is being run in python (though called from R!), using the reticulate package. More info here : https://rstudio.github.io/reticulate/articles/introduction.html

This means you don't run install.packages('umap'), but need to install the umap-learn package from python using, for example, pip.

**Comment by MichaelStreuber** [comment]
Hi Paul, hi satijalab,

Thank you very much for your fast answer and sorry for this delayed response.

I checked my commands and indeed  used the command "RunUMAP()" but it didn't worked. 
I am using Seurat Version 2.3.3. (with R Version 3.5.1).

Concerning your point install the umap-learn package from python: How can I install it, I mean which commands do I have to use? I am not so familiar with Python and don't know what I have to do now, sorry :(

**Comment by mojaveazure** [comment]
To learn how to use UMAP and install it from official Python sources, please see [UMAP's README](https://github.com/lmcinnes/umap/blob/master/README.rst).

**Comment by MichaelStreuber** [comment]
Thank you Paul!

**Comment by twsaari** [comment]
Can this be changed to use the `umap` native R package instead of the python implementation via reticulate? It has been very troublesome getting the python package to behave correctly when using Conda and Docker to manage the software (for reproducibility purposes).
