### ISSUE TITLE
dims.use does not work in RunHarmony

### ISSUE THREAD

**Issue by vagabond12** [satijalab/seurat#5902]
I have tried to set  dims.use =2:15 during RunHarmony process. But it does not work, and the UMAP is the same as not setting  dims.use.  What is the reason? Thank you.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  Can you please post the full code you are running that results in the issue?

Thanks!
Sam

**Comment by timoast** [comment]
The `RunHarmony()` function is actually part of the harmony R package, not Seurat. Please open an issue there: https://github.com/immunogenomics/harmony
