### ISSUE TITLE
Error: Feature names of counts matrix cannot be empty

### ISSUE THREAD

**Issue by mcsintonn** [satijalab/seurat#5904]
### Discussed in https://github.com/satijalab/seurat/discussions/5903

<div type='discussions-op-text'>

<sup>Originally posted by **mcsintonn** May  2, 2022</sup>
Hi,

I'm brand new to single cell and I'm trying to use Seurat for the first time. I have a CellRanger output, with a raw_feature_bc_matrix folder. This folder contains three compressed files: barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz. 

I have read this folder into R Studio using the following line, as recommended in the Seurat guide:

**naive1.data <- Read10X(data.dir = "/Users/Desktop/naive_raw_feature_bc_matrix")**

I then try to use the CreateSeuratObject command as follows:

**adipnaive <- CreateSeuratObject(counts = naive1.data, project = "TrypWAT", min.cells = 3, min.features = 200)**

At this point, I get the following error: 
**Error: Feature names of counts matrix cannot be empty**

I'm completely lost here, and was wondering if anyone has any insights into what might be causing the problem?  I was wondering if it might be because as well as mouse genes, there are also trypanosome genes in this file. I have attached an example of the file (although in Excel format rather than .tsv) 
[features_file_example.xlsx](https://github.com/satijalab/seurat/files/8602343/features_file_example.xlsx)

Any advice would be very much appreciated! 
</div>

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What is the output of:

```
class(naive1.data)

head(rownames(test), 5)
```

Best,
Sam

**Comment by rsatija** [comment]
As sam implies, the issue here is likely that the row names of the matrix are not set. One possibility is that there are non-standard characters in yoru file (for example %2). Removing the % should fix the problem. Please re-open if that does not solve.

**Comment by curiegat** [comment]
Hi, 

I am having the same problem, I have changed the % into _ and it gives me the same error message. Would you please suggest what should I do?. Currently the data has . and _ on the name

Looking forward for your suggestion. 

Thank you 

Best regards, 

Agatha

**Comment by lubianat** [comment]
Same problem here, situation similar to curiegat.

**Comment by lubianat** [comment]
"solved" it by removing all gene symbols with a dot: `count_matrix <- count_matrix[- grep("\\.", count_matrix$gene.symbol),]`

**Comment by AnjaliS1** [comment]
Same problem here too.

**Comment by curiegat** [comment]
@lubianat and @AnjaliS1 I solved the problem by creating the Seurat object using Cellenics [(https://scp.biomage.net/data-management)](url) and downloading the rds file, but I think it is because of the unwanted characters in the row names of the matrix, the code is available from cellenics too in the following link [https://github.com/biomage-org/pipeline/blob/master/pipeline-runner/R/gem2s-2-load_user_files.R](url).

**Comment by a1aks** [comment]
This blog maybe closed but I wished to give my take on this for solving the problem. 

When one gets Error: Feature names of counts matrix cannot be empty - it means that there some row names in the data matrix/ data frame that are "empty" not NA. To check this one can use 
any(rownames(naive1.data == '')). This should give you a boolean results with TRUE/FALSE. Then check which row is actually empty by using the command which(rownames(naive1.data == '')). You will get the exact cell number that is empty. 

By removing the empty cell and then doig 
adipnaive <- CreateSeuratObject(counts = naive1.data, project = "TrypWAT", min.cells = 3, min.features = 200)

should solve the problem. 

Hope this helps for naive seurat users.
