### ISSUE TITLE
VlnPlot gives negative values but the data matrix doesn't have negative values

### ISSUE THREAD

**Issue by VeraSUN73** [satijalab/seurat#5908]
[

`Paraxial_mesoderm <- c('TBX6', 'RSPO3', 'DLL1', 'CDX2', 'DLL3', 'DUSP6', 'MSGN1', 'HES7', 'EVX1')
VlnPlot(pmds, features = Paraxial_mesoderm, assay = "RNA", slot = "data", log=F)`

![Screen Shot 2022-05-03 at 17 06 35](https://user-images.githubusercontent.com/84078741/166415833-8bf57b3a-f4f4-4fbc-b3d3-f9bd36edde7a.png)

Hi Seurat team,

I was trying to plot violin plot for gene expression, but it gives negative values for some genes, like the first one "TBX6". I have checked my data matrix doesn't have negative values and I also specified to use data slot in RNA assay.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  Can you provide two pieces of information?

First, what is the result of these three commands:
```
DefaultAssay(pmds)

test <- FetchData(object = pmds, vars = "TBX6")

range(test)
```

Second, can you please provide the code you used to process the object prior to attempting to plot these features?

Thanks!
Sam

**Comment by VeraSUN73** [comment]
Hi Sam,

The DefaultAssay(pmds) is "RNA", and the range(test) is 0 to 7.21965732933839e-05. I basically use the standard pipeline to process my single cell data matrix, didn't change much.
`pmds <- CreateSeuratObject(df, meta.data = me)
pmds <- NormalizeData(pmds)  
pmds <- FindVariableFeatures(pmds)
pmds <- ScaleData(pmds)
pmds <- RunPCA(pmds, npcs = 50)
pmds <- RunUMAP(pmds, reduction = "pca", dims = 1:50, 
                    umap.method = "umap-learn", metric = "correlation")
pmds <- FindNeighbors(pmds, reduction = "pca", dims = 1:50)
`

**Comment by samuel-marsh** [comment]
Hi,

hmmm that's strange.  What does plot look like if you run:

```
test <- FetchData(object = pmds, vars = c("TBX6", "orig.ident"))

ggplot(test, aes(x = orig.ident, y = TBX6)) +
  geom_violin()
```

**Comment by rsatija** [comment]
Thanks sam. This is essentially what VlnPlot is doing. ggplot can occasionally return strange plots when there is a very small range of values (in this case, 10^-5).

Please do re-open this issue if the code suggested above returns only positive values (demonstrating that the issue is with VlnPlot)

**Comment by mi-lew** [comment]
I have the same issue. The range is very small:


> DefaultAssay(cdsF)
[1] "RNA"
> test <- FetchData(object = cdsF, vars = "IFNG")
> range(test)
[1] 0.000000e+00 5.589442e-14

> summary(range(GetAssayData(cdsF, layer="data")["IFNG",], na.rm=TRUE))
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 1.397e-14 2.795e-14 2.795e-14 4.192e-14 5.589e-14 


The VlnPlot gives me this:
`VlnPlot(cdsF, 
        features = "IFNG", 
        layer = "data",
        assay = "RNA",
        pt.size = 0)`

<img width="685" height="476" alt="Image" src="https://github.com/user-attachments/assets/244c94bf-246d-4f79-a854-6f69eea87065" />

...while the simple ggplot shows this:
`test1 <- FetchData(object = cdsF, vars = c("IFNG", "sample"), layer = "data")
ggplot(test1, aes(x = sample, y = IFNG)) +
  geom_violin()`

<img width="510" height="382" alt="Image" src="https://github.com/user-attachments/assets/f0718242-bd5a-40e8-8c95-c0c990c31df4" />
