### ISSUE TITLE
Using my interested da peaks in  `enriched.motifs `  turns into an error.

### ISSUE THREAD

**Issue by jiangpuxuan** [satijalab/seurat#5909]
Here is my code:

```
de.motif <- rownames(f30.atac)[1:50]
enriched.motifs <- FindMotifs(
  object = mydata,,
  features = de.motif,
)
```
```
head(de.motif)
head(enriched.motifs)
```
<img width="540" alt="1651584391(1)" src="https://user-images.githubusercontent.com/81287604/166461420-54676a6f-4051-4a0a-aca2-3346fba07716.png">

Everything is OK. 

And I tried to use my interested da peaks in `enriched.motifs` :

```
enriched.motifs <- FindMotifs(
  object = mydata,
  features = the da peaks in some interested cells ,
)
```
But the error is:
```
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian", : 'x' contains missing values
```
Thank you for your help!

**Comment by timoast** [comment]
Please open this issue in the Signac repository
