### ISSUE TITLE
Link to FIt-SNE Fork

### ISSUE THREAD

**Issue by linqiaozhi** [satijalab/seurat#591]
I am very glad to see that FIt-SNE is an option for RunTSNE and hope that it will be useful to Seurat users! 

One quick question--I noticed that the documentation here:

https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/man/RunTSNE.Rd#L33

links the user to a fork of FIt-SNE that is 19 commits behind the current version of FIt-SNE. Should this link perhaps be updated to the [actual](https://github.com/KlugerLab/FIt-SNE) FIt-SNE repo? Or, if you'd prefer to link to a fork--perhaps the recent changes we've made could be merged to that fork? Among other changes, there was a pretty bad memory leak that we fixed and might be present still in the fork you are linking to.

**Comment by mschilli87** [comment]
@linqiaozhi: I suggest to directly open a PR so it can be accepted with a single click. :wink:
