### ISSUE TITLE
Label transfer using subset of PBMC multimodal reference 

### ISSUE THREAD

**Issue by owenwilkins** [satijalab/seurat#5915]
Hello, 

I was hoping someone may be able to provide some guidance on performing label transfer using the multimodal PBMC reference (used in [this](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html) vignette) when the query data only contains a subset of PBMC cell types. 

In my case, I have a dataset that was sorted and should contain only T-cells, therefore the other cell types in the reference should be absent from this query dataset. In theory, I would expect the label transfer to be more accurate if the cell types missing from the query were also absent from the reference. 

Is there a suggested workflow for performing label transfer using the PBMC reference in this case? It seems like downloading the raw data of the reference and recalculating the WNN graph after selection for the cells of interest may be the way to do this, however was hoping someone could provide some advice on this use case. 

Thanks in advance,

**Comment by yuhanH** [comment]
Hi,
You can use the default workflow in your situation. The default workflow can handle issue directly.
