### ISSUE TITLE
use of SCT assay slots when using vars.to.regress

### ISSUE THREAD

**Issue by ceesu** [satijalab/seurat#5916]
Hello, thanks for your work on this package. I am hoping to get more clarification on the use of the `counts`, `data` and `scale.data` slots coming out of SCT and when to use each when we specify variables to regress out. This question is related to #3715 however it doesn't seem like that issue is still active.

The wiki seems like it used to describe the use of the slots as follows (summarized from [here](https://github.com/friedue/Notes/blob/master/Seurat.md), I can't seem to find the original source): `counts` = original expression matrix before any processing,  `data` =normalized and log-transformed data, `scale.data`= z-score version of `data`.

I have the following questions about it:

1.  If I understand correctly, it was mentioned e.g. in #1739 #3061 that the command `SCTransform()` regresses out `nCount_RNA` by default. Is this a different procedure than what is done for variables specified using the `vars.to.regress` option of this function?   If you don't mind, are there details on the regression procedure described somewhere? e.g. would it mean the function does some kind of internal calculation, vs. using the exact contents of the current `nCount_RNA` column in the metadata of the Seurat object?

2. After specifying `vars.to.regress` , where is the corrected and normalized version of the count matrix stored, would it be `data`  or `scale.data`? i.e. is it still true that `scale.data` is exactly the z-score normalized version of `data`?
3. Do answers to the above change for `vst.flavor="v2"`? Is one of the versions of SCTransform. (v2 vs. non-v2) better for getting a normalized corrected count matrix for downstream applications? However it seems like it was already suggested [pre-v2 ](https://satijalab.org/seurat/articles/sctransform_vignette.html) that the SCT procedure

>   improves common downstream analytical tasks such as variable gene selection, dimensional reduction, and differential expression.

Thank you,

**Comment by saketkc** [comment]
This is documented in the [help doc](https://satijalab.org/seurat/reference/sctransform): 
> Returns a Seurat object with a new assay (named SCT by default) with counts being (corrected) counts, data being log1p(counts), scale.data being pearson residuals; sctransform::vst intermediate results are saved in misc slot of the new assay.

The pearson residuals (`scale.data`) slot adjust for nCount_RNA using a regularized negative-binomial model as described in this [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1). The `vars.to.regress` essentially uses a linear model to perform a second regression and regresses out the effect of a given covariate: https://github.com/satijalab/seurat/blob/3bee84a8d710b7ee0022b929dab1df2f6ba26fdb/R/preprocessing.R#L1810. This only changes the `scale.data` slot and not the `data` slot.

In `vst.flavor="v2"` we provide a more parsimonious regularization and improved the variable feature selection procedure - the core method is still a regularized negative binomial (regularization being performed on the overdispersion parameter such that genes with similar mean expression have similar overdispersion). See the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9) for details. For corrected counts, the procedure is same as before except that with multiple datasets we now perform correction based on minimum of the median UMI (see the paper for details) - this is useful if you wish to perform DE across two different SCT normalized datasets with differences in sequencing depth. See [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for an example.

**Comment by yinshiyi** [comment]
> . This only changes the `scale.data` slot and not the `data` slot.

* regresses out `nCount_RNA` or if the corrected-count data is used.
Then the `data` will be changed accordingly as log1p of correct-`count`. 
https://github.com/satijalab/seurat/blob/3bee84a8d710b7ee0022b929dab1df2f6ba26fdb/R/preprocessing.R#L1803
This SetAssayData is ran after 
https://github.com/satijalab/seurat/blob/3bee84a8d710b7ee0022b929dab1df2f6ba26fdb/R/preprocessing.R#L1784C1-L1796C4

* But the `vars.to.regress` will only change `scale.data`
