### ISSUE TITLE
Cell Cycle Scoring Gene Order

### ISSUE THREAD

**Issue by chenv3** [satijalab/seurat#5917]
I was running cell cycle scoring on a sample and in the process observed that changing the order of the provided gene list results in slightly different scoring and a change in the phase call for some cells.  For example, the following two calls resulted in different phase calls for 241 cells out of 6393. 

`CellCycleScoring(seur, s.features = cc.genes.updated.2019$s.genes, g2m.features = cc.genes.updated.2019$g2m.genes, set.ident = TRUE)`

`CellCycleScoring(seur, s.features = sort(cc.genes.updated.2019$s.genes), g2m.features = sort(cc.genes.updated.2019$g2m.genes), set.ident = TRUE)`

Since I did not expect the gene order to impact the results, I was wondering if it would be possible to get more information about how the scoring is calculated. Is there a recommendation for how to decide the order of genes provided when running scoring?

Thank you

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The dev team may be able to clarify but I would bet that this is on the random selection of "control" genes.  If the selection of control genes occurs in different order from different expression bins that could result in different control genes being selected and therefore effect the overall score and subsequent phase determination.  You can actually see this if you run the same gene list in same order but change the seed.

```
pbmc <- pbmc3k.SeuratData::pbmc3k.final

pbmc1 <- CellCycleScoring(pbmc, s.features = cc.genes.updated.2019$s.genes, g2m.features = cc.genes.updated.2019$g2m.genes, set.ident = TRUE)

pbmc2<- CellCycleScoring(pbmc, s.features = cc.genes.updated.2019$s.genes, g2m.features = cc.genes.updated.2019$g2m.genes, set.ident = TRUE, seed = 500)

test <- which(pbmc1@meta.data$Phase != pbmc2@meta.data$Phase)
length(test)

[1] 229
```

My guess is this means that there are number of cells that are on border of phase determination and therefore a switch in the control gene selection which changes score results in different phase call.  Module scores as calculated in Seurat can also be heavily biased by the composition make up of the dataset as it effects control gene selection and subsequent determination of gene expression enrichment.

Best,
Sam

**Comment by yuhanH** [comment]
Thanks @samuel-marsh  for your clear explanation. 

hi @chenv3 
The difference results from the randomness of negative control genes.
