### ISSUE TITLE
Indexing error from MergeSeurat( )

### ISSUE THREAD

**Issue by 891404** [satijalab/seurat#592]
Hi all,
After reinstalling Seurat today, I have been having issues with running the MergeSeurat( ).
![image](https://user-images.githubusercontent.com/40044501/42296663-6d5a03dc-7fad-11e8-9b74-e06d6d1de48b.png)
I was hoping to solve this issue by adding identifiers to the cell names to ensure there were no duplicates (this was not needed prior to the reinstallation today, meaning the cell names could not have been duplicated. But I tried this anyway)
![image](https://user-images.githubusercontent.com/40044501/42296729-f8eacf9e-7fad-11e8-8a30-badc667fbf3d.png)
The current Seurat version I am using is 2.3.2.

**Comment by andrewwbutler** [comment]
Please update to v2.3.3 to resolve this issue.
