### ISSUE TITLE
 Peak-Calling - Group.by  ERROR   -> Requested grouping variable not found after peck calling on clusters

### ISSUE THREAD

**Issue by matteozoia4** [satijalab/seurat#5920]
Dear Satijalab,

My aim is to run a peak calling per clustered regions based on the variable "celltype" in the metadata list of the object "heart".
With the final aim to call peaks specific per each cluster in a given region.
It seems that no peaks per cell type are found.

Many thanks for your help!

Code :

`DefaultAssay(heart) <- "ATAC"
Macs2PeaksCulsters <- CallPeaks(heart, group.by = "celltype", macs2.path = "/Users/mz20v137/opt/anaconda3/envs/htseq_pipelines/bin/macs2")`

`Macs2PeaksCulsters <- keepStandardChromosomes(Macs2PeaksCulsters, pruning.mode = "coarse")
Macs2PeaksCulsters <- subsetByOverlaps(x = Macs2PeaksCulsters, ranges = blacklist_mm10, invert = TRUE)`

`macs2_counts_Clusters <- FeatureMatrix(
  fragments = Fragments(heart),
  features = Macs2PeaksCulsters,
  cells = colnames(heart)
)`

`heart[["Macs2PeaksClusters"]] <- CreateChromatinAssay(
  counts = macs2_counts_Clusters,
  fragments = frag.file,
  annotation = annotations
)`

`DefaultAssay(heart) <- "Macs2PeaksClusters"
peak_plot <- PeakPlot(
  heart,
  region = "chr3-66337001-67337000",
  assay = NULL,
  peaks = NULL,
  group.by = 'celltype'
) `

Warning message:

`In PeakPlot(heart, region = "chr3-66337001-67337000", assay = NULL,  :
  Requested grouping variable not found`

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I'd suggest posting this issue to the Signac repo as is it an issue with Signac function and not Seurat.  https://github.com/timoast/signac

Best,
Sam

**Comment by matteozoia4** [comment]
Thank you!
