### ISSUE TITLE
FindVariableFeatures after SplitObject and subset: Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :    invalid 'x'

### ISSUE THREAD

**Issue by chairchild** [satijalab/seurat#5922]
```r
# insert reproducible example here
```
Error when running FindVariableFeatures:
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :    
   invalid 'x'
R 4.1.1 Seurat_4.0.5 

I used SplitObject to split an integrated seurat object, and then used subset function to extract some target cell. When I FindVariableFeatures, get error.
If I extract same cells directly from the integrated seurat object, it's work.

**Comment by rsatija** [comment]
Most likely you forgot to run NormalizeData prior to running FindVariableFeatures (the function can error out because of the large un-normalized values). Please re-open if this doesn't fix the issue, and we can help debug
