### ISSUE TITLE
CreateSeuratObject() with tab.gz file

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#5923]
Hi,

I would like to re-analyze this dataset https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE104323 however the only files available are:

GSE104323_10X_expression_data_V2.tab.gz
GSE104323_metadata_barcodes_24185cells.txt.gz
GSE104323_series_matrix.txt.gz

How can I create a Seurat Object from this?

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful!  So you just need to read the data in and then as long as data is in gene x cell format (row x col) it can be used to create Seurat object.

```
library(tidyverse)
library(Seurat)
library(stringi)

# read raw data
raw_data <- data.table::fread("~/Downloads/GSE104323_10X_expression_data_V2.tab.gz", data.table = FALSE)

# move gene names to row names
first_col_name <- colnames(test[1])
raw_data <- raw_data %>%
  column_to_rownames(first_col_name)

# change cell prefix so that Seurat can read entire prefix when creating object
colnames(raw_data) <- stri_replace_first_fixed(str = colnames(raw_data), pattern = "_", replacement = "-")

# Create Seurat Object
seurat_obj <- CreateSeuratObject(counts = raw_data, names.field = 1, names.delim = "_")
```

Then you can read in meta data and add to the existing object:
```
# read in meta data
meta_data <- data.table::fread("~/Downloads/GSE104323_metadata_barcodes_24185cells.txt.gz", data.table = FALSE, check.names = TRUE)

# remove empty rows
meta_data <- meta_data[1:24185, ]

# change barcodes to match the change we made when creating seurat object
meta_data$Sample.name..24185.single.cells. <- stri_replace_first_fixed(str = meta_data$Sample.name..24185.single.cells., pattern = "_", replacement = "-")

# Move barcodes to rownames
first_col_name <- colnames(meta_data[1])

meta_data <- meta_data %>% 
  column_to_rownames(first_col_name)

# Add to seurat object
seurat_obj <- AddMetaData(object = seurat_obj, metadata = meta_data)
```

Best,
Sam

**Comment by giorgiatosoni** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful! So you just need to read the data in and then as long as data is in gene x cell format (row x col) it can be used to create Seurat object.
> 
> ```
> library(tidyverse)
> library(Seurat)
> library(stringi)
> 
> # read raw data
> raw_data <- data.table::fread("~/Downloads/GSE104323_10X_expression_data_V2.tab.gz", data.table = FALSE)
> 
> # move gene names to row names
> first_col_name <- colnames(test[1])
> raw_data <- raw_data %>%
>   column_to_rownames(first_col_name)
> 
> # change cell prefix so that Seurat can read entire prefix when creating object
> colnames(raw_data) <- stri_replace_first_fixed(str = colnames(raw_data), pattern = "_", replacement = "-")
> 
> # Create Seurat Object
> seurat_obj <- CreateSeuratObject(counts = raw_data, names.field = 1, names.delim = "_")
> ```
> 
> Then you can read in meta data and add to the existing object:
> 
> ```
> # read in meta data
> meta_data <- data.table::fread("~/Downloads/GSE104323_metadata_barcodes_24185cells.txt.gz", data.table = FALSE, check.names = TRUE)
> 
> # remove empty rows
> meta_data <- meta_data[1:24185, ]
> 
> # change barcodes to match the change we made when creating seurat object
> meta_data$Sample.name..24185.single.cells. <- stri_replace_first_fixed(str = meta_data$Sample.name..24185.single.cells., pattern = "_", replacement = "-")
> 
> # Move barcodes to rownames
> first_col_name <- colnames(meta_data[1])
> 
> meta_data <- meta_data %>% 
>   column_to_rownames(first_col_name)
> 
> # Add to seurat object
> seurat_obj <- AddMetaData(object = seurat_obj, metadata = meta_data)
> ```
> 
> Best, Sam

Thanks a lot!!

**Comment by samuel-marsh** [comment]
No problem!!
