### ISSUE TITLE
Low populated clusters after FindMultiModalNeighbors 

### ISSUE THREAD

**Issue by Baboon61** [satijalab/seurat#5925]
I am analysing Multiomics mouse data sequenced with 10x Genomics' Chromium technology aligned using cellranger-arc. After sample aggregation I run Seurat to process the data and end up creating a weighted nearest neighbor from both RNA and ATAC modalities. Both graphs and clusterings from RNA and ATAC separately look good, but when I run `FindMultiModalNeighbors`, whatever the resolution in `FindClusters` I get a bunch of really small clusters with 2 or 3 cells.
```
object <- FindMultiModalNeighbors(
  object = object,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:15, 2:8),
  weighted.nn.name = "weighted.nn",
  modality.weight.name = "RNA.weight.name",
  snn.graph.name = "wsnn",
  verbose = TRUE
)
```
> Calculating cell-specific modality weights
> Finding 20 nearest neighbors for each modality.
> Calculating kernel bandwidths
> Warning message in FindMultiModalNeighbors(object = object, reduction.list = list("pca", :
> "The number of provided modality.weight.name is not equal to the number of modalities. RNA.weight peaks.weight are used to store the modality weights"
> Finding multimodal neighbors
> Constructing multimodal KNN graph
> Constructing multimodal SNN graph
```
object <- FindClusters(object, resolution = 0.3, verbose = FALSE, graph.name="wsnn")
object$seurat_clusters_BiMod <- object$seurat_clusters
object <- RunUMAP(object, nn.name = "weighted.nn", assay = "RNA", reduction.name="umap_BiMod", verbose = TRUE)
```
> 10:21:18 UMAP embedding parameters a = 0.9922 b = 1.112
> 10:21:21 Commencing smooth kNN distance calibration using 1 thread
> 10:21:25 Initializing from normalized Laplacian + noise
> 10:21:28 Commencing optimization for 200 epochs, with 1605376 positive edges
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> 10:22:00 Optimization finished
> Warning message:
> "Cannot add objects with duplicate keys (offending key: UMAP_) setting key to original value 'umap_bimod_'"

![image](https://user-images.githubusercontent.com/10078276/167125882-a8dd5b99-431b-47b0-8571-d60773b40675.png)

```
> table(object$seurat_clusters_BiMod)
    0     1     2     3     4     5     6     7     8     9    10    11    12 
11222  8496  7770  6097  5977  5862  5664  2833  1252  1179  1012   708   413 
   13    14    15    16    17    18    19    20    21    22    23    24    25 
  333     3     3     2     2     2     2     2    88     2     2     2     2 
   26    27    28    29    30 
    2     2     2     2     2 
```
I tried to investigate different clustering resolutions, these small clusters are highlighted at low resolution and are reliable whatever the resolution.
```
#From clustree package
```
![image](https://user-images.githubusercontent.com/10078276/167126241-3e584dcb-0a28-4634-8bf2-019fa3bb8dbc.png)
Here are some metadata from one of the problematic cluster for the bimodal clustering (cluster 17).
```
                   orig.ident nCount_RNA nFeature_RNA nCount_ATAC nFeature_ATAC
TACCTTAGTTGCAATG-2  PeakCtrl2       6488         2569       17005          7166
TACCTTTAGTCCTTCA-2  PeakCtrl2       6505         2604       21224          8624
                   orig.ident_merge model frequency_count mononucleosomal
TACCTTAGTTGCAATG-2             Ctrl  Ctrl           10894            3155
TACCTTTAGTCCTTCA-2             Ctrl  Ctrl           13366            3735
                   nucleosome_free reads_count percent.mt nucleosome_signal
TACCTTAGTTGCAATG-2            5973       44109   4.993835         0.5002701
TACCTTTAGTCCTTCA-2            7517       51611   3.489623         0.5079799
                   nucleosome_percentile TSS.enrichment TSS.percentile
TACCTTAGTTGCAATG-2                  0.12       8.492560           0.82
TACCTTTAGTCCTTCA-2                  0.13       9.518637           0.92
                   nCount_peaks nFeature_peaks      FRiP      pANN
TACCTTAGTTGCAATG-2         9261           7051 0.8501010 0.3163265
TACCTTTAGTCCTTCA-2        11556           8480 0.8645818 0.3265306
                   DF.classifications Amulet_multiplet snn_RNA_res.2
TACCTTAGTTGCAATG-2            Singlet          singlet             2
TACCTTTAGTCCTTCA-2            Doublet          singlet             3
                   seurat_clusters_RNA snn_ATAC_res.0.5 seurat_clusters_ATAC
TACCTTAGTTGCAATG-2                   2                3                    3
TACCTTTAGTCCTTCA-2                   3                3                    3
                   RNA.weight peaks.weight wsnn_res.0.3 seurat_clusters_BiMod
TACCTTAGTTGCAATG-2          1 5.667721e-27           17                    17
TACCTTTAGTCCTTCA-2          1 2.787833e-13           17                    17
                   doublets
TACCTTAGTTGCAATG-2  Singlet
TACCTTTAGTCCTTCA-2  Singlet
```
![image](https://user-images.githubusercontent.com/10078276/167130205-61e9a5ff-6c25-4624-81bd-fcf9625a08e1.png)

Since cells in this small clusters (i.e cluster 17) are part of bigger clusters in RNA projection and ATAC projection, I did not check gene markers or specific accessibility regions for these clusters. I assume that they are not that different in genes expression and genomic accessibility compare to the other neighbor cells to explain such clustering.

**Comment by yuhanH** [comment]
HI
You can set  `prune.SNN = 0` in `FindMultiModalNeighbors` which usually can solve this issue. 
If the problem is not solved, i will reopen this issue.

**Comment by Baboon61** [comment]
Hello, the above solution fixed my issue for the `FindMultiModalNeighbors` function.
I am rerunning some RNA data and I got the same weird behaviour again after Harmony integration over 100k cells. This time the `prune.SNN = 0` in `FindNeighbors` is not fixing the issue.
When I am reducing the number of selected PCs (to 10/15PCs) to find the neighbors, the cluster distribution looks fine.
The weird clusters are located within huge populations, those are not isolated cells.

I tried the same workflow with the `ifnb` dataset and it is working like a charm.
```
library(Seurat)
library(SeuratData)
library(patchwork)

InstallData("ifnb")
LoadData("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")

ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
    DefaultAssay(x) <- "RNA"
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

ifnb <- merge(ifnb.list[[1]], y = ifnb.list[2], merge.data = TRUE)
ifnb <- FindVariableFeatures(ifnb, selection.method = "vst", nfeatures = 2000)
ifnb <- ScaleData(ifnb, features = rownames(ifnb))
ifnb <- RunPCA(ifnb)
ifnb <- RunHarmony(ifnb, "stim", theta=1, lambda=1, sigma=0.1, plot_convergence = FALSE)
ifnb <- FindNeighbors(ifnb, reduction = "harmony", dims = 1:40, graph.name="snn_harmony")
ifnb <- FindClusters(ifnb, resolution = 3, graph.name="snn_harmony")
table(ifnb$seurat_clusters)
```
