### ISSUE TITLE
 'Realloc' could not re-allocate memory - IntegrateData

### ISSUE THREAD

**Issue by batalha23** [satijalab/seurat#5926]
Hi! I'm trying to run IntegrateData on a list of 4 datasets (total 3.6Gb) and I keep getting this error message:

```
Error in (if (is.logical(from)) ..m2lgC else .m2dgC)(from) : 
  'Realloc' could not re-allocate memory (345696000 bytes)

```

This is already using the reciprocal PCA and reference-based integration suggested for large daatsets (https://satijalab.org/seurat/articles/integration_large_datasets.html), after getting the error message mentioned in #2133 (https://github.com/satijalab/seurat/issues/2133). In this case, I am using only one of my datasets as reference.

Could this be an issue of the dataset size, and is there any way (other than subsampling) to reduce it or make the process less memory-intensive? Or, alternatively, to determine how much RAM will be needed to run this integration (and maybe take it to a different computer - I'm currently running this on a PC with 16 Gb installed RAM)?

Below you may find the code for the complete integration workflow:

```
#Create list of objects to be integrated
HER2obj_list <- list(db006, db007, db008, db012)

#Select variable features (3000 most variable, from SCT)
integ_features <- SelectIntegrationFeatures(object.list = HER2obj_list, nfeatures = 3000)

#Prepare the SCT object list for integration
HER2obj_list <- PrepSCTIntegration(object.list = HER2obj_list, anchor.features = integ_features)

#Find anchors between datasets
integ_anchors <- FindIntegrationAnchors(object.list = HER2obj_list, reference = c(1), normalization.method = "SCT", reduction = "rpca", dims = 1:50, anchor.features = integ_features)

#Integrate datasets
HER2baseline_1_int <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT", dims = 1:50)

```

Thank you!

**Comment by rsatija** [comment]
Please see our recent vignette on 'Atomic Sketch Integration' here : https://satijalab.org/seurat/articles/atomic_integration.html

This workflow enables the integration of extremely large datasets with substantially reduced memory usage
