### ISSUE TITLE
Questions about reproducing process

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#5927]
Hi, sorry to disturb you. Now I intend to set different seeds for Seurat v4 to evaluate its performance, so I wonder if there are any methods I can use to help me achieve this target. Could I directly use set.seed()? Thanks a lot.

**Comment by andrewwbutler** [comment]
Hi,

Functions that have a stochastic element should have a parameter for the random seed that you can directly set. For example in `RunPCA`, you can set `seed.use`.
