### ISSUE TITLE
Gene's show up in the Dim plots and violin plots as very diffrent but not in my differential analysis

### ISSUE THREAD

**Issue by haquett** [satijalab/seurat#5929]
Hello!
I have a Seurat object that was integrated and the dim plots and violin plots show a clear difference between a gene but in the differential "FindMarkers" list, it is not present. What does this mean?

Thanks!

**Comment by haquett** [comment]
VlnPlot(immune.combined1, features = c("Il4"), group.by = "orig.ident")
Idents(object = immune.combined1) <- immune.combined1@meta.data$orig.ident
markersRNA <- FindMarkers(object = immune.combined1, ident.1 = "LDS", ident.2 = "SeuratProject")

Attached is the vln plot for IL4. I didn't attach the "markersRNA csv", but Il4 was not included in that analysis when I expected it based on the vln plot

**Comment by haquett** [comment]
[il4.pdf](https://github.com/satijalab/seurat/files/8653208/il4.pdf)
Sorry, there is the violin plot I am referring to

**Comment by haquett** [comment]
> 
Hi Sam, see my response in the comments! Thanks.

**Comment by haquett** [comment]
Hi Sam,

I replied to your request  in the thread. Let me know if you need more
information.

Thanks so much,
Tamara

**Comment by timoast** [comment]
It's not clear from the plot that the gene is necessarily differentially expressed between the groups. I'd suggest lowering the `logfc.threshold` and `min.pct` parameters in `FindMarkers()` and check the fold change in expression for IL4 between the groups.
