### ISSUE TITLE
Selecting the highest expressing cells

### ISSUE THREAD

**Issue by jasminelmah** [satijalab/seurat#5931]
Hello!

I want to rank the cells in my expression matrices by most highly expressing cell, then subset that matrix to obtain eg the first 100 most highly expressing cells. My workflow is a little extended - I am combining five species, each which have treatment batches, so I have normalized each species' raw UMI matrix separately by SCTransform, integrated the within-species batches, then integrated a second time across species. This has produced biologically feasible results.

My questions: 
1) At what stage should I select the most highly expressing cells? My guess is after normalization, which I do with SCTransform? 
2) Which type of normalized data set should I be identifying the most highly expressed cells? I have been using the pearson residuals for downstream work from seurat_object[["SCT"]]@scale.data, but I am not sure if higher positive-value residuals correspond to higher expression? Should I be ranking cells by the corrected UMI counts in seurat_object[["SCT"]]@counts ?
3) What effect do you think selecting the most highly expressing cells will have? My hope is that cells of the same cell type will cluster together more effectively. If this isn't true, what would you suggest to increase clustering success?

Thanks for your help!

**Comment by saketkc** [comment]
I am not sure I understand the motivation of selecting the highest expressing cells - do you mean highly expressed genes? A cell with high "expression" will have higher total UMI (`nCount_RNA`). Clustering is dependent on the features, i.e. genes and not the cells. Variable Features are selected during integration by [SelectIntegrationFeatures](https://satijalab.org/seurat/reference/selectintegrationfeatures) which allows you to set the number of features `nfeatures`.
