### ISSUE TITLE
Error in AddModuleScore

### ISSUE THREAD

**Issue by xinmiaoyan** [satijalab/seurat#5932]
hello, I encountered a error when I want to use AddModuleScore to calculate a score. 

feature_name = c("IL23","TNF","CXCL9","CXCL10","CXCL11","CD86","IL1A","IL1B","IL6","CCL5","IRF5","IRF1","CD40","IDO1","KYNU","CCR7")

Do you have any suggestion to solve this problem? Appreciate it!

**Comment by samuel-marsh** [comment]
Hi,

What is the error message that you are getting?  Could you please post full code that you are running?

Thanks!
Sam

**Comment by xinmiaoyan** [comment]
hi,  Sam, I solved this problem by transferring the gene vector into list. 
the whole code is 
feature_name = c("IL23","TNF","CXCL9","CXCL10","CXCL11","CD86","IL1A","IL1B","IL6","CCL5","IRF5","IRF1","CD40","IDO1","KYNU","CCR7")
obj = AddModuleScore(obj, features = list(feature_name), name='CYCLE')

but it still has one more problem that in meta.data which has a new column should be named 'CYCLE', but it was labeled as 'CYCLE1' automatically.

I tried a lot, and confirmed that maybe a little bug. So do you have any solution for it? Appreciate it!

**Comment by samuel-marsh** [comment]
Hi,

Yes to create scores of set of genes you need to have things as a list.  In terms of name that is the default for the function.  You can always rename the column later manually if you need to change it.

Best,
Sam
