### ISSUE TITLE
FeaturePlot increase maximum expression limit

### ISSUE THREAD

**Issue by kygithubtokenaccount** [satijalab/seurat#5934]
Hi,

I'm trying to change the parameters of FeaturePlot for some of my genes of interest.  I can set the max cutoff to decrease the maximum limit of the gene expression displayed on the plots.  Is there a way that allows me to increase the upper limit of the gene expression instead?  

Thank you very much

**Comment by samuel-marsh** [comment]
Hi,

Do you simply mean that you want the displayed expression scale to go above the actual maximum expression level in the cells of the object?

Best,
Sam

**Comment by kygithubtokenaccount** [comment]
Thanks for the reply, Sam.  Yes, correct.  I want to display the expression scale to go above the maximum expression level in the cells of the object.

**Comment by kygithubtokenaccount** [comment]
Thank you very much Sam!  The code is what I was looking for

**Comment by samuel-marsh** [comment]
Happy to help.
