### ISSUE TITLE
Ridgeplot Documentation slot parameter

### ISSUE THREAD

**Issue by Rohit-Satyam** [satijalab/seurat#5935]
I believe it's a typo. The ridge plot [documentation ](https://satijalab.org/seurat/reference/ridgeplot)says:

><html>
<body>

slot | Use non-normalized counts data for plotting
-- | --

</body>
</html>

I believe it should be log-normalized since the data slot stores log-normalized counts, isn't it??

**Comment by timoast** [comment]
Thanks, this should be the name of the slot used. The documentation is now fixed on the develop branch.
