### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ashmitadey** [satijalab/seurat#5937]
Hi, I'm following the guided seurat tutorial, and when I get to the RunPCA step I get this error for some particular datasets:
Error in irlba(A = t(x = object), nv = npcs, ...) : max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Please help me to solve this.

Thanks in advance
Ashmita

**Comment by ashmitadey** [comment]
Thank you Sam
Unfortunately I am not able to solve the problem even after changing the parameters.

Best wishes
Ashmita

**Comment by samuel-marsh** [comment]
Hmm.  Can you please provide the full code you are running and what version of Seurat you are using?

Thanks,
Sam

**Comment by ashmitadey** [comment]
I am using Seurat version 4.0.0 and my entire code is as follows:
`
nbt.data=read.delim("path/GSE172184_processed_data_countdata.tsv.gz",header = T, row.names=1, sep="", as.is=T)
library(dplyr)
library(Seurat)
pbmc <- CreateSeuratObject(counts=nbt.data, min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(pbmc), 10)
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
print(pbmc[["pca"]], dims = 1:15, nfeatures = 10)
VizDimLoadings(pbmc, dims = 6, reduction = "pca")
`

**Comment by timoast** [comment]
This dataset only contains 38 samples, and the default number of PCs to compute is 50. The number of PCs needs to be lower than the number of samples and features. You can lower the `npcs` parameter in `RunPCA()` to solve this issue, although you might want to check that the data is what you're expecting it to be if this is supposed to be a scRNA-seq dataset.
