### ISSUE TITLE
What would be the best way to do hierarchical clustering with Seurat or any other packages with Seurat object?

### ISSUE THREAD

**Issue by yklee020** [satijalab/seurat#594]
Hi all,
I am wondering if anyone has done hierarchical clustering with Seurat object in other packages. I understand developers trying to standardize with S4 class object so I want to know what could be the best way to analyze my 10x data with hierarchical clustering method. I will thank you in advance for your insights.

**Comment by satijalab** [comment]
We don't have internal functions for this in Seurat, but you can of course use hclust to cluster your data, and then use SetIdent to place the resulting cluster IDs back into the Seurat object.
