### ISSUE TITLE
leidenalg not found even though it is installed (conda env)

### ISSUE THREAD

**Issue by sonodeiv** [satijalab/seurat#5944]
This is how I created my conda environment:

> conda create -n r413py39 python=3.9
> conda activate r413py39
> conda install -c conda-forge r-base=4.1.3
> conda install -c conda-forge r-seurat=4.1.1
> conda install -c conda-forge leidenalg=0.8.10=py39h0e26352_0

when running Seurat::FindClusters() I get:
> Error: Cannot find Leiden algorithm, please install through pip (e.g. pip install leidenalg).

Even though
> pip freeze | grep leiden

gives:
> leidenalg==0.8.10

I really can't find any solution online so any help would be much appreciated,
Thanksss

**Comment by maxim-h** [comment]
I can also attest to the same problem. I'm using `venv` and configured the correct interpreter through both Rstudio GUI and `reticulate`.

The suggestion from @samuel-marsh doesn't apply to my case because `reticulate::py_discover_config()` shows the correct configuration to begin with. 

In fact when I run the same check as in the `FindClusters()` function I get the correct result:
```r
> py_module_available(module = "leidenalg")
[1] TRUE
```

It is only when I actually run `FindClusters()` `reticulate` seems to forget completely about the configured environment and throws this error.

 The only workaround that I've found so far is the following:
     1. Open a shell
     2. Activate the `venv` with `source [PATH TO VENV]/bin/activate`
     3. From this shell start `R` or `Rstudio`
     4. Run `Seurat::FindClusters()`

So I'm not sure if it's strictly `reticulate`'s problem since in my case it identifies python environment correctly and can even see the `leidenalg` package. The problem arises only when calling the `Seurat` code.

**Comment by maxim-h** [comment]
One other thing I found is that if I use the same environment and just try to run the `leiden::leiden` function it actually works. 
I.E.:
```r
library(leiden)
leiden(object = seurat@graphs$SCT_snn)
```
It actually works. The `library(leiden)` line gives some 
<details>
<Summary>warnings</Summary>
Unable to set up conda environment r-reticulate
run in terminal:
conda init
conda create -n r-reticulate
conda environment r-reticulate installed
Unable to install python modules igraph and leidenalg
run in terminal:
conda install -n r-reticulate -c conda-forge vtraag python-igraph pandas umap learn
python modules igraph and leidenalg installed
</details>
but that doesn't seem to cause any problems downstream. For clarity, I don't even have conda installed. 

\
Now then again, if I change the source code of `Seurat:::RunLeiden` and exclude the following check 

https://github.com/satijalab/seurat/blob/3bee84a8d710b7ee0022b929dab1df2f6ba26fdb/R/clustering.R#L1676-L1681

and retry the `FindClusters(seurat, algorithm = 4, verbose = TRUE, group.singletons=F, resolution = .8)` I get:
```r
Error in py_module_import(module, convert = convert) :
ModuleNotFoundError: No module named 'numpy'
```
Seemingly coming from exactly the same function (`leiden::leiden`) that worked when ran separately. 

Even more so, just running the `Seurat:::RunLeiden` also works:
```r
> Seurat:::RunLeiden(object = seurat@graphs$SCT_snn, method = "matrix")
   [1]  7  9  4 13  2  9 10  3  9  3  6 14  6  2 12  8  4  9  5  5  3  6  4  5  9  2  4
  [28] 13  1  9  2  8  5  1  1  2  3  1 12  4  1  3  1  1  1  4  4  8  7  1  5  2  5  1
  [55]  5  8  8  2 10  2  5  9  2  6  1 10 13 13  4  3  7  1  5 12  5  8  3  3 13  9 11
...
```
So literally all of the components of the `Seurat::FindClusters` work fine when ran outside of it and `reticulate` doesn't cause any problems. All the python code runs and returns the results.
But once you call the `Seurat::FindClusters` itself `reticulate` just forgets what was going on.

**Comment by mojaveazure** [comment]
Please use standard CPython that either came with your computer or from [Python directly](https://www.python.org/). [We've noticed issues with reticulate and Anaconda not playing nicely together](https://github.com/satijalab/seurat/issues?utf8=%E2%9C%93&q=is%3Aissue+conda+), and would strongly suggest not using it.

**Comment by rafsanlab** [comment]
Not related to Seurat, since I'm using Scanpy but I got similar error using condas. 
Somehow using version `leidenalg=0.8.8` fix it.

**Comment by corrinenief** [comment]
Solved here with more details https://www.reddit.com/r/bioinformatics/comments/1jbgjt7/how_to_correctly_install_leidenalg_for_seurat/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
