### ISSUE TITLE
DotPlot of specific clusters using the idents parameter giving different average expression levels (?)

### ISSUE THREAD

**Issue by shaln** [satijalab/seurat#5945]
Hi. I have a question regarding the plotting of dot plots. For context, I have a dataset with 4 different cell types, in both Control and Treated conditions. I wanted to find out if any of the differentially-expressed genes within each cluster/cell type was associated with the 'Mitotic Nuclear Division' GO term (GO:0140014), and to make a dot plot of the differentially-expressed genes that are also part of this GO term. 

I first plotted all clusters using this line of code and the plot I have is below the code: 
`t <- DotPlot(data, features=mit.nuc.div.deg, dot.scale=10, split.by="condition", cols="RdBu")
`

![test2](https://user-images.githubusercontent.com/39313061/167825246-138d8aeb-5366-43cf-bc41-45764f8a45f5.png)

From the plot above, you can see that the genes Fgfr3 has a lower average expression than Flna in Cell.2_Treated (blue gray dot vs orange). However, when I opt to plot only the Cell.2 and Cell.4 clusters (plot below), using the `idents` parameter in `DotPlot`, the levels of average expression in the dot plot for these 2 genes look like they are in a more similar range (ie both dots are orange). I understand that the Average Expression scale is slightly different between the two plots in their range (-2 to 2, and -1 to 1), but the difference in average expression between the genes should still stay the same, no? Or am I misinterpreting something here?

![test1](https://user-images.githubusercontent.com/39313061/167825258-04242389-de09-4477-872b-f7b52f97c261.png)

Below is a reproducible example of the code I used to generate the list of genes to be plotted. Thanks in advance for any help and responses to this!

```
library(Seurat)
library(ggplot2)
library(topGO)
library(org.Mm.eg.db)

data <- readRDS("data.RDS")
DefaultAssay(data) <- 'RNA'
Idents(data) <- "cell.type"

# any DEG involved in mitotic nuclear division
deg_cell.1 <- read.csv("data.DGE_cell.1.csv")
deg_cell.2 <- read.csv("data.DGE_cell.2.csv")
deg_cell.3 <- read.csv("data.DGE_cell.3.csv")
deg_cell.4 <- read.csv("data.DGE_cell.4.csv")

# Extract list of genes based on specific GoTerms to create a signature
all.genes <- rownames(data)
geneList <- ifelse(all.genes %in% all.genes, 1, 0)
names(geneList) <- all.genes
GOdata <- new("topGOdata",
              ontology = "BP", 
              allGenes = geneList,
              geneSelectionFun = function(x)(x == 1),
              annot = annFUN.org, 
              mapping = "org.Mm.eg.db", 
              ID = "symbol")

# signature based on expressed genes
allGO<-genesInTerm(GOdata)
mit.nuc.div <- allGO[["GO:0140014"]]

mit.nuc.div.deg1 <- mit.nuc.div[mit.nuc.div %in% deg_cell.1$X]
mit.nuc.div.deg2 <- mit.nuc.div[mit.nuc.div %in% deg_cell.2$X]
mit.nuc.div.deg3 <- mit.nuc.div[mit.nuc.div %in% deg_cell.3$X]
mit.nuc.div.deg4 <- mit.nuc.div[mit.nuc.div %in% deg_cell.4$X]
mit.nuc.div.deg <- c(mit.nuc.div.deg1, mit.nuc.div.deg2, mit.nuc.div.deg3, mit.nuc.div.deg4)
mit.nuc.div.deg <- sort(unique(mit.nuc.div.deg))

t <- DotPlot(data, features=mit.nuc.div.deg, dot.scale=10, idents=c('Cell.2', 'Cell.4'), split.by="condition", cols="RdBu")
```

**Comment by rsatija** [comment]
The DotPlot function scales the color of the dots based on the remainder of the plot, which is why this happens. Note that the scale on the color bar also changes to reflect this.

You can set scale=F, and also use the col.min and col.max arguments, to get around this
