### ISSUE TITLE
Error when using SCTransform

### ISSUE THREAD

**Issue by HediaTnani** [satijalab/seurat#5947]
Hi, 

I'm getting this error lately:
`Error in if (getOption(x = "Seurat.memsafe")) { : 
argument is of length zero`

when running this code:

`seurat.ls <- lapply(X = seurat.ls, FUN = function(x) {
  x <- SCTransform(object = x)
})`

Am I doing something wrong?

**Comment by saketkc** [comment]
What version of Seurat are you using?

**Comment by HediaTnani** [comment]
> What version of Seurat are you using?

`> packageVersion("Seurat")
[1] ‘4.1.1’`

**Comment by saketkc** [comment]
Does this also happen if you run `SCTransform` on a single object?

**Comment by HediaTnani** [comment]
Yes same error.

What should I do? 
Install another version?

**Comment by HediaTnani** [comment]
Any update?

**Comment by saketkc** [comment]
Closing as we haven't heard back, feel free to reopen if this is still an issue.
