### ISSUE TITLE
Findmarkers for continues variable

### ISSUE THREAD

**Issue by suhasaii** [satijalab/seurat#5948]
Can we use findmarkers function to identify DEGs from continues variable. For example, I am looking for genes which are differential over time (T1, T2, T3) without using group like ident.1 vs ident.2.
I found workaround, ident1 vs other time variable. But want to confirm if there is time dependent DEG analysis possible without specifying idents.

**Comment by yuhanH** [comment]
Hi, 
i think this question is related to differential statistics methods. If samples from different time points are paired, you may consider using some paired-parametric or paired-nonparametric tests. 
Otherwise, i think the default method can work in your case.
