### ISSUE TITLE
FindMarkers mistaking identity class for cell name

### ISSUE THREAD

**Issue by vincent-van-hoef** [satijalab/seurat#595]
Hi,

I'm analysing a dataset where individual cells are identified by a number and predetermined clusters (set by SetAllIdent on this object) are numbered as well. Finding markers for a single cluster ID that also identifies a cell results in a "Cell group 1 has fewer than..." error. 
Easy to work around by changing cluster names, of course, but it should not happen due to the first length condition in the if clause at line 104 in differential_expression.R. However due to the placement of the parentheses this condition does not result in a boolean and always passes...

**Comment by satijalab** [comment]
Hi Vincent - not sure I completely understand, but I think to avoid confusion we would strongly suggest naming your cells in a way that would not be confused with possible cluster labels. This is easy to do by changing the column names in the original data matrix.

If you'd like, you can also submit a PR with modified () placement.
