### ISSUE TITLE
as.SingleCellExperiment produced data without dimensions reduction information

### ISSUE THREAD

**Issue by Ashone1992** [satijalab/seurat#5951]
I am trying to perform Slingshot analysis, so I convert Seurat data to singlecellexperiment data by `as.SingleCellExperiment`. However, I did not get the dimensions reduction information after the conversion. How to solve this problem or add dimensions reduction information by other functions?
```
> scRNA_rds <- readRDS("D:/Seq_data/Seur_analysis.rds")
> scRNA_sce <- as.SingleCellExperiment(scRNA_rds)
> reducedDims(scRNA_sce)
List of length 0
names(0)
```

**Comment by CaptainXqu** [comment]
I had the same issue and then I figured out that you might want to assign an “assay” (RNA or others) for the conversion：
 as.SingleCellExperiment( scRNA_rds, assay = "RNA")

**Comment by DarioS** [comment]
I experienced the same problem today. The documentation of `as.SingleCellExperiment` is too short and could be improved.

**Comment by s-trend** [comment]
> I had the same issue and then I figured out that you might want to assign an “assay” (RNA or others) for the conversion：
> as.SingleCellExperiment( scRNA_rds, assay = "RNA")

Did specifying the "RNA" assay resolve the issue for you to use with slingshot?
