### ISSUE TITLE
Integrating multiome, scRNA, snATAC 

### ISSUE THREAD

**Issue by myylee** [satijalab/seurat#5952]
Hi,

Thanks for the great package and the constant maintenance plus updates! 

I have a multiome dataset which I have analyzed using the WNN approach. Now, I have two additional unpaired dataset, one is a scRNA-seq while the other one is snATAC-seq. I'm wondering what is the best way to integrate the two unpaired dataset with the multiome? 

For integrating scRNA-seq with the multiome dataset, I've been following the supervised-PCA approach demonstrated here: https://satijalab.org/seurat/articles/multimodal_reference_mapping.html#example-1-mapping-human-peripheral-blood-cells-1.

However, I wasn't so sure how to integrate the snATAC-seq. Is there an equivalent version of supervised LSI? If not, should I use FindingIntegrationAnchors to map the the ATAC portion of the multiome dataset and snATAC dataset, but in this way, I will not be using the WNN graph during the integration? Or should I convert the snATAC to gene activity score and integration with the RNA profiles in the multiome dataset? 

I'm not sure how different the results will be across these options, but would love to hear your opinion on which might be the best approach here. Looking forward to hearing your suggestions. Thank you very much! 

Best regards,
Michelle

**Comment by yuhanH** [comment]
hi Michelle
In your case, you can try our new method, bridge integration which uses multiome dataset as a bridge to integrate scRNA and snATAC. You don't need to calculate gene activity score for snATAC data.  
Here is the vignette: https://satijalab.org/seurat/articles/bridge_integration_vignette.html
