### ISSUE TITLE
Why the location of violin splits varies in the same dataset?

### ISSUE THREAD

**Issue by Sophia409** [satijalab/seurat#5956]
Hi,

I would like to compare the expression level of features across cell types and samples.  So I plot a vlnplot splitting by two samples. It's weird that the location of red violin (sample 1) and green one (sample 2) is not fixed. As you can see from the boxed sections, two colors somehow change their location. What's the reason?

This is my code:
`VlnPlot(object, split.by = 'species',features = features, flip = T,same.y.lims=F,assay = "RNA",pt.size = 0,raster = T,sort = F,stack = T,split.plot = T)`

![ede9bd817f365746f7807b384058ff2](https://user-images.githubusercontent.com/30619010/168307264-1f98d572-ec4d-41a8-b1d5-d7e6802d3fdd.png)

Any comments will be greatly appreciated.

Sophia

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This is issue only with the old visualization style for split violins.  See response from dev team here:
https://github.com/satijalab/seurat/issues/3007#issuecomment-629310216

Best,
Sam
