### ISSUE TITLE
FindConservedMarker() metap package installation gave a nonzero status

### ISSUE THREAD

**Issue by Skrueger09** [satijalab/seurat#5957]
I am processing my Single Cell RNA seq data and I am at Cluster Analysis:
FindConservedMarkers(seurat_integrated,
                     ident.1 = cluster,
                     grouping.var = "sample",
                     only.pos = TRUE,
		     min.diff.pct = 0.25,
                     min.pct = 0.25,
		     logfc.threshold = 0.25)

But I get an error of 
Error: Please install the metap package to use FindConservedMarkers.
This can be accomplished with the following commands: 
----------------------------------------
install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('metap')
----------------------------------------

Then when I try to install metap I get the following message:
ERROR: dependency ‘qqconf’ is not available for package ‘metap’
* removing ‘/home/shawn/R/x86_64-pc-linux-gnu-library/4.1/metap’
Warning in install.packages :
  installation of package '/extDataS/class/BIMD514_2021/project/ShawnK/DarlandSC/DarlandSC/Sc_RNA_Seq/data/metap_1.8.tar.gz' had non-zero exit status
<img width="830" alt="Screen Shot 2022-05-13 at 12 12 30 PM" src="https://user-images.githubusercontent.com/100965543/168334400-4157f33e-ff33-41b8-980d-73ea0d74ca35.png">
<img width="874" alt="Screen Shot 2022-05-13 at 12 12 59 PM" src="https://user-images.githubusercontent.com/100965543/168334470-6ae29799-2ad3-493e-8009-1f7e50c23928.png">
<img width="872" alt="Screen Shot 2022-05-13 at 12 13 27 PM" src="https://user-images.githubusercontent.com/100965543/168334513-2c92788b-c0e5-4556-9141-14852716c058.png">

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  Did you try running:
```
install.packages("qqconf")
```

Best,
Sam

**Comment by Skrueger09** [comment]
@samuel-marsh 
I have tried manually installing qqconf as well and I have the same error

**Comment by samuel-marsh** [comment]
So the error above is saying qqconf is not available (which is strange because it appears to be good for R3+.  What is the error when attempting direct qqconf install?

**Comment by Skrueger09** [comment]
<img width="876" alt="Screen Shot 2022-05-15 at 7 32 58 PM" src="https://user-images.githubusercontent.com/100965543/168501524-3b265669-4a88-48d1-8f6f-dffa9cea28b5.png">

**Comment by samuel-marsh** [comment]
Hi,

so ya looks like some sort of compilation issue related to qqconf package and not Seurat directly.  I would suggest posting to their repo for help solving the install issue.  https://github.com/eweine/qqconf

Best,
Sam

**Comment by saketkc** [comment]
Hi @Skrueger09, the latest qqconf seems to require fftw3 headers, which needs to be installed on the system: `apt-get install libfftw3-dev`

**Comment by AngCamp** [comment]
No offense but this is a pretty important function and it seems like this should be something Seurat handles automatically.

**Comment by LitalBarak96** [comment]
did you found a solution?
