### ISSUE TITLE
Is sctransform2 workable for single-nuclei RNA-seq?

### ISSUE THREAD

**Issue by DexinYang1998** [satijalab/seurat#5958]
Recently, I worked on snRNA-Seq from multiple samples (cell numbers: 150k; sample numbers: 18). I am wondering whether I could perform sctransform2 to remove the batch effect and normalize the data.

Thank you very much!

**Comment by saketkc** [comment]
Sctransform's primary objective is to normalize, though in principle you could mitigate batch effects as well. See [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for an example (which performs normalization, followed by integration to remove batch effects).
