### ISSUE TITLE
mapping query to reference

### ISSUE THREAD

**Issue by rhodesch** [satijalab/seurat#5959]
I recently tried the Azimuth app and was very impressed. Looking at the associated analysis R file, l have 2 related questions about the SCTransform step for the query object performed by the Azimuth app:

The azimuth app uses the following parameters for normalizing query object:
```
# Preprocess with SCTransform
query <- SCTransform(
  object = query,
  assay = "RNA",
  new.assay.name = "refAssay",
  residual.features = rownames(x = reference$map),
  reference.SCT.model = reference$map[["refAssay"]]@SCTModel.list$refmodel,
  method = 'glmGamPoi',
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
  do.scale = FALSE,
  do.center = TRUE
)
```

1) Why does Azimuth set `do.correct.umi = FALSE` in SCTransform() while the associated vignette in Seurat() [Mapping and annotating query datasets](https://satijalab.org/seurat/articles/integration_mapping.html) uses default parameters for SCTransform of the query, particularly `do.correct.umi = TRUE`?

2) If I aim to combine multiple samples/datasets with clear batch effects using Azimuth, where eash sample is mapped to a reference, for downstream analysis should I use either the original `RNA` slot, or create a separate `SCT` slot (NOT the `refAssay` slot lacking corrected UMI counts)? I'm interested in not just differential testing but also analyses like pseudotime/trajectory inference.

Thanks in advance for any input.

**Comment by yuhanH** [comment]
Hi,
It just saves computing time to set `do.correct.umi = FALSE`. In the integration, we integrated sct residuals and did not use corrected data slot.
For q2, I would suggest you use RNA slot for the downstream. Since you have many batches, the corrected data slot may be corrected by different SCT models.

**Comment by rhodesch** [comment]
Thanks @yuhanH. Leaving issue closed but have a quick follow-up for question 2. Is it reasonable to set `do.correct.umi = TRUE` in the code above? Then multiple query samples/batches would have RNA counts adjusted to the reference SCT model, in addition to projecting query PCA/UMAP embeddings to reference.

So something like below (additional SCT parameters omitted):
```
query <- SCTransform(
  object = query,
  assay = "RNA",
  new.assay.name = "refAssay",
  residual.features = rownames(x = reference$map),
  reference.SCT.model = reference$map[["refAssay"]]@SCTModel.list$refmodel,
  do.correct.umi = TRUE
)
```

**Comment by yuhanH** [comment]
Hi, @rhodesch 
The above code may not work well. It is designed for for reference mapping to use reference-SCT model. Reference-SCT model may not model query sequencing depth effects, so the corrected data from reference-SCT model is not suggested.
