### ISSUE TITLE
Correlation matrix with different dataset markers 

### ISSUE THREAD

**Issue by GreyRockIQ** [satijalab/seurat#5960]
Hello
I want to plot a Correlation matrix heatmap with markers in my dataset of Seurat integrated clusters vs published/different dataset markers in CSV files (containing 100+ markers).

Any suggestions on how to do this?

Thanks
GreyRock

**Comment by yuhanH** [comment]
You can use `AverageExpression` to get pseudobulk expression profile for your clusters. 
Then, you can use [ComplexHeatmap](https://jokergoo.github.io/ComplexHeatmap-reference/book/) to plot the correlation heatmap.
