### ISSUE TITLE
issues installing seurat in R v4.2 

### ISSUE THREAD

**Issue by carlosaya2** [satijalab/seurat#5962]
my admin renewed my R to 4.2 and I lost all the installed packages. when reinstalling seurat, it failed to install as it needed rgeos. I tried to install rgeos but it required geos-config which I cannot install as there is no version for R v4.2. 

![image](https://user-images.githubusercontent.com/61134130/168517167-c582c315-aee8-4e12-ae8d-80a538f67c11.png)

The problem is I cannot use sudo install as I do not have admin rights. is there a way that i can solve this issue or I can download the right package?

I tried to install libgeos through CRAN and did not work. 

will highly appreciate your help with this.

Cheers, 

carlos

**Comment by longmanz** [comment]
Hi, 

It is likely a problem with package "rgeos". Is it possible to ask your admin to help sudo install?  
Alternatively, you may use Anaconda to install your own R and packages. It also helps avoid R being renewed on your cluster.

Longda

**Comment by mojaveazure** [comment]
SeuratObject depends on rgeos for spatial support, has a requirement of libgeos. You can have your admin install libgeos, or you can get the source from https://libgeos.org/

**Comment by skchronicles** [comment]
Hey @mojaveazure @longmanz,

I am also able to replicate this error/issue on a fresh install of `ubuntu/20.04` using `R/4.2`.

Here is a screenshot of the error when trying to install Seurat:
![image](https://user-images.githubusercontent.com/18038345/175432130-4778c92f-c305-468c-80b9-8c22134463a8.png)

I was able to resolve the issue by installing `libgeos-dev` with apt, as you suggested:
```bash
DEBIAN_FRONTEND=noninteractive apt-get install -y libcairo2-dev
```

Do you think it might be worth suggesting this C/C++ library should be installed in your documentation? 

I did not see it mentioned anywhere here:
https://satijalab.org/seurat/articles/install.html

Even just a small blurb could be helpful.

Best,
@skchronicles
