### ISSUE TITLE
Which assay and slot to use for visualising gene expression in different scenarios

### ISSUE THREAD

**Issue by ChristinaSteyn** [satijalab/seurat#5966]
Hi there, thank you for developing so many amazing tools! I realise this question has been asked before in different ways but I have been having some discussions with my lab and we are still a bit confused about which assay and slot to use for visualizing the expression of genes in different scenarios (e.g comparing between clusters in one dataset, comparing between clusters using multiple merged datasets, comparing between samples, or comparing between conditions comprising multiple samples such as treated vs control). The one concern is that we are working with brain tissue and our understanding is that some cell types such as the Excitatory Neurons may have a greater number of UMIs than other cell types such as Astrocytes (a real biological difference) and so by performing the standard log normalization method one will in a sense ‘over-normalize’ the counts of cells that have a higher UMI count for biological reasons. This is not ideal for visualization as it may, for example, appear as though a gene is equally expressed in two cell types when it is actually more highly expressed in the one cell type. As far as I can understand, the SCT method of normalization should be able to account for this and adjust for technical effects such as differences in sequencing depth between cells while retaining true biological variation. Thus, if one would like to compare the expression of a gene in **multiple cell types** for a **single dataset** then one could consider using the SCT assay and data slot (log of the corrected counts)? If, on the other hand, one would like to compare the expression of a gene between **multiple samples** for a **single cell type** then according to issue #4082, using the SCT assay and data slot could be misleading if the samples were sequenced to different depths and so instead the RNA assay and data slot is recommended as this imposes a uniform standard across datasets. However, I am uncertain which assay and slot to use for the following: 
1. If one wanted to compare the expression of a gene between **multiple clusters** and **multiple samples** simultaneously, for example, comparing the expression of a gene in Astrocytes, Microglia, and Excitatory neurons between sample1, sample2, sample3, and sample4?
2. If one wanted to compare the expression of a gene between **multiple clusters** and **multiple samples** but instead of splitting by sample, you take an **average across samples**? 
and
3. If one wanted to compare between **multiple conditions** and **multiple clusters**, for example, comparing treated to control in Astrocytes, Microglia, and Excitatory Neurons by plotting a heatmap (e.g., [as seen in issue #2201](https://github.com/satijalab/seurat/issues/2201) )?

I am also a bit confused because the documentation for violin plots suggests that the unnormalized counts should be used even though in this issue #1717 they suggest using the RNA assay and data slot for any visualisation. I was wondering if the recommendation to use unnormalized counts is something about violin plots specifically (e.g., that they show a distribution as opposed to an average)? 

Thank you very much for your consideration - any assistance would be greatly appreciated.

**Comment by yuhanH** [comment]
HI 
In https://github.com/satijalab/seurat/issues/1717, it suggested use `RNA assay` normalized data for downstream analysis not `integrated assay` data. 
For the downstream analysis, normalized data in the RNA assay is suggested in most cases. 
For other confounding factors, you can control them in your differential statistics model.

**Comment by ChristinaSteyn** [comment]
Hi Yuhan, 

Thank you for your response. I am still confused whether it is always correct to use the normalized data RNA assay when visualising the expression of genes between different clusters because as I mentioned in my previous question this may lead to 'over-normalising' the counts if some cell types biologically have a higher UMI count. Could you please clarify whether this is the case? 

It seems that the SCT assay has many advantages over standard log normalization and yet according to issue #4082 , using the SCT assay could be misleading if one is using multiple samples hence my questions posed above which specifically refer to which assay and slot one should use for visualising gene expression so that it most accurately represents the differences between clusters/samples/conditions. Is there any chance you could read over those questions again and confirm that I should use the RNA assay, data slot to visualise the expresison of genes in all three situations described above?

Could you also please provide clarification regarding why the documentation of violin plots suggests that we use the non-normalised counts even though you have advised above that we should use the normalised counts?

**Comment by denvercal1234GitHub** [comment]
@ChristinaSteyn -- Any update on the final decisions?
