### ISSUE TITLE
Export ATAC Profiles (Coverage) in .bigwig format ?

### ISSUE THREAD

**Issue by matteozoia4** [satijalab/seurat#5967]
Dear Satijalab,

is it possible to export ATAC profiles in .bigwig format (i.e out of single cell clusters)?

Best regards,

MZ

**Comment by timoast** [comment]
You can split the BAM file according to cell barcode, then create a bigwig file for each split bam file. See the `filterbarcodes` function here: https://timoast.github.io/sinto/

**Comment by matteozoia4** [comment]
Many thanks for the hint it is extremely useful!


Best regards and thank you!


________________________________
Da: Tim Stuart ***@***.***>
Inviato: venerdì, 20. maggio 2022 20:43:53
A: satijalab/seurat
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [satijalab/seurat] Export ATAC Profiles (Coverage) in .bigwig format ? (Issue #5967)


You can split the BAM file according to cell barcode, then create a bigwig file for each split bam file. See the filterbarcodes function here: https://timoast.github.io/sinto/
