### ISSUE TITLE
Adding threshold lines to VlnPlots

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#5971]
I'm new to both R and Seurat so please bear with me.  I have my VlnPlots and was wondering if there was a way to add horizontal lines showing where I'm choosing my threshold limits?

Also, can I add a title about the VlnPlot?  And rename the axes?  I guess I'm wondering how to do regular ggplot stuff to VlnPlot.

Thanks,
Stacy

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.

To add horizontal line and title you can use typical ggplot2 the wing:
```
VlnPlot(...) +
    geom_hline(yintercept = c(low_cutoff, high_cutoff), linetype = "dashed", color = "red") 
```

Also as a shortcut I have package which has shortcuts for plotting QC functions like nFeature_RNA and an adaptable function that can plot any feature.

https://samuel-marsh.github.io/scCustomize/articles/QC_Plots.html#vlnplot-based-qc-plots

Best,
Sam

**Comment by samuel-marsh** [comment]
Didn’t explicitly mention it but the scCustomize functions have built in parameters to plot thresholds and change titles, labels, etc.

Example here:
https://samuel-marsh.github.io/scCustomize/reference/QC_Plots_Genes.html
