### ISSUE TITLE
Removing clusters with PC positive for a certain feature

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#5972]
I'm very new to R and Seurat.  I'm processing data for my lab and have been asked to remove cells that are positive for a certain feature from any cluster.  I really have no idea how to do this...any help would be greatly appreciated.

Thanks,
Stacy

**Comment by samuel-marsh** [comment]
Hi Stacy,

So it’s definitely possible although I would be very careful about blanket removal of cells with certain features as you could easily be removing real biology or real biology that is masked by ambient RNA contamination or variety of other factors.

That said if you want to identify cells positive for certain factor and then subset them out you could run:
```
library(Seurat)
library(dplyr)
library(magrittr)

data <- FetchData(object = OBJ, vars = "GENE")
cell_names <- data %>% 
  filter(GENE > 0) %>% 
  rownames()

OBJ_SUB <- subset(x = OBJ, cells = cell_names, invert = TRUE)
```

Best,
Sam

**Comment by stacygenovese** [comment]
Thank you so much!  And I'll pass along the concerns to the senior
researcher.  I really appreciate the response and your response to my
previous question.  The scCustomized did what I needed!

Best,
Stacy

**Comment by samuel-marsh** [comment]
Glad to help!

Also forgot there is even easier way for getting the cells:

```
cell_names <- WhichCells(OBJ, expression = GENE > 0)

OBJ_SUB <- subset(x = OBJ, cells = cell_names, invert = TRUE)
```

Same result either way just less code.

Best,
Sam
