### ISSUE TITLE
Typo in PrepSCTIntegration

### ISSUE THREAD

**Issue by AlexWeinreb** [satijalab/seurat#5977]
In the example of `?PrepSCTIntegration` ([web](https://satijalab.org/seurat/reference/prepsctintegration)), the last command is:
```
pancreas.integrated <- IntegrateData(anchors)
```

It should be:
```
pancreas.integrated <- IntegrateData(anchors, normalization.method = "SCT")
```
otherwise the `scale.data` slot of the integrated object is incorrect and we get a hard-to-understand `Error in data.use[features, ] : no 'dimnames' attribute for array`.

Thank you for your work!

**Comment by rsatija** [comment]
Thanks. I believe this is correct in the vignette but appears to be missing in the documentation example as you say. @saketkc can fix and update in the next version

**Comment by saketkc** [comment]
Thanks! This has been fixed upstream.
