### ISSUE TITLE
Errors in CellCycleScoring

### ISSUE THREAD

**Issue by lyc1234** [satijalab/seurat#598]
Hi, 
I'm interested in calculating the CellCycleScoring for my datasets. However, I have met with two small problems when trying to get the code to work as described below and would greatly appreciate any assistance and/or feedback:
1)I tried to get the CellCycleScoring for one of my datasets, but both S. Score and G2M.Score showed as “NA”. I have checked to make sure that the genes in my gene lists are present in the data. Does anyone know what could’ve gone wrong and how should I fix this problem?

2)Is it possible to calculate the CellCycleScoring with only have one gene list instead of two?
Thank you so much in advance!

**Comment by satijalab** [comment]
You can use the AddModuleScore function to add individual scores. If all genes are present in your object@data matrix, and none of the values in that matrix are NA, you should not have this problem. If it persists, please do feel free to upload a reproducible example.
