### ISSUE TITLE
How can I make seurat object from public data source?

### ISSUE THREAD

**Issue by polespin** [satijalab/seurat#5980]
Hi.

I have a question about make seurat object file. 
I reconstruct single cell sequencing analysis using public data (E-MTAB-8832, https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-8832/?query=cancer&sortby=raw&sortorder=descending)

I got error just below.
---------------------------------------------------------------------------------------------
CSF1R.data<-read.table("E:/E-MTAB-8832.processed.1/CSF1R_metadata.txt")
CSF1R<- CreateSeuratObject(counts = CSF1R.data, min.cells = 3, min.features = 200)
**Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Warning message:
In storage.mode(from) <- "double" : NAs introduced by coercion**
---------------------------------------------------------------------------------------------

How can I fix that error and make seurat object from that file? 
I attached txt file from E-MTAB-8832 dataset. 

Any answer is really appreciated.
Thank you.

[CSF1R_metadata.txt](https://github.com/satijalab/seurat/files/8738344/CSF1R_metadata.txt)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So this file that you are referencing here isn't a gene expression x cell matrix.  When you read it in and look at it you find it's just a meta data table for the cells containg their meta data and UMAP coordinates from the performed analysis.  To create Seurat object you need data.frame, matrix etc that is in feature x cell format (feature = row, cell = column).

Best,
Sam

**Comment by saketkc** [comment]
Hi @polespin, as @samuel-marsh said this dataset does not seem to have a counts matrix available which is the input required for Seurat. The raw data _seems_ to be available here: https://www.ebi.ac.uk/ena/browser/view/PRJEB34105?show=reads
