### ISSUE TITLE
Merging seurat clusters 

### ISSUE THREAD

**Issue by Rahul1711arora** [satijalab/seurat#5981]
Hi, 

I have a quick query about merging different clusters for meta-analysis. 
So, I have 8 different datasets that I have now normalised and clustered. I have also extracted the relevant cluster separately from each dataset. I now need to merge all of them together and re-cluster so that I see 8 different clusters on a new map. I am not sure on how to do that. Any help is much appreciated. 

Thanks in advance!
Rahul

**Comment by longmanz** [comment]
Hi, 
If you simply want to subset and merge datasets you may use subset() and merge() functions in Seurat (see examples at https://satijalab.org/seurat/articles/essential_commands.html ).

You may also find the scRNA integration tutorial useful if you are merging datasets from different sources (https://satijalab.org/seurat/articles/integration_introduction.html).

Longda

**Comment by rsatija** [comment]
I'll also suggest that before merging/integrating, you store the dataset ID in the metadata.

For example:

```
object$dataset = "Dataset1"
```

That way, after you merge the objects, you can pass `dataset` as an argument to the `group.by` parameter in functions like `DimPlot`

**Comment by Rahul1711arora** [comment]
Thank you so much. I will try that!
