### ISSUE TITLE
VlnPlot log=T

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [satijalab/seurat#5984]
Hey everyone,

I am analysing some mouse single cell RNA seq data. I need to distinguish for the CD90.2 positive and negative cells for downstream analysis(I have CD90.2 in my CITE Seq panel). However the CITESeq expression doesn't look so beautiful so I cant properly set a threshold for the expression level. However when I use log=T the plot looks more bimodal but I cant figure out what logarithmic scale is used in order to set the threshold in my non-logarithmic dataset. Please see attached the plots: 1) normal scale and 2) log scale. Any help/suggestion would be really appreciated!
1)
![image](https://user-images.githubusercontent.com/60395255/169594329-5948aad4-1975-41a6-8aab-88405322518b.png)
2)
![image](https://user-images.githubusercontent.com/60395255/169594770-fc0c0043-ed1a-4fbd-ba2e-42d0eb2a078b.png)

Thanks a lot!

**Comment by timoast** [comment]
log10 is used, I've updated the documentation on the develop branch

**Comment by christoforos-dimitropoulos** [comment]
> log10 is used, I've updated the documentation on the develop branch

hey thanks for the prompt response. however in my case, the cells with expression level around 4 seem to have expression level around 5 in the log scale plot. does this fit with the log10?

**Comment by timoast** [comment]
It's done using `ggplot2::scale_y_log10()`, so the values on the axis still correspond to the original data but as spaced on a log10 scale
