### ISSUE TITLE
FindTransferAnchors

### ISSUE THREAD

**Issue by chenx9** [satijalab/seurat#5987]
When I run the code below, I get an error
anchors <- FindTransferAnchors(
  reference =ctr_preob,
  query =fra_preob ,
  reference.reduction = "pca"
)
Error in cn.data2[nn.cells2, ] : subscript out of bounds

**Comment by CHAOYiming** [comment]
Hi I met the same problem. 
In my case it works when i added `recompute.residuals = FALSE`. 
FYI: 
> anchors <- FindTransferAnchors(reference = sample_sc, query = sample_ST, dims = 1:20, reference.reduction = "pca", normalization.method = "SCT", recompute.residuals = FALSE)

**Comment by yuhanH** [comment]
hi @chenx9  and @CHAOYiming 
Could you provide more scripts you used?

**Comment by CHAOYiming** [comment]
@yuhanH sorry just realise you are the collaborator. Anyway thanks!

**Comment by yuhanH** [comment]
hi @CHAOYiming 
Thanks for posting the script. In your case, you are mapping a spatial-RNA into scRNA reference. 
It seems that the SCT model in the reference does not fit for the spatial gene expression query well. 
`recompute.residuals = FALSE` is a good way in your case. 

@chenx9 do you have similar situation?

**Comment by yuhanH** [comment]
hi @CHAOYiming 
I haven't heard back from you for a long time. I will close this issue first. If you still meet this issue, we can reopen it.
