### ISSUE TITLE
Add Title and Legend setting on SpatialDimPlot() function

### ISSUE THREAD

**Issue by emkahuda** [satijalab/seurat#5988]
I am trying to plot the spatial features of cell distribution using the SpatialDimPlot() function. How to add the title to this plot as well as modify the legend, including colours?

**Comment by mojaveazure** [comment]
`SpatialDimPlot`, and all other visualization functions return (patchworked) ggplot2 objects (`DimHeatmap` by default uses base graphics, but can be configured to use ggplot2 by passing `fast = FALSE`) and can be manipulated like all other ggplot2 objects
