### ISSUE TITLE
Questions about CreateGeneActivityMatrix function in Seurat V3

### ISSUE THREAD

**Issue by Kevis9** [satijalab/seurat#5990]
Seurat V3 has a function `CreateGeneActivityMatrix`, which can convert ATAC peaks to gene-level's matrix.
```
CreateGeneActivityMatrix(
  peak.matrix,
  annotation.file,
  seq.levels = c(1:22, "X", "Y"),
  include.body = TRUE,
  upstream = 2000,
  downstream = 0,
  verbose = TRUE
)
```
Here are my questions:

1. What is the format of the first parameter `peak.matrix` ? For example, what are the row names of this matrix? (Are there  naming rules for chromosome regions ?). 
2. About the parameter seq.levels. Besides 1...22,X,Y , Can I add other chromosomes ? like `hs37d5` or `GL000193.1` etc.

**Comment by timoast** [comment]
> What is the format of the first parameter peak.matrix ? For example, what are the row names of this matrix? (Are there naming rules for chromosome regions ?).

Row names should be formatted as `chr:start-stop`

> About the parameter seq.levels. Besides 1...22,X,Y , Can I add other chromosomes ? like hs37d5 or GL000193.1 etc.

Yes
