### ISSUE TITLE
DotPlot non-scaled gradient

### ISSUE THREAD

**Issue by Landbruce** [satijalab/seurat#5991]
Hello,
First of all thank you so much for Seurat! It is amazing!

I have been using SeuratV4 and comparing two conditions (untreated and treated). When plotting using DotPlot function, scale=TRUE is resulting in all positive values to have a similar value and the same is happening with the negative ones (which looks right based in how the "scale" is performed).

Including `scale = FALSE` and plotting just the avg.exp values the values are much better but I am having a huge variation as expected when comparing distinct genes. In this case, col.max and col.min is not being working to limit the maximum and lowest values of the expression levels gradient. Would be great, for example if I can have +1 and -1 for example instead of the current +2.5 and -2.5.  

**How can I determine the max and min in my expression levels gradient legend when the expression is not scaled?**

Thanks a lot!

**Comment by longmanz** [comment]
Hi, 
It is not super clear to me what you are trying to do. But in DotPlot you can actually specify the lower and upper limits of your scaling by using `scale.min =`  and `scale.max = `.
