### ISSUE TITLE
Multimodal reference mapping: Data format

### ISSUE THREAD

**Issue by DDDDDDKKKKKK** [satijalab/seurat#5992]
We tried to use the code example provided at the URL: https://satijalab.org/seurat/articles/multimodal_reference_mapping.html

In order to perform a reference mapping based on multiomic single cell data defined by a scRNA-seq and a scATAC-seq feature vector and one cell type label for each of the 8.000 data points. The goal is to use 80% of the data as the reference data set to predict the labels of the other 20%. However, we had difficulties bringing our data into the right format. Our data is encoded in numpy arrays, two for the two scRNA-seq and scATAC-seq feature matrices and one for the intiger array representing the 14 different labels. How do we use the Multimodal reference mapping based on this data?

**Comment by torkencz** [comment]
Hi, I think you need to get your files into Seurat files. I would use this as help as there are differences in R and python matrix formats: https://rstudio.github.io/reticulate/articles/arrays.html.  Alternative that I can think of is using this: https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html . If your problem does not resolve I can reopen this.
