### ISSUE TITLE
Subclustering

### ISSUE THREAD

**Issue by eneseroglu1** [satijalab/seurat#5994]
How can i subclustering for one cell type? I used to this code but i could not take any output in R. FindSubCluster(
  object,
  cluster,
  graph.name,
  subcluster.name = "sub.cluster",
  resolution = 0.5,
  algorithm = 1
)
I think, the problem is about graph name. I could not take any  name the umap graph. İs there any solution about this situation?

**Comment by timoast** [comment]
Please include the full code you're running and the error message that you see

**Comment by torkencz** [comment]
Hi, you should provide a graph name in your object. E.g.: "RNA_snn" from obj.merge@graphs$RNA_snn.
