### ISSUE TITLE
[ UMAP] Should i perform a batch correction or integration ? 

### ISSUE THREAD

**Issue by hamidsta** [satijalab/seurat#5998]
Hello, i'm currently analysing multiomics data accros two condition, here is my umap 

![image](https://user-images.githubusercontent.com/102754023/170142171-7f4373cf-acb9-4e0e-ba11-f097927fc7f0.png)

As you can see , my clusters are really well separated accros my conditions male / female . I wonder if i should integrate accros the sex or not ?  that way i will have the number of cluster corresponding to the number of cell types identitfied and not "male_/female_" Personnaly i think it's not necessary since the clusters are so well separated. And The Differential expression might not pose a problem if i want to compare male against female since the male and female annotated clusters basically contain 99% of the cells of their "identity". 

Am i doing that right ? 

thank you very much

**Comment by torkencz** [comment]
Hi, I would integrate in case you want to look at cell type differences across cell types (without taking sex into account). You can compare across sex within the same cell type after you identify matching cell types. If you trust your current cell type annotations then you might not need to integrate.
