### ISSUE TITLE
Integration with/without SCT

### ISSUE THREAD

**Issue by cgraham13** [satijalab/seurat#5999]
Hello,

I am integrating 3 samples. Each of the samples have been normalized with SCTransform and they all look good. I am having some issues when I am integrating the samples. I have tried 2 different approaches:

1) Integration with SCT 

features <- SelectIntegrationFeatures(object.list = ntd.list, nfeatures = 3000)
NTD.integrated <- PrepSCTIntegration(object.list = ntd.list, anchor.features = features)
anchors <- FindIntegrationAnchors(
  object.list = NTD.integrated,
  object.list = ntd.list,
  normalization.method = "SCT", 
  anchor.features = features
)
NTD.integrated <- IntegrateData(anchorset = anchors,
                                normalization.method = "SCT"
                                )  

NTD.integrated <- RunPCA(NTD.integrated)
NTD.integrated <- RunUMAP(NTD.integrated, reduction = "pca", dims = 1:30)
NTD.integrated <- FindNeighbors(NTD.integrated, reduction = "pca", dims = 1:30)
NTD.integrated <- FindClusters(NTD.integrated, resolution = c(0.5))

2) Integration without SCT

features <- SelectIntegrationFeatures(object.list = ntd.list, nfeatures = 2000)
anchors <- FindIntegrationAnchors(
  object.list = NTD.integrated,
  object.list = ntd.list,
  anchor.features = features
)
NTD.integrated <- IntegrateData(anchorset = anchors
                                )  

NTD.integrated <- ScaleData(NTD.integrated, verbose = FALSE)
NTD.integrated <- RunPCA(NTD.integrated)
NTD.integrated <- RunUMAP(NTD.integrated, reduction = "pca", dims = 1:30)
NTD.integrated <- FindNeighbors(NTD.integrated, reduction = "pca", dims = 1:30)
NTD.integrated <- FindClusters(NTD.integrated, resolution = c(0.5))

When I look at the clustering and UMAP with both approaches they are very different. The SCT UMAP has a lot of small clusters and the integration without SCT looks more realistic. My main question is, is it ok to integrate without SCT when the samples have been normalized individually using SCTransform?

I have attached the UMAPs below for reference.

Thanks in advance!

Carly

[MoA-UMAP-NTD-Normalized.pdf](https://github.com/satijalab/seurat/files/8766988/MoA-UMAP-NTD-Normalized.pdf)
[MoA-UMAP-NTD-SCTInt.pdf](https://github.com/satijalab/seurat/files/8766989/MoA-UMAP-NTD-SCTInt.pdf)

**Comment by saketkc** [comment]
While it is fine to integrate without SCT, you can also consider using the [v2 flavor](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for SCT.
