### ISSUE TITLE
installing seurat

### ISSUE THREAD

**Issue by smith0493** [satijalab/seurat#60]
I keep trying to install seurat and getting this type of error message. Any suggestions?

> library(devtools)
> install_github("satijalab/seurat")
Downloading GitHub repo satijalab/seurat@master
from URL https://api.github.com/repos/satijalab/seurat/zipball/master
Installing Seurat
"C:/Users/smith493/Documents/R/R-3.2.5/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/smith493/AppData/Local/Temp/Rtmp8yFqXU/devtools11585fd04b12/satijalab-seurat-a08d507"  \
  --library="C:/Users/smith493/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'Seurat' ...
** libs

*** arch - i386
g++ -m32 -std=c++0x -I"C:/Users/smith493/DOCUME~1/R/R-32~1.5/include" -DNDEBUG    -I"C:/Users/smith493/Documents/R/win-library/3.2/Rcpp/include" -I"C:/Users/smith493/Documents/R/win-library/3.2/RcppEigen/include" -I"C:/Users/smith493/Documents/R/win-library/3.2/RcppProgress/include" -I"d:/RCompile/r-compiling/local/local323/include"  -g -std=c++11 -Wall -pedantic   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
cc1plus.exe: error: unrecognized command line option '-std=c++11'
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/Users/smith493/DOCUME~1/R/R-32~1.5/etc/i386/Makeconf" -f "C:/Users/smith493/DOCUME~1/R/R-32~1.5/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="Seurat.dll" OBJECTS="RcppExports.o data_manipulation.o"' had status 2
ERROR: compilation failed for package 'Seurat'
* removing 'C:/Users/smith493/Documents/R/win-library/3.2/Seurat'
Error: Command failed (1)

**Comment by andrewwbutler** [comment]
You need to have a compiler that supports c++11 and the latest Rtools should come with one that does. Try updating to the latest version of R and Rtools.

**Comment by smith0493** [comment]
Hi Andrew,

I updated to R 3.3.3 and reloaded the Rtools then tried installing again.
After having the install fail maybe ten times (each time because another
package was missing) and loading the missing package each time, I might
have managed to get Seurat to load some tutorial data.

Thanks.

Karen Smith

**Comment by andrewwbutler** [comment]
Sorry about the dependency issues. Not sure why on some Windows machines it can't seem to automatically find and download all the right ones. The easiest fix for now is to just install them all "manually" before installing Seurat. Below is the command that should catch all the required ones in case others are having the same issue.

`install.packages(c("ROCR", "stringr", "mixtools", "lars", "fastICA", "tsne", "Rtsne", "fpc", "ape", "VGAM", "pbapply", "igraph", "FNN", "caret", "plyr", "dplyr", "RColorBrewer", "MASS", "Matrix", "irlba", "reshape2", "gridExtra", "gplots", "gdata", "ggplot2", "Rcpp", "RcppEigen", "RcppProgress", "tclust", "ranger"), dependencies = T)`

**Comment by smith0493** [comment]
Hi Andrew,

I am trying to do the tutorial for the pmbc's ( which is indicated as an
older tutorial) and it appears some of the commands have changed in R
3.3.3.  Do you have a link to a tutorial and tutorial data that is for R
3.3.3?

Thank you .

Karen Smith

**Comment by andrewwbutler** [comment]
Do you know what version of Seurat you updated from?

**Comment by smith0493** [comment]
Hi Andrew,

I am a complete newcomer to most of this R stuff. I followed the directions
on your lab website and used this line

"install_github("satijalab/seurat")" to get whatever Seurat version this
command would install if you used it this week.  I also ran the line of
code you emailed me yesterday

install.packages(c("ROCR", "stringr", "mixtools", "lars", "fastICA",
"tsne", "Rtsne", "fpc", "ape", "VGAM", "pbapply", "igraph", "FNN", "caret",
"plyr", "dplyr", "RColorBrewer", "MASS", "Matrix", "irlba", "reshape2",
"gridExtra", "gplots", "gdata", "ggplot2", "Rcpp", "RcppEigen",
"RcppProgress", "tclust", "ranger"), dependencies = T)
Thank you.

Karen

**Comment by andrewwbutler** [comment]
The [PBMC tutorial](http://satijalab.org/seurat/pbmc-tutorial.html) on the website corresponds to the latest version of Seurat.

**Comment by smith0493** [comment]
Hi Andrew,

I have been doing the pbmc tutorial and it looked like things were working
ok until I got to the "FindClusters" command.  Here is what was being done
in R studio

> VizPCA(pbmc, 1:2)
> PCAPlot(pbmc, 1, 2)
> PCHeatmap(pbmc, pc.use = 1, cells.use = 100, do.balanced = TRUE)
Warning messages:
1: In heatmap.2(data.use, Rowv = NA, Colv = NA, trace = "none", col =
col.use,  :
  Discrepancy: Rowv is FALSE, while dendrogram is `both'. Omitting row
dendogram.
2: In heatmap.2(data.use, Rowv = NA, Colv = NA, trace = "none", col =
col.use,  :
  Discrepancy: Colv is FALSE, while dendrogram is `column'. Omitting column
dendogram.
> PCHeatmap(pbmc, pc.use = 1:12, cells.use = 500, do.balanced = TRUE,
label.columns = FALSE, use.full = FALSE)
There were 24 warnings (use warnings() to see them)
> pbmc <- JackStraw(pbmc, num.replicate = 100, do.print = FALSE)

> pbmc <- JackStraw(pbmc, num.replicate = 100, do.print = FALSE)
> JackStrawPlot(pbmc, PCs = 1:12)
Warning messages:
1: In prop.test(c(length(which(pAll[, i] <= score.thresh)),
floor(nrow(pAll) *  :
  Chi-squared approximation may be incorrect
2: Removed 17462 rows containing missing values (geom_point).
> PCElbowPlot(pbmc)
> pbmc <- FindClusters(pbmc, pc.use = 1:10, resolution = 0.6, print.output
= 0, save.SNN = T)
Error: Registry key 'Software\JavaSoft\Java Runtime
Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: running command 'java -jar
"C:/Users/smith493/Documents/R/win-library/3.3/Seurat/java/ModularityOptimizer.jar"
"C:/Users/smith493/Documents/R/win-library/3.3/edge_17992.txt"
"C:/Users/smith493/Documents/R/win-library/3.3/output_17992.txt" 1 0.6 1
100 10 0 0' had status 2
2: In file(file, "rt") :
  cannot open file
'C:/Users/smith493/Documents/R/win-library/3.3/output_17992.txt': No such
file or directory


Is this basically telling me that I am using Java 1.8 and I should be using
Java 1.7?

Thank you .

Karen Smith

**Comment by smith0493** [comment]
Hi Andrew,

I currently have JAva version 8 update 121 (build 1.8.0_121-b13).

Thank you.

Karen Smith

**Comment by andrewwbutler** [comment]
Hi Karen,

This seems to be a relatively common problem with java when you upgrade from 7 to 8. Try removing Java entirely and reinstalling Java 8. 

Here's a couple of posts where people were having similar trouble and the solutions that worked for them: 
http://stackoverflow.com/questions/29697543/registry-key-error-java-version-has-value-1-8-but-1-7-is-required
http://stackoverflow.com/questions/29697543/registry-key-error-java-version-has-value-1-8-but-1-7-is-required
http://www.devfish.net/post/2015/07/16/error-java-version-1-7-is-required.aspx
