### ISSUE TITLE
normalization or cluster-wise normalization for DE analysis?

### ISSUE THREAD

**Issue by kkonoo** [satijalab/seurat#6000]
Hi there,
I normalized my single-cell data and successfully integrated and find some clusters. 
Now, I'm trying to do DE analysis in each cluster.
To identify DEGs, I used RNA assays in Seurat object and collapsed counts into individual levels to use edgeR.
In this case, should I normalize such pseudo-bulk counts in each cluster or across clusters?

Thanks,
E.H.

**Comment by torkencz** [comment]
Hi, I think edgeR takes raw counts as opposed to normalized ones.
