### ISSUE TITLE
Follow up to replicate quuestions

### ISSUE THREAD

**Issue by AuritaP** [satijalab/seurat#6003]
In your answer below, when you say normalize each sample separately, does that mean you first load the data individually for each sample, creating  seurat object for each one, normalizing that and then you merge the two controls? Or Can you load all four samples at once in one seurat object?

Yes, there are several possible approaches here. As mentioned in #4753, you could use your 2 Control's as a reference, in which case I would use the following steps:
  1. Normalize all 4 samples separately
  2. Integrate the 2 control samples
  3. Integrate each case sample with the integrated control object, as shown [here](https://satijalab.org/seurat/articles/integration_mapping.html) 
  4. dimension reduction
  5. downstream analysis

Hope this is helpful!

_Originally posted by @mhkowalski in https://github.com/satijalab/seurat/issues/5553#issuecomment-1024376692_

**Comment by Gesmira** [comment]
Hi, you would want to make 4 individual Seurat objects. You can normalize your samples at the same time by putting them into a list:

```
samples.list <- c(control_1, control_2, case_1, case_2)
for (i in 1:length(samples.list) {
    samples.list[[i]] <- NormalizeData(samples.list, verbose = FALSE)
    samples.list[i]] <- FindVariableFeatures(samples.list, selection.method = "vst", nfeatures = 2000,
        verbose = FALSE)
        
}
```
Then make a list of only the normalized control samples and integrate: 

```
control.list <- c(control_1, control_2
control.anchors <- FindIntegrationAnchors(object.list = control.list, dims = 1:30)
control.integrated <- IntegrateData(anchorset = control.anchors, dims = 1:30)

```
At this point, you can then integrate your other objects with this integrated control object and follow the rest of the workflow.

**Comment by AuritaP** [comment]
Thank you
