### ISSUE TITLE
H5 file not opening with Read10X_h5 function

### ISSUE THREAD

**Issue by MrClearLovez** [satijalab/seurat#6006]
Hi,

I am unable to open any H5 file with the Read10X function. The very same code with the same H5 files had worked for my colleague but is not working for me. Can you help me fix this? Thank you so much!

when I run code ,on using the Read10X_h5 function to open the file, I am getting the errors listed below:

suppressMessages({
library(dplyr)
library(Seurat)
library(ggplot2)
library(Cairo)
library(data.table)
library(hdf5r)})

h1<-Read10X_h5("submit.h5")

Error in self$read_low_level(file_space = self_space_id, mem_space = mem_space_id, : HDF5-API Errors:
    error #000: H5Dio.c in H5Dread(): line 179: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #001: H5VLcallback.c in H5VL_dataset_read(): line 2011: dataset read failed
        class: HDF5
        major: Virtual Object Layer
        minor: Read failed

    error #002: H5VLcallback.c in H5VL__dataset_read(): line 1978: dataset read failed
        class: HDF5
        major: Virtual Object Layer
        minor: Read failed

    error #003: H5VLnative_dataset.c in H5VL__native_dataset_read(): line 166: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #004: H5Dio.c in H5D__read(): line 545: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #005: H5Dchunk.c in H5D__chunk_read(): line 2549: unable to read raw data chunk
        class: HDF5
        major: Low-level I/O
        minor: Read failed

    error #006: H5Dchunk.c in H5D__c
Traceback:

1. Read10X_h5("submit.h5")
2. sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]), 
 .     dims = shp[], giveCsparse = FALSE)
3. .M.kind(x)
4. counts[]
5. `[.H5D`(counts, )
6. x$read(args = args, dataset_xfer_pl = dataset_xfer_pl, flags = flags, 
 .     drop = drop, envir = envir)
7. self$read_low_level(file_space = self_space_id, mem_space = mem_space_id, 
 .     dataset_xfer_pl = dataset_xfer_pl, set_dim = TRUE, dim_to_set = dim_to_set, 
 .     drop = drop)

Thank you so much for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Just to confirm is your file a h5 file generated by cell ranger or by tool using the cell ranger format?

Best,
Sam

**Comment by MrClearLovez** [comment]
> 
Hello,
I solved this problem by changing to another computer, but the specific problem is not clear. Sincere thanks for your help!

**Comment by MrClearLovez** [comment]
Hello,
I solved this problem by changing to another computer, but the specific problem is not clear. Sincere thanks for your help!





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samuel ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [satijalab/seurat] H5 file not opening with Read10X_h5 function (Issue #6006)





 
Hi,
 
Not member of dev team but hopefully can be helpful.  Just to confirm is your file a h5 file generated by cell ranger or by tool using the cell ranger format?
 
Best,
 Sam
