### ISSUE TITLE
How does AggregateExpression() of raw counts result in decimal values?

### ISSUE THREAD

**Issue by CarlottaHS** [satijalab/seurat#6007]
Hi Seurat-team,

I have a question about you AggregateExpression() function. I understand this function is simply summing up the counts by the categories specified in the `group.by` parameter. As far as I understand the raw counts in my object are saved at `seurat_obj,@assays$RNA@counts`
Thus, I ran the function:
```
cts <- Seurat::AggregateExpression(seurat_obj,
                                  group.by=c("cell_type","orig.ident"), 
                                  assays="RNA",
                                  slots="counts",
                                  return.seurat=FALSE)```

So, assuming this function is simply summing up the raw counts of my object, how is it possible that the final result includes decimal values and not only integers? I have trouble finding my mistake and hope you can help me!

Thanks in advance!

**Comment by yuhanH** [comment]
Hi, 
Currently `AggregateExpression` can only average your data. But you can use this internal `Seurat:::PseudobulkExpression(pb.method = 'aggregate' )`to sum up counts by `categories. 
Here is an example:
```
bulk <- Seurat:::PseudobulkExpression(object = pbmc_small, pb.method = 'aggregate', slot = 'counts')
 ```
We will add this parameter in `AggregateExpression` soon.

**Comment by yuhanH** [comment]
yes. just need to set `pb.method = 'aggregate'` in the `PseudobulkExpression`.

**Comment by CarlottaHS** [comment]
Great, thanks!

**Comment by shanshancode** [comment]
how to select certain column from this dataframe
> head(sc.de@meta.data)
                                orig.ident nCount_RNA nFeature_RNA treatment time replicate genetype percent.mt percent.chl percent.rRNA nCount_SCT nFeature_SCT log10GenesPerUMI treat_time
Mock_3hpi_1_AAACCCAAGTGCTCAT-1 Mock_3hpi_1       3291         1456      Mock 3hpi         1     Col0  0.7292616    3.524765    1.3065937       2967         1455        0.8993081  Mock_3hpi
Mock_3hpi_1_AAACCCAAGTTGGACG-1 Mock_3hpi_1       3147         1333      Mock 3hpi         1     Col0  0.8261837    4.766444    1.8112488       2913         1333        0.8933455  Mock_3hpi
Mock_3hpi_1_AAACCCACACCGTGAC-1 Mock_3hpi_1       3762         1628      Mock 3hpi         1     Col0  0.5316321    3.216374    1.1164274       3095         1618        0.8982596  Mock_3hpi
Mock_3hpi_1_AAACCCAGTCCCTAAA-1 Mock_3hpi_1       5569         1986      Mock 3hpi         1     Col0  0.2334351   14.185671    0.5027833       3291         1730        0.8804526  Mock_3hpi
Mock_3hpi_1_AAACCCATCCGGACGT-1 Mock_3hpi_1       3634         1480      Mock 3hpi         1     Col0  0.8805724   10.897083    1.5410017       3067         1474        0.8904267  Mock_3hpi
Mock_3hpi_1_AAACCCATCGTTCAGA-1 Mock_3hpi_1       3086         1443      Mock 3hpi         1     Col0  0.2916397    3.985742    1.1665587       2897         1443        0.9053906  Mock_3hpi
