### ISSUE TITLE
Footprint / PlotFootprint error : Error in match(x, table, nomatch = 0L)...

### ISSUE THREAD

**Issue by matteozoia4** [satijalab/seurat#6009]
I add motifs to an object (heart) and I then would like to perform Footprinting on some Promoter-Element linked peak regions.

`pfm <- getMatrixSet(
  x = JASPAR2022,
  opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
)`
`motif.matrix <- CreateMotifMatrix(
  features = StringToGRanges(rownames(heart), sep = c(":", "-")),
  pwm = pfm,
  genome = BSgenome.Mmusculus.UCSC.mm10,
  sep = c(":", "-"),
  use.counts = FALSE
)`
`heart <- AddMotifs(
  object = heart,
  genome = BSgenome.Mmusculus.UCSC.mm10,
  data = motif.matrix,
  pfm = pfm
)`
`heart <- RegionStats(
  object = heart,
  genome = BSgenome.Mmusculus.UCSC.mm10,
  sep = c(":", "-")
)`

`FootprintOnChromatinAssay <- Footprint(heart,
    BSgenome.Mmusculus.UCSC.mm10,
    motif.name = NULL,
    key = motif.name,
    regions = c("chr3-66656199-66656963", "chr3-66591579-66593056", "chr3-66970054-66971268", "chr3-66576632-66577579"),
    assay = heart@assays[["Macs2Peaks"]],
    upstream = 250,
    downstream = 250,
    compute.expected = TRUE,
    in.peaks = FALSE,
    verbose = TRUE
    )`

I got this error though:

`Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments`

Best regards and thank you!

**Comment by timoast** [comment]
Please open an issue in the SIgnac repository: https://github.com/timoast/signac
