### ISSUE TITLE
How to combine more than 2 set?

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#601]
Hi,
I'm trying to combine several set in order to compare them. I follow the tutorial **Tutorial: Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses** in order to add more than two datasets.
Si I perform the first step of the tutorial **Setup the Seurat objects** then when I am in the **Perform a canonical correlation analysis (CCA)** part I don't know how to proceed.
In your example for the `RunMultiCCA`, for `genes.use` you select `pbmc_small@var.genes` because this is the same set, but in the case of differents dataset, how do we do?

Just to check, this is what I tried to do:
```R
# ----------- Gene selection for input to CCA
ctrl_SC07_3HR <- FindVariableGenes(ctrl_SC07_3HR, do.plot = T)
ctrl_SC07_0HR <- FindVariableGenes(ctrl_SC07_0HR, do.plot = T)
ctrl_SC06_3HR <- FindVariableGenes(ctrl_SC06_3HR, do.plot = T)
ctrl_SC06_0HR <- FindVariableGenes(ctrl_SC06_0HR, do.plot = T)

g.1 <- head(rownames(ctrl_SC07_3HR@hvg.info), 1000)
g.2 <- head(rownames(ctrl_SC07_0HR@hvg.info), 1000)
g.3 <- head(rownames(ctrl_SC06_0HR@hvg.info), 1000)
g.4 <- head(rownames(ctrl_SC06_0HR@hvg.info), 1000)
genes.use <- unique(c(g.1, g.2,g.3,g.4))
genes.use <- intersect(genes.use, rownames(ctrl_SC07_3HR@scale.data))
genes.use <- intersect(genes.use, rownames(ctrl_SC07_0HR@scale.data))
genes.use <- intersect(genes.use, rownames(ctrl_SC06_0HR@scale.data))
genes.use <- intersect(genes.use, rownames(ctrl_SC06_3HR@scale.data))

# Run CCA
multiCCA_list <- list(ctrl_SC07_3HR , ctrl_SC07_0HR, ctrl_SC06_3HR,ctrl_SC06_3HR )

immune.combined_TEST <- RunMultiCCA(object.list=multiCCA_list, genes.use = ctrl_SC06_3HR@var.genes, num.ccs=4)
```

Then I add this message:
```R
[1] "Computing CC 1"
[1] "Computing CC 2"
[1] "Computing CC 3"
[1] "Computing CC 4"
Error in MergeSeurat(object1 = combined.object, object2 = object.list[[i]],  : 
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names
```

**Comment by mschilli87** [comment]
@camilliano: see https://github.com/satijalab/seurat/issues/207, https://github.com/satijalab/seurat/issues/239, https://github.com/satijalab/seurat/issues/600, https://github.com/satijalab/seurat/issues/549, https://github.com/satijalab/seurat/issues/562, https://github.com/satijalab/seurat/issues/567 & https://github.com/satijalab/seurat/issues/568 :wink:

**Comment by mojaveazure** [comment]
Please update to Seurat v2.3.3 (as per #592)
