### ISSUE TITLE
Is it ok to regress out individual sample/dataset?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6014]
Hi! I’m very curious about this. To regress out unwanted variations, a covariate can be regressed out during scaledata(), eg percent mitochondria, percent ribosome, or nCount_RNA, batch number, etc. 

During integration of a number of samples/datasets like across studies/cohorts (like from 5 studies), disease conditions (like mild, moderate, severe, death, asymptomatic), tissue types (like blood, lung), is it okay to just regress the “dataset” or “sample” column in seurat object to regress out individual variations? 

From a general observation, after regressing individual samples/datasets, same cell types tend to cluster together in one cluster regardless if they are from normal, or moderate, or severe. But if sampels/datasets are not regressed, the same cell type—but from normal and from severe—separates from each other.

Is it beneficial or should this be avoided?

Will it negatively affect discovery of phenotype-associated cell states or phenotype-associated subpopulation, because regressing individuals prevents the deviation of one cell type cluster into separate subset-clusters? I haven’t really seen a published study who regressed out individual datasets in integrated studies. So I wonder if this is something that should not be done.

Thank you very much in advance!

**Comment by saketkc** [comment]
Regressing out a sample would probably make sense if you have evidence that the effects arising from each sample have an additive effect (which is *uninteresting*) on the observed counts (ScaleData() uses a linear regression to regress out a covariate). In most cases, the sample or batch specific effects are non-linear (which is what the batch correction approaches in Seurat and other methods try to handle). A similar logic also applies when you have multiple covariates.
