### ISSUE TITLE
Subset a cell group from Seurat objects and FindAllMarkers showed a relative low avg_log2FCand close pcts

### ISSUE THREAD

**Issue by zrhhl** [satijalab/seurat#6021]
Hi seurat team,
Thanks for your excellent analysis instrument! 
Here I have a dataset and identify the cell group with all the data. Then I used `subset()`  to get a cell group, split by its "orig.  ident"and did routine analysis. When I called `FindAllMarkers()` I found the results show a short DEG list in each cluster and the top DEG has a relative low avg_log2FC.  Also, pct.1 is close to pct.2.
Did it mean the FindClusters result should be adjusted or does this cell group not have obvious heterogeneity?

Here is the main code :
```
sub_obj <- subset(x = combine_obj, idents = c(7,9,13,15,16,17,18,19,21,22,23,24))
DefaultAssay(sub_obj) <- "RNA"
Subset_Cells.list <- SplitObject(sub_obj, split.by = "orig.ident")
for (i in 1:length(Subset_Cells.list)) {
                Subset_Cells.list[[i]] <- NormalizeData(Subset_Cells.list[[i]], verbose = FALSE)
                Subset_Cells.list[[i]] <- FindVariableFeatures(Subset_Cells.list[[i]], selection.method = "vst", nfeatures = 2000,verbose = FALSE)
        }
Integrated <- FindIntegrationAnchors(object.list = Subset_Cells.list, dims = 1:30)
Integrated <- IntegrateData(anchorset = Integrated, dims = 1:30)
DefaultAssay(object = Integrated) <- "integrated"
combined=ScaleData(Integrated,verbose = FALSE)
combined <- RunPCA(object = combined, npcs = 24, verbose = FALSE)
combined <- RunUMAP(object = combined, reduction = "pca", dims = 1:24)
combined <- FindNeighbors(object = combined, reduction = "pca", dims = 1:24)
combined <- FindClusters(combined, resolution = 0.3)
combined.markers <- FindAllMarkers(object = combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use ="wilcox")
```

Here is the part of top DEG:
![image](https://user-images.githubusercontent.com/60513492/171116483-b413fc0e-16d4-4430-a7de-c6e0544d7c3d.png)
![image](https://user-images.githubusercontent.com/60513492/171116533-6fe8c614-b180-4a29-9c67-a024a214a23a.png)

I have check the Q&A and did not find the definite answer.
Hope to your reply.

Thanks,
Laura

**Comment by saketkc** [comment]
> When I called FindAllMarkers() I found the results show a short DEG list in each cluster and the top DEG has a relative low avg_log2FC. Also, pct.1 is close to pct.2.

`FindAllMarkers()` does one celltype vs. rest comparison - so when you subset, the "rest" group has effectively changed which is why you would see `pct.2` (proportion of cells in the "rest" category that have a non-zero value for this gene) value change (however, note that the tables you posted above are for two different clusters). Hope that helps.

**Comment by zrhhl** [comment]
> `FindAllMarkers()` does one celltype vs. rest comparison - so when you subset, the "rest" group has effectively changed which is why you would see `pct.2` (proportion of cells in the "rest" category that have a non-zero value for this gene) value change (however, note that the tables you posted above are for two different clusters). Hope that helps.

Thanks for your explanation. You said it, the "rest" group changed when I selected part of the cells. My purpose is to compare the subtle difference in a cell group(like the epithelial cells can be divided into basal, goblet, epithelial progenitor cells and other epithelial classes), so I choose the cell class(like total epithelial cells or total immune cells) to compare the difference in it. ​Maybe the result could indicate there was no obvious difference in it or the cell class has no significant heterogeneity (un, if the analysis code was right)?

Thanks,
laura

**Comment by saketkc** [comment]
The top few genes are differentially expressed (with a log2FC ~ 0.5) in cluster 0 - though are not specific to it (because they are also expressed in the "rest" with a pct.2 > 0.9). I think this is what you are saying too.

**Comment by zrhhl** [comment]
> 

Yes, we have reached an agreement on the results above. I just wonder if I can access the necessity to divide a  large cell cluster into many small cell clusters base on the `FindAllMarkers()` result. ​Perhaps it should be determined with biological knowledge. Anyway, thanks for your patient explanation!​ :grinning:
