### ISSUE TITLE
Filtering TransferData results based on prediction scores

### ISSUE THREAD

**Issue by GabrielBaldissera** [satijalab/seurat#6023]
Hello, 

I have used the TransferData function to predict cluster IDs for some new cells and I was wondering how to read the results. I see there is a prediction score for each label tested and a maximum score that corresponds to the predicted.id identified.
I noticed that the prediction ID score has a range of 0 to 1, being that some cells are predicted to an ID with a maximum score of 1 for a given ID and others with lower scores.

My projection overall seems good as I have inspected the predicted groups with Violin plots for cell type markers and calculated conserved markers. However, I have some large clusters that have cells with low prediction scores. I am concerned maybe this is impacting the results of downstream analyses. 

I am considering removing some of these cells that had a lower score for the label prediction. Would you have any advice or guideline on how to go about the prediction scores? Let`s say how to think of thresholds? 

I was considering using something like the following to remove some of the cells with lower prediction scores.
```
> table(new_sample_query@meta.data$prediction.score.max > 0.60)

FALSE  TRUE 
 1571  6867 
```
Do you think that could be a reasonable value for a threshold?

One observation is that I am very confident that there is no different population among the cells I am projecting. I have done some pre-processing and subset the cells I am projecting, so they should be similar cell types.

I would appreciate any thoughts about this.

Thanks!
Best,

Gabriel

**Comment by torkencz** [comment]
Hi,

A similar question was asked in issue [1959](https://github.com/satijalab/seurat/issues/1959). I would recommend you read the paper [here](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8), as suggested in there. Overall, I think your threshold is reasonable. There is no surefire way of telling what your threshold should be, as long as you checked conserved markers and think that the cells in question are lower quality (check quality metrics for those groups), you can remove them in my opinion.
