### ISSUE TITLE
Spatial transcriptomics, Harmony & normalisation

### ISSUE THREAD

**Issue by JJBio** [satijalab/seurat#6028]
I am analysing multiple Visium slides and have a grave batch effect. 
As suggested by [10x](https://kb.10xgenomics.com/hc/en-us/articles/360054864351-Can-I-aggregate-data-from-different-samples-or-staining-protocols-using-spaceranger-aggr-), I would like to correct for the batch effect using Harmony. 
However, SCtransform and Harmony (used according to this [workflow](https://github.com/satijalab/seurat/issues/4896)), did not give me good results. In contrast, using the 'old' normalisation (lognormalize) works much better (at least the results are biologically more sensible). Additionally, I would like use my scRNA-seq dataset for integration, which is also processed with lognormalize. Furthermore, I am avoiding this [issue](https://github.com/satijalab/seurat/issues/5009), correct? So, the final corrected values are not comparable across samples. 
Nevertheless, the [vignette](https://satijalab.org/seurat/articles/spatial_vignette.html) states:  
> As a result, standard approaches (such as the [LogNormalize()](https://satijalab.org/seurat/reference/LogNormalize.html) function), which force each data point to have the same underlying ‘size’ after normalization, can be problematic.

Hence, my final question is how problematic is using lognormalize on spatial data? Would you absolutely not recommend it?

**Comment by rsatija** [comment]
While we use SCTransform in the vignettes, it is certainly not problematic to use LogNormalize when doing spatial workflows
