### ISSUE TITLE
Accessing data from the Seurat object

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6029]
Once the entire pipeline is run on data (meaning the seurat object created, data is subset, normalized, scaled, PCA run, UMAP run, etc), is it possible to somehow grab the original, pre-processed data from the object?  I'm asking because I'd like to generate FeatureScatter plots but I only want to write the code once - after all the data has been processed.  At this point is it possible to generate the plots on the pre-processed and post-processed data?

Thanks

**Comment by rsatija** [comment]
Absolutely, you can use the GetAssayData or FetchData functions, you can see examples at:
https://satijalab.org/seurat/articles/essential_commands.html

**Comment by samuel-marsh** [comment]
Hi,

You can get overview of what is contained in each slot on the Seurat GitHub wiki page: https://github.com/satijalab/seurat/wiki

Best,
Sam
