### ISSUE TITLE
umap visualization for different conditions

### ISSUE THREAD

**Issue by zor4x** [satijalab/seurat#6033]
Hello, I have a seurat object with different conditions: wt_day1, wt_day6, ko_day1 and ko_day6. I have in metadata object the columns that indicates the treatment (WT and KO), the timepoint (day1 and day6), and the column with treatment at timepoint (WT_day1, WT_day6, KO_day1 and KO_day6). 
When I create the dimplot to visualize the UMAP, I would to show only the treatment WT at day1 and day6, but I don't know how to do it, because if I set the option split.by, I can only chose the column with timepoint, treatment, or treatment_timepoint. Can someone help me?
 
that's the example of columns metadata:
[treatment     timepoint   treatment_timepoint
           KO                d1                         KO_d1
           KO                d2                         KO_d6
           WT               d1                         WT_d1
           WT               d2                          WT_d6

**Comment by jarchana09** [comment]
Hi. I am not a member of the Seurat development team, but perhaps this may be helpful. You could try to subset the data based on the chosen metadata columns while plotting. For example,
`DimPlot(object = subset(seurat_object,  treatment_timepoint %in% c("WT_d1", "WT_d6")), split.by = "treatment_timepoint")`

Hope this helps. Thank you

**Comment by torkencz** [comment]
Hi. Yeah, I would either subset your data to those two timepoint treatment combos or if you would like to show everything on your UMAP I would set colors so the KO groups are very faint grey etc.
