### ISSUE TITLE
Using multiple genes to mark clusters

### ISSUE THREAD

**Issue by Dillon214** [satijalab/seurat#6040]
Hello Seurat team,

The end-goal of my analysis involves selecting genes to stain different cell populations using immunohistochemisty. While FindMarkers is good at finding genes that, on their own, are fairly strong markers, I was wondering whether there is a built-in way to determine a set of genes (say, 2-3) which co-expresses within a specific cluster. This might be able achieve a higher level of specificity than any one given gene.

**Comment by yuhanH** [comment]
hi @Dillon214 
In `FindMarkers`, we have installed several differential methods. You can see the document by `?FindMarkers` and then set the method in the parameter `test.use` in `FindMarkers`.
