### ISSUE TITLE
Regress.out actually does NOT regress

### ISSUE THREAD

**Issue by emanuelavilla** [satijalab/seurat#6044]
Hello Seurat Team!

I am trying to mitigate the effect of ribosomal genes in my integrated data. To contextualise, I have 4 data of leukaemia, 2 from a mouse and 2 from another mouse. We found that one mouse has high-level expression of ribosomal genes and we want to regress this variance. 

I applied 2 strategies: first I have added the ribosomal metadata column in the single object with _SeuratObj[["percent.rb"]] <- PercentageFeatureSet(SeuratObj, pattern = "^Rp[sl]")_ and then I  used the metadata column in vars.to.regress parameter during ScaleData. The other strategy I applied was running _AddModuleScore_ using a list of genes for the 2 subunits of the ribosome and then I used the score as a variable to regress in ScaleData. 

However, in both cases, I found that the ribosomal genes still influenced the clusterisation and integration of all 4 data. 

Any suggestion?

**Comment by saketkc** [comment]
Can you paste your full code code here?

**Comment by emanuelavilla** [comment]
> Can you paste your full code code here?

For the first strategy, I used the PercentageFeatureSet to calculate the percentage of ribosomal content per cell and used that as a variable to regress.

_obj.combined[["percent.rb"]] <- PercentageFeatureSet(obj.combined, pattern = "^Mrp[sl]", assay = "RNA")
obj.combined <- ScaleData(obj.combined, verbose = T, vars.to.regress = c("percent.rb"))
obj.combined <- RunPCA(obj.combined, npcs = 30, verbose = FALSE)
obj.combined <- RunUMAP(obj.combined, reduction = "pca", dims = 1:30)
obj.combined <- FindNeighbors(obj.combined, reduction = "pca", dims = 1:30)
obj.combined <- FindClusters(obj.combined, resolution = 0.5)_

For the second strategy, I followed the vignette of the cell cycle regression. So, I started with a list of the ribosomal genes from the Ribosomal Protein Gene Database (http://ribosome.med.miyazaki-u.ac.jp/rpg.cgi?mode=orglist&org=Mus%20musculus&type=m).

_Ribo.small.subunit = c("Mrps2", "Mrps5", "Mrps6", "Mrps7", "Mrps9", "Mrps10", "Mrps11", "Mrps12", "Mrps14", "Mrps15", "Mrps16", 'Mrps17', 'Mrps18a', 'Mrps18b', 'Mrps18c', 'Mrps21', 'Mrps22', 'Mrps23', 'Mrps24', 
                       'Mrps25', 'Mrps26', 'Mrps27', 'Mrps28', 'Mrps29', 'Mrps30', 'Mrps31', 'Mrps33', 'Mrps34', 'Mrps35', 'Mrps36')

Ribo.large.subunit = c('Mrpl1','Mrpl2','Mrpl3','Mrpl4','Mrpl9','Mrpl10','Mrpl11','Mrpl12','Mrpl13','Mrpl14','Mrpl15','Mrpl16','Mrpl17','Mrpl18','Mrpl19','Mrpl20','Mrpl21','Mrpl22','Mrpl23','Mrpl24','Mrpl27','Mrpl28',
                       'Mrpl30','Mrpl32','Mrpl33','Mrpl34','Mrpl35','Mrpl36',	'Mrpl37', 'Mrpl38', 'Mrpl39', 'Mrpl40', 'Mrpl41', 'Mrpl42', 'Mrpl43','Mrpl44-1','Mrpl45','Mrpl46','Mrpl47', 'Mrpl48-1','Mrpl48-2','Mrpl49',
                       'Mrpl50','Mrpl51','Mrpl52','Mrpl53','Mrpl54','Mrpl55','Lactb')_

Then, I created a list of these genes and run the AddModuleScore on that list of genes.

_Ribo.genes = list(Ribo.small.subunit, Ribo.large.subunit)

APL.combined <- AddModuleScore(
  object = APL.combined,
  features = Ribo.genes,
  name = 'RiboScore',
  assay = "RNA"
)_

After that I scaled the data and the PCA.

_obj.combined <- ScaleData(obj.combined, vars.to.regress = c("RiboScore_smallSub", "RiboScore_largeSub"), features = rownames(obj.combined))

obj.combined <- RunPCA(obj.combined, features = VariableFeatures(obj.combined), nfeatures.print = 10)_

**Comment by saketkc** [comment]
The steps look correct, though only one of them should suffice. It is hard to comment on the actual results without taking a look at the data. You could also try  [SCTransform workflow](https://satijalab.org/seurat/articles/sctransform_vignette.html) to mitigate the ribosomal effects or remove them from the set of you `VariableFeatures()` before running integration. `VariableFeatures(object) <- setdiff(VariableFeatures(object), ribo_genes)`
