### ISSUE TITLE
Computing transcriptional burst kinetics from single-cell data in seurat

### ISSUE THREAD

**Issue by harshini-c** [satijalab/seurat#6046]
Hi,

I was wondering if we can use Seurat to compute burst size and burst frequency from scRNAseq datasets ? There seems to be RNA velocity analysis available, but I am looking for transcriptional bursting kinetics.

Thank you,
Harshini

**Comment by saketkc** [comment]
There is currently no support for modeling burst kinetics in Seurat.

**Comment by harshini-c** [comment]
Hi,

Thanks for the reply. I am wondering if the seurat dev team is aware of any tools avaible for computing bursting kinetics from scRNAseq data (non-allelic)? any recommendations? Or any reason for not including this analysis in Seurat or any thoughts on being available in the future? 

Do you think analysis of transcriptional kinetics from scRNAseq is widely accepted or there still exist some questions on the validity of the results from existing models.

Your thoughts in this regard would be very helpful!
Thanks!
