### ISSUE TITLE
Clarification of Atomic Sketch Integrated Reference Annotation

### ISSUE THREAD

**Issue by rbutleriii** [satijalab/seurat#6048]
Hello, Running thorough the [Atomic Sketch Integration Tutorial](https://satijalab.org/seurat/articles/atomic_integration.html) and I had some confusion between the paper and the tutorial.

I generate the integrated the subset of atoms, and then I place the original datasets in this space for the tutorial to see them fully reconstituted. 👍

If I instead wanted to map _another_ dataset into this space to transfer cell annotations to the new dataset. Can I take the `atoms.merge` object after `RunUMAP` and plug this straight into [Unimodal UMAP projection](https://satijalab.org/seurat/articles/integration_mapping.html#unimodal-umap-projection-1) (i.e. `MapQuery`)? 

So something like: 
```R
# optional step: SCTransform normalization
for (i in seq(atoms.list)) {
    atoms.list[[i]] = SCTransform(atoms.list[[i]], vst.flavor="v2", verbose=F)
}

# perform integration
features = SelectIntegrationFeatures(object.list=atoms.list)
atoms.merge = FastRPCAIntegration(object.list=atoms.list, dims=1:80, 
                                  normalization.method="SCT", 
                                  anchor.features=features)

# we can generate a 2D visualization representing the integrated atoms
atoms.merge = RunUMAP(atoms.merge, reduction="integrated_dr", dims=1:80, 
                      return.model=T)

# load my data that needs annotations (already has RunPCA w/ 80 PCs and RunUMAP)
sc = readRDS("20220418.PS19_C31.overall.rds")

# Transfer annotations from reference
sc.anchors = FindTransferAnchors(reference=atoms.merge, query=sc, dims=1:80, 
                                 reference.reduction="pca")
sc = MapQuery(anchorset=sc.anchors, reference=atoms.merge, query=sc, 
              refdata=list(class="class_label", subclass="subclass_label", 
                           neighborhood="neighborhood_label", region="region_label"), 
              reference.reduction="pca", reduction.model="umap")
```

**Comment by yuhanH** [comment]
hi @rbutleriii 
Right. You can this integration and mapping. 
There is a minor issue in your script. You need to set `normalization.method = "SCT"` in the `FindTransferAnchors` step.

**Comment by rbutleriii** [comment]
Thanks @yuhanH, I got another error on `FindTransferAnchors`: 
```R
Error: Given reference assay (SCT) has 2 reference sct models. Please provide a reference assay with a  single reference sct model.
```
Seems because `SCTransform` was performed on the list prior to integration. If I rerun `SCTransform` after `FastRPCAIntegration` and then try to find transfer anchors, it works: 
```R
atoms.merge = SCTransform(atoms.merge, vst.flavor="v2")

> > allen
> An object of class Seurat
> 54623 features across 30000 samples within 2 assays
> Active assay: SCT (23153 features, 3000 variable features)
>  1 other assay present: RNA
>  3 dimensional reductions calculated: integrated_dr, pca, umap

# Transfer annotations from reference
sc.anchors = FindTransferAnchors(reference=atoms.merge, query=sc, dims=1:50, 
                                 reference.reduction="integrated_dr")
sc = MapQuery(anchorset=sc.anchors, reference=atoms.merge, query=sc, 
              refdata=list(class="class_label", subclass="subclass_label", 
                           neighborhood="neighborhood_label", region="region_label"), 
              reference.reduction="integrated_dr", reduction.model="umap")
```
but is that going to impact the `"integrated_dr"` reduction model that I am re-normalizing? I am also a little unsure if I should be using `reference.reduction="integrated_dr"` or `reference.reduction="pca"`, but it seems like only the former will have properly integrated reference datasets.
![20220621 PS19_C31 atom integrated subclass_annots](https://user-images.githubusercontent.com/6644896/174910273-658d6777-12b3-4653-ae95-8939c1f965fd.png)

**Comment by yuhanH** [comment]
Hi, @rbutleriii 
You need to change the default assay of atoms.merge to `integrated` and then there will be only one SCT model. 
You don't need to re-run SCT after integration. You should use `reference.reduction="integrated_dr"` in FindTransferAnchor. 
In `MapQuery`, you do not need to set `reference.reduction="integrated_dr"`. 
Please let me know if you still meet any error.
