### ISSUE TITLE
Is a way to obtain batch effect-adjusted gene expression matrix using Seurat

### ISSUE THREAD

**Issue by jiajinlongkang** [satijalab/seurat#6052]
Hi Seurat group, 

I have some questions running through the seurat data integration tutorial here (https://satijalab.org/seurat/articles/integration_introduction.html).

I have integrated several datasets of my own following the instructions in the above tutorial. However, some of my downstream analysis requires a batch effect-adjusted expression matrix but I am not sure whether I can get such thing using Seurat. It appears to me that Seurat CCA returns by default an adjusted gene expression matrix for those highly variable genes under the "integrated assay". **Therefore it seems that by setting the integration features to all genes in the object I can theoretically obtain an adjusted expression matrix for all genes**. Nevertheless, I suspect it would become computationally intensive and time-consuming. Besides, I have the impression that the integrated assay data should not be used for downstream analysis except for clustering and visualization, since the assay is reverted to "RNA" for differential expression as shown in the above tutorial.

I also checked batch effect correction methods included in seurat-wrapper, such as LIGER and fastMNN, but they appear to perform correction in the low dimensional embedding space.

I wonder whether Seurat provides any method (either Seurat functions or any other community packages wrapped in Seurat) that can return a batch effect-adjusted gene expression matrix. Specifically,  is setting features to all genes in CCA a feasible way (as shown in bold text)? If not, is there any other functions I can use for this purpose?

Thank you for your help.

Jack Kang

**Comment by timoast** [comment]
You can set the `features.to.integrate` parameter in `IntegrateData()` to change the set of features that are corrected, and you could set this to all genes in the dataset if you wanted to. However for most downstream applications you only are interested in a batch-corrected low-dimensional space, and for things like differential expression or data visualization we don't recommend using batch corrected data.
