### ISSUE TITLE
Tracing Cells from one Seurat object on another Seurat Object

### ISSUE THREAD

**Issue by Victoriat0618** [satijalab/seurat#6053]
Hi there,

I'm trying to trace a group of cells in one cluster on a New UMAP plot of the same sample.  I am trying to locate the location of these cells on a new UMAP plot based on the new seurat clustering of the sample.  I managed to get the cell ids of the cells that I'm tracing but am not sure how to correctly input this info in my new seurat object. 

Any help would be appreciated. Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Are you looking to find the new numerical coordinates or just visualize those cells on the new UMAP plot, both?  Are you looking for 1:1 mapping per cell or simply where that group of cells is?

Best,
Sam

**Comment by Victoriat0618** [comment]
I'm simply trying to figure out where that cells are located on the UMAP plot. I have the cell ids but wasn't sure what's the best way to approach this as metadata?

Thanks,
Victoria

**Comment by JJBio** [comment]
Not a member but maybe I have helpful input. 
I have done something similar (I just wanted to check how the annotation of a different workflow mapped to the new workflow). I have simply used the `merge` function to merge the metadata of two seurat objects - however you need to make sure that the **order of the merged metadata** is the same as before! Then set the idents to what you are interested in and plot the UMAP. Maybe there is a nicer way of doing this but this worked for me.

**Comment by samuel-marsh** [comment]
Hi,

Sorry for delaying responding.  If you have list of cell names from the first object and want to see them on the new UMAP plot then you can simply supply those names in the `DimPlot` call:

```
cell_names <- c("Cell1", "Cell2", ...)

DimPlot(object = OBJECT, cells.highlight = cell_names)
```


If you want the new UMAP coordinates for the old cells you can use `Embeddings()` to pull the coordinates from new analysis and then filter that result by the cell names from previous analysis.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @Victoriat0618 

Did this solve your issue or is there something else you need help with tracking the cells?

Best,
Sam

**Comment by Victoriat0618** [comment]
Hi Sam,

Thanks for the answer. Yes. The issue has been resolved.
