### ISSUE TITLE
SCTransform after merge or integration  of multiple sample

### ISSUE THREAD

**Issue by MasumiO** [satijalab/seurat#6054]
Hi seurat team! Thank you for the great tools for single-cell analysis.

Now we are preparing about 100 samples using the 10X Multiome kit. 100 samples are classified into two conditions.
We speculate that a Seurat object merged or integrated all data is large enough to be short of RAM, which motivates us to merge objects subsetted by cell type. (We are using 128G RAM.)

 Based on my situation, I have three questions. If you find any misunderstanding, please correct me.

1.  When should we use SCTransform(). Before merge/integrate or after?

I understand that the data normalized SCTransform is scaled by the median gene expression of all cells in a sample, which can cause the problem that the mere comparison of normalized value (corrected counts) between conditions A/B is meaningless. (This is how we merge() multiple samples, right?) But normalizing values after merge() using SCTransform also sounds like a bit of trouble because of the following reason. In my understanding, SCTransform finally fits parameters using values from all cells from a sample. The paper introducing SCTransform v2 suggests the parameter theta is varied by sample (Is it right?). If so, I think it is weird that parameters common among samples are fitted using the value of all samples. 
I know that using IntegrateData() is the way to fix this problem, but you already suggested using merge(), not IntegrateData(), in many answers posted here. (like #4000) How to fix this problem?

2. Does merging/Integrating subsets of objects cause a problem or not?

As mentioned before, we plan to merge objects after subsetted by cell types, which means that we will merge objects as many times as the cell types. Does this operation affect the downstream analysis? I'm wondering if the normalization of SCTransform after the merge may lead to the problem (if we choose to do so). The select variable features also may cause the difference, leading to different results from using an unsplit object. Is it suitable for downstream analysis such as dimension reduction, clustering, or identifying the difference between conditions/ among samples? I think that the IntegrateData() may cause different results similar to the above.

3.  Are DE/DA tests affected by merging/integrating?

In my understanding, FindMarkers() do not always use the normalized values. We can include a design matrix in the test and conduct DE tests regardless of a merging/integrating method you suggested using, right? If so, questions 1&3 confused me... Why should we not use IntegrateData() when conducting the DE test???

**Comment by saketkc** [comment]
> When should we use SCTransform(). Before merge/integrate or after?
> Does merging/Integrating subsets of objects cause a problem or not?

The goal of SCTransform is to perform normalization within an experiment by learning the model of technical noise (within the experiment). If you have multiple experiments, we recommend running SCTransform on each experiment individually. Merging or integrating is very context dependent - you could start by asking if integration is really required by performing a dimensionaly reduction on merged dataset and proceed to integration if you notice batch effects. For integration on large datasets, Seurat provides two workflows in [this](https://satijalab.org/seurat/articles/integration_large_datasets.html) and [this](https://satijalab.org/seurat/articles/atomic_integration.html) vignette. Hopefully this answers both of your questions.


> Are DE/DA tests affected by merging/integrating?

The goal of integration is to find corresponding cell states across conditions (or experiments). Integrated values are non-linear transformation of `scale.data` which implies they cannot be used for DE/DA analysis and hence we recommend using the RNA or SCT assay ("data" slot) for performing DE. An example of this workflow is in [this](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) vignette. Hope this helps.
