### ISSUE TITLE
FindTransferAnchors error when using SCT-transformed & Merged data as reference

### ISSUE THREAD

**Issue by JohnGenome** [satijalab/seurat#6055]
Hi!
I'm using Seurat v4.0.4, and got an error when using FindTransferAnchors() with SCT-transformed & Merged data as reference.
The codes:
`tmp1 <- SCTransform(tmp1, assay = "RNA")`
`tmp2 <- SCTransform(tmp2, assay = "RNA")`
`tmp3 <- SCTransform(tmp3, assay = "RNA")`
`tmp.merge <- merge(tmp1, y = c(tmp2,tmp3), merge.data = T)`
`anchors <- FindTransferAnchors(reference = tmp.merge, query = query.data, normalization.method = "SCT")`
The message:
`Error in as.data.frame.default(x) :
  cannot coerce class 'structure("SCTModel", package = "Seurat")' to a data.frame`
When i ran:
`tmp.merge = UpdateSeuratObject(tmp.merge)`
`tmp.merge = UpdateSCTAssays(tmp.merge)`
It report the same error:
`Error in as.data.frame.default(x) :
  cannot coerce class 'structure("SCTModel", package = "Seurat")' to a data.frame`

Should I take additional steps processing the merged data or follow the standard integration procedure on datasets normalized with SCTransform from the begining?
Thank you so much for your help!

**Comment by saketkc** [comment]
Can you update to the latest Seurat release and report here if the error persists?

**Comment by JohnGenome** [comment]
Hi saketkc, you are right. Updating Seurat to 4.1.1 did solve the problem. Here is my code:
`> anchors <- FindTransferAnchors(reference = tmp.merge, query = query.data, normalization.method = "SCT", recompute.residuals = T)`
`Error: Given reference assay (SCT) has 3 reference sct models. Please provide a reference assay with a  single reference sct model.`
`# Rerun using query's own model and it works`
`> anchors <- FindTransferAnchors(reference = tmp.merge, query = query.data, normalization.method = "SCT", recompute.residuals = F)`
BTW, if it's better to set recompute.residuals = F? It was suggested to do SCT-transfrom for each sample separately due to different system errors. Similarly, why we have to apply reference model to query data?

**Comment by saketkc** [comment]
Since you are merging the datasets here (and not integrating), the reference model needs to be specified if you want to use the reference model for computing residuals (this particularly helps in cases where the batch effects between reference and query are significant). When set of `FALSE`, this model is learned using the query.

**Comment by JohnGenome** [comment]
Thanks for your kindly reply!

**Comment by denvercal1234GitHub** [comment]
Hey @JohnGenome -- Given that we should set recompute.residuals=T to use ref model in merging, how did you go around the error of SCT ref assay has multiple models? Thank you so much!

**Comment by JohnGenome** [comment]
Hi @denvercal1234GitHub , in my datasets, it seems to be no batch effects between reference and query. I did transfering only to avoid re-merging all samples again. So it's okay to set `recompute.residuals=T`.

**Comment by apal6** [comment]
Hi,

I have a follow up question. I have individual clusters with precomputed embeddings from TSNE. I would like to merge these while preserving the dimentional reduction so that when I generate the dimplot, it comes out to be exactly how it was when individual clusters are plotted.

Thank you for any advice.

Best,
Aastha

**Comment by shaniAmare** [comment]
Hello @apal6 ,

Were you able to sort out this for yourself? If so, can you please give me some tips? My intention is to `FindTransferAnchors` and use `MapQuery` downstream using the `tsne` reduction rather than `pca`.

Many thanks
