### ISSUE TITLE
How to Account for Inter-Replicate Variation

### ISSUE THREAD

**Issue by KSaunders777** [satijalab/seurat#6056]
Hello,

I came across this paper: https://www.nature.com/articles/s41467-021-25960-2 and it essentially says that single-cell DEG methods may be biased towards highly expressed genes and in not accounting for inter-replicate variation, basically returns DEGs that don't actually exist in the biology. I am not a statistician so I may be misunderstanding something, but is there a way in Seurat to account for inter-replicate variation or lessen this bias in FindMarkers or some other step in the Seurat pipeline?

Thanks for reading!

**Comment by KSaunders777** [comment]
Is this perhaps something I would add to the latent.vars parameter in FindMarkers? https://github.com/satijalab/seurat/discussions/4259

**Comment by saketkc** [comment]
You can use MAST or LR based test to account for fixed-effects by specifying "latent.vars = 'mycovariate'", something like: `FindMarkers(test.use="MAST", latent.vars="mycovariate")`. For random-effects we recommend using MAST directly with normalized data values: https://rglab.github.io/MAST/

**Comment by KSaunders777** [comment]
Thank you so much @saketkc!

**Comment by denvercal1234GitHub** [comment]
Hi @saketkc - Would you mind briefly clarifying what you meant by "fixed-effects" versus "random-effects" in the setting of scRNA-seq DEG testing? 

Thank you so much!

**Comment by samuel-marsh** [comment]
Fixed and random effects in this case are parts of the MAST two part hurdle model.  I suggest reading the original MAST paper for more info:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0844-5

In case of inter-replicate variability though you still may be better off with pseudo bulk method depending on question/application.
https://www.biorxiv.org/content/10.1101/2022.02.16.480517v1
