### ISSUE TITLE
Read10X_h5 fails due to hdf5r issues (libhdf5_hl.so.200)

### ISSUE THREAD

**Issue by SuhasSrinivasan** [satijalab/seurat#6058]
Documenting this bug and workarounds for others who may be facing the same issue.

The `Read10X_h5` function fails to work since there are two issues due to the combination of `CentOS 7` and `hdf5r 1.3.5 (latest)`.
The first issue blocks installation and the second issue blocks loading respectively.

These issues along with their workaround were reported to the hdf5r repo:
https://github.com/hhoeflin/hdf5r/issues/188

**Comment by saketkc** [comment]
Thanks for opening the issues @SuhasSrinivasan, however since the underlying issue is tied to `hdf5r`, we will close this here. Hopefully it will get resolved on its own once the rpm/deb repositories are updated.

**Comment by SuhasSrinivasan** [comment]
Hi @saketkc 
Just wanted to check if `rhdf5` (Bioconductor) can be a better backend rather than `hdf5r`.
Since `rhdf5` is not dependent on OS-based HDF5 libraries, it installs and works fine on older systems e.g,. CentOS 7.

**Comment by saketkc** [comment]
Totally possible, though we currently do not want to depend on BioC as it will add another layer of complexity during installation.

**Comment by SuhasSrinivasan** [comment]
Thank you!
