### ISSUE TITLE
Error: Given reference assay (SCT) has (more than one) reference sct models. Please provide a reference assay with a single reference sct model.

### ISSUE THREAD

**Issue by KSaunders777** [satijalab/seurat#6064]
Hello,

I am following this vignette https://satijalab.org/seurat/articles/spatial_vignette.html#integration-with-single-cell-data-1 and am wanting to run `FindTransferAnchors` between an integrated dataset that used the first sctransform integration method (not v2) and made use of the reference-based integration method, and some 10x visium spatial data. However, when I run `FindTransferAnchors`, I get this error: 

```
for (slide in slide_all) {
  DefaultAssay(slide) <- "Spatial"
  slide <- SCTransform(slide, assay = "Spatial", verbose = FALSE) %>%
    RunPCA(verbose = FALSE)
  
  anchors <- FindTransferAnchors(reference = sobj_integrated, 
                                 query = slide, 
                                 normalization.method = "SCT")
}

Error: Given reference assay (SCT) has 7 reference sct models. Please provide a reference assay with a single reference sct model.
```

Because I used reference-based integration, there are 7 SCT.models (one for each variable I split by in SplitObject. Here's what I did for the integration.

```
sobj.list <- SplitObject(sobj, split.by = "Technology")

for (i in 1:length(combo.list)) {
  sobj.list[[i]] <- SCTransform(sobj.list[[i]], verbose = T)
}

features <- SelectIntegrationFeatures(object.list = sobj.list, nfeatures = 3000)
sobj.list <- PrepSCTIntegration(object.list = sobj.list, anchor.features = features)

reference.1 <-  which(names(combo.list) == c("Tech1"))
reference.2 <-  which(names(combo.list) == c("Tech2"))
reference.3 <-  which(names(combo.list) == c("Tech3"))
reference.4 <-  which(names(combo.list) == c("Tech4"))

reference.list <- c(reference.1, reference.2, reference.3, reference.4)

sobj.anchors <- FindIntegrationAnchors(object.list = sobj.list, normalization.method = "SCT", anchor.features = features, reference = reference.list)

sobj_integrated <- IntegrateData(anchorset = sobj.anchors, normalization.method = "SCT")
```

Using the integrated assay for sobj_integrated fixes the issue, but is this correct given this workflow?

Thanks for reading!

**Comment by yuhanH** [comment]
HI @KSaunders777 
In the SCT assay, all SCT models are stored. While integrated assay only stores one final reference SCT model. 
When you run `FindTransferAnchors`, you should set reference object to integrated assay, because you need to build anchors between query and the batch-free reference.

**Comment by yeswzc** [comment]
> HI @KSaunders777 In the SCT assay, all SCT models are stored. While integrated assay only stores one final reference SCT model. When you run `FindTransferAnchors`, you should set reference object to integrated assay, because you need to build anchors between query and the batch-free reference.

Hi, could you me more specific?

I have the same issue but I still can't figure out how to solve this.

I used SCT for feature selection, normalization, PCA  and etc.. Then I used CCAIntegration to integrate two splitted dataset.  In this step, I have to add normalization.method = "SCT" to make it run succefully.
```
sc.ref.integrated <- IntegrateLayers(object = sc.ref, method = CCAIntegration, 
                                     assay = "SCT", normalization.method = "SCT",
                                     orig.reduction = "pca",
                                     new.reduction = "integrated.cca", verbose = FALSE)
```

After this, I tired:
```
> sc.anchors <- FindTransferAnchors(reference = sc.ref.integrated, query = scRNA , dims = 1:30,
+                                   reference.reduction = "pca")
Error: Given reference assay (SCT) has 2 reference sct models. Please provide a reference assay with a  single reference sct model.
In addition: Warning message:
In ValidateParams_FindTransferAnchors(reference = reference, query = query,  :
  Both reference and query assays have been processed with SCTransform.Setting normalization.method = 'SCT' and continuing.
```
, and
```
> sc.anchors <- FindTransferAnchors(reference = sc.ref.integrated, query = scRNA , dims = 1:30,
+                                   normalization.method = "SCT",
+                                   reference.assay = "SCT", query.assay = "SCT",
+                                   reference.reduction = "pca")
Error: Given reference assay (SCT) has 2 reference sct models. Please provide a reference assay with a  single reference sct model.

```
, and
```
> sc.anchors <- FindTransferAnchors(reference = sc.ref.integrated, query = scRNA , dims = 1:30,
+                                   normalization.method = "SCT",
+                                   reference.assay = "integrated", query.assay = "SCT",
+                                   reference.reduction = "pca")
Error in match.arg(arg = value, choices = Assays(object = object)) : 
  'arg' should be one of “RNA”, “SCT”
```
I have no idea what to do to make it run. Can you teach me how should I do?
Thank you!

**Comment by danielcgingerich** [comment]
I believe this is because of the differences in `IntegrateLayers ` vs the old `FindIntegrationAnchors `--> `IntegrateData ` workflow.
In `IntegrateLayers`, this is a wrapper for `FindIntegrationAnchors `--> `IntegrateEmbeddings`, so its returning a dimensional reduction object, leaving the SCT assay unchanged.  
Integrated embeddings are not useable for finding transfer anchors. Must use the old workflow. Correct me if I am wrong

**Comment by hesbornomwandho** [comment]
#How was this solved , i am having same issue here using seurat version 5.1.1

ransfer.anchors <- FindTransferAnchors(
+   reference = TGFB_RNA,
+   query = TGFB_ATAC,
+   reduction = 'cca',
+   normalization.method = "SCT",
+   dims = 1:25
+ )
Error: Given reference assay (SCT) has 2 reference sct models. Please provide a reference assay with a  single reference sct model.

**Comment by KidElectric** [comment]
I was having this issue with similar datasets. The thing that appears to be working for me (in that it runs... have not verified this is "working" in the analytical sense) is specifying the assays very specifically. So specifying SCT assay in the reference and the integrated assay in the spatial query dataset.

`anchors <- FindTransferAnchors(reference = ref,
                                            reference.assay = "SCT", 
                                            query = vis,
                                            query.assay = "integrated",
                                            features = rownames(vis[["integrated"]]),
                                            reduction = "rpca",
                                            normalization.method = "SCT")
  `
I think part of these issues can arise from having the query assay set to SCT which in my hands appears not to work...

**Comment by mmfalco** [comment]
Seurat team now suggests to run the integration with [this](https://github.com/satijalab/seurat/issues/8938#issuecomment-2541548843) approach, which helped me to get rid of the issue.
