### ISSUE TITLE
How to add meta data to an already-integrated seurat object?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6066]
Hello. Is it possible to add new metadata to categorize a group of samples?

I usually use AddMetaData() to add sample identities or groupings to each of the samples/seurat objects, but I don't know how to do it in an integrated object. 

I previously integrated samples 1-10 and already processed a lot. I wonder how to a new column "GROUP" that categorizes sampleS 1-5 as "G1" and samples 6-10 as "G2".

Thank you!

**Comment by andrewwbutler** [comment]
Hi,

Adding metadata to an integrated object works the same as adding to any other Seurat object. You just need a vector (or dataframe) that has the group information for each cell. In your particular example assuming you have the sample as a metadata column called `sample`, you could probably do the following.

```R
object$GROUP <- ifelse(test = object$sample %in% 1:5, yes = "G1", no = "G2")
```

**Comment by levinhein** [comment]
Hi @andrewwbutler! Thank you for your reply!

This works! **How about if I am adding a new meta.data for a new column for every cell type or only one cell type without affecting the others?**

It appears that the yes-no parameter will delete the original value and replace it with the new one every time this is ran even though it is only intended for one cell type. (All cell types categorized as "no" always get changed.)  
 
```
SEURAT$column <- ifelse(test = SEURAT$celltype %in% "B Cells", yes = "3000", no = "0")
SEURAT$column <- ifelse(test = SEURAT$celltype %in% "T Cells", yes = "5000", no = "0")
SEURAT$column <- ifelse(test = SEURAT$celltype %in% "NK Cells", yes = "1000", no = "0")
SEURAT$column <- ifelse(test = SEURAT$celltype %in% "Plasma Cells", yes = "2000", no = "0")
```
Thank you!!!

**Comment by andrewwbutler** [comment]
Yes, you should really only use the `ifelse` approach if you have a two class situation. There are many ways to approach this for multiple classes but one method could be

```R
SEURAT$column <- NA # or any other initialization value
SEURAT$column[SEURAT$celltype == "B Cells"] <- 3000
# ... etc for the rest
```
