### ISSUE TITLE
How to correlate a gene with a gene set expression?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6067]
Hello,

May I ask how to correlate a **gene** like TF with a **gene set/module** expression?

For simple idea/example, I would like to correlate GENE_A expression with gene set signature/module expression (GENE_B, GENE_C, GENE_D, GENE_E)?

Should I just AddModuleScore() for 1 gene and AddModuleScore() for gene set and create a scatterplot? I feel like I'm doing it wrong.

I tried the old issues submitted by others but it seems like it's not the same with what I want, like they to discover the genes that are correlated to the module, while I want to test if a specific gene is correlated with the module.  

Thank you!

**Comment by yuhanH** [comment]
Hi,
you only need to create the module score for the gene set (GENE_B, GENE_C, GENE_D, GENE_E) and then can calculate correlation between two vectors: gene_A expression and module score.
