### ISSUE TITLE
Create split violin plot of WT and mutant mice model. 

### ISSUE THREAD

**Issue by Amin2130538** [satijalab/seurat#6068]
Currently, I am performing integration analysis of WT and mutant mice model using R and would like to create a split violin plot based on the gene expression. 

I mange to create the Violin plot for example like this using this code:
 VlnPlot(combined_seurat, features = c("Thbs1"), split.by = "orig.ident", pt.size = 0.2, ncol = 1,  cols = c ('WT_3'='#C45AEC', 'Homozygous_3'='#6AA121'))

However, I would like to create split violin plot for example like this:
![Screen Shot 2022-06-13 at 17 17 23](https://user-images.githubusercontent.com/96256252/173310331-bf1be77a-f139-4ee9-862a-579c1da7df3c.png)

Please let me know how to I can do that or If there any suggested code. Your suggestions are highly appreciated. Thank you

**Comment by jarchana09** [comment]
Hi. Not a member of the development team, but perhaps this may be helpful.
To enable the single split violin plot when using more recent versions of Seurat, you can set the parameter `split.plot=TRUE` as mentioned in the Seurat Violin plot reference page: [https://satijalab.org/seurat/reference/vlnplot](https://satijalab.org/seurat/reference/vlnplot)
For example, updating your code by setting the split.plot parameter may work:
`VlnPlot(combined_seurat, features = c("Thbs1"), split.by = "orig.ident", pt.size = 0.2, ncol = 1, cols = c ('WT_3'='#C45AEC', 'Homozygous_3'='#6AA121'), split.plot=TRUE)`
Thank you.

**Comment by Amin2130538** [comment]
Thank you very much for your comment  and kind code. It works perfect now. Thank you.... :)
