### ISSUE TITLE
How to integrate CMO data?

### ISSUE THREAD

**Issue by SDJ7007** [satijalab/seurat#6069]
Hello,
Thank you so much for vignettes that explain everything well. 
I have a question to ask, I have CMO data 
How do I integrate these four datasets? 
Like in the example datasets. there is stim and control. 
How can I split my dataset?
Is it possible to split my dataset on the basis of the CMO labelled? 

I have already ran these four datasets individually but I would like to integrate and know what is the difference between them? 

Thank you so much.

Kind Regards,
Shweta Johari

**Comment by mhkowalski** [comment]
Hello, apologies for the delayed response. Yes, it is possible to split your datasets and then integrate them however you would like (it is hard for us to make a specific recommendation without understanding your specific data and experimental design). I would refer you to the integration vignette for more details. If you have a specific question about the integration pipeline, feel free to open another issue, including any relevant code and where you are encountering issues.
