### ISSUE TITLE
Feature Request: Scrublet for doublet prediction within Seurat

### ISSUE THREAD

**Issue by dpcook** [satijalab/seurat#607]
Hi all--the new tool [Scrublet](https://www.biorxiv.org/content/early/2018/07/09/357368?rss=1&utm_source=dlvr.it&utm_medium=twitter) seems like a great method for doublet detection. It's currently only implemented in Python, but a Seurat function that calls it could be a nice addition to the processing pipeline.

**Comment by mschilli87** [comment]
This could go in its own package after https://github.com/satijalab/seurat/issues/586 or something similar is done. :wink:

**Comment by satijalab** [comment]
This could be done without any modifications to Seurat, but would involve an API call to python to classify doublets, and store this information in object@meta.data

This is beyond our bandwidth at the moment, but should not be difficult to program if you or others have some bandwidth to help.
