### ISSUE TITLE
Error with SCTransform (vst.flavor = "v2") when using vst.flavor = "v2" together with batch_var

### ISSUE THREAD

**Issue by shawez** [satijalab/seurat#6072]
Hi!
I'm using Seurat v4.1.1, and got an error when using SCTransform (vst.flavor = "v2") for normalization with batch_var.

The code is:

_allCell <- SCTransform(seuratObject, method = "glmGamPoi", batch_var = "Patient", ncells =ncol(seuratObject@assays$RNA@counts), vst.flavor = "v2")_

**vst.flavor='v2' set, setting model to use fixed slope and exclude poisson genes.
Calculating cell attributes from input UMI matrix: log_umi
Total Step 1 genes: 12670
Total overdispersed genes: 12627
Excluding 43 genes from Step 1 because they are not overdispersed.
Variance stabilizing transformation of count matrix of size 12670 by 276361
Model formula is y ~ (log_umi) : Patient + Patient + 0
Get Negative Binomial regression parameters per gene
Using 2000 genes, 276361 cells
  |                                                                                                                                                           |   0%
Error in fit$Beta[, "Intercept"] : subscript out of bounds**

Code is working without batch_var. 
Should I take additional steps processing the merged data?
Thank you so much for your help!

Best,

Shawez

**Comment by saketkc** [comment]
Use of `batch_var` is currently not supported in `SCTransform()`. I would recommend running `sctransform::vst()` with `batch_var` and then using the pearson residuals for downstream processing. An example is showin in [this vignette](https://htmlpreview.github.io/?https://github.com/satijalab/sctransform/blob/supp_html/supplement/batch_correction.html)

**Comment by shawez** [comment]
Thanks [saketkc](https://github.com/saketkc),
Do you think using SCTransform with vars.to.regress (my batch variable) would also be a viable option?
