### ISSUE TITLE
Preprocessing of scRNA-seq data prior integration with spatial data

### ISSUE THREAD

**Issue by JJBio** [satijalab/seurat#6074]
Dear Seurat team, 

I have a question concerning the integration of scRNA-seq data and spatial data. I am following your [vignette](https://satijalab.org/seurat/articles/spatial_vignette.html). 
I have a large scRNA-seq data set with many subpopulations of cell types annotated. Should I filter rare cell types and merge subpopulations (e.g. M1/M2 macrophages) prior integration? And is there a way to see/check how well the integration works with subpopulations? 

Thank you so much for your help!

**Comment by torkencz** [comment]
Hi,
I would start with higher level annotations first for integration. You are likely not going to detect very rare cell populations as spatial data tends to be lower quality. Afterwards I would look at prediction scores for your annotations, which should give you an idea of the resolution of annotations that you could get to.
