### ISSUE TITLE
Cycling through all clusters running FindConservedMarkers()

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6076]
I'm trying to cycle through all markers in an integrated and processed Seurat object and am getting errors, that I think are because the gene expressions are too low in certain clusters.  My code is:
```
  #**Determine the number of clusters **
  num_clusters <- max(as.numeric(as.character(
    gene.conditions.integrated@meta.data$seurat_clusters)))
  
  #**Cycle through each cluster finding the conserved markers**
  #**Store each dataframe of markers in the misc slot**
  for (i in 0:num_clusters) {
    gene.conditions@misc$temp <- FindConservedMarkers(gene.conditions.integrated,
                                                          ident.1 = i, grouping.var = "genotype")
    names(gene.conditions@misc)[names(gene.conditions@misc)=="temp"] <-
      paste0(names(gene.conditions), ".cluster_", i, ".markers")
  }
```
This is working until I get to cluster 12.  Then I get an error:

Warning: Identity: 12 not present in group KO. Skipping KO
Warning: Identity: 12 not present in group WT. Skipping WT
Error in marker.test[[i]] : subscript out of bounds

After doing some googling it would seem a fix would be to lower min.cells.groups but when I try that, I get an error:

 object 'min.cells.groups' not found

Is there any way to skip a cluster that doesn't have whatever is necessary to run FindConservedMarkers()?  I really would like to do this in a loop and not individually.

Thanks,

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Just to clarify do you have more genotypes than just WT and KO?

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi Stacy,

Can you post the full code that is causing the error when setting `min.cells.groups`? 

Best,
Sam

**Comment by stacygenovese** [comment]
Sure...

```
  #**Determine the number of clusters **
  num_clusters <- max(as.numeric(as.character(
    gene.conditions.integrated@meta.data$seurat_clusters)))
  
  #**Cycle through each cluster finding the conserved markers**
  #**Store each dataframe of markers in the misc slot**
  for (i in 0:num_clusters) {
    gene.conditions@misc$temp <- FindConservedMarkers(gene.conditions.integrated,
                                                          ident.1 = i, grouping.var = "genotype", min.cells.group = 0)
    names(gene.conditions@misc)[names(gene.conditions@misc)=="temp"] <-
      paste0(names(gene.conditions), ".cluster_", i, ".markers")
  }
```

**Comment by damouzo** [comment]
Hi Stacy,

I ran into your same problem today using `FindConservedMarkers()`. It is a good tool but it seems that it has a problem working with those groups/clusters that have very few cells. For example, if there is a cluster "15" that has 0 cells, the function will skip that cluster with a warning (that's perfect). On the other hand, if the number of cells is between `min.cells.groups` (default = 3) and 0, an error is thrown and it stops working. That is why I recommend you to previously remove from the Seurat Object the cells of the clusters with 3 or less cells for each condition/sample. Something like:


```
few_cells_samples <- unique(integrated_seurat@meta.data$orig.ident)
few_cells <- vector()

for (i in 1:length(few_cells_samples)) {   # remove cellstype w/ less than 3 cells in each sample/condition
    few_cells_tmp <- table(integrated_seurat@meta.data$seurat_clusters[integrated_seurat@meta.data$orig.ident == few_cells_samples[i]]) <= 3
    few_cells_tmp <- names(few_cells_tmp)[few_cells_tmp == "TRUE"]
    few_cells <- c(few_cells,few_cells_tmp)
}

clusters <- sort(unique(integrated_seurat@meta.data$seurat_clusters))
clusters <- clusters[clusters %!in% few_cells]

```

I hope you find it useful
Best,
Dani

**Comment by andrewdchen** [comment]
> Sure...
> 
> ```
>   #**Determine the number of clusters **
>   num_clusters <- max(as.numeric(as.character(
>     gene.conditions.integrated@meta.data$seurat_clusters)))
>   
>   #**Cycle through each cluster finding the conserved markers**
>   #**Store each dataframe of markers in the misc slot**
>   for (i in 0:num_clusters) {
>     gene.conditions@misc$temp <- FindConservedMarkers(gene.conditions.integrated,
>                                                           ident.1 = i, grouping.var = "genotype", min.cells.group = 0)
>     names(gene.conditions@misc)[names(gene.conditions@misc)=="temp"] <-
>       paste0(names(gene.conditions), ".cluster_", i, ".markers")
>   }
> ```
> 
> Or do you mean my whole script? It's 800 lines long and don't think I can share that whole thing. It's OK...I found a work around

@stacygenovese Just wondering, what's the work around you found? I'm trying to do something similar - apply FindConservedMarkers to each cluster in a parallel `foreach` loop.
