### ISSUE TITLE
Violin Plot change order Homozygous  and WT to WT and Homozygous

### ISSUE THREAD

**Issue by Amin2130538** [satijalab/seurat#6078]
I need a suggestion from you to create a violin plot in R for integrated scRNA-seq data. 
When I create a violin plot it shows "Homozygous 5" first and "Wild Type 5" second. But, I would like to plot "Wild Type 5" first and "Homozygous 5" second. I used that code but it is not working. 

VlnPlot(combined_seurat, features = c("Cnn1"), [split.by](http://split.by/) = "orig.ident", pt.size = 0, cols = c('Wild Type 5' = 'red', 'Homozygous 5' = 'green'),  split.plot = TRUE)

<img width="1001" alt="Screen Shot 2022-06-15 at 16 53 30" src="https://user-images.githubusercontent.com/96256252/173782325-8489de51-381b-4517-b13d-ef0666e0c8f9.png">

Please let me know if you have any suggestion code or guidance. Your opinions are highly appreciated. Thank you...

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This is issue only with the old visualization style for split violins.  See response from dev team here:
https://github.com/satijalab/seurat/issues/3007#issuecomment-629310216

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi Amin,

My mistake.  All that you need to do is change the factor levels for your meta data category.  See here for example: https://github.com/satijalab/seurat/issues/5930#issuecomment-1121134929. 

Best,
Sam
