### ISSUE TITLE
pct values - how are the genes assigned as detected?

### ISSUE THREAD

**Issue by heidhel** [satijalab/seurat#6079]
Hi!

I am having a hard time getting a grip of the pct.1 and pct.2 values. This is how they are described in the documentation:

- pct.1: The percentage of cells where the gene is detected in the first group

- pct.2: The percentage of cells where the gene is detected in the second group

I would need to know how a gene is assigned as detected and what amount of expression is enough.

From the references I learned that some expression thresholds are counted. Does it come straight from that?
(McDavid A, Finak G, Chattopadyay PK, et al. Data exploration, quality control and testing in single-cell qPCR-based gene expression experiments. Bioinformatics. 2013;29(4):461-467. doi:10.1093/bioinformatics/bts714)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The percent expression is calculated as cells with any level of expression of a feature.  It simply uses all non-zero cells vs total cells to calculate the value.  

https://github.com/satijalab/seurat/blob/f1b2593ea72f2e6d6b16470dc7b9e9b645179923/R/differential_expression.R#L1033-L1038

If you are interested in calculating values using a certain threshold you can modify that code above for what ever cells that you need (note that in code above the `object` is not Seurat object but data matrix from Seurat object.  e.g., 
```
object <-  GetAssayData(object = SEU_OBJ_NAME, slot = "data")

cells.1 <- WhichCells(object = SEU_OBJ_NAME, idents = "IDENT_NAME")

cells.2 <- WhichCells(object = SEU_OBJ_NAME, idents = "IDENT_NAME", invert = TRUE)

thresh.min <- DESIRED_THRESHOLD

pct.1 <- round( 
   x = Matrix::rowSums(x = object[features, cells.1, drop = FALSE] > thresh.min) / 
     length(x = cells.1), 
   digits = 3 
 ) 

pct.2 <- round( 
   x = Matrix::rowSums(x = object[features, cells.2, drop = FALSE] > thresh.min) / 
     length(x = cells.2), 
   digits = 3 
 ) 
```

You can also use function from my scCustomize package [Percent_Expressing](https://samuel-marsh.github.io/scCustomize/articles/Statistics.html#percent-of-cells-expressing-features)

```
library(scCustomize)

percent_express <- Percent_Expressing(seurat_object = pbmc, features = c("CD4", "CD8A"))
```

Best,
Sam

**Comment by yuhanH** [comment]
Thanks @samuel-marsh  for your nice explanation!
