### ISSUE TITLE
Meta data label transfer not working for one data set following integration

### ISSUE THREAD

**Issue by vleifer685** [satijalab/seurat#6082]
After adding celltype labels to my original dataset (let's say "obj_A"), and confirming that they are present in the metadata, I integrated my dataset with another dataset (let's say "obj_B"), which also has celltype labels stored in the metadata. 

--> I've confirmed that the labels are present in obj_A in a number of ways, for example, manually via: View(obj_A@metadata); and also via table(obj_A$celltype).

However, no matter what I do, the celltype labels for obj_A disappear from the integrated object's (let's say obj_AB) metadata. For example, when I plot DimPlot(obj_AB, reduction = 'umap', group.by = "celltype"), only the clusters from obj_B appear labeled correctly via the celltype metadata. Meanwhile, the clusters originally from obj_A are only labeled as "0", "1", "2," etc., and there appears to be one fewer cluster (n=5) than there was in obj_A (n=6).

This problem does not occur with another parameter, "orig.ident." Here, the original identity from each dataset is preserved, so I am able to do DimPlot(obj_AB, reduction='umap', split.by="orig.ident") successfully, to have two separate plots.

Finally, when I integrate obj_A with a second data set (obj_C) to form integrated object "obj_AC", which does not have celltype information stored in its metadata, the obj_A celltype labels do not disappear, and I am able to see the labels on the UMAP plots.

**Comment by yuhanH** [comment]
hi 
what data type of celltype in `obj_A` and `obj_B`? Are the character or factor?
If they are factors with different levels, it may lead this error. 
You can first convert celltype in obj_A and obj_B to character first. 
```
obj_A$celltype <- as.character(obj_A$celltype )
obj_B$celltype <- as.character(obj_B$celltype )
```

**Comment by yuhanH** [comment]
Since we haven’t heard from you, we will close this issue first. If you still have this issue, we can reopen it.
