### ISSUE TITLE
Summarizing the number of DEGs per cluster into a table or in a new column of seurat object?  

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6084]
Hello, 

Is there a way to summarize the number of DEGs for all clusters in a Seurat object by doing FindAllMarkers()  and then summarizing the DEG numbers per cluster into a table?

I'm attempting to plot the summary of DEG numbers by modifying into something like this:

```
PLOT <- ggplot(TC.combined_labeled, aes(seurat_clusters, nFeature_RNA, fill = seurat_clusters)) +    geom_bar(stat = "identity")
```

![image](https://user-images.githubusercontent.com/68268222/174101688-d29ccffa-3256-4db9-a580-0a96d851515d.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  You don't necessarily need to actually make a new table you can simply use the data.frame output by `FindAllMarkers`.

```
pbmc <- pbmc3k.SeuratData::pbmc3k.final

markers <- FindAllMarkers(object = pbmc)

ggplot(data = markers) +
  stat_count(mapping = aes(x = cluster, fill = cluster)) +
  xlab("Seurat Cluster") +
  ylab("DEG Count") +
  labs(fill = "Seurat Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # Added this just to make plot legible in smaller size for posting here.

```
![image](https://user-images.githubusercontent.com/38284410/174106509-431529b8-0add-4517-bc3b-c24216616e13.png)

If you still simply want a data.frame with the count values you can run the following:
```
pbmc <- pbmc3k.SeuratData::pbmc3k.final

markers <- FindAllMarkers(object = pbmc)

total_DEG <- data.frame(table(markers$cluster))

colnames(total_DEG) <-c("Seurat_Clusters", "DEG_Count")
```

I will add though that there are two issues with this visualization as you describe.  First, is that it does not take into account any individual level variation in the data and whether one or more samples are driving the majority of the effects observed.  The second is the normal issue with doing cluster vs. cluster DEG (see here: https://github.com/satijalab/seurat/discussions/5528#discussioncomment-2016188 for some more detail).

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi,

So using above it is simply the total genes with now reference to up or downregulated.

First to sort by number of DEG the easiest is probably using additional function from forcats package:
```
ggplot(data = markers) +
  stat_count(mapping = aes(x = forcats::fct_infreq(cluster), fill = cluster)) +
  xlab("Seurat Cluster") +
  ylab("DEG Count") +
  labs(fill = "Seurat Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Now in terms of sorting there are many ways to do the up vs down check.
Easiest in my opinion is just to subset the dataframe before plotting (or during plotting if you don't want to create the extra data.frame).
_Note you may want to do this anyways to filter for DEGs of certain fold change or p value.  This can be done in the `FindAllMarkers` call by specifying parameter values different from defaults or posthoc with simple filtering._

```
markers_down <- markers %>% 
  filter(avg_log2FC < 0)

ggplot(data = markers_down) +
  stat_count(mapping = aes(x = forcats::fct_infreq(cluster), fill = cluster)) +
  xlab("Seurat Cluster") +
  ylab("Downregulated DEG Count") +
  labs(fill = "Seurat Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# OR

ggplot(data = subset(markers, subset = avg_log2FC < 0)) +
  stat_count(mapping = aes(x = forcats::fct_infreq(cluster), fill = cluster)) +
  xlab("Seurat Cluster") +
  ylab("Downregulated DEG Count") +
  labs(fill = "Seurat Cluster") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

![image](https://user-images.githubusercontent.com/38284410/174126613-d6cece05-c870-4132-b3a6-8536dcdc3cdb.png)


You can also plot them both at the same time if you want by modifying original dataframe and then changing `fill` to reflect that new column.
```
markers$direction <- ifelse(markers2$avg_log2FC > 0, 'Positive', 'Negative')

ggplot(data = markers) +
  stat_count(mapping = aes(x = forcats::fct_infreq(cluster), fill = direction)) +
  xlab("Seurat Cluster") +
  ylab("Total DEG Count") +
  labs(fill = "Upreg vs. Downreg") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

![image](https://user-images.githubusercontent.com/38284410/174127222-2477abf3-053c-4ccf-a36d-b5af85bf798b.png)

Best,
Sam

**Comment by levinhein** [comment]
You're amazing, Sam!!! You're the best!!!! Thank you so much!!!!!!!!! :)))))))))))))

**Comment by samuel-marsh** [comment]
Happy to help!
