### ISSUE TITLE
RPCA changes raw count

### ISSUE THREAD

**Issue by Huimin721** [satijalab/seurat#6085]
Dear Team,

I performed a data integration with RPCA algorithm, then extract the raw count with Seurat.object@assays@RNA@count, however, I found the count data is slightly different from the count data I read with Read10X_h5. May I ask, does RPCA change the expression data? Thanks so much!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you please provide full code that you are running for the analysis and the code you are using to compare the counts values?

Best,
Sam

**Comment by samuel-marsh** [comment]
Can you post the code and output of the comparison are you running that states that counts after are different?

**Comment by Huimin721** [comment]
> Can you post the code and output of the comparison are you running that states that counts after are different?

Hi Sam,

Thank you. There are a lot of differences between the 2 count matrices. I subset the raw count with the genes and cells appear in the count matrix after integration:
> dim(countdt)
[1] 23597 59446
> dim(rawcountdt)
[1] 23597 59446
> diff = rawcountdt-countdt
> sum(colSums(diff) !=0 )
[1] 28432
> identical(countdt['ZNF669',],rawcountdt['ZNF669',])
[1] FALSE


I also visualize the count matrices density by cell or by gene, the density patterns are the same. So I assume RPCA may do  a little data trimming for the raw count?

**Comment by Huimin721** [comment]
> Can you post the code and output of the comparison are you running that states that counts after are different?

Here are some more exploration:
> (countdt['ZNF669',] - rawcountdt['ZNF669',])[(countdt['ZNF669',] - rawcountdt['ZNF669',])!=0]
ATCGGATAGCGATGGT-1 
                         -1 
> (countdt[,'ATCGGATAGCGATGGT-1'] - rawcountdt[,'ATCGGATAGCGATGGT-1'])[(countdt[,'ATCGGATAGCGATGGT-1'] - rawcountdt[,'ATCGGATAGCGATGGT-1']) !=0]
    ZNF669     ELMOD3   METTL21A       SHQ1      ABCF3      HCG25     ZNF318      BLVRA      SMKR1 
        -1         -1         -1         -1         -1         -1         -1         -1         -1 
     DEAF1     PRKAB1      MLXIP       PCK2     HEATR3      GNAO1     ZNF624      CEP85   SOS1-IT1 
        -1         -1         -1         -1         -1         -1         -1         -1         -1 
     CRYGS       GRK4      ADCK5 AL590705.1      NOXA1 AL450384.2 AL392046.1     TRIM66   TMEM229B 
        -1         -1         -1         -1         -1         -1         -1         -1         -1 
AC018557.1  C17orf107 AC007448.5 AC005332.1 AC005523.2      PROCR AC245140.2  ACBD3-AS1 
        -1         -1         -1         -1         -1         -1         -1         -1

**Comment by yuhanH** [comment]
Hi, @Huimin721 
I cannot reproduce this issue by `ifnb`. The code is at below.
I get `TRUE` from `all(ifnb[['RNA']]@counts  == immune.combined[['RNA']]@counts )`
Could you try to show me a reproducible example? Thanks. 

```

library(Seurat)
library(SeuratData)
data("ifnb")

# load dataset
LoadData("ifnb")

# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(ifnb, split.by = "stim")

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
   x <- NormalizeData(x)
   x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration run PCA on each
# dataset using these features
features <- SelectIntegrationFeatures(object.list = ifnb.list)
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
   x <- ScaleData(x, features = features, verbose = FALSE)
   x <- RunPCA(x, features = features, verbose = FALSE)
})

immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features, reduction = "rpca")
# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)

all(ifnb[['RNA']]@counts  == immune.combined[['RNA']]@counts )

```

**Comment by Huimin721** [comment]
@yuhanH @samuel-marsh 
Hi everyone,

Thanks so much for your exploration. I find the issue is reproducible for other data. 
I downloaded some raw human brain ST data from:
**https://github.com/LieberInstitute/HumanPilot
I used h5 files for 151507,151508,151509,151510.**

library(Seurat) 
library(dplyr)
library(ggplot2)


#load data
sample_list = list(c(151507:151510),c(151669:151672),c(151673:151676))

getNamedSeuart = function(name_one){
  counts = Read10X_h5(
    paste(paste('HumanPilot-master/10X',name_one,sep='/'),paste(name_one,"filtered_feature_bc_matrix.h5",sep = '_'),sep='/')
  )
  colnames(counts) = paste(name_one,colnames(counts),sep = ':')
  seurat_object = CreateSeuratObject(counts, min.cells = 3, min.features = 200)
  return(seurat_object)
}


sample_list = sample_list[[1]]
dt = lapply(sample_list, function(x) getNamedSeuart(x))


#normalize and find variable features

dt <- lapply(X = dt, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

#select integration features
features <- SelectIntegrationFeatures(object.list = dt)

dt <- lapply(X = dt, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

#perform integration
dt.anchors <- FindIntegrationAnchors(object.list = dt, 
                                     anchor.features = features, reduction = "rpca")
dt.combined <- IntegrateData(anchorset = dt.anchors)
DefaultAssay(dt.combined) <- "integrated"

dt.combined <- ScaleData(dt.combined, verbose = FALSE)
dt.combined <- RunPCA(dt.combined, npcs = 30, verbose = FALSE)
dt.combined <- RunUMAP(dt.combined, reduction = "pca", dims = 1:30)
dt.combined <- FindNeighbors(dt.combined, reduction = "pca", dims = 1:30)
dt.combined <- FindClusters(dt.combined, resolution = 0.5)

seuratcount = dt.combined[['RNA']]@counts


realcount = lapply(sample_list, function(x) {
  counts = Read10X_h5(
    paste(paste('HumanPilot-master/10X',x,sep='/'),paste(x,"filtered_feature_bc_matrix.h5",sep = '_'),sep='/')
  )
  colnames(counts) = paste(x,colnames(counts),sep = ':')
  counts
})
realcount = do.call('cbind',realcount)
dim(realcount)
realcount = realcount[rownames(seuratcount),colnames(seuratcount)]
identical(realcount,seuratcount)



**Still returns FALSE.**
> dim(realcount)
[1] 33538 18033
> dim(seuratcount)
[1] 19855 18006
> realcount = realcount(rownames(seuratcount),colnames(seuratcount))
Error in realcount(rownames(seuratcount), colnames(seuratcount)) : 
  could not find function "realcount"
> realcount = realcount[(rownames(seuratcount),colnames(seuratcount)]
Error: unexpected ',' in "realcount = realcount[(rownames(seuratcount),"
> realcount = realcount[rownames(seuratcount),colnames(seuratcount)]
> identical(realcount,seuratcount)
[1] FALSE

**Comment by samuel-marsh** [comment]
Hi @Huimin721

So the issue you seem to be describing in this last post is not about the raw counts changing RPCA (or any analysis) but the `OBJECT[['RNA']]@counts` being different from raw matrix file before object creation.  This is to be expected when you include the following code in your object creation (taken from last post):
```
seurat_object = CreateSeuratObject(counts, min.cells = 3, min.features = 200)
```

By setting min.cells to 3 any genes expressed in 2 cells or less are removed.  Therefore features dim goes from 33538 (all features) to 19855 (features with non-zero counts in 3 or more cells.  By setting min.features = 200 you eliminate any cells with less than 200 unique features expressed.  Therefore the cells dim foes from 18033 (all cells called by cell ranger) to 18006 (all cells with 200 or greater unique features). 

If you want to include everything you can set those parameters to zero.  However, these are often used as baseline filtering to remove very low quality cells (less than XXX unique features) and genes that are extremely lowly expressed (across cells; less than XX cells expressing gene).  

As @yuhanH described in his answer when you take the `OBJECT[['RNA']]@counts` after object creation but before analysis and then again after analysis you will find they are the same.

Best,
Sam

**Comment by Huimin721** [comment]
> Hi @Huimin721
> 
> So the issue you seem to be describing in this last post is not about the raw counts changing RPCA (or any analysis) but the `OBJECT[['RNA']]@counts` being different from raw matrix file before object creation. This is to be expected when you include the following code in your object creation (taken from last post):
> 
> ```
> seurat_object = CreateSeuratObject(counts, min.cells = 3, min.features = 200)
> ```
> 
> By setting min.cells to 3 any genes expressed in 2 cells or less are removed. Therefore features dim goes from 33538 (all features) to 19855 (features with non-zero counts in 3 or more cells. By setting min.features = 200 you eliminate any cells with less than 200 unique features expressed. Therefore the cells dim foes from 18033 (all cells called by cell ranger) to 18006 (all cells with 200 or greater unique features).
> 
> If you want to include everything you can set those parameters to zero. However, these are often used as baseline filtering to remove very low quality cells (less than XXX unique features) and genes that are extremely lowly expressed (across cells; less than XX cells expressing gene).
> 
> As @yuhanH described in his answer when you take the `OBJECT[['RNA']]@counts` after object creation but before analysis and then again after analysis you will find they are the same.
> 
> Best, Sam

Hi Sam, 
Thanks so much. I understand some genes and cells will be excluded because of the filtering. However, I have taken that into consideration, I do:
realcount = realcount[rownames(seuratcount),colnames(seuratcount)]
I was comparing the exact same genes from the exact same cells, but they are still different. Could you please comment on this? Thanks so much.

**Comment by samuel-marsh** [comment]
Hi @Huimin721,

So I think what you are describing is still object creation issue.  I didn't see 10X files in repo you posted so I just used one of mine from GEO.  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE188441


Here is example demonstrating that RPCA does not alter raw counts:
```
mat_list <- Read10X_GEO(data_dir = "~/Downloads/GSE188441_RAW/")

dt = lapply(mat_list, function(x) getNamedSeuart(x))

dt <- lapply(X = dt, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

#select integration features
features <- SelectIntegrationFeatures(object.list = dt)

dt <- lapply(X = dt, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

#perform integration
dt.anchors <- FindIntegrationAnchors(object.list = dt,
                                     anchor.features = features, reduction = "rpca")

post_rpca_mat1 <- dt[[1]]@assays$RNA@counts

raw_mat1 <- as.sparse(mat_list[[1]])

raw_mat1 = raw_mat1[rownames(post_rpca_mat1),colnames(post_rpca_mat1)]

identical(raw_mat1, post_rpca_mat1)

[1] TRUE
```

What I believe is happening is that when you are creating your object list you are filtering each object individually and that is just causing some differences.   Here is example showing what happens if you merge matrix and then create Seurat object prior to creating the object and then split it apart for the integration workflow:

```
# Read in and merge data
mat_list <- Read10X_GEO(data_dir = "~/Downloads/GSE188441_RAW/")

mat_merged <- Merge_Sparse_Data_All(matrix_list = mat_list, add_cell_ids = names(mat_list))

# Create single object
pre_split_seurat <- CreateSeuratObject(counts = mat_merged, min.cells = 3, min.features = 200, names.field = 1, names.delim = "_")

# split object
split_seurat <- SplitObject(object = pre_split_seurat, split.by = "orig.ident")

# extract counts from single object
pre_merged_object_counts <- pre_merge_seurat@assays$RNA@counts

# filter merged raw matrix by cells and genes
mat_merged_raw = mat_merged[rownames(pre_merged_object_counts),colnames(pre_merged_object_counts)]

# Identical
identical(pre_merged_object_counts, mat_merged_raw)
[1] TRUE

# Now run integration workflow
dt <- lapply(X = split_seurat, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

#select integration features
features <- SelectIntegrationFeatures(object.list = dt)

dt <- lapply(X = dt, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

#perform integration
dt.anchors <- FindIntegrationAnchors(object.list = dt,
                                     anchor.features = features, reduction = "rpca")

dt.combined <- IntegrateData(anchorset = dt.anchors)

# pull raw counts
mat_integrated <- dt.combined@assays$RNA@counts

# Check identical to unsplit seurat object at beginning
identical(pre_merged_object_counts, mat_integrated)
[1] TRUE

# Check identical to raw matrix at beginning
identical(mat_integrated, mat_merged_raw)
[1] TRUE
```

So the data isn't actually changing but due to how you filter each object individually and then merge and then filter the original matrix it makes it look like data has changed.

Best,
Sam

**Comment by Huimin721** [comment]
Hi Sam, @samuel-marsh 

Thanks so much. I think we are closer. Yes, I think the individual filtering will make each single Seurat object contains different genes. For example, if object A contains 'CD3D' but object B does not contains 'CD3D', in the final integrated Seurat object, how does Seurat deal with CD3D expression in cells from object B?

**Comment by samuel-marsh** [comment]
Hi @Huimin721 

I'll leave that to @yuhanH or another member of the Seurat team in terms of analysis methods behind integration.

Best,
Sam

**Comment by yuhanH** [comment]
Thank you  @samuel-marsh for this whole debugging process!
Hi @Huimin721  integration process itself will not change the count and data matrices in the original assay. Some filter steps in the preprocess may affect it. 
In the case that object A includes 'CD3D' and object B does not, after merging the two objects (no integration), all corresponding cells for 'CD3D' in object B will be filled up with zeros.
