### ISSUE TITLE
Normalization and Ordering of Cell Cycle Regression, DoubletFinder, and Integration

### ISSUE THREAD

**Issue by adri-biochem** [satijalab/seurat#6087]
Hello, I apologize if this question has been asked before, or if this is not the place to ask it. I am running an experiment on a group of epithelial cells. I only have 4 clusters of different cell types, but only 1 main cell type is being looked at, so it is a fairly low complexity dataset. I also only have 2 samples that I would like to integrate later. I am fairly new to running ScRNA Seq, so I am a bit confused on the ordering of everything, and I was wondering if anyone could help me out. I have 2 pipelines I'm running and I am wondering if my ordering for any of them is correct/incorrect, or if I should add/take away any more steps. I looked at previous questions similar to this, but none that used vignettes with both cell cycle scoring and DoubletFinder that I could find ([#1679](https://github.com/satijalab/seurat/issues/1679), [#3665](https://github.com/satijalab/seurat/issues/3665)). Please link me to them if this has been asked already.

First, I am looking to compare SCTransform to LogNormalize and seeing if this impacts cell cycle scoring and doublet rate, as well as any final results from the UMAP. The pipelines I have for these are as follows, and I have my questions at each step:

Pipeline 1: LogNormalize
1) QC/Filtering
2)  LogNormalize 
3) Run Cell Cycle Scoring
4) FindVariableFeatures, ScaleData (should I regress out cell cycle here or do it later when I integrate)?
5) RunPCA, ElbowPlot
6) FindNeighbors, FindClusters, RunUMAP (I do not specify resolution here, should I?)
7) Run DoubletFinder on each sample individually
    - PROBLEM: when I run doublet finder using this pipeline my pK value is extremely small (0.005), is this okay?
8) Subset out doublets and re-merge object
9) This is where I'm stuck, **should I run LogNormalize again?**. Given how it works, I do not think it is necessary to re-run LogNormalize, but I am not sure.
10) Run integration (SelectIntegrationFeatures --> FindIntegrationAnchors --> Integrate Data)
11) ScaleData and regressed out cell cycle here (does it matter where I regress out cell cycle? Should I do this before I run DoubletFinder?)
12) RunPCA and ElbowPlot
13) FindNeighbors, FindClusters, RunUMAP (specify resolution here?)
14) Identify cell populations that are not of interest and subset out those clusters
15) Rerun FindNeighbors, FindClusters, RunUMAP (specified resolution here only, is that okay?)
16) Get final UMAP

Pipeline 2: SCTransform
1) QC/Filtering
2) SCTransform (SCTransform does not regress anything out yet)
3) Run Cell Cycle Scoring
4) Should I re-run SCTransform here with regressed out cell cycle scores, or should I do it after DoubletFinder?
5) RunPCA, ElbowPlot
6) FindNeighbors, FindClusters, RunUMAP (did not specify resolution here)
7) Run DoubletFinder on each sample individually, subset out doublets and re-merge object
8) Should I re-run SCTransform here again after DoubletFinder to regress out cell cycle or do it at step 4?
9) Run Integration (SelectIntegrationFeatures --> PrepSCTIntegration --> FindIntegrationAnchors --> Integrate Data)
10) Run PCA and ElbowPlot
11) FindNeighbors, FindClusters, RunUMAP 
12) Subset out unwanted clusters
13) Rerun FindNeighbors, FindClusters, RunUMAP (specified resolution here only, is that okay?)
14) Get Final UMAP

I guess my overarching questions are: what would you change in these pipelines? Does the ordering of everything make sense? Where should I re-normalize: after cell cycle or after doublet finder/before integration or does it not matter?

Thank you!

**Comment by adri-biochem** [comment]
As an Update I did see on the DoubletFinder Site that Cell Cycle scoring should not be regressed out until after DoubletFinder is ran ([#124](https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/124)). However if anyone can still check my workflow I'd be very grateful.

**Comment by torkencz** [comment]
Hi you should definitely not regress anything out before running DoubletFinder. I would post any further question relating to that to the developers. You do not need to rerun normalization after sub-setting an object because that is done on a per cell basis. The workflows you presented above makes sense. Alternatively, you ensure that cc genes are included in integration. Afterwards, you can calculate cell cycle scores based on the integrated dataset, and regress these out using ScaleData (after integration).
