### ISSUE TITLE
using harmony on multiome data

### ISSUE THREAD

**Issue by afcmalone** [satijalab/seurat#6089]
Hi,
I have followed the tutorial on 'https://satijalab.org/signac/articles/pbmc_multiomic.html' exactly for my 10X multiome data.
The multiome data is from 4 different samples. I generated Cellranger output using the 'aggregate' function to include all 4 of these samples. i.e. one Cellranger output for 4 samples.
I followed the pipeline on 'https://satijalab.org/signac/articles/pbmc_multiomic.html'  but there is now batch effect.
I am wondering how to remove this batch effect?
I tried to apply harmony to the batch variable but not sure how to do this correctly.
Do i perform harmony on both 'RNA' and 'peaks' assay? what 'graph.name' do i then use to cluster etc.
Thank you in advance

**Comment by yuhanH** [comment]
Hi @afcmalone 
You can follow this [harmony vignette](https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/harmony.html) to get rid of batch effects in pca (RNA) and lsi (ATAC) respectively. 
Then you can perform WNN to perform multiomdal clustering.

**Comment by afcmalone** [comment]
Thank you for your quick response

Here is the code i used. visually it looks better.
Is there any steps here that are incorrect?

library(harmony)
DefaultAssay(pbmc) <- "peaks"
pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'orig.ident2',
  reduction = 'lsi',
  assay.use = 'peaks',
  project.dim = FALSE,
  reduction.save = "harmony_p"
)
pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'orig.ident2',
  reduction = 'pca',
  assay.use = 'RNA',
  project.dim = FALSE,
  reduction.save = "harmony_r"
)
#Joint UMAP visualization
# build a joint neighbor graph using both assays - WNN
pbmc <- FindMultiModalNeighbors(
  object = pbmc,
  reduction.list = list("harmony_r", "harmony_p"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)
# build a joint UMAP visualization
pbmc <- RunUMAP(
  object = pbmc,
  nn.name = "weighted.nn",
  reduction.name = "wnn.umap",
  assay = "RNA",
  verbose = TRUE
)
pbmc <- FindNeighbors(pbmc) 
pbmc <- FindClusters(pbmc, graph.name = 'wsnn')
DimPlot(pbmc,reduction = "wnn.umap",  group.by = 'orig.ident2') 

Thank you for your help!
