### ISSUE TITLE
How to choose a reasonable number of CCs after RunMultiCCA

### ISSUE THREAD

**Issue by dnarna909** [satijalab/seurat#609]
Here is what I got:

immune.combined <- RunMultiCCA(object.list = pbmc.list, genes.use = genes.use, num.ccs = 30)
MetageneBicorPlot(immune.combined, grouping.var = "group", dims.eval = 1:30, display.progress = FALSE)
![plot3](https://user-images.githubusercontent.com/39634511/42582343-777095c4-84f4-11e8-9053-518d972e1a25.jpg)

The drop-off in signal is after CC15, but increase after CC20. Do I chose CC1-15 or CC1-20 for analysis. Thanks

**Comment by satijalab** [comment]
We have seen similar plots for some datasets, and this is indeed challenging for selection of CCs. Unlike with PCA, these curves are not guaranteed to be monotonically decreasing.

We are working on more advanced methods for this problem. In the meantime, we encourage you to explore the sensitivity of your downstream results to this parameter choice. In the manuscript, we did not see significant changes in the results +/- 5 CCs. Hopefully you observe similar results, but if not, you may have to use more manual approaches to estimate the dimensionality of your dataset.
