### ISSUE TITLE
Finding variable genes using SCTransform

### ISSUE THREAD

**Issue by navtronius** [satijalab/seurat#6093]
Hi, I have used FindVariableGenes in the past to find variable genes on my scRNA-seq datasets, however with the advent of SCTransform, I had one question.

How does one find the highest n variable genes using SCTransform? This was straightforward to do using FindVariableGenes, but I am clearly missing something obvious to be able to do something similar using SCtransform... I have 24,000 genes after SCTransform which is a lot more than I would like for downstream analysis. Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You have 24,000 variable genes or total genes?  What is the result of:
`length(VariableFeatures(object = OBJECT))`?

Best,
Sam

**Comment by saketkc** [comment]
`SCTransform()` does its own variable feature selection based on residual variance. By default, it selects 3000 features which you can control with `variable.features.n` parameter. See [documentation](https://satijalab.org/seurat/reference/sctransform)  for details.
