### ISSUE TITLE
Using Harmony on multiome data#6089

### ISSUE THREAD

**Issue by afcmalone** [satijalab/seurat#6094]
Thank you for your quick response

Here is the code i used. visually it looks better.
Is there any steps here that are incorrect?

library(harmony)
DefaultAssay(pbmc) <- "peaks"
pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'orig.ident2',
  reduction = 'lsi',
  assay.use = 'peaks',
  project.dim = FALSE,
  reduction.save = "harmony_p"
)
pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'orig.ident2',
  reduction = 'pca',
  assay.use = 'RNA',
  project.dim = FALSE,
  reduction.save = "harmony_r"
)
#Joint UMAP visualization
# build a joint neighbor graph using both assays - WNN
pbmc <- FindMultiModalNeighbors(
  object = pbmc,
  reduction.list = list("harmony_r", "harmony_p"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)
# build a joint UMAP visualization
pbmc <- RunUMAP(
  object = pbmc,
  nn.name = "weighted.nn",
  reduction.name = "wnn.umap",
  assay = "RNA",
  verbose = TRUE
)
pbmc <- FindNeighbors(pbmc) 
pbmc <- FindClusters(pbmc, graph.name = 'wsnn')
DimPlot(pbmc,reduction = "wnn.umap",  group.by = 'orig.ident2') 

Thank you for your help!

_Originally posted by @afcmalone in https://github.com/satijalab/seurat/issues/6089#issuecomment-1159515838_

**Comment by timoast** [comment]
Looks good to me
