### ISSUE TITLE
Blending gene expression in SpatialFeaturePlot

### ISSUE THREAD

**Issue by jad362** [satijalab/seurat#6095]
Hello-

I am trying to plot multiple genes using `SpatialFeaturePlot` and was wondering if there was a blend option like there is for normal `FeaturePlot`? Plotting the co-expression of say a ligand and its receptor on a Visium slide would be incredibly interesting if possible. Is this something that is in the works?

Thanks!
Joe

**Comment by mojaveazure** [comment]
Hi Joe, we don't have support for blended spatial plots, but if you use the new [spatial framework](https://satijalab.org/seurat/articles/spatial_vignette_2.html), you can use `ImageFeaturePlot`, which supports blending, but does not support backing tissue stains

**Comment by ahm1072019** [comment]
Hi, I wanted to check if ImageFeaturePlot was available for 10x Vissium platform now as I see it was just used for Nanostring, Akoya, and Vizgen

**Comment by parkjooyoung99** [comment]
is imagefeatureplot available for 10x visium data??

**Comment by george-hall-ucl** [comment]
Hi all,

I have written a function that implements blended SpatialFeaturePlots. It's a bit hacky - it's actually a SpatialDimPlot with the blended colour specified for each point. But it does the job!

It should be straightforward to use: you just pass it the Seurat object and the names of the two metadata columns that you want to plot.  You can set `combine = FALSE` if you want to return each element of the plot separately.

Here is the function, I've included an example below.

```R
SpatialFeaturePlotBlend <- function(cells_obj, column_1, column_2,
                                    combine = TRUE)  {

    # Convert decimal number to hexadecimal. Pad with 0s if only a single
    # character following conversion.
    as_hex <- function(num) {
        hex_str <- as.character(as.hexmode(num))
        if (nchar(hex_str) == 1) {
            hex_str <- paste0("0", hex_str)
        }

        return(hex_str)
    }

    metadata_to_hexadecimal <- function(in_dat) {
        apply(in_dat, 2,
              function(x) {
                  # Make minimum 0
                  x - min(x)
              }) %>%
        apply(2,
              function(x) {
                  # Constrain to range [0, 255]
                  round(255 * (x / max(x)))
              }) %>%
        apply(1,
              function(x) {
                  # Convert to hexadecimal codes
                  toupper(paste0("#", as_hex(x[1]), as_hex(x[2]), "00"))
              })
    }

    blend_plot_theme <- theme(legend.position = "none",
                              plot.title = element_text(hjust = 0.5))

    plot_list <- lapply(c(column_1, column_2),
                        function(column) {
                            max_color <- ifelse(column == column_1,
                                                "#FF0000", "#00FF00")
                            SpatialFeaturePlot(cells_obj, column_1) +
                                scale_fill_gradient(low = "#000000",
                                                    high = max_color) +
                                ggtitle(column) +
                                blend_plot_theme
                        })

    dat <- FetchData(cells_obj, c(column_1, column_2))
    colors <- as.matrix(dat) %>% metadata_to_hexadecimal()

    new_md_column <- paste0(column_1, "_vs_", column_2)
    cells_obj[[new_md_column]] <- colors
    names(colors) <- as.character(colors)

    plot_list[[3]] <- SpatialDimPlot(cells_obj, new_md_column, cols = colors) +
                        ggtitle(paste0(column_1, "_", column_2)) +
                        blend_plot_theme

    side_length <- 100
    legend_grid <- expand.grid(seq(from = min(dat[, column_1]),
                                   to = max(dat[, column_1]),
                                   length.out = side_length),
                               seq(from = min(dat[, column_2]),
                                   to = max(dat[, column_2]),
                                   length.out = side_length))
    colnames(legend_grid) <- c(column_1, column_2)
    legend_colors <- metadata_to_hexadecimal(legend_grid)
    legend_grid$color <- legend_colors
    names(legend_colors) <- legend_colors

    legend <- ggplot(legend_grid,
                     aes(x = .data[[column_1]], y = .data[[column_2]],
                         color = color)) +
                geom_point(shape = 15, size = 1.9) +
                scale_color_manual(values = legend_colors) +
                coord_cartesian(expand = FALSE) +
                theme(legend.position = "none", aspect.ratio = 1,
                      panel.background = element_blank())

    plot_list[[4]] <- wrap_plots(ggplot() + theme_void(), legend,
                                 ggplot() + theme_void(), ncol = 1,
                                 heights = c(0.2, 0.6, 0.2))

    if (combine == FALSE) {
        return(plot_list)
    } else {
        p <- wrap_plots(plot_list, nrow = 1,
                        widths = c(0.28, 0.28, 0.28, 0.16))
        return(p)
    }
}
```

**Example**

Using the `brain` dataset from the [Seurat spatial vignette](https://satijalab.org/seurat/articles/spatial_vignette), we can use `SpatialFeaturePlotBlend` as follows: 

```R
library(Seurat)
library(ggplot2)
library(dplyr)
library(patchwork)

SpatialFeaturePlotBlend(brain, "Hpca", "Ttr")
```

<img width="1478" alt="brain_Hpca_vs_Ttr_blend" src="https://github.com/satijalab/seurat/assets/77325372/1644ead2-6084-4981-a3c2-e0f0f1fb34f2">

**Comment by samuel-marsh** [comment]
Hi @george-hall-ucl,

I think there may be some issues with the plots as per the image you posted.  For instance there are spots that are black in both genes yet have color in blended plot (solid ovals show 2 examples) and at least by my eyes the area of the images that should have the highest intensity for blended color is not the highest on resulting plot (dashed oval).  I might be missing something but wanted to check.

<img width="1478" alt="309250904-1644ead2-6084-4981-a3c2-e0f0f1fb34f2" src="https://github.com/satijalab/seurat/assets/38284410/b4db4899-8b69-4aef-9fb7-a3624c60a6fe">

Best,
Sam

**Comment by howtofindme** [comment]
> Hi @samuel-marsh,
> 
> Whoops! Thank you for spotting this! It looks like I introduced a typo when trying to tidy the code for this post 🤦‍♂️. Turns out I was plotting the same metadata column in each of the first two SpatialFeaturePlots. So, the blended plot was correct, but the colours in the second plot (Ttr) were using the values of Hpca. Fixed in the code below, and I will edit my earlier post.
> 
> The fixed code generates:
> 
> <img alt="brain_Hpca_vs_Ttr_blend_bugfix" width="1486" src="https://private-user-images.githubusercontent.com/77325372/309691552-ca2f528c-1d99-4776-9740-7e3a6086deaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg3NTYsIm5iZiI6MTcxMDMxODQ1NiwicGF0aCI6Ii83NzMyNTM3Mi8zMDk2OTE1NTItY2EyZjUyOGMtMWQ5OS00Nzc2LTk3NDAtN2UzYTYwODZkZWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzRhMWRjMWZmOTNkZjcwZDc2ZjA0YmQ4MTNjOTk5YTAyOWQ5OWQ2NjNmOGFlZGIzYjQ0NjQ2NTE2YzZmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ffyHCUljNMoapaKqPoHsTplaokxNDe_nWpOq-pQddHU">
> `SpatialFeaturePlotBlend` with bugfix:
> 
> ```r
> SpatialFeaturePlotBlend <- function(cells_obj, column_1, column_2,
>                                     combine = TRUE)  {
> 
>     # Convert decimal number to hexadecimal. Pad with 0s if only a single
>     # character following conversion.
>     as_hex <- function(num) {
>         hex_str <- as.character(as.hexmode(num))
>         if (nchar(hex_str) == 1) {
>             hex_str <- paste0("0", hex_str)
>         }
> 
>         return(hex_str)
>     }
> 
>     metadata_to_hexadecimal <- function(in_dat) {
>         apply(in_dat, 2,
>               function(x) {
>                   # Make minimum 0
>                   x - min(x)
>               }) %>%
>         apply(2,
>               function(x) {
>                   # Constrain to range [0, 255]
>                   round(255 * (x / max(x)))
>               }) %>%
>         apply(1,
>               function(x) {
>                   # Convert to hexadecimal codes
>                   toupper(paste0("#", as_hex(x[1]), as_hex(x[2]), "00"))
>               })
>     }
> 
>     blend_plot_theme <- theme(legend.position = "none",
>                               plot.title = element_text(hjust = 0.5))
> 
>     plot_list <- lapply(c(column_1, column_2),
>                         function(column) {
>                             max_color <- ifelse(column == column_1,
>                                                 "#FF0000", "#00FF00")
>                             SpatialFeaturePlot(cells_obj, column) +
>                                 scale_fill_gradient(low = "#000000",
>                                                     high = max_color) +
>                                 ggtitle(column) +
>                                 blend_plot_theme
>                         })
> 
>     dat <- FetchData(cells_obj, c(column_1, column_2))
>     colors <- as.matrix(dat) %>% metadata_to_hexadecimal()
> 
>     new_md_column <- paste0(column_1, "_vs_", column_2)
>     cells_obj[[new_md_column]] <- colors
>     names(colors) <- as.character(colors)
> 
>     plot_list[[3]] <- SpatialDimPlot(cells_obj, new_md_column, cols = colors) +
>                         ggtitle(paste0(column_1, "_", column_2)) +
>                         blend_plot_theme
> 
>     side_length <- 100
>     legend_grid <- expand.grid(seq(from = min(dat[, column_1]),
>                                    to = max(dat[, column_1]),
>                                    length.out = side_length),
>                                seq(from = min(dat[, column_2]),
>                                    to = max(dat[, column_2]),
>                                    length.out = side_length))
>     colnames(legend_grid) <- c(column_1, column_2)
>     legend_colors <- metadata_to_hexadecimal(legend_grid)
>     legend_grid$color <- legend_colors
>     names(legend_colors) <- legend_colors
> 
>     legend <- ggplot(legend_grid,
>                      aes(x = .data[[column_1]], y = .data[[column_2]],
>                          color = color)) +
>                 geom_point(shape = 15, size = 1.9) +
>                 scale_color_manual(values = legend_colors) +
>                 coord_cartesian(expand = FALSE) +
>                 theme(legend.position = "none", aspect.ratio = 1,
>                       panel.background = element_blank())
> 
>     plot_list[[4]] <- wrap_plots(ggplot() + theme_void(), legend,
>                                  ggplot() + theme_void(), ncol = 1,
>                                  heights = c(0.2, 0.6, 0.2))
> 
>     if (combine == FALSE) {
>         return(plot_list)
>     } else {
>         p <- wrap_plots(plot_list, nrow = 1,
>                         widths = c(0.28, 0.28, 0.28, 0.16))
>         return(p)
>     }
> }
> ```
> 
> Thanks again! George

THANKS for your contribution, but it throws me a stranger pic when I run here:
![image](https://github.com/satijalab/seurat/assets/72066151/f8ef4bcd-7f8c-4eca-bca5-1860f967e428)

**Comment by george-hall-ucl** [comment]
Hi @howtofindme!

> THANKS for your contribution, but it throws me a stranger pic when I run here

It looks to me like the legend is not being suppressed as intended (the blended plot will have a legend entry for each spot, hence why the legend needs to be hidden). Has `blend_plot_theme` been correctly copied? What happens if you run it as the `SpatialFeaturePlotBlend` function, rather than running the code inside the function (as I think you're doing here?)

Thanks,
George

**Comment by howtofindme** [comment]
Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.
in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I might think it as a numeric representation of the combined expression.
maybe we should change new_md_column parameter to num

**Comment by howtofindme** [comment]
> Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.
> in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I might think it as a numeric representation of the combined expression.
> maybe we should change new_md_column parameter to num

Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.
in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I might think it as a numeric representation of the combined expression.
maybe we should change new_md_column parameter to num

**Comment by howtofindme** [comment]
> Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.
> in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I might think it as a numeric representation of the combined expression.
> maybe we should change new_md_column parameter to num

Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.

in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I think it as a numeric representation of the combined expression.

maybe we should change new_md_column parameter to num, but I do not know how to change it to num

**Comment by howtofindme** [comment]
> Hi @howtofindme!
> 
> > THANKS for your contribution, but it throws me a stranger pic when I run here
> 
> It looks to me like the legend is not being suppressed as intended (the blended plot will have a legend entry for each spot, hence why the legend needs to be hidden). Has `blend_plot_theme` been correctly copied? What happens if you run it as the `SpatialFeaturePlotBlend` function, rather than running the code inside the function (as I think you're doing here?)
> 
> Thanks, George

Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.

in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I think it as a numeric representation of the combined expression.

maybe we should change new_md_column parameter to num, but I do not know how to change it to num

**Comment by howtofindme** [comment]
> Hi @howtofindme!
> 
> > THANKS for your contribution, but it throws me a stranger pic when I run here
> 
> It looks to me like the legend is not being suppressed as intended (the blended plot will have a legend entry for each spot, hence why the legend needs to be hidden). Has `blend_plot_theme` been correctly copied? What happens if you run it as the `SpatialFeaturePlotBlend` function, rather than running the code inside the function (as I think you're doing here?)
> 
> Thanks, George

Thank you for the rapid reply,
Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.

in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I think it as a numeric representation of the combined expression.

maybe we should change new_md_column parameter to num, but I do not know how to change it to num

Best,
Young

**Comment by howtofindme** [comment]
> Thank you for the rapid reply, Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.
> 
> in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I think it as a numeric representation of the combined expression.
> 
> maybe we should change new_md_column parameter to num, but I do not know how to change it to num
> 
> Best, Young

Thank you for the rapid reply @george-hall-ucl ,
Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.

in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I think it as a numeric representation of the combined expression.

maybe we should change new_md_column parameter to num, but I do not know how to change it to num

Best,
Young

**Comment by howtofindme** [comment]
> Hi @howtofindme
> 
> > Because when I run it as the SpatialFeaturePlotBlend function ,It throws me the same pic.
> 
> Hmm that is weird. What happens if you try to hide the legend with `theme()`? i.e., what happens if you run:
> 
> ```r
> plot_list[[3]] <- SpatialDimPlot(cells_obj, new_md_column, cols = colors) +
>                         ggtitle(paste0(column_1, "_", column_2)) +
>                         theme(legend.position = "none")
> ```
> 
> > in your codes, SpatialFeaturePlotBlend function treats the new_md_column as a color code, while I think it as a numeric representation of the combined expression.
> > maybe we should change new_md_column parameter to num, but I do not know how to change it to num
> 
> Sorry, I'm not quite sure what you mean here, but I think the function's approach should work (although I admit it is messy!). I create a new metadata column which, for each spot, contains the colour that the spot should have in the blended plot. I then tell `SpatialDimPlot` to colour each spot according to the colour stored in that spot's metadata.
> 
> The problem with your code is that the legend is not being hidden and is therefore obscuring the plot. If my above code still does not hide the legend, please can you provide a minimal example (e.g. with the `brain` dataset that I use above) that produces the incorrect plot on your machine, then I will see whether I can reproduce the bug on mine.
> 
> Thanks, George

@george-hall-ucl 

Thanks for your patients,
I found the problems were caused by multiple slides.

And here is the  solutions: 
##select one slide 自建函数----
get_one_slideimage=function(slide,image_name="NS_7"){
  # slide=eachslide
  tmpimages=slide@images[[image_name]]
  slide@images=list()
  slide@images[[image_name]]=tmpimages
  return(slide)
  
}

cells_obj=get_one_slideimage(d.all,image_name = "SiO2_56")

SpatialFeaturePlotBlend(cells_obj ,column_1 = "Gapdh","Actb") &
  theme(legend.position = "none")

![image](https://github.com/satijalab/seurat/assets/72066151/9f1aa8d3-5ddd-45a7-84f5-1a04218c34d0)
But, The final column's green appears less vibrant compared to the second.

By the way, I've made some additions to your SpatialFeaturePlotBlend function.
 SpatialFeaturePlot(cells_obj, column,
                                           keep.scale = 'all', crop = FALSE,
                                           pt.size.factor=1, #控制spot的大小
                                           stroke = 0 ,#控制spot的亮度
                                           max.cutoff = "q99"
                                           )
best,
Young

**Comment by george-hall-ucl** [comment]
Hi @howtofindme,

Well done for fixing it! I wonder if the problem with the colours is also due to the multiple samples / images? Maybe try subsetting out just one sample from `d.all` (e.g. the one corresponding to `SiO2_56`) and see what happens?

Thanks,
George

**Comment by howtofindme** [comment]
> Hi @howtofindme,
> 
> Well done for fixing it! I wonder if the problem with the colours is also due to the multiple samples / images? Maybe try subsetting out just one sample from `d.all` (e.g. the one corresponding to `SiO2_56`) and see what happens?
> 
> Thanks, George
@george-hall-ucl thanks for your kind suggestion,
I've subset the sample as you suggested, but the final column's green is still less vibrant. Any ideas why this might be happening? ![image](https://github.com/satijalab/seurat/assets/72066151/4fcddcc3-259f-4037-a497-13fdec9163a8)
![image](https://github.com/satijalab/seurat/assets/72066151/e53b3787-69a1-4070-b206-a13ed17f304a)
best,
Young

**Comment by george-hall-ucl** [comment]
Hi @howtofindme,

If that didn't fix it, then I wonder if the problem could be some of the extra options you have added to `SpatialFeaturePlot`. What happens if you don't set `keep.scale = 'all'` or `max.cutoff = "q99"`? i.e. revert SpatialFeaturePlot to

```r
SpatialFeaturePlot(cells_obj, column,
crop = FALSE,
pt.size.factor=1, #控制spot的大小
stroke = 0 ,#控制spot的亮度
)
```

Thanks,
George

**Comment by howtofindme** [comment]
> Hi @howtofindme,
> 
> If that didn't fix it, then I wonder if the problem could be some of the extra options you have added to `SpatialFeaturePlot`. What happens if you don't set `keep.scale = 'all'` or `max.cutoff = "q99"`? i.e. revert SpatialFeaturePlot to
> 
> ```r
> SpatialFeaturePlot(cells_obj, column,
> crop = FALSE,
> pt.size.factor=1, #控制spot的大小
> stroke = 0 ,#控制spot的亮度
> )
> ```
> 
> Thanks, George
@george-hall-ucl 
Thank you for your tireless replies.

I followed your instructions, but the results were not much different from before. However, I found a new method that can solve this problem.

You can use the plot_spatial function in cell2location.

The code is as follows:# Now we use cell2location plotter that allows showing multiple cell types in one panel
 #range(0, 7)
# ‘yellow’ ‘orange’ ‘blue’ ‘green’ ‘purple’ ‘grey’ ‘white’

from cell2location.plt import plot_spatial

sample_names=adata_vis.obs['sample'].unique()
sample_names


for slide_name in sample_names:
# select up to 6 clusters
    clust_labels = ['Actb', 'Gapdh']
    #clust_col = ['' + str(i) for i in clust_labels] # in case column names differ from labels
     # Define your cluster colors
    clust_colors = {'Actb' : 'green', 'Gapdh': 'red'}

     # Create a list of colors corresponding to your clusters
    clust_col = [clust_colors[label] for label in clust_labels]


    slide = select_slide(adata_vis, slide_name)
    slide.obs['Gapdh']=slide.X [ :, slide.var.index=='Gapdh'].toarray()  
    slide.obs['Actb']=slide.X [ :, slide.var.index=='Actb'].toarray() 
    with mpl.rc_context({'figure.figsize': (15, 15)}):
        plot_spatial(
        adata=slide,
        # labels to show on a plot
        #clust_col = clust_col, 
        labels=clust_labels,
        reorder_cmap= [0,2],
        color=list({'Actb' : 'green', 'Gapdh': 'red'}),
        show_img=True,
        # 'fast' (white background) or 'dark_background'
        style='fast',
        img_key='hires',
        # limit color scale at 99.2% quantile of cell abundance
        max_color_quantile=0.992,
        # size of locations (adjust depending on figure size)
        circle_diameter=6,
        colorbar_position= "bottom"       #'right'
        )
      #  plt.title(slide_name)  # 设置标题为slide_name
    plt.show()
![image](https://github.com/satijalab/seurat/assets/72066151/9654d67d-7cb6-4378-a006-ef497d351ba2)
Best，
Young

**Comment by george-hall-ucl** [comment]
Hi @howtofindme,

Weird that it still didn't work! Glad you've found a solution though :)

Thanks,
George

**Comment by AnjaK88** [comment]
Hi all,

thanks heaps for this script @george-hall-ucl and many thanks to @howtofindme, as I would have encountered the same issue with multiple slices - everything works well for me!

However, one question (as I am not a bioinformatician myself). Is it possible to add a "default assay" to the script? As one of my genes of interest is "present in more than one".  

Thanks a lot in advance,
Anja

**Comment by howtofindme** [comment]
> Hi all,
> 
> thanks heaps for this script @george-hall-ucl and many thanks to @howtofindme, as I would have encountered the same issue with multiple slices - everything works well for me!
> 
> However, one question (as I am not a bioinformatician myself). Is it possible to add a "default assay" to the script? As one of my genes of interest is "present in more than one".
> 
> Thanks a lot in advance, Anja

hi, you can delete the assay that you do not want before you visiulize
Young

**Comment by george-hall-ucl** [comment]
Hi @AnjaK88 and @howtofindme,

Thank you for your interest and help! I have now improved the code substantially and uploaded it as a [repository](https://github.com/george-hall-ucl/SpatialFeaturePlotBlend) with better documentation. I have now implemented support for multiple images and for non-default assays (among other things - please see the README!)

I suggest that we move future discussion over to that repository. @samuel-marsh @mojaveazure, is it possible for one of you to collapse this thread between my first post and this one please as it has got a bit messy? (this might not be possible on an Issue?) I have linked the repository above and will also add the link in my original post.

Thanks all,
George

**Comment by howtofindme** [comment]
> Hi @AnjaK88 and @howtofindme,
> 
> Thank you for your interest and help! I have now improved the code substantially and uploaded it as a [repository](https://github.com/george-hall-ucl/SpatialFeaturePlotBlend) with better documentation. I have now implemented support for multiple images and for non-default assays (among other things - please see the README!)
> 
> I suggest that we move future discussion over to that repository. @samuel-marsh @mojaveazure, is it possible for one of you to collapse this thread between my first post and this one please as it has got a bit messy? (this might not be possible on an Issue?) I have linked the repository above and will also add the link in my original post.
> 
> Thanks all, George

Dear George，
Thanks for your contribution. we would move to [repository](https://github.com/george-hall-ucl/SpatialFeaturePlotBlend) if we have further disscussions.
Unfortunately, GitHub itself doesn't currently offer a built-in way to collapse threads within issues or discussions.
