### ISSUE TITLE
Integrated Data: Error in [.default(old.meta.data, i) : invalid subscript type 'list'

### ISSUE THREAD

**Issue by Xuyuch** [satijalab/seurat#6098]
Hello,
I want to integrate 2 RNA datafile by using integratedData. I meet similar questions like https://github.com/satijalab/seurat/issues/3871.
I do not know if it is caused by h5ad and H5Seurat. Everything else(like PCA plotting a Umap) went properly when I am analyzing one of these 2 data files.  

This is the code of the FindIntegrationAnchors step

```ruby
anchors <- FindIntegrationAnchors(object.list = c(seq, merfish), dims = 1:15)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=11s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 46500 anchors
Filtering anchors
	Retained 7424 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=03h 26m 42s
```

 Error begins to happen when I am doing the IntegrateData step.

```ruby
integrated <- IntegrateData(anchorset = anchors, dims = 1:15)
Error in `[.default`(old.meta.data, i) : invalid subscript type 'list'
```

and here is the information about my dataset

```ruby
> seq
An object of class Seurat 
36577 features across 22272 samples within 1 assay 
Active assay: RNA (36577 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap
> merfish
An object of class Seurat 
254 features across 280186 samples within 1 assay 
Active assay: RNA (254 features, 254 variable features)
```

Could you please give me some instructions and information about how can I solve it?
Thanks

**Comment by Xuyuch** [comment]
It may be caused by a small problem during process of transfer from anndata to H5Seurat.  I have tried another way(sceasy) to read the anndata into the Seurat program and it works in the end.

**Comment by emmawwinchester** [comment]
I had a similar problem and was able to fix it by specifying the RNA assay. 

specifically, I had the issue using merge:
> name<-merge(E13_5_incisors_2, y=E13_5_incisors_3)
Error in `[.default`(old.meta.data, i) : invalid subscript type 'list'
In addition: Warning message:
In CheckDuplicateCellNames(object.list = objects) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.


and fixed it by designating:
> name<-merge(E13_5_incisors_2[['RNA']], y=E13_5_incisors_3[['RNA']])
which ran with no issues.

**Comment by yhoogstrate** [comment]
This is a strange bug. I have the same - tried to merge a Seurat object created from regular files with one from a converted h5ad.

It seems to 'work' by only merging all except the last cell from the h5ad converted object:

```
glioma.combined <- merge(x = seurat_obj_h5ad[,1:ncol(seurat_obj_h5ad)-1],
                         y = seurat_obj_regular,
                         add.cell.ids = c("j", "b"))
```
Since merging works with `n - 1` but not `n` cells worries me given 1 and 0 count indices for different langues and file formats.
