### ISSUE TITLE
No standard deviation info stored for integrated_lsi

### ISSUE THREAD

**Issue by liz-is** [satijalab/seurat#6101]
Hi,

I have some scATAC-seq data which has been integrated as described [here](https://satijalab.org/signac/articles/integrate_atac.html#integration). I wanted to plot an elbow plot for this data but it seems that the required info is not stored:

```
ElbowPlot(Normal_integrated, ndims = 50, reduction = "integrated_lsi") 
Error in ElbowPlot(Normal_integrated, ndims = 50, reduction = "integrated_lsi") : No standard deviation info stored for integrated_lsi
```

I found this related issue: https://github.com/immunogenomics/harmony/issues/54 for Harmony integration. I also found at least one previous issue https://github.com/timoast/signac/issues/89 where the person runs ElbowPlot on an LSI reduction, suggesting it should be theoretically possible with the integrated LSI too?

**Comment by timoast** [comment]
There's no "integrated" feature loadings or singular values, for this you can use the original (unintegrated) LSI
