### ISSUE TITLE
Question on workflow

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6105]
I have three datasets - WT, KO, and Double KO.  Right now I'm processing all three separately, including running FindClusters() on each.  Then I integrate them and reprocess, including running FindClusters() again on the integrated data.

My question is - should I be running FindClusters() on the individual sets before integrating or is that messing up by data?  Should I be integrating the raw count matrices and then processing or is the workflow I have OK?

Thanks,
Stacy

**Comment by torkencz** [comment]
FindClusters should not be messing anything up with your integration. The workflow that you have should be okay.
