### ISSUE TITLE
Extract same cells in each cluster /sample

### ISSUE THREAD

**Issue by Deepesh123gupta** [satijalab/seurat#6106]
Bad luck solving this issue. :( 
I have 6 scRNA Seq samples (3 WT + 3 MUT). I could able to downsample **X  no. of cells** for each sample but what I want further to keep same cells per cluster per sample. For example: In the below sample , I would like to extract 65 cells per cluster/sample. 

Hard time solving this !

**Issue**: What I am getting is total 65 cells for cluster 1 across all sample 

![image](https://user-images.githubusercontent.com/62347074/175155803-46e1f93c-b0ad-4b09-ad5a-f5cfcbed576f.png)

**Comment by saketkc** [comment]
You could do this using dplyr:

```
object@metadata %>% dplyr::group_by(sample_id, seurat_cluster) %>% sample_n(size=65) %>% rownames() -> cells_to_keep
```

**Comment by Deepesh123gupta** [comment]
Thanks for your response.
