### ISSUE TITLE
Cannot draw heatmap more than 10,000 cells

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#6107]
Hello everyone!

I have a problem for drawing heatmap specific markers.

I want to draw heatmap using total cell. However,  I can't draw it more than 10,000 cells.

In my case, cell number of my sample is:

      Excitatory Oligodendrocyte      Inhibitory       Microglia             OPC     Endothelial            VLMC        NF_oligo 
          56642           11558           11239            4352            2877            1185             662             441 
      Astrocyte 
            479
```
DoHeatmap(subset(inte.combined, downsample = 5000),features = c(Excitatory,Inhibitory,Astro,Microglia,OPC,Oligodendrocyte,Endo,NF_oligo),assay = 'RNA')+scale_fill_gradientn(colours = rev(brewer.pal(7,"RdBu")))
```
![image](https://user-images.githubusercontent.com/52641420/175192886-260616ca-ecfc-41a5-a07e-b3faf389753c.png)

I can draw up to 5,000 cells but I cannot draw more than 10,000.
```
DoHeatmap(inte.combined,features = c(Excitatory,Inhibitory,Astro,Microglia,OPC,Oligodendrocyte,Endo,NF_oligo),assay = 'RNA')+scale_fill_gradientn(colours = rev(brewer.pal(7,"RdBu")))
```
If I run this cmd, no output like this:
![image](https://user-images.githubusercontent.com/52641420/175194701-47394841-374b-4095-a7aa-ece959364732.png)

Thank you for any suggestions!!

**Comment by Gesmira** [comment]
Hi, due to ggplot limitations, the heatmap will not plot if the object is larger than a certain number of cells. If the `inte_combined` object includes all of the cells you showed, the object has more than 70k cells and thus you will have to downsample to plot, as you did in the first example.
