### ISSUE TITLE
Transfer cell-type label from subset to initial seurat_obj

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#6109]
Hi,

I'm stuck on a stupid thing and some help would be much appreciated!

I annotated the main cell types of a **Seurat Object A** and subsetted some of these cell types into a new **Seurat Object B** to have a more accurate annotation of cell subtypes. How can I create in the original **Seurat Object A** a metadata column containing the original cell type annotation A for some of the cells and the new cell subtype annotation B for some other cells? I basically want to include the new subtypes found B in the original **Seurat Object A**.

So far I tried this, but the new subtypes annotation is hidden by the original one.

```
library(scooter)

metadata1 <- seurat_obj@meta.data
metadata2 <- seurat_sub@meta.data
metadata1$celltype <- seurat_obj@meta.data$Cell.Type
metadata2$celltype <- seurat_sub@meta.data$cluster

metadata <- merge_metadata(metadata1, metadata2, log_file = NULL)

metadata1$final_celltype <- metadata$celltype

seurat_obj@meta.data <- metadata1
```
Thank you!!

**Comment by rbutleriii** [comment]
I think you are asking about [updating values in a data.frame](https://stackoverflow.com/questions/32899580/update-rows-of-data-frame-in-r)? 
```R
ind = match(rownames(seurat_sub@meta.data), rownames(seurat_obj@meta.data))
seurat_obj@meta.data[ind, "Cell.Type"] = seurat_sub@meta.data[, "cluster"]
```
no test data provided, so check that gives the output you are wanting.

**Comment by giorgiatosoni** [comment]
> ```r
> ind = match(rownames(seurat_sub@meta.data), rownames(seurat_obj@meta.data))
> seurat_obj@meta.data[ind, "Cell.Type"] = seurat_sub@meta.data[, "cluster"]
> ```

Hi, thanks for your reply!

I tried the code but I get the following error:
_Warning message:
In `[<-.factor`(`*tmp*`, iseq, value = c("Neuroblast", "Neuroblast",  :
  invalid factor level, NA generated_
  
  I tried to convert the seurat_obj@meta.data$Cell.Type using 
`as.character.factor(antagomir@meta.data$Cell.Type)`

No error anymore but the "Cell.Type" values is not updated with the "cluster" values...

**Comment by rbutleriii** [comment]
I imagine it is a dtype issue, they both must be the same, in this case probably best `as.character()`. You can check with `str(sc@meta.data)`
```R
> library(Seurat)
> library(SeuratData)
> sc = ifnb
> sc[["Cell.Type"]] = "Hello"
> sc1 = sc[, c(1, 3, 5)]
> sc1[["cluster"]] = "World"
> head(sc@meta.data)
                  orig.ident nCount_RNA nFeature_RNA stim seurat_annotations
AAACATACATTTCC.1 IMMUNE_CTRL       3017          877 CTRL          CD14 Mono
AAACATACCAGAAA.1 IMMUNE_CTRL       2481          713 CTRL          CD14 Mono
AAACATACCTCGCT.1 IMMUNE_CTRL       3420          850 CTRL          CD14 Mono
AAACATACCTGGTA.1 IMMUNE_CTRL       3156         1109 CTRL                pDC
AAACATACGATGAA.1 IMMUNE_CTRL       1868          634 CTRL       CD4 Memory T
AAACATACGGCATT.1 IMMUNE_CTRL       1581          557 CTRL          CD14 Mono
                 Cell.Type
AAACATACATTTCC.1     Hello
AAACATACCAGAAA.1     Hello
AAACATACCTCGCT.1     Hello
AAACATACCTGGTA.1     Hello
AAACATACGATGAA.1     Hello
AAACATACGGCATT.1     Hello
> ind = match(rownames(sc1@meta.data), rownames(sc@meta.data))
> sc@meta.data[ind, "Cell.Type"] = sc1@meta.data[, "cluster"]
> head(sc@meta.data)
                  orig.ident nCount_RNA nFeature_RNA stim seurat_annotations
AAACATACATTTCC.1 IMMUNE_CTRL       3017          877 CTRL          CD14 Mono
AAACATACCAGAAA.1 IMMUNE_CTRL       2481          713 CTRL          CD14 Mono
AAACATACCTCGCT.1 IMMUNE_CTRL       3420          850 CTRL          CD14 Mono
AAACATACCTGGTA.1 IMMUNE_CTRL       3156         1109 CTRL                pDC
AAACATACGATGAA.1 IMMUNE_CTRL       1868          634 CTRL       CD4 Memory T
AAACATACGGCATT.1 IMMUNE_CTRL       1581          557 CTRL          CD14 Mono
                 Cell.Type
AAACATACATTTCC.1     World
AAACATACCAGAAA.1     Hello
AAACATACCTCGCT.1     World
AAACATACCTGGTA.1     Hello
AAACATACGATGAA.1     World
AAACATACGGCATT.1     Hello
```

**Comment by torkencz** [comment]
Hi, from what I can understand the NAs are generated because the data frame you are trying to add is a subset therefore not all cells get a label in dataset A. I would create a dataframe that comtains all of the cell names of object A and give them an annotation that is other than NA when they are not present in object B. Also I prefer to use the AddMetadata function.

**Comment by tingxie2020** [comment]
Hi I have the same need. Did you[giorgiatosoni](https://github.com/giorgiatosoni) figure out how to do it now?
