### ISSUE TITLE
Using max.cells.per.ident in FindMarkers function

### ISSUE THREAD

**Issue by ravipatel4** [satijalab/seurat#611]
Hi,

I am interested performing differential expression (DE) analysis between two "identities". I am using FindMarkers to do this. Based on the manual of this command, I gather that max.cells.per.ident option allows me to pick (randomly) same number of cells in each "identity", and FindMarkers use only this subset of cells DE analysis. Is my interpretation of this option correct?

If so, when I perform the analysis with different values for max.cells.per.ident, I expect to get different number of genes. However, it doesn't matter what value I choose for max.cells.per.ident, I get same list of genes with identical logFC values. I have 102 cells in one "identity" and 223 cells in another, and I tried Inf, 50 and 100 values for max.cells.per.ident with identical results for all. I think there must be change in logFC at the very least, if this option is supposed to do what I alluded before. Please let me know if I am doing anything wrong. Following are the commands I used.

```
deGenes = FindMarkers(seuratObj, ident.1 = "5-4", ident.2 = "5-2", min.pct = 0.25)
deGenes = FindMarkers(seuratObj, ident.1 = "5-4", ident.2 = "5-2", min.pct = 0.25, max.cells.per.ident = 50)
deGenes = FindMarkers(seuratObj, ident.1 = "5-4", ident.2 = "5-2", min.pct = 0.25, max.cells.per.ident = 102)
```

Thank you.

Best,
Ravi

**Comment by satijalab** [comment]
We calculate average logFC and pct detection on the full dataset, but the p-values are calculated on  the subsampled cells
