### ISSUE TITLE
ImageDimPlot() flipping axes

### ISSUE THREAD

**Issue by pander21** [satijalab/seurat#6110]
Hi, I noticed that `ImageDimPlot()` is flipping axes, i.e. y axis is plotted horizontally and x axis is plotted vertically. Why is that? Expected behaviour would be to plot axes in correct orientation, obviously. Thank you!

**Comment by AustinHartman** [comment]
Hi, this was actually done to mirror the behavior in `SpatialDimPlot` and `SpatialFeaturePlot`. I'd recommend using `coord_flip` from `ggplot2` to flip coordinates to the expected orientation.

**Comment by Puriney** [comment]
Yes, it is really confusing. `x` uses the y-coordinates while `y` uses the x-coordinates. Programmingly speaking, if uses additionally does something like `geom_vline(xintercept = 1000, color='yellow')`, it will draw on the y-axis. Very frustrating. 

https://github.com/satijalab/seurat/blob/1549dcb3075eaeac01c925c4b4bb73c73450fc50/R/visualization.R#L8780-L8788

<img width="628" alt="image" src="https://github.com/user-attachments/assets/90e164d3-1a9e-4c07-8155-9bfb6631b0ce">

<img width="576" alt="image" src="https://github.com/user-attachments/assets/2d0b841f-3640-479e-9ec9-9f9f04e473a6">
