### ISSUE TITLE
Plotting scaled data on a heatmap using the SCT assay

### ISSUE THREAD

**Issue by jdarmitage** [satijalab/seurat#6111]
Hi,

So my understanding is that sctransform() automatically fills the scale.data slot with the Pearson residuals from the transformation, however this is different to the output generated by ScaleData when run on the RNA assay (centers the normalised data which is more useful for heatmaps). Purely for heatmap visualisation only, is it better to scale the SCT data in a similar way to how it's performed on the RNA assay?

Best regards,
Jesse

**Comment by saketkc** [comment]
I would recommend using the corrected counts (data slot of SCT) for visualization on the heatmap. You might also consider scaling it.
