### ISSUE TITLE
Spatial transcriptomics and scRNA data integration (Error in FindTransferAnchors)

### ISSUE THREAD

**Issue by jahanzebsaqib** [satijalab/seurat#6113]
Dear Seurat Team
Hope you are doing well!
I am following this tutorial [spatial vignette](https://satijalab.org/seurat/articles/spatial_vignette.html) with publically available Spatial and scRNA datasets, but the problem is they only provide the count matrix and high-resolution image file (No SpaceRange output is available), that's why I'm trying to create a Spatial Seurat object using two different approaches.

# Approach 1 (input data folder is "approach1")

`data   <- read.table(file='ad_v2.tsv' ,sep="\t", header = TRUE, as.is = TRUE, check.names = FALSE, row.names = 1)`
`object = CreateSeuratObject(counts = data, assay="Spatial")`

`X <- read.table(file='xx.csv')`
`Y <- read.table(file='yy.csv')`
`BARCODES <- t(read.table(file='barcodes_v2.csv'))`
`coord.df = data.frame(x=X, y=Y, stringsAsFactors=FALSE)`
`rownames(coord.df) = BARCODES`

`object@images$image =  new( Class = 'SlideSeq', assay = "Spatial", key = "image_", coordinates = coord.df )`

# Approach 2 (input data folder is "approach2")

`counts <- Read10X('../temp/Final_10X/')`
`object <- CreateSeuratObject(counts, assay = "Spatial")`
`img <- Read10X_Image("../temp/Final_10X/spatial/")`
`img <- img[Cells(object)]`
`DefaultAssay(img) <- DefaultAssay(object)`
`object[["slice"]] <- img`

# scRNA object code (input data folder is "rna")
count_mat <- read.table("GSE138852_counts.csv",sep=",", header = TRUE, as.is = TRUE, check.names = FALSE, row.names = 1)
rna_data  <- CreateSeuratObject(counts = count_mat, project = "combo", min.cells = 3, min.features = 200, assay = 'RNA')

I also uploaded the pre-analyzed RDS object of scRNA data so you can load that object directly

The code is working fine till the section of tutorial **"Identification of Spatially Variable Features"** but when I'm running function `FindTransferAnchors` I'm getting the following error.

![error](https://user-images.githubusercontent.com/49393444/175538119-9e446181-5e79-4d3e-bbc5-043fb63888bd.jpg)

# Following is the link of directory that contains all the input files and scripts
[Data directory](https://drive.google.com/drive/folders/1-3nEkN8IDbl24R8-5VweFGdRN7nZXpbx?usp=sharing)

I'm already read all the pages related to this problem but couldn't find any solution yet.

Your kind consideration will be highly regarded by all means,
Many thanks,
Saqib Jahanzeb

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
