### ISSUE TITLE
Integrating vs Merging: When to do SCTransform() and Which Variable Features to use for downstream clustering analysis?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6116]
Hi there, 

From issues #5667 #5761, @saketkc suggested we should perform SCTransform() separately for each Seurat object (ie each sample) before integrating or merging the samples (then use this merged object to perform downstream PCA, clustering and DEG). 

(1) If want to see which cells are transcriptionally unique to a sample and which cells are transcriptionally shared between samples, should I do merging or integrating?

(2) Is there a senerio when we should merge the samples (as Seurat objects) first before doing SCTransform (i.e. performing SCTransform() on the merged Seurat object)?

Thank you very much for your input!

**Comment by saketkc** [comment]
> (1) If want to see which cells are transcriptionally unique to a sample and which cells are transcriptionally shared between samples, should I do merging or integrating?
 
The goal of integrating is to get rid of batch effects, so the answer is context dependent.

> (2) Is there a senerio when we should merge the samples (as Seurat objects) first before doing SCTransform (i.e. performing SCTransform() on the merged Seurat object)? 

If the technical noise is sufficiently different (generally the case when  using two different technologies, it makes most sense to apply SCT separately. If that is not the case, you would get very similar results either way.

**Comment by denvercal1234GitHub** [comment]
Hi @saketkc - Thanks again for your advice on performing the SelectIntegrationFeatures() for two SCTransform-ed Seurat objects when merging. Doing so however gave me an error when I performed FindTransferAnchors below (having 2 SCT models). Would you mind advising me on how to proceed? Thank you for your help.

```
Error: Given reference assay (SCT) has 2 reference sct models. Please provide a reference assay with a  single reference sct model.
```
