### ISSUE TITLE
Parallelization for PrepSCTFindMarkers

### ISSUE THREAD

**Issue by rbutleriii** [satijalab/seurat#6117]
Hi all, 

[Looking through](https://github.com/satijalab/seurat/blob/f1b2593ea72f2e6d6b16470dc7b9e9b645179923/R/differential_expression.R#L2023) `PrepSCTFindMarkers`, it doesn't look like it is using future to speed up its `lapply` calls, and it is notably slow for me. I think for ~136k cells x 50k features it takes about 4-6ish hours to complete? Small thing, but currently this is the longest step in my pipelines. 

Thanks

**Comment by saketkc** [comment]
Thanks for the request - it can definitely be parallelized. I will look into it.

**Comment by realzehuali** [comment]
I am crying. I have got 98 datasets and 2M cells to run. I am desperate now.

**Comment by dekan-aleksandr** [comment]
I am also crying!

**Comment by saketkc** [comment]
Thanks everyone for your patience. https://github.com/satijalab/seurat/commit/e5171f7a6b2b1145753b0b1606d16e30d6b0984d should speed up `PrepSCTFindMarkers` by default (and also supports parallelization - though that might not always lead to speedups given the data splitting being a bottle neck).

For V4, you can test the changes by installing the latest develop branch:
```r
devtools::install_github("satijalab/seurat", ref="develop")
```
