### ISSUE TITLE
FeaturePlot() + spectral ...in a seurat object split by group

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6119]
Hello. May I kindly ask for your advice on how to implement this spectral color scale? For integrated object, it works perfectly, but if you set the `split.by = group` parameter, only the last figure is colored with spectral scale, while the first and second figures adapts the default.

I was expecting that all three figures (groups) will be colored just like as the integrated object.

**INTEGRATED OBJECT:**
FeaturePlot(KD.harmony, c("CD8A"))+ scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral")))

![image](https://user-images.githubusercontent.com/68268222/175872987-8ae8897f-e8aa-4e02-bcaf-a2257cb81a17.png)
 

**OBJECT SPLIT.BY = GROUP**
FeaturePlot(KD.harmony, c("CD8A"), ncol = 3, split.by = "group", reduction = "umap", max.cutoff = "q98") + scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral")))

![image](https://user-images.githubusercontent.com/68268222/175872165-6727a12a-f2e2-450b-8730-5da971c0e0d5.png)

As you can compare, when I use spectral scale in an integrated object, the cell clusters with no/low expression is colored blue. But when split.by is used, the clusters that express the markers are the ones that are colored blue, while the background is just gray. 

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

This is due to multiple plots being a patchwork object instead of ggplot2.  The only change in your code that is needed is to replace the `+` with patchwork’s `&` to apply theming to all plots.

```
FeaturePlot(KD.harmony, c("CD8A"), ncol = 3, split.by = "group", reduction = "umap", max.cutoff = "q98") & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral")))
```

Best,
Sam
