### ISSUE TITLE
Is it possible to make a Violin Plot where x-axis are genes and split by condition (healthy and disease)?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6120]
hello. Is it possible to make a Violin Plot where, instead of meta.data (groups/conditions/clusters) on x-axis, it (the x-axis) will be genes, and split.by can be set to condition/meta.data? If yes, how to do this?

**Comment by timoast** [comment]
Different genes usually have different expression ranges, and so you would normally want to plot different genes on separate y-axes. There are some more flexible violin-style plotting functions in scCustomize that you might be interested in: https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html
