### ISSUE TITLE
How to make the DotPlot legend text smaller?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6121]
Hi. How can I make the legend text smaller? As you can see from this figure, the scale got cut off at "25". 

I used the "+ theme(axis.text.y = element_text(size = 10))" to attach at the end of the DotPlot function, only the identity/group names gets smaller, while the legends still stay in big fonts:

![image](https://user-images.githubusercontent.com/68268222/175931637-66f0ce84-8abd-4eed-ad29-7bb7d04b056a.png)

I can easily drag the edges of the zoomed/new window of the RStudio's plot, but there's just too much space if I do that:

![image](https://user-images.githubusercontent.com/68268222/175931547-ad825051-5dcc-40dc-8260-9091b9fff0a0.png)

**Comment by samuel-marsh** [comment]
Hi,

Yes you just need to specify the right ggplot2 theme element.  axis.text.y controls y axis text so makes sense that legend remains the same.  See here for example of how to view theme options and how to change legend text size.
https://stackoverflow.com/a/20407883

Best,
Sam

**Comment by levinhein** [comment]
Hi Sam. Is it possible to compress the spacing? As you can see, simply making the legends smaller does not have any impact on the spacing.

* making the spacing tight by manually adjust the zoomed/window of plot cuts the legends.
* default setting where the legends are optimally displayed is too spacious.
* making the fonts of the legends small still leaves the plot very spacious across groups. 

I wonder if you have any workaround on this? Thank you!

![image](https://user-images.githubusercontent.com/68268222/176394992-7f101db4-54b4-4875-8c80-bc678a55c4bb.png)
