### ISSUE TITLE
Number of Variable Features for Homogenous Data

### ISSUE THREAD

**Issue by adri-biochem** [satijalab/seurat#6124]
Hello, I wanted to get someone's opinion on setting this parameter in my analysis. I am working with primarily one cell type only and my data is very homogenous. I also only have 2 WT samples that I am integrating at the moment. I wanted to know if it is better for homogenous data to set more (n = 5000) or less (n = 2000) variable features. When I do this, there does not seem to be a huge difference in how the data looks, or some of the markers, however, I am not sure which would more accurately represent the data for downstream analysis. I was cautioned with some pipelines that this parameter can change clustering so I just wanted to be sure. Thank you!

**Comment by timoast** [comment]
The number of variable features selected determines the set of features used for PCA dimension reduction, and so can influence downstream clustering and visualization (UMAP or tSNE) results. It will not affect differential expression testing, other than effects resulting from changing cluster membership. It's hard to give general advice about what the optimal number of genes is, but usually more complex/heterogeneous datasets will have more variable genes, and more homogeneous datasets might have a smaller set of truly variable genes
