### ISSUE TITLE
After apply AverageExpression(), column name is no longer matching original cell identity

### ISSUE THREAD

**Issue by MaggieLuCB** [satijalab/seurat#6125]
Hi Seurat Team, 

After renaming the cluster to corresponding cell types, I have one cell type that is labeled as "Astrocyte:Embryonic_stem_cell-derived ". However, after applying AverageExpression() function, the text is no longer the same. Instead, the name for that particular cell type is now "Embryonic_stem_cell-derived_Astrocyte".  Is it possible to preserve the original text during AverageExpression calculation?

**Comment by longmanz** [comment]
Hi,
Please avoid using ":" when labelling your cells if you do not want this auto-conversion to happen. This is because the AverageExpression() will automatically remove any ":" and append it to the end of the string. The exact code is as followed:
`colnames(x = category.matrix) <- sapply(
      X = colnames(x = category.matrix),
      FUN = function(name) {
        name <- gsub(pattern = "data\\[, [1-9]*\\]", replacement = "", x = name)
        return(paste0(rev(x = unlist(x = strsplit(x = name, split = ":"))), collapse = "_"))
      })`
