### ISSUE TITLE
GEO txt.gz file does not contain gene names

### ISSUE THREAD

**Issue by vleifer685** [satijalab/seurat#6126]
Hi!

I have a question about analyzing a txt.gz file from GEO, which does not contain gene names, only sequences (e.g. "TTTAGTCAGGAAAGGT"). Each sequence is its own row. Is there a way to identify the gene name (e.g. CD79) that each sequence corresponds to? 

For some reason it seems like I can filter out mitochondrial genes, which makes me wonder whether seurat understands the gene names, and I just can't see them for some reason. I'm not very familiar with analyzing GEO data, so if there are some basics that I'm missing that anyone can point out, that would be helpful.

Here is the dataset: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE155512
Here is my code:

data <- read.delim("~/Desktop/GSE155512_RAW/GSM4705589_RPE004_matrix.txt.gz", header = T, stringsAsFactors = F)
seurat <- CreateSeuratObject(data, min.cells = 10, min.features = 200, project = "seurat")
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")

Thank you!

**Comment by saketkc** [comment]
```r
counts <- read.delim("notebooks/GSM4705589_RPE004_matrix.txt.gz", row.names=1)
```

The first column needs to be read as rownames.
