### ISSUE TITLE
Variable Features function in Seurat v4

### ISSUE THREAD

**Issue by ahassien** [satijalab/seurat#6128]
Hello there,

I am trying to run the cluster_sim.R simulations code found here:
https://github.com/MarioniLab/FurtherMNN2018

I am using Seurat v4, and I get the following error:

```
Error in RunCCA.Seurat(Se, Se2, genes.use = rownames(batches[[1]]), do.normalize = FALSE) : 
VariableFeatures not computed for the RNA assay in object1
```

Is the VariableFeatures function still supported by Seurat v4? It appears that using this function returns an empty logical when debugging.

```
Browse[1]> VariableFeatures(object1, assay=assay1)
logical(0)
```

```
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

```

**Comment by timoast** [comment]
`VariableFeatures()` is an accessor function, and is still present in Seurat v4. The reason it returns an empty vector is that there are no variable features that have been compute for this assay. You can assign variable features using the `VariableFeatures(obj) <- features` syntax, or by running `FindVariableFeatures()`.
