### ISSUE TITLE
HTOdemux assumption 

### ISSUE THREAD

**Issue by juanjaureguilozano** [satijalab/seurat#6130]
Hi!

I am running HTOdemux for cell hashing demultiplexing using 4 samples that were pooled in same well. However, the pooling was not even, where S1=37%, S2 and S3=25%, and S4=12.5% of cells. Do you know if this would cause an issue for analysis? My concern is whether HTOdemux makes an assumption that all the HTOs for singlets will be found in a somewhat similar count/proportion leading to change in cutoffs?

Thank you so much!

**Comment by longmanz** [comment]
Hi @juanjaureguilozano,
HTODemux is based on k-means. If you are concerned about the sample proportion affecting the tag cut-offs, you may try MULTIseqDemux() alternatively, since it determines the cut-off individually based on the tag's count distribution for each tag.
