### ISSUE TITLE
What to do to resolve the issue with strong linear correlation found after FeatureScatter()?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6131]
Hello. I was doing a FeatureScatter of 2 gene set scores (A and B) using FeatureScatter() to conclude a positive correlation (e.g. the higher the "A", the higher the "B"). 

1. However according to issue https://github.com/satijalab/seurat/issues/1470, the expected visualization should be cloud-like and not a straight line in the middle, or that it might be confounding. Below, I observed the same phenomenon on my data. 

2. Also, as you can see from the data, the majority of expression of all cells in x-axis and y-axis are above zero, however, the correlation score became -0.09. Based on the figure, shouldn't it be positively correlated?  

3. Or is FeatureScatter() a great way to check positive correlation? Is there any better way/technique that I might be missing out to check correlation of two gene set scores?

![image](https://user-images.githubusercontent.com/68268222/176611815-2f270540-b709-4b03-8b1d-37e3b3e3a537.png)

**Comment by saketkc** [comment]
The correlation value here is -0.09 (plot title), which is near zero. You can manually run `cor(FeatureSetA, FeatureSetB)` to cross check this value (this should also answer your other question).
