### ISSUE TITLE
FindMarkers() for three integrated conditions

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6133]
Hi all,

I have three conditions which I have integrated, WT/KO/DBL_KO.  How do I use FindMarkers() in this case?  There is no ident.3 parameter.  Do I have to do this multiple times:
iteration #1: ident.1 = WT, ident.2 = KO
iteration #2: ident.1 = WT, ident.2 = DBL_KO
iteration#3: ident.2 = KO, ident.2 = DBL_KO

so that each condition is compared with every other condition?  Or is that a better way to do this?

Thanks,
Stacy

**Comment by saketkc** [comment]
If you just specify `ident.1="WT"`, it would do one vs rest (KO + DBL_KO) comparison. See the function [documentation](https://satijalab.org/seurat/reference/findmarkers) for details.
