### ISSUE TITLE
LeverageScoreSampling message - nsketch

### ISSUE THREAD

**Issue by cbligaard** [satijalab/seurat#6134]
Hi Seurat team,

I was testing the atomic sketch integration approach, and when using the `LeverageScoreSampling` function, I noticed that even when changing the input to the `num.cells` argument, I still got the message "CountSketch sampling 5000 cells". Looking at the function, this appears to be due to the message printing `nsketch` [here](https://github.com/satijalab/seurat/blob/b4fdcbd8b7509dff1e914435f7ba7ffc7b318260/R/integration.R#L6407).

I am wondering if this is a mistake or if I am missing the meaning of `nsketch`. Just to be clear, the output from `LeverageScoreSampling` does return the desired `num.cells`.

Best,
Christina

**Comment by yuhanH** [comment]
Hi 
`nsketch` is a parameter in function `LeverageScore` and it is used to determine the size of CountSketch random matrix, which is related to the calculation of leverage score. 
`num.cells` in function `LeverageScoreSampling` is the number of sampling cells based on the leverage score. 
We will improve the documentation of these two functions.

**Comment by yuhanH** [comment]
Thank you for reporting this. We have improved the documentation in the latest seurat5 branch.
