### ISSUE TITLE
Original Identity after Integration

### ISSUE THREAD

**Issue by pbpayal** [satijalab/seurat#6135]
Hello,

I integrated 8 10X datasets ( 4 controls and 4 experiment) using FindIntegrationAnchors and IntegrateData.

Will this give me number of cells or number of genes per sample?
`table(integrated_data$orig.ident)`

I want to find out how many cells are in each replicate.

Thanks,
Payal

**Comment by pbpayal** [comment]
Thanks @jarchana09 for your prompt reply.

When I do
`table(integrated_data$orig.ident)`
```
# sample_132 sample_155 sample_165 sample_295 sample_300 sample_301 sample_319 sample_326 
# 3004       3576       7042       9932       1572       3841        827       1790 

```
But, before integration step when I do separately 
```
dim(sample_319_sobj)
```
```
# [1] 17644  3375
which is 17644 genes and 3375 cells right?
```

After integration, for sample_319, the number of cells show 827 . Do the number of cells reduce due to normalization after integration?

**Comment by jarchana09** [comment]
Hi Payal,
As far as I understand, normalization and integration will not reduce the number of cells. 
1. Have you tried checking the number of cells in the integrated object by specifying the meta.data column corresponding to the sample_id instead of orig.ident?
2. Is the number of cells showing up differently only for one sample with your code?

In response to your query, you are correct that 3375 is the number of cells.

**Comment by pbpayal** [comment]
Yes, the number of cells are showing up differenlty for all samples.

First I filtered for UMIs and genes, then normalized and did FindVariableFeatures in each group for all the samples like this example.

```
sample_132 <- Read10X(data.dir = "../132/filtered_feature_bc_matrix")
sample_132_sobj <- CreateSeuratObject(counts = sample_132, project = "sample_132", min.cells = 3, min.features = 200)
dim(sample_132_sobj)
# [1] 21405 12925
sample_132_sobj$stim <- "MD"
sample_132_sobj[["percent.mt"]] <- PercentageFeatureSet(sample_132_sobj, pattern = "^MT-")
sample_132_sub <- subset(sample_132_sobj, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5 )
sample_132_sub <- NormalizeData(sample_132_sub, verbose = FALSE)
sample_132_sub <- FindVariableFeatures(sample_132_sub, selection.method = "vst", nfeatures = 2000)

```
Then  I integrated the datasets like this:
```
immune.anchors.2 <- FindIntegrationAnchors(object.list = list(sample_300_sub, sample_301_sub,sample_165_sub, sample_295_sub,
                                                            sample_326_sub,sample_319_sub,sample_155_sub,sample_132_sub), dims = 1:20)
immune.combined.integrated <- IntegrateData(anchorset = immune.anchors.2, dims = 1:20)
dim(immune.combined.integrated)
[1] 23477 31584
```
```
table(immune.combined.integrated@meta.data$orig.ident)
sample_132 sample_155 sample_165 sample_295 sample_300 sample_301 sample_319 sample_326 
      3004       3576       7042       9932       1572       3841        827       1790 

```
But I donot see the sample names separately in the metadata object. I get the following options
![Screen Shot 2022-07-01 at 2 40 53 PM](https://user-images.githubusercontent.com/20340380/176953143-8b074eab-ad90-4040-a3dc-6d4f4406a8d0.png)

**Comment by torkencz** [comment]
Hi @pbpayal,

Integration should never reduce the number of cells you have. The only time you filter out cells is in your sample_132_sub <- subset(sample_132_sobj, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5 ) step, so you should be checking dim after that step. Also if you create a metadata column like object$sample<-"sample_1 for each of your objects before integration then you can run table on that metadata column after integration. This should match up in numbers with you filtered number of cells.
