### ISSUE TITLE
inconsistent results of manual calculate with the Findmarkers function

### ISSUE THREAD

**Issue by Lei-GitHub** [satijalab/seurat#6136]
Hi Seurat teams,

Thank you.
I use the Findmarkers function and get the results like this: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xul8/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xul8/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

p_val | avg_logFC | pct.1 | pct.2 | p_val_adj | symbol
-- | -- | -- | -- | -- | --
0 | -1.41485 | 0.357 | 0.686 | 0 | NPDC1

</body>

</html>

And my code for findmarkers is like this : 
FindMarkers(data,ident.2 = ident.2,ident.1 = ident.1, verbose = FALSE,pseudocount.use = 0, base=2,min.pct=0).

But if I use the manual method with data slot, 
log2(rowmean(data@assays$RNA@data[,ident.1])/rowmean(data@assays$RNA@data[,ident.2))

I got the value like this 
= log2( 0.16708877/0.552549357)
=-1.725489

the fold change calculated by manual is big than FindMarkers function (-1.414850315). 
Would you mind help me to see what I missed in my calculation and which parameters in Findmarkers function I ignored?
I really appreciate that.
Best,
Lei

**Comment by timoast** [comment]
Here you're taking mean in log-transformed data (assuming you ran NormalizeData), whereas the `FindMarkers()` function reports mean in the non-log transformed expression space

**Comment by Lei-GitHub** [comment]
> Here you're taking mean in log-transformed data (assuming you ran NormalizeData), whereas the `FindMarkers()` function reports mean in the non-log transformed expression space

Thank you very much for that answer. Do you mean the data from data@assays$RNA@data[,ident.1] is the log-transformed data? May I know where can I find the data FindMarkers default use?  Thank you very much.
