### ISSUE TITLE
How to add color gradient guide to my FeaturePlot?

### ISSUE THREAD

**Issue by Zhr-Abdi** [satijalab/seurat#6139]
Hi
When I'm using `FeaturePlot()` for one gene, my graph has the color gradient guide but when I want to plot multi genes, the color gradient guide is missed.
`FeaturePlot(seurat.HSC, features ='Ecm1', min.cutoff = 'q10')`

vs

`FeaturePlot(seurat.HSC, features = c('Ecm1','Gucy1b1','Acta2'), min.cutoff = 'q10', 
            split.by = 'sample'  )`

Thanks for any help.
![33](https://user-images.githubusercontent.com/79995272/176841888-6d1b116f-f0e6-429f-b68d-9883a1a20b09.JPG)
![44](https://user-images.githubusercontent.com/79995272/176841906-d2547eb8-b5d7-4926-b4e7-d3a36c09befe.JPG)

**Comment by jarchana09** [comment]
Hi,
As mentioned by @samuel-marsh in [https://github.com/satijalab/seurat/issues/5243#issuecomment-954794948](https://github.com/satijalab/seurat/issues/5243#issuecomment-954794948), you can use ggplot2's theme to include the legend for the color scale.
For example, with your code:
`FeaturePlot(seurat.HSC, features = c('Ecm1','Gucy1b1','Acta2'), min.cutoff = 'q10', split.by = 'sample' ) & theme(legend.position = "right")`

Hope this helps. Thanks.
