### ISSUE TITLE
VariableFeatures for integration: CCA vs Harmony/FastMNN

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#6140]
I want to integrate 3 datasets and I have a question about what the best way to select `VariableFeatures` is. If I use
CCA, the recommendation is to select `VariableFeatures` for each batch, however in `RunFastMNN` or `RunHarmony`,
the `VariableFeatures` are calculated in the merged object.
So I want to ask what is, in your opinion, the most accurate way to select those; calculate them for each batch and
then select the intersection (or union) or to calculate them on the whole object? Criteria would be, of course, a good
balance between batch removal and biological conservation.

**Comment by torkencz** [comment]
Hi, 
I can only give you my personal take on this subject. I have in the past used SelectIntegrationFeatures when integrating across more than two datasets. This function ranks features by the number of datasets they are deemed variable in, breaking ties by the median variable feature rank across datasets. However, doing variable feature across all datasets should also work, depending on how different the datasets are that you are trying to integrate. So in summary I think it varies depending on the datasets that you are trying to integrate and if you have the time you should try multiple approaches.
