### ISSUE TITLE
Subsetting a Seurat object based on genotype

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6142]
I would like to subset my Seurat object (called gene.conditions) and pull all Idents not containing the "WT" pattern.  The Idents right now follow:
0.Rpl7_WT 3.Ptma_WT 2.Ptma_WT 1.Prdx6_WT 15.Col9a1_DBL_KO ...

I want to subset all the Idents that don't have "WT" in them.  Currently I have:
```
stim.cells <- subset(gene.conditions, Idents = !grepl("WT", Idents(gene.conditions)))
```

but this is not working.  Any ideas on how I accomplish this?

Thanks

**Comment by torkencz** [comment]
Hi, I would create a metadata column based on your cell id's (maybe use str_split_fixed) and then subset based on that.
