### ISSUE TITLE
Confused about PrepSCTFindMarkers in SCTransform v2

### ISSUE THREAD

**Issue by longxiaxiao** [satijalab/seurat#6144]
Hi! Thanks a lot for your useful tool for single cell analysis.

Recently i used SCTransform v2 according to this vignette: [sctransform_v2_vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html).

There are 2 samples for analysis. First, in order to do DE analysis between **these 2 samples**, i ran
`samples.combined <- PrepSCTFindMarkers(samples.combined) `
`DEG_btw2samples <- FindMarkers(samples.combined , assay = "SCT", slot = "data",  ident.1 = "sample2", ident.2 = "sample1")`
It worked well!

Then, i'd like to find DEG in a specific cluster analysed before between these 2 samples like:
`cluster.combined.sct <- samples.combined[ , samples.combined$cell %in% c('cell_type')]`
`DEG_incluster_btw2samples <- FindMarkers(cluster.combined.sct , assay = "SCT", slot = "data", 
                                   ident.1 = "sample2", ident.2 = "sample1")` 

 I got this information:
**Run 'PrepSCTFindMarkers' before running 'FindMarkers()'.**
But i run PrepSCTFindMarkers() before! I am confused that whether running PrepSCTFindMarkers() so many times results in overcorrection. 

Thanks for your attention!

**Comment by saketkc** [comment]
If you are doing DE on a subset, re-correction is not required, as mentioned in the vignette:
> If running on a subset of the original object after running [PrepSCTFindMarkers()](https://satijalab.org/seurat/reference/PrepSCTFindMarkers.html), [FindMarkers()](https://satijalab.org/seurat/reference/FindMarkers.html) should be invoked with recorrect_umi = FALSE to use the existing corrected counts:

```r
immune.combined.sct.subset <- [subset](https://rdrr.io/r/base/subset.html)(immune.combined.sct, idents = [c](https://rdrr.io/r/base/c.html)("B_STIM", "B_CTRL"))
b.interferon.response.subset <- [FindMarkers](https://satijalab.org/seurat/reference/FindMarkers.html)(immune.combined.sct.subset, assay = "SCT", ident.1 = "B_STIM", ident.2 = "B_CTRL", verbose = FALSE, recorrect_umi = FALSE)
```
