### ISSUE TITLE
Cluster label positions

### ISSUE THREAD

**Issue by mukundvarma** [satijalab/seurat#615]
Is there a way to get label positions for the cluster names (i.e. the coordinates they appear on, on the tSNE plot)? This could be useful for uploading datasets to the Broad single cell portal.

**Comment by satijalab** [comment]
We don't output these coordinates in the package- but they are easy to compute using

1. The cell IDs per cluster (WhichCells)
2. The tSNE embeddings (GetCellEmbeddings)
