### ISSUE TITLE
WNN vignette: setting dimensions forces wnn-umap to rna-umap

### ISSUE THREAD

**Issue by ViHammer** [satijalab/seurat#6151]
I have noticed that, when limiting the number of dimensions used for RunUMAP, the wnn and the purely rna based UMAP projection are identical.

I ran the exact code of the WNN vignette up to and including the FindMultiModalNeighbors step.
I then ran the following code for umapping and plotting. Please note that the only thing I changed is adding a `dims` flag to the wnn UMAP projection:
```
bm <- RunUMAP(bm,
              dims = 1:30, # ADDED THIS LINE
	      nn.name = "weighted.nn", 
              reduction.name = "wnn.umap", 
	      reduction.key = "wnnUMAP_")
bm <- FindClusters(bm, graph.name = "wsnn", algorithm = 3, resolution = 2, verbose = FALSE)

bm <- RunUMAP(bm, 
              reduction = 'pca', 
              dims = 1:30, 
	      assay = 'RNA', 
              reduction.name = 'rna.umap',
              reduction.key = 'rnaUMAP_')
			  
bm <- RunUMAP(bm, 
              reduction = 'apca', 
              dims = 1:18, 
	      assay = 'ADT', 
              reduction.name = 'adt.umap', 
              reduction.key = 'adtUMAP_')

p2 <- DimPlot(bm, reduction = 'wnn.umap', label = TRUE, repel = TRUE, group.by = 'celltype.l2', label.size = 2.5) + NoLegend()			  
p3 <- DimPlot(bm, reduction = 'rna.umap', label = TRUE, repel = TRUE, group.by = 'celltype.l2', label.size = 2.5) + NoLegend()
p4 <- DimPlot(bm, reduction = 'adt.umap', label = TRUE, repel = TRUE, group.by = 'celltype.l2', label.size = 2.5) + NoLegend()

pdf("example_plots.pdf", width = 20)
p2 + p3 + p4
dev.off()
```

![grafik](https://user-images.githubusercontent.com/43847498/177157477-368eeb1f-99aa-4860-ae28-69a4718b276a.png)
The WNN and RNA umap projections are identical.

Why does limiting the pca dimensions cause this? Is this an error in the vignette, or does it cause RunUMAP to default back to the rna pca embedding?

**Comment by yuhanH** [comment]
Thanks for reporting this bug. When you add the `dims`, the current function will directly use PCA with dims to run UMAP instead of using `nn.name = "weighted.nn"`.

**Comment by yuhanH** [comment]
Thank you for reporting this bug. It is fixed in the latest seurat5 branch.
