### ISSUE TITLE
How to get the embeddings after data integration using CCA

### ISSUE THREAD

**Issue by RawanSO** [satijalab/seurat#6152]
Hi,
I performed data integration on two datasets using 'IntegrateData' from Seurat using CCA. Is there a way to get the embeddings from CCA results for the integrated data object?
Thanks

**Comment by torkencz** [comment]
You should run Embeddings(object) on the integrated assay.

**Comment by RawanSO** [comment]
Thanks for your reply.
However, after I run Embeddings(immune.combined) , I got 'Error: Cannot find 'pca' in this Seurat object'! any idea how to get CCA embeddings on the intergrated cca-based object? Thanks
