### ISSUE TITLE
Order of clusters in VlnPlot

### ISSUE THREAD

**Issue by aminerva** [satijalab/seurat#6153]
I have multiple Seurat objects that all come from the same larger dataset, but each one contains only those cells that express a gene at a value >0. For example, two of these objects were created with the following code. 

`non_da_Insr_sub <- subset(x = ctrl_non_da, subset = Insr > 0)
non_da_Lepr_sub <- subset(x = ctrl_non_da, subset = Lepr > 0)`

The original larger dataset (ctrl_non_da) was already clustered upstream, so these subsets contain the same cluster labels. When plotting gene expression across the clusters in a given subset the order of the clusters is colored differently in each subset. See plots attached. In the first, the clusters are correctly colored in numerical order. In the second, the clusters are colored in order of their first digit. I am not talking about the order on the x axis, but rather the order they are being colored and are showing up in the legend. Changing the Idents does not seem to solve this issue, as it just reorders the x axis to match the incorrect legend order (third image). Do you know why this is happening? And how I can fix it so that the clusters in every object are colored in the correct order?

Code to create the plots is as follows:

1) correct Insr plot
`options(repr.plot.width = 8, repr.plot.height = 5) 
VlnPlot(non_da_Insr_sub, features=c("Insr"), slot="data")`

2) Incorrect Lepr plot
`options(repr.plot.width = 8, repr.plot.height = 5) 
VlnPlot(non_da_Lepr_sub, features=c("Lepr"), slot="data")`

3) Reordered Lepr plot, still incorrect
`Idents(non_da_Lepr_sub) <- factor(x=Idents(non_da_Lepr_sub), levels=sort(levels(non_da_Lepr_sub)))
options(repr.plot.width = 8, repr.plot.height = 5) 
VlnPlot(non_da_Lepr_sub, features=c("Lepr"), slot="data")`

![image](https://user-images.githubusercontent.com/55995342/177389339-74038960-3c3b-456c-8eb5-be4ab49867cd.png)

![image](https://user-images.githubusercontent.com/55995342/177389591-c94cf8a4-2b6b-4567-a245-2955e2749cd7.png)

![image](https://user-images.githubusercontent.com/55995342/177389649-5b65dce8-40c6-4e48-868d-fa397682481c.png)

**Comment by tkim-NW** [comment]
Have you already tried using ggplot2 layers to alter your plots? something like scale_fill_discrete() or scale_colour_manual() to your VlnPlot command? 
Like this:
`VlnPlot(non_da_Lepr_sub, features=c("Lepr"), slot="data") + scale_colour_manual(values = c("red", "blue", "green", [ETC, FILL IN THE COLORS YOU CHOOSE HERE])`
for reference: https://ggplot2.tidyverse.org/reference/scale_manual.html#color-blindness

if you already have please disregard

**Comment by timoast** [comment]
The order that cell groups are displayed is determined by the factor levels in the object, this can be changed using the `levels()` function
