### ISSUE TITLE
confusion about scTransform scale data

### ISSUE THREAD

**Issue by Fclef** [satijalab/seurat#6155]
Hi,

I'm using seraut for one of my single cell projects. And I have some doubts reagarding to sctransform correction.
I have virus infected and uninfected human cells and I use sctransform to normalize the data. The thing is, after performing scTransform, I realize some of the virus genes have non-zero expression in scale.data slot while in count slot they are still zero.
I understand scale.data is essentially like z-score, since I normalized infected and uninfected cells together, the basemean is not zero anymore. But how come uninfected cells have various expressions in scale.data but all zero in counts slot? Isn't the count slot reverse transformed from scale.data? 

Thanks for your help in advance！

**Comment by saketkc** [comment]
`counts` slot stores the corrected counts (after adjusting for sequencing depth, once a regularized negative binomial model has been run). The `scale.data` stores the pearson residuals (which basically are an estimate of how different is a given gene's expression given the expected mean). If you have all zeros for a gene, it should have been filtered out in the first step of SCTransform (where by default it considers only genes that are expressed in at least 5 cells). But the pearson residuals are calculated per cell per gene (which takes into account the actual sequencing depth of the cell) - which would explain why they could be different even if you have the same counts.
