### ISSUE TITLE
DimPlot vector.friendly does not work for ggplot2 3.0.0

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#616]
Hi,

I updated ggplot2 to the new 3.0 version. Now the `vector.friendly` option in `DimPlot` does not work anymore. Only cluster labels are plotted, but the cells are missing. In addition, I received the following warning message:
```
Warning in min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
Warning in max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
```

Thanks! 

![image](https://user-images.githubusercontent.com/5046690/42723615-73f57fa0-871e-11e8-809f-537684e00f13.png)

**Comment by mojaveazure** [comment]
Should be fixed as of commit 917ec43
