### ISSUE TITLE
Accessing column in expression matrix for a particular sample

### ISSUE THREAD

**Issue by aryan-dugar2** [satijalab/seurat#6164]
Given a SeuratObject created from a 10X file,  `pbmc`, how can I access the expression values across ALL features for a particular cell? I know I can access the cell names with `rownames(pbmc@meta.data)` and the matrix with `GetAssayData(object = pbmc, slot = "counts")`, but I'm really confused as to how to index the matrix such that I can extract a column/row from it. (I am not sure if the data I want is a row or column in the matrix - I believe it is a column).

**Comment by torkencz** [comment]
Hi, 
I would either use the FetchData command or us GetAssayData and select a column. 
https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/GetAssayData
https://rdrr.io/github/mojaveazure/seurat-object/man/FetchData.html
