### ISSUE TITLE
ERROR: lazy loading failed for package ‘Seurat’

### ISSUE THREAD

**Issue by hemantgujar** [satijalab/seurat#6165]
Hi can anyone help with following error. Thanks. 

` install.packages("Seurat")`

g++ -std=gnu++11 -I"/sc/arion/work/gujarh01/software/R-4.1.2/include" -DNDEBUG  -I'/sc/arion/work/gujarh01/software/R-4.1.2/library/Rcpp/include' -I'/sc/arion/work/gujarh01/software/R-4.1.2/library/RcppEigen/include' -I'/sc/arion/work/gujarh01/software/R-4.1.2/library/RcppProgress/include' -I/usr/local/include   -fpic  -g -O2  -c stats.cpp -o stats.o
gcc -std=gnu11 -I"/sc/arion/work/gujarh01/software/R-4.1.2/include" -DNDEBUG  -I'/sc/arion/work/gujarh01/software/R-4.1.2/library/Rcpp/include' -I'/sc/arion/work/gujarh01/software/R-4.1.2/library/RcppEigen/include' -I'/sc/arion/work/gujarh01/software/R-4.1.2/library/RcppProgress/include' -I/usr/local/include   -fpic  -g -O2  -c valid_pointer.c -o valid_pointer.o
g++ -std=gnu++11 -shared -L/usr/local/lib64 -o Seurat.so ModularityOptimizer.o RModularityOptimizer.o RcppExports.o data_manipulation.o fast_NN_dist.o integration.o snn.o stats.o valid_pointer.o
installing to /sc/arion/work/gujarh01/software/R-4.1.2/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 328447 Segmentation fault      R_TESTS= '/sc/arion/work/gujarh01/software/R-4.1.2/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/Rtmp6Bg97f/file4d6754b818bd7'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE)
 7: (function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>),     error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
17: asNamespace(ns)
18: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
19: loadNamespace(package = package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, partial = TRUE)
20: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
21: suppressPackageStartupMessages(loadNamespace(package = package,     lib.loc = lib.loc, keep.source = keep.source, keep.parse.data = keep.parse.data,     partial = TRUE))
22: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, compress = compress, set.install.dir = set.install.dir)
23: tools:::makeLazyLoading("Seurat", "/sc/arion/work/gujarh01/software/R-4.1.2/library/00LOCK-Seurat/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/sc/arion/work/gujarh01/software/R-4.1.2/library/Seurat")
An irrecoverable exception occurred. R is aborting now ...
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/sc/arion/work/gujarh01/software/R-4.1.2/library/Seurat’

The downloaded source packages are in
        ‘/tmp/RtmphneQ85/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status

`> sessionInfo()`
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /sc/arion/work/gujarh01/software/R-4.1.2/lib/libRblas.so
LAPACK: /sc/arion/work/gujarh01/software/R-4.1.2/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] XML_3.99-0.8 tiff_0.1-10

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2

**Comment by mojaveazure** [comment]
Try updating your existing packages with `update.packages()`, then try installing Seurat
