### ISSUE TITLE
Differential expression across two clusters subsetted from an integrated seurat object

### ISSUE THREAD

**Issue by vleifer685** [satijalab/seurat#6167]
Hi! 

I integrated two datasets, then subsetted two clusters of T cells - one from each of the original objects. Each cluster has its original dataset saved in the metadata (e.g.: Tcells$orig_ident splits the cells into two, one for each dataset).

I would like to make a scatterplot of differentially expressed genes between the two clusters, and have followed the tutorial here: https://satijalab.org/seurat/articles/integration_introduction.html

I am able to generate a list of the average expression of each gene in the integrated T cell cluster, but am having trouble creating the scatterplot. Whenever I do so, only a single point appears (screenshot attached). 

R reports this error: 
1. Error in FUN(X[[i]], ...) : object 'Orig_Dataset_A' not found 2. 
- This occurs after I run the line of code with ggplot.
- This does not occur when I put the two axis labels in quotes (e.g., aes("Orig_Dataset_A", "Orig_Dataset_B")

My code is below. I would really appreciate any help troubleshooting!

Below, seurat is the integrated object. In the metadata, celltype contains cell labels from original clusters (e.g. before integration); orig_ident contains the labels for each original dataset (e.g. A and B). 

t.cells <- subset(seurat, subset = celltype == c("T cells 1", "T cells 2"))
avg.t.cells <- as.data.frame(log1p(AverageExpression(t.cells, verbose = FALSE)$RNA))
avg.t.cells$gene <- rownames(avg.t.cells)
genes.to.label = c("CD4", "CD8")
p1 <- ggplot(avg.t.cells, aes("Orig_dataset_A", "Orig_dataset_B")) + geom_point() + ggtitle("T Cells")
p1 <- LabelPoints(plot = p1, points = genes.to.label, repel = TRUE)

<img width="616" alt="Screen Shot 2022-07-07 at 6 42 42 PM" src="https://user-images.githubusercontent.com/89035872/177883375-1d27da66-dcd8-4b8f-9e0f-411923c1ef6d.png">

**Comment by torkencz** [comment]
It seems like in this case you are plotting a "dataset" where you provide 1 data point that consists of the vector "Orig_dataset_A", "Orig_dataset_B". I recommend you check what your column names are after the averaging (are your Idents Orig_dataset_A and B?), because it seems like you don't have that in the dataframe you create. I can reopen if problem continues.
