### ISSUE TITLE
IntegrateData before TransferData

### ISSUE THREAD

**Issue by qiminghaonan1** [satijalab/seurat#6168]
Hi,
We have performed spatia sequencing and single-cell nuclear sequencing on the same samples respectively. 

We want to use ‘’FindTransferAnchors’ and ‘TransferData’  to add cell type annotation to spatial dataset by single-cell nuclear dataset. 

Transfer alone is not effective. Can we first Integrate single-cell data and spatial data by using ‘FindIntegrationAnchors’ and ‘IntegrateData’ .Then split , and then transfer spatial data according to ingle-cell data.

eg.
#integrate
new.integrated <- IntegrateData(anchorset = new.anchors, dims = 1:30)
DefaultAssay(new.integrated) <- "integrated"
new.integrated <- ScaleData(new.integrated, verbose = FALSE)
# PCA
new.integrated <- RunPCA(new.integrated, npcs = 30, verbose = FALSE)
#DimPlot(new.integrated, reduction = "pca", group.by = "from")
new.integrated <- RunUMAP(new.integrated, reduction = "pca", dims = 1:30)
#split data
new.list <- SplitObject(new.integrated, split.by = "from")
new.query <- new.list[["pub"]]
new.spa<- new.list[["spa"]]
#transfer
new.anchors <- FindTransferAnchors(reference =new.query , query = new.spa, 
                                   dims = 1:30)
snRnaClPredictions = TransferData(
    anchorset=new.anchors, refdata=new.query$subclass, dims=1:30, 
)

**Comment by saketkc** [comment]
Integration and Transfer internally use the same set of anchors. You can try integrating -> clustering -> annotating based on markers, but in this case It makes more sense to use the RNA reference to "transfer" the celltypes to your spatial data.
