### ISSUE TITLE
Run SCTransform() again or not after extracting a subset?

### ISSUE THREAD

**Issue by longxiaxiao** [satijalab/seurat#6169]
Hi! Thanks for your attention.

I analysed my 2 samples according to this [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) and extracted a cluster from the origin object. 
`xx.cell.sct <- samples.combined[ , samples.combined$cell %in% c('xx cell')]`
I would like to subcluster this cluster(xx.cell.sct) and get more details. 

May i run SCTransform() **again** on this xx.cell.sct first? Or just RunPCA(), RunUMAP(), etc?
Thanks a lot!

**Comment by Gesmira** [comment]
Hi, if you are extracting the subset from an integrated object, you can rerun SCTransform() to rescale the data for the subsetted object, rerun the integration steps on the subsetted object, then continue with the clustering workflow.

**Comment by anaccsilva** [comment]
Hi, I would like to follow up on this question.
When you say rerun SCTransform(), do you mean the whole process? I am running SCT v2.

Should I set the assay to integrate first and run SCT() -> PCA -> SelectIntegrationFeatures -> PrepSCTIntegration -> Anchors and Integrate again?

Sorry for the question. I see that this recluster question shows up sometimes, but there is no vignette about it.

Thank you,
Ana
