### ISSUE TITLE
Adding Feature Level Meta Data

### ISSUE THREAD

**Issue by Camila-goclowski** [satijalab/seurat#6170]
I have been attempting to add feature (gene) level metadata from a GTF file and incorporate it into my Seurat object for downstream analysis. The documentation of the AddMetaData tool says to use brackets in order to access, and add to, feature-level metadata, but that has not worked. I have attempted a number of different routes, none of which seem to allow me to add my feature-level metadata. 

Please let me know if there is a different route to do so. Thank you.

**Comment by samuel-marsh** [comment]
Hi,

not member of dev team but hopefully can be helpful.  Can you provide example of what information you are trying to add and what code you have tried?  Are you trying to add alternate gene names?  Currently the meta.data slot in Seurat objects is per cell meta data.  There is not support for adding alternate gene names or IDs currently.

Best,
Sam

**Comment by torkencz** [comment]
Currently, the best way to add feature level metadata is via [[<- operator or via AddMetadata, as discussed here https://github.com/satijalab/seurat/issues/2855. We will work on making this easier in future releases.  You also have to check that your feature names overlap between the Seurat object and the gtf. Can reopen if more info is provided.
