### ISSUE TITLE
What is the difference between de novo UMAP vs UMAP obtained by RunUMAP() of the merged data without merging pca/spca?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6173]
Hi there, 

In the turorial for de novo UMAP visualization (https://satijalab.org/seurat/articles/multimodal_reference_mapping.html), following the merge of two Seurat objects, there is a merge of sPCA. 

Would you mind letting me know what is the difference between **(1)** this de novo UMAP vs **(2)** merge(setting merge.dr="ref.umap") vs **(3)** the UMAP generated by simply performing the clustering and RunUMAP of the merged object?

Also, it mentions sPCA is best suited for CITE-seq. If I only have scRNA-seq GEX data, or if I have only the ref has protein data but the query is GEX only, should I stick to merging PCA? 

Thank you for your advice!

**Comment by yuhanH** [comment]
HI, 
de novo UMAP `(1)` is the UMAP generated from query batch-corrected cell embeddings (`ref.spca`) and reference cell cell embeddings (`spca`).  This UMAP is similar to the `(3)` you described, which is built from batch corrected expression value not embeddings. 
`ref.umap` in your query data is the UMAP generated by reference UMAP model and parameters and the shape of this UMAP is very similar to the reference UMAP. 

SPCA is mainly used for compressing multi-modal information into one modality. When your reference is single-modality, you don't need to run SPCA.

**Comment by denvercal1234GitHub** [comment]
Thank you @yuhanH! So we should perform the workflow to generate de novo UMAP when we expect batch effect and we should simply merge the data (without batch correction) when we do not expect too much batch effect? 

Because when I merge the 2 dataset, there is not really a need to specify which data is ref and which is query. I just want to see whether certain cells of datataset A co-cluster with which cells from dataset B. In this case, which way should I do? 

Thank you so much!

**Comment by yuhanH** [comment]
hi @denvercal1234GitHub 
I would suggest you begin by analyzing your data in a simple way. When you observe clear batch effect, then you might want to use batch correction integration.

**Comment by denvercal1234GitHub** [comment]
Hi @yuhanH - But if I have 2 Seurat objects that were SCTransform-ed and RunPCA() as in normal SCTransform workflow, and I just do the following codes. How would the 2 approaches below differ in terms of what they can tell us? 

Also, I am a bit confused which code generate the `ref.umap` that is then used in the line `refquery[["spca"]] <- [merge](https://rdrr.io/r/base/merge.html)(reference[["spca"]], pbmc3k[["ref.spca"]])`.

Thank you so much for your patience!

APPROACH 1:

```
obj_1$id <- 'obj_1'
obj_2$id <- 'obj_2'
obj12 <- merge(obj_1, obj_2)
obj12[["pca"]] <- merge(obj_1[["pca"]], obj_2[["pca"]])
obj12 <- RunUMAP(obj12, reduction = 'pca', dims = 1:50)
DimPlot(obj12, group.by = 'id', shuffle = TRUE)
```

APPROACH 2:
```
obj_1$id <- 'obj_1'
obj_2$id <- 'obj_2'
obj12 <- merge(obj_1, obj_2)
obj12 <- RunPCA(obj12)
obj12 <- RunUMAP(obj12, reduction = 'pca', dims = 1:50)
DimPlot(obj12, group.by = 'id', shuffle = TRUE)
```

**Comment by yuhanH** [comment]
hi @denvercal1234GitHub 
Approach 1 and 2 are different, but the batch effects are correct for both of them. In approach 1, it is a de novo UMAP calculated from batch corrected embeddings (spca). In approach2, the shape of query UMAP will be very similar to the reference UMAP. 

For example, in this [pbmc mapping vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html), this umap (query + reference) is generated by approach1.
![image](https://user-images.githubusercontent.com/29529544/184982831-74297c49-6d95-4efa-8417-3e5642112e5d.png)

These query UMAPs are `ref.umap` and the cell type structure is very similar to the original reference UMAP. 
![image](https://user-images.githubusercontent.com/29529544/184983390-6c918c11-d36d-4372-85f8-805eba028881.png)

For approach3, it depends on how you do the integration. In the PBMC mapping vignette, we only corrected embeddings not gene expression, so approach3 will generate a PCA/UMAP that cells are separately by the biological and technologies difference.
