### ISSUE TITLE
interactive tool to manually draw contours on sections for spatial transcriptomics

### ISSUE THREAD

**Issue by rmc0106** [satijalab/seurat#6175]
Hi!
I was looking for an interactive tool that allows the user to manually draw (e.g. with a mouse or with a tablet) contours on a section in spatial transcriptomics, so in this way the user will be able to subset the desired spots (falling inside the contour) and perform downstream analysis only on those. This would be very helpful, if cells of interest are known based on their anatomic location. 

I found that a tool with these features is available for Scanpy in the Squidpy package and it is called Napari:
https://squidpy.readthedocs.io/en/stable/external_tutorials/tutorial_napari.html 
I would like to ask you if anything similar is available for Seurat, because I will be happy to try.

Currently, I am trying to analyze slide-seq data from some test sections.

Thanks

**Comment by rsatija** [comment]
This is a really nice feature of Napari, but unfortunately not something we can currently implement in R/Seurat
