### ISSUE TITLE
Is it correct to diffenrt set of genes to be integrated using features.to.integrate, while I have normalized only 2000 genes for integration analysis?

### ISSUE THREAD

**Issue by Sahu-Mousumi** [satijalab/seurat#6176]
Hi!
I have a quick question.

I have normalized the gene expression prior to data integration and selected 2000 genes (default no.) as variable features.

I am interested in few genes and thus I am providing those in the integration step using features.to.integrate. Is it correct? 

Because genes of my interest might be in the list 2000 variable features. 

Thank you!

**Comment by timoast** [comment]
You can certainly use the `IntegrateData()` function to correct a different set of genes to those used when finding anchors. However, keep in mind that for many downstream tasks (for example, differential expression or data visualization) you will need to use the original uncorrected data
