### ISSUE TITLE
About Seurat Object Project name -- Issue with CreateSeuratObject() "project =____ "

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6177]
Hello. May I ask what did I do wrong? I loaded a .csv counts matrix using below code. When I created the seurat object, I specified project = "PCD", but the generated VlnPlot used the first column (cell ID) in the counts matrix as project name instead.  

```
#Read scRNAseq expression data
PCD.data <- read.delim(file = "2022-Datafrom-Pediatric-Coeliac-Disease/PBMC-Pediatric-Coeliac-Disease/Supplementary_Table_8_scRNAseq_rawcounts.csv", sep = ",", row.names = 1, as.is=T) 

PCD.data
```

![image](https://user-images.githubusercontent.com/68268222/178548741-7ce0fd20-bdda-4702-9ce7-5b896bddcfdd.png)

```
#Create Seurat object
PCD <- CreateSeuratObject(counts = PCD.data, project = "PCD", min.cells = 3, min.features = 200)
#Standard pre-processing workflow
PCD[["percent.mt"]] <- PercentageFeatureSet(PCD, pattern = "^MT-")
PCD[["percent.rb"]] <- PercentageFeatureSet(PCD, pattern = "^RP[SL]") #NKD <- NKD[!grepl("^MT-", rownames(NKD)), ]
PCD[["percent.hb"]] <- PercentageFeatureSet(PCD, pattern = "^HB") # For 10% hemoglobin: https://insight.jci.org/articles/view/135678#SEC4
VlnPlot(PCD, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
```

![image](https://user-images.githubusercontent.com/68268222/178548925-2d3e1132-b7ac-4ac4-ac2b-0a6c490be8ea.png)

**Comment by mojaveazure** [comment]
The `names.field` and `names.delim` parameters to [`CreateSeuratObject`](https://mojaveazure.github.io/seurat-object/reference/CreateSeuratObject.html) are used to set the initial identity, not the project. If you have too many values from this process, then we use the project. You can change this by setting the idents to your project after you make your object

```R
Idents(PCD) <- Project(PCD)
```
