### ISSUE TITLE
creating a new smaller Seurat object from a subset of the assays in an existing Seurat object

### ISSUE THREAD

**Issue by msherafatian** [satijalab/seurat#6180]
Hi
There are a few situation that a Seurat object needs to be split (converted) into smaller Seurat objects: 

- As we run different pipelines on a Seurat objects 
- Merging it with other Seurat objects
- Multiomics objects

In these instances it is useful to be able to create a new Seurat object using only a subset of assays available in the old one.

**Comment by mojaveazure** [comment]
Please see [`DietSeurat`](https://satijalab.org/seurat/reference/dietseurat)
