### ISSUE TITLE
Installation problem  on r-base 4.2.1-1.2204.0

### ISSUE THREAD

**Issue by Fdm8610** [satijalab/seurat#6181]
I am not able to install Seurat packages on r 4.2.1-1.2204.0 in my ubuntu 22.04 terminal.
This is the message I get.

g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RcppEigen.so RcppEigen.o RcppExports.o fastLm.o init.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -llapack: No such file or directory
/usr/bin/ld: cannot find -lblas: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: RcppEigen.so] Error 1
ERROR: compilation failed for package ‘RcppEigen’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/RcppEigen’
ERROR: dependency ‘RcppEigen’ is not available for package ‘RSpectra’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/RSpectra’
ERROR: dependency ‘sitmo’ is not available for package ‘dqrng’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/dqrng’
ERROR: dependency ‘curl’ is not available for package ‘httr’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/httr’
ERROR: dependency ‘png’ is not available for package ‘reticulate’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/reticulate’
ERROR: dependency ‘RcppArmadillo’ is not available for package ‘sctransform’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/sctransform’
ERROR: dependencies ‘rgeos’, ‘RcppEigen’ are not available for package ‘SeuratObject’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/SeuratObject’
ERROR: dependencies ‘reticulate’, ‘igraph’ are not available for package ‘leiden’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/leiden’
ERROR: dependency ‘httr’ is not available for package ‘plotly’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/plotly’
ERROR: dependencies ‘RSpectra’, ‘irlba’, ‘dqrng’ are not available for package ‘uwot’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/uwot’
ERROR: dependencies ‘httr’, ‘igraph’, ‘irlba’, ‘leiden’, ‘plotly’, ‘png’, ‘reticulate’, ‘Rtsne’, ‘sctransform’, ‘SeuratObject’, ‘uwot’, ‘RcppEigen’ are not available for package ‘Seurat’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpjHz0Bd/downloaded_packages’
There were 19 warnings (use warnings() to see them)

How can I solve this problem?

Thank you

**Comment by Stfort52** [comment]
Seems like you have missing packages. I suggest you consult [here](https://stackoverflow.com/questions/25065113/blas-lapack-not-installed-how-to-install-it).

**Comment by Fdm8610** [comment]
I reinstalled R latest version 4.2.1
Then 
install.packages("Seurat")

and again


ERROR: dependency ‘RcppArmadillo’ is not available for package ‘sctransform’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/sctransform’
ERROR: dependency ‘httr’ is not available for package ‘plotly’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/plotly’
ERROR: dependencies ‘httr’, ‘igraph’, ‘irlba’, ‘leiden’, ‘plotly’, ‘png’, ‘reticulate’, ‘Rtsne’, ‘sctransform’, ‘SeuratObject’, ‘uwot’, ‘RcppEigen’ are not available for package ‘Seurat’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpspdFBk/downloaded_packages’
There were 19 warnings (use warnings() to see them)

What should I do to make Seurat working? 

Thank you

**Comment by Fdm8610** [comment]
I have now 16 warnings

ERROR: dependencies ‘RSpectra’, ‘irlba’, ‘dqrng’ are not available for package ‘uwot’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/uwot’
ERROR: dependencies ‘igraph’, ‘irlba’, ‘leiden’, ‘png’, ‘reticulate’, ‘Rtsne’, ‘sctransform’, ‘SeuratObject’, ‘uwot’, ‘RcppEigen’ are not available for package ‘Seurat’
* removing ‘/local/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.2/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpoSBIPV/downloaded_packages’
There were 16 warnings (use warnings() to see them)

**Comment by Stfort52** [comment]
Are those all of the warning/error messages?

> Seems like you have missing packages. I suggest you consult [here](https://stackoverflow.com/questions/25065113/blas-lapack-not-installed-how-to-install-it).

Also, have you done this?

**Comment by Fdm8610** [comment]
> Are those all of the warning/error messages?
> 
> > Seems like you have missing packages. I suggest you consult [here](https://stackoverflow.com/questions/25065113/blas-lapack-not-installed-how-to-install-it).
> 
> Also, have you done this?

yes, those are all errors.

I have tried to apt-get install the missing packages but it doesn't work. In example

sudo apt-get install SeuratObject
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package SeuratObject

**Comment by Stfort52** [comment]
> 
> I have tried to apt-get install the missing packages but it doesn't work. In example
> 
> sudo apt-get install SeuratObject Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package SeuratObject

So, you have to perform two things here.

1. install the missing libraries with ubuntu's package manager `apt`(by using `apt-get install ...)`.
2. install Seurat via CRAN(a.k.a. with `install.packages(...)`.

Here, you have to distinguish between case 1 and case 2. 

> I am not able to install Seurat packages on r 4.2.1-1.2204.0 in my ubuntu 22.04 terminal.
> This is the message I get.
> 
> g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RcppEigen.so RcppEigen.o RcppExports.o fastLm.o init.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
> /usr/bin/ld: cannot find -llapack: No such file or directory
> /usr/bin/ld: cannot find -lblas: No such file or directory
> collect2: error: ld returned 1 exit status
> make: *** [/usr/share/R/share/make/shlib.mk:10: RcppEigen.so] Error 1
> ERROR: compilation failed for package ‘RcppEigen’

Here, you can see that `/usr/bin/ld` is reporting that it's missing `-llapack`. In other words, when `install.packages(...)` tried to install `RcppEigen` which is a dependency of `Seurat`, it tried to compile and link `RcppEigen` correctly but failed due to the lack of `lapack` library. This is a library for linear algebra, and it's not only used for R package `RcppEigen` but also many different Non-R applications. Therefore, you should install it via `apt-get`. The same thing goes for `-lblas`.
To install these packages, consult the link posted above. 

On the other hand, `SeuratObject` is a instance of R package. Therefore, it should be installed by `install.packages(...)`. (However in this case you don't need to install `SeuratObject` manaually because installing `Seurat` will also install `SeuratObject`)

**Comment by Fdm8610** [comment]
Thank you, solved!
