### ISSUE TITLE
vars.to.regress vs just Normalizing by Batch

### ISSUE THREAD

**Issue by carversh** [satijalab/seurat#6184]
Hi,

I am trying to remove batch effects not via taking the residuals of a regression but by normalizing each expression set based on batch number. Is there a fast may to do this in Seurat or do I have to do this manually?

**Comment by longmanz** [comment]
Hi, 
You may divide the seurat obj into subsets based on the batch number and then use lapply() to perform the normalization for each subset. 
`obj.list <- SplitObject(obj, split.by = "batch_num")`
`obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})`
