### ISSUE TITLE
Conflicting guidelines on how to set variable features for SCTransform-ed merged object?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6185]
In issue #5183 #5135, @yuhanH & @mhkowalski mentioned setting `VariableFeatures(object[["SCT"]]) <- rownames(object[["SCT"]]@scale.data)` in the merging workflow of 2 objects that were SCTransform-ed (v2) separately. 

In issue #5738, @saketkc however suggested to made a list of the 2 objects (which were each SCTransform(v2) separately) then perform SelectIntegrationFeatures of the list -> variable_genes. After that, set VariableFeatures(merged object) <- variable_genes. Finally, we can now perform RunPCA, etc for clustering analysis using the merged object.

Would anyone mind clarifying when to use which approach? 

And, now that the merged object's SCT Assay has 2 SCT models, which model to use for RunPCA etc and how to specify it? Because as mentioned in issue #6182, doing FindTransferAnchors() gave me an error for having 2 SCT ref models and it asked to provide a ref assay with 1 model.

Thank you so much!

**Comment by saketkc** [comment]
`VariableFeatures(object[["SCT"]]) <- rownames(object[["SCT"]]@scale.data)` => This takes the union of variable features (so a maximum of 4000 features might be selcted).
`SelectIntegrationFeatures` => This ranks features by the number of datasets they are deemed variable in and selects 2000 of them (by default). 

There is no conflict, as these are two different ways of defining what is "variable" across datasets. `RunPCA` does not depend on SCT models as it will use the `scale.data` slot. For doing `FindTransferAnchors()`, with multiple models you could set `recompute.residuals=FALSE` to use the query SCT residuals.
