### ISSUE TITLE
Subset based on partial identity of columns names

### ISSUE THREAD

**Issue by Fdm8610** [satijalab/seurat#6186]
Hi

I would like to subset my Seurat object based on partial identity of columns name.
In example, my columns are named aRCG1_AAATATATATATTA, aRCG1_TTTTATATTATATTTTA, aRCG2_AATTTTTTTCCCACT, aRCG2_AAAAAAAAAA, aRCG3_TTTTTTTTTTTT....

Is it possible to subset columns based on the presence of  "aRCG1_" in the title?

Thank you!!!

**Comment by Stfort52** [comment]
Just subset the Seurat object as if you are subsetting a data.frame. 

For example, given a seurat object `so`, 
```R
so[,so %>% colnames %>% str_detect("^aRCG1_")]
```
(...provided that you have `magrittr` and `stringr`.)

**Comment by Fdm8610** [comment]
THANK YOU
