### ISSUE TITLE
RenameIdents() not saving

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6187]
I'm trying to figure out which resolution to use for my clustering.  For each resolution I run FindAllMarkers() then rename the idents. But when my loop advances, the previous changes are lost.  Here's my code, which is not elegant but works:
```
res <- c(0.1, 0.3, 0.5, 0.7, 0.9, 1.0)
gene.list <- FindClusters(gene.list, resolution = res)

for (i in 1:length(res)){
    current_res <- paste0("RNA_snn_res.", res[i])
    
    Idents(gene.list) <- current_res
    
    gene.list@misc$current_res <- FindAllMarkers(gene.list,  only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
    
    names(gene.list@misc)[names(gene.list@misc) == "current_res"] <-   paste0(names(gene.list), ".", res[i], ".resolution")
    
    #**Rename the Idents to be the top marker for that cluster**
    temp <- paste0(names(gene.list, ".", res[i], ".resolution")
    markers <- as.data.frame(gene.list@misc[names(gene.list@misc) == temp]) 
    names(markers) <- str_sub(names(markers), nchar(temp) + 2)
    markers <- markers %>% group_by(cluster) %>% slice_max(n = 1, order_by = avg_log2FC)
    markers <- markers$gene
    names(markers) <- levels(gene.list)
    gene.list <- RenameIdents(gene.list, markers)
  }
```

When I step through the code it does what I want.  But when it advances to the next resolution the changes for the previous resolution are lost.  Any insight as to why RenameIdents doesn't save once the active ident is changed?  Also, any ideas on how to simplify this code would be appreciated.

Thanks,
Stacy

**Comment by timoast** [comment]
Here you rename the idents, but then at the start of each loop change the idents to something else, so the renamed idents would be lost. You probably want to save the renamed idents by adding to metadata or something, eg `obj$renamed <- Idents(obj)`

**Comment by stacygenovese** [comment]
I understand that...why would RenameIdents not store the changes simply because the active ident was changed?  It seems like renaming clusters with the top markers for determining which resolution is appropriate is something many people would want to do.
