### ISSUE TITLE
Seurat Object loading as 'character' from RData file

### ISSUE THREAD

**Issue by LaviCor** [satijalab/seurat#6188]
Hello all,

I recently downloaded data (in the form of an existing seurat object) from a paper from dryad data repository.

the file type was listed to be RData, so i tried to load it into R using the 'load' function.
however when trying to use any of seurat functions, it says it cannot do so as the object is of "character" type.
using "typeof" returned that the type of the object was indeed "character".

However, in the data window, the object was listed to be "Large Seurat".
In addition, when inspecting the object structure, everything looked fine, save for the type of the first row (the object as a whole?), which was listed to be a S4(Seurat::Seurat), instead of the S4(SeuratObject::Seurat) which is shown for regular working data I have.
![image](https://user-images.githubusercontent.com/101585799/178992395-96623fa1-890b-4d5c-ae10-f5bb12bde951.png)
vs
![image](https://user-images.githubusercontent.com/101585799/178992473-58a8e2ba-6ca6-4055-a1bb-9d4dc0bf0040.png)

Also, when downloading the file, it was listed as just "file" type (not RData), and the file name had no extension.

I have no idea how to solve this issue, so any help on how to properly load or convert the data to a working seurat object would be much appreciated.

**Comment by timoast** [comment]
Not sure what the issue is exactly but if you provide the link to the dryad repository and the file I can take a look.

**Comment by LaviCor** [comment]
Thanks for the reply!
Sorry about that, was sure I added it.
https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.t4b8gtj34

Paper is https://www.nature.com/articles/s42003-021-02810-x

**Comment by timoast** [comment]
It worked fine for me. Running this code:

```r
library(Seurat)
load("~/doi_10.5061_dryad.t4b8gtj34__v7/myo_slim_seurat_v1-1.RData")
myo.slim.seurat
```
```
An object of class Seurat 
28253 features across 84383 samples within 1 assay 
Active assay: RNA (28253 features, 2000 variable features)
 1 dimensional reduction calculated: phate_harmony
```

The file is a zip file containing a folder with different Rdata files and a readme file. Make sure the zip file downloads completely and you unzip it before accessing the files.
