### ISSUE TITLE
Unable to find/plot a gene identified as a cluster marker

### ISSUE THREAD

**Issue by ishwarvh** [satijalab/seurat#6192]
Hello,

I have idenitfied the markers genes for the predicted clusters. I am now trying to plot the top10 marker genes per cluster using a featureplot. 

However, I am unable to find some of these genes in in "data", "scale.data" or "counts" slots.
Here is the warning I receive when plotting:
`Warning message:
In FetchData.Seurat(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found:  Jag1`

Has anyone come across this before or have any idea why this might be. 
I was not able to find any posts/issues related to this in the closed issues.

Thank you,
Ishwar

**Comment by torkencz** [comment]
It could be that you only scaled variable features instead of all genes. 

all.genes <- rownames(object)
object<- ScaleData(object, features = all.genes)

**Comment by ishwarvh** [comment]
Thank you for your reply. That was the first thing I checked. 
I used all genes for `ScaleData`

**Comment by torkencz** [comment]
In that case I would check if it is in the counts, normalized data etc. via GetAssayData or FetchData. Unfortunately, I cannot give better advice since I don't have the data you are looking at.
