### ISSUE TITLE
Is CellScatter() a scatter of cells ...or a scatter of features/genes?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6199]
Hello. I calculated `AverageExpression()` of all clusters (0,1, 2, 3, 4). I thought `AverageExpression() `calculates the average expression of all genes/features? And that `CellScatter()` visualizes all those cells? But when I set the `features` to 4 genes, it also only shows 4 dots on the plot. 
 
Is `CellScatter()` a scatter of cells ...or a scatter of features/genes?

My major question is: **How to make a scatter plot of cells/clusters' average expression for only a list of genes?** 

I have a cell type with 5 clusters. I want to create a **cell scatter** of average expression (of a list of genes) to compare cluster 5's average expression on healthy (HC) and dengue (DNV).

`CellScatter(cluster.averages, cell1 = "HC", cell2 = "DNV")
`
![image](https://user-images.githubusercontent.com/68268222/179348717-4a8fd01e-f610-43c1-8894-3442769ecd04.png)

`CellScatter(cluster.averages, cell1 = "HC", cell2 = "DNV", features = c("CD4", "CD8A", "CD8B", "GNLY"))
`
![image](https://user-images.githubusercontent.com/68268222/179348760-751b0280-c0bf-4dd4-bc05-12ec8e662519.png)

**Comment by saketkc** [comment]
`CellScatter` plots the expression of all features by default given two cells. What you want to could be done by operating on an assay with average values:

```r
avg_assay <- AverageExpression(object, group.by="my_label", slot="data", return.seurat=TRUE)
CellScatter(avg_assay, cells1="cluster1", cells2="cluster2", features=c("gene1", "gene2"))
```
