### ISSUE TITLE
BuildClusterTree with canonical vectors

### ISSUE THREAD

**Issue by romanhaa** [satijalab/seurat#620]
I was wondering if it was possible to run the `BuildClusterTree()` function using a specified number of canonical vectors, just like you can take principal components instead of genes?

That would be great because the tree doesn't correlate too much with the CCA-based tSNE/UMAP projections.

Thanks!

**Comment by satijalab** [comment]
Unfortunately we don't support this. You can easily extract the vectors with GetCellEmbeddings and generate your own dendrogram/tree
