### ISSUE TITLE
Seurat functions taking forever to execute when running using rpy2 

### ISSUE THREAD

**Issue by ankur26197-acog** [satijalab/seurat#6204]
I am implementing general steps of scRNA study like QC, integration, clustering and cell annotation on a dataset. I am using Seurat to implement each of these functions and anndata2ri and rpy2 for interchangeability of anndata to SCE object. I basically source all my R scripts using r.source from robjects module and call them from my notebook. However when trying to run several Seurat functions, I find that each of the basic steps like normalising data or finding variable features takes hours for a single sample but they execute smoothly when I try running my code using magic functions described here https://github.com/theislab/anndata2ri.

Steps to reproduce-

- Load a scRNA dataset in anndata.

- Write functions for analysis like QC, normalisation, integration, clustering, etc. in R

- Source each of these function using r from rpy2.robjects module and call them from a notebook/python file. Make sure all these functions calling the respective R functions are in the same notebook/python file. Pass the same anndata object modified after every function call.

- Also implement the previous step using magic functions

In ideal case after running QC if you try integration using https://satijalab.org/seurat/reference/integratedata , you will see that each of the basic steps provided there take hours for executing while it runs smoothly using the magic functions.

`Ubuntu 20.04` `Python version 3.8.8` `anndata version 0.8.0` `anndata2ri version 1.0.3` `rpy version 3.2.7` `R version 4.2.0`

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
