### ISSUE TITLE
Integration SCTransform(v2) workflow: How to solve Error in scale.data[anchor.features, ] : subscript out of bounds?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6205]
Hi there, 

In issues #3085 #5183 , @yuhanH seemed to suggest: 

STEP 1: Merge 2 Seurat objects (each was already SCTransform-ed individually with regressing out any variable of interest), setting merge.data = FALSE. 
STEP 2: `SplitObject()` to create a list containing these 2 Seurat objects with `split.by = a batch variable`. 
STEP 3: Rerun `SCTransform()` on each of these objects obtained from the list on its **RNA Assay.** individually to obtain the variable features without rescaling the object.
STEP 4: run RunPCA, FindNeighbors, etc. as shown in the tutorial for each object individually (https://satijalab.org/seurat/articles/sctransform_v2_vignette.html)
STEP 5: Combine the two objects back as a list for integration according to the tutorial. 

**(Question 1):** For rerunning SCTransform() (STEP 3), do we set `do.scale=FALSE` and `do.center=TRUE` and no need to re-regressing out variables? I thought so because each object before merging had already been `SCTransform(do.scale=T, do.center = T, with regressing out percent.mt and cell cycle genes)`. 

The reason I asked is because when I rerun SCTransform(STEP 3 with `do.scale=F, do.center=T` without regressing any variables), the "new" nCount_SCT and nFeature_SCT of the objects were different from the nCount_SCT and nFeature_SCT values that were originally obtained by running SCTransform() before merging. 

**(Question 2):** According to #5183, If I merge the objects (individually SCTransform-ed with scale.data=T prior to merge), setting `merge.data = T`, I will not need to rescale the merged object, right? 

**(Question 3):** Doing the steps above or just simply SCTransform() each object individually before combining them into a list to run `PrepSCTIntegration()`, I still ran into an error of `Error in scale.data[anchor.features, ]: subscript out of bounds` as reported by #5408. 

Would you mind advising me on how to proceed? 

Thank you very much for your help.

**Comment by yuhanH** [comment]
HI @denvercal1234GitHub 
**For question1**, we don't suggest you change `do.scale` and `do.center` unless you have solid reasons to do that. Typically, if you have removed cells with a high percentage of mitochondria, you don't need to regress out "percent.mt". 
You can find many discussions about cell cycle gene regression. 

**For question2**,  you are right. You don't need to rescale the merged object. If you need to get residuals for new genes, you can use `GetResidual()` in the merged object. 

**For question3**, it seems that your anchor.features don't exist in all individual object **RNA assay**.  `SelectIntegrationFeatures` can be used to select anchor.features.

`features <- SelectIntegrationFeatures(object.list = object.list, nfeatures = 3000)`

**Comment by denvercal1234GitHub** [comment]
Thank you @yuhanH for your response. 

Would you mind elaborating a bit on the `do.scale` and `do.center` conditions for the two cases below? 

**Case 1.** In merging SCTransform(v2) workflow, I do the following steps. Would you mind letting me know whether the setting of `do.scale` and `do.center` in Steps 2 and 5 here make sense?

 1. CreateSeuratObject() for each dataset
 2. SCTransform(**do.scale=FALSE, do.center=FALSE**, method = "glmGamPoi", vst.flavor = "v2", return.only.var.genes = F) to allow calculating cell cycle scores on normalize data
 3. CellCycleScoring() on the SCT Assay for each object which has only been normalized and not yet scaled
 4. DefaultAssay() <- 'RNA' for each object
 5. SCTransform(vars.to.regress = c("percent.mt", "CC.Difference"), **do.scale=TRUE, do.center=TRUE**, vst.flavor = "v2") to now actually scale and center the data
 6. merge(merge.data = T) the two objects --- _merged_obj_
 7. Make a list of the 2 objects --- _the_list_
 8. SelectIntegrationFeatures(the_list, assay = c("SCT", "SCT"), nfeatures = 3000, fvf.nfeatures=3000) to select the variable features from the 2 objects --- _var_both_
 9.  VariableFeatures(merged_obj) <- _var_both_
 10. DefaultAssay(merged_obj) <- 'SCT' of merged_obj
 11. RunPCA(assay = 'SCT', features = var_both) of merged_obj
 12. DefaultAssay(merged_obj) <- 'SCT' of merged_obj
 13. RunUMAP(reduction = "pca", return.model=T) of merged_obj

**Case 2.** If the two individual Seurat objects have already been SCTransform-ed (setting `do.scale` = T and `do.center` = T), then when I make them into a list in order to redo SCTransform(), I should not rescale, which means I should set `do.scale` = F and `do.center` = F, right?

**Comment by yuhanH** [comment]
Hi,@denvercal1234GitHub  
when you make them into a list to run SCTransform, these two objects will be running SCTransform separately. You don't need to set `do.scale` and `do.center`.

**Comment by matasV99** [comment]
Hi, running into this same issue when trying to integrated two seurat objects each with different samples of a condition. Any clarity on a sample code to solve this would be very useful.
