### ISSUE TITLE
Highlight Cell Barcodes and Display Clusters at the same time

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#6207]
Hello,

I would like to plot specific cell barcodes from a list on my UMAP with a unique color but also display clusters called by Seurat at the same time.

I saw that Seurat can highlight specific cell barcodes, but it greys out the rest of the UMAP: [(https://github.com/satijalab/seurat/issues/2371)]

Is there a way to do this using DimPlot?

Thank you again!

**Comment by torkencz** [comment]
Hi, I think that if you specify a set of barcodes via "cells.highlight" in DimPlot and also have your cluster info under Idents in your object you can set label=T and have both types of info on your plot.

**Comment by atly2000** [comment]
Thank you. I plotted my UMAP like this:
DimPlot(D1_so, reduction = 'umap',label = TRUE, cells.highlight = barcode_list, cols.highlight = "blue4", order = TRUE ),

but I cannot see the colors of my clusters. I can only see the numbers labelling my clusters and the colored dots representing each barcode from my list. 
Is there a way to view both the colors of the clusters and the highlighted cells at the same time?

**Comment by atly2000** [comment]
> Hi, I think that if you specify a set of barcodes via "cells.highlight" in DimPlot and also have your cluster info under Idents in your object you can set label=T and have both types of info on your plot.

Thank you. I plotted my UMAP like this:
DimPlot(D1_so, reduction = 'umap',label = TRUE, cells.highlight = barcode_list, cols.highlight = "blue4", order = TRUE ),

but I cannot see the colors of my clusters. I can only see the numbers labelling my clusters and the colored dots representing each barcode from my list.
Is there a way to view both the colors of the clusters and the highlighted cells at the same time?
