### ISSUE TITLE
How to create Seuratobject using 3 samples

### ISSUE THREAD

**Issue by mayurdoke6** [satijalab/seurat#6209]
Hello,

I have total of 6 scRNA seq data samples which can be divided into group A and B.  I would like to create Seuratobject A and B by combining 3 samples counts data for each group. Eventually I would like to see UMAP with colored by group A and B.  I tried many ways but failed. I can see UMAP with 6 colors representing 6 samples. Could you please help me with this issue?  
Please find below my code for your reference-

A1.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-1/filtered_feature_bc_matrix")
A2.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-2/filtered_feature_bc_matrix")
A3.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-3/filtered_feature_bc_matrix")
A1 <- CreateSeuratObject(counts = A1.data, 
                              project = "A7"
)
A2 <- CreateSeuratObject(counts = A2.data, 
                              project = "A7"
)
A3 <- CreateSeuratObject(counts = A3.data, 
                              project = "A7"
)

head(x = colnames(x = A1))
A1 <- RenameCells(object = A1, add.cell.id = "A7")
head(x = colnames(x = A1))
head(x = colnames(x = A2))
A7 <- RenameCells(object = A2, add.cell.id = "A7")
head(x = colnames(x = A7))
head(x = colnames(x = A3))
A3 <- RenameCells(object = A3, add.cell.id = "A7")
head(x = colnames(x = A3))
A1[["percent.mt"]] <- PercentageFeatureSet(object = A1, pattern = "^MT-")
A2[["percent.mt"]] <- PercentageFeatureSet(object = A2, pattern = "^MT-")
A3[["percent.mt"]] <- PercentageFeatureSet(object = A3, pattern = "^MT-")
p1 <- VlnPlot(object = A1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
p2 <- VlnPlot(object = A2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
p3 <- VlnPlot(object = A3, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
CombinePlots(plots = list(p1, p2, p3), ncol =1)
p4 <- FeatureScatter(object = A1, feature1 = "nCount_RNA", feature2 = "percent.mt")
p5 <- FeatureScatter(object = A1, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
p6 <- FeatureScatter(object = A2, feature1 = "nCount_RNA", feature2 = "percent.mt")
p7 <- FeatureScatter(object = A2, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
p8 <- FeatureScatter(object = A3, feature1 = "nCount_RNA", feature2 = "percent.mt")
p9 <- FeatureScatter(object = A3, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(p4, p5, p6, p7, p8, p9), ncol =2)
A1 <- subset(x = A1, subset = nFeature_RNA > 200 & nFeature_RNA < 8000 & percent.mt < 20)
A2 <- subset(x = A2, subset = nFeature_RNA > 200 & nFeature_RNA < 8000 & percent.mt < 20)
A3 <- subset(x = A3, subset = nFeature_RNA > 200 & nFeature_RNA < 8000 & percent.mt < 20)
p10 <- VlnPlot(object = A1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
p11 <- VlnPlot(object = A2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
p12 <- VlnPlot(object = A3, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
CombinePlots(plots = list(p10, p11, p12), ncol =1)
p13 <- FeatureScatter(object = A1, feature1 = "nCount_RNA", feature2 = "percent.mt")
p14 <- FeatureScatter(object = A1, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
p15 <- FeatureScatter(object = A2, feature1 = "nCount_RNA", feature2 = "percent.mt")
p16 <- FeatureScatter(object = A2, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
p17 <- FeatureScatter(object = A3, feature1 = "nCount_RNA", feature2 = "percent.mt")
p18 <- FeatureScatter(object = A3, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(p13, p14, p15, p16, p17, p18), ncol =2)

**Comment by jarchana09** [comment]
Hello. Not a member of Seurat team, but perhaps this may be helpful.
You could add a meta.data column called group for each of the 6 scRNA seq objects, prior to merging/integration. Then, when you plot a UMAP and set the parameter `split.by = "group"` in DimPlot, it should color by the two groups.
Hope this helps. Thanks

**Comment by mayurdoke6** [comment]
> Hello. Not a member of Seurat team, but perhaps this may be helpful. You could add a meta.data column called group for each of the 6 scRNA seq objects, prior to merging/integration. Then, when you plot a UMAP and set the parameter `group.by = "group"` in DimPlot, it should color by the two groups, similar to the first figure in https://satijalab.org/seurat/articles/integration_introduction.html Hope this helps. Thanks

@jarchana09 Thank you very much for reply. I will try that way and let you know.

**Comment by jarchana09** [comment]
Hello @mayurdoke6. You could try this:
#Your code with modifications to include 6 samples
```
A1.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-1/filtered_feature_bc_matrix")
A2.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-2/filtered_feature_bc_matrix")
A3.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-3/filtered_feature_bc_matrix")
A4.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-4/filtered_feature_bc_matrix")
A5.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-5/filtered_feature_bc_matrix")
A6.data <-Read10X(data.dir = "C:/Users/mad1188/Box/Sequencing Data/cellranger_count/-A-7-6/filtered_feature_bc_matrix")

A1 <- CreateSeuratObject(counts = A1.data, project = "A7")
A2 <- CreateSeuratObject(counts = A2.data, project = "A7")
A3 <- CreateSeuratObject(counts = A3.data, project = "A7")
A4 <- CreateSeuratObject(counts = A4.data, project = "A7")
A5 <- CreateSeuratObject(counts = A5.data, project = "A7")
A6 <- CreateSeuratObject(counts = A6.data, project = "A7")
```

#Adding group information, assuming A1-3 belong to group A and A4-6 to group B
```
A1$group <- "A"
A2$group <- "A"
A3$group <- "A" 

A4$group <- "B"
A5$group <- "B"
A6$group <- "B"
```
#Assuming you have done QC, and either merged or integrated the samples, performed clustering, etc. then you visualize the UMAP of the merged/integrated Seurat object
```
DimPlot(combined.seu, reduction = "umap", group.by = "group") 
```
#This should ideally generate a combined UMAP that is colored one color per group as in first figure in [https://satijalab.org/seurat/articles/integration_introduction.html](https://satijalab.org/seurat/articles/integration_introduction.html)
```
#If you want to visualize the 2 groups separately
DimPlot(combined.seu, reduction = "umap", split.by = "group") 
```
#This will generate a similar representation as in  [https://satijalab.org/seurat/articles/integration_introduction.html](https://satijalab.org/seurat/articles/integration_introduction.html) where split.by is used

I am not sure if this is what you were aiming for, but hope this helps.

**Comment by mayurdoke6** [comment]
@jarchana09  Thank you so much for your help. It worked perfectly.

**Comment by mayurdoke6** [comment]
Thank you so much @jarchana09 for your help. I deeply appreciate it.

**Comment by jarchana09** [comment]
Thank you @mayurdoke6 . Glad it was helpful.
