### ISSUE TITLE
ScaleData error

### ISSUE THREAD

**Issue by chenlingantelope** [satijalab/seurat#621]
Everything before (filter cells, normalize and find variable genes run without error  but ScaleData throws an error. 
> pbmc <- ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito"))
> Regressing out: nUMI, percent.mito
>   |======================================================================| 100%Error in { : 
>   task 1 failed - "NA/NaN/Inf in foreign function call (arg 1)"
> In addition: Warning message:
> In as.vector(y) : closing unused connection 3 (<-localhost:11607)
>

**Comment by evolvedmicrobe** [comment]
Do any entries for the data in the pbmc object or `nUMI` or `percent.mito` contain NA values? If so, they can not be used in a regression and will have to be removed beforehand.

**Comment by chenlingantelope** [comment]
No none of them contain NA values.

**Comment by evolvedmicrobe** [comment]
R is certainly detecting that you are passing in a non-finite value to some `.Call` code, which indicates you are creating such a value at some point, per the code here:

https://github.com/wch/r-source/blob/6f74cb68c2238bcedab37da09b6c5d7fb56dfaea/src/main/dotcode.c#L1600

Note that `NA` values can occasionally be created when converting from a string type to a factor type.  Can you run the following code and let me know what its result is?

    latent.data <- FetchData(object = pmbc, vars.all = c("nUMI", "percent.mito"))
    genes.regress <- rownames(pbmc@data)
    data.use <- pbmc@data[genes.regress, , drop = FALSE];
    print(any(!is.finite(data.use) | any(!is.finite(latent.data)))

**Comment by chenlingantelope** [comment]
Awesome I think I figured out what the issue is! There are 6325 cells with nUMI 1e+308 due to some error in the input dataframe...  Thanks so much!!!
