### ISSUE TITLE
Using ggtitle() on CellScatter removes the correlation score

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6210]
Hello. Is there any way I can retain the correlation score if I add a title on CellScatter plot? I checked the parameters in CellScatter() function but it seems it doesn't have a built-in parameter to add a title, so I used ggtitle, but doing so omits the correlation score (0.95) from the plot. 

May I also ask how to show the gene names of the dots on the plot?

Thank you!

**> CellScatter(cluster.averages, cell1 = "Healthy", cell2 = "Disease")** 

![image](https://user-images.githubusercontent.com/68268222/179706018-505bc6af-1223-406a-9585-16d77c776ffa.png)

**> CellScatter(cluster.averages, cell1 = "Healthy", cell2 = "Disease") + ggtitle("Gene expression correlation")**

![image](https://user-images.githubusercontent.com/68268222/179705685-6f3d034d-1f71-4025-9a3b-5f0adf180d9d.png)

**Comment by jarchana09** [comment]
Hello. I am not a member of the Seurat development team, but perhaps these suggestions may be helpful.
To include both title and the correlation coefficient, one way would be to assign the figure to a variable and then manually edit the title parameter. 
For example,
```
p1 <- CellScatter(cluster.averages, cell1 = "Healthy", cell2 = "Disease")
p1$labels$title <- paste0("Gene expression correlation\n", p1$labels$title) 
#p1$labels$title holds the correlation coefficient value; so we can append to it and add an additional figure title 
```

To label specific genes (reference: [https://satijalab.org/seurat/articles/integration_introduction.html](https://satijalab.org/seurat/articles/integration_introduction.html)) you can use Seurat's LabelPoints function. For example, in continuation with the code included above

`p1 <- LabelPoints(plot = p1, points = <gene_name(s)>, repel = TRUE)`

Hope this helps. Thanks.
