### ISSUE TITLE
AddModuleScore for visium data

### ISSUE THREAD

**Issue by AvitalPo** [satijalab/seurat#6212]
Hi,

I'm analyzing 10x visium data, and I have a gene set of interest. Can I use AddModuleScore to get a score for each spot? I know this is not a single cell level, and I can have several cells within one spot. That is why I'm asking if it is appropriate.

Thanks,
Avital

**Comment by yuhanH** [comment]
Hi @AvitalPo 
I think you can calculate AddModuleScore for each spot.  Like you mentioned, you need to realize that the module score you calculated here is not for single-cell.
