### ISSUE TITLE
subset function in v3

### ISSUE THREAD

**Issue by jindall** [satijalab/seurat#6213]
how to make a subset of seurat object that contains the cells expressing just the genes in the gene_list:
gene_list has 4000 genes in total
<img width="792" alt="text_case" src="https://user-images.githubusercontent.com/10815307/179791812-bae6f5a5-c466-4a4c-aea9-a5f56c3b1f6a.png">

**Comment by yuhanH** [comment]
Hi @jindall 
I don't fully understand what cells you want.  `expr` is a data frame and you can set your specific conditions to get cell names and use `subset ` to get a new seurat object.
Here, I use pbmc_small as an example.

```
pbmc_small
geme_list <- c("GZMB", "CCL5")
expr <- FetchData(object = pbmc_small, vars = geme_list)
## select cells at least express GZMB, CCL5
select.cells <- rownames(expr)[rowSums(expr) > 0]
pbmc_small.sub <- subset(pbmc_small, cells = select.cells)
```
