### ISSUE TITLE
DoHeatmap, how to display specific genes

### ISSUE THREAD

**Issue by andynkili** [satijalab/seurat#6214]
Hi and thank you for the fantastic tool,

I am doing a gene expression heatmap. However to avoid having overlapping gene labels and display only some of them, I do (labels is the list of 47 genes labels that I want to display):
`DoHeatmap(mydata, features = top100$gene,size = 4)
     +NoLegend()
     +scale_y_discrete(labels=labels)
     +theme(axis.text.y = element_text(angle = 40, vjust = 0.5, hjust=1))`
But the result is not the one expected:
![Picture1](https://user-images.githubusercontent.com/49782275/179814940-31970922-6df3-4dfb-a6f6-1faeb170bb28.png)

Here is what I would like to reproduce (from Couturier, C.P _et al_, Single-cell RNA-seq reveals that glioblastoma recapitulates a normal neurodevelopmental hierarchy. Nat Commun, 2020):
![Untitled](https://user-images.githubusercontent.com/49782275/179803436-e4a6ef68-111c-4313-a9cb-cc45b5baea0d.png)

**Comment by torkencz** [comment]
Hi, this seems like more of a ggplot than a Seurat question. I think the plot that you are trying to copy the style of was made in ComplexHeatmap. There you can specify specific rows to label as an annotation option. You just need to output your data and format it into a matrix.
