### ISSUE TITLE
How to "adjust" for difference in cell numbers among datasets in merging and integration SCTransform (v2) workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6216]
Hi there, 

Thanks for a great tool. 

I have 4 datasets I aim to merge and also to integrate; however, the cell numbers are not quite similar across these 4 datasets, especially Batch 2 dataset. Would you mind helping me to address 2 questions below?

1. In the SCTransform(v2) merging workflow and Integration workflow, is there any step that already takes care of the difference in cell number between datasets?

2. If not, is it advisable to take the smallest number of cells across all datasets randomly for the analyses? If so, is there already a package or function that does this? The problem here is my smallest number of cells is 500 cells.

Thank you so much for your advice!

<img width="1334" alt="Screen Shot 2022-07-20 at 11 47 27 AM" src="https://user-images.githubusercontent.com/62179082/179964093-4428fbe5-6f56-4364-a446-b05742597a70.png">

**Comment by saketkc** [comment]
You could do this outside seurat and then use the `subset()` function:

```r
barcodes_to_keep <- my_metadata %>% group_by(celltype, donor) %>% dyplr::sample_n(500) %>% pull(barcode)
object <- subset(object, cells=barcodes_to_keep)
```
