### ISSUE TITLE
HoverLocator() not working in my Shiny App

### ISSUE THREAD

**Issue by Tinocapo** [satijalab/seurat#6217]
I have tried to make the HoverLocator function work on my shiny app but it doesn't work; the plot won't load. The worst part is I think the script itself is correct because when I close the app the plot appears but in the viewer panel of Rstudio

**Comment by andrewwbutler** [comment]
Hi,

Can you provide more details or a reproducible example of trying to integrate `HoverLocator` with a shiny app? The output of `HoverLocator` is a plotly plot so you will need to handle that with the appropriate rendering and output functions in your app.

**Comment by andrewwbutler** [comment]
Closing the issue due to no response
