### ISSUE TITLE
Uncertain about how to implement average expression FeaturePlot code

### ISSUE THREAD

**Issue by s-storey** [satijalab/seurat#6218]
Good day, 

I am a little lost after essentially inheriting a scRNAseq pipeline, but I'd love to use this tool as an 'unbiased' annotation strategy. I'm looking for help as to how to apply this to my own seurat objects but don't quite understand the application of metadata well enough to do this on my own. 

Any help parsing through this code would be really appreciated.

```R
# Select genes of interest (using sample() here for demonstration purposes)
gene.set <- sample(x = rownames(x = object@data), size = 100, replace = FALSE)

# Get mean expression of genes of interest per cell
mean.exp <- colMeans(x = object@data[gene.set, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$gene.set.score'
if (all(names(x = mean.exp) == rownames(x = object@meta.data))) {
  cat("Cell names order match in 'mean.exp' and 'object@meta.data':\n", 
      "adding gene set mean expression values in 'object@meta.data$gene.set.score'")
  object@meta.data$gene.set.score <- mean.exp
}

# Plot mean expression using Seurat::FeaturePlot()
FeaturePlot(object = object, features.plot = "gene.set.score")
```

_Originally posted by @leonfodoulian in https://github.com/satijalab/seurat/issues/528#issuecomment-395069837_

**Comment by andrewwbutler** [comment]
Hi,

I'm not sure I can add much beyond what the comments already explain but basically, what this code chunk is doing is computing the per-cell mean for a set of genes and storing this as a cell-level meta.data entry. Those values are then being used by the `FeaturePlot` function to display these values in a scatter plot where cells are colored by gene set mean. Please feel free to update though if you have a more specific question.
