### ISSUE TITLE
How to use genes for featureplot NOT used in SCTransform

### ISSUE THREAD

**Issue by amufaamo** [satijalab/seurat#6220]
Hi, I did SCTransform in my PBMC samples, and I want to show featureplot CD4, CD8A ... like that. 

But I can't find CD4, because CD4 was not used for SCTransfrom. 3000 genes were used for SCTransfrom.

So, is it possible to show featureplot of genes which are not used in SCTransform?

**Comment by saketkc** [comment]
You should be using the 'data' slot of SCTransform for visualization which stores the corrected counts for all the features (even if they are not variable).

```r
FeaturePlot(object, assay="SCT")

```

One reason you would not see CD4 in the `data` slot is if it is expressed in <5 cells (SCTransform will filter these genes out by default), but you can override this behavior by doing `SCTransform(min_cells=1, vst.flavor="v2")`
