### ISSUE TITLE
How to extract the gene's expression levels as a separate data frame?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6222]
Hello. Starting with a seurat object, may I ask how to extract a data frame of a gene's expression levels per cell, i.e. rows are cells and one column of gene expression values.

Initially, I do AddModuleScore() for one gene so that the seurat object generates the gene's score for all cells and this score becomes appended as a column in the metadata of the seurat object. But then again, this score is a module score, not expression levels. 

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Ya module score is not what you want.  See `[FetchData](https://mojaveazure.github.io/seurat-object/reference/FetchData.html)`.  Just make sure to set Default Assay to whichever assay you want before calling `FetchData` and set the slot to whichever slot you want in the function call.

Best,
Sam
