### ISSUE TITLE
How to create a Seurat object form xls files?

### ISSUE THREAD

**Issue by utingtseng** [satijalab/seurat#6227]
I am trying to analyse data from the GEO database (GSE137804). The raw data is available in xls format and I am struggling to convert this into a seurat object. I have tried creating barcodes, features and matrix files by extracting them from the xls and converting them into tsv.gz with the write.table function. However, I got this error: Error in readMM(file = matrix.loc) : file is not a MatrixMarket file.
I wonder if there is a better way of reading xls files into a seurat object.

Additionally, I am also unsure how to incorporate the information in the annotation.csv into the seurat object. My current way of doing this is by creating a list containing the barcodes for desired cell types and subsetting the seurat object using the list. However, I wish to integrate the information into the seurat object and label the clusters based on the author's annotation. 

Thank you!

**Comment by Stfort52** [comment]
`Matrix::readMM` is designed to read a [MatrixMarket format](https://networkrepository.com/mtx-matrix-market-format.html) such as CellRanger's matrix file, and is not for reading plain dense matrices like `tsv`. If you converted the xls file into a tsv a plain `read.table` or `read.csv` should get the job done. Alternatively, take a look at tidyverse's [`readxl`](https://readxl.tidyverse.org/) package to directly read `xls` files in.
