### ISSUE TITLE
Utility of the "new" active.ident: Do we need to change cluster names before merging in computing de novo UMAP?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6228]
Hi there, 

I have 2 Seurat objects which were SCTransform-ed (v2) individually and carried through clustering analysis. 

I now want to compute the de novo UMAP visualization to see which cells are shared or unique between these 2 objects, following the de novo UMAP section of https://satijalab.org/seurat/articles/multimodal_reference_mapping.html#example-2-mapping-human-bone-marrow-cells-1. 

Between these objects, there are cluster labels that are the same, e.g., both Object 1 and Object 2 have cluster 1, cluster 2, etc. 

Q1. Would you mind helping me understand the utility of de novo UMAP visualization? Is it just for visualizing on this new UMAP where the cells that might be present in 1 Object but not the other Object might cluster in proximity to other cells? 

Q2. Or, is it simply to identify which cells that were not present in one of the 2 Objects and the co-clustering on the UMAP does not have a meaning?

Q3. Following the merging (`merg.data=T` and merge `pca`), when I examined the cell count of the new cluster names between the 2 Objects, the resulting cluster assignment in `active.ident` of the merged object was simply the combination of both Objects. So, does it mean the fact that Object 1 and Object 2 both have cells belonging to the "new" cluster 1, for example, does not mean that these cells were co-clustered; it just means that they had the same cluster name before the merge?

Thank you for your insight!

**Comment by longmanz** [comment]
Hi @denvercal1234GitHub ,
Re Q1 and Q2: By generating the de novo UMAP after merging 2 datasets, we are able to look for cell clusters that are not shared by the 2 datasets. This could happen especially when your 2 datasets have profound heterogeneity. 

Re Q3: It just means that they had the same cluster name before the merge.

**Comment by denvercal1234GitHub** [comment]
Hi @longmanz - Thank you for your response. 

For Q1 and 2, would you mind elaborating a bit more on this utility of de novo UMAP? Do you mean that if we simply merge without merging `pca`, the algorithm would just put cells which are dataset-specific to the most similar cells of the other dataset, whereas in de novo UMAP, these dataset-specific cells stay separated? 

For Q3, so should I make sure that each Object has unique cluster names before merging the Objects? Because if the cells are just grouped simply due to the fact that they have the same cluster names, then it does not provide me with any useful info by this de novo UMAP?

**Comment by longmanz** [comment]
Hi @denvercal1234GitHub,
Sorry for the late reply! 
Re 1). Yes you are right. de novo UMAP is always worth looking into due to the potential existence of these dataset-specific cell clusters.
Re 2).  Yes.
