### ISSUE TITLE
set dotplot y-axis in order 

### ISSUE THREAD

**Issue by yamihn** [satijalab/seurat#6229]
Hi, I produced a dotplot with the function 
DotPlot(obj, features =unique(top2_markers$gene), cols = c("white", "blue"), group.by = "res.0.2", col.min = -0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + coord_flip()
and I got this 
![markers_02](https://user-images.githubusercontent.com/109409803/180714044-716cd2f0-f5c1-48f6-9106-017f7f203cb9.png)

but I would to order the y-axis ( genes) in the way to visualize the dots in order in a diagonal line from bottom left to top right.
Could u suggest me a way to do it?

**Comment by k3yavi** [comment]
Hi @yamihn ,

you can try giving factor instead of a regular vector of gene names to the `features` parameters, where levels would of the factor would be the the order of the genes you cant in the DotPlot.
