### ISSUE TITLE
Will it be correct to refind FindVariableFeatures using integrated assay in a subset?

### ISSUE THREAD

**Issue by Gonglinjing** [satijalab/seurat#6230]
Hi!

I have isolated subsets of T cells from single cell analysis. Will it be okay to refind FindVariableFeatures using integrated assay or I have to do this using RNA?

Thank you for your insight!

**Comment by yuhanH** [comment]
Hi @Gonglinjing 
It would better use RNA assay to refine your variable features.
Because you may only variable features to perform integration, only variable features are present in the integrated assay. You may not get new variable features in integrated assay.
