### ISSUE TITLE
After the subsets of low quality cells were removed, will it be correct to analyse the rest of data again according to seruat's standard procedures?

### ISSUE THREAD

**Issue by Gonglinjing** [satijalab/seurat#6231]
Hi!

I have analysed the sihgle-cell sequencing data and removed the subsets of low quality cells. Can I analyse the rest of data again according to seruat's standard procedures, including Normalizing the data, Identification of highly variable features, Scaling the data, Perform linear dimensional reduction, Determine the ‘dimensionality’ of the dataset and Cluster the cells?

Thanks!

**Comment by timoast** [comment]
Yes you can
