### ISSUE TITLE
subsetting seurat object increases in size

### ISSUE THREAD

**Issue by shabs24** [satijalab/seurat#6232]
Hi all,

When I subset the Seurat object, the size of the new object increase drastically. My initial object with has 43K cells is ~ 600MB.
When I subset the seurat object (~32 K cells)the size goes to 7.6 GB. I am not sure what I am doing wrong. 

Any help/suggestions?

Many Thanks!

**Comment by timoast** [comment]
Can you provide a reproducible example?

**Comment by timoast** [comment]
Yes, that reproduces this issue

**Comment by shabs24** [comment]
> Yes, that reproduces this issue

Here is the code
object =readRDS("object.rds")
dim(object)
29838 36792
format(object.size(object), units = "Gb")
#[1] "2.5 Gb"

object_final<-subset(object, idents = c(1,3,13,14,16,17),invert=TRUE)
dim(object_final)
# [1] 29838 25696
format(object.size(object_final), units = "Gb")
# [1] "1.8 Gb"
object_final <- FindVariableFeatures(object = object_final, selection.method = "vst", nfeatures = 2000)
object_final <- ScaleData(object = object_final, features = rownames(object_final))
object_final <- RunPCA(object = object_final, features = VariableFeatures(object_final), npcs = 50)
object_final<-RunHarmony(object_final, "orig.ident", plot_convergence = TRUE)
ElbowPlot(object = object_final,ndims=50)
object_final<-RunUMAP(object_final, reduction = "harmony", dims = 1:20) 
object_final<-FindNeighbors(object_final, reduction = "harmony", dims = 1:20)
object_final<-FindClusters(object_final, resolution = 0.5) 
format(object.size(object_final), units = "Gb")
[1] "7.2 Gb"

object_final<-subset(object_final, idents = c(11),invert=TRUE)
dim(object_final)
# [1] 29838 25285
format(object.size(object_final), units = "Gb")
# [1] "7 Gb"
object_final <- FindVariableFeatures(object = object_final, selection.method = "vst", nfeatures = 2000)
object_final <- ScaleData(object = object_final, features = rownames(object_final))
object_final <- RunPCA(object = object_final, features = VariableFeatures(object_final), npcs = 50)
object_final<-RunHarmony(object_final, "orig.ident", plot_convergence = TRUE)
ElbowPlot(object = object_final,ndims=50)
object_final<-RunUMAP(object_final, reduction = "harmony", dims = 1:20) 
object_final<-FindNeighbors(object_final, reduction = "harmony", dims = 1:20)
object_final<-FindClusters(object_final, resolution = 0.5)
dim(object_final)
# [1] 29838 25285
> format(object.size(object_final), units = "Gb")
[1] "7.1 Gb"

**Comment by shabs24** [comment]
Here is the code
object =readRDS("object.rds")
dim(object)
29838 36792
format(object.size(object), units = "Gb")
[1] "2.5 Gb"

object_final<-subset(object, idents = c(1,3,13,14,16,17),invert=TRUE)
dim(object_final)
[1] 29838 25696
format(object.size(object_final), units = "Gb")
 [1] "1.8 Gb"
object_final <- FindVariableFeatures(object = object_final, selection.method = "vst", nfeatures = 2000)
object_final <- ScaleData(object = object_final, features = rownames(object_final))
object_final <- RunPCA(object = object_final, features = VariableFeatures(object_final), npcs = 50)
object_final<-RunHarmony(object_final, "orig.ident", plot_convergence = TRUE)
ElbowPlot(object = object_final,ndims=50)
object_final<-RunUMAP(object_final, reduction = "harmony", dims = 1:20) 
object_final<-FindNeighbors(object_final, reduction = "harmony", dims = 1:20)
object_final<-FindClusters(object_final, resolution = 0.5) 
format(object.size(object_final), units = "Gb")
[1] "7.2 Gb"

**Comment by timoast** [comment]
Ok, so it's not subsetting that makes the object larger, but running an analysis? That's expected since steps like `ScaleData()` will add data to the object.

**Comment by timoast** [comment]
There’s no need to scale all the genes, and that’s what uses most of the memory since it’s a large dense matrix
