### ISSUE TITLE
Unable to specify reduction using FeaturePlot()

### ISSUE THREAD

**Issue by andradejon** [satijalab/seurat#6233]
Apologies in advance for not supplying any code to troubleshoot, but I think this is more just an issue with function capabilities, not personal error.

I have a dataset with three umap reductions (say A, B, and C). This was obtained by mapping the droplets of one dataset onto two others using FindTransferAnchors(), TransferData(), IntegrateEmbeddings(), and ProjectUMAP() as described here:
https://satijalab.org/seurat/articles/multimodal_reference_mapping.html

If I specify any of these three reductions using the reduction argument of DimPlot(), it works just fine and I get the appropriate plots. When I use FeaturePlot() to map some continuous trait onto these droplets, however, it only uses the first umap reduction (A) regardless of what I put in the reduction argument. Calling DefaultDimReduc() also shows that A is the default, and there is no DefaultDimReduc<- function to change this. I also see an older post showing that the old method of doing this, SetDimReduction(), is deprecated.
https://github.com/satijalab/seurat/issues/1271

Any help would be appreciated. Thank you.

**Comment by timoast** [comment]
What version of Seurat are you using? Can you show the sessionInfo()? I think this was an issue fixed in a previous release

**Comment by timoast** [comment]
Closing this since we haven't heard back
