### ISSUE TITLE
Selecting Neighbors

### ISSUE THREAD

**Issue by klpara** [satijalab/seurat#6234]
Hello,

I trying to integrate data from different developmental stages, however, I am finding that one cluster keeps popping up consisting of two distinct mature cell types. I am trying to adjust the integration parameters to separate these cells, since they should be distinct states, but I wonder if there is a recommended method to address this issue?

I have tried FindIntegrationAnchors(reduction= "rpca" or "cca") and FindNeighbors (annoy.metric="euclidean" or "cosine"). As well as altering the n.trees, k values (k.anchor, k.filter, k.score), and tried increasing the number of features where possible. The dataset is around 5000 cells in total (between 1000-2000 cells at each developmental stage).

Thank you!

multipledata <- SplitObject(multipledata,split.by="dataset")

multipledata <- lapply (X=multipledata, FUN=function(x){
  x <- SCTransform(x, residual.features = NULL, ncells = NULL, variable.features.n=3000)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures=2000, do.plot=FALSE)
})

multifeatures <- SelectIntegrationFeatures(object.list=multipledata,nfeatures=2000)
multipledata <- PrepSCTIntegration(object.list=multipledata, anchor.features=multifeatures)
multianchors <- FindIntegrationAnchors(object.list=multipledata, normalization.method = "SCT", anchor.features=multifeatures,k.anchor=5,k.filter=100,k.score=30,nn.method="annoy",n.trees=50,reduction="rpca",dims=1:30)

integrated <- IntegrateData (anchorset=multianchors, normalization.method="SCT")
integrated <- ScaleData(integrated, features=rownames(integrated)) %>% RunPCA(npcs = 50,features=NULL)
integrated <- FindNeighbors (integrated, reduction = "pca", dims = 1:10, n.trees=50,annoy.metric="euclidean")

**Comment by sjwu571** [comment]
This paper https://www.cell.com/cell-reports/fulltext/S2211-1247(22)01202-5 and code in their supplementary material/github might help you. Good luck!
