### ISSUE TITLE
How to load and create seurat object from aggregated expression matrix txt file, and separate the samples?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6237]
Hello! Good day, May I kindly ask for your advice on how I can move forward with creating a seurat object from publicly available data at **GSE152450 (GSM4616047_scRNA-Seq_of_enriched_monocytes_matrix.txt.gz)**: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4616047

According to the description in GEO, the samples are labeled with the following (HI for healthy, KD for disease):
-Sample Tag 6—TTACCCGCAGGAAGACGTATACCCCTCGTGCCAGGCGACCAATGC (used to lable "Enriched monocytes - HI1")
-Sample Tag 7—TGTCTACGTCGGACCGCAAGAAGTGAGTCAGAGGCTGCACGCTGT (used to lable "Enriched monocytes - HI2")
-Sample Tag 8—CCCCACCAGGTTGCTTTGTCGGACGAGCCCGCACAGCGCTAGGAT (used to lable "Enriched monocytes - KD1")
-Sample Tag 9—GTGATCCGCGCAGGCACACATACCGACTCAGATGGGTTGTCCAGG (used to lable "Enriched monocytes - KD2")

I tried this code:

`ALL.DATA <- read.table(file = "GSM4616047_matrix.txt.gz", sep = "", header=TRUE, row.names=1, as.is=T) `

![image](https://user-images.githubusercontent.com/68268222/180965465-54500599-330d-4286-b969-d1f8e1138017.png)

It also created NA's. Further, as you can see, the first row is very strange. I think there's something that went wrong somewhere? Rows should be genes right? But this first row is "Cell_Index" and the nCount_RNA is 4 billion+!

Can anyone please help me? How could I load this file, create a seurat object, and separate the sample groups (HI and KD) please?

Thanks in advance!

**Comment by Stfort52** [comment]
According to the official [Docs](https://mojaveazure.github.io/seurat-object/reference/CreateSeuratObject.html), when you're making a Seurat Object from a custom matrix, you must have the **cells as columns and features as rows**. 
Also, taking a look at the public data `GSM4616047`, it seems like it has other metadatas like `Cell_Index` and `Sample_Tag` in it. As these metadatas are not a part of the count matrix, you should seperate those columns from the data and create a Seurat object only with the pure count matrix. The metadatas can be assigned later to each cells. Consult the official tutorial for this.
