### ISSUE TITLE
FindMarkers on Integrated datasets

### ISSUE THREAD

**Issue by Lipinski-B** [satijalab/seurat#6238]
Hi,

Regarding on the following quote from @satijalab, do you know if to perform FindMarkers on an integrated dataset is still dangerous or if it's statistically correct today? Cause the Seurat's vignette are that talkactive about this, and the RNA assay is still supporting some batch effect that could be removed by the integration process.

"
_When comparing data across conditions (for example, ctrl v. drug), you should not run FindMarkers on the integrated data, but on the original dataset (assay = "RNA"). This is because the integration will aim to remove differences across samples so that shared populations align together._

_This is why we treat sample comparison as a two-step process. First, we integrate datasets together to consistently identify common cell populations across datasets. Second, we perform DE on the original (unintegrated) data, to find gene expression differences for each population._

_Originally posted by @satijalab in https://github.com/satijalab/seurat/issues/1168#issuecomment-466076466_
"

Thanks in advance.
Boris

**Comment by timoast** [comment]
> do you know if to perform FindMarkers on an integrated dataset is still dangerous or if it's statistically correct today?

Nothing has changed, we still do not recommend using the integrated data for differential expression
