### ISSUE TITLE
'X' must be atomic error when running a merged sobjmlist composed of a seurat object ref and new seurat obj dataset.

### ISSUE THREAD

**Issue by JanRose1** [satijalab/seurat#6239]
Hey everyone so I'm trying to run the following line of code

`features <- SelectIntegrationFeatures(object.list = sobjmlist)`

but I get the following error

> WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 'x' must be atomic

To give an idea of how I've written my code up to this point using the new dataset here's the format

`sobjmlist <- list(ref, query)`
`sobjmlist`

> [[1]]
An object of class Seurat 
47662 features across 57989 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 1 dimensional reduction calculated: pca
[[2]]
An object of class Seurat 
27305 features across 107344 samples within 1 assay 
Active assay: RNA (27305 features, 2000 variable features)

The current reference data and new seurat object are as follows

`ref`

> An object of class Seurat 
47662 features across 57989 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 1 dimensional reduction calculated: pca

`ref@assays`

> $RNA
Assay data with 45662 features for 57989 cells
First 10 features:
 A1BG-AS1, A1CF, A2M, A2M-AS1, A2ML1, A2ML1-AS1, A2MP1, A3GALT2, A4GALT,
A4GNT 
$integrated
Assay data with 2000 features for 57989 cells
Top 10 variable features:
 TPSAB1, TMSB4X, FXYD4, AQP2, UMOD, S100A8, RGS5, DEFB1, SLC12A1, C1QB 

`query`

> An object of class Seurat 
27305 features across 107344 samples within 1 assay 
Active assay: RNA (27305 features, 2000 variable features)

`query`

> An object of class Seurat 
27305 features across 107344 samples within 1 assay 
Active assay: RNA (27305 features, 2000 variable features)

`query@assays`

> $RNA
Assay data with 27305 features for 107344 cells
Top 10 variable features:
 ENSG00000211592, ENSG00000211895, ENSG00000211896, ENSG00000132465,
ENSG00000211677, ENSG00000211897, ENSG00000211679, ENSG00000167748,
ENSG00000115386, ENSG00000211893 

In comparison when run with a simulated query constructed from the reference as follows
`s <- readRDS('/content/drive/MyDrive/Reference.RDS')`
`v <- sample(colnames(s), size =500, replace=F)`
`s[['split']] <- NA`
`s[['split']] <- names(s$split) %in% v`
`q <- subset(s, split == TRUE)`
`r <- subset(s, split != TRUE)`
`q <- CreateSeuratObject(q[['RNA']]@counts)`
`saveRDS(r, '/content/drive/MyDrive/Reference.RDS')`
`saveRDS(q, '/content/drive/MyDrive/DemoQuery.RDS')`

`rm(q,r,s,v)`

and then going through the same normalization properties I then do the same creation of a merged list using the two objects
`sobjmlist2 <- list(ref,demq)`

the object itself looks similar and the demoquery isn't significantly different in format to the new dataset
`sobjmlist2`

> [[1]]
An object of class Seurat 
47662 features across 57989 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 1 dimensional reduction calculated: pca
[[2]]
An object of class Seurat 
45662 features across 500 samples within 1 assay 
Active assay: RNA (45662 features, 2000 variable features)

`demq`

> An object of class Seurat 
45662 features across 500 samples within 1 assay 
Active assay: RNA (45662 features, 2000 variable features)

`demq@assays`

> $RNA
Assay data with 45662 features for 500 cells
Top 10 variable features:
 GNLY, IGFBP5, CTSS, FP671120.1, FP671120.4, FCN1, ID3, TYROBP, LST1,
S100A2 

Solutions I've tried mostly stem from this following link
https://github.com/satijalab/seurat/issues/1296
I've yet to try checking for features with underscores but I have tried changing the default assay such that the one for the ref and query match yet it didn't work nor was it an issue when I ran the code using the simulated query and the reference. The only alternative that lie are checking for features with underscores (Which I'd appreciate if someone could tell me a convenient way to do so.) Or that there exists some larger discrepancy between the features of the reference with the new dataset vs the reference with a simulated query of itself. 

Any help would be appreciated.

**Comment by Moloch0** [comment]
I met the same question...after three months.Yet I have no idea about it.

**Comment by Moloch0** [comment]
> I met the same question...after three months.Yet I have no idea about it.

That's awkward... because the gene IDs in the two data sets do not match...
I converted the ENSEMBL IDs to gene symbols, and it worked.

**Comment by torkencz** [comment]
Yeah the only thing I can think of the ENSEMBL ID route.
