### ISSUE TITLE
 Seurat Error: Duplicate cell names 

### ISSUE THREAD

**Issue by farhanma** [satijalab/seurat#624]
Dear,

I am using Seurat for scRNAseq analysis in R language and I am experiencing the following error:

```R
Running CCA
Merging objects
Error in MergeSeurat(object1 = object, object2 = object2, do.scale = FALSE,  :
  Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names
Calls: RunCCA -> MergeSeurat
Execution halted
```

After a through investigation, I found out that the error is caused because I am calling the following line (line 29 in the attached file):

`Data.combined <- RunCCA(iPSCs171, treat180, genes.use = genes.use, num.cc = 30)`

This error is generated only when I am specifically using these two datasets, and according to my understanding, the error is because I am having duplicate cell names
that appear in the both datasets.

Please could you advise me?

Attached is the R script.

```R
library(Seurat)

iPSCs171.data <- Read10X(data.dir = "/media/ibex_scratch/171220_D00658_0041_AH3LLWBCX2-Lane2-iPSCs/outs/filtered_gene_bc_matrices/GRCh38")
treat180.data <- Read10X(data.dir = "/media/ibex_scratch/180221_D00658_0046_AH3LG3BCX2-iPSCs/outs/filtered_gene_bc_matrices/GRCh38") 

iPSCs171 <- CreateSeuratObject(raw.data = iPSCs171.data, project = "iPSCs171_data", min.cells = 5)
iPSCs171@meta.data$run2 <- "iPSCs171"
iPSCs171 <- FilterCells(iPSCs171, subset.names = "nGene", low.thresholds = 500, high.thresholds = Inf)
iPSCs171 <- NormalizeData(iPSCs171)
iPSCs171 <- ScaleData(iPSCs171, display.progress = F)


treat180 <- CreateSeuratObject(raw.data = treat180.data, project = "treat180_data", min.cells = 5)
treat180@meta.data$run2 <- "treat180"
treat180 <- FilterCells(treat180, subset.names = "nGene", low.thresholds = 500, high.thresholds = Inf)
treat180 <- NormalizeData(treat180)
treat180 <- ScaleData(treat180, display.progress = F)

iPSCs171 <- FindVariableGenes(iPSCs171, do.plot = F)
treat180 <- FindVariableGenes(treat180, do.plot = F)

g.1 <- head(rownames(iPSCs171@hvg.info), 1000)
g.2 <- head(rownames(treat180@hvg.info), 1000)
genes.use <- unique(c(g.1, g.2))
genes.use <- intersect(genes.use, rownames(iPSCs171@scale.data))
genes.use <- intersect(genes.use, rownames(treat180@scale.data))

Data.combined <- RunCCA(iPSCs171, treat180, genes.use = genes.use, num.cc = 30)
```

**Comment by romanhaa** [comment]
Did you check if there are duplicate cell names? If that is the case, just go ahead and add a suffix/prefix, e.g. `xxxxx-iPSC` or `xxxxx-treat`. You can do it either manually before merging the data sets or during the merging by using the parameters mentioned in the error message: `add.cell.id1` and/or `add.cell.id2`

Keep in mind that the cell names are simply the cell barcodes which come from a known (IIRC ~750k) library so it's not unlikely to have an overlap of barcodes between two data sets.

**Comment by farhanma** [comment]
Yes it does have duplicated cell names. Thank you very much, it is now working.

I replace the RunCCA with the following:

`Data.combined <- RunCCA(iPSCs171, treat180, add.cell.id1 = "iPSCs171", add.cell.id2 = "treat180", genes.use = genes.use, num.cc = 30)`

**Comment by yueqiw** [comment]
Hi,

I had the same duplicate call names issue today and solved it by the following code: 
```
colnames(data1@data) <- paste("S1", colnames(data1@data), sep = "_")
colnames(data1@raw.data) <- paste("S1", colnames(data1@raw.data), sep = "_")
colnames(data1@scale.data) <- paste("S1", colnames(data1@scale.data), sep = "_")
rownames(data1@meta.data) <- paste("S1", rownames(data1@meta.data), sep = "_")
data1@cell.names <- paste("S1", data1@cell.names, sep = '_')

# and do the same for the other dataset, replace the 'S1' prefix with something like 'S2'
```

**Comment by yojetsharma** [comment]
> <- paste("S1", data1@cell.names, sep = '_')

Where can I find cell.names in my seurat obj?

**Comment by thisismuskaangupta** [comment]
> > <- paste("S1", [data1@cell.names](mailto:data1@cell.names), sep = '_')
> 
> Where can I find cell.names in my seurat obj?

https://satijalab.github.io/seurat-object/reference/Cells.html
