### ISSUE TITLE
min.features vs nFeature_RNA: are they just the same filter?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6242]
Hello, just want to clarify whether **min.features** and **nFeature_RNA** are just the same filter?

In CreateSeuratObject,  `min.features` is commonly set to 200, and similarly,  `nFeature_RNA` is commonly set to 200 as well.

I ask this because actually, in my dataset, I'm trying to filter/include only cells with **100 and above** genes, so I am not sure if I should change both of these parameters to **100** or only one of them. Thank you very much.

**Comment by samuel-marsh** [comment]
Hi,

Yes setting min.feature when creating object or setting with nFeature_RNA will perform the same thing.

As a word of personal experience the 200 gene threshold shown in tutorials is just an example that is appropriate for that dataset.  A typical value is highly dataset specific and depends on sequencing technology, cell types present, and sequencing depth.

From experience working with brain tissue even with previous gen 10X kits (3’ V2) I always set much higher min.feature (usually at least 600 genes/cell; depending on cell type).  I would say that 100 genes per cell is a pretty low threshold and you may be including a number of low quality cells in your analysis.

Best,
Sam

**Comment by saketkc** [comment]
I agree with @samuel-marsh, the thresholds shown in the vignettes are dataset (and technology) dependent. I would recommend visualizing/calculating summary statistics on your dataset and then determining these thresholds.
