### ISSUE TITLE
Which slot is best to use for downstream analysis. Say visually comparing expression of one group vs another? 

### ISSUE THREAD

**Issue by ahdee** [satijalab/seurat#6243]
Hi as I understand it, 
SCTranformed ```scale.data``` slots are the Pearson Residuals (as per the publication); ```counts``` slots are from the Negative Binomial model to median transcript count per cell and the ```data``` are log2 transformed. However I can't seem to get a consistent answer as to which of these slots are best to use say, to compare group a vs group b in a violin plot and just running a wilcox test or something. 

I'm inclined to think log2 of the scale.data ( the pearson residuals ) are best to use but wanted some confirmation? 

thanks.

**Comment by saketkc** [comment]
In the [v2 workflow](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) we show that you can use the correct counts `data` slot for DE and visualization - this also works if you have datasets with difference in sequencing depth. Pearson residuals themselves are not comparable across datasets.
