### ISSUE TITLE
FindVariableFeatures() error in simpleLoess

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6249]
Hello! 

I ran FindVariableFeatures() on a subset celltype taken from a big seurat object and I got the followinf warning messages. I wonder if this can just be ignored or if it needs to be fixed? I'm not sure how to resolve this. May I ask for your advice? 

Thank you!

![image](https://user-images.githubusercontent.com/68268222/182034918-6b336ced-50fe-4dcc-9d30-d6eb691d3419.png)

**Comment by saketkc** [comment]
You can ignore this warning.
