### ISSUE TITLE
Saving both gene ID and gene symbols/names

### ISSUE THREAD

**Issue by romanhaa** [satijalab/seurat#625]
Is there a way to save both gene IDs and gene symbols/names in the Seurat object? Currently I'm converting them manually but having this built-in would be great to facilitate down-stream analysis where the ID is required (e.g. gene ontology) while using the gene name makes interpreting marker gene lists much more intuitive.

**Comment by satijalab** [comment]
We do not support this now (but will in the future). For the moment, you can store a table of the gene ID / ensembl ID (or similar) conversions in the object@misc slot.

**Comment by yojetsharma** [comment]
> Is there a way to save both gene IDs and gene symbols/names in the Seurat object? Currently I'm converting them manually but having this built-in would be great to facilitate down-stream analysis where the ID is required (e.g. gene ontology) while using the gene name makes interpreting marker gene lists much more intuitive.

Can you please share the code of how you are converting the ensembl ids to gene names in a seurat obj?
