### ISSUE TITLE
How to remove batch effect when using 10x multiome seq?

### ISSUE THREAD

**Issue by DexinYang1998** [satijalab/seurat#6250]
Hi,

I have 5 samples from the same biological system profiled by 10x multiome-seq. If I want to remove the batch effect, do I need to perform batch effect correction in scRNA-Seq and scATAC-Seq separately, and then perform Weighted Nearest Neighbour (WNN) to do the downstream analysis?

Thanks.

**Comment by torkencz** [comment]
Try https://github.com/satijalab/seurat/issues/3645
