### ISSUE TITLE
Ran out of Memory When Scaling Data with ScaleData function

### ISSUE THREAD

**Issue by chrislee14108** [satijalab/seurat#6251]
Hi, I am trying to scale a scRNA Seq data found on 10x genomics website for my scRNA Seq analysis and am running it on a Windows laptop. Apparently I ran into a memory error when I tried to scale the data with the ScaleData function, which I don't quite understand why or where the error is coming from.

`Error in subCsp_rows(x, i, drop = drop) : 
Cholmod error 'out of memory' at file ../Core/cholmod_memory.c, line 146`

Any suggestions or solutions will be appreciated!

**Comment by AustinHartman** [comment]
How many features are you passing to `ScaleData`? If possible, you could reduce the number of features used to reduce memory usage
