### ISSUE TITLE
What's the difference between between average expression and average expression scaled?

### ISSUE THREAD

**Issue by jd2022a** [satijalab/seurat#6252]
In R/Seurat, I'm looking at the expression of genes, for example Ddx4. I created a dot plot and then looked at the data behind the dot plot. There's average expression and average expression scaled. What's the difference? Which one should I consider for seeing if the gene is expressed or not? I also don't understand why average expression scaled has negative values as how can a gene be negatively expressed? Sorry if this is a really basic question I'm in undergrad and don't know anything.
<img width="409" alt="Screen Shot 2022-08-01 at 11 40 41 AM" src="https://user-images.githubusercontent.com/110422214/182225142-0ef1af42-4b56-44d7-9d1c-4dad1900ba87.png">

**Comment by saketkc** [comment]
Average expression is the average of the normalized expression values. Scaled expression values centers the expression to have zero mean and a standard deviation of one. See [documentation](https://satijalab.org/seurat/reference/scaledata) for details.
