### ISSUE TITLE
Plotting both specific cell barcodes and showing cluster colors at the same time.

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#6256]
> Hi, I think that if you specify a set of barcodes via "cells.highlight" in DimPlot and also have your cluster info under Idents in your object you can set label=T and have both types of info on your plot.

Thank you. I plotted my UMAP like this:
DimPlot(D1_so, reduction = 'umap',label = TRUE, cells.highlight = barcode_list, cols.highlight = "blue4", order = TRUE ),

but I cannot see the colors of my clusters. I can only see the numbers labelling my clusters and the colored dots representing each barcode from my list.
Is there a way to view both the colors of the clusters and the highlighted cells at the same time?

_Originally posted by @atly2000 in https://github.com/satijalab/seurat/issues/6207#issuecomment-1201696225_

**Comment by k3yavi** [comment]
Unfortunately, you can either highlight cells or color all the clusters, there is no way to do both.
