### ISSUE TITLE
Identify clusters using result from FindAllMarkers

### ISSUE THREAD

**Issue by chen496923026** [satijalab/seurat#6259]
Hi,
I have a problem in identifying cluster when I using result from FindAllMarkers.
I noticed that all of the pct.1 were lower than pct.2 in this cluster.
So, how could I identify the specific cluster using the result from FindAllMarkers?
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

p_val | avg_log2FC | pct.1 | pct.2 | p_val_adj | cluster | gene
-- | -- | -- | -- | -- | -- | --
7.97E-27 | 1.705866824 | 0.646 | 0.726 | 1.78E-22 | 13 | Gm42418
2.50E-20 | 0.294266036 | 0.131 | 0.377 | 5.59E-16 | 13 | Arfgef3
2.60E-20 | 0.261782045 | 0.092 | 0.304 | 5.82E-16 | 13 | Tspoap1
3.50E-20 | 0.303002986 | 0.147 | 0.405 | 7.83E-16 | 13 | Grik5
4.73E-20 | 0.250532961 | 0.124 | 0.36 | 1.06E-15 | 13 | Mir124-2hg

</body>

</html>

**Comment by Gesmira** [comment]
Hi, 
Have you tried setting the only.pos parameter to equal true: `all.markers <- FindAllMarkers(object = pbmc, only.pos = TRUE)`? This should return only the positive markers.
