### ISSUE TITLE
RunMultiCCA() fails to detect duplicated cell names early on

### ISSUE THREAD

**Issue by HenrikBengtsson** [satijalab/seurat#626]
There's a [thinko](https://github.com/satijalab/seurat/blob/master/R/dimensional_reduction.R#L835-L839) in how `RunMultiCCA()` tries to protect against duplicatd cell names early on;

```r
  names.list <- lapply(object.list, slot, name = "cell.names")
  names.intersect <- Reduce(intersect, names.list)
  if(length(names.intersect) > 0) {
    stop("duplicate cell names detected, please set 'add.cell.ids'")
  }
```

For instance, if `intersect(object.list[[1]], object.list[[2]])` is empty, then it doesn't matter what `object.list[[3]]` etc. contains.

**Comment by satijalab** [comment]
Closing this issue as we are now moving away from the use of RunMultiCCA - we do improved error checking in the v3 workflow - thanks to your comment
