### ISSUE TITLE
What is the difference between integrating by donor_ID vs performing DEG with donor_ID as latent.vars?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6262]
Hi there, 

My dataset when merged showed a high impact in clustering by `donor_ID`. So I want to subtract out this donor effect. 

Question 1. Would you mind helping me understand how do the two approaches below differ in terms of the interpretation of their results?
Question 2. For approach 2, I cannot use `wilcox` test.  Among `LR`, `negbinom`, `poisson`, and `MAST`, what are the key criteria to select the test appropriate for scRNA-seq?

Thank you so much!

APPROACH 1: Integrate datasets by `donor_ID`

APPROACH 2: Merge datasets, then perform `FindMarkers(latent.vars = donor_ID)`?

**Comment by saketkc** [comment]
The goal of integration is to identify corresponding cell states among the donors. If the goal of DE is to identify consistent cell state markers (independent of the donor), you would want to regress it out using LR or any of the other GLM-based test. Suggesting one test here is out of purview, but most glm based tests will return similar top ranking genes (though some GLMs can return very lowly expressed genes also as DE, so you might have to apply posthoc filtering).
