### ISSUE TITLE
How to obtain variable feature info if we selected variable features for merged Seurat object using SelectIntegrationFeatures()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6263]
Following issues #5761 and #4115, 

Would you mind letting me know how to get variable feature info if we selected the variable features for a merged Seurat object using `SelectIntegrationFeatures()`? 

I did this because I `SCTransform(v2)` each object separately before merging them, which removed their variable features. I thus used `SelectIntegrationFeatures()` output as variable features for the merged object.

Thank you again for your help!

```
merged_var_features <- SelectIntegrationFeatures(object_list, assay = c("SCT", "SCT"), nfeatures = 5000, fvf.nfeatures=5000)

VariableFeatures(merged_object) <- merged_var_features
```

**Comment by saketkc** [comment]
Answered in #6412
