### ISSUE TITLE
Identify expression level of a signatue using AddModuleScore() 

### ISSUE THREAD

**Issue by utingtseng** [satijalab/seurat#6264]
I am trying to assess how well a cell type fits in with an expression signature, which may contain a high expression of some genes and a low expression of some other genes. For example, I want to see which cell type out of the 5 I have in my dataset fits the best with the description of high exp in geneA, geneB and low exp in geneC. 

Is AddModuleScore() an appropriate tool for this case? From what I understand, AddModuleScore calculates the score based on the relative expression level to average. But I am unsure as to how the scores for different genes in the list of feature is added. If it's cumulative does it mean that the scores for the low exp gene will cancel out the score of the high exp gene?

If this is not the best solution to what I want to do, any pointers to how I could approach this problem would be much appreciated!

**Comment by torkencz** [comment]
Hi, I would include genes that are uniformly high in the cell type. AddModuleScore should work for your problem.
