### ISSUE TITLE
Calculation of Feature Mean by HVFInfo

### ISSUE THREAD

**Issue by 7young-wang** [satijalab/seurat#6265]
Hi Seurat Team,

I want to first thank you all for this amazing package and how you have managed to answer everyone's question. I got inspired a lot just by viewing the issues posted here. Thank you!

I am trying to calculate average expression level for each gene in my sample by using the HVFInfo function. I started with 7 samples and `merged` them first. Then I followed the workflow, subset and excluded some cells, logNormalized and then used the following lines to find average expression. 
```
FindVariableFeatures(
  object = comb_5dpf,
  selection.method = "vst", nfeatures = 2000)
variant_feature_info <- HVFInfo(object = comb_5dpf, selection.method = "vst")
```
And I got a table like this:
```
                          mean     variance variance.standardized
si:ch73-252i11.3  0.0016162621 0.0016758658             0.8581024
PARP12            0.0013365244 0.0015212772             0.9552709
syn3              0.0001554098 0.0001553905             0.9408545
ptpro             0.0750940229 0.0785332849             0.7065253
eps8              0.0183694402 0.0193380474             0.7789658
si:ch1073-395m9.3 0.0000000000 0.0000000000             0.0000000
```
However, if I calculate the mean directly from the raw matrix like this:
```
raw <- comb_5dpf@assays[["RNA"]]@data
gene_average <- function(matrix) {
  mean <- rowMeans(matrix)
  name <- rownames(matrix)
  return (data.frame(name, mean))
}
raw_average <- gene_average(raw)
```
The table I got gives different value from the above HVF function. 
```
                               name         mean
si:ch73-252i11.3   si:ch73-252i11.3 0.0026190233
PARP12                       PARP12 0.0018405065
syn3                           syn3 0.0002374131
ptpro                         ptpro 0.1273302605
eps8                           eps8 0.0312038061
si:ch1073-395m9.3 si:ch1073-395m9.3 0.0000000000
```
I am wondering why is that and which one I should use. Is that because `comb_5dpf@assays[["RNA"]]@data` isn't the matrix HVFInfo has been using? 

Any suggestions are welcomed. Thanks in advance!

**Comment by saketkc** [comment]
You can use [AverageExpression](https://satijalab.org/seurat/reference/averageexpression) to get mean normalized values.

**Comment by mojaveazure** [comment]
The `vst` method of `FindVariableFeatures` uses the counts matrix, not the normalized data matrix
