### ISSUE TITLE
How Do I get a list of gene expression (from high to low) in a specific cluster of cells in Seurat

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#627]
Hi everyone,
I'm using Seurat to analyze Differential Gene Expression, I clustered the cells, what I wana do know is to go to cluster 1 for example and get a list from high to low of the mean of gene expression in this cluster, how do I do that? 
```R
norm.data <- data.frame(mean.exp = rowMeans(expm1(x = object@data)))
norm.data <- norm.data[order(norm.data$mean.exp, decreasing = TRUE),, drop = FALSE] 
```
I wrote this, but his gives me the list in all the cells, how do I specify a specific cluster?
Thakn you for your help

**Comment by leonfodoulian** [comment]
Hi @EDYAC,

You can subset the Seurat object to a specific cluster before hand using `Seurat::SubsetData()`. For more info, please check the documentation of the function.

Best,
Leon
