### ISSUE TITLE
Analyzing scATAC seq from barcodes.tsv.gz,  matrix.mtx.gz,  peaks.bed.gz files

### ISSUE THREAD

**Issue by mariamnawaz1** [satijalab/seurat#6270]
Hi,

I am analyzing scATACseq data from a cellranger-atac count function output and have only these 3 files: barcodes.tsv.gz  matrix.mtx.gz  peaks.bed.gz. I couldn't find a way to read them to create a count matrix and eventually a Seurat object. I tried using Read10x but got an error  "Gene name or features file missing. Expecting features.tsv.gz".
Is there any way I can read those files or a way to convert them into .h5 file format which is what has been used as an input in this [tutorial ](https://satijalab.org/signac/articles/pbmc_vignette.html) that I am following? 

P.S. I am new to Single-cell analysis.

Thanks!

**Comment by Liripo** [comment]
@mariamnawaz1 you should use [signac](https://satijalab.org/signac/articles/pbmc_vignette.html)

**Comment by mariamnawaz1** [comment]
> @mariamnawaz1 you should use [signac](https://satijalab.org/signac/articles/pbmc_vignette.html)

@Liripo ,  I am using the same tutorial, but to start with I need a .h5 file according to this tutorial. Could you please specify what do you mean?

**Comment by torkencz** [comment]
Hi,
An H5 file should've been created from cellranger. Alternately, you can create a features file from your bed file (with awk for instance) and read it in the way you were trying to. Down the line you have to create a chromatin assay from that and add the fragment files.
