### ISSUE TITLE
Using Personal Reference in Azimuth

### ISSUE THREAD

**Issue by xsun1229** [satijalab/seurat#6276]
Hi! 

I am trying to annotate my dataset with Azimuth in R but using my own reference dataset. I have some questions about how to format my own reference dataset. 

I think the function RunAzimuth(query,reference) should be the function I need. 'reference' here is the name of a path to a directory containing my own ref.Rds and idx.annoy. 

The question rise here. I have some difficulties preparing these two files. I found a [wiki page](https://github.com/satijalab/azimuth/wiki/Azimuth-Reference-Format) explaining the files. If I understand correctly, the ref.Rds file is a seurat object containing the slot you mentioned in the page while the idx.annoy contains annoy index. I am confused what dose this format look like. How can I generate such file? I find an example [here](https://seurat.nygenome.org/references/pbmc/) but I cannot 
load the idx.annoy file into R. 

Could you please give some suggestions on how to generate the ref.Rds and idx.annoy if I already have a seurat object which I want to use as a reference? 

Thank you! 
Xiaotong

**Comment by AustinHartman** [comment]
Hi - I'd recommend using the `AzimuthReference` function from Azimuth to convert your Seurat object into the proper reference format. You can save the ref.Rds and idx.annoy using the output of `AzimuthReference` with `saveRDS(object = ref, file = '/your/directory/ref.Rds')`
and `SaveAnnoyIndex(object = ref[["refdr.annoy.neighbors"]], file = '/your/directory/idx.annoy')`.  Then you should be able to annotate your dataset with `query <- RunAzimuth(query, '/your/directory')`
