### ISSUE TITLE
Workflow question with cell cycle and SCTransform

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6279]
I know there are other posts about this but I find them very confusing as I am new to scRNAseq and R.  I have three gentoypes I need to integrate.  Can someone tell me if this workflow is valid:

```
1. Calculate % mitochondrial genes
2. Filter out low quality cells
3. SCTransform
4. Calculate Cell Scores
5. Create a list of all three genotypes
6. SelectIntegrationFeatures()
7. PrepSCTIntegration()
8. FindIntegrationAnchors()
9. IntegrateData()
10. ScaleData(integratedObject, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(integratedObject))
11. RunPCA(integratedObject, features = c(s.genes, g2m.genes))
12. RunUMAP()
13. FindNeighbors()
14. FindClusters()
```

Does this seem reasonable?  Really appreciate the help.

Thanks,
Stacy

**Comment by Ahmedalaraby20** [comment]
10. ScaleData(integratedObject, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(integratedObject))
using rownames might not be a good idea, this will inflate the size of your obj I would use variable features instead, 
11. RunPCA(integratedObject, features = c(s.genes, g2m.genes))
not sure why you are using features = c(s.genes, g2m.genes), what do you want to do?

**Comment by stacygenovese** [comment]
Thanks...I took those two lines straight from the Seurat cell cycle
vignette.  I'm using SCTransform so am not running FindVariableFeatures().

I'm trying to just make sure my cells aren't clustering based on cell
cycle and not based on type of cell.  Maybe this isn't necessary but I was
following along with the vignette and Seurat Issue #3665.

**Comment by Ahmedalaraby20** [comment]
@stacygenovese I would just do something like this

```
10. integratedObject <- RunPCA(integratedObject, vars.to.regress = c("S.Score", "G2M.Score"), verbose = TRUE)
11. ElbowPlot
12. FindNeighbors()
13.  FindClusters()
14. RunUMAP()
```
you don't need to scale your dataset after integration, you can check out this for more help, 
[https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1
](url)

another way around it is to delete all CC genes from your dataset

```
counts <- GetAssayData(integratedObject, assay = "RNA")
counts <- counts[-(which(rownames(counts) %in% c(CCgenesnameslist))),] 
integratedObjectNOCCgenes<- subset(integratedObject, features = rownames(counts))
```

if things do not work just let me know I can take a look at your code and maybe I can help
