### ISSUE TITLE
I want to further cluster and annotate my macrophage subpopulations in more detail.

### ISSUE THREAD

**Issue by MaJiakang** [satijalab/seurat#6280]
When I integrated my single-cell data using the findintegrationanchors and integrateddata functions. I want to further cluster and annotate my macrophage subpopulations in more detail, such as M1 macrophages and M2 macrophages. Unfortunately, I don't know how to deal with this matter now.I try to write down the processing code by myself, but I have no ability to judge whether it is correct or not.

DefaultAssay(obj.combined) <- "integrated"
Idents(obj.combined) <- 'cell_type'

sce_Macrophage<- subset(obj.combined, idents = "Mono/Macro")
all.genes <- rownames(sce_Macrophage[["RNA"]]@data)
sce_Macrophage <- ScaleData(sce_Macrophage, features = all.genes)
sce_Macrophage <- RunPCA(sce_Macrophage, npcs = 30, verbose = FALSE)
sce_Macrophage <- RunUMAP(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindNeighbors(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindClusters(sce_Macrophage, resolution = 0.4)

**Comment by Ahmedalaraby20** [comment]
I see no issue here, 
however, I would suggest that you run findvariable and use `sce_Macrophage <- ScaleData(sce_Macrophage, features = features = VariableFeatures(sce_Macrophage ))`

If the issue is that after subculsturing your cells are not culturing into M0/1/2 then I would suggest that you increase the resusion in `FindClusters`

**Comment by MaJiakang** [comment]
Thank you for spending your precious time helping me with this issue. Your suggestion is to tell me to recalculate the variable features in the macrophage cluster, and then go to the next step. Based on your suggestion, I re-wrote the code as follows.

DefaultAssay(obj.combined) <- "integrated"
Idents(obj.combined) <- 'cell_type'
sce_Macrophage<- subset(obj.combined, idents = "Mono/Macro")
sce_Macrophage <- FindVariableFeatures(sce_Macrophage, selection.method = "vst", nfeatures = 2000)
sce_Macrophage <- ScaleData(sce_Macrophage, features =VariableFeatures(sce_Macrophage ) )
sce_Macrophage <- RunPCA(sce_Macrophage, npcs = 30, verbose = FALSE)
sce_Macrophage <- RunUMAP(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindNeighbors(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindClusters(sce_Macrophage, resolution = 0.4)

**Comment by MaJiakang** [comment]
> I see no issue here, however, I would suggest that you run findvariable and use `sce_Macrophage <- ScaleData(sce_Macrophage, features = features = VariableFeatures(sce_Macrophage ))`
> 
> If the issue is that after subculsturing your cells are not culturing into M0/1/2 then I would suggest that you increase the resusion in `FindClusters`
Thank you for spending your precious time helping me with this issue. Maybe I should reintegrate my data like the code below. But as a beginner, I still don't know if it's right or not.
DefaultAssay(obj.combined) <- "RNA"
Idents(obj.combined) <- 'cell_type'
sce_Macrophage <- subset(x = obj.combined, idents = "Mono/Macro")
Subset_Cells.list <- SplitObject(sce_Macrophage, split.by = "orig.ident")
for (i in 1:length(Subset_Cells.list)) {
  Subset_Cells.list[[i]] <- NormalizeData(Subset_Cells.list[[i]], verbose = FALSE)
  Subset_Cells.list[[i]] <- FindVariableFeatures(Subset_Cells.list[[i]], selection.method = "vst", nfeatures = 2000,verbose = FALSE)
}
Integrated <- FindIntegrationAnchors(object.list = Subset_Cells.list, dims = 1:30)
Integrated <- IntegrateData(anchorset = Integrated, dims = 1:30)
DefaultAssay(object = Integrated) <- "integrated"
combined<-  ScaleData(Integrated,verbose = FALSE)
combined <- RunPCA(object = combined, npcs = 24, verbose = FALSE)
combined <- RunUMAP(object = combined, reduction = "pca", dims = 1:24)
combined <- FindNeighbors(object = combined, reduction = "pca", dims = 1:24)
combined <- FindClusters(combined, resolution = 0.4)

**Comment by Ahmedalaraby20** [comment]
I usually go with the first option 
Maybe if it is wrong someone might suggest something else

```
DefaultAssay(obj.combined) <- "integrated"
Idents(obj.combined) <- 'cell_type'
sce_Macrophage<- subset(obj.combined, idents = "Mono/Macro")
sce_Macrophage <- FindVariableFeatures(sce_Macrophage, selection.method = "vst", nfeatures = 2000)
sce_Macrophage <- ScaleData(sce_Macrophage, features =VariableFeatures(sce_Macrophage ) )
sce_Macrophage <- RunPCA(sce_Macrophage, npcs = 30, verbose = FALSE)
sce_Macrophage <- RunUMAP(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindNeighbors(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindClusters(sce_Macrophage, resolution = 0.4)
```
If you need any further help let me know, maybe I can also take a look at your script in case you still need help

**Comment by MaJiakang** [comment]
Thank you, professor. I really appreciate your help. 
感谢您！

**Comment by yuhanH** [comment]
hi @Ahmedalaraby20 
Thank you for your helpful comments!  I agree that you can follow the first option to define sub-clusters.
Also, if two types of macrophages already show some clear separation in your full integrated data, you can just start with PCA step. 
```
DefaultAssay(obj.combined) <- "integrated"
Idents(obj.combined) <- 'cell_type'
sce_Macrophage<- subset(obj.combined, idents = "Mono/Macro")
sce_Macrophage <- RunPCA(sce_Macrophage, npcs = 30, verbose = FALSE)
sce_Macrophage <- RunUMAP(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindNeighbors(sce_Macrophage, reduction = "pca", dims = 1:20)
sce_Macrophage <- FindClusters(sce_Macrophage, resolution = 0.4)
```
