### ISSUE TITLE
Merging multiple hashed samples and QC on invididual ones

### ISSUE THREAD

**Issue by learning-MD** [satijalab/seurat#6281]
Hi,

I have 8 separate runs of PBMCs from patients, hashing together 5 samples per run (using TotalSeqC HTOs). I am following the demultiplexing vignette (https://satijalab.org/seurat/articles/hashing_vignette.html) for each multiplexed sample and identifying the individual samples. I have the following 2 questions:

1. My understanding is that, despite normalization, feature selection, and clustering, when I merge together all 8 multiplexed samples using merge(), that Seurat is merging the raw count matrices, so I can rerun the [NormalizeData()](https://satijalab.org/seurat/reference/NormalizeData.html), [ScaleData()](https://satijalab.org/seurat/reference/ScaleData.html), and [FindVariableFeatures()](https://satijalab.org/seurat/reference/FindVariableFeatures.html) processes on the fully merged dataset of 40 patient samples. I wanted to confirm that this accurate.

2. When working with tissue-specific samples run individually in 10x lanes, I've been able to incorporate stringent QC (e.g., subseting features for [3rd quartile + 1.5(IQR)] the nCounts and nFeatures). Currently, I'm just visually evaluating the FeatureScatter plots (as per the guided clustering tutorial) and subsetting features with cutoffs based on that. Is there a way to interrogate each hashed sample individually to perform sample-level QC or is the way I'm doing it right now the "best" way to do so with hashed samples?

Thanks in advance!

**Comment by Ahmedalaraby20** [comment]
For 
1. I would actually try to integrate the samples, it might give me some peace of mind that there is no batch effect, assuming that you don't overload the 10x system you will roughly end with 80k cells that can be easily integrated 
[https://satijalab.org/seurat/articles/integration_introduction.html#introduction-to-scrna-seq-integration-1](url)
of course you have to do the QC before starting the integration. 

2. I do a single x10 run alone assuming that the cells for each sample are treated the same and I visualize the QC parameter after filtering and usually they are comparable however if you wish to treat every sample separately you can use 
`Hashtags <- SplitObject(GEX, split.by="HTO_classification") /
sample1<- Hashtags[["hashtagename1"]] 
`
I honestly would not do that given that I work with samples that are prepared and treated the same.

**Comment by learning-MD** [comment]
Thanks @Ahmedalaraby20!

1. I use Harmony for batch effect correction - treating each patient as their own batch. For that reason, I was planning on merging rather than integrating the samples.
2. Thanks - I ended up just doing QC based on the visual inspection of nFeature_RNA and nCount_RNA plots for the hashed samples, along with a mitochondrial cutoff of <15%.

**Comment by mhkowalski** [comment]
Hello, sure you can look at QC metrics individually for each sample. You could do this by splitting the object as suggested above, or plotting violin plots with the option ```group.by="HTO_classification```. It may be worthwhile to investigate if your samples have similar QC metrics as this could effect downstream analysis.
