### ISSUE TITLE
Correct way to subset cells

### ISSUE THREAD

**Issue by elifozcelik** [satijalab/seurat#6282]
Hi, I am trying to subset a part of my data and re-cluster them. However, I am not sure about the steps I have to follow. My general data is already normalized & scaled, should I re-do it? I will paste my code block below. I use an integrated data. Thanks!

Tnumtry <- subset(diet.combined2, idents = c("10","12","7","4","13")) #clusters that I want to re-cluster
t.count <- GetAssayData(Tnumtry, slot= 'counts')
t_objects <- SetAssayData(
    object = Tnumtry,
    slot = 'counts',
    new.data = t.count,
    assay = 'RNA'
)

DefaultAssay(t_objects) <- 'integrated'
t_objects <- RunPCA(t_objects, npcs = 15, verbose = FALSE)
t_objects <- FindNeighbors(t_objects, reduction = "pca", dims = 1:15)
t_objects <- FindClusters(t_objects, resolution = 0.5)
t_objects <- RunUMAP(t_objects, reduction = "pca", dims = 1:15)
DimPlot(t_objects, reduction = "umap", label = TRUE)

DefaultAssay(t_objects) <- "RNA"
t_objects <- NormalizeData(t_objects)
t_objects <- ScaleData(t_objects)

**Comment by AustinHartman** [comment]
I'd recommend rescaling your subsetted data before re-runnning PCA because the data will no longer be centered after subsetting. Let me know if that answers your question

**Comment by elifozcelik** [comment]
Hi do you mean re-scaling the integrated data? Thanks a lot.
