### ISSUE TITLE
How to create a heatmap of Seurat object based on manual selection of three populations (based on 2 features)?

### ISSUE THREAD

**Issue by liljahardar** [satijalab/seurat#6284]
I have a Seurat object and want to create a heatmap with a gene list separated by three populations that I manually select by the expression of two genes.

I would like the three populations to have these gene expression patterns:

Pop1: Gene X expression < 1.5
Pop2: Gene X expression > 1.5, Gene Y expression > 1
Pop3: Gene X expression > 1.5, Gene Y expression < 1

I was able to create a metadata column with selective expression of one gene but could not find a way to do it with the above-mentioned selective expression of the two genes and put that info into one metadata column. 

This is what I did to add the info of the first gene into metadata: 

GeneX <- WhichCells(Seurat_Object, expression = GeneX > 1.5
Seurat_Object$GeneX<- ifelse(colnames(Seurat_Object) %in% GeneX, "Pos", "Neg")
DoHeatmap(Seurat_Object, features = mygenelist, group.by="GeneX")

Is there a way to do this in a rather simple way?

**Comment by yuhanH** [comment]
hi @liljahardar 
I think what you did is correct. There is not a better way to do this.
