### ISSUE TITLE
VlnPlot - Error in if (all(data[, feature] == data[, feature][1])) { :  missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by ryXnATP** [satijalab/seurat#6285]
I am currently faced with an issue regarding the development of a VlnPlot. I have literally just run everything on my donor01 sample, so all thats changed coding wise is the fact that it is donor 02 instead of donor 01. 

VlnPlot(donor02, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"), ncol = 3)

returns with:

Error in if (all(data[, feature] == data[, feature][1])) { : 
missing value where TRUE/FALSE needed

As a newcomer to R, could anybody advise on what i need to change and how to understand this issue in case it comes up again?

**Comment by andrewwbutler** [comment]
Hi,

I would check that you don't have any `NA` or missing values in any of the features you are trying to plot. E.g.

```R
which(is.na(donor02$percent.mito))
```

If you do have `NA` or missing values for one or more of these features, I would try to figure out why any of these are missing before continuing with the analysis/visualization.

**Comment by peterzhao1998** [comment]
Kind of a reminder to myself

Sometimes, the row.name of the meta.data might change when you process the data. Therefore, the vlnplot() or subset() cannot find the cell you want based on the cell name. 

What you can do is

`rownames(s@meta.data) <- Cells(s)`

Where "s" is your Seurat object

**Comment by apal6** [comment]
Hi, I am having the same issue. I have processed multiple samples previously using the same seurat processing workflow but now i  get this weird error which suggests to me that something is breaking in the create seurat object function. 

script:
sobj <- CreateSeuratObject(counts = laminaProporia, project = "laminaPropria", min.cells = 3, min.features = 200)
grep ("^MT-", rownames(sobj[["RNA"]]),value = T)
`[1] "MT-ND1"  "MT-ND2"  "MT-CO1"  "MT-CO2"  "MT-ATP8" "MT-ATP6" "MT-CO3"  "MT-ND3"  "MT-ND4L" "MT-ND4" 
[11] "MT-ND5"  "MT-ND6"  "MT-CYB" `
sobj[["percent.mt"]] <- PercentageFeatureSet(sobj, pattern = "^MT")

VlnPlot(sobj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

error: `Warning: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Error in if (all(data[, feature] == data[, feature][1])) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: The following requested variables were not found: nFeature_RNA, nCount_RNA 
2: Removing 39566 cells missing data for vars requested `

Could you please help?

Thank you!

**Comment by yamihn** [comment]
> Hi, I am having the same issue. I have processed multiple samples previously using the same seurat processing workflow but now i get this weird error which suggests to me that something is breaking in the create seurat object function.
> 
> script: sobj <- CreateSeuratObject(counts = laminaProporia, project = "laminaPropria", min.cells = 3, min.features = 200) grep ("^MT-", rownames(sobj[["RNA"]]),value = T) `[1] "MT-ND1" "MT-ND2" "MT-CO1" "MT-CO2" "MT-ATP8" "MT-ATP6" "MT-CO3" "MT-ND3" "MT-ND4L" "MT-ND4" [11] "MT-ND5" "MT-ND6" "MT-CYB" ` sobj[["percent.mt"]] <- PercentageFeatureSet(sobj, pattern = "^MT")
> 
> VlnPlot(sobj, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
> 
> error: `Warning: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead. Error in if (all(data[, feature] == data[, feature][1])) { : missing value where TRUE/FALSE needed In addition: Warning messages: 1: The following requested variables were not found: nFeature_RNA, nCount_RNA 2: Removing 39566 cells missing data for vars requested `
> 
> Could you please help?
> 
> Thank you!

Hi, you should set options(Seurat.object.assay.calcn = TRUE) before creating seurat object.
it worked for me
