### ISSUE TITLE
MY BRAIN IS "^mt-"  

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#629]
```R
mito.genes.All<- grep(pattern = "^mt-", x = rownames(x =All@data), value = TRUE)
```

As I understand when you type this, you get the 13 mitochondrial genes, my question is how those 13 genes are found? is the list already  built in Seurat?

Thank you,

**Comment by chlee-tabin** [comment]
It comes from the All@data, so the gene names are imported from your own data. It is possible that the mitochondrial genes do not start with "mt-".

**Comment by EDYAC** [comment]
This is exactly how, the genes all start with mt lol, thank you, now I'm able to call out the MHC2 genes they all start with H2, I learned something, MY BRAIN IS "^mt-"ier
