### ISSUE TITLE
FindMarkers without specifying a 2nd cluster 

### ISSUE THREAD

**Issue by LaviCor** [satijalab/seurat#6290]
Hello all,
Something I was wandering about now that I started to understand a bit better what the functions I'm using actually do.

So FindAllMarkers compares each cluster to all other cluster to get their differentially expressed genes.
FindMarkers work similarly but when comparing gene expression between 2 clusters.

However when running FindMarkers without specifying a cluster for ident.2, the function runs correctly, and returns a similar gene list to what I get for a given cluster when running FindAllMarks.
Does is work the same? or is there some sort of core difference between the two functions? (aside from the number of genes returned by default for each cluster)

Thanks in advance

**Comment by LaviCor** [comment]
@samuel-marsh was suspecting something along these lines, thanks for making it clear!

**Comment by samuel-marsh** [comment]
Happy to help!
