### ISSUE TITLE
Add "ncol=" argument to ImageFeaturePlot() and ImageDimPlot()

### ISSUE THREAD

**Issue by pander21** [satijalab/seurat#6291]
Functions FeaturePlot() and DimPlot() have `ncol=` argument that can be used to control how are plots of individual genes arranged into a grid.

In contrast, ImageFeaturePlot() function does not have this argument. This becomes especially problematic if multiple fields of view are plotted in one function call by passing a vector of FOVs into `fov=` argument as the individual plots are arranged into grid in a very messy way. It would be great to have ncol= argument added also to ImageFeaturePlot() and ImageDimPlot(). 
Thank you!

**Comment by AustinHartman** [comment]
Hi @pander21, I agree this would be useful to add, but is not currently on the roadmap. I'd recommend building individual plots by calling `ImageFeaturePlot` and `ImageDimPlot` multiple times and organizing the plots as desired using `patchwork`
