### ISSUE TITLE
Problem package Seurat with R 4.2.1

### ISSUE THREAD

**Issue by emanuelavilla** [satijalab/seurat#6293]
Hello, Satija lab!

Recently, I downloaded version 4.2.1 of R in Rstudio. Then, I installed the Seurat package in my library. However, when I call the library, I got an error

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Rstudio-4.2-lib/rgeos/libs/rgeos.so':
  libgeos_c.so.1: cannot open shared object file: No such file or directory

I cannot understand what the problem is.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  It appears to be issue with rgeos and libgeo.  Try the solutions posted in this post and the one below here to see if that can resolve your issue.
https://github.com/satijalab/seurat/issues/5962#issuecomment-1146264495

Best,
Sam

**Comment by longmanz** [comment]
Hi @emanuelavilla, 
Just as @samuel-marsh mentioned you will need to install rgeos and libgeo. You may install it from the source https://libgeos.org/. 

Best,
Longda
