### ISSUE TITLE
Sctransform - Noisy UMAP 

### ISSUE THREAD

**Issue by Sayyam-Shah** [satijalab/seurat#6294]
Hello @saketkc,

Thank you for the amazing tool. Sctransform version 2 has performed extremely well with my bone marrow data. However, I noticed some noisiness with my cord blood data. I compared the UMAP to TPM normalized data.

![image](https://user-images.githubusercontent.com/102439837/184238828-f49ff1f3-8195-4e65-86b6-79a2cf0a2bb8.png)
Above is my sctransform normalized UMAP.

![image](https://user-images.githubusercontent.com/102439837/184238912-9c4e1525-f721-4ccf-b6e9-768a40bd62ab.png)
Above is my TPM normalized UMAP.

What factors may be contributing to the noisiness with the sctransform normalized UMAP? How may I generate a clean UMAP while still using sctransform. This definitely came as a surprise since sctransform performed very well with my other dataset.

Best Regards,
Sayyam

**Comment by saketkc** [comment]
Hi @Sayyam-Shah, it is hard to say anything without being able to look at the data. But one thing I could recommend is looking at the range of residuals - the default clip range is set to -sqrt(n/30), sqrt(n/30) which can be very liberal if you have a large number of cells with batch effects. If so, I would recommend setting the `clip.range=c(-10,10)`.

**Comment by Sayyam-Shah** [comment]
Thank you so much! I'll try that.
