### ISSUE TITLE
Add metadata to samples after making seurat object. 

### ISSUE THREAD

**Issue by callmcgovern** [satijalab/seurat#6297]
Hi, I have 11 samples that are grouped in three different genotypes (homozygote, heterozygote, wild type). I have made the seurat object for all the single cell data in all 11 samples but now I would like to add a column to the meta data of the seurat object that corresponds to that samples genotype. I know there is a function Addmetadata() but to my understanding this function associates metadata with either cells or features, not for samples. The sample names are currently the Orig.idents of my seurat object so it there a way to assign the various orig.idents their genotypes? 
Thank you for the help!

**Comment by mhkowalski** [comment]
Hello! Yes you are correct that the metadata corresponds to cells. You would have to assign genotypes to each cell based on what sample they came from by creating a new column in the metadata. Here is a rough overview of one way you could do this: 

seurat_obj$genotype <- NA # initialize a new metadata column
seurat_obj$genotype[seurat_obj$orig.ident == "sample1"] <- "WT" #assign genotype for each sample

**Comment by callmcgovern** [comment]
Thank you so much for the assistance @mhkowalski !!
