### ISSUE TITLE
Sctransform - Scanpy 

### ISSUE THREAD

**Issue by Sayyam-Shah** [satijalab/seurat#6298]
Hello @saketkc,

Do you guys have any plans of adding sctransform vst 2 on Scanpy? I believe it will reach a broader audience and accelerate the field by allowing accessibility to this amazing tool in both python and R. 

Thank you,
Sayyam

**Comment by saketkc** [comment]
Hi @Sayyam-Shah, we do have a python implementation that you can use in your scanpy workflow: https://github.com/saketkc/pysctransform

**Comment by Sayyam-Shah** [comment]
Does this follow version 2?

**Comment by saketkc** [comment]
Yes, using `v2` however requires rpy2, see demo [notebook](https://github.com/saketkc/pySCTransform/blob/develop/notebooks/demo.ipynb) for an example.

**Comment by Sayyam-Shah** [comment]
Thank you, sorry does it also create the data slot and counts slot from sctransform? Non-negative corrected UMI counts

**Comment by saketkc** [comment]
Yes, it returns a dictionary with all the elements, that you can pull into scanpy.

**Comment by Sayyam-Shah** [comment]
Thank you so much! This is amazing.
