### ISSUE TITLE
Merge function for SCTransformed Seurat object

### ISSUE THREAD

**Issue by SBaek613** [satijalab/seurat#6299]
Hi, 

I have a question regarding merge function for SCTransformed Seurat object.

I am running SCTransform on per sample basis as suggested by previous issues and tutorials.
It works great when I am using all the cells from all the samples since most of the samples have decent amount of cells so there would be no genes dropping for low expression. 

However, I am also trying to subset the total object (say subsetting CD8 T cell only) and rerun the process. But since some samples end up having only a few cells and running SCTransform on per sample basis removes lowly expressed genes (I could try to set min_cells =0 to avoid that but I feel like that could mess up the whole matrix), merging all the samples together creates scale.data slot with genes shared by all the samples. 

So when I try to use SelectIntegrationFeatures (which also only takes genes shared by all samples, but I modified it to not do that since those lines were just removing so many genes for cell types with low cell counts) to add variable genes to merged object and runPCA, a lot of the variable genes are not considered during PCA since they are not in the scale.data matrix. 

I saw from the document that merge function for SCTAssay object (merge.SCTAssay) has na.rm parameter which seems to be set to FALSE to prevent removing genes from scale.data slot but it just doesn't seem to work for Seurat object with SCT as default assay.

Now I am kinda stuck with how to get around this issue. (also my samples after subsetting still had at least 50~100 cells per sample)

I have tried...
1. Just let runPCA ignore all the genes not in scale.data slot. (Sometimes there were only 300-400 genes out of 2000 variable genes). Results weren't too bad and I was able to identify cell subtypes but running PCA with that few genes doesn't feel right when there are a lot more variable genes.
2. making empty sparse matrix with genes removed after SCTransform and rbind to SCT count matrix so that scale.data slot won't be filtered. But adding genes to Seurat object doesn't really seem to work.
3. set min_cells = 0. But I am not sure what it will do to whole distribution and correction.
4. set do.correct.umi = FALSE, but that feels like just losing purpose of SCTransform.
5. Perform SCTransform on some group basis rather than per sample basis but the result was even worse than running (1) in terms of marker gene separation and such.

Would there be any suggestions or work-around methods so that merged object doesn't have scale.data slot with only shared genes?

Thanks for reading a long question.

**Comment by saketkc** [comment]
If you are subsetting a subpupulation of cells, you need not necessarily run SCTransform again, though you would want to re-run RunPCA. The variable features for RunPCA can themselves be defined in alternate ways and `SelectIntegrationFeatures` is one way to do that.  As an aside, you can ppulate the `scale.data` slot for any gene besides the variable features by using [GetResidual](https://satijalab.org/seurat/reference/getresidual) function - so you can populate the residuals for any set of genes before merging the different SCT objects.
