### ISSUE TITLE
SNN graph question

### ISSUE THREAD

**Issue by agelber** [satijalab/seurat#63]
Hi,

I've been using Seurat for a short while now based on the tutorial and it's been immensely useful , thank you!

I'm trying to better understand some of the algorithms and implementations and I have a question about the SNN graph.  If it's a constructing a KNN graph, shouldn't the minimum number of edges a given vertex has be k? I checked the minimum sum(object@snn.dense[,i]>0) and found a column with only one entry in it (the cell itself). Why is this? 

Best,
Alon

**Comment by andrewwbutler** [comment]
Hi Alon,

You're right that the first KNN graph that is computed should have k edges per vertex. When we go on to construct the SNN graph, (which looks at the shared neighborhoods of two cells) if the overlap in neighborhoods isn't strong enough, we'll throw out that edge. This threshold is controlled by the `prune.SNN` parameter. 

It's possible that for that cell, there aren't any other cells that pass this threshold.

**Comment by agelber** [comment]
Thank you!
