### ISSUE TITLE
How do you integrate datasets from 4 tumors?

### ISSUE THREAD

**Issue by shwetajohari** [satijalab/seurat#6300]
Hello,
My name is Shweta Johari and I have analyzed the four tumors separately but that is not what is expected of me.
Hence, I would like to know how to integrate the four datasets.
These four tumors are treated differently as control and treatment. In the example dataset is shown to be split by "stim" but how do I do it? 
In addition, these tumors were run by CMO of 10X genomics. 
Can someone please help on how to integrate these datsets? 

Thank you so much.

Kind Regards,
Shweta Johari

**Comment by torkencz** [comment]
Hi, if I understand correctly I would integrate based on your datasets (so the 4 tumors), not on the stim. You should be able to do that based on the any of the integration vignettes.

**Comment by shwetajohari** [comment]
Hello
Thank you so much for the response. However, I did try but its not integrated.
Is the input the multi (CMO Tagged) -feature, matrix, and barcode or are the input individual feature matrix and barcode file? 
Also, how will I be able to split the data?

Thank you again. 

Kind Regards,
Shweta Johari
