### ISSUE TITLE
Why do "data" slot of SCT Assay and RNA Assay have different number of genes?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6303]
Hi there, 

Would you mind clarifying again why `GetAssayData()` of the same Seurat object returns different numbers of log-normalized genes for the same number of cells when I set `assay="RNA"` vs `assay="SCT"`? 

Related to #5916 

Thank you for your help.

**Comment by saketkc** [comment]
By [default](https://github.com/satijalab/sctransform/blob/d962a4a858e5d4b0d69abe8ac54cf534eec010b8/R/vst.R#L122), SCT only considers gene expressed if they are expressed (UMI >=1) in a minimum of 5 cells. You can change this by passing the `min_cells=1` parameter to `SCTransform()`, but that would require invoking the `vst.flavor=“v2”` as well.
