### ISSUE TITLE
Error in performing integration

### ISSUE THREAD

**Issue by raman91** [satijalab/seurat#6304]
Hi,

I am integrating my data with one of the public data using the below command -
immune.combined <- IntegrateData(anchorset = immune.anchors)

But i get the following error:

Error in RowMergeMatricesList(mat_list = all.mat, mat_rownames = all.rownames,  : 
  Expecting a string vector: [type=NULL; required=STRSXP]

Could you pls let me know what can be the cause of this error?

Thank you

**Comment by AustinHartman** [comment]
Hi, could you please post your `sessionInfo()` and a small reproducible example if possible so we can better assess whats going on?
