### ISSUE TITLE
PrepSCTFindMarkers() is slow: "Recorrecting SCT counts using minimum median counts"

### ISSUE THREAD

**Issue by lwtan90** [satijalab/seurat#6309]
Hi,

I love using Seurat for all single-cell analysis, but I can't help to provide a user feedback on the PrepSCTFindMarkers() function. It is extremely slow even for a 8000 cells data sets.
Are there any way to speed this up?
Thank you.

Wilson

**Comment by Ruismart** [comment]
same issue right now, half hour to run findallmarkers for a similar datasize, but 3 hours have past, no any other info except "Recorrecting SCT counts using minimum median counts: xxxx"

**Comment by saketkc** [comment]
Thanks for the report. We are aware of this and will work on improving the speed. It can particularly be slow if there are multiple large datasets since the model needs to regenerate corrected counts for each one of them separately. One way to avoid this would be to pre-calculate the mininum of the median UMI across datasets and pass this to SCTransform, something like `SCTransform(scale.factor=5159)` where 5159 is the minimum of `median(object$nCount_RNA)` across datasets - you can skip the `PrepSCTFindMarkers()` step this way.

**Comment by realzehuali** [comment]
I am crying. I have got 98 datasets and 2M cells to run. I am desperate now.

**Comment by vincycheng** [comment]
@realzehuali May I ask how long it ended up taking? I am a similar size dataset and would like to have a better estimate of time. Thanks!

**Comment by realzehuali** [comment]
@vincycheng 3 days in the end.

**Comment by vincycheng** [comment]
@saketkc 
Following up on this thread. I have once again an integration with 8 datasets, each with 10-50k cells, and the PrepSCTFindMarkers() function takes longer than 4 days already. 
If I want to use the scale_factor as you mentioned before, how do I archive it in an integrated object? Do I just rerun the SCTransform at the SCT slot? Does this work with v2? Or do I need to go back to the pre-integration step to do that? The goal for me is to be able to run FindMarkers().
Thanks!

**Comment by saketkc** [comment]
@vincycheng  Yes, you should just rerun SCTransform for all objects separately with the same scale_factor (no need to do integration again).

**Comment by vincycheng** [comment]
Thank you @saketkc for your reply. Could you clarify how to do it? I am not sure what do you mean by "rerun SCTransform for all objects separately". Thanks!

**Comment by saketkc** [comment]
```r
ob.list <- lapply(X = ob.list, SCTransform, vst.flavor="v2", scale_factor=<NUM>)
```

**Comment by vincycheng** [comment]
> ```r
> ob.list <- lapply(X = ob.list, SCTransform, vst.flavor="v2", scale_factor=<NUM>)
> ```
> 
> where is the minimum among the `median(ob$nCount_RNA)` among all your objects.

I see what you mean, but like I mentioned before, my goal is to use FindMarker() in the integrated object to find differential genes in two conditions within the same cluster, that means I will need to get the proper SCT counts in the integrated object. Is there an easy way to archive it?

**Comment by saketkc** [comment]
Once you have the clusters in your integrated objects, you can extract that as a column from the metadata, and create a merged object with `ob.list` and add it back there.

```r
seurat_clusters <- ob.integrated$seurat_clusters
ob.merge <- merge(ob.list[[1]], ob.list[2:length(ob.list)]
ob.merge <- AddMetaData(ob.merge, meta.data=seurat_clusters, col.name="integrated_clusters")
```

**Comment by Angel-Wei** [comment]
Hi Saket, thanks for the solution. So just following up on this thread and your solution, I also did an integration of multiple objects (around 78K cells in total) via harmony and I was trying to call `PrepSCTFindMarkers()` to prepare for running `FindAllMarkers()` as well. However, it's been staying at 
`Found 4 SCT models. Recorrecting SCT counts using minimum median counts: 3648`
for a day and showing nothing else.

I wonder after I pasted back the metadata info of integrated_clusters to call FindAllMarkers() and when it's done, can I copy from the `ob.merge` and replace the `nCount_SCT` column in the integrated object? Perhaps better yet, also "tell" or render the integrated object to have 1 SCT model? Thanks for the help in advance!

**Comment by saketkc** [comment]
Hi Angel, I am sorry about the speed of recorrection step at the moment. It needs to be fixed in a future release. In the meanwhile, I would recommend following the steps above for recorrection. Once you have the integrated object and clusters, I do not see a reason why you would need to tell it that you have one model. 

What you could do to obtain what you are suggesting is to add back the correct counts data from the merged object to the integrated object (once you do this you can run FindMarkers on the integrated object by passing `recorrect.umi=FALSE` as the UMI has already been corrected. So the full set of steps would look like this:

```r
ob.list <- <My list of Seurat objects with RNA assay>
min_median_umi <- min(lapply(X = ob.list, FUN = function(x) median(x$nCount_RNA))
ob.list <- lapply(X = ob.list, SCTransform, vst.flavor="v2", scale_factor=min_median_umi)
ob.merged <- merge(ob.list[[1]], ob.list[2:length(ob.list)])

corrected_counts <- GetAssayData(ob.merged, assay = "SCT", slot="counts")
corrected_data <- GetAssayData(ob.merged, assay = "SCT", slot="data")
suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
                                           assay ="SCT",
                                           slot = "counts",
                                           new.data = corrected_counts)})
suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
                                           assay = "SCT",
                                           slot = "data",
                                           new.data = corrected_data)})

```

**Comment by Angel-Wei** [comment]
Got it! Thank you so much for your help Saket! All of my objects to be integrated are already SCTransformed. I guess I'll just replace the `median(x$nCount_RNA)` with `median(x$nCount_SCT)`. The method really helps with my problem. Thank you so much!

**Comment by Angel-Wei** [comment]
Oh yes, that makes sense! Thanks for the correction!

**Comment by Angel-Wei** [comment]
Hi Saket @saketkc ! I wonder is it possible that running this step:
`ob.list <- lapply(X = ob.list, SCTransform, scale_factor=min_median_umi)` 
could potentially change the number of features/genes within the object in a list? As after I merged the lists of objects, I found that the rownames(ob.merged) and rownames(object.integrated) were not perfectly matched when I called `SetAssayData`.

**Comment by saketkc** [comment]
Yes, totally possible. If the `scale_factor` changes, the number of features detected and the nCount_SCT will change.

**Comment by Angel-Wei** [comment]
Thanks for the quick reply Saket @saketkc! I think there are about ~700 genes reduced, I guess I'll probably subset my harmonized object by the number of genes/features of ob.merged like:
harmonized_seur <- harmonized_seur[rownames(ob.merged),]
if this can be considered as a general practice when dealing situations like this. Just to be certain, the `SetAssayData` function helps to find the one-to-one match when replacing the data right? No need to reorder rownames or cellnames by ourselves?

**Comment by saketkc** [comment]
No need to reorder. These genes are also lowly expressed genes (so a reduced scale factor causes there gene counts to be essentially zero). Also, if you set the `vst.flavor="v2"`, it should remain consistent through your analysis.

**Comment by Angel-Wei** [comment]
Sounds awesome! Thank you so much for the info!

**Comment by wangziqi0321** [comment]
> Hi Angel, I am sorry about the speed of recorrection step at the moment. It needs to be fixed in a future release. In the meanwhile, I would recommend following the steps above for recorrection. Once you have the integrated object and clusters, I do not see a reason why you would need to tell it that you have one model.
> 
> What you could do to obtain what you are suggesting is to add back the correct counts data from the merged object to the integrated object. Once you do this you can run FindMarkers on the integrated object by passing `recorrect.umi=FALSE` as the UMI has already been corrected. So the full set of steps would look like this:
> 
> ```r
> ob.list <- <My list of Seurat objects with RNA assay>
> min_median_umi <- min(lapply(X = ob.list, FUN = function(x) median(x$nCount_RNA))
> ob.list <- lapply(X = ob.list, SCTransform, vst.flavor="v2", scale_factor=min_median_umi)
> ob.merged <- merge(ob.list[[1]], ob.list[2:length(ob.list)])
> 
> corrected_counts <- GetAssayData(ob.merged, assay = "SCT", slot="counts")
> corrected_data <- GetAssayData(ob.merged, assay = "SCT", slot="data")
> suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
>                                            assay ="SCT",
>                                            slot = "counts",
>                                            new.data = corrected_counts)})
> suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
>                                            assay = "SCT",
>                                            slot = "data",
>                                            new.data = corrected_data)})
> markers <- FindAllMarkers(object.integrated, assay="SCT", recorrect_umi=FALSE)
> ```

Thanks very much for your code, really helps. I still have to more questions about this issue: 1、I've got two different mim

**Comment by wangziqi0321** [comment]
> Hi Angel, I am sorry about the speed of recorrection step at the moment. It needs to be fixed in a future release. In the meanwhile, I would recommend following the steps above for recorrection. Once you have the integrated object and clusters, I do not see a reason why you would need to tell it that you have one model.
> 
> What you could do to obtain what you are suggesting is to add back the correct counts data from the merged object to the integrated object. Once you do this you can run FindMarkers on the integrated object by passing `recorrect.umi=FALSE` as the UMI has already been corrected. So the full set of steps would look like this:
> 
> ```r
> ob.list <- <My list of Seurat objects with RNA assay>
> min_median_umi <- min(lapply(X = ob.list, FUN = function(x) median(x$nCount_RNA))
> ob.list <- lapply(X = ob.list, SCTransform, vst.flavor="v2", scale_factor=min_median_umi)
> ob.merged <- merge(ob.list[[1]], ob.list[2:length(ob.list)])
> 
> corrected_counts <- GetAssayData(ob.merged, assay = "SCT", slot="counts")
> corrected_data <- GetAssayData(ob.merged, assay = "SCT", slot="data")
> suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
>                                            assay ="SCT",
>                                            slot = "counts",
>                                            new.data = corrected_counts)})
> suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
>                                            assay = "SCT",
>                                            slot = "data",
>                                            new.data = corrected_data)})
> markers <- FindAllMarkers(object.integrated, assay="SCT", recorrect_umi=FALSE)
> ```
Thanks for your solution and it really helps. Yet I still have a question related to this issue and the code you provided: I've got two different minimum median counts using the code you provided (which is 1178) and the original PrepSCTFindMarkers function (which gives a minimum median counts of 997.5), so is this reasonable? And which minimum median counts should I choose for the subsequent analysis? 
Thanks!

**Comment by wangziqi0321** [comment]
> Hi Angel, I am sorry about the speed of recorrection step at the moment. It needs to be fixed in a future release. In the meanwhile, I would recommend following the steps above for recorrection. Once you have the integrated object and clusters, I do not see a reason why you would need to tell it that you have one model.
> 
> What you could do to obtain what you are suggesting is to add back the correct counts data from the merged object to the integrated object. Once you do this you can run FindMarkers on the integrated object by passing `recorrect.umi=FALSE` as the UMI has already been corrected. So the full set of steps would look like this:
> 
> ```r
> ob.list <- <My list of Seurat objects with RNA assay>
> min_median_umi <- min(lapply(X = ob.list, FUN = function(x) median(x$nCount_RNA))
> ob.list <- lapply(X = ob.list, SCTransform, vst.flavor="v2", scale_factor=min_median_umi)
> ob.merged <- merge(ob.list[[1]], ob.list[2:length(ob.list)])
> 
> corrected_counts <- GetAssayData(ob.merged, assay = "SCT", slot="counts")
> corrected_data <- GetAssayData(ob.merged, assay = "SCT", slot="data")
> suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
>                                            assay ="SCT",
>                                            slot = "counts",
>                                            new.data = corrected_counts)})
> suppressWarnings({object.integrated <- SetAssayData(object = object.integrated,
>                                            assay = "SCT",
>                                            slot = "data",
>                                            new.data = corrected_data)})
> markers <- FindAllMarkers(object.integrated, assay="SCT", recorrect_umi=FALSE)
> ```

And another question is: Can I do this on each seurat objects before the PCA and integration?Here are my codes 

min_median_umi <- min(unlist(lapply(file, FUN = function(x) median(x$nCount_RNA))))
  
  file[[i]] <- SCTransform(file[[i]], 
                           vst.flavor = "v2", 
                           vars.to.regress=c('nCount_RNA','percent.mito',
                                             'percent.ribo','percent.diss'),
                           scale_factor=min_median_umi,
                           verbose = TRUE)
  
  
  file[[i]] <- RunPCA(file[[i]],npcs = 30, verbose = TRUE)

then follows the SelectIntegrationFeatures, PrepSCTIntegration, FindIntegrationAnchors, and IntegrateData procedure. 

Thanks!

**Comment by saketkc** [comment]
Thanks everyone for your patience. https://github.com/satijalab/seurat/commit/e5171f7a6b2b1145753b0b1606d16e30d6b0984d should speed up `PrepSCTFindMarkers` by default (and also supports parallelization - though that might not always lead to speedups given the data splitting being a bottle neck).
