### ISSUE TITLE
Difference between min.features = 200 and nFeature_RNA > 200？

### ISSUE THREAD

**Issue by MaJiakang** [satijalab/seurat#6310]
![image](https://user-images.githubusercontent.com/110780219/184781349-49878a65-bbc9-42bd-8022-fb96527f9069.png)

When I'm analyzing the data, I first use CreateSeuratObject( min.features = 200) to create the object, then filter it with nFeature_RNA > 200, and I end up with 104439 cells, however, when my criterion is min.features = 200&subset = nFeature_RNA > 300, the cell number is 104440, I can't understand this change.
If I use the filter criteria as min.features = 300&subset = nFeature_RNA > 200, the total number of cells remaining at the end may be different

**Comment by mojaveazure** [comment]
`min.features` in `CreateSeuratObject` does a `>=` filter, not a `>` filter
