### ISSUE TITLE
Relative Counts vs Log Normalize?

### ISSUE THREAD

**Issue by spriyansh** [satijalab/seurat#6313]
I am working with the ScRNA-Seq data; the dataset has cells from human first-trimester placenta and decidua. The dataset is available at [Sc Expression Atlas][1] and is generated with Drop-Seq.

Sc Expression Atlas has a dataset available in [raw format][2] (Raw counts values before filtering and normalization) and [normalized format][3] (Untransformed expression values, normalized to counts per million). Upon plotting the violins for the number of counts of the two, I get the following plots, which is expected.
![Biostars](https://user-images.githubusercontent.com/34842808/184890920-08cf1d15-5698-43db-85e2-4bc2805365f9.png)

To my knowledge, all the normalizations are doing the job correctly.

However, I came across a few articles discussing the implication of log-normalization on the count data (ref [this](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.2041-210X.2010.00021.x) and [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4120293/)). As you can see from the plots, relative count normalization makes the counts more normally distributed than log-normalize counts ( I see this being used in almost all Seurat implementations). Therefore, I would like to know on what basis I should decide the strategy for normalization. I find Seurat RC more intuitive than Seurat log-normalize for this particular dataset; what are your thoughts?

  [1]: https://www.ebi.ac.uk/gxa/sc/experiments/E-HCAD-23/downloads
  [2]: https://www.ebi.ac.uk/gxa/sc/experiment/E-HCAD-23/download/zip?fileType=quantification-raw&accessKey=
  [3]: https://www.ebi.ac.uk/gxa/sc/experiment/E-HCAD-23/download/zip?fileType=normalised&accessKey=
  [4]: /media/images/e69ce29a-f32d-436c-a458-c10cb419

**Comment by saketkc** [comment]
Normalization is an active research area in the scRNA-seq world. For example, see some recent papers [paper1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8764781/) [paper2](https://www.biorxiv.org/content/10.1101/2021.06.24.449781v3.abstract), [paper3](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02451-7).  We have had good success with SCTransform, but you can choose the method that seems to make most sense for your data (as what you have done).
