### ISSUE TITLE
Label SeuratObject origin after merge

### ISSUE THREAD

**Issue by r-osorio** [satijalab/seurat#6317]
Hi,

I have merged a bunch of SeuratObjects to create one larger object of similar experiments, with the hopes to eventually integrate this with another object and compare similarities/differences. I followed the instructions on how to [combine multiple 10x runs](https://satijalab.org/seurat/articles/merge_vignette.html), so each column is now prefixed with sample1_, sample2_, etc. 

I have now created a umap of all the merged samples, and was hoping to find a way to label the umap by sample, to show whether the cells are being clustered by sample origin (ex// all of sample1_ is in cluster1, all of sample2_ is in cluster 2, etc), or if the samples are evenly distributed between clusters (ex// sample1_ is evenly split between clusters 1 3 and 5, sample2_ is mainly in clusters 3 and 4, etc etc).

Is there a way to visualize this?

**Comment by Stfort52** [comment]
Hi,
Take a look at the [`LabelClusters`](https://satijalab.org/seurat/reference/labelclusters) function.

**Comment by timoast** [comment]
The simplest thing to do is to add some metadata to the object before merging them that encodes their dataset of origin, eg: `obj1$dataset <- 1; obj2$dataset <- 2`

**Comment by r-osorio** [comment]
adding metadata was the easiest solution, thank you!
