### ISSUE TITLE
Can't recompute CCA coordinates with feature loadings

### ISSUE THREAD

**Issue by jindalk** [satijalab/seurat#6319]
Reposting with more info:

I tried regenerating CCA coordinates for cells in my existing object by multiplying the cell x feature matrix with the feature loadings matrix, but these coordinates do not match the original ones. This works fine for PCA, do feature loadings between CCA and PCA represent different things?

I am trying to use CCA feature loadings to map new cells from the same sample into an existing space, but want to make sure it actually works using existing cells first.

Thanks

**Comment by yuhanH** [comment]
Hi @jindalk 
In the CCA method, it is unlike PCA that you can project new cells based on feature loadings.  You cannot map new cells to the existing CCA space because two singular vectors both represent cells.
