### ISSUE TITLE
how can I tweak Seurat integration parameters to mitigate overcorrection in my data

### ISSUE THREAD

**Issue by pariaaliour** [satijalab/seurat#6321]
Dear Seurat team,
I used Seurat integration for analysis of my dataset. However, I noticed that it does overcorrection as I integrated pbmc dataset with my spinal cord dataset and I saw that the cells were mixed like other cell types. So, I tried to do harmony but didn't get stable clustering. I'm wonder if you have any recommendation to mitigate this issue?
The code I use to integrate my dataset is as below:

# SCTransform
for (i in 1:length(split_seurat)) {
  split_seurat[[i]] <- NormalizeData(split_seurat[[i]], verbose = TRUE)
  split_seurat[[i]] <- CellCycleScoring(split_seurat[[i]], g2m.features=g2m_genes, s.features=s_genes)
  split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = c("percent.chrM", "S.Score", "G2M.Score"))
}
#Data integration
  
integ_features <- SelectIntegrationFeatures(object.list = split_seurat)
split_seurat <- PrepSCTIntegration(object.list = split_seurat, anchor.features = integ_features)
integ_anchors <- FindIntegrationAnchors(object.list = split_seurat, normalization.method = "SCT", anchor.features = integ_features)
seurat_integrated <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT")
  
I'm also wondering do the samples need to be splited by identity or it should be any uninteresting variable affecting clustering more?
I appreciate your help on this,
Paria

**Comment by timoast** [comment]
You can try lowering the k.anchor parameter in FindIntegrationAnchors to be more stringent in finding anchors

**Comment by pariaaliour** [comment]
Thanks for your response. I did decreased the k.anchor parameter but didn't see much difference. The code I used is as below

# Split seurat object by condition to perform cell cycle scoring and SCT on all samples
split_seurat <- SplitObject(filtered_seurat, split.by = "orig.ident")

# SCTransform
for (i in 1:length(split_seurat)) {
    split_seurat[[i]] <- SCTransform(split_seurat[[i]], verbose = TRUE, vars.to.regress = "percent.chrM")
   }

#Data integration
  integ_features <- SelectIntegrationFeatures(object.list = split_seurat)
  split_seurat <- PrepSCTIntegration(object.list = split_seurat, anchor.features = integ_features)
  integ_anchors <- FindIntegrationAnchors(object.list = split_seurat, normalization.method = "SCT", k.anchor = [2], anchor.features = integ_features)
  seurat_integrated <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT")

![image](https://user-images.githubusercontent.com/52675953/187516924-3c3eab46-5204-4eee-960e-8bbd31d22f4b.png)

I spliced the data by tissue which returns spinal cord and pbmc (blood). UMAP plots are as below:
as the default parameter for k.anchor is 5 I chose three different parameters 4, 3, and 2 respectively.
<img width="437" alt="anchor4" src="https://user-images.githubusercontent.com/52675953/187516439-03c1b6fd-e93c-4c8e-9245-996360ab1fc4.png">

<img width="381" alt="annchor3" src="https://user-images.githubusercontent.com/52675953/187516470-7c208666-6bcf-46b2-83fc-3b531576dfea.png">

<img width="381" alt="anchor2" src="https://user-images.githubusercontent.com/52675953/187516493-0b8edb79-45c7-441b-870c-eed1b7783880.png">

I Donn't expect to see overlapping all cell type in spinal cord and pbmc. I really appreciate your advice on this
Paria
