### ISSUE TITLE
Can I regress out chemistry effect with running ScaleData on my integrated data

### ISSUE THREAD

**Issue by pariaaliour** [satijalab/seurat#6323]
Dear Seurat team,
I'm wondering if I have significant chemistry effect in my single cell dataset is it recommended to regress it out after integration using "ScaleData" function or integration would take care of it and I do need to run ScaleData without regressing out any variables? 
Thank you in advance!
Paria

**Comment by saketkc** [comment]
ScaleData is designed to adjust for internal covariates . You should use integration if the goal is to identify corresponding cell states across datasets (or chemistries in your case conditional on the fact that the datasets across chemistry show batch effects)
