### ISSUE TITLE
Problem with the reordering of samples on violin plot

### ISSUE THREAD

**Issue by FrAoJm** [satijalab/seurat#6324]
Hi!

I am having problems reordering the samples to be plotted in the `vlnplot`. I have been trying this solution:
https://github.com/satijalab/seurat/issues/2121#issue-496484507
https://github.com/satijalab/seurat/issues/454#issue-319628883

so what I am doing is:

1) Rename some clusters (some of them will be merged as they represent the same cell type). I'll go from 13 clusters to 7 clusters
```
current.cluster.ids <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,13)
new.cluster.ids <- c("Kidney",  
                     "Kidney", 
                     "Endothelial",
                     "Mesenchymal",
                     "Liver",
                     "Endothelial",
                     "Unknown",
                     "Immune",
                     "Endothelial",
                     "Eritrocyte",
                     "Endothelial",
                     "Immune",
                     "Endothelial",
                     "Mesenchymal")

names(new.cluster.ids) <- levels(seuratObj)
seuratObj.merged <- RenameIdents(seuratObj, new.cluster.ids)
```

2) Setting the order for the `vlnplot`
```
my_levels <- c("Kidney",	"Endothelial", "Immune", "Eritrocyte", "Mesenchymal", "Liver", "Unknown")
my_genes <- c("FABP1", "PLVAP", "CYP11A1", "COL3A1",	"C1QC",	"CHGB",	"PLP1", "HBA1", "PLVAP", "CARTPT", "TMSB10")
colors <- c("red", "brown", "green", "blue", "gray", "lightblue", "yellow", "pink", "black", "darkblue","darkgray")

# Reordering
seuratObj.merged$orig.ident <- factor(x = seuratObj.merged$orig.ident, levels = my_levels)

# Plot
c <- VlnPlot(seuratObj.merged, features= my_genes , stack = TRUE, sort = F, flip = TRUE, cols= colors) +
        theme(legend.position = "none") + ggtitle("Key genes expression")
c
```

The result of this plot is an X axis with this order:
"Kidney",	"Endothelial", "Mesenchymal", "Liver", "Unknown", "Immune", "Eritrocyte")

Any clue of what I am doing wrong? Any help would be really appreciated

Best regards!

**Comment by timoast** [comment]
Here you changed the factor levels of the `orig.ident` metadata column, which is not the same as the active cell identities used to group the plot by default. If you run:

```r
Idents(seuratObj.merged$orig.ident) <- "orig.ident"
```

it should work

**Comment by FrAoJm** [comment]
Hi!
sorry for my late reply, I have been with another issue and just returned to this one. 

If I run my code, and after I run @timoast one, I get the following: 

`Error in UseMethod(generic = "Idents<-", object = object) : 
  no applicable method for 'Idents<-' applied to an object of class "factor"`

What I noticed is that before I run my code, the **orig.ident** column has a "SeuratProject" word in all the cells. After do my code this changes to "NA". And this is not changed after run @timoast code. 

seurat_clusters column is the one which stores the cluster of each cell, the original ones 1 to 13, I cannot see the new cluster renamed as cells populations, which are only 7, and are the ones that I want to reorder in the plot. They have to be stored somewhere because they are plotted in the natural order of the vector... but no clue what I am doing wrong. 

Thanks!!!!

**Comment by timoast** [comment]
Sorry this was a typo by me, I've edited the comment now
