### ISSUE TITLE
Do we need to run PrepSCTFindMarkers() for a Seurat object created only by dataset aggr-ed by cellranger?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6325]
Hi there, 

I have datasets sequenced from several donors and were aggregated during `cellranger aggr()` (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/aggregate#what_is_aggr).  So, there is no merging step within the Seurat workflow but the Seurat object was created simply from 1 pooled `filtered_feature_bc_matrix`.

Do I need to still run `PrepSCTFindMarkers()` for my Seurat object?

Thank you for your advice.

**Comment by saketkc** [comment]
The goal of PrepSCTFindMarker is to bring two (or more) datasets at an agreeable sequencing depth. Since you have pooled data (cellranger aggr seems to already subsample to account for variation in *read depth*), you need not run `PrepSCTFindMarkers`

**Comment by denvercal1234GitHub** [comment]
Thank you @saketkc. But if I had already ran `PrepSCTFindMarkers` on my Seurat object of data ran by cellranger aggr, do I need to start over or it is okay just that it was not needed?
