### ISSUE TITLE
Negatively DE genes

### ISSUE THREAD

**Issue by WernaUVenema** [satijalab/seurat#633]
considering differential expression analyses:
I performed DE analyses on my data, which consists of multiple clusters, exporting only the positively DE genes (FindAllMarkers(dataset, test.use=”MAST”, only.pos=T)), however I find it is also possible to export negatively DE genes in my dataset. Now I am wondering if it makes sense to do so: Would I not find many false positives there with my single cell dataset which is zero inflated?
My question is: in what cases do you recommend to use the function only.pos=F, and in what would you say I should be careful using only.pos=F?

**Comment by satijalab** [comment]
Sparsity and noise can affect both positively and negatively regulated genes in DE analysis. You should use only.pos=T if you want to identify only up-regulated genes in a cluster. We find this particularly useful when searching for putative markers to define a cluster's identity, or for visualization (heatmaps)

**Comment by wupeng2** [comment]
hello，
as you say, only.pos=T  is  useful when searching for putative markers to define a cluster's identity, or for visualization ,but if I want use DE genes to do GOanalysis,should I  still set only.pos=T ?

**Comment by wupeng2** [comment]
hello，
as you say, only.pos=T  is  useful when searching for putative markers to define a cluster's identity, or for visualization ,but if I want use DE genes to do GOanalysis,should I  still set only.pos=T ?
