### ISSUE TITLE
What will be the merge command for 4 tumors?

### ISSUE THREAD

**Issue by shwetajohari** [satijalab/seurat#6331]
Hello, 

I have successfully merged two tumors but when I have to merge 4 tumors, how do you write the merge command?

setwd("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall")
> library(Seurat)
Attaching SeuratObject
Attaching sp
> library(patchwork)
####added all the tumors
> control = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu1_099")
> dnavaccine = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu2_099")
> inhibitor = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu3_099")
> combitr = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu4_099")
####created the surat object for all
> control_seurat = CreateSeuratObject(counts = control$`Gene Expression`, project = "control")
> dnavaccine_seurat = CreateSeuratObject(counts = dnavaccine$`Gene Expression`, project = "dnavaccine")
> inhibitor_seurat = CreateSeuratObject(counts = inhibitor$`Gene Expression`, project = "inhibitor")
> combitr_seurat = CreateSeuratObject(counts = combitr$`Gene Expression`, project = "combitr")
> head(control_seurat@meta.data,5)
                   orig.ident nCount_RNA nFeature_RNA
AAACCCACAAGAAACT-1    control      36491         5904
AAACCCACACGTACTA-1    control      19944         3794
AAACGAAGTGTGATGG-1    control      21324         3717
AAACGAATCCTAGCCT-1    control      22089         4207
AAACGCTAGTAAGGGA-1    control       3147         1348

####What will be the merge for these tumors?
merge_seurat = merge(x = c(control_seurat,dnavaccine_seurat) , y = c(inhibitor_seurat, combitr_seurat) ,add.cell.id = c("control", "dnavaccine", "inhibitor", "combitr"))
Error in as.data.frame.default(x[[i]], optional = TRUE) : cannot coerce class ‘structure("Seurat", package = "SeuratObject")’ to a data.frame

Thank you. 

Kind Regards,
Shweta Johari

**Comment by denvercal1234GitHub** [comment]
Check out "https://satijalab.org/seurat/articles/merge_vignette.html" in the "Merging More Than Two Seurat Objects" section

**Comment by shwetajohari** [comment]
Hello,
Thank you for the reply.
I did go through that but I cant get it. 
In my case, I dont have one object where everything is.
SO in the example it is:
pbmc.big <- [merge](https://rdrr.io/r/base/merge.html)(pbmc3k, y = [c](https://rdrr.io/r/base/c.html)(pbmc4k, pbmc8k), add.cell.ids = [c](https://rdrr.io/r/base/c.html)("3K", "4K", "8K"), project = "PBMC15K")
pbmc.big

Thats why I wrote this but its not working:
merge_seurat = merge(x = c(control_seurat,dnavaccine_seurat) , y = c(inhibitor_seurat, combitr_seurat) ,add.cell.id = c("control", "dnavaccine", "inhibitor", "combitr"))

Thank you though :)
Kind regards,
Shweta Johari

**Comment by denvercal1234GitHub** [comment]
You need to put `x=control_seurat` then `y=c(all the rest of the datasets)`

**Comment by timoast** [comment]
@denvercal1234GitHub is correct, the argument `x` should be a single Seurat object not a vector
