### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by pwmellors** [satijalab/seurat#6332]
I am trying to install the Seurat package in an HPC environment using linux command line, MacOS

ERROR: compilation failed for package ‘httpuv’
* removing ‘/home/user/R/lib64/R/library/httpuv’
ERROR: dependency ‘RcppTOML’ is not available for package ‘reticulate’
* removing ‘/home/user/R/lib64/R/library/reticulate’
ERROR: dependency ‘httpuv’ is not available for package ‘shiny’
* removing ‘/home/user/R/lib64/R/library/shiny’
ERROR: dependency ‘reticulate’ is not available for package ‘leiden’
* removing ‘/home/user/R/lib64/R/library/leiden’
ERROR: dependency ‘shiny’ is not available for package ‘miniUI’
* removing ‘/home/user/R/lib64/R/library/miniUI’
ERROR: dependencies ‘leiden’, ‘miniUI’, ‘reticulate’, ‘shiny’ are not available for package ‘Seurat’
* removing ‘/home/user/R/lib64/R/library/Seurat’

The downloaded source packages are in
	‘/tmp/RtmprGnO0k/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("Seurat") :
  installation of package ‘RcppTOML’ had non-zero exit status
2: In install.packages("Seurat") :
  installation of package ‘httpuv’ had non-zero exit status
3: In install.packages("Seurat") :
  installation of package ‘reticulate’ had non-zero exit status
4: In install.packages("Seurat") :
  installation of package ‘shiny’ had non-zero exit status
5: In install.packages("Seurat") :
  installation of package ‘leiden’ had non-zero exit status
6: In install.packages("Seurat") :
  installation of package ‘miniUI’ had non-zero exit status
7: In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status

Is this a dependency issue of some kind?

**Comment by shwetajohari** [comment]
Hey
I dont know if this will help you but I had an issue to install Seurat and sct on the mac too.
I got the following reply:

Saket Choudhary: I would recommend installing brew: https://brew.sh/ and then brew install gcc and then installing sctransform.

You install this brew and gcc on the mac terminal and then move onto installing packages. 

It didnt work after this but however, I restarted the mac and then it suddenly started working well. 
Again, I am not sure if this will help but you can try :)

Regards,
Shweta Johari

**Comment by timoast** [comment]
You'll need to work through the installation of dependencies and ensure you can get them installed on your machine. Sometimes missing compilers can cause issues for packages that contain compiled code. If this is the case, you could ask the system admin for help, or try using conda to install the package binaries
