### ISSUE TITLE
PrepareBridgeReference: No features to use in finding transfer anchors

### ISSUE THREAD

**Issue by EST09** [satijalab/seurat#6333]
Hi!

Thank you for your package. I've been trying to run bridge integration from (https://www.biorxiv.org/content/10.1101/2022.02.24.481684v1.full) following the [vignette](https://satijalab.org/seurat/articles/bridge_integration_vignette.html) and issue (#5697). However, I keep running into a problem in ```PrepareBridgeReference```

```
Normalizing query using reference SCT model
Error: No features to use in finding transfer anchors. To troubleshoot, try explicitly providing features to the features parameter and ensure that they are present in both reference and query assays.
```

I'm trying to use Azimuth Bone Marrow scRNA-seq as the reference which I've downloaded from [Zenodo](https://zenodo.org/record/5521512#.YwP0Py0w30o) (both ref.rds and annoy.idx). I can't manage to load the azimuth reference bonemarrowref from SeuratData. 

```
ref <- LoadReference("~/Downloads/BM")
ref = ref$map
```
   
For the bridge I want to use CITE-Seq data bmcite from SeuratData.

```
InstallData("bmcite")
bm <- LoadData(ds = "bmcite")
```

I would like to use bridge integration to map a CyTOF dataset as the query. I've checked/renamed, and anchor proteins which are available in all reference, bridge and query consist of a list of 7 proteins which I call new_adt_features: 

```
new_adt_features = c("CD11c", "CD127-IL7Ra", "CD14", "CD38", "CD45RA","CD69", "HLA.DR")
``` 

I've performed SCTransform on the CITESeq dataset (bm)

```{r}
bm <- SCTransform(bm, verbose = FALSE)
```

This leaves me with two Seurat objects. 

The reference: 

```
An object of class Seurat 
3000 features across 297627 samples within 1 assay 
Active assay: refAssay (3000 features, 0 variable features)
 2 dimensional reductions calculated: refUMAP, refDR
```

and the bridge:

```
An object of class Seurat 
33990 features across 30672 samples within 3 assays 
Active assay: RNA (17009 features, 2000 variable features)
 2 other assays present: ADT, SCT
 2 dimensional reductions calculated: spca, wnn.umap
```

To try to integrate my reference and bridge, I rely on these 7 features. 

```
DefaultAssay(bm) <-  "RNA"
DefaultAssay(ref) <- "SCT"

ref.extend <- PrepareBridgeReference(reference = ref,
                      normalization.method = "SCT",
                       bridge = bm,
                       reference.reduction = 'refUMAP', 
                       reference.dims = dims.rna,
                       bridge.query.assay = 'ADT',
                      supervised.reduction = 'spca',
                       bridge.query.features = new_adt_features)
``` 

I've tried renaming the reference refAssay to SCT or RNA as in (#5332) but the problem seems to remain. 

```
ref = RenameAssays(object = ref, refAssay = 'SCT')
```

I was wondering if you had any advice on where I might be going wrong? Thank you!

Best wishes,
Emily

**Comment by Gesmira** [comment]
Hi Emily, 
I believe the issue is due to what you have defined as `reference.reduction = 'refUMAP'` in `PrepareBridgeReference()`. This should in fact be `reference.reduction = 'refDR'`. 'refDR' from your reference object represents the PCA reduction. `FindTransferAnchors()`, which is called by `PrepareBridgeReference()`, uses the rownames of the reference feature loadings as the features parameter. Since the UMAP reduction doesn't have these feature loadings, no features names would be found if you set this as the reference reduction.

**Comment by EST09** [comment]
Hi Gesmira, 

Thank you so much for getting back. Would I then always need a PCA reduction (called "refDR") in order to use FindTransferAnchors or PrepareBridgeReference? I had been running the UMAP from all my features previously. 

Thank you!

Best wishes, 
Emily

**Comment by Gesmira** [comment]
Hi Emily, 
If you create your own RNA reference using the default workflow `obj.rna = SCTransform(object = obj.rna) %>% RunPCA() %>% RunUMAP(dims = 1:50, return.model = TRUE)` this pca reduction will be called "pca" instead. But, yes, regardless, you will need a reference reduction which you then use to compute the UMAP reduction to run FindTransferAnchors and PrepareBridgeReference. More info on parameters: https://satijalab.org/seurat/reference/findtransferanchors
Best, 
Gesi
