### ISSUE TITLE
what non-variable count and variable count mean?

### ISSUE THREAD

**Issue by Chrisdoan9** [satijalab/seurat#6337]
Hello all,

Would anyone please tell me what non-variable count and variable count mean in this tutorial?
[pbmc3k_tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html)

Thank you so much!

**Comment by denvercal1234GitHub** [comment]
`FindVariableFeatures()` has a parameter where you decided how many variable genes/features you want to compute. That is what "variable counts" mean in that plot. Non-variable counts = total # of genes - variable counts

**Comment by Chrisdoan9** [comment]
Thank you so much!
