### ISSUE TITLE
Issue Recalling pbmc data for Guided Clustering Tutorial

### ISSUE THREAD

**Issue by ob6nb** [satijalab/seurat#6339]
Hi! I'm fairly new to programming, so apologies if this issue seems fairly easy lol. I'm trying to work through the guided clustering tutorial, but R keeps showing me this error: 

![image](https://user-images.githubusercontent.com/111803659/186464825-ecb0f5d7-a6a4-4b05-9815-35a3dfe76d91.png)
I also had a couple friends who are bio engineers take a look at the code and attempted to untar the file, however, once we attempted to untar it we got this error:
![image](https://user-images.githubusercontent.com/111803659/186465061-e45e0d7d-1fb2-4cbc-bac6-663a96dbbc3c.png)

note: i also went through previous solutions for similar issues and different each time, another error has come up

**Comment by timoast** [comment]
`data.dir` needs to point to the directory containing the 10x matrix files. Specifying the tar will not work, you'll need to extract the tar file and provide the path to the folder itself
