### ISSUE TITLE
Cutoff to find out number of variable genes?

### ISSUE THREAD

**Issue by parveenkgit** [satijalab/seurat#634]
I have gone through multiple seurat tutorials or links but could not find proper explanation about optimal cutoffs (x.low.cutoff, x.high.cutoff and y.cutoff) to choose to find out variable genes. Even from the dispersion vs avg-expression plot, it is difficult to select the optimal cut-offs. It would be helpful if some information related to choosing the optimal cut-offs can be added.

**Comment by satijalab** [comment]
All methods for HVG selection have some cutoff parameters, and unfortunately criteria for 'optimality' are difficult to identify.

If you have UMI data, we suggest identifying HVG on the basis of variance-to-mean ratio, as we demonstrate here : https://satijalab.org/seurat/mca.html

Again, with UMI datasets - we typically do not notice large differences in the analysis depending on the exact number of genes selected- ranging from 2k genes to even the full transcriptome.
