### ISSUE TITLE
>0 or >1 to select cells that express a gene?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6340]
Hi there, 

In the tutorial, to select cells that express a gene, it says to do `subset(pbmc, subset = MS4A1 > 1)`. 

Would you mind confirming that if I want to subset out cells that express a gene, should I set `subset = MS4A1 >1` or `subset = MS4A1 >0`?

Thank you

**Comment by timoast** [comment]
It's up to you, you can set whatever cutoff you'd like to define whether a gene is "expressed" or not, and this may vary depending on dataset
