### ISSUE TITLE
Intracluster analysis on Seurat object with multiple SCT models - FindMarkers asks for PrepSCTFindMarkers again

### ISSUE THREAD

**Issue by andrei-stoica26** [satijalab/seurat#6342]
Hi,

After splitting a Seurat object with multiple SCT models (datasets were individually SCTransformed and then merged) into Seurat objects corresponding to my clusters, I get this error if I try to run FindMarkers on any of the subsets:

Error in FindMarkers.SCTAssay(object = data.use, slot = slot, cells.1 = cells$cells.1,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`.

This does not seem right - I've already run PrepSCTFindMarkers on the whole dataset once. Not sure why subsetting should change anything.

Is it safe to simply delete the SCT models from the original Seurat object prior to subsetting, as below?

`seuratObj@assays$SCT@SCTModel.list <- list()`

Thank you for your help.

**Comment by saketkc** [comment]
As indicated in the [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html#identify-differential-expressed-genes-across-conditions-1), you can set `recorrect.umi=FALSE` when running FindMarkers on subset objects.

**Comment by andrei-stoica26** [comment]
Thanks, saketkc.
