### ISSUE TITLE
Splitting UMAP 'batch' after Merging two Seurat Objects

### ISSUE THREAD

**Issue by john-j-oh** [satijalab/seurat#6350]
Hello,

I loaded in two separate scRNA-seq libraries and merged two SeuratObjects by the merge() function. I took all of the steps shown in the tutorial to reach UMAP/tSNE. Is there a way to display the merged UMAP/tSNE graph based on its orig.ident?

I am using Seurat v.4.1.1, ggplot2 v.3.3.6, and reticulate v.1.25 (for RunUMAP function).

> table(PBMC.Combined$orig.ident)

  InfectedPBMC UninfectedPBMC 
          8718          10288 

This is what Seurat returns when I inquire about PBMC.Combined.

Thank you.

John

**Comment by timoast** [comment]
You can use the `split.by` parameter

**Comment by john-j-oh** [comment]
Thank you for your help!

I also have another question about parameters order and shuffle. I displayed my UMAP on R with FeaturePlot(Stomach.Combined, features = c("Slfn4", "Nos2", "Arg1"), pt.size = 1) got these plots.
![7  Slfn4, Nos2, Arg1](https://user-images.githubusercontent.com/112213594/187279528-fcbcaad5-2baf-48d8-9fa6-74decc8883d5.png)

Since the cells of interest are buried by negative cells, so I wanted to add `order` or `shuffle` parameter to the `FeaturePlot` command and it seems to not work. I was wondering if this is a glitch or if there's a way around it.

John
