### ISSUE TITLE
How to subset & analyze query cells that are unique from ref dataset after computing de novo UMAP visualization?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6351]
Hi there, 

From the tutorial (https://satijalab.org/seurat/articles/multimodal_reference_mapping.html#computing-a-new-umap-visualiztion-1), de novo visualization helps identify cell subsets that are unique in the query dataset (thus remained separated from the ref subsets in the de novo UMAP). 

I can now visualize on the UMAP the query cells that are not present in ref dataset. **But, the `active.ident` of the merged object is simply still an aggregate of those of the original query and ref cluster IDs.** 

Would you mind advising on:

**Question 1.** How can I subset (and not just visualize on UMAP) (1) these cells that are unique to query dataset and (2) cells that are unique to the ref dataset? (Related = #4597)

**Question 2** We have to run unimodal `MapQuery()` using the same query and ref objects before computing the de novo UMAP. In order to analyze the cell states that are "shared" between query and ref, should I first extract out the cells identified by de novo visualization from the predictions given by unimodal `MapQuery()`?

**Question 3.** From #6173, de novo UMAP is the UMAP generated from query batch-corrected cell embeddings, and not the expression values. If I want to now perform DEG for these unique/shared cells, should I run `PrepSCTFindMarkers()` to adjust for the sequencing depth of the query and ref datasets per #6325? And, is it appropriate to `FindMarkers()` and `FindConservedMarkers()` between a subseted query cell group vs a ref cluster on this merged object?

Thank you so much!

**Comment by yuhanH** [comment]
hi, @denvercal1234GitHub 

Questions 1 and 2 pertain to novel population detection. You can construct a one-class SVM from the reference cells and then utilize it to detect out-of-distribution query cells from the model built in the batch-corrected, low-dimensional space. We don't have a built-in function for this, so you'll need to write your custom one.
As for Question 3, you can refer to our vignettes about differential expression analysis.
