### ISSUE TITLE
FeaturePlot(blend = TRUE), how is it made?

### ISSUE THREAD

**Issue by Tinocapo** [satijalab/seurat#6357]
Hello!

I am trying to make a comparison of 2 different module scores that are not within a Seurat object, they are AUCell results. I think a really cool way to show the difference and similarities is the blend = TRUE in featurePlot() and I was wondering if anybody could send me the code as to how to make this plot. I'm having a lot of trouble being able to generate the 2D color gradient as well as the plot that compares the features, it would really mean a lot to me if someone could send me the source code or something.

Sincerely,

Tino

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can find all of the raw source code in the R folder within the github repo.  In this case `FeaturePlot` code starts here:
https://github.com/satijalab/seurat/blob/3bee84a8d710b7ee0022b929dab1df2f6ba26fdb/R/visualization.R#L971-L974

The blend portion of the code can be found at several points within the overall function code corresponding to setting up different parts of the blended plot.

Best,
Sam
