### ISSUE TITLE
Error in idx[i, ] <- res[[i]][[1]] : number of items to replace is not a multiple of replacement length in IntegrateData()

### ISSUE THREAD

**Issue by WhalleyT** [satijalab/seurat#6359]
Hi,

I've been getting the following error message when running ```IntegrateData()``` on my scATAC data.

```
Warning: Number of anchors is less than k.weight. Lowering k.weight for sample pair. Finding integretation vectors. 
Finding integration vector weights 
Error in idx[i, ] <- res[[i]][[1]] : number of items to replace is not a multiple of replacement length
```
the code leading up to this looks like:
```
library(tidyverse)
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v75)

set.seed(999)

read_files <- function(path, id){
  #paths to read
  h5   <- paste(path, "filtered_peak_bc_matrix.h5", sep = "/")
  meta <- paste(path, "singlecell.csv", sep = "/")
  frag <- paste(path, "fragments.tsv.gz", sep = "/")
  
  counts <- Read10X_h5(filename = h5)
  
  metadata <- read.csv(file = meta,
                       header = TRUE,
                       row.names = 1)
  
  chrom_assay <- CreateChromatinAssay(counts = counts,
                                      sep = c(":", "-"),
                                      genome = 'hg19',
                                      fragments = frag,
                                      min.cells = 10,
                                      min.features = 200)
  
  #combine them all
  data <- CreateSeuratObject(counts = chrom_assay,
                             assay = "peaks",
                             meta.data = metadata)
  
  data@meta.data$dataset <- id
  
  return(data)
}

internal <- read_files("all_combined_NEW/outs/", "US")
public   <- read_files("public_combined/outs/", "Public")

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)

# change to UCSC style since the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'

# add the gene information to the object
Annotation(internal) <- annotations
Annotation(public)   <- annotations

dim_reduce <- function(seurat_obj){
  seurat_obj <- FindTopFeatures(seurat_obj, min.cutoff = 10)
  seurat_obj <- RunTFIDF(seurat_obj)
  seurat_obj <- RunSVD(seurat_obj)
  
  return(seurat_obj)
}

public <- dim_reduce(public)
internal <- dim_reduce(internal)

# find integration anchors
integration.anchors <- FindIntegrationAnchors(
  object.list = list(internal, public),
  anchor.features = rownames(combined),
  reduction = "rlsi",
  dims = 2:30
)

# integrate LSI embeddings
integrated <- IntegrateEmbeddings(
  anchorset = integration.anchors,
  reductions = combined[["lsi"]],
  new.reduction.name = "integrated_lsi",
  dims.to.integrate = 1:30
)
```
My apologies, I can't seem to recreate this error with any of the "sample" datasets so I suspect it is something to do with the nature of our data. I will try and think of a means of sharing the data itself. The error message itself is quite a generic R error,  I see from #6341 it can be related to a disparity in the size of the datasts but we have several thousand cells per dataset. 

Thanks in advance and happy to supply any additional information

**Comment by emanuelavilla** [comment]
I got the same issue: when I tried to integrate 2 scATAC, I got the error. Actually, I have discovered that it was a problem in the FindIntgerationAnchors: I got a 0% when finding all pairwise anchors. Maybe it is the same for you.
Unfortunately, I cannot understand what the problem relies on because I have already used the same script for other 2 integrations, always between 2 scATACseq data.
Did you resolve the problem?

**Comment by decodebiology** [comment]
Having same issue. Any solution yet?

**Comment by Gesmira** [comment]
Hi, sorry for the delay in response here. 
How many anchors are in `integration.anchors`? Seems like that may be the source of the issue if you have thousands of cells per dataset. 
Otherwise, if your samples are small, see: [#3930](https://github.com/satijalab/seurat/issues/3930)

**Comment by bobermayer** [comment]
I have the same problem when trying to integrate 10 datasets with 6-10k cells each. `FindIntegrationAnchors` gives >6k anchors in total (22-297 between each pair), but `IntegrateData` fails after a few steps:

```
Merging dataset 1 into 3
...
Merging dataset 10 into 8
...
Merging dataset 2 into 8 10
...
Merging dataset 7 into 3 1
...
Merging dataset 5 into 9
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length
```

(there's 58 anchors between datasets 5 and 9)

any help would be greatly appreciated!

**Comment by levinhein** [comment]
> I have the same problem when trying to integrate 10 datasets with 6-10k cells each. `FindIntegrationAnchors` gives >6k anchors in total (22-297 between each pair), but `IntegrateData` fails after a few steps:
> 
> ```
> Merging dataset 1 into 3
> ...
> Merging dataset 10 into 8
> ...
> Merging dataset 2 into 8 10
> ...
> Merging dataset 7 into 3 1
> ...
> Merging dataset 5 into 9
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> Error in idx[i, ] <- res[[i]][[1]] : 
>   number of items to replace is not a multiple of replacement length
> ```
> 
> (there's 58 anchors between datasets 5 and 9)
> 
> any help would be greatly appreciated!
> 
> **update**: setting `k.anchor=10, k.filter=250` helps, but I don't know why ...

Hi @bobermayer I encountered same error as yours and did your suggestion setting k.anchor=10, k.filter=250 in FindIntegrationAnchors(), but I still have it. Did you finally resolve it?

**Comment by Gesmira** [comment]
Hi, 
We are adding a more informative error message for this issue currently in the development branch. It seems to occur when the number of anchor cells is less than the k.weight parameter which is the number of neighbors to use when weighting anchors. For now, I would recommend reducing k.weight, combining samples if there are few cells in certain samples, or adjusting parameters to [FindIntegrationAnchors](https://satijalab.org/seurat/reference/findintegrationanchors) (which can be provided as inputs to IntegrateLayers) to increase the number of anchors/cells which act as anchors. Decreasing k.weight will decrease the power of your integration, so we recommend checking the results of your integration if these parameters are changed to ensure the results are satisfactory.
