### ISSUE TITLE
h5ad to Seurat Object

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#6360]
Hi, I'm trying to convert a h5ad file to a Seurat object using SeuratDisk however when I run
`Convert("All_Combined_preLoom.h5ad", dest = "h5seurat", overwrite = TRUE)`

I get the following errors. 

Error in dfile$obj_copy_from(src_loc = source, src_name = "obs", dst_name = "meta.data") : HDF5-API Errors: error #000: ../../src/hdf5-1.12.0/src/H5Ocopy.c in H5Ocopy(): line 251: unable to copy object class: HDF5 major: Object header minor: Unable to copy object error #001: ../../src/hdf5-1.12.0/src/H5VLcallback.c in H5VL_object_copy(): line 5530: object copy failed class: HDF5 major: Virtual Object Layer minor: Unable to copy object error #002: ../../src/hdf5-1.12.0/src/H5VLcallback.c in H5VL__object_copy(): line 5491: object copy failed class: HDF5 major: Virtual Object Layer minor: Unable to copy object error #003: ../../src/hdf5-1.12.0/src/H5VLnative_object.c in H5VL__native_object_copy(): line 126: unable to copy object class: HDF5 major: Symbol table minor: Unable to copy object error #004: ../../src/hdf5-1.12.0/src/H5Ocopy.c in H5O_copy(): line 313: unable to copy object class: HDF5 major: Object header minor: Unable

Error in private$closeFun(id) : HDF5-API Errors: error #000: ../../src/hdf5-1.12.0/src/H5F.c in H5Fclose(): line 886: decrementing file ID failed class: HDF5 major: Object atom minor: Unable to close file error #001: ../../src/hdf5-1.12.0/src/H5I.c in H5I_dec_app_ref(): line 1422: can't decrement ID ref count class: HDF5 major: Object atom minor: Unable to decrement reference count error #002: ../../src/hdf5-1.12.0/src/H5F.c in H5F__close_cb(): line 243: unable to close file class: HDF5 major: File accessibility minor: Unable to close file error #003: ../../src/hdf5-1.12.0/src/H5VLcallback.c in H5VL_file_close(): line 3977: file close failed class: HDF5 major: Virtual Object Layer minor: Unable to close file error #004: ../../src/hdf5-1.12.0/src/H5VLcallback.c in H5VL__file_close(): line 3945: file close failed class: HDF5 major: Virtual Object Layer minor: Unable to

How can I fix this? Thank you :)

**Comment by yuhanH** [comment]
hi,
sorry for the delay. You can have a try on sceasy to convert object format.  https://github.com/cellgeni/sceasy
