### ISSUE TITLE
Spaceranger 2.0 breaks Read10X_Image

### ISSUE THREAD

**Issue by jebard** [satijalab/seurat#6362]
This was referenced in #6338 but was resolved as user found a fix -- but this change should be incorporated into newer versions of Seurat --

July 18th release of spaceranger 2.0 updated names for a couple of files that are hardcoded into the Read10X_image function

Space Ranger 1.3 outputs | Space Ranger 2.0 outputs
tissue_positions_list.csv | tissue_positions.csv(Added header row)

https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/release-notes

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Have you tried running the develop branch?  There was PR a little while back from member of 10X team to update compatibility.
https://github.com/satijalab/seurat/pull/6208#issue-1308410878

Best,
Sam

**Comment by jebard** [comment]
Hey Sam!
Thanks for posting that -- missed that! Appreciate the link and will resolve

**Comment by anjrao17** [comment]
Hi, In addition to the change in file name, there is now also a header row for tissue_positions.csv which causes an error in Read10X_image().  I was able to solve it by removing the header for the file manually - but would it be possible to add this functionality as well to the current CRAN version? Thanks for a great package!
