### ISSUE TITLE
Map Query Error in ReferenceMapping Seurat

### ISSUE THREAD

**Issue by Victoriat0618** [satijalab/seurat#6363]
Hi there,

I'm trying to run mapquery on one of the metadata in my reference dataset. It's giving me this error and I couldn't figure out why.

> Predicting cell labels
> Error: Feature names of data matrix cannot be empty

Error only occurs in using this metadata as reference.celltype. Other metadata in the same reference dataset didn't show this error.
Any suggestions will be helpful. Thanks

**Comment by mhkowalski** [comment]
Hello, 

Have you checked if there are any NA values in your metadata?

**Comment by yuhanH** [comment]
Since we haven't heard you, we will close this issue first. If you still have this issue, we can reopen it.
