### ISSUE TITLE
how to make Read10X_Image work with aggr_tissue_positions.csv?

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#6364]
```r
# insert reproducible example here
```

I used Read10X_Image to read my visum data but I got the below error:
“cannot open file 'tissue_positions_list.csv.
I have only aggr_tissue_positions.csv, not tissue_positions_list.csv. I have also one filtered_feature_bc_matrix.h5.
By looking at the spatial folder I find four subfolders that indicate this h5 data is aggregated for all four samples.
How to tweak Read10X_image to work in this type of format?

Thank you

**Comment by longmanz** [comment]
Hi,
You may try to simply change the file name of "aggr_tissue_positions.csv" into "tissue_positions.csv" and load it with Read10X_Image.
However, please note that you will need to alter the columns of your "aggr_tissue_positions.csv" into the format of "tissue_positions.csv", that is: 'barcodes', 'tissue', 'row', 'col', 'imagerow', 'imagecol'.

**Comment by dcollins15** [comment]
As off v5.1.0 `Read10X_Image` the regex used to search for the tissue positions file has been relaxed and should now recognize the "aggr_tissue_positions.csv" if it is present in the specific `data.dir` 👍
