### ISSUE TITLE
NormalizeData before SCTransform for demultiplexing

### ISSUE THREAD

**Issue by acv21** [satijalab/seurat#6365]
Hello,

I am analysing a 10x scRNA-seq dataset where 6 cell populations were multiplexed by antibody-based cell hashing (with Totalseq-B antibodies). I demultiplexed the dataset using either `HTODemux` or `MULTIseqDemux`, both of which require the following preprocessing, if I understood the documentation correctly:
```
data <- Read10X(data.dir=data_dir)
obj=CreateSeuratObject(counts=data$`Gene Expression`)
obj[['Protein']]=CreateAssayObject(counts=data$`Antibody Capture`)
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern="^MT-")
obj.norm <- NormalizeData(obj)
obj.norm <- NormalizeData(obj.norm, assay="Protein", normalization.method="CLR")
```

After these steps, I run demultiplexing with either `HTODemux` or `MULTIseqDemux` and subset the `obj.norm` object to remove negatives and doublets. My question is: can I use `SCTransform` directly on the subset `obj.norm` (pre-log-normalised to run demultiplexing), or do I need to go back to the initial non-log-normalised `obj` (which does not however have the classification from the demultiplexing step)?

Thanks for your help!

**Comment by f6v** [comment]
You don't need to run `NormalizeData` on the gene expression data before the demultiplexing, only on the HTO assay. After removing non-singlets, you can normalise your RNA data with `SCTransform`.

**Comment by acv21** [comment]
Thank you very much @f6v , that makes sense!
