### ISSUE TITLE
RunMultiCCA and AlignSubspace output

### ISSUE THREAD

**Issue by jk86754** [satijalab/seurat#637]
Hi,

I am wondering: when one performs merging of multiple datasets using RunMultiCCA and AlignSubspace in Seurat, what slot of the new Seurat object does the merged and normalized matrix get stored?

Thanks!

Joe

**Comment by satijalab** [comment]
We do not modify the gene expression matrix - but provide an aligned low-dimensional subspace for downstream analysis (clustering). Future versions will also normalize/batch-correct the underlying expression data.
