### ISSUE TITLE
Graphical representation question

### ISSUE THREAD

**Issue by john-j-oh** [satijalab/seurat#6371]
Hi all,

I am analyzing my infected PBMC data side by side by merging them as one object. When I displayed its plot split by its identity, Infected is placed on the left automatically (I assume this is more because of alphabetic order). Is there a way to switch spots of Infected and Uninfected UMAP plots? I don't think it would be an `order` parameter would it be?

An example plot of mine is shown below:
![Rplot09](https://user-images.githubusercontent.com/112213594/187785358-3324267e-c0ee-4ca7-a233-3373d0f49aad.png)

Thank you.

**Comment by f6v** [comment]
You can by the `split.by` argument to `DimPlot`. So that'd be your infected/not infected column in the metadata. I'd try converting that column to a factor with the desired order. But I don't know if that's going to work.

**Comment by samuel-marsh** [comment]
Hi,

In your split plot the solution suggested by @f6v is correct.  What you need to do is change the leveling of the factor so that it matches how you want it to be displayed.

In your case you would want to run:
```
OBJ@meta.data$META_NAME <- factor(x = OBJ@meta.data$META_NAME, levels = c("UniPBMC", "InPBMC"))
```

Best,
Sam
