### ISSUE TITLE
plotting genes that are co-expressed in featureplot eliminating color from cells expressing only one of the genes.

### ISSUE THREAD

**Issue by yamihn** [satijalab/seurat#6376]
Hi everyone! I would like to know if there is a way to visualize in the third plot only the cells expressing both genes, eliminating from the visualization those cells that express only one gene:

 FeaturePlot(object = seurat,
                      features = c("Igfbp5", "Epcam"),
                       reduction =  "umap", pt.size = 0.8, blend = TRUE, blend.threshold = 1, order = T)
![trial_coexpr](https://user-images.githubusercontent.com/109409803/187906563-645923d8-ad3b-45b4-ac84-943d1ceac540.png)

**Comment by timoast** [comment]
You can use the `cells.highlight` parameter in `DimPlot()` to highlight certain cells in the plot. You first need to identify which cells express each gene over a given threshold, eg:

```r
cells <- WhichCells(obj, expression = Igfbp5 > 1 & Epcam > 1)
```

then pass those cells in the `cells.highlight` parameter.
