### ISSUE TITLE
Creating a new dataset to analyze from integrated data

### ISSUE THREAD

**Issue by elifozcelik** [satijalab/seurat#6377]
Hi, I have a integrated data which is about 100k immune cells. They have been scaled, normalized and already have a finalized umap. I want to get T cells from this dataset and create a completely new umap with only 18k T cells. I have extracted the count matrix after subsetting the cells I want from the general using subset function. However, the UMAP I am creating now looks very similar and meaningless in every resolution. I will paste my code below, any help is appreciated. Thanks a lot. 

tcount <- GetAssayData(t.cells, slot= c(‘counts’))

t_seurat <- CreateSeuratObject(tcount, project = “SeuratProject”, assay = “RNA”,
 min.cells = 0, min.features = 0, names.field = 1,
 names.delim = “_”, meta.data = NULL)
 
diet.list <- SplitObject(t_seurat, split.by = “diets”)
diet.list <- lapply(X = diet.list, FUN = function(x) {
  x <- SCTransform(x, vars.to.regress = “[percent.mt](http://percent.mt/)”, verbose = FALSE, return.only.var.genes= FALSE)
})

features <- SelectIntegrationFeatures(object.list = diet.list)
diet.list <- PrepSCTIntegration(object.list =diet.list, anchor.features = features)
diet.anchors <- FindIntegrationAnchors(object.list = diet.list, anchor.features = features, normalization.method = ‘SCT’)
t.combined <- IntegrateData(anchorset = diet.anchors, normalization.method = ‘SCT’)
DefaultAssay(t.combined) <- “integrated”

t.combined<- RunPCA(t.combined, npcs = 25, verbose = FALSE)
t.combined <- FindNeighbors(t.combined, reduction = “pca”, dims = 1:20)
t.combined <- FindClusters(t.combined, resolution = 0.4)
t.combined <- RunUMAP(t.combined, reduction = “pca”, dims = 1:20)
DimPlot( t.combined, reduction = “umap”, label = TRUE,raster=FALSE)

**Comment by yuhanH** [comment]
hi @elifozcelik 
In your case, you don't need to re-run integration for your T cells. 
You can subset your T cells, just re-run PCA from the integrated assay and define new clusters. Here is a similar issue: https://github.com/satijalab/seurat/issues/6280
