### ISSUE TITLE
Within cluster differential analysis

### ISSUE THREAD

**Issue by jianxinwang** [satijalab/seurat#6378]
Hi, is there anyway to do differential analysis within a cluster? I have a single cell project which involves samples under treatment and control conditions. I merged the two seurat objects together to make clusters. I would like to identify differentially expressed genes within a cluster between the treatment and control groups, however, I'm not able to found a way in the Seurat package. Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can find example of how to do this in the documentation of `FindMarkers` By setting optional parameters.

```
# Take all cells in cluster 2, and find markers that separate cells in the 'g1' group (metadata
# variable 'group')
markers <- FindMarkers(pbmc_small, ident.1 = "g1", group.by = 'groups', subset.ident = "2")
```

Best,
Sam

**Comment by jianxinwang** [comment]
Thanks you so much!

Jason
