### ISSUE TITLE
FindTransferAnchors on SCTransformed data for lable transfer

### ISSUE THREAD

**Issue by TRpeddoc** [satijalab/seurat#6379]
Hi, I am trying to transfer labels from one scRNA dataset to another, unlabeled set. I created Seurat objects and ran the SCTranformation pipeline on both with no issues, creating SCT assays.
next, I tried using Seurat V3 integration and label transfer vignette. the SCT tab does not have specific instructions for label transfer, so I went through these steps:
1. As specified in the documentation- the initial steps of Feature selection and prepSCTintegration.
2. used FindTransferAnchors on the prepped objects 

I keep getting this error:
>Warning: No columnames present in cell embeddings, setting to 'ProjectPC_1:1'
>Error: All cells in the object being added must match the cells in this object

This repeats also when running the Seurat vignette supplied data:

my code:

`pancreas.data <- ( "...pancreas_expression_matrix.rds")
metadata <- ("...pancreas_metadata.rds")
pancreas <- CreateSeuratObject(pancreas.data, meta.data = metadata)
pancreas.list <- SplitObject(pancreas, split.by = "tech")
for (i in 1:length(pancreas.list)) {
  pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], verbose = FALSE)
}
pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 3000)
options(future.globals.maxSize= 80000000000)

pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features, 
                                    verbose = FALSE)
anchors <- FindTransferAnchors(reference = pancreas.list[[1]], query= pancreas.list[[2]], normalization.method = "SCT",  dims = 30 )
`

I keep getting this error:
>Performing PCA on the provided reference using 3000 features as input.
>Projecting cell embeddings
>Warning: No columnames present in cell embeddings, setting to 'ProjectPC_1:1'
>Error: All cells in the object being added must match the cells in this object

I have tried: 
setting "reference.reduction" to call previously calculated PCAs for the objects, with no success. 
setting different "reduction" to other reduction methods

all result in the same error message. It seems that when creating the PCS object, the function names the PCs in a faulty way (?) and the next stepps in FindTransferAnchors are blocked.

session info:
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Seurat versions: 
SeuratObject_4.1.1 , Seurat_4.1.1.9003
SCTransform 0.3.4

```r
pancreas.data <- readRDS(file= ".../pancreas_expression_matrix.rds")
metadata <- readRDS(file=".../pancreas_metadata.rds")
pancreas <- CreateSeuratObject(pancreas.data, meta.data = metadata)
pancreas.list <- SplitObject(pancreas, split.by = "tech")
for (i in 1:length(pancreas.list)) {
  pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], verbose = FALSE)
}
pancreas.features <- SelectIntegrationFeatures(object.list = pancreas.list, nfeatures = 3000)
options(future.globals.maxSize= 80000000000)

pancreas.list <- PrepSCTIntegration(object.list = pancreas.list, anchor.features = pancreas.features, 
                                    verbose = FALSE)
anchors <- FindTransferAnchors(reference = pancreas.list[[1]], query= pancreas.list[[2]], normalization.method = "SCT",  dims = 30 )```

**Comment by saketkc** [comment]
Ideally one would want to do label transfer on a query object that is not part of the reference. In this case that reference is `pancreas.list` and not just the first object (`pancreas.list[[1]]`). You would want to do something like this:

```r
pancreas.query <- pancreas.list[["fluidigmc1"]]
DefaultAssay(pancreas.list) <- "integrated"
pancreas.anchors <- FindTransferAnchors(reference = pancreas.integrated, query = pancreas.query,
    dims = 1:30, reference.reduction = "pca", normalization.method="SCT")
```
