### ISSUE TITLE
FindClusters: Number of nodes/edges changes from one run to another

### ISSUE THREAD

**Issue by areyoukidneyme** [satijalab/seurat#6381]
Hello!

I was re-knitting an html file and I the file wasn't knitted successfully because the number of clusters somehow changed. I didn't change any of my codes so I was curious why the clustering changed. I traced it back to the `FindClusters` command. In my original knitted file this was the output:

> Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck
>  
> Number of nodes: 18134
> Number of edges: 848379
>  
> Running Louvain algorithm...
> Maximum modularity in 10 random starts: 0.8777
> Number of communities: 6
> Elapsed time: 5 seconds

When I rerun the same Rmarkdown file, everything was the same until the `FindClusters` output:

> Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck
> 
> Number of nodes: 18123
> Number of edges: 851680
> 
> Running Louvain algorithm...
> Maximum modularity in 10 random starts: 0.8761
> Number of communities: 7
> Elapsed time: 3 seconds

This change, I believe, resulted in giving me more clusters.

Can anyone explain to me why this is happening and what I should do to avoid this? 

Thanks in advance!

**Comment by longmanz** [comment]
Hi, 
If all your datasets and commands are unchanged, have you updated your Seurat to a different version? Do you still remember which version you used previously, and what is the current version of your Seurat?

**Comment by rsatija** [comment]
This appears to be a small error driven by numerical precision (18134 vs 18123 edges),  and is likely driven by running the Louvain algorithm on different systems. If you're able to post an example using any of the datasets in seurat_data where you say different values over different runs, please let us know, and we will work to debug.
