### ISSUE TITLE
Rescaling seurat object

### ISSUE THREAD

**Issue by devenderarora** [satijalab/seurat#6383]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal>We are running the analysis on two samples with different
conditions:<o:p></o:p></p>

<p class=MsoNormal>sample1_ctrl, sample1_E, sample1_EL<o:p></o:p></p>

<p class=MsoNormal>sample2_ctrl, sample2_E, sample2_EL<o:p></o:p></p>

<p class=MsoNormal>We have saved the Seurat object samples with information:<o:p></o:p></p>

<p class=MsoNormal>Seurat_obj$orig.ident<o:p></o:p></p>

sample1_ctrl | sample1_E | sample1_EL | sample2_ctrl | sample2_E | sample2_EL
-- | -- | -- | -- | -- | --
5543 | 5442 | 5322 | 6528 | 5952 | 6009

</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><b>Condition1<o:p></o:p></b></p>

<p class=MsoNormal>sample1_2$set&lt;- sub(&quot;_.*&quot;, &quot;&quot;,
seurat_obj$orig.ident)<o:p></o:p></p>

<p class=MsoNormal>sample1_2$set<o:p></o:p></p>

sample1 | sample2
-- | --
16307 | 18489

<p class=MsoNormal>When we run the Average expression, we can run without any
problem.<o:p></o:p></p>

<p class=MsoNormal>average_expr.scaledata_sample_1_2 &lt;-
AverageExpression(sample_1_2, return.seurat = F,<o:p></o:p></p>

<p class=MsoNormal><span
style='mso-spacerun:yes'>                                  </span>features =
gene_list_1_2, slot=&quot;scaled.data&quot;)<o:p></o:p></p>

</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal><b>Condition2<o:p></o:p></b></p>

<p class=MsoNormal>We tried to subset via <span
style='mso-spacerun:yes'> </span>function<o:p></o:p></p>

<p class=MsoNormal>sample1_all$set&lt;- subset(seurat_obj, orig.ident == c(‘sample1_ctrl',
‘sample1_E', ‘sample1_EL'))<o:p></o:p></p>

<p class=MsoNormal>But it failed to subset these samples together and removed
so many cells from the new seurat object.<o:p></o:p></p>

sample1_ctrl | sample1_E | sample1_EL
-- | -- | --
1765 | 1856 | 1954

</body>

</html>

**Condition3**
seurat_sample1_ctrl<-subset(seurat_obj, subset = orig.ident == "sample1_ctrl")
seurat_sample1_E<-subset(seurat_obj, subset = orig.ident == "sample1_E")
seurat_sample1_EL<-subset(seurat_obj, subset = orig.ident == "sample1_EL")

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal>seurat_sample &lt;- merge(seurat_ sample1 _ctrl, y =c
(seurat_ sample1 _E, seurat_ sample1 _EL), add.cell.ids= c(&quot;ctrl&quot;,
&quot;E&quot;, &quot;EL&quot;), project = &quot;scRNA&quot;)<o:p></o:p></p>

<p class=MsoNormal>table(seurat_sample$orig.ident)<o:p></o:p></p>

sample1_ctrl | sample1_E | sample1_EL
-- | -- | --
5543 | 5442 | 5322

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>

When we performed the Average expression on the seurat object:
average_expr.scaledata_sample<- AverageExpression(seurat_sample, return.seurat = F,
                                  features = gene_list_sample, slot="scaled.data")
We are ending up with the error “scaled slot empty” and need to perform scaling again on the data.

Our questions are:
**1.	When we use subset function with exact sample names in condition2 why did the number of cells reduce.
2.	Why do we need to scale the data again after merging the subset data?**

**Comment by timoast** [comment]
> 1. When we use subset function with exact sample names in condition2 why did the number of cells reduce.

You should be using `%in%` rather than `==`, eg:

```r
sample1_all$set<- subset(seurat_obj, orig.ident %in% c('sample1_ctrl', 'sample1_E', 'sample1_EL'))
```

> 2. Why do we need to scale the data again after merging the subset data?

The scaled and centered values for each cell depend on the values of other cells in the dataset, as this will affect the mean and sd. This is why we recommend re-scaling after subsetting or merging objects
