### ISSUE TITLE
Integration and Normalization of multiple biological replicates

### ISSUE THREAD

**Issue by stefanerb89** [satijalab/seurat#6390]
I have a problem with UMI normalization with different biological replicates. I have 3 control samples and 5 treatments. My approach is the following:

1. Normalization of each sample
2. Merge samples
3. DE analysis

My code:

```
for(i in 1:length(samples)){
  
  
xx <- Read10X(data.dir = paste0("/media/.../outs/filtered_feature_bc_matrix"))
  xx <- CreateSeuratObject(counts = xx, project = sample.names[i], min.cells=3, min.features=200)
  xx$sampleid <- sample.names[i]
  xx[["percent.mt"]] <- PercentageFeatureSet(xx, pattern = "^MT-")

  xx <- NormalizeData(ctrl1, normalization.method = "LogNormalize", scale.factor = 10000)
  xx <- SCTransform(ctrl1,method = "glmGamPoi", vars.to.regress = "percent.mt", verbose = FALSE)
 list[[i]] <- xx
}
```
Integration of data and for reference I used control samples 1-3:
```

all.samples.names <- c("Control1", "Control2", "Control3", "Pat1.0","Pat2.0","Pat4.0","Pat5.0")
rename.cells.list <- list()

for (i in 1:(length(all.samples))) {
  
  ctrl1 <- RenameCells(all.samples[[i]], add.cell.id = all.samples.names[i])
  rename.cells.list[[i]] <- ctrl1
}

features <- SelectIntegrationFeatures(object.list = rename.cells.list)
rename.cells.list <- PrepSCTIntegration(object.list = rename.cells.list, anchor.features = features)

anchors <- FindIntegrationAnchors(object.list = rename.cells.list, reference = c(1, 2, 3), normalization.method = "SCT", dims = 1:50, anchor.features = features)
immune.integrated <- IntegrateData(anchorset = anchors, dims = 1:50,normalization.method = "SCT", verbose=TRUE)
```

Now when I use the code from https://satijalab.org/seurat/articles/integration_introduction.html I get pretty crazy plots. The treatment samples have an expression count scale from 1-5 and the controls from 1-1000.

For example, S100A9 for control of 500 and Treatment only 4. It should be increased in the treatment samples. What I have done wrong? Something wrong with normalization?

**Comment by longmanz** [comment]
Hi @stefanerb89 ,
It is a bit strange to see such big difference in the count between samples. When you say "expression count scale from 1-5 and the controls from 1-1000", do you refer to the raw count? 

If so, this might indicates a big difference in the sequencing depth between samples. Is this batch effect as expected? 

In addition, you mentioned you got a "crazy plots". Do you refer to the UMAP? Could you please share your plots here if possible?

**Comment by yuhanH** [comment]
Since we haven’t heard from you, we will close this issue first. If you still have this issue, we can reopen it.
