### ISSUE TITLE
spaceranger 2.0 renamed tissue_positions_list.csv to tissue_positions.csv

### ISSUE THREAD

**Issue by simoncmo** [satijalab/seurat#6392]
Hi Seurat team,

For the latest spaceranger 2.0 pipeline, 10x renamed the output `tissue_positions_list.csv` to `tissue_positions.csv`

<img width="198" alt="image" src="https://user-images.githubusercontent.com/54045654/189178370-4a83d507-0688-42c0-893a-37efa91612b8.png">

`Load10X_spatial` failed at `Read10X_Image`

```r
# insert reproducible example here
Load10X_spatial(SEURAT_OUTPUT_PATH)
```

> Error in file(file, "rt") : cannot open the connection
> 6.
> read.csv(file = file.path(image.dir, "tissue_positions_list.csv"), 
> col.names = c("barcodes", "tissue", "row", "col", "imagerow", 
> "imagecol"), header = FALSE, as.is = TRUE, row.names = 1)
> 5.
> Read10X_Image(image.dir = file.path(data.dir, "spatial"), filter.matrix = filter.matrix)

At the moment I'm seeing this file name being hardcoded in `preprocessing.R` without a parameter to set it 
```r
Read10X_Image <- function(image.dir, image.name = "tissue_lowres_image.png", filter.matrix = TRUE, ...) {
  image <- readPNG(source = file.path(image.dir, image.name))
  scale.factors <- fromJSON(txt = file.path(image.dir, 'scalefactors_json.json'))
  tissue.positions <- read.csv(
    file = file.path(image.dir, 'tissue_positions_list.csv'),
    col.names = c('barcodes', 'tissue', 'row', 'col', 'imagerow', 'imagecol'),
    header = FALSE,
    as.is = TRUE,
    row.names = 1
  )
```
Could you please add an official fix to this function to make it compatible with both file names? 
Thanks!!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Have you tried the dev branch?  There was PR from 10X team couple months ago to address this.

https://github.com/satijalab/seurat/pull/6208#issue-1308410878

Best,
Sam
