### ISSUE TITLE
Questioning DEG results and correct implementation of pipeline with SCT(vst.flavor = "v2")

### ISSUE THREAD

**Issue by mauritsunkel** [satijalab/seurat#6395]
Hi Satijalab, 

Four questions:
Based on our differentially expressed genes (DEG) analysis with the default Wilcoxon rank sum test used by the FindMarkers family functions we were surprised with the results, 12367/13655 features tested had a p_val_adj < 0.05.
1. Is this common/normal in single-cell RNA DEG? 
2. Is there any book you could recommend me to read on single-cell RNA DEG analysis? 

I'm curious if my implementation of Seurat, including SCT workflow with vst flavor 2 for our data processing is correct for this DEG approach. In short, our experimental design has a mono-culture of cell type A and a co-culture of cell types A and B. After individual processing of the samples, I integrate them, after integration, we perform a cluster selection by a marker panel of some genes, then we want to perform DEG on orig.ident of mono-culture vs co-culture to see the DEG.

My summarized pipeline with Seurat (SCT with vst.flavor = "v2"): 
```
data.list <- list()

## individual processing
data <- Read10X(data.dir)
data <- CreateSeuratObject(data, min.cells = 3, min.features = 700)
data <- PercentageFeatureSet(data, pattern = "^MT-", col.name = "percent.mt")
data <- subset(data, subset = nFeature_RNA > 200)
data <- SCTransform(data, vst.flavor = "v2", vars.to.regress = "percent.mt", return.only.var.genes = TRUE)
data <- RunPCA(data, features = SeuratObject::VariableFeatures(object = data), npcs = 50, verbose = FALSE)
data <- FindNeighbors(data, dims = 1:20)
data <- FindClusters(data, resolution = 0.5, algorithm = 4) # use Leiden algorithm
data <- RunUMAP(data, reduction = "pca", dims = 1:20)

data.list[length(data.list)+1] <- data

## integration 
features   <- SelectIntegrationFeatures(data.list, nfeatures = 3000)
data.list  <- PrepSCTIntegration(data.list, anchor.features = features)
anchors    <- FindIntegrationAnchors(data.list, normalization.method = "SCT", anchor.features = features, reference = ref.sample)
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")

# integration-processing (once pre- and once postselection)
DefaultAssay(integrated) <- "integrated"
integrated <- RunPCA(integrated, features = SeuratObject::VariableFeatures(object = integrated), npcs = 50)
integrated <- FindNeighbors(integrated, dims = 1:20)
integrated <- FindClusters(integrated, resolution = 0.5, algorithm = 4, method = "igraph") # Leiden alg
integrated <- RunUMAP(integrated, reduction = "pca", dims = 1:20)
integrated <- PrepSCTFindMarkers(integrated, assay = "SCT")
SeuratObject::DefaultAssay(integrated) <- "SCT"
# cluster.selection defined by marker panel of interest for selecting clusters representing cell type A
integrated <- subset(integrated, idents = cluster.selection)
# re-run integration-processing up to selection

## cluster annotation (not shown)

## DEG analysis
sample_markers <- FindMarkers(integrated, assay = "SCT", ident.1 = "co-culture-cell-type-A", only.pos = FALSE, logfc.threshold = 0, min.pct = 0)
```

3. Is the pipeline logic here correct? 
4. Are the correct data slots being processed/used throughout for correct DEG analysis? 

I hope my question is clear, I'll be glad to share more details if needed! 

Thanks in advance for your time,
Maurits

**Comment by saketkc** [comment]
Hi @mauritsunkel, the pvalues can be inflated because of a large sample size. Your workflow looks correct. The only thing I would suggest is to also take into account the effect size (avg_log2FC) while interepreting the results and not just the (adjusted) p-values. Your current setting of `logfc.threshold=0` is too liberal which would explain the extremely high number of DE genes.
