### ISSUE TITLE
Seurat scRNA-seq integration

### ISSUE THREAD

**Issue by yjlui** [satijalab/seurat#6397]
I've done the tutorial on scRNA-seq integration (https://satijalab.org/seurat/articles/integration_introduction.html) using Seurat 4.1.1. Could someone please explain to me why seurat_clusters and seurat_annotations give different results? I'd imagine all the cells in Cluster 1 are "CD4 Naive T"?

> table(t.cells@meta.data$seurat_clusters)

   0    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   0 2499    0    0    0    0    0    0    0    0    0    0    0    0    0

> table(t.cells@meta.data$seurat_annotations)

CD4 Memory T  CD4 Naive T        CD8 T           Mk  T activated
          76         2365            9           17           32

Many thanks!

**Comment by AustinHartman** [comment]
The vignette referred to on the website was run using Seurat v4.0.6 so the unsupervised clustering results vary slightly due expected to changes in more recent versions

**Comment by yjlui** [comment]
Thank you for your replies, @AustinHartman and @k3yavi!

I actually think it could be a bug. I'm aware the the unsupervised clustering results  (UMAP) could be different if different versions of software are used. I've recently updated some software, so there are now only 14 (rather than 15) clusters. However, seurat_clusters and seurat_annotations ought to give the same results as basically one is the ID and the other is the description. 

Please see below for the codes I used (I literally copied and pasted the codes from the vignette; the number of elements in Cluster 1 is now 2528 as, like I said, some software has been updated):

> library(Seurat)
# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)
# Visualization
p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
Attaching SeuratObject
Attaching sp
> library(SeuratData)
── Installed datasets ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── SeuratData v0.2.2 ──
✔ ifnb   3.1.0                                                                                                        ✔ pbmc3k 3.1.4

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Key ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ Dataset loaded successfully
❯ Dataset built with a newer version of Seurat than installed
❓ Unknown version of Seurat installed

> library(patchwork)
> # install dataset
> InstallData("ifnb")
Warning: The following packages are already installed and will not be reinstalled: ifnb
> # load dataset
> LoadData("ifnb")
An object of class Seurat
14053 features across 13999 samples within 1 assay
Active assay: RNA (14053 features, 0 variable features)
> # split the dataset into a list of two seurat objects (stim and CTRL)
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
> # normalize and identify variable features for each dataset independently
> ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
+     x <- NormalizeData(x)
+     x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
+ })
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> # select features that are repeatedly variable across datasets for integration
> features <- SelectIntegrationFeatures(object.list = ifnb.list)
> immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
        Found 16393 anchors
Filtering anchors
        Retained 6756 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04m 41s
> # this command creates an 'integrated' data assay
> immune.combined <- IntegrateData(anchorset = immune.anchors)
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
> # specify that we will perform downstream analysis on the corrected data note that the
> # original unmodified data still resides in the 'RNA' assay
> DefaultAssay(immune.combined) <- "integrated"
> # Run the standard workflow for visualization and clustering
> immune.combined <- ScaleData(immune.combined, verbose = FALSE)
> immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
> immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
Warning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
This message will be shown once per session
21:54:26 UMAP embedding parameters a = 0.9922 b = 1.112
21:54:26 Read 13999 rows and found 30 numeric columns
21:54:26 Using Annoy for neighbor search, n_neighbors = 30
21:54:26 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:54:29 Writing NN index file to temp file /tmp/RtmpQtuTC7/file49158d5d3c8
21:54:29 Searching Annoy index using 1 thread, search_k = 3000
21:54:33 Annoy recall = 100%
21:54:34 Commencing smooth kNN distance calibration using 1 thread with target n_neighbors = 30
21:54:35 Initializing from normalized Laplacian + noise (using irlba)
21:54:36 Commencing optimization for 200 epochs, with 619596 positive edges
Using method 'umap'
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:54:56 Optimization finished
> immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
Computing nearest neighbor graph
Computing SNN
> immune.combined <- FindClusters(immune.combined, resolution = 0.5)
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 13999
Number of edges: 569433

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.9058
Number of communities: 15
Elapsed time: 2 seconds
1 singletons identified. 14 final clusters.
> # Visualization
> p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "stim")
> p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE, repel = TRUE)
> p1 + p2
> DimPlot(immune.combined, reduction = "umap", split.by = "stim")
> # For performing differential expression after integration, we switch back to the original
> # data
> DefaultAssay(immune.combined) <- "RNA"
> nk.markers <- FindConservedMarkers(immune.combined, ident.1 = 6, grouping.var = "stim", verbose = FALSE)
> head(nk.markers)
       CTRL_p_val CTRL_avg_log2FC CTRL_pct.1 CTRL_pct.2 CTRL_p_val_adj
GNLY            0        6.006422      0.944      0.045              0
FGFBP2          0        3.223246      0.503      0.020              0
CLIC3           0        3.466418      0.599      0.024              0
PRF1            0        2.654683      0.424      0.017              0
CTSW            0        2.991829      0.533      0.029              0
KLRD1           0        2.781453      0.497      0.019              0
          STIM_p_val STIM_avg_log2FC STIM_pct.1 STIM_pct.2 STIM_p_val_adj
GNLY    0.000000e+00        5.863771      0.956      0.060   0.000000e+00
FGFBP2 2.789932e-160        2.196674      0.259      0.016  3.920691e-156
CLIC3   0.000000e+00        3.545647      0.625      0.031   0.000000e+00
PRF1    0.000000e+00        4.100747      0.863      0.057   0.000000e+00
CTSW    0.000000e+00        3.135466      0.594      0.035   0.000000e+00
KLRD1   0.000000e+00        2.875972      0.556      0.027   0.000000e+00
            max_pval minimump_p_val
GNLY    0.000000e+00              0
FGFBP2 2.789932e-160              0
CLIC3   0.000000e+00              0
PRF1    0.000000e+00              0
CTSW    0.000000e+00              0
KLRD1   0.000000e+00              0
> FeaturePlot(immune.combined, features = c("CD3D", "SELL", "CREM", "CD8A", "GNLY", "CD79A", "FCGR3A",
+     "CCL2", "PPBP"), min.cutoff = "q9")
> immune.combined <- RenameIdents(immune.combined, `0` = "CD14 Mono", `1` = "CD4 Naive T", `2` = "CD4 Memory T",
+     `3` = "CD16 Mono", `4` = "B", `5` = "CD8 T", `6` = "NK", `7` = "T activated", `8` = "DC", `9` = "B Activated",
+     `10` = "Mk", `11` = "pDC", `12` = "Eryth", `13` = "Mono/Mk Doublets", `14` = "HSPC")
Warning: Cannot find identity 14
> DimPlot(immune.combined, label = TRUE)
> Idents(immune.combined) <- factor(Idents(immune.combined), levels = c("HSPC", "Mono/Mk Doublets",
+     "pDC", "Eryth", "Mk", "DC", "CD14 Mono", "CD16 Mono", "B Activated", "B", "CD8 T", "NK", "T activated",
+     "CD4 Naive T", "CD4 Memory T"))
> markers.to.plot <- c("CD3D", "CREM", "HSPH1", "SELL", "GIMAP5", "CACYBP", "GNLY", "NKG7", "CCL5",
+     "CD8A", "MS4A1", "CD79A", "MIR155HG", "NME1", "FCGR3A", "VMO1", "CCL2", "S100A9", "HLA-DQA1",
+     "GPR183", "PPBP", "GNG11", "HBA2", "HBB", "TSPAN13", "IL3RA", "IGJ", "PRSS57")
> DotPlot(immune.combined, features = markers.to.plot, cols = c("blue", "red"), dot.scale = 8, split.by = "stim") +
+     RotatedAxis()
> library(ggplot2)
> library(cowplot)

Attaching package: ‘cowplot’

The following object is masked from ‘package:patchwork’:

    align_plots

> theme_set(theme_cowplot())
> t.cells <- subset(immune.combined, idents = "CD4 Naive T")
> Idents(t.cells) <- "stim"
> avg.t.cells <- as.data.frame(log1p(AverageExpression(t.cells, verbose = FALSE)$RNA))
> avg.t.cells$gene <- rownames(avg.t.cells)
> cd14.mono <- subset(immune.combined, idents = "CD14 Mono")
> Idents(cd14.mono) <- "stim"
> avg.cd14.mono <- as.data.frame(log1p(AverageExpression(cd14.mono, verbose = FALSE)$RNA))
> avg.cd14.mono$gene <- rownames(avg.cd14.mono)
> genes.to.label = c("ISG15", "LY6E", "IFI6", "ISG20", "MX1", "IFIT2", "IFIT1", "CXCL10", "CCL8")
> p1 <- ggplot(avg.t.cells, aes(CTRL, STIM)) + geom_point() + ggtitle("CD4 Naive T Cells")
> p1 <- LabelPoints(plot = p1, points = genes.to.label, repel = TRUE)
When using repel, set xnudge and ynudge to 0 for optimal results
> p2 <- ggplot(avg.cd14.mono, aes(CTRL, STIM)) + geom_point() + ggtitle("CD14 Monocytes")
> p2 <- LabelPoints(plot = p2, points = genes.to.label, repel = TRUE)
When using repel, set xnudge and ynudge to 0 for optimal results
> p1 + p2

> table(t.cells@meta.data$seurat_clusters)

   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   0 2528    0    0    0    0    0    0    0    0    0    0    0    0
> table(t.cells@meta.data$seurat_annotations)

CD4 Memory T  CD4 Naive T        CD8 T           Mk  T activated
          76         2382            9           23           38
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /Filers/package/R-base/4.2.0/lib64/R/lib/libRblas.so
LAPACK: /Filers/package/R-base/4.2.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] cowplot_1.1.1           ggplot2_3.3.6           patchwork_1.1.2
[4] pbmc3k.SeuratData_3.1.4 ifnb.SeuratData_3.1.0   SeuratData_0.2.2
[7] sp_1.5-0                SeuratObject_4.1.0      Seurat_4.1.1

loaded via a namespace (and not attached):
  [1] TH.data_1.1-1         Rtsne_0.16            colorspace_2.0-3
  [4] deldir_1.0-6          ellipsis_0.3.2        ggridges_0.5.3
  [7] spatstat.data_2.2-0   leiden_0.4.3          listenv_0.8.0
 [10] farver_2.1.1          ggrepel_0.9.1         mvtnorm_1.1-3
 [13] fansi_1.0.3           mathjaxr_1.6-0        codetools_0.2-18
 [16] splines_4.2.0         mnormt_2.1.0          TFisher_0.2.0
 [19] polyclip_1.10-0       jsonlite_1.8.0        ica_1.0-3
 [22] cluster_2.1.3         png_0.1-7             rgeos_0.5-9
 [25] uwot_0.1.14           shiny_1.7.2           sctransform_0.3.3
 [28] spatstat.sparse_2.1-1 compiler_4.2.0        httr_1.4.4
 [31] assertthat_0.2.1      Matrix_1.4-1          fastmap_1.1.0
 [34] lazyeval_0.2.2        limma_3.52.1          cli_3.4.0
 [37] later_1.3.0           htmltools_0.5.2       tools_4.2.0
 [40] igraph_1.3.4          gtable_0.3.1          glue_1.6.2
 [43] RANN_2.6.1            reshape2_1.4.4        dplyr_1.0.10
 [46] rappdirs_0.3.3        Rcpp_1.0.9            Biobase_2.56.0
 [49] scattermore_0.8       vctrs_0.4.1           multtest_2.52.0
 [52] nlme_3.1-157          progressr_0.11.0      lmtest_0.9-40
 [55] spatstat.random_2.2-0 stringr_1.4.1         rbibutils_2.2.8
 [58] globals_0.16.1        mime_0.12             miniUI_0.1.1.1
 [61] lifecycle_1.0.2       irlba_2.3.5           goftest_1.2-3
 [64] future_1.28.0         qqconf_1.1.1          MASS_7.3-57
 [67] zoo_1.8-11            scales_1.2.1          spatstat.core_2.4-4
 [70] promises_1.2.0.1      spatstat.utils_2.3-1  sandwich_3.0-1
 [73] parallel_4.2.0        RColorBrewer_1.1-3    reticulate_1.25
 [76] pbapply_1.5-0         gridExtra_2.3         rpart_4.1.16
 [79] stringi_1.7.8         mutoss_0.1-12         plotrix_3.8-2
 [82] BiocGenerics_0.42.0   Rdpack_2.3.1          rlang_1.0.5
 [85] pkgconfig_2.0.3       matrixStats_0.62.0    lattice_0.20-45
 [88] ROCR_1.0-11           purrr_0.3.4           tensor_1.5
 [91] htmlwidgets_1.5.4     labeling_0.4.2        tidyselect_1.1.2
 [94] parallelly_1.32.1     RcppAnnoy_0.0.19      plyr_1.8.7
 [97] magrittr_2.0.3        R6_2.5.1              generics_0.1.3
[100] multcomp_1.4-19       DBI_1.1.2             withr_2.5.0
[103] sn_2.0.2              pillar_1.8.1          mgcv_1.8-40
[106] fitdistrplus_1.1-8    survival_3.3-1        abind_1.4-5
[109] tibble_3.1.8          future.apply_1.9.1    crayon_1.5.1
[112] KernSmooth_2.23-20    utf8_1.2.2            spatstat.geom_2.4-0
[115] plotly_4.10.0         grid_4.2.0            data.table_1.14.2
[118] metap_1.8             digest_0.6.29         xtable_1.8-4
[121] numDeriv_2016.8-1.1   tidyr_1.2.1           httpuv_1.6.6
[124] stats4_4.2.0          munsell_0.5.0         viridisLite_0.4.1

**Comment by yjlui** [comment]
> Hi @yjlui,
> 
> It seems you have only one cluster on the Seurat object and somehow assigned multiple cell-type annotations. Hard to say without the code.

Sent you the code (I _literally_ copied and pasted the code from the vignette). Looks like a bug to me tbh. Thank you.
