### ISSUE TITLE
scRNA-seq integration with another dataset to include missing cell population

### ISSUE THREAD

**Issue by juhjeong** [satijalab/seurat#6400]
Hello, Satija lab

I downloaded a #1 pancreatic cancer scRNA-seq dataset (aquired from multiple patients) via GEO, which is publicly available. 
But, I found out endothelial cell population was missing from the dataset for some reasons (may be...missing during tissue processing?)

Meanwhile, another publicly available #2 scRNA-seq dataset only includes endothelial cells (pancreatic tumor-infiltrated CD31+ endothelial cells were sorted... of course from different patients).

In this case, is it acceptable to integrate #1 and #2 datasets for Seurat analysis in order to analyze a further complete tumor microenvironment? 
Do you think that there are no logical flaws for this integration analysis?

Thanks for your opinion, in advance.

Best,
Juhee

**Comment by f6v** [comment]
@juhjeong I'm not from Satija lab, but can try to answer.

These kinds of questions keep popping up regularly. I don't think you're going to get an answer in a way you expect. It all depends on your downstream analysis and the batch effect magnitude. Keep in mind that tumor microenvironment can be heterogenous in different patients. What do you expect to see by combining the datasets?

**Comment by torkencz** [comment]
Hi,

Unfortunately, I have to agree that it would be difficult to figure out what is true biological variation vs batch effect. Integration will not likely solve your problem of the missing endothelial cells. Also, the fact that you don't really have overlapping cell types between your datasets makes things even harder.
