### ISSUE TITLE
Seurat object making issue

### ISSUE THREAD

**Issue by DukKi88** [satijalab/seurat#6402]
Hello, 

I have a problem with data import from GSE141259. 
(GSE link : https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE141259)

In GSE141259, there is barcodes.txt.gz, genes.txt.gz, rawcounts.mtx.gz instead of tsv.gz files. 
Datas were imported as follows, 

setwd("directory") # setting directory to read data from it
counts<-readMM("GSE141259_WholeLung_rawcounts.mtx.gz")
Genes = read.table(gzfile("GSE141259_WholeLung_genes.txt.gz"),sep="\t")
Barcodes = read.table(gzfile("GSE141259_WholeLung_Barcodes.txt.gz"),sep="\t")

but i cannot merged afterwards. 

rownames(counts) <- Barcodes
Error in dimnamesGets(x, value) : 
  invalid dimnames given for “dgCMatrix” object
rownames(counts) <- Genes
Error in dimnamesGets(x, value) : 
  invalid dimnames given for “dgCMatrix” object

Thank you for the generous help, in advance...

Best Regards,
DKK

**Comment by jarchana09** [comment]
Hello DKK. After reading in the gene IDs and cell barcodes, assigning these variables to the column with the data, before adding these values to the counts matrix, may be helpful (as mentioned in this site: [https://github.com/hbctraining/scRNA-seq/blob/master/lessons/readMM_loadData.md](https://github.com/hbctraining/scRNA-seq/blob/master/lessons/readMM_loadData.md) ).

For example, extending your code:
```
gene_ids <- Genes$V1 #where V1 is the column name for the column that contains the gene IDs/symbols
barcode_ids <- Barcodes$V1 #where V1 is the column name for the column that contains the barcode/cell IDs

rownames(counts) <- gene_ids #gene IDs as row names of the counts matrix
colnames(counts) <- barcode_ids #cell barcode IDs as column names of the counts matrix 
```
You could also assign the appropriate columns while reading in the data.
For example,
```
Genes <- read.table(gzfile("GSE141259_WholeLung_genes.txt.gz"),sep="\t")$V1
Barcodes <- read.table(gzfile("GSE141259_WholeLung_Barcodes.txt.gz"),sep="\t")$V1
```


Hope this helps.
Thanks.
