### ISSUE TITLE
Does sample size affect FeaturePlot?

### ISSUE THREAD

**Issue by Sahu-Mousumi** [satijalab/seurat#6403]
Hi All!
I have 27 disease and 10 control samples. I have done an integration analysis. And for a particular cell type I have subset the object. I plotted feature plot for couple of genes and I found more disease cells expressing some of the genes in compared to control. 

Is it true for biological reason or I should go for any normalization process for sample size? These are uncorrected values from RNA assay. 
 
Thanks!

**Comment by yuhanH** [comment]
Hi, 
FeaturePlot is just a visualization method. If you want to get biological conclusion, you need to apply related normalization and statistics methods to get your conclusion.
