### ISSUE TITLE
how to add new metadata

### ISSUE THREAD

**Issue by IlianCx** [satijalab/seurat#6405]
Hello
I am trying to add scrublet calls as meta data with the below code for deletion of doublets after few steps.

doublets <- read.csv("../scrublet_output_table.csv", header = F, row.names = Null)
colnames(doublets) <- c("doublet_score","predicted_doublet")
object <- AddMetaData(object,doublets)
head(object[[]])

Though I can see two new columns as doublet scores and doublet, I couldn't able to see the data stored in the columns for the object. 
if I change, row.names to 1, it shows that it is not allowed.
Is there any other way to add new metadata for the object?

Thanks for your help in advance!
IllianCx

**Comment by denvercal1234GitHub** [comment]
It should fix it if you add each column (i.e., double_score column then add predicted_doublet column later) as meta data instead of adding the data frame of two columns as meta data.

**Comment by timoast** [comment]
> Though I can see two new columns as doublet scores and doublet, I couldn't able to see the data stored in the columns for the object.

Can you clarify what you mean by this?

**Comment by IlianCx** [comment]
Please check the attached figure. There are no values in the new columns. when I change row. names=1, it shows new row names are not allowed.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/111017980/190713405-b58f6ef0-5af2-4639-a0e3-6a068a63ece8.png">

Thanks for your help!

**Comment by timoast** [comment]
My guess is that the rownames of the "doublets" dataframe do not match the cell names in your Seurat object. Can you show the first few lines of the doublets object?

**Comment by IlianCx** [comment]
Here is the shot of first few lines in scrublet output file
<img width="288" alt="image" src="https://user-images.githubusercontent.com/111017980/190715955-286400ab-2cd7-40de-8bf4-6b818d48e157.png">
Thanks!!

**Comment by timoast** [comment]
The dataframe needs to have row names that match the cell names in the Seurat object (otherwise there's no way to know what metadata is for what cell). You'll need to add this before adding metadata to the object
