### ISSUE TITLE
Error in validityMethod(as(object, superClass)) :    object 'Matrix_validate' not found

### ISSUE THREAD

**Issue by BohrXD** [satijalab/seurat#6407]
Error in validityMethod(as(object, superClass)) : 
  object 'Matrix_validate' not found

while using

 scRNA.counts <- Read10X(data.dir = "filtered_feature_bc_matrix") 

and

scRNA <- FindNeighbors(scRNA, dims = pc.num) 

what just happend ?

**Comment by B195515** [comment]
I had the same issue with loading a .mtx file.

**Comment by Zzzzuri** [comment]
me2, does anyone know how to solve this problem??? plzzzzzzzz Q^Q

**Comment by B195515** [comment]
I tried updating the "Matrix" package to version 1.5-1 and removed the previous version from the library folder. Restart R/RStudio and reload the libraries that use Matrix as dependency. It should work.

**Comment by BohrXD** [comment]
guys,,update 'Matrix' to >=1.5-0 does worked :)

**Comment by andywangcqmu** [comment]
it works, you guys are my heros.
