### ISSUE TITLE
HVFInfo failed to retrieve variable feature information if SelectIntegrationFeatures() was used for merged object

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6412]
Following up on issue #6263, `HVFInfo()` failed to retrieve variable feature information if we selected the variable features for a merged Seurat object using `SelectIntegrationFeatures()` instead of running `SCTransform` on the merged object directly.

Would you mind letting me know how to get variable feature info in this case?

Note: I did this because I SCTransform(v2) each object separately before merging them, which removed their variable features. I thus used SelectIntegrationFeatures() output as variable features for the merged object.

Thank you again for your help!

```
merged_var_features <- SelectIntegrationFeatures(object_list, assay = c("SCT", "SCT"), nfeatures = 5000, fvf.nfeatures=5000)

VariableFeatures(merged_object) <- merged_var_features

HVFInfo(merged_object, assay="SCT")
```

Error = `Error: Please run either 'FindVariableFeatures' or 'SCTransform'`

**Comment by saketkc** [comment]
It is tricky to define "gmean", "residual_variance" and "variance" on features given there are multiple datasets. You can run `SCTResults(merged_object, slot = "feature.attributes")` to get a list of these attributes for each dataset.

**Comment by denvercal1234GitHub** [comment]
Thanks @saketkc. Running `SCTResults(merged_object, slot = "feature.attributes")` returned results for different models, e.g., `model1`, `model1.1`, ... `model1.5`. Each model has a different number of features, whereas my merged Seurat SCT object has 16,003 features. What is the difference among these models?

Thanks for your help.


<img width="645" alt="Screenshot 2023-12-27 at 17 58 21" src="https://github.com/satijalab/seurat/assets/62179082/4d0c0fb0-9d11-4e01-99b2-b6f5d049cbf2">
