### ISSUE TITLE
irlba() in RunPCA()c doesn't have center argument options

### ISSUE THREAD

**Issue by wanghao98** [satijalab/seurat#6413]
I am trying to understand the RunPCA command. It appears that when `approx=TRUE` it calls the irlba function to run a svd of the matrix:

```
  if (approx) {
      npcs <- min(npcs, nrow(x = object) - 1)
      pca.results <- irlba(A = t(x = object), nv = npcs, ...)
      ...
  }
```
This means that it uses the default `center` option for `irlba` (which is `NULL` meaning no centering). 
However, in the help for the irlba function, the correspondence to PCA would require `center=colMeans(X)`. You can see this in their example code:

```
set.seed(1)
A <- matrix(runif(400), nrow=20)
# Principal components (see also prcomp_irlba)
P <- irlba(A, nv=1, center=colMeans(A))
# Compare with prcomp and prcomp_irlba (might vary up to sign)
cbind(P$v,
prcomp(A)$rotation[, 1],
prcomp_irlba(A)$rotation[, 1])
```

If you do not include the center command, you do not get the same as the `prcomp`
```
P <- irlba(A, nv=1)
# Compare with prcomp and prcomp_irlba (might vary up to sign)
cbind(P$v,
prcomp(A)$rotation[, 1],
prcomp_irlba(A)$rotation[, 1])
```

Therefore, I am unclear what exactly is RunPCA doing and why it is not centering the matrix before running the SVD.

**Comment by timoast** [comment]
The data used by the RunPCA function is already scaled and centered (the output of `ScaleData()` typically)
