### ISSUE TITLE
SampleUMI source code?

### ISSUE THREAD

**Issue by reliscu** [satijalab/seurat#6417]
I'm looking for the source code for RunUMISampling, which is called from SampleUMI. Would someone be kind enough to point me to this?

Thanks in advance.

**Comment by samuel-marsh** [comment]
Hi,

All source code can be found in “R” folder in the repo.  In this case here is link to `SampleUMI`:
https://github.com/satijalab/seurat/blob/a1294c4d363780548dbf9cc4a4abb3a6078a6d64/R/preprocessing.R#L1460

Best,
Sam

**Comment by reliscu** [comment]
Hi @samuel-marsh,

Thanks for getting back to me.

I was actually asking about the source code for **RunUMISampling** (and, ideally, **RunUMISamplingPerCell**), which is _called_ from  SampleUMI. I'm unable to find the definitions for these functions in preprocessing.R.

Thanks,
Rebecca

**Comment by samuel-marsh** [comment]
Hi Rebecca,

sorry misread there.  Those are in two parts as they are Rcpp exports.

R export script is here:
https://github.com/satijalab/seurat/blob/8da35ba8dc2d60f504f7cf276efd684dc19a418c/R/RcppExports.R

You can find rest of code in src folder.  If you search within repo for the function names you find all scripts they are part of for easy viewing.

Best,
Sam

**Comment by reliscu** [comment]
Thanks Sam, appreciate it!
