### ISSUE TITLE
Questions about figure size adjustment

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6419]
Hi, I wonder if there are any methods I can use to adjust the figure size of the output figure of Seurat, for example, Vlnplot()
Can I use something like plot+(...)? Thanks a lot.

**Comment by samuel-marsh** [comment]
Hi,

Are you trying to adjust the size of figure when saved to file?

Best,
Sam

**Comment by timoast** [comment]
Closing since we haven't received any more information. You can also search general R documentation for advice about saving plots with different sizes

**Comment by HelloWorldLTY** [comment]
Sorry for my late reply, yes, I wonder how to adjust the figure size and quality when we intend to save the file?

**Comment by samuel-marsh** [comment]
Hi,

So as @timoast has mentioned you search R documentation for even more info but basically you can supply height width, and other image parameters in image saving functions like `ggsave()` or `pdf()`.

Example from ggsave documentation:
`ggsave("mtcars.pdf", width = 20, height = 20, units = "cm") `

Best,
Sam
