### ISSUE TITLE
Installation error/package load failed for 'Seurat'

### ISSUE THREAD

**Issue by fly4all** [satijalab/seurat#642]
I've been trying to install Seurat following the directions on the website. 
Version of R: 3.5

**Code shown below:**
```R
install.packages("Seurat")
library(Seurat)
library(dplyr)

# Load the PBMC dataset
data_dir <- '/Downloads/'
list.files(data_dir)
pbmc.data <- Read10X(data.dir = data_dir)

```
**The output I got is displayed below:**
```R
> install.packages("Seurat")
Installing package into ‘/Users/ahmedmar/Library/R/3.5/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/Seurat_2.3.4.tgz'
Content type 'application/x-gzip' length 2653423 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

The downloaded binary packages are in
	/var/folders/77/pdjzg7792t54dw36kjhw147m2yxqts/T//RtmpLofqVO/downloaded_packages
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’
> library(dplyr)
> 
>  Load the PBMC dataset
> data_dir <- '/Downloads/'
> list.files(data_dir)
[1] "pbmc3k_filtered_gene_bc_matrices.tar" "practice_seurat.R"                   
> pbmc.data <- Read10X(data.dir = data_dir)
Error in Read10X(data.dir = data_dir) : could not find function "Read10X"
```

**Comment by evolvedmicrobe** [comment]
The `hdf5r` library is one of a few set of R packages that requires code not installed by R.  You don't have this code available, and so cannot install that package.

By analogy, some TVs come with a built in cable-box or antenna and work just fine on their own.  Other TVs need a separate and pre-existing cable box or antenna to produce anything but jibberish on the screen.  The `hdf5r` package is such a TV, and you will need to separately install the `hdf5` library (the equivalent of the cable-box/TV) before it will work.  See the key instructions in the error message (below) and try again.

    The required HDF5 library files can be installed as follows:
    - Debian-based (e.g. Debian >= 8.0, Ubuntu >= 15.04): 'sudo apt-get install libhdf5-dev'
    - Old Debian-based (e.g Debian < 8.0, Ubuntu < 15.04): Install from source (see INSTALL)
    - OS X using Homebrew: 'brew install homebrew/science/hdf5'
    - RPM-based (e.g Fedora): 'sudo yum install hdf5-devel'

**Comment by 117999** [comment]
got similar problem when I tried to 
`library(Seurat)`
it appeared that
`Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘multtest’`
I have tried to 
`install.packages('multtest')` separately, still it comes as
`package ‘multtest’ is not available (for R version 3.6.3)` don't know what's the problem, anyone can help?

**Comment by timoast** [comment]
multtest is on bioconductor: https://www.bioconductor.org/packages/release/bioc/html/multtest.html

To install:

```r
BiocManager::install(multtest)
```

**Comment by 117999** [comment]
I have got a new problem when I am trying to reinstall Seurat or update it
it appears to be successfully installed
but when I tried to use it 
`library (Seurat)`
The output I got is displayed below:
`Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.5 is already loaded, but >= 0.4.6 is required`
what should I do then?

**Comment by mailcolm9** [comment]
> multtest is on bioconductor: https://www.bioconductor.org/packages/release/bioc/html/multtest.html
> 
> To install:
> 
> ```r
> BiocManager::install(multtest)
> ```

Hi,

I encounter the same issue, and don't know what happened.

**Comment by YunzhouYang** [comment]
hi, @evolvedmicrobe 
i used the "brew install hdf5" in the os terminal and it worked.
if it doesn't work, update the brew and reinstall the hdf5. this worked for me.

thank you.
