### ISSUE TITLE
Error when running CreateSeuratObject

### ISSUE THREAD

**Issue by FionaMoon** [satijalab/seurat#6420]
Hi, Seurat group
 I got error when running `CreateSeuratObject` recently which never happened before.
```
data <- CreateSeuratObject(counts = x, min.cells = min_cells, min.features = min_features, project = project_name)

# Error in Matrix(from) : invalid 'data'
```
`x` is a data.frame which load from counts.csv

 Any advice would be appreciated!

Fiona

**Comment by saketkc** [comment]
What is the output of `x[1:5, 1:5]`

**Comment by mojaveazure** [comment]
Please ensure your data frame has only numeric or integer values

```R
for (i in names(x) {
  print(class(x[[i]]))
}
```
We cannot use non-numeric or non-integer values in a `Seurat` object
