### ISSUE TITLE
how to see in which cluster is not expressed a gene

### ISSUE THREAD

**Issue by feanaros** [satijalab/seurat#6422]
Hello, I want to select, as I saw in my umap, which cluster has the expression of a specific gene as zero. There is a way? thank you

**Comment by samuel-marsh** [comment]
Hi,

visualizing the data as `VlnPlot` can probably give you best idea for which clusters have lowest (or zero) expression of gene.  If you want to subset and analyze data without those clusters or only within those clusters you can use `subset` function.

Best,
Sam

**Comment by feanaros** [comment]
Hi! thank you!
