### ISSUE TITLE
LocalStruct metric on the SC Transformed Data

### ISSUE THREAD

**Issue by TatjanaUffelmann** [satijalab/seurat#6423]
Hi dear Seurat Team, 

I have to compare different integration methods in Seurat metrics. It turned out that this was not easy with the Sctransformed data. 
I would like to compare the methods and use the LocalStruct as a Metric. However applying the LocalStruct on my data, I get following error: 
"Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-" 
My solutions to fix this did not work! 

How could I solve that issue und calculate the LocalStruct? 

Thanks a lot for helping !

**Comment by yuhanH** [comment]
hi @TatjanaUffelmann 
I don't think you can use `LocalStruct ` function on SCTransformed data. 
You need to re-write the function a little bit based on the source code.
You can replace this `FindVariableFeatures` with `VariableFeatures(ob) <- features` where `features` are your pre-defined variable features. 
```
    ob <- FindVariableFeatures(
      object = ob,
      verbose = FALSE,
      selection.method = "dispersion",
      nfeatures = 2000
    )
```
