### ISSUE TITLE
"keep.scale" argument not working if scale_color_gradientn() is added to a FeaturePlot() function

### ISSUE THREAD

**Issue by gabrielnegreira** [satijalab/seurat#6424]
Hi, 

I am having a small problem when I try to create a plot with a custom color scale. I am doing a plot with 4 samples in a seurat object using FeaturePlot() with the argument "split.by" set to "sample". I want the color scale for the feature I'm plotting to have the same range across the 4 samples. I understand this is the standard behavior of the FeaturePlot() function as the keep.scale argument is by default set to "feature". However, if I add a custom color scale using &scale_colour_gradientn(), then each plot has its own scale range, making comparisons between samples not feasible. If the &scale_colour_gradientn() is not included, then the color range is the same across samples, so I think the scale_colour_gradientn() function overwrites the keep.scale argument from FeaturePlot(). Is there a way to fix this?

The code that returns a plot with the same scale range across samples is:

```
FeaturePlot(seuratObj, feature, keep.scale = "feature", split.by = "sample")
```

While the code that returns a plot with each sample having its own color scale range is:

```
FeaturePlot(seuratObj, feature, keep.scale = "feature", split.by = "sample")&
  scale_color_gradientn(colors = my_pallete)
```

Thanks for any suggestions!

**Comment by samuel-marsh** [comment]
Also as note if using scCustomize, I would suggest using the develop branch because it’s close to new release and contains lots of bug fixes.

**Comment by gabrielnegreira** [comment]
> Also as note if using scCustomize, I would suggest using the develop branch because it’s close to new release and contains lots of bug fixes.

Thanks a lot for the suggestion! I'll try your package. 

Best,

Gabriel
