### ISSUE TITLE
Heatmap DEGs overlap: How to handle 

### ISSUE THREAD

**Issue by Deepesh123gupta** [satijalab/seurat#6431]
Here, I have so many clusters with DEGs but these genes are not very distinct for each clusters (to some extent which is normal). How to handle it? Data collected from scRNAseq. 
Suggestions are appreciated. 
![image](https://user-images.githubusercontent.com/62347074/190715574-522de9a3-f987-4f01-815e-ff7fb6733705.png)

**Comment by longmanz** [comment]
Hi,
Could you please let me know what is each column representing? Is each column here representing a single cell or a pseudo-bulked cell type/cluster? 

In addition, how is DEG defined for each cluster? Are they from FindMarkers()/FindAllMarkers() in Seurat?

**Comment by Deepesh123gupta** [comment]
This is the average gene expression heatmap. Each column represents cluster. DEGs are defined using FINDAllmarkers() and plotted top 10 gene for 18 clusters (in seurat).

**Comment by mhkowalski** [comment]
Hello, 

To find distinct genes for each cluster, you may have to run `FindMarkers` to compare similar clusters (if clusters are similar compared to the rest of your dataset, they may have the same markers that come up in `FindAllMarkers`, because this is a 1-vs-all comparison).
