### ISSUE TITLE
Combine subset with WhichCells

### ISSUE THREAD

**Issue by JessicaP94** [satijalab/seurat#6432]
Hello,
I'm trying to subset a Seurat object based on gene expression level in only 2 clusters. The other clusters should remain untouched.
I tried this but didn't work:
``
Wu_Ptgfrn<-subset(Wu, subset=PTGFRN>0.5, 
                     idents = WhichCells(Wu, expression = PTGFRN>0.5,idents = c("CAFs","PVL")))
``
Error in WhichCells.Seurat(object = x, cells = cells, idents = idents,  : 
  Cannot find the following identities in the object: CID3586_AGCGGTCGTGACTCATCID3586_ATTACTCAGTGCAAGCCID3586_CAACCAACAAGTCTGTCID3586_CACCTTGAGTGATCGGCID3586_CGTCTACGTTACGCGCCID3586_TCCCGATAGCAGACTGCID3586_GTGTGCGGTCGCGTGTCID3586_ACTATCTTCAGCGACCCID3586_TGGTTAGTCTCAAGTGCID3586_CTGGTCTTCTGCGACGCID3586_GTGCATAAGATCCGAGCID3586_CAAGAAAAGATGGGTCCID3586_CCCATACGTCATCCCTCID3586_CTGCCTATCGCGTAGCCID3586_GACCAATTCTTTACACCID3586_GCAGCCATCTCTGCTGCID3586_GCTCCTAGTATAAACGCID3586_TGGCGCAGTAAGGATTCID3921_CATGCCTCATACAGCTCID3921_CCTACCAGTCGGCATCCID3921_CCTCAGTGTGTTTGGTCID3921_CTGATCCCATAAGACACID3921_GTACTTTAGAGGTTGCCID3921_TGCGCAGTCGTTTATCCID3921_ACGCCAGGTTGCGCACCID3921_CGAATGTCAAGGGTCACID3921_GACTACAAGAAGGCCTCID3921_ATGAGGGGTGTATGGGCID3921_GATCTAGAGAGACGAACID3921_CGACTTCAGCGCTTATCID3921_CACAGGCCAGGTCGTCCID3921_CGTCTACAGCTACCTACID3921_GTTCTCGAGATGTGGCCID3921_ATTACTCTCCGCAGTGCID3921_ACTGAGTAGACGCACACID3921_ATAAGAGTCCTTGGTCCID3921_CCGGTAGCATTCACTTCID3921_CCTAGCTTCGCCAAATCID3921_CCTATTATCGCCAGCACID

How can I do it?
Thank you!

**Comment by samuel-marsh** [comment]
Hi,

I think the easiest way to do this is multistep process.  Using pbmc3k object as example.

```
# Identify cells meeting criteria to subset (expression level plus identity)
fos_high <- WhichCells(object = pbmc, expression = FOS > 3, idents = c("B", "NK"))

# Identify cells in all clusters except selected clusters (all cells not in chosen clusters)
other_clusters <- WhichCells(object = pbmc, idents = c("B", "NK"), invert = T)

# Combine cells
subset_cells <- c(fos_high, other_clusters)

# subset object 
pbmc_sub <- subset(x = pbmc, cells = subset_cells)
```

Best,
Sam

**Comment by JessicaP94** [comment]
Thank you Sam!
Should I then recluster after subsetting?
The UMAP plots look different although they have the correct number of cells after the subsetting.
Thank you! 

> Hi,
> 
> I think the easiest way to do this is multistep process. Using pbmc3k object as example.
> 
> ```
> # Identify cells meeting criteria to subset (expression level plus identity)
> fos_high <- WhichCells(object = pbmc, expression = FOS > 3, idents = c("B", "NK"))
> 
> # Identify cells in all clusters except selected clusters (all cells not in chosen clusters)
> other_clusters <- WhichCells(object = pbmc, idents = c("B", "NK"), invert = T)
> 
> # Combine cells
> subset_cells <- c(fos_high, other_clusters)
> 
> # subset object 
> pbmc_sub <- subset(x = pbmc, cells = subset_cells)
> ```
> 
> Best, Sam

**Comment by torkencz** [comment]
Hi, you can re-scale and then redo the clustering after subsetting.

**Comment by samuel-marsh** [comment]
In additon to what @torkencz mentioned I would also re-run finding the variable features.  Removing cells (depending on thei expression and how many) alter the highly variable features and therefore all of the steps downstream (scale, pca, clustering, etc).

Best,
Sam

**Comment by JessicaP94** [comment]
> Hi, you can re-scale and then redo the clustering after subsetting.

Thank you!

**Comment by JessicaP94** [comment]
> In additon to what @torkencz mentioned I would also re-run finding the variable features. Removing cells (depending on thei expression and how many) alter the highly variable features and therefore all of the steps downstream (scale, pca, clustering, etc).
> 
> Best, Sam

Thank you Sam!
