### ISSUE TITLE
How to interpret and perform DEG using the de novo UMAP of merged object?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6436]
Follow up on issue #6228, @longmanz informed that "by generating the de novo UMAP after merging 2 datasets, we are able to look for cell clusters that are not shared by the 2 datasets." 

**Question 1.** If I see there are some query cells that are "close to" some ref cells, can I interpret it as these query cells "co-cluster" with these ref cells, even though these query cells are not present in the reference data? Or, do I need to actually perform merged analysis (from normalization, FindClusters, ...) to investigate that?

**Question 2.** As asked in the open issue #6351, From #6173, de novo UMAP is the UMAP generated from query batch-corrected cell embeddings, and not the expression values. 

If I want to now perform DEG for these unique/shared cells (as detected visually in the de novo UMAP), do I need to run the entire pipeline starting from `SCTransform()` the 2 individual objs then remerge? 

Or, can I directly do `PrepSCTFindMarkers()` to adjust for the sequencing depth of the query and ref datasets per #6325, then `FindMarkers()`? 

Thank you so much!

**Comment by longmanz** [comment]
Hi @denvercal1234GitHub,
Re 1). After you integrate the 2 datasets and run the de novo UMAP, you can run FindNeighbors() and FindClusters() to perform clustering analysis for your integrated dataset (as in https://satijalab.org/seurat/articles/integration_introduction.html). Then you can look into the cluster identity of these "co-cluster" cells.

Re 2). There are 2 ways to run DE analysis for your integrated dataset:
         a. you can directly do FindMarkers() by using the "RNA" assay of the integrated dataset (but batch effect is not corrected); you should NOT run FindMarkers() using the "integrated" assay.  
         b. You will need to re-run the entire SCTransform pipeline (as in https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), then PrepSCTFindMarkers() and FindMarkers().
