### ISSUE TITLE
Method to filter CCA vectors by minimum bicor cutoff in AlignSubspace()

### ISSUE THREAD

**Issue by yueqiw** [satijalab/seurat#644]
In the Mayer(@mayer-lab) et al, 2018 paper "[Developmental diversification of cortical inhibitory interneurons](https://www.nature.com/articles/nature25999)", The CCA alignment process has an extra step to filter CCV based on a minimum bicor cutoff: 
> For downstream analysis (t-distributed stochastic neighbour embedding (t-SNE) and subtype mapping), we selected CCV for which at least 30 genes exhibited a minimum bicor of 0.15 in both datasets, applying the same cutoff across all three analyses.

This does not seem to be implemented in the `AlignSubspace` function in Seurat (only in @mayer-lab 's version: [1_integrated_analysis.R](https://github.com/mayer-lab/Mayer-et-al-2018_IntegratedAnalysis/blob/master/R/1_integrated_analysis.R) and [dimensional_reduction.R](https://github.com/mayer-lab/SeuratForMayer2018/blob/f0f045a34e5d59b8a42b9c58a68c7e9ec7d9f678/R/dimensional_reduction.R)). 

Looking at the analysis pipeline, this seems to be a critical step for the downstream cell type assignment (many CC vectors are filtered out by this step, especially for younger mouse brain samples). I guess the results in the paper would be slightly different without using the cutoff for selecting CCV. But I haven't found a way to do this kind of filtering in Seurat. 

Is there a way to filter CCV by minimum bicor in Seurat without having to install the Mayer-lab version? Thanks!

**Comment by satijalab** [comment]
This is the statistic we use in MetageneBicorPlot, which is implemented in the package.
