### ISSUE TITLE
SCTransform(return.only.var=F) still does not return all features in scale.data slot.

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6443]
Hi there, 

After setting `SCTransform()` to return not only variable features while running it on individual objects before merging them (then `SelectIntegrationFeatures()` to set variable genes) as advised in #5759 #4240, there were still genes that did not get populated in scale.data slot for SCT Assay. I also checked these genes passed the `min.cells` threshold of `SCTransform()`. 

When I tried to `GetResidual()` for these features, it says **_"This SCTAssay contains multiple SCT models. Computing residuals for cells using different models. Warning: Residuals not computed for the following requested features: ..."_**

Would you mind advising on how to proceed? I was thinking of performing ScaleData(assay=RNA) on this merged object but since SCTransform() was done on individual object before merging, is it appropriate to do ScaleData() on the merged? 

Thank you for your help! 

```
GetResidual(obj, features=c(....), assay="SCT")
```

**Comment by saketkc** [comment]
I would advise populating the `scale.data` slot for individual objects before merging, using the `GetResiduals` function on each SCT object separately.
