### ISSUE TITLE
find genes with expression in cluster A higher by a given FC than any other cluster 

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#6444]
Hi,
I was wandering if it was possible to add a feature to find genes with an expression in cluster A , let's say 2 times higher than any other cluster among B,C and D, instead of grouping all the cells outside of cluster A which could dilute the expression of the genes.
Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can get list of genes like this fairly easily by running loop/*apply functions across clusters of interest (see below).

One caveat to keep in mind as always though with cluster vs. cluster DE is that the p values are dramatically overinflated and therefore using them as statistical cutoff is problematic.  In this example I set p value at p < 0.01 but that is fairly arbitrary.  Again it will depend what you are using data for in downstream analysis but just something to be aware of.

```
library(tidyverse)
library(Seurat)

# Load object
pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

# make variable with clusters of interest
clusters <- c("CD14+ Mono", "FCGR3A+ Mono", "DC")

# Run FindMarkers using lapply: create dataframes then filter on adj. pval then pull vector of genes from filtered dataframe.
     # Setting logfc threshold to 1 (2 fold change) and only.pos = T to only look at upreg genes.
     # In this case we are looking at comparison of CD8 T cells vs several other clusters (chose myeloid based clusters so that some of output genes would be shared for this example).

multi_marker <- lapply(clusters, function(x){
  markers <- FindMarkers(object = pbmc, ident.1 = "CD8 T", ident.2 = x, logfc.threshold = 1, only.pos = T)
  markers <- markers %>% 
    filter(p_val_adj < 0.01) %>% 
    rownames_to_column("genes") %>% 
    pull(genes)
})

# Pull out genes that intersect between all of the outputs
overlap_genes <- reduce(multi_marker, function(x, y){
  intersect(x = x, y = y)
})

> overlap
 [1] "CCL5"    "IL32"    "NKG7"    "PTPRCAP" "CD3D"    "CST7"    "GZMA"    "MALAT1"  "CTSW"    "RPS27A" 
[11] "HLA-A"   "CD3E"    "GZMK"    "GZMM"    "LCK"     "RARRES3"

```

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @kaizen89,

did this solution work for you?  If so let me know and I can go ahead and close the issue.

Thanks!
Sam

**Comment by kaizen89** [comment]
Hi @samuel-marsh, yes your solution does the job. Thanks a lot. Though, I think it could be improved if using `presto` implementation of `FindAllmarkers` and using only the average expression per cluster and then computing the FC of cluster with highest expression of the marker over the 2nd highest expressing cluster. Closing for now. Thanks again!
