### ISSUE TITLE
comparison of gene sets

### ISSUE THREAD

**Issue by Elham-adabi** [satijalab/seurat#6445]
Dear Seurat team, 

I am trying to plot the average expression of gene sets and calculate the ±SEM of all of them. for example, I want to check the average expression of all apoptosis-related genes and compare it between my groups. I found something similar in a publication:

![Picture2](https://user-images.githubusercontent.com/102491571/191214673-0c514909-da22-4db6-b99b-32199b87fe91.jpg)
**Comparison of apoptosis correlative gene sets between HD, CR, and NR group. Literature-based gene sets were listed at left side. Scatter plot with bar shows mean±SEM. Symbols represent average expression value of each gene across all single cells.**

if I get it correct they calculate the average expression of each gene across all single cells and then include them all in one bar with SEM.

For my analysis, I can calculate the average expression of my gene sets as:
ApopAvexp <- AverageExpression(
 cart.combined,
  assays = "RNA",
  features = c("BIRC3", "BCL2A1", "APOE", "BCL2",  "IER3"),
  return.seurat = TRUE,
  group.by = "ident",
  add.ident = NULL,
  verbose = TRUE
)
 But I can't make that graph with my gene set in one bar and compare it among different conditions.
I would appreciate it if you can help me with this.

Best, 
Elham

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  First, in terms of statistics and comparing differentially expressed genes you shouldn't use just tradtional t-test or ANOVA etc.  It is best to use a statistic test designed for differential gene expression analysis, especially one that allows for passing more complex models to account for other sources of variance in the data (batch, sex, treatment, etc).

Second, I would recommend consider something potentially like a module score (either using `AddModuleScore` or could check out UCell package as there can be some issues with `AddModuleScore` depending on dataset composition).

Best,
Sam

**Comment by Elham-adabi** [comment]
Dear @samuel-marsh , 

Thanks a lot for your help, I tried the AddModuleScore and I think it is working?
> Apoptosis <- list(c( "BIRC3", "BCL2A1", "APOE", "BCL2",  "IER3"))
> # change the features based on the above gene sets name
> cart.combined <- AddModuleScore(object = cart.combined, features = Apoptosis, assay = "RNA", name = "Apoptosis", ctrl = 5 )
> # the name will be added to metadata columns, with 1. e.g name x will be x1
> names(x = cart.combined[[]])
 [1] "orig.ident"             "nCount_RNA"             "nFeature_RNA"           "donor"                 
 [5] "cartridge"              "sample"                 "id"                     "nCount_ABSEQ"          
 [9] "nFeature_ABSEQ"         "integrated_snn_res.0.5" "seurat_clusters"        "integrated.weight"     
[13] "ABSEQ.weight"           "wsnn_res.0.3"           "Cell_type"              "CARrna"                
[17] "CARp"                   "VSV"                    "His"                    "CD8p"                  
[21] "CD4p"                   "mix"                    "mix1"                   "mix2"                  
[25] "Apoptosis1"            
> DefaultAssay(cart.combined) <- "RNA"
> Idents(cart.combined) <- "donor"
> VlnPlot(object = cart.combined, features = "Apoptosis1", pt.size = 0, y.max = 4)  + geom_boxplot( width=0.25, fill="white")+
stat_compare_means(label = "p.signif", comparisons = list(c("D1", "D2")))

![image](https://user-images.githubusercontent.com/102491571/191590997-32aff66b-b7cf-4b1b-a122-7475ebab0bd3.png)

So now I have the comparison of the donors based on all my apoptotic gene set score?
Regarding the statistics, I don't aim for t-test and ANOVA and if I am correct the default is Kruskal Wallis, 
Is this what you mean?

**Comment by torkencz** [comment]
Hi, I think the Module Score should work best for you. I recommend a KW test, yes.
