### ISSUE TITLE
Using FindMarkers to find cell type specific differentially expressed genes?

### ISSUE THREAD

**Issue by mckennareale** [satijalab/seurat#6447]
Hello,

I'm working on finding differentially expressed genes across a control and treatment group. So far, I've followed this vignette: https://satijalab.org/seurat/archive/v3.0/immune_alignment.html

In the "Identify differential expressed genes across conditions" subsection, the vignette describes how "CD14 and CXCL10 are genes that show a cell type specific interferon response." This list of differentially expressed genes was found by running:

`b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL", verbose = FALSE)
head(b.interferon.response, n = 15)`

From the way the vignette words this, it seems that it's coincidental that CD14 and CXCL10, which are differentially expressed between "B_STIM" and "B_CTRL" are somewhat specific to B cells since this code also output some markers that were interferon response genes (not specific to just B cells and monocytes).

Is there a way to run FindMarkers with, for example, "B_STIM" and "B_CTRL" as the identities being compared but that selects for markers that are only upregulated upon stimulation in B cells and not in all other cell types? In other words, is there a way to change the input of FindMarkers to filter out genes that are just interferon response genes and not those that are specifically upregulated in B cells after interferon treatment?

**Comment by mayurdoke6** [comment]
Hello @mckennareale ,

I am not from the Satija group but I will try to give answers to your question. Please let me know if I do not understand correctly. But, I think you can run interferon response genes upon stimulation in all other cell types by simply using other cell type names instead of b cells in the STIM group compared to the CTRL group. For example- In the case of CD14 Mono -cell type 
CD14 Mono.interferon.response <- FindMarkers(immune.combined, ident.1 = "CD14 Mono_STIM", ident.2 = "CD14 Mono_CTRL", verbose = FALSE) head(CD14 Mono.interferon.response, n = 15)

You can also check out the following link- and check out  code under-**Identify differential expressed genes across conditions**
https://satijalab.org/seurat/articles/sctransform_v2_vignette.html

I hope this helps.

**Comment by mckennareale** [comment]
Hi @mayurdoke6 ,

Thank you so much for your response!

I've followed the vignette Seurat published that includes adding the column with the cell type and condition information together (for example, "CD14 Mono_STIM" and "CD 14 Mono_CTRL") and compared these two identities within the same cell type to see differential expression in the treatment condition compared to control. However, I'm looking to not only compare treatment and control within the same cell type but also find which differentially expressed genes are specific to that one cell type. For example, I'm interested in the genes that are upregulated upon interferon treatment only in CD14+ monocytes but not genes that are upregulated in multiple cell types in response to interferon treatment.

Is there a way to filter out the results from FindMarkers comparing, for example CD14 Mono_STIM and CD14 Mono_CTRL, so the results are only genes upregulated specifically in CD14 monocytes?

Thank you so much!

**Comment by mayurdoke6** [comment]
You can create  a column in your metadata as a "ctrl' and another one as an " interferon treatment". run differential expression with   ident.1 = "ctrl', ident.2 =" interferon treatment". verbose = FALSE) head(interferon.response, n = 15)

**Comment by torkencz** [comment]
From what I am reading you want to get cell type specific signal and remove the signal that is common across treatments in multiple cell types. I would do your normal DE and the remove the significant results from running FindConservedMarkers with cell types given as the shared condition. Alternatively, you could do FindALLMarkers on all of your CTRLs and then use the genes that are unique to each of the cell types to filter further the results that you get from you 1-on-1 cell type comparisons.
