### ISSUE TITLE
Questions regarding PAGA ANALYSIS

### ISSUE THREAD

**Issue by mayurdoke6** [satijalab/seurat#6449]
Hello,
Thank you so much for creating this tool. I have some specific questions regarding the arrows which shows directionality of cells that are in transition state and move from one cluster to another.

I have analyzed the scRNAseq data using seurat. Then used the Metadata information to run scvelo and velocyto to analyze the RNA velocity of each cluster. Then used PAGA which gave us the directions. When We used combined umap of control and treated samples to analyze the RNA velocity, we got right direction of transition of cells state by using PAGA. However, when we combined two control samples groups to run PAGA, it gave us weird results such as the cells (endothelial and macrophages in pancreas) which are not even originally related to cells such as acinar cells showed arrows towards to the cluster (acinar in pancreas). This created questions on the validity of these arrows which do not have biological significance. Could you please give us the explanation regarding this. We would really appreciate your help. Your answer will definitely clear our doubts. Please find attached picture.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This seems to be question about the analysis and results from PAGA and not Seurat.  I would recommend posting to their repository to better understand the issues.

Best,
Sam
