### ISSUE TITLE
avg_logFC

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#645]
Dear all,

how is avg_logFC computed exactly?I already checked the code:
https://github.com/satijalab/seurat/blob/master/R/differential_expression.R

But results differ when I do this manually. Are only non-zero entries used in the calculation?

Thanks, best, Chris

**Comment by paolo-kunderfranco** [comment]
Yes, i think only non zero counts are considered

**Comment by satijalab** [comment]
0 counts are also considered- but we do add a pseudocount to guard against zero values (this is also a user-defined parameter if you wish to remove this). The code above shows our exact procedure.

**Comment by balthasar0810** [comment]
Thanks. Maybe you forgot to paste the "code above" you mentioned? Chris

----------
Dr. med Dipl.-Math. Christian Hinze

AG Schmidt-Ott
Max-Delbrück-Centrum
für Molekulare Medizin (MDC) Berlin-Buch
Robert-Rössle-Str. 10
13125 Berlin
Tel.: +49 30 9406 3240
christian.hinze@mdc-berlin.de

Medizinische Klinik mit Schwerpunkt Nephrologie
Charité - Universitätsmedizin Berlin
Campus Benjamin Franklin
Hindenburgdamm 30
12203 Berlin
Tel. +49 30 8445 2441
christian.hinze@charite.de<mailto:kai.schmidt-ott@charite.de>
________________________________
Von: satijalab [notifications@github.com]
Gesendet: Freitag, 27. Juli 2018 01:21
An: satijalab/seurat
Cc: balthasar0810; Author
Betreff: [ext] Re: [satijalab/seurat] avg_logFC (#645)


0 counts are also considered- but we do add a pseudocount to guard against zero values (this is also a user-defined parameter if you wish to remove this). The code above shows our exact procedure.
