### ISSUE TITLE
Error when running FindTransferAnchors()

### ISSUE THREAD

**Issue by sherry1000001** [satijalab/seurat#6452]
I meet the error below when running FindTransferAnchors().

here is my code 
```r
anchors <- FindTransferAnchors(reference = cancer, query = rudin, l2.norm = FALSE,dims = 30, reference.reduction = "pca") #30`
```

Projecting cell embeddings
Warning: No columnames present in cell embeddings, setting to 'ProjectPC_1:1'
Error: All cells in the object being added must match the cells in this object
In addition: Warning messages:
1: In rbind(orig.embeddings, projected.pca) :
  number of columns of result is not a multiple of vector length (arg 1)
2: In Cells(x = value) == Cells(x = x) :
  longer object length is not a multiple of shorter object length

> #-------------------------------------------------------------------
> R version 4.2.1 (2022-06-23 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19043)
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> other attached packages:
> [1] ggplot2_3.3.6      limma_3.52.2       sp_1.5-0           SeuratObject_4.1.2
> [5] Seurat_4.2.0

**Comment by linderss** [comment]
I had the same issue, updating the packages and restart R solved it.
