### ISSUE TITLE
Cannot run "loadData() function after saving RDS file and reading RDS file using "saveRDS" & "readRDS" (rstudio, Seurat)

### ISSUE THREAD

**Issue by akira5555** [satijalab/seurat#6453]
# what I want to perform, purpose
I want to load multiple sample data(pbmc16 and pbmc45), and integrate by following the tutorial "below
＃Performing integration on datasets normalized with SCTransform
https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1

# what I did
#1. I performed the pre-processing step (filtering) and SCtransform in each sample, and then save each data with the code 
saveRDS(pbmc16, file = "../output/pbmc16_Seurat_Guided_Clustering_Tutorial.rds")
saveRDS(pbmc45, file = "../output/pbmc45_Seurat_Guided_Clustering_Tutorial.rds")

pbmc16; type S4 [20542x20700](SeuratObject:: Seurat)
assays; list [2]
meta.data; list [20700x8] (S3:data.frame)

#2. read each sample data by using "readRDS" function
pbmc16 <- readRDS("../output/pbmc16_Seurat_Guided_Clustering_Tutorial.rds")
pbmc45 <- readRDS("../output/pbmc45_Seurat_Guided_Clustering_Tutorial.rds")

#3. After that, I want to load the data as shown in the tutorial (LoadData("ifnb"))
LoadData(pbmc16)
LoadData(pbmc45)

Then I got this error
> LoadData(pbmc16)
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments

# Problem
I don't know how to load each data and integrate the multiple data.

Could you please suggest me the recommended code or advice?
Thanks in advance,

**Comment by samuel-marsh** [comment]
Hi,

`LoadData` as shown there is command specific to loading data from the SeuratData package.  Once you use `readRDS` assigned to variable the data is loaded in your R session.

Best,
Sam

**Comment by akira5555** [comment]
Thank you so much!
