### ISSUE TITLE
Scale in DoHeatmap() strange

### ISSUE THREAD

**Issue by sebozzie** [satijalab/seurat#6454]
Hello,

The scale in DoHeatmap I assume is a z-score. However sometimes the expression scale bar doesn't show a normal distribution (0 is not the center). I found an example on your site: https://satijalab.org/seurat/reference/doheatmap

![image](https://user-images.githubusercontent.com/79752884/191925488-4e4419ac-7528-4744-81a7-08ecf870b19f.png)

I would like to understand why this is the case and how one can adjust it such that the range goes from -2.5 to 2.5 and not -1 to 2.5.

Thanks!

**Comment by f6v** [comment]
Maybe this will help: https://github.com/satijalab/seurat/issues/1166

**Comment by yuhanH** [comment]
Hi, @sebozzie 
If you set `disp.min` and `disp.max` to the same value, then you will get 0 value in the middle. 
Since this heatmap shows the relative gene expression across cells in your object, `zero` doesn't have valid meaning here.
