### ISSUE TITLE
Is FindConservedMarkers too slow ? 

### ISSUE THREAD

**Issue by hemantgujar** [satijalab/seurat#6457]
Is FindConservedMarkers too sow ? is there a way to make it faster ? 

`> df <- FindConservedMarkers(Exp, ident.1 = i-1, grouping.var = "group", verbose = T)`

> Testing group CONTROL: (4) vs (0, 5, 11, 7, 9, 1, 3, 10, 13, 6, 8, 12, 15, 14, 2, 16)
>   |+++                                               | 5 % ~02h 14m 29s

**Comment by saketkc** [comment]
How many cells do you have have? You can enable multiprocessing using `future`. See [this](https://satijalab.org/seurat/articles/future_vignette.html) vignette for an example. You can also increase the default thresholds by passing `FindConservedMarkers` the same set of arguments that you would pass to `FindMarkers` [documentation](https://satijalab.org/seurat/reference/findmarkers). These include `pct.1` and `logfc.threshold`. If you are only interested in postive markers, you could also set `only.pos=TRUE`. These extra arguments will ensure the tests run on a subset of features thus making it faster.
