### ISSUE TITLE
How can I create a seurat with only barcodes.tsv and matrix.mtx files?

### ISSUE THREAD

**Issue by zhoushican** [satijalab/seurat#6461]
How can I create a seurat with only barcodes.tsv and matrix.mtx files?  data from the GSE135779.

**Comment by samuel-marsh** [comment]
Hi,

It appears the gene.tsv file is also present it just isn’t with the other two files.  Should be able to download them all and create as normal.  Let me know if you run into further issues and I’ll reopen issue.

Best,
Sam
![8AE81472-569F-43AB-B3C3-ACBE60FF8935](https://user-images.githubusercontent.com/38284410/192157046-c567dd6f-e4cf-43c3-95c8-8dfa0d1a8f6b.png)
