### ISSUE TITLE
Error/Seurat error with R/Rstudio version 4.1.1

### ISSUE THREAD

**Issue by akira5555** [satijalab/seurat#6464]
Originally, I used Seurat with "R version 4.1.1 (2021-08-10)". However, the package "glmGamPoi" [which requires R (version "4.2") ], so I uninstalled R and Rstudio, and then installed "R-4.2.1.pkg (notarized and signed)"[https://cran.r-project.org/bin/macosx/].

However, this resulted in the situation that Seurat didin't work (I didn't record the detail of the error.)

Then I decided to switch back to uninstall R v4.2.1 and then installed R version 4.1.1 (2021-08-10) again.

Unfortunately, Seurat didn't work again as shown below, although it originally worked with R v4.1.1.
--------------------------------------------------
> library(Seurat)
Warning: package ‘Seurat’ was built under R version 4.1.2Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Matrix’ 1.3-4 is being loaded, but >= 1.5.0 is required
--------------------------------------------------

I do appreciate if you advice me what I should do now to run Seurat.

--

[The code below is the R notebook when Seurat worked successfully]
R version 4.1.1 (2021-08-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] patchwork_1.1.1    ggplot2_3.3.6      sp_1.4-7           SeuratObject_4.1.0 Seurat_4.1.1      

loaded via a namespace (and not attached):
  [1] Rtsne_0.16            colorspace_2.0-3      ggsignif_0.6.3        deldir_1.0-6         
  [5] ellipsis_0.3.2        ggridges_0.5.3        rstudioapi_0.13       spatstat.data_2.2-0

**Comment by samuel-marsh** [comment]
Hi,

As the error states you need to update the version of Matrix package.  Running
`install.packages(“Matrix”)` should solve the current error.

Best,
Sam

**Comment by akira5555** [comment]
Hi Sam,

Thank you for your response.
Actually, newer version of Matrix package (Version: 1.5) existed, so I installed the Matrix (ver 1.5).
After downloading, I run library(Seurat) , then it says "package ‘Seurat’ was built under R version 4.1.2Error" as shown below.
I found out the link for R ver 4.1.2 [R-4.1.2.tar.gz](http://lib.stat.cmu.edu/R/CRAN/src/base/R-4/R-4.1.2.tar.gz), and tried to install it, but I can't install it because it may not contain installer.

Could you please let me know how to install the R ver 4.1.2, which I downloaded?

Sincerely,
AKira



> library(Matrix)
Warning message:
package ‘Matrix’ was built under R version 4.1.2 

> library(Seurat)
Warning: package ‘Seurat’ was built under R version 4.1.2Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘rlang

**Comment by samuel-marsh** [comment]
Hi,

So again this error isn’t about R version but another missing package.

“there is no package called ‘rlang”

I would recommend uninstalling Seurat and then reinstalling so that it properly installs needed dependencies.

best,
Sam

**Comment by akira5555** [comment]
Hi Sam,

Thank you for your comment. After installing R version 4.1.2, it started to work.

I do appreciate your kind support.

Sincerely,
Akira

**Comment by samuel-marsh** [comment]
glad it worked.
