### ISSUE TITLE
Is there a way to find the number of cells that is positive for a marker? 

### ISSUE THREAD

**Issue by shwetajohari** [satijalab/seurat#6466]
Hello, 

Good afternoon. 
I know there is a way to find the number of cells for each cluster. 
However, is there a way to find out how many cells are positive for example CD8+? 
Also, in integrated data, is there a way to find the number of positive cells for each treatment? 

Thank you. 

Kind Regards,
Shweta Johari

**Comment by samuel-marsh** [comment]
Hi,

You can easily check number of cells positive for marker in couple ways but easiest might be something like this (where 0 is level of expression considering something expressed; which you can obviously change if desired):
```
sum(GetAssayData(object = OBJECT, slot = "data")["GENE",]>0)
```

For number of cells in any given category column from meta data you can use:
```
table(OBJECT@meta.data$COLUMN_NAME)
```

Best,
Sam
