### ISSUE TITLE
Performing Integrated Analysis

### ISSUE THREAD

**Issue by sgolomb** [satijalab/seurat#6475]
Hello,

I am following the vignette for Introduction to scRNA-seq integration. I chose to merge my datasets then run SCTransform and then do the integration workflow ("Performing integration on datasets normalized with SCTransform"). After finishing the IntegrateData() function I ran RunPCA() and RunUMAP(). While I was looking back at the instructions closer to the top of the page under "Perform an integrated analysis", I realized that **I had not set DefaultAssay to "integrated" before running the RunPCA() and RunUMAP()** commands. Is that necessary for the performing RunPCA/RunUMAP on the SCTransformed integrated dataset? After running IntegrateData(), would "integrate" be the active assay? 

Also, if I have HTO and ADT data (CITE-seq), is it correct to perform normalization/HTOdemux after running the integration? I'm unclear on how the "integrate" assay is used in conjunction with the other assays in the object (RNA, ADT, HTO). Is the integrate assay mainly for cell clustering and then going forward to analyze gene/ADT expression, the object needs to use the RNA or ADT assays?

Appreciate any help/guidance!

Sam

**Comment by WesDe** [comment]
Hi,

Not a developer but you can check the active assay by calling your seurat_object in R. So after running IntregrateData() you can check if the "integrated" assay is active, if not run DefaultAssay(seurat_object)<-"integrated" and then run your PCA, Umap...

You are right the integrated assay is mainly for cell clustering (it only contains high variable features), so for differential gene expression you need to run on your RNA assay, perform NormalizeData and ScaleData on all genes.

Best,

**Comment by sgolomb** [comment]
Thank you, Wes! This makes sense and I re-did the UMAP with the "integrated" assay. 

And yes, I have a better understanding now on the purpose of the integration and how normalization of the RNA assay needs to occur separately for gene expression analyses.

Thanks for responding!
Sam
