### ISSUE TITLE
RunPCA maybe some little problems?

### ISSUE THREAD

**Issue by Fackie** [satijalab/seurat#648]
Im not sure if u are right about the explicition about rev.pca?
u said rev.pca default false when the input is cell*gene? but i checked ur code and i think maybe it should be gene*cell?

**Comment by satijalab** [comment]
Thanks for the feedback. We have double checked and the code is correct as is (this has independently been checked a couple times in the community as well). 

By default, the input to irlba contains cells as rows and genes as columns. If rev.pca is set to TRUE (not the default), PCA is run on the gene x cell matrix. We do not recommend this, and will likely remove this option from future versions.

Thanks for taking a close look!

**Comment by rcalandrelli** [comment]
Hello Seurat team, first of all thanks for the great job!

The issue reported here isn't still clear to me. Input matrices are usually genes in the rows and cells in the columns. The PBMC dataset that you linked in your first tutorial is exactly the same. However, you do not set rev.pca = TRUE when you run the PCA in the tutorial (according to the function documentation and your answer above, it should be set to TRUE in this case).

I have seen another issue #1087 where it is asked the same question, but it is still not answered.
Please explain this better!
