### ISSUE TITLE
Question regarding SCTransform

### ISSUE THREAD

**Issue by hemantgujar** [satijalab/seurat#6490]
Hi

I have a question.

Why do we run SCTransform on individual samples and not the dataset ?

Instead of running SCTransform on every sample and then integrating the data. Can I run SCTransform over the entire database or a group of database ? If yes. Do I need to lognormalize after that ? I want to check differential expression of genes.

Thanks
Hemant

**Comment by WesDe** [comment]
Hi,

Not a developer from Seurat but to explain it:
* you can perform SCTransform  on each sample to take care of the dataset-specific variation then proceed to integration
* you can perform SCTransform on the whole dataset if you have no such variation (i.e: sample were processed together, same library size etc., no batch effect to summarize) but this way you don't integrate your data you merge them.

You don't need to normalize your data for the clustering if you performed SCTransform part but you will have to run NormalizeData and ScaleData on the RNA assay for the differential gene expression. It is not advised to perform differential gene expression on SCT assay.
More information [there](https://github.com/satijalab/seurat/issues/6054) and [there](https://github.com/satijalab/seurat/discussions/3998)

I let Seurat developer to correct me, if I am wrong.
Best,

**Comment by saketkc** [comment]
Thanks @WesDe! Your response is helpful though it requires some clarification.

 I would like to add that you can use the SCT assay to perform differential expression but on the "data" slot as we show in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html).
