### ISSUE TITLE
Can I analyze flow cytometry data with Seurat ? 

### ISSUE THREAD

**Issue by Nidane** [satijalab/seurat#6492]
Hi team, thanks a lot for such a useful tool! 

I wonder other than conventional scRNA-seq data, whether Seurat could be used to analyze other single cell data like flow cytometry ones ? 

i.e. if I convert flow cytometry results (.fcs files) into a dataframe-ish file (.csv etc., which is also like cells x genes/markers), whether I could convert such a dataframe into a Seurat object and analyze it with Seurat ? 

Thanks.

**Comment by yuhanH** [comment]
HI Nidane
Sure. When you load the matrix into seurat, you can analyze it in the same way that you would ADT data.
https://satijalab.org/seurat/articles/multimodal_vignette.html
