### ISSUE TITLE
Gene or features expression of a single cell #6451

### ISSUE THREAD

**Issue by mayurdoke6** [satijalab/seurat#6495]
Hello,

I have a question related to #6451. I was able to get the gene expression of a single cell with a particular barcode  ID. I would like to know how to get the gene expression of 100 cells with their respective barcode ID. Do I have to run the code for every single cell? Please let me know how to get the gen expression for 100 cells in a single .csv file.

**Comment by samuel-marsh** [comment]
closed as answered in #6451
