### ISSUE TITLE
Why do we need to "+1" following GetAssayData() and as.matrix()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6496]
Hi there, 

In the Help page of `GetAssayData()`, there is an example of pulling the count data for an object as below. Why do we need to do `count.data + 1` to convert it into a count matrix?

Thank you.

```
# Set an Assay slot directly
count.data <- GetAssayData(pbmc_small[["RNA"]], slot = "counts")
count.data <- as.matrix(x = count.data + 1)
new.assay <- SetAssayData(pbmc_small[["RNA"]], slot = "counts", new.data = count.data)

```

**Comment by timoast** [comment]
This is simply an example to show how you can use the SetAssayData function to assign a different matrix to the dataset, it's not intended as a demonstration of how to analyze single-cell data
