### ISSUE TITLE
FindIntegrationAnchors is too slow

### ISSUE THREAD

**Issue by hemantgujar** [satijalab/seurat#6497]
Hi 

I have a question. Is FindIntegrationAnchors too slow. 
I have 300,000 cells. 

and I am using nfeatures = 3000

Thanks

**Comment by WesDe** [comment]
Hi,

To speed up the process you can rely on parallelization with future package as described [there](https://satijalab.org/seurat/articles/future_vignette.html).

Best,

**Comment by samuel-marsh** [comment]
Hi,

You can also check out vignettes here on tips for working with large datasets:
https://satijalab.org/seurat/articles/integration_large_datasets.html

As well as vignette on Atomic Sketch Integration for large datasets:
https://satijalab.org/seurat/articles/atomic_integration.html

Best,
Sam
