### ISSUE TITLE
Issues with spaceranger output filenames when using Load10X_Spatial()

### ISSUE THREAD

**Issue by evchambers** [satijalab/seurat#6498]
Hi, I am trying to read in some example spaceranger output into the Seurat spacial transcriptomics pipeline. When using Load10X_Spatial() I get errors about the filenames of the spatial data.

I think this may be due to spaceranger renaming the output file tissue_positions_list.csv into tissue_positions.csv in outs/spatial. When I rename the file the error disappears.

 This is using the spaceranger output directory 'outs' as the input

```{r}
brain <- Load10X_Spatial(data.dir ="outs/",filename = "filtered_feature_bc_matrix.h5"  )
```

```
Warning: cannot open file 'outs//spatial/tissue_positions_list.csv': No such file or directoryError in file(file, "rt") : cannot open the connection
```

R version 4.2.1 
Seurat_4.1.1
spaceranger-2.0.0

**Comment by evchambers** [comment]
Ah super! Thanks

**Comment by samuel-marsh** [comment]
No problem!
