### ISSUE TITLE
AddSamples doesn't automatically generate data.info for new data

### ISSUE THREAD

**Issue by b-dawes** [satijalab/seurat#65]
When combining data using the AddSamples method without providing meta.data, the new data will have NA for every column in data.info. Would it be possible to change it to set the fields automatically generated by the Setup function such as nGene and nUMI?

I looked a bit at the source for AddSamples, and it looks like Setup is called for the combined data and then the data.info field is overwritten with the old meta data. Maybe this could be fixed by merging in the automatically generated fields with the old meta data?

**Comment by satijalab** [comment]
Thanks for the catch, we'll check it out and fix

**Comment by andrewwbutler** [comment]
AddSamples now sets nGene and nUMI properly in v2.0
