### ISSUE TITLE
Integrated Seurat Object isnt converting to Monocle 3 object. 

### ISSUE THREAD

**Issue by shwetajohari** [satijalab/seurat#6500]
Hello,

I am receiving the follow error:
cds <- as.cell_data_set(b.seu)
Warning: Monocle 3 trajectories require cluster partitions, which Seurat does not calculate. Please run 'cluster_cells' on your cell_data_set object.

library(Seurat)
library(patchwork)
library(SeuratWrappers)
library(ggplot2)
library(tidyverse)

control = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu1_099")
inhibitor = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu2_099")
dnavaccine = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu3_099")
combitr = Read10X("C:/Users/TVIT1/Desktop/imtegrationsdj_Tuall/Tu4_099")

Created the Seurat Object:
control_seurat = CreateSeuratObject(counts = control$Gene Expression,
project = "control")
inhibitor_seurat = CreateSeuratObject(counts = inhibitor$Gene
Expression, project = "inhibitor")
dnavaccine_seurat = CreateSeuratObject(counts = dnavaccine$Gene
Expression, project = "dnavaccine")
combitr_seurat = CreateSeuratObject(counts = combitr$Gene Expression,
project = "combitr")

Merged the datasets
merge_seurat = merge(x = control_seurat, y = c(inhibitor_seurat,
dnavaccine_seurat, combitr_seurat), [add.cell.id](http://add.cell.id/) = c("control",
"inhibitor","dnavaccine", "combitr"))
head([merge_seurat@meta.data](mailto:merge_seurat@meta.data),5)

Filtering the mitochondrial genes
merge_seurat$mitoRatio <- PercentageFeatureSet(object = merge_seurat,
pattern = "^mt-")
metadata <- [merge_seurat@meta.data](mailto:merge_seurat@meta.data)
metadata$cells <- rownames(metadata)
library(dplyr)
metadata <- metadata %>%
dplyr::rename(group = orig.ident,
nUMI = nCount_RNA,
nGene = nFeature_RNA)
library(stringr)
metadata$sample <- NA
metadata$sample[which(str_detect(metadata$cells, "^control_"))] <- "control"
metadata$sample[which(str_detect(metadata$cells, "^inhibitor_"))] <- "inhibitor"
metadata$sample[which(str_detect(metadata$cells, "^dnavaccine_"))] <-
"dnavaccine"
metadata$sample[which(str_detect(metadata$cells, "^combitr_"))] <- "combitr"
[merge_seurat@meta.data](mailto:merge_seurat@meta.data) <- metadata
head([merge_seurat@meta.data](mailto:merge_seurat@meta.data),5)
tail([merge_seurat@meta.data](mailto:merge_seurat@meta.data),5)
data.list <- SplitObject(merge_seurat, [split.by](http://split.by/) = "sample")

data.list <- lapply(X = data.list, FUN = function(x) {
x <- NormalizeData(x)
x <- FindVariableFeatures(x, selection.method = "vst")
})

Integration of datasets
features <- SelectIntegrationFeatures(object.list = data.list)
immune.anchors <- FindIntegrationAnchors(object.list = data.list,
anchor.features = features)
immune.combined <- IntegrateData(anchorset = immune.anchors)
DefaultAssay(immune.combined) <- "integrated"
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:10)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca",
dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)
p1 <- DimPlot(immune.combined, reduction = "umap", [group.by](http://group.by/) = "sample")
p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE, repel = TRUE)
DimPlot(immune.combined, reduction = "umap", [split.by](http://split.by/) = "sample")

DefaultAssay(immune.combined) <- "RNA"
library(metap)
all.markers084 <- FindAllMarkers(immune.combined, only.pos = TRUE,
min.pct = 0.25, logfc.threshold = 0.25)

b.seu <- WhichCells(immune.combined, idents= c("B", "CD21+ B", "Immature B", "Tuft", "Inflammatory mono", "Goblet cell"))
b.seu = subset(immune.combined, cells = b.seu)

pre-processing using seurat
b.seu <- NormalizeData(b.seu)
b.seu <- FindVariableFeatures(b.seu)
b.seu <- ScaleData(b.seu)
b.seu <- RunPCA(b.seu)
b.seu <- FindNeighbors(b.seu, dims = 1:30)
b.seu <- FindClusters(b.seu, resolution = 0.9)
b.seu <- RunUMAP(b.seu, dims = 1:30, n.neighbors = 50)

a1 <- DimPlot(b.seu, reduction = 'umap', group.by = 'seurat_clusters', label = T)

MONOCLE3 WORKFLOW ---------------------
monocle3 requires cell_data_set object
convert seurat object to cell_data_set object for monocle3
...1 Convert to cell_data_set object ------------------------
cds <- as.cell_data_set(b.seu)
Warning: Monocle 3 trajectories require cluster partitions, which Seurat does not calculate. Please run 'cluster_cells' on your cell_data_set object.

**Comment by samuel-marsh** [comment]
Hi,

The message you posted simply appears to be a warning not an error.  Is the cds object not being created in your environment?

What is result of `class(cds)`?

Best,
Sam

**Comment by shwetajohari** [comment]
Hello Sam,

Thanks for your reply.

I went on reading for this: https://github.com/satijalab/seurat/issues/1658
But again, received an error at the end step.

> recreate.partition <- c(rep(1, length(cds@colData@rownames)))
> names(recreate.partition) <- cds@colData@rownames
> recreate.partition <- as.factor(recreate.partition)
> cds@clusters@listData[["UMAP"]][["partitions"]] <- recreate.partition

> list_cluster <- b.seu@meta.data[[sprintf("seurat_clusters")]]
> #list_cluster <- b.seu@meta.data[[sprintf("ClusterNames_%s_%sPC", 0.5, 20)]]
> names(list_cluster) <- b.seu@assays[["RNA"]]@data@Dimnames[[2]]

> list_cluster <- b.seu@meta.data[[sprintf("seurat_clusters")]]
> #list_cluster <- b.seu@meta.data[[sprintf("ClusterNames_%s_%sPC", 0.5, 20)]]
> names(list_cluster) <- b.seu@assays[["RNA"]]@data@Dimnames[[2]]

> cds@clusters@listData[["UMAP"]][["clusters"]] <- list_cluster
> cds@clusters@listData[["UMAP"]][["louvain_res"]] <- "NA"

> cds <- monocle3::preprocess_cds(cds, method = "PCA", norm_method = "none")
> cds <- monocle3::reduce_dimension(cds, reduction_method = "UMAP")
No preprocess_method specified, using preprocess_method = 'PCA'

> reducedDim(cds, "UMAP") <- Embeddings(b.seu, "umap")

> cds@preprocess_aux$gene_loadings <- b.seu@reductions[["pca"]]@feature.loadings
Error in cds@preprocess_aux$gene_loadings <- b.seu@reductions[["pca"]]@feature.loadings : no slot of name "preprocess_aux" for this object of class "cell_data_set"

> cds@preprocess_aux$gene_loadings <- Loadings(seu, "pca")
Error in Loadings(seu, "pca") : object 'seu' not found

> cds@preprocess_aux$gene_loadings <- Loadings(b.seu, "pca")
Error in cds@preprocess_aux$gene_loadings <- Loadings(b.seu, "pca") : no slot of name "preprocess_aux" for this object of class "cell_data_set"

Kind regards,
Shweta Johari

**Comment by timoast** [comment]
This seems to be a warning message rather than an actual error. Is the `cds` object created?

**Comment by mojaveazure** [comment]
Looking at the [class definition for `cell_data_set`](https://github.com/cole-trapnell-lab/monocle3/blob/master/R/cell_data_set.R#L28-L34), it doesn't look like there's a slot called `preprocess_aux`; it would appear that Seurat is generating the `cell_data_set` correctly, but the slot you're trying to access isn't part of `cell_data_set`

**Comment by tsofiya** [comment]
I am also getting the same error message. From what I see, the function sending this message is SingleCellExperiment::reducedDims(cds). From some reason, the product of this function has a reduction called TSNE rather then tSNE (and tSNE is the original name in the cds object). Did anyone solved this?
