### ISSUE TITLE
How to add the expressions to the Spatial Seurat object?

### ISSUE THREAD

**Issue by HosseinMousavi** [satijalab/seurat#6501]
Hi,

Thanks for providing the spatial vignette! I am trying to create a Spatial Seurat Object. I implemented the following commands and added the **counts** to the spatial object. I need to add the **expressions** to this object (I already created the expression for each spot). Your help would be deeply appreciated!

What I found from #2790 

```
slide.seq = CreateSeuratObject(counts = COUNTS_MTX, assay="Spatial")

coord.df = data.frame(x=X, y=Y, stringsAsFactors=FALSE) # (stringsAsFactors only if also have a separate barcodes column)
rownames(coord.df) = BARCODES

slide.seq@images$image =  new(
    Class = 'SlideSeq',
    assay = "Spatial",
    key = "image_",
    coordinates = coord.df
  )
```

**Comment by timoast** [comment]
Can you elaborate on what you mean by "expressions" and how this is different to counts?

**Comment by HosseinMousavi** [comment]
> Can you elaborate on what you mean by "expressions" and how this is different to counts?

Hi,
Counts store in @counts and expressions are stored in @data or @sacle.data in a Seurat object.

**Comment by samuel-marsh** [comment]
Hi,

Those slots are generated in the course of analysis during data normalization and scaling respectively.

Best,
Sam

**Comment by timoast** [comment]
Yes, these slots will be filled as you run an analysis.
