### ISSUE TITLE
error with "pip install leiden"

### ISSUE THREAD

**Issue by anndan7** [satijalab/seurat#6504]
Hi, I am trying to use the leiden alg (algorithm=4) with FindClusters in Seurat in Rstudio. When I try to run this, it gives the error: "Cannot find Leiden algorithm, please install through pip (e.g. pip install leidenalg)", even though I've done library(leiden). When I go to my terminal to try pip install leidenalg, I get the following process and I am not sure how to fix, thanks!

ANACON~1\envs\r-reticulate\Lib\site-packages>python -m pip install leiden
Collecting leiden
  Using cached leiden-1.0.2.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting nose
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
Collecting hgvs
  Using cached hgvs-1.5.2-py2.py3-none-any.whl (99 kB)
Collecting pygr
  Using cached pygr-0.8.2.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\annda\AppData\Local\Temp\pip-install-4k34nfc4\pygr_a4d9c1e205a448a5be0f47150fe1116e\setup.py", line 19
          print 'Setuptools not imported, falling back to distutils'
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This appears to be issue as you mentioned with the installation of python leidenalg package.  I would suggest posting to the repo for that package (https://github.com/vtraag/leidenalg) to help with your installation issues as it is separate from Seurat.

Best,
Sam
