### ISSUE TITLE
Predicting labels won't work while projecting the data

### ISSUE THREAD

**Issue by pouyadfd** [satijalab/seurat#6507]
I'm trying to project the annotations from sc-RNA seq data to spatial rna, I followed the steps as in https://satijalab.org/seurat/articles/spatial_vignette.html
it finds the anchors but when I try to predict the labels in query dataset(spatial data) using the reference (sc-rna seq) the prediction assay is always empty and it doesn't give any erros while running the codes. I tried relabeling the celltypes and also tried with general subtypes but the issue persists. Would you please help me out?

> predictions.assay <- TransferData(anchorset = anchors, refdata = allen_reference$celltype, prediction.assay = TRUE,
+     weight.reduction = nano[["pca"]], dims = 1:30)
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Predicting cell labels
> nano[["predictions"]] <- predictions.assay

![Screenshot from 2022-10-06 11-48-03](https://user-images.githubusercontent.com/66023193/194282404-adac516f-d304-40bc-903c-8253ed3e6772.png)

**Comment by timoast** [comment]
The prediction scores for each class are stored in the `data` slot of the returned assay, and from the screenshot above it seems like the data slot does contain values. Can you elaborate on what you mean that it is empty?

**Comment by pouyadfd** [comment]
Hi, Thanks for the answer. I retired with feeding the function with only reference and query objects and this time it worked fine. Thanks again!
