### ISSUE TITLE
Why the cell number in the 3th line of code decrease from 50000 to 20000?

### ISSUE THREAD

**Issue by wanglu2014** [satijalab/seurat#6508]
query_seur2 <- Seurat::NormalizeData(wash_obj) # Normalize the data
query_seur3 <- Seurat::FindVariableFeatures(query_seur2,nfeatures = 2000) # Determine the variable features of the dataset

query_seur4 <- Seurat::ScaleData(query_seur3)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you clarify what the issue you are having is?  Unfortunately I’m not quite sure what you are describing.

Best,
Sam

**Comment by wanglu2014** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. Can you clarify what the issue you are having is? Unfortunately I’m not quite sure what you are describing.
> 
> Best, Sam

Thank you for your timely reply. A similar problem happened to genes. https://github.com/satijalab/seurat/issues/5334  My problem is the cells were lost.

**Comment by samuel-marsh** [comment]
Hi,

At what step are cells being lost?  After which function?

Can you provide output of:
```
# step before cells are “lost”
ncol(OBJ)

# run step where issue is occurring
…

# check cells again
ncol(OBJ)
```

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi,

Are you still having issue?  If so can you provide details described in post above this?

thanks!

**Comment by timoast** [comment]
Closing this since we haven't heard back
