### ISSUE TITLE
How to plot a featureplot showing 4 genes with 4 different colors in the same featureplot

### ISSUE THREAD

**Issue by mayurdoke6** [satijalab/seurat#6509]
Hello,

I am trying to map 4 different genes on featureplot with 4 different colors. I used the following code- 

FeaturePlot(xyz features = c("ABC", "GCC", "CEL", "FYB"), cols = c("red","green","blue","yellow"),combine = TRUE, min.cutoff= 0, max.cutoff = 9, pt.size = 4,raster = FALSE)

But, it resulted in 4 different featureplot. I would like to see all four genes in the same feature plot. Is that possible? Could you please help me? Thank you in advance.

**Comment by samuel-marsh** [comment]
Hi,

Just to confirm are you trying to plot expression levels of 4 different genes on same plot or just plot the cells that YES/NO express the gene with given color?

Plotting expression level is not currently possible for more than two genes.  For two genes you can set `blend = TRUE`.  It would likely be extremely hard to tell exactly what various degrees of colors meant with 4 overlapping expression scales.

Best,
Sam

**Comment by torkencz** [comment]
Hi, currently we cannot do expression levels for multiple genes on the same feature plot. Blend would help but it also would be very difficult to visually separate for 4 different genes.
