### ISSUE TITLE
Error in while ((it <- it + 1) < limit && abs(del) > eps)

### ISSUE THREAD

**Issue by shawez** [satijalab/seurat#6515]
Hello, 

I'm using Seurat v3.1.4, on a subset of data (~250K cells) and got an error when using SCTransform for normalization with batch_var.

The code is:

_nCell <- SCTransform(seuratObject, batch_var = "Dataset", vars.to.regress = c("S.Score", "G2M.Score", "percent.mt"), verbose = TRUE)_

**warning: solve(): system is singular; attempting approx solution
Error in while ((it <- it + 1) < limit && abs(del) > eps) { :
  missing value where TRUE/FALSE needed**

However, if I run the SCTransform() on complete data (~290K cells) it doesn't raise the error:

_nCell <- SCTransform(seuratObject, batch_var = "Dataset", vars.to.regress = c("S.Score", "G2M.Score", "percent.mt"), verbose = TRUE)_

Warning: The 'show_progress' argument is deprecated as of v0.3. Use 'verbosity' instead. (in sctransform::vst)
Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 12670 by 297512 (Random) 250000
Model formula is y ~ (log_umi) : Dataset + Dataset + 0
Get Negative Binomial regression parameters per gene
Using 2000 genes, 297512 cells
  |                                                                                                                                          |   0%
warning: solve(): system is singular; attempting approx solution
  |=====================================================================                                                                     |  50%
warning: solve(): system is singular; attempting approx solution

warning: solve(): system is singular; attempting approx solution
  |========================================================================================================                                  |  75%
warning: solve(): system is singular; attempting approx solution
  |==========================================================================================================================================| 100%
There are 2 estimated thetas smaller than 1e-07 - will be set to 1e-07
Found 340 outliers - those will be ignored in fitting/regularization step

Some genes not detected in batch GSE139829 -- assuming a low mean.
Some genes not detected in batch HRA000087 -- assuming a low mean.
Some genes not detected in batch GSE131907 -- assuming a low mean.
Some genes not detected in batch GSE123902 -- assuming a low mean.
Some genes not detected in batch E_MTAB_8410 -- assuming a low mean.

Second step: Get residuals using fitted parameters for 12670 genes
  |==========================================================================================================================================| 100%
Computing corrected count matrix for 12670 genes
  |==========================================================================================================================================| 100%
Calculating gene attributes
Wall clock passed: Time difference of 13.10503 hours
Determine variable features
Set 3000 variable features
Place corrected count matrix in counts slot
Regressing out S.Score, G2M.Score, [percent.mt](http://percent.mt/), IFN_responseGeneset1, DIG1
  |==========================================================================================================================================| 100%
Centering data matrix
  |==========================================================================================================================================| 100%
Set default assay to SCT
There were 29 warnings (use warnings() to see them)

**Does it have something to do with the size of the dataset?**

Thank you so much for your help!

Best,

Shawez

**Comment by timoast** [comment]
Can you update to the latest Seurat release and see if you still have this error?

**Comment by shawez** [comment]
> Can you update to the latest Seurat release and see if you still have this error?
Hello [timoast](https://github.com/timoast),
Yes, I did but not working as batch_var is currently not supported in SCTransform() for Seurat 4.X.X
**warning: solve(): system is singular; attempting approx solution
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed**

**Comment by timoast** [comment]
Can you please clarify, did you install the latest release and still have this error?

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
