### ISSUE TITLE
How to deal with the ribosomal gene during the analysis.

### ISSUE THREAD

**Issue by Xiphord** [satijalab/seurat#6516]
Hi,
When I am analyzing my data, which is some fibroblast of disease and control group, it happen to get a cluster whose marker genes are mostly ribosomal gene. We are quite sure that these genes are not candidate markers which might be some noise. 

And my issue is how to deal with the ribosomal gene properly during the analysis. Could we get rid of all the ribosomal genes before analysis?

Thank you very much,

Xiphord

**Comment by longmanz** [comment]
Hi, 
You can get a list of Rib genes in your Seurat obj by running 
`RPS.genes <- grep(pattern = "^RPS", x = rownames(x = seurat.obj@data), value = TRUE)`

There are several ways to deal with the Rib genes if you think they are problematic. For example, 
1. You may remove these Rib genes in the original count matrix before generating the Seurat obj;
2. You may exclude them from your VariableFearure list after your FindVariableFeature() step, so as to make sure that they will not be included as variable genes when running RunPCA(), RunUMAP(), etc.;

Longda
