### ISSUE TITLE
ncol parameter on FeaturePlot

### ISSUE THREAD

**Issue by jjo12** [satijalab/seurat#6522]
Hello,

I've been trying to figure out why `ncol` parameter on `FeaturePlot()` command is not working. I've combined 6 libraries and was hoping that I can display my feature plots in 3x2 arrangement. Do I have to use another parameter besides just `ncol`?

Thank you!

J

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So as the documentation for `FeaturePlot` states `ncol` is ignored if `split.by = TRUE` which sounds like what you are doing.

One solution is the function `FeaturePlot_scCustom` from my package scCustomize.  I have enabled ability to set number of columns even when using `split.by`.  If using scCustomize please install “develop” branch.  Major update next week but dev branch contains tons of bug fixes.

Best,
Sam

**Comment by jjo12** [comment]
Perfect!

Thank you so much, as always!

J

**Comment by samuel-marsh** [comment]
Happy to help!
