### ISSUE TITLE
Combining two libraries as one object

### ISSUE THREAD

**Issue by jjo12** [satijalab/seurat#6526]
Hi All,

I have 6 libraries where its 3 conditions and n = 2 for each condition. I want to merge n = 2 and further merge the 3 conditions together so that UMAP clustering compares all of them together. I've tried to merge twice, but it seems like the `split.by` parameter splits it to n = 2.

The example UMAPs look like this. Each replicate is placed next to each other and I would like them to be combined.
![Rplot17](https://user-images.githubusercontent.com/94518140/194806661-cb4dff0d-2ee4-44fd-a4bb-234bc0b17fe7.png)

Thank you.

J

**Comment by WesDe** [comment]
Hi,

I'm not a developer from Seurat but if I correctly understood you want to merge libraries together ?
You can either merge them all together if you want to perform a merge analysis (which suppose there is no batch effect in your data) or proceed to the integration method described [there](https://satijalab.org/seurat/articles/integration_introduction.html). You can keep track of your condition and replicate by adding metadata in a seurat object : 
`Seurat_object_1[["condition"]]<-"condition 1 a"
Seurat_object_2[["condition"]]<-"condition 1 b"`

Then you can merge all you condition this way : 
`Seurat.combined <- merge(x = Seurat_object_1, y = c(Seurat_object_2,Seurat_object_3))
`
From this part you can perform a standard analysis or split you Seurat.combined by the meta.data "condition" to perform the integration method. You can then use the "condition" meta.data to display UMAP, perform differential gene expression based on condition etc.

Best,
Wes

**Comment by jjo12** [comment]
I will try this method out! Thank you.

J

**Comment by jjo12** [comment]
Hi Wes,

This method worked like a magic!

Thank you!

J

**Comment by jjo12** [comment]
Hi Wes,

**Comment by jjo12** [comment]
Hi Wes and All,

I found the answer actually! If you want to subset your Seurat object for your UMAP based on metadata, you can subset the object like this:

in `object =` argument of plotting features, `seurat_object = subset(seurat_object, metadata_category %in% "metadata")`

I've tested this on `DimPlot(` and `FeaturePlot(` and it works.

J
