### ISSUE TITLE
Integrating conditions of different sample/cell numbers

### ISSUE THREAD

**Issue by elzevr** [satijalab/seurat#6528]
Dear Seurat team,
I would like to get some advice on the best way to integrate samples from 3 different conditions: 10 healthy, 3 moderate and 3 severe. 
However, I have different sample sizes: 6000 cells in total for moderate and similarly 6000 cells in total for severe, while I have about 60 000 for the healthy. Would it be best to first downsample the healthy to 6000 before the integration step? Otherwise I am afraid that the cells from moderate and severe conditions will get "lost" in the final integrated object?

Thank you for your help!

**Comment by f6v** [comment]
I'd suggest to run the normalisation, dimensionality reduction, and clustering without any integration first to see the batch effect magnitude. Whether to use all the controls, that's on you. In general, I rarely see such unbalanced comparisons in published papers.

**Comment by mhkowalski** [comment]
Hello, 

Thanks for your question.  I'm not sure what you mean by the cells getting "lost", but I wouldn't recommend downsampling your healthy cells, as more cells are generally better for the purposes of cell annotation.

There are a variety of approaches you could use here, and it's difficult to recommend one without exploring and understanding your data and samples.  If you believe that you have similar cell types in your healthy and diseased conditions, you might use reference mapping to map your diseased datasets onto an integrated healthy reference, as in this [vignette](https://satijalab.org/seurat/articles/integration_mapping.html). Then, you could directly do differential expression comparing healthy and diseased cells within each cell type or cluster. You could also try integrating healthy and diseased samples directly, as you suggest above.
