### ISSUE TITLE
LogNormalized PBMC reference 

### ISSUE THREAD

**Issue by aybugealtay** [satijalab/seurat#6531]
Hello, 
I am working with the PBMC data and followed your "Integrating scRNA-seq and scATAC-seq data" tutorial. 

My question is  about using available PBMC reference (https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat) for cell type annotation using the scATAC-seq gene activity matrix. From what I gather reading the issues of Seurat and Signac, for FindTransferAnchors() function to work, both the reference data and the query should be normalized using the same normalization technique (https://github.com/stuart-lab/signac/issues/92). 

The PBMC reference is SCT normalized but applying SCT normalization to scATAC gene activity matrix is not recommended (https://github.com/stuart-lab/signac/issues/433). Hence, the only option for the integration is to apply logTransformation for the reference data. I followed the pages but couldn't  find any link to logNormalised PBMC reference, neither any tutorial/instructions to follow. 

Do you have any leads regarding this?

Thanks!

**Comment by AustinHartman** [comment]
Hi, you should be able to download the full dataset from CZI with the raw counts here which you can log normalize [https://cellxgene.cziscience.com/collections/b0cf0afa-ec40-4d65-b570-ed4ceacc6813](https://cellxgene.cziscience.com/collections/b0cf0afa-ec40-4d65-b570-ed4ceacc6813)

**Comment by aybugealtay** [comment]
Thank you very much!
