### ISSUE TITLE
Problem when running harmony

### ISSUE THREAD

**Issue by chrismahony** [satijalab/seurat#6533]
I am running this:

obj<- RunHarmony(
  obj,
  group.by.vars = c("sample"),
  reduction = "pca",
  max.iter.harmony = 30,
  dims.use = 1:20,
  project.dim = T,
  plot_convergence = T,
  assay.use="RNA"
)

but I get the following error:

Harmony converged after 7 iterations
Error in UseMethod(generic = "Key", object = object) : 
  no applicable method for 'Key' applied to an object of class "character"

This is the same is true if I just run:

obj<- RunHarmony(obj,  group.by.vars ="sample")

Any help would be great thanks
Chris

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I would suggest posting this to the Harmony repo.  `RunHarmony` is part of their package so they are best to help troubleshoot running that function.

Best,
Sam
