### ISSUE TITLE
Practical difference between NormalizeData and SCTransform

### ISSUE THREAD

**Issue by trickovicmatija** [satijalab/seurat#6535]
Hello,

Very nice tool!
I want to integrate scRNA-Seq data into spatial transcriptomics data (both done entirely in Seurat).
Following the tutorial for scRNA-Seq (with NormalizeData and ScaleData), clustering and running UMAP and subsequent visualization yields expected clusters of cells. I annotated the clusters, saved them to metadata, and saved the entire Seurat object as an RDS file.

On the other hand, I use SCTransform for ST data (I am aware of and understand the differences and logic behind both). After processing (again following your tutorial), I am at the step where I want to integrate those two technologies. I see that you normalize scRNA-Seq data again but now use SCTransform and rerun PCA and UMAP. If I follow that and visualize the results with UMAP, the result is different compared to NormalizeData done before. It is so different that previously defined clusters that were apart are merged, and one previous cluster is broken into many smaller ones scattered throughout the plot.

If I continue with the integration, it technically works, but I am unsure if I can trust the results.
Is it expected that the results of those normalizations are so different? If so, why are you sticking to NormalizeData in scRNA-Seq but moving to SCTransform afterward for the same data? Is it necessary to use SCTransform data for integration?

Thank you very much for your help,
Matija

**Comment by f6v** [comment]
I don't think that the results should be extremely different. It'd be easier if you show some of the code and the plots.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So how different and if they are different is going to rely heavy dataset to dataset based on strengths and limitations of each technique (recommend reading scTransform v1 and v2 papers for more).  I also would say I’d expect them to be not that different without knowing more about specific datasets and parameters used in code.  

As to which you should use, that is up to you.  Trying both and multiple parameters of both is critical.  It’s then up to you to evaluate the results and see which one makes most sense.  There is no one size fits all in scRNAseq analyses and evaluation of multiple parameter settings and techniques is critical part of any analysis.


Best,
Sam
