### ISSUE TITLE
Error during heatmap some features were omitted as not found in scale data for the RNA assay.

### ISSUE THREAD

**Issue by Amin2130538** [satijalab/seurat#6542]
I use this code to run the heatmap after integration, and clustering. 

Seurat::DoHeatmap(combined_seurat, features = unique(top5$gene)) +
  ggplot2::theme(axis.text.y = ggplot2::element_text(size = 10))

**But I received a warning message:** 
**In Seurat::DoHeatmap(combined_seurat, features = unique(top5$gene)) :
  The following features were omitted as they were not found in the scale.data slot for the RNA assay: Tns1, Col4a2, Hspg2, Eln, Acta2, Tagln, Myl9, Tpm1, Tmsb4x**

Here I used "DefaultAssay(combined_seurat) <- "RNA" " and got this error or warning message and these genes are not shown in the heatmap, but when I use "DefaultAssay(combined_seurat) <- "integrated" " there is no error.

So why are these genes omitted during the heatmap and why not found in scale data for RNA assay? So, How to I can solve this problem? Your kind suggestions will be highly appreciated. Thank you...

**Comment by f6v** [comment]
It depends on how the data is scaled. But most likely the scaling in your code is done only on the HVG features. But the DE is run on all the genes. So a gene in your data can be DE, but not a HVG, so there's no scale data for this gene.

**Comment by samuel-marsh** [comment]
Hi,

@f6v is correct.  The default when running `ScaleData` is that only the variable features will be scaled.  To scale all features all you need to do is set assay to “RNA” and run:
`Obj <- ScaleData(Obj, features = rownames(Obj))`

Best,
Sam

**Comment by Amin2130538** [comment]
Hello members,

Thank you very much for your kind comments and suggested code. It works perfectly. 

Best
Amin
