### ISSUE TITLE
Seurat does not compile on Windows

### ISSUE THREAD

**Issue by bastian-wur** [satijalab/seurat#6545]
Dear all,

I have some problem, and it seems it's something technical which I cannot fix.
Description is easy: I try to install Seurat on Windows 10, and it does not work, no specific error.

R version: 4.2.1
RStudio version: RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Windows version: 10

What did I do:
1) install.packages("Seurat"):
- Installs, but crashes after loading the library. Installation happens within a second, which is way too short, I guess. I have to delete the local appdata folder for R to not make RStudio crash on a new startup.
2) install.packages("Seurat", type = "source"):
Would seem to install, no error message, but gets a non-0 exit code.
End of the output of the console (a lot of stuff compiles beforehand without issues:
```
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package 'Seurat'
* removing 'D:/R-library/R-4.1.1/Seurat'
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status
```
3) install_github("satijalab/seurat"):
Compiles a lot too, but doesn't install either.
End of console output is:
```
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package 'Seurat'
* removing 'D:/R-library/R-4.1.1/Seurat'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/089998/AppData/Local/Temp/RtmpOGLrBv/file244358e7a55/Seurat_4.2.0.tar.gz’ had non-zero exit status
```

So... I don't think it's an issue on my side. Is there something wrong with the Windows package?
I also just (a few days ago) installed it on a Linux VM in our cluster, and that one seems to work.
Any advice?

Best regards,
Bastian

EDIT: Please disregard that the custom library folder says R 4.1.1, I have only 4.2.1 installed, and the folder itself is from an older version, but should not conflict with anything.
EDIT2: Yes, I have also seen this one https://github.com/satijalab/seurat/issues/40 , and all the other stuff installs fine.

**Comment by mojaveazure** [comment]
Can you try installing R in PowerShell or R-Gui (`rgui.exe`)?

**Comment by timoast** [comment]
Closing this since we haven't heard back
