### ISSUE TITLE
Load10X_Spatial fails if there is a "tissue_positions_list.csv" file in the data, which exists in all of my samples

### ISSUE THREAD

**Issue by johan-gson** [satijalab/seurat#6547]
I got the following error from the following line>
vd = Load10X_Spatial(
  data.dir = "C:/Code/Projects/CLLSpatial/data/XXX")

Error in file(file, "rt") : invalid 'description' argument

I debugged it, and it turns out that the following lines in Read10X_Image fails:

  tissue.positions.path <- Sys.glob(paths = file.path(image.dir, 'tissue_positions*'))
  tissue.positions <- read.csv(
    file = tissue.positions.path,
    col.names = c('barcodes', 'tissue', 'row', 'col', 'imagerow', 'imagecol'),
    header = ifelse(
      test = basename(tissue.positions.path) == "tissue_positions.csv",
      yes = TRUE,
      no = FALSE
    ),
    as.is = TRUE,
    row.names = 1
  )

So, tissue.positions.path becomes a list of two files, "tissue_positions.csv" and "tissue_positions_list.csv" - trying to use a list of length > 1 gives that error message.

I am also at Broad if you need anything.

**Comment by johan-gson** [comment]
And, removing the tissue_positions_list.csv fixes the problem as a workaround, but that took quite some time to figure out :)

**Comment by johan-gson** [comment]
Ok, sorry, this was caused by a previous user, the file ending with "_list" shouldn't be there. I'm closing this now.

**Comment by jeramand** [comment]
I was having the same issue, but I on purpose created the `tissue_positions_list.csv` for backward compatibility with tools that that do not work with the new Spaceranger 2.0 output yet. Maybe that's a special case, but it would be nice if Seurat would work with both files present (and maybe take the "newer" `tissue_positions.csv` in that case).
