### ISSUE TITLE
Conflicting license ?

### ISSUE THREAD

**Issue by pallaeyo** [satijalab/seurat#6553]
Thanks for making this great software.

The github LICENSE.md file states that this software is MIT license,
and the cran site also states the same.

Interestingly at the bottom of the page https://satijalab.org/seurat/ there's another statement;
"Seurat is released under the GNU Public License (GPL 3.0)."

MIT and GPL are completely different - can I ask which license is the correct one?

**Comment by timoast** [comment]
The correct license is MIT, we will update this on the website

**Comment by timoast** [comment]
This is now updated on the website
