### ISSUE TITLE
Unable to install Seurat library

### ISSUE THREAD

**Issue by mariamnawaz1** [satijalab/seurat#6554]
Hi,

I have installed Seurat in R previously but this time it is giving an error saying "package ‘Seurat’ is not available (for R version 3.6.1)". Could you let me know how can I install it? I tried doing everything I could find online.

Thank you!

**Comment by WesDe** [comment]
Hi,

As explain on the website:` "To install Seurat, [R](https://www.r-project.org/) version 4.0 or greater is required."
You can also install previous version as explained [there](https://satijalab.org/seurat/articles/install.html).

So the easiest way is to update your R version, if you are on a server and unable to update the default R version, you may be able to use the Seurat docker or create a conda environment.

Best,
WesDe

**Comment by samuel-marsh** [comment]
Hi,

@WesDe is correct.  I'll also add if locally and you want to maintain multiple R versions you can use tool like RSwitch to easily  manage and switch between R versions (package libraries kept separate between R versions).

Best,
Sam
