### ISSUE TITLE
CCA integration of merged object

### ISSUE THREAD

**Issue by jgarces02** [satijalab/seurat#6559]
Hi, is it possible to performed a CCA integration on a object with already merged dataset or is it mandatory to pass a `object.list`?

`SO <- SelectIntegrationFeatures(object.list = list.seurat, nfeatures = 3000)`

I mean, I can split my merged dataset through `SplitObject` and then pass it to `object.list` but I'm not sure if it's correct from an analysis point of view or if there's a more straightforward way. 

Thanks

**Comment by Gesmira** [comment]
Hi, as can be seen in this vignette, [Introduction to scRNA-seq integration](https://satijalab.org/seurat/articles/integration_introduction.html), you should provide a list of Seurat objects for the integration steps. As you suggested, you can split your object with `SplitObject` by sample or stimulation, for example, and then normalize, find variable features, and follow the rest of the integration workflow with that list.
