### ISSUE TITLE
Adding titles to dotplot

### ISSUE THREAD

**Issue by atlmalive** [satijalab/seurat#6561]
Hi everyone,

Can anyone guide me on adding a title to a dotplot?

I've made 3 separate dotplots, labeled the legends and stacked them on top of each other. I wanted to name my dotplot something such as vs04p at the top of the plot. Thanks in advance!

Dot1 <- DotPlot(object = so, features = panM, 
cols = c("pink","purple"), col.min = 0, col.max = 5)+RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),
axis.text.y=element_text(size=7)) + xlab('P_genes') + theme(axis.title.x = element_blank(), 
 axis.text.x = element_blank(), axis.ticks.x = element_blank(),axis.line.x = element_blank())

Dot2 <- DotPlot(so, features =p1, 
cols = c("pink","purple"), col.min = 0, col.max = 5)+RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),
axis.text.y=element_text(size=7)) + xlab('p1_genes') +theme(axis.title.x = element_blank(), 
axis.text.x = element_blank(), axis.ticks.x = element_blank(),axis.line.x = element_blank())

Dot3 <- DotPlot(so, features = p2, 
cols = c("pink","purple"), col.min = 0, col.max = 5)+RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),
axis.text.y=element_text(size=7)) + xlab('p2_genes') + theme(axis.title.x = element_blank())

Dot <- (Dot1/Dot2/Dot3)
ggplot2::ggsave(stringr::str_interp("plots/soDot.pdf"), plot = Dot, height = 10.6, width = 8.3, units = "in")

**Comment by samuel-marsh** [comment]
Hi,

Similar to the other theming you've done you can add title to DotPlots using standard ggplot theming (`ggtitle`).
```
Dot1 <- DotPlot(object = so, features = panM,
cols = c("pink","purple"), col.min = 0, col.max = 5)+RotatedAxis()+coord_flip()+theme(axis.text.x=element_text(size=7),
axis.text.y=element_text(size=7)) + xlab('P_genes') + theme(axis.title.x = element_blank(),
axis.text.x = element_blank(), axis.ticks.x = element_blank(),axis.line.x = element_blank()) + ggtitle("Title Here")
```

If you want to add one title to your patchwork of the 3 plots you can use patchwork themeing:
```
Dot <- (Dot1/Dot2/Dot3) + plot_annotation(title = 'Title Here')
```

Best,
Sam
