### ISSUE TITLE
Interpreting SCT

### ISSUE THREAD

**Issue by Shaken-not-stirred** [satijalab/seurat#6564]
### Discussed in https://github.com/satijalab/seurat/discussions/6536

<div type='discussions-op-text'>

<sup>Originally posted by **Shaken-not-stirred** October 11, 2022</sup>
I hope this is not a trivial question or a question that was already posted and answered. But so far, I did not find an answer in the previous discussions, instructions or the original paper. (A) How can one interpret the scale of the SCT assay, (B) what does the value 1 mean when do.scale and do.center are either TRUE or FALSE, and (C) what is the log base? Any help would be appreciated. Whereas I can see visually pleasing changes in my graphs based on the SCT, I would really like to know what the numeric differences mean in terms of scale and in terms of comparing a gene to mean or median gene expression of the dataset. Whereas I think I know the answers to my questions, confirmation would be very welcome. </div>

**Comment by yuhanH** [comment]
hi
1. scale data in SCT assay is the centered Pearson residuals. You can find detailed methods in SCTransform manuscript. [sctransform v1](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1) and [sctransform v2](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9)
2. do.scale will standrand the variance of each gene to 1 and do.center will center the mean of each gene to 0, so value 1 is just a relative value in the scale.data slot
3. the log base is e (2.7182....)

**Comment by Shaken-not-stirred** [comment]
Thank you for the clarification, yuhanH, it is really appreciated. Perhaps just another similar question, namely what is the log base in assays$RNA@data? It again says that the data is log-transformed, but I am not 100% sure what the log base is. Similarly, LogNormalize()? I am sorry for asking this, but I simply cannot find this information in publications, discussions, .pdf files etc. Can I work with a custom base? I know I could potentially access assays$RNA@counts and then do a log-transformation of my liking, but it would be much more straightforward to use what your package already provides. I think the most user-friendly is having everything on a log2 scale, simply because of interpretability. Thank you again.
