### ISSUE TITLE
NicheNet with SCT v2

### ISSUE THREAD

**Issue by anaccsilva** [satijalab/seurat#6570]
Hello, I am trying to run Nichenet analysis on my Seurat object that I used the newer V2 regularization pipeline.
I saw that someone previously asked the same question to Nichenet developers, but I guess they also need some of your input.

They asked: "Could you ask them how they would analyze DE between two conditions on SCT-integrated data? (after subsetting the data to get only cells of one cell type)"

I appreciate the help.

**Comment by saketkc** [comment]
DE analysis should be performed on SCT corrected counts (`data` slot). You can use `PrepSCTFindMarkers()` to account for different library depths across datasets as shown in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html).

**Comment by anaccsilva** [comment]
Thank you. I'll contact them.
