### ISSUE TITLE
DoHeatmap

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#6577]
I have a list of barcodes for certain cells of interest.
I would like to plot a heatmap using DoHeatmap for only these cells.

- How can I specify my list of interesting barcodes for DoHeatmap?
- Can I choose specific clusters to plot on DoHeatmap? For example, I want to only look at clusters labeled for a certain cell type.
- How can I choose what genes are displayed by DoHeatmap? What are the best genes to show?

**Comment by f6v** [comment]
`DoHeatmap` accepts a Seurat object, so you can always subset it to specific cells or clusters before making a heatmap. I'm not sure if you need/want to re-scale that specific subset though.

**Comment by atly2000** [comment]
> `DoHeatmap` accepts a Seurat object, so you can always subset it to specific cells or clusters before making a heatmap. I'm not sure if you need/want to re-scale the expression values that specific subset though.

I currently have cells across three different time points. Should I re-scale the data if I am only using some of my cells and not the entire UMAP? What is the best way to go about this?

**Comment by f6v** [comment]
I guess if you subset, then the data might be not centered anymore. If you want to be centered, then you can re-run the scaling.

**Comment by mhkowalski** [comment]
Yes, you should re-scale the data if you would like the features to be scaled and centered for that subset of cells.
