### ISSUE TITLE
How to extract the normalized expression of only 1 gene?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6578]
Hello. May I ask how to extract the normalized expression of only 1 gene?

I would like to create a gene expression by pathway score correlation, but I don't know how to extract a column of normalized expression values of cells for only 1 gene. Do you have any suggestions?

Thank you!

**Comment by f6v** [comment]
Given `processed_seurat`:

```
An object of class Seurat 
29896 features across 3514 samples within 2 assays 
Active assay: SCT (12221 features, 3000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
```

I do this:

`GetAssayData(processed_seurat['Cd4', ])`

Which returns `1 x 3514 sparse Matrix of class "dgCMatrix"`

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can easily do this with `FetchData` too.

```
Gene <- FetchData(object = obj, vars = "Gene", slot = "data")
```

Best,
Sam
