### ISSUE TITLE
Too many small clusters found after integrating data by harmony

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#6579]
Dear Seurat team,

I used Seurat coupled with harmony several times for integrating batched samples and achieved good results. But when I recently integrate 52 samples including 34w cells in total by harmony, it gives very strange results.  The UMAP looks very mass with too many small clusters as shown below.  My question is what caused this to happen and how to solve it to make it looks reasonable. My codes are attached below because I have used Seurat and harmony several times I don't think it is caused by my codes. Are there any parameters to adjust to make it integrate reasonably?

Many thanks!

## My codes to run 
scObject is my Seurat object. SampleID is the label for each sample.

```
scObject <- NormalizeData(scObject) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA(npcs = 50, verbose = FALSE)
scObject <- RunHarmony(scObject, group.by.vars = "SampleID", dims.use =1:50, project.dim = TRUE, plot_convergence=TRUE)
scObject.integrated <- RunUMAP(scObject.integrated, reduction = "harmony", dims = 1:30)
scObject.integrated <- FindNeighbors(scObject.integrated, reduction = "harmony", dims = 1:30)
scObject.integrated <- FindClusters(scObject.integrated, resolution = 0.5)
```

![UMAP integrated by harmony](https://github.com/SeadonXing/Questions/blob/master/UMAP.harmony.PNG)

**Comment by f6v** [comment]
> Are there any parameters to adjust to make it integrate reasonably?

First, define reasonable. I think it's very subjective. Second, I'd suggest plotting the distribution of samples within each cluster. Are these smaller clusters sample-specific? What kind of cells do you have there? Most importantly, why do you integrate by sample? Was there a batch effect between samples? Do you have plots for distribution of samples on the UMAP without any integration?

**Comment by timoast** [comment]
This is also a question for the Harmony developers rather than Seurat: https://github.com/immunogenomics/harmony
