### ISSUE TITLE
ECCITE data release GSE164378 repertoire barcode format

### ISSUE THREAD

**Issue by crichgriffin** [satijalab/seurat#6581]
Hi,

I downloaded the  5' Eccite data from GEO, https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378  

The barcodes are formatted differently in the RNA/HTO/ADT data to the repertoire data
The RNA/HTO/ADT are formatted as L11_AAACCTGAGGCGTACA
and the repertoire data are in the format AAACCTGAGCATCATC-1. 

Is there a release of the repertoire data that is consistent with the RNA data?

**Comment by timoast** [comment]
@crichgriffin please contact the corresponding author directly, as this is not related to Seurat
