### ISSUE TITLE
Subclustering according to low vs High expression of a candidat gene

### ISSUE THREAD

**Issue by Dalhte** [satijalab/seurat#6582]
Hello
I hope it has not been already answered elsewhere.
I'm new to scRNA-seq analysis
I would like to divide a cluster in two subcluster according to a given gene expression but I don't know how to do that. If somebody knows the trick, it would be great.
Best
David

**Comment by AustinHartman** [comment]
You can select a group of cells based on gene expression of some gene (MS4A1 shown here) with the following code: `b.cells <- Cells(subset(pbmc, subset = MS4A1 > 0)` and subsequently assign those cells to a cluster

**Comment by Dalhte** [comment]
Thanks a lot !
Best
D
