### ISSUE TITLE
Average expression different in dotplot vs Average expression analysis for all genes.

### ISSUE THREAD

**Issue by devenderarora** [satijalab/seurat#6584]
Dear Seurat Team,
I am trying to plot a dot plot using 
`plot1<-DotPlot(subset_CD10_5_0, features = c(cc.genes$s.genes, "MAP2"),  split.by = "seurat_clusters", cols="RdBu")`

Looking closer at the scaled average expression in cases for MAP2 we found the observed value.
for **plot1$data** the data look like:

| avg.exp | pct.exp  | features.plot | id  | avg.exp.scaled |
|---------|----------|---------------|-----|----------------|
| 10.60558 | 87.42138 | **MAP2** | CD10_5_0 | -0.30941 |
  
After looking into the info we found the average expression calculated by:
 
`AverageExpression(
  CD10_5_0 ,
  features = subset_CD10_5_0@assays$RNA@meta.features,
  return.seurat = FALSE,
  group.by = "ident",
  add.ident = NULL,
  slot = "scale.data",
  verbose = TRUE
)`

for MAP2 was
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

MAP2 | -0.24779
-- | --

</body>

</html>

I am trying to understand the scaling of data but could not get any information.

Can you please help me with understanding why the average expression in dotplot is different than Average expression function.

Thanks,
Devender

**Comment by torkencz** [comment]
Hi. You might wanna check this out, which discusses this issue https://github.com/satijalab/seurat/issues/2798.
If not clear I can reopen.
