### ISSUE TITLE
RunMultiCCA tutorial

### ISSUE THREAD

**Issue by acooley3** [satijalab/seurat#659]
Where can I find the tutorial for RunMultiCCA?

Thanks,
Anne

**Comment by yueqiw** [comment]
https://satijalab.org/seurat/immune_alignment.html
The first paragraph contains a link to an R source file for MultiCCA. I guess this is the only tutorial available so far.

**Comment by acooley3** [comment]
Ok, thanks. Based off previous issues and comments, it seemed like there was a tutorial for RunMultiCCA but I haven't been able to find it, so maybe not.

**Comment by acooley3** [comment]
Is there going to be a tutorial for RunMultiCCA?
