### ISSUE TITLE
When use SCTransform to analysis spatial transcriptome data error 

### ISSUE THREAD

**Issue by wy-cmd** [satijalab/seurat#6591]
I used the following code to process the spatial transcriptome data:
`library(dplyr)
library(data.table)
library(Matrix)
library(rjson)
library(ggplot2)
library(ggsci)
library(Seurat)
library(patchwork)
library(RColorBrewer)
library(pheatmap)
library(cowplot)
library(ggpubr)
library(future)
infile <- args[2]#infile<-"marker_cellbin_center_cell.gem"
bs <- as.numeric(args[3])#50
cut <- as.numeric(args[4]) #200
pc <- as.numeric(args[5]) #20
res <- as.numeric(args[6]) #0.5
sp <- as.character(args[7]) #human
pro <- tail(unlist(strsplit(infile,"/")),1)
pro <- gsub(".gem|.txt|.tsv|.gz|_filterd","",pro)
dat <- fread(file = infile)
dat$x <- trunc((dat$x - min(dat$x)) / bs + 1)
dat$y <- trunc((dat$y - min(dat$y)) / bs + 1)

out <- cbind(dat$y,dat$x,out)
colnames(out)[1:2] <- c(paste0("bin",bs,".y"),paste0("bin",bs,".x"))
fwrite(out,paste0(pro,"_bin",bs,"_information.txt"),col.names=T,row.names=F,sep="\t",quote=F)
dat <- dat[, sum(UMICount), by = .(geneID, x, y)]
dat$bin_ID <- max(dat$x) * (dat$y - 1) + dat$x
bin.coor <- dat[, sum(V1), by = .(x, y)]
geneID <- seq(length(unique(dat$geneID)))
hash.G <- data.frame(row.names = unique(dat$geneID), values = geneID)
gen <- hash.G[dat$geneID, 'values']

##
bin_ID <- unique(dat$bin_ID)
hash.B <- data.frame(row.names = sprintf('%d', bin_ID), values = bin_ID)
bin <- hash.B[sprintf('%d', dat$bin_ID), 'values']
cnt <- dat$V1

##
rm(dat)
gc()

##
tissue_lowres_image <- matrix(1, max(bin.coor$y), max(bin.coor$x))

tissue_positions_list <- data.frame(row.names = paste('BIN', rownames(hash.B), sep = '.'),
                                    tissue = 1, 
                                    row = bin.coor$y, col = bin.coor$x,
                                    imagerow = bin.coor$y, imagecol = bin.coor$x)

scalefactors_json <- toJSON(list(fiducial_diameter_fullres = 1,
                                 tissue_hires_scalef = 1,
                                 tissue_lowres_scalef = 1))
mat <- sparseMatrix(i = gen, j = bin, x = cnt)

rownames(mat) <- rownames(hash.G)
colnames(mat) <- paste('BIN', sprintf('%d', seq(max(hash.B[, 'values']))), sep = '.')

seurat_spatialObj <- CreateSeuratObject(mat, project = 'Spatial', assay = 'Spatial',min.cells=5, min.features=5)

##
generate_spatialObj <- function(image, scale.factors, tissue.positions, filter.matrix = TRUE) 
{
  if (filter.matrix) {
    tissue.positions <- tissue.positions[which(tissue.positions$tissue == 1), , drop = FALSE]
  }
  
  unnormalized.radius <- scale.factors$fiducial_diameter_fullres * scale.factors$tissue_lowres_scalef
  
  spot.radius <- unnormalized.radius / max(dim(image))
  
  return(new(Class = 'VisiumV1', 
             image = image, 
             scale.factors = scalefactors(spot = scale.factors$tissue_hires_scalef, 
                                          fiducial = scale.factors$fiducial_diameter_fullres, 
                                          hires = scale.factors$tissue_hires_scalef, 
                                          lowres = scale.factors$tissue_lowres_scalef), 
             coordinates = tissue.positions, 
             spot.radius = spot.radius))
}

spatialObj <- generate_spatialObj(image = tissue_lowres_image, 
                                  scale.factors = fromJSON(scalefactors_json), 
                                  tissue.positions = tissue_positions_list)
spatialObj <- generate_spatialObj(image = tissue_lowres_image, 
                                  scale.factors = fromJSON(scalefactors_json), 
                                  tissue.positions = tissue_positions_list)

##
spatialObj <- spatialObj[Cells(seurat_spatialObj)]
DefaultAssay(spatialObj) <- 'Spatial'

seurat_spatialObj[['slice1']] <- spatialObj

rm(mat)
rm(bin.coor)
rm(hash.G)
rm(hash.B)
rm(bin)
rm(gen)
rm(cnt)

dir.create("figures")

### for mouse("^mt-")/human("^MT-")
seurat_spatialObj[["percent.mt"]] <- PercentageFeatureSet(seurat_spatialObj, pattern = mt_pattern) 
Q1 <- quantile(seurat_spatialObj$nFeature_Spatial)[2]
Q3 <- quantile(seurat_spatialObj$nFeature_Spatial)[4]
upper <- as.numeric(Q3+1.5*(Q3-Q1))
lower <- as.numeric(Q1-1.5*(Q3-Q1))
#raw Quality
pdf(paste0("figures/",pro,"_bin",bs,"_QC_raw.Feature.pdf"))
VlnPlot(seurat_spatialObj, features = c("nFeature_Spatial", "nCount_Spatial", "percent.mt"), ncol=3,pt.size = 0) +theme(axis.text.x=element_text(angle=20,size=0),axis.title.x=element_text(angle=20,size=10))+labs(x=paste0("nGene: ",dim(seurat_spatialObj)[1],"; ","nBIN: ",dim(seurat_spatialObj)[2]))
plot(density(seurat_spatialObj$nFeature_Spatial))+abline(v=c(50,100,150,200,500),col="grey",lwd=2,lty=6)
SpatialFeaturePlot(seurat_spatialObj, features="nFeature_Spatial", stroke=0) + theme(legend.position = "right") + scale_y_reverse()
SpatialFeaturePlot(seurat_spatialObj, features="nCount_Spatial", stroke=0) + theme(legend.position = "right") + scale_y_reverse()
dev.off()
#q()
#QC
pdf(paste0("figures/",pro,"_bin",bs,"_QC.Feature.pdf"))
#temp <- seurat_spatialObj
seurat_spatialObj <- subset(seurat_spatialObj,subset = nFeature_Spatial > cut &  percent.mt < 20)
VlnPlot(seurat_spatialObj, features = c("nFeature_Spatial", "nCount_Spatial", "percent.mt"), ncol=3,pt.size = 0) +theme(axis.text.x=element_text(angle=20,size=0),axis.title.x=element_text(angle=20,size=10))+labs(x=paste0("nGene: ",dim(seurat_spatialObj)[1],"; ","nBIN: ",dim(seurat_spatialObj)[2]))
plot(density(seurat_spatialObj$nFeature_Spatial))+abline(v=c(500,650,800),col="grey",lwd=2,lty=6)
SpatialFeaturePlot(seurat_spatialObj, features="nFeature_Spatial", stroke=0) + theme(legend.position = "right") + scale_y_reverse()
SpatialFeaturePlot(seurat_spatialObj, features="nCount_Spatial", stroke=0) + theme(legend.position = "right") + scale_y_reverse()
dev.off()
#seurat_spatialObj <- temp
saveRDS(seurat_spatialObj,file=paste0(pro,"_bin",bs,"_QC.rds"))
q()
##############################  4. Data SCTransform  Clusters ##############################
set.seed(6)

seurat_spatialObj <- SCTransform(seurat_spatialObj, assay = "Spatial", verbose = FALSE, variable.features.n=3000)
`
But ,when run “seurat_spatialObj <- SCTransform(seurat_spatialObj, assay = "Spatial", verbose = FALSE, variable.features.n=3000)” is error：
`warning: solve(): system is singular; attempting approx solution
Error in h(simpleError(msg, call)) : 
  在为't'函数选择方法时评估'x'参数出了错: missing value where TRUE/FALSE needed `
What is the cause of this, and how do I change it? Thanks~

**Comment by saketkc** [comment]
Can you try running `SCTransoform(vst.flavor="v2")`

**Comment by wy-cmd** [comment]
Thank you very much, it is ready to run!
