### ISSUE TITLE
FindAllMarkers after Merge (SCT data) / PrepSCTFindMarkers Issue

### ISSUE THREAD

**Issue by lsryap** [satijalab/seurat#6592]
I am currently analysing single cell data consisting of 8 time-points in a series. I have processed each of these datasets via SCTransform, and following PCA, UMAP and clustering have used FindAllMarkers to visualise DE markers. The output is clear and makes biological sense.

I have now attempted to merge these objects together to see changes over time. In the first instance I merged all SCT objects, then ran SCTransform for a second time on the merged object and performed clustering etc. FindAllMarkers ran fine, and again the output made sense.

However I was unsure whether this second SCtransform was correct, so I attempted a different pipeline:

1) Merge the 8 individual SCT objects
2) VariableFeatures(merged.obj[["SCT"]]) <- rownames(merged.obj[["SCT"]]@scale.data)
3) RunPCA(merged.obj, verbose = FALSE)
    RunUMAP(merged.obj, dims = 1:50, verbose = FALSE)
    FindNeighbors(merged.obj, dims = 1:50, verbose = FALSE)
    FindClusters(merged.obj, resolution = 0.8, verbose = FALSE)
    DimPlot(merged.obj, reduction = "umap", label = TRUE) *this looks good - clusters similar to SCTransform-ing twice but 
    clearer separation here*
4) merged.obj <- PrepSCTFindMarkers(merged.obj, assay = "SCT", verbose = TRUE)
5) FindAllMarkers(merged.obj, only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, assay = "SCT")

(5) returns:

Warning: No DE genes identified
Warning: The following tests were not performed: 
Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`

I'm not sure what to attempt next as I have run the PrepSCTFindMarkers command on the data already.

Thanks in advance for any pointers. I'm not from a bioinformatics background which I'm sure shows!

**Comment by saketkc** [comment]
Can you paste your full code here?

**Comment by lsryap** [comment]
Apologies for the late reply. 

I actually ran the exact same script on a different machine and it worked fine! Clusters look good and FindAllMarkers returned no errors at all. The problem is seemingly something my end and not with the code itself.
