### ISSUE TITLE
DotPlot 'split.by' plotting alphabetically instead of by ordered factor levels

### ISSUE THREAD

**Issue by RobertWhitener** [satijalab/seurat#6594]
Hi, I have generated a list of genes which I am trying to plot on a DotPlot.

I am grouping by 'cellannotation' and then splitting the graph by 'stage', which refers to the developmental stage of my samples (aka, they have an age associated with them)

The group.by parameter is correctly ordering the groups as I want them, but the split.by parameter is only plotting the splits in alphabetical order, which is frustrating when trying to compare expression across time.

I have tried rev() to reverse the stages, converted the column to a chr type, and re-ordered the levels; none of which appear to have any affect on the order by which the stages are plotted.

Any ideas?

Thanks
Robert

**Comment by mmdzt** [comment]
Wanna know this too

**Comment by torkencz** [comment]
Yeah what @mmdzt wrote could work. Or any kind of releveling.

**Comment by RobertWhitener** [comment]
Hi mmdzt and torkenc.

I specifically mentioned trying to re-level the metadata in my original post, which had no effect.

That said,  I'm currently in the process of moving to a new machine, necessitating re-installation of my R packages.  Maybe this will fix my issue.
