### ISSUE TITLE
Compatibility with maegatk

### ISSUE THREAD

**Issue by dy-lin** [satijalab/seurat#6595]
A special version of mgatk has been released called maegatk, specific for scRNA-seq data: https://github.com/caleblareau/maegatk

I'd like to request a version of the `ReadMGATK()` command that is in the Signac package for maegatk output. Currently the number of columns / what the columns represent are different in maegatk than that of mgatk, so `ReadMGATK()` is incompatible.

**Comment by k3yavi** [comment]
Hi @dy-lin ,

The requests for adding functionality to read/write from/to complementary tools are supported through the Seurat wrapper package [here](https://github.com/satijalab/seurat-wrappers). Please feel free to add a PR to the repo.
