### ISSUE TITLE
Subclustering and Integration

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#6596]
Yes, you should re-scale the data if you would like the features to be scaled and centered for that subset of cells. For your first and second questions, you can subset the object based on a list of cells or clusters that you would like to plot (see examples [here](https://satijalab.org/seurat/articles/essential_commands.html). 

You can plot whatever genes you would like, although you might consider plotting genes that vary by cluster or condition, such as those you would find from the ```FindMarkers``` command.

_Originally posted by @mhkowalski in https://github.com/satijalab/seurat/issues/6577#issuecomment-1287341832_

I am planning on performing gene expression analysis based on a cluster I identified during UMAP construction.
I have the barcode list for all the cells in this cluster.
If I am working with an integrated dataset with multiple timepoints, how can I create a new integrated object containing only these cell barcodes?

**Comment by k3yavi** [comment]
you can use the `subset` functionality, `subset(object, cells=<your_list>)`
