### ISSUE TITLE
Error: No requested features found in the scale.data slot for the RNA assay

### ISSUE THREAD

**Issue by mariamnawaz1** [satijalab/seurat#6599]
I am trying to plot Heatmap of an integrated data. As suggested in the tutorial, I am using the RNA assay for that but it is giving me error. I have tried scaling the RNA assay before plotting heatmap, but didn't workout. Please help.

gse <- ScaleData(gse, features = rownames(gse), assay="RNA", verbose = FALSE)
DoHeatmap(gse, features=features, assay = "RNA")

Error: No requested features found in the scale.data slot for the RNA assay.

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What is the result of:

```
all(features %in% rownames(gse))
```

Best,
Sam

**Comment by yuhanH** [comment]
Thank you @samuel-marsh for your answer. I agree with you. It is very likely that some genes in `features` not in the data slot as well.
You can use the intersect of genes. 
`features <- intersect(features, rownames(gse[['RNA']]))`

**Comment by seasonzhao** [comment]
Hi,I think if you can check gse have the "scale.data",gse>RNA>scale.data,if scale.data is 0,you need to do something like "ScaleData(gse, features = all.genes)"

by the way,this is my first time to comment on github,I hope I can help :)
