### ISSUE TITLE
DE analysis and expression visualization with SCTransform v2

### ISSUE THREAD

**Issue by tianyi21** [satijalab/seurat#6601]
Hi Seurat Team,

Recently, I'm working on comparing two 10x multiome datasets. As a first step, I tried to follow SCTv2 vignette to integrate RNAseq dataset (Also per recommendation #5346, I'm supposed to integrate RNA first). I have a few questions and will be grateful if you can help me with these.

1. In the [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), `FindConservedMarkers` and `FeaturePlot` was performed on `SCT` assay. From what I have learned, `SCT@data` of `ctrl` and `stim` contains uncorrected Pearson residual from `SCTransform` of each group itself. In other words, I would expect batch effect if we visualize `SCT@data` directly. Therefore, the difference between `ctrl` and `stim` group is the combination of stimulation and technical difference. As a results, DE test is testing based on both of them, and expression levels between `ctrl` and `stim` in `FeaturePlots` cannot be compared directly. I'm wondering if `FindConservedMarkers` should be run on `integrated@data`. Please correct me if I miss anything.
2. When using SCT integration, the gene of interest (GoI) may not be selected as top features (e.g., not in top-3000). Therefore, in the integration, GoI will not be included in the anchorset either. Currently, what I'm doing is the following: after running SCTransform, I run `GetResidual(object, feature=GoI)` to ensure both dataset contains GoI. Then, when running integration, I will manually, and forcibly, include GoI.
```
features <- SelectIntegrationFeatures(object.list = dataset.list, nfeatures = 3000)
dataset.list <- PrepSCTIntegration(object.list = dataset.list, anchor.features = **c(features, GoI)**)
dataset.anchors <- FindIntegrationAnchors(object.list = dataset.list, normalization.method = "SCT", anchor.features = **c(features, GoI)**)
```
However, as you may notice, this will alter the results. So, I would like to see what will be the best practice if GoI is not present in the TopFeatures. P.s. if you can answer question 1, I can then `GetResidual` for GoI and visualize in integrated UMAP space.
3. For a single dataset, if I processed it with SCT v2, I should be able to run DE analysis directly on the SCT assay. I have seen quite a few issues (#4032) saying that DE should be performed directly on SCT v1 assay and it should be done on RNA. In such a scenario, I am supposed to run `NormalizeData` and `log1p` on RNA assay and run DE afterwards on `RNA@data`. Am I understanding this correctly?

Thanks in advance!

**Comment by saketkc** [comment]
> From what I have learned, SCT@data of ctrl and stim contains uncorrected Pearson residual from SCTransform of each group itse

This is incorrect. The `data` slot contains **corrected counts**. Pearson residuals are stored in the `scale.data` slot. The batched corrected information is in the `integrated` assay. 

> However, as you may notice, this will alter the results. So, I would like to see what will be the best practice if GoI is not present in the TopFeatures. P.s. if you can answer question 1, I can then GetResidual for GoI and visualize in integrated UMAP space.

I am not sure what the Goi is here - is it expected to be differentially expressed between the two conditions? You can still test genes for differential expression if they are not part of features used for integration.


> For a single dataset, if I processed it with SCT v2, I should be able to run DE analysis directly on the SCT assay. I have seen quite a few issues.

Yes, you can use  the SCT data slot for DE after running `PrepSCTFindMarkers()`  (irrespective of v1 or v2). DE should not be run on Pearson resisduals (scale.data slot).

**Comment by tianyi21** [comment]
Hi Saket, thanks for your clarification. 

I had some misunderstandings on the data and scale.data slot but now it's clear.  Regarding question 2. GoI stands of gene(s) of interests, and we expect them to be differentially expressed between two conditions. Suppose GoIs are not part of the integration features, then which assay shall I run DEG on? 

Referencing to [this vignette](https://satijalab.org/seurat/archive/v3.0/immune_alignment.html), DEG analysis (`FindConservedMarkers()`) was performed on `combined@RNA` assay (which is analogue to `combined@SCT` under SCT workflow). In this case, without integration, won't batch effect between control and treatment group alters the DEG results? To me, running DEG on `combined@integrated` would make more sense, since the integration rule out technical difference. But in this case, GoIs are not present there.

Thanks for your help and please let me know if I missed anything.

**Comment by saketkc** [comment]
DEG should never be run on the integrated assay. So GoI not being one of the integration features is not an issue. 

You can adjust for batch effects during DE testing. One way to do so is to use the LR/MAST is option in 'test.use' when running FindMarkers and passing it your batch as 'latent.vars'.
