### ISSUE TITLE
subset and reclustering multiomic object

### ISSUE THREAD

**Issue by yamihn** [satijalab/seurat#6602]
Hello, I have a question about my analysis. I have a multiomic object scrnaseq + scatac seq integrated. I want to analyze a small subset of clusters. So this is what I did, using the integrated dataset:

 object= subset(myseurat, idents= c(1,2,3)
DefaultAssay(object) <- "RNA"
Idents(object) <- "clusters"  
object <- FindVariableFeatures(object, selection.method = "vst", nfeatures = 3000)
object<- ScaleData(object, verbose = FALSE, features = VariableFeatures(object))
object <- RunPCA(object, npcs = 50, verbose = FALSE, features = VariableFeatures(object))
object <- FindNeighbors(object, dims = 1:30)
object <- RunUMAP(object, dims = 1:30)
object <- FindClusters(object, resolution = 0.35)

About the scATAC-seq, I want to find the differentially accessible rergions. So, I need to calculate again the LSI, and recall the cluster? I don't have clear that part.
Thank you

**Comment by timoast** [comment]
Answered here: https://github.com/stuart-lab/signac/discussions/1258
