### ISSUE TITLE
Manual cluster designation by cell barcodes 

### ISSUE THREAD

**Issue by kysbbubbu** [satijalab/seurat#661]
Because I have identified interesting subpopulation from monocle, 
I have a data to designate new cluster manually by cell barcode like below. 

AAACGGGTCCGCAGTG-1 | 0
AAACGGGTCGATGAGG-1 | 0
AAACGGGTCGTTACGA-1 | 2
AAAGATGAGTACTTGC-1 | 2
AAAGATGAGTGTTGAA-1 | 0
AAAGATGTCAATCACG-1 | 0
AAAGATGTCGGGAGTA-1 | 0
AAAGCAAAGTGGAGAA-1 | 0
AAAGCAACACAGCGTC-1 | 0
AAAGTAGCATAAGACA-1 | 0
AAAGTAGCATAGGATA-1 | 2

How can I input these data to seurat object? (seuratobject@ident)

Thanks

**Comment by leonfodoulian** [comment]
Hi @kysbbubbu,

I suggest you add these data in your `object@meta.data` slot, say in a column named `manual.clusters`. You can then use the following code to change the identity of your cells to those chosen manually:

```R
object <- SetAllIdent(object = object, id = "manual.clusters")
```

Hope this helps!

Best,
Leon

**Comment by kysbbubbu** [comment]
in my case i put 00220000002... to manual.clusters in meta.data
and I used your code and it worked
Thanks
