### ISSUE TITLE
MULTISeqDemux function error: "No threshold found for CMO302"

### ISSUE THREAD

**Issue by JS0715** [satijalab/seurat#6611]
Hi
I am working on analyzing multiplexing (cellplex and TotalSeqA) data. I used HTOdemux for demultiplexing samples and it worked fine for both cellplex and totalseqA data however when I used MULTISeqDemux function for demultiplexing cellplex data it is giving me error saying "No threshold found for CMO302"

MULTISeqDemux function worked on TotalSeqA data though. Can you please help me understand what's going on?
<img width="575" alt="MultiSeqdemux-error" src="https://user-images.githubusercontent.com/62351024/198012862-f2b9bab1-e1c4-43e5-a5ae-25235c7dc9b6.png">

**Comment by f6v** [comment]
I had the same issue, but the other way around, i.e. `HTOdemux`. What you could do is plot a distribution for a specific feature. There's something about it that doesn't meet the assumptions of the underlying model. This could happen if the binding was sub-optimal and the counts aren't distributed the way the model expects them to.

**Comment by JS0715** [comment]
@f6v Thanks so much for the response! I thought so about the violation of assumptions of the model. I tried HTOdemux function and it works fine. What I wanted to do was benchmark and see which of these two methods are better for my dataset. Can you please help me understand what you mean by this "What you could do is plot a distribution for a specific feature" by showing an example and why this is important to check? Also, are you talking about the binding of lipid tags here? "binding was sub-optimal and the counts aren't distributed the way the model expects them to". Thanks again!

**Comment by longmanz** [comment]
Hi @JS0715 ,
Since you are setting "autoThresh = T", it will automatically try to find a suitable threshold, which could lead to the "No threshold found" problem, and @f6v explained the reason for that. What I usually do is to set "autoThresh = F" and just define a hard threshold ("quantile = x") myself. You may test several hard thresholds to see which fits the best to your dataset.
