### ISSUE TITLE
The integration question when using FindIntegrationAnchors

### ISSUE THREAD

**Issue by Moloch0** [satijalab/seurat#6612]
Hi, 
we are trying to integrate two samples which come from 10x(more than 10000 cells) and Smart seq(2000 cells).
We found that different cell numbers made a big difference in the results
**10x 2000 vs smart 2000**  817 anchors

![image](https://user-images.githubusercontent.com/113491969/198016837-653efc76-e058-4cc0-97f0-b96cece2bdcd.png)
**10x 8000 vs smart 2000**  1433 anchors
![image](https://user-images.githubusercontent.com/113491969/198016893-a386f1fb-0a9b-4a03-8e33-015156962fd3.png)

What is clear is that the two data sets are not completely or completely related to each other. But since the number of cells matters so much to the outcome, how should we determine the number of cells, or use other methods?

**Comment by f6v** [comment]
I don't think subsetting the 10x dataset is a good idea. First, which ones do you want to take for the integration? The results will differ depending on the specific subset of the whole data. Second, my guess is that due to sparsity, a smaller subset of 10x data will result in fewer common features with smartseq2. In any way, I wouldn't subset. What you could try is to explore other methods like `Harmony`, `Scanorama`, `BBKNN`, and others outside Seurat.

**Comment by Moloch0** [comment]
> I don't think subsetting the 10x dataset is a good idea. First, which ones do you want to take for the integration? The results will differ depending on the specific subset of the whole data. Second, my guess is that due to sparsity, a smaller subset of 10x data will result in fewer common features with smartseq2. In any way, I wouldn't subset. What you could try is to explore other methods like `Harmony`, `Scanorama`, `BBKNN`, and others outside Seurat.

Thanks for your comments. We tried to annotate the 10x data with the smart-seq dataset. So we randomly selected different numbers of cells to see what happened. But we don't seem to be able to measure the outcome of balanced cell numbers. If we have a similar number of cells, they integrate very closely. If the cells are vastly different in number, they become discrete populations. Anyway, we should try another way to see how this works.

**Comment by f6v** [comment]
>  If the cells are vastly different in number, they become discrete populations. Anyway, we should try another way to see how this works.

I don't think you have a unique situation. Smartseq2 datasets usually have much fewer cells than 10x, so all the tools that have been developed were tested in the same setting. Good luck with other tools.

**Comment by Moloch0** [comment]
> > If the cells are vastly different in number, they become discrete populations. Anyway, we should try another way to see how this works.
> I don't think you have a unique situation. Smartseq2 datasets usually have much fewer cells than 10x, so all the tools that have been developed were tested in the same setting. Good luck with other tools.

Thank you very much. We recently tried `harmony` and it turned out to be worse than we thought. Trying to combine 10X and smart seq is not a good idea. It's our ideas that confuse ourselves, not our tools.

**Comment by mhkowalski** [comment]
One additional comment here: you could try reference mapping the smaller SMART-Seq dataset onto the larger 10X dataset, as in this [vignette.](https://satijalab.org/seurat/articles/integration_mapping.html) You could then assess that expected cell-type markers line up to assess how well this works. 

Please follow up if you have any additional questions.
