### ISSUE TITLE
Regressing out both mitochondral genes and cell cycle effects seperately using SCTransform() and ScaleData()t

### ISSUE THREAD

**Issue by evchambers** [satijalab/seurat#6613]
Similar question to https://github.com/satijalab/seurat/issues/3926 , https://github.com/satijalab/seurat/issues/3935

Hello all, 

I just have some questions regarding my workflow. I am seeing clusters rich in mitochondrial genes even after subsetting the data  to include cells with < 20% mitochondrial genes. I am also seeing a lot of clusters driven by cell cycle effects.

I have some concerns with using `SCTransform()` and `ScaleData ()`to effectively regress these out. Any ideas or input on the following questions would be most welcome! 
1. Is it appropriate to scale the data again using `ScaleData()` following `SCTransform()`? 
2. If so should I set `do.scale=F` in`ScaleData()`?
3. Is there a way to regress these out together or not given that `CellCycleScoring()` should be done on normalised data?

```[r]
seurat <- CreateSeuratObject(counts,, min.cells = 10, min.features = 200)
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")

#Subset out low quality cells
seurat <- subset(seurat, subset = nFeature_RNA > 200  & nFeature_RNA < 7000 & percent.mt < 20 & nCount_RNA > 5000)
 
# regress out mito
seurat <- SCTransform(seurat vars.to.regress = "percent.mt", verbose = FALSE) 
  
#do cell cycle scoring
seurat <- CellCycleScoring(seurat, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
seurat <- ScaleData(seurat, vars.to.regress = c("S.Score", "G2M.Score"), features =  rownames(seurat))

#Run clustering
seurat<- RunPCA(seurat, features = VariableFeatures(object = seurat),)
seurat<- FindNeighbors(seurat)
seurat<- FindClusters(seurat, resolution = 0.5)
seurat<- RunTSNE(seurat)
seurat <- RunUMAP(seurat, dims = 1:15)->

```

**Comment by f6v** [comment]
I'd suggest to not mix `SCTransform` and `ScaleData`. Instead, simply use `SCTransform` to normalise the data. Then calculate cell cycle scores. After that, the Seurat object will have the scores. Save these as csv/tsv(export metadata columsn as a table). 

Then load the GEX the data again, create a new Seurat object. And add the metadata columns from csv/tsv you created with cell cycles scores to that object. Now, you can use the scores to regress the cell cycle out when using `SCTransform`. In essence, you'll do two passes of `SCTransform` on your data. Does this make sense?

**Comment by evchambers** [comment]
@f6v Thank you very much for your reply and advice.

It seems perhaps a long winded solution to have to reload the object again.  Would `do.scale=F` in the scaledata options not also work? Or perhaps I could use sctransform again? 

Thanks

**Comment by evchambers** [comment]
I think I have found a solution in a tutorial that allows for the seperate effects to be regressed out together in `SCTransform` following an ealier `ScaleData` step. For these interested the tutorial is below

https://hbctraining.github.io/scRNA-seq_online/lessons/06_SC_SCT_normalization.html

**Comment by shihsama** [comment]
If you have done SCTransform(), the "triology" functions can be bypassed.
