### ISSUE TITLE
FindTransferAnchors error  *** caught segfault *** address (nil), cause 'memory not mapped'

### ISSUE THREAD

**Issue by scarlettcanny0629** [satijalab/seurat#6614]
Hi,

I am using FindTransferAnchors and found that there is memory not mapped error that I don't know how to debug.
My input are two seurat RNA datasets with different number of genes across different cells and the overlapped genes number is 589.

Many thanks for your help!

> transfer.anchors = FindTransferAnchors(reference = chang.rna, query = smi_tme.rna, 
                                       features = row.names(chang.rna),
                                       reference.assay = "RNA", query.assay = "RNA", reduction = "cca")

Warning: 11183 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 589 features.

Running CCA

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: Standardize(mat = object1, display_progress = FALSE)
 2: RunCCA.default(object1 = data1, object2 = data2, standardize = TRUE,     num.cc = num.cc, verbose = verbose, )
 3: RunCCA(object1 = data1, object2 = data2, standardize = TRUE,     num.cc = num.cc, verbose = verbose, )
 4: RunCCA.Seurat(object1 = reference, object2 = query, features = features,     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,     verbose = verbose)
 5: RunCCA(object1 = reference, object2 = query, features = features,     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,     verbose = verbose)
 6: FindTransferAnchors(reference = chang.rna, query = smi_tme.rna,     features = row.names(chang.rna), reference.assay = "RNA",     query.assay = "RNA", reduction = "cca")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by timoast** [comment]
Can you show the full code you're running and output of `sessionInfo()`?
