### ISSUE TITLE
Integration of two experiments with CTRL in each experiment

### ISSUE THREAD

**Issue by LaetitiaRacine** [satijalab/seurat#6616]
Hello,

I've read  multiple issues on integration but couldn't find one that corresponds to my situation. 

I've got two scRNAseq experiments (10X platform) : 
- n°1 : one CTRL sample, six treated samples with different drugs
- n°2 : one CTRL sample,  two treated samples with different drugs (different from the ones used in n°1 experiment)
My initial experimental plan was to to all the conditions the same day but due to technical problems I couldn't do it.  Therefore, the two experiments were completed several months apart. I'm working on human primary CD34+ cells. The cells from experiments n°1 are a pool of multiple donors to avoid any patient specificity. The cells from experiments n°2 are also a pool of donors but a different one from experiment n°1. 

My goal is to compare my drugs conditions (8 samples) to the CTRL condition (two samples mixed ?) and also compare the drugs among each other without any batch effect interference. 

I pre-processed with SCT each conditions individually. I tried integration following the vignette and also the reference-based integration but I didn't understand exactly how to handle this specific case.

- Taking all the samples, should I merge all the samples from the same experiment before integrating both experiments together ?
- By doing that, is there a way to have both my CTRL merged and integrated and serve as a unique reference for later comparison ?
- Is it possible to bypass and only merge the CTRL before integration and consider them as a single reference ?

Anyone's help and/or comments would be really appreciated.
Thank you :)

**Comment by f6v** [comment]
What you need to do:
1. Process two experiments **separately without integration**. Make UMAP plots where you can see how different samples group.
2. Process two experiment **together without integration**. Sample UMAP plots where you can see individual samples **and** experiment groups. 

It's not possible to say how to process your data without seeing any plots. Is there even a batch effect there? That's for you to figure out with the plots. Feel free to post those here, I'll try to suggest something.

**Comment by LaetitiaRacine** [comment]
Thanks for your help !
I tried to follow your indications and here are the plots that I obtained.

1. Process two experiments separately without integration. 

Experiment/Batch1:
To do so, I created a list of previously normalized object (SCT, separatly for each condition) for the seven conditions of the first experiment. I determined the common variable features with features = SelectIntegrationFeatures (see issue #5761) and I merged all the object ofthe list. Then I added the variable features with VariableFeatures(merged) = feature and applied RunPCA and RunUMAP functions. I obtained the plots with DimPlot function. 
![umap_batch1_corrected](https://user-images.githubusercontent.com/67157711/199254709-7b6c3c44-346f-4649-a8ec-066b26680c20.png)


What can I deduced by comparing those plots ?
Do I need batch correction, if yes could you explain me how you see it ?




Experiment/Batch2:
I proceeded the same way for the 3 conditions of the second experiment.
![umap_batch2_corrected](https://user-images.githubusercontent.com/67157711/199254749-8704ace5-562f-4bdd-bc94-9689530bee38.png)


2. Process two experiments together without integration.

For the global analysis, I created a list with all the conditions from both experiments (separatly normalized with SCT) and proceeded the same way to extract the variables features. Then I merged all and also used RunPCA and RunUMAP.
![umap_bothbatch_corrected](https://user-images.githubusercontent.com/67157711/199254784-e707589b-4bd8-484f-8f46-d7cc7f9fb54d.png)
![umap_bothbatch_split_corrected](https://user-images.githubusercontent.com/67157711/199254805-a0d1cfac-9c0c-49ca-8c99-f38f551a402b.png)
To see better, I also did a plot with only both controls : 
![umap_bothbatch_ctrl](https://user-images.githubusercontent.com/67157711/199254924-8c8ca6c1-df6a-4d90-bb42-8e22d429706e.png)


What can I deduced by comparing those plots ?
Do I need batch correction with integration, if yes could you explain me how you see it ?
If I need to do integration, how should I proceed ?

**Comment by LaetitiaRacine** [comment]
Another interrogation. 
Before I asked for help here, I tried some other stuffs to figure out if I needed batch correction or not. I worked only with my controls conditions (I guess now it's not the best practice), and visualized them on umap too. I did it based on SCT normalisation or based on Lognormalisation. 

For SCT, I did the same as described earlier and obtained those graphs (quite the same as the solution 2) : 
![umap_ctrl_merged_sct](https://user-images.githubusercontent.com/67157711/199256538-4fe6ab07-5dd2-465c-a9fa-aa4eced2e11a.png)

For LogNormalisation, I used this code : 

`# Extract the two controls from the list of seurat object`  
`CTRL_manip1 = list_seurat_norm[["CTRL"]]`  
`CTRL_manip2 = list_seurat_norm[["CTRL2"]]`
`# Merge both control objects`
`CTRL_merged = merge(x = CTRL_manip1, y = CTRL_manip2, add.cell.ids = c("CTRL1", "CTRL2"))`
`# Visualize control objects in UMAP and PCA`
`DefaultAssay(CTRL_merged) = "RNA"`
`CTRL_merged = NormalizeData(CTRL_merged)`
`CTRL_merged = FindVariableFeatures(CTRL_merged)`
`CTRL_merged = ScaleData(CTRL_merged)`
`CTRL_merged = RunPCA(CTRL_merged, npcs = 30)`
`CTRL_merged = RunUMAP(CTRL_merged, reduction = "pca", dims = 1:30)`
`umap_batch = DimPlot(object = CTRL_merged, `
`                     group.by = "orig.ident", `
`                    reduction = "umap")`
`umap_split = DimPlot(object = CTRL_merged, `
`                     group.by = "orig.ident",`
`                    split.by = "orig.ident", `
`                    reduction = "umap") + NoLegend()`

and the plot really confused me. 
![umap_ctrl_merged_log](https://user-images.githubusercontent.com/67157711/199256747-c6e7a419-971d-4322-ac61-98cbd91c76ca.png)

Is it normal that I obtained so different results with different normalizations ? If I look only at the plot based on LogNormalisation, I would say there is a huge batch effect to correct but with SCT it seems quite ok. 
What's wrong in what I did here ? I'm really lost here.

Thanks a lot for your help !

**Comment by f6v** [comment]
In general, if you see that samples mix well together, my opinion is that you don't need any "integration". "Mix well" is, of course, subjective. People have come up with different metric for that(which I haven't really used so can't recommend anything). But at least for the very first plot you have I can say that I don't see why integration is necessary between the samples there.

Now, you can clearly see that "drug 7" stands out though. It is impossible to say whether this is a technical or biological effect without knowing the context. It is for you for decide whether such a difference is expected. Try finding markers for it and figure out if that's meaningful. Maybe there's contaminating RNA there? Just a thought.

Also, when you say "batch 1" and "batch 2", were all the samples within the batches processed on the same day? Is there anything different between the samples(sequencing depth, number of UMIs/genes, % MT transcripts, etc.). 

As for your second question about SCT vs log-normalisation, I haven't seen such drastic differences. Can't say much more.

**Comment by LaetitiaRacine** [comment]
I expect to have big differences between my CTRL cells and my "drug" cells so it's a good thing for me that "drug7" stands out.
 
About the batch, yes all the samples from batch 1 were processed the same day in the same technical conditions. The samples from batch 2 were processed on an other day (but all 3 the same day) and the sequencing chip was different than the one used for batch 1. 

My concerns were when I want to compare batch 1 with batch 2, but as you said my CTRL samples (one from each batch) seems to mix pretty well when I merged all the conditions (plot 8) so I might not need integration. 

About the comparison between SCT and log-normalisation, I might have done some mistake in my code. If I find it, I will let you know, else I will preferentially work with SCT normalisation. 

Thank you for your advice :)
