### ISSUE TITLE
How to subset/filter a seurat object with different parameters per group? 

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6618]
Hello! I have a seurat object with 2 groups: healthy and disease. I would like to simultaneously subset the object such that healthy group  will contain only GeneA-negative cells, while disease group will only contain GeneA-positive cells. 

I saw this pattern from Seurat command list, but this filters all groups in the same way:
`subset(x = pbmc, subset = MS4A1 > 0, idents = "healthy")`  # making the health group MS4A1-positive
`subset(x = pbmc, subset = MS4A1 < 0, idents = "disease")` # making the health group MS4A1-negative 

I have thought of separately performing the subsetting per group and then putting them back together using merge() but doing so will erase the normalized and scaled data so I was wondering if there's an easy way to do simultaneous subsetting for two groups using two different filters for each. Thank you!

**Comment by f6v** [comment]
> I have thought of separately performing the subsetting per group and then putting them back together using merge()

I would suggest to get two objects as you say, but don't merge them. Instead, get the barcodes(i.e. `colnames()`)  of these objects. Then you can merge two barcode vectors. After that, subset the original Seurat object with this combined barcode vector.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So just as note you should rescale the data after merging or subsetting regardless because the values depend on the other cells in the dataset.

What you can do is extract the cells that you want and subset on those:
```
cells1 <- WhichCells(pbmc, expression = MS4A1 > 0, idents = "healthy")
cells2 <- WhichCells(pbmc, expression = MS4A1 < 0, idents = "disease")

cells_comb <- c(cells1, cells2)

pbmc_sub <- subset(pbmc, cells = cells_comb)
```

Best,
Sam
