### ISSUE TITLE
CreateSeuratObject() error when loading matrix with only 1 cell

### ISSUE THREAD

**Issue by jdime** [satijalab/seurat#6621]
Hello,

I'm loading a mtx with only 1 cell/barcode in the barcodes.tsv.gz file. I use:
`expression_matrix <- Read10X(data.dir = PathToDataset, strip.suffix = F)`
And it's loaded as:

> [1] "dgCMatrix"
> attr(,"package")
> [1] "Matrix"
> [1] 33515     1

Then: 
`so <- CreateSeuratObject(counts = expression_matrix, min.cells = 1)`, but I'm getting this error:

> Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
>   'x' must be an array of at least two dimensions
> Calls: CreateSeuratObject ... CreateAssayObject -> <Anonymous> -> <Anonymous> -> <Anonymous>
> Execution halted

I read [here](https://statisticsglobe.com/r-colsums-rowsums-error-must-be-array-two-dimensions#:~:text=colSums(data%5B%20%2C%201%2C%20drop%20%3D%20FALSE%5D)%20%20%20%20%23%20Column%20sums%20for%20subset): that this type of issue for `colSums` can be fixed by using `drop = FALSE`:
`colSums(data[ , 1, drop = FALSE])`, and I'm wondering if I could use `rowSums(..., drop = FALSE])`, so I can use `CreateSeuratObject()` for datasets with only one cell.

If yes, where should I put that `drop = FALSE`?

This is my session info:

> "R version 4.0.5 (2021-03-31)"                                                       
>  [2] "Platform: x86_64-apple-darwin17.0 (64-bit)"                                         
>  [3] "Running under: macOS Big Sur 10.16"                                                 
>  [4] ""                                                                                   
>  [5] "Matrix products: default"                                                           
>  [6] "BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib"  
>  [7] "LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib"
>  [8] ""                                                                                   
>  [9] "locale:"                                                                            
> [10] "[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8"                  
> [11] ""                                                                                   
> [12] "attached base packages:"                                                            
> [13] "[1] parallel  stats4    stats     graphics  grDevices utils     datasets "          
> [14] "[8] methods   base     "                                                            
> [15] ""                                                                                   
> [16] "other attached packages:"                                                           
> [17] " [1] STACAS_1.1.0                tidyr_1.2.0                "                       
> [18] " [3] future_1.21.0               cowplot_1.1.1              "                       
> [19] " [5] ggplot2_3.3.5               data.table_1.14.0          "                       
> [20] " [7] fmsb_0.7.1                  optparse_1.6.6             "                       
> [21] " [9] dplyr_1.0.9                 SeuratObject_4.0.4         "                       
> [22] "[11] Seurat_4.0.2                DropletUtils_1.10.3        "                       
> [23] "[13] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0"                       
> [24] "[15] Biobase_2.50.0              GenomicRanges_1.42.0       "                       
> [25] "[17] GenomeInfoDb_1.26.7         IRanges_2.24.1             "                       
> [26] "[19] S4Vectors_0.28.1            BiocGenerics_0.36.1        "                       
> [27] "[21] MatrixGenerics_1.2.1        matrixStats_0.61.0         "                       
> [28] "[23] Matrix_1.3-3               "              

              .

Thanks.

**Comment by yuhanH** [comment]
hi @jdime 
One cell input case is very rare. You can just duplicate your input matrix as two cells and then subset to one cell. But no guarantee that other functions can support one cell case.

**Comment by jdime** [comment]
Yes, I just realized that functions like FindIntegrationAnchors() or IntegrateData() won't work with such low number of cells in a sample. So I'll need to merge samples with few cells anyways. Thanks.
