### ISSUE TITLE
batch effects

### ISSUE THREAD

**Issue by juechenyang** [satijalab/seurat#6624]
Hello,

So when we have an integrated dataset which is produced by using pipeline from Seurat (https://satijalab.org/seurat/articles/integration_introduction.html), is the log normalized matrix (data slot) in "RNA" assay still a matrix without batch effect correction? If so, is it safe to use log normalized matrix for gene expression variation profiling across cells from different batches?

Thank you!

**Comment by timoast** [comment]
Yes, the RNA assay contains the original, un-integrated, data

**Comment by juechenyang** [comment]
Hello,

Thank you for your response! My second question is whether the variation of gene expression profiled by **the original, un-integrated, data** across cells still carries batch effects (technical variations). 

Thank you again!

**Comment by timoast** [comment]
Yes, the original data is unchanged

**Comment by juechenyang** [comment]
Is it recommended to use batch-corrected expression values (for 2000 or 3000 highly variable genes) for downstream analysis and annotation of UMAP clusters generated using batch-corrected data?
