### ISSUE TITLE
Mixscape issues. 

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#6626]
Dear Seurat team, 

I am trying to troubleshoot mixscape. 
To run 'Calculate perturbation signature (PRTB)' function, I entered the following code: 

crispr <- CalcPerturbSig(
  object = crispr, 
  assay = "RNA", 
  slot = "data", 
  gd.class ="sgrna_symbol", 
  nt.cell.class = "sgrna_id", 
  reduction = "pca", 
  ndims = 40, 
  num.neighbors = 20, 
  split.by = "channel", 
  new.assay.name = "PRTB")

I got the following error: 
Processing 1
Error in nn2(data = numeric(0), query = c(13.8771946372216, -5.71075258395218,  : 
  Cannot find more nearest neighbours than there are points

I am able to run the test eccite data from seuratdisk. I try to look around myself first before asking here. 
The seurat object here is crispr. I am able to do much of the other seurat functions on this object. But since the data is from a crispr-seq screen, it would have been good to determine which cells escaped KO. Any help would be greatly appreciated. Thanks a lot.

**Comment by nmalwinka** [comment]
I had that error too. I fixed that by combining several negative controls together (non-targeting gRNA cells + cells transfected with negative control gRNA that targets a non-expressed gene) as it seems there were not enough control cells.

**Comment by kasumaz** [comment]
@nmalwinka Thanks a lot. I will check it out and hope it does the trick. I can mention something here tomorrow when I check it out again :)

**Comment by mhkowalski** [comment]
Yes, I would check that you are labeling the NT cells correctly. The argument  `nt.cell.class` should specify the non-targeting gRNA cell classification identity. Are your NT cells labeled as "sgrna_id"? For instance if the value of "sgrna_symbol"  that corresponds to the control cells is "non-targeting", you should specify `nt.cell.class = "non-targeting"`. 

You can check the function documentation [here](https://satijalab.org/seurat/reference/calcperturbsig) as well. Please write back to us if you have additional questions.
