### ISSUE TITLE
is there any way to remove ribosomal genes from the scRNA seq data? 

### ISSUE THREAD

**Issue by rimanpreetkaur** [satijalab/seurat#6628]
I tried to regress out while scaling but it still showing in my data, is there any way to get rid of ribosomal genes and non-coding genes

**Comment by longmanz** [comment]
Hi,
When you say it is still "showing" in your data, are you saying it affects your UMAP/clustering? If it is the case, could you show an example? 
As for "getting rid of" ribo-genes and nc-genes, I assume you want to get rid of their impact from your down-stream analysis. One thing you can do is after you run your FindVariableFeatures(), you explicitly remove any ribo-gene and nc-gene you do not want from your variable gene list. You can reset your variable gene list by `VariableFeatures() = features_removed_ribo_nc` . If you then proceed to your downstream analysis (ScaleData, RunPCA, RunUMP, etc.), you should not see effect from the genes you have removed.
