### ISSUE TITLE
Demultiplexing HTO

### ISSUE THREAD

**Issue by plumpaper551** [satijalab/seurat#6629]
Hi, 

I am trying to demultiplex my CITEseq data by MULTIseqDemux().
My data set includes Totalseq Ab (130 antibodies), Hashtag Ab (2 antibodies), and RNA information.
I set default assay with "HTO", and ran MULTIseqDemux(), but, I see Totalseq Ab and Hashtag combination in "MULTI_classification" column in meta.data. So, almost all the cells were annotated as "Doublet".
I want to classify cells only using Hashtag information. How can I do that?

Here are codes I used.
#Load the libraries
library(Seurat)
library(ggplot2)
library(patchwork)
library(tidyverse)

pbmc10k.data <- Read10X(data.dir = "data/filtered_feature_bc_matrix/")
rownames(x = pbmc10k.data[["Antibody Capture"]]) <- gsub(pattern = "_[control_]*TotalSeqC", replacement = "",
                                                         x = rownames(x = pbmc10k.data[["Antibody Capture"]]))
pbmc10k <- CreateSeuratObject(counts = pbmc10k.data[["Gene Expression"]], min.cells = 3, min.features = 200)
pbmc10k <- NormalizeData(pbmc10k)

#Find and scale variable features
pbmc.hashtag <- FindVariableFeatures(pbmc10k, selection.method = "mean.var.plot")
pbmc.hashtag <- ScaleData(pbmc.hashtag, features = VariableFeatures(pbmc.hashtag))

#Add HTO data as a new assay independent from RNA
pbmc.hashtag[["HTO"]] <- CreateAssayObject(pbmc10k.data[["Antibody Capture"]][, colnames(x = pbmc10k)])
#Normalize HTO data, here we use centered log-ratio (CLR) transformation
pbmc.hashtag <- NormalizeData(pbmc.hashtag, assay = "HTO", normalization.method = "CLR", margin = 2)

#Default Assay
DefaultAssay(pbmc.hashtag) <- "HTO"
pbmc.hashtag <- MULTIseqDemux(pbmc.hashtag, assay = "HTO", quantile = 0.7,
              autoThresh = FALSE,
              maxiter = 5,
              qrange = seq(from = 0.1, to = 0.9, by = 0.05),
              verbose = TRUE) 

#Group cells based on the max HTO signal
Idents(pbmc.hashtag) <- "HTO_maxID"
RidgePlot(pbmc.hashtag, assay = "HTO", features = rownames(pbmc.hashtag[["HTO"]])[142:145], ncol = 2)
view(pbmc.hashtag@meta.data)

**Comment by longmanz** [comment]
Hi, 
If I understand it correctly, you may need to keep a record of your TotalSeqC row.names as well as your Hashtag row.names first, and create assay objects for them separately. For example, after running Read10X(), you may:
`totalseq_id = grep(pattern = "[control]*TotalSeqC", 
x = rownames(x = pbmc10k.data[["Antibody Capture"]]))`
`hashtag_id = grep(pattern = "[control]*TotalSeqC", 
x = rownames(x = pbmc10k.data[["Antibody Capture"]]), invert = TRUE)`

And then when you are creating HTO assay, you just include the hashtag_id:
`pbmc.hashtag[["HTO"]] <- CreateAssayObject(pbmc10k.data[["Antibody Capture"]][hashtag_id, colnames(x = pbmc10k)])`
You can then generate a new assay for your totalseq:
`pbmc.hashtag[["TTS"]] <- CreateAssayObject(pbmc10k.data[["Antibody Capture"]][totalseq_id, colnames(x = pbmc10k)])`
You can then demultiplex either HTO or TTS assay separately.

**Comment by plumpaper551** [comment]
Thank you for your comment!
How can I annotate particular markers as totalseq_id or hashtag_id?
e.g. how can I annotate Hashtag-1 and Hashtag-2 as "hashtag_id" and otherwise (e.g. CD4 and CD8) to "totalseq_id"?
