### ISSUE TITLE
FindAllMarkers gives different marker genes in Seurat v 4.2.0 and v.4.1.1.

### ISSUE THREAD

**Issue by nmalwinka** [satijalab/seurat#6630]
Hi, 
I have the same Seurat object and calculated marker genes using FindAllMarkers for each group. In version 4.1.1. I got 198 Marker genes, in newer version (4.2.0) using the same command I got 31 genes. What has changed? 
Also, which assay is more appropriate to find markers- RNA or SCT?

Many thanks.

**Comment by timoast** [comment]
Can you show the full code you're using?

**Comment by samuel-marsh** [comment]
@timoast posted reprex in similar issue #6586

**Comment by samuel-marsh** [comment]
See #6586.  Seurat 4.2.1 fixes the issue.
