### ISSUE TITLE
Labelling cell types in DimPlot 

### ISSUE THREAD

**Issue by abhisheksinghnl** [satijalab/seurat#6631]
Hello Community,

I am sorry to post this question and I assume it is a fairly easy for most of you guys.

So, I have a seurat object and its metadata look like this

![image](https://user-images.githubusercontent.com/20971751/199516818-7759c71c-f4e9-4ddf-9325-079546e2a318.png)

and when I use DimPlot to get the clusters and labels I still see the labels of Seurat clusters instead of Cell Types
DimPlot(srat)

![image](https://user-images.githubusercontent.com/20971751/199517291-dfa16f3f-f197-4e45-a6e4-02b328cc204e.png)

I am missing something but what I am unable to figure out.

Thank you

**Comment by jarchana09** [comment]
Hello @abhisheksinghnl,
This may be helpful. First, you could try setting the identity of the Seurat object to the meta data column containing the cell type identities. For example, if the hpca.main column contains the celltypes of your interest:

```
Idents(srat) <- "hpca.main" 

#Visualization
DimPlot(srat)
```
#Additional option to visualize the plot with cell types labelled onto the clusters and exclude the separate legend 
```
DimPlot(srat, label = TRUE) & NoLegend()
```

Hope this helps.
Thanks.

**Comment by longmanz** [comment]
Thank you @jarchana09 !
