### ISSUE TITLE
FindMarkers not identifying genes that pass logfc.threshold 

### ISSUE THREAD

**Issue by sfhill** [satijalab/seurat#6633]
Hi!

I've been using Seurat without issue for a few months, and suddenly this week (with the same data), I'm unable to use FindMarkers to identify differential gene expression between two groups. I run:

`DEG <- FindMarkers(combined,
                   ident.1='WT',
                   ident.2='Chronic',
                   logfc.threshold=0.25, 
                   test.use="wilcox",
                   assay="integrated")`

And the output is: 

`Warning message:
In FindMarkers.default(object = data.use, slot = data.slot, counts = counts,  :
  No features pass logfc.threshold threshold; returning empty data.frame`

When I look at the fold change of individual genes I've previously identified as differentially expressed using:

`AverageExpression(combined, features='Slc1a2')`

I can see that the same genes have log2FCs larger than 0.25. I haven't changed my code or the dataset I'm putting in, so I'm not sure what the issue is. I have also tried uninstalling and reinstalling Seurat.

**Comment by jarchana09** [comment]
Hello. Not sure if this will help, but based on my understanding the Seurat team suggests using the RNA assay for differential expression testing, or the SCT assay if SCTransform v2 was used for normalization, and not the integrated assay (  [https://github.com/satijalab/seurat/issues/1717#issuecomment-504458665](https://github.com/satijalab/seurat/issues/1717#issuecomment-504458665) ;  [https://github.com/satijalab/seurat/discussions/4032](https://github.com/satijalab/seurat/discussions/4032) ; [https://github.com/satijalab/seurat/discussions/4000](https://github.com/satijalab/seurat/discussions/4000)   )

**Comment by longmanz** [comment]
Hi @sfhill , 
1. It is not clear to me what caused the difference? Have you updated your Seurat during the time? You may lower your logfc.threshold to 0.1 and see if you can see DE gene 'Slc1a2'. 

2. Thanks @jarchana09 for the explanation. Yes, it is not advised to use integrated assay to perform DE test. This has been discussed by many previous threads. For example, you may see discussion here: https://github.com/satijalab/seurat/discussions/4000

**Comment by sfhill** [comment]
I'm also not sure what caused the difference. I haven't touched Seurat since the last time the code worked, and I'm using the same data. The only change I've made is to install some other R packages, but those aren't even loaded into R and deleting them didn't solve the issue.

I have tried lowering the logfc.threshold, and I can get p-values - but the FC values are still way off from what I can see they should be. Using the RNA assay gives me differentially expressed genes with lof2FC > 0.25, but it's still not the same list I've gotten previously. Do you have any idea what could have changed?

I've been using a different package to perform the differential expression (presto) in the meantime and that is working fine. I'm really not sure what's wrong!

Thanks!
