### ISSUE TITLE
Average Expression on Integration data with scale.data slot not writing all the genes

### ISSUE THREAD

**Issue by devenderarora** [satijalab/seurat#6635]
Hello,

I am trying to get an average expression from integrated seurat objects with scaled data and  

The seurat object are: 

**seurat_obj**

 `$CC3A
An object of class Seurat 
33538 features across 28141 samples within 1 assay 
Active assay: RNA (33538 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap

$CC3B
An object of class Seurat 
33538 features across 43136 samples within 1 assay 
Active assay: RNA (33538 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap

$CD10
An object of class Seurat 
33538 features across 56396 samples within 1 assay 
Active assay: RNA (33538 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap

`
I am trying to change the nfeatures function in _SelectIntegrationFeatures_ to include all the genes but couldn't get more than 3218 features.

`d10x_6sample.data_features <- SelectIntegrationFeatures(object.list = d10x_6sample.data, 
                                                        nfeatures = "33538")`
length(d10x_6sample.data_features)
3218 
```
integration.anchors <- FindIntegrationAnchors(object.list = d10x_6sample.data, 
                                              normalization.method = "LogNormalize", 
                                              anchor.features = d10x_6sample.data_features, 
                                              verbose = FALSE)
```
I also tried to integrate the data as suggested by [post](https://github.com/satijalab/seurat/issues/3916#issuecomment-764770788)
and also with all the genes from one seurat object but still limited to max 3218 genes.

```
d10x_6sample.data.integ_git_allgenes <- IntegrateData(anchorset = integration.anchors, 
                            normalization.method = "LogNormalize", 
                            features.to.integrate = **all.genes**,
                            verbose = FALSE)
```

May I know a possible way to work around and get the average expression for all the genes from integrated seurat object using scale.data slot.

Thanks,
Devender

**Comment by timoast** [comment]
I would not recommend using all the genes for `anchor.features`, and it doesn't sound like that's actually what you want here anyway. 

The `features.to.integrate` parameter controls what genes corrected expression values will be computed for. Setting this to a vector containing all genes should return an integrated assay containing all of those genes, can you provide a reproducible example where that doesn't work?

**Comment by timoast** [comment]
Closing this since we haven't heard back
