### ISSUE TITLE
`TransferData` to find non-dominant cell types in spatial data

### ISSUE THREAD

**Issue by jad362** [satijalab/seurat#6636]
Hi-

I am looking to analyze a Visium object and have single cell data to deconvolute the cell types in each spot. While single cell data highlights heterogeneity in cell types (like immune cells), spatial signatures are dominated by the tissue expression profile. I was wondering if it was possible to tinker with the `FindTransferAnchors` or `TranferData` functions to prioritize the identification of cell types that are not part of the dominant baseline transcriptional signature. Alternatively, could I decrease the effect of low-variance genes in this process?

Thanks!
Joe

**Comment by timoast** [comment]
If there are some genes that have a high background expression level in the spatial data that you want to exclude from the anchor-finding, you could try removing these from the list of anchor features used (the `features` parameter in `FindTransferAnchors()`)
