### ISSUE TITLE
Seurat 2.2

### ISSUE THREAD

**Issue by twillafup** [satijalab/seurat#6637]
I have output created from the Optimus pipleine on Terra and am trying to duplicate a workflow that was develkoped with Seurat 2.2. I currently have Seurat version 4.x installed.

How can I "downgrade" my existing Seurat or at least install v2 in parallel?

Pipeline: https://app.terra.bio/#workspaces/featured-workspaces-hca/HCA_Optimus_Pipeline.

Right now, I'm trying to create a Seurat object using `Read10X`: The folder has 3 needed files and am getting: Error in `Read10X("~/Fieldwork/fieldwork_data/output/", gene.column = 2, : Barcode file missing. Expecting barcodes.tsv.gz`

Would installing Seurat 2.2 fix the error? Or is there a way in Seurat 4 to make it work?

Thanks

**Comment by longmanz** [comment]
Hi, 
If you want to install old(er) versions of Seurat, please refer to this page: https://satijalab.org/seurat/articles/install.html 

Regarding the error you encountered, I am not sure which version of Cellranger you used for your 10x dataset. Are the 3 needed files gzipped? You may refer to this thread for more information: https://github.com/satijalab/seurat/issues/643
