### ISSUE TITLE
Technical issues in Scaledata

### ISSUE THREAD

**Issue by aquiilla** [satijalab/seurat#664]
Hi,
I have a problem when scaling the data. As in an attached image, the display shows the percentage of regressing out as 0%, which did not increase from 0.
I would appreciate it if you could give me any advice. R version is 3.4.1. Thanks!
<img width="1055" alt="screen shot 2018-07-27 at 12 26 05 am" src="https://user-images.githubusercontent.com/36237304/43289987-48cc8c6c-9135-11e8-823e-7bc62cd12976.png">

**Comment by leonfodoulian** [comment]
Hi,

Could you please share your `sessionInfo()`? I tried to run the exact same command lines as you did, and it worked fine for me. 

Best,
Leon

**Comment by aquiilla** [comment]
Hi Leon,
Thank you for the prompt reply. Here is my sessioninfo(). 
<img width="2553" alt="screen shot 2018-07-27 at 9 58 50 am" src="https://user-images.githubusercontent.com/36237304/43306589-5686311a-9184-11e8-9d1b-7201ffd423ca.png">

**Comment by leonfodoulian** [comment]
Hi @aquiilla,

I am not sure why is this happening. For how long have you waited for the algorithm to run? Also, did you notice any CPU or memory overload when the function was running?

Best,
Leon

**Comment by aquiilla** [comment]
Hi Leon, I reinstalled macOS, R and now everything is fine. Thanks for your help! Best, Akira

**Comment by rgranit** [comment]
I have this very same problem, yet re-installing R won't help.. any suggestions?

**Comment by mschilli87** [comment]
@rgranit:
> re-installing R won't help.. any suggestions?

@aquiilla wrote
>  I reinstalled macOS

:wink:

**Comment by rgranit** [comment]
@mschilli87 

Thanks.. yes, I noticed 😉 but figured that this also included re-installing R.. Anyway, I'm currently open to any suggestions that would not involved re-installing macOS 😁

**Comment by evolvedmicrobe** [comment]
Is it using CPU (check activity monitor) or did it just freeze?

**Comment by leonfodoulian** [comment]
@rgranit,

I would rather agree with @evolvedmicrobe in checking the CPU usage. What I often encountered when my machine was quite busy is that it took some time before the function (`Seurat::ScaleData()`) got executed, but never more than 1-2 minutes of wait. 

Best,
Leon

**Comment by mschilli87** [comment]
@rgranit:
> Anyway, I'm currently open to any suggestions that would not involved re-installing macOS

How about installing GNU/Linux? :wink:

Joking aside: I'm not familiar with macOS but I guess it has (h)top so you could check the state of the process when it get's 'stuck', if this is `R`, just wait a little as suggested above.

**Comment by leonfodoulian** [comment]
I think it could be related either to the `foreach`, `doSNOW` or `parallel` packages that handle parallel processing in `Seurat`, as these are common to both functions. Note that even if you run the function on a single core, an independent cluster (or R session) is launched for the execution of the sub-functions implemented in `Seurat::ScaleData()` and `Seurat::JackStraw()`. This being said, I really don't know why is this happening, as both function run properly on my end. Maybe you could check compatibility between the versions of these packages, and your OS version?

**Comment by rgranit** [comment]
@leonfodoulian I'm using MacOS 10.13.6 - how do I check the compatibility of  the `foreach`, `doSNOW` or `parallel` packages with this version?

**Comment by sunnytsoiwave** [comment]
@rgranit 
Hi, I experience the same problem but my stupid institutes' spyware doesn't allow me to reinstall or update my OS. Have you found any fix?

**Comment by rgranit** [comment]
@sunnytsoiwave the solution I found was running the analysis on another computer with more RAM..

**Comment by sunnytsoiwave** [comment]
@rgranit  thanks for the reply.
but my computer already has 16GB RAM

**Comment by rgranit** [comment]
With large sets that might not be enough.. one of my files took >60GB of
ram to run

**Comment by sunnytsoiwave** [comment]
@rgranit

I used to run all the analysis on my computer. They are not big datasets. I even tried to rerun some dataset that I had run. Still got stuck at 0%.

**Comment by sunnytsoiwave** [comment]
I even tried running sudo R and run the script in console. Same.

**Comment by MichaelPeibo** [comment]
I got the same problem, my system is Ubuntu 16.04.

**Comment by CSBioAzim** [comment]
use gc() to clean up your memory from garbages
