### ISSUE TITLE
FindMarkers( ) and FindAllMarkers( ), I'm not sure whether to perform differential analysis on all features or highly variable features.

### ISSUE THREAD

**Issue by M-jk22** [satijalab/seurat#6641]
In the process of analysis, I always had a question. For the above two functions, Their input data is counts, normalized data, or scaled data. These two functions are used to analyze the difference of all genes or highly variable genes.

**Comment by lucygarner** [comment]
I am not one of the developers, but all genes will be analysed (if they are not filtered by the arguments in the `FindMarkers` function e.g. `min.pct`).

**Comment by MaJiakang** [comment]
https://github.com/satijalab/seurat/issues/6641#issuecomment-1304908033

Thank you, Professor. Your answer gives me a deeper understanding of the two functions. Indeed, the default input data of the two functions is normalized data.

**Comment by saketkc** [comment]
The input to `FindMarkers/FindAllMarkers` is normalized data. You can pre-select the genes to run the tests on using the `logfc.threshold` and `pct.1` thresholds. See [documentation](https://satijalab.org/seurat/reference/findmarkers) for details.
