### ISSUE TITLE
how to open scRNA .tsv.tmp file in seurat

### ISSUE THREAD

**Issue by rimanpreetkaur** [satijalab/seurat#6642]
I am trying to retrieve the scRNA data from (GSE158769), they submitted in .tsv format. and it gave .tmp file after extraction. does anyone know who to open .tmp files in seurat and how to analyse these fiile in seurat

how to make seurat object from these files.

**Comment by timoast** [comment]
It looks like your file was not completely downloaded, which is the reason for the .tmp extension

**Comment by rimanpreetkaur** [comment]
It was completely downloaded.

**Comment by timoast** [comment]
Looking at the files on GEO, they should end in `.tsv.gz`, not `.tmp`. `.tmp` usually indicates a partially downloaded file

**Comment by rimanpreetkaur** [comment]
Yes, when i extracted or unzip the file, then it generated .tmp file.
I shared the screenshots with you, after extraction, it gave exprs_raw.tsv.gz.tmp file after complete extraction. I used winrar and 7 zip tools.
![79D34CEE-898E-4196-BD78-52572F112652](https://user-images.githubusercontent.com/91835754/201428894-e27bad2b-e476-4441-ae41-7549ab271464.jpeg)

**Comment by rimanpreetkaur** [comment]
![CFFBE7FC-F5DF-49C1-9387-61F898E283EF](https://user-images.githubusercontent.com/91835754/201428944-4f70db5e-507a-4b91-b392-0074f63d7f1a.jpeg)
