### ISSUE TITLE
Single cell seurat cluster missing after integration with spatial seurat object from 10X Visium

### ISSUE THREAD

**Issue by nancyliy** [satijalab/seurat#6643]
I followed the tutorial vignette to perform integration of spatial seurat object with single-cell RNAseq data. However I noticed certain seurat clusters were dropped out from the prediction assay. 

Attached two independent example codes and outputs here display the scRNAseq seurat clusters used for integrating with spatial seurat object. However, upon integration, the highlighted clusters went missing and turned into 0 in prediction score and meanwhile there is a new seurat cluster named "max" appeared when calling `SpatiallyVariableFeatures()` and got plotted in the `SpatialFeaturePlot`. We have not been able to generate `SpatialFeaturePlot` for the missing seurat clusters "Macrophage_1", "Endothelial_cells" from one dataset and "P_MyoFb" seurat cluster from another independent dataset. Both cases we had the mysterious "max" cluster being added instead.

Please kindly look into this and help to troubleshoot.
[Spatial seurat script.pdf](https://github.com/satijalab/seurat/files/9944803/Spatial.seurat.script.pdf)
[output bug 1.pdf](https://github.com/satijalab/seurat/files/9944804/output.bug.1.pdf)
[output bug 2.pdf](https://github.com/satijalab/seurat/files/9944805/output.bug.2.pdf)
[output bug 3.pdf](https://github.com/satijalab/seurat/files/9944806/output.bug.3.pdf)
[output bug 4.pdf](https://github.com/satijalab/seurat/files/9944807/output.bug.4.pdf)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
