### ISSUE TITLE
Include a warning in `RunPCA` if not all of the variable features are present in the scale.data slot

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#6646]
Hi,

I am running the SCTransform workflow. I was manually replacing the genes in the variable features slot and then running PCA, but I didn't realise that some of the variable features were not being used for PCA, since they were absent in the scale.data slot.

This is explained in the `RunPCA` documentation as below but there is no warning when you run the function to indicate that not all of the variable features are being used for PCA.

> Note that the features must be present in the scaled data. Any requested features that are not scaled or have 0 variance will be dropped, and the PCA will be run using the remaining features.

Adding a warning might help others to realise this.

Best wishes,
Lucy

**Comment by lucygarner** [comment]
My workaround to fill in the missing data is described here: #6645. Does this seem reasonable?

**Comment by rsatija** [comment]
You should use GetResidual to accomplish this. I agree that it can be confusing when doing a custom variable gene set, but I also think a warning message might be  confusing to many users (sometimes a feature can be missing from the scale data slot even when not setting a custom list of features - for example if its present in a rare set of cells and that set of cells is subsetted out - and a warning message would be confusing to users). We'll keep things as they are but appreciate the thoughtful feedback
