### ISSUE TITLE
UMAP without previous dimension reduction

### ISSUE THREAD

**Issue by EliseAld** [satijalab/seurat#665]
Hello,

I am wondering if there is a way to run  the RunUMAP() function before running pca or ica or any other dimension reduction method beforehand, ie just writing RunUMAP(data) or RunUMAP(data, reduction.use = "umap") ?
It didn't work yet for me but since UMAP is also used for dimension reduction, just wanted to ask if it was possible to do so with Seurat.

Thanks for the help !
Elise

**Comment by romanhaa** [comment]
From the description of `RunUMAP()`:

`genes.use`: If set, run UMAP on this subset of genes (instead of running on a set of reduced dimensions). Not set (NULL) by default.

**Comment by EliseAld** [comment]
It works, thanks !

**Comment by joonlee3** [comment]
For Seurat v3.0, how do we run UMAP without previous dimension reduction such as PCA? I am trying to use RunUMAP with highly variable genes.

**Comment by mojaveazure** [comment]
@joonlee3 Set `dims = NULL`, and pass the features you want to run UMAP on to the `features` argument of `RunUMAP`

**Comment by joonlee3** [comment]
When I use features, then I've got the following error

`Error in RunUMAP.Seurat(object = seurat.raw, dims = NULL, features = features.raw,  : 
  formal argument "features" matched by multiple actual arguments`
