### ISSUE TITLE
Error in converting loom to Seurat 

### ISSUE THREAD

**Issue by woodylxf** [satijalab/seurat#6651]
Hi, 
    I am trying to convert a loom file to Seurat object with the codes from the tutorial
`loom <- Connect(filename = "../data/data.loom", mode = "r")`
`DATA <- as.Seurat(loom)` 
    but got this error:

Reading in /matrix
Warning: Duplicate feature names found, making unique
Storing /matrix as counts
Saving /matrix to assay 'RNA'

**Error in args_regularity_evaluation(args = args, ds_dims = simple_extent$dims,  : 
  Number of arguments not equal to number of dimensions: 1 vs. 2**

Any suggestions? Thanks a lot!

**Comment by yuhanH** [comment]
You have a try on this package, sceasy https://github.com/cellgeni/sceasy which can convert different single-cell data formats.
