### ISSUE TITLE
CellCycleScoring

### ISSUE THREAD

**Issue by dp9090** [satijalab/seurat#6656]
Hi, regarding the CellCycleScoring function, can it be also adapted for cell identification as well? In place of the S, g2m features, can we use other cell markers as features?

In general, what's the best way to perform cell identification then? Based on some heatmap and manual annotation of seurat clusters? Or could we use this somewhat semi-automated way of assigning identities to the cells?

**Comment by martin-jeremy** [comment]
Yes you can, CellCycleScoring is just a wrapper that use : 

1/ AddModuleScore function() based on s.features and g2m.features.
2/ Assign state based on the score.

**Comment by dp9090** [comment]
Apologies, I'm a beginner here. Could you explain how the assigning function works?

And it seems that when I separate the cells based on manual annotation of the seurat clusters by featureplot,
I have some cells that may differ when compared to using this scoring function.
