### ISSUE TITLE
The number of DEGs in low proportion cluster

### ISSUE THREAD

**Issue by dahun73** [satijalab/seurat#6658]
Hello :)

I have one quick question about the result of DE analysis.

Actually, I performed DE analysis between control and case samples for each cluster. After that, I checked the number of DEGs for each cluster. I realized that there are many DEGs in low proportion cluster. 

![image](https://user-images.githubusercontent.com/52641420/200757055-a6903b23-e2ae-49da-b451-ff3285323357.png)

My personal opinion is there may be some artifacts in this result. Is this result normal? What do you think about this? If not, is there any solution such as correction or normalization?

Thank you in advance!

**Comment by mhkowalski** [comment]
Hello,

I cannot say for sure without looking at your data and knowing the experimental design, but it is possible that this is an artifact. I can give a couple of brief suggestions of things to check: Have you integrated your data? Are there substantial batch effects between cases and controls? Have you checked to see if these clusters resemble cell types that you believe? For example, if you see genes that should be cell type markers coming up as differentially expressed within your smaller clusters, this might suggest the input clustering should be modified. Ideally, each cluster should reflect the same cell type for both case and control samples.

Hope this is helpful.
