### ISSUE TITLE
Adding global title option to CombinePlots

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#6659]
Did #1568 ever get implemented? "suptitle" would be a great addition.

**Comment by samuel-marsh** [comment]
Hi,

So I believe CombinePlots is soft-deprecated in favor of independent use of patchwork package which offers much greater flexibility and control of plot assembly.  The basic function of `CombinePlots` can be accomplished with patchworks `wrap_plots` and annotation of the plot assembly can be done using `plot_annotation`.  More details here: https://patchwork.data-imaginist.com/articles/guides/annotation.html

Best,
Sam

**Comment by timoast** [comment]
Yes,  we recommend other ways of achieving this, like using patchwork or ggpubr

**Comment by lucygarner** [comment]
Thank you, I used `wrap_plots` as follows. However, it was still necessary to use `combine = FALSE` and add `plot_annotation` to generate an overall title. Or is there an easier way to do this?

```
multi_feature <- function(seurat_object, 
                          plot_title, 
                          plot_features) {
    print(wrap_plots(FeaturePlot(seurat_object, 
                                 features = plot_features, 
                                 combine = FALSE)) +
              plot_annotation(
                  title = plot_title, 
                  theme = theme(
                      plot.title = element_text(
                          face = "bold", size = 18, hjust = 0.5))))
```

**Comment by lucygarner** [comment]
Great, thanks very much.
