### ISSUE TITLE
Tracing the gene expression pattern in development

### ISSUE THREAD

**Issue by fereshtehizadi** [satijalab/seurat#666]
Excuse me, this is not an issue with this nice package rather my biggest confusion after working with seurat for a month. 
I am working on Dictyostelium developmental stages. sampling for single cell RNA-seq has been done in 8 time points (2, 4, ...,16 hours). Text books say that we should be able to see roughly two groups of cell types toward the development. By Seurat and clustering resolution 0.7, I have clustered the last time point (16 hours) to 3 clusters (figure). 

[

![](https://image.ibb.co/mGtNDo/Untitled.png)
](url)
There are some experimentally validated marker genes for cell types in this organism by which I see that in 16 hour time point I really have two groups of cells. I am going back to 14 hour , 12 hour, .., 2 hour time points to see whether genes describing each time point are the same during the time or not, in the other word how development works in this organism but I totally don't know how to do that.

You imagine for each time point I have clustered my cells independently by seurat that gave me roughly 2 or 3 clusters of cells in each time point and marker genes for each cluster as well.

For example this is markers of time point 16 hours

[

![](https://image.ibb.co/nu7JKT/Untitled.png)
](url)

The question is this; how could I visualise the temporal expression of genes in each cluster of each time point in before or after time point (during the development)? For example I have three clusters in 16 hour time point, how could I know the expression pattern of descriptive genes in each cluster of time point 16 in another time points? either the genes describing each cluster in each time point are the same during the development of not? if not how to visualise the possible relationship among descriptive genes in each cluster during the time points...

**Comment by AndyR2** [comment]
Try using URD, plot axial.tree function
Farrell et al., Science 360, 979 (2018)

**Comment by fereshtehizadi** [comment]
Sorry URD paper gives a supplementary file describing the methods but I could not find any git or R package for URD. Do you know R package or vignette of URD please?

**Comment by AndyR2** [comment]
Its right here at GitHub.  
https://github.com/farrellja/URD

**Comment by AndyR2** [comment]
Here are links as last few lines of the paper:

[cid:image001.jpg@01D437B9.0D1DC800]

**Comment by fereshtehizadi** [comment]
Thank you

**Comment by fereshtehizadi** [comment]
Sorry, I have just read these to papers but likely there is not any git or package and all has been described in methods. so how we can run the methods used in these two papers on my data?

http://science.sciencemag.org/content/early/2018/04/25/science.aar5780

http://science.sciencemag.org/content/early/2018/04/25/science.aar4362

**Comment by satijalab** [comment]
As previously suggested here, check out : https://github.com/farrellja/URD

By the way, Jeff Farrell (of URD- Farrell et al., Science 2018), also led the Seurat spatial mapping manuscript (Nat Biotech, 2015). He is the master of Space and Time.
