### ISSUE TITLE
Leidenalg error

### ISSUE THREAD

**Issue by marcomerg** [satijalab/seurat#6660]
Hi all,

I am on heart tissue single cell analysis, in particular on immune cell analysis through Seurat. When it comes to subclustering, I get an error message with the Leiden algorithm as follows: "Cannot find Leiden algorithm, please install through pip (e.g. pip install leidenalg)", even though I actually installed it previously. 

I tried to create a new conda environment and install all the packages I require, and start using the new environment. I think that what’s most likely to have happened is that I installed or updated some other packages, which is interfering with Leiden/Seurat dependencies and caused troubles in using the clustering function.

 Does anyone know what can fix this?

Many thanks in advance,
Marco

**Comment by alikhuseynov** [comment]
I would recommend to create new conda env from scratch, and install Seurat and related packages in there.
Then install `leidenalg `via `conda` or `mamba`
`conda install -c conda-forge leidenalg`
Or `mamba install -c conda-forge leidenalg`
Check the installed library
`conda list | egrep "leiden"`

Afterwards it should work in that conda new env.

```
## test
library(Seurat)
library(magrittr)
pbmc <- pbmc_small
pbmc %<>% RunPCA %>% 
ScaleData %>%
FindNeighbors(dims = 1:10) %>% 
FindClusters(algorithm = 4, resolution = 0.5)
pbmc$seurat_clusters %>% unique # check clusters
```

**Comment by mojaveazure** [comment]
Please install leidenalg using pip to install in your system's Python library in order for R to see it properly
