### ISSUE TITLE
Problem with Seurat library : Registered S3 method overwritten by 'SeuratObject':

### ISSUE THREAD

**Issue by Anthoprog** [satijalab/seurat#6661]
Hello everyone, I have a problem with seurat, when I try to launch : `library(Seurat)`, this problem appears:

`Registered S3 method overwritten by 'SeuratObject':
  method                from
  is.infinite.Centroids     
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratObject/libs/SeuratObject.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratObject/libs/SeuratObject.so, 0x0006): tried: '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratObject/libs/SeuratObject.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratObject/libs/SeuratObject.so' (no such file), '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratObject/libs/SeuratObject.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

I absolutely needs Seurat for my project and I don't know what to do, I'm a beginner in R studio.
Also if that precision can help, I'm running R studio on Mac Os.

**Comment by timoast** [comment]
Can you try reinstalling Seurat and see if you still have this error?

**Comment by timoast** [comment]
Closing since we haven't heard back
