### ISSUE TITLE
Pull gene expression from UMAP based on orig.ident

### ISSUE THREAD

**Issue by varshi02** [satijalab/seurat#6663]
Hi all, 

I would like to make a bar graph or something similar in which I visualise the gene expression of a certain gene in each cluster and from which dataset it comes from. 

E.g. I have a merged dataset from 3 different conditions and I want to know how much gene1 is expressed in cluster 1, (which I know how to show)

But then I also want to know how many cells from each of the three conditions express gene1 in Cluster 1. I would like this for all my clusters. Does anyone know how to do this?

Thank you guys in advance!

**Comment by torkencz** [comment]
I would just use FetchData to pull your normalized expression data for each of your conditions and clusters and then make a dataframe where you combine these. You can also just subset to each of your clusters and make a violin plot where you group by condition.
