### ISSUE TITLE
DimPlot graph without titles

### ISSUE THREAD

**Issue by aaz398** [satijalab/seurat#6664]
Hi,

I am trying to produce a DimPlot graph without labels/titles corresponding to my different "identities". 

For instance, in the image below from https://satijalab.org/seurat/reference/dimplot, I would like to remove the titles 0, 1, and 2 above the individual UMAP plots. I haven't been able to find ggplot2 or DimPlot functions which can do this. What am I missing?

Thanks so much.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/86684789/201227664-41c41e46-72ea-4896-b8a6-b6222e08e3d1.png">

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You should be able to use standard ggplot2 theming for this.  You will also have to use patchwork notation due to multiple plots.

```
DimPlot(…) & theme(plot.title = element_blank())
```

Best,
Sam
