### ISSUE TITLE
Different FindMarkers results on 4.1 and 4.2 using MAST

### ISSUE THREAD

**Issue by Melissa-LS** [satijalab/seurat#6667]
Similar to issue #6586, I found different results when using FindAllMarkers in Seurat 4.1.0 and in the developer's version installed today (4.2.1). In my case, I was testing MAST (v 1.24.0) directly on the count matrix (not SCTransform results). For clarity, please see the code below:

MASTtest <- FindAllMarkers(SeuObj, assay = "RNA",  test.use = "MAST", latent.vars = "tech")

Could these two issues be related?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you post the full code you are running between 4.1.0 and 4.2.1?  If possible using reproducible example from SeuratData package (e.g., https://gist.github.com/samuel-marsh/d32b79421773587bce8be1feb78a5ab2)

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @Melissa-LS,

Please try updating to new CRAN of Seurat 4.3.  Two issues with `FindMarkers` have now been addressed since 4.2.0.  If your issue persists after updating please post here (with full code as suggested above) and I can reopen issue for Seurat team.

Best,
Sam

**Comment by Melissa-LS** [comment]
Thank you so much Sam!  and sincere apologies for the delay. I can confirm that Seurat 4.1 and 4.3 gave me the same results on Seurat data and with my own dataset. At a broad level, do you know what changed?
Best, Melissa
