### ISSUE TITLE
Change cell names of list of barcodes

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [satijalab/seurat#6669]
In my seurat object have a list of barcodes ~100 that have cell types assigned. I want to re-assign/rename these barcodes as another cell types. Is there a function to do this?

Thanks!

**Comment by f6v** [comment]
From the [docs](https://mojaveazure.github.io/seurat-object/reference/Idents.html):

```
# Set cell identity classes
# Can be used to set identities for specific cells to a new level
Idents(pbmc_small, cells = 1:4) <- 'a'
[head](https://rdrr.io/r/utils/head.html)(Idents(pbmc_small))
#> ATGCCAGAACGACT CATGGCCTGTGCAT GAACCTGATGAACC TGACTGGATTCTCA AGTCAGACTGCACA 
#>              a              a              a              a              0 
#> TCTGATACACGTGT 
#>              0 
#> Levels: a 0 1 2
```

**Comment by Gesmira** [comment]
@f6v's answer works to change the cell identities of the seurat object which can then be saved to a new metadata column:
`pbmc_small$cell_names <- Idents(pbmc_small)`. This is recommended if you're adding cell type labels. 
If you want to specifically change the the cell barcode, you can do that by changing the column names of the counts matrix using something like 
`colnames(pbmc_small)[1:5] <- c('a', 'b', 'c', 'd', 'e')` but note that you should keep the cell names unique so the first way is reccomended if you want to add the same cell type label to multiple cells.
