### ISSUE TITLE
Can DMPlot or DimPlot plot 3d diffusion map?

### ISSUE THREAD

**Issue by QiangShiPKU** [satijalab/seurat#667]
Can DMPlot or DimPlot plot 3d diffusion map?
I have tried that but fail.

**Comment by romanhaa** [comment]
Fail with what error message? Can you be more specific? If you are talking about a tSNE projection, you first need to calculate 3 dimensions by running `RunTSNE(..., dim.embed=3, ...)`. Afterwards you should be able to plot all three dimensions using `TSNEPlot()`.

**Comment by leonfodoulian** [comment]
@QiangShiPKU,

You cannot plot 3D plots with `Seurat::DimPlot()`. You can check this [web page](http://www.sthda.com/english/wiki/impressive-package-for-3d-and-4d-graph-r-software-and-data-visualization) for some examples on how to get 3D plots with R.

Best,
Leon

**Comment by satijalab** [comment]
you can also extract the underlying embeddings (using GetCellEmbeddings - example here https://satijalab.org/seurat/dim_reduction_vignette.html), and feed these into a 3d plotting function

**Comment by SLWOlsen** [comment]
I know this issue is closed now but I'm relatively new to R and  I've been trying to make a 3d CCA plot for a long time and I finally did it after seeing this post and the comment about extracting the underlying embeddings (Thank you!). I thought I'd leave a comment about what worked for me because as a new user I like to see explicit examples.  So here's what I did. 

library(rgl) #interactive 3d plotting

CCA1<-GetCellEmbeddings(object, reduction.type = "cca", dims.use = 1,
                  cells.use = NULL)
CCA2<-GetCellEmbeddings(object, reduction.type = "cca", dims.use = 2,
                        cells.use = NULL)
CCA3<-GetCellEmbeddings(object, reduction.type = "cca", dims.use = 3,
                        cells.use = NULL)

plot3d(x = CCA1, y = CCA2, z = CCA3, col=c(mycolors)[object@ident], type="s",radius=1, xlab = "CC1", ylab = "CC2", zlab = "CC3")

rgl::rglwidget()

**Comment by jriv724** [comment]
I know I'm a little late to the game, but here is a function I've developed for 3D plotting of seurat objects. 

For RunUMAP you will have to set n_components >= 3

` 
BiocManager::install('plotly')

library(plotly)
library(Seurat)
library(tidyverse)
library(dplyr)


S.O = seurat.object

S.O@reductions$pca@cell.embeddings
S.O@reductions$umap@cell.embeddings

getPcaUmapMetaData <- function(S.O){
  pc <- S.O@reductions$pca@cell.embeddings
  pc <- data.frame(pc) %>% mutate(Sample = rownames(pc)) %>% 
    transmute(Sample = Sample, PC_1 = PC_1 ,PC_2 = PC_2, PC_3 = PC_3, PC_4 = PC_4, PC_5 = PC_5, PC_6 = PC_6)
  umap <- S.O@reductions$umap@cell.embeddings
  umap <- data.frame(umap) %>% mutate(Sample = rownames(umap)) %>% 
    transmute(Sample = Sample, UMAP_1 = umap_1,umap_2 = umap_2, UMAP_3 = umap_3 )
  
  meta.data <- data.frame(Sample = rownames(S.O@meta.data), active.ident = S.O@active.ident)
  meta.data <- left_join(meta.data,
                         pc, by = 'Sample')
  meta.data <- left_join(meta.data, umap, by = 'Sample')
  return(meta.data)  
}

pca.tg <- getPcaUmapMetaData(S.O)

fig <- plotly::plot_ly(pca.tg, x = ~PC_1, y = ~PC_2, z = ~PC_3, color = ~active.ident)
fig <- fig %>% plotly::add_markers(size = .75)
fig <- fig %>% plotly::layout(scene = list(xaxis = list(title = 'PC_1'),
                                           yaxis = list(title = 'PC_2'),
                                           zaxis = list(title = 'PC_3')))

fig


umap.fig <- plotly::plot_ly(pca.tg, x = ~UMAP_1, y = ~umap_2, z = ~UMAP_3, color = ~active.ident)
umap.fig <- umap.fig %>% plotly::add_markers(size = .75)
umap.fig <- umap.fig %>% plotly::layout(scene = list(xaxis = list(title = 'UMAP_1'),
                                                     yaxis = list(title = 'UMAP_2'),
                                                     zaxis = list(title = 'UMAP_3')))

umap.fig`
