### ISSUE TITLE
Whichcell function for different idents

### ISSUE THREAD

**Issue by Elham-adabi** [satijalab/seurat#6671]
Hi, 
I am trying to  create a column in meta data based on expression of a gene, but I want to have different thresholds for my different samples, Using the following code: 

DefaultAssay(cart.combined) <- "ABSEQ"
Idents(cart.combined) <- "donor"
CARp <- 
WhichCells(object = cart.combined, expression =`CAR-P.Ab` > log1p(3.1) , idents = "D1")  %>%
WhichCells(object = cart.combined, expression = `CAR-P.Ab` > log1p(2) , idents = "D2") %>%
WhichCells(object = cart.combined, expression = `CD19:SJ25C1.Ab` < log1p(0.8124951))

Error in CellsByIdentities(object = object, cells = cells, ...) : 
  Cannot find cells provided

while without including idents, this works:
CARp <- 
  WhichCells(object = cart.combined, expression =`CAR-P.Ab` > log1p(3.1))  %>%
 WhichCells(object = cart.combined, expression = `CD19:SJ25C1.Ab` < log1p(0.8124951))

I cannot figure out what is the problem with the first code, I would appreciate your help.

Best, 
Elham

**Comment by timoast** [comment]
I'd suggest extracting the lists of cells separately for the different samples and combining them, eg:

```r
cells1 <- WhichCells(object = cart.combined, expression =CAR-P.Ab > log1p(3.1), idents = "D1")
cells2 <- WhichCells(object = cart.combined, expression =CAR-P.Ab > log1p(2), idents = "D2")
all.cells <- c(cells1, cells2)
```
