### ISSUE TITLE
`SplitObject` gives different answer than merged object

### ISSUE THREAD

**Issue by tbrunetti** [satijalab/seurat#6672]
Hello,

I am trying to understand why the `SplitObject()` function gave me a diffferent result then when the object is merged.  For example,I am performing a quantile level filtering on the number of features per sample.  I have checked the sample after filtering and performing a merged across all 4 data sets into a single seurat object:

For a single sample (donor1), I subset my data to apply a 1% quantile filtering to just that data set which results in a minimum value of `321` in the `nFeature_RNA` column.

I then merged all 4 filtered data sets into a single Seurat object called `filtered_data_object`.  When I check what the minimum `nFeature_RNA` value is for `donor`1 I still get `321` as expected.

```
min(filtered_data_object@meta.data[which(filtered_data_object@meta.data$donorID == "donor1"),"nFeature_RNA"])`
[1] 321
```

However, if I take this merged data object and split it using `SplitObject` that minimum value is now different:  
```
Idents(filtered_data_object) <- "donorID"
newSplit <- SplitObject(filtered_data_object, split.by = "ident")
min(newSplit[['donor1']]@meta.data$nFeature_RNA)
[1] 311
```

I have re-written and checked my code numerous times and I feel like I am going crazy but I must be missing something.  Can you please provide any insights on why this happens?

I am using `Seurat version 4.1.1`

Thanks!

**Comment by tbrunetti** [comment]
I think I figured it out.  I didn't apply any gene level filtering before I split the objects and it returns the same (expected) answer.  That means that the gene level filtering that results in changes to the metadata, **only take effect after splitting**, but if you never split, they will be unchanged

With that being said, I guess it is best to perform a gene level filtering first and then apply a cell level filtering since the quantiles will changes after applying gene level filters?

**Comment by saketkc** [comment]
Gene level and cell level filtering should ideally be performed on individual datasets (or batches or donors).
