### ISSUE TITLE
how to convert raw.tsv file to seurat object

### ISSUE THREAD

**Issue by rimanpreetkaur** [satijalab/seurat#6676]
I have downloaded raw.tsv.gz  file from from GSE158769 (10x) in .tsv format as the raw data, and want to convert it into Seurat object.

**Comment by rimanpreetkaur** [comment]
when I read it in R using read_tsv command it showed only gene sequence

**Comment by timoast** [comment]
```r
library(Seurat)
library(data.table)

counts <- data.frame(fread("~/GSE158769_exprs_raw.tsv", sep = "\t"), row.names = 1)
obj <- CreateSeuratObject(counts = counts)
```
