### ISSUE TITLE
Dot Plot: invalid character indexing following merging objects

### ISSUE THREAD

**Issue by Colin-med** [satijalab/seurat#6679]
I am trying to run a DotPlot having of multiple genes after having merged a few objects. VlnPlot(), FindMarkers(), AverageExpression() all work fine. However, when I run DotPlot()
DotPlot(Object, group.by="treatment", features = gene_of_interest) 
it returns
Warning: Could not find GENE in the default search locations, found in RNA assay instead
Error in intI(j, n = d[2L], dn[[2L]], give.dn = FALSE) : 
  invalid character indexing
In addition: Warning message:
In cells.idents["NA"] <- names(x = which(x = is.na(x = Idents(object = object)[cells]))) :
  number of items to replace is not a multiple of replacement length

**Comment by Xrmkm** [comment]
I actually encountered this too for one of my features. Though only for this line: "Warning: Could not find GENE in the default search locations, found in RNA assay instead." 

I wonder if others recommend against it, but I may just FindVariableFeatures() of all genes possible to include in the downstream analysis.

**Comment by lxsalama** [comment]
I've been dealing with this for 2 days and I think I've got it.
There are two different errors in here. One is irrelevant. 

The first warning:  Could not find GENE in the default search locations, found in RNA assay instead
Refers to the DefaultAssay which when you first make the merged Seurat object must be "integrated" to run scaling and nearest neighbor clustering. 
You set the place where it retrieves the assay data for these functions using the below code:
DefaultAssay(Seurat_object) <- "integrated"
You can check what is it set to using this:
DefaultAssay(object = Seurat_object)

When you make dotplots or violin plots for example it needs the assay results in "RNA" and can't use "integrated". The good thing here is that you don't actually have to set it back to "RNA". It will check the "integrated" assay results, not find the data it needs and switch to the "RNA" assay results. So this is a non-issue here.

The reason your code isn't running is the second error:
"invalid character indexing"
Upstream of this code block you should have run the PCA and UMAP commands on your newly merged Seurat object to get your clusters. 
If you're like me, you may have approached your dataset initially interested in only a handful of the cell.type clusters identified. I went and named those clusters and left everything else unnamed using the RenameIdents command.

The example from Seurat's pipeline is below:
Idents(immune.combined) <- factor(Idents(immune.combined), levels = c("HSPC", "Mono/Mk Doublets",
    "pDC", "Eryth", "Mk", "DC", "CD14 Mono", "CD16 Mono", "B Activated", "B", "CD8 T", "NK", "T activated",
    "CD4 Naive T", "CD4 Memory T"))
markers.to.plot <- c("CD3D", "CREM", "HSPH1", "SELL", "GIMAP5", "CACYBP", "GNLY", "NKG7", "CCL5",
    "CD8A", "MS4A1", "CD79A", "MIR155HG", "NME1", "FCGR3A", "VMO1", "CCL2", "S100A9", "HLA-DQA1",
    "GPR183", "PPBP", "GNG11", "HBA2", "HBB", "TSPAN13", "IL3RA", "IGJ", "PRSS57")
DotPlot(immune.combined, features = markers.to.plot, cols = c("blue", "red"), dot.scale = 8, split.by = "stim") +
    RotatedAxis()

If you don't name every cell cluster something then the assay return on the genes you identified won't match the Idents of the clusters in your seurat object. It's possible if you don't rename any of the clusters the command still works, but it makes the example pipeline harder to follow. I don't think keeping them as numbers works either for some reason. I finally settled on naming my clusters of interest and giving the other clusters letter place holders until I could go back and positively ID the cell.type.
Example:
Combined_seurat <- RenameIdents(Combined_seurat, `0` = "MuSC", `1` = "A", `2` = "B",
                                `3` = "C", `4` = "D", `5` = "E", `6` = "F", `7` = "G", `8` = "H", `9` = "I",
                                `10` = "J", `11` = "K", `12` = "L", `13` = "M", `14` = "N", `15` = "O", `16` = "P", `17` = "Q", `18` = "R")

Idents(Combined_seurat) <- factor(Idents(Combined_seurat), levels = c("MuSC", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L","M","N","O","P","Q","R"))
DotPlot(Combined_seurat, features = markers.to.plot, cols = c("blue", "red"), dot.scale = 8, split.by = "orig.ident") +
  RotatedAxis()
With that change it should work. I had trouble going back and naming every cluster after specifically renaming the handful, so you may need to go back and recreate your merged seurat object before doing this.

I've only being doing scSeq for a week, so someone with more experience please correct any errors here. Hope that helps.

**Comment by Xrmkm** [comment]
I commented on the first error e.g., finding the feature in the RNA instead of the integrated assay. I've come to understand that this does not mean the feature expression is invalid, but that the RNA assay may have expression information not selected in the Integrated assay slot. Thank you for chiming in!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
