### ISSUE TITLE
Batch corrected counts for downstream analysis

### ISSUE THREAD

**Issue by cutleraging** [satijalab/seurat#6680]
Hello Seurat team, I am working with a dataset that contains multiple experiments and has batch effects. I can use the SCTransform v2 and integration workflow to mitigate these effects.
![image](https://user-images.githubusercontent.com/84161843/202035355-72642ce2-f242-4e9c-84a1-3052bc565fe0.png)

I would now like to output a table of "batch-corrected" counts. I am able to get "corrected counts" by using 
```
obj <- PrepSCTFindMarkers(obj, assay = "SCT") 
counts <- GetAssayData(object = obj.stem.young, assay = "SCT", slot = "counts")
```

However, if I try to use these "corrected counts" to do cell clustering, I can still see the batch effect.

```
obj.new <- CreateSeuratObject(counts)
obj.new <- SCTransform(obj.new, vst.flavor = "v2", verbose = FALSE)
obj.new <- RunPCA(obj.new, npcs = 50, verbose = FALSE)
obj.new <- RunUMAP(obj.new, reduction = "pca", dims = 1:30)
```

![image](https://user-images.githubusercontent.com/84161843/202035149-e5b22fb0-c33b-4292-80d7-215e633a5516.png)

Though, it looks a little bit different from using the un-integrated counts.
![image](https://user-images.githubusercontent.com/84161843/202036113-0fc7e928-d3eb-469c-8375-24d4d1e9540c.png)

So, is it possible to output "batch corrected" counts from the workflow I am using and validate this by performing clustering using those counts? If not, what are the steps one can use to output "batch corrected" counts?

Thanks!

**Comment by alikhuseynov** [comment]
Hi there,
If I understand correctly, what you need are the corrected counts from `"integrated"` assay, not from `"SCT"`, ie after you used [`IntegrateData()`](https://satijalab.org/seurat/reference/integratedata)
eg using [this Seurat workflow](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1)

```
# eg, from Seurat workflow 
LoadData("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")
ifnb.list <- lapply(X = ifnb.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT", anchor.features = features)
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT") # this is batch-corrected object in "integrated" assay

# all cells with nfeatures from SelectIntegrationFeatures()
counts <- GetAssayData(object = immune.combined.sct, assay = "integrated", slot = "counts")
```
best

**Comment by cutleraging** [comment]
Hello  and  thanks for  that. Although it is clear that you did not test that code because there are no counts in the integrated assay. Here is how I got integrated data for all the genes.

```
# split the dataset
obj.list <- SplitObject(obj, split.by = group)

# normalize and identify variable features for each dataset independently
obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- SCTransform(x, vst.flavor = "v2", verbose = FALSE)
})

# select features that are repeatedly variable across datasets for integration
var_features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 3000)
obj.list <- PrepSCTIntegration(object.list = obj.list, anchor.features = var_features)

# get anchors using repeatedly variable features
anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = var_features, normalization.method = "SCT")

# select all features to integrate: https://github.com/satijalab/seurat/issues/2590
all_features <- lapply(obj.list, row.names) %>% Reduce(intersect, .)

# integrate using anchors from variable features but integrate ALL features
obj.integrate <- IntegrateData(anchorset = anchors, features.to.integrate = all_features, normalization.method = "SCT")
```

Although when I look at the data from this, I can see that it is centered around 0 and contains negative values. What I am looking for is a table of positive batch corrected counts for the downstream analysis I need to perform.
![image](https://user-images.githubusercontent.com/84161843/202317604-bbae5a8b-8ec4-4418-b8f1-e88c86fa6f4d.png)

**Comment by alikhuseynov** [comment]
Sorry about that, they are in `"scale.data"` slot
Anyhow, `"integrated"` assay is useful for clustering etc.. Any downstream analysis should be done on `"RNA"` or `"SCT"` assays
This issue #283 is related

If you only want batch-corrected count matrix, it's probably better to use some "regression–based" batch-correction methods.
Eg [`ComBat()`](https://rdrr.io/bioc/sva/man/ComBat.html), that returns the batch-corrected matrix.

best

**Comment by saketkc** [comment]
You can account for batchesn when running DE tests using the `test.use="LR"` or `test.use="MAST"` along with `latent.vars="batch"`. You should not use values from the integrated assay for DE testing.
