### ISSUE TITLE
add 'assay' parameter to FeaturePlot

### ISSUE THREAD

**Issue by rocanja** [satijalab/seurat#6681]
It would be great if the '**assay**' parameter could be added to the **FeaturePlot** function in a similar way to how it's available for VlnPlot, RidgePlot and DotPlot ... to enable easy plotting of features from custom assays in the seurat object. The current workaround is to reset the default assay with 'DefaultAssay(object = seurat) <- "custom"', but being able to specify the assay in the FeaturePlot call directly would be neater. Thank you for considering and thanks for this great package!

**Comment by saketkc** [comment]
Thank you for the suggestion. You can use the assay keys to do this. For example `sct_LYZ` will plot the data slot of `SCT` assay for `LYZ` gene.
