### ISSUE TITLE
find DE genes/markers or other downstream analysis after cell cycle regression 

### ISSUE THREAD

**Issue by lengfei5** [satijalab/seurat#6685]
Dear Seurat team, 

Thanks for such a great tool that we are all using in a daily basis.

Recently we got some scRNA-seq data with clear cell cycle signature.
We wanna regress out the cell cycle score. 

But, if I understand well, the regressed data will be saved in the scaled.data, 
in that case, how can I continue the downstream analysis, e.g.
- find the mark genes that is using 'data' instead of 'scaled.data '
- trajectory analysis with the regessed data. 

Many thanks.

**Comment by longmanz** [comment]
Hi,
The default Wilcos test in FindMarkers() does not support covariates. But you may use some alternative methods to do that, for example FindMarkers(test.use = 'MAST') (or 'LR', 'negbinom', 'poisson'). All of them support the 'latent.vars = ' flag which allows you to specify any covariate (cell_cycle_score) you want to fit in your DE test.

As for trajectory analysis, you may need to turn to other packages (e.g., monocle3) to do that.

**Comment by lengfei5** [comment]
Dear @longmanz,

Make sense and thank you for the answer.
