### ISSUE TITLE
Are there any ways to make the dots in a violin plot transparent?  

### ISSUE THREAD

**Issue by xsun1229** [satijalab/seurat#6689]
Hi all!

I am trying to make the dots representing cells transparent but have not found a method. 
Could anyone share some suggestions on it?

I tried to adjust it with geom_point(alpha=0.1) but only dots on the vertical line can be modified....

![Screen Shot 2022-11-16 at 11 25 45 PM](https://user-images.githubusercontent.com/62573051/202364665-d620d159-d10f-45df-b8f1-603cd232efbe.png)

Thanks a lot!
Miley

**Comment by alikhuseynov** [comment]
you could try to plot it like this:
```
pl1 <- VlnPlot(pbmc_small, pt.size = FALSE, features = "nCount_RNA", group.by = "groups") & geom_jitter(alpha = 0.1)
pl1
```

**Comment by xsun1229** [comment]
> you could try to plot it like this:
> 
> ```
> pl1 <- VlnPlot(pbmc_small, pt.size = FALSE, features = "nCount_RNA", group.by = "groups") & geom_jitter(alpha = 0.1)
> pl1
> ```

Thanks a lot! This works!

It seems I have too many dots. So I am wondering if there is any way to change the plotting order so that the violin plot is on top?

Thank you again!!

**Comment by alikhuseynov** [comment]
no worries,
Dirty solution:
```
pl1$layers <- pl1$layers %>% rev
pl1
```

**Comment by xsun1229** [comment]
> no worries, Dirty solution:
> 
> ```
> pl1$layers <- pl1$layers %>% rev
> pl1
> ```

Wow. It works perfect for me!
I appreciate your help!
