### ISSUE TITLE
Error in JackStrawPlot PC subset when 1 is not included

### ISSUE THREAD

**Issue by kvittingseerup** [satijalab/seurat#669]
For cases where a lot of significant PCs are found it could be nice to make multiple JackStrawPlots with subsets of the PCs - but JackStrawPlot() does not work when the range of PCs does not include 1. Specifically:

```R
JackStrawPlot(object = pbmc_small, PCs = 1:6) # works
```

```R
JackStrawPlot(object = pbmc_small, PCs = 2:6) # fails
```
With the following error:
```R
Error in approx(1L:lenx, sx, n = leny) : 
  need at least two non-NA values to interpolate
In addition: Warning message:
In xy.coords(x, y, setLab = FALSE) : NAs introduced by coercion
```

**Comment by aaharoni1** [comment]
I am also experiencing this issue

**Comment by samuel-marsh** [comment]
Also having problems with this.  Creates problems when the number of significant PCs is very large and limiting factor becomes screen real estate to easily view the plots.

**Comment by mojaveazure** [comment]
Thanks for bringing this up; this will be fixed in the next major release of Seurat.

**Comment by samuel-marsh** [comment]
Awesome!  Thanks for the update!!

**Comment by andrewwbutler** [comment]
`JackStrawPlot` in Seurat v3 has been updated to allow the plotting of any combination of PCs. Additionally, we have decided to combine the curves into a single plot by default (though you can always access the underlying data with accessors to plot it however you'd like). 

![screen shot 2018-11-06 at 3 37 28 pm](https://user-images.githubusercontent.com/5632416/48092155-e7ecaa80-e1d9-11e8-84ec-9e5c3dd39114.png)

**Comment by samuel-marsh** [comment]
This is awesome!  Really like having the curves on single plot.
Thanks for all your work in the updates!!
