### ISSUE TITLE
Weird plots 

### ISSUE THREAD

**Issue by Echoloria** [satijalab/seurat#6690]
Hi, 
   I got a weird plot when I use JackStraw, here are my script and plots, I don't know how to explain it and how to adjust my parameters.
:
ALL <- JackStraw(ALL, num.replicate = 100)
ALL <- ScoreJackStraw(ALL, dims = 1:20)
JackStrawPlot(ALL, dims = 1:20)
ElbowPlot(ALL)

Thanks,
Echo.

![Rplot01](https://user-images.githubusercontent.com/36149883/202356725-4c854e6a-f8d5-457a-b0b8-5c8abe599c2a.png)
![Rplot](https://user-images.githubusercontent.com/36149883/202356745-37a793b6-05df-4f43-896e-20f437ea3103.png)

**Comment by timoast** [comment]
Can you include the full code you used to create the ALL object?

**Comment by timoast** [comment]
Closing since we haven't heard back
