### ISSUE TITLE
 subclustering on a subset of an integrated object 

### ISSUE THREAD

**Issue by zor4x** [satijalab/seurat#6695]
Hello. I have made a subset of cells from my multiomic integrated dataset (8 samples, two days per genotype x 2 replicates) with ATAC and RNA assay and would like to recluster it to focus on smaller population. Weirdly, the genotypes are similar, but there seems to be a difference between days. is it a batch effect? do i have to redo integration?
![treatment_umap](https://user-images.githubusercontent.com/106872836/202671545-6e762d50-3d9f-448d-9658-bc34c5518bc3.png)

![time_umap](https://user-images.githubusercontent.com/106872836/202670193-cb1bf85b-5b29-4395-bf92-fab652fbe876.png)
![treatment_time](https://user-images.githubusercontent.com/106872836/202670213-22efd2ad-854f-48bd-a705-69b0d8163df8.png)
![umap_dataset](https://user-images.githubusercontent.com/106872836/202670235-f9080ec9-b973-4fc5-bab9-fd58bdbcce51.png)

What I did is:
```
library(Seurat)
set.seed(42)
DefaultAssay(dataset) <-"RNA"
obj = subset(dataset, idents = c(1,4,8,10))
DefaultAssay(obj) <- "RNA"
obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 3000)
obj<- ScaleData(obj, verbose = FALSE, features = VariableFeatures(obj))

obj <- RunPCA(obj, npcs = 50, verbose = FALSE, features = VariableFeatures(obj))
obj <- FindNeighbors(obj, dims = 1:30, features = VariableFeatures(obj))
obj <- RunUMAP(obj, dims = 1:30)
obj <- FindClusters(obj, resolution = 0.20)
```

**Comment by yuhanH** [comment]
Hi, 
do you observe difference of time point in your original integrated object?
Also, after you subset cells, you should still work on the integrated assay (`ScaleData `, `RunPCA`, `FindNeighbors`,...).

**Comment by zor4x** [comment]
Hi, yes I was working on integrated assay.
Also yes, I saw differences of time in original object, but not so evidents

**Comment by yuhanH** [comment]
hi @zor4x 
From the above scripts, it seems that you worked on the RNA assay of your subset data. Just make sure set the default assay to `integrated`.
After subsetting cells, you can also try to just re-run PCA, Neighbors, UMAP to see if the results make more sense.
