### ISSUE TITLE
Problem with UpdateSeuratObject

### ISSUE THREAD

**Issue by eileen316** [satijalab/seurat#6699]
> turtle.neurons.update = UpdateSeuratObject(object = turtle.neurons)
Error: We are unable to convert Seurat objects less than version 2.X to version 3.X
Please use devtools::install_version to install Seurat v2.3.4 and update your object to a 2.X object

**I installed Seurat 2.3.4 according to the error message.**

> library(Seurat)
> packageVersion("Seurat")
[1] ‘2.3.4’
> turtle.neurons.update = UpdateSeuratObject(object = turtle.neurons)
> turtle.neurons
An object of class seurat in project turtle 
 21167 genes across 5901 samples.
> turtle.neurons.update
An object of class seurat in project turtle 
 21167 genes across 5901 samples.

**I ran updateSeuratObject again, but it doesn't update properly.**
**There is no difference between not updating and updating.**

> packageVersion("Seurat")
[1] ‘4.3.0’
> turtle.neurons.update
An old seurat object
 21167 genes across 5901 samples

**Comment by mojaveazure** [comment]
To update Seurat objects from v1.x, you must update them to v2 objects using Seurat v2.3.4; make sure you do _not_ have Seurat v4 or SeuratObject installed when using Seurat v2.3.4 to update old Seurat objects. Once you update, you must save the object as an Rds file, then re-install SeuratObject v4.x from CRAN, read in your v2 object Rds file, then update to a v3/v4 object with `UpdateSeuratObject`
