### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by tomazberisa** [satijalab/seurat#67]
Noticed you mention GPL v3 on http://satijalab.org/seurat but are missing a license in the repository, which may inadvertently turn away some users or developers.

Here is the SOP (which boils down to a LICENSE.txt file in the repo):
https://help.github.com/articles/licensing-a-repository/

**Comment by mschilli87** [comment]
@andrewwbutler: I opened a PR (#68) adding the GPL v3 in case you want that.

**Comment by andrewwbutler** [comment]
Thanks for bringing this up and for the quick PR!
