### ISSUE TITLE
Filtering cells in merged data

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#670]
Hello everyone,
How can I filter cells in a merged object by setting specific thresholds for each object?
Merged<- FilterCells(object = Merged, subset.names = c("nGene", "percent.mito"), 
    low.thresholds = c(200, -Inf), high.thresholds = c(2500, 0.05))
this function set the same threshold for both objects.
Can I perhaps filter the cells in each object first and then merge them? 
Thank you so much.

**Comment by leonfodoulian** [comment]
Hi @EDYAC,

You should first filter your cells before merging the objects. Otherwise, all cells will be filtered using the same criteria.

Best,
Leon
