### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by yjiakang** [satijalab/seurat#6702]
I am working on the scRNA dataset. Here is my code.
```
> head(test@meta.data)
                         orig.ident nCount_RNA nFeature_RNA  tissue  treat
KC02A_AAACCCAGTTATAGCC-1      KC02A       1342          271 tissue1 treat1
KC02A_AAACCCAGTTGTTGTG-1      KC02A       3562          445 tissue1 treat1
KC02A_AAACCCATCGCACGAC-1      KC02A       2340          379 tissue1 treat1
KC02A_AAACCCATCTCGCTCA-1      KC02A       4375          227 tissue1 treat1
KC02A_AAACGAAAGAGTTCGG-1      KC02A       4785         1216 tissue1 treat1
KC02A_AAACGAAAGTCATGAA-1      KC02A       2426          454 tissue1 treat1
                          time percent.mt RNA_snn_res.0.5 seurat_clusters
KC02A_AAACCCAGTTATAGCC-1 time1   69.29955               1               1
KC02A_AAACCCAGTTGTTGTG-1 time1   69.65188               1               1
KC02A_AAACCCATCGCACGAC-1 time1   76.32479               1               1
KC02A_AAACCCATCTCGCTCA-1 time1   91.13143               1               1
KC02A_AAACGAAAGAGTTCGG-1 time1   25.57994               8               8
KC02A_AAACGAAAGTCATGAA-1 time1   67.55977               8               8
                         is_virus virus_reads    celltypes
KC02A_AAACCCAGTTATAGCC-1     hbv-           0  Hepatocytes
KC02A_AAACCCAGTTGTTGTG-1     hbv+           1  Hepatocytes
KC02A_AAACCCATCGCACGAC-1     hbv-           0  Hepatocytes
KC02A_AAACCCATCTCGCTCA-1     hbv-           0  Hepatocytes
KC02A_AAACGAAAGAGTTCGG-1     hbv-           0 CD8+_T-cells
KC02A_AAACGAAAGTCATGAA-1     hbv-           0 CD8+_T-cells

```

> FindConservedMarkers(test, ident.1=0, group="orig.ident")
Warning: Identity: 0 not present in group KC03A. Skipping KC03A
Warning: Identity: 0 not present in group KC10A. Skipping KC10A
Warning: Identity: 0 not present in group KC02A. Skipping KC02A
Warning: Identity: 0 not present in group KC06A. Skipping KC06A
Warning: Identity: 0 not present in group KC08A. Skipping KC08A
Warning: Identity: 0 not present in group KC07A. Skipping KC07A
Warning: Identity: 0 not present in group KC09A. Skipping KC09A
Warning: Identity: 0 not present in group KC05A. Skipping KC05A
Error in marker.test[[i]] : subscript out of bounds
On other dataset，all is OK. Can you be kind to help? Thanks.

**Comment by torkencz** [comment]
Hi, based on what I am seeing you are trying to compare a group that does not exist in the metadata column that you provided. You can only compare a group name that is in " orig.ident", so KC03A etc.
