### ISSUE TITLE
Integration with custom features - Error in scale.data[anchor.features, ] : subscript out of bounds

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#6707]
Hi,

I would like to perform SCT integration with custom features. My aim is to run `SelectIntegrationFeatures` on a subset of the samples to be integrated. This is because some of my samples comprise cells from two tissues, while the others comprise cells from only one tissue. I thought selecting integration features on the samples with two tissues might improve the integration.

However, I am getting the following error when I try this with the SCT workflow:
```
features <- SelectIntegrationFeatures(
    seurat_list[1:4], 
    nfeatures = 3000)

seurat_list <- PrepSCTIntegration(
    seurat_list, 
    anchor.features = features)
```

>   |                                                  | 0 % ~calculating  
> Error in scale.data[anchor.features, ] : subscript out of bounds  
> In addition: Warning message:
> The following requested features are not present in any models: ITGAD, KIR2DL1, RORB, RASIP1 

Is this not possible or am I going about it the wrong way? I am also confused as to why there are some features not present in any of the models, since select features was performed on a subset of the samples for integration.

Best wishes,
Lucy

**Comment by yuhanH** [comment]
hi 
it seems that the features you selected may not be present in all objects.
You can filter features by intersecting RNA assay features. 
```
features <- SelectIntegrationFeatures(
    seurat_list[1:4], 
    nfeatures = 3000)

for (obj.i in seurat_list) {
features <- intersect(features, rownames( obj.i[['RNA']])
}
seurat_list <- PrepSCTIntegration(
    seurat_list, 
    anchor.features = features)
```

**Comment by lucygarner** [comment]
Thank you, I fixed the problem in a similar way as below.

```
features <- SelectIntegrationFeatures(
                seurat_list[custom_samples], nfeatures = variable)
            for (i in seq_along(seurat_list)) {
                features <- features[
                    features %in% rownames(seurat_list[[i]][["SCT"]])]
```
