### ISSUE TITLE
Cell group 1 is empty - no cells with identity class

### ISSUE THREAD

**Issue by peachone** [satijalab/seurat#6708]
When I run FindAllMarkers(), everything is fine and normal if I am using the categories from FindClusters(), but when I try to use custom categories from my own meta, I get an error
the following problem appears.

`sce@active.ident <- as.factor(sce@meta.data$cluster)`
`allmarker <- FindAllMarkers(sce, only.pos = TRUE,logfc.threshold = 0.25, min.pct = 0.25)`

it An error is reported：

Calculating cluster prol. TAM
Calculating cluster TAM 1
Calculating cluster TAM 2
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing prol. TAM versus all:
	Cell group 1 is empty - no cells with identity class 
Warning: When testing TAM 1 versus all:
	Cell group 1 is empty - no cells with identity class 
Warning: When testing TAM 2 versus all:
	Cell group 1 is empty - no cells with identity class

Can anyone tell me how I need to change it?

**Comment by yuhanH** [comment]
Could you sent the active idents by this way?
```
Idents(sce) <- 'cluster'
```
Could you show `table(sce$cluster)` and `levels(sce$cluster)` to see if there are factor levels without any cells?

**Comment by peachone** [comment]
> Could you sent the active idents by this way?
> 
> ```
> Idents(sce) <- 'cluster'
> ```
> 
> Could you show `table(sce$cluster)` and `levels(sce$cluster)` to see if there are factor levels without any cells?

Thank you very much for your reply.
This problem has been solved by the following code：
`Idents(sce) <- sce@meta.data[["cluster"]]`
