### ISSUE TITLE
Unable to LoadData() for humancortex data

### ISSUE THREAD

**Issue by TedRees61** [satijalab/seurat#6712]
I'm trying the [integration Vignette](https://satijalab.org/seurat/articles/integration_introduction.html). I want to use the humancortex dataset as that is closest to my real world case. the Dataset appears to install OK and shows up in InstalledData() but when trying load data it comes up with an 

Error: Could not find dataset 'humancortexref', please check manifest and try again

I tried with other data sets and it seems ok

Code and Messages below
InstalledData()
LoadData(ds="humancortexref")

![image](https://user-images.githubusercontent.com/78317272/203541691-f836a204-5fb8-4a5a-9963-3b643a1ef485.png)

Works Ok for c.elegens

LoadData("celegans.embryo")

An object of class Seurat 
20222 features across 6188 samples within 1 assay 
Active assay: RNA (20222 features, 0 variable features)

FYI I tried on Seurat 4.2 and 4.3. Appreciate your help

**Comment by TedRees61** [comment]
Still not working. I tried using the data() function instead of LoadData() as per this explanation https://github.com/satijalab/seurat-data.
I also tried removeData then re-installing. It works ok for C.elegens data so I'm not sure why it can't "find" the dataset

**Comment by AustinHartman** [comment]
In order to load `humancortexref`, please use `LoadData("humancortexref", type = "azimuth")` as all of the `SeuratData` datasets ending with `ref` are azimuth references which are loaded in slightly differently. Note that these reference datasets are lightweight objects used for cell annotation, so the raw counts isn't stored
