### ISSUE TITLE
strange 

### ISSUE THREAD

**Issue by DelongZHOU** [satijalab/seurat#6716]
Hi,
I'm having a strange result with subset. Basically when I select one cluster it returns expected number of cells but when I select two clusters it returns fewer cells then the two individual cluster combined..
![image](https://user-images.githubusercontent.com/56367172/203682658-e20e4c76-ccb6-474d-8e3a-95f635667e4f.png)

Here I first select cluster 3 and it returns 6627 cells; select cluster 7 returns 2009 cells; but when select cluster c(3,7) it returns only 4414 cells.
Can you help me figuring out what's missing?
Thanks!

**Comment by samuel-marsh** [comment]
Hi,

This has to do with the default behavior of `==` in R and is behaving normally.  See https://stackoverflow.com/questions/42637099/difference-between-the-and-in-operators-in-r

What you need to run:
```
sub_obj <- subset(obj, subset = seurat_clusters %in% c(3, 7))
```

Best,
Sam

**Comment by DelongZHOU** [comment]
Thanks Samuel. My lack of fluency in R is showing.

May I suggest include this in the Seurat Command list
https://satijalab.org/seurat/articles/essential_commands.html

There's one example using
`idents = c("CD4 T cells", "CD8 T cells")`
while another uses 
`subset = orig.ident == "Replicate1"`

So natually I tried to combine them into what I did.

Anyway thanks for your time!

**Comment by samuel-marsh** [comment]
No worries!

Yes if you use one of the Seurat params (idents, cells) then you can provide many variables with simply the param `=` and the function will take care of it under the hood.  But if providing different variable to the `subset` param then you need to follow R syntax.

Best,
Sam
