### ISSUE TITLE
SCTransform error with Vizgen data

### ISSUE THREAD

**Issue by WesDe** [satijalab/seurat#6717]
Hi,

I am trying to analyze public vizgen data (liver) from the RDS file I have saved after the use of the LoadVizgen function (I haven't download the image folder from the public dataset).  An error appears when I try to run SCTransform as the vignette described: 
`vizgen.obj <- SCTransform(vizgen.obj, assay = "Vizgen", clip.range = c(-10, 10), )
`

> Calculating cell attributes from input UMI matrix: log_umi
Error in make_cell_attr(umi, cell_attr, latent_var, batch_var, latent_var_nonreg,  : 
  cell attribute "log_umi" contains NA, NaN, or infinite value

Any idea about the cause of the error ?

Best,
WesDe

**Comment by alikhuseynov** [comment]
Hi there,
remove cells that have zero transcript count, ie `obj_vz %<>% subset(subset = nCount_Vizgen > 0)`
then it should work.
Hope this helps.

**Comment by WesDe** [comment]
Hi, 

You were right, I didn't expect from raw file to include empty cell. 

Best,
