### ISSUE TITLE
Issue with running PrepareBridgeReference

### ISSUE THREAD

**Issue by sumeer1** [satijalab/seurat#6718]
Good day!

I have been testing the new bridge integration and when I run PrepareBridgeReference. 
It shows an error of "could not find a function PrepareBridgeReference" , even though I have all the libraries installed

```r
dims.atac <- 2:50
dims.rna <- 1:50
DefaultAssay(obj.multi) <-  "RNA"
DefaultAssay(obj.rna) <- "SCT"
obj.rna.ext <- PrepareBridgeReference(reference = obj.rna,
                                      bridge = obj.multi, 
                                      reference.reduction = "spca",
                                      reference.dims = dims.rna,
                                      normalization.method = "SCT"
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you provide output of `sessionInfo()`?

Thanks,
Sam

**Comment by Gesmira** [comment]
Hi, 
If you follow the below steps:
1. restart R
2. run this from the vignette: `remotes::install_github("satijalab/seurat", "feat/dictionary", quiet = TRUE)`
3. `library(Seurat) `

The dictionary branch of Seurat should then be loaded and PrepareBridgeReference will be found.
