### ISSUE TITLE
Workflow to Run SCTransform() again after extracting a subset from an integrated object 

### ISSUE THREAD

**Issue by anaccsilva** [satijalab/seurat#6719]
Hi, I would like to follow up on the following issue #6169. 

When you say rerun SCTransform(), do you mean the whole process? I am running SCT v2.

Should I set the assay to integrate first and run SCT() -> PCA -> SelectIntegrationFeatures -> PrepSCTIntegration -> Anchors and Integrate again?

In this other issue (#5012) @saketkc says not to rerun SCT. So, I am a little bit confused.

Sorry for the question. I see that this recluster question shows up sometimes, but there is no vignette about it.

Thank you,
Ana

**Comment by saketkc** [comment]
Hi @anaccsilva, re-running SCTransform post subsetting _might_ sometimes help reveal finer structure in the data but from a normalization point of view is not required (though there is nothing wrong if you run it again).

**Comment by anaccsilva** [comment]
Thank you so much for the quick reply.
I will try re-running SCT(). In this case, which assay should I use to restart the process? And should I run all the way, integrating the new object again?
Thank you so so much!!

**Comment by saketkc** [comment]
SCT by default runs on the RNA assay (which is what you would do for the subsetted object). Any downstream processin g (PCA/integration) would need to be redone as well.

**Comment by anaccsilva** [comment]
I have an error selecting integration features. 
I need an object.list, right? But I don't have it, because I have this integrated object, so I get: 

"Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector". 

Not sure how I can proceed.
Sorry for the stupid questions, but I am not an expert in this area, just a biologist trying to analyze the data :-D 
Thank you in advance.

**Comment by anaccsilva** [comment]
I think I got it. Can you see if it makes sense please?
`om.immune = subset(OM, idents = c(32,33,20,4,21,17,27,5,6,10,0,15,37,31))
DefaultAssay(om.immune) <- "RNA"
SCTransform(om.immune, vst.flavor = "v2", verbose = FALSE)
om.immune.list <- SplitObject(om.immune, split.by = "om")
om.immune.features <- SelectIntegrationFeatures(object.list = om.immune.list, nfeatures = 3000)
OM.list <- PrepSCTIntegration(object.list = om.immune.list, anchor.features = OM.all.features,verbose = T)
`
And continue from there...

**Comment by saketkc** [comment]
Yes, that looks correct.

**Comment by anaccsilva** [comment]
Still getting error :-(
om.immune.list <- PrepSCTIntegration(object.list = om.immune.list, anchor.features = om.immune.features,verbose = T)
  |                                                  | 0 % ~calculating  Warning: SCT model not present in assay
Error in scale.data[anchor.features, ] : 
  no 'dimnames' attribute for array

I have this integrated object of 18 patients that I ran SCTransform individually. 
Although I ran again the SCT in the integrated object before splitting, after splitting, I don't have that integrated object anymore, right? But individually they do. Any ideas? 
Long issue and questions. I am sorry.

**Comment by anaccsilva** [comment]
I had a whole other comment here, but after completely seeing your message, I tried, and it works!!

Thank you so much for your help and patience!
