### ISSUE TITLE
Seurat subset function error --> Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) :    invalid character indexing

### ISSUE THREAD

**Issue by parkjooyoung99** [satijalab/seurat#6720]
Hello, 
I have a question about version of seurat and subset function. 

i made seurat object with 'v.4.1.x' and later update seurat to 'v.4.2.1'. 
After updating the seurat, subset function does not work with 4.1.x object.

Does version of seurat matters when using subset function?

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you provide the code that you are running and the full error that you are getting?

Thank you,
Sam

**Comment by parkjooyoung99** [comment]
Hi, 
i used **subset(obj, idents ='0')** as described in seurat tutorial and error above is the full error. 

By the way, using new obj made with code i used before (before updating seurat version) worked. 
I guess the version of seurat for the object and the current environment matters.

**Comment by samuel-marsh** [comment]
Is this solved as per your other issue #6904?

Thanks,
Sam

**Comment by samuel-marsh** [comment]
closing as I haven't heard back.  If this is still an issue please post here.

Best,
Sam

**Comment by ElisaRosatiScalchi** [comment]
Having a similar issue:

`subset(seurat, subset = nFeature_RNA > 200 & nFeature_RNA < 3500 & percent.mt < 10) 
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing`

sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.4.2
LAPACK: /hpc/apps/2018/R/v4.0.2.app/lib/R/lib/libRlapack.so

other attached packages:
harmony_1.0                 Rcpp_1.0.6                  SeuratObject_4.0.0          **Seurat_4.0.1**
