### ISSUE TITLE
How to add metadata to an existing dataset

### ISSUE THREAD

**Issue by aclynch160** [satijalab/seurat#6723]
Hey there!

I am presently working on reanalysis of the GSE176293 data subset. 

The formatting of the files are a bit odd; my initial data file is a combined barcode/features file with the following format: 

```{r}
Barcode 
         Gene1    Gene2    Gene3    Gene4
AAA...      1       2        1       0
BBB...      1       0        1       1 
CCC...      1       1        0       1
```

Anyhow. I reformatted the dataset into the correct format using the following (courtesy of @samuel-marsh): 

```{r}
test <- data.table::fread("G:/.shortcut-targets-by-id/17gW9rYfqH0ekinppcX_LVzdsw-QBqK87/AL/AL-10/scRNA- Rudensky/mln-cd4t-scrnaseq.csv", data.table = F) %>%
     column_to_rownames("V1")

# transpose and make to dgCMatrix
mat_trans <- as.sparse(t(test))

# make seurat:
test_seu <- CreateSeuratObject(mat_trans)

```
However, I have realized upon analysis of the above data: I never applied the metadata, which includes the original sample ID's.

The format of the metadata file is, again, a bit odd;(or perhaps it isn't, and I'm just a beginner). Here are the first few rows:

```{r}

  | batch | n_genes | sample | n_counts | after_filter | phenograph | phenograph_subset
-- | -- | -- | -- | -- | -- | -- | --
AAACCTGAGAGGTACC-1-0 | 0 | 589 | GFP-GF | 1155.294 | TRUE | 1 | NA
AAACCTGAGGGATGGG-1-0 | 0 | 1239 | GFP-GF | 1628.615 | TRUE | 5 | s7
AAACCTGAGGTCGGAT-1-0 | 0 | 645 | GFP-GF | 1311.158 | TRUE | 2 | NA
AAACCTGGTAGCCTAT-1-0 | 0 | 535 | GFP-GF | 992.0568 | TRUE | 4 | NA
AAACCTGTCCGATATG-1-0 | 0 | 867 | GFP-GF | 1022.65 | TRUE | 1 | NA
AAACGGGAGGACTGGT-1-0 | 0 | 913 | GFP-GF | 1216.149 | TRUE | 1 | NA
AAACGGGGTACCCAAT-1-0 | 0 | 2045 | GFP-GF | 1172.588 | TRUE | 2 | NA
AAACGGGGTACCGAGA-1-0 | 0 | 912 | GFP-GF | 1487.835 | TRUE | 3 | s2
```

Adding metadata using AddMetaData does not seem to work, as it does not link the cellnames in column 1 to the correct object. As such, I think I need to reformat this data, as well, unless I'm missing something terribly obvious. 

Flipping the columns as I flipped the cells and features does not work, as I receive a "NAs added via coercion" error, followed by an "unequal column number" error when trying to power through and using AddMetaData as following: 

```{r}
zsme <- AddMetaData(
  object = zsme,
  metadata = meta_data,
  col.name = 'sample')
```

Say, for example, I want to add the above data to my seurat object; or at least, the "sample" column. How might you folks go about doing so?

Thank you!!

**Comment by samuel-marsh** [comment]
Hi,

In the meta data that you want to add are the cell barcodes the rownames of the data.frame or are they in the first column?

Best,
Sam

**Comment by aclynch160** [comment]
Hey there! 

The barcodes are the first column.

**Comment by aclynch160** [comment]
Sam, 

I realized I was horribly overcomplicating things. 

I managed to make things work by doing the following:

```{r}
metadata <- data.table::fread("G:/.shortcut-targets-by-id/17gW9rYfqH0ekinppcX_LVzdsw-QBqK87/AL/AL-10/scRNA- Rudensky/mln-cd4t-scrnaseq-cells.csv", data.table = T) %>%
     column_to_rownames("V1")

zsme <- AddMetaData(
  object = zsme,
  metadata = metadata,
  col.name = )

```

Thanks for the help anyways!
