### ISSUE TITLE
Is it possible to use seurat to integrate scATAC-seq data?

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6724]
Hi, I have two multiome datasets (both contain scrna and scatac)
I wonder if it is possible to use seurat to integrate atac to atac. Thanks a lot!

**Comment by timoast** [comment]
Yes, please see https://stuartlab.org/signac/articles/integrate_atac.html

**Comment by HelloWorldLTY** [comment]
Hi Tim, I intend to integrate the scatac data in the peak space rather than latent data space, like seurat. Is it possible? Thanks a lot!

**Comment by timoast** [comment]
Yes, you can run IntegrateData rather than IntegrateEmbeddings but the resulting matrix will be extremely large

**Comment by HelloWorldLTY** [comment]
Oh, many thanks for your help, and I will try it later.

**Comment by HelloWorldLTY** [comment]
Thanks. I think after integration, ChromatinAssay becomes seuratobject. However, to identify gene-peak link, I still need CA. Could you please help me solve this problem? Thanks a lot.

**Comment by timoast** [comment]
You can create a new ChromatinAssay using the integrated matrix (running the `CreateChromatinAssay()` function). However, I would not recommend using an integrated peak matrix for finding peak-gene correlations, as the correlation values will be inflated.

**Comment by HelloWorldLTY** [comment]
Ok, I got it. I think I will directly concat two assays to perform peak-gene correlations, but I am not sure if it will be affected by batch effect or not since we need to reach the balance between biological conservation and batch effect removal.
