### ISSUE TITLE
Questions about sctransform data

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6728]
Hi all, I set highly variable genes a 1000, and I only intend to access the matrix with hvgs x cells matrix after sctransform operation. I wonder if it is the same as the @scaledata here:

$ SCT:Formal class 'SCTAssay' [package "Seurat"] with 9 slots
  .. .. .. ..@ SCTModel.list:List of 1
  .. .. .. .. ..$ model1:Formal class 'SCTModel' [package "Seurat"] with 7 slots
  .. .. .. .. .. .. ..@ feature.attributes:'data.frame':	38565 obs. of  12 variables:
  .. .. .. .. .. .. .. ..$ detection_rate       : num [1:38565] 0.000301 0.005528 0.003896 0.011008 0.001489 ...
  .. .. .. .. .. .. .. ..$ gmean                : num [1:38565] 6.86e-05 1.65e-03 1.17e-03 3.34e-03 3.65e-04 ...
  .. .. .. .. .. .. .. ..$ variance             : num [1:38565] 0.00002 0.000713 0.000508 0.001505 0.000126 ...
  .. .. .. .. .. .. .. ..$ residual_mean        : num [1:38565] -0.00024 0.0564 0.04701 0.078 0.02262 ...
  .. .. .. .. .. .. .. ..$ residual_variance    : num [1:38565] 0.000017 2.910806 3.396234 2.790796 2.338548 ...
  .. .. .. .. .. .. .. ..$ theta                : num [1:38565] 8.12e-08 1.06e-02 4.54e-03 4.26e-02 4.75e-06 ...
  .. .. .. .. .. .. .. ..$ (Intercept)          : num [1:38565] -12.98 -10.93 -11.52 -9.91 -12.89 ...
  .. .. .. .. .. .. .. ..$ log_umi              : num [1:38565] 2.4 2.61 2.7 2.51 2.91 ...
  .. .. .. .. .. .. .. ..$ genes_log_gmean_step1: logi [1:38565] FALSE FALSE FALSE TRUE FALSE FALSE ...
  .. .. .. .. .. .. .. ..$ step1_theta          : num [1:38565] NA NA NA 2.48e-07 NA ...
  .. .. .. .. .. .. .. ..$ step1_(Intercept)    : num [1:38565] NA NA NA -6.68 NA ...
  .. .. .. .. .. .. .. ..$ step1_log_umi        : num [1:38565] NA NA NA 1.14 NA ...
  .. .. .. .. .. .. ..@ cell.attributes   :'data.frame':	63137 obs. of  3 variables:
  .. .. .. .. .. .. .. ..$ umi        : num [1:63137] 6268 4696 5136 7330 4911 ...
  .. .. .. .. .. .. .. ..$ log_umi    : num [1:63137] 3.8 3.67 3.71 3.87 3.69 ...
  .. .. .. .. .. .. .. ..$ cells_step1: logi [1:63137] FALSE FALSE FALSE FALSE FALSE FALSE ...
  .. .. .. .. .. .. ..@ clips             :List of 2
  .. .. .. .. .. .. .. ..$ vst: num [1:2] -251 251
  .. .. .. .. .. .. .. ..$ sct: num [1:2] -45.9 45.9
  .. .. .. .. .. .. ..@ umi.assay         : chr "RNA"
  .. .. .. .. .. .. ..@ model             : chr "y ~ log_umi"
  .. .. .. .. .. .. ..@ arguments         :List of 32
  .. .. .. .. .. .. .. ..$ latent_var               : chr "log_umi"
  .. .. .. .. .. .. .. ..$ batch_var                : NULL
  .. .. .. .. .. .. .. ..$ latent_var_nonreg        : NULL
  .. .. .. .. .. .. .. ..$ n_genes                  : num 2000
  .. .. .. .. .. .. .. ..$ n_cells                  : num 5000
  .. .. .. .. .. .. .. ..$ method                   : chr "glmGamPoi"
  .. .. .. .. .. .. .. ..$ do_regularize            : logi TRUE
  .. .. .. .. .. .. .. ..$ theta_regularization     : chr "od_factor"
  .. .. .. .. .. .. .. ..$ res_clip_range           : num [1:2] -251 251
  .. .. .. .. .. .. .. ..$ bin_size                 : num 500
  .. .. .. .. .. .. .. ..$ min_cells                : num 5
  .. .. .. .. .. .. .. ..$ residual_type            : chr "pearson"
  .. .. .. .. .. .. .. ..$ return_cell_attr         : logi TRUE
  .. .. .. .. .. .. .. ..$ return_gene_attr         : logi TRUE
  .. .. .. .. .. .. .. ..$ return_corrected_umi     : logi TRUE
  .. .. .. .. .. .. .. ..$ min_variance             : num -Inf
  .. .. .. .. .. .. .. ..$ bw_adjust                : num 3
  .. .. .. .. .. .. .. ..$ gmean_eps                : num 1
  .. .. .. .. .. .. .. ..$ theta_estimation_fun     : chr "theta.ml"
  .. .. .. .. .. .. .. ..$ theta_given              : NULL
  .. .. .. .. .. .. .. ..$ exclude_poisson          : logi FALSE
  .. .. .. .. .. .. .. ..$ use_geometric_mean       : logi TRUE
  .. .. .. .. .. .. .. ..$ use_geometric_mean_offset: logi FALSE
  .. .. .. .. .. .. .. ..$ fix_intercept            : logi FALSE
  .. .. .. .. .. .. .. ..$ fix_slope                : logi FALSE
  .. .. .. .. .. .. .. ..$ scale_factor             : logi NA
  .. .. .. .. .. .. .. ..$ vst.flavor               : NULL
  .. .. .. .. .. .. .. ..$ verbosity                : num 0
  .. .. .. .. .. .. .. ..$ verbose                  : NULL
  .. .. .. .. .. .. .. ..$ show_progress            : NULL
  .. .. .. .. .. .. .. ..$ sct.clip.range           : num [1:2] -45.9 45.9
  .. .. .. .. .. .. .. ..$ sct.method               : chr "default"
  .. .. .. .. .. .. ..@ median_umi        : num 2
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:94160] 17060 18118 18082 18082 18082 18082 18082 18082 18082 18082 ...
  .. .. .. .. .. ..@ p       : int [1:63138] 0 2 2 2 2 2 2 2 3 4 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 38565 63137
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:38565] "ENSG00000233750.3" "ENSG00000225972.1" "ENSG00000225630.1" "ENSG00000237973.1" ...
  .. .. .. .. .. .. ..$ : chr [1:63137] "GCTAACGGATACTGAGCGACGTCCTACTTGCCAGCCTTT" "CCGTATGATTATCGAGATGAGTCCTACTTGCGCTGCTTT" "TATTAGACTTCATTGACGCTGACGACCTGCAGAGATGAAT" "AGTTGAATCATGAGGAATCAGTCCTACTTGACGCTTATAT" ...
  .. .. .. .. .. ..@ x       : num [1:94160] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:94160] 17060 18118 18082 18082 18082 18082 18082 18082 18082 18082 ...
  .. .. .. .. .. ..@ p       : int [1:63138] 0 2 2 2 2 2 2 2 3 4 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 38565 63137
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:38565] "ENSG00000233750.3" "ENSG00000225972.1" "ENSG00000225630.1" "ENSG00000237973.1" ...
  .. .. .. .. .. .. ..$ : chr [1:63137] "GCTAACGGATACTGAGCGACGTCCTACTTGCCAGCCTTT" "CCGTATGATTATCGAGATGAGTCCTACTTGCGCTGCTTT" "TATTAGACTTCATTGACGCTGACGACCTGCAGAGATGAAT" "AGTTGAATCATGAGGAATCAGTCCTACTTGACGCTTATAT" ...
  .. .. .. .. .. ..@ x       : num [1:94160] 0.693 0.693 0.693 0.693 0.693 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num [1:1000, 1:63137] -0.0997 -0.0262 -0.0113 -0.0781 -0.0367 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:1000] "ENSG00000225630.1" "ENSG00000198744.5" "ENSG00000171608.16" "ENSG00000142634.13" ...
  .. .. .. .. .. ..$ : chr [1:63137] "GCTAACGGATACTGAGCGACGTCCTACTTGCCAGCCTTT" "CCGTATGATTATCGAGATGAGTCCTACTTGCGCTGCTTT" 

Thanks a lot.

**Comment by alikhuseynov** [comment]
Hi there, 
I think it depends on what you need that *hvgs x cells matrix* for.
[`SCTransform()` description](https://satijalab.org/seurat/reference/sctransform) pretty much tells you what output you get.
I guess, If you want (corrected) raw counts with *hvgs* only, just subset `@counts` matrix to keep the 1000 variable features.
Hope this helps.

**Comment by saketkc** [comment]
`scale.data` slot stores the pearson residuals while corrected counts (for all genes) are stored in the `data` slot.

**Comment by pagarwal14** [comment]
Hi,
Can you please explain the meaning of pearson residuals and correct counts in simple terms.  I kind of understand but am not able to understand the reasoning.  If there are resources that would help understand in non-statistical language please let me know.  Thanks.

**Comment by saketkc** [comment]
Here's some non-technical (and technical) discussion on sctransform: https://drive.google.com/file/d/1mbFNhQYHlVsKThIuhDfe_ouz-FkHdpGo/view?usp=sharing. The basic idea is simple: learn the model of technical noise in the data (which is exhibited by majority of genes). The residuals quantify how much each observed value deviates from this "expected" model of technical noise. Positive pearson residual (PR) = more deviation from expected model; negative PR = less deviation than expected
