### ISSUE TITLE
RunDiffusion error

### ISSUE THREAD

**Issue by tomallison24** [satijalab/seurat#673]
Hey guys,

I am having a problem with the RunDiffusion function. As far as I can tell my seurat object is fine (I have all the downstream analysis done fine) but I am getting the following error when running this line:
```R
RunDiffusion(pbmc.1, cells.use = NULL, dims.use = 1:10)
```
It is giving me the following error:
```R
Error in destiny::DiffusionMap(data = as.matrix(data.dist), n_eigs = max.dim,  : 
  k has to be < nrow(data) (And 2858 ≥ nrow(data))
```
Any help would be much appreciated!

Tom

**Comment by tomallison24** [comment]
Hey, thanks for the help!

Strange as there are far more rows than columns in the data set. (21183 rows vs 3410 columns).

I ran you suggested code and got the following output:

> for(i in 1:2858) {
+   tryCatch({
+     RunDiffusion(pbmc.1, cells.use = NULL, dims.use = 1:10, k = destiny::find_dm_k(i))
+   },
+   error = function(err) message(paste0("Didn't work for ", i)))
+ }
Didn't work for 1
Didn't work for 2
Didn't work for 3
Didn't work for 4
Didn't work for 5

Looks like not even K1 works? Is it possible the data is too similar for DC components to be plotted?

I have also gone ahead and changed k to 1:

 RunDiffusion(pbmc.1, cells.use = NULL, dims.use = 1:10, k = 1)

unfortunately get a whole different error!

> RunDiffusion(pbmc.1, cells.use = NULL, dims.use = 1:10, k=1)
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Thanks in advance

**Comment by evolvedmicrobe** [comment]
Ah strange, indeed the data might be weird somehow.

My recommendation would be to try and debug the program.  You can call, `debug(destiny::DiffusionMap)` which should open the debugger when it goes inside the function.  Then you can step through by typing `n`, and print out the variables as you go along.  That should allow you to see where the error is being produced and understand it a bit better.

**Comment by tomallison24** [comment]
OK super, thank you for the help - I will give this a go

**Comment by andrewwbutler** [comment]
Closing for now as `RunDiffusion` is basically just a wrapper around `destiny::DiffusionMap`. Please reopen though if you have any updates or if the bug is in some of that wrapper code.

**Comment by adnners** [comment]
Hi guys, 
I´m new with rundifussion and I keep getting an error when I try to run a deforum prompt. Any advice? I´m using a mac. Thanks!
