### ISSUE TITLE
Dealing with dissociation signal in clustering and downstream analysis

### ISSUE THREAD

**Issue by Dillon214** [satijalab/seurat#6730]
Hello Seurat team,

I have a question regarding my analysis. You see, I have been working on a dataset which is primarily composed of macrophage cells harvested from 8 different bodily tissues, with the goal of comparing and contrasting said tissue-specific macrophages. When I merge all the cells and cluster, I see that most tissue macrophages seggregate into their own separate clusters seggregated by tissue of origin, and other more similar types of tissue macrophages cluster together. This is expected behavior.

What troubles me about this analysis, however, is that some tissues were digested enzymatically, and others were digested with mechanical dissociation. Enzymatic digestion, as I've come to see it, causes a variable degree of transcriptomic changes in cells, but usually manifests as the upregulation of immediate early genes (Fos, Jun, etc.). See the picture below to observe the effect this has on clustering . 

So, I'm confident that clustering is still primarily driven by biology, however differences in the severity of dissociation stress response within and between different tissue macrophages is affecting clustering and confounding differential expression testing. Does anyone have any advice about what I should do? I have tried regressing out the dissociation signal, and have tried integrating affected vs. unaffected cells, and I am not confident that the results of either are accurate to the biology (though integration did perform better in this regard). My main sticking point is the issue of differential expression, whenever I want to compare biologically similar tissue macrophages. Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/73907611/204647349-12756553-97dc-4cb9-a8ea-a32275416510.png)

![image](https://user-images.githubusercontent.com/73907611/204645015-42b8a07c-6f49-4b88-b2d1-50865d25113b.png)

**Comment by timoast** [comment]
> some tissues were digested enzymatically, and others were digested with mechanical dissociation.

If you only have one replicate of each tissue being either digested enzymatically or mechanically (ie, complete confounding between tissue and digestion method), there's unfortunately no way to tell whether differences are due to the dissociation method or tissue. However, if you assume that dissociation signals are shared across tissues then you may be able to identify what differences are due to the dissociation method (different between mechanical and enzymatic regardless of tissue of origin).
