### ISSUE TITLE
How to run splitobject operation towards a dataset merged by merge function

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6732]
Hi, I intend to integrate multiome data (scrna-scrna, scatac-scatac), so I need to assign some index or marks for each dataset before merge operation. However, I did not find such parameter in the function merge. Therefore, I wonder if there are any methods such as:

d = merge(d1,d2,batch=(1,2)), and then

splitobject(d, based on batch )

Thanks a lot!

**Comment by WesDe** [comment]
Hi,

Are you talking about :

`seurat.combined <- merge(x = obj_1, y = c(obj_2,obj_3))
seurat.split<-SplitObject(seurat.combined, split.by = "batch")
`
Be sure to have added the batch information in each object before merging them.

Best

**Comment by Gesmira** [comment]
Hi, 
Once you have made a seurat object for each of your datasets, you can add the batch information to the metadata of each of your seurat objects using 
```
obj_1$batch <- "batch_1"
obj_2$batch <- "batch_2"
```
This will add a column to the metadata called "batch". 
You can then follow @WesDe's steps for merging and splitting the object based on this batch variable downstream.
