### ISSUE TITLE
Questions about using integration results to find gene-peak link

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6733]
Hi, since I have many multiome datasets, I plan to integrate them together in their raw expression space (that is ,rna to rna, atac to atac). My plan is:

1. run integration method for both rna and atac based on cca (mentioned in seurat)
2. change the assay into integrated results, and then perform analysis.

However, in step2, it seems that the integrated dataset is not in chorme accessibility form, so I cannot use integrated results to find gene-peak link. Could you please help me? Thanks a lot.

**Comment by timoast** [comment]
Answered here: https://github.com/satijalab/seurat/issues/6724
