### ISSUE TITLE
Addmodulescore on sce to seurat object

### ISSUE THREAD

**Issue by gk1610** [satijalab/seurat#6735]
I have a single celled experiment object w/o logcounts. I converted the sce object to seurat object using
ATAC <- as.Seurat(ATAC_sce, counts = "counts",data=NULL)

 pbmc_small <- AddModuleScore(
  object = ATAC,
  features = list(features_peaks),
  ctrl = length(0.75*length(features_peaks)),
  name = "test" )

My question is does AddModuleScore score work on counts if logcounts are not present in the object.

**Comment by timoast** [comment]
You should normalize the data before running `AddModuleScore()`, the function assumes that normalization has been done
