### ISSUE TITLE
Error in Matrix(from) : invalid 'data'

### ISSUE THREAD

**Issue by Aanchal85** [satijalab/seurat#6736]
I am trying to run the 1st steps of filtering the data using Seurat. I am using the freely available single-cell dataset from Zeishal et al. with the columns as cell i.ds and rows as gene names and the mRNA molecular count data.
The following is the screen shot of the dataset.

cell_id	1772071015_C02	1772071017_G12	1772071017_A05	1772071014_B06	1772067065_H06
Tspan12	0	0	0	3	0
Tshz1	3	1	0	2	2
Fnbp1l	3	1	6	4	1
Adamts15	0	0	0	0	0
Cldn12	1	1	1	0	0

I run the following command and get the error listed:
mydata <- CreateSeuratObject(counts = raw_counts, min.cells = 3, min.features = 200, project = "mydata_scRNAseq")
Error in Matrix(from) : invalid 'data'

**Comment by timoast** [comment]
Can you provide a link to the data you're using, as well as the code you're using to read the matrix into R and your session info?

**Comment by Schmitt467** [comment]
I have a similar problem with TDM<- Matrix(as.matrix(TD),sparse=TRUE) 
On my pic you can see my matrix TD.
![image](https://user-images.githubusercontent.com/132559049/236159528-3fd9a5c3-1fd6-4fc6-9405-f10db8a485e1.png)
Any suggestions?
