### ISSUE TITLE
Exclude unwanted regions on 10x Visium images and compare annotated regions on images

### ISSUE THREAD

**Issue by cf98** [satijalab/seurat#6740]
### Discussed in https://github.com/satijalab/seurat/discussions/6739

<div type='discussions-op-text'>

<sup>Originally posted by **cf98** November 30, 2022</sup>
Hi everyone,

I am learning the 10X visium data analysis pipeline on Seurat.

I noticed that there are a few fold or wrinkles on my image, and I am wondering if Seurat would allow me to exclude those regions before all the normalization and clustering steps. It would be nice if there's an interactive interface to mark those regions and exclude them before starting on everything. 

Also, I hope to know if it's possible to overlay pathology annotations on the image. It would be very nice to see if an annotated region is enriched for specific gene expressions or cluster of cell types.

Thanks,
Changfeng</div>

**Comment by AustinHartman** [comment]
If you are able to identify the particular spots in the Visium slide overlapping the fold and wrinkles in the histology image, then you can subset the counts matrix of your object like this: `subset(object, cell = overlapping.spots, invert = T)`.

There's not currently a supported way to overlay pathology annotations but you could attempt to do this manually, perhaps replacing the images spaceranger provides with your own, and load using `Read10X_Image`

**Comment by cf98** [comment]
Thank you!
I identified the spot barcodes with the help of 10X loupe browser.
