### ISSUE TITLE
Error in validityMethod(as(object, superClass)) :  object 'CsparseMatrix_validate' not found

### ISSUE THREAD

**Issue by hseebi** [satijalab/seurat#6745]
I just try to use (FindNeighbors cmd from seurat) in my R and got this error :

s1 <- FindNeighbors(s1, dims = 1:30, verbose = F0)
Error in validityMethod(as(object, superClass)) : object 'CsparseMatrix_validate' not found

Traceback

15.validityMethod(as(object, superClass))
14.isTRUE(x)
13.anyStrings(validityMethod(as(object, superClass)))
12.validObject(.Object)
11..nextMethod(.Object = .Object, ... = ...)
10.callNextMethod()
9.initialize(value, ...)
8.initialize(value, ...)
7.new(Class = "Graph", i = c(0L, 181L, 307L, 608L, 716L, 862L, 
863L, 933L, 1370L, 2012L, 2234L, 2565L, 2646L, 2672L, 3041L, 
3166L, 3237L, 3852L, 4047L, 4052L, 4347L, 4356L, 4404L, 4424L, 
4472L, 4732L, 5213L, 5477L, 1L, 385L, 726L, 929L, 2206L, 2266L, ...
6.do.call(what = "new", args = object.list)
5.UpdateSlots(object = object)
4.`DefaultAssay<-.Graph`(object = `*tmp*`, value = assay)
3.`DefaultAssay<-`(object = `*tmp*`, value = assay)
2.FindNeighbors.Seurat(srat1, dims = 1:30, verbose = F)
1.FindNeighbors(srat1, dims = 1:30, verbose = F)

R 4.2.0

Please help me to figure-out this issue. Thank you

**Comment by timoast** [comment]
Please see https://github.com/satijalab/seurat/issues/6715
