### ISSUE TITLE
FindMarkers getting Error "Cannot find the following identities in the object: 25"

### ISSUE THREAD

**Issue by cf98** [satijalab/seurat#6747]
I am using Seurat 4.3.0. I run the command `FindMarkers(healthy_A1_norm, ident.1 = 3, min.diff.pct = 0.25, min.pct = 0,25)` on an SCTransformed seurat object. The object has cluster 0-7 from `FindClusters` results.

Based on the help document, if I pass nothing to ident.2, it should give comparison to all other clusters.

Whichever cluster number I put in ident.1 (I also tried using quoted cluster number), it throws this error and I can't move on:
`Error in WhichCells.Seurat(object = object, idents = ident.2) : Cannot find the following identities in the object: 25`

I tried to include an ident.2 for comparison, but it throws the same error.

PS: I was able to run `FindAllMarkers`, but that won't give any marker genes for cluster 0, which has been explained in another issue.
PPS: I don't quite understand how `FindAllMarkers` is done: does it compare DEGs pairwise, then combine all the DEGs and information together for each cluster?

**Comment by cf98** [comment]
I just realized that I typed comma instead of dot.
Would be nice if someone can answer the questions on PS and PPS.

**Comment by Voltarikk** [comment]
I'm having this problem too.

**Comment by Voltarikk** [comment]
> 
I've solved this problem.
cluster2.markers <- FindMarkers(pbmc, ident.1 = '2', min.pct = 0.25)
head(cluster2.markers, n = 5)
