### ISSUE TITLE
cant reproduce UMAP

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [satijalab/seurat#6748]
Hey, 
recently I had to move my Seurat analysis to a new machine. However i can't seem to reproduce the UMAP plots. Clusters seem the same but they are differently located in the plot. Is there any seed changes with the recent update or any other change which would affect that? 
thanks a lot

**Comment by Jiayi-Zheng** [comment]
Based on my limited knowledge, there are some random factors involved when calculating UMAP and doing clustering. So maybe try set.seed(x) to preset the random variable might help make result repeatable?

**Comment by yuhanH** [comment]
You can find more detailed discussion in this issue: https://github.com/satijalab/seurat/issues/5358
Generally, irlba returns very slightly different results across different devices due to differences in numerical precision, and this will affect UMAP results
