### ISSUE TITLE
So could we set some parameters of seurat or R to elevate the work efficiency of CPU and RAM?

### ISSUE THREAD

**Issue by vagabond12** [satijalab/seurat#675]
The RunTSNE, FindClusters and  FindAllMarkers processes are very time consuming. We first thaught that we need more powerful workstation, but the fact is that it does not work, and our CPU and RAM are all not used with high efficiency. So could we set some parameters of seurat or R to elevate the work efficiency of CPU and RAM? Thanks.

**Comment by satijalab** [comment]
Please check out our vignette on analyzing very large datasets (https://satijalab.org/seurat/mca.html), which contains some tips on working with very large datasets (>100,000 cells).
