### ISSUE TITLE
"Warning:" for using "MAST" to find markers

### ISSUE THREAD

**Issue by zhangsiyu1997** [satijalab/seurat#6750]
When I use "MAST" in FindALLMarkers, I encounter an error. I don't know how to solve this problem. What should I do to fix it.

Seurat 4.2.1
> nc_object.markers <- FindAllMarkers(nc_object, min.pct = 0.25,logfc.threshold = 0.25,test.use = "MAST")
Calculating cluster 0
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method
Warning: When testing 1 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method
Warning: When testing 2 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method
Warning: When testing 3 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method
Warning: When testing 4 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method
Warning: When testing 5 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method
Warning: When testing 6 versus all:
	invalid name for slot of class “BayesGLMlike”: norm.method

**Comment by zhangsiyu1997** [comment]
[Hack to](https://github.com/RGLab/MAST/commit/16e90b42f071e0019d59db92ab58f41c5a9f7ab8) [resolve](https://github.com/RGLab/MAST/commit/16e90b42f071e0019d59db92ab58f41c5a9f7ab8) https://github.com/RGLab/MAST/issues/175 [and](https://github.com/RGLab/MAST/commit/16e90b42f071e0019d59db92ab58f41c5a9f7ab8) https://github.com/satijalab/seurat/issues/6489

**Comment by weixiao1991** [comment]
Norm.method pamameter is not valid. I have changed the R script for this. Please see https://github.com/weixiao1991/seurat.

**Comment by longmanz** [comment]
Hi, 
I am closing this issue for now as @saketkc has kindly fixed this issue in https://github.com/satijalab/seurat/issues/6489 . 
Will reopen it if the issue persists.
