### ISSUE TITLE
`DimPlot`'s `combine=FALSE` not returning a list of separate plots, with `split.by` set

### ISSUE THREAD

**Issue by Xrmkm** [satijalab/seurat#6751]
Related to #2645:

When I set `combine = FALSE` in `DimPlot`, I still get a patchworked, combined object (in a list with a length of 1)! This was never an issue with the Seurat code, so I wonder what I could be overlooking. I am certainly splitting by setting `split.by` to my metadata column.

![image](https://user-images.githubusercontent.com/115947650/205507739-9a2bce62-fcb6-4b47-8cd5-373f9e8910ce.png)

A list of plots should be returned, per `DimPlot` [reference](https://satijalab.org/seurat/reference/dimplot) snippet above, but I can't seem to get the list of plots returned! `Combine = FALSE` with my `FeaturePlot`, with `split.by` set, does return a list, however!

**Comment by mojaveazure** [comment]
`split.by` uses facets to perform the splits, so there's nothing that patchwork can do because it's all one ggplot object. The `combine` parameter is used with multiple `group.by` values

**Comment by Xrmkm** [comment]
Thank you, Paul.
