### ISSUE TITLE
RStudio crashes when saving plot using png()

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6752]
Hello. Is there currently an issue or an update with Seurat? Previously, everything goes perfectly well, but recently, when I save my FeaturePlot using png() and dev.off(), my RStudio always crashes.

```
png("Seurat-MMP9.png", width=10, height=4, res=1200, units="in"
FeaturePlot(Seurat, "MMP9", cols = c("lightgray", "blue"), max.cutoff = "q90", pt.size = 0.5, split.by = "groups")
dev.off()
```

Has anyone recently experienced this? Thank you.

**Comment by saketkc** [comment]
Would you need a resolution of 1200 dots per inch? It is possible that the rendering system is filling up your memory trying to generate  high resolution figure (especially so if you have a large number of cells). You can try switching on rasterization by passing `FeaturePlot(raster=TRUE)` and see if that helps. Else, I would recommend lowering the dpi (res=300 is reasonable for most use cases)
