### ISSUE TITLE
How to define the name of the sub -group of a cell？

### ISSUE THREAD

**Issue by M-jk22** [satijalab/seurat#6755]
I read some research on single-cell sequencing, and many studies will conduct more detailed clustering and annotations for certain cells, but I cannot understand their naming rules for these cell sub-groups, such as: CD4-C5-STMN1. But STMN1 is not a Marker Gene, I am confused. I have worked hard to solve this problem for a long time, but I still did not summarize the standard version of the plan.
If you can provide very standard processes and naming rules to learn, I will be grateful.

**Comment by mhkowalski** [comment]
Hello, 

Unfortunately, there is not a standardized system for annotating cells, and this will vary substantially across papers and organ systems. STMN1, for example, might refer to a subset of CD4 cells that express STMN1, but will not be a marker gene for CD4 T cells. H

If you are looking for a standardized way to annotate cells, I would recommend https://azimuth.hubmapconsortium.org/, which is designed to automate single-cell annotation for various tissues.

Hope this is helpful!
