### ISSUE TITLE
VlnPlot split.plot oiption flips the violins

### ISSUE THREAD

**Issue by huipan1973** [satijalab/seurat#6756]
Hi 

I used VlnPlot to make a plot like this
![image](https://user-images.githubusercontent.com/4342926/205751087-889388c4-1384-4b11-acd3-03b08fe9da2a.png)

However, after I added the split.plot = TRUE option, the violins flipped to the opposite sides, so the dots and violins didn't match.
![image](https://user-images.githubusercontent.com/4342926/205751568-015676d8-e899-4e2d-a62b-722398a95d63.png)

The code I used:
VlnPlot(seuratobj, features = "RPL41", split.by = "Sample", ncol = 1, split.plot = TRUE)

**Comment by torkencz** [comment]
By the looks of it not all of your clusters have both sample 1 and sample 2 in them? that is why you are getting the half violin plots?

**Comment by huipan1973** [comment]
It was because the left and right sides flipped.

Best regards,
Hui
________________________________
