### ISSUE TITLE
Questions about integration analysis workflow

### ISSUE THREAD

**Issue by HarrisHan2000** [satijalab/seurat#6759]
Hi,

Thanks for developing this potent and user-friendly tool!
 
I am now doing an integrated analysis, and I can't help but wonder about this issue:  
When analyzing datasets integrated via the V3 integration method, should I integrate again after selecting a particular subset for subsequent analysis? I suppose integrating considering all cell types must cause different transformations of data distributions compared to that considering particular cell types, right? Should I do a re-integrated or not? 

Thanks and look forward to your response.

Best,
Harris Han

**Comment by torkencz** [comment]
Hi,
I wish I could give you a straight up perfect answer but I think it depends on the problem. In my personal experience reintegration is not always necessary. Sometimes reintegration has worked for me to reveal subclusters, but considering other cell types has helped as well. I would look at the both of them and look if the biology makes sense. I apologize for not giving you a better answer.
