### ISSUE TITLE
Difference between RNA and Integrated slots in AverageExpression() of integrated dataset

### ISSUE THREAD

**Issue by Jiayi-Zheng** [satijalab/seurat#6760]
Hi, I did `profile = AverageExpression(seu.int)`, which returns me two slots, one by RNA and one by Integrated. 

I'm not sure what's the difference between them and which one should I use, if I want the transcriptome expression profile of a particular cell type in my `seu.int`?

**Comment by saketkc** [comment]
For average transcriptome profile you need the averaged "RNA" assay. You can provide `AverageExpression(assays="RNA")` to only calculate mean values for the RNA assay. See method documentation for details: https://satijalab.org/seurat/reference/averageexpression
