### ISSUE TITLE
Attach hgnc_symbols in addition to ENSEMBL_id?

### ISSUE THREAD

**Issue by Christopher-Ng** [satijalab/seurat#6763]
I have created a Seurat object via import with Alevin-Fry, and it is appropriately linked to ensembl_ids as per the GTFs used to create the SingleCellExperiment and then the import with Alevin-Fry. 

For labeling purposes and downstream, I'd love to include hgnc_symbols in addition to the ensembl_ids. Is the "best practice" for this to create new assay metadata with the hgnc_symbols? I did create one of these, but then I'm unclear of how to "Switch" the primary labels from ensembl_id to hgnc_symbol. Thanks!

**Comment by saketkc** [comment]
Current version of Seurat requires feature name remain constant throughout the analysis. If you prefer hgnc_symbols, I would recommend creating an object with hgnc_symbols before doing any downstream analysis.
