### ISSUE TITLE
Conversion of Giotto Object to Seurat

### ISSUE THREAD

**Issue by michellemlin** [satijalab/seurat#6764]
Hello,

Is it possible to convert a Giotto object to a Seurat object and keep all of the downstream analysis information currently stored in the Giotto object? 
Thank you in advance.

Best,
Michelle

**Comment by AustinHartman** [comment]
While this would be useful it's not something we currently support, but if you're interested in converting on your own the `CreateCentroids`, `CreateSegmentation` and `CreateFOV` functions will be useful
