### ISSUE TITLE
Printing a CSV file of gene marker expression in clusters

### ISSUE THREAD

**Issue by atlmalive** [satijalab/seurat#6765]
Hi all, 
I am trying to print a list of gene expressions for the following idents 0 and 3 (clusters) for CD14, AIF1, FTL etc. 

This is currently what I am using which works. 
**length(WhichCells(sovs01sc, idents = c(0,3), expression = CD14 > 0))**

I was trying this:
**length(WhichCells(sovs01sc, idents = c(0,3), expression = CD14 > 0, expression = AIF1 > 0, expression = FTL > 0)) which gave me this error:** "_Error in WhichCells.Seurat(sovs01sc, idents = c(0, 3), expression = CD14 >  : 
  formal argument "expression" matched by multiple actual arguments_"

This there a way to get a list of multiple gene markers? I was thinking that it could be done with a loop but I'm not certain. Any help will be appreciated.

**Comment by mojaveazure** [comment]
You can chain expressions in `WhichCells` using the standard R construct with `&` and `|` (not `&&` or `||`)

```R
CD14 > 0 & AIF1 > 0
```

**Comment by atlmalive** [comment]
@mojaveazure I tried chaining the expressions as: length(WhichCells(obj, idents = c(0,3), expression = CD14 > 0 | FTL > 0)) which I get a count of 57. I was trying to get a list of the number of the 2 genes. When I run:

length(WhichCells(sovs01sn, idents = macro, expression = CD14 > 0)) ## counts = 4
length(WhichCells(sovs01sn, idents = macro, expression = FTL > 0)) ## counts = 55

Both add up to be a different number than the chain expression.

Any suggestions?
