### ISSUE TITLE
Issue with Read10X_h5

### ISSUE THREAD

**Issue by zvan14** [satijalab/seurat#6766]
I have used this function before on a mac and I had no issues, but when using windows I can't get the function to work. I am not sure if it has to do with the fact that I am using windows, but I am at a lost on what to do. I have tried moving the file around and copying its path, but I kept getting this issue. I also have left out the C: but the function still will not go through.

> RL2103 <-Read10X_h5("C:/Herring_Project/Herring_Files/RL2103_ga22_snRNAseq_raw_matrix.h5.gz", use.names = TRUE, unique.features = TRUE)
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5F.c in H5Fopen(): line 604: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Fint.c in H5F_open(): line 1087: unable to read superblock
        class: HDF5
        major: File accessibilty
        minor: Read failed

    error #002: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Fsuper.c in H5F_super_read(): line 277: file signature not found
        class: HDF5
        major: File accessibilty
        minor: Not an HDF5 file

**Comment by mojaveazure** [comment]
This is a gzipped HDF5 file, which hdf5r on Windows cannot natively handle. Try ungzipping it before reading it in
