### ISSUE TITLE
Count gene markers 

### ISSUE THREAD

**Issue by atlmalive** [satijalab/seurat#6770]
Hi all,

I am trying to write a code that lists the number of gene markers (ex. CD14, AIF1, CD4, etc) present in each cluster in a CSV file. I wanted to combine these three markers in one line of code and tried: 
**length(WhichCells(sovs01sc, idents = c(0,3), expression = CD14 > 0,  expression = AIF1 > 0, expression = CD4 > 0))** but I received an error: _"Error in WhichCells.Seurat(sovs01sc, idents = c(0, 3), expression = CD14 >  : 
  formal argument "expression" matched by multiple actual arguments"_

This is what I have so far. These 3 lines of code work separately but it is tedious to run each one and then write the gene marker count in an excel file. 
**length(WhichCells(sovs01sc, idents = c(0,3), expression = CD14 > 0))
length(WhichCells(sovs01sc, idents = c(0,3), expression = AIF1 > 0))
length(WhichCells(sovs01sc, idents = c(0,3), expression = CD4 > 0))**

Any assistance will be greatly appreciated.

**Comment by alikhuseynov** [comment]
HI there, 
the code below should work, it gives total number cells expressing selected gene in specific cluster(s).
Is that what you are looking for?

```
## Example on PBMC (small) object
DefaultAssay(pbmc_small) <- "RNA"
Idents(pbmc_small) <- "RNA_snn_res.1" # set clusters
# selected markers
genes <- c("AIF1", "CD4", "CD14")
# check if selected markers are present in the object
genes %<>% intersect(rownames(pbmc_small))
thres = 0 # threshold for expression level, eg > 3 counts
cells.out <- 
lapply(seq(genes), function (i) 
{ which(FetchData(pbmc_small, 
                  slot = "data",
                  cell = WhichCells(pbmc_small, idents = c("0", "1")), # only cells for cluster "0" and "1"
                  vars = genes[i]) > thres, 
        arr.ind = TRUE, 
        useNames = TRUE) %>% rownames %>% length }
                 )
# add names to a list
names(cells.out) <- genes
cells.out %>% str
List of 2
 $ AIF1: int 32
 $ CD14: int 13
```

**Comment by atlmalive** [comment]
This was very helpful! Thank you so much!
