### ISSUE TITLE
FoldChange vs FindMarkers give differnet log fc results

### ISSUE THREAD

**Issue by coralzhang** [satijalab/seurat#6773]
I encountered a similar issue reported here https://www.biostars.org/p/9478554/ 
Here is an example, 
`mat1=FoldChange(pbmc_small, ident.1 = 1); 
mat2 <- FindMarkers(object = pbmc_small, ident.1 = 1); 
mat1["MS4A1",]; mat2["MS4A1",]; `
This is the output: 
> mat1["MS4A1",]
              avg_log2FC pct.1 pct.2
MS4A1 **-0.6837357**  0.08 0.182
> 
> mat2["MS4A1",]
                p_val            avg_log2FC pct.1 pct.2 p_val_adj
MS4A1 0.1840551  **-4.289191**  0.08 0.182         1
>

**Comment by longmanz** [comment]
Hi,
Can you try the latest version of Seurat? This logfc issue should be fixed now.

**Comment by coralzhang** [comment]
Thank you for your response. But I tried to reinstall using this
`install_github("satijalab/seurat")`
Then tried this 
`> library(Seurat)
>  mat1=FoldChange(pbmc_small, ident.1 = 1); mat2 <- FindMarkers(object = pbmc_small, ident.1 = 1); mat1["MS4A1",]; mat2["MS4A1",]; 
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
      avg_log2FC pct.1 pct.2
MS4A1 -0.6837357  0.08 0.182
          p_val avg_log2FC pct.1 pct.2 p_val_adj
MS4A1 0.1840551  -4.289191  0.08 0.182         1`

Here is the sessioninfo

> sessionInfo()
> R version 4.2.1 (2022-06-23)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Big Sur ... 10.16
> 
> Matrix products: default
> BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] devtools_2.4.5     usethis_2.1.6      SeuratObject_4.1.3 Seurat_4.3.0      
> 
> 
>

**Comment by lucygarner** [comment]
Hi,

I am having the same issue with Seurat 4.3.0. The `FoldChange` and `FindMarkers` functions give me very different fold change values. The DefaultAssay of my Seurat object is "RNA".

```
markers <- FindMarkers(seurat_obj, ident.1 = "TCR", ident.2 = "unstim")
fold_change <- FoldChange(seurat_obj, ident.1 = "TCR", ident.2 = "unstim")
```

`markers["CCL4", ]`
     p_val avg_log2FC pct.1 pct.2 p_val_adj
CCL4     0   5.550652 0.962 0.685         0

`fold_change["CCL4", ]`
     avg_log2FC pct.1 pct.2
CCL4   1.264632 0.962 0.685

Your advice or explanation would be much appreciated. Which are the "correct" fold change values? I would like to obtain fold change values for all genes.

Best wishes,
Lucy

**Comment by saketkc** [comment]
Apologies everyone for the delay.

I have just pushed https://github.com/satijalab/seurat/commit/992c1a96693b1467160969625edc8a5c80ab0867 to develop branch which should fix this and related issues. Can you pull from the develop branch and re-open this issue if you are still facing issues?

```r
devtools::install_github("satijalab/seurat", branch="develop")
```
