### ISSUE TITLE
seurat subset function error: Error in .nextMethod(x = x, i = i) : NAs not permitted in row index

### ISSUE THREAD

**Issue by yhlstiic** [satijalab/seurat#6774]
I am trying to subset a seurat object obtained from CosMx's nanostring scRNA-seq dataset using the following code:

`CosMx_T <- subset(CosMx, idents = "Tumour")`

But it will reproduce this error:

`Error in .nextMethod(x = x, i = i) : NAs not permitted in row index`

It doesn't matter what identity I use, but it does not allow me to subset my seurat object. I have checked for NAs within my sample and I couldn't find any 'NA' within the Nanostring assay or meta.data.

```
> sum(is.na(CosMx@assays$Nanostring@data@x))
[1] 0
> 
> sum(is.na(CosMx@meta.data))
[1] 0
```

However, this code works fine for my other seurat object obtained from 10X genomics' scRNA-seq dataset.

**Comment by alikhuseynov** [comment]
Hi, 
I'm not from Seurat team, however take a look these issues #6409 #6683 #6248, they might help.
Make sure your `Images(CosMx)` name does not have underscores `"_"` or any other special characters, the `"."` char works well for separate names.
 
eg in my case it looks like this:
```
Images(obj)
'cellpose.resolve.w6'
# if needed, renaming FOV works like this
names(obj@images) <- "my.fov.name"

```

**Comment by mhkowalski** [comment]
Apologies for our slow response, thanks for the solution. Please open a new issue if you continue to have difficulties.

**Comment by Pointillomic** [comment]
Hi all, 

In case anyone else has the same issue, the solution for me was actually solving a different (/opposite) naming issue - in my particular dataset, the cells were named with "." in them.

This was a problem as Crop internally calls the Overlay function, which in turn has the following inside:
names(x = idx) <- vapply(X = strsplit(x = names(x = idx), 
    split = "\\."), FUN = "[[", FUN.VALUE = character(length = 1L), 
    1L, USE.NAMES = FALSE)

This causes an issue if your cells were labeled in the format "[experiment].[cell]"

You can fix this using RenameCells, which successfully renames the cells in the images slot as well (I replaced the "." with "-")

**Comment by Evenlyeven** [comment]
> Hi all,
> 
> In case anyone else has the same issue, the solution for me was actually solving a different (/opposite) naming issue - in my particular dataset, the cells were named with "." in them.
> 
> This was a problem as Crop internally calls the Overlay function, which in turn has the following inside: names(x = idx) <- vapply(X = strsplit(x = names(x = idx), split = "\."), FUN = "[[", FUN.VALUE = character(length = 1L), 1L, USE.NAMES = FALSE)
> 
> This causes an issue if your cells were labeled in the format "[experiment].[cell]"
> 
> You can fix this using RenameCells, which successfully renames the cells in the images slot as well (I replaced the "." with "-")

This solved my issue after ~48hrs exploration. I cannot thank you enough!!!
