### ISSUE TITLE
How to create a joint visualization from bridge integration?

### ISSUE THREAD

**Issue by Chengwei94** [satijalab/seurat#6778]
Hi there,

How do I create a joint visualization from bridge integration like this, since the tutorial only have mapping? Is it through the normal integration procedure but using bridge.anchors instead? 

<img width="203" alt="image" src="https://user-images.githubusercontent.com/61018420/206897354-bbcda8f3-152d-4c09-8d89-7fb166cdbf13.png">

**Comment by yuhanH** [comment]
hi @Chengwei94 
do you mean joint visualization of reference and query?

**Comment by yuhanH** [comment]
You can use `FindBridgeIntegrationAnchors` and `IntegrateEmbeddings` to get the merged object with dictionary representation for both query and reference.
