### ISSUE TITLE
Is NormalizeData() needed after SubsetData()?

### ISSUE THREAD

**Issue by CMC-LI** [satijalab/seurat#678]
Hi there, 

I have a Seurat object containing scRNA-seq data combined from 6 samples, and the object has already undergone NormalizeData() and the rest of the Seurat pipeline. What I wanted to do next is to re-analyze a subset that includes only 4 of the 6 samples.

My question is: after using Subsetdata() to create a new Seurat object, do I need to re-run NormalizeData() on this new object? 

My understanding is that re-running NormalizeData() will not be necessary, because that normalization was done on a per-cell basis (normalizing each gene expression within a cell to the total expression within that cell), and adding or subtracting additional samples or cells will not make any difference to how the data is normalized within each cell. 

Is my understanding correct? 

I am learning the Seurat pipeline and will appreciate some guidance. Thank you!

**Comment by satijalab** [comment]
That is correct - you do not need to renormalize.
