### ISSUE TITLE
Reference scRNA-seq dataset for skin

### ISSUE THREAD

**Issue by rajeha** [satijalab/seurat#6780]
Thank you all for this awesome tool. I saw in the [spatial vignette](https://satijalab.org/seurat/articles/spatial_vignette.html) that Seurat can identify cell types in the brain using a reference scRNA-seq dataset. Would you recommend a similar reference dataset but for the skin? If not, what other method would you recommend for cell-type annotation?

**Comment by Gesmira** [comment]
Hi! 
I would recommend using the data from [this paper](https://www.science.org/doi/10.1126/science.aba6500) as a scRNA-seq reference. The data can be downloaded and visualized [here](https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-8142/results/tsne?ref=biostudies).
