### ISSUE TITLE
merging Seurat objects but not getting a unique orig.ident

### ISSUE THREAD

**Issue by haileyani** [satijalab/seurat#6783]
Hi,
I am trying to merge two seu.rds files using the following command:

WTKOFL.merged <- merge(x=WTFL, y =KOFL , add.cell.ids = c("WT", "KO"), project = "WTKOFL", merge.data = TRUE)

but I get data that does not distinguish the cell IDs in the orig.ident column. The column only gives me Seurat Project and not the "WT", "KO" that was specified with add.cell.ids.

Can anyone help me solve this problem?
Thank you

The merged data looks like this:
table(WTKOFL.merged$orig.ident)
#SeuratProject
#        9072
##orig.ident nCount_RNA nFeature_RNA percent.mt
WT_AAACAGCCAAGCTTTG-1 SeuratProject      10823         3635   14.35831
WT_AAACAGCCAGGTTATT-1 SeuratProject      10027         3617   10.84073
                      RNA_snn_res.0.5 seurat_clusters      
WT_AAACAGCCAAGCTTTG-1               1               1 
WT_AAACAGCCAGGTTATT-1               0               0 
                      pANN_0.25_0.01_3541 DF.classifications_0.25_0.01_3541
WT_AAACAGCCAAGCTTTG-1                  NA                              <NA>
WT_AAACAGCCAGGTTATT-1                  NA                              <NA>

**Comment by samuel-marsh** [comment]
Hi @alikhuseynov,

Is correct.  Adding cell ids changes the cell barcodes (in part to avoid name collision) but does not alter the orig.ident.  You can either do as @alikhuseynov suggests or you can do after merge using and if else statement specifying new barcode prefixes.

Best,
Sam
