### ISSUE TITLE
Normalizing data in AvgExpression fx (seurat) 

### ISSUE THREAD

**Issue by atlmalive** [satijalab/seurat#6785]
Hi all,

I am trying to get the average expression of a set of genes within several different clusters. What I am trying to do is normalize that data. 

My script is as follows: **cluster.averages <- AverageExpression(soVS01sc)
write.table(write.csv(cluster.averages[["RNA"]][, 1:8],"results/avgExVS01sc.csv"))**

But I am getting large numbers such as 86 for CD74 among one of my clusters. 
**What I am trying to do is scale or normalize them (not sure what the right term is, if any) so that the highest possible expression is 1 while no expression is 0.** This is so I can plot it on a graph and see if the avg expression is associated with tumor growth. 

I've tried using the slot = 'scale.data' and 'counts' to get a range of 0 to 1 but sometimes I will still get a number much larger than 1 or negative numbers (not exactly sure why I would be getting negative numbers) 

For an example, see below: 
**d = AverageExpression(object = sovs01sn, return.seurat = F, slot = 'counts')
write.csv (d, 'results/counts1.csv')** 

Any help would be greatly appreciated!

**Comment by alikhuseynov** [comment]
`"scaled.data"` are z-scores
`AverageExpression()` on `slot = "data"` exponentiates values before averaging. see `?AverageExpression`
If you want to scale your average expression matrix to a range of 0 to 1 per cluster, then you can do this:

```
# eg on small PBMC object
library(magrittr) # for pipe %>% operator
obj <- pbmc_small
avg.mat <- AverageExpression(obj, assays = "RNA", slot = "data", 
                             group.by = "RNA_snn_res.0.8") %>% .[[1]]
avg.mat %>% head #..normalized values non-log scale!

# scale per cluster
scaled.avg.mat <- 
  sapply(colnames(avg.mat) %>% seq, function (i) { 
    scales::rescale(log1p(avg.mat)[,i], # apply log1p() on them if necessary
                    to = c(0,1)) })
quantile(scaled.avg.mat, c(0.01, 1)) # check expression range
dimnames(scaled.avg.mat)[[2]] <- colnames(avg.mat) # add cluster names
scaled.avg.mat %>% str
scaled.avg.mat %>% range
# [1] 0 1
```
best

**Comment by saketkc** [comment]
@alikhuseynov You need to make sure the data has been normalized (`NormalizeData` if you are using LogNormalization or `SCTransform`) before running `AverarageExpression`.

**Comment by atlmalive** [comment]
@alikhuseynov and @saketkc Thanks for helping with this issue! I was able to run the code with success!
