### ISSUE TITLE
'segs" not found with LoadNanostring function

### ISSUE THREAD

**Issue by WesDe** [satijalab/seurat#6786]
Hi,

Questions related to https://github.com/satijalab/seurat/issues/6521, I am trying to load Nanostring data using LoadNanostring function but an error rises revealing the absence of "segs" information:
`nano.1<-LoadNanostring("Lung6/Lung6-Flat_files_and_images/", fov="Lung6")`
`Error in data.frame(x = segs$x_global_px, y = segs$y_global_px, cell = paste0(as.character(segs$cellID),  : 
  object 'segs' not found `

Do segmentation files are related to RawMorphological directory  and are not contained in the data files directory from the public dataset ?

Best,

**Comment by AustinHartman** [comment]
The segmentation polygons are a non-default Nanostring CosMx SMI output which the LoadNanostring function expects to be present. For lung 5 you can access them here: [https://www.dropbox.com/s/hl3peavrx92bluy/Lung5_Rep1-polygons.csv?dl=0](https://www.dropbox.com/s/hl3peavrx92bluy/Lung5_Rep1-polygons.csv?dl=0). For datasets where the segmentations aren't available, I'd recommend using `ReadNanostring` similar to this:
```r
data <- ReadNanostring(data.dir = data.dir, type = "centroids")
cents <- CreateCentroids(data$centroids)
coords <- CreateFOV(coords = list("centroids" = cents), type = "centroids")
obj <- CreateSeuratObject(counts = data$matrix)
obj[["fov"]]<-subset(coords, cell=Cells(obj))
```

**Comment by WesDe** [comment]
It works perfectly thank you !

**Comment by Gitman0810** [comment]
> The segmentation polygons are a non-default Nanostring CosMx SMI output which the LoadNanostring function expects to be present. For lung 5 you can access them here: https://www.dropbox.com/s/hl3peavrx92bluy/Lung5_Rep1-polygons.csv?dl=0. For datasets where the segmentations aren't available, I'd recommend using `ReadNanostring` similar to this:
> 
> ```r
> data <- ReadNanostring(data.dir = data.dir, type = "centroids")
> cents <- CreateCentroids(data$centroids)
> coords <- CreateFOV(coords = list("centroids" = cents), type = "centroids")
> obj <- CreateSeuratObject(counts = data$matrix)
> obj[["fov"]]<-subset(coords, cell=Cells(obj))
> ```

Hi AustinHartman!

Thank you for your explaination! However, the segmentation polygons file you shared no longer exists. Could you please upload it again? Many thanks in advance!

**Comment by adityakangune** [comment]
The file "Lung5_Rep1-polygons.csv" seems to be deleted from https://www.dropbox.com/s/hl3peavrx92bluy/Lung5_Rep1-polygons.csv?dl=0. 
Is there any other way to get the file?
Thank you!
