### ISSUE TITLE
IntegrateData ends with "unable to coerce from TsparseMatrix to [CR]sparseMatrixwhen length of 'i' slot exceeds 2^31-1"

### ISSUE THREAD

**Issue by zorglubz-coder** [satijalab/seurat#6787]
Hi,
Thank you for providing this amazing tool!

I am trying to integrate 20 samples, for a total of 85,000 cells.
I am following the "Performing integration on datasets normalized with SCTransform" from [https://satijalab.org/seurat/articles/integration_rpca.html](https://satijalab.org/seurat/articles/integration_rpca.html) almost to the letter. I am just using the v2 of SCTransform.

```
list_of_seurat_object <- lapply(X = list_of_seurat_object, FUN = SCTransform, method = "glmGamPoi", vst.flavor = "v2")
features <- SelectIntegrationFeatures(object.list = list_of_seurat_object, nfeatures = 3000)
list_of_seurat_object <- PrepSCTIntegration(object.list = list_of_seurat_object, anchor.features = features)
list_of_seurat_object <- lapply(X = list_of_seurat_object, FUN = RunPCA, features = features)
immune.anchors <- FindIntegrationAnchors(object.list = list_of_seurat_object, normalization.method = "SCT",
    anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 20)
immune.combined.sct <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT", dims = 1:30)
```

At first the process crashed the computer, I am now running it with 500 Gb of memory.

My issue now is that the function IntegrateData ends with this error message:

> Integrating data
> Merging dataset 15 into 5 4 3 18 13
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 5 4 3 18 13 15 into 16 11 14 10 6 9 19 7 8 2
> Extracting anchors for merged samples
> Finding integration vectors
> Error in .T2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  :
>   unable to coerce from TsparseMatrix to [CR]sparseMatrixwhen length of 'i' slot exceeds 2^31-1

I have looked around, and I could not find this error message in other issues.
Is there a workaround for me to integrate my data?

Here is my session info

> R version 4.2.2 Patched (2022-11-10 r83330)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 22.04.1 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so
> 
> locale:
>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> other attached packages:
>  [1] SeuratObject_4.1.3 Seurat_4.3.0.9001  readxl_1.4.1       glmGamPoi_1.10.1
>  [5] anndata_0.7.5.5    clustree_0.5.0     ggraph_2.1.0       patchwork_1.1.2
>  [9] ape_5.6-2          Matrix_1.5-3       SCINA_1.2.0        gplots_3.1.3
> [13] MASS_7.3-58.1      sleepwalk_0.3.2    forcats_0.5.2      stringr_1.5.0
> [17] purrr_0.3.5        readr_2.1.3        tidyr_1.2.1        tibble_3.1.8
> [21] tidyverse_1.3.2    sctransform_0.3.5  ggplot2_3.4.0      dplyr_1.0.10
> 
> loaded via a namespace (and not attached):
>   [1] backports_1.4.1             plyr_1.8.8
>   [3] igraph_1.3.5                lazyeval_0.2.2
>   [5] sp_1.5-1                    splines_4.2.2
>   [7] jrc_0.5.1                   listenv_0.8.0
>   [9] scattermore_0.8             GenomeInfoDb_1.34.4
>  [11] digest_0.6.31               htmltools_0.5.4
>  [13] viridis_0.6.2               fansi_1.0.3
>  [15] magrittr_2.0.3              tensor_1.5
>  [17] googlesheets4_1.0.1         cluster_2.1.4
>  [19] ROCR_1.0-11                 tzdb_0.3.0
>  [21] globals_0.16.2              graphlayouts_0.8.4
>  [23] modelr_0.1.10               matrixStats_0.63.0
>  [25] R.utils_2.12.2              spatstat.sparse_3.0-0
>  [27] timechange_0.1.1            colorspace_2.0-3
>  [29] rvest_1.0.3                 ggrepel_0.9.2
>  [31] haven_2.5.1                 crayon_1.5.2
>  [33] RCurl_1.98-1.9              jsonlite_1.8.4
>  [35] spatstat.data_3.0-0         progressr_0.12.0
>  [37] survival_3.4-0              zoo_1.8-11
>  [39] glue_1.6.2                  polyclip_1.10-4
>  [41] gtable_0.3.1                gargle_1.2.1
>  [43] zlibbioc_1.44.0             XVector_0.38.0
>  [45] leiden_0.4.3                DelayedArray_0.24.0
>  [47] future.apply_1.10.0         BiocGenerics_0.44.0
>  [49] abind_1.4-5                 scales_1.2.1
>  [51] DBI_1.1.3                   spatstat.random_3.0-1
>  [53] miniUI_0.1.1.1              Rcpp_1.0.9
>  [55] xtable_1.8-4                viridisLite_0.4.1
>  [57] reticulate_1.26             stats4_4.2.2
>  [59] htmlwidgets_1.6.0           httr_1.4.4
>  [61] RColorBrewer_1.1-3          ellipsis_0.3.2
>  [63] ica_1.0-3                   pkgconfig_2.0.3
>  [65] R.methodsS3_1.8.2           farver_2.1.1
>  [67] uwot_0.1.14                 deldir_1.0-6
>  [69] dbplyr_2.2.1                utf8_1.2.2
>  [71] tidyselect_1.2.0            rlang_1.0.6
>  [73] reshape2_1.4.4              later_1.3.0
>  [75] munsell_0.5.0               cellranger_1.1.0
>  [77] tools_4.2.2                 cli_3.4.1
>  [79] generics_0.1.3              broom_1.0.2
>  [81] ggridges_0.5.4              fastmap_1.1.0
>  [83] goftest_1.2-3               fs_1.5.2
>  [85] fitdistrplus_1.1-8          tidygraph_1.2.2
>  [87] caTools_1.18.2              RANN_2.6.1
>  [89] pbapply_1.6-0               future_1.29.0
>  [91] nlme_3.1-161                mime_0.12
>  [93] R.oo_1.25.0                 xml2_1.3.3
>  [95] compiler_4.2.2              plotly_4.10.1
>  [97] png_0.1-8                   spatstat.utils_3.0-1
>  [99] reprex_2.0.2                tweenr_2.0.2
> [101] stringi_1.7.8               lattice_0.20-45
> [103] vctrs_0.5.1                 pillar_1.8.1
> [105] lifecycle_1.0.3             spatstat.geom_3.0-3
> [107] lmtest_0.9-40               RcppAnnoy_0.0.20
> [109] data.table_1.14.6           cowplot_1.1.1
> [111] bitops_1.0-7                irlba_2.3.5.1
> [113] httpuv_1.6.7                GenomicRanges_1.50.1
> [115] R6_2.5.1                    promises_1.2.0.1
> [117] KernSmooth_2.23-20          gridExtra_2.3
> [119] IRanges_2.32.0              parallelly_1.33.0
> [121] codetools_0.2-18            gtools_3.9.4
> [123] assertthat_0.2.1            SummarizedExperiment_1.28.0
> [125] withr_2.5.0                 S4Vectors_0.36.1
> [127] GenomeInfoDbData_1.2.9      parallel_4.2.2
> [129] hms_1.1.2                   grid_4.2.2
> [131] MatrixGenerics_1.10.0       googledrive_2.0.0
> [133] Rtsne_0.16                  spatstat.explore_3.0-5
> [135] ggforce_0.4.1               shiny_1.7.4
> [137] Biobase_2.58.0              lubridate_1.9.0

**Comment by saketkc** [comment]
With 20 datasets I would recommend using RPCA or reference based integration. [This vignette](https://satijalab.org/seurat/articles/integration_large_datasets.html) offers some tips that should be helpful!

**Comment by zorglubz-coder** [comment]
Thanks, I made four of my samples reference, and it is working great!

**Comment by hoonghim** [comment]
Dear @saketkc ,

Hello, I am also having the same problem after following the vignette you recommended.

I tried reference based integration after running SCTransform.

The same error still occurs during the IntegrateData step.

Here are my codes and error messages.

```
# Read Seurat object
x.obj.filter <- readRDS(file = x.file)

# Run FindVariableFeatures
x.obj.filter <- FindVariableFeatures(object = x.obj.filter, selection.method = "vst")
  
#   Regress out cell cycle scores
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
  
x.obj.filter <- CellCycleScoring(x.obj.filter, s.features = s.genes, g2m.features = g2m.genes, set.ident = T)
  
x.obj.filter <- ScaleData(object = x.obj.filter, features = rownames(x.obj.filter), vars.to.regress = c("nCount_RNA", "percent.mt", "S.Score", "G2M.Score"))  
  
# Perform linear dimensional reduction
x.obj.filter <- RunPCA(object = x.obj.filter, features = VariableFeatures(object = x.obj.filter), npcs = 50)

#######
# Run SCTransform and integrate data using CCA

# Split Seurat object by sample
rds.list <- SplitObject(x.obj.filter, split.by = "orig.ident")

# Run SCTransform
for (i in names(rds.list)) {
    print(i)
    rds.list[[i]] <- SCTransform(rds.list[[i]], verbose = FALSE, vars.to.regress = c("nCount_RNA", "percent.mt", "S.Score", "G2M.Score"), method="glmGamPoi")
}
    
rds.features <- SelectIntegrationFeatures(object.list = rds.list, nfeatures = 3000)

rds.list <- PrepSCTIntegration(object.list = rds.list, anchor.features = rds.features)

# Set reference dataset using normal sample indices
reference_dataset <- which(!grepl(pattern = "DIS|^01-D", names(rds.list)))
        
# Run FindIntegrationAnchors using reference dataset
rds.anchors <- FindIntegrationAnchors(object.list = rds.list, 
                                      normalization.method = "SCT",
                                      anchor.features = rds.features, 
                                      reference = reference_dataset)
# Run IntegrateData
rds.integrated <- IntegrateData(anchorset = rds.anchors, normalization.method = "SCT")

Integrating data
Merging dataset 8 into 10 11 68 78 77 61 65
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 66 into 69 72 73 74 64
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 70 79 into 67 75 62
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 9 into 10 11 68 78 77 61 65 8
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 76 into 69 72 73 74 64 66
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 67 75 62 70 79 into 69 72 73 74 64 66 76
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 10 11 68 78 77 61 65 8 9 into 69 72 73 74 64 66 76 67 75 62 70 79
Extracting anchors for merged samples
Finding integration vectors
Error in .T2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  :
  unable to coerce from TsparseMatrix to [CR]sparseMatrixwhen length of 'i' slot exceeds 2^31-1
In addition: There were 50 or more warnings (use warnings() to see the first 50)
>     reference_dataset
 [1]  8  9 10 11 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79
> warnings()
Warning messages:
1: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0) [2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
2: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0) [2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
...
50: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0) [2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.

  
```

Here is my session info
```

R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /BiO/Live/hoonkim/.Renv/versions/R-4.0.5/lib/R/lib/libRblas.so
LAPACK: /BiO/Live/hoonkim/.Renv/versions/R-4.0.5/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] future_1.30.0      stringr_1.5.0      patchwork_1.1.2    ggplot2_3.4.0
 [5] SeuratData_0.2.2   harmony_0.1.1      Rcpp_1.0.9         Cairo_1.6-0
 [9] doMC_1.3.8         iterators_1.0.14   foreach_1.5.2      RColorBrewer_1.1-3
[13] SeuratObject_4.1.3 Seurat_4.3.0

loaded via a namespace (and not attached):
 [1] nlme_3.1-152           matrixStats_0.63.0     spatstat.sparse_3.0-0
 [4] RcppAnnoy_0.0.20       httr_1.4.4             sctransform_0.3.5
 [7] tools_4.0.5            utf8_1.2.2             R6_2.5.1
[10] irlba_2.3.5.1          KernSmooth_2.23-18     uwot_0.1.14
[13] DBI_1.1.3              lazyeval_0.2.2         colorspace_2.0-3
[16] withr_2.5.0            sp_1.5-1               tidyselect_1.2.0
[19] gridExtra_2.3          compiler_4.0.5         progressr_0.12.0
[22] cli_3.5.0              spatstat.explore_3.0-5 plotly_4.10.1
[25] scales_1.2.1           lmtest_0.9-40          spatstat.data_3.0-0
[28] ggridges_0.5.4         pbapply_1.6-0          rappdirs_0.3.3
[31] goftest_1.2-3          digest_0.6.31          spatstat.utils_3.0-1
[34] pkgconfig_2.0.3        htmltools_0.5.4        parallelly_1.33.0
[37] fastmap_1.1.0          htmlwidgets_1.6.0      rlang_1.0.6
[40] shiny_1.7.4            generics_0.1.3         zoo_1.8-11
[43] jsonlite_1.8.4         spatstat.random_3.0-1  ica_1.0-3
[46] dplyr_1.0.10           magrittr_2.0.3         Matrix_1.5-3
[49] munsell_0.5.0          fansi_1.0.3            abind_1.4-5
[52] reticulate_1.26        lifecycle_1.0.3        stringi_1.7.8
[55] MASS_7.3-53.1          Rtsne_0.16             plyr_1.8.8
[58] grid_4.0.5             listenv_0.9.0          promises_1.2.0.1
[61] ggrepel_0.9.2          crayon_1.5.2           deldir_1.0-6
[64] miniUI_0.1.1.1         lattice_0.20-41        cowplot_1.1.1
[67] splines_4.0.5          tensor_1.5             pillar_1.8.1
[70] igraph_1.3.5           spatstat.geom_3.0-3    future.apply_1.10.0
[73] reshape2_1.4.4         codetools_0.2-18       leiden_0.4.3
[76] glue_1.6.2             data.table_1.14.6      png_0.1-8
[79] vctrs_0.5.1            httpuv_1.6.7           polyclip_1.10-4
[82] gtable_0.3.1           RANN_2.6.1             purrr_1.0.0
[85] tidyr_1.2.1            scattermore_0.8        assertthat_0.2.1
[88] mime_0.12              xtable_1.8-4           later_1.3.0
[91] survival_3.2-10        viridisLite_0.4.1      tibble_3.1.8
[94] cluster_2.1.1          globals_0.16.2         fitdistrplus_1.1-8
[97] ellipsis_0.3.2         ROCR_1.0-11

```

![image](https://user-images.githubusercontent.com/42195952/211950059-9ec7b704-e188-45c0-a127-406c86f7b069.png)

Any suggestions would be of great help.

Sincerely,

Seunghoon

**Comment by zorglubz-coder** [comment]
Hi @hoonghim,
How man datasets are you using for your reference?
I only used four, and the issue is if you use too many in the FindIntegrationAnchors, then it is too much for IntegrateData.
I don't knwo the max number of datasets you can use, but you should try running only on a few of them (less than 5) and see if this is woking.
Then you can try to repeat with more and more. But too many is the issue (in my opinion as a Seurat user)

**Comment by luzzhou** [comment]
> Dear @saketkc ,
> 
> Hello, I am also having the same problem after following the vignette you recommended.
> 
> I tried reference based integration after running SCTransform.
> 
> The same error still occurs during the IntegrateData step.
> 
> I am utilizing ~400,000 cells from 86 samples (25 samples are from public normal dataset).
> 
> Could the dataset being too large have something to do with this problem?
> 
> Here are my codes and error messages.
> 
> ```
> # Read Seurat object
> x.obj.filter <- readRDS(file = x.file)
> 
> # Run FindVariableFeatures
> x.obj.filter <- FindVariableFeatures(object = x.obj.filter, selection.method = "vst")
>   
> #   Regress out cell cycle scores
> s.genes <- cc.genes$s.genes
> g2m.genes <- cc.genes$g2m.genes
>   
> x.obj.filter <- CellCycleScoring(x.obj.filter, s.features = s.genes, g2m.features = g2m.genes, set.ident = T)
>   
> x.obj.filter <- ScaleData(object = x.obj.filter, features = rownames(x.obj.filter), vars.to.regress = c("nCount_RNA", "percent.mt", "S.Score", "G2M.Score"))  
>   
> # Perform linear dimensional reduction
> x.obj.filter <- RunPCA(object = x.obj.filter, features = VariableFeatures(object = x.obj.filter), npcs = 50)
> 
> #######
> # Run SCTransform and integrate data using CCA
> 
> # Split Seurat object by sample
> rds.list <- SplitObject(x.obj.filter, split.by = "orig.ident")
> 
> # Run SCTransform
> for (i in names(rds.list)) {
>     print(i)
>     rds.list[[i]] <- SCTransform(rds.list[[i]], verbose = FALSE, vars.to.regress = c("nCount_RNA", "percent.mt", "S.Score", "G2M.Score"), method="glmGamPoi")
> }
>     
> rds.features <- SelectIntegrationFeatures(object.list = rds.list, nfeatures = 3000)
> 
> rds.list <- PrepSCTIntegration(object.list = rds.list, anchor.features = rds.features)
> 
> # Set reference dataset using normal sample indices
> reference_dataset <- which(!grepl(pattern = "DIS|^01-D", names(rds.list)))
>         
> # Run FindIntegrationAnchors using reference dataset
> rds.anchors <- FindIntegrationAnchors(object.list = rds.list, 
>                                       normalization.method = "SCT",
>                                       anchor.features = rds.features, 
>                                       reference = reference_dataset)
> # Run IntegrateData
> rds.integrated <- IntegrateData(anchorset = rds.anchors, normalization.method = "SCT")
> 
> Integrating data
> Merging dataset 8 into 10 11 68 78 77 61 65
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 66 into 69 72 73 74 64
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 70 79 into 67 75 62
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 9 into 10 11 68 78 77 61 65 8
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 76 into 69 72 73 74 64 66
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 67 75 62 70 79 into 69 72 73 74 64 66 76
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 10 11 68 78 77 61 65 8 9 into 69 72 73 74 64 66 76 67 75 62 70 79
> Extracting anchors for merged samples
> Finding integration vectors
> Error in .T2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  :
>   unable to coerce from TsparseMatrix to [CR]sparseMatrixwhen length of 'i' slot exceeds 2^31-1
> In addition: There were 50 or more warnings (use warnings() to see the first 50)
> >     reference_dataset
>  [1]  8  9 10 11 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79
> > warnings()
> Warning messages:
> 1: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0) [2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
> 2: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0) [2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
> ...
> 50: Detected creation of a 'multiprocess' future. Strategy 'multiprocess' is deprecated in future (>= 1.20.0) [2020-10-30]. Instead, explicitly specify either 'multisession' (recommended) or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'.
> 
>   
> ```
> 
> Here is my session info
> 
> ```
> 
> R version 4.0.5 (2021-03-31)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 22.04.1 LTS
> 
> Matrix products: default
> BLAS:   /BiO/Live/hoonkim/.Renv/versions/R-4.0.5/lib/R/lib/libRblas.so
> LAPACK: /BiO/Live/hoonkim/.Renv/versions/R-4.0.5/lib/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods
> [8] base
> 
> other attached packages:
>  [1] future_1.30.0      stringr_1.5.0      patchwork_1.1.2    ggplot2_3.4.0
>  [5] SeuratData_0.2.2   harmony_0.1.1      Rcpp_1.0.9         Cairo_1.6-0
>  [9] doMC_1.3.8         iterators_1.0.14   foreach_1.5.2      RColorBrewer_1.1-3
> [13] SeuratObject_4.1.3 Seurat_4.3.0
> 
> loaded via a namespace (and not attached):
>  [1] nlme_3.1-152           matrixStats_0.63.0     spatstat.sparse_3.0-0
>  [4] RcppAnnoy_0.0.20       httr_1.4.4             sctransform_0.3.5
>  [7] tools_4.0.5            utf8_1.2.2             R6_2.5.1
> [10] irlba_2.3.5.1          KernSmooth_2.23-18     uwot_0.1.14
> [13] DBI_1.1.3              lazyeval_0.2.2         colorspace_2.0-3
> [16] withr_2.5.0            sp_1.5-1               tidyselect_1.2.0
> [19] gridExtra_2.3          compiler_4.0.5         progressr_0.12.0
> [22] cli_3.5.0              spatstat.explore_3.0-5 plotly_4.10.1
> [25] scales_1.2.1           lmtest_0.9-40          spatstat.data_3.0-0
> [28] ggridges_0.5.4         pbapply_1.6-0          rappdirs_0.3.3
> [31] goftest_1.2-3          digest_0.6.31          spatstat.utils_3.0-1
> [34] pkgconfig_2.0.3        htmltools_0.5.4        parallelly_1.33.0
> [37] fastmap_1.1.0          htmlwidgets_1.6.0      rlang_1.0.6
> [40] shiny_1.7.4            generics_0.1.3         zoo_1.8-11
> [43] jsonlite_1.8.4         spatstat.random_3.0-1  ica_1.0-3
> [46] dplyr_1.0.10           magrittr_2.0.3         Matrix_1.5-3
> [49] munsell_0.5.0          fansi_1.0.3            abind_1.4-5
> [52] reticulate_1.26        lifecycle_1.0.3        stringi_1.7.8
> [55] MASS_7.3-53.1          Rtsne_0.16             plyr_1.8.8
> [58] grid_4.0.5             listenv_0.9.0          promises_1.2.0.1
> [61] ggrepel_0.9.2          crayon_1.5.2           deldir_1.0-6
> [64] miniUI_0.1.1.1         lattice_0.20-41        cowplot_1.1.1
> [67] splines_4.0.5          tensor_1.5             pillar_1.8.1
> [70] igraph_1.3.5           spatstat.geom_3.0-3    future.apply_1.10.0
> [73] reshape2_1.4.4         codetools_0.2-18       leiden_0.4.3
> [76] glue_1.6.2             data.table_1.14.6      png_0.1-8
> [79] vctrs_0.5.1            httpuv_1.6.7           polyclip_1.10-4
> [82] gtable_0.3.1           RANN_2.6.1             purrr_1.0.0
> [85] tidyr_1.2.1            scattermore_0.8        assertthat_0.2.1
> [88] mime_0.12              xtable_1.8-4           later_1.3.0
> [91] survival_3.2-10        viridisLite_0.4.1      tibble_3.1.8
> [94] cluster_2.1.1          globals_0.16.2         fitdistrplus_1.1-8
> [97] ellipsis_0.3.2         ROCR_1.0-11
> ```
> 
> ![image](https://user-images.githubusercontent.com/42195952/211950059-9ec7b704-e188-45c0-a127-406c86f7b069.png)
> 
> Any suggestions would be of great help.
> 
> Sincerely,
> 
> Seunghoon

Hi @hoonghim, have you solved this problem? I encountered the same error as you. I have 70 samples that need to be integrated 😩

Error in .M2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  : 
  unable to aggregate TsparseMatrix with 'i' and 'j' slots of length exceeding 2^31-1
