### ISSUE TITLE
FindMarkers Error with DESeq2

### ISSUE THREAD

**Issue by GEmilioHO** [satijalab/seurat#6789]
Hi,

I am trying to identify differentially expressed genes between two cell identities using DESeq2:

`markers.astro <- FindMarkers(ctrl.seurat, ident.2 = "Astrocytes_control", ident.1 = "Astrocytes_neurog2", test.use = "DESeq2")`

However, I'm getting the following error:
```
Error in CheckDots(..., fxns = "DESeq2::results") : 
  None of the functions passed could be found
```
I have Seurat v4.3.0 and DESeq2 v1.38.1.

Thank you!

**Comment by GEmilioHO** [comment]
I think I've found the bug. It's on the line 1364 of differential_expression.R. Should be: 

`CheckDots(..., fxns = DESeq2::results)`

**Comment by Jiankun-Liang** [comment]
I encounter the same issue in the latest version seurat V5.0.1, Can anyone help?

Tfeb.makers <- FindMarkers(MS1,ident.1= "Tfeb_Dox_yes",
                        iden.2 = c("mock_Dox_yes",
                                      "EGFP_Dox_yes"),
                           test.use = "DESeq2")
Error in CheckDots(..., fxns = "DESeq2::results") : 
  None of the functions passed could be found
