### ISSUE TITLE
Possible to enable do.return argument for PCAPlot? Alternatively, enable categorical variable coloring in FeaturePlot?

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [satijalab/seurat#679]
Hello! I'd like to standardize a number of plots I'm making using a mixture of FeaturePlot (for genes) and PCAPlot (for metadata). However, the default parameters for the two functions result in plots with different line widths, title fonts, etc, which then requires downstream tweaking to make uniform visualizations. Is there a way to add the do.return function to PCAPlot? I could then standardize everything in ggplot. Alternatively, is there a way to make FeaturePlot amenable to categorical variables? 

Thanks,
Chris

**Comment by satijalab** [comment]
PCAPlot (which extends DimPlot) does have a do.return argument - which hopefully is helpful.

On a more short/medium timescale, we are working on a much more uniform set of plotting strategies for exactly this reason - stay tuned!
