### ISSUE TITLE
Question on why IntegrateData() inserts 0 as gene expression for not existing gene in one SeuratObject

### ISSUE THREAD

**Issue by jeji0209** [satijalab/seurat#6793]
Hello, I am integrating datasets with two different conditions, and planning on further analysis of comparing those two conditions. 
However when I was running my differential expression gene analysis using FindMarkers(), I encountered an issue.
I realized that some genes had pct.1 = 0 in my result, and therefore the gene came out as being down-regulated. (avg_logFC = -3.7). Skeptical, I ran  `AverageExpression(seu.integrated, verbose = FALSE)$RNA` with the condition as identity, and found that the average expression for this gene in condition 1 was actually 0.
When I traced back to the seurat objects that I have integrated, I found out that there weren't any existing gene expression for this gene in seurat object of condition1, and the cells in this seurat object was imputated with 0 for gene expression in the integrated seurat object. 
In this case, I feel that this DEG is not a gene that is differentially expressed due to the difference in condition, but more of a result of a batch effect that has occurred due to the difference of sample that I have collected. There is also a mention of this similar issue in #5226, and how inserting 0 for non-existing genes might create a batch effect in further analysis. Here I have two questions: 

1. Is there a reason in why IntegrateData() inserts gene expression 0 as default for genes not in a seurat object, instead of using only common genes existing in all seurat objects that have to be integrated?
2. I changed my analysis into integrating my datasets with only common genes that are in all data, using the Features.to.Integrate argument in IntegrateData(). Is this an appropriate approach if I want to use this integrated object for differential analysis of two conditions?

Thank you :)

**Comment by alikhuseynov** [comment]
..not part of a Seurat team, however this this issue #1676 could be related as well

**Comment by Gesmira** [comment]
Thank you @alikhuseynov, as stated in issue [#1676](https://github.com/satijalab/seurat/issues/1676), we maintain the features from all datasets and put 0 counts when a feature is not present in cells from a dataset. Your approach of only using the features present in both objects is valid and you will then only be able to do differential expression analysis on features present in both of the datasets.
