### ISSUE TITLE
How can I label a subset within highlighted cells (using cells.highlight in DimPlot)

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#6794]
- I often highlight set of cells using `DimPlot( ..., cells.highlight = cellIDs, cols.highlight = "red")`. 
- Now I would like to highlight additionally some other cells on the same umap (say, in green, but it could be a different color, cellID label, etc.). 
- _To show what I mean, I manually made to show the point:_

<img width="385" alt="image" src="https://user-images.githubusercontent.com/5101911/208267242-a09e88f4-4d31-440f-9045-f8970dd4d1cd.png">

- **Using `cells.highlight` allows to increase size of the highlighted cells, that's why simply making another identity and plot it simply as three clusters (grey, red, green) would not be handy.**

I could extract UMAP coord, and plot on top of the UMAP objects, but I wonder if there is an easier way. 

Input much appreciated, thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I have implemented a sample solution (that also checks for cell duplicates and ensures all IDs are valid, etc) in my package scCustomize (develop branch).  It's fairly straightforward ggplot2 theming (if interested see source code for function).

```
library(Seurat)
library(patchwork)
library(scCustomize)

pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc <- UpdateSeuratObject(pbmc)

MS4A1 <- WhichCells(object = pbmc, expression = MS4A1 > 3)

GZMB <- WhichCells(object = pbmc, expression = GZMB > 3)

cells <- list("MS4A1" = MS4A1,
              "GZMB" = GZMB)

# function will create color scheme based on package default palettes
p1 <- Cell_Highlight_Plot(seurat_object = pbmc, cells_highlight = cells)

# supply your own colors
p2 <- Cell_Highlight_Plot(seurat_object = pbmc, cells_highlight = cells, highlight_color = c("dodgerblue", "forestgreen"))

wrap_plots(p1, p2)
```

![image](https://user-images.githubusercontent.com/38284410/208279236-fda5672a-4b8f-4094-875d-bf7a675da6f5.png)


Best,
Sam

**Comment by vertesy** [comment]
Thanks Sam, very nice solution! 

The thing is that I also use it within a package I built on top of Seurat ([`Seurat.utils::clUMAP()`](https://github.com/vertesy/Seurat.utils)), so I would aim for a solution using vanilla Seurat. I guess I could dig it out from the code of `Cell_Highlight_Plot()`...

**Comment by samuel-marsh** [comment]
Ya I mean it all should work internally with DimPlot so long as the input to cells.highlight is named list and color vector is equivalent to number of entries in list.  Then just need the ggplot2 theming after plot to edit the legend.

**Comment by samuel-marsh** [comment]
Relevant bits here:
https://github.com/samuel-marsh/scCustomize/blob/a611c2395a87b9533825c484b19af4e62794b385/R/Seurat_Plotting.R#L934-L951

**Comment by vertesy** [comment]
Thank you, I will look into it!

**Comment by samuel-marsh** [comment]
No problem!
