### ISSUE TITLE
How delete a slot in seurat obj?

### ISSUE THREAD

**Issue by victorwang123** [satijalab/seurat#6796]
I want to delete a slot in my seurat obj as the following scripts, but it didnt work, how to delete a slot ?
`pbmc@neighbors <- NULL`

**Comment by samuel-marsh** [comment]
Hi,

Can you clarify why you want to delete a slot?

Best,
Sam

**Comment by victorwang123** [comment]
> Hi,
> 
> Can you clarify why you want to delete a slot?
> 
> Best, Sam

Thanks for responding to me so promptly！
I want to put the object into Python and make it as simple as possible, so I want to get rid of some unused slots

**Comment by samuel-marsh** [comment]
Just question but if you are porting the object the python would it be simpler to just extract the data you do want and move that into what ever object format in python you want vs. removing slots to port whole object?
