### ISSUE TITLE
Writing/printing into seurat marker count into a .csv

### ISSUE THREAD

**Issue by atlmalive** [satijalab/seurat#6797]
Hi all,

Please see 'Count gene markers #6770'. I am using the script from there to try to print the list into a .csv file. This is what I have so far: 
"DefaultAssay(vs1) <- "RNA"
Idents(vs1)
# selected markers
genes <- cd_genes
# check if selected markers are present in the object
genes %<>% intersect(rownames(vs1))
thres = 0 # threshold for expression level, eg > 3 counts
cells.out <- 
  lapply(seq(genes), function (i) 
  { which(FetchData(vs1, 
                    slot = "data",
                    cell = WhichCells(vs1, idents = lac),
                    vars = genes[i]) > thres, 
          arr.ind = TRUE, 
          useNames = TRUE) %>% rownames %>% length }
  )
names(cells.out) <- genes # add names to a list
gmark_count <- list(cells.out %>% str)

head(gmark_count)
write.csv(print(gmark_count, 'results/markercountvs01sn.csv'))
print(cells.out)"

I am able to generate a list of genes stored as 'lac' but I tried using write.csv and print command to get that list to be loaded onto the object gmark_count but I get a "NULL" error. It appears that the string is not being stored. I also trying using list and data.frame command but have not been successful thus far. 

Any suggestions? Any help will be greatly appreciated.

**Comment by alikhuseynov** [comment]
Hi, I'm glad that #6770 worked out, however I'm not from Seurat team.
`str()` this one shows only the structure..
to export as ` .csv `you can use this:
```
gmark_count <- cells.out %>% as.data.frame.list
write.csv(gmark_count, "results/markercountvs01sn.csv")
```

**Comment by atlmalive** [comment]
Thanks for the help. This is what I ended up using based on your suggestion to save info vertically into csv and it worked! Your suggestion saved the info horizontally. 

DefaultAssay(sovs01sn) <- "RNA"
Idents(sovs01sn)
# selected markers
genes <- cd_genes
# check if selected markers are present in the object
genes %<>% intersect(rownames(vs1))
thres = 0 # threshold for expression level, eg > 3 counts
cells.out <- 
  lapply(seq(genes), function (i) 
  { which(FetchData(vs1, 
                    slot = "data",
                    cell = WhichCells(vs1, idents = lac),
                    vars = genes[i]) > thres, 
          arr.ind = TRUE, 
          useNames = TRUE) %>% rownames %>% length }
  )
names(cells.out) <- genes # add names to a list
gmark_count <- cells.out %>% as.data.frame.list %>% t()
write.csv(gmark_count, "results/markercountvs1.csv") ##saves data vertically
