### ISSUE TITLE
Find DEG between clusters previously assigned from the metadata

### ISSUE THREAD

**Issue by GiuliaSansone** [satijalab/seurat#6799]
Hello,
I am working on a dataset from the Allen Brain institute which already provided their clusters based on hierarchical clustering method. I tried perform the cluster analysis following the pipeline in the vignette but, as expected, I didn't get the same clusters as the methods are different. With my PI we decided to base the further analysis on the clusters they already provided in the metadata.
Is it possible to perform a differential gene expression analysis on the clusters they already assigned?

Thank you
Best, 

Giulia

**Comment by samuel-marsh** [comment]
Hi Guila,

Not member of dev team but hopefully can be helpful.  You can do this with any categorical variable.  Simply set the relevant meta.data column as the active.ident.
```
Idents(obj) <- "META_DATA_COLUMN"
```

Best,
Sam
