### ISSUE TITLE
FindMarkers() adjusted pvalues do not change when changing the logfc.threshold parameter

### ISSUE THREAD

**Issue by rauldiul** [satijalab/seurat#6801]
Hi!

Thanks for your great software. I'm using the `FindMarkers` (`Seurat v4.3.0`) function while changing the parameter `logfc.threshold`, with the following code:
 ```
FindMarkers(seu,
                   # Filters
                   min.pct	= 0.1, # default: do not test genes which are expressed <10% cells in both populations
                   min.diff.pct = -Inf, # default: not pre-filter by diff pct	
                   logfc.threshold = 0.25, # not pre-filter by logFC: this is a time-limiting step!!!
                   min.cells.feature	= 3, # default: at least 3 cells express the gene in 1 group
                   min.cells.group	= 3, # default: at least 3 cells per group
                   ident.1 = paste0(y,"_O"),
                   ident.2 = paste0(y,"_Y"),
                   verbose = TRUE,
                   slot = "data",
                   test.use = "LR",
                   latent.vars = "group.ee") 
```

In the documentation, it is stated that `logfc.threshold` controls:

> Limit testing to genes which show, on average, at least X-fold difference (log-scale) between the two groups of cells. Default is 0.25 Increasing logfc.threshold speeds up the function, but can miss weaker signals.

My understanding is that with this parameter, you filter genes **prior to testing** (and this, indeed, speeds up the function a lot) and thus you control the number of tests.

However, when I try `logfc.threshold = 0.25` versus `logfc.threshold = 0`, and get a matrix with 85 genes versus 10524 genes, the results have the same adjusted p-values for the 85 genes with logFC >0.25. I get that they should have the same p-values (because the tests for each row are independent), but p-value adjustment for multiple testing depends on the total number of rows. 

**So the question is, shouldn't adjusted p-values change when changing the `logfc.threshold` parameter?**

Maybe I'm missing something, maybe the matrix is filtered after testing. But if this is the case I cannot imagine how the function is quicker when setting the filter.

thanks for your help

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  See previous post where this issue was discussed: https://github.com/satijalab/seurat/issues/905#issuecomment-434537989)

Best,
Sam

**Comment by rauldiul** [comment]
Oh! Thank you! that totally clears it up! I guess that's also (partly) why the use Bonferroni correction, because it does not depend on the distribution of p-values from all the tests
