### ISSUE TITLE
Have an option to disable warning of rasterization after 100k points of feature plot

### ISSUE THREAD

**Issue by GirayEryilmaz** [satijalab/seurat#6802]
Feature plot gives the warning:
Rasterizing points since number of points exceeds 100,000.
To disable this behavior set `raster=FALSE`

An option to silence this would be great. Also I believe it should go away if I set raster=FALSE or raster=TRUE explicitly. 

If I plot many genes at once, I get many of these warnings which fills the logs of an R shiny app I am developing with no good reason and clutters my screen when doing analysis.

If there is a convenient way to silence this warning please forgive me for posting this and let me know what it is.

Thank you.

**Comment by alikhuseynov** [comment]
`suppressMessages()` works for me. 
Hope this helps.

**Comment by yuhanH** [comment]
@alikhuseynov , Thank you for answering this issue. 
@GirayEryilmaz , you can also try `suppressWarnings(FeaturePlot(xxx))` to avoid the warning message.
