### ISSUE TITLE
Some questions about finding HVGs based on sctransform

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6803]
Hi, I wonder if I intend to select the highly variable genes based on sctransform, which instruction I should use to generate them.

It should be:
genes_selected = pbmc_new@assays$SCT@var.features

or
correct_matrix = pbmc_new@assays$SCT@scale.data
rownames(correct_matrix)
Their results are different, which are quite confused. Thanks.

**Comment by saketkc** [comment]
When you run SCTransform, it also automatically selects the variable features (based on high residual variance). You can see these features using `VariableFeatures(object)`
