### ISSUE TITLE
Error when using "subset" to reproduce results of "SubsetData"

### ISSUE THREAD

**Issue by KlarkDo** [satijalab/seurat#6805]
Hi,
I'm reproducing results from a paper in 2019. They might use seurat V2. I'm using V4.3.0.
The original codes are shown below,
```
load("../data/SeuratObject.RData")
cells <- rownames(seu.ica@meta.data)[which(!is.na(seu.ica@meta.data$celltype))]
seu.ica <- SubsetData(seu.ica, cells.use = cells)
```
I tried this and the result was:
```
> seu.ica <- subset(seu.ica, cells = cells)
Error in subset.default(seu.ica, cells = cells) : 
  argument "subset" is missing, with no default
```
Thanks!

**Comment by Gesmira** [comment]
Hi, 
Can you try setting the Idents() of the object to the celltype/name that you are using and run: 
`seu.ica <- subset(seu.ica, idents = cells)`. More info on subsetting here: [Seurat Command List](https://satijalab.org/seurat/articles/essential_commands.html)

**Comment by KlarkDo** [comment]
> Hi, Can you try setting the Idents() of the object to the celltype/name that you are using and run: `seu.ica <- subset(seu.ica, idents = cells)`. More info on subsetting here: [Seurat Command List](https://satijalab.org/seurat/articles/essential_commands.html)

Thanks for the advice. But when I tried, it showed:

```
> Idents(seu.ica, cells = rownames(seu.ica@meta.data)[which(!is.na(seu.ica@meta.data$celltype))])<- 'cells'
Error in UseMethod(generic = "Idents<-", object = object) : 
  no applicable method for 'Idents<-' applied to an object of class "seurat"
```

**Comment by Gesmira** [comment]
Are you trying to subset out cells that have an NA value for "celltype"? If so something like this should work
`subset <- subset(seu.ica, subset = celltype != "NA")`

The error you are getting though suggests something may be wrong with your seurat object. Are you using the object made with Seurat v2? If so, you may need to run:
`seu.ica <- UpdateSeuratObject(seu.ica`

And then the subsetting commands should work fine. 
Let me know if that helps!

**Comment by KlarkDo** [comment]
> Are you trying to subset out cells that have an NA value for "celltype"? If so something like this should work `subset <- subset(seu.ica, subset = celltype != "NA")`
> 
> The error you are getting though suggests something may be wrong with your seurat object. Are you using the object made with Seurat v2? If so, you may need to run: `seu.ica <- UpdateSeuratObject(seu.ica)`
> 
> And then the subsetting commands should work fine. Let me know if that helps!

Thank you very much. They worked fine.
