### ISSUE TITLE
What is the reference for allen cortex data in spatial_vignette.Rmd

### ISSUE THREAD

**Issue by wwzhang** [satijalab/seurat#6807]
In https://satijalab.org/seurat/articles/spatial_vignette.html#integration-with-single-cell-data-1 

Could you list the related publication(s) for allen_cortex.rds (https://www.dropbox.com/s/cuowvm4vrf65pvq/allen_cortex.rds?dl=1) in the vignette like later in the same vignette for Saunders et al 2018 (https://doi.org/10.1016/j.cell.2018.07.028)?

**Comment by AustinHartman** [comment]
Here's the reference: [https://www.nature.com/articles/nn.4216](https://www.nature.com/articles/nn.4216). It's linked in the vignette when you click "reference scRNA-seq dataset"
