### ISSUE TITLE
mtx.gz.part- file

### ISSUE THREAD

**Issue by mvslmdOjbi** [satijalab/seurat#6819]
I am new to Seurat and bioinformatics analysis, so please excuse my very basic question.

I'm trying to analysis scRNA-seq data deposited in https://github.com/CBIIT-CGBB/CISH_Cell_Med/tree/main/Tumor.
In this dataset, some of the matrix files are deposited as a form of **mtx.gz.part-** .
Are there any way to convert these files into mtx.gz files, which can be read by Seurat？

I would be grateful for your support.

**Comment by f6v** [comment]
This might have something to do with Github limits on file size(or file size limits in other system). Try concatenating all the files like [so](https://stackoverflow.com/questions/8005114/fast-concatenation-of-multiple-gzip-files).

**Comment by mvslmdOjbi** [comment]
Thank you very much for your valuable reply.
It is really helpful for me.
By combining the files, the date was successfully read by Seurat.

> This might have something to do with Github limits on file size(or file size limits in other system). Try concatenating all the files like [so](https://stackoverflow.com/questions/8005114/fast-concatenation-of-multiple-gzip-files).
