### ISSUE TITLE
RunMultiCCA with big numbers of cells

### ISSUE THREAD

**Issue by ogarmar3** [satijalab/seurat#682]
Hello,

I'm pooling samples from multiple experiments and multiCCA gives the best results. However, when processing more than ~60k cells it takes a very long time and high memory to run, being impracticable.

If I decrease the number of hvgenes and ccs, it can run but I lose a lot of clusters. Is there any strategy for large datasets I could use?

Thank you,

Marcos Otero

**Comment by leonfodoulian** [comment]
Hi Marcos,

Please check issue #675 for more details. The referenced vignette in that issue does not have tips on how to improve running `Seurat::RunMultiCCA()` on very large datasets, but definitely has tips on how to improve running the other steps in Seurat with large datasets.

Have a nice one!

Best,
Leon

**Comment by ogarmar3** [comment]
Hi Leon,

Thank you for your answer. The information I got from issue #675 is quite useful.
However, the limiting step in my pipeline is still Seurat::RunMultiCCA(). It takes four days to run, and I'm not even using all the CCS I should do to get the proper clustering.

Best,
Marcos

**Comment by satijalab** [comment]
For large numbers of batches, we are aware that MultiCCA is computationally inefficient. We have identified solutions to this, and will release in the near future.

**Comment by huyqdinh** [comment]
I am wondering if you have a timeline for multiCCA speed&memory update? Thanks a lot
