### ISSUE TITLE
How to build a Seurat object from Anndata or SingleCellExperiment object?

### ISSUE THREAD

**Issue by danli349** [satijalab/seurat#6820]
Hello,

How to build a Seurat object from Anndata or SingleCellExperiment object?

Thanks a a lot.
Dan

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  See object conversion vignette for full details on converting to other formats.

https://satijalab.org/seurat/articles/conversion_vignette.html

Best,
Sam

**Comment by danli349** [comment]
Very helpful. Thanks
