### ISSUE TITLE
Can MappingScore() be used to get an absolute measure of scRNAseq dataset similarity to the reference dataset?

### ISSUE THREAD

**Issue by Sesukai** [satijalab/seurat#6822]
Hi Seurat Team,

I have been using Seurat v4 Reference Mapping align some query scRNAseq datasets that come from IPSC-derived cells that were subject to several directed cortical differentiation protocols at multiple timepoints. The reference dataset I made by merging several individual fetal cortical sample datasets that I had annotated based on their unsupervised cluster DEGs (following [this vignette](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html#normalizing-the-data-1) using the default parameters). 

I am interested in seeing which protocol produces cells most similar to the cells found in the fetal datasets as well as which fetal timepoints the query datasets tend to map to. I understand that the MappingScore() function can show me query cells that aren't well represented in the reference dataset, so I figured that these scores could tell me which datasets are most similar to the reference dataset. However, in comparing the violin plots of the mapping scores for a query dataset from one of the differentiation protocols to a query dataset that contains just pluripotent cells it looks like there are cells with high mapping scores found in both cases (see attached images) even though really only the differentiated cells should have cells closely resembling the fetal cortical tissue cells.

My question is whether or not the mapping score can be used as an absolute measurement of query to reference dataset similarity or if it is always just a relative measure where the high and low thresholds are set by the query dataset. If the latter, what alternative functions might I use here to get information about absolute similarity?  

Thanks.

Attached Files:
[Code_Used_For_Mapping.txt](https://github.com/satijalab/seurat/files/10333019/Code_Used_For_Mapping.txt)
![Differentiated Cell Mapping Score](https://user-images.githubusercontent.com/99214617/210265962-8a2d39cc-5053-4da6-908c-8036cebc529e.png)
<img width="408" alt="Pluripotent Cell Mapping Score" src="https://user-images.githubusercontent.com/99214617/210265970-55bd11db-83bd-45ff-9b1b-a00d1032d584.png">

**Comment by mhkowalski** [comment]
Hello, 

No-I would not use the mapping score as a metric to compare datasets. I don't have a specific recommendation, but as a rough solution you could look at correlation between the average expression cell types in your reference and query. For instance, you could calculate pseudobulk gene expression for the most variable features and then calculate the correlation between that population in the query and the closest population in the reference.   Hope this is helpful!
