### ISSUE TITLE
subset object still carrying over info from merged/integrated object

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#6823]
Hi,

I tried running DGE on a subset (by sample) of the merged/integrated object. 
The PrepSCTFindMarkers fails with an error that turns out to be caused by a call to SCTResults.

observed_median_umis <- lapply(X = SCTResults(object = object[[assay]], slot = "cell.attributes"), FUN = function(x) median(x[, "umi"]))

The SCTResults call on the subset of the object returns results from all the samples of the merged/integrated object, rather than only the subset.

I am not sure if this is a wanted behavior, and I thought I should report it. 

Best

**Comment by Gesmira** [comment]
Hi, 
If SCTransform was run on the entire object, can you try running `PrepSCTFindMarkers()` on the whole object, then subsetting and running `FindMarkers()` with `recompute_umi = FALSE` as outlined in [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html).

**Comment by gianfilippo** [comment]
Thanks
