### ISSUE TITLE
How to match cells from the coordinates with meta.data?

### ISSUE THREAD

**Issue by QSong-github** [satijalab/seurat#6824]
I tried to use Seurat to import the vizgen merscope data. However, I am confused about the cells (x, y, cell ID) get from "GetTissueCoordinates". How these cells match with the object@meta.data? The object@meta.data has no information on cells at all...

**Comment by alikhuseynov** [comment]
try to follow this [vignette on Vizgen](https://satijalab.org/seurat/articles/spatial_vignette_2.html#mouse-brain-vizgen-merscope)
the cell and or molecule coordinated are stored in FOV of the object, not in metadata.
eg `Images(obj)` will give you names of FOVs, or `obj[[Images(obj)[1]]]` will give you the info on first FOV
`obj[[Images(obj)[1]]][["centroids"]] %>% GetTissueCoordinates` return data frame of x,y coords of cell centroids and cell id

hope it is clear.

**Comment by AustinHartman** [comment]
Hi @QSong-github, the data from a Vizgen MERSCOPE experiment is stored in a couple of different places within the Seurat object. The meta.data information stores data about all of the cells in object. A subset of those cells can be stored within the images slot of the Seurat object which is where GetTissueCoordinates fetches information from. To get all of the cells in the object, you can run `Cells(obj)`. Hope this helps!
