### ISSUE TITLE
Follow-Up to: DoHeatmap: Scale Differs when group.by Changes

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#6826]
Hi,
It seems that there is no direct way to control the scale of the color bar. But you may do it via ggplot2() to change the scale by yourself (since the heatmaps are generated by ggplot2). For example:

`DoHeatmap(pbmc_small) + scale_fill_gradientn(limits = c(-2, 2), colours = PurpleAndYellow(), na.value = "white")`

You can modify the limits = c( lower_limit, upper_limit) to any other values, based on the maximal and minimal expression values in your datasets.

_Originally posted by @longmanz in https://github.com/satijalab/seurat/issues/6776#issuecomment-1355595911_
      
Thank you for explaining. I tried specifying the scale like this but still got the same results.
I believe the scale of the heatmaps changed because I changed the "group.by" identities when calculating AverageExpression.

The first heatmap:
average_of_anno1_indiv <- AverageExpression(object = time1,group.by="clonotype_status",return.seurat = TRUE)
Where clonotype_status has 50 identities.

The second heatmap:
average_of_anno1 <- AverageExpression(object = time1,group.by="CD8_status",return.seurat = TRUE)
Where CD8_status has 3 identities.

Could the difference in number of identities affect the values on the heatmap?

**Comment by longmanz** [comment]
Hi, 

1. What was your command to generate the Heatmap? 
2. I cannot reproduce your issue using pbmc_small. If possible, can you provide a minimal reproducible example dataset to us? 
3. Regarding the identity, please remember to specify it with group.by when running DoHeatmap(). According to your previous heatmaps, the heatmap identity (labelled by the legend) is not the correct Identity you are referring to (3 or 50).

**Comment by atly2000** [comment]
**Here are the commands I used to generate the heatmap:**
For the heatmap that separates the data by 50 identities (clonotype_status): 
average_of_anno1 <- AverageExpression(object = time1,group.by="clonotype_status",return.seurat = TRUE)
DoHeatmap(average_of_anno1,features=c(pos_genes,neg_genes))

For the heatmap that separates the data by 3 identities (CD8_status):
average_of_anno1 <- AverageExpression(object = time1,group.by="CD8_status",return.seurat = TRUE)
DoHeatmap(average_of_anno1,features=c(pos_genes,neg_genes))

I specified the "group.by" in the AverageExpression calculation rather than the DoHeatmap function.

**Comment by longmanz** [comment]
Hi, 
Just to confirm, `DoHeatmap(average_of_anno1,features=c(pos_genes,neg_genes)) + scale_fill_gradientn(limits = c(-2, 2), colours = PurpleAndYellow(), na.value = "white")` did not modify the scale in your figure? Did it return an error message?

**Comment by atly2000** [comment]
It modifies the numerical scale, but I still cannot compare the two heatmaps. 
I expected Column 3 of both heatmaps to match, but they do not.
In both CD8_status and clonotype_status, column 3 contains the same cell barcodes.
As a result, I think that adding a greater number of identities caused the heatmap colors to change with respect to themselves.
I can compare values within the same heatmap, but not with another heatmap.

Do you think using the RNA expression matrix from the Seurat object to plot a heatmap in ggplot2 would be a better solution?
I tried doing a similar analysis using a Seurat AverageExpression object in ggplot2.

**Comment by longmanz** [comment]
Hi, 
I see what you mean now. You want the values of your two columns match to each other. In that case, you should specify the data.slot to "data" (e.g., `DoHeatmap(average_of_anno1,features=c(pos_genes,neg_genes), slot = "data")`. 
The default is set to "scale.data" so that each row (i.e., gene) is scaled to have mean = 0 and variance = 1. And they will not match because you have different number of identities (columns) in your heat maps.

**Comment by atly2000** [comment]
Thank you very much for explaining! I think that is the solution. 
I really appreciate it.

I am planning on splitting my data by time and plotting three heatmaps for three time points. 
If I also want to proceed with the results of AverageExpression as a heatmap in ggplot2, how can I ensure that all of these heatmaps are comparable? 

After splitting my data by time1, time2, time3, then using AverageExpression on each time dataset (group.by CD8_status), could I use these matrices to plot a heatmap in ggplot2?:

1.  time1@assays$RNA@data
2.  time2@assays$RNA@data
3.  time3@assays$RNA@data

And I could expect the values across all three heatmaps to be comparable?

**Comment by longmanz** [comment]
Hi, 
Glad to hear that. As for the time dataset, using the "data" slot should be good. They are comparable to each other.
