### ISSUE TITLE
Analyzing Gene Expression and Clustering of Cells using 4 different data sets

### ISSUE THREAD

**Issue by pvimal** [satijalab/seurat#683]
I recently obtained single cell data on different disease states of patients. I had a couple questions which I was hoping someone could answer. 

I am trying to plot and analyze these samples, which would require normalizing gene expression, relative to one another. Would I use 'the merge function to do so, and if I did would that allow me to plot them separately? Do you have any recommendations of papers or code script you could point me in the direction to as a guide?

Any and all help is appreciated!

Thank you for your time,

**Comment by leonfodoulian** [comment]
Hi,

There are a lot of issues that have been already addressed that answer your questions. And the easiest answer to give is that all depends on your dataset. Check for instance issues #311 and #556 for more details.

Hope these help!

Best,
Leon
