### ISSUE TITLE
Processing 4 CITE-seq (RNA + ADT) datasets

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#6832]
Hi Seurat Team,

Thanks for developing this great package.  

I have 4 CITE-seq datasets processed using 10X cellRanger pipeline with the "filtered data matrix" sets available.

I wish to integrate and cluster them together.  I did go through the multiple issues here that discuss the potential workflows, namely, 
https://github.com/satijalab/seurat/issues/3890
https://github.com/satijalab/seurat/issues/4815
and some others.

However, I am very confused at this stage as to the best way forward, and so I am hoping somebody will clarify.  I am particularly confused as to how to combine and integrate and how to process the RNA+ADT with integration.

My specific questions are:
1) Should I do scTransform or regular normalization?
2) How should I integrate, separately or together?
3) How should I merge afterwards?
4) How should I proceed for clustering, DE, marker genes, etc.?

Many of the issues, particularly the two above, give answers using Seurat 3, and so what's the best workflow for this purpose under Seurat 4?  That is not clear to me.  It will be great if somebody could point me to a clear workflow to achieve these objectives.

Many thanks.

**Comment by yuhanH** [comment]
hi @CodeInTheSkies 
1. For RNA, you can use either SCTransform or log normalization. For ADT, you would better use CLR log normalization example: 
```
DefaultAssay(object) <- 'ADT'
object <- NormalizeData(object, normalization.method = "CLR", margin = 2)
```
2, You should integrate them separately. 
3. You can make two different integrated assays. check out https://github.com/satijalab/seurat/issues/3890
4. After you perform WNN analysis on both integrated RNA and ADT assays, you can get a `wsnn` graph which can be used for clustering. check out [WNN vignette ](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html)
Then you can find markers based on original RNA and protein assays. 

Hope it is helpful for you.

**Comment by CodeInTheSkies** [comment]
Thank you very much @yuhanH for your response.  Yes, it is much clearer now, and I will try your advice.

Best Regards.

**Comment by sagrikachugh** [comment]
My dataset has total 15 samples but only 4 of them are CITE-seq and rest 11 samples are scRNA-seq. The dataset is from a single experiment. I was wondering if someone can suggest how to process the RNA+ADT with integration. My question is 

Should I integrate the 4 CITE-seq samples with rest of the samples and perform [WNN analysis](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html) or separately process the 4 samples?

Thanks
