### ISSUE TITLE
DEenrichRPlot function request

### ISSUE THREAD

**Issue by jjacob12** [satijalab/seurat#6833]
Hi Seurat Developers,
Many thanks for all you continue to do for the single cell community. I recently used the ```DEenrichRPlot``` command which, impressively did the job of finding enriched genes with just 1 line of code. However, I am using Seurat on an HPC server which does not have an internet connection. Is it possible you can configure this command so it works offline? I emailed the Maayan lab who developed the enrichR package but I am not sure if they can address the issue or whether you could?  
John

**Comment by jnrmro** [comment]
Following up on this. Also have same issue. Thanks!

**Comment by jjacob12** [comment]
Please see https://github.com/wjawaid/enrichR/issues/59. I did not resolve the issue unfortunately.

**Comment by mhkowalski** [comment]
Hi, 

I'm closing this for now as this is under the purview of the enrichR developers and not Seurat. Thanks for your question!

**Comment by jjacob12** [comment]
Hi, 
Yes that is fine, thanks.
