### ISSUE TITLE
Genes missing from slot='scale.data' vs. slot='data'

### ISSUE THREAD

**Issue by sg3451** [satijalab/seurat#6835]
I am generating RidgePlots for a set of candidate genes. When using assay='SCT' and slot='data', I get plots for all candidate genes. But when setting slot='scale.data', some of the genes are missing and reported as 'not found'.  The problem is not specific to RidgePlot as I am also seeing this with FeaturePlot and FeatureScatter commands. Below is an example:

> RidgePlot(scnorm_KO1m, features = c(candgenes_wat, "S.Score", "G2M.Score"), group.by = "seurat_clusters", combine = TRUE, assay = "SCT", slot="data")+
+   theme(legend.position = "bottom")
Picking joint bandwidth of 3.88e-06
Picking joint bandwidth of 0.0169
Picking joint bandwidth of 0.00447
Picking joint bandwidth of 0.00667
Picking joint bandwidth of 0.00762

> RidgePlot(scnorm_KO1m, features = c(candgenes_wat, "S.Score", "G2M.Score"), group.by = "seurat_clusters", combine = TRUE, assay = "SCT", slot="scale.data")+
+   theme(legend.position = "bottom")
Picking joint bandwidth of 0.0936
Picking joint bandwidth of 0.00667
Picking joint bandwidth of 0.00762
Warning message:
In FetchData.Seurat(object = object, vars = features, slot = slot) :
  The following requested variables were not found: Lep, Adipoq

**Comment by longmanz** [comment]
Hi @sg3451 ,
when you run SCTransform(), did you set the "return.only.var.genes" to FALSE? If not, only a subset of variable genes will be scaled and stored in the "scale.data" slot. That is probably why you do not see all the genes you want. 
Let me know if this cannot fix it and I will re-open the issue.
