### ISSUE TITLE
Pearson Residual Slot Clarification 

### ISSUE THREAD

**Issue by freddie090** [satijalab/seurat#6838]
Hi, 

Probably a simple question, but I can't seem to find the answer anywhere... 

Could somebody please clarify the difference between the Pearson Residual values: 

- located in the `scale.data` slot of the `SCT` assay, and 
- summarised in the `SCTModel.list$model1@feature.attributes` of the `SCT` assay. 

... for example, if I try and calculate the variance of the residuals in the `scale.data` slot (via `apply(scale.data, 1, var)`) I get different values from those in the `residual_variance` column of the `feature.attributes` data.frame.

**Comment by saketkc** [comment]
`scale.data` slot of the `SCT` assays stores the pearson residuals (scaled by default).

`SCTModel.list$model1@feature.attributes` stores the per gene attributes (glm model parameters, gene mean, residual variance).  One reason you might see a discrepancy in the `residual_variance` and `rowVar(scale.data)` is how the clipping of residuals work. You can fix the clipping range to say `res.cip.range=c(-10, 10)` and see that they match up.

**Comment by freddie090** [comment]
Hi, 

Thanks for your reply @saketkc. 

Apologies, just a follow up on this - can I confirm how I can extract the _non-scaled_, _non-centred_ Pearson Residual matrix?

I've re-run `SCTransform` with `do.scale = F` and `do.center = F`, however when I look at the distribution of Pearson Residual variances as a function of the average expression (UMIs detected for that gene, taken from the `RNA` count data slot) it appears they have still been scaled and centred? (image attached)

I would like the raw Pearson Residuals in a matrix format so I can simultaneously compare the between-gene and between-cell variance. At the moment, I can look at between-gene differences by using the `feature.attributes` residual variance column, however I'm reluctant to use the apparently scaled and centred values as strong correlations between average expression and variance remain. 
Please correct me if the reasoning behind any of this is misguided! 

Thanks again 


![image](https://user-images.githubusercontent.com/39130504/212662954-9d2ce24f-bacf-4d34-b1e2-9b3a0d117f73.png)

**Comment by saketkc** [comment]
It would be helpful if you paste your code. The centering acts on residuals - additive shifts do not affect the variance.

**Comment by saketkc** [comment]
The code to reproduce the mean-variance plots are in this repo: https://github.com/saketkc/scRNA_NB_comparison. In particular Figure2.Rmd and [run_seurat.R](https://github.com/saketkc/scRNA_NB_comparison/blob/master/code/02_run_seurat.R)
