### ISSUE TITLE
Set minimal cluster size in FindClusters() in Seurat4

### ISSUE THREAD

**Issue by xxihe** [satijalab/seurat#6842]
Hi, I am using FindClusters() function and identified several clusters with only 2 or 3 cells in each cluster. 

I am wondering if there is a parameter to set the minimal size of cluster. I googled this function. It seems that there is one called " min.cluster.size"  in Seurat version 1.2, however in Seurat version 4, it is no longer exist. Is there an similar parameter in the current version?

**Comment by AustinHartman** [comment]
This is not an available parameter in Seurat 4 but I would recommend modifying the `resolution` parameter to modulate cluster size. You can also try different clustering algorithms by modifying the `algorithm` parameter. See here for more info: [https://satijalab.org/seurat/reference/findclusters](https://satijalab.org/seurat/reference/findclusters)
