### ISSUE TITLE
Questions about finding different gene-peak links based on rna and sct

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6843]
Hi all, I contact two seperated datasets to generate the overall gene-peak link result. However, I found that the results I have based on RNA in the idenfitifcation process are very differernt from the results based on SCT. For two datasets, is it ok for me to directly contact them? Thanks.

**Comment by saketkc** [comment]
Hi @HelloWorldLTY, There could be difference arising from the way the normalization works for `SCT/RNA` assays. If you are using the RNA assay make sure you have run `NormalizeData` before running downstream processing. Please open an issue in Signac repo if you have further questions about gene-peak linking.
