### ISSUE TITLE
RunMiQC missing enforce_left_cutoff and keep_all_below_boundary

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#6844]
Hi,

I am seeing exclusion of low-mito cells in my analysis and I realized that the RunMiQC does not seem to account for this.

Best

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I would suggest posting this to Seurat Wrappers repo as this function is part of that package and not Seurat.  

Best,
Sam

**Comment by gianfilippo** [comment]
ok, thanks
