### ISSUE TITLE
The results is NA when i run findcluster()

### ISSUE THREAD

**Issue by xzw222** [satijalab/seurat#6847]
I'm trying to use a new distance to define the similarity between cells，so I used the calculated distance matrix to build snn graph. When i run findcluster(), meta.data$seurat_clusters is NA. Why does this result occur？ Thanks

dis = read.table('', header = TRUE, row.names = 1)
dis = as.dist(dis)
graph = FindNeighbors(dis)
dclu.seurat = seu
dclu.seurat@graphs = graph
dclu.seurat = FindClusters(dclu.seurat, graph.name = 'snn',resolution = 1, modularity.fxn = 1)
######################
dclu.seurat@meta.data$seurat_clusters
   [1] NA NA NA NA NA ...

**Comment by AustinHartman** [comment]
It's possible that the graph object you are adding to the graphs slot is in some way invalid, could you provide a fully reproducible example to help with debugging?

**Comment by mhkowalski** [comment]
Closing because of lack of response, please open if you have additional questions.
