### ISSUE TITLE
Add ModuleScore lists comparison

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#6848]
Hi,

I would like to compare two lists of markers, to see which list is better in identifying a certain (annotated) cell type. 

Let's say I have lists A and B, both containing markers for astrocytes, and a dataset with annotated astrocytes. If I want to test if list A is better in identifying astros in the dataset than list B, would you do a Wilcox test between the scores obtained using list A and B? or better count all the cells with a score > 0.2 (example) and do a chisq on the proportions?

Also, does the length of the list affect the score results?

I would like to hear your thoughts on this, thanks :)

Best,

Giorgia

**Comment by mhkowalski** [comment]
Hello, 

We don't have recommendations on how to compare across module scores with different lists of genes, as this is dependent on both the number of genes in the list, how highly these genes are expressed, and how specific this gene expression is for a particular cell population. It also might not make sense to use the same cutoff for a different list of genes. You could in principle find a good cutoff for both sets of genes and run a chiseq test on the proportions, as you suggest. 

If your goal is to annotate astrocytes in additional datasets based on your annotated dataset, I would recommend you check out our methods for reference mapping, such as this [vignette](https://satijalab.org/seurat/articles/integration_mapping.html).
