### ISSUE TITLE
cells belong to a cluster found close to other clusters

### ISSUE THREAD

**Issue by Sahu-Mousumi** [satijalab/seurat#6853]
Hi!
I am attaching a DImPlot. A bunch of cluster2 cells(in red) are found near cluster 4 and 5. Is it acceptable or do I need to change any clustering options?

Thank you!
![image](https://user-images.githubusercontent.com/74224273/211367393-5d69b93b-4ee2-4837-aad4-ea210a6081f0.png)

**Comment by f6v** [comment]
I can't provide an answer, only comment. I've seen it in my own data, as well is in published datasets. My understanding is that since clustering and UMAP are two distinct algorithms, there can be some disparities. Even though the two use the neighbourhood graph as input.

**Comment by yuhanH** [comment]
Thanks @f6v  for your answers. I agree with you. 
The choice of clustering algorithm, the clustering resolution and the parameters used can also affect the results. If you should separate cluster 2 into another two clusters, it mainly depends on if you can biologically meaningful markers.
Technically, you can use `FindSubCluster()` to further clustering current `cluster2` and check the separated cluster marker genes. Then you may determine what cell types that cluster should be.

**Comment by f6v** [comment]
@Sahu-Mousumi one additional angle is looking for doublets. Or "hybrid transcriptomes", where cells are phenotypically in the middle between, say, T and NK cells. For example:

<img width="229" alt="image" src="https://user-images.githubusercontent.com/13019221/212658796-3bfbe5e5-eef8-40e0-b131-c504b483002c.png">

The highlighted cells (blue) are from one cluster(and already over-clustered!), although you can see two blobs that are far away from each other on the UMAP. 
The small blob on top gravitates towards T cells, although the whole cluster could be annotated as NK cells. In addition, some of the cells in that smaller blob are annotated as potential doublets by `scDblFinder`. And by the way, this is a result from `scVI` + `Scanpy`, so the issue isn't `Seurat`-specific. Understanding what these are will take some in-depth investigation.
