### ISSUE TITLE
unable to load the Brain Vizgen/MERFISH Data

### ISSUE THREAD

**Issue by JuanXie19** [satijalab/seurat#6854]
Hi Seurat team,

Thanks very much for developing Seurat.

I am learning to analyze imaging-based HST data and is following the vignette provided by Seurat(https://satijalab.org/seurat/articles/spatial_vignette_2.html). Yet I am stuck with data loading.

Specifically, when I tried the ReadVizgen function, I got a list of length two, 

![image](https://user-images.githubusercontent.com/98572468/211408321-887235ef-7971-4c4e-b50a-1b42e448cede.png)

but when I tried the LoadVizgen function, I got the following error message:
![image](https://user-images.githubusercontent.com/98572468/211408388-123bf33f-d066-4a2e-bec1-af99fe0dbaba.png)

I had all the HDF files under the cell_boundaries folder, which is located under my data.dir

Could you help and check what might be the problem?

Thanks!

**Comment by AustinHartman** [comment]
@JuanXie19 could you please list the files found in `data.dir` as well as the names of a few of the files in the `cell_boundaries` directory within `data.dir`?

**Comment by JuanXie19** [comment]
Thanks for the response.
Here is the list
![image](https://user-images.githubusercontent.com/98572468/211410731-b63119b2-248a-45e7-950f-59e3140772d9.png)

And the names of some files in the cell_boundaries
![image](https://user-images.githubusercontent.com/98572468/211410818-8de6e04b-3cf1-4a0d-b4f9-6ee31d3ae655.png)

**Comment by AustinHartman** [comment]
I believe the Seurat code expects the files within `cell_boundaries` to follow slightly different naming (see [here](https://github.com/satijalab/seurat/blob/763259d05991d40721dee99c9919ec6d4491d15e/R/preprocessing.R#L2662) if you're curious). In order to immediately workaround this error, I suggest removing the prefix from the files in the `cell_boundaries` directory such that each file follows the following naming structure: `feature_data_[\d]*.hdf5`. In the future, I'll plan to add better flexibility regarding cell boundary file names. If you can share, where did you download this data / did you modify file names at all? I haven't seen cell boundary files with this naming before.

**Comment by JuanXie19** [comment]
Hi Austin,
Thank you very much for the feedback, I got your point and will modify the file names as suggested.
I downloaded the data from the link provided in the vignette.
After going to https://info.vizgen.com/mouse-brain-data, I clicked 'Access ', 
![image](https://user-images.githubusercontent.com/98572468/211442252-690b3634-d93d-47bb-981b-0008dd047bfb.png)

which directed me to a google cloud page:
![image](https://user-images.githubusercontent.com/98572468/211442378-077d58f2-3c4f-4b5f-a788-c510659996aa.png)

I noticed that the files names shown in the folder do not have prefix, yet when I download them, there are prefix in 
The hdf files are downloaded from the cell_boundaries folder:
![image](https://user-images.githubusercontent.com/98572468/211442582-5940a1e7-b8e0-41eb-b107-f60594ab6588.png)

**Comment by JuanXie19** [comment]
Hi Austin,

I modified the files names as suggested, and this time I got an new error message:
![image](https://user-images.githubusercontent.com/98572468/211451686-32723f7e-6290-426e-8095-7eac9d7c0d4c.png)

**Comment by JuanXie19** [comment]
Hi Austin,
I modified the file names as suggested and this time I can load the data successfully. Thank you very much for the help!

**Comment by mabbasi6** [comment]
Hi!
I have the same issue. I am trying to follow the Vignette to load the Vizgen public MERFISH dataset. Here is what the data structure looks like:
![image](https://github.com/satijalab/seurat/assets/75707223/186bc7f8-ff5c-42aa-8ec7-4b804ba4ab7b)
Here is the data structure in the cell_boundaries folder:
![image](https://github.com/satijalab/seurat/assets/75707223/88dce2a8-0e92-4ec8-ad9a-2bd2ad82c017)
Here is the error I get when I run the code to load the data:
![image](https://github.com/satijalab/seurat/assets/75707223/810fa9bb-d50f-4b40-8019-d0370c85faed)

Thank you in advance for your help with this issue!
