### ISSUE TITLE
Add progress bar to all functions that use futures

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#6855]
The [progressr](https://progressr.futureverse.org/) package allows progress bar updates in the future framework with little modifications to existing code for package developers. I think it will be very useful for analysis of large-scale data, that progress updates can be reported and users can choose to visualize those updates.

**Comment by rsatija** [comment]
I think this is a good idea, but as mentioned in other issues, we are re-evaluating the framework we use for parallelization and will update before the official Seurat v5 release. Closing now for our internal tracking, but will include a progress bar when we have an updated solution (though it may not use future)
