### ISSUE TITLE
FeaturePlot label = T not working

### ISSUE THREAD

**Issue by parkjooyoung99** [satijalab/seurat#6856]
With other objects, I had no problem using 'labet = T' parameter for FeaturePlot function when labeling cluster number on featureplot. However, all of the sudden this function gives me Error of 

Error in `[<-.data.frame`(`*tmp*`, labels.loc[, id] == group, id, value = c(Sample = "Sample")) : 
  missing values are not allowed in subscripted assignments of data frames 

I am attaching the link to download my seurat object.  
https://drive.google.com/file/d/11JDrhKrsievMCOd6kPev8HAHxchdJ8d-/view?usp=sharing

And this is my sessionInfo
<img width="728" alt="image" src="https://user-images.githubusercontent.com/77565848/211464435-0fe60305-42a6-412a-8806-e1d35168324e.png">

```r
kera = readRDS('kera_harm.rds')
FeaturePlot(kera, 'KRT1',cols = c('lightgray','red3'),label = T) 
```

Thanks!

**Comment by yuhanH** [comment]
Thank you @lucygarner for answering this issue. 
@parkjooyoung99 does Idents have any NA or  empty value (`""`)?

**Comment by yuhanH** [comment]
hi @parkjooyoung99 
since we haven't heard back from you for two weeks, i will close this issue first. If you still have this issue, we can reopen it.
