### ISSUE TITLE
Integrate data after subset?

### ISSUE THREAD

**Issue by paulatn240** [satijalab/seurat#6857]
Hi, 

I have subset B cells from my data and perform the following steps after subsetting:

```
bcells_subset <- ScaleData(bcells_subset)
bcells_subset <- RunPCA(bcells_subset)
bcells_subset <- RunUMAP(bcells_subset, dims = 1:20)
bcells_subset <- FindNeighbors(bcells_subset, dims = 1:20) %>% FindClusters(resolution = 0.2)

plot1 <- UMAPPlot(bcells_subset , group.by="donor")
plot2 <- UMAPPlot(bcells_subset , label = T) 
plot1+plot2
```
In Plot1 I can see that the cells from the different donors are not completely merged, they form discrete groups. 
But If I perform integration of the donors datasets after I have subset the B cells, in the UMAP the cells from the different donors appeared merged. 
Would be this integration correct?

Thank you very much for your help!

**Comment by mhkowalski** [comment]
Hello, 

It's difficult to answer without understanding and exploring but your data, but in general the integrated version will focus on shared features across your donors. We typically use integration to identify the most similar cell populations between donors. However, it is possible that integration removes some true biological differences between donors as well. 

I recommend running FindMarkers on both the unintegrated and integrated B cell clusters to see if the clustering reflects biological variation between the donors or batch effects. 

Hope this is helpful.
