### ISSUE TITLE
SCTransform on Single Nuclear Data removing almost all cluster markers

### ISSUE THREAD

**Issue by r-osorio** [satijalab/seurat#6858]
Thank you Seurat team for your fantastic work!

I have a question regarding some single nuclear data I am analyzing for the first time (34k cells). I ran through the standard seurat workflow, using `SCTransform(my_dataset, vst.flavor = "v2", vars.to.regress = "percent.mt")` to hopefully fix some batch effect when I eventually integrate this sample with some other ones we will process. However, after running through the workflow to the point of generating clusters and a UMAP, when I run `FindAllMarkers(my_dataset, assay="SCT", slot="data")`, I am only getting a total of 25 markers for the entire seurat object, eleven of which are still mitochondrial genes (MT-ND3, MT-CO2, etc).

Code I have run to get to this point: 

```
my_dataset[["percent.mt"]] <- PercentageFeatureSet(my_dataset, pattern="^MT-")
my_dataset <- subset(my_dataset, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 20)
my_dataset <- SCTransform(my_dataset, vst.flavor = "v2", vars.to.regress = "percent.mt") %>%
    RunPCA(npcs = 30) %>%
    RunUMAP(reduction = "pca", dims = 1:30) %>%
    FindNeighbors(reduction = "pca", dims = 1:30) %>%
    FindClusters(resolution = 0.7)
my_dataset.markers <- FindAllMarkers(my_dataset, assay="SCT", slot="data")
```

These 25 markers, with nearly half being mitochondrial genes, isn't enough to label any of the 7 clusters that resulted from this workflow. Admittedly, this is my first time working with SCTransform, so I thought maybe this was the problem and I was doing something incorrectly, so I tried running through the original seurat workflow instead:

```
test[["percent.mt"]] <- PercentageFeatureSet(test, pattern="^MT-")
test <- subset(test, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 20)
test <- NormalizeData(test)
test <- FindVariableFeatures(test)
all.genes <- rownames(test)
test <- ScaleData(test, features = all.genes)
test <- RunPCA(test, features = VariableFeatures(object = test))
test <- FindNeighbors(test, dims = 1:30)
test <- FindClusters(test, resolution = 0.7)
test <- RunUMAP(test, dims = 1:30)
test.markers <- FindAllMarkers(test)
```

This resulted in 859 markers, which was more helpful in labeling at least some of my clusters. As a result, I am inclined to just proceed with this methodology and ignore SCTransform, but I would like to know why the first workflow did not work, and if there is any way to continue using SCTransform? I am wondering if the problem is with the fact that my data is single nuclear, as I have a single cell dataset (4,000 cells) where SCTransform worked better (3,754 markers), and in testing two other single nuclear datasets of mine, SCTransform produced similarly poor results (anywhere from 5-25 markers per dataset with a bunch of mitochondrial genes).

Thank you for any help you can provide!

**Comment by saketkc** [comment]
Can you update to latest version of Seurat and retry? Also, what happens if you lower the threshold of `logfc.threshold' to something like 0.2 (default is 0.25).

**Comment by r-osorio** [comment]
Updated Seurat today, re-ran with logfc.threshold to 0.2. Unfortunately only got 30 markers total, 6 of which were mitochondrial. The markers still were not helpful in identifying cluster cell types.

**Comment by saketkc** [comment]
If you can share the object at schoudhary@nygenome.org, I will be happy to take a look.

**Comment by giovanegt** [comment]
Hi,
Not from the developing team but, in the past satijalab recommended using the RNA assay (not the SCT) for DEG analysis. 

@satijalab mentioned  "While it is possible to correct these differences using the SCTransform-based integration workflow for the purposes of visualization/clustering/etc., we do not recommend running differential expression directly on Pearson residuals. Instead, we recommend running DE on the standard RNA assay. issue #4032. 

Also, you could play a bit with a different DEG test. The default is Wilcox, which is suitable for handling nonparametric data.
We have used the "negbinom" test before and we were very satisfied with the results. the "negbinom" test, identify DEG between two groups of cells using a negative binomial generalized linear model. 
But again, perhaps the point that comes to mind is whether the person residues from SCT assay are a good form to measure gene expression and can be used in DEG tests.  Perhaps the RNA assay, after QC, batch correction, and Normalization would be our pick.

**Comment by r-osorio** [comment]
Arent the residuals stored in `scale.data` slot of the `SCT` assay? I was writing my analysis off the [SCTransform vignette](https://satijalab.org/seurat/articles/sctransform_vignette.html) where they write:

"We store log-normalized versions of these corrected counts in pbmc[["SCT"]]@data, which are very helpful for visualization.
You can use the corrected log-normalized counts for differential expression and integration. However, in principle, it would be most optimal to perform these calculations directly on the residuals (stored in the scale.data slot) themselves. This is not currently supported in Seurat v3, but will be soon."

I interpreted this as it would be acceptable to find markers using SCT's data or scale.data slots, though scale.data may be preferable. Happy to try the RNA assay though as well as negative binomial testing and report back!

I am also considering just running with the original seurat workflow, as it seems to be readily identifying at least some cluster cell types and from what I can tell, while SCTransform is a powerful tool, it is not strictly necessary to analyze your samples, especially if factors like mitochondrial percent do not need to be regressed out.

**Comment by saketkc** [comment]
We recommed using the corrected counts (stored in the `data` slot of `SCT` assay) for DE analysis and for visualization. Please see the [updated vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for a demo use case which performs DE and visualization of two different conditions (post integration).

**Comment by saketkc** [comment]
Closing as I haven't heard back.
