### ISSUE TITLE
How to obtain scaled data for analyses outside Seurat?

### ISSUE THREAD

**Issue by ravipatel4** [satijalab/seurat#686]
Hello,

I understand that when Seurat regresses out the unwanted sources of variation, it stores the scaled data in `scale.data` slot, which is eventually used for dimensionality reduction. I also understand that the data in `scale.data` is in the form of z-scored residuals. I am interested in performing further analyses, such as clustering, pseudo-time analysis outside of Seurat after removing unwanted sources of variation. My question is how do I use the z-scored residuals from `scale.data` to remove the unwanted variation form the raw data? In another words, is it possible to apply the residuals calculated by Seurat to my raw data and how do I do that?

If you care, the reason I am interested in this is because my cells are divided into two groups: 1) cells with higher nUMI, 2) cells with lower nUMI. We believe that this is due to different properties of cells in different groups. But I want to remove the nUMI covariate from the raw data before I cluster the cells.

Thank you very much for your help in advance.

Best,
Ravi

**Comment by satijalab** [comment]
Hi Ravi - RunPCA uses the @scale.data slot, so all downstream analyses will automatically be based on these values.

If you wish to take the @scale.data values out of seurat (to import into another package), you can access them using the GetAssayData function (or just take the object@scale.data matrix).

**Comment by ravipatel4** [comment]
Hi Satijalab,

Thank you for your reply. 

I think my question wasn't clear enough. I already know from your manual that ScaleData function uses the normalized data, regresses out unwanted sources of variation and scales (z-score) the data, which is eventually stored in @scale.data slot. However this scaled (z-scored) is less useful for other analysis outside Seurat, such as clustering, DE gene analysis, etc. I was wondering if there is a way to extract the regressed-out data before it is scaled (z-scored)?

Thank you.

Best,
Ravi
