### ISSUE TITLE
Subsetting error

### ISSUE THREAD

**Issue by nickchakiryan** [satijalab/seurat#6861]
I am having what is probably a silly issue that I cannot resolve.

Am trying to subset a Cosmx seurat object (nano.obj) to select a single fov.

Successfully able to subset multiple fovs corresponding to clinical response and non-response:

```
> response.set <- subset(nano.obj, 
+                    (Slide_name=="RCC3" & fov=="5")|
+                    (Slide_name=="RCC3" & fov=="6")|
+                    (Slide_name=="RCC3" & fov=="11")|
+                    (Slide_name=="RCC3" & fov=="12")|
+                    (Slide_name=="RCC4" & fov=="3")|
+                    (Slide_name=="RCC4" & fov=="4")|
+                    (Slide_name=="RCC3" & fov=="9")|
+                    (Slide_name=="RCC3" & fov=="10")|
+                    (Slide_name=="RCC3" & fov=="13")|
+                    (Slide_name=="RCC3" & fov=="14")|
+                    (Slide_name=="RCC4" & fov=="7")|
+                    (Slide_name=="RCC4" & fov=="8")|
+                    (Slide_name=="RCC5" & fov=="1")|
+                    (Slide_name=="RCC5" & fov=="2")
+                    )
> 
> table(response.set$fov,response.set$Slide_name)
    
     RCC3 RCC4 RCC5
  1     0    0 4344
  2     0    0 3122
  3     0 3227    0
  4     0 2665    0
  5  5735    0    0
  6  1508    0    0
  7     0 3426    0
  8     0 6090    0
  9  3738    0    0
  10 3432    0    0
  11 2938    0    0
  12 5063    0    0
  13 5092    0    0
  14 2872    0    0
```

However, am unable to accomplish subsetting of a single fov:

```
> rcc.3.5 <- subset(nano.obj, 
+                   (Slide_name=="RCC3" & fov=="5"))
Error in subset.Segmentation(x = x[[i]], cells = cells) : 
  None of the requested cells found
```

There are 5,735 cells meeting these parameters (Slide RCC3 and fov 5), so it is not an issue with missing data corresponding to the selected variables.

Any tips would be appreciated.

**Comment by AustinHartman** [comment]
I'm having trouble reproducing this - any chance you could share this object or a small subset for debugging? My email is ahartman@nygenome.org

**Comment by nickchakiryan** [comment]
Thank you for your response! Unfortunately we cannot share this data.  Any ideas would be appreciated, even if you are unable to 100% confirm.

**Comment by AustinHartman** [comment]
No worries - what could be going on is the cells contained in the `nano.obj` assay are not all included in the image (contains molecule positions, cell boundaries, etc). In order to check this I'd suggest doing something like this:
```r
# get all of the cells from the assay matching subset condition
assay.cells <- Cells(obj[["RNA"]])[obj$condition=="1" & obj$fov=="5"]

# two kinds of boundaries, which aren't necessarily present for all cells
all.segmentation.cells <- Cells(obj[["fov"]], boundary = "segmentation")
all.centroid.cells <- Cells(obj[["fov"]], boundary = "centroids")

# double check that cell boundaries exist for the cells matching subset condition
length(intersect(assay.cells, all.segmentation.cells))
length(intersect(assay.cells, all.centroids.cells))
```

**Comment by nickchakiryan** [comment]
Confirmed segmentation and centroids for all 5,735 cells in this fov. Still not allowing me to subset out these cells. 

> assay.cells.5 <- Cells(response.set[["SCT"]])[response.set$fov==5]
> 
> all.segmentation.cells <- Cells(response.set[["Run5448.RCC3"]], boundary = "segmentation")
> all.centroid.cells <- Cells(response.set[["Run5448.RCC3"]], boundary = "centroids")
> 
> length(intersect(assay.cells.5, all.segmentation.cells))
[1] 5735
> length(intersect(assay.cells.5, all.centroid.cells))
[1] 5735
> fov5 <- subset(x= response.set, subset= fov==5)
Error in subset.Segmentation(x = x[[i]], cells = cells) : 
  None of the requested cells found

Very confusing.

**Comment by nickchakiryan** [comment]
Hey! Update, I figured this out. 

This Nanostring Seurat object has multiple FOVs with their associated segmentations/centroids. When subsetting out a single FOV it tries to carry over the other FOVs as well but without any cells, causing the error. 

This was corrected by just deleting the other FOVs from the Seurat object prior to subsetting.

**Comment by AustinHartman** [comment]
Thanks for the update - this is is confusing behavior I'll try to better handle in a future release
