### ISSUE TITLE
Dotplot interpretation in split.by function

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#6864]
How to interpret this dot plot.My interpretation is:
In Plot , 40% of Cholangiocytes_Treated has v high expression. While Cholangiocytes_CTRL has 50% cells expressing but expression is not high as compared to Cholangiocytes_Treated(40% cells but with high expression).
So Treated has higher expression of CXCL1 than CTRL?
Kindly help me interpreting this?

 
[B.pdf](https://github.com/satijalab/seurat/files/10412500/B.pdf)

**Comment by Gesmira** [comment]
Hi, 
Your interpretation is close, but the color encodes the average expression of all cells in the class, not just the 40/50%.  Please refer to [Dot Plot Visualization](https://satijalab.org/seurat/reference/dotplot) for descriptions of what the color and size mean.
