### ISSUE TITLE
Trouble when generating CreateSeuratObject from raw count matrix

### ISSUE THREAD

**Issue by treps-l** [satijalab/seurat#6865]
Hello everyone,

I am facing trouble when generating a Seurat Object from a publicly available raw count matrix of scRNA-seq data.
The matrix can be downloaded from there (https://www.dropbox.com/s/kdf9hvaze3grlnh/Raw%20counts%20data.zip?dl=1) but it is pretty large (100 K cells) so I created a raw count matrix having the same format with only 5 cells and 4 genes (attached).
[Data.csv](https://github.com/satijalab/seurat/files/10359514/Data.csv)

When I run the following code I end up with a Seurat Object but I lost my cell ids on the way and have an extra row. Do you have any idea on how to circumnavigate this? I did check my data frame before generating the Seurat Object, and it looks fine to me. Is this a format issue?

dataMatrix <- read.csv(file = "Data.csv", header = TRUE, sep = ",")
observations <- dataMatrix[[1]]
features <- colnames(dataMatrix)[-1]
dataMatrix2 <- transpose(dataMatrix[, -1])
colnames(dataMatrix2) <- observations
dataMatrix2$Feature <- features
setcolorder(dataMatrix2, c("Feature", observations))
names(dataMatrix2)[1] <- "orig.ident"
dataMatrix2
<img width="371" alt="image" src="https://user-images.githubusercontent.com/122088579/211490374-3f897261-602e-484d-86fe-6f455b290cdd.png">
seuratObject <- CreateSeuratObject(counts = dataMatrix2)
View(seuratObject@meta.data)
<img width="385" alt="image" src="https://user-images.githubusercontent.com/122088579/211225659-9742a4b6-f3e6-499c-85c8-cc53ab0ef41a.png">

Thanks in advance,

**Comment by alikhuseynov** [comment]
the `dataMatrix2` looks like a data.frame not a matrix. Also, it's probably better to convert large dataset to sparse matrix before generating Seurat object.
Note: in `CreateSeuratObject()`, `counts` are: *Either a matrix-like object with unnormalized data with cells as columns and features as rows or an Assay-derived object*
hope this helps

**Comment by samuel-marsh** [comment]
closing this issue as it is not related to bug in Seurat and we are discussing in Discussions: https://github.com/satijalab/seurat/discussions/6846
