### ISSUE TITLE
SCTransform Error in match(x, table, nomatch = 0L) :    'match' requires vector arguments

### ISSUE THREAD

**Issue by GiuliaSansone** [satijalab/seurat#6867]
Hello all, 
I'm currently working integrating two datasets from the Allen Brain Institute (Human and Mouse V1) and I've been using Harmony  following this tutorial https://hbctraining.github.io/scRNA-seq_online/lessons/06a_integration_harmony.html. 

#Integrate human and mouse datasets
object_list<-list(L1_human2,L1_mouse)
merged_object <- Merge_Seurat_List(list_seurat = object_list)
merged_object <- merged_object %>%
  NormalizeData() %>%
  FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
  ScaleData()%>% 
  SCTransform(object= merged_object, verbose = FALSE)

I keep getting this error: 
 Error in match(x, table, nomatch = 0L) :    'match' requires vector arguments

Please, could someone help me with that? 
Thank you, 
Best.

Giulia

**Comment by saketkc** [comment]
If you are using dplyr pipes (%>%) the first argument is the object itself, so you should be invoking `SCTransform(verbose=FALSE)` without the `object` argument (which is how it is done in the tutorial)
