### ISSUE TITLE
Is Mixscape applicable for pooled scRNA-seq CRISPRa or CRISPRi experiments?

### ISSUE THREAD

**Issue by camelest** [satijalab/seurat#6868]
Dear Seurat team,

Hi, I have gone through the Mixscape vignette. I'm wondering whether Mixscape is applicable for CRISPRa or CRISPRi setting and if not, whether there is some future plan for this direction.

Best,

**Comment by yuhanH** [comment]
Hi, @camelest 
Yes. Mixscape can work for both CRISPRa and CRISPRi. You can need to set the control and targeted guide names properly.
