### ISSUE TITLE
Do we only do QC cell and gene filtering for "spliced" and not "unspliced" RNA in RNA Velocity analysis?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6869]
In the tutorial (http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html), after converting the loom object into Seurat object, we set "spliced" as "RNA" for the Seurat object. I will also want to do cell and gene QC here before doing SCTransform(), RunPCA(), etc to perform clustering prior to doing RNA velocity analysis.

1. Will I only need to do filtering for "nFeature_spliced", "nCount_spliced", etc and not the "unpsliced"? 

2. Should I adjust the gene- and cell-filtering thresholds that I used in my "regular" Seurat clustering analysis for now processing these loom files in order to obtain the inputs for scVelo? 

Thank you so much.

**Comment by ollieeknight** [comment]
Perhaps one way of doing it could be to have your original Seurat object (where both spliced, unspliced, and ambiguous counts are mereged) in a state of dimensionality reduction/clustering after your favourite QC methods that you are happy with, and then subset the cells of your loom object to match the exact same cells?

**Comment by denvercal1234GitHub** [comment]
Hi @ollieeknight

Thank you for your response, but it would not work, because the loom object once converted into Seurat, it will have spliced, unspliced, and ambiguos RNAs. 

So, even though you are right that we could select the cells from these loom objects (now saved Seurat objects) based on the matching cells in the original GEX Seurat object (which has all the QCs done), but the loom object once converted into Seurat, it will have spliced, unspliced, and ambiguos RNAs.

**Comment by ollieeknight** [comment]
ah - i understand! with which package did you generate the ```loom``` files, ```velocyto```?
You could still subset the merged ```loom``` file from the GEx seurat object, right?
```
loom_seurat <- subset(loom_seurat, cells = colnames(seurat_gex))
```

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
