### ISSUE TITLE
Fatal error: creating temporary file for '-e' failed, while running ScaleData

### ISSUE THREAD

**Issue by sunkh1026** [satijalab/seurat#687]
I ran Seurat package (https://github.com/satijalab/seurat) in R. I followed step-by-step as [https://satijalab.org/seurat/pbmc3k_tutorial.html]

Everything worked until
```R
pbmc <- ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito"))
```
and it showed:
```R
> Fatal error: creating temporary file for '-e' failed
```
and the run got stuck. I have no idea what it means --- is it a problem in R or in Linux?

Then, as suggested, I ran:

```R
traceback()
```

Here is the output:
```R
> 6: socketConnection("localhost", port = port, server = TRUE, blocking
> = TRUE, 
>        open = "a+b", timeout = timeout) 5: newPSOCKnode(names[[i]], options = options, rank = i) 4: makePSOCKcluster(names = spec, ...) 3:
> parallel::makeCluster(num.cores) 2: RegressOutResid(object = object,
> vars.to.regress = vars.to.regress, 
>        genes.regress = genes.use, use.umi = use.umi, model.use = model.use, 
>        display.progress = display.progress, do.par = do.par, num.cores = num.cores) 1: ScaleData(object = pbmc, vars.to.regress = c("nUMI", "percent.mito"))
```
Then, as suggested, I ran:
```R
library(parallel)
makeCluster(detectCores() - 1)
```

Here is the output:
```R
> Fatal error: creating temporary file for '-e' failed
```
However, alternately, if I ran:
```R
pbmc <- ScaleData(object = pbmc)
```

that is, I removed the additional argument "vars.to.regress = c("nUMI", "percent.mito")", then it ran fine.

I have no idea how this fatal error occurs while adding one more argument. How to solve this issue? Thanks!

  [1]: https://satijalab.org/seurat/pbmc3k_tutorial.html

**Comment by andrewwbutler** [comment]
Given that 
```R
library(parallel)
makeCluster(detectCores() - 1)
```
throws the same error, this appears to be an issue with the `parallel` and therefore a bit beyond the scope of Seurat.
