### ISSUE TITLE
Converted H5AD file into H5seurat file, but stuck on how to analyse this file

### ISSUE THREAD

**Issue by Ahas80** [satijalab/seurat#6870]
I was trying to do some analysis upon the fetal lung cell atlas ATACseq data from https://www.lungcellatlas.org/ when I ran into a couple of errors in R when I was trying to read the 27.4GB H5AD file, and I was really hoping you might be able to point me in the right direction. 

The code I am running is as below 
￼
install.packages(c('Seurat','SeuratData','SeuratDisk','SCP','reticulate'))

if (!require("devtools", quietly = TRUE)) {
  install.packages("devtools")
}
devtools::install_github("zhanghao-njmu/SCP")

if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-disk")

library(Seurat)
library(SeuratDisk)
library(SeuratData)
library(SCP)
library(reticulate) 

Convert("/Users/Aamir/Desktop/Project/Sequence files/211201Fetal_lung_ATAC.h5ad",dest = "h5seurat", overwrite = TRUE)
**Lung <- LoadH5Seurat("/Users/Aamir/Desktop/Project/Sequence files/211201Fetal_lung_ATAC.h5seurat")**
Lung

And I unfortunately seem to be stumbling on line 24. 

The error I receive is as follows: 
Validating h5Seurat file
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Initializing RNA with data
Error in sparseMatrix(i = x[["indices"]][] + 1, p = x[["indptr"]][], x = x[["data"]][],  : 
  'p' must be a nondecreasing vector c(0, ...)
In addition: Warning message:
In sparseMatrix(i = x[["indices"]][] + 1, p = x[["indptr"]][], x = x[["data"]][],  :
  NAs introduced by coercion to integer range

I was wondering if this might be because of line 23 where I use the convert function, because as I run it I get this warning : 

Warning: Unknown file type: h5ad
Warning: 'assay' not set, setting to 'RNA'
Creating h5Seurat file for version 3.1.5.9900
Adding X as data
Adding X as counts
Adding meta.features from var
Adding X_umap as cell embeddings for umap
Adding cell_type_colors to miscellaneous data
Adding predictedGroup_Un_colors to miscellaneous data

Perhaps I have to state that it isn’t RNA and it is scATAC but im not sure how I might go about doing this and my googling attempts have proven unsuccessful.

Any help wold be much appreciated!

**Comment by Ahas80** [comment]
@mojaveazure perhaps you might have a fix for my issue, or even some advice on what I could do different?

**Comment by yuhanH** [comment]
You have a try on this package, sceasy https://github.com/cellgeni/sceasy which can convert different single-cell data formats.

**Comment by Ahas80** [comment]
> 

This only converts the single cell data into various formats, I was hoping to convert the data and then load the data so I could perform analysis via Seurat. the convert function worked (or so it seems), but the load H5seurat function is where there seems to be an error popping up. do you know what I might be able to do about this as I want to follow the exact analyses that the paper has undertaken but im struggling to do that with seurat.

**Comment by yuhanH** [comment]
Not fully understand. Does the below script work for you?
```
input_file = "/xxx/211201Fetal_lung_ATAC.h5ad"
output_file = "/xxx/211201Fetal_lung_ATAC_seurat.rds"

# save h5ad into a seurat object
sceasy::convertFormat(input_file, from="anndata", to="seurat", outFile= output_file)

# load h5ad ad a seurat object in the R session
obj <- sceasy::convertFormat(input_file, from="anndata", to="seurat")

```

**Comment by Ahas80** [comment]
> Not fully understand. Does the below script work for you?
> 
> ```
> input_file = "/xxx/211201Fetal_lung_ATAC.h5ad"
> output_file = "/xxx/211201Fetal_lung_ATAC_seurat.rds"
> 
> # save h5ad into a seurat object
> sceasy::convertFormat(input_file, from="anndata", to="seurat", outFile= output_file)
> 
> # load h5ad ad a seurat object in the R session
> obj <- sceasy::convertFormat(input_file, from="anndata", to="seurat")
> ```

I am now having an issue when doing the second step which results in the following error

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': negative length vectors are not allowed

**Comment by yuhanH** [comment]
em... You may need to check the anndata version for `211201Fetal_lung_ATAC.h5ad` and install proper version anndata.
Then, you use `reticulate` directly to extract the information you need to construct a new Seurat object. 
For example
```
library(reticulate)
library(anndata)
library(Seurat) 
library(Matrix)

sc <- import('scanpy', convert = FALSE)
numpy <- import('numpy', convert = FALSE)
anndata<- import('anndata', convert = FALSE)
scipy<- import('scipy', convert = FALSE)

adata <- py_to_r(sc$read_h5ad("211201Fetal_lung_ATAC.h5ad") )
mat <- as.sparse(adata$X)
colnames(mat) <- make.unique( as.character(adata$var$gene_name))
obj <- CreateSeuratObject(counts = t(mat), meta.data = adata$obs )
```
You can also add dimensional reduction into seurat object using similar ways.

**Comment by Ahas80** [comment]
Hey Yuhan, 
a quick question if you dont mind, how would I check the anndata version for my file please?  After I manage this I will give your reticulate method a go.
I have tried it before but It didnt work. 

Also just wanted to say thanks so much for helping! I've been stuck on this for so long and I really do appreciate your time

**Comment by yuhanH** [comment]
Hi,
You can try to find more information in the manuscript that uses this data.
 If you cannot find exact information, you can have a try on anndata 0.8 and 0.7. There are some big changes between those two version.
