### ISSUE TITLE
Demultiplexing scRNA data set using HTODemux gives different output when subsetting the data sets into cell types 

### ISSUE THREAD

**Issue by moutazhelal** [satijalab/seurat#6876]
Thank you for reading my Issue

I am analyzing scRNA seq data set of almost 8000 cells which contains diverse cell types (T cells, Epithelial cells, Myeloid cells) from breast tissue Hashtaged with 4 Hashtags. After demultiplexing I lost almost 85% of my epithelial cells because they are assigned as negative but the loss in the other cell types are negligible .
I follow these steps:

```
all_Samples <- Read10X(data.dir = "I:/outs/filtered_feature_bc_matrix")
Seurat.object = CreateSeuratObject(counts = all_Samples$`Gene Expression`)

Normalize RNA and find and scale variable features
Seurat.object <- NormalizeData(Seurat.object)
Seurat.object <- FindVariableFeatures(Seurat.object, selection.method = "mean.var.plot")
Seurat.object <- ScaleData(Seurat.object, features = VariableFeatures(Seurat.object))

 Normalize HTO data
Seurat.object[['HTO']] = CreateAssayObject(counts = all_Samples$`Antibody Capture`)
Seurat.object <- NormalizeData(Seurat.object, assay = "HTO", normalization.method = "CLR")
Seurat.object <- HTODemux(Seurat.object, assay = "HTO", positive.quantile = 0.99)
table(Seurat.object$HTO_classification.global, Seurat.object$Global_Cell_types)
```

![image](https://user-images.githubusercontent.com/63544197/213180178-9797422f-0087-478b-88a4-dd1ab6fbb2b1.png)

I had an idea to assign first global cell types based on canonical cell markers afterwords I splite each cell type in a separate Seurat object. On those separated object I preformed demultiplexing. For epithelial cells, the cell assigned as Singlets tippled my workflow is mentioned below

```
all_Samples <- Read10X(data.dir = "I:/outs/filtered_feature_bc_matrix")
Seurat.object = CreateSeuratObject(counts = all_Samples$`Gene Expression`)
 Normalize RNA and find and scale variable features
Seurat.object <- NormalizeData(Seurat.object)
Seurat.object <- FindVariableFeatures(Seurat.object, selection.method = "mean.var.plot")
Seurat.object <- ScaleData(Seurat.object, features = VariableFeatures(Seurat.object))

Normalize HTO data
Seurat.object[['HTO']] = CreateAssayObject(counts = all_Samples$`Antibody Capture`)
Seurat.object <- NormalizeData(Seurat.object, assay = "HTO", normalization.method = "CLR")
 UMAP and clustering
Seurat.object <- RunPCA(Seurat.object, features = VariableFeatures(Seurat.object))
Seurat.object <- FindNeighbors(Seurat.object, reduction = "pca", dims = 1:10)
Seurat.object <- FindClusters(Seurat.object, resolution = 1, verbose = FALSE)
Seurat.object <- RunUMAP(Seurat.object, dims = 1:10)
DimPlot(Seurat.object, reduction = "umap", cols = polychrome_pal , label = T)
plot markers genes to assign cell types
FeaturePlot(Seurat.object, features = c( "DCN", "LUM", "THY1", "ACTA2". "EPCAM", ""KRT7",  "CD3E","CD3D", "TRAC", ), slot ='data') 
 Rename clusters 
Idents(Seurat.object) = "RNA_snn_res.1"
Seurat.object <- RenameIdents(Seurat.object, '1' = 'Epithelial.cells', '7' = 'Epithelial.cells', '8' = 'Epithelial.cells'
                        , '20' = 'Epithelial.cells',  '13' = 'Epithelial.cells',  '5' = 'Epithelial.cells',  '10' = 'Epithelial.cells')

Seurat.object@meta.data[["Global_Cell_types"]] = Idents(Seurat.object)
 Subset only epithelial cells 
Seurat.object.epi.b <- subset(Seurat.object, idents = "Epithelial.cells"  )
Seurat.object.epi.b <- HTODemux(Seurat.object.epi.b, assay = "HTO", positive.quantile = 0.99)
table(Seurat.object.epi.b$HTO_classification.global, Seurat.object.epi.b$Global_Cell_types)
```
![image](https://user-images.githubusercontent.com/63544197/213180265-671ddd08-8eaf-408d-8b8b-1943d1aa7fe7.png)

This difference is due to the change in the cut off s for each Hashtag 
when demultiplexing all cells 

> Cutoff for B0251 : 29 reads
> Cutoff for B0252 : 75 reads
> Cutoff for B0253 : 9218 reads
> Cutoff for B0254 : 456 reads

When demultiplexing epithelial cells 

> Cutoff for B0251 : 29 reads
> Cutoff for B0252 : 73 reads
> Cutoff for B0253 : 2973 reads
> Cutoff for B0254 : 383 reads

My question is which approach should I follow and why this huge change in cell number.

I appreciate any help,
Moutaz

**Comment by ollieeknight** [comment]
Firstly, I would use FeatureScatter to compare the expression of each hashtag against each other
```
library(tidyverse)

DefaultAssay(Seurat.object) <- 'HTO'
FeatureScatter(Seurat.object, 'Hashtag1','Hashtag2') & coord_fixed()
FeatureScatter(Seurat.object, 'Hashtag1','Hashtag2') & coord_fixed()
````
Then one way could be to manually define hashtags, such as (1 for an expression is just a guess, yours _will_ differ)
```
Seurat.object$hash_annotation <- "Unclear"
hash1 <- WhichCells(Seurat.object, expression = Hashtag1 > 1 & Hashtag2 < 1 & Hashtag3 <1 & Hashtag4 <1)
Seurat.object$hash_annotation <- ifelse(colnames(Seurat.object) %in% hash1, "Hashtag1", Seurat.object$hash_annotation)
# and so on for hash2, 3 and 4.
Seurat.object < - SetIdent(Seurat.object, value = 'hash_annotation)
```

Then, you can perform your Feature Scatters again and see how your chosen expression cutoffs look.

**Comment by mhkowalski** [comment]
Hi, 

It seems like the distribution of counts for your hashtags might be very different, based on the cutoff values. Do your other cells besides epithelial cells have much higher HTO counts? This would explain why you are calling your epithelial cells mostly negatives.  It seems valid to run HTODemux on just the epithelial cells.  I would just be sure to check the distribution of HTO counts for all cells and just epithelial cells to see if you believe the results for either case (for each Hashtag, ideally there is a clear positive and negative population and your chosen cutoff reflects this).
