### ISSUE TITLE
About applying UMAP/PCA over certain number of clusters

### ISSUE THREAD

**Issue by Pedramto89** [satijalab/seurat#6877]
Once we got the number of clusters after doing umap, is it possible to do again umap or pca over some certain number of clusters?

**Comment by alikhuseynov** [comment]
clusters are coming `FindClusters()` not from running UMAP, that's independent.
you can subset object to keep specific clusters and re-run UMAP.

**Comment by yuhanH** [comment]
Thanks @alikhuseynov  for your reply.
Right. You can subset the object and then re-run UMAP.
