### ISSUE TITLE
Subset by ident cluster shows discrepencies 

### ISSUE THREAD

**Issue by randystyle21** [satijalab/seurat#6879]
Hello, Seurat Developers. I tried to find this answer from the previous issues but I couldn't find it. I don't know how to put this in words. So I will add code down there. So practically, there is a little discrepancies when you subset a specific cluster then reverts its identity to the integrated_snn_res.xx. 

I assigned cluster 12 into beta in integrated_snn_res.0.8 . Then I subset alpha cluster, and change the identity to the integrated_snn_res.0.8 but it weirdly has cluster 12. (which is not major, it's 8 cells only.) And several other clusters like 1~2 cells. I hope I was clear enough. So what does this mean? Should I remove these cells?

'''R

Idents(seurat_reference) <- "integrated_snn_res.0.8"
seurat_reference <- RenameIdents(seurat_reference,
"0"="alpha","5"="alpha","7"="alpha","10"="alpha","15"="alpha",
"3"="beta","1"="beta","13"="beta","2"="beta","9"="beta","16"="beta","6"="beta","12"="beta",
"4"="delta","8"="PP",
"18"="acinar","11"="ductal",
"19"="endothelial",
"21"="schwann",
"17"="mast","20"="mono/macro",
"14"="stellate")

alpha_only <- subset(seurat_reference, ident="alpha")

Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from proj.umap_ to projumap_
--
 
  |
 

<br class="Apple-interchange-newline">

Idents(alpha_only) <-"integrated_snn_res.0.8"
levels(alpha_only) 

[1] "0"  "1"  "3"  "5"  "7"  "9"  "10" "12" "13" "15"
'''

**Comment by ollieeknight** [comment]
I've found this before, and a way to fix it is:

```
Idents(seurat_reference) <- "integrated_snn_res.0.8"
seurat_reference <- RenameIdents(seurat_reference,
"0"="alpha","5"="alpha","7"="alpha","10"="alpha","15"="alpha","3"="beta","1"="beta","13"="beta","2"="beta","9"="beta","16"="beta","6"="beta","12"="beta","4"="delta","8"="PP","18"="acinar","11"="ductal","19"="endothelial","21"="schwann","17"="mast","20"="mono/macro","14"="stellate")
seurat_reference[["celltype"]] <- Idents(object = seurat_reference)
seurat_reference <- SetIdent(seurat_reference, value = 'celltype')


alpha_only <- subset(seurat_reference, ident="alpha")
```

Let me know if this worked?
