### ISSUE TITLE
RunMultiCCA error

### ISSUE THREAD

**Issue by YanaKotlyarenko** [satijalab/seurat#688]
Hello,
I have a list of SeuratObjects to which I was trying to apply RunMultiCCA, but I keep having this error:

Error in data.use[genes.use, ] : subscript out of bounds

Every object has different cell identities and same meta.data names. 
What can be the issue?
Thank you very much.

**Comment by leonfodoulian** [comment]
Hi,

Could you please paste the code and a `traceback()` for easier troubleshooting?

Best,
Leon

**Comment by YanaKotlyarenko** [comment]
Hi, 

the problem was that I was using a summation of var.genes in "genes.use = ", so some genes were redundant. Now I'm using the command "unique" to create the genes list, and it works. 

Thank you very much for your time and attention anyway.
