### ISSUE TITLE
Subset of specific cells

### ISSUE THREAD

**Issue by merveyrc** [satijalab/seurat#6882]
Hello, I have data of PBMC sample containing cells of different diseased and healthy control subjects (three types of diseased subjects and healthy control in one sample). I saw this information in the cell metadata file I downloaded from GEO (GSE194315_CellMetadata-AS_TotalCiteseq_20220711.tsv.gz.). 
How can I separate specific cell barcodes (about 50000 cell) from the metadata of my seurat object? I just want to use one type of diseased subject cells.

**Comment by AustinHartman** [comment]
You can add the metadata to the `Seurat` object with the `AddMetaData` function once you've loaded the metadata from GEO into a data.frame. Next, you can subset your Seurat object to only contain the cells classified as diseased. The code should look something like this:
```r
seurat.object <- AddMetaData(seurat.object, metadata = metadata.dataframe)
Idents(seurat.object) <- "disease.state" # or whatever you choose to name the metadata column
disease.cells <- WhichCells(seurat.object, idents = "disease") # name of category in metadata column indicating a cell is in diseased state
subset.seurat.object <- subset(seurat.object, cells = disease.cells)
```
