### ISSUE TITLE
filtering out MT/RPS genes from a list of genes

### ISSUE THREAD

**Issue by nicoleconzucchero** [satijalab/seurat#6883]
Hi all, I am a newbie to single cell analysis and R, and have got stuck on something:
I have clustered a dataset (5 clusters), and performed differential expression testing, so I have a list of up&down - regulated genes for each cluster (10 lists)

![Screenshot 2023-01-20 at 15 07 39](https://user-images.githubusercontent.com/123184262/213731560-e515c4c6-5154-4d92-8688-4d6ae5228ed8.png)

there's lots of MT and RP genes in these lists, which I'd like to exclude, but I cannot find the code for it. I have tried several things (which may well be very stupid/wrong):

myGenes.RPS <- tfh.markers.2 & !pattern="^TRB|^TRA|^TRG|^TRD|^RPS|^RPL|^MT-"
myGenes.RPS <- list(UP.0=tfh.markers.2$gene[tfh.markers.2$avg_log2FC > 0.01 & tfh.markers.2$p_val_adj< 0.05 & tfh.markers.2$cluster == 0 & VariableFeatures(tfh.markers.2)[!grepl(VariableFeatures(tfh.markers.2),pattern="^TRB|^TRA|^TRG|^TRD|^RPS|^RPL|^MT-")]
myGenes.RPS <- myGenes$UP.0 & grep(pattern = "^TRB|^TRA|^TRG|^TRD|^RPS|^RPL|^MT-", x = myGenes$UP.0)

*tfh.markers.2 is the result of the differential expression testing using FindAllMarkers function
*myGenes$UP.0 is a list of upregulated genes from cluster 0

Any ideas what the correct code to filter out certain genes from a list is?

Thanks x

**Comment by shahrozeabbas** [comment]
Hi,

If you look at the documentation for `FindMarkers` and `FindAllMarkers`, there is a `features` parameter that allows the user to only consider certain genes when performing the DE testing. What you might be able to do is filter out the genes from your list you don't want to consider prior to calculating DE genes. See the example below:

```
gene.list <- c('geneA', 'geneB', 'geneC', 'MT-CYB')
new.gene.list <- gsub('^MT-(.*)', NA, gene.list)
final.gene.list <- new.gene.list[!is.na(new.gene.list)]
markers <- FindAllMarkers(seurat_object, features=final.gene.list)
```

You can do the same with RP genes. Also, you could take a look at the `stringr` package which provides many functions for easily manipulating characters/strings in R. Hope this helps!

**Comment by mhkowalski** [comment]
To subset a vector of genes to remove mitochondrial genes, for instance, you could do something like 
`genes[grep("^MT", genes, invert=TRUE)]`. I would hope this is helpful. I would consult grep documentation for additional details.
