### ISSUE TITLE
how to create Seurat Object with scRNA seq data which is not from 10X Genomics platform

### ISSUE THREAD

**Issue by xhNorthwestern** [satijalab/seurat#6885]
Hi,

I want to use Seurat package to re-analyze single cell RNA (scRNA) sequencing data which was from published papers. The data is not from 10X Genomics platform, and I got it from NCBI GEO database as txt file. I do not know how to create Seurat Object with it. Could you give me some suggestions?  I would really appreciate your help.

Thanks.

**Comment by shahrozeabbas** [comment]
Hi, 

Please see the `CreateSeuratObject` function. [Here](https://mojaveazure.github.io/seurat-object/reference/CreateSeuratObject.html) is the link for the documentation. 

Hope this helps!

**Comment by xhNorthwestern** [comment]
Hi @shahrozeabbas , it worked. Thanks for your suggestions!
