### ISSUE TITLE
Description of cell types in meta.data slot from the seurat object

### ISSUE THREAD

**Issue by amitgilboa** [satijalab/seurat#6886]
Hi,

I can not understand some of the cell types of the meta.data slot from the seurat object. For example what is the meaning of: nonproliferating mature active B cells? I thought an active B cell continues to proliferate as long as it lives. 
Do you have an explanation for each cell type in single-cell RNA data?

Thanks in advance,
Amit

**Comment by ollieeknight** [comment]
This is an issues page for the Seurat package and not any specific data analysis stemming from published data - please close this request and look at the original paper/contact the authors to find out why these cells are named as such.
