### ISSUE TITLE
SCT v2 and normalized visualization

### ISSUE THREAD

**Issue by beamaraba** [satijalab/seurat#6888]
Hi,
I have three datasets that I integrated and normalized with SCTv2. My question is regarding visualization doing DotPlots. Is it ok to use the normalized data to compare different datasets (DEG) now with SCTv2 or is it still necessary to use the RNA data? And if I have less than 5 groups, is it still fine to do dotplots or I should do the Vlnplot instead?
Thanks!

**Comment by saketkc** [comment]
You can use the SCT assay for visualization. If there is a huge variation between the sequencing depths of the three datasets, you should run `PrepSCTFindMarkers` before visualization - this will ensure the sequencing depth corrected counts are comparable across the datasets. An example workflow is avaialable in this [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html)
