### ISSUE TITLE
merging different sequencing files from same sample!

### ISSUE THREAD

**Issue by Elham-adabi** [satijalab/seurat#6889]
Dear Seurat team, 

I am trying to re-analyze the publicly available dataset, in which they have two sequencing files for one sample. one from 10x and the other is a method called capID, 
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE151511,  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE150992
The capID is meant to supplement the 10x data. my question is how can I add the expression data from the capID to 10x.  I want to get the true number of cells expressing a gene by combining two expression matrixes,  and I tried the following code for one sample: 

P01 <- CreateSeuratObject(counts = P01, project = "P01", min.cells = 3, min.features = 200)
P01capID <- CreateSeuratObject(counts = P01capID, project = "P01capID", min.cells = 3)

merged_P01 <- merge(P01, P01capID)
Warning: Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

merged_P01[["percent.mt"]] <- PercentageFeatureSet(merged_P01, pattern = "^MT-")
merged_P01_filtered <- subset(merged_P01, subset = nFeature_RNA > 200 & nFeature_RNA < 7000 & percent.mt < 15)
merged.P01 <- NormalizeData(merged_P01_filtered)
VlnPlot(merged.P01, features = "FMC63-CD19SCFV", pt.size = 0.01)+geom_hline(yintercept = log1p(0.4))+NoLegend()

![image](https://user-images.githubusercontent.com/102491571/214067653-ab51f311-807b-4758-95dc-3d47fb2a865a.png)

Considering that these two (10x and capID) have different thresholds for defining the positive and negative populations, I have to split the objects at this point and then define positive cells for each method separately.?

I was wondering if my analysis aproach for these data sets is correct or there is another way that I can supplement the 10x data with the capID data?

**Comment by f6v** [comment]
I'd suggest to do the QC separately and then combine objects to run the standard clustering workflow. You can then assess if the technical differences between the datasets are stronger than the biological similarity. Based on that you can decide whether you need to do the batch effect correction between the different assays.

**Comment by saketkc** [comment]
@Elham-adabi I believe the capID dataset was performed on a smaller gene panel (this explains the huge difference in expression of the same gene across the two datasets on your plot). If you want to compare 10X vs capID I would recommend subsetting them both the the same gene set before running normalization. Feel free to reopen with any followup questions.
