### ISSUE TITLE
Converting from AnnData to Seurat/sce

### ISSUE THREAD

**Issue by cgraham13** [satijalab/seurat#6891]
Hello,

I am attempting to read an h5ad object into R to use with Seurat. I have been trying to use the SeuratDisk Convert() function but R keeps crashing. I have ~30GB of storage on my computer so I don't think this is the issue, especially since I am attempting to save to an external disk.

I have attached a screen shot of how far the analysis gets. The code I am using is:

maus_ad <- Convert("/Volumes/CarlysData/Data/GSE174188_CLUES1_adjusted.h5ad", dest = "h5seurat", overwrite = TRUE)

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/20915287/214442485-d0d62f98-f4ad-4ec7-9543-ebf16539d774.png">

Any help or other approaches are appreciated, thanks!

Carly

**Comment by yuhanH** [comment]
You have a try on this package, `sceasy` https://github.com/cellgeni/sceasy which can convert different single-cell data formats.

**Comment by yuhanH** [comment]
I will close this issue first. If it is not solved, we can open this later.
