### ISSUE TITLE
unable to load data LoadVizgen

### ISSUE THREAD

**Issue by Elena983** [satijalab/seurat#6895]
I saw a similar question but can not solve it by myself.
I took another merscope data.
but still, have an error in loading.
![image](https://user-images.githubusercontent.com/68946912/214854923-0e7896ed-9b6a-44e4-ae92-55197a2e5145.png)

![image](https://user-images.githubusercontent.com/68946912/214854969-22db5d2b-5593-459b-89c4-171cc44e20d7.png)

![image](https://user-images.githubusercontent.com/68946912/214855000-aab74192-e149-476e-b8f7-d77e32e2edd1.png)

**Comment by samuel-marsh** [comment]
Hi,

I believe that’s error looking for hdf5r package.  Do you have the hdf5r package installed?  If not try installing that and seeing if it solves the error.

Best,
Sam

**Comment by Elena983** [comment]
I have already done it, and the process started, but after 2 min, I received this
![image](https://user-images.githubusercontent.com/68946912/214913706-6c6a5a9f-b3ab-4eb3-9fdd-4403d7d631e9.png)

**Comment by samuel-marsh** [comment]
A quick google search seems to indicate the most likely issue is corrupt hdf5 file or file not truly in h5 format.  If you download the dataset featured in Seurat vignette are you able to load that?
https://satijalab.org/seurat/articles/spatial_vignette_2.html

**Comment by alikhuseynov** [comment]
Hi, I think that has to do with your `feature_data_*.hdf5` files, some of them have `0B` on that screenshot you posted.
Probably if you remove (or disregard) those "empty" files, it will solve the issue.
Hope this helps.

**Comment by Elena983** [comment]
I re-downloaded the folder, and it worked fine.
Thanks

**Comment by samuel-marsh** [comment]
Great!
