### ISSUE TITLE
Graph.name not present in FindClusters().

### ISSUE THREAD

**Issue by Chanukya-Pavan** [satijalab/seurat#6896]
Hi,

I am working on DE analysis currently and I after integrating two large datasets as suggested in the pipeline, I stared FindCluster() too. I followed the exact instructions and received an error saying 'graph.name not present', after looking up at #2995 issue I added the line where I set default assay to integrated, yet the issue was there. What can I do to resolve this issue.

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Could you please post the full code that you are running and full error message?

Thanks!
Sam

**Comment by Chanukya-Pavan** [comment]
Hi,

This was the code I used

1. DefaultAssay(combined.integrated ) <- "integrated"
2. combined.integrated <- ScaleData(combined.integrated, verbose = FALSE)
3. combined.integrated <- RunPCA(combined.integrated, npcs = 30, verbose = FALSE)
4. combined.integrated <- RunUMAP(combined.integrated, reduction = 'pca', dims = 1:20)
5. combined.integrated <- FindClusters(combined.integrated, resolution = 0.5)
6. combined.integrated <- FindNeighbors(combined, reduction = "pca", dims = 1:20)

The error I got for line 5 is this:

Error in FindClusters.Seurat(combined.integrated, resolution = 0.5) : 
  Provided graph.name not present in Seurat object

Let me know if I need to provide anything else.

**Comment by Chanukya-Pavan** [comment]
Hi Sam,

I was reviewing my code again and found that the order was wrong with lines 5 and 6, so I interchanged and encountered a new error with FindCluster(....) same code as above just 5 and 6 interchanged.

The error is:
Error: Cannot find 'pca' in this Seurat object.

I looked at #5395 but it seemed a bit complicated. Sorry for the silly mistake above, could you help me with this?

Thanks, 
Chanukya

**Comment by ollieeknight** [comment]
Chanukya - one way to check the graphs in your seurat object is (where my seurat object is 'alldata')

`
names(alldata@graphs)
[1] "wknn" "wsnn"
`

You can then specify this in your FindClusters command, such as:
`
alldata <- FindClusters(alldata, graph.name = "wsnn", resolution = 0.1, algorithm = 4, group.singletons = T)
`

**Comment by Chanukya-Pavan** [comment]
Hi Ollieeknight,

Thanks for your response, it is very helpful. Sadly I couldn't figure out the other error that I posted, I would be gladdened if you can help me in that regard.

Thanks,
Chanukya

**Comment by ollieeknight** [comment]
I think you're missing a step - does this work?

```
library(tidyverse)
combined.integrated <- FindVariableFeatures(alldata, verbose = FALSE, assay = "integrated") %>%
ScaleData(verbose = FALSE) %>%
RunPCA(verbose = FALSE) %>%
RunUMAP(reduction = 'pca', dims = 1:20)
combined.integrated <- FindNeighbors(combined, reduction = "pca", dims = 1:20)
combined.integrated <- FindClusters(combined.integrated, resolution = 0.5)
```

**Comment by Chanukya-Pavan** [comment]
Hi ollieknight,

I have used your suggestions and was able to solve the issue. Thanks for the help.
