### ISSUE TITLE
I think it is necessary to recover the original gene activity matrix creation function

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#6897]
Hi, I find that the current Geneactivity() function can only work for scatac-seq data with peaks and fragement information. However, plenty of current data do not provide such information, and I think it is also an important feature, mentioned by this question with no answer:
https://www.biostars.org/p/9525109/

Therefore, I think it is still necessary to keep the original seurat functin, known as
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "./ad paper dataset/Homo_sapiens.GRCh37.87.gtf",
seq.levels = c(1:22, "X", "Y"), upstream = 2000, verbose = TRUE)
For the current work. Or do we have any similar fuctions that can help us directly construct gene activity score matrix directly from peaks matrix? Thanks a lot.

**Comment by mhkowalski** [comment]
Hello, 

This question relates to Signac, so I would direct you to open an issue in the Signac github. Thanks!
