### ISSUE TITLE
UMAP connectivity plot 

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#6898]
### _Can a direct call to this plot be implemented in Seurat?_
(Sorry if its already available, I did not find it)

> UMAP works by constructing an intermediate topological representation of the approximate manifold the data may have been sampled from. In practice this structure can be simplified down to a weighted graph. Sometimes it can be beneficial to see how that graph (representing connectivity in the manifold) looks with respect to the resulting embedding. It can be used to better understand the embedding, and for diagnostic purposes. To see the connectivity you can use the umap.plot.connectivity function. It works very similarly to the umap.plot.points function, and has the option as to whether to display the embedding point, or just the connectivity. To start let’s do a simple plot showing the points:
Source: https://umap-learn.readthedocs.io/en/latest/plotting.html#plotting-connectivity

`umap.plot.connectivity(mapper, show_points=True)`
![](https://umap-learn.readthedocs.io/en/latest/_images/plotting_32_2.png)

`umap.plot.connectivity(mapper, edge_bundling='hammer')`
![](https://umap-learn.readthedocs.io/en/latest/_images/plotting_34_2.png)

### This seems to be a generally useful tool to interpret UMAP representations more carefully.

**Comment by yuhanH** [comment]
hi @vertesy 
Seurat uses [uwot](https://github.com/jlmelville/uwot) to generate UMAP visulization. Do you know if uwot has this functionality?

**Comment by vertesy** [comment]
mmm...

https://github.com/jlmelville/uwot/issues/65

**Comment by jlmelville** [comment]
uwot does not do this.

**Comment by yuhanH** [comment]
@jlmelville Thanks for your reply!

**Comment by denvercal1234GitHub** [comment]
@yuhanH and @jlmelville -- So did Seurat implement this feature in the end? Thank you

**Comment by jlmelville** [comment]
@denvercal1234GitHub I don't work on Seurat so I am unable to tell you.
