### ISSUE TITLE
Visualizing gene expression with scale.data slot

### ISSUE THREAD

**Issue by tanonymush** [satijalab/seurat#6899]
Dear Seurat team,

Thank you for providing an extremely useful package!

I have a question regarding plotting gene expressions using the FetchData command.
I am plotting the expression of two genes to investigate their correlation, but which assay / slot would be the most suitable to use in this type of assay? 

Additionally, when I use scale.data slot, it usually create these "branching" pattern; how can this be explained?

![Screenshot 2023-01-27 at 21 33 07](https://user-images.githubusercontent.com/20794769/215088077-0ba23943-1634-454e-8df4-725ba0c8aa24.png)

Thank you in advance,

Taimu

**Comment by ollieeknight** [comment]
This could potentially be an issue with gene dropout. One method to recover this could be by using an imputation method like [MAGIC](http://htmlpreview.github.io/?https://github.com/KrishnaswamyLab/MAGIC/blob/master/Rmagic/inst/examples/bonemarrow_tutorial.html)?

**Comment by saketkc** [comment]
You should be using the `data` slot for visualization. `scale.data` centers the centered and scaled values for each feature.
