### ISSUE TITLE
subset function does not work if Seurat version changes

### ISSUE THREAD

**Issue by parkjooyoung99** [satijalab/seurat#6904]
I have seurat object made with 'v.4.2.1' and currently using seurat 'v.4.3.0'.
Here, I cannot use subset function due to the error below. 
Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  invalid character indexing
  
I had this error before and reported here https://github.com/satijalab/seurat/issues/6720  and found the the version of seurat for the object and the current environment matters.

I think this should be fixed since it might be impossible to make new object every time I update my seurat version. 
Thank you!

You can download my seurat object made with seurat 'v.4.2.1'
https://drive.google.com/file/d/1sxVHsczFYzj0fCFJH9rnh7IJYTPalWRU/view?usp=sharing

<img width="790" alt="image" src="https://user-images.githubusercontent.com/77565848/215426767-26305194-4107-4f78-93c5-211d42a0c828.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/77565848/215427104-0c2fb859-f0a7-439d-bd00-a5a5128c99d5.png">

```r
lym = readRDS(' ') object can be downloaded here https://drive.google.com/file/d/1sxVHsczFYzj0fCFJH9rnh7IJYTPalWRU/view?usp=sharing
idx = rownames(lym@meta.data)[(lym$seurat_clusters %>% as.character()) %in% c('5','14','15','17')]
lym = subset(lym, cells = idx)
```

**Comment by parkjooyoung99** [comment]
It worked perfectly, 
thanks for your recommendation!

**Comment by aitoe96** [comment]
Hi all,

I have the same issue:

> s_nodups[[5]] = subset(s[[5]], subset = Doublets == "Singlet")
Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  invalid character indexing

, and the given solution doesn't work for me, obtaining a new error: 

> selected <- WhichCells(s[[5]], idents = "Singlet")
Error in WhichCells.Seurat(s[[5]], idents = "Singlet") : 
  Cannot find the following identities in the object: Singlet

Note:
1. I'm sure that the object contains a metadata slot with the identities.
2.The subset function works for the rest objects but not for this particular one.

**Comment by ollieeknight** [comment]
is the metadata column 'Doublets'? If you perform
alldata <- SetIdent(alldata, value = 'Doublets')
selected <- WhichCells(alldata, idents = 'Singlet'), what is the error?

**Comment by aitoe96** [comment]
Doing what you say:

>s[[5]] <- SetIdent(s[[5]], value = 'Doublets')
> selected <- WhichCells(s[[5]], idents = 'Singlet')
> s[[5]] <- subset(s[[5]], cells = selected)

Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  invalid character indexing

**Comment by aitoe96** [comment]
Doing what you say:

> s[[5]] <- SetIdent(s[[5]], value = 'Doublets')
> selected <- WhichCells(s[[5]], idents = 'Singlet')
> s[[5]] <- subset(s[[5]], cells = selected)

Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  invalid character indexing

**Comment by ollieeknight** [comment]
when you perform ```selected <- WhichCells(s[[5]], idents = 'Singlet')```, does ```selected``` get assigned a string of cell barcodes?

**Comment by aitoe96** [comment]
Yes, It does

**Comment by ollieeknight** [comment]
hmm, i'm not sure what to suggest from here. Things you could try:
```
common <- intersect(colnames(s[[5]]), selected # are the 'selected' cells found in the barcodes of the object?
```
Do your cell barcodes have anything appended to them, or are they as basic as ```"ATAAGAGAGAGCCTAG-1"```? Maybe if they're too long it's unhappy - this has happened to me before  

```table(s[[5]]@active.ident)``` - does this give you an output of singlets and doublets?

**Comment by aitoe96** [comment]
When I do the intersect, there are no cells identified as "select" in common

The Barcodes are pretty long (i.e.:  S5818Hippo3_TAGAGATCATAACACAATAA’, ‘S5818Hippo4_GGATGCTCGACTTACATAAA’, ‘S5818Hippo2_TTGCAACTGGTTAAAGGTTC’, ...), but they have the same length in the rest objects and it works for them.  

This: table(s[[5]]@active.ident), give me this output: 

> table(s[[5]]@active.ident)

Doublet Singlet 
    144    4213

**Comment by ollieeknight** [comment]
hmm, alright. is there a way you can upload the object so I could download and take a look?

**Comment by aitoe96** [comment]
https://drive.google.com/file/d/1UQu-EDF1q0zFfniaXfc7PpIZQeX-4mJL/view?usp=share_link

**Comment by ollieeknight** [comment]
alright, the error persists for me too. Could you try something else for doublet finder - use a temporary object to map doublet ID's to, and then move that metadata column over to the original object, like:
```
for (i in 1:length(alldata)){
  print(paste0("Running DoubletFinder on sample ",i,", ",names(alldata[i])))
  doubletdata <- DietSeurat(alldata[[i]]) %>%
    NormalizeData(verbose=F) %>%
    FindVariableFeatures(verbose=F) %>%
    ScaleData(verbose = F) %>%
    RunPCA(npcs = 30, verbose = F)
  nExp <- round((ncol(alldata[[i]]/2000)*100)
  doubletdata <- doubletFinder_v3(doubletdata, PCs = 1:30, pK = 0.09, nExp = nExp)
  doublet.metadata <- colnames(doubletdata@meta.data)[grepl("DF.classification", colnames(doubletdata@meta.data))]
  doubletdata <- SetIdent(doubletdata, value = doublet.metadata)
  alldata[[i]]$doubletfinder_annotation <- doubletdata@active.ident
  alldata[[i]] <- subset(alldata[[i]], doubletfinder_annotation == 'Singlet')
}
```

**Comment by aitoe96** [comment]
Finally I found the issue and solve it, anyway thank you for your help.

The problem was that there was an inconsistency in the gene names between different slots of the object such as counts and metadata. This happened because I changed the gene names after the data was pre-processed and did not change them in all slots, only in the active assay. 

To solve this I have changed the name of the genes when loading the matrices before creating the seurat object, this way the genes have the same name in all the object and there are no inconsistencies in the subsequent analysis. 

Thank you very much for all the help and time you have given me.

**Comment by ElisaRosatiScalchi** [comment]
> selected <- WhichCells(s[[5]], idents = 'Singlet')
> s[[5]] <- subset(s[[5]], cells = selected)

I have the same problem/error here

**Comment by ElisaRosatiScalchi** [comment]
> > > selected <- WhichCells(s[[5]], idents = 'Singlet')
> > > s[[5]] <- subset(s[[5]], cells = selected)
> > 
> > 
> > I have the same problem/error here
> 
> @ElisaRosatiScalchi could you provide the assays, dim() of your object? does the first line work, where you select cells?


The first like works fine indeed. Here is my object:
`> seurat
An object of class Seurat 
21422 features across 13431 samples within 3 assays 
Active assay: RNA (21400 features, 0 variable features)
 2 other assays present: HTO, ADT
> dim(seurat)
[1] 21400 13431`
