### ISSUE TITLE
Multimodal Weighted Nearest Neighbor Analysis

### ISSUE THREAD

**Issue by arnaudmet** [satijalab/seurat#6909]
Hi,
I'm working on very similar samples, and it is hard to visually dissociate these samples, even if these populations are experimentally different. Both samples were sequenced at the same time using HTO.
I was wondering if multimodal WNN can be applied to downstream analysis to dissociate populations to focus on a population that could explain the differences. I did GSEA analysis (escapeGSEA), decoupleR, and SCENIC analysis.
The objective is to use multiple analyses to separate a small population with few differences that could explain the differences observed experimentally

Is it correct to run WNN using all these assays and does it make sense? i plan to run the WNN the same way than with ADT, create PCA for each assay.

```
DefaultAssay(combined)='tfswmean'
combined=ScaleData(combined)
combined=FindVariableFeatures(combined)
combined=RunPCA(combined, reduction.name = 'tpca')
ElbowPlot(combined,reduction = 'tpca')


DefaultAssay(combined)='pathwayswmean'
combined=ScaleData(combined)
combined=FindVariableFeatures(combined) 
combined=RunPCA(combined, reduction.name = 'ppca')
ElbowPlot(combined,reduction = 'ppca')


DefaultAssay(combined)='SCENIC'
combined=ScaleData(combined) 
combined=FindVariableFeatures(combined) 
combined=RunPCA(combined, reduction.name = 'spca')
ElbowPlot(combined,reduction = 'spca')



combined <- FindMultiModalNeighbors(
  combined, reduction.list = list("pca", "tpca",'ppca','spca'), 
  dims.list = list(1:15, 1:10,1:13,1:10), modality.weight.name = "RNA.weight"
)
combined <- RunUMAP(combined, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
combined <- FindClusters(combined, graph.name = "wsnn", algorithm = 3, resolution = 2, verbose = T)
```
thanks for help

**Comment by yuhanH** [comment]
Hi @arnaudmet 
I think your above scripts make sense. You can remove ` modality.weight.name = "RNA.weight` in function `FindMultiModalNeighbors`. `FindMultiModalNeighbors` will provide four modality weight names depending on the assay name that corresponds to the dimensional reduction.
