### ISSUE TITLE
y axis units of VlnPlot

### ISSUE THREAD

**Issue by mooreann** [satijalab/seurat#691]
I cant seem to find this metric anywhere, but does anyone know what units the y axis of the VlnPlots are? I know there's variable to make it log expression, but what's the default?
Thanks in advance.

**Comment by satijalab** [comment]
By default, VlnPlot plots values from the @data slot, which is in log-scale.

**Comment by swvanderlaan** [comment]
Just the regular `r` `log`-scale? I.e. natural log?

**Comment by zenghh1226** [comment]
Does vlnplot denoise the data? I also want to know what is the value of y axis. What is the function of the code below which was captured from the  source of single vlnplot ?
![Uploading image.png…]()
