### ISSUE TITLE
Average expression in FindAllMarker file

### ISSUE THREAD

**Issue by devenderarora** [satijalab/seurat#6910]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/arora172/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal>We are trying to figure out avg_log2FC expression of a
specific gene in cluster based on FindAllMarker file.<o:p></o:p></p>

<p class=MsoNormal>We have a seurat object with a total of 21 clusters and a
total of 50,482 cells. <o:p></o:p></p>

<p class=MsoNormal>In cluster6 with 2056 cells, 1872 cells have more than 0
read counts for a total read count of 9745. Similarly, rest of the clusters
C0-C5 and C7-C20 have total of 48436 cells out of which 44305 cells have more
than 0 reads for a total of 239676 reads.<o:p></o:p></p>

<p class=MsoNormal>The information below id from FinfAllMarkers file:<o:p></o:p></p>

<p class=MsoNormal>Avg_Log2Fc<span style='mso-spacerun:yes'>       
</span>Pct1<span style='mso-spacerun:yes'>       </span>Pct2<span
style='mso-spacerun:yes'>       </span>padj_pvalue<span
style='mso-spacerun:yes'>       </span>cluster<span style='mso-spacerun:yes'> 
</span>gene<o:p></o:p></p>

<p class=MsoNormal>0.644801543<span style='mso-spacerun:yes'>      
</span>0.915<span style='mso-spacerun:yes'>     </span>0.915<span
style='mso-spacerun:yes'>     </span>1.4413E-80<span
style='mso-spacerun:yes'>          </span>6<span
style='mso-spacerun:yes'>              </span>FABP7<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>We are able to calculate pct.1 (1872/2046 = 0.915)` and `
pct.2
(44305/48436=0.915)
`.<o:p></o:p></p>

<p class=MsoNormal>May we know how to calculate the average log2fc for a
specific gene?<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Our second question is:<o:p></o:p></p>

<p class=MsoNormal>We tried to extract the expression value for the respective
gene “FABP7” from seurat object using the function:<o:p></o:p></p>

`gene1<- FetchData(object_seu, vars = "FABP7")`

<p class=MsoNormal>and retrieved the count data from seurat object with:<o:p></o:p></p>

`write.table(as.matrix(GetAssayData(object = object_seu, slot = "counts")), genelist.csv', sep = ',', row.names = T, col.names =T, quote = F)`

<p class=MsoNormal>and grep “FABP7” from the list and got the count for the
same.<o:p></o:p></p>

<p class=MsoNormal><span style='mso-tab-count:2'>                                </span><o:p></o:p></p>

Barcode | Expression | Count
-- | -- | --
AAACCCAAGAATTGTG-1 | 3.069628 | 2
AAACCCAAGCTACAAA-1 | 2.572413 | 8
AAACCCAAGGCAGGGA-1 | 2.234337 | 1
AAACCCAGTGGATCGA-1 | 1.951934 | 1
AAACGAAAGTTACTCG-1 | 1.714471 | 1
AAACGAACAAACTGCT-1 | 2.297628 | 8
AAACGAACAAGCGATG-1 | 1.976302 | 4

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>We would like to know the rationale behind calculating the
Expression value for each gene that was fetched using FetchData function. In
other words, how are the counts used to calculate expression values? <o:p></o:p></p>

<p class=MsoNormal>Thanks for your endless support.<o:p></o:p></p>

</body>

</html>

**Comment by saketkc** [comment]
This is explained in the `FindMarkers` function [documentation](https://satijalab.org/seurat/reference/findmarkers).

```
avg_logFC: log fold-chage of the average expression between the two groups. Positive values indicate that the gene is more highly expressed in the first group

pct.1: The percentage of cells where the gene is detected in the first group

pct.2: The percentage of cells where the gene is detected in the second group

p_val_adj: Adjusted p-value, based on bonferroni correction using all genes in the dataset


```

**Comment by saketkc** [comment]
`log(x = rowMeans(x = expm1(x = data.1)) + pseudocount.use) - log(x = rowMeans(x = expm1(x = data.2)) + pseudocount.use))` where data.1 comes from group1.
