### ISSUE TITLE
Using "scale.data" or "data" slot for SCTtransformed data DE analysis

### ISSUE THREAD

**Issue by ningxinkang** [satijalab/seurat#6912]
Hi,

I'm currently doing scRNA-seq analysis using SCTtransformed data. I did DE analysis on each cluster by calling `FindMarkers()`(using "MAST" test). I tried using both "scale.data" and "data" as input, with other parameters staying the same, but it turns out that there are more DEGs found using the slot "scale.data". I'm wondering which slot you would suggest using in this case. I read from this [page](https://satijalab.org/seurat/articles/sctransform_vignette.html) that it is most optimal to do downstream calculations using residuals, but I want to make sure if it is the same case here when using "MAST" test. I'm also wondering why I get more DEGs using "scale.data" slot. Thank you!!

**Comment by saketkc** [comment]
`scale.data` slot of SCT assay contains pearson residuals while `data` slot contains `log1p(corrected counts)`. I would recommend using either the `counts` or the `data` slot for DE (using a GLM or wiloxon test). Please see the [updated vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) for details.

**Comment by rmc0106** [comment]
Hi, @saketkc what if I need to find DE genes between my ctrl and stim conditions but they do not integration?

**Comment by saketkc** [comment]
@rmc0106 not sure I understand your question. You can always run DE between two datasets (irrespective of whether they integrate or not).

**Comment by rmc0106** [comment]
@saketkc  sorry that I was not clear. More details of my question can be found here: https://github.com/satijalab/seurat/issues/7258#issuecomment-1531356522     #7258
