### ISSUE TITLE
RunPCA for ADT data: Error in prcomp.default(x = t(object), rank. = npcs, ...) :    as.integer(rank.) > 0 is not TRUE

### ISSUE THREAD

**Issue by LixinyuLiu** [satijalab/seurat#6919]
Hi Seurat Team, 

I am integrating multiple samples using Cite-Seq with RNA and ADT (6 ab). I am using the RPCA integration pipeline suggested for ADT data. However, when I was performing the RunPCA step for ADT. I have encountered an error. The following is my code, data, and error report. Could you please help me resolve this problem? Thank you in advance. 

Best regards, 
E

#Code
for (i in 1:length(adtlist)){
  DefaultAssay(adtlist[[i]]) <- 'ADT'
  
  VariableFeatures(adtlist[[i]]) <- rownames(adtlist[[i]][["ADT"]])
  adtlist[[i]] <- NormalizeData(adtlist[[i]], 
                                normalization.method = 'CLR', margin = 2)  
}

features.adt <- SelectIntegrationFeatures(object.list = adtlist)

adtlist <- lapply(X = adtlist, FUN = function(x) {
  x <- ScaleData(x, features = features.adt, verbose = FALSE)
  x <- RunPCA(x,reduction.name = 'apca', features = features.adt, 
              verbose = FALSE, approx=FALSE)
})

#Here is the error report: 
**Error in prcomp.default(x = t(object), rank. = npcs, ...) : 
  as.integer(rank.) > 0 is not TRUE**
In addition: Warning message:
In PrepDR(object = object, features = features, verbose = verbose) :
  The following 6 features requested have zero variance (running reduction without them): CD41-TotalseqA, CD201-TotalseqA, CD48-TotalseqA, CD150-TotalseqA, CD135-TotalseqA, CD27-TotalseqA

#Here is my data: 
An object of class Seurat 
16796 features across 4830 samples within 2 assays 
Active assay: ADT (6 features, 6 variable features)
 1 other assay present: RNA

**Comment by LixinyuLiu** [comment]
> packageVersion("Seurat") 
[1] ‘4.3.0’

**Comment by yuhanH** [comment]
From the error, it seems that ADT expression in some objects from `adtlist`  have no variance.
Could you show the variance of ADT for all individual objects in `adtlist`?

**Comment by LixinyuLiu** [comment]
Hello, 
Thank you for the reply. 0 variance is shown in a few objects. In that case, Can I still do the integration?
 var(adtlist[[1]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0              0               0               0              0
CD201-TotalseqA              0               0              0               0               0              0
CD48-TotalseqA               0               0              0               0               0              0
CD150-TotalseqA              0               0              0               0               0              0
CD135-TotalseqA              0               0              0               0               0              0
CD27-TotalseqA               0               0              0               0               0              0
> var(adtlist[[2]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0              0    0.000000e+00    0.000000e+00              0
CD201-TotalseqA              0               0              0    0.000000e+00    0.000000e+00              0
CD48-TotalseqA               0               0              0    0.000000e+00    0.000000e+00              0
CD150-TotalseqA              0               0              0    1.403115e-04   -1.969008e-08              0
CD135-TotalseqA              0               0              0   -1.969008e-08    1.403115e-04              0
CD27-TotalseqA               0               0              0    0.000000e+00    0.000000e+00              0
> var(adtlist[[3]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0   0.000000e+00    0.000000e+00               0   0.000000e+00
CD201-TotalseqA              0               0   0.000000e+00    0.000000e+00               0   0.000000e+00
CD48-TotalseqA               0               0   1.008980e-04   -2.036286e-08               0  -2.036286e-08
CD150-TotalseqA              0               0  -2.036286e-08    2.017756e-04               0  -4.072573e-08
CD135-TotalseqA              0               0   0.000000e+00    0.000000e+00               0   0.000000e+00
CD27-TotalseqA               0               0  -2.036286e-08   -4.072573e-08               0   2.017756e-04
> var(adtlist[[4]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0              0               0               0              0
CD201-TotalseqA              0               0              0               0               0              0
CD48-TotalseqA               0               0              0               0               0              0
CD150-TotalseqA              0               0              0               0               0              0
CD135-TotalseqA              0               0              0               0               0              0
CD27-TotalseqA               0               0              0               0               0              0
> var(adtlist[[5]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0              0               0               0              0
CD201-TotalseqA              0               0              0               0               0              0
CD48-TotalseqA               0               0              0               0               0              0
CD150-TotalseqA              0               0              0               0               0              0
CD135-TotalseqA              0               0              0               0               0              0
CD27-TotalseqA               0               0              0               0               0              0
> var(adtlist[[6]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0              0               0               0              0
CD201-TotalseqA              0               0              0               0               0              0
CD48-TotalseqA               0               0              0               0               0              0
CD150-TotalseqA              0               0              0               0               0              0
CD135-TotalseqA              0               0              0               0               0              0
CD27-TotalseqA               0               0              0               0               0              0
> var(adtlist[[7]]@assays$ADT@counts  %>% as.matrix()%>% t())
                CD41-TotalseqA CD201-TotalseqA CD48-TotalseqA CD150-TotalseqA CD135-TotalseqA CD27-TotalseqA
CD41-TotalseqA               0               0              0    0.0000000000               0              0
CD201-TotalseqA              0               0              0    0.0000000000               0              0
CD48-TotalseqA               0               0              0    0.0000000000               0              0
CD150-TotalseqA              0               0              0    0.0001145344               0              0
CD135-TotalseqA              0               0              0    0.0000000000               0              0
CD27-TotalseqA               0               0              0    0.0000000000               0              0

Best regads, 
E

**Comment by yuhanH** [comment]
It seems that there are some samples having no ADT variance. To perform PCA analysis, the sample needs to have variance for the input features. 
Also, you can use the below code to calculate feature variance
```
apply(X = pbmc_small[['RNA']]@counts, MARGIN = 1, FUN = var )
```
