### ISSUE TITLE
how to cluster rare non-overlapping cells

### ISSUE THREAD

**Issue by guoyanzhao** [satijalab/seurat#692]
Hi,

I am working on comparing data from wild type and knock out mice to identify a specific cell type. Some how the data was biased with very few of the cells of interest (~ 2-3%) based on marker genes. There are ~1% of the cell that could not be aligned between WT and KO. Most of those cells express the marker gene of interest and potentially are the cells of biological significance.  I have two issues. First in current analysis the cells does not cluster. Second in your tutorial those rare unaligned cells were discarded whereas I would like to include those cells in the downstream analysis and hopefully they cluster together.  Could you please share your thoughts on what I can do in this situation?

Thank you very much!
Guoyan

**Comment by satijalab** [comment]
While we provide the option of removing non-overlapping populations, it is certainly not required. You can skip the SubsetData step to remove these cells and continue with clustering.

However, ensuring that non-overlapping populations are not blended during an integrated analysis remains a challenge for Seurat and all alignment/batch correction methods. We look forward to releasing new methods in the future to improve on this challenge.

**Comment by guoyanzhao** [comment]
Thank you for your explanation!

Since this is a comparison between WT and KO we would expect  cells do not align if the gene KO affects the transcriptome significantly. I found out later that those unaligned cells mainly distributed into two clusters. One of the cluster expresses the expected cell markers.
