### ISSUE TITLE
After SCTransform v2: Are counts corrected for sequencing depth only or for sequencing depth and confounding variables

### ISSUE THREAD

**Issue by aghr** [satijalab/seurat#6921]
Could you please clarify if counts in seo$SCT@counts after SCTransform v2 (Seurat 4) are:

1. corrected for sequencing depth per cell only
    - eg.. as stated here https://github.com/satijalab/seurat/issues/3923
2. or if they are corrected (normalized) for sequencing depth per cell and confounding variables considered via argument vars.to.regress when running SCTransform?
    - eg. as stated in section [Where are normalized values stored for sctransform?](https://satijalab.org/seurat/articles/sctransform_vignette.html): "To assist with visualization and interpretation. we also convert Pearson residuals back to ‘corrected’ UMI counts."

Why am I confused?
I ran SCTransfrom twice on the same input once with vars.to.regress=NULL giving Seurat object seo1 and a second time with vars.to.regress='pct_mito' giving Seurat object seo2. The values in 'pct_mito' vary across cells, of course.'The Pearson residuals in seo1 and seo2 are different, as expected. The count matrix and data matrix of seo1 and seo2 are exactly the same. I interpret this such that SCTransform normalizes counts and data to the sequencing depth only even when running SCTrnsform with vars.to.regress=pct_mito'. But this would contradict the fact that counts are corrected by converting back Pearson residuals as these are different in seo1 vs seo2.

Is is possible to get counts corrected for sequencing depth and confounding variables from a Seurat object after SCTransfrom was run where confounding variables to be corrected for were given via argument vars.to.regress?

Many thanks.

**Comment by saketkc** [comment]
Hi @aghr,

> corrected for sequencing depth per cell only

This is correct. 

`vars.to.regress` will regress out the covariate from the pearson residuals (`scale.data` slot) and not the counts (or the corrected counts, i.e. `data` slot. You could adjust for the confusing variables when doing DE (using the `data` or `counts` slot) using a GLM based test (such as MAST or `test.use="LR"` in `FindMarkers`) Hope this helps! Feel free to reopen with any follow up questions.
