### ISSUE TITLE
Topn markers for individual cluster

### ISSUE THREAD

**Issue by azwainCC** [satijalab/seurat#6925]
Hello
Is there a way to get  dot plot with topn markers for an individual cluster specifically?
Thanks in advance,
Azwa

**Comment by mhkowalski** [comment]
Hi- to do this you should run FindMarkers to obtain markers for your cluster of interest. Then you can provide a vector of those genes to the dotplot function, as in `DotPlot(object, features = your.markers)` Please see the `DotPlot` documentation for more details.
