### ISSUE TITLE
Conversion between Seurat and SingleCellExperiment results in rowData names (0) in SingleCellExperiment object

### ISSUE THREAD

**Issue by genomics-geek** [satijalab/seurat#6926]
Hi,

I have a question about conversion of a Seurat object to SingleCellExperiment.  We have a process that exports rowData from SingleCellExperiment objects and was hoping to keep it simple by just converting to SingleCellExperiment and then run the same exports. However, I noticed after conversion from Seurat to SingleCellExperiment, rowData is always (0). Is this expected? How can one export similar information from Seurat?  Everything else works perfectly!  I was just hoping I could export rowData.

Package info:
SingleCellExperiment_1.20.0
SeuratObject_4.1.3 
Seurat_4.3.0    

Example code:

```R
suppressPackageStartupMessages(library(Seurat))

args <- commandArgs(trailingOnly = TRUE)
inputfile <- args[1]

rds_object <- readRDS(inputfile)
rds_sce_object <- as.SingleCellExperiment(rds_object)

> rds_sce_object
class: SingleCellExperiment 
dim: 13714 2700 
metadata(0):
assays(2): counts logcounts
rownames(13714): AL627309.1 AP006222.2 ... PNRC2.1 SRSF10.1
rowData names(0):
colnames(2700): AAACATACAACCAC AAACATTGAGCTAC ... TTTGCATGAGAGGC
  TTTGCATGCCTCAC
colData names(6): orig.ident nCount_RNA ... Barcode ident
reducedDimNames(2): PCA UMAP
mainExpName: RNA
altExpNames(0):
```

Here is how I usually export the rowData

```R
suppressPackageStartupMessages(library(SingleCellExperiment))
library(tools)

gene_metadata<-data.frame(rowData(rds_sce_object))
write.csv(gene_metadata, "rowdata.csv", row.names = FALSE, quote = FALSE)
```

Is there an equivalent in Seurat if the conversion won't handle rowData? 

Thanks in advance!

**Comment by yuhanH** [comment]
hi, 
You have a try on this package, `sceasy` https://github.com/cellgeni/sceasy which can convert different single-cell data formats. You can convert seurat object to SingleCellExperiment object.
