### ISSUE TITLE
Cell proportion differences

### ISSUE THREAD

**Issue by azwainCC** [satijalab/seurat#6927]
Hello
I am finding Cell proportion differences in the clusters between the plots
 1. integration/seurat_clusters
2.integration/active.ident
though I have not made any changes before labelling (merging)
Is there anything else that contributes to cell number differences between clustering and changing cell identities?
Thanks in advance,
Azwa

**Comment by saketkc** [comment]
Not sure I understand the question.  Can you elaborate what is it that you are trying to do?

**Comment by mhkowalski** [comment]
Closing because of no response, please open again if you need additional assistance.
