### ISSUE TITLE
Problem on project qurey on reference UMAP 

### ISSUE THREAD

**Issue by intawat** [satijalab/seurat#6928]
I posted the question on Azimuth ad below but there , seem to have less attenuation I would to repost the problem here again. 
https://github.com/satijalab/azimuth/issues/134

I made my own reference map using Azimuth. Then use it for TransferData function, the results is very good as I expected. However, I have problem to visualize the result on reference Umap. I follow the code from an issue https://github.com/satijalab/azimuth/issues/77. RF =my reference map.

Calculate the query neighbors in the reference with respect to the integrated embeddings.
query[["query_ref.nn"]] <- FindNeighbors(
object = Embeddings(RF[["refDR"]]),
query = Embeddings(query[["integrated_dr"]]),
return.neighbor = TRUE,
l2.norm = TRUE )

The reference used in the app is downsampled compared to the reference on which the UMAP model was computed. This step, using the helper function NNTransform, corrects the Neighbors to account for the downsampling.
query <- Azimuth:::NNTransform(
object = query,
meta.data = RF[[]]
)

Project the query to the reference UMAP.
query[["proj.umap"]] <- RunUMAP(
object = query[["query_ref.nn"]],
reduction.model = RF[["refUMAP"]],
reduction.key = 'UMAP_'
)

DimPlot(object = query, reduction = "proj.umap",label = TRUE) + NoLegend()

Then project map is not nice as below

<img width="502" alt="Screen Shot 2023-02-02 at 7 00 17 AM" src="https://user-images.githubusercontent.com/7950494/216821520-e88f23fd-2106-4064-b2c6-8617971d13d4.png">

the REF map is below

<img width="479" alt="Screen Shot 2023-02-02 at 7 00 24 AM" src="https://user-images.githubusercontent.com/7950494/216821536-febb12a4-e15e-4a6d-b5ed-0f994d0b6eaf.png">

Please help

**Comment by Gesmira** [comment]
Hi, 
Happy to try to help! Is the code you included the only code you ran after `TransferData`? I'm assuming you also run `IntegrateEmbeddings()` to get the "integrated_dr" in the query?

Can you include all of your code to map the query or be able to send a reproducible example over email? In the meantime, you can also try running[ `RunAzimuth` from the Azimuth package](https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html) to ensure all the same steps are being run and compare your results. 
Thanks!

**Comment by intawat** [comment]
Dear Satijalab/Seurat,

Thank you very much. I am looking forward to fix the problem.

I performed data integration using CCA method but I didnt use SCTransform
on the reference so I ran sct transform first as Azimuth needs for build
reference.

dat.integrated <-  SCTransform(dat.integrated, vst.flavor = "v2",verbose =
T)

RF <- AzimuthReference(
  dat.integrated,
  refUMAP = "umap",
  refDR = "pca",
  refAssay = "SCT",
  dims = 1:50,
  k.param = 31,
  plotref = "umap",
  plot.metadata = NULL,
  ori.index = NULL,
  colormap = NULL,
  assays = NULL,
  metadata = "cl_names",
  reference.version = "1.0.0",
  verbose = TRUE
)

#############################

Then I prepare query data using  reference.SCT.model,  FindTransferAnchors
and Transferdata. The result is very good to predict the cell type base on
reference cluster

###
query <- SCTransform(
  object = panel[["OB_Veh"]] ,
  assay = "RNA",
 new.assay.name = "refAssay",
residual.features = rownames(x = RF),
 reference.SCT.model = ***@***.***$refmodel,
  vst.flavor = "v2",
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
 do.scale = FALSE,
  do.center = TRUE)

 anchors <- FindTransferAnchors(
  reference = RF,
   query =  query,
   k.filter = NA,
   reference.neighbors = "refdr.annoy.neighbors",
   reference.assay = "refAssay",
   query.assay = "refAssay",
   reference.reduction = "refDR",
   normalization.method = "SCT",
   features = intersect(rownames(x = RF), VariableFeatures(object = query)),
   dims = 1:50,
   n.trees = 20,
   mapping.score.k = 100
 )

 query <- TransferData(
   reference = RF,
   query = query,
   dims = 1:50,
   anchorset = anchors,
   refdata = RF$cl_names,
   store.weights = TRUE, n.trees = 1000
 )

###########################

The projection of a query code is on the attachment pdf of jupyter notebook.

With the best regards,
Intawat

**Comment by Gesmira** [comment]
Hi Intawat, 
Thanks! I didn't get the pdf attachment, would you be able to send it to [gmolla@nygenome.org](gmolla@nygenome.org) ?

Also did you try running [`RunAzimuth` from the Azimuth package](https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html)? I want to check if it's an issue with your query/reference themselves or perhaps an issue with the way you are calling the projection functions. 

You can do this test your azimuth reference directly with the following code:

``` 
# Using the reference you generated before
# RF <- AzimuthReference(....)
# Make folder to store reference data in: "path_to_reference"
saveRDS(object = RF, file =  "~/path_to_reference/ref.Rds", compress=F)
SaveAnnoyIndex(object = RF[["refdr.annoy.neighbors"]], file = "~/path_to_reference/idx.annoy")

# Then run azimuth with path to reference 
query <- RunAzimuth(query, reference =  "~/path_to_reference")
# And visualize projected umap on query
DimPlot(query, reduction = ref.umap, label = T)
```

If the results of this look good, that means the projection is working and you may have to troubleshoot your script to make the results in line with `RunAzimuth` or just use the code above instead. If not, we can debug further.

**Comment by intawat** [comment]
Got error right the way when call

Error in SaveAnnoyIndex(object = RF[["refdr.annoy.neighbors"]], file =
"refAz/idx.annoy"): Index for provided Neighbor object is NULL
Traceback:

1. SaveAnnoyIndex(object = RF[["refdr.annoy.neighbors"]], file =
"refAz/idx.annoy")
2. stop("Index for provided Neighbor object is NULL")


However when I run FindTransferAnchors as below that contain
reference.neighbors = "refdr.annoy.neighbors" . Itworks and get good
results in prediction.


anchors.veh1 <- FindTransferAnchors(
  reference = RF,
   query = query.veh1,
   k.filter = NA,
   reference.neighbors = "refdr.annoy.neighbors",
   reference.assay = "refAssay",
   query.assay = "refAssay",
   reference.reduction = "refDR",
   normalization.method = "SCT",
   features = intersect(rownames(x = RF), VariableFeatures(object =
query.veh1)),
   dims = 1:50,
   n.trees = 20,
   mapping.score.k = 100
 )

**Comment by Gesmira** [comment]
For some reason the index has not been stored for the neighbors in your Azimuth reference so it will not let you save the annoy index. This is odd because when you run `AzimuthReference` it calls `FindNeighbors` with parameters `cache.index = T` and `return.neighbor = T` so the index should be present.  

I'm assuming if you run `reference[["refdr.annoy.neighbors"]]@alg.idx` it returns nothing? Can you try rerunning `AzimuthReference()` on your integrated object in case it has been edited since making it and let me know if the index is stored. Something may have gone wrong with your neighbors slot in the reference, leading to issues with the projection.

**Comment by intawat** [comment]
When I run : ***@***.***,  got error below.  I
will try to rerun AzimuthReference() and get back to you. Thank you.

ERROR while rich displaying an object: Error in sprintf("C++ object
<%s> of class '%s' <%s>", externalptr_address(pointer), : external
pointer is not valid

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
6. repr::mime2repr[[mime]](obj)
7. repr_text.default(obj)
8. paste(capture.output(print(obj)), collapse = "\n")
9. capture.output(print(obj))
10. withVisible(...elt(i))
11. print(obj)
12. print.default(obj)
13. (new("standardGeneric", .Data = function (object)
  . standardGeneric("show"), generic = structure("show", package = "methods"),
  .     package = "methods", group = list(), valueClass = character(0),
  .     signature = structure("object", simpleOnly = TRUE), default =
new("derivedDefaultMethod",
  .         .Data = function (object)
  .         showDefault(object), target = new("signature", .Data = "ANY",
  .             names = "object", package = "methods"), defined =
new("signature",
  .             .Data = "ANY", names = "object", package = "methods"),
  .         generic = structure("show", package = "methods")),
skeleton = (new("derivedDefaultMethod",
  .         .Data = function (object)
  .         showDefault(object), target = new("signature", .Data = "ANY",
  .             names = "object", package = "methods"), defined =
new("signature",
  .             .Data = "ANY", names = "object", package = "methods"),
  .         generic = structure("show", package =
"methods")))(object)))(new("Rcpp_AnnoyAngular",
  .     .xData = <environment>))
14. (new("standardGeneric", .Data = function (object)
  . standardGeneric("show"), generic = structure("show", package = "methods"),
  .     package = "methods", group = list(), valueClass = character(0),
  .     signature = structure("object", simpleOnly = TRUE), default =
new("derivedDefaultMethod",
  .         .Data = function (object)
  .         showDefault(object), target = new("signature", .Data = "ANY",
  .             names = "object", package = "methods"), defined =
new("signature",
  .             .Data = "ANY", names = "object", package = "methods"),
  .         generic = structure("show", package = "methods")),
skeleton = (new("derivedDefaultMethod",
  .         .Data = function (object)
  .         showDefault(object), target = new("signature", .Data = "ANY",
  .             names = "object", package = "methods"), defined =
new("signature",
  .             .Data = "ANY", names = "object", package = "methods"),
  .         generic = structure("show", package =
"methods")))(object)))(new("Rcpp_AnnoyAngular",
  .     .xData = <environment>))
15. sprintf("C++ object <%s> of class '%s' <%s>", externalptr_address(pointer),
  .     .Call(Class__name, cppclass), externalptr_address(cppclass))

**Comment by intawat** [comment]
## I reran AzimuthReference and now I have idx

***@***.***

C++ object <0x564484ce4ea0> of class 'AnnoyAngular' <0x56446c1f89f0>


##Then I saved reference , now it is good


saveRDS(object = RF, file =  "refAz/ref.Rds", compress=F)
SaveAnnoyIndex(object = RF[["refdr.annoy.neighbors"]], file = "refAz/idx.annoy")


##When I use RunAzimuth , create another error below. I think the
function tried to connect online to get homolog.table ??


query <- RunAzimuth(query.dmab1, reference =
"/storage/Intawat/sc_RNAseq/FINAL/refAz")


Error in curl::curl_fetch_memory(url, handle = handle): Timeout was
reached: [seurat.nygenome.org] Connection timeout after 10001 ms
Traceback:

1. RunAzimuth(query.dmab1, reference = "/storage/Intawat/sc_RNAseq/FINAL/refAz")
2. RunAzimuth.Seurat(query.dmab1, reference =
"/storage/Intawat/sc_RNAseq/FINAL/refAz")
3. ConvertGeneNames(object = query, reference.names = rownames(x = reference),
 .     homolog.table =
"https://seurat.nygenome.org/azimuth/references/homologs.rds")
4. Online(url = homolog.table)
5. comp(x = httr::status_code(x = httr::GET(url = url,
httr::timeout(seconds = getOption("timeout")))),
 .     y = code)
6. f(...)
7. httr::status_code(x = httr::GET(url = url, httr::timeout(seconds =
getOption("timeout"))))
8. httr::GET(url = url, httr::timeout(seconds = getOption("timeout")))
9. request_perform(req, hu$handle$handle)
10. request_fetch(req$output, req$url, handle)
11. request_fetch.write_memory(req$output, req$url, handle)
12. curl::curl_fetch_memory(url, handle = handle)

[*]:

**Comment by Gesmira** [comment]
Do you have an internet connection where you are running R? If not, the call to seurat.nygenome.org will fail. However, you can download the file [here](https://seurat.nygenome.org/azimuth/references/homologs.rds) and edit the RunAzimuth function to include `homolog.table = "~/path_to_table/homologs.rds"` instead of the url [here](https://github.com/satijalab/azimuth/blob/fa45d4c153d2623b89792f8b57aab333e889cdab/R/azimuth.R#L78). 
You can either use `trace("RunAzimuth.Seurat", edit = T, where = RunAzimuth)` to edit the function or simply copy [the function](https://github.com/satijalab/azimuth/blob/fa45d4c153d2623b89792f8b57aab333e889cdab/R/azimuth.R#L22), change that line in `ConvertGeneNames()`, then rerun the function. Let me know if this makes sense.

**Comment by intawat** [comment]
I got the same results from the UMAP plot. Please see the attached file
from chunk 93.

//Intawat

**Comment by Gesmira** [comment]
Hi, I am unable to see the attached file as email attachments are not included in github comments.  Can you send to [gmolla@nygenome.org](gmolla@nygenome.org)? 

In addition if you can send the query and reference objects, before running azimuth functions, that would be very useful to help with figuring out what may have occured with their initial construction, thanks!

**Comment by intawat** [comment]
Just sent you the notebook and link to load the reference and query.

Thank you.

**Comment by Gesmira** [comment]
Hi, 
Upon looking at your reference object, it seems that you have computed the umap reduction using 740 neighbors. We generally recommend a much smaller number, as too large of value will not represent the local structure of your data well. 

Furthermore, Azimuth uses the default value for `k` (20) in finding the neighbors when projecting the UMAP, so the number of neighbors found between the query and reference will be very different from the number of neighbors within the reference itself, leading to issues with the UMAP projection. If you perform MapQuery instead of RunAzimuth, the UMAP will improve slightly as `k` becomes the number of neighbors of the reference model, however the local structure in the UMAP will still look poor.   

I would recommend rerunning RunUMAP() for your reference (before running AzimuthReference) using the default number of neighbors. If you feel strongly about changing this, you can, but we recommend staying between 5 and 50 neighbors. 

Then upon rerunning AzimuthReferenence() and RunAzimuth(), the results should improve. When I tried just recomputing the umap model with the default parameters on the Azimuth reference you shared with me, the results improve significantly.

**Comment by michael-kotliar** [comment]
> For some reason the index has not been stored for the neighbors in your Azimuth reference so it will not let you save the annoy index. This is odd because when you run `AzimuthReference` it calls `FindNeighbors` with parameters `cache.index = T` and `return.neighbor = T` so the index should be present.
> 
> I'm assuming if you run `reference[["refdr.annoy.neighbors"]]@alg.idx` it returns nothing? Can you try rerunning `AzimuthReference()` on your integrated object in case it has been edited since making it and let me know if the index is stored. Something may have gone wrong with your neighbors slot in the reference, leading to issues with the projection.

I believe, the `graph.name` should be a vector - one name for nn, another for snn.
