### ISSUE TITLE
Importing .txt.gz files from GEO to generate Seurat objects

### ISSUE THREAD

**Issue by mdeg89** [satijalab/seurat#6930]
Hi,

I don't have much experience with Seurat and scrRNAseq. I usually have no problems when using Read10X function, however,
one of the biggest obstacle for me is importing data from GEO (often .txt) to create a new Seurat object. 

Example dataset# 1: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE182001
In this case, the .txt file is different from the norm, where cells are on different columns. When trying to import data with Read.table/Read.csv this then generates a Seurat object with weird number of features e/o samples.

Example dataset#2: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137540

Error examples:
_**trial.data <- read.table("/Users/marcodegiovanni/Downloads/GSE182001_RAW/GSM5515944_Stomach.st.txt")
Error in read.table("/Users/marcodegiovanni/Downloads/GSE182001_RAW/GSM5515944_Stomach.st.txt") : 
  duplicate 'row.names' are not allowed**_

In some other attemtps I have tried to use:
"raw.data<- data.table::fread("/Users/marcodegiovanni/Downloads/xxxx.txt", data.table = F)"
which allows me to often create a Seurat object, but which than lead to the following errors:

Warning message: In matrix(data = as.numeric(x = x), ncol = nc) : NAs introduced by coercion

**Error in validityMethod(as(object, superClass)) :
object 'CsparseMatrix_validate' not found** 

Can somebody let me know how to modify the Read.csv/table functions in orther to convert these kind of .txt files into Seurat objects?

**Comment by saketkc** [comment]
You can use the following code to read these files:

```
library(dplyr)
library(magrittr)
library(data.table)


df <- fread("GSE182001_RAW/GSM5515944_Stomach.st.txt.gz")
df2 <- df[, c("Cell_Index", "Gene", "RSEC_Adjusted_Molecules")]
counts <- df2 %>% pivot_wider(values_from = "RSEC_Adjusted_Molecules", names_from = "Cell_Index", values_fill = 0) %>% as.data.frame()
rownames(counts) <- counts$Gene
counts$Gene <- NULL
obj <- CreateSeuratObject(counts=counts)

```
