### ISSUE TITLE
Integrating a complex spatial RNA experiment

### ISSUE THREAD

**Issue by Dillon214** [satijalab/seurat#6937]
Hello Seurat team,

I am analyzing a spatialRNA (Visium) dataset with a complex design, the major experimental factors being timepoint, disease vs control, tissue, and 3D section (of the given tissue). For example, one slice of tissue may be tissue A, diseased, timepoint 2, 3D section 3. 

I am interested in integrating the dataset with the goal of identifying shared biology, namely shared regions within each tissue, and the proceeding to test for differences caused by this disease over time, however I am confused about how to accomplish this. I know how to integrate data over one condition (such as disease vs control, tech A vs tech B), but I'm unsure how to approach this complicated experiment. 

Do you have any advice about how to accomplish this goal, or if it is even feasible? Due to the large size of the dataset I'm working with, I think that referecne-based integration is likely necessary, but I'm stumped as to how I ought to split my data, normalize (sctransform?), and choose references. 

Any help would be appreciated, and thank you very much for developing this amazing tool. Also, one issue I found to be partially related was #2468

**Comment by AustinHartman** [comment]
Reference mapping may make sense here to initially identify shared cell types across experiments and conditions if a sufficient reference dataset is available. I think the question of how to integrate across multiple questions is dependent on what questions you're asking. For instance, if you'd like to explore changes across time points, then it probably makes sense to integrate data from each time point separately. Hope this helps!
