### ISSUE TITLE
How to account for differences in cell numbers sequenced in different conditions?

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#6939]
Hi, I have samples belonging to Condition A, B and C. I see ~7X more cell number in condition A (even after getting rid of doublets, mitochondrial genes and dead cells) after sequencing compared to condition B and C (same filters used for these 2 as "condition A"). I have 3 questions:
1. Is there a way I can further lower the cell number just in condition A (during pre-processing/normalization steps) so that the UMAP plot looks similar (in terms of cell numbers/cell populations/cluster size) to condition B and C UMAP plots? 
2. Is it acceptable to use more stringent filtering procedures for 1 sample and lenient filtering procedures for other 2, and then integrating them after QC for analysis?
3. If not, how do I know that the differences in gene expression (DEG lists/differences in dot plots) is not because of excess cells sequenced in condition A vs conditions B and C and it really is in fact a meaningful, biologically explainable result? 
PS: I'm not a bioinformatician so I only get the integrated RDS file from our bioinformatics specialist and I'm not really aware of what kind of normalization steps they incorporate, but can ask and provide the details if needed.
Would appreciate any help with this issue. Thank you!

**Comment by nikita421** [comment]
![Inkedcontrol kc ksc individual split SeuratV4 UMAP](https://user-images.githubusercontent.com/75581151/217642916-5ee9091a-d36c-42f2-9fda-7213b33d4073.jpg)

Attaching the UMAP plot incase, this helps explain the case better.

**Comment by saketkc** [comment]
> Is there a way I can further lower the cell number just in condition A (during pre-processing/normalization steps) so that the UMAP plot looks similar (in terms of cell numbers/cell populations/cluster size) to condition B and C UMAP plots?

Yes, but I am not sure you would want to do that just to improve the representation on the UMAP. You can do `subset` command in Seurat to subset an object but what you want to achieve here is not possible using this command alone.


> Is it acceptable to use more stringent filtering procedures for 1 sample and lenient filtering procedures for other 2, and then integrating them after QC for analysis?

Ideally, you want to keep the filtering criteria same throughout unless the samples also had a different chemistry (or any other known source of variation).

> If not, how do I know that the differences in gene expression (DEG lists/differences in dot plots) is not because of excess cells sequenced in condition A vs conditions B and C and it really is in fact a meaningful, biologically explainable result?

Assuming you are doing across the same celltype between conditions, and If you used the Wilcoxon-signed-rank-sum test (default in `FindMarkers'), it is fair to assume the difference is biological. The test is suitable for groups of different size (where the group sizes correspond to cells in condition A and B within a celltype).

**Comment by saketkc** [comment]
You can use [milo](https://github.com/MarioniLab/miloR) for differential abundance tests.
