### ISSUE TITLE
Bias in AverageExpression heatmap because of difference in cell numbers.

### ISSUE THREAD

**Issue by Amygator** [satijalab/seurat#6940]
I have a dataset that contains KO and WT cells within the same sample, as the animals were mixed. I have already created a subset containing only my cells of interest but I would like to analyze the impact my KO has on the subclusters I have calculated in the subset. I created a new metadata slot called "Group" that contains information on Genotype and Cluster. I then used FindMarker to find differences between both genotypes within one Cluster. 
Unfortunately, there is much fewer WT cells compared to KO cells in the dataset. Therefore the heatmaps don't look really good, as the single cells are not evenly distributed. I then decided to use AverageExpression to create a heatmap with average values. But for some reason it gives all the genes in the KO samples a value close to 0 and on the WT side higher/lower values. This technically shows the correct genetic relations, but just doesn't look right. I guess it might be due to the extreme differences in cell numbers but I was hoping that there is a solution. I just can not figure out what it is. 
Maybe I have also done something wrong with the Scaling at any point. 

I would be incredibly grateful for any advice. 

Best,
Amelie

```
# Creating a list of all the cells in Cluster 0
Idents(AggCOI) <- "Group"
COI0 <- WhichCells(AggCOI, idents = c("CD45.2-0", "CD45.1-0"))

# Finding Markers based on Genotype (CD45.1 or CD45.2) within cluster 0
AggCOI.GT0markers <-FindMarkers(AggCOI, ident.1 = "CD45.2-0", ident.2 = "CD45.1-0", group.by = "Group")

# Making a list of the top genes to continue (I am aware that this is probably not the right way to do this but it worked)
COIGT0.genes <- AggCOI.GT0markers  %>% top_n(n = 60, wt = avg_log2FC) 
COIGT0.WTgenes <- AggCOI.GT0markers  %>% top_n(n = -60, wt = avg_log2FC)
COIGT0.genes <- rbind(COIGT0.genes, COIGT0.WTgenes)


# Calculating Average Expression within each Group
COI.averages <- AverageExpression(AggCOI, return.seurat = T, group.by = "Group")


# Making the Heatmap based on the DEG in cluster 0 using Average expression data
DoHeatmap(COI.averages, 
features = rownames(COIGT0.genes), 
label=F, 
cells = c("CD45.1-0", "CD45.2-0"), 
draw.lines = F, 
group.colors = c("black", "blue"), 
group.bar = T) 
+  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n =5, name = "RdYlBu")))

```

![Heatmap](https://user-images.githubusercontent.com/64131050/217843931-ccfa21d0-87e0-4b8e-ae8b-4c06829a574c.jpg)

**Comment by longmanz** [comment]
Hi, 
In your original seurat object (not the pseudo-bulk one), have you check the nCount_RNA and nFeature_RNA between the KO and WT cells? Is there a big difference between them? 

AverageExpression() should not be affected by the number of cells in general. How many KO and WT cells do you have in your dataset, respectively?

**Comment by Amygator** [comment]
Hi,
Thank you for your reply. I checked nCount and nFeature distribution using a FeatureScatter Plot. It actually looks a little biased to me. Although those cells come from the same mice and have been prepared within the same samples, as they were mixed animals.  So I'm not really sure where this is coming from, as it can't be a preparation issue. 

I defined the genotype via my feature barcoding data with rather strict limitations, so i have a few NA cells, but within my cells of interest seurat object I get this distribution:
```
> table(Idents(AggCOI))

CD45.2 CD45.1 
  3209    114

```
As I said, it is unfortunately very different. 

I know this is more a sequencing analysis than a Seurat question, but do you think the result of FindMarker will  be influenced by this, other than the visualization? So will it still give me the correct differentially expressed genes?
Any advice would be greatly appreciated. 

Thank You very much!


Best,
Amelie

![image](https://user-images.githubusercontent.com/64131050/218435953-230bfa34-93de-4c12-bed2-6ebe73538d81.png)

**Comment by Amygator** [comment]
Hi,
Thanks again.

1.  Yes the UMAP and tSNE look okay. I do have unequal distribution of WT and KO cells over the clusters, but I was expecting to see that from FACS data that I have from the same animals. 
2. That's a very good idea. It actually does look a little nicer in terms of the colors. It also changes the DEGs a little, but not more than I would expect from a slight shift in the cells. The main genes are still there. 

I hope this means I can proceed that way. 
Thank you so much for your assistance. 

![image](https://user-images.githubusercontent.com/64131050/218525718-e2688a19-88de-49b0-80ce-b2d55c1308ee.png)

**Comment by longmanz** [comment]
Hi, 
The heatmap looks good. And it is a good sign that the DEGs you identified are consistent. It indicates that these DEGs are likely real signals. 
For visual illustration, you may also try single-cell level heatmap instead of the current pseudo-bulk heatmap, where you can sub-sample "CD45.2" cells to match the number of "CD45.1".
