### ISSUE TITLE
Error with FindConservedMarkers()

### ISSUE THREAD

**Issue by Chrisdoan9** [satijalab/seurat#6941]
Hi all,

I try to run FindConservedMarkers() but I got this message:

```
markers_cluster_8 <- FindConservedMarkers(CV.harmony,
                    ident.1 = 8,
                    grouping.var = 'condition')
```
Warning: Identity: 8 not present in group B. Skipping VVWarning: Identity: 8 not present in group A. Skipping NCError in marker.test[[i]] : subscript out of bounds.

This error appears in many clusters I chose. Would you have a suggestion? Thank you so much!

**Comment by Gesmira** [comment]
Hi, 
`FindConservedMarkers` will look for ident.1 within the Idents() of your object. Thus, you should set the Idents() to whatever column in your metadata has "8" and your other labels. 

For example, if these labels are in `CV.harmony$seurat_clusters`, you should run: 
``` 
Idents(CV.harmony) <- "seurat_clusters"
markers_cluster_8 <- FindConservedMarkers(CV.harmony,
                    ident.1 = 8,
                    grouping.var = 'condition')
```
