### ISSUE TITLE
DE analysis of merged vs integrated data 

### ISSUE THREAD

**Issue by anarrebelo** [satijalab/seurat#6942]
If the cells compared in the DE analysis are the same, should the DE analysis of merged datasets be the same as DE analysis of integrated datasets? That is, should the RNA assay (data slot) of merged and integrated datasets be the same?

Thanks in advance for your help.

**Comment by saketkc** [comment]
Not sure I understand the question. But if you are asking how shouled DE analysis be perfomed on integrated datasets - then you are right, you should be using the RNA assay for DE.

**Comment by anarrebelo** [comment]
Hi! I am sorry, my question was slightly different.

I have two datasets (dts1 dts2), I combined them through integration, did all the necessary processing and annotated the cells (and added annotation as metadata), then I performed DE analysis with FindMarkers () (roc test, grouping cells based on my annotation, assay = ‘RNA’).

Next, I used DietSeurat to keep only the metadata and RNA assay and split the datasets. I then merged the split datasets, performed all downstream processing and performed DE analysis as before. But even though I am comparing the same groups of cells (roc test, grouping cells based on the same annotation), I get different results. 

It seems that in the DE analysis of assay RNA of the integrated dataset I get many ribosomal genes that do not appear when I do the DE analysis after merging the split objects. 

Shouldn't the output be the same? If I understood correctly the RNA assay of merged and integrated datasets should be the same... Since DE analysis is performed in the RNA assay shouldn't the results be the same in merged and integrated objects?

Thanks in advance for everything!

**Comment by saketkc** [comment]
Yes, it should be the same. Can you update to the latest version of Seurat [4.3.0](https://github.com/satijalab/seurat/releases/tag/v4.3.0)? There was an important bugfix in the 4.3.0 release which would explain the discrepancy.

**Comment by saketkc** [comment]
DE should be performed on the RNA or the SCT assay.

**Comment by anarrebelo** [comment]
Yes, but I get different results when I do the FindMarkers on the integrated (RNA assay) or in the merged object, and since they should be the same, in which results should I trust?

Thank you.

**Comment by saketkc** [comment]
Can you paste your code here?

**Comment by anarrebelo** [comment]
Sure! Here it goes:
`##Integration
seu.list_glia <- list(NAME1= Control_glia)
seu.list_glia <- c(seu.list_glia, NAME2 = Tumor_glia)

features.glia <- SelectIntegrationFeatures(object.list = seu.list_glia)
glia.anchors <- FindIntegrationAnchors(object.list = seu.list_glia, anchor.feature = features.glia)
glia.combined <- IntegrateData(anchorset = glia.anchors)
DefaultAssay(glia.combined) <- "integrated"
glia.combined <- ScaleData(glia.combined, verbose = FALSE)
glia.combined <- RunPCA(glia.combined, npcs = 150, verbose = FALSE)
use.pcs <- 1:74
glia.combined <- FindNeighbors(glia.combined, dims=use.pcs)
glia.combined <- RunUMAP(glia.combined, dims = use.pcs)
res.cutoff <- 0.5
glia.combined <- FindClusters(glia.combined, resolution=res.cutoff)

##Annotate clusters as “Cluster nº_orig.ident”
###Define the identities of the glia.combined as metadata seurat_clusters
Idents(glia.combined) <- "seurat_clusters"
metadata.col <- rep(c("X_XXX"), times = length(colnames(glia.combined)))

###In the metadata.col lets add our glia.combined names instead of X_XXX
names(metadata.col) <- colnames(glia.combined)

nClusters <- 20
for (i in 1:nClusters) {
  CellType.name <- WhichCells(glia.combined, ident= i-1, expression = orig.ident == "Control_glia")
  metadata.col[CellType.name] <- paste0(i-1,"Control_glia")
  
  CellType.name <- WhichCells(glia.combined, ident= i-1, expression = orig.ident == "Tumor_glia")
  metadata.col[CellType.name] <- paste0(i-1,"Tumor_glia")
}

###Add metadata column called cluster_type to the integrated dataset
glia.combined <- AddMetaData(glia.combined, metadata.col, col.name = "cluster_type")
DefaultAssay(glia.combined) <- "RNA"

##DE between the same cluster, different orig.ident 
wb <- createWorkbook()
ntop <- 100
for (i in 1:20) {
  top.markers <- FindMarkers(glia.combined, test.use = "roc", group.by = "cluster_type",ident.1 = paste0(i-1,"Tumor_glia"), ident.2 = paste0(i-1,"Control_glia"), assay = "RNA")
  topNp <- top.markers %>% top_n(n=ntop, wt=myAUC)
 
  addWorksheet(wb,paste0("DE_cluster",i-1,"Tumor_glia"))
  writeData(wb,sheet = paste0("DE_cluster",i-1,"Tumor_glia") , topNp , colNames = T, rowNames = T)
}

###Split the dataset 
glia.combined <- DietSeurat(glia.combined, assay='RNA')
list.seuobj <- SplitObject(glia.combined, split.by = "orig.ident")

### Merge the split datasets 
merge.glia <- merge(list.seuobj$Control_glia, y= list.seuobj$Tumor_glia, add.cell.ids = c("Control_glia", "Tumor_glia") , merge.data = TRUE, project = "merge.glia")
DefaultAssay(merge.glia) <- "RNA"

merge.glia <- FindVariableFeatures(merge.glia, selection.method = "vst", nfeatures = 4000)
merge.glia <- ScaleData(merge.glia, verbose = FALSE)
merge.glia <- RunPCA(merge.glia, npcs = 150, verbose = FALSE)
use.pcs <- 1:71
merge.glia <- FindNeighbors(merge.glia, dims=use.pcs)
merge.glia <- RunUMAP(merge.glia, dims = use.pcs)
res.cutoff <- 0.5
merge.glia <- FindClusters(merge.glia, resolution=res.cutoff)

##DE analysis same cluster integrated, different orig.ident (performed on the merged object)
cortex1_tumorvscortex1_control <- FindMarkers(merge.glia, test.use = "roc", group.by = "cluster_type",ident.1 = "14Tumor_glia", ident.2 = "14Control_glia", assay = "RNA")
ntop1 <- 100
top100P <- cortex1_tumorvscortex1_control %>% top_n(n = ntop1, wt = myAUC)
`

**Comment by anarrebelo** [comment]
Sure! Here it goes: 

```
##Integration
seu.list_glia <- list(NAME1= Control_glia)
seu.list_glia <- c(seu.list_glia, NAME2 = Tumor_glia)

features.glia <- SelectIntegrationFeatures(object.list = seu.list_glia)
glia.anchors <- FindIntegrationAnchors(object.list = seu.list_glia, anchor.feature = features.glia)
glia.combined <- IntegrateData(anchorset = glia.anchors)
DefaultAssay(glia.combined) <- "integrated"
glia.combined <- ScaleData(glia.combined, verbose = FALSE)
glia.combined <- RunPCA(glia.combined, npcs = 150, verbose = FALSE)
use.pcs <- 1:74
glia.combined <- FindNeighbors(glia.combined, dims=use.pcs)
glia.combined <- RunUMAP(glia.combined, dims = use.pcs)
res.cutoff <- 0.5
glia.combined <- FindClusters(glia.combined, resolution=res.cutoff)

##Annotate clusters as “Cluster nº_orig.ident”
###Define the identities of the glia.combined as metadata seurat_clusters
Idents(glia.combined) <- "seurat_clusters"
metadata.col <- rep(c("X_XXX"), times = length(colnames(glia.combined)))

###In the metadata.col lets add our glia.combined names instead of X_XXX
names(metadata.col) <- colnames(glia.combined)

nClusters <- 20
for (i in 1:nClusters) {
  CellType.name <- WhichCells(glia.combined, ident= i-1, expression = orig.ident == "Control_glia")
  metadata.col[CellType.name] <- paste0(i-1,"Control_glia")
  
  CellType.name <- WhichCells(glia.combined, ident= i-1, expression = orig.ident == "Tumor_glia")
  metadata.col[CellType.name] <- paste0(i-1,"Tumor_glia")
}

###Add metadata column called cluster_type to the integrated dataset
glia.combined <- AddMetaData(glia.combined, metadata.col, col.name = "cluster_type")
DefaultAssay(glia.combined) <- "RNA"

##DE between the same cluster, different orig.ident 
wb <- createWorkbook()
ntop <- 100
for (i in 1:20) {
  top.markers <- FindMarkers(glia.combined, test.use = "roc", group.by = "cluster_type",ident.1 = paste0(i-1,"Tumor_glia"), ident.2 = paste0(i-1,"Control_glia"), assay = "RNA")
  topNp <- top.markers %>% top_n(n=ntop, wt=myAUC)
 
  addWorksheet(wb,paste0("DE_cluster",i-1,"Tumor_glia"))
  writeData(wb,sheet = paste0("DE_cluster",i-1,"Tumor_glia") , topNp , colNames = T, rowNames = T)
}

###Split the dataset 
glia.combined <- DietSeurat(glia.combined, assay='RNA')
list.seuobj <- SplitObject(glia.combined, split.by = "orig.ident")

### Merge the split datasets 
merge.glia <- merge(list.seuobj$Control_glia, y= list.seuobj$Tumor_glia, add.cell.ids = c("Control_glia", "Tumor_glia") , merge.data = TRUE, project = "merge.glia")
DefaultAssay(merge.glia) <- "RNA"

merge.glia <- FindVariableFeatures(merge.glia, selection.method = "vst", nfeatures = 4000)
merge.glia <- ScaleData(merge.glia, verbose = FALSE)
merge.glia <- RunPCA(merge.glia, npcs = 150, verbose = FALSE)
use.pcs <- 1:71
merge.glia <- FindNeighbors(merge.glia, dims=use.pcs)
merge.glia <- RunUMAP(merge.glia, dims = use.pcs)
res.cutoff <- 0.5
merge.glia <- FindClusters(merge.glia, resolution=res.cutoff)

##DE analysis same cluster integrated, different orig.ident (performed on the merged object)
cortex1_tumorvscortex1_control <- FindMarkers(merge.glia, test.use = "roc", group.by = "cluster_type",ident.1 = "14Tumor_glia", ident.2 = "14Control_glia", assay = "RNA")
ntop1 <- 100
top100P <- cortex1_tumorvscortex1_control %>% top_n(n = ntop1, wt = myAUC)
```

**Comment by saketkc** [comment]
I am assuming you have run `NormalizeData` on the initial Control_glia and Tumor_glia objects.
Can you try running `NormalizeData()` after `DietSeurat` as well?

**Comment by anarrebelo** [comment]
Yes I have run `NormalizeData` on the initial Control_glia and Tumor_glia objects.

I tried running `NormalizeData()` after `DietSeurat` before merging and it didn't make a difference.

However, I have the impression that the results of `FindMarkers()` are dependent on the order of which you normalize data. That is:

Scenario 1: 
```
NormalizeData(Control_glia)
NormalizeData(Tumor_glia)
merge.glia <- merge(list.seuobj$Control_glia, y= list.seuobj$Tumor_glia, add.cell.ids = c("Control_glia", "Tumor_glia") , merge.data = TRUE, project = "merge.glia")
```
Then I get different results in DE analysis when applying `FindMarkers()` in integrated (assay='RNA') vs in merged object

Scenario 2:
```
NormalizeData(Control_glia)
NormalizeData(Tumor_glia)
merge.glia <- merge(list.seuobj$Control_glia, y= list.seuobj$Tumor_glia, add.cell.ids = c("Control_glia", "Tumor_glia") , merge.data = TRUE, project = "merge.glia")
NormalizeData(merge.glia)
```
Then I get the **same** results in DE analysis when applying `FindMarkers()` in integrated (assay='RNA') vs in merged object

When is it correct to normalize the data and why does it make a difference to normalize after merging if in theory you keep the data slot (Normalized data)?

Thank you very much for your help!

**Comment by saketkc** [comment]
Thanks for your patience @anarrebelo! This issues has been fixed in the develop branch https://github.com/satijalab/seurat/commit/992c1a96693b1467160969625edc8a5c80ab0867 

You can checkout the latest updates by installing the develop branch:

```r
remotes::install_github("satijalab/seurat", ref="develop")
```

If you are still facing issues, please open a new issue.
