### ISSUE TITLE
Parallelization via BiocParallel

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [satijalab/seurat#6944]
Hi ! is it possible to switch from future to BiocParallel since BiocParallel don't copy the data x times in RAM ? 

that will be more efficient withe the increasing size of dataset. 

Thanks

**Comment by alikhuseynov** [comment]
I would be interested to see that too. I'm using [parallel package](https://www.rdocumentation.org/packages/parallel/versions/3.4.0) whenever possible to speed-up things, there I can control for number of cores used etc.. Eg, [mclapply](https://www.rdocumentation.org/packages/parallel/versions/3.4.0/topics/mclapply) function is super useful and faster than default `lapply()`

**Comment by BenjaminDEMAILLE** [comment]
> I would be interested to see that too. I'm using [parallel package](https://www.rdocumentation.org/packages/parallel/versions/3.4.0) whenever possible to speed-up things, there I can control for number of cores used etc.. Eg, [mclapply](https://www.rdocumentation.org/packages/parallel/versions/3.4.0/topics/mclapply) function is super useful and faster than default `lapply()`

I mean not Parallel but BoicParallel : https://www.rdocumentation.org/packages/BiocParallel/versions/1.6.2/topics/bplapply

because parallel also copy x time the data in the ram

**Comment by alikhuseynov** [comment]
I see, have a look at this related issue https://github.com/satijalab/seurat/issues/457

**Comment by rsatija** [comment]
We have a few similar requests and the team agrees that this is worth exploring and looking into. Closing this issue for now but we are going to evaluate the different strategies for parallelization prior to our official v5 release.
