### ISSUE TITLE
Downsample from "STIM" or any Ident from metadata

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#6949]
@pankoj-das , it's in this vignette.
https://satijalab.org/seurat/v3.0/multimodal_vignette.html

Basically, the command is:
`cbmc.small <- subset(cbmc, downsample = 300)`

_Originally posted by @nicodemus88 in https://github.com/satijalab/seurat/issues/3116#issuecomment-640440296_

I would like to downsample by "stim" in my dataset so that each "stim" has the same number of cells (ex: 2000). How would I change this command?
           
I have tried splitting my data by "stim," then performing the downsample using subset(time1, cells = sample(Cells(time1), 2000)), but I need to rerun PCA and UMAP again. How can I preserve my previous UMAP shape?
Do I have no choice but to rerun PCA and UMAP again?

**Comment by longmanz** [comment]
Hi, 
If I understand your requests correctly, you may do it with the following commands:
`stim_cells = Cells(cbmc)[which(cbmc$groups == "stim")]`
`ctrl_cells = Cells(cbmc)[which(cbmc$groups == "ctrl")]`
`slct_stim_cells = sample(stem_cells, size = 2000)`
`slct_ctrl_cells = sample(ctrl_cells, size = 2000)`
`subset_cbmc = subset(cbmc, cells = c(slct_stim_cells, slct_ctrl_cells))`

The subset_cbmc should preserver your original PCA/UMAP information for plotting.
