### ISSUE TITLE
Guided Clustering Tutorial Lacks a Resolution Parameter Choice Section

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#6951]
The tutorial defined by vignettes/pbmc3k_tutorial.Rmd has a section titled Cluster the Cells. The `resolution` parameter controls how many clusters are reported. I would like to see another paragraph about choosing a good value of `resolution`. Perhaps there could be some statistic used, such as Within-cluster Sum of Squares / Between-clusters Sum of Squares and a convenience function that plots the WSS / BSS statistic for a grid of `resolution` parameter values. Is it a good idea to offer such functionality or not?

**Comment by Dragonmasterx87** [comment]
Hi @DarioS 

Im not a seurat Dev but you can use `clustree` to look at cluster stability across layers of resolution. You can find the code here [clustree](https://github.com/lazappi/clustree) you can find a vignette here [clustree vignette](https://cran.r-project.org/web/packages/clustree/vignettes/clustree.html#seurat-objects)

**Comment by mhkowalski** [comment]
Hi. Apologies for the delayed response. We don't have a specific recommendation for a metric to assess cluster resolutions. We have found this to really differ based on what cell types are in your sample and the level of resolution you want for your downstream analysis.
