### ISSUE TITLE
Seurat. How to creat an object with two assays with different number of cells

### ISSUE THREAD

**Issue by Dalhte** [satijalab/seurat#6952]
Hello
I have a RNA + ATAC multiom experiment. 
The RNA part is "dirty" so I have to run soupx first. However, that is modifying my total cells number and when I try to reunite the RNA and ATAC assays in the same object :

object[["ATAC"]] <- CreateChromatinAssay(object.counts, fragments = frags.object, project = "object", assay = "ATAC", meta.data=md.object)

I get :
Cannot add a different number of cells than already present
Is there a way to create the object only with the common cells present in both assays ?
Best
David

**Comment by nathan-nakatsuka** [comment]
Hi David, what you should do is find the cells that were deleted after using soupx, then use the original RNA+ATAC object and subset it to remove the cells that were deleted.
