### ISSUE TITLE
Run DEenrichRPlot() on subset of the original cluster with recorrect_umi = FALSE but failed

### ISSUE THREAD

**Issue by ningxinkang** [satijalab/seurat#6955]
Hi team! I'm doing DE analysis following the [v2 SCT transform tutorial](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html#perform-integration-using-pearson-residuals-1). 
Before doing DE analysis, I run `PrepSCTFindMarkers()` on my Seurat object. And I do DE on separate clusters with `recorrect_umi = FALSE`, using SCT assay, data slot, and Wilcox test.
It works fine for `FindMarkers()`, but fails when I run `DEenrichRPlot()`.
The error message when I run `DEenrichRPlot()` is as follows:
`Error in FindMarkers.SCTAssay(object = data.use, slot = slot, cells.1 = cells$cells.1,  :
  Object contains multiple models with unequal library sizes. Run PrepSCTFindMarkers() before running FindMarkers().`
It seems that 'DEenrichRPlot()' does not recognize the corrected counts. Please let me know what I can do to correct this!

Thank you!!

Here is a chunk of my code

    Idents(new_integrated_obj)  <- "Visit"
    lapply(unique(new_integrated_obj$seurat_clusters)[-(1:3)], function(sc) {
      enrichR <- DEenrichRPlot(
        subset(new_integrated_obj, subset=seurat_clusters == sc),
        ident.1 = "V1",
        ident.2 = "V3",
        logfc.threshold = 0.25,
        balanced = T,
        min.pct = 0.25,max.genes = 500,
        test.use = "wilcox",verbose = TRUE,
        only.pos = F,assay = "SCT", 
        slot = "data",
        enrich.database = "GO_Biological_Process_2021",
        return.gene.list = T)
    })

**Comment by mhkowalski** [comment]
Hello, 

My apologies, but we are no longer supporting this function. Please refer to other packages that enable the user to perform gene set enrichment analyses.
