### ISSUE TITLE
A question about parameter clip.max in Seurat::FindVariableFeatures function.

### ISSUE THREAD

**Issue by CaoWei-UM** [satijalab/seurat#6957]
Dear all,
    I'm a student and I tried to use Seurat to deal with my scRNA-seq data. When I use function "FindVariableFeatures" with default "vst" method, I noticed there's a parameter called "clip.max", and the default value of it is the square root of the number of cells. I'm confused about this value, so I checked source code of function "FindVariableFeatures". But I still confused about it.
    In preprocessing.R line 3467,  "FindVariableFeatures " called c++ function "SparseRowVarStd",  the "clip.max" is "vmax" in this function.  "vmax" should be used to "clip **values** larger than vmax to vmax". I don't know what the **values** is. And that extend to 2 more questions.
    1. In data_manipulation.cpp line 324, "std::min" is used for "vmax" and "(it.value() - mu[k]) / sd[k]" . "sd[k]" is the square root of the expected varience of gene k. When "(it.value() - mu[k])" is a negative value (a cell's UMI count less than mean count of a gene), "vmax" cannot clip this value.
    2.  If we change data_manipulation.cpp line 324 to "colSum += std::min(pow(vmax, 2), pow((it.value() - mu[k]) / sd[k], 2));", the result is still strange. The expectations value of "pow((it.value() - mu[k]) / sd[k], 2)" is "((mat.rows() - 1)*varience[k])/(mat.rows()*expected.varience[k])", a value around 1. But pow(vmax, 2) is "mat.rows()", the number of cells, much larger than 1. Why use such  a big value to clip a small value?
    Thank you for your help!
             CaoWei

**Comment by rsatija** [comment]
Very sorry for the slow reply here. The reason we have this parameter is to set a maximum value for outlier gene expression. If we don't clip at all, any artifactual gene (for example, from a molecule with many PCR sequencing errors in the UMI) can drive aberrant clustering. If we clip with too small a value, it dampens the influence of an outlier, which may make it harder to find rare cell types. 

We found that reasonable settings for this parameter scale with the square root of total cells in the dataset, which explains the code you are citing.
