### ISSUE TITLE
How to plot expression of a single cell marker in a Seurat object?

### ISSUE THREAD

**Issue by giuliospinozzi** [satijalab/seurat#6961]
Hi, I would like to make an x-y plot of the coordinates of a marker, first selecting the positive cells (setting a threshold on the expression), how can I do it?

Here is the Seurat object:
```
seurat<-CreateSeuratObject(total)

#Normalization using the CLR method (recommended for CITE-seq data, which is still protein and therefore closer than RNAseq)
seurat <- NormalizeData(seurat, normalization.method = "CLR", scale.factor = 10000)
all.genes <- rownames(seurat)
seurat <- ScaleData(seurat, features = all.genes)

seurat <- RunPCA(seurat, features = all.genes)

#dimentions based on PCA
dimentions=20

# select dims based on PCA plot
seurat <- FindNeighbors(seurat, dims = 1:dimentions)
seurat <- FindClusters(seurat, resolution = 0.3)
```

**Comment by mhkowalski** [comment]
Can you please clarify what "coordinates" you are referring to?

**Comment by giuliospinozzi** [comment]
> Can you please clarify what "coordinates" you are referring to? 

Plot in the coordinates of the ROI. After that also in the cluster coordinates.

Thanks

**Comment by giuliospinozzi** [comment]
here some pics...

<img width="321" alt="Screen Shot 2023-02-26 at 10 19 23" src="https://user-images.githubusercontent.com/9041243/221402230-fb600b7a-eaa8-4541-be99-444caf46aa89.png">
<img width="238" alt="Screen Shot 2023-02-26 at 10 19 58" src="https://user-images.githubusercontent.com/9041243/221402259-c481699d-c4f8-4655-b3ad-1e9f68f56578.png">

**Comment by giuliospinozzi** [comment]
Hi tried this code, but it produces errors:
`for (i in 1:length(seurat_list)) {
  seurat_list[[i]] <- NormalizeData(seurat_list[[i]], verbose = FALSE)
  #seurat_list[[i]] <- ScaleData(seurat_list[[i]], features = all.genes)
  seurat_list[[i]] <- FindVariableFeatures(
  seurat_list[[i]], selection.method = "vst",
  nfeatures = 2000, verbose = FALSE
  )
}
anchors <- FindIntegrationAnchors(object.list = seurat_list)
alldata.int <- IntegrateData(anchorset = anchors)`

seurat_list is a large list of seurat object (9 items)

Merging dataset 8 into 7
Extracting anchors for merged samples
Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  did not converge--results might be invalid!; try increasing work or maxit
Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds

**Comment by rsatija** [comment]
Not sure exactly what you are asking but here are two things that might be helpful

```
# select cells that pass a threshold and only plot these cells
cells.plot <- WhichCells(pbmc,expression = LYZ>2)
DimPlot(pbmc)

# plot specific parts of a UMAP
DimPlot(pbmc,cells = cells.plot)+xlim(-10,10)+ylim(-10,10)
```
