### ISSUE TITLE
How to plot density of cells

### ISSUE THREAD

**Issue by chrismahony** [satijalab/seurat#6962]
I would like to plot the density of cells on my umap to show e.g. I have greater density of cells in cluster 1 in my treated vs untreated controls?

Is this possible?

Thanks

**Comment by longmanz** [comment]
Hi, 
As suggested here (https://github.com/satijalab/seurat/issues/2520), to generate a density-like UMAP you may try to modify the UMAP object with the geom_density_2d from ggplot2 (https://ggplot2.tidyverse.org/reference/geom_density_2d.html)

Or you may try R-packages like the "Nebulosa" which is compatible to Seurat (https://bioconductor.org/packages/devel/bioc/vignettes/Nebulosa/inst/doc/nebulosa_seurat.html).

**Comment by alikhuseynov** [comment]
you mean something like that?
<img width="963" alt="umap_dens" src="https://user-images.githubusercontent.com/52053807/221411083-102107ab-5844-4b37-9af9-e36505f83307.png">

```
# using small single cell dataset - pbmc_small
library(cetcolor)
library(Seurat)
library(ggplot2)

# run UMAP
pbmc_small %<>% RunUMAP(dims = 1:10, reduction = "pca")

# generate UMAP plot
pl1 <- UMAPPlot(pbmc_small, 
                combine = FALSE # returns full ggplot object
                )

# custom color scale
scale.col <- cet_pal(16, name = "fire")

# make plot
pl1[[1]] & 
  stat_density_2d(aes_string(x = "UMAP_1", y = "UMAP_2", fill = "after_stat(level)"), 
                  linewidth = 0.2, geom = "density_2d_filled", 
                  colour = "ivory", alpha = 0.4, n = 150, h = c(1.2, 1.2)) & 
  scale_fill_gradientn(colours = scale.col) & 
  DarkTheme()
```
