### ISSUE TITLE
use of raw counts after the data matrix is generated

### ISSUE THREAD

**Issue by coralzhang** [satijalab/seurat#6963]
Dear authors, 
I have a question about when Seurat will directly use the raw count matrix in the object after the data matrix (normalized counts) is generated. In my data, I have a gene that constitutes a relatively big portion of the total number of reads in a specific group of cells. But for a specific purpose, I do not want to include this gene in any of the analyses, from variable genes/dimension reduction to data integration and later clustering, visualization, or DE genes. Suppose I exclude this gene in constructing the Seurat object. In that case, the issue I see is that the normalization will be significantly biased upwards for the cells with high counts of this gene (since the library size is estimated downwards for these cells). So the workaround I can think of is to create the Seurat object without this gene, do the log normalization manually with that special gene’s counts taken into consideration, and put it in Seurat’s data slot. Now the pitfall is if Seurat is ever going to use the original counts again in other functions to calculate, say, the column sum of the count matrix furthermore. Thanks!

**Comment by longmanz** [comment]
Hi, 
When you run PCA, clustering, DE, or UMAP, you can always specify the list of features/genes you want to use with "features = " flag. In that case, you can remove that gene in your feature list so that it will not be used during these processes.

**Comment by coralzhang** [comment]
My analysis include the data integration in the end, and the step  FindVariableFeatures is a step prior to [SelectIntegrationFeatures](https://satijalab.org/seurat/reference/SelectIntegrationFeatures.html). FindVariableFeatures seems to ignore the features argument. See below: 


LoadData("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")

dat=ifnb.list[["CTRL"]]
dat=NormalizeData(dat)
feat1=rownames(dat)[1:1000]
dat=FindVariableFeatures(dat, selection.method = "vst", nfeatures = 200, features=feat1)
which(dat@assays$RNA@var.features %in% feat1) ## this length should be 200 if things work out as expected, but the out put is much shorter. 
[1]  28  29  44  71  76 116 123 131 157 160 166 168 170 176 177 181 189 192 200
