### ISSUE TITLE
FindMarkers with split.by genotype

### ISSUE THREAD

**Issue by MariamHakobyanL** [satijalab/seurat#6966]
Hi,

Could you please explain what exactly this command will do in terms of comparison and statistical testing:
DEG <- FindMarkers(seurat, ident.1 = "clusterA", split.by = "genotype").
For example,  does this compare WT clusterA gene expression with all other WT clusters and mutant clusterA with all other mutant cells and then both results with each other?

Many thanks for your time!
Mariam

**Comment by longmanz** [comment]
Hi, 
split.by does not do anything in FindMarkers(). If you are looking for a way to separate your groups, you can try the "group.by = " and "subset.ident =" flag.

**Comment by MariamHakobyanL** [comment]
Hi, 

Thank you for your answer! So the following line would be the correct one, as suggested by the tutorial.
FindMarkers(seurat, ident.1 = "WT", group.by = "genotype", subset.ident = "CD4_Tcells")

My problem with this was, that I get almost no DEGs, which could of course be due to the biology, but when using other downstream analysis methods, I do see clear transcriptional differences. Could you maybe comment on what the problem here might be?

Thank you for your time!

**Comment by longmanz** [comment]
Hi, 
No DEGs being found could be driven by different reasons. 
1. The default DE method is wilcoxon rank sum test, which is quite conserved. You may try other methods instead. 
2. The p_val_adj reported by FindMarkers is after Bonferroni multiple testing correction (which is very stringent). You may rank the genes based on "p_val" instead, and check if the top genes are what you expect. 
3. The default log-fold change threshold (logfc.threshold) is 0.25. You may lower it to 0.1 to include more genes in DE test. Some DEGs might come with lower logfc.threshold. 

In your downstream analysis methods, did you do any other DE test? Could you give an example of "clear transcriptional differences"?
