### ISSUE TITLE
FindClusters(so, algorithm = 4, method = "igraph") issue with leiden/leidenalg package 

### ISSUE THREAD

**Issue by mauritsunkel** [satijalab/seurat#6967]
I ran FindClusters(so, algorithm = 4, method = "igraph") fine a couple of months ago, I don't recall reinstalling any package in the meantime but now it's not working anymore.

I have leidenalg v0.8.4 installed via reticulate in a r-miniconda environment. 
I also tried my local python v3.8 install with: pip install leidenalg (v0.8.4). 

Running FindClusters(so, algorithm = 4, method = "igraph") while the python from r-miniconda gets called straight up crashes (aborts) my R session. 
Running via my local python gets me the following error: 
 Error in py_get_attr_impl(x, name, silent) : AttributeError: module 'leidenalg' has no attribute 'Optimiser'

(Another try got me another error: Error in make_py_object.igraph(object, weights = weights) : (converted from warning) NAs introduced by coercion to integer range

Any tips are welcome. 
What are the steps I could follow to resolve this?

**Comment by mauritsunkel** [comment]
If I restart R and follow the steps from cstill1992's comment in #2512 with the following code: 
library(leiden)
reticulate::py_install(packages ='leidenalg')
reticulate::py_install(packages ='igraph')
reticulate::py_install(packages ='numpy')
devtools::install_github("TomKellyGenetics/leiden")
Cluster_assignment <- leiden(integrated@graphs$integrated_snn)

I get:
Error: ImportError: DLL load failed while importing _c_leiden: The specified procedure could not be found.

**Comment by mauritsunkel** [comment]
Following the steps from #114 @vtraag
conda create -n r-leiden -c conda-forge r-leiden leidenalg numpy
# perform all necessary installation steps in terminal 
source activate r-leiden
R
library("leiden")
no
library(igraph)
G <- igraph::graph.famous('Zachary')
part <- leiden::leiden(G)

I get 
# Error: ImportError: DLL load failed while importing _c_leiden: The specified procedure could not be found.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
