### ISSUE TITLE
SCTransform v2 visualisation and DE analysis

### ISSUE THREAD

**Issue by acv21** [satijalab/seurat#6968]
Hello,

I am analysing a 10x scRNA-seq dataset, and prior to cell cycle regression, clustering and DE analysis, I've run SCTransform v2 as follows:
`object <- SCTransform(object, method="glmGamPoi", vars.to.regress="percent.mt", vst.flavor = "v2", verbose=FALSE)`
I have a few questions, related to visualisation and DE analysis.

When running `FeaturePlot` and `VlnPlot`, I tried three options (see plots attached/below):
![seuratviz](https://user-images.githubusercontent.com/112349930/220217490-3a4eaa12-da11-478a-810b-facbafed185c.jpg)

- Plots A and D: using default code (data slot from SCT assay). However, I noticed that some genes seemed to be expressed in cell types that I would not expect them to be expressed in at all. Also, the expression level seems to be in discrete internals, which does not seem biologically plausible.
- Plots B, E and C: I tried plotting the data using the scale.data slot, and the results are closer to what I would expect (in plot E, *only* if we consider 0 as the "real" threshold: for instance, I would not expect any expression of this gene in cluster 5). However, the expression level of some cells is negative (which is confusing, how can it be?) (see plot B and E. In plot C, I set a threshold of 0.
- Plot F: As a last option, I tried changing the assay to "RNA" (data slot, log-normalised): this plot is also a bit confusing, as I would not expect expression in several clusters including cluster 5.

Code below (default assay is SCT):
`A <- FeaturePlot(object, features=c("PECAM1"), pt.size=0.2, min.cutoff=0)`
`B <- FeaturePlot(object, features=c("PECAM1"), pt.size=0.2, slot="scale.data")`
`C <- FeaturePlot(object, features=c("PECAM1"), pt.size=0.2, slot="scale.data", min.cutoff=0)`
`D <- VlnPlot(object=object, features='PECAM1', assay="SCT")`
`E <- VlnPlot(object=object, features='PECAM1', assay="SCT", slot="scale.data")`
`F <- VlnPlot(object=object, features='PECAM1', assay="RNA")`

My questions are:

1. What is the best/most accepted way to visualise gene expression level, both in `FeaturePlot`, `VlnPlot`, and for downstream analyses such as calculating the % of cells expressing a gene? When I try calculating the % of cells expressing the gene as explained [here](https://github.com/satijalab/seurat/discussions/5033#discussioncomment-1869728) (3rd option), I get very high percentages, which for many clusters I would not expect at all.
2. Why are there negative values in plots B and E? And more in general, how can I define the "true" negative cells? Biologically speaking, I would expect the 0 line in plot E to be the true negative threshold, but I am worried that it actually isn't, and that I am missing cells with low expression of my gene of interest due to some transformation of the data in the scale.data slot.
3. Lastly, I have a question which is not related to data visualisation: in the [SCTransform v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), it says to use [`PrepSCTIntegration`](https://satijalab.org/seurat/reference/PrepSCTIntegration.html) before `FindMarkers`. Is this only true when working integrating two datasets? I am working with a non-integrated dataset, do I also need to perform `PrepSCTIntegration` before `FindMarkers` or `FindAllMarkers`?

Thank you for your time and help!

**Comment by hannah-codenow** [comment]
I have the same issue, except even I used "scale.date" all the dots are aligned.

**Comment by saketkc** [comment]
> What is the best/most accepted way to visualise gene expression level, both in FeaturePlot, VlnPlot, and for downstream analyses such as calculating the % of cells expressing a gene? When I try calculating the % of cells expressing the gene as explained https://github.com/satijalab/seurat/discussions/5033#discussioncomment-1869728 (3rd option), I get very high percentages, which for many clusters I would not expect at all.

As we show in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), the `data` slot of SCT assay should be used for visualization and differential expression analysis. The `scale.data` slot stores the residuals which are hard to compare across datasets. The `data` slot contains `log1p(corrected counts)`. To caculate % of cells expressing a particular gene I would recommed using the `FoldChange()` function with the SCT assay. Documentation is [here](https://satijalab.org/seurat/reference/foldchange). Also it seems your plot F is  based on the SCT assay (the scales on the RNA assay go all the way upto 15 likely indicating it has not been normalized - i.e. `NormalizeData` was not run before visualization).

> Why are there negative values in plots B and E? And more in general, how can I define the "true" negative cells? Biologically speaking, I would expect the 0 line in plot E to be the true negative threshold, but I am worried that it actually isn't, and that I am missing cells with low expression of my gene of interest due to some transformation of the data in the scale.data slot.

Hopefully this is answered in my response to your previous question. 

> Lastly, I have a question which is not related to data visualisation: in the [SCTransform v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), it says to use [PrepSCTIntegration](https://satijalab.org/seurat/reference/PrepSCTIntegration.html) before FindMarkers. Is this only true when working integrating two datasets? I am working with a non-integrated dataset, do I also need to perform PrepSCTIntegration before FindMarkers or FindAllMarkers?

The recommendation is to use `PrepSCTFindMarkers` (and not `PrepSCTIntegration`) for running differential expression on SCT assays for two different objects (or experiments). The reasoning behind `PrepSCTFindMarkers` is to bring the two experiments to same sequencing depth (as by default SCT's correction step caculates counts based on median sequencing depth of the experiment which could vary across experiments).

**Comment by hannah-codenow** [comment]
Not sure why but I have used the `data` slot of SCT assay but all dots are still aligned. See code below:

`VlnPlot(querydata,features = c("Pdcd1","Ctla4"), group.by = "t_cell_line", pt.size = 0.01, add.noise = FALSE, slot = "data", assay = "SCT")`

![Screenshot 2023-02-24 at 1 00 56 PM](https://user-images.githubusercontent.com/126226389/221255075-f8ddd389-3886-4458-8fbd-9054a3cd0333.png)

**Comment by hannah-codenow** [comment]
> > What is the best/most accepted way to visualise gene expression level, both in FeaturePlot, VlnPlot, and for downstream analyses such as calculating the % of cells expressing a gene? When I try calculating the % of cells expressing the gene as explained [#5033 (comment)](https://github.com/satijalab/seurat/discussions/5033#discussioncomment-1869728) (3rd option), I get very high percentages, which for many clusters I would not expect at all.
> 
> As we show in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), the `data` slot of SCT assay should be used for visualization and differential expression analysis. The `scale.data` slot stores the residuals which are hard to compare across datasets. The `data` slot contains `log1p(corrected counts)`. To caculate % of cells expressing a particular gene I would recommend using the `FoldChange()` function with the SCT assay. Documentation is [here](https://satijalab.org/seurat/reference/foldchange). Also it seems your plot F is based on the SCT assay (the scales on the RNA assay go all the way upto 15 likely indicating it has not been normalized - i.e. `NormalizeData` was not run before visualization).

I think the default setting of slot is `data`, so [acv21](https://github.com/acv21)'s figure D still have the problem of discrete data, just like mine. Could you help us look into this?

**Comment by saketkc** [comment]
As I mentioned, `data` slot is `log1p(corrected counts)` so the output will not be continuous (Corrected counts for a gene would be 0,1,2 resulting in 0, 0.69, 1.09 respectively)

**Comment by Sanaz01** [comment]
Hi @saketkc
Thank you for your inputs! My following questions are regarding analysis of scRNA data.
1. As you mentioned earlier that 
> As we show in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html), the data slot of SCT assay should be used for visualization and differential expression analysis

However, following `FindMarkers` function from [this](https://satijalab.org/seurat/reference/findmarkers) mentions that when `test.use="DESeq2"`, `slot=counts` is set automatically. Even when 'data' is provided as input. Is there any misunderstanding from my side? How to proceed from here?

2. Learning from [vignette](https://satijalab.org/seurat/archive/v4.3/sctransform_v2_vignette), commands for finding DE genes after using `IntegrateData` on multiple Seurat objects is:
```
seurat_combined <- PrepSCTFindMarkers(object=seurat_combined, assay = "SCT", verbose = TRUE)
markers <- FindAllMarkers(seurat_combined, assay="SCT", test.use='DESeq2', slot="data")
```
I am getting the following error:
Calculating cluster SWOG2003
Setting slot to counts for DESeq2 (counts based test: 
Calculating cluster SWOG2178
Setting slot to counts for DESeq2 (counts based test: 
Calculating cluster SWOG-3304-B
Setting slot to counts for DESeq2 (counts based test: 
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing SWOG2003 versus all:
	None of the functions passed could be found
Warning: When testing SWOG2178 versus all:
	None of the functions passed could be found
Warning: When testing SWOG-3304-B versus all:
	None of the functions passed could be found

3. Learning from your [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9) **FigS23**, using the DESeq2 on SCT corrected counts should give me similar results as 
`markers <- FindAllMarkers(seurat_combined, assay="RNA", test.use='DESeq2', slot="counts")`
Is this correct?

**Comment by saketkc** [comment]
Thanks for your question, @Sanaz01.

> However, following FindMarkers function from [this](https://satijalab.org/seurat/reference/findmarkers) mentions that when test.use="DESeq2", slot=counts is set automatically. Even when 'data' is provided as input. Is there any misunderstanding from my side? How to proceed from here?

This is an implementation choice. You can pull out the corrected counts and run DESeq2 manually.
