### ISSUE TITLE
Get ''cells per spot'' and ''genes per spot from a Seu object containing a 10x Visium experiment

### ISSUE THREAD

**Issue by cathalgking** [satijalab/seurat#6969]
I have a 10x Visium experiment containing an image and expression values (aligned with Space ranger) contained within a Seurat object. I would like to answer 2 questions about my sample:
1. How many **cells** per Visium spot are present?
2. How many **genes** per Visium spot are present?

And if possible - view each of the above on the tissue image?

Is there a way to do this with the Seurat package? I know that there is standard Vln plots showing genes and library size but I would need the co-ordinates of each spot (I think) in order to do this.

Thanks

**Comment by AustinHartman** [comment]
1. It's not possible to deconvolve exactly how many cells are present per Visium spot, but you can try to estimate based on known spot size and expected cell size. 10x Genomics suggests [here](https://www.10xgenomics.com/resources/analysis-guides/integrating-single-cell-and-visium-spatial-gene-expression-data) that there are 1-10 cells per spot.
2. You can access the number of genes per spot via the `nFeature_Spatial` metadata column.
You can plot the number of genes per spot with the following:
`SpatialFeaturePlot(object, features = "nFeature_Spatial")`

**Comment by alikhuseynov** [comment]
- to get ~ number of cells per spot you need to use some other tools, not sure if this is now available in Seurat. Eg, a measure of how many (segmented) nuclei of H&E image are present under each spot. That could give you some "estimated" measure for number of cells.
- total genes per spot -> `nFeature_Spatial`, and total UMIs per spot -> `nCount_Spatial`, are available after you create your Seurat object.

**Comment by marencc** [comment]
@alikhuseynov Which tool would you recommend to measuere "how many (segmented) nuclei of H&E image are present under each spot" ?? Many thanks!

**Comment by alikhuseynov** [comment]
> @alikhuseynov Which tool would you recommend to measuere "how many (segmented) nuclei of H&E image are present under each spot" ?? Many thanks!

I haven't tried segmentation tools in R, but should work on H&E.
 https://github.com/ludvigla/TREXSeg https://htmlpreview.github.io/?https://github.com/ludvigla/cell_segmentation/blob/master/doc/cell_segmentation.html
https://bioconductor.org/packages/release/bioc/vignettes/simpleSeg/inst/doc/simpleSeg.html
