### ISSUE TITLE
FeaturePlot split.by Only Allows One Row of Output

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#6970]
`split.by` isn't flexible enough to allow customisation of the number of rows the plot should be split into. It results in a bad plot.
![image](https://user-images.githubusercontent.com/631218/220211910-6df1893c-ac23-4b50-95cf-c5459de8410e.png)
It looks like it uses `wrap_plots` from [patchwork](https://cran.r-project.org/web/packages/patchwork/index.html) package which has `nrow` and `ncol` but no way to pass them through from Seurat.

**Comment by samuel-marsh** [comment]
Hi @DarioS,

Not member of dev team but hopefully can be helpful.  There are two solutions you can use for this.  You can wrap plots yourself second time or I have implemented the ability to split plot and specify columns in my package scCustomize.  See this link for details on both solutions: https://github.com/satijalab/seurat/issues/3463#issuecomment-1435709876

Best,
Sam

**Comment by mhkowalski** [comment]
Closing this issue, thanks @samuel-marsh for the solution!

If you'd like to do this with patchwork, ou can return a list of plots using the `combine=FALSE` option, which then can be used with `wrap_plots` or other similar functions.
