### ISSUE TITLE
Updated packages on the same computer causes UMAP to cluster differentely

### ISSUE THREAD

**Issue by theoffice18** [satijalab/seurat#6972]
Hello,

Today I went through the process of single cell analysis and needed to updated some packages so I could install CellChat. I updated a few packages, but some required me to restart R studio. So I saved my script and updated a bunch of packages. However once I went through my code again. The UMAP looked flipped and some of the clusters were either a different size or a different location. See pics below. First one being the original and the second being after I updates some packages. This was done on the same computer all in the same day. This happened *occasionally* to me before, and in those circumstances I would restart r studio once or twice and it would go back to looking the same. However, I have done that several times and still am having an issue.  I have looked up prior cases on GitHub of this and I could only find ones that were across different computers or a different OS. 

Appreciate any help!

Theoffice18

![DGE_filteredumap_louvain_res_p3-labels](https://user-images.githubusercontent.com/126020895/220451420-06c064e7-adf6-41b5-b7db-43f1c11bafaa.png)

![flip](https://user-images.githubusercontent.com/126020895/220451466-ad5993ec-8ab5-461f-bbad-135cee243233.png)

**Comment by SofieRutsaert** [comment]
I have the same problem. Same script run on the same computer with the same dataset. One UMAP run in 2022, one run in 2023, for two different datasets. Based on prior comment found here on Github but indeed different computers then, I hoped and concluded that it is not an issue.


![image](https://user-images.githubusercontent.com/7246664/220692162-f227cd95-eeec-4415-a30a-a43f4944bd48.png)

![image](https://user-images.githubusercontent.com/7246664/220692355-cc130959-aa06-40be-ab0c-f8427e1f9a27.png)

**Comment by AustinHartman** [comment]
It's possible that updates in a number of packages could change the resulting UMAP slightly. I think the most likely package which could be impacting projections is `uwot` which you can try downgrading to an earlier version. For example:
`devtools::install_version("uwot", version = "0.1.10", repos = "http://cran.us.r-project.org")`

**Comment by theoffice18** [comment]
I re-ran all code and it went back to working normally again. I believe the only ones I was skipping were ones where I saved a figure. Must have been skipping something on accident.

Thanks for the help.
