### ISSUE TITLE
LogNormalize in NormalizeData documentation is a little unclear, small word change could help

### ISSUE THREAD

**Issue by AngCamp** [satijalab/seurat#6974]
The documentation for LogNormalize in [NormalizeData](https://satijalab.org/seurat/reference/normalizedata)  states the following: **"LogNormalize: Feature counts for each cell are divided by the total counts for that cell _and multiplied_ by the scale.factor. This is then natural-log transformed using log1p"** how ever the wording of **"_AND_ multiplied by the scale factor"** should be changed to "_BEFORE BEING_ multiplied" or "_THEN_ multiplied", the reason being the current wording leaves it vague as to whether the cell feature count is multiplied by the scale factor or if the full term is multiplied.  Ideally the actual equation would be provided with mathjax if that is possible.  Also while it may be clear to the authors that feature counts represents UMI, it should be made explicit that the feature counts is being used as a stand in for UMI as feature count is not a term used in literature and could lead to confusion.

**Comment by Lea2609** [comment]
(a/b)*c = (a*c)/b. It is the same thing

**Comment by yuhanH** [comment]
Thank you @Lea2609  for your explanation. 

hi, @AngCamp Thank you for your suggestion for our documentation. Just like @Lea2609 respond, the current documentation describes the same thing you suggested.
