### ISSUE TITLE
Load/Merge multiple sequencing runs for same sample

### ISSUE THREAD

**Issue by Alexlcm826** [satijalab/seurat#6975]
How do I merge sequencing data from multiple cartridges? I'm working on a CROP-seq dataset containing Transcriptome, CITE and SGRNA 3 different assays, where the samples were sequenced across 12 different cartridges. After initial QC of individual cartridges, I would like to merge the counts across these assays and perform QC on the large Seurat object, without creating unique cell barcodes.

How do I merge multiple Seurat objects or counts across different assays without creating unique cell barcodes? Is there a way to bypass  CheckDuplicateCellNames()?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So if you are sequencing the same library across multiple sequencing runs then the merge needs to be performed during the generation of count matrices from the sequencing runs.  The reason for this is to ensure accurate collapsing of UMIs.  If you simply added count values across all the runs there is no way to confirm that you are not duplicate counting the same UMIs across runs.  This will also solve the issue of having duplicate cell names as it will collapse everything in single matrix.

Best,
Sam

**Comment by longmanz** [comment]
Hi, 
Many thanks to @samuel-marsh 's response. As he suggested, to merge multiple runs from the same sample, we have to do it before the alignment/generation of count matrix. Specifically, I would catenate all the fastq files from multiple runs into a single fastq file and then do the alignment using cellranger.
