### ISSUE TITLE
Documentation for importing custom spatial transcriptomics data

### ISSUE THREAD

**Issue by pvtodorov** [satijalab/seurat#6977]
The [Image Based Transcriptomics vignette](https://satijalab.org/seurat/articles/spatial_vignette_2.html) on the Seurat website details loading from various spatial formats. I have a different format (Resolve) and would like to know if there is a general way to create a Seurat object with counts, coordinates, image, etc that is recommended for data that does not currently fit.

**Comment by alikhuseynov** [comment]
one of our lab members developed pipeline to process Resolve data and generate Seurat object. 
Older version is available -> https://github.com/MicheleBortol/RESOLVE_tools
The optimized one is currently on institutional GitLab. 
If you have a gitlab account, here is the link -> https://codebase.helmholtz.cloud/resolve_tools/

**Comment by AustinHartman** [comment]
Thanks for the reference @alikhuseynov. I'd recommend using the shared resolve_tools code for now @pvtodorov. We should have a LoadResolve function available soon once output formats from their pipeline are mature / public data is available.
