### ISSUE TITLE
Gene loadings of the umap of several integrated datasets

### ISSUE THREAD

**Issue by AndreaRP** [satijalab/seurat#6979]
Hi!

I have integrated 4 datasets (following [this](https://satijalab.org/seurat/articles/integration_rpca.html) vignette). Everything worked great and I generated a nice integrated UMAP of everything. However, for some reason I can't find the UMAP feature loadings. The slots in `seurat_object@reductions$umap@feature.loadings` and `seurat_object@reductions$umap@feature.loadings.projected` are both empty matrices. The embeddings are in their slot, however. 
How can I access the loadings info for the integrated UMAP?

Thanks!

**Comment by Dragonmasterx87** [comment]
Hi @AndreaRP 

Not a dev but will try to help, not entirely sure what you are trying to achieve tho. Let's assume your integrated dataset is called `cowabunga`

First ->

```
# Whats the output of: 
cowabunga@reductions[["umap"]]
```

Second ->

```
# If you are trying to get your feature loadings this should work for you
df.cellembeddings <- as.data.frame(cowabunga[["umap"]]@cell.embeddings)
```

Hope that helps, if not tag me in the response and i'l try to help.

Cheers,

🐲

**Comment by AndreaRP** [comment]
Thanks for the tip Dragonmasterx87 (cool name btw), but what I want are the gene loadings (the contribution of the genes to the variance of each component) not the position of the cells in the UMAP, which is what's stored in the cell.embeddings slot.

**Comment by longmanz** [comment]
Hi, 
The UMAP is not a linear transformation (such as PCA). It is a non-linear transformation that works on distances (usually calculated based on PCs) between cells. Therefore, unlike PCA, there is no "feature.loadings" in UMAP. This thread explained it better than me: https://github.com/lmcinnes/umap/issues/129

**Comment by Dragonmasterx87** [comment]
Hi @AndreaRP as @longmanz outlines, UMAP is non-linear multidimensional reduction therefore it works on distances calculated from the PCs if you need feature embeddings you will have to use lower dimensional equivalents like the PCA.
