### ISSUE TITLE
Spot/Radius size conversion to Micron (real distance)

### ISSUE THREAD

**Issue by mortunco** [satijalab/seurat#6980]
Hi,

Thank you for developing Seurat. Its reliable and makes spatial/single-cell data analysis standardized.

BACKGROUND:
Lets limit our discussion for the visium slides right now. I would like to obtain the spot positions in metric (micron) format. From this  [link](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/spatial), I took that we can calculate Micron/Pixal ratio from the following paragraph.

> The spot diameter and fiducial diameter are estimated fractional pixels of the spot diameter in the original image. They are estimated based on the registration solution and the known size of the spots and fiducial frame and does not use prior knowledge of the image pixel sizes. In this example, the estimated pixel size was calculated from the spot diameter for the full resolution image. microns/pixels=65/89.43834961≈0.7267575965

PROBLEM:
I was hoping solve this problem by multiplying GetTissueCoordinates(), then I realised Seurat does some background scaling operations.

Question1:
In this line, we calculate unnormalized radius and spot radius. https://github.com/satijalab/seurat/blob/763259d05991d40721dee99c9919ec6d4491d15e/R/preprocessing.R#L1051-L1052
Could you elaborate, why there is not a constant radius which is `the diameter of a theoretical 65µm spot` from the 10x link above? I am analyizing two datasets here and their radius values are not same.

```
r$> Radius(brca1@images$brca1)
0.01264679

r$> Radius(brca0@images$brca0)
[1] 0.01144189
```

Question2:
What is the unit of the `Radius(seurat_obj@images)` code. Referring the line shared above, to me it seems like 1/diameter. 
```
unnormalized radius = fiducial_diameter_fullres (Pixels/Diameter) * tissue_lowres_scalef (nounit)
spot.radius <-  unnormalized.radius (Pixels/Diameter) / max(dim(x = image)) (Pixel)
= 1/Diameter
```

Question3:
Cellranger reports both fiducial and spot pixel/radius values but we used fiducial ones here rather than spot ones. Is there any reason? Also I couldnt find any resources about why these two are not same (This is 100% not Seurat related but I couldn't find anything else online sorry.)

I know this problem is kinda, we wanted to solve this problem this way question but you folks have already very helpful to explain Seurat's philosophy. I really looked everywhere and wanted to ask. 

Thank you very much for your time,

Best regards,

Tunc.

**Comment by mortunco** [comment]
This is link to the data.
https://www.dropbox.com/scl/fo/7vmdltymwsbqeca2auajg/h?dl=0&rlkey=3roq58rcgri9jh1pu53b5b7kl

This is the following code
```
brca0=Load10X_Spatial(data.dir="./ST_BRCA0",slice="brca0")
brca1=Load10X_Spatial(data.dir="./ST_BRCA1",slice="brca1")

Radius(brca1@images$brca1)
Radius(brca0@images$brca1)
```

**Comment by AustinHartman** [comment]
Hi, I understand its a little confusing to find that these values vary from dataset to dataset. The values you're looking at are largely for plotting purposes (aligning the spots on top of the H&E stain). I'd recommend working directly from the spaceranger outputs if you'd like to get  spot positions in microns. You can first extract the positions of each barcode/spot in pixels from the `tissue_positions.csv`. Then, you can get the scaling factor from from the `spot_diameter_fullres` key in `scalefactors_json.json`. If that value is 80, then you can multiply all of your barcode positions by 65/80 to convert to microns.
