### ISSUE TITLE
Questions about confidence score in annotating query datasets

### ISSUE THREAD

**Issue by Kevis9** [satijalab/seurat#6981]
Hi! Thanks for the insightful and informative work! I am using Seurat v4 to annotate cells in query data based on reference data. I want to know how to get the confidence score of the predicted cell type.
Following code is what I am using now.
```
query <-  MapQuery(anchorset = reference.anchors, reference = reference.object, query = query.object,
    refdata = list(celltype = "type"), reference.reduction = "cca", reduction.model = "umap")
    pred = query$predicted.celltype
```

**Comment by yuhanH** [comment]
when you run `MapQuery`, the prediction score is calculated and stored in the object. 
In your case, it is called `query$predicted.celltype.score`
