### ISSUE TITLE
Error: Cannot find 'rpca' in this Seurat object

### ISSUE THREAD

**Issue by errcricket** [satijalab/seurat#6982]
I have a large single nuc. dataset (10X) with 4 experimental conditions and am following the vignette on integrating large datasets: [https://satijalab.org/seurat/articles/integration_large_datasets.html](url). I am having issues completing the pipeline with all the samples so I have restricted the analysis to 3 samples that come from different experimental conditions (~14K cells per sample). It was not clear how to deal with references when there are more than 2 experimental conditions [https://github.com/satijalab/seurat/issues/4889](url) so for the moment I have just ignored including references in the FindIntegrationAnchors command: I mention this not to solve the reference issue but in case this is somehow related to my stated error. 

I am encountering an error when running the `RunPCA` command; here is my code. 

```
transform_object_rpca <- function(S)
{
   SO.list <- SplitObject(S, split.by = 'Samples')
   
   SO.list <- lapply(X = SO.list, FUN = function(x) {
      x <- NormalizeData(x)
      x <- FindVariableFeatures(x)
   })  

   features <- SelectIntegrationFeatures(object.list = SO.list)

   SO.list <- lapply(X = SO.list, FUN = function(x) {
      x <- ScaleData(x, features = features, verbose = FALSE)
      x <- RunPCA(x, features = features, verbose = FALSE, approx=FALSE)
   })  

   SO.anchors <- FindIntegrationAnchors(object.list = SO.list, reduction = 'rpca', dims=1:compo)
   SO.integrated <- IntegrateData(anchorset = SO.anchors, dims=1:compo)
   SO.integrated <- ScaleData(SO.integrated, verbose = FALSE)
   SO.integrated <- RunPCA(SO.integrated)
}
```

And I get the following error:
```
Error: Cannot find 'rpca' in this Seurat object
Execution halted
```

A post suggested to `FindVariableFeatures` between `ScaleData` and `RunPCA`, however that just added new warnings (plus, the variable features gene names changed in the `@assays[["integrated"]]@var.features`):

Code...

```
SO.integrated <- FindVariableFeatures(object = SO.integrated) 
SO.integrated <- RunPCA(SO.integrated) 
```

or

```
SO.integrated <- FindVariableFeatures(object = SO.integrated) 
SO.integrated <- RunPCA(SO.integrated, features = VariableFeatures(object = SO.integrated), verbose = FALSE)
```

Error...
```
309   #Error: Cannot find 'rpca' in this Seurat object
310    #In addition: Warning messages:
311    # 1: In FindVariableFeatures.Assay(object = assay.data, selection.method = selection.method,  :
312    #   selection.method set to 'vst' but count slot is empty; will use data slot instead
313    # 2: In eval(predvars, data, env) : NaNs produced
314    # 3: In hvf.info$variance.expected[not.const] <- 10^fit$fitted :
315    #   number of items to replace is not a multiple of replacement length
```

I have checked my objects/variables at each step along the way and everything _seems_ correct and I have read through these posts: [https://github.com/satijalab/seurat/issues/3589](url), [https://github.com/satijalab/seurat/issues/5395](url), [https://github.com/satijalab/seurat/issues/1788](url), but have yet to find a solution and I am very stuck. Any assistance is greatly appreciated. 

Session info
```
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

Package: Seurat
Version: 4.3.0
Date: 2022-11-18
```

**Comment by yuhanH** [comment]
what step do you get error? `FindIntegrationAnchors ` or `IntegrateData `?

**Comment by errcricket** [comment]
The error is produced on the `   SO.integrated <- RunPCA(SO.integrated)` step.

**Comment by yuhanH** [comment]
Could you also show me the print message of this object? Thanks. 
`RunPCA` step doesn't depend on `rpca` in your object.

**Comment by errcricket** [comment]
Sure.

```
An object of class Seurat 
31477 features across 39526 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
```
<img width="755" alt="Screenshot 2023-02-25 at 2 48 39 PM" src="https://user-images.githubusercontent.com/4574607/221376738-93a4d468-7213-4189-acfa-0cd55889d1ae.png">

**Comment by errcricket** [comment]
!!!!! The code runs as expected. The part of the code I left out is after the above code and that was causing the error!!!

```
324    elbow_file <- paste(subdirectory1, '/', project, '_elbow_plot.pdf', sep='')
325    pdf(file=elbow_file, onefile=TRUE, width=11, height=8.5)
326    print(ElbowPlot(SO.integrated, ndims = compo, reduction = 'rpca'))
327    dev.off()
```

This is residual code for when I was using the standard integration approach (changed `rpca` to `pca` and the error was gone-o).  Many apologies, closing issue.
