### ISSUE TITLE
How to re-run SCTransform() to find variable genes without re-normalisation after subsetting?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6987]
Hi there, 

There has been various discussion regarding whether to re-normalize after subsetting a cell population that had been `SCTransform`. 

The consensus appeared to be no need to re-normalize the data because SCTransform normalises data on per-cell basis, but should re-run `SCTransform` to re-define the variable genes with do.scale=T, and do the clustering pipeline from `RunPCA` etc. 

But, would you mind informing me how to find variable genes with SCTransform without re-normalizing the data? Or, people still stick to `FindVariableFeatures` then `SelectIntegrationFeatures`?

Thank you for your help!

**Comment by saketkc** [comment]
The variable features in SCTransform workflow are determined based on their rank of residual variance. Whether you should re-run SCTransform on the sub-population of cells is context specific (and the variable features will change in the process) - you can use `VariableFeatures()`to obtain these.
