### ISSUE TITLE
ERROR When Installing Latest Seurat

### ISSUE THREAD

**Issue by h1hui** [satijalab/seurat#699]
Hi there,

I am working with a bio-linux. I used to have Seurat on my RStudio, but this time when I do 'library(Seurat)' it indicates that it is not installed so I figured I have to install again. I used 'install.packages('Seurat')' as indicated on the satijalab website but I got the following error message: 

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/minion/R/x86_64-pc-linux-gnu-library/3.4/hdf5r/libs/hdf5r.so':
  /home/minion/R/x86_64-pc-linux-gnu-library/3.4/hdf5r/libs/hdf5r.so: invalid ELF header
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/home/minion/R/x86_64-pc-linux-gnu-library/3.4/Seurat’
* restoring previous ‘/home/minion/R/x86_64-pc-linux-gnu-library/3.4/Seurat’
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status

Anyone knows what's going on? I have R version 3.4.4.

Thanks,
Ashley

**Comment by evolvedmicrobe** [comment]
Your hdf5r library appears to be corrupt.  I would try reinstalling it with `install.packages("hdf5r", type = "source")`.  Note that is may need hdf5 libraries on your system, which I'd be surprised if they weren't in biolinux, but just if needed you should try running this command at the terminal before attempting to install the package in R.

    sudo apt-get install libhdf5-dev

**Comment by h1hui** [comment]
Hello Evolvedmicrobe,

So I tried but it failed again. It seems that my version is too old. But then I tried the command line in the terminal, but still the same.

configure: error: The version of hdf5 installed on your system is not sufficient. Please ensure that at least version 1.8.12 is installed
ERROR: configuration failed for package ‘hdf5r’

**Comment by evolvedmicrobe** [comment]
So it looks like if you `sudo apt-get...` hdf5 on BioLinux (based on ubuntu 14.04), it installs the hdf5 version 1.8.11, whereas you need >= 1.8.12 (which is handed out for ubuntu 16, but not 14).

The simplest solution is perhaps to install a version of Seurat where the `hdf5` is optional.

    install.packages("devtools")
    library(devtools)
    install_github("HenrikBengtsson/seurat", ref="feature/hdf5r-optional")

**Comment by satijalab** [comment]
I'll second Nigel's response - but in future versions - we will ensure that hdf5 installation is not required from CRAN

**Comment by Chuxj** [comment]
> So it looks like if you `sudo apt-get...` hdf5 on BioLinux (based on ubuntu 14.04), it installs the hdf5 version 1.8.11, whereas you need >= 1.8.12 (which is handed out for ubuntu 16, but not 14).
> 
> The simplest solution is perhaps to install a version of Seurat where the `hdf5` is optional.
> 
> ```
> install.packages("devtools")
> library(devtools)
> install_github("HenrikBengtsson/seurat", ref="feature/hdf5r-optional")
> ```

Hello Evolvedmicrobe,

I tried your suggestion "install_github("HenrikBengtsson/seurat", ref="feature/hdf5r-optional")",
but it still didn't work. 


 During startup - Warning message:
   Setting LC_CTYPE failed, using "C" 
   checking for file '/tmp/RtmpjvmGjg/remotes951b4ae68158/HenrikBengtsson-seurat<U+221A>  checking for file '/tmp/RtmpjvmGjg/remotes951b4ae68158/HenrikBengtsson-seurat-f870542/DESCRIPTION'
-  preparing 'Seurat':
<U+221A>  checking DESCRIPTION meta-information
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'Seurat_2.3.4.tar.gz'
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into '/home/XXXXX/R/x86_64-pc-linux-gnu-library/3.4'
(as 'lib' is unspecified)
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) : 
  (converted from warning) installation of package '/tmp/RtmpjvmGjg/file951b375767c3/Seurat_2.3.4.tar.gz' had non-zero exit status

Do you have any idea on it?

Thx a lot!

**Comment by rich-green-aifimmunology** [comment]
I am getting the same error but this link appears dead

install_github("HenrikBengtsson/seurat", ref="feature/hdf5r-optional")

**Comment by rich-green-aifimmunology** [comment]
> install_github("HenrikBengtsson/seurat", ref="feature/hdf5r-optional")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref feature/hdf5r-optional

  Did you spell the repo owner (`HenrikBengtsson`) and repo name (`seurat`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by Chrisdoan9** [comment]
Hello all,

Would anyone please suggest a solution to this error? Thank you so much!

**Comment by mjstrumillo** [comment]
in answer to the discussion - if hdf5r is corrupted/doesnt install, make sure your conda has updated version of hdf5 
`conda install -c anaconda hdf5
`
that should eliminate *some* of the hdf5r bugs

**Comment by linklmath** [comment]
> conda install -c anaconda hdf5



> Hello all,
> 
> Would anyone please suggest a solution to this error? Thank you so much!

hi, Could you tell me what is going on?

**Comment by Chrisdoan9** [comment]
I am working on something else, and will let you know.
