### ISSUE TITLE
Why the cells clumped together in sct_ (vs rna_ RNA Assay) VlnPlots for merged CITE-seq object?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6991]
Hi there, 

I downloaded a publicly available CITE-seq dataset as Seurat object, which has a batch effect variable `gem_id`. 
I then subset the object to select T cells. 
My aim is to now integrate by gem_id with `harmony` and recluster based on RNA.

**QUESTION 1.** Would you mind helping me assess whether the workflow below makes sense?

**QUESTION 2.** Why the VnPlots below, especially PLOT 2 (sct_CD19 on SCT Assay) have the cells clump in a horizontal line and not spread out as in rna_CD19? Should I trust PLOT2 (only identified cluster 10) or PLOT3 (rna_CD18 on RNA Assay; identified many more clusters) given my workflow below? 

Thank you. 

```
Split the object by `gem_id` into individual gem_id datasets in a list

Perform `SCTransform` on the RNA assay for each datasets independently in this list
Merge the datasets in this list with `merge.data = T`
`SelectIntegrationFeatures` on SCT 
RunPCA on SCT
RunHarmony (pca) with `group.by.vars = "gem_id" on SCT
RunUMAP (harmony reduction)
FindClusters on SCT

PrepSCTFindMarkers on SCT

DefaultAssay() <- 'ADT'
Perform `NormalizeData` with (CLR, margin = 2) on ADT

###### Following steps were also done for WNN analysis, which should not interfere with the RNA-based clustering as SCT assays are specified before running VlnPlot ############
ScaleData()
RunPCA(apca)
RunHarmony(apca) with `group.by.vars = "gem_id" on ADT
Perform WNN integrated analysis with harmony reductions
###########################

```

**PLOT 1. adt_CD19 ADT** 
```
DefaultAssay(obj_MERGED) <- 'ADT'
VlnPlot(obj_MERGED, "adt_CD19", assay = 'ADT', group.by = "SCT_snn_res.2")
```

<img width="560" alt="Screenshot 2023-03-05 at 18 02 23" src="https://user-images.githubusercontent.com/62179082/222977653-fb8e09a8-f227-4c85-90a6-b5ea246c5990.png">

**PLOT 2. CD19 SCT** 
```
DefaultAssay(obj_MERGED) <- 'SCT'

VlnPlot(obj_MERGED, "sct_CD19", assay = 'SCT', group.by = "SCT_snn_res.2")
```

<img width="556" alt="Screenshot 2023-03-05 at 18 05 09" src="https://user-images.githubusercontent.com/62179082/222977763-5e8eff43-ee5f-42e2-b927-b808ce38f40a.png">

**PLOT 3. rna_CD19 RNA**
```
DefaultAssay(obj_MERGED) <- 'RNA'

VlnPlot(obj_MERGED, "rna_CD19", assay = 'RNA', group.by = "SCT_snn_res.2")
```

<img width="707" alt="Screenshot 2023-03-05 at 18 05 45" src="https://user-images.githubusercontent.com/62179082/222977793-edddbef4-04e8-4dd0-9230-dd738328f6f3.png">

Thank you for your help!

**Comment by saketkc** [comment]
The workflow makes sense. Did you run `NormalizeData` before doing the last visualization?

**Comment by denvercal1234GitHub** [comment]
Hi @saketkc, in my workflow, I did do
(1)`NormalizeData` on RNA assay after I split the object by `gem_id` into individual gem_id datasets in a list (because I wanted to calculate the cell cycle gene scores). 
(2) Then, I ensure`DefaultAssay` was set to `RNA` to perform `SCTransform` on the RNA assay for each datasets independently in this list. 
(3) Then, Merge the datasets in this list with `merge.data = T` etc as described above

**Comment by saketkc** [comment]
The median UMI for your subsetted cells is 1,203. By default `NormalizeData` uses a scale factor of 10,000. SCTransform uses the median number of UMI as the scale factor when calculating the corrected counts. The discrepancy between RNA and SCT vlnplots is because of this difference.

**Comment by denvercal1234GitHub** [comment]
I see. So if I want to investigate and to visualize which clusters showing the expression for a set of key genes, do you recommend to use RNA or SCT? Would it be more accurate to use SCT assay, but RNA looks better... Thanks @saketkc

**Comment by saketkc** [comment]
I would recommend using the SCT assay. I would also argue that the median UMI scale factor is more reasonable.

**Comment by denvercal1234GitHub** [comment]
Thank you so much, Saket!
