### ISSUE TITLE
Combining biological replicates

### ISSUE THREAD

**Issue by theoffice18** [satijalab/seurat#6992]
Hello,

I used the parse biosciences single nuclei platform. Within my run I had 8 uniquely barcoded samples. Samples were defined by number in the pipeline using the FASTQ files. This gave me one DGE matrix and one cell_meta file. Using the matrix and cell_meta file, I created one seurat object. Then I split them by experiment to account for batch effects since it was a different cohort and isolation was done on a different day. Samples were barcoded together in the same run. This gave me one integrated seurat object.

My goal now is to combine conditions 1&5 and conditions 3&7 into the same group. Within the meta data, the conditions still hold the sample name that was used during the pipeline. How can I combine these conditions once they've been integrated?

Thanks,
theoffice18

**Comment by longmanz** [comment]
Hi,
Not quite sure about what "combine these conditions" means. If you are referring to data integration, you may follow this tutorial: https://satijalab.org/seurat/articles/integration_introduction.html .
Or, if you are referring to changing the condition labels in your meta.data, you can create a new column in your meta.data that merges 1&5 and 3&7:
`seurat_obj$new_condition = seurat_obj$condition`
`seurat_obj$new_condition[seurat_obj$condition %in% c("cond1", "cond5")] = "cond1_5"` 
`seurat_obj$new_condition[seurat_obj$condition %in% c("cond3", "cond7")] = "cond3_7"`
