### ISSUE TITLE
Seurat 4.3.0 with spaceranger-2.0.0

### ISSUE THREAD

**Issue by Nitin123-4** [satijalab/seurat#6993]
Hi team,

I am not able to read the spatial data with Seurat 4.3.0. 

all.data <- Seurat::Load10X_Spatial(data.dir = prefix,
  filename = "filtered_feature_bc_matrix.h5",
  assay = "Spatial", # specify name of the initial assay
  slice = SampleID, # specify name of the stored image
  filter.matrix = TRUE,
  to.upper = FALSE
)

Where it is working with Seurat 4.1.0. 

Is there any change we need to do to make it working?
It has anything to do with spaceranger-2.0.1 i.e. new release?

**Comment by Nitin123-4** [comment]
It is working for Seurat 4.3.0 where Seurat 4.1.0 is looking for tissue_positions_list.csv file. 

I got the answer.

Thanks.

**Comment by yuhanH** [comment]
Thank you for solving this.
