### ISSUE TITLE
error when ues subset()

### ISSUE THREAD

**Issue by yanwuanxin** [satijalab/seurat#6995]
`p<-subset(x=pro,idents="CD8")`

Error in `[[<-`(`*tmp*`, dimreduc, value = tryCatch(expr = subset.DimReduc(x = x[[dimreduc]],  :
  [[<- defined for objects of type "S4" only for subclasses of environment

Seurat v3.2.3

**Comment by longmanz** [comment]
Hi,
It is hard to tell what caused the problem, but the answer from https://github.com/satijalab/seurat/issues/3964#issuecomment-768912470 seems to be able to fix it. 
Or you may update your Seurat to the latest version.
