### ISSUE TITLE
The visualization and data mining shows different story.

### ISSUE THREAD

**Issue by Chanukya-Pavan** [satijalab/seurat#6996]
Hi, 

I am new to seurat and have been learning it since past 4 months and use it for my scRNA seq analysis.

I followed the exact same pipeline mentioned online and have encountered some big issues, in this case my feature plot and violin plot of a gene gives one interpretation whereas the data acquired from FindAllMarkers, FindConserevedMarkers, FindMarkers and AverageExpression output data gives another, which in this case is quite opposite. So I got total confusion on what should I rely on to conclude.

Starting off, after PCA analysis 27 clusters have been identified and I have done it with integrating two datasets, so have two conditions, "Healthy" and "IPF". and I got data as follows:

1. **DE Genes for each cluster among condition**: Here I didn't want any comparison with other clusters, just wanted to know what are the DE genes among the condition in each cluster, so I used FindMarkers as follows -
`DE_genesfor_cluster0 <- FindMarkers(combined_integrated, ident.1 = "healthy", ident.2 = "ipf", subset.ident = 0, group.by = "condition")` 

2. **DE Genes of each cluster compared to others**: Here I wanted to know genes that are DE in one cluster compared to all others so I used FindAllMarkers as follows-
`combined_integrated.markers <- FindAllMarkers(combined_integrated, only.pos = TRUE)
All_markers <- combined_integrated.markers %>% group_by(cluster)
write.csv(All_markers, "marker_genes_integrated.csv")
`
3. **DE Genes of each cluster compared to others per condition**: Here I wanted to get genes that are DE per cluster based on condition, so I used FindConservedMarkers as follows-
`markers_for_cluster0 <- FindConservedMarkers(combined_integrated, ident.1 = 0, grouping.var = "condition")`

4. **All gene expression data per cluster**: Here I wanted to get all gene expression data, so I used AverageExpression with assay set to RNA as follows-
`all_genes <- AverageExpression(combined_integrated, slot = "data", assays = "RNA")
head(all_genes)
write.csv(all_genes, "All_genes_expressed_RNA")`

I was looking at the feature plots and violin plots of our genes of interest and have found this to be very contradicting. I searched for a Gene: MUC5AC in all of the above datasets for a specific cluster i.e. 4 to check whether this is unique to it and conclude it as marker, all of the searches shows that it was not found in any of the datasets (except all gene expression) which states, it is not DE in this cluster. However when I try to visualize it by using violin plot and feature plot as follows, it showed it is DE and unique to that cluster.

**Violin plot :**
`VlnPlot(combined_integrated, features = c("MUC5AC"), split.by = "condition", raster = F, combine = F, pt.size = 0.5, sort = F)`

![MUC5AC_violin](https://user-images.githubusercontent.com/112158036/222138476-568d426c-6ee4-4cce-8a71-0e66a39d7499.png)

**Feature Plot**
`FeaturePlot(combined_integrated, order = T, features = c("MUC5AC"), cols = c("gray80", "red"), raster = FALSE, label = T, split.by = "condition")
`

![MUC5AC_Feature](https://user-images.githubusercontent.com/112158036/222139021-d31bc311-23b7-47fd-b805-500677cea4e3.png)

This clearly show that it is DE in cluster 4 (along with 7), contradicting what I found from the output files of above codes. 

These are the output files of the above commands.

[marker_genes_integrated.csv](https://github.com/satijalab/seurat/files/10860944/Find_all_Markers.csv) - FindAllMarkers

[markers_for_cluster4.csv](https://github.com/satijalab/seurat/files/10860949/FindConservedMarkers_for_cluster4.csv) - FindConservedMarkers

[DE_genesfor_cluster4.csv](https://github.com/satijalab/seurat/files/10860953/FindMarkers_cluster4.csv) - FindMarkers

Please let me know if I missed something or have interpreted something in a wrong way and help me in this issue.

Thanks,
Chanukya

**Comment by longmanz** [comment]
Hi,
The 3 files you uploaded are missing for some reasons. To answer your question in general, yes, the MUC5AC looks like a real DE gene. But there are a few things you need to make sure:
1. When you run FindMarkers() or related DE functions, you should always specify the assay to "RNA" (or SCT if you use SCTransform() ), i.e., `FindMarkers(..., assay = "RNA")`. Using "integrated" assay is not appropriate for DE test. See more discussion here:  https://github.com/satijalab/seurat/issues/5881 and https://github.com/satijalab/seurat/issues/1717 .
2. If you are using the correct assay but still get missing genes (e.g., not being reported in your FindMarkers() results), you can lower your logfc.threshold threshold to include more genes in your DE test. Some genes might get excluded simply due to their log-fold change not being high enough.
