### ISSUE TITLE
Issue with Heatmap

### ISSUE THREAD

**Issue by Chanukya-Pavan** [satijalab/seurat#6997]
Hi,

I was trying to visualize using a heatmap, but I encountered an error saying:
"Warning: [38;5;232mRemoved 26 rows containing missing values (`geom_text()`).[39m"

The command I used was `DoHeatmap(combined_integrated, features = c("WT1", "TP63", "SLC40A1", "KRT7"), cells = 200, assay = "integrated")`. I tried looking up in online but have got no help so far. 

Could you help me out in this.

Thanks,
Chanukya

**Comment by longmanz** [comment]
Hi,
When you use the "cells = " flag, you should input a vector of cell IDs, instead of a number (e.g., 200). If you only want 200 cells being plotted, you can randomly extract IDs of 200 cells from your data and input that to "cells = ".

**Comment by Chanukya-Pavan** [comment]
> Hi, When you use the "cells = " flag, you should input a vector of cell IDs, instead of a number (e.g., 200). If you only want 200 cells being plotted, you can randomly extract IDs of 200 cells from your data and input that to "cells = ".

I removed "cells = " command and tried, this time it showed no error but the output was blank. What command would you suggest to use for the requirement I have

**Comment by longmanz** [comment]
Hi,
How many cells do you have in your dataset? If there are too many cells, you may still consider shrink it down to 200 or 500 for visualization.
