### ISSUE TITLE
Can't download the allen_cortex.rds

### ISSUE THREAD

**Issue by Seraph-009** [satijalab/seurat#6999]
https://www.dropbox.com/s/cuowvm4vrf65pvq/allen_cortex.rds?dl=1

I tried to download the allen_cortex.rds many times, however, I cannot download the data successfully.
Could you be kind to upload the data in the Github?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What error are you getting when you try to download the file?  I just checked and have no issues downloading the file.  Have you tried from different network/machine?

Best,
Sam

**Comment by saketkc** [comment]
The download seems to be working fine. It might have been an intermittent issue at the dropbox end (can you check if dropbox.com is not blocked on your network)
