### ISSUE TITLE
..beyond 2 group comparisons..

### ISSUE THREAD

**Issue by lenz99-** [satijalab/seurat#700]
I am involved in a gene expression analysis based on a single cell sequencing experiment.
We have two groups (`A` and `B`, say) – with each subject of a group measured repeatedly at different time points (`A1` and `A2` for subjects of group A and `B1` and `B2` in group B, say).
The research questions is to find genes that show a specific expected expression pattern across the four groups A1, A2, B1 and B2. It is thus more complex than just a non-paired two-group comparison.

In the vignette documentation around `FindMarkers` I have seen only examples involving two groups.
Does Seurat currently allow to specify more than 2 groups for gene expression comparison and are repeated measures of cells from same subject at different time point supported?
Can you advice an approach?

Thanks for your help. -m

**Comment by satijalab** [comment]
You can use FindConservedMarkers - which runs and agglomerates the results from multiple pairwise DE tests. You can see an example of this in our stimulated/control PBMC vignette (for example, identifying markers of NK cells in both stimulated and unstimulated cells), which is similar to your question regarding multiple timepoints

**Comment by nhyda** [comment]
Does FindConservedMarkers can find markers in data with 3 groups or more. The vignette say it is for 2 groups
