### ISSUE TITLE
Parallel FindMarkers with Future

### ISSUE THREAD

**Issue by weshorton** [satijalab/seurat#7000]
Hello,

I am a beginner in terms of parallel computing in R and am trying to run FindMarkers() using the framework described in the [vignette](https://satijalab.org/seurat/articles/future_vignette.html). I'm actually trying to use FindAllMarkers(), but my issue appears with both of them. After setting the plan and running my code, I check out my cores using htop and find that only one core is being used.

```
> availableCores()
system 
    24 

> plan("multisession")
> plan()
multisession:
- args: function (..., workers = availableCores(), lazy = FALSE, rscript_libs = .libPaths(), envir = parent.frame())
- tweaked: FALSE
- call: plan("multisession")

clusters_v <- levels(seurat_object)
test <- FindMarkers(seurat_object, 
                                   ident.1 = clusters_v[1], 
                                   ident.2 = clusters_v[-1],
                                   only.pos = F,
                                   test.use = "MAST",
                                   latent.vars = "batchID"

### OR
# test <- FindAllMarkers(seurat_object, only.pos = F, test.use = "MAST", latent.vars = "batchID")

```

Looking at htop, I see this:

<img width="956" alt="Screen Shot 2023-03-01 at 1 10 59 PM" src="https://user-images.githubusercontent.com/16656587/222266035-14f83fbf-c768-4c4a-9f7a-1c2807241fda.png">

The function call does seem to be running faster than previously, but I feel like I should be seeing usage on other cores instead of just the one. Any comments, links to resources, etc. are appreciated!

**Comment by AustinHartman** [comment]
The MAST differential expression method is unfortunately not configured to run in parallel. If you try a different method (like `test.use = "wilcox"`) you should see more cores used

**Comment by ppm1337** [comment]
I would like to add to this discussion that the [current vignette](https://satijalab.org/seurat/articles/future_vignette) proves that the parallelization is not working any more. The default `test.use = "wilcox"` with 4 workers in the example has no speedup according to the [plot in the vignette](https://satijalab.org/seurat/articles/future_vignette_files/figure-html/viz.compare-1.png):

![](https://satijalab.org/seurat/articles/future_vignette_files/figure-html/viz.compare-1.png)

In an [archived vignette](https://satijalab.org/seurat/archive/v3.1/future_vignette.html), the same example showed a considerable speedup with 4 workers:

![Untitled](https://github.com/satijalab/seurat/assets/24212727/75fec06d-1c09-48ea-8921-c71aebcda8b9)

**Comment by ishwarvh** [comment]
Would like to add that parallelization seems to have broken when using the future package within RStudio.  
Neither specifying "multisession" nor "multicore" has any effect on the number of cores used. All the previously parallelized functions run on only a single core!
