### ISSUE TITLE
10X data contains more than one type and is being returned as a list containing matrices of each type.

### ISSUE THREAD

**Issue by jimmyuab** [satijalab/seurat#7001]

**Comment by jimmyuab** [comment]
> setwd("E:/single2022/analysis_results_individual_samples")
> setwd("E:/single2022/analysis_results_individual_samples/DB_HM_TAC/filtered_feature_bc_matrix")
> SRR780<-Read10X(data.dir = "E:/single2022/analysis_results_individual_samples/DB_HM_TAC/filtered_feature_bc_matrix/")
10X data contains more than one type and is being returned as a list containing matrices of each type.

**Comment by samuel-marsh** [comment]
Hi,

can you please describe what issue you are having?

Best,
Sam

**Comment by jimmyuab** [comment]
Thanks ,
I am working on Single cell sequencing data.
 SRR780<-Read10X(data.dir = "E:/single2022/analysis_results_individual_samples/WT_Chow_Sham/filtered_feature_bc_matrix/")
10X data contains more than one type and is being returned as a list containing matrices of each type.
Warning message:
In for (i in seq_len(n)) { :
  closing unused connection 3 (../SRR10_outs/filtered_feature_bc_matrix/)
> SRR780[1:5,1:5]
Error in SRR780[1:5, 1:5] : incorrect number of dimensions

**Comment by jimmyuab** [comment]
I read data 10X,
-Read10X(data.dir = "E:/single2022/analysis_results_individual_samples/WT_Chow_Sham/filtered_feature_bc_matrix/")
10X data contains more than one type and is being returned as a list containing matrices of each type.
same file type as filtered_feature_bc_matrix/

**Comment by jimmyuab** [comment]
**10X data contains more than one type and is being returned as a list containing matrices of each type.**
I have no idea how to solve this problem

**Comment by jimmyuab** [comment]
HI peers,
I'm trying to load 10X data with the required types: barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz; but there was a message saying "10X data contains more than one type and is being returned as a list containing matrices of each type".

**Comment by Gesmira** [comment]
Hi, as mentioned in [issue #5849](https://github.com/satijalab/seurat/issues/5849), this is likely due to the fact that your data actually does contain multiple assay types. I see you asked for the specific link that had been referenced there, which is now at this address: [https://stuartlab.org/signac/articles/pbmc_multiomic.html](https://stuartlab.org/signac/articles/pbmc_multiomic.html)

Let me know if this helps!

**Comment by jimmyuab** [comment]
Hi,
I am a new user of R. Thanks for your help, I will work on it over time.


Jianli Zhao M.D

Assistant Professor

Director of Physiological Core of Animal Models

Department of Biomedical Engineering

UAB School of Medicine

Volker Hall G094E

1670 University BLvd, Birmingham,AL35233

***@***.***

________________________________

**Comment by jimmyuab** [comment]
Thank you for this link, it was very helpful to me in more ways than I expected.


Jianli Zhao M.D

Assistant Professor

Director of Physiological Core of Animal Models

Department of Biomedical Engineering

UAB School of Medicine

Volker Hall G094E

1670 University BLvd, Birmingham,AL35233

***@***.***

________________________________

**Comment by Gesmira** [comment]
Great, no problem!
