### ISSUE TITLE
Set unhighlighted spots to transparent in SpatialDimPlot()

### ISSUE THREAD

**Issue by cf98** [satijalab/seurat#7005]
Hi Seurat team & user community,

I am trying to use SpatialDimPlot() to highlight specific cells on visium H&E images. However, when I use cells.highlight to set the group of cells, I do get these cells highlighted, but the unselected cells appear as white and covers the tissue. I tried to alter alpha setting, however, it also changes the transparency of my selected cells.

Is it possible to set the unselected cells to transparent, so that I can see the tissue underneath? 
![Screen Shot 2023-03-02 at 2 34 05 PM](https://user-images.githubusercontent.com/78611089/222545551-c2ed714b-752b-434d-b9d6-5a84aa05a0ec.png)

Thanks,
Changfeng

**Comment by alikhuseynov** [comment]
set `alpha = NULL`
```
eg 
pl1 <- 
  SpatialPlot(object, 
              cells.highlight = Cells(object)[1:100], # just first 100 spots
              cols.highlight = c("red", "gray10"),
              image.alpha = 1, 
              alpha = NULL,
              pt.size.factor = 1.6)
```
check `cols.highlight` as well for custom colors

**Comment by cf98** [comment]
> 

Thank you so much!! It works!
Just curious if you know any other parameters will allow setting different alpha values for highlighted vs unselected cells?

Changfeng

**Comment by alikhuseynov** [comment]
glad that it helped :)
you can set the alpha value for the "Unselected" spots

```
eg
alpha.set <- 0.2 # custom alpha value
pl1 <- 
  SpatialPlot(object, 
              cells.highlight = Cells(object)[1:100], # just first 100 spots
              cols.highlight = c("red", alpha("gray10", alpha.set)),
              image.alpha = 1, 
              alpha = NULL, 
              pt.size.factor = 1.6)
```

**Comment by cf98** [comment]
> glad that it helped :) you can set the alpha value for the "Unselected" spots
> 
> ```
> eg
> alpha.set <- 0.2 # custom alpha value
> pl1 <- 
>   SpatialPlot(object, 
>               cells.highlight = Cells(object)[1:100], # just first 100 spots
>               cols.highlight = c("red", alpha("gray10", alpha.set)),
>               image.alpha = 1, 
>               alpha = NULL, 
>               pt.size.factor = 1.6)
> ```

Thank you!
