### ISSUE TITLE
 Error: Cannot find 'pca' in this Seurat

### ISSUE THREAD

**Issue by singcell** [satijalab/seurat#7008]
It is recommended to use RPCA reduction when running `FindIntegrationAnchors` on large dataset by Seurat authors. However when I do this, I get error

> Error: Cannot find 'pca' in this Seurat

What should I do to get rid of this error? should I run RunPCA before `FindIntegrationAnchors` and `ScaleData`? In this case when should I use `DefaultAssay`
Would it not change any outcome?

Thank you

**Comment by alikhuseynov** [comment]
difficult to answer without your code. It tells that you don't have or didn't run PCA on you object(s)

**Comment by longmanz** [comment]
Hi, 
Please run RunPCA() before you do RPCA based integration. Please set your DefaultAssay to the correct assay (the assay you run your RunPCA() ). 
You may follow the tutorial here (https://satijalab.org/seurat/articles/integration_rpca.html).
