### ISSUE TITLE
trying to reproduce paper data; problem with subsetting

### ISSUE THREAD

**Issue by mocherry** [satijalab/seurat#7009]
Dear all,

quite new to R I try to reproduce results from a 2017 sc paper.
The code runs o.K. up to this step:
scNuc2 <- readRDS("data/scNuc2.rds")
ex.clusters <- grep("^Ex", levels(scNuc2@ident), value = T, ignore.case = T)
use.cells <- names(scNuc2@ident[scNuc2@ident %in% ex.clusters])  # 15353 nuclei
scNuc2.ex <- SubsetData(scNuc2, cells.use = use.cells)

and is obviously related to the "SubsetData".

I have learned that this has been replace in newer versions. Alas, I cannot fire out to formulate the subsetting correctly.

Help would be greatly appreciated.

Best,
Matthias

**Comment by longmanz** [comment]
Hi,
Subsetting a Seurat object can be achieved by "subset()". If you are using Seurat v4, then you should be able to run the following to get your subset:
`scNuc2.ex <- subset(scNuc2, cells = use.cells)`
