### ISSUE TITLE
Average Expression function output units

### ISSUE THREAD

**Issue by mooreann** [satijalab/seurat#701]
I've been using the AverageExpression function to look at the comparative expression of genes throughout some of my clusters and then have plotted those values with a heatmap. I've noticed though that the expression scale changes depending on what I'm plotting (IE I've gotten expression measurements from -2 to 2 and -0.4 to 0.4). Does anyone know if this is on a log scale, or how does AverageExpression calculate these values/ what are the units?

**Comment by mojaveazure** [comment]
Please see the "Value" section of the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/AverageExpression) for `AverageExpression`

**Comment by mooreann** [comment]
That just tells me the output is a matrix, I'm wondering what are the units of the numbers within the output matrix.
