### ISSUE TITLE
Error specifying "cells = " in DoHeatmap

### ISSUE THREAD

**Issue by lschachtner** [satijalab/seurat#7010]
I'm trying to use the DoHeatmap function to look at gene expression for specific treatments/clusters using the "cells = " parameter. However, when I specify which cells I want to plot it returns an error.

Here's the line of code I'm using to specify which cells based on treatment metadata.

`DoHeatmap(LTS127.singlet, cells = LTS127.singlet$treatment == "Untreated")`

"Error in names(group.use) <- cells : 
  'names' attribute [11815] must be the same length as the vector [1879]"

I understand that there are 11815 total cells in my Seurat object and 1879 cells that are "Untreated", I'm just not sure what I need to do to get around this issue.

**Comment by longmanz** [comment]
Hi,
Please specify a vector of cell IDs instead of a Boolean vector with "cells = ". 
`DoHeatmap(LTS127.singlet, cells = colnames(LTS127.singlet)[LTS127.singlet$treatment == "Untreated"])`

**Comment by lschachtner** [comment]
I figured I was making a novice mistake. 

Thank you for your help!
