### ISSUE TITLE
Should we run NormalizeData() function before using FindAllMarkers() or FindMarkers() in an integrated object?

### ISSUE THREAD

**Issue by ChrisTzaferis** [satijalab/seurat#7011]
Hi Seurat dev team and thank you for the development of such a useful R package!

I have a question regarding the usage of FindMarkers or FindAllMarkers functions after performing integration analysis.
Following the vignette https://satijalab.org/seurat/archive/v3.0/immune_alignment.html and reading a previous discussion https://github.com/satijalab/seurat/issues/3397 I was wondering if it's advised to run NormalizeData() on the RNA assay before proceeding with the two previously mentioned functions? By trying both options (using or not using NormalizeData), I have noticed that the output columns of p_val, pct.1, pct.2, p_val_adj remain the same in both cases, however a different value of avg_logFC is returned.
Is this normal? 

Thank you in advance!
(My Seurat version is 4.2.0.999.)

**Comment by longmanz** [comment]
Hi, 
If you are using the default setting of NormalizeData(), all the reads will be normalized by "LogNormalize" method ("Feature counts for each cell are divided by the total counts for that cell and multiplied by the scale.factor. This is then natural-log transformed using log1p."). Integration has no impact on the LogNormalize step. So whether you run NormalizeData() before or after integration, you should have the same values for the same gene in the same cell in you RNA assay ('data' slot). You can check this by looking at the seurat_obj@assays$RNA@data.
I am not sure why avg_logFC is different while others are the same. Please make sure you are using the RNA assay in your FindMarkers() step. Is it possible for you to provide us a reproducible example of this issue?

**Comment by ChrisTzaferis** [comment]
Thank you for your response! I totally agree with your explanation and this is also the behavior I would expect, however using the IFNB dataset provided here: https://satijalab.org/seurat/articles/integration_introduction.html I faced the same issue with the avg_LogFC value. Despite of the differences in the FC values, the normalized expression of GNLY gene in a random cell is the same in both cases, as expected. Could you try the following code and check if you get the same issue with the avg_LogFC? 
Thank you!

```{r}
#--------------------------IFNB dataset-----------------------------------------
library(Seurat)
library(SeuratData)
library(patchwork)

set.seed(1)
# load dataset
LoadData("ifnb")

# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.list <- SplitObject(ifnb, split.by = "stim")

# normalize and identify variable features for each dataset independently
ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = ifnb.list)

immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)
# this command creates an 'integrated' data assay
immune.combined <- IntegrateData(anchorset = immune.anchors)

# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)

# Visualization
p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2

DefaultAssay(immune.combined) <- "RNA"
FeaturePlot(immune.combined, features = c("GNLY", "FGFBP2", "CLIC3", "PRF1"), label = T)

cluster6_Markers <- FindMarkers(immune.combined, ident.1 = "6", base = exp(1), min.pct = 0.25, assay = "RNA")
cluster6_Markers$gene <- rownames(cluster6_Markers)

#use NormalizeData() after integration
immune.combined_ND <- NormalizeData(immune.combined)
cluster6_Markers_NormData <- FindMarkers(immune.combined_ND, ident.1 = "6", base = exp(1), min.pct = 0.25, assay = "RNA")
cluster6_Markers_NormData$gene <- rownames(cluster6_Markers_NormData)

#Check the normalized expression in a random cell
immune.combined@assays$RNA@data["GNLY", "AAGAGATGACGCTA.1"] 
immune.combined_ND@assays$RNA@data["GNLY", "AAGAGATGACGCTA.1"]
```

**Comment by longmanz** [comment]
Hi, 
Thank you for sharing an example on this issue. However, it seems that I cannot reproduce the issue (I tried with v4.1.1 and v4.3.0). The avg_logFC are consistent before and after normalization from my end:
<img width="646" alt="Screen Shot 2023-03-06 at 10 57 46 AM" src="https://user-images.githubusercontent.com/8408639/223164357-9698be9b-9ace-4998-99f2-eb76e3f4f52b.png">

Could you please share the different avg_logFC you obtained with us?

**Comment by ChrisTzaferis** [comment]
Thank you for your quick response! In the following image you can see my output using the same commands from the image you have shared.
![image](https://user-images.githubusercontent.com/66067062/223172571-eba9e625-cca5-4b62-8119-a83ab3ac55d8.png)

Could it be a version specific issue? I will definitely try the new v4.3.0.

**Comment by ChrisTzaferis** [comment]
I have found this post https://github.com/satijalab/seurat/issues/6586 and reading also the section for the bugs fixed in the Version 4.3.0 https://github.com/satijalab/seurat/releases, I guess that it's probably the same issue.

**Comment by longmanz** [comment]
Hi, 
You are right! Sorry for not realizing it earlier. Thanks for pointing that out.

**Comment by ChrisTzaferis** [comment]
Thank you, everything works as expected with v4.3.0!
