### ISSUE TITLE
Manually change cell type

### ISSUE THREAD

**Issue by FraMont1** [satijalab/seurat#7012]
Hello Seurat team,

Thanks for developing Seurat, this is an amazing tool.
I am analyzing two datasets of the same organ in two different species (A-B).
Initially I analyzed the two species separately. For both species I annotated the cell types. 
Then I integrated them using one2one orthologues. After the clustering of the integrated dataset some cells which in the species A belong to a cell type (smooth muscle cells) now cluster with epithelial cells in the species B.
Is it correct to manually select these cells and change their cell type?
Thank you for the answer.
Best,
Francesco

**Comment by mhkowalski** [comment]
Hello, 

I recommend checking for expression of marker genes that you trust for both cell types in this population and assess if you think they are smooth muscle or epithelial cells.

**Comment by saketkc** [comment]
You can use a combination of manually derived and supervised labels as long as the assigned labels recapitulate canonical markers for these celltypes.
