### ISSUE TITLE
CalcPerturbSig(): Parameters Value

### ISSUE THREAD

**Issue by acharyasant7** [satijalab/seurat#7013]
Hi, I have three conditions in my data (control and two mutants). I want to calculate pertubation scores for each mutant against control. Can I do that using CalcPerturbSig(). 
What parameters should I include in gd.class and nt.cell.class and split.by?

**Comment by longmanz** [comment]
Hi, 
In the gd.class you should specify the column name for your "conditions" in your meta-data, and nt.cell.class should be set to the label name of your "control" group in your "conditions". You probably do not need to use split.by if all your cells are from single cell type. If not, you might consider use split.by to specify your "cell.type" in your meta-data.
