### ISSUE TITLE
Why data scale.data do not contain marker genes of some clusters? 

### ISSUE THREAD

**Issue by emkahuda** [satijalab/seurat#7014]
I run pre-processing steps for the single cell data provided here https://satijalab.org/seurat/articles/pbmc3k_tutorial.html. Let say the seurat object variable is data_scRNA.  Using ScaleData() function, which is by default, results 2000 genes by checking data_scRNA@assays$RNA@scale.data. The problem is when trying to plot heatmap by 

DoHeatmap(data_scRNA, features = top10$gene, label = FALSE) + theme(axis.text=element_text(size=4))

I got the error

The following features were omitted as they were not found in the scale.data slot for the RNA assay: MEG3, RORB, COL3A1, S100A6, RAMP1, PTN, DCN, CFD, IGF1, PTGDS, CALD1

I have checked that these are marker genes of a specific cluster (top10), but not found in scale.data. How is it possible that the marker genes are not found in scale.data? How to solve this issue? 

Thank you.

**Comment by alikhuseynov** [comment]
are those marker among the Variable Features? ie, after you run `FindVariableFeatures()`

**Comment by emkahuda** [comment]
Nope, I used the argument feature. = 2000 by default, and the genes MEG3, RORB, COL3A1, S100A6, RAMP1, PTN, DCN, CFD, IGF1, PTGDS, CALD1 of top10$gene are not found in the list obtained from FindVariableFeatures(). That is why it is confusing. Is there an away to solve it?

**Comment by alikhuseynov** [comment]
I'm not from Seurat team...
but, you can increase `nfeatures = 3000` and see if any of your markers will there. There might be different reasons why those markers are not picked up as variable features in your dataset.
In `ScaleData()` you can pass the vector of genes to `features`, that should work, else it takes the variable features.

**Comment by emkahuda** [comment]
Yes, I tried it already. It only works when I use all genes as features in FindVariableFeatures(), although it should not be necessary to pick up high variable genes, but I guess there is a cluster that does not have strong marker compared to others, maybe.

**Comment by alikhuseynov** [comment]
The Differential Gene Expression analysis with `FindAllMarkers()` should give you some feeling which clusters have your top markers. 
In DoHeatmap() use the slot = "data", then the markers will be there.

**Comment by mhkowalski** [comment]
Closing as the solution mentioned above works. To view markers in a heatmap, they must be within the scale.data slot. As mentioned above you can manually specify which genes you would like to scale by using the `features` argument of `ScaleData()`.
