### ISSUE TITLE
Error in CreateSeuratObject: object 'pbmc.data' not found

### ISSUE THREAD

**Issue by Sloe-Johnson** [satijalab/seurat#7016]
Hi! I am trying to get the tutorial going, but I am encountering a problem I don't understand. 
I have this code 
`library(dplyr)
library(Seurat)
library(patchwork)

#load the PBMC dataset 
dir_data <- '.../BrCa_Atlas_Count_out'
pmbc.data <- Read10X(data.dir = dir_data)

# Initialise the Seurat Object with the raw, non-normalised data
pbmc <- CreateSeuratObject(counts = pbmc.data, project = 'pbmc3k', min.cells = 3, min.features = 200)
pbmc `

With this code I get the error " Error in CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3,  : 
  object 'pbmc.data' not found" but I don't understand why. Is it a code or a data problem?

**Comment by yuhanH** [comment]
could you double check if your downloaded data is in this directory: ` '.../BrCa_Atlas_Count_out'`

**Comment by saketkc** [comment]
Closing this as we haven't heard back. Please open a new issue if you are still facing issues.
