### ISSUE TITLE
SplitDotPlotGG change/include color palette

### ISSUE THREAD

**Issue by MichaelStreuber** [satijalab/seurat#702]
Hi,

I am using an aligned data (two datasets). I know how to change the color for these two datasets in a SplitDotPlot, but I would like to change the color palette for both and not just include it like this:

SplitDotPlotGG(effector.subsets, genes.plot = rev(markers.to.plot), 
                      cols.use = c(c("red", "blue")), x.lab.rot = T, plot.legend = T, 
                      dot.scale = 15, do.return = T, grouping.var = "treated")

Here the min expression always starts in grey but I would like that it starts e.g. in black and go to red the more genes are expressed.

I know that there is the RColorBrewer function, but I didn't manage to create a palette and include it in the command above to change the color from black to red or from black to blue.

I tried the commands below to creat two color palettes.

pal <- colorRampPalette(c("black", "red"))
# Just return black and red
pal(10)
#[1] "#000000" "#1C0000" "#380000" "#550000" "#710000" "#8D0000" "#AA0000" "#C60000" "#E20000" "#FF0000"

pal2 <- colorRampPalette(c("black", "blue"))
# Just return black and blue
pal2(10)
# [1] "#000000" "#00001C" "#000038" "#000055" "#000071" "#00008D" "#0000AA" "#0000C6" "#0000E2" "#0000FF"

Then I included them into my command but it didn't work:

sdp <- SplitDotPlotGG(effector.subsets, genes.plot = rev(markers.to.plot), 
                      cols.use = c(pal(10), pal2(10)), x.lab.rot = T, plot.legend = T, 
                      dot.scale = 15, do.return = T, grouping.var = "treated")

Does anyone see my mistake or have experience with RColorBrewer?

Best,
Michael

**Comment by satijalab** [comment]
We include a CustomPalette function where you can specify a low, medium, and high color - returning a continuous gradient.

If you want a discrete gradient, you shouldn't need RColorBrewer, but can create your own vector containing only "black", and "blue", for example
