### ISSUE TITLE
AddMetadata

### ISSUE THREAD

**Issue by OnkarMulay** [satijalab/seurat#7021]
The AddMetadata function removes the image from the seurat object. Thanks

```r
# insert reproducible example here
GX1A1 <- AddMetaData(GX1A1,GX1A1_Annotation)

```

**Comment by nathan-nakatsuka** [comment]
Dear OnkarMulay, could you provide more information about your Seurat Object and more details about what image is being removed?

**Comment by saketkc** [comment]
Closing this as we haven't heard back. Please feel free to reopen if your issue is still unresolved.
