### ISSUE TITLE
Subcluster including other cell types

### ISSUE THREAD

**Issue by bio-lilin** [satijalab/seurat#7023]
Hello!
After cell annotation, I extracted the tumor cell subset and further performed the cell subset analysis, but I found that the subset contained immune cells. Can I directly delete these immune cells? Thank you!

**Comment by Gesmira** [comment]
Hi, if you have a cluster of immune cells, you can create a new column in the metadata with the new cell types and label the immune cells. Then, you can again subset out the tumor cells. 

```
object$celltype.new <- "tumor"
object@meta.data[list_of_immune_cells,  ]$celltype.new <- "immune"
tumor <- subset(object, subset = celltype.new == "tumor") 
```

**Comment by bio-lilin** [comment]
Thank you for your reply, I will readjust the cell annotation.
