### ISSUE TITLE
vlnplot change title of multiple plots

### ISSUE THREAD

**Issue by obrien-james** [satijalab/seurat#7024]
Hi, 

Is there a way to change the titles of the vlvplots if you select multiple features, this would typically generate a single plot with multiple vlnplots. 

For example, VlnPlot(pbmcs, features=c("CD19", "MS4A1", "CD27"), pt.size=0, ncol=3)

This would generate 3 vlnplots next to each other, each with a titles of CD19 | MS4A1 | CD27 
I would like to be able to rename the plot MS4A1 to CD20 

Hope this makes sense

James

**Comment by alikhuseynov** [comment]
something like that:
```
markers <- c("CD19", "MS4A1", "CD27")
pl_vln <- VlnPlot(pbmcs, features = markers, pt.size = 0, ncol = 3, 
combine = FALSE # returns list of plots
)
names(pl_vln) <- markers
pl_vln$MS4A1 & ggtitle("CD20")
```

**Comment by obrien-james** [comment]
Thanks, 

This works great. 

Is it possible to apply a theme to the whole list of plots rather than individually. 

I.e. theme(axis.title.x = element_blank(), axis.title.y = element_blank()) ?

**Comment by alikhuseynov** [comment]
yes, using a loop or `lapply()`
`lapply(pl_vln %>% seq, function(i) { pl_vln[[i]] & theme(axis.title.x = element_blank(), axis.title.y = element_blank()) })`

**Comment by mhkowalski** [comment]
I agree with what was said above, you should create a list of plots and can then modify them using lapply or a for loop.
