### ISSUE TITLE
Help with pre-processing, percent.mt step

### ISSUE THREAD

**Issue by svashisht89** [satijalab/seurat#7026]
Hello, I am new to code and Seurat. I am having issues with obtaining percent.mt - my 4 datasets give the same message: All cells have the same value of percent.mt (0). I am wondering if my file was formatted correctly or if gene names are being detected in my Seurat Object. Do I have to rename something? currently my data matrix looks like this for each experiment (not Seurat Object) and here is a sample code I am using to turn it into SeuratObject and obtain percent.mt (image and code are from different datasets - just giving you the general idea)

<img width="1097" alt="Screen Shot 2023-03-07 at 10 59 50 AM" src="https://user-images.githubusercontent.com/127227867/223477537-9ff8e186-39dc-401a-b40c-df79ca311617.png">

TSV<-CreateSeuratObject(counts = BaselTSV)
TSV
#An object of class Seurat, 40196 features across 5432 samples within 1 assay, Active assay: RNA (40196 features, 0 variable features)

TSV[["percent.mt"]]<-PercentageFeatureSet(TSV, pattern = "^MT-")
head(TSV@meta.data,10)
#has some NAs in first row introduced by coersion, need to remove
TSV.norm<-subset(TSV, subset = nCount_RNA !="NA")
head(TSV.norm@meta.data,10)
VlnPlot(object= TSV.norm, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),ncol=3)
#In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :All cells have the same value of percent.mt.

**Comment by saketkc** [comment]
You need to read the first column as rownames when importing the counts:

```
counts <- read.csv("xx.tsv", row.names=1)
object <- CreateSeuratObject(counts = counts)
# perform percent.mt calculation here
```

Additionally you can check if your dataset has mitochondrial genes defined by doing:

```
grep("^MT-", rownames(counts), value=T)
```
