### ISSUE TITLE
Memory corruption when running IntegrateData

### ISSUE THREAD

**Issue by RoseString** [satijalab/seurat#7027]
Dear Seurat developers, 

I ran into the following error during ```IntegrateData(anchorset = anchors)``` run:
```*** Error in `/sw/apps/R/4.1.1/rackham/lib64/R/bin/exec/R': malloc(): memory corruption: 0x00000011858a4660 ***```

The overall memory usage (dotted black line) peaked at 200GB, while I had a max of 478.5GB. I already set R_MAX_VSIZE=500Gb in ~/.Renviron, so I'm not sure what went wrong. I'd really appreciate any input!

```
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 16 15 8 11 3 5 13 4 12 10 2 9 1 14 6 7 35 34 20 into 31 28 33 24 27 23 25 36 18 30 29 17 32 26 19 21 22
Extracting anchors for merged samples
Finding integration vectors
*** Error in `/sw/apps/R/4.1.1/rackham/lib64/R/bin/exec/R': malloc(): memory corruption: 0x00000011858a4660 ***

```
![bianca-sens2022006-dasun-3905](https://user-images.githubusercontent.com/7266414/223552483-6a4436d2-b618-441c-84e6-2108cb9f2f96.png)

**Comment by alikhuseynov** [comment]
not from the Seurat team.. but it looks like you have a lot of samples/subsets that are getting merged. Not sure but could be that. I saw sometime ago similar errors when working with lots of samples..
How large is your dataset, cells, genes, samples etc..?

**Comment by keggleigh** [comment]
Hi,

Posting here as I'm having a similar issue. Also not sure what went wrong - has a solution been found to this? Thank you!

Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 16 17 7 15 into 5 12 9 1 8 2 11 13 6
Extracting anchors for merged samples
Finding integration vectors
Error in subCsp_rows(x, i, drop = drop) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: IntegrateData ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows

Job efficiency:
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 64
CPU Utilized: 03:33:23
CPU Efficiency: 1.56% of 9-12:18:08 core-walltime
Job Wall-clock time: 03:34:02
Memory Utilized: 244.59 GB
Memory Efficiency: 16.56% of 1.44 TB

**Comment by alikhuseynov** [comment]
your datasets are very large [see this discussion](https://www.biostars.org/p/9521477/#9521480)
also related #3650
What integration approach are you using? For large datasets it's better to use [RPCA](https://satijalab.org/seurat/articles/integration_rpca.html)

**Comment by alikhuseynov** [comment]
how many cells and genes?

**Comment by keggleigh** [comment]
Also using rpca method, trying to integrate 17 datasets with a combined total of ~380,000 cells and ~26000 genes

**Comment by alikhuseynov** [comment]
it should be possible.. there are atlases the have more cells than that.
[Azimuth - Lung](https://azimuth.hubmapconsortium.org/references/#Human%20-%20Lung%20v2%20%28HLCA%29)
[Azimuth - Heart](https://azimuth.hubmapconsortium.org/references/#Human%20-%20Heart)

**Comment by keggleigh** [comment]
Hi @RoseString - I found a solution and managed to integrate the data. I had to reduce the k.anchors parameter and when I ran it at the default, which I believe is 5, seurat was able to integrate the data.

**Comment by Gesmira** [comment]
Hi, 
Thank you to others who gave suggestions here. We also recommend checking out [Seurat v5 for large-scale analyses](https://satijalab.org/seurat/articles/get_started_v5.html). The on-disk computation capabilities ([example here](https://satijalab.org/seurat/articles/parsebio_sketch_integration)) would be helpful in cases where memory is a concern.
