### ISSUE TITLE
Different results of FindMarkers in version 4.0.1 vs. 4.2.0

### ISSUE THREAD

**Issue by KNGrimstad** [satijalab/seurat#7028]
Hi, 
I have been working on a project for a couple of years, and originally ran FindMarkers (as well as FindAllMarkers) with Seurat version 4.0.1 (along with all other, original analyses), comparing to clusters, and identified 94 significantly upregulated genes with the settings used (see below). I recently reran the same analysis, with the same dataset (originally processed with version 4.0.1) with the latest version (4.2.0) of Seurat, and ended up with only some 60 significantly upregulated genes. 

The parameter settings used were the same, namely FindMarkers(seurat.object, ident.1 = "2", ident.2 = "3", min.pct = 0.25, only.pos = T, test.use = "wilcox"). I have browsed through the changes listed for the updates of Seurat since 4.0.1, but have yet to find a reason for the discrepancy, so I was wondering if there is something that I have missed in this regard that may explain why the results are different given the same parameters.  

Thanks in advance!

**Comment by saketkc** [comment]
We fixed the issues with FindMarkers in Seurat 4.3: https://github.com/satijalab/seurat/releases/tag/v4.3.0. Please consider updating and feel free to reopen if you still notice issues.
