### ISSUE TITLE
How do you remove rows with infinite numbers from Seurat object?

### ISSUE THREAD

**Issue by prakashraaz** [satijalab/seurat#7029]
I'm trying to create a Violinplot of a seurat object
VlnPlot(samp1, features =  "nCount_RNA")

I get the following
Warning message:
Computation failed in `stat_ydensity()`
Caused by error in `seq.int()`:
! 'to' must be a finite number 

I get what looks like an empty plot.

The data type of nCount_RNA is numeric.

Afterwards, when I try to find variable features with 
samp1 <- FindVariableFeatures(samp1, selection.method = "vst", nfeatures = 2000)

I get the following error
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  NA/NaN/Inf in foreign function call (arg 1)

What is causing this error? And how do I remove the rows with NA/NaN/Inf, if that is what is causing the error?
Thank you in advance.

**Comment by prakashraaz** [comment]
Update:
I did try these to fix it which didn't work
samp1 <- samp1[!is.infinite(rowSums(samp1)),]
samp1 <- samp1[!is.nan(rowSums(samp1)),]
samp1 <- samp1[!is.na(rowSums(samp1)),]

**Comment by alikhuseynov** [comment]
I suggest to do some sanity checks before you create seurat obj, ie count matrix, gene and cell names.
And afterwards. update the object `samp1 %<>% UpdateSeuratObject()`
Also, no NA/NAN/etc.. in `nCount_RNA` and `nFeature_RNA`. eg `any(pbmc_small$nCount_RNA %>% is.na)` (same for NaN `is.nan()`) if it returns`TRUE` then check which are NAs `which(!pbmc_small$nCount_RNA %>% is.na)` 
hope this helps

**Comment by saketkc** [comment]
Can you elaborate on how the object was created? You can ensure all genes are detected in at least one cell and all cells have at least one feature by doing this at the creation step:

```
object <- CreateSeuratObject(counts=samp1, min.features=1, min.cells=1) 
```
