### ISSUE TITLE
Genes subset

### ISSUE THREAD

**Issue by france-hub** [satijalab/seurat#7030]
Hello Seurat team!

Thanks for this package. 
I am trying to delete a gene from my Seurat object, recluster and maintain the idents. The cluster annotation before my gene removal is in a metadata column labeled clusters.2. I looked into old issues, but I want to ask about the output I get. I am able to subset but in the end the UMAP plots with/without the gene of interest are very similar (weird right?). 

```
#remove WT1 transgene and recluster
counts <- GetAssayData(CD8, assay = "integrated")
counts <- counts[-(which(rownames(counts) %in% c('WT1-transgene'))),]
CD8_noWT1 <- subset(CD8, features = rownames(counts))

#verify the WT1-transgene is removed
"WT1-transgene" %in% VariableFeatures(CD8)
"WT1-transgene" %in% VariableFeatures(CD8_noWT1)

DefaultAssay(CD8_noWT1) <- "RNA"
CD8_noWT1 <- FindVariableFeatures(CD8_noWT1, selection.method = "vst", 
                            nfeatures = 2000, 
                            verbose = FALSE)
# Scale the counts in the integrated assay
DefaultAssay(CD8_noWT1) <- "integrated"
CD8_noWT1 <- ScaleData(CD8_noWT1)
# Run PCA and UMAP
CD8_noWT1 <- RunPCA(CD8_noWT1)
CD8_noWT1 <- RunUMAP(CD8_noWT1, dims = 1:30, verbose = FALSE)
# Plot the elbow plot
ElbowPlot(object = CD8_noWT1, ndims = 30)
# Determine the K-nearest neighbor graph
CD8_noWT1 <- FindNeighbors(object = CD8_noWT1, dims = 1:20)
# Determine the clusters for various resolutions                                
CD8_noWT1 <- FindClusters(object = CD8_noWT1, resolution = c(0.4, 0.6, 0.7, 0.8, 0.9, 1.0,1.2))
# set cluster IDs to resolution 0.4 clustering
CD8_noWT1 <- SetIdent(CD8_noWT1, value = "integrated_snn_res.0.4")
#Plot UMAP
DefaultAssay(CD8_noWT1) <- "RNA" #Put "RNA" as default assay
CD8_noWT1@active.ident <- CD8_noWT1$clusters.2 %>% factor()
p.1 <- DimPlot(CD8) + ggtitle("WT1tg_in")
p.2 <- DimPlot(CD8_noWT1) + ggtitle("WT1tg_out")
rownames(CD8_noWT1)[1]
rownames(CD8)[1]
plot_grid(p.1, p.2)

```
Here are the plots:
![Rplot01](https://user-images.githubusercontent.com/56587709/223823507-2cc554da-bf62-4399-8866-cfe4e4e64bfe.png)
What am I missing?

**Comment by nathan-nakatsuka** [comment]
Dear france-hub, there are several possibilities for this. Usually deleting a single gene shouldn't change the UMAP very much unless it is a gene with very high variability that differentiates the clusters a lot. What is this WT1-transgene? It is possible also that the gene of interest is not a variable feature and therefore has very little to no effect on the UMAP.

**Comment by yuhanH** [comment]
hi @france-hub 
It depends on if `WT1-transgene` is in your VariableFeatures. We only use variable features to perform PCA analysis, UMAP visulization, clustering. If `WT1-transgene` is not in VariableFeatures of your object, it makes sense that umap doesn't change after you delete it.

**Comment by france-hub** [comment]
WT1-transgene is in VariableFeatures. I solide by removing the gene before the integration step of the workflow. Thanks for your help!

**Comment by yuhanH** [comment]
hi @france-hub 
I see. There are some small differences in those two umaps. It may result from the small feature loading of `WT1-transgene` in your PCA space. 
You can find the feature loadings of WT1-transgene by `CD8[['pca']]@feature.loadings[WT1-transgene,]`
