### ISSUE TITLE
How do I calculate mean fold log change in FindConservedMarkers?

### ISSUE THREAD

**Issue by dekan-aleksandr** [satijalab/seurat#7031]
Hello!

I checked many questions, but it is still not clear to me. 

How do I denormalize log2FC output of FindMarkers (FindConservedMarkers)? 
I need raw FC values to calculate mean FC values. 
Thank you!

I've found that you're using pseudocounts and log2. 

Let's say I have two samples. After running FindConservedMarkers I get log2FC for a gene X equal to 0.62 and 0.74.

Then I raise them to the power of 2, take the mean, and subtract one. Is this right?

**Comment by alikhuseynov** [comment]
to convert `log2FC` to `FC`, you need to raise the base to the `log2FC` values. Eg `2^0.62` gives the `FC`, then you can subtract the pseudocount value.

**Comment by dekan-aleksandr** [comment]
Oh, I see. Thank you!
 I was worried that using pseudocounts could bias the results.
