### ISSUE TITLE
UMAP legend labels and colors don't match highlighted cells

### ISSUE THREAD

**Issue by LBH2021** [satijalab/seurat#7033]
I'm trying to highlight my top N VDJ clones on my GEX UMAP plot and am very close to the plot I want with the following code:

# Get the top N most frequent clonotypes
top_clonotypes <- names(sort(table(immune.combined@meta.data$clonotype_id), decreasing = TRUE))[1:10]

# Assign a unique color to each clonotype
colors <- rainbow(length(top_clonotypes) + 1)

# Create a list of row names for each clonotype
highlight_rows_clonotype <- lapply(top_clonotypes, function(c) {
  row.names(immune.combined@meta.data)[immune.combined@meta.data$clonotype_id == c]
})

# Plot the umap with each clonotype highlighted in a different color
DimPlot(immune.combined,
        reduction = "umap",
        group.by = "clonotype_id",
        cells.highlight = highlight_rows_clonotype,
        order = highlight_rows_clonotype,
        cols.highlight = colors,
        sizes.highlight = 0.1) +
  scale_color_manual(values = colors, labels = top_clonotypes)

Which gives the following plot:

<img width="742" alt="Screen Shot 2023-03-09 at 6 25 46 PM" src="https://user-images.githubusercontent.com/118935557/224207534-bd6a0803-ea29-4795-8cf2-662e0bb5e991.png">

The problem is that the legend labels and colors don't match the corresponding clonotype. For example: what is labeled as clonotype1 should actually be NA and should not be highlighted (ideally grey) and the actual clonotype1 is what is labeled as NA. I think part of the problem is that the "cells.highlight" argument calls a list of row names (i.e. the corresponding cell barcodes) I defined called "highlight_rows_clonotype" but this isn't directly linked to the corresponding clonotype IDs. I think there should be a way to get this to work but I've tried multiple solutions and can't seem to figure it out. Any help would be greatly appreciated. Thank you!

**Comment by alikhuseynov** [comment]
The problem is in `scale_color_manual()` since it does not recognize "Unselected" cells as NA.
Eg, I tried to reproduce it on `pbmc_small` object, take a look probably it will work in you case too.
```
top_clonotypes <- names(table(pbmc_small$RNA_snn_res.1) %>% sort(decreasing = TRUE))[1:2] # first 2 clusters
colors <- rainbow(length(top_clonotypes) + 1)
highlight_rows_clonotype <- 
  lapply(top_clonotypes %>%, function(c) {
  Cells(pbmc_small)[which(pbmc_small$RNA_snn_res.1 == c)]
})
highlight_rows_clonotype %>% str
# run UMAP
pbmc_small %<>% RunUMAP(reduction = "pca", dims = c(1:10))
pl1 <- 
  DimPlot(pbmc_small,
        reduction = "umap",
        pt.size = 0.5,
        group.by = "RNA_snn_res.1",
        cells.highlight = highlight_rows_clonotype,
        order = highlight_rows_clonotype,
        cols.highlight = colors,
        sizes.highlight = rep(2, highlight_rows_clonotype %>% length()), # make highlighted cells larger
        )
pl1 # this should work as default to show "Unselected" or NA cells
# change "Unselected" to NA
pl1$data$highlight[which(pl1$data$highlight == "Unselected")] <- NA
# plot again with custom colors and labels.
pl1 & scale_color_manual(values = colors, label = top_clonotypes)
```

**Comment by LBH2021** [comment]
Thank you very much for your reply! Your solution helped to prevent the cells I don't want to highlight from being highlighted. However, the legend labels and colors still do not match the correct cells on the UMAP plot. Below is an example:

UMAP plot from "pl1 <- DimPlot(immune.combined..."

<img width="591" alt="Screen Shot 2023-03-10 at 9 58 44 AM" src="https://user-images.githubusercontent.com/118935557/224389775-5639a5a1-a90f-4134-9cf9-2c77554e3ad3.png">

In the above plot, the labels are correct in the sense that Group_1 is the most abundant clonotype, Group_2 is the next most abundant clonotype, etc. However, for publication, I want the labels in the legend to reflect the actual clonotype IDs.

When I use "pl1 & scale_color_manual(values = colors, label = top_clonotypes)" to rename the labels, I get the following plot:

<img width="594" alt="Screen Shot 2023-03-10 at 10 04 24 AM" src="https://user-images.githubusercontent.com/118935557/224390670-4886310b-4ccf-4bac-a04f-ef59f4066dee.png">

In this second plot, the highlighted cells that should be "clonotype1" are now labeled as "clonotype47". To double check the identity of the highlighted cells, I made a plot in which only "clonotype1" is highlighted:

<img width="592" alt="Screen Shot 2023-03-10 at 10 07 55 AM" src="https://user-images.githubusercontent.com/118935557/224391283-80d0f998-54a0-4917-b046-c8581b4e83c9.png">

As you can see in this final plot, the labels change depending on the number of VDJ clones I plot instead of corresponding with the actual clonotype IDs.

I have included my full updated code below based on your first response in case it helps. Thank you again for helping me to solve this problem.

top_clonotypes <- names(table(immune.combined@meta.data$clonotype_id) %>% sort(decreasing = TRUE))[1:1]

colors <- rainbow(length(top_clonotypes) + 1)

highlight_rows_clonotype <- lapply(top_clonotypes, function(c) {
  row.names(immune.combined@meta.data)[immune.combined@meta.data$clonotype_id == c]
})

pl1 <- DimPlot(immune.combined,
          reduction = "umap",
          pt.size = 0.5,
          group.by = "clonotype_id",
          cells.highlight = highlight_rows_clonotype,
          order = highlight_rows_clonotype,
          cols.highlight = colors,
          sizes.highlight = rep(2, highlight_rows_clonotype %>% length())) # make highlighted cells larger

pl1 # this should work as default to show "Unselected" or NA cells

# change "Unselected" to NA
pl1$data$highlight[which(pl1$data$highlight == "Unselected")] <- NA

# plot again with custom colors and labels.
pl1 & scale_color_manual(values = colors, label = top_clonotypes)

**Comment by yuhanH** [comment]
hi @LBH2021 
`DimPlot` sometimes cannot handle NA value properly. The easiest way is to replace NA with "na" characters. 
If the variable is factor, you need to convert it to characters and then replace NA to "na".

**Comment by LBH2021** [comment]
Hello @yuhanH
Thank you for your help. The variable was already a factor. I changed NA to "na" but this did not fix the problem. Would you give me an example of how the above code could be modified to fix the problem? Any additional help is greatly appreciated. Thank you again!
