### ISSUE TITLE
sc-RNAseq question

### ISSUE THREAD

**Issue by suanzaoren** [satijalab/seurat#7035]
Hi there,
I'm trying to read an h5 file from a published data set (available on GEO accession GSM4453632), using the Read10X_h5 function, but keep getting the following error.
>       Read10X_h5('molecule_info.h5')
Error in x$exists(name) : HDF5-API Errors:
    error #000: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5L.c in H5Lexists(): line 824: unable to get link info
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #001: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5L.c in H5L_exists(): line 2765: path doesn't exist
        class: HDF5
        major: Symbol table
        minor: Object already exists

    error #002: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Gtraverse.c in H5G_traverse(): line 861: internal path traversal failed
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #003: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Gtraverse.c in H5G_traverse_real(): line 596: can't look up component
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #004: D:/a/rtools-packages/r

appreciated if you could give me some advice!
Thanks
Zerun Song

**Comment by nathan-nakatsuka** [comment]
Dear @suanzaoren, the GEO data does not have the counts matrix (it is only the molecular info). Probably you have to email them to ask them to upload the actual count matrix:
See here for more info: https://www.bioinformatics.babraham.ac.uk/training/10XRNASeq/10X_Introduction.pdf
page 14

**Comment by suanzaoren** [comment]
Thanks for  nathan,it's essential for me that the information you produce.It let me reduce a large of vain.
