### ISSUE TITLE
Trouble with finding cluster markers

### ISSUE THREAD

**Issue by ClaudCampos** [satijalab/seurat#7037]
Hello,

I've ran my analysis and plotted the clusters. After this stage, I'm trying to find markers for the different clusters, following the Seurat tutorial. I have done this previously, with very nice results. I didn't change any version of my packages.
However, I'm running the analysis on a new set of data, to see the different genes expressed in each cluster with the usual code, but I keep retrieving the same list, regardless of how unrelated the clusters are. 
Has anyone been through the same issue? If so, what was done to solve it?
Thanks!
The code and results are below.
Claudia

**cluster0.markers <- FindMarkers(il20k_k, ident.1 = 1, min.pct = 0.25)
head(cluster0.markers, n = 5)
cluster1.markers <- FindMarkers(il20k_k, ident.1 = 1, min.pct = 0.25)
head(cluster1.markers, n = 5)
cluster10.markers <- FindMarkers(il20k_k, ident.1 = 1, min.pct = 0.25)
head(cluster10.markers, n = 5)**

> cluster0.markers <- FindMarkers(il20k_k, ident.1 = 0, min.pct = 0.25)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
> head(cluster0.markers, n = 5)
                                                            p_val avg_log2FC pct.1 pct.2 p_val_adj
LOC113219418-uncharacterized-LOC113219418                       0 -0.8014375 0.998 0.992         0
LOC100576540-vacuolar-protein-sorting-associated-protein-27     0 -0.8786735 0.994 0.993         0
CSP3-chemosensory-protein-3                                     0 -0.7676400 1.000 1.000         0
LOC113218735-uncharacterized-LOC113218735                       0 -0.8451671 0.999 0.999         0
LOC725380-chymotrypsin-inhibitor                                0 -0.7627248 0.999 0.999         0
> cluster1.markers <- FindMarkers(il20k_k, ident.1 = 0, min.pct = 0.25)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
> head(cluster1.markers, n = 5)
                                                            p_val avg_log2FC pct.1 pct.2 p_val_adj
LOC113219418-uncharacterized-LOC113219418                       0 -0.8014375 0.998 0.992         0
LOC100576540-vacuolar-protein-sorting-associated-protein-27     0 -0.8786735 0.994 0.993         0
CSP3-chemosensory-protein-3                                     0 -0.7676400 1.000 1.000         0
LOC113218735-uncharacterized-LOC113218735                       0 -0.8451671 0.999 0.999         0
LOC725380-chymotrypsin-inhibitor                                0 -0.7627248 0.999 0.999         0
> cluster10.markers <- FindMarkers(il20k_k, ident.1 = 0, min.pct = 0.25)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
> head(cluster10.markers, n = 5)
                                                            p_val avg_log2FC pct.1 pct.2 p_val_adj
LOC113219418-uncharacterized-LOC113219418                       0 -0.8014375 0.998 0.992         0
LOC100576540-vacuolar-protein-sorting-associated-protein-27     0 -0.8786735 0.994 0.993         0
CSP3-chemosensory-protein-3                                     0 -0.7676400 1.000 1.000         0
LOC113218735-uncharacterized-LOC113218735                       0 -0.8451671 0.999 0.999         0
LOC725380-chymotrypsin-inhibitor                                0 -0.7627248 0.999 0.999         0

**Comment by saketkc** [comment]
```
cluster0.markers <- FindMarkers(il20k_k, ident.1 = 1, min.pct = 0.25)
head(cluster0.markers, n = 5)
cluster1.markers <- FindMarkers(il20k_k, ident.1 = 1, min.pct = 0.25)
head(cluster1.markers, n = 5)
cluster10.markers <- FindMarkers(il20k_k, ident.1 = 1, min.pct = 0.25)
head(cluster10.markers, n = 5)
```

From the code above it seems you are always passing `ident.1=1` instead of 0,1, and 10 respectively.
