### ISSUE TITLE
A question regarding genes input

### ISSUE THREAD

**Issue by medinih** [satijalab/seurat#704]
Hello,
I want to use Seurat in order to analyze scRNA-seq data, and cluster cells by mitochondrial genes. can I use Seurat with mitochondrial genes only (non-nuclear genes)?

another question is, what is the smallest data set of cells one can use in Seurat?

Thank you,
Hadar.

**Comment by satijalab** [comment]
We don't recommend this but if you have a specific reason to do so - you can cluster only on mitochondrial genes. Just use these genes as input for the PCA step. 

There is no minimum cell size to use in Seurat. However, graph-based clustering methods tend to perform poorly with small numbers of cells (<100 or so).
