### ISSUE TITLE
How should I fix the error "inner loop 1; cannot correct step size"?

### ISSUE THREAD

**Issue by pariaaliour** [satijalab/seurat#7041]
Hi Seurat team,
I am trying to do the DEG analysis using FindMarkers function and below is the code.

![image](https://user-images.githubusercontent.com/52675953/224522538-e6dcb636-86ed-4571-9c58-04bf9d362e71.png)

I am not sure why I'm getting the below error 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': (subscript) logical subscript too long
I appreciate your help on this.
Thanks,
Paria

**Comment by mhkowalski** [comment]
Hi, 

Which line of code do you get the error at?

**Comment by mhkowalski** [comment]
Closing because of lack of response, please open a new issue if you'd like additional help.
