### ISSUE TITLE
Using FindNeighbors to build a SNN graph for generic numerical matrix

### ISSUE THREAD

**Issue by timmocking** [satijalab/seurat#7044]
Hi all,

I'm trying to build a shared-nearest neighbor graph in either Python and/or R. I noticed that in my own implementation, I can do the nearest-neighbor calculation quite fast, but looping over all neighbors for a point remains intensive. 

I wanted to try Seurat's implementation, to see if its faster. So my input is a general numerical matrix, and I'm trying to process it using Seurat. 

```
mat <- read.csv('example.csv')

obj <- CreateSeuratObject(counts = mat)

my_seurat_obj <- FindNeighbors(obj, 
                               k.param=10,
                               reduction=NULL,
                               prune.snn=3/10,
                               nn.eps=0)
```

I get the following error:
```
Warning: The following arguments are not used: prune.snn
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "data.frame"
```

The same error can easily be reproduced with the pbmc dataset:

```
pbmc_raw <- read.table(
  file = system.file('extdata', 'pbmc_raw.txt', package = 'Seurat'),
  as.is = TRUE)

pbmc_small <- CreateSeuratObject(counts = pbmc_raw)

pbmc_small <- FindNeighbors(obj, 
                            k.param=10,
                            reduction=NULL,
                            prune.snn=3/10,
                            nn.eps=0)
```

I'm probably missing some required structure in the object, but I can't figure out what it is?

**Comment by yuhanH** [comment]
hi @timmocking 
If you want to use `FindNeighbors` for assay, you need to set dims to NULL. 
```
pbmc_small <- FindNeighbors(pbmc_small, dims = NULL, k.param = 30)

```
