### ISSUE TITLE
When creating a Seurat object using metadata,  values become NA，warning message:In matrix(data = as.numeric(x = x), ncol = nc) : NAs introduced by coercion

### ISSUE THREAD

**Issue by Asdust-HW** [satijalab/seurat#7045]
Hello, I am new to code and Seurat.
When I create a Seurat object using the metadata obtained in geo, it is forced to turn to be NA ,only these columns remain:orig.ident；nCount_RNA；nFeature_RNA and nCount_RNA；nFeature_RNA turn to be NA.
The warning message:In matrix(data = as.numeric(x = x), ncol = nc) : NAs introduced by coercion

The code is as follows

`if(!require(multtest))install.packages(("multtest"))
if(!require(Seurat))install.packages(("Seurat"))
if(!require(dplyr))install.packages(("dplyr"))
if(!require(patchwork))install.packages(("patchwork"))
if(!require(R.utils))install.packages(("R.utils"))
library(dplyr)
library(Seurat)
library(patchwork)`

`humankidney_sc.data<-read.table("GSE210622_metadata.txt",comment.char = "#",sep = "",fill=TRUE,na.strings = "",quote="",row.names=NULL)
humankidney_sc <- CreateSeuratObject(counts = humankidney_sc.data , project = "humankidney_sc")
head(humankidney_sc@meta.data,10)`

![image](https://user-images.githubusercontent.com/127836650/225000557-323faa4b-613d-4f66-9ad9-bbc52b13d788.png)

**Comment by alikhuseynov** [comment]
I'm not from the Seurat team.. but try to use `data.table::fread()` and make sure that your `humankidney_sc.data` is matrix-like object or a sparse matrix

**Comment by samuel-marsh** [comment]
Hi,

The issue appears to be that you are creating Seurat object using meta data.  When using `CreateSeuratObject` you need to supply a counts matrix to the `counts` parameter.  

Best,
Sam

**Comment by samuel-marsh** [comment]
Meta data can be added either during the `CreateSeuratObject` using `meta.data` parameter or by using `AddMetaData` after object creation.

Also while it won't hurt you may want to filter out the nCount and nFeature columns from metadata you downloaded as those will be populated automatically during object creation and no need to duplicate them.

**Comment by Asdust-HW** [comment]
> 



> 我不是修拉团队的人。但尝试使用并确保你的 是类似矩阵的对象或稀疏矩阵`data.table::fread()``humankidney_sc.data`

Thanks for the advice! I'm trying to convert this to a sparse matrix

**Comment by Asdust-HW** [comment]
> 


First of all, thank you for your answer. Let me try to modify it
> 


> 

First of all, thank you for your answer. Let me try to modify it

**Comment by Asdust-HW** [comment]
> 元数据可以在 using 参数期间添加，也可以在创建对象后使用 添加。`CreateSeuratObject``meta.data``AddMetaData`
> 
> 此外，虽然它不会有什么坏处，但您可能希望从您下载的元数据中过滤掉 nCount 和 nFeature 列，因为它们将在对象创建期间自动填充，无需复制它们。

First of all, thank you for your answer. Let me try to modify it

**Comment by saketkc** [comment]
@Asdust-HW Your `humankidney_sc.dat` needs to be a matrix. You should see a matrix when you looka the first 5 rowas and columns like this:
```
> humankidney_sc[1:5, 1:5]
```
