### ISSUE TITLE
Differential Expression of Cluster that only Appears in 1 Condition

### ISSUE THREAD

**Issue by codeneeded** [satijalab/seurat#7047]
scRNAseq was performed over 6 samples, 3 control, and 3 comparisons. After integration, I changed the default assay to RNA, and used the FindMarkers function to look at the differences in clusters between Comparison and control conditions. To do this I first split my seurat object by cluster using the splitobject function and then looked at it by condition using the FindMarkers function, with the conditions being labled in the metadata.

This works when the cluster is present in both control and comparison condition. However, if I have cluster x present in the disease condition and not in control, how would I look for differential expression?

Current code

```
### Split seurat by ident.
SeuratObject_splitlist_i <- SplitObject(test, split.by = "ident")

### assign identity as condition (for control vs comparison conditions)
for (i in 1:length(SeuratObject_splitlist_i)) {
  Idents(SeuratObject_splitlist_i[[i]]) <- "condition" }

### For loop finding markers of control vs comparison for each cluster and writing to .csv file.
for (i in 1:length(SeuratObject_splitlist_i)) {
  g.name<- names(SeuratObject_splitlist_i)[i]
  dif_genes <- FindMarkers(SeuratObject_splitlist_i[[i]], ident.1 = 'Condition', ident.2= 'Control', min.pct=0.25,
                           logfc.threshold=0.05)
  write.csv(dif_genes, file = paste0(g.name,"_Comparison_vs_Control.csv"))
}
```
If the cluster only exists in one condition, then Findmarkers cannot run as ident.2='Control' in findmarker function won't exist.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I’m little confused about your question.  You’re asking how to run things of cluster only exists in one condition?  If there is cluster that only exists in one condition then there is no reason to run differential expression because there is no comparison that can be made.

Bezt,
Sam

**Comment by Gesmira** [comment]
@samuel-marsh is right. If you are trying to find differentially expressed genes between disease and control, then cells from that cluster would have to be present in both conditions.

As an alternative, if you are just interested in the expression of this cluster compared to all other cells, you can set the `Idents()` as the cell types and run FindMarkers for that specific cluster. However, this will not give you information about how this expression compares in disease vs. control.
