### ISSUE TITLE
Multiple multi-omics samples

### ISSUE THREAD

**Issue by zji90** [satijalab/seurat#7049]
Hi,

I would like to integrate multiple multi-omics (RNA+ATAC) samples using Seurat. It seems that there is no existing pipeline to do this. So will it be an acceptable practice if I first integrate RNA and ATAC separately across samples, and then use WNN to integrate the two PCAs that have already been integrated across samples?

**Comment by yuhanH** [comment]
hi @zji90 
You are right. Here is a similar issue https://github.com/satijalab/seurat/issues/5346
