### ISSUE TITLE
Average Expression function output units

### ISSUE THREAD

**Issue by mooreann** [satijalab/seurat#705]
I've been using the AverageExpression function to look at the comparative expression of genes throughout some of my clusters and then have plotted those values with a heatmap. I've noticed though that the expression scale changes depending on what I'm plotting (IE I've gotten expression measurements from -2 to 2 and -0.4 to 0.4). Does anyone know if this is on a log scale, or how does AverageExpression calculate these values/ what are the units?

Note: the value section of the documentation for AverageExpression only tells me the output is a matrix, of which I can tell. I'm looking for the actual units of the numerical values within the output matrix.

**Comment by satijalab** [comment]
Your question is primarily about the data used in DoHeatmap - which is the @scale.data slot. This stores z-scored expression values, for example, those used as PCA.

Cells with a value > 0 represent cells with expression above the population mean (a value of 1 would represent cells with expression 1SD away from the population mean). Hope that helps!

**Comment by ideascidata** [comment]
The original title of this thread is my exact question, so I'm asking it again here. 

I've been using the AverageExpression function and noticed that the numbers that are computed are substantially different than simply taking the row mean for each gene in the object@data matrix (even when averaging in non-log space). 

I see the documentation says that output is in non-log space and averaging is done in non-log space. I thought this would be log2, but perhaps not? 

Thanks for your help

**Comment by andrewwbutler** [comment]
Hi,

The relevant lines of code can be found [here](https://github.com/satijalab/seurat/blob/aafba71530ae5bfd602eea380b8b45f0062580ad/R/utilities.R#L227-L277). If you're averaging the `data` slot, this should amount to running `mean(expm1(x))` over each row (gene).

**Comment by ideascidata** [comment]
Perfect- thanks so much,
Aaron
