### ISSUE TITLE
different clustering results using same version of Seurat in different version of R (4.2.2 and 4.0.5)

### ISSUE THREAD

**Issue by RosycloudsRan** [satijalab/seurat#7051]
Recently, I found that, different clustering results were obtained using same data，same version of seurat with same parameters but in different versions of R (4.2.2 and 4.0.5).

Could you please tell me what led to the different clustering results???

**Comment by saketkc** [comment]
Closing this as we haven't heard back. Please feel free to reopen if your issue is still unresolved.
