### ISSUE TITLE
Question about doublets filtering

### ISSUE THREAD

**Issue by sanderslhc** [satijalab/seurat#7052]
Hi,

I'm using the Doubletfinder to filter the doublets in my research. In this step, I used all genes to perform PCA and set the PCs as 1:10 because I want to preserve more information of each cell and this PCs range won't lead to many noises. Do you think this is reasonable?

Best
Houcheng

**Comment by yuhanH** [comment]
hi @sanderslhc 
I think this question is more relevant to Doubletfinder package. You would suggest you post this issue in their repo.
