### ISSUE TITLE
Atomic Sketch Integration approach. No longer supported?

### ISSUE THREAD

**Issue by Victor21v** [satijalab/seurat#7053]
Hi,

I would like to try the Atomic sketch integration for scRNA-seq data tutorial for my datasets (https://satijalab.org/seurat/articles/atomic_integration.html). However, I have seen vignette is removed from Github. Does it mean it is no longer recommended to use this approach for integration?

Thanks in advanced

**Comment by yuhanH** [comment]
Hi,
Sorry for the mistake. The vignette is back now.
