### ISSUE TITLE
Merging more than two seurat objects

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#706]
Is there a way to merge 4 seurat objects? 
MergeSeurat is for two objects. I know that there is also AddSamples but this add a sample without creating a Seurat Object, my point is that I have 4 dataset, I want to create a Seurat object for each so I can filter the cells for each object then merge them all together. is there a way to do that?
Thank you all

**Comment by mschilli87** [comment]
@EDYAC: see https://github.com/satijalab/seurat/issues/207, https://github.com/satijalab/seurat/issues/239 & https://github.com/satijalab/seurat/issues/601 :wink:

**Comment by Dragonmasterx87** [comment]
Everyone has got to stop quoting other pages where this answer is not discussed. It is an excellent question that requires an appropriate explanation, especially for non-computational-fools like myself which took some time figuring this out :)

# this example is for a typical 10x CellRanger output, use other codes to create Seurat objects when non-10x platforms are used
xx.data <- Read10X(data.dir = "~xx/filtered_feature_bc_matrix")
xx <- CreateSeuratObject(raw.data = xx.data,
                             project = "xx")

xy.data <- Read10X(data.dir = "~xy/filtered_feature_bc_matrix")
xy <- CreateSeuratObject(raw.data = xy.data,
                             project = "xy"
                             )

xz.data <- Read10X(data.dir = "~xz/filtered_feature_bc_matrix")
xz <- CreateSeuratObject(raw.data = xz.data,
                             project = "xz"
                             )

n2.combined <- MergeSeurat(object1 = xx, 
                               object2 = xy, 
                               add.cell.id1 = "xx",
                               add.cell.id2 = "xy",
                               project = "2samples"
                               )

n3.combined <- MergeSeurat(object1 = n2.combined, 
                               object2 = xz, 
                               add.cell.id2 = "xz",
                               project = "3samples"
                               )

# check tail and head for addition of sample specific ids 
tail(n3.combined@cell.names)
head(x = n3.combined@cell.names)

# to check cell number in the 2 sample combination and then the 3 sample combination
table(n2.combined@meta.data$orig.ident)
table(n3.combined@meta.data$orig.ident)

**Comment by Dragonmasterx87** [comment]
I have some code that can help you merge>2 objects :) [You can find it here](https://github.com/Dragonmasterx87/Merging-2-Seurat-Objects/blob/a0fbb358c2942597b9c45fe6c3091d41d339e281/Merging%20%3E2%20Seurats)!

**Comment by Simon6089** [comment]
I think the **Reduce** function can work well, for example:
```{r}
Reduce(function(x,y) merge(x,y,add.cell.ids = c(x@project.name,y@project.name)) , Seurat.list)
```
just input a list of seurat objects, and it seems that **MergeSeurat** function is replaced by **merge**.

**Comment by timoast** [comment]
@Simon6089 there's no need to do this, `y` can be a list of Seurat objects (see the docs for merge)
