### ISSUE TITLE
Error in UseMethod(generic = "DefaultAssay", object = object) :    no applicable method for 'DefaultAssay' applied to an object of class "data.frame"

### ISSUE THREAD

**Issue by jiangzzhh** [satijalab/seurat#7060]
library(Seurat)
counts <- read.table("1.txt", header=TRUE, row.names=1)
object <- CreateSeuratObject(counts = counts, project = "1", min.cells = 3, min.features = 200)
object <- CreateAssayObject(object, assay = "RNA", data = as.matrix(counts))
object <- PercentageFeatureSet(object, pattern = "^MT-")
object <- AddMetaData(object, object$percent.mt, col.name = "percent.mt")
preQC_rna <- VlnPlot(object, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), 
                     ncol = 3, 
                     group.by = "orig.ident", 
                     pt.size = 0)
The following error occurs after running the above code.Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "data.frame"

**Comment by saketkc** [comment]
`object <- CreateAssayObject(object, assay = "RNA", data = as.matrix(counts))` is not required here. You should be using `NormalizeData` if what you are originally reading as counts are UMIs.
