### ISSUE TITLE
To Recorrect UMI or Not to Recorrect UMI during FindAllMarkers Across Different Metadata

### ISSUE THREAD

**Issue by almm2020** [satijalab/seurat#7061]
To begin, I know that when you subset data, you should select recorrect_umi=FALSE . That is not the conundrum I've run into. My dataset has a lot of metadata which includes tissue and time point. I've also added information that included the clusters broken down by time. When I switch to another active identity and then run FindAllMarkers should I leave the default  recorrect_umi=T or should I switch to  recorrect_umi=FALSE ? 

A simple example of what I mean is:

Ex:
all_markers <- FindAllMarkers(object.integrated,
                               only.pos=T, logfc.threshold = 0.5,
                              recorrect_umi=T)

#timepoint markers
Idents(object.integrated) <- "time"
time.point_markers <- FindAllMarkers(object.integrated,
                               only.pos=T, logfc.threshold = 0.5,
                              **recorrect_umi=T**)

**_Or should I choose_**

Idents(object.integrated) <- "time"
time.point_markers <- FindAllMarkers(object.integrated,
                               only.pos=T, logfc.threshold = 0.5,
                              **recorrect_umi=FALSE**)

When I subset and change the active identities for marker identification, I've obviously not run recorrect_umi=T.

**Comment by saketkc** [comment]
You should recorrect UMI if you are merging SCT objects and they have different median sequencing depths and this needs to be only done once (without subsetting)
