### ISSUE TITLE
Bridge Integration Issue- invalid character indexing 

### ISSUE THREAD

**Issue by leeanapeters** [satijalab/seurat#7063]
Hi, thank you for the fantastic package!

I am attempting bridge integration using a bridge consisting of RNA and protein (made in house) and a cytof dataset.

I am encountering two issues:

1) In PrepareBridgeReference:
 "You're computing too large a percentage of total singular values, use a standard svd instead"

I have used the code indicated in #5697 for the bridge and RNA objects here, and made sure to scale both objects.

2) In FindBridgeTransferAnchors I get an invalid character indexing error and the code does not run.

Any help would be appreciated!

Session Info:

R version 4.2.2
Serurat 4.1.1
Platform linux-gnu
Running under Ubuntu 22.04.02 LTS

**Comment by yuhanH** [comment]
hi @leeanapeters 
You don't need to worry about the first issue.  Just need to make sure protein names in your cite-seq and cytof data should be the same. 
For the second issue, could you post your scripts?

**Comment by leeanapeters** [comment]
Hi thanks for the reply!

For the cytof and citeseq I just changed the rownames in the data slot using gsub and selected the ones that matched as variable features 

data<- obj[["CITE]]@data
row names(data)<- gsub("X","Y",row names(data)
obj[["CITE"]]@data<- data
DefaultAssay(obj)<- "CITE"
adt.feature<- intersect(rownames(cytof), rownames(obj[["CITE"]])
VariableFeatures(obj)<- adt.feature
obj<- ScaleData(obj, features=adt.features,do.scale=TRUE)
dims.adt=1:30
dims.rna=1:50
ref.extend<- PrepareBridgeReference(rna,normalization.method="LogNormalize",bridge=obj, 
reference.reduction="pca",bridge.query.assay="CITE",reference.dims=dims.rna,supervised.reduction="spca",bridge.query.features=adt.feature)
anchor<- FindBridgeTransferAnchors(extended.reference=ref.extend, query=cytof, reduction="pcaproject",scale=FALSE, dims=dims.adt)

It is only the last command that generates the error

Thanks!

**Comment by yuhanH** [comment]
hi @leeanapeters 
sorry for this late reply.... I would guess this step may cause the issue. We don't recommend you to change any slot using `@`. You would better use `CreateAssayObject()` to generate the new assay to rename features. 
```
data<- obj[["CITE]]@DaTa
row names(data)<- gsub("X","Y",row names(data)
obj[["CITE"]]@DaTa<- data
```
If possible, could you make a small reproducible example? That will be much easier for us to debug.

**Comment by Gesmira** [comment]
Closing for now due to lack of response. Please feel free to reopen if the problem persists!
