### ISSUE TITLE
Immunoglobulin genes

### ISSUE THREAD

**Issue by purisuto** [satijalab/seurat#7064]
When working with B cell data, I saw one study that appeared to remove immunoglobulin genes from the Seurat object prior to normalisation, which can be done using some form of:

`seu <- seu[ ! grepl("^IG(HV|KV|LV|HG|LC|HM|HD|HA)", rownames(seu)), ]`

Given Ig genes are highly expressed in ASCs, do you think that including them in the normalisation would skew values for non-Ig genes in ASCs?

**Comment by yuhanH** [comment]
The normalization step will not be significantly impacted by the removal of Ig genes, as it will only result in a smaller nCount_RNA without altering counts for other genes. However, this may affect FindVariableFeatures, PCA, and other related analyses. To include or exclude Ig genes depends on their importance in the clustering process.
