### ISSUE TITLE
DotPlot not working with a given feature set

### ISSUE THREAD

**Issue by andradejon** [satijalab/seurat#7065]
Hello,

I'm trying to use DotPlot to generate an expression matrix grouped by cluster, but it's telling me that my requested variables aren't found and returns an error.

I have an integrated dataset that is normalized and using the RNA assay:
> integrated
An object of class Seurat 
50360 features across 21625 samples within 3 assays 
Active assay: RNA (27818 features, 0 variable features)
 2 other assays present: SCT, integrated
 2 dimensional reductions calculated: pca, umap
>
> integrated <- NormalizeData(integrated)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|

I also have two feature sets, features1 and features2. All features in both sets are present in the RNA assay, and features1 is a subset of features2:
> length(features1)
[1] 1392
> head(features1)
[1] "LOC119726097" "LOC119725423" "LOC119725797" "LOC119735012" "LOC119735014" "LOC119734049"
> length(features2)
[1] 3371
> head(features2)
[1] "LOC119743287" "LOC119742599" "LOC119742959" "LOC119721125" "LOC119721048" "LOC119719908"
> 
> sum(features1 %in% features2)
[1] 1392
> sum(features1 %in% rownames(integrated@assays$RNA@meta.features))
[1] 1392
> sum(features2 %in% rownames(integrated@assays$RNA@meta.features))
[1] 3371

If I run DotPlot using features1, I get the following plot. Not pretty, but I'm not using the plot as is, and it runs which is important:
`> DotPlot(integrated, features=features1, assay='RNA', group.by = 'seurat_clusters')`
<img width="525" alt="000015" src="https://user-images.githubusercontent.com/74783330/227000530-e688fbaa-dcae-4cc4-bd06-288b88b5462f.png">

But if I run using features2, it holds for a long time before giving me the following error:
`> DotPlot(integrated, features=features2, assay='RNA', group.by = 'seurat_clusters')`

`Warning: Found the following features in more than one assay, excluding the default. We will not include these in the final data frame: LOC119743287, LOC119742959, LOC119721048, LOC119720818, LOC119720819, LOC119736166, LOC119726830, LOC119731534, LOC119732333, LOC119730873, LOC119730405,` 
(...this continues for a while)
`Warning: Could not find LOC119742599 in the default search locations, found in RNA assay insteadWarning: Could not find LOC119721125 in the default search locations, found in RNA assay insteadWarning: Could not find LOC119719908 in the default search locations, found in RNA assay insteadWarning: Could not find LOC119736167 in the default search locations, found in RNA assay insteadWarning: Could not find LOC119732332 in the default search locations, found in RNA assay insteadWarning: Could not find LOC119732334 in the default search locations, found in RNA assay instead`
(...this also continues for a while)
`Warning: The following requested variables were not found (10 out of 2296 shown): LOC119743287, LOC119742959, LOC119721048, LOC119720818, LOC119720819, LOC119736166, LOC119726830, LOC119731534, LOC119732333, LOC119730873`

I'm not sure what I'm doing wrong in this instance. It looks like 2296 features were not found, which is weird because that would also have to then include features in features1. Any help would be appreciated, thanks!

**Comment by andradejon** [comment]
The default assay is already RNA

**Comment by Yifath7** [comment]
I have the same problem...

**Comment by andradejon** [comment]
Coming back to check on this. I see the "more information needed" label was added. What sort of additional information would need to be provided?

**Comment by yuhanH** [comment]
@andradejon sorry about the delay...
Could you use any dataset in SeuratData to reproduce this problem? or send us a your own reproducible example? thank you.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
