### ISSUE TITLE
Help with importing single cell CRIPSR screening data into seurat

### ISSUE THREAD

**Issue by wliangl** [satijalab/seurat#7069]
Hi, I am learning the Mixscape function in the Seurat.
Could anyone let me know how to import single-cell CRISPR screening data into Seurat with meta.data information?
In the Mixscape vignette, the pre-made eccite-seq data has many meta.data such as guide ID, gene, NT.....  
Could  anyone let me know how to generate these metadata from a count matrix of cell barcode vs gRNA names?

Thank you!
Wliangl

**Comment by longmanz** [comment]
Hi, 
Do you mean that you have your own CRISPR sequencing data, and you want to add meta data to it? You can use function AddMetaData() in Seurat to add whatever meta data you want to a seurat object.
In most cases, after running the sequencing and alignment, the software (e.g., cellranger for 10x platform) will generate a "cell_metadata.csv" file. This is usually where you obtain your meta-data.

**Comment by wliangl** [comment]
> Hi, Do you mean that you have your own CRISPR sequencing data, and you want to add meta data to it? You can use function AddMetaData() in Seurat to add whatever meta data you want to a seurat object. In most cases, after running the sequencing and alignment, the software (e.g., cellranger for 10x platform) will generate a "cell_metadata.csv" file. This is usually where you obtain your meta-data.

Hi, Thank you for the help. Yes, I would like to generate metadata for my own single cell cripsr screening data. 
Simply saying, in the Mixscape vignette, eccite-seq dataset was loaded with full metadata information. I would like to learn the code that generates this eccite-seq object using a count matrix and other metadata files. Do you by chance know where to find the code? I read their paper but can not find the code. 

Thank you so much!

**Comment by longmanz** [comment]
Hi, 
I am not sure which platform you used to generate your CRISPR data, but if you are using 10x, to add meta data is very straightforward. You will first need to find and load your "protospacer_calls_per_cell.csv" file produced by 10x Cellranger (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/crispr), and use AddMetaData() to add the desired columns to your object. 
`# suppose you have your seurat obj names as "dat10x"`
`protospacer_calls_per_cell <- as.data.frame(read.csv("10x_crispr/aligned_data/ID/outs/crispr_analysis/protospacer_calls_per_cell.csv"))`
`rownames(protospacer_calls_per_cell) <- sapply(protospacer_calls_per_cell$cell_barcode, FUN = function(x) strsplit(x, split = "\\-")[[1]][1])`
`dat10x <- AddMetaData(dat10x, metadata = protospacer_calls_per_cell[,"feature_call", drop= FALSE], col.name = "gd")`
`dat10x <- AddMetaData(dat10x, metadata = protospacer_calls_per_cell[,"num_features", drop= FALSE], col.name = "num_features")`

**Comment by wliangl** [comment]
Hi, Thank you so much for the code. I will try and learn how to use it.

Best
wliangl
