### ISSUE TITLE
extracting donor level annotation for cells 

### ISSUE THREAD

**Issue by gromanoibarra** [satijalab/seurat#7070]
I'm studying gene expression in asthma, and recently was asked to look into the public asthma single-cell rna seq data found here:

https://cells.ucsc.edu/?ds=teichmann-asthma+asthma-epithelial

I want to see if the expression differences are unique to some types of asthma. I've been able to pull cell id barcodes and gene expression levels, as well as condition (control vs asthma). But i haven't been able to find which cells came from which donor.

Here's what I've been doing:

```
require(Seurat)
require(data.table)
setwd(here())

mat <- fread("exprMatrix.tsv.gz")
meta <- read.table("meta.tsv", header=T, sep="\t", as.is=T, row.names=1)
genes = mat[,1][[1]]
genes = gsub(".+[|]", "", genes)
mat = data.frame(mat[,-1], row.names=genes)
so <- CreateSeuratObject(counts = mat, project = "asthma", meta.data=meta)

#Scale data
so <- ScaleData(so, features = genes)

exp.dataframe <- so@assays$RNA@data %>% 
  data.frame() %>% 
  rownames_to_column("gene")
```
I suspect it's nested in something like "@assays$RNA@data" but not sure what the directory is.

if it's helpful, the donors are listed in the supplementary data where they indicate how many cells they got from each donor, and what kind of asthma they had. Here are the twelve donors - not sure if I can "search" to see where they might be listed....

Donors without asthma: ARMS026 ARMS032 ARMS038 ARMS040 ARMS051 ARMS054

Donors with Asthma: ARMS024 ARMS033 ARMS035 ARMS043 ARMS048 ARMS050

thanks everyone!

**Comment by saketkc** [comment]
The metadata information is the `object@meta.data` slot, but it is the same as what you inputted it when you read the `meta.data` file. Make sure the rownames of `meta.data` object are set to cell names before creating the object.

**Comment by longmanz** [comment]
Hi, 
This is an issue about this specific dataset, so we recommend that you reach out to its authors for details/help. 
If there is no donor information in your @metadata, you may look up the actual cell-IDs (colnames(so@assays$RNA@data)), sometimes they will include the actual donor IDs as part of the cell-IDs.
