### ISSUE TITLE
WNN Analysis - dim(X) must have a positive length

### ISSUE THREAD

**Issue by camilafarias112** [satijalab/seurat#7072]
Hello Seurat team,

I'm experiencing an error with my analysis and am unsure where the issue is.
I'm trying to run a WNN analysis with `FindMultiModalNeighbors()` in my multi-sample CITE-seq dataset.
I've already 1) normalized and found variable features from each of my rna and adt assays; 2) integrated samples, scaled them, and ran PCA and UMAPs for each assay. This resulted in a CD45.combined Seurat object:
<img width="787" alt="Screenshot 2023-03-27 at 2 37 35 PM" src="https://user-images.githubusercontent.com/47650119/228035709-0fac1ff2-3023-4291-80fa-d6f6459d5459.png">

I can't run the following code:
```
> CD45.combined <- FindMultiModalNeighbors(
+   CD45.combined, reduction.list = list("pca", "PCA_Protein"),
+   modality.weight.name = "RNA.weight", dims.list = c(1:50, 1:50))
Calculating cell-specific modality weights
Error in apply(X = mat, MARGIN = MARGIN, FUN = function(x) { : 
  dim(X) must have a positive length
```

Both of my PCAs have positive lengths... what could I be missing?
I'd appreciate it if you guys could provide some feedback. Big fan of the Seurat pipeline!
Best, Camila

**Comment by yuhanH** [comment]
hi @camilafarias112 
`FindMultiModalNeighbors` needs to have a list as the input for dims.list instead of a vector.
```
 CD45.combined <- FindMultiModalNeighbors(
   CD45.combined, reduction.list = list("pca", "PCA_Protein"),
   modality.weight.name = "RNA.weight", dims.list = list(1:50, 1:50))
```
