### ISSUE TITLE
Formal class Seurat

### ISSUE THREAD

**Issue by imranjesar** [satijalab/seurat#7074]
I am working on MSCs, while in R when i am trying to CreateSeuratObject it is generating a formal class seurat and when i am printing my object is is giving following response;
#An object of class Seurat 
0 features across 0 samples within 1 assay 
Active assay: RNA (0 features, 0 variable features)
After doing lot searching, what i came to find that number of rows in barcodes.tsv and matrix.mtx are not similar
nrows in matrix = 34742
nrows in barcodes.tsv = 6896

is there any problem with my data or i am doing anything wrong?
I am completely a noob here, a little help will be appreciated 
thanks

**Comment by longmanz** [comment]
Hi,
The matrix.mtx file is a matrix stored in sparse format (the 3 columns are row_position, column_position, count_value), so it is normal that the row number of matrix.mtx does not match the barcodes.tsv. 

To load the matrix.mtx + barcodes.tsv into R and create a Seurat obj, you may follow this tutorial:
https://satijalab.org/seurat/reference/readmtx
Make sure to set the "cell.column" and "feature.column" to the correct one in your features.tsv and barcodes.tsv files, respectively.
