### ISSUE TITLE
how to add adt and hto information to seurat object creaed from a rna matrix that contain less cells than in adt or hto matrix

### ISSUE THREAD

**Issue by fxmauvais** [satijalab/seurat#7077]
Hi everyone,

I am trying to reanalyze a public dataset from GEO (accession number is GSE214060). I want to start working from the mtx files provided and not from raw fastq files. I downloaded the mtx, features and barcodes gz files. 
I created for rna, adt and hto information a matrix using the function ReadMtx from the Seurat package.

`test.rna <- ReadMtx(mtx = "matrix.mtx.gz", cells = "barcodes.tsv.gz", features = "features.tsv.gz")` 
`test.hto <- ReadMtx(mtx = "hto_matrix.mtx.gz", cells = "hto_barcodes.tsv.gz", features = "hto_features.tsv.gz", feature.column = 1)` 
`test.adt <- ReadMtx(mtx = "adt_matrix.mtx.gz", cells = "adt_barcodes.tsv.gz", features = "adt_features.tsv.gz", feature.column = 1)`

Then I created an assay object using the CreateAssayObject() function for adt and hto:
`assay_hto <- CreateAssayObject(counts = test.hto)` 
`assay_adt <- CreateAssayObject(counts = test.adt)` 

Then, I created a Seurat object from the rna matrix 
`rna_object <- CreateSeuratObject(counts = test.rna, assay = "RNA")` 

When I try to add either adt or hto information from the created assay object to the rna_object Seurat object I get the following error message:

`rna_object[["ADT"]] <- assay_adt` 
Error: Cannot add a different number of cells than already present

Indeed, when looking at the objects:
1) rna_object is An object of class Seurat  32287 features across 18662 samples within 1 assay 
Active assay: RNA (32287 features, 0 variable features)
2) assay_adt is Assay data with 7 features for 19235 cells
3) assay_hto is Assay data with 5 features for 19235 cells

So if i correctly understand the situation there are 18662 cells in the rna_object and 19235 in the two assays. I assume that this come from a filtering performed by the contributors but anyway I wonder how to add in this particular situation bot adt and hto information to my rna_object SeuratObject.

Thank you very much for your kind help

**Comment by longmanz** [comment]
Hi,
You will need to use the intersect (shared) cells across the RNA, HTO, and ADT assays to create a Seurat object. Seurat (V4) does not allow discrepancy of cells between assays. For example, you will need to do the following:
```
rna_object <- CreateSeuratObject(counts = test.rna, assay = "RNA")
cells.use <- intersect(colnames(assay_hto), colnames(assay_adt))
cells.use <- intersect(cells.use, colnames(rna_object ))

# remove cells that are not shared
rna_object <- subset(rna_object, cells = cells.use)
dat10x[["HTO"]] <- subset(assay_hto, cells = cells.use)
dat10x[["ADT"]] <- subset(assay_adt, cells = cells.use)
```

That being said, the above solution is for Seurat V4.  With the release of Seurat V5, now we can have different cells in different assays in the same Seurat object. You can read more about the new features in Seurat V5 at https://satijalab.org/seurat/articles/get_started_v5.html.
