### ISSUE TITLE
correct reference hyperlink text

### ISSUE THREAD

**Issue by HelenaLC** [satijalab/seurat#7078]
Kindly, could you correct the hyperlink-text under [Compare healthy and diabetic samples](https://satijalab.org/seurat/articles/parsebio_sketch_integration#compare-healthy-and-diabetic-samples) to say *Crowell et al.* rather than *Soneson et al.*, as it's linking to `muscat` for subpopulation-specific multi-sample/cross-condition DE? Unless you are referring to [this](https://www.nature.com/articles/nmeth.4612) paper on DE in general? Thanks.

**Comment by AustinHartman** [comment]
Hi @HelenaLC, very sorry about this mistake and thank you for pointing it out! We've updated the text to acknowledge papers.

**Comment by HelenaLC** [comment]
Ui, that was quick. Thanks!
