### ISSUE TITLE
Azimuth annotation with  Azimuth human pancreas reference for image-based spatial data in Seurat

### ISSUE THREAD

**Issue by yingsun-ucsd** [satijalab/seurat#7079]
I am working on Nanostring CosMx Spatial Molecular Imager in Seurat. In the document, it mentions that "instead of performing unsupervised analysis, we map the Nanostring profiles to our Azimuth Healthy Human Lung reference, which was defined by scRNA-seq. We used Azimuth version 0.4.3 with the reference version 1.0.0. You can download the pre-computed results, which include annotations, prediction scores, and a UMAP visualization."

My question is: **How can I generate this Azimuth annotation file "nanostring_data.Rds" using Azimuth Human Pancreas reference? Would you please point me to the instructions for this?**

**Comment by AustinHartman** [comment]
Hi @yingsun-ucsd, I'd recommend using `RunAzimuth` locally with the `pancreasref` reference to annotate your data. Alternatively, you can upload you data to the azimuth app [here](https://azimuth.hubmapconsortium.org/references/#Human%20-%20Pancreas), and download the results which should look something like the file you're interested in.

If you choose to use `RunAzimuth` locally the steps would look something like this:
```r
# install Azimuth and SeuratData
devtools::install_github("satijalab/azimuth")
devtools::install_github("satijalab/seurat-data")
pancreas.object <- RunAzimuth(pancreas.object, reference = "pancreasref")
```

**Comment by yingsun-ucsd** [comment]
@AustinHartman Thanks a lot! Unfortunately, I had trouble installing "devtools". Here is the error message I got.

_______________________________

**install.packages( "devtools" )
devtools::install_github("satijalab/azimuth")**

Installing package into ‘/home/ysun/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)

also installing the dependencies ‘textshaping’, ‘ragg’, ‘pkgdown’

Warning message in install.packages("devtools"):
“installation of package ‘textshaping’ had non-zero exit status”
Warning message in install.packages("devtools"):
“installation of package ‘ragg’ had non-zero exit status”
Warning message in install.packages("devtools"):
“installation of package ‘pkgdown’ had non-zero exit status”
Warning message in install.packages("devtools"):
“installation of package ‘devtools’ had non-zero exit status”

Error in loadNamespace(x): there is no package called ‘devtools’
Traceback:

1. loadNamespace(x)
2. withRestarts(stop(cond), retry_loadNamespace = function() NULL)
3. withOneRestart(expr, restarts[[1L]])
4. doWithOneRestart(return(expr), restart)

**Comment by AustinHartman** [comment]
@yingsun-ucsd I'd recommend identifying the specific errors which caused devtools dependencies to not install successfully. Most likely, there are some missing system dependencies you'll have to install in order to install devtools successfully.

**Comment by yingsun-ucsd** [comment]
@AustinHartman Thanks. I got it to work by following my colleague's suggestion to install via conda using conda-forge "conda install -c conda-forge r-devtools".

**Comment by yingsun-ucsd** [comment]
@AustinHartman Hi, I have one more question: I have a Seurat object w/ SoupX assay (RNA) and Raw non-corrected data (RAW_mtx) in *.rds. Is that possible to use it as the "reference" while running RunAzimuth?

**Comment by yingsun-ucsd** [comment]
@AustinHartman  I followed your instructions to map the profiles to Azimuth Human Pancreas reference as "pancreas.object <- RunAzimuth( pancreas.object, reference = "pancreasref" )". It works great! And I need more help from you.

I would like to do the same thing but with my own single-cell RNA-seq data as the reference. To my understanding, I can use "AzimuthReference" to generate the reference to do so. But I did not find the instruction, protocol, or example of how. I am very new to Seurat, could you please give me some guidance on it? Thanks a lot!
