### ISSUE TITLE
Interaction with count layers before integration V5

### ISSUE THREAD

**Issue by JABioinf** [satijalab/seurat#7083]
Hi and thank you for developing this v5! 
I followed the BPCcells vignette to create a merged Seurat object from a list of multiple 10X samples: https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html

I am having issue interacting with the multiple layers during seurat object creation for basic QC before integration and for instance couldn't run the  following;
`merged.object <- CreateSeuratObject(counts = data.list,min.cells = 3,min.features = 500)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'colSums': comparison (6) is possible only for atomic and list types`
and for the same reason most likely couldn't run
`PercentageFeatureSet(merged.object,pattern = "^MT-")`
since it only operate on the 1st layer apparently.
What is your recommendation to preprocess sample lists before integration? Do I need to Join layer, preprocess as a whole, then split again or is there a simple way to interact with multiple layers.

It seems the functions don't automatically apply to list of objects or all count layers. Could their be more documentation on the way to interact with multiple layers of count data from multiple samples for preprocessing steps (e.g. filtering, subsetting, mitochondrial, cell cycle scoring, etc.)? It would be great if one of the example vignette could start from a list of raw 10X samples cell ranger output (unfiltered, unprocessed, etc.) and manipulate them as v5 SeuratObjects until integration (instead of data preprocessed from other vignette). That would be really helpful !

Also I noticed, SCT method is not mentioned in v5 integration vignette. Do you recommend now only the NormalizeData path or can SCT be run as usual before integration? (I was using the SCT v2 flavor before with glmGamPoi) 

Note that the JoinLayers link toward man page  doesn't work in this vignette: https://satijalab.org/seurat/articles/seurat5_essential_commands.html
Thank you for the help! Sorry if it's already mention somewhere.

**Comment by Gesmira** [comment]
HI @JABioinf, thanks for bringing these issues to our attention! The two issues you mentioned (filtering a list of BPCells matrices and `PercentageFeatureSet` for objects with multiple layers) should now be fixed in the seurat5 branches of Seurat and SeuratObject. In terms of `PercentageFeatureSet`, the percentages are now calculated per layer and joined together, so that each cell in the object has the metadata added.

```
remotes::install_github("mojaveazure/seurat-object", "seurat5", quiet = TRUE)
remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)
```

In terms of your second point, SCTransform is still supported in Seurat v5!
