### ISSUE TITLE
extract gene coordinates and TSS from gene list

### ISSUE THREAD

**Issue by feanaros** [satijalab/seurat#7086]
Hi, I have a list of 50 genes like this:

    "Tshz2"   "Ebf1"    "Col26a1" "Ebf2"    "Unc5c"   "Prkg1"   "Eya1"    "Ldb2"    "Rbms3"   "Arhgap6"

And I need the coordinates of gene body and the TSS +1000/-1000 bp. How can I get it?
The genome is `mm10.`

Thanks

**Comment by mhkowalski** [comment]
Hi, this is not relevant to Seurat, but I would suggest that you use a package such as [biomaRt](https://bioconductor.org/packages/release/bioc/vignettes/biomaRt/inst/doc/accessing_ensembl.html#given-the-human-gene-tp53-retrieve-the-human-chromosomal-location-of-this-gene-and-also-retrieve-the-chromosomal-location-and-refseq-id-of-its-homolog-in-mouse), which allows you to acces Ensembl's databases.
