### ISSUE TITLE
Choosing number of CC for clustering

### ISSUE THREAD

**Issue by nicodemus88** [satijalab/seurat#709]
Hi,

I am trying to perform a combination analysis for 3 samples. All 3 samples have the same condition (in this case, cancer). 

I sequenced all 3 samples using 10x and I got full sequencing coverage for all 3. The only difference is the number of cells for each sample (350, 150 and 800 cells).

When I performed RunMultiCCA and plot the correlation plot, my plot looks like this below.

![00_cc_plot](https://user-images.githubusercontent.com/24598265/44296479-0b026f00-a2fb-11e8-9108-26d629b31d14.png)

How many CCs should I use for clustering in this case? As you can see, the correlation looks strange as one of it goes up after about CC10. 

Hope to hear some feedback soon. Thank you very much.

**Comment by andrewwbutler** [comment]
Hi,

Please see  #609.
