### ISSUE TITLE
integrating replicates for spatial data (Visium) and finding variable features

### ISSUE THREAD

**Issue by mistrm82** [satijalab/seurat#7094]
Hello, I have used Seurat for numerous scRNA-seq datasets, but a first time user with Spatial transcriptomics and I am having some trouble navigating the best way forward.

I am using Seurat v4.3 to analyze 10X Visium data. I have been following the vignette as closely as possible but have an issue when it comes to combining samples. I have 3 biological replicates from a tumor sample. First I evaluated each sample independently to look at various QC metrics. Next, I merged samples into a single object to see how samples were clustering.

```
parental <- merge(x = CD_Visium_01, 
                     y = c(CD_Visium_04, CD_Visium_07),
                     add.cell.ids = samples[c(1,4,7)])

# Run PCA again on all samples in group
parental <- SCTransform(parental, assay = "Spatial", verbose = TRUE)
parental  <- RunPCA(parental , assay = "SCT", verbose = FALSE)
parental  <- FindNeighbors(parental, reduction = "pca", dims = 1:30)
parental <- FindClusters(parental, verbose = FALSE)
parental  <- RunUMAP(parental, reduction = "pca", dims = 1:30)
```

 I noticed that each sample segregated to into separate clusters, suggesting a need to integrate across the replicates.

![image](https://user-images.githubusercontent.com/6545708/229137517-f1fc3691-154b-4244-875b-333a0567449d.png)

I did not see an example of integration across slides/samples in the vignette, but assumed we could do something similar to what we do for scRNA-seq -- is this okay? If not, how do I deal with replicates with spatial data?

For each sample I run SCT and the successfully performed integration on them. 

```
p.features <- SelectIntegrationFeatures(list(CD_Visium_01, CD_Visium_04, CD_Visium_07), nfeatures = 3000, verbose = FALSE)
#Prep for integration
p.prepsct <- PrepSCTIntegration(object.list = list(CD_Visium_01, CD_Visium_04, CD_Visium_07), 
                              anchor.features = p.features, verbose = FALSE)

# Find anchors
p.int.anchors <- FindIntegrationAnchors(object.list = p.prepsct, normalization.method = "SCT", verbose = FALSE,
                         anchor.features = p.features)
# Integrate
parental.integrated <- IntegrateData(anchorset = p.int.anchors, normalization.method = "SCT", verbose = FALSE)

parental.integrated <- RunPCA(parental.integrated, verbose = FALSE)
parental.integrated <- FindNeighbors(parental.integrated, dims = 1:30)
parental.integrated <- FindClusters(parental.integrated, verbose = FALSE)
parental.integrated <- RunUMAP(parental.integrated, dims = 1:30)
```

So now I have this combined Seurat object where replicates are now aligned:

![image](https://user-images.githubusercontent.com/6545708/229140300-3ac6c2ff-31ad-403f-8ad3-ba1e1e92a380.png)

Now I would like to find spatially variable features and I am not sure what is the best way to go about this.

1. Using `FindMarkers()`. This works fine if my DefaultAssay is "integrated". But when I change the assay to "SCT", I get the following error:

```
de_markers <- FindMarkers(parental.integrated, ident.1 = 0, ident.2 = c(1:7))
Error in FindMarkers.SCTAssay(object = data.use, slot = slot, cells.1 = cells$cells.1,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`.
```

When I try and run `parental.integrated <- PrepSCTFindMarkers(parental.integrated, assay = "SCT")` , my system crashes.

2. Using `FindSpatiallyVariableFeatures()`.  This also causes R to crash.

Any help would be greatly appreciated, thanks so much!

**Comment by AustinHartman** [comment]
Hi @mistrm82, thank you for detailing your issue. Integrating the three datasets sounds like a reasonable approach to me, given these are replicates. After identifying shared clusters or cell types via integration, I would recommend finding markers which are conserved across replicates using the original merged assay, rather than the integrated assay. Second, I'd recommmend trying `moransi` to identify variable features, which can be specified via the `selection.method` argument as it runs much faster. I hope to add some new and faster spatially variable feature finding methods soon. Hope this helps!

**Comment by mistrm82** [comment]
Thank you @AustinHartman !

Just a couple of follow-up questions:

When you say that you "recommend finding markers which are conserved across replicates using the original merged assay" - Do I take cluster identities from the integrated assay and assign them to spots in the merged assay and use that object to perform FindMarkers?

Should I also be using the merged assay as input to the `FindSpatiallyVariableFeatures()` function? I had tried `moransi` method but it also crashes so I am not sure that the method selection is the issue.

**Comment by AustinHartman** [comment]
That's right, identify cluster identities for each spot in each Visium experiment, based on the integrated assay. That way, your clusters will represent shared cell types / states across experiments. Finding spatially variable features requires the positional information for each spot relative to the other spots and thus should be called on each object/experiment separately.
