### ISSUE TITLE
Reference mapping fails to assign correct UMAP coordinates for query dataset when reference is downsampled to smaller cell count

### ISSUE THREAD

**Issue by kriukovav** [satijalab/seurat#7098]
Dear Seurat developers, thank you for this software!

I would like to report a behavior, which I have not expected. I use reference mapping according to your vignette:

```
RunUMAP(<object_reference>, dims = <>, reduction = "pca", return.model = TRUE)
anchors <- FindTransferAnchors(
    reference = <object_reference>,
    query = <object_query>,
    reference.reduction = "pca",
    k.anchor = 5)
mapped_query <- MapQuery(anchorset = anchors, reference = <object_reference>, query = <object_query>, refdata = "seurat_clusters", reference.reduction = "pca", reduction.model = "umap")
```

Everything works perfectly in this case. 

Then I want to use the same procedure with a downsampled reference (the same reference dataset, but keeping a random relatively small number of cells). And ideally, I want to keep the reference UMAP structure untouched. 
To do that, I run RunUMAP() on the full reference dataset, then subset() the reference dataset to keep a smaller number of cells, then do FindTransferAnchors() and MapQuery(). 
```
RunUMAP(<object_reference>, dims = <>, reduction = "pca", return.model = TRUE)
<object_reference> <-  subset(<object_reference>, cells = sample(1:length(rownames(<object_reference>[[]])), 15000))
anchors <- FindTransferAnchors(
    reference = <object_reference>,
    query = <object_query>,
    reference.reduction = "pca",
    k.anchor = 5)
mapped_query <- MapQuery(anchorset = anchors, reference = <object_reference>, query = <object_query>, refdata = "seurat_clusters", reference.reduction = "pca", reduction.model = "umap")
```
In this scenario, label transfer seems to work well. But the refUMAP coordinates (mapped_query@reductions$ref.umap@cell.embeddings) in the mapped_query dataset do not match (overlay) the coordinates in the reference dataset. Could you please tell me whether it is expected behavior? 

Thank you for any reply in advance!

**Comment by kriukovav** [comment]
I decided to add images to better explain the issue. This one refers to the reference mapping to the full dataset (grey dots - reference dataset, blue dots - mapped query dataset on top) 
![image](https://user-images.githubusercontent.com/49070913/229306159-560043e8-81ef-4cea-9a04-8f6a9c55e7e6.png)

And this one refers to the reference mapping to the downsampled reference dataset
![image](https://user-images.githubusercontent.com/49070913/229306374-5a3f9d43-3d1b-4786-a4d8-7f736b9bfb35.png)

**Comment by mhkowalski** [comment]
You need to re-run UMAP after subsetting the reference for this to work. Also, we recommend that rather than randomly subsetting the reference, you could try using our methods for sketching, which will downsample the reference to a set of informative cells (and preserve rare cell populations), see details [here](https://satijalab.org/seurat/articles/seurat5_sketch_analysis.html).
