### ISSUE TITLE
What exactly can I infer from PCHeatmap?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#71]
Hello Seurat Team,

I couldn't find a satisfactory answer to the following question in the tutorials or the help pages, and so I thought of asking here.  

What exactly can I infer about my data from the PCHeatmap plots?  I see that the columns of the plots are the cells/barcodes, and the rows are genes.  What are the values that are represented by the colors?  Are they PC scores, or are they simply the scaled count values?

Any explanation that gives the intuition of the heatmap plots would be greatly appreciated!  Thanks!

**Comment by satijalab** [comment]
They are scaled count values.
