### ISSUE TITLE
Plotting clusters with their sub-clusters simultaneously 

### ISSUE THREAD

**Issue by fereshtehizadi** [satijalab/seurat#710]
Hi,

Sorry, Seurat has clustered my 1562 cells to 8 clusters (I have 8 time points), however each of 8 clusters could be clustered to 2 or 3 sub-clusters. Is there any way to plot heat map or violin plot of clusters with its sub-clusters in one plot??? Something like this plot that there is 3 main clusters with some sub-clusters

[

![](https://image.ibb.co/cEqFvz/Untitled.png)
](url)

Thank you for any help and suggestion

**Comment by satijalab** [comment]
You can use SetIdent to manually set the identities in the original object to include SetIdent.

Though its not a perfect example, we have a similar use case for SetIdent here:
https://satijalab.org/seurat/visualization_vignette.html
