### ISSUE TITLE
conversion SingleCellExperiment to Seurat (as.Seurat) runs into error

### ISSUE THREAD

**Issue by jkaiser87** [satijalab/seurat#7101]
Hey,
Thanks so much for providing this amazing resource! I am super excited to try the different integration methods in Seurat as this has been an issue for us in the past.
 
I have a singlecellexperiment object, that I used to convert into a seurat object using the 'as.Seurat' function, which worked perfectly in the current CRAN version. I just updated to v5, but now I can't convert the object anymore with this error message:

```
sce.all <- readRDS("SCE_integrated.rds")
obj <- as.Seurat(sce.all)

```
which now results in:
`Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 'arg' should be one of “counts”, “data”, “scale.data”`

I saw that in the vignette for the conversion for v5 it is showing the same error: https://satijalab.org/seurat/articles/seurat5_conversion_vignette.html Is there a workaround for this?

**Comment by zhujack** [comment]
I have run into the same error. Hope the authors will take a look at this issue soon.

**Comment by Gesmira** [comment]
Hi, 
We now recommend the use of [sceasy](https://github.com/cellgeni/sceasy) for converting between Seurat and SingleCellExperiment objects.

**Comment by rsango6** [comment]
Hi @Gesmira,
I tried to use `sceasy` however I don't see, among other options, to convert from Single Cell Experiment format to Seurat format, which is exactly what OP has asked and something I would also need. I am running in the same error as the folks above. Do you think this might be fixed soon?
Thanks!

**Comment by me37uday** [comment]
Hi,

Same error when trying to convert from loom to seurat. And looks like sceasy does not support this conversion as well. 

Any alternate suggestions would be much appreciated!

Best,
U
