### ISSUE TITLE
installation of additional packages used in Seurat v5

### ISSUE THREAD

**Issue by joonlee3** [satijalab/seurat#7102]
I was trying to install suggested R packages for Seurat v5. I failed to install two packages - **Azimuth** and **SeuratWrappers**. That is what I've got. FYI, I am currently using R 4.2.0.

```r
> remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE)
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpdeR8Ai/file42e5382359db/Azimuth_0.4.6.9001.tar.gz’ had non-zero exit status

> remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet = TRUE)
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpdeR8Ai/file42e54523be4/SeuratWrappers_0.3.1.tar.gz’ had non-zero exit status
```

**Comment by Gesmira** [comment]
Hi, 
Can you change the parameter to `quiet = FALSE` and share the error that should show right before that warning message? 
`remotes::install_github("satijalab/azimuth", "seurat5", quiet = FALSE)`

That should help tell us exactly which dependency it failed on.

**Comment by joonlee3** [comment]
Hi,

   I repeated it. Now I've got a different error message
`Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 34.203.235.60. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2023-03-31 21:18:58 UTC

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.`

**Comment by Gesmira** [comment]
This is an issue on the Github API side, you can follow it's instructions and se your personal access token in R with 
`credentials::set_github_pat("")` or wait and try again later as it will reset.

**Comment by joonlee3** [comment]
Hi,

  I added github token and reran the command suggested above. Here is what I've got.
`
* installing *source* package ‘SeuratWrappers’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘SeuratWrappers’ in namespaceExport(ns, exports):
 undefined exports: [batchelor]{fastMNN}
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratWrappers’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratWrappers’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/kd/t6hs8p3d395061h5sbynh4yc0000gp/T//RtmpupYdLV/file9be61367329b/SeuratWrappers_0.3.1.tar.gz’ had non-zero exit status
`
I tested it on my macbook and Rstudio on cloud system. I've got the same error. Any suggestions? Thank you.

Best,
Joon

**Comment by Wang-Cankun** [comment]
> Hi,
> 
> I added github token and reran the command suggested above. Here is what I've got. `
> 
> * installing _source_ package ‘SeuratWrappers’ ...
>   ** using staged installation
>   ** R
>   ** byte-compile and prepare package for lazy loading
>   ** help
>   *** installing help indices
>   ** building package indices
>   ** testing if installed package can be loaded from temporary location
>   Error: package or namespace load failed for ‘SeuratWrappers’ in namespaceExport(ns, exports):
>   undefined exports: [batchelor]{fastMNN}
>   Error: loading failed
>   Execution halted
>   ERROR: loading failed
> * removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratWrappers’
> * restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SeuratWrappers’
>   Warning message:
>   In i.p(...) :
>   installation of package ‘/var/folders/kd/t6hs8p3d395061h5sbynh4yc0000gp/T//RtmpupYdLV/file9be61367329b/SeuratWrappers_0.3.1.tar.gz’ had non-zero exit status`
> 
> I tested it on my macbook and Rstudio on cloud system. I've got the same error. Any suggestions? Thank you.
> 
> Best, Joon

@joonlee3 I had the same issue. Check the solution at https://github.com/satijalab/seurat-wrappers/issues/152#issuecomment-1498424820

**Comment by Gesmira** [comment]
[PR fixing this](https://github.com/satijalab/seurat-wrappers/pull/157) has been merged now. Thanks all for the details and catching the fix!
The updated package can be installed with: 
`remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet = TRUE)`

**Comment by RenJ-Feng** [comment]
>remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet = FALSE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo satijalab/seurat-wrappers@seurat5
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: spatstat.... (3.2-5 -> 3.2-6) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
spatstat.... (3.2-5 -> 3.2-6) [CRAN]
Installing 1 packages: spatstat.explore

  有二进制版本的，但源代码版本是后来的:
                 binary source needs_compilation
spatstat.explore  3.2-5  3.2-6              TRUE

  Binaries will be installed
试开URL’https://cran.rstudio.com/bin/windows/contrib/4.3/spatstat.explore_3.2-5.zip'
Content type 'application/zip' length 3324993 bytes (3.2 MB)
downloaded 3.2 MB

程序包‘spatstat.explore’打开成功，MD5和检查也通过

下载的二进制程序包在
	C:\Users\Administrator\AppData\Local\Temp\RtmpwTMVc1\downloaded_packages里
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpwTMVc1\remotes13dc6933767d\satijalab-seurat-wrappers-f647ce4/DESCRIPTION' (366ms)
─  preparing 'SeuratWrappers': (446ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (382ms)
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'SeuratWrappers_0.3.2.tar.gz'
   
* installing *source* package 'SeuratWrappers' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'R.utils'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'SeuratWrappers'
* removing 'D:/Program Files/R/R-4.3.2/library/SeuratWrappers'
Warning message:
In i.p(...) :
  安装程序包‘C:/Users/ADMINI~1/AppData/Local/Temp/RtmpwTMVc1/file13dc66f72c9f/SeuratWrappers_0.3.2.tar.gz’时退出狀態的值不是0

**Comment by RenJ-Feng** [comment]
Solution
remotes::install_github('satijalab/seurat-wrappers@community-vignette', quiet = TRUE)
