### ISSUE TITLE
subset function not working on chromatin assay object after updating Seurat to V5

### ISSUE THREAD

**Issue by Priyadarshini-Rai** [satijalab/seurat#7105]
```r
# insert reproducible example here
```

**Comment by Gesmira** [comment]
Hi, have you installed the V5 version of Signac as well? 
`remotes::install_github("stuart-lab/signac", "seurat5")`

**Comment by Priyadarshini-Rai** [comment]
Hi. No, I haven't installed version 5 of Signac. But, I switched to Seurat
4.3 but still it is giving the same error message.

*With Regards,*
*Priyadarshini Rai*
*Research Scholar, IIIT Delhi*
*Mobile: +919560039273*

**Comment by Gesmira** [comment]
What is the error message you are getting?

**Comment by Priyadarshini-Rai** [comment]
Hi.

I am getting the following error message.

Error in `LayerData<-`(object = `*tmp*`, layer = i, ..., value = value) :
  'value' must be a 'matrix' or 'dgCMatrix'

*With Regards,*
*Priyadarshini Rai*
*Research Scholar, IIIT Delhi*
*Mobile: +919560039273*

**Comment by Priyadarshini-Rai** [comment]
Thank you for your help. After restoring the 'SeuratObject' library to the
previous version, we are now not getting the error.

*With Regards,*
*Priyadarshini Rai*
*Research Scholar, IIIT Delhi*
*Mobile: +919560039273*

**Comment by Gesmira** [comment]
Ok great, I'm gonna close the issue then since this seems to be resolved for now!
