### ISSUE TITLE
FindMarkers - Differential expression analysis

### ISSUE THREAD

**Issue by pauld789** [satijalab/seurat#7106]
Hi,
I am currently using seurat for scRNAseq analysis. I have integrated my samples, did clustering and used the PrepSCTF function, please see the code below for the PrepSCTF function: 
sObj <- PrepSCTFindMarkers(sObj, assay = "SCT", verbose = TRUE)

For differential expression analysis, I have changed the ident to cell type condition using the following code:
sObj$celltype.cnd <- paste0(sObj$seurat_clusters,'_', sObj$SampID)
View(sObj@meta.data)
Idents(sObj) <- sObj$celltype.cnd

sObj.markers_cluster1 <- FindMarkers(sObj, ident.1 = "1_control", ident.2 = "1_cKO", min.pct = 0.25, logfc.threshold = 0.25)

Since I am new to this kind of analysis, I was confused about using 'RNA' or 'SCT' for differential expression analysis. Additionally, I do find major differences when I use 'SCT' vs 'RNA' as the default assay. Can you help me with this?

Thank you!

**Comment by longmanz** [comment]
Hi, 
To run DE test for the SCT assay you can do this `SCT.DE <- FindMarkers(sObj, assay = "SCT", ident.1 = "1_control", ident.2 = "1_cKO", verbose = FALSE)`. You can read more on this at https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9.

Ideally, the SCT assay and RNA assay should have similar DE results (both are good for DE test). The discrepancy you observed might indicate there is confounding / batch effect in your data.
