### ISSUE TITLE
Slots Descriptions Are Ambiguous

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#7108]
[Slots](https://github.com/satijalab/seurat/wiki/Assay#slots) has `data` described as "Normalized data matrix". Do you mean linear or log scale numbers? I was looking at the code for `FoldChange.default` and noticed when slot is `"data"`, the choice of `mean.fxn` is:

```r
Browse[3]> mean.fxn
function (x) 
{
    return(log(x = rowMeans(x = x) + pseudocount.use, base = base))
}
<environment: 0x5563f0dafd78>
```

For log-scaled input data, this causes logarithms to effectively be applied twice. Some published batch effect correction methods, such as scMerge, take input data on linear scale and return data on log scale.

**Comment by rsatija** [comment]
Thanks for the thoughtful feedback. We have consistently referred to normalized data as a representation of the counts matrix in log-scale. The `counts` slot stores integer values. In principle we could also store normalized counts (linear scale), but these are rarely used, and its more efficient just to recompute them when needed (as this function does).
