### ISSUE TITLE
Integrate two ATAC and two GEX samples? (non-multiome)

### ISSUE THREAD

**Issue by meaksu** [satijalab/seurat#7109]
Hi,
I have an experiment with two different conditions, and each condition has one ATAC and one Gene Expression dataset, but they are not from the same cells. From what I understand, it would be possible to integrate the ATAC across both conditions and Gene Expression across both conditions, and it would also be possible to integrate the ATAC and Gene Expression together for the same condition. 

However, would it be possible to somehow do a "four-way" integration of the two ATAC and two Gene Expression data so that everything would be comparable? If so, what would be the order of the steps needed to accomplish this?

**Comment by mhkowalski** [comment]
Hi, 

What do you mean integrating ATAC and Gene Expression together for the same condition? If you mean integrating ATAC and  RNA by calculating gene activity (GA) scores from your ATAC data, you could simply calculate GA scores for both ATAC-seq datasets and then integrate all 4 datasets together. 

As an alternative, depending on what tissue you have and if there we have an Azimuth reference for that tissue, you might also use our recently developed bridge integration method  (see [here](https://satijalab.org/seurat/articles/seurat5_integration_bridge.html)). This method would allow you to map both your RNA and ATAC-seq data to one of our Azimuth references. This method will annotate your cells using a healthy reference, without assuming a particular relationship between ATAC-seq and RNA-seq.
