### ISSUE TITLE
DotPlot:  cluster order and subsets

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#711]
I have a SC dataset w 22 clusters and want to use DotPlot to show Hox complex expression.    The Qs are a) how to plot clusters in order of my choosing, b) how to plot a specific subset of clusters.   An 'idents.include' argument in DotPlot would give a subset, but how to do custom ordering?

I'm looking for organization like the attached figure.
To generate it, I've cut&paste the output of three separate DotPlot calls after running different SubsetData functions to get objects w only the tailored group of clusters shown.   It works for a figure, but unfortunately the scaling of each plot is different.   

![image](https://user-images.githubusercontent.com/33207886/44305250-d1942880-a327-11e8-8a45-788b5ba938a8.png)

**Comment by satijalab** [comment]
The 'identity class' of a Seurat object is a factor (in object@ident) (with each of the options being a 'factor level'). The order in the DotPlot depends on the order of these factor levels.

We don't have a specific function to reorder factor levels in Seurat, but here is an R tutorial with osme examples
https://www.r-bloggers.com/reorder-factor-levels/

**Comment by sjfleming** [comment]
Explicit example that worked for me in Seurat 3:

```R
# reorder clusters
obj2@active.ident <- factor(obj2@active.ident, 
                            levels=c("Memory CD4 T", 
                                     "Naive CD4 T",
                                     "CD14+ Mono", 
                                     "Memory B", 
                                     "Naive B", 
                                     "CD8+ T", 
                                     "CD8+ T: 2", 
                                     "NK", 
                                     "FCGR3A+ Mono", 
                                     "Platelet", 
                                     "DC"))
```

**Comment by jiansongatnih** [comment]
@sjfleming I tried your suggested approach to order my cell types (active.ident) for DotPlot, but I got the following error message:
Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

Do you know why? and how to fix it? Thanks!

**Comment by AndyR2** [comment]
this code works for several plot types (dotplot, violin, barplot) to get custom ordering in Sv3.

`#reorder clusters 
my_levels <- c(0,23,6,2,..........)
factor(Idents(obj_name), levels= my_levels)
Idents(obj_name) <- factor(Idents(obj_name), levels= my_levels)

#create ggplot object
plot <-DotPlot(obj_name, features = c("Wnt4", "Lhx1", "Wt1", etc,)
#generate the plot & flip axes
plot + coord_flip()`

**Comment by jiansongatnih** [comment]
Thank you Andy! I tried as suggested, but got the same error message. 
If I do not try to change the order of the cell types on the DotPlot, everything works fine, with the cell types shown in a reverse alphabetical order.

#########
myLevels <- c("Stem",
"TA 1",
"TA 2",
"Cycling TA",
"Immature enterocytes 1",
"Immature enterocytes 2",
"Enterocyte progenitors",
"Enterocytes",
"M-like cells",
"BEST4+ enterocytes",
"Secretory TA",
"Immature goblet",
"Goblet",
"Tuft",
"Enteroendocrine",
"WNT2B+ Foshi",
"WNT2B+ Foslo 1",
"WNT2B+ Foslo 2",
"RSPO3+",
"WNT5B+ 1",
"WNT5B+ 2",
"Inflammatory fibroblasts",
"Myofibroblasts",
"Endothelial",
"Microvascular",
"Post-capillary venules",
"Pericytes",
"Glia",
"Macrophages",
"DC1",
"DC2",
"Inflammatory monocytes",
"CD69+ mast",
"CD69– mast",
"Cycling monocytes",
"NKs",
"ILCs",
"CD4+ activated Fos−hi",
"CD4+ activated Fos−lo",
"CD4+ memory",
"Tregs",
"CD4+ PD1+",
"CD8+ IELs",
"CD8+ LP",
"CD8+ IL-17+",
"MT-hi",
"Cycling T",
"Plasma",
"Follicular",
"GC",
"Cycling B")

factor(Idents(merged_combined), levels= myLevels)
Idents(merged_combined) <- factor(Idents(merged_combined), levels= myLevels)

features <-  c("ST6GAL1", "ST6GAL2", "ST6GALNAC1", "ST6GALNAC2", "ST3GAL1", "ST3GAL2", "ST3GAL3", "ST3GAL6","ST6GALNAC3", "ST6GALNAC4", "ST6GALNAC6", "ST8SIA1", "ST8SIA4", "ST8SIA6","ST3GAL5" )

DotPlot(merged_combined, features = features) + RotatedAxis()
############
> DotPlot(merged_combined, features = features, col.min = 1, dot.scale = 6, assay = "RNA") + RotatedAxis()
Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

**Comment by stephanyfoster** [comment]
Is it possible to orger gene names rather than cluster numbers?
thanks!

**Comment by AndyR2** [comment]
Yes.  Key is knowing that a ggplot object allows for many custom plots.

See the script suggestions from Sept 11.

I'll try to generate a couple examples.
________________________________

**Comment by AndyR2** [comment]
Here are two plots where I've custom ordered the gene names 
![image](https://user-images.githubusercontent.com/33207886/104062094-ab98a880-51ae-11eb-8620-3f25328cc6bd.png)  
![image](https://user-images.githubusercontent.com/33207886/104062212-e7cc0900-51ae-11eb-8775-d506dfe360b1.png)

**Comment by huhayahoo** [comment]
Based on reply from Satija lab, this seems to work

# Set the active ident to "cell_type"
Idents(integrated_seurat) <- "cell_type" 

# Re-order the active ident alphabetically
Idents(integrated_seurat) <- factor(integrated_seurat@active.ident, sort(levels(integrated_seurat@active.ident)))
