### ISSUE TITLE
question: is there a way to manually assign cluster identities without running findMarkers function

### ISSUE THREAD

**Issue by stillhere89** [satijalab/seurat#712]
Hi,
I am wandering if there was a way to manually assign cluster identities without running findClusters function.
I tried setCluster function but it required getCluster from a previous findClusters ( I dont see the point here If I already have the clusters, maybe I missed something)
Thanks

**Comment by satijalab** [comment]
You can use the SetIdent function to manually assign identities to cells - if you have prior knowledge.
