### ISSUE TITLE
Error - subset function returns "None of the requested variables were found" when they are actually present

### ISSUE THREAD

**Issue by Sloe-Johnson** [satijalab/seurat#7121]
Hi everyone! I am experiencing an issue subsetting a Seurat object. I have to add the metadata of a dataset to a Seurat object in a way that doesn't result in rows with empty values. The metadata is in csv format and, because of the characteristics of the dataset, doesn't include all the cells and the samples present in the Seurat Object obtained from an original h5 object - therefore I am trying to filter out the rows with empty values in either orig.ident or in barcode. However, for some reason, the code never seems to work and shows an error even though a visual examination of the object shows that there are indeed rows to remove. The error shown in all instances is the following one: 

_Error in FetchData.Seurat(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found:_ 

I have tried to use the following pieces of code:
`mySeurat <- subset(seurat_dataset, !is.na(orig.ident))`

`mySeurat <- subset(seurat_dataset, !is.na(Barcode))`

`mySeurat <- subset(seurat_dataset, !is.na(seurat_dataset$orig.ident))`

`mySeurat <- subset(seurat_dataset, !is.na(seurat_dataset$Barcode))`

`na_barcodes <- is.na(seurat_dataset$Barcode)
 mySeuratObject_filtered <- subset(seurat_dataset, !na_barcodes)`

This is how the dataset, unfiltered, looks like:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/96177128/229801619-8ba1bafc-6947-436e-9ca7-01d467b63def.png">

I checked for typos or different names in variables and they are no mistakes. Metadata results successfully added, and using typeof() to check for data type of dataset returns a S4. "length(unique(seurat_dataset$Barcode))" returns 48800, "length(unique(seurat_dataset$Barcode))" 971. 

`my_seurat <- subset(seurat_dataset, subset = Barcode %in% unique(seurat_dataset$Barcode))`
return a completely unchanged dataset. 

Does any of you have an idea on how to correct this error? Can someone help me with this issue?

**Comment by JABioinf** [comment]
Hi  @Sloe-Johnson 
I'm not from the Seurat team, but in that case would it work if you replace the NAs by an actual value (e.g. "Excluded") in your metadata table  before adding it to the Seurat object and then using simply `subset(seurat.obj, orig.ident != "Excluded")` for instance? Usually works for me so as not to use `! is.na()`.
Best,

**Comment by Sloe-Johnson** [comment]
Ok, I will try! Could you please suggest me a way to do it?

**Comment by Gesmira** [comment]
Hi, 
The way to filter out NA values is 
`obj.sub <- subset(obj, subset = Barcode != "NA")` where "Barcode" would be your metadata column of choice.
