### ISSUE TITLE
Follow Up to #6826: Scale.Data vs Data Slot for Heatmaps

### ISSUE THREAD

**Issue by atly2000** [satijalab/seurat#7122]
```
Thank you very much for explaining! I think that is the solution. 
I really appreciate it.

I am planning on splitting my data by time and plotting three heatmaps for three time points. 
If I also want to proceed with the results of AverageExpression as a heatmap in ggplot2, how can I ensure that all of these heatmaps are comparable? 

After splitting my data by time1, time2, time3, then using AverageExpression on each time dataset (group.by CD8_status), could I use these matrices to plot a heatmap in ggplot2?:

1.  time1@assays$RNA@data
2.  time2@assays$RNA@data
3.  time3@assays$RNA@data

And I could expect the values across all three heatmaps to be comparable?
```

_Originally posted by @atly2000 in https://github.com/satijalab/seurat/issues/6826#issuecomment-1428408971_
            
I am revisiting this data. Thank you for your advice!

Because Seurat does not have gene expression clustering for heatmaps, I am planning on exporting the gene expression matrices for gene expression clustering and plotting heatmaps in ggplot2.

I am planning on subsetting my data into three parts: time1, time2, time3.
```
pbmc <- my Seurat Object
DefaultAssay(pbmc) <- "RNA"
pbmc_1 <- subset(pbmc,subset = time =="1")
pbmc_2 <- subset(pbmc,subset = time =="2")
pbmc_3 <- subset(pbmc,subset = time =="3")
```

For each Time, I will run AverageExpression.
```
average_pbmc_1<- AverageExpression(object = pbmc_1,group.by="choice_clonotype",return.seurat = TRUE)
average_pbmc_2<- AverageExpression(object = pbmc_2,group.by="choice_clonotype",return.seurat = TRUE)
average_pbmc_3<- AverageExpression(object = pbmc_3,group.by="choice_clonotype",return.seurat = TRUE)
```

If I plot the expression values from these three matrices as a heatmap:
```
matrix 1: average_pbmc_1@assays$RNA@data
matrix 2:  average_pbmc_2@assays$RNA@data
matrix 3: average_pbmc_3@assays$RNA@data
```

...could I compare the gene expression of a single gene across three heatmaps?
For example, if the gene increases in expression value from matrix 1, matrix 2, to matrix 3, is it correct to assume that the expression increases over time?

I am assuming that if I were to use @scale.data instead, I cannot make this assumption because each gene's expression can only be compared to other cells in the same matrix (ex: only compare within matrix 1. Cannot compare matrix 1 to matrix 2).

**Comment by longmanz** [comment]
Hi,
Yes, you are definitely right that we cannot compare expression levels across matrices/heatmaps if we use @scale.data. But if you use @data slot then the comparison is okay as they have the same scale/unit.
