### ISSUE TITLE
RNA assay or SCTransform with v2 regularization for visualizing and post analysis ?

### ISSUE THREAD

**Issue by Kim-Gihyeon** [satijalab/seurat#7123]
Dear developers or experts,

Hello, thank you for developing good tools for scRNA analysis !
Even though there were so nice explanations and tutorials, I am confused about which count value is suitable after SCTransform.

From section #4082, I understood that [counts] slot in RNA assay is suitable for post-analysis to minimize risk or bias due to some possible variations (like a batch effect in sequencing depth) among samples.

Recently, SCTransform with v2 regularization was updated (March 27), and I figured out that developers recommended the usage of [scale.data] (pearson residual value) slot in SCT assay after SCTransform with v2 regularization. An integration step was performed by using pearson residual, which was calculated by SCTransfrom with v2 regularization. DEGs were also calculated by using pearson residual , neither [counts] or [data] slot. 

Shortly, my question is "Can I use the pearson residual count for DEG test and plotting after SCTransform with v2 regardless of batch effect, or still I should use the [counts] slot in RNA assay ?"

Additionally, If you do not mind, could you recommend any tools for helping me to choose which expression value is suitable for DEG test in each scRNA analysis? (How can I measure the variations among samples? Are there any criteria of it?)

Thank you for your help and your time, in advance.
Best regards,
Gihyeon

**Comment by saketkc** [comment]
> Recently, SCTransform with v2 regularization was updated (March 27), and I figured out that developers recommended the usage of [scale.data] (pearson residual value) slot in SCT assay after SCTransform with v2 regularization. An integration step was performed by using pearson residual, which was calculated by SCTransfrom with v2 regularization. DEGs were also calculated by using pearson residual , neither [counts] or [data] slot.

This is incorrect. The [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html#identify-differential-expressed-genes-across-conditions) uses the 'data' slot (which stores the corrected counts) for running the DE tests. This is also what we recommend for running DE generall (and not the pearson residuals i.e. scale.data slot of SCT assay). 

You can use the SCT assays data slot for DE and visualization. We do not recommend using pearson residuals of visualization or DE.

**Comment by Kim-Gihyeon** [comment]
Thank you for your answer! :)

**Comment by saketkc** [comment]
Hi @Tommy0398,

> From what I've seen with SCTransform V2 normalised data using the SCT assay for visualization is inappropriate as it seems to make cells express genes where they didn't before whereas if you lognormalise the RNA data as in https://github.com/satijalab/seurat/issues/4130 the data appears to have the same kind of expression normalization in the regions that express the gene without some cells suddenly expressing the gene.

This is theoretically impossible, but if you can point me to an example I am happy to take a look. Please make sure you are using the "SCT" assay for visualization.

**Comment by Tommy0398** [comment]
I believe I'm using the SCT assay correctly for the featureplots. 

This is my code: 
```

DefaultAssay(Optimals) <- "SCT"
Seurat::FeaturePlot(Optimals,features = "CD36",order = TRUE)
ggsave(paste0("output/",prefix,"/Featureplots_test/CD36_featureplot_SCT.png"),height = 1080,width = 1920,units = "px",dpi = 200)


DefaultAssay(Optimals) <- "RNA"
Seurat::FeaturePlot(Optimals,features = "CD36",order = TRUE)
ggsave(paste0("output/",prefix,"/Featureplots_test/CD36_featureplot_RNA_not_normalised.png"),height = 1080,width = 1920,units = "px",dpi = 200)


Optimals_test <- NormalizeData(Optimals, assay = "RNA")
DefaultAssay(Optimals_test) <- "RNA"
Seurat::FeaturePlot(Optimals_test,features = "CD36",order = TRUE)
ggsave(paste0("output/",prefix,"/Featureplots_test/CD36_featureplot_RNA_normalised.png"),height = 1080,width = 1920,units = "px",dpi = 200)

```

And these are the featureplots that I get:

RNA assay not normalized: 
![CD36_featureplot_RNA_not_normalised](https://github.com/satijalab/seurat/assets/84406675/8228c93e-4064-4a7e-9964-dd5f7a6bcbbf)


RNA assay normalized: 
![CD36_featureplot_RNA_normalised](https://github.com/satijalab/seurat/assets/84406675/7c9a7b1a-dbe8-4579-adf6-1210ca8ec370)


SCT assay:
![CD36_featureplot_SCT](https://github.com/satijalab/seurat/assets/84406675/c62e9a34-10ed-462e-89a7-e86752754d24)


You can see on the SCT assay that theres a cloud in the bottom left that wasn't there before. 

Just to make it clearer, here's the SCT and RNA normalised data using scCustomize's version of the featureplot:

RNA assay normalised:
![CD36_featureplot_RNA_nromalised_scCustomize](https://github.com/satijalab/seurat/assets/84406675/08992fc5-afdc-44ef-8afc-9eea02ec1185)



SCT assay
![CD36_featureplot_SCT_sccustomize](https://github.com/satijalab/seurat/assets/84406675/8ad8baf9-d53f-42da-8bfe-e249922fddf4)



Sorry for all the plots, I hope that makes it clearer what I'm talking about.

**Comment by saketkc** [comment]
Thanks @Tommy0398, I think it is fair to compare them visually but it has its own caveats. Can you select the subpopulation of cells and then compare their expression of CD36 from RNA and SCT data slots?

**Comment by saketkc** [comment]
Hi @Tommy0398, please open a new issue with the requested details. Thank you!
