### ISSUE TITLE
integration different datasets

### ISSUE THREAD

**Issue by IronSpirit** [satijalab/seurat#7126]
I am integrating 3 dataset for annotating another dataset currently, which are pancreatic datasets, Baron, Muraro, and Segerstolpe, the data I want to predict is Xin dataset.

Baron :
An object of class Seurat 
20125 features across 8569 samples within 1 assay 
Active assay: RNA (20125 features, 0 variable features)

Muraro:
An object of class Seurat 
19059 features across 3072 samples within 1 assay 
Active assay: RNA (19059 features, 0 variable features)

Seger:
An object of class Seurat 
26179 features across 3514 samples within 1 assay 
Active assay: RNA (26179 features, 0 variable features)

Xin:
An object of class Seurat 
39851 features across 1600 samples within 1 assay 
Active assay: RNA (39851 features, 0 variable features)

But I think I couldn't integrate dataset properly now. I got SegFault error everytime I did this code.

    merged <- merge(baron, y=c(muraro,seger))

    DefaultAssay(merged) <- "RNA"
    merged.list <- SplitObject(merged, split.by="batch")
    merged.list <- merged.list[c("baron", "muraro", "seger")]

    merged.list<- lapply(X = merged.list, FUN = function(x) {
        x <- NormalizeData(x, verbose = FALSE)
        x <- FindVariableFeatures(x, verbose = FALSE)
    })

    features <- SelectIntegrationFeatures(object.list = merged.list, nfeatures = 3000, verbose=FALSE)

    merged.list <- lapply(X = merged.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
    })

    merged.anchors <- FindIntegrationAnchors(object.list = merged.list, anchor.features = features, verbose = FALSE)
    
Is there anything wrong in this code?

**Comment by mhkowalski** [comment]
The code looks good to me. It could be that you are running out of memory, could you try integrating on a subset of cells from each of these objects?

**Comment by IronSpirit** [comment]
I am sorry that answer is too late, integrating only 2 data is fine.

**Comment by mhkowalski** [comment]
I mean taking a subset of cells from each object and then integrating (rather than integrating just 2 objects). However, I would also recommend using our Seurat v5 workflow for integration, which enables the user to integrate large datasets without loading all of the data into memory (see [here](https://satijalab.org/seurat/articles/parsebio_sketch_integration) to get started).

If you continue to have issues, please open a new issue and we're happy to help further.
