### ISSUE TITLE
Saving joint Seurat 5 object not clear

### ISSUE THREAD

**Issue by GreenGilad** [satijalab/seurat#7128]
Hi Seurat team!

I've been playing around with v5 and it is not very clear how to save the new Seurat object. I've merged several scRNA-seq libraries into a single object with one layer 

```
obj <- CreateSeuratObject(counts = lapply(res, `[[`, "counts"))
obj <- JoinLayers(obj)
```

Now I wish to save this new object. Following the [Using BPCells with Seurat Object](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html) vignette it seems like all I should do is:

```
saveRDS(
  object = obj,
  file = "atlas.Rds",
  destdir = "atlas/data/")
```

But doing so, I get the following warning:
```
Warning message:
The matrix provided does not exist on-disk
```

The documentation is also not clear about it. I would have expected the saveRDS to create the bp at the given directory if it is not there. How should I save the Seurat object?

**Comment by Gesmira** [comment]
Hi, 
Thanks for reporting this and we'll try to update the documentation/warning to make it more clear. To clarify, when running saveRDS, your Seurat object does not currently have a BPCells matrix? 

The way you are using `saveRDS` will only save the BPCells matrix to your destination directory if it already exists somewhere on disk. The idea is that you would have previously created a BPCells matrix using the `write_matrix_dir()` and `open_matrix_dir()` functionalities previously referenced in that vignette. The new functionality of `saveRDS` would then allow you to save the object and the BPCells directory (wherever it exists) in the same folder for ease of access. 

If a BPCells matrix is not in your object or a corresponding BPCells directory does not exist in your file system, saveRDS will just save your object as is.

**Comment by GreenGilad** [comment]
Hi @Gesmira 

The object is the joining of multiple libraries (using `JoinLayers`. Each library is a Seurat 4 object, loaded using `readRDS` and then coverted to the BPCells matrix (as shown in the vignette.

After joining the layers should I `write_matrix_dir`? it is not clear.

**Comment by Gesmira** [comment]
Hi @GreenGilad, 
I see, thanks for pointing out this specific issue. I'll implement a fix to deal with the scenario where there are multiple BPCells directories in one layer. 

In the meantime, you can either use the code you included at the end to write a new single matrix for the layer or as long as you keep the BPCells directories in the same position and simply run `saveRDS(atlas)`, when you load in your object, it will automatically load in those specific directories as it saves that information in the layer.

**Comment by GreenGilad** [comment]
Hi @Gesmira :)

I think it would be better to introduce some parameter by which either to allow multiple directories or to create a new BPCell matrix in a new path. This will allow the user to "override" existing data or to have an independent copy of the joint layers to work over without worrying about the "raw" pre-joined data

In addition, I am not 100% sure this issue is independent to a [different one ](https://github.com/satijalab/seurat/issues/7147) I've posted where there seems to be some limit on the overall number of layers merged and which causes all downstream analysis to fail (even just the simple `NormalizeData` step)

**Comment by Gesmira** [comment]
Hi, 
Apologies for the late response but we've now included new functionality for saving Seurat Objects with multiple BPCells directories in one layer in the newest version of SeuratObject. Please clear your session, restart R, and reinstall with: 
`remotes::install_github("mojaveazure/seurat-object", "seurat5")`

Each BPCells directory on disk belonging to the layer is accessed and copied if "destdir" is specified. Thanks again for bringing this to our attention!
