### ISSUE TITLE
ProjectData default values

### ISSUE THREAD

**Issue by GreenGilad** [satijalab/seurat#7129]
Hi Seurat team!

Geat work with the `ProjectData` function - it really helps to streamline the code and not fall into issues of UMAP vs PCA projection as I had in the past (https://github.com/satijalab/seurat/issues/5199).

Minor suggestion: set default values `sketched.reduction="pca", full.reduction = "pca.full", umap.model = "umap"`. I know these won't always be the values users will set - but these are the fitting default values for a standard "new" Seurat pipeline when using sketch (and which I suspect will be the main flow of usage of this function)

Thanks!

**Comment by yuhanH** [comment]
Thank you for your suggestions. I understand your point about setting default values to "pca", "pca.full", and "umap", which fits a standard "new" Seurat pipeline when using sketch. However, we would like to maintain the flexibility of this function and allow users to specify their parameters. It is also important that users are aware what dimensional reductions they are using and creating.

We will take your suggestion into account when we further develop and improve our documentation.
