### ISSUE TITLE
v5 Installation Error: 'SeuratObject'

### ISSUE THREAD

**Issue by OdmaaBayar** [satijalab/seurat#7133]
Hi, I am currently trying to install Seurat v5 using the "remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("satijalab/seurat", "seurat5", quiet = TRUE)" function and I get the following error across different versions of R/R Studio (currently running on R 4.1.2) : 

  Error: Failed to install 'Seurat' from GitHub:
    System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
  E> ** data
  E> *** moving datasets to lazyload DB
  E> ** inst
  E> ** byte-compile and prepare package for lazy loading
  E> Error: package ‘SeuratObject’ 4.1.3 was found, but >= 4.9.9.9049 is required by ‘Seurat’

I have tried reinstalling the 'SeuratObject' package and if I understand correctly, the latest version of this SeuratObject available is 4.1.3, so I am wondering if another package or error may be creating conflicts.

Thank you!

**Comment by adoe21** [comment]
I'm getting the same error, did you happen to find a solution?

**Comment by OdmaaBayar** [comment]
@adoe21, I ended up getting around the issue by removing all previous installations of Seurat and SeuratObject and starting from a clean slate (R 4.1.2). I think someone else also had the same problem #7162.

**Comment by Gesmira** [comment]
Hi, 
In terms of your original question, the version of SeuratObject required for Seurat v5 can be installed using 
`remotes::install_github("mojaveazure/seurat-object", "feat/CalN_generic")`
Let us know if that fixes the Seurat v5 install issue.

**Comment by OdmaaBayar** [comment]
@Gesmira Thank you, this resolves the issue!

**Comment by ghregn** [comment]
Hi,
Is there an updated link? Or am I doing something else wrong? Thank you.

```
remotes::install_github("mojaveazure/seurat-object", "seurat5")
```

_Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref seurat5
  Did you spell the repo owner and repo name correctly?
  If spelling is correct, check that you have the required permissions to access the repo._

**Comment by owenwilkins** [comment]
have this issue also

**Comment by bclaremar** [comment]
Seems that it can be installed by:

`install.packages("SeuratObject")`

nowadays
