### ISSUE TITLE
Merge function is not working.

### ISSUE THREAD

**Issue by lzyent** [satijalab/seurat#7136]
Hi, thank you for the work in developing and updating the Seurat application. 
When I was using Seurat to merge samples as Seurat Objects within seu_list, the merge function didn't work properly. 
```r
seu <- merge(x=seu_list[[1]], y=seu_list[2:length(seu_list)], add.cell.ids = names(seu_list))
seu
An object of class Seurat 
22564 features across 39487 samples within 1 assay 
Active assay: RNA (22564 features, 2000 variable features)
 21 layers present: counts.1, counts.2, counts.3, counts.4, counts.5, counts.6, counts.7, counts.8, counts.9, counts.10, counts.11, counts.12, counts.13, counts.14, counts.15, counts.16, counts.17, counts.18, counts.19, counts.20, counts.21
```
As you can see, layers of count matrices from individual samples were not concatenated.
Thanks again for your efforts!

**Comment by inofechm** [comment]
I think you need to use the new `JoinLayers()` function.
It will take in a seurat object with multiple layers and join them into one.

**Comment by stefanonard85** [comment]
> `JoinLayers()` function.

THE FUNCTION does not work and gives this error:
> RES <- JoinLayers(RES)
Error in UseMethod(generic = "JoinLayers", object = object) : 
  no applicable method for 'JoinLayers' applied to an object of class "c('SCTAssay', 'Assay', 'KeyMixin')"

**Comment by fhss** [comment]
> > `JoinLayers()` function.
> 
> THE FUNCTION does not work and gives this error:
> 
> > RES <- JoinLayers(RES)
> > Error in UseMethod(generic = "JoinLayers", object = object) :
> > no applicable method for 'JoinLayers' applied to an object of class "c('SCTAssay', 'Assay', 'KeyMixin')"

I'm having the same problem, did you manage to solve it?

**Comment by Morteza1450** [comment]
Hi,
Please use the following command, I hope the problem will be solved.

`obj<- JoinLayers(obj,  assay = "RNA")`

**Comment by marencc** [comment]
Just to add more information in the case where metadata is lost by JoinLayers, I found this [thread,](https://github.com/satijalab/seurat/issues/8207) that explains that the best way to use the function JoinLayers is: 

`merged_seurat[["RNA"]] <-JoinLayers(merged_seurat[["RNA"]])`

which can be safely run after merging two or more seurat obj as usual, and apparently metadata is not lost.

**Comment by egumnit** [comment]
I am still having this issue after running the recommended fix
>TP73_all<-merge(x= diet_TP73_dev_pos, y=diet_adult_TP73_neurons)
> TP73_all[["RNA"]] <-JoinLayers(TP73_all[["RNA"]])
Error in UseMethod(generic = "JoinLayers", object = object) : 
  no applicable method for 'JoinLayers' applied to an object of class "c('Assay', 'KeyMixin')"
TP73_all<- JoinLayers(TP73_all,  assay = "RNA")
Error in UseMethod(generic = "JoinLayers", object = object) : 
  no applicable method for 'JoinLayers' applied to an object of class "c('Assay', 'KeyMixin')"
