### ISSUE TITLE
 Positive Expression Data Values

### ISSUE THREAD

**Issue by merveyrc** [satijalab/seurat#7138]
HelIo, 
I am currently in need of expression data for both healthy control and stimulated conditions of each cell type that I have determined. To obtain this data, I first created subsets of each cell type for both healthy and stimulated conditions.

In attempting to view the expression values for the healthy condition of one particular cell type, CD4MEMORY_Healthy, I ran the following code: 
CD4MEMORY_Healthy@assays[["integrated"]]@scale.data

 However, I have noticed that some of the values in the data are negative, which is not what I was expecting. My question is how I can view the expression data with only positive values ( without zeros)? Also I am wondering that can I solve this problem by applying log2 normalization? if it is possible, how can I do? Thank you for your time and assistance.

**Comment by alikhuseynov** [comment]
the `"integrated"` assay is only for PCA, UMAP, clusterting, and it not for differential gene expression analysis or anything downstream where you need raw or normalized counts. 
See also #1717

**Comment by saketkc** [comment]
You should switch to the RNA or SCT assay for differential expression analysis. The integrated values are not (physically) interpretable and hence should not be used for DE.

**Comment by merveyrc** [comment]
Thank you for your returns. How can I do log2 normalization to count data of RNA assay? I need positive gene expression values.

**Comment by alikhuseynov** [comment]
you can do log1p of raw counts or use the normalized `"data"` slot
