### ISSUE TITLE
fastMNN need scaleData?

### ISSUE THREAD

**Issue by skytguuu** [satijalab/seurat#7139]
Hi,

I tried to integrated several different single cell RNA-seq datasets using the wrapper of fastMNN in Seurat following the tutorial (https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/fast_mnn.html). However, I found there is no scaled data before RunFastMNN. I was wondering whether I need to do scaled data before RunFastMNN, or do scaled data after RunFastMNN? If we added scale data before RunFastMNN, does the result will changed greatly or not? 

Could you give me advise that whether we need scale data before or after RunFastMNN?

 I noticed there is no ScaleData step in the tutorial, does this mean fastMNN don't need to use the scaled data?

Thanks.

**Comment by Gesmira** [comment]
Correct, you do not need to` ScaleData` before integration with fastMNN. For downstream steps, such as dimensional reduction, `ScaleData` should be run. I reccomend following the tutorial you linked as well as the [Seurat Integration Tutorial](https://satijalab.org/seurat/articles/integration_introduction.html).
