### ISSUE TITLE
Questions about the supplymentary of Bulter et al. paper

### ISSUE THREAD

**Issue by Yuanxin-Wang** [satijalab/seurat#714]
Hi,

I'm new to the single cell seq. Thank you so much for developing the Seurat package in r and making the data processing so much convenient. But I have some questions after reading the supplementary of the paper 'Integrated analysis of single-cell transcriptomic data across conditions, technologies and species'.

1. For the part 3 'identification of dataset-specific cells', at the bottom of page 3. 'We then form orthonormal bases D and E via QR decomposition such that A=DR B=ER'. Why here can we get the same R (the triangular matrix) from both A and B's QR decomposition?

2. After the QR decomposition, X and Y are projected onto D and E. Since D and E are not the eigenvectors of A and B, why we choose to project X and Y onto them and reconstruct the result for the later variance calculation?

3. For the part 4 'Aligning canonical correlation vectors',at the middle of page 5, 'This procedure robustly corrects for differences in feature scale, $\phi_{i}\^prime=\phi_i\^prime+min_{z=10,...90}\abs(Q_{\phi_{i}^\prime}(z)-Q_{\theta_{i}^\prime}(z))$'. Why there is always a plus after the $\phi_i\^prime$? If $\phi$ is greater than $\theta$, couldn't a minus will make $\phi$ and $\theta$ closer to each other?

Thank you so much in advance!

**Comment by andrewwbutler** [comment]
Hi,

1. The R matrices here are not going to be the same. We do this step to form the bases D and E here , which will not be the same either.
2. The goal of this step is to compute the amount of variance explained by the first N dimensions in both CCA and PCA space and compare the ratio. We would expect that cells from non-overlapping populations would be well explained in the PCA space but not in the CCA space and thus examining that ratio may allow us to identify those cells.
3. Sorry for the confusion on this step. We take the the absolute value of the differences between Q_{\phi_{i}^\prime}(z) and Q_{\theta_{i}^\prime} to determine the minimum but then add the actual value to  Phi_i^prime so this could be either positive or negative. You can see the code for that step [here](https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/alignment.R#L177-L199)

**Comment by Yuanxin-Wang** [comment]
Thanks for the explanation. But for the second question, why we need to do the QR decomposition to compute the amount of variance explained by the first N dimension in CCA space? Since u and v are eigenvectors, why don't we just project X and Y directly to the normalized u and v to calculate the variance?
