### ISSUE TITLE
How to randomly order cells of a seurat object?

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#7143]
After merging different samples I tried these 2 options to reorder cells randomly and not by sample but didnt change anything
```
option1: seurat[ ,sample(Cells(seurat), size= ncol(seurat))]
option2: seurat = subset(seurat, cells=sample(Cells(seurat), size= ncol(seurat)))
```
Is there another way to rerder cells after creating the seurat object?

**Comment by saketkc** [comment]
You can reorder cells during plotting (I cannot think of another use case) by passing the `cells` parameters:

```
DimPlot(object, cells = sample(Cells(object))
FeaturePlot(object, cells = sample(Cells(object)), features = "PLP1")
```
