### ISSUE TITLE
Bug in the setting of `mean.fxn` for `FindMarkers`

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#7146]
If:
```
norm.command <- paste0("NormalizeData.", assay)
Command(seurat_all, command = norm.command, value = "normalization.method")
```

gives:
> NormalizeData.RNA has not been run or is not a valid command.

mean.fxn is set to:
```
function(x) {
    return(log(x = rowMeans(x = x) + pseudocount.use, base = base))
}
```

even if `slot = "data"`.

This can happen if you have run `NormalizeData` on a previous Seurat object, subset and renamed that Seurat object, and not re-run `NormalizeData`.

_Originally posted by @lucygarner in https://github.com/satijalab/seurat/issues/7107#issuecomment-1503647848_

**Comment by lucygarner** [comment]
Due to the following code in the `FoldChange.Assay` function:

 ```
 norm.command <- paste0("NormalizeData.", assay)
  norm.method <- if (norm.command %in% Command(object = object) && is.null(x = reduction)) {
    Command(
      object = object,
      command = norm.command,
      value = "normalization.method"
    )
  } else if (length(x = intersect(x = c("FindIntegrationAnchors", "FindTransferAnchors"), y = Command(object = object)))) {
    command <- intersect(x = c("FindIntegrationAnchors", "FindTransferAnchors"), y = Command(object = object))[1]
    Command(
      object = object,
      command = command,
      value = "normalization.method"
      )
    } else {
    NULL
    }
```

**Comment by lyj790** [comment]
Hi everyone,
I have the same proble. I've just update Seurat from 4.0.5.9000 to 4.9.9.9045, and I got a different FC result in the new version.
When we run FoldChange( ), it should have an argument  `norm.method='LogNormalize'` pass to FoldChange.Assay( ). But it didn't.

**Comment by saketkc** [comment]
Hi @lucygarner,  

I have just pushed https://github.com/satijalab/seurat/commit/992c1a96693b1467160969625edc8a5c80ab0867 to develop branch which should fix this and related issues. Can you pull from the develop branch and re-open this issue if you are still facing issues?

```r
devtools::install_github("satijalab/seurat", branch="develop")
```

**Comment by lucygarner** [comment]
Great, thank you.
