### ISSUE TITLE
ADT assay disappear after filtering low quality cells.

### ISSUE THREAD

**Issue by tufeiyinjie** [satijalab/seurat#7148]
Recently, I generate a seurat object with RNA and ADT assay after reading H5 files. However, when I extracted metadata for filtering low quality cells, and replace the filtered metadata back into the object. The ADT assay just disappear. But, the ncount_ADT and nfeature_ADT columns are still in the metadata. I am curious when happened to the ADT assay? Is there a way to keep the ADT assay after filtering the low quality cells?

Thanks.

**Comment by ollieeknight** [comment]
can you share the code you use before, during and after the assay disappears?

**Comment by tufeiyinjie** [comment]
@ollieeknight Thanks for your quick reply. Here are my codes listed below.
> se_obj <- readRDS(file = "/ix1/rferris/feitu/cellranger/fastq/18-139/seurat_obj/CD3_130_131_til.rds")
> Assays(se_obj)
[1] "RNA" "ADT"
> ##Remove genes that have zero expression in all cells
> #Output a logical vector for every gene on whether the more than zero counts per cell
> #Extract counts
> counts <- GetAssayData(object = se_obj, slot = "counts")
> #Output a logical vector for every gene on whether the more than zero counts per cell
> nonzero <- counts >0
> #Sums all TRUE values and returns TRUE if more than 10 TRUE values per gene
> keep_genes <- Matrix::rowSums(nonzero) >= 10
> #Only keeping those genes expressed in more than 10 cells
> filtered_counts <- counts[keep_genes,]
> #Reassign to filtered Seurat object
> se_obj <- CreateSeuratObject(filtered_counts,meta.data = se_obj@meta.data)
> ##Generate quality metrics
> #Add number of genes per UMI for each cell to metadata
> se_obj$log10GenesPerUMI <- log10(se_obj$nFeature_RNA)/log10(se_obj$nCount_RNA)
> #Compute percent mito ratio
> se_obj$mitoRatio <- PercentageFeatureSet(object = se_obj, pattern = "^MT-")
> se_obj$mitoRatio <- se_obj$mitoRatio/100
> #Create metadata data frame
> metadata <- se_obj@meta.data
> #Add cell IDs to metadata
> metadata$cells <- rownames(metadata)
> #Rename columns
> metadata <- metadata %>%
+    dplyr::rename(seq_folder = orig.ident,
+                  nUMI = nCount_RNA,
+                  nGene = nFeature_RNA)
> #Create treatment_timing column
> metadata$treatment_timing <- NA
> metadata$treatment_timing[which(str_detect(metadata$cells, "pre"))] <- "pre"
> metadata$treatment_timing[which(str_detect(metadata$cells, "post"))] <- "post"
> #Create patient_ID column
> metadata$patient_ID <- NA
> metadata$patient_ID[which(str_detect(metadata$cells, "130"))] <- "130"
> metadata$patient_ID[which(str_detect(metadata$cells, "131"))] <- "131"
> #Create cell_source column
> metadata$cell_source <- NA
> metadata$cell_source[which(str_detect(metadata$cells, "P"))] <- "pbl"
> metadata$cell_source[which(str_detect(metadata$cells, "T"))] <- "til"
> #Add metadata back to Seurat object
> se_obj@meta.data <- metadata
> DefaultAssay(se_obj)
[1] "RNA"

**Comment by ollieeknight** [comment]
alright, let's simplify things slightly, where ```alldata``` is your seurat object:
```
total_counts_per_cell <- colSums(alldata@assays$RNA@counts)
mito_genes <- rownames(alldata)[grep("^MT-", rownames(alldata))]
alldata$percent_mitochondrial <- colSums(alldata@assays$RNA@counts[mito_genes, ])/total_counts_per_cell
ribo_genes <- rownames(alldata)[grep("^RP[SL]", rownames(alldata))]
alldata$percent_ribosomal <- colSums(alldata@assays$RNA@counts[ribo_genes, ])/total_counts_per_cell

features <- rownames(alldata@assays$RNA)[Matrix::rowSums(alldata@assays$RNA@counts) > 0] # can change this number for any, perhaps 10
alldata@assays$RNA <- subset(alldata@assays$RNA, features = features)
```

I think as you're subsetting features based on counts, and these rownames aren't in your ADT assay, they're removed. See if the code above tuned to your dataset fixes the issue.

**Comment by ollieeknight** [comment]
if you want to remove the assay, you can do
```
alldata@assays$RNA <- NULL
```

**Comment by tufeiyinjie** [comment]
Thanks.

**Comment by ollieeknight** [comment]
> Thanks.

could you mark as completed?

**Comment by mhkowalski** [comment]
Closing this, thanks @ollieeknight. They are correct that if you make a new SeuratObject with the `CreateSeuratObject` function and provide the RNA counts only, this will not include an ADT assay.
