### ISSUE TITLE
MultiCCA and extracting the components for follow up analysis

### ISSUE THREAD

**Issue by klecao** [satijalab/seurat#715]
Hello,
I am running a Multi CCA on several data sets and would like to extract components to carry on with my own analyses.

The classical Seurat way would be in 4 steps:
obj = RunMultiCCA(my_data).                                      # step 1
obj = AlignSubspace(obj)                                            # step 2
obj = RunPCA(obj, reduction.use = "cca.aligned") # step 3
PCAPlot(obj, do.return = T)                                         # step 4

Now, I would like to skip steps 3 and 4 to run my own favourite PCA function. I can extract the components from CCA or PCA (from steps 2 or 3):
extract.cca <- GetCellEmbeddings(object = obj, reduction.type = "cca.aligned")
extract.pca <- GetCellEmbeddings(object = obj, reduction.type = "pca")

What I am surprised to see is that if I run a PCA on the extract.cca components, I do not get the same results as in Step 4. Instead, I obtain the exact same sample plot only when I run a PCA on the extract.pca components! Could I have more clarification about what is done in Steps 3 and 4 in Seurat?

Thank you very much!

**Comment by concatenize** [comment]
The developers can correct me if this is wrong, but my understanding is that Seurat runs PCA based on the scaled expression values, not based on the CCA embeddings. You're comparing PCA(PCA(data)) against PCA(data), not against PCA(CCA(data)). Typical analyses with Seurat's CCA + DTW would feed the aligned CCA embeddings into t-SNE, UMAP, clustering, et cetera.

**Comment by klecao** [comment]
Thank you @concatenize, are you saying that:
a -  obj = RunPCA(obj, reduction.use = "cca.aligned") is actually running obj = RunPCA(obj)?
b - that I could only run CCA + DTW on tSNE or UMAP (I would agree that a PCA on CCA(data) does not make much sense from a data dimension reduction perspective).
c - that visualising the CCA + DTW components directly (using GetCellEmbeddings) is not correct
or all of the above? :)

**Comment by klecao** [comment]
Thanks @concatenize, good to know about a. And yes I agree with you RE b. And will think about c. I m closing the issue.
