### ISSUE TITLE
Cluster Differential Abundance Testing

### ISSUE THREAD

**Issue by Sidy2015** [satijalab/seurat#7152]
Dear Seurat Team, 

I am analysing a single cell data set using Seurat. I have 3 datasets representing 3  conditions. After integration and clustering, i want to test the cluster abundance between the different conditions. 
Is it a way to do this kind of test in Seurat? 
Or should i use common statistical  tests like Chi2 test?

Thank you for any suggestion
Sidy

**Comment by Sidy2015** [comment]
Thank you a lot. I will check it out

**Comment by apal6** [comment]
Hi @Sidy2015,

Were you able to run milo? I found another method [https://github.com/phipsonlab/speckle] for similar kind of analysis. I am not sure of any benchmarked method. Would be helpful to hear your thoughts on Milo. 

Thanks!
