### ISSUE TITLE
subset error 

### ISSUE THREAD

**Issue by wbvguo** [satijalab/seurat#7155]
Hi, thanks for maintaining this tool, I came across an error using `subset`

```
tmp = subset(seurat_raw, subset = (Type %in% c("InVivo", "InVitro")) & (!(Time %in% c("D", "E"))))
```

Error: 
```
Error in Time %in% c("D", "E"): object 'Time' not found
```

while the following code is working smoothly
```
tmp <- subset(seurat_raw, subset = (Type %in% c("InVivo", "InVitro")) & (Time %in% c("A", "B", "C")))
```

It seems it cannot recognize the `not in` symbol `!(x %in% y)`, may I ask if you have any idea about the reason?

Thanks,
Wenbin

**Comment by ollieeknight** [comment]
are 'Type' and 'Time' entries of metadata in your object?

**Comment by wbvguo** [comment]
yes, they are in the colnames of the metadata in the object

**Comment by ollieeknight** [comment]
try this: 
```
seurat_raw <- SetIdent(seurat_raw, value = 'Type')
seurat_raw <- subset(seurat_raw, idents = c('InVivo','InVitro'))
seurat_raw <- SetIdent(seurat_raw, value = 'Time')
seurat_raw <- subset(seurat_raw, idents = c('D','E'))
```

**Comment by ollieeknight** [comment]
I understand, however my previous comment is the recommended way of subsetting. See [here](https://satijalab.org/seurat/articles/essential_commands.html#seurat-object-interaction)

**Comment by mhkowalski** [comment]
Yes, if you would like to subset a group based on a NOT statement (i.e. all cells where Time is not equal to D or E), I would use the following:
```
Idents(seurat_raw) <- seurat_raw$Time
sub <- subset(seurat_raw, idents = c('D', 'E'), invert=TRUE)
```
