### ISSUE TITLE
Generating a "filtered_feature_bc_matrix.h5" with 10X Visium data components

### ISSUE THREAD

**Issue by ariskare** [satijalab/seurat#7157]
Hi all, I recently acquired access to a 10X Visium dataset, and was able to download the following components from a single experiment: "matrix.mtx", "genes.tsv", "barcodes.tsv", "tissue_lowres_image.png", "scalefactors_json.json", "tissue_positions_list.csv", and a ".tif" file. I can't use Load10X_Spatial() to read this data, as this function requires an ".h5" format, and unfortunately, we do not have immediate access to the original .h5 file. 

I was wondering, is there a way to generate an ".h5" file with the components I have? I imagine all the data to do this is present, but I do not know if there is a pipeline to automate this. Thank you so much for the help.

**Comment by alikhuseynov** [comment]
These should help
[Read10X](https://satijalab.org/seurat/reference/read10x)
[ReadMtx](https://satijalab.org/seurat/reference/readmtx)

**Comment by ariskare** [comment]
I was actually able to find a solution from the 10X Applied Bioinformatics team. 

`library(DropletUtils)
library(Seurat)

filter_matrix <- Read10X("./filtered_feature_bc_matrix/")

write10xCounts("./filtered_feature_bc_matrix.h5", filter_matrix, type = "HDF5",
               genome = "mm10", version = "3", overwrite = TRUE,
               [gene.id](http://gene.id/) = rownames(filter_matrix),
               gene.symbol = rownames(filter_matrix))`

From 10X: You can put the files "matrix.mtx", "genes.tsv", and "barcodes.tsv" in the directory filtered_feature_bc_matrix and use the following R codes to convert the matrix into h5 file. Here I'm using a mouse mm10 reference result as an example.

**Comment by Icedoesnotburn** [comment]
To follow-up on this, I got 10+ individual samples from a public dataset, where each sample has a;
barcodes.tsv
features.tsv
matrix.mtx

I have merged these samples into a single Seurat Object (allsamples), but now I need to convert this back into a filtered_feature_bc_matrix.h5

Is this possible in any way? 
Either from the individual 10+ barcode/feature/matrix files or from the merged Seurat Object?

Thanks in advance

**Comment by alikhuseynov** [comment]
> To follow-up on this, I got 10+ individual samples from a public dataset, where each sample has a; barcodes.tsv features.tsv matrix.mtx
> 
> I have merged these samples into a single Seurat Object (allsamples), but now I need to convert this back into a filtered_feature_bc_matrix.h5
> 
> Is this possible in any way? Either from the individual 10+ barcode/feature/matrix files or from the merged Seurat Object?
> 
> Thanks in advance

I know those only:

- [`DropletUtils::write10xCounts`](https://rdrr.io/github/MarioniLab/DropletUtils/man/write10xCounts.html)
- [`scCustomize::Create_10X_H5`](https://samuel-marsh.github.io/scCustomize/reference/Create_10X_H5.html
)
