### ISSUE TITLE
Failed to reproduce 

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7159]
Hi
I have updated Seurat version and then i am trying to reproduce same umap but unable to do.
I don't remember which version i actually used previously to analyze data?
Any way how to recreate same umap?I have tried almost 3.0,3.1,.3.2.2, 3.2.3,3,4.0.4. but its not reproducing?
Any guidance how can i sort this out?

**Comment by nathan-nakatsuka** [comment]
Dear @zara03, we need more information to figure this out. It is unlikely that there is a difference due to different Seurat versions. You might have changed your Seurat object leading to a new UMAP. Try to look back at your code if some change happened to your data between the two plots.

**Comment by zara03** [comment]
Hi i was using updated version of R fixed it.Thank you

**Comment by zara03** [comment]
Can you please look into my issue #7202


From: nathan-nakatsuka ***@***.***>
Date: Friday, April 21, 2023 at 4:44 PM
To: satijalab/seurat ***@***.***>
Cc: Syeda, Zehra ***@***.***>, Mention ***@***.***>
Subject: Re: [satijalab/seurat] Failed to reproduce (Issue #7159)

Closed #7159<https://github.com/satijalab/seurat/issues/7159> as completed.
