### ISSUE TITLE
DEG analysis by cluster using DEseq2 analysis 

### ISSUE THREAD

**Issue by kysbbubbu** [satijalab/seurat#716]
Hello.

I try to do DEG analysis by cluster using DEseq2 analysis.

After reading previous users' questions, I understand that I have to do analyze on the non-normalized matrix.  I clustered cells on the raw.data by  using "SetAllIdent" and do DEG analysis by DEseq2. 

my gene-cell matrix is about 20,000 gene, 5000 cells and do analysis on server computer 

converting counts to integer mode 
gene-wise dispersion estimates <-- it takes several hours in this step 

My question is :
1. is DEseq 2 analysis takes much more time than default method? 
2. Is my method is right for doing DEG analysis between clusters orginally formed by normalized data?

Thanks in advance

**Comment by andrewwbutler** [comment]
Hi, 

1. Yes, it is likely that DESeq2 will take longer than the default method.
2. I'm not sure exactly what you mean by "clustered cells on the raw.data by using "SetAllIdent". The clustering analysis doesn't have to change based on which DE test you want to do. It's just which transformation of the data (or in this case the raw counts), the DE test is being performed on that matters.
