### ISSUE TITLE
Spatial Transcriptome Technology（ST(100um), The predecessor of 10X Visium technology）

### ISSUE THREAD

**Issue by wang0430** [satijalab/seurat#7160]
Hi, thank you so much for developing such a great tool, I have a question for you.
Can seurat analyze data from ST technology? I haven't seen any tutorials so far, so I don't know how to analyze it?

**Comment by alikhuseynov** [comment]
I'm not from the Seurat team.
However, it should be possible, but you will need to do some data preparation from older ST methods.
this older workflow of [Spaniel package](https://github.com/RachelQueen1/Spaniel/blob/Version_0.9.9/vignettes/spaniel-vignette.Rmd) should help to create Seurat object.
