### ISSUE TITLE
Seurat5 install  ! System command 'R' failed

### ISSUE THREAD

**Issue by wang0430** [satijalab/seurat#7161]
Hello, thank you very much for upgrading seurat. Recently, the following error will always be displayed when installing seurat5. I don’t know how to solve it. Do you have any solutions?

Installing 1 packages: fastDummies
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Error: Failed to install 'Seurat' from GitHub:
  ! System command 'R' failed

**Comment by chrarnold** [comment]
Exactly the same here. Happens within Rstudio using R 4.2.2.

**Comment by FEI38750** [comment]
Same error:  "! System command 'R' failed" within Rstudio R 4.2.2

**Comment by Gesmira** [comment]
Hi, it's possible there is a dependency issue. Can you rerun the install with `quiet = FALSE` so we can discern where the error is occurring?

**Comment by stefanonard85** [comment]
<img width="715" alt="Screenshot 2023-04-29 at 1 16 58 PM" src="https://user-images.githubusercontent.com/16965990/235315376-c1d04c3c-4622-4787-8c0b-b5597dc4b9df.png">

**Comment by AustinHartman** [comment]
Hi @stefanonard85, please update SeuratObject with `remotes::install_github("mojaveazure/seurat-object", "seurat5")` which is required for Seurat v5

**Comment by elenab-creator** [comment]
Hello! I had the same problem and followed your suggestion only to run into the following error:
![Screenshot 2023-07-18 at 16 51 42](https://github.com/satijalab/seurat/assets/76881545/7f554180-c269-4e9b-ab21-923d45b32e70)
Can someone help?

**Comment by Jiayi-Zheng** [comment]
@AustinHartman 
Hello, I updated my seuratobject accordingly, but the error message remains the same with installing seurat5.

**Comment by nina-hahn** [comment]
Dear all,
Same problem here as well. Did anybody find a solution? 
Best,
Nina

**Comment by YY-SONG0718** [comment]
Hello all,

Run into the same issue. For me it was `ERROR: dependency ‘BPCells’ is not available for package ‘Seurat’` and the complaint is that BPCells cannot find the hdf5 install.

After digging around I believe it is because I have an x86 R installation but the ARM hdf5 was installed, which is the default by homebrew. [This page](https://github.com/bnprks/BPCells#macos) by BPCells explains the issue.

Since the BPCells dependency is new to SeuratV5 it did not pop up previously.

Yuyao

**Comment by Flu09** [comment]
> Hi @stefanonard85, please update SeuratObject with `remotes::install_github("mojaveazure/seurat-object", "seurat5")` which is required for Seurat v5

> remotes::install_github("mojaveazure/seurat-object", "seurat5")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref seurat5

  Did you spell the repo owner and repo name correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by nbartonicek** [comment]
Same as the above:
> remotes::install_github("mojaveazure/seurat-object", "seurat5") 
Using github PAT from envvar GITHUB_PAT. Use `gitcreds::gitcreds_set()` and unset GITHUB_PAT in .Renviron (or elsewhere) if you want to use the more secure git credential store instead.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref seurat5

  Did you spell the repo owner and repo name correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by ss6025** [comment]
I notice this issue has been closed. but what was the solution? I have encountered the same error.

**Comment by Gesmira** [comment]
Hi all, 
You can now install these packages directly from CRAN. Please try
```
install.packages("SeuratObject")
install.packages("Seurat")
```
