### ISSUE TITLE
namespace ‘SeuratObject’ 4.1.1 is already loaded, but >= 4.9.9.9060 is required

### ISSUE THREAD

**Issue by wang0430** [satijalab/seurat#7162]
Hello author,
I am installing Seurat5, but it shows that the version of SeuratObject that depends on it is 4.9.9.9060, but how can I upgrade this package?

**Comment by Gesmira** [comment]
Hi, 
the version of SeuratObject required for Seurat v5 can be installed using
`remotes::install_github("mojaveazure/seurat-object", "seurat5")`
