### ISSUE TITLE
subset getting weird 

### ISSUE THREAD

**Issue by joe-jhou2** [satijalab/seurat#7167]
```r
# insert reproducible example here
# CellType exists in the meta.data, all cell types are correct. the code below worked well before
subset(HSV_integrated, subset = CellType %in%  c("CD4 T", "CD4 Treg", "CD8 T", "NK", "Ki67+ T"))

# Suddenly, it sees to subset the data (seurat object size is small). But, when I DimPlot() after subsetting, it still shows all subsets. 

# Then I try to do like this:
subset(HSV_integrated, idents = c("CD4 T", "CD4 Treg", "CD8 T", "NK", "Ki67+ T")) 
# Idents(HSV_integrated) is correctly matching. 

# Now, DimPlot() shows these subsetted clusters!!! BUT meta.data still have all subsets name, it seems the subset not apply on the meta data. 

# I'm so confused.  
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Yes you are correct that code you posted will subset the object but will not drop factor levels from the meta data.  See previous post for info on how to dropp levels from meta data or during subset.
https://github.com/satijalab/seurat/issues/5069#issuecomment-921887662
https://github.com/satijalab/seurat/issues/5069#issuecomment-918189691

Best,
Sam

**Comment by mimisikai** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. Yes you are correct that code you posted will subset the object but will not drop factor levels from the meta data. See previous post for info on how to dropp levels from meta data or during subset. [#5069 (comment)](https://github.com/satijalab/seurat/issues/5069#issuecomment-921887662) [#5069 (comment)](https://github.com/satijalab/seurat/issues/5069#issuecomment-918189691)
> 
> Best, Sam

Hi Sam, Thanks. I think it's not only about dropping unused levels. 
`HSV_Tcell_subClusters@meta.data[['CellType']]` still have all cell types. 
`> unique(HSV_Tcell_subClusters@meta.data[['CellType']])
 [1] "CD4 T"         "Endothelial"   "CD8 T"         "NK"            "Fibroblast"    "Myeloid"       "CD4 Treg"      "B cell"        "Smooth Muscle" "Keratinocyte" 
[11] "pDC"           "Ki67+ T"   `

I guess something went wrong. 
Before subsetting: 
`> dim(HSV_integrated@meta.data)
[1] 36654   172
> dim(HSV_integrated)
[1] 33579 36654`

After subsetting:
`> dim(HSV_Tcell_subClusters@meta.data)
[1] 20881   172
> dim(HSV_Tcell_subClusters)
[1] 33579 20881`

However, subset by `subset(HSV_integrated, idents = c("CD4 T", "CD4 Treg", "CD8 T", "NK", "Ki67+ T")) `, meta.data size is smaller, but when checking meta cell type, it still has all cell types as shown above.

**Comment by yuhanH** [comment]
Thank you @samuel-marsh  for answering this issue. I would have the same guess. 
hi @mimisikai , could you post a reproducible example using `pbmc_small`? Thank you.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
