### ISSUE TITLE
Add new.cell.ids to integration

### ISSUE THREAD

**Issue by SomeGuy3865** [satijalab/seurat#7168]
Extremely simple request. When you merge seurat objects, there is an options called add.cell.id to each object. This is obviously useful as individual cell barcodes can overlap between different experiments, leading to them being dropped (duplicate cell id's which need to be enforced, at least as i understand it, or at least later on you can add metadata based on the source cells). 

I'd suggest to add that feature as an option in integrate.

**Comment by saketkc** [comment]
Hi @SomeGuy3865, thanks for the request. We do not have the bandwidth to implement this in the near future. I would recommend making use of `RenameCells(object, add.cell.id='XYZ')` option for now.

**Comment by SomeGuy3865** [comment]
That is what I ended up doing. Just a suggestion - I know there must be a million things higher in the priority list. Thank you.

Sincerely,
Kevin Maroney

M.S. Biotechnology
University of California
PhD student
University of Alabama at Birmingham

________________________________
