### ISSUE TITLE
Differential expression between two conditions

### ISSUE THREAD

**Issue by ClaireG18** [satijalab/seurat#717]
Dear Seurat Team,

I am approaching the analysis of single-cell RNA-seq data pre-processed with the Cell Ranger pipeline.

If the goal is comparing expression in all cells of one "treated" sample versus all cells in a "control" sample  (~4000 cells each), is the recommended pipeline the one in this tutorial https://satijalab.org/seurat/immune_alignment.html, in which two separate objects are created/filtered/normalized, and then alignment is performed before using FindMarkers?

Or should rather a single object be created by merging the two samples and FindMarkers used to compare cells originally in the treated sample versus those in the control one without performing alignment?

Thanks in advance for your advice!

**Comment by satijalab** [comment]
If the goal is to compare expression in all cells - then you should merge the samples and run FindMarkers.

If the goal is to compare the expression of specific cell subsets between the two conditions, and the shared biological identity of these subsets is lost due in a joint analysis, we suggest the alignment workflow.

**Comment by ClaireG18** [comment]
Thank you for the clarification
