### ISSUE TITLE
Map Query Not Recognizing Returned UMAP Model

### ISSUE THREAD

**Issue by katimbach** [satijalab/seurat#7179]
I am having an issue similar to that referenced below, but I am using Seurat version 4.3.0. I have tried to map the same reference on two separate Seurat query objects, on which I have previously run RunUMAP(return.model= TRUE), but I get the same error mentioned multiple times. 

I wonder if this is related to the following Warning that appears when running RunUMAP on the objects: 
```
Warning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
```

Could somebody from the Seurat development team provide some guidance as to how to proceed? Thank you! 

 
              @cdarby Hi， I ran the RunUMAP with "return.model=TRUE", but still get the error. I also used the latest Seurat version.
`Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first`

Thanks,
Yale

_Originally posted by @Yale73 in https://github.com/satijalab/seurat/issues/3615#issuecomment-834075094_

**Comment by yuhanH** [comment]
hi @katimbach 
Could you post more scripts about building the reference and mapping the query?

**Comment by NikolayZolotarev** [comment]
> hi @katimbach Could you post more scripts about building the reference and mapping the query?

Hi @yuhanH ,
I have the same problem.

I am using Stewart et al. 2019 data as a reference (https://azimuth.hubmapconsortium.org/references/#Human%20-%20Kidney). And I am trying to map data from Muto et al. 2021.

This is my code:

```
#Reference
kidney_ref <- readRDS(file = "kidney_demo_stewart.rds")
kidney_ref <- NormalizeData(kidney_ref)
kidney_ref <- FindVariableFeatures(kidney_ref)
kidney_ref <- ScaleData(kidney_ref, verbose = FALSE)
kidney_ref <- RunPCA(kidney_ref, npcs = 30, verbose = FALSE)
kidney_ref <- RunUMAP(kidney_ref, reduction = "pca", dims = 1:30)
kidney_ref <- FindNeighbors(kidney_ref, reduction = "pca", dims = 1:30)
kidney_ref <- FindClusters(kidney_ref, resolution = 0.5)

#Query
kidney_Muto <- Read10X_h5(file="GSM4572192_Control1_filtered_feature_bc_matrix.h5",
                          use.names = TRUE, unique.features = TRUE)
kidney_Muto <- CreateSeuratObject(counts = kidney_Muto, project = i,  min.cells = 3, min.features = 200)
kidney_Muto <- NormalizeData(kidney_Muto)
kidney_Muto <- FindVariableFeatures(kidney_Muto, selection.method = "vst", nfeatures = 2000)

kidney_Muto <- ScaleData(kidney_Muto, verbose = FALSE)
kidney_Muto <- RunPCA(kidney_Muto, npcs = 30, verbose = FALSE)

transfer_anchors <- FindTransferAnchors(reference = kidney_ref, query = kidney_Muto, dims = 1:30, 
                                        reference.reduction = "pca")

kidney_Muto <- RunUMAP(kidney_Muto, dims = 1:30, reduction = "pca", return.model = TRUE)
kidney_Muto <- MapQuery(anchorset = transfer_anchors, reference = kidney_ref, query = kidney_Muto, 
                        refdata = list(celltype = "celltype"), reference.reduction = "pca", reduction.model = "umap")
```

I get this error:
`Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first`

I can see the model in my query data (kidney_Muto@reductions$umap@misc$model), but MapQuery doesn't recognize it for some reason.
I use Seurat_4.3.0

Thank you for your help.
