### ISSUE TITLE
FindAllMarkers returning only markers for 1st cluster

### ISSUE THREAD

**Issue by DanSchnell** [satijalab/seurat#718]
Hi,    
I have a situation with 14 clusters.  The data below show there are plenty of cells in each cluster, and I've done many other analyses with parts of this dataset and the clusters have well-know markers.  
0              1        2          3         4        5        6         7         8        9      10        11       12 
14823 11443  9547  8833  8331  7635  4154  3417  2531  2404  2046  1909  1871 
   13    14      Sum 
 1541  1327 81812 
I've tried adjusting the min.pct, logfc.threshold , min.dff.pct, max.cells.per.ident=1000, and keep getting something like the following for number of markers per cluster:
   0    1    2    3    4    5    6    7    8    9   10   11   12   13   14 
1005    0    0    0    0    0    0    0    0    0    0    0    0    0    0 
Using wilcoxon test with return.thresh=0.05.
Thoughts on other things to try?
Thanks,
Dan Schnell
CCHMC

**Comment by DanSchnell** [comment]
using seurat 2.3.1
calling SubsetData to reduce each ident to 200 cells did not fix the issue

**Comment by andrewwbutler** [comment]
Hi,

Can you provide the command that you ran along with the `sessionInfo()`? Also, could you try `FindMarkers` on two specific clusters you know should return well-known markers and see what that returns?

**Comment by DanSchnell** [comment]
Thanks for getting back to me Andrew.
I’m trimming the datasets a bit by removing doublets, so they will be a little smaller.  I expect I’ll be the point of having the samples merged and running FindAllMarkers within a day or two.  I’ll do the two things that you suggested and reply again with the info.
Dan

**Comment by DanSchnell** [comment]
Hi Andrew,
In FindAllMarkers, are markers found by comparing each cluster to the balance of the cells as a single group, or,
are markers found for each pairwise combination of clusters and then an intersection (or other) approach used?
Thanks,
Dan

**Comment by leonfodoulian** [comment]
Hi @DanSchnell,

> In FindAllMarkers, are markers found by comparing each cluster to the balance of the cells as a single group, or,
> are markers found for each pairwise combination of clusters and then an intersection (or other) approach used?

In `Seurat::FindAllMarkers()`, cells from each cluster are compared to all other cells combined. If you wish to perform pairwise comparisons, I suggest you use `Seurat::FindMarkers()` in a for loop, where at each iteration a pairwise comparison is performed. Don't forget to specify `ident.2` as the target cluster to which cells from `ident.1` will be compared to. 

Hope this help!

Best,
Leon

**Comment by DanSchnell** [comment]
Thanks very much Leon!
Just to make sure I understand the specifics…
If I want to find markers for cluster 0, I could set ident.1=0 and ident.2=NULL.
Furthermore, if I specify only.pos=TRUE, it would ID markers in cluster 0 that are more highly expressed compared to the balance of the cells.
Sound right?
Thanks,
Dan

**Comment by leonfodoulian** [comment]
> If I want to find markers for cluster 0, I could set ident.1=0 and ident.2=NULL.

Correct. But you should use the `Seurat::FindMarkers()` function.

> Furthermore, if I specify only.pos=TRUE, it would ID markers in cluster 0 that are more highly expressed compared to the balance of the cells.

Setting `only.pos = TRUE` would return a list of genes that are expressed in the cells from the cluster specified as `ident.1` at an average difference higher than `logfc.threshold` compared to cells from the cluster specified as `ident.2` (code at [line 180 in differential_expression.R](https://github.com/satijalab/seurat/blob/7618ac8798e2aefc509529f07af9d2836b96a1be/R/differential_expression.R#L180)). In fact, only those genes will be tested for by the function.

Hope this was clear!

Best,
Leon

**Comment by DanSchnell** [comment]
Great—will do.  Thanks much!

**Comment by DanSchnell** [comment]
Just a note to let you know that the issue did not arise when I used a slightly smaller dataset.  I suspect that there was something that I overlooked in the creation of the problematic dataset and I managed to not induce the same problem as I was creating the new dataset.
Thanks,
Dan
