### ISSUE TITLE
Using RNA, SCT or Integrated assay for DEA

### ISSUE THREAD

**Issue by Rahul1711arora** [satijalab/seurat#7181]
Hi, 

We have been using Seurat v4.3.0 for our data analysis and we are while looking through the tutorials at `https://broadinstitute.github.io/2020_scWorkshop/batch-correction-lab.html ` for batch correction, we realised that it states: 
`The integrated data must not be used in DE tests as it violates assumptions of independence in DE tests!`
So, we are now really confused as to why to integrate the datasets if we need to run the DEA on RNA/SCT assay? 
Also, could you please suggest which one of the 3 assays is best to run the differential expression analysis? 

Looking forward to hear soon. Thanks in advance for your help. 

Best,
Rahul

**Comment by saketkc** [comment]
The goal of integration is to figure out the analogous celltypes across two conditions (or technologies or batches). Once you have the data integrated, you should switch to the RNA or SCT assay to calculate markers.
