### ISSUE TITLE
Error loading seurat object

### ISSUE THREAD

**Issue by climonte** [satijalab/seurat#7182]
Hello, 

I've been using seurat for the last 1-2 years. I recently upgraded to the most recent version (v5). Since doing this I have been having trouble loading seurat objects. I had been able to open the file using the older seurat version. I quit/restarted R, uninstalled seurat and reinstalled an older version, and I am still having this issue. My code and the error message I received are below. There is nothing wrong with the file I am trying to open - as I said, this worked before. 

I am using the following versions:
seurat 4.3.0
seuratdisk 0.0.0.9014
seuratobject 4.1.3

I would really appreciate your help! This has been very frustrating and I've spent hours troubleshooting to no avail. 

`seurat <- LoadH5Seurat('~/filename.h5Seurat')`

```
Validating h5Seurat file
Initializing RNA with data
Adding counts for RNA
Adding scale.data for RNA
Adding feature-level metadata for RNA
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of “counts”, “data”, “scale.data”
```

**Comment by Gesmira** [comment]
Hi, 
Based on your error message, it seems that you still may have the v5 version of SeuratObject loaded. If you clear your R environment, restart R, and run: 

```
install.packages(c("SeuratObject", "Seurat"))
library(SeuratObject)
library(Seurat)
```

That should restore the older version of Seurat correctly. Let me know if that works for you.

**Comment by climonte** [comment]
This worked!! Thank you so much! 

Do you know if there is a bug in the newer versions of these packages that is in the process of being resolved?

**Comment by Gesmira** [comment]
Some updates for seurat5 have been added to [feat/h5ad of seurat-disk](https://github.com/mojaveazure/seurat-disk/tree/feat/h5ad), but it is being less actively maintained. We recommend the use of packages like [sceasy](https://github.com/cellgeni/sceasy) for converting to seurat objects.
