### ISSUE TITLE
PrepareBridgeReference not found? 

### ISSUE THREAD

**Issue by clee700** [satijalab/seurat#7184]
Hello! I am trying  to reproduce this vignette: https://satijalab.org/seurat/articles/seurat5_integration_bridge.html#map-scatac-seq-dataset-using-bridge-integration
I downloaded the data and am able to run everything up until this point, PrepareBridgeReference(), at which point R says it cannot find the function. It also cannot find FindBridgeTransferAnchors(). When I click on PrepareBridgeReference in the vignette to get a look at the documentation (https://satijalab.org/seurat/articles/reference/PrepareBridgeReference.html), I get a 404 Page not found error. 

Any advice? Thank you!

 library(Seurat)
obj.rna.ext <- PrepareBridgeReference(
+   reference = obj.rna, bridge = obj.multi,
+   reference.reduction = "spca", reference.dims = dims.rna,
+   normalization.method = "SCT")
Error in PrepareBridgeReference(reference = obj.rna, bridge = obj.multi,  : 
  could not find function "PrepareBridgeReference"
 packageVersion("Seurat")
[1] '4.9.9.9041'
<img width="545" alt="image" src="https://user-images.githubusercontent.com/112990107/232606291-87dd06db-8820-43f9-abc6-90de8d23a985.png">

**Comment by Gesmira** [comment]
Hi, can you try clearing your R environment, restarting R, and loading the new version of Seurat again?

**Comment by mhkowalski** [comment]
Closing because of no response, please make sure that you have Seurat 5 installed in order to use this function.
