### ISSUE TITLE
read slideseq use ReadSlideSeq

### ISSUE THREAD

**Issue by wang0430** [satijalab/seurat#7188]
Hello,
I currently want to analyze the data of slideseq technology, but the operation documentation of ReadSlideSeq function is very concise, I don't know what data to prepare, position?counts?image?
Can you give an example with public data,
best wishes

**Comment by longmanz** [comment]
Hi, 
To load a SlideSeq dataset you will need to have the bead coordinate file in .csv format. 
```
ReadSlideSeq
function (coord.file, assay = "Spatial") 
{
    if (!file.exists(paths = coord.file)) {
        stop("Cannot find coord file ", coord.file, call. = FALSE)
    }
    slide.seq <- new(Class = "SlideSeq", assay = assay, coordinates = read.csv(file = coord.file, 
        header = TRUE, as.is = TRUE, row.names = 1))
    return(slide.seq)
}
```

After that, you can load your RNA count data as normal (e.g., use CreateSeuratObject() ), and then attach your bead coordinate information to this SeuratObject. 

For your reference, you many read this external tutorial for how to create a SeuratObj for SlideSeq datasets: https://patrickcnmartin.github.io/Vesalius/articles/Vesalius_Analysis/Vesalius_analysis.html
