### ISSUE TITLE
 SeuratV5  AddModuleScore on all layers 

### ISSUE THREAD

**Issue by bkutlu** [satijalab/seurat#7191]
Hello, 
Is AddModuleScore adopted to run on all layers? When I do the following,

obj <- LoadData("pbmcsca")
obj <- subset(obj, nFeature_RNA > 1000)
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$Method)

cd_features<-list(c('CD79B','CD79A','CD19','CD180','CD200','CD3D','CD2','CD3E','CD7','CD8A','CD14','CD1C','CD68','CD9','CD247'))
obj <- AddModuleScore(obj, features = cd_features, name = 'CD_Features')

 I get this error:
Error in ctrl.scores[i, ] <- Matrix::colMeans(x = assay.data[features.use,  : 
  number of items to replace is not a multiple of replacement length
In addition: Warning message:
In LayerData.Assay5(object = object, layer = layer, ...) :
  multiple layers are identified by counts.Smart-seq2 counts.CEL-Seq2 counts.10x_Chromium_v2_A counts.10x_Chromium_v2_B counts.10x_Chromium_v3 counts.Drop-seq counts.Seq-Well counts.inDrops counts.10x_Chromium_v2
 only the first layer is used

Thanks

**Comment by yuhanH** [comment]
Thank you for reporting this bug. We will fix it soon.

**Comment by SadieVanHorn** [comment]
I have also encountered this bug, is there any progress on it? Thanks!

**Comment by nandobonf** [comment]
I'm facing same issue

**Comment by yuhanH** [comment]
Hi
We are working on this bug in progress. The easiest solution for now is to calculate module score after running JoinLayers.

**Comment by yuhanH** [comment]
Thank you for reporting this bug. We have improved the error message. Current, you need to join layers to run `AddModuleScore`.

**Comment by Lucyyang1991** [comment]
I have the same bug when I run `CellCycleScoring` using BPCells result.
```
> object
An object of class Seurat 
32124 features across 74483 samples within 1 assay 
Active assay: RNA (32124 features, 2000 variable features)
 21 layers present: counts.LPR_SP_CD45_12w, counts.LPR_SP_CD45_21w, counts.LPR_SP_CD45_6w, counts.LPR_SP_DNT_12w, counts.LPR_SP_DNT_21w, counts.LPR_SP_DNT_6w, counts.LPR_T_DNT_6w, counts.MRL_SP_CD45_6w, counts.MRL_SP_DNT_6w, counts.MRL_T_DNT_6w, data.LPR_SP_CD45_12w, data.LPR_SP_CD45_21w, data.LPR_SP_CD45_6w, data.LPR_SP_DNT_12w, data.LPR_SP_DNT_21w, data.LPR_SP_DNT_6w, data.LPR_T_DNT_6w, data.MRL_SP_CD45_6w, data.MRL_SP_DNT_6w, data.MRL_T_DNT_6w, scale.data
 5 dimensional reductions calculated: pca, umap.unintegrated, harmony, umap.harmony, umap.harmony.orig
> obj.cc = CellCycleScoring(object, s.features = mouse_cell_cycle_genes$s.genes, g2m.features = mouse_cell_cycle_genes$g2m.genes, set.ident = T)
Warning: The following features are not present in the object: Pcna-ps2, not searching for symbol synonyms
Error in ctrl.scores[i, ] <- Matrix::colMeans(x = assay.data[features.use,  : 
  number of items to replace is not a multiple of replacement length
```

**Comment by beyondpie** [comment]
I use  `Seurat.object::RowMergeSparseMatrices` to manually merge the mats.
https://rdrr.io/github/mojaveazure/seurat-object/man/RowMergeSparseMatrices.html

**Comment by seasonzhao** [comment]
try to do this before CellCycleScoring:
pbmc_small[["joined"]] <- JoinLayers(pbmc_small[["RNA"]])
DefaultAssay(pbmc_small) <- "joined"
pbmc_small <- CellCycleScoring(pbmc_small,s.features = s.genes,g2m.features = g2m.genes, set.ident = TRUE)

**Comment by seasonzhao** [comment]
try to do this before CellCycleScoring:
```
pbmc_small[["joined"]] <- JoinLayers(pbmc_small[["RNA"]])
DefaultAssay(pbmc_small) <- "joined"
pbmc_small <- CellCycleScoring(pbmc_small,s.features = s.genes,g2m.features = g2m.genes, set.ident = TRUE)
```

**Comment by purisuto** [comment]
Sorry bit of a naive follow up here as I'm still learning the correct workflow and applying it to some published v3 datasets.

So the start of the workflow would be:
QC filtering → Remove genes (optional like rRNA and mtRNA) → Split the seurat object (by desired batch parameter) → `NormalizeData()` → `JoinLayers()` → `CellCycleScoring()` → `ScaleData()` (regressing out desired variables like CC.difference)

But is the subsequent workflow:
1) `Split()` → `FindVariableFeatures()` (edit variable features if desired) → `RunPCA `→ `IntegrateLayers()` → `JoinLayers()` → integrated PCA, clustering, downstream analysis

or

2)  `FindVariableFeatures()` (edit variable features if desired) → `RunPCA ` → `Split()` → `IntegrateLayers()` → `JoinLayers()` → integrated PCA, clustering, downstream analysis

i.e. Does splitting the seurat object before or after running the unintegrated PCA have any effect?

**Comment by guanghaoli** [comment]
> try to do this before CellCycleScoring:
> 
> ```
> pbmc_small[["joined"]] <- JoinLayers(pbmc_small[["RNA"]])
> DefaultAssay(pbmc_small) <- "joined"
> pbmc_small <- CellCycleScoring(pbmc_small,s.features = s.genes,g2m.features = g2m.genes, set.ident = TRUE)
> ```

This is OK in my analysis!
