### ISSUE TITLE
Low percentage of 'Fraction Antibody Reads Usable' in Feature Barcode Cell Ranger output

### ISSUE THREAD

**Issue by rcrueda** [satijalab/seurat#7194]
Hi, I have a question regarding the Cell Ranger output of scRNAseq with Feature Barcode. I've performed the standard Cell Ranger count using cellranger-6.0.0 and the following arguments:
--id=A_GEX \
--libraries=library_A.csv \
--transcriptome=/....../refdata-gex-GRCh38-2020-A \
--feature-ref=/...../10x_feature_ref.csv

When looking at the output QC I've noticed that the antibody sequencing parameters show good sequencing quality. However, the "Fraction Antibody Reads Usable" is very low. 
![image](https://user-images.githubusercontent.com/74883075/233374506-05ba3132-2989-4cd3-8655-20d7bc8a857a.png)

When looking at the count matrix every feature barcode is counted, so the barcodes in the 10x_feature_ref.csv seem to be correct. 

Is there any reason why this is happening? or is there any way to solve it?

Thank you in advance

**Comment by samuel-marsh** [comment]
Hi,

This question would be best asked in community forum (I.e. biostars) or to 10X support as it concerns cell ranger results and is not an issue with the Seurat R package.

Best,
Sam
