### ISSUE TITLE
Error in saveh5seurat after upgrading to Seurat v5

### ISSUE THREAD

**Issue by KristinAass** [satijalab/seurat#7196]
Hi,
I recently upgraded to Seurat v5 and now I cannot save h5seurat files anymore. I can still load (loadh5seurat) the files I saved with the previous version of Seurat, but I am not able to save files. I always get the same error, see code below.
Thanks,

Kristin

```
MM.all <- Read10X_h5(filename="~/Documents/Nye_dokumenter_november_2021/Aass.Microenv.scRNAseq2023/cellrangerfilesQC_GCF-2022-88/data/1458D_filtered_feature_bc_matrix.h5")
> MM.all <- CreateSeuratObject(counts = MM.all, project="New", min.cells=3, min.features=200, assay = "RNA")
> SeuratDisk::SaveH5Seurat(MM.all,overwrite = T,verbose = T)
Warning: Overwriting previous file New.h5Seurat
Creating h5Seurat file for version 3.1.5.9900
Adding counts for RNA
Adding data for RNA
No variable features found for RNA
Error in if (ncol(x = x[[]])) { : argument is of length zero
```

**Comment by yuhanH** [comment]
hi @KristinAass 
you can use `saveRDS` to save Seurat 5 object. Currently, SaveH5Seurat is not supported for seurat v5.

**Comment by Plasmiddddd** [comment]
Hi @yuhanH, I wonder is `SaveH5Seura` available for v5 now? I'm using `saveRDS` currently. Just wondering which way is better to save data for v5. Thanks
