### ISSUE TITLE
Feature plot

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7202]
Hi
I am making feature plot and each feature plot has its own scale like from 0 to 3 or some has from 0 to 1.5.
My question is is it not discriminating to have different scale in same dataset?
We should put max cut off to have a fair analysis?
or using as default generated feature plot is fair?
i have attached 2feature plots from same analysis they have different scale.
[AD.pdf](https://github.com/satijalab/seurat/files/11299103/AD.pdf)

[B1.pdf](https://github.com/satijalab/seurat/files/11299104/B1.pdf)

i used this code:
FeaturePlot(obj,"Adgre1")

**Comment by nathan-nakatsuka** [comment]
Try the keep.scale argument (https://satijalab.org/seurat/reference/featureplot).
