### ISSUE TITLE
unable to read in mtx.gz file converted from h5ad file

### ISSUE THREAD

**Issue by indapa** [satijalab/seurat#7203]
Hi,

I am new to scRNAseq and Seurat. I pulled down this h5ad file from [here](https://figshare.com/s/2892d1cf91752e08a963?file=17727365)

The authors used scanpy but I want to analyze it with Seurat. Following this [example](https://github.com/mousepixels/sanbomics_scripts/blob/main/h5ad_to_seurat.ipynb#enroll-beta) I wrote out the .mtx file from the AnnData object like so

`io.mmwrite('~/HCL/matrix_files/matrix, adata.X.T)`

But when I try this command in Seurat:

`hcl_raw_data <- Seurat::Read10X(data.dir = "~/HCL_conversion/HCL_matrix_files/")`

I get the error:

`Error in scan(file, nmax = 1, what = what, quiet = TRUE, ...) :
scan() expected 'an integer', got '0.00000000e+00'`

I tried a smaller example with the example PBMC data from converting from h5ad by writing out the barcodes, features, and mtx file and running the Read10X, and it worked fine. But I am unclear why this isn't working? Am I encoding the data incorrectly in the call to io.mmwrite that is causing Read10X to throw an error?

Any help is appreciated. ``

**Comment by yuhanH** [comment]
hi @indapa 
I would suggest you use [sceasy](https://github.com/cellgeni/sceasy) package to convert h5ad to a seurat object.
