### ISSUE TITLE
Google Cloud Storage error while download MERFISH dataset

### ISSUE THREAD

**Issue by wang0430** [satijalab/seurat#7204]
Hello, I recently updated seurat5 and want to use him to analyze MERFISH data. I see that the public dataset you are using is (https://console.cloud.google.com/storage/browser/public-datasets-vizgen-merfish/datasets /mouse_brain_map/BrainReceptorShowcase?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false). But since my IP is from China, I can't use gsutil to download data from Google Cloud Storage at all. Could you please pass it on to me?
Or is there a friend who can help me download the relevant data? My email is wangguoliang@big.ac.cn, please feel free to contact me, thank you very much!

**Comment by AustinHartman** [comment]
Hi @wang0430, I'd recommend reaching out to Vizgen directly to see if they have an alternative file transfer solution.
