### ISSUE TITLE
Please, please HELP: How to import UMAP.coords.tsv.gz?

### ISSUE THREAD

**Issue by shawnql08** [satijalab/seurat#7207]
I am new and not a professional bioinformatics. I have downloaded  **Matrix: exprMatrix.tsv.gz**, **Cell meta annotations: meta.tsv** AND **UMAP.coords.tsv.gz** from pulished data. After I load the *Matrix: exprMatrix.tsv.gz**, **Cell meta annotations: meta.tsv** , how can I import the **UMAP.coords.tsv.gz**? so that I can get the same cluster data as the author's. Is there a tutorial or can someone let me know how to do it?

Sinerely appreciate your help.

**Comment by longmanz** [comment]
Hi, 
Yes you can load your own UMAP information to a Seurat object. Make sure that your UMAP.coords.tsv.gz file contain the cell-barcodes (for example, in column 1). For example:
```
# seurat_obj is your Seurat obj. 

UMAP_coordinates <- read.table("UMAP.coords.tsv", stringsAsFactors = F, header = T, row.names = 1)
UMAP_coordinates_mat <- as(UMAP_coordinates, "matrix")

# Create DimReducObject and add to object
seurat_obj[['UMAP']] <- CreateDimReducObject(embeddings = UMAP_coordinates_mat, key = "UMAP_", global = T, assay = "RNA")
```

You can see more information from this thread: https://github.com/satijalab/seurat/issues/5113.
