### ISSUE TITLE
subsetting cells in seurat v5

### ISSUE THREAD

**Issue by ollieeknight** [satijalab/seurat#7208]
After running this command (subsetting one object based on common cells from another object) I get this error, which normally is fine in seurat v4

```r
alldata.rna$multiome[['RNA']] <- subset(alldata.rna$multiome[['RNA']], cells = colnames(alldata.atac$multiome[['ATAC']]))
Warning: Different cells in new layer data than already exists for counts
Error in validObject(object = object) : 
  invalid class "Assay5" object: 1: All layers must have a record in the cells map (offending layer: data)
invalid class "Assay5" object: 2: All layers must have a record in the features map (offending layer: data)
```
or
```r
alldata.rna$multiome <- subset(alldata.rna$multiome, cells = colnames(alldata.atac$multiome))
Error in match.arg(arg = i, choices = colnames(x = x)) : 
  'arg' should be "counts"
```

**Comment by longmanz** [comment]
Hi,
Is your alldata.rna a list of Seurat V5 objects? If you assign it with a different assay names (e.g., `alldata.rna$multiome[['RNAsub']] <- subset(alldata.rna$multiome[['RNA']], cells = colnames(alldata.atac$multiome[['ATAC']]))`, do you still observe the same issue?

**Comment by ollieeknight** [comment]
thank you for replying - I'll get back to you!

**Comment by Fernandobec** [comment]
I'm also getting a similar problem, when trying to subset by idents = or by cells = I get the following error:
Error in `LayerData<-`(object = `*tmp*`, layer = i, ..., value = value) : 
  'value' must be a 'matrix' or 'dgCMatrix'
This didn't happen before I updated to the v5, how can this issue be solved?
Thanks!

**Comment by cmiciano** [comment]
Commenting as I see the same as @Fernandobec 

```
subset(sobj, subset = sample_id == "BPS_100uM_1")

Error in `LayerData<-`:
! 'value' must be a 'matrix' or 'dgCMatrix'
Traceback:

1. subset(sobj, subset = sample_id == "BPS_100uM_1")
2. subset.Seurat(sobj, subset = sample_id == "BPS_100uM_1")
3. suppressWarnings(expr = slot(object = x, name = "assays")[[assay]] <- tryCatch(expr = suppressWarnings(expr = base::subset(x = x[[assay]], 
 .     cells = cells, features = assay.features), classes = "validationWarning"), 
 .     error = function(e) {
 .         if (e$message == "Cannot find features provided") {
 .             return(NULL)
 .         }
 .         else {
 .             stop(e)
 .         }
 .     }))
4. withCallingHandlers(expr, warning = function(w) if (inherits(w, 
 .     classes)) tryInvokeRestart("muffleWarning"))
5. tryCatch(expr = suppressWarnings(expr = base::subset(x = x[[assay]], 
 .     cells = cells, features = assay.features), classes = "validationWarning"), 
 .     error = function(e) {
 .         if (e$message == "Cannot find features provided") {
 .             return(NULL)
 .         }
 .         else {
 .             stop(e)
 .         }
 .     })
6. tryCatchList(expr, classes, parentenv, handlers)
7. tryCatchOne(expr, names, parentenv, handlers[[1L]])
8. value[[3L]](cond)
```

**Comment by NicolaasVanRenne** [comment]
I get the same error when following the atac seq vignette.

Subset does not work anymore... 

`subset(pbmc.atac, subset = seurat_annotations != "filtered")`

> Error in `LayerData<-`(object = `*tmp*`, layer = i, ..., value = value) : 
>   'value' must be a 'matrix' or 'dgCMatrix'

**Comment by ybaeus** [comment]
any updates on this?

**Comment by aburgosru** [comment]
same, I can not subset anymore

**Comment by shaniAmare** [comment]
Seurat V5 completely screwed up the subsetting for me too. 

Also I was trying the `LoadNanostring()` function in V5 which is also very much not outputting the same object structure as for V4 which means all my previous code that was working 2 months ago are now with errors! Not the best way to end my year!

**Comment by odolsicardo** [comment]
I had the same issue and solved it re-installing SeuratObject package from CRAN -> install.packages("SeuratObject")

**Comment by Close-your-eyes** [comment]
Try something like this before subset

`Seurat::DefaultAssay(so) <- "RNA"
so@assays[["RNA"]]@layers[["scale.data"]] <- NULL`
