### ISSUE TITLE
In an integrated scRNA-seq analysis, looking for a metric in Seurat 4.3 that indicates how well integrated the cells from each sample are

### ISSUE THREAD

**Issue by jjacob12** [satijalab/seurat#7209]
I have performed an integrated analysis of several samples, three of which are cancer cell lines grown in different growth conditions (as a conventional monolayer; tumour spheroid; in co-culture with a brain organoid) and three others are patient scRNA-seq brain cancer samples of the same type. My analysis indicates that the cell lines grown in co-culture with a brain organoid have a transcriptional profile more akin to patient tumours. When I integrated all these samples as per the conventional workflow (prior 'merge' showed each sample separating by batch so an integrated analysis was justified) I observed nice integration of all samples except the conventional monolayer cell line stayed separate. This was a nice result as monolayer cell lines typically have little in common phenotypically with patient tumours. 
-here is a tSNE plot pre-integration
<img width="1207" alt="Screenshot 2023-04-23 at 20 28 03" src="https://user-images.githubusercontent.com/63459892/233860775-e4b2144a-c6d2-4548-8c08-940d78efa2d0.png">
 
- and here is the tSNE plot after integration
<img width="1208" alt="Screenshot 2023-04-23 at 20 31 05" src="https://user-images.githubusercontent.com/63459892/233860890-cef672e2-9aa8-4b69-83e8-acdcff6e6da7.png">

The green dots represent the tumour spheroid (dySpher) and the red dots represent the cancer cells grown in coculture (dyCbo) that I computationally extracted from the co-culture condition. My impression eye-balling the lower tSNE plot in the central area where cells look well integrated, is that the green cells are possibly more clumped together than the red cells. If that impression is correct, then that could mean the green cells bear a lower resemblance to the patient tumours (muv41, sj454, sj577) than the red (dyCbo) cells. Is there a metric I could use in a Seurat slot that captures how well integrated the cells from each sample are? I looked at the ```integrated_snn..``` score in the metadata but that is a factor variable, not a numeric variable and I wondered if the higher that score, the better integrated the cells of that sample are? Is it appropriate to use this metric for my purposes? Would plotting these scores and comparing their medians be appropriate? Or is there another way to do this?
Many thanks.

**Comment by f6v** [comment]
I don't have an answer for you, but I came across [an article](https://www.life-science-alliance.org/content/4/6/e202001004) that you might find useful.

**Comment by jjacob12** [comment]
Many thanks, I will take a look.

**Comment by jjacob12** [comment]
The Seurat function ```MixingMetric``` turned out to be useful for this, after a bit of searching. Thanks.

**Comment by saketkc** [comment]
There are metrics in the [SeuratV3 paper](https://www.cell.com/cell/pdf/S0092-8674(19)30559-8.pdf) that you will find  implemented here: https://github.com/satijalab/Integration2019/blob/master/analysis_code/integration/integration_metrics.R

**Comment by jjacob12** [comment]
Many thanks for this.
