### ISSUE TITLE
LoadVizgen error

### ISSUE THREAD

**Issue by wang0430** [satijalab/seurat#7210]
hi,
I analyzed s2r1 dataset was produced using the Vizgen MERSCOPE system, but got error
 [> vizgen.obj <- LoadVizgen(data.dir = "./out/", fov = "s2r1")
|--------------------------------------------------|
|==================================================|
Warning in ReadVizgen(data.dir = data.dir, filter = "^Blank-", type = c("centroids",  :
  83546 cells missing polygon information
Error in UseMethod(generic = "CreateSegmentation", object = coords) : 
  no applicable method for 'CreateSegmentation' applied to an object of class "NULL"
In addition: There were 50 or more warnings (use warnings() to see the first 50)]

![1682310860563](https://user-images.githubusercontent.com/112233361/233900767-318a201d-279c-465b-ada4-a9c2b7e092ef.png)

**Comment by wang0430** [comment]
I solved it, Thanks

**Comment by Chaosli98** [comment]
> I solved it, Thanks
Could you please share the solution? I had the same problem

**Comment by ivywxx** [comment]
I also had the same problem. Could you please share the solution?
