### ISSUE TITLE
Seurat v5 ReadParseBio Error unused arguments (cell.sep = ",", feature.sep = ",", mtx.transpose = TRUE)

### ISSUE THREAD

**Issue by mbatiuk** [satijalab/seurat#7211]
Trying to load ParseBio data:

ReadParseBio("./parse_output/sublibrary_S1/S1/DGE_filtered/")

and getting this error:

Error in ReadMtx(mtx = mtx, cells = cells, features = features, cell.column = 1,  : 
  unused arguments (cell.sep = ",", feature.sep = ",", mtx.transpose = TRUE)

When trying to use ReadMtx that underlays ReadParseBio function:

ReadMtx(mtx = "./parse_output/sublibrary_S1/S1/DGE_filtered/DGE.mtx", 
                cells = "./parse_output/sublibrary_S1/all-well/DGE_filtered/cell_metadata.csv", 
                features = "./parse_output/sublibrary_S1/all-well/DGE_filtered/all_genes.csv",
                cell.column = 1, feature.column = 2, skip.cell = 1, skip.feature = 1)

Error is like this:

Error in ReadMtx(mtx = "./parse_output/sublibrary_S1/S1/DGE_filtered/DGE.mtx", :
feature.column was set to 2 but ./parse_output/sublibrary_S1/all-well/DGE_filtered/all_genes.csv only has 1 column(s). Try setting the feature.column argument to a value <= to 1.

To my understanding ReadMtx does notread .csv files properly, but does not understand cell.sep = ",", feature.sep = "," parameters neither

**Comment by saketkc** [comment]
I am not sure which version of the Parsebio output you are having trouble with, but in this case you should be able to use `ReadMtx` to resolve this (following hints from the error):

```r
ReadMtx(mtx = "./parse_output/sublibrary_S1/S1/DGE_filtered/DGE.mtx",
cells = "./parse_output/sublibrary_S1/all-well/DGE_filtered/cell_metadata.csv",
features = "./parse_output/sublibrary_S1/all-well/DGE_filtered/all_genes.csv",
cell.column = 1, feature.column = 1, skip.cell = 1, skip.feature = 1)
```

**Comment by yxsee** [comment]
Just to update, I faced this issue when using Seurat_4.9.9.9045, but updating to Seurat_4.9.9.9058 resolved it.
