### ISSUE TITLE
How to use leidenbase instead of Python based 'leiden algorithm' implementation?

### ISSUE THREAD

**Issue by mauritsunkel** [satijalab/seurat#7212]
Hi, 

Based on #6792  I wanted to try the Leidenbase (https://github.com/cole-trapnell-lab/leidenbase) implementation to circumvent Reticulate for calling Python to run the leiden algorithm (`FindClusters(algorithm = 4) or FindClusters(algorithm = "leiden")`) as I had many install issues. 

Running FindNeighbors() I get SO@graphs$SCT_snn (shared nearest neighbor graph, and $SCT_nn). I tried then running: 
`igraph <- igraph::graph_from_adjacency_matrix(SO@graphs$SCT_snn)`
Followed by: 
`clusters <- leidenbase::leiden_find_partition(igraph, resolution_parameter = .1)`
`clusters$membership`
Even when playing with the resolution_parameter most cells seem to stay in their own 'cluster' (singleton partition, partition not found?)

Any suggestions for making this work? (Even open for how to make the Python implementation work after all)

**Comment by yuhanH** [comment]
hi @mauritsunkel 
This issue seems to be more relevant to `leidenbase::leiden_find_partition` but not really to Seurat. You would better post this issue in leidenbase github.
