### ISSUE TITLE
Seurat V5 on MERFISH data without hdf5r files

### ISSUE THREAD

**Issue by YidaZhang0628** [satijalab/seurat#7215]
### Discussed in https://github.com/satijalab/seurat/discussions/7170

<div type='discussions-op-text'>

<sup>Originally posted by **YidaZhang0628** April 14, 2023</sup>
I am planning to use Seurat V5 on a MERFISH dataset. The tutorial uses `LoadVizgen` function to read the files. However, I don't have hdf5r files from segmentation. Therefore, I won't be able to use `LoadVizgen`. I can read the data using `ReadVizgen` but it results in a plain list instead of a Seurat object. Any idea on how to read MERFISH data without segmentation information into a Seurat object?</div>

**Comment by alikhuseynov** [comment]
For Cellpose output, I submitted a PR handle Cellpose output #7190 
You may it `devtools::install_github(repo = "alikhuseynov/seurat", ref = "feat/vizgen")`
To load Vizgen this workflow could help [make Seurat objects](https://github.com/alikhuseynov/add-on_R/blob/develop/R/example_read_load_vizgen_v2.R)
