### ISSUE TITLE
Converting from h5seurat to h5ad

### ISSUE THREAD

**Issue by JohnSpJun** [satijalab/seurat#7216]
Hi,

I am attempting to convert an h5seurat object to h5ad object. Specifically, I want to use the "counts" assay instead of the scale.data assay in my h5ad object. However, the current Convert method seems to automatically use the scale.data section if it exists in the h5seurat object. Is there a way to specify which assay I want to copy over to the h5ad object?

**Comment by yuhanH** [comment]
Hi, @JohnSpJun 
I would suggest you use [sceasy](https://github.com/cellgeni/sceasy) package to convert seurat to h5ad file.
