### ISSUE TITLE
Data integration not replicable if order of objects in list produced by SplitObjects changes

### ISSUE THREAD

**Issue by jasminelmah** [satijalab/seurat#7217]
Description: Following the basic Seurat [integration tutorial](https://satijalab.org/seurat/articles/integration_introduction.html), I've found that the order of the objects (samples) in the list produced by Seurat::SplitObjects affects the absolute numbers of the integrated matrix that is produced. The numbers are off by a fair amount e.g. -0.06415531 vs. 0.02116652. This is a significant issue for me because although the data is successfully integrated, I need my analyses to be repeatable and I cannot ensure that the order of objects will always be the same for each run. 

This is reproducible with a clean R session for each run.

My own workflow uses the SCTransform version of the integration workflow, but the issue is reproducible using the basic LogNormalize integration tutorial and the` ifnb` data. Here's a reproducible example.

1. Run the basic Seurat integration tutorial:
> ```{r}
> library(Seurat)
> library(SeuratData)
> library(patchwork)
> InstallData("ifnb")
> LoadData("ifnb")
> 
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
> ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
>     x <- NormalizeData(x)
>     x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
> })
> features <- SelectIntegrationFeatures(object.list = ifnb.list)
> immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)
> immune.combined <- IntegrateData(anchorset = immune.anchors)
> DefaultAssay(immune.combined) <- "integrated"
> immune.combined <- ScaleData(immune.combined, verbose = FALSE)
> immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
> immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
> immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
> immune.combined <- FindClusters(immune.combined, resolution = 0.5)
> ```

2. Rerun the tutorial but change the order of the objects in the list:
>```{r}
> library(Seurat)
> library(SeuratData)
> library(patchwork)
> InstallData("ifnb")
> LoadData("ifnb")
>
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
> 
> ### -- CHANGE ORDER OF OBJECT LIST -- ###
> ifnb.list <- c(STIM=ifnb.list$STIM, CTRL=ifnb.list$CTRL)
>
> ifnb.list <- lapply(X = ifnb.list, FUN = function(x) {
>     x <- NormalizeData(x)
>     x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
> })
> features <- SelectIntegrationFeatures(object.list = ifnb.list)
> immune.anchors <- FindIntegrationAnchors(object.list = ifnb.list, anchor.features = features)
> immune.combined <- IntegrateData(anchorset = immune.anchors)
> DefaultAssay(immune.combined) <- "integrated"
> immune.combined <- ScaleData(immune.combined, verbose = FALSE)
> immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
> immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
> immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
> immune.combined <- FindClusters(immune.combined, resolution = 0.5)
> ```

Then compare values. The values are notably different for both the matrices in the scale.data and data slots of the "integrated" assay. As noted above, I am using the SCTransform workflow so I need to use the matrix in the "integrated" scale.data slot in particular.

I can see that the number of anchors found differed (16393  vs 16390). My best guess is that because integration occurs by pairwise merging, the order samples are merged matters. And I know you can input your own sample tree (although this is not a suitable solution for my own workflow). However, in the above example and in my own workflow, I used default values - `sample.tree = NULL` and `preserve.order=FALSE`. In that case, isn't the sample tree automatically calculated by using hclust on a distance matrix? And shouldn't that produce the same sample tree even if the order of samples in the list vary (the data values themselves are the same so it should produce the same distance matrix)? Interestingly, when running the above code Seurat DOES merge the samples in the same direction even when the list order is switched (ie it merges sample 1 -> sample 2 in the first chunk, and 2 -> 1 when the list is reordered in the second chunk).

**My questions for you:**  
1) What exactly is going on? I am going through your source code and it would be helpful for me if you could go into detail.
2) What can I do to ensure the values of the integrated data are identical each run, despite the fact that the order of the samples in the SplitObjects list may vary?

Thank you for your help!! Seurat has been absolutely integral to my workflow, as it has been for many others, and I've always appreciated the prompt responses to issues posted on Github.
...

Here is my session info. This project has spanned multiple years and so I currently need to continue to use an older version of Seurat.
> R version 4.2.2 (2022-10-31)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Monterey 12.6.5
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] patchwork_1.1.2       ifnb.SeuratData_3.0.0 SeuratData_0.2.2     
> [4] SeuratObject_4.1.3    Seurat_4.2.1         
> 
> loaded via a namespace (and not attached):
>   [1] Rtsne_0.16             colorspace_2.0-3       deldir_1.0-6          
>   [4] ellipsis_0.3.2         ggridges_0.5.4         rstudioapi_0.14       
>   [7] spatstat.data_3.0-0    leiden_0.4.3           listenv_0.8.0         
>  [10] ggrepel_0.9.2          bit64_4.0.5            fansi_1.0.3           
>  [13] codetools_0.2-18       splines_4.2.2          R.methodsS3_1.8.2     
>  [16] cachem_1.0.6           knitr_1.41             polyclip_1.10-4       
>  [19] jsonlite_1.8.4         ica_1.0-3              cluster_2.1.4         
>  [22] png_0.1-7              R.oo_1.25.0            uwot_0.1.14           
>  [25] spatstat.sparse_3.0-0  shiny_1.7.3            sctransform_0.3.5     
>  [28] compiler_4.2.2         httr_1.4.4             assertthat_0.2.1      
>  [31] Matrix_1.5-1           fastmap_1.1.0          lazyeval_0.2.2        
>  [34] cli_3.6.1              later_1.3.0            htmltools_0.5.3       
>  [37] tools_4.2.2            igraph_1.3.5           gtable_0.3.1          
>  [40] glue_1.6.2             RANN_2.6.1             reshape2_1.4.4        
>  [43] dplyr_1.0.10           rappdirs_0.3.3         fastmatch_1.1-3       
>  [46] Rcpp_1.0.9             scattermore_0.8        jquerylib_0.1.4       
>  [49] vctrs_0.5.1            ape_5.6-2              spatstat.explore_3.0-5
>  [52] nlme_3.1-160           progressr_0.11.0       lmtest_0.9-40         
>  [55] spatstat.random_3.0-1  xfun_0.35              stringr_1.5.0         
>  [58] globals_0.16.1         rbibutils_2.2.9        mime_0.12             
>  [61] miniUI_0.1.1.1         lifecycle_1.0.3        irlba_2.3.5.1         
>  [64] goftest_1.2-3          future_1.29.0          MASS_7.3-58.1         
>  [67] zoo_1.8-11             scales_1.2.1           promises_1.2.0.1      
>  [70] spatstat.utils_3.0-1   parallel_4.2.2         RColorBrewer_1.1-3    
>  [73] yaml_2.3.6             reticulate_1.26        pbapply_1.5-0         
>  [76] gridExtra_2.3          ggplot2_3.4.0          sass_0.4.4            
>  [79] stringi_1.7.8          Rdpack_2.4             rlang_1.0.6           
>  [82] pkgconfig_2.0.3        matrixStats_0.62.0     evaluate_0.18         
>  [85] lattice_0.20-45        tensor_1.5             ROCR_1.0-11           
>  [88] purrr_0.3.5            htmlwidgets_1.5.4      cowplot_1.1.1         
>  [91] bit_4.0.5              tidyselect_1.2.0       parallelly_1.32.1     
>  [94] RcppAnnoy_0.0.20       plyr_1.8.7             magrittr_2.0.3        
>  [97] R6_2.5.1               generics_0.1.3         DBI_1.1.3             
> [100] pillar_1.8.1           fitdistrplus_1.1-8     abind_1.4-5           
> [103] survival_3.4-0         sp_1.5-1               tibble_3.1.8          
> [106] future.apply_1.10.0    crayon_1.5.2           KernSmooth_2.23-20    
> [109] utf8_1.2.2             spatstat.geom_3.0-3    plotly_4.10.1         
> [112] rmarkdown_2.18         grid_4.2.2             data.table_1.14.6     
> [115] digest_0.6.30          xtable_1.8-4           R.cache_0.16.0        
> [118] tidyr_1.2.1            httpuv_1.6.6           R.utils_2.12.1        
> [121] TreeTools_1.8.0        munsell_0.5.0          viridisLite_0.4.1     
> [124] bslib_0.4.1

**Comment by longmanz** [comment]
Hi, 
Thanks for reporting this. You are right that sample.tree = NULL and preserve.order=FALSE will force the integration to be done in the same order. However, in the previous `FindIntegrationAnchors()` step, since the order of two objects are swapped, the set of anchors being selected are no longer the same. Given that, even if you force the `IntegrateData()` to be done in the same order, it will still produce a different "integrated" assay. 
However, a different "integrated" assay does not mean the integration is messed up. In fact, if you generate UMAP and perform clustering analysis using the 2 different integrated assays, you will obtain highly consistent results. I am not sure what you intend to do with the "normalized data" in the integrated assay. But please bear in mind that it is not supposed to be used for analyses like DE test or even generating heatmap. You should always switch back to the "RNA" assay for these analyses. 
If you insist to do so, you can manually order the list of Seurat objects. For example, you can do it based on the memory usage of each object:
```
sizes <- sapply(ifnb.list, object.size)
ordered_ifnb.list <- obj_list[order(sizes)]

immune.anchors <- FindIntegrationAnchors(object.list = ordered_ifnb.list, anchor.features = features)
immune.combined <- IntegrateData(anchorset = immune.anchors)
```
