### ISSUE TITLE
Reproducibility issue with integrated dataset

### ISSUE THREAD

**Issue by carol457** [satijalab/seurat#7218]
Dear Seurat team,

I am having similar issues as described in #2884 and #7217. 
Like #7217 this project spans several years so we have to continue with an older version of Seurat. 

My questions are: 
1. how can we ensure reproducibilty of our data when dependencies, such as Matrix are updated as well? (Note that I cannot install  the older version of Matrix, as Seurat v3.1.2 is now dependent on version >1.5)
2. And which information do we need to report when publishing our analysis, besides the version of Seurat, R, uwot, and the different parameters used (number of principal components, resolution)?

Thank you for your help!

**Comment by nathan-nakatsuka** [comment]
Dear @carol457 , unfortunately it is difficult to ensure exact reproducibility unless all the prior packages are the same and for our newer Seurat versions, we had to keep updating to be dependent on updated packages. You should report Seurat version, R, and the relevant dependent packages as well as all parameters you used in each of the functions that were not default parameters. The differences should usually be fairly small, though, so should not affect your basic interpretation of results.
