### ISSUE TITLE
CalcPerturbSig is not working

### ISSUE THREAD

**Issue by TsviyaOlender** [satijalab/seurat#7222]
Hi
I have seurat object of PertubSeq data. After loading the GEX data, and cleaning I have 5094 cells, one replicate. All cells have one guide, and every guide is present in at least 50 cells (I selected for these cells). After normalization, PCA and UMPA reduction I try to calculate 
CalcPerturbSig. I am getting the error:
Processing rep1
Error in nn2(data = numeric(0), query = c(6.42505122785096, 4.69891716494836,  : 
  Cannot find more nearest neighbours than there are points

seurat.obj.f<- CalcPerturbSig(
  object = seurat.obj.f, 
  assay = "RNA", 
  slot = "data", 
  gd.class ="targetGene", 
  nt.cell.class = "NT",
  reduction = "pca", 
  ndims = 30, 
  num.neighbors = 20, 
  new.assay.name = "PRTB")

**Comment by longmanz** [comment]
Hi,
You might consider reducing the value of "num.neighbors" (e.g., 10).

**Comment by TsviyaOlender** [comment]
Thank you so much for your prompt answer. Unfortunately, it didn’t help me. I found the problem- I had several types of non-targeted cells, with different names. When I renamed all non-targeted (NT-1,NT-2…etc.) as “NT”  the issue was solved. I run the function using the targetGene (several guides per gene). But when I try to run it with the guideID I get the error again. I renamed all “NT” guides as having the same guideID, and I tried to modify the num.neighbors and ndims. But it didn’t help. Can you please advise?
seurat.obj.f<- CalcPerturbSig(
  object = seurat.obj.f,
  assay = "RNA",
  slot = " data",
  gd.class ="guid.id",
  nt.cell.class = "NT",
  reduction = "pca",
  ndims = 15,
  num.neighbors = 10,
  new.assay.name = "PRTB")
Processing rep1
Error in nn2(data = numeric(0), query = c(5.03368192263483, -9.71553827437961,  :
  Cannot find more nearest neighbours than there are points

Many thanks
Tsviya

**Comment by longmanz** [comment]
Hi Tsviya,
Thanks for your information. 

1. Yes, in your "targetGene" column, the cells with a NT-guide should all be named as "NT", because "`nt.cell.class = 'NT'` " will only search for cells that exactly match the string "NT" in the "targetGene" column. 

2. When you switch to the "guideID" column, it is the same. All your cells with a NT-guide should all be named as "NT". 

Let me know if the issue persists, and I will re-open the issue.
