### ISSUE TITLE
 ScaleData run time run time long while regressing out variables

### ISSUE THREAD

**Issue by PriyaLakr** [satijalab/seurat#7223]
Hi,

How did you solve the issue? I'm having similar issue.

Would running ScaleData() only on top X variable features affected downstream analysis like FindAllMarks() or other DE analysis()?

As recommended in the tutorial, ScaleData() only on top X variable features would affect heatmap visualization.

Thank you,

**Comment by AustinHartman** [comment]
Typically, it's recommended to run `ScaleData` on only the `VariableFeatures` to save time and memory
