### ISSUE TITLE
Subset on expression level of MHC class II expression

### ISSUE THREAD

**Issue by Wongchang-T** [satijalab/seurat#7227]
Hi Seurat support team,

I have tried to subset cells base on expression level of genes encoded for MHC class II molecule such as H2-Eb1, H2-Aa and H2-Ab1 using subset command (as the below), but it is not success. However, I can run others whatever genes that is not MHC-class II.

My command
Hi.MHC <- subset(Object, H2-Eb1 >= 4)

It shows the errors as below
Error in FetchData.Seurat(object = object, vars = unique(x = expr.char[vars.use]), : 
None of the requested variables were found:

Thank you for support

**Comment by nathan-nakatsuka** [comment]
Dear @Wongchang-T , most likely you need to do: DefaultAssay(Object) <- "RNA". If that doesn't work, please provide the rest of the code and data so we can reproduce the error.
