### ISSUE TITLE
error when do feature selection

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#7229]
I have already run the previous code in the same page and goes well,
but when I run this code:
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2

The print hints:
Error in seq.default(min, max, by = by) : 'from' must be a finite number
In addition: Warning messages:
1: Transformation introduced infinite values in continuous x-axis 
2: Transformation introduced infinite values in continuous x-axis

Does anyone know what's going on there?  Does the data need to be precessed or any parameters with the axis need to be set when using the plot function?

Thank you very much!

**Comment by AustinHartman** [comment]
Hi, I'd first check that plot1 displays. If that's the case, check that top10 is a vector containing the cells you aim to label. If that doesn't work, please provide a reproducible example so I can diagnose further.

**Comment by yulchen810** [comment]
> Hi, I'd first check that plot1 displays. If that's the case, check that top10 is a vector containing the cells you aim to label. If that doesn't work, please provide a reproducible example so I can diagnose further.

I have resolved this problem, thank you a lot.
