### ISSUE TITLE
Error in object.list[[x]][[nn.reduction]]: during FindIntegrationAnchors

### ISSUE THREAD

**Issue by emanuelavilla** [satijalab/seurat#7230]
Hello!

I am trying to integrate 3 data of sc-ATAC. Each sample is the integration between 2 conditions (normal and tumoral). So, I have 6 samples in total.
When I did the integration of the two conditions for each sample, everything was fine. However, when I try to do the same between the 3 data (already integrated for the conditions), I got an error.
![Screenshot 2023-04-26 alle 11 54 08](https://user-images.githubusercontent.com/85672107/234540244-a094a278-f49f-44b2-9fce-b9dbbfcd6101.png)

I don't understand the reason why it worked for the integration of conditions, but not for the 3 data. Maybe it would be better to integrate all the 6 at the same time?

**Comment by Gesmira** [comment]
Hi, 
Did you run the dimensional reduction on the new datasets as shown in the ATAC integration vignette: `pbmc.atac <- RunSVD(pbmc.atac)`

**Comment by Gesmira** [comment]
Closing for now. Please feel free to reopen if your issue persists.
