### ISSUE TITLE
Seurat V5 cannot run FindMarkers

### ISSUE THREAD

**Issue by caodudu** [satijalab/seurat#7231]
The question is caused by the reconstruction of seurat.
The new object cannot fetch the data by the way `object[features, cells.1]` .

please modify the following code in the function FoldChange.default
```
    pct.1 <- round(x = rowSums(x = object[features, cells.1, 
        drop = FALSE] > thresh.min)/length(x = cells.1), digits = 3)
    pct.2 <- round(x = rowSums(x = object[features, cells.2, 
        drop = FALSE] > thresh.min)/length(x = cells.2), digits = 3)
```

**Comment by JHovelly** [comment]
I think the problem is that BPCell-based analysis doesn't support Findmarker.

**Comment by Gesmira** [comment]
Hi, 
Running `FindMarkers` should now be supported on objects with BPCells assays. Please reopen the issue if you find the error to persist. Thanks!
