### ISSUE TITLE
MapQuery projection onto ForceAtlas2 embeddings

### ISSUE THREAD

**Issue by KrGurashi** [satijalab/seurat#7233]
Dear Seurat team,

Thanks for the great tool.
I would like to project a queried sample onto a force-atlas2 embedding computed on my reference (saved in a the reference seurat object in reductions). However, currently MapQuery seem to be restricted on umap embeddings.

Is there anyway I could perform such projection? As I can easily compute the transfer anchors, could i just copy the first two dimensions of the reduction in the metadata and transfer it using TransferData?

Thanks

**Comment by AustinHartman** [comment]
No familiar with force-atlas2, but it seems reasonable that you could copy to metadata and then use TransferData. Of course, this isn't a supported workflow in Seurat so I can't really speak on the validity of this approach.
