### ISSUE TITLE
SCTransform: Error in is_scalar_character(x = key) : could not find function "is_scalar_character"

### ISSUE THREAD

**Issue by Priyadarshini-Rai** [satijalab/seurat#7238]
After uninstalling Seurat v5 and then installing Seurat v4.3, we are getting the following error while using SCTransform.

**Comment by Rui-Jing** [comment]
I encounted the same error.

**Comment by saketkc** [comment]
Can you retry after reinstalling SeuratObject?

```
remove.packages(c("Seurat", "SeuratObject"))
install.packages(c("Seurat"))
```

**Comment by Pointillomic** [comment]
I had the same issue and manually reinstalling SeuratObject caused the same error - presumably because the version was different. However, letting Seurat reinstall SeuratObject fixed the issue
