### ISSUE TITLE
How to extract certain cluster for other analysis

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7239]
Hi
I want to extract certain clusters from a dataset after analysis lets say  T Cells and want to save them as a file so it can be used for overlay analysis by other people.
How to extract the clusters in form of matrix so it can be used as starting file for other analysis?

**Comment by yuhanH** [comment]
Thank you @officialprofile for your help.
After subset, you can also save it as a rds file.

**Comment by zara03** [comment]
thank you so much.
