### ISSUE TITLE
Error in FindAllMarkers for large datasets

### ISSUE THREAD

**Issue by ericvon11** [satijalab/seurat#724]
Hi,
I'm having a similar issue to #417 
I'm trying to compute DEGs for a large dataset (>100k) and am getting no DEGs because the function is breaking at some point. I'm running this on a machine using 256GB RAM and have set max.cells as far low as 100 (tried 500, 1,000, and 2,000 as well) and am getting the error. It is not an issue with the quality of the cluster as I can run this on very well defined astrocyte clusters against neuronal clusters and still get this error:

```R
> c4 = FindMarkers(MyProject, ident.1 = 4, test.use = 'MAST', logfc.threshold = .5,  max.cells.per.ident = 100)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

I doubt max.cell.per.ident is working as its supposed to as 100 cells per cluster with 60 clusters in my object would lead to testing of 100 vs 5900 cells, which 256GB RAM should handle easily.

I also suspect the gene filter isn't working efficiently as downsampling genes.use works even with very relaxed thresholds (logFC of .1):
```R
c4 = FindMarkers(myProject, ident.1 = 4, test.use = 'MAST', logfc.threshold = .1, max.cells.per.ident = 100, genes.use = sample(rownames(MyProject@data),10000))
```

Yet when I increase genes.use and apply a very strict logFC thresh of 3, which should reduce the tested gene list down to only a few genes, I still get the same cholmod error:

```R
c4 = FindMarkers(MyProject, ident.1 = 4, test.use = 'MAST', logfc.threshold = 3, max.cells.per.ident = 100, genes.use = sample(rownames(all@data),15000))
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

I tried to reproduce this cholmod error and found it comes from:
```R
x = as.matrix(MyProject@data)
```
However, if cells.1 is properly set with 100 cells, there's no way this error should come up with as.matrix(MyProject@data[ , (100cellnames)])

Is it possible that the function is asking for the full object's dense matrix before filtering the genes or cells?

**Comment by ericvon11** [comment]
Also, this is using Seurat v2.3.4

**Comment by DanSchnell** [comment]
I wonder if my post (718) is a manifestation of the same underlying issue(s).
I was wondering if the seurat object itself was corrupted.
I'm going to try applying the SubsetData function to the so before calling FindAllMarkers to see if FAM provides the usual output.

**Comment by DanSchnell** [comment]
Calling SubsetData to reduce each ident to 200 cells did not fix issue in post 718.
Using seurat 2.3.1

**Comment by satijalab** [comment]
Do you receive the same error with default expression tests? I'm wondering if this may be specifically related to the MAST DE test.

**Comment by ericvon11** [comment]
So one workaround appears to be to go into FindMarkers and specify `cells.2` as a subset on the frontend, which will give pct.1, pct.2, etc. metrics according to the subset that was specified (currently these numbers are computed using all cells). I guess taking random samples from this each time will make the measured pct.1, pct.2 and avg_logFC disagree slightly between clusters since there might be 500/1,000 cells that express gene-x in one iteration of sampling, then only 490/1,000 cells that express it in the next round of sampling. With the other option being to not have this test work at all, I think I'll take the slight disagreeance

for subsetting all of ident.2 to only be equal to max.cells.per.ident :
```
else {
    if (is.null(x = ident.2)) {
      set.seed(seed = random.seed)
      cells.2 <- sample(names(object@ident[!(object@ident == ident.1)]), max.cells.per.ident)
    }

```
OR, what I want is to threshold huge clusters to only include max.cells.per.ident, as in SubsetData:

```
  else {
    if (is.null(x = ident.2)) {
      cells.2 <- WhichCells(object, max.cells.per.ident = max.cells.per.ident)
    }
```
It also helps to add max.cells.per.ident to cells.1 as well to avoid 10,000 cell clusters from using all 10,000 of those cells to test expression.

**Comment by pandhey** [comment]
> So one workaround appears to be to go into FindMarkers and specify `cells.2` as a subset on the frontend, which will give pct.1, pct.2, etc. metrics according to the subset that was specified (currently these numbers are computed using all cells). I guess taking random samples from this each time will make the measured pct.1, pct.2 and avg_logFC disagree slightly between clusters since there might be 500/1,000 cells that express gene-x in one iteration of sampling, then only 490/1,000 cells that express it in the next round of sampling. With the other option being to not have this test work at all, I think I'll take the slight disagreeance
> 
> for subsetting all of ident.2 to only be equal to max.cells.per.ident :
> 
> ```
> else {
>     if (is.null(x = ident.2)) {
>       set.seed(seed = random.seed)
>       cells.2 <- sample(names(object@ident[!(object@ident == ident.1)]), max.cells.per.ident)
>     }
> ```
> OR, what I want is to threshold huge clusters to only include max.cells.per.ident, as in SubsetData:
> 
> ```
>   else {
>     if (is.null(x = ident.2)) {
>       cells.2 <- WhichCells(object, max.cells.per.ident = max.cells.per.ident)
>     }
> ```
> It also helps to add max.cells.per.ident to cells.1 as well to avoid 10,000 cell clusters from using all 10,000 of those cells to test expression.

Hi,

I have similar issue. I tried with max.cells.per.ident but it doesn't work. I am currently using Seurat v2.3. did you get markers for your data. I really appreciate your reply.
