### ISSUE TITLE
Normalize raw expression per SAMPLES, not cells

### ISSUE THREAD

**Issue by maithermbarros** [satijalab/seurat#7244]
I understand that the normalization performed by NormalizeData() is done per cell. Normalization is applied uniformly across all cells in the dataset, regardless of their sample of origin. However, I am working with a massive Seurat object that contains reads from different patients and within each patient I have different samples originated from different organs.

I would like to normalize the raw expression per sample, as I believe there are strong technical batch effects between samples that need to be removed. How can I get this done using Seurat? Shall I use the block.size argument within NormalizeData()? Or could I just run NormalizeData() followed by ScaleData()?

Any input would be greatly appreciated. Thank you!

**Comment by longmanz** [comment]
Hi, 
The default normalization method in NormalizeData() is 'LogNormalize', which only depends on the total read count in one cell, regardless of the sample of origin. NormalizeData() is not be able to correct for your sample/batch effect. Please consider using Harmony package if you want to correct for that (https://portals.broadinstitute.org/harmony/index.html, https://www.nature.com/articles/s41592-019-0619-0).

block.size is just a way to do the normalization in parallel for speed. It has not effect on the normalization.
