### ISSUE TITLE
Integration strategy: SCT or simple merge???

### ISSUE THREAD

**Issue by tf1993614** [satijalab/seurat#7247]
Hi,

I have three scRNA datasets that come from different tissues but all contain steroidogenic cells. I analysed those datasets individually to retrieve those steroidogenic cells per dataset. Finally, I got three Seurat objects containing stereogenic cells from different tissues.

Now, I want to integrate those three Seurat objects to form a new Seurat object in order to check if there is any difference among stereogenic cells from different tissues.

I tried two strategies:

- I simply merged those three Seurat objects by using merge function and ran standard workflow. Those steroidogenic cells from different tissues can separate from each other on UMAP. That's what I expect. But I am afraid it may be the consequence of batch effect instead of real biological differences, since simple merging can't do batch effect correction.

- Then, I tried to integrate three Seurat objects by single cell transform (SCT) algorithm. I used normalized counts afte SCT to make a UMAP again and found all cells from different tissue mix together. That doesn't biologically make sense. I am worrying whether SCT would over correction to remove biological difference among cells from different tissues?

**This is UMAP of SCT**
![Rplot](https://user-images.githubusercontent.com/61369770/235106233-6e4a80c1-d441-4690-abcb-315700a80c46.png)

**This is UMAP of simple merging**
![Rplot02](https://user-images.githubusercontent.com/61369770/235106379-8c28eda3-ffae-4831-8253-2fe9db2346d5.png)

Could you give me some suggestions?

Thanks,
Feng

**Comment by saketkc** [comment]
While it is not clear whether you ran SCT or used SCT based integration workflow, it seems to goal of your analysis would be to identify what is different (or similar) between these celltypes. I think doing a DE analysis is more suitable here. Alternatively if your goal is to identify analogous subpopulation among these celltypes across tissues then you would want to go the integration route.
