### ISSUE TITLE
Proper location inside Seurat object for custom dimensional reductions?

### ISSUE THREAD

**Issue by plijnzaad** [satijalab/seurat#7248]
What is the proper place to put / find additional dimensional reductions (i.e. ones that were not calculated by e.g. `RunUMAP`)  so that that they work properly with `DimPlot` and `FeaturePlot` when specifying a `reduction` argument? The layout of the Seurat object has reductions both as list members in the toplevel (e.g. `obj$umap`) and  as list members of the `obj@reductions` slot.  It is confusing because removing unwanted reductions doesn't always seem to work. This appears to be related to issues #1742

**Comment by Gesmira** [comment]
HI, 
You can add your own reduction using the following function: 
```
object[["custom"]] <- CreateDimReducObject(embeddings = custom_reduction, key = "custom_", assay = DefaultAssay(object))
```
