### ISSUE TITLE
doc error in Seurat 

### ISSUE THREAD

**Issue by jlchen5** [satijalab/seurat#7249]
No method or default for coercing “Assay” to “Assay5” on [this page](https://satijalab.org/seurat/articles/seurat5_spatial_vignette.html). If I change the `assay5` to `assay` which is correct and could run.

<img width="874" alt="截屏2023-04-28 19 50 45" src="https://user-images.githubusercontent.com/61578993/235141865-5d302b34-c41a-4ac8-a79c-b86fbf196836.png">

**Comment by AustinHartman** [comment]
Assuming you have v5 installed, you can coerce an `Assay` to `Assay5` with 
```r
brain[["Spatial"]] <- [as](https://rdrr.io/r/methods/as.html)(brain[["Spatial"]], Class = "Assay5")
```
