### ISSUE TITLE
Merging large dataset problem

### ISSUE THREAD

**Issue by wliangl** [satijalab/seurat#7250]
Hi, I am trying to merge 9 individual drug treatment Multiome datasets to a large dataset which may have >150K cells. I am having the following problems:

1. Since these dataset are not necessarily overlapped (i.e.: they do not always have the control group for the same cell line), I may not be able to find any anchor point among all the datasets and  have to merge them using the traditional "merge" function,  it takes very long time (on a server, >24hrs so far and still not finished yet). Is there any better/faster way to merge them?

2. I did a test run to merge 3 datasets before normalization and HTO demultiplexing. However, after merging, the HTODemux function always failed with the message "Cells with zero counts exist as a cluster". In the merged dataset, there are around 30 different HTO conditions.  I did some other tests and found that if the HTO condition is more than 20, then some times I will see this "zero counts" message.  If I run HTODemux on individual datasets and then merge, there is no problem. Is there any good explanation or solution for this? I may need to run large datasets with more than 30 HTO conditions in the future. 

Thank you so much for the help  

Wliangl

**Comment by mhkowalski** [comment]
Hi, 

1. We do provide extensive functionality in our new Seurat v5 release to handle integrating large datasets and performing differential expression (see [here](https://satijalab.org/seurat/articles/parsebio_sketch_integration), for example).

2. I would recommend running HTODemux on individual datasets and then merge. The function tries to learn a background distribution of HTO counts, which might be different between datasets, so this should be run prior to merging.
