### ISSUE TITLE
BridgeIntegration: no applicable method for 'DefaultAssay' applied to an object of class "BridgeReferenceSet"

### ISSUE THREAD

**Issue by ShanshanHe7** [satijalab/seurat#7252]
Hello and good day! 
I have a problem with MapQuery while running Bridge Integration followed by your [vignettes](https://satijalab.org/seurat/articles/seurat5_integration_bridge.html).
I successfully constructed the extended reference with reference and multiome data, and found the bridge anchors between query and the extended reference.
However, when I was trying to map the query dataset onto the extended reference with MapQuery function, I got this error:
`Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "BridgeReferenceSet"`
  Below is the MapQuery code I ran:
`obj.atac    <- MapQuery(anchorset = bridge.anchor,  
reference = obj.rna.ext,
query = obj.atac,
reduction.model = "umap",
)`
Then I search the source code in MapQuery and  found this problem maybe is setting 'DefaultAssay()'
`reference[[anchor.reduction]] <- CreateDimReducObject(embeddings = ref.reduction.emb,
key = "L_", assay = DefaultAssay(reference))`
I also had the same error while trying to get the DefaultAssy with obj.rna.ext
 `> DefaultAssay(obj.rna.ext)
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "BridgeReferenceSet"`
  In this case,  how can I map the query dataset onto the extended reference? Should I change the reference from obj.rna.ext to obj.rna ?
  Thanks!

**Comment by yuhanH** [comment]
There may be a bug in this object. Could you post a reproducible example? Or email me your object, yhao@nygenome.org 
Thank you.

**Comment by ShanshanHe7** [comment]
Thanks for your reply! Below is the detail of all data I used.
> obj.multi
An object of class Seurat 
264737 features across 10202 samples within 3 assays 
Active assay: RNA (36601 features, 0 variable features)
 2 other assays present: ATAC, SCT
 7 dimensional reductions calculated: umap.atac, pca, umap.rna, lsi, harmony_pca, harmony_lsi, umap.wnn
> obj.atac
An object of class Seurat 
199507 features across 5498 samples within 1 assay 
Active assay: ATAC (199507 features, 199507 variable features)
 2 dimensional reductions calculated: umap.atac, lsi
 > obj.rna
An object of class Seurat 
54287 features across 24046 samples within 3 assays 
Active assay: SCT (20322 features, 3000 variable features)
 2 other assays present: RNA, integrated
 4 dimensional reductions calculated: pca, umap, tsne, harmony
 dims.atac <- 2:50
dims.rna <- 1:50
DefaultAssay(obj.multi) <-  "RNA"
DefaultAssay(obj.rna) <- "SCT"

And below is the code :
obj.rna.ext <- PrepareBridgeReference(reference = obj.rna,
                                      bridge = obj.multi, 
                                      reference.reduction = "pca", 
                                      reference.dims = dims.rna,
                                      normalization.method = "SCT"
)
bridge.anchor <- FindBridgeTransferAnchors(extended.reference = obj.rna.ext, 
                                           query = obj.atac, 
                                           reduction = "lsiproject",
                                           dims = dims.atac,
)
obj.atac <- MapQuery(anchorset = bridge.anchor, 
                     reference = obj.rna.ext,
                     query = obj.atac, 
                     refdata = obj.rna$cell_type,
                     reduction.model = "umap",
)
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "BridgeReferenceSet"

**Comment by ShanshanHe7** [comment]
Also I found there is a function called `FindBridgeAnchor` in your `FindBridgeTransferAnchors`function. I am curious how this function works but I couldn't find the codes of this function in your github or in R package. 
> FindBridgeAnchor()
Error in FindBridgeAnchor() : could not find function "FindBridgeAnchor"

**Comment by yuhanH** [comment]
Hi @ShanshanHe7 
From the below error, it seems that your seurat and seurat object are out of version. 
```
Error in UseMethod(generic = "DefaultAssay", object = object) :
no applicable method for 'DefaultAssay' applied to an object of class "BridgeReferenceSet"
```
Could you update them to the seurat v5 and re-try it?

`FindBridgeAnchor` is an internal function. You can access it by `Seurat:::FindBridgeAnchor`

**Comment by ShanshanHe7** [comment]
Hi, I checked my object version and the session information. I will try to update my object and see if it can success. Thank you 
> Version(obj.rna)
[1] '3.1.5'
> Version(obj.multi)
[1] '4.1.3'
> Version(obj.atac)
[1] '4.1.3'
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.2.1
Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
 [1] EnsDb.Hsapiens.v86_2.99.0 ensembldb_2.22.0          AnnotationFilter_1.22.0   GenomicFeatures_1.50.4   
 [5] AnnotationDbi_1.60.0      Biobase_2.58.0            GenomicRanges_1.50.2      GenomeInfoDb_1.34.9      
 [9] IRanges_2.32.0            S4Vectors_0.36.1          BiocGenerics_0.44.0       qs_0.25.4                
[13] ggrepel_0.9.3             symphony_0.1.1            harmony_0.1.1             Rcpp_1.0.10              
[17] SeuratDisk_0.0.0.9020     forcats_1.0.0             stringr_1.5.0             dplyr_1.1.0              
[21] purrr_1.0.1               readr_2.1.4               tidyr_1.3.0               tibble_3.1.8             
[25] ggplot2_3.4.1             tidyverse_1.3.2           data.table_1.14.6         Signac_1.9.0             
[29] SeuratObject_4.1.3        Seurat_4.1.1.9001

**Comment by ShanshanHe7** [comment]
> 

Also I used `UpdateSeuratObject()` to update my RNA reference object to `4.1.3` and run the codes, however I still reproduce  the same problem
