### ISSUE TITLE
Converting log2TPM_matrix into Seurat object

### ISSUE THREAD

**Issue by yechanYS** [satijalab/seurat#7253]
I recently downloaded normalized_log2TPM_matrix.rds file from GSE131907.
So, I read this log2TPM matrix file into data frame, using readRDS() function, and confirmed the barcodes/cell names are in colnames, the genes are in rownames.

But, when I try to convert this data frame into seurat object using CreateSeuratObject(), i can see the error message "R session aborted. The R session had a fatal error. The session was terminated."

How can I create seurat object from this dataset? Is it a problem that I didn't use dgCMatrix?
Used code is below:

```
library(dplyr)
library(Seurat)
library(patchwork)

luad.mtx <- readRDS("~/Desktop/GSE131907_Lung_Cancer_normalized_log2TPM_matrix.rds")
print(rownames(luad.mtx))
print(colnames(luad.mtx))

luad <- CreateSeuratObject(counts = luad.mtx, min.cells = 20, min.features = 200)
```

**Comment by saketkc** [comment]
I was able to create the object using the following lines:

```
object <- CreateSeuratObject(counts = luad.mtx, data=luad.mtx)
```

It is possible that your instance of R is running out of memory (due to limited RAM).
