### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by ahlem1962** [satijalab/seurat#7255]
Hello,
I'm working on different replicate of 2 types of conditions (patients and control ) 
my question : should we created a seurat object for each replicate and don't merge then and then apply the normlization and batch effect seperately or we merge 2 conditions and then apply the batch effect ? 
second question : How to choose the appropriate method for batch effect (harmony or seurat or ... ) 
My ultimate objective is to determine differencial gene expression across the 2 conditions

**Comment by mhkowalski** [comment]
Hello, 

For your question about normalization, if you are just doing log-normalization, then it will not matter whether you merge or normalize first. If you are using a more sophisticated technique like SCTransform, I would recommend running this on the replicates separately (see #6054).

 The best way to choose an integration method is probably to try different things out and compare the results. The goal of integration is to annotate similar cell types in both replicates (which enables DE analysis as you say), so a simple check is to look at cell type markers of interest to determine how well the batch correction is working.
