### ISSUE TITLE
"Blank codeword" non-existent in recent update to Xenium output files

### ISSUE THREAD

**Issue by limm4** [satijalab/seurat#7257]
Hi team, 

I ran the xenium tutorial (mouse brain dataset) and everything was working well until I ran Seurat on my actual dataset. 
I get the following error (see below) and when I checked back, 10x genomics has made new output file changes in their v1.1 (Feb 2023) update and renamed “Blank Codeword” feature type in cell-feature matrix to “Unassigned Codeword”. https://www.10xgenomics.com/support/in-situ-gene-expression/documentation/instruments/xenium-analyzer/release-notes-xenium-analyzer-instrument-sw
Hence, this new change is not recognized in Seurat when running datasets that have been generated recently. 

Is there a way fix this? Thank you very much!

Error in `CreateAssayObject()`:
! No cell names (colnames) names present in the input matrix
---
Backtrace:
    ▆
 1. └─Seurat::LoadXenium(path, fov = "fov")
 2.   └─SeuratObject::CreateAssayObject(counts = data$matrix[["Blank Codeword"]])

**Comment by AustinHartman** [comment]
Hi @limm4, support for this change is included on the develop branch of Seurat, and will be released on CRAN in the near future
