### ISSUE TITLE
DE expression analysis between 2 conditions (not integrated) by using FindMarkers(). Which slot to use?

### ISSUE THREAD

**Issue by rmc0106** [satijalab/seurat#7258]
Hi,
I read many other posts about this topic and also your new vignette here: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html. I would like to ask a clarification about a scenario where data integration is not needed, and comparing SCtransform v1 versus v2

In my case I have one experiment with 2 datasets: stim and ctrl (Left and right hemisphere of a same mouse brain, dissected together but collected in 2 different tubes for 10x genomics). 
Since they are very similar, after clustering they show the same cell types, and the UMAPs basically look almost identical, so I don't integrate the 2 data sets.

First, after initial QC, I apply NormalizeData(), FindVariableFeatures(),  ScaleData(), RunPCA() to check for example if the mitochondria genes are source of unwanted variation (and eventually regress it out later). This, creates the "RNA" slot with "counts" "data" and "scale.data"
Then I apply SCTransform() (I believe still the version1) and here I regress out the mito genes. At this point the function creates the "SCT" slot, with its "counts" "data" and "scale.data". After this, I apply RunPCA() again.
Next, after selecting the number of PCs, I run FindNeighbors() and RunUMAP()

At this point, I can run FindMarkers() between the 2 conditions but it is not clear to me now which slot I have to select now, prior applying this function. At the moment I am using the default test that the function uses, which I believe is Wilcox.
Should I use DefaultAssay() to select the "RNA" slot or the "SCT"? 
If "RNA" slot, which of the "counts" "data" and "scale.data" subslots should I use? What does the default do?
Same question if I have to use "SCT" slot: which of the "counts" "data" and "scale.data" subslots should I use? What does the default do?

I am asking this because in your new vignette with sctransform version2 you show that you integrate the data first, I was not sure if what described in your vignette is applicable to my analysis.

Thank you!

**Comment by alikhuseynov** [comment]
it depends which statistical test you are using, eg if `"wilcox"` then normalized data should be used `slot = "data"`
details are in ?Seurat::FindMarkers(), eg `slot` _Slot to pull data from; note that if test.use is "negbinom", "poisson", or "DESeq2", slot will be set to "counts"_

**Comment by rmc0106** [comment]
@alikhuseynov thanks for your help. I understand that it is test dependent but I was curious about the new SCT described in this vignette https://satijalab.org/seurat/articles/sctransform_v2_vignette.html. If I don't need data integration and then I apply FindMarkers() without specifying which test in the argument, so by using the default Wilcox test, do I still have to select the "data" of "RNA" slot that contained the normalized data generated by NormalizeData()? 
Because in the vignette it says that we should use the "SCT" instead, but it describes a scenario where they integrated the data first. I was wondering if that is applicable for non-integrated data as well.

**Comment by saketkc** [comment]
@rmc0106 Given you are using the SCT workflow, I would recommend using the SCT assay for DE analysis. When you run `FindMarkers(object, assay="SCT")`, it chooses the data slot (which stores log1p(corrected counts)) as the default. DE should not be run on `scale.data` slot (at least not using the wilcoxon test).

**Comment by rmc0106** [comment]
@saketkc, ok thanks! To summarize what I am gonna do and just double check that I understood correctly:
 I will apply your version2 of SCT which is SCTransform(myobject, vst.flavor = "v2") on my data. Then, I will select the "SCT" slot by using FindMarkers(object, assay"SCT"). If not specificied, FindMarkers() will automatically use the Wilcoxon test and select the "data" of the "SCT" slot, so I don't have to be worried about a chance that it accidentally uses "scale.data". All this can be done, **no matter the data was integrated or not**, correct?
 
 Thank you very much!

**Comment by rmc0106** [comment]
@saketkc PS: Then, I assume that what it is written in this post, dated 2019, https://github.com/satijalab/seurat/issues/2027 Satija lab says that "For DGE, we recommend using the RNA assay (normalized counts)", is not valid anymore, right? And that based on what you just told me "SCT" is as recommended as "RNA" slot, correct?

**Comment by saketkc** [comment]
Yes, you can use SCT data slot for DE (irrespective of whether you integrate or not)

**Comment by rmc0106** [comment]
@saketkc thank you!

**Comment by haoyanioz** [comment]
> Yes, you can use SCT data slot for DE (irrespective of whether you integrate or not)

Dear saketkc, 

For my data, I observed significant discrepancies in the sets of differentially expressed genes obtained from RNA data slot and SCT v2 data slot. Have you encountered a similar situation before?


Best,
Star

**Comment by haoyanioz** [comment]
Dear saketkc @saketkc ,

For my data, I observed significant discrepancies in the sets of differentially expressed genes obtained from RNA data slot and SCT v2 data slot. Have you encountered a similar situation before?

Best,
Star

**Comment by rmc0106** [comment]
@saketkc as a follow up question: in some tutorials it says that the DE on SCT assay will be only done on the first 2000-3000 most variable genes and this would be an issue if we want consider all the genes (since many of the genes of interest might not be present in the data anymore). Is this true?

**Comment by saketkc** [comment]
Can you point me to the vignette where this is mentioned (it is incorrect if it is mentioned so). Are you sure you are not talking about variable genes?

**Comment by rmc0106** [comment]
@saketkc I found it here in this Harvard bioinformatics course: https://hbctraining.github.io/scRNA-seq_online/lessons/08_SC_clustering_quality_control.html when the explore the clusters identities by using known marker genes.
It says: "NOTE: The SCTransform normalization was performed only on the 3000 most variable genes, so many of our genes of interest may not be present in this data."


Also, it is something that I noticed by myself:
10% of my cells express GFP. If I try to find these GFP expressing cells in the UMAP by considering the "RNA" assay, then I can find them. However, if I try to find these cells in the UMAP by considering the "SCT" assay, then it says that all the cells in my dataset have zero expression of GFP.

This is a problem when I run the DE with FindMarkers() between the 2 conditions.
My clustering on the entire dataset shows 10 clusters in both conditions: 0,1,2,3,4,5,6,7,8,9; but I want to run DE only on the clusters where I see GFP expression which are cluster 1,2,3. So I subset the dataset to get only 1,2,3 and I run DE on 1,2,3 comparing stim vs ctrl. If I consider all the cells of clusters 1,2,3 (so GFP expressing cells + the rest of cells not expressing GFP but in these same clusters), then DE on SCT assay works. However, if I want to run DE ONLY on the GFP expressing cells from clusters 1,2,3, then I have to use the "RNA" assay, because otherwise it just says that in the SCT assay there are no cells with GFP expression > 0. 

That's why I am confused on which is the best assay/slot to use for DE analysis

**Comment by saketkc** [comment]
I don't understand the rationale of the vignettes you linked, but just to clarify these are not Seurat vignettes.

SCT's correction step can assign 0 counts to GFP gene so that is what it seems to be doing. If you a priori know which cells express GFP - you can assign that as an additional identity to the metadata and use that to perform your subset operation.  I would still recommend using the SCT slot for DE (Please make sure you are using the latest version of Seurat).

**Comment by rmc0106** [comment]
@saketkc  I am using the v4.3.0, which I believe it is the latest. 
What's the reason why SCT's correction step assigns 0 counts to GFP gene? 


Ok I am using these following lines to find a priori the identities of the GFP expressing cells:

DefaultAssay(LR_merged__clust_1_2_3) <- "RNA"

ID_cells_GFP_clust <- c(WhichCells(LR_merged__clust_1_2_3, expression = GFP > 0))

LR_merged__clust_1_2_3_onlyGFP<- subset(LR_merged__clust_1_2_3, cells = ID_cells_GFP_clust)

Idents(LR_merged__clust_1_2_3_onlyGFP)<-"orig.ident"

LR_merged__clust_1_2_3_onlyGFP <- PrepSCTFindMarkers(LR_merged__clust_1_2_3_onlyGFP)

LvsR_markers <- FindMarkers(LR_merged__clust_1_2_3_onlyGFP,
                                                           assay="SCT",                       
                                                           logfc.threshold = 0.0,
                                                            min.pct=0,
                                                           ident.1 = "L_filt_feature_bc_matrix",
                                                           ident.2 = "R_filt_feature_bc_matrix",
                                                           recorrect_umi = FALSE) 
                                                           
                                                           
Now it seems it works, thanks. The PrepSCTFindMarkers() does not really do anything though
