### ISSUE TITLE
One specific character variable fails to be included as latent.vars in FindMarkers function

### ISSUE THREAD

**Issue by reneemoerkens** [satijalab/seurat#7262]
Hi Seurat team,

I am experiencing an issue with including one of my variables as latent.vars in the FindMarkers function. I use the function below with Seurat 4.3.0 on SCT assay of the Seurat object (after performing SCTransform_v2):
`cluster.markers <- FindAllMarkers(ooac, min.pct = 0.1, logfc.threshold = 0.25, test.use = "MAST", latent.vars = c("cell_line", "condition", "CDR"))`

The variables I include as latent.vars are the following: 
cell_line: class/mode = character
condition: class/mode = character
CDR: class/mode = numeric

I do not get an error, but when I compare the output of the FindAllMarkers function including and excluding these latent.vars, I get exactly identical results with or without 'condition' as latent.vars, while p-values change after including either 'cell_line' or 'CDR'. 

The Ident is set to my cell type clusters and each of the clusters contains a mix of the different conditions that are specified in the 'condition' variable. I also used the stand alone version of MAST to verify that 'condition' has a significant effect in a qq-plot.
Also, both 'cell_line' and 'condition' character variables contain elements only consisting of letters (no other functional signs).

Is there anything I could still check for this character variable 'condition' that might explain why it is not influencing the analysis/not taken into account?

Also, it is expected that the differences of including latent variables only shows in the p-values, not in the number or identity of DE genes and average log2FC? 

Thank you so much!

**Comment by nathan-nakatsuka** [comment]
Dear @reneemoerkens , is it possible that one of our other variables encompasses the "condition" variable? or is it that when you use Stand alone MAST and you put in all of the variables, then you have a different result than when you use the Seurat version? It might be also that something to do with 'condition' being in factor form (or not in factor form)? I would need a reproducible example of this to debug it properly.

**Comment by mhkowalski** [comment]
Hi- closing because of lack of response. I agree with Nathan that your model may be over-specified, so adding "condition" will not change the results. Please let us know if we can assist further.
