### ISSUE TITLE
Difference between map query and integration

### ISSUE THREAD

**Issue by sakatash** [satijalab/seurat#7264]
Dear Seurat crew,
First thank you for the awesome package and the continued updates and maintenance. This is so useful!
I was wondering regarding the difference between map query and integration procedures.

I have 2 datasets; one from a 10x run and the other from SMRTseq. The proportions of cell types in each is different. The 10x data should have most of the cell types of the tissue in question (so in essence a reference), while the SMRTseq data should include only a small subset of these, and possibly others which don't exist in the original 10x.

As far as I understood it, all the different integration methods can mostly be used to impute the similarities (and differences) between the annotations of one dataset onto another. No further analysis can be done on an integrated dataset (i.e. DEG)
Both map query and integration require the definition of anchors, but for integration the data is further processed as a whole, essentially restructuring the data. This restructuring prevents assignment of cluster identities, as these are new clusters which may be composed of different cells. 
My question is then in this case where I want to find assign cluster identity from one data set to another, what would be the benefits of integration?
Thank you very much

**Comment by Gesmira** [comment]
Hi,
Based on your use case of wanting to assign cluster identities from the reference to a query, you should use the MapQuery workflow outlined [here](https://satijalab.org/seurat/articles/integration_mapping.html). Integration allows further analysis, but you would have to repeat clustering and relabel the clusters.
