### ISSUE TITLE
FindMultiModalNeighbours Error: std::bad_alloc

### ISSUE THREAD

**Issue by aodainic7** [satijalab/seurat#7265]
Hey guys,
I have a big dataset of 337965 cells out of 206 samples, which is a subset of CD8 and NK cells out of a larger PBMC dataset. I have only 1091 features, since I'm working with the most variable ones and, additionally 137 ADT features. 
![image](https://user-images.githubusercontent.com/130008047/236139019-55f5ba84-83af-4994-abd6-47dc5de73c6d.png)

I am trying to perform the WNN analysis, and since I have so many samples, I get 150 wsnn clusters with a resolution of 0.4 and k.nn of 20. The majority of the cells cluster in the first 40 clusters, and the rest of the clusters contain 4 cells or less. When I try to increase the k.nn, the maximum what I increased it to is 80 without it crashing, thus reducing the number of clusters to 80. I would like to go higher with the k.nn but I get the following errors:
 Error in ComputeSNN(nn_ranked = select_nn, prune = prune.SNN) : 
  std::bad_alloc
or
Constructing multimodal SNN graph
Error: std::bad_alloc
Execution halted
![image](https://user-images.githubusercontent.com/130008047/236139651-f55d9a81-3b10-4ebb-b9f0-599a443f8e53.png)
![image](https://user-images.githubusercontent.com/130008047/236139764-bfdb16a9-aaca-4091-a98a-9897766eac9b.png)

I can't be running out of memory, since I am running it on a hpc and I allowed up to 250 Gb for the job, it stops at 85 Gb. 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/130008047/236139879-74ec5459-29e8-47c9-806d-af3b82d493a3.png">

I have searched through the Issues list on Github, and found a similar problem. I have tested the solution of the previous people, without success. I can do FindNeighbours() on both 'pca' and 'apca' without a problem. 

Thanks in advance!

**Comment by yuhanH** [comment]
hi @aodainic7 
It seems to be a similar issue with https://github.com/satijalab/seurat/issues/4793
Decreasing prune.SNN to 1/20 may solve that over-clustering issue. 
The error/limit you get is from RCPP when we put KNN graph into C++ to calculate SNN graph. I think decreasing  `prune.SNN` or increasing `knn.range` in `FindMultiModalNeighbors ` will solve this issue.
