### ISSUE TITLE
How to merge 2 Seurat datasets of different tissues that can cluster them independently, but visualise them in the same UMAP?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#7267]
Hi there, 

I have 2 fully clustered Seurat objects. Each comes from a different tissue. I do not want to integrate them because I want to use `RNA Velocity` analysis to see the potential differentiation relationships among the clusters between these 2 tissues. 

Should I merge the 2 objects (instead of integrating), but then how do I ensure that they are clustered independently or more accurately, how can I visualise them both in the same UMAP? 

Earlier I computed a de novo UMAP with one object as ref and the other as query, but ofc, it will force the cells to co-cluster together.

Thank you for your help!

**Comment by mhkowalski** [comment]
Hello, 

I am not sure what you mean here. You say that you want to visualize cells on the same UMAP but not force them to co-cluster together. If you calculate RNA velocity separately on each dataset, I'm not if those are comparable across datasets.

**Comment by denvercal1234GitHub** [comment]
Hi @mhkowalski -- Thank you for your response! My apologies for the unclear questions. 

So I have 2 Seurat objects that were fully clustered and everything. Each from a different tissue. I did compute RNA velocities for each tissue object separately. Now, I aim to see if there is a way that I could compute RNA velocity of these 2 tissue data together. 

I could merge the 2 Seurat object data and then perform the typical clustering (with integration using the batch variable as tissue type) but then the cells from each tissues likely co-cluster together because likely there are cell types in one tissue that are present in the other tissues. So if that is the case, then I would not be able to see whether the RNA velocity arrows pointing to clusters of one tissue towards clusters of another tissue, because a cluster now would contain cells of both tissues, right?

IDK, do you have any suggestions to visualise the differentiation relationships between clusters of a tissue towards clusters of another tissues?

**Comment by yuhanH** [comment]
hi @denvercal1234GitHub 
If you just aim to visualize those two tissues in the UMAP but separately, you can add a constant value into the first dimensions of the UMAP from the second object. This modification can create a separation between the two.
