### ISSUE TITLE
Multiple genes in one violin plot

### ISSUE THREAD

**Issue by cesco-lemon** [satijalab/seurat#727]
Hello everyone,

I've been looking at a variety of genes in my different clusters, it looks pretty amazing and it was relatively easy thanks to Seurat!!!

What I would like to visualise now is the expression of certain genes in all the cells before clustering. I was able to generate plots like this one below (Rplot.pdf) that looks at the expression of certain genes in the total population but I was wondering if it was possible to generate a single graph that shows more than one violin plot for different genes in the total population (similar to multiple genes one plot).

[Rplot.pdf](https://github.com/satijalab/seurat/files/2311579/Rplot.pdf)

![multiple genes one plot](https://user-images.githubusercontent.com/42619695/44485878-0b16ad80-a620-11e8-814e-75c72761bc51.png)

**Comment by satijalab** [comment]
We have a couple solutions, depending on exactly what you are asking

1. If you want to visualize genes across different groups of cells, you can use the group.by argument to split the ViolinPlot - for example - across clusters or replicates.

2. You can return ggplot2 objects for each plot, and plot the results simultaneously using plot_grid from the cowplot package.

See our visualization vignette on the website for examples of both
