### ISSUE TITLE
Why does scRNA-seq dataset integration using Seurat 4.3 blend together biologically distinct tumour subtypes inappropriately?

### ISSUE THREAD

**Issue by jjacob12** [satijalab/seurat#7271]
Hi Satija Lab,
Using Seurat 4.3, I have tested the scRNA-seq Integration workflow (conventional workflow) with several publicly available datasets of medulloblastoma tumour subtypes. There are 4 major subtypes and in attempting to test the relatedness to an established cell line, corresponding to one of these 4 subtypes, widely used by the community and grown in a non-malignant brain organoid, I first downloaded these patient tumour datasets ([GSE119926](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE119926)) from GEO. Of these, I used a selection of 9 samples corresponding to the identifiers below (from the paper: https://doi.org/10.1038/s41586-019-1434-6). Each sample has a few hundred cells:
MUV41, SJ454, SJ577 (corresponding to subtype 1)
SJ516, BCH807 (subtype 2)
MUV11, SJ917 (subtype 3)
MUV19, MUV27 (subtype 4)

I first pre-processed my samples and the public datasets the same way. For a single sample, the code is shown below:
```
# load the raw counts data for 1 sample
raw.counts.muv41 <- read.table(file = "./hovestadt_Nature2019/GSM3905417_MUV41.txt",
                         sep = "")

# create the Seurat object. Use the Seurat min.gene default this time
muv41 <- CreateSeuratObject(raw.counts.muv41,
                            min.cells = 10,    # note 10 cells not 3
                            min.genes = 200,
                            project = "muv41")

# identify mitochondrial genes
mito.genes <- grep(pattern = "^MT", x = rownames(x = muv41), value = TRUE)
percent.mito <- 
  Matrix::colSums(muv41[mito.genes, ])/Matrix::colSums(muv41)

# add only the mitochondrial gene percent to the metadata
muv41 <- 
  AddMetaData(object = muv41, metadata = percent.mito, col.name = "percent.mito")

# remove ribosomal genes as I did this with my samples to make cell classification easier
muv41 <- muv41[ ! grepl('^RP[SL]', rownames(muv41)), ]

# remove mitochondrial genes - looks like authors already removed these??
muv41 <- muv41[ ! grepl("^MT-", rownames(muv41)), ]

# normalise the object, find Variable features (default for FindVariableFeatures is 'selection.method='vst')
muv41 <- NormalizeData(muv41)
muv41 <- FindVariableFeatures(muv41, nfeatures = 3000)

# get cell cycle scores, then regress this variable out
muv41 <- CellCycleScoring(muv41,
                          s.features = cc.genes$s.genes,
                          g2m.features = cc.genes$g2m.genes,
                          set.ident = TRUE)
muv41 <- ScaleData(muv41, vars.to.regress = c("S.Score", "G2M.Score"))

# run PCA and tSNE
muv41 <- RunPCA(muv41, npcs = 50)
muv41 <- RunTSNE(muv41, dims = 1:20)
```

On merging the datasets I found a strong batch effect, as expected. I then performed batch correction as follows:
```
seurat.list <- list(muv41, sj454, sj577, 
                    sj516, bch807, muv11, sj917, muv19, muv27)  # these are the different patient tumours, none of my samples
features <- SelectIntegrationFeatures(object.list = seurat.list)
allMB.anchors <- FindIntegrationAnchors(object.list = seurat.list, anchor.features = features)
allMB.combined <- IntegrateData(anchorset = allMB.anchors)

DefaultAssay(allMB.combined) <- "integrated"
allMB.combined <- ScaleData(allMB.combined, verbose = FALSE) %>% 
  RunPCA(npcs = 30, verbose = FALSE) %>% 
  RunTSNE(reduction = "pca", dims = 1:30) %>% 
  FindNeighbors(reduction = "pca", dims = 1:30) %>% 
  FindClusters(resolution = 1.0)

DimPlot(allMB.combined, group.by = "orig.ident", pt.size = 3) +
  theme(legend.text=element_text(size=20)) +
  labs(title = "")
```

The scatter plot shows the samples are well-blended together, without separate clustering of the patient samples by biological subtype.
<img width="1089" alt="Screenshot 2023-05-04 at 13 59 39" src="https://user-images.githubusercontent.com/63459892/236212143-0280bf88-a98d-4747-8eb0-3e21e601d2d7.png">

Is there something amiss with my code or analysis workflow? Or are samples becoming blended after integration for some other reason? I 'd be very grateful to know how to proceed. Many thanks.

**Comment by nathan-nakatsuka** [comment]
Dear @jjacob12 , the purpose of integration is to match cell types so the same cell types can be called and then differential expression can be done with matched cell types. Thus, the samples should be blended after integration if it is done properly, so this is fine.

**Comment by jjacob12** [comment]
Hi,
Thanks very much for responding. However, I am a little puzzled by this. Looking at  Stuart et al. Cell 2019 paper it states: "Methods that perform well in both metrics effectively match populations across datasets without blending distinct populations together". So, looking at for example, Figure 2A-H in the paper, we can see that biologically distinct islet cell subtypes remain nicely separated in the UMAP plot. In my case, the tumour subtypes are biologically distinct also, yet integration has blended all 4 subtypes together. This stands in contrast to the UMAP plots from Fig. 2 and does not seem right. The next step in my analysis was to integrate tumour cell types we have been using in the lab that are known to be much more closely related to tumour subtype 1 above. My prediction was that after integration I would see our lab tumour sample much closer in UMAP space to subtype 1 than to subtypes 2,3,4.  However, that was not the case and all samples were blended in a single large cluster more-or-less. Do I need to adjust some parameters  of the integration workflow so that I get something that looks a bit more like Fig. 2?

**Comment by nathan-nakatsuka** [comment]
try: 
SCTransform(allMB.combined, vst.flavor="v2)
RunPCA(allMB.combined, npcs=30)
RunUMAP(allMB.combined, reduction="pca", dims=1:30)
Then DimPlot

Might be you need SCTransform, or might be UMAP will be better than tSNE.

**Comment by jjacob12** [comment]
Thanks. Other Github posts by the Satija lab have recommended doing SCTransform on each sample separately, then doing the integration but I will give your suggestion a go first.

**Comment by nathan-nakatsuka** [comment]
Sorry actually yes we usually do SCTransform before integration, then PCA, UMAP, Dimplot. I just meant doing that instead of FindVariableFeatures and ScaleData since it can often yield sharper biological distinctions.

**Comment by jjacob12** [comment]
Ok, will feed back soon, many thanks.

**Comment by jjacob12** [comment]
I tried out fastMNN which did a much better job at keeping biologically distinct samples apart in the integration. There's already a Seurat wrapper for that which is handy.
