### ISSUE TITLE
Annotating Spatial Data with Updated Allen Atlas Taxonomy

### ISSUE THREAD

**Issue by ivingan01** [satijalab/seurat#7273]
Hello Seurat Community,

I am a novice coder, trying my best to understand the intricacies of analyzing data in seurat. I have a seemingly simple question with probably a very complicated answer. 

I have a spatial transcriptomic data set from coronal sections of mouse brain. These sections contain (amongst other things) the anatomical regions of the cortex and the hippocampus. In the seurat saptial tutorial (https://satijalab.org/seurat/articles/spatial_vignette.html) there is a section for integrating with single cell data to use the cell-type annotations from a single cell atlas as the annotations for spatial data set. The atlas used is cortex specific and from the allen institute in 2016.

In 2021, the allen institute published a more detailed cell type taxonomy which now contains the hippocampus as well as the cortex (https://portal.brain-map.org/atlases-and-data/rnaseq/mouse-whole-cortex-and-hippocampus-10x) (Yao Z,et al., A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation. Cell. 2021 Jun 10;184(12):3222-3241.e26. doi: 10.1016/j.cell.2021.04.021.).

My main biological questions involve the hippocampus and not the cortex alone, so I would like to use these updated data to annotate my spatial data set in the same way as instructed in the tutorial. These data are not neatly packaged into a .RDS file like the allen_cortex.rds file used in the seurat tutorial. 

What would I need to do with the files listed on their web portal to get to the point of integrating these data with my data set for the purpose of annotation? Am I missing something and making things more complicated than they need to be? Is there another file listed here that I can use for annotations without having to personally load an analyze a 68 gb gene expression matrix?

Thank you

**Comment by AustinHartman** [comment]
It looks like the data provided here is all within a single HDF5 file. I'd recommend loading this file into memory and then selecting particular hippocampus or cortex samples from the file to use for integration. You can split each sample into it's own seurat object and integrate as described here: [integration_large_datasets](https://satijalab.org/seurat/articles/integration_large_datasets.html)

You should be able to load the hdf5 file with something like this:
```r
library(hdf5r)
Read_h5_modified <- function(filename) {
  infile <- hdf5r::H5File$new(filename = filename, mode = 'r')
  counts <- infile[['data']][['counts']][ , ]
  genes <- infile[["data"]][["gene"]][]
  samples <- infile[["data"]][['samples']][]
  colnames(counts) <- genes
  rownames(counts) <- samples
  return(counts)
}
counts <- Read_h5_modified("expression_matrix_10x.hdf5")
```
