### ISSUE TITLE
How to add loom assays to Seurat object: Error in UseMethod(generic = "as.sparse", object = x) :    no applicable method for 'as.sparse' applied to an object of class "Assay"?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#7276]
Hi there, 

I had loom objects for different samples generated by `velocyto`, and a Seurat object that had been fully analysed (with SCTransform clustering and UMAP etc). 

I was able to concatenate my loom objects into 1 object and converted it to Seurat object, but this object has not been in anyway processed (e.g., normalise etc that are typically done in scVelo pipeline). 

**How might I add the ambiguous, matrix, spliced, unspliced to my Seurat GEX cluster object? Do I do as below?**

```
test[["ambiguous"]] <- CreateAssayObject(counts = concat_adata_Seurat@assays$ambiguous)
test[["matrix"]] <- CreateAssayObject(counts = concat_adata_Seurat@assays$matrix)
test[["spliced"]] <- CreateAssayObject(counts = concat_adata_Seurat@assays$splice)

```

Doing this gave me error however "Error in UseMethod(generic = "as.sparse", object = x) : no applicable method for 'as.sparse' applied to an object of class "Assay""

Thank you for your help!

**My Seurat GEX cluster object:**
<img width="442" alt="Screenshot 2023-05-04 at 18 55 55" src="https://user-images.githubusercontent.com/62179082/236288722-7b625b17-6ded-4f55-ac0a-ab0b9426197e.png">

**My loom-converted Seurat object:** 
<img width="468" alt="Screenshot 2023-05-04 at 18 56 04" src="https://user-images.githubusercontent.com/62179082/236288758-83e34992-9073-4901-8a90-02ba40d6f38b.png">

Posted https://github.com/zhanghao-njmu/SCP/issues/130

**Comment by AustinHartman** [comment]
It looks like you are providing full Assays to CreateAssayObject via the counts parameter. You should be able to edit your code to either of the following:
```r
test[["ambiguous"]] <- concat_adata_Seurat@assays$ambiguous

test[["ambiguous"]] <- CreateAssayObject(counts = concat_adata_Seurat@assays$ambiguous@counts)
```
