### ISSUE TITLE
Volcano plot

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7277]
Hi
I am new to bioinformatics.
I have analyzed my data with seurat and successfully presented.I am trying to make Volcano plots of Differentially expressed genes in certain clusters.For that i saved the excel files with gene names, average log2FC and adjusted p value.After wards i transforemed this file into csv file named "res". This file has 3 variables avgLog2FC, adj.p.val and gene names.
I read this file and try to create volcano plot but i am having an issue it might be unrelated here but if some one can help me how to sort this out?Like how to make gene, avfLog2fc and p.val.adj to be read so plot can be made?
code is ;when i read res file its structure is
 > res
             gene avgLog2FC     p.val.adj
1            Igkc 2.9106251  2.740000e-17
2           Crip1 1.8832284 2.730000e-118
3            Ly6d 1.8370875  1.490000e-38

> EnhancedVolcano(res,x= avgLog2F
![Screen Shot 2023-05-04 at 3 18 48 PM](https://user-images.githubusercontent.com/96392364/236306819-9e7e9e5c-7191-47c3-8e60-b2c81858206b.png)
C, y= p.val.adj,lab=gene)
Error in (function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x,  : 
  object 'avgLog2FC' not found

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I would suggest posting this in general bioinformatics forum (Biostars) or on the EnhancedVolcano repo/BioConductor help forum as this is issue with that package and not with the Seurat package.

Best,
Sam
