### ISSUE TITLE
no features.tsv or genes.tsv output

### ISSUE THREAD

**Issue by priscilla-glenn** [satijalab/seurat#7278]
Hi, 
I recently ran cellranger-atac on my single cell fastq files and received the three output files in outs/filtered_peak_bc_matrix

barcodes.tsv
matrix.mtx
peaks.bed

There is no features.tsv file so when I tried to run 'atac_obj <- Read10X(data.dir = cellranger_path)' it didn't work and requested the features.tsv or genes.tsv file. Is there a way in which I can use the peaks.bed file? Do I need to convert it to the features.tsv file? Or is my output just missing the required file?

Thanks.

**Comment by AustinHartman** [comment]
I'd recommend `counts <- Read10X_h5(filename = "../vignette_data/atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5")`. The h5 file contains the same information as the three files you listed.
