### ISSUE TITLE
Cell cycle scoring aproach

### ISSUE THREAD

**Issue by Xcubitor** [satijalab/seurat#728]
Hello,

I was wondering how the cell cycle scoring command operates. Meaning, that are the steps that are undertaken in order to come up with the scores for each cell?

thanks :-)

**Comment by orrzor** [comment]
take a look here....
https://satijalab.org/seurat/cell_cycle_vignette.html#assign-cell-cycle-scores

**Comment by Xcubitor** [comment]
Thanks orrzor :-) I did but the vignette doesn't really explain how the data from the gene sets is pulled together and how the scores are computed.

**Comment by satijalab** [comment]
As we say in the vignette, the scores are computed using an algorithm developed by Itay Tirosh, when he was a postdoc in the Regev Lab (Science et al., 2016). The gene sets are also taken from his work.

You can read the methods section of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4944528/ to see how the scoring works, but essentially- the method scores cells based on the expression of each gene in a signature set - after controlling for the expected expression of genes with similar abundance.

**Comment by ChelseaCHENX** [comment]
Does the Seurat object need to be normalized and scaled before applying cell cycle scoring? If not, would this function automatically do normalization/scaling?
