### ISSUE TITLE
Seurat5 enable mamba/micromamba IntegrateLayers

### ISSUE THREAD

**Issue by WesDe** [satijalab/seurat#7280]
Hi,

Thank you again for this amazing Seurat5 which looks promising ! I would like to know if it will possible to extend conda_env require argument to use IntegratedLayer function for SCVI to other environment such as mamba/micromamba ?

Best,

**Comment by yuhanH** [comment]
Hi, 
You can find the source of SCVI integration in `SeuratWrappers::scVIIntegration()`. Then you make a new function with the modification of reticulate python environment settings. Then, using your modified function in the `IntegrateLayers`
