### ISSUE TITLE
Visium: annotation from atlas data

### ISSUE THREAD

**Issue by Umaarasu** [satijalab/seurat#7282]
Hi,

I would like to process an atlas data, so that I could use the annotation to label my cell cluster from visium spatial transcirptomics. My issue is that the data provided in the atlas paper are in ".Robj" format and for some reason after I load() the data, I am not able to process it as per the example you have provided. Below is my error. Has anyone else had this issue?

>load("facs_Lung_seurat_tiss.Robj")
> View(tissue)
> tissue
An old seurat object
 16496 genes across 1620 samples
>UpdateSeuratObject(tissue)
An object of class Seurat 
16496 features across 1620 samples within 1 assay 
Active assay: RNA (16496 features, 366 variable features)
 2 dimensional reductions calculated: pca, tsne
> x <- SCTransform(tissue, ncells = 3000, verbose = FALSE) %>%
+   RunPCA(verbose = FALSE) %>%
+   RunUMAP(dims = 1:30)
**Error in UseMethod(generic = "GetAssay", object = object) : 
  no applicable method for 'GetAssay' applied to an object of class "seurat"**

**Comment by AustinHartman** [comment]
It looks like you call `UpdateSeuratObject` without updating `tissue` with the results. Try modifying the update line with `tissue <- UpdateSeuratObject(tissue)`

**Comment by Umaarasu** [comment]
> It looks like you call `UpdateSeuratObject` without updating `tissue` with the results. Try modifying the update line with `tissue <- UpdateSeuratObject(tissue)`

Thanks!
