### ISSUE TITLE
QC in Sketch-based analysis workflow

### ISSUE THREAD

**Issue by ttumkaya** [satijalab/seurat#7284]
Hi Seurat Team,

Thank you for providing the community with such a great tool.

I am testing the sketch-based workflow on a fairly large dataset and was wondering if there're any recommendations for how/when in the workflow to integrate the QC steps? Applying QC to only sketched data and projecting back on to the full dataset doesn't seem like the right way to go about it but the size of the full dataset makes QC hard as well, just wondering if there's a workaround you would suggest? Couldn't find an example in the vignettes.

Thank you,
Tayfun

**Comment by nathan-nakatsuka** [comment]
Hi @ttumkaya , we suggest you do QC prior to sketching. When the Seurat object is being created, it produces the QC metrics (nCount_RNA, etc.), so you should do it immediately when the Seurat object is created.
