### ISSUE TITLE
saveRDS error

### ISSUE THREAD

**Issue by realzehuali** [satijalab/seurat#7285]
> g = readRDS("BPCells/obj_raw.Rds")  #### saved by version 4.9.9.9040 now upgrading to 4.9.9.9044
> saveRDS(object = g, file = "obj_raw2.Rds", destdir = "BPCells")
Error in slot(object = object, name = "layers")[[layer]][features, cells,  : 
  no slot of name "zero_dims" for this object of class "MatrixSubset"

**Comment by realzehuali** [comment]
A Seurat5 object just read from RDS can not be saved by saveRDS

**Comment by Gesmira** [comment]
Hi, are you able to save the object if you don't specify the `destdir` parameter?

**Comment by realzehuali** [comment]
I have to re-run the pipeline with 4.9.9.9044 to save my previous RDS.
I found this might be due to the lack of slot zero_dims in counts layer created by 4.9.9.9040.

**Comment by Gesmira** [comment]
Considering it works correctly now, I will close this issue. Please feel free to reopen if not.
