### ISSUE TITLE
Removing Duplicate Cells

### ISSUE THREAD

**Issue by henrymamir** [satijalab/seurat#729]
I'm very new to R and Seurat. I've done analysis on two subsets of a 10X data set focusing on a specific gene for each subset, and there are shared cells between the two subsets. I was wondering if there was some way to merge these subsets, even though they share some cells. Thank you!

**Comment by satijalab** [comment]
Check out the arguments for MergeSeurat, which allows you to add a prefix to the Cell ID (for example, 'replicate1_", or "replicate2_", to get around this problem

**Comment by henrymamir** [comment]
Is there any way to "overwrite" these cells, or filter out the duplicates?
