### ISSUE TITLE
SpatialDimPlot for select slides

### ISSUE THREAD

**Issue by gucascau** [satijalab/seurat#7290]
I integrated ~10 slides firstly but would like to show only 2-4 slides for the SpatialDimPlot. Is there an easy way to show them?

I used the Dimplot it is working very well, but not SpatialDimPlot. SpatialDimPlot showed all of the slides but still retained the empty figures for slides that are not subsets.

>  FinalClustersObjsubset <-subset(FinalClustersObj, subset= (orig.ident == "PyeloD0_1" |orig.ident == "PyeloD1_1"|orig.ident == "PyeloD3_1"))

 > SpatialDimPlot(FinalClustersObjsubset,crop=TRUE)

Any suggestion? Thanks

**Comment by AustinHartman** [comment]
Use the `images` parameter in `SpatialDimPlot` to only show select slides/images
