### ISSUE TITLE
Significant discrepancy between the sets of differentially expressed genes obtained from RNA data slot and SCT v2 data slot

### ISSUE THREAD

**Issue by haoyanioz** [satijalab/seurat#7292]
Dear developers and users,

In my dataset, I have observed significant inconsistencies in the sets of differentially expressed genes obtained from RNA data slot and SCT v2 data slot using Seurat 4.1.2. Have you encountered a similar scenario previously? What are the underlying causes and potential strategies for addressing this issue?

Best,
Star

**Comment by saketkc** [comment]
Can you paste your code here? If you switch to RNA assay for running DE, make sure you are running `NormalizeData` before running `FindMarkers`

**Comment by haoyanioz** [comment]
> 

Thank you for your reply. My main codes are shown as follows: 
    
> dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'data'))
[1]   3000 202328
> dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'scale.data'))
[1]   3000 202328
> dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'counts'))
[1] 0 0
> dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'counts'))
[1]  14663 202328
> dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'scale.data'))
[1]  14663 202328
> dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'data'))
[1]  14663 202328
> dim(GetAssayData(object = seurat_integrated@assays$SCT, slot = 'data'))
[1]  14663 202328

    DefaultAssay(seurat_integrated) <- "SCT"
    seurat_integrated <- PrepSCTFindMarkers(seurat_integrated)
    seurat_integrated.markers1 <- FindMarkers(seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = i,logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data", recorrect_umi = FALSE)

   DefaultAssay(seurat_integrated) <- "RNA"
   seurat_integrated.markers2 <- FindMarkers( seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = i,logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data")


Thanks again.

Best,
Star

**Comment by haoyanioz** [comment]
> Can you paste your code here? If you switch to RNA assay for running DE, make sure you are running `NormalizeData` before running `FindMarkers`

Thank you for your reply. My main codes are shown as follows:

dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'data'))
[1] 3000 202328
dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'scale.data'))
[1] 3000 202328
dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'counts'))
[1] 0 0
dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'counts'))
[1] 14663 202328
dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'scale.data'))
[1] 14663 202328
dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'data'))
[1] 14663 202328
dim(GetAssayData(object = seurat_integrated@assays$SCT, slot = 'data'))
[1] 14663 202328

DefaultAssay(seurat_integrated) <- "SCT"
seurat_integrated <- PrepSCTFindMarkers(seurat_integrated)
seurat_integrated.markers1 <- FindMarkers(seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = i,logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data", recorrect_umi = FALSE)
DefaultAssay(seurat_integrated) <- "RNA"
seurat_integrated.markers2 <- FindMarkers( seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = i,logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data")

Thanks again.

Best,
Star

**Comment by saketkc** [comment]
You need to normalize RNA data before running findmarkers:
```r
DefaultAssay(seurat_integrated) <- "RNA"
seurat_integrated <- NormalizeData(seurat_integrated)
seurat_integrated.markers2 <- FindMarkers( seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = 1, logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data")

```

**Comment by haoyanioz** [comment]
> You need to normalize RNA data before running findmarkers:
> 
> ```r
> DefaultAssay(seurat_integrated) <- "RNA"
> seurat_integrated <- NormalizeData(seurat_integrated)
> seurat_integrated.markers2 <- FindMarkers( seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = 1, logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data")
> ```


Thank you for your response.

I have normalized RNA data after integrating several samples from different groups. Should I perform normalization again? Apologies for my confusion.

seurat_integrated <- NormalizeData(seurat_integrated, verbose = FALSE, normalization.method = "LogNormalize", scale.factor = 10000)
all.genes <- rownames(x = seurat_integrated)
seurat_integrated <- ScaleData(object = seurat_integrated, features = all.genes)

dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'data'))
[1] 3000 202328
dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'scale.data'))
[1] 3000 202328
dim(GetAssayData(object = seurat_integrated@assays$integrated, slot = 'counts'))
[1] 0 0
dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'counts'))
[1] 14663 202328
dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'scale.data'))
[1] 14663 202328
dim(GetAssayData(object = seurat_integrated@assays$RNA, slot = 'data'))
[1] 14663 202328
dim(GetAssayData(object = seurat_integrated@assays$SCT, slot = 'data'))
[1] 14663 202328

DefaultAssay(seurat_integrated) <- "SCT"
seurat_integrated <- PrepSCTFindMarkers(seurat_integrated)
seurat_integrated.markers1 <- FindMarkers(seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = 1, logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data", recorrect_umi = FALSE)
DefaultAssay(seurat_integrated) <- "RNA"
seurat_integrated.markers2 <- FindMarkers( seurat_integrated, ident.1 = "stim", group.by = 'group', subset.ident = 1, logfc.threshold = 0.25, test.use = "wilcox", min.pct = 0.1, slot = "data")

Thanks again.

Best,
Star

**Comment by saketkc** [comment]
Can you elaborate on what is the discrepancy?
