### ISSUE TITLE
ScaleData for all genes in v5

### ISSUE THREAD

**Issue by aCompanionUnobtrusive** [satijalab/seurat#7293]
Hello,

I am wondering how to use the ScaleData() function to scale all genes in Seurat version 5, and not just variable features.

In earlier seurat versions, I would run this:
```
obj <- ScaleData(obj,features = rownames(obj))
```

but now when I do this in version 5, I get the following error:

```
Error: In function min_by_row: "vals" must be greater than zero
    ▆
 1. ├─Seurat::ScaleData(obj, features = rownames(obj))
 2. └─Seurat:::ScaleData.Seurat(obj, features = rownames(obj))
 3.   ├─Seurat::ScaleData(...)
 4.   └─Seurat:::ScaleData.StdAssay(...)
 5.     ├─Seurat::ScaleData(...)
 6.     └─Seurat:::ScaleData.IterableMatrix(...)
 7.       └─BPCells::min_by_row(...)
 8.         └─BPCells:::assert_greater_than_zero(vals)
```

For additional info, I'm using seurat version '4.9.9.9042'

Thanks! :)

**Comment by yuhanH** [comment]
hi @aCompanionUnobtrusive 
This bug is fixed in the latest seruat 5, version `4.9.9.9045`
