### ISSUE TITLE
PrepSCTFindMarkers for CellChat

### ISSUE THREAD

**Issue by me-orlov** [satijalab/seurat#7296]
Hello everyone,

I am wondering whether anyone here has used CellChat with Seurat objects? If so, would it be appropriate to run PrepSCTFindMarkers on my merged object with multiple SCT models prior to use in CellChat? The input to CellChat needs to be a normalized matrix, so I figured re-correcting for differences in sequencing depth between the samples would make sense here? Sorry for the newbie question! I am asking the CellChat developers about it as well. 

Thank you for your time.

**Comment by saketkc** [comment]
Yes, I would recommend running `PrepSCTFindMarkers` before any analysis that requires normalized data (this step here ensures that the corrected counts are calculated using the same sequencing depth for all datasets).
