### ISSUE TITLE
RegressOut cell cycle effects

### ISSUE THREAD

**Issue by amisharin** [satijalab/seurat#73]
Hello Seurat team, 
I would like to filter out the effects of cell cycle, but I could not find variable to be used with RegressOut. If I understand correctly, instead of genes.regress=NULL, I should provide a list of cell cycle genes, is this correct? Are there any validated lists of cell cycle genes for both mouse and human that can be used with Seurat? 

RegressOut(object, latent.vars, genes.regress = NULL, model.use = "linear",
  use.umi = F, do.scale = T, do.center = T, scale.max = 10)

Thank you in advance
Alexander

**Comment by andrewwbutler** [comment]
Hi Alexander,

You can check the [Macosko et al. 2015](https://www.ncbi.nlm.nih.gov/pubmed/26000488) paper for gene sets. To run the regression, you don't set `genes.regress` to your list of cell cycle genes. You have to essentially calculate a cell cycle score for each cell by either 

1.  following similar methodology to the above paper 
2. Run a PCA but ONLY using cell cycle genes. Typically PC1 will correspond to cell cycle phase, essentially representing a cell cycle score.

You would then provide this score in `latent.vars` to RegressOut.
