### ISSUE TITLE
Visualizing Tsne in each iteration.

### ISSUE THREAD

**Issue by tiagobrc** [satijalab/seurat#730]
Hi, thanks for Seurat!

I was looking at a page https://distill.pub/2016/misread-tsne/, which I found very interesting to see the evolution of each iteration in real time. I started to think how and what would I need to do to visualize Seurat Tsne function like that. Do anyone have any ideas?

**Comment by satijalab** [comment]
You can set the max.iter in the RunTSNE function - which will only run tSNE for a certain number of iterations. You can use this to build up screenshots for a movie.

Evan Macosko actually did this for the original Drop-seq paper. It takes quite a while to generate, but you can view the results here:
https://www.dropbox.com/s/lb15zv223bbyes0/tsplot_new.mp4?dl=0
