### ISSUE TITLE
Loading UMI counts to seurat

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#7300]
Hello. Anyone can please help?

I downloaded scRNA-seq data from **https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146285** but the files are not the standard genes/features, barcodes, matrix files. For example, the file is "GSM4376680_Sham_1day_plate1_UMIcount.tsv"--it's UMI counts? (Additionally, there's an additional file called "GSE146285_barcodes_used.txt.gz" in this public data).

There doesn't seem a complete Seurat tutorial for loading all kinds of single-cell data types (if I am not mistaken), so I'm stuck here too. Does anyone know how to load this data type in seurat please? Thank you!

**Comment by Gesmira** [comment]
Hi, 
The input to a Seurat object should be a cell x gene matrix. If the file you included is of that format, you can load it in and give it as input to `CreateSeuratObject()`. Depending on what the other file represents, you could use those barcodes to filter your data if you only want those cells.
