### ISSUE TITLE
SCTransform Error in make_cell_attr()

### ISSUE THREAD

**Issue by moi-taiga** [satijalab/seurat#7302]
I am using data from [A Single-Cell Tumor Immune Atlas for Precision Oncology](https://zenodo.org/record/5205544)
When runnning SCTransform I get the following error:

```r
object <- readRDS("~/TICAtlas_downsampled.rds")

library(Seurat)
library(sctransform)
object <- SCTransform(object, verbose = FALSE)
```

*Error in make_cell_attr(umi, cell_attr, latent_var, batch_var, latent_var_nonreg,  : 
  cell attribute row names must match column names of count matrix*

**Comment by saketkc** [comment]
Thanks for the suggestion! I have been meaning to change that line for a while. I will make a change in the next release of sctransform.
