### ISSUE TITLE
Seurat v5 docker image

### ISSUE THREAD

**Issue by sidwekhande** [satijalab/seurat#7303]
Hi team,

I was wondering if you could provide a public docker image with Seurat v5 (and other packages mentioned in the v5 vignette) installed. Please let me know if one already exists, I could not find one under https://hub.docker.com/r/satijalab/seurat. 

Thanks!

**Comment by evchambers** [comment]
In the meantime, if anyone is interested I have created a singularity def file which should create a singularity image that runs Seurat v5. [Link](https://github.com/evchambers/singularity_containers/tree/main/Seurat_v5)

**Comment by Gesmira** [comment]
Thanks for your patience! There is now a docker image for Seurat v5. The image tag is `satijalab/seurat:5.0.0`. Seurat v5 is also now officially on CRAN so can be easily installed with `install.packages("Seurat")`.

**Comment by lvclark** [comment]
I am getting permission denied errors when trying to pull it, although I can pull other public images.
