### ISSUE TITLE
Bridge Integration Clarification 

### ISSUE THREAD

**Issue by clee700** [satijalab/seurat#7304]
Hello, I hope you are having a good day. I have some questions about the Seurat V5 pipeline. 
I am using the tutorial https://satijalab.org/seurat/articles/seurat5_integration_bridge.html and have successfully ran the vignette. 
My questions: 
1. Where is the harmonized dictionary representation stored? (Using the notation from the Supplementary Methods of the paper, I am looking for matrix L) I have checked the obj.atac assay for ATAC for counts and data, and it is the same as the obj.atac object created without bridge integration. Similarly, where is the harmonized dictionary representation for the obj.rna? Is it in obj.rna.ext?  
2. Is there a way to get the obj.atac and obj.rna items in the same object? Analogous to Seurat V3, I am looking for IntegrateData instead of TransferData. 
3. Does Seurat V5 do imputation of the predicted modality? It seems possible that using the dictionary representation, we would reconstruct the missing modality but I am not sure that is in the design. 
Thank you!

**Comment by ShanshanHe7** [comment]
Hi, I also tried to use bridge integration these days and I also have the same question.
In my `obj.rna.ext` object,  `RNA` and `SCT` assay contain the integrated data both from `obj.rna` and `obj.multi`, `ATAC` assay contain the ATAC data from `obj.multi`. And I think the `Bridge` assay is the harmonized reduced dictionary representation for scRNA data(Lx), but I also don't know where they stored L_y and L. I guess the reduction `lap` is L and `ref.pca` is the mapped `obj.multi` to RNA pca  UMAP. 
> obj.rna.ext
An object of class Seurat 
283256 features across 34248 samples within 4 assays 
Active assay: SCT (32932 features, 0 variable features)
 3 layers present: counts, data, scale.data
 3 other assays present: RNA, Bridge, ATAC
 14 dimensional reductions calculated: pca.1, umap, tsne, harmony, umap.atac, pca.2, umap.rna, lsi, harmony_pca, harmony_lsi, umap.wnn, ref.pca, lap, slsi

**Comment by yuhanH** [comment]
hi @ShanshanHe7  Thank you for your reply. That's right. Bridge assay, Bridge.reduc or ref.Bridge.reduc are the dictionary representations. 
for question 2, you can use `FindBridgeIntegrationAnchors` and `IntegrateEmbeddings` to get the merged object with dictionary representation for both query and reference. 
for question 3, in `MapQuery`, you can impute expression value from Reference to Query just like before
```
MapQuery(...
refdata = list(
predicted_ADT = "ADT"
)
)
```
