### ISSUE TITLE
About calculate p value

### ISSUE THREAD

**Issue by DM0815** [satijalab/seurat#7309]
Excuseme, I have a question. I have a seurat object, and take a cluster'B' out. In cluster B subsnet, There are two conditions(disease and healthy). I want to calculate p value (p_adj, and so on) of all genes, when I use findmaker or find allmarker function, it just give me some DEGS, But I want to get all genes in two conditions comparison. Can you give me some hints? Thanks.

**Comment by AustinHartman** [comment]
By default, `FindMarkers` will only consider genes which a log fold change and expression threshold. If you set those parameters to 0, p-values will be calculated for all genes but please not this will take longer to run.
```r
obj <- FindMarkers(obj, logfc.threshold=0, min.pct=0)
```

**Comment by DM0815** [comment]
> 

Got it. Thanks!
