### ISSUE TITLE
Robustness of Seurat's clusters

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#731]
Hello Seurat Team,

I would like to know what's the best way to check the robustness of Seurat's clusters?  Is there any function that would test that (apart from the ValidateClusters function that I'm aware of)?  I know one can randomly downsample the cells many times and see if the same clusters appear repeatedly, as one way of checking for cluster robustness.  Is there a function for doing this?   Any other suggestions?

Would really appreciate any responses.

Thanks a lot!

**Comment by andrewwbutler** [comment]
Hi,

We don't have any specific functions for downsampling to test clustering robustness but you could look into `SubsetData` or `SampleUMI` if you would like to build something like that.
