### ISSUE TITLE
Combining Multiple Already Integrated Seurat Objects

### ISSUE THREAD

**Issue by almm2020** [satijalab/seurat#7312]
I previously posted this in the discussion section but never got any responses, so I'm going to try my luck here.

I have two integrated Seurat objects. The first has 2 individual samples and the second has 8. I don't have the original files or barcodes for the first set but I do for the second. I'm not sure how to go about combining these two datasets. The metadata for the two integrated objects is different, but when I combine the objects I would like to try to keep at least the metadata from the second object. I should also mention that I'm really interested in combining them to use for pseudotime and that for the rest of the analysis, I'm not using the first set.

I'm under the assumption that I need to extract each sample information from the two objects and then integrate them.

 Can someone explain the difference between splitting an object into two individual objects or using SubsetData to subset each individual sample into an individual object? When I attempted to split the second object I run into my RStudio crashing even when using a large amount of memory.

Any advice is greatly appreciated.

edit: When I integrate the individual samples since they already have metadata, do I need to make sure that there are the same columns for all samples? Do I have to normalize the data again?

**Comment by mhkowalski** [comment]
Hi, 

Merging Seurat objects should also merge the metadata. If any columns are present in one object but not another, this column will be preserved but will be populated with NAs for the cells from the object where that column is not present. (see [merging vignette](https://satijalab.org/seurat/articles/merge_vignette.html)). 

Yes, you should split the objects and integrate them using the original RNA expression (not the integrated assay) see [here](https://satijalab.org/seurat/articles/integration_introduction.html).

**Comment by almm2020** [comment]
Since both objects have already been normalized as individual objects when combined do I need to normalize them again before integrating?
