### ISSUE TITLE
Should I stick with SCT assay and use PrepSCTFindMarkers() after integrating multiple SCTransformed objects via Harmony

### ISSUE THREAD

**Issue by Angel-Wei** [satijalab/seurat#7313]
Hi, thank you for the amazing tool to analyze scRNA-seq data. I'm working on integrating Seurat objects from two conditions but all at the same time point together. I have 3 objects: control1, treat1, treat2; the objects of the treated group were processed individually using SCTransform. Here's my current pipeline which probably works the best if I just check how clusters overlap on the UMAP when I group by either the treatment or the object:

```
myList <- list(control1, treat1, treat2)

features <- SelectIntegrationFeatures(object.list = myList, nfeatures = 3000)
merged_seurat <- merge(x = myList[[1]],
                       y = myList[2:length(myList)],
                       add.cell.ids = c("control1", "treat1", "treat2"),
                       merge.data = T)
VariableFeatures(merged_seurat) <- features

merged_seurat <- merged_seurat %>%
  #SCTransform(vars.to.regress = c("nCount_RNA", "nFeature_RNA", "percent.mt")) %>%
  RunPCA() %>%
  RunTSNE()
```
**Question 1: I was debating on whether to comment-out and run SCTransfrom() again on the merged matrix before I RunPCA()**. I think this is not required for Seurat's own integration method and it's also mentioned in #1836, for example, the pipeline by nicodemus88. However, I'm using harmony which seems to better integrating data in our own case. Although re-run SCTransfrom on merged matrix wasn't brought up in a vignette I followed [https://hbctraining.github.io/scRNA-seq_online/lessons/06a_integration_harmony.html](url) (I used the pipeline described in the second scenario). But I also see posts by the harmony group that re-run SCTransform on merged dataset is also recommended [https://github.com/immunogenomics/harmony/issues/41](url). I tried both cases including (only 1 SCT model) and leaving this step (3 SCT models, representing SCT-normalized values for each object prior integration). It seems that leaving this step and proceed with harmony() was slightly better. But I'd like to hear any suggestions.

Here's my pipeline for harmony
```
harmonized_seurat <- RunHarmony(merged_seurat, 
                                group.by.vars = selected.group.by.vars, 
                                reduction = "pca", assay.use = "SCT", reduction.save = "harmony",
                                project.dim = F)

harmonized_seurat <- harmonized_seurat %>%
  RunUMAP(reduction = "harmony", assay = "SCT", dims = 1:30) %>%
  FindNeighbors(reduction = "harmony", dims=1:30) %>%
  FindClusters(resolution=0.8)
```

**Question 2: I need to perform marker identifications after integration via harmony. I wonder which options I should go with when I call `FindAllMarkers()`**:
option 1:
```
harmonized_seurat <- PrepSCTFindMarkers(object = harmonized_seurat, verbose = TRUE) # prepares object to run differential expression on SCT assay with multiple models
harmonized_seurat.markers <- FindAllMarkers(harmonized_seurat, only.pos = T)
```
option 2: I also see posts recommending switching back to the RNA assay for feature plots and marker identification, like mentioned in #4032 and #2023. So I still ran this before I even reached harmony:
```
merged_seurat <- merged_seurat %>%
  NormalizeData() %>%
  ScaleData(vars.to.regress=c("nCount_RNA", "nFeature_RNA", "percent.mt"))
```
and when I call `FindAllMarkers()`, I specified the assay to be `RNA`:
`harmonized_seurat.markers <- FindAllMarkers(harmonized_seurat, assay = "RNA", only.pos = T)`

Love to hear any insights on these two questions. Thank you so much for the help!

**Comment by saketkc** [comment]
Based on your analysis if you are happy with harmony's integration you should stick to it (and need not run SCT again). `PrepSCTFindMarkers` is required in the case where you run SCTransform on individual objects and want to use the corrected data (data slot of SCT assay) for DE analysis. I would recommend using the SCT assay for DE testing here.

**Comment by Angel-Wei** [comment]
Hi Saket, thank you so much for your quick reply! This is informational!

**Comment by yinshiyi** [comment]
`#SCTransform(vars.to.regress = c("nCount_RNA", "nFeature_RNA", "percent.mt"))`
this part could be reviewed, i think scaleData need to write out nCount_RNA, but the negative binomial regression in sct take cares of the ncount_RNA already.
