### ISSUE TITLE
how to save PCA results to data frame for printing to .tsv file?

### ISSUE THREAD

**Issue by stevekm** [satijalab/seurat#7314]
I have a Seurat object in R from a completed analysis. I want to save the PCA table to a file in .csv or .tsv format. How can I do this?

It seems that despite giving the appearance of a dataframe, the `pca` attribute is infact not a dataframe;

```
> class(obj$pca)
[1] "DimReduc"
attr(,"package")
[1] "SeuratObject"
```

as such, you cannot write it to a file with the normal methods;

```
> write.table(x = obj$pca, file = "pca.tsv")
Error in as.data.frame.default(x[[i]], optional = TRUE) :
  cannot coerce class 'structure("DimReduc", package = "SeuratObject")' to a **data.frame**
```

What is the best way to go about handling this? For what its worth, I also wanted to do a few misc. dataframe tasks with the object first as well before saving it to file, namely add the rownames as a separate "ID" column to make printing cleaner in the file. 

In an effort to print the file, I even tried to first pull off the values from the PCA object into a real dataframe first, however that did not work either.

```
> ncol(refobj$pca)
[1] 10
> nrow(refobj$pca)
[1] 2581
> colnames(refobj$pca)
 [1] "PC_1"  "PC_2"  "PC_3"  "PC_4"  "PC_5"  "PC_6"  "PC_7"  "PC_8"  "PC_9"
[10] "PC_10"
> refobj$pca[["PC_1"]]
Error in embeddings[i, j, drop = drop, ...] : subscript out of bounds

> as.data.frame.matrix(refobj$pca)
...
Warning message:
In format.data.frame(if (omit) x[seq_len(n0), , drop = FALSE] else x,  :
  corrupt data frame: columns will be truncated or padded with NAs
```

It seems you cannot even natively convert the object into a dataframe, or extract values properly using standard dataframe value access methods. 

Please advise on how to correctly handle this, thanks

**Comment by Jiayi-Zheng** [comment]
`pca <- as.data.frame(Embeddings(object = seu[["pca"]]))`

Try this?
