### ISSUE TITLE
How can I convert a matrix like in GSE126030 to a seurat object?

### ISSUE THREAD

**Issue by Matias0101012** [satijalab/seurat#7315]
The file I can download from repository GSE126030 is GSE126030_RAW.tar. Inside there are all the different samples in an extention matrix.txt.gz. Each of this files contain a matrix where the first and second column corresponds to the Feature file needed when using the function [Read10X]. The barcodes are in the first line and the rest is the count matrix.
When I try to create a seurat object using this matrix file I get N/A columns.
What is the best/easy way to create a seurat object from this data?

**Comment by saketkc** [comment]
You can read the data something like this (but please verify if the cell numbers make sense with the original publication)
```r
z <- read.delim("GSM3589407_PP002swap.filtered.matrix.txt.gz", sep="\t")
# assign rown names as gene names
rownames(z) <- make.unique(z[,2])
# remove gene id/name columns
z[,1] <- NULL
z[,2]  <- NULL
z[, "X"] <- NULL # not sure what this is
```

`z` is then your counts matrix.

**Comment by vandontduong** [comment]
I tried these steps, but ran into an error when creating the Seurat object. Do you have any advice on how to resolve this issue? 

```
> obj_1 <- CreateSeuratObject(counts = count_matrix_1, min.cells = 3, min.features = 200)
Counts matrix provided is not sparse. Creating V5 assay in Seurat Object.
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric
```

I tried converting the count matrices by following [this approach](https://stackoverflow.com/questions/10555210/r-convert-matrix-or-data-frame-to-sparsematrix), but it doesn't seem to work for some reason.

```
library(Matrix)
> count_matrix_1_sparse <- as(count_matrix_1, "sparseMatrix")
Error in .m2sparse.checking(from, ".", "C") : 
  matrix of invalid type "character" to .m2sparse.checking()
> count_matrix_1_sparse <- Matrix(count_matrix_1, sparse = TRUE)
Error in Matrix(count_matrix_1, sparse = TRUE) : invalid 'data'
```
