### ISSUE TITLE
Cyclic IF Feature Analysis

### ISSUE THREAD

**Issue by bbraun923** [satijalab/seurat#7317]
We are using Seurat's new spatial toolkit to analyze cyclic IF data from tissue based on features extracted from Cell Profiler, it is working very well. Any reason there would be problems adding additional columns based on other texture/granularity features of the stains beyond intensity?

**Comment by AustinHartman** [comment]
You can certainly add additional cell information to the metadata slot of the Seurat object or as an assay containing IF-derived cellular features. Hope that answers your question!
