### ISSUE TITLE
k.weight parameter not accepted

### ISSUE THREAD

**Issue by clee700** [satijalab/seurat#7321]
Hello, I was trying to change the k.weight to see how it would affect the results. I am running into this error; what is the correct specification for k.weight? 
Thank you!

```r
RNA.ext <- PrepareBridgeReference(
   reference = RNA, bridge = pbmc_multi_bridge,
   reference.reduction = "pca", reference.dims = dims.rna,
   normalization.method = "SCT", k.weight = 35)

```
Error in PrepareBridgeReference(reference = RNA, bridge = pbmc_multi_bridge,  : 
  unused argument (k.weight = 35)

<img width="610" alt="image" src="https://github.com/satijalab/seurat/assets/112990107/ec2526fa-2fca-4d99-992d-f775931ec9e8">

**Comment by yuhanH** [comment]
hi @clee700 
`k.weight` is a parameter not provided in `PrepareBridgeReference`. You need to modify this function to add this parameter. 
If you find this parameter is very important, you can make pull request after you modification.
