### ISSUE TITLE
heatmap legend overlapped

### ISSUE THREAD

**Issue by DUAN-GAO** [satijalab/seurat#7322]
Dear Seurat team and users,
I would like to ask how to adjust the character layout in the heatmap plot?
I drew with function DoHeatmap() and you can see the cluster label is overlapped in the plot.

![图片1](https://github.com/satijalab/seurat/assets/23400434/73240289-3e14-4cae-80db-0430964e57dc)

**Comment by AustinHartman** [comment]
You could consider dropping the labels and depend upon the color bar and the plot legend, or you could try adjusting the `lines.width` to increase the space between groups of cells so that the text can be displayed without overlap.
