### ISSUE TITLE
TSNE plot axis

### ISSUE THREAD

**Issue by DUAN-GAO** [satijalab/seurat#7323]
Dear Seurat team and users,
I would like to know how to adjust the axis in the Dimension plot below. As you can they have different y-axis ranges, the first one is -30- 30 while the second is -50-50.I would like them to be both -50-50 so that they display unanimously.

![图片1](https://github.com/satijalab/seurat/assets/23400434/12575e33-eb99-43dd-914d-35cb6494e439)
![图片2](https://github.com/satijalab/seurat/assets/23400434/c3561044-c8ca-4577-b800-ddb1773e17f6)

**Comment by AustinHartman** [comment]
You can edit the range of the y-axis using `ggplot2` functions:
```r
plot <- DimPlot(object)
plot + ylim(-50, 50)
```
