### ISSUE TITLE
Extract eigenvalues from RunPCA()

### ISSUE THREAD

**Issue by timothevanmeter** [satijalab/seurat#7324]
Hello,

I am trying to produce a graphic containing the eigenvalues for a PCA done on the expression matrix of my dataset.
The package **factoextra** enables one to retrieve the eigenvalues from the results of **prcomp()**, **princomp()**, but it does not seem to work for the result of **RunPCA()**.
Is there a way either with or without using factoextra to extract the eigenvalues from the results of RunPCA ?

Another issue is that a PCA done with prcomp or princomp is **a lot longer** than one performed with RunPCA for the same dataset.
Why is that ? Does RunPCA implements SVD (singular value decomposition) and the others do not ?

It would be a huge help if anyone knew how to obtain the eigenvalues for an expression matrix in a more time-efficient way.

Thanks a lot,

**Comment by saketkc** [comment]
Hi @timothevanmeter, while this is currently not supported, you should be able to do this by using `irlba`. The relevant code section is here:

https://github.com/satijalab/seurat/blob/763259d05991d40721dee99c9919ec6d4491d15e/R/dimensional_reduction.R#L880
