### ISSUE TITLE
Removing specific cluster based on one gene down regulation 

### ISSUE THREAD

**Issue by nitinsai1** [satijalab/seurat#7325]
Hello,

Im using seurat pipeline to analyze the single cell RNA-seq data. I m stuck with one problem I found two clusters with out gene A expression but this specific gene is expressed in all other clusters. It is important this gene it should be expressed so I would like to remove the two clusters which does not express it. But I use subset and Invert = TRUE commands and recluster the data it changes original UMAP structure. Can any body suggest an other way to remove the clusters based on gene expression.

Thank you,
Sainitin

**Comment by AustinHartman** [comment]
You can go into the matrix and select the cells with > 0 expression of your gene of interest and the only provide those cells when you plot the UMAP using `DimPlot(obj, cells = cells)`. Alternatively, you can either remove those cells entirely before clustering, or be sure the particular genes is not chosen as a variable feature so it will be used in your PCA and UMAP embeddings.
