### ISSUE TITLE
Error running SketchData: Is BPCells package needed for modest sample size?

### ISSUE THREAD

**Issue by jlmalin** [satijalab/seurat#7327]
Hi and thank you for Seurat v5.

To start, I am running SketchData on a dataset of ~5K cells (ultimately to be run on 22 datasets prior to integrating them), but am receiving an error:
`
> dat <- Read10X(path)
> test <-CreateSeuratObject(counts = dat, min.cells = 3, min.features = 200)
> test <- NormalizeData(test)
Normalizing layer: counts
Warning: The following arguments are not used: layer
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> test <- FindVariableFeatures(test)
Finding variable features for layer counts
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> SketchData(test, 1000)
Error in match.arg(arg = assay, choices = Assays(object = object)) : 
  'arg' must be NULL or a character vector
`
I see that there are issues installing BPCells [https://github.com/bnprks/BPCells/issues/6#issuecomment-1476976677](url) . Given that I haven't had success yet installing this package, I'd be interested in learning if it's possible to run SketchData without BPCells on datasets of modest size?

Thanks!
Justin

**Comment by yuhanH** [comment]
hi @jlmalin 
There is a bug in SketchData for the v3 assay as the input. We will fix this bug soon. 
Currently, you can just convert your assay from v3 to v5. Also, setting the parameters name with parameters value. 
```
test[['RNA']] <- as(object = test[['RNA']], Class = 'Assay5')
test <- SketchData(object = test, ncells = 1000)
```

**Comment by jlmalin** [comment]
Works perfectly. Thanks!

Justin
