### ISSUE TITLE
Blank UMAP

### ISSUE THREAD

**Issue by mayan2009** [satijalab/seurat#7328]
Hi I am runing seurat pipeline for 200 000 cells, and I met no error but the Umap plot is totally blank. Could anyone pleaseto help to fix it?

**Comment by yuhanH** [comment]
hi @mayan2009 
This is related to the updates of [scattermore](https://github.com/exaexa/scattermore). It is now required for you to manually adjust `pt.size` within `DimPlot`, for instance, `pt.size = 1`. We will fix this issue from Seurat side soon.

**Comment by samuel-marsh** [comment]
@yuhanH 

It appears that maybe it's just as simple as moving line 8022 to 8028 in the `SingleDimPlot` code.  That way `pt.size` is set following raster selection if `raster = NULL` is left as default.

https://github.com/satijalab/seurat/blob/763259d05991d40721dee99c9919ec6d4491d15e/R/visualization.R#L8022-L8028


Best,
Sam

**Comment by saketkc** [comment]
Hi @mayan2009, this is now fixed in the develop branch. You can pull the latest update for Seurat 4 using:

```r
remotes::install_github("satijalab/seurat", "develop", quiet = TRUE)
```
