### ISSUE TITLE
Error when running UMAP on sketched joined dataset in v5

### ISSUE THREAD

**Issue by jsialar** [satijalab/seurat#7329]
I imported multiple BPCell matrices and created seuratobjects out of each of them. I then merged the seuratobjects and joined the layers:

```r
#Import BPCell matrices
fileslist=str_sort(list.files('/mnt/FPMANA001A/LargeData/counts/production', pattern='S5908', full.names = T), numeric=T)
mat_list=mapply(import_matrix_market_10x, mtx_dir=fileslist, outdir=basename(fileslist))
#Create Seuratobj
seuratobj_list<-lapply(mat_list, CreateSeuratObject)
seuratobj_merged=merge(seuratobj_list[[1]], seuratobj_list[2:length(seuratobj_list)], add.cell.ids = basename(fileslist))
#Join layers
seuratobj_merged=JoinLayers(seuratobj_merged)
```
Afterwards, I sketched a subset of cells:
```r
seuratobj_merged_genotyped <- SketchData(
  object = seuratobj_merged_genotyped,
  ncells = 100000,
  method = "LeverageScore",
  sketched.assay = "sketch"
)
```
I then performed UMAP on the sketched data:
```r
DefaultAssay(seuratobj_merged_genotyped)='sketch'
seuratobj_merged_genotyped <- ScaleData(seuratobj_merged_genotyped)
seuratobj_merged_genotyped <- RunPCA(seuratobj_merged_genotyped)
seuratobj_merged_genotyped <- RunUMAP(seuratobj_merged_genotyped, dims = 1:50, return.model = T)
```
I encountered the following error in RunUMAP:
```
06:53:24 Writing NN index file to temp file /mnt/tmp/RtmpNmTLHd/file39087ed143fc

06:53:24 Searching Annoy index using 1 thread, search_k = 3000

Error in if (fsize > 2147483647) {: missing value where TRUE/FALSE needed
Traceback:

1. RunUMAP(seuratobj_merged_genotyped, dims = 1:50, return.model = T)
2. RunUMAP.Seurat(seuratobj_merged_genotyped, dims = 1:50, return.model = T)
3. RunUMAP(object = data.use, reduction.model = reduction.model, 
 .     return.model = return.model, assay = assay, umap.method = umap.method, 
 .     n.neighbors = n.neighbors, n.components = n.components, metric = metric, (truncated)
``` 

The NN index temp file cannot be found at the specified path, which caused the error. 
If I just subset the seurat object (take the first 1000 cells) without running SketchData and run UMAP on it, no issues encountered.

**Comment by jsialar** [comment]
The cause here is the SketchData function. After running it, I can't create and write to temporary files anymore. For example, the following code will fail:
```
fileConn<-file(tempfile())
writeLines(c("Hello","World"), fileConn)
```

The error will be:
```
Warning message in writeLines(c("Hello", "World"), fileConn):
“cannot open file '/mnt/tmp/RtmpTPHhR5/file1424d37cb67': No such file or directory”
Error in writeLines(c("Hello", "World"), fileConn): cannot open the connection
Traceback:

1. writeLines(c("Hello", "World"), fileConn)
```

**Comment by MaximilianNuber** [comment]
I encounter the same issue, same error message. But without sketching, the problem did not occur. Thanks already for any help :)

**Comment by jsialar** [comment]
What I found was restarting R resolve the problem. So I save the Seuratobject containing the sketch assay, restart R and load the saved object to continue.

**Comment by Dario-Rocha** [comment]
I got a very similar issue when trying to run UMAP on sketched data

> 14:04:59 Writing NN index file to temp file /var/folders/vs/2n7hpqjd7s70rsg0ys8kzgc40000gn/T//RtmpdL8eOq/filef88216594f1
> Unable to open: No such file or directory (2)
> 14:04:59 Searching Annoy index using 1 thread, search_k = 3000
> Unable to open: No such file or directory (2)
> Error in if (fsize > 2147483647) { : 
>   missing value where TRUE/FALSE needed

and even some error messages when saving RDS and restarting R

> `saveRDS(a_integrated, "onesampletest_temp.RDS")`
> Error in gzfile(file, mode) : cannot open the connection
> In addition: Warning message:
> In gzfile(file, mode) :
>   cannot open compressed file '/var/folders/vs/2n7hpqjd7s70rsg0ys8kzgc40000gn/T//RtmpdL8eOq/rstudio-available-packages-f8814156b58/time.rds', probable reason 'No such file or directory'
> 
> Restarting R session...

> Error: QuartzBitmap_Output - unable to open file '/var/folders/vs/2n7hpqjd7s70rsg0ys8kzgc40000gn/T//RtmpdL8eOq/dc0409d18492465f83861d95f8ab7f97.png'`

and it also got solved by saving the object to an rds file, restarting R and reloading since the rds creation

**Comment by ttumkaya** [comment]
Bizarre, I get this same error only with the rPCA integration but not Harmony or fastMNN. 

Will try restarting too, thanks for the tip everyone!

Tayfun

**Comment by Gesmira** [comment]
Hi all, thanks for reporting this. The issue should now be fixed in the seurat5 branch of Seurat. Please restart R and reinstall Seurat. 

```
remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)
```
