### ISSUE TITLE
Quantile thresholds in FeaturePlot

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#733]
Hello Seurat Team,

I am trying to understand what exactly gets plotted when I use FeaturePlot and specify min.cutoff and max.cutoff values as quantiles (q25 and q75).  My features to plot are not gene-expressions but a custom-computed score.  Earlier, I add these values as a meta.data column, and then also compute z-scores of this column using base::scale function.

When I specify the min.cutoff and max.cutoff as quantiles, do the values get scaled in some way so that the range of the values becomes (roughly) 0 to 1?  I say roughly because I see colorbars as attached.

Any insights would be greatly appreciated.

Thanks a lot!

![image](https://user-images.githubusercontent.com/12577720/44552707-1c7fb880-a6f9-11e8-99af-9b733dd41962.png)  ![image](https://user-images.githubusercontent.com/12577720/44552725-2b666b00-a6f9-11e8-9716-45795f3c6d09.png)

 
![image](https://user-images.githubusercontent.com/12577720/44552791-61a3ea80-a6f9-11e8-97a5-5675930258f2.png)  ![image](https://user-images.githubusercontent.com/12577720/44552801-6a94bc00-a6f9-11e8-939b-1ec9de994a05.png)

**Comment by satijalab** [comment]
Seurat does not rescale the values, but clips outliers based on the quantiles, so they do not dominate the color scheme. This works both for gene expression or for added scores
