### ISSUE TITLE
Conversion seurat v5 to sce

### ISSUE THREAD

**Issue by emanuelavilla** [satijalab/seurat#7333]
Hello!

I am trying to convert my seurat object to a SingleCellExperiment object. However, I got this error. Could be possible that the error is caused by the new version of seurat object v5?

![Screenshot 2023-05-16 alle 16 12 06](https://github.com/satijalab/seurat/assets/85672107/2acfac1c-01ca-4148-94d0-3b3bfbb92f4a)

**Comment by Gesmira** [comment]
Hi, 
Do you have multiple layers in your object?
If so, I would recommend joining the layers or using code like this to get a list of SingleCellExperiment objects per layer: 

```
  layers <- Layers(object, search = 'data')
  objects.sce <- lapply(
    X = layers,
    FUN = function(x, f) {
      return(as.SingleCellExperiment(
        x = subset(x = object,
                   features = f,
                   cells = colnames(LayerData(object, layer = x)))
            )
        )
    },
    f = rownames(object)
  )

```

**Comment by ShanshanHe7** [comment]
For my case is I convert each assay in my multiome Seurat  to  `SingleCellExperiment` respectively then combine them together.
`DefaultAssay(obj.multi) <- "RNA"`
`obj.multi.rna <- obj.multi`
`obj.multi.rna[["ATAC"]] <- NULL`
`obj.multi.rna.sce <- as.SingleCellExperiment(obj.multi.rna)`
`DefaultAssay(obj.multi) <- "ATAC"`
`obj.multi.atac <- obj.multi`
`obj.multi.atac[["RNA"]] <- NULL`
`obj.multi.atac.sae <- as.SingleCellExperiment(obj.multi.atac)`
`obj.multi.mae <- MultiAssayExperiment(list("RNA"  = obj.multi.rna.sce, 
                                           "ATAC" = obj.multi.atac.sce ))`
