### ISSUE TITLE
4 samples over a timecourse  RNA and single CITE-seq antibody

### ISSUE THREAD

**Issue by colin986** [satijalab/seurat#7335]
Hi,

I have 4 different samples with RNA and a single CITE-seq antibody. 

I have integrated the RNA data following the integration tutorial. 

For the CITE-seq data I have normalised using CLR, margin = 1.  

Is this the best approach? Is there any alternatives I could use? I is feasible to include a single CITE-seq target in the RNA matrix?

Any help appreciated, 
Colin

**Comment by saketkc** [comment]
Hi Colin, these are very broad questions and the answers are very context dependent. Regarding the CLR normalization, using margin=2 will normalize for differences in ADT depth across cells while margin=1 will normalize across features. In situations where your antibody panels are small and have been sequenced to saturation using margin=2 might give you a better normalization (but it depends).

You could use the CITE-seq data as a reference (assuming it has higher number of cells and good data quality) and then use it to annotate the rest of your datasets. Alternatively, you could integrate them together and use the RNA + protein markers to annotate the clusters. There is no right answer here.

**Comment by mhkowalski** [comment]
Hi, 

I would not recommend including your CITE-seq data in the RNA matrix. I think CLR with margin =1 is reasonable, I'm not sure of any alternatives with only a single antibody. It might be helpful to look at the distribution of counts in your data (is it clearly bimodal, can you identify a population that is more highly expressed?) If there is no clear separation of populations, it will be hard to know which cells express the marker more highly or just have more reads. If you have multiple antibodies, then you can normalize sequencing depth across cells with CLR with margin = 2, but with 1 marker you do not know if a cell is more deeply sequenced or if the protein is more highly expressed in that cell.
