### ISSUE TITLE
Error running SketchData with SCTransformed data

### ISSUE THREAD

**Issue by jlmalin** [satijalab/seurat#7336]
Hello,

In running SketchData on each of 22 SCTransformed datasets, 20 datasets run to completion while two datasets throw errors. One of the two datasets, for example:
`
> smpl <- "SCAF2487" 
> obj.list[[smpl]][['SCT']] <- as(object = obj.list[[smpl]][['SCT']], Class = 'Assay5')
> print(obj.list[[smpl]]@active.assay)
[1] "SCT"
> sketch.500.list[[smpl]] <- SketchData(obj.list[[smpl]], ncells = min(500, dim(obj.list[[smpl]])[2]), method = "LeverageScore", sketched.assay = "sketch")
Calcuating Leverage Score
Running LeverageScore for layer data
Error in `LeverageScore()`:
! too slow
Run `rlang::last_trace()` to see where the error occurred
`

The two datasets that fail do not appear qualitatively different than those for which SketchData ran. These are the two that threw errors:
`
> smpl <- "SCAF2487"
> obj.list[[smpl]]
An object of class Seurat 
41671 features across 11465 samples within 2 assays 
Active assay: SCT (18071 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap

> smpl <- "SCAF4982"
> obj.list[[smpl]]
An object of class Seurat 
45024 features across 18695 samples within 2 assays 
Active assay: SCT (19846 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
`

This is an example dataset that ran SketchData to completion:
`
> small <- "SCAF2832"
> obj.list[[smpl]]
An object of class Seurat 
34674 features across 996 samples within 2 assays 
Active assay: SCT (16446 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
`

Can you conjecture why _SketchData_ ran for 20 datasets but not for the two that threw errors?

In your reply to #7171, who also had  _Error in LeverageScore()_, you advised running _FindVariableFeatures_.
Since my object was SCTransformed, my understanding is that the object already has VariableFeatures:
`
> obj.list[[smpl]]@active.assay
[1] "SCT"
> VariableFeatures(obj.list[[smpl]])[1:5]
[1] "HES4"   "ISG15"  "DVL1"   "CCNL2"  "MRPL20"

Nonetheless I tried running _FindVariableFeatures_ followed by _SketchData_:
`
> smpl <- "SCAF2487" 
> obj.list[[smpl]] <- FindVariableFeatures(obj.list[[smpl]])
Finding variable features for layer counts
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> obj.list[[smpl]]@active.assay
[1] "SCT"
> obj.list[[smpl]] <- SketchData(obj.list[[smpl]], ncells = min(500, dim(test)[2]), method = "LeverageScore", sketched.assay = "sketch")
Calcuating Leverage Score
Running LeverageScore for layer data
sampling 5000 cells
Performing QR decomposition
Performing random projection
Attempting to cast layer data to dgCMatrix
Attempting to cast layer counts to dgCMatrix
`

... and it successfully ran to completion.
So, is this sketched dataset based on different underlying normalization than the 20 SCT transformed datasets that ran successfully without first running FindVariableFeatures? 
If so, is this a concern for subsequent integration of these two datasets with the other 20?
And lastly, what are your recommendations for integrating multiple sketched datasets? I can open a separate issue for this last question, if you prefer.

Thanks!
Justin

**Comment by yuhanH** [comment]
Hi Justin
For those two datasets, have you subset cells after running SCTransform?
Generally, I would not suggest you run SketchData on SCT assay. The most common way is to use RNA assay, run `NormalizeData`, `FindVariableFeatures` and then`SketchData`.

**Comment by jlmalin** [comment]
Hi Yuhan,
Thank you for your reply. To answer your question, there was no subsetting following SCTransform.
So, how would you say the performance compares between running SketchData on normalized RNA assay data,  followed by integrations; vs. sampling cells based on leverage score followed by SCTransform and Integration as described in [https://satijalab.org/seurat/articles/atomic_integration.html](url) ?
Thanks,
Justin

**Comment by yuhanH** [comment]
hi @jlmalin 
`SketchData` is designed specifically for large-scale data analysis. Our approach to calculating the leverage score doesn't generate large matrices during intermediate steps. Unlike `SketchData`, sctransform is not particularly optimized for handling large-scale data. Additionally, the output residual matrix is always a dense matrix, so it is not proper to be used for sketching.

**Comment by jlmalin** [comment]
Thanks, Yuhan.
