### ISSUE TITLE
How to remove cells from following analysis

### ISSUE THREAD

**Issue by lilycanfly** [satijalab/seurat#734]
Hi,
We noticed that we have some contamination in our sample preparation. Is there way that I can remove these cluster from my data and re-cluster it? Thanks a lot.

Best,
Lili

**Comment by mojaveazure** [comment]
Hi Lili,

You can use the [`SubsetData`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/SubsetData) function to reduce a Seurat object to certain cells. If all of the cells you want to remove are in a single cluster, you can use the `ident.remove` argument to remove that identity.
