### ISSUE TITLE
Integration on Seurat v5 after SCTransform v2 normalization

### ISSUE THREAD

**Issue by Victor21v** [satijalab/seurat#7342]
Hello,

I am trying to do a integration analysis with some datasets. First, I would like to apply SCTransform v2 normalization. However, I'm using Seurat V5, that means I have merged the datasets followed by SCTransform normalization, as I assume it normalizes based on the layers I have provided. 

While I do the normalization, it seems SCT takes in account the layers:
> Running SCTransform on assay: RNA
> Running SCTransform on layer: counts.RPE004
> Using block 1 from RPE004 to learn model.
> Place corrected count matrix in counts slot
> Running SCTransform on layer: counts.RPE005
> Using block 1 from RPE005 to learn model.
> Place corrected count matrix in counts slot
> Running SCTransform on layer: counts.RPE006
> Using block 1 from RPE006 to learn model.
> Place corrected count matrix in counts slot
> Warning: Assay SCT changing from Assay5 to SCTAssay
> Set default assay to SCT

However, after the normalization has been done, I realise the models have been stored for each dataset, but the SCT assay is not stored in layers like RNA slot:

> RPE[["SCT"]]
> SCTAssay data with 17156 features for 8866 cells, and 3 SCTModel(s) 
> Top 10 variable features:
> ITLN1, MGP, APOE, HLA-DRA, TAGLN, IGFBP7, LYZ, CCL4, HLA-DRB1, CD74 

That's means when I try to use IntegrateLayers() function, it displays an error, so I can't follow with the integration nor compare different integration procedures (CCA, Harmony, etc.).

**Since there's any documentation regarding the use of SCTransform on Seurat v5 with layers following integration approaches**, my question is the following:
Should I have to follow old SCTransform v2 vignette? That means, separate datasets and perform SCT independently, etc.

Thanks in advance

**Comment by vpbio** [comment]
Is there any update regarding this issue ?  I also have this question.

**Comment by longmanz** [comment]
Dear both,

Given that you did not provide the exact Rcodes you were using, we tried to reproduce the issue on our own. We found that using following codes, SCTransform works pretty fine with Seurat V5 assay:
```
# using data from vignette 
obj <- LoadData("pbmcsca")
obj = UpdateSeuratObject(obj)
obj <- subset(obj, nFeature_RNA > 1000)
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$Method)

# get mt-percent
obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^MT-")

# run sctransform on all layers as the user suggested
obj <- SCTransform(obj, method = "glmGamPoi", vars.to.regress = "percent.mt", vst.flavor = "v2")
obj = RunPCA(obj, npcs = 30, verbose = FALSE)

# one-liner to run Integration; 
obj <- IntegrateLayers(object = obj, method = HarmonyIntegration, 
  orig.reduction = "pca", new.reduction = 'harmony', 
  assay = "SCT", verbose = FALSE)

obj <- FindNeighbors(obj, reduction = "harmony", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, cluster.name = "harmony_clusters")

# 
obj <- RunUMAP(obj, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
p1 <- DimPlot(
    obj,
    reduction = "umap.harmony",
    group.by = c("Method", "CellType"),
    combine = FALSE
)

```
And you can see that the integration works pretty well from the UMAP p1. 
We will close this issue for now. But if you still encounter issue with the above workflow, we will reopen it.

**Comment by Akos-Bio-Data** [comment]
I was wondering if Seurat’s merge() function creates the same type of [['RNA']] layers when merging multiple Seurat objects as the split() function does when splitting one object’s [['RNA']] assay into layers? Could this be a reason why some Users report that SCTransform() did not affect all layers within the Seurat object?
