### ISSUE TITLE
RDS file format and information stored

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7343]
Hi
I have analyzed 4 samples together and saved 4 clusters as RDS file to give to other lab for analysis.
I have attached the code, my question is this RDS file will contain raw counts under count in RNA assay?
Kindly suggest is it correct way to have raw counts?

dl <-  c(Ctrl = "~/Desktop/WT/F" , D1= "~/Desktop/D1/F" , D2= "~/Desktop/D2/F" ,  D3= "~/Desktop/D3/F")
#Read 10X
dl <- Read10X (dl)
#Create object
Data.all <- CreateSeuratObject(counts= dl)
#
Data.all[["percent.mt"]] <- PercentageFeatureSet(Data.all, pattern = "^mt-")
Data.all <- subset(Data.all,subset = nFeature_RNA > 200 & nFeature_RNA < 2500  & percent.mt < 10)
#
Data<- SCTransform(Data.all, method = "glmGamPoi", vars.to.regress = "percent.mt",do.correct.umi = TRUE , verbose = TRUE,conserve.memory = TRUE)
Data <- RunPCA(Data,verbose=FALSE)
Data  <- RunUMAP(Data, reduction="pca",dims=1:30)
Data <- FindNeighbors(Data, dims = 1:30, verbose = FALSE)
Data <- FindClusters(Data, verbose = FALSE)
DimPlot(Data)
#
T  <- subset(Data,idents=c("2","7","23"))
#
Idents(T)= "orig.ident"
DimPlot(T ,label = TRUE)
T@assays$RNA@counts

**Comment by mhkowalski** [comment]
Hi, 

Saving your seurat object as an RDS will preserve the raw counts, as long as the raw counts are in your object.
