### ISSUE TITLE
Rasterizing UMAPs

### ISSUE THREAD

**Issue by FahdAdam** [satijalab/seurat#7345]
Hello,

I have an issue in Seurat::DimPlot(raster = TRUE), whenever I set raster = True, the UMAP becomes very transparent and barely seen, I tried to play around with pt.size and raster.dpi, but unfortunetaly it gives a UMAP as if no raster was applied!
when just setting raster = TRUE, the UMAP looks as wished but blurry! Any solution for this issue?

**Comment by saketkc** [comment]
Hi @FahdAdam, not sure what you mean by as if no raster was applied, but here are some examples with `pbmc_small`:

> DimPlot(pbmc_small, raster=T)
![image](https://github.com/satijalab/seurat/assets/682153/fda6a982-eb26-42da-8227-8ab6c5b5a0d6)

> DimPlot(pbmc_small, raster=T, pt.size=3, raster.dpi = c(1024,1024))
![image](https://github.com/satijalab/seurat/assets/682153/bd77dece-4a64-4a87-8e35-77457409810f)


You want to increase the `raster.dpi` parameter for the plots to look smoother (but at the cost of increasing the file size). Hope this helps! I am closing this, but feel free to reopen if you have any follow up questions.
