### ISSUE TITLE
hclust error in IntegrateEmbeddings with a subset of anchors

### ISSUE THREAD

**Issue by zhang248** [satijalab/seurat#7348]
Hi,

I'm currently working on integrating some scATAC samples. I followed Timoast's suggestion (https://github.com/stuart-lab/signac/issues/1405) and subsetted my AnchorSet object from the output of FindIntegrationAnchors(). However, when I attempted to run IntegrateEmbeddings() using this subset, I encountered the following error:
`Error in hclust(d = dist.mat) :
  NA/NaN/Inf in foreign function call (arg 10)
`
Bellow are my codes:
`integration.anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = rownames(pigOBJ2), reduction = "rlsi", dims = 2:30)
`
`integration.anchors2 <- subset(integration.anchors, dataset.matrix = samplemtx)
`
`pigOBJ3 <- IntegrateEmbeddings(anchorset = integration.anchors2, reductions = pigOBJ2[["lsi"]], new.reduction.name = "integrated_lsi", dims.to.integrate = 1:30)`

Thanks!

**Comment by zhang248** [comment]
I have reviewed the codes in the integration function and it appears that the error is triggered by the presence of 'Inf' values in the distance matrix, which is used as an input for the 'hclust' function. Specifically, after subsetting my AnchorSet object, the values between the removed pairs become 0 in the similarity matrix. Consequently, when calculating distances using the 'as.dist' function, these values turn into 'Inf'.

I'm uncertain about how to resolve this error, so any suggestions would be greatly appreciated!

**Comment by Gesmira** [comment]
Hi, 
We would recommend rerunning FindIntegrationAnchors with the samples that you would like to integrate specifically. We don't currently support running integration on a subset AnchorSet object as you can tell from the error you ran into.
