### ISSUE TITLE
How to build one object contains data from different samples in Seurat V5?

### ISSUE THREAD

**Issue by xmliu01** [satijalab/seurat#7350]
I am using Seurat V5 to analysis a single cell RNA dataset, which includes multiple samples. I want to load them into one Seurat V5 object and integrate them, but I don't know how the load them at first.

I loaded each of them and build Seurat object respectively as the following code:
```
W2.5_1.count=Read10X("./data/W2.5_1_R1250/",gene.column = 1)
W2.5_2.count=Read10X("./data/W2.5_2_R1251/",gene.column = 1)
W3_1.count=Read10X("./data/W3_1_R1744/",gene.column = 1)
W3_2.count=Read10X("./data/W3_2_R1745/",gene.column = 1)
W2.5_1=CreateSeuratObject(counts=W2.5_1.count,project = "W2.5_1",min.cells=3)
W2.5_2=CreateSeuratObject(counts=W2.5_2.count,project = "W2.5_2",min.cells=3)
W3_1=CreateSeuratObject(counts=W3_1.count,project = "W3_1",min.cells=3)
W3_2=CreateSeuratObject(counts=W3_2.count,project = "W3_2",min.cells=3)
```

**Comment by Dario-Rocha** [comment]
1- Create a list with the count matrices
2- Create one seurat object with the list of the count matrices
There is more info about that in this vignette: https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html#load-data-from-multiple-h5ad-files
