### ISSUE TITLE
std::bad_alloc error after running IntegrateData() in SCTransform v2 workflow

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [satijalab/seurat#7354]
Dear Seurat team,

I am following "_SCTransform, v2 regularization_" workflow for 16 snRNA-seq datasets (number of cells ~300k ). 
I am getting a following error after running `IntegrateData()`:
```
This warning is displayed once every 8 hours. 
Error: **std::bad_alloc**
Execution halted
Warning message:
system call failed: Cannot allocate memory  
```

My PC specifications: 
**RAM:** 125G
**free disk space:** 2.5T  (67%)
Seurat v. 4.9.9.9040
object.size(anchorset)  # 41683870864 bytes

How can I solve this issue?
Thank you

**Comment by saketkc** [comment]
Hi @IrinaVKuznetsova For large datasets, we have some recommendations here which would be useful: https://satijalab.org/seurat/articles/integration_large_datasets.html. Please feel free to reopen if you face issues.

**Comment by IrinaVKuznetsova** [comment]
> Hi @IrinaVKuznetsova For large datasets, we have some recommendations here which would be useful: https://satijalab.org/seurat/articles/integration_large_datasets.html. Please feel free to reopen if you face issues.

I have tried a workflow for large datasets, it works fine and relatively quick for this size, but falls over when I run IntegrateData() generating the same error Error: `**std::bad_alloc**`
I also, tried to Parallelization with future ( https://satijalab.org/seurat/articles/future_vignette.html)  and got `"system call failed: Cannot allocate memory"`
thanks
