### ISSUE TITLE
RunAzimuth - Could not resolve host: seurat.nygenome.org

### ISSUE THREAD

**Issue by SirKuikka** [satijalab/seurat#7357]
Hi,

I'm running Azimuth in Seurat v5. It works fine if I have internet connection, but it doesn't work if I don't have internet connection. Does Azimuth transfer the data to a server for processing? Is there a way to Azimuth locally?

`Error in curl::curl_fetch_memory(url, handle = handle) :    Could not resolve host: seurat.nygenome.org`

**Comment by Gesmira** [comment]
Hi, 
RunAzimuth requires an internet connection to fetch the homolog table file to convert gene names. Alternatively, you can download that file [here](https://seurat.nygenome.org/azimuth/references/homologs.rds), and run `AzimuthApp` specifying the path to the homolog file like so: 
```
AzimuthApp(reference= "reference_folder", config = "config.json", demodataset = "demo.rds", homolog.table = "homolog.rds")
```

**Comment by SirKuikka** [comment]
Hi,

I ran this 

`AzimuthApp(reference= "C:/rlibs/4.2.3/pbmcref.SeuratData/azimuth/",homolog.table = "C:/Users/user/Downloads/homolog.rds")


But I got the same connection error in the app after I uploaded the data matrix there.
`

**Comment by Gesmira** [comment]
My apologies, I included the wrong parameter name! Can you retry with: `Azimuth.app.homologs = "C:/Users/user/Downloads/homolog.rds"` and let me know if that works?

**Comment by SirKuikka** [comment]
No, it doesn't. Then i get this error `URL using bad/illegal format or missing URL`.

**Comment by SirKuikka** [comment]
And this solution requires opening the shiny app. Is there a command that can be ran?

**Comment by Gesmira** [comment]
It seems like the problem may be the windows file path format as I am not able to replicate the issue. The function would ignore a path starting with "C". Can you try providing a relative path? We can push a fix for this bug if that is the case. 

To your second question, `RunAzimuth` does not support adding a parameter for the homolog table as the URL is hard-coded. You could change the source code of the function using commands like `trace()`. Or you could run the internal functions individually. The homolog table is specifically provided to the `ConvertGeneNames` function.

**Comment by SirKuikka** [comment]
Yes, it worked with a relative path. Thank you.

**Comment by Huffyphenix** [comment]
@Gesmira 
Thank you for your nice tool!
I met a problem similar to this when I tried to run Azimuth locally with Seurat v5.
I have downloaded homologs.rds file, and ran AzimuthApp specifying the path to the homolog file like so:
`obj <- RunAzimuth(obj, reference = "/apps/users/yxy_hufeifei/Huff/Brain_scRNAseq_forNSF/HCA_brain_Cell_Atlas_v1/ref/Azimuth_humancortexref", Azimuth.app.homologs = "/apps/users/yxy_hufeifei/Huff/Brain_scRNAseq_forNSF/HCA_brain_Cell_Atlas_v1/ref/homolog.rds")`

Here is the output in console:
```
Warning: **The following arguments are not used: Azimuth.app.homologs**
Warning: Overwriting miscellanous data for model
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Warning: Adding a dimensional reduction (refUMAP) without the associated assay being present
Error in curl::curl_fetch_memory(url, handle = handle) :
  Could not resolve host: seurat.nygenome.org
Calls: RunAzimuth ... request_fetch -> request_fetch.write_memory -> <Anonymous>
```

I checked the arguments of RunAzimuth and found there is no argument called Azimuth.app.homologs.
Is this an update of the function? What can I do if I need to run RunAzimuth without an internet connection?

**Comment by s-andrews** [comment]
I'm hitting the same problem.  In our case the breakage originates with a security system which generates self-signed https certificates for all outgoing connections.  We have a root certificate in our chain for these, but any program which doesn't trust the windows certificate store won't see this.

In R you need to change the download method option to make any https downloads work:

```options("download.file.method"="wininet") ```

..and after that you can download the homologs file OK:

```
download.file('https://seurat.nygenome.org/azimuth/references/homologs.rds';, destfile = "c:/Users/andrewss/homologs.rds")
trying URL 'https://seurat.nygenome.org/azimuth/references/homologs.rds';
Content type 'application/octet-stream' length 3458249 bytes (3.3 MB)
downloaded 3.3 MB
```

The problem is that ```readRDS``` doesn't seem to honour this so that still fails:

```
readRDS('https://seurat.nygenome.org/azimuth/references/homologs.rds';)
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
cannot open compressed file 'https://seurat.nygenome.org/azimuth/references/homologs.rds';, probable reason 'Invalid argument' 
```

I could supply the homolog.rds file as a file but ```RunAzimuth``` doesn't offer this as an option.  The homolog table is hard-coded as an https URL without an option which can change it.

If you changed the function definition for ```RunAzimuth``` to be:

```
RunAzimuth.Seurat <- function(
  query,
  reference,
  query.modality = "RNA",
  annotation.levels = NULL,
  umap.name = "ref.umap",
  do.adt = FALSE,
  verbose = TRUE,
  assay = NULL,
  k.weight = 50,
  n.trees = 20,
  mapping.score.k = 100, 
  homolog.table.location = "'https://seurat.nygenome.org/azimuth/references/homologs.rds'"
  ...
)
```

..and then changed the code for the conversion to be:

```
query <- ConvertGeneNames(
      object = query,
      reference.names = rownames(x = reference),
      homolog.table = homolog.table.location
    )
```

Then we'd be able to set this at run time to avoid this problem.

**Comment by s-andrews** [comment]
After more digging the root of this problem for us is that ``gzfile`` in R doesn't have a ```method``` option.  A normal ```file``` connection can specify the download method using the ```url.method``` option, but for some reason this isn't implemented in ```gzfile``.  That means that we'd need support from within Azimuth to bypass the download (which would be nice anyway).
