### ISSUE TITLE
SketchData of Seurat V5 not working

### ISSUE THREAD

**Issue by cliftonlewis** [satijalab/seurat#7360]
Firstly great new implementation of Seurat with version 5. Iw as trying to use it , however, it is failing at the first step of sketching the data. I think this has to do with the SeuratOject CastAssay function, however, I'm not too sure how to fix the error. Any help greatly appreciated.
> obj <- SketchData( object = obj,   ncells = 50000,   method = "LeverageScore",   sketched.assay = "sketch" )
Calcuating Leverage Score
Running LeverageScore for layer data
sampling 5000 cells
Performing QR decomposition
Performing random projection
Warning: The following arguments are not used: method, layer
Error in UseMethod(generic = "CastAssay", object = object) : 
  no applicable method for 'CastAssay' applied to an object of class "c('Assay', 'KeyMixin')"

**Comment by Gesmira** [comment]
Hi, 
Based on the error, it seems that you are not running this on an object with a v5 assay, which is required. You can convert your Assay to Assay5 using the following code: `obj[["RNA"]] <- as(obj[["RNA"]], "Assay5")`, or rebuild the object setting `options(Seurat.object.assay.version = 'v5')`
