### ISSUE TITLE
To find out DE between two groups?

### ISSUE THREAD

**Issue by surinderchd** [satijalab/seurat#7363]
seurat.objectnew <- SetIdent(seurat.objectnew, value = "Type")
cell_de1 <- FindMarkers(seurat.objectnew, ident.1 = "Disease", ident.2 = "Control", min.pct = 0.25, logfc.threshold = 0.25)

I want to compare my control group with disease group, to check wether expression in disease condition increase or decrease?
So for this ident.1 should be the control group or ident.2 ?

Please help me to clear this.
Thanks & Regards

**Comment by saketkc** [comment]
@surinderchd ident.2 is the group against which log fold change is calculated (so a logfoldchange of 0.5 implies ident.1 has higher gene expression than ident.2)
