### ISSUE TITLE
The seurat object structure is as follows. No information can be extracted.How do I extract the matrix after the '$' sign?

### ISSUE THREAD

**Issue by leiwen7788** [satijalab/seurat#7367]
>str(data)
Formal class 'seurat' [package "Seurat"] with 0 slots
 Named list()
  ..$ raw.data    :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:81916773] 78 99 103 183 188 198 222 224 225 226 ...
  .. .. ..@ p       : int [1:58359] 0 518 1036 2543 3469 4050 4958 5739 6565 7252 ...
  .. .. ..@ Dim     : int [1:2] 23498 58358
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:23498] "FO538757.2" "AP006222.2" "RP4-669L17.10" "RP11-206L10.9" ...
  .. .. .. ..$ : chr [1:58358] "Healthy1_Cd45+_AAACCTGCAGTATCTG" "Healthy1_Cd45+_AACTGGTTCATGGTCA" "Healthy1_Cd45+_AACTTTCCAGCTGTAT" "Healthy1_Cd45+_AAGGTTCCACATGACT" ...
  .. .. ..@ x       : num [1:81916773] 1 1 1 1 1 1 1 9 4 11 ...
  .. .. ..@ factors : list()
  ..$ data        :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:81916773] 78 99 103 183 188 198 222 224 225 226 ...
  .. .. ..@ p       : int [1:58359] 0 518 1036 2543 3469 4050 4958 5739 6565 7252 ...
  .. .. ..@ Dim     : int [1:2] 23498 58358
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:23498] "FO538757.2" "AP006222.2" "RP4-669L17.10" "RP11-206L10.9" ...
  .. .. .. ..$ : chr [1:58358] "Healthy1_Cd45+_AAACCTGCAGTATCTG" "Healthy1_Cd45+_AACTGGTTCATGGTCA" "Healthy1_Cd45+_AACTTTCCAGCTGTAT" "Healthy1_Cd45+_AAGGTTCCACATGACT" ...
  .. .. ..@ x       : num [1:81916773] 2.38 2.38 2.38 2.38 2.38 ...
  .. .. ..@ factors : list()
  ..$ scale.data  : symbol NULL

**Comment by Gesmira** [comment]
Hi, 
It seems like you are using an object built under an older version of Seurat. We recommend using the latest version of Seurat and updating your object with `UpdateSeuratObject()`. Alternatively, you can extract the matrix from the `raw.data` slot in this older object and build a new Seurat Object.
