### ISSUE TITLE
How to fix Seurat dotplot binary scale for two samples

### ISSUE THREAD

**Issue by KatGoldfinch** [satijalab/seurat#7368]
Hello, 
little question about Dotplot in Seurat. 
When I make the Dotplot for more than 2 samples, I do have the gradient of colors indicating the level of average expression (pic 1)
DotPlot (cells, features=c("OBSL1", "PAX6", "BDNF", "GAP43", "CDK5", "NCAM1", "PROM1", "NES", "GFAP"),   dot.scale = 9,
cols = c("blue", "red"),scale=T) +theme(axis.text.x = element_text(angle = 90))

![4sam](https://github.com/satijalab/seurat/assets/65793468/200ccfe7-0392-4b80-b233-7cafeacbbe64)

However, when I do the same plot only with two samples, the color scale becomes binary (all dots are either bright red, or bright blue) (pic2). 
![2sam](https://github.com/satijalab/seurat/assets/65793468/ddf5c5d7-1cfa-4e06-9b5e-ce5c8be87618)
DotPlot (cells, features=c("OBSL1", "PAX6", "BDNF", "GAP43", "CDK5", "NCAM1", "PROM1", "NES", "GFAP"),   dot.scale = 9,
         cols = c("blue", "red"),scale=T, idents = c("WT", "Sample 1")) +theme(axis.text.x = element_text(angle = 90))

Can you please advise how to fix it?

**Comment by AustinHartman** [comment]
Try setting `scale = FALSE`. Scaling data when comparing the expression across a small number of groups is challenging to interpret.
