### ISSUE TITLE
AddModuleScore

### ISSUE THREAD

**Issue by maqingyue** [satijalab/seurat#7369]
Hello, I encountered the following error while using the addmoduleScore function:

Error in `cut_number()`:
! Insufficient data values to produce 24 bins.

When I change the nbin parameters, I can eliminate this error. Increasing or decreasing the nbin can eliminate the error. I would like to ask if the scores obtained from different samples using different nbins are comparable?

**Comment by mhkowalski** [comment]
Hi, 

I wouldn't recommend comparing module scores across different samples. The genes chosen as a background will be different, and these scores might not be comparable. You could merge the samples and then calculate the module score, if you'd like.
