### ISSUE TITLE
FeaturePlot bug when specifying min.cutoff?

### ISSUE THREAD

**Issue by iiiir** [satijalab/seurat#737]
Hi,

I am not sure if i hit a bug. I am playing with featureplot and found that if i specifying min.cutoff. a lot of cells gets removed from he plot.
Here what i expected when do not specify cut.off.
i counted "CD28" positive cells using:

```R
> CD28_positive_idx <- which(myproject@data["CD28",] > 0)
> table(myproject@ident[CD28_positive_idx])
...         CTL          NK 
...          12           4 
```
so i am expecting 4 cells for NK group to be CD28 positive and 12 cells for CTL group

**the following plot is CORRECT**
```R
> FeaturePlot(myproject,
            features.plot = c("CD28"),
            cols.use = c("lightgrey","blue"),
            overlay = T,no.legend = F, 
            pt.size = 1)
```

**the following command, only highlights 1 CTL cell and 0 NK cell. but all my values are larger than 0.8**
```R
> FeaturePlot(myproject,
            features.plot = c("CD28"),
            cols.use = c("lightgrey","blue"), min.cutoff = 0.8,
            overlay = T,no.legend = F, 
            pt.size = 1)
> min(myproject@data["CD28",idx])
[1] 0.952763
```
also, change 0.8 to 0.5, or 0.1, different number of cells will be highlighted.

can you take a look to make sure i did not miss anything, why the numbers does not match?

thanks,
Shuoguo

**Comment by andrewwbutler** [comment]
Hi Shuogo,

Cells shouldn't get removed from the plot by specifying `min.cutoff`. Any cells with values below that value (or quantile) get set to `min.cutoff` but they're still plotted so I'm not sure why cells are being removed. 

Also, why are you setting `overlay = T`? That should only work when you provide two features to plot. I can't seem to reproduce the problem on my end. Can you provide a reproducible example on the test dataset (`pbmc_small`) or provide a download link to the object you're working with?
