### ISSUE TITLE
Convert 10X multiome Seurat object to MultiAssayExperiment/SingleCellExperiment

### ISSUE THREAD

**Issue by ShanshanHe7** [satijalab/seurat#7370]
Dear team,
Hi and good day. I am having a short problem abut converting 10X multiome Seurat object to MultiAssayExperiment. My solution is converting each assay in multiome Seurat  to `SingleCellExperiment` respectively then combine them together. However, in this way, I loss the colData in `MultiAssayExperiment` file then I add the colData manually. I am wondering do you have any  better idea?

`DefaultAssay(obj.multi) <- "RNA"`
`obj.multi.rna <- obj.multi`
`obj.multi.rna[["ATAC"]] <- NULL`
`obj.multi.rna.sce <- as.SingleCellExperiment(obj.multi.rna)`
`DefaultAssay(obj.multi) <- "ATAC"`
`obj.multi.atac <- obj.multi`
`obj.multi.atac[["RNA"]] <- NULL`
`obj.multi.atac.mae <- as.SingleCellExperiment(obj.multi.atac)`
`obj.multi.mce <- MultiAssayExperiment(experiments = list("RNA"  = obj.multi.rna.sce, "ATAC" = obj.multi.atac.sce ), colData      =  obj.multi.rna.sce@colData)`

**Comment by ShanshanHe7** [comment]
Also, is there any method that can directly convert 10X multiome Seurat file to `scMultiome` format?

**Comment by yuhanH** [comment]
hi @ShanshanHe7 
You may have a try on this mudata, https://pmbio.github.io/MuDataSeurat/
You can convert multi-assay seurat into h5mu and then to MultiAssayExperiment.
