### ISSUE TITLE
Blend.Threshold - lower colocalisation threshold

### ISSUE THREAD

**Issue by lds8Henry** [satijalab/seurat#7372]
When I change the blend.threshold on a umap plot, only the negative level becomes lower. The double positive level (yellow) stays the same? 
![image](https://github.com/satijalab/seurat/assets/134525955/5b568f12-b2e5-4da0-9cdc-a58623710f1f)

I have seen other examples where the threshold for double positive becomes lower:
![image](https://github.com/satijalab/seurat/assets/134525955/ee8085f3-2c77-4e26-a361-dd7049a625a6)

Does anyone know how to do this?

Thanks!

**Comment by lds8Henry** [comment]
Bump

**Comment by howtofindme** [comment]
> When I change the blend.threshold on a umap plot, only the negative level becomes lower. The double positive level (yellow) stays the same? ![image](https://user-images.githubusercontent.com/134525955/240648046-5b568f12-b2e5-4da0-9cdc-a58623710f1f.png)
> 
> I have seen other examples where the threshold for double positive becomes lower: ![image](https://user-images.githubusercontent.com/134525955/240648451-ee8085f3-2c77-4e26-a361-dd7049a625a6.png)
> 
> Does anyone know how to do this?
> 
> Thanks!

have you solved it?   i got the same problem!

**Comment by lds8Henry** [comment]
I haven't gotten blend to work. Nebulosa has some colocalisation tools - but it takes up much more space because you have to show the two single genes, then the third is the intersection. For this experiment I have three samples, uncut, 24 and 48hpa:

```{r}


Plot_Density_Custom(seurat, features = "msx3", custom_palette = CustomPalette(low ="lightgray", high = "#FF4500", mid = "#FFEF7D", k = 50)) +
    facet_wrap(.~seurat$orig.ident, ncol=2)
Plot_Density_Custom(seurat, features = "fbln1",  custom_palette = CustomPalette(low ="lightgray", high = "#FF4500", mid = "#FFEF7D", k = 50)) +
    facet_wrap(.~seurat$orig.ident, ncol=2)
Plot_Density_Joint_Only(seurat, features = c("msx3", "fbln1"), custom_palette = CustomPalette(low ="lightgray", high = "#FF4500", mid = "#FFEF7D", k = 50)) +
    facet_wrap(.~seurat$orig.ident, ncol=2)

```


![image](https://github.com/satijalab/seurat/assets/134525955/8924cf06-dd05-4ff2-bea5-b1b614b995e9)

![image](https://github.com/satijalab/seurat/assets/134525955/26b3a7de-649c-4134-ac52-5c0b42d97309)

![image](https://github.com/satijalab/seurat/assets/134525955/21634253-309f-450e-abd5-10cd9ef837e8)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
