### ISSUE TITLE
Integer error Read10X and ReadMM

### ISSUE THREAD

**Issue by SpiffyLab** [satijalab/seurat#7374]
I am trying to load publicly available large-scale single cell data using Read10X and ReadMM in R: 
> pss.data <- Read10X(data.dir = "E:\\samples_feature_bc_matrix\\")
Error in scan(file, nmax = nz, quiet = TRUE, what = list(i = integer(),  : 
  scan() expected 'an integer', got '6986952691'

> matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
> mat <- readMM(file = matrix.path)
Error in scan(file, nmax = nz, quiet = TRUE, what = list(i = integer(),  : 
  scan() expected 'an integer', got '6986952691'

I receive a similar integer error as issue #4030, but I am lost with how to split the matrix into several parts. I tried to use the code from Ting-PKU within Python but I received an error. I am not as familiar with Python compared to R. Is there a way to solve this problem within R?

Any help would be greatly appreciated. Thanks!

**Comment by Marwansha** [comment]
can you let me know how u managed this 

hey, i have same error with reading the matrix, and i splited the matrix into 3 diffrent parts, but cant merge them back, any advices on this

x=readMM("/pasteur/zeus/projets/p02/evo_immuno_pop/single_cell/project/CZI_AfricanCellAtlas/data/GEX/11__cell_type_assignment_full/untitled_folder/counts_v2.mtx")
Error in scan(file, nmax = 1, what = what, quiet = TRUE, ...) :
scan() expected 'an integer', got '2267347504'

the head of the file have the format that people here mentioned is problematic
(base) [masharaw@maestro-submit ~]$ head /pasteur/zeus/projets/p02/evo_immuno_pop/single_cell/project/CZI_AfricanCellAtlas/data/GEX/11__cell_type_assignment_full/untitled_folder/counts_v2.mtx
%%MatrixMarket matrix coordinate real general
%
697321 14329 2267347504
1 3 1
1 5 6
1 6 1.05E2
1 7 1
1 9 2
1 10 3
1 11 3

i splitted the matrix to 3 files m1,m2,m3
but i still cant merge them do you know of a way to do this ?

matrices_123 <- rbind(m1, m2, m3)Error in .rbind2Csp(x, y) :
 Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
