### ISSUE TITLE
cellcell interaction or ligand receptor interaction analysis

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#7380]
Thank you for creating such a wonderful tool for spatial analysis. I was wondering at the very downstream analysis after integrating scRNAseq dataset - is there further deeper analysis into looking into cellcell interaction or ligand-receptor analysis? 

and if so - are those analysis at a single cell level after integration with scRNAseq dataset?

**Comment by saketkc** [comment]
Hi @chrkuo, currently there is no support for cell-cell interaction analyses in Seurat, but there are other tools that you should be able to use.

**Comment by chrkuo** [comment]
@saketkc do you have any recommended tools ? thank you
