### ISSUE TITLE
Set number of anchors used for integration in IntegrateLayers() Seurat v5

### ISSUE THREAD

**Issue by jeraldnoble** [satijalab/seurat#7382]
Hello,

Thanks for the v5 update, it seems to solve a sparse matrix error I was receiving using CCA integration in v4.

Is there a way to set the number of anchors used for IntegrateLayers()? In v4 I would set this in the anchor.features parameter of FindIntegrationAnchors().

**Comment by yuhanH** [comment]
hi @jeraldnoble 
There is no way to set the number of anchors used in our integration function. `anchor.features` is used to define what features used for integration. 
Currently, you can set `VariableFeatures` of your object to determine what features used for integration.

**Comment by jeraldnoble** [comment]
> hi @jeraldnoble There is no way to set the number of anchors used in our integration function. `anchor.features` is used to define what features used for integration. Currently, you can set `VariableFeatures` of your object to determine what features used for integration.

Per the documentation for FindIntegrationAnchors():
