### ISSUE TITLE
Merge data losing clustering information/sctransform results

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#7383]
Hi, 

I am trying to individually perform scTransform on all of my scRNAseq data samples -> merge them into one object and then run harmony. However, when I try to run harmony the sctransform clustering or reduction analysis is not there anymore. Is there a way to merge objects while still preserving the data? Additionally, when I merge data - the different sample identities are lost as well.

appreciate some assistance with this

**Comment by LinearParadox** [comment]
sctransform should replace the counts and is not a dimensionality reduction method. Harmony adjusts the principal components of the objects and creates a new set. They shouldn't be touching the same slot. Clustering should be provided after harmony. A basic workflow would be:
QC/Cell Filtering --> PCA --> Harmony --> UMAP/TSNE Dim reduction --> Find Neighbors --> Clustering --> Correct SCTransform --> Find Markers

**Comment by chrkuo** [comment]
> sctransform should replace the counts and is not a dimensionality reduction method. Harmony adjusts the principal components of the objects and creates a new set. They shouldn't be touching the same slot. Clustering should be provided after harmony. A basic workflow would be:
> 
> QC/Cell Filtering--> SCTransform --> PCA --> Harmony --> UMAP/TSNE Dim reduction --> Find Neighbors --> Clustering --> Correct SCTransform --> Find Markers

Thank you. @LinearParadox when i individually perform sctransform -> PCA and then merge objects then perform harmony. The merging steps eliminate the PCA analysis I've done and also eliminates all the sample identities from different patient. Is there a way to circumvent this?

**Comment by LinearParadox** [comment]
What I usually do is I add a column in the metadata that indicates sample. I don't see why you're performing PCA per patient, you should be performing PCA on the merged sample.

**Comment by chrkuo** [comment]
@LinearParadox  when i combine all SCTRANSFORMED objects into one object my variable feature column becomes 0. so i can't even run PCA on the merged sample. do you have any insights into how to fix this

**Comment by saketkc** [comment]
Hi @chrkuo, when merging different sctransfomr objects, you will have to define a set of variable genes. One way to do this is to use:

```r
var.genes <- FindIntegrationFeatures(sct.object.list)
VariableFeatures(sct.merged.object) <- var.genes
```

And then do `RunPCA` and `RunUMAP`.
