### ISSUE TITLE
std::bad_alloc error after running IntegrateData() in SCTransform v2 workflow (reopened #7354 )

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [satijalab/seurat#7387]
Dear @saketkc ,  

reopening #7354 issue as I am still facing the same issue.
I am getting an error after running IntegrateData() for 16 samples (~300k):
```
This warning is displayed once every 8 hours. 
Error: **std::bad_alloc**
Execution halted
Warning message:
system call failed: Cannot allocate memory  
```

I tried a workflow for the large datasets, which speeds up processing, but falls over when I run IntegrateData() generating the same error Error: **std::bad_alloc**, also tried to  Parallelization with future, same issue "system call failed: Cannot allocate memory"

My PC specifications:
RAM: 125G
CPU: 32
free disk space: 2.5T (67%)
Seurat v. 4.9.9.9040
object.size(anchorset) # 41683870864 bytes

thank you, 
Regards, 
Irina

**Comment by IrinaVKuznetsova** [comment]
tried to run it with 256Gb RAM, again raises an error "std::bad_alloc" after running  IntegrateData()

**Comment by saketkc** [comment]
Hi @IrinaVKuznetsova, can you paste your full code here? Which workflow for integration are you using?

**Comment by saketkc** [comment]
Closing as I haven't heard back. Please feel free to reopen if you are still facing issues.
