### ISSUE TITLE
merge back an SplitObject

### ISSUE THREAD

**Issue by mreza-ef** [satijalab/seurat#7388]
I used SplitObject to split a seurat object to sample_list. then I applied normalization on each individual object and then annotation of cells in each object. Now I am going to merge back my sample_list to one seurat object again. would you please advice me what would be the right way for doing this?

I already tried the below codes but both change the order of the cells! 
library(scCustomize)
combined_object <- scCustomize::Merge_Seurat_List(
  sample_list,
  add.cell.ids = NULL,
  merge.data = TRUE,
  project = "SeuratProject"
)

I also tried this:

for(i in 2:length(sample_list)){
  merged_seurat <- merge(merged_seurat, y = sample_list[[i]])
}

and my data is multiome data with 2 assays.

another and a more important question would be how can I reorder the colnames() of the new seurat object based on the original one?

thank you

**Comment by saketkc** [comment]
If you have a list of objects, you can use merge to do this:

```
merged.object <- merge(objects.list[[1]], objects.list[2:length(objects.list)])
```

To reorder the columns you can use `subset` and pass it the list of cells in the order you want them to be:

```
orderd.object <- subset(merged.object, cells = vector_of_cells_names)
```
