### ISSUE TITLE
For the function "FindClusters"

### ISSUE THREAD

**Issue by zorrodong** [satijalab/seurat#739]
Hi,

Thanks for the useful tool.

For the function "FindClusters", I wonder if I set the dim.use as Null, what has been used to construct the KNN graph ?

Looking forward to your reply, thanks very much !

Best,

Zorro
20180828

**Comment by leonfodoulian** [comment]
Hi @zorrodong,

If `dims.use = NULL` and `genes.use = NULL`, then the normalized gene expression matrix of variable genes will be used to construct the KNN graph. For more details, please check [lines 71 to 73 in snn.R](https://github.com/satijalab/seurat/blob/7618ac8798e2aefc509529f07af9d2836b96a1be/R/snn.R#L71-L73).

Best,
Leon

**Comment by zorrodong** [comment]
Thanks very much!

Best,

Zorro
