### ISSUE TITLE
can not install Seurat5

### ISSUE THREAD

**Issue by ZihaoXingUP** [satijalab/seurat#7390]
mv: cannot move '/tmp/RtmpeDvpPc/Rinst646d10412543/00LOCK-SeuratObject/00new/SeuratObject' to '/tmp/RtmpeDvpPc/Rinst646d10412543/SeuratObject': Permission denied
   ERROR:   moving to final location failed
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'Seurat' from GitHub:
  Failed to install 'SeuratObject' from GitHub:
  ! System command 'R' failed

**Comment by ZihaoXingUP** [comment]
> Hi, Seems like R doesn't have full permissions on the system you're using. Can you try adding the `--no-lock` argument: `remotes::install_github("satijalab/seurat", "seurat5", INSTALL_opts = c('--no-lock'))`
_**i use the root permission and '--no-lock', but it still can not install seurat5 on my system**._
![image](https://github.com/satijalab/seurat/assets/68001792/b26a8008-9566-4fe4-8cce-c85558615216)
![image](https://github.com/satijalab/seurat/assets/68001792/3d5e0fb1-0514-4321-adf9-51ef43fd84b6)

**Comment by WangJingwen21** [comment]
I met the same error.

**Comment by Streisenberg** [comment]
I am also facing the same issues. Moreover, I was able to use the SCP package from Hao Zhang in my project which contains some Seurat functions, but I'm unable to load it due to an error related to the SeuratObject dependency. Whenever I attempt to load the SCP package, I receive the following error message:

`Error: package or namespace load failed for 'SCP':
  object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'
`

Additionally, I tried to install the SeuratObject package using the following command:

`remotes::install_github("mojaveazure/seurat-object", "seurat5", INSTALL_opts = c('--no-lock'))
`

However, this installation attempt resulted in the following error same as here:

`
Error: Failed to install 'SeuratObject' from GitHub:
   ! System command 'R' failed
`
Could someone please provide guidance on how to resolve it? Thank you!

**Comment by mimisikai** [comment]
same issue here. try remotes::install_github("satijalab/seurat", "seurat5", INSTALL_opts = c('--no-lock')) but not work. return the same error: Error: Failed to install 'Seurat' from GitHub:
  Failed to install 'SeuratObject' from GitHub:
  ! System command 'R' failed

**Comment by Gesmira** [comment]
Hi @WangJingwen21 @Streisenberg @mimisikai, 
Can you share what is causing the error? Please rerun installation with quiet=FALSE and share the error message before the final `Error: Failed to install 'SeuratObject' from GitHub: ! System command 'R' failed` please. 

``` 
remotes::install_github("mojaveazure/seurat-object", "seurat5", quiet = FALSE)
```

**Comment by Streisenberg** [comment]
Dear @Gesmira,

When I run:

`remotes::install_github("mojaveazure/seurat-object", "seurat5", quiet = FALSE)`

I am receiving the error below:

`Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo mojaveazure/seurat-object@seurat5
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/nb/f7r_tjtx3nsbg1tlnpfbzsmcndrz1b/T/RtmpXv4JNa/remotesd8736af430a5/mojaveazure-seurat-object-c51dd86/DESCRIPTION’ ...
─  preparing ‘SeuratObject’: (401ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages (462ms)
         -----------------------------------
─  installing *source* package ‘SeuratObject’ ...
   ** using staged installation
   ** libs
   g++-13.1.6 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppEigen/include' -I/opt/R/arm64/include   -fPIC  -mtune=native -g -O2 -Wall -pedantic -Wconversion -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   /bin/sh: g++-13.1.6: command not found
   make: *** [RcppExports.o] Error 127
   ERROR: compilation failed for package ‘SeuratObject’
─  removing ‘/private/var/folders/nb/f7r_tjtx3nsbg1tlnpfbzsmcndrz1b/T/RtmpdIaAmd/Rinstd9cb7d334133/SeuratObject’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'SeuratObject' from GitHub:
  ! System command 'R' failed`

Thank you in advance for your help!

**Comment by Gesmira** [comment]
Hi @Streisenberg , 
Are you installing on mac? It seems that you are missing the make package. Some details for R installation [here](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf). And details on installing make on mac here: https://stackoverflow.com/questions/10265742/how-to-install-make-and-gcc-on-a-mac
