### ISSUE TITLE
Seurat v5 harmony integration workflow confusion

### ISSUE THREAD

**Issue by Dario-Rocha** [satijalab/seurat#7391]
When using harmony to integrate multiple samples into one dataset, PCA and variable features selection should be run on the merged raw data, as stated for example [here](https://hbctraining.github.io/scRNA-seq_online/lessons/06a_integration_harmony.html)

However, in the in the seurat v5 [sketch integration vignette](https://satijalab.org/seurat/articles/parsebio_sketch_integration), the PCA and variable feature selection is performed on the split dataset, which results in PCA and variable feature selection to be run for each layer separately.

Therefore, my question is which of protocol should be used:
JoinLayers > VariableFeatures > PCA > Harmony > ProjectIntegration (error)
JoinLayers > Split > VariableFeatures > PCA > Harmony > ProjectIntegration > ProjectData (warning)
JoinLayers > VariableFeatures > PCA > Harmony > Split > ProjectIntegration > ProjectData (warning)

And what is the meaning of this warning when running ProjectData

> Finding sketch neighbors
> Finding sketch weight matrix
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Transfering refdata from sketch
> All grouping variables have 1 value only. Computing across all cells.

This is my pipeline for running the harmony integration according the the [sketch integration vignette](https://satijalab.org/seurat/articles/parsebio_sketch_integration), which seems to be running just fine (with some workarounds due to known current bugs). Although there is this warning I am not exactly sure what is it about when running ProjectData (more details in the collapsible section):

<details>
  <summary>JoinLayers > Split > VariableFeatures > PCA > Harmony > ProjectIntegration > ProjectData (warning)</summary>
##Create Layered Seurat----
#from a list of bp cells matrices and a metadata dataframe with info on all the samples and cells

`a_seurat <- CreateSeuratObject(counts = a_rna_list, meta.data = a_metadata)`

##sketch seurat----
```
a_seurat <- NormalizeData(a_seurat)
a_seurat <- FindVariableFeatures(a_seurat, nfeatures = 2000)
```

###ignore tcr genes
```
a_seurat <- FindVariableFeatures(a_seurat)
temp_varfeats <- VariableFeatures(a_seurat)
temp_keepindex <- grepl("^trav|^trac|^traj|^trbv|^trbc|^trbj|^tradv", tolower(temp_varfeats))
temp_varfeats <- temp_varfeats[!temp_keepindex]
VariableFeatures(a_seurat) <- temp_varfeats

a_seurat <- SketchData(object = a_seurat,
                          ncells = 2000,
                          method = "LeverageScore",
                          sketched.assay = "sketch")

```
#B)Harmony 0----
#joining and resplitting layers, otherwise it gets bugged
```
a_integrated <- a_seurat
a_integrated <- JoinLayers(a_integrated)
a_integrated <- split(x = a_integrated, f = a_integrated$orig.ident)
```

#requirements
```
a_integrated <- FindVariableFeatures(a_integrated)
temp_varfeats <- VariableFeatures(a_integrated)
temp_keepindex <- grepl("^trav|^trac|^traj|^trbv|^trbc|^trbj|^tradv", tolower(temp_varfeats))
temp_varfeats <- temp_varfeats[!temp_keepindex]
VariableFeatures(a_integrated) <- temp_varfeats
a_integrated <- ScaleData(a_integrated)
a_integrated <- RunPCA(a_integrated)
```

#integration
```
a_integrated <- IntegrateLayers(
  object = a_integrated, 
  method = HarmonyIntegration,
  group.by = 'orig.ident',
  orig.reduction = "pca", 
  new.reduction = "harmony",
  verbose = FALSE
)
```

##UMAPS----
#restart R at this point, otherwise it gets bugged, no need clearing workspace, may need to save and reload seurat object

`a_integrated <- RunUMAP(a_integrated, dims = 1:30, return.model = T, reduction = 'harmony')`

##clustering----
```
a_integrated <- FindNeighbors(a_integrated, reduction = "harmony", dims = 1:30, )
a_integrated <- FindClusters(a_integrated, resolution = c(0.00, 0.02, 0.05, 0.10, 0.15, 0.20), random.seed	= 1234)
```

#rename clustering variable
```
temp_clusterindex <- grep('sketch_snn_res.', names(a_integrated@meta.data))
temp_clusternames <- names(a_integrated@meta.data)[temp_clusterindex]
temp_clusternames <- str_replace_all(string = temp_clusternames, pattern = 'sketch_snn_res.', replacement = 'har0_')
names(a_integrated@meta.data)[temp_clusterindex] <- temp_clusternames
names(a_integrated@meta.data)
```

#fix clusternames
```
for(temp_res in temp_clusternames){
  a_integrated@meta.data[[temp_res]] <- sprintf("%02s", as.character(a_integrated@meta.data[[temp_res]]))
}
```

##ProjectLabels----

#first project integration
```
a_integrated <- ProjectIntegration(object = a_integrated,
                                   sketched.assay = "sketch",
                                   assay = "RNA",
                                   reduction = "harmony")
```

#get cluster refdata
```
temp_clusterindex <- grep('har0', names(a_integrated@meta.data))
temp_clusternames <- names(a_integrated@meta.data)[temp_clusterindex]
temp_refdata <- as.list(temp_clusternames)
names(temp_refdata) <- paste0('full_', temp_clusternames)
```

#then project data
```
a_integrated <- ProjectData(object = a_integrated, 
                            sketched.assay = "sketch", 
                            assay = "RNA", 
                            sketched.reduction = "harmony.full",
                            full.reduction = "harmony.full", 
                            dims = 1:30, refdata = temp_refdata)
```

> Finding sketch neighbors
> Finding sketch weight matrix
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Transfering refdata from sketch
> All grouping variables have 1 value only. Computing across all cells.

#fix cluster names
```
temp_namesindex <- startsWith(x = names(a_integrated@meta.data), prefix = 'full') & !endsWith(x = names(a_integrated@meta.data), suffix = '.score')
temp_newnames <- names(a_integrated@meta.data)[temp_namesindex]
temp_newnames <- paste0('c', temp_newnames)
names(a_integrated@meta.data)[temp_namesindex] <- temp_newnames
```

#rerun umap
```
a_integrated <- RunUMAP(a_integrated, reduction = "harmony.full", dims = 1:30, reduction.name = "umap.full",
                        reduction.key = "UMAPfull_")

```
</details>

However, if I ommit the splitting step, when trying to ProjectIntegration, it fails, this would be the pipeline
JoinLayers > VariableFeatures > PCA > Harmony > ProjectIntegration (error)

```
a_integrated <- ProjectIntegration(object = a_integrated,
                                    sketched.assay = "sketch",
                                    assay = "RNA",
                                    reduction = "harmony")
```

> Warning: No layers found matching search pattern provided
> Warning: No layers found matching search pattern provided
> Warning: No layers found matching search pattern provided
> 0 atomic cells identified in the sketched.assay
> Correcting embeddings
> Warning: No layers found matching search pattern provided
> Error in atom.data[, atom.cells] : 
>   invalid or not-yet-implemented 'Matrix' subsetting
> In addition: Warning message:
> Layer ‘data.s367_cd25hi_t2’ is empty 

Additionally, re-splitting the object after performing the integration and before attempting to project the integration, makes it work again. This would the pipeline JoinLayers > VariableFeatures > PCA > Harmony > Split > ProjectIntegration > ProjectData (warning)

```
a_integrated <- split(a_integrated, a_integrated$orig.ident)
a_integrated <- ProjectIntegration(object = a_integrated,
                                  sketched.assay = "sketch",
                                  assay = "RNA",
                                  reduction = "harmony")
```

> 2000 atomic cells identified in the sketched.assay
> Correcting embeddings
> 1983 atomic cells identified in the sketched.assay
> Correcting embeddings
> Warning message:
> No columnames present in cell embeddings, setting to 'harmonyfull_1:50' 

and the ProjectData step works, albeit with a warning I don't really understand what does it mean

```
a_integrated <- ProjectData(object = a_integrated, 
                             sketched.assay = "sketch", 
                             assay = "RNA", 
                             sketched.reduction = "harmony.full",
                             full.reduction = "harmony.full", 
                             dims = 1:30, refdata = temp_refdata)
```

> Finding sketch neighbors
> Finding sketch weight matrix
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Transfering refdata from sketch
> All grouping variables have 1 value only. Computing across all cells.

**Comment by yuhanH** [comment]
hi @Dario-Rocha 
In the [sketch integration vignette](https://satijalab.org/seurat/articles/parsebio_sketch_integration), upon obtaining the sketched assay, we identify variable features based on the split data. However, the 'ScaleData' and 'RunPCA' functions are executed on the merged sketched data. The data is joined in the `ScaleData` step.

Following the integration step, we apply the 'JoinLayers' function. The goal is to facilitate differential analysis within the sketched assay. Therefore, if your analysis doesn't need to explore differential marker genes within the sketched assay, there's no requirement to run 'JoinLayers' or perform a split later.

Upon integration completion, you can proceed directly to the 'ProjectIntegration' and 'ProjectData' functions.
