### ISSUE TITLE
Checking the effect of regressing out a set of genes

### ISSUE THREAD

**Issue by pagarwal14** [satijalab/seurat#7392]
Hi,
I am trying to regress out a set of genes in an object that has been generated using the standard SCTransform workflow.  After using AddModuleScore() I use SCTransform for regressing out the genes using the command:
SCTransform(AlvFib, vars.to.regress = c("ECM_genes_regress1"))
I am using this object in another tool called CellChat, but I don't see the effect of the gene set regression.
1. How can I ensure that the regression has worked and the new expression data is in the Seurat object., i.e., which slot of SCT assay would the modified expression be found and how can I compare them to the previous data.
2. Do I need to RunPCA after SCTransform() for the desired effect?
3. What is the proper value for ctrl in AddModuleScore()
4. Is there any visualization I can do to see the effects of pre/post gene set regression.

Thanks!

**Comment by saketkc** [comment]
> How can I ensure that the regression has worked and the new expression data is in the Seurat object., i.e., which slot of SCT assay would the modified expression be found and how can I compare them to the previous data.

Regression using `vars.to.regress` will regress out these values from the `scale.data` slot of SCT assay.

> Do I need to RunPCA after SCTransform() for the desired effect?

Yes, all steps downstream of SCTransform() need to be rerun again (except when you are not using scale.data slot such as when running FindMarkers() or any other fucntion that relies on data slot)

> What is the proper value for ctrl in AddModuleScore()

This is subjective and depends on your analysis. The default of 100 should be good for most gene sets of similar size, but if you have a larger gene set you can try increasing this to match up to your input size.

> Is there any visualization I can do to see the effects of pre/post gene set regression.

You can visualize the `scale.data` slot using `DoHeatmap` or `Vlnplot(slot="scale.data")`.
