### ISSUE TITLE
convert Seurat object to SpatialExperiment

### ISSUE THREAD

**Issue by cathalgking** [satijalab/seurat#7393]
I know it is possible to convert a Seurat object to a SingleCellExperiment with the `as.SingleCellExperiment()` function but is it possible to convert a Seurat object to a SpatialExperiment object? I have a Seurat object that contains a 10x Visium experiment that I would like to convert to a SpatialExperiment object. thanks

**Comment by AustinHartman** [comment]
Hi @cathalgking, this isn't something currently on the road map but I agree would be useful in the future
