### ISSUE TITLE
Add an outline of the clusters

### ISSUE THREAD

**Issue by mdidish** [satijalab/seurat#7395]
Hello everyone
Does anyone know how to add an outline of the clusters when generating a plot using `FeaturePlot()`? Maybe through through ggplot2?
Best,
Marc

**Comment by longmanz** [comment]
hi,
Do you mean you want to add boundary line to each cluster in FeaturePlot? You will need to do it using ggplot2. Here is one package that allows you to do so: geom_mark_ellipse from https://ggforce.data-imaginist.com/reference/geom_mark_ellipse.html
