### ISSUE TITLE
Identification of population

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7396]
Hi 
i am running Seurat pipeline on a dataset which is T Cells.
With resolution 0.8 i identified  5 clusters which i named (0,1,2,3 ,4).This object is T .I was unable to assign proper identity to these clusters so i run this(T) as new object as XXX and tried to clustered with resolution of  0.5 resulting in 3 clusters 0,1 and 2.
Do it means the clusters all clusters in T object are of 3 types?

[2000.pdf](https://github.com/satijalab/seurat/files/11618564/2000.pdf)
[2001.pdf](https://github.com/satijalab/seurat/files/11618565/2001.pdf)

**Comment by mhkowalski** [comment]
Hi, it's hard to say if these are distinct cell types without knowing your data. I would recommend looking at genes that are differentially expressed in these clusters to see if you think they represent distinct cell types.
