### ISSUE TITLE
Discrepancy between UMAP and graph-based clustering after subset

### ISSUE THREAD

**Issue by ysbioinfo** [satijalab/seurat#7398]
Hi Seurat team,
I have an question related to the discrepancy between cluster and umap visualization.
At the beginning, I ran standard Seurat command lines and got some clusters:
```
data_all <- SCTransform(data_all, method = "glmGamPoi", variable.features.n = 2000)
data_all <- RunPCA(data_all, npcs = 30, ndims.print = 1:5, nfeatures.print = 5)
data_all <- FindNeighbors(data_all, reduction = "pca", dims = 1:30, nn.eps = 0.5)
data_all <- FindClusters(data_all, resolution = 0.6, n.start = 10)
data_all <- RunUMAP(data_all, dims = 1:30, min.dist = 0.3, umap.method = 'uwot')
```
I annotated these clusters to biologically meaningful cell types according to the marker genes (in this process I manually merged  some clusters since they shared similar marker genes). Finally, I got a picture as below
![umap_full](https://github.com/satijalab/seurat/assets/28683548/6fad2eb7-1103-4599-9d69-eb7a509d5092)

As you can see, the cluster result aligns with the UMAP visualization quite well: different clusters are well-separated after dimension reduction. Then, I wanted to focus on macrophages, i.e. the clusters with prefix “Mac”. Thus I subset the data and re-generate a UMAP figure using the command below:
```
cells <- row.names(data_all@meta.data)[grep('Mac', data_all@meta.data$annotation)]
data_sub <- subset(data_all, cells = cells)

data_sub <- FindVariableFeatures(data_sub, selection.method = "vst", nfeatures = 2000)
data_sub <- ScaleData(data_sub)
data_sub <- RunPCA(data_sub, npcs = 100, ndims.print = 1:5, nfeatures.print = 5)
data_sub <- RunUMAP(data_sub, dims = 1:30, umap.method = 'uwot')
```
And here comes my problem, the UMAP figure I got did not align with my annotated clusters. For example, "Mac_PPIF" and "Mac_NLRP3" mix together. 
![umap_subset](https://github.com/satijalab/seurat/assets/28683548/b494a643-9dd4-4fc1-8b9f-9951c873fccc)

Is such discrepancy caused by FindVariable, Scaledata and PCA after subsetting? From my perspective, since the cells are different now, so the variable features should also re-calculated. I think it will lead to more meaningful results. Do you think these repetitive analyses are essential? Look forward to your sound advice.

Thanks in advance.

Yang

**Comment by Gesmira** [comment]
Hi Yang, 
Yes, when you subcluster and recalculate the UMAP, it will look slightly different as the population of cells is different. For a thorough discussion on subclustering, please refer to https://github.com/satijalab/seurat/issues/1883

**Comment by ysbioinfo** [comment]
Thanks! Very helpful.

**Comment by apal6** [comment]
Hi,

I am doing a similar analysis where I am reclustering myeloid population. I am still confused as instead of getting a big cluster, I am getting distinct subclusters.  Same is happening with T cells. 

I haven't reintegrated my myeloid subset instead just applied normalisation, findVariableFeatures, scaling and them Umap. Would like to know if anyone could pinpoint the problem. 

Thank you,
Aastha

**Comment by apal6** [comment]
<img width="598" alt="Screenshot 2023-06-14 at 4 01 45 PM" src="https://github.com/satijalab/seurat/assets/127814354/50a62807-7ede-4da9-a2f4-07a7051c40df">

**Comment by apal6** [comment]
<img width="589" alt="Screenshot 2023-06-14 at 4 02 18 PM" src="https://github.com/satijalab/seurat/assets/127814354/1eb1480a-75ab-4ab0-9b6e-cb183f25a583">
