### ISSUE TITLE
Seurat doesn't seem to scale genes to unit variance before PCA.  But isn't scaling better?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#74]
Hello Seurat Team,

Before taking PCA, Seurat doesn't seem to be scaling the genes to unit variance. That is, the internal setting of ".scale" parameter in prcomp is left to default by Seurat, which is FALSE. I am wondering, is there a specific reason why Seurat doesn't scale genes to unit variance? Is this more advantageous?

The documentation of prcomp suggests that it is better to scale, although for compatibility with S, they have left the default to FALSE.

I see that "scaling" versus "not scaling" the genes to unit variance across all cells makes a significant difference in the downstream results, in TSNE, etc.

I do realize that the "do.scale" and "do.center" options in the Setup command of Seurat default to TRUE.  Even when these are TRUE, I still see a significant difference in the downstream results between explicitly setting the ".scale" option to TRUE or FALSE in the PCA command.  I don't understand why this would be so, given that the data should already be scaled and centered during the initial Setup process.

I would really appreciate your response regarding this aspect.

Thanks!

**Comment by CodeInTheSkies** [comment]
Hello Seurat Team,

Before taking PCA, Seurat doesn't seem to be scaling the genes to unit variance.  That is, the internal setting of ".scale" parameter in prcomp is left to default by Seurat, which is FALSE.  I am wondering, is there a specific reason why Seurat doesn't scale genes to unit variance?  Is this more advantageous?

The documentation of prcomp suggests that it is better to scale, although for compatibility with S, they have left the default to FALSE.

I see that "scaling" versus "not scaling" the genes to unit variance across all cells makes a significant difference in the downstream results, in TSNE, etc.

I would really appreciate your response regarding this aspect.

Thanks!

**Comment by julietchen** [comment]
Hi,
Just another seurat user here --
If you look at the PCA() or PCAFast() methods, you'll see that the data being used is`object@scale.data`, which is the scaled data set by setting do.scale=T during the Setup() call. There wouldn't be a need to set the .scale parameter in the prcomp() call because you're already using scaled data. I think that if you set .scale=T, you'd be scaling the scaled data. 

Hope that helps,
Julie
