### ISSUE TITLE
pairs for Seurat object

### ISSUE THREAD

**Issue by Elena983** [satijalab/seurat#7403]
Dear Seurat team
What would you suggest for performing pairs correlation analysis for some genes like here
![2023-06-01 16 21 25](https://github.com/satijalab/seurat/assets/68946912/e3151f03-590b-4f7f-819f-4b1316152d39)

**Comment by AustinHartman** [comment]
Hi, it is possible that these cells represent doublets if you observe significant counts for both Macrophage and T cell marker genes. I'd recommend checking additional cell type markers to develop a better sense as to whether the cell type annotations make sense.

**Comment by Elena983** [comment]
Thanks, Austin
But how to create the same plot? 
We usually use the pairs function for datasets, but what would be the case for Seurat object?
