### ISSUE TITLE
integerate scRNA seq with FACS

### ISSUE THREAD

**Issue by omaaribra** [satijalab/seurat#7404]
Hi— In Hao et al, Nat Biotech 2023, you discussed the possibility of integrating scRNA-seq with other single-cell proteomics such as CODEX or CITE-seq. Given the wide use of FACS, I am asking about the feasibility of integrating scRNA-seq and flow cytometry data. Is that possible and how? Is there a recommended analysis step that can help with such an analysis? Thanks!

**Comment by tomashhurst** [comment]
Hey @omaaribra , very cool question. Quick clarification: are you interested in integrating ADT data (i.e. protein expression) from say CITE-seq data, with FACS data? Or are you looking to integrate RNA expression data with FACS? For the former, yes this is definitely doable, we can give some guidance for doing this in Seurat. The later is a bit more complicated, we have some solutions but it's not straight forward.

**Comment by omaaribra** [comment]
Hi @tomashhurst, I am actually interested in the latter. Is it possible?

**Comment by yuhanH** [comment]
hi @tomashhurst 
Here is the related issue that we discussed about Cytof-RNA integration. 
https://github.com/satijalab/seurat/issues/5697

**Comment by kashishdoshi** [comment]
Hey @tomashhurst I was wondering how would you do the former? I would like to integrate CITE-seq ADT data with CyTOF data. I assume that the CyTOF and FACS data should have a similar workflow!
