### ISSUE TITLE
Question about the assay layer obtained by SCTransform used for SCENIC analysis.

### ISSUE THREAD

**Issue by gladelephant** [satijalab/seurat#7408]
Dear Seurat Team,
I want to ask a question about the assay layer obtained by SCTransform used for SCENIC analysis.
We commonly used codes such as "write.csv(t(as.matrix(sce@assays$RNA@counts))" to extract the raw count matrix as input for pySCENIC analysis. I understand that SCTransform could obtain 'corrected count' and used PrepSCTFindMarkers to ensure that the fixed value is dry properly, and the 'corrected count' layer is suitable for differentially expressed genes (DEG) analysis. 
I want to make sure——when doing the SCENIC analysis, is is more suitable to use the 'SCT@count' layer rather than the 'RNA@counts',  similar to DEG analysis input?  
Thanks a lot.

**Comment by saketkc** [comment]
I think this question is better suited for SCENIC authors. But to give some context, the `counts` slot of SCTransform stores the corrected counts, the `data` slot stores log1p(corrected counts).
