### ISSUE TITLE
FindMarkers: avg_logFC and others

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#741]
Hi all,
I have obtained some results from FindMarkers during an integrated analysis. I have clustered my cells first and then run FindMarkers within each cluster to see differencies between genotypes. My questions are related to avg_logFC:
1. Could you confirm that it is Napierian log (ln)? So, to get the fold change, I need to do: e^x?
2. How is it calculated? 
3. I have obtained some results where avg_logFC is i.e. 0.76, but I have pct.1=0.6 and pct.2=0. How is possible the calculation of avg_logFC if I have no expression in any cell from group 2? If there is no expression of this gene in any cell in group 2... there is no way to calculate a ratio of level of expression, right? I do not know how this avg_logFC is calculated.
4. To see significance, should I pay attention to p_val or p_val_adjusted? None of these values are log, right?
Thank you very much in advance!
Best,
Marina

**Comment by andrewwbutler** [comment]
Hi Marina,

1. Yes, we use natural log (ln) in this calculation. 
2. See #467 
3. See #467 
4. We perform a conservative bonferroni p-value adjustment to correct for multiple testing. p-values are not log-transformed.

**Comment by mvalenzuelav** [comment]
Thank you very much @andrewwbutler.
However, I can not answer question 3 because I think I do not understand the script for avg_logFC calculation due to my poor knowledge in Maths and R. Is it because the function only takes a subset of cells to calculate pct.1 and pct.2 but takes all cells to calculate avg_logFC? So that the gene could be expressed in some cells but not in the ones that have been taken to calculate pct.1 and pct.2?
I would be very grateful if I could understand only question 3. 
Thank you very much again in advance.
Marina

**Comment by andrewwbutler** [comment]
The same sets of cells are used for calculating both `pct.1/2` and `avg_logFC`. We calculate average log expression for any gene in each group as:
```R
 log(x = mean(x = expm1(x = x)) + pseudocount.use)
```
Note that the pseudocount is defined to be 1 by default. We then take the difference of these values (group1 - group2) to compute `avg_logFC`.

`ptc.1/2` are calculated as the percentage of cells in each group that the gene is detected. 

```R
x = apply(
      X = data.use[genes.use, cells.1, drop = F],
      MARGIN = 1,
      FUN = function(x) {
        return(sum(x > 0) / length(x = x))
      }
)
```

This value is rounded to the 3rd decimal so it's possible you have a gene that is only expressed in a very small percentage of cells (giving you pct.2=0) but is very highly expressed in the few cells that it's detected in so you see a non-zero `avg_logFC`.

**Comment by mvalenzuelav** [comment]
Of course, now I understand! It is because of the rounding that I am obtaining 0 in pct.2.
Thanks very much!

**Comment by cemalley** [comment]
Hi, adding my two cents for future visitors. It is confusing to calculate avg_logFC with sample 1 - sample 2. I believe it is the opposite in DESeq2. The sign should be reversed if you are reporting change from sample 1 to sample 2, unless I am mistaken.

**Comment by Crystalli2018** [comment]
I did a test on my data and it looks like which group is pct.1 and which is pct.2 depends on the names of the samples, it's listed in alphabetic order. For example, If  sample1 is named as B and sample2 as A, in the differential gene list, the avg_logFC is always A-B, and the violin plot by group is always A on the left and B on the right. If this is how it works, need to be careful how to name the samples.

**Comment by Crystalli2018** [comment]
Sorry, please ignore my previous post. It's s1-s2

**Comment by ClaireG18** [comment]
Hi,

could you clarify the following:
- does the function assume that the input object data are in log scale?
- is pseudocount.use employed to avoid log of zeros (or otherwise very small values)?
- why did you decide to use expm1 and not just exp?
- and more in general: why not calculating the average logFC using the means of the log transformed values?

Thanks a lot,

Claire

**Comment by andrewwbutler** [comment]
Issue seems to be resolved. The documentation has been updated in v3 to include a returned "Value" section which hopefully makes it more clear what `avg_logFC` is: 
> avg_logFC: log fold-chage of the average expression between the two groups. Positive values indicate that the gene is more highly expressed in the first group

**Comment by billgreenwald** [comment]
Hello,

Sorry to revive a closed issue.  I am getting extremely different fold changes between two methods, and after reading #467 its not clear why.

First method:
av=AverageExpression(combined,assays='RNA')
av=data.frame(apply(av[['RNA']],FUN=function(x) log(x+1),MARGIN=c(1,2)))
foldChanges=av$A-av$B

Second method:
foldChanges2=FindMarkers(combined, ident.1 = 'A', ident.2='B', min.pct = 0.25)$A_vs_B_avg_logFC

foldChanges and foldChanges 2 can be off by up to an entire log fold change (ie 2.3 fold different).
