### ISSUE TITLE
Intergrated scRNA ATacseq + HTO

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#7411]
Dear Team,

I have a 6 mouse 10x singlecell RNA+ Atacseq  sample multiplexed with AB.  I used cell ranger aRC pipeline for  generating count metric and Run CItseq over the HTO to create the matrix for the 3 Samples. I would like to perform analysis between the three samples  in three ways
1) with in RNASEQ,
2) with in ATACSEQ 
4) RNASEQ+ATAC.

My current issue is on how to integrate the 3 data sets(RNA+ATACSEQ+HTO). Should I need to use the Signac pipeline. if so How do I integrate HTO and demultiplex the samples. I was unable to find a vignette as such explaining the same from the Matrix being the starting input

Thanks in advance

**Comment by bassanio** [comment]
Can someone please guide me to a vignette or protocols on running the same please?

**Comment by mhkowalski** [comment]
You can add multiple assays to the same seurat object, as documented [here](https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html#wnn-analysis-of-10x-multiome-rna-atac) . You can then perform analysis using either assay separately or using a multimodal approach such as wnn. I'm not sure if this addresses your question, please comment if you have additional questions.

**Comment by bassanio** [comment]
@mhkowalski : Thank you for your response. I have seen the Document. For me its on how to integrate the Antibody output from citeseq (umi_count folder) and to do comparative analysis between the Samples
