### ISSUE TITLE
CreateSeuratObject from list of BPCells matrices ignores repeated barcodes

### ISSUE THREAD

**Issue by Dario-Rocha** [satijalab/seurat#7412]
Given a list of BPCells matrices, using CreateSeuratObject(counts = list_of_bpCells_matrices, meta.data = meta_data), if there are repeated colnames among different counts matrices, the resulting seurat object will have less columns than the sum of the number of columns of all the bpcells matrices. Changing the colnames of the bpcells matrices so that they are all unique and not shared with any of the other bpcells matrices fixes the issue.

**Comment by mihem** [comment]
True, I've reported the same issue here https://github.com/satijalab/seurat/issues/7318

**Comment by Gesmira** [comment]
This should now be fixed in the newest version of SeuratObject. Please clear your session, restart R, and reinstall with: 
`remotes::install_github("mojaveazure/seurat-object", "seurat5"`

**Comment by eheinrichs** [comment]
Im running into this same issue now using Seurat v 5.1.0 and Seurat Object v 5.0.2

All of the data is in the Seurat object, so if I iterate through the layers of the Seurat object and pull the barcodes from there I get the same number of barcodes as if I iterate through all of the original 10x barcode files. But if I just call colnames or look at the metadata length of the object I end up with much fewer. this number matches exactly the number of unique barcodes in the original 10x barcode files.
