### ISSUE TITLE
Can't install Siganc

### ISSUE THREAD

**Issue by fengweimin-maker** [satijalab/seurat#7416]
Hi，

After I installed Seurat v5 and Siganc, I can't library Siganc. It's seems something wrong in SeuratObject?
`library(Signac)
Error: package or namespace load failed for ‘Signac’:
 object ‘LayerData<-’ is not exported by 'namespace:SeuratObject'
In addition: Warning message:
package ‘Signac’ was built under R version 4.2.3 `

**Comment by Gesmira** [comment]
Seems like you need to install the v5 version of SeuratObject as well. 
`remotes::install_github("mojaveazure/seurat-object", "seurat5")`

**Comment by fengweimin-maker** [comment]
Hi,

Another error of install seurat-object，like the follow figure:
![image](https://github.com/satijalab/seurat/assets/60514168/0fcb3efc-fd2b-422e-964d-af8eb20ddaac)
