### ISSUE TITLE
Swapping reference and query gives different results in label transfer.

### ISSUE THREAD

**Issue by JoshuaCumming** [satijalab/seurat#7426]
I am trying to determine if cell states from cancer correspond to cell states in normal tissue. To do so I am trying label transfer. I have noticed that swapping the reference and query gives different results. Both objects have been integrated using the same rpca method and label transfer is being conducted on the "integrated" assay.

Here is the code:

```
anchors <- FindTransferAnchors(reference = Cancer.SO, query = Normal.SO, 
    dims = 1:10, reference.reduction = "pca", normalization.method = "LogNormalize")

Normal.SO <- MapQuery(
  anchorset = anchors,
  query =Normal.SO,
  reference = Cancer.SO,
  refdata = list(Cell_type = "integrated_snn_res.0.1"), reference.reduction = "pca")


anchors <- FindTransferAnchors(reference = Normal.SO, query = Cancer.SO, 
    dims = 1:10, reference.reduction = "pca", normalization.method = "LogNormalize")

Cancer.SO <- MapQuery(
  anchorset = anchors,
  query = Cancer.SO,
  reference = Normal.SO,
  refdata = list(Cell_type = "integrated_snn_res.0.1"), reference.reduction = "pca")

p1 <- DimPlot(Normal.SO, reduction = "umap", label = T, pt.size = 1) + ggtitle("Normal SO Integrated")
p2 <- DimPlot(Cancer.SO, reduction = "umap", label = T, pt.size = 1) + ggtitle("Cancer SO Integrated")
p3 <- DimPlot(Cancer.SO, group.by = "predicted.Cell_type", pt.size = 1) + ggtitle("Cancer SO Integrated Predicted ID Normal SO Integrated Reference")
p4 <- DimPlot(Normal.SO, group.by = "predicted.Cell_type", pt.size = 1) + ggtitle("Normal SO Integrated Predicted ID Cancer SO Integrated Reference")
plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2)
```
![image](https://github.com/satijalab/seurat/assets/43875547/d72ce418-20e8-4fd2-bce1-c24d6a15a8ed)

When using the cancer SO as a reference the predicted IDs correspond well to the clusters but the reverse isn't true. Any ideas why this is the case and how to select the best reference and query dataset? 

I am also curious if the label transfer should definitely be performed on the integrated or RNA assays could be used?

Thanks for any help!

**Comment by mhkowalski** [comment]
Hi-

You can use the integrated assay for the reference object, but I would use the RNA assay for the query in each case. It's hard to assess the results of label transfer without knowing what cell types these correspond to/ if they correspond to actual cell types. I would check marker genes of each cluster that you believe and see what's happening in each case.

**Comment by mea2712** [comment]
I will piggy back on this question as I am facing with the same situation.
My question is: 
how can I get the gene lists used to predict the labels? 
Thanks!
