### ISSUE TITLE
subsetting a large seuratv5 object to generate a new smaller seurat object

### ISSUE THREAD

**Issue by Dario-Rocha** [satijalab/seurat#7428]
For portability and testing issues, I need to subset a large seurat v5 object (1.3 million cells), to take, for example, 50.000 cells at random from that object. And I need to generate a new seurat object with all the stuff trimmed down to the selected cells, not add a new assay to the original large seurat object.
In seurat v4 I'd usually do this:

`small_seurat <- big_seurat[,sample(1:ncol(big_seurat), 50000, replace = FALSE]`

However, that approach in seurat v5 results in

```
<error/rlang_error>
Error in `subset.Seurat()`:
! No cells found
```

If instead I rename the idents of the large seurat object and the use the subset function, changing the Idents takes a huge amount of time, and then using the subset function takes even longer

```
Idents(big_seurat) <- big_seurat@meta.data$cell_id
temp_subsample_index <- sample(big_seurat@meta.data$cell_id, 50000, replace = FALSE)
small_seurat <- subset(big_seurat, idents = temp_subsample_index)
```

Is there a better way of doing this that I am completely missing?

**Comment by bumpingbell** [comment]
I also had this problem using Seurat 5 on a large dataset. Specifically, my dataset is merged from several smaller ones. I waited for the subset function to complete, but the output is a table with all values = NA. Furthermore, when I omitted several datasets to make the merged dataset smaller, the subset function works smoothly. I finally had to filter each of the datasets first before I merge them.

**Comment by yuhanH** [comment]
Hi, you can subset object based on the cell name in your object.
for example,
```
obj.sub <- subset(pbmc_small, cells = colnames(pbmc_small)[1:10])
```

**Comment by Dario-Rocha** [comment]
I am sorry, but the solution proposed is actually the issue in a large dataset. Trying to create a new seurat object by selecting a subset of the cells in a large seurat object using the subset function results in unusually long processing times and the output is a table with all values = NA
