### ISSUE TITLE
Workflow regarding multiple samples of scRNAseq data

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#7429]
hi seurat team,

I have 7 individual scRNAseq dataset that I am trying to analyze and combine. I have tried to individually filter them -> sctransform -> combine but after I combine them I lose all the variable features identified in the individual sctransformed object. 

I am wondering if you can give some guidance regarding what the best workflow is

**Comment by saketkc** [comment]
You can pass the list of SCTransform objects to `FindIntegrationFeatures`, which as explained in the [documentation](https://satijalab.org/seurat/reference/selectintegrationfeatures) will return top 3000 features after ranking them based on how often they appear as varaible across your 7 datasets.
