### ISSUE TITLE
Removing contaminating cells based on expression of a few specific genes?

### ISSUE THREAD

**Issue by Jessi44** [satijalab/seurat#743]
Hi,

I'm new to the world of scRNA seq data analysis and have been using Seurat to analyse some 10x data from CD4 T cells this past month. After looking at the expression of specific genes, I noticed that I have some contaminating CD8 T cells present. These contaminating CD8 T cells cluster together in my tSNE and I have removed them by removing the specific cluster using ident.remove. However, I understand that this isn't the best way to remove these cells. 

Is it possible to remove these cells by whether or not they express a few genes such as CD8a and CD8b?

Sorry if this is a repeat question, I haven't found any similar queries.

**Comment by pvimal** [comment]
I have the same problem as well! Anyone have any recommendations?

**Comment by andrewwbutler** [comment]
Hi,

The `SubsetData` function can be used to remove cells based on the expression of a gene or set of genes via the `subset.name` and `accept.low/high` parameters.

**Comment by Jessi44** [comment]
Thank you for your reply and suggestion.  I have been able to remove cells expressing one or another gene using the following: 

data1.1 <- FilterCells(data1, subset.names = c("Cd8a", "Cd8b1"), high.thresholds = c(1, 1))

However, this removes cells expressing either Cd8a or CD8b1 over a level of 1, which I find too stringent. What I want to be able to do is remove cells that are expressing Cd8a AND Cd8b1 over a level of 1. Is there a way to do this? Thanks for your help.
