### ISSUE TITLE
fail to analysis atac-seq layers for a multi-omics data in seurat V5

### ISSUE THREAD

**Issue by rdf1993** [satijalab/seurat#7435]
DefaultAssay(scData1)="ATAC"
scData1 <- RunTFIDF(scData1)
Error in as(object = object, Class = "CsparseMatrix") : 
  no method or default for coercing "Assay5" to "CsparseMatrix"

**Comment by Gesmira** [comment]
Hi, please use the ChromatinAssay format for scATAC-seq data. You can follow the [vignette here for creating your assay. ](https://stuartlab.org/signac/articles/pbmc_vignette.html)
