### ISSUE TITLE
reduction argument of FindNeighbors function and visualization of gene activity score

### ISSUE THREAD

**Issue by hiuchi** [satijalab/seurat#7436]
Thank you for providing us with the great package.
I have three questions.

1. [This vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) clusters cells based on their distance on the PCA even though they are visualized using the UMAP. This often results in cells that are far apart on the UMAP belonging to the same cluster. Why not cluster by distance on the UMAP plane?
2. After projecting two different scATAC-seq datasets on UMAP, is it appropriate to represent the gene activity score of a given gene by color? Is it misleading to color by gene activity on the same plane despite the batch effects?
3. I calculated gene activity with the GeneActivity() function without error and only got gene activity for half the number of genes in the RNA assay. Why is this?

Thank you for your cooperation.

**Comment by mhkowalski** [comment]
Hello, 

1. The UMAP representation is also calculated using the PCA embeddings. It wouldn't make sense to cluster on a 2D representation of PCA space. I don't see many examples where cells are in the same cluster but are far apart on the UMAP.
2. Yes, you might check each batch individually to see if there are substantial batch effects. 
3. The missing genes might not be protein-coding or may not be present in the annotation you are using (see [here](https://github.com/stuart-lab/signac/discussions/1132)).

Hope this is helpful!
