### ISSUE TITLE
DE analysis p-adjusted value question

### ISSUE THREAD

**Issue by kitzcode** [satijalab/seurat#744]
Hi!
I have a question about the different tests that can be applied to get differentially expressed genes. Do all of them use Bonferroni correction? MAST and DESeq2 usually use FDR, right? So I was wondering if that was implemented here as well.

Thanks

**Comment by andrewwbutler** [comment]
Hi,

The Bonferroni correction is applied uniformly across all tests. The uncorrected p-values are also returned though if you would like to use your preferred correction method.
