### ISSUE TITLE
Previous code failing to replicate result (UMAP not separating clusters properly)

### ISSUE THREAD

**Issue by RandomRipples** [satijalab/seurat#7449]
I had earlier (1 year ago) used a certain workflow (see Workflow 1 below) that had resulted in a proper UMAP (see UMAP 1 below) with well-separated clusters. Now, when I am loading my previously saved rds file ("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 03 March UHN/Patient heterogeneity heatmaps/lung.bcells.sct.rds"), I am able to get the same UMAP (UMAP 1) but if I re-run the exact same code from scratch, my clusters are not separating - I am getting only 2 instead of 4 clusters and the cells are all mixed up with each other (see UMAP 2 below). 
I am aware that every time you run the code, the UMAP will look different (unless you use a seed code). That is not the problem I am facing here. The problem is the UMAP is unable to separate the clusters at all. Please note this is happening to all my previous files - the data that generated 6 or 7 well-separated tight clusters is now only giving 2-3 spread-out mixed-up clusters that are clearly not right. Can you please let me know what is going wrong and how I can replicate my previous result (it is okay if the UMAP looks different as long as it gives me well-separated proper number of clusters)? Thank you so much for your help. 

**Workflow 1**

# Load Libraries 

library(devtools)
library(tidyverse)
library(Seurat)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(SoupX) # https://cran.r-project.org/web/packages/SoupX/vignettes/pbmcTutorial.html
library(SingleR)
library(patchwork)
library(sctransform) # https://satijalab.org/seurat/articles/sctransform_vignette.html
library(RColorBrewer)## https://satijalab.org/seurat/archive/v3.0/integration.html# Set working directory
library(viridis)
library(pheatmap)
library(EnhancedVolcano)
library(readxl)

# Set working directory

setwd("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 03 March UHN/Patient heterogeneity heatmaps")

# Load required B cell objects (all lung samples only) 

clad53_lung_B_cells <- readRDS("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 01 Jan UHN/Lung PBMC SCT Integrated Analysis 2/Files/clad53_lung_B_cells.rds")
clad62_lung_B_cells <- readRDS("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 01 Jan UHN/Lung PBMC SCT Integrated Analysis 2/Files/clad62_lung_B_cells.rds")
clad63_lung_B_cells <- readRDS("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 01 Jan UHN/Lung PBMC SCT Integrated Analysis 2/Files/clad63_lung_B_cells.rds")
clad64_lung_B_cells <- readRDS("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 01 Jan UHN/Lung PBMC SCT Integrated Analysis 2/Files/clad64_lung_B_cells.rds")
clad68_lung_B_cells <- readRDS("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 01 Jan UHN/Lung PBMC SCT Integrated Analysis 2/Files/clad68_lung_B_cells.rds")

# Check active assay for each B cell object and change to RNA assay if needed

DefaultAssay(clad53_lung_B_cells) <- "RNA"

## All other B cell objects are already at RNA assay

# Merge all B cell objects 

lung.bcells <- merge (`clad53_lung_B_cells`, y = c(`clad62_lung_B_cells`, `clad63_lung_B_cells`, `clad64_lung_B_cells`, `clad68_lung_B_cells`), 
                           project = "lung.scintegration")

lung.bcells

# Add sample name to metadata

lung.bcells = AddMetaData(object = lung.bcells, metadata=substr(colnames(lung.bcells), 1, 12), col.name='Sample')

## SCT integration 

lung.bcells.list <- SplitObject(lung.bcells, split.by = "Sample")
lung.bcells.list <- lapply(X = lung.bcells.list, FUN = SCTransform)
features <- SelectIntegrationFeatures(object.list = lung.bcells.list, nfeatures = 3000)
lung.bcells.list <- PrepSCTIntegration(object.list = lung.bcells.list, anchor.features = features)

lung.bcells.anchors <- FindIntegrationAnchors(object.list = lung.bcells.list, normalization.method = "SCT",
                                                   anchor.features = features)
lung.bcells.sct <- IntegrateData(anchorset = lung.bcells.anchors, normalization.method = "SCT")

# Save rds 

saveRDS(lung.bcells.sct, file = "C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 03 March UHN/Patient heterogeneity heatmaps/lung.bcells.sct.rds")

# Read rds if needed 

lung.bcells.sct <- readRDS("C:/Users/burma/OneDrive - UHN/UHN Work/Data Collection UHN/2022 03 March UHN/Patient heterogeneity heatmaps/lung.bcells.sct.rds")

# Make sure default assay is integrated assay (if not, change to integrated assay)

lung.bcells.sct

# Run PCA, UMAP and make Dim Plots 

lung.bcells.sct <- RunPCA(lung.bcells.sct, verbose = FALSE)
lung.bcells.sct <- RunUMAP(lung.bcells.sct, reduction = "pca", dims = 1:30)
lung.bcells.sct = FindNeighbors(lung.bcells.sct)
lung.bcells.sct = FindClusters(lung.bcells.sct, resolution = 0.4)

DimPlot(lung.bcells.sct, reduction = "umap")

**UMAP 1**

![image](https://github.com/satijalab/seurat/assets/136590946/cd7438a8-de93-4b3e-838c-6f77a4ef274e)

**UMAP 2**

![image](https://github.com/satijalab/seurat/assets/136590946/13496ed4-a5b4-419f-9089-1290fda01cdc)

Please let me know if I can provide any other information to sort this out!

Thank you so much for your help.

**Comment by longmanz** [comment]
Hi both,
This is generally hard to debug from our end. 
We did not introduce any change to SCTransform v1 integration (the one you were using) between V4.0 and V4.3, but the dependent packages of the UMAP (e.g., uwot) have been updated during this time. Any change in their settings will produce different UMAP results. 
I would recommend you focus on validating whether these clusters are real or not, by running Findmarkers(..., assay = 'RNA', ...) between the different clusters. Once you obtain some cluster marker genes, you might have a better clue on if the clustering really makes sense (especially the purple cluster in your previous UMAP). 
In addition, you may also try the latest SCTv2 in Seurat V4.3 for integration (see https://satijalab.org/seurat/articles/sctransform_v2_vignette.html). 
I will close this issue for now, and if you find any further issue, I will re-open it.
