### ISSUE TITLE
Error in Seurat object when trying to integrate 10X Visium data 

### ISSUE THREAD

**Issue by krigia** [satijalab/seurat#7450]
Hello Seurat team,

I am working to integrate 10X Visium data using Seurat.
I follow the instructions from this link https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_07_spatial.html#Integration

I work with "S4 object of class Seurat" Seurat objects from two tumor Visium samples generated by using STutility/Seurat.
I get the following error and warnings:

st.list <- PrepSCTIntegration(object.list = st.list, anchor.features = st.features,
+                               verbose = FALSE)
> int.anchors <- FindIntegrationAnchors(object.list = st.list, normalization.method = "SCT",
+                                       verbose = FALSE, anchor.features = st.features)
  |                                                  | 0 % ~calculating  Warning: Different cells and/or features from existing assay SCT
Warning: Different cells and/or features from existing assay SCT
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=17s  
**Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.**
> neuroblastoma_F1_2.integrated <- IntegrateData(anchorset = int.anchors, normalization.method = "SCT",
+                                                verbose = FALSE)
**Warning: Different cells and/or features from existing assay SCT
Warning: Different cells and/or features from existing assay SCT**
**Error in validObject(.Object) :
  invalid class “Assay” object: Keys must be a one-length character vector**

I would greatly appreciate your feedback and help. 
Thank you.

**Comment by rachelzoeb** [comment]
I am having this same error when integrating a regular 10X Seurat object list. 

Integrating data
Error in validObject(.Object) :
  invalid class �<80><9C>Assay�<80><9D> object: Keys must be a one-length character vector
Calls: IntegrateData ... TransformDataMatrix -> new -> initialize -> initialize -> validObject
Execution halted

> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /Fingerlin/home/blumhagenr/software/miniconda3/envs/seurat5/lib/libopenblasp-r0.3.21.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: America/Denver
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Matrix_1.5-4.1          dplyr_1.1.2             SeuratObject_4.9.9.9084
[4] Seurat_4.3.0

**Comment by AustinHartman** [comment]
Hi @krigia, before performing integrations try calling `obj <- UpdateSeuratObject(obj)` to ensure the version of the Seurat package loaded matches with the version of the Seurat object analyzed.

**Comment by krigia** [comment]
Hi @AustinHartman 

I did what you suggest and I get the following error:

> st.list <- PrepSCTIntegration(object.list = st.list, anchor.features = st.features,
+                               verbose = FALSE)
> int.anchors <- FindIntegrationAnchors(object.list = st.list, normalization.method = "SCT",
+                                       verbose = FALSE, anchor.features = st.features)
  |                                                  | 0 % ~calculating  Warning: Different cells and/or features from existing assay SCT
Warning: Different cells and/or features from existing assay SCT
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=20s  
Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
> int.anchors <-UpdateSeuratObject(int.anchors)
**Error: We are unable to convert Seurat objects less than version 2.X to version 3.X
Please use devtools::install_version to install Seurat v2.3.4 and update your object to a 2.X object**

Then I removed Seurat package and installed Seurat v2.3.4:
**install.packages('devtools')
devtools::install_version(package = 'Seurat', version = package_version('2.3.4'))**

I closed R and open it again. But I continue to get the same error: **We are unable to convert Seurat objects less than version 2.X to version 3.X
Please use devtools::install_version to install Seurat v2.3.4 and update your object to a 2.X object**

Please advise. I have some critical deadlines to complete the project. Thank you.

**Comment by krigia** [comment]
Hi @AustinHartman 

When I try to install Seurat v2.3.4,

I get the following error:
> devtools::install_version(package = 'Seurat', version = package_version('2.3.4'), force = TRUE)
Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/Seurat/Seurat_2.3.4.tar.gz
Skipping 2 packages not available: multtest, SDMTools
Installing 4 packages: multtest, mutoss, metap, SDMTools
Installing packages into ‘/Users/genomelab/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
Warning: dependency ‘multtest’ is not available
trying URL 'https://cran.rstudio.com/src/contrib/mutoss_0.1-13.tar.gz'
Content type 'application/x-gzip' length 907567 bytes (886 KB)
==================================================
downloaded 886 KB

trying URL 'https://cran.rstudio.com/src/contrib/metap_1.8.tar.gz'
Content type 'application/x-gzip' length 1097503 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

ERROR: dependency ‘multtest’ is not available for package ‘mutoss’
* removing ‘/Users/genomelab/Library/R/x86_64/4.3/library/mutoss’
ERROR: dependency ‘mutoss’ is not available for package ‘metap’
* removing ‘/Users/genomelab/Library/R/x86_64/4.3/library/metap’

The downloaded source packages are in
‘/private/var/folders/tw/p_th3mmn3hl7_cl89xq8z4yr0000gs/T/RtmprjKRK1/downloaded_packages’
Installing package into ‘/Users/genomelab/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
ERROR: dependencies ‘SDMTools’, ‘metap’ are not available for package ‘Seurat’
* removing ‘/Users/genomelab/Library/R/x86_64/4.3/library/Seurat’
Warning messages:
1: packages ‘multtest’, ‘SDMTools’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
2: In i.p(...) : installation of package ‘mutoss’ had non-zero exit status
3: In i.p(...) : installation of package ‘metap’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘/var/folders/tw/p_th3mmn3hl7_cl89xq8z4yr0000gs/T//RtmprjKRK1/remotes17d2c5a596040/Seurat’ had non-zero exit status

Thank you.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
