### ISSUE TITLE
MAST within Seurat: need to convert data to log2 counts per million (log2(CPM + 1))?

### ISSUE THREAD

**Issue by mykoka** [satijalab/seurat#7454]
Hello,  I would appreciate if anybody can clarify a doubt I have got
I am running MAST in the FindMarkers within Seurat directly from my Seurat object.
```

DEGA_B<- FindMarkers(all_samples, ident.1 = "A", 
                                     ident.2="B", group.by ="phenotype",
                                     subset.ident = c("C0", "C1", "C2", "Th2", "C6"), test.use = "MAST",
                                     logfc.threshold = 0.25)
```
I read in many papers that they convert data to log2 counts per million (log2(CPM + 1)) before running MAST. I assume this is not needed if I run it within Seurat right?
Many thanks!

**Comment by longmanz** [comment]
Hi,
Yes. You do not need to do conversion by yourself if this is implemented in MAST. 
Seurat FindMarkers() for MAST is just a wrapper, and it will pass the count matrix to MAST, and MAST will perform the conversion.
