### ISSUE TITLE
RunUMAP: Error in x2set(Xsub, n_neighbors, metric, nn_method = nn_sub, n_trees,  :    Non-finite entries in the input matrix 

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#7457]
Hello! I've been encountering issues when I upgraded to Seurat 5 and then decided to revert to my previous version v4.3.0. I have experienced issues/errors related to PCA analysis.

Now at the RunUMAP step, I have this error:

```
Error in x2set(Xsub, n_neighbors, metric, nn_method = nn_sub, n_trees,  : 
  Non-finite entries in the input matrix
```
![image](https://github.com/satijalab/seurat/assets/68268222/cc26021a-3f66-4cdf-afe5-2353d2b6f046)

Here's a downsampled Seurat object I'm processing for your perusal: https://drive.google.com/file/d/1bpmHY_AhJ0Dvjuaq5FSbWgC2S4MZowMj/view?usp=sharing

Hoping for any help. Thank you!!!

**Comment by saketkc** [comment]
Hi @levinhein, can you re-run the PCA step? The calculated PCA embeddings in your object seem a bit weird.

```
seurat <- RunPCA(seurat)
seurat <- RunUMAP(seurat, dims=1:30)

```

resulted in 
![image](https://github.com/satijalab/seurat/assets/682153/8076bae3-e600-470f-8961-e40d6955eedd)

**Comment by levinhein** [comment]
Hi @saketkc when I run that, or when I don't put specify npcs less than 50 in `RunPCA()`, I always encounter `Error in irlba` which doesn't get resolved. Please see: https://github.com/satijalab/seurat/issues/7451 

Maybe you have a solution to this issue? It all started when I updated to seurat v5.

**Comment by CongjiaMa** [comment]
Hi @levinhein,I also encountered the same problem during calculation. How did you solve it in the end?

**Comment by JackLMc** [comment]
Commenting to bump, I have encountered the same issue.

**Comment by CongjiaMa** [comment]
谢谢，已收到

**Comment by ChawlaP1994** [comment]
Can someone put up a script/code that worked with this issue: RunUMAP: Error in x2set(Xsub, n_neighbors, metric, nn_method = nn_sub, n_trees, : Non-finite entries in the input matrix

I tried downgrading the Seurat to from v5 to v4.4.0 but still the same issue

**Comment by CongjiaMa** [comment]
谢谢，已收到
