### ISSUE TITLE
Rename Ensembl id to Gene Name

### ISSUE THREAD

**Issue by ryf0810** [satijalab/seurat#7460]
Hi Author,

I downloaded two Seurat objects from the online resources, where the RNA assay only contains feature in ensembl id format. I get the corresponding gene names using getBM() function from biomaRt library. However when I tried to replace the ensembl

gene.fetal <- getBM(
  attributes = c('ensembl_gene_id', 'external_gene_name'),
  filters = 'ensembl_gene_id',
  values = rownames(fetal.kidney),
  mart = ensembl.con
)
dict <- setNames(gene.fetal$external_gene_name, gene.fetal$ensembl_gene_id)
gene.names.fetal <- unname(dict[rownames(fetal.kidney)])
rownames(fetal.kidney) <- gene.names.fetal

Then, Warning: Renaming features in v3/v4 assays is not supported, this Error popped up. Are there any way to map the gene names to replace ensembl id? Thank you!

Best!

**Comment by denvercal1234GitHub** [comment]
Hi @ryf0810 - Could you specify the code you used? Like `rownames(SeuratObj[[RNA]]$data < new_gene_names_vector`?

**Comment by samyuktha-suresh** [comment]
Hello @ryf0810 , could you please share your code for the same? Thanks!

**Comment by szhaoaf** [comment]
The warning could be solved by rename the layer data as suggested.

See below: 

```
> Liver_FACS <- readRDS("/Users/Desktop/ab2c1368-ab62-44a2-8bb2-18e8999acd64.rds")
> head(rownames(Liver_FACS))
[1] "ENSMUSG00000029422" "ENSMUSG00000076126" "ENSMUSG00000049036" "ENSMUSG00000029577" "ENSMUSG00000040746"
[6] "ENSMUSG00000020590"
> rownames(Liver_FACS@assays[["RNA"]]@counts) <- new_name$id2
> rownames(Liver_FACS@assays[["RNA"]]@data) <- new_name$id2
> head(rownames(Liver_FACS))
[1] "Rsrc2"   "Mir669b" "Tmem121" "Ube3b"   "Rnf167"  "Snx13"  
```

Remember to use  "@assays[["RNA"]]@counts" instead of [['RNA']]$counts, otherwise it will give you the errors:

```
> rownames(Liver_FACS[["RNA"]]@data) <- new_name$id2

Error in validObject(object = value) : 

  invalid class “Assay” object: 1: 'counts' must have the same features as 'data'

invalid class “Assay” object: 2: meta.features' must have the same features as 'data'
```

Bests,
生信分析那点事儿-公众号

**Comment by samyuktha-suresh** [comment]
Thanks a lot, will try this out.

Sam
