### ISSUE TITLE
Can't Install Seurat5 in kaggle

### ISSUE THREAD

**Issue by MohammadIzadi** [satijalab/seurat#7461]
Hi,
Thanks for developing Seurat. It is very useful and interesting.
When I want to install Seurat5 in Kaggle, I get the error that see in attached picture. Can you help me, please?

![image](https://github.com/satijalab/seurat/assets/84282111/dc4ae24d-da68-40d3-b3a8-86bb5e8c104f)
![image](https://github.com/satijalab/seurat/assets/84282111/23b327f3-cc18-4e84-b3c1-34b7e724497f)

**Comment by AustinHartman** [comment]
Thanks for raising this. I just pushed a fix to SeuratObject which should solve this installation issue.

**Comment by MohammadIzadi** [comment]
Sorry, It's not working. Can you help me please?
