### ISSUE TITLE
`FindBridgeTransferAnchors` does not find "PrepareBridgeReference" command sometimes

### ISSUE THREAD

**Issue by Zepeng-Mu** [satijalab/seurat#7464]
Hello,
I'm trying to run dictionary learning using my own query and reference data and using the 10x multiome data as bridge. I encountered this error in `FindBridgeTransferAnchors`:

```
<simpleError in Command.Seurat(object = extended.reference, command = "PrepareBridgeReference"): PrepareBridgeReference has not been run or is not a valid command.>
```
The error message says `PrepareBridgeReference` has not been run but in fact I have run it. I checked SeuratObject package and `Command.Seurat` uses `slot` to pull the commands that's been run. Doing the same thing on my extended ref, I realized that the command is actually called `Seurat..PrepareBridgeReference` whereas `FindBridgeTransferAnchors` function only checks for `command = "PrepareBridgeReference"`.

After some digging around, I found this is because I used `Seurat::PrepareBridgeReference` instead of `PrepareBridgeReference` in my function call. I feel like this might be a bit hard trouble shoot and I wonder whether there might be a better way to handle this.

Thanks!

**Comment by yuhanH** [comment]
hi @Zepeng-Mu 
Thank you for reporting this bug. We fill fix it soon.

**Comment by yuhanH** [comment]
Thank you for reporting this bug. It is fixed in the latest version of seurat5 branch.
