### ISSUE TITLE
Seurat v5 use merge seurat error in IntegrateLayers

### ISSUE THREAD

**Issue by Liripo** [satijalab/seurat#7467]
```R
library(Seurat)
options(Seurat.object.assay.version = "v5")

Baron <- Seurat::Read10X("./data/umi_counts/Pancreas_datasets/Baron_human")
Baron_obj <- CreateSeuratObject(Baron)
Baron_obj$dataset <- "Baron"

Muraro <- Seurat::Read10X("./data/umi_counts/Pancreas_datasets/Muraro/")
Muraro_obj <- CreateSeuratObject(Muraro)
Muraro_obj$dataset <- "Muraro"

obj <- merge(Baron_obj,Muraro_obj)

obj <- NormalizeData(obj) |> 
  FindVariableFeatures(selection.method = "vst", nfeatures = 2000)

obj <- ScaleData(obj)
obj <- RunPCA(obj)

obj <- IntegrateLayers(object = obj, 
                       method = RPCAIntegration,
                       orig.reduction = "pca", 
                       verbose = F)
```
When I use the above process, I encounter the following error:
```R
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing
```
I seem to have to do the following, first join and then split.(Is this expected behavior?)
```R
obj <- merge(Baron_obj,Muraro_obj)
obj <- JoinLayers(obj)

obj <- split(obj,f = obj$dataset)
```

My seurat version is `4.9.9.9041`.

**Comment by rsatija** [comment]
We will take a look at this next week, in the mean time could you provide a link to the Baron and Muraro matrices (Dropbox is fine) for testing?

**Comment by Liripo** [comment]
Great to hear that, link below：

Baron_human：&nbsp;https://drive.google.com/file/d/1H_VnC9RXm0kOe3sFgVUAejMAbayLKEUP/view?usp=drive_link

Muraro：https://drive.google.com/file/d/1bkOMuST27p00Qhe6fUn2FwOVlwzAX4IS/view?usp=drive_link









                       
原始邮件
                       
                     

发件人："rsatija"< ***@***.*** &gt;;

发件时间：2023/7/1 3:29

收件人："satijalab/seurat"< ***@***.*** &gt;;

抄送人："Liripo"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [satijalab/seurat] Seurat v5 use merge seurat error inIntegrateLayers (Issue #7467)




 
We will take a look at this next week, in the mean time could you provide a link to the Baron and Muraro matrices (Dropbox is fine) for testing?

**Comment by Gesmira** [comment]
Hi @Liripo, 
This has been fixed in the newest version of Seurat v5! Please clear and restart your R session and install using: 

```
remotes::install_github("mojaveazure/seurat-object", "seurat5", quiet = TRUE)
remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)
```
