### ISSUE TITLE
Phenograph clustering using a Seurat object

### ISSUE THREAD

**Issue by zoqaiyum** [satijalab/seurat#7469]
Hello, 

I understand that the FindClusters() function is able to provide clustering based on reductions such as UMAP, tSNE, and PCA. I was wondering if there's any way to perform clustering using Phenograph? The use of supplemental packages such as Rphenograph would be helpful as a guide. 

Thanks!

**Comment by GeorgeAlehandro** [comment]
Hello, I am using this code in order to find the clusters of a Seurat object based on scaled RNA expression via Phenograph. 

```{r}
data <- as.matrix(t(seurat_obj@assays$RNA@scale.data))
Rphenograph_out <- Rphenograph(data, k = 45)
seurat_obj$phenograph_cluster <- "placeholder"
seurat_obj$phenograph_cluster <- factor(membership(Rphenograph_out[[2]]))
```
Hope that is helpful to your case!
Best.

**Comment by zoqaiyum** [comment]
Hi @GeorgeAlehandro 

I am just running the code now, however my input data has around 40,000 rows and 2,000 columns. How long did it take you to run your codes and how big was your data?

Thanks!

**Comment by zoqaiyum** [comment]
Hi @GeorgeAlehandro 

It took me a total of about 1 hr 8 mins. Would you be able to please provide an example of a code you ran to visualize the phenograph clusters on umap_1 and umap_2 axes?

Thanks so much!

**Comment by GeorgeAlehandro** [comment]
Hello @zoqaiyum 

My dataset is relatively very small (I am comparing three sub-populations of CD8), it consists of 2100 cells. The clustering took ~5 seconds.
In order to visualize the clusters on the UMAP (Assuming you saved the clusters in $phenograph_cluster like in my example above) 
you can use this: 
```{r}
DimPlot(seurat_obj, label = TRUE, repel = TRUE, label.size = 2.5, group.by ="phenograph_cluster")
```

Best

**Comment by zoqaiyum** [comment]
Thanks so much @GeorgeAlehandro
