### ISSUE TITLE
error when install the v5 seurat using  remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)

### ISSUE THREAD

**Issue by honghh2018** [satijalab/seurat#7470]
Hi,
    I try to install the latest v5 seurat failed, the error showing below,
    how to fix this error in this situation?
Enter one or more numbers, or an empty line to skip updates: 
Error: Failed to install 'Seurat' from GitHub:
  ! System command 'R' failed
Best,
hanhuihong

**Comment by Gesmira** [comment]
Hi, 
Have you installed the v5 version of SeuratObject? 
Furthermore, can you include the output of the error message before the last one you showed so we can actually see what went wrong? Be sure to set the parameter `quiet = F` during install.

**Comment by Gesmira** [comment]
Closing for now due to no response. Feel free to reopen if the issue persists.

**Comment by honghh2018** [comment]
The seurat v5 had been solved myself, it was a library dependence issue.
