### ISSUE TITLE
change angle of text(not in axis X or Y) in violin plot 

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#7471]
Hi, Dear Seurat team:
I'm drawing a violin plot. As for the graph, the X axis is cell type; Y axis: left side of the graph is expression level(like 2, 3, 4), right side of the graph is gene name. The name is displayed vertically but very small, I want to adjust it to horizontal(or 90 degree angle). I used theme function and set that **theme(axis.text.y.right = element_text(angle = 0))** or **theme(axis.text.y.right = element_text(angle = 90))**, the direction of text didn't change.
Can you give me some suggestions?

Thank you very much,
Claire

**Comment by AustinHartman** [comment]
Hi, if you want to rotate the title of the y-axis use `axis.title.y.left` and if you intend to rotate the y-axis labels use `axis.text.y.left`. Keep in mind, if multiple violin plots are generated after calling `VlnPlot` once (i.e. by specifying multiple `features`), you will have to update the labels of each individual plot.
