### ISSUE TITLE
How to convert H5Seurat to H5ad Visium data

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [satijalab/seurat#7473]
Hi ! How can I convert a seurat to H5ad with Visium data ? SueratDisk delete images data

**Comment by yuhanH** [comment]
hi @BenjaminDEMAILLE 
We would suggest you use [sceasy](https://github.com/cellgeni/sceasy) for h5ad conversion.

**Comment by BenjaminDEMAILLE** [comment]
> hi @BenjaminDEMAILLE 
> 
> We would suggest you use [sceasy](https://github.com/cellgeni/sceasy) for h5ad conversion. 

Yes I try but doesn't work with Spatial Seurat.

**Comment by BenjaminDEMAILLE** [comment]
I want to go from spatial Seurat to spatial H5ad. And every tools I use either crash or delete the spatial part.

**Comment by rsatija** [comment]
Unfortunately we do not support this, spatial data is far more complex than the count matrices of scRNA-seq, especially the imaging slots. Each technology (Visium, Xenium, etc.) also has its own file formats and requirements. We can support these within Seurat but it is outside our capability to write specific converters for each technology at the moment.
