### ISSUE TITLE
Can we perform pseudobulk using ScTransform (v2) normalized data?

### ISSUE THREAD

**Issue by LifeExtender** [satijalab/seurat#7474]
Hi guys, 

First off, thank  you guys for the tool it's been an a great help for single cell analysis!

I had a question regarding the use of ScTransform normalized data. I was hoping to normalize batch corrected data with ScTransform followed by perform DEG analysis using EdgeR-LRT given we have distinct biological replicates. 

I am just not sure if this is actually possible since ScTransform produces the pearson residuals. Any guidance on this would be very much appreciated. Thank you!

**Comment by alikhuseynov** [comment]
..not from Seurat team. But, I think you could use `counts` slot from SCT assay for DEG

**Comment by saketkc** [comment]
@LifeExtender You can use `Seurat:::AggreagateExpression(object, assays="SCT", slot="counts", group.by="XX")[[1]]` to aggregate corrected counts and pass it do any counts based DE test.
