### ISSUE TITLE
Y-axis on RidgePlots?

### ISSUE THREAD

**Issue by tonimaried** [satijalab/seurat#748]
Hello,

Is there a way to visualize the y-axis of RidgePlots? Also, is there an easy way to see how many cells are in each plot?

I used the following code to generate the plot below:
```R
RidgePlot(filter.Hn1, features.plot = c("Hn1"),group.by = "infected", y.log = FALSE,remove.legend = TRUE,size.y.use = 10,do.sort = TRUE,
          nCol = 2)
```
![rplot01](https://user-images.githubusercontent.com/42901521/44951228-a122b300-ae2c-11e8-8a47-af84f2466cde.jpeg)

Thanks for your help and time.

**Comment by andrewwbutler** [comment]
Hi,

You can add the y-axis line back in via `theme`. For example:
```R
RidgePlot(object = pbmc_small, "LYZ") + theme(axis.line.y = element_line())
```

You can see how many cells are in each group by using `table` on that meta.data column

```R
table(filter.Hn1@meta.data$infected)
```

**Comment by tonimaried** [comment]
Thank you very much!
