### ISSUE TITLE
cannot reproduce the analysis of Seurat on the RStudio Pro Server

### ISSUE THREAD

**Issue by lzhangLIH** [satijalab/seurat#7482]
I tried to reproduce the results by following your guided tutorial 2700 PBMCs, without making any modification. It worked well on RStudio desktop. But it couldn't properly perform PCA analysis on the RStudio pro server at our institute. I have attached the plots from the PCA results here. I made sure that I used Seurat 4.3.0 on both platforms. 
![pbmc3k_2dim](https://github.com/satijalab/seurat/assets/54404985/71d4f676-3019-4eeb-9a8b-ba17a32ad29e)
![pbmc3k_dimplot](https://github.com/satijalab/seurat/assets/54404985/de0f4488-6c75-4283-b94c-f4f19be4e4a3)
![pbmc3k_elbow](https://github.com/satijalab/seurat/assets/54404985/9c35b554-28d2-467b-a647-ebe94d0d1fc1)

**Comment by AustinHartman** [comment]
Could you provide complete code to reproduce this?

**Comment by lzhangLIH** [comment]
I followed the steps from the tutorial https://satijalab.org/seurat/articles/pbmc3k_tutorial.html using the same dataset. The code worked well in the Rstudio Desktop, but not on the RSTudio Pro Server at our institute. I discovered that the problem lies with the RunPCA. When I switched from using irlba to svd for decomposition on the RStudio Pro Server, the problem was resolved.


Lu Zhang
Research Engineer

Luxembourg Institute of Health
1A-B, rue Thomas Edison, L-1445 Strassen
Luxembourg
Tel: +352 26970-874
Email: ***@***.******@***.***>

[https://files.lih.lu/outlookSignature/lih_v2.jpg]

More about LIH : https://www.lih.lu/

[https://files.lih.lu/outlookSignature/AR2022.jpg]<https://www.lih.lu/en/activity-reports/?utm_source=outlook&utm_medium=email&utm_campaign=AR-22+Email+Signature>


Join us on Facebook and follow our activities on Twitter:
https://www.facebook.com/Luxembourg.Institute.of.Health
http://twitter.com/LIH_Luxembourg
***@***.******@***.***>

This message (including any attachments) is intended for the addressee only and may contain confidential and/or privileged information and/or information protected by intellectual property rights. If you have received this message  by mistake, please notify the sender by return e-mail and delete this message from your system. You should not use, alter, copy or distribute this message or disclose its contents to anyone. E-mail transmission can not be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Luxembourg Institute of Health shall not be responsible nor liable for the proper and complete transmission of the information contained in this communication nor for any delay in its receipt or damage to your system.
