### ISSUE TITLE
Error in h(simpleError(msg, call)) when using FindIntegrationAnchors function 

### ISSUE THREAD

**Issue by ZhenyaoYe** [satijalab/seurat#7485]
Hi,

Would there be someone available who could kindly assist me with the below issue I encountered while utilizing the FindIntegrationAnchors function?

Filtering anchors
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'as.matrix': error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds

Thank you so much!

Best regards,
Zhenyao

**Comment by peng-gang** [comment]
I have the same error when I use FindIntegrationAnchors listed below. How do you solve this issue?

anchors <- FindIntegrationAnchors(object.list = data.list, anchor.features = features)

**Comment by peng-gang** [comment]
It looks like I cannot use 
options(Seurat.object.assay.version = 'v5')

**Comment by zonghongz** [comment]
I also have this issue, I just opened a new issue before I noticed the same issue, any solution?
