### ISSUE TITLE
Reference mapping Harmony-corrected Seurat onto Reference Seurat

### ISSUE THREAD

**Issue by sallyseullee-0821** [satijalab/seurat#7487]
Hi! I am pretty new to Seurat and I would really appreciate your help!

I have a harmonized Seurat object that I would like to use as the query data. The reference Seurat object was obtained from publicly available database, which already has all the cell types labeled. So, my aim is to map the harmonized query onto the reference data to help with identifying cell types of my query data. 

It seems like there is no method of setting the query reduction model while running FindTransferAnchors. Also, neither query nor reference data are integrated. What can I do to perform this analysis? 

Thank you!

**Comment by yuhanH** [comment]
hi @sallyseullee-0821 
Mapping a harmonized query to the reference isn't a straightforward thing. I recommend splitting your query object and then mapping each sample separately. In the reference mapping, batch correction will be performed.

**Comment by nathan-nakatsuka** [comment]
Dear @sallyseullee-0821 , also it is okay if the query is not integrated, because the purpose of mapping the query onto the reference is to get the cell-types, which is what integration does if you don't have a reference for mapping.
