### ISSUE TITLE
IntegrateData - Finding integration vector weights Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds

### ISSUE THREAD

**Issue by ZhenyaoYe** [satijalab/seurat#7488]
Hi, 

Would there be someone available who could kindly assist me with the issue I encountered while utilizing the IntegrateData function?

Finding integration vectors
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  did not converge--results might be invalid!; try increasing work or maxit
**Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds**

Thank you! 

Best regards,
Zhenyao

**Comment by nathan-nakatsuka** [comment]
Dear @ZhenyaoYe , this should solve your problem (https://www.biostars.org/p/454509/). I believe you need to subset to genes that are present as rownames of the matrix.
