### ISSUE TITLE
Question: "duplicates" error in running TSNE

### ISSUE THREAD

**Issue by ghyanc** [satijalab/seurat#749]
I am handling with data generated by BD Rhapsody platform. The input is a gene expressing matrix. The problem is when I ran the "RunTSNE" function, it reported:
###
Error in Rtsne.default(X = as.matrix(x = data.use), dims = dim.embed,  :
  Remove duplicates before running TSNE.
###
I've checked for the gene list and cell indices, there was no duplicate gene or cell index included.
Anyone know this issue? 
Thanks!

**Comment by andrewwbutler** [comment]
Please see #85, #167, #499.
