### ISSUE TITLE
DEenrichRPlot terms for positive and negative genes are identical

### ISSUE THREAD

**Issue by julia-aguade** [satijalab/seurat#7492]
Hi, 

I am using the DEenrichRPlot function to plot the pathway enrichments for the DE genes beween 2 identities. I use "balanced = T" to see both the categories enriched in the positive (upregulated) DE genes and the categories for the negative (downregulated) DE genes. The output plot has the 2 parts, however, the categories are identical in both. This is what I am using:

```
DEenrichRPlot(
  sample,
  ident.1 = barsPatient,
  ident.2 = barsCtrl,
  balanced = T,
  logfc.threshold = 0.25,
  assay = NULL,
  max.genes = 100,
  test.use = "wilcox",
  p.val.cutoff = 0.05,
  cols = NULL,
  enrich.database = "GO_Molecular_Function_2023",
  num.pathway = 30,
  return.gene.list = F)
```

![Rplot](https://github.com/satijalab/seurat/assets/91636479/5ea31ce2-6b7d-48c0-b023-e2f58c83c3d0)

I have run FindMarkers on the same 2 identities and there are both upregulated and downregulated genes, and have seen using other tools that the enriched categories in the up and down genes are not the same.

I have also tested using different enrich.database and showing more num.pathway

Could you help me figure out what the issue is?

Thank you!

**Comment by longmanz** [comment]
Hi,
Thank you for reporting this. Sorry, this is indeed a bug. We will be fixing this soon. In the meantime, could you manually generate the enrichR plot by using the following codes:
```
# neg.markers.list should be the gene IDs of the negative DEGs from your FindMarkers() test

neg.er <- enrichR::enrichr(genes = neg.markers.list, 
                                   databases = enrich.database)
neg.er <- do.call(what = cbind, args = neg.er)
neg.er$log10pval <- -log10(x = neg.er[, paste(enrich.database, 
                                                      sep = ".", "P.value")])
neg.er$term <- neg.er[, paste(enrich.database, sep = ".", 
                                      "Term")]
neg.er <- neg.er[1:num.pathway, ]
neg.er$term <- factor(x = neg.er$term, levels = neg.er$term[order(neg.er$log10pval)])

p2 <- ggplot(data = neg.er, aes_string(x = "term", 
                                                   y = "log10pval")) + geom_bar(stat = "identity", 
                                                                                fill = "indianred2") + coord_flip() + xlab("Pathway") + 
                scale_fill_manual(values = cols, drop = FALSE) + 
                ylab("-log10(pval)") + ggtitle(paste(enrich.database, 
                                                     ident.1, sep = "_", "negative markers")) + theme_classic() + 
                geom_text(aes_string(label = "term", y = 0), 
                          size = 5, color = "black", position = position_dodge(1), 
                          hjust = 0) + theme(axis.title.y = element_blank(), 
                                             axis.text.y = element_blank(), axis.ticks.y = element_blank())
```

We will update you once we fix this bug.

**Comment by julia-aguade** [comment]
Thank you! I will use your script. Looking forward to the update when the bug is fixed, it will be much more comfortable.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
