### ISSUE TITLE
Corrected UMIs from SCTransform data

### ISSUE THREAD

**Issue by AKNG97** [satijalab/seurat#7494]
Hi! A couple of questions regarding SCTransfrom slots. 

1. Why does the corrected UMIs are rounded to an integer? Is there a way to round to a number of decimals?

2. Does negative Pearson residuals produce negative corrected UMIs in every case or could there be a case where a negative residual results in a positive corrected UMI?

3. Is the log-normalization applied to the corrected UMIs matrix performed with the NormalizeData function?

**Comment by saketkc** [comment]
> Why does the corrected UMIs are rounded to an integer? Is there a way to round to a number of decimals?

The idea here is to generate a UMI "count" that has been corrected for sequencing depth and hence it is an integer.

> Does negative Pearson residuals produce negative corrected UMIs in every case or could there be a case where a negative residual results in a positive corrected UMI?

The sign of pearson residuals does not imply the sign of corrected UMIs. Corrected UMIs are by definition non-negative. Please see the the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9) for details about how the correction is performed.

> Is the log-normalization applied to the corrected UMIs matrix performed with the NormalizeData function?

LogNormalization is a different normalization approach. log1p(corrected counts) are stored in the `data` slot of SCT assay (this is not related to NormalizeData)
