### ISSUE TITLE
Seurat input data: umi.counts vs counts vs tpm vs fpkm

### ISSUE THREAD

**Issue by rocanja** [satijalab/seurat#7496]
Dear Seurat Team,

_I have been using your very comprehensive Seurat package for about two years now, but I am still stumbling across details I wasn't fully aware of and I wished somebody had spelled them out more clearly, especially for newbies in scrnaseq analysis. One of these topics is relating to the input data for Seurat. Below I have tried to summarise what I have learned over the last two years and how I decided to handle different data input types with Seurat. It would be great if somebody from the Seurat team could check these points for correctness, so they can stay here as a reference for newbies facing the same challenges._
 
An important point to know first is that a **seurat.object has 3 data slots**:

- the **COUNT** slot is expected to contain the raw data values in **LINEAR** space, usually UMI based counts coming from the 10X CellRanger output
- the **DATA** slot contains the normalised data values in **LOG** space ... it's important to know that Seurat uses **log1p** transformation  ... that is ln(x+1) ... natural log as opposed to log2 or log10 ... this is super important to keep in mind
- the **SCALE.DATA** slot contains scaled data 

When the input data is **UMI.counts** (this is what Seurat expects per default, usually the counts matrix coming from 10X CellRanger):

1. create a seurat.object with the **raw counts in linear space**, this populates the COUNT and DATA slots: `seurat.object<-CreateSeuratObject(counts = UMI.counts.data)` #UMI.counts.data is a matrix with genes in rows and cells in columns
2. run the **normalisation** step:` seurat.object<-NormalizeData(seurat.object) `#this updates the DATA slot by converting the data into log space using log1p, but also normalises by the total counts per cell and multiplies by a scaling factor
3. **find variable features**: `seurat.object<-FindVariableFeatures(seurat.object)` #function uses the COUNTS slots and that's why it's important that the data in that slot is in LINEAR space
4. run the **scaling** function to populate the SCALE.DATA slot: `seurat.object<-ScaleData(seurat.object)` #function scales data based on the DATA slot

When the input data is **TPM or FPKM**:

_Note, even though it is possible to use TPM and FPKM values with Seurat with some tweaks, I have a few concerns re the downstream functions that are based on differential expression analyses eg. FindMarkers(), as they are generally made for count data and executing them on tpm or fpkm data is usually not recommended!?_  

1. create a seurat.object with the **tpm/fpkm in linear** space, this populates the COUNT and DATA slots: `seurat.object<-CreateSeuratObject(counts = tpm.data) `#tpm.data is a matrix with genes in rows and cells in columns
2. DON'T run the default normalisation step, since TPM and FPKM are already library size / gene length normalised, but since they are not log transformed, manually **add log1p transformed values** into the DATA slot: `seurat.object<-SetAssayData(object=seurat.object, slot="data", new.data = log1p(tpm.data))` #this updates the DATA slot with the logged values ... best to use log1p as opposed to log2(+1) or log10(+1) transformation, since Seurat plotting functions assume the DATA slot to have log1p data and using other transformations can result in unintended plot effects
3. **find variable features:** `seurat.object<-FindVariableFeatures(seurat.object) `#function uses the COUNTS slots and that's why it's important that the data in that slot is in LINEAR space
4. run the **scaling** function to populate the SCALE.DATA slot: `seurat.object<-ScaleData(seurat.object) `#function scales data based on the DATA slot 

When the input data is **counts that are not UMI based**:

_If the input values are counts generated in the traditional (bulk-rnaseq-like) way, without the usage of UMI's, it's important to consider doing a gene-length normalisation. This is very important when comparing the expression level between genes, as is done by some of the Seurat downstream / plotting functions ... since longer genes intrinsically tend to have more counts than shorter genes. UMI-based counts are not compromised by gene length and thus, gene length normalisation is not needed there._ 

1. create a seurat.object with the **counts in linear space**, this populates the COUNT and DATA slots: `seurat.object<-CreateSeuratObject(counts = count.data) `#count.data is a matrix with genes in rows and cells in columns
2. DON'T run the default normalisation step, but generate a data matrix with library size + gene length normalised and scaled values manually, log1p transform and add that into the DATA slot: `seurat.object<-SetAssayData(object=seurat.object, slot="data", new.data = normalised.log1p.count.data)) `#this updates the DATA slot ... best to use log1p as opposed to log2(+1) or log10(+1) transformation, since Seurat plotting functions assume the DATA slot to have log1p data and using other transformations can result in unintended effects
3. **find variable features**: `seurat.object<-FindVariableFeatures(seurat.object)` #function uses the COUNTS slots and that's why it's important that the data in that slot is in LINEAR space
4. run the **scaling** function to populate the SCALE.DATA slot:` seurat.object<-ScaleData(seurat.object)` #function scales data based on the DATA slot

**Comment by rsatija** [comment]
Thanks for your very thoughtful post.

Your post correctly describes how to implement custom normalization procedures, which may be useful if you want to work with non-UMI data.

Your broader point is that the counts slot does not have to represent only counts (it can represent TPM values which are non-integer), but it does need to be in linear scale for FindVariableFeatures to work correctly with default parameters. Additionally, the data slot does need to be in log scale for ScaleData to work correctly with default parameters.
