### ISSUE TITLE
Subset function suddenly not working 

### ISSUE THREAD

**Issue by martuskaR** [satijalab/seurat#7498]
HELLO , 

After updating R studio, Seurat subset() function doesn't work. it throws an error to the code I have used before and worked fine. 
<img width="418" alt="image" src="https://github.com/satijalab/seurat/assets/122094828/8606fe7d-cb1d-42c0-af25-7465e3162d9f">
Could you help please?

Kind Regards,

_Originally posted by @martuskaR in https://github.com/satijalab/seurat/issues/5676#issuecomment-1604379076_

**Comment by Gesmira** [comment]
Hi, 
Can you provide the output of sessionInfo()? In the meantime, I also recommend checking the advice here to see if any solve your issue.

**Comment by Gesmira** [comment]
Hi @elizalica,
Can you share the code you ran that led to your issue?

**Comment by elizalica** [comment]
selected <- WhichCells(seurat_mtxSCT, idents = c(2,3,4,5))
 subset_cluster <- subset(seurat_mtxSCT, cells =  selected)
Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE)


subset_cluster <- subset(seurat_mtxSCT, idents =  c("2","3","4","5")) - same error


idx = rownames(seurat_mtxSCT@meta.data)[(seurat_mtxSCT$seurat_clusters %>% as.character()) %in% c("2","3","4","5")]
subset_cluster = subset(seurat_mtxSCT, cells = idx) - same error

**Comment by Gesmira** [comment]
Hi, 
Apologies for the late response here, is this still an issue with the newest versions of Seurat and SeuratObject on CRAN?

**Comment by martuskaR** [comment]
Hi, 
Thanks a lot for getting back!
 I think, the issue was Seurat object, although I cannot tell why and what the problem was. On a scatter plot, the cells were no longer scattered and they were aligned in parallel lines. This object couldn't be subsetted. When I went to previous version when scatter plot was showing cells scattered all around, the subset function worked. I dont have bioinformatics background, and so until now I have no idea what happened with my Seurat object then. Does anyone know and could kindly explain? 

Regards, 
Marta

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if needed.
