### ISSUE TITLE
Is that possible to plot the distribution of more than two gene through Featureplot

### ISSUE THREAD

**Issue by zqyhyunbin** [satijalab/seurat#750]
Dear all,
i was using Featureplot to show the distribution about one gene in scRNA-seq data, but i found it was only support one or two gene, and i has a list of gene, and wanna see the expression of them, is that possible?

**Comment by mojaveazure** [comment]
You can pass the genes you would like to see as a vector ([not a list](https://jennybc.github.io/purrr-tutorial/bk00_vectors-and-lists.html)) to the [`features.plot`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/FeaturePlot) argument.

```R
library(Seurat)
data('pbmc_small')
features <- sample(pbmc_small@var.genes, 6) # Replace with a vector of your genes
FeaturePlot(object = pbmc_small, features.plot = features)
```
