### ISSUE TITLE
'ncol' is too big for `PrepareBridgeReference`

### ISSUE THREAD

**Issue by Zepeng-Mu** [satijalab/seurat#7503]
Hi, I encountered this error in the last step of `PrepareBridgeReference`:

```
Smoothing peaks matrix
Performing eigendecomposition
Constructing Bridge-cells representation


Error in DelayedArray::colAutoGrid(x = counts, ncol = length(x = layer.cells)) :
  'ncol' is too big. Blocks of length > .Machine$integer.max are not
  supported yet. Please specify a smaller 'ncol'.
Calls: PrepareBridgeReference ... merge.Seurat -> merge -> merge.SCTAssay -> lapply -> FUN
Execution halted
```
The error seems to suggest that there are too many cells. But my reference data is just 600K cells, and the bridge from 10X is even smaller. So I'm not sure whether this is a problem of my data or some other reasons.

Thanks in advance!

**Comment by Zepeng-Mu** [comment]
Just as a follow up, I tried the same code but just using 2e4 cells and everything worked fine. So I guess it is due to the reference being too large. But .Machine$integer.max is 2.14e9, so I'm not sure why 600K cells would exceed that.

Would it be sensible to run SCTransform, PCA and UMAP on the full dataset and then run `PrepareBridgeReference` on blocks of data?

**Comment by yuhanH** [comment]
i think it results from the dense matrix of the SCT residuals. How do you integrate your reference? 
If you use SCT-based integration, you can empty scale.data slot in your integrated assay.

**Comment by Zepeng-Mu** [comment]
Hi, I tried setting the scale.data to NULL but still got the same error message:
```r
haniffa2021New@assays$SCT$scale.data <- NULL
```

```
Normalizing query using reference SCT model
Warning: No layers found matching search pattern provided
Warning: 206 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 2794 features.
Projecting cell embeddings
Finding neighborhoods
Finding anchors
	Found 3344 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
  |                                                  | 0 % ~calculating  
Integrating dataset 2 with reference dataset
Finding integration vectors
Integrating data
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=21s  
Computing nearest neighbor graph
Computing SNN
Generating normalized laplacian graph
Performing eigendecomposition of the normalized laplacian graph
Smoothing peaks matrix
Performing eigendecomposition
Constructing Bridge-cells representation
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=08s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07s  
Error in DelayedArray::colAutoGrid(x = counts, ncol = length(x = layer.cells)) : 
  'ncol' is too big. Blocks of length > .Machine$integer.max are not supported yet. Please specify a smaller 'ncol'.
```

**Comment by Zepeng-Mu** [comment]
Actually, setting the scale.data in bridge object to NULL solves the problem, though I'm not sure if this information is needed for downstream steps.

**Comment by yuhanH** [comment]
Since we don't use SCT residuals for most downstream analysis after integration, it will not create a new problem.
