### ISSUE TITLE
Error: readMM(): column indices 'j' are not in 1:ncol[=4422]

### ISSUE THREAD

**Issue by Syayaq** [satijalab/seurat#7504]
I try to create a Seurat Object and when I use Read10X :

a<-CreateSeuratObject(counts = Read10X("D:/ATAC-seq/SCRNA_GBM//GSM5319529_SF8963",gene.column=1),min.cells = 3, 
                   min.features = 200)

there is an error message as follows:

Error: readMM(): column indices 'j' are not in 1:ncol[=4422]
In addition: Warning messages:
1: In scan(file, nmax = nz, quiet = TRUE, what = list(i = integer(),  :
  number of items read is not a multiple of the number of columns
2: In scan(file, nmax = nz, quiet = TRUE, what = list(i = integer(),  :
  embedded nul(s) found in input

These are the header of my 3 files:

[barcodes.tsv.gz](https://github.com/satijalab/seurat/files/11888997/barcodes.tsv.gz)
[features.tsv.gz](https://github.com/satijalab/seurat/files/11888998/features.tsv.gz)
[matrix.mtx.gz](https://github.com/satijalab/seurat/files/11888999/matrix.mtx.gz)

Do you have any idea to solve this problem?
Thanks a lot.

**Comment by Gesmira** [comment]
Hi, 
I recommend checking the advice out [here](https://github.com/satijalab/seurat/issues/2946). It seems that your barcode and feature values are flipped compared to the number of lines in each file.

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if the issue persists!
