### ISSUE TITLE
Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from peaks to peaks_

### ISSUE THREAD

**Issue by Syayaq** [satijalab/seurat#7506]
I try to create a Seurat Object for scATAC files geting from GEO and when I do like this:

mtx_path <- paste(mex_dir_path, "matrix.mtx", sep = '/')
feature_path <- paste(mex_dir_path, "peaks.bed", sep = '/')
barcode_path <- paste(mex_dir_path, "barcodes.tsv", sep = '/')

features <- readr::read_tsv(feature_path, col_names = F) %>% tidyr::unite(feature)
barcodes <- readr::read_tsv(barcode_path, col_names = F) %>% tidyr::unite(barcode)

mtx <- Matrix::readMM(mtx_path) %>%
  magrittr::set_rownames(features$feature) %>%
  magrittr::set_colnames(barcodes$barcode)

mtx<-as(mtx, 'CsparseMatrix')
chrom_assay1 <- CreateChromatinAssay(counts = mtx,
                                     sep = c(":", "-"), genome = 'hg38',
                                     min.cells = 10,
                                     min.features = 200)
CreateSeuratObject(counts = chrom_assay, assay = "peaks",project = pro,min.cells = 10, 
                   min.features = 200)

there is an error message as follows:

Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from peaks to peaks_

These are the 3 files of mine:
[barcodes.tsv.gz](https://github.com/satijalab/seurat/files/11890378/barcodes.tsv.gz)
[matrix.mtx.gz](https://github.com/satijalab/seurat/files/11890379/matrix.mtx.gz)
[peaks.bed.gz](https://github.com/satijalab/seurat/files/11890521/peaks.bed.gz)

I want to konw that does it will exert an influence on my following works.

Thanks a lot.

**Comment by Gesmira** [comment]
Hi, 
This is a warning, not an error message. Thus, I wouldn't worry about it! It's just setting the name of the Keys in the correct format for SeuratObject. Your assay will still be called "peaks".
