### ISSUE TITLE
FindTransferAnchors + MapQuery between from a CITE-seq query to a CITE-seq reference 

### ISSUE THREAD

**Issue by stemangiola** [satijalab/seurat#7507]
I did not find an answer to this question online.

I want to transfer the labels (FindTransferAnchors + MapQuery) between from a CITE-seq query to a CITE-seq reference.

For the sake of this example

```r
query <- LoadH5Seurat("../data/pbmc_multimodal.h5seurat")
reference <- LoadH5Seurat("../data/pbmc_multimodal.h5seurat")
```

In 

```r
 FindTransferAnchors(
      reference = reference,
      query = query,
      reference.reduction = ???, # I would like to use pca (from RNA) + apca (from ADT)
      dims = 1:50
    )
```

I don't see how to use [RNA pca], [ADT apca] together

And how `MapQuery` should look like?

Thanks a lot.

**Comment by yuhanH** [comment]
At present, we are not providing support for multimodal reference mapping. In relation to your CITE-seq, you have the option to use either the RNA or ADT assay for reference mapping. For the construction of the reference, the WNN graph (multimodal graph) can be used to obtain the supervised RNA PCA or ADT PCA for single-modality mapping. The following example demonstrates the process:  [computing sPCA transformation.](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html)
