### ISSUE TITLE
Different FindMarkers results with Seurat v4.3.0 and Seurat v4.9.9.9045

### ISSUE THREAD

**Issue by KunFang93** [satijalab/seurat#7513]
Hi,

Thanks for providing this wonderful tool! I followed vignette: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html#identify-differential-expressed-genes-across-conditions-1 but get different number of markers under two versions (Seurat v4.3.0 and  Seurat v4.9.9.9045):

For v.4.3.0, I got total 234 markers in b.intereferon.response data, but v.4.9.9 gave me a total of 911 markers. I found that 234 markers identified in v.4.3.0 is all contained by v.4.9.9. In this case, I wondered which results should I followed? Please let me know if more information is needed, thanks for your help!

Best,
Kun

**Comment by shahrozeabbas** [comment]
You might try to annotate the clusters using both sets of markers. Reason being is even if the markers are different, it's possible the cell type annotation is not, in which case it may not matter that the results are different because they still lead you to the same cell type annotation.

**Comment by longmanz** [comment]
Hi,
This has nothing to do with the FindMarkers() itself, but a change of `pseudocount.use`. In version <= 4.3, the default pseudocount.use is 1, and in v5 it has been changed to 0.1. 
If you prefer to have the same DE results, just explicitly set `pseudocount.use = 1` when running FindMarkers(), you should be able to get the same number of DEGs ( = 234).
