### ISSUE TITLE
BPCells and non-counts matrices

### ISSUE THREAD

**Issue by kthorner** [satijalab/seurat#7516]
Hi everyone,

My goal is to create lightweight Seurat objects to be used in Shiny applications. To that end, I'm trying out v5 and following the instructions in the BPCells vignette. I use SCT v2 and after processing remove most things besides the data slot of the SCT assay, reductions, and metadata with DietSeurat(). 

My question: Is there an implicit assumption that BPCells should be used only for raw counts, as shown in the examples? I know its primary use is to convert at the very beginning and have it speed up analysis, and by using it on the non-sparse SCT data I'm not really benefiting from the compression. But I was hoping I could at least benefit from not needing to load everything into memory. In the example below I'm able to technically assign an on-disk matrix to the data by changing the class, but then I can no longer find markers as "object is not a matrix". Is what I'm doing logical but just not supported yet? Thanks. 

```r
write_matrix_dir(mat = pbmc[["SCT"]]$data, dir = "datasets/pbmc_data")
counts.mat <- open_matrix_dir(dir = "datasets/pbmc_data")
pbmc[["SCT"]] <- as(object = pbmc[["SCT"]], Class = "Assay5")
pbmc[["SCT"]]$data <- counts.mat
markers <- FindAllMarkers(pbmc,assay = "SCT")
```

**Comment by yuhanH** [comment]
hi @kthorner 
BPCells can be utilized with any sparse matrix. Often, there is no need to store other matrices, as the results are stored as queued operations stemming from raw counts. 
The SCT data slot remains sparse, thus it can be saved as a BPCells object. But currently we do not support the use of FindMarkers on the BPCells matrix. We are working on it. You need to use a sparse matrix for find markers.
