### ISSUE TITLE
the inconsistent normalization results using SCTransform and NormalizationData

### ISSUE THREAD

**Issue by xiaojjia** [satijalab/seurat#7518]
Dear Seurat team,
Thanks for your great package!

I am using and comparing the `SCTransform` function and `NormalizeData` ( & `FindVariableFeatures` & `ScaleData`) function from the Seurat package, but got two different results after normalization. 
So I have two problem:

- [ ] How to explain the two inconsistent normalization results?
- [ ] For Spatial transcriptome, whether the parameter `min_cell` means min_spot in  `SCTransform` function?

PS: For Nor_results, it is 33538 genes and 1661 spots; for SCT_results, it gets 17626 genes and 1661 spots.

Thanks for your help!
Best,
xiaoj

Here is my R code and the correspoding results:
# SCTransform
```
mydata <- SCTransform(st,
            assay = "Spatial",
            method = "glmGamPoi",
            ncells = 2000, # the total of my spots is 1661
            vars.to.regress = "percent.mt",
            return.only.var.genes = FALSE,
            min_cells = 1,
            verbose = F)
p3 <- VlnPlot(mydata, features = c("nCount_SCT", "nFeature_SCT"), pt.size = 0.1) + NoLegend()
p4 <- SpatialFeaturePlot(mydata, features = c("nCount_SCT", "nFeature_SCT")) + theme(legend.position = "top")
plot_grid(p3, p4, ncol = 1)
```
![image](https://github.com/satijalab/seurat/assets/102225308/aa045948-c778-4d60-b2ed-e752a083f728)

# NormalizeData, FindVariableFeatures, ScaleData
```
mydata <- NormalizeData(mydata,
            assay = "Spatial",
            normalization.method = "LogNormalize",
            scale.factor = 10000)
mydata <- FindVariableFeatures(mydata, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(mydata)
mydata <- ScaleData(mydata, features = all.genes)
p5 <- VlnPlot(mydata, features = c("nCount_Spatial", "nFeature_Spatial"), pt.size = 0.1) + NoLegend()
p6 <- SpatialFeaturePlot(mydata, features = c("nCount_Spatial", "nFeature_Spatial")) + theme(legend.position = "top")
plot_grid(p5, p6, ncol = 1)
```
![image](https://github.com/satijalab/seurat/assets/102225308/b9ef2206-6e51-47df-995f-a18ae2d42216)

**Comment by saketkc** [comment]
Hi @xiaojjia , The two normalization use different "size factors". NormalizeData uses a default scale factor of 10000 while SCTransform uses a scale factor of `median(nCount_RNA)`. The difference in SCT features is attributable to this difference.

The `min_cells ` parameter treats when to consider a gene expressed. By default this is set to 5 which means SCTransform will calculate residuals and corrected counts for a feature only if it is expressed in a minimum of 5 cells (or spots in your case)

**Comment by xiaojjia** [comment]
> Hi @xiaojjia , The two normalization use different "size factors". NormalizeData uses a default scale factor of 10000 while SCTransform uses a scale factor of `median(nCount_RNA)`. The difference in SCT features is attributable to this difference.
> 
> The `min_cells ` parameter treats when to consider a gene expressed. By default this is set to 5 which means SCTransform will calculate residuals and corrected counts for a feature only if it is expressed in a minimum of 5 cells (or spots in your case)

Thanks so much! I got it!
