### ISSUE TITLE
IntegrateData

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [satijalab/seurat#7519]
### Discussed in https://github.com/satijalab/seurat/discussions/7311

<div type='discussions-op-text'>

<sup>Originally posted by **JLi-github** May 11, 2023</sup>
Hi,

I have a question about IntegrateData: integrate <- IntegrateData(anchorset = anchors, dims = 1:50, features.to.integrate = all_genes)

I got an error: Integrating data
Merging dataset 15 into 23 4
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Integrating data
Merging dataset 24 20 1 into 19 10 3
Extracting anchors for merged samples
Finding integration vectors
Error in .T2C(newTMat(i = c(ij1[, 1], ij2[, 1]), j = c(ij1[, 2], ij2[,  : 
  'Calloc' could not allocate memory (298833518 of 8 bytes)
</div>

Hi I got the same error running RPCA

**Comment by Gesmira** [comment]
Answered [here](https://github.com/satijalab/seurat/issues/7419). Please reopen if this does not help.

**Comment by BenjaminDEMAILLE** [comment]
Thx ! When do you expect v5 release as stable ?
