### ISSUE TITLE
Re-clustering of given clusters

### ISSUE THREAD

**Issue by Gerde89** [satijalab/seurat#752]
Dear Seurat team，
     Thanks for developing Seurat， I have a question while re-clustering some of clusters，could you please help me？ 
     I have run RunMultiCCA, AlignSubspace, FindClusters, RunTSNE， now I want to re-clustering the cells using some of the clusters， such as， cluster-0 & cluster-1，so I run RunTSNE() with cells.use, does that correct ?  I don't want to get the 'zoom-in' of the cluster-0 & cluster-1, but I want to re-clustering these two clusters.
     Thanks in advance!
Sincerely，
Gerde

Edit:  It seems that run RunTSNE() with cells.use directly is wrong, should I subset T-cells from each sample and creat a new seurat object, and then normalize, find var genes, scaledata,  RunMultiCCA ... ?

**Comment by satijalab** [comment]
You can certainly subset your data, and recalculate Variable Genes, scale, run PCA, and cluster.

Note that you can set ident.use = c(0, 1) to subset two clusters.

**Comment by Gerde89** [comment]
@bwang258 @satijalab  Thanks a lot ! Yes, I want to subset cluster 0,1 and run clustering on it. Thanks all !
