### ISSUE TITLE
Issue with ifnb object

### ISSUE THREAD

**Issue by bykovam** [satijalab/seurat#7521]
While following the code for "Introduction to SCTransform, v2 regularization" (https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) I encountered the following issue:

# Library Install
library(Seurat)
library(SeuratData)
library(patchwork)
library(dplyr)
library(ggplot2)
library(sctransform)
library(glmGamPoi)

# install dataset
InstallData("ifnb")

# load dataset
LoadData("ifnb")

# split the dataset into a list of two seurat objects (stim and CTRL)
ifnb.updated = UpdateSeuratObject(object = ifnb)
ifnb.list <- SplitObject(ifnb.updated, split.by = "stim")
ifnb.list <- SplitObject(ifnb, split.by = "stim")

The console output reads as follows:

> # Library Install
> library(Seurat)
> library(SeuratData)
> library(patchwork)
> library(dplyr)
> library(ggplot2)
> library(sctransform)
> library(glmGamPoi)
> 
> # install dataset
> InstallData("ifnb")
Warning: The following packages are already installed and will not be reinstalled: ifnb
> 
> # load dataset
> LoadData("ifnb")
Validating object structure
Updating object slots
Ensuring keys are in the proper structure
Warning: Assay RNA changing from Assay to Assay
Ensuring keys are in the proper structure
Ensuring feature names don't have underscores or pipes
Updating slots in RNA
Validating object structure for Assay ‘RNA’
Object representation is consistent with the most current Seurat version
An object of class Seurat 
14053 features across 13999 samples within 1 assay 
Active assay: RNA (14053 features, 0 variable features)
 2 layers present: counts, data
> 
> 
> 
> 
> # split the dataset into a list of two seurat objects (stim and CTRL)
> ifnb.updated = UpdateSeuratObject(object = ifnb)
Validating object structure
Updating object slots
Ensuring keys are in the proper structure
Warning: Assay RNA changing from Assay to Assay
Ensuring keys are in the proper structure
Ensuring feature names don't have underscores or pipes
Updating slots in RNA
Validating object structure for Assay ‘RNA’
Object representation is consistent with the most current Seurat version
> ifnb.list <- SplitObject(ifnb.updated, split.by = "stim")
> ifnb.list <- SplitObject(ifnb, split.by = "stim")
Error in slot(object = object, name = s) : 
  no slot of name "images" for this object of class "Seurat"

The ifnb object available in the SeuratData package needs to be updated, as it will not work without running UpdateSeuratObject on it

**Comment by saketkc** [comment]
Thanks for reporting the issue @bykovam - this will be addressed in a future SeuratData release. For now, I would recommend running the following code to update the object (as you have done):


```r
ifnb <- UpdateSeuratObject(object = ifnb)
```
