### ISSUE TITLE
Error: Cannot find 'SCT' in this Seurat object

### ISSUE THREAD

**Issue by kcunhaerocha** [satijalab/seurat#7523]
Hi everyone.

I am having trouble with some integrated data that were available online. 

I downloaded the integrated Seurat object and I thought I would have to follow the normal steps to analyze it, but I can't do any command. Everything that I try to do I receive the same error: Error: Cannot find 'SCT' in this Seurat object.

head() of the object:

                     orig.ident nCount_RNA nFeature_RNA
AAACGAAAGAAGCGAA-1_1_3 Massier et al. #4   293.1686          259
AAACGAAGTCATCCCT-1_1_3 Massier et al. #4   255.2264          231
AAACGAAGTTTGGCTA-1_1_3 Massier et al. #4   346.0842          295
AAACGCTAGCATCCCG-1_1_3 Massier et al. #4   216.6815          206
AAAGGATGTACGATCT-1_1_3 Massier et al. #4   230.5742          211
AAAGGATGTCCTGGGT-1_1_3 Massier et al. #4   342.6275          283
AAAGGTAGTAACAGGC-1_1_3 Massier et al. #4   229.0557          205
AAAGTGAAGCAAATGT-1_1_3 Massier et al. #4   220.5494          207
AAAGTGATCCACAAGT-1_1_3 Massier et al. #4   232.8506          218
AACAACCTCAGCCCAG-1_1_3 Massier et al. #4   307.3811          301
                       percent.mt percent.MTRNR percent.MALAT1
AAACGAAAGAAGCGAA-1_1_3  0.3215016             0      0.1103344
AAACGAAGTCATCCCT-1_1_3  0.0000000             0      2.5698862
AAACGAAGTTTGGCTA-1_1_3  2.5038661             0      0.0000000
AAACGCTAGCATCCCG-1_1_3  0.0000000             0      1.7223610
AAAGGATGTACGATCT-1_1_3  0.0000000             0      0.2087123
AAAGGATGTCCTGGGT-1_1_3  0.0000000             0      0.3591571
AAAGGTAGTAACAGGC-1_1_3  0.0000000             0      0.0000000
AAAGTGAAGCAAATGT-1_1_3  0.7284323             0      2.5286168
AAAGTGATCCACAAGT-1_1_3  0.0000000             0      1.5771639
AACAACCTCAGCCCAG-1_1_3  0.0000000             0      0.8706538
                       percent.RP percent.HB.genes nCount_SCT
AAACGAAAGAAGCGAA-1_1_3  0.3274669                0        751
AAACGAAGTCATCCCT-1_1_3  0.0000000                0        763
AAACGAAGTTTGGCTA-1_1_3  0.0000000                0        789
AAACGCTAGCATCCCG-1_1_3  0.0000000                0        709
AAAGGATGTACGATCT-1_1_3  0.4184906                0        723
AAAGGATGTCCTGGGT-1_1_3  0.0000000                0        785
AAAGGTAGTAACAGGC-1_1_3  1.6836358                0        697
AAAGTGAAGCAAATGT-1_1_3  0.3983622                0        723
AAAGTGATCCACAAGT-1_1_3  0.0000000                0        737
AACAACCTCAGCCCAG-1_1_3  0.3143529                0        755
                       nFeature_SCT      UMAP_1     UMAP_2 method
AAACGAAAGAAGCGAA-1_1_3          259  3.82752378 -2.6912397  snSeq
AAACGAAGTCATCCCT-1_1_3          241 -2.24208145 -0.3776850  snSeq
AAACGAAGTTTGGCTA-1_1_3          295  0.15153666 -3.3659111  snSeq
AAACGCTAGCATCCCG-1_1_3          234 -1.21442179 -0.4548016  snSeq
AAAGGATGTACGATCT-1_1_3          231  0.71769090 -1.8460655  snSeq
AAAGGATGTCCTGGGT-1_1_3          283 -0.09256788 -3.3836389  snSeq
AAAGGTAGTAACAGGC-1_1_3          226  1.28874429 -2.1728801  snSeq
AAAGTGAAGCAAATGT-1_1_3          232 -1.90820734  0.1982813  snSeq
AAAGTGATCCACAAGT-1_1_3          235 -2.61982887 -0.9904722  snSeq
AACAACCTCAGCCCAG-1_1_3          301 -2.32943051 -0.5681639  snSeq`

What I am trying to do:

`VlnPlot(object, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)`

The error that I receive:
`Error in `DefaultAssay<-.Seurat`(object = `*tmp*`, value = assay) : 
  Cannot find assay SCT`

or
When I try to see the cluster,=:
`DimPlot(object, reduction = "umap")`
The error:
`Error: Cannot find 'SCT' in this Seurat object`

What should I do?
Thank you :)

**Comment by saketkc** [comment]
Can you point me to the object?
