### ISSUE TITLE
SeuratObject5 missing for Seurat5

### ISSUE THREAD

**Issue by shlomita** [satijalab/seurat#7525]
Cannot install Seurat5

I tried to install Seurat 5 on R/4.2.0. 
I got the error:
```
> remotes::install_github("satijalab/seurat", "seurat5")
....
** byte-compile and prepare package for lazy loading
   Error: package ‘SeuratObject’ 4.1.3 was found, but >= 4.9.9.9049 is required by ‘Seurat’
   Execution halted
   ERROR: lazy loading failed for package ‘Seurat’
```
Where can I find SeuratObject5 and any other dependencies?

**Comment by shahrozeabbas** [comment]
https://satijalab.org/seurat/articles/install.html

**Comment by Gesmira** [comment]
Hi, 
Please use the following code to install SeuratObject v5. 
`remotes::install_github("mojaveazure/seurat-object", "seurat5")`
