### ISSUE TITLE
Seurat v5 does not display umap reduction with rasterization

### ISSUE THREAD

**Issue by arnaudmet** [satijalab/seurat#7526]
Thanks for your amazing work!
When I'm trying to plot gene expression, of metadata, with a umap reduction, Seurat automatically try to rasterize, because of the number of cells. The dot representing cells do not appear. Only a white background, with axis is displayed. 

for exemple, this line of code does not display the dots. 
`FeaturePlot(combined, "CD34", slot = "data", order = T,reduction = "umap")
`
I need to specify, to disable rasterization to display dot properly. 
`FeaturePlot(combined, "IL1RAP", slot = "data", order = T,reduction = "umap", raster=F)
`

This way I'm able to display umap reduction.

**Comment by bbimber** [comment]
@arnaudmet Is there a reason you closed this? I think I'm seeing exactly the same thing

**Comment by arnaudmet** [comment]
> @arnaudmet Is there a reason you closed this? I think I'm seeing exactly the same thing

Hi, I still investigate, so i thought it was not necessary to keep it open without more information. 
Because it appears that it's not due to SeuratV5 or Assay5. I had the same problem with others version. So, I suspect that it could be due to third package interfering with plotting.
I'll reopen it if I'm not the only one with this problem and if you want to bring some information.

**Comment by bbimber** [comment]
@arnaudmet: since I posted here, I came across this, which is probably the same issue: https://github.com/satijalab/seurat/issues/7328

**Comment by saketkc** [comment]
Hi @arnaudmet, this fix should be in `seurat5` branch. To clarify, this happened because of an upstream updated to `ggscatter` and has already been fixed in the `develop` branch. Can you pull from the latest `seurat5` branch?

```r
devtools::install_github("satijalab/seurat", ref="seurat5")

```
