### ISSUE TITLE
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package, which was just loaded, will retire in October 2023. 

### ISSUE THREAD

**Issue by stroke1989** [satijalab/seurat#7533]
Hi, 
Thanks for this excellent tool. I sucessfully installed Seurat5, but when it was loaded, some warnings occurred:
> library(Seurat)
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
Attaching SeuratObject

I don't know whether these warnings suggest incomplete function of Seurat5. Could I use it for downstream analysis?

**Comment by rsatija** [comment]
This will not cause any issues with your downstream analysis. We may need to make changes to the package install requirements prior to October 2023.
