### ISSUE TITLE
DoHeatmap Error when selecting cells - Error in h(simpleError(msg, call)) : 

### ISSUE THREAD

**Issue by nina-hahn** [satijalab/seurat#7535]
Dear all, 

I merged 8 Visium Spatial datasets, performed normalization and batch effect correction using MNN. When I perform selection of features, it works fine. When I select a subset of cells, I get the following error and R crashes (only restarting helps).

Error in h(simpleError(msg, call)) : 
  Error evaluating argument 'x' in method selection for function 'as.matrix': Error evaluating argument 'x' in method selection for function 't': subscript out of bounds

The selection of cells was imported from the Loupe browser, where I manually selected spots (=cells) according to an immunostaining pattern.

Here you can find the part of code that is not working:

> ChPX.selected.cells<-read.csv(file = file.ChPX.spots)

> str(ChPX.selected.cells)
'data.frame':	174 obs. of  2 variables:
 $ Barcode  : chr  "AATTAAAGGTCGGCGT-1" "ACCCGGTTACACTTCC-1" "AGTCAACACCACCATC-1" "AGTGATATGAGTAGTT-1" ...
 $ ChPx.GFAP: chr  "PCI_GM2560" "PCI_GM2560" "PCI_GM2560" "PCI_GM2560" ...

> plotXX<-DoHeatmap(brain.norm.MNN,
           assay = "Spatial",
           features= Top10.Var.Feat.MNN,
           cells = ChPX.selected.cells$Barcode)

May it be a problem that I have a merged data sets and spots are redundant? 

BTW: Is there any other way than restarting R after getting that error? ESC is not working. 

Best, 
Nina

**Comment by longmanz** [comment]
Hi, 
This error happens when you try to plot cells that are not in the seurat object. To avoid this issue, you can first filter your `ChPX.selected.cells$Barcode` and only query the cells that are in your object. For example, you can:
```
slct_cells = intersect(colnames(seurat_object), ChPX.selected.cells$Barcode)
plotXX<-DoHeatmap(brain.norm.MNN,
assay = "Spatial",
features= Top10.Var.Feat.MNN,
cells = slct_cells)
```
You should be able to avoid this error.

**Comment by nina-hahn** [comment]
Thanks longmanz, I tried. The intersection is empty. I checked the following

> head(ChPX.selected.cells$Barcode)
[1] "AATTAAAGGTCGGCGT-1" "ACCCGGTTACACTTCC-1" "AGTCAACACCACCATC-1"
[4] "AGTGATATGAGTAGTT-1" "ATCCAGGATTCGTGAA-1" "ATCCTACCTAAGCTCT-1"
> head (colnames(brain.norm.MNN))
[1] "AAACACCAATAACTGC-1_1_1_1_1" "AAACAGCTTTCAGAAG-1_1_1_1_1"
[3] "AAACAGGGTCTATATT-1_1_1_1_1" "AAACAGTGTTCCTGGG-1_1_1_1_1"
[5] "AAACCGGGTAGGTACC-1_1_1_1_1" "AAACCGTTCGTCCAGG-1_1_1_1_1"

I guess this might be due to the merge function that I used to combine the 8 datasets.  However, I do not have any clue how to deal with it. Do you have any idea?

Best

**Comment by longmanz** [comment]
Hi, 
This  "XXX_1_1_1_1" happens automatically when you have duplicated cell IDs in some of your original seurat objects, and in order to differentiate them after Merge(), Seurat will add [_1]* to the duplicated cell IDs.

To solve this, you need to make sure for the cells listed in ChPX.selected.cells$Barcode, which cells **from which objects** (since there are duplicated ones) are the ones that you really want to highlight. 

For example, **before merging**, you can make an additional column for each object to annotate these cells. And then after the merging, you will know which cells need to be highlighted even if their cell-IDs change to "XXX_1_1". 
```
obj1$highlight_or_not = 0
obj1$highlight_or_not[colnames(obj1) %in% ChPX.selected.cells$Barcode] = 1
## repeat this for obj2, obj3, ..., obj8

brain.norm.MNN = merge(...)

# get the cells that need to be highlighted:
slct_cells = colnames(brain.norm.MNN)[brain.norm.MNN$highlight_or_not == 1] 

plotXX<-DoHeatmap(brain.norm.MNN,
assay = "Spatial",
features= Top10.Var.Feat.MNN,
cells = slct_cells)

```

**Comment by nina-hahn** [comment]
Hi, 

your answers were very helpful, thank you very much. I found a solution how to deal with the problem even after merging. 

##Extract indices for barcodes that arise by merging of seurat objects
N<-c()
indices.Barcodes<-data.frame()
for (i in 1:length(Sample.IDs)){
  N<-colnames(brain.norm.MNN)[brain.norm.MNN$Sample.ID==Sample.IDs[i]][1] 
  N<-substring(N, 19,nchar(N))
  print(N)
  N<-data.frame(N,Sample.IDs[i])
  
  if (i==1){indices.Barcodes<-N}
  else
  {indices.Barcodes<-rbind(indices.Barcodes,N)}
}
names(indices.Barcodes)<-c("Index", "Sample.ID")

##Add the newBarcodes that should match the barcodes in the merged Seurat data set
newBarcode<-c()
for( i in 1:length(ChPX.selected.cells$Barcode)){
  newBarcode[i]<-paste(substring(ChPX.selected.cells$Barcode,1,16)[i],"-1", 
           indices.Barcodes$Index[indices.Barcodes$Sample.ID==ChPX.selected.cells$ChPx.GFAP[i]],
           sep="")
}

ChPX.selected.cells<-cbind(ChPX.selected.cells, newBarcode)
slct_cells = intersect(colnames(brain.norm.MNN), ChPX.selected.cells$newBarcode)
