### ISSUE TITLE
Issue with running AddModuleScore in seurat v5

### ISSUE THREAD

**Issue by lselfors** [satijalab/seurat#7536]
Hi, I'm reanalyzing samples using seurat v4.9.9042 and I'm getting very different results using AddModuleScore than I got with previous versions of Seurat. In v5, the scale seems very wrong.  I'm using the exact same data.  The code that has been tweaked a little to handle seurat v5.  Here's an example of a featureplot after AddModuleScore.  

![image](https://github.com/satijalab/seurat/assets/46331273/98e72470-44c7-44ce-9f65-3304b5198496)

Here are the feature plots for all of the genes in the signature.  As you can see, the data from the markers is consistent, with the small cluster at 2 o'clock being low (in fact all of the markers are DE fdr<0.05 and FC<-1.3 in this cluster), but the AddModuleScore, which is calculated from these genes, doesn't make any sense.  Note that the scale is very strange.  In my previous analysis of this sample, I did not see this discrepancy.  The differential expression and GSEA results between the reanalysis and older analysis match ok.  The only issue I see is with "AddModuleScore".

![image](https://github.com/satijalab/seurat/assets/46331273/9cf74e8c-4a6d-4e1a-89d6-f3b7e84880bc)

Here's my code:

MYC_TARGETS=c("YWHAE","HDDC2","GLO1","NDUFAB1","NHP2","RANBP1","COX5A","CCT4","PRDX3","UBE2E1","SNRPG","PCBP1","LSM2","RAN","PSMA4","DEK")
seurat=AddModuleScore(seurat,features=list(MYC_TARGETS), name="addmodulescore")
FeaturePlot(seurat,features=c("addmodulescore1"))
FeaturePlot(seurat,features=c(MYC_TARGETS))

seurat

An object of class Seurat 
31694 features across 3001 samples within 2 assays 
Active assay: RNA (15847 features, 0 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: SCT
 2 dimensional reductions calculated: pca, umap

Here's how I generated the new seurat object:

oldSeurat=get(load(seurat))
seurat=CreateSeuratObject(as.matrix(oldSeurat[["RNA"]]$counts), min.cells = 20, min.features = 500)

I then ran for normalize data, scale.data, etc.
   
sessionInfo() R version 4.2.1 (2022-06-23) Platform: x86_64-pc-linux-gnu (64-bit) Running under: CentOS Linux 7 (Core)  Matrix products: default BLAS/LAPACK: /n/app/openblas/0.3.19-gcc-9.2.0/lib/libopenblas_haswellp-r0.3.19.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] grid      stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] fgsea_1.24.0            png_0.1-8               RColorBrewer_1.1-3      ComplexHeatmap_2.14.0    [5] reshape2_1.4.4          stringr_1.5.0           MultiK_0.1.0            Seurat_4.9.9.9042        [9] SeuratObject_4.9.9.9084 sp_1.6-1                lattice_0.20-45         ggplot2_3.4.2           [13] gridExtra_2.3           scales_1.2.1            dplyr_1.1.2              loaded via a namespace (and not attached):   [1] Rtsne_0.16             colorspace_2.1-0       rjson_0.2.21           deldir_1.0-9             [5] ellipsis_0.3.2         ggridges_0.5.4         circlize_0.4.15        RcppHNSW_0.4.1           [9] GlobalOptions_0.1.2    clue_0.3-64            rstudioapi_0.14        spatstat.data_3.0-1     [13] farver_2.1.1           leiden_0.4.3           listenv_0.9.0          ggrepel_0.9.3           [17] RSpectra_0.16-1        fansi_1.0.4            codetools_0.2-18       splines_4.2.1           [21] doParallel_1.0.17      polyclip_1.10-4        spam_2.9-1             jsonlite_1.8.5          [25] ica_1.0-3              cluster_2.1.3          uwot_0.1.14            shiny_1.7.4             [29] sctransform_0.3.5      spatstat.sparse_3.0-1  compiler_4.2.1         httr_1.4.6              [33] Matrix_1.5-4.1         fastmap_1.1.1          lazyeval_0.2.2         cli_3.6.1               [37] later_1.3.1            htmltools_0.5.5        tools_4.2.1            igraph_1.4.3            [41] dotCall64_1.0-2        gtable_0.3.3           glue_1.6.2             RANN_2.6.1              [45] fastmatch_1.1-3        Rcpp_1.0.10            scattermore_1.1        vctrs_0.6.2             [49] spatstat.explore_3.2-1 nlme_3.1-157           progressr_0.13.0       iterators_1.0.14        [53] lmtest_0.9-40          spatstat.random_3.1-5  globals_0.16.2         mime_0.12               [57] miniUI_0.1.1.1         lifecycle_1.0.3        irlba_2.3.5.1          goftest_1.2-3           [61] future_1.32.0          MASS_7.3-57            zoo_1.8-12             promises_1.2.0.1        [65] spatstat.utils_3.0-3   parallel_4.2.1         reticulate_1.29        pbapply_1.7-0           [69] stringi_1.7.12         S4Vectors_0.36.2       fastDummies_1.6.3      foreach_1.5.2           [73] BiocGenerics_0.44.0    BiocParallel_1.32.6    shape_1.4.6            rlang_1.1.1             [77] pkgconfig_2.0.3        matrixStats_1.0.0      ROCR_1.0-11            purrr_1.0.1             [81] tensor_1.5             labeling_0.4.2         patchwork_1.1.2        htmlwidgets_1.6.2       [85] cowplot_1.1.1          tidyselect_1.2.0       parallelly_1.36.0      RcppAnnoy_0.0.20        [89] plyr_1.8.8             magrittr_2.0.3         R6_2.5.1               IRanges_2.32.0          [93] generics_0.1.3         pillar_1.9.0           withr_2.5.0            fitdistrplus_1.1-11     [97] survival_3.3-1         abind_1.4-5            tibble_3.2.1           future.apply_1.11.0    [101] crayon_1.5.2           KernSmooth_2.23-20     utf8_1.2.3             spatstat.geom_3.2-1    [105] plotly_4.10.2          GetoptLong_1.0.5       data.table_1.14.8      digest_0.6.31          [109] xtable_1.8-4           tidyr_1.3.0            httpuv_1.6.11          stats4_4.2.1           [113] munsell_0.5.0          viridisLite_0.4.2
--
 
> | >
>

**Comment by rsatija** [comment]
Thanks for catching this. This is a bug, and we've identified the source which we will fix ASAP

**Comment by JABioinf** [comment]
Small related note, but CellCycleScoring and AddModuleScore do not seem to work on split object across layers (right? I got: `"Error in ctrl.scores[i, ] <- Matrix::colMeans(x = assay.data[features.use,  :
  number of items to replace is not a multiple of replacement length
`and `
warning "only the first layer is used"
`). 
If this is not feasible/desirable to apply those function across layers, maybe it should be noted as a small note in v5 vignettes describing basic processing that cell cycle scoring need to be done before split.
