### ISSUE TITLE
Identifying differential expressed genes across different samples

### ISSUE THREAD

**Issue by ArtiCore** [satijalab/seurat#7537]
Hello,

I am following this tutorial for identifying differential expressed genes across samples: https://satijalab.org/seurat/archive/v3.1/immune_alignment.html

I am facing a problem regarding how to select the different groups, while I want to include all the clusters for each condition.

In the tutorial it uses the following code:

t.cells <- subset(immune.combined, idents = "CD4 Naive T")
Idents(t.cells) <- "stim"
avg.t.cells <- log1p(AverageExpression(t.cells, verbose = FALSE)$RNA)
avg.t.cells$gene <- rownames(avg.t.cells)

cd14.mono <- subset(immune.combined, idents = "CD14 Mono")
Idents(cd14.mono) <- "stim"
avg.cd14.mono <- log1p(AverageExpression(cd14.mono, verbose = FALSE)$RNA)
avg.cd14.mono$gene <- rownames(avg.cd14.mono)_

How can I select all the cells and calculate expression for different samples? While the "SetIdent" parameter doesn't accept characters (the column of the metadata with the sample name stored).

Thank you in advance!

**Comment by mhkowalski** [comment]
Hi, you can subset based on other columns in the meta data. For example, to get all cells in g1 of the `pbmc_small` seurat object (included with the package), you can use the following: 

```g1 <- subset(pbmc_small, groups=="g1")```
