### ISSUE TITLE
Weird issue regarding UMAP and processor

### ISSUE THREAD

**Issue by LinearParadox** [satijalab/seurat#7539]
I'm running some of our single cell data on a GCP instance. I got a weird issue where UMAP runs into the error:
"Error in x2set(Xsub, n_neighbors, metric, nn_method = nn_sub, n_trees, : Non-finite entries in the input matrix seurat" when running UMAP on a GCP instance using the C3 configuration. This configuration uses the Intel Sapphire Rapids CPU. When I run UMAP on an N2D or C2 platform, which use AMD Milan Epyc and Intal Cascade Lake respectively as their CPUs, UMAP runs completely fine. This leads me to believe it is for some reason a CPU specific issue.

**Comment by AustinHartman** [comment]
Hi @LinearParadox, Seurat depends on the [uwot](https://github.com/jlmelville/uwot) package for computing UMAP projections. I'd recommend posting this issue there as they'll be best able to address this.
