### ISSUE TITLE
how to display the different sample distribution in one same cluster

### ISSUE THREAD

**Issue by zqyhyunbin** [satijalab/seurat#754]
Dear all,
 i think i meet a problem, i have 5scRNA-seq data in different tissue, and i combined them together, and do the t-SNE plot, so based on one special cluster, i show to do the subcluster.

1. when i pick out the special cluster (like cluster 1), make a seurat object and do the t-SNE again, the shape of it totally changed, why? it that possible keep the original shape?
2. And i wanna see the different sample distribution based on the subcluster result, what should i do, now i see the CCA method could do this, but this method is so different

**Comment by andrewwbutler** [comment]
Hi,

1. The shape of the t-SNE is always going to change if you re-run the algorithm with a different set of points. If you subset the object, the original coordinates are preserved though if you don't re-run t-SNE. 
2. Can you clarify what you mean? I'm not sure I understand the question.
