### ISSUE TITLE
SCT assay in SCTransform V2 integration workflow appears to cause cells with zero counts in a gene to gain expression

### ISSUE THREAD

**Issue by Tommy0398** [satijalab/seurat#7540]
Following on from https://github.com/satijalab/seurat/issues/7123 it appears like cells that had zero counts in certain cells suddenly gain expression for these genes in the SCT assay after following the SCTransform V2 integration pipeline. Reposting here for @saketkc 

RNA assay normalised with NormalizeData:
![CD36_featureplot_RNA_nromalised_scCustomize](https://github.com/satijalab/seurat/assets/84406675/405c0273-3384-4b18-9817-fc0e2d1ba23d)

SCT assay 
![CD36_featureplot_SCT_sccustomize](https://github.com/satijalab/seurat/assets/84406675/51564f7e-4185-4d93-85f0-f4ba4851e56e)

I've subsetted the cells in the bottom left cloud (~1500 cells) using:
```
#Convert to monocles data format to use the cell selector
cds <- SeuratWrappers::as.cell_data_set(Optimals)

#Use the selector to highlight the cloud of cells with new CD36 expression 
cells_selected <- monocle3::choose_cells(cds)

#Determine what the cell Ids are
cells_selected_meta <- as.data.frame(colData(cells_selected))
cells_selected_cell_ids <- row.names(cells_selected_meta)

#Highlight the cell subset to show where they are 
DimPlot(Optimals,cells.highlight = cells_selected_cell_ids)
```
![highlighted_area](https://github.com/satijalab/seurat/assets/84406675/f28985c4-edfb-4d45-9646-0dc2fa6516cc)

Illustrating what is in the selected area as a sanity check
```
#Subset the seurat object based on the cell ids 
Optimals$cells <- colnames(Optimals)

Optimals_subset <- subset(Optimals, cells %in% cells_selected_cell_ids)

#plot just the subset to show the right area has been subsetted
Optimals_subset_temp <- NormalizeData(Optimals_subset, assay = "RNA")
DefaultAssay(Optimals_subset_temp) <- "RNA"
scCustomize::FeaturePlot_scCustom(Optimals_subset_temp,features = "CD36")

DefaultAssay(Optimals_subset) <- "SCT"
scCustomize::FeaturePlot_scCustom(Optimals_subset,features = "CD36")

```
RNA Assay normalised:
![highlighted_area_zoom_RNA_norm](https://github.com/satijalab/seurat/assets/84406675/96a31c78-439d-4059-834f-28da0ff4c7f0)

SCT Assay:
![highlighted_area_zoom_SCT](https://github.com/satijalab/seurat/assets/84406675/5f9374f8-9675-423d-a094-642b527f5ca5)

Extracting the counts in the subsetted area to show the expression level difference in RNA and SCT
```
#Get count data for the normalised RNA assay 
Optimals_subset_RNA <- GetAssayData(Optimals_subset,assay = "RNA",slot = "data")
Optimals_subset_RNA_CD36 <- Optimals_subset_RNA_CD36 <- Optimals_subset_RNA["CD36",]
#Identify cells with zero counts in the RNA assay
Optimals_subset_RNA_CD36_zero <- Optimals_subset_RNA_CD36[Optimals_subset_RNA_CD36 == 0]

#Sanity check
sum(Optimals_subset_RNA_CD36_zero)
  #0
length(Optimals_subset_RNA_CD36_zero)
  #1517

#Get count data for the SCT assay 
Optimals_subset_SCT <- GetAssayData(Optimals_subset,assay = "SCT",slot = "data")
Optimals_subset_SCT_CD36 <- Optimals_subset_SCT["CD36",]

#Subset to the same cells in the zero count RNA assay 
Optimals_subset_SCT_CD36_zero <- Optimals_subset_SCT_CD36[names(Optimals_subset_SCT_CD36) %in% names(Optimals_subset_RNA_CD36_zero)]

#Sanity check
sum(Optimals_subset_SCT_CD36_zero)
  #346.57
length(Optimals_subset_SCT_CD36_zero)
  #1517

sum(Optimals_subset_SCT_CD36_zero != 0)
  #500
setequal(names(Optimals_subset_SCT_CD36_zero),names(Optimals_subset_RNA_CD36_zero))
  #TRUE
```

So here it looks like 500 of the 1517 cells in the subset that have zero expression in the RNA assay have gained expression in the SCT assay.

**Comment by saketkc** [comment]
Can you share the object with me? My email is schoudhary@nygenome.org

**Comment by saketkc** [comment]
Thanks for sharing the object @Tommy0398. What you are observing is more of a feature of SCTransform. When correcting counts - the model predicts what observed counts would be if the entire dataset was to be sequenced to a median sequence depth using the pearson residuals - i.e., an average model of technical noise. In this case the mode predicts that given the model for technical noise in the dataset the observed counts for CD36 are high. It is not hard to see why:

```r

df <- FetchData(object = object.orig, vars = c("sct_CD36", "rna_CD36", "nCount_RNA", "nFeature_RNA", "nCount_SCT"))
df$log10_nCount_RNA <- log10(df$nCount_RNA)
df$log10_nCount_SCT <- log10(df$nCount_SCT)

df$sct_minus_rna <- df$sct_CD36 - df$rna_CD36
df_pos <- df %>% dplyr::filter(sct_minus_rna>0)
df_rna_zero <- df %>% dplyr::filter(rna_CD36==0)


p1 <- ggplot(df_rna_zero, aes(rna_CD36, sct_CD36, color=log10_nCount_RNA)) + geom_jitter() + geom_abline() + scale_color_viridis()
p2 <- ggplot(df_rna_zero, aes(rna_CD36, sct_CD36, color=log10_nCount_SCT)) + geom_jitter() + geom_abline() + scale_color_viridis()

p1 | p2
```



![image](https://github.com/satijalab/seurat/assets/682153/c83a85df-90ab-4633-bdea-f3839337a9b6)


What the above plot is telling you is those cells have been sequenced to a higher depth during the correction step - resulting in higher CD36 counts. Hope this makes sense. Please feel free to reopen with follow up questions!

**Comment by Tommy0398** [comment]
Thanks for looking into this @saketkc.

My main question is whether you think this is fine to use in downstream analysis? I'm interpreting this as the SCT model predicts that those cells would have had expression in CD36 if the sequencing depth was higher and so the SCT adjusted counts shows expression for CD36 for those cells where it wasn't observed in the raw data. Assuming that the SCT assay's prediction is correct is it fine to continue using SCTransform in visualization and differential expression analysis or would it be better to use the RNA assay for this? 

Also just to get a better understanding as to why this occurs. Is it because those cells generally have lower sequencing depth than the other cells in the datasets and so the expression gets adjusted?

**Comment by saketkc** [comment]
> My main question is whether you think this is fine to use in downstream analysis? I'm interpreting this as the SCT model predicts that those cells would have had expression in CD36 if the sequencing depth was higher and so the SCT adjusted counts shows expression for CD36 for those cells where it wasn't observed in the raw data. Assuming that the SCT assay's prediction is correct is it fine to continue using SCTransform in visualization and differential expression analysis or would it be better to use the RNA assay for this?

Totally fine to use for both. By default `NormalizeData` uses a scale factor of 10000, but in this case (at least in the subset) the median sequencing depth is higher so you can argue that using a smaller sequencing depth (if you are using the default scale factor for NormalizeData) is dampening the signal a bit. It also cannot handle the zeros (so they will remain as such). SCT on other hand is using the model of technical noise to calculate for the median sequencing depth what the observed counts would be (you can also provide it a smaller scale factor such as 10000 by using the `scale_factor` argument when running SCTransform) and compare against Log normalization approach.

> Also just to get a better understanding as to why this occurs. Is it because those cells generally have lower sequencing depth than the other cells in the datasets and so the expression gets adjusted?

Hopefully the above explaination answers this. Feel free to post any remaining questions.
