### ISSUE TITLE
differential expression gene analysis for each celltype between groups by FindMarkers have very few genes after filtered

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#7543]
Dear Seurat team,
Thank you very much for your excellent work, and hope you are all well.
Here is my questions: 
The data has been pre-processed and integrated, the cell numbers is 4451, 10635, 19311 and 91234. 
I did DEG analysis between groups(drug and ctrl) for each cell type by FindMarkers, and I only got less than 50 DEGs for each cell type, that's weird. 
the code: 
DEG_groups <- FindMarkers(Seurat_Obj, ident.1 = "FBLI", ident.2 = "FB93",
                              min.pct = 0.25, assay = "RNA") %>% 
      filter(p_val_adj < 0.05)
I checked the group assigned to each cell is correct, Did I use the wrong methods? Do I need to use counts slot, then what function and test method should be used? 
Also, the analysis returns average log2FC. For a specific differential expression gene, what if most cells express low levels but a small proportion of the cells express very high, which is different from most cells expressing a median level that is close to the average log2FC, right? how can I fix this problem? 

Thanks a lot!

**Comment by yulchen810** [comment]
By the way, when I do normalization and scaling, I used the following code. I scaling all genes after FindVariableFeatures, is that correct? could that be the reason I got a weird DEG result? maybe I should use the default mode that only variable genes to be scaled?
    Obj <- NormalizeData(Obj, normalization.method = "LogNormalize", scale.factor = 10000)
    Obj <- FindVariableFeatures(Obj, selection.method = "vst", nfeatures = 2000)
    all.genes <- rownames(Obj)
    Obj <- ScaleData(Obj, features = all.genes)
    Obj <- RunPCA(Obj, npcs = nPCs)

**Comment by mhkowalski** [comment]
Hi, you are setting `min.percent = 0.25`, which is higher than the default value of `0.1` and may reduce the number of genes that are differentially expressed, as this requires the gene to be captured in at least 25% of cells in both populations. You could also try adjusting other parameters in `FindMarkers` (see documentation for more details), but it's hard to know how many differentially expressed genes you should expect to find.

We don't recommend you use the counts slot for differential expression. The results of differential expression will not be affected by which genes are scaled, as the function by default uses the `"data"` slot and not `"scale.data"`. 

Re your question on a small proportion of cells expressing a gene very highly, the `pct.1` and `pct.2` values in the output allow you to differentiate this case, as a cell that is highly expressed in a low proportion of cells will have a low value here.

Hope this is helpful!

**Comment by yulchen810** [comment]
> 

That's helpful. Thank you!
