### ISSUE TITLE
Regarding Seurat integration

### ISSUE THREAD

**Issue by swainasish** [satijalab/seurat#7547]
I have 3 datasets, Control, Treated-1, Treated-2. Control and Treated-1 coming from one experiment. Treated-2 coming from second experiment (having another GEO accession ID). When I integrate all three, Control and Treated-1 have similar UMAP distribution and Treated-2 have different UMAP distribution. Not a single cell have the shared space. 
Q1. What is the possible problem ?
Q2. Can we integrate all three by taking another data from (TabulaSapiens) as reference ?

**Comment by mhkowalski** [comment]
Q1: I'm not sure of the problem without seeing your full code. Are you following the integration vignette, and making sure to integrate different experimental conditions separately?

Q2: Yes, we have built extensive tools for annotating datasets using reference datasets, as shown [here](https://satijalab.org/seurat/articles/integration_mapping.html). We also have developed a toolkit, [Azimuth](https://azimuth.hubmapconsortium.org), that automatically processes and annotates scRNA-seq data using reference datasets. I can't recommend a particular reference without knowing what type of cells you are working with. 

Hope this is helpful!
