### ISSUE TITLE
MetageneBicorPlot

### ISSUE THREAD

**Issue by kvnlmei** [satijalab/seurat#755]
Hi, when I RunCCA and generate a MetageneBicorPlot, I get a graph that looks like this:

<img width="886" alt="screen shot 2018-09-05 at 11 20 33 am" src="https://user-images.githubusercontent.com/31289107/45103362-bf730200-b0fd-11e8-9140-6b904928f69b.png">

It's not a smooth downward curve. What does it mean that the graph goes up? Does this mean that for some of the higher CC numbers, the amount of variance explained is greater than lower numbered CC's? If that's true, how are CC's ordered if not by amount of variance explained? 

Thank you!

**Comment by andrewwbutler** [comment]
Hi,

As mentioned in #323 and #609, these curves are not guaranteed to be monotonically decreasing. For a complete description of how we construct these curves, please see the "CC selection for downstream analysis" heading of [methods section](https://www.nature.com/articles/nbt.4096#methods) of the paper.
