### ISSUE TITLE
How to build a Neighbor object from a graph?

### ISSUE THREAD

**Issue by frankligy** [satijalab/seurat#7550]
Hello,

I have a simple question that I can not find a straightforward instruction online, I have a matrix of the shape (n_cells, n_cells), this is a distance matrix that I derived from another program. I am hoping to use that to replace some of the slots in the Seurat object, particularly, the `Graph` and `Neighbor` objects. 

Replacing Graph is easier, I just need to use `as.Graph` to convert a sparse matrix to a Graph object, but if I want to have a Neighbor object of the shape (n_cells, 20) as Seurat normally does, how can I do that? Shall I use something like `as.Neighbor(graph)` or FindNeighbors functions?

Thanks a lot,
Frank

**Comment by yuhanH** [comment]
Hi, You can use this `NNtoGraph` internal function to convert the neighbor object into KNN graph. 
for example, 
```
pbmc_small <- FindNeighbors(pbmc_small, return.neighbor = T)
graph <- Seurat:::NNtoGraph(nn.object = pbmc_small[['RNA.nn']])
```
