### ISSUE TITLE
How FindMarkers "avg_log2FC" works, and why is it different from what is calculated from the FoldChange function and manual calculation?

### ISSUE THREAD

**Issue by jabatin** [satijalab/seurat#7551]
Hi,

To begin, I've reviewed a previous issue listed here: https://github.com/satijalab/seurat/issues/467, as well as reviewed the code  in https://github.com/satijalab/seurat/blob/96d07d80bc4b6513b93e9c10d8a9d57ae7016f9f/R/differential_expression, but I did not find the answer to my issues there. 

Question 1: Why does the values from FindMarkers and FoldChange functions give different results? (I could not find the source code of FoldChange to compare)

FindMarkers Code: FMtest <- FindMarkers(object, ident.1 = "x" ,ident.2 = "y", min.pct = 0.1, logfc.threshold = 0.25, test.use = "wilcox")
FindMarkers Result: object["Fosb",]  -----------> the logFC is 0.7928
FoldChange Code: FoldChange(object, ident.1 = "x",ident.2 = "y", features = c("Fosb"),pseudocount.use = 1)
FoldChange Result: -----------------------------> the logFC is 0.4409

Question 2: Why I am not able to replicate the calculated avg_log2FC using snippets from the source code?

Looking at the code, avg_log2FC is calculated directly from "total.diff" as according to the code:
"to.return[, "avg_logFC"] <- total.diff[rownames(x = to.return)]".

And total.diff is directly calculated using the code here:
data.1 <- apply(X = data.use[genes.use, cells.1, drop = F], MARGIN = 1, FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))
data.2 <- apply(X = data.use[genes.use, cells.2, drop = F], MARGIN = 1, FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))
total.diff <- (data.1 - data.2)

Inputting my data.....using normalized data from the @data 
for data.use I substituted in these variables...where I split the seuratobject into subsets of x and y identities.
(data.1) data.use_x <- object_x[["RNA"]]@data
(data.2) data.use_y <- object_y[["RNA"]]@data
genes.use = "Fosb"
cells.1 = colnames(object_x)
cells.2 = colnames(object_y)

Results:
data.1 = 8.42
data.2 = 5.49
total.diff = 2.93

This result is completely different from the 0.7928 calculated using the FindMarkers function and thus my confusion. I notice that a log2 function wasn't passed in my code but I did not find that anywhere in the differential_expression source code. I would really love to understand better how the avg_log2FC values are being calculated to understand the math behind it.

Thanks for any help!

**Comment by jabatin** [comment]
Thank you, that is exactly what I was looking for!

**Comment by samuel-marsh** [comment]
Happy to help!
