### ISSUE TITLE
[Seurat5]: SCTModel.list contains only a subset of feature attributes after calling SCTransform

### ISSUE THREAD

**Issue by Gilquin** [satijalab/seurat#7557]
Running `SCTransform` on a Seurat v5 object (`Assay5` class for **RNA** assay) will return an `SCT` assay where any of the `SCTModel` may miss some `feature.attributes` if the number of cells is less than the argument `ncells` (default to 5000). In this case, the following subset of `feature.attributes` is lost: `detection_rate`, `gmean` and `variance`.

The culprit is a call to the function `SCTModel_to_vst` which [skips](https://github.com/satijalab/seurat/blob/c8e2e6771d9ba6adb333fdce47dd5738594df7ad/R/preprocessing.R#L5177) the fields `detection_rate`, `gmean` and `variance`.

 This removes the possibility of using the function `VariableFeaturePlot` on the newly created **SCT** assay (which calls `HVFInfo.SCTAssay` which itself searches for `gmean` and `variance`, see the [corresponding line](https://github.com/satijalab/seurat/blob/763259d05991d40721dee99c9919ec6d4491d15e/R/objects.R#L1543)).
<br/>

Is this intended or not? If not, a possible solution would be to add the following line:
```r
vst_out.reference$gene_attr <- local.reference.SCT.model@feature.attributes
```
[there](https://github.com/satijalab/seurat/blob/c8e2e6771d9ba6adb333fdce47dd5738594df7ad/R/preprocessing5.R#L1590C1-L1590C1), in the `SCTransform.StdAssay` function body.
<br/>

Here is a reproducible example:
```r
options(Seurat.object.assay.version = "v5")

# Load data
Sobject <- Seurat::UpdateSeuratObject(pbmc3k.SeuratData::pbmc3k)

# Create Seurat v5 object
SobjectV5 <- SeuratObject::CreateSeuratObject(
  counts = SeuratObject::CreateAssay5Object(counts = Sobject[["RNA"]]@counts),
  assay = "RNA",
  meta.data = Sobject@meta.data,
  project = Sobject@project.name
)

# SCT normalization
SobjectV5 <- Seurat::PercentageFeatureSet(SobjectV5, pattern = "^MT-", col.name = "percent.mt")
SobjectV5 <- Seurat::SCTransform(
  SobjectV5,
  vst.flavor = "v2",
  vars.to.regress = "percent.mt",
  seed.use = 404,
  ncells = 2000
  )

# Check the missing columns
str(SobjectV5[["SCT"]]@SCTModel.list$model1@feature.attributes)
```
Note that running the example with `ncells = 5000` returns the full set of `feature.attributes` as an "edge" case.

**Comment by saketkc** [comment]
Thank you @Gilquin for a reproducible example. We should support it and will release a fix soon.

**Comment by saketkc** [comment]
Hi @Gilquin, thanks for the reproducible example. This has been fixed internally and will be in the official Seurat V5 release.
