### ISSUE TITLE
stacked violinplot

### ISSUE THREAD

**Issue by thamsepia** [satijalab/seurat#7558]
Is there a way to visualise the average expression of a list of genes in a specified cluster  (ie compare expression levels of the genes in the same cluster) as a violin plot instead of a dotplot or heatmap?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  If you are looking simply for stacked violin plot you can do that by setting `stack = TRUE` in the call for `VlnPlot`.  Another option is the `Stacked_VlnPlot` function from my package scCustomize (https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#stacked-violin-plots).

Violin plots are by their nature though not plotting the average expression.  Their shape is indication of distribution of all of the points in the data, not just the average.  So if you are strictly looking to plot just the averages of expression within a cluster then Violin plots are probably not what you are looking for.  The exception could be if you wanted to create violin plot showing the distribution of average gene expression within a cluster for each sample in the dataset.  You could do this by pulling and arranging the data from Seurat object and then manually plotting using ggplot2 and `geom_violin`.  In this case the violin's shape would represent the distribution of average gene expression within each sample for each cluster.

Best,
Sam
