### ISSUE TITLE
JackStrawPlot - error max dimension is 0

### ISSUE THREAD

**Issue by paolabc** [satijalab/seurat#7562]
Hi There

I am trying to see if  my 20 PC are significant from my integrated seurat object by uisng JackStrawPlot. But it does not work and an error appears. By evaluating my  ElbowPlot, I was expecting at leat 15 signifcant PC.

`JackStrawPlot(merged_filtered_seurat,reduction = "pca",dims = 1:20) 
`
Error in JackStrawPlot(merged_filtered_seurat, reduction = "pca", dims = 1:20,  : 
  Max dimension is 0

Thank you for your support.

Paola

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but can be helpful.  Did you run `JackStraw` and `ScoreJackStraw` before calling `JackStrawPlot`?

If not try running those functions and then running the plot function?  See this previous issue (https://github.com/satijalab/seurat/issues/6349#issuecomment-1228833498).

If you have already run those commands can you post full code that you ran and copy of the output of `sessionInfo()`?

Best,
Sam

**Comment by paolabc** [comment]
Hi,

Thank you for your answer. Yes, I did not run these functions before JackStrawPlot. I thought this could be inside of SeuratObject. Thank you for letting me know. Now it woks!

Best,
Paola

**Comment by samuel-marsh** [comment]
Great! Happy to help!
