### ISSUE TITLE
Switching Versions between Seurat 4.3 to Seurat 5

### ISSUE THREAD

**Issue by BaluPai** [satijalab/seurat#7563]
Hi,
I am currently running into issues when I switch to Seurat V5.

I have been using Seurat 4.3 available on our servers for creating my initial objects from snRNAseq data.
Since I have some new Spatial data, which I am planning to compare with the snRNAseq data, I started switching to Seurat V5 but I am getting error during integration or running SCTransform etc. 

Is it the best to stay with Seurat 4.3? Would it be still possible to do multimodal analysis with spatial data ?
I am new to single-cell world, especially ST analysis.

Any help or suggestion appreciated. (related: #7187)
Thanks

Example of errors I got:
1)
> ####This worked when run on R/4.3.0 with latest seurat version v5.0
> Idents(GBMCX)<- "sample"
> GBM<- subset(GBMCX, idents = c("2C","20C","31C"), invert = TRUE)
**Error in intI(j, n = d[2L], dn[[2L]], give.dn = FALSE) : 
  invalid character indexing
In addition: Warning message:
In cells.idents["NA"] <- names(x = which(x = is.na(x = Idents(object = object)[cells]))) :**

2)##Have to switch to Seurat 4.3. from Seurat V5.0 and then it works
> for (i in 1:length(GBM_list)) {
+   GBM_list[[i]] <- SCTransform(GBM_list[[i]], vst.flavor = "v2", method = "glmGamPoi_offset", ncells = 2000, exclude_poisson = TRUE,verbose = FALSE)
+ }
**Error in make_cell_attr(umi, cell_attr, latent_var, batch_var, latent_var_nonreg,  : 
  count matrix must have row and column names**

3) ####But then this step gives error in Seurat 4.3
> GBM_Integrated_SCT <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
**Error in GetAssayData(object = object, assay = umi.assay, slot = "counts")[features_to_compute,  : 
  no 'dimnames' attribute for array**

**Comment by saketkc** [comment]
Can you share one of your objects that is causing the error? My email is schoudhary@nygenome.org

**Comment by saketkc** [comment]
Thanks for sharing your object. Though I don't get any error with this object using Seurat V4 or V5. Can you share the object that is erroring?

**Comment by saketkc** [comment]
Also, just `object <- SCTransform(object, vst.flavor="v2")` should suffice for invoking `v2`.

**Comment by BaluPai** [comment]
Hi Saket,

GBM1_17273_adultCXref_inferCNV_030723.rds
<https://mtsinai-my.sharepoint.com/:u:/r/personal/balagopal_pai_mssm_edu/Documents/GBM1_17273_adultCXref_inferCNV_030723.rds?csf=1&web=1&e=plfXt4>
GBM1_ErrorOnR4.2Seurat4.3_forSaket.docx
<https://mtsinai-my.sharepoint.com/:w:/r/personal/balagopal_pai_mssm_edu/Documents/GBM1_ErrorOnR4.2Seurat4.3_forSaket.docx?d=wea57f828d9204023b392376ff8303add&csf=1&web=1&e=aTodnw>
The earlier object was one among 6 samples that I tried to integrate and
then got the error as shown in the document that I shared with you
(previous email).
Here is the object that gives the error while using the Subset function,
depending on the version.
I have also attached a document showing the error/ or not depending on the
version used and the session information.

Thanks so much for your help. I really appreciate it.

Best regards,
Balu

**Comment by saketkc** [comment]
Hi @BaluPai, Can you share the objects over email? Thanks!

**Comment by saketkc** [comment]
Thanks for sharing your object. I am not sure I understand the goal of subsettting here:

```r


> z <- readRDS("GBM1_17273_adultCXref_inferCNV_030723.rds") 
> Idents(z) <- "sample" 
> table(Idents(z))  

  2C  20C  31C 
2624 2563 3213 
```

Doing  `GBM1<- subset(GBM1_CX, idents = c("2C","20C","31C"), invert = TRUE)` will force it to select cells which do **not** belong to 2C/20C/31C label when there are none.

**Comment by BaluPai** [comment]
The object I shared with you is a merged object. And with this step I would like to remove the object that has a metadata column named "sample" (with IDs 2C, 20C and 31C) whereas the other object neither has those IDs, hence NA (nor had sample column).
But the main issue here is this subsetting works on v5 but fails in v4.3, with the same objects.

**Comment by saketkc** [comment]
Right. The ideal thing to do here is to set the `NA` samples to something else "unknown".

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
