### ISSUE TITLE
Multimodal Reference Mapping with Low Cell Numbers

### ISSUE THREAD

**Issue by me-orlov** [satijalab/seurat#7564]
Dear Seurat developers and community,

I have a dataset of control and treatment samples that get integrated to generate a UMAP and sequencing-depth-corrected (in the SCT assay) using PrepSCTFindMarkers. I am then subsetting out the immune cell clusters to map those cells onto a peripheral immune cells reference, as described in the multimodal mapping vignette. However, I am running into the following issue -  some of my samples have very few immune cells (~50-100). I can get the analysis to run by setting a higher k.anchor in FindTransferAnchors, but I am generally concerned about results generated from so few cells as being unreliable. In addition, when creating a de-novo visualization, to look for cells that will not be found in the reference dataset, I find very little overlap, wherein I would expect significant overlap.  

Having looked through similar questions, I know that I could try merging the samples (all the controls together, and all the treatments together) to yield higher cell numbers. However, I am concerned about batch effects. If I merge all the controls together, for example, and use the RNA assay for the merged query to recompute the residuals with the reference SCT model, will the different sequencing depths of the different samples pose a problem? I believe FindTransferAnchors requires the "raw", depth-uncorrected RNA assay for the query. Should I use the integrated SCT assay of the query in the mapping? I would appreciate if someone could walk me through this. 

If there is a better way to handle samples with low cell counts, I would love to hear about it.

Thank you for your time and patience!

**Comment by me-orlov** [comment]
As a follow-up question: When I try to run ```FindTransferAnchors``` with a query object that only has the SCT assay and no RNA assay, I get the following error: 

```
"Error: Query assay provided is an SCTAssay based on an orignal UMI assay that is no longer present in the query Seurat object. Unable to recompute residuals based on the reference SCT model."
```

Sorry if this is a dumb question, but I would greatly appreciate it if someone could explain it to me. Am I correct in understanding that this function requires both the SCT (for ```normalization.method = "SCT"```) and the RNA assays to be present in the query object?

**Comment by me-orlov** [comment]
As a follow-up, it would be great to get more clarification about https://github.com/satijalab/seurat/issues/5843. It was asking which assay to use for the query, not the reference, but the given answer pertained to the reference. Thank you!

**Comment by rsatija** [comment]
There's not really an easy answer to this question. The methods in Seurat (as well as Scanpy) are largely based off of the context of neighbor graphs, which assume that each cell in the dataset have a number of similar 'neighbor' cells (i..e k=20). This assumption will be violated for small datasets of 50-100 cells. my suggestion would be to merge the samples and not perform integration. The 'batch effects' will not invaldate your downstream analysis, but may require you to annotate the same cell type in multiple clusters.

**Comment by me-orlov** [comment]
Thank you for your prompt reply, I was also thinking there isn't a simple answer here! Good to know - I will stay away from using small datasets individually. I have a few follow-up questions, if you don't mind:

To begin with, each of my samples has sufficiently large cell numbers. As such, I use integration to generate a UMAP and manually (via DE and inspection) assign IDs to the generated clusters. Then I subset out the immune cell clusters only and split by sample - that's where I start having 100-200 cells in some samples. To avoid this, I have split the object by control vs. treatment (each containing several samples), so that I have sufficient cell numbers, like you suggest. The code I use here is:

```
subSeurat <- subset(Seurat.allIntegrated, idents = clustersTOKeep)
Seurat.split <- SplitObject(subSeurat, split.by = "treatment")
Control <- Seurat.split[[1]]
Treated <- Seurat.split[[2]]
```

Suppose I have 3 subsetted control samples, obtained by the method above and merged in ```Control```. ```Control```'s SCT assay now consists of 3 individual SCT models, one for each sample. ```Control``` also has a subset of the original, total "integrated" SCT assay. I am wondering: what would be the difference, conceptually, between using ```Control[["SCT"]``` and ```Control[["integrated"]]``` as my query for FindTransferAnchors and MapQuery. 

i.e. 
1) Version 1:
```
anchors_int <- FindTransferAnchors(
    reference = reference,
    query = Control,
    query.assay = "integrated",
    k.filter = NA,
    reference.reduction = "spca", 
    reference.neighbors = "spca.annoy.neighbors", 
    dims = 1:50,
    normalization.method = "SCT"    
  )
```
and 

2) Version 2:

```
anchors_SCT <- FindTransferAnchors(
    reference = reference,
    query = Control,
    query.assay = "SCT",
    k.filter = NA,
    reference.reduction = "spca", 
    reference.neighbors = "spca.annoy.neighbors", 
    dims = 1:50,
    normalization.method = "SCT"    
  )
```
Q1: Is there a specific reason not to use the original integrated assay here? Is it because it will only contain SCT data for the 3,000 features originally used in the integration (prior to any subsetting)? 

Q2: In addition, would it be better to merge the samples and re-run the SCT on them as a whole, and make a single SCT model, before finding the anchors, instead of either Version 1 or 2?

Q3: Do sequencing depth differences between samples pose an issue for FindTransferAnchors and MapQuery, or are they taken care of because Pearson residuals are used (I know the within-sample sequencing depth differences would be!)?

Sorry for asking so many questions. I am new to the field and truly appreciate any extra guidance you can provide.
