### ISSUE TITLE
How to create Seurat object from 10x h5 files for multimodal WNN analysis? 

### ISSUE THREAD

**Issue by xgongatsynthekine** [satijalab/seurat#7567]
Hi, 

I tried to use WNN model for 10x CITE-seq data analysis. I can exactly repeat what described here: https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html, which means my R setting is correct.

But I ran into issue when I do analysis for my own dataset.

I have two samples merged in a h5 file (filtered_feature_bc_matrix.h5) from CellRanger, and I tried to create a Seurat object from this h5 file using the below command line:
file = '/path/filtered_feature_bc_matrix.h5'
sample.m = Read10X_h5(file, use.names = TRUE, unique.features = TRUE)
rna_counts = sample.m$`Gene Expression`
adt_counts = sample.m$`Antibody Capture`

data = CreateAssayObject(counts = rna_counts)
adt.data = CreateAssayObject(counts = adt_counts)
data[['ADT']] = adt.data

It gave error message:
Error in `[<-.data.frame`(`*tmp*`, , i, value = new("Assay", counts = new("dgCMatrix",  : 
  replacement has 137 rows, data has 36601

Can you please let me know how to generate data from 10x h5 file equivalent to the data bm in the tutorial (https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html)?

In this document https://github.com/satijalab/seurat/blob/master/vignettes/weighted_nearest_neighbor_analysis.Rmd, it is very clear how to read 10x data for scRNA and scACAT, but for CITE seq, there is no publicly available document which gives instruction how to create Seurat object from 10x h5 file directly. Could you please kindly give more instruction for this purpose so that more people can use WNN from 10x h5 file directly? Thanks!

**Comment by AustinHartman** [comment]
In the line ```data[['ADT']]] = adt.data``` you are attempting to add an assay containing ADT counts to an assay containing RNA counts. To construct an object with two separate assays, one containing RNA counts and one containing ADT counts, try the following:
```r
object = CreateAssayObject(counts = rna_counts)
adt.data = CreateAssayObject(counts = adt_counts)
object[['ADT']] = adt.data
```
