### ISSUE TITLE
Run KEGG in Seurat object

### ISSUE THREAD

**Issue by krigia** [satijalab/seurat#7568]
@troels @pmarks @mxposed @zeehio @smoe 
Hello Seurat team,

I am running GSEA analysis in 10X spatial and scRNA-seq data and I would like to use KEGG dataset.
Which function/category should I run?
For Hallmark, I run _m_df<- msigdbr(species = "Homo sapiens", **category = "H**")_

but category = "KEGG" does not work.

Thank you.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  This question doesn't appear to be related to the Seurat package but about the msigdbr package.  I would suggest posting to the repo for that package for help with their functions (`msigdbr(...)`)

Best,
Sam

**Comment by krigia** [comment]
Thank you, Sam.

Best

From: Samuel Marsh ***@***.***>
Reply-To: satijalab/seurat ***@***.***>
Date: Thursday, July 13, 2023 at 6:53 PM
To: satijalab/seurat ***@***.***>
Cc: "Giannikou, Krinio" ***@***.***>, Author ***@***.***>
Subject: Re: [satijalab/seurat] Run KEGG in Seurat object (Issue #7568)


        External Email - Use Caution

Hi,

Not member of the dev team but hopefully can be helpful. This question doesn't appear to be related to the Seurat package but about the msigdbr package. I would suggest posting to the repo for that package for help with their functions (msigdbr(...))

Best,
Sam

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1fQtnDrPAJ0KF-24uoyupnp_O5m-LRr_mpDRz96UBOnocXlNarB_oRtMXcn_20myoxN7hdF7lEEgtQWDlRGt92EbWishJ66vKhyL7B_DXpwANqolYrn33iw1d33_KhBjsZPIjWM1j6n-onoIktgsYR1bBL74Z9a9H3J72O4YKkZbP4Acyn60v_DPDmEDJC749pIkWYi92cgKy8epglCTm5yLjm5dBty_gEYgNfH0luZVCeNakP312BVP8DGHHYxe7ChpasbhBk7i0ALL--UqtVzxj1F9ACwiaJeqJ574_u0vPaoqUEgzGxG4K9-7laIohM9AFFNQ3Rif-QUv-5GrNvA/https%3A%2F%2Fgithub.com%2Fsatijalab%2Fseurat%2Fissues%2F7568%23issuecomment-1635147299>, or unsubscribe<https://secure-web.cisco.com/1fOElalcCSUu2Lxj6BPiXJCqlLlGsqgIx-JWPdDsN5jxIoPp_0shhrXEVPH5SE6cnnCIPDDCkH9wGiDLjTC2koQqHcB4jysF7rvezax0NTCkyDD7tm7ZDh6oI8TiZ3G0d3yfSEfQzsQqZA1fZn8qDWXd8iCpMMxcvBkMsXsNmFbgaAJrBy5SDZbB8NLmEwky5SJdJl13e64pyPLwfFv0rpncMEgMAST8HOwFT0DSYVOmVhSIP0x-4-qnilIMOGAt_CoLqrtHI6gWq0E1-MvDvzqkVIlKiXwIR1HLdW-Yh4jHiWH6ZSr-TpVGTmVkBE8bZcQtfasamtgmBgO0fY5HSFg/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXYDRTJEIMS4UMPMWTFYK5DXQCRBJANCNFSM6AAAAAA2JUPVLM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.
