### ISSUE TITLE
Feature Plot bringing positive dots to the front

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#757]
Hello everyone,
I'm doing Feature plots for a specific gene, and in the same cluster I have cells that express and does that doesn't express this specific gene. Is there a way to bring the positive cells to the front? I can see that some cells express the gene but the dot is behind other negative ones.
Thank you

**Comment by leonfodoulian** [comment]
Hi @EDYAC,

You can check [this function](https://github.com/satijalab/seurat/issues/235#issuecomment-351479800) I had shared a while ago (issue #235). You should use the `customize_Seurat_FeaturePlot()` function. Simply run it on your R session before executing the following code:

```R
# Set do.return = TRUE to return ggplot2 object 
p <- FeaturePlot(object = object, features.plot = "Actb", do.return = TRUE) 

# Customize plot by bringing cells with higher expression levels to the front
customize_Seurat_FeaturePlot(p = p, expression.threshold = 0)
```

Best,
Leon

**Comment by EDYAC** [comment]
Thank you Leon

**Comment by smithsl** [comment]
Hi, sorry to wade in on this question.
@leonfodoulian, is it possible to tweak the code you wrote for issue #235, so that it will work with brewer.pal for a continuous colour scale using the gradient.use argument?
Thanks,

**Comment by smithsl** [comment]
Thank-you!

**Comment by CodeInTheSkies** [comment]
Here is an alternative solution, explained here: 
https://github.com/satijalab/seurat/issues/235#issuecomment-454937420

**Comment by tmccra2** [comment]
Does anyone know how to do this with the new Seurat V3?

**Comment by ekaitya** [comment]
I would like to second tmccra2's question.  How do we execute this function in Seurat V3?

**Comment by kmshort** [comment]
In Seurat v3, FeaturePlot now has baked in tools:
order = FALSE (default) set as TRUE will plot higher values on top of lower values.. doing the ordering for you.
min.cutoff = NA (default), set as a number to remove cells below a certain expression level.
max.cutoff = NA (default), set as a number to remove cells above a certain expression level.

The only thing it doesn't implement now is ALPHA. Which would be awesome.

**Comment by Prakrithi-P** [comment]
> ```r
> p <- FeaturePlot(object = object, features.plot = "Actb", do.return = TRUE) 
> ```

Hi  Leon,
when I try to run this I get the error: 'unused arguments (features.plot = "my_gene", do.return = TRUE)'
when I run 
p <- FeaturePlot(so, features = "my_gene"), I get 'Error in order(p$data$gene) : argument 1 is not a vector

' .. And when I  do
p <- FeaturePlot(so, features = "uTAR952")
p$data$gene<-p$data$my_gene
# Customize plot by bringing cells with higher expression levels to the front
customize_Seurat_FeaturePlot(p = p, expression.threshold = 0)

I get 'Error: Index out of bounds'

I couldn't figure out what I'm doing wrong. Could you please help with this.

Thanks,
Prakrithi

**Comment by leonfodoulian** [comment]
Hi @Prakrithi-P,

If you are using Seurat v3 or higher, the [`customize_Seurat_FeaturePlot`](https://github.com/satijalab/seurat/issues/235#issuecomment-351479800) function will not work. However, you'll find an answer to your question in the previous comment by @kmshort.

Best,
Leon

**Comment by RajneeshSrivastava** [comment]
Certainly, order=T works!
```
FeaturePlot(object = seurat.object, features = "CD68", raster=F,order=T)+ scale_colour_gradientn(colours =c("grey","red","black"))
```
