### ISSUE TITLE
sh: line 1: 155023 Segmentation fault R_TESTS= '/share/soft/apps/R-4.1.2/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpOErley/file25d3e4c664076'

### ISSUE THREAD

**Issue by karlie002** [satijalab/seurat#7570]
when I trying to install the packages "Seurat" with command install.packages("Seurat"),I met a problem like this :

sh: line 1: 155023 Segmentation fault      R_TESTS= '/share/soft/apps/R-4.1.2/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpOErley/file25d3e4c664076'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE)
 7: (function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE))(<environment>),     error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
17: asNamespace(ns)
18: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
19: loadNamespace(package = package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, partial = TRUE)
20: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
21: suppressPackageStartupMessages(loadNamespace(package = package,     lib.loc = lib.loc, keep.source = keep.source, keep.parse.data = keep.parse.data,     partial = TRUE))
22: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     keep.parse.data = keep.parse.data, compress = compress, set.install.dir = set.install.dir)
23: tools:::makeLazyLoading("Seurat", "/share/home/wuqian/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-Seurat/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/share/home/wuqian/R/x86_64-pc-linux-gnu-library/4.1/Seurat")
An irrecoverable exception occurred. R is aborting now ...
ERROR: lazy loading failed for package ‘Seurat’

<Session Info>
 R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /share/soft/apps/R-4.1.2/lib64/R/lib/libRblas.so
LAPACK: /share/soft/apps/R-4.1.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sp_2.0-0

loaded via a namespace (and not attached):
 [1] lattice_0.21-8      fansi_1.0.4         dplyr_1.1.2         utf8_1.2.3          grid_4.1.2          R6_2.5.1            lifecycle_1.0.3    
 [8] gtable_0.3.3        magrittr_2.0.3      scales_1.2.1        pillar_1.9.0        ggplot2_3.4.2       rlang_1.1.1         cli_3.6.1          
[15] rstudioapi_0.14     Matrix_1.5-4.1      generics_0.1.3      vctrs_0.6.3         tools_4.1.2         glue_1.6.2          munsell_0.5.0      
[22] compiler_4.1.2      pkgconfig_2.0.3     colorspace_2.1-0    BiocManager_1.30.21 tidyselect_1.2.0    tibble_3.2.1        patchwork_1.1.2   

Any help will be grateful!

**Comment by karlie002** [comment]
I have solved the issue when upgrading the version of package "RcppAnnoy" from 0.0.20 to 0.0.21 .
The bug is so strange ,hope for helping other people come over the same problem.

**Comment by maoyongbioinfo** [comment]
> 

Yes, I have corrected the same errors and install Seurat successful by re-install the RcppAnnoy, thank you very much !!!
