### ISSUE TITLE
How to convert ensemble_id-gene name to gene name in a given seurat object?

### ISSUE THREAD

**Issue by yojetsharma** [satijalab/seurat#7572]
I have a seurat object which has "ENSG000000003.15-TSPAN6" (for example) and I would like to get rid of the everything before the gene name. How can I do this?
Thank you

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  First, just as note I would be very careful renaming features in existing object due to needing to make sure everything is properly renamed, much easier to do before creating object.  If you have already created object it's fairly straightforward to extract matrix, rename features, re-create object and then add any reductions, graphs, etc back to new object.

All of that said there is simple way to do this via stringr package.
```
library(stringr)

gene_list <- GENES

# extract everything after first "-" in gene name (preserve any "-" or other punctuation present in in name of gene itself)
new_names <- str_extract(string = gene_list, pattern = "(?<=-).+$")
```

Best,
Sam

**Comment by yojetsharma** [comment]
Thanks for this. But I am a beginner in this, so cannot figure out the missing lines of codes that I need to write before extracting the gene names.

**Comment by yojetsharma** [comment]
Here is what I did:
```
#First I extracted the counts from the seurat object
counts <- obj@assays$RNA@counts
metadata <- obj@meta.data
#then from counts, I extracted the gene list as follows
gene_list <- counts@Dimnames[[1]]
new_names <- str_extract(string = gene_list, pattern = "(?<=-).+$")
head(new_names)
[1] "TSPAN6"   "TNMD"     "DPM1"     "SCYL3"    "C1orf112" "FGR" 

```
So this worked!
But how do I put this new_names back to the obj@Dimnames[[1]]?

**Comment by samuel-marsh** [comment]
So again because of all the aspects in Seurat object I would advise renaming the genes before creating the object.

From your already created object the step by step breakdown would be:
```
# Pull matrix
OBJ_mat <- OBJ[["RNA"]]@counts

# get current rownames
genes_old <- rownames(OBJ_mat)

# remove ENS ID portion
genes_new <- str_extract(string = gene_list, pattern = "(?<=-).+$")

# replace old row names with new ones
rownames(OBJ) <- genes_new

OBJ_new <- CreateSeuratObject(counts = OBJ_mat, min.cells = 0, min.features = 0)
```

Hope that clears it up.

Best,
Sam

**Comment by saketkc** [comment]
Hi @yojetsharma, We recommend creating a new matrix with gene names. You can use a helper function from `Azimuth`, as shown in [this vignette](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html)
