### ISSUE TITLE
Which assay and slot does IntegrateData uses

### ISSUE THREAD

**Issue by Rohit-Satyam** [satijalab/seurat#7575]
I have a small query now that I am running Integration after running `RunALRA` function. Does IntegrateData uses "RNA" assay and it's `data` slot while running `IntegrateData` function or does it use default assay's data slot (which `RunALRA` sets to "alra")? Since I couldn't find any tutorial on how can one use both ALRA and Seurat together for integrating imputed data as we discuss in issues [here](https://github.com/KlugerLab/ALRA/issues/22) and [here](https://github.com/KlugerLab/ALRA/issues/25), I was tempted to ask here. I am planning to use "logNormalization". And I have 4 samples where `DefaultAssay` is "alra" (because I carried out imputation) and 1 reference atlas MCA which has `DefaultAssay` as "RNA".

**Comment by Rohit-Satyam** [comment]
@troels @pmarks @mxposed @zeehio Please help.

**Comment by Gesmira** [comment]
Hi, 
In `FindIntegrationAnchors`, you can set the assay that will be used per object. If you don't specify the assay, it will take the DefaultAssay per object.
