### ISSUE TITLE
ProjectData return reduction include tsne

### ISSUE THREAD

**Issue by Liripo** [satijalab/seurat#7576]
```R
obj <- ProjectData(
  object = obj,
  assay = "RNA",
  full.reduction = c("pca.full"),
  sketched.assay = "sketch",
  sketched.reduction = c("pca"),
  umap.model = "umap",
  dims = 1:50,
  refdata = list(cluster_full = "seurat_clusters")
)
```
Is there a way for me to get both full.umap and full.tsne results？Doesn't seem to be seen in the tutorial.

**Comment by yuhanH** [comment]
hi @Liripo 
tsne package doesn't have this supervised format visualization in uwot, https://jlmelville.github.io/uwot/metric-learning.html, so currently you cannot get `full.tsne`.
