### ISSUE TITLE
Would like to remove borders of all label boxes in DimPlot()

### ISSUE THREAD

**Issue by zandigohar** [satijalab/seurat#7578]
Dear Seurat Developers,

I would like to remove the black borders of label boxes in `DimPlot(label.box=TRUE, ...)` in my UMAP visualization. It appears I need to set ` label.size = NA` in the `geom_label()` or `geom_label_repel()` to do so. 

Moreover, I think I either have to do it in the Visualization.R script of the Seurat package or do `DimPlot(...) + geom_label_repel(...)` in my own script. For the latter, I need x, y, and label information but then I am not sure how to extract those, and seems to be inefficient to do it for all my visualization. 

Would you please help me find the best approach to remove the borders?

Thank you!

**Comment by longmanz** [comment]
Hi, 
The color of the label box boundary always matches the color of the label itself, which can be modified by `DimPlot(..., label.color = 'white')`. If you do not want the black color, you can set it to white or any other color you want for your desire.

**Comment by zandigohar** [comment]
But I do not think the border color matches the box color. It seems the default is black.

Here is a reproducible example:
```
pbmc3k.final <- SeuratData::LoadData("pbmc3k", type = "pbmc3k.final")
pbmc3k.final <- UpdateSeuratObject(object = pbmc3k.final)
DimPlot(pbmc3k.final, reduction='umap', label=TRUE, label.box=TRUE)
```
<img width="437" alt="image" src="https://github.com/satijalab/seurat/assets/36520735/77372a8a-8275-4b70-b1b7-d38600b1dd99">

If you zoom you see the box borders are black:
<img width="131" alt="image" src="https://github.com/satijalab/seurat/assets/36520735/6496a4ea-7e50-4fc3-ad0b-71486fd280ea">

Changing the border color to white by  `DimPlot(..., label.color = 'white')`, would change all to white. 

I want each border to be colored as the box color. (e.g. if the box is blue, the border of the box to be blue as well)
