### ISSUE TITLE
Order of data normalization for layer integration

### ISSUE THREAD

**Issue by jonhsussman** [satijalab/seurat#7585]
I have a question about data CLR normalization, I see in the two relevant integration Seurat v5 vignettes NormalizeData is performed at different times. In the seurat5_integration vignette, the data is split into the layers and then NormalizeData is performed (presumably normalizing each layer independently). In the parsebio_sketch_integration vignette, NormalizeData is performed directly after creating the seurat object, presumably normalizing all the data as a single unit, and then separating it into the individual layers before performing the sketch and integration. 

While presumably this wouldn't make a difference for LogNormalization as this is done on individual cells in isolation, when normalizing across cells as shown in the Seurat CODEX vignette, it seems like this would make a difference. Do you have thoughts on which approach is better suited? It's not entirely apparent to me if there is a difference here at all, or if so if this different is meaningful. 

Thanks, 
Jonathan

**Comment by longmanz** [comment]
Hi, 
As you mentioned, the default normalization method is "LogNormalize" so it has no impact whether you perform it in a subset/layers or after merging them. 
However, when you need to use the CLR normalization (e.g., for the CODEX data or any CITE-seq data), you should do it before splitting, as CLR requires a geometric mean to be calculated from all the cells (or all the genes, depending on the `margin =` you set during `NormalizeData()`). Subsetting the data will deviate the mean. There are several papers discussing the pros and cons of CLR normalization (https://www.nature.com/articles/s41467-022-29356-8), which might be helpful to you.

**Comment by ruohuchengxhe** [comment]
> Hi, As you mentioned, the default normalization method is "LogNormalize" so it has no impact whether you perform it in a subset/layers or after merging them. However, when you need to use the CLR normalization (e.g., for the CODEX data or any CITE-seq data), you should do it before splitting, as CLR requires a geometric mean to be calculated from all the cells (or all the genes, depending on the `margin =` you set during `NormalizeData()`). Subsetting the data will deviate the mean. There are several papers discussing the pros and cons of CLR normalization (https://www.nature.com/articles/s41467-022-29356-8), which might be helpful to you.

Hi, I'm curious about what jonhsussman said, could you let me know if calculations such as NormalizeData is perfomed on each layer individually when the seurat object is splitted? Thank you!
