### ISSUE TITLE
Problems with large datasets for SCTransform. 

### ISSUE THREAD

**Issue by Junedays** [satijalab/seurat#7587]
I noticed a problem about large datasets for SCTransform. 
When the datasets are too large, it might come to an error. I have provided a reproducible example as follow:

#packages prep
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(Azimuth)
library(ggplot2)
library(patchwork)
options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")
InstallData("pbmcsca")

#simulate a large dataset with 200,000 cells
obj <- LoadData("pbmcsca")
obj <- Seurat::UpdateSeuratObject(obj)
obj <- subset(obj, subset=nFeature_RNA > 1000)

obj.list=list()
for (i in 1:23){
  obj.list[i]=obj
}

obj2 <- merge(x=obj.list[[1]],
             y=obj.list[-1])

#check the number of cells
nrow(obj2@meta.data)

#updated the layers
obj2[["RNA"]] <- JoinLayers(obj2[["RNA"]])
obj2[["RNA"]] <- split(obj2[["RNA"]], f = obj2$Method)
Layers(obj2[["RNA"]])

# Have error
obj2 <- SCTransform(obj2, vst.flavor = "v2")

#The error is as follow:
Error in DelayedArray::colAutoGrid(x = counts, ncol = ncol(counts)) : 
  'ncol' is too big. Blocks of length > .Machine$integer.max are not supported yet. Please specify a smaller 'ncol'.

============
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.0 (2023-04-21)
 os       Ubuntu 22.04.2 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       Asia/Shanghai
 date     2023-07-20
 rstudio  2023.06.0+421 Mountain Hydrangea (server)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version    date (UTC) lib source
 abind                  1.4-5      2016-07-21 [3] RSPM (R 4.3.0)
 Azimuth              * 0.4.6      2023-07-14 [1] Github (satijalab/azimuth@fa45d4c)
 Biobase                2.60.0     2023-04-25 [1] Bioconductor
 BiocGenerics           0.46.0     2023-04-25 [3] Bioconductor
 BiocManager            1.30.21    2023-06-10 [3] RSPM (R 4.3.0)
 bit                    4.0.5      2022-11-15 [3] RSPM (R 4.3.0)
 bit64                  4.0.5      2020-08-30 [3] RSPM (R 4.3.0)
 bitops                 1.0-7      2021-04-24 [3] RSPM (R 4.3.0)
 cellranger             1.1.0      2016-07-27 [3] RSPM (R 4.3.0)
 cli                    3.6.1      2023-03-23 [3] RSPM (R 4.3.0)
 cluster                2.1.4      2022-08-22 [2] CRAN (R 4.3.0)
 codetools              0.2-19     2023-02-01 [2] CRAN (R 4.3.0)
 colorspace             2.1-0      2023-01-23 [3] RSPM (R 4.3.0)
 cowplot                1.1.1      2020-12-30 [3] RSPM (R 4.3.0)
 crayon                 1.5.2      2022-09-29 [3] RSPM (R 4.3.0)
 data.table             1.14.8     2023-02-17 [3] RSPM (R 4.3.0)
 DelayedArray           0.26.6     2023-07-02 [3] Bioconductor
 DelayedMatrixStats     1.22.1     2023-06-09 [3] Bioconductor
 deldir                 1.0-9      2023-05-17 [3] RSPM (R 4.3.0)
 digest                 0.6.33     2023-07-07 [3] RSPM (R 4.3.0)
 dotCall64              1.0-2      2022-10-03 [3] RSPM (R 4.3.0)
 dplyr                  1.1.2      2023-04-20 [3] RSPM (R 4.3.0)
 DT                     0.28.1     2023-06-22 [1] Github (rstudio/DT@6a82b6d)
 ellipsis               0.3.2      2021-04-29 [3] RSPM (R 4.3.0)
 fansi                  1.0.4      2023-01-22 [3] RSPM (R 4.3.0)
 fastDummies            1.7.3      2023-07-06 [3] RSPM (R 4.3.0)
 fastmap                1.1.1      2023-02-24 [3] RSPM (R 4.3.0)
 fitdistrplus           1.1-11     2023-04-25 [3] RSPM (R 4.3.0)
 fs                     1.6.2      2023-04-25 [3] RSPM (R 4.3.0)
 future                 1.33.0     2023-07-01 [3] RSPM (R 4.3.0)
 future.apply           1.11.0     2023-05-21 [3] RSPM (R 4.3.0)
 gargle                 1.5.1      2023-06-19 [3] RSPM (R 4.3.0)
 generics               0.1.3      2022-07-05 [3] RSPM (R 4.3.0)
 GenomeInfoDb           1.36.1     2023-06-21 [3] Bioconductor
 GenomeInfoDbData       1.2.10     2023-06-19 [3] Bioconductor
 GenomicRanges          1.52.0     2023-04-25 [3] Bioconductor
 ggplot2              * 3.4.2      2023-04-03 [3] RSPM (R 4.3.0)
 ggrepel                0.9.3      2023-02-03 [3] RSPM (R 4.3.0)
 ggridges               0.5.4      2022-09-26 [3] RSPM (R 4.3.0)
 glmGamPoi              1.12.2     2023-07-02 [3] Bioconductor
 globals                0.16.2     2022-11-21 [3] RSPM (R 4.3.0)
 glue                   1.6.2      2022-02-24 [3] RSPM (R 4.3.0)
 goftest                1.2-3      2021-10-07 [3] RSPM (R 4.3.0)
 googledrive            2.1.1      2023-06-11 [3] RSPM (R 4.3.0)
 googlesheets4          1.1.1      2023-06-11 [3] RSPM (R 4.3.0)
 gridExtra              2.3        2017-09-09 [3] RSPM (R 4.3.0)
 gtable                 0.3.3      2023-03-21 [3] RSPM (R 4.3.0)
 hdf5r                  1.3.8      2023-01-21 [3] RSPM (R 4.3.0)
 htmltools              0.5.5      2023-03-23 [3] RSPM (R 4.3.0)
 htmlwidgets            1.6.2      2023-03-17 [1] RSPM (R 4.3.0)
 httpuv                 1.6.11     2023-05-11 [3] RSPM (R 4.3.0)
 httr                   1.4.6      2023-05-08 [3] RSPM (R 4.3.0)
 ica                    1.0-3      2022-07-08 [3] RSPM (R 4.3.0)
 igraph                 1.5.0      2023-06-16 [3] RSPM (R 4.3.0)
 IRanges                2.34.1     2023-06-22 [3] Bioconductor
 irlba                  2.3.5.1    2022-10-03 [3] RSPM (R 4.3.0)
 jsonlite               1.8.7      2023-06-29 [3] RSPM (R 4.3.0)
 KernSmooth             2.23-22    2023-07-10 [2] RSPM (R 4.3.0)
 later                  1.3.1      2023-05-02 [3] RSPM (R 4.3.0)
 lattice                0.21-8     2023-04-05 [2] CRAN (R 4.3.0)
 lazyeval               0.2.2      2019-03-15 [3] RSPM (R 4.3.0)
 leiden                 0.4.3      2022-09-10 [3] RSPM (R 4.3.0)
 lifecycle              1.0.3      2022-10-07 [3] RSPM (R 4.3.0)
 listenv                0.9.0      2022-12-16 [3] RSPM (R 4.3.0)
 lmtest                 0.9-40     2022-03-21 [3] RSPM (R 4.3.0)
 magrittr               2.0.3      2022-03-30 [3] RSPM (R 4.3.0)
 MASS                   7.3-60     2023-05-04 [2] RSPM (R 4.3.0)
 Matrix                 1.6-0      2023-07-08 [2] RSPM (R 4.3.0)
 MatrixGenerics         1.12.2     2023-06-09 [3] Bioconductor
 matrixStats            1.0.0      2023-06-02 [3] RSPM (R 4.3.0)
 mime                   0.12       2021-09-28 [3] RSPM (R 4.3.0)
 miniUI                 0.1.1.1    2018-05-18 [3] RSPM (R 4.3.0)
 munsell                0.5.0      2018-06-12 [3] RSPM (R 4.3.0)
 nlme                   3.1-162    2023-01-31 [2] CRAN (R 4.3.0)
 parallelly             1.36.0     2023-05-26 [3] RSPM (R 4.3.0)
 patchwork            * 1.1.2      2022-08-19 [3] RSPM (R 4.3.0)
 pbapply                1.7-2      2023-06-27 [3] RSPM (R 4.3.0)
 pbmcsca.SeuratData   * 3.0.0      2023-07-18 [1] local
 pillar                 1.9.0      2023-03-22 [3] RSPM (R 4.3.0)
 pkgconfig              2.0.3      2019-09-22 [3] RSPM (R 4.3.0)
 plotly                 4.10.2     2023-06-03 [3] RSPM (R 4.3.0)
 plyr                   1.8.8      2022-11-11 [3] RSPM (R 4.3.0)
 png                    0.1-8      2022-11-29 [3] RSPM (R 4.3.0)
 polyclip               1.10-4     2022-10-20 [3] RSPM (R 4.3.0)
 presto                 1.0.0      2023-07-14 [1] Github (immunogenomics/presto@31dc97f)
 progressr              0.13.0     2023-01-10 [3] RSPM (R 4.3.0)
 promises               1.2.0.1    2021-02-11 [3] RSPM (R 4.3.0)
 purrr                  1.0.1      2023-01-10 [3] RSPM (R 4.3.0)
 R.methodsS3            1.8.2      2022-06-13 [3] RSPM (R 4.3.0)
 R.oo                   1.25.0     2022-06-12 [3] RSPM (R 4.3.0)
 R.utils                2.12.2     2022-11-11 [3] RSPM (R 4.3.0)
 R6                     2.5.1      2021-08-19 [3] RSPM (R 4.3.0)
 RANN                   2.6.1      2019-01-08 [3] RSPM (R 4.3.0)
 rappdirs               0.3.3      2021-01-31 [3] RSPM (R 4.3.0)
 RColorBrewer           1.1-3      2022-04-03 [3] RSPM (R 4.3.0)
 Rcpp                   1.0.11     2023-07-06 [3] RSPM (R 4.3.0)
 RcppAnnoy              0.0.21     2023-07-02 [3] RSPM (R 4.3.0)
 RcppHNSW               0.4.1      2022-07-18 [3] RSPM (R 4.3.0)
 RCurl                  1.98-1.12  2023-03-27 [3] RSPM (R 4.3.0)
 remotes                2.4.2      2021-11-30 [3] RSPM (R 4.3.0)
 reshape2               1.4.4      2020-04-09 [3] RSPM (R 4.3.0)
 reticulate             1.30       2023-06-09 [3] RSPM (R 4.3.0)
 rlang                  1.1.1      2023-04-28 [3] RSPM (R 4.3.0)
 ROCR                   1.0-11     2020-05-02 [3] RSPM (R 4.3.0)
 RSpectra               0.16-1     2022-04-24 [3] RSPM (R 4.3.0)
 rstudioapi             0.15.0     2023-07-07 [3] RSPM (R 4.3.0)
 rsvd                   1.0.5      2021-04-16 [3] RSPM (R 4.3.0)
 Rtsne                  0.16       2022-04-17 [3] RSPM (R 4.3.0)
 S4Arrays               1.0.4      2023-05-14 [3] Bioconductor
 S4Vectors              0.38.1     2023-05-02 [3] Bioconductor
 scales                 1.2.1      2022-08-20 [3] RSPM (R 4.3.0)
 scattermore            1.2        2023-06-12 [3] RSPM (R 4.3.0)
 sctransform            0.3.5      2022-09-21 [3] RSPM (R 4.3.0)
 sessioninfo            1.2.2      2021-12-06 [3] RSPM (R 4.3.0)
 Seurat               * 4.9.9.9049 2023-06-19 [3] Github (satijalab/seurat@3a826c5)
 SeuratData           * 0.2.2      2023-07-14 [1] Github (satijalab/seurat-data@d6a8ce6)
 SeuratDisk             0.0.0.9020 2023-07-14 [1] Github (mojaveazure/seurat-disk@9b89970)
 SeuratObject         * 4.9.9.9086 2023-07-14 [1] Github (mojaveazure/seurat-object@4be3e8d)
 SeuratWrappers       * 0.3.1      2023-06-21 [3] Github (satijalab/seurat-wrappers@d28512f)
 shiny                  1.7.4.1    2023-07-06 [3] RSPM (R 4.3.0)
 shinyBS              * 0.61.1     2022-04-17 [3] RSPM (R 4.3.0)
 shinydashboard         0.7.2      2021-09-30 [3] RSPM (R 4.3.0)
 shinyjs                2.1.0      2021-12-23 [3] RSPM (R 4.3.0)
 SingleCellExperiment   1.22.0     2023-04-25 [3] Bioconductor
 sp                   * 2.0-0      2023-06-22 [3] RSPM (R 4.3.0)
 spam                   2.9-1      2022-08-07 [3] RSPM (R 4.3.0)
 sparseMatrixStats      1.12.2     2023-07-02 [1] Bioconductor
 spatstat.data          3.0-1      2023-03-12 [3] RSPM (R 4.3.0)
 spatstat.explore       3.2-1      2023-05-13 [3] RSPM (R 4.3.0)
 spatstat.geom          3.2-2      2023-07-06 [3] RSPM (R 4.3.0)
 spatstat.random        3.1-5.001  2023-06-22 [1] https://spatstat.r-universe.dev (R 4.3.0)
 spatstat.sparse        3.0-2      2023-06-25 [3] RSPM (R 4.3.0)
 spatstat.utils         3.0-3      2023-05-09 [3] RSPM (R 4.3.0)
 stringi                1.7.12     2023-01-11 [3] RSPM (R 4.3.0)
 stringr                1.5.0      2022-12-02 [3] RSPM (R 4.3.0)
 SummarizedExperiment   1.30.2     2023-06-06 [3] Bioconductor
 survival               3.5-5      2023-03-12 [2] CRAN (R 4.3.0)
 tensor                 1.5        2012-05-05 [3] RSPM (R 4.3.0)
 tibble                 3.2.1      2023-03-20 [3] RSPM (R 4.3.0)
 tidyr                  1.3.0      2023-01-24 [3] RSPM (R 4.3.0)
 tidyselect             1.2.0      2022-10-10 [3] RSPM (R 4.3.0)
 utf8                   1.2.3      2023-01-31 [3] RSPM (R 4.3.0)
 uwot                   0.1.16     2023-06-29 [3] RSPM (R 4.3.0)
 vctrs                  0.6.3      2023-06-14 [3] RSPM (R 4.3.0)
 viridisLite            0.4.2      2023-05-02 [3] RSPM (R 4.3.0)
 withr                  2.5.0      2022-03-03 [3] RSPM (R 4.3.0)
 xtable                 1.8-4      2019-04-21 [3] RSPM (R 4.3.0)
 XVector                0.40.0     2023-04-25 [3] Bioconductor
 zlibbioc               1.46.0     2023-04-25 [3] Bioconductor
 zoo                    1.8-12     2023-04-13 [3] RSPM (R 4.3.0)

**Comment by saketkc** [comment]
Thanks, we will release a fix soon.

**Comment by chainorato** [comment]
Hi, I'm facing the same problem.
May I ask whether this issue is already fixed?

**Comment by sabrina0701** [comment]
I have the same problem. It works well with the same dataset with Seurat v4, does it the specific problem in V5? And how to fix this? Thanks!

**Comment by saketkc** [comment]
Hi @sabrina0701, we will have a fix for this very soon. Thanks for your patience.

**Comment by kenneditodd** [comment]
@saketkc I have a similar problem. 

I am trying to merge my list of seurat objects after running SCTransform. 
```
 obj <- SplitObject(obj, split.by = "splitCol")
  obj <- lapply(obj, SCTransform)
  var.features <- SelectIntegrationFeatures(obj)
  obj.merged <- Merge_Seurat_List(obj)
```
I get the following error message.
```
Error in DelayedArray::colAutoGrid(x = counts, ncol = length(x = layer.cells)) : 
  'ncol' must be >= 1 and <= ncol(x)
```

**Comment by saketkc** [comment]
Hi @kenneditodd I would recommend updating to the lateset `seurat5` branch while we wait for CRAN to approve.

```
remotes::install_githu("satijalab/seurat", "seurat5", quiet = TRUE)
```

We got rid of the DelayedArray infrastructure entirely for SCTransform
