### ISSUE TITLE
A questio about LoadVizgen

### ISSUE THREAD

**Issue by zhaomou233123** [satijalab/seurat#7588]
hi,
I analyzed s2r1 dataset was produced using the Vizgen MERSCOPE system, but got error
Warning in ReadVizgen(data.dir = data.dir, filter = "^Blank-", type = c("centroids",  :
  Cannot find hdf5r; unable to load segmentation vertices
Error in UseMethod(generic = "CreateSegmentation", object = coords) : 
  no applicable method for 'CreateSegmentation' applied to an object of class "NULL"
![屏幕截图 2023-07-20 095014](https://github.com/satijalab/seurat/assets/116482542/2ca98cc1-b4b0-4f4d-a1f4-0c81674e0caa)

**Comment by zhaomou233123** [comment]
I can't find the right way to slove it

**Comment by alikhuseynov** [comment]
what kind of output do you have from Vizgen? 

If it's a new output that has `.parquet` files for cell segmentations, then your `data.dir` should contain these files:
```
detected_transcripts.csv
cell_by_gene.csv
cell_metadata.csv
cell_boundaries.parquet
```
take a look at this PR #7190 and this posts #7080 #7215

**Comment by alikhuseynov** [comment]
> By default the function looks for segmentation, so if you do not have any it'll give you that error.
> 
> Based on not the screenshot you don't have segmentation data for Seurat to access, so you should pass in the argument `type = 'centroids` to `LoadVizgen`. This way it'll take the centroid information from the metadata and not look for segmentation data. I haven't tested this but believe it should work.

I can confirm that, if segmentation data is not provided, and even if the `type = c("segmentations", "centroids")` it would still make FOV with `"centroids"` and `"molecules"` with current PR #7190

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
