### ISSUE TITLE
Significant differences in avg_logFC between Seurat versions 3.12 and 4.3.01 in FindMarkers function

### ISSUE THREAD

**Issue by YingkaiSun** [satijalab/seurat#7589]
**Description:**
I am using Seurat version 4.3.01, and I found that the FoldChanger of differential genes run out by the FinderMarkers() function in version 3.12 is very different (the parameters used are the same). The results are as follows:

```r
# Differential gene comparison
WTvsPBS <- FindMarkers(object = sobj,ident.1 ='BtWT', ident.2 = 'PBS',test.use = 'MAST', min.pct = 0,
                       logfc.threshold = 0)

# version 4.3.01 result
# In order to compare with the old version, I calculated avg_logFC based on Log2_FC 

> WTvsPBS %>% mutate(FC=2^avg_log2FC,avg_logFC=log(FC,base = exp(1))) %>% head

     p_val avg_log2FC pct.1 pct.2     p_val_adj        FC  avg_logFC
Cbr3    2.073494e-270 -0.9139621 0.092 0.585 6.694277e-266 0.5307256 -0.6335102
Cfd     3.359224e-252 -0.6842468 0.001 0.404 1.084525e-247 0.6223306 -0.4742838
Neat1   3.978474e-245  0.5553315 0.985 0.855 1.284450e-240 1.4695063  0.3849265
Mxd1    2.451112e-240  0.7711352 0.934 0.581 7.913414e-236 1.7066121  0.5345102
Gsta1   3.020424e-224 -0.8282159 0.052 0.480 9.751440e-220 0.5632253 -0.5740755
Cyp2d12 7.420280e-212  0.9173625 0.711 0.239 2.395637e-207 1.8886594  0.6358673

# version 3.12 result

> head(WTvsPBs)
		p_val		avg_logFC	pct.1		pct.2		p_val_adj	
Cbr3 	1.008708e-270	 -1.445641	 0.092 	0.585 	3.256614e-266
Cfd 	3.357946e-252 	-2.833607 	0.001	 0.404 	1.084113e-247
Neat1 	3.040163e-245	 1.096695 	0.985 	0.855	 9.815165e-241
Mxd1	 1.909972e-240 	1.150563 	0.934 	0.581	6.166344e-236
Gsta1	2.040464e-224 	-1.514349	 0.052	 0.480	 6.587638e-220
Cyp2d12 5.520472e-212 	1.312877 	0.711 	0.239 	1.782284e-207


> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SeuratObject_4.1.3           Seurat_4.3.0.1               ieugwasr_0.1.5               readr_2.1.4                 
 [5] tibble_3.2.1                 purrr_1.0.1                  fs_1.6.2                     MendelianRandomization_0.8.0
 [9] TwoSampleMR_0.5.6            stringr_1.5.0                dplyr_1.1.2                  data.table_1.14.8

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The reason for this is because prior to v4 the log fold changes reported were natural log not log2.  V4 changed the default to log2 fold change.

https://github.com/satijalab/seurat/blob/master/NEWS.md#changes-11

Best,
Sam

**Comment by YingkaiSun** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. The reason for this is because prior to v4 the log fold changes reported were natural log not log2. V4 changed the default to log2 fold change.
> 
> https://github.com/satijalab/seurat/blob/master/NEWS.md#changes-11
> 
> Best, Sam



Hi Sam,

Thank you for your quick response and suggestion. I understand the change of Seurat v4 to use log2FC instead of lnFC, but in my case, I have already accounted for this change in my code by converting log2FC to lnFC. Even after performing this conversion, there is still a significant discrepancy between the results obtained in v3 and v4.

I really appreciate your assistance, and any additional suggestions or insights would be greatly appreciated.

Best regards,
Yingkai

**Comment by samuel-marsh** [comment]
Hi Yingkai,

Apologies I missed that in original post.

What happens if you explicitly set natural log in `FindMarkers` call by setting `base = exp(1)`

**Comment by YingkaiSun** [comment]
> Hi Yingkai,
> 
> Apologies I missed that in original post.
> 
> What happens if you explicitly set natural log in `FindMarkers` call by setting `base = exp(1)`


Hi Sam,

Thank you for your suggestion. I followed your advice and reran the `FindMarkers` function with `base = exp(1)` to explicitly set the log base as natural log in v4. Here is the command I used:

```r
WTvsPBS <- FindMarkers(object = sobj, ident.1 ='BtWT', ident.2 = 'PBS',test.use = 'MAST', min.pct = 0,
                       logfc.threshold = 0, base = exp(1))

head(WTvsPBS)

            p_val  avg_logFC pct.1 pct.2     p_val_adj
Cbr3    2.073494e-270 -0.6335102 0.092 0.585 6.694277e-266
Cfd     3.359224e-252 -0.4742838 0.001 0.404 1.084525e-247
Neat1   3.978474e-245  0.3849265 0.985 0.855 1.284450e-240
Mxd1    2.451112e-240  0.5345102 0.934 0.581 7.913414e-236
Gsta1   3.020424e-224 -0.5740755 0.052 0.480 9.751440e-220
Cyp2d12 7.420280e-212  0.6358673 0.711 0.239 2.395637e-207
```

It's concerning that these results are consistent with my previous manually converted lnFC results using Seurat v4. However, both of these are significantly different from the lnFC results from Seurat v3. I'm curious if there's any additional insight you might have on this.

Best,
Yingkai

**Comment by samuel-marsh** [comment]
Hi Yingkai,

Thanks for trying that, it's what I expected but just wanted to be 100% sure.

Couple other questions just to rule some things out.
What slot are you using with FindMarkers?  Are you using `NormalizeData` or `SCT` based pipeline?  The object that you are using for `FindMarkers` was it updated from V3 to V4 and just `FindMarkers` re-run or was it processed in V4 from raw data but using identical code?

I'm also wondering if perhaps there was a change in the pseudocount used between V3 and V4.3.0.1 but I don't remember.  @saketkc may have better idea here as he has been responsible for lot of code and updates to things functions.

Best,
Sam

**Comment by YingkaiSun** [comment]
> Hi Yingkai,
> 
> Thanks for trying that, it's what I expected but just wanted to be 100% sure.
> 
> Couple other questions just to rule some things out. What slot are you using with FindMarkers? Are you using `NormalizeData` or `SCT` based pipeline? The object that you are using for `FindMarkers` was it updated from V3 to V4 and just `FindMarkers` re-run or was it processed in V4 from raw data but using identical code?
> 
> I'm also wondering if perhaps there was a change in the pseudocount used between V3 and V4.3.0.1 but I don't remember. @saketkc may have better idea here as he has been responsible for lot of code and updates to things functions.
> 
> Best, Sam


Hi Sam,

Thank you for your reply.

To answer your questions, the Seurat object I am working with was actually generated on a different machine running Seurat v3. This object was sent to me (in the .rds format) by a colleague who had already performed the normalization and pre-processing steps in v3.

In terms of my own process, I am running Seurat v4 on my machine and our code, running against the same object, has identical parameter settings. However, the log fold change values are dramatically different between v3 and v4, even though the pct.1 and pct.2 results are completely consistent.

To add, my colleague also tested my code on his machine running v3 and was able to get results consistent with his initial ones (but still significantly different from the ones obtained on my machine running v4).

To clarify, we did not use the SCTransform normalization method in this pipeline.

Best,
Yingkai

**Comment by samuel-marsh** [comment]
Hi Yingkai,

So unfortunately at least on my end I cannot replicate this issue.  I would double check the object you have in both versions of Seurat to make sure data in the slots matches.  Did you run `UpdateSeuratObject` when loading into Seurat4?  If not try do that.  Otherwise not really sure but appears to be potentially object specific.

Best,
Sam

Here is code I used:

```
# Install Seurat 3.0.1
install.packages("~/Downloads/Seurat_3.0.1.tar.gz", type = "source", repos = NULL)

pbmc <- pbmc3k.SeuratData::pbmc3k.final

# "MAST"
markers <- FindMarkers(object = pbmc, ident.1 = "B", ident.2 = "NK", test.use = "MAST")
write.csv(markers, "~/Downloads/markers3MAST.csv")

# Default "wilcox"
markers <- FindMarkers(object = pbmc, ident.1 = "B", ident.2 = "NK")
write.csv(markers, "~/Downloads/markers3.csv")


# Seurat 4.3.0.1
library(Seurat)

pbmc <- pbmc3k.SeuratData::pbmc3k.final

markers <- FindMarkers(object = pbmc, ident.1 = "B", ident.2 = "NK", , base = exp(1), test.use = "MAST")
write.csv(markers, "~/Downloads/markers4MAST.csv")

markers <- FindMarkers(object = pbmc, ident.1 = "B", ident.2 = "NK", base = exp(1))
write.csv(markers, "~/Downloads/markers4.csv")



# check LFC values
> head(read.csv("~/Downloads/markers3MAST.csv"))
         X         p_val avg_logFC pct.1 pct.2     p_val_adj
1     CD74 1.685025e-217  2.546235 1.000 0.832 2.310843e-213
2  HLA-DRA 2.073349e-195  3.471469 1.000 0.323 2.843391e-191
3     NKG7 5.764270e-170 -4.340686 0.087 1.000 7.905120e-166
4     GNLY 2.010928e-122 -4.326040 0.078 0.961 2.757787e-118
5 HLA-DPB1 8.287359e-118  2.529997 0.985 0.316 1.136528e-113
6     GZMB 5.131418e-117 -3.817554 0.017 0.961 7.037226e-113
> head(read.csv("~/Downloads/markers4MAST.csv"))
         X         p_val avg_logFC pct.1 pct.2     p_val_adj
1     CD74 1.685025e-217  2.546235 1.000 0.832 2.310843e-213
2  HLA-DRA 2.073349e-195  3.471469 1.000 0.323 2.843391e-191
3     NKG7 5.764270e-170 -4.340686 0.087 1.000 7.905120e-166
4     GNLY 2.010928e-122 -4.326040 0.078 0.961 2.757787e-118
5 HLA-DPB1 8.287359e-118  2.529997 0.985 0.316 1.136528e-113
6     GZMB 5.131418e-117 -3.817554 0.017 0.961 7.037226e-113
>


> head(read.csv("~/Downloads/markers3.csv"))
     X        p_val avg_logFC pct.1 pct.2    p_val_adj
1 GZMB 3.186146e-97 -3.817554 0.017 0.961 4.369480e-93
2 NKG7 1.262672e-94 -4.340686 0.087 1.000 1.731628e-90
3 PRF1 1.835435e-93 -3.197358 0.029 0.948 2.517115e-89
4 GZMA 3.036581e-93 -3.096164 0.015 0.929 4.164367e-89
5 CTSW 3.151498e-93 -2.913836 0.070 0.987 4.321965e-89
6 CST7 9.767143e-92 -3.036006 0.038 0.948 1.339466e-87
> head(read.csv("~/Downloads/markers4.csv"))
     X        p_val avg_logFC pct.1 pct.2    p_val_adj
1 GZMB 3.186146e-97 -3.817554 0.017 0.961 4.369480e-93
2 NKG7 1.262672e-94 -4.340686 0.087 1.000 1.731628e-90
3 PRF1 1.835435e-93 -3.197358 0.029 0.948 2.517115e-89
4 GZMA 3.036581e-93 -3.096164 0.015 0.929 4.164367e-89
5 CTSW 3.151498e-93 -2.913836 0.070 0.987 4.321965e-89
6 CST7 9.767143e-92 -3.036006 0.038 0.948 1.339466e-87
> 

```

**Comment by ssy525** [comment]
Hi Yingkai,
Have you been able to solve that problem? I seem to be having the same one... 
Thank you.

**Comment by YingkaiSun** [comment]
> Hi Yingkai,
> 
> So unfortunately at least on my end I cannot replicate this issue. I would double check the object you have in both versions of Seurat to make sure data in the slots matches. Did you run `UpdateSeuratObject` when loading into Seurat4? If not try do that. Otherwise not really sure but appears to be potentially object specific.
> 
> Best, Sam
> 

Hi Sam,

Thank you for your suggestions. I have checked the object in both versions and tried using the UpdateSeuratObject function, but it didn't seem to make any difference to the results. My colleague and I are still looking into other possibilities but haven't found a solution yet.

Best,
Yingkai

**Comment by YingkaiSun** [comment]
> Hi Yingkai,
> Have you been able to solve that problem? I seem to be having the same one...
> Thank you.

Hi [@ssy525](https://github.com/ssy525),

I noticed you're encountering the same issue. I'm also still in the process of finding a solution, but I'll make sure to share any findings here to help you as well.

Best,
Yingkai

**Comment by ssy525** [comment]
Hi Yingkai, Sam,
Thank you very much for your reply.

I tried to compare the avg_logFC values in the `FindMarkers` output with those calculated manually from `my_dataset[["RNA"]]@data`. 
I noticed that the output of `FindMarkers` from my_dataset corresponded to 
log1p(mean(group1$expression))-log1p(mean(group2$expression)).
On the other hand, the output of `FindMarkers` from the pbmc dataset corresponded to
log1p(mean(expm1(group1$expression)))-log1p(mean(expm1(group2$expression))).

By checking with str(), the column `@ commands $ NormalizeData.RNA` was missing in my_dataset (I do not know why) and, by re-doing NormalizeData(), `FindMarkers` now gives proper avg_logFC values on my_dataset.

I am not sure if this is relevant to your case,, but I would be happy if it somehow helps...

**Comment by samuel-marsh** [comment]
Hi @ssy525 

Yes, that does help, I’d forgotten about that!  Thanks!

@YingkaiSun try running `NormalizeData` again.  In newer versions Seurat looks for what commands have been run before choosing the function to use during `FindMarkers`.  I would bet that @ssy525 is correct and that’s the source of your issue.

Best,
Sam

**Comment by ssy525** [comment]
Hi Sam,

could I ask you why (or on what condition) `@ commands $ NormalizeData.RNA` is erased from the object?  Thank you!

**Comment by samuel-marsh** [comment]
Hi @ssy525,

I don't know details of that and maybe Seurat team can chime in.  It could also be that normalize command was stored different in early V3 and that is either lost or not recognized but having never run into this issue personally I'm not sure.

Best,
Sam

**Comment by ssy525** [comment]
Hi Sam,
Thanks a lot, that may be why V3 could give proper results..

**Comment by YingkaiSun** [comment]
Hi Sam, Hi@ssy525 

I really appreciate your help. Following your suggestion, I re-ran the NormalizeData function and it seems to have resolved the issue. I can now get the expected results from FindMarkers function, which align with the results obtained on the V3 setup.

Thank you again for your patience and assistance in this matter. Your insights were crucial in solving this problem.
Best,
Yingkai

**Comment by samuel-marsh** [comment]
Hi Yingkai,

No problem, happy to help!  Glad we figured it out!

Best,
Sam
