### ISSUE TITLE
Spatial plot of subclusters

### ISSUE THREAD

**Issue by Pedramto89** [satijalab/seurat#7590]
Hi. I found some subclusters on one of my clusters and now I want to visualize each subcluster on the spatial image. How can I do that?

**Comment by AustinHartman** [comment]
Assuming you have an object with the subclusters stored in the Seurat object as metadata one of the following will work depending on which kind of spatial data you have:
```r
# Slide-based methods (Slide-seq or Visium)
SpatialDimPlot(object, group.by = "subcluster")

# Image-based methods (eg 10x Xenium, Vizgen MERSCOPE, Nanostring CosMx SMI)
ImageDimPlot(object, group.by = "subcluster")
```
