### ISSUE TITLE
IntegrateSketchEmbeddings in Seurat V5 not found

### ISSUE THREAD

**Issue by YOU-k** [satijalab/seurat#7592]
Hi there,
Thanks for providing the Seurat version 5 available. But when I am following https://satijalab.org/seurat/articles/atomic_integration.html. I could not find the function [IntegrateSketchEmbeddings](https://satijalab.org/seurat/reference/IntegrateSketchEmbeddings.html). could you please provide any paper or document for us to refer to? Cheers, Yue

**Comment by Gesmira** [comment]
Hi, 
The documentation you've linked is out of date with Seurat v5. Please follow the code [in this vignette]. Thanks! (https://satijalab.org/seurat/articles/parsebio_sketch_integration)
