### ISSUE TITLE
Edge case in MeanVarPlot when last bin only has one gene

### ISSUE THREAD

**Issue by Lakon** [satijalab/seurat#76]
The error I'm getting at the very end (96%) of Calculating gene dispersion in MeanVarPlot:                           
```Error in apply(data.iter, 1, fxn.x) : dim(X) must have a positive length```

My dataset has 26001 genes and in MeanVarPlot the bin size for the txtProgressBar is 1000. That leaves one gene for the last bin.

The issue is at Line 4521 at the moment.
```genes.iter=genes.use[my.inds]; data.iter=data[genes.iter,]```

Pretty sure you can just add the drop=FALSE argument to fix
```genes.iter=genes.use[my.inds]; data.iter=data[genes.iter,, drop=FALSE]```

**Comment by andrewwbutler** [comment]
Thanks for pointing this out. The suggested fix has been implemented in the latest commit.
