### ISSUE TITLE
Do cells that express Gene A tend to express Gene B?

### ISSUE THREAD

**Issue by ryandhindsa** [satijalab/seurat#760]
Hi, I am wondering the proper way to do co-expression analysis. I want to determine how often two genes are expressed together in a given cell. I ran across the co-expression plotting feature, but was wondering the proper way to quantify this. Is there an existing function in Seurat? Thanks!

**Comment by satijalab** [comment]
We don't have a function for this in Seurat. However you could try using correlation (or mutual information) between two genes to quantify this
