### ISSUE TITLE
subscript out of bounds in TransferData when integrating RNA and ATAC

### ISSUE THREAD

**Issue by jules-samaran** [satijalab/seurat#7601]
Hi,

This issue is a replicate of https://github.com/stuart-lab/signac/issues/1453 but @timoast recommended that I open an issue here. Aditionnallly issue #7597 seems to refer to the same problem but it was closed by the author without an explanation

I tried integrating scRNA-seq and scATAC-seq data as described in this [vignette](https://satijalab.org/seurat/articles/atacseq_integration_vignette.html) but when executing the line
`imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, weight.reduction = data.2[[mod2.red]], dims = 2:latent.dim, k.weight = 5)`
I get the following output: Finding integration vectors:

> Finding integration vector weights
> Errorr in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds
> Calls : TransferData -> FindWeights

The two data sets I'm integrating only have 200 cells each but still around 800 anchors are retained and I decreased k.weight thinking it was the root of the issue but it didn't change anything. Am I missing something? Thanks in advance for your help!

Output of sessionInfo()

> R version 4.2.2 (2022-10-31)
> Platform: aarch64-apple-darwin20 (64-bit)
> Running under: macOS Ventura 13.2.1
> 
> Matrix products: default
> BLAS: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages:
> [1] ggplot2_3.4.2 Signac_1.10.0 SeuratObject_4.1.3 Seurat_4.3.0
> 
> loaded via a namespace (and not attached):
> [1] Rtsne_0.16 colorspace_2.1-0 deldir_1.0-9
> [4] ellipsis_0.3.2 ggridges_0.5.4 XVector_0.38.0
> [7] GenomicRanges_1.50.2 spatstat.data_3.0-1 leiden_0.4.3
> [10] listenv_0.9.0 bit64_4.0.5 ggrepel_0.9.3
> [13] fansi_1.0.4 codetools_0.2-19 splines_4.2.2
> [16] RcppRoll_0.3.0 polyclip_1.10-4 jsonlite_1.8.5
> [19] Rsamtools_2.14.0 ica_1.0-3 cluster_2.1.4
> [22] png_0.1-8 uwot_0.1.14 shiny_1.7.4
> [25] sctransform_0.3.5 spatstat.sparse_3.0-1 compiler_4.2.2
> [28] httr_1.4.6 Matrix_1.5-4.1 fastmap_1.1.1
> [31] lazyeval_0.2.2 cli_3.6.1 later_1.3.1
> [34] htmltools_0.5.5 tools_4.2.2 igraph_1.4.3
> [37] gtable_0.3.3 glue_1.6.2 GenomeInfoDbData_1.2.9
> [40] RANN_2.6.1 reshape2_1.4.4 dplyr_1.1.2
> [43] MuDataSeurat_0.0.0.9000 fastmatch_1.1-3 Rcpp_1.0.10
> [46] scattermore_1.1 Biostrings_2.66.0 vctrs_0.6.2
> [49] spatstat.explore_3.2-1 nlme_3.1-162 progressr_0.13.0
> [52] lmtest_0.9-40 spatstat.random_3.1-5 stringr_1.5.0
> [55] globals_0.16.2 mime_0.12 miniUI_0.1.1.1
> [58] lifecycle_1.0.3 irlba_2.3.5.1 goftest_1.2-3
> [61] future_1.32.0 zlibbioc_1.44.0 MASS_7.3-60
> [64] zoo_1.8-12 scales_1.2.1 promises_1.2.0.1
> [67] spatstat.utils_3.0-3 parallel_4.2.2 RColorBrewer_1.1-3
> [70] reticulate_1.29 pbapply_1.7-0 gridExtra_2.3
> [73] stringi_1.7.12 S4Vectors_0.36.2 BiocGenerics_0.44.0
> [76] BiocParallel_1.32.6 GenomeInfoDb_1.34.9 rlang_1.1.1
> [79] pkgconfig_2.0.3 matrixStats_1.0.0 bitops_1.0-7
> [82] lattice_0.21-8 ROCR_1.0-11 purrr_1.0.1
> [85] tensor_1.5 patchwork_1.1.2 htmlwidgets_1.6.2
> [88] bit_4.0.5 cowplot_1.1.1 tidyselect_1.2.0
> [91] parallelly_1.36.0 RcppAnnoy_0.0.20 plyr_1.8.8
> [94] magrittr_2.0.3 R6_2.5.1 IRanges_2.32.0
> [97] generics_0.1.3 DBI_1.1.3 withr_2.5.0
> [100] pillar_1.9.0 fitdistrplus_1.1-11 survival_3.5-5
> [103] abind_1.4-5 RCurl_1.98-1.12 sp_1.6-1
> [106] tibble_3.2.1 future.apply_1.11.0 hdf5r_1.3.8
> [109] crayon_1.5.2 KernSmooth_2.23-21 utf8_1.2.3
> [112] spatstat.geom_3.2-1 plotly_4.10.2 grid_4.2.2
> [115] data.table_1.14.8 digest_0.6.31 xtable_1.8-4
> [118] tidyr_1.3.0 httpuv_1.6.11 stats4_4.2.2
> [121] munsell_0.5.0 viridisLite_0.4.2

Here's the code I run after preprocessing:

```
transfer.anchors <- FindTransferAnchors(reference = data.1, query = data.2,
                                        features = VariableFeatures(object = data.1),
                                        reference.assay = assay.1,
                                        query.assay = mod2.cross,
                                        reduction = "cca")
genes.use <- VariableFeatures(data.1)
refdata <- GetAssayData(data.1, assay = "RNA", slot = "data")[genes.use, ]
imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, weight.reduction = data.2[[mod2.red]],
    dims = 2:latent.dim, k.weight = 5)
```

**Comment by longmanz** [comment]
hi,
The issue arises when calling `Embeddings(reduction)[nn.cells2, dims]` in FindWeights(). Since you have tried reducing k.weight and it did not help, is it possible that you set the `latent.dim` too large? 
Also, it would be helpful if you could provide us a minimal dataset to reproduce this issue.

**Comment by jules-samaran** [comment]
Reducing latent.dim solved the issue (from 30 to 15), thank you!
