### ISSUE TITLE
Normalizing Query Object for Reference Mapping doesn't matter? 

### ISSUE THREAD

**Issue by me-orlov** [satijalab/seurat#7603]
Dear Seurat community,

I have several questions about FindTransferAnchors and multimodal reference mapping. I will reference issue #7564 , as I started this analysis there, but I have new questions now. 

1) In my analysis, I start with an integrated query object, ```Seurat.allIntegrated```, which was generated by integrating various control and treatment samples together to control for technical variation. I am only interested in mapping specific clusters, so I subset them out.
```
subSeurat <- subset(Seurat.allIntegrated, idents = clustersTOKeep)
Seurat.split <- SplitObject(subSeurat_int, split.by = "treatment")
controls <- Seurat.split[[1]] # This contains the three control samples.
treatment  <- Seurat.split[[2]] # Treatment 1
```
where controls has the following structure:

```
controls
An object of class Seurat 
64542 features across 747 samples within 3 assays 
Active assay: integrated (3000 features, 3000 variable features)
 2 other assays present: RNA, SCT
```
and ```controls$SCT``` has multiple SCT models (from before the original integration). 

I then attempt multimodal reference mapping using the vignette as a guide, with the pbmc reference:

```
control_anchors <- FindTransferAnchors(
  reference = reference,
  k.filter = NA,
  query = controls,
  query.assay = "integrated",
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50)
```

 However, regardless of whether I do ```query.assay = “RNA”``` or ```query.assay = “integrated”``` or ```query.assay = “SCT”```, I always get the same set of anchors and anchor scores. 
Furthermore, regardless of whether I use query object modified to contain only the raw RNA assay, only the SCT  assay, or only integrated assay in MapQuery:

```
    controls <- MapQuery(
    anchorset = control_anchors, 
    query = controls,
    reference = reference, 
    refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"),
    reference.reduction = "spca",
    reduction.model = "wnn.umap")
```
I get exactly the same cell predictions and cell prediction scores (not similar, but exactly identical). I don’t understand why? Why would using the “integrated” and “RNA” assays for the query here yield identical results? 

I have even explicitly merged the controls and re-run the SCT on the merged object before doing all of the above. I still get the same results. 

Why is any normalization done to the query entirely irrelevant? I would like to use the “integrated” SCT assay, corrected for technical variation, as the input for reference mapping, instead of just starting with the raw RNA counts. 
________________________________________________________________________________________________________________________________________

2) I have tested this with the vignette data. Although the vignette says to first normalize the query in the same manner as the reference, regardless of whether I do or not include this step:

```
pbmc3k <- SCTransform(pbmc3k, verbose = FALSE)
```
I still get exactly the same anchors, anchor scores and cell prediction scores. 
Why should we then be normalizing the query? 

Code for this step is below:
```
# Try to run FindTransferAnchors without normalizing the query first, since this seems to make no difference for MY data. 
anchors_RNA_Only <- FindTransferAnchors(
  reference = reference,
  query = pbmc3k,
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50
)

pbmc3k_RNAonly <- MapQuery(
  anchorset = anchors_RNA_Only,
  query = pbmc3k_RNAonly,
  reference = reference,
  refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca", 
  reduction.model = "wnn.umap"
)

# Normalize reference as in the vignette and run as normal:
pbmc3k <- SCTransform(pbmc3k, verbose = FALSE)

anchors <- FindTransferAnchors(
  reference = reference,
  query = pbmc3k,
  query.assay = "SCT",
  normalization.method = "SCT",
  reference.reduction = "spca",
  dims = 1:50
)

pbmc3k <- MapQuery(
  anchorset = anchors,
  query = pbmc3k,
  reference = reference,
  refdata = list(
    celltype.l1 = "celltype.l1",
    celltype.l2 = "celltype.l2",
    predicted_ADT = "ADT"
  ),
  reference.reduction = "spca", 
  reduction.model = "wnn.umap"
)

#Compare:
identical(anchors_RNA_Only@anchors, anchors@anchors)
identical(pbmc3k@meta.data$predicted.celltype.l1.score, pbmc3k_RNAonly@meta.data$predicted.celltype.l1.score) 

```
If this entire process only using the RNA query assay? Why would I get the same results?
________________________________________________________________________________________________________________________________________

3) I have tried to run my analysis with “CCA” reduction to see what would happen:

```
varfeat <- intersect(VariableFeatures(reference),VariableFeatures(controls$integrated)
anchors_control_CCA <- FindTransferAnchors(
  reference = reference,
  k.filter = NA,
  query = controls,
  query.assay = "integrated",
  reference.assay = "SCT",
  normalization.method = "SCT",
  reduction = "cca",
  dims = 1:50,
  features = varfeat
)

```
But I get the following error:

```
Error in RunCCA.Seurat(object1 = reference, object2 = query, features = features, : VariableFeatures not computed for the SCT assay in object1"
```

I am therefore at a loss of how to proceed with reference mapping a previously integrated query object. I would love it if someone could walk me through the relevant commands or point me in the right direction. I have read the Stuart paper on integration. If it matters, I am currently running Seurat version 4.3.0.

Thank you for your time and patience!

**Comment by Gesmira** [comment]
Hi, 
When mapping to an SCTransformed reference, we internally recompute the query Pearson residuals with `SCTransform` based on the reference's SCT model. If you want to use your original SCTransformed query data, you can set `recompute.residuals = FALSE`.

**Comment by me-orlov** [comment]
Hello Gesmira and thank for your answer a few months ago - it makes sense now! I have come back to this portion of my project and realized I still don't quite understand the impact of the recomputing residuals (or not) on the overall results of reference mapping or spatial integration analyses. I have a couple of follow-up questions: 

1) Just to double check: In cases where we want to use a query that has been integrated to first correct for batch effects is the only option then to set recompute.residuals = FALSE? If I do not, am I losing the batch effects corrections?

2) What are the potential negative implications of using recompute.residuals = FALSE? I saw in https://github.com/satijalab/seurat/issues/6662 that this might only be appropriate when the cell composition is similar between the query and reference? What do we do when the query might not contain all the cell types found in the reference? Is there any guidance on how to handle reference mapping when the query itself must first be integrated? 

Thank you in advance.
