### ISSUE TITLE
Issue following BPCells with Seurat V5 Vignette

### ISSUE THREAD

**Issue by ccnawrocki** [satijalab/seurat#7604]
Hello, 
When trying to follow this vignette: https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html, I could not create a Seurat object. Why am I getting this error?

```r
library(BPCells)
library(Seurat)
library(SeuratDisk)
library(SeuratObject)
library(Azimuth)

options(Seurat.object.assay.version = "v5")

brain.data <- open_matrix_10x_hdf5(
  path = "/Users/cnawrocki/Desktop/mouse_data.h5"
)
# Write the matrix to a directory
write_matrix_dir(
  mat = brain.data,
  dir = "/Users/cnawrocki/Desktop/mouse_counts"
)

# Now that we have the matrix on disk, we can load it
brain.mat <- open_matrix_dir(dir = "/Users/cnawrocki/Desktop/mouse_counts")
brain.mat <- Azimuth:::ConvertEnsembleToSymbol(mat = brain.mat, species = "mouse")

# Create Seurat Object
brain <- CreateSeuratObject(counts = brain.mat)
```

I get this error:
```
Error in UseMethod(generic = "as.sparse", object = x) : 
  no applicable method for 'as.sparse' applied to an object of class "c('MatrixDir', 'IterableMatrix')"
```

Also, the ConvertEmsembleToSymbol function is not working for me. I have tried to switch to Seurat V5, but it does not seem to be doing anything.

**Comment by yuhanH** [comment]
HI 
For `ConvertEnsembleToSymbol`,  you need to install seurat5 version of `Azimuth` as well. 
```
remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE)
```
Please confirm if SeuratObject is also installed in seurat5 branch. 
https://satijalab.org/seurat/articles/install.html
