### ISSUE TITLE
Seurat subset() function does not work

### ISSUE THREAD

**Issue by JoBeh** [satijalab/seurat#7609]
Dear all,

I have been trying to subset my Seurat object for days but I Keep encountering this error.

> mtd_subset <- subset(x = seuratObj, subset = `Td-tomato` > 0) 

Error in intI(i, n = d[1L], dn[[1L]], give.dn = FALSE) : 
  invalid character indexing

any ideas?

thanks in advance.

**Comment by Gesmira** [comment]
Actually, it seems that the metadata column name "Td-tomato" is causing the issue. Please either use `` to wrap the variable name or rename your variable.
