### ISSUE TITLE
re clustering

### ISSUE THREAD

**Issue by naixiangxiaozi** [satijalab/seurat#761]
after getting a subset, why do I not get new identities on that subset?

**Comment by andrewwbutler** [comment]
I'm not sure I understand the question here. You can take a subset of a Seurat object using `SubsetData`. This preserves the identities of the original object. To get "new identities", you would need to reanalyze the subset that you took.

**Comment by naixiangxiaozi** [comment]
Thank you, I have already solved this problem.


Regards,

Hua

________________________________
