### ISSUE TITLE
How to analyze Differential expression for multiple time  points through Seurat. 

### ISSUE THREAD

**Issue by hseebi** [satijalab/seurat#7611]
I have a dataset of two conditions (control and mutant) with multiple timepoints (young, adult and aged). How can i analyze Differential expression in all these timepoints through FindMarkers(object,  ident.1 = "", ident.2 = ""). I want to compare young, adult and age group among themselves with reference into control and mutant.  Is their an alternative way?

**Comment by Gesmira** [comment]
Hi, 
If I understand correctly, you would want to compare control young vs. mutant young, control adult vs. mutant adult, etc. In this case, you can make a new metadata column called "condition_timepoint" for example, and just `paste0(obj$condition, "_", obj$timepoint)` and then FindMarkers using these idents like, 
```
Idents(obj) <- "condition_timepoint"
FindMarkers(obj, ident.1 = "control_young", ident.2 = "mutant_young")
```
