### ISSUE TITLE
How can we interpret the prediction scores?

### ISSUE THREAD

**Issue by mea2712** [satijalab/seurat#7615]
Hello seurat
I wonder if you could elaborate a little on how to interpret the prediction scores we get from TransferData().
I know they go from 0 to 1 and I've read you suggest a score larger than 0.7 is a good score. 
However, where does the 0.7 come from? Is it a posterior probability? Or just a count?

Thanks!

**Comment by yuhanH** [comment]
You can find it in the [Azimuth FAQ](https://azimuth.hubmapconsortium.org/) Mapping QC session.
