### ISSUE TITLE
unable to read and incorporate the Sample information from molecule_info.h5 to seurat object.

### ISSUE THREAD

**Issue by Shamzar** [satijalab/seurat#7616]
Hello,
I quite new to Single cell analysis and I am running into the following problem. I had 12 different samples sequenced on Illumina, 6 of them are control and other 6 are treatment. I ran cellranger --count function on all 12 samples together and got outs folder with following files.

analysis
filtered_feature_bc_matrix
metrics_summary.csv
possorted_genome_bam.bam
raw_feature_bc_matrix
web_summary.html
cloupe.cloupe h5
molecule_info.h5
possorted_genome_bam.bam.bai
raw_feature_bc_matrix.h5

I used the raw_feature_bc_matrix.h5 file to generate seurat object however its missing the sample information. In order to put sample information in this seurat object I am trying to read molecule_info.h5 file and pull the sample information from it and put that into the Seurat [object@meta.data](mailto:object@meta.data).

Although, I am unable to read this molecule_info.h5 using Read10Xh5 command because it keeps giving me error.

metadata_dir <- "/home/Single_cell/yard/1013MJ1/outs/molecule_info.h5"
Mh5 <- Read10X_h5(metadata_dir)
Error in x$exists(name) : HDF5-API Errors:
error #000: H5L.c in H5Lexists(): line 845: unable to get link info
class: HDF5
major: Links
minor: Can't get value

error #001: H5L.c in H5L__exists(): line 2932: path doesn't exist
    class: HDF5
    major: Links
    minor: Object already exists

error #002: H5Gtraverse.c in H5G_traverse(): line 848: internal path traversal failed
    class: HDF5
    major: Symbol table
    minor: Object not found

error #003: H5Gtraverse.c in H5G__traverse_real(): line 579: can't look up component
    class: HDF5
    major: Symbol table
    minor: Object not found

error #004: H5Gobj.c in H5G__obj_lookup(): line 1135: can't locate object
    class: HDF5
    major: Symbol table
    minor: Object not found

error #005: H5Gstab.c in H5G__stab_lookup(): line 876: can't read message
    class: HDF5
    major: Symbol table
    minor: Unrecognized message

error #006: H
Can you help me get Sample information incorporated into my seurat object. Thankyou!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This isn't really a question for Seurat as in terms of reading the molecule_info.h5 is not possible with Seurat's `Read10X_h5` which is for reading the h5 barcode matrix files.  However, hopefully this info below can helpful.

First, If you want to read the molecule file you can use `read10xMolInfo` from the DropletUtils package.

Second, I would also note for proper cell calling and QC, Cell Ranger `count` should be run once for each sample and get one output per sample (in your case 12 total output folders).  That will allow cell calling to be done on sample specific basis which can be important as different samples may have different levels of droplet "cleanliness" and cell calling from empty droplets depends on that barcode rank UMI curve.  Then you can either **1)** read each of the files into R and either merge them into single matrix prior to creating object or merge objects after creating or **2)** run cell ranger `aggr` on the 12 outputs which will create a single output matrix for you if you don't want to merge in R and each samples barcodes will have specific suffix that when read into Seurat will assign unique orig.ident to each sample allowing for you to easily add more meta data.  If you use `aggr` method just make sure you set normalize parameter correctly depending on whether you want to downsample matrices or not.

Best,
Sam
