### ISSUE TITLE
FindMarkers() log2_fc scores very low

### ISSUE THREAD

**Issue by Leran10** [satijalab/seurat#7617]
Hi,

I have been using Seurat for several projects. I found that the avg_log2FC scores are always very low (mostly 0.1 - 1.2, sometimes 2). When I try to use the results in ReactomePA for pathway analysis, but pathway found. I wondered if there is any parameter that I missed?

<img width="589" alt="image" src="https://github.com/satijalab/seurat/assets/17597071/1ff1322d-b55e-460b-aac0-fea776905297">

Thanks!
Leran

**Comment by igrabski** [comment]
Hi Leran, the avg_log2FC scores indicate the log2 fold-change of average expression between the two groups. Hence, a score of 0 would indicate no difference in average expression, and a score of 1 would indicate that one group has double the average expression of the other. The values you are seeing here appear reasonable and are not unusually low; how meaningful these DEGs are will depend on your specific context.
