### ISSUE TITLE
integration using SCT2

### ISSUE THREAD

**Issue by yuuuuzhang** [satijalab/seurat#7620]
Hi, 
in this document, https://satijalab.org/seurat/articles/sctransform_v2_vignette.html, why you do not do SCT or ScaleData again on the integrated assay before running PCA?

**Comment by longmanz** [comment]
Hi, 
After the integration, we will be directly working on the "integrated" assay, which contains the data matrix that has already been "batch harmonized". So RunPCA() and other downstream commands can be directly applied without the need to do another SCTransform() or ScaleData().
