### ISSUE TITLE
FeatureScatter after SCTransform

### ISSUE THREAD

**Issue by Frank1213817** [satijalab/seurat#7621]
Hi Seurat team,

I am using Seurat v5 and SCTransform v2 for my scRNA-seq analysis.

I would like to plot a FeatureScatter plot to show if there is a co-expression pattern of two genes.

However, after SCTransform, the counts are normalized to the same levels, which shows strange patterns.
I am wondering if there is anything to do with this or if there is anything wrong with the usage of the function.

Might be a stupid question as I am still a rookie in scRNA-Seq analysis🤣

**Comment by longmanz** [comment]
Hi,
I am not sure what "strange patterns" you are referring to. But to perform a comparison between two genes, you can switch back to "RNA" assay and "data" slot `e.g., DefaultAssay(obj) = "RNA", FeatureScatter(obj, slot = "data")`. 
If you can show us your codes for SCTransform() and ScatterPlot(), and also an example of your plots, that would be nice. Thank you.

**Comment by Frank1213817** [comment]
Hi longmanz! glad to have your reply!

I am working on several seurat objects and I have performed SCTransform to each of them before intergation by IntegrateData.
The code I use for SCTransform and integration is :

`seurat_list <- lapply(X = seurat_list, FUN = function(x){
  x <- SCTransform(x, vst.flavor = 'v2', vars.to.regress = 'percent_mt')
})`
`integration_features <- SelectIntegrationFeatures(seurat_list, nfeatures = 3000)`
`seurat_list <- PrepSCTIntegration(seurat_list, anchor.features = integration_features)`

`#identify anchors and perform integration`
`all_combined_anchors <- FindIntegrationAnchors(object.list = seurat_list, anchor.features = integration_features, normalization.method = "SCT")`
`all_combined <- IntegrateData(anchorset = all_combined_anchors, normalization.method = "SCT")`

After integration I set assay to "RNA" and plot a featurescatter by:
`DefaultAssay(all_combined) <- "RNA"`
`FeatureScatter(all_combined, feature1 = "Rbfox3", feature2 = "Map2", slot = "data")`

The output plot is like:
![image](https://github.com/satijalab/seurat/assets/140804943/ef0da761-5cd3-483b-b66a-659dc417ccb3)

Wondering if you know what's going on and if there is anything to solve the problem. Thank you so much!

**Comment by longmanz** [comment]
Hi @Frank1213817 ,
Sorry for the late reply. The data in your "data" slot (RNA assay) are still counts. Did you forget to run NormalizeData(all_combined, )?
