### ISSUE TITLE
SCTransform functioning differently during integration?

### ISSUE THREAD

**Issue by timothevanmeter** [satijalab/seurat#7623]
Hello,

I am not sure why I obtained quite different results on the same data using SCTransform.

I have three datasets, dataset 9 having a sequencing depth substantially larger than the other two: the categories **RD1-9**, **RD10-9** in the graphic below.
![vlnplot_rd_wt combined2](https://github.com/satijalab/seurat/assets/32583238/47f4004e-3443-43d6-ba78-078acbbe86ce)

--------------------------------------------------------------

I have used SCTranform on two samples one from dataset 9 and one from dataset 8 to observe if this bias was corrected. This was done by loading in the two 10x samples (referred to as rd9 and rd8) and using sctransform with the following commands:
```
rd <- merge( x = rd9, y = rd8 )

## run sctransform
rd <- SCTransform(rd, verbose = FALSE)

plot <- VlnPlot(rd, features = c("nFeature_RNA", "nFeature_SCT"), pt.size = 0)
```
I obtained the following:
![vlnplot_rd10-8-9_sctransform_no-mitochondrial](https://github.com/satijalab/seurat/assets/32583238/335460a7-5573-4ba8-a6bb-4c5d9ee92b3a)

Which I was pleased to see tried to accomodate for the difference in sequencing depth.

--------------------------------------------------------------
--------------------------------------------------------------

However, when I tried to integrate these datasets with sctransform, as presented online [here](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform) ; the results did not look alike at all.
Here are the commands I used to integrate the datasets one pair at a time. Both elements of a pair are listed in **file.list**. The resulting combined dataset is then used as the first element of the next pair to process. I had to do this because integrating all datasets at the same time is not possible on my machine.
```
        file.list <- lapply( X = file.list, FUN = SCTransform )
        features <- SelectIntegrationFeatures( object.list = file.list, n = 3000 )
        file.list <- PrepSCTIntegration( object.list = file.list, anchor.features = features )
        tmp_anchors <- FindIntegrationAnchors( object.list = file.list, normalization.method = "SCT", anchor.features = features )
        file.combined <- IntegrateData( anchorset = tmp_anchors, normalization.method = "SCT" )
```
This is done within a for loop until all the datasets are combined into one. But the results differ greatly. The datasets integrated this way do not seem as well normalized for differences in sequencing depth between samples, see figure below:

![vlnplot_rd_sctransform](https://github.com/satijalab/seurat/assets/32583238/0eab2646-b16b-4b13-8ab5-2aa980a9d227)

--------------------------------------------------------------
--------------------------------------------------------------

### My question is: **What could be the reason for this?**

- Could it be that the **order** in which the datasets are integrated affects the way sctranform corrects the bias in sequencing depth?
- If so, should I present at first step the two most extremes samples as the first pair to be integrated?

--------------------------------------------------------------

**Thank you in advance for your consideration.**

**Comment by longmanz** [comment]
Hi,
Re 1). It is actually not about the order. You actually performed 2 different SCTransform(). As in your initial code, you first `merge()` the rd9 and rd8 into one seurat object, and then ran SCTransform(). SCTransform() was performed to them simultaneously. In your second step, SCTransform() was done separately to each of the dataset, and then integration was performed. In such way, SCTransform would NOT know there is a sequencing depth difference between datasets. So it will not be able to correct for them. 
Re 2). I am not sure what your final goal is. If you only want to correct for the sequencing depth difference (but you will need to make sure the difference only leads to a simple mean shift in the expression levels between different datasets), you will need to merge all your datasets into a Seurat object first, and then run `SCTransform(..., var.to.regress = "dataset_id")` (dataset_id should be the dataset identity). This will explicitly tell SCTransform() to correct for such mean expression difference. 
However, if your goal is just to perform integration, you can simply follow this (https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform).

**Comment by timothevanmeter** [comment]
Hello,

Thank you for your answer!

Does this mean that applying SCTransform on multiple datasets at the same time and integrating them as well is impossible?
My issue being that the sequencing depth bias does not go away during the integration procedure.
Do you think it would be possible to apply SCTransform to the integrated data **a posteriori** ?

Best regards,
