### ISSUE TITLE
mitochondrial genes exist in DEG using FindAllMarkers in single nuclei RNA-seq dataset

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#7624]
Hi Dear Seurat team,
I found mitochondrial genes exist in DEGs using FindAllMarkers in both Integrated and one or two subset celltype dataset, and they ranks top in DEGs. can I just remove mitochondrial genes after nFeature, nCount, mito_percent<5% filtering before integrating data? or can I remove mitochondrial genes after I subset cell type?
remove mito_gene before integrating code like this:
```
Obj[["percent_mt"]] <- PercentageFeatureSet(Obj, pattern = "^mt-")
    Obj <- subset(Obj, subset =
                    nFeature_RNA > Filter_nFeature_RNA[1] & nFeature_RNA < Filter_nFeature_RNA[2]
                  & nCount_RNA > Filter_nCount_RNA[1] & nCount_RNA < Filter_nCount_RNA[2]
                  & percent_mt < MitoPercent)
    Obj <- NormalizeData(Obj, normalization.method = "LogNormalize", scale.factor = 10000)
    Obj <- Obj[!grepl("^mt-", rownames(Obj)), ]
    Obj <- FindVariableFeatures(Obj, selection.method = "vst", nfeatures = 2000)
    Obj <- ScaleData(Obj)
    Obj <- RunPCA(Obj)
```
remove mito_gene before subset code like this:
```
Obj <- subset(Seurat_Obj, idents = idents)
  DefaultAssay(Obj) <- "RNA"
  Obj <- Obj[!grepl("^mt-", rownames(Obj)), ]
  Obj <- FindVariableFeatures(Obj, selection.method = "vst", nfeatures = 2000) 
  Obj <- ScaleData(Obj)  # gene 
  Obj <- RunPCA(Obj, npcs = nPCs)
  Obj <- RunUMAP(Obj, reduction = "pca", dims = 1:nPCs)
  Obj <- FindNeighbors(Obj, dims = 1:nPCs)
  Obj <- FindClusters(Obj, resolution = res)

```
I don't know If it's acceptable to remove mitochondrial genes, and is it ok to remove after normalzing?

Thank you!
Best

**Comment by igrabski** [comment]
Hi, if you are not interested in differentially expressed mitochondrial genes, the simplest solution would just be to set the `features` argument in `FindAllMarkers`. By default, `FindAllMarkers` uses all genes in differential testing. You could instead specify `features = rownames(Obj)[!grepl("^mt-", rownames(Obj))]`, which will result in testing all non-mitochondrial genes.

**Comment by yulchen810** [comment]
> Hi, if you are not interested in differentially expressed mitochondrial genes, the simplest solution would just be to set the `features` argument in `FindAllMarkers`. By default, `FindAllMarkers` uses all genes in differential testing. You could instead specify `features = rownames(Obj)[!grepl("^mt-", rownames(Obj))]`, which will result in testing all non-mitochondrial genes. 

Because this is single nuclei RNA-seq, the mitochondrial genes detected due to technical reason, it shouldn't exist, right? That's why I was thinking to remove it.
Thank you!

**Comment by yulchen810** [comment]
> Hi, if you are not interested in differentially expressed mitochondrial genes, the simplest solution would just be to set the `features` argument in `FindAllMarkers`. By default, `FindAllMarkers` uses all genes in differential testing. You could instead specify `features = rownames(Obj)[!grepl("^mt-", rownames(Obj))]`, which will result in testing all non-mitochondrial genes. 

By the way, mitochondrial genes exist in top DEGs in subsetted cell type, which means it affected clustering result, should I just ignoring that effection?

**Comment by igrabski** [comment]
Thanks for the follow-up question. In this case, it's hard to say without looking at the data why you are finding mitochondrial genes as highly differential expressed if there shouldn't be any present. If there is a relatively small subset of cells within that cell type that are highly expressing mitochondrial genes, you may want to investigate whether those cells warrant being removed; if the high expression of these genes is more widespread, there may be a more significant data quality issue. Without a better understanding of what is causing such high expression, unfortunately it's difficult as well to say whether these genes should be removed before or after normalization.

**Comment by yulchen810** [comment]
The mitochondrial genes present top in DEGs in a subcluster of oligodendrocyte and a subcluster of OPC. I also tried to remove all mitochondrial genes after nFeature, nCount ang mitochondrial genes percent filtering, and before normalize. it seems better.

**Comment by yulchen810** [comment]
> Thanks for the follow-up question. In this case, it's hard to say without looking at the data why you are finding mitochondrial genes as highly differential expressed if there shouldn't be any present. If there is a relatively small subset of cells within that cell type that are highly expressing mitochondrial genes, you may want to investigate whether those cells warrant being removed; if the high expression of these genes is more widespread, there may be a more significant data quality issue. Without a better understanding of what is causing such high expression, unfortunately it's difficult as well to say whether these genes should be removed before or after normalization. 

remove the cluster that highly expressed mitochondrial genes can be used. I will do this, Thank you.
