### ISSUE TITLE
handling reporter genes (like GFP, YFP ..)

### ISSUE THREAD

**Issue by 180910ldh** [satijalab/seurat#763]
I want to exclude reporter genes in FindVariablegene, FindMarkers and FindClusters but include those in FeaturePlot. 
Is there a command to exclude specific gene ?

**Comment by leonfodoulian** [comment]
Hi @180910ldh,

Simply remove those genes from `object@var.genes` after computing `Seurat::FindVariableGenes()`. By default, `Seurat::RunPCA()` uses the genes located in `object@var.genes` for PCA dimensionality reduction. 

```R
# R is case sensitive, so gene names should be written with the correct letter case
object@var.genes <- object@var.genes[-grep(pattern = "GFP|YFP", x = object@var.genes)]
```
Best,
Leon
