### ISSUE TITLE
How is ATAC data merged

### ISSUE THREAD

**Issue by GirayEryilmaz** [satijalab/seurat#7630]
While merging multiple Seurat objects of multiple modalities (GEX, ATAC and protein), how are chromatin assays merged?

I have read these issues https://github.com/satijalab/seurat/issues/2757 and https://github.com/satijalab/seurat/issues/4857 which refer to this [page](https://satijalab.org/signac/articles/merging.html) which is no longer available. 

Thank you.

**Comment by zskylarli** [comment]
Hi,
The vignette for scATAC-seq merging using the Signac package has been moved to this link:
https://stuartlab.org/signac/articles/merging.html
Hope this helps!
