### ISSUE TITLE
RenameAssays

### ISSUE THREAD

**Issue by RawanSO** [satijalab/seurat#7632]
Hi,
I wanted to rename an assay with a variable (assay_name = 'ToBeNamed') like RenameAssays(object = pbmc_small, assay_name = 'rna'). How to do that? Thanks

**Comment by longmanz** [comment]
Hi, 
You can create a new assay by `seurat_obj[['ToBeNamed']] = seurat_obj[['rna']]`, and then use `seurat_obj[['rna']] = NULL` to remove the original assay.

**Comment by RawanSO** [comment]
Thanks !
