### ISSUE TITLE
Integratedata

### ISSUE THREAD

**Issue by ramikheireddine** [satijalab/seurat#7633]
Hello, I am trying to integrate 8 data sets and although my computer has 70GBT Ram, it is crashing.
Is there any way around this issue?

**Comment by vishnums007** [comment]
Yes Rami. Get a new computer  :P

**Comment by ramikheireddine** [comment]
Not going to risk asking for that!

**Comment by Gesmira** [comment]
Hi, 
Although a new computer would be nice, if memory is an issue we recommend trying out [Seurat v5](https://satijalab.org/seurat/articles/install) as it integrates with [BPCells to allow for on-disk computations](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette). Check out all vignettes here: https://satijalab.org/seurat/articles/get_started_v5
