### ISSUE TITLE
Can I integrate visium data from different samples using SCTransform & SCT integration?

### ISSUE THREAD

**Issue by oghzzang** [satijalab/seurat#7634]
Dear seurat team.

I really thank to your wonderful package. 

Then, I have two questions.

1. Can I integrate SCTransformed visium data from different samples using SCT integration?

I saw a lot of tutorials and papers about the integration that combined multiple slide from same individual.

However, I didn't find the integration using multiple visium data derived from multiple individual.
(Actually, I already know we can integration the multiple datasets technically)

How do you think about that???

Whatever,, My question is..

can I integrate the multiple visium data from different samples using SCT integration algorithm like scRNA-seq tutorial? Is it reasonable?

2. If I want to compare the expression values between visium data derived from multiple individual, What slot & assay is your recommendation? 

visium_list <- list(A,B)
merged_obj <- merge(A, y = B, add.cell.ids = c("A", "B"))
merged_obj <- NormalizeData(merged_obj)
merged_obj <- FindVariableFeatures(merged_obj)
merged_obj <- ScaleData(merged_obj)
merged_obj <- SCTransform(merged_obj)

then, I can use these data to compare the two visium data
- Spatial assays:count, Spatial assays:data, Spatial assays:scale.data,
- SCT assays:data, SCT assays:scale.data,

So, My question is "what do you recommend to compare two visium data derived from two individuals?"

Many thanks!!

**Comment by saketkc** [comment]
Yes you can use SCT based integration for visisum data. For Average expression please use the data slot of SCT assay.

**Comment by oghzzang** [comment]
Thanks! @saketkc 

However, I found your answer. 

https://github.com/satijalab/seurat/issues/5009#issuecomment-907426252

In this answer you said like this

> If your library sizes are comparable across the different slides, you can compare the data slots of SCT assay. What currently happens is that SCTransform when correcting for library sequencing depth at the regression step substitutes the median library size, which could make the final corrected values not comparable across samples. We have addressed this in an update to sctransform which should land soon in the near future. But if the median sequencing depths are similar, the data slot is comparable.
> 
> If you do not expect huge slide to slide variation in terms of technical noise, you would get very similar results if you run SCTransform after merging. The idea behind splitting and then running SCTransform is to enable it to learn a dataset-specific model of technical noise (which could be very similar across samples in most cases).


My library sizes are very different across the different slides derived from individuals. 
In this case, can I compare the data average expression using the data slot of SCT assay?? 

<img width="740" alt="image" src="https://github.com/satijalab/seurat/assets/33537478/85261b3c-782c-4c9e-853f-04b702622829">

Many Thanks.

**Comment by dimurali93** [comment]
I have a similar issue. My library sizes varies 3 fold among different visium slides. Can I still use SCT before merging and run Harmony integration to compare genes across slides?

**Comment by isrgbf** [comment]
> Yes you can use SCT based integration for visisum data. For Average expression please use the data slot of SCT assay.

I have a few questions regarding this,

1- After doing SCTransform for each individual sample, then merging and doing SCTransform for the merged object, we split by orig.ident, but I have a dataset consisting of four samples, 2 for each group. I had to merge each group separately, and then merge those two objects together for differential expression, but I can't find a way to assign groups to each sample to use the group.by argument in FindAllMarkers. Do you have any recommendations regarding that?

2- I am doing manual annotation (because I don't have a scRNa reference dataset to integrate) but across developmental time points, which adds a lot of noise when running FindClusters on the integrated dataset. Do you recommend, in this case, using Harmony or RPCA integration? 

Thank you.
