### ISSUE TITLE
Adding Metadata categorizing cells by column name string

### ISSUE THREAD

**Issue by boogieman118** [satijalab/seurat#7640]
Hello! I am trying to categorize cells by the samples that they came from using column names in the count matrix.
For example, each cell column is named "HCC15_plate2_AO21924" in which the HCC15 indicates it came from patient 15. Is there an easy we to add meta-data that identifies the sample the cell came from purely based on cell column names, perhaps using a string-search function? 

Eventually, I hope to color color cells after clustering on gene expression by the patient that the cell came from

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The easiest way for the format of your cell barcodes is actually to do this during object creation.  You simply need to tell Seurat where the names are located and the delimiting variable.  In your case you would want:
```
OBJ <- CreateSeuratObject(counts = MAT, names.field = 1, names.delim = "_")
```

This will make all of those prefixes into labels in the `orig.ident` column.

Best,
Sam

**Comment by Gesmira** [comment]
Thanks for answering, @samuel-marsh! You can also use functions like `gsub()` to extract information from the rownames of the metadata (which are the same as your cell names) and then add them to the metadata like `obj$patient <-  gsub(" **your expression here** ", colnames(obj@meta.data))`
