### ISSUE TITLE
Issue during leverage score calculation "max(nu, nv) must be strictly less than min(nrow(A), ncol(A))"

### ISSUE THREAD

**Issue by singlecellfan** [satijalab/seurat#7650]
Hi all,

I am running the new v5 pipeline and I am currently stuck at this error that occurs during sketching. For each sample in my dataset I want to sketch 5,000 cells.
However, I always get this error.

Is there a solution to this?

Thank you in advance!

```
Calcuating Leverage Score
Error in irlba(A = object, nv = 50, nu = 0, verbose = FALSE) :
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))
Calls: SketchData ... LeverageScore.StdAssay -> LeverageScore -> LeverageScore.default -> irlba
```

**Comment by Gesmira** [comment]
How many cells/features does each sample have? Can you include the full code you run?

**Comment by singlecellfan** [comment]
Hi, 
I am running it on FACS data, meaning I have many cells and only few features.
In this example I have run it on 3.5 mio cells with 34 features.
The number of cells per sample ranges from 5,600 to over 40,000 cells.

This is how I run it:
`SketchData(object = object, ncells = 2000, method = "LeverageScore", sketched.assay = "sketch")`

Important to note that on the total dataset with 11 mio cells the function ran smoothly. It just seems to have a problem after subsetting the data to one cluster/cell population.

**Comment by Gesmira** [comment]
Hi, this should be fixed in the latest update of the seurat5 branch. Please restart your R session and update with:
`remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)`
