### ISSUE TITLE
ReadMtx is not recognizing the path 

### ISSUE THREAD

**Issue by nitinmahajan20** [satijalab/seurat#7651]
Hi, I using Seurat for many years, but am having this issue with the ReadMtx function recently. I gave the path and it worked fine for the first time, the problem starts when I reopen or want to reload the data. I don't change any path or anything, BUT it does not work. HOWEVER, it works, when I make a new folder and copy data in that or duplicate the data, then I give new path and it works.   The is issue is I am not able to re-read the folder more than one time. I tried to clear the environment, and restart the notebook. It seems that ReadMtx function is somehow prohibiting or locking the path to REREAD. Also, I tried the same thing using Scanpy, I am facing the same issue, but over there at least I am able to read the features.tsv and barcodes.tsv, but not the matrix.mtx. 

The following code works 
```{r}
data1 <- ReadMtx(
    mtx = paste0("/Users/xxx/Desktop/scRNA", "/matrix.mtx.gz"),
    features = paste0("/Users/xxx/Desktop/scRNA", "/features.tsv.gz"),
    cells = paste0("/Users/xxx/Desktop/scRNA", "/barcodes.tsv.gz")
)
```
However, when I try to reload this in same or new notebook, it does not.

I also tried to set the working dir as same, or giving the full path. 

I use Mac (Apple M1 Pro, Ventura 13.4.1c) and R Studio (Version 2023.06.1+52)

**Comment by zskylarli** [comment]
Hi - could you provide the error message?

**Comment by saketkc** [comment]
Hi @nitinmahajan20, can you post the error you are here? Given you are on a mac you can check if the file actually exists by doing `ls -ltrha /path/to/file` on your terminal.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
