### ISSUE TITLE
Heatmap analysis for an integrated Seurat Object

### ISSUE THREAD

**Issue by BartBryant** [satijalab/seurat#7652]
Hi
Following this tutorial on integration of two Seurat Objects
https://satijalab.org/seurat/archive/v3.0/immune_alignment

How can I obtain a Heatmap with (1) specific set of features and (2) specific cell types?

Thanks,
Bart

**Comment by mhkowalski** [comment]
Hello, 

You might find the documentation for `DoHeatmap` useful. You can specify which features you want with the `features` argument (just make sure those features are scaled prior to plotting). You can also specify which cells you would like to plot with the `cells` argument. (or subset your seurat object to only those cell types).

Hope this is helpful!

**Comment by BartBryant** [comment]
sorry @mhkowalski, I had more specific questions to this function

after following this tuturial
https://satijalab.org/seurat/archive/v3.0/immune_alignment.html
i have an integrated SeuratObject, specifically Wt versus mutant with up to 5 different cell types

can the 'DoHeatMap' function query a set of features within just two cell types found within Wt and mutant? 
Or is 'DoHeatMap' only for a single SeuratObject? 
If possible, can you give example lines of code?

Thanks for the tool, really enjoying Seurat, just want to get the most out of this very powerful tool
-Bart
