### ISSUE TITLE
Inf or very high numbers in avg-log2FC after FindAllMarkers() 

### ISSUE THREAD

**Issue by Fanny-bio** [satijalab/seurat#7657]
Hi all, I had a question when  I analysed my data.

I have five single-cell 10X data from similar samples. Here is my workflow:

1: read my five samples by Read10X 
2: Create Seurat Object separately
3: cell QC
4: SCTransform + integration by CCA
5: RunPCA -> RunUMAP -> FindNeighbors -> FindClusters
6: DefaultAssay "RNA"
7: Then, use FindAllMarkers to find the conserved genes, but the avg-log2FC values were very strange as shown below:
R-005218	7.876941e-157	133.465475	0.138	0.269	1.229827e-152	0	Res-005218
R-016714	0.000000e+00	Inf	0.918	0.792	0.000000e+00	1	Res-016714
R-016715	0.000000e+00	Inf	0.883	0.729	0.000000e+00	1	Res-016715
R-010944	0.000000e+00	Inf	0.862	0.747	0.000000e+00	1	Res-010944
R-015973	0.000000e+00	Inf	0.976	0.936	0.000000e+00	1	Res-015973
R-010239	0.000000e+00	765.537016	0.573	0.229	0.000000e+00	1	Res-010239

when I used NormalizeData + FindVariableFeatures to replace SCTransform, the data seemed ok.
Does anyone have some ideas about the problem? 

Thanks!

**Comment by Gesmira** [comment]
Hi, if you are using the RNA assay for your analysis, you should run NormalizeData before running FindMarkers. When you change the DefaultAssay to "RNA", then run `NormalizeData()`, to ensure outliers in expression don't dramatically impact the fold change calculations.
