### ISSUE TITLE
Using DESeq2 for DE analysis

### ISSUE THREAD

**Issue by jc271828** [satijalab/seurat#7659]
Hi Seurat Team,

I was wondering what's the way you guys would recommend doing DE analysis using DESeq2. From **the Choudhary and Satija paper (Fig S23)**, _DESeq2 was run using raw counts or sctransform v2 corrected counts as input_, it sounds like the authors used either raw counts from the RNA assay or "counts" slot in the SCT assay with test.use set to DESeq2 in FindMarkers (without doing pseudo-bulk).

A previous thread (https://github.com/satijalab/seurat/issues/7653#issuecomment-1668622499_) mentioned doing pseudo-bulk and using counts. So I was wondering how the Seurat team would recommend using DESeq2 at the end of the day:

1) pseudo-bulk data (using RNA counts or SCT counts for pseudo-bulk?) and then use DESeq2's DESeq function instead of Seurat's FindMarkers?
2) no pseudo-bulk, just use FindMarkers with assay = "RNA" and slot = "counts"?
3) no pseudo-bulk, just use FindMarkers with assay = "SCT" and slot = "counts" (this will throw an error. Somehow FindMarkers can't do assay = "SCT" and test.use = "DESeq2" at the same time, even with slot set to "counts")?

Thank you for your time!

**Comment by jc271828** [comment]
@Gesmira @longmanz @satijalab

**Comment by rbutleriii** [comment]
I see the test run in the 2022 paper run using the recommended adjusted methods, although it is unclear if that is with test="LRT":
![image](https://github.com/satijalab/seurat/assets/6644896/152feb82-2728-43b9-87bb-7673049f0bca)
@longmanz Is there a way to pass those to the `FindMarkers` ? I am unsure how you would call DESeq on a seurat object?

**Comment by jc271828** [comment]
Not part of the Seurat team, but based on their advice, I tried following DESeq2-side of the vignettes. Here’s a pretty good workbook on using DESeq2 on sc data https://hbctraining.github.io/scRNA-seq_online/lessons/pseudobulk_DESeq2_scrnaseq.html

It’s pseudo-bulk instead of running on individual cells like FindMarkers though.

Looking forward to more Seurat team’s insights!
