### ISSUE TITLE
Error in data.frame(..., check.names = FALSE) :    arguments imply differing number of rows:

### ISSUE THREAD

**Issue by yiklim** [satijalab/seurat#766]
Hi, I am trying to perform a CCA on 2 data sets. I am stuck at the visualization step after the RunCCA command. The command lines and error message are as follows:

```R
library(Seurat)
ctrl.data <- Seurat::Read10X("/Users/yiklimkok/Desktop/Run1Sample1_New_filtered_gene_bc_matrices/genome_GKO/")
stim.data <- Seurat::Read10X("/Users/yiklimkok/Desktop/Run1Sample2_New_filtered_gene_bc_matrices/genome_GKO/")
```

```R
ctrl <- CreateSeuratObject(raw.data = ctrl.data, project = "UNT", min.cells = 5)
ctrl@meta.data$stim <- "CTRL"
ctrl <- FilterCells(ctrl, subset.names = "nGene", low.thresholds = 500, high.thresholds = Inf)
ctrl <- NormalizeData(ctrl)
ctrl <- ScaleData(ctrl, display.progress = F)
```

```R
stim <- CreateSeuratObject(raw.data = stim.data, project = "GKO", min.cells = 5)
stim@meta.data$stim <- "STIM"
stim <- FilterCells(stim, subset.names = "nGene", low.thresholds = 500, high.thresholds = Inf)
stim <- NormalizeData(stim)
stim <- ScaleData(stim, display.progress = F)
```

```R
ctrl <- FindVariableGenes(ctrl, do.plot = F)
stim <- FindVariableGenes(stim, do.plot = F)
g.1 <- head(rownames(ctrl@hvg.info), 1000)
g.2 <- head(rownames(stim@hvg.info), 1000)
genes.use <- unique(c(g.1, g.2))
genes.use <- intersect(genes.use, rownames(ctrl@scale.data))
genes.use <- intersect(genes.use, rownames(stim@scale.data))
```

###ADDED add.cell.id1 = "ctrl"
```R
mdm.combined <- RunCCA(ctrl, stim, genes.use = genes.use, num.cc = 30, add.cell.id1 = "ctrl")
```

```R
p1 <- DimPlot(object = mdm.combined, reduction.use = "cca", group.by = "stim", pt.size = 0.5, do.return = TRUE)
p2 <- VlnPlot(object = mdm.combined, features.plot = "CC1", group.by = "stim", do.return = TRUE)
plot_grid(p1, p2)
```

```R
Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 9960, 6236
```

**Comment by yiklim** [comment]
Hi @andrewwbutler,

I got the error after trying to run: 
p2 <- VlnPlot(object = mdm.combined, features.plot = "CC1", group.by = "stim", do.return = TRUE)

And here is the traceback()

> traceback()
7: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
6: data.frame(..., check.names = FALSE)
5: cbind(deparse.level, ...)
4: cbind(data.return, data.add)
3: FetchData(object = object, vars.all = features.plot, ...)
2: data.frame(FetchData(object = object, vars.all = features.plot, 
       ...), check.names = F)
1: VlnPlot(object = mdm.combined, features.plot = "CC1", group.by = "stim", 
       do.return = TRUE)

Could this be due to the input? In the tutorial, the read.table function was used and the input file has the extension .txt.gz. 

If you would look at my input, I was using Seurat::Read10X with the files obtained directly from CellRanger as I did not know how to generate that file.

Also, when I was trying to perform a CCA using the following line:

mdm.combined <- RunCCA(ctrl, stim, genes.use = genes.use, num.cc = 30)

I obtained the following error message:

Error in MergeSeurat(object1 = object, object2 = object2, do.scale = FALSE, : Duplicate cell names, please provide 'add.cell.id1' and/or 'add.cell.id2' for unique names

So I modified the line to the following:

mdm.combined <- RunCCA(ctrl, stim, genes.use = genes.use, num.cc = 30, add.cell.id1 = "ctrl")

which allowed me to proceed with the next step. Would this mess up the data/analysis?

**Comment by yiklim** [comment]
Hi @andrewwbutler,

Any updates on my issue?

**Comment by akrausfish** [comment]
Hello,

Did anyone have a solution? I am having the same problem with VlnPlot after merging data with RunCCA.  I have updated everything as talked about in #199, but am still not able to visualize.

**Comment by xunsheng** [comment]
Tracking back, the issue seems start from 
`FetchData(object = object, vars.all = features.plot, ...)`

**Comment by andrewwbutler** [comment]
Hi @yiklim,

Sorry for the orphaned issue. Hopefully you were able to resolve this?
