### ISSUE TITLE
Extracting centroids of clusters in high-dimensional principal component space

### ISSUE THREAD

**Issue by brennandmcdonald** [satijalab/seurat#7660]
Hello,

I am interested in comparing the euclidian distances between single cell clusters as an initial step toward assessing cell type differentiation at different embryonic timepoints. I have read these two posts ([post 1](https://github.com/satijalab/seurat/issues/1419) and [post 2](https://github.com/lmcinnes/umap/issues/92)) about interpreting cluster distances based on UMAP coordinates, and they suggest that we should be cautious when drawing conclusions from this type of analysis because the layouts of clusters in UMAPs can sometimes be arbitrary.

However, it seems to me that this analysis could be improved by comparing the centroids of clusters in high-dimensional principal component space rather than just in the 2D UMAP manifold, which might take into account more gene expression information. Is there a way to extract the centroids of clusters in high-dimensional gene expression space?

Thank you for your help.

**Comment by igrabski** [comment]
Hi Brennand,

We don't have an automatic function to compute cluster centroids, but you could extract the PC embeddings (e.g. `seuratobject@reductions$pca@cell.embeddings`) and then compute the average values over the rows for each cluster. This will give you the centroid for each cluster, and from there, you can compute Euclidean distances between each pair of cluster centroids.
