### ISSUE TITLE
Remove scale.data

### ISSUE THREAD

**Issue by GirayEryilmaz** [satijalab/seurat#7662]
What is the right way to remove scale.data from a Seurat object with multiple modalities?

What I have is this:
```
DietSeurat(
  pbmc,
  counts = TRUE,
  data = TRUE,
  scale.data = FALSE,
  features = NULL,
  assays = NULL,
  dimreducs = Reductions(pbmc), #To keep all of the reductions
  graphs = Graphs(pbmc), #To keep all of the graphs
  misc = TRUE
)
```
Which seems to work. Is this the best way? 

Also, what about neighbors?

Thanks

**Comment by Gesmira** [comment]
Hi, 
Yes, you can use DietSeurat to subset your SeuratObject. Documentation is here: https://satijalab.org/seurat/reference/dietseurat
