### ISSUE TITLE
Where is integrated matrix stored in Seurat v5

### ISSUE THREAD

**Issue by zonghongz** [satijalab/seurat#7665]
Hello,
I am using seurat v5 to do integration, after I have done IntegrateLayers(), where I can extract integrated data matrix? 
for example, if I use old version of seurat, after integration I can get integrated matrix by seurat_obj@assay$integrated@data. However I could not find any integrated layers in my v5 seurat object, I would appreciate if you may help me out.

thank you
zong

**Comment by zskylarli** [comment]
Hi, the integrated embeddings will be saved in the reductions slot of your Seurat object. To access your integrated layer, use `[object_name]$[reduction_name]`. If you have any other questions, let us know!

**Comment by frenkiboy** [comment]
I think the original question refered to the integrated data matrix not to the integrated reduction. Could you please state where the integrated matrix is stored, and how to obtain it?

**Comment by tewengtong** [comment]
> I think the original question refered to the integrated data matrix not to the integrated reduction. Could you please state where the integrated matrix is stored, and how to obtain it?

Hi, do you find where is the integrated assay?
