### ISSUE TITLE
The legacy packages maptools, rgdal, and rgeos issue

### ISSUE THREAD

**Issue by terrytas** [satijalab/seurat#7669]
Hi

I believe that Seurat  still uses legacy packages maptools, rgdal, and rgeos, underpinning the sp package.

-------------------------------------------
> library(Seurat)
Loading required package: SeuratObject
Loading required package: sp
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
-------------------------------------------

Do you have a plan to update the code for sf in the place of sp in Seurat soon? 
If not, what will happen after October 2023? 
Will we not be able to use Seurat?

Best regards

Terry

**Comment by zskylarli** [comment]
Hi - we will be updating package requirements for Seurat V5 in an upcoming CRAN release. Thanks for pointing this out!

**Comment by terrytas** [comment]
Hi

Thanks a lot.

Terry

**Comment by terrytas** [comment]
Hi

"we will be updating package requirements for Seurat V5 in an upcoming CRAN release"
I wonder if the code has already been updated for sf.

regards

Terry
