### ISSUE TITLE
ADT normalisation unable to get rid of sample to sample technical differences

### ISSUE THREAD

**Issue by rcrueda** [satijalab/seurat#7675]
Hi Seurat team, 

I have 6 different 10x samples for which I have produced RNA and ADT data. The ADT consists on 20 T cell marker genes. I am reaching out because I am having some issues to properly normalise the ADT data. 

Probably due to differences in sequencing depths, differences in the abundance of marker genes expressed per cell and background noise, I see technical differences between my samples. This is for example clear to see when I look at CD4 and CD8 markers (since T cells are positive for one or the other I can always see a clear positive and negative signal per cell); the threshold between positive and negative varies quite a bit across the Expression Level axis for the different samples:
![image](https://github.com/satijalab/seurat/assets/74883075/ea036e67-307a-4830-b514-36c5fde21a31)
 
For the rest of my markers I often see a similar pattern, however, since I don't have a true negative control I'm finding it hard to trust if my expression levels are truly comparable. I attach some examples:
![image](https://github.com/satijalab/seurat/assets/74883075/aab9f284-720a-4fa1-b8a8-a6b6ff63e69f)

The code I am currently using to normalise the data is the following. 
seurat.list <- SplitObject(seurat, split.by = "Sample")
seurat.list <- lapply(X = seurat.list, FUN = function(x) {
  x <- NormalizeData(x, normalization.method = "CLR", margin = 2, assay = "ADT")
})
seurat <- merge(seurat.list [[1]], y = seurat.list [2:length(seurat.list )], merge.data = TRUE)

Has anyone faced a similar problem, and if so, is there any suggestions of how I can improve this normalisation? 

It is also not clear to me if it is necessary or when to decide to Scale or integrate ADT data.

Thank you very much for your time!

**Comment by mhkowalski** [comment]
Hi, 

I don't have a specific recommendation on how to compare ADTs across samples, as this can be challenging, as you observe. If you are trying to cluster on ADT's, you can try to perform the integration workflow on the ADT assay. Others have tried to use [empty droplets for ADT batch correction](https://www.nature.com/articles/s41467-022-29356-8).
