### ISSUE TITLE
normalisation by read length

### ISSUE THREAD

**Issue by thamsepia** [satijalab/seurat#7676]
I am using a scRNA seq platform that has UMIs but still has gene length biases as it uses both 3' primers and random hexamers.  I want to compare gene expression levels of a set of genes within the same cluster and need to correct the counts for transcript length on top of sequencing depth. Is there a way to correct for gene length biases after depth normalisation with seurat? 
Thank you

**Comment by longmanz** [comment]
Hi, 
Sorry, Seurat does not support normalisation by read length since the count matrix does not store the length information of each UMI/read.
