### ISSUE TITLE
compare 2 sequencing platform (nb of genes detected)

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#768]
Hi everyone,

The lab compare 2 experiments (PBMC proceed with 10x pipeline) and sequence the library once with _NextSeq_ and once with **NovaSeq.**

I don't understand why there are more genes detected with the NovaSeq than the NextSeq (around 1000) ?
_I am aware that there are more cells detected also but I don't get it._

If you have some information about that, thank you!

Camille

**Comment by satijalab** [comment]
This is likely because the NovaSeq returns more reads total, and therefore more reads per cell. You can see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5376499/ for more information on power analyses for scRNA-seq.
