### ISSUE TITLE
ProjectData(object = object, sketched.assay = "sketch", assay = "RNA", sketched.reduction = "integrated.rpca.full", full.reduction = "integrated.rpca.full")

### ISSUE THREAD

**Issue by zheng-sc** [satijalab/seurat#7681]
Hey Seurat Team,

I have a question regarding the `object <- ProjectData(object = object, sketched.assay = "sketch", assay = "RNA", sketched.reduction = "integrated.rpca.full", full.reduction = "integrated.rpca.full", dims = 1:30, refdata = list(celltype.full = "celltype.manual"))` from the [Sketch integration using a 1 million cell dataset from Parse Biosciences ](https://satijalab.org/seurat/articles/parsebio_sketch_integration) tutorial. I can't understand the `sketched.reduction = "integrated.rpca.full"` here. From my understanding it should be "integrated.rpca".

Thanks a lot for answering!

**Comment by Gesmira** [comment]
Hi, 
After you do `ProjectIntegration`, in the example, the full reduction for all of the cells will now be called "integrated.rpca.full" as it adds the .full specification at the end of the name of the sketched reduction. Realizing the parameter naming is a bit confusing here, `sketched.reduction` is now the name of the full reduction that will be used to `ProjectData`.  Then, here you could set `full.reduction` to something else as it will just be the name of the reduction, but to keep it consistent we name it "integrated.rpca.full" again. 
Hope that clarifies things!
