### ISSUE TITLE
Integrating data from different tissue types

### ISSUE THREAD

**Issue by amkhasawneh** [satijalab/seurat#7683]
Hello all.

I am currently trying to integrate PBMC and BM scRNA-seq data (in Seurat Objects) from the same individual/patient. Does it make sense to use Seurat to do this? Is the approach actually valid? 

Thank you.

**Comment by longmanz** [comment]
Hi, 
It is definitely okay to integrate PBMC and BM dataset, no matter if they are from the same individual or not. You may follow the standard CCA integration pipeline to do that (https://satijalab.org/seurat/articles/integration_introduction).

**Comment by amkhasawneh** [comment]
Thanks a lot!
