### ISSUE TITLE
Get general DEG list

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#769]
Hi everyone!

I want to compare the DEG list we obtained with Loupe browser with DEG list obtain with Seurat.
Problem is: with Loupe, I get the total DEG list, not a list by cluster. How can I get the same with Seurat?

Thanks

Camille

**Comment by satijalab** [comment]
You can run FindAllMarkers to obtain markers from each cluster, as described in:
https://satijalab.org/seurat/pbmc3k_tutorial.html

**Comment by camilliano** [comment]
I am sorry I don't get it at all...

So let me explain just to be sure!

I am following the tutorial: **Integrating stimulated vs. control PBMC datasets to learn cell-type specific responses**.

At the end, we can compare DEG between control set and treated set with this:
```
immune.combined@meta.data$celltype.stim <- paste0(immune.combined@ident, "_", immune.combined@meta.data$stim)
immune.combined <- StashIdent(immune.combined, save.name = "celltype")
immune.combined <- SetAllIdent(immune.combined, id = "celltype.stim")
b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL", 
print.bar = FALSE)
```
Which is great!
But I wanna try something like this:
```
FindMarkers(immune.combined, ident.1 = "allcells_STIM", ident.2 = "allcells_CTRL", 
    print.bar = FALSE)
```
_Like in bulk RNAseq (I know I know...)_

In `object@meta.data$orig.ident` we have the information of the identity of the two set combined and I don't understand why we cannot use this...

Sorry again if I don't understand what you propose.

**Comment by leonfodoulian** [comment]
Hi @camilliano,

If you want to have a list of DEG between your sample conditions, simply follow the first answer of @andrewwbutler:

```R
object <- SetAllIdent(object = object, id = "orig.ident")
markers <- FindAllMarkers(object = object)
```

Best,
Leon

**Comment by camilliano** [comment]
Great! Thanks everyone!
_(and sorry for the misunderstanding)_
