### ISSUE TITLE
Error with UpdateSeuratObject() and confirming workarounds.

### ISSUE THREAD

**Issue by Kim-Gihyeon** [satijalab/seurat#7691]
Hello! Thank you for developing this nice tool.

I got a RDS file from a paper by [Zheng, et. al. 2023](https://www.nature.com/articles/s43018-023-00599-8#data-availability). (The version of Seurat used in the paper is 3 and the SeuratObject is version 3.1.4)

I loaded as a seurat object by ```SueObj <- readRDS("raw_object.rds") ```
However, when I just call SeuObj, ```no slot of name "images" for this object of class "Seurat"``` error appeared.

So, I have tried SeuratObject::UpdateSeuratOjbect() according to the previous solution ([link](https://stackoverflow.com/questions/63589248/no-slot-of-name-images-error-when-trying-to-open-rds-file)). 
Unfortunately, I also got an error ```Error in !all.equal(target = md.features, current = data.features, check.attributes = FALSE) :  invalid argument type ```

To solve those errors, I tried the following workaround and those errors seemed to be solved, but I'm not sure if I did it correctly.
Workaround#1: Running ```SeuObj@images <- list()``` to solve ```no slot of name "images" for this object of class "Seurat"``` error.
Workaround#2: Running ```SeuObj@assays$RNA <- CreateAssay5Object(SeuOjb@assays$RNA@counts)``` to solve ```Error in !all.equal(target = md.features, current = data.features, check.attributes = FALSE) :  invalid argument type ```

If you don't mind, could you check that I have done right? And if I was wrong, could give me a solution?

Thank you for your help in advance.
Gihyeon.

_Session info_
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=ko_KR.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=ko_KR.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=ko_KR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ko_KR.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Seoul
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] openxlsx_4.2.5.2        HGNChelper_0.8.1        clustree_0.5.0          ggraph_2.1.0            future_1.33.0           randomcoloR_1.1.0.1    
 [7] ggsci_3.0.0             ggpubr_0.6.0            RColorBrewer_1.1-3      data.table_1.14.8       patchwork_1.1.2         lubridate_1.9.2        
[13] forcats_1.0.0           purrr_1.0.1             readr_2.1.4             tidyr_1.3.0             tibble_3.2.1            tidyverse_2.0.0        
[19] Matrix_1.6-0            stringr_1.5.0           gtools_3.9.4            magrittr_2.0.3          ggrepel_0.9.3           ggplot2_3.4.2          
[25] dplyr_1.1.2             Seurat_4.9.9.9058       SeuratObject_4.9.9.9091 sp_2.0-0               

loaded via a namespace (and not attached):
  [1] RcppAnnoy_0.0.21       splines_4.3.0          later_1.3.1            ggplotify_0.1.1        R.oo_1.25.0            polyclip_1.10-4       
  [7] fastDummies_1.7.3      lifecycle_1.0.3        rstatix_0.7.2          globals_0.16.2         lattice_0.21-8         MASS_7.3-60           
 [13] backports_1.4.1        plotly_4.10.2          httpuv_1.6.11          sctransform_0.3.5      zip_2.3.0              spam_2.9-1            
 [19] spatstat.sparse_3.0-2  reticulate_1.30        cowplot_1.1.1          pbapply_1.7-2          abind_1.4-5            Rtsne_0.16            
 [25] R.utils_2.12.2         yulab.utils_0.0.6      tweenr_2.0.2           irlba_2.3.5.1          listenv_0.9.0          spatstat.utils_3.0-3  
 [31] goftest_1.2-3          RSpectra_0.16-1        spatstat.random_3.1-5  fitdistrplus_1.1-11    parallelly_1.36.0      leiden_0.4.3          
 [37] codetools_0.2-19       ggforce_0.4.1          tidyselect_1.2.0       aplot_0.1.10           farver_2.1.1           viridis_0.6.4         
 [43] matrixStats_1.0.0      spatstat.explore_3.2-1 jsonlite_1.8.7         ellipsis_0.3.2         tidygraph_1.2.3        progressr_0.13.0      
 [49] ggridges_0.5.4         survival_3.5-5         systemfonts_1.0.4      tools_4.3.0            ragg_1.2.5             ica_1.0-3             
 [55] Rcpp_1.0.11            glue_1.6.2             gridExtra_2.3          withr_2.5.0            fastmap_1.1.1          fansi_1.0.4           
 [61] digest_0.6.33          timechange_0.2.0       R6_2.5.1               mime_0.12              gridGraphics_0.5-1     textshaping_0.3.6     
 [67] colorspace_2.1-0       scattermore_1.2        tensor_1.5             spatstat.data_3.0-1    R.methodsS3_1.8.2      utf8_1.2.3            
 [73] generics_0.1.3         graphlayouts_1.0.0     httr_1.4.6             htmlwidgets_1.6.2      uwot_0.1.16            pkgconfig_2.0.3       
 [79] gtable_0.3.3           lmtest_0.9-40          htmltools_0.5.5        carData_3.0-5          dotCall64_1.0-2        scales_1.2.1          
 [85] png_0.1-8              ggfun_0.1.1            rstudioapi_0.15.0      tzdb_0.4.0             reshape2_1.4.4         checkmate_2.2.0       
 [91] nlme_3.1-162           curl_5.0.1             zoo_1.8-12             KernSmooth_2.23-22     parallel_4.3.0         miniUI_0.1.1.1        
 [97] vipor_0.4.5            ggrastr_1.0.2          pillar_1.9.0           grid_4.3.0             vctrs_0.6.3            RANN_2.6.1            
[103] promises_1.2.0.1       car_3.1-2              xtable_1.8-4           cluster_2.1.4          beeswarm_0.4.0         cli_3.6.1             
[109] compiler_4.3.0         rlang_1.1.1            future.apply_1.11.0    ggsignif_0.6.4         labeling_0.4.2         plyr_1.8.8            
[115] ggbeeswarm_0.7.2       stringi_1.7.12         viridisLite_0.4.2      deldir_1.0-9           munsell_0.5.0          lazyeval_0.2.2        
[121] spatstat.geom_3.2-4    V8_4.3.3               RcppHNSW_0.4.1         hms_1.1.3              shiny_1.7.4.1          ROCR_1.0-11           
[127] igraph_1.5.0.1         broom_1.0.5

**Comment by Sidex71** [comment]
Hi, I think your approach is great. I am working with the same dataset too. You however would need to process the data again (normalize, scale, find variable features, PCA and clustering). The developers may have other necessary information to add though. 
May I ask, do you have access to the TCR sequencing data for this study?

**Comment by Sidex71** [comment]
> Hello! Thank you for developing this nice tool.
> 
> I got a RDS file from a paper by [Zheng, et. al. 2023](https://www.nature.com/articles/s43018-023-00599-8#data-availability). (The version of Seurat used in the paper is 3 and the SeuratObject is version 3.1.4)
> 
> I loaded as a seurat object by `SueObj <- readRDS("raw_object.rds") ` However, when I just call SeuObj, `no slot of name "images" for this object of class "Seurat"` error appeared.
> 
> So, I have tried SeuratObject::UpdateSeuratOjbect() according to the previous solution ([link](https://stackoverflow.com/questions/63589248/no-slot-of-name-images-error-when-trying-to-open-rds-file)). Unfortunately, I also got an error `Error in !all.equal(target = md.features, current = data.features, check.attributes = FALSE) : invalid argument type `
> 
> To solve those errors, I tried the following workaround and those errors seemed to be solved, but I'm not sure if I did it correctly. Workaround#1: Running `SeuObj@images <- list()` to solve `no slot of name "images" for this object of class "Seurat"` error. Workaround#2: Running `SeuObj@assays$RNA <- CreateAssay5Object(SeuOjb@assays$RNA@counts)` to solve `Error in !all.equal(target = md.features, current = data.features, check.attributes = FALSE) : invalid argument type `
> 
> If you don't mind, could you check that I have done right? And if I was wrong, could give me a solution?
> 
> Thank you for your help in advance. Gihyeon.
> 
> _Session info_ R version 4.3.0 (2023-04-21) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 22.04.2 LTS
> 
> Matrix products: default BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
> 
> locale: [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C LC_TIME=ko_KR.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=ko_KR.UTF-8 [6] LC_MESSAGES=en_US.UTF-8 LC_PAPER=ko_KR.UTF-8 LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C [11] LC_MEASUREMENT=ko_KR.UTF-8 LC_IDENTIFICATION=C
> 
> time zone: Asia/Seoul tzcode source: system (glibc)
> 
> attached base packages: [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages: [1] openxlsx_4.2.5.2 HGNChelper_0.8.1 clustree_0.5.0 ggraph_2.1.0 future_1.33.0 randomcoloR_1.1.0.1 [7] ggsci_3.0.0 ggpubr_0.6.0 RColorBrewer_1.1-3 data.table_1.14.8 patchwork_1.1.2 lubridate_1.9.2 [13] forcats_1.0.0 purrr_1.0.1 readr_2.1.4 tidyr_1.3.0 tibble_3.2.1 tidyverse_2.0.0 [19] Matrix_1.6-0 stringr_1.5.0 gtools_3.9.4 magrittr_2.0.3 ggrepel_0.9.3 ggplot2_3.4.2 [25] dplyr_1.1.2 Seurat_4.9.9.9058 SeuratObject_4.9.9.9091 sp_2.0-0
> 
> loaded via a namespace (and not attached): [1] RcppAnnoy_0.0.21 splines_4.3.0 later_1.3.1 ggplotify_0.1.1 R.oo_1.25.0 polyclip_1.10-4 [7] fastDummies_1.7.3 lifecycle_1.0.3 rstatix_0.7.2 globals_0.16.2 lattice_0.21-8 MASS_7.3-60 [13] backports_1.4.1 plotly_4.10.2 httpuv_1.6.11 sctransform_0.3.5 zip_2.3.0 spam_2.9-1 [19] spatstat.sparse_3.0-2 reticulate_1.30 cowplot_1.1.1 pbapply_1.7-2 abind_1.4-5 Rtsne_0.16 [25] R.utils_2.12.2 yulab.utils_0.0.6 tweenr_2.0.2 irlba_2.3.5.1 listenv_0.9.0 spatstat.utils_3.0-3 [31] goftest_1.2-3 RSpectra_0.16-1 spatstat.random_3.1-5 fitdistrplus_1.1-11 parallelly_1.36.0 leiden_0.4.3 [37] codetools_0.2-19 ggforce_0.4.1 tidyselect_1.2.0 aplot_0.1.10 farver_2.1.1 viridis_0.6.4 [43] matrixStats_1.0.0 spatstat.explore_3.2-1 jsonlite_1.8.7 ellipsis_0.3.2 tidygraph_1.2.3 progressr_0.13.0 [49] ggridges_0.5.4 survival_3.5-5 systemfonts_1.0.4 tools_4.3.0 ragg_1.2.5 ica_1.0-3 [55] Rcpp_1.0.11 glue_1.6.2 gridExtra_2.3 withr_2.5.0 fastmap_1.1.1 fansi_1.0.4 [61] digest_0.6.33 timechange_0.2.0 R6_2.5.1 mime_0.12 gridGraphics_0.5-1 textshaping_0.3.6 [67] colorspace_2.1-0 scattermore_1.2 tensor_1.5 spatstat.data_3.0-1 R.methodsS3_1.8.2 utf8_1.2.3 [73] generics_0.1.3 graphlayouts_1.0.0 httr_1.4.6 htmlwidgets_1.6.2 uwot_0.1.16 pkgconfig_2.0.3 [79] gtable_0.3.3 lmtest_0.9-40 htmltools_0.5.5 carData_3.0-5 dotCall64_1.0-2 scales_1.2.1 [85] png_0.1-8 ggfun_0.1.1 rstudioapi_0.15.0 tzdb_0.4.0 reshape2_1.4.4 checkmate_2.2.0 [91] nlme_3.1-162 curl_5.0.1 zoo_1.8-12 KernSmooth_2.23-22 parallel_4.3.0 miniUI_0.1.1.1 [97] vipor_0.4.5 ggrastr_1.0.2 pillar_1.9.0 grid_4.3.0 vctrs_0.6.3 RANN_2.6.1 [103] promises_1.2.0.1 car_3.1-2 xtable_1.8-4 cluster_2.1.4 beeswarm_0.4.0 cli_3.6.1 [109] compiler_4.3.0 rlang_1.1.1 future.apply_1.11.0 ggsignif_0.6.4 labeling_0.4.2 plyr_1.8.8 [115] ggbeeswarm_0.7.2 stringi_1.7.12 viridisLite_0.4.2 deldir_1.0-9 munsell_0.5.0 lazyeval_0.2.2 [121] spatstat.geom_3.2-4 V8_4.3.3 RcppHNSW_0.4.1 hms_1.1.3 shiny_1.7.4.1 ROCR_1.0-11 [127] igraph_1.5.0.1 broom_1.0.5

Hi, I think your approach is great. I am working with the same dataset too. You however would need to process the data again (normalize, scale, find variable features, PCA and clustering). The developers may have other necessary information to add though.
May I ask, do you have access to the TCR sequencing data for this study?

**Comment by Kim-Gihyeon** [comment]
> > Hello! Thank you for developing this nice tool.
> > I got a RDS file from a paper by [Zheng, et. al. 2023](https://www.nature.com/articles/s43018-023-00599-8#data-availability). (The version of Seurat used in the paper is 3 and the SeuratObject is version 3.1.4)
> > I loaded as a seurat object by `SueObj <- readRDS("raw_object.rds") ` However, when I just call SeuObj, `no slot of name "images" for this object of class "Seurat"` error appeared.
> > So, I have tried SeuratObject::UpdateSeuratOjbect() according to the previous solution ([link](https://stackoverflow.com/questions/63589248/no-slot-of-name-images-error-when-trying-to-open-rds-file)). Unfortunately, I also got an error `Error in !all.equal(target = md.features, current = data.features, check.attributes = FALSE) : invalid argument type `
> > To solve those errors, I tried the following workaround and those errors seemed to be solved, but I'm not sure if I did it correctly. Workaround#1: Running `SeuObj@images <- list()` to solve `no slot of name "images" for this object of class "Seurat"` error. Workaround#2: Running `SeuObj@assays$RNA <- CreateAssay5Object(SeuOjb@assays$RNA@counts)` to solve `Error in !all.equal(target = md.features, current = data.features, check.attributes = FALSE) : invalid argument type `
> > If you don't mind, could you check that I have done right? And if I was wrong, could give me a solution?
> > Thank you for your help in advance. Gihyeon.
> > _Session info_ R version 4.3.0 (2023-04-21) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 22.04.2 LTS
> > Matrix products: default BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
> > locale: [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C LC_TIME=ko_KR.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=ko_KR.UTF-8 [6] LC_MESSAGES=en_US.UTF-8 LC_PAPER=ko_KR.UTF-8 LC_NAME=C LC_ADDRESS=C LC_TELEPHONE=C [11] LC_MEASUREMENT=ko_KR.UTF-8 LC_IDENTIFICATION=C
> > time zone: Asia/Seoul tzcode source: system (glibc)
> > attached base packages: [1] stats graphics grDevices utils datasets methods base
> > other attached packages: [1] openxlsx_4.2.5.2 HGNChelper_0.8.1 clustree_0.5.0 ggraph_2.1.0 future_1.33.0 randomcoloR_1.1.0.1 [7] ggsci_3.0.0 ggpubr_0.6.0 RColorBrewer_1.1-3 data.table_1.14.8 patchwork_1.1.2 lubridate_1.9.2 [13] forcats_1.0.0 purrr_1.0.1 readr_2.1.4 tidyr_1.3.0 tibble_3.2.1 tidyverse_2.0.0 [19] Matrix_1.6-0 stringr_1.5.0 gtools_3.9.4 magrittr_2.0.3 ggrepel_0.9.3 ggplot2_3.4.2 [25] dplyr_1.1.2 Seurat_4.9.9.9058 SeuratObject_4.9.9.9091 sp_2.0-0
> > loaded via a namespace (and not attached): [1] RcppAnnoy_0.0.21 splines_4.3.0 later_1.3.1 ggplotify_0.1.1 R.oo_1.25.0 polyclip_1.10-4 [7] fastDummies_1.7.3 lifecycle_1.0.3 rstatix_0.7.2 globals_0.16.2 lattice_0.21-8 MASS_7.3-60 [13] backports_1.4.1 plotly_4.10.2 httpuv_1.6.11 sctransform_0.3.5 zip_2.3.0 spam_2.9-1 [19] spatstat.sparse_3.0-2 reticulate_1.30 cowplot_1.1.1 pbapply_1.7-2 abind_1.4-5 Rtsne_0.16 [25] R.utils_2.12.2 yulab.utils_0.0.6 tweenr_2.0.2 irlba_2.3.5.1 listenv_0.9.0 spatstat.utils_3.0-3 [31] goftest_1.2-3 RSpectra_0.16-1 spatstat.random_3.1-5 fitdistrplus_1.1-11 parallelly_1.36.0 leiden_0.4.3 [37] codetools_0.2-19 ggforce_0.4.1 tidyselect_1.2.0 aplot_0.1.10 farver_2.1.1 viridis_0.6.4 [43] matrixStats_1.0.0 spatstat.explore_3.2-1 jsonlite_1.8.7 ellipsis_0.3.2 tidygraph_1.2.3 progressr_0.13.0 [49] ggridges_0.5.4 survival_3.5-5 systemfonts_1.0.4 tools_4.3.0 ragg_1.2.5 ica_1.0-3 [55] Rcpp_1.0.11 glue_1.6.2 gridExtra_2.3 withr_2.5.0 fastmap_1.1.1 fansi_1.0.4 [61] digest_0.6.33 timechange_0.2.0 R6_2.5.1 mime_0.12 gridGraphics_0.5-1 textshaping_0.3.6 [67] colorspace_2.1-0 scattermore_1.2 tensor_1.5 spatstat.data_3.0-1 R.methodsS3_1.8.2 utf8_1.2.3 [73] generics_0.1.3 graphlayouts_1.0.0 httr_1.4.6 htmlwidgets_1.6.2 uwot_0.1.16 pkgconfig_2.0.3 [79] gtable_0.3.3 lmtest_0.9-40 htmltools_0.5.5 carData_3.0-5 dotCall64_1.0-2 scales_1.2.1 [85] png_0.1-8 ggfun_0.1.1 rstudioapi_0.15.0 tzdb_0.4.0 reshape2_1.4.4 checkmate_2.2.0 [91] nlme_3.1-162 curl_5.0.1 zoo_1.8-12 KernSmooth_2.23-22 parallel_4.3.0 miniUI_0.1.1.1 [97] vipor_0.4.5 ggrastr_1.0.2 pillar_1.9.0 grid_4.3.0 vctrs_0.6.3 RANN_2.6.1 [103] promises_1.2.0.1 car_3.1-2 xtable_1.8-4 cluster_2.1.4 beeswarm_0.4.0 cli_3.6.1 [109] compiler_4.3.0 rlang_1.1.1 future.apply_1.11.0 ggsignif_0.6.4 labeling_0.4.2 plyr_1.8.8 [115] ggbeeswarm_0.7.2 stringi_1.7.12 viridisLite_0.4.2 deldir_1.0-9 munsell_0.5.0 lazyeval_0.2.2 [121] spatstat.geom_3.2-4 V8_4.3.3 RcppHNSW_0.4.1 hms_1.1.3 shiny_1.7.4.1 ROCR_1.0-11 [127] igraph_1.5.0.1 broom_1.0.5
> 
> Hi, I think your approach is great. I am working with the same dataset too. You however would need to process the data again (normalize, scale, find variable features, PCA and clustering). The developers may have other necessary information to add though. May I ask, do you have access to the TCR sequencing data for this study?

Hi, thank you for your reply.
Unfortunately, I do not have the TCR sequencing data from this study.
Hope you will find it!
