### ISSUE TITLE
Error with plot functions: Graphic API version mismatch

### ISSUE THREAD

**Issue by AmirhosseinQ1** [satijalab/seurat#7692]
Hello!
I have been trying to use `Vlnplot(Data[[1]], features = "nFeature_RNA)` to draw a violin plot, but I get the following error:
`Error in RStudioGD() : 
  Shadow graphics device error: r error 4 (Error in grDevices:::png("C:/Users/A0367~1.GHO/AppData/Local/Temp/Rtmp4ciOvX/9288a30261f54326afc6b948b6e47626.png",  : 
  Graphics API version mismatch
)`

I tried updating packages like ragg and Cairo but the error still remained.
this is my `sessioninfo()`

`
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This issue does not seem to be related to Seurat itself but more an issue with R/RStudio communication and graphics device.  My best guess to try first would be deleting and re-installing RStudio and if that does not solve the issue I suggest posting in RStudio forum or contacting their support for more assistance.

Best,
Sam

**Comment by AmirhosseinQ1** [comment]
Thanks Samuel;
As Samuel said, It didn't relate to Seurat. After updating `ragg` and choosing this package as the default graphic package in `tool` >> `global options...` >> `Graphics` >> `Backend`, I noticed that my `grDevices` package version was built for R 4.2.2, not R 4.3.1. So, I simply reinstall R:)
