### ISSUE TITLE
Issues with subset() on seurat object

### ISSUE THREAD

**Issue by groy87** [satijalab/seurat#7693]
Hi,

I am trying to subset certain clusters from an integrated seurat object to run further analysis `merged_seurat.beta <- subset(merged_seurat, subset = seurat_clusters == c(3,7,13,19,20,21))` and getting this warning:

`Warning messages:
1: In ==.default(seurat_clusters, c(3, 7, 13, 19, 20, 21)) :
  longer object length is not a multiple of shorter object length
2: In is.na(e1) | is.na(e2) :
  longer object length is not a multiple of shorter object length`

The number of cells in clusters 3, 7,13,19,20,21 combined is 2239 but after subsetting the total number of cells is 375 only. Why is it removing cells on subsetting?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This has to due to with the inherent behavior of `==` vs `%in%` in R.  What you want in this situation is `%in%`.
```
merged_seurat.beta <- subset(merged_seurat, subset = seurat_clusters %in% c(3,7,13,19,20,21))
```

Alternatively if `seurat_clusters` is the active ident then you can just do:
```
merged_seurat.beta <- subset(merged_seurat, idents = c(3,7,13,19,20,21))
```

Best,
Sam
