### ISSUE TITLE
Calculate average gene expression per voxel post integration for Visium

### ISSUE THREAD

**Issue by TeodoraTockovska** [satijalab/seurat#7695]
Hi, Seurat dev team! I wanted to thank you for creating such a powerful tool for scRNAseq and spatial transcriptomics analysis.

I wanted to ask if it is possible to implement a feature in Seurat for calculating the average gene expression per voxel for spatial transcriptomics (Visium) analysis post integration. I have a project with 10 Visium samples which I've integrated into 1 object. I've selected 1 sample as my representative image to show the expression for a few genes of interest. It would be really interesting to see what the average gene expression values would be for a gene from all samples on the 1 representative image. I can foresee issues with implementing what I am asking because every sample has its own image and set of coordinates. However, after data integration and clustering, the voxels should have similar gene expression values among samples, so maybe it would be possible.

**Comment by alikhuseynov** [comment]
Hi there,
I'm not directly from the team, though, I think, the simplest one is [`AverageExpression()`](https://satijalab.org/seurat/reference/averageexpression) with `group.by = "samples"` to get it per sample or per cluster `"seurat_clusters"` . 
If per cluster, then add the resultant average value to the corresponding cluster of 1st representative sample object. Eg, if the PECAM1 average expression across 4 samples in cluster 2 has a value of 10, then the whole cluster 2 of 1st representative sample object will get that value, and so on for the other clusters..

A bit more work would be needed to have the consensus or average spatial gene expression map of all the samples on selected representative image. If the samples are consecutive sections, then the spot coordinates can be aligned.
If sample sections are non-consecutive, then one can get top nearest neighbors (nns) from ` FindNeighbors()` per spot and calculate mean expression of those top nns per gene. Then add to object metadata (per gene).

<details>
  <summary> For now something like this can be done: </summary>
  
```
# function to return metadata of Seurat obj ----
    callmeta <- function(object = NULL) {
        return(object@meta.data) 
    }

# run data processing if need, else use already available object ----
obj %<>% # merged Visium data object 
  SCTransform(assay = "Spatial", verbose = FALSE) %>%
  RunPCA(assay = "SCT", verbose = FALSE) %>%
  FindNeighbors(reduction = "pca", dims = 1:30,
                return.neighbor = TRUE # NOTE: important to return the graph
  )

# get expression data ----
expr.df <- 
  FetchData(obj, 
            vars = rownames(obj), # vector of all genes or only selected genes 
            slot = "data") %>%
  # add samples meta var
  mutate(samples = obj$samples)
expr.df %>% str

# subset obj for 3rd sample, ie representative image ----
Idents(obj) <- "samples"
obj.3 <- subset(obj, idents = "MB295_B")
obj.3
# keep only selected image/section, in this case sample 3
obj.3@images <- obj.3@images[3]

# calculate mean expression ----
# ..using top nearest neighbors per spot id of 3rd (representative sample)
nns <- 10 # how many top nearest neighbors to use
df.mean.expr <-
  BiocParallel::bplapply(
    Cells(obj.3) %>% seq(), function(spot) {
      expr.df %>%
        slice(Indices(obj@neighbors$Spatial.nn)[Cells(obj.3)[spot], 1:nns]) %>% 
        reshape2::melt() %>%
        group_by(variable) %>%
        summarise(mean.expr = mean(value)) %>%
        mutate(spot.id = Cells(obj.3)[spot])
    }, BPPARAM = BiocParallel::MulticoreParam(10, 
                                              tasks = 30L,
                                              force.GC = FALSE, 
                                              progressbar = TRUE)) %>% 
  suppressMessages() %>% 
  data.table::rbindlist() %>%
  # remove any factor vars
  mutate_if(is.factor, as.character.factor)
df.mean.expr %>% str

# 1st gene for all spots
df.mean.expr %>% 
  mutate_if(is.factor, as.character.factor) %>%
  filter(variable == pull(., variable) %>% .[1]) %>% str

# add mean gene expression to object metadata - per gene ----
for (i in c(df.mean.expr %>% 
              pull(., variable) %>% 
              unique() %>% seq())) {
  obj.3 %<>% AddMetaData(metadata = df.mean.expr %>% 
                           filter(variable == pull(., variable) %>% .[i]) %>% 
                           pull(mean.expr), 
                         col.name = paste0(df.mean.expr %>% pull(., variable) %>% .[i], ".mean.expr")
  ) 
}
obj.3 %>% callmeta() %>% str

# plot selected gene expression on representative sample 3 object
SpatialFeaturePlot(obj.3, features = "FOS")

# plot selected mean gene expression on representative sample 3 object
SpatialFeaturePlot(obj.3, features = "FOS.mean.expr")
```
</details>

Hope this helps.

**Comment by TeodoraTockovska** [comment]
@alikhuseynov Thank you so much for your comment! I will look into the code, I really appreciate it. Have a nice day!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
