### ISSUE TITLE
SCTransform vs. NormalizeData

### ISSUE THREAD

**Issue by oghzzang** [satijalab/seurat#7699]
Dear @rsatija @saketkc, 

I really appreciate this wonderful tool. 
In the normalization step, there are two representative tools in seurat (NormalizeData, and SCTransform).
I saw a lot of issues & your paper about SCTransform (Hafemeister and Satija, 2019).
But I have several questions yet. 

Question 1. In this issue, https://github.com/satijalab/seurat/issues/5009#issuecomment-907426252
you said like this. 

> **If your library sizes are comparable across the different slides, you can compare the data slots of SCT assay.** What currently happens is that SCTransform when correcting for library sequencing depth at the regression step substitutes the median library size, which could make the final corrected values not comparable across samples. We have addressed this in an update to sctransform which should land soon in the near future. But if the median sequencing depths are similar, the data slot is comparable.

**_Then, does it mean "If the samples have different nCount_RNA (P<0.05 in Willcoxon's rank sum or Kruskal Walis test), We couldn't use SCTransform to integrate dataset"?_**

**_Question 2. Can I use the normlization method like this?_** 
Step1) For Integration only,
(1) SCTransform by each samples
(2) SCT Integration using Seurat tutorial
(3) Clustering

Step2) For finding DEG or downstream analysis
(1) conventional NormalizeData & FindVariableFeatures & ScaleData 
(2) Set default assay as 'RNA'
(3) Find DEG across Integrated slot-based clusters
(4) Use 'RNA' slot for Downstream analysis (Pseudotime, Cell-Cell interaction, etc)

**_Question 3. Can I use the data like this for downstream analysis?_**
1) SCTransform by each samples 
2) Just merge them
3) Find the variable features & aggregate them across the samples
4) RunPCA & Clustering
5) Use the SCT data slot to compare the each samples.

Many thanks!!!!

**Comment by saketkc** [comment]
Hi @oghzzang, these questions should be addressed in [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette). You can use SCT for all the tasks you mentioned - integration, differential expression, visualization.

**Comment by maithermbarros** [comment]
@saketkc the link is broken, can you please provide the new one? I searched for a similar vignette, but only fond it for version 5 but I am still using version 4. Thanks a lot

**Comment by saketkc** [comment]
See the archive: https://satijalab.org/seurat/archive/v4.3/sctransform_v2_vignette
