### ISSUE TITLE
The `slot` argument of `Assays()` was deprecated in SeuratObject 5.0.0 and is now defunct.

### ISSUE THREAD

**Issue by nbutyrate** [satijalab/seurat#7701]
Hi, I am trying to analyze a Seurat object in the SCP package, and its throwing the following error.

Could you please take a look and let me know if its something you could help me resolve, 

DIS_sub <- SCP::RunDEtest(srt = DIA_sub1, group_by = "Cell_Type", fc.threshold = 1, only.pos = FALSE)
[2023-08-20 18:48:35] Start DEtest
Workers: 14
Error:
! The `slot` argument of `Assays()` was deprecated in SeuratObject 5.0.0 and is now defunct.
ℹ Please use `LayerData()` instead.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by longmanz** [comment]
Hi,
In Seurat V5, "slot" no longer exists. If you want to keep using SCP package, you may need to revert back to Seurat V4. Or you may need to wait for SCP's update so that it is compatible with Seurat V5.
