### ISSUE TITLE
Method to create a smaller object using "CreateSeuratObject" or "subset"

### ISSUE THREAD

**Issue by npatel-ah** [satijalab/seurat#7702]
Hello, 

Thanks for the great tool and detailed documentation. 

My goal is reduce the size of Seurat object (primarily because Monocle2 fails during one of the step due "long vectors not supported yet:" error, Please note the Seurat object I am trying to run Monocle2 is much larger than the example below)

I tried two ways and thought they would yield sample results but they do not and wanted to understand what is difference between these two methods. 

Here is the base object 
```
pbmc_raw
An object of class Seurat
25939 features across 17301 samples within 1 assay
Active assay: RNA (25939 features, 2000 variable features)
 3 dimensional reductions calculated: pca, tsne, umap

```

Method1

```
pbmc1 = CreateSeuratObject(counts  = pbmc_raw[["RNA"]]@counts,min.cells=20, min.features=400)
pbmc1 = AddMetaData(object = pbmc1, metadata = pbmc_raw$cell_type, col.name = 'cell_type')
pbmc1
An object of class Seurat
19613 features across 16914 samples within 1 assay
Active assay: RNA (19613 features, 0 variable features)
```

Method2

```
pbmc2 <- subset( x = pbmc_raw,  subset = nFeature_RNA > 400 & nCount_RNA > 20)
pbmc2
An object of class Seurat
25939 features across 16914 samples within 1 assay
Active assay: RNA (25939 features, 2000 variable features)
 3 dimensional reductions calculated: pca, tsne, umap

```
I am truly grateful for your assistance in understanding the distinctions.

Thanks.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.
So just to clarify are you trying to sub-sample a larger object or just to reduce large object to only essential information?

In general for reducing size of object without sub-sampling you should look at `DietSeurat` function.

In terms of differences between your two approaches you show.
In the first you are creating new object taking just the raw data then filtering it so only genes which are present in 20 or more cells or cells with 400 or more genes are retained.  Hence the reduction in both number of cells and number of genes and loss of reductions/variable genes.

In second example you are taking object and filtering the cells included by only retaining those with more than 400 features (you are also only retaining cells with more than 20 UMIs but that’s already going to be done by the genes > 400).  That’s why only cell number is reduced and reductions/vat genes are retained.

Best,
Sam

**Comment by longmanz** [comment]
Hi,
Many thanks to @samuel-marsh for the explanation! Yes, the "Method2" only performs filtering to the cells, instead of the features. If you want to remove features as well (not necessary in most cases), you may use "Method1" or do it manually with `pbmc_raw = subset(pbmc_raw, features = list_of_features_with_min_cell_20)`, where the `list_of_features_with_min_cell_20` being the list of features you generate based on min.cells >= 20.

**Comment by npatel-ah** [comment]
Thank you much both of you for clarification.
