### ISSUE TITLE
Different DEG results from different analysis methods for SCT integrated object

### ISSUE THREAD

**Issue by Frank1213817** [satijalab/seurat#7704]
Dear Seurat Team,

I am using Seurat v4.3 to analyze an integrated object. When it comes to finding marker genes for each cluster, I have tried 3 different approaches and it has given me 3 different outputs. 

I have tried:
① SCT integration → PrepSCTFindMarkers → FindAllMarkers(assay = "SCT")
② SCT integration → FindAllMarkers(assay = "RNA")
③ SCT integration → NormalizeData(assay = "RNA") → FindVariableFeatures → ScaleData → FindAllMarkers(assay = "RNA")

I am wondering which one would be the correct way to do DE analysis.

I have seen quite a number of posts regarding the assay to use in FindMarkers but I haven't come to a conclusion.
Looking forward to any comments and it is really important for me. Thank you!!!!

**Comment by saketkc** [comment]
Hi @Frank1213817,

I would recommend using the latest Seurat from develop branch (using `remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("satijalab/seurat", "develop", quiet = TRUE)`. We made some fixes to ensure that `FindMarkers` returns consistent results. That said, if you are using SCT for integration, I would recommend using the SCT assay for finding markers (your workflow #1)
