### ISSUE TITLE
Hermony integration method doesn't properly assign reduction name

### ISSUE THREAD

**Issue by wudustan** [satijalab/seurat#7705]
When running IntegrateLayers() the HarmonyIntegration method doesn't feed `new.reduction` to the resulting object.

      merge.seurat <- IntegrateLayers(
      object = merge.seurat, method = CCAIntegration, group.by = "merge.factor",
      orig.reduction = "pca", new.reduction = "integrated.cca",
      verbose = TRUE
    )
    merge.seurat <- IntegrateLayers(
      object = merge.seurat, method = RPCAIntegration, group.by = "merge.factor",
      orig.reduction = "pca", new.reduction = "integrated.rpca",
      verbose = TRUE
    )
    merge.seurat <- IntegrateLayers(
      object = merge.seurat, method = HarmonyIntegration, group.by = "merge.factor",
      orig.reduction = "pca", new.reduction = "integrated.harmony",
      verbose = TRUE
    )
    merge.seurat <- IntegrateLayers(
      object = merge.seurat, method = FastMNNIntegration, group.by = "merge.factor",
      orig.reduction = "pca", new.reduction = "integrated.mnn",
      verbose = TRUE
    )
    merge.seurat <- IntegrateLayers(
      object = merge.seurat, method = scVIIntegration, group.by = "merge.factor",
      orig.reduction = "pca", new.reduction = "integrated.scvi",
      conda_env = "~/miniconda3/envs/scvi-env/",
      verbose = TRUE
    )
    names(merge.seurat@reductions)

```
> names(merge.seurat@reductions)
[1] "pca"             "integrated.cca"  "integrated.rpca" "harmony"         "integrated.mnn"  "integrated.scvi"
```

**Comment by Gesmira** [comment]
Apologies for the late response, but this is now fixed in the newest version of Seurat on CRAN. Please reopen if you continue to have issues.
