### ISSUE TITLE
Read10X_Image incorrectly sets the value of spot to scale.factors$tissue_hires_scalef

### ISSUE THREAD

**Issue by brianraymor** [satijalab/seurat#7706]
This is based on reading the code and reviewing with @mojaveazure.

[Read10X_Image ](https://github.com/satijalab/seurat/blob/8da9ee677a9613988c4d585ec825524c0586ea92/R/preprocessing.R#L1170C1-L1175C7)  incorrectly processes the value of spot from spaceranger scalefactors_json.json:

    scale.factors = scalefactors(
      spot = scale.factors$tissue_hires_scalef,
      fiducial = scale.factors$fiducial_diameter_fullres,
      hires = scale.factors$tissue_hires_scalef,
      scale.factors$tissue_lowres_scalef
    ),

`spot` should be:

`    spot = scale.factors$spot_diameter_fullres
`

**Comment by realzehuali** [comment]
Yeah, I think you are right. I also found this might be a problem.

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat as of 4616cc6 and will make its way to CRAN in the near future. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1).
