### ISSUE TITLE
when conducting findmarker how to calculate pvalue/fc of given gene that cells only expressed

### ISSUE THREAD

**Issue by DM0815** [satijalab/seurat#7708]
when conducting findmarker how to calculate pvalue/fc of given gene that cells only expressed. In other words, if which cell didn't express given gene, I need to remove  it, it similar to the codes'' data <- data[data$given gene!= 0, ]'',then  calculate genes's p-value and log2FC

**Comment by longmanz** [comment]
Hi,
We generally do not recommend removing cells as you described. That would create bias when calculating log2FC or P-values. You are free to do it manually by extracting this gene from seurat_obj@assays$RNA$data["given_gene", ] and then remove those 0 from it and calculate log2FC or run Wilcoxon Rank Sum test to get the DE p-values.
