### ISSUE TITLE
HTOdemux returns warning and NAs

### ISSUE THREAD

**Issue by ElisaRosatiScalchi** [satijalab/seurat#7709]
I am running HTOdemux on my seurat object with the following code:
```
 read_gex <- Read10X(data.dir = tmp)  # Seurat function to read in 10x count data
    rna=read_gex$`Gene Expression`
   #define hto number and names if necessary
    cite=read_gex$`Antibody Capture`#[1:hto_number,]
    joint.bcs <- intersect(colnames(cite), colnames(rna))
    
   # Subset RNA and HTO counts by joint cell barcodes
    rna <- rna[, joint.bcs]
    cite <- cite[, joint.bcs]

# Create seurat
    seurat <- CreateSeuratObject(counts = rna, project = sample_name_short, min.cells = 5, min.features = 200) 
    
    hto=cite[grep("Hashtag",row.names(cite)),]
    hto <- hto[, row.names(seurat@meta.data)]
    seurat[["HTO"]] <- CreateAssayObject(counts =hto)
    seurat$barcode=paste(row.names(seurat@meta.data),seurat$orig.ident,sep=".")
    row.names(seurat@meta.data)<-seurat$barcode
    
    #normalize and PCA
    all.genes <- rownames(seurat) 
    seurat<- Seurat::NormalizeData(seurat,verbose = FALSE) %>%
      FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
      ScaleData(verbose = FALSE,features = all.genes) %>% 
      RunPCA(pc.genes = seurat@var.genes, npcs = 20, verbose = FALSE) 
    
 #run HTO demux
    seurat<-NormalizeData(object = seurat, assay = "HTO", normalization.method = "CLR")
    Idents(seurat)<-"orig.ident"
    seurat<-HTODemux(seurat, assay = "HTO", positive.quantile=0.99999 )
```

and I get the following stdOut:
```
Cutoff for C0251-Hashtag-1 : 66 reads
Cutoff for C0252-Hashtag-2 : 164 reads
Cutoff for C0253-Hashtag-3 : 134 reads
Cutoff for C0254-Hashtag-4 : 42 reads
Cutoff for C0256-Hashtag-6 : 160 reads
Cutoff for C0257-Hashtag-7 : 139 reads
Warning message:
In `Idents<-.Seurat`(object = `*tmp*`, cells = doublets, value = "Doublet") :
  Cannot find cells provided
```

And when I go checking the HTO-related columns in the resulting seurat object, they are al NAs.  So it seems the warning is telling me something that does not work but I cannot understand what.
Potentially important point: in this dataset we have a mixture of hashtagged and non-hashtagged cells, which I was thinking to retrieve taking the HTO_classification.global Negative cells. I do not see how this may create a problem but just wanted to mention it. 
Any clue what is going on here? Never found this error anywhere.

**Comment by longmanz** [comment]
Hi,
positive.quantile=0.99999 seems to be too high. Have you tried positive.quantile=0.99 (the default)? Setting the positive.quantile too high you will end up with few/no cells being positively called as a singlet.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
