### ISSUE TITLE
RenameIdent can only rename one cluster

### ISSUE THREAD

**Issue by QiangShiPKU** [satijalab/seurat#771]
Hi,
I noticed that RenameIdent can only rename one cluster once. I think it should be able to rename multiple clusters such as following example. Could you update this in the new version?
```
C57Y_1 <- RenameIdent( object = C57Y_1,  
                       old.ident.name = c(0,1,2), 
                       new.ident.name = c("C1","C2", "C3")
                       )
```

**Comment by satijalab** [comment]
To change multiple IDs at once, you can follow the steps in the 3k tutorial, for example:

current.cluster.ids <- c(0, 1, 2, 3, 4, 5, 6, 7)
new.cluster.ids <- c("CD4 T cells", "CD14+ Monocytes", "B cells", "CD8 T cells", 
    "FCGR3A+ Monocytes", "NK cells", "Dendritic cells", "Megakaryocytes")
pbmc@ident <- plyr::mapvalues(x = pbmc@ident, from = current.cluster.ids, to = new.cluster.ids)
TSNEPlot(object = pbmc, do.label = TRUE, pt.size = 0.5)

**Comment by andrewwbutler** [comment]
Hi, 

This will be included as a feature in the next major Seurat release. Functionality has been added as of commit fedee7beda2b82835ca7fbe5960c09624b99e894 though it works slightly differently than your example. E.g.

```R
object <- RenameIdents(object = object,  '0' = 'C1', '1' = 'C2', '2' = 'C3')
```

**Comment by jonathanzhang53** [comment]
Had this issue and I just wrote a simple loop.

for (i in 1:30) {
	d = RenameIdent(d, old.ident.name = old[i], new.ident.name = new[i])
}

where old and new are character vectors with the idents

**Comment by QiangShiPKU** [comment]
@jonathanzhang53 great

**Comment by msadman-sakib** [comment]
> Had this issue and I just wrote a simple loop.
> 
> for (i in 1:30) {
> d = RenameIdent(d, old.ident.name = old[i], new.ident.name = new[i])
> }
> 
> where old and new are character vectors with the idents

This doesn't work, unfortunately. I tried it (with correct function call `RenameIdents`, but I get this error:
```
Error in RenameIdents.Seurat(seurat_integrated, old.ident.name = current.cluster.ids[i],  : 
  Can only rename identity classes to one value
```
I saw in [issue #2580](https://github.com/satijalab/seurat/issues/2580) as a replying saying that:
> `RenameIdents` is not designed to take variables as old identity names.

**Comment by msadman-sakib** [comment]
> Hi,
> I noticed that RenameIdent can only rename one cluster once. I think it should be able to rename multiple clusters such as following example. Could you update this in the new version?
> 
> ```
> C57Y_1 <- RenameIdent( object = C57Y_1,  
>                        old.ident.name = c(0,1,2), 
>                        new.ident.name = c("C1","C2", "C3")
>                        )
> ```

[The current 3K pbmc tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) has a fix for this problem now. For example:

```
new.cluster.ids <- c("Naive CD4 T", "CD14+ Mono", "Memory CD4 T", "B", "CD8 T", "FCGR3A+ Mono",
    "NK", "DC", "Platelet")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
DimPlot(pbmc, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```
