### ISSUE TITLE
 FindTransferAnchors: using a object analyzed with scanpy as reference

### ISSUE THREAD

**Issue by VilainLab** [satijalab/seurat#7712]
Hello,

I am trying to use a scanpy object as a reference, to annotate my query object which is processed in seurat. I downloaded the .h5ad object converted it into rds by **_sceasy_**, and used **sctrnasform** to normalize it, as my seurat object is . Then when I am trying to use _**FindTransferAnchors**_ I am getting the following error 
**Error in Loadings(object = reference[[reduction]])[features, dims] :
  no 'dimnames' attribute for array**
Am I missing something here? 
Please find below the code snippet for your perusal:
**Nasal_CZI.path <- file.path(inPath,  '20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.h5ad')
sceasy::convertFormat(Nasal_CZI.path, from="anndata", to="seurat", outFile='20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.rds')
YoshRef <- readRDS(file.path(outPath.Yosh, "20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.rds"))
YoshRef.SCTransform <- SCTransform(YoshRef,  vst.flavor = "v2", verbose = TRUE)
DefaultAssay(YoshRef.SCTransform) <- "SCT"
YoshRef.SCTransform<- UpdateSeuratObject(YoshRef.SCTransform)
YoshRef.SCTransform <- UpdateSCTAssays(YoshRef.SCTransform)
Baby.Adult.Inf.notInf.annotated<- UpdateSeuratObject(Baby.Adult.Inf.notInf.annotated)
Baby.Adult.Inf.notInf.annotated <- UpdateSCTAssays(Baby.Adult.Inf.notInf.annotated)
#YoshRef[['integrated']] <- as(object = YoshRef[['integrated']] , Class = "SCTAssay")
lung.anchors <- FindTransferAnchors(reference = YoshRef.SCTransform, query = Baby.Adult.Inf.notInf.annotated, dims = 1:30, reference.reduction = "pca", normalization.method = "SCT", recompute.residuals = FALSE, reference.assay= "SCT", query.assay= "SCT")**

Do you think I need to perform dimensional reduction on the scanpy transformed object?

Thanks again for the awesome tool and please let me know if u need anything else.

Thanks,
Surajit

**Comment by Gesmira** [comment]
Hi, 
Please reference the [mapping vignette](https://satijalab.org/seurat/articles/integration_mapping) for how to prepare a reference object to be used in transfer anchor finding. Does "pca" exist as a dimensional reduction in your object? As the reference.reduction parameter is required to be a reduction in your object, you should perform dimensional reduction which you can see in the vignette. Let me know if that helps!

**Comment by VilainLab** [comment]
Hello,

Thanks for the reply. Sorry for not providing the object information earlier. Both my reference (created using scanpy) and query (created using seurat), have both PCA and UMAP reductions. Please find below the object summary:
### Reference Created by Scanpy (and converted to seurat object by sceasy)
**YoshRef**
An object of class Seurat
32871 features across 32588 samples within 1 assay
Active assay: RNA (32871 features, 0 variable features)
 2 dimensional reductions calculated: pca, umap

### Reference Created by Seurat
**Baby.Adult.Inf.notInf.annotated**
An object of class Seurat
38887 features across 31085 samples within 3 assays
Active assay: SCT (15862 features, 0 variable features)
 2 other assays present: RNA, integrated
 2 dimensional reductions calculated: pca, umap

Please let me know your thoughts.

Surajit

**Comment by Gesmira** [comment]
Hi, 
So you are trying to use the reference created by scanpy to annotate the "reference created by Seurat"(as you call it)? I notice in FindTransferAnchors the object is called YoshRef.SCTransform, but the one you show does not have an SCT assay. Are you running SCTransform in Seurat after the pca and umap have already been computed on the reference in scanpy?

**Comment by VilainLab** [comment]
Sorry for the late response and thanks for the suggestion. I converted the data using sctransform, performed PCA , then UMAP. I worked after that. Please find below the code:
**Nasal_CZI.path <- file.path(path, "/20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.h5ad")
sceasy::convertFormat(Nasal_CZI.path, from="anndata", to="seurat", outFile=file.path(outpath, "20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.rds")
YoshRef <- readRDS(file.path(outPath.Yosh, "20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.rds"))
YoshRef.SCTransform <- SCTransform(YoshRef,  vst.flavor = "v2", verbose = TRUE)
YoshRef.SCTransform.PCA <- RunPCA(YoshRef.SCTransform, verbose = FALSE)
YoshRef.UMAP <- RunUMAP(YoshRef.SCTransform.PCA, dims = 1:30, reduction = "pca", return.model = TRUE)
Baby.Adult.Inf.notInf.annotated <- Baby.Adult.Inf.notInf.scale; YoshRef.annotated <- YoshRef.scale
DefaultAssay(YoshRef.UMAP) <- "SCT"
YoshRef.annotated<- UpdateSeuratObject(YoshRef.UMAP)
YoshRef.annotated <- UpdateSCTAssays(YoshRef.annotated)
DefaultAssay(Baby.Adult.Inf.notInf.annotated) <- "SCT"
Baby.Adult.Inf.notInf.annotated<- UpdateSeuratObject(Baby.Adult.Inf.notInf.annotated)
Baby.Adult.Inf.notInf.annotated <- UpdateSCTAssays(Baby.Adult.Inf.notInf.annotated)
#YoshRef[['integrated']] <- as(object = YoshRef[['integrated']] , Class = "SCTAssay")
lung.anchors <- FindTransferAnchors(reference = YoshRef.annotated, query = Baby.Adult.Inf.notInf.annotated, dims = 1:30, reference.reduction = "pca", normalization.method = "SCT", recompute.residuals = FALSE, reference.assay= "SCT", query.assay= "SCT")
YoshRef.PCA <- RunUMAP(YoshRef.annotated, dims = 1:30, reduction = "pca", return.model = TRUE)
lung_query <- MapQuery(anchorset = lung.anchors, reference = YoshRef.annotated, query = Baby.Adult.Inf.notInf.annotated,
    refdata = list(celltype = "Annotation"), reference.reduction = "pca", reduction.model = "umap")**
The converted object 
**YoshRef.UMAP
An object of class Seurat
61567 features across 32588 samples within 2 assays
Active assay: SCT (28696 features, 3000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap**
The annotation works, and I could identify almost all the cell types.
Do you think this work flow is good for annotating with objects created by scanpy?

Thanks,
Surajit

**Comment by Gesmira** [comment]
Hi, 
Sorry for the late response here, but glad to hear this is now working for you! I can't make final conclusions on your workflow as it pertains to scanpy, but from a quick glance this workflow looks correct to me!
