### ISSUE TITLE
failed for library(Seurat)

### ISSUE THREAD

**Issue by Teich2233** [satijalab/seurat#7715]
Hi, I try to library(Seurat), it show this mistake:

library(Seurat)
Error: package or namespace load failed for 'Seurat' in inDL(x, as.logical(local), as.logical(now), ...):
unable to load shared object ‘C:/Users/sunny/anaconda3/Lib/R/library/igraph/libs/x64/igraph.dll’：:
LoadLibrary failure:  could not find the specified program

Traceback:

1. library(Seurat)
2. tryCatch({
 .     attr(package, "LibPath") <- which.lib.loc
 .     ns <- loadNamespace(package, lib.loc)
 .     env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
 . }, error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste(" in", deparse(cc)[1L])
 .     else ""
 .     msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
 .         sQuote(package), P, conditionMessage(e))
 .     if (logical.return && !quietly) 
 .         message(paste("Error:", msg), domain = NA)
 .     else stop(msg, call. = FALSE, domain = NA)
 . })
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. value[[3L]](cond)
6. stop(msg, call. = FALSE, domain = NA)

I've tried everything here, and nothing has worked, such as 
1) https://github.com/rdotnet/rdotnet/issues/62,  2) https://github.com/satijalab/seurat/issues/5673

**Comment by Gesmira** [comment]
Hi, 
This [recent post](https://stackoverflow.com/questions/76551629/how-to-install-seurat-package-in-r-studio-on-a-remote-server) seems to be directly related to your igraph issue, have you tried the approach here?

**Comment by Teich2233** [comment]
@Gesmira Great, thank  you. Install the igraph work for me.

**Comment by Gesmira** [comment]
Great!
