### ISSUE TITLE
Grey dots for some genes in DotPlot

### ISSUE THREAD

**Issue by nsauerwald** [satijalab/seurat#7719]
When I plot marker genes using the DotPlot() function, certain genes show grey dots across all identities, even though there is no grey in the colormap being used. I've seen some similar issues where dots are grey when using an integrated assay (like #4274 and #1715) but the recommended solution on those is to ensure you are using the "RNA" assay, which I am already doing here. A small example:

`DefaultAssay(sc) <- "RNA"
genelist <- c("Apoe","Lipa","Lyz2","C1qa")

cellsubset <- subset(sc, idents= c("0", "1", "2", "3"))
DotPlot(object = cellsubset, features = genelist, col.min=0) +
                         theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
                         scale_colour_gradient2(low = "red", mid="black", high = "blue")
`
Which gives the graph below, where both Apoe and Lyz2 dots are completely grey. These genes show up clearly as markers for certain identities in a FeaturePlot, so I'm confused about this behavior in the DotPlot function. Thanks in advance for any advice and/or explanation!

![seurat_dotplot_markergenes_example](https://github.com/satijalab/seurat/assets/39094651/b54bccaa-70b8-4c4b-a8bf-52f4070346c5)

**Comment by alikhuseynov** [comment]
The color scale has to do with the range of (scaled) mean expression. By default Dotplot(scale = TRUE) scales data to z-scores. If you want only positive (non-scaled) expression use `scale = FALSE`.

I assume that values for `"Apoe"` and `"C1qa"` are below 0 in your plot, that's why they are grey? Try to set `col.min = -3` of something like that.
Or, try to save the plot and check the data:
```
test.plot <- 
  DotPlot(object = cellsubset, features = genelist, col.min=0) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_colour_gradient2(low = "red", mid="black", high = "blue")
test.plot$data %>% str
test.plot$data %>% pull(avg.exp.scaled) %>% range()
```
hope this helps.

**Comment by nsauerwald** [comment]
Thanks for the quick reply! Setting `col.min=-3` did not change the resulting figure, but your suggestion of checking the data range did help. In case anyone else has a similar issue and sees this, it looks like this comes from some NaNs in my data rather than negative values - checking the data range as you suggested gives this:

```
'data.frame':	16 obs. of  5 variables:
 $ avg.exp       : num  Inf 6.83e+06 Inf 3.19e+115 5.70e+176 ...
 $ pct.exp       : num  99 73 98.8 88.6 94 ...
 $ features.plot : Factor w/ 4 levels "Apoe","Lipa",..: 1 2 3 4 1 2 3 4 1 2 ...
 $ id            : Factor w/ 4 levels "0","1","2","3": 1 1 1 1 2 2 2 2 3 3 ...
 $ avg.exp.scaled: num  NaN -0.623 NaN 1.5 NaN ...
[1] NaN NaN
```

**Comment by alikhuseynov** [comment]
> Thanks for the quick reply! Setting `col.min=-3` did not change the resulting figure, but your suggestion of checking the data range did help. In case anyone else has a similar issue and sees this, it looks like this comes from some NaNs in my data rather than negative values - checking the data range as you suggested gives this:
> 
> ```
> 'data.frame':	16 obs. of  5 variables:
>  $ avg.exp       : num  Inf 6.83e+06 Inf 3.19e+115 5.70e+176 ...
>  $ pct.exp       : num  99 73 98.8 88.6 94 ...
>  $ features.plot : Factor w/ 4 levels "Apoe","Lipa",..: 1 2 3 4 1 2 3 4 1 2 ...
>  $ id            : Factor w/ 4 levels "0","1","2","3": 1 1 1 1 2 2 2 2 3 3 ...
>  $ avg.exp.scaled: num  NaN -0.623 NaN 1.5 NaN ...
> [1] NaN NaN
> ```

no worries. I'm not from the dev team. However, yeah, your input data seems to have issues. It might have something to do when you run subset. 
Does it work fine on the whole `sc` object, ie for all clusters?
Try to run it on the whole obj and set idents inside.
```
test.plot <- 
  DotPlot(object = cellsubset,  idents= c("0", "1", "2", "3"), features = genelist, col.min=0) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_colour_gradient2(low = "red", mid="black", high = "blue")
test.plot
```

**Comment by nsauerwald** [comment]
Sorry for the slow response on this - I got derailed with something else. Anyway it turns out the issue was that I was using the SCT assay (which has some Inf average expression and therefore NaNs in the scaled average expression), when I should have used the log-normalized RNA assay for this. Thanks for your help! Closing now

**Comment by ZhangRuifen** [comment]
> Hi @nsauerwald, could you please clarify what you mean? In your initial post, you explained that you were using the RNA assay (DefaultAssay(sc) <- "RNA"), and yet it turns out you were using the SCT assay? How did you determine this? I am having a similar problem with the gray dots in the dotPlot.

Hi! I have the same questions, when I use "RNA" or "SCT" to  draw the DotPlot, it seems that there is no significant difference in idents. However,when I used "integrated" to draw, it seems can seperate different ident.  
But, I'm not sure whether use "integrated" to draw DotPlot is correct? Does anyone have suggestions?

**Comment by alikhuseynov** [comment]
> > Hi @nsauerwald, could you please clarify what you mean? In your initial post, you explained that you were using the RNA assay (DefaultAssay(sc) <- "RNA"), and yet it turns out you were using the SCT assay? How did you determine this? I am having a similar problem with the gray dots in the dotPlot.
> 
> Hi! I have the same questions, when I use "RNA" or "SCT" to draw the DotPlot, it seems that there is no significant difference in idents. However,when I used "integrated" to draw, it seems can seperate different ident. But, I'm not sure whether use "integrated" to draw DotPlot is correct? Does anyone have suggestions?
> 
> ![image](https://private-user-images.githubusercontent.com/140964439/310436806-c1b15fc1-0af0-4c91-9704-ebbb48344322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjIxMzEsIm5iZiI6MTcwOTc2MTgzMSwicGF0aCI6Ii8xNDA5NjQ0MzkvMzEwNDM2ODA2LWMxYjE1ZmMxLTBhZjAtNGM5MS05NzA0LWViYmI0ODM0NDMyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQyMTUwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDZjNjc4MGZmMGNlMjgyYmNkMDQyZGQwMjcwMTc1NTU5Y2YwNmYwMzU0MWU3ZTQwNmU1OGJhMmM0ZDRmZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bO_dA4L1bknQuIXcUOo4pI3k8YpZOsgyVjbUtrhvaIg)

"integrated" assay (ie, batch corrected) is only used for clustering, PCA, UMAP etc..
Once you get clusters, there should be difference in gene expression between them on RNA or SCT assay. Else I would say something might have gone wrong during integration of your datasets

**Comment by ZhangRuifen** [comment]
> > > Hi @nsauerwald, could you please clarify what you mean? In your initial post, you explained that you were using the RNA assay (DefaultAssay(sc) <- "RNA"), and yet it turns out you were using the SCT assay? How did you determine this? I am having a similar problem with the gray dots in the dotPlot.
> > 
> > 
> > Hi! I have the same questions, when I use "RNA" or "SCT" to draw the DotPlot, it seems that there is no significant difference in idents. However,when I used "integrated" to draw, it seems can seperate different ident. But, I'm not sure whether use "integrated" to draw DotPlot is correct? Does anyone have suggestions?
> > ![image](https://private-user-images.githubusercontent.com/140964439/310436806-c1b15fc1-0af0-4c91-9704-ebbb48344322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjIxMzEsIm5iZiI6MTcwOTc2MTgzMSwicGF0aCI6Ii8xNDA5NjQ0MzkvMzEwNDM2ODA2LWMxYjE1ZmMxLTBhZjAtNGM5MS05NzA0LWViYmI0ODM0NDMyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQyMTUwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDZjNjc4MGZmMGNlMjgyYmNkMDQyZGQwMjcwMTc1NTU5Y2YwNmYwMzU0MWU3ZTQwNmU1OGJhMmM0ZDRmZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bO_dA4L1bknQuIXcUOo4pI3k8YpZOsgyVjbUtrhvaIg)
> 
> "integrated" assay (ie, batch corrected) is only used for clustering, PCA, UMAP etc.. Once you get clusters, there should be difference in gene expression between them on RNA or SCT assay. Else I would say something might have gone wrong during integration of your datasets

Thanks for your reply!  I'm not sure where is the problem, I just followed by the lesson here:https://github.com/hbctraining/scRNA-seq/blob/master/lessons/06_SC_SCT_and_integration.md.  And the clustree looks good that each cluster seperated form each other.
This is my code, I'm not sure whether there is any problem that will influence the result. Thank you very much! Sorry to bother you!


Idents(obj)
1.
Epithelial<-obj[,obj@meta.data$seurat_clusters %in% c(0,1,2,3,7)]
Epi.list <- SplitObject(Epithelial, split.by = "sample.id") 
for (i in 1:length(Epi.list)) {
  Epi.list[[i]] <- NormalizeData(Epi.list[[i]], verbose = TRUE)
  Epi.list[[i]] <- CellCycleScoring(Epi.list[[i]], s.features = s.genes, g2m.features = g2m.genes, assay = 'RNA', set.ident = TRUE)
  Epi.list[[i]] <- SCTransform(Epi.list[[i]], method = "glmGamPoi", assay = 'RNA', new.assay.name = 'SCT', vars.to.regress = c("nCount_RNA","nFeature_RNA","percent.mt","S.Score","G2M.Score"))
}
2.
integ_features <- SelectIntegrationFeatures(object.list = Epi.list,nfeatures = 3000)

Epi.list <- PrepSCTIntegration(object.list = Epi.list, 
                                   anchor.features = integ_features)

integ_anchors <- FindIntegrationAnchors(object.list = Epi.list, 
                                        normalization.method = "SCT", 
                                        anchor.features = integ_features)

Epi_integrated <- IntegrateData(anchorset = integ_anchors, 
                                   normalization.method = "SCT")

3.
# Run PCA
Epi_integrated <- RunPCA(object = Epi_integrated)
Epi_integrated <- FindNeighbors(object = Epi_integrated, reduction = 'pca',dims = 1:prin_comp)
Epi_integrated <- FindClusters(object = Epi_integrated,resolution = resolution.range)
T<-clustree(Epi_integrated) 
Epi_integrated <- RunUMAP(Epi_integrated, dims = 1:prin_comp, verbose = FALSE) 
p1<-DimPlot(Epi_integrated, reduction = "umap", group.by = "integrated_snn_res.0.1", label="T")

**Comment by GaryZhangYue** [comment]
I had a similar issue where some genes had dark grey colors across all the samples (the other genes worked). Looking at the data matrix associated with the dotplot, these genes had NA in columns average expression and scaled average expression, although the pct.expression had valid values. I was able to fix this by running **Joinlayers**.
