### ISSUE TITLE
"dimTitle" is not a graphical parameter

### ISSUE THREAD

**Issue by yewero** [satijalab/seurat#772]
I am using Seurat (v2.3.4). When I run this:
`PCHeatmap(object = expr, pc.use = 1:12, cells.use = 500, do.balanced = TRUE, label.columns = FALSE, use.full = FALSE)`
The wanrings will be shown:
```
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  "dimTitle" is not a graphical parameter
2: In doTryCatch(return(expr), name, parentenv, handler) :
  "dimTitle" is not a graphical parameter
3: In doTryCatch(return(expr), name, parentenv, handler) :
  "dimTitle" is not a graphical parameter
4: In doTryCatch(return(expr), name, parentenv, handler) :
  "dimTitle" is not a graphical parameter
5: In doTryCatch(return(expr), name, parentenv, handler) :
  "dimTitle" is not a graphical parameter
6: In doTryCatch(return(expr), name, parentenv, handler) :
  "dimTitle" is not a graphical parameter
```
How can I avoid these warnings?

**Comment by andrewwbutler** [comment]
Hi @yewero,

You can safely ignore these warnings. If you just don't want to see them, you can wrap the function call in `suppressWarnings()`. We've re-worked these kinds of heatmaps for the next Seurat version so in the future you shouldn't see these messages.

**Comment by yewero** [comment]
@andrewwbutler OK, I got it. Thanks.
