### ISSUE TITLE
Integrate data using multiple confounding factors

### ISSUE THREAD

**Issue by pkhoueiry** [satijalab/seurat#7723]
In a case where we have a mix of different runs (day1, day2, day3), conditions (e.g treated and not treated), and donors (donor 1, donor 2, donor 3), is there a way in Seurat V5 to integrate (remove batch effects) using all three confounding factors?

**Comment by longmanz** [comment]
Hi,
You can simply treat the 18 combinations of the 3 factors (3*2*3 = 18 combinations) equally and integrate them simultaneously. You may use the IntegrateLayers() to do it (https://satijalab.org/seurat/articles/seurat5_integration). 
Alternatively, "conditions" may cause more heterogeneity than "runs" or "donors". You may first integrate "runs + donors" of the "not-treated" group first, and then use the integrated "not-treated" as the reference data to map the rest samples onto it. An example of such strategy can be found [here](https://satijalab.org/seurat/articles/integration_mapping).
