### ISSUE TITLE
MapQuery function  Error in idx[i, ] <- res[[i]][[1]] : 

### ISSUE THREAD

**Issue by Kenneth-new-user** [satijalab/seurat#7727]
When transferring umap of very different data sets (FindTransferAnchors only found 250 anchors), running:

data.query <- MapQuery(anchorset = ref.anchors, reference = ref, query = data.query , reference.reduction = "pca", reduction.model = "umap")

give the following error:
Integrating dataset 2 with reference dataset
Finding integration vectors
Finding integration vector weights
Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length

I can run the function on other datasets with no problem.

**Comment by Gesmira** [comment]
I would recommend reducing the number of neighbors to use when weighing anchors (k.weight) significantly or adjusting parameters to [FindIntegrationAnchors](https://satijalab.org/seurat/reference/findintegrationanchors) (which can be provided as inputs to IntegrateLayers) to increase the number of anchors/cells which act as anchors. For example, you can turn off anchor filtering by setting k.filter = NA. Playing around with these parameters will affect the power of your integration, so we recommend checking the results of your integration to ensure the results are satisfactory.
