### ISSUE TITLE
Scale version of adding metadata to cellranger multi output 

### ISSUE THREAD

**Issue by mbartl13** [satijalab/seurat#7728]
Hi- I am attempting to repeat what worked previously on a smaller data set where I added in a column to re-assign cell IDs to a specific sample. I have several longitudinal samples which I ran using cellranger multi v07 and when loading into Seurat all samples are denoted as "-1". However, this dataset is considerably larger than the previous one. Any tips/suggestions for how to perform something similar to what I performed previously at scale? This would be useful to the community as it would allow for users to run cellranger multi with Seurat vs running 100+ cellranger count and then aggr. 
Thanks!

# Create table for how samples should be partitioned
```
example_meta_by_sample` <- tibble::tribble(
  ~orig.ident,  ~sample_
name,
1,	"	1001",
2,	"	1002 ",
3,	"	1003",
4,	"	1560")
```
# Change orig.ident column to factor so that it can be joined later
```
example_meta_by_sample$orig.ident <- as.factor(example_meta_by_sample$orig.ident)
metadata <- read_csv("metasmall.csv")
```
[metasmall_v02.xlsx](https://github.com/cran/Seurat/files/12453767/metasmall_v02.xlsx)

# Pull existing meta data where samples are specified by orig.ident and remove everything but orig.ident
```
OBJ_meta <- SeuratObject@meta.data %>% 
  select(orig.ident) %>% 
  rownames_to_column("barcodes")
```
# Use full join with object meta data in x position so that by sample meta dataframe is propagated across the by cell meta dataframe from the object and then remove orig.ident because it's already present in object meta data.
```
full_new_meta <- full_join(x = OBJ_meta, y = example_meta_by_sample) %>% 
  column_to_rownames("barcodes") %>% 
  select(-orig.ident)
```
# Add to object to graph by treatment groups
`SeuratObject <- AddMetaData(object = SeuratObject, metadata = full_new_meta)`

**Comment by mbartl13** [comment]
Thanks Sam will try!
________________________________

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
