### ISSUE TITLE
Convert h5ad file to seurat file

### ISSUE THREAD

**Issue by sanderslhc** [satijalab/seurat#7730]
HI, I'm trying to convert some h5ad files to seurat files. Here is my code:
"Convert("TS_Bone_Marrow.h5ad", dest="h5seurat", assay = "RNA", overwrite=F)". When I want to load the h5seurat file, there is something wrong happened like "Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 'arg' should be one of “counts”, “data”, “scale.data”".  How to solve this problem

**Comment by Gesmira** [comment]
Hi, 
We have stopped maintaining SeuratDisk. We recommend using packages like [sceasy](https://github.com/cellgeni/sceasy) to do this conversion. 

`sceasy::convertFormat(h5ad_file, from="anndata", to="seurat",
                       outFile='filename.rds')`

**Comment by mihem** [comment]
@Gesmira I think it would be great if you could put that in the readme of seuratdisk. Also the first google match https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html tells you to use that method.

I recently used it and it took me days till I figured out that the main problem was'n t the python package but the incomplete conversion. Worked flawless with sceasy

**Comment by sanderslhc** [comment]
Thanks you. I turn to using sceasy but there are still some problem. When I run the code "sceasy::convertFormat("Blood.h5ad", from="anndata", to="seurat",outFile='Blood.rds')", it will be stopped with "Error: ModuleNotFoundError: No module named 'pandas.core.index'". How can I fix it?

**Comment by Gesmira** [comment]
Hi, @mihem, we will think about the best way to share this! 
@sanderslhc It's possible your version of pandas is out of date. If the error persists, I recommend opening an issue on the sceasy github repo.
