### ISSUE TITLE
NormalizeData and FindVariableFeatures

### ISSUE THREAD

**Issue by shuoshuoliu** [satijalab/seurat#7733]
I am using the functions NormalizeData and FindVariableFeatures, but these functions do not change anything. The output is the same as the input. 

For example, the maximum value of pbmc3k is 419. After normalization, the maximum is still 419. The # of features of pbmc3k is 13714 and after selecting 2000 variables, dimension does not change.

```r
data("pbmc3k")
pbmc <- NormalizeData(pbmc3k)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
```

**Comment by shuoshuoliu** [comment]
Thanks very much Samuel! To my understanding, NormalizeData is to scale down large numbers, so after using the function, the maximum (largest) number should be lowered. Is this right? I am new to this function.

Thanks for sharing the function VariableFeatures. So, this means we should use VariableFeatures to find out which features selected and then subset the raw data, e.g., pbmc0[, VariableFeatures(pbmc)]?

**Comment by samuel-marsh** [comment]
Hi @shuoshuoliu ,

I got email that you had replied here but I don't see any message now.  Do you still have questions about this?

**Comment by samuel-marsh** [comment]
Happy to help!
