### ISSUE TITLE
A question about nuisance regression in single cell's analysis

### ISSUE THREAD

**Issue by caodudu** [satijalab/seurat#7737]
I'm a new hand at single cell's analysis. I notice that many tools (Seurat or Scanpy) or tutorials suggested users to implement nuisance regression to remove the effect of some covariables and update matrix with residuals. I'm just starting to learn linear regression so that I'm confused for the normal assumption of residuals. In my opinion, it is hard to argue that the residuals of normalized data atisfy the normality hypothesis . Data distribution should be multi-modal due to grouping and other factors. So why we can use nuisance regression in single cell's analysis?

**Comment by igrabski** [comment]
Thanks for your question. In linear regression, we specifically assume that the observed data, conditional on the covariates, follows a normal distribution; in other words, after accounting for the grouping structure in your model, the left-over residual should be normally distributed.
