### ISSUE TITLE
Read h5da files 

### ISSUE THREAD

**Issue by cartal** [satijalab/seurat#774]
Hi, 

I'm trying to read a couple of h5da files, but I can't seem to make it work. 
Do you guys have a workaround for this?

More specifically, my problem is this (See attachment):

![screen shot 2018-09-13 at 16 44 02](https://user-images.githubusercontent.com/3297906/45499451-5d0ca800-b774-11e8-8db1-06b2c35fd39b.png)

I have tried this on my Mac and a Linux machine running Ubuntu with R 3.5 (both).

Thanks

**Comment by cartal** [comment]
Anything on this?

**Comment by mrichter23** [comment]
Hi,
Is there any news on this? I have the same problem...

**Comment by satijalab** [comment]
Closing as we are working on AnnData conversion, and will update #1021 when we have a fix
