### ISSUE TITLE
Workflow after subsetting, reintegration?

### ISSUE THREAD

**Issue by Rhacki** [satijalab/seurat#7740]
Hello,
I was wondering what the best practice is after subsetting one celltype/cluster of a whole integrated dataset. After running subset(), which steps of the "basis" seurat workflow are necessary and which of them should be performed on the integrated and which on the RNA assay? Would it be necessary to run the integration again or to stick to the integrated assay from the whole dataset? 
I would appreciate every hint, thank you :)

**Comment by longmanz** [comment]
Hi,
It depends on what your downstream analyses are. If you plan to perform DE analysis, just stick to the "RNA" assay. And you do not need to re-integrate your subset. 
If you want better resolution of sub-clustering, you might consider re-doing the RunPCA and RunUMAP on your integrated assay after subsetting.
