### ISSUE TITLE
mitochondrial genes at top gene markers

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#7741]
Hi, dear Seurat team,
should mitochondrial genes be removed after filtering cell and before normalization in single nuclei RNA-seq data analysis?
The top 1～9 markers are mitochondrial genes in cell type one subcluster using FinaAllMarkers function. the cell proportions of subcluster/cell type cluster is over 10%, and there are four cell types has this problem. 

The background is clean according to CellRanger count report.

I follow the procedure: Cellranger-Cellbender-filtering cells(nCount, nFeature, mito_percent<5%)-remove doublet-Integrate(to remove batch effect)-clustering-annotate cell type-subset specific cell type-subclustering-FindAllMarkers for all subcluster. 
Even I set mito_percent < 1%, this phenomenon is still exist.
which is better, remove mitochondrial genes, or not remove?

Thank you!
Best

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Part of this comes down to personal preference and the specifics of a given analysis.  Personally, I never remove mito genes from the original matrix.  If they are top cluster markers it is probably worth digging into why that is.  Some things to think about:  Does the cluster show other potential signs of unhealthy cells?  Is the clustering resolution too high (or too low but less likely)?  Did you regress the percent mito during analysis?  Examine which PCs have high loading on mito genes?  Should number of PCs selected be different?  Or number of variable genes be different?  In the end there isn't a global "right" answer but will be dataset/analysis specific.

Hope that can be helpful.

Best,
Sam

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
