### ISSUE TITLE
Disable warning of rasterization after 100k points in DimPlot, FeaturePlot etc.

### ISSUE THREAD

**Issue by Peter-bbh** [satijalab/seurat#7745]
When number of points to plot exceeds 100,000, the plot is defaulted to rasterization and a warning is issued, "Rasterizing points since number of points exceeds 100,000. To disable this behavior set `raster=FALSE`".

First time it is great, but always is anoying. It can be removed by suppressWarnings(), see #6802, but it clutters the code.

An easy fix seems to be to change the preceeding condition in "visualization.R" (three places) from
"if ((nrow(x = data) > 1e5) & !isFALSE(raster)){" to "if ((nrow(x = data) > 1e5) & **is.null**(raster)){"

In this way, only if the raster option is not already specified, the warning will appear. So setting "raster = TRUE" will produce the same plot, but without the warning.

**Comment by samuel-marsh** [comment]
@Peter-bbh this is now to be implemented in Seurat v4.4 (release soon).  See #7842.

Best,
Sam
