### ISSUE TITLE
Valid to compare number of differentially expressed genes (DEGs)?

### ISSUE THREAD

**Issue by simonmfr** [satijalab/seurat#7746]
Hi, is it valid to compare multiple cell types by looking at the number of DEGs with q<0.05 between two conditions (KO vs WT)? Can this tell us which cell type shows the strongest effect of the condition?

For example, this was done in Allen et al, Cell, 2023, Fig. 4A (10.1016/j.cell.2022.12.010): 

<img width="209" alt="image" src="https://github.com/satijalab/seurat/assets/70199914/c72dd1e9-1e3c-477d-9b9c-45a47f76ef4f">

Aren’t cluster size or number of unique genes confounders in this analysis? Say cell type A with 5000 cells has much more DEGs than cells type B with only 200 cells. In #1340 you mention that you do not correct for cluster size.

Advice is much appreciated!

**Comment by longmanz** [comment]
Hi,
Yes, number of cells will definitely affect the number of DEGs being identified. To perform a fair comparison, I would suggest down-sample the large(r) cluster to make them have the same number of cases and controls as in the small(er) cluster. 
The sequencing depth might also be an issue, so it is also recommended to make sure the cells remained in the large(r) cluster to have similar UMI-count as those in the small(er) cluster.
