### ISSUE TITLE
Unable to convert singlecellexperiment file to seurat file due to delayed matrix in sce file

### ISSUE THREAD

**Issue by AShahzad9** [satijalab/seurat#7747]
Hi, 

I tried to use both the as.seurat and creatseuratobject functions to convert my singlecellexperiment file to a seurat object but I keep getting the same error. 

meninges_seurat <-as.Seurat(meninges_sce, counts = "counts", data = "logcounts", assay = NULL, project = "SingleCellExperiment")
Error in UseMethod(generic = "as.sparse", object = x) : 
  no applicable method for 'as.sparse' applied to an object of class "c('DelayedMatrix', 'DelayedArray', 'DelayedUnaryIsoOp', 'DelayedUnaryOp', 'DelayedOp', 'Array', 'RectangularData')"

I am not sure what is the best way to convert this delayed matrix into the appropriate form to allow for the conversion. Any help would be appreciated

Thanks

**Comment by zskylarli** [comment]
Hi, 
Please update your version of SCE and rerun makeSCE to create a compatible SCE object that can then be converted to a Seurat object. See this issue here https://github.com/limfuxing/ruvIIInb/issues/10.
