### ISSUE TITLE
clusters with very few cells

### ISSUE THREAD

**Issue by gianfilippo** [satijalab/seurat#7748]
Hi,

I have a dataset of 12 TILs samples, 6 pre and 6 post treatment. 

After clustering, I am ending up with 3 to 5 'spurious' clusters containing 2 to 5 cells each, independently of some parameters. 
I used : 
resolution range from 0.4 to 1.6. 
CCA or RPCA
3000 or 5000 features
30 or 50 PCs.

The cells in those clusters do not seem to have any unusual features (although I may have missed something here).
Anyway, I simply removed the clusters.

Still, since I never had this issue, I would like your opinion.

Thanks

**Comment by longmanz** [comment]
Hi, 
If you are sure that these cells are not low-quality cells (check nCount_RNA, nFeature_RNA, mito_percent, etc.), then they are probably real clusters, just with very low frequency (some rare cell types). 
You can also check if these cells are from the same individual or not. If they are from different individuals, they are more likely to be true clusters.

**Comment by gianfilippo** [comment]
Hi,
the cells mostly come from a single sample, so I do not think they are real clusters. 
I switched to Leiden clustering and I do not get these clusters any longer, at any resolution.
 Thanks
