### ISSUE TITLE
Guided clustering tutorial file is wrong

### ISSUE THREAD

**Issue by latacca** [satijalab/seurat#775]
Hello, I am going through the tutorials and the pollen et al 2014 object is missing. In its place is a zebra fin dataset. How can I go about getting the Pollen data to reproduce the clustering analyses?

Best,

Luisa

**Comment by satijalab** [comment]
You can download the file here : https://www.dropbox.com/s/wf0y82avlub2vmw/HiSeq301-RSEM-linear%20values.txt?dl=0
