### ISSUE TITLE
questions about intergrated analysis in Seurat v5

### ISSUE THREAD

**Issue by Ithinky** [satijalab/seurat#7754]
Hi,
Thanks for your great tools!

I know that integrated data is stored in dimensional reduction in Seurat v5, such as obj$integrated.cca. However, there is no integrated raw data as integrated assay in Seurat v4. So, after I using JoinLayers( ), I still use unintegrated data to do following analysis, such as FindMarkers( ) or CellCycleScoring( ). Therefore, I think the results will be influenced by batch effect. Could you give me some help, thank you!

Best,
Ithinky

**Comment by zskylarli** [comment]
Hi,
See more discussion on this topic here:[https://github.com/satijalab/seurat/issues/5881] and [https://github.com/satijalab/seurat/issues/1717]. If you need to return a batch-corrected matrix, you can try other methods (not supported directly by Seurat) such as Scanorama.
