### ISSUE TITLE
 Convert  Seurat v5 objects back to previous object structure

### ISSUE THREAD

**Issue by sabrina0701** [satijalab/seurat#7757]
Hi teams,

I have tried to convert Seurat v5 objects into h5ad format, but it failed for the object structure, and seurat-disk also failed to SaveH5Seurat since the layers, so would it be possible that add a function to convert Seurat v5 objects back to v4 object structure, or the seurat-disk would SaveH5Seurat for the Seurat v5 objects.

Thanks.
Sabrina

**Comment by Gesmira** [comment]
Hi @sabrina0701, 
This is detailed in the [Seurat v5 Command Cheat Sheet](https://satijalab.org/seurat/articles/seurat5_essential_commands.html)

```
# convert a v5 assay to a v3 assay
pbmc3k[["RNA3"]] <- as(object = pbmc3k[["RNA"]], Class = "Assay")

# convert a v3 assay to a v5 assay
pbmc3k[["RNA5"]] <- as(object = pbmc3k[["RNA3"]], Class = "Assay5")
```

**Comment by sabrina0701** [comment]
Hi gesmira,

Thanks for the reply, however I know how to convert a v5 assay to a v3
assay, the problem is here, after conversion, the v3 assay still use
layers instead of slots, which will results in the failure to
SaveH5Seurat, so it still don't really compatible with the old
version.

Many thanks!

Best wishes,
Sabrina


gesmira ***@***.***> 于2023年9月4日周一 15:16写道：

**Comment by Gesmira** [comment]
Hi, 
Although when you print a v3 assay in the console it shows "layers", it doesn't actually use the layer infrastructure. 
What is the error you are getting with SaveH5Seurat? We have stopped actively maintaining SeuratDisk so this may be related to that. If you are trying to create an AnnData object, I recommend using [sceasy](https://github.com/cellgeni/sceasy) for the conversion. Let me know if that is helpful!

**Comment by sabrina0701** [comment]
It was solved. Thanks!

gesmira ***@***.***> 于2023年9月4日周一 15:31写道：
