### ISSUE TITLE
SCTransform after doublets removed(use DoubletFinder)

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#7758]
Hi, Dear Seurat team
I have two datasets, each has 6 samples. I filtered cells of each sample (set threshold of nCount nFeature Mito-percent) and used standard workflow (NormalizeData-FindVariableFeatures-ScaleData-RunPCA-RunUMAP), then removed doublets use DoubletFinder. 

I want to integrate the two datasets, and I read this (https://satijalab.org/seurat/archive/v3.0/integration.html).

It suggests using SCTransform if integrating multiple datasets. If I use the SCTransform, it will re-normalize data since data has been normalized in standard workflow. Is it correct if I use SCTransform in this case?

Or should I integrate each dataset for 6 samples and then integrate the two datasets?

Thank you.
Best,
Xiaoyan

**Comment by saketkc** [comment]
Hi @yulchen810,

You can use either approach for integration. Please see [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette) for an example in SCTransform and [this vignette](https://satijalab.org/seurat/articles/integration_introduction) for standard log normalization approach.

**Comment by yulchen810** [comment]
> Hi @yulchen810,
> 
> You can use either approach for integration. Please see [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette) for an example in SCTransform and [this vignette](https://satijalab.org/seurat/articles/integration_introduction) for standard log normalization approach.
Thank you


> Hi @yulchen810,
> 
> You can use either approach for integration. Please see [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette) for an example in SCTransform and [this vignette](https://satijalab.org/seurat/articles/integration_introduction) for standard log normalization approach.

Ok, Thank you.

**Comment by shaniAmare** [comment]
Hi @saketkc 

I was looking for a similar but a little different solution for my data. I hope it is OK to piggy back on an open query, but please let me know if I have to open a new issue for this.

I have data that I collected from a few public datasets. I have successfully run multiple integration rounds on them. But after looking at the integrated data, I think it can be a little more cleaned up (e.g. seeing cell groups with low nFeature and/or nCount levels, "cell bridges" connecting larger clusters, etc.). So my questions are;
1. to further clean them up do I need to go back to the original individual data sets?
2. or else can I subset the data set + do duplicate removal while having the the `integrated` assay as the active one?

Many thanks for your time,
Shani.

**Comment by saketkc** [comment]
Hi @shaniAmare ,

It is fine to remove the cells post integration if they are doublets/empty cells. `subset(object.integrated, idents = "buggylcuster", invert=T)` for example would remove your `buggycluster`. If you have any follow up questions please open a a new issue.
