### ISSUE TITLE
P_val_Adj in FindMarkers is differentthan the manually calculated on 

### ISSUE THREAD

**Issue by JoBeh** [satijalab/seurat#7759]
Dear Seurat team,

I am trying to find the DEGs between a marker gene-positive cells vs a marker gene-negative cells within a specific cluster. So what I did was the following:

I used SCTransform then followed the regular pre-processing steps. After I clustered my cells I subsetted the cluster of interest like this:

`MG_so <- subset(so_clustered, 
                idents = 0
                )`

Then I performed the analysis between positive and negative cells like this:

`Idents(MG_so) <- MG_so@meta.data$mTd
DEG_0 <- FindMarkers(MG_so,
                                      ident.1 = "Positive", ident.2 = "Negative"
                                      )`

Now my problem is, when I look at the DEG_0 results, I realized that the P_val_Adj results are not the same as what I would get if I would manually get using the equation, So, here is what I get from the FindMarkers analysis.

`view(DEG_0)`

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yoyo_/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yoyo_/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<div style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

  | p_val | avg_log2FC | pct.1 | pct.2 | p_val_adj
-- | -- | -- | -- | -- | --
  |   |   |   |   |  
mTd | 0.00E+00 | 1.0524674 | 0.974 | 0 | 0
Ccl3 | 7.25E-06 | 0.5089369 | 0.735 | 0.622 | 0.1348857
Mcl1 | 1.07E-05 | 0.2668265 | 0.757 | 0.632 | 0.1990445
Ctsb | 1.36E-05 | 0.2653206 | 0.995 | 0.987 | 0.2533275
Dusp1 | 8.62E-05 | 0.3974667 | 0.794 | 0.686 | 1
Ptn | 4.95E-04 | -0.3238517 | 0.201 | 0.311 | 1
Cstb | 6.10E-04 | 0.2533783 | 0.439 | 0.323 | 1
Nfkbia | 8.60E-04 | 0.3191193 | 0.921 | 0.856 | 1
Rgs1 | 1.91E-03 | 0.3477973 | 0.677 | 0.572 | 1
Dbi | 2.09E-03 | -0.3325476 | 0.413 | 0.49 | 1
Mt3 | 2.73E-03 | -0.2803545 | 0.392 | 0.477 | 1
Gdf15 | 2.75E-03 | 0.3614295 | 0.138 | 0.076 | 1
Ier3 | 3.46E-03 | 0.3842371 | 0.587 | 0.49 | 1
Aldoc | 3.92E-03 | -0.3151071 | 0.46 | 0.536 | 1
Ccl4 | 3.93E-03 | 0.4535613 | 0.799 | 0.784 | 1
Mbp | 4.80E-03 | -0.3378054 | 0.794 | 0.836 | 1
Gem | 5.05E-03 | 0.275135 | 0.407 | 0.323 | 1
Cd83 | 7.18E-03 | 0.3351807 | 0.757 | 0.671 | 1
Atf3 | 8.16E-03 | 0.289084 | 0.725 | 0.638 | 1
Hbb-bs | 9.29E-03 | -0.3224734 | 0.593 | 0.65 | 1
Apod | 1.34E-02 | -0.254032 | 0.243 | 0.324 | 1
Gm13889 | 1.18E-01 | 0.2715118 | 0.185 | 0.143 | 1
Ccl2 | 1.52E-01 | 0.3043008 | 0.354 | 0.296 | 1
Ttr | 4.42E-01 | -0.3633912 | 0.095 | 0.114 | 1
Adamts1 | 5.15E-01 | -0.2524058 | 0.169 | 0.183 | 1
Hspb1 | 8.32E-01 | 0.4457698 | 0.159 | 0.172 | 1

</body>

</html>

The problem here is the P_va_Adj shows that non of the genes expression is significant. 

But when calculating the same P_vals manually using The Bonferroni test with and an alpha of 0.05 I get the following results

0.0000000
0.0001885
 0.0002782
 0.0003536
 0.0022412
 0.0128700
 0.0158600
 0.0223600
 0.0496600
 0.0543400
 0.0709800
 0.0715000
 0.0899600
 0.1019200
 0.1021800
 0.1248000
 0.1313000
 0.1866800
 0.2121600
 0.2415400
0.3484000
 1.0000000
 1.0000000 
1.0000000 
1.0000000 
1.0000000

Can someone help me address the problem and solve it please?

Thanks in advance,
JB

**Comment by saketkc** [comment]
Hi @JoBeh, thanks for the question. `p_val_adj` is based on `p.adjust(method="bonferroni", n=nrow(object))` which uses all the genes for the denominator.

**Comment by mluciarr** [comment]
I’m experiencing the same issue. I ran the analysis using all genes (min.pct = 0 and  logfc.threshold = 0), but I still get different adjusted p-values (p_val_adj) between the two analyses. I actually obtained more significant genes and DARs when doing it manually than with the FindMarkers function. How is this possible?
