### ISSUE TITLE
Combining Two 10X Runs

### ISSUE THREAD

**Issue by DHGK** [satijalab/seurat#776]
When I tried to combine two datasets, it gave me this error:

Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

I'm wondering what's the issue here and how to solve. Thanks!

DHGK

**Comment by andrewwbutler** [comment]
Hi,

Could you provide the code you're using to try to combine the datasets?

**Comment by DHGK** [comment]
library(Seurat)
library(dplyr)
hESC.1.data <- Read10X(data.dir = "")
hESC.2.data <- Read10X(data.dir = "")
hESC.1 <- CreateSeuratObject(raw.data = hESC.1.data, min.cells = 3, min.genes = 200, project = "hESC1")
hESC.2 <- CreateSeuratObject(raw.data = hESC.2.data, min.cells = 3, min.genes = 200, project = "hESC2")
hESC.combined <- MergeSeurat(object1 = hESC.1, object2 = hESC.2, add.cell.id1 = "I", 
    add.cell.id2 = "II", project = "hESC")
head(x = hESC.combined@cell.names)
table(hESC.combined@meta.data$orig.ident)

**Comment by DHGK** [comment]
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : invalid character indexing
17.
stop("invalid character indexing")
16.
intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE)
15.
subCsp_cols(x, j, drop = drop)
14.
as(x, "CsparseMatrix")[, j, drop = drop]
13.
as(x, "CsparseMatrix")[, j, drop = drop]
12.
is(x, "sparseMatrix")
11.
.as.Tsp(as(x, "CsparseMatrix")[, j, drop = drop], noCheck = !drop)
10.
x[, j = j, drop = TRUE]
9.
x[, j = j, drop = TRUE]
8.
eval(call, parent.frame())
7.
eval(call, parent.frame())
6.
callGeneric(x, , j = j, drop = TRUE)
5.
object1@raw.data[, object1@cell.names]
4.
object1@raw.data[, object1@cell.names]
3.
inherits(x = mat1, what = "data.frame")
2.
RowMergeSparseMatrices(mat1 = object1@raw.data[, object1@cell.names], mat2 = object2@raw.data[, object2@cell.names])
1.
MergeSeurat(object1 = hESC.1, object2 = hESC.2, add.cell.id1 = "I", add.cell.id2 = "II", project = "hESC")

**Comment by andrewwbutler** [comment]
Hmm, can you check that `hESC.1.data` and `hESC.2.data` are read in properly (i.e. have the expected gene and cell names)? Also, make sure the `Matrix` package is loaded (though it should be by default when you load `Seurat`). If that doesn't fix it, I would recommend either:

1. providing a link to download the object (or subset that reproduces the error)
2. merging the two matrices (`hESC.1.data` and `hESC.1.data`) yourself and feeding that into `CreateSeuratObject`.

**Comment by DHGK** [comment]
Thanks, the problem has been solved by merging the two matrices myself and then feeding it to Seurat.
