### ISSUE TITLE
Removing/Adjusting the title from a split FeaturePlot

### ISSUE THREAD

**Issue by mmandanas** [satijalab/seurat#7761]
Hi! I have created a multi-panel FeaturePlot using a single feature (i.e. a gene like "MS4A1") split across multiple conditions, but wanted to remove the title containing the name of the feature (i.e. "MS4A1") from the output image. How would I go about this?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You can modify output plots as you would any ggplot2/patchwork plot.

```
FeaturePlot(...) & theme(plot.title = element_blank())
```

Best,
Sam
