### ISSUE TITLE
how to remove doublet 

### ISSUE THREAD

**Issue by LiuYing732** [satijalab/seurat#7768]
Hi, how to remove the doublet via R. I already found the doublet through the DoubletFinder package.

**Comment by alikhuseynov** [comment]
just `subset` your Seurat object given cell ids that are not doublets or using `idents`.
Say,  DoubletFinder results are stored in `obj$db.finder.out` with 2 types `"doublet"` and `"singlet"`
then:
```
Idents(obj) <- "db.finder.out"
obj %<>% subset(idents = c("singlet"))
```

**Comment by LiuYing732** [comment]
Great, thank you very much.

Best.
Liu Ying
________________________________
发件人: alikhuseynov ***@***.***>
发送时间: 2023年9月10日 19:57
收件人: satijalab/seurat ***@***.***>
抄送: ***@***.*** ***@***.***>; Author ***@***.***>
主题: Re: [satijalab/seurat] how to remove doublet (Issue #7768)


just subset your Seurat object given cell ids that are not doublets or using idents.
Say, DoubletFinder results are stored in obj$db.finder.out with 2 types "doublet" and "singlet"
then:

Idents(obj) <- "db.finder.out"
obj %<>% subset(idents = c("singlet"))


―
