### ISSUE TITLE
Weighted Nearest Neighbor Analysis - Input Data Format

### ISSUE THREAD

**Issue by shamer3** [satijalab/seurat#7769]
I am trying to analyse some scATAC + Gene expression data, and I have been directed to the Weighted Nearest Neighbor Analysis tutorial. However I am not quite sure what the input format of the data needs to be for this analysis. The data has been preprocessed using cell ranger-arc mkfastq and cell ranger-arc count so I have the standard outputs from that.

I was trying to create a Seurat object from the barcodes.tsv, features.tsv, matrix.mtx but it didn't seem to work.

Would really appreciate some help.

**Comment by rsatija** [comment]
10x CellRanger outputs the multimodal data as a h5 file, which can be read in using Seurat. You can see an example here:
https://stuartlab.org/signac/articles/pbmc_multiomic
