### ISSUE TITLE
How to filter on unique molecular identifiers in scRNA seq using Seurat

### ISSUE THREAD

**Issue by das2000sidd** [satijalab/seurat#7770]
Probably a really basic question but I see papers mention things like "cells were subsequently filtered to include only high quality cells (as defined by >500 detectable genes, >1500 unique molecular identifiers, and <15% of transcripts coming from mitochondrial genes)."

I know the detectable genes and mitochondrial filter but how do you apply the molecular identifier filter in Seurat?

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

As long as the data is from a technology that has UMIs then the `nCount_RNA` within the Seurat object is what you are looking for.

Best,
Sam
