### ISSUE TITLE
Error merging three seurat object! 

### ISSUE THREAD

**Issue by synatkeamsk** [satijalab/seurat#7774]
Dear Teacher, 
I got error when merging three seurat object: Not sure how to fix!
My code here! 

**MergedNML <- merge(NML_I, y = c(NML_II, NML_III),
                   add.cell.ids = ls()[1:3],
                   project = 'MergedNML')**

**Warning: The following arguments are not used: project
Error in fixupDN.if.valid(value, x@Dim) : 
  length of Dimnames[[2]] (1) is not equal to Dim[2] (3669)**

Hope you can help.. 

Kind Regards,

Synat,

**Comment by koefoeden** [comment]
Could maybe be related to your other issue - if your seurat objects are not in fact seurat objects?

**Comment by longmanz** [comment]
Thank you @koefoeden! Yes please make sure your objects are actually Seurat objects.
