### ISSUE TITLE
No slot of name "meta.data" for the object class "Assay"

### ISSUE THREAD

**Issue by synatkeamsk** [satijalab/seurat#7775]
Dear Sir/Madam, 

I have created three Seurat object and I was viewing metadata, but I could not find it.

NML_I<- CreateAssayObject(counts= NML_I, project= "NML_I", min.cells = 3, min.features = 200)
NML_II<- CreateAssayObject(counts= NML_II, project= "NML_II", min.cells = 3, min.features = 200)
NML_III<- CreateAssayObject(counts= NML_III, project= "NML_III", min.cells = 3, min.features = 200)
                #some explanation is min.cell means at least three cells that express the gene
                #we keep at least 200 genes that expressed the mRNA !

#View seurat object! 
view(NML_I@meta.data)

Error in is.data.frame(x) : 
  no slot of name "meta.data" for this object of class "Assay"

I watched video tutorial of someone and they could view it. Not sure why I could get metadata and how to get it.

Kind Regards,

Synat

**Comment by koefoeden** [comment]
It looks like you **haven't** in fact created three SeuratObjects (which should have the meta.data slot) as you meant to, but instead created three Assay objects, which rightly doesn't have the meta.data slot. 

Did you mean to use the CreateSeuratObject function?

**Comment by synatkeamsk** [comment]
Thanks you professor for my spotting my silly mistake. I really appreciated that you spotted that. I solved my issue. Regards,
