### ISSUE TITLE
Finding markers with scATAC-seq

### ISSUE THREAD

**Issue by mistrm82** [satijalab/seurat#7776]
Hello,

I am analyzing multiome data (ATAC+RNA) and am wondering about the workflow. I have completed analysis through to WNN analysis to integrate the two modalities.

I have identified marker genes from the RNA for each cluster and I thought a next logical step would be to  similarly identify differentially accessible regions for each cluster. I was able to successfully run both FindAllMarkers and FindConservedMarkers using the code below, but I wanted to know -- is this a feasible approach?

```
## Find top markers (peaks)

print("Finding top markers in ATAC assay")
Idents(seurat_slm) <- "seurat_clusters"
DefaultAssay(seurat_slm) <- "ATAC"

markers <- FindAllMarkers(object = seurat_slm, 
                          only.pos = TRUE,
                          logfc.threshold = 0.1,
                          min.pct = 0.02,
                          test.use = 'LR',
                          latent.vars = 'atac_peak_region_fragments')

write.csv(markers, row.names = FALSE, 
          file = paste0(res_dir, "/FindAllMarkers_WNN_allsamples_res0-2_ATAC_logistic-reg.csv"))

# Find conserved markers for peaks
# Create function to get conserved markers for any given cluster
get_conserved <- function(cluster){
  FindConservedMarkers(seurat_slm,
                       ident.1 = cluster,
                       grouping.var = "age",
                       only.pos = TRUE,
                       logfc.threshold = 0.1,
                       min.pct = 0.02,
                       test.use = 'LR',
                       latent.vars = 'atac_peak_region_fragments') %>% 
    cbind(cluster_id = cluster, .)
}

conserved_markers <- map_dfr(c(0:14), get_conserved)

write.csv(conserved_markers %>%  rownames_to_column(var="gene"), row.names = FALSE, quote = FALSE,
          file = paste0(res_dir, "/FindConservedMarkers_WNN_allsamples_res0-2_ATAC_logistic-reg.csv"))

```

The **result of FindAllMarkers is rows of regions (genomic coordinates)** each listed with similar stats we get from RNA. The **results from FindConservedMarkers is rows listed by gene identifiers and the genomic coordinate information is lost**. My thought is to use the FindAllMarkers results and use Signac `ClosestFeature()`.

An alternative approach might be to re-call peaks for each cluster separately and then use those peaks to identify nearest gene. I have worked with plenty of bulk ATAC-seq but this is my first with scATAC-seq.

Any help would be much appreciated!!

Best,
Meeta

**Comment by saketkc** [comment]
Hi @mistrm82, your approach looks correct. You can also recall peaks for each cluster and use the same approach as well.

**Comment by mistrm82** [comment]
Hi @saketkc my issue was the difference in  result produced by FindAllMarkers  and FindConservedMarkers. In the latter I lose any genomic coordinate information and therefore have no way to map back to my original data. 

Should FindConservedMarkers be used with scATAC?

**Comment by saketkc** [comment]
Can you post the output of your `FindConservedMarkers()` and `FindAllMarkers`, and also,

```
> object@assays$RNA@counts[1:5,1:5]
> object@assays$atac@counts[1:5,1:5]

```

**Comment by mistrm82** [comment]
Hi @saketkc 

Below are screenshots to demonstrate the differences between the outputs. T

<img width="773" alt="Screenshot 2023-10-05 at 4 24 29 PM" src="https://github.com/satijalab/seurat/assets/6545708/d575a941-173d-41f0-b93e-0fa9e3102859">
<img width="857" alt="Screenshot 2023-10-05 at 4 25 00 PM" src="https://github.com/satijalab/seurat/assets/6545708/7e7f287a-3e6f-4a24-ac6b-55b32e6b2e90">

**Comment by mhkowalski** [comment]
Hi, 

Sorry for your delayed response. If you or anyone else has this issue, you should add ```assay="ATAC"``` to the ```FindConservedMarkers()``` call.  This runs on the ```RNA``` assay by default.
