### ISSUE TITLE
Error in GeneActivity(pbmc,features = VariableFeatures(pbmc.rna)):No fragmenrt information found for requested assay

### ISSUE THREAD

**Issue by Syayaq** [satijalab/seurat#7779]
Hi, I downloaded the following scATAC-seq data from GEO:
[barcodes.tsv.gz](https://github.com/satijalab/seurat/files/12569426/barcodes.tsv.gz)
[matrix.mtx.gz](https://github.com/satijalab/seurat/files/12569427/matrix.mtx.gz)
[peaks.bed.gz](https://github.com/satijalab/seurat/files/12569428/peaks.bed.gz)

The data does not provide a fragment file to download, my question is whether I can create a fragment file for subsequent single cell analysis from just these three files that are already there

**Comment by rsatija** [comment]
Unfortunately you will need to contact the authors. There is no way to reconstruct the fragment files from just the peak/cell barcode matrix that is provided on GEO. You will need either the original FASTQ files or a BAM file
