### ISSUE TITLE
Filtering cells by UMI distribution

### ISSUE THREAD

**Issue by robertamezquita** [satijalab/seurat#778]
Would it be helpful to contribute a function that subsets a seurat object based on the distribution of the UMI counts/rank? 

I'm working with some data from 10X that includes a lot of low quality cells, and was thinking writing a function that takes a seurat object, calculates the inflection points (knee) for each sample group by `orig.ident` (or some other grouping variable), and returns a subsetted object based on cells that pass the threshold (simultaneously adding info to the object about the calculated thresholds and a plot with the inflection points shown as well).

If this would be useful, I have the function I wrote and happy to share it, but can also structure it as a formal pull request, but first want to see if this would even be something of interest/within the scope of Seurat 3.0. 

Example plot below with calculated inflection points to cutoff low quality cells for each sample:

![screen shot 2018-09-14 at 4 41 03 pm](https://user-images.githubusercontent.com/2438701/45589564-a7a93400-b8dc-11e8-9613-654835c8b1b6.png)

**Comment by satijalab** [comment]
Sounds great! Yes you are welcome to submit a PR - thanks!

**Comment by 2236529177** [comment]
> Would it be helpful to contribute a function that subsets a seurat object based on the distribution of the UMI counts/rank?
> 
> I'm working with some data from 10X that includes a lot of low quality cells, and was thinking writing a function that takes a seurat object, calculates the inflection points (knee) for each sample group by `orig.ident` (or some other grouping variable), and returns a subsetted object based on cells that pass the threshold (simultaneously adding info to the object about the calculated thresholds and a plot with the inflection points shown as well).
> 
> If this would be useful, I have the function I wrote and happy to share it, but can also structure it as a formal pull request, but first want to see if this would even be something of interest/within the scope of Seurat 3.0.
> 
> Example plot below with calculated inflection points to cutoff low quality cells for each sample:
> 
> ![screen shot 2018-09-14 at 4 41 03 pm](https://user-images.githubusercontent.com/2438701/45589564-a7a93400-b8dc-11e8-9613-654835c8b1b6.png)

Dear robertamezquita,
your job is really and truly wonderful. I want to consult you a question, how do you distinct low quality and rare cell types, thanks a lot.

**Comment by robertamezquita** [comment]
@2236529177 I think that's a great question. First though, we have to make a distinction between low quality and rare cells, which are not synonymous. Rare cell populations may have abundant mRNA, but simply have very little representation in the dataset (hence, rare). Low quality be a function of various things - here, this function attempts to address failed reactions/poor or deficient loadings based on having less barcodes/UMIs what we would normally expect based on the dataset distribution. 

Where the rare cell and technical effect aspects may be conflated is where rare cells might have less mRNA abundance to read out (although this can happen to any cell type). Indeed, there may be rare cells we are missing in the regime that may by default be removed based on such standard routines, so its important to inspect your data to see if there is some signal in the noise and subsequently adjust your criteria for removing "bad" cells accordingly.
