### ISSUE TITLE
FindMarkers Error

### ISSUE THREAD

**Issue by Rahul1711arora** [satijalab/seurat#7781]
Hi,

I wanted to ask a question about analysis and not sure if that's a bug or a problem at my end.
I have a Seurat object which I created after running integration on different Seurat objects. All the cells in the integrated Seurat object are of the same cell type, i.e., inhibitory neurones but differ wrt age groups, i.e., either group_1, group_2, group_3, or group_5.

I wanted to perform differential expression between all the groups, so I changed the identities of those cells using the age group information from the metadata column.
It use to run fine before but since I have updated to R version 4.2.2, I am getting a strange error. Unfortunately, I cannot get back to the previous version as this is a part of a meta-analysis script that stops working on previous version due to addition of multiple packages required for downstream analysis.

For the current analysis, so far, it runs the comparisons for group_1 versus all. But the moment it switches to group_2 versus group_3, it gives the following error:

`Error in levels <- (*tmp*, value = as.character(levels)): factor level [13] is duplicated`

Upon running the comparisons outside the master script, and explicitly defining the comparison groups, the analysis runs well for group_2 vs group_3, group_2 vs group_5, and group_3 vs group_5. Unfortunately, I cannot run this manually as I need to run all of this in an automated way on a cluster.

I also checked that the Cell Ids in this Seurat object are not duplicated. But of course, the Idents will be same, as I mentioned earlier that they refer to a metadata column in the object.
Interestingly, I have another Seurat object with the same specifications and all the comparison runs perfectly fine for that.

Since all of this is automated, I'm not sure if I can attach the code here, but for the object, I can't attach it here because it's quite big despite being zipped. Could you suggest how can I share that?

**Comment by igrabski** [comment]
Hi Rahul, first, as a general note, if you want to find all markers between every pair of groups, you can use the function `FindAllMarkers`, which will let you avoid calling `FindMarkers` individually for every pair. 

For your specific problem here, can you share the part of your code where you are running your comparisons, including the one that seems to work (group_1 versus all) and then where it fails (group_2 versus group_3)?

**Comment by Rahul1711arora** [comment]
Hi, 

Thanks for your reply. I am running these individual comparisons to use the output in different downstream analysis and so it has to run that way. 

Please find the code attached
[Diff_exp_func_enrich.R.zip](https://github.com/satijalab/seurat/files/12642476/Diff_exp_func_enrich.R.zip)

The important thing is that if I run the comparison between any group apart from `group_1` versus any, I get the error message for level duplication using this script. But if I run the comparison individually, by using commands directly, such as

`markers <- FindMarkers(de_analysis, test.use = "negbinom", ident.1 = "group_2", ident.2 = "group_3", assay = "SCT")  `

It runs perfectly fine. And interestingly, this happens for a specific seurat object and not others.

But since this is a meta-analysis code, I can't do these comparisons manually and locally. I hope this code helps to identify the problem. If you need the seurat object, kindly let me know where can I share that as it's a bigger one so can't be attached here. 

Best,
Rahul

**Comment by igrabski** [comment]
Hi Rahul, if running the command directly as you described works, then I recommend you check that these lines are doing as you intended:

```
ident.1 = check_for_levels[index_value_1]
ident.2 = check_for_levels[index_value_2]
```

The only difference between running the command directly and what you have in your function seems to be when you pass in those values, so I would make sure that `ident.1` and `ident.2` are actually equal to the group names. You should also make sure that they are characters, e.g. you can try passing in `as.character(ident.1)` and `as.character(ident.2)`. 

If that doesn't resolve your problem, please feel free to email me your Seurat object at igrabski@nygenome.org.
