### ISSUE TITLE
Analyzing public data does not result in the same UMAP graph

### ISSUE THREAD

**Issue by YB0101-cli** [satijalab/seurat#7785]
Hi all,

I start learning about single cell RNA-seq analysis recently. So, to ensure that I can correctly analyze the data that I will obtained from my own experiments, I started analyzing the public data first. I used the data deposited in the NCBI server and published in the paper entitled "Single-Cell Analyses Identify Dysfunctional CD16+CD8 T Cells in Smokers". I used the parameters described in the paper, the only difference is the Seurat version. The paper used Seurat version 3.0.0.9000 and I am using version 4.3.0.1. Does different version of Seurat gives different result? 

The following UMAP is my result:
![image](https://github.com/satijalab/seurat/assets/137983007/d3f39089-3d9f-4d9e-ade0-db4c65b57889)

And this is the published UMAP:
![image](https://github.com/satijalab/seurat/assets/137983007/f4844914-81ba-45f5-a1e1-4a96f0c7e910)

Since the dataset contain smoker and non-smoker data, I played around with the merging sequence, i.e.: merging the data sequentially based on their IDs vs. merging the same type of data first (smoker with smoker and non-smoker with non-smoker) before merging all of them together. I found that the UMAP resulted from these two different approaches are different although the dataset is the same. Is this normal, if so, which UMAP should I trust?

This is the UMAP resulted from merging the data sequentially:
![image](https://github.com/satijalab/seurat/assets/137983007/b40c08c8-0a5a-445e-9047-0455cbad390c)

This is the UMAP resulted from merging the same type of data first and then merging the two different groups of data together:
![image](https://github.com/satijalab/seurat/assets/137983007/e396dc67-07e8-4b7d-810b-878ba9ad3d4e)

Thanks in advance for the input.

**Comment by GischD** [comment]
How did you merge these dates? Did you use this `https://satijalab.org/seurat/articles/integration_rpca`
If the data is merged before you get the data you need to apply a batch-effect correction method.

**Comment by YB0101-cli** [comment]
Thank you for the advice, I tried it today. I tried CCA today and already got a better result, no batch variation anymore, but still cannot obtain the same graph as the published one.

**Comment by GischD** [comment]
There are many factors that can change UMAP. QC parameter and also a random variable on the reduction model. I think it is hard to compare both because you don't have an X and Y in the previous UMAP.  If the public data has feature plots try to do these plots in your data and see where this localizes.

**Comment by YB0101-cli** [comment]
So, you mean that we cannot get the same UMAP everytime unless we follow the exact same procedure and parameters, right? 
Thank you for your suggestion, I tried the feature plots and roughly I got similar clusters of the major and specific immune cells, but I missed the minor cell types though. 
My UMAP after relabeling for major immune cells (two tiny clusters appeared and since the feature plots did not show any major expression for these clusters, I cannot assign any cell type to them): 
![image](https://github.com/satijalab/seurat/assets/137983007/6f397a2b-6d4a-4bdb-9dcc-52a62dc9fd77)
The published UMAP for major immune cells:
![image](https://github.com/satijalab/seurat/assets/137983007/147f7f3d-d006-4726-a534-a72f81fb92c8)
My UMAP for the specific immune cells:
![image](https://github.com/satijalab/seurat/assets/137983007/2fb15bf2-f8f8-488a-a907-0983e7c3f564)
I found 18 clusters for CD4T, 5 clusters for CD8T, 3 clusters for NK, 4 clusters for monocytes and 1 cluster for B
The published UMAP for specific immune cells:
![image](https://github.com/satijalab/seurat/assets/137983007/3c8cc9e9-061e-4309-ba22-d9f9854359fd)
They found 12 clusters for CD4T, 7 clusters for CD8T, 1 cluster for NKT, 3 clusters for NK, 4 clusters monocytes, 1 cluster for DC, 2 clusters for B, 1 cluster for MK and 1 cluster for Ery. 

In your opinion, is my result good enough? Since any procedure gives results, I just want to make sure that I get the correct ones. If you have any suggestions or inputs regarding QC to assess output quality and correctness, please let me know. Thanks so much.

**Comment by longmanz** [comment]
Hi,
Thank you @GischD. The main reason you see very different UMAP is because the version of Seurat you uses is different from the one they used in the paper. Many parameters have been changed from v3 to v4. 
Regarding your second question, A (merging the data sequentially) and B (merging the same type of data first and then merging the two different group) are actually consistent with each other. Both of them have consistent clusters. The sequence of merging does impact your UMAP a bit because the orders of cells are different. 
Regarding your third question, have you tried to label your own UMAP with their specific immune cell types?

**Comment by YB0101-cli** [comment]
Thanks @longmanz for the input. 
Regarding my third question, aI am sorry that I pasted the wrong image in my previous comment. Here is the correct image:
![Screenshot_20230917_232845](https://github.com/satijalab/seurat/assets/137983007/78f2e1d5-2b0d-44a8-bf82-b5feb6df4397)
As you can see, the main clusters are similar, but the smaller clusters are different. The UMAP that I generated didn't pick up the smaller ones, like NKT and DC. And I generated two tiny clusters that did not show any expression for NKT and DC markers. The published UMAP looks very nice and all clusters are well segregated.

**Comment by longmanz** [comment]
Hi @YB0101-cli ,
Thank you for the update. 
I think it is a bit tricky to re-produce the exact same clustering as in their paper. One thing you could check for their data is to find the Cluster Markers for their annotated (smaller) clusters, and see if the markers really exist (or do the markers really make sense). It is not necessary that their clustering is better than yours.
