### ISSUE TITLE
how to create multiple seurat objects if there is 3 conditions and 3x biological replicate (e.g. mice) per condition?

### ISSUE THREAD

**Issue by klai001** [satijalab/seurat#7786]
Hi i have mined a data in which its experimental design is such that I have 3 conditions (prolonged, acute , healthy)
and there're 4-6x biological replicate per condition. In each unique dataset/ GSMxxxx (e.g. prolonged rep 1)
- theres a barcodes, matrix and features file.

How should i go about this? I would think that 
1. create a seurat object independently for each unique dataset (e.g. prolonged rep 1).
2. creating a list for integration for ALL datasets, listing ALL healthy as reference

Also, is there a way to recursively create the seurat object for all files?

**Comment by Gesmira** [comment]
Hi, 
Your steps make sense! I recommend assessing the quality of your integration after, and adjusting the workflow if necessary. In regards to your second question, there is not a direct Seurat function to do this, but you can use code like `all <- map(list_of_data, CreateSeuratObject)` after reading in the directories with the `Read10X` function.
