### ISSUE TITLE
Is it possible to generate a ridgeplot and VlnPlot with zero feature expression?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#7790]
Hello! My current problem is demonstrating that a gene is not present in a dataset or independent cohort; indeed, it was not present upon analysis. However, a limitation of VlnPlot and ridgeplot is that it does not allow the generation of a plot with zero expression of a specific gene in question. Is there a way to force it to generate the these plots?

Example error in ridgeplot: 

```
>RidgePlot(ALL.harmony, features = "THISGENE")
Error in `FetchData()`:
! None of the requested variables were found: THISGENE
Run `rlang::last_trace()` to see where the error occurred.
```

```
> VlnPlot(ALL.harmony, features = "THISGENE")
Error in `FetchData()`:
! None of the requested variables were found: THISGENE
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So this is personal opinion but is showing a plot of zero necessary?  Often I find such things cane be done with either a table within figure or supplemental table showing percent of cells that express given gene and then you can include gene not expressed there with numerical 0.

Best,
Sam

**Comment by longmanz** [comment]
Thanks @samuel-marsh! Yes it seems not necessary to "force" a VlnPlot/RidgePlot if the gene does not even present in the dataset.
