### ISSUE TITLE
Sketch integration with widely varying sample sizes

### ISSUE THREAD

**Issue by nadschro** [satijalab/seurat#7793]
Hi,
I'm trying to integrate 55 samples that range in size from 40 to 15000 cells, with most of them being about 4000 cells.
The very small samples represent a condition with increased cell death and their surviving cells are important to integrate into the whole. 

As it doesn't make much sense to use 40 cells as the sampling size, I've run SketchData with 4000 cells on the larger samples and integrated them. Is there a way to properly integrate the small samples into that object afterward?

Thank you!

**Comment by Gesmira** [comment]
Hi, 
You could `merge()` samples together to increase the size of the object while maintaining sample information in the metadata. You could then sketch from this larger combined object. Alternatively, you can follow our [integration workflow](https://satijalab.org/seurat/articles/seurat5_integration) to add in the smaller samples, but keep in mind that with samples of that size you will likely need to adjust anchor finding parameters and should assess the quality of the integration yourself.

**Comment by nadschro** [comment]
Thank you for the input!
