### ISSUE TITLE
MapQuery verbose=F doesn't work

### ISSUE THREAD

**Issue by thisisamirv** [satijalab/seurat#7794]
Hi, I just wanted to let you know that the verbose=F option in MapQuery function doesn't do anything, as you can see in the log of my analysis below:

> samples <- MapQuery(anchorset=anchors, query=samples, reference=ref, refdata=list(celltype.l1="celltype.l1", celltype.l2="celltype.l2"), reference.reduction="spca", reduction.model="wnn.umap", verbose=F)

Computing nearest neighbors
Running UMAP projection
21:18:14 Read 1782 rows
21:18:14 Processing block 1 of 1
21:18:14 Commencing smooth kNN distance calibration using 10 threads with target n_neighbors = 15
21:18:14 Initializing by weighted average of neighbor coordinates using 10 threads
21:18:14 Commencing optimization for 67 epochs, with 26730 positive edges
Using method 'umap'
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
21:18:14 Finished

Not a big deal though, but it would be better to be able to get rid of these extra messages.

**Comment by rsatija** [comment]
These outputs are actually from RunUMAP, which does produce outputs that we do not control. Setting verbose=F does reduce the amount of output the function returns though, but you are correct that it does not reduce it to 0.
