### ISSUE TITLE
FindMarkers output: is p_val raw or adjusted?

### ISSUE THREAD

**Issue by khandarius** [satijalab/seurat#78]
Hello and thank you for the amazing software. I was wondering about the output of the differential expression tests, specifically the p-values. Are they raw or have they been adjusted for multiple testing? I didn't find information about this in the documentation. Going through the code it seems that they are raw, but I just wanted to make sure. Thanks in advance!

**Comment by andrewwbutler** [comment]
Yes, that's correct. The p-values that are reported from these functions are raw (uncorrected) p-values.
