### ISSUE TITLE
plot_cells function error when trying to plot gene expression in Monocle3 using Seurat integrated data

### ISSUE THREAD

**Issue by DrLukeSimpson** [satijalab/seurat#7800]
I've been following a pipeline to integrate and analyze single-cell data using Seurat, and then convert the integrated Seurat object to a Monocle3 object for trajectory analysis.

The code I've used is primarily from the Seurat website:
InstallData("hcabm40k")
data("hcabm40k")
hcabm40k = UpdateSeuratObject(object = hcabm40k)

hcabm40k <- SplitObject(hcabm40k, split.by = "orig.ident")
for (i in seq_along(hcabm40k)) {
  hcabm40k[[i]] <- NormalizeData(hcabm40k[[i]]) %>% FindVariableFeatures()
}
features <- SelectIntegrationFeatures(hcabm40k)
for (i in seq_along(along.with = hcabm40k)) {
  hcabm40k[[i]] <- ScaleData(hcabm40k[[i]], features = features) %>% RunPCA(features = features)
}
anchors <- FindIntegrationAnchors(hcabm40k, reference = c(1, 2), reduction = "rpca", dims = 1:30)
integrated <- IntegrateData(anchors, dims = 1:30)
integrated <- ScaleData(integrated)
integrated <- RunPCA(integrated)
integrated <- RunUMAP(integrated, dims = 1:30, reduction.name = "UMAP")
integrated <- FindNeighbors(integrated, dims = 1:30)
integrated <- FindClusters(integrated)
DimPlot(integrated, group.by = c("orig.ident", "ident"))
cds <- as.cell_data_set(integrated)
cds<- reduce_dimension(cds, preprocess_method = 'PCA')
cds<- reduce_dimension(cds, preprocess_method = 'UMAP')
cds <- cluster_cells(cds)
p1 <- plot_cells(cds, show_trajectory_graph = FALSE)
p2 <- plot_cells(cds, color_cells_by = "partition", show_trajectory_graph = FALSE)
wrap_plots(p1, p2)
integrated.sub <- subset(as.Seurat(cds), monocle3_partitions == 1)
?subset
?monocle3_partitions
cds <- as.cell_data_set(integrated.sub)
cds <- learn_graph(cds)
plot_cells(cds, label_groups_by_cluster = FALSE, label_leaves = FALSE, label_branch_points = FALSE)

Everything works smoothly until I try to plot gene expression with the plot_cells function:

plot_cells(cds, genes = "HBB", label_groups_by_cluster = FALSE, label_leaves = FALSE, label_branch_points = FALSE)

Executing this gives me the following error:

Error in names(sf) <- colnames(SingleCellExperiment::counts(cds)) : 
  attempt to set an attribute on NULL

I have tried updating R to 4.3.1 and updating Seurat and Monocle3. If I use counts(cds) the counts information is there! Any suggestions would be greatly appreciated! 

Thank you

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
