### ISSUE TITLE
Famous "No requested features found in the scale.data slot for the RNA assay."

### ISSUE THREAD

**Issue by errcricket** [satijalab/seurat#7802]
I have ran a full analysis on a large dataset containing many samples using RPCA (large dataset approach). I specifically used the rownames (line 451) to avoid the _No requested features found in the scale.data slot for the RNA assay_ error, but I was not successful. There are no shortages of similar [questions](https://github.com/satijalab/seurat/issues/2960), and yet, I am still lost.

```
446    features <- SelectIntegrationFeatures(object.list = SO.list)
447    features_full <- rownames(S) #added 8.24.23
448 
449    #------------------------------------------------------------------
450    SO.list <- lapply(X = SO.list, FUN = function(x) {
451       x <- ScaleData(x, features = features_full, verbose = FALSE)
452       x <- RunPCA(x, features = features, verbose = FALSE, approx=FALSE)
453    })
```

As a cheat, I tried to scale the data again (saving it as a different object), but the results were the same.
```
S2 <- ScaleData(S, features=rownames(S))
DefaultAssay(S2) <- 'integrated'
DoHeatmap(S2, features = c('TPO', 'TG', 'PAX8')) 
#The following features were omitted as they were not found in the scale.data slot for the integrated assay: PAX8, TG
```

I am not certain if this is pertinent, but the data was originally run at multiple resolutions. Clustree was used to identify areas of overclustering, and using WhichCells, a single clustering schema was created from the original (multiple) resolutions. I also added the new cluster names into metadata, but no subsetting has occurred. 

I have 2 questions.

1. Is it ok to run ScaleData using the rownames, and RunPCA using the just the variable features? (Is this why the error is still occurring? I was trying to save time, and not use all the genes to run PCA.)
2. **Without having to start from scratch**, is there a way to scale the genes so that I can create a heatmap?

Assistance welcomed and appreciated.

**Comment by Gesmira** [comment]
Hi, 
Can you try with running `DefaultAssay(S2) <- 'integrated'` before you run` ScaleData()`? It's possible you are running ScaleData on a different assay, hence the warning. Furthermore, can you confirm that those genes are actually present in the rownames of your object?

**Comment by errcricket** [comment]
Thanks for the response @Gesmira.

The code for S2 was created with the code below, is in alignment with your suggestion, but still generates the error.

```
DefaultAssay(S) <- 'integrated'
S2 <- ScaleData(S, features=rownames(S))
DefaultAssay(S2) <- 'integrated'
DoHeatmap(S2, features = c('TPO', 'TG', 'PAX8')) 
```

I looked at the length of the rownames(S), I was surprised to find that it was only 2000 genes. I am not sure how that happened and will revisit it. For the moment, I grabbed _all_ the genes and scaled them and tried to plot a heatmap...same exact error.

```
features <- S@assays[["RNA"]]@counts@Dimnames[[1]]
DefaultAssay(S) <- 'integrated'
#S2 <- ScaleData(S, features=features) #rownames(S))
S2 <- ScaleData(S, features=S@assays[["RNA"]]@counts@Dimnames[[1]]) #rownames(S))
DefaultAssay(S2) <- 'integrated'
DoHeatmap(S2, features = c('TPO', 'TG', 'PAX8'))

The following features were omitted as they were not found in the scale.data slot for the integrated assay: PAX8, TG
> 'PAX8' %in% features
[1] TRUE
> 'TG' %in% features
[1] TRUE
```

My main question right now is...Without having to start from scratch, is there a way to scale the genes so that I can create a heatmap?

**Comment by errcricket** [comment]
A better way to describe my problem is that a) it is too computationally expensive to run all of the cluster-making steps with the full gene set for large datasets. I solve [this](https://satijalab.org/seurat/articles/integration_large_datasets) with variable/a select number of genes -- which does not guarantee that I can then create a DoHeatmap figure of cluster-defining markers because they may not be included within the variable genes. It seems like there should be a function to do so with non-normalized RNA values...and the solution is already [here](https://github.com/satijalab/seurat/issues/2486). I will return an averaged-value Seurat object, and make the heatmap from that. Closing.
