### ISSUE TITLE
Error about JoinLayers after subsetting a seurat object with already existed scale.data layers

### ISSUE THREAD

**Issue by Junedays** [satijalab/seurat#7804]
I am reporting an error about joinlayers, i have identified the reason, and i am not sure whether it is a bug, or a simple mistake that i could solve by renewing the scale. data. 

I attached the following reproducible examples:

# Load the example dataset. 
load(pbmsca)

# The first part is OK, no error. 
# In this part, i just do the split and traditional normalize, and scale process. This flow is OK as we can split and rejoint layers easily. 
obj <- pbmcsca
obj
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$Method)
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- JoinLayers(obj)
obj

# The second part will have an error. 
# In the second part analysis, i would like to subset the obj and then do another normalize and scale

obj2 <- subset(obj,nFeature_RNA>2000)
obj2 # now we can see obj2 already has a scale.data layer now. 

# Now we want to do the normalize and scale again in this subset, so that we can further cluster them. 

obj2[["RNA"]] <- split(obj2[["RNA"]], f = obj2$Method)
obj2
obj2 <- NormalizeData(obj2)
obj2 <- FindVariableFeatures(obj2)
obj2 <- ScaleData(obj2)

# now we can see the potential errors, a new scale.data was added to the layer, with alrealy splitted scale.data.layers
obj2

# and then we will have error when
obj2 <- JoinLayers(obj2)
obj2

An object of class Seurat 
33694 features across 1708 samples within 1 assay 
Active assay: RNA (33694 features, 1811 variable features)
 12 layers present: data, counts, scale.data.Smart-seq2, scale.data.CEL-Seq2, scale.data.10x_Chromium_v2_A, scale.data.10x_Chromium_v2_B, scale.data.10x_Chromium_v3, scale.data.Drop-seq, scale.data.Seq-Well, scale.data.inDrops, scale.data.10x_Chromium_v2, scale.data

# now we can wee that , possibly due to the newly added scale.data to the already existed splitted scale.data sets, the JoinLayers cannot do the rejoint for all splitted scale.data.

**Comment by Gesmira** [comment]
Hi, 
We've changed the behavior of split so that it only splits "counts" and "data" layers by default. This will fix your issues as there will always be one joined "scale.data" layer. This is in line with the reasoning that the scaling should be done with all of the cells. 
Thanks for bringing this up!

**Comment by mattmacd4** [comment]
With this new update I've been running into a problem where the JoinLayers doesn't actually join the counts layers both for split BP cells objects and for in-memory objects.

```R
> thymus_immune_merge <- merge(x = h5BP_CD45P.tcells, y = thymus_raw_tcellsubset_v5BP, add.cell.ids = c("imm", "thy"), project = "TregDevo")
> thymus_immune_merge
An object of class Seurat 
45071 features across 109482 samples within 1 assay 
Active assay: RNA (45071 features, 0 variable features)
 2 layers present: counts.teich_immune, counts.teich_thymus
> thymus_immune_merge <- JoinLayers(thymus_immune_merge)
> thymus_immune_merge
An object of class Seurat 
45071 features across 109482 samples within 1 assay 
Active assay: RNA (45071 features, 0 variable features)
 3 layers present: counts, counts.teich_immune, counts.teich_thymus
```
You can see the behavior doesn't actually join the layers, but instead creates an additional layer. This was not occurring 24-48hrs ago.

**Comment by mattmacd4** [comment]
Reproducible code example:

```R
pbmc3k <- LoadData("pbmc3k")
random_values <- sample(c("a", "b"), nrow(pbmc3k@meta.data), replace = TRUE)
pbmc3k$random <- random_values
```


```R
>pbmc3k
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features, 0 variable features)
 4 layers present: counts.a, counts.b, data.a, data.b

> pbmc3k <- JoinLayers(pbmc3k)

> pbmc3k
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features, 0 variable features)
 6 layers present: data, counts, counts.a, counts.b, data.a, data.b
```

**Comment by Gesmira** [comment]
Thanks for pointing this out! This is fixed now in the SeuratObject repo. You can restart and reinstall with: 
`remotes::install_github("mojaveazure/seurat-object", "seurat5")`
