### ISSUE TITLE
FindSubCluster vs Subset+Reclustering

### ISSUE THREAD

**Issue by shaln** [satijalab/seurat#7809]
Hi, 

Opening a new issue on this, as the question was previously asked here but remains unanswered though the issue was closed https://github.com/satijalab/seurat/issues/5012#issuecomment-916314469. 

How does the FindSubCluster() function work? Would re-using the same variable features not be an issue? Prior to this function becoming available, finding subclusters would involve: subsetting, re-scaling, re-finding variable features within the subset, and then re-clustering the subset. Does the FindSubCluster() function do all of that under the hood?

**Comment by mhkowalski** [comment]
Hi, thanks for your question. You are always welcome to check the source code (the ```FindSubCluster()``` function can be found in ```clustering.R```), but to answer your question, no, this function merely subsets the SNN graph used for clustering (to just the cluster of interest) and runs clustering again.  It will give different results from the subsetting procedure you describe above.

**Comment by annepureddy** [comment]
Thank you for your response. Is there a reason to prefer using the FindSubCluster() method over the subsetting procedure mentioned earlier? Additionally, I already have an integrated multiome object. For analyses such as pseudotime, do I need to subset and recluster, or can I use the FindSubCluster() function directly without additional subsetting?
