### ISSUE TITLE
problem sketching with BPcells

### ISSUE THREAD

**Issue by matosmr** [satijalab/seurat#7810]
Hi, I am trying to following[ this vignette](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette) to create a on-disk representation. I am able to write the MatrixDir,  and open it from the directory. However, I am running into problems when adding. that representation back to the Seurat Object. 

 

```r
obj <- readRDS("reference_inmune_cells/tabula-sapiens_immune.rds")
obj = UpdateSeuratObject(object = obj)
format(object.size(obj), units = "Mb")
str(obj)
write_matrix_dir(mat = obj[["RNA"]]@counts, dir ="reference_inmune_cells/tabula_immune_counts2/")
```

Formal class 'Seurat' [package "SeuratObject"] with 13 slots
  ..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "SeuratObject"] with 8 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:578888429] 38 137 148 197 229 256 266 273 297 332 ...
  .. .. .. .. .. ..@ p       : int [1:264825] 0 2300 3604 6230 8485 10871 13731 15603 17313 20754 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 58604 264824
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:58604] "ENSG00000223972" "ENSG00000227232" "ENSG00000278267" "ENSG00000243485" ...
  .. .. .. .. .. .. ..$ : chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  .. .. .. .. .. ..@ x       : num [1:578888429] 9 2 1 1 3 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:578888429] 38 137 148 197 229 256 266 273 297 332 ...
  .. .. .. .. .. ..@ p       : int [1:264825] 0 2300 3604 6230 8485 10871 13731 15603 17313 20754 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 58604 264824
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:58604] "ENSG00000223972" "ENSG00000227232" "ENSG00000278267" "ENSG00000243485" ...
  .. .. .. .. .. .. ..$ : chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  .. .. .. .. .. ..@ x       : num [1:578888429] 2.31 2.02 1.77 2.91 1.75 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "rna_"
  .. .. .. ..@ assay.orig   : NULL
  .. .. .. ..@ var.features : logi(0) 
  .. .. .. ..@ meta.features:'data.frame':	58604 obs. of  11 variables:
  .. .. .. .. ..$ feature_type         : Factor w/ 1 level "Gene Expression": 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. ..$ highly.variable      : logi [1:58604] FALSE FALSE FALSE FALSE FALSE FALSE ...
  .. .. .. .. ..$ mvp.mean             : num [1:58604] 6.40e-05 2.27e-03 6.18e-05 1.37e-04 1.00e-12 ...
  .. .. .. .. ..$ mvp.dispersion       : num [1:58604] 0.835 2.442 1.295 2.656 NaN ...
  .. .. .. .. ..$ mvp.dispersion.scaled: num [1:58604] -0.574 0.533 -0.257 0.681 0 ...
  .. .. .. .. ..$ mean                 : num [1:58604] 3.88e-05 1.08e-03 3.27e-05 4.77e-05 0.00 ...
  .. .. .. .. ..$ std                  : num [1:58604] 0.00557 0.03173 0.00563 0.00804 1 ...
  .. .. .. .. ..$ feature_is_filtered  : logi [1:58604] FALSE FALSE FALSE FALSE FALSE FALSE ...
  .. .. .. .. ..$ feature_name         : Factor w/ 58604 levels "5S_rRNA_ENSG00000276861",..: 10337 56299 24237 22664 22663 12930 27687 27683 27678 40028 ...
  .. .. .. .. ..$ feature_reference    : Factor w/ 1 level "NCBITaxon:9606": 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. ..$ feature_biotype      : Factor w/ 1 level "gene": 1 1 1 1 1 1 1 1 1 1 ...
  .. .. .. ..@ misc         : list()
  ..@ meta.data   :'data.frame':	264824 obs. of  27 variables:
  .. ..$ tissue_in_publication                   : Factor w/ 24 levels "Bladder","Blood",..: 9 9 9 9 9 9 9 9 9 9 ...
  .. ..$ assay_ontology_term_id                  : Factor w/ 3 levels "EFO:0009922",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ donor_id                                : Factor w/ 15 levels "TSP1","TSP2",..: 6 6 6 6 6 6 6 6 6 6 ...
  .. ..$ anatomical_information                  : Factor w/ 36 levels "abdomen","anterior",..: 19 19 19 19 19 19 19 19 19 19 ...
  .. ..$ nCounts_RNA_UMIs                        : num [1:264824] 7633 2858 10395 6610 9387 ...
  .. ..$ nFeaturess_RNA                          : num [1:264824] 2259 1152 2598 2125 2345 ...
  .. ..$ cell_ontology_class                     : Factor w/ 62 levels "b cell","basophil",..: 34 41 34 33 34 51 34 41 34 41 ...
  .. ..$ free_annotation                         : Factor w/ 147 levels "AREG High T-Cell",..: 46 45 46 29 46 66 46 45 46 45 ...
  .. ..$ manually_annotated                      : logi [1:264824] TRUE TRUE TRUE TRUE TRUE TRUE ...
  .. ..$ compartment                             : Factor w/ 1 level "immune": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ sex_ontology_term_id                    : Factor w/ 2 levels "PATO:0000384",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ disease_ontology_term_id                : Factor w/ 1 level "PATO:0000461": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ is_primary_data                         : logi [1:264824] FALSE FALSE FALSE FALSE FALSE FALSE ...
  .. ..$ organism_ontology_term_id               : Factor w/ 1 level "NCBITaxon:9606": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ suspension_type                         : Factor w/ 1 level "cell": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ cell_type_ontology_term_id              : Factor w/ 56 levels "CL:0000037","CL:0000038",..: 11 16 11 56 11 33 11 16 11 16 ...
  .. ..$ tissue_ontology_term_id                 : Factor w/ 44 levels "UBERON:0000016",..: 29 29 29 29 29 29 29 29 29 29 ...
  .. ..$ development_stage_ontology_term_id      : Factor w/ 14 levels "HsapDv:0000155",..: 5 5 5 5 5 5 5 5 5 5 ...
  .. ..$ self_reported_ethnicity_ontology_term_id: Factor w/ 4 levels "HANCESTRO:0016",..: 2 2 2 2 2 2 2 2 2 2 ...
  .. ..$ cell_type                               : Factor w/ 56 levels "hematopoietic stem cell",..: 11 16 11 56 11 33 11 16 11 16 ...
  .. ..$ assay                                   : Factor w/ 3 levels "10x 3' v3","Smart-seq2",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ disease                                 : Factor w/ 1 level "normal": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ organism                                : Factor w/ 1 level "Homo sapiens": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ sex                                     : Factor w/ 2 levels "male","female": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ tissue                                  : Factor w/ 44 levels "endocrine pancreas",..: 29 29 29 29 29 29 29 29 29 29 ...
  .. ..$ self_reported_ethnicity                 : Factor w/ 4 levels "African American or Afro-Caribbean",..: 2 2 2 2 2 2 2 2 2 2 ...
  .. ..$ development_stage                       : Factor w/ 14 levels "61-year-old human stage",..: 5 5 5 5 5 5 5 5 5 5 ...
  ..@ active.assay: chr "RNA"
  ..@ active.ident: Factor w/ 1 level "local": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..- attr(*, "names")= chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  ..@ graphs      : list()
  ..@ neighbors   : list()
  ..@ reductions  :List of 4
  .. ..$ pca      :Formal class 'DimReduc' [package "SeuratObject"] with 9 slots
  .. .. .. ..@ cell.embeddings           : num [1:264824, 1:50] -11.62 -24.75 -9.43 -7.02 -5.83 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  .. .. .. .. .. ..$ : chr [1:50] "PC_1" "PC_2" "PC_3" "PC_4" ...
  .. .. .. ..@ feature.loadings          : num[0 , 0 ] 
  .. .. .. ..@ feature.loadings.projected: num[0 , 0 ] 
  .. .. .. ..@ assay.used                : chr "RNA"
  .. .. .. ..@ global                    : logi FALSE
  .. .. .. ..@ stdev                     : num(0) 
  .. .. .. ..@ key                       : chr "PC_"
  .. .. .. ..@ jackstraw                 :Formal class 'JackStrawData' [package "SeuratObject"] with 4 slots
  .. .. .. .. .. ..@ empirical.p.values     : num[0 , 0 ] 
  .. .. .. .. .. ..@ fake.reduction.scores  : num[0 , 0 ] 
  .. .. .. .. .. ..@ empirical.p.values.full: num[0 , 0 ] 
  .. .. .. .. .. ..@ overall.p.values       : num[0 , 0 ] 
  .. .. .. ..@ misc                      : list()
  .. ..$ scvi     :Formal class 'DimReduc' [package "SeuratObject"] with 9 slots
  .. .. .. ..@ cell.embeddings           : num [1:264824, 1:50] -0.918 0.5 -0.472 -0.224 -0.578 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  .. .. .. .. .. ..$ : chr [1:50] "SCVI_1" "SCVI_2" "SCVI_3" "SCVI_4" ...
  .. .. .. ..@ feature.loadings          : num[0 , 0 ] 
  .. .. .. ..@ feature.loadings.projected: num[0 , 0 ] 
  .. .. .. ..@ assay.used                : chr "RNA"
  .. .. .. ..@ global                    : logi FALSE
  .. .. .. ..@ stdev                     : num(0) 
  .. .. .. ..@ key                       : chr "SCVI_"
  .. .. .. ..@ jackstraw                 :Formal class 'JackStrawData' [package "SeuratObject"] with 4 slots
  .. .. .. .. .. ..@ empirical.p.values     : num[0 , 0 ] 
  .. .. .. .. .. ..@ fake.reduction.scores  : num[0 , 0 ] 
  .. .. .. .. .. ..@ empirical.p.values.full: num[0 , 0 ] 
  .. .. .. .. .. ..@ overall.p.values       : num[0 , 0 ] 
  .. .. .. ..@ misc                      : list()
  .. ..$ scvi_umap:Formal class 'DimReduc' [package "SeuratObject"] with 9 slots
  .. .. .. ..@ cell.embeddings           : num [1:264824, 1:2] 9.77 9.29 8.89 8.06 8.72 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  .. .. .. .. .. ..$ : chr [1:2] "SCVIumap_1" "SCVIumap_2"
  .. .. .. ..@ feature.loadings          : num[0 , 0 ] 
  .. .. .. ..@ feature.loadings.projected: num[0 , 0 ] 
  .. .. .. ..@ assay.used                : chr "RNA"
  .. .. .. ..@ global                    : logi FALSE
  .. .. .. ..@ stdev                     : num(0) 
  .. .. .. ..@ key                       : chr "SCVIumap_"
  .. .. .. ..@ jackstraw                 :Formal class 'JackStrawData' [package "SeuratObject"] with 4 slots
  .. .. .. .. .. ..@ empirical.p.values     : num[0 , 0 ] 
  .. .. .. .. .. ..@ fake.reduction.scores  : num[0 , 0 ] 
  .. .. .. .. .. ..@ empirical.p.values.full: num[0 , 0 ] 
  .. .. .. .. .. ..@ overall.p.values       : num[0 , 0 ] 
  .. .. .. ..@ misc                      : list()
  .. ..$ umap     :Formal class 'DimReduc' [package "SeuratObject"] with 9 slots
  .. .. .. ..@ cell.embeddings           : num [1:264824, 1:2] 5.05 3.74 4.1 4.57 4.53 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:264824] "AAACCCACACTCCTGT_TSP6_Liver_NA_10X_1_1" "AAACGAAGTACCAGAG_TSP6_Liver_NA_10X_1_1" "AAAGAACAGCCTCTTC_TSP6_Liver_NA_10X_1_1" "AAAGAACGTAGCACAG_TSP6_Liver_NA_10X_1_1" ...
  .. .. .. .. .. ..$ : chr [1:2] "UMAP_1" "UMAP_2"
  .. .. .. ..@ feature.loadings          : num[0 , 0 ] 
  .. .. .. ..@ feature.loadings.projected: num[0 , 0 ] 
  .. .. .. ..@ assay.used                : chr "RNA"
  .. .. .. ..@ global                    : logi FALSE
  .. .. .. ..@ stdev                     : num(0) 
  .. .. .. ..@ key                       : chr "UMAP_"
  .. .. .. ..@ jackstraw                 :Formal class 'JackStrawData' [package "SeuratObject"] with 4 slots
  .. .. .. .. .. ..@ empirical.p.values     : num[0 , 0 ] 
  .. .. .. .. .. ..@ fake.reduction.scores  : num[0 , 0 ] 
  .. .. .. .. .. ..@ empirical.p.values.full: num[0 , 0 ] 
  .. .. .. .. .. ..@ overall.p.values       : num[0 , 0 ] 
  .. .. .. ..@ misc                      : list()
  ..@ images      : list()
  ..@ project.name: chr "local"
  ..@ misc        :List of 2
  .. ..$ schema_version: chr "3.1.0"
  .. ..$ title         : chr "Tabula Sapiens - Immune"
  ..@ version     :Classes 'package_version', 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 4 1 0
  ..@ commands    : list()
  ..@ tools       : list()

```
counts.mat <- open_matrix_dir(dir = "reference_inmune_cells/tabula_immune_counts2/")
class(counts.mat)

obj[["RNA"]]@counts <- counts.mat
```

**Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “MatrixDir” is not valid for @‘counts’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE
Error during wrapup: 'length = 17' in coercion to 'logical(1)'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart**

R version 4.3.1 (2023-06-16)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /nfs/sw/miniconda3/miniconda3-3.22.0/envs/R-4.2.3/lib/libopenblasp-r0.3.24.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.3           Azimuth_0.4.6         shinyBS_0.61.1        SeuratDisk_0.0.0.9020 ggplot2_3.4.3        
[6] BPCells_0.1.0         SeuratObject_4.1.3    Seurat_4.3.0.1       

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3     rstudioapi_0.15.0      jsonlite_1.8.7         magrittr_2.0.3         spatstat.utils_3.0-3  
  [6] fs_1.6.3               vctrs_0.6.3            ROCR_1.0-11            spatstat.explore_3.2-1 htmltools_0.5.6       
 [11] cellranger_1.1.0       googlesheets4_1.1.1    sctransform_0.3.5      parallelly_1.36.0      KernSmooth_2.23-22    
 [16] htmlwidgets_1.6.2      ica_1.0-3              plyr_1.8.8             plotly_4.10.2          zoo_1.8-12            
 [21] igraph_1.5.1           mime_0.12              lifecycle_1.0.3        pkgconfig_2.0.3        Matrix_1.6-1          
 [26] R6_2.5.1               fastmap_1.1.1          fitdistrplus_1.1-11    future_1.33.0          shiny_1.7.5           
 [31] digest_0.6.33          colorspace_2.1-0       patchwork_1.1.3        tensor_1.5             irlba_2.3.5.1         
 [36] progressr_0.14.0       fansi_1.0.4            spatstat.sparse_3.0-2  httr_1.4.7             polyclip_1.10-4       
 [41] abind_1.4-5            compiler_4.3.1         gargle_1.5.2           bit64_4.0.5            withr_2.5.0           
 [46] MASS_7.3-60            rappdirs_0.3.3         SeuratData_0.2.2       tools_4.3.1            lmtest_0.9-40         
 [51] googledrive_2.1.1      httpuv_1.6.11          future.apply_1.11.0    goftest_1.2-3          glue_1.6.2            
 [56] nlme_3.1-163           promises_1.2.1         grid_4.3.1             Rtsne_0.16             cluster_2.1.4         
 [61] reshape2_1.4.4         generics_0.1.3         hdf5r_1.3.8            gtable_0.3.4           spatstat.data_3.0-1   
 [66] tidyr_1.3.0            data.table_1.14.8      sp_2.0-0               utf8_1.2.3             spatstat.geom_3.2-5   
 [71] RcppAnnoy_0.0.21       ggrepel_0.9.3          RANN_2.6.1             pillar_1.9.0           stringr_1.5.0         
 [76] spam_2.9-1             RcppHNSW_0.4.1         later_1.3.1            splines_4.3.1          lattice_0.21-8        
 [81] survival_3.5-7         bit_4.0.5              deldir_1.0-9           tidyselect_1.2.0       miniUI_0.1.1.1        
 [86] pbapply_1.7-2          knitr_1.43             gridExtra_2.3          scattermore_1.2        shinydashboard_0.7.2  
 [91] xfun_0.40              matrixStats_1.0.0      DT_0.29                stringi_1.7.12         lazyeval_0.2.2        
 [96] codetools_0.2-19       tibble_3.2.1           cli_3.6.1              uwot_0.1.16            xtable_1.8-4          
[101] reticulate_1.31        munsell_0.5.0          Rcpp_1.0.11            globals_0.16.2         spatstat.random_3.1-5 
[106] png_0.1-8              parallel_4.3.1         ellipsis_0.3.2         presto_1.0.0           dotCall64_1.0-2       
[111] listenv_0.9.0          viridisLite_0.4.2      scales_1.2.1           ggridges_0.5.4         leiden_0.4.3          
[116] purrr_1.0.2            crayon_1.5.2           rlang_1.1.1            cowplot_1.1.1          shinyjs_2.1.0  
```r
library(Seurat)
options(Seurat.object.assay.version = "v5")
library(BPCells)
library(ggplot2)
library(SeuratObject)
library(SeuratDisk)
library(Azimuth)
library(dplyr)

# needs to be set for large dataset analysis
options(future.globals.maxSize = 1e9)
obj <- readRDS("reference_inmune_cells/tabula-sapiens_immune.rds")
obj = UpdateSeuratObject(object = obj)

# Note that since the data is stored on-disk, the object size easily fits in-memory (<1GB)
format(object.size(obj), units = "Mb")

str(obj)
# Write the counts layer to a directory
#write_matrix_dir(mat = obj[["RNA"]]@counts, dir ="reference_inmune_cells/tabula_immune_counts2/")

counts.mat <- open_matrix_dir(dir = "reference_inmune_cells/tabula_immune_counts2/")
class(counts.mat)

obj[["RNA"]]@counts <- counts.mat

```

**Comment by Gesmira** [comment]
Hi,
BPCells can only be used with objects that have v5 Assays. I would first ensure you have a v5 Assay like: 
`inherits(obj[["RNA"]], "Assay5")`
If this is false, you can convert the assay in your object to a v5 assay like so: 
`obj[["RNA"]] <- as(obj[["RNA"]], "Assay5")`

Second, in v5 you should use $ to access the counts layers:
`obj[["RNA"]]$counts <- counts.mat`

Hope that helps!

**Comment by Gesmira** [comment]
Oh, just noticed your sessionInfo, looks like you need to install Seurat v5! 
Installation instructions can be found here: 
https://satijalab.org/seurat/articles/install
