### ISSUE TITLE
Will PaCMAP be incorporated?

### ISSUE THREAD

**Issue by hchoiHiLung** [satijalab/seurat#7811]
Congratulations to Seurat v5 beta!

As people are recommending PaCMAP over t-SNE and UMAP for dimensional reduction, will PaCMAP be added to Seurat v5 soon?

**Comment by hyhuang00** [comment]
I'm eager to contribute to the PaCMAP integration. However, I could use some guidance on understanding the code structure. Would anyone from the Seurat team be available to assist? Your help would be greatly appreciated.

**Comment by mhkowalski** [comment]
Hi, sorry for our delayed response. We would be delighted to welcome a contribution to SeuratWrappers. We have a contribution guide [here](https://github.com/satijalab/seurat-wrappers/wiki), and would be happy to answer any questions you have in that repo.
