### ISSUE TITLE
Mapping query to reference cell problem

### ISSUE THREAD

**Issue by sshen82** [satijalab/seurat#7816]
Hi,
I am using Seurat v5 to project query data into reference. Below is the code I have. However, I constantly receive error as below on the FindTransferAnchors step. Do you know what happened?
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds
Traceback:

Query = merge(Methyl@assays$RNA, Patch@assays$RNA)
Query = CreateSeuratObject(Query)
Query <- NormalizeData(Query)
Query <- FindVariableFeatures(Query, nfeatures = 3000)
Query <- ScaleData(Query, features = VariableFeatures(Query))

obj = readRDS("/p/keles/schic/volumeC/SiqiShen/code/Liu2023/Yao2023_Isocortex.Rds")
obj <- JoinLayers(obj)
ct_RNA = obj@meta.data$cluster
names(ct_RNA) = obj@meta.data$cell_label
obj@meta.data$cluster = stringr::str_split_fixed(obj@meta.data$cluster, " ", 4)[, 1]
obj = subset(obj, subset = cluster %in% c("IT", "L2", "L2/3", "L4", "L4/5", "L5", "L5/6", "L6", "L6b",
                                "L6b/CT", "Lamp5", "Pvalb", "Sncg", "Sst", "Vip"))
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- SketchData(
  object = obj,
  ncells = 40000,
  method = "LeverageScore",
  sketched.assay = "sketch"
)
DefaultAssay(obj) <- "sketch"
obj <- FindVariableFeatures(obj, nfeatures = 3000)
obj <- ScaleData(obj, features = VariableFeatures(obj))
obj = RunPCA(obj)

anchors <- FindTransferAnchors(
  reference = obj,
  query = Query,
  reference.reduction = "pca",
  dims = 1:50
)
pbmc3k <- MapQuery(
  anchorset = anchors,
  query = Query,
  reference = obj,
  reference.reduction = "pca"
)

**Comment by sshen82** [comment]
By the way, I need to add that it will work if I set the parameter reduction = "cca", but after this, the MapQuery will have error as below. 
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE): invalid character indexing

**Comment by Gesmira** [comment]
Hi, 
Are you using v3 or v5 assays: 
`inherits(obj[["sketch"]], "Assay5")` returns True or False? 

Does the error still occur if you do not sketch? 

Lastly, are you able to create a reproducible example with the data we provide in our vignettes?

**Comment by sshen82** [comment]
Oh, I forgot to close this question. I found that in IntegrateLayer, there is a "reference" parameter that can be used as a substitude to the MapQuery function. Thanks for your help still!

**Comment by jonathan-columbiau** [comment]
Hi, 

I'm still getting this error when trying to use the FindTransforAnchors method. 

I couldn't find the reference parameter in IntegrateLayer, did you mean IntegrateData?

Thanks!

**Comment by sshen82** [comment]
> Hi, 
> 
> 
> 
> I'm still getting this error when trying to use the FindTransforAnchors method. 
> 
> 
> 
> I couldn't find the reference parameter in IntegrateLayer, did you mean IntegrateData?
> 
> 
> 
> Thanks!

Hi,
IntegrateLayer is a function in v5. Did you update Seurat to that version?

**Comment by jonathan-columbiau** [comment]
Ah, thanks! Found it - I was a bit confused because the parameter normally doesn't appear in the help page for the function.
