### ISSUE TITLE
Gray dots in DotPlot after integrating SCTransformed objects

### ISSUE THREAD

**Issue by mariecrane** [satijalab/seurat#7817]
I followed the [SCTransform -> integration workflow ](https://satijalab.org/seurat/articles/integration_introduction#performing-integration-on-datasets-normalized-with-sctransform) and am trying to make a DotPlot visualization of marker gene expression in my different idents. However, a handful of genes are showing up as gray. I've found a few other issues about this (#4274, #7719, #1719), but they all were resolved by setting `assay = "RNA"`, which I have already done. 

I think this may have to do with the `scaled.data` slot of the RNA assay being empty? However, when I tried running `ScaleData` on the RNA assay prior to calling `DotPlot`, it did not resolve the issue. In response to issue #783, someone said that DotPlot uses the `data` slot, not the `scaled.data` slot, so maybe my issue is unrelated. I'm just at a loss and I'm not sure how to proceed!

Here is my code, starting from the integration step:
```R

# Integrate multiple SCTransformed objects (stored in snRNA.list)
integ_features <- SelectIntegrationFeatures(object.list = snRNA.list, nfeatures = 3000)
snRNA.list <- PrepSCTIntegration(object.list = snRNA.list, anchor.features = integ_features)
integ_anchors <- FindIntegrationAnchors(object.list = snRNA.list, normalization.method = "SCT", anchor.features = integ_features) 
snRNA.integrated <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT")

# Cluster
snRNA.integrated <- RunPCA(snRNA.integrated)
snRNA.integrated <- RunUMAP(snRNA.integrated, dims = 1:30)
snRNA.integrated <- FindNeighbors(snRNA.integrated, dims = 1:30)
snRNA.integrated <- FindClusters(snRNA.integrated, resolution = 0.8)

# Annotate clusters
cell_type <- read.csv("assigned_cell_cluster_names_v2.csv", stringsAsFactors = T)   
cell_type$cluster <- factor(cell_type$cluster)
meta_data <- snRNA.integrated@meta.data %>% 
  rownames_to_column() %>%
  left_join(cell_type, by = c("integrated_snn_res.0.8" = "cluster")) %>%
  column_to_rownames() %>%
  as.data.frame()
snRNA.integrated@meta.data <- meta_data

# Subset to remove low-quality clusters
snRNA.integrated_subset <- subset(snRNA.integrated, idents = c("low_Q"), invert = TRUE)

# Dot plot of marker genes
DotPlot(object =snRNA.integrated_subset, assay = "RNA", features = marker_gene_list, cluster.idents = TRUE)

```

And here is the resulting DotPlot with gray points for the Muc2, Fcgbp, Clca1, and Kcnip4:
[all_cell_types_dotPlot.pdf](https://github.com/satijalab/seurat/files/12677152/all_cell_types_dotPlot.pdf)

**Comment by saketkc** [comment]
Hi @mariecrane, can you try the following?
```r
DefaultAssay(snRNA.integrated_subset) <- "SCT"
DotPlot(object =snRNA.integrated_subset,  features = marker_gene_list, cluster.idents = TRUE)
```

Please feel free to re-open if you still notice issues.

**Comment by mariecrane** [comment]
Hi @saketkc, thank you for your quick reply! Setting the assay to SCT does resolve the gray dot issue, although I thought it was best to use the RNA assay for visualization? Would it be appropriate to use the SCT assay in this case?

**Comment by saketkc** [comment]
I would recommend using the SCT assay, particularly with the v2 option. Here's a vignette demonstrating these steps: https://satijalab.org/seurat/articles/sctransform_v2_vignette
