### ISSUE TITLE
Read10X multiple data doesn't add metadata. 

### ISSUE THREAD

**Issue by cartal** [satijalab/seurat#782]
Hi again, 

So I'm reading multiple 10X files from a list:

sample_1
sample_2
sample_3
sample_4
sample_5

Each 'sample_' folder contains multiple cells. What I'm trying to do is to create a Seurat object from all these files and trying to add the metadata associated to each cell type. 

The metadata looks like this:
samples run organ year
sample_1 10x_1 spleen 2018
sample_2 10x_1 liver 2018
sample_3 10x_2 spleen 2017
sample_4 10x_2 liver 2017

And I run the following command:

`multissue <- CreateSeuratObject(raw.data = samples_10x, meta.data = multissue_metadata, project = "multissue10x_10x", min.genes = 1000, min.cells = 100)`

However, the metadata sections only show 'NA' for each cell. 

How can I add the metadata to each cell in each folder of my list? or should I separate the tissues and integrate them using CCA?

**Comment by andrewwbutler** [comment]
Hi,

Just to be clear, here you're passing a matrix that is genes x cells to `raw.data` and a data frame that is cells x number_of_metadata_features to `meta.data`?

**Comment by cartal** [comment]
I was about to close this. Thanks!
