### ISSUE TITLE
Expression Values in DotPlot Function in Seurat

### ISSUE THREAD

**Issue by xhbkirby** [satijalab/seurat#783]
Hi,

I have a question about the meaning of the expression values shown in the graphs generated by the DotPlot function. By looking at the legend it seems the values are scaled. But at which level is the scaling actually applied? Are these values extracted from the `@scale.data` slot (thus will retain the adjustment from regression if any is applied)? Or are they from the `@data` slot (normalized data without any regression) and then centered and scaled across the cell groups/clusters? Thanks!

**Comment by andrewwbutler** [comment]
Hi,

The values in `DotPlot` are extracted from the `@data` slot, averaged, and then passed to `scale`. These are then Min-Maxed based on the `col.min` and `col.max` parameter values.

**Comment by aditisk** [comment]
Hello,  I have a follow up question to the explanation above. On looking at the values returned by the DotPlot function using plot$data, there are 2 columns that have expression data titled "avg.exp" and "avg.exp.scaled".

For a specific gene, if I check the average expression using the standard mean() function, this value is not matching what is reported in the "avg.exp" column for the same sample. I am using the data slot from my seurat object. Can someone please clarify why these values are not matching ? Thanks a lot.
