### ISSUE TITLE
Can the results obtained from snRNA seq and scRNA seq be analyzed together?

### ISSUE THREAD

**Issue by christophechu** [satijalab/seurat#7832]
Can the results obtained from snRNA seq and scRNA seq be analyzed together?

**Comment by saketkc** [comment]
Hi @christophechu, it is not clear what your question is - but yes, you can analyze them together by merging them or integrating them. Here is a vigentte showing how to integrate multiple scRNA-seq datasets: https://satijalab.org/seurat/articles/integration_introduction
