### ISSUE TITLE
How to determine the total count for each gene in lymphotype B 

### ISSUE THREAD

**Issue by DaliBAmor** [satijalab/seurat#7833]
Hello
I really need help !! 
I have RDS object, this file is processed , normalized ( using sct transform approach ) and clusters were identified ( in other words it ready to use seurat object ). 

My question is how to determine the number of counts for each gene in lymphocyte B in both control and patients ( I have 2 controls and 2 patients) . 
clusters are stored in ( meta.data@clusters ) and patients/control are stored in meta.data@orig.ident

Thank you in advance 

![image](https://github.com/satijalab/seurat/assets/128040777/f3dede91-5ab1-4949-8fda-8a2b64c7496b)

**Comment by mhkowalski** [comment]
Hello, you can use this ```AggregateExpression``` function to sum counts by a grouping variable.

First, I would subset to just your celltype of interest, and then sum counts for each gene, with the ```group.by``` option set as the meta data column describing case vs control status (or patient status if you'd like to sum by patient).  As a rough example,

 ```
subset <- subset(rds_obj, clusters == "celltype_of_interest")
counts.sum <- AggregateExpression(subset, group.by="patient", slot = "counts")
```

**Comment by DaliBAmor** [comment]
thank you very much for your response I'm really grateful !!

but I'm still confused because for example for patients I have 2 replicates for each type of mutations ( here I have 2 types of mutations for COPA) for example for the mutation COPA1 I have ( COPA1_1 and COPA1_2 and it's the same thing for COPA2) . So in the column orig.ident I have ( COPA1,COPA2,CTR1,CTR2) and I have another column called Sample_ID where I have (COPA1_1 , COPA1_2 , COPA2_1 , COPA2_2 , CTR1 and CTR2 ). I want to genrate a table with 4 columns with averages of counts for each gene for one type of mutation (average count per gene for COPA1 mutations for both patients together, and the same for the 2 patients who have the COPA2 mutation and finally a column for average count of control. 

Does this script correct ? :: plz correct me : 

rds_obj <- readRDS('merged_rds_obj.rds')

Idents(rds_obj) <- "clusters"

rds_obj <- subset(rds_obj, idents = "lymphocyte B", invert = FALSE)

merged_rds_obj$group <- ifelse(str_detect(rds_obj$sampleID, "COPA2"), "COPA2", ifelse(str_detect(merged_rds_obj$SampleID, "COPA1"), "COPA1", "Controls"))

separate controls from patients
Idents(rds_obj) <- "group"

controls <- subset(rds_obj, idents = "Controls", invert = FALSE)

patients_COPA1 <- subset(rds_obj, idents = "COPA1", invert = FALSE)

patients_COPA2 <- subset(rds_obj, idents = "COPA2", invert = FALSE)

counts_table <- AverageExpression(rds_obj, group.by = "group")

**Comment by DaliBAmor** [comment]
> Hello, you can use this `AggregateExpression` function to sum counts by a grouping variable.
> 
> First, I would subset to just your celltype of interest, and then sum counts for each gene, with the `group.by` option set as the meta data column describing case vs control status (or patient status if you'd like to sum by patient). As a rough example,
> 
> ```
> subset <- subset(rds_obj, clusters == "celltype_of_interest")
> counts.sum <- AggregateExpression(subset, group.by="patient", slot = "counts")
> ```
thank you very much for your response I'm really grateful !!

but I'm still confused because for example for patients I have 2 replicates for each type of mutations ( here I have 2 types of mutations for COPA) for example for the mutation COPA1 I have ( COPA1_1 and COPA1_2 and it's the same thing for COPA2) . So in the column orig.ident I have ( COPA1,COPA2,CTR1,CTR2) and I have another column called Sample_ID where I have (COPA1_1 , COPA1_2 , COPA2_1 , COPA2_2 , CTR1 and CTR2 ). I want to genrate a table with 4 columns with averages of counts for each gene for one type of mutation (average count per gene for COPA1 mutations for both patients together, and the same for the 2 patients who have the COPA2 mutation and finally a column for average count of control.

Does this script correct ? :: plz correct me :

rds_obj <- readRDS('merged_rds_obj.rds')

Idents(rds_obj) <- "clusters"

rds_obj <- subset(rds_obj, idents = "lymphocyte B", invert = FALSE)

merged_rds_obj$group <- ifelse(str_detect(rds_obj$sampleID, "COPA2"), "COPA2", ifelse(str_detect(merged_rds_obj$SampleID, "COPA1"), "COPA1", "Controls"))

separate controls from patients
Idents(rds_obj) <- "group"

controls <- subset(rds_obj, idents = "Controls", invert = FALSE)

patients_COPA1 <- subset(rds_obj, idents = "COPA1", invert = FALSE)

patients_COPA2 <- subset(rds_obj, idents = "COPA2", invert = FALSE)

counts_table <- AverageExpression(rds_obj, group.by = "group")
