### ISSUE TITLE
 How to identify barcodes from single-cell sequencing fastq files?

### ISSUE THREAD

**Issue by M-jk22** [satijalab/seurat#7839]
How can I determine the barcode from a single-cell sequencing fastq file? Is it the first 16 nucleotides of the reads? I'm quite puzzled. If you could answer this question, I would greatly appreciate it.
![26f708532528df76e1e40b9f67f0039](https://github.com/satijalab/seurat/assets/110780219/2cf09b55-5a16-4761-ac6b-94358a4be1b1)

**Comment by mhkowalski** [comment]
Hi- it depends what tech was used for scRNA seq and how the fastq files were generated. In [10x genomics](https://www.10xgenomics.com/support/single-cell-gene-expression/documentation/steps/sequencing/sequencing-requirements-for-single-cell-3), the first 16 bp's of read 1 correspond to the cell barcode, but I'm not sure for your data.

 You could always check your barcodes against a barcode whitelist, which gives a list of all possible barcode sequences (for 10X, this is included with cellranger).
