### ISSUE TITLE
[v5+BPCells] Add overwriting option to saveRDS()

### ISSUE THREAD

**Issue by frac2738** [satijalab/seurat#7844]
When I try to save an existing seurat v5+bcpcells object, I get an error because the BPCells directory cannot be overwritten:

```r
> saveRDS(exp_sample1, file = "filtered_sample1_logNorm.rds", destdir = "/mnt/disk1/BPCells_data")
Warning: Changing path in object to point to new BPCells directory location
Warning: Changing path in object to point to new BPCells directory location
Warning: Changing path in object to point to new BPCells directory location
Warning message:
Error: Error: Can't move this dir to new path: Error: [EEXIST] Failed to copy '/mnt/disk1/BPCells_data/sample1/col_names' to '/mnt/disk1/BPCells_data/sample1/col_names': file already exists
```
It works if I save to a different folder.

`write_matrix_dir` already supported the owerwriting of the BCPcells folder (`raw_feature_matrix, dir = ..., overwrite = TRUE`), and it would be handy for this behaviour to exist in  `saveRDS`

This is the code I tried to use to quickly remove  some cells from a sample before integration with other objects.

```r
exp_sample1 <- readRDS("/mnt/disk1/BPCells_data/filtered_sample1_logNorm.rds")
cellines_umi <- CellSelector(DimPlot(exp_sample1))
exp_sample1 <- subset(exp_sample1, cells = cellines_umi, invert = TRUE)

saveRDS(exp_sample1, file = "filtered_sample1_logNorm.rds", destdir = "/mnt/disk1/BPCells_data/")

```

**Comment by mhkowalski** [comment]
Hi, 

We no longer support setting the `destdir` with ```saveRDS()``` , as shown [here](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette#saving-seurat-objects-with-on-disk-layers). Please open an issue if you have other questions, thanks.
