### ISSUE TITLE
Is it possible to use a multimodal reference dataset to label clusters on a scRNAseq dataset?

### ISSUE THREAD

**Issue by juniajvs** [satijalab/seurat#7845]
Hello all,

Thank you so much for this magnificent single cell analysis tool!

I am going through your vignettes and other atlas papers trying to figure if it is possible to use a CITE-seq dataset as a reference to create and label clusters on a scRNA-seq dataset. Is there a featiure for this in Seurat?

**Comment by igrabski** [comment]
Thanks for the kind words! Yes, this is possible in Seurat; please see the [multimodal reference mapping vignette](https://satijalab.org/seurat/articles/multimodal_reference_mapping) for an example.
