### ISSUE TITLE
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :    invalid 'x' with Seurat V5

### ISSUE THREAD

**Issue by mihem** [satijalab/seurat#7850]
On this publically available dataset, `FindVariablesFeatures` worked with `Seurat_4.9.9.9060` 
https://osmzhlab.uni-muenster.de/nfs/bpcells/bpcells_debug.html.

Now with the latest github version `Seurat_4.9.9.9065` I get the following error when running `FindVariablesFeatures`

```
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :    invalid 'x' 
```

I could not reproduce this with the pbmc3k dataset, however I could process the above dataset with the previous Seurat version, and there is only the RNA assay available (earlier bug reports seem to be caused by a wrong assay https://github.com/satijalab/seurat/issues/2387#issuecomment-602903345)

Reproducible example that works with v5 `9060` but not v5 `9065`
https://osmzhlab.uni-muenster.de/nfs/bpcells/bpcells_debug.html

maybe @Gesmira, since this seems to be related to the latest changes in Seurat V5.

Thanks!

**Comment by sweet0cat** [comment]
I have the same problem, hoping for the solution.

**Comment by Gesmira** [comment]
Hi both, thanks for bringing this to our attention! A fix has been pushed to the public version of Seurat. You can restart your R session and install the new version like so:
```
remotes::install_github("satijalab/seurat", "seurat5")
```

**Comment by mihem** [comment]
Thanks. I can confirm, this little comma fixes things.
