### ISSUE TITLE
Order of Normalization and splitting layer using Seurat 5

### ISSUE THREAD

**Issue by pandaqiuqiu** [satijalab/seurat#7853]
According to the Seurat 5 tutorial, there are two different approaches:

Normalize first, then split layers by sample:
obj <- NormalizeData(obj)
obj[["RNA"]] <- [split](https://rdrr.io/r/base/split.html)(obj[["RNA"]], f = obj$Sample)

Stratify by sample first, then normalize within each sample:
obj[["RNA"]] <- [split](https://rdrr.io/r/base/split.html)(obj[["RNA"]], f = obj$Sample)
obj <- NormalizeData(obj)

Do these two methods make a difference? Which one is better?

**Comment by frac2738** [comment]
The difference between the two approaches is that in the first case you are applying the transformation to the global dataset, while in the second case each sample will be transform independently.
Which one is better, depends on what you are doing.
With `NormalizeData` the order should not matter too much, as the normalisation acts at the cell level.
Different story with scaling.

**Comment by mhkowalski** [comment]
Yes, if you are running the default `NormalizeData()` function, the values will not change if you perform normalization before or after splitting. Please see the documentation for details on how the normalized data is calculated.
