### ISSUE TITLE
How to integrate data with different levels of batches?

### ISSUE THREAD

**Issue by Yuling192** [satijalab/seurat#7856]
I want to integrate spatial datasets using v5. 
I have different batches of experiments (level 1. They were generated by the same f), each batch of experiments has several slides (level 2), and each slide has several samples.
What's the recommended way to integrate my datasets?

Thank you!

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. There may also be additional conversations there that address the question you have.

We look forward to seeing your post there - thanks for using Seurat!
