### ISSUE TITLE
how to deal with “Error in readMM(file = matrix.loc) : file is not a MatrixMarket file”

### ISSUE THREAD

**Issue by DCWdcw** [satijalab/seurat#7858]
Today, while studying Seurat for the analysis of single-cell sequencing data (from the public database GEO162577)
 I kept encountering the error message "Error in readMM(file = matrix.loc) : file is not a MatrixMarket file." I have checked the files after extracting them, and there doesn't seem to be any issue.
Could you please advise on how to resolve this problem? 
I would greatly appreciate any assistance, as this issue has been bothering me for a while.

**Comment by igrabski** [comment]
Hi, can you share exactly what you file you are trying to read, and what command you ran here? What is `matrix.loc` in this instance?

**Comment by mhkowalski** [comment]
Hi- we haven't heard back, so I'm going to close this issue for now. Please open a new issue with a detailed report of the problem you're having if you continue to experience issues.
