### ISSUE TITLE
Seurat v5 can not find DE gene identifed and the "FindAllMarkers" function points to a non-existent directory

### ISSUE THREAD

**Issue by sweet0cat** [satijalab/seurat#7859]
Hello, I am having issues with FindAllMarkers after RunUMAP, FindNeighbors and FindClusters in my resolution. However, a series of errors or warning messages appear, when i runFindAllMarkers or try to fix it 

there are some code and their errors and warning messages i received:

20231001 1300:
markers <- FindAllMarkers(object, assay = "RNA", logfc.threshold = 0.25,only.pos = TRUE)

Calculating cluster 0
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Calculating cluster 7
Calculating cluster 8
Calculating cluster 9
Calculating cluster 10
Calculating cluster 11
Calculating cluster 12
Calculating cluster 13
Calculating cluster 14
Calculating cluster 15
Calculating cluster 16
Calculating cluster 17
Calculating cluster 18
Calculating cluster 19
Calculating cluster 20
Calculating cluster 21
Calculating cluster 22
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 1 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 2 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 3 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 4 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 5 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 6 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 7 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 8 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 9 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 10 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 11 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 12 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 13 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 14 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 15 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 16 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 17 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 18 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 19 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 20 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 21 versus all:	data layers are not joined. Please run JoinLayers
Warning: When testing 22 versus all:	data layers are not joined. Please run JoinLayers

then i try to fix this worning and "no DE genes identified" by function "JoinLayers":

20231001 1305:
object <- JoinLayers(object)
> markers <- FindAllMarkers(object, assay = "RNA", logfc.threshold = 0.25,only.pos = TRUE)
Calculating cluster 0
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Calculating cluster 7
Calculating cluster 8
Calculating cluster 9
Calculating cluster 10
Calculating cluster 11
Calculating cluster 12
Calculating cluster 13
Calculating cluster 14
Calculating cluster 15
Calculating cluster 16
Calculating cluster 17
Calculating cluster 18
Calculating cluster 19
Calculating cluster 20
Calculating cluster 21
Calculating cluster 22
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 1 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 2 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 3 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 4 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 5 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 6 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 7 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 8 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 9 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 10 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 11 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 12 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 13 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 14 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 15 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 16 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 17 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 18 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 19 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 20 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 21 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1
Warning: When testing 22 versus all:	Missing directory: D:\16.DNT\32.Seurat5\integrate.lognorm\aDNT1

**Comment by sweet0cat** [comment]
this problems are:
1. why there have not DE genes identified?
2. why this directory missing?


Actually, the name of directory,“integrate.lognorm”, is my file of preconditioning of this seurat object. However, i never set this directory to any default diectory such as setwd("thisdirectory") in my codes.Interestingly, the missing path pointed by this function is not on the same hard-drive as the working directory I set up.

then ,i try to copy “integrate.lognorm” and its files to this missing directory:
20231001 1330:

>  markers <- FindAllMarkers(object, assay = "RNA", logfc.threshold = 0.25,only.pos = TRUE)
Calculating cluster 0
Loading required package: BPCells
Loading required package: BPCells
Loading required package: BPCells
Loading required package: BPCells
Loading required package: BPCells
Loading required package: BPCells
Loading required package: BPCells
Loading required package: BPCells
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Calculating cluster 7
Calculating cluster 8
Calculating cluster 9
Calculating cluster 10
Calculating cluster 11
Calculating cluster 12
Calculating cluster 13
Calculating cluster 14
Calculating cluster 15
Calculating cluster 16
Calculating cluster 17
Calculating cluster 18
Calculating cluster 19
Calculating cluster 20
Calculating cluster 21
Calculating cluster 22
Warning: No DE genes identified
There were 50 or more warnings (use warnings() to see the first 50)

> warnings()
Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
2: In sqrt(sigma2) : NaNs produced
3: In sqrt(sigma2) : NaNs produced
4: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
5: In sqrt(sigma2) : NaNs produced
6: In sqrt(sigma2) : NaNs produced
7: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
8: In sqrt(sigma2) : NaNs produced
9: In sqrt(sigma2) : NaNs produced
10: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
11: In sqrt(sigma2) : NaNs produced
12: In sqrt(sigma2) : NaNs produced
13: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
14: In sqrt(sigma2) : NaNs produced
15: In sqrt(sigma2) : NaNs produced
16: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
17: In sqrt(sigma2) : NaNs produced
18: In sqrt(sigma2) : NaNs produced
19: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
20: In sqrt(sigma2) : NaNs produced
21: In sqrt(sigma2) : NaNs produced
22: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
23: In sqrt(sigma2) : NaNs produced
24: In sqrt(sigma2) : NaNs produced
25: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
26: In sqrt(sigma2) : NaNs produced
27: In sqrt(sigma2) : NaNs produced
28: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
29: In sqrt(sigma2) : NaNs produced
30: In sqrt(sigma2) : NaNs produced
31: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
32: In sqrt(sigma2) : NaNs produced
33: In sqrt(sigma2) : NaNs produced
34: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
35: In sqrt(sigma2) : NaNs produced
36: In sqrt(sigma2) : NaNs produced
37: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
38: In sqrt(sigma2) : NaNs produced
39: In sqrt(sigma2) : NaNs produced
40: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
41: In sqrt(sigma2) : NaNs produced
42: In sqrt(sigma2) : NaNs produced
43: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
44: In sqrt(sigma2) : NaNs produced
45: In sqrt(sigma2) : NaNs produced
46: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
47: In sqrt(sigma2) : NaNs produced
48: In sqrt(sigma2) : NaNs produced
49: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'
50: In sqrt(sigma2) : NaNs produced


when i copy files of "integrate.lognorm" to this miss directory and run FindAllMarkers, the speed of computer code execution has slowed down visually. sadly, it is not work.

hoping your reply, tks

**Comment by sweet0cat** [comment]
this bug can be solve by update seurat to the Latest version meanwhile create and copy bpcells files to this missing directory. it is working now.

**Comment by Gesmira** [comment]
Hi, 
Glad you were able to resolve the issue. In the latest Seurat version, this should be functioning normally. Closing now, but feel free to reopen if you run into further problems related to this.

**Comment by sweet0cat** [comment]
> To add on, with Seurat v5, the "FindAllMarkers" function is still slow, taking ~15 min per cluster with an "integrated" default assay (~350,000 cells). Is it expected or is there a way to speed up the process for 12 clusters (~300,000 cells)? I am using the below plan for executing my script locally.
> 
> ```
> library(future)
> plan("multisession", workers = 12)
> options(future.globals.maxSize = 15000 * 1024^2)
> ```
> 
> A supplementary question, what default assay is best for identifying the cluster-specific markers, "integrated" or "SCT"?

Thank you for your reply. You can use the r package "BPCell" package for seurat v5, which can significantly reduce running memory and improve running speed. Please refer to the official documentation for specific code and usage, which may be useful to you.

**Comment by samuel-marsh** [comment]
Hi @RajneeshSrivastava,

Just as note to question in your last post.  Integrated assay should not be used for DE analysis.  You should either use RNA or SCT assays. 

Best,
Sam

**Comment by urual** [comment]
Hello, i know you may have many way to solve this problem.But, i also want to share the way that solves the trouble by "joinlaryers()" function.You can solves this wrong by running "object <- joinlaryers(object)" after using FindAllMarkers.
P.S. object is your scRNA-seq data of Seurat.
