### ISSUE TITLE
[v5+BPCells] How to change the location of the BPCells directory from different computers?

### ISSUE THREAD

**Issue by frac2738** [satijalab/seurat#7863]
I have analysed a dataset on `machine A` and I now need to move the processed data to `machine B`.
As the matrix are stored to disk and linked to a path on `machine A`, I was wondering how to change those paths, and point them to a location on machine B, without starting from scratch on `machine B`.

Basically I would like to go from 

```r
> srt_Object[["RNA"]]$counts
Loading required package: BPCells
24889 x 7361 IterableMatrix object with class RenameDims

Row names: AL627309.1, AL627309.5 ... AC007325.4
Col names: C20-59-07-C029_AAACCCAAGTTCGCAT-1, C20-59-07-C029_AAACCCAGTACCCGAC-1 ... C20-59-07-C029_TTTGTTGTCAGCGCGT-1

Data type: uint32_t
Storage order: column major

Queued Operations:
1. Load compressed matrix from directory /mnt/disk1_on_machineA/projects/03_processed_data/BPCells_data/sample1
2. Select rows: 1, 3 ... 27763 and cols: 4, 9 ... 16081
3. Reset dimnames
```
to 

```r
> srt_Object[["RNA"]]$counts
Loading required package: BPCells
24889 x 7361 IterableMatrix object with class RenameDims

Row names: AL627309.1, AL627309.5 ... AC007325.4
Col names: C20-59-07-C029_AAACCCAAGTTCGCAT-1, C20-59-07-C029_AAACCCAGTACCCGAC-1 ... C20-59-07-C029_TTTGTTGTCAGCGCGT-1

Data type: uint32_t
Storage order: column major

Queued Operations:
1. Load compressed matrix from directory /storage_on_remote_server/sample1
2. Select rows: 1, 3 ... 27763 and cols: 4, 9 ... 16081
3. Reset dimnames
```

Is it possible?

**Comment by Gesmira** [comment]
Yes, you can use the function saveRDS() with specific BPCells arguments as explained [here](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette#saving-seurat-objects-with-on-disk-layers).
```
saveRDS(
  object = srt_Object,
  file = "obj.Rds",
  destdir = "your/path", 
  relative = TRUE
)
```

This will save the object and the BPCells matrices to a folder and adjust the pointer path in the object to the moved folder. I would recommend setting `relative = TRUE` if you are going to be moving machines. If you then copy this folder to a new machine and keep them in the same folder, the new counts should be accessed from the relative path and you can confirm the path to the directory in the same way you have done above. 

Alternatively, you could always reset it with `srt_Object[["RNA"]]$counts <- open_matrix_dir("/path/to/BP_dir")`.

**Comment by frac2738** [comment]
Thanks Gesmira,
I didn't know about the `relative` argument.
It might help a lot if you could mention its existence in the BPCells vignette too.

I set ` relative = TRUE` and it seems to do the job.
Thanks.
