### ISSUE TITLE
`DoHeatmap()` being able to do hierarchical clustering and adjusting column width for cell groups

### ISSUE THREAD

**Issue by zandigohar** [satijalab/seurat#7864]
Dear developers,

It would be perfect and very helpful if the Seurat function `DoHeatmap()` was also able to do hierarchical clustering of row/column/both. 
For instance, `pheatmap` has the mentioned feature by setting `cluster_rows` and/or `cluster_cols` to `TRUE`.

Also if users could possibly change the column width of cell groups (make cell proportions default as `NULL`) or have the option to make them even-sized instead of subsampling their data, that could make small clusters more visible and pretty helpful.

Thanks for your great work!

**Comment by mhkowalski** [comment]
Hi @zandigohar, 

Thank you so much for the suggestion, and sorry for our delayed response. We agree that these would be really nice enhancements to the current `DoHeatmap` function. Unfortunately, our bandwidth is limited so we won’t be able to include this in our roadmap at this time, but we'll note this and consider adding this functionality in the future.

We cannot overstate how much we appreciate your input and we encourage you to keep sharing your ideas. If you have other ideas, please don’t hesitate to let us know.
