### ISSUE TITLE
SCTransform and batch effect

### ISSUE THREAD

**Issue by miguecass** [satijalab/seurat#7866]
Hi,

I have 26 different samples (single cell datasets, so for me its like having 26 batches). Each cell is classified in 4 different classes across all samples and I would like to compare each of these classes against each other. Therefore, I need a DE gene list to perform pathway enrichment. However, I feel a bit lost with the process.

First, I normalized each sample separately and then I am wondering if once merging the datasets if I should SCT normalize again. Because just merging the batch effect of each sample should still be present, right? Removing the batch with any batch removing algorithm is not an option for me (Combat, IntegrateData, etc...). I have not seen an example of why we should not use SCTransform in all the data together. How would you suggest me to get rid of (or reduce) batch effect if I have 26 different samples and I want to perform DE analysis?

So far, if I merge the SCTransform object and I run FindAllMarkers, should be fine?

Thanks in advance,
Best,

**Comment by longmanz** [comment]
Hi ,
Even if you run SCTransform() after merging the datasets, and use `SCTransform(..., vars.to.regress = "batch")` to try to regress out the batch effect, your data might still contain batch effect in the end.  "vars.to.regress" only works if the batch effect only affect the mean expression of each genes in your 26 samples, but this is usually not true. Batch effect also affects your sequencing depth in each sample. 
We would recommend run SCTransform separately for each sample, and then run PrepSCTFindMarkers() to harmonized their seq depths and run DE analyses. see details https://github.com/satijalab/seurat/issues/7407
Additionally, it seems like you want to integrate your datasets as well. If that is the case, you should also run SCTransform separately and then run IntegrateData. Then you can perform your RunUMAP() and FindCluster() to define clusters and run FindAllMarkers().

**Comment by RajneeshSrivastava** [comment]
Hi
A similar question is raised previously (https://github.com/satijalab/sctransform/issues/55) however require more clarity.

Let me reiterate the problem applicable to my case:

Here is the work design that I have:
> Multi-organ (n=8,  e.g. brain, heart, liver, kidney... etc)
                 >Tissue (<=2, e.g. brain =list("midbrain", "hypothalamus")) 
                                  >Condition (2) (Control, Treatment)
                                                   >Samples (<=5)

Although I do expect, a varying cell type composition, I am particularly interested in common cell types across multi-organ and conducting a downstream analysis utilizing the resource.

My intent is to utilize seurat5 with the [BPCells](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette) function. 
If I understand correctly, the approach (in seurat5) would be:
>Create SeuratObject for each sample and do [SCTTransform](https://satijalab.org/seurat/articles/sctransform_vignette) 
            >[Integrate](https://satijalab.org/seurat/articles/seurat5_integration) Seurat objects per tissue [last section]
                        > [Merge](https://satijalab.org/seurat/articles/seurat5_merge_vignette) all objects at the organ level
                                     >Subset cell type(s) of interest
                                                 >Downsteam analysis

Now, my questions are as follows:
How to handle batch effect in multi-organ single-cell data?
If SCT is not applied correctly as above, when to do SCTransform in my case?
After merging the Seurat Objects at organ level, should I re-run SCT and a follow up PCA or just PCA?

I might be wrong in explaining the steps. Please do correct and would like to request for any recommended step or pseudocode to utilize BPCells+seurat5 pipeline for my case, covering all steps would be great. I bet it will reduce a lot of confusions while migrating from seurat V4 to V5

Thank you in advance.

With regards,
Rajneesh

**Comment by alifarhat40** [comment]
What is interesting to me is that sometimes SCTransform does "batch correction" without needing for further integrations. So I am confused on when to do integrations and when no to.
