### ISSUE TITLE
Featureplot after mapping query to reference

### ISSUE THREAD

**Issue by diegorunav** [satijalab/seurat#7867]
After mapping a seurat object to a reference, I wanted to check the prediction values of some of the passed data (in this case the cell_class_label, which has 3 categories "GABAergic", "Glutamaterigc" and "Non-Neuronal") and then filter out of my seurat object the non-neuronal cells. 
Before removing:
`
# Create vector of classes present in neus
cell_classes <- unique(neus@meta.data$predicted.class_label)

for (i in 1:3) {
  print(
    FeaturePlot(
      object = neus,
      features = cell_classes[i],
      reduction = "ref.umap",
      cols = c("lightgrey", "darkgreen"),
      ncol = 1
    ) +
    theme(plot.title = element_text(size = 10))
  )
}
`
![image](https://github.com/satijalab/seurat/assets/127498480/e24037be-209b-47de-b6de-ea3ceaac2a61)
![image](https://github.com/satijalab/seurat/assets/127498480/3a22846a-aec9-45df-94b7-ba648c3ac6ef)
![image](https://github.com/satijalab/seurat/assets/127498480/56c9f71c-d67f-42c6-be17-2ba2131b983b)

After removing non-neuronal cells:

`
# Remove Non-neuronal & check
neus <- subset(neus, subset = predicted.class_label == "Non-Neuronal", invert =T)

# Check prediction plots per class
DimPlot(neus, reduction = "ref.umap", group.by = "predicted.class_label", label = TRUE, label.size = 3, repel = TRUE)

for (i in 1:3) {
  print(
    FeaturePlot(
      object = neus,
      features = cell_classes[i],
      reduction = "ref.umap",
      cols = c("lightgrey", "darkgreen"),
      ncol = 1
    ) +
    theme(plot.title = element_text(size = 10))
  )
}

`
![image](https://github.com/satijalab/seurat/assets/127498480/acba2238-24bf-40e0-a24c-51aa4f122cf7)
![image](https://github.com/satijalab/seurat/assets/127498480/a8c88896-2300-4f12-9d21-0f8ba34c98e0)
![image](https://github.com/satijalab/seurat/assets/127498480/23b622bf-dbbf-4335-991e-1cd04ae6a03b)

So as you see, although there dosn´t seem to be any "Non-Neuronal" cells. the FeaturePlot still delivers some cells with a prediction score. I would llike to know where this data is coming from.
I also tried to change the default assay to "prediction.score.class_label" with out any success. 

`
DefaultAssay(neus) <- "prediction.score.class_label"

FeaturePlot(neus, features = cell_classes, reduction = "ref.umap",  cols = c("lightgrey", "darkgreen"))
`
![image](https://github.com/satijalab/seurat/assets/127498480/8c511775-43a7-4941-8036-ac12cf04738a)

Also, why does it have a different scale (0.0 to 0.5) ?

Thanks in advance for any kind of help!

**Comment by mhkowalski** [comment]
Hello, 

If I understand your question correctly, you are wondering why some cells that are labeled as Non-Neuronal have a non-zero prediction score for the Non-neuronal celltype. Some cells could have a non-zero prediction score for Non-neuronal, but are not annotated as Non-neuronal, because they have a higher prediction score for something else (here it looks like many of these cells are annotated as Glutamatergic). This also explains why the scale is different, because the max non-neuronal score on the neuronal cell types is lower, which makes sense in this context. 

Hope this is helpful!

**Comment by RajneeshSrivastava** [comment]
@mhkowalski
Not sure, if the cols gradient function is fabricated in FeaturePlot of seurat_v5.
All it shows in v5, is binary (no red, figure below), that was not the case with v4.

Please clarify. Thank you! 

```
FeaturePlot(test,"VFS1",cols=c("grey","red","black"))
```
![image](https://github.com/satijalab/seurat/assets/34284131/cf8cbca6-eae3-4d8d-9c23-c90b4d14c419)
