### ISSUE TITLE
Error in CalcPerturbSig 

### ISSUE THREAD

**Issue by rach88** [satijalab/seurat#7871]
Hi,
I am running into the following error with Mixscape while analysing my dataset. Here's the code:

temp.seu <- CalcPerturbSig(object = temp.seu, assay = "RNA", slot = "data", gd.class ="gene", nt.cell.class = "NT",
  reduction = "pca", ndims = 40, num.neighbors = 20, split.by=NULL, new.assay.name = "PRTB")

Error message:
Processing rep1
Error in nn2(data = numeric(0), query = c(-6.99258402643058, 9.8575419710391,  : 
 Cannot find more nearest neighbours than there are points

My dataset contains ~4% non targeting cells. Any troubleshooting insights are greatly appreciated!

**Comment by longmanz** [comment]
hi,
This might happen when there is not enough NT neighbors for some of the cells (given that you only have ~4% NT cells). You may try to use a smaller num.neighbors (e.g., 10) to re-run your CalcPerturbSig() to see if the error goes away. Let me know if you still encounter the same error and I will reopen the issue.

**Comment by strawberry098** [comment]
I'm having the same issue.  I reduced `num.neighbors` and re-run `CalcPerturbSig()`, but I'm still getting the same error
