### ISSUE TITLE
Does runfastMNN require rebatching in single-cell subpopulations?

### ISSUE THREAD

**Issue by UEATTOOMUCH260** [satijalab/seurat#7878]
Hi,
I am analyzing single-cell data processed with RunFastMNN. When I use `subset` to extract a subgroup of cells from the data, do I need to re-perform batch correction?
Here's my current approach:

```r
TCells_sub <- subset(scRNA_MNN_105res1, ident= "T cells")
Tsublist <- SplitObject(TCells_sub, split.by = "category")
Tsublist <- lapply(Tsublist, FUN = function(x) NormalizeData(x, assay = "RNA",verbose = FALSE))
Tsublist <- lapply(Tsublist, FUN = function(x) FindVariableFeatures(x, assay = "RNA",verbose = FALSE) )

scRNA_MNN <- RunFastMNN(object.list = Tsublist, d = 100)
scRNA_MNN2 <- RunUMAP(scRNA_MNN, reduction = "mnn", dims = 1:100)
scRNA_MNN2 <- FindNeighbors(scRNA_MNN2, reduction = "mnn", dims = 1:100)
scRNA_MNN2 <- FindClusters(scRNA_MNN2)
```
Is this a reasonable way to handle it?
Could you please give me some advice?

Thanks!!

**Comment by igrabski** [comment]
Hi, if you have already performed batch correction, you shouldn't need to perform it again from just subsetting a set of cells.
