### ISSUE TITLE
Seurat QC automation for scRNAseq or imaging-based single-cell resolution spatial data

### ISSUE THREAD

**Issue by estellad** [satijalab/seurat#7883]
Hi there, 

Rather than an issue, this is more of a pull request. 

[Here is a package I wrote](https://github.com/estellad/SeuratQCUtils), adapting QC methods in the OSCA book from the Bioconductor community to automate QC for Seurat object, e.g. assay = "RNA" (scRNAseq - Chromium), or "Xenium" (Xenium), or maybe also for "Spatial" (Visium)...

Please let me know if you want to merge this package into main Seurat, or should I make it a CRAN package.

Sincerely,
Estella

**Comment by igrabski** [comment]
Hi Estella, thanks for bringing this to our attention! This sounds like great work -- we would recommend you make it a separate CRAN package.
