### ISSUE TITLE
RNA is not an assay present in the given object. Available assays are: 

### ISSUE THREAD

**Issue by yinzhenx216** [satijalab/seurat#7884]
can't NormalizeData

**Comment by Gesmira** [comment]
Can you share `sessionInfo()` and your code to create the object and the full errors you run into?

**Comment by Gesmira** [comment]
Hi, 
Based on the fact that I just accidentally reproduced this, it seems that you have Seurat v4 installed with SeuratObject v5. 
Please update your Seurat version with: 
`remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)`
