### ISSUE TITLE
Atomic Sketch Integration. No longer supported, again?

### ISSUE THREAD

**Issue by HuXuantao** [satijalab/seurat#7887]
Hi,

I recently tried to use the Atomic sketch integration for scRNA-seq data. However, `remotes::install_github("satijalab/seurat", "feat/dictionary")`  failed. And I found that 
 feat/dictionary content and atomic_integration vignette have been removed from Github. Does it mean it is no longer recommended to use this approach for integration?

**Comment by HuXuantao** [comment]
@yuhanH

**Comment by Gesmira** [comment]
Hi, 
The sketch integration vignette is now [here](https://satijalab.org/seurat/articles/parsebio_sketch_integration) and the corresponding code is part of Seurat v5. Installation instructions are [here](https://satijalab.org/seurat/articles/install).
