### ISSUE TITLE
Error: Object 1 assay - SCT has not been processed by PrepSCTIntegration - after having SCTransform and PrepSCTIntegration run

### ISSUE THREAD

**Issue by jawi005** [satijalab/seurat#7889]
Dear Seurat team,

I have a split seurat object with a list of 2 elements. To integrate these data sets I run SCTransform() followed by PrepSCTIntegration() without problems. When I want to run FindIntegrationAnchors() this error occurs: 

>Error: Object 1 assay - SCT has not been processed by PrepSCTIntegration. Please run  PrepSCTIntegration prior to FindIntegrationAnchors() if using assays generated by SCTransform.

My code is: 

split_seurat_ctr <- SplitObject(seurat_phase, split.by = "sample")[1:2]
 
split_seurat_ctr<- lapply(X = split_seurat_ctr, FUN = function(x) {
  x <- SCTransform(x, vars.to.regress = c("percent.mt", "percent.clp"))
}) 
 
#-------------------------Integration---------------------------
 
 
integ_features_contr <- SelectIntegrationFeatures(object.list = split_seurat_ctr,
                                            nfeatures = 3000)

#---------Prepare the SCT list object for integration

integrate_contr <- PrepSCTIntegration(object.list = split_seurat_ctr,
                                      assay = "SCT",
                                      anchor.features = integ_features_contr)

 
integrate_contr <- FindIntegrationAnchors(object.list = split_seurat_contr,
                                          normalization.method = "SCT",
                                          anchor.features = integ_features_contr)
 
 The default assay is set to "SCT" 

I hope you can help me, 
thanks 
Jana

**Comment by saketkc** [comment]
Hi @jawi005, you should be passing `integrate_contr` (the object output after running `PrepSCTIntegration`) to `FindintegrationAnchors` and. not `split_seurat_contr`.
