### ISSUE TITLE
AverageExpression() silently replaces "_" with "-" in final column names

### ISSUE THREAD

**Issue by ccasar** [satijalab/seurat#7893]
Hi, 
not a major problem, but an annoying one:

If any label, passed with idents or the `group.by` argument, contains an underscore, it will be silently replaced with a minus during the `AverageExpression` calculation. 

```r
library(Seurat)
pbmc_small$groups2 <- c(rep("A_B",40),rep("C_D",40))

avg_ex <- AverageExpression(pbmc_small, group.by = c("groups2"))
colnames(avg_ex$RNA)

data[, 1]A-B data[, 1]C-D 
       "A-B"        "C-D"
```

I'm currently using Seurat version `4.9.9.9067` and I can't remember this happening before.

**Comment by mhkowalski** [comment]
Hi, thanks for reporting this. 

This is new, and was implemented in the case that you specify `group.by` with multiple elements.  In this case, the new column names reflect the identity of both grouping variables, separated by an underscore.  Therefore, we replace "_" with "-"  in the original labels to avoid any confusion. We are in the process of adding a message to indicate that this is happening (as well as updating the documentation for `AverageExpression`).

```
head(AverageExpression(object = pbmc_small, group.by = c('groups', 'groups2'))$RNA)
6 x 4 sparse Matrix of class "dgCMatrix"
            g1_A-B     g1_C-D    g2_A-B    g2_C-D
MS4A1     40.68298   1.325557 127.78656   .      
CD79B     50.67178   9.483066 113.72065  16.21719
CD79A     82.91678   8.646396 128.26261   .      
HLA-DRA  391.22353 499.397892 548.77477 197.47803
TCL1A     28.66519   3.764352 110.39221   .      
HLA-DQB1  54.23565  56.346087  86.13789  24.78854
```

**Comment by mhkowalski** [comment]
Closing now, as the latest version of seurat5 contains a message to indicate that this is happening.
