### ISSUE TITLE
Issue with scVI integration: ImportError from pydantic.main

### ISSUE THREAD

**Issue by jwweii** [satijalab/seurat#7897]
Description:
While running the scVI integration in Seurat, I encountered an ImportError which stated: cannot import name 'ModelMetaclass' from 'pydantic.main'.

Details:
Upon further investigation, I found a discussion thread at [pydantic GitHub issue #6381](https://github.com/pydantic/pydantic/issues/6381). It indicates that ModelMetaclass was removed from pydantic post the 2.0 release.

Temporary Solution:
As a workaround, I downgraded pydantic to version 1.8, which resolved the error. It might be beneficial to consider this compatibility issue or update the requirements accordingly.

**Comment by igrabski** [comment]
Hi, can you confirm whether this issue still persists using the latest version of Seurat? If so, please feel free to open a new issue about this.
