### ISSUE TITLE
SeuratV5-BPcells reference map for RNA and ATAC

### ISSUE THREAD

**Issue by LucaTucciarone** [satijalab/seurat#7898]
Hi, 
I am interested in using SeuratV5 and the package BPcells to reference map snATACseq over a multiomics object. Seems like there is no vignette for this, but it would be very helpful. 

Also, any vignette regarding BPcells ATAC and Seuratv5?

**Comment by igrabski** [comment]
Thanks for the suggestion! Unfortunately, our bandwidth is limited so we won’t be able to include this in our roadmap at this time. We’ll circle back to this once our resources allow.
