### ISSUE TITLE
Request for support for New Dataset in CosMx

### ISSUE THREAD

**Issue by ayumatsubo** [satijalab/seurat#7901]
Thank you for always creating useful tools. 

I use CosMx, but the latest output differs from the NSCLC dataset and is available in this format at the following URL (https://nanostring.com/products/cosmx-spatial-molecular-imager/human-liver-rna-ffpe-dataset/). It would be greatly appreciated if, in the next version of Seurat, you could make it compatible with this format.

If possible, please consider adding a protocol to integrate two or more different datasets. This would be particularly valuable for conducting niche or cluster analysis on multiple samples. 

 If you have any more questions or need further assistance, feel free to ask. 

Thank you in advance!

Ayumu

**Comment by dpcook** [comment]
Not a direct solution, but note that Nanostring has a custom module on their GitHub to export flat files from AtoMx in a format consistent with the NSCLC and TAP data.

https://github.com/Nanostring-Biostats/CosMxDACustomModules

**Comment by ayumatsubo** [comment]
I'm sorry for late response.

This information really help me, and I was able to export the dataset as flat files form.

Thank you very much.
