### ISSUE TITLE
Integrate multiple scRNA-seq datasets onto an existing UMAP

### ISSUE THREAD

**Issue by sallyseullee-0821** [satijalab/seurat#7903]
Hi, 
I previously successfully clustered scRNA-seq data from 38 different samples, all collected from different batches.
The steps I followed include normalization with SCTransform, selecting 3000 integration features, running PCA, and integrating the data using 'PrepSCTIntegration' and 'FindIntegrationAnchors'. Here is the code I used: 

```
#~~~~~~~ Normalization and Scaling ~~~~~~~~
# SCTransform on each sample
aging_list <- SplitObject(aging, split.by = "hpap_id")
for (i in 1:length(aging_list)) {
  aging_list[[i]] <- SCTransform(aging_list[[i]], method = "glmGamPoi", vars.to.regress = "percent.mt", verbose = FALSE)
}
#~~~~~~~ Perform integration from different samples ~~~~~~~
# features for integration
features <- SelectIntegrationFeatures(object.list = aging_list, nfeatures = 3000)
aging_list <- lapply(X = aging_list, FUN = function(x) {
  x <- RunPCA(x, features = features)
})
aging <- PrepSCTIntegration(aging_list, anchor.features = features)
anchors <- FindIntegrationAnchors(aging, normalization.method = "SCT", reduction = "rpca", anchor.features = features)
aging.integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
aging.integrated <- RunPCA(aging.integrated, verbose = TRUE)
aging.integrated <- RunUMAP(aging.integrated, reduction = "pca", dims = 1:30, verbose = FALSE)
aging.integrated <- FindNeighbors(aging.integrated, dims = 1:30, verbose = FALSE)
aging.integrated <- FindClusters(aging.integrated <- FindClusters(aging.combined.sct.30, resolution = 0.8, method = "igraph", verbose = FALSE)
```
Now, I have an additional 18 samples that I would like to map onto the existing UMAP. 
I reviewed the integration and mapping vignettes and some past Github issues, but I am still uncertain of the best approach to use.  

Specifically, I am considering processing the new samples in the same way - SCTransformation and PCA for each of the additional 18 samples individually. 
And then merge them into one seurat object (merged_query) and follow this instruction provided in the vignette. 
```
anchors <- FindTransferAnchors(reference = aging.integrated, query = merged_query,
    dims = 1:30, reference.reduction = "pca")
predictions <- TransferData(anchorset = anchors, refdata = aging.integrated$celltype,
    dims = 1:30)
merged_query <- AddMetaData(merged_query, metadata = predictions)
```
Can someone please confirm whether this is a recommended approach? 
Additionally, should the default assay for 'aging.integrated' be "integrated" and the default for the 'merged_query' be "SCT"? 

I would really appreciate your guidance!

**Comment by saketkc** [comment]
Hi @sallyseullee-0821, you should be able to do this following the instructions in [this vignette](https://satijalab.org/seurat/articles/integration_mapping#unimodal-umap-projection) using `MapQuery`.
