### ISSUE TITLE
GetAssayData() with Seurat v5 object

### ISSUE THREAD

**Issue by MWRR** [satijalab/seurat#7905]
When I run GetAssayData()  using Seurat v5 object
`sce <- GetAssayData(object = obj, assay = "RNA")`

 to use SingleR package for annotation. I got the error

> Error in `GetAssayData()`:
> ! GetAssayData doesn't work for multiple layers in v5 assay.

**Comment by Gesmira** [comment]
In Seurat v5, we recommend using `LayerData()`. However, if you have multiple layers, you should combine them first with `obj <- JoinLayers(obj)`, then you can use either function.
