### ISSUE TITLE
AddChromatinModule returns metadata with NA

### ISSUE THREAD

**Issue by Ryuichi30** [satijalab/seurat#7906]
Hi,

I have performed AddChromatinModule function to add chromatin accessibility variation in genomic regions with some transcription factor binding to metadata.
`All3 <- AddChromatinModule(All3, features=dfdf, genome=BSgenome.Mmusculus.UCSC.mm10, assay = NULL, verbose = TRUE)`

Then, I noticed that some cells have NA values in the metadata.

Due to the NA values, FeaturePlots using the metadata returns the following error.
`FeaturePlot(All3, features = features, pt.size = 0.1, max.cutoff = "q90", reduction = 'umapharmonyATAC')+ labs(color = "Deviation")`
`Error in quantile.default(x = data, probs = this.quantile) :  missing values and NaN's not allowed if 'na.rm' is FALSE`

Does AddChromatinModule function sometimes create NA values?
If so, please let me know how to perform FeaturePlot using the metadata including NA values.

Thanks,
Ryuichi

**Comment by saketkc** [comment]
Hi @Ryuichi30, you should open an issue on [signac repo](https://github.com/stuart-lab/signac)
