### ISSUE TITLE
Analysis with quantitative phenotypes

### ISSUE THREAD

**Issue by corunesa** [satijalab/seurat#7907]
Hi! I wanted to find association between gene expression in a certain cluster and a quantitative variable. I want to know if there is any gene expression in my cluster 11 that is associated with a numerical scale. 
I have obtained the expression values of cluster 11 with GetAssayData: 

cells.use <- WhichCells(object = seurat.integrated, ident = 11)
expr <- GetAssayData(object = seurat.integrated, assay.type = "integrated", slot = "data")[, cells.use]
expr <- as(Class = 'matrix', object = expr)

But how can the cell know to which patient it corresponds?
Then I wanted to run a regression, I don't know if this is the best method to evaluate this. 

Thank you all very much in advance!

**Comment by longmanz** [comment]
Hi,
1. You should not use the "integrated" assay to extract the expression data. You should use the "RNA" assay instead. 
`expr <- GetAssayData(object = seurat.integrated, assay.type = "RNA", slot = "data")[, cells.use]`
2. To get the cells' patient identity, you can command like this
`colnames(seurat.integrated)[seurat.integrated$sample == "patient ID"]`. You need to substitute the 'sample' and 'patient ID' to the actual column name and patient ID. 
3. To run regression, you can use lm(), glm() , or glm.nb() function in R.
