### ISSUE TITLE
generating pseudobulk data from spatial

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#7909]
Is there a method of generating pseudobulk data from spatial object? or is the only way integrating all spatial data together?

**Comment by longmanz** [comment]
Hi, 
If you want to generate pseudobulk data based on cell-type or donor identity, you can use [AggregateExpression()](https://satijalab.org/seurat/reference/aggregateexpression)
As for integration of multiple spatial data, you can refer to this [vignette](https://satijalab.org/seurat/articles/spatial_vignette.html).
