### ISSUE TITLE
Seurat v5, how to project sketched data in multiple layers into full datasets?

### ISSUE THREAD

**Issue by Lin13432** [satijalab/seurat#7910]
Hi,

I want to used sketched data to run some integrative analysis like scvi-tools, it works well, but when I extend results to the full datasets, the function ProjectData() does not work because " ! GetAssayData doesn't work for multiple layers in v5 assay.".

So how can I do that?

**Comment by Lin13432** [comment]
I tried to follow the tutorial "Sketch integration using a 1 million cell dataset from Parse Biosciences"https://satijalab.org/seurat/articles/parsebio_sketch_integration, but when I run obj <- ProjectIntegration(object = obj, sketched.assay = "sketch", assay = "RNA", reduction = "integrated.scvi"), I got error:
50000 atomic cells identified in the sketched.assay

Correcting embeddings

Warning message in LayerData.Assay5(object = object[[sketched.assay]], layer = layers[i], :
“multiple layers are identified by data.Pool1 data.Pool3 data.Pool4 data.Pool5 data.Pool6 data.Pool7 data.Pool8
 only the first layer is used”
Error in .subscript.2ary(x, , j, drop = TRUE): subscript out of bounds
Traceback:

1. ProjectIntegration(object = obj, sketched.assay = "sketch", assay = "RNA", 
 .     reduction = "integrated.scvi")
2. UnSketchEmbeddings(atom.data = LayerData(object = object[[sketched.assay]], 
 .     layer = layers[i], features = features), atom.cells = cells.sketch, 
 .     orig.data = LayerData(object = object[[assay]], layer = layers[i], 
 .         features = features), embeddings = Embeddings(object = object[[reduction]]), 
 .     sketch.matrix = sketch.matrix)
3. atom.data[, atom.cells]
4. atom.data[, atom.cells]
5. .subscript.2ary(x, , j, drop = TRUE)
6. stop("subscript out of bounds")

How to solve this error?

**Comment by Lin13432** [comment]
This is the object:

An object of class Seurat 
38118 features across 337598 samples within 2 assays 
Active assay: sketch (19059 features, 2000 variable features)
 21 layers present: data.Pool1, data.Pool3, data.Pool4, data.Pool5, data.Pool6, data.Pool7, data.Pool8, counts.Pool1, counts.Pool3, counts.Pool4, counts.Pool5, counts.Pool6, counts.Pool7, counts.Pool8, scale.data.Pool1, scale.data.Pool3, scale.data.Pool4, scale.data.Pool5, scale.data.Pool6, scale.data.Pool7, scale.data.Pool8
 1 other assay present: RNA
 4 dimensional reductions calculated: pca, integrated.scvi, umap.unintegrated, umap.scvi

**Comment by Gesmira** [comment]
Hi, 
We pushed recent changes to the seurat5 branch where this should be fixed. You can restart your R session and reinstall with: 
```
remotes::install_github("mojaveazure/seurat-object", "seurat5", quiet = TRUE)
remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)
```
