### ISSUE TITLE
PrepSCTIntegration get Error in scale.data[anchor.features, ] : subscript out of bounds

### ISSUE THREAD

**Issue by jeffrey-cs** [satijalab/seurat#7911]
Hi there,

I have searched here and found several issues where people got the same error. However, none seems to be under the same circumstance as mine. I apologize if I missed a solution.

I had 2 spatial transcriptomics datasets and I tried to integrate them using SCTransform. I got the following error when running PrepSCTIntegration:
`Error in scale.data[anchor.features, ] : subscript out of bounds`

My code is as below:

```
st_1 <- Load10X_Spatial("raw.data/st1")
st_2 <- Load10X_Spatial("raw.data/st2")
obj.list <- list(st1 = st_1, st2 = st_2)
obj.list <- lapply(obj.list, SCTransform, assay = "Spatial")
int.features <- SelectIntegrationFeatures(obj.list, nfeatures = 3000)
int.prepsct <- PrepSCTIntegration(obj.list, anchor.features = int.features)
```

I found that if I set `return.only.var.genes = TRUE` when running SCTransform, the error was fixed. Is that correct to do so?

Thank you for your help.

**Comment by saketkc** [comment]
Hi @jeffrey-cs, I am unable to reproduce this issue, but something could check if any of the dataset has genes with all zeros. I would also recommend setting `vst.flavor="v2"` in your `lapply` question to invoke a faster (and more robust) estimation strategy.
