### ISSUE TITLE
RidgePlot - group by feature and plot by identity?

### ISSUE THREAD

**Issue by stacyhung** [satijalab/seurat#7915]
Hello,

Typically, the RidgePlot is used to plot the density of expression for a given gene or set of genes according to some identity variable, like cell type.   Is there a way to invert these plots, so that instead of having a single RidgePlot per gene grouped by identity, have a single RidgePlot per identity and grouped by gene?  In this sense, the RidgePlots could act as another form of expression profile for a given identity?

Thank you.

**Comment by longmanz** [comment]
Hi,
There is no direct way to generate the RidgePlot you want, but you can try to do it by using ggridge R-package. 

Alternatively, if you set the `stack == T` in RidgePlot (e.g., `RidgePlot(object = pbmc_small, features = rownames(pbmc_small)[1:5], group.by = "RNA_snn_res.1", stack = T))`, you can generate a plot that partially fulfill your need.
