### ISSUE TITLE
Why is vst recommended over mvp or disp?

### ISSUE THREAD

**Issue by KiomivDijk** [satijalab/seurat#7916]
1. One advantage to using the SCTransform workflow (which automatically sets variable genes), is that genes are weighted by their amount of residual variance in downstream analyses. This way you can add in more genes and the results will not change as much (because the additional genes will have less weight)

2. If not using SCTransform, we do recommend VST.

3. While all methods will give slightly different results, and we do generally believe some work better than others (see above), there are no unique considerations to doing Ctrl vs Treatment analyses for this question

_Originally posted by @satijalab in https://github.com/satijalab/seurat/issues/3304#issuecomment-663666014_

Dear sir/madam,

In the issue quoted, satijalab recommended using the vst method if SCTransform is not utilised. I was wondering what the reasoning behind this is? 

Thanks a lot in advance!

**Comment by rsatija** [comment]
The VST workflow for identifying variable features is similar in concept to the sctransform procedure, but without the negative binomial parameterization. We wrote this for Seurat v3, whereas the mvp and dips procedures were developed in earlier versions.
