### ISSUE TITLE
Merge without renaming -- targeted enrichment 

### ISSUE THREAD

**Issue by zwang996** [satijalab/seurat#7917]
I am also trying to combine two count matrices from the same sample (same 10x 3' platform) but for the second sequencing i ordered a fully custom panel of baits (only containing 50 genes of interest) for targeted enrichment. I am not entirely sure how the enrichment was done but my understanding is both runs started with the same cDNA library. I think it would make sense to numerically sum the gene counts for cells with identical barcodes but am unsure how to do it. How do people generally merge two count matrices from the same sample using 1) regular library and 2) a custom panel of baits? Do I do it at the Seurat object level or Cell Ranger level? 

The link to 10X targeted enrichment analysis: 
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count-targeted
The link to 10X target-parent comparison:
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/targeted-compare#requirements

**Comment by igrabski** [comment]
Hi, unfortunately we don't offer any existing functionality for this, and you will likely have to write some custom code to enable this.
