### ISSUE TITLE
Find Markers Returning List of reduction name_number instead of gene names after integration

### ISSUE THREAD

**Issue by mattmacd4** [satijalab/seurat#7920]
I am integrating two publicly available datasets with BP cells based v5 objects and integrating with layers. I tried both harmony and fast.mnn and I can get working integrations with UMAPs that align known control cell types within each dataset. However when I try to FindMarkers on the same object, it runs, but instead of gene names it's outputing the reduction name with a number(see below). Is this normal behavior for this? Is there a way to convert to gene names? Any help is greatly appreciated!

```R
cluster24 <- FindMarkers(thymus_immune_merge, ident.1 = 24,ident.2 = 17,reduction = "harmony")
```

Output looks like this:
                   p_val    avg_diff     p_val_adj
harmony_2   0.000000e+00 14.12201862  0.000000e+00
harmony_7   0.000000e+00 11.93553592  0.000000e+00
harmony_3   0.000000e+00  5.14839527  0.000000e+00
harmony_1   0.000000e+00  4.44567097  0.000000e+00
harmony_5   0.000000e+00  4.39080552  0.000000e+00
harmony_4   0.000000e+00  4.31960554  0.000000e+00
harmony_6   0.000000e+00  3.13848669  0.000000e+00
harmony_18  0.000000e+00 -2.06511736  0.000000e+00
harmony_12  0.000000e+00 -3.71529076  0.000000e+00
harmony_10  0.000000e+00 -7.14179004  0.000000e+00
harmony_8   0.000000e+00 -7.50128762  0.000000e+00
harmony_19 1.347438e-295 -2.20599931 1.475202e-290
harmony_15 1.247728e-264 -1.95065493 1.366037e-259
harmony_25 4.627602e-235 -1.55145495 5.066391e-230
harmony_9  5.237897e-228 -2.03304810 5.734554e-223
harmony_23 9.415668e-163 -1.35986710 1.030846e-157
harmony_21 2.469062e-136  1.17144038 2.703179e-131

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The reason is because you are setting the reduction parameter which per the manual for FindMarkers tests between cell embedding.  Simply remove that parameter and you should be good.  Make sure you set your assay to RNA or SCT (depending on pipeline and your choice) though before running DE.

Best,
Sam
