### ISSUE TITLE
Parse Biosciences vignette: Manual cluster annotation using marker genes

### ISSUE THREAD

**Issue by HeatherKates** [satijalab/seurat#7921]
Hello, thanks for the great tools! We are following steps at https://satijalab.org/seurat/articles/parsebio_sketch_integration compiled from https://github.com/satijalab/seurat/blob/seurat5/vignettes/ParseBio_sketch_integration.Rmd.

Would you be willing to provide the documentations for your annotation of the clusters using marker genes? In the vignette, it says only: 

`105 # You can now annotate clusters using marker genes.`
`106 # We performed this step, and include the results in the 'sketch.celltype' metadata column`

(although as an aside I think this metadata is then referred to using 'celltype.manual')
`109 plot.s2 <- DimPlot(object, group.by = 'celltype.manual', reduction = 'umap')`

We have followed the steps in the vignette and have resolved a similar number and projection of clusters from the UMAP, but get some ambiguous cluster annotations from our initial attempts to manually annotate these clusters using cell-type markers from https://azimuth.hubmapconsortium.org/references/#Human%20-%20PBMC. We are working to refine the cell-type marker lists and visualize gene expression across the UMAP projection to aid us in manual annotation, but I would be most appreciative of seeing the code/markers used for manual annotation (like a mapping table) in the vignette to be able to fully reproduce the workflow presented in the vignette.

Thank you!

**Comment by igrabski** [comment]
Hi, we have included the cell type labels in the `celltype.manual` column as you noted (thanks for pointing out the difference in reference!) -- we don't have a complete mapping table or such used for the annotation, since this vignette is primarily just an example of how analysis could be done, and certainly different approaches might result in different annotations.
