### ISSUE TITLE
Preprocessing for Akoya objects generated from Qupath

### ISSUE THREAD

**Issue by jwalewski** [satijalab/seurat#7923]
Hello, I am attempting to use ReadAkoya() on a qupath output file. Since the code was failing (at line https://github.com/satijalab/seurat/blob/57564e282a1ba54c655192d907d83df21164dc78/R/preprocessing.R#L1506), I decided to backtrack the issue through the code and found that line https://github.com/satijalab/seurat/blob/57564e282a1ba54c655192d907d83df21164dc78/R/preprocessing.R#L1486 is responsible.  

On this line there is attempt at finding a column named Cell: Mean. My qupath data does not have this column, and as a result a matrix with 0 columns is being created (downstream of here, there's a division over 0 error on line 1506).

What should the intended behavior here be for a qupath file that doesn't have a Cell: mean column?

**Comment by igrabski** [comment]
Hi, at present we assume that qupath files do contain a 'Cell: mean' column. Unfortunately, we do not currently support reading in qupath files lacking this information.
