### ISSUE TITLE
TransferData kills kernel in transferring features step

### ISSUE THREAD

**Issue by LucaTucciarone** [satijalab/seurat#7925]
I am trying to map ATACseq onto Multiomics. 
Here my 2 objects:
Query
An object of class Seurat 
351348 features across 160312 samples within 2 assays 
Active assay: ATAC (331741 features, 331741 variable features)
 1 other assay present: RNA
 3 dimensional reductions calculated: umap.atac, lsi, harmony.atac

Reference
An object of class Seurat 
435431 features across 57064 samples within 4 assays 
Active assay: ATAC (331750 features, 331750 variable features)
 3 other assays present: RNA, RNA_raw, SCT
 8 dimensional reductions calculated: pca, umap.rna, umap.atac, umap.wnn, harmony.rna, lsi, harmony.atac, umap.harmony.atac
 
 This is how I made a consensus of peaks:
 `combined.peaks <- reduce(x = c(granges(reference@assays$ATAC), granges(query@assays$ATAC)))

#Filter out non-standard chromosomes
combined.peaks <- keepStandardChromosomes(combined.peaks, pruning.mode = "coarse")

blacklist_hg38 <- read.table('/nfs/lab/Luca/Assets/references/hg38-blacklist.v2.bed', sep = "\t")
blacklist_hg38 = blacklist_hg38[c(1,2,3),]
colnames(blacklist_hg38) <- c('chr','start','end')
blacklist_hg38_gr <- makeGRangesFromDataFrame(blacklist_hg38)

#Filter out blacklisted regions
combined.peaks <- subsetByOverlaps(x = combined.peaks, ranges = blacklist_hg38_gr, invert = TRUE)

#Filter out very small and large peaks
combined.peaks <- combined.peaks[width(combined.peaks) <10000 & width(combined.peaks) >20]

write.table(as.data.frame(combined.peaks), paste0(step1.dir, 'multiome_sciATAC_celltypes_consensus.bed'), sep = '\t', row.names = FALSE)`
 
 This is how I am running transferdata:
 query = TransferData(
    anchorset = anchors, 
    query = query,
    reference = reference, 
    refdata = list(
      celltypes = "celltypes", 
      predicted_ATAC = "ATAC"),
    weight.reduction = "lsi"
)
 
 
 I do not have any error, the kernel dies after reaching the "Transferring features step" after a LOOOONG time with very low processor engagement (1-3%).
 
Finding integration vectors
Finding integration vector weights
Predicting cell labels
Transfering 331750 features onto reference data

And then it dies. 

Ideas?

**Comment by igrabski** [comment]
Hi, you should be able to address this by re-installing the current version of Seurat. Please feel free to open a new issue if you are still experiencing this problem with the latest release!
