### ISSUE TITLE
Seurat installation on server Rstudio using Docker 

### ISSUE THREAD

**Issue by muskang123** [satijalab/seurat#7927]
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory

Any help would be greatly appreciated!

Thanks!

**Comment by szhorvat** [comment]
Please see https://r.igraph.org/articles/installation-troubleshooting.html

**Comment by saketkc** [comment]
Hi @muskang123, this seems unrelated to Seurat so I am going to close this. It seems to be coming from igraph so it is possible the above link might be helpful.
