### ISSUE TITLE
Grey bars occuring between heatmap plot

### ISSUE THREAD

**Issue by kblust** [satijalab/seurat#7928]
Hello,

I tried to make a heatmap from the average expression of specific genes in my Seuratobject: 

1. Calculate the average gene expression of two samples and return a new seurat object
averages.beta2 <- AverageExpression(beta_multi, group.by = "orig.ident", return.seurat = TRUE)

2. Create Heatmap for specific genes comparing the average expression of both samples
markers <- c("INS", "G6PC2", "SIX2", "HOPX", "UCN3", "IAPP", "CPE", "FXYD2", "CHGB", "MAFA", "SIX3", "CHGA", "MAFB", "DLK1", "ESRRG")
DoHeatmap(averages.beta2, features = markers, group.by = "orig.ident") + scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n =4, name = "RdBu")))

Does anyone know why these grey bars are formed in the heatmap? 

![average_maturebeta](https://github.com/satijalab/seurat/assets/116660192/ef86bc1f-42dc-4e3c-97d8-355dedf364c0)

Thanks for your help!

**Comment by igrabski** [comment]
Thanks for your question! You can remove these gray bars by adding the argument `draw.lines = FALSE` into your `DoHeatmap` command.
