### ISSUE TITLE
Optimizing FindTransferAnchor memory usage on Suerat v5

### ISSUE THREAD

**Issue by Dario-Rocha** [satijalab/seurat#7929]
Hello again,
Following the covid sct mapping vignette from https://satijalab.org/seurat/articles/covid_sctmapping, 
I am trying to map a query v5 BPCells dataset with 92 layers and 1.3 million cells to a reference v3 dataset of 100k cells and I encountered multiple issues.
The first issue, and not the main topic of this post, is that compatibility and interconversion between seurat objects v3 and v5 is not straightforward. First thing I had to do was to modify the reference, otherwise the FindTransferAnchor wouldn't work

```
temp_reference[['integrated']] <- as(object = temp_reference[["integrated"]], Class = "Assay5")
temp_reference[["pca"]] <- CreateDimReducObject(embeddings = Embeddings(object = temp_reference[["pca"]]), 
                                                key = "PC_", 
                                                assay = DefaultAssay(temp_reference))
```

After I managed to get a query object that seems to be compatible, I moved on to trying to find the anchors, and here is where the main issue is.

```
temp_anchors <- FindTransferAnchors(reference = temp_reference, reference.assay = "integrated",
                                    query = a_projected, query.assay = "RNA",
                                    reduction = 'rpca',
                                    reference.reduction = 'pca')
```
However, this would attempt to perform the PCA on the 1.3 million cells by creating a dense matrix of the whole 1.3 million cells dataset, which obviously results in a crash.

Do you have any suggestions as to how to face this problem?

**Comment by rsatija** [comment]
You are correct that mapping a BPCells query does require a v5 reference, and you did modify this correctly.

The issue is that you are trying to run FindTransferAnchors with rpca dimensional reduction as opposed to pcaproject dimensional reduction. - which is the default. That will stream the principal component structure learned from the reference onto the query object.
