### ISSUE TITLE
MetageneBicorPlot not found

### ISSUE THREAD

**Issue by KoichiHashikawa** [satijalab/seurat#793]
It seems that MetageneBicorPlot was not successfully installed along Seurat by the command install.packages('Seurat').
I faced this issue when running CCA. Other functions and packages seems to be OK so far.

**Comment by mojaveazure** [comment]
What exact command did you try for installing Seurat and using `MetaGeneBicorPlot`? Could you also provide any errors from the Seurat install process?

**Comment by mojaveazure** [comment]
Could you provide the error you get when running MetageneBicorPlot?

**Comment by KoichiHashikawa** [comment]
I reinstalled Seurat and this issue is solved.
This was solely the installation problem.
