### ISSUE TITLE
Integration of an already integrated Seurat object and a new Seurat object

### ISSUE THREAD

**Issue by yip2002** [satijalab/seurat#7930]
Hello and thank you for developing such a great tool!

I have two Seurat objects. The first one is a new Seurat object, it is created from "expression_matrix.csv" and "metadata.csv". The second has 6 samples and has been integrated, and it has "RNA" assay and "integrated" assay. I want to use "IntegrateData" to integrate the two Seurat object. Which assay should be used in the second Seurat object, "RNA" or "Integrated"?

Thanks!

**Comment by mhkowalski** [comment]
Hi,

I can see two possibilities for this situation. 
1) You could map the new data to an integrated reference if you don't want to re-integrate (see [here](https://satijalab.org/seurat/articles/integration_mapping.html)). 
2) If you'd like to integrate the old object with the new object, then you should use the "RNA" assay. It may not make a large difference, but you could use the  `sample.tree` argument, to integrate the 6 samples together first and then integrate those with the new Seurat object. Please see the documentation of `IntegrateData` for more details.
