### ISSUE TITLE
Distance matrix

### ISSUE THREAD

**Issue by pbombna** [satijalab/seurat#7931]
I want to compare Seurat multimodal clustering with other algorithms which require a distance matrix as an input. How can I extract it from Seurat after running  FindMultiModalNeighbors() function? I know that [['weighted.nn']]@nn.dist contains multimodal distance in PCA space based on the correlation distance. 

Can I just do dist(object[['weighted.nn']]@nn.dist)? 

Thank you

**Comment by longmanz** [comment]
Hi, 
To access the distance matrix calculated by FindMultiModalNeighbors(), you can use the [Distances()](https://rdrr.io/github/mojaveazure/seurat-object/man/Distances.html).
