### ISSUE TITLE
FindAllMarkers cluster result is less than FindMakers

### ISSUE THREAD

**Issue by miderxi** [satijalab/seurat#7935]
library(dplyr)
library(Seurat)
library(patchwork)
setwd("~/Rwork")
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "./filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
#pbmc <- NormalizeData(pbmc)

pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
pbmc <- RunUMAP(pbmc, dims = 1:10)

pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
a <- pbmc.markers %>% filter(cluster=="0")
c <- pbmc.markers %>% filter(cluster=="1")

pbmc.marker <-FindMarkers(pbmc, ident.1 = 0,  only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
pbmc.marker$gene <- rownames(pbmc.marker)
b <- pbmc.marker

![图片](https://github.com/satijalab/seurat/assets/41559035/eb674c8d-6966-46ea-b47e-6a3939917a29)

**Comment by igrabski** [comment]
In `FindAllMarkers`, there is an additional argument `return.thresh` specifying a p-value threshold used to subset the DE results. By default, `return.thresh` is set to 0.01. However, in `FindMarkers`, there is no such subsetting automatically performed based on the p-value. If you wanted to ensure identical results between the two calls, you can set `return.thresh = 1` in the `FindAllMarkers` call.

**Comment by miderxi** [comment]
thanks for you answer.
