### ISSUE TITLE
Error: Cannot find assay '' in this Seurat object

### ISSUE THREAD

**Issue by apal6** [satijalab/seurat#7940]
Hi, 

I am trying to integrate the individual seurat objects but I keep getting the following error when I try to run,

SARC_combined.anchors <- FindIntegrationAnchors(object.list = SARC_combined_list, anchor.features = features)

`Error: Cannot find assay '' in this Seurat object`

My script:

#combined_list is the list of seurat objects processed individually. 
features <- SelectIntegrationFeatures(object.list = combined_list)
SARC_combined.anchors <- FindIntegrationAnchors(object.list = SARC_combined_list, anchor.features = features)

Thanks you!

**Comment by jestlin15** [comment]
Hi, may i please ask how you managed to solve this issue? I am currently facing the same problem :(
