### ISSUE TITLE
Vignette "Using BPCells with Seurat Objects" outdated for function saveRDS()

### ISSUE THREAD

**Issue by InternetExplorerBoy** [satijalab/seurat#7949]
Dear Seurat team,
I am using the beta version of Seurat v5 and noticed that the newly added function parameter `destdir` in `saveRDS()` (which previously worked without an issue), doesn't work anymore and throws me the following error:

> Error in saveRDS(object = scdata, file = ..., :
> unused argument (destdir = ...`

It seems that the function `saveRDS()` was replaced by `SeuratObject::SaveSeuratRds()` (but the behavior is not the same anymore, see #7948 ).  The documentation, however, wasn't updated yet.

**Comment by zskylarli** [comment]
Hi - thank you for pointing this out! We are planning to release updated vignettes when Seurat v5 is released on CRAN.
