### ISSUE TITLE
Adding SJ counts as an assay/metdata?

### ISSUE THREAD

**Issue by mattzano** [satijalab/seurat#7951]
Hi all,

was wondering if anyone has tried to add SJ.out to a Seurat object either as an additional assay or as a part of the metadata of a Seurat object. 
I cannot find any info about it but it looks quite straightforward from a theoretical perspective.

Would be helpful to then visualise splicing variants/junctions on a DimPlot etc...

Thanks
Matteo

**Comment by igrabski** [comment]
Hi, we don't explicitly offer this feature or have any examples of it, so you may have to write some custom code to enable this -- that said, in principle it should be possible!
