### ISSUE TITLE
ProjectData() and ProjectIntegration()

### ISSUE THREAD

**Issue by Lin13432** [satijalab/seurat#7954]
Hi,

I would like to see the details about the parameters of these two functions ProjectData() and ProjectIntegration(), how can I find them? The link of these two function remain 404.

obj <- [ProjectData](https://satijalab.org/seurat/reference/ProjectData.html)(
  object = obj,
  assay = "RNA",
  full.reduction = "pca.full",
  sketched.assay = "sketch",
  sketched.reduction = "pca",
  umap.model = "umap",
  dims = 1:50,
  refdata = [list](https://rdrr.io/r/base/list.html)(cluster_full = "seurat_clusters")
)

object <- [ProjectIntegration](https://satijalab.org/seurat/reference/ProjectIntegration.html)(
object = object, 
sketched.assay = "sketch", 
assay = "RNA", 
reduction = "integrated.rpca")

Or if anybody can explain the algorithm how these functions work with these parameters settings, I will appreciate it!!

**Comment by zskylarli** [comment]
Hi - can you try using the commands `?ProjectData` or `?ProjectIntegration` in your R session? This should provide documentation for the functions.
