### ISSUE TITLE
Two biologically different tissues present in one slide (spatial image), how to easily annotate it?

### ISSUE THREAD

**Issue by zandigohar** [satijalab/seurat#7956]
Hello, and thanks for your endless efforts and help.

I am working on a 10X Visium Spatial data, but the experiment contains two different tissues within one single slide. I was wondering what would be the easiest and fastest way to annotate the two tissues on the image.

For instance, let's assume the `anterior` and `posterior` tissues of the [tutorial brain dataset](https://satijalab.org/seurat/articles/spatial_vignette) were both in **a single slide**. How would you be able to name the first tissue anterior and the second tissue posterior in your Seurat `meta.data`?

Thank you!

**Comment by longmanz** [comment]
Hi, 
Are these 2 tissues visually separate on your slide? If so, it should be relative easy to assign the anterior and posterior based on the coordinate of each cell. For example, see [Cell Centroids: The spatial coordinates marking the centroid for each cell being profiled](https://satijalab.org/seurat/articles/spatial_vignette_2), and you can do the manual assignment by yourself. 
However, if they are kind of blended together, then it would be tricky and it is better to do so by running standard UMAP and find-neighbor analysis.

**Comment by zandigohar** [comment]
Hi,

Thanks for your reply. In my case, it was difficult to split it using centroids as the samples were too close, so I followed your second idea and it worked. Thank you!

For anyone ever encountering the same issue, I am putting my script here, which takes a Seurat spatial object and returns :
```
visually_annotate <- function(seurat){
    options(Seurat.object.assay.version = "v3")
    counts <- t(seurat@images[[1]]@coordinates[, c('row','col')])
    metadata <- seurat@meta.data
    image_data <- seurat@images
    coords <- seurat@images[[1]]@coordinates
    seurat <- NA
    seurat = CreateSeuratObject(counts = counts, assay="Spatial")
    seurat@images <- image_data
    seurat@assays$Spatial@data <- seurat@assays$Spatial@counts
    VariableFeatures(seurat) <- row.names(seurat)
    seurat <- ScaleData(seurat, features = row.names(uteri_geom))
    seurat <- FindNeighbors(seurat, dims = NULL, 
                                verbose = FALSE, reduction=NULL)
    return(seurat)
}
seurat_temp <- visually_annotate(seurat)
seurat_temp <- FindClusters(seurat_temp, verbose = FALSE, res=0.05) # choose a res that clearly splits your conditions
SpatialDimPlot(seurat_temp,  pt.size.factor = 1) # visually investigate the annotation
conditon1_cells <- colnames(subset(seurat_temp, subset=seurat_clusters==0)) # choose the first condition
seurat_temp <- NULL
seurat@meta.data$condition <- 'posterior'
seurat@meta.data[conditon1_cells,]$condition <- 'anterior'
```
