### ISSUE TITLE
Usage of `anchor.features` in `MapQuery()`

### ISSUE THREAD

**Issue by DanScarc** [satijalab/seurat#7958]
Hi Seurat team,

I am not entirely sure why the `features` slot of `anchorset`  in `MapQuery()` wouldn't be used if I run it with the following parameters:

```
query <- MapQuery(
    anchorset = anchors,
    query = query,
    reference = ref,
    reference.reduction = "spca",
    reduction.model = "umap_spca"
  )
```

Where `anchors` (from `FindTransferAnchors()`), `reference.reduction` and `reduction.model` have been computed previously. 
Am I overlooking something or would the above call ignore $|HVG_{ref}\cap HVG_{query}|$? Again, why?

Thank you in advance!

**Comment by rsatija** [comment]
The feature set for mapping query datasets onto references is set by default to the intersection of reference HVG and all query features. This is set at the FindTransferAnchors step, which precedes MapQuery

**Comment by DanScarc** [comment]
Yes, sorry, I meant $|HVG_{ref}\cap AllGenes_{query}|$. Thank you for clarifying!
