### ISSUE TITLE
Are there faster alternatives to read_rds() AND saveRDS() to read or write large Seurat objects?

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#7962]
Dear Seurat Team,

I often need to read or write large Seurat objects (>>40GB) to pause or continue my analysis workflow.

I use `saveRDS()` to write and `read_rds()` to load Seurat objects and it takes inconveniently slow. 
I disabled compression for faster writing, but still it takes too long.

Are there alternative functions or formats to save / load Seurat objects?

All formats & functions I found online are designed for matrices or data frames, not internally complex objects.

Thank you!
(I did not find a previous issue)

**Comment by saketkc** [comment]
Hi @vertesy, seurat objects saving should be also compatible with the [qs](https://cran.r-project.org/web/packages/qs/vignettes/vignette.html) package which uses a different serialization (resulting in faster read and write).

**Comment by vertesy** [comment]
Thanks so much, will try it!

**Comment by samuel-marsh** [comment]
+1 for qs package.

**Comment by vertesy** [comment]
Just to conclude, I can confrim that `qs` is indeed much faster, but really depends on the CPUs available, file system, etc.

In vague and generic terms, for me `qs::qsave()` is as fast _with compression,_ as `saveRDS()` without.

I did not encounter any problems using it (yet), I recommend using it.

**Comment by DanielZucha** [comment]
Thank you for this valuable insight!

Just adding a mention that `library(qs)` is being deprecated, and its successor `qs2` [package](https://github.com/qsbase/qs2) is now recommended for use.
