### ISSUE TITLE
PrepSCTFindMarkers Error

### ISSUE THREAD

**Issue by kkearns13** [satijalab/seurat#7964]
I have a v5 object that I've been trying to use `PrepSCTFindMarkers` on, but I run into the error: `Error in UseMethod(generic = "SCTResults", object = object) : 
  no applicable method for 'SCTResults' applied to an object of class "c('Assay5', 'StdAssay', 'KeyMixin')"`

The object I have is made of multiple experiments that I ran SCTransform on separately, merged, and used IntegrateLayers with RPCA. Here is some code of my current workflow:

```
# set QC cutoffs on each dataset separately
# perform SCTransform separately
# normalize HTO separately
# MULTIseqDemux separately and remove doublets/negatives

merge.dat <- merge(dat1, y = c(dat2, dat3, dat4, dat5, dat6),
                  merge.data = TRUE)

merge.dat[["SCT"]] <- split(merge.dat[["SCT"]], f = merge.dat$orig.ident)

test.integrated <- IntegrateLayers(
  object = merge.dat, method = RPCAIntegration, features = rownames(merge.dat),
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  verbose = T, assay = "SCT")

DefaultAssay(test.integrated) <- "SCT"

test.integrated <- FindNeighbors(test.integrated, reduction = "integrated.rpca", 
                                 dims = 1:30)
test.integrated <- FindClusters(test.integrated, resolution = 0.5, 
                                cluster.name = "rpca_clusters")
test.integrated <- RunUMAP(test.integrated, reduction = "integrated.rpca", 
                           dims = 1:30, reduction.name = "umap.rpca")

test.integrated <- JoinLayers(test.integrated)

test.integrated <- PrepSCTFindMarkers(test.integrated)

pbmc.markers <- FindAllMarkers(test.integrated, only.pos = TRUE, 
                               min.pct = 0.25, logfc.threshold = 0.25, 
                               assay="SCT")
```

Any help is much appreciated! Thank you!

**Comment by saketkc** [comment]
Hi @kkearns13, can you update to the latest `seurat5` branch and try this again?

```r
remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("satijalab/seurat", "seurat5", quiet = TRUE)
````

We made some fixes in the past couple of weeks before the CRAN release (which is still pending)

**Comment by kkearns13** [comment]
Hi Saket,

Apologies for the delay! 

I tried updating to the latest branch as you suggested, but I can't get it to work. I actually realized that I was using Seurat v4.9.9 for some reason, so I restarted my R session and made sure to load the updated branch. I checked `Version(test.integrated)` and found that my object was actually version 4.9.9 and thought maybe that was why `PrepSCTFindMarkers` didn't work even with the updated branch. So I also tried upgrading it using `UpdateSeuratObject`, which then said version 5.0.0, but `PrepSCTFindMarkers` still didn't work. I also had `options(future.globals.maxSize = 5e+09)` and `options(Seurat.object.assay.version = "v5")` set while making the object, not sure if that would have mattered though.

**Comment by saketkc** [comment]
I am unable to reproduce the issue. I would recommend installing things from CRAN since everything is now on cran:

```r
remove.packages(c("Seurat", "SeuratObject"))
# restart session
install.packages(c("Seurat"))
```

If you are still faciing issues, can you open a new issue and tag me? thanks!
