### ISSUE TITLE
I seem to be getting the same cells when I downsample a Seurat dataset

### ISSUE THREAD

**Issue by Kenneth-new-user** [satijalab/seurat#7967]
data is a Seurat obj with 1500 cells. I ran this code to downsample data to 3 sets of 500 cells, and then checked the number of common cells between each downsampled set, but common.cells turns out to have 500 elements which meant that the same 500 cells were selected for each round of downsampling? I thought it would be random.

```
ds1 <- subset(x = data, downsample = 500)
ds2 <- subset(x = data, downsample = 500)
ds3 <- subset(x = data, downsample = 500)

# Create list of gene names from all Seurat objects
total.cells <- list(colnames(ds1),
                    colnames(ds2),
                    colnames(ds3))

# Get common gene names 
common.cells <- Reduce(f = intersect, x = total.cells)
```

Better still if anyone could suggest a way to divide the data set into 3 equal parts randomly with no overlap. Many thanks.

**Comment by Kenneth-new-user** [comment]
I can answer the first part of my own question now. It seems that I need to use the sample() function to get random samples of the data set.
```
set.seed(42)
ds1 <- data[, sample(colnames(OFC), size =500, replace=F)]
ds2 <- data[, sample(colnames(OFC), size =500, replace=F)]
ds3 <- data[, sample(colnames(OFC), size =500, replace=F)]
```
gives me a list of common cells <500 with a different number of common.cells if I change the value of the seed.

However, what I really wanted to do is to divide the data set up into 3 equal parts with no overlap. Still looking for ideas on how to achieve this. Many thanks.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So what this boils down to is simple vector split (but add randomness).  

```
# 1: Pull all cells
all_cells <- Cells(obj)

# 2: random order cells
all_cells_random <- sample(all_cells)

# 3: pick number of splits desired
num_splits <- 3

# 4: split cells into number of groups
splits <- split(all_cells_random, rep_len(1:num_splits, length(all_cells_random)))

# 5: subset object by cells
obj_list <- lapply(1:length(splits), function(x) {
  sub_obj <- subset(x = obj, cells = splits[[x]])
})

```

As fyi I found this solution (steps 1-4 above) from google/stackoverflow, just need to define your google search into generic tems (i.e. splitting a vector randomly) as opposed to Seurat specific and answer came up pretty quick.

Best,
Sam
