### ISSUE TITLE
Top differential genes not highly expressed in DESeq2 results for single-cell pseudobulk

### ISSUE THREAD

**Issue by DaianeH** [satijalab/seurat#7969]
I'm using pseudobulk on scRNA-seq data from a Seurat object to compare two groups of cancer patients (with TP53 mutation vs wild-type) using Deseq2.
 
The most differentially expressed gene is LRP6, with a log2FoldChange of 7 and padj=6e-13. Here’s the Deseq2 plot of counts aggregated per sample as pseudo-bulk (each circle is a sample), where we can see that definitely this gene seems to be not expressed in WT, but expressed in MUT:

![LRP6](https://github.com/satijalab/seurat/assets/2428375/fcc5fca3-3b74-4d35-ac88-1f5f62588b0c)

However, when I use Seurat VlnPlot function (with pt.size=0) to plot the expression of this gene on the Seurat object, I don’t see much expression of this gene, most cells have zero expression which is not even enough to form a violin:

![LRP6_violin](https://github.com/satijalab/seurat/assets/2428375/59c41d48-e7b3-47b2-b1b8-64ef2ec85d6d)

There's definitely some cells expressing this gene, more so in MUT, but not enough to form a violin.
 
So I wonder, is this gene really differentially expressed? Is it expressed enough to be considered biologically important, if I can't see the violin?
 
For comparison, this is how a positive control should look like, a gene that is definitely expressed, differentially expressed, and biologically important:

![IFITM3](https://github.com/satijalab/seurat/assets/2428375/c2689bd4-4861-4e1b-a945-e0a0c00064be)

Thank you in advance,

**Comment by igrabski** [comment]
Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
