### ISSUE TITLE
rownames(GetAssayData(soj)) output is different from soj@assays even though both are from the `RNA` assay slot

### ISSUE THREAD

**Issue by klai001** [satijalab/seurat#7970]
I am recently trying out AddModuleScore() function from seurat but this function is unable to search for the features which clearly already exist in my RNA slot.
 I then checked the list of genes in my counts e.g. 
```
DefaultAssay(soj) <- "RNA"
granzyme=c("GZMB","GZMA","GZMH")
counts <- GetAssayData(soj, assay = "RNA")
rownames(counts)[grep("^GZM", rownames(counts))]
```

this was the output, which clearly shows they exist in the RNA slot.
`'GZMK''GZMA''GZMH''GZMB''GZMM'`

However, when i extract the rownames of the soj in their RNA assay e.g. 
```
allgenes=rownames(soj@assays$RNA)
granzyme_list <- list(intersect(allgenes,granzyme))
granzyme_list
```

the output is empty:
`1. `

i know these genes definitely exist as I'm able to use FeaturePlot on "granzyme" list
FeaturePlot(soj, reduction = "umap", features = c("GZMK","GZMA","GZMH","GZMB","GZMM"))
![image](https://github.com/satijalab/seurat/assets/55043905/0203701b-651f-4244-b628-9072dd42e97b)

would appreciate some suggestions regarding the discrepancies on the same Assay slot. 
thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you post the code you ran and the full error message?

Thanks!
Sam

**Comment by igrabski** [comment]
Hi, since there hasn't been a response in a while, I will close this issue, but please feel free to open a new issue if you are still having problems with this.
