### ISSUE TITLE
Analysis of logicle transformed Flow Cytometry Data

### ISSUE THREAD

**Issue by B-Betz** [satijalab/seurat#7975]
Dear authors,

First of all, thank you very much for your great work on Seurat!
I would like to use Seurat for analyzing data coming from a Spectral Flow experiment (more than 10 million cells, 40 markers/feature per cell). Since there are so many cells, I want to use the data sketching introduced with Seurat v5. 
My data is pre-gated with FlowJo and I export the transformed (logicle transformation) and scaled data.

To my understanding, Seurat expects log transformed data as it performs expm1() in several functions (mentioned here: https://github.com/satijalab/seurat/issues/747#issuecomment-417894121). 

Is it appropriate to use the logicle transformed data with Seurat? I would omit the step NormalizeData in the analysis. 

If not, would you have a suggestion how to properly format the data to be used with Seurat?

Thank you very much for your help!

**Comment by igrabski** [comment]
Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
