### ISSUE TITLE
Workflow for SCTransform V2, Integration, and DE while regressing out variables queries 

### ISSUE THREAD

**Issue by Tommy0398** [satijalab/seurat#7976]
Hi, 

I've found questions posted previously that are similar to my question but don't provide the full picture that is specific to the approach I'm using, so I'm asking here to make sure my approach is valid: 

Workflow:
1. Create all Seurat objects 
2. QC and filter all objects 
3. SCTransform(vst.flavor = "v2",vars.to.regress=c("sex","batch"))) each and switch to SCT assay
4. Integrate all the objects using the SCTransform V2 approach (https://satijalab.org/seurat/articles/sctransform_v2_vignette) 
    - Uses the control group as the reference as the samples are too large to do all pairwise (suggested in https://github.com/satijalab/seurat/issues/4753) 
    - FindIntegrationAnchors(object.list = Seu_object_list, normalization.method = "SCT", anchor.features = features,reference = reference_dataset ) 
5.   PCA, runUMAP, FindNeighbours, FindClusters and visulise
6. Calculate cell cycle score on integrated data as in https://github.com/satijalab/seurat/issues/5879 
    - This is mostly being used for visualization for now
7. FindMarkers as in https://satijalab.org/seurat/articles/sctransform_v2_vignette
    - Not Including anything as latent.vars
    - I'm not sure if this step if you should include the variables in latent.vars

Questions: 

1. Is the above workflow fine? 
2. Do you actually need to include vars.to.regress, or would the effect of these be removed during integration. Assuming you don't, would the effects be accounted for when doing findMarkers downstream? (possibly related to question 3)
3. If you regress out a variable in SCTransform, should you then include it in FindMarkers or would it already be corrected for? This is using the SCTransform workflow for findMarkers as in https://satijalab.org/seurat/articles/sctransform_v2_vignette 
4. Can you regress out batch if its only contained within 1 group? For my two conditions there are 6 and 9 samples in the groups respectively. Of the 6 sample group 3 of those are from another batch.

Previous issues referenced here:
- Regressing out variables using SCTransform, mentions FindMarkers but doesn't include latent.vars
    -  https://github.com/satijalab/seurat/issues/5029
- Workflow regressing out variable using SCTransform (merge not integrate) 
    - https://github.com/satijalab/seurat/discussions/4259 
- Integration using control group as reference 
    - https://github.com/satijalab/seurat/issues/4753 
- Calculating cell cycle scores on integrated data 
    - https://github.com/satijalab/seurat/issues/5879 and issues within 

Thanks,
Tommy

**Comment by saketkc** [comment]
> Is the above workflow fine?

Yes.

> Do you actually need to include vars.to.regress, or would the effect of these be removed during integration. Assuming you don't, would the effects be accounted for when doing findMarkers downstream? (possibly related to question 

FindMarkers() operates on `data` slot which does not have things regressed (unlike `scale.data` slot). 

> If you regress out a variable in SCTransform, should you then include it in FindMarkers or would it already be corrected for This is using the SCTransform workflow for findMarkers as in https://satijalab.org/seurat/articles/sctransform_v2_vignette

Same answer as above. If you want to explicitly adjust for covariates during `FindMarkers` step, you could use a GLM based test and use `latent.vars`. 

> Can you regress out batch if its only contained within 1 group? For my two conditions there are 6 and 9 samples in the groups respectively. Of the 6 sample group 3 of those are from another batch.

Regression requires you have a balanced design. If there is confounding, you will receiver an error. Short answer, is you can.

**Comment by Tommy0398** [comment]
Hi @saketkc, 

Thank you for the reply. Theres a part of it I overlooked. 

In https://satijalab.org/seurat/articles/sctransform_v2_vignette SCTransform is run on individual objects and so I can't regress out sex effects as each object is an individual sample. How should I regress out the sex effect for integration? 

Sorry I didn't consider that when I first wrote the issue. 

Kind Regards,
Tommy
