### ISSUE TITLE
Installing Azimuth for Seurat 4

### ISSUE THREAD

**Issue by YB0101-cli** [satijalab/seurat#7978]
Dear all,

According to Seurat and Azimuth tutorial page (https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html), Azimuth should work with Seurat4 and 5, but I failed to install it in R with Seurat version 4.3.0.1. 

I got the following error message when attempted the installation:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'Seurat' 4.3.0.1 is being loaded, but >= 5.0.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'Azimuth' 

Therefore, is it possible to install Azimuth for the current version of Seurat? 
I cannot afford to upgrade Seurat  since I need to use the same version to analyze all the samples. 

Thank you in adavnce for any input or help.

**Comment by Gesmira** [comment]
Hi @YB0101-cli, 
The newest version of Azimuth requires Seurat v5 due to new functionality. To install the version of azimuth you were previously working with, you can run: 
`remotes::install_github("satijalab/azimuth", "release/0.4.6")`
