### ISSUE TITLE
Normalization for RunMultiCCA

### ISSUE THREAD

**Issue by dingying85** [satijalab/seurat#798]
Dear Seurat developer:

I have a question, suppose I have 3 treatment groups and each group have 2 scRNASEQ samples (total 6 samples). For preparing the data for RunMultiCCA, should I perform Normalization and Scaling on combined 2 samples for each group, or I should do normalization and scaling on each sample and then combine every two samples for each group and then do RunMultiCCA? Thanks.

Just wondering whether there is a normal (0,1) assumption for each group for that algorithm.

Yours,
Ying

**Comment by andrewwbutler** [comment]
Hi Ying,

You should run scaling and normalization separately for each dataset that goes into `RunMultiCCA`.

**Comment by dingying85** [comment]
Thanks, just to confirm if each dataset contains 2 separate samples, those
2 samples should be combined and normalize together instead of normalize
separably? Thanks. -Ying
