### ISSUE TITLE
How to define features.tsv.gz and barcodes.tsv.gz files when manually giving the input to CreateSeuratObject function?

### ISSUE THREAD

**Issue by StarkTS98** [satijalab/seurat#7980]
Hello, 

I am new to single-cell analysis and I did the Seurat tutorial with the PBMC single-cell data. Now I am trying it on my CELseq dataset. Here I am not reading the count matrix from a specific directory, instead, concatenating counts from 2304 cells having their individual counts.hdf files, converting to a sparse matrix and then giving it as input to make the Seurat object. 
I am using the Seurat package version 4.3.0.1 and I am runnning into `Error: Feature names of counts matrix cannot be empty` when using the `CreateSeuratObject`. 
I have thoroughly checked my input matrix which has mouse gene names as rownames and cell identifiers as the column names. There are no duplicate names and no NULL values. I think this error is coming because of the absence of a features file. In this case, where I do not read the count matrix from a file but instead, make one by combining from multiple cells, I have a few questions:
1) Is it always necessary to have the features and barcode files separately?
2) How do I specify the `features.tsv.gz` and `barcodes.tsv.gz files` in the script as I am not using the `Read10X` function?
3) Is there any specific format for the presence of "-" or "_" in the barcodes?

My input matrix looks like the following screenshot. For now, the column names are just cell identifiers which when I changed to actual cell barcode sequences gave the same error
![image](https://github.com/satijalab/seurat/assets/104354986/32495dcb-9436-4d29-b393-877c20462f78)

Any help would be appreciated!
Thanks in advance

**Comment by chrkuo** [comment]
@StarkTS98 would love to know how you're analyzing CEL-Seq data since I am interested in analyzing them

**Comment by StarkTS98** [comment]
> @StarkTS98 would love to know how you're analyzing CEL-Seq data since I am interested in analyzing them
I followed the regular pipeline of demultiplexing according to UMIs and CELseq barcodes followed by alignment. Now I have the count data for each single cell and want to run Seurat on the pooled single-cell data :)

**Comment by chrkuo** [comment]
> > @StarkTS98 would love to know how you're analyzing CEL-Seq data since I am interested in analyzing them
> 
> I followed the regular pipeline of demultiplexing according to UMIs and CELseq barcodes followed by alignment. Now I have the count data for each single cell and want to run Seurat on the pooled single-cell data :)

Do you mind sharing your R code? My email is chris3kuo@gmail.com
