### ISSUE TITLE
Tutorials for Seurat 4

### ISSUE THREAD

**Issue by YB0101-cli** [satijalab/seurat#7981]
Dear all,

I am using Seurat version 4.3.0.1 for my analysis. Since I am new in the field I need to consult the tutorial page quite often, but yesterday when I visited Seurat home page, I could not find the tutorial for Seurat version 4 anymore, everything is replaced with Seurat version 5. Could you please tell me the link for Seurat version 4 tutorial? I checked the archive page, but could not find what I was looking for, either links were broken or they did not contain a correct information. 
Also, is it still possible to click the command on the tutorial page to get the explanations and options for each command? 

Thank you for your help.

**Comment by ppm1337** [comment]
You can find the archived versions of the articles under [https://satijalab.org/seurat/articles/archive](https://satijalab.org/seurat/articles/archive), mind the entries `v4.3`.
