### ISSUE TITLE
Cannot retrieve multimodal CITE-seq reference in Multimodal reference mapping vignette

### ISSUE THREAD

**Issue by ianchlee** [satijalab/seurat#7982]
Hi,

I am trying to work with the [multimodal reference mapping](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html) vignette and would like to use the pbmc_multimodal_2023.rds object. However, I am unable to download the reference data using the following code and instead receive the error No such file or directory.
`options(SeuratData.repo.use = "http://seurat.nygenome.org")`
`reference <- readRDS("/brahms/hartmana/vignette_data/pbmc_multimodal_2023.rds")`

 I've also tried using this line instead but it also doesn't work with the same No such file or directory error:
`reference <- readRDS(url("http://seurat.nygenome.org/brahms/hartmana/vignette_data/pbmc_multimodal_2023.rds", method="libcurl"))
`

May I ask if the h5Seurat object available in [here](https://atlas.fredhutch.org/nygc/multimodal-pbmc/) is the same reference data? Alternatively, how should I use SeuratDisk to get the reference data?

**Comment by igrabski** [comment]
Hi, that link is just an internal link to where we have the data stored on our end. To access the full data, you can refer to the data availability details in the original [paper](https://www.sciencedirect.com/science/article/pii/S0092867421005833?via%3Dihub).
