### ISSUE TITLE
RunUMAP error

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#7983]
I merged 6 spatial transcriptomic objects together and then ran 

Metastaticsamples.merge <- ScaleData(Metastaticsamples.merge)

#perform linear reduction analysis:
Metastaticsamples.merge <- RunPCA(Metastaticsamples.merge, features = VariableFeatures(object = Metastaticsamples.merge))

#Metastatic
Metastaticsamples.merge <- FindNeighbors(Metastaticsamples.merge, reduction = "pca", dims = 1:15)
Metastaticsamples.merge <- FindClusters(Metastaticsamples.merge, verbose = FALSE)
Metastaticsamples.merge <- RunUMAP(Metastaticsamples.merge, dims = 1:15)

However upon doing RunUMAP i hit an error code

20:35:37 Initializing from normalized Laplacian + noise (using irlba)
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

any thoughts on what happened and how to overcome this?

**Comment by Grolinck** [comment]
I have the same issue, let me know if you fixed it! Also when I went back to Seurat 4.3.0 it is still there...

**Comment by wtoddfarmer** [comment]
I just ran into this error with v4.4.0. 

Updating the "Matrix" package seemed to resolve the issue.

**Comment by chrkuo** [comment]
> I just ran into this error with v4.4.0. 
> 
> 
> 
> Updating the "Matrix" package seemed to resolve the issue.

I think my Matrix package is already updated but i can check. Did you have to uninstall and reinstall?

**Comment by wtoddfarmer** [comment]
> > I just ran into this error with v4.4.0.
> > Updating the "Matrix" package seemed to resolve the issue.
> 
> I think my Matrix package is already updated but i can check. Did you have to uninstall and reinstall?

I did not uninstall and reinstall. Just a simple install.packages. I did need to restart the R session to load the new package version.

**Comment by ellefeg** [comment]
I am having the same problem but updating Matrix to `Matrix_1.6-2` didn't help. What version of Matrix are you running @wtoddfarmer ?

I downgraded to `Seurat_4.4.0` and `SeuratObject_4.1.4` because Seurat v5 gave me all sorts of other Matrix-associated errors (#7993 - downgrading Matrix gives me another error message).

Here's what I ran in Seurat v4:
```
library(Seurat)
library(Matrix)
df <- readRDS("/path/to/obj.RDS") #Seurat object made with v4
df <- RunUMAP(df, reduction = "pca", dims = 1:11)
```
I get this error:
```
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
```

Here's the traceback:
```
12: irlba::irlba(L, nv = n, nu = 0, maxit = iters)
11: withCallingHandlers(expr, warning = function(w) if (inherits(w, 
        classes)) tryInvokeRestart("muffleWarning"))
10: suppressWarnings(res <- irlba::irlba(L, nv = n, nu = 0, maxit = iters))
9: irlba_spectral_tsvd(L, ndim + 1)
8: irlba_tsvd_normalized_laplacian_init(A, ndim, verbose = FALSE)
7: spectral_init(V, ndim = n_components, verbose = verbose)
6: uwot(X = X, n_neighbors = n_neighbors, n_components = n_components, 
       metric = metric, n_epochs = n_epochs, alpha = learning_rate, 
       scale = scale, init = init, init_sdev = init_sdev, spread = spread, 
       min_dist = min_dist, set_op_mix_ratio = set_op_mix_ratio, 
       local_connectivity = local_connectivity, bandwidth = bandwidth, 
       gamma = repulsion_strength, negative_sample_rate = negative_sample_rate, 
       a = a, b = b, nn_method = nn_method, n_trees = n_trees, search_k = search_k, 
       method = "umap", approx_pow = approx_pow, n_threads = n_threads, 
       n_sgd_threads = n_sgd_threads, grain_size = grain_size, y = y, 
       target_n_neighbors = target_n_neighbors, target_weight = target_weight, 
       target_metric = target_metric, pca = pca, pca_center = pca_center, 
       pca_method = pca_method, pcg_rand = pcg_rand, fast_sgd = fast_sgd, 
       ret_model = ret_model || "model" %in% ret_extra, ret_nn = ret_nn || 
           "nn" %in% ret_extra, ret_fgraph = "fgraph" %in% ret_extra, 
       ret_sigma = "sigma" %in% ret_extra, ret_localr = "localr" %in% 
           ret_extra, batch = batch, opt_args = opt_args, epoch_callback = epoch_callback, 
       binary_edge_weights = binary_edge_weights, tmpdir = tempdir(), 
       verbose = verbose, dens_scale = dens_scale, seed = seed)
5: umap(X = object, n_threads = nbrOfWorkers(), n_neighbors = as.integer(x = n.neighbors), 
       n_components = as.integer(x = n.components), metric = metric, 
       n_epochs = n.epochs, learning_rate = learning.rate, min_dist = min.dist, 
       spread = spread, set_op_mix_ratio = set.op.mix.ratio, local_connectivity = local.connectivity, 
       repulsion_strength = repulsion.strength, negative_sample_rate = negative.sample.rate, 
       a = a, b = b, fast_sgd = uwot.sgd, verbose = verbose, ret_model = return.model)
4: RunUMAP.default(object = data.use, reduction.model = reduction.model, 
       return.model = return.model, assay = assay, umap.method = umap.method, 
       n.neighbors = n.neighbors, n.components = n.components, metric = metric, 
       n.epochs = n.epochs, learning.rate = learning.rate, min.dist = min.dist, 
       spread = spread, set.op.mix.ratio = set.op.mix.ratio, local.connectivity = local.connectivity, 
       repulsion.strength = repulsion.strength, negative.sample.rate = negative.sample.rate, 
       a = a, b = b, uwot.sgd = uwot.sgd, seed.use = seed.use, metric.kwds = metric.kwds, 
       angular.rp.forest = angular.rp.forest, densmap = densmap, 
       dens.lambda = dens.lambda, dens.frac = dens.frac, dens.var.shift = dens.var.shift, 
       reduction.key = reduction.key, verbose = verbose)
3: RunUMAP(object = data.use, reduction.model = reduction.model, 
       return.model = return.model, assay = assay, umap.method = umap.method, 
       n.neighbors = n.neighbors, n.components = n.components, metric = metric, 
       n.epochs = n.epochs, learning.rate = learning.rate, min.dist = min.dist, 
       spread = spread, set.op.mix.ratio = set.op.mix.ratio, local.connectivity = local.connectivity, 
       repulsion.strength = repulsion.strength, negative.sample.rate = negative.sample.rate, 
       a = a, b = b, uwot.sgd = uwot.sgd, seed.use = seed.use, metric.kwds = metric.kwds, 
       angular.rp.forest = angular.rp.forest, densmap = densmap, 
       dens.lambda = dens.lambda, dens.frac = dens.frac, dens.var.shift = dens.var.shift, 
       reduction.key = reduction.key, verbose = verbose)
2: RunUMAP.Seurat(df, reduction = "pca", dims = 1:11)
1: RunUMAP(df, reduction = "pca", dims = 1:11)
```

And my sessionInfo()

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: xxxxx
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.6-2       SeuratObject_4.1.4 Seurat_4.4.0      

loaded via a namespace (and not attached):
  [1] deldir_1.0-9           pbapply_1.7-2          gridExtra_2.3          rlang_1.1.2            magrittr_2.0.3        
  [6] RcppAnnoy_0.0.21       spatstat.geom_3.2-7    matrixStats_1.1.0      ggridges_0.5.4         compiler_4.3.1        
 [11] png_0.1-8              vctrs_0.6.4            reshape2_1.4.4         stringr_1.5.0          pkgconfig_2.0.3       
 [16] fastmap_1.1.1          ellipsis_0.3.2         utf8_1.2.4             promises_1.2.1         rmarkdown_2.25        
 [21] purrr_1.0.2            xfun_0.41              cachem_1.0.8           jsonlite_1.8.7         goftest_1.2-3         
 [26] later_1.3.1            spatstat.utils_3.0-4   irlba_2.3.5.1          parallel_4.3.1         cluster_2.1.4         
 [31] R6_2.5.1               ica_1.0-3              spatstat.data_3.0-3    bslib_0.5.1            stringi_1.7.12        
 [36] RColorBrewer_1.1-3     reticulate_1.34.0      parallelly_1.36.0      lmtest_0.9-40          jquerylib_0.1.4       
 [41] scattermore_1.2        Rcpp_1.0.11            knitr_1.45             tensor_1.5             future.apply_1.11.0   
 [46] zoo_1.8-12             sctransform_0.4.1      httpuv_1.6.12          splines_4.3.1          igraph_1.5.1          
 [51] tidyselect_1.2.0       abind_1.4-5            rstudioapi_0.15.0      yaml_2.3.7             spatstat.random_3.2-1 
 [56] codetools_0.2-19       miniUI_0.1.1.1         spatstat.explore_3.2-5 listenv_0.9.0          lattice_0.22-5        
 [61] tibble_3.2.1           plyr_1.8.9             shiny_1.7.5.1          ROCR_1.0-11            evaluate_0.23         
 [66] Rtsne_0.16             future_1.33.0          survival_3.5-7         polyclip_1.10-6        fitdistrplus_1.1-11   
 [71] pillar_1.9.0           KernSmooth_2.23-22     plotly_4.10.3          generics_0.1.3         sp_2.1-1              
 [76] ggplot2_3.4.4          munsell_0.5.0          scales_1.2.1           globals_0.16.2         xtable_1.8-4          
 [81] glue_1.6.2             lazyeval_0.2.2         tools_4.3.1            data.table_1.14.8      RANN_2.6.1            
 [86] dotCall64_1.1-0        leiden_0.4.3           cowplot_1.1.1          grid_4.3.1             tidyr_1.3.0           
 [91] colorspace_2.1-0       nlme_3.1-163           patchwork_1.1.3        cli_3.6.1              spatstat.sparse_3.0-3 
 [96] spam_2.10-0            fansi_1.0.5            viridisLite_0.4.2      dplyr_1.1.3            uwot_0.1.16           
[101] gtable_0.3.4           sass_0.4.7             digest_0.6.33          progressr_0.14.0       ggrepel_0.9.4         
[106] htmlwidgets_1.6.2      htmltools_0.5.7        lifecycle_1.0.4        httr_1.4.7             mime_0.12             
[111] MASS_7.3-60           
```

**Comment by longmanz** [comment]
Hi,
Thank you for reporting this and providing solutions. This is indeed an issue caused by Matrix 1.6-2 (https://github.com/mojaveazure/seurat-object/issues/145). Please down-grade your Matrix back to 1.6-1.1 or earlier to avoid this issue temporarily. 
`remotes::install_version("Matrix", version = "1.6-1.1")`

**Comment by yangjy53** [comment]
install.packages("Matrix")

**Comment by QianhuiXu** [comment]
> Hi, Thank you for reporting this and providing solutions. This is indeed an issue caused by Matrix 1.6-2 ([mojaveazure/seurat-object#145](https://github.com/mojaveazure/seurat-object/issues/145)). Please down-grade your Matrix back to 1.6-1.1 or earlier to avoid this issue temporarily. `remotes::install_version("Matrix", version = "1.6-1.1")`

I get this error, but Matrix is 1.6-3
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.0 (2023-04-21)
 os       CentOS Linux 7 (Core)
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Asia/Shanghai
 date     2023-11-23
 rstudio  2023.03.1+446 Cherry Blossom (server)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────
 package          * version  date (UTC) lib source
 abind              1.4-5    2016-07-21 [2] CRAN (R 4.3.0)
 BiocGenerics       0.46.0   2023-04-25 [2] Bioconductor
 callr              3.7.3    2022-11-02 [2] CRAN (R 4.3.0)
 circlize           0.4.15   2022-05-10 [2] CRAN (R 4.3.0)
 cli                3.6.1    2023-03-23 [2] CRAN (R 4.3.0)
 clue               0.3-64   2023-01-31 [2] CRAN (R 4.3.0)
 cluster            2.1.4    2022-08-22 [3] CRAN (R 4.3.0)
 codetools          0.2-19   2023-02-01 [3] CRAN (R 4.3.0)
 colorspace         2.1-0    2023-01-23 [2] CRAN (R 4.3.0)
 ComplexHeatmap     2.16.0   2023-04-25 [2] Bioconductor
 cowplot            1.1.1    2020-12-30 [2] CRAN (R 4.3.0)
 crayon             1.5.2    2022-09-29 [2] CRAN (R 4.3.0)
 data.table         1.14.8   2023-02-17 [1] CRAN (R 4.3.0)
 deldir             1.0-9    2023-05-17 [2] CRAN (R 4.3.0)
 digest             0.6.31   2022-12-11 [2] CRAN (R 4.3.0)
 doParallel         1.0.17   2022-02-07 [2] CRAN (R 4.3.0)
 dotCall64          1.0-2    2022-10-03 [2] CRAN (R 4.3.0)
 dplyr            * 1.1.3    2023-09-03 [1] CRAN (R 4.3.0)
 ellipsis           0.3.2    2021-04-29 [2] CRAN (R 4.3.0)
 fansi              1.0.4    2023-01-22 [2] CRAN (R 4.3.0)
 fastmap            1.1.1    2023-02-24 [2] CRAN (R 4.3.0)
 fitdistrplus       1.1-11   2023-04-25 [2] CRAN (R 4.3.0)
 foreach            1.5.2    2022-02-02 [2] CRAN (R 4.3.0)
 future             1.28.0   2022-09-02 [1] CRAN (R 4.3.0)
 future.apply       1.11.0   2023-05-21 [2] CRAN (R 4.3.0)
 generics           0.1.3    2022-07-05 [2] CRAN (R 4.3.0)
 GetoptLong         1.0.5    2020-12-15 [2] CRAN (R 4.3.0)
 ggplot2          * 3.4.3    2023-08-14 [1] CRAN (R 4.3.0)
 ggrepel            0.9.3    2023-02-03 [2] CRAN (R 4.3.0)
 ggridges           0.5.4    2022-09-26 [2] CRAN (R 4.3.0)
 GlobalOptions      0.1.2    2020-06-10 [2] CRAN (R 4.3.0)
 globals            0.16.2   2022-11-21 [2] CRAN (R 4.3.0)
 glue               1.6.2    2022-02-24 [2] CRAN (R 4.3.0)
 goftest            1.2-3    2021-10-07 [2] CRAN (R 4.3.0)
 gridExtra          2.3      2017-09-09 [2] CRAN (R 4.3.0)
 gtable             0.3.3    2023-03-21 [2] CRAN (R 4.3.0)
 htmltools          0.5.5    2023-03-23 [2] CRAN (R 4.3.0)
 htmlwidgets        1.6.2    2023-03-17 [2] CRAN (R 4.3.0)
 httpuv             1.6.11   2023-05-11 [2] CRAN (R 4.3.0)
 httr               1.4.6    2023-05-08 [2] CRAN (R 4.3.0)
 ica                1.0-3    2022-07-08 [2] CRAN (R 4.3.0)
 igraph             1.3.5    2022-09-22 [2] CRAN (R 4.3.0)
 IRanges            2.34.0   2023-04-25 [2] Bioconductor
 irlba              2.3.5.1  2022-10-03 [2] CRAN (R 4.3.0)
 iterators          1.0.14   2022-02-05 [2] CRAN (R 4.3.0)
 jsonlite           1.8.5    2023-06-05 [2] CRAN (R 4.3.0)
 KernSmooth         2.23-20  2021-05-03 [3] CRAN (R 4.3.0)
 later              1.3.1    2023-05-02 [2] CRAN (R 4.3.0)
 lattice            0.21-8   2023-04-05 [3] CRAN (R 4.3.0)
 lazyeval           0.2.2    2019-03-15 [2] CRAN (R 4.3.0)
 leiden             0.4.3    2022-09-10 [2] CRAN (R 4.3.0)
 lifecycle          1.0.3    2022-10-07 [2] CRAN (R 4.3.0)
 listenv            0.9.0    2022-12-16 [2] CRAN (R 4.3.0)
 lmtest             0.9-40   2022-03-21 [2] CRAN (R 4.3.0)
 magrittr           2.0.3    2022-03-30 [2] CRAN (R 4.3.0)
 MASS               7.3-58.4 2023-03-07 [3] CRAN (R 4.3.0)
 Matrix             1.6-3    2023-11-14 [2] CRAN (R 4.3.0)
 matrixStats        1.0.0    2023-06-02 [2] CRAN (R 4.3.0)
 mime               0.12     2021-09-28 [2] CRAN (R 4.3.0)
 miniUI             0.1.1.1  2018-05-18 [2] CRAN (R 4.3.0)
 munsell            0.5.0    2018-06-12 [2] CRAN (R 4.3.0)
 nlme               3.1-162  2023-01-31 [3] CRAN (R 4.3.0)
 parallelly         1.36.0   2023-05-26 [2] CRAN (R 4.3.0)
 patchwork        * 1.1.2    2022-08-19 [2] CRAN (R 4.3.0)
 pbapply            1.7-0    2023-01-13 [2] CRAN (R 4.3.0)
 pillar             1.9.0    2023-03-22 [2] CRAN (R 4.3.0)
 pkgbuild           1.4.0    2022-11-27 [2] CRAN (R 4.3.0)
 pkgconfig          2.0.3    2019-09-22 [2] CRAN (R 4.3.0)
 plotly             4.10.2   2023-06-03 [2] CRAN (R 4.3.0)
 plyr               1.8.8    2022-11-11 [2] CRAN (R 4.3.0)
 png                0.1-8    2022-11-29 [2] CRAN (R 4.3.0)
 polyclip           1.10-4   2022-10-20 [2] CRAN (R 4.3.0)
 prettyunits        1.1.1    2020-01-24 [2] CRAN (R 4.3.0)
 processx           3.8.1    2023-04-18 [2] CRAN (R 4.3.0)
 progressr          0.13.0   2023-01-10 [2] CRAN (R 4.3.0)
 promises           1.2.0.1  2021-02-11 [2] CRAN (R 4.3.0)
 ps                 1.7.5    2023-04-18 [2] CRAN (R 4.3.0)
 purrr              1.0.2    2023-08-10 [1] CRAN (R 4.3.0)
 R.methodsS3        1.8.2    2022-06-13 [2] CRAN (R 4.3.0)
 R.oo               1.25.0   2022-06-12 [2] CRAN (R 4.3.0)
 R.utils            2.12.2   2022-11-11 [2] CRAN (R 4.3.0)
 R6                 2.5.1    2021-08-19 [2] CRAN (R 4.3.0)
 RANN               2.6.1    2019-01-08 [2] CRAN (R 4.3.0)
 RColorBrewer       1.1-3    2022-04-03 [2] CRAN (R 4.3.0)
 Rcpp               1.0.10   2023-01-22 [2] CRAN (R 4.3.0)
 RcppAnnoy          0.0.20   2022-10-27 [2] CRAN (R 4.3.0)
 remotes            2.4.2    2021-11-30 [2] CRAN (R 4.3.0)
 reshape2           1.4.4    2020-04-09 [2] CRAN (R 4.3.0)
 reticulate         1.29     2023-06-05 [2] CRAN (R 4.3.0)
 rjson              0.2.21   2022-01-09 [2] CRAN (R 4.3.0)
 rlang              1.1.1    2023-04-28 [2] CRAN (R 4.3.0)
 ROCR               1.0-11   2020-05-02 [2] CRAN (R 4.3.0)
 rstudioapi         0.14     2022-08-22 [2] CRAN (R 4.3.0)
 Rtsne              0.16     2022-04-17 [2] CRAN (R 4.3.0)
 S4Vectors          0.38.1   2023-05-02 [2] Bioconductor
 scales             1.2.1    2022-08-20 [2] CRAN (R 4.3.0)
 scattermore        1.2      2023-06-12 [1] CRAN (R 4.3.0)
 sctransform        0.3.5    2022-09-21 [2] CRAN (R 4.3.0)
 sessioninfo        1.2.2    2021-12-06 [2] CRAN (R 4.3.0)
 Seurat           * 4.3.0    2022-11-18 [2] CRAN (R 4.3.0)
 SeuratObject     * 5.0.1    2023-11-17 [2] CRAN (R 4.3.0)
 shape              1.4.6    2021-05-19 [2] CRAN (R 4.3.0)
 shiny              1.7.4    2022-12-15 [2] CRAN (R 4.3.0)
 sp                 1.6-1    2023-05-31 [2] CRAN (R 4.3.0)
 spam               2.9-1    2022-08-07 [2] CRAN (R 4.3.0)
 spatstat.data      3.0-1    2023-03-12 [2] CRAN (R 4.3.0)
 spatstat.explore   3.2-5    2023-10-22 [1] CRAN (R 4.3.0)
 spatstat.geom      3.2-7    2023-10-20 [1] CRAN (R 4.3.0)
 spatstat.random    3.2-1    2023-10-21 [1] CRAN (R 4.3.0)
 spatstat.sparse    3.0-1    2023-03-12 [2] CRAN (R 4.3.0)
 spatstat.utils     3.0-3    2023-05-09 [2] CRAN (R 4.3.0)
 stringi            1.7.12   2023-01-11 [2] CRAN (R 4.3.0)
 stringr            1.5.0    2022-12-02 [2] CRAN (R 4.3.0)
 survival           3.5-5    2023-03-12 [3] CRAN (R 4.3.0)
 tensor             1.5      2012-05-05 [2] CRAN (R 4.3.0)
 tibble             3.2.1    2023-03-20 [2] CRAN (R 4.3.0)
 tidyr              1.3.0    2023-01-24 [2] CRAN (R 4.3.0)
 tidyselect         1.2.0    2022-10-10 [2] CRAN (R 4.3.0)
 utf8               1.2.3    2023-01-31 [2] CRAN (R 4.3.0)
 uwot               0.1.16   2023-06-29 [2] CRAN (R 4.3.0)
 vctrs              0.6.3    2023-06-14 [1] CRAN (R 4.3.0)
 viridisLite        0.4.2    2023-05-02 [2] CRAN (R 4.3.0)
 withr              2.5.0    2022-03-03 [2] CRAN (R 4.3.0)
 xtable             1.8-4    2019-04-21 [2] CRAN (R 4.3.0)
 zoo                1.8-12   2023-04-13 [2] CRAN (R 4.3.0)


Let me know if you fixed it!  Thank you very much!

**Comment by wangteamsysu** [comment]
Guys, I got the same error. Here is my version that can solve it:
```
> packageVersion('SeuratObject')
[1] ‘4.1.4’
> packageVersion('Matrix')
[1] ‘1.6.1.1’
> packageVersion('Seurat')
[1] ‘4.4.0’
```

**Comment by sophiakrix** [comment]
Thanks @wangteamsysu , this worked for me!

**Comment by sybgyy** [comment]
> packageVersion('SeuratObject')
[1] ‘4.1.4’
> packageVersion('Matrix')
[1] ‘1.6.1.1’
> packageVersion('Seurat')
[1] ‘4.4.0’
This is my version and I get a new error.

Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
  function 'sexp_as_cholmod_sparse' not provided by package 'Matrix'

**Comment by ollieeknight** [comment]
has anyone figured out a way to get past this issue with seurat v5?
