### ISSUE TITLE
Error in old workflow despite Seurat v5 Claiming to be backwards compatiable

### ISSUE THREAD

**Issue by jwalewski** [satijalab/seurat#7985]
Upon looking at the Seurat v5 changelog I see that there is a claim of backwards compatability - that all existing workflows can be preserved. I am trying to learn Seurat, and I am using the following tutorial to do so: (https://github.com/hbctraining/scRNA-seq_online/tree/master). In this tutorial, to obtain the counts, there is the following step:

```r
counts <- GetAssayData(object = filtered_seurat, slot = "counts")
```

the error is as follows:
```r
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
The `slot` argument of `GetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.
```

This Assay has two layers, one each for control and stimulated counts. What would be the proper way to obtain the counts in the newest version of Seurat?

Thanks so much for your help!

**Comment by samuel-marsh** [comment]
Hi @jwalewski,

Not member of dev team but hopefully can be helpful.  So I believe that backward compatibility reference is in regards to workflows using v4 object structures.  When using V5 object structure (i.e. objects that have layers) you need to use workflow specific commands.  In this case I believe what you are looking for is `LayerData` (https://mojaveazure.github.io/seurat-object/reference/Layers.html).

Best,
Sam

**Comment by jwalewski** [comment]
Understood, thank you for this advice. Would the correct command for a Seurat v5 object then be
```
controlcounts <- LayerData(filtered_seurat, layer="control")
stimcounts <- LayerData(filtered_seurat, layer="stim")
```
How would I then merge these? Would keeping them in a list be acceptable?

Or would it be best to try to render it in as a v4 object? Is this possible in Seurat v5?

**Comment by longmanz** [comment]
Hi,
Thank you @samuel-marsh ! 
And yes @jwalewski please use the new layer-related functions in Seurat v5 to manipulate layer data. If you want to merge them you can do `merged = JoinLayers(filtered_seurat)` first and then use `LayerData(merged, assay = "RNA", slot = "counts")` to extract your count data.
