### ISSUE TITLE
FinderMarkers error in Integrated analysis of two samples with RefSeq gene name

### ISSUE THREAD

**Issue by Crystalli2018** [satijalab/seurat#799]
I wanted to use a subset of cells that expressed certain genes (count>0) for integrated analysis, so I generated a CSV file using "cellranger mat2csv" command and subset the data. The default gene ID in the csv file is ensembl ID, and the code will finish without any error, but when I replaced the ensembl ID with gene names and removed the duplicate entries, I got an error like this:
```R
#----------------
 Error in 1:nrow(x = countdata.test) : argument of length 0
Calls: FindConservedMarkers -> FindMarkers -> WilcoxDETest -> mysapply -> lapply
In addition: Warning messages:
1: In if (!ident.use.2 %in% object@ident) { :
  the condition has length > 1 and only the first element will be used
2: In if (!ident.use.2 %in% object@ident) { :
  the condition has length > 1 and only the first element will be used
Execution halted
#----------------
```
I wonder if some special symbols in some gene names caused this. Thanks.

**Comment by andrewwbutler** [comment]
This is likely happening because there is no overlap in the genes you're trying to test and the gene names present in the data matrix. At which step did you replace the ensembl IDs with gene names and how did you do that?

**Comment by Crystalli2018** [comment]
I did the ID conversion outside Seurat code in the CSV file, get the subset, then input the subset file to Seurat integration analysis. However, I did come up with an alternative way to get the subset using two WhichCells + rbind commands on the two lists of genes, then intersect the two subset cells to get what I want. Still wonders why the first approach didn't work.
