### ISSUE TITLE
Trouble with MapQuery in V5

### ISSUE THREAD

**Issue by katkatrach** [satijalab/seurat#7990]
Hello!  I am attempting to run a UMAP project via MapQuery. I am unable to get past the first step of creating a anchor set between the query and reference object. I am using the following code to run the anchor search:

`anchors <- FindTransferAnchors(
  reference = ReferenceObject,
  query = QueryObject,
  k.filter = NA,
  reference.reduction = "pca",
  dims = 1:50
)`

And receive this error:

> Projecting cell embeddings
> Error` in rowMeans2(x = reference.data) : 
>  Argument 'dim.' must be an integer vector of length two.

I am having trouble resolving this.  The ReferenceObject is a V3.1.5 object, and the QueryObject is V4.1.4 object, though I get the same error when a V5 QueryObject. Removing the reference.reduction parameter allows the function to work with just a 'Warning: npcs is smaller than the largest value requested by the dims parameter.' However the anchors cannot be used to run the MapQuery function as it is missing the PCA. Both objects do have PCA reductions with embeddings. 

Any help is appreciated! Even if I am just missing a step.

Here is the sessionInfo() output:
> R version 4.3.0 (2023-04-21)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.5 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> locale:
>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
>  [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
>  [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
> 
> time zone: America/Chicago
> tzcode source: system (glibc)
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] Azimuth_0.4.6.9004    shinyBS_0.61.1        SeuratWrappers_0.3.19 pagoda2_1.0.10       
>  [5] igraph_1.5.1          Matrix_1.6-1.1        pdfCluster_1.0-4      patchwork_1.1.3      
>  [9] ggplot2_3.4.3         dplyr_1.1.3           SeuratDisk_0.0.0.9020 Seurat_5.0.0         
> [13] SeuratObject_5.0.0    sp_2.0-0             
> 
> loaded via a namespace (and not attached):
>   [1] ProtGenerics_1.32.0               fs_1.6.3                         
>   [3] matrixStats_1.0.0                 spatstat.sparse_3.0-2            
>   [5] bitops_1.0-7                      DirichletMultinomial_1.42.0      
>   [7] TFBSTools_1.38.0                  devtools_2.4.5                   
>   [9] httr_1.4.7                        RColorBrewer_1.1-3               
>  [11] profvis_0.3.8                     tools_4.3.0                      
>  [13] sctransform_0.4.1                 utf8_1.2.3                       
>  [15] R6_2.5.1                          DT_0.29                          
>  [17] lazyeval_0.2.2                    uwot_0.1.16                      
>  [19] mgcv_1.8-42                       rhdf5filters_1.12.1              
>  [21] urlchecker_1.0.1                  withr_2.5.0                      
>  [23] prettyunits_1.2.0                 gridExtra_2.3                    
>  [25] progressr_0.14.0                  cli_3.6.1                        
>  [27] Biobase_2.60.0                    spatstat.explore_3.2-3           
>  [29] fastDummies_1.7.3                 EnsDb.Hsapiens.v86_2.99.0        
>  [31] shinyjs_2.1.0                     spatstat.data_3.0-1              
>  [33] readr_2.1.4                       ggridges_0.5.4                   
>  [35] pbapply_1.7-2                     Rsamtools_2.16.0                 
>  [37] R.utils_2.12.2                    parallelly_1.36.0                
>  [39] sessioninfo_1.2.2                 BSgenome_1.68.0                  
>  [41] rstudioapi_0.15.0                 RSQLite_2.3.1                    
>  [43] generics_0.1.3                    BiocIO_1.10.0                    
>  [45] gtools_3.9.4                      ica_1.0-3                        
>  [47] spatstat.random_3.1-6             googlesheets4_1.1.1              
>  [49] GO.db_3.17.0                      fansi_1.0.4                      
>  [51] S4Vectors_0.38.2                  abind_1.4-5                      
>  [53] R.methodsS3_1.8.2                 lifecycle_1.0.3                  
>  [55] yaml_2.3.7                        SummarizedExperiment_1.30.2      
>  [57] rhdf5_2.44.0                      BiocFileCache_2.8.0              
>  [59] Rtsne_0.16                        grid_4.3.0                       
>  [61] blob_1.2.4                        promises_1.2.1                   
>  [63] shinydashboard_0.7.2              crayon_1.5.2                     
>  [65] miniUI_0.1.1.1                    lattice_0.21-8                   
>  [67] cowplot_1.1.1                     annotate_1.78.0                  
>  [69] GenomicFeatures_1.52.2            KEGGREST_1.40.0                  
>  [71] pillar_1.9.0                      GenomicRanges_1.52.0             
>  [73] rjson_0.2.21                      future.apply_1.11.0              
>  [75] codetools_0.2-19                  fastmatch_1.1-3                  
>  [77] leiden_0.4.3                      glue_1.6.2                       
>  [79] drat_0.2.3                        data.table_1.14.8                
>  [81] remotes_2.4.2                     vctrs_0.6.3                      
>  [83] png_0.1-8                         spam_2.9-1                       
>  [85] urltools_1.7.3                    cellranger_1.1.0                 
>  [87] poweRlaw_0.70.6                   gtable_0.3.4                     
>  [89] cachem_1.0.8                      dendsort_0.3.4                   
>  [91] Signac_1.9.0.9000                 S4Arrays_1.0.6                   
>  [93] mime_0.12                         pracma_2.4.2                     
>  [95] survival_3.5-5                    gargle_1.5.2                     
>  [97] geometry_0.4.7                    RcppRoll_0.3.0                   
>  [99] N2R_1.0.1                         Rook_1.2                         
> [101] ellipsis_0.3.2                    fitdistrplus_1.1-11              
> [103] brew_1.0-8                        ROCR_1.0-11                      
> [105] nlme_3.1-162                      usethis_2.2.1                    
> [107] bit64_4.0.5                       progress_1.2.2                   
> [109] filelock_1.0.2                    RcppAnnoy_0.0.21                 
> [111] GenomeInfoDb_1.36.3               irlba_2.3.5.1                    
> [113] KernSmooth_2.23-21                seqLogo_1.66.0                   
> [115] colorspace_2.1-0                  BiocGenerics_0.46.0              
> [117] DBI_1.1.3                         tidyselect_1.2.0                 
> [119] processx_3.8.2                    bit_4.0.5                        
> [121] compiler_4.3.0                    curl_5.0.2                       
> [123] hdf5r_1.3.8                       xml2_1.3.5                       
> [125] DelayedArray_0.26.7               plotly_4.10.2                    
> [127] rtracklayer_1.60.1                triebeard_0.4.1                  
> [129] caTools_1.18.2                    scales_1.2.1                     
> [131] lmtest_0.9-40                     callr_3.7.3                      
> [133] rappdirs_0.3.3                    stringr_1.5.0                    
> [135] digest_0.6.33                     goftest_1.2-3                    
> [137] presto_1.0.0                      spatstat.utils_3.0-3             
> [139] XVector_0.40.0                    htmltools_0.5.6                  
> [141] pkgconfig_2.0.3                   MatrixGenerics_1.12.3            
> [143] dbplyr_2.3.3                      fastmap_1.1.1                    
> [145] ensembldb_2.24.1                  rlang_1.1.1                      
> [147] htmlwidgets_1.6.2                 shiny_1.7.5                      
> [149] zoo_1.8-12                        jsonlite_1.8.7                   
> [151] BiocParallel_1.34.2               R.oo_1.25.0                      
> [153] RCurl_1.98-1.12                   magrittr_2.0.3                   
> [155] GenomeInfoDbData_1.2.10           dotCall64_1.0-2                  
> [157] Rhdf5lib_1.22.1                   munsell_0.5.0                    
> [159] Rcpp_1.0.11                       reticulate_1.32.0                
> [161] stringi_1.7.12                    zlibbioc_1.46.0                  
> [163] MASS_7.3-60                       plyr_1.8.8                       
> [165] pkgbuild_1.4.2                    parallel_4.3.0                   
> [167] listenv_0.9.0                     ggrepel_0.9.3                    
> [169] CNEr_1.36.0                       deldir_1.0-9                     
> [171] Biostrings_2.68.1                 sccore_1.0.3                     
> [173] splines_4.3.0                     tensor_1.5                       
> [175] hms_1.1.3                         BSgenome.Hsapiens.UCSC.hg38_1.4.5
> [177] ps_1.7.5                          spatstat.geom_3.2-5              
> [179] RcppHNSW_0.5.0                    reshape2_1.4.4                   
> [181] biomaRt_2.56.1                    stats4_4.3.0                     
> [183] pkgload_1.3.2.1                   TFMPvalue_0.0.9                  
> [185] magic_1.6-1                       XML_3.99-0.14                    
> [187] BiocManager_1.30.21               tzdb_0.4.0                       
> [189] JASPAR2020_0.99.10                httpuv_1.6.11                    
> [191] RANN_2.6.1                        tidyr_1.3.0                      
> [193] RMTstat_0.3.1                     purrr_1.0.2                      
> [195] polyclip_1.10-4                   SeuratData_0.2.2.9001            
> [197] future_1.33.0                     scattermore_1.2                  
> [199] rsvd_1.0.5                        xtable_1.8-4                     
> [201] AnnotationFilter_1.24.0           restfulr_0.0.15                  
> [203] RSpectra_0.16-1                   later_1.3.1                      
> [205] googledrive_2.1.1                 viridisLite_0.4.2                
> [207] tibble_3.2.1                      memoise_2.0.1                    
> [209] AnnotationDbi_1.62.2              GenomicAlignments_1.36.0         
> [211] IRanges_2.34.1                    cluster_2.1.4                    
> [213] globals_0.16.2  
> 

Thank you!

**Comment by zskylarli** [comment]
Hi - when you run MapQuery without the reference.reduction parameter, this indicates that you are simply using the default PCA computed on the reference object, whereas setting it to "pca" would specify the name of dimensional reduction to use as "pca". The 'Warning: npcs is smaller than the largest value requested by the dims parameter.' indicates that when you ran PCA, you did not obtain 50 PCs. Could you check your PCA results in the reduction slot of the Seurat object to check the name it is stored under, and if it has the number of dimensions that you want? Here is the vignette for reference: https://satijalab.org/seurat/articles/integration_mapping.

**Comment by katkatrach** [comment]
Hello! I checked in both the reference and query object. Both have PCA results named 'pca'. The reference object pca has the dimensions [203702 x 50] and the query object pca has the dimensions [114165 x 50]. The reference is missing scale data, could this be part of the issue?

**Comment by Dario-Rocha** [comment]
I am having the same issue even when using as reference and query the exact same object. I just reinstalled Seuratv5 from CRAN

**Comment by McKowen-JK** [comment]
I have the same issue currently. Any solutions?

**Comment by igrabski** [comment]
Hi, the issue is likely due to the different versions of your two objects. If the problem persists even with using two v5 objects, please feel free to open a new issue.
