### ISSUE TITLE
intagrate 10x data - layers not found - 

### ISSUE THREAD

**Issue by RN-Taka** [satijalab/seurat#7995]
Hi, how are you?
Can you help me? 
After merging two seurat objects, I can't find the layers to overlay the clusters and analyze the expression differential expressed genes across conditions.

comand:
zf.data1 <- Read10X(data.dir = "/path/1/filtered_gene_bc_matrices/")
zf.data 2 <- Read10X(data.dir = "/path/2/filtered_gene_bc_matrices/")
zf1 <- CreateSeuratObject(counts = zf.data1, project = "ZF", min.cells = 5, min.features = 200)
zf2 <-CreateSeuratObject(counts = zf.data2, project = "ZF", min.cells = 5, min.features = 200)
combined <- merge(zf1, y= zf2, add.cell.ids = c("1","2"),merge.data=T)

Then,  tried to use this function
combined[["RNA"]] <- split(combined[["RNA"]], f = combined$1)

and didn't work it.

thank you
Rafael

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question. Are you using the latest version of Seurat? If so, after merging, it will keep the layers separate (one counts/data layer for each object that you are merging). If you would like to split by a different variable, then you first need to join these layers and then split. Is "1" the variable you are trying to split by? That is not a valid variable name. You could also consult this [vignette](https://satijalab.org/seurat/articles/essential_commands) for more examples about merging and joining/splitting layers.

**Comment by RN-Taka** [comment]
Hi, 
Yes, I used the version 5.0.0. Now, it apparently worked. but now it seemed like a new error when I tried to plot the reduction dimensin...   
the comand:

zf1 <- CreateSeuratObject(counts = zf.data1, project = "AA", min.cells = 5)
zf1$AA <- 'AA'
zf1 <- PercentageFeatureSet(zf1, pattern = "^mt-", col.name = "percent.mt")
zf1 <- subset(zf1, subset = nFeature_RNA > 50 & percent.mt < 5)

zf2 <-CreateSeuratObject(counts = zf.data2, project = "BB", min.cells = 5)
zf2$BB <- 'BB'
zf2 <- PercentageFeatureSet(zf2, pattern = "^mt-", col.name = "percent.mt")
zf2 <- subset(zf2, subset = nFeature_RNA > 50 & percent.mt < 5)

zfs <- merge(x=zf1, y=zf2)
zfsa <- NormalizeData(zfs)
zfsa <- FindVariableFeatures(zfsa, selection.method = "vst", nfeatures = 1000)
zfsa <- ScaleData(zfsa, do.scale = TRUE , do.center = TRUE, assay="RNA")
zfsa <- RunPCA(zfsa)
zfsa <- FindNeighbors(zfsa, dims = 1:30, reduction = "pca")
zfsa <- FindClusters(zfsa, resolution = 2, cluster.name = "unintegrated_clusters")
zfsa <- RunUMAP(zfsa, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
zfsa
DimPlot(zfsa, reduction = "umap.unintegrated", group.by = c("AA","BB", "seurat_clusters"))
zfsa <- IntegrateLayers(object = zfsa, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
                        verbose = FALSE)
# re-join layers after integration
zfsa[["RNA"]] <- JoinLayers(zfsa[["RNA"]])
zfsa <- FindNeighbors(zfsa, reduction = "integrated.cca", dims = 1:30)
zfsa <- FindClusters(zfsa, resolution = 1)
zfsa <- RunUMAP(zfsa, dims = 1:30, reduction = "integrated.cca")
DimPlot(zfsa, reduction = "umap", split.by = "AA")

error:
Error in `[<-.data.frame`(`*tmp*`, , split.by, value = list(BB = c("BB",  : 
  replacement element 1 has 330 rows, need 484
In addition: Warning message:
Removing 154 cells missing data for vars requested4


thak you !

**Comment by RN-Taka** [comment]
Hi,
thank you, understand the part of the anchor and integrated the objects.

Now, I had problem to generated the "seurat_annotation" file in the step to Identify conserved cell type markers. I know these is formed for barcodes and cluster number, but I can't creat a different variable in meta.data. 
Can you help me?
