### ISSUE TITLE
How to transfer label from scRNA to scATAC after batch removal?

### ISSUE THREAD

**Issue by Yijia-Jiang** [satijalab/seurat#7996]
Hi, I want to transfer label from scRNA to scATAC after batch removal. I could produce the integration of two modalities, but could not transfer labels from RNA to ATAC. The error shows below:
Warning: Please provide a vector that is the same length as the number of reference cells used in anchor finding.
Length of vector provided: 24184
Length of vector required: 0
Skipping element 1.
Error: None of the provided refdata elements are valid.

Below is the code I used, could you help with this issue? Thank you very much.
```r
DefaultAssay(atac) <- "RNA"
atac <- SCTransform(atac,  verbose = FALSE)
DefaultAssay(rna) <- "RNA"
rna <- SCTransform(rna,  verbose = FALSE)

ifnb.list <- list(rna, atac)
features <- SelectIntegrationFeatures(object.list = ifnb.list, nfeatures = 3000)
ifnb.list <- PrepSCTIntegration(object.list = ifnb.list, anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = ifnb.list, normalization.method = "SCT", anchor.features = features,
                                        verbose = FALSE)
integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT", 
                            verbose = FALSE)
integrated <- RunPCA(integrated, verbose = FALSE)
integrated <- RunUMAP(integrated, dims = 1:30, verbose = FALSE)

predicted.labels <- TransferData(
  anchorset = anchors,
  refdata = rna$major_annotation
  weight.reduction = atac[["lsi"]], 
  dims = 1:30
)
```

**Comment by longmanz** [comment]
Hi, 
It is not recommended to use SCTransform() for your ATAC data. Also, you are setting the default assay of your 'atac' object to "RNA"? Or is it actually a multimodal dataset that contains both RNA and ATAT assay? Also, is "LSI" reduction already calculated and stored in your 'atac' object? 
You may follow this vignette (https://satijalab.org/seurat/articles/seurat5_atacseq_integration_vignette) to pre-process your RNA and ATAC objects and then integrate them for label transferring.
