### ISSUE TITLE
AggregateExpression question regarding normalization and counts and data slots for downstream analysis

### ISSUE THREAD

**Issue by MarioCHMGF** [satijalab/seurat#7997]
Hi everyone,
Lately I am mostly figuring out how to proceed with pseudobulk analyses staying in Seurat environment and objects and I have come to some things I don't really understand, so I apologize in advance.
AggregateExpression default slot is data and if we use the function on not normalized object we get the warning "Exponentiation yielded infinite values. `data` may not be log-normed.", which makes sense. But reading the function details it is clearly said, that in case of  return.seurat=T, it performs normalization and scaling before returning the object. 
**Does this mean normalization is performed on sc data and then again when applying AggregateExpression?**

# checking counts sum for a X gene
ifnb <- LoadData("ifnb")

data <- ifnb

sum(data[["RNA"]]$counts[5001,])
[1] 7011

# normalization of data
dataN <- NormalizeData(data)

# aggregation
pseudoN <- AggregateExpression(object = dataN, assays = "RNA", return.seurat = T, group.by="orig.ident")

# aggregated object with normalized data
pseudoN[["RNA"]]$counts[5001,1:2]
IMMUNE-CTRL IMMUNE-STIM 
   16216.69    15242.50  **# Why do I get so inflated counts?**
pseudoN[["RNA"]]$data[5001,1:2]
IMMUNE-CTRL IMMUNE-STIM 
   9.693858    9.631908  **# Is this slot normalized 2 times, before agg and meanwhile agg?**
pseudoN[["RNA"]]$scale.data[5001,1:2]
IMMUNE-CTRL IMMUNE-STIM 
  0.7071068  -0.7071068 

if I use counts slot, the counts make sense and values of all three (counts, data and scale.data) slots are the same no matter if data is prior-normalized or not prior to AggregateExpression:

# aggregation
pseudoNC <- AggregateExpression(object = dataN, assays = "RNA", slot = "counts", return.seurat = T, group.by="orig.ident")

# aggregated object with normalized data using counts slot
pseudoNC[["RNA"]]$counts[5001,1:2]
IMMUNE-CTRL IMMUNE-STIM 
       3534        3477 **# sum is 7011**
pseudoNC[["RNA"]]$data[5001,1:2]
IMMUNE-CTRL IMMUNE-STIM 
   8.170469    8.154213 
pseudoNC[["RNA"]]$scale.data[5001,1:2]
IMMUNE-CTRL IMMUNE-STIM 
  0.7071068  -0.7071068

What I wonder is, if I want to perform pseudobulk using DESeq2 on Seurat object, should I aggregate on prior-normalized object and use data slot or should I just aggregate using counts slot, which is going to be normalized and scaled embedded in AggregateExpression?

Thank you very much in advance for any suggestions!

With kind regards,

Mario

**Comment by mbatiuk** [comment]
I have the same question

Default slot for AggregateExpression is data that contains normalized values

Why is it so? I'm a bit puzzled since there is another normalization and scaling happening after aggregation

Would not it create extra bias if using normalized data for AggregateExpression instead of using raw counts?
