### ISSUE TITLE
identifying different libraries

### ISSUE THREAD

**Issue by amisharin** [satijalab/seurat#80]
Dear Seurat support team, 
I used expression matrix generated from three 10x sc sequencing runs from three libraries (three biological replicates) aggregated together using 10x cellRanger. Is there a way to color-code individual libraries in tSNE plots? 
Is there a way to group cells by libraries in heatmaps? 
Thank you in advance. 
Alexander

**Comment by andrewwbutler** [comment]
Hi Alexander,

If you store the library ID in object@data.info (you can use AddMetaData() for this), then you can add the `group.by` parameter to TSNEPlot() and DoHeatmap() to group cells by library.

**Comment by amisharin** [comment]
Thank you!
