### ISSUE TITLE
Request: add PR-AUC metric

### ISSUE THREAD

**Issue by tantrev** [satijalab/seurat#800]
It would just be really nice if the precision-recall area under curve (PR-AUC) could be added alongside the now-implemented AUC metric.  PR-AUC is especially handy when dealing with imbalanced datasets (e.g. most sub-populations in a scRNA-seq experiment).

The following functions that use AUC could potentially benefit from a PR-AUC implementation:
BatchGene
FindAllMarkers
FindMarkers
FindVariableGenes
MarkerTest

**Comment by satijalab** [comment]
Thanks very much for this comment- which we had thought about but not previously tested.

I did spend some time testing the ability of multiple PR metrics for DE. I was hoping to find, as you suggest, improved identification of marker genes for extremely rare populations. I tested these methods on the pbmc3k dataset, focusing on the rare populations (Megakaryocytes and Dendritic Cells).

I did find that PR-AUC (very slightly) outperformed AUC, but that the Wilcox test was the most successful. This was not a comprehensive survey, and of course biased by what I believe are the 'best' markers of these populations. I would be delighted if someone posted evidence to the contrary, and we would then consider adding additional tests.
