### ISSUE TITLE
ATAC QC

### ISSUE THREAD

**Issue by nboldon** [satijalab/seurat#8002]
Although I don’t have any RNA-seq data to utilize in Seurat, I was hoping that I could import my scATAC-seq data from Cellranger-ATAC into Seurat to test quality control metrics and clustering. When attempting to do so, however, I keep running into the issue of not having feature files to input. Is there a different file type or code that I can use? I haven’t been able to ascertain any solutions from searches or documentation. Thank you!

**Comment by zskylarli** [comment]
Hi - typically, for scATAC-seq data, you'll be working with a fragments file and possibly a peaks file, both outputted by CellRanger-ATAC. Please ensure you have these files available, and try the following commands if you haven't:
```
library(Seurat)
# Replace with the path to your CellRanger-ATAC output
atac.data <- [Read10X_h5](https://satijalab.org/seurat/reference/read10x_h5)("path/to/your/cellranger-atac/output/directory")
seurat.object <- CreateSeuratObject(counts = atac.data, assay = 'ATAC')
```
Let me know if you run into more issues or have additional questions.

**Comment by nboldon** [comment]
Hi Zhuoyan,Thank you very much! One of the reasons I want to test our QC in Seurat is because I am getting very different results in ArchR between fragment and bam files. Is there a way for me to compare these file types in Seurat, or can I only compare fragment and peaks files (both of which I have)?Cheers!NaomiOn Nov 10, 2023, at 1:04 PM, Zhuoyan Li ***@***.***> wrote:﻿
Hi - typically, for scATAC-seq data, you'll be working with a fragments file and possibly a peaks file, both outputted by CellRanger-ATAC. Please ensure you have these files available, and try the following commands if you haven't:
library(Seurat)
# Replace with the path to your CellRanger-ATAC output
atac.data <- [Read10X_h5](https://satijalab.org/seurat/reference/read10x_h5)("path/to/your/cellranger-atac/output/directory")
seurat.object <- CreateSeuratObject(counts = atac.data, assay = 'ATAC')

Let me know if you run into more issues or have additional questions.

**Comment by nboldon** [comment]
Sorry, I guess the better way to ask that question is if I can input any other ATAC files into Seurat other than h5 files?Thanks!NaomiOn Nov 10, 2023, at 1:35 PM, Naomi Boldon ***@***.***> wrote:﻿Hi Zhuoyan,Thank you very much! One of the reasons I want to test our QC in Seurat is because I am getting very different results in ArchR between fragment and bam files. Is there a way for me to compare these file types in Seurat, or can I only compare fragment and peaks files (both of which I have)?Cheers!NaomiOn Nov 10, 2023, at 1:04 PM, Zhuoyan Li ***@***.***> wrote:﻿
Hi - typically, for scATAC-seq data, you'll be working with a fragments file and possibly a peaks file, both outputted by CellRanger-ATAC. Please ensure you have these files available, and try the following commands if you haven't:
library(Seurat)
# Replace with the path to your CellRanger-ATAC output
atac.data <- [Read10X_h5](https://satijalab.org/seurat/reference/read10x_h5)("path/to/your/cellranger-atac/output/directory")
seurat.object <- CreateSeuratObject(counts = atac.data, assay = 'ATAC')

Let me know if you run into more issues or have additional questions.
