### ISSUE TITLE
ScaleData is required when using self normalized data!

### ISSUE THREAD

**Issue by noobCoding** [satijalab/seurat#8003]
It was working in before updating to Seurat 5.0 when I created Seurat object with normalized data and bypass the NormalizeData step before ScaleData.

But it is no longer accepted and cause errors in all my previous codes

**Comment by mhkowalski** [comment]
Hi- thanks for your question. In the previous versions,  "data" was automatically populated with the raw counts prior to running `NormalizeData`, which is no longer the case in v5. Therefore, if you run `ScaleData` and the "data" layer does not exist, this will not work.  

If you want to run `ScaleData` on the raw counts (which I wouldn't recommend doing in most cases), you could do the following:
```pbmc_small <- ScaleData(pbmc_small, layer = "counts")```
