### ISSUE TITLE
DietSeurat probably does not use drop = FALSE, and errors if 1 feature only is selected

### ISSUE THREAD

**Issue by stemangiola** [satijalab/seurat#8005]
DietSeurat probably does not use drop = FALSE, and errors if 1 feature only is selected

```r

pbmc |>   DietSeurat(features = rownames(pbmc)[1])

```

**Comment by igrabski** [comment]
Thanks for bringing this to our attention -- we do not generally recommend subsetting to just a single feature, but we will circle back to this in the future!
