### ISSUE TITLE
RunMultiCCA segfault with large (170k) number of cells

### ISSUE THREAD

**Issue by chenlingantelope** [satijalab/seurat#801]
Is there an upper limit to the number of cells RunMultiCCA? I sent an email with more detailed information with the title "Problem with RunMultiCCA" on September 26.

**Comment by lw157** [comment]
Did you get replied? I have similar problems. Thanks.

**Comment by chenlingantelope** [comment]
@lw157 No I was just told to come here to post an issue

**Comment by andrewwbutler** [comment]
There isn't an explicit upper limit to the number of cells for `RunMultiCCA` though with that many cells, you may be running out of memory. Our integration procedure in v3 (see [vignette here](https://satijalab.org/seurat/pancreas_integration_label_transfer.html)) should be more capable of dealing with data on that scale. If you're still running into this issue with v3, please feel free to open a new issue!
