### ISSUE TITLE
PrepSCTFindMarkers Issue (#7964 follow-up)

### ISSUE THREAD

**Issue by kkearns13** [satijalab/seurat#8013]
Hi @saketkc - tagging you because I am still experiencing issues after following your suggestions to remove and reinstall the Seurat package from CRAN on issue #7964 

After reinstalling Seurat, I tried `PrepSCTFindMarkers` again. My object is version 4.9.9, and I tried `PrepSCTFindMarkers` on both the 4.9.9 object as well as an updated one using `UpdateSeuratObject`, which turned it into 5.0.0.  I'm still getting this error on both:
```
Error in UseMethod(generic = "SCTResults", object = object) : 
  no applicable method for 'SCTResults' applied to an object of class "c('Assay5', 'StdAssay', 'KeyMixin')"
```

Thank you for your help so far!

**Comment by kkearns13** [comment]
I think we figured out a solution to this issue. Here is what worked for us with an object subsetted from an already integrated object following the code from #7964 (with comments showing differences from original post):

```
MO_sub <- subset(test.integrated, idents=c(1,2,3))

# used to be "SCT" not "RNA"
MO_sub[["RNA"]] <- split(MO_sub[["RNA"]], f = MO_sub$orig.ident)

# included `SCTransform` and `RunPCA` -- re-normalize
MO_sub <- SCTransform(MO_sub)
MO_sub <- RunPCA(MO_sub)

# included `normalization.method` option (will not run without it)
MO.integrated <- IntegrateLayers(
  object = MO_sub, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca", normalization.method="SCT",
  verbose = T, assay = "SCT")

MO.integrated <- FindNeighbors(MO.integrated, reduction = "integrated.rpca", 
                                 dims = 1:30)
MO.integrated <- FindClusters(MO.integrated, resolution = 0.5, 
                                cluster.name = "rpca_clusters")

# added `RunPCA` here
MO.integrated <- RunPCA(MO.integrated)

MO.integrated <- RunUMAP(MO.integrated, reduction = "integrated.rpca", 
                           dims = 1:30, reduction.name = "umap.rpca")

MO.integrated <- PrepSCTFindMarkers(MO.integrated)

pbmc.markers <- FindAllMarkers(MO.integrated, only.pos = TRUE, 
                               min.pct = 0.25, logfc.threshold = 0.25, 
                               assay="SCT")
```

I was under the impression that since the datasets in the original integrated object were already normalized individually that we wouldn't need to re-normalize again, but this is what worked for us. @saketkc If you have any thoughts, we'd greatly appreciate it! But I think we are good to go now, thank you for your help!

**Comment by socialtree-yt** [comment]
Hello,I also met this problem without SCT normalization pipeline:

sce=subset(obj,idents = c(2,3,5,6,10,11,18,20,24))
DefaultAssay(sce) <- "RNA"
Idents(sce)=sce$celltype2
scRNAlist=SplitObject(sce,split.by = 'sample')
sce <- merge(scRNAlist[[1]], y=c(scRNAlist[[2]], scRNAlist[[3]], scRNAlist[[4]], scRNAlist[[5]], 
                                           scRNAlist[[6]], scRNAlist[[7]], scRNAlist[[8]], scRNAlist[[9]], 
                                 scRNAlist[[10]], scRNAlist[[11]]))
sce <- NormalizeData(sce)
sce <- FindVariableFeatures(sce)
sce <- ScaleData(sce)
sce <- RunPCA(sce)
obj <- IntegrateLayers(
    orig.reduction = "pca",normalization.method='RNA',assay='RNA',
  object = obj, method = scVIIntegration,
  new.reduction = "integrated.scvi",
  conda_env = "xx", verbose = FALSE
)
when I tried similar ways as you mentioned above, it also failed:
Error in UseMethod(generic = "GetAssay", object = object) :
  no applicable method for 'GetAssay' applied to an object of class "c('Assay5', 'StdAssay', 'KeyMixin')"
Calls: IntegrateLayers ... split_named_unnamed -> eval -> eval -> <Anonymous> -> <Anonymous>

Please help me a lot. I don't know how to resolve this problem, thank you!

**Comment by socialtree-yt** [comment]
> Hello,I also met this problem without SCT normalization pipeline:
> 
> sce=subset(obj,idents = c(2,3,5,6,10,11,18,20,24)) DefaultAssay(sce) <- "RNA" Idents(sce)=sce$celltype2 scRNAlist=SplitObject(sce,split.by = 'sample') sce <- merge(scRNAlist[[1]], y=c(scRNAlist[[2]], scRNAlist[[3]], scRNAlist[[4]], scRNAlist[[5]], scRNAlist[[6]], scRNAlist[[7]], scRNAlist[[8]], scRNAlist[[9]], scRNAlist[[10]], scRNAlist[[11]])) sce <- NormalizeData(sce) sce <- FindVariableFeatures(sce) sce <- ScaleData(sce) sce <- RunPCA(sce) obj <- IntegrateLayers( orig.reduction = "pca",normalization.method='RNA',assay='RNA', object = obj, method = scVIIntegration, new.reduction = "integrated.scvi", conda_env = "xx", verbose = FALSE ) when I tried similar ways as you mentioned above, it also failed: Error in UseMethod(generic = "GetAssay", object = object) : no applicable method for 'GetAssay' applied to an object of class "c('Assay5', 'StdAssay', 'KeyMixin')" Calls: IntegrateLayers ... split_named_unnamed -> eval -> eval -> ->
> 
> Please help me a lot. I don't know how to resolve this problem, thank you!

the "obj" in IntegrateLayers is the "sce" object mentioned above. They are in two different scripts.
