### ISSUE TITLE
Error using subset(): "error in getClassDef()"

### ISSUE THREAD

**Issue by jpvoth** [satijalab/seurat#8014]
Hi - I am using Seurat 5.0.0 in R, and have been compiling a single nucleus RNAseq set. I have successfully compiled the individual samples into one Seurat object, ran PCA and umap on the whole object. At this point, inspecting the metadata I see a new column "seurat_clusters" which represents clusters 0-31  that were ID'ed in the pca/umap, which is as expected. 

I then run the following: 

Idents(seurat) <- "seurat_clusters") # assigning the Idents() to the cluster ID numbers
table(Idents(seurat))

  
 0         1         2        3         4         5         6         7         8        9 
50670 18582 16570 16044 14872 14412 13164 12855  9186  8030 
   10    11      12      13      14      15     16      17      18      19 
 5424  5387  4115  3849  3767  3212  2722  2621  2499  1952 
   20    21       22      23     24     25     26     27     28     29 
 1616  1321  1294   948   771   756   647   259   190   176 
   30 
   66 

--> This is exactly right so far from what I can tell. Basically the cells are properly ID'ed to their respective cluster. (sorry formatting is weird, either way not important to question, basically this confirms that group "3" has values in it). 

So - the next line of code:
test <- subset(x = seurat, idents = "3") # trying to subset all cells in cluster 3

And it kicks this error:
Error in getClassDef(x@superClass, package = packageSlot(x))@virtual : 
  no applicable method for `@` applied to an object of class "NULL"

I cannot find any forum posts with this error so I'm struggling to figure out how to proceed. Any ideas on how to resolve this?

**Comment by jpvoth** [comment]
I'll also say the error message is the same when I go about subsetting a different way as well:

test <- subset(x = seurat, subset = seurat_clusters == "3")

Error in getClassDef(x@superClass, package = packageSlot(x))@virtual : 
  no applicable method for `@` applied to an object of class "NULL"

This makes me think it is some sort of error with my specific Seurat Object formatting when I compiled it, but I am not sure. The getClassDef() command is happening "under the hood" so I'm struggling to see how to resolve it.

**Comment by aodainic7** [comment]
Same for me, neither subset, nor tidyseurat::filter does not work anymore after upgrading to Seurat5. Downgrading to v4.4.0 solved the issue

**Comment by jpvoth** [comment]
Did you simply reinstall Seurat v4.4.0, or did you also reinstall SeuratObjects and other packages as well? I reverted to v4.4.0 and it still is kicking the same error message.

**Comment by jpvoth** [comment]
I can confirm - I had to revert Seurat to v4.4.0 and SeuratObject to v4.1.4, but that did resolve the issue. The line 

test <- subset(seurat, idents = "3") works now.

**Comment by aodainic7** [comment]
down-grade also your Matrix back to 1.6-1.1 with `remotes::install_version("Matrix", version = "1.6-1.1")`

**Comment by igrabski** [comment]
Hi, this issue should be resolved by upgrading to the current versions of Seurat, SeuratObject, and Matrix.
