### ISSUE TITLE
Switch Vignette according to Seurat Version

### ISSUE THREAD

**Issue by robingarcia** [satijalab/seurat#8016]
The vignette "Introduction to scRNA-seq integration" shows the latest veersion (here: 5.0.0)
https://satijalab.org/seurat/articles/integration_introduction

How can I call up the vignette for an earlier version (e.g. 4.3.0)?

**Comment by robingarcia** [comment]
Okay. This solution worked: https://satijalab.org/seurat/archive/v4.3/integration_introduction

But this vignette was not included in https://satijalab.org/seurat/articles/archive

**Comment by mhkowalski** [comment]
Hi, 

We have an updated archive here: `https://satijalab.org/seurat/articles/archive`. Please let us know if you are not able to find previous versions there, thanks!
