### ISSUE TITLE
Multiome analysis - Exporting Peak Information Following Clustering

### ISSUE THREAD

**Issue by slives-lab** [satijalab/seurat#8017]
Regarding multiome analysis (snATAC + expression) I am following the multiome tutorial: 

https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis 

I am wondering how to export peaks associated with specific clusters. I have defined seurat_clusters and celltype, but I am uncertain about how to export the corresponding peaks for these clusters.

**Comment by igrabski** [comment]
Hi, please see the [Signac vignettes](https://stuartlab.org/signac/articles/overview) for more detailed examples of ATAC analysis.
