### ISSUE TITLE
Retain all genes after running SCTransform

### ISSUE THREAD

**Issue by yesitsjess** [satijalab/seurat#8018]
I'm losing genes from my dataset after running SCTransform that I'd like to keep.

`sctrans <- SCTransform(object=proj, vst.flavor="v2", verbose=F, method="glmGamPoi", conserve.memory=T)`

```
> orig
An object of class Seurat 
36601 features across 295148 samples within 1 assay 
Active assay: RNA (**36601** features, 0 variable features)
```

```
> sctrans
An object of class Seurat 
70604 features across 295148 samples within 2 assays 
Active assay: SCT (**34003** features, 3000 variable features)
```
I've searched for similar issues but the answer to these is usually a redirect to [here](https://github.com/satijalab/seurat/issues/2128). Unless I'm misunderstanding the answer this doesn't help me because there's 5505 samples expressing one of the lost genes, so I don't think it will be retained by decreasing `min_cells`.

I tried adding `return.only.var.genes=F` but then I get the following message:
`Will not return corrected UMI because residual type is not set to 'pearson'`
this means `sctransform::correct` will not be run but I'm not sure of the ramifications of missing this step. 

Could anyone offer advice please?

**Comment by saketkc** [comment]
I am not sure retaining genes that are lowly expressed (have non-zero UMI in 5 cells or less) is generally that useful, but you could do this:

```r
sctrans <- SCTransform(object=proj, vst.flavor="v2", verbose=F,  conserve.memory=T, min_cells=1, return.only.var.genes=F)
```
If you run into issues, please feel free to email me the object and I can tkae a look: schoudhary@nygenome.org

**Comment by MWRR** [comment]
I got same when I run SCTransform
`merged.SCT <- SCTransform(merged.singlets, vars.to.regress =c("nFeature_RNA", "nCount_RNA", "percent.mt"),
			 vst.flavor="v2", min_cells=1,
			 variable.features.n = 3000, verbose = FALSE,
			conserve.memory = TRUE,
			return.only.var.genes = TRUE)`
any solution?
