### ISSUE TITLE
extracting genes on certain chromosome

### ISSUE THREAD

**Issue by tsotnech** [satijalab/seurat#802]
Hi everyone,

I have bunch of 10X libraries, that I'm analyzing with Seurat. I've subset the cell populations that I'm interested in and now I want to extract the expression of all the genes from certain chromosome. I couldn't find if Seurat object actually saves the gene locations somewhere. Is there an easy way of going through the expression of my subset cells and extracting only expression of genes from certain chromosome? 

Thanks a lot,

Tsotne

**Comment by andrewwbutler** [comment]
Hi Tsotne,

Seurat doesn't currently save the gene locations anywhere. However, if you have the mapping from gene to chromosome, it should be fairly straightforward to subset the matrices. For a more detailed description of what is stored in the data slots, please see [FAQ 7](https://satijalab.org/seurat/faq).
