### ISSUE TITLE
Outdated function arguments in a vignette about using future

### ISSUE THREAD

**Issue by Cleiti** [satijalab/seurat#8020]
https://github.com/satijalab/seurat/blame/ca4c48b6300d7c10857e2d59a8ddee2858c7e2fc/vignettes/future_vignette.Rmd#L43

This vignette seems to be for V3 despite the page being compiled in sep2023: all code within is creating errors. Seems to be because the term "multiprocess" is no longer recognized by future, but "multisession" seems to work instead, so updating that might fix the vignette to be relevant for latest versions of seurat.

**Comment by ppm1337** [comment]
Exactly. [HenrikBengtsson](https://github.com/HenrikBengtsson), the author of future, [commented earlier on this problem in a previous issue](https://github.com/satijalab/seurat/issues/7185#issuecomment-1616422768).

See #7185

**Comment by mvhunter1** [comment]
Running into this issue as well while trying to integrate a huge dataset.

**Comment by igrabski** [comment]
Thanks for pointing this out! We actually no longer support / use the future vignette, so please disregard the older versions of that vignette.

**Comment by nick-youngblut** [comment]
> Thanks for pointing this out! We actually no longer support / use the future vignette, so please disregard the older versions of that vignette.

@igrabski  Is there a vignette on parallel processing for Seurat v5? I don't see one. Future is used in some vignettes (e.g., https://satijalab.org/seurat/articles/seurat5_integration), but I don't see docs on actually using future (e.g., `library(future); plan("multisession", workers = 4)`).

It's a bit dangerous to have the only vignette that pops up in a search as https://satijalab.org/seurat/archive/v4.3/future_vignette, in which the docs state:

```
`plan("multiprocess", workers = 4)`
```

...but [multiprocess is deprecated](https://www.rdocumentation.org/packages/future/versions/1.30.0/topics/multiprocess)

**Comment by igrabski** [comment]
We don't currently actively maintain parallel processing for Seurat v5. Our current vignettes can be found on [this page](https://satijalab.org/seurat/articles/get_started_v5_new); the one you linked it is part of our archived vignettes, which do sometimes come up in external search engine results.

**Comment by nick-youngblut** [comment]
Thanks @igrabski for the info! 

Why isn't parallel processing supported? I thought that a major feature of v5 was "Flexible, interactive, and highly scalable analsyis", so one would likely think that parallel processing would be a key component of *scalable*. 

Just to check are there any plans on integrating GPU acceleration, as is [being done for scanpy](https://developer.nvidia.com/blog/gpu-accelerated-single-cell-rna-analysis-with-rapids-singlecell/)?

**Comment by igrabski** [comment]
At this time, we don't have the bandwidth for those features, though certainly we are very open to external collaborations or contributions! Otherwise, we hope to continue expanding functionality in the future as bandwidth allows.

**Comment by nick-youngblut** [comment]
Thanks @igrabski for the info! We will probably be switching to RAPIDS-singlecell as our datasets get larger, but that's really only because we have access to large GPUs.
