### ISSUE TITLE
Error in CreateSeuratObject

### ISSUE THREAD

**Issue by pati-ni** [satijalab/seurat#8021]
Hi our vignette is causing problems. We think it is related to the latest version of Seurat.

This is the command we are using:
```R
pbmc <- CreateSeuratObject(counts = cbind(pbmc.stim, pbmc.ctrl), project = "PBMC", min.cells = 5)
```
This command gives this error:

```
Error in validObject(.Object) : 
  invalid class “LogMap” object: superclass "mMatrix" not defined in the environment of the object's class
```

Other users have experienced the error, please see below.

https://community.rstudio.com/t/seurat-functions-throwing-error-messages-due-to-conflicting-packages/176936

This was all when we submitted our vignette in CRAN. As a result, I don't have the `sessionInfo()`.

I did *not* reproduce locally and I don't want to install the problematic version of Seurat at this moment.

**Comment by samuel-marsh** [comment]
Hi,

This appears to likely be error not caused by Seurat but by latest version of matrix package.  See previous issues: https://github.com/satijalab/seurat/issues/7993#issuecomment-1806436852.  Try downgrading matrix package and seeing if that solves the issue.

Best,
Sam

**Comment by longmanz** [comment]
Hi,
Thank you @samuel-marsh for your help! 
To @pati-ni , as suggested, please try to down-grade your Matrix package to <= 1.6-1.1. If the issue persists, I will reopen the issue.

**Comment by pati-ni** [comment]
Here is what the matrix devs pointed out:

> There is no bug.  Reinstall SeuratObject from sources to get a build compatible with the currently installed Matrix version (whatever it is).  Unfortunately, CRAN has been slow to re-install affected packages on its pretest machines.

I can not influence the build environment of CRAN so I am unsure why this is the proposed solution
