### ISSUE TITLE
Generated Annotaions file -seurat object

### ISSUE THREAD

**Issue by RN-Taka** [satijalab/seurat#8023]
Hi,
I run the Integrated and Identify differential expressed genes across conditions pipelines. But I don't find how to generated the annotations file to use in the "AggregateExpression" function. I know these is formed for barcodes and cluster number, and add with the  "Seurat::AddMetaData" function, but I couldn't creat it.

Can you help me? How to generated the file with barcodes and cell type ?

best

**Comment by mhkowalski** [comment]
Hi, I'm not sure that I understand. There are a variety of ways you could generate annotations for your data,  including manual annotation such as [here](https://satijalab.org/seurat/articles/pbmc3k_tutorial), or [reference mapping](https://satijalab.org/seurat/articles/integration_mapping) to another dataset. 

Please let me know if this doesn't answer your question, if you could clarify further what you mean.

**Comment by RN-Taka** [comment]
Sory, i'm so laty.

it solved.
thank you !
