### ISSUE TITLE
Possible reasons for UMAP reduction to present fragmented points

### ISSUE THREAD

**Issue by SonghaoLuo** [satijalab/seurat#8024]
I am trying to compute new features using gene expression information from single-cell data, and then visualize UMAP reduction of these features, but it seems that there are many small dots appearing sporadically in the neighborhood of the larger classes. May I ask empirically what might be causing this situation?

seurat_obj <- NormalizeData(seurat_obj) %>% 
                        ScaleData() %>% 
                        FindVariableFeatures() %>%
                        RunPCA() %>%
                        RunUMAP(dims = 1:5) %>%
                        FindNeighbors(dims = 1:5) %>%
                        FindClusters(resolution = 0.1)

<img width="486" alt="image" src="https://github.com/satijalab/seurat/assets/138028157/995fe9fd-dc57-42ac-9e5f-37fdc673c3f5">

This figure shows the case when I take a 1:5 dimensional PCA component. If I take 1:10 or more, the points will be more scattered, such as:

<img width="483" alt="image" src="https://github.com/satijalab/seurat/assets/138028157/6280b55b-c13a-4095-97f2-0110dfba9652">

I think the new feature quantities I calculated reflect cell-specific information to some extent, but there's always something like noise that perhaps needs to be analyzed at a finer level.

**Comment by igrabski** [comment]
Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum.
