### ISSUE TITLE
Batch effect removal from 10x visium ST data i.e Each slide with multiple tissue sample 

### ISSUE THREAD

**Issue by archanabhardwaj** [satijalab/seurat#8027]
Hello everyone
 
I am working on 10x visium spatial transcirptome data from multiple slides. In our experiment design, we basically have sequence data from two slides and processed in Space ranger pipeline for get feature matrix from each slide. For downstream analysis, I am using Seurat method with information given at https://satijalab.org/seurat/articles/sctransform_v2_vignette.
 
However, each slide has data from three tissues samples.  
Slide 1 : Control1, Treatment 1-1, Treatment2-1
Slide 2 : Control2 , Treatment 1-2, Treatment2-2
 
I would like to create integrate object from two slides with proper batch effect. Here are key steps I am following for my data processing : 

step 1 :  Normalization of  each slide 
 slide1 <- SCTransform(slide1, vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)

 slide2 <- SCTransform(slide2, vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)

In order to remove any sub-sample level batch effect, I am wondering if I should include sample id from each slide in "vars.to.regress" variable ? 

For downstream analysis, I am  following the steps given in the tutorial. 

I plan to integrate the two datasets using SelectIntegrationFeatures, PrepSCTIntegration, and FindIntegrationAnchors functions.

Step 2 : integration of two datasets 
st.list <- list(data1= slide1, data2 = slide2)
features <- SelectIntegrationFeatures(object.list = st.list, nfeatures = 3000)
st.list <- PrepSCTIntegration(object.list = st.list, anchor.features = features)

st.anchors <- FindIntegrationAnchors(object.list = st.list, normalization.method = "SCT",
    anchor.features = features)
st.combined.sct <- IntegrateData(anchorset = st.anchors, normalization.method = "SCT")

st.combined.sct <- RunPCA(st.combined.sct, verbose = FALSE)
st.combined.sct <- RunUMAP(st.combined.sct, reduction = "pca", dims = 1:30, verbose = FALSE)
st.combined.sct <- FindNeighbors(st.combined.sct, reduction = "pca", dims = 1:30)
st.combined.sct <- FindClusters(st.combined.sct, resolution = 0.2)

I would appreciate all the suggestion!!

**Comment by saketkc** [comment]
I would recommend running `SCTransform` on each sample individually:

```r
st.list <- lapply(st.list, SCTransform, vst.flavor="v2")
features <- SelectIntegrationFeatures(object.list = st.list, nfeatures = 3000)
st.list <- PrepSCTIntegration(object.list = st.list, anchor.features = features)
```
