### ISSUE TITLE
Variable features and scale.data missing in integrated object. 

### ISSUE THREAD

**Issue by martuskaR** [satijalab/seurat#8031]
Hello, @timoast @yuhanH 

I integrated two different object lists, one with standard integration (protein data), and the other with SCT (ran data) (all seurat4.3). I want to combine them and run win analysis. The issue I am facing is that when I try to run RunPCA() after data integration I get the following error. 

> integrated_abseq_sct <- RunPCA(integrated_abseq_sct, assay = 'Integratedabseq', reduction.name = 'apca')
Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.

I tried to solve it by finding variable features of unintegrated assay and passing the vector in RunPCA(). This threw another error:
> integrated_abseq_sct <- RunPCA(integrated_abseq_sct, assay = 'Integratedabseq', reduction.name = 'apca', integrated_abseq_sct@assays[["AbSeq"]]@var.features)
Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Data has not been scaled. Please run ScaleData and retry

In the sct integrated object I seem to have scale data and var.features although I don't understand why this is the case. 

The problem is that in multiple issues on GitHub, I read people saying you should not run ScaleData() nor FindVariableFeatures() on integrated assay. However, I need these to run PCA. What would be the solution? I am very confused after reading in multiple posts and SCT integration tutorial (https://satijalab.org/seurat/archive/v3.0/integration.html) that ScaleData should not be run on integrated data. At the same time, both in here https://satijalab.org/seurat/archive/v3.0/integration.html and in here https://satijalab.org/seurat/archive/v3.0/immune_alignment.html scale data is run on integrated  data. 

Could you kindly help me to find a solution with explanation as I don't have bioinformatics background. 

Thank you,
Marta

**Comment by igrabski** [comment]
Hi, I am closing this issue because it has been some time, but if you are still experiencing these problems, please feel free to open a new issue and please both describe how you created your object `integrated_abseq_sct` and please show the output `sessionInfo()`.
