### ISSUE TITLE
Detection rate in SCT assay

### ISSUE THREAD

**Issue by siddharthamantrala** [satijalab/seurat#8032]
Hi Everyone, 
I came across this command with the SCT assay of my seurat object `seurat_integrated@assays$SCT@SCTModel.list$model1@feature.attributes`, it has `detection_rate`  as one of its columns. 
Could anyone suggest/explain on what does it represent and why is it only available in the SCT and integrated assay but not in the RNA assay of my seurat object? Also the values differ for the same set genes in SCT assay and integrated assay.

Thank You,
Siddhartha

**Comment by saketkc** [comment]
Hi @siddharthamantrala, `detection_rate` is the proportion of cells the gene has at least 1 UMI. Hope this helps.
