### ISSUE TITLE
DE analysis and heatmap generation after SCTransform

### ISSUE THREAD

**Issue by DeySayanti** [satijalab/seurat#8035]
Hello Seurat Team,

I did check my question, but the answers were from late 2020. So I was wondering if there could be new explanations based on your current development.
Question:
I have different runs of 10x data and I have 2 different conditions as well. In total 5 datasets, that I have integrated successfully using Seurat 4.3.0 guidelines. I have used SCtransform for the normalization and scaling purposes. Used SCT assay before subseting (and ran PrepSCTFindMarkers wherever needed) for functions like FeaturePlot, VlnPlot, FindMarkers using the guidelines. 

My question is, when in a similar downstream analysis I am trying to obtain top10 genes from my clusters (irrespective of the difference between 2 conditions) using FindAllMarkers function and trying to plot a heatmap (using DoHeatmap (object, features= top10genesfromeachcluster$gene))  things are very bright. And looks like some genes are very high in cluster 0, 1, 2 as indicated in the image below.

Any suggestions to how I can make it better using SCT assay only?  or, How I can use RNA assay if the initial integrated objected is SCtransformed?

![heatmap](https://github.com/satijalab/seurat/assets/111168514/ee02e76c-4810-4c20-aa19-86df34b3202c)

**Comment by DeySayanti** [comment]
Here is the whole code what  I am using.

set.seed(4500000)
options(future.globals.maxSize = 1000 * 1024^2)

library(Seurat)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(dplyr)
library(tidyr)
library(future)
library(SingleR)
library(ExperimentHub)
library(Matrix)
library(cowplot)
library(sctransform)
library(glmGamPoi)
library(monocle3)
library(SeuratWrappers)
library(hdf5r)
library(multtest)
library(metap)
library(RColorBrewer)


URL1 <- "D:/Rfiles/R/seq1ana1/unvaccinated_filtered_feature_bc_matrix"
URL2 <- "D:/Rfiles/R/seq1ana1/vaccinated_filtered_feature_bc_matrix"
URL3 <- "D:/Rfiles/R/seq2ana2/unvaccinated_filtered_feature_bc_matrix"
URL4 <- "D:/Rfiles/R/seq2ana2/vaccinated_filtered_feature_bc_matrix"
URL5 <- "D:/Rfiles/R/seq3ana3/vaccinated_filtered_feature_bc_matrix"
URL6 <- "D:/Rfiles/R/seq5ana5/vaccinated_filtered_feature_bc_matrix"
URL7 <- "D:/Rfiles/R/seq4ana4/vehicle_filtered_feature_bc_matrix"

#load un vaccinated data set and Initialize the Seurat object with the raw (non-normalized data).

unvaccinated1.data <- Read10X(data.dir = URL1)
unvaccinated1 <- CreateSeuratObject(counts = unvaccinated1.data, project = "1", min.cells = 0, min.features = 0)

unvaccinated2.data <- Read10X(data.dir = URL3)
unvaccinated2 <- CreateSeuratObject(counts = unvaccinated2.data, project = "2", min.cells = 0, min.features = 0)

vaccinated1.data <- Read10X(data.dir = URL2)
vaccinated1 <- CreateSeuratObject(counts = vaccinated1.data, project = "3", min.cells = 0, min.features = 0)

vaccinated2.data <- Read10X(data.dir = URL4)
vaccinated2 <- CreateSeuratObject(counts = vaccinated2.data, project = "4", min.cells = 0, min.features = 0)

vaccinated3.data <- Read10X(data.dir = URL5)
vaccinated3 <- CreateSeuratObject(counts = vaccinated3.data, project = "5", min.cells = 0, min.features = 0)

vaccinated5.data <- Read10X(data.dir = URL6)
vaccinated5 <- CreateSeuratObject(counts = vaccinated5.data, project = "6", min.cells = 0, min.features = 0)

vehicle.data <- Read10X(data.dir = URL7)
vehicle <- CreateSeuratObject(counts = vehicle.data, project = "7", min.cells = 0, min.features = 0)

merged.data <- merge(x = unvaccinated1, y = c(unvaccinated2, vaccinated1, vaccinated2, vaccinated3), add.cell.ids = c("unvaccinated_1_1", "unvaccinated_2_2", "vaccinated_1_3","vaccinated_2_4","vaccinated_3_5" ))
merged.data$sample <- rownames(merged.data@meta.data)

# split sample column
merged.data@meta.data <- separate(merged.data@meta.data, col = 'sample', into = c('Type','Run_No','Dataset','Barcode'), 
                                  sep = '_')
# calculate mitochondrial percentage
merged.data$MitoPercent <- PercentageFeatureSet(merged.data, pattern='^mt-')
merged.data$RiboPercent <- PercentageFeatureSet(merged.data, pattern='^rp[sl]')

# explore QC
VlnPlot(merged.data, features = c("nFeature_RNA", "nCount_RNA", "MitoPercent"), ncol = 3)
FeatureScatter(merged.data, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")+
  geom_smooth(method = 'lm')

# filtering
merged_filtered <- subset(merged.data, subset = nFeature_RNA > 500 & nFeature_RNA <7000 & nCount_RNA <50000 &
                            MitoPercent < 10)
VlnPlot(merged_filtered, features = c("nFeature_RNA", "nCount_RNA", "MitoPercent"), ncol = 3)
FeatureScatter(merged_filtered, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")+
  geom_smooth(method = 'lm')

# perform integration to correct for batch effects ------
obj.list <- SplitObject(merged_filtered, split.by = 'orig.ident')
for(i in 1:length(obj.list)){
  obj.list[[i]] <- SCTransform(object = obj.list[[i]], vars.to.regress = "MitoPercent", vst.flavor = "v2", verbose = FALSE)%>%
    RunPCA(npcs = 30, verbose = FALSE)
  
}
# select integration features
features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 3000)
obj.list <- PrepSCTIntegration(object.list = obj.list, anchor.features = features)

# find integration anchors (CCA)
anchors <- FindIntegrationAnchors(object.list = obj.list, normalization.method = "SCT", anchor.features = features)

# integrate data
integrated_data <- IntegrateData(anchorset = anchors,  normalization.method = "SCT")

# Scale data, run PCA and UMAP and visualize integrated data
integrated_data <- RunPCA(object = integrated_data)
ElbowPlot(integrated_data, ndims = 50)
integrated_data <- RunUMAP(object = integrated_data, dims = 1:30)
integrated_data<- FindNeighbors(integrated_data, reduction = "pca", dims = 1:30)
integrated_data <- FindClusters(integrated_data, resolution = 0.5)

#Dimplot and plotting by different runs to check if the bacth effect is removed after integration
DimPlot(integrated_data, reduction = 'umap', label = TRUE)
DimPlot(integrated_data, reduction = 'umap', group.by = 'Run_No')

# Further downstream analysis is a comparison between type unvaccinated and vaccinated

DimPlot(integrated_data, reduction = 'umap', split.by = "Type",label = TRUE)

DefaultAssay(integrated_data) <- "SCT"
FeaturePlot(integrated_data, features = "Ptprc", split.by = "Type", label = TRUE)
VlnPlot(integrated_data, features = c("Klrb1c","Klra3", "Klra9","Gzmb","Eomes", "Prf1", "Nkg7", "Il7r", "Cxcr3", "Cxcr6"), idents = c(1,8,16,20,29,32), split.by = "Type")

integrated_data$treatment <- paste(integrated_data$seurat_clusters, integrated_data$Type, sep = "_")
DefaultAssay(integrated_data) <- "integrated"

#subclustering level1 (immune cell)
DefaultAssay(integrated_data) <- "integrated"
integrateCD45 <- subset(integrated_data, subset = Ptprc>0)
integrateCD45 <- RunPCA(object = integrateCD45)
ElbowPlot(integrateCD45, ndims = 50)
integrateCD45 <- RunUMAP(object = integrateCD45, dims = 1:20)
integrateCD45<- FindNeighbors(integrateCD45, reduction = "pca", dims = 1:20)
integrateCD45 <- FindClusters(integrateCD45, resolution = 0.3)
DimPlot(integrateCD45, reduction = 'umap', label = TRUE)
DefaultAssay(integrateCD45) <- "SCT"
integrateCD45 <- PrepSCTFindMarkers(integrateCD45)
integrateCD45.markers <- FindAllMarkers(integrateCD45, only.pos = TRUE,  min.diff.pct = 0.25, recorrect_umi = FALSE)
top10cd45 <- integrateCD45.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DoHeatmap(integrateCD45, features = top10cd45$gene, assay = 'SCT') + NoLegend()
DefaultAssay(integrateCD45) <- "integrated"
#subclustering level2 (NK cell population)
NK_cell <- subset(integrateCD45, subset = Klrb1c > 0 & Ncr1 > 0 )
NK_cell <- RunPCA(NK_cell)
ElbowPlot (NK_cell) 
NK_cell <- FindNeighbors(object = NK_cell, dims = 1:8)
NK_cell <- FindClusters(object = NK_cell, resolution = 0.08)
NK_cell <- RunUMAP(object = NK_cell, dims = 1:8)
View(NK_cell@meta.data)
DimPlot(NK_cell, reduction = 'umap', split.by = "Type",label = TRUE)
FeaturePlot(NK_cell, features = "Klra3",  split.by = "Type",label = TRUE)
DefaultAssay(NK_cell) <- "SCT"
NK_cell <- PrepSCTFindMarkers(NK_cell)
NK_cell.markers <- FindAllMarkers(NK_cell, only.pos = TRUE,  min.diff.pct = 0.23, recorrect_umi = FALSE)
top10 <- NK_cell.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DoHeatmap(NK_cell, features = top10$gene, assay = 'SCT') + NoLegend()

**Comment by DeySayanti** [comment]
Any insight? @saketkc

I would be really grateful!!!

**Comment by saketkc** [comment]
If you would like to use the RNA assay for visualization (slightly more appropriate here given difference in residuals across objects), here is how you can do it:

```
DefaultAssay(object) <- "RNA"
object <- NormalizeData(object)
object <- ScaleData(object, features = markers.gene)
DoHeatmap(object, features=markers.gene)
```

**Comment by kaqisekuzi** [comment]
> If you would like to use the RNA assay for visualization (slightly more appropriate here given difference in residuals across objects), here is how you can do it:
> 
> ```
> DefaultAssay(object) <- "RNA"
> object <- NormalizeData(object)
> object <- ScaleData(object, features = markers.gene)
> DoHeatmap(object, features=markers.gene)
> ```


@saketkc Hello, I have a similar question. 
Question 1: Is it necessary to perform two steps on RNA assay: "NormalizeData" and "ScaleData" before using the FindAllMarkers() function to find differentially expressed genes for different cell types?

Question 2: Is it necessary to perform two steps, "NormalizeData" and "ScaleData", on RNA assay before using the FindMarkers() function to find inter group differentially expressed genes under different control conditions (control vs. case)?

I am very much looking forward to your reply, which is very important to me. Thank you very much
