### ISSUE TITLE
How to load Xenium when I have cell_feature_matrix.h5 instead of barcodes, matrix and features folder?

### ISSUE THREAD

**Issue by sailseem** [satijalab/seurat#8036]
Dear developer,
As in the tile, how to LoadXenium when I have cell_feature_matrix.h5 instead of barcodes, matrix and features folder?

Thanks a lot for your valuable time!!

**Comment by alikhuseynov** [comment]
it doesn't seem to be implemented to support `cell_feature_matrix.h5`
https://github.com/satijalab/seurat/blob/develop/R/preprocessing.R#L2155-L2161
The standard XeniumRanger output always has `cell_feature_matrix` folder

**Comment by igrabski** [comment]
Hi, at this time we do not support `cell_feature_matrix.h5`.
