### ISSUE TITLE
Issue with R crashing and restarting during runPCA in Seurat v5

### ISSUE THREAD

**Issue by lisch7** [satijalab/seurat#8037]
Hi there,

I hope you're doing well. I am currently facing an issue while using Seurat v5. Specifically, I am encountering a problem where R crashes and restarts during the RunPCA step in the standard workflow. In terms of equipment, I am using a server with sufficient memory (1T).  And my project involved ~120w cells with 36766 features .

I would greatly appreciate any assistance or insights you can provide to help me resolve this issue. Please let me know if you need any additional information from my end.

Thank you in advance for your help!

**Comment by igrabski** [comment]
Hi Lisch, can you share all the code you are using up to this step? In particular, have you run `FindVariableFeatures` (or alternatively `SCTransform` if you are using that workflow) prior to running `RunPCA`?

**Comment by lisch7** [comment]
Thanks for your kind reply. My code is as follows:

```
sce[["RNA"]] <- split(sce[["RNA"]], f = sce$study)
sce <- NormalizeData(sce, normalization.method = 'LogNormalize', scale.factor = 10000)
sce <- FindVariableFeatures(sce, selection.method = "vst", nfeatures = 2000)
sce <- FindVariableFeatures(sce, selection.method = "vst",nfeatures = 2000)
sce <- ScaleData(sce) # vars.to.regress = "percent.mt"
sce <- RunPCA(sce) 
```

But I have found out that the problem may be solved by use the following code:

```
sce[["RNA"]] <- split(sce[["RNA"]], f = sce$study)
sce <- NormalizeData(sce, normalization.method = 'LogNormalize', scale.factor = 10000)
sce <- FindVariableFeatures(sce, selection.method = "vst", nfeatures = 2000)
sce <- SketchData(
  object = sce,
  ncells = 50000,
  method = "LeverageScore",
  sketched.assay = "sketch"
)
DefaultAssay(sce) <- "sketch"
sce <- FindVariableFeatures(sce, selection.method = "vst",nfeatures = 2000)
sce <- ScaleData(sce) # vars.to.regress = "percent.mt"
sce <- RunPCA(sce) 
```
