### ISSUE TITLE
FindMarkers() for pseudobulk

### ISSUE THREAD

**Issue by yeaeunhan** [satijalab/seurat#8043]
In the vignette for [Differential expression testing](https://satijalab.org/seurat/articles/de_vignette) , I'm wondering if the FindMarkers() is supposed to work for the pseudobulk because ValidateCellGroups function is asking for more than 3 cells in each group and I think the aggregation was supposed to produce one bulk for group... right?

Also, there's a typo in the following:

```
only_sc <- merge_dat$gene[which(merge_dat$p_val.bulk > 0.05 & 
                                  merge_dat$p_val.sc < 0.05)]
only_bulk <- merge_dat$gene[which(merge_dat$p_val.bulk < 0.05 & 
                                    merge_dat$p_val.sc > 0.05)]
```

should be

```
only_sc <- merge_dat$gene[which(merge_dat$p_val.sc > 0.05 & 
                                  merge_dat$p_val.sc < 0.05)]
only_bulk <- merge_dat$gene[which(merge_dat$p_val.bulk < 0.05 & 
                                    merge_dat$p_val.bulk > 0.05)]
```

Thank you!

**Comment by longmanz** [comment]
Hi,
1. If you only have 1 or 2 groups/samples, then it is not recommended to do pseudobulk based on the group identity. Using single-cell level data to perform DE-test is okay. 
2. Thank you for your suggestion, but that is not a typo. We aim to extract the DE genes that are only significant (p<=0.05) in one test but not in the other (p>0.05).
