### ISSUE TITLE
Join Layers question

### ISSUE THREAD

**Issue by AnjaliS1** [satijalab/seurat#8044]
Hi, I'm using the Seurat v5 vignette for integration. I have carried out different integrations on my datasets just like in the tutorial e.g. cca, rpca and harmony. However, I don't understand what join layers is doing? How is it deciding which integration method to go ahead with in order to create the final counts, data and scale data files? There does not seem to be an option to specify, for example if I only want to keep the harmony integration, and I want to go ahead with that. Could someone explain the process to me and what I would need to do additionally in my code to merge the datasets based on the harmony integration?

**Comment by zskylarli** [comment]
Hi - JoinLayers does not perform integration, but joins a merged object back into a single layer. You can check our commands vignette [here](https://satijalab.org/seurat/articles/essential_commands) for more information. For IntegrateLayers,you can specify the integration method, and it will be saved in a reduction slot with a corresponding name (e.g. if you use CCA integration, it is saved to integrated.cca, or whatever new reduction name you specify), and will still be in that slot after you perform JoinLayers. You can then use that for downstream analysis. Note that all of the integration methods implemented in Seurat perform integration in the lower dimensional space, and does not alter the counts matrix. If you have any other questions, feel free to reopen this issue.

**Comment by AnjaliS1** [comment]
Hi, thank you for getting back to me so quickly. I am interested in integrating the data, i.e. the counts, data and scale.data of two datasets. If JoinLayers after IntegrateLayers, does not integrate the counts, then how do I integrate the count data for downstream analysis? I do not only want to have an integrated reduction plot.
