### ISSUE TITLE
Is there a way to plot Heatmap of AE by cell type

### ISSUE THREAD

**Issue by Jiayi-Zheng** [satijalab/seurat#8048]
Hello, I want to do a key marker heatmap with averaged expression. So I tried to make a new seurat object by `AverageExpression()` and `return.seurat = T`. However, when I do `DoHeatmap()` on the acquired AE seurat. It gives me this:
<img width="429" alt="Screen Shot 2023-11-17 at 10 34 53 PM" src="https://github.com/satijalab/seurat/assets/90501211/bdb06a37-f0b3-4958-b675-1ddda23d585e">

With a large white space between the columns of data, as separation between cells of different ident. I wonder if there is a way that I can remove the white space between? Looking over the DoHeatmap() manual didn't give me such an option... I see some publications have this kind of figure. I just can't figure out what function combination did they use to get such nice-looking figures...

Thank you!

**Comment by Gesmira** [comment]
Hi, 
In DoHeatmap, you can set the parameter `draw.lines = FALSE`. This should remove the white lines you are seeing here.

**Comment by Jiayi-Zheng** [comment]
@Gesmira Thank you for your quick reply! I just tried DoHeatmap with `draw.lines = FALSE` but the white space between data columns are still there...
