### ISSUE TITLE
Read10x after cellranger aggr or cellranger count

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#805]
I see in the tutorial https://satijalab.org/seurat/pbmc3k_tutorial.html
it starts from here.
pbmc.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19/"), but filtered_gene_bc_matrices is adirectory of cellranger acount, whera the directory of  cellranger aggr maybe 
filtered_gene_bc_matrices_mex

**Comment by andrewwbutler** [comment]
Typically, we use `Read10X` to read in count matrices and perform normalization within Seurat. Please see #672 for additional discussion.
