### ISSUE TITLE
Regress out mitochondrial gene using fastMNN

### ISSUE THREAD

**Issue by galaxyeee** [satijalab/seurat#8055]
Dear, Seurat developers.

Hi,
I have a question about regressing out.
I integrated my sample data using fastMNN. But, I knew fastMNN use internal scaling.
So I want to know how to regress out mitochondrial gene by using fastMNN.
If there is solution, I'd appreciate it if you could let me know.

This is my code.
```
combined_mal_pre <- merge(malignant, y = precc, 
                          add.cell.ids = c("Malignant", "preCC"), 
                          project = "Malignant & preCC")

combined_mal_pre <- NormalizeData(combined_mal_pre, normalization.method = "LogNormalize", scale.factor = 10000)
combined_mal_pre <- FindVariableFeatures(combined_mal_pre)
combined_mal_pre <- RunFastMNN(object.list = SplitObject(combined_mal_pre, split.by = "orig.ident"))
combined_mal_pre <- RunUMAP(combined_mal_pre, reduction = "mnn", dims = 1:20)
combined_mal_pre <- FindNeighbors(combined_mal_pre, reduction = "mnn", dims = 1:20)
combined_mal_pre <- FindClusters(combined_mal_pre)
```

Thank you.
EUNHA

**Comment by longmanz** [comment]
Hi,
There is no way from our end to regress out the cell-cycle or other factors because RunFastMNN uses its own scaling. But, you may consider regress it out after the RunFastMNN, as mentioned here (https://github.com/satijalab/seurat/discussions/4187).
