### ISSUE TITLE
“avg_log2FC“ results was not same in seurat 4.4 and 5.0 

### ISSUE THREAD

**Issue by LeeKamlong** [satijalab/seurat#8056]
I'm using FindAllMarkerss() function to slect the cell clusting marker. The 'data' and 'count' was same in two version. But the “avg_log2FC“ results was different.
for example
In 4.4:
![image](https://github.com/satijalab/seurat/assets/58457503/214325d8-d588-41bd-bfbd-e74ea02e14f3)
but In 5.0
![image](https://github.com/satijalab/seurat/assets/58457503/387ccdaf-204f-4c8d-b046-18f59fef8a24)

**Comment by lucygarner** [comment]
I'm not a Seurat developer, but there was a bug in the calculation of avg_log2FC() in previous versions of Seurat. #7146 #6202 #7749

**Comment by samuel-marsh** [comment]
Hi All,

Also not member of dev team but the issue is due to the change in implementation of pseudocount between 4.4 and v5.  See info here:
https://satijalab.org/seurat/articles/announcements

Best,
Sam
