### ISSUE TITLE
VlnPlot shows  nGenen in a incorrect way

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#806]
![image](https://user-images.githubusercontent.com/25199946/46191687-fd44fe00-c32a-11e8-8eed-1d3c3e0f0679.png)

![image](https://user-images.githubusercontent.com/25199946/46191715-1d74bd00-c32b-11e8-969c-12d898866cf6.png)

it is difficult to understand the y.log = TRUE in these two pdf(upper y.log = FALSE, below  y.log = TRUE ), so I think the Instructions of Seurat should clearly describe when choose different features.plot , if not maybe puzzled

**Comment by 2236529177** [comment]
I ran the code in https://satijalab.org/seurat/pbmc3k_tutorial.html,and the mito percent bigger than 1, really unbelievable

**Comment by andrewwbutler** [comment]
Hi, 

When using `y.log = TRUE`, Seurat seems to be adding a pseudocount of 1. https://github.com/satijalab/seurat/blob/9fae278a495818a5c3358fbe34b957d950416e77/R/plotting_internal.R#L662-L664

This is why you're seeing values greater than 1 for percent mito. We will address this in the next release but for now, I would avoid using that flag for data that isn't varying over a large range (1K to 100K)

**Comment by 2236529177** [comment]
> Hi,
> 
> When using `y.log = TRUE`, Seurat seems to be adding a pseudocount of 1.
> 
> [seurat/R/plotting_internal.R](https://github.com/satijalab/seurat/blob/9fae278a495818a5c3358fbe34b957d950416e77/R/plotting_internal.R#L662-L664)
> 
> Lines 662 to 664 in [9fae278](/satijalab/seurat/commit/9fae278a495818a5c3358fbe34b957d950416e77)
> 
>  if (y.log) { 
>    noise <- rnorm(n = length(x = data[, feature])) / 200 
>    data[, feature] <- data[, feature] + 1 
> This is why you're seeing values greater than 1 for percent mito. We will address this in the next release but for now, I would avoid using that flag for data that isn't varying over a large range (1K to 100K)

you are the author, thanks for your reply, can we communicate with email, I send some email for the Satija lab, but no one reply
