### ISSUE TITLE
How to correctly set findTransferAnchors reference.reduction with integrated reference 

### ISSUE THREAD

**Issue by gmbjoca** [satijalab/seurat#8061]
Dear all/seurat-team, 

I am looking for guidance on how to set the reference.reduction parameter in an analysis similar to https://satijalab.org/seurat/articles/integration_mapping.html.   

In the example, the reference is integrated with cca, giving the "integrated.cca" reduction. However, in FindTransferAnchors you use     reference.reduction = "pca".   

I have two questions:    
q1: Could you instead use reference.reduction = "integrated.cca", or similar after running another integration method (eg "integrated.rpca", or even "integrated.rpca.full" if working from a sketch based integration approach)?   
q2: When using reference.reduction="pca", does that ignore dataset specific batch effects that were removed by the (cca)integration?    

Thanks for your help.

**Comment by tvegawaichman** [comment]
I have the same question... is it resolved?

**Comment by tvegawaichman** [comment]
Sorry, I'm still confused.
If I use the reference.reduction="pca", does that ignore the batch effects that were removed before with the cca.integration? Shouldn't I use reference.reduction="cca.integration"?
