### ISSUE TITLE
Error with `DimPlot` rasterization - empty plot

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#8063]
When using `DimPlot` on a Seurat object containing >100,000 cells, the output plot is empty - axis and legend present but no data points - when rasterizing points as by default. If I turn rasterization off, I see the plot as expected.

```r
# Plot looks fine
DimPlot(seurat_obj, raster = FALSE)
```

```r
#  Empty plot - axes and legend present as normal
DimPlot(seurat_obj)
```

```r
sessionInfo()
```

> R version 4.3.0 (2023-04-21)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 22.04.2 LTS
> 
> Matrix products: default
> BLAS:   /ceph/package/u22/R-base/4.3.0/lib/R/lib/libRblas.so 
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.10.0
> 
> locale:
>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
> 
> time zone: Europe/London
> tzcode source: system (glibc)
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] lubridate_1.9.2    forcats_1.0.0      stringr_1.5.0      dplyr_1.1.2       
>  [5] purrr_1.0.1        readr_2.1.4        tidyr_1.3.0        tibble_3.2.1      
>  [9] ggplot2_3.4.2      tidyverse_2.0.0    SeuratObject_4.1.3 Seurat_4.3.0.1    
> [13] scattermore_1.2   
> 
> loaded via a namespace (and not attached):
>   [1] RColorBrewer_1.1-3     rstudioapi_0.14        jsonlite_1.8.5        
>   [4] magrittr_2.0.3         spatstat.utils_3.0-3   farver_2.1.1          
>   [7] fs_1.6.2               vctrs_0.6.3            ROCR_1.0-11           
>  [10] memoise_2.0.1          spatstat.explore_3.2-1 htmltools_0.5.5       
>  [13] usethis_2.1.6          curl_5.0.1             sctransform_0.3.5     
>  [16] parallelly_1.36.0      KernSmooth_2.23-21     desc_1.4.2            
>  [19] htmlwidgets_1.6.2      ica_1.0-3              plyr_1.8.8            
>  [22] plotly_4.10.2          zoo_1.8-12             cachem_1.0.8          
>  [25] igraph_1.5.0           mime_0.12              lifecycle_1.0.3       
>  [28] pkgconfig_2.0.3        Matrix_1.5-4.1         R6_2.5.1              
>  [31] fastmap_1.1.1          fitdistrplus_1.1-11    future_1.32.0         
>  [34] shiny_1.7.4            digest_0.6.32          colorspace_2.1-0      
>  [37] patchwork_1.1.2        ps_1.7.5               rprojroot_2.0.3       
>  [40] tensor_1.5             irlba_2.3.5.1          pkgload_1.3.2         
>  [43] labeling_0.4.2         progressr_0.13.0       timechange_0.2.0      
>  [46] fansi_1.0.4            spatstat.sparse_3.0-2  httr_1.4.6            
>  [49] polyclip_1.10-4        abind_1.4-5            compiler_4.3.0        
>  [52] remotes_2.4.2          withr_2.5.0            pkgbuild_1.4.0        
>  [55] MASS_7.3-60            sessioninfo_1.2.2      tools_4.3.0           
>  [58] lmtest_0.9-40          httpuv_1.6.11          future.apply_1.11.0   
>  [61] goftest_1.2-3          glue_1.6.2             callr_3.7.3           
>  [64] nlme_3.1-162           promises_1.2.0.1       grid_4.3.0            
>  [67] Rtsne_0.16             cluster_2.1.4          reshape2_1.4.4        
>  [70] generics_0.1.3         gtable_0.3.3           spatstat.data_3.0-1   
>  [73] tzdb_0.4.0             hms_1.1.3              data.table_1.14.8     
>  [76] sp_2.1-1               utf8_1.2.3             spatstat.geom_3.2-1   
>  [79] RcppAnnoy_0.0.20       ggrepel_0.9.3          RANN_2.6.1            
>  [82] pillar_1.9.0           later_1.3.1            splines_4.3.0         
>  [85] lattice_0.21-8         survival_3.5-5         deldir_1.0-9          
>  [88] tidyselect_1.2.0       miniUI_0.1.1.1         pbapply_1.7-2         
>  [91] gridExtra_2.3          devtools_2.4.5         matrixStats_1.0.0     
>  [94] stringi_1.7.12         lazyeval_0.2.2         codetools_0.2-19      
>  [97] cli_3.6.1              uwot_0.1.15            xtable_1.8-4          
> [100] reticulate_1.34.0      munsell_0.5.0          processx_3.8.1        
> [103] Rcpp_1.0.10            globals_0.16.2         spatstat.random_3.1-5 
> [106] png_0.1-8              parallel_4.3.0         ellipsis_0.3.2        
> [109] prettyunits_1.1.1      profvis_0.3.8          urlchecker_1.0.1      
> [112] listenv_0.9.0          viridisLite_0.4.2      scales_1.2.1          
> [115] ggridges_0.5.4         leiden_0.4.3           crayon_1.5.2          
> [118] rlang_1.1.1            cowplot_1.1.1

**Comment by lucygarner** [comment]
Thank you @samuel-marsh. Unfortunately, I can't downgrade the scattermore package in my current setup, as everything is controlled by sys admin. So I will wait until they upgrade Seurat and hopefully that will fix the issue!

**Comment by samuel-marsh** [comment]
Hi,

Ok that’s too bad.  Does explicitly setting the pt.size within the function command solve the issue?

Best,
Sam

**Comment by lucygarner** [comment]
Great suggestion! This seems to work if I set pt.size > 0.2.
