### ISSUE TITLE
why not select genes in a section, less then some value is meaningful?

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#807]
mito precent is the less the better,so we should not set 0.05, nGenes maybe in a section, because too many means more than one cell, so about this parameter, do you have some suggestions

![image](https://user-images.githubusercontent.com/25199946/46192792-da1c4d80-c32e-11e8-92d7-18b122edf45e.png)

**Comment by andrewwbutler** [comment]
Please see #346 and #259
