### ISSUE TITLE
BPCells Vignette - Links Broken

### ISSUE THREAD

**Issue by felixm3** [satijalab/seurat#8070]
The two vignette links [here](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette):

<img width="836" alt="image" src="https://github.com/satijalab/seurat/assets/43228120/c47e4a18-7623-4f28-9d3c-211c4f26e391">

don't go anywhere.

**Comment by zskylarli** [comment]
Thank you for opening this issue, this has been fixed now!
