### ISSUE TITLE
broken link on announcements to intergration_mapping | 404

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#8071]
On 
`https://satijalab.org/seurat/articles/announcements` 

there is a broken link to 

`https://satijalab.org/seurat/articles/intergration_mapping.html`

I think should be:
`https://satijalab.org/seurat/articles/seurat5_integration_mapping`

**Comment by zskylarli** [comment]
Thank you for noticing and opening this issue, this has been fixed now!
