### ISSUE TITLE
AddModule score function error

### ISSUE THREAD

**Issue by krigia** [satijalab/seurat#8072]
Hello @troels @pmarks @mxposed @zeehio @smoe 

I am running the Addmodulescore function in a loop for GSEA genesets

__#run all GSEA C8 cell type signature gene sets (n=830) 
gsea_C8_list <- read.csv(file= "/Volumes/Pegasus/10X-Visium-Precision/results/RunUMAP/c8.all.v2023.2.Hs.symbols.gmt.csv", header = FALSE)
geneset8 <- as.list(as.data.frame(t(gsea_C8_list[,3:1770]))) 

score_graph <- function(x){  
se_F2_scRNAseqmodule <- AddModuleScore(
object =  se_F2_normalized,     
features = list(c(t(gsea_C8_list[x, 3:1770]))),    
rownames(x= se_F2_normalized),   
ctrl = 100,     
name = c(gsea_C8_list[x, 1]))      

head(x = se_F2_scRNAseqmodule[])_

se_F2_scRNAseqmodule.score <- se_F2_scRNAseqmodule@meta.data[[paste0(gsea_hallmark_list[x, 1], "1")]] se_F2_scRNAseqmodule.score

}_

_test3 <- lapply(seq_along(geneset8), score_graph)
test3 <- as.data.frame(test3) print(test3)
write.csv(test3, "C8_se_F2.csv")_

And I am getting the following error

**Error in AddModuleScore(object = se_F2_normalized, features = list(c(t(gsea_C8_list[x,  :   The following feature lists do not have enough features present in the object:  exiting... 
In addition: Warning message: In AddModuleScore(object = se_F2_normalized, features = list(c(t(gsea_C8_list[x,  :   Could not find enough features in the object from the following feature lists:  Attempting to match case...**

I would greatly appreciate your feedback.

Thank you

**Comment by igrabski** [comment]
This error means that there are insufficient features in `gsea_C8_list[x, 3:1770]` that are present in your object `se_F2_normalized`. I would recommend double-checking, for example, that the genes in `gsea_C8_list[x, 3:1770]` are of the same format (e.g. ENSEMBL ID vs. symbol, etc.) as in your object.
