### ISSUE TITLE
HARMONY + SCT + SUBSET

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [satijalab/seurat#8073]
Hello, 

Im running the combination of SCT + Harmony as mentioned in : [https://github.com/immunogenomics/harmony/issues/41](url)

```
data.list<-readRDS("Seurat_SCT_List_ByPatient.rds")

integ_features <- SelectIntegrationFeatures(object.list = data.list, nfeatures = 2000) 

merged_seurat <- merge(x = data.list[[1]],y = data.list[2:length(data.list)],merge.data = TRUE)
DefaultAssay(merged_seurat) <- "SCT"

VariableFeatures(merged_seurat) <- inter_features

set.seed(12345)
merged_seurat <- RunPCA(merged_seurat, assay = "SCT", npcs = 50,features=integ_features)
dim.final <- Calculo.Dimensiones.PCA(merged_seurat)

integration.var<-"Patient.ID"

harmonized_seurat <- RunHarmony(merged_seurat,
group.by.vars = integration.var, 
reduction = "pca", 
assay.use = "SCT", 
reduction.save = "harmony",
plot_convergence = TRUE,
dims.use = 1:dim.final,
epsilon.cluster=-Inf,
epsilon.harmony=-Inf)

harmonized_seurat <- RunUMAP(harmonized_seurat, reduction = "harmony", assay = "SCT", dims = 1:dim.final)
harmonized_seurat <- FindNeighbors(harmonized_seurat,reduction = "harmony",dims = 1:dim.final,graph.name = "Harmony_SCT")
resolutions <- c(0.1,0.3,0.5)
harmonized_seurat <- FindClusters(harmonized_seurat, resolution = resolutions,graph.name = "Harmony_SCT")
```

This is the code of merging both SCT and Harmony.  However, I need to subset two clusters of interest from the total object and Im doubting on how to do it. 

The object has both the SCT assay and RNA assay, and the embedding corrected for both assays. My questions will be: 

1. Which assay should I use to subset? --> If the SCT assay is used I only have 2000 genes as it were chosen in the SelectIntegrationFeatures.

**Comment by shahrozeabbas** [comment]
If you are going to subset the object, my advice is to subset based on the cluster or identities of interest. Then perform the analysis from scratch as if it were a completely brand new dataset. This means you'll be recalculating the `SCT` assay along with the set of new variable genes. 

Set the default assay to `RNA`, use `DietSeurat` to clean the object and keep only the `RNA` assay, subset based on identity or group of interest, reanalyze using same workflow you used for the entire dataset as a blank slate.

**Comment by anemartinezlarrinaga2898** [comment]
Okey! Thank you is what I was doing : )
