### ISSUE TITLE
SCTIntegration in Seurat V5

### ISSUE THREAD

**Issue by pdimitron** [satijalab/seurat#8076]
Hi Satija Lab,

I'm working on updating some of my analyses to be compatible with SeuratV5 and I was curious about SCT Integration in SeuratV5. In my previous script, I had incorporated [this vignette ](https://satijalab.org/seurat/reference/prepsctintegration), prior to using Harmony but I see that this is not part of the new [integration vignette](https://satijalab.org/seurat/articles/seurat5_integration) for SeuratV5. I do incorporate SCT regularization as part of my integration as described at the end of SeuratV5 Integration vignette, but my clustering is somewhat different. I was wondering if these two integrations are functionally equivalent or similar and what considerations I might need to make going forward. Thanks in advance for your insight!

**Comment by longmanz** [comment]
Hi,
In the [new integration vignette](https://satijalab.org/seurat/articles/seurat5_integration), you can still find the SCT + RPCAIntegration integration workflow at the bottom (last section). 
But in this [previous vignette](https://satijalab.org/seurat/reference/prepsctintegration), it uses the default CCA-based integration method. It really depends on your choice. To know more on the difference between RPCA and CCA, you may refer to this vignette (https://satijalab.org/seurat/articles/integration_rpca.html).
