### ISSUE TITLE
Modification of the cell identities by Seurat functions

### ISSUE THREAD

**Issue by timothevanmeter** [satijalab/seurat#8077]
Hello,

I am trying to compare two datasets composed of the same cells: one that I have been analysing after integrating it (it is composed of different samples) and the original one, which is composed of all the cells simply merged in one dataset.

However, the cells identities are not identical anymore.

It seems the identities of the cells has been changed in the process: the values stored in `<my_dataset>@assays$RNA@data@Dimnames[[2]]`, precisely I think underscores with an index have been added in their names. I say this because the following command:

`WhichCells(<merged_data>, cells = WhichCells(<integrated_and_analysed_data>))`

only returns a couple of cells (< 100), but not near as much as the total dataset ~119566 cells, which in all logic it should return.

I could not understand when exactly did this modification of the cell's identities happened in the analysis. From this issue (https://github.com/satijalab/seurat/issues/380) I understood that the cell's identities are overwritten by some functions as Seurat::FindClusters() and that the only way to keep the cell identities for further reference is to stored them in the meta.data slot of the SeuratObject.

Can anyone confirm this? Is there a list of the functions in Seurat that overwrite the cell's identities?

Also, why is this the default functioning if it means that after any analysis any comparison or return to the data before analysis is impossible?

Thanks in advance for any advise or information anyone can provide on this issue.

**Comment by longmanz** [comment]
Hi,
Are you saying that the Idents of the two objects are different? You can always reset your Idents using [Idents()](https://satijalab.org/seurat/articles/essential_commands.html) function. 
Or are you saying the cell IDs are changed after integration? Integration process will automatically add "_" to the cell IDs to differentiate cells from different datasets. If you do not want this, you may use [RenameCells()](https://search.r-project.org/CRAN/refmans/SeuratObject/html/RenameCells.html) to rename all your cells in the integrated dataset.
