### ISSUE TITLE
Appropriate way to remove batch effects on multiomic data using Harmony

### ISSUE THREAD

**Issue by nicolaromano** [satijalab/seurat#8079]
I have 4 multiomic samples (scRNAseq + scATAC, done on the same cell), showing very clear batch effect and trying to use Harmony to remove it.

Essentially I create a Seurat object using

```
counts <- Read10X_h5(GE_h5_path)

seurat_obj <- CreateSeuratObject(
    counts = counts$`Gene Expression`,
    assay = "RNA"
)

seurat_obj[["ATAC"]] <- CreateChromatinAssay(
    counts = counts$Peaks,
    sep = c(":", "-"),
    fragments = fragments_path,
    annotation = annotation
)
```

After various QC filtering I use `Signac::CallPeaks`,  and create a chromatine assay for the peaks, essentially following the multiomic tutorial on the [Signac website](https://stuartlab.org/signac/articles/pbmc_multiomic).

I then run dimensionality reduction and normalization using

```
DefaultAssay(seurat_obj) <- "RNA"
seurat_obj <- seurat_obj %>%
    SCTransform() %>%
    RunPCA(npcs = 50)

DefaultAssay(seurat_obj) <- "peaks"
seurat_obj <- seurat_obj %>%
    RunTFIDF() %>%
    FindTopFeatures(min.cutoff = 5) %>%
    RunSVD()

# Build a joint neighbor graph using both assays
seurat_obj <- FindMultiModalNeighbors(
    object = seurat_obj,
    reduction.list = list("pca", "lsi"),
    dims.list = list(1:50, 2:40),
    modality.weight.name = "RNA.weight",
    verbose = TRUE
)

# Build a joint UMAP visualization
seurat_obj <- RunUMAP(
    object = seurat_obj,
    nn.name = "weighted.nn",
    assay = "RNA",
    verbose = TRUE
)
```

And finally, run Harmony, correcting for the effect of Library (note: 2 libraries are control and 2 libraries are mutant)

```
seurat_obj_harm <- RunHarmony(
    object = seurat_obj,
    group.by.vars = "Library", 
    project.dim = FALSE,
    max_iter = 50
)

seurat_obj_harm <- RunUMAP(seurat_obj_harm,
    dims = 2:30,
    reduction = "harmony"
)
```

Plotting UMAP before and after, e.g.

```
p1 <- DimPlot(seurat_obj, group.by = "Library", pt.size = 0.1)
p2 <- DimPlot(seurat_obj_harm, group.by = "Library", pt.size = 0.1)
grid.arrange(p1, p2, ncol = 2)
```

I can see that the batch effect is gone. 
So, my question is:

1 - Is my workflow correct?
2 - Do I need to run Harmony on the ATAC data as well?
3 - How do I see if there is still a batch effect in the ATAC data?

**Comment by shahrozeabbas** [comment]
Batch effect is most likely going to be present in both RNA and ATAC if present at all. So you'll need to run Harmony on PCA and LSI reductions independently. Then build the joint, WNN representation using the batch corrected Harmony reductions. 

So first run PCA on the RNA, then pass that into Harmony. Then run SVD on the ATAC and specify the 'lsi' reduction in `RunHarmony`. Finally, when you call `FindMultiModalNeighbors`, your reduction list will be `harmony_rna` and `harmony_lsi` provided that you have named each iteration of harmony respectively. 

As far as checking for batch effect, there are different ways of going about this using published tools or naively plotting a UMAP and coloring by your "batch" label. If cells are grouped by batch, then you still could have batch effect driving your clustering.

**Comment by shahrozeabbas** [comment]
That's a good question. I think if you were to examine for batch effect in each modality individually and confirm that Harmony does indeed correct for it adequately, then I assume when creating the joint representation you should not see any batch effect. 

You may be able to repurpose the workflow that I have created [here](https://github.com/shahrozeabbas/Harmony-RNA-Workflow) for multiome analysis. Feel free to take a look and let me know if you have any questions.

**Comment by rsatija** [comment]
That is correct - you can use Harmony (or any integration technique) to independently integrate RNA and ATAC batch effects, and then use the integrated_rna and integrated_atac dimensional reductions for WNN construction.
