### ISSUE TITLE
FindVariableGenes uses suggestions

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#808]
First, why the name did not keep the same style about 

x.low.cutoff Bottom cutoff on x-axis for identifying variable genes
x.high.cutoff Top cutoff on x-axis for identifying variable genes
y.cutoff Bottom cutoff on y-axis for identifying variable genes
y.high.cutoff Top cutoff on y-axis for identifying variable genes

and also the descrition in the Instruction is really too little.

Thanks a lot

**Comment by andrewwbutler** [comment]
Hi,

It's a good point and we are working to standardize parameter names and improve the documentation in the next release. For this function in particular, we will replace the above with two parameters: `mean.cutoff` and `dispersion.cutoff`. These will each take a vector of two values that correspond to the high and low cutoffs.
