### ISSUE TITLE
Trying to combine datasets & receiving error

### ISSUE THREAD

**Issue by aadharmg** [satijalab/seurat#8081]
Hi all,

I am working on GSE139107 & trying to merge the control & 2-day post IRI datasets. So far I have loaded both datasets in & made individual seurat objects labelled "Sham & IRI". I am trying to integrate the objects before any further downstream analysis, but keep receiving the following error: 

Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "list"

My code is as below, the error is at the last function: 

``` {r}
Sham <- NormalizeData(Sham)
IRI <- NormalizeData(IRI)

Sham <- FindVariableFeatures(Sham)
IRI <- FindVariableFeatures(IRI)

gse_list <- list(Sham, IRI)

gse_list <- IntegrateLayers(object = gse_list, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)
```

Anyone know where the issue lies?

**Comment by shahrozeabbas** [comment]
You need to pass a `Seurat` object to `IntegrateLayers` not a list. It looks like you are using Seuratv5? You can merge the Sham and IRI objects into one and perform the normalization and variable gene detection independently on both datasets. This merged object needs to be passed to `IntegrateLayers`.
