### ISSUE TITLE
error: RunSVD

### ISSUE THREAD

**Issue by zhoudezhoudezhou** [satijalab/seurat#8092]
I follow the tutorial: WNN analysis of 10x Multiome, RNA + ATAC

How can I deal with the problems below?
pbmc <- RunSVD(pbmc)
>>>
Running SVD
Warning in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : 
  程序包'as_cholmod_sparse'不提供'Matrix'这样的函数

**Comment by shahrozeabbas** [comment]
You need to allocate more memory for the analysis. Currently Seuratv5 + BPCells does not carry over to ATAC data. Hopefully this will change soon.

**Comment by Gesmira** [comment]
Hi,
Solutions for this have been provided here: https://github.com/satijalab/seurat/issues/8100
Restarting R and reinstalling Matrix and irlba should fix the issue.
