### ISSUE TITLE
Different "Name for the expression programs" in AddModuleScore

### ISSUE THREAD

**Issue by Frank1213817** [satijalab/seurat#8097]
Hi Seurat dev team! I have a question regarding the AddModuleScore function.

The output of AddModuleScore generates many "names" in the metadata, which is explained to be "Name for the expression programs" by the documentation.

I am wondering how to understand these different "expression programs", are they groups of features that have similar expression patterns? What are the differences among these "expression programs"?

Should I just use the first name ("name1") for visualization and further analysis? Or is there any standard which score to choose?

Many many thanks for your kind attention.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Are you inputting multiple lists of genes for scoring?  If not there should only be one column added to meta data.  Can you post full code you are running?

Thanks,
Sam

**Comment by Frank1213817** [comment]
Hi Sam! Thank you for your reply! I think I have only input one gene list, my code is just like:

gene_list <- c("gene1", "gene2", "gene3", ...)

seurat_object <- AddModuleScore(seurat_object, features = gene_list, name = "marker", assay = "RNA")

And it gives me "marker1", "marker2", "marker3", ... in my metadata.

**Comment by samuel-marsh** [comment]
Hi,

So as described in function documentation the genesets need to be of class list, otherwise it is just computing a score for each gene in the vector.  So what you need to run is:

```
gene_list <- list(c("gene1", "gene2", "gene3", ...))

seurat_object <- AddModuleScore(seurat_object, features = gene_list, name = "marker", assay = "RNA")

```

Best,
Sam

**Comment by Frank1213817** [comment]
Hi Sam, I guess you are right, that's a coding issue...
Really appreciate your help!

Frank
