### ISSUE TITLE
RegressOut orig.ident

### ISSUE THREAD

**Issue by mehc555** [satijalab/seurat#81]
Hi,

I'm trying to regress out batches with 10X data, however I'm not getting the results I would expect on my own data. As a test case I went back and used two 10X datasets (replicates), subsampled them to 200 cells each and then ran PCA/TSNE with and without regression of the orig.ident variable. Without regression, the data clusters as expected but with regression there's a clear batch effect. Maybe I am missing something obvious or have coding errors, or is this expected?

Thank you

[noregress.pdf](https://github.com/satijalab/seurat/files/1041135/noregress.pdf)
[regress_batch.pdf](https://github.com/satijalab/seurat/files/1041136/regress_batch.pdf)
[code.txt](https://github.com/satijalab/seurat/files/1041137/code.txt)

**Comment by satijalab** [comment]
That is surprising. Can you try using a linear model instead of a negbinom for the regression? It may be that 200 cells is not enough cells to fit negative binomial distributions for many genes, especially if the genes are not expressed in a high proportion of cells.

**Comment by mehc555** [comment]
It does work with the linear regression. Also trying with all cells (~3.4K), it seems to only work with linear regression. I get many of these warnings with negbinom:

40: In sqrt(1/i) : NaNs produced
41: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  ... :
  iteration limit reached

Thanks

[code.txt](https://github.com/satijalab/seurat/files/1047489/code.txt)
[regress_linear_batch.pdf](https://github.com/satijalab/seurat/files/1047490/regress_linear_batch.pdf)
[regress_all_cells_batch.pdf](https://github.com/satijalab/seurat/files/1047491/regress_all_cells_batch.pdf)
[regress_all_cells_linear_batch.pdf](https://github.com/satijalab/seurat/files/1047492/regress_all_cells_linear_batch.pdf)
