### ISSUE TITLE
irlba Bug When Attempting to RunUMAP()

### ISSUE THREAD

**Issue by jwalewski** [satijalab/seurat#8100]
Hello,

I am attempting to use the RunUMAP() function on some test data I have and I am getting the following error:
```
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
```
 I am currently using Seurat v.4.4.0 and SeuratObject v4.1.4. Even after explicitly importing irlba I get the same error. RunTSNE(), however, works exactly as expected. Do you guys have any idea about what's going on here, or is more information needed?

**Comment by LiorLuo** [comment]
I solved this by running following scripts
install.packages("Matrix", type = "source")
install.packages("irlba", type = "source")

**Comment by QuietgraceH** [comment]
I met the same irror when  run `pbmc3 <- RunSVD(pbmc3)`.
Error:
Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol): 程序包'as_cholmod_sparse'不提供'Matrix'这样的函数
Traceback:

1. RunSVD(pbmc3)
2. RunSVD.Seurat(pbmc3)
3. RunSVD(object = assay.data, assay = assay, features = features, 
 .     n = n, reduction.key = reduction.key, scale.max = scale.max, 
 .     verbose = verbose, ...)
4. RunSVD.Assay(object = assay.data, assay = assay, features = features, 
 .     n = n, reduction.key = reduction.key, scale.max = scale.max, 
 .     verbose = verbose, ...)
5. RunSVD(object = data.use, assay = assay, features = features, 
 .     n = n, reduction.key = reduction.key, scale.max = scale.max, 
 .     verbose = verbose, ...)
6. RunSVD.default(object = data.use, assay = assay, features = features, 
 .     n = n, reduction.key = reduction.key, scale.max = scale.max, 
 .     verbose = verbose, ...)
7. irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol)

**Comment by jwalewski** [comment]
> install.packages("Matrix", type = "source")
> install.packages("irlba", type = "source")

Luckily, this seems to have worked for me. Thank you!

**Comment by Rym12345** [comment]
> I solved this by running following scripts install.packages("Matrix", type = "source") install.packages("irlba", type = "source")

**Comment by Rym12345** [comment]
> I solved this by running following scripts install.packages("Matrix", type = "source") install.packages("irlba", type = "source")

this also seems to have worked for me. thank you
when I use the Seurat V5, this eror don’t happen. However ,it happens when I use the Seurat V4.
I don‘t  understand the reason

**Comment by Evenlyeven** [comment]
> > I solved this by running following scripts install.packages("Matrix", type = "source") install.packages("irlba", type = "source")
> 
> this also seems to have worked for me. thank you when I use the Seurat V5, this eror don’t happen. However ,it happens when I use the Seurat V4. I don‘t understand the reason

I am using Seurat V5 and saw the error ...

**Comment by yukixuen** [comment]
> I solved this by running following scripts
> install.packages("Matrix", type = "source")
> install.packages("irlba", type = "source")

Worked too. Thank you!

**Comment by cetinsz** [comment]
> I solved this by running following scripts install.packages("Matrix", type = "source") install.packages("irlba", type = "source")

This doesn´t work for me in Seurar V4 unfortunately.

**Comment by zhuldyzhanzak** [comment]
This does not work for me as well.  Can anyone please help? 

My Seurat is 4.3.0.1
SeuratObject is 4.0.3
Matrix is 1.6-4

**Comment by fisheryu2022** [comment]
> Hello,
> 
> I am attempting to use the RunUMAP() function on some test data I have and I am getting the following error:
> 
> ```
> Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
>   function 'as_cholmod_sparse' not provided by package 'Matrix'
> ```
> 
> I am currently using Seurat v.4.4.0 and SeuratObject v4.1.4. Even after explicitly importing irlba I get the same error. RunTSNE(), however, works exactly as expected. Do you guys have any idea about what's going on here, or is more information nee

> This does not work for me as well. Can anyone please help?
> 
> My Seurat is 4.3.0.1 SeuratObject is 4.0.3 Matrix is 1.6-4

It doesn't work for me either. Are you using M1 too?

**Comment by zhuldyzhanzak** [comment]
> > Hello,
> > I am attempting to use the RunUMAP() function on some test data I have and I am getting the following error:
> > ```
> > Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
> >   function 'as_cholmod_sparse' not provided by package 'Matrix'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am currently using Seurat v.4.4.0 and SeuratObject v4.1.4. Even after explicitly importing irlba I get the same error. RunTSNE(), however, works exactly as expected. Do you guys have any idea about what's going on here, or is more information nee
> 
> > This does not work for me as well. Can anyone please help?
> > My Seurat is 4.3.0.1 SeuratObject is 4.0.3 Matrix is 1.6-4
> 
> It doesn't work for me either. Are you using M1 too?

It started to work recently. Try to install a package called RSpectra. It helped me

**Comment by Cinzialo** [comment]
> I solved this by running following scripts install.packages("Matrix", type = "source") install.packages("irlba", type = "source")

It works for me too. Thanks

**Comment by fisheryu2022** [comment]
Thank you to both Cinzialo and zhuldyzhanzak! I have now solved the problem. Here is my solution: 1.	Go to https://cran.r-project.org/bin/macosx/tools/, download an installer package [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg)
2.	In R: install.packages("Matrix", type = "source")
3.	In R: install.packages("irlba", type = "source")

**Comment by menage95** [comment]
I have an M1 and am running into the error as well, but the below solution does not work:

2. In R: install.packages("Matrix", type = "source")
3. In R: install.packages("irlba", type = "source")

Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

**Comment by fisheryu2022** [comment]
> I have an M1 and am running into the error as well, but the below solution does not work:
> 
> 2. In R: install.packages("Matrix", type = "source")
> 3. In R: install.packages("irlba", type = "source")
> 
> Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : function 'as_cholmod_sparse' not provided by package 'Matrix'

Here, there, before installing Matrix and irlba, you could do this first : Go to https://cran.r-project.org/bin/macosx/tools/, download an installer package [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg)

**Comment by menage95** [comment]
> > I have an M1 and am running into the error as well, but the below solution does not work:
> > 
> > 2. In R: install.packages("Matrix", type = "source")
> > 3. In R: install.packages("irlba", type = "source")
> > 
> > Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : function 'as_cholmod_sparse' not provided by package 'Matrix'
> 
> Here, there, before installing Matrix and irlba, you could do this first : Go to https://cran.r-project.org/bin/macosx/tools/, download an installer package [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg)

that worked thanks!!!

**Comment by HappinessEricst** [comment]
> RSpectra

Thanks this worked for me without needing to downgrade my matrix from 1.5.4.1

**Comment by jpcartailler** [comment]
Having the same issue trying to run `RunSVD`

```
Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
```
The system is Win10:
```
Seurat         4.3.0
SeuratObject   5.0.1
Matrix         1.6-5
irlba          2.3.5.1
```
I tried this but it did not work (like @cetinsz reported)
```
install.packages("Matrix", type = "source")
install.packages("irlba", type = "source")
```
and I tried installing `RSpectra` but the issue persists.

**Comment by fisheryu2022** [comment]
> Here, there, before installing Matrix and irlba, you could do this first : Go to https://cran.r-project.org/bin/macosx/tools/, download an installer package [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg)

**Comment by Elham-adabi** [comment]
I had the same issue and could solve it with updating to R4.3.2 and Running:
install.packages("Matrix", type = "source")
install.packages("irlba", type = "source")

**Comment by apal6** [comment]
Hi, 

I am having the same issue. Any advice? 

Code and error: 
`install.packages("Matrix",type="source")
install.packages("irlba",type="source")
cds<-preprocess_cds(cds,num_dim=50)`

error: Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

**Comment by HappinessEricst** [comment]
> Hi,
> 
> I am having the same issue. Any advice?
> 
> Code and error: `install.packages("Matrix",type="source") install.packages("irlba",type="source") cds<-preprocess_cds(cds,num_dim=50)`
> 
> error: Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE, : function 'as_cholmod_sparse' not provided by package 'Matrix'



I had to install the package "RSpectra" this solved mine

**Comment by alicekao1118** [comment]
Solved the problem by installing `RSpectra`

Below are some of my package and env info:
R 4.1.0
Seurat 4.4.0
I'm using server on Linux

**Comment by shiranss** [comment]
> > Here, there, before installing Matrix and irlba, you could do this first : Go to https://cran.r-project.org/bin/macosx/tools/, download an installer package [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg)

I tried this followed by 
install.packages("Matrix", type = "source")
install.packages("irlba", type = "source")

but I still have the same error. 

I also installed RSpectra and loaded it which still gives the same error. Could anyone help with this?

R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.4.1
Seurat_5.0.3               
SeuratObject_5.0.1  
Matrix_1.6-5     
irlba_2.3.5.1

**Comment by ScienceComputing** [comment]
> > > Here, there, before installing Matrix and irlba, you could do this first : Go to https://cran.r-project.org/bin/macosx/tools/, download an installer package [gfortran-12.2-universal.pkg](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg)
> 
> I tried this followed by install.packages("Matrix", type = "source") install.packages("irlba", type = "source")
> 
> but I still have the same error.
> 
> I also installed RSpectra and loaded it which still gives the same error. Could anyone help with this?
> 
> R version 4.3.3 (2024-02-29) Platform: aarch64-apple-darwin20 (64-bit) Running under: macOS Sonoma 14.4.1 Seurat_5.0.3 SeuratObject_5.0.1 Matrix_1.6-5 irlba_2.3.5.1

Maybe you can try R 4.4.0 for Mac, and re-install Matrix. I do not see irlba bug anymore. Hope it helps.

**Comment by igrabski** [comment]
Hi all, these issues should be resolved using the most up-to-date versions of `Seurat`, `SeuratObject`, and `Matrix`, and by installing `Matrix` and `irlba` from source as suggested as above. If problems persist, please feel free to open a new issue.

**Comment by sugarballer** [comment]
Matrix 1.6-1 solves this problem.

**Comment by Chrisdoan9** [comment]
R 4.4 solved the error.
