### ISSUE TITLE
FindMarkers MAST output containing unexpected number of genes

### ISSUE THREAD

**Issue by anneforsyth** [satijalab/seurat#8102]
We are currently working with Seurat v5 and encountering a notable discrepancy in the output size between DESeq2 and MAST when performing differential expression (DE) analysis. Our workflow involves:
1. Using DESeq2 with pseudobulk raw counts (DESeqDataSetFromMatrix() --> DESeq() workflow, not using FindMarkers for this) 
2. Employing MAST via FindMarkers with normalized counts from SCTransform v2 (using default min_cells = 5)
For both methods, we're applying the same pre-filtering criteria (min.pct = 0.01 for either comparison group) and starting with a nearly identical gene count (18,085 for DESeq2, 18,058 for MAST due to min_cells filtering in SCTransform). However, we've observed that the total output from MAST (regardless of significance) is approximately half the size of that from DESeq2 (~8,000 vs ~16,000 total genes). We are including sex, age, nFeature_Spatial and gDNA percent as covariates in each analysis, with sample_id as an additional covariate for MAST. 
This raises a concern: several genes identified as significant in the DESeq2 output (using logFC threshold of 0.25 and adjusted p-value threshold of 0.05) are completely absent in the MAST output. Could you provide insights or suggestions on why there's such a significant loss of genes in the MAST results? Any guidance on troubleshooting this issue would be greatly appreciated. 

Code used to manually filter genes for DESeq2:

```
counts <- GetAssayData(s, assay = "Spatial", layer = "counts")
ident_1 <- "iAD" 
ident_2 <- "nAD"
    
spots_1 <- s@meta.data$sample_barcode[s@meta.data$condition == ident_1]
spots_2 <- s@meta.data$sample_barcode[s@meta.data$condition == ident_2]
    
counts_1 <- counts[,colnames(counts) %in% spots_1]
counts_2 <- counts[,colnames(counts) %in% spots_2]
    
percent_1 <- rowMeans(counts_1 > 0)
percent_2 <- rowMeans(counts_2 > 0)
    
keep_1 <- names(percent_1)[percent_1 >= 0.01]
keep_2 <- names(percent_2)[percent_2 >= 0.01]
    
genes_keep <- c(keep_1, keep_2) %>% unique()
counts <- counts[row.names(counts) %in% genes_keep,]
    
pseudobulk <- t(rowsum(t(counts), group = colnames(counts)))
```
Code used to run FindMarkers with MAST:

```
# This step needed for PrepSCTFindMarkers
for (name in names(s@assays$SCT@SCTModel.list)) {
  s@assays$SCT@SCTModel.list[[name]]@umi.assay <- 'Spatial'
}

# Recorrect counts after subsetting 
s <- PrepSCTFindMarkers(object = s) 

degs <- FindMarkers(object = s,
                    ident.1 = "iAD",
                    ident.2 = "nAD",
                    recorrect_umi = FALSE,
                    latent.vars = c("sex", "age_centered", "gw_features_centered", "gDNA_centered", "sample_id"),
                    test.use = "MAST",
                    logfc.threshold = -Inf, 
                    min.pct = 0.01,
                    assay = "SCT")
```

**Comment by igrabski** [comment]
Hi Anne, I'm not able to reproduce this issue on my end -- I tried `FindMarkers` with the "MAST" option on some example datasets, and I'm able to get the same number of outputted genes as the input object. Can you try setting `min.pct = 0` to see what happens? In addition, can you confirm that the final object `s` being passed into `FindMarkers` has the expected number of genes? If neither of those helps, are you able to provide a reproducible example that I could take a look at?
