### ISSUE TITLE
Unable to perform makeShinyApp in Seurat V5

### ISSUE THREAD

**Issue by NSchippel** [satijalab/seurat#8103]
Today I updated Seurat to V5, but now am finding it difficult to navigate different functions. I think this is likely due to the addition of "layers" into the RNA assay. I have tried to read some of the layers introductions and cheat sheets, but I am still finding it difficulty. 

My main issue is that I am unable to perform makeShinyApp after the new update. Here is the code I was using prior to the update that always worked perfectly

```
obj = readRDS("obj.rds")

scConf = createConfig(obj)
makeShinyApp(obj, scConf, gene.mapping = TRUE, shiny.title = "obj_visualization") 

```
The makeShinyApp function still works when I use .rds files that were generated prior to the update (and so do not have the "layers" within the RNA assay), but I am unable to find any fix to make it so I can use this function with the new .rds files I have made (which I will need to do as I am going back to run SCTransform on all these objects). 

Please let me know if I can provide any additional information! 

Thank you so much

**Comment by Gesmira** [comment]
Hi, 
Since this is not a Seurat function, we recommend opening an issue in the [ShinyCell github repo](https://github.com/SGDDNB/ShinyCell). They should be able to update their functions to work with the new SeuratObject structure.
