### ISSUE TITLE
Bug in FindTransferAnchors - Seurat

### ISSUE THREAD

**Issue by acaulier** [satijalab/seurat#8106]
I am currently trying to import clusters annotations from a scRNA-seq dataset into another scATAC-seq assay.
When i run the FindTransferAnchors function, as following: 
transfer.anchors <- FindTransferAnchors(reference = RNA_obj, query = ATAC_obj, features = VariableFeatures(object = RNA_obj), reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")
I get the error : **"Error in validObject(.Object): invalid class "Graph" object: superclass "mMatrix" not defined in the environment of the object's class"**

I have RNA_obj as "RNA" assay of a seurat object, and ATAC_obj as "ACTIVITY" assay of a second seurat object.

The activity assay has been built following the seurat vignette:
# quantify gene activity
gene.activities <- GeneActivity(pbmc.atac, features = VariableFeatures(pbmc.rna))
# add gene activities as a new assay
pbmc.atac[["ACTIVITY"]] <- CreateAssayObject(counts = gene.activities)
# normalize gene activities
DefaultAssay(pbmc.atac) <- "ACTIVITY"
pbmc.atac <- NormalizeData(pbmc.atac)
pbmc.atac <- ScaleData(pbmc.atac, features = rownames(pbmc.atac))

# Matrix package issue?
I know people reported some problems with the Matrix package and recommended to downgrade it to v1.3-2, but it's incompatible with the use of Signac here ("Error: package or namespace load failed for 'Signac' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace 'Matrix' 1.3-2 is already loaded, but >= 1.6.3 is required")

Any recommendation to overcome this issue?

**Comment by igrabski** [comment]
Hi, this should now work with the current versions of `Seurat`, `SeuratObject`, and `Matrix`. Please feel free to open a new issue if problems persist!
