### ISSUE TITLE
FindTransferAnchors: Error in dimnames(x) <- dn: length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by acaulier** [satijalab/seurat#8107]
Hello,
I am trying to annotate my ATACseq data (GRCh37_filtered), with the cell type annotations (seurat clusters) from the RNAseq dimension (JAN_028_rna_subset) by running ```FindTransferAnchors``` function.

```
transfer.anchors <- FindTransferAnchors(reference = JAN_028_rna_subset, query = GRCh37_filtered, features = VariableFeatures(object = JAN_028_rna_subset),
    reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")
```
gives me the following error in the merging step of CCA reduction step: 
```
Error in dimnames(x) <- dn: length of 'dimnames' [1] not equal to array extent
Traceback:
1. FindTransferAnchors(reference = JAN_028_rna_subset, query = GRCh37_filtered,
 .     features = VariableFeatures(object = JAN_028_rna_subset),
 .     reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")
2. RunCCA(object1 = reference, object2 = query, features = features,
 .     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,
 .     verbose = verbose)
3. RunCCA.Seurat(object1 = reference, object2 = query, features = features,
 .     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,
 .     verbose = verbose)
4. `rownames<-`(x = `*tmp*`, value = Cells(x = combined.object))
```

Looking at the dimensions of those 2 Seurat objects:
```
dim(JAN_028_rna_subset)
36601          164431
```
```
dim(GRCh37_filtered)
1307            164431
```

Where does it come from?
Thanks for help!

**Comment by Evenlyeven** [comment]
I have the same error while using runCCA...

**Comment by liangyuli12138** [comment]
I have met the same problem, Is there any ways to solve?

**Comment by Yiqa** [comment]
I have this kind of warning message: 

```
Warning: 190 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 1810 features.

Running CCA
Merging objects
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
Calls: FindTransferAnchors -> RunCCA -> RunCCA.Seurat -> rownames<-

```

I also met the same problem, can anyone help with this?

**Comment by mihuzx** [comment]
> I have this kind of warning message:
> 
> ```
> Warning: 190 features of the features specified were not present in both the reference query assays. 
> Continuing with remaining 1810 features.
> 
> Running CCA
> Merging objects
> Error in dimnames(x) <- dn : 
>   length of 'dimnames' [1] not equal to array extent
> Calls: FindTransferAnchors -> RunCCA -> RunCCA.Seurat -> rownames<-
> ```
> 
> I also met the same problem, can anyone help with this?

I also met the same error. Anyone have an idea?

**Comment by fancody** [comment]
I also ran into such an issue during the process of predicting scatac via scrna using snapatac, after which I successfully ran FindTransferAnchors on an older R version: 4.0.5 and seurat version: 4.1.1, so I guess it might be because of an issue with some versions

**Comment by fancody** [comment]
I also ran into such an issue during the process of predicting scatac via scrna using snapatac, after which I successfully ran FindTransferAnchors on an older R version: 4.0.5 and seurat version: 4.1.1, so I guess it might be because of an issue with some versions

**Comment by craniolab** [comment]
In my case the main issue is with the version of SeuratObject. Downgrading to 4.1.3 solved my issues. I don't think the Seurat 4.x.x versions are compatible with the 5.x versions of SeuratObject, at least not in the case of this function.
