### ISSUE TITLE
The provided reduction.model does not have a model stored. Please try running umot-learn on the object first

### ISSUE THREAD

**Issue by Jingle0814** [satijalab/seurat#8112]
Hi,
Thank you to your team for developing WNN, I encountered an error while running WNN.
First,I used my integrated object to create a WNN reference.
The code:
bm<-readRDS("bm.rds")
DefaultAssay(bm) <- 'RNA'
bm <- NormalizeData(bm) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()%>%RunUMAP(dims=1:30, return.model = T)
DefaultAssay(bm) <- 'integrated'
VariableFeatures(bm) <- rownames(bm[["integrated"]])
bm <- RunPCA(bm,reduction.name = 'ipca')

#bm <- NormalizeData(bm) %>% ScaleData() %>% RunPCA(reduction.name = 'ipca')

#--------------------------------------------------calculate its closest neighbors based on a weighted combination of RNA
#### For each cell, we calculate its closest neighbors in the dataset based on a weighted combination of RNA and protein similarities. The cell-specific modality weights and multimodal neighbors are calculated in a single function, which takes ~2 minutes to run on this dataset. We specify the dimensionality of each modality (similar to specifying the number of PCs to include in scRNA-seq clustering), but you can vary these settings to see that small changes have minimal effect on the overall results.

# Identify multimodal neighbors. These will be stored in the neighbors slot, 
# and can be accessed using bm[['weighted.nn']]
# The WNN graph can be accessed at bm[["wknn"]], 
# and the SNN graph used for clustering at bm[["wsnn"]]
# Cell-specific modality weights can be accessed at bm$RNA.weight
bm <- FindMultiModalNeighbors(
#                               bm, reduction.list = list("pca", "apca"), 
                              bm, reduction.list = list("pca","ipca"),
                                  dims.list = list(1:30, 1:30), modality.weight.name = "RNA.weight"
                            #  dims.list = list(1:30), modality.weight.name = "RNA.weight"

                                )

bm <- RunUMAP(bm, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
bm <- FindClusters(bm, graph.name = "wsnn", algorithm = 3, resolution = 2, verbose = FALSE)
bm <- RunUMAP(bm, reduction = 'pca', dims = 1:30, assay = 'RNA',
                            reduction.name = 'rna.umap', reduction.key = 'rnaUMAP_')
bm <- RunUMAP(bm, reduction = 'ipca', dims = 1:30, assay = 'integrated',
                            reduction.name = 'integrate.umap', reduction.key = 'inteUMAP_')
saveRDS(bm,file="ref.WNN.rds")

Then I used another object to query, but I encountered an error：
The provided reduction.model does not have a model stored. Please try running umot-learn on the object first
The query code：
anchors <- FindTransferAnchors(
                                 reference = bm,
                                   query = scrna,
#                                    normalization.method = "SCT",
                                   normalization.method = "LogNormalize",
                                       reference.reduction = "pca",
                                         dims = 1:30
                                 )
query <- MapQuery(
                     anchorset = anchors,
                       query = scrna,
                         reference = reference,
                           refdata = list(
                                              celltype = "annotation"
#                                                 celltype.l2 = "celltype"
#                                                     predicted_ADT = "ADT"
                                                ),
#                    reference.reduction = "spca", 
                  reference.reduction = "pca",
#                      reduction.model = "wnn.umap"
                     reduction.model = "wnn.umap"
                     )
Is there some wrong with my analysis code? Or how do I solve this problem? Thanks a lot!

**Comment by Jingle0814** [comment]
There is a problem with this display,  my code:
1. create ref
    bm <- readRDS("bm.rds")
    DefaultAssay(bm) <- 'RNA'
    bm <- NormalizeData(bm) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()%>%RunUMAP(dims=1:30, return.model = T)
DefaultAssay(bm) <- 'integrated'
VariableFeatures(bm) <- rownames(bm[["integrated"]])
bm <- RunPCA(bm,reduction.name = 'ipca')

bm <- FindMultiModalNeighbors(bm, reduction.list = list("pca","ipca"),dims.list = list(1:30, 1:30), modality.weight.name = "RNA.weight")
bm <- RunUMAP(bm, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
bm <- FindClusters(bm, graph.name = "wsnn", algorithm = 3, resolution = 2, verbose = FALSE)
bm <- RunUMAP(bm, reduction = 'pca', dims = 1:30, assay = 'RNA',
                            reduction.name = 'rna.umap', reduction.key = 'rnaUMAP_')
bm <- RunUMAP(bm, reduction = 'ipca', dims = 1:30, assay = 'integrated',
                            reduction.name = 'integrate.umap', reduction.key = 'inteUMAP_')

2. WNN
  anchors <- FindTransferAnchors(
                                 reference = bm,
                                   query = scrna,
                                   normalization.method = "LogNormalize",
                                       reference.reduction = "pca",
                                         dims = 1:30
                                 )
query <- MapQuery(
                     anchorset = anchors,
                       query = scrna,
                         reference = reference,
                           refdata = list(
                                              celltype = "annotation"),
reference.reduction = "pca",
reduction.model = "wnn.umap"
)

The error I encounterd: 
The provided reduction.model does not have a model stored. Please try running umot-learn on the object first

**Comment by rsatija** [comment]
The issue here is that when you need to set return.model=TRUE on the call to RunUMAP (you do this in the first call, but then you rerun the function without setting the parameter).
We will also update the documentation to make this more clear.

**Comment by strawberry098** [comment]
I added the parameter `return.model = TRUE` during `RunUMAP`, but I am still getting `Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first` when I run MapQuery.

**Comment by HothriMoka** [comment]
Hi, Is this solved? I am using Seurat v_5.1.0, `return.model = TRUE` during RunUMAP, but still getting the 
> Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first

**Comment by mfiumara99** [comment]
@strawberry098 Use reduction.model = "umap" in MapQuery() and it works.
