### ISSUE TITLE
How do I use DESeq2 in Seurat?

### ISSUE THREAD

**Issue by Saumya513** [satijalab/seurat#8114]
I want to generate count matrix and perform the same DGE analysis as we do for bulk RNA seq data for single cell RNA seq data in Seurat.

**Comment by longmanz** [comment]
Hi, 
You may refer to this vignette for how to directly perform DESeq2 in Seurat: https://satijalab.org/seurat/articles/de_vignette . After you pseudo-bulk your cells you should be able to run DESeq2. 

Alternatively, you can extract your count matrix from Seurat `count_matrix = seurat_object@assays$RNA@counts` or `count_matrix = LayerData(seurat_object, layer = "RNA", assay = "counts"` (if you are using v5 object), and then follow your ordinary DESeq2 workflow.
