### ISSUE TITLE
Differential expression test between two seurat object's cell subtypes(clusters).

### ISSUE THREAD

**Issue by DUAN-GAO** [satijalab/seurat#8118]
Hi, guys, I would like to know something about differential expression test.
I am using Seurat 4.3.0.1, for celltypes in one seurat object I know that I can use function 

`
monocyte.de.markers <- FindMarkers(ifnb, ident.1 = "CD16 Mono", ident.2 = "CD14 Mono")
`
to test differential expression. But I got no idea how to do this between two objects for example pbmc1 and pbmc2. One cell cluster from pbmc1 and the other cell cluster from pbmc2.

Could anyone help, many thanks.

**Comment by DUAN-GAO** [comment]
Also, I tried merge function. The new combined seurat object mixed clusters from two seurat object which is not good since I need two separate cluster to fill in the parameter of the FindMarkers function.

**Comment by longmanz** [comment]
Hi,
To avoid the clusters got mixed up you can rename your cluster labels in pbmc1 and pbmc2, respectively. For example:
```
pbmc1$cluster = paste0("pbmc1_", pbmc1$cluster)
pbmc2$cluster = paste0("pbmc2_", pbmc2$cluster)

pbmc_merge = merge(pbmc1, y = pbmc2)

# run DE
Idents(pbmc_merge) = "cluster"
monocyte.de.markers <- FindMarkers(pbmc_merge, ident.1 = "pbmc1_CD16 Mono", ident.2 = "pbmc2_CD14 Mono")
```
