### ISSUE TITLE
Doing heat map by URD object

### ISSUE THREAD

**Issue by fereshtehizadi** [satijalab/seurat#812]
Sorry, Seurat has functions like **FeaturePlot**, **DimPlot** and **DoHeatmap** by which we can plot the expression of a list of genes on cell clusters. I am working with URD that likely does not have such options or I can not find that. URD has **plotDot** and **plotViolin** but would be clear only for a few number of genes (please look at the pictures). Could you please help me in doing DoHeatmap  by URD object? Because I need to plot more than 200 genes on cell clusters comes from URD

[

![](https://preview.ibb.co/bzy6Wp/R7MRf.jpg)
](url)

[

![](https://image.ibb.co/ihfZ1p/5.jpg)
](url)
Thanks a lot in advance

**Comment by andrewwbutler** [comment]
If you want to use clusters from another program with your Seurat object, you need to add them into the `object@meta.data` slot as a new column. You can use the `AddMetadata` function to add in additional vectors of information.
