### ISSUE TITLE
How to import the cell segmentation boundary information recognized by Cellpose in the format of *_cp_outlines.txt as segmentations into Seurat?

### ISSUE THREAD

**Issue by Rui-Jing** [satijalab/seurat#8124]
Thanks for developing this user-friendly tools for analysis ScRNA data.

I have image data similar to MerFISH. After upstream analysis, I obtain three types of files **similar to Vizgen**: cell_by_gene, Cell_metadata, and detected_transcripts. 
However, during cell segmentation, I processed the Z-stacked images with Cellpose, resulting in files in the ***_cp_outlines.txt format**. How can I read these files into Seurat so that they can be transformed into a format similar to the result of **GetTissueCoordinates(vizgen.obj[["s2r1"]][["segmentation"]])**, i.e., in the X, Y, Cell format?

The format of the ***_cp_outlines.txt** file is as follows:
[
![微信图片_20231202173036](https://github.com/satijalab/seurat/assets/59251760/9b0476ae-5945-42d7-862f-ed62234b1305)
](url)

The indices at the beginning of each row in the image correspond to the cell count I identified, matching the output in **data$centroids$cell**.
Can you help me convert the format of this type of outline file to a format that Seurat can use?

**Comment by MarcElosua** [comment]
Interested in this as well!

**Comment by alikhuseynov** [comment]
> Interested in this as well! Not just about CellPose but how to add multiple segmentation layers to the same object!

As far as I understood `SeuratObject` is using `sp` package to store segmentations.
If adding multiple layers, say `z` var, then using [`sf`](https://r-spatial.github.io/sf/) package would be a better option. 
`segmentation` would be basically a data frame and `sf` classes with `$geometry` var that stores polygons. 

Eg, for Vizgen output using `cell_boundaries.parquet`
```
polys <- sfarrow::st_read_parquet("./cell_boundaries.parquet")
polys %>% str
Classes ‘sf’ and 'data.frame':	559790 obs. of  10 variables:
 $ ID                : int  0 312 104 156 260 ...
 $ EntityID          :integer64 112833000000100001 112833000000100001 112833000000100001 ...
 $ ZIndex            : int  3 6 4 1 0 5 2 4 5 2 ...
 $ Type              : chr  "cell" "cell" "cell" "cell" ...
 $ ZLevel            : num  6 10.5 7.5 3 1.5 9 4.5 7.5 9 4.5 ...
 $ Name              : 'vctrs_unspecified' logi  NA NA NA  ...
 $ ParentID          : 'vctrs_unspecified' logi  NA NA NA  ...
 $ ParentType        : 'vctrs_unspecified' logi  NA NA NA ...
 $ X__index_level_0__: int  0 348 116 174 290  ...
 $ Geometry          :sfc_MULTIPOLYGON of length 559790; first list element: List of 1
  ..$ :List of 1
  .. ..$ : num [1:12, 1:2] 6805 6807 6808 6809 6809 ...
  ..- attr(*, "class")= chr [1:3] "XY" "MULTIPOLYGON" "sfg"
 - attr(*, "sf_column")= chr "Geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA
  ..- attr(*, "names")= chr [1:9] "ID" "EntityID" "ZIndex" "Type" ...
```
Then one can select the desired `z` layer and get only layer-specific cell segmentations.
```
# layers range from 0 to 6
polys_2 <- 
  #..for 2nd layer
  polys %>% dplyr::filter(ZIndex == 1)
```
This however, would require some re-implementation of FOV part in `SeuratObject` to support `sf` geomentries

**Comment by alikhuseynov** [comment]
> Thanks for developing this user-friendly tools for analysis ScRNA data.
> 
> I have image data similar to MerFISH. After upstream analysis, I obtain three types of files **similar to Vizgen**: cell_by_gene, Cell_metadata, and detected_transcripts. However, during cell segmentation, I processed the Z-stacked images with Cellpose, resulting in files in the ***_cp_outlines.txt format**. How can I read these files into Seurat so that they can be transformed into a format similar to the result of **GetTissueCoordinates(vizgen.obj[["s2r1"]][["segmentation"]])**, i.e., in the X, Y, Cell format?
> 
> The format of the ***_cp_outlines.txt** file is as follows: [ ![微信图片_20231202173036](https://private-user-images.githubusercontent.com/59251760/287435252-9b0476ae-5945-42d7-862f-ed62234b1305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTIxODAsIm5iZiI6MTcwNTU5MTg4MCwicGF0aCI6Ii81OTI1MTc2MC8yODc0MzUyNTItOWIwNDc2YWUtNTk0NS00MmQ3LTg2MmYtZWQ2MjIzNGIxMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE1MzEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjIwM2NhZTA3Yzc1YTU2ZDIyMTQ2ZjJmMzc5MGVhMWM2OThlYzc0MjAxMjYyNzlkNTA3ZDI0NWE0ZjQ3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XtxE6j6jyPXRESvNF5hGVLV6QctEXQBy4KYgtjtb4qA) ](url)
> 
> The indices at the beginning of each row in the image correspond to the cell count I identified, matching the output in **data$centroids$cell**. Can you help me convert the format of this type of outline file to a format that Seurat can use?

Probably you know already, that Vizgen is using mid-plane image for cell segmentation, so basically cell polygons in all `$Zindex` are the same. There is [Vizgen postprocessing pipeline](https://github.com/Vizgen/vizgen-postprocessing) that allows per `z` layer segmentation.

As for making `data$centroids$cell` x , y , and cell_id data frame from your `_cp_outlines.txt` file, should be easy, if that file has all the necessary information stored some how. Could you upload an example of that file or a file similar to it?

**Comment by igrabski** [comment]
Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions or questions requiring custom code like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum.

If you believe this question does represent a bug in the current code, please feel free to open a new issue with further details!

**Comment by igrabski** [comment]
Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions or questions requiring custom code like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum.

If you believe this question does represent a bug in the current code, please feel free to open a new issue with further details!
