### ISSUE TITLE
> library(Seurat) failed despite working before 

### ISSUE THREAD

**Issue by AhmedWKZ** [satijalab/seurat#8130]
I installed Seurat library and it was working before and now I got this error! any idea how to solve that ?

> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘httpuv’
In addition: Warning message:
package ‘Seurat’ was built under R version 4.0.5

**Comment by mhkowalski** [comment]
Hi, 

Thanks for reporting this. I haven't seen this particular error before, could you try restarting your R session, and then installing Seurat again? If this doesn't work, you could try upgrading your R version as well.

**Comment by mhkowalski** [comment]
Closing as we haven't heard back, please open a new issue if you are still experiencing problems with installing Seurat.
