### ISSUE TITLE
HTODemux gives weird results according to UMAP

### ISSUE THREAD

**Issue by jgarces02** [satijalab/seurat#8133]
Hi, 

Once applied `HTODemux` and remove doublets and negative cells, the UMAP gives me some strange results: there're two clusters identified with the barcodes (blue and green) and another one with the doublets (pink)... but then, there're a bunch of doublets located clearly in the green cluster and far away from the doublets' one. Could those "doublets" be considered as belonging to the green-barcoded cluster or are they certainly doublets?

![image](https://github.com/satijalab/seurat/assets/27858969/b50f0e23-1e57-4478-90a2-cf652fd13382)

Thanks!

**Comment by igrabski** [comment]
UMAP visualizations are not always completely accurate representations, but it also certainly possible to sometimes have either overly conservative or overly lenient results when demultiplexing based on choice of parameters. I would recommend visualizing the HTO values within the putative doublets (for example, by using some of the visualization methods demonstrated in the [vignette](https://satijalab.org/seurat/articles/hashing_vignette.html)) to help understand whether these seem like true doublets, or if the ones in the green cluster just have a slightly higher 'background' level of HTO counts for the other barcode.
