### ISSUE TITLE
why RunPCA has en error because of max(nu, nv) must be positive

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#814]
![image](https://user-images.githubusercontent.com/25199946/46243084-77948180-c402-11e8-8393-3a805de62c8b.png)

**Comment by andrewwbutler** [comment]
This can happen if you are requesting more PCs (20 is the default) than you have input features. How many genes are you using as input to `RunPCA` (`pbmc_Scale@var.genes`)?

**Comment by 2236529177** [comment]
> This can happen if you are requesting more PCs (20 is the default) than you have input features. How many genes are you using as input to `RunPCA` (`pbmc_Scale@var.genes`)?

Thanks a lot. andrewwbutler. So I need to confirm how many genes the scaled_data have before PCA.
and I am really puzzled the tutorial in website https://satijalab.org/seurat/pbmc3k_tutorial.html, it used the same vairable pbmc from start to finish，and I still could not figure out a clear typical solution for  seurat in 10xgenomics, do you have a good suggestion for me, thanks a lot.
> length(pbmc_Scale@var.genes)
[1] 0
> pbmc_Scale@var.genes
logical(0)
