### ISSUE TITLE
Featureplot of cells with zero expression in one of the layers in an integrated object fails

### ISSUE THREAD

**Issue by ishwarvh** [satijalab/seurat#8140]
All the cells in one of the layers in my integrated object has an expression value of 0 for a gene (Venus). 

Featureplot using the `split.by` argument, showed no expression values for this gene in that layer up until seurat v5.0, with a warning that all cells in one of the layer had the same value of (0) for that gene. This worked for my purpose since it is exactly what I expect in my data.

However this warning seems to have been converted into an error in Seurat v5.0.1 and featureplot using `split.by` argument is broken and does not output a plot.

I have tried setting `na.cutoff = 0`,  `na.cutoff = NA`, and even `na.cutoff="q10"`  which result in the same error.

```
Error: (converted from warning) All cells have the same value (0) of "Venus"
```

I am also seeing a similar error pop up when plotting features from the meta.data slot such as "nCount_RNA" and "nFeature_RNA". 

Again, this is new behaviour in v5.0.1. If this is an intentional change, please advise a workaround for this issue. If not, I would appreciate it if this change is reverted.

Thank you,
Ishwar

**Comment by mhkowalski** [comment]
Hello, 

this seems to be related to your R settings (this is a warning, which is intentional, but it is getting converted to an error automatically). 

could you try running ```options(warn = 1)```, and then try again?

**Comment by ishwarvh** [comment]
Ok, thank you. Not sure how that crept in. Restarting R seems to have fixed the issue.
