### ISSUE TITLE
as.Seurat function in Seurat5 is no longer accepting GeoMx dataset

### ISSUE THREAD

**Issue by dksenthil** [satijalab/seurat#8143]
I think `as.Seurat` function in Seurat5 is no longer accepting the GeoMx datasets. Followed the steps given in the below link. It was working fine  previously for me. 

https://www.bioconductor.org/packages/release/bioc/vignettes/GeomxTools/inst/doc/GeomxSet_coercions.html

```
demoSeurat <- as.Seurat(norm_target_demoData, normData = "q_norm")
Error in validObject(object = object) : 
  invalid class “Seurat” object: 'project' cannot be an empty character 
```

**Comment by wjzwjz5** [comment]
I also encountered the same problem, do you have a solution now?

**Comment by longmanz** [comment]
Hi, 
Sorry that it broke after Seurat v5, but this `as.Seurat` is actually implemented by the GeomxTools package (https://github.com/Nanostring-Biostats/GeomxTools/blob/master/R/coercions.R), and we cannot fix it from our end. A workaround is to downgrade your Seurat back to v4 to work with GeoMx data. 

I see that this issue has already been posted to GeomxTools's GitHub (https://github.com/Nanostring-Biostats/GeomxTools/issues/191). Hopefully they will respond and help solve this issue soon.
