### ISSUE TITLE
Editing output of FeaturePlot()

### ISSUE THREAD

**Issue by ForestCA** [satijalab/seurat#815]
I'd like to change the titles of individual plots (as well as customize the theme()) output from FeaturePlot(). I can currently do this by editing each single plot one at a time, but I'm wondering if I could (1) input a vector (or list?), (2) have it applied sequentially/respectively to each plot, (3) keeping the same output structure (i.e. multiple plots) as FeaturePlot()? 

Otherwise, given that I can extract the necessary data.frames, I'm not sure how to re-create the multiple plots (as they are output with each gene 'highlighted' in a different plot) using ggplot. 

I could try different approaches, I'm sure there is more than one way to do this. Thanks in advance for your help.

**Comment by andrewwbutler** [comment]
Hi,

I would use an apply statement or loop over the individual plots if you want to use the same customization options for each one. This would return a list of modified plots which you could then pass to `cowplot::plot_grid` to put them into a grid.
