### ISSUE TITLE
Most of cells in the full datasets have 'NA' cluster after Sketch integration

### ISSUE THREAD

**Issue by Alvis-Jiang** [satijalab/seurat#8152]
Hi, 

I am recently using the Sketch integration method to integrate two scalable datasets.  AfterI integrated the full datasets using [ProjectIntegration] and [ProjectData], I found that most of the cells in the full datasets have an 'NA'  seurat_cluster. Could you please give me any suggestions on this issue? My codes are below:

merged.object <- LoadSeuratRds('/Data_collection/All_datasets_Merged_BPcell/All_datasets_Merged.rds')
merged.object <- NormalizeData(merged.object)
merged.object[["RNA"]] <- split(merged.object[["RNA"]], f = merged.object$project)
merged.object <- FindVariableFeatures(merged.object)
merged.object <- SketchData(object = merged.object, ncells = 5000, method = "LeverageScore", sketched.assay = "sketch")
DefaultAssay(merged.object) <- "sketch"
merged.object <- FindVariableFeatures(merged.object)
merged.object <- ScaleData(merged.object)
merged.object <- RunPCA(merged.object)
merged.object_INT <- IntegrateLayers(merged.object, method = RPCAIntegration,
                                     orig.reduction = "pca", new.reduction = "integrated.rpca")
merged.object_INT <- FindNeighbors(merged.object_INT, reduction = "integrated.rpca", dims = 1:30)
merged.object_INT <- FindClusters(merged.object_INT, resolution = 2 )
merged.object_INT  <- RunUMAP(merged.object_INT , reduction = "integrated.rpca", dims = 1:30, return.model = T)
merged.object_INT <- ProjectIntegration(object = merged.object_INT, sketched.assay = "sketch", assay = "RNA", reduction = "integrated.rpca")
merged.object_INT <- ProjectData(object = merged.object_INT, sketched.assay = "sketch", assay = "RNA", sketched.reduction = "integrated.rpca.full", full.reduction = "integrated.rpca.full", dims = 1:30)
object <- RunUMAP(merged.object_INT, reduction = "integrated.rpca.full", dims = 1:30, reduction.name = "umap.full",
    reduction.key = "UMAP_full_")

The metadata on the merged.object_INT shows most of cells have no cluster info.
![WeChat Screenshot_20231207110702](https://github.com/satijalab/seurat/assets/64271338/10a76a6f-5183-4215-b015-4c81a9be5a47)

Thank you so much!

**Comment by rsatija** [comment]
The `ProjectData` function, in this context, should transfer labels from the sketched cells to the entire dataset. In order for this to happen, you need to specify where the labels are stored for the sketched cells. You can do this with the `refdata` parameter, which I think is missing from your function call.

As an example from the parse sketch integration vignette, the cell type labels from the sketched cells were stored in the `celltype.manual` metadata column.

```
object <- ProjectData(object = object, sketched.assay = "sketch", assay = "RNA", sketched.reduction = "integrated.rpca.full",
    full.reduction = "integrated.rpca.full", dims = 1:30, refdata = list(celltype.full = "celltype.manual"))
```

**Comment by sentisci** [comment]
Hi,  I am having the smae issue . Cells that were not used dueing SketchData step are not assigned to a cluster and declared <NA>
I  followed the following Vignette https://satijalab.org/seurat/articles/parsebio_sketch_integration 

My code:


filtered_seurat <- NormalizeData(filtered_seurat)
filtered_seurat <- FindVariableFeatures(filtered_seurat, verbose = FALSE)
filtered_seurat <- SketchData(object = filtered_seurat,
                              ncells = 5000,
                              method = "LeverageScore",
                              sketched.assay = "sketch")
filtered_seurat
filtered_seurat <- FindVariableFeatures(filtered_seurat)
filtered_seurat <- ScaleData(filtered_seurat)
filtered_seurat <- RunPCA(filtered_seurat)
filtered_seurat <- IntegrateLayers(
  object = filtered_seurat, method = RPCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.rpca",
  dims = 1:30, k.anchor = 20, 
  verbose = FALSE
)
filtered_seurat <- FindNeighbors(filtered_seurat,reduction = "integrated.rpca",
                                 dims = 1:30)
filtered_seurat <- FindClusters(filtered_seurat, resolution = 0.5,
                                cluster.name = "rpca_clusters")

filtered_seurat_project <- ProjectIntegration(object = filtered_seurat,
                                      sketched.assay = "sketch", assay = "RNA",
                                      reduction = "integrated.rpca")

filtered_seurat_project_2 <- ProjectData(object = filtered_seurat_project, sketched.assay = "sketch",
                               assay = "RNA", sketched.reduction = "integrated.rpca",
                      full.reduction = "integrated.rpca.full", dims = 1:30,
        refdata = list(celltype.full = "rpca_clusters"))

> filtered_seurat@meta.data$rpca_clusters[1:10]
 [1] <NA> 6    5    1    7    <NA> <NA> <NA> <NA> <NA>
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

> filtered_seurat_project@meta.data$rpca_clusters[1:10]
 [1] <NA> 6    5    1    7    <NA> <NA> <NA> <NA> <NA>
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
> colnames(filtered_seurat_project@meta.data)
 [1] "seq_folder"       "nUMI_RNA"         "nGene"            "nUMI_ADT"         "nFeature_ADT"     "percent_mt"      
 [7] "percent_ribo"     "log10GenesPerUMI" "cells"            "type"             "nUMI_RNA_1og10"   "nUMI_ADT_1og10"  
[13] "nCount_SCT"       "nFeature_SCT"     "nCount_RNA"       "nFeature_RNA"     "nCount_ADT"       "Patient"         
[19] "Group"            "leverage.score"   "rpca_clusters"    "seurat_clusters" 


Can you please review and let me know as soon as you can ? Thanks in advance

**Comment by SchaferLabUMassChan** [comment]
Hi @sentisci @rsatija ! I'm having the same issue. Did you find a solution? I do have a celltype.manual column in my metadata but I still see most of the cells as NA after I run this and I don't see a new metadata column named celltype.full
object <- ProjectData(object = object, sketched.assay = "sketch", assay = "RNA", sketched.reduction = "integrated.rpca.full",
                      full.reduction = "integrated.rpca.full", dims = 1:30, refdata = list(celltype.full = "celltype.manual"))
Thanks!
