### ISSUE TITLE
Why  set margin=2 when performing data Normalization on ADT assay in the WNN tutorial page?

### ISSUE THREAD

**Issue by wchenqi** [satijalab/seurat#8159]
Hello,

when I tried to follow the codes presented on WNN section "https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis", it wrote that: "bm <- [NormalizeData](https://satijalab.org/seurat/reference/normalizedata)(bm, normalization.method = 'CLR', margin = 2)".

Why do we need to set margin to 2 for ADT normalization，but not for RNA assay normalizaion?

Thank you~

**Comment by mhkowalski** [comment]
Hello, 

Thanks for your question. Please see #3605. For CLR normalization, we want to normalize within a cell (i.e. margin=2) when our antibody panels are sufficiently large. If you only have a couple of antibodies, then this doesn't work, in which case we'd recommend using margin=1. Our standard log-normalization for RNA, (`method="LogNormalize"`) also normalizes data within a cell. Please see the `NormalizeData` documentation for more details on this calculation.
