### ISSUE TITLE
10x data with Error in seq.int(rx[1L], rx[2L], length.out = nb) :    'to' must be a finite number

### ISSUE THREAD

**Issue by marong0511** [satijalab/seurat#816]
Hi everyone,

Recently I analyzed a batch of 10x data, when I followed the instruction on the website, everything worked well. However, when I delved into the package documents in details, I found there exist several specific models for UMI data in the step 'ScaleData'. So I modified my parameter as below:
```R
ctrl.new <- NormalizeData(object = ctrl.new, 
                          normalization.method = "LogNormalize",
                          scale.factor = 10000)
ctrl.new <- ScaleData(object = ctrl.new,
                      model.use = 'negbinom',
                      use.umi = TRUE,
                      vars.to.regress = c("nUMI", "percent.mito"),
                      display.progress = TRUE,
                      do.par = TRUE)
ctrl <- ctrl.new
pdf(file = "hcon_variable_genes_no_threshold.pdf",width = 12, height = 8)
par(mfrow= c(1,1))
ctrl <- FindVariableGenes(object = ctrl, 
                          mean.function = ExpMean, 
                          dispersion.function = LogVMR,
                          x.low.cutoff = 0.01,
                          x.high.cutoff = 3,
                          y.cutoff = 0.5)
dev.off()
```
Then I got the error message: Error in seq.int(rx[1L], rx[2L], length.out = nb) :    'to' must be a finite number

I did normalize the data. Anyone can tell me what' wrong with this?

Thanks

**Comment by satijalab** [comment]
Apologies as we were never able to reproduce this. I am closing as we have improved versions of variable feature selection in Seurat v3, which should not return this error, but please re-open this issue if you continue to have the same error with the latest version.
