### ISSUE TITLE
How can I import Anndata to seurat?

### ISSUE THREAD

**Issue by uqnsarke** [satijalab/seurat#8163]
I was trying to convert Anndata to Seurat, but its not working.
library(SeuratDisk)
Convert("PFC_Results_res004.h5ad", ".h5seurat")
seuratObj <- LoadH5Seurat("PFC_Results_res004.h5Seurat")

Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat

Warning message:
“Unknown file type: h5ad”
Warning message:
“'assay' not set, setting to 'RNA'”
Creating h5Seurat file for version 3.1.5.9900

Adding X as scale.data

Adding raw/X as data

Adding raw/X as counts

Adding meta.features from raw/var

Adding dispersions from scaled feature-level metadata

Adding dispersions_norm from scaled feature-level metadata

Merging feature_types from scaled feature-level metadata

Error in source[["var"]][[mf]]$read(): attempt to apply non-function
Traceback:

1. Convert("PFC_Results_res004.h5ad", ".h5seurat")
2. Convert.character("PFC_Results_res004.h5ad", ".h5seurat")
3. Convert(source = hfile, dest = dest, assay = assay, overwrite = overwrite, 
 .     verbose = verbose, ...)
4. Convert.H5File(source = hfile, dest = dest, assay = assay, overwrite = overwrite, 
 .     verbose = verbose, ...)
5. H5ADToH5Seurat(source = source, dest = dest, assay = assay, overwrite = overwrite, 
 .     verbose = verbose)

**Comment by lisch7** [comment]
Maybe you can follow the following instruction: https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette

**Comment by Gesmira** [comment]
Hi, 
SeuratDisk is no longer actively supported. I recommend using the workflow @lisch7 tagged: `data <- open_matrix_anndata_hdf5(path)`
OR using [sceasy](https://github.com/cellgeni/sceasy).

**Comment by AleksZakirov** [comment]
@Gesmira thank you very much, the sceasy worked for me, while no other method yielded anything meaningful.

```
library(Seurat)
library(sceasy)
library(reticulate)

h5ad_path = "path/to/file/file.h5ad"
sceasy::convertFormat(h5ad_path, from="anndata", to="seurat",
                       outFile='filename.rds')

data = readRDS('filename.rds')
```
