### ISSUE TITLE
Integrating cells from same experiment?

### ISSUE THREAD

**Issue by t1nnenissen** [satijalab/seurat#8165]
Hi there, 

I have a question regarding the Seurat analysis of my single cell RNA seq data that I would love to get your opinion on. My dataset consists of stem cells treated for 48 hours with control, low TNF, or high TNF (these cells were multiplexed and run on the same chip)

When looking at the UMAP plots after qc I can see that the cells treated with control or low TNF cluster together/overlay. However, the cells treated with high TNF cluster by itself. 

My questions is whether I should integrate my data across the three treatment groups? Some places I read that this is appropriate when you have treated cells. 

My understanding is that integration is there to help iron out technical and statistical noise. In addition, they can potentially reduce real biological effects. As I reduced batch effect by harvesting cells on the same day and running them on the same chip I am unsure if I should integrate.

Looking forward to hearing from you!

Best,
Tinne

**Comment by igrabski** [comment]
Hi Tinne, thanks for your question. In this case, because you expect true biological differences to distinguish these three groups, you are correct that you should not integrate here because you will likely remove the biological effect.
