### ISSUE TITLE
Finding differentially expressed genes between Seurat clusters

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8167]
Good afternoon,

I am working with a dataset of 7 patients. I have merged all raw counts to one count object with JoinLayers:

Now I would like to know whether there are certain genes differentially expressed between my Seurat clusters. For that I ran

```
markers_all<-FindAllMarkers(kid.filtered_new,     
                test.use = 'DESeq2',       
                slot = 'counts')
```
However, it does not find any differentially expressed genes, which I believe can't be true.

I wonder whether it has to do with the way I joined the counts of the 7 patients.

```
kid.filtered_new<- JoinLayers(kid.filtered)

pbmc_counts_combined <- GetAssayData(kid.filtered_new, slot = 'counts')

pred_combined <- SingleR(test = pbmc_counts_combined,
        ref = ref,
        labels = ref$label.main)

kid.filtered_new$singleR.labels <- pred_combined$labels[match(rownames(kid.filtered_new@meta.data), rownames(pred_combined))]
```

Maybe I should perform all the data preparation jobs again after joining the data (I ran all this before joining the layers, which I believe is then done by patient (layer) individually):

```
kid.filtered <- NormalizeData(object = kid.filtered)
kid.filtered <- FindVariableFeatures(object = kid.filtered)
kid.filtered <- ScaleData(object = kid.filtered)
kid.filtered <- RunPCA(object = kid.filtered)
kid.filtered <- FindNeighbors(object = kid.filtered, dims = 1:20)
kid.filtered <- FindClusters(object = kid.filtered, resolution=0.1) # directly specify which resolution 
kid.filtered <- RunUMAP(object = kid.filtered, dims = 1:20)
```

Thank you for any help!!

**Comment by ishwarvh** [comment]
Hello, 
Not a member of dev team, but hopefully can offer some help as I am dealing with something similar right now. 
I am assuming you are working with Seurat 5. If so, could you tell me how you merged your datasets?
Also, I don't see any type of integration steps. May be integrating your data with harmony or RPCA may yield better results.

**Comment by LeaLe88** [comment]
Hey, thank you for your answer.  Yes, I am working with Seurat 5. I have solved the issue and I was able to find differentially expressed genes. However, I still wonder whether I should normalise the data before or after (or both) joining the layers? 
I have also integrated data now, however I read that for differential expression analysis we shouldn't use integrated data, or?

**Comment by mhkowalski** [comment]
Hello, 

It does not matter whether you normalize before or after joining the layers. Also, you are correct that you shouldn't use the integrated data for differential expression.  I hope this is helpful.

**Comment by LeaLe88** [comment]
Thank you very much for your answer!
