### ISSUE TITLE
Dim Plot

### ISSUE THREAD

**Issue by nitinmahajan20** [satijalab/seurat#8170]
I am using the Posit Workbench on Sagemaker. I am running Dimplot function, but I am getting the error shown below.

Interestingly,  when I am running the same function on my local machine using the same object, it works fine. 

```r
# DimPlot(filtered_seurat_R, group.by = "orig.ident", reduction = "umap", label = FALSE)
```

```r
Error in Ops.data.frame(guide_loc, panel_loc) : 
  '==' only defined for equally-sized data frames
```

![Screenshot 2023-12-11 at 12 37 13 PM](https://github.com/satijalab/seurat/assets/36308726/bf38c988-dd0f-46d0-9ee4-688ff8344598)

**Comment by igrabski** [comment]
Hi Nitin, it looks like this may be related to your version of ggplot2 -- see this issue with [Patchwork/ggplot](https://github.com/thomasp85/patchwork/issues/342). In particular, it looks like you are using the developmental version of ggplot2, 3.4.4.9000, but version 3.4.4 should work.

**Comment by nitinmahajan20** [comment]
I uploaded the new version and restarted the R , Yes, it is working. 

Thank you!!!
