### ISSUE TITLE
Finding a gene expression with sequence?

### ISSUE THREAD

**Issue by azwainCC** [satijalab/seurat#8171]
Hello
Is there a way to check gene expression from single cell data with sequence?
I would like to select few cells expressing a particular gene which I couldn't trace from data as it is not present in the genome of the organism. 
We have transgenetically/artificially generated this line with human genome sequence to knockdown some other gene expression.

Thanks in advance for your help,
Az

**Comment by saketkc** [comment]
If I understand it correctly, you would like to visualize the expression of a gene (sequence) which was not part of the genome. You would need to make this gene part of your annotation (gtf file) before quantifying. In other words, this step needs to happen at the alignment step (before running Seurat).

Feel free to reopen if I have misunderstood your question
