### ISSUE TITLE
Pooled scRNAseq data differential analysis

### ISSUE THREAD

**Issue by rustlab1** [satijalab/seurat#8173]
Hi, 

I hope you can help me with a probably trivial question: 

I have pooled data from n=6 mice of specific brain regions. I want to look at differential gene expression after treatment in individual celltypes. Since I assume I cannot perform pseudo-bulk analysis (because my samples are pooled), what is the recommended way to analyse the data, using simply FindMarkers?  e.g.

```{r}
vascular.de <- FindMarkers(merged_seurat.combined, ident.1 = "Vascular_Stim", ident.2 = "Vascular_CTRL", verbose = FALSE)
```
Or is there any other way or any correction that I can add to avoid false positives. Appreciate any guidance you can provide. Thanks for your work on the Seurat package. It's been very helpful.

**Comment by rsatija** [comment]
Unfortunately you cannot perform DE analysis in pseudobulk if you don't have any replicate identifiers (i.e. if you have no way of determining which cell originated from which animal). You can still perform single cell-level DE, but there will be no way of controlling for inter-individual variation across animals.

In the future you could consider running our [cell hashing](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1603-1) workflow to retain sample identity prior to pooling
