### ISSUE TITLE
ERROR :Matrix type cannot be converted to python

### ISSUE THREAD

**Issue by SEVEN1003** [satijalab/seurat#8174]
When I was in seurat v5 when running the code
```
obj <- IntegrateLayers(
  object = obj, method = scVIIntegration,
  new.reduction = "integrated.scvi",
  conda_env = conda_env, verbose = FALSE
)
```
The following error occurred

error : Matrix type cannot be converted to python(only integer, numeric, complex, logical, and character matrixes can be converted
What is the reason for this？

**Comment by leo0on** [comment]
me too!!!!!
hope for a result TAT

**Comment by dcollins15** [comment]
Are you able to run this on the example dataset from our [Integrative analysis](https://satijalab.org/seurat/articles/seurat5_integration) vignette?

**Comment by SEVEN1003** [comment]
I tried this tutorial, but another error, I didn't run RunAzimuth, seems to be an error because the network problem, my code is shown below. It is worth mentioning in my seurat v4.9 version to be able to run all of the code, including RunAzimuth and scVI integration

```
rm(list = ls())
library(BPCells)
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(SeuratWrappers)
options(future.globals.maxSize = 1e9)
options(Seurat.object.assay.version = "v5")

# load in the pbmc systematic comparative analysis dataset
obj <- SeuratData::LoadData("pbmcsca")
obj <- subset(obj, nFeature_RNA > 1000)
# obj <- RunAzimuth(obj, reference = "pbmcref")
# currently, the object has two layers in the RNA assay: counts, and data
obj
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$Method)
obj

### start
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)

conda_env = 'C:\\Users\\15642\\AppData\\Local\\r-miniconda\\envs\\scVI_v5'
obj <- IntegrateLayers(
  object = obj, method = scVIIntegration,
  new.reduction = "integrated.scvi",
  conda_env = conda_env, verbose = FALSE
)

```

**Comment by SEVEN1003** [comment]
in addition, I can run HarmonyIntegration and FastMNNIntegration, but sometimes when I run RPCAIntegration, I got 
 Error in 'ScaleData()' :
! No layer matching pattern 'data' found. Please run NormalizeData and retry

**Comment by dcollins15** [comment]
Could you please clarify which lines are throwing which errors/warnings — it's difficult to tell what's going on from the information you provided. 

If you're still encountering the initial error message when running your code on the example dataset there may be an issue with your `conda` env. Otherwise, if the code runs fine, the problem is likely with your dataset. 

For unrelated problems, please open a separate issue.
