### ISSUE TITLE
SCT merged data and Bridge Integration

### ISSUE THREAD

**Issue by leeanapeters** [satijalab/seurat#8177]
Hi, thank you for the great package!

I am performing bridge integration and am wondering if it is possible to use merged data rather than integrated data?

When specifying "SCT" for normalization I get the error: "Given reference assay (SCT) has 13 reference sct models. Please provide a reference assay with a  single reference sct model" which I know should be solved by specifying the integrated assay. However since my data are batch corrected and merged rather than integrated I am not sure how to get past this. 

Can you let me know if this is feasible or if it is necessary to use the integrated assay for this procedure?

Thanks!

Leeana

**Comment by saketkc** [comment]
HI @leeanapeters, I would recommend using integrated assay (i.e. running integration) with the Bridge workflow. The integrated assay stores only one SCT model.
