### ISSUE TITLE
VlnPlot with different Seurat Objects

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#8186]
Hello

I have 2 seurat objects - one with just the raw reads and one which I have filtered for nFeatures nCounts and percent.mt.

I want to create compiled graphs of both before/after QC of the data which is in 2 different objects (object 1: raw, object2: QC filtered)

Is there a way to get (eg) nFeature of object 1 and object 2 onto the same Vlnplot?

**Comment by saketkc** [comment]
You can merge the dataset:

```r
dataset1$type <- "Before QC"
dataset2$type <- "After QC"
dataset1 <- RenameCells(dataset1, add.cell.id="data1")
dataset2 <- RenameCells(dataset1, add.cell.id="data2")
merged <- merge(dataset1, dataset2)
VlnPlot(merged, features = c("nFeature_RNA", "nCount_RNA"), group.by="type")
```
