### ISSUE TITLE
Error in NormalizeData:  'meta.features' must have the same features as 'data'

### ISSUE THREAD

**Issue by vertesy** [satijalab/seurat#8187]
Hello,

I have been using `future_lapply` for `NormalizeData` on a list of Seurat objects for years. Suddenly (v.5 ?) I encountered an error:

### Code
```r
future.apply::future_lapply(X = ls.Seurat, FUN = NormalizeData, normalization.method = "LogNormalize", scale.factor = 10000)
```

### Error
```r
Error in validObject(object = value) : 
  invalid class “Assay” object: meta.features' must have the same features as 'data'
```

### ls.Seurat
```r
ls.Seurat
$sc06.692
An object of class Seurat 
27786 features across 7154 samples within 1 assay 
Active assay: RNA (27786 features, 0 variable features)
 2 layers present: counts, data

$sc06.693
An object of class Seurat 
26673 features across 3368 samples within 1 assay 
Active assay: RNA (26673 features, 0 variable features)
 2 layers present: counts, data
 
 ...etc
```

### Debug

```r
obj <- ls.Seurat[[2]]
obj <- NormalizeData(object = obj, normalization.method = "LogNormalize", scale.factor = 10000)
obj <- NormalizeData(object = obj, normalization.method = "RC", scale.factor = 10000)
```
both fail with the same error. There is something wrong with individual objects.

```r
> l(rownames(obj[["RNA"]]@meta.features))
[1] 26673
> l(rownames(obj[["RNA"]]@data))
[1] 26673
> l(rownames(obj[["RNA"]]@counts))
[1] 26673
```

**Comment by vertesy** [comment]
```r

idx.Miss <- (rownames(obj[["RNA"]]@meta.features) != rownames(obj[["RNA"]]@data))
cbind(rownames(obj[["RNA"]]@meta.features)[idx.Miss]
               , rownames(obj[["RNA"]]@data)[idx.Miss]
                         )
[,1]                             [,2]                       
[1,] "NA"                             "LINC02593"                
[2,] "NA.1"                           "PRXL2B"                   
[3,] "NA.2"                           "PRDM16-DT"                
[4,] "NA.3"                           "LNCTAM34A"                
[5,] "NA.4"                           "SLC66A1"                  
[6,] "NA.5"                           "MICOS10"                  
[7,] "NA.6"                           "YARS1"          
```

**Comment by vertesy** [comment]
This may not be a Seurat issue. 
It seems to be a consequence of updating mapped gene names to the latest HGNC symbols, was incompletely performed (not updated in `@meta.features`).

This issue however is long present, so Seurat seem to have become more sensitive to it.


`SeuratUtils::RenameGenesSeurat`  ...
> called by `SeuratUtils::UpdateGenesSeurat`  
> called by `SeuratUtils::Convert10Xfolders`
... always missed the feature to deal with  `@meta.features`.

**Comment by Gesmira** [comment]
Hi, 
Can you share the code you used to update the genes to the latest symbols as well as a small reproducible example? If you have an object you can share, you can email it to `gmolla@nygenome.org`.

**Comment by vertesy** [comment]
Hey, the issue seem to have been caused by [`SeuratUtils::RenameGenesSeurat`](https://github.com/vertesy/Seurat.utils/blob/24cc3d22166f1807dcdd9e2348d956efdafcb792/R/Seurat.Utils.R#L2678), which now has an experimental phase solution to it. Also addressed in https://github.com/satijalab/seurat/issues/1049#issuecomment-1859297524
