### ISSUE TITLE
Best Method of Combining RNA Velocity and sc-RNAseq dimensionality reduction

### ISSUE THREAD

**Issue by jwalewski** [satijalab/seurat#8188]
Hello,

I am wondering what the most effective method of combining sc-RNAseq UMAP clusters (currently generated in Seurat, but could be done in python with sklearn's UMAP method if needed) and count matricies generated with velocyto intended to be run in CellRank (scvelo) to infer RNA velocity.

As the field currently stands today, I see three possible options:
- Do the entire process in python, which would mean using sklearn's UMAP method and applying it to single cell data 
- Generate clusters in seurat, and then write the result out to an H5AD file which is imported into scvelo along with the loom file generated by veloctyo (and writing code to combine them)
- Finally, I wonder if it would be possible to load the H5AD/Loom files into R, combine/integrate (I plan to do this with 20 samples), and then load everything into scvelo for RNA velocity

Of these options, what is likely the most accurate and time efficient? Easiest to implement?

Many thanks for your consideration!

**Comment by rsatija** [comment]
If you would like to use any of Seurat's functions for cluster determination, then the second option should be quite straightforward. You can export a clustered Seurat objet to H5AD, import into python, and run scvelo/cellrank.
