### ISSUE TITLE
Which clustering is right?

### ISSUE THREAD

**Issue by fereshtehizadi** [satijalab/seurat#819]
Sorry,

I have clustered my cells by seurat by

```
FindClusters(object = seurat, reduction.type = "pca", dims.use = 1:13, 
                     save.SNN = TRUE)
```

By which I was able to annotate my clusters by some marker genes.

Now, I have clustered my cells by URD with different methods like 

`graphClustering(object, num.nn = c(50,60,70), do.jaccard=T, method="Louvain")
`
and 

`graphClustering(object, num.nn = c(50,60,70), do.jaccard=T, method="Infomap")
`

But I am not able to annotate clusters by my markers anymore and similarity between seurat clusters and URD ones in terms of cells assign to each cluster is pretty low. 

Could you please give me some clues to know which clustering methods make more sense and is right to be followed?

Thanks a lot in advance

**Comment by satijalab** [comment]
That question is a bit broad for a GitHub issue, but if you are interested, Martin Hemberg's group wrote a very nice review on single cell clustering

https://www.nature.com/articles/s41576-018-0088-9
