### ISSUE TITLE
FindNeighbors speediest parameters

### ISSUE THREAD

**Issue by mjrmason** [satijalab/seurat#8190]
Hi I am computing cell neighbors using the FindNeighbors function and returning the neighbors. 

`FindNeighbors(sc_obj, dims = 5, return.neighbor = T)`

I am running this on a seruat object and am looking for parameters to speed this up. I am using a very larger instance but multiple cores are not being used. I suspect that this function will be parallelized in the future but in the mean time I was wondering if you could provide suggestions for which parameters to use to speed it up. Like nn.method, n.tree, annoy.metric, k.param and others.
I'd like to be able to run it on 200K + cells eventually.

Thank you kindly,
Mike

**Comment by samuel-marsh** [comment]
Hi Mike,

Not member of dev team but hopefully can be helpful.  How long is `FindNeighbors` taking you to run?  I just ran couple timings on some of my own data and even 150K cells takes under a minute with 40 dims and default parameters on my laptop.  Are you experiencing significantly slower?

Best,
Sam

**Comment by mhkowalski** [comment]
Hello, 

I agree with Sam that `FindNeighbors` is not likely to be a time-intensive step or the limiting factor in analyzing large dstasets in our experience.

**Comment by mjrmason** [comment]
Hi, sorry for going MIA. Find Neighbors is taking me over two hours. Does that help?

**Comment by mjrmason** [comment]
Ok I have done some sleuthing and you are right. The speed issue is on my end. Sorry.

**Comment by xoelmb** [comment]
Hi, I'm experiencing a similar issue trying to follow the integration pipeline in Seurat 5 when I try to compute neighbors in an object with 4 layers, only RNA assay.
Could you elaborate on what your specific issue was in case that helps me debug my pipeline?
Thanks in advance
