### ISSUE TITLE
How to convert spatial data from Scanpy (python) to Seurat (R) ?

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#8191]
Thanks for the update of Seurat to process the spatial transcriptome data. Could you please help me with converting the patial data from Scanpy (python) to Seurat (R) ?

I got the h5ad file (spatial transcriptome data.). And it cannot be loaded by Seurat through the previous method:
```
 library('seurat-disk')
 Convert("Human.h5ad",
         dest="h5seurat",
         assay = "RNA",
         overwrite=F)
```

**Comment by grimwoo** [comment]
Here is a simplified [solution online](https://blog.csdn.net/qq_52813185/article/details/129713083#:~:text=%E4%BB%8EScanpy%E7%9A%84Anndata%E5%AF%B9%E8%B1%A1%E6%8F%90%E5%8F%96%E4%BF%A1%E6%81%AF%E5%B9%B6%E8%BD%AC%E6%88%90Seurat%E5%AF%B9%E8%B1%A1%EF%BC%88%E9%80%82%E7%94%A8%E4%BA%8E%E7%A9%BA%E9%97%B4%E7%BB%84%E4%B8%94%E6%B6%89%E5%8F%8Ah5%E6%96%87%E4%BB%B6%E8%AF%BB%E5%86%99%EF%BC%89%201%20Anndata%E5%AF%B9%E8%B1%A1%E8%BD%AC%E6%88%90Seurat%E5%AF%B9%E8%B1%A1,2%20h5%E6%96%87%E4%BB%B6%E8%AF%BB%E5%86%99%203%20%E7%A9%BA%E9%97%B4%E7%BB%84%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2), I modified it a little.

Before it, I have to mention the following tips: 
1, This method cannot plot the figure as beutiful as it in Scanpy. It lost the HE staining layer of the sequenced sample. Anyone who knows how to solve this problem please let me know.
2, We do not have to create a spatial Seurat object. I do not know what happened, but the speed of plot (```SpatialFeaturePlot``` vs ```FeaturePlot```) is much lower. And the plots of these two function are quite similar, so this step is not necessary.



### Here is the modified code:

```
library(Seurat)
library(dplyr)
library(ggplot2)
library(stringr)
library(reticulate)
reticulate::use_condaenv(condaenv = "D:/Anaconda/envs/scRNA", required = TRUE)
library("anndata")

  data <- read_h5ad("D:/Data/Human.h5ad") # Using Scanpy in python environment
  Object <- CreateSeuratObject(counts = t(as.matrix(data$X)), meta.data = data$obs)
  
  Object <- NormalizeData(Object)
  Object <- FindVariableFeatures(Object, nfeatures = 2000)
  Object <- ScaleData(Object)
  Object <- RunPCA(Object, npcs = 30)
  Object <- RunUMAP(Object, dims = 1:30) # to load the Spatial location information

  Object@reductions$Spatial <- Object@reductions$umap
  Object@reductions$Spatial@cell.embeddings <- data$obsm$X_spatial
  rownames(Object@reductions$Spatial@cell.embeddings) <- rownames(Object@reductions$umap@cell.embeddings)
  colnames(Object@reductions$Spatial@cell.embeddings) <- colnames(Object@reductions$umap@cell.embeddings)
  Object@reductions$Spatial@key <- 'Spatial_'
  colnames(Object@reductions$Spatial@cell.embeddings) <- gsub(
    pattern = "umap_", replacement = 'Spatial_', 
    x = colnames(Object@reductions$Spatial@cell.embeddings))

  FeaturePlot(Object, features = 'nCount_RNA',
              reduction = 'Spatial',
              pt.size = 3,
              raster = F, order = T)
```

###The following code would create a spatial Seurat object, which I do not recomond.
```
  library(dplyr)
  library(data.table)
  library(Matrix)
  library(rjson)
  pos <- Object@reductions$Spatial@cell.embeddings
  tissue_lowres_image <- matrix(1, max(pos[,1]), max(pos[,2]))
  tissue_positions_list <- data.frame(row.names = colnames(Object),
                                      tissue = 1,
                                      row = pos[,1], col = pos[,2],
                                      imagerow = pos[,1], imagecol = pos[,2])
  scalefactors_json <- toJSON(list(fiducial_diameter_fullres = 1,
                                   tissue_hires_scalef = 1,
                                   tissue_lowres_scalef = 1))
  mat <- Object@assays$RNA@layers$counts
  rownames(mat) <- rownames(Object)
  colnames(mat) <- colnames(Object)
  
  seurat_spatialObj <- CreateSeuratObject(mat, project = 'Spatial', assay = 'Spatial',min.cells=5, min.features=5)
  generate_spatialObj <- function(image, scale.factors, tissue.positions, filter.matrix = TRUE) {
    if (filter.matrix) {
      tissue.positions <- tissue.positions[which(tissue.positions$tissue == 1), , drop = FALSE]
    }
    
    unnormalized.radius <- scale.factors$fiducial_diameter_fullres * scale.factors$tissue_lowres_scalef
    spot.radius <- unnormalized.radius / max(dim(image))
    return(new(Class = 'VisiumV1',
               image = image,
               scale.factors = scalefactors(spot = scale.factors$tissue_hires_scalef,
                                            fiducial = scale.factors$fiducial_diameter_fullres,
                                            hires = scale.factors$tissue_hires_scalef,
                                            lowres = scale.factors$tissue_lowres_scalef),
               coordinates = tissue.positions,
               spot.radius = spot.radius))
  }
  
  spatialObj <- generate_spatialObj(image = tissue_lowres_image,
                                    scale.factors = fromJSON(scalefactors_json),
                                    tissue.positions = tissue_positions_list)
  
  spatialObj <- spatialObj[Cells(seurat_spatialObj)]
  DefaultAssay(spatialObj) <- 'Spatial'
  seurat_spatialObj[['slice1']] <- spatialObj
  
  colnames(seurat_spatialObj@meta.data)
  dev.off()
  dev.off()
  SpatialFeaturePlot(seurat_spatialObj, features = "nCount_Spatial")
```

**Comment by grimwoo** [comment]
Could the official Seurat team provide a much mature solution? Thanks in advance.

And anyone who encountered bugs please refers to [the original links](https://blog.csdn.net/qq_52813185/article/details/129713083#:~:text=%E4%BB%8EScanpy%E7%9A%84Anndata%E5%AF%B9%E8%B1%A1%E6%8F%90%E5%8F%96%E4%BF%A1%E6%81%AF%E5%B9%B6%E8%BD%AC%E6%88%90Seurat%E5%AF%B9%E8%B1%A1%EF%BC%88%E9%80%82%E7%94%A8%E4%BA%8E%E7%A9%BA%E9%97%B4%E7%BB%84%E4%B8%94%E6%B6%89%E5%8F%8Ah5%E6%96%87%E4%BB%B6%E8%AF%BB%E5%86%99%EF%BC%89%201%20Anndata%E5%AF%B9%E8%B1%A1%E8%BD%AC%E6%88%90Seurat%E5%AF%B9%E8%B1%A1,2%20h5%E6%96%87%E4%BB%B6%E8%AF%BB%E5%86%99%203%20%E7%A9%BA%E9%97%B4%E7%BB%84%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2) for help. I am only a fresh men in this field.

**Comment by grimwoo** [comment]
Scanpy plot:
![image](https://github.com/satijalab/seurat/assets/49429496/e028591b-1e31-4f91-b130-ac97a28743c8)

Transformed Seurat spatial object:
![image](https://github.com/satijalab/seurat/assets/49429496/495e5423-e2c5-40ae-878f-fdc8dd7c84e4)

**Comment by rsatija** [comment]
Apologies that we are unable to support spatial converters, so we would recommend just remaking the Seurat object from the original 10x data files - using our [visium vignette](https://satijalab.org/seurat/articles/spatial_vignette.html)

**Comment by dkcoxie** [comment]
I understand the recommendation to start with the original 10x files but this means that any custom binned spatial data generated by python based workflows that result in an AnnData object are then incompatible with Seurat. Is this still the recommendation for Seurat v5 regarding spatial data?
