### ISSUE TITLE
Bridge Integration MapQuery UMAP is from query, not reference

### ISSUE THREAD

**Issue by leeanapeters** [satijalab/seurat#8192]
Hi, I am really excited to try out bridge integration on a single cell RNAseq dataset, multiomic bridge, and a cytof dataset. 

There were ~34 overlapping proteins between the bridge and cytof, and I've followed the procedures from #5697

The issue that I am having is that running DimPlot after MapQuery shows the ref.umap reduction as the reduction from the query rather than the reference, and labels consequently do not look like they were transferred well.

Here is the result from: DimPlot(cytof, group.by="predicted.l1", reduction="ref.umap",label=TRUE)

<img width="827" alt="Screen Shot 2023-12-14 at 9 37 48 PM" src="https://github.com/satijalab/seurat/assets/63328808/f07b300e-0a89-46e7-b673-51765c3b7a7e">

You can see that this is not the same as the umap from my rna reference 

<img width="705" alt="Screen Shot 2023-12-14 at 9 25 13 PM" src="https://github.com/satijalab/seurat/assets/63328808/ca13a6d7-4b5e-49ae-b9a8-fe42545fcb02">

But actually the ref.umap that is transferred is from the bridge, and not the RNA somehow 

<img width="829" alt="Screen Shot 2023-12-14 at 9 33 56 PM" src="https://github.com/satijalab/seurat/assets/63328808/27d0dc9e-88c5-4a56-97f7-f0ccbcffd6d1">

I have run the code with ref.umap and UMAP both specified and this happens either way. Any help would be much appreciated as I do not understand where I am going wrong.

Thanks!

code: 

ref.extend <- PrepareBridgeReference(reference = rna,
                                     normalization.method = 'LogNormalize',
                                     bridge = HPA1_sub,
                                     reference.reduction = 'pca',
                                     reference.dims = dims.rna,
                                     bridge.query.assay = 'ADT',
                                     bridge.query.features = adt.feature)

anchor <- FindBridgeTransferAnchors(extended.reference = ref.extend,
                                    query = cytof,
                                    reduction = 'pcaproject',
                                    scale = scale,
                                    dims = dims.adt)

cytof <- MapQuery(anchorset = new_anchor,
                      reference = new_ref,
                      query = cytof,
                      refdata = list(l1=  'seurat_clusters'),
                      reduction.model = 'ref.umap'  )

**Comment by Gesmira** [comment]
Hi, 
Based on your third DimPlot, it seems that your RNA umap is not called 'ref.umap', but is 'rna.umap'. To use the rna umap, in `MapQuery` you should set the reduction.model to the name of the reduction that you set when you initially run UMAP on the RNA object.

**Comment by rsatija** [comment]
I'm closing this issue for the moment but feel free to re-open if this did not solve the issue for you
