### ISSUE TITLE
api.github.co

### ISSUE THREAD

**Issue by xiaxiaobai19870219** [satijalab/seurat#8193]
remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE)
wrong: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Failed to connect to api.github.com port 443 after 10008 ms: Timeout was reached

**Comment by saketkc** [comment]
These errors are intermittent generally (and not related to seurat). You can try again.
