### ISSUE TITLE
Issue with formatting in VlnPlot?

### ISSUE THREAD

**Issue by mukundvarma** [satijalab/seurat#82]
I had an issue with the formatting options size.x.use, size.y.use etc. in VlnPlot, where these parameters were not getting passed to the function. I believe this was because there were multiple theme() layers being added to the ggplot object, and it only displays the options called in the last one. I don't know if this is something peculiar to my setup or if others have this problem as well. I've fixed this, and added a no.legend option in my fork. I can make a pull request if you like.

Plot before fix (call: VlnPlot(object, "Actb", size.x.use = 16))
![image](https://user-images.githubusercontent.com/4998310/26887587-60512952-4b76-11e7-9701-d1e08b7833fb.png)

Plot after fix
![image](https://user-images.githubusercontent.com/4998310/26887540-3e824b3a-4b76-11e7-82ce-2fb79845aa21.png)

**Comment by andrewwbutler** [comment]
Yep, it's not just you. The formatting is a bit off for VlnPlot. We're working on finishing up a new release that includes a fix for this but we'd be happy to accept a pull request if you'd like the changes incorporated sooner.
