### ISSUE TITLE
Seurat normalization

### ISSUE THREAD

**Issue by asilvestris84** [satijalab/seurat#8200]
Dear curators of the Seurat package, 
I have a question (perhaps trivial) on which I would like to ask you for clarification: as you know, cellranger in the alignment and gene expression quantification steps "suggests" using a gtf annotation filtered by the one complete from gencode in such a way to contain only some categories of genes (for example, protein_coding, long non-coding and antisense RNA); I was therefore wondering whether considering only some of the transcripts actually sequenced could not create a bias at the level of normalization of the sequencing depth between the cells calculated by Seurat, and whether it would not therefore be preferable to use the non-filtered gtf, at least for this step. Thanks so much for the help. 
Alessandro

**Comment by mhkowalski** [comment]
Hello, 

Thanks for your question. I think the most important thing is that you are internally consistent (i.e. if you are comparing two samples, you use the same quantification steps for both). If you are comparing to other datasets with different quantification strategies, it would make sense to run normalization using the same set of genes (or re-quantify to ensure your quantifications are comparable). Hope this is helpful.
