### ISSUE TITLE
Trying to find mitochondrial data in converted seurat object

### ISSUE THREAD

**Issue by sky5198** [satijalab/seurat#8205]
I converted a Monocle3 CDS into a seurat object and trying to process the data using the seurat guided tutorial (https://satijalab.org/seurat/articles/pbmc3k_tutorial). I wanted to calculate the mitochondrial QC metrics but all of the values are 0. I have attached images of the uploaded matrix, gene annotations, and cell annotation files that were uploaded to GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5596828) used to create the Monocle3 cds. I tried to look to see if the pattern was different (if I needed to change the "^MT-") but I can't even find were the Mito. data is stored. I have attached screenshots of the files used to make the Monocle3 cds. 

[Github_help_12-19-23.pdf](https://github.com/satijalab/seurat/files/13718236/Github_help_12-19-23.pdf)

**Comment by saketkc** [comment]
It is possible tha tmitochondrial genes have been filtered out. You can check the output of

```r
grep(pattern="^MT-", x=rownames(object), value=T) # should be empty
```
