### ISSUE TITLE
question about FilterCells

### ISSUE THREAD

**Issue by mimidu** [satijalab/seurat#821]
Hi Seurat developers,

Thank you for the great documentation! It is so helpful and easy to follow =) 

I just have a question about the function of FilterCells. If I want to filter out cells with mito.frac>7% or nUMI <1000, what is the best way of doing that? It looks like subset.names is using "and" instead of "or". Is there a way to subtract my 'filterout' object from 'seuratraw'? Thanks!
```R
filterout <- FilterCells(object = seuratraw,
subset.names = c("nUMI", "percent.mito"),
low.thresholds = c(-Inf, 0.07),
high.thresholds = c(1000, Inf))

dim(filterout@meta.data)
#[1] 16  4
dim(seuratraw@meta.data)
#[1] 17447     4

seuratraw <- FilterCells(object = seuratraw, 
subset.names = c("nUMI", "percent.mito"),
low.thresholds = c(1000, -Inf),
high.thresholds = c(Inf, 0.07))

dim(seuratraw@meta.data)
#[1] 17255     4
```

**Comment by satijalab** [comment]
You can break this into two commands- first filtering on nUMI, then filtering on percent.mito. This will result in an OR-like operation
