### ISSUE TITLE
Include confounding variables for DESeq2?

### ISSUE THREAD

**Issue by noranekonobokkusu** [satijalab/seurat#8211]
Hi,

thank you for adding a [tutorial](https://satijalab.org/seurat/articles/de_vignette) on pseudobulked DE! I was wondering whether it is possible to somehow specify potential confounding variables in the model when using `FindMarkers` with `DESeq2` as described in the tutorial.

Thanks,
Ksenia

**Comment by longmanz** [comment]
Hi,
You can use "latent.vars = " to specify the column names of the confounding variables and DESeq2 will regress them out.

**Comment by longmanz** [comment]
Hi,
Sorry for the misinformation. In fact this is not supported for FindMarkers::DESeq2 at the moment. 

We will work on implementing this soon. In the meantime, could you try to extract the count matrix and meta-data from your seurat object, and then use DESeq2 package directly (https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html)?
 
 Alternatively, you can also run single-cell level analysis without pseudo-bulking and adjust for confounding with the glmGamPoi package (https://bioconductor.org/packages/release/bioc/html/glmGamPoi.html). This method is based on a similar negative binomial model as DESeq2 uses, but much more efficient that DESeq2 if you are using single-cell level data.

**Comment by noranekonobokkusu** [comment]
Thank you, I will give it a try!
