### ISSUE TITLE
Seurat fails to create `meta.features` slot when building from raw counts

### ISSUE THREAD

**Issue by Rohit-Satyam** [satijalab/seurat#8214]
Hi

I am trying to create seurat object from count matrix and metadata but for some reason the latest version of Seurat (v5) creates `meta.data` slot instead of `meta.features` slot. The code to reproduce this behaviour is given below

```r
library(Seurat)
library(SeuratData)
sobj <- CreateSeuratObject(counts = pbmc3k@assays$RNA@counts, project = "MCA")
## OR
sobj <- CreateSeuratObject(counts = as.sparse(pbmc3k@assays$RNA@counts), project = "MCA")
> sobj@assays$RNA@meta.data
data frame with 0 columns and 13714 rows
```

This should be the `meta.features` slot not `meta.data` (maybe typo error in your code). This small error is causing error in conversion of Seurat object to anndata (see [issue](https://github.com/cellgeni/sceasy/issues/82))

If there is a workaround kindly let me know!

**Comment by Gesmira** [comment]
Hi, 
This is expected. The Assay5 object replaced `meta.features` with `meta.data`,  so what you're seeing is correct. The `meta.data` slot at the assay level now contains feature-level metadata, while the `meta.data` slot at the object level contains cell-level metadata. 

Sceasy has yet to offer support for the v5 assay. 

For now, I would reccomend converting your assay to a v3 assay. This can be done like so:
`sobj[["RNA"]] <- as(sobj[["RNA"]], "Assay")`
At that point, conversion should run normally.

**Comment by samuel-marsh** [comment]
@Rohit-Satyam 

In case it helps simplify workflow I have added new function `as.anndata` to scCustomize that will work for either v3/4 or v5 objects without need to convert assay first.

https://samuel-marsh.github.io/scCustomize/articles/Object_Conversion.html#convert-seurat-or-liger-objects-to-anndata-objects

Best,
Sam

**Comment by JZL** [comment]
Thanks @samuel-marsh and all the Seurat contributors, you save the day again :-)
