### ISSUE TITLE
How to merge data after integration

### ISSUE THREAD

**Issue by linderss** [satijalab/seurat#8215]
Hi,

I have a dataset with samples originating from "tumor" and "normal" - when merging all samples normal cells and tumor cells form distinct clusters as it is biologically expected. However i noticed that it was necessary to integrate by "donor.id" due to high variability - when setting harmony group.by.vars="donor.id" the normal and tumor cells are also integrated and didn't form uniform clusters anymore. 
Therefore I wanted to subset the dataset into normal and tumor samples and only integrate the tumor samples and then merge with the normal cells - however when using merge(seurat_object) the harmony reduction gets lost. Is there somehow a way to merge data after partial integration was performed or any other workarounds for choosing different integration settings?

Thanks for your help!

**Comment by rsatija** [comment]
Unfortunately there is no way to partially integrate only a subset of samples in the way you suggest. This is true for the harmony method of integration but also all integration methods. 

You can integrate the tumor samples in a separate object, then perform clustering and annotation (based on the integrated dimensional reduction), and then after this you can merge all samples together. After you do this, you can retain the tumor sample clusters/cell type annotations, and use these as necessary
