### ISSUE TITLE
Displaying an empty row for non-detected /missing genes in DotPlot

### ISSUE THREAD

**Issue by Kenneth-new-user** [satijalab/seurat#8217]
I want to plot the same set of genes in different tissue across developmental stages but DotPlot will not display the gene if it was not detected in a stage. Is there a way to make it display an empty row for not detected genes instead of skipping that gene entirely? It is also important to know which genes are not expressed in a stage in what tissues.

**Comment by mhkowalski** [comment]
Hello, 

Thanks for your question. Are you trying to plot the same gene using multiple Seurat objects? If so, you make a new metadata variable for the developmental stage, merge these objects,  and then use DotPlot with the  ```split.by = "stage"``` argument. This approach should plot every gene for each stage and whatever variable you have set as the `idents`.
