### ISSUE TITLE
Error: Unable to coerce an object of class dgCMatrix to a Seurat object

### ISSUE THREAD

**Issue by Voltarikk** [satijalab/seurat#8218]
Dear all
I have a problem when I read the gene cell matrix that is an object of class dgCMatrix,I tried to convert it into Seurat object,but there appeared an error.
**Error: Unable to coerce an object of class dgCMatrix to a Seurat object**

Here is my code:
`library(Seurat)`
`sdata <- readRDS(file="D:/code/single_cell/github_code/harmony2019/data/figure3/exprs_30k.rds")`
`sdata.loom<- as.loom(x = sdata, filename ="D:/code/single_cell/github_code/harmony2019/data/figure3/data.loom",` verbose = `FALSE)`
`sdata.loom$close_all()`

thanks for answering!

**Comment by Gesmira** [comment]
Hi @Voltarikk , 
We are closing this issue now as we are no longer prioritizing support for loom conversion.

In Seurat v5, we include support for the [v5 assay class](https://satijalab.org/seurat/articles/seurat5_essential_commands.html), which can flexibly store data in a variety of formats (including disk-backed formats). We include multiple examples for disk-backed analysis using the [BPCells package from Ben Parks ](https://github.com/bnprks/BPCells).
