### ISSUE TITLE
Change Clusters Order - TSNEPlot

### ISSUE THREAD

**Issue by ogarmar3** [satijalab/seurat#822]
Hello,

TSNEplot generates a plot with the clusters in alphabetical/numerical order. Is it possible to change it to a custom order?

I've tried
```R
object@ident <- factor(object@ident, levels = new_order)
```
but that changes the cluster identities.

Thanks!
Marcos Otero

**Comment by satijalab** [comment]
This is the correct syntax - just be sure that the new_order contains the same elements as levels(object@ident) (though in a different order), you can also try adding ordered = T at the end of the command
