### ISSUE TITLE
Reference sample argument in IntegrateLayers 

### ISSUE THREAD

**Issue by leqi0001** [satijalab/seurat#8222]
Hi,
I tried to find similar questions but couldn't. I'm trying to integrate data using Seurat v5 and SCTransform following this code:
https://satijalab.org/seurat/articles/seurat5_integration

options(future.globals.maxSize = 3e+09)
obj <- SCTransform(obj)
obj <- RunPCA(obj, npcs = 30, verbose = F)
obj <- IntegrateLayers(
object = obj,
method = RPCAIntegration,
normalization.method = "SCT",
reference = 1:3
verbose = F
)

Error in FindIntegrationAnchors(object.list = object.list, anchor.features = features, : unused argument (referenece = 1:3)

However, I wasn't able to specify reference samples in IntegrateLayers, which seems to be specific to SCT. Looks like the layers returned by SCTransform contain the older structure instead of all the samples. Maybe it's wrong to specify reference samples using numerics this way?

If I understood it correctly, integrateLayers does not return corrected counts for the dataset, unlike integrateData in previous version. Is there such an option for v5? My dataset seems too big (230K cells with 15k filtered features) for the v4 integration method after specifying a few reference samples with rpca method. Providing more memory (from 500Gb to 1Tb) doesn't seem to make any difference.

Error in .cbind2Csp(x, y) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: IntegrateData ... cbind -> cbind2 -> cbind2 -> cbind2sparse -> .cbind2Csp
In addition: Warning messages:
1: `invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `inject()` instead.
This warning is displayed once every 8 hours. 
2: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 2.4 GiB
Execution halted

Thanks!
Le

**Comment by saketkc** [comment]
Hi @leqi0001,

I am unable to reproduce this, can you confirm if it was not a typo (`reference` and not `referenece`) and open a new issue if  you still cannot resolve it.

```r
obj <- LoadData("pbmcsca")
obj <- subset(obj, nFeature_RNA > 1000)
obj[["RNA"]] <- split(x = obj[["RNA"]], f = obj$Method)
obj <- SCTransform(obj)
obj <- PrepSCTFindMarkers(obj)
obj <- RunPCA(obj)

> obj.int <- IntegrateLayers(
+     object = obj, method = RPCAIntegration,
+     orig.reduction = "pca", new.reduction = "integrated.rpca",
+     verbose = FALSE, normalization.method = "SCT", reference = c(1,2,3)
+ )
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01s  
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=48s  
```
