### ISSUE TITLE
Integration of a Poisson corrected counts data and an uncorrected counts data

### ISSUE THREAD

**Issue by RM83** [satijalab/seurat#8227]
Hi Seurat team,
I have two count matrices (A and B) of the same phenotype but from two different studies. A is a Poisson-corrected counts data, and B is an uncorrected counts data. My question is, can I integrate the two datasets using Seurat's IntegateData workflow stated here (https://satijalab.org/seurat/reference/integratedata)? Or, do I need to get the uncorrected count matrix for data A first? 

Thank you.

**Comment by Gesmira** [comment]
Hi @RM83, 
Thanks for your issue and apologies for the delay in response. To use Seurat's integration workflow, we recommended starting with the raw (uncorrected) count data for both datasets. This allows the workflow to correct for technical differences between datasets during the integration process.
