### ISSUE TITLE
GSVA

### ISSUE THREAD

**Issue by paolo-kunderfranco** [satijalab/seurat#823]
Hi,
I would like to perform a Gsva analysis to check whether a b cell cluster is more activated than another.
Have you ever tried similar approaches?
What should I provide as input list of genes?
Any hint?
Many thanks
Paolo

**Comment by satijalab** [comment]
We do not support this internally in Seurat - but of course would encourage you to input our results into other external packages. To focus on pulling data from a single clusters - take a look at : https://satijalab.org/seurat/interaction_vignette.html
