### ISSUE TITLE
Is it possible to run RunAzimuth() for a dataset with 74 cells?

### ISSUE THREAD

**Issue by oigorlobo** [satijalab/seurat#8230]
When I ran Runazimuth() with my dataset containing 74 cells, I got the following error:

Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length

I have already decreased the 'k.weight' parameter, for example, but the same error message shows up. 

I appreciate any help!

**Comment by Gesmira** [comment]
Hi, 
You should decrease the `mapping.score.k` parameter to less than the number of cells you have. For example, if you have 74 cells, you could do: `mapping.score.k = 70`
