### ISSUE TITLE
error integrating seurat objects

### ISSUE THREAD

**Issue by si-purple** [satijalab/seurat#8237]
Hi there,
I'm new to R and trying to integrate 4 Seurat objects. Three contain more than one sample, while one only has one sample.
This is the code I'm using:

features <- SelectIntegrationFeatures(object.list = TAM.list)
TAM.list <- lapply(X = TAM.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})
TAM.anchors <- FindIntegrationAnchors(object.list = TAM.list, anchor.features = features, reduction = "rpca")
TAM.combined <- IntegrateData(anchorset = TAM.anchors)

In the last step, I get this error:
**Error in `object[[assay]]`:
! ‘SCT_RPCA’ not found in this Seurat object**

Two out of 4 Seurat objects have SCT_RPCA while the others don't. Is that what is causing the error? 

Thank you!

**Comment by dcollins15** [comment]
Is `SCT_RPCA` an assay or a dimensional reduction?

**Comment by si-purple** [comment]
Hi! It's an assay. I ran SCTransform in all datasets (some were normalized/scaled before) and that fixed the issue. However, one dataset had other assays (protein and others) and now I get a different error because the assays are missing in the other datasets. I moved on to IntegrateLayers (following Integrative analysis in Seurat v5) and was able to integrate the datasets. 
Thanks!

**Comment by dcollins15** [comment]
Glad you were able to get things working! Please don't hesitate to reach out if you need any other support 😄
