### ISSUE TITLE
SCTransformation

### ISSUE THREAD

**Issue by mainyanghr** [satijalab/seurat#8238]
Hopefully you are doing well. Recently I am stuck with SCTransform steps. My merged data is around 8G and working with 37RAM computer.

1: The sub-samples was SCTransformed before merging, after merging , I can not run the RunPCA directly with the following errors: 

MergeALL <- RunPCA(mergeALL, verbose = FALSE)

Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.

Then I run the following code, there is another errors. 

MergeALL <- FindVariableFeatures(MergeALL, selection.method = "vst", nfeatures = 2000, verbose = FALSE)

Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-

I am wondering how should I improve that?

2:  I am thinking to use another strategies to avoid the above errors.  I am thinking to re-run the SCTransform on the merged data. Since that it is not possible to run SCTransform directly for 8G data, I changed code slightly.

MergeALLv1 <- SCTransform(object=mergeALL, vst.flavor="v2", verbose=F,  conserve.memory=T)

Warning:  Will not return corrected UMI because residual type is not set to 'pearson'
Warning: Different cells and/or features from existing assay SCT

I am wondering whether this warming is serious and how should I improve that?

I appreciate for your kind help!

Best,

**Comment by saketkc** [comment]
Hi @mainyanghr, you can assing the variable features of the merged SCT assay by using `FindIintegrationFeatures` and then calculate residuals, followd by PCA:

```r
features <- FindIntegrationFeatures(object.list)
object.merged <- GetResiduals(object.merged, features = features)
VariableFeatures(object.merged) <- features
object.merged <- RunPCA(object.merged)
...

```
