### ISSUE TITLE
Using FindMarkers, no longer need to indicate assay = "RNA", or what is going on?

### ISSUE THREAD

**Issue by kmcandre88** [satijalab/seurat#8239]
Hello,

Tried searching for this issue and maybe it has been already answered so I apologize if it has. I am new to Seurat V5, previously, when looking for DEGs in a specific cluster I would use the following code

`DEGCluster1 <- FindMarkers(obj, "Cluster 1", assay = `"RNA"``

Now, when I attempt to use this same code since upgrading to Seurat V5 I receive the following error:

Warning: No layers found matching search pattern provided
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowSums': subscript out of bounds
In addition: Warning messages:
1: Layer ‘data’ is empty 
2: Layer ‘data’ is empty 

I have tried setting the default assay to RNA and it will only work on the SCT assay, could someone please fill me in on what is going on here, I know there are now layers in the assays but I was under the impression that DGE was best performed on the raw RNA counts.

Thank you for your time!!!

Kyle

**Comment by igrabski** [comment]
Hi Kyle, can you show the steps in creating and processing your object `obj` up the point where you are running `FindMarkers`, and what the output is when you print `obj`? It looks like you are missing the `data` layer for some reason in your object. By default, `FindMarkers` is done using Wilcox testing with the `data` layer, which represents normalized counts; we typically do not use Wilcox with raw counts due to differing coverage across cells.

**Comment by Zhong-qiu** [comment]
You can try normalizing this seurat object. You can see that the original seurat object only has count. After normalization is performed, the data of the RNA data layer will be generated, so that the next step can be performed.
`pbmc <- NormalizeData(pbmc,
                         normalization.method = "LogNormalize",
                         scale.factor = 10000)`

**Comment by Gesmira** [comment]
Hi, 
Due to the lack of response from the original poster, we are closing this issue for now. If you continue to run into the issue, please consider reposting with a reproducible example. Thank you!
