### ISSUE TITLE
Question about reference mapping/cell classification with sketch workflow 

### ISSUE THREAD

**Issue by jonathan-columbiau** [satijalab/seurat#8243]
Hi, thanks for maintaining Seurat! 

I'm trying to use a large cell atlas as a reference for cell type classification. Because I can't load the reference into memory, I was planning to use the sketching workflow to select a subset of 100,000 cells, then use FindTransferAnchors to transfer labels between the query dataset and this smaller sketched reference. Is this appropriate? 

In the vignettes they use sketching as a lower RAM way to project labels within an individual dataset, but I couldn't find whether it would be a good idea to use sketching before label transfer between datasets.

**Comment by Gesmira** [comment]
Hi @jonathan-columbiau, 
You can definitely do this. Essentially, you will just be creating a representative version of your original reference object. The results won't be exactly the same, but should be quite similar. 

[I also recommend using BPCells](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette
) as a way to deal with large objects in memory. This can let you work with the large object directly as a reference. You can check out the vignette here for more info on how to use BPCells. It will substantially lower the amount of memory the object takes.
