### ISSUE TITLE
I used RunMoransI of Seurat5 to get the Moran score for Xenium but the results are all 1

### ISSUE THREAD

**Issue by ddwzhou** [satijalab/seurat#8245]
According to [instraction](https://rdrr.io/cran/Seurat/man/RunMoransI.html),：
exp=data.frame(xenium.obj@assays$SCT@scale.data)【same with exp=data.frame(xenium.obj@assays$SCT@data)】
pos=GetTissueCoordinates(xenium.obj)
rownames(pos)=pos$cell
#in order to get res more quickly
tt1=exp[1:5000,1:100]
res_moran=RunMoransI(tt1,pos[colnames(tt1),c("x","y")])
then the res 
![image](https://github.com/satijalab/seurat/assets/57782907/f4b09fcb-d405-4185-9f82-52569dd2b791)

Did I use the RunMoransI function correctly? cause one can really not get much information from the instraction web. Does the res look like "normal"?

**Comment by diala-ar** [comment]
Hi. I am having the same problem! Any help is really appreciated.

**Comment by diala-ar** [comment]
I found the source of the issue. In my case, I was using data from meta.data so data was formatted as genes in columns and cells in rows, when I transposed it, I got observed values different than 1.
@ddwzhou, I am not sure what you are setting tt to. but I guess, if you set tt1=exp[1:5000,1:100], then RunMoransI should work. Hope this helps!

**Comment by ddwzhou** [comment]
Hello @diala-ar, I used a sub function [BinData] from https://github.com/cran/Seurat/blob/master/R/preprocessing.R. 
exp=data.frame(xenium.obj@assays$[SCT@scale.data](mailto:SCT@scale.data))
pos=GetTissueCoordinates(xenium.obj)
binned.data <- BinData(data=exp,pos=pos)
res_moran=RunMoransI(binned.data$data,binned.data$pos)
then the res gets more reasonable.

**Comment by Gesmira** [comment]
Hi @ddwzhou, 

@diala-ar, when you say you were using the metadata, were you specifically calling the meta.data slot from the Seurat Object or were you just using a transposed version of the data? If you can share your code, it would be useful for debugging @ddwzhou 's as well.  

@ddwzhou are you up to date with all packages? There was also recently an update to the `ape` package which MoransI uses, so I would recommend updating this package as well. 

Furthermore, is it possible that something is off with your data? Can you visualize a few genes?

**Comment by alikhuseynov** [comment]
Spatial stats in Seurat can take a while to compute, especially for large dataset of image-based ST (eg, > 300 genes and >200K cells). Like `FindSpatiallyVariableFeatures` would never finish up in my case.

@Gesmira what's the best way to use Seurat's spatial stats on large data?

To my experience, the fastest way was to use `moranfast::moranfast` C++ implementation, or [`Voyager`](https://pachterlab.github.io/voyager/articles/moran_landing.html) with much more spatial implementations. 

Here is the example with [`moranfast`](https://github.com/mcooper/moranfast), 2 technologies (Vizgen & Resolve Bioscience)

<details>
  <summary>moran's I run</summary>

```
obj
An object of class Seurat 
325 features across 278473 samples within 2 assays 
Active assay: SCT (161 features, 161 variable features)
 1 other assay present: VizRes
 7 spatial fields of view present

# moran's I -> compute per sample
# full data - moranfast::moranfast
start.time <- Sys.time()
pbapply::pboptions(type = "timer", style = 1, char = "=")
obj.moransI.fast <-
  pbapply::pblapply(obj %>% 
                      Images() %>% seq, 
                    function(im) { 
                      BiocParallel::bplapply(obj %>% rownames %>% seq, function(i) {
                        moranfast::moranfast(x = 
                                               # count matrix per sample
                                               obj %>% 
                                               GetAssayData(assay = "SCT", slot = "data") %>% 
                                               .[i, match(obj[[Images(obj)[im]]] %>% Cells(),
                                                          obj %>% Cells()) %>% na.omit()],
                                             c1 = obj[[Images(obj)[im]]][["centroids"]] %>% 
                                               GetTissueCoordinates() %>% pull(x),
                                             c2 = obj[[Images(obj)[im]]][["centroids"]] %>% 
                                               GetTissueCoordinates() %>% pull(y),
                                             alternative = "greater")
                      }, BPPARAM = BiocParallel::MulticoreParam(14, tasks = 20L,
                                                                force.GC = FALSE,
                                                                progressbar = TRUE)
                      ) %>%
                        # convert/make df data
                        data.table::rbindlist(.) %>%
                        mutate(samples = Images(obj)[im],
                               genes = obj %>% rownames(),
                               genes.group = 
                                 case_when(
                                   grepl(pattern = "Blank-|FP ", x = obj %>% rownames()) ~ "Background",
                                   !grepl(pattern = "Blank-|FP ", x = obj %>% rownames()) ~ "Target"))
                    }) %>%
  data.table::rbindlist() %>%
  arrange(observed %>% desc)

end.time <- Sys.time()
end.time - start.time # ca 25 mins

obj.moransI.fast %>% str
Classes ‘data.table’ and 'data.frame':	1127 obs. of  9 variables:
$ observed         : num  0.1059 0.092 0.0825 0.0815 0.077 ...
$ expected         : num  -0.0000128 -0.0000163 -0.0000501 -0.0000501 -0.0000128 ...
$ sd               : num  0.0000341 0.0000425 0.000107 0.000107 0.0000341 ...
$ p.value          : num  0 0 0 0 0 0 0 0 0 0 ...
$ samples          : chr  "qx1.Vizgen" "qx2.Vizgen" "qx1.w6a1.Resolve" "qx2.w6a1.Resolve" ...
$ genes            : chr  "NRXN3" "BOC" "TULP1" "CA10" ...
$ genes.group      : chr  "Target" "Target" "Target" "Target" ...

```

**Comment by Baboon61** [comment]
If someone come across this issue, my guess is that OP's has integrated different Xenium datasets. Thus the spatial location given has `GetTissueCoordinates(xenium.obj)` contains multiple tissues, therefore the `RunMoransI` for most of the genes do not make sense (p.value=1)
