### ISSUE TITLE
Adding assay object in v5 object

### ISSUE THREAD

**Issue by ruggerobelluomo** [satijalab/seurat#8246]
Hi all,

I need to add an assay from one merged object to another. Before using seurat v5 I was able to do this in the following manner: 

alldata.integrated[["unspliced"]] <- CreateAssayObject(data = renamed.assay@assays$unspliced@data)

but now with the new layers of Seurat v5 I cannot find anymore the count data in the object. Do you know where I can find it?

These are my 2 objects:

An object of class Seurat 
34285 features across 117193 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 2 layers present: data, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap

An object of class Seurat 
108896 features across 117193 samples within 2 assays 
Active assay: spliced (54448 features, 0 variable features)
 16 layers present: counts.B2FYH, counts.B3MOC, counts.B3MYH, counts.B4FYH, counts.B5MOC, counts.B5MOH, counts.B5MYC, counts.B5MYH, counts.B6FOC, counts.B6FOH, counts.B6FYC, counts.B6FYC_2, counts.B7MOC, counts.B7MOH, counts.B7MYC, counts.B8FOH
 1 other assay present: unspliced

Thanks for the help!

**Comment by saketkc** [comment]
Hi @ruggerobelluomo,  You are adding the counts in the data layer, which can be accessed using:

```r
GetAssayData(object = obj, assay = "unspliced", layer="data")
```

If you want to add a new layer to your existing assay, you can do:

```r
obj[["spliced"]]$counts.unspliced <-  renamed.assay@assays$unspliced@counts
```
