### ISSUE TITLE
Seurat not converting to SingleCellExperiment

### ISSUE THREAD

**Issue by lichenlady94** [satijalab/seurat#8248]
Hi!

I've been trying to convert my Seurat object to SingleCell but keep getting the following
> sce<- as.SingleCellExperiment(samples.merge)
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Run `rlang::last_trace()` to see where the error occurred.
I was wondering if this is an error on my end or a known kink in Seurat?

**Comment by saketkc** [comment]
Hi @lichenlady94, this is currently not supported with v5. You can convert your assays to v3 assays and try:

```r
object[["RNA"]] <- as(object[["RNA"]], Class="Assay")
object <- as.SingleCellExperiment(object)
```

**Comment by amarinderthind** [comment]
> Hi @lichenlady94, this is currently not supported with v5. You can convert your assays to v3 assays and try:
> 
> ```r
> object[["RNA"]] <- as(object[["RNA"]], Class="Assay")
> object <- as.SingleCellExperiment(object)
> ```

Is this supposed to work with the "SCT" assay as well?

**Comment by amarinderthind** [comment]
> > Hi @lichenlady94, this is currently not supported with v5. You can convert your assays to v3 assays and try:
> > ```r
> > object[["RNA"]] <- as(object[["RNA"]], Class="Assay")
> > object <- as.SingleCellExperiment(object)
> > ```
> 
> Is this supposed to work with the "SCT" assay as well?


I am getting the following error and wondering what could be the right approach to convert the integrated_seurat Object to the SingleCellExperiment object. 

> seurat_integrated1[["SCT"]] <- as(seurat_integrated1[["SCT"]], Class="Assay")
> seurat_integrated1 <- as.SingleCellExperiment(seurat_integrated1)
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Backtrace:

**Comment by bixBeta** [comment]
> > > Hi @lichenlady94, this is currently not supported with v5. You can convert your assays to v3 assays and try:
> > > ```r
> > > object[["RNA"]] <- as(object[["RNA"]], Class="Assay")
> > > object <- as.SingleCellExperiment(object)
> > > ```
> > 
> > 
> > Is this supposed to work with the "SCT" assay as well?
> 
> I am getting the following error and wondering what could be the right approach to convert the integrated_seurat Object to the SingleCellExperiment object.
> 
> > seurat_integrated1[["SCT"]] <- as(seurat_integrated1[["SCT"]], Class="Assay")
> > seurat_integrated1 <- as.SingleCellExperiment(seurat_integrated1)
> > Error in `GetAssayData()`:
> > ! GetAssayData doesn't work for multiple layers in v5 assay.
> > Backtrace:

You will need to join all of your layers first, before switching Assay5 to Assay Class.

**Comment by ACMGlueck** [comment]
Hi @saketkc : is it planned to support the conversion of Assay5 data to SingleCellExperiment objects in future versions of the Seurat package?

**Comment by Vik2025** [comment]
`object %<>% JoinLayers() %>% as.SingleCellExperiment()` works for me.

**Comment by jcorn427** [comment]
@saketkc any word on if this functionality will be supported? I'd like to use SingleR with a v5 Seurat object and I'm getting the same error as @ACMGlueck when trying to convert from Assay5 to Assay3. Any help would be much appreciated.

**Comment by KidElectric** [comment]
I was having some trouble with this as well in v5 Seurat object and I found sce <- GetAssayData(object = object, assay = "Spatial.008um") to work for me to use SingleR (using visium data in this case).

**Comment by shirleyyy07** [comment]
> > > Hi [@lichenlady94](https://github.com/lichenlady94), this is currently not supported with v5. You can convert your assays to v3 assays and try:
> > > object[["RNA"]] <- as(object[["RNA"]], Class="Assay")
> > > object <- as.SingleCellExperiment(object)
> > 
> > 
> > Is this supposed to work with the "SCT" assay as well?
> 
> I am getting the following error and wondering what could be the right approach to convert the integrated_seurat Object to the SingleCellExperiment object.
> 
> > seurat_integrated1[["SCT"]] <- as(seurat_integrated1[["SCT"]], Class="Assay")
> > seurat_integrated1 <- as.SingleCellExperiment(seurat_integrated1)
> > Error in `GetAssayData()`:
> > ! GetAssayData doesn't work for multiple layers in v5 assay.
> > Backtrace:

as.SingleCellExperiment(seurat.object, assay = "SCT") works for me
