### ISSUE TITLE
How is average expression done in DotPlot?

### ISSUE THREAD

**Issue by MiTPenguin** [satijalab/seurat#825]
I have this dataset that's been normalized using NormalizeData (which is just log normalization). Things seems to plot out fine using VlnPlot, so the y axis should just be log(normalized data). However, I find that when I plot the same data using DotPlot, the avg expression scale doesn't seem to match with what's plotted on the violin plots.

Going through the vignettes, I see the same thing (https://satijalab.org/seurat/visualization_vignette.html#five-visualizations-of-marker-gene-expression). Looking at just the megakaryocytes, the expression of PF4 is > 4 (on the violin log scale). But looking at the dot plot, the scale only goes up to maybe 3 (again, I assume on the normalized log scale?).

Am I missing something here? The documentation of AverageExpression is also not clear about what it does with normalized data.

**Comment by DanSchnell** [comment]
I had a little trouble trying to match calculations as well.  Below is what I determined--maybe this will help. 
# Normalization method "LogNormalize" normalizes the gene 
# expression measurements for each cell by the total expression in the cell, 
# multiplies this by a scale factor (10,000 by default), and 
# log-transforms the result  (ln(1+n/N*10**4)),  adding 1 to prevent ln(0).

**Comment by DanSchnell** [comment]
Big bold not intended--didn't realize the R comment character # would do that.
