### ISSUE TITLE
igraph 2.0.0 update

### ISSUE THREAD

**Issue by krlmlr** [satijalab/seurat#8256]
We are planning a large update of the igraph R package, but we don't have a good way to check if Seurat is still compatible with the updated package. Of the 800+ packages that use igraph, Seurat is one of those that occasionally can't be checked on our infrastructure.

What's a good way to ensure that we don't accidentally break Seurat?

CC @szhorvat.

**Comment by dcollins15** [comment]
Hi @krlmlr thanks for reaching out — if you can point me to some way to install the updated packages, I'd be more than happy to test `Seurat` against the updates and coordinate any changes that may be required. Just let me know 🙂
