### ISSUE TITLE
using Seurat on bulk data?

### ISSUE THREAD

**Issue by rpeys** [satijalab/seurat#826]
Is it ever ok to use Seurat for clustering bulk samples. I am looking at FPKM data from ~750 bulk RNA-seq samples. As suggested for FPKM data, I manually input log transformed data to the `@data` slot [`cd138_bm@data <- log(cd138_bm@raw.data + 1)`] and skip the `NormalizeData() `function. I then use functions `FindVariableGenes`, `ScaleData`, `RunPCA`, `FindClusters`, `RunTSNE`, `FindAllMarkers` in their usual ways to find clusters & cluster markers. My clustering results are quite reasonable, and reflect published work clustering similar samples.

What are the potential pitfalls of using these Seurat functions on bulk data? In `FindAllMarkers`, would you recommend I use the "negbinom" test? (currently using wilcox) Any other arguments you would recommend changing from the default? The FPKM data was generated using CuffLinks. Thank you!

**Comment by satijalab** [comment]
Hi Rebecca,

You can certainly use Seurat for bulk rna-seq analysis. For DE, I would suggest using established tools like DESeq2, either within or external to the package. The normalization procedure you describe is also reasonable.

best,
Rahul
