### ISSUE TITLE
Best practice for removing doublets using Hash antibody staining?

### ISSUE THREAD

**Issue by k4terina** [satijalab/seurat#8261]
Hi!

I have a CITE-seq dataset from cells that were stained with some ADT mastermix, then split into 6 parts, then stained with Hash antibodies (n=6) and then pooled again before generation of 10X data. I created a seurat object with three assays: RNA, ADT and one assay holding the Hash-ADT counts :

> seurat_objects[["LO12_Healthy"]]@assays[["HTO"]]@counts@Dimnames[[1]]
[1] "Hash1-ADT" "Hash2-ADT" "Hash3-ADT" "Hash4-ADT" "Hash5-ADT" "Hash6-ADT"

Can any one recommend the best practice for removing doublets using these counts? Thank you!

k4terina

**Comment by samuel-marsh** [comment]
Hi @k4terina,

Not member of dev team but hopefully can be helpful.  You can refer to the Seurat team's vignette for demultiplexing here: https://satijalab.org/seurat/articles/hashing_vignette.

Best,
Sam
