### ISSUE TITLE
Problem when running GeneActivity() function

### ISSUE THREAD

**Issue by Mariateresa91** [satijalab/seurat#8263]
Dear all,
I am trying to create a gene activity matrix of a scATAC-seq dataset, but I am always getting this error:

![image](https://github.com/satijalab/seurat/assets/155670828/f5b9dd12-98c8-4d5d-a2f1-c0d0f2355d63)

Now, I am new to Seurat, and my input is a .h5 file containing both scRNA-seq and scATAC-seq data, but I have done the analysis also taking only the ATAC-seq dataset. I don't know what I am doing wrong honestly. Here is the code I have used:

counts <- Read10X_h5("filtered_feature_bc_matrix.h5")
fragpath <- "atac_fragments.tsv"
### create a Seurat object containing the RNA data
pbmc <- CreateSeuratObject(counts = counts$`Gene Expression`,assay = "RNA")
### create ATAC assay and add it to the object
pbmc[["ATAC"]] <- CreateChromatinAssay(counts = counts$Peaks,sep = c(":", "-"),fragments = fragpath, annotation = annotation_ce11)
genome(pbmc[["ATAC"]]) = 'ce11'
### analyze gene expression data
DefaultAssay(pbmc) <- "RNA"
pbmc <- SCTransform(pbmc)
pbmc <- RunPCA(pbmc)
### analyze ATAC-seq data
pbmc <- FindTopFeatures(pbmc, min.cutoff = 5)
pbmc <- RunTFIDF(pbmc)
pbmc <- RunSVD(pbmc)
### joint UMAP
pbmc <- FindMultiModalNeighbors(object = pbmc,reduction.list = list("pca", "lsi"), dims.list = list(1:50, 2:40),modality.weight.name = "RNA.weight",verbose = TRUE)
pbmc <- RunUMAP(object = pbmc,nn.name = "weighted.nn",verbose = TRUE)
pbmc = RunTSNE(object = pbmc,nn.name = "weighted.nn",tsne.method = "Rtsne")
pbmc = FindNeighbors(object = pbmc, reduction = 'lsi',dims = 2:30)
pbmc = FindClusters(object = pbmc, verbose = FALSE, algorithm = 3)
a = GeneActivity(pbmc, assay = "ATAC")

Here is my annotation:

![image](https://github.com/satijalab/seurat/assets/155670828/9958c67c-e82a-4f97-a28c-7f4832f7d1e5)

Here are the fragments:

![image](https://github.com/satijalab/seurat/assets/155670828/fc26dc33-2187-4eeb-840d-1e47b7515ba2)

Here is the GRanges object:

![image](https://github.com/satijalab/seurat/assets/155670828/ff3a2b8b-1ed9-42aa-b077-c318e1563eab)

and the error is present also when adding the seqlengths to pbmc[["ATAC"]].

Any help would be appreciated!

Mariateresa

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  `GeneActivity` is actually a part of Signac package and not Seurat.  For help with the errors you are getting I recommend post to Signac repo (https://github.com/stuart-lab/signac).

Best,
Sam
