### ISSUE TITLE
Seurat5 problem installation

### ISSUE THREAD

**Issue by Mila-Suerat5MeDaDolorDeCabeza** [satijalab/seurat#8264]
> remotes::install_github("satijalab/seurat", "seurat5", quiet = FALSE)
Downloading GitHub repo satijalab/seurat@seurat5
Installing 1 packages: Matrix
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/Matrix_1.6-4.zip'
Content type 'application/zip' length 4561742 bytes (4.4 MB)
downloaded 4.4 MB

package ‘Matrix’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Matrix’
Warning: restored ‘Matrix’

The downloaded binary packages are in
	C:\Users\sanchm63\AppData\Local\Temp\RtmpGqC4Ss\downloaded_packages
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\sanchm63\AppData\Local\Temp\RtmpGqC4Ss\remotes63707d2d1c90\satijalab-seurat-a4075e7/DESCRIPTION' ...
─  preparing 'Seurat': (405ms)
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  installing the package to process help pages (352ms)
         -----------------------------------
   ERROR: dependency 'Matrix' is not available for package 'Seurat'
─  removing 'C:/Users/sanchm63/AppData/Local/Temp/RtmpKWX62P/Rinst6b381f88f85/Seurat'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'Seurat' from GitHub:
  ! System command 'Rcmd.exe' failed
In addition: Warning message:
In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.3.1\library\00LOCK\Matrix\libs\x64\Matrix.dll to C:\Program Files\R\R-4.3.1\library\Matrix\libs\x64\Matrix.dll: Permission denied

**Comment by Mila-Suerat5MeDaDolorDeCabeza** [comment]
> install.packages('Seurat')
also installing the dependency ‘Matrix’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/Matrix_1.6-4.zip'
Content type 'application/zip' length 4561742 bytes (4.4 MB)
downloaded 4.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/Seurat_5.0.1.zip'
Content type 'application/zip' length 2901241 bytes (2.8 MB)
downloaded 2.8 MB

package ‘Matrix’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘Matrix’
Warning in install.packages :
  problem copying C:\Program Files\R\R-4.3.1\library\00LOCK\Matrix\libs\x64\Matrix.dll to C:\Program Files\R\R-4.3.1\library\Matrix\libs\x64\Matrix.dll: Permission denied
Warning in install.packages :
  restored ‘Matrix’
package ‘Seurat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\sanchm63\AppData\Local\Temp\RtmpGqC4Ss\downloaded_packages

**Comment by mhkowalski** [comment]
Hello, 

Hi- could you please try restarting R? 

If this doesn't work, the problem looks like it's with your inability to upgrade the Matrix package. I would try uninstalling your current version of the Matrix package using the utils function `remove.packages`. It also seems that you may not have access to the place where Matrix is installed, so I would check to make sure that you can access this directory as well.  

Hope this is helpful, and please let us know if you continue to have issues.
