### ISSUE TITLE
Conda update to latest version & extra packages bundle.

### ISSUE THREAD

**Issue by jmgs7** [satijalab/seurat#8266]
Dear ones, 

First, congratulations and thank you this amazing piece of scientific software.

We are really loving the new multiomics integration capabilities of the new V5, but we would really love to be able to install it with conda (currently in V4, 4.4 I think). We know that V5 has published just a few months ago, but we would like to ask if there are plans to update de Conda package.

Also, when working from a Conda environment to work with R packages (especially useful for a data science lab, since it allows easy and reproducible configuration of multiple servers/workstations), it's very complicated to install packages from source using remote or devtools (mainly because of the absence of the R compiler tools in the Conda and the trickery to get them and make them work in Conda environments). That's why we think that the creation of an additional "official" Conda package containing all pre-compiled and ready-to-use extra packages for Seurat (BPCells, presto, glmGamPoi, seurat-data, seurat-wrappers, azimuth...) or some sort of solution would be very interesting and widely appreciated from your user's community. 

I hope you find these suggestions useful, although we understand they might be time-comsuming and out of your scope.

Please, keep the great work you are doing.

Thank you very much for your attention, best regards.

**Comment by zskylarli** [comment]
Hi - thank you for your kind words and the suggestion! We definitely recognize that this would be beneficial for the community and will consider implementations as soon as possible. For now, we hope that the R-universe installation options listed on our Seurat installation page are useful. Please keep up posted on any immediate issues that arise from not having a Conda environment. Thanks again!
