### ISSUE TITLE
It seems that using the offcial code cannot install correct version

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#8270]
Hi, since v5 has many bugs, I plan to downgrade my Seurat to v4. However, using this code cannot install Seurat v4:

![image](https://github.com/satijalab/seurat/assets/43333475/2f0346dc-96ec-4175-a03b-32eba769c340)

This still gives me V5.0.1. Could you please fix it? Thanks.

**Comment by zskylarli** [comment]
Thank you for reporting this! We will have a fix and follow up soon. In the meantime, feel free to report any bugs that are interfering with your analysis, since we hope that more users can adopt v5 moving forward.

**Comment by Gesmira** [comment]
Hi, 
This should now be fixed and Seurat v4 can be installed with the following code from r-universe: 
```
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_version("SeuratObject", "4.1.4", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
remotes::install_version("Seurat", "4.4.0", repos = c("https://satijalab.r-universe.dev", getOption("repos")))
```
Thanks for your patience!
