### ISSUE TITLE
Seurat v5: AverageExpression()  Error in data.use.i == Inf :    comparison (==) is possible only for atomic and list types

### ISSUE THREAD

**Issue by alasaa** [satijalab/seurat#8272]
Hello, 

I got this error when I am using AverageExpression in Seurat v5:

cluster.averages <- AverageExpression(obj) 
Error in data.use.i == Inf : 
  comparison (==) is possible only for atomic and list types

Why did seurat say there was infinite in my data? But if so, I shouldn't be able to run FindConservedMarkers. However, I can run FindConservedMarkers. Is infinite caused by CCA? How can I avoid this error?

Could anyone help me?  I really need to use the function “AverageExpression”

Here are the functions that I used:

CreateSeuratObject()-> merge()-> NormalizeData()-> FindVariableFeatures()-> ScaleData()-> RunPCA() -> RunUMAP() -> FindNeighbors() -> FindClusters()-> IntegrateLayers(method=CCAIntegration)-> RunUMAP() -> FindNeighbors() -> FindClusters() -> subset()-> JoinLayers()-> RenameIdents()-> AverageExpression()

Thank you very much!

**Comment by mariafiruleva** [comment]
Hi, I've just encountered the same issue. It seems that the comparison `mat == Inf` / `is.infinite(mat)` could not handle matrices generated by the `BPCells` package.

https://github.com/satijalab/seurat/blob/41d19a8a55350bff444340d6ae7d7e03417d4173/R/utilities.R#L1343

One trick is to select the genes you are interested in (e.g., group marker genes by cluster => select top-10 genes), and create a temporary object with only those genes:

```
get_mtx_with_averaged_expr <- function(object, target_genes) {
  tmp_object <- subset(object, features = target_genes)
  tmp_object[["RNA"]]$data <- as(object = tmp_object[["RNA"]]$data, Class = "dgCMatrix")
  AverageExpression(tmp_object, assay = "RNA", layer = "data", features = target_genes)
}
```

**Comment by Gesmira** [comment]
Hi, 
As of Seurat v5, we recommend using `AggregateExpression` to perform pseudo-bulk analysis. You will not run into this error if you use `AggregateExpression`.
