### ISSUE TITLE
Differences between Seurat v4 and v5 Integration

### ISSUE THREAD

**Issue by MartaBenegas** [satijalab/seurat#8274]
Hi Seurat Team! 

While I was revisiting my code to adapt it to Seurat v5, I spotted some differences in the integration pipeline between v4 and v5. Thus, I would really appreciate it if you could solve the doubts that I've found!

My code is based on the integration vignettes:
- Version 4: https://satijalab.org/seurat/archive/v4.3/integration_introduction
- Version 5: https://satijalab.org/seurat/articles/integration_introduction

1. In **v4**, the **PCA** is run **after** the integration, while in **v5** it is performed **before** the integration. Why so? Both methods use CCA, right? (in the example vignettes)
2. Why the integration was stored in an **assay** in **v4** and now in a **reduction** in **v5**? Again, using the CCA in both versions. The information is quite different.
```r
> s.old.combined
An object of class Seurat 
32748 features across 3619 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 layer present: data
 1 other assay present: RNA

> s.old.combined@assays$integrated@data[10:13,10:13]
4 x 4 sparse Matrix of class "dgCMatrix"
                   dog10-AAACGGGCATTGGCGC dog10-AAACGGGGTAGCTCCG dog10-AAACGGGTCACAGTAC dog10-AAACGGGTCTCTGAGA
ENSCAFG00845006666               .                      2.853201               .                      .       
ENSCAFG00845014717               .                      1.112811               3.845169               3.560857
ENSCAFG00845031003               .                      .                      .                      .       
ENSCAFG00845013518               1.579408               1.964129               .                      .  

> s.new
An object of class Seurat 
30748 features across 3619 samples within 1 assay 
Active assay: RNA (30748 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 2 dimensional reductions calculated: pca, integrated.cca

> s.new@reductions$integrated.cca@cell.embeddings[1:3,1:3]
                       integratedcca_1 integratedcca_2 integratedcca_3
dog10-AAACCTGCAGCTCGAC       -9.254898       0.7129071     -1.16322507
dog10-AAACCTGGTGACCAAG      -12.266157      -4.1952528     -0.02150497
dog10-AAACCTGTCTCGGACG      -10.009954      -2.9386433     -0.15979543
```

Thanks in advance!

**Comment by zskylarli** [comment]
Hi - thank you for your questions. Both methods do use CCA to identify anchors for integration; however, as noted in our vignette, the v5 integration procedure has changed to return the corrected embeddings instead of an assay, which captures the shared sources of variation and allows you to directly perform downstream analysis. Therefore, in the v5 vignette, we are running PCA first so to then perform correction on that reduction. When using CCA integration in v4, PCA is run on the integrated assay to facilitate visualization via UMAP, and does not relate to the dimensionality reduction process for anchor identification. Please feel free to reopen this issue if you have follow-up questions!

**Comment by tim-meese** [comment]
Hello Seurat Team

I want to ask a follow up question about this topic. In Seurat V4, I would call `RunPCA` after the integration and afterwards determine the dimensionality of the dataset by investigating the elbowplot. The elbowplot gave me the number of principal components I want to retain. I used this information in `RunUMAP`, `FindNeighbors` and `FindClusters`. 

In Seurat V5 this approach does not work anymore for the reason highlighted here. Is there a way to replicate this workflow in Seurat V5? 
My first idea was creating the elbowplot after calling `RunPCA` and providing the number principal components I want to retain (nPC) to the `IntegrateLayers(, dims=1:nPCs)`. But I am not sure if this correct. 
Or is it not needed to "optimize" the number if principal components here? 

Thanks in advance and appreciating the input.

With kind regards
Tim

**Comment by frenkiboy** [comment]
Could you please tell us why you decided to drop the integrated matrix, and report the PCA? is there a way of getting the integrated matrix?

**Comment by tim-meese** [comment]
Adding to the question of @frenkiboy , is there a way to reproduce the results from CCA integration in V4 in V5? What is the recommended way to select an appropriate number of dimensions in Seurat V5?
