### ISSUE TITLE
Obtain raw gene expression of Seurat object for one gene

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8281]
Good afternoon,

I would like to filter my Seurat object for one particular gene and extract the raw gene expression for this gene. 
Can anyone advise me on how to do so?

I am aware that I can retrieve the raw counts via

`GetAssayData(object = pbmc, assay = "RNA", slot = "counts")` , however I struggle how to filter on a specific gene.

Thank you for any hints!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So yes you can pull all of the raw counts with `GetAssayData` as you described.  This returns dgCMatrix which can be filtered as you would any dgCMatrix in R (I would direct you to google and StackExchange for finding more info that you need there).

However, there is easier way in Seurat specifically using `FetchData`.
```
ACTB_raw_counts <- FetchData(object = obj, vars = "ACTB", layer = "counts")

ACTB_norm_exp <- FetchData(object = obj, vars = "ACTB", layer = "data")
```

Best,
Sam

**Comment by LeaLe88** [comment]
Dear Sam, 

Thank you so much for your reply.

The function FetchData is great, its exactly what I needed.

Best Regards,
Lea
