### ISSUE TITLE
MapQuery transferdata.args parameter is disregarded

### ISSUE THREAD

**Issue by AndreaRP** [satijalab/seurat#8285]
I am trying to transfer a small batch of spatial transcriptomics "cell" counts onto a bigger dataset. The number of cells is very low, so I assume I have to tune the k.weight parameter in _TransferData_ when using _MapQuery_, which I have done by using the _transferdata.args_ parameter as suggested in issue [4117](https://github.com/satijalab/seurat/issues/4117#issuecomment-1662946520). However when I run the _MapQuery_ with  _transferdata.args = F_, I'm still getting "k.weight (100) is set larger than the number of cells in the query object (31). Please choose a smaller k.weight.". I've also tried specifying different k.weights (lower than the number of query cells) but it always throws the same error, stating that the k.weight is 100.
Below is a reproducible snippet with the issue. The data I've used is the pbmc Seurat tutorial [dataset](https://cf.10xgenomics.com/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz).

```
pbmc.data <- Read10X(data.dir = "~/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

set <- sample(colnames(pbmc), 31)
pbmc.query <- subset(x = pbmc, cells = set)
pbmc.query <- NormalizeData(object = pbmc.query)
pbmc.query <- FindVariableFeatures(object = pbmc.query, selection.method = "vst", nfeatures = 2000)
pbmc.query <- ScaleData(object = pbmc.query)

pbmc.ref <- subset(x = pbmc, cells = setdiff(colnames(pbmc), set))
pbmc.ref <- NormalizeData(object = pbmc.ref)
pbmc.ref <- FindVariableFeatures(object = pbmc.ref, selection.method = "vst", nfeatures = 2000)
pbmc.ref <- ScaleData(object = pbmc.ref)
pbmc.ref <- RunPCA(pbmc.ref, features = VariableFeatures(object = pbmc.ref))


anchors <- FindTransferAnchors(reference = pbmc.ref
                              , query = pbmc.query
                              , k.filter = NA # This was specified in issue #4117 reply
                              , reference.reduction = "pca"
                              , dims = 1:30
                              )
results <- MapQuery(anchorset = anchors, reference = pbmc.ref, query = pbmc.query
                  , reference.reduction = "pca", reduction.model = "umap"
                  , transferdata.args = list(k.weight = FALSE)
                  )
```

**Comment by Gesmira** [comment]
Hi, 
I can't reproduce this error when `transferdata.args` is set as in your code. We have fixed the issue in a previous release. Please feel free to reopen if the error persists. Thanks!
