### ISSUE TITLE
Error when subset RNA assay stored on-disk

### ISSUE THREAD

**Issue by nimanouri-nn** [satijalab/seurat#8287]
Hello Seurat, 

I have a Seurat object (sobj) built using BPCells (joined-layers of 4 samples), and I am attempting to subset it by 10,000 cell IDs (cell_ids). My end-goal is to convert the subset RNA assay, stored on-disk, into an in-memory representation (dgCMatrix) according to the Seurat vignette. However, I encountered the error below. I suspect the error stems from a mismatch in the dimensions of the on-disk matrix. Any idea why this is happening?

`
> DefaultAssay(sobj)
[1] "RNA"

> sobj
An object of class Seurat 
45228 features across 30600 samples within 2 assays 
Active assay: RNA (22614 features, 2000 variable features)
 2 layers present: counts, data
 1 other assay present: sketch
 5 dimensional reductions calculated: pca.sketch, harmony.sketch, umap.sketch, harmony, umap

> dim(sobj)
[1] 22614 30600

> sobj_sub <- subset(sobj, cell = cell_ids)

> sobj_sub
An object of class Seurat 
45228 features across 10000 samples within 2 assays 
Active assay: RNA (22614 features, 2000 variable features)
 2 layers present: counts, data
 1 other assay present: sketch
 5 dimensional reductions calculated: pca.sketch, harmony.sketch, umap.sketch, harmony, umap

> dim(sobj_sub)
[1] 22614 10000

> dim(sobj_sub[["RNA"]]$counts)
[1] 22614 10000

> dim(sobj_sub[["RNA"]]$counts@matrix)
[1] 22614 30600

> lengths(sobj_sub[["RNA"]]$counts@dimnames)
[1] 22614 10000

> as(sobj_sub[["RNA"]]$counts, Class="dgCMatrix")
Error: RenameDims: Cow names must be length 0 or equal to number of input cols
`

**Comment by nimanouri-nn** [comment]
I repeated this experiment with subsetting in a different format of `subset` and a different variable `sample_id`, but again the same error:

`
> DefaultAssay(sobj)
[1] "RNA"

> sobj
An object of class Seurat 
45228 features across 30600 samples within 2 assays 
Active assay: RNA (22614 features, 2000 variable features)
 2 layers present: counts, data
 1 other assay present: sketch
 5 dimensional reductions calculated: pca.sketch, harmony.sketch, umap.sketch, harmony, umap

> dim(sobj)
[1] 22614 30600

> sobj_sub <- subset(sobj, subset = sample_id %in% c("S1"))

> sobj_sub
An object of class Seurat 
45228 features across 7439 samples within 2 assays 
Active assay: RNA (22614 features, 2000 variable features)
 2 layers present: counts, data
 1 other assay present: sketch
 5 dimensional reductions calculated: pca.sketch, harmony.sketch, umap.sketch, harmony, umap

> dim(sobj_sub)
[1] 22614  7439

> dim(sobj_sub[["RNA"]]$counts)
[1] 22614  7439

> dim(sobj_sub[["RNA"]]$counts@matrix)
[1] 22614 30600

> lengths(sobj_sub[["RNA"]]$counts@dimnames)
[1] 22614  7439

> as(sobj_sub[["RNA"]]$counts, Class="dgCMatrix")
Error: RenameDims: Cow names must be length 0 or equal to number of input cols
`

**Comment by nimanouri-nn** [comment]
if I use `seurat_clusters` variable for subsetting, all the sudden everything works fine, strange... any idea?

`
> DefaultAssay(sobj)
[1] "RNA"

> sobj
An object of class Seurat 
45228 features across 30600 samples within 2 assays 
Active assay: RNA (22614 features, 2000 variable features)
 2 layers present: counts, data
 1 other assay present: sketch
 5 dimensional reductions calculated: pca.sketch, harmony.sketch, umap.sketch, harmony, umap

> dim(sobj)
[1] 22614 30600

> sobj_sub <- subset(sobj, subset = seurat_clusters %in% c(2))

> sobj_sub
An object of class Seurat 
45228 features across 3332 samples within 2 assays 
Active assay: RNA (22614 features, 2000 variable features)
 2 layers present: counts, data
 1 other assay present: sketch
 5 dimensional reductions calculated: pca.sketch, harmony.sketch, umap.sketch, harmony, umap

> dim(sobj_sub)
[1] 22614  3332

> dim(sobj_sub[["RNA"]]$counts)
[1] 22614  3332

> dim(sobj_sub[["RNA"]]$counts@matrix)
[1] 22614  3332

> lengths(sobj_sub[["RNA"]]$counts@dimnames)
[1] 22614  3332

> as(sobj_sub[["RNA"]]$counts, Class="dgCMatrix")
22614 x 3332 sparse Matrix of class "dgCMatrix"
`

**Comment by bnprks** [comment]
This appears to have been a BPCells issue which I just fixed (see linked issue above)

**Comment by mhkowalski** [comment]
Closing, as this seems to be fixed in Ben's BPCells update.
