### ISSUE TITLE
order of FindVariableGenes, ScaleData

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#829]
I am a little confused about the order of  FindVariableGenes, ScaleData, you can see in website https://satijalab.org/seurat/pbmc3k_tutorial.html and https://satijalab.org/seurat/immune_alignment.html, there are different order, but one for pca, one for cca, is because of the following analysis so you change he order of FindVariableGenes, ScaleData or other?  Thanks a lot.

**Comment by leonfodoulian** [comment]
Hi @2236529177,

As long as `Seurat::ScaleData()` is run on all the genes present in `object@data`, the order of these two functions does not matter. If you'd like to scale only variable genes (which is computationally much faster), then you would want to run `Seurat::FindVariableGenes()` first.

Best,
Leon

**Comment by 2236529177** [comment]
> `:FindVariableGenes()` first.
> 
> Best,

Thanks for your kind and professional reply.  I also want to ask whether  NormalizeData and ScaleData has order? if yes, is it ok for you to tell me the order, as you know,  ScaleData change the distribution of data, while NormalizeData not. Thanks a lot.

**Comment by leonfodoulian** [comment]
Hi @2236529177,

`Seurat::ScaleData()` is performed on the normalized data, so you should first run `Seurat::NormalizeData()`.

Best,
Leon
