### ISSUE TITLE
How to rasterize SpatialFeaturePlot

### ISSUE THREAD

**Issue by diala-ar** [satijalab/seurat#8290]
Thanks so much for the great package!

I was wondering whether it is possible to add a raster parameter for SpatialFeaturePlot, as in FeaturePlot. saving a pdf containing multiple spatial feature plots generates big pdf file. I tried to use the ggrastr::rasterize(p) and ggrastr::rasterise(p, layers='GeomSpatial'), I save the output as a pdf file, but the pdf size did not decrease if compared with saving the plot without any rasterization. Thanks!

**Comment by dcollins15** [comment]
How big are your output files?

It's possible that the PDF size is not decreasing because it is being dominated by the PNG image that the plot is overlaid on top of. In that case, rasterizing the rest of the plot won't help much.

**Comment by diala-ar** [comment]
Thanks a lot @dcollins15, you are definitely right this has to do with the png file, because when I set image.alpha=0 in the SpatialFeaturePlot, the size of a pdf file containing 8 spatial figures decreases from 5.4MB to 2.3MB. However, is there a way to rasterize the background image if we need to keep it in the background? Thanks again!

**Comment by dcollins15** [comment]
AFAIK PNGs are in a rasterized format your best bet may be to try compressing the PDF files after you've generated them. The only other option I can think of is to compress the PNGs before plotting but I'm not sure how that would affect the spatial coordinate mapping. Sorry that I don't have a better answer for you but happy plotting!

**Comment by ckfromCN** [comment]
Try ggrastr::rasterise(p,layers='Spatial',dpi = 600)
This works for me.
