### ISSUE TITLE
Keeping the scale.data when merging

### ISSUE THREAD

**Issue by villadswin** [satijalab/seurat#8295]
Hi, 

I am trying to scale and merge several seurat objects. The pipeline is quite time consuming, and I therefore want to parallelize with snakemake and scaling each seurat object separately, before merging them all together.

The problem is that when merging seurat objects the scale.data slot in the RNA assay is deleted (This isn't the case for SCT assays). Using merge.data = TRUE will only preserve the data slot. 

I could save the scale.data separately and merge them manually, but I haven't found a very efficient way to do it, as the scale.data is quite cumbersome to work with in the sparseMatrix format.

Thanks in advance.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So I think you are misunderstanding the scale.data layer.  The results of this layer are dependent expression across all cells in an object.  Therefore, the values from one object before being merged with another are no longer correct.  Therefore, the layer is removed and you need to re-run `ScaleData` after merging the objects.

Best,
Sam

**Comment by villadswin** [comment]
Hi Sam, 

Thank you so much for your response!

I should maybe also have added that when running ScaleData after merging, i am using the split.by argument to center, scale and regress variables from each sample independently.  My understanding is that if this is not done independently per sample, then we will potentially introduce batch effect in the scale.data. Thats why i think it should be okay to keep the scale.data when merging. I do agree that merging the scale.data layer/slot should be done with caution, as there are potential pitfalls. 

Best, 
Villads
