### ISSUE TITLE
SketchData errors in v5 Seurat

### ISSUE THREAD

**Issue by michellesingapore** [satijalab/seurat#8296]
Hi all, please help! 
I'm referencing https://satijalab.org/seurat/articles/parsebio_sketch_integration on 10x data and a couple error jumps up depending on the code that I try to run

I have a seurat object (sce) of about 4.7GB and i started by normalising 
scenorm <- NormalizeData(sce) #Seurat 7.5GB

> FindVariableFeatures(scenorm, verbose = FALSE)
An object of class Seurat 
21346 features across 6962223 samples within 1 assay 
Active assay: RNA (21346 features, 2000 variable features)
 36 layers present: counts.sn1hr_1, counts.sn1hr_2, counts.sn4hr, counts.snd0_1, counts.snd0_2, counts.snd0_3, counts.snd1_1, counts.snd1_2, counts.snd1_3, counts.snd1_4, counts.snd1_5, counts.snd1_6, counts.snd3_1, counts.snd3_2, counts.snd3_3, counts.snd7_1, counts.snd7_2, counts.snd7_3, data.sn1hr_1, data.sn1hr_2, data.sn4hr, data.snd0_1, data.snd0_2, data.snd0_3, data.snd1_1, data.snd1_2, data.snd1_3, data.snd1_4, data.snd1_5, data.snd1_6, data.snd3_1, data.snd3_2, data.snd3_3, data.snd7_1, data.snd7_2, data.snd7_3

^ All's good, so i try to sketch

> object <- SketchData(scenorm, ncells = 5000, method = "LeverageScore", sketched.assay = "sketch") 
Calcuating Leverage Score
Error in switch(EXPR = tolower(x = method), mean.var.plot = "mvp", dispersion = "disp",  : 
  EXPR must be a length 1 vector

^This caused this error, but i also tried to specify all the arguments as shown below which gives me a different error 

> object <- SketchData(scenorm, assay = NULL, ncells = 5000, sketched.assay = "sketch", method = LeverageScore, var.name = "leverage.score", over.write = FALSE, seed = 123, cast = "dgCMatrix", verbose = TRUE)
Error in match.arg(arg = method) : 
  'arg' must be NULL or a character vector

I am unable to figure out how to fix this! Thank you in advance

**Comment by Gesmira** [comment]
Hi, 
The second error is because the method has to be in quotes: `method = "LeverageScore"`. 
In regards to the first error, this is the error you get if the object does not have variable features stored, which is because you didn't set the output of the `FindVariableFeatures` function back to the object. 
You have to run something like this:
```
scenorm <- FindVariableFeatures(scenorm, verbose = FALSE)
```
And then you can run the `SketchData` function after as you did in the first way.

**Comment by sbt2024** [comment]
I am having the same exact error when running SketchData even when I have the method in quotes as suggested above. SketchData was working fine with previous Seurat v4.999, I am seeing this error for the first time after having updated to Seurat v5.03. 

`> sc_v5_test2 <- SketchData(sc_v5_test2, assay = NULL, ncells = 1000, method = "LeverageScore", sketched.assay = "sketch")
Calcuating Leverage Score
Error in switch(EXPR = tolower(x = method), mean.var.plot = "mvp", dispersion = "disp",  : 
  EXPR must be a length 1 vector
> `
