### ISSUE TITLE
Seurat Analysis: Deleting cells from seurat object

### ISSUE THREAD

**Issue by isaiao01** [satijalab/seurat#8299]
I have not been able to code anything as i am in the thought process.. but i was wondering i have 3 samples: DP1, DP2 and DP3. 

DP1 is tumor cells but both DP2 and DP3 are tumor + PBMCs. I would like to delete the PBMCs. How could one potentially go about this so that we have DP1, DP2 and DP3 as tumor cells only for further analysis? I have included a column in the metadata titles cells to differentiation DP1, DP2, and DP3. 

I hope this makes sense. All help will be appreciated as i have no idea how to do this in seurat.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  To remove cells from object all you need is a vector of the barcodes you want to remove (or those you want to keep) and use `subset`.

If you have vector of cells to keep (named `cells_to_keep`) then run:
```
obj <- subset(obj, cells = cells_to_keep)
```

If you have vector of cells to remove (named `cells_to_remove`) then run:
```
obj <- subset(obj, cells = cells_to_remove, invert = TRUE)
```

Best,
Sam

**Comment by isaiao01** [comment]
Hmm i see what you are saying but how do i even identify the pbmc cells in the seurat object? Do i need the pbmc markers? That's the difficult part here

**Comment by samuel-marsh** [comment]
Hi @isaiao01,

That is up to your analysis to identify.  I would point you to Seurat vignettes for further info on analysis methods.

Best,
Sam
