### ISSUE TITLE
How to subset cells with particular gene(s) expressed?

### ISSUE THREAD

**Issue by ericvon11** [satijalab/seurat#83]
Hi,

I realize this is probably a very newb question and isn't an "issue" with the package, but I've been trying to subset my data for a while to no avail. I've been learning R for about a month now, but at this point, I'd really just like someone else's help on how to accomplish this one thing: I'm trying to subset just my Vglut positive neurons to subcluster and look for any patterns in just this population of cells. This same method could of course then be applied to all the other major subtypes.

Using the mitochondrial SubsetData concept in the tutorials, I figured I could tell Seurat to look for Vglut genes, then subset the cells based on whether they have the Vglut genes (using a very low accept.low percentage). This isn't working and I'm sure there's a flaw in my thinking. Vglut has a length of 1.

```

vglut.genes = grep("^Slc17", rownames(PData@data), value = T)
percent.glut = colSums((PData@data[vglut.genes, ])) / colSums((PData@data))
PData = AddMetaData(PData, percent.glut, "percent.glut")
Vglut = SubsetData(PData, subset.name = "percent.glut", accept.low =.01 )
```

**Comment by mukundvarma** [comment]
It would be helpful if you can explain what exactly you mean by "not working".

The function itself works. Do you know for sure that you have any vglut genes being expressed at all? If yes, is 1% of the total reads a "low enough" cutoff for reads assigned to these genes? You could look at a histogram of percent.glut to figure out what an acceptable low cutoff should be

**Comment by sameet** [comment]
Hi,
Excellent answer, but can I also reverse the process.  Say I have a list of genes, for which I calculated the percent transcripts, I want to select those cells where this percentage is very low.  What should I change, the `accept.low`, or the `accept.high`.

**Comment by satijalab** [comment]
Accept.high sets the maximum value to keep, so you probably want to change this. In v2.0, We've updated the documentation slightly, and added a function (FilterCells) to assist users in QC and filtration.
