### ISSUE TITLE
Convert.SingleCellExperiment throws an error when cell names arent present

### ISSUE THREAD

**Issue by karim-soufi** [satijalab/seurat#830]
Hello,

Convert.SingleCellExperiment will throw an error when converting from sce object that doesnt have the cell names as colnames in the counts matrix.

```R
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “NULL” is not valid for @‘cell.names’ in an object of class “seurat”; is(value, "vector") is not TRUE
```
The col.names parameter in DropletUtils::read10xCounts is FALSE by default. However, reading multiple samples in sce will force the colnames to be empty, which will cause an issue when converting an sce object with multiple samples to seurat.

best regards.

**Comment by andrewwbutler** [comment]
Hi,

This should now work in Seurat v3.0 via the `as.Seurat` function (docs/conversion vignette coming soon). If the column names (cell names) are missing in the SingleCellExperiment object, they will be filled with "cell_columnidx" (e.g "cell_1") to ensure consistent/unique cell names.

**Comment by NadineBestard** [comment]
Hello, 
I am reopening this issue as `as.Seurat` is still giving similar issues, as discussed [here](https://support.bioconductor.org/p/9136786/#9137421). The error that pops up is `Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing`
