### ISSUE TITLE
V5 FeaturePlot behaviour

### ISSUE THREAD

**Issue by mdeea** [satijalab/seurat#8302]
I've recently upgraded to Seurat V5.
The behaviour of Featureplot wrt colorpalettes seems to have changed.
When I supply it with a vector of colours, 
it just bins the data into two bins corresponding to the maximal and minimal values in the palette.
Is there some other option I should be using to get a gradient of colours?

`plasma <- viridis(10, direction = 1, option = "C")`

`FeaturePlot(mySet.combined,
                 reduction = "umap", 
                 features = myHallmarks[3], order = TRUE,
                 keep.scale = 'feature',
                 split.by = "Age",
               cols = plasma
              )`
[myUmap.pdf](https://github.com/satijalab/seurat/files/13895557/myUmap.pdf)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  In terms of applying gradient you can do this as you would with any ggplot2 object with post plot theming.

Alternatively, I have implemented gradient natively in my package scCustomize `FeaturePlot_scCustom`.  It is plasma by default and also shifts non-expressing cells off of the color scale to a different color.

Best,
Sam

**Comment by mdeea** [comment]
Thanks, I had post-hacked it using patchwork but wanted to understand what I was doing wrong.
