### ISSUE TITLE
Vignette "Demultiplexing with hashtag oligos (HTOs)" results in "404 Not Found" Error

### ISSUE THREAD

**Issue by tim-meese** [satijalab/seurat#8306]
Hello

I wanted to consult the vignette ["Demultiplexing with hashtag oligos (HTOs)"](https://satijalab.org/seurat/articles/seurat5_hashing_vignette.html), but this results in an "404 Not Found" error. Could this be fixed? 

In essence, I want to know how to perform demultiplexing of hashtag oligos of different libraries in Seurat version 5. More specifically, does this also work with the different layers? 

With kind regards

**Comment by samuel-marsh** [comment]
Hi,

It seems you are working with outdated link.  The most up to date link is:
https://satijalab.org/seurat/articles/hashing_vignette

You can always start from seurat homepage to navigate to most up to date vignettes.
https://satijalab.org/seurat/

Best,
Sam
