### ISSUE TITLE
Dots > scale.max disappear in DotPlot

### ISSUE THREAD

**Issue by ogarmar3** [satijalab/seurat#831]
Hello,

I want to make the small dots (low pct.ext) bigger. I tried scale.max=60 to make the biggest dots be >60 pct.ext. What happens is, if pct.ext > 60, the dots don't appear on the plot.

Is there a way to make the dots above scale.max threshold appear, or another way to make the lower pct.ext dots look bigger?

Thank you!
Marcos

Edit: clarity

**Comment by mojaveazure** [comment]
Fixed as of commit fe23d65
