### ISSUE TITLE
Can I use SCT-transformed data to compare expression of genes when samples have significantly different library sizes ? (Visium)

### ISSUE THREAD

**Issue by Bberenicedug** [satijalab/seurat#8312]
Dear Seurat team, 

I would like to perform DE analysis on Visium data from different samples (from different patients).
I have used the following pipeline (SCT transformation of each sample individually, merging, and then integration using Harmony).

I initially wanted to compare gene expression of several genes of interest across samples using the data of the SCT slot of my integrated object but found some discussions online that made me question this idea, and didn't find any clear and definitive answer on this topic.

Especially, it seems that we shouldn't use the SCT data if samples have different library sizes (which is the case for my visium data, where I see major differences in sequencing depth). This seems to be true at least for the package version in 2021. 

Especially, I saw the following answer from your team in 2021 : 
"You can run DE on SCT corrected counts if the SCT model is the same across all the experiments (or they have similar median sequencing depth). " https://github.com/satijalab/seurat/issues/4620 

But it didn't say, how we could perform if we don't have the same library sizes ?

Many thanks for your help !! (and for your great package)
Hope I didn't miss any information !

**Comment by saketkc** [comment]
Hi @Bberenicedug , see [this vignette](https://satijalab.org/seurat/articles/sctransform_vignette) for an example. In brief, if you have smaples with different library sizes that we individually normalized with SCTransform, you can merge them and run `PrepSCTFindMarkers` to recalculate the corrected counts using minimum of median sequencing depth

**Comment by Bberenicedug** [comment]
Dear Saket,

Many thanks for your prompt answer.

_( For your information, I believe that the link provided may not be the correct one. The vignette does not cover the integration and merging of different datasets, nor does it include the usage of the PrepSCTFindMarkers function (it's a demonstration of how to execute sct-transformation on a single dataset). )_

I have proceeded to run "PrepSCTFindMarkers" and reviewed the associated documentation, which seems to be just what I needed !  :+1: 

Thank you once again for your help
