### ISSUE TITLE
Run FindAllMarkers function in parallel

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8315]
Good afternoon,

I am facing long run times with below function since I added the adjustment for batch (via latent.vars):
`FindAllMarkers(kid.filtered_new,test.use="poisson",latent.vars = "orig.ident")`

 I would like to run it in parallel in RStudio. I read some old posts about doing it with the doFuture package.
However, more recent posts mentioned that this is not working anymore? https://github.com/satijalab/seurat/issues/7000 ?

Can anyone advise me if this is the case and if so could you recommend me any other option to run this function in parallel?

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Within the Future framework you could always use `FindMarkers` and `future_lapply` instead of `FindAllMarkers`.

```
library(future)
library(future.apply)

plan(multisession(workers = XX))
idents <- levels(Idents(obj))

markers <- future_lapply(idents, function(x) {
  FindMarkers(object = obj, ident.1 = x)
}, future.seed = TRUE)
```

Best,
Sam

**Comment by LeaLe88** [comment]
Dear Sam

Thank you so much for your reply!

And this would work with latent.vars argument? And I can choose the test.use?

I would run it as shown below then:

```
library(future)
library(future.apply)

plan(multisession(workers = XX))
idents <- levels(Idents(obj))

markers <- future_lapply(idents, function(x) {
  FindMarkers(object = obj, ident.1 = x, ,test.use="poisson",**latent.vars = "orig.ident"**)}, future.seed = TRUE)
```

**Comment by samuel-marsh** [comment]
Hi @LeaLe88,

No problem, happy to help!  Ya it will work with whatever other arguments you want in the function.  The `ident.1 = x` is key part as that specifies which of the clusters in `idents` to use.

Best,
Sam

**Comment by LeaLe88** [comment]
Hi Sam,

Just one more question for clarification: I have received now the results of the run :). It looks a bit different to the previous results I received from FindAllMarkers. Instead of having one document, which includes the pvalue and logFC for each cluster compared to all other cluster, I have now 15 sheets in my excel sheet (I believe these represent my 15 clusters). Just to clarify: It is correct that e.g. sheet one (for cluster 1) I have now the p-value and logFC for cluster 1 compared to all other clusters?

Thank you!

**Comment by HenrikBengtsson** [comment]
PS. @samuel-marsh , the official specification is `plan(multisession, workers = XX)`, not `plan(multisession(workers = XX))`. I've noticed others using the latter, and don't know when that style started to spread, but it's not official supported (and I surprised it actually works)

**Comment by samuel-marsh** [comment]
Hi @HenrikBengtsson yes thanks for correcting error!  Indeed an older code doc where I copied from for this issue.

**Comment by LeaLe88** [comment]
Thank you, I have changed it. Continued discussion in future github on this https://github.com/HenrikBengtsson/future/discussions/710.
