### ISSUE TITLE
Error in simpleLoess() using FindVariableFeatures() function

### ISSUE THREAD

**Issue by valentinaOpazo** [satijalab/seurat#8316]
Hello!
In order to merge 14 seurat objects into one and avoid memory problemI used `SeuratDiet` function to each sample with this code (if I don't run `DietSeurat`, my memory RAM can't perform the `merge` function)

```
BC1_diet <- DietSeurat(BC1,assays = c('predicted','peaks'))
BC2_diet <- DietSeurat(BC2,assays = c('predicted','peaks'))
BC3_diet <- DietSeurat(BC3,assays = c('predicted','peaks'))
BC4_diet <- DietSeurat(BC4,assays = c('predicted','peaks'))
BC5_diet <- DietSeurat(BC5,assays = c('predicted','peaks'))
CC1_diet <- DietSeurat(CC1,assays = c('predicted','peaks'))
CC2_diet <- DietSeurat(CC2,assays = c('predicted','peaks'))
CC3_diet <- DietSeurat(CC3,assays = c('predicted','peaks'))
LC1_diet <- DietSeurat(LC1,assays = c('predicted','peaks'))
LC2_diet <- DietSeurat(LC2,assays = c('predicted','peaks'))
OV1_diet <- DietSeurat(OV1,assays = c('predicted','peaks'))
OV2_diet <- DietSeurat(OV2,assays = c('predicted','peaks'))
RCC1_diet <- DietSeurat(RCC1,assays = c('predicted','peaks'))
RCC2_diet <- DietSeurat(RCC2,assays = c('predicted','peaks'))

carcinoma <-  merge(
  x = BC1_diet,
  y = list(BC2_diet,BC3_diet,BC4_diet,BC5_diet,CC1_diet,CC2_diet,CC3_diet,LC1_diet,LC2_diet,OV1_diet,OV2_diet,RCC1_diet,RCC2_diet),
  add.cell.ids = c("BC1","BC2","BC3","BC4","BC5","CC1","CC2","CC3","LC1","LC2","OV1","OV2","RCC1","RCC2"))
```

With carcinoma object I need to run `FindVariableFeatures` on the assay with gene expression data (called **_predicted_**) but I got this error message:

```
DefaultAssay(carcinoma) <- "predicted"
carcinoma <- NormalizeData(carcinoma)
carcinoma <- FindVariableFeatures(carcinoma, nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'
```

Searching in another issues I found that this could be for problems on input matrix https://github.com/satijalab/seurat/issues/2387#issuecomment-603173007. My input matrix looks like this:

```
head(carcinoma@assays$predicted@counts)
6 x 48198 sparse Matrix of class "dgCMatrix"
  [[ suppressing 43 column names 'BC1_AAACGAAAGAACGTCG-1', 'BC1_AAACGAAAGTATGCTC-1', 'BC1_AAACGAAAGTCTAGAA-1' ... ]]
                                                                                                 
RP11-34P13.7  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
FO538757.2    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AP006222.2    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
RP4-669L17.10 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
RP5-857K21.4  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
RP11-206L10.9 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
                      
RP11-34P13.7  . ......
FO538757.2    . ......
AP006222.2    . ......
RP4-669L17.10 . ......
RP5-857K21.4  . ......
RP11-206L10.9 . ......

 .....suppressing 48155 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................
```

Is the problem because the input matrix?? How can I fix it??

**Comment by longmanz** [comment]
Hi, 
I am guessing your are using predicted RNA values as your "predicted" assay. Please could you make sure that the "predicted" assay is correctly generated in your previous steps? 
It seems that all the genes have 0 values in the top few rows of your matrix. You can quickly check this by running `row_sum = RowSums(carcinoma@assays$predicted@counts)` and see if the values are not all 0s. 
Also, could you try is you can run FindVariableFeatures() to any one of your objects (BC1, BC2, ...) prior to merging, and see if it works okay or not.

**Comment by valentinaOpazo** [comment]
Thanks for your answer! In effect the "predicted" assay was created from the imputation of scRNAseq dataset with `FindTransferAnchors` and `TransferData` functions to each of the 14 samples. 
I checked the counts matrix and just like you mentioned all genes have 0 values, but this occurs after running `merge` function because  _BC1_ and _BC1_diet_ have proper values in their matrix. Also `FindVariableFeatures` works fine with both objects.

**Comment by Gesmira** [comment]
Hi @valentinaOpazo, 
Are you still running into this issue?

**Comment by valentinaOpazo** [comment]
Finally, I didn't use the output objects of `DietSeurat` and `merge` function works fine
