### ISSUE TITLE
JoinLayers error -  incorrect number of dimensions

### ISSUE THREAD

**Issue by muktic** [satijalab/seurat#8317]
Hi, I'm using JoinLayers() to join layers of a Seurat object that has 70 layers. I keep running into the following error in JoinLayers():

```
> hto.id <- JoinLayers(hto.id)
Error in methods::slot(object = object, name = "layers")[[layer]][features,  : 
  incorrect number of dimensions
```

I'm not sure how to debug this - is there any way to fix this error?
Thanks in advance!

**Comment by mainyanghr** [comment]
> Hi, I'm using JoinLayers() to join layers of a Seurat object that has 70 layers. I keep running into the following error in JoinLayers():
> 
> ```
> > hto.id <- JoinLayers(hto.id)
> Error in methods::slot(object = object, name = "layers")[[layer]][features,  : 
>   incorrect number of dimensions
> ```
> 
> I'm not sure how to debug this - is there any way to fix this error? Thanks in advance!

I have the same errors when do the subset. Could you give me some suggestions?  Thank you very much.
