### ISSUE TITLE
SCTransform function choose different HVGs from the exact same input objects

### ISSUE THREAD

**Issue by sengao86** [satijalab/seurat#8319]
Hello, 

I ran SCTransform on the exact same dataset on two occasions using the same code on the same server, but got two different sets of HVGs.

The changes between the two runs is that I updated Seurat from 4.1.1 to 4.4.0,  and updated other packages installed. 

There are about 32 HVGs were not the same between the two sets. 

I reinstalled 4.1.1 and the results was still the same to 4.4.0 but different to the results from previous run of 4.1.1.  

I also tried versions earlier than 4.1.1 (like 4.06) and got the same result to the 4.4.0.

It seems that the difference was not caused by the different versions of Seurat.

The resulting SCT data matrices were not the same too.

Hope I can get a general idea about what caused this change.

Thanks!

code used:
SCTransform(tmp_data, assay = "Spatial", return.only.var.genes = FALSE, verbose = FALSE)

**Comment by saketkc** [comment]
HI @sengao86, in v4 `SCTransform` uses the `MASS` package's utility for estimating the NB parameters. While we have not detected any changes in our test-cases (and I do not expect them to change a lot with new MASS releases), I would need more information to debug. If you can email me the code and the object at schoudhary@nygenome.org. I can take a look. I will close this issue for now.
