### ISSUE TITLE
SubsetData with subset.name + accept.value returns error 'unexpected '@' in object@dr$@'

### ISSUE THREAD

**Issue by carmensandoval** [satijalab/seurat#832]
Hi, 

I'm trying to subset a Seurat object made up of three different samples using the `SubsetData` function, but I keep getting this strange error...

```
> gw22 <- SubsetData(superobject, subset.name = "orig.ident", accept.value="gw22", 
                      do.clean=TRUE, subset.raw=TRUE)
```

```
Error in parse(text = paste0("data.use <- object@dr$", names(x = var.options[which(i ==  :
  <text>:1:23: unexpected '@'
1: data.use <- object@dr$@
```

This is what `superobject@meta.data` looks like:

![image](https://user-images.githubusercontent.com/10520084/46639110-06974d00-cb19-11e8-9352-756c8eb7e83f.png)

Thank you,

Carmen

**Comment by mojaveazure** [comment]
Hi Carmen,

Thanks for bringing this up; we're overhauling the subsetting functionality and will ensure this is fixed in the next release of Seurat

**Comment by carmensandoval** [comment]
Thank you!

**Comment by satijalab** [comment]
Closing as we have fixed this in v3 as paul suggested, you can find more at
https://satijalab.org/seurat/essential_commands.html
