### ISSUE TITLE
Where is the number of anchors stored in Seurat object?

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#8322]
Hi there,

I opened an old Seurat object which was integrated with the CCA algorithm. I need to report on how many anchors were generated for the publication of a manuscript, are they stored somewhere in the `str(object`?

Thanks in advance

**Comment by jsim91** [comment]
The object history should be under `object@commands`. For example, you might be able to find k.anchor by doing something similar to: `object@commands[["FindIntegrationAnchors"]]@params[["k.anchor"]]`. I would recommend doing `View(object@commands)` within RStudio to find the exact value you're searching for though.

**Comment by igrabski** [comment]
Hi Theodore, unfortunately it doesn't seem that this information on the number of anchors is saved in the object history. I think all you can do is go back and try to recreate the object (using the appropriate version of Seurat under which the object was made).
