### ISSUE TITLE
Using pseudobulk for molecular subtyping

### ISSUE THREAD

**Issue by nadine-ships** [satijalab/seurat#8324]
Hey,

I am working with single-cell RNA from breast cancer patients and would like to determine the molecular breast cancer subtypes of  each sample to see if that affects the clustering.
I was thinking to use the genefu package for the subtyping which requires a matrix of samples(rows) x genes(cols). I used the following to obtain a count matrix:
bulk <- AggregateExpression(data, return.seurat = T, slot = "counts", assays = "RNA", group.by = c('sample'))
count_matrix <- bulk@assays[["RNA"]]@layers[["data"]]

Then I assigned the colnames (sample names) like this:
colnames(count_matrix) <- names(bulk@active.ident)

However, I can't figure out where the gene names are stored which will be used to assign the rownames.
My count matrix is a 30366 x 13 matrix. Features(object) returns only 25718 genes. What am I missing here?

Also, any advice on this approach for molecular subtyping would be appreciated.

Thank you,
Nadine

**Comment by samuel-marsh** [comment]
Hi Nadine,

Not member of dev team but hopefully can be helpful.  So first I can't replicate your error using public dataset:
```
hca <- hcabm40k.SeuratData::hcabm40k

hca <- UpdateSeuratObject(hca)

bulk <- AggregateExpression(hca, return.seurat = T, slot = "counts", assays = "RNA", group.by = c('orig.ident'))
count_matrix <- bulk@assays[["RNA"]]@layers[["data"]]

> dim(count_matrix)
[1] 17369     8
> length(Features(hca))
[1] 17369
> 
```

So I would first recommend to check input data you are using and re-run code.

I would also say that unless you are using it for something else then setting `return.seurat = TRUE` isn't necessary.  If you set that to false you will get a matrix that has both the column and row names already set.

Furthermore, the second line in your code is going to pull the wrong data unfortunately.  If you do set return.seurat = TRUE then you want to pull the raw counts and not normalized data, which is what many pseudobulk approaches in packages outside of Seurat want.

Finally, I'm not familiar with genefu but it appears to be based on use for microarray and not RNAseq so not sure that's the best platform to use (but again not very familar with it) and you might want to look into things more.

Best,
Sam

**Comment by Gesmira** [comment]
Thanks for the response @samuel-marsh! Closing now as this seems to have answered the questions relevant to Seurat analysis. Please feel free to reopen if issues persist.
