### ISSUE TITLE
Seurat V5 FindVariableFeatures() and HarmonyIntegration() Question

### ISSUE THREAD

**Issue by Aaron-sqw** [satijalab/seurat#8325]
Dear Team,
I have two questions in Seurat V5:
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$tech)
obj<-NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)

1. When I process FindVariableFeatures(), each Layer will generate variable features, and the whole project will also get 2000 variable features. My question is if the whole object variable features are from the Layers(like the function SelectIntegrationFeatures()) or just from the merged total cells in the object.
2. After finishing the command upon, when I hope to use harmony to do integration, **object <- (object = obj, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = 'harmony', verbose = FALSE)** , I find this method could only adjust **tech** level batch effect,  but I also hope to adjust sample difference at the same time, I try to use group.by.vars=c("tech","sample"), but it didn't work.

Best regards,
Qiwei

**Comment by Aaron-sqw** [comment]
Hay,
I check the FindVariableFeatures() for layers and list+SelectIntegrationFeatures(), the results are same.
The method should be the same one.

Thanks!

**Comment by Gesmira** [comment]
HI @Aaron-sqw, 
When we find variable features with an object with 2 layers for example, we identify each layer's variable features, find the common variable features, and then supplement until n variable features are present in a list using the most variable features in the two lists that are also features in the other matrices. This is the same as the method we use for identifying features for integration. 

To your second question, we don't currently support grouping by multiple variables for integration. However, you can create a variable that contains both tech and sample by pasting the values together and then using this variable for integration. Something like: `obj$tech_sample <- paste0(obj$tech, "_", obj$sample)`. Then you can supply `tech_sample` for integration.

**Comment by Aaron-sqw** [comment]
> To your second question, we don't currently support grouping by multiple variables for integration. However, you can create a variable that contains both tech and sample by pasting the values together and then using this variable for integration. Something like: `obj$tech_sample <- paste0(obj$tech, "_", obj$sample)`. Then you can supply `tech_sample` for integration.

Dear Gesmira,
Thanks a lot for your reply!
For the second question, if I set as your method, after split layers, as samples is the smallest element in my project, so paste together should be the same as samples.  I tried using the old method  RunHarmony(group.by.vars =c("sample","tech")), It seems work that could adjust the batch from two parts. 
Whether the new version Seurat V5 could add this **group.by.vars** parameter in the HarmonyIntegration.

Best,
Aaron

**Comment by mtrussart** [comment]
Hi, 

Following up on the previous questions, I would like to know can I specify which variables to use for Harmony when using 
merge <- IntegrateLayers(
  object = merge, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",normalization.method = "SCT",
  verbose = FALSE
)
You mentioned @Gesmira in the previous example : "to supply tech_sample for integration" but where do you define it in IntegrateLayers? and which one does it use by default?

Thanks a lot,
Marie

**Comment by rachadele** [comment]
> Hi,
> 
> Following up on the previous questions, I would like to know can I specify which variables to use for Harmony when using merge <- IntegrateLayers( object = merge, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "harmony",normalization.method = "SCT", verbose = FALSE ) You mentioned @Gesmira in the previous example : "to supply tech_sample for integration" but where do you define it in IntegrateLayers? and which one does it use by default?
> 
> Thanks a lot, Marie

I think you will have to split by that group (e.g. `split(obj[["RNA"]], f = obj$tech_sample`))
