### ISSUE TITLE
Findmarkers print clusters

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8326]
Good morning, 

Is there an argument I can add to FindMarkers in order to print the clusters I am comparing?
In particular in my case I am using FindMarkers for the same purpose as FindAllMarkers (comparing all clusters to each other) in parallel as suggested in this forum via:

```
markers <- future_lapply(idents, function(x) {
  FindMarkers(object = kid.filtered_new, ident.1 = x, test.use="poisson",latent.vars = "orig.ident")
},future.seed = TRUE)
```

However, I end up with a document without clusters names, which makes it a bit of a "guessing game" which sheet is which cluster.

Thank you!

**Comment by dimurali93** [comment]
Hi, 
As mentioned in [this](https://satijalab.org/seurat/articles/pbmc3k_tutorial) page, you could do the following to get cluster numbers.
```
pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE)
pbmc.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
```

**Comment by LeaLe88** [comment]
@dimurali93  Thank you for your response. Unfortunately I cannot run FindAllMarkers due to run times. Therefore running above function with FindMarkers which doesnt provide a cluster as an output.

**Comment by samuel-marsh** [comment]
Hi @LeaLe88,

you can add cluster id inside of lapply
```
markers <- future_lapply(idents, function(x) {
  Clu_marker <- FindMarkers(object = kid.filtered_new, ident.1 = x, test.use="poisson",latent.vars = "orig.ident")
  Clu_marker$cluster <- x
},future.seed = TRUE)
```

Best,
Sam

**Comment by LeaLe88** [comment]
Dear Sam, 

Thank you. 
For some reason I am using all cores even though I specified the following:

```
plan(multisession(workers = 6))   #seems not to be working correctly 
idents <- levels(Idents(kid.filtered_new))

# To avoid this error run:
#Error in getGlobalsAndPackages(expr, envir = envir, globals = globals) : 
#The total size of the 2 globals exported for future expression ('FUN()') is 1.27 GiB.. This exceeds the maximum allowed size of 500.00 MiB (option 'future.globals.maxSize'). 
options(future.globals.maxSize = 8000 * 1024^2)

#Create future
markers <- future_lapply(idents, function(x) {
  Clu_marker <- FindMarkers(object = kid.filtered_new, ident.1 = x, test.use="poisson",latent.vars = "orig.ident")
  Clu_marker$cluster <- x
},future.seed = TRUE)
```

Do you have any additional thought on why this is happening? 

Thanks so much!
