### ISSUE TITLE
relation between do.scale and do.center and Scaledata 

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#833]
I found a lot of functions supply param do.scale and do.center, and seurat have independent Scaledata function, seurat also mentioned in CreateSeuratObject "In object@scale.data, perform row-scaling (gene-based z-score). FALSE by default. In this case, run ScaleData later in the workflow. As a shortcut, you can specify do.scale = TRUE (and do.center = TRUE) here"

so should I set do.scale as Fasle in  all other functions if I used Scaledata first. what is more, why there is no do.normal because you have independent function NormalizeData.

also, is there an order of NormalizeData and Scaledata .

Thanks a lot, dear professor.

**Comment by leonfodoulian** [comment]
Hi @2236529177,

> I found a lot of functions supply param do.scale and do.center, and seurat have independent Scaledata function, seurat also mentioned in CreateSeuratObject "In object@scale.data, perform row-scaling (gene-based z-score). FALSE by default. In this case, run ScaleData later in the workflow. As a shortcut, you can specify do.scale = TRUE (and do.center = TRUE) here"

If your data is not yet normalized during the creation of the Seurat object, you can set `do.scale = FALSE` and `do.center = FALSE` when running `Seurat::CreateSeuratObject()`. This will allow you to do some quality checks on your cells, filter the low quality cells (or any other undesired cell) and then normalize and scale your data.

> so should I set do.scale as Fasle in all other functions if I used Scaledata first. what is more, why there is no do.normal because you have independent function NormalizeData.

Also, if you want to do some quality checks on your data before normalization after creating the Seurat object (i.e. using the raw data), then you can skip the normalization step when running `Seurat::CreateSeuratObject()`.

If you have already performed quality checks and filtered your cells before creating the Seurat object, then you can perform normalization and scaling while creating the Seurat object, and skip the `Seurat::NormalizeData()` and `Seurat::ScaleData()` functions. 

> also, is there an order of NormalizeData and Scaledata .

Please check my answer here: https://github.com/satijalab/seurat/issues/829#issuecomment-428095700.

> there is also a param named scale.factor, default 10000, I want to get more description about this, because the recommended scope of this param. Thanks a lot .

Please check issue #330.

Hope these help!

Best,
Leon

**Comment by 2236529177** [comment]
> Hi @2236529177,
> 
> > I found a lot of functions supply param do.scale and do.center, and seurat have independent Scaledata function, seurat also mentioned in CreateSeuratObject "In [object@scale.data](mailto:object@scale.data), perform row-scaling (gene-based z-score). FALSE by default. In this case, run ScaleData later in the workflow. As a shortcut, you can specify do.scale = TRUE (and do.center = TRUE) here"
> 
> If your data is not yet normalized during the creation of the Seurat object, you can set `do.scale = FALSE` and `do.center = FALSE` when running `Seurat::CreateSeuratObject()`. This will allow you to do some quality checks on your cells, filter the low quality cells (or any other undesired cell) and then normalize and scale your data.
> 
> > so should I set do.scale as Fasle in all other functions if I used Scaledata first. what is more, why there is no do.normal because you have independent function NormalizeData.
> 
> Also, if you want to do some quality checks on your data before normalization after creating the Seurat object (i.e. using the raw data), then you can skip the normalization step when running `Seurat::CreateSeuratObject()`.
> 
> If you have already performed quality checks and filtered your cells before creating the Seurat object, then you can perform normalization and scaling while creating the Seurat object, and skip the `Seurat::NormalizeData()` and `Seurat::ScaleData()` functions.
> 
> > also, is there an order of NormalizeData and Scaledata .
> 
> Please check my answer here: [#829 (comment)](https://github.com/satijalab/seurat/issues/829#issuecomment-428095700).
> 
> > there is also a param named scale.factor, default 10000, I want to get more description about this, because the recommended scope of this param. Thanks a lot .
> 
> Please check issue #330.
> 
> Hope these help!
> 
> Best,
> Leon
I do not know whether you ever tried cellrange count and aggr, the output of cellranger count just like in website https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count and https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/summary, it also supplied qulity checks(I do not know whether this is your quality checks mean) like following picture. but I guess it is not , because in the website of https://satijalab.org/seurat/pbmc3k_tutorial.html, it started from Read10X, but also did independent nomal and scale steps, but not in the Seurat::CreateSeuratObject() step
![image](https://user-images.githubusercontent.com/25199946/46709881-50e31000-cc78-11e8-95db-146e094b1c68.png)


one more question, in your  formula log(x = (t(x = t(x = data)/colSums(x = data)) * scale.factor) + 1),  the scale.factor just enlarge the data, and I still do not whether we should change this param, if so, is it convenient for you to tell me the range of it.

another puzzle, I am not familiar with statics, but I found function scale(in the R scale(data, , center = T,scale = T)) is a function of normalization, in the website https://satijalab.org/seurat/pbmc3k_tutorial.html, it described NormalizeData **"(By default, we employ a global-scaling normalization method “LogNormalize” that normalizes the gene expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000 by default), and log-transforms the result.)"** , just enlarge the data and than get the log(Base number of which(e, 2, 10) )?. I do not understand why it enlarge and then narrow（I may misunderstand the function of this, sorry）.

 in the website https://satijalab.org/seurat/pbmc3k_tutorial.html, it described ScaleData "(The scaled z-scored residuals of these models are stored in the scale.data slot, and are used for dimensionality reduction and clustering. does it stand for mean=0，std=1?)".  

so I may can understand Seurat::ScaleData() is performed on the normalized data, so you should first run Seurat::NormalizeData(). because you finally make the data  mean=0，std=1, so this should be the last step.

Thanks a lot professor.

**Comment by leonfodoulian** [comment]
Hi @2236529177,

As a side note, I am not a "professor", so please call me Leon. 

Normalizing the data through `Seurat::NormalizeData()` corrects for sequencing depth, such that all cells will have the same total number of counts. The reason why the normalized data are log-transformed is to approximate a normal distribution of the data (in other words, to "unskew" the skewed distribution of RNA-seq data in general). This is fundamentally different from z-scoring. The idea of z-scoring is to give the same weight for all genes when computing PCA, since now genes will have the same mean (of 0) and standard deviation (of 1) across all cells, which is not the case when normalizing the data. 

```R
require(Seurat)

# Compute mean and sd on normalized data
rowMeans(x = pbmc_small@data)
apply(X = pbmc_small@data, MARGIN = 1, FUN = sd)

# Compute mean and sd on scaled data
rowMeans(x = pbmc_small@scale.data)
apply(X = pbmc_small@scale.data, MARGIN = 1, FUN = sd)
```
Best,
Leon

**Comment by 2236529177** [comment]
one more question, in your formula log(x = (t(x = t(x = data)/colSums(x = data)) * scale.factor) + 1), the scale.factor just enlarge the data, and I still do not whether we should change this param, if so, is it convenient for you to tell me the range of it.
