### ISSUE TITLE
Findmarker Differential expression and Volcano

### ISSUE THREAD

**Issue by antoine4ucsd** [satijalab/seurat#8330]
Hello
I am working on harmonized scRNA data integrated with Harmony and I want to look at DE between 2 groups of samples
I followed this tutorial 
https://satijalab.org/seurat/articles/de_vignette
and considered the default and pseudobulk strategy.

if I run the folliowing
```
mydata_agg <- AggregateExpression(mydata, assays = "SCT", return.seurat = T, group.by = c( "pid", "hivstatus"))
mydata_agg$celltype.stim <- mydata_agg$status

mydata_agg.de <- FindMarkers(object = mydata_agg,
                                assay = "SCT",
                         ident.1 = "status1",
                         ident.2 = "status2",
                         test.use = "DESeq2")

```
the resulting Volcano plot seems shifted (i.e. log2 change not centered to zero). I assume it has to do with the scaling /log transformation but I am not sure what would be the optimal way to perform DE on these data.
I also tried with RNA assay, default test (Wilcox) and without aggregation. all lead to different results.

any thoughts on the 'optimal' strategy to consider?
sorry for the naive question and thank you in advance for your input!
![volcano](https://github.com/satijalab/seurat/assets/18502631/dbad6518-af2a-41f3-ba2c-8e465b995afb)

**Comment by harrisonized** [comment]
Hi @antoine4ucsd. I ran into the same issue. When I investigated, I found that using `FindMarkers` with `test.use="DESeq2"` is supposed to call `DESeq2DETest`, which is found here:
https://github.com/satijalab/seurat/blob/656fc8b/R/differential_expression.R#L842-L875

However, when you 



https://github.com/satijalab/seurat/blob/release/4.3.0/R/differential_expression.R#L1354-L1386




Unfortunately, 

When you run `FindMarkers` and select `test.use = "DESeq2"`, the code in question being run is found here:

**Comment by mhkowalski** [comment]
Hello,

Thanks a lot for reporting this. This was a bug, caused by the default behavior of using the counts slot for calculating fold-changes, which doesn't take into account imbalanced sample sizes between the two groups when doing pseudobulk analysis. We have updated this function as of v5.0.2 to allow a `fc.slot` argument, which is set to `data` by default. You should no longer see this behavior, but please let us know if you have any additional problems.

**Comment by mhkowalski** [comment]
Just noting that @harrisonized is also correct, we don't use the same `FoldChange` calculation as DESeq2 so you would have to use their function directly if you'd like to use their calculation, but you should not see this "shifted" behavior on volcano plots with latest seurat version.

**Comment by r-osorio** [comment]
Hi I'm wondering if this has been confirmed to be fixed - I am creating a volcanoplot with my data on seruat 5.0.2 and my plot is still centered off of the origin (right-shifted). Ran FindMarkers between two cell identities on my RNA assay.

**Comment by nicol-flores** [comment]
Hello,

I have the same issue with the volcano plot. I am working on integrated scRNA-seq data and I followed the differential expression testing vignette.

I run the following:
`pseudo_seurat <- AggregateExpression(seurat_harmony, assays = "RNA", return.seurat = T, 
                                     group.by = c("condition", "orig.ident", "seurat_clusters"))

pseudo_seurat$celltype_cond <- paste(pseudo_seurat$seurat_clusters, 
                                     pseudo_seurat$condition, sep = "_")

Idents(pseudo_seurat) <- "celltype_cond"
library(DESeq2)
bulk_c0_de <- FindMarkers(object = pseudo_seurat,
                          ident.1 = "0_SR",
                          ident.2 = "0_CI",
                          test.use = "DESeq2",
                          min.cells.group = 2)`

And the volcano plot looks shifted:
<img width="762" alt="Captura de pantalla 2024-05-06 a la(s) 7 28 13 p m" src="https://github.com/satijalab/seurat/assets/169075754/99097370-eee0-4598-8940-ce6e7d94a4d3">

Is there a way to fix this? I’m using Seurat v5.0.3
Any input would be appreciated, thanks!

**Comment by ayusyarif** [comment]
Hi,

I also encounter the same issue here

![Screenshot 2024-09-23 at 10 19 47 AM](https://github.com/user-attachments/assets/a993b911-fbad-443e-92d7-25432db424bc)

**Comment by michael-r-odea** [comment]
Hi, 
Re: @r-osorio 's comment, it appears the new default `fc.slot = 'data'` in FindMarkers/FindAllMarkers results in the same shift in the avg_log2FC values that was mentioned before. Setting `fc.slot = 'counts'` fixed this issue for me. (I'm using v5.1.0.) 

```
cluster_markers = FindAllMarkers(mouse, logfc.threshold = 0)
cluster_markers_FCcounts = FindAllMarkers(mouse, logfc.threshold = 0, fc.slot = "counts")

p1 <- ggplot(data = cluster_markers %>% filter(cluster == "3"), 
       aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') + 
  geom_point(size = 0.01) + labs(x = "avg. log2-fold change", y = "-log10(adjusted p-value)", title = "default")

p2 <- ggplot(data = cluster_markers_FCcounts %>% filter(cluster == "3"), 
       aes(x = avg_log2FC, y = -log10(p_val_adj))) +
  geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') + 
  geom_point(size = 0.01) + labs(x = "avg. log2-fold change", y = "-log10(adjusted p-value)", title = "fc.slot = 'counts'")

p1 + p2
```
![volcano_plots](https://github.com/user-attachments/assets/4dd8dbbc-3fa6-4a6a-a34c-fffb66d0716e)

**Comment by sadhnarao** [comment]
@michael-r-odea @mhkowalski 

Hi - I still see this behavior on Seurat, even with fc.slot set to counts/data. I am not using DeSEQ, just Find.Markers followed by plotting.

, , ,

    # find all markers of T-cell related clusters, 10 clusters total
    tcell_cluster<- c("Tregs", "T cells CD8" , "T cells CD8 KLRG1", "T cells CD4 IL17A", 
                     "IELs ID3 ENTPD1", "T cells CD4 FOSB", "T cells Naive CD4", 
                     "ILCs", "NK cells KLRF1 CD3G-", "T cells OGT")     

    tcell.markers <- FindMarkers(seuratObjectsubset, ident.1 = tcell_cluster)
    tcell.markers2 <- FindMarkers(seuratObjectsubset, ident.1 = tcell_cluster, fc.slot = 'counts')
   
    # plot
    
    p17 <- ggplot(data = tcell.markers, 
                 aes(x = avg_log2FC, y = -log10(p_val_adj))) +
      geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') + 
      geom_point(size = 0.01) + labs(x = "avg. log2-fold change", y = "-log10(adjusted p-value)", title = "default")
    
    p18 <- ggplot(data = tcell.markers2, 
                  aes(x = avg_log2FC, y = -log10(p_val_adj))) +
      geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') + 
      geom_point(size = 0.01) + labs(x = "avg. log2-fold change", y = "-log10(adjusted p-value)", title = "fc.slot = 'counts'")
    
    p17 + p18
, , ,

![image](https://github.com/user-attachments/assets/92e5836c-4d26-4420-9733-249d85d48255)
