### ISSUE TITLE
Why splitting object for mapping to reference? [MapQuery]

### ISSUE THREAD

**Issue by jgarces02** [satijalab/seurat#8333]
Hi, I'm following the tutorial for "Multimodal reference mapping" and don't understand why splitting the object to map. 

In the case of my data, all samples have been processed through the same tech and have already normalized individually and merged. Is it still necessary to split again my data by sample to do this mapping? If not, what would the difference be, please?

Thank you in advance.

**Comment by igrabski** [comment]
Hi Juan-Jose, if you have already appropriately normalized your data by sample, there is no need to split it again. You can just run the mapping on your full object.
