### ISSUE TITLE
Extract tissue_[low|hires]_image.png from spatial Seurat object

### ISSUE THREAD

**Issue by jdime** [satijalab/seurat#8334]
Hello,

Is there a way to extract a `tissue_hires_image.png` file from a spatial Seurat object?

For example, in the `brain` example of the [spatial vignette](https://satijalab.org/seurat/articles/spatial_vignette), I noticed that there is an array `brain@images$anterior1@image` with:
> dim(brain@images$anterior1@image)
> [1] 599 600   3

Are those 3 matrix layers what I should convert/write into a *png file? If yes could you please advice how? or are the image files stored elsewhere in the Seurat object?

Also, I saw other issues/questions switching from lowres to hires, I guess the *png that I get back will depend on what the creator of the object specified, A'm I right? or both hires and lowres are stored?

Thanks.

Javier

**Comment by alikhuseynov** [comment]
I'm not from the dev team, but I think by default it reads `tissue_lowres_iamge.png`. 
These issues #5614 #4833 should help you using `hires` image.
Now to convert the image into `.png`, you can use `terra` package.
```
image_vis <- 
SeuratObject::GetImage(obj_visium, mode = "raster") %>% 
as.matrix %>% 
terra::rast()
image_vis %>% plot
# export as .png or .tif
writeRaster(image_vis, "./test.png")
```

**Comment by jdime** [comment]
Thanks @alikhuseynov, that worked out!
But yes, there seems to be only the `tissue_lowres_image.png` attached in the object.
