### ISSUE TITLE
JoinLayers() is not working for SCT assay after integration

### ISSUE THREAD

**Issue by chiwwong** [satijalab/seurat#8336]
Thanks for the clarification, my bad. If I may a follow up, in the issue #7542 there is no mention of how to proceed further to perform DE analysis. The [Seurat5 Integration vignette](https://satijalab.org/seurat/articles/seurat5_integration) pointed me to `JoinLayers()`. Unfortunately, as 'SCT' assay is not an 'Assay5' type object, I was met with the following error:

```
> seurat %<>% JoinLayers()
Error in UseMethod(generic = "JoinLayers", object = object) : 
  no applicable method for 'JoinLayers' applied to an object of class "c('SCTAssay', 'Assay', 'KeyMixin')"
```
Neither the `PrepSCTFindMarkers()` helped me to collapse the different SCT models.
```
> seurat %<>% PrepSCTFindMarkers()
Found 6 SCT models. Recorrecting SCT counts using minimum median counts: 2388
Error in `StitchMatrix()`:
! Stitching matrices of class “dgTMatrix” is not yet supported
```
As you mentioned before, an upcoming update of Seurat5 SCT assay documentation will shed more light on the right procedures. I will be on a lookout. :-)

The link to the object was sent. Feel free to contact me as needed.

Cheers, 
Daniel

_Originally posted by @DanielZucha in https://github.com/satijalab/seurat/issues/7672#issuecomment-1675845577_
            

I would like to know if there is any update on the utilities of JoinLayers(). I cannot find the document even after the official release of v5.

I experienced the exact same error when running Seurat. While I acknowledge that combining the layers back might not be necessary if the final analysis is to plot out the UMAP, it seems that downstream analyses require one single layer. Some examples would be using the [FindTransferAnchors] and [RunAzimuth]. 
> Error: Given reference assay (SCT) has 25 reference sct models. Please provide a reference assay with a single reference sct model.

(https://satijalab.github.io/azimuth/reference/RunAzimuth.html)(https://satijalab.org/seurat/reference/findtransferanchors)

**Comment by saketkc** [comment]
Hi @chiwwong, once you integrate your samples using SCTransform based workflow and want to use this for reference mapping, you should set the reference object to integrated assay, something like:
```r
anchors <- FindTransferAnchors(reference = sct.integrated.reference, query = query, normalization.method = "SCT", npcs = 50, reference.assay = "integrated")

```
