### ISSUE TITLE
The segregation of count data into count.1 and count.2 while using LayerData() function in Seurat v5

### ISSUE THREAD

**Issue by Saumya513** [satijalab/seurat#8337]
I want to use the cellchat pipeline for understanding interactions in my single cell data for which the counts for each cells have to be extracted. By default, it considers only the first layer hence some cells whose counts are stored in count.2 are not taken. But my metadata has information about all the cells which doesnt let the cellchat object to be created. How do I combine these two counts into a single count matrix.
The error that it throws is:
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning message:
In createCellChat(object = count_ko, meta = meta_ko, group.by = "group") :
  The cell barcodes in 'meta' is different from those in the used data matrix.
              We now simply assign the colnames in the data matrix to the rownames of 'mata'!

Alternatively, I tried to use this command:
cellchat <- createCellChat( cdc_cd8_ko , group.by='ident') 
**But this also fails for Seurat v5**
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Run `rlang::last_trace()` to see where the error occurred.

Please help me to find a way around. Any help would be appreciated!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What you nee to do is run `JoinLayers`.  That will merge the relevant layers together into single layers.

Best,
Sam
