### ISSUE TITLE
how to get the matrix of stim and ctrl in your tutorial while the paper used 10x of Hyun Min Kang

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#834]
I found the paper "Multiplexed droplet single-cell rNA-sequencing using natural genetic variation" mentioned eight samples , but there are only five fastqs in  EBI of SRP102802. and there are only five fastq.gz, no annotated left and right. and cellranger count may be unable to get the file of immune_stimulated_expression_matrix.txt.gz. 
So I am wondered how you get the expression matrix, thanks a lot

**Comment by satijalab** [comment]
We e-mailed the corresponding author directly, who kindly provided it.

**Comment by 2236529177** [comment]
> We e-mailed the corresponding author directly, who kindly provided it.

I also, but no people reply to me .
