### ISSUE TITLE
BuildClusterTree _ The `slot` argument of `AverageExpression()` is deprecated as of Seurat 5.0.0.

### ISSUE THREAD

**Issue by zahramesri** [satijalab/seurat#8343]
Hello,

I am trying to run this line 

>BuildClusterTree(obj)

However I get this message, I would greatly appreciate your help:

As of Seurat v5, we recommend using AggregateExpression to perform pseudo-bulk analysis.
This message is displayed once per session.
First group.by variable `ident` starts with a number, appending `g` to ensure valid variable names
This message is displayed once every 8 hours.
An object of class Seurat 
32960 features across 49505 samples within 2 assays 
Active assay: SCT (16480 features, 1999 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: Spatial
 2 dimensional reductions calculated: pca, umap
 11 images present: CHS07.838_1R, CHS08.4433, CHS08.600, CHS09.1895_2C, CHS09.3781_5C, CHS13.7859_5.H, CHS17.9714_3.G, CHS18.4942_5.D, CHS18.6488_1F, CHS18.7826_3.R, CHS18.8277_2.M
Warning message:
The `slot` argument of `AverageExpression()` is deprecated as of Seurat 5.0.0.
ℹ Please use the `layer` argument instead.
ℹ The deprecated feature was likely used in the Seurat package.
  Please report the issue at <https://github.com/satijalab/seurat/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by longmanz** [comment]
Hi, 
I do not see an error message here, so I am not sure what you are referring to. Are you concerned about the warning messages? If you are using Seurat v5, please run `UpdateSeuratObject()` for your seurat object to make sure it is updated to the v5 format.

**Comment by warming151** [comment]
I met the same issue here, and my object is V5 format...

**Comment by Gesmira** [comment]
This should be fixed now. Please post a new issue is you continue to run into problems. Thanks!
