### ISSUE TITLE
Stable getter function for assay@meta.features and assay5@meta.data?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#8345]
In Seurat 4, an Assay has the slot @meta.features. In Assay5, this is meta.data. Is there any kind of accessor, analogous to GetAssayData(), which gives a consistent way to access that dataframe for both seurat versions?

**Comment by longmanz** [comment]
Hi, 
Sorry there is no such analogous function. Please modify your codes according to the version of Assay. And please note that the column names of @meta.features and @meta.data are also different from each other, so you will need to adjust your codes for this as well.
