### ISSUE TITLE
R language Seurat object using subset reported error

### ISSUE THREAD

**Issue by Tiller-R** [satijalab/seurat#8348]
![Screenshot 2024-01-20 235024](https://github.com/satijalab/seurat/assets/157229451/b9f6f038-9102-4d03-a813-4cfde85f0fd0)
This is the first time I've encountered this error with a subset prompt
I just want to extract the meta.data$cell_type==cardiac muscle myoblast data from scRNA separately, but it always gives me an error!
I checked my own data and it does contain this "cardiac muscle myoblast", what's going on?
Thank you to everyone who solved this problem!

**Comment by Tiller-R** [comment]
One image failed to upload, make up the post
![Uploading Screenshot 2024-01-20 235811.png…]()

**Comment by Tiller-R** [comment]
![Screenshot 2024-01-20 235811](https://github.com/satijalab/seurat/assets/157229451/8e57e8fb-011f-4091-ad2a-dba2e6444699)

**Comment by zskylarli** [comment]
Hi - could you check if this works?

```
Idents(scRNA_mus) <- "cell_type"
scRNA_mus <- subset(scRNA, idents = "cardiac muscle myoblast")
```

**Comment by Tiller-R** [comment]
Thanks for clearing up the confusion, I found the problem after repeated tests and checks in the past few days, and I'm here to share my findings and opinions with you in the hope that it will help those who are experiencing the same similar problem.
1.First I checked my Seurat object: 
①head(scRNA@assays$RNA)
                   vst.mean vst.variance vst.variance.expected
ENSG00000125812 0.051862051  0.056257106           0.057430583
ENSG00000022277 0.257277734  0.290501749           0.314427929
ENSG00000196776 0.234067663  0.262302698           0.282925672

                vst.variance.standardized vst.variable
ENSG00000125812                 0.9795670        FALSE
ENSG00000022277                 0.9239057        FALSE
ENSG00000196776                 0.9271082        FALSE

②head(scRNA@assays[["RNA"]]@counts@Dimnames[[1]])
[1] "GZF1"  "RTF2"  "CD47"  "TRBC2" "GRINA" "HOOK3"

③head(scRNA@assays[["RNA"]]@var.features)
[1] "IGKC"  "HBA2"  "IGHA1" "IGHG3" "HBB"   "IGHG1"
2.In general, they are unified form such as: ESEMBLE ID or GENE SYMBOL
I suddenly remembered that I had used a custom function from another big guy to rename the genes of Seurat objects for graphing purposes, so I'll just place the link here to protect the big guy's copyright: https://www.jianshu.com/p/6495706bac53
It was because I changed the name of the original gene that this problem occurred here, when I re-run and no longer rename, the problem was solved, the following is the process of checking the success of the Seurat object
①head(scRNA@assays$RNA)
                   vst.mean vst.variance vst.variance.expected
ENSG00000125812 0.051862051  0.056257106           0.057430583
ENSG00000022277 0.257277734  0.290501749           0.314427929
ENSG00000196776 0.234067663  0.262302698           0.282925672
                vst.variance.standardized vst.variable
ENSG00000125812                 0.9795670        FALSE
ENSG00000022277                 0.9239057        FALSE
ENSG00000196776                 0.9271082        FALSE
②head(scRNA@assays[["RNA"]]@counts@Dimnames[[1]])
[1] "ENSG00000125812" "ENSG00000022277" "ENSG00000196776" "ENSG00000211772"
[5] "ENSG00000178719" "ENSG00000168172"
③head(scRNA@assays[["RNA"]]@var.features)
[1] "ENSG00000211592" "ENSG00000188536" "ENSG00000211895" "ENSG00000211897"
[5] "ENSG00000244734" "ENSG00000211896"
3.Final result
![Uploading 123.png…]()
