### ISSUE TITLE
How do I expand the single cell clusters in umap?

### ISSUE THREAD

**Issue by Saumya513** [satijalab/seurat#8355]
I want the umap for single cell cluster on a subsetted object to spread and not concentrated at one place because its impossible to see gene expression for certain genes in FeaturePlot. I have tried reclustering the cells but they still dont spread. Any help will be appreciated!

**Comment by mhkowalski** [comment]
Hello, 

You could try subsetting these cells of interest and running a new UMAP on those cells to separate them further. I would make sure to re-run `FindVariableFeatures` , `ScaleData`, and `RunPCA` on the subset of cells you are interested in to make sure you are identifying sources of variation within this cell population. Hope this is helpful!
