### ISSUE TITLE
Impact of confounding factors

### ISSUE THREAD

**Issue by DKaukonen** [satijalab/seurat#8356]
Hi,

I have been working with Suerat for several years and I really appreciate the time and effort you have put into this project. I find the documentation well written and help is always easy to find. There is one issue I would like to ask about and it is regarding confounding factors.

In Seurat, we have the variable `vars.to.regress = c(CF1,CF2,CF3...) ` when we are normalizing data. My question is, can we pull out the coefficients of each of the vars that were regressed? It would be nice to see what sort of impact each variable is having on our data.

I have looked around the documentation and here on GitHub and have not found any way to do this or to compare each confounding factor, with the exception of just visualizing the plots. How could I go about doing this?

Thank you for your time.

EDIT; what I am looking for is a way to perform a likelihood ratio test (or ANOVA) to compare adjusting out variables to no adjustments.

**Comment by saketkc** [comment]
Hi @DKaukonen, currently this is not supported. Though you should be able to take the `scale.data` slot values and run it through lm/anova analysis outside of seurat.

**Comment by DKaukonen** [comment]
Hi @saketkc ,

Thank you for your response. Apologies for the late response, I have been trying to piece together what your response meant. I am not sure I follow on using the `scale.data` slot. I was looking to compare the LL and degrees of freedom from the adjusted vs unadjusted models. Without the models, I am not sure how one would just use the `scale.data` slot values to see what impact adjusting has on the analysis. 

Could you explain what you mean? 

Thank you,
-Damien
