### ISSUE TITLE
Seurat Integration

### ISSUE THREAD

**Issue by isaiao01** [satijalab/seurat#8357]
So, I have 3 samples: 

1. DP1 = Tumor cells 
2. DP2 & DP3 = Tumor  + PBMC cells 

I performed Seurat integration and created a dimplot split by cells (tumor cells, tumor+pbmc cells). I am attempting to remove the pbmc cells. Could i use the FindConservedMarkers to find the markers that are common to both dimplots? 

I am assuming that this function would be able to only identify the tumor cells since that is what the dimplots would share in common... that way i can subset the seurat object based on these markers....

To be clear is that what the FindConservedMarkers function does or this thought process would be wrong?

**Comment by saketkc** [comment]
The goal of [FindConservedMarkers](https://satijalab.org/seurat/reference/findconservedmarkers) is to find markers that are conserved in two datasets. See linked documentation for details.
