### ISSUE TITLE
FindMarkers with several dataset (4)

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#836]
Hi everyone,

I am currently working with multiCCA with 4 different dataset. Two of them are control and two are stimulated set.
I add a slot to have the treatment information (cf. below)
```R
objectA@meta.data$stim <- "CTRL"
objectB@meta.data$stim <- "CTRL"
objectC@meta.data$stim <- "STIM"
objectD@meta.data$stim <- "STIM"
```
 everything went OK from now and I want to identify differential expressed genes across conditions ("CTRL" versus "STIM"), so I have done this below:
```R
object@meta.data$celltype.stim <- paste0(object@ident, "_",object@meta.data$stim)
object <- StashIdent(object, save.name = "celltype")
object <- SetAllIdent(object, id = "celltype.stim")
```

and now I am in this situation: I want to create a function for all my `new.ident`, that are shared with the 4 dataset, but I want something like this (cf. below) with the tow STIM versus the two CTRL
```R
interferon.response <- FindMarkers(object, ident.1 = "STIM", ident.2 = "CTRL", print.bar = FALSE)
```

any suggestion??

Thanks!!

**Comment by 2236529177** [comment]
your data comes put from 10x?

**Comment by camilliano** [comment]
Actually, I want to avoid rewriting all of this:
```
b.interferon.response <- FindMarkers(object, ident.1 = "B cell_ADU", ident.2 = "B cell_CTRL", print.bar = FALSE)

t.interferon.response <- FindMarkers(object, ident.1 = "T cell_ADU", ident.2 = "T cell_CTRL", print.bar = FALSE)

mono.interferon.response <- FindMarkers(object, ident.1 = "Monocytes_ADU", ident.2 = "Monocytes_CTRL", print.bar = FALSE)

NK.interferon.response <- FindMarkers(object, ident.1 = "NK_ADU", ident.2 = "NK_CTRL", print.bar = FALSE)

etc
```

**Comment by 2236529177** [comment]
> Actually, I want to avoid rewriting all of this:
> 
> ```
> b.interferon.response <- FindMarkers(object, ident.1 = "B cell_ADU", ident.2 = "B cell_CTRL", print.bar = FALSE)
> 
> t.interferon.response <- FindMarkers(object, ident.1 = "T cell_ADU", ident.2 = "T cell_CTRL", print.bar = FALSE)
> 
> mono.interferon.response <- FindMarkers(object, ident.1 = "Monocytes_ADU", ident.2 = "Monocytes_CTRL", print.bar = FALSE)
> 
> NK.interferon.response <- FindMarkers(object, ident.1 = "NK_ADU", ident.2 = "NK_CTRL", print.bar = FALSE)
> 
> etc
> ```

I thought we can put the params in a dataframe, and write a function, to loop the parms

**Comment by 2236529177** [comment]
> Actually, I want to avoid rewriting all of this:
> 
> ```
> b.interferon.response <- FindMarkers(object, ident.1 = "B cell_ADU", ident.2 = "B cell_CTRL", print.bar = FALSE)
> 
> t.interferon.response <- FindMarkers(object, ident.1 = "T cell_ADU", ident.2 = "T cell_CTRL", print.bar = FALSE)
> 
> mono.interferon.response <- FindMarkers(object, ident.1 = "Monocytes_ADU", ident.2 = "Monocytes_CTRL", print.bar = FALSE)
> 
> NK.interferon.response <- FindMarkers(object, ident.1 = "NK_ADU", ident.2 = "NK_CTRL", print.bar = FALSE)
> 
> etc
> ```

Is it convennienf for you to give me a look a many fastqs ofcellrange results, I can not get that from 10xgenomics, and the data of some papers in EBI seems to have to paired data though it described as paired-end, my email is 2236529177@qq.com, thanks a lot, if you send me an email, please notice me in github, thanks a lot

**Comment by satijalab** [comment]
Thanks for the question - we don't have the equivalent of FindAllMarkers for the type of comparative analysis you describe, though I can see why it might be helpful. I recommend writing a quick for loop, as suggested in this thread, which should accomplish the same goals
