### ISSUE TITLE
IntegrateLayers multiple errors 

### ISSUE THREAD

**Issue by martuskaR** [satijalab/seurat#8361]
Hello, 

I saw many people having problems with IntegrateLayers(), however, I did not manage to find a solution to my errors. 
My objects were created with a previous version of Seurat, now I am using 5.0.1. Could you kindly have a look at my code below and assist? 

> CD4_targ_int_rna <- CD4.targ
> CD4_targ_int_rna <- UpdateSeuratObject(object = CD4_targ_int_rna)
> CD4_targ_int_rna[["SCT"]] <- split(CD4.targ[["SCT"]], f = CD4.targ$SampleTAG)
Warning: Assay SCT changing from SCTAssay to Assay5
Warning message:
Input is a v3 assay and `split()` only works for v5 assays; converting to a v5 assay 
> CD4_targ_int_rna <- IntegrateLayers(object = CD4_targ_int_rna, method = CCAIntegration, normalization.method = "SCT", verbose = T)
Error in `IntegrateLayers()`:
! None of the features provided are found in this assay
Run `rlang::last_trace()` to see where the error occurred.

I specified features, got another error: 

> CD4_targ_int_rna <- IntegrateLayers(object = CD4_targ_int_rna, method = CCAIntegration, normalization.method = "SCT", verbose = T, features = genes.targ)
Error in as(object = object.list[[i]][[assay[i]]], Class = "SCTAssay") : 
  no method or default for coercing “Assay5” to “SCTAssay”

Then I tried integrating using ifnb data, got another error:

> ifnb <- LoadData("ifnb")
> # split datasets and process without integration
> ifnb[["RNA"]] <- split(ifnb[["RNA"]], f = ifnb$stim)
> ifnb <- SCTransform(ifnb)
> ifnb <- RunPCA(ifnb)
> ifnb <- RunUMAP(ifnb, dims = 1:30)
> DimPlot(ifnb, reduction = "umap", group.by = c("stim", "seurat_annotations"))
> # integrate datasets
> ifnb <- IntegrateLayers(object = ifnb, method = CCAIntegration,verbose = F)
  |                                                  | 0 % ~calculating  Error in UseMethod(generic = "Assays", object = object) : 
  no applicable method for 'Assays' applied to an object of class "NULL"

I am wondering whether going back to previous version of Seurat would help, and integrate using FindIntegrationAnchors()?

Thank you, 
Marta

**Comment by mainyanghr** [comment]
I feel we have similar problems with layers.

**Comment by nyanmo** [comment]
I had similar problem.
Could you try SCTransform before IntegrateLayers?

**Comment by martuskaR** [comment]
I did and it did not work. I even tried creating new Seurat Object (so that there are layers already), and then running SCT. Also didn’t work ☹

From: nyanmo ***@***.***>
Date: Tuesday, 23 January 2024 at 15:25
To: satijalab/seurat ***@***.***>
Cc: Marta Rzepkowska ***@***.***>, Author ***@***.***>
Subject: Re: [satijalab/seurat] IntegrateLayers multiple errors (Issue #8361)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I had similar problem.
Could you try SCTransform before IntegrateLayers?

**Comment by Gesmira** [comment]
Hi, 
Your ifnb integration call is incorrect. If you run `ifnb <- IntegrateLayers(object = ifnb, method = CCAIntegration, normalization.method = "SCT")` it should fix your issue. When you recreated the objects yourself, what did you run?

**Comment by Gesmira** [comment]
Closing for now due to lack of response, but feel free to reopen or post a new issue if this continues. Thanks!

**Comment by martuskaR** [comment]
Hello, 

Sorry about the delay. The issue was caused by the fact I was splitting SCT assay rather than RNA. When I split RNA and then run SCT,  it worked fine. Thanks a lot!

**Comment by eric-hy** [comment]
I have same question

> > Hi, Your ifnb integration call is incorrect. If you run `ifnb <- IntegrateLayers(object = ifnb, method = CCAIntegration, normalization.method = "SCT")` it should fix your issue. When you recreated the objects yourself, what did you run?
> 
> Why this has to be run on SCT assay? In this tutorial, it clearly stated that IntegrateLayers was run on log normalized data, but I could not replicate with any Seurat versions
> 
> https://satijalab.org/seurat/articles/seurat5_integration
> 
> `obj.ref <- IntegrateLayers(object = obj.ref, method = CCAIntegration, orig.reduction = "umap",new.reduction = "integrated.cca", verbose = FALSE) | | 0 % ~calculating Error in UseMethod(generic = "Assays", object = object) : no applicable method for 'Assays' applied to an object of class "NULL"`

**Comment by Gesmira** [comment]
Hi, 
This does not have to be run on SCT assay, we were just working through how to do so. If you are having an issues with integration of log normalized data, please feel free to open another issue. Thanks!

**Comment by maozhy3** [comment]
I found some of my programs failed to save the result of ```FindVariableFeatures``` in the Seurat object when I encountered the same error. I used ```VariableFeaturePlot(scRNAlist, assay = "RNA")``` to check this and received an error. Then I reran the code:

```R
scRNAlist <- scRNAlist %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 3000)
```

and tested it with `VariableFeaturePlot(scRNAlist, assay = "RNA")`, which returned the correct plot. Then I ran `IntegrateLayers()` and it succeeded.

I used to think that the input for ```IntegrateLayers()``` function was `orig.reduction`, so why does `VariableFeatures` matter?"

**Comment by jpvoth** [comment]
Hi - I am not at all an expert on Seurat but have been using it for a couple years and I have a guess as to why you need the FindVariableFeatures() before IntegrateLayers() can work. I suspect that FindVariableFeatures() is essentially the "FindAnchors" step that integration uses. This is a guess, as I know that the integration process itself has verbose that claims it is also finding anchors.

**Comment by MaraLlamas** [comment]
> Hello,
> 
> Sorry about the delay. The issue was caused by the fact I was splitting SCT assay rather than RNA. When I split RNA and then run SCT, it worked fine. Thanks a lot!

Dear @martuskaR thank you for posting this. I had the exact same error and it was driving me crazy!
