### ISSUE TITLE
subset function and layer is mysterious now

### ISSUE THREAD

**Issue by mainyanghr** [satijalab/seurat#8362]
Dear Seurat team.

I have a well established pipeline that was runing well two weeks ago. But suddenly, many steps are getting messy due to the confusing layers.  With the following exact code, I could subset B cells successfully from same object called Allcells. But not the T cell. Any input will be helpful. 
Thanks

`Tcellpure <- subset(Allcells, idents = "T cell")`
Error in methods::slot(object = object, name = "layers")[[layer]][features,  : 
  incorrect number of dimensions

**Comment by Gesmira** [comment]
Hi, 
Sorry, this isn't something we are able to reproduce. 
```
library(SeuratData)
library(Seurat)
pbmc3k <- LoadData('pbmc3k')
pbmc3k$random <- sample(c("a", "b"), nrow(pbmc3k@meta.data), replace = T)
pbmc3k[["RNA"]] <- split(pbmc3k[["RNA"]], f = pbmc3k$random)
Idents(pbmc3k) <- "random"
subset(pbmc3k, idents = "a")
```
Is "T cell" present in the idents of your object? Could you create a reproducible example with `pbmc3k` or provide a small object where this is occuring?

**Comment by mainyanghr** [comment]
Finally, I figured out. Thank you. Because the layers were produced by new Seurat 5.

**Comment by shiau123** [comment]
Hi, i am having the same problem now. Could you kindly tell me how did you fix this problem, please? Many thanks

**Comment by ollieeknight** [comment]
> Hi, i am having the same problem now. Could you kindly tell me how did you fix this problem, please? Many thanks

I think if you rejoin layers, then subset, then resplit them, it works. but it's definitely a bug

**Comment by ollieeknight** [comment]
I think if you rejoin layers, then subset, then resplit them, it works. but it's definitely a bug

**Comment by ollieeknight** [comment]
ah! I think I figured it out. You need to make sure that whatever you're splitting across, not one of the IDs can have 1 cell. It must always be more than 2. For example, if you split across donor_id but one of the donors is only made of one cell.

**Comment by leonfodoulian** [comment]
Hi @Gesmira,

The following code should reproduce the issue:

```r
require(Seurat)
obj <- pbmc_small
obj@meta.data$random <- c("a", "a",
                          sample(x = c("b", "c"),
                                 nrow(x = pbmc_small@meta.data) - 2,
                                 replace = TRUE))
obj[["RNA"]] <- split(x = obj[["RNA"]],
                      f = obj@meta.data$random)
obj.g2 <- subset(x = obj,
                 subset = groups == "g2")
obj.g2.sub <- subset(x = obj.g2,
                     subset = random %in% c("a", "b"))
```

When you subset a `Seurat` object with multiple layers and end up with one of the samples represented by only one cells, you can no longer subset the object any further. The reason is that the corresponding layers will be vectors rather than matrices (dense or sparse).

Best,
Leon

**Comment by Gesmira** [comment]
Hi Leon, 
Thank you for including the reproducible example. Since the original issue was resolved, if you can open a new issue with the example, we can look into it more deeply. Thanks!

**Comment by leonfodoulian** [comment]
> Hi Leon, Thank you for including the reproducible example. Since the original issue was resolved, if you can open a new issue with the example, we can look into it more deeply. Thanks!

Done
