### ISSUE TITLE
How to continue TCR-seq downstream analysis by seurat?

### ISSUE THREAD

**Issue by Lianfuwu** [satijalab/seurat#8366]
I have gotten the Output data that I ran cellrange VDJ pipeline, but I don't know how to continue analyzing the outputs. Which package can go on dealing with downstream analysis as the seurat package can analyze the scRNA-seq data after cellrange deals with it?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  As this isn’t directly Seurat question it is probably better for more general bioinformatics forum.

To start pointing you in the right direction though you can check out this document from 10X Genomics website: https://www.10xgenomics.com/analysis-guides/immune-profiling-analysis-whats-next-after-cell-ranger

Best,
Sam
