### ISSUE TITLE
Recommended worfklow for data integration

### ISSUE THREAD

**Issue by tim-meese** [satijalab/seurat#8367]
Hello

What is the recommended workflow for data integration? In [Introduction to scRNA-seq integration](https://satijalab.org/seurat/articles/integration_introduction) integration is performed with `IntegrateLayers` and directly followed by `JoinLayers`, `FindNeighbors`, `FindClusters` and `RunUMAP`. 
However, in [Integrative analysis in Seurat v5](https://satijalab.org/seurat/articles/seurat5_integration) `JoinLayers` is only called on the end of the sequence: `IntegrateLayers`, `FindNeighbors`, `FindClusters`, `RunUMAP` and `JoinLayers`.

Is there a difference between both sequences of commands? If so, what is the recommend way of performing integration. 

Looking forward to your reply. 

With kind regards
Tim

**Comment by igrabski** [comment]
Hi Tim, as long as you are using the integrated dimension reduction for these steps, it doesn't matter which of the two orders you take.
