### ISSUE TITLE
How to call Seurat object name in for loop?

### ISSUE THREAD

**Issue by kousi31** [satijalab/seurat#8371]
I am new to bioinformatics. I have 12 Seurat objects. I am trying to use for loop on my Seurat objects to calculate the percent mitochondrial genes. But I get an error.

```
obj_names <- list('cov01', 'cov02', 'cov03')

for (i in obj_names){

i[["percent.mt"]] <- PercentageFeatureSet(i, pattern = "^MT-")

 }
```
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "character"

How to call Seurat objects in for loop.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So what you are experiencing is general property of R.

You have created a list of character vectors (i.e. "cov01") which I presume is the name of the Seurat object in your environment.  But the way you have done this R only sees the character vector.

You can use `lapply` to do this easily for a group of Seurat objects in a list.

```
seu_list <- list(obj1, obj2, etc)

seu_list <- lapply(seu_list, function(x) {
  x <- PercentageFeatureSet(x, pattern = "^MT-", col.name = "percent.mt")
})
```

Best,
Sam
