### ISSUE TITLE
Using integrated gene expression values for further analysis (deconvolution)

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8375]
Good morning, 

I have integrated my data using harmony. 
Now I would like to use this integrated data for a deconvolution approach.

So far I have only used my harmony integrated data for clustering, but now I wonder how do I access the integrated counts?! I have read in other approaches they are stored under assay="integrated" (beside the assay "RNA" and assay "SCT"). But there is no assay integrated?!

Can you please clarify?
Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Harmony does not produce batch corrected expression values but is an integration technique that produces correcte embeddings for visualization and integrated assay should not be used for DE.  See this comment for further info (https://github.com/satijalab/seurat/issues/7673#issuecomment-1681223493).

Best,
Sam

**Comment by LeaLe88** [comment]
Dear @samuel-marsh 

Thank you very much for your comment. That clarifies it. 
I understand that I should not use integrated values for DE. However according to this it is recommended to use integrated data in order to build a Signature Matrix for deconvolution:

![image](https://github.com/satijalab/seurat/assets/71077063/f64253ec-1df6-43f5-bbb4-99b7e65fc0a4)

So maybe I need to use a different integration approach in order to get batch corrected expression values which provides them in the "integrated" slot.
Do you know which integration method would be suitable for this?

Thank you!
