### ISSUE TITLE
ScaleData + vars.to.regress using different sets of genes returns identical output

### ISSUE THREAD

**Issue by carmensandoval** [satijalab/seurat#838]
Hi Seurat team,

I'm currently trying out different ways to normalize / scale our data so as to minimize our batch effect and make it possible to compare and cluster cells from different biological samples.

I tried the `vars.to.regress` option within ScaleData, with` vars.to.regress = orig.ident` (sample in my case) , and this already showed significant improvement in terms of sample intermixing.

However, I next wanted to try this regression by sample using only variable genes selected with the `FindVariableGenes` function. I am puzzled because it seems that the output stored in `@scale.data` (for the variable genes) is exactly the same, regardless of whether one tells the function to use a subset of genes or the entire gene set. I have three different sets of 'variable genes'; one obtained by applying the FindVariableGenes function to my "superobject" (a Seurat object made up of 3 different samples), a second gene set, obtained by applying the function to each individual sample, and obtaining the intersection of genes, and a third one, doing the same as before, but in this case getting the union of genes. 

I focused here on comparing the `var.genes.union` and the `var.genes.intersect` sets with the whole gene set.

I've also tried this with the `Seurat::: RegressOutResid( )` as advised [here](https://github.com/satijalab/seurat/issues/618) ,ie, without scaling after regressing out the `orig.ident` variable, and the results are also the same.

Can you pelase help me out why this is happening?

Thank you,

Carmen

1. Using `ScaleData` with ` genes.use` option.
```
scale.data.var.genes <- list()

scale.data.var.genes[["intersection"]] <- ScaleData(superobject,  genes.use = var.genes.intersect, vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 6) %>% .@scale.data

scale.data.var.genes[["union"]] <- ScaleData(superobject,  genes.use = var.genes.union, vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 6) %>% .@scale.data
```

With `var.genes.intersect`:

Regressing out: orig.ident
  |======================================================================| 100%
Time Elapsed:  8.92418384552002 secs

With `var.genes.union`:

Regressing out: orig.ident
  |======================================================================| 100%
Time Elapsed:  15.3900265693665 secs

```{r}
identical(scale.data.var.genes[["intersection"]][var.genes.intersect, ] , scale.data.var.genes[["union"]][var.genes.intersect, ])

identical(scale.data.var.genes[["intersection"]][var.genes.intersect, ], superobject@scale.data[var.genes.intersect, ])
```
TRUE
TRUE

2. Using `ScaleData` with ` data.use` option.
```{r}
scale.data.var.genes <- list()

scale.data.var.genes[["intersection"]] <- ScaleData(superobject, data.use =  superobject@data[var.genes.intersect, ], 
                         vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 8) %>% .@scale.data

scale.data.var.genes[["union"]] <- ScaleData(superobject,  data.use =  superobject@data[var.genes.union, ], vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 8) %>% .@scale.data
```

```{r}
identical(scale.data.var.genes[["intersection"]][var.genes.intersect, ] , 
          scale.data.var.genes[["union"]][var.genes.intersect, ])

identical(scale.data.var.genes[["intersection"]][var.genes.intersect, ], original.superobject.data[var.genes.intersect, ])
```
TRUE
TRUE

```{r}
superobject.data.all.genes <- superobject@data 

scale.data.var.genes <- list()

superobject@data <- superobject.data.all.genes[var.genes.intersect, ]
dim(superobject@data)

scale.data.var.genes[["intersection"]] <- ScaleData(superobject, data.use = superobject@data, 
                         vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 8) %>% .@scale.data


superobject@data <- original.superobject.data[var.genes.union, ]
dim(superobject@data)

scale.data.var.genes[["union"]] <- ScaleData(superobject, data.use = superobject@data, 
                         vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 8) %>% .@scale.data


original.superobject.data -> superobject@data 

scale.data.var.genes[["all.genes"]] <- ScaleData(superobject, data.use = superobject@data, 
                         vars.to.regress = "orig.ident", 
                         do.scale = T, do.center = T, 
                         display.progress = T, do.par = T, num.cores = 8) %>% .@scale.data
```

```{r}
lapply(scale.data.var.genes, dim)
```
$intersection
[1]   479 49500

$union
[1]  2694 49500

$all.genes
[1] 16399 49500

```{r}
identical(scale.data.var.genes[["intersection"]][var.genes.intersect, ] , 
          scale.data.var.genes[["union"]][var.genes.intersect, ],
          scale.data.var.genes[["all.genes"]][var.genes.intersect, ])
```
[1] TRUE

3. Applying `RegressOutResid` option as advised in link above, with `genes.regress` option:
```{r}
#Get data with regression
vars.to.regress = "orig.ident"
regress.data.var.genes <- list()

superobject@data <- superobject.data.all.genes[var.genes.intersect, ]
dim(superobject@data)

regress.data.var.genes[["intersect"]] <- Seurat:::RegressOutResid(
            object = superobject,
            vars.to.regress = vars.to.regress,
            genes.regress =  var.genes.intersect,
            use.umi = FALSE,
            model.use = 'linear',
            display.progress = TRUE,
            do.par = TRUE,
            num.cores = 8
      )    

superobject@data <- superobject.data.all.genes[var.genes.union, ]
dim(superobject@data)

regress.data.var.genes[["union"]] <- Seurat:::RegressOutResid(
            object = superobject,
            vars.to.regress = vars.to.regress,
            genes.regress = var.genes.union,
            use.umi = FALSE,
            model.use = 'linear',
            display.progress = TRUE,
            do.par = TRUE,
            num.cores = 8
      )   

superobject@data <- superobject.data.all.genes
dim(superobject@data)

regress.data.var.genes[["all.genes"]] <- Seurat:::RegressOutResid(
            object = superobject,
            vars.to.regress = vars.to.regress,
            use.umi = FALSE,
            model.use = 'linear',
            display.progress = TRUE,
            do.par = TRUE,
            num.cores = 8
      )   
    
lapply(regress.data.var.genes, dim)
```
$intersect
[1]   479 49500

$union
[1]  2694 49500

$all.genes
[1] 16399 49500

```{r}
identical(regress.data.var.genes[["intersect"]][var.genes.intersect, ] , 
          regress.data.var.genes[["union"]][var.genes.intersect, ],
          regress.data.var.genes[["all.genes"]][var.genes.intersect, ])
```
[1] TRUE

**UPDATE:** I have also tried converting `superobject@meta.data$orig.ident` to a factor, to no avail. The output after regressing out `orig.ident` is still identical with `var.genes.union` and `var.genes.intersect` . 😔

`superobject@meta.data$orig.ident <- factor(superobject@meta.data$orig.ident)`

**Comment by 2236529177** [comment]
have you ever tried cellranger aggr.
is there anywhere said seurat can deal with batch effect

**Comment by andrewwbutler** [comment]
Hi Carmen,

In the examples you outline above, scaling is performed per gene (i.e. each gene is scaled independently) so providing different sets of genes to `ScaleData` will only change which genes are scaled, not the results for any particular gene. That's why when you subset the results at the end to include genes scaled in all sets, you get identical results.

**Comment by thetapper** [comment]
Hi @2236529177, 

_cellranger aggr_ is possible to use but it simply downsamples your data which will likely reduce your data quality and also not account for specific batch effects.

Seurat offers as far as I know two options to deal with batch effects:

1. Alignment:
https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html
http://satijalab.org/seurat/Seurat_AlignmentTutorial.html

2. Regression:
> ScaleData(.., vars.to.regress=x)
