### ISSUE TITLE
install seurat V5  get error 'memory not mapped'

### ISSUE THREAD

**Issue by wow123yf** [satijalab/seurat#8380]
hi   I installing V4.4.0 and everything is fine，but when I installed V5.0.1 I got the following error message
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 19877 Segmentation fault      (core dumped) R_TESTS= '/opt/R/4.3.2/lib/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpkV4VA8/file497c75ea3cce'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

23: tools:::makeLazyLoading("Seurat", "/home/u1/R/x86_64-pc-linux-gnu-library/4.3/00LOCK-Seurat/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/home/u1/R/x86_64-pc-linux-gnu-library/4.3/Seurat")
An irrecoverable exception occurred. R is aborting now ...
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/home/u1/R/x86_64-pc-linux-gnu-library/4.3/Seurat’

The downloaded source packages are in
	‘/tmp/RtmpRvcYOa/downloaded_packages’
Warning message:
In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status

> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so;  LAPACK version 3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.3.2 tools_4.3.2

I updated all packages according to the previous issue
> packageVersion("RcppAnnoy")
[1] ‘0.0.22’

**Comment by longmanz** [comment]
Hi,
Are you directly installing the Seurat from CRAN or from GitHub? Can you also show us the sessionInfo()?

**Comment by wow123yf** [comment]
I directly installing the Seurat from CRAN ，

```
sessionInfo() 
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so;  LAPACK version 3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.3.2
```

**Comment by longmanz** [comment]
Hi, 
This is strange and we would suggest you installing it from the source (you can download it from CRAN or our Github) to see if the issue persists?

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if problems still occur.

**Comment by teng-gao** [comment]
I have same issue ..
