### ISSUE TITLE
Process killed when trying to merge 20 multiomics samples

### ISSUE THREAD

**Issue by ScienceBear** [satijalab/seurat#8384]
Hi all,

I'm attempting to merge 20 10X multiomics samples, each with roughly 10,000 nuclei, so I can integrate them into one object in order to unify the snATAC peaks using GenomicRanges. The merge function runs for a little while and then the session is aborted in RStudio. It's also killed in base R. I'm running this in an interactive session on an HPC with a 100 Gb RAM ceiling. I'm sharing my code structure below (I've replaced each of my sample IDs with "Object" here) just in case someone sees something I haven't. Recently finished a project and updated to Seurat v5: it is taking me some time to get to grips with and there may be some recent "features" which are causing issues.

```
library(Seurat)
library(Signac)
library(EnsDb.Mmusculus.v79)
library(BSgenome.Mmusculus.UCSC.mm10)
library(ggplot2)
library(cowplot)
library(clustree)

set.seed(4444)

# For each sample
countsObject<- Read10X_h5("Object.h5")
fragpathObject <- "Object_atac_fragments.tsv.gz"

# For each sample
ObjectSeurat <- CreateSeuratObject(
  counts = countsObject$`Gene Expression`,
  assay = "RNA")
  
# For each sample
ObjectSeurat [["ATAC"]] <- CreateChromatinAssay(
  counts = countsObject$Peaks,
  sep = c(":", "-"),
  fragments = fragpathObject,
  annotation = annotation
)  
# Merge (crashes here)
Object_merged <- merge(x = ObjectSeurat, y = c(ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat, ObjectSeurat), add.cell.ids = c("Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object", "Object"))
```

**Comment by TeodoraTockovska** [comment]
Hi! From my experience, single cell multiome analyses require a lot of computational power. 100 GB does not sound like enough RAM for 20 sc-multiome samples. Moreover, integrating sc-multiome samples is not as simple as your code above. If your goal is to integrate the snATAC data, you will need to combine the data based on common peak sets, as specified here: https://stuartlab.org/signac/articles/merging 

Here is a good discussions page on the topic: https://github.com/stuart-lab/signac/discussions/438
