### ISSUE TITLE
Cells plotted outside of image in 10X spatial data

### ISSUE THREAD

**Issue by sallyseullee-0821** [satijalab/seurat#8386]
I am currently working with 10X spatial data and when plotting the cells on the spatial data, I observe that three spots are appearing outside of the intended image boundaries. The plot generated is attached. 
[S1L-counts-distribution.pdf](https://github.com/satijalab/seurat/files/14073896/S1L-counts-distribution.pdf)

I would appreciate any guidance or advice on how to resolve this issue. Is there a known bug or a common mistake that might lead to this problem? 

The code I used: 
```
seurat <- Load10X_Spatial(dir, filename, assay = "Spatial", slice = "slice1", filter.matrix = TRUE, to.upper = FALSE)

plot1 <- VlnPlot(S1L, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
plot2 <- SpatialFeaturePlot(S1L, features = "nCount_Spatial") + theme(legend.position = "right")
wrap_plots(plot1, plot2)
dev.off()
```

Thank you in advance for your help.

Sally

**Comment by longmanz** [comment]
Hi, 
This seems to be an issue with the coordinates provided from the 10X end, instead of a bug from Seurat. If you apply standard QC to your dataset, it is likely you will remove the 3 cells.
