### ISSUE TITLE
Unable to use pseudobulk analysis for two samples per condition

### ISSUE THREAD

**Issue by Zack-G-123** [satijalab/seurat#8389]
I am attempting to use pseudobulk analyses with DESeq2 for DE analysis, however I current have 2 control samples and 2 experimental samples. Thus, to compare any individual cluster across conditions, I am using 2 "cells" for each group. This leads to an error stating there is a minimum of 3 cells per group when running `FindMarkers()` with `test.use = 'DESeq2'` 

However, from what I understand, this is not an inherent limit on the DESeq2 side, which normally could run with 2 samples per group at the cost of significantly reduced statistical power. Is there a way to bypass this check during `FindMarkers`?

**Comment by longmanz** [comment]
Hi, 
You can modify the `min.cells.group = 3` to other number (e.g., 2) when running FindMarkers().
