### ISSUE TITLE
Scaledata vars.to.regress

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#839]
I read the instructions of seurat and you outstanding paper "Integrating single-cell transcriptomic data across different conditions, technologies, and species". 
In the ONLINE METHODS of the paper, it mentioned several times of regress out. so when it comes to individual-specific, how should set the param, and can you give a more detailed process of the cell cycle score you need to regress out in the (We then used the ScaleData function in Seurat
(using the cell cycle score as latent variable in a linear regression framework)
to mitigate this source of variation in the data set, before CCA)
{
vars.to.regress
Variables to regress out (previously latent.vars in RegressOut). For example,
nUMI, or percent.mito.
}

![image](https://user-images.githubusercontent.com/25199946/46783906-a1349d80-cd5e-11e8-94e7-6c78350ecb9f.png)

thanks a lot

**Comment by 2236529177** [comment]
I can there are five fastq,gz in EBI, this sequenced in paried-end, why not have R_1, R_2 file(paired-end should have 2 files). is it convenient for you to tll me how to obtain a unique molecular identifier (UMI) count matrix for the Kang et al( immune_control_expression_matrix.txt.gz  and immune_stimulated_expression_matrix.txt.gz, how you get this, because after cellranger count there is no file like this)
![image](https://user-images.githubusercontent.com/25199946/46784478-d510c280-cd60-11e8-8fe7-71088a9e3148.png)

thanks a lot.

**Comment by 2236529177** [comment]
you also mentioned regressed out mitochondrial heterogeneity from each data set before running CCA. I think these two factors should be common for all samples, so I think they should set to param vars.to.regress, so should we pass a list or vector to vars.to.regress, is it convenient for you to give more examples.
thanks a lot

![image](https://user-images.githubusercontent.com/25199946/46785671-173c0300-cd65-11e8-9070-489212949f8d.png)

**Comment by satijalab** [comment]
Hello - we regressed out mitochondrial as demonstrated in the PBMC3k tutorial on the website. Our cell cycle analysis, is demonstrated on our website in the cell cycle vignette. Lastly, we obtained the expression matrices from the authors of the original manuscript, who kindly sent them to us.

**Comment by 2236529177** [comment]
> Hello - we regressed out mitochondrial as demonstrated in the PBMC3k tutorial on the website. Our cell cycle analysis, is demonstrated on our website in the cell cycle vignette. Lastly, we obtained the expression matrices from the authors of the original manuscript, who kindly sent them to us.

yeah, so I am wondering how to select regress out element, si there any basic elements, such nGene, nUMI, mito, you know, to carry out a workflow, I need to find out basic elements, thanks a lot
