### ISSUE TITLE
Error in FindTransferAnchors()

### ISSUE THREAD

**Issue by sarahshuang** [satijalab/seurat#8390]
I used R4.2.1 in Rstudio on Mac system (Apple M1)

```r
# # load data
E8.5.2 = readRDS("/Users/sarah/Desktop/Cai/E7.5_E9.5/GSM7979961-E8.5.1-2/GSM7979961_E8.5.2.bin50.rds")
CellType = readRDS("/Users/sarah/Downloads/UE.harmony.pc30-web-diet.rds")


library(Seurat)

E8.5.2@meta.data[1:11578,] <- NA
E8.5.2@meta.data[["seurat_clusters"]] = as.character(E8.5.2@active.ident)

# because CellType is not SCT assay, we need transform
E8.5.2@assays[["SCT"]]@counts = E8.5.2@assays[["SCT"]]@data
CellType@assays[["RNA"]]@counts = CellType@assays[["RNA"]]@data
CellType = SCTransform(CellType, assay = "RNA", new.assay.name = "SCT")

# Identify variable features in each dataset
reference.features <- FindVariableFeatures(CellType)

# Find the intersection of variable features
common.features <- intersect(CellType@assays[["SCT"]]@var.features, E8.5.2@assays[["SCT"]]@var.features)

# Find transfer anchors using common features
anchors <- FindTransferAnchors(CellType, E8.5.2, features = common.features, recompute.residuals = FALSE, 
                               normalization.method = 'SCT', dims = 1:30)

# Transfer labels from the reference to the query dataset
query <- TransferData(reference, query, anchors, dims = 1:30)

SpatialPlot(E8.5.2, group.by = "celltype") 

```
Then the error appeared.
```
Warning: 230 features of the features specified were not present in both the reference query assays. 
Continuing with remaining 0 features.
Error: No features to use in finding transfer anchors. To troubleshoot, try explicitly providing features to the features parameter and ensure that they are present in both reference and query assays.
```
<img width="831" alt="截屏2024-01-29 15 09 49" src="https://github.com/satijalab/seurat/assets/105658106/046ac549-4057-4705-9eaa-2f6938a5c6cb">

<img width="829" alt="截屏2024-01-29 15 10 18" src="https://github.com/satijalab/seurat/assets/105658106/1a98c688-a749-42dc-8d02-8e81c270f665">

The common.feature include 230 features which are intersections of reference and query datasets, so I was confused as to why it couldn't find the common features.

**Comment by sarahshuang** [comment]
I want the function to go in var.features but it seems the function cannot find var.features in both ref and query datasets. Could you please teach me how can I fix it?

**Comment by saketkc** [comment]
Hi @sarahshuang, you are doing  a few steps that I do not think are necessary, but happy to take a look at the objects if you can share them with me. schoudhary@nygenome.org

**Comment by sarahshuang** [comment]
> Hi @sarahshuang, you are doing a few steps that I do not think are necessary, but happy to take a look at the objects if you can share them with me. [schoudhary@nygenome.org](mailto:schoudhary@nygenome.org)

Sure. I sent these public datasets to your email address, titled "issue#8390 Error in FindTransferAnchors()". Thanks for your help so much in advance!

**Comment by saketkc** [comment]
Hi @sarahshuang,

Your `Celltype` object is log normalized (there is no counts information in the `Celltype@assays$RNA@counts` slot however), so I would recommend using log normalization workflow in this case.

![image](https://github.com/satijalab/seurat/assets/682153/8e2aec30-b3ad-4708-af63-b5b0b31372b1)

**Comment by sarahshuang** [comment]
> Hi @sarahshuang,
> 
> Your `Celltype` object is log normalized (there is no counts information in the `Celltype@assays$RNA@counts` slot however), so I would recommend using log normalization workflow in this case.


Yes. However, E8.5.2 is SCT transformed. Okay, thanks. I will keep trying to find out how to solve it.
