### ISSUE TITLE
Unable to run DESeq2

### ISSUE THREAD

**Issue by yesitsjess** [satijalab/seurat#8393]
I'm having some difficulty using DESeq2 as my FindMarkers method.

When I run Wilcoxon rank sum it works fine:
`wilcox <- FindMarkers(obj, ident.1="group1", ident.2="group2", test.use="wilcox")`

But when I run DESeq2 I get an error:
`deseq2 <- FindMarkers(obj, ident.1="group1", ident.2="group2", test.use="DESeq2")`
```
Setting slot to counts for DESeq2 (counts based test: 
Error in CheckDots(..., fxns = "DESeq2::results") : 
  None of the functions passed could be found
```

R version 4.2.3 
Seurat_5.0.1 
DESeq2_1.38.3

**Comment by saketkc** [comment]
Hi @yesitsjess, can you update to the latest version of BioC and DESeq2 and open a new issue if you still get this error?

```r
BiocManager::install(version = "3.18")
BiocManager::install("DESeq2")

```
