### ISSUE TITLE
Error in FetchData : trying to convert the ENSEMBL gene ids to gene symbols and add a metadata

### ISSUE THREAD

**Issue by HappinessEricst** [satijalab/seurat#8394]
hi please i encountered a problem which keeps giving me an error. Here is the code i wrote:
receptor.df <- FetchData(object = ha.obj, vars=receptor.names, slot="counts")

Here is the error i keep having
Error in FetchData.Seurat(object = ha.obj, vars = receptor.names, slot = "counts") : None of the requested variables were found

please can anyone help me out. I am trying to convert the ENSEMBL gene ids to gene symbols and add a metadata.

**Comment by igrabski** [comment]
Hi, I'm not sure what's causing the error without more information about your object or `receptor.names`, but the error suggests that the variables within `receptor.names` are not found in your data. That said, if you are just trying to convert the gene names from ENSEMBL ids to symbols, you may find the [`ConvertGeneNames()`](https://satijalab.github.io/azimuth/reference/ConvertGeneNames.html) function from `Azimuth` helpful.
