### ISSUE TITLE
sketch integration arguments don't make snese

### ISSUE THREAD

**Issue by bankhead3** [satijalab/seurat#8396]
In https://satijalab.org/seurat/articles/parsebio_sketch_integration arguments for ProjectData have the same reduction listed for sketched and full.  Also, is ProjectIntegration call reduction argument correct?  Isn't this the same reduction used for sketch?
Please advise.  
Armand

![image](https://github.com/satijalab/seurat/assets/31142967/aad07490-2327-45a0-a07d-1e2cf8523574)

**Comment by Gesmira** [comment]
Hi, 
This has been asked about and explained in more detail here:  https://github.com/satijalab/seurat/issues/7681
If the parameters continue to be confusing, we will flag this and potentially update them or improve documentation. Let me know if you continue to have questions.
