### ISSUE TITLE
Downsampling of Seurat object makes RNA Assay undetectable

### ISSUE THREAD

**Issue by annemarijnkramer** [satijalab/seurat#8397]
Hi, 

I've run into a new issue with Seurat v5 when downsampling a Seurat object. 

I have a dataobject with 70 samples included, which I would like to downsample to 500 cells per sample for downstream analysis ease on a local computer before running the script on the total object, by using the following code: 

mx_500 <- subset(mx, downsample = 500)

However, after doing so the RNA Assay is not recognized for further downstream analysis. When looking at the object this is what is reported: 

An object of class Seurat 
22366 features across 35000 samples within 2 assays 
Active assay: SCT (22320 features, 3000 variable features)
 1 other assay present: ADT 

However, looking for RNA specifically it just seems to be stored as an Assay5 object rather than Assay. 
> class(mx_500 [["RNA"]])
[1] "Assay5"
attr(,"package")
[1] "SeuratObject"
> class(mx_500 [["ADT"]])
[1] "Assay"
attr(,"package")
[1] "SeuratObject"
> class(mx_500 [["SCT"]])
[1] "SCTAssay"
attr(,"package")
[1] "Seurat"

Trying to convert this by using the following code:
> mx_500 [["RNA"]] <- as(object = mx_500 [["RNA"]], Class = "Assay")

Error in as(object = mx_500 [["RNA"]], Class = "Assay") : 
  no method or default for coercing "Assay5" to "Assay"

Could you please help me with retrieving the RNA Assay so that it is recognized for further downstream analysis.

Thank you 

SessionInfo() R version 4.2.1 (2022-06-23 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 22621)  Matrix products: default  locale: [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 [4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] future.apply_1.11.1   future_1.33.1         SeuratDisk_0.0.0.9020 SeuratObject_4.1.3    Seurat_4.3.0          scales_1.3.0           [7] rstatix_0.7.2         ggplot2_3.4.4         dplyr_1.1.2           data.table_1.14.8     reshape2_1.4.4         loaded via a namespace (and not attached):   [1] backports_1.4.1             systemfonts_1.0.5           plyr_1.8.8                  igraph_1.4.3                  [5] lazyeval_0.2.2              sp_1.6-1                    splines_4.2.1               BiocParallel_1.30.4           [9] listenv_0.9.0               scattermore_1.1             usethis_2.2.1               GenomeInfoDb_1.32.4          [13] digest_0.6.31               htmltools_0.5.7             fansi_1.0.4                 magrittr_2.0.3               [17] memoise_2.0.1               tensor_1.5                  cluster_2.1.3               ROCR_1.0-11                  [21] tzdb_0.3.0                  remotes_2.4.2               globals_0.16.2              readr_2.1.4                  [25] matrixStats_1.0.0           spatstat.sparse_3.0-1       colorspace_2.1-0            ggrepel_0.9.3                [29] textshaping_0.3.6           crayon_1.5.2                RCurl_1.98-1.12             jsonlite_1.8.5               [33] progressr_0.14.0            spatstat.data_3.0-1         survival_3.5-5              zoo_1.8-12                   [37] glue_1.6.2                  polyclip_1.10-4             gtable_0.3.4                zlibbioc_1.42.0              [41] XVector_0.36.0              leiden_0.4.3.1              DelayedArray_0.22.0         car_3.1-2                    [45] pkgbuild_1.4.3              SingleCellExperiment_1.20.0 BiocGenerics_0.44.0         abind_1.4-5                  [49] spatstat.random_3.1-5       miniUI_0.1.1.1              Rcpp_1.0.10                 viridisLite_0.4.2            [53] xtable_1.8-4                reticulate_1.29             bit_4.0.5                   stats4_4.2.1                 [57] profvis_0.3.8               htmlwidgets_1.6.4           httr_1.4.7                  RColorBrewer_1.1-3           [61] ellipsis_0.3.2              ica_1.0-3                   farver_2.1.1                urlchecker_1.0.1             [65] pkgconfig_2.0.3             scuttle_1.6.3               uwot_0.1.14                 deldir_1.0-9                 [69] utf8_1.2.3                  labeling_0.4.3              tidyselect_1.2.0            rlang_1.1.1                  [73] later_1.3.1                 munsell_0.5.0               tools_4.2.1                 cachem_1.0.8                 [77] cli_3.4.1                   generics_0.1.3              broom_1.0.5                 devtools_2.4.5               [81] ggridges_0.5.5              stringr_1.5.1               fastmap_1.1.1               ragg_1.2.5                   [85] goftest_1.2-3               bit64_4.0.5                 fs_1.6.3                    fitdistrplus_1.1-11          [89] purrr_1.0.1                 RANN_2.6.1                  pbapply_1.7-2               nlme_3.1-157                 [93] sparseMatrixStats_1.10.0    mime_0.12                   hdf5r_1.3.8                 compiler_4.2.1               [97] rstudioapi_0.14             plotly_4.10.3               png_0.1-8                   spatstat.utils_3.0-3        [101] tibble_3.2.1                stringi_1.7.12              lattice_0.20-45             Matrix_1.5-4.1              [105] vctrs_0.6.2                 pillar_1.9.0                lifecycle_1.0.4             spatstat.geom_3.2-1         [109] lmtest_0.9-40               RcppAnnoy_0.0.20            cowplot_1.1.2               bitops_1.0-7                [113] irlba_2.3.5.1               httpuv_1.6.11               patchwork_1.2.0             GenomicRanges_1.48.0        [117] R6_2.5.1                    promises_1.2.0.1            KernSmooth_2.23-20          gridExtra_2.3               [121] IRanges_2.30.1              parallelly_1.36.0           sessioninfo_1.2.2           codetools_0.2-18            [125] MASS_7.3-57                 pkgload_1.3.3               SummarizedExperiment_1.26.1 withr_2.5.2                 [129] sctransform_0.3.5           S4Vectors_0.34.0            GenomeInfoDbData_1.2.9      hms_1.1.3                   [133] parallel_4.2.1              grid_4.2.1                  beachmat_2.14.0             tidyr_1.3.0                 [137] DelayedMatrixStats_1.20.0   carData_3.0-5               MatrixGenerics_1.8.1        Rtsne_0.16                  [141] spatstat.explore_3.2-1      Biobase_2.56.0              shiny_1.8.0
--
 
> | >
>

</body>
</html>
```
![image](https://github.com/satijalab/seurat/assets/116310784/829d8adf-4692-417a-b594-3ea7856f6d72)

**Comment by annemarijnkramer** [comment]
Because I have performed SCTransformation on the 70 samples included that have been merged into 1 dataset I would like to PrepSCT integration as follows: 

mx.list <- SplitObject(mx_500, split.by = "sample") 
features <- SelectIntegrationFeatures(object.list = mx.list, nfeatures = 3000)
 mx.list <- PrepSCTIntegration(object.list = mx.list, anchor.features = features)

However the error that comes back then is: 
Warning: The umi assay (RNA) is not present in the object. Cannot compute additional residuals.

**Comment by saketkc** [comment]
Hi @annemarijnkramer based on your ouput, it seems your RNA assay was not present before subsetting? I am not able to reproduce this with `pbmc_small`

```r
pbmc <- SCTransform(pbmc_small)
z <- subset(pbmc, downsample=2)
> z
An object of class Seurat 
450 features across 6 samples within 2 assays 
Active assay: SCT (220 features, 220 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, tsne
```

**Comment by saketkc** [comment]
Also, it seems your object was made using SeuratV5 but you only have Seurat4 installed.
