### ISSUE TITLE
which dataset should be used to Subgroup analysis？ Integrated or RNA? 

### ISSUE THREAD

**Issue by myoucchent** [satijalab/seurat#8398]
Cell subsets were extracted by subset, and dimension reduction clustering was performed again. Which dataset should to be used to do ' NormalizeData', 'FindVariableFeatures', 'ScaleData', Reduction and clustering?

**Comment by cgoneill** [comment]
My understanding is that the integrated assay is intended for use in dimension reduction and clustering without running `NormalizeData()`, `FindVariableFeatures()`, or `ScaleData()` on it. Historically, it hasn't been recommended to run those on the integrated assay. I think the current recommendation is to use the integrated assay for this, but rerunning `NormalizeData()` and `FindVariableFeatures()` shouldn't be necessary - see #2539 and #4675.

**Comment by Gesmira** [comment]
Yep, this has been addressed previously and the explanation provided by @cgoneill above is correct. However, if you want variable features that are more specific to the subset, you can rerun `FindVariableFeatures` and either way should rerun `ScaleData` on the `RNA` assay. You can then redo the dimensional reduction and clustering in your subset on the `integrated` assay.
