### ISSUE TITLE
error while integration

### ISSUE THREAD

**Issue by imrjesh** [satijalab/seurat#8400]
While integrating few sample, i got this error
Error in irlba(A = t(x = object), nv = npcs, ...): max(nu, nv) must be strictly less than min(nrow(A), ncol(A))
The code which i am using is this 
file1 <- readRDS("~/file1_processed.rds")
file2 <- readRDS("~/file2_processed.rds")
file3 <- readRDS("~/file3_processed.rds")
Seuratlist <- list(file1, file2, file3)
saveRDS(Seuratlist, "~/Integrated_SeuratObj_2.rds")
# The “variable features” (genes) were identified and normalized
Seuratlist <- readRDS(~/Integrated_SeuratObj_2.rds")
Seuratlist <- lapply(X = Seuratlist, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2500)
})
# Then features that were repeatedly variable across datasets were selected as a basis for the integration
features <- SelectIntegrationFeatures(object.list =Seuratlist)
Seuratlist <- lapply(X = Seuratlist, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

anchors <- FindIntegrationAnchors(object.list = Seuratlist, 
                                         anchor.features = features,
                                         reduction = "rpca")

Seurat.combined <- IntegrateData(anchorset = anchors)
#DefaultAssay(Seurat.combined) <- "integrated"
Seurat.combined <- ScaleData(Seurat.combined, verbose = FALSE)
Seurat.combined <- RunPCA(Seurat.combined, npcs = 20, verbose = FALSE)
Seurat.combined <- RunUMAP(Seurat.combined, reduction = "pca", dims = 1:20)
Seurat.combined <- FindNeighbors(Seurat.combined, reduction = "pca", dims =1:20)
Seurat.combined <- FindClusters(Seurat.combined, resolution = 1)
saveRDS(Seurat.combined, "~/Seurat_combined_new.rds")

**Comment by Gesmira** [comment]
Hi, 
Are you getting this error in the integration step or in RunPCA? 
Here is a relevant issue. https://github.com/satijalab/seurat/issues/1914
If you continue to run into problems, please share the specific line that causes the issue.

**Comment by Gesmira** [comment]
Closing now due to lack of response. Feel free to reopen if you continue to run into problems. Thanks!
