### ISSUE TITLE
ProjectData meeting error: 

### ISSUE THREAD

**Issue by yanwuanxin** [satijalab/seurat#8402]
the following code, using harmony rm to batch, will encounter errors：
`
pro <- IntegrateLayers(
  object = pro,
  method = "HarmonyIntegration",
  orig.reduction = "pca", 
  new.reduction = "harmony",
  verbose = FALSE
)

pro <- RunUMAP(pro, reduction = "harmony", dims = 1:dim, return.model = T, reduction.name = ""sketch_umap"", reduction.key = ""sketchUMAP_"")

pro <- ProjectData(
  object = pro,
  assay = "RNA",
  full.reduction = "harmony.full",
  sketched.assay = "sketch",
  sketched.reduction = "harmony",
  umap.model = "sketch_umap",
  dims = 1:20,
  refdata = list(cluster = "seurat_clusters")
)
`

`
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 't': no applicable method for 'as.sparse' applied to an object of class "c('double', 'numeric')"
`

this error appears because there is no data available in `pro@reductions$harmony@feature.loadings`; before running the `ProjectData`, run the following code can fix errors:
`
feature.harmony <- pro@reductions$pca@feature.loadings
colnames(feature.harmony) <- str_c("harmony_", seq(1:dim))
pro@reductions$harmony@feature.loadings <- feature.harmony
`
although the above code can fix the error, I think it is more reasonable to fix it in IntegrateLayers( or in HarmonyIntegration )

**Comment by dcollins15** [comment]
Can you please try running `ProjectIntegration` before `ProjectData` (per the sketch-integration [vignette](https://satijalab.org/seurat/articles/parsebio_sketch_integration)) and let us know if that resolves your issue 🙂

**Comment by yanwuanxin** [comment]
running ProjectIntegration before ProjectData can solve this issue. the result of umap of sketch data and full data has significant difference follow [this case](https://satijalab.org/seurat/articles/parsebio_sketch_integration), i have another question: [in this case](https://satijalab.org/seurat/articles/parsebio_sketch_integration) after runing `ProjectData` do not runing `RunUMAP` is it reasonable?

my test result of harmony:
![image](https://github.com/satijalab/seurat/assets/61311726/08e9c043-a103-45fb-ae6a-30c5ecc5a367)

**Comment by Gesmira** [comment]
Hi @yanwuanxin, 
No, you do not have to call `RunUMAP` again once the sketched UMAP has been projected to the full object. 

@rschauner thank you for your comments! We are actively working on improving integration documentation.
