### ISSUE TITLE
Determine dimensionality dataset after integration in Seurat V5

### ISSUE THREAD

**Issue by tim-meese** [satijalab/seurat#8403]
Hello Seurat Team

I want to ask a follow up question about [issue 8274](https://github.com/satijalab/seurat/issues/8274). 
In Seurat V4, I would call RunPCA after the integration and afterwards determine the dimensionality of the dataset by investigating the elbowplot. The elbowplot gave me the number of principal components I want to retain. I used this information in RunUMAP, FindNeighbors and FindClusters.

In Seurat V5 this approach does not work anymore for the reason highlighted here. Is there a way to replicate this workflow in Seurat V5?
My first idea was creating the elbowplot after calling RunPCA and providing the number principal components I want to retain (nPC) to the IntegrateLayers(, dims=1:nPCs). But I am not sure if this correct.
Or is it not needed to "optimize" the number if principal components here?

Thanks in advance and appreciating the input.

With kind regards
Tim

**Comment by igrabski** [comment]
Hi Tim, yes you can pass the number of principal components you want to use into `IntegrateLayers`. The exact argument you should use depends on the integration method you want to use. For example, you would use `dims` as in your example for `CCAIntegration`, but `npcs` for `HarmonyIntegration`, and so on. You can see the available integration functions and then look at their respective documentations at the bottom [here](https://satijalab.org/seurat/reference/integratelayers).

**Comment by tim-meese** [comment]
@igrabski , thank you for your explanation.

Does my proposed strategy, i.e. determining the relevant number of principal components on the merged object by an elbowplot sounds sensible? I fear that using too many PCs for integration will introduce noise.

Curious to know what you think.

**Comment by igrabski** [comment]
Hi Tim, yes, an elbow plot would be one sensible way to choose the number of PCs!
