### ISSUE TITLE
Find markers after integration of samples of the same type

### ISSUE THREAD

**Issue by g-pinel** [satijalab/seurat#8410]
Dear Seurat developers, I've seen multiples posts that explain that you should perform DE between conditions using the original data and not the integrated data because the integration process could interfere with the differences between those conditions (e.g. stim vs ctrl).

However, I want to integrate samples **of the same kind** from two different studies (healthy1 + healthy2) just to have more cells and then find markers between cell types. In this case in which the two original datasets contain the same kind of samples, is it correct to run FindMarkers() using the integrated data? Or would it still be better to use the un-integrated assay?

Thanks in advance

**Comment by longmanz** [comment]
Hi,
Please use the un-integrated (e.g., "RNA") assay to perform DE analysis. Even if the 2 samples are from the same kind, integration process will distort the the counts which are no longer suitable for DE analysis. In fact, in Seurat v5, there is no longer an "integrated" assay stored anymore after integration.

**Comment by g-pinel** [comment]
Thanks!
