### ISSUE TITLE
Is it okay to run SCTransform on normalized seurat object?

### ISSUE THREAD

**Issue by zelliesn** [satijalab/seurat#8411]
It it okay to run SCTransform on a Seurat object that is already normalized? For some reason when I check seuratobject@assays$RNA$counts, the values are normalized too (and is equal to seuratobject@assays$RNA$data). I'm not sure if it is valid to run SCTransform on this data? Thank you.

**Comment by saketkc** [comment]
Have you plotted the mean-variance relationship on your `counts` and `data` slots to see if they are actually counts (unnormalized) or log normalized? If they are counts, yes you can run SCTransform.
