### ISSUE TITLE
PercentAbove includes NA's as if above threshold

### ISSUE THREAD

**Issue by molecules** [satijalab/seurat#8412]
Heads up, I found out that if NAs are included, then they are counted as above the threshold.

For example, I would expect that given one value at the threshold and some NAs, that the "PercentAbove" would return 0. However, as you can see, the following code counts all NAs as being above the threshold.

```
> a <- c(1, NA, NA)
> PercentAbove(a, threshold = 1)
[1] 0.6666667
```

https://github.com/satijalab/seurat/blob/41d19a8a55350bff444340d6ae7d7e03417d4173/R/utilities.R#L1129-L1131

**Comment by longmanz** [comment]
Hi,
Thank you for pointing this out. This is indeed a bug, and it could potentially affect DotPlot(). We will fix it.

**Comment by Gesmira** [comment]
Hi, 
This is now resolved in the most recent version of Seurat. Please feel free to reopen if you continue to run into any problems. Thanks!
