### ISSUE TITLE
Weird scale when FeaturePlot used with viridis

### ISSUE THREAD

**Issue by colin893** [satijalab/seurat#8416]
Hi,

I have never faced any trouble so first time I comment, but I run out of idea. I've used Seurat for the two last years and everything's fine. However, recently, a function I used doesn't behave the same way as usual (I updated some packages without noticing, I guess it might be the problem).

I used to plot transcript percentage expression for feature and plot with FeaturePlot() in conjunction with viridis color to add some contrast. The scale would be from 100% of maximum expression found in cells, and 0 or at least the lowest existing.

I still can compute the PercentageFeatureSet, but just the scale is blocked between 1 and 2. I tried so download old Seurat/viridis releases but changed nothing, maybe you will have an idea?

```r

int2NoMEDiet<-readRDS("scripts/RDS/int2NoMEDiet.rds")
DefaultAssay(int2NoMEDiet)<-"RNA"
int2NoMEDiet[["ctrb1.Score"]] <- PercentageFeatureSet(int2NoMEDiet, features = "ctrb1")
max(int2NoMEDiet[["ctrb1.Score"]]) # 29.47
min(int2NoMEDiet[["ctrb1.Score"]]) # 0
FeaturePlot(int2NoMEDiet, "ctrb1.Score", order = T, label.size = 3, pt.size = 0.5) # scale between 0 and 30%
FeaturePlot(int2NoMEDiet, "ctrb1.Score", order = T, label.size = 3, pt.size = 0.5, cols = viridis(100, option = "A"))  # scale between 1 and 2


```
FeaturePlot(int2NoMEDiet, "ctrb1.Score", order = T, label.size = 3, pt.size = 0.5) # scale between 0 and 30% ## result >
![image](https://github.com/satijalab/seurat/assets/50266955/0cc160c9-7611-4fe8-9d97-2a27cf7841a2)
FeaturePlot(int2NoMEDiet, "ctrb1.Score", order = T, label.size = 3, pt.size = 0.5, cols = viridis(100, option = "A"))  # scale between 1 and 2 ## result >
![image](https://github.com/satijalab/seurat/assets/50266955/69474c44-a4d7-416d-8213-c1e73ff702ec)

**Comment by longmanz** [comment]
Hi, 
You will need to pass it with ggplot2::scale_colour_gradientn(). Directly setting the cols with viridis does not work (any more). 
e.g.,
`FeaturePlot(int2NoMEDiet, "ctrb1.Score", order = T, label.size = 3, pt.size = 0.5) + scale_colour_gradientn(colours = viridis(10, alpha = 1, begin = 0, end = 1, direction = 1, option = "D"))`
