### ISSUE TITLE
How to build a data frame with gene expression per cell type with Seurat V5?

### ISSUE THREAD

**Issue by alasaa** [satijalab/seurat#8418]
Hi,
I would like to create my own signature matrix/data frame from single-cell RNA data.
I know the Seurat web (https://satijalab.org/seurat/articles/essential_commands.html#seurat-object-data-access).
But when I run:
> data.a=obj[["RNA"]]$data # "obj" is build by BPCells and Seurat V5. I also JoinLayers.
> class(data.a)
[1] "RenameDims"
attr(,"package")
[1] "BPCells"

> obj
An object of class Seurat 
32285 features across 120212 samples within 1 assay 
Active assay: RNA (32285 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 4 dimensional reductions calculated: pca, umap.unintegrated, integrated.cca, umap.cca

I also tried this:
> data.b=obj@assays$RNA@layers$data 
> class(data.b)
[1] "RenameDims"
attr(,"package")
[1] "BPCells"

and I also tried this:
> data.a=LayerData(obj, assay = "RNA", layer = "data")
> class(data.a)
[1] "RenameDims"
attr(,"package")
[1] "BPCells"

These "data.a" and "data.b" are S4 objects, not the data frame I want. 
I want gene expression data frame which colnames are cells' name (for example ACACAACTAC...) and rownames are gene names (for example Ptprc, Cd86...)

Could you help me?
Thank you very much!

**Comment by basetwin** [comment]
try this code
exp <- obj[['RNA']]$counts
in this way, you can get the counts matrix

**Comment by basetwin** [comment]
```r
exp <- obj[['RNA']]$counts
```

**Comment by basetwin** [comment]
try this code
```r
exp <- obj[['RNA']]$counts
```

**Comment by Gesmira** [comment]
Hi, 
Sorry for the late response here! You can convert the BPCells classes into dgCMatrix classes with: 
`data.dgc <- as(data.a, "dgCMatrix")`
This will have cells as columns and genes as rows. You can then convert this into a dataframe if you'd like.
