### ISSUE TITLE
The calculation method of spot.radius

### ISSUE THREAD

**Issue by guoyang-github** [satijalab/seurat#8420]
Hi,
Thank you for developing Seurat. 
When working with Seurat, I noticed a variable spot.radius within the function Read10X_Image, and its calculation logic is as follows:

https://github.com/satijalab/seurat/blob/763259d05991d40721dee99c9919ec6d4491d15e/R/preprocessing.R#L1051-L1052

I wonder why not define ```spot.radius``` as ```scale.factors$spot_diameter_fullres * scale.factors$tissue_lowres_scalef```, which would seem to be a more straightforward interpretation. 
What is the reason for using ```fiducial_diameter_fullres``` and normalizing with ```max(dim(x = image))``` ?
How do these affect downstream analysis?

Thanks,

**Comment by dcollins15** [comment]
I came across this myself while making some related updates - I agree, this should probably be `spot_diameter_fullres * tissue_lowres_scalef`. The `spot.radius` is used for plotting, but you can also control the spot size using `pt.size.factor` for `SpatialFeaturePlot` and `SpatialDimPlot`. Anecdotally, the plots are quite similar either way so I wouldn't expect downstream analysis to be affected. 

We should be updating this soon.

**Comment by dcollins15** [comment]
This was adjusted in `v5.1.0` - we will likely introduce a patch to allow users to recover the `spot.radius` value discussed in this thread 👌
