### ISSUE TITLE
Question about seurat v5

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8421]
I am following the vignette 

https://satijalab.org/seurat/articles/seurat5_integration

obj <- IntegrateLayers(
  object = obj, method = FastMNNIntegration,
  new.reduction = "integrated.mnn",
  verbose = FALSE
)

I encountered an an issue with FastMNNIntegration method
Error: object 'FastMNNIntegration' not found

Another question I have (a  naive one). Does finding clusters depend on find neigbors code the directly precedes it and the reduction used? I am asking because before find clusters, we always find neighbors.  How does the findclusters function make sure that those are the clusters that comes from cca and not scvi. can you explain the logic please?
obj <- FindNeighbors(obj, reduction = "integrated.scvi", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, cluster.name = "scvi_clusters")

obj <- FindNeighbors(obj, reduction = "integrated.cca", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, cluster.name = "cca_clusters")

**Comment by cgoneill** [comment]
If you run `sessionInfo()`, do you see batchelor on the list of packages, either attached or loaded via a namespace? The `FastMNNIntegration` method is from that package, so if you don't have it installed, you won't be able to use that integration method. 

Regarding your second question, I'm not sure I understand what you're asking. Are you asking how `FindClusters()` determines which reduction to use for clustering? My understanding is that `FindClusters()` itself doesn't rely on a particular dimension reduction for clustering and uses the neighbors calculated by `FindNeighbors()`. `FindNeighbors()` has a `reduction` argument you can pass to specify which is used - it defaults to `reduction = "pca"`, but after running integration, you'd need to specify an alternative reduction (e.g. `reduction = "integrated.scvi"`, `reduction = "integrated.cca"`, etc.). I'm not sure whether you can have multiple sets of neighbors, so you would need to rerun `FindNeighbors()` each time, but as long as you have names for each of the clustering sets you run, you could have clusters from each batch correction method.
