### ISSUE TITLE
Subset data by HTO Classification

### ISSUE THREAD

**Issue by evakareus** [satijalab/seurat#8423]
I am very new at using R and I am working on analyzing 10x data. I have been able to figure out variable features, clustering, etc but now I would like to separate my data set by HTO classification. So far I made a umap plot of both hash.IDs but I am interested in looking at difference in gene expression between the clusters on the umap. I have absolutely no idea how to do this. Any advice or tips would be greatly appreciated!
![image](https://github.com/satijalab/seurat/assets/159053901/07d41afb-ee9c-4f20-9aa6-89f38d8eb7e7)

**Comment by longmanz** [comment]
Hi,

Are you referring to differential expression (DE) analysis? You can refer to this vignette for more details on this: https://satijalab.org/seurat/articles/de_vignette
