### ISSUE TITLE
Cannot add graphs with unordered cells after LayerIntegration

### ISSUE THREAD

**Issue by edo98811** [satijalab/seurat#8427]
I performed a standard analysis of data coming from different subjects with seurat, then I wrote a function to subset my dataset, with this command:

`subset_seurat_object <- seurat_object[, seurat_object@meta.data[[column_to_subset]] %in% wished_subset]`

I get this error: `Fehler: Cannot add graphs with unordered cells`

What I did before is:

After loading the data and creating the single objects I ran on each subject these lines:
```
seurat_object <- NormalizeData(seurat_object)
seurat_object$percent.mt <- PercentageFeatureSet(seurat_object,pattern = "^MT-")
seurat_object <- subset(seurat_object, subset = nFeature_RNA > 200
                            & nFeature_RNA < 2500 & percent.mt < 5)
```
The objects are then added to a list, then merged: `merge(x = seurat_objects[[1]], y = seurat_objects[-1], add.cell.ids = subjects_info)` (subjects_info is a vector with subjects ID). Each cell is saved in the metadata as ID_barcode (done automatically by merge).

I then computed:
```
seurat_object <- FindVariableFeatures(seurat_object)
seurat_object <- ScaleData(seurat_object)
seurat_object <- RunPCA(seurat_object)
``` 
And then I performed integration:
```
seurat_object <- IntegrateLayers(
      object = seurat_object , method = HarmonyIntegration,
      orig.reduction = orig_reduction, new.reduction = new_reduction,
      verbose = TRUE)
seurat_object[["RNA"]] <- JoinLayers(seurat_object[["RNA"]])
```
After this I ran `FindNeighbour` and `FindClusters` before trying to create a subset.

Is there something I am missing about the way I am supposed to perform integration or is it something else?
Thank you very much in advance

**Comment by igrabski** [comment]
Hi, it's possible the problem is due to the way you are trying to subset your object. If you try using the subset command instead, do you run into the same problem? For example:

```
subset_seurat_object <- subset(seurat_object, subset = column_to_subset %in% wished_subset)
```

**Comment by edo98811** [comment]
I actually solved it but I forgot to delete the question. The mistake was on my side, I was doing an operation with the metadata (I didn't report it because I mistakenly deemed it was not related) which modified the row names of the data frame. This messed up the Seurat object. Thank you for your reply

**Comment by saphir746** [comment]
Encountered the same error when trying to subset a seurat object after modifying its meta.data:
`Umap_filtered<-subset(seur_obj, subset = RNA_snn_res.1.3 %in% Clt_keep)
Error: Cannot add graphs with unordered cells`

Fixed by doing this:
`seur_obj<- AddMetaData(seur_obj,df.new.meta)`

Instead of this:
`seur_obj@meta.data %<>% df.new.meta`
