### ISSUE TITLE
Get tissue coordinates in microns

### ISSUE THREAD

**Issue by JThomasWatson** [satijalab/seurat#8429]
I'm working on a distance-based analysis of a Visium dataset and would like to know the coordinates of each spot in micrometers. This is similar to #4900, I believe. 

When I use `GetTissueCoordinates()`, the coordinates returned range from zero to just under 600. Given the slide's capture area measures 6.5 x 6.5 mm (6,500 micrometers), is there a way to transform the `GetTissueCoordinates()` output to represent each spot's location in microns? Thank you!

**Comment by dcollins15** [comment]
Scaling is applied to the raw coordinates by default when calling`GetTissueCoordiantes`, passing `scale = NULL` should give the untransformed coordinates - let us know if you run into any other issues 🙂

**Comment by Houssi1337** [comment]
Hello @JThomasWatson , I am working on a similar objective so I am curious how did you calculate the distance between spots ? Is it based on an euclidian distance of the output of GetTissueCoordinates(... , scale = NULL) or how exactly ?
Thank you for your reply in advance!

**Comment by Gesmira** [comment]
Closing the issue now as the original query was answered. Please feel free to continue the discussion in the comments here. Thanks!
