### ISSUE TITLE
Export Seurat object to UCSC cell browser

### ISSUE THREAD

**Issue by mxposed** [satijalab/seurat#843]
Hi

There's a great browser viewer for single-cell RNA-seq data, UCSC cell browser: https://github.com/maximilianh/cellBrowser
It creates a bunch of static files for each dataset, which can be served as a static website or viewed on localhost.
As input it requires `tsv` files with expression matrix, metadata and genes, so we wrote a converter from standard Seurat object to the `tsv` files: https://github.com/maximilianh/cellBrowser/blob/master/src/cbImportSeurat

I wonder if you will be interested in adding that code to Seurat directly, so the user won't have to install new package or use Rscript in shell, but could just call a corresponding function in Seurat library?
If so, could you please describe how the pull request should look like

**Comment by satijalab** [comment]
Hi - this is great, and we'd be happy to host a function in Seurat. 

I just followed up by e-mail and we look forward to discussing
