### ISSUE TITLE
best way to integrate different spatial samples

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#8431]
I am interested in combing different spatial samples that I have individually analyzed (ie. scaled/normalized/runUMAP etc). 

Is the correct workflow to merge them and then redo the scale/normalize/runUMAP on the merged object? 

or is there a specific step I skip or don't do? 

Thanks

**Comment by igrabski** [comment]
Hi, we don't have a specific recommended workflow for integrating spatial samples. You could apply any standard scRNA-seq integration workflow, from our vignettes for example, using the gene expression data.
