### ISSUE TITLE
How to verify that my references are correct for IntegrateLayers rpca ?

### ISSUE THREAD

**Issue by Alexis-Varin** [satijalab/seurat#8432]
Hello, I have a dataset composed of 43 samples, and I am integrating using Seurat v5 IntegrateLayers RPCAIntegration with 5 references. Everything works fine, including the JoinLayers after, the UMAP etc.

But I do wonder about the references I have chosen. How can I be sure that the index I have input as references (4, 27, etc) are the correct ones I want ? I used View() to check the layers index. Is there a way to check the index of a specific layer so that I can be sure I selected the correct ones ?

Is the order the same as the factor levels in the ident I used to split ? Would : 

`levels(Idents(seurat_object))[index]`

Give me the correct index to input as references ?

While it was easy with Seurat v4 integration to simply check the index within the list of objects, I find checking the index much more mysterious with layers.

Thanks

**Comment by mhkowalski** [comment]
Hello, 

the `IntegrateLayers` command is searching `Layers(object = object, search = "data")` to determine the order of integration, so you could check the index in this way: 

``` Layers(object = seurat_object, search = "data")[index]```

We're working on implementing a way to specify the reference by name, which we think would be easier.
