### ISSUE TITLE
GetAssayData doesn't work for multiple layers in v5 assay.

### ISSUE THREAD

**Issue by surinderchd** [satijalab/seurat#8433]
Dear Sir/Madam,
Please guide me how to solve this error.

> data.input <- GetAssayData(object = seurat_object, assay = "RNA") Error in `GetAssayData()`: ! GetAssayData doesn't work for multiple layers in v5 assay. Run `rlang::last_trace()` to see where the error occurred.
--
Thank You,

**Comment by longmanz** [comment]
Hi,
For v5 assay please use LayerData() for extraction.

**Comment by surinderchd** [comment]
Thanks for your suggestion, i tried it, but again i am having this error,
Thanks and Regards,


> cellchatnew <- createCellChat(object = PTstroma_traj, group.by = "Group", assay = "RNA")
[1] "Create a CellChat object from a Seurat object"
The `meta.data` slot in the Seurat object is used as cell meta information 
The cell barcodes in 'meta' is  AAACGCTCATGCCGAC-1_1 AACCAACCAACTAGAA-1_1 AACCTGACAAATCCCA-1_1 AACGTCATCTTTGCAT-1_1 AACTTCTTCCCGAGGT-1_1 AACTTCTTCGCGAAGA-1_1 
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
In addition: Warning messages:
1: In LayerData.Assay5(object = x, layer = i) :
  multiple layers are identified by data.BDP3_db/m.1 data.1 data.BDP4_db/db.2 data.2 data.BDP5_SGLT2i.3 data.3 data.BDP6_SGLT2i-aPC.4 data.4 data.BDP7_db/m.5 data.5 data.BDP8_db/db.6 data.6 data.BDP9_SGLT2i.7 data.7 data.BDP10_SGLT2i-aPC.8 data.8
 only the first layer is used
2: In createCellChat(object = PTstroma_traj, group.by = "Group", assay = "RNA") :
  The cell barcodes in 'meta' is different from those in the used data matrix.
              We now simply assign the colnames in the data matrix to the rownames of 'mata'!
