### ISSUE TITLE
FindConservedMarkers error

### ISSUE THREAD

**Issue by chungsai** [satijalab/seurat#8434]
Hello, I am following the Integration Introduction module vignette code by code on MacOS Ventura. I am on the latest Rstudio version, R version and Seurat version

Yet when I arrive at this line

nk.markers <- FindConservedMarkers(ifnb, ident.1 = "NK", grouping.var = "stim", verbose = FALSE)
head(nk.markers)

I encounter 

Error: Please install the metap package to use FindConservedMarkers.
This can be accomplished with the following commands: 
----------------------------------------
install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('metap')
----------------------------------------

After looking at other reports in this page, I installed MacPort and installed fftw-3

<img width="752" alt="Screenshot 2024-02-07 at 12 58 53 PM" src="https://github.com/satijalab/seurat/assets/125383765/aa709c34-d34f-4ee8-988d-2d7613e7a93c">

And then installed. 
<img width="963" alt="Screenshot 2024-02-07 at 1 04 19 PM" src="https://github.com/satijalab/seurat/assets/125383765/35d4a906-2059-4180-9457-bcb2a5a450d3">

Following the prompt, I did force=TRUE. Which allowed installation, and re-ran the code. Yet, the same error asking me to install metap, etc... happened again. And I am at a loss.

<img width="1020" alt="Screenshot 2024-02-07 at 12 58 36 PM" src="https://github.com/satijalab/seurat/assets/125383765/0ecf8dc0-ce6a-49e4-8b52-4c3ca7037eb0">

Then following another thread, I found 

that doing 

> "metap" %in% installed.packages()
[1] FALSE

Meaning somehow it wasn't installed. The OP of that thread fixed it because his Rtools wasn't installed. But this is a windows phenomenon, and MacOS doesn't need it?
I have XCode, Homebrew and Macport in my terminal.

I tried.

<img width="1122" alt="Screenshot 2024-02-07 at 1 16 44 PM" src="https://github.com/satijalab/seurat/assets/125383765/370db2bd-d364-4819-a181-41a700ed4fb7">
Which gave me an error of a different nature.

I am wondering if anyone has some insight on this issue.

Thank you,

**Comment by mhkowalski** [comment]
It's a bit hard to tell where the problem is. Can you please restart your R session and try to re-run the command? If it's still failing please post your session info as well. 

You could also try install the package 'Rdpack' via `install.packages` to see if that is failing as well.

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if the error persists.
