### ISSUE TITLE
Seurat V5 manually editing variable features

### ISSUE THREAD

**Issue by purisuto** [satijalab/seurat#8438]
In Seurat V4, after running `FindVariableFeatures()` I was able to manually edit the variable features using the following code, i.e. when we want to remove immunoglobulin genes that dominate variable features of B cell data.

```
seuB@assays$RNA@var.features <- seuB@assays$RNA@var.features[!grepl("^IG(HV|KV|LV|HG|LC)",seuB@assays$RNA@var.features)]
```

However now in Seurat V5 I noticed that `@assays$RNA@var.features` is no longer present and the variable features are stored in `@assays$RNA@meta.data$var.features`

Do you have an updated recommended method for editing the variable features?  Is it sufficient to set the unwanted features to NA in the var.features column of the metadata?

[sorry if this has already been asked.  I did a bit of searching but could not easily identify]
[Thank you for your amazing package]

**Comment by Alexis-Varin** [comment]
Hi, you should use the dedicated VariableFeatures() function

`genes.to.remove = VariableFeatures(seuB)[grep("^IG(HV|KV|LV|HG|LC)", VariableFeatures(seuB))]
VariableFeatures(seuB) = setdiff(VariableFeatures(seuB), genes.to.remove)`

**Comment by samuel-marsh** [comment]
@Alexis-Varin is correct.  The best way to access/set various aspects of Seurat objects is to used provided getter/setter functions.

Another commonly used example of such a function would be `Idents`.

Best,
Sam

**Comment by purisuto** [comment]
Thank you.  Much appreciated.
