### ISSUE TITLE
How to merge/integrate multiple 10x samples from a single GEO?

### ISSUE THREAD

**Issue by davidepernici** [satijalab/seurat#8440]
I just want to analyze data from this GEO https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138267
which contains multiple 10x outputs

I'm trying to understand how should I properly filter, normalize and merge or integrate these data but searching online it's super confusing as everyone seems to have their own method... 
Multiple seurat objects? A single one? SCT? Before or after?
Could anyone please shed some light?
Thank you so much

**Comment by karabicicim** [comment]
Hi I am not in a developer team but you should load them with the Read10X function one by one and then create corresponding Seurat objects. 

Cntrla <- Read10X(data.dir = "your file path")
Cntrl1 <- CreateSeuratObject(counts = Cntrla, project = "xx")
...
repeat for others
After that you can merge all of them

Matrix2 <- merge(x = Cntrl1, 
                 y = c(Cntrl2, xx,xx,xx,), 
                 add.cell.id = c("Control1","Control2","xx","xx","xx"))

Best,

**Comment by davidepernici** [comment]
> Hi I am not in a developer team but you should load them with the Read10X function one by one and then create corresponding Seurat objects.
> 
> Cntrla <- Read10X(data.dir = "your file path") Cntrl1 <- CreateSeuratObject(counts = Cntrla, project = "xx") ... repeat for others After that you can merge all of them
> 
> Matrix2 <- merge(x = Cntrl1, y = c(Cntrl2, xx,xx,xx,), add.cell.id = c("Control1","Control2","xx","xx","xx"))
> 
> Best,

Hello, thanks for the reply.
So you would just merge without integration and then normalize directly the merged object?

**Comment by samuel-marsh** [comment]
Hi @davidepernici,

That answer is largely going to be analysis specific.  It is up to end user to determine whether an integrative analysis method is needed or not for given analysis.  I would suggest trying both with and without integration and then determining the best path forward.

Best,
Sam
