### ISSUE TITLE
DoHeatMap weird results/clustering issues

### ISSUE THREAD

**Issue by andynkili** [satijalab/seurat#8442]
Dear Seurat developpers,

I am using Seurat v5 and the result of DoHeatMap is quite messy:
![image](https://github.com/satijalab/seurat/assets/49782275/a54dacac-585d-4176-89ec-e29866ad3dc5)

Here is the corresponding code that I used:
`mydata <- NormalizeData(mydata, normalization.method = "LogNormalize", scale.factor = 10000)
mydata <- FindVariableFeatures(mydata, selection.method = "vst", nfeatures = 2000)

# data reduction and clustering
all.genes <- rownames(mydata)
mydata <- ScaleData(mydata, features = all.genes)
mydata <- RunPCA(mydata, features = VariableFeatures(object = mydata));ElbowPlot(mydata,ndims = 50)
mydata <- FindNeighbors(mydata, dims = 1:10)
mydata <- FindClusters(mydata, resolution = 0.5)

# cluster visualization
mydata <- RunUMAP(mydata, dims = 1:10)`

The Elbow plot looks like this:
![image](https://github.com/satijalab/seurat/assets/49782275/ce535fe8-bf2b-497c-992b-6f0cbe59e8e4)

And despite 20 PC, the result doesn't change much.

I thought it could be related to the dataset so I ran the same code on different data (already QCed) and ended up with similar messy results (reflecting unreliable clustering).
Likewise on other dataset, I tried changing the number of used PCs, resolution, removed doublets and high mitochondrial expressing cells, ... but still the heatmap indicates issues with the clustering.
What am I missing? How could I improve the clustering?
 
I would like to achieve something likle this (from seurat vignette) with more well-defined clusteres and genes ordered:
![image](https://github.com/satijalab/seurat/assets/49782275/8908cf6a-e9ed-4c9d-9eef-fcbb0a013978)

Best,
Andy

**Comment by yls2g13** [comment]
Hey Andy, glad to know I'm not alone. I'm facing a similar problem here - did you manage to figure out why this was happening? Keen to hear your thoughts.

**Comment by andynkili** [comment]
@yls2g13
I figured it was QC related, so I check my QC pipeline and some doublets were not filtered correctly as well as cells with mitochondrial genes (my previous treshold was 20%, so I lowered it to 5%).
It improved a lot (see below) but I am not still satisfied:
![image](https://github.com/satijalab/seurat/assets/49782275/32079f1a-ff1f-4508-b7fe-0d5d68fcbfb7)

Indeed cluster 0, 1, 2, 3 and 8 seem related but 0 and 1 are not expressing much differential genes while 2, 3 and 8 have clear markers.
Maybe it is just a matter of clustering resolution, though the current one is just 0.6 (not too high).

Despite the clustering improvement, this is not optimal and apart from resolution I don't know how to get better results.
Any thoughts on this?

Best,
Andy

**Comment by andynkili** [comment]
Another sample from the same dataset has that weird band (higlighted in my previous comment by the red box) of genes at the bottom of every cluster:
![image](https://github.com/satijalab/seurat/assets/49782275/d6e6b10a-7b69-418f-a3d7-ebc83ea403e7)

Those genes seems to be expressed accross **all clusters**, which doesn't make really sense as those should be differentially expressed genes.
Is it some sort of noise? How to deal with it?
I tried to be more stringent regarding min.cells and min.features, previously both set to 0 and now to 100 and 200 respectively.
However the issue is not fixed:
![image](https://github.com/satijalab/seurat/assets/49782275/13a952b1-231b-4354-ad68-de6a6890d7b1)

Does someone anyone have a clue on that matter?

Best,
Andy

**Comment by mhkowalski** [comment]
Hi Andy, 

Thanks for posting and for using Seurat, and sorry for our delayed response. I'm not what genes you are using as input to `DoHeatmap()`, but you could try being more stringent about what genes you are plotting. The red genes you highlighted do seem to be more highly express in clusters 1-4 compared to 5-10 for example, but may not have a very high logFC or very significant p-value.

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance for analysis questions.
