### ISSUE TITLE
Seurat gene expression between patients help

### ISSUE THREAD

**Issue by sps2332** [satijalab/seurat#8444]
Hello, 

I am very new to seurat and have performed data analysis using the vignettes available. I have 24  samples (All CD4 cells from 12 different donors pre and post-treatment) sequenced using cell ranger multiplex assay. I have demuxed everything loaded into Seurat and merged the datasets, corrected for batch effects, and integrated the samples. I did find markers and looked at conserved and DE genes pre and post-treatment for all the patients.

Now, I am trying to look at the differences between each donor pre and post-treatment. Could someone please help as to how I can do that using the seurat_integrated object?

**Comment by longmanz** [comment]
Hi,
It is not recommended to run DE test using the integrated assay. You may run DE tests using the RNA assay of your seurat object.
As for looking for donor-specific DE genes, you can perform FindMarkers() and by setting the ident.1 and ident.2 to the corresponding donor. For example, you can refer to the DE analysis vignette (https://satijalab.org/seurat/articles/de_vignette):
```
obj$donor_celltype_treatment <- paste0(obj$donor, obj$celltype, obj$treatment, sep = "_")
Idents(obj) <- "donor_celltype_treatment"
DE_results <- FindMarkers(obj, ident.1 = "donor1_CD4T_pre", ident.2 = "donor1_CD4T_post", verbose = FALSE)
```
You can repeat the above step for all 24 donors and get the donor specific DE genes.
