### ISSUE TITLE
SCT transform for a big data, splitobject

### ISSUE THREAD

**Issue by karabicicim** [satijalab/seurat#8447]
Dear All,

I would like to ask about the best way to reduce data usage and faster data obtain method. Recently I found a dataset that includes 25 patient data. (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE169379 ).
In here I am just interesting with this two data:
GSE169379_MIBC_snSeq.h5ad.gz	451.2 Mb	(ftp)(http)	H5AD
GSE169379_non_tumor_snSeq.h5ad.gz	83.7 Mb	(ftp)(http)	H5AD

1) Firstly I transform them .h5seurat file using seuratdisk packages. And successfully create a Seuratobject.
Also, I checked for the cell cycle phase and saved it seurat_phase.
However when I try to run this: 

```
library(harmony)
harmonized_seurat <- RunHarmony(seurat_phase, group.by.vars = c("orig.ident"), reduction = "pca", assay.use = "SCT", reduction.save = "harmony")
```
**I wasn't able to do it because of a lack of memory.**

2) So I decided to split them using this code line:

```
split_seurat <- SplitObject(seurat_phase, split.by = "sample")
split_seurat <- split_seurat[c("Bladder674", "Bladder54", "Bladder702", "Bladder752", "Bladder912", "Bladder896", "Bladder36", "Bladder72", "Bladder824", "Bladder590", "Bladder59", "Bladder489", "Bladder763", "Bladder739", "Bladder913", "Bladder1204", "Bladder371", "Bladder1126", "Bladder8", "Bladder446", "Bladder485", "Bladder593", "Bladder419", "Bladder518", "Bladder1246")]
for (i in 1:length(split_seurat)) {
    split_seurat[[i]] <- NormalizeData(split_seurat[[i]], verbose = TRUE)
    split_seurat[[i]] <- CellCycleScoring(split_seurat[[i]], g2m.features=g2m_genes, s.features=s_genes)
    split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = c("mitoRatio","S.Score","G2M.Score"))
    }
```

```
for (i in 1:length(split_seurat)) {
    split_seurat[[i]] <- RunPCA(split_seurat[[i]], assay = "SCT", npcs = 50)
}
```

3) It successfully worked. However, when I try to merge them back into one merged_seurat for the following steps I get a **lack of memory error again.**

So is there a way to make all the following steps in a split format or should I merge them before it? 

RunUMAP
RunTSNE
FindNeighbors
FindClusters

I saw some people suggest lapply like packages but I couldn't apply it here. If anyone can show me the best way to do it in one code line it will be the life-saving hero for me!

I would like to learn the best memory-friendly way to do it!

Thank you for your kind comments!

**Comment by saketkc** [comment]
Hi @karabicicim , you can do lapply for any of the steps, `obj <- lapply(obj.list, FUN=RunPCA)` for example but you will be limited by memory in any case so ideally for these many samples you should be requesting a large memory (200Gb+).

**Comment by karabicicim** [comment]
Dear @saketkc 

Thank you for your comment. How should I request more memory? The following code seems doesn't work well.
`options(future.globals.maxSize = 4000 * 1024^2)`

Is there any other way to increase memory?

 Could you please check my steps I will be grateful if you confirm it.
```

split_seurat <- SplitObject(seurat_phase, split.by = "sample")

split_seurat <- split_seurat[c("Bladder674", "Bladder54", "Bladder702", "Bladder752", "Bladder912", "Bladder896", "Bladder36", "Bladder72", "Bladder824", "Bladder590", "Bladder59", "Bladder489", "Bladder763", "Bladder739", "Bladder913", "Bladder1204", "Bladder371", "Bladder1126", "Bladder8", "Bladder446", "Bladder485", "Bladder593", "Bladder419", "Bladder518", "Bladder1246")]

for (i in 1:length(split_seurat)) {
    split_seurat[[i]] <- NormalizeData(split_seurat[[i]], verbose = TRUE)
    split_seurat[[i]] <- CellCycleScoring(split_seurat[[i]], g2m.features=g2m_genes, s.features=s_genes)
    split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = c("mitoRatio","S.Score","G2M.Score")
    split_seurat[[i]] <- RunPCA(split_seurat[[i]], assay = "SCT", npcs = 50))
    }
```
After here I was confused about the next steps. 
I would like to apply Harmony and wanna follow these steps but not sure how should I do it in a split_seurat object. Because it is a list format and Harmony doesn't work with a list format.

```
library(harmony)
harmonized_seurat <- RunHarmony(split_seurat, group.by.vars = c("orig.ident"), reduction = "pca", assay.use = "SCT", reduction.save = "harmony") 
harmonized_seurat <- RunUMAP(harmonized_seurat, reduction = "harmony", assay = "SCT", dims = 1:30)
harmonized_seurat <- RunTSNE(harmonized_seurat, reduction = "harmony", assay = "SCT", dims = 1:30)
harmonized_seurat <- FindNeighbors(object = harmonized_seurat, reduction = "harmony")
harmonized_seurat <- FindClusters(harmonized_seurat, resolution = c(0.2, 0.4, 0.6, 0.8, 1))
DimPlot(harmonized_seurat, reduction = "umap", label = T)
DimPlot(harmonized_seurat, reduction = "tsne", label = T)
```

The first line here gives an error. Then I tried the merge them but I encountered another memory error. May I continue here without merging and taking any memory errors? 

Could you please share the with me code line? I am still learning so it is sometimes hard to understand without saw the code line, if you can it will be very helpful.

Best

**Comment by saketkc** [comment]
I meant requesting more memory if you are running this on an hpc.
