### ISSUE TITLE
Seurat5 pbmcsa Integration expression level differences in SCTransform vs normal pipeline in unintegrated or integrated samples

### ISSUE THREAD

**Issue by chungsai** [satijalab/seurat#8449]
Hello, 

I am doing this vignette (https://satijalab.org/seurat/articles/seurat5_integration) and experimenting between the standard pipeline and the SCTransform pipeline.

I follow all the regular code listed in the vignette, and only out the portion that calls for SCTransform.

e.g: 

obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)
obj <- FindNeighbors(obj, dims = 1:30, reduction = "pca")
obj <- FindClusters(obj, resolution = 2, cluster.name = "unintegrated_clusters")
obj <- RunUMAP(obj, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")

vs

obj <- SCTransform(obj)
obj <- RunPCA(obj, npcs= 30, verbose = FALSE)
obj <- RunUMAP(obj, dims = 1:30, verbose = FALSE, reduction.name = "umap.unintegrated")
obj <- FindNeighbors(obj, dims = 1:30, verbose = FALSE, reduction = "pca"))
obj <- FindClusters(obj, resolution =2, verbose = FALSE, cluster.name = "unintegrated_clusters")

However, this seems to drastically affect the expression level of features CD8A highlighted in the vignette and therefore all subsequent analysis? What could be causing this?

Regular Violin plot of CD8A of unintegrated clusters

p1 <- VlnPlot(
  obj,
  features = "rna_CD8A", group.by = "unintegrated_clusters"
) + NoLegend() + ggtitle("CD8A - Unintegrated Clusters")

<img width="634" alt="Screenshot 2024-02-08 at 10 30 21 PM" src="https://github.com/satijalab/seurat/assets/125383765/b86568eb-e42a-479d-8fb1-c470d9486814">

Regular Violin plot of CD8A of unintegrated cluster (using SCTransform)

Using the Vlnplot code as above

<img width="703" alt="Screenshot 2024-02-08 at 10 30 39 PM" src="https://github.com/satijalab/seurat/assets/125383765/587f6a02-9bd8-4601-81ba-6f93bfb5dfd3">

When replacing rna_CD8A with just CD8A

<img width="707" alt="Screenshot 2024-02-08 at 10 30 33 PM" src="https://github.com/satijalab/seurat/assets/125383765/1d5ca6ca-7e58-42d1-842e-f57279625da2">

Clearly, something went wrong. 

Thanks for any insight.

**Comment by saketkc** [comment]
If you run SCTransform and use `VlnPlot` it fetches data from the `data` slot of "SCT" assay unless you speciify the assay (such as `rna_CD8` in your example. `rna_CD8` will fetch data from the RNA assay and in this case it is unnormalized (because you didn't run `NormalizeData` prior to `SCTransform` (you aren't expected to))
