### ISSUE TITLE
Size of radius is abnormal after subsetting the visium data.

### ISSUE THREAD

**Issue by sylee623** [satijalab/seurat#8460]
Hello, I try to subsetting my visium data but after subsetting them, their radius size is changed into too small.

Here is an example.

Before subsetting
<img width="327" alt="image" src="https://github.com/satijalab/seurat/assets/42854915/298519a2-bef7-4719-9237-1e2631d1bbac">

After subsetting
<img width="233" alt="image" src="https://github.com/satijalab/seurat/assets/42854915/086d86a1-79f5-4b7c-b7b4-9443f1830665">

How can I maintain the size of points after subsetting?

**Comment by dcollins15** [comment]
Please try adjusting the spot size using the `pt.size.factor` parameter - let us know if that doesn't work 🙂
