### ISSUE TITLE
Question about pseudobulking analysis in DE testing vignette

### ISSUE THREAD

**Issue by genome2020** [satijalab/seurat#8463]
Hi,
I have an experimental design very similar to the one described in the DE vignette. 

https://satijalab.org/seurat/articles/de_vignette

I am testing the pseudobulk method for my analysis using DESeq2. I noticed that the analysis doesn't take into account differences between the donor. I checked the source code (line 1524 in the R script below) and it seems the design formula only includes the group and not the donor (the dataset has multiple donors). 

https://github.com/satijalab/seurat/blob/HEAD/R/differential_expression.R

How should I set up the analysis to correct for the donors? 

Any input is appreciated.

Thanks.

**Comment by igrabski** [comment]
Hi, to clarify, are you currently pseudobulking by donor? If so, each "sample" being compared already represents each donor in your differential expression analysis. This is in contrast to differential expression at the single-cell level, where every cell is treated as an independent sample regardless of donor origin.
