### ISSUE TITLE
integration issue 

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#8465]
Hi, I integrated 16 different tumors together and then subset each of the integrated object and looked at gene expression. Interestingly, when I look at PDCD1, the gene itself is not found in the original assay (pre-integratation) of the object within the tumor but is now discovered in the integrated sub-setted tumor. any explanation. 

I'm really confused as to how one gene was not found pre-integration and now is found post-integration

**Comment by Gesmira** [comment]
It's difficult to answer this question without any relevant code. But this is likely related to v5 functionality. If you join layers in one object, then the features of all layers will be combined into the counts matrix so they are all represented. However, the cells that originally had no counts for this feature will continue to have no counts for this feature. So, the gene isn't now "found", your subsetted tumor cells should still not have any expression of this gene.

**Comment by chrkuo** [comment]
> It's difficult to answer this question without any relevant code. But this is likely related to v5 functionality. If you join layers in one object, then the features of all layers will be combined into the counts matrix so they are all represented. However, the cells that originally had no counts for this feature will continue to have no counts for this feature. So, the gene isn't now "found", your subsetted tumor cells should still not have any expression of this gene. 

But it is found in the specific tumor when it previously wasn't found which is why I'm confused.
