### ISSUE TITLE
IntegrateLayers with HarmonyIntegration vs RunHarmony

### ISSUE THREAD

**Issue by Gregory94** [satijalab/seurat#8467]
Hi,

I have two related questions about integrating.

1. When I use IntegrateLayers with the `HarmonyIntegration` method I get different results and clusters compared to the `RunHarmony` function from `library(harmony)`. _Could anyone explain what causes the differences and what method is the best?_
I have an example code below, copied from the [integrative analysis](https://satijalab.org/seurat/articles/seurat5_integration#perform-streamlined-one-line-integrative-analysis) vignette.

**Short explaination of the code**:
I load the `pbmcsca` dataset that includes the metadata entries `Method` and `Experiment`. In this example I split the data in layers based on the `Method` metadata and perform `IntegrateLayers(obj, method = HarmonyIntegration)`. Next, for the `RunHarmony` I use the parameter `group.by.vars = "Method"`. The other parameters are the same or left to their default value. (Btw, it doesn't matter whether I first perform `JoinLayers` before `RunHarmony` or not).

```
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ggplot2)
library(patchwork)
library(harmony)
library(ggplot2)
options(future.globals.maxSize = 1e9)

### LOAD DATA
# InstallData('pbmcsca')
obj <- LoadData("pbmcsca")
obj <- UpdateSeuratObject(obj)
obj <- subset(obj, nFeature_RNA > 1000)
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$Method)
obj



### PROCESSING
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)

obj <- FindNeighbors(obj, dims = 1:30, reduction = "pca")
obj <- FindClusters(obj, resolution = 2, cluster.name = "unintegrated_clusters")

obj <- RunUMAP(obj, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
p0 <- DimPlot(obj, reduction = "umap.unintegrated", group.by = c("Method"), combine = FALSE, label.size = 2)
p0_cluster <- DimPlot(obj, reduction = "umap.unintegrated", group.by = c("unintegrated_clusters"), combine = FALSE, label.size = 2)



### INTEGRATELAYERS WITH HARMONY
obj <- IntegrateLayers(object = obj, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "harmony", verbose = FALSE)

obj <- FindNeighbors(obj, reduction = "harmony", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, cluster.name = "harmony_clusters")

obj <- RunUMAP(obj, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
p1 <- DimPlot(obj, reduction = "umap.harmony", group.by = c("Method"), combine = FALSE, label.size = 2)
p1_cluster <- DimPlot(obj, reduction = "umap.harmony", group.by = c("harmony_clusters"), combine = FALSE, label.size = 2)



### RUNHARMONY INTEGRATION
obj <- RunHarmony(object = obj, reduction = "pca", group.by.vars = "Method", dims.use = 1:30, reduction.save = 'runharmony', plot_convergence = F)

obj <- FindNeighbors(obj, reduction = "runharmony", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, cluster.name = "runharmony_clusters")

obj <- RunUMAP(obj, reduction = "runharmony", dims = 1:30, reduction.name = "umap.runharmony")
p2 <- DimPlot(obj, reduction = "umap.runharmony", group.by = c("Method"), combine = FALSE, label.size = 2)
p2_cluster <- DimPlot(obj, reduction = "umap.runharmony", group.by = c("runharmony_clusters"), combine = FALSE, label.size = 2)


wrap_plots(c(p1_cluster, p2_cluster))
```
Left:`IntegrateLayers`; Right: `RunHarmony`
![integration_v5_figure1](https://github.com/satijalab/seurat/assets/29129193/4d876ea5-4279-47ae-9362-867a6299ad12)

2. As a followup question, in `RunHarmony` I can give a list of covariates (using the `group.by.vars` argument) that are corrected for during integration. In `IntegrateLayers` I can also pass this argument, but it seems to give different results to the method advised in [issue 8136](https://github.com/satijalab/seurat/issues/8136). *Again, can anyone help me figuring out which method is best*. Below I have an additional code for this question.

**Short explaination of the code**:
I have integrated the data again with split layers based on the 'Methods' and additionally I have passed the argument `group.by.vars = "Experiment"` to also correct for 'Experiment' type. Next, I have joined the layers, created a new metadata entry where I combine the Methods and Experiment metadata entry and then I split the layers based on this combined entry. Finally I run `IntegrateLayers` again based on this new combined metadata entry.

```
### INTEGRATELAYERS WITH HARMONY USING GROUPBYVARS
obj_groupbyvars <- IntegrateLayers(object = obj, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "harmony", group.by.vars = "Experiment", verbose = FALSE)

obj_groupbyvars <- FindNeighbors(obj_groupbyvars, reduction = "harmony", dims = 1:30)
obj_groupbyvars <- FindClusters(obj_groupbyvars, resolution = 2, cluster.name = "harmony_clusters")

obj_groupbyvars <- RunUMAP(obj_groupbyvars, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
p3 <- DimPlot(obj_groupbyvars, reduction = "umap.harmony", group.by = c("Method"), combine = FALSE, label.size = 2)
p3_cluster <- DimPlot(obj_groupbyvars, reduction = "umap.harmony", group.by = c("harmony_clusters"), combine = FALSE, label.size = 2)



### INTEGRATELAYERS WITH HARMONY BY COMBINING METADATA
obj_joinlayers <- JoinLayers(obj)
obj_joinlayers@meta.data[['covariates']] <- paste(obj_joinlayers$Method, obj_joinlayers$Experiment, sep = '_')
obj_joinlayers[['RNA']] <- split(obj_joinlayers[['RNA']], obj_joinlayers$covariates)
obj_joinlayers <- IntegrateLayers(object = obj_joinlayers, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "harmony", verbose = FALSE)

obj_joinlayers <- FindNeighbors(obj_joinlayers, reduction = "harmony", dims = 1:30)
obj_joinlayers <- FindClusters(obj_joinlayers, resolution = 2, cluster.name = "harmony_clusters")

obj_joinlayers <- RunUMAP(obj_joinlayers, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
p4 <- DimPlot(obj_joinlayers, reduction = "umap.harmony", group.by = c("Method"), combine = FALSE, label.size = 2)
p4_cluster <- DimPlot(obj_joinlayers, reduction = "umap.harmony", group.by = c("harmony_clusters"), combine = FALSE, label.size = 2)



wrap_plots(c(p3_cluster, p4_cluster))
```
Left: `IntegrateLayers` with `group.by.vars`; Right:`IntegrateLayers` after `split` with combined covariates.
![integration_v5_figure2](https://github.com/satijalab/seurat/assets/29129193/f6bbcca7-4a52-4bcf-8e96-6e02c19cf01f)

Thanks in advance for any advice.

**Comment by igrabski** [comment]
Hi Gregory, thanks for your question and for this detailed and well-documented report! There have been some changes to `RunHarmony`, which means the default parameters may be slightly different between the `IntegrateLayers` implementation and `RunHarmony`; for example, off the bat, the default number of PCs used in `IntegrateLayers` is 50. We are planning to update our implementation to better reflect the updated Harmony functions; in the meantime, the differences look minor between the final reductions here (the UMAPs are rotated from one another, but the clusters look very similar). While you should make sure the results are sensible, it likely would not make a big impact which of these two you used. 

For your second question, we do not currently use the arguments passed in `group.by.vars` in `IntegrateLayers`; instead, you should combine the metadata entries as you did in the second approach.

**Comment by shihsama** [comment]
> Hi Gregory, thanks for your question and for this detailed and well-documented report! There have been some changes to `RunHarmony`, which means the default parameters may be slightly different between the `IntegrateLayers` implementation and `RunHarmony`; for example, off the bat, the default number of PCs used in `IntegrateLayers` is 50. We are planning to update our implementation to better reflect the updated Harmony functions; in the meantime, the differences look minor between the final reductions here (the UMAPs are rotated from one another, but the clusters look very similar). While you should make sure the results are sensible, it likely would not make a big impact which of these two you used.
> 
> For your second question, we do not currently use the arguments passed in `group.by.vars` in `IntegrateLayers`; instead, you should combine the metadata entries as you did in the second approach.

Hi,
    I compared these two workflows. I noticed a little difference that Runharmony would return stdev while HarmonyIntegration would not. This parameter would help us to determing PCs to choose. Will this be updated in the future version? Thanks!
