### ISSUE TITLE
WNN multimodal integration on multiple batches

### ISSUE THREAD

**Issue by haerin0106** [satijalab/seurat#8468]
Hi! Thank you for the great program. I have a quick question regarding the wnn process.
I have a large dataset with about 50 samples with scRNAseq and CITEseq data. The data was generated in batches of 5 samples each. When running wnn, a previous issue ([https://github.com/satijalab/seurat/issues/3799](url) has recommended doing rna integration and cite integration separately, then running wnn to bring the two modalities together. My question is: is it possible to run wnn by batch instead of running the whole data in one go. For instance, can we run wnn on each batch and then integrate the wnn assay from the different batches? 
This is an issue for us mostly because our data seems to be reaching its computational limit when running wnn on the full dataset at once, and we expect more data to come. If running wnn by batch is not an option, what would you recommend to make it less challenging? 
Any help would be much appreciated! Thank you again for the amazing program.

**Comment by igrabski** [comment]
Hi, thanks for your question! We do recommend that you separately integrate RNA and ADT, then apply WNN. Unfortunately, we don't currently have a recommendation if this is too computationally intensive. Depending on your specific data and use case, you could consider doing this for a subset of your samples and then projecting the remaining samples onto that WNN -- but this should be considered carefully and would only make sense if that subset of samples are representative of the remaining samples.
