### ISSUE TITLE
Featureplot() automatically printing "AnnData" on the figure

### ISSUE THREAD

**Issue by maggs-x** [satijalab/seurat#8470]
Hi, my name is Maggs. I'm having trouble finding a solution in the documentation for "AnnData" being printed automatically on my plots. Attached is an example. Is there a way to turn this automatic feature off? Thanks for your help! Let me know if you need more information. 

Maggs
![Screenshot 2024-02-14 at 1 32 25 PM](https://github.com/satijalab/seurat/assets/131017774/dd7b8438-246e-4805-8caa-e9f888fb73ae)

**Comment by maggs-x** [comment]
Oh, I realize setting label=FALSE solves it.

**Comment by samuel-marsh** [comment]
Glad you solved issue!

Best,
Sam
