### ISSUE TITLE
Split a cluster based on low and high expression for one gene 

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8473]
Dear all, 

I would like to know if the following is somehow possible to do in Seurat:

Let´s assume I have identified 5 clusters. If I analyse the expression of gene XY in these clusters I realise that e.g. in cluster 3 I have an area of high and low expression of that gene. 
Now my question: Is it somehow possible to split this cluster 3 into two "subclusters" (low and high gene expression of gene XY)?

The reason is that I would like to get a Matrix as below:

```

Gene   |cell 1 Cluster 3 low | cell 2 Cluster 3 high | cell 3 Cluster high | ...
XY             2                               6                    8                        

```
Thank you!

**Comment by mhkowalski** [comment]
Hi, we have a `FindSubCluster` function that you could use. This won't subcluster based specifically on that gene, so you could also define a new metadata column based on expression of that gene, such as below:

```
pbmc_small$subcluster <- paste(pbmc_small$RNA_snn_res.0.8, ifelse(pbmc_small[['RNA']]$data["CD19",] >1,
 "high", "low"), sep="_")
> head(pbmc_small$subcluster)
ATGCCAGAACGACT CATGGCCTGTGCAT GAACCTGATGAACC TGACTGGATTCTCA AGTCAGACTGCACA TCTGATACACGTGT 
       "0_low"        "0_low"        "1_low"        "0_low"        "0_low"        "0_low" 
```
 I'll also just note that it's generally risky to perform analysis based on the expression of a single gene in the case this gene drops out in some cells that do express it.

**Comment by LeaLe88** [comment]
Dear @mhkowalski,

Thank you so much for your reply, thats exactly what I was looking for.

May I ask one more question - since I am running a deconvolution based on these clusters afterwards I should have beside these two subcluster "low & "high" also a subcluster with everything else because the deconvolution will try to add up subcluster "low" and "high" otherwise to 100% (however not all % of gene expression can be based on these two subclusters of cluster 3 in bulk RNA Seq). 
So is it somehow possible to MERGE my new metadata "subcluster" with the old metadata ("seurat clusters) however removing in the old clustering the cluster 3 since this is already included in subcluster?
Hope this makes sense.

Thank you!
