### ISSUE TITLE
Merging seurat objects with precomputed reductions

### ISSUE THREAD

**Issue by apal6** [satijalab/seurat#8477]
Hi,

I have individual clusters reported in a paper that I am trying to replicate. I would like to merge these while preserving the dimentional reductions so that when I generate the dimplot, it comes out to be exactly how it was when individual cluster was plotted. I tried merging the objects and adding the reductions as a col in the merged object. Not sure if this is the right way? 
Thank you for any advice.

Best,
Aastha

**Comment by mhkowalski** [comment]
Hi, 

Do you have the same reductions calculated for each cluster? If so, you can set the `merge.dr=TRUE` to also merge the dimension reductions. If you have a separate UMAP for each cluster, then it doesn't make sense to merge these.  Hope this is helpful.
