### ISSUE TITLE
Cannot Use Matrix and Seurat Object at the same time.

### ISSUE THREAD

**Issue by MehvesOzel** [satijalab/seurat#8483]
Previously I got this error: 
Error in irlba::irlba(L, nv = n, nu = 0, maxit = iters) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix' 
and downgraded my Matrix package via remotes::install_version("Matrix", version = "1.6-1")
However now I cannot use SeuratObject package due to this error:
Error: package or namespace load failed for ‘SeuratObject’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Matrix’ 1.6-1 is being loaded, but >= 1.6.3 is required

How can I use Matrix and SeuratObject at the same time?

**Comment by samuel-marsh** [comment]
Hi,

This has been reported before.  Please try previously selected solutions to update Matrix and irlba packages:

```
install.packages("Matrix", type = "source")
install.packages("irlba", type = "source")
```

Best,
Sam
