### ISSUE TITLE
Run PCA/tSNE using customized normalization data

### ISSUE THREAD

**Issue by DadongZ** [satijalab/seurat#849]
I tested some normalization methods on the count sparse matrix.  What's the best way to use Seurat for a down stream PCA/tSNE analysis based on this normalized matrix?

**Comment by satijalab** [comment]
If you insert your custom-normalized matrix into object@data, you should be able to proceed onwards from the ScaleData function for downstream analyses. If you do observe significantly improved results with alternative normalizations, please do let us know!
