### ISSUE TITLE
Proper order of running FindSpatiallyVariableFeatures and PrepSCTFindMarkers

### ISSUE THREAD

**Issue by pcantalupo** [satijalab/seurat#8494]
### Discussed in https://github.com/satijalab/seurat/discussions/8480

<div type='discussions-op-text'>

<sup>Originally posted by **pcantalupo** February 15, 2024</sup>
**I made changes to my original discussions post**
I have a merged Seurat object (Visium spatial data) from 4 individually SCTransformed Seurat objects. When I ran FindMarkers on my merged object, I got the message saying that PrepSCTFindMarkers needs to be run first. From the docs, this function is going to create a new count and data slot in the SCT assay thereby deleting the original SCT assay. 

I'm concerned since I also want to run FindSpatiallyVariableFeatures. However, I am not sure if I should use the new SCT assay created by PrepSCTFindMarkers or run FindSpatiallyVariableFeatures before running PrepSCTFindMarkers. What is the proper order of operations for these two functions?

Also, which SCT assay is best to use for generating feature visualizations (i.e. VlnPlots, FeaturePlots, etc..)? I think using the PrepSCTFindMarkers SCT assay is best for this since it would be the same data used to determine differentially expressed genes. 

Thank you
</div>

**Comment by saketkc** [comment]
PrepSCTFindMarkers only touches the corrected counts (`data` slot) so the order does not matter. You should use corrected counts post `PrepSCTFindMarkers` for visualization.

**Comment by pcantalupo** [comment]
Hi, thank you for your response.

I think your statement `You should use corrected counts post` is ambiguous. Do you mean use the new `counts` slot or the new `data` slot for visualization?

I disagree that the `counts` slot is not changed. The documentation of PrepSCTFindMarkers explicitly says `The counts slot of the SCT assay is replaced with recorrected counts and the data slot is replaced with log1p of recorrected counts.` I confirmed this by comparing the `counts` slot before and after running Prep. Here are the results of the first 50 rows and columns using `waldo::compare`:
```
> waldo::compare(c1[1:50,1:50], c2[1:50,1:50], max_diffs = 3)
`old@i[1:36]`: 45 45 40 and 33 more...
`new@i[1:18]`: 45 45               ...

`old@i[38:72]`: 34 38 41 and 32 more...
`new@i[20:41]`: 34 38 41            ...

`old@p`: 0 1 2 and 48 more...
`new@p`: 0 1 1            ...

And 5 more differences ...
```

After reading the help docs for FindSpatiallyVariableFeatures it makes sense that the order would not matter since it uses the `scale.data` slot and this slot does not change when running PrepSCTFindMarkers. But there could be confusion down the road when using the updated SCT assay after PrepSCTFindMarkers since the values used to generate the `scale.data` slot so longer exist. Maybe this isn't a problem for people but I like to keep my data consistent and reproducible. I have taken the route to keep the original SCT assay and then create a new assay called 'SCT_PFM' for holding the results of PrepSCTFindMarkers

I look forward to hearing more opinions about this from members of the community.

Thank you

**Comment by saketkc** [comment]
Thanks, I should have been a bit more clear.

- You should use `data` slot of SCT assay for visualization after running `PrepSCTFIndMarkers`
- SCT `scale.data` (which is what is used by FindSpatiallyVariableFeatures) is pearson residuals  which is what is used to perform correction. Note that these values are not dependent on what values you have in your `data` or `counts` slot of the SCT assay 
- When you run PrepSCTFindMarkers, it uses the pearson residuals and minimum of the median sequencing depth across samples to reverse the regression model (see Choudhary & Satija 2022 for details)

**Comment by pcantalupo** [comment]
Thank you for clarifying

> * SCT `scale.data` (which is what is used by FindSpatiallyVariableFeatures) is pearson residuals  which is what is used to perform correction. Note that these values are not dependent on what values you have in your `data` or `counts` slot of the SCT assay

This is confusing. I thought `scale.data` is directly calculated from the `data` slot?  This is true for the RNA assay, right? I hope so or all my assumptions for years has been wrong. Maybe I just don't understand the inner workings of SCT. Please explain. Thank you

**Comment by saketkc** [comment]
I would refer you to the [SCT paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9). But in short, `scale.data` is pearson residuals for SCT assay and scaled data for RNA assay.
