### ISSUE TITLE
Cite-Seq Cell Type Assigment Problem

### ISSUE THREAD

**Issue by MehvesOzel** [satijalab/seurat#8500]
I have a Cite-Seq dataset that I'm trying to annotate cell types using https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat this reference. However, I'm getting this error 
Error in validObject(object = object) : 
  invalid class “DimReduc” object: colnames for ‘feature.loadings’ must start with reduction key (apca_)
What could be the issue and how can I fix this?

**Comment by mhkowalski** [comment]
Hi, 

It seems like you are trying to map to our PBMC reference. There may be problems with the h5Seurat object on this site. You could also perform reference mapping using the same reference with our Azimuth functionality (see [`here`](https://satijalab.github.io/azimuth/articles/run_azimuth_tutorial.html) for more information).
