### ISSUE TITLE
Filtering & merging metadata

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8504]
Dear all, 

In issue 8473 ( https://github.com/satijalab/seurat/issues/8473) I asked how to separate into two subcluster of low & high gene expression within one cluster (e.g. cluster 3).
I managed to get a new subcluster in my metadata with low/high gene expression within cluster 3.
So when I access  myobject@meta.data$subcluster I have Cluster 3 high and Cluster 3 low.

However the issue is all my other clusters including cluster 3 (not subdivided) (e.g. 1,2,3,4,5) are in myobject@meta.data$seurat_clusters.

Is there any way I can combined myobject@meta.data$subcluster with myobject@meta.data$seurat_clusters however remove cluster 3 from myobject@meta.data$seurat_clusters since this is already included in myobject@meta.data$subcluster?

I tried creating two separate Seurat objects and then merging & joining layers after, however I think its not correct because it only takes the metadata of Seurat_cluster3:

Combined <- merge(x = Seurat_cluster3, y = Seurat_other_clusters= ls()[1:2],project = 'combined_object') 
#Join
Combined<- JoinLayers(Combined)

Thank you very much!

**Comment by longmanz** [comment]
Hi, 

I am not 100% sure what you are trying to do so please pardon me if I am speaking non-sense. Are you referring to merging the meta-data columns ("seurat_clusters" and "subcluster")? If so, you can easily do that using the following codes:
```
myobject@meta.data$new_cluster = myobject@meta.data$seurat_clusters
myobject@meta.data$new_cluster[myobject@meta.data$seurat_clusters == "cluster3"] = myobject@meta.data$subcluster[myobject@meta.data$seurat_clusters == "cluster3"]
```
And you can use myobject@meta.data$new_cluster for your downstream analysis.
