### ISSUE TITLE
regression coefficients

### ISSUE THREAD

**Issue by vrutten** [satijalab/seurat#851]
Hi,

Could you tell me how I can extract the regression coefficients when using the "ScaleData" function?

Thanks

V

**Comment by 2236529177** [comment]
the scaledata should be a expression matrix, are you sure there is corr data in it, 
![image](https://user-images.githubusercontent.com/25199946/46987410-b0cd3100-d126-11e8-95de-3f24312af4e9.png)
![image](https://user-images.githubusercontent.com/25199946/46987488-f0941880-d126-11e8-81ce-4bed86b5a65f.png)

**Comment by mschilli87** [comment]
AFAICT, `ScaleData` simply calls `RegressOutResid` to do the actual regression which only returns the residuals of the regression model (then used by `ScaleData` as data to scale). So I'm not sure how to get the coefficients from the Seurat object but you could do what `RegressOutResid` is doing manually to get them: https://github.com/satijalab/seurat/blob/7618ac8798e2aefc509529f07af9d2836b96a1be/R/preprocessing_internal.R#L25-L181

**Comment by satijalab** [comment]
We do not store the regression coefficients, so you will have to modify the source code to save these. This is something we will consider storing in the future.

**Comment by vrutten** [comment]
Would it be possible to make the coefficients available when you have a moment? It seems like quite a useful/important thing to be able to do a sanity check on which I assume most people would want to do(?). The pipeline is so nice to use, it would be great to have this feature too (if possible).
