### ISSUE TITLE
How to get the corrected counts in the result of IntegrateData(normalization.method="SCT")

### ISSUE THREAD

**Issue by FUzzy9876** [satijalab/seurat#8511]
Seurat provides a great workflow for data integration. Unfortunately, my downstream analysis relies on the count matrix. I would like to use the SCTransform workflow to remove batch effects from the data, but I found that `integrated_data@assays[["integrated"]]@counts` is empty in the output of `IntegrateData(normalization.method="SCT")`.

I follow the instructions in this issue:  https://github.com/satijalab/seurat/issues/4317#issuecomment-816877635

> After integration using SCT-normalized counts, the data slot will contain non-centered Pearson residuals and the scale.data slot will contain the centered residuals.
> Transforming post-integration residuals to corrected counts is not supported/tested, but if you absolutely have to do this, refer to the sctransform::correct_counts function in the SCT case or use expm1 in the log case. Again, this is not necessarily encouraged.

I am trying to use `sctransform::counts` to calculate the corrected counts, but I notice that `integrated_data@assays[["integrated"]]@SCTModel.list[["refmodel"]]` (which I believe is the location where Seurat saves the SCT model after integration) seems to be different from the output of sctransform::vst. As a result, it cannot be used as input parameters for `sctransform::counts`.

In addition, I found that sctransform in Seurat stores `log1p(counts)` in the data slot, as documented here: https://satijalab.org/seurat/reference/sctransform. 
So what exactly is stored in the data slot in the result of `IntegrateData(normalization.method="SCT")`? Is it `log1p(counts)` or non-centered Pearson residuals?

If it is the non-centered Pearson residuals, how can I get the corrected counts from it?

**Comment by dcollins15** [comment]
> So what exactly is stored in the data slot in the result of IntegrateData(normalization.method="SCT")? Is it log1p(counts) or non-centered Pearson residuals?

That's correct, the non-centered Pearson residuals should end up in the `data` slot. 👍 

> If it is the non-centered Pearson residuals, how can I get the corrected counts from it?

There's no supported way to achieve this, unfortunately. If at all possible, I'd recommend that you consider reworking your analysis workflow to avoid having to attempt this type of transform — if you're really stuck you could try running `sctransform::vst` on your raw counts matrix to get a model in a form that can be handed to `sctransform::correct_counts` - it won't match the model generated during integration but may at least provide a programmatic workaround. Again, I don't recommend doing this, but you can always give it a try 🤷
