### ISSUE TITLE
FindAllMarkers not working (JoinLayers)

### ISSUE THREAD

**Issue by piotay** [satijalab/seurat#8513]
Hello all!

I have a seuratobject made of four merged datasets from the same sample type. I was able to successfully generate a UMAP that does not seem to need integration. 
![7b0cc274-e403-4bbd-9810-a1f11c8cfe26](https://github.com/satijalab/seurat/assets/99440488/72b3d02f-6e67-412e-9a30-b829a6949b8f)

I would like to run FindAllMarkers to see the top differential genes for each Seurat cluster. Here is the code I am running:

`obj_markers <- FindAllMarkers(obj, assay="RNA", only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)`

and here is the error:

```
Calculating cluster 0
Calculating cluster 1
Calculating cluster 2
Calculating cluster 3
Calculating cluster 4
Calculating cluster 5
Calculating cluster 6
Calculating cluster 7
Calculating cluster 8
Calculating cluster 9
Calculating cluster 10
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing 0 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 1 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 2 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 3 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 4 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 5 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 6 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 7 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 8 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 9 versus all:
	data layers are not joined. Please run JoinLayers
Warning: When testing 10 versus all:
	data layers are not joined. Please run JoinLayers
```

I have processed this type of data before and this error is new to me.

I have already tried:
-JoinLayers(obj)
-DefaultAssay(qc_sub) <- "RNA"

[Here is a link to someone who had the same issue](https://www.biostars.org/p/9584082/#9584182), but it does not seem to be resolved.

Any assistance would be appreciated.
Thank you!

**Comment by piotay** [comment]
I solved this by doing
obj<-JoinLayers(obj)

**Comment by Leonrunning** [comment]
works for me too, thanks

**Comment by Guqq1989** [comment]
After running joinlayer， the same error occurred again. the Seurat version i used was 5.0.2

**Comment by wjbio15** [comment]
im having the same problems

**Comment by wjbio15** [comment]
when do you join the layers, after the standard flow (ie merged_data <- NormalizeData(merged_data), merged_data <- FindVariableFeatures(merged_data), merged_data <- ScaleData(merged_data), merged_data <- RunPCA(merged_data)

then merged_data <- JoinLayers(merged_data[["RNA"]]) 

or 
merge multiple seurat objects first, then straight away use join layers, then do the above standard flow?
