### ISSUE TITLE
DE Analysis Between A Subset Seurat Object Dataset Versus Original Seurat Object Dataset

### ISSUE THREAD

**Issue by Zeddicus77** [satijalab/seurat#8514]
This is my first GitHub post and venture into R and seurat, so I apologize for the naivety of my question and if this has been answered elsewhere. It seems like this should be a common type of analysis question, but I have not been able to find out how to go about it via extensive Googling. Here are the steps I have taken and my question:

1) Started with a complex tissue dataset which formed 11 low resolution clusters in the "original" seurat object.
2) Subset the cells in "original" cluster-8 to form a separate "subset-1" seurat object containing 5 low resolution subclusters.
3) Subset the cells in "subset-1" subcluster-1 to form a separate "subset-2" seurat object containing 6 high resolution subclusters.
4) How can I perform DE analysis of these "subset-2" subclusters compared to the rest of the "original" dataset?

Thanks in advance!

**Comment by Zeddicus77** [comment]
I found out I was just missing some quote marks for location. Working code is:

`everything@meta.data$endothelial_subclusters <- ifelse(rownames(everything@meta.data) %in% **"**endothelial_cells**"**, "endothelial_1", "other")`

**Comment by Zeddicus77** [comment]
# No worries, I got it to work this way:

# Got cell names:

cellnames_all <- Cells(everything)
cellnames_ec <- Cells(endothelial_cells)

# Created a vector of labels
# For cells in the endothelial subset, labelled them as "EC", for others label them as "Other"
labels <- ifelse(cellnames_all %in% cellnames_ec, "EC", "Other")

# Added the labels as a new column to the metadata
everything_ec <- AddMetaData(everything, metadata = labels, col.name = "Labels")

# Checked if the new column was added
head(everything_ec@meta.data, n = 2)

# Checked to see if subset of original cells had the right number of labels

Idents(everything_ec) <- "Labels"

table(Idents(everything_ec))

# Correct number of cells labelled with the "EC" label

# Can now do perform DE analysis

DefaultAssay(everything_ec) <- "RNA"

ec.vs.all.markers <- FindMarkers(everything_ec, ident.1 = "EC", ident.2 = "Other", logfc.threshold = 1, test.use = "roc", only.pos = TRUE)

# Checked list of DE genes

head(ec.vs.all.markers, n = 20)

**Comment by dcollins15** [comment]
Glad you were able to figure things out - please let us know if you run into any other issues 🙂
