### ISSUE TITLE
Error in heatmap.cnv(obs_data, Rowv = obs_dendrogram, Colv = FALSE, cluster.by.row = TRUE,  :    'RowIndividualColors' must be a character vector of length nrow(x)

### ISSUE THREAD

**Issue by fariznazir** [satijalab/seurat#8517]
Hi, 

I am running InferCNV and facing this issue at "STEP 15: computing tumor subclusters via leiden"

Thank you for the help!

**Comment by dcollins15** [comment]
Please provide the output of sessionInfo() so we can try to help to debug 🙂 It might also be worth re-posting on `infercnv`'s [issues page](https://github.com/broadinstitute/inferCNV/issues)
