### ISSUE TITLE
Error: std::bad_alloc when run FindNeighbors

### ISSUE THREAD

**Issue by Huimin721** [satijalab/seurat#8519]
Dear team,

Thanks so much for developing the outstanding analysis tool! I recently met this error when I run FindNeighbors on 200000 cells data.

Computing nearest neighbor graph
Computing SNN
Error: std::bad_alloc
Execution halted

I have checked my PCA, the PCA looks fine, and there is no NA. I request 500GB on the server. Could I ask if you have any hints why this happens? Thanks so much!

Best,
Huimin

**Comment by longmanz** [comment]
Hi Huimin,

This does not seem to be a memory issue. Can you provide us the complete script that you use for your analysis? 

There have been several previous posts reporting similar issues (as in https://github.com/satijalab/seurat/issues/6473). It could happen if you are using a different modality like ADT and there are "empty" cells in that assay.

**Comment by raygozag** [comment]
HI, I'm having the same issue, and I have one terabyte of memory. Is there an alternative to FindNeighbors?

**Comment by StardDii** [comment]
> HI, I'm having the same issue, and I have one terabyte of memory. Even so it is possible it's not enough, but then, is there an alternative to FindNeighbors?

Hi Im having same issue  too! have you solved now?

**Comment by hangyinn** [comment]
Hi all, I have the same issue. Have you solved this now?

I have 900GB of memory. FindNeighbors failed on a 1.4M cells x 6000 genes seurat object with the following settings:
```
FindNeighbors(seu.obj, 
                dims = 1:50,
                k.param = 35,
                prune.SNN = 1/10,
                annoy.metric = "cosine",
                verbose = FALSE)
```
I followed the discussion in https://github.com/satijalab/seurat/issues/6473. There is no "empty cells" and no NA values in PCA embedding. k.param=20 had a successful run. I don't believe this function can exhaust this much memory. There should be something wrong during the computation.

**Comment by AldrichCPU-bio** [comment]
> Hi all, I have the same issue. Have you solved this now?
> 
> I have 900GB of memory. FindNeighbors failed on a 1.4M cells x 6000 genes seurat object with the following settings:
> 
> ```
> FindNeighbors(seu.obj, 
>                 dims = 1:50,
>                 k.param = 35,
>                 prune.SNN = 1/10,
>                 annoy.metric = "cosine",
>                 verbose = FALSE)
> ```
> 
> I followed the discussion in [#6473](https://github.com/satijalab/seurat/issues/6473). There is no "empty cells" and no NA values in PCA embedding. k.param=20 had a successful run. I don't believe this function can exhaust this much memory. There should be something wrong during the computation.

Perhaps it do need more resources than what we thought for computing the neighbors. Some processes may be necessary to lower computational load, including wider threshold in this step or the most efficient, reducing cell numbers. And the ‘Sketching’ methods could also be a potential option especially for a large data set, referred to section `Sketch-based analysis in Seurat v5`. And of course, if you are rich enough, please neglect what mentioned above and forgive my comment really with no offense :P

**Comment by msraredon** [comment]
I am also having this issue. I encountered a futures error requesting more RAM, provided, and now I'm caught in this same error. I am trying to cluster 4.7 million cells.

<img width="882" height="789" alt="Image" src="https://github.com/user-attachments/assets/e4078c2f-5457-4dd8-b219-17690ed80778" />
