### ISSUE TITLE
reduction parameter in RunUMAP FindNeighbors and FindClusters

### ISSUE THREAD

**Issue by Alexis-Varin** [satijalab/seurat#8520]
Hello, I have been extensively analysing CCA integrated data with Seurat 4 for quite some time and never set the reduction parameter of RunUMAP to anything other than the default "pca".

However after updating to Seurat 5 and while checking the vignettes I noticed that in the integration [vignette](https://satijalab.org/seurat/articles/seurat5_integration) you now specify "integrated.cca" (or any other integration done) :

`obj <- FindNeighbors(obj, reduction = "integrated.cca", dims = 1:30)`
`obj <- FindClusters(obj, resolution = 2, cluster.name = "cca_clusters")`
`obj <- RunUMAP(obj, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")`
 
Is this new behavior ? Was it implemented in Seurat 4 already ? The documentation for ?RunUMAP reduction parameter still indicates :

`Which dimensional reduction (PCA or ICA) to use for the UMAP input. Default is PCA`

so no update on this new use.

Thanks

**Comment by Alexis-Varin** [comment]
Here are two examples of the same dataset with reduction parameter of RunUMAP set to either "pca" or "integrated.cca"

![RunUMAP pca](https://github.com/satijalab/seurat/assets/149001252/5566b5a6-6f25-4ea5-9958-2b63737b6844)
![RunUMAP integrated cca](https://github.com/satijalab/seurat/assets/149001252/8480476b-bcd1-43cd-a5c3-2f7eccc58524)

**Comment by longmanz** [comment]
Hi,
If you have integrated your datasets and wish to use the CCA embeddings for FindNeighbors() or RunUMAP(), you will need to specify this when running the functions. In the Seurat v4 vignette (https://satijalab.org/seurat/articles/integration_introduction), we did specify "integrated.cca" for these two functions. 

But it is possible that in some earlier versions of our vignette, we did not specify "integrated.cca". 

As for the two UMAPs you provided, do you mean you see a poorer clustering when using "integrated.cca" (the bottom figure)? In the case where the integration did not work well, you may also consider using reference mapping with Azimuth.
