### ISSUE TITLE
write10xCounts() finding information for gene.symbol in Seurat v5.0.1 Object

### ISSUE THREAD

**Issue by cfausto** [satijalab/seurat#8523]
Hello,

I am trying to create a single cell reference using a Seurat v5.0.1 object and following the vignette [here](https://www.10xgenomics.com/analysis-guides/creating-single-cell-references-for-xenium-custom-panel-design-from-seurat-or-anndata). 

I am specifically trying to do "Option 1: Save MEX files with DropletUtils", and am running into issues with finding the gene.symbol parameter when using [write10xCounts()](https://rdrr.io/github/MarioniLab/DropletUtils/man/write10xCounts.html).

I tried to fix this error based on this [issue post](https://github.com/satijalab/seurat/issues/8214), and changed `meta.features` to `meta.data`.

When running the code below:

`write10xCounts(
  "reference_data",
  GetAssayData(seurat_obj, assay="RNA", slot="counts")[, subset],
  gene.id = rownames(seurat_obj),
  gene.symbol = GetAssay(seurat_obj)@meta.data[["feature_name"]],
  barcodes = colnames(seurat_obj)[subset],
  type = "sparse",
  version = "3")`

I receive this error:

`Error in write10xCounts("reference_data", 
GetAssayData(seurat_obj, assay = "RNA",  : 
  lengths of 'gene.id' and 'gene.symbol' must be equal to 'nrow(x)'`

I am trying to find where `feature_name` can be located, and am not familiar with looking in-depth into Seurat Objects. I appreciate any help!

**Comment by zskylarli** [comment]
Hi - since Seurat object metadata corresponds with cell information and should not contain feature names/gene symbols, you may need to manually obtain a mapping of your gene IDs to gene symbols and input that to write10xCounts, such as using an annotation package (i.e. EnsDb.Hsapiens.v79). 

```
library(EnsDb.Hsapiens.v79)
edb <- EnsDb.Hsapiens.v79
gene.symbols <- mapIds(x = edb, keys = rownames(seurat_obj), column = "SYMBOL", keytype = "GENEID")
```

If you have further questions, feel free to reopen this issue.
