### ISSUE TITLE
RPCAIntegration on SCT assay

### ISSUE THREAD

**Issue by Alexis-Varin** [satijalab/seurat#8525]
Hello, I have run `SCTransform()` and `RunPCA()` on my object and am ready to integrate with `RPCAIntegration` and 6 references on the `SCT` assay :

`RPCAintegrated = IntegrateLayers(obj, method = RPCAIntegration, orig.reduction = "pca", new.reduction = "integrated.rpca", normalization.method = "SCT", assay = "SCT", reference = c(1,4,7,9,12,21))`

But first I want to check if my references are correct with `Layers()` :

`Layers(obj, assay = "SCT", search = "data")[c(1,4,7,9,12,21)]`
`NA NA NA NA NA NA`

Now this result is expected because the `SCTAssay` does not support layers, but then how does the `RPCAIntegration` pull the correct references from the `SCT` assay if there is just a single `data` layer ? Does it pull from the `RNA` assay instead ?
As `Layers(obj, assay = "RNA", search = "counts")[c(1,4,7,9,12,21)]` give me the correct layers I want for references. Can I trust that these samples will be the ones used for integration and from the `SCTAssay` ?

I know that there will be in the near future clarifications about `SCTransform` pipeline and Seurat 5 integration but I just want to be sure that I am correctly integrating as of now.

The integration does run fine so no problem on that side, I am just curious how can the `RPCAIntegration` work given the `SCTAssay` `data` layer is not split and it therefore cannot pull the split references from it.

Thanks

**Comment by zskylarli** [comment]
Yes - as shown in this [vignette](https://satijalab.org/seurat/articles/integration_introduction#perform-integration-with-sctransform-normalized-datasets), as long as you specify your normalization method to be SCT, we handle splitting the object internally. The code is [here](https://github.com/satijalab/seurat/blob/656fc8b562d53e5d0cedda9e09d9dda81e8c00e9/R/integration5.R#L378C3-L389C6) for your reference if you want to look into it further.Please feel free to reopen the issue if you have further questions/comments!
