### ISSUE TITLE
Is there a manual for the Seurat Docker image?

### ISSUE THREAD

**Issue by mpluz** [satijalab/seurat#8527]
Hello! My data is too big to analyze directly on my computer, so I am trying to use a docker image in my group's server. I am very new to do this so I'm having difficulties figuring it out. Is there a manual in the lines of what is available for Kallisto and Bowtie2 that I could read to better understand how to use this docker image? 
Thank you for the help.

**Comment by igrabski** [comment]
Hi, please see the relevant commands at the bottom of this page [here](https://satijalab.org/seurat/articles/install.html), and feel free to re-open this issue if you run into any problems!
