### ISSUE TITLE
Question about harmony in v5

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8528]
Harmony can integrate over multiple covariates such as
seuratObject <- RunHarmony(seuratObject,  group.by.vars = c("dataset", "donor", "batch_id"))

with v5 how to  specify a vector covariates to integrate?

object <- IntegrateLayers(
  object = object, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony",
  verbose = FALSE
)

**Comment by igrabski** [comment]
Hi, please see [@8136](https://github.com/satijalab/seurat/issues/8136). The main idea is to make a new metadata covariate that combines your covariate of interests, and then to split layers by that covariate.

**Comment by RobinCarvajal** [comment]
what about the theta argument? how do you adjust that for each covariate?

**Comment by Jaimelan** [comment]
I have run into this same question, what about the theta parameter to define the strength of each covariate, has this just dissapeared?
