### ISSUE TITLE
Cell Cycle Regression with Human to Mouse Gene Conversion 

### ISSUE THREAD

**Issue by calinep** [satijalab/seurat#8529]
Hello,

I am essentially trying to reproduce some clustering results from a dataset (AML cells) and I am trying to regress out some cell cycle genes as per Seurat Cell Cycle Scoring and Regression Vignette. One question is can I get some guidance on how I can convert the list of genes from human to mouse homolog genes before scoring and regression steps? I want to look at all phases of the cell cycle. Any help would be welcome!

**Comment by longmanz** [comment]
Hi,
I personally use the reference from JAX lab at (http://www.informatics.jax.org/downloads/reports/HOM_MouseHumanSequence.rpt) for such conversion. You can easily convert human gene symbols to mouse ones based on this.
