### ISSUE TITLE
Converting Seurat 5 to AnnData

### ISSUE THREAD

**Issue by GreenGilad** [satijalab/seurat#8531]
Hi Seurat team,

I am trying to convert a Seurat 5 object to AnnData but not managing. The specific object is the harmonized result of 2 BPCells Seurat objects created as follows:

```
write_matrix_dir(readRDS("counts1.rds"), dir = "counts1", overwrite=T)
obj1 <- CreateSeuratObject(counts = open_matrix_dir("counts1"), project = "object1")

write_matrix_dir(readRDS("counts2.rds"), dir = "counts2", overwrite=T)
obj2 <- CreateSeuratObject(counts = open_matrix_dir("counts2"), project = "object2")

obj <- merge(obj1, obj2)
rm(obj1, obj2)

obj <- SCTransform(obj, vst.flavor = "v2", variable.features.n = 4000, verbose = F)
obj <- RunPCA(obj, npcs = 30, verbose = F)
obj <- IntegrateLayers(obj, method = HarmonyIntegration,
                       orig.reduction = "pca", new.reduction = "integrated.harmony",
                       assay = "SCT", verbose = FALSE)
obj <- FindNeighbors(obj, reduction = "integrated.harmony", dims = 1:30, verbose=F)
obj <- FindClusters(obj, resolution = .5, cluster.name = "harmony.clusters.0.5", verbose=F)
obj <- RunUMAP(obj, reduction = "integrated.harmony", dims = 1:30, reduction.name = "umap.harmony", verbose=F)

ad <- reticulate::import("anndata", convert = FALSE)
obj.ad <- Convert(from=obj, to="anndata", filename="converted.object.h5ad")
```

The last row, of converting to AnnData throws:

```
Error in Convert(from = obj, to = "anndata", filename = "converted.object.h5ad") : 
  argument "source" is missing, with no default
```

I've seen a [similar issue](https://github.com/satijalab/seurat/issues/8141) where the suggestion was to first save as H5Seurat and then covert to AnnData. Besides not wanting to store this temporary-intermediate H5Seurat object, it also does not work (probably because of the object using BPCells):

```
> SaveH5Seurat(obj, "object.h5Seurat")
Creating h5Seurat file for version 3.1.5.9900
Error in attr$write(robj) : Error writing dataset
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So I believe based on previous comments here that SeuratDisk (Convert function) is no longer actively being maintained.

I have recently implemented new function `as.anndata` in my package scCustomize.  It supports both Seurat 5 and v3/4 objects.  See vignette here: https://samuel-marsh.github.io/scCustomize/articles/Object_Conversion.html#convert-seurat-or-liger-objects-to-anndata-objects

Best,
Sam

**Comment by JAMKuttan** [comment]
Also not a dev team member here, just a user. 
I also do this and it seems to work.

scObj[["RNA"]] <- as(scObj[["RNA"]], "Assay")
sceasy::convertFormat(scObj, from="seurat", to="anndata",
                      outFile='AnnData.h5ad')

**Comment by samuel-marsh** [comment]
Hi @JAMKuttan,

Yes, I based my functions off of sceasy in part but scCustomize’s will work without needing to convert between assay formats and can work for either Assay5 or Assay objects.  Unfortunately sceasy appears to not be actively maintained which is why it doesn’t work for V5 objects.

Best,
Sam

**Comment by samuel-marsh** [comment]
I’ve also include converter for to reformat assay between Assay and Assay5 in either direction as needed.

https://samuel-marsh.github.io/scCustomize/reference/Convert_Assay.html

**Comment by Gesmira** [comment]
Amazing Sam! Thank you! 
Closing now and we'll recommend users to use your function for converting to AnnData for objects with v5 assays in the future. 
Best, 
Gesi

**Comment by rkulchar** [comment]
Hi! Thanks so much... I get this error when I try this: 

> as.anndata(x = st, file_path = "/home/ICI", file_name = "st_anndata.h5ad")
• Checking Seurat object validity & Extracting Data
Error in as.anndata():
! main_layer must be one of counts.1, counts.2, counts.3, counts.4, data.1, data.2, data.3, and data.4
Run rlang::last_trace() to see where the error occurred.

My st structure is this:
An object of class Seurat
541 features across 280758 samples within 4 assays
Active assay: Xenium (280 features, 280 variable features)
9 layers present: counts.1, counts.2, counts.3, counts.4, data.1, data.2, data.3, data.4, scale.data
3 other assays present: BlankCodeword, ControlCodeword, ControlProbe
2 dimensional reductions calculated: pca, umap
4 spatial fields of view present: fov fov.2 fov.3 fov.4

**Comment by rkulchar** [comment]
Thanks @samuel-marsh . Do you have any advice on how I can transfer spatial assays from R to Python? I've tried so many different packages but nothing seems to work!

**Comment by calafell** [comment]
Hi @samuel-marsh,

I'm also trying to save an h5ad file using scCustomize for my Xenium data. While I can save the file successfully, the @images slot is not retained. Do you know how I could include this slot in the h5ad file or add it later to the Python object?

I’d really appreciate any guidance on this.

Thank you so much for your help!

Best,

**Comment by thisismuskaangupta** [comment]
Hi

The following function may be useful for you, to add an image to your anndata object.

https://stlearn.readthedocs.io/en/stable/api/stlearn.add.image.html
