### ISSUE TITLE
Dotplot does not support change the size of x-axis?

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#854]
Dear author,
there seems no params to set the size of x-axis, thanks a lot.

![image](https://user-images.githubusercontent.com/25199946/46989055-183aaf00-d12e-11e8-9d1e-380753043e4e.png)

**Comment by 2236529177** [comment]
maybe we should reset the theme of  ggplot2 just like follows
![image](https://user-images.githubusercontent.com/25199946/46990163-8ed9ab80-d132-11e8-8d33-28b4af3f0033.png)

**Comment by mschilli87** [comment]
@2236529177:
You can set `do.return = TRUE` and modify the `ggplot2` object afterwards:

```r
p <- DotPlot(..., do.return = FALSE)
p + theme(axis.text = element_text(size = ...))
```
