### ISSUE TITLE
non-zero exit status

### ISSUE THREAD

**Issue by bebejhun** [satijalab/seurat#8540]
After I installed Seurat(R4.2.1), these warning messages appears.

✔ Package 'Seurat' successfully installed.
Warning messages:
1: In utils::install.packages("leiden", repos = "https://cloud.r-project.org") :
  installation of package ‘leiden’ had non-zero exit status
2: In utils::install.packages("Seurat", repos = "https://cloud.r-project.org") :
  installation of package ‘igraph’ had non-zero exit status
3: In utils::install.packages("Seurat", repos = "https://cloud.r-project.org") :
  installation of package ‘leiden’ had non-zero exit status
4: In utils::install.packages("Seurat", repos = "https://cloud.r-project.org") :
  installation of package ‘Seurat’ had non-zero exit status
  
  I also tried to download each package, but I still get the same error.
  I found out that there are no packages in the file directory. (I think this is because of the warning below)
  
  In file included from vendor/cigraph/src/community/optimal_modularity.c:32:0:
vendor/cigraph/src/internal/glpk_support.h:39:10: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
          ^~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'vendor/cigraph/src/community/optimal_modularity.o' failed
make: *** [vendor/cigraph/src/community/optimal_modularity.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/iamgojasper/R/x86_64-pc-linux-gnu-library/4.2/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status
ERROR: dependency ‘igraph’ is not available for package ‘leiden’
* removing ‘/home/iamgojasper/R/x86_64-pc-linux-gnu-library/4.2/leiden’
Warning in install.packages :
  installation of package ‘leiden’ had non-zero exit status
ERROR: dependencies ‘igraph’, ‘leiden’ are not available for package ‘Seurat’
* removing ‘/home/iamgojasper/R/x86_64-pc-linux-gnu-library/4.2/Seurat’
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status
  
  Does anyone know here how to solve this? I'm new in using Seurat. Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

So this appears to be compilation error related to the igraph package and not issue with Seurat.  I would recommend posting to igraph repo for help resolving the issue.

Best,
Sam

**Comment by caodudu** [comment]
Seurat you tried to install failed actually. You can fix it by exploring its calling chain: Seurat → leiden → igraph → glpk.  An appropriate solution is compiling glpk additionally. For example, please try the command 'conda install conda-forge::glpk' if R locates in an anaconda environment.
