### ISSUE TITLE
Cell cycle regression before integeration causes error during integration

### ISSUE THREAD

**Issue by Shubhra1994** [satijalab/seurat#8542]
Hello,
I have 7 samples which I first merge into single object.
```
mut1_h5 <- Read10X_h5("m1_filtered_feature_bc_matrix.h5",use.names = T)
mut1_seur <- CreateSeuratObject(mut1_h5, project = "mut1_h5")
```
I read all the samples like this.
```
merged_object=merge(mut1_seur,c(mut2_seur,mut3_seur,mut4_seur,wt1_seur,wt2_seur,wt3_seur),
                 project ="x"
                 )
               
```
After this I run NormalizeData, FindVariableFeatures,ScaleData. I know there is a strong effect of cell cycle so I want to mitigate it.
I run CellCycleScoring on this merged object.
```
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
merged_object <- CellCycleScoring(merged_object, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
merged_object$CC.Difference <- merged_object$S.Score - merged_object$G2M.Score
merged_object <- ScaleData(merged_object, vars.to.regress = "CC.Difference", features = rownames(merged_object))

```

After this I run RunPCA, FindNeighbors , FindClusters and RunUMAP on this regressed object. 

But as soon as I run IntegrateLayers on this object

```
merged_object_filt_ccregressed_integrated_seurat <- IntegrateLayers(object = merged_object, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = TRUE)

```
, It gives me an error:
Finding all pairwise anchors

> Error in UseMethod(generic = "Assays", object = object) : 
>   no applicable method for 'Assays' applied to an object of class "NULL"
> Calls: IntegrateLayers ... FUN -> DietSeurat -> unique -> unlist -> lapply -> Assays
> Execution halted
>  

When I print 

```
Assays(merged_object)
Layers(merged_object)

```
I get

> Slot "data":
> List of length 1
> 
> [1] "counts"     "data"       "scale.data"

Any idea what is happening. Are the order of steps wrong?

**Comment by zskylarli** [comment]
Hi - since I don't have access to your objects, I can only assume this error is due to your merging step. Instead of passing in the six samples as a vector (which is probably why IntegrateLayers is finding a NULL class in the object instead of an Assay), you will need to merge pairwise and then proceed to create the right structure. Please let me know if you have further questions. 

```
objects_to_merge = [mut1_seur, mut2_seur, mut3_seur, mut4_seur, wt1_seur, wt2_seur, wt3_seur]
while len(objects_to_merge) > 1:
    # Merge the first two objects and append the result to the end of the list
    merged = merge(objects_to_merge.pop(0), objects_to_merge.pop(0), project="x")
    objects_to_merge.append(merged0
merged_object = objects_to_merge[0]
```
