### ISSUE TITLE
FeatureScatter group.by parameter with continuous variables

### ISSUE THREAD

**Issue by rocanja** [satijalab/seurat#8562]
Hello Seurat Team, it would be great if the group.by parameter of the `FeatureScatter()` function could also take continuous variables and then color the points with a color gradient eg. to overlay the scatter plot with the expression level of a gene or the percentage of mitochondrial reads etc. At the moment it seems to only accept distinct variables, or have I missed something? 
I have also tried adding a ggplot2 geom_point() layer to `FeatureScatter()`, but that doesn't seem to work either. As a workaround, I know that I can extract the respective columns from the seurat object and then just plot with ggplot2, but it would be neat if `FeatureScatter()` could handle it as well. Love your package, keep doing the great work you do!

UPDATE: I just came across the [scCustomize](https://samuel-marsh.github.io/scCustomize/articles/QC_Plots.html) package which has some really nice QC plotting functions that can do overlays with continuous variables.

**Comment by igrabski** [comment]
Thanks for the suggestion! Unfortunately, our bandwidth is limited so we won’t be able to include this in our roadmap at this time. We’ll circle back to this once our resources allow. That said, `scCustomize` certainly has some very nice options and hopefully is a good workaround at this time!
