### ISSUE TITLE
IntegrateLayers warning, does it affect my results?

### ISSUE THREAD

**Issue by chungsai** [satijalab/seurat#8563]
Hello, 

I was just rnning 
AllMP <- IntegrateLayers(
  object = AllMP, method = HarmonyIntegration,
  orig.reduction = "pca", new.reduction = "harmony", normalization.method = "SCT",
  verbose = FALSE
)

And although it succeeded, it gave me this warning 

 did not converge in 25 iterations 

and this warning
3x.

#Quick-TRANSfer stage steps exceeded maximum (= 8531550)

I was wondering if this affects my results, and if I could fix it if it does

Thanks,,

As an aside, I am also getting errors for another reduction methods.

For RPCA, I get
Error in FindWeights(object = merged.obj, integration.name = integration.name,  : 
  Number of anchor cells is less than k.weight. Consider lowering k.weight to less than 70 or increase k.anchor.

For FastMNN, I get

Error in checkBatchConsistency(batches, cells.in.columns = TRUE) : 
  number of rows is not the same across batches (see batch "normalization.method"
This is on a SCTransformed object with 18 layers.

**Comment by ollieeknight** [comment]
you can add the option `max.iter.harmony = x` into `IntegrateLayers`, if you want to increase the convergence possibility. Nevertheless I've not had issues with when it's not converged.

As for the second question, it's worth checking how many cells you have in each layer. each layer needs to be larger than 70 I think you might be able to add `k.weight = NA`

**Comment by rsatija** [comment]
Thanks for the complete answer here. It seems that most of these integration methods are having difficulty identifying cells in matched biological states in your data. This is why Harmony is having difficulty converging, and why Seurat is returning a very small number of anchors.

There are not easy solutions in this case, but if there is minimal overlap of biological populations in your data, you likely want to proceed without performing integration.
