### ISSUE TITLE
R crashes on execution of updateSeuratObject

### ISSUE THREAD

**Issue by skohli01** [satijalab/seurat#8565]
I have installed seurat 5.0 and trying to load a .rds file but when I execute following code R Studio crashes
pbmc = readRDS(file = "myfile.rds")
pbmc.updated = UpdateSeuratObject(object=pbmc)

> packageVersion("Seurat")
[1] ‘5.0.0’

can someone please help?

**Comment by ollieeknight** [comment]
how big is your file, with how many features, cells, assays? what is it that's crashing, if you get that output?

**Comment by skohli01** [comment]
input file is 4GB, Iam reading RDS file and after that this line of code crashes (gets message R fatal error)
sox2ip.updated = UpdateSeuratObject(object=sox2ip)

**Comment by ollieeknight** [comment]
I think you'll have to reinstall R and seurat. It's a small file and shouldn't be causing such errors

**Comment by igrabski** [comment]
Please try this with the current version of `Seurat` and `SeuratObject` and that should address your issue. If the problem persists, please feel free to open a new issue!
