### ISSUE TITLE
Failed to retrieve gene counts per cell

### ISSUE THREAD

**Issue by trandoanduyhai** [satijalab/seurat#8567]
We got problem to retrieve gene counts per cell of a Seurat object (12 samples aggrated by Cellranger). The code is:
write.table(disco@assays[["RNA"]]@counts, file=‚/path/Gene_Count_per_Cell.tsv', quote=FALSE, sep='\t', col.names = TRUE)
--> None of requested variables were found.
My seurat object is shown below. It would be extremely helpful if you could assist me to solve this problem. Thank you in advance!

![image](https://github.com/satijalab/seurat/assets/10762388/c981c696-7f2a-443e-93d3-5262f864370a)

**Comment by Gesmira** [comment]
To access the counts of an Assay5 assay you should use the **$** not the **@**.  The following should work normally: `obj@assays[["RNA"]]$counts`
