### ISSUE TITLE
Is there anyway to speed up the IntegrateLayers?

### ISSUE THREAD

**Issue by warming151** [satijalab/seurat#8572]
I have a big dataset and I already run IntegrateLayers step for 70 hours and it's still running... Is there anyway to speed up for example using Parallelization or something else? Thanks!

**Comment by mhkowalski** [comment]
Hello, 

For very large datasets,  I'd recommend checking out our [vignette](https://satijalab.org/seurat/articles/parsebio_sketch_integration),  where we demonstrate using on-disk data storage as well as a "sketch" integration strategy, where we perform integration on a representative sample of the data and project the resulting dimension reduction onto to the full dataset.  I hope this is helpful.
