### ISSUE TITLE
Improving Reproducibility: avg_log2FC_V4 Estimates in Seurat V5 (`FindAllMarkers()` and `FindMarkers()`)

### ISSUE THREAD

**Issue by tim-meese** [satijalab/seurat#8573]
Dear Seurat developers,

I appreciate the robustness of Seurat V5, especially the option to set `test.use` to “wilcox_limma” for reproducing results from Seurat V4. However, I’ve noticed that the avg_log2FC values calculated by both `FindAllMarkers()` and `FindMarkers()` in Seurat V5 are nearly identical, regardless of the test used (default “wilcox” or “wilcox_limma”). The p-values and adjusted p-values also align closely, **however there are large discrepancies between the estimated avg_log2FCs between V4 and V5, especially for lowly expressed genes.**
![image](https://github.com/satijalab/seurat/assets/129525975/c36de9dd-daf2-403f-9cf8-9de69cbdd836)
![image](https://github.com/satijalab/seurat/assets/129525975/acaf8640-da47-45f3-bd1d-41b3d522c267)

If this is consistent across datasets, it seems unnecessary to run “wilcox_limma” since it yields the same results but at a slower pace than the default implementation. **For the sake of reproducibility, I propose including both avg_log2FC_V5 and avg_log2FC_V4 in the results.**

Thank you for your consideration.

Best regards, 
Tim

**Comment by mhkowalski** [comment]
Hi Tim, 

Thank you for your thoughtful comments. I'll note that the logFC calculation is the same regardless of the test used, as long as the tests both use the same `slot` (which is true of wilcox and wilcox_limma). We expect there to be a discrepancy between seurat4 and seurat5 logFC values, (see this [announcement](https://satijalab.org/seurat/articles/announcements)). We're not planning on supporting both logFC calculations in the future (we think our updated calculation more accurately reflects the underlying data). 

Regarding ```wilcox``` vs ```wilcox_limma``` p-values, the ```wilcox``` method employs presto's fast Wilcoxon test, which uses a Gaussian approximation to increase speed (see the presto package for more details).  Therefore, ```wilcox``` and ```wilcox_limma``` p-values will not be identical in all cases, but we think for the majority of users, the speed-up is worth using this approximation.

I hope this is helpful.
