### ISSUE TITLE
Matrix compression performs poorly with non-integers.

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8577]
> write_matrix_dir(mat = data, dir = gsub(".h5ad", "_BP", file.path))
Warning: Matrix compression performs poorly with non-integers.
• Consider calling convert_matrix_type if a compressed integer matrix is intended.

i downloaded an h5ad atlas from internet and i am in the process of converting it to .rds to do label transfer by seurat. i just do not understand why the need to convert into integers. the logic behind this warning. what would be the drawbacks to leave as is or to convert. thank you.

**Comment by rsatija** [comment]
This reflects the way that the BPCells package streams data in from disk efficiently (the bit-packing core of the method is most efficient when using integers.
