### ISSUE TITLE
Mixscape eccite$NT typo error?

### ISSUE THREAD

**Issue by strawberry098** [satijalab/seurat#8578]
In the mixscape vignette, `eccite$NT` is not present in the Seurat object metadata table.  Is there a typo?

# Calculate percentage of KO cells for all target gene classes.
`df <- prop.table(table(eccite$mixscape_class.global, eccite$NT),2)`

**Comment by longmanz** [comment]
Hi, 
Can you provide your sessionInfo() of your `Seurat` and `SeuratData` package? Testing from my end, we can see the "NT" column is present in the `eccite@meta.data` (see below):
![Screen Shot 2024-03-15 at 2 17 46 PM](https://github.com/satijalab/seurat/assets/8408639/1fd85443-249c-4517-bf42-d0629fe1d817)

**Comment by strawberry098** [comment]
@longmanz 

I'm using a dataset from an arrayed CRISPR experiment rather than a pooled screen.  After renaming my control sample as "NT", I was able to follow through with the analysis.  Thank you!
