### ISSUE TITLE
Normalization method

### ISSUE THREAD

**Issue by jial2** [satijalab/seurat#858]
I am using Seurat to do filter and normalization. Currently I am using default method “LogNormalize”, but my colleague suggested using “BISCUIT” or other methods, I don’t know if Seurat can run BISCUIT or other normalization methods. It is not clear in the help document for function NormalizeData. Could you please let me know?

Thanks

**Comment by satijalab** [comment]
We do not have support for BISCUIT, but you can explore this method on a GitHub repo from the authors:
https://github.com/sandhya212/BISCUIT_SingleCell_IMM_ICML_2016
