### ISSUE TITLE
Reconstruct original data shape following harmony normalization

### ISSUE THREAD

**Issue by leeleavitt** [satijalab/seurat#8584]
We want to normalize our data using `Harmony`, but need the original shape of the data to use in other portions of our analytical pipeline.

For example we want to run normalization and then "gate" this newly normalized data for flow cytometry. 

From my investigation into `Seurat` and `Harmony`, `Seurat` provides PCA embeddings to the `Harmony` algorithm, which returns the same embeddings, but now normalized.

Since `Seurat` uses SVD to create the PCA embeddings, it seems that I should be able to reconstruct the original dataset where the U, S, and V matrices are multiplied back together to reconstruct the original data shape.

**Comment by alikhuseynov** [comment]
I think you mean batch correction/integration of samples in this case, not the normalization of gene expression counts. I don't recall that harmony has gene expression normalization algorithm. 
If you want just to use `harmony`, you can run stuff on count matrix, [see this](https://portals.broadinstitute.org/harmony/articles/quickstart.html#normalized-gene-matrix)

**Comment by igrabski** [comment]
In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
