### ISSUE TITLE
error in evaluating the argument 'x' in selecting a method for function 't': Missing directory:

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8585]
i followed this vignette to create  a seurat object then moved it to a different computer to do normalization etc.., so the path changed for the BP folder.  it is still looking for the old path of where the folder was placed in the old computer. I repeated the steps to create the folder again but I am just posting this to report this issue and know how to avoid it in the future.

> seurat_object <- NormalizeData(seurat_object)
Normalizing layer: counts
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 't': Missing directory: /mnt/a7619626-ad19-4d93-b171-74df6ad5b303/folder1/object_BP

**Comment by igrabski** [comment]
Thanks for posting, your workaround should solve this issue!

**Comment by NadineBestard** [comment]
I got this error using a seurat object that some collaborators shared with me. I figure it was "BP" related, as the "BPCells" package is automatically loaded.

From [this BPcells vignette](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html#saving-seurat-objects-with-on-disk-layers), it seems that the only option is for the collaborators to reconvert to in-memory matrix before sharing. 
But from your message, it looks like you were able to "repeat the steps to create the folder again". How did you do that?

Thank you
