### ISSUE TITLE
MACSima derived fluorescence intensity

### ISSUE THREAD

**Issue by patrick-willems** [satijalab/seurat#8586]
Best,

I am helping in a project where average fluorescence intensities were generated for about 4000 cells and 120 channels/proteins. I re-formatted these data in a sort of 10X object and read into Seurat. Using the default options works fine, with the code below:

seuratObj <- CreateSeuratObject(counts = data, min.cells = 3, min.features = 2) %>%
  AddMetaData(metaData)   %>%
  NormalizeData() %>%
  FindVariableFeatures(selection.method = "vst") %>%
  ScaleData()  %>%
  RunPCA(nfeatures.print=1)

However my question is whether this is acceptable or one should use different normalisation procedures like CLR in Cite-seq data? Or SCTransform? Below here is an image of a typical distribution of intensity for a single protein.

EDIT: There are no missing values in this dataset.

![example](https://github.com/satijalab/seurat/assets/34685749/1959d562-24e7-44c8-9aa9-29fe1f820808)

Thanks in advance!
Patrick

**Comment by igrabski** [comment]
In an effort to more promptly address user issues, we’ve started asking users to direct analysis questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
