### ISSUE TITLE
Where do I find a matrix similar to the "integrated" assay of earlier versions?

### ISSUE THREAD

**Issue by philoel** [satijalab/seurat#8588]
(details for how the Seurat object in question was made are in a .txt file, attached; it should be a quick/easy read)

I'm trying to adapt code in a script I wrote (from pre-v5 of Seurat) which expects me to be able to fetch a matrix or dataframe from the integrated assay of my dataset, like so:

```
# First, we create an average expression matrix, just on the 'integrated' assay
celltype_avgexp <- AverageExpression(object = seurat_object, 
    return.seurat = F, 
    verbose = F, 
    assays = 'integrated')
celltype_avgexp.rna <- celltype_avgexp$integrated # we still have to select it otherwise matrix computations won't work
```
I then coerce to a matrix, log2p transform it, and then transpose it, make a distance matrix from it, and then build a neighbour-joining tree with the APE package, like so:

```
celltype_avgexp.matrix <- as.matrix(celltype_avgexp.rna)
celltype_avgexp.matrix.log2p <- log2(celltype_avgexp.matrix+1)
celltype_avgexp_t <- t(celltype_avgexp.matrix.log2p) # transpose in preparation for making distance matrix
celltype_avgexp_matrix_dist <- dist(celltype_avgexp_t, method = "euclidean") # turn to a distance matrix
celltype_avgexp_matrix_tree <- ape::nj(celltype_avgexp_matrix_dist) # does a NJ tree (no bootstrapping)
```
The problem is that after integrating in the new way enabled by Seurat v5, the new object format does not seem to store the outputted things I expect to see in a way that I can find. 

What can I do to prepare a matrix similar to the one I needed for the code I have that exists? In the end, I just need something I can eventually poke and prod into a distance matrix. I've had a pretty strong cup of coffee and I haven't been able to intuit it on my own.

When I type the name of the Seurat object in the console to inspect what it is, the result is:

```
An object of class Seurat 
18304 features across 23432 samples within 1 assay 
Active assay: RNA (18304 features, 2000 variable features)
 13 layers present: counts.SN053, counts.SN092_s, counts.SN013, counts.SN160, counts.SN178, counts.SN014, data.SN053, data.SN092_s, data.SN013, data.SN160, data.SN178, data.SN014, scale.data
 3 dimensional reductions calculated: pca, integrated.cca, umap.cca
```

When I JoinLayers(), I still don't get anything that seems like an integrated assay:
```
An object of class Seurat 
18304 features across 23432 samples within 1 assay 
Active assay: RNA (18304 features, 2000 variable features)
 3 layers present: data, counts, scale.data
 3 dimensional reductions calculated: pca, integrated.cca, umap.cca
```

In previous work, I learned that making a tree off the integrated assay gave me a tree topology that reflected signal in the data that I was looking for, and I was able to make good use of it; using the RNA assay gave completely bonkers topology. This is why I do not use the RNA assay now. 

Now, I am repeating this analysis but with some fresh data, and need something like what existed before. 

Any tips?

[workflow_to_prep_datasets.txt](https://github.com/satijalab/seurat/files/14524402/workflow_to_prep_datasets.txt)

**Comment by igrabski** [comment]
Hi Phil, we no longer output the integrated assay that we did in previous versions of Seurat, since we don't recommend its usage in typical downstream analysis. If you need it for your particular purpose, I would recommend using an older version of Seurat.
