### ISSUE TITLE
VlnPlot(), split.by = "group", split.plot = T

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#8592]
Hi,
I use VlnPlot to plot marker genes and split by two group, sometimes group1 is on the left side, sometimes on the right  side, does anyone know how to fix this problem?

![image](https://github.com/satijalab/seurat/assets/43404279/037a261b-9487-4873-819d-3657cd7fc76b)

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  This is issue only with the old visualization style for split violins.  See response from dev team here:
https://github.com/satijalab/seurat/issues/3007#issuecomment-629310216.

The newer style splits are better visualization and don't suffer from this issue.

Best,
Sam

**Comment by yulchen810** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. This is issue only with the old visualization style for split violins. See response from dev team here: [#3007 (comment)](https://github.com/satijalab/seurat/issues/3007#issuecomment-629310216).
> 
> The newer style splits are better visualization and don't suffer from this issue.
> 
> Best, Sam
Hi,
I use Seurat version ‘4.3.0.1’, which sometimes has this problem. but my analysis is almost done, so I may not upgrade Seurat to the newest version.
Thank you!
Best

**Comment by samuel-marsh** [comment]
Hi @yulchen810,

The "new" plotting option is already in Seurat v4.  I was just clarifying between new vs old styles of split violins.  Simply leave `split.plot = FALSE` and it will render with the new style.

Best,
Sam

**Comment by yulchen810** [comment]
> Hi @yulchen810,
> 
> The "new" plotting option is already in Seurat v4.  I was just clarifying between new vs old styles of split violins.  Simply leave `split.plot = FALSE` and it will render with the new style.
> 
> Best,
> Sam

I see. 
Thank you.
