### ISSUE TITLE
Joining layers on multimodal data 

### ISSUE THREAD

**Issue by Samir1703** [satijalab/seurat#8593]
Hello, 

I'm kinda new to single cell data analysis and I'm handling multimodal data. I have run cite-seq and have 6 samples with RNAseq and ADT surface protein expression. So i have an object with 2 assays : RNA and ADT

My question is when joining the layers for the 6 samples, should i join the layers of ADT together, and RNA together or should I just run join layers without specifying which assay it is ?

As in shouId I run :
Seurat <- joinlayers(Seurat)

Or :
Seurat <- joinlayers(Seurat, assay = 'RNA')
Seurat <- joinlayers(Seurat, assay = 'ADT')

**Comment by igrabski** [comment]
Hi, if you run `JoinLayers` without specifying which assay, then the layers will only be joined for whatever your default assay is set to. If you want layers to be joined for both the RNA and the ADT assays, then you should run the commands with the assay specified.
