### ISSUE TITLE
Remove jitters from VlnPlot

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#86]
Hello Seurat Team,

Is it possible to remove the jitter points from VlnPlot?  I see that the code uses geom_jitter, and simply removing that line might get me what I want, but I'm not sure how to do it when calling VlnPlot.  There seems to be no option to switch jitters off.

I looked at the package, but the main Seurat file is an RDB file, which I don't know how to modify.  So, it will be great if somebody could tell me how to avoid the jitter points in a VlnPlot.  My data has just too many of them, thus completely obscuring the kernel density shapes.

Thanks!

**Comment by b-dawes** [comment]
I actually looked into this a while back, at least back then there was no way to tell Seurat to not plot the jitter. You can remove the points manually by editing the ggplot object that Seurat returns.

This would look something like this:

```
p_list <- VlnPlot(seurat, "genename", do.ret = TRUE)
p_list[[1]]$layers <- p_list[[1]]$layers[1]
ggsave(file = "filename.pdf", plot = p_list[[1]])
```

Note that this will only work if you enter a single gene name into Seurat. If you enter in multiple gene names, Seurat applies some additional formatting to the plots.

**Comment by ryanrichholt** [comment]
You might try setting the argument `use.raw = TRUE` in the `VlnPlot()` function. It works for what I want.

**Comment by CodeInTheSkies** [comment]
Tried all suggested solutions, but to me, what actually worked was simply setting "size.use = -1".  This was just a guess, since in other usages of ggplots2, setting parameters to negatives sometimes removes features/layers.  This time, I got lucky, and my guess worked.  Thanks all for your responses.
