### ISSUE TITLE
Seurat object for stereoseq spatial data

### ISSUE THREAD

**Issue by Carissimo** [satijalab/seurat#8606]
I tried to create a Seurat object for Stereoseq spatial data , but I cannot find the information related to the image in it. How can resolve it? Is there any indication about creating a Seurat object from a .gef stereoseq file?

**Comment by MathurinD** [comment]
Hi, the stereoseq pipeline also produces a .h5ad file under 05.spatialcluster (or the output of `singularity exec $sif spatialCluster` if you run each step yourself) that can be converted to .h5seurat then loaded with:
```
library(SeuratDisk)
Convert('data.h5ad','data.h5seurat')
LoadH5Seurat('data.h5seurat')
```

The .gef file does not contain the image information, it is combined with a .ipr file by `spatialCluster`.
Note that if you have a cell segmentation the output will be in `041.cellcut`.

**Comment by igrabski** [comment]
Hi, please see [@8969](https://github.com/satijalab/seurat/issues/8969) for an example!
