### ISSUE TITLE
SCTtransform for large samples

### ISSUE THREAD

**Issue by mainyanghr** [satijalab/seurat#8609]
Dear everyone, 
I am trying to run SCTtransform for large data, please help me to debug the errors in my pipeline. 

`
run.list <- SplitObject(run, split.by = "experiment")
run.list <- lapply(X = run.list, FUN = SCTransform)

features <- SelectIntegrationFeatures(run.list)
VariableFeatures(run) <- features

run <- GetResidual(run, features = features)`

After running this, I get the errors:
`Error in GetResidual(run, features = features) : 
  RNA assay was not generated by SCTransform`

Any input will be helpful.

Thank you all

Harry

**Comment by saketkc** [comment]
Please see the integration vignette for an example of using SCTransform based integration: https://satijalab.org/seurat/articles/integration_introduction.html

You are running GetResidual() on an object which only has "RNA" assay (and no "SCT" assay").
