### ISSUE TITLE
renaming features in seurat 5

### ISSUE THREAD

**Issue by Sirin24** [satijalab/seurat#8610]
Hello I used to add a manually curated list of gene through
object@assays$RNA@counts@Dimnames[[1]] <- names

now how to do it in seurat v5?

Also, I have a question about azimuth. 
brain.mat <- Azimuth:::ConvertEnsembleToSymbol(mat = mat, species = "human")
I received this error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [www.ensembl.org:443] Operation timed out after 10000 milliseconds with 0 bytes received

**Comment by mhkowalski** [comment]
Hi, 

We don't recommend that you change the gene names in your object, but rather change the rownames of the matrix before running ```CreateSeuratObject``` (or you could make a new assay and overwrite the old assay if you have other stuff in the object you'd like to keep).

Also with your Azimuth question, that seems to happen from time to time and is related to connecting to Ensembl. Could you please try running this again?

**Comment by Sirin24** [comment]
no i am still facing the same issue with azimuth. how to make a new assay and overwrite the old assay? which do you recommend, using ensembl ids or gene names for the analysis? if using gene names. then on merging objects, how does seurat handle them? does it try to make them unique or should i make then unique before merging?
