### ISSUE TITLE
 different types of "batch effects" 

### ISSUE THREAD

**Issue by 2673380801** [satijalab/seurat#8620]
Dear author,

Hello. I have a point that I'm not quite clear about and I hope to get your answer. If we have multiple different types of "batch effects" and want to use Seurat to preprocess one type of batch effect first, then use split and IntegrateLayers successively, and then run split and IntegrateLayers functions again with the obtained low-dimensional representation, is this approach reliable? I found that it seems to throw an error when running continuously: "The following layers are already split." Is this multiple handling of different types of "batch effects" suitable for Seurat, or is it best for Seurat to only handle one type of "batch effect" at a time?

**Comment by mhkowalski** [comment]
Hello, 

We do not recommend multiple rounds of integration. You can split the layers however you see appropriately, or compare different integration strategies to see which yields the best response. A reasonable rule of thumb is to investigate what variable seems to be driving most of the clustering in the unintegrated data and integrate using this variable.
