### ISSUE TITLE
reference.reduction (UMAP) does not contain all the dimensions required by the dims parameter.

### ISSUE THREAD

**Issue by Sirin24** [satijalab/seurat#8621]
Hello, I have imported a umap to an object which I wanted to label my samples with.
Is there any way to proceed with umap projection without having to compute a new umap? also, I think the paramters are not available because it was an h5ad object.

>sample <- CreateSeuratObject(sample)
>sample <- NormalizeData(sample)
>sample <- FindVariableFeatures(sample)
>sample <- ScaleData(sample)

>object[["UMAP"]] <- CreateDimReducObject(embeddings = umap_coordinates_mt, key = "UMAP_",  global = T, assay = "RNA")
object

> object
An object of class Seurat 
59357 features across 280956 samples within 1 assay 
Active assay: RNA (59357 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 1 dimensional reduction calculated: UMAP

> anchors <- FindTransferAnchors(reference = object, query = sample, dims = 1:30, reference.reduction = "UMAP")
Error: reference.reduction (UMAP) does not contain all the dimensions required by the dims parameter.

**Comment by mhkowalski** [comment]
Hello, 

This won't work , because you are requesting 30 dimensions from a 2-dimensional reduction (UMAP). I would not recommend trying to project your data directly onto a UMAP, you should project them onto the PCs that were used to generate the UMAP. If you don't have these PCs or the UMAP model saved, this won't be possible.

**Comment by Sirin24** [comment]
Thank you, I will follow the steps to create the PCs and save the model.  I have 2 questions. I hope you can help. First do I need to correct for batches again for this reference? 
Second question: after i am finished with creating the new PCs/model, can I still use the old umap? 
so that  I use the model to transfer the cluster and subcluster cell type  annotations but then use the old umap to place the cells in the same dimension as the original reference.
