### ISSUE TITLE
SCT reproducibility / evolution between Seurat versions

### ISSUE THREAD

**Issue by MarieCoutelier** [satijalab/seurat#8624]
Hi, 

I'm trying to reproduce some analyses done on a spatial transcriptomics object. I noticed that I have different results on the clustering of an object ran with the same pipeline in April 2023 and January 2024 (end_qc_v2 and end_qc_v3, below). I tracked the difference down to the SCT assay before PCA and UMAP. 

My questions in short are : 
- **Did the SCT command evolve between Seurat v4.1.1, Seurat v4.3.0.1, then Seurat v5.0.1? I see small differences between both v4 and marked differences with v5 (no top 10 variable feature in common).**
- Can those small differences propagate to explain larger differences in PCA (up to 42) then in clustering with identical resolution chosen? 

Below is a detailed explanation if needed. 

Thank you for your help!

Marie 

----

The command saved in both objects (end_qc_v2 and end_qc_v3) are the same
```
> end_qc_v2@commands$SCTransform.Spatial
Command: SCTransform(obj, assay = "Spatial", verbose = FALSE)
Time: 2023-04-28 10:40:55.349751
assay : Spatial 
new.assay.name : SCT 
do.correct.umi : TRUE 
ncells : 5000 
variable.features.n : 3000 
variable.features.rv.th : 1.3 
do.scale : FALSE 
do.center : TRUE 
clip.range : -8.648699 8.648699 
conserve.memory : FALSE 
return.only.var.genes : TRUE 
seed.use : 1448145 
verbose : FALSE 
> end_qc_v3@commands$SCTransform.Spatial
Command: SCTransform(obj, assay = "Spatial", verbose = FALSE)
Time: 2024-01-05 16:12:49.331907
assay : Spatial 
new.assay.name : SCT 
do.correct.umi : TRUE 
ncells : 5000 
variable.features.n : 3000 
variable.features.rv.th : 1.3 
do.scale : FALSE 
do.center : TRUE 
clip.range : -8.648699 8.648699 
conserve.memory : FALSE 
return.only.var.genes : TRUE 
seed.use : 1448145 
verbose : FALSE 
```

as are the top variable features, but the difference seems to boil down to rounding approximations: 

```
> max(end_qc_v3@assays$SCT@scale.data-end_qc_v2@assays$SCT@scale.data)
[1] 1.776357e-15
> end_qc_v3@assays$SCT
SCTAssay data with 12420 features for 2244 cells, and 1 SCTModel(s) 
Top 10 variable features:
 IGKC, G0S2, SCD, NPPB, HBA2, DCN, CFD, HSPA1B, FOSB, CCL21 
> end_qc_v2@assays$SCT
SCTAssay data with 12420 features for 2244 cells, and 1 SCTModel(s) 
Top 10 variable features:
 IGKC, G0S2, SCD, NPPB, HBA2, DCN, CFD, HSPA1B, FOSB, CCL21 
```

Then the error seems to propagate in the PCA, with identical commands: 

```
> end_qc_v2@commands$RunPCA.SCT
Command: RunPCA(obj, assay = "SCT", verbose = FALSE)
Time: 2023-04-28 10:40:56.560784
assay : SCT 
npcs : 50 
rev.pca : FALSE 
weight.by.var : TRUE 
verbose : FALSE 
ndims.print : 1 2 3 4 5 
nfeatures.print : 30 
reduction.name : pca 
reduction.key : PC_ 
seed.use : 42 
> end_qc_v3@commands$RunPCA.SCT
Command: RunPCA(obj, assay = Default_assay_dim_reduction_clustering,     verbose = FALSE)
Time: 2024-01-05 16:12:50.628072
assay : SCT 
npcs : 50 
rev.pca : FALSE 
weight.by.var : TRUE 
verbose : FALSE 
ndims.print : 1 2 3 4 5 
nfeatures.print : 30 
reduction.name : pca 
reduction.key : PC_ 
seed.use : 42 
```
but larger difference in magnitude: 
```
> max(end_qc_v2@reductions$pca@cell.embeddings - end_qc_v3@reductions$pca@cell.embeddings)
[1] 42.2316
```

and I end up with a different clustering. 

My questions are hence: 
1- Is this variability in PCA / clustering linked to these slight differences in SCT only or should I look elsewhere? 

2- The small differences in SCT seem to be linked to a Seurat version change from v4.1.1 to 4.3.0.1 that unfortunately happened after one of our conda environment crashed. When I re-run the same command twice in a row with 4.3.0.1, I obtain exactly identical results, without rounding approximation. What evolved between both?

3- If I rerun SCT with Seurat v5.0.1 (which I have installed locally) and not Seurat v4.3.0.1 (the version in the conda of the pipeline), I have markedly different results with the same command. How is this explained?
```
> end_qc_v3@assays$SCT
SCTAssay data with 12420 features for 2244 cells, and 1 SCTModel(s) 
Top 10 variable features:
 **IGKC, G0S2, SCD, NPPB, HBA2, DCN, CFD, HSPA1B, FOSB, CCL21** 
> test <- end_qc_v3
> test <- SCTransform(test, assay = "Spatial", verbose = FALSE)
> test@assays$SCT
SCTAssay data with 12420 features for 2244 cells, and 1 SCTModel(s) 
Top 10 variable features:
 **NPPB, G0S2, DCN, SCD, HBA2, HSPA1B, FOSB, CFD, NPPA, FOS** 
> max(end_qc_v3@assays$SCT@scale.data-test@assays$SCT@scale.data)
[1] 11.74688
```

**Comment by jdrnevich** [comment]
I don't know about v4.1.1 vs. v4.3.0, but the default changed in v5. From https://satijalab.org/seurat/articles/sctransform_vignette: "In Seurat v5, SCT v2 is applied by default. You can revert to v1 by setting vst.flavor = 'v1'"

**Comment by saketkc** [comment]
Hi @MarieCoutelier, the default estimation has changed between Seurat v5 and Seurat v4. There were no changes between v4.1.1 to v4.3.0.1  to SCTransform's functionality. If you can provide a reproducible example, I will be happy to debug.
