### ISSUE TITLE
Weighted Nearest Neighbours with CITE-seq data

### ISSUE THREAD

**Issue by daymecita** [satijalab/seurat#8628]
Hello team!

I have a CITE-seq dataset with a panel of 28 ADTs. I reduced the dimensionality of the data and clustered cells based on the ADTs, RNA and ADT+RNA using the WNN approach described in Seurat. Using the clustering from the WNN along with the expression of marker genes and ADTs I classified my cells in 5 broad types. Then, I took Stromal cells and performed sublclustering (re-integrating samples and re-discovering HVGs, dim red on these cells). Suprisingly, cluster 6 in Stromal expressed T cells  ADTs markers and seem to be different. 
![image](https://github.com/satijalab/seurat/assets/100194518/7d8e0f86-43ba-4dab-a7a8-384de09c9792)

I highlighted cells from cluster 6 in the UMAPs obtained from al cells, and I see that on the ADT umap, these cells are with the other T cells, but in the RNA and WNN UMAPs they cluster with the Stromal cells. I don't understand this. Any thoughts about what could be the reason behind it? On the other hand, I see that the WNN umap and the RNA UMAP tend to be very similar, despite the good performance of my ADTs. Isn't the RNA taking higher weights because we use more genes than ADTs as predictors? 

![image](https://github.com/satijalab/seurat/assets/100194518/a7f50212-60dd-4920-822e-5517f2fa5e44)

**Comment by Gesmira** [comment]
Hi @daymecita, 
I would double check the gene expression markers of these cells and see if there is a reason they are clustering with the stromal cells. If you are convinced these are T cell markers, I would also recommend looking into adjusting the corresponding weights for each modality. This is described in more detail here: https://github.com/satijalab/seurat/issues/3785
