### ISSUE TITLE
Accessing *all* associated package versions of an "old" Seurat object/project? (perhaps considered also as a general R scripting/project question)

### ISSUE THREAD

**Issue by nataliapadillo** [satijalab/seurat#8629]
I am relatively new to R:
**How do I access the packageVersions() (or similar command, like sessionInfo()) of an rds object or .Rdata SEURAT object from MONTHS ago? I simply would like to know: what were all package _versions_ used at _THAT_ time (i.e.: Seurat, tidyverse, Matrix, scales, cowplot, ggplot, DropletUtils, etc etc etc)?**

For context: I am running single cell analyses with Seurat. I try restarting the session and simply loading the object to my environment-- but when I run any of the above commands, only the ambient/'current' package versions pop up (I presume they are automatically loaded when the object is), and I know those are certainly not the full extent of the packages used and I can tell they are newer versions. Therefore, I load the rest of the packages, but as expected, they have all updated to newer versions (I had highly likely done so in other single cell experiment projects I have been running at the same time). I am having dependency issues in not being able to run a function (DropletUtils) that previously worked months ago, so I want to know what package version of that function + others I used to use which worked. Makes sense?

If it cannot be retrieved, what is your preferred/favorite way to document what package versions you are using in your projects?

Thanks in advance!!

**Comment by igrabski** [comment]
In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
