### ISSUE TITLE
RunPCA with a vector of features?

### ISSUE THREAD

**Issue by sarahnjfranks** [satijalab/seurat#8633]
Hello, 

I am a new Seurat user and attempting to apply the workflow from the "Introduction to scRNA-seq integration" vignette to my own data (https://satijalab.org/seurat/articles/integration_introduction)

I've imported my data as a Seurat object
`N1.seurat <-CreateSeuratObject(N1_matrix, assay = "MP", min.cells = 0, min.features = 0, meta.data = N1_metadata)`

**I want to RunPCA, but with supplying a vector of features instead of running FindVariableFeatures()**

When I run the below code, I get the obvious expected error
`N1.seurat <- RunPCA(N1.seurat)`
Error: No variable features, run FindVariableFeatures() or provide a vector of features

What form does the vector of features need to be supplied in? When I have tried the below code with a manually supplied vector I get another error
`N1.seurat <- RunPCA(object = N1.seurat, features = N1_features)`
Error in RowVar.function(x = object) : unused argument (x = object)

Appreciate any advice!

**Comment by igrabski** [comment]
This command should work:

```
 N1.seurat <- RunPCA(object = N1.seurat, features = N1_features)
```

where `N1_features` is a character vector of your feature names. I'll close this issue for now, but if you are still having problems with this, please re-post this issue with more details about your object and what form `N1_features` takes.
