### ISSUE TITLE
Where to find harmonized embeddings after Bridge integration

### ISSUE THREAD

**Issue by alitinet** [satijalab/seurat#8639]
Hi @yuhanH,

where do I find harmonized embeddings for the reference and for the mapped query? I saw this issue #7304, but i still don't understand where to get the embeddings. My query object has `ref.Bridge.reduc` slot, so I guess for the query it's there? But my `obj.rna.ext` doesn't have `Bridge` reduction or anything like that. It does have `obj.rna.ext@assays[["Bridge"]]`, is that the cell embeddings? 

So could you please clarify 
1. that harmonized cell embeddings for the query are in `query@reductions[["ref.Bridge.reduc"]]`?
2. where do I find cell embedding for the reference?

Thank you!

**Comment by dcollins15** [comment]
Hi @alitinet ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!

**Comment by jules-samaran** [comment]
Hi @alitinet, did you find the answer to your question? I'm tempted as well to use query@reductions[["ref.Bridge.reduc"]] and obj.rna.ext@assays[["Bridge"]]
