### ISSUE TITLE
Integrated stimulated vs control pbmc dataset tutorial - filtering of cells with high mitochondrial genes?

### ISSUE THREAD

**Issue by lmacdonald12** [satijalab/seurat#864]
Hi, 

I am following your PBMC tutorial where you compare datasets of two conditions. I am just wondering why mitochondrial gene expression is not taken into account in filtering of cells? as done in individual analysis tutorial. I tried to do this myself and it appears that none of the cells express any MT genes? 

Thanks

**Comment by 2236529177** [comment]
yeah, there should be some popular ways to regree out.

**Comment by lmacdonald12** [comment]
I am following the tutorial, human data.

**Comment by leonfodoulian** [comment]
Hi @lmacdonald12,

You can filter your cells based on any relevant criteria. I don't think that not filtering cells based on mitochondrial genes has any relevance regarding Seurat's CCA algorithm (if I'm not mistaken). Note that tutorials are written for learning purposes, and that your analysis should be dataset specific.

Best,
Leon
