### ISSUE TITLE
integrating healthy and disease samples (n=3 each) prior to Umap

### ISSUE THREAD

**Issue by teganmct** [satijalab/seurat#8646]
Hello,

I am working with 3 healthy and 3 disease patients and I am wanting to combine these before Umap so I can have two umaps one for healthy and one disease. At the moment they are splitting based on sample name ie HC1, HC2, HC3 and same for the disease but I want them to split all HC and all disease. can I do this by adding another column to the metadata which the code states HC1, 2, 3 are = HC? i have attached my current code whereby I am splitting based on Sample name.

split.filtered.PSAHC <- SplitObject(filtered.PSAHC, split.by = "Sample_Name")

# normalize and identify variable features for each dataset independently
split.filtered.PSAHC <- lapply(X = split.filtered.PSAHC, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# select features that are repeatedly variable across datasets for integration
integ.features <- SelectIntegrationFeatures(object.list = split.filtered.PSAHC, 
                                            nfeatures = 2000) 
# this command creates an 'integrated' data assay
anchors <- FindIntegrationAnchors(object.list = split.filtered.PSAHC,
                                  anchor.features = integ.features)

I am a beginner in R so this may be simple or may not

**Comment by rsatija** [comment]
yes, you can combine the two column names together. For example
```
object$split_id = paste0(object$sample_name,"_",object$disease_id)
```
