### ISSUE TITLE
A typo in the deg tutorial

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#8652]
Hi, I think I found a typo in this tutorial:

![image](https://github.com/satijalab/seurat/assets/43333475/378e8b21-4e8d-46db-8365-9b2d57ca6939)

I think for poisson distribution, the underlying distribution should be Poisson rather than negative bionomial. Thanks.

**Comment by rsatija** [comment]
Thanks - we have corrected this internally and it will be fixed in the next public release!
