### ISSUE TITLE
Error for FindMarkers

### ISSUE THREAD

**Issue by loumurphy** [satijalab/seurat#8657]
What I input
'nk_t_markers <- FindMarkers(seurat_object, ident.1 = 'NK/T')'

The error that keeps appearing 
'Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: NK/T'

**Comment by loumurphy** [comment]
> levels(Idents(object))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'levels': object 'object' not found

**Comment by samuel-marsh** [comment]
Is "object" the name of your object?

**Comment by loumurphy** [comment]
output 
 [1] "0"  "1"  "2"  "3"  "4"  "5" 
 [7] "6"  "7"  "8"  "9"  "10" "11"
[13] "12" "13" "14" "15"

**Comment by samuel-marsh** [comment]
Ok so the reason `FindMarkers` is erroring is because "NK/T" is not in active identities of the object.  If you have created another identity column in meta.data you can set that with:
`Idents(object) <- "column_name"`

Best,
Sam

**Comment by loumurphy** [comment]
How do I add it to active identities of the object ?

**Comment by samuel-marsh** [comment]
You can see example here:
https://satijalab.org/seurat/articles/pbmc3k_tutorial#assigning-cell-type-identity-to-clusters

best,
Sam
