### ISSUE TITLE
PercentageFeatureSet doesn't always work when specifying assay. 

### ISSUE THREAD

**Issue by maxim-h** [satijalab/seurat#8658]
I've been trying to run `PercentageFeatureSet` on an object that already has multiple assays, with default one being `integrated`.

I do the following, but it doesn't work:
```r
> PercentageFeatureSet(object = seurat, pattern = "^RP[LS]", assay = "RNA")
NULL
```
Pretty sure it's because `PercentageFeatureSet` searches for `counts` layers, but doesn't specify which `assay` to look for layers in.
https://github.com/satijalab/seurat/blob/c54e57d3423b3f711ccd463e14965cc8de86c31b/R/utilities.R#L1173-L1174

So, since `integrated` assay doesn't have a `counts` layer nothing works.

My guess is that just pushing the `assay` parameter down to `Layers` call should fix this.

**Comment by igrabski** [comment]
Thanks for bringing this to our attention! This indeed seems like a bug, and we will look into it. In the meantime, a workaround is to specify the `DefaultAssay` of your object as `RNA` (or whichever contains the `counts` layer you would like to use).
