### ISSUE TITLE
How distinguish difference of spatial transcriptomics caused by the total number of RNA in different cells?

### ISSUE THREAD

**Issue by liuxiawei** [satijalab/seurat#8665]
I have attempted to create a new Seurat object for analysis based on spatial metabolomics data. In this process, I found that some data differed with the MSI data directly obtained. For instance, the content of some compounds was very low across all tissue, and the differences in compounds after data processing by seurat were exaggerated. I suspect this is caused by normalization. 

In our spatial transcriptomics analysis, there are still some cells that have less total RNA. How to eliminate the analytical differences caused by cell type and varying total RNA quantity during the analysis process?

**Comment by dcollins15** [comment]
Hi @liuxiawei 

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
