### ISSUE TITLE
Meaning of the 'counts' layer of the SCT assay

### ISSUE THREAD

**Issue by viktorfeketa** [satijalab/seurat#8667]
I am trying to understand the meaning of the nCount_SCT.
From the sctransform vignette:

> To assist with visualization and interpretation, we also convert Pearson residuals back to ‘corrected’ UMI counts. You can interpret these as the UMI counts we would expect to observe if all cells were sequenced to the same depth. If you want to see exactly how we do this, please look at the correct function [here](https://github.com/ChristophH/sctransform/blob/master/R/denoise.R).

nCount is the sum of all UMI counts per cell. If all cells were sequenced to the same depth, the sum of UMI counts should be the same for every cell, and equal to the normalization base (10,000 for example) - this is the definition of the "sequencing depth". Thus, nCount_SCT should be the same for every cell. However, plotting nCount_SCT reveals that this is not the case (from the pbmc3k dataset) - each cell has different "total UMI counts", which means they were not sequenced to the same depth, and the values are thus still not-normalized.

Is this logic correct, or am I missing something - could you please explain?

I am mostly trying to understand what would be the intuitive measure of gene expression after normalization by SCT. Can I use a value N for a gene G for a cell C in the 'count' layer of the SCT assay to make the claim that, if cells were sequenced to the same depth, let's say 10,000 molecules per cell, the cell C would contain N molecules of transcript G?
What is the normalization base by default, is it 10,000?

![ncount_sct](https://github.com/satijalab/seurat/assets/63417114/0e1c6087-4aad-4e85-90c1-b360aa7372f4)

**Comment by saketkc** [comment]
sum(nCount_SCT) is not expected to be the same for all cells. As explained in the [v1 paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1), the corrected counts are obtained after reversing the regression model by asking what would be the observed counts (with minimal technical noise) if the cells  were to be sequenced to a fixed depth (median nCount_RNA by default).
