### ISSUE TITLE
how to interprete the result of PCHeatmap

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#867]
how to interprete the result of PCHeatmap, is the different stands for different ident?
thanks a lot
![image](https://user-images.githubusercontent.com/25199946/47090619-d573f680-d255-11e8-8515-25a6e8a7bd70.png)

**Comment by satijalab** [comment]
Check out ?PCHeatmap for more information on this function, as well as https://satijalab.org/seurat/pbmc3k_tutorial.html, which explains the function
