### ISSUE TITLE
How to interpret high log2FC in CITE-Seq data 

### ISSUE THREAD

**Issue by bl24** [satijalab/seurat#8670]
Hello, I'm trying to perform differential expression analysis on my CITE-Seq data. I annotated my cells using Azimuth and used FindMarkers and found that a protein marker, TCR, was showing up high on my results for NK cells which is unexpected (the avg_log2FC was -6). I took a look at a Violin plot sorted by average expression for TCR and NK cells are ranked near the bottom (screenshot included). How should I interpret this result?

![Screen Shot 2024-03-20 at 2 00 46 PM](https://github.com/satijalab/seurat/assets/14930703/2146b1a1-5384-4284-81b0-efbc90332bcf)

**Comment by dcollins15** [comment]
Hi @bl24,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
