### ISSUE TITLE
Convert seurat v5 object to v3/4 object using Seurat v4 

### ISSUE THREAD

**Issue by laijen000** [satijalab/seurat#8676]
Hello, 

I was given a Seurat object that was created using Seurat v5, however I am only using Seurat v4. This has led to issues where the object only has the SCT assay (no RNA assay). If I try to set DefaultAssay(seurat_object) = 'RNA', I get the error that there is no RNA assay. It seems the functions for converting from v5 and v3 are only available in Seurat v5. I would greatly appreciate workarounds for this since I need the RNA assay for DE analysis, and my HPC cluster only has Seurat v4 installed. Thank you!

**Comment by tkapello** [comment]
I have a similar question. @rsatija, could someone assist with this request?

**Comment by dcollins15** [comment]
Thanks for reaching out! 

Unfortunately, this operation cannot be supported. Our recommendation would be to use a v5 installation to convert the object or just re-generate it from the initial counts matrix.
