### ISSUE TITLE
addmodulescore

### ISSUE THREAD

**Issue by Sirin24** [satijalab/seurat#8680]
I have a question regarding addmodulescore.  I have prepared a list of ligands and their receptors that are of interest in a specific disease. how to laverage addmodulescore and what I can deduce from it?. positive numbers mean clusters or cell types express it more compared to controls? how is it different from findmarkers in a certain celltype compared to control then find in that list the ligands and the receptors?

Another question I have is the ctrl? this is manually selected by seurat from the gene pool which is all genes in the object or from the list I provided? how to make it more strict to get more significant results?

if addmodulescore is not suitable in this context. what other functions of seurat that might it be help?

**Comment by dcollins15** [comment]
Hi @Sirin24,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
