### ISSUE TITLE
FindAllMarkers function after batch effect correction with Harmony

### ISSUE THREAD

**Issue by vukojicic-nevena** [satijalab/seurat#8694]
Hi, 

Is it okay to use FindAllMarkers function for GMI step if I had identified batch effect and removed it with Harmony (so clustering was performed using harmony reduction)? 
Does that mean that batch effect is neutralized from the data and doesn't affect the gene marker identification step? In scran's version of this function there is a block parameter that accounts for batch, but I was wondering is it enough to just use Seurat FindAllMarkers as is, if I've performed Harmony before, or should I tweak some parameter to include batch?

Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Harmony and most other integration methods only correct the cell embedding, they do not produce corrected count matrices.  Corrected count matrices do suffer from significant issues.

So you should absolutely be running FindAllMarkers on RNA (or SCT) assay following appropriate pipeline.  Depending on the type of test you use in FindAllMarkers you have option to specify additional covariates such as batch to the model.  The choice of DE test and which covariates to use is going to be dependent on the dataset specifics and on the questions being asked in the analysis.

Best,
Sam
