### ISSUE TITLE
How to rotate Axis labels in VlnPlot?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#87]
Hello Seurat Team,

In the violin plots draw using VlnPlot, I need to rotate the x-axis labels, as the names overlap rendering them unreadable.  Please let me know if there is a way to achieve this.

Many thanks!

**Comment by andrewwbutler** [comment]
Hi,

Currently there isn't an easy way to do this within the package although our next release overhauls some of the plotting functionality and will include this as a parameter option. For now though, you can return the plot as a ggplot object and manipulate it however you want. Here's how you would go about rotating the x-axis labels:

`plot <- VlnPlot(object, "GENE", do.ret = T)[[1]]`
`plot + theme(axis.text.x = element_text(angle = 90))`

**Comment by CodeInTheSkies** [comment]
Thanks!  This worked, except that I had to also set "hjust=1", like this:

`+ theme(axis.text.x = element_text(angle = 45, hjust=1))`

**Comment by cemalley** [comment]
In Seurat 3.1.4, when plotting many features with VlnPlot and adding the +theme(), it only rotates the axis text for the last feature in the list. This is my solution with cowplot to get all the idents rotated.

```
library(cowplot)
plot_grid(VlnPlot(is013.merged, features=c('CD44'))+theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.title.x = element_blank()) + guides(fill=FALSE),
          VlnPlot(is013.merged, features=c('S100B'))+theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.title.x = element_blank()) + guides(fill=FALSE),
          VlnPlot(is013.merged, features=c('NFIA'))+theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.title.x = element_blank()) + guides(fill=FALSE),
          VlnPlot(is013.merged, features=c('NFIB'))+theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.title.x = element_blank()) + guides(fill=FALSE),
          VlnPlot(is013.merged, features=c('VIM'))+theme(axis.text.x = element_text(angle = 30, hjust = 1), axis.title.x = element_blank()) + guides(fill=FALSE))
```
