### ISSUE TITLE
Creating a list of genes to regress out

### ISSUE THREAD

**Issue by JoshuaCumming** [satijalab/seurat#870]
Hello,

I was wondering if it is possible to create a list of genes and regress them out in the same way that you can for cell cycle genes? 

First, I have written the list of genes into a text document but when I use the ReadLines function it does not make them into a numeric as it does when I read in the cell cycle gene list. Is there a way that you can write a list of genes and input them in the same way you do for the cell cycle?

I was also wondering if there is a scoring function like CellCycleScoring that you can use for a list of genes you have created?

Thanks for any help!

**Comment by JoshuaCumming** [comment]
Hi,

Great thanks, AddModuleScore sounds great. However, I have just tried to run it and receive this error message:
DNUC_cc_pscg_removed <- AddModuleScore(object = DNUC_cc_pscg_removed, genes.list = Psc.Type.Genes, ctrl.size = 5, enrich.name = "Psc_Type_Genes")
Error in AddModuleScore(object = DNUC_cc_pscg_removed, genes.list = "Psc.Type.Genes",  : 
  The following gene lists do not have enough genes present in the object:  exiting...
In addition: Warning message:
In AddModuleScore(object = DNUC_cc_pscg_removed, genes.list = "Psc.Type.Genes",  :
  Could not find enough genes in the object from the following gene lists:  Attempting to match case... 

I have a list of 29 genes but not all may be present in the object, is there a threshold number of genes required for the function?

Thanks very much for the help.

Best,

Joshua

**Comment by leonfodoulian** [comment]
Hi @JoshuaCumming,

Is your genes list input a data frame or a list?

Best,
Leon

**Comment by JoshuaCumming** [comment]
Hi,

It's a character in the same format as the cc.genes example.

Best,

Joshua

**Comment by leonfodoulian** [comment]
Could you please paste the `R` output of `Psc.Type.Genes`?

**Comment by JoshuaCumming** [comment]
> Psc.Type.Genes
 [1] "Alx1"      "C1qtnf7"   "Cav3"      "Ccl20"     "Ccl8"      "Cdh1"      "Dcn"       "Dpep1"     "En1"      
[10] "Fgf21"     "Grem2"     "Hoxa11os"  "Hoxc12"    "Hp"        "Igfbp4"    "Inmt"      "Ntn5"      "Penk"     
[19] "Prr9"      "Rarres2"   "Rorb"      "Runx3"     "Saa3"      "Serpina3n" "Slpi"      "Smoc1"     "Sod3"     
[28] "Tgm1"      "Tnfsf8"  > Psc.Type.Genes
 [1] "Alx1"      "C1qtnf7"   "Cav3"      "Ccl20"     "Ccl8"      "Cdh1"      "Dcn"       "Dpep1"     "En1"      
[10] "Fgf21"     "Grem2"     "Hoxa11os"  "Hoxc12"    "Hp"        "Igfbp4"    "Inmt"      "Ntn5"      "Penk"     
[19] "Prr9"      "Rarres2"   "Rorb"      "Runx3"     "Saa3"      "Serpina3n" "Slpi"      "Smoc1"     "Sod3"     
[28] "Tgm1"      "Tnfsf8"

**Comment by leonfodoulian** [comment]
Your gene list should be a list, and not a character vector. Try running the following, and rerun the code.

```R
Psc.Type.Genes <- list(Psc.Type.Genes)
```

Also, to check that those genes are present in your dataset, you can run the following:

```R
which(x = unlist(x = Psc.Type.Genes) %in% rownames(x = DNUC_cc_pscg_removed@data))
```

Best,
Leon

**Comment by JoshuaCumming** [comment]
It's all working now. Thanks for your help!

Best,

Joshua
