### ISSUE TITLE
Different visualization results before and after PrepSCTFindMarkers

### ISSUE THREAD

**Issue by makabakayu** [satijalab/seurat#8712]
Hi seurat team,

I'm using SCTransform for my multiple ST samples individually and then merge them together, and I perform `PrepSCTFindMarkers` to pull sequencing depth of all samples at the same level.
 
My question is when I plot nCount of each spot on spatial using `SpatialFeaturePlot` for the row count, SCT count before `PrepSCTFindMarkers` and SCT count after `PrepSCTFindMarkers`  individually, I found the spatial plot for SCT count after `PrepSCTFindMarkers` to be unreasonable. For example, my samples are tumor samples, which means the expression level is higher in the tumor epithelial region than in the stromal region, and the spatial plot of row count and SCT count before `PrepSCTFindMarkers` are consistent with this phenomenon, but SCT count after `PrepSCTFindMarkers` is very different, some samples are even reversed.

 I wonder  what's going on here and how do I fix this cause I want to do some differential expression analysis later.

**Comment by saketkc** [comment]
`PrepSCTFindMarkers` recalculates the corrected counts by reversing the regression model by using minimum of median sequencing depth. As we show in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02584-9), this results in lowest FPR at the same level of FDR. For DE, I would recommend running `PrepSCTFindMarkers` if you are using the SCT workflow.
