### ISSUE TITLE
PCA Scaling Requirement After Non-integer Gene-level Batch Correction

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#8714]
I use SCTransform on raw counts to look at the original data with UMAP. Then I use a batch correction method, [scMerge 2](https://www.nature.com/articles/s41467-023-39923-2), which does not return integer counts but decimal numbers for each gene. I want to run PCA and UMAP on the batch-corrected data. However,

```r
> fibroSeurat <- RunPCA(fibroSeurat)
Error in PrepDR(object = object, features = features, verbose = verbose) : 
  Data has not been scaled. Please run ScaleData and retry
```

In the first step before batch correction, SCTransform already scaled the data and I made a UMAP, I can't use SCTransform again because, after batch correction, the data is no longer integer count. What should I do?

**Comment by saketkc** [comment]
Hi @DarioS, if you are running this on `scMerge2`'s output (I am not familiar with the method), and it is batch corrected (and scaled), it should ideally be going to the `scale.data` slot of your object. PCA  is run using the values in the `scale.data` slot (RNA or SCT assay)
