### ISSUE TITLE
RunSVD()

### ISSUE THREAD

**Issue by VOlberding** [satijalab/seurat#8717]
Hi,

I'm having issues while attempting to run RunSVD() and am getting this issue:

Error in irlba(A = t(x = object), nv = n, work = irlba.work, tol = tol) : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

I'm on an M2

**Comment by JHCCoder** [comment]
Running `install.packages("irlba", type="source")` downgraded by Matrix from 1.6.4 to 1.6-1.1 which is not compatible with Signac. I can't load Signac anymore. Any idea on how to properly create a conda environment with Signac and Seurat5? 
```
Error: package or namespace load failed for ‘Signac’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Matrix’ 1.6-1.1 is already loaded, but >= 1.6.4 is required
```
