### ISSUE TITLE
real spot distance analysis calculation in visium

### ISSUE THREAD

**Issue by Houssi1337** [satijalab/seurat#8720]
Hello everyone, 
I am currently working on the calculation of real distance between spots in visium slide (in microns) and I managed to get the spot coordinates using the GetTissueCoordinates(object, scale = "NULL", cols = c("imagerow", "imagecol").
So I generated a pairwise distance matrix using rdist function using the generated coordinates and the calculation was based on the euclidian method.
But the problem is that you would expect the minimum distance to be 55microns (distance between centers of two near spots) which is not the case in my matrix in which I got as a minimum is 50.
Did I operate in the right approach , or can someone recommend me a function or other approach to test?
Thanks!

**Comment by zskylarli** [comment]
Hi - I believe that level of discrepancy should be expected! Instead of the minimum, have you looked at the average distance between the spatially closest spots and seeing if that is closer to 55um?
