### ISSUE TITLE
Do you need to normalise and scale after AggregateExpression if return.seurat = TRUE is selected 

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [satijalab/seurat#8727]
Dear Seurat team, 
Clarification is required for the  AggregateExpression(return.seurat = TRUE) function , as the documentation  suggests to normalise and scale data if return.seurat = TRUE is used

> If return.seurat = TRUE, aggregated values are placed in the 'counts' layer of the returned object. The data is then normalized by running [NormalizeData](https://satijalab.org/seurat/reference/normalizedata) on the aggregated counts. [ScaleData](https://satijalab.org/seurat/reference/scaledata) is then run on the default assay before returning the object.
[ref:](https://satijalab.org/seurat/reference/aggregateexpression) 

However, following this [tutorial ](https://satijalab.org/seurat/articles/de_vignette) there is no normalisation and scaling performed 

checked my Seurat v5 aggregated object. I do have raw counts (counts layer) and normalised counts ('data' layer) in the Seurat object: 
```
GetAssayData( pseudo_seurat, layer="counts")[1:5, 1:5]
           L1_clust0 L1_clust1 L1_clust2 L1_clust3 L1_clust4
AL627309.1           .           .           .           .           .
AL627309.5           2           4           1           .           1
LINC01409           14          46          11           8          24

GetAssayData( pseudo_seurat,  layer="data")[1:5, 1:5]

            L1_clust0 L1_clust1 L1_clust2 L1_clust3 L1_clust4
AL627309.1  0.00000000 0.000000000 0.000000000   0.0000000 0.000000000
AL627309.5  0.02016010 0.014213209 0.005656866   0.0000000 0.009176936
LINC01409   0.13326509 0.152394003 0.060532249   0.1161947 0.199883236

```

thank you

**Comment by zskylarli** [comment]
Hi - this documentation basically says that within AggregateExpression, we already run NormalizeData and ScaleData on the aggregated counts, so you will not need to run it again.
