### ISSUE TITLE
Error when using distance matrix in FindClusters

### ISSUE THREAD

**Issue by gexijin** [satijalab/seurat#873]
Hi I was trying to run FindClusters with my own distance matrix, but encountered errors:
Error in data.use[i, ] : incorrect number of dimensions

I used the same dimension for the distance matrix. 

Can someone provide an example of using distance matrix? I understand that it is experimental.
Thank you.

**Comment by gexijin** [comment]
I actually figured it out by cloning the FindClusters and BuildSNN functions. There is caused by an error in the BuildSNN function that could be easily solved. 
The current version of R (3.5.1) does not allow us to refer to the individual elements in the distance matrix. Try this:
> data <- matrix(1:20, nrow=4, ncol=5)
> d <- dist( data )
> d[1, ]   
Error in d[1, ] : incorrect number of dimensions
> as.matrix(d)[1, ] 
       1        2        3        4 
0.000000 2.236068 4.472136 6.708204 

To solve this issue, we only need to change the beginning of the BuildSNN function as follows:
BuildSNN2 <- function (object, genes.use = NULL, reduction.type = "pca", dims.use = NULL, 
    k.param = 10, plot.SNN = FALSE, prune.SNN = 1/15, print.output = TRUE, 
    distance.matrix = NULL, force.recalc = FALSE, filename = NULL, 
    save.SNN = TRUE, nn.eps = 0) 
{
    if (!is.null(x = distance.matrix)) {
        data.use <- as.matrix( distance.matrix )
....

Currently, the it is:
BuildSNN2 <- function (object, genes.use = NULL, reduction.type = "pca", dims.use = NULL, 
    k.param = 10, plot.SNN = FALSE, prune.SNN = 1/15, print.output = TRUE, 
    distance.matrix = NULL, force.recalc = FALSE, filename = NULL, 
    save.SNN = TRUE, nn.eps = 0) 
{
    if (!is.null(x = distance.matrix)) {
        data.use <- distance.matrix 
....

The only difference is the as.matrix (    ), without which data.use is a distance matrix.

**Comment by satijalab** [comment]
Thanks so much for looking into this. We will explore and fix, especially if this is still in issue in Seurat v3. @andrewwbutler

**Comment by mojaveazure** [comment]
Hi Steven,

This should be fixed as of commit 437f644; please note that in Seurat v3, `BuildSNN` was replaced by `FindNeighbors`
