### ISSUE TITLE
How to outline Seurat clusters in black?

### ISSUE THREAD

**Issue by yamihn** [satijalab/seurat#8730]
### Discussed in https://github.com/satijalab/seurat/discussions/8728

<div type='discussions-op-text'>

<sup>Originally posted by **yamihn** April  5, 2024</sup>
Hello everyone,

I'm currently working with Seurat for single-cell RNA-seq analysis, and I'm trying to enhance the visualization of my UMAP plots. I was wondering if there's a way to outline the clusters identified by Seurat in black. I've tried using the borders = TRUE and border.color = "black" parameters in the DimPlot() function, but it seems they're not supported.

Does anyone know if there's a way to achieve this within Seurat or with additional customization using ggplot2?

Any help or suggestions would be greatly appreciated.

Thank you!</div>

**Comment by zskylarli** [comment]
I believe that you may have to do that in an external software such as Illustrator; the Seurat DimPlot() function does not support that visualization.
