### ISSUE TITLE
AggregateExpression not using 'data' layer in v5

### ISSUE THREAD

**Issue by lijing-lin** [satijalab/seurat#8732]
I wanted to generate pseudobulk RNA with AggregateExpression with code:

`cts <- AggregateExpression(seu.norm ,group.by = c("cluster","Patient"), 
                           assays = ("RNA"), return.seurat = F)
`

`seu.norm` is multi-layer Seurate v5 object with counts data on the layers: 'counts.1', 'counts.2', ... and normalised data on the layers 'data.1,' 'data.2', ...

From the code, it seems 'data' layer is used by default. However, my test showed that it is still counts data being used for aggregation.

```r
# insert reproducible example here
```

**Comment by samuel-marsh** [comment]
Hi @lijing-lin,

Can you clarify what you mean when you say "From the code".

This is code of `AggregateExpression` where is shows "counts" is used by default.
https://github.com/satijalab/seurat/blob/c54e57d3423b3f711ccd463e14965cc8de86c31b/R/utilities.R#L358-L388

Best,
Sam

**Comment by mhkowalski** [comment]
Hello, 

Thanks @samuel-marsh for your response. Yes, as the documentation specifies, `AggregateExpression` uses counts by default.

**Comment by lijing-lin** [comment]
Thank you both @samuel-marsh  @mhkowalski 

Apologies for my oversight. For some reason, I was jumping to read the function`PseudobulkExpression` instead.

Just to clarify, `AggregateExpression` uses 'counts' by default and one cannot specify the layer. To aggregate normalised data, one has to use `PseudobulkExpression` directly, which indeed uses `layer = 'data'` by default (also by default `method = 'average'`)

```
agg.norm <- PseudobulkExpression(seu.norm ,group.by = c("cluster","Patient"),  assays = ("RNA"),
                             method = 'aggregate', return.seurat = F)
```

**Comment by mhkowalski** [comment]
Thanks for clarifying. I'll just mention it doesn't make sense to pseudobulk by taking the sum of normalized data, as this sum will be dependent on the number of cells in each group. If you want to use the data layer, I would recommend using `AverageExpression` (which averages the normalized data instead).
