### ISSUE TITLE
How to make Seurat layers in a Seurat object list?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#8734]
Hello. I have 58 scRNA-seq samples to integrate. With Seurat v5, data are now split in layers. I have a trouble following the tutorial. After preprocessing all samples individually, I made them into a Seurat object list. I want to integrate them (IntegrateLayers()). I tried the below but it doesn't work. Any help?

```
# split assay into 58 layers
object.list[["RNA"]] <- split(object.list[["RNA"]], f = object$orig.ident)
```

**Comment by Gesmira** [comment]
Is object.list a list? If so, the code you're running won't work as it is supposed to run on a single seurat object at a time. 

If object.list is an object, what is the error you are getting? 

If you have many samples, you could run something like:
``` 
# This will create an object with multiple layers already
merged.object <- CreateSeuratObject(counts = data.list, meta.data = metadata)
```

**Comment by Gesmira** [comment]
Hi, closing now due to lack of response. Feel free to reopen if errors persist!
