### ISSUE TITLE
Change in default value for min.pct in FindMarkers

### ISSUE THREAD

**Issue by artemisDiscovery** [satijalab/seurat#8735]
Why was the default threshold for min.pct in FindMarkers changed from 0.10 to 0.01? Is that an error, or based on some new consensus as to the best value?

The previous level ensured that you didn't have DE involving a small number of cells  in the comparison groups, which might reflect more noise than signal.

We spent a lot of time chasing down this issue when the number of DE genes went from ~5,000 to > 13,000 in two analyses of the same data using Seurat 5. In one case the min.pct was explicitly set in the code, in the other it was assumed that the default value was as before.

Thanks,
Randy

**Comment by igrabski** [comment]
Hi Randy, the previous threshold of `min.pct` was set partially as a way to control the computational time of the `FindMarkers` procedure. Because `FindMarkers` was made much faster for the v5 release, we now set `min.pct` lower by default to allow more markers to be tested. The output of `FindMarkers` includes the percent expression in each cluster, so you can still filter your results afterwards if you believe that your DE genes include too many noisy, lowly-expressed markers. Alternatively, you can also still set `min.pct` to 0.10 or any other preferred value when calling `FindMarkers`.

**Comment by artemisDiscovery** [comment]
Hi, thanks for the explanation, I thought that might be the case.

Here's an interesting point though - it is not just a matter of filtering for your chosen minpct after the comparison.  You get somewhat different results with different settings of min.pct. 

On our data, for a particular cluster/cell type, with your new default we get 13,486 DE genes (p-adj < 0.05), with the old higher default we find 7,649 genes. The intersection is indeed big, 6,541 genes, but there are 1,108 genes unique to the set found with min.pct = 0.1, and there are 6,945 genes unique to the DE set with your new default. 

In the 'min.pct=0.01-unique' set of 6,945 genes, there are 159 genes with one or both sides of the comparison showing expression > 0.1,  i.e. these are not present in the comparison made with the old default of 0.1 .

Not a huge deal, pretty sure this is a side-effect of the way false discovery works, it has some sensitivity to the number of genes found and the way they are ranked.

Randy

**Comment by igrabski** [comment]
Yes definitely -- here, the adjusted p-values are computed using the Bonferroni correction, which is a function of the total number of features being tested. From a statistical perspective, pre-filtering features based on their expression, and then testing for differential expression, may introduce some level of bias, as opposed to testing all features. (Of course, clustering your data and then doing DE among the clusters results in some level of bias as well, which is difficult to avoid!) That said, p-values are only so meaningful, and in any case we would caution against directly assuming all genes below some p value threshold are truly DE without careful consideration and interpretation of effect sizes, etc.
