### ISSUE TITLE
LogFC calculation in FindMarkers

### ISSUE THREAD

**Issue by snowGlint** [satijalab/seurat#8738]
Hello, when I manully calculated the log2FC, I found the result was different from the FindMarkers function; When I check the soure code I found this function calculating logFC like this:
<img width="480" alt="23c4796d9cbcfb9db36d7cf754c0bc2" src="https://github.com/satijalab/seurat/assets/93318795/d88756e5-1a3c-404e-90b3-915ae125d856">

I tested this code manully, and its result were the same as the FindMarkers function:
<img width="507" alt="96003edab84cb60cf44fa535afe38e9" src="https://github.com/satijalab/seurat/assets/93318795/4ca44dab-4eca-49d6-b9bf-ac76ea606b35">

However, what I previoussly thought the meaning of logFC is the log(avg_A/avg_B) ; this caculation seems not like this(I know the add 1 operation to avod zero but don't understand why calculate e(x)), are there any reasons behind this?; And I found there was a big difference between this function's result and results from direct calculation;

```r
log2(mean(MNRAKO)/mean(MNRALC)) = -0.16
```

 This will cause a different result when I choose the logFC cretia to filter some genes. Which one  should I choose better?

**Comment by morallawwithin** [comment]
See https://github.com/satijalab/seurat/issues/6701

**Comment by snowGlint** [comment]
> See #6701

Thanks!
