### ISSUE TITLE
AverageExpression and DoHeatmap scaling: each raw or global?

### ISSUE THREAD

**Issue by amisharin** [satijalab/seurat#874]
In the [interaction vignette](https://satijalab.org/seurat/interaction_vignette.html#calculating-the-average-gene-expression-within-a-cluster) how is the data matrix for the resulting heatmap scaled? I'd expect that each row should be centered and scaled (i.e. each row would have the brightest purple and brightest yellow), but right now it looks like it is not centered. I understand that it looks ok for lineage-specific markers, but for a predefined list of genes it gives weird looking heatmaps (and gives the wrong message).

[Rplot.pdf](https://github.com/satijalab/seurat/files/2498518/Rplot.pdf)

I apologize if this issue has been already covered, but I could not find it on github. Thank you.

**Comment by leonfodoulian** [comment]
Hi @amisharin,

The scaling of the Seurat object when running `Seurat::AverageExpression()` is performed by the `Seurat::ScaleData()` function. So the scaling is performed for each gene independently.

https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/utilities.R#L536-L662

> I'd expect that each row should be centered and scaled (i.e. each row would have the brightest purple and brightest yellow), but right now it looks like it is not centered.

Even though scaling is performed per gene, genes will not necessarily have the same highest (positive) or lowest (negative) values. However, they all indeed have a mean close to 0 and a standard deviation of 1. You can check that using the following function. 

```R
stats.scaled.data <- apply(X = object@scale.data, 
                           MARGIN = 1, 
                           FUN = function(x) {
                             out <- cbind(min(x),
                                          max(x),
                                          mean(x = x),
                                          sd(x = x))
                             return(out)
                           })
rownames(x = stats.scaled.data) <- c("min", "max", "mean", "sd")
```


Since the legend colour bar is unique for all genes, only the gene(s) having the highest scaled value will show the brightest yellow colour in any of the cells/clusters, and the same is true for the gene(s) with the lowest scaled value. 

Best,
Leon

**Comment by amisharin** [comment]
In Leon we trust! :) I knew you'd not leave this question unanswered on a cold October evening!

Thank you for your response, Leon, and for pointing out to the relevant code. But since it is already averaged and scaled data and all we do is visualizing the pattern of the gene expression between different clusters: wouldn't it make sense to re-center the data matrix prior to scaling to go from most high to most low on every row? Otherwise, we will have examples like Gene4 on the attached plot or IL32 in the vignette: not too low and not too high. Am I missing some important point why these plots should not be from max to min on each raw? Thank you.

**Comment by leonfodoulian** [comment]
Hi @amisharin,

The data is already centered by default by `Seurat::ScaleData()`.  See lines 601 to 607 and 609 to 615 below.

https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/preprocessing.R#L499-L637

The minimum and maximum values per gene will depend on their range of expression values. Assume two genes, each with a given mean and variance. When scaled and centered, they will not necessarily have the same minimum and maximum values, but still will have a mean close to 0 and a standard deviation of 1.

```R
> set.seed(seed = 123)
> exp.mat <- data.frame(g1 = rpois(n = 10, lambda = 2),
+                       g2 = rpois(n = 10, lambda = 1))
> scaled.exp.mat <- scale(x = exp.mat, center = TRUE, scale = TRUE)
> apply(X = scaled.exp.mat, MARGIN = 2, FUN = function(x) {
+   out <- cbind(min(x),
+                max(x),
+                mean(x = x),
+                sd(x = x))
+   return(out)
+ })
                g1            g2
[1,] -1.777913e+00 -9.187960e-01
[2,]  1.185276e+00  1.587011e+00
[3,]  4.439266e-17 -6.938894e-17
[4,]  1.000000e+00  1.000000e+00
```

Hope this helps.

Best,
Leon

**Comment by leonfodoulian** [comment]
Hi @2236529177,

As of Seurat version 2.0, `Seurat::DoHeatmap()` uses `ggplot2`, and not `gplots::heatmap.2`. This is both mentioned in the current [documentation of the function](https://www.rdocumentation.org/packages/Seurat/versions/2.3.2/topics/DoHeatmap), and is evident in the code of the function:

https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/plotting.R#L47-L247

Best,
Leon

**Comment by 2236529177** [comment]
> Hi @2236529177,
> 
> As of Seurat version 2.0, `Seurat::DoHeatmap()` uses `ggplot2`, and not `gplots::heatmap.2`. This is both mentioned in the current [documentation of the function](https://www.rdocumentation.org/packages/Seurat/versions/2.3.2/topics/DoHeatmap), and is evident in the code of the function:
> 
> [seurat/R/plotting.R](https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/plotting.R#L47-L247)
> 
> Lines 47 to 247 in [65b77a9](/satijalab/seurat/commit/65b77a9480281ef9ab1aa8816f7c781752092c18)
> 
>  DoHeatmap <- function( 
>    object, 
>    data.use = NULL, 
>    use.scaled = TRUE, 
>    cells.use = NULL, 
>    genes.use = NULL, 
>    disp.min = -2.5, 
>    disp.max = 2.5, 
>    group.by = "ident", 
>    group.order = NULL, 
>    draw.line = TRUE, 
>    col.low = "#FF00FF", 
>    col.mid = "#000000", 
>    col.high = "#FFFF00", 
>    slim.col.label = FALSE, 
>    remove.key = FALSE, 
>    rotate.key = FALSE, 
>    title = NULL, 
>    cex.col = 10, 
>    cex.row = 10, 
>    group.label.loc = "bottom", 
>    group.label.rot = FALSE, 
>    group.cex = 15, 
>    group.spacing = 0.15, 
>    assay.type = "RNA", 
>    do.plot = TRUE 
>  ) { 
>    if (is.null(x = data.use)) { 
>      if (use.scaled) { 
>        data.use <- GetAssayData(object,assay.type = assay.type,slot = "scale.data") 
>      } else { 
>        data.use <- GetAssayData(object,assay.type = assay.type,slot = "data") 
>      } 
>    } 
>    # note: data.use should have cells as column names, genes as row names 
>    cells.use <- SetIfNull(x = cells.use, default = object@cell.names) 
>    cells.use <- intersect(x = cells.use, y = colnames(x = data.use)) 
>    if (length(x = cells.use) == 0) { 
>      stop("No cells given to cells.use present in object") 
>    } 
>    genes.use <- SetIfNull(x = genes.use, default = rownames(x = data.use)) 
>    genes.use <- intersect(x = genes.use, y = rownames(x = data.use)) 
>    if (length(x = genes.use) == 0) { 
>      stop("No genes given to genes.use present in object") 
>    } 
>    if (is.null(x = group.by) || group.by == "ident") { 
>      cells.ident <- object@ident[cells.use] 
>    } else { 
>      cells.ident <- factor(x = FetchData( 
>        object = object, 
>        cells.use = cells.use, 
>        vars.all = group.by 
>      )[, 1]) 
>      names(x = cells.ident) <- cells.use 
>    } 
>    cells.ident <- factor( 
>      x = cells.ident, 
>      labels = intersect(x = levels(x = cells.ident), y = cells.ident) 
>    ) 
>    data.use <- data.use[genes.use, cells.use, drop = FALSE] 
>    if ((!use.scaled)) { 
>      data.use = as.matrix(x = data.use) 
>      if (disp.max==2.5) disp.max = 10; 
>    } 
>    data.use <- MinMax(data = data.use, min = disp.min, max = disp.max) 
>    data.use <- as.data.frame(x = t(x = data.use)) 
>    data.use$cell <- rownames(x = data.use) 
>    colnames(x = data.use) <- make.unique(names = colnames(x = data.use)) 
>    data.use %>% melt(id.vars = "cell") -> data.use 
>    names(x = data.use)[names(x = data.use) == 'variable'] <- 'gene' 
>    names(x = data.use)[names(x = data.use) == 'value'] <- 'expression' 
>    data.use$ident <- cells.ident[data.use$cell] 
>    if(!is.null(group.order)) { 
>      if(length(group.order) == length(levels(data.use$ident)) && all(group.order %in% levels(data.use$ident))) { 
>        data.use$ident <- factor(data.use$ident, levels = group.order) 
>      } 
>      else { 
>        stop("Invalid group.order") 
>      } 
>    } 
>    breaks <- seq( 
>      from = min(data.use$expression), 
>      to = max(data.use$expression), 
>      length = length(x = PurpleAndYellow()) + 1 
>    ) 
>    data.use$gene <- with( 
>      data = data.use, 
>      expr = factor(x = gene, levels = rev(x = unique(x = data.use$gene))) 
>    ) 
>    data.use$cell <- with( 
>      data = data.use, 
>      expr = factor(x = cell, levels = cells.use) 
>    ) 
>    # might be a solution if we want discrete interval units, makes the legend clunky though 
>    #data.use$expression <- cut(data.use$expression, breaks = breaks, include.lowest = T) 
>    #heatmap <- ggplot(data.use, aes(x = cell, y = gene, fill = expression)) + geom_tile() + 
>    #                  scale_fill_manual(values = PurpleAndYellow(), name= "Expression") + 
>    #                  scale_y_discrete(position = "right", labels = rev(genes.use)) + 
>    #                  theme(axis.line=element_blank(), axis.title.y=element_blank(), 
>    #                        axis.ticks.y = element_blank()) 
>    if (rotate.key) { 
>      key.direction <- "horizontal" 
>      key.title.pos <- "top" 
>    } else { 
>      key.direction <- "vertical" 
>      key.title.pos <- "left" 
>    } 
>    heatmap <- ggplot( 
>      data = data.use, 
>      mapping = aes(x = cell, y = gene, fill = expression) 
>    ) + 
>      geom_tile() + 
>      scale_fill_gradient2( 
>        low = col.low, 
>        mid = col.mid, 
>        high = col.high, 
>        name= "Expression", 
>        guide = guide_colorbar( 
>          direction = key.direction, 
>          title.position = key.title.pos 
>        ) 
>      ) + 
>      scale_y_discrete(position = "right", labels = rev(genes.use)) + 
>      theme( 
>        axis.line = element_blank(), 
>        axis.title.y = element_blank(), 
>        axis.ticks.y = element_blank(), 
>        strip.text.x = element_text(size = group.cex), 
>        axis.text.y = element_text(size = cex.row), 
>        axis.text.x = element_text(size = cex.col), 
>        axis.title.x = element_blank() 
>      ) 
>    if (slim.col.label) { 
>      heatmap <- heatmap + 
>        theme( 
>          axis.title.x = element_blank(), 
>          axis.text.x = element_blank(), 
>          axis.ticks.x = element_blank(), 
>          axis.line = element_blank(), 
>          axis.title.y = element_blank(), 
>          axis.ticks.y = element_blank() 
>        ) 
>    } else { 
>      heatmap <- heatmap + theme(axis.text.x = element_text(angle = 90)) 
>    } 
>    if (! is.null(x = group.by)) { 
>      if (group.label.loc == "top") { 
>        switch <- NULL 
>        # heatmap <- heatmap + 
>        #   facet_grid( 
>        #     facets = ~ident, 
>        #     drop = TRUE, 
>        #     space = "free", 
>        #     scales = "free" 
>        #   ) + 
>        #   scale_x_discrete(expand = c(0, 0), drop = TRUE) 
>      } else { 
>        switch <- 'x' 
>        # heatmap <- heatmap + 
>        #   facet_grid( 
>        #     facets = ~ident, 
>        #     drop = TRUE, 
>        #     space = "free", 
>        #     scales = "free", 
>        #     switch = "x" 
>        #   ) + 
>        #   scale_x_discrete(expand = c(0, 0), drop = TRUE) 
>      } 
>      heatmap <- heatmap + 
>        facet_grid( 
>          facets = ~ident, 
>          drop = TRUE, 
>          space = "free", 
>          scales = "free", 
>          switch = switch, 
>        ) + 
>        scale_x_discrete(expand = c(0, 0), drop = TRUE) 
>      if (draw.line) { 
>        panel.spacing <- unit(x = group.spacing, units = 'lines') 
>        # heatmap <- heatmap + theme(strip.background = element_blank(), panel.spacing = unit(group.spacing, "lines")) 
>      } else { 
>        panel.spacing <- unit(x = 0, units = 'lines') 
>        # 
>      } 
>      heatmap <- heatmap + 
>        theme(strip.background = element_blank(), panel.spacing = panel.spacing) 
>      if (group.label.rot) { 
>        heatmap <- heatmap + theme(strip.text.x = element_text(angle = 90)) 
>      } 
>    } 
>    if (remove.key) { 
>      heatmap <- heatmap + theme(legend.position = "none") 
>    } 
>    if (! is.null(x = title)) { 
>      heatmap <- heatmap + labs(title = title) 
>    } 
>    if (do.plot) { 
>      heatmap 
>    } 
>    return(heatmap) 
>  } 
> Best,
> Leon

oh, sorry, I want to say PCHeatmap, so sometimes I fall into puzzle, which function I am using, thanks a lot, do you have some suggestions on comparing differerent genes on different conditions.
![image](https://user-images.githubusercontent.com/25199946/47284633-a2957e00-d61a-11e8-8ce0-072eb39704e4.png)
