### ISSUE TITLE
error in Seurat_5.0.3.9909 for Visium HD

### ISSUE THREAD

**Issue by lilwo** [satijalab/seurat#8742]
Please follow the install instructions included our [quickstart vignette](https://satijalab.org/seurat/articles/visiumhd_commands_intro) - support for Visium HD will be introduced in v5.1.0 but for now is available as pre-release v5.0.3.9909 👍

_Originally posted by @dcollins15 in https://github.com/satijalab/seurat/issues/8700#issuecomment-2027267593_

Thanks for the great job
I 've tryed the new seuat ,but there is an error when I run Load10X_Spatial:
Error in if (tools::file_ext(filename) == "parquet") { : 
  the condition has length > 1
and I found it happend at code 
    if (is.null(image)) {
        image.list <- mapply(Read10X_Image, file.path(data.dirs, 
            "spatial"), assay = assay.names, slice = slice.names, 
            MoreArgs = list(filter.matrix = filter.matrix))
May I ask what is the reason?

**Comment by dcollins15** [comment]
It seems like `Read10X_Image` is finding more than one `tissue_positions` file in the specified `image.dir` - what does your file structure look like?

**Comment by lilwo** [comment]
> It seems like `Read10X_Image` is finding more than one `tissue_positions` file in the specified `image.dir` - what does your file structure look like?
Yes, it is. I converted tissue_positions.parquet to csv format earlier. 
 Is SCTransform or Normalize and scale recommended for HD data? It seems that SCTransform is not easy to use because it requires a lot of computational power and filtering, which NormalizeData does not.

**Comment by dcollins15** [comment]
> Yes, it is. I converted tissue_positions.parquet to csv format earlier.

Remove the duplicate file from the `image.dir` and things should work properly 😃 

> Is SCTransform or Normalize and scale recommended for HD data? It seems that SCTransform is not easy to use because it requires a lot of computational power and filtering, which NormalizeData does not.

Per the vignette, we recommend running the standard pre-processing workflow in favor of SCTransform - if you have any other questions not pertaining to the topic of this thread, please open another issue 👍
