### ISSUE TITLE
SCT assay for differential expression analysis using findMarkers()

### ISSUE THREAD

**Issue by JonasHaesevoets** [satijalab/seurat#8747]
Dear,

I've been combing through posts in this repository and other online resources, but I haven't found a definitive answer on whether to use the RNA or SCT assay for differential expression analysis (DEA) in Seurat v5.

Could you please clarify the recommended approach?

Here's what I've gathered so far:

Limited SCT Assay Functionality: It seems directly performing DEA on the SCT assay in Seurat v5 might not be ideal due to limited functionality and potential incomparability between datasets.
Is this understanding correct?

If so, would using the normalized RNA assay (after SCTransform normalization) be the recommended course of action for differential expression analysis in Seurat v5?

I appreciate any insights you can offer.

Thanks,

**Comment by saketkc** [comment]
> Limited SCT Assay Functionality: It seems directly performing DEA on the SCT assay in Seurat v5 might not be ideal due to limited functionality and potential incomparability between datasets.

This isn't correct. You should be able to run `PrepSCTFindMarkers` and then run DE on the SCT assay.

**Comment by JHCCoder** [comment]
Except that the issue integrating the sample [#8566](https://github.com/satijalab/seurat/issues/8566) based on this [tutorial ](https://satijalab.org/seurat/articles/integration_introduction.html) isn't resolved at the moment. So if you have multiple samples, I don't know how would I proceed. I would love to use SCTransformed data but I'm forced to resort to log normalized data at this point.
