### ISSUE TITLE
changed color of identity after BuildClusterTree do.reorder =T

### ISSUE THREAD

**Issue by MichaelPeibo** [satijalab/seurat#875]
Hi,

I did Phylogenetic Analysis  by 
`mda=BuildClusterTree(mda,do.reorder = TRUE,reorder.numeric = TRUE)`

however, the color palette is changed, see below, is there any way to recover previous color palette?
(Previous one is more 'colorful' to me)

Thanks!
 

[TSNEplot_ordered.pdf](https://github.com/satijalab/seurat/files/2501682/TSNEplot_ordered.pdf)
[TSNEplot_previous.pdf](https://github.com/satijalab/seurat/files/2501688/TSNEplot_res1.2_pc70.new.pdf)

**Comment by dhb2128** [comment]
ClusterTree returns a numeric value, whereas the ident before was a factor. If you make `mda@ident <- as.factory(mda@ident)` you should see the old colors. You can also return the ggplot object with `do.return=T` and then run `scale_color_hue()`

**Comment by MichaelPeibo** [comment]
@dhb2128 
Great! 
It works!

Thanks!
