### ISSUE TITLE
HarmonyIntegration - HarmonyMatrix is deprecated

### ISSUE THREAD

**Issue by xxiann** [satijalab/seurat#8756]
The current `HarmonyIntegration` method provided by Seurat uses a deprecated version function `HarmonyMatrix()` instead of `RunHarmony()`. Though the warning message produced indicates that all unused parameter passed on from `HarmonyMatrix` are ignored, there are still some inconsistencies in terms on default parameters, e.g. `lambda=1` instead of `lambda=NULL` default in the current `HarmonyIntegration`. Hopefully you will be able to look into this!

```r
# code to reproduce
# load dataset
ifnb <- LoadData("ifnb")
# split the RNA measurements into two layers one for control cells, one for stimulated cells

ifnb[["RNA"]] <- split(ifnb[["RNA"]], f = ifnb$stim)
i
# run standard anlaysis workflow
ifnb <- NormalizeData(ifnb)
ifnb <- FindVariableFeatures(ifnb)
ifnb <- ScaleData(ifnb)
ifnb <- RunPCA(ifnb)

ifnb <- IntegrateLayers(object = ifnb, method = HarmonyIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)

sessionInfo()
# other attached packages:
#  [1] lubridate_1.9.3       forcats_1.0.0         stringr_1.5.1        
#  [4] dplyr_1.1.4           purrr_1.0.2           readr_2.1.5          
#  [7] tidyr_1.3.1           tibble_3.2.1          ggplot2_3.5.0        
# [10] tidyverse_2.0.0       harmony_1.2.0         Rcpp_1.0.12          
# [13] patchwork_1.2.0       SeuratWrappers_0.3.5  SeuratData_0.2.2.9001
# [16] Seurat_5.0.3          SeuratObject_5.0.1    sp_2.1-3    
```

Warning Message:
Warning: HarmonyMatrix is deprecated and will be removed in the future from the API in the futureWarning: Warning: The parameters do_pca and npcs are deprecated. They will be ignored for this function call and please remove parameters do_pca and npcs and pass to harmony cell_embeddings directly.Warning: Warning: The parameter tau is deprecated. It will be ignored for this function call and please remove parameter tau in future function calls. Advanced users can set value of parameter tau by using parameter .options and function harmony_options().Warning: Warning: The parameter block.size is deprecated. It will be ignored for this function call and please remove parameter block.size in future function calls. Advanced users can set value of parameter block.size by using parameter .options and function harmony_options().Warning: Warning: The parameter max.iter.harmony is replaced with parameter max_iter. It will be ignored for this function call and please use parameter max_iter in future function calls.Warning: Warning: The parameter max.iter.cluster is deprecated. It will be ignored for this function call and please remove parameter max.iter.cluster in future function calls. Advanced users can set value of parameter max.iter.cluster by using parameter .options and function harmony_options().Warning: Warning: The parameter epsilon.cluster is deprecated. It will be ignored for this function call and please remove parameter epsilon.cluster in future function calls. Advanced users can set value of parameter epsilon.cluster by using parameter .options and function harmony_options().Warning: Warning: The parameter epsilon.harmony is deprecated. It will be ignored for this function call and please remove parameter epsilon.harmony in future function calls. If users want to control if harmony would stop early or not, use parameter early_stop. Advanced users can set value of parameter epsilon.harmony by using parameter .options and function harmony_options().

**Comment by dcollins15** [comment]
Updating `HarmonyIntegration` is on our roadmap and should be complete soon 👍
