### ISSUE TITLE
SingleR

### ISSUE THREAD

**Issue by nitinmahajan20** [satijalab/seurat#8757]
I am having issue running the Single R , nit sure why I am getting the error. Please help

```
seurat_integrated,
```
An object of class Seurat 
51866 features across 54453 samples within 3 assays 
Active assay: RNA (24468 features, 0 variable features)
 2 layers present: data, counts
 2 other assays present: SCT, integrated
 2 dimensional reductions calculated: pca, umap

```
ref <- celldex::HumanPrimaryCellAtlasData()
seurat_integrated_counts <- GetAssayData(seurat_integrated, layer = 'counts')

pred <- SingleR(test = seurat_integrated_counts,
        ref = ref,
        labels = ref$label.main)

pred
```

ERROR 

```
Error in SingleR(test = seurat_integrated_counts, ref = ref, labels = ref$label.main) :  argument "sc_data" is missing, with no default

**Comment by samuel-marsh** [comment]
Hi,

This appears to be an error with SingleR package and not Seurat.  I would suggest posting to their repo for help navigating this error.

Best,
Sam
