### ISSUE TITLE
 it is okay to leave the default `scale=TRUE' in FindIntegrationAnchors when doing RPCA integration using CLR (Seurat  ‘4.3.0’)

### ISSUE THREAD

**Issue by d-lashgari** [satijalab/seurat#8759]
Hi, I am still unclear about the 3rd question from @NienkeMekkes . The vignette doesn't mention the `scale` option, which probably indicates that it is okay to leave the default `scale=TRUE`. But I am not sure why this is the case, as SCTransform is meant to be an alternative to `NormalizeData`, `FindVariableFeatures` AND `ScaleData`. Is scaling the data in `FindIntegrationAnchors` really necessary?
Thanks,
Vinnie

_Originally posted by @vincr04 in https://github.com/satijalab/seurat/issues/1734#issuecomment-597137744_

**Comment by d-lashgari** [comment]
I assume FindIntegrationAnchors sets scale to Flase if the the method used  for normalization is sctramsform but to me  it  is unclear  what happens when using rpca with sctransform for integration.  In this [vignette](https://satijalab.org/seurat/archive/v3.2/integration.html);  RPCA section, data  is scaled but scale is not set to false afterwards. is this ok?

**Comment by dcollins15** [comment]
Hi @d-lashgari ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
