### ISSUE TITLE
Error running Seurat with normalized input and zinbwave

### ISSUE THREAD

**Issue by sharvari14** [satijalab/seurat#876]
Hi,

I am writing to seek your help with using a TMM normalized input matrix as input to create Seurat object.

I get an error following the example in the code below to use zinbwave function:
[(https://github.com/drisso/zinbwave/issues/17)]

```
se <- SummarizedExperiment(as.matrix(input)) # put in the colData() part of the object at least batch
zinb <- zinbwave(se[input_obj@var.genes,],K=10, epsilon=1000)
Error in .local(Y, ...) : 
  The input matrix should contain only whole numbers.
Can you please help with this error.

```
Thanks
Sharvari

**Comment by satijalab** [comment]
I believe this error is with the zinbwave package (which we love!), but unfortunately cannot provide support for. Since zinbwave operates on counts, please make sure you are passing a counts (and not normalized data) matrix
