### ISSUE TITLE
as.Seurat Converter Loses a Matrix

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#8763]
Either `logcounts` or `merged` becomes `data` but it is not clear from `?as.Seurat` which one is lost and which one is renamed.

```r
> allHuman
class: SingleCellExperiment 
dim: 21473 101722 
metadata(44): Samples Samples ... Samples Samples
assays(3): counts logcounts merged
allHuman <- as.Seurat(allHuman)
> allHuman
An object of class Seurat 
21473 features across 101722 samples within 1 assay 
Active assay: originalexp (21473 features, 0 variable features)
 2 layers present: counts, data
 2 dimensional reductions calculated: PCA, UMAP
```

Is it by design or a bug?

**Comment by igrabski** [comment]
Hi, we no longer support `as.Seurat`, but you can look at `sceasy` or `scCustomize` for object conversion functions.

**Comment by DarioS** [comment]
That's a shame because none of the alternatives actually work.

```r
> library(sceasy)
> converted <- convertFormat(allHuman, from = "sce", to = "seurat") # Only from seurat to sce shown in README.
Error: Unsupported conversion from "sce" to "seurat"
```

> Currently the package is primarily centered around interactivity with Seurat Objects with some functionality with LIGER objects and support for CellBender outputs. If users are interested in adapting functions to provide comparable functionality with SCE or other object formats, I would be happy to add them.

Source: scCustomize README.
