### ISSUE TITLE
Run sctransform on the whole object or per cell type

### ISSUE THREAD

**Issue by anglixue** [satijalab/seurat#8764]
Hi,

I wonder if I have a sample with multiple cohorts and batches, would you recommend to run SCTransform on the whole object or separately for each cell type? Which option will provide better correction results?

Thank you!

**Comment by dcollins15** [comment]
Hi @anglixue ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
