### ISSUE TITLE
Find DEG based on spatial data

### ISSUE THREAD

**Issue by hejingyu1023** [satijalab/seurat#8766]
I integrated control and mutant data, Trying to do "Findconservedmarker" and "DEG", former one perfectly work after i did the change on the UMI assay, but when comes to DEG, cluster0 and 4 had error 
"> deg_cluster_0 <- FindMarkers(cluster_0_data, ident.1 = "Control", ident.2 = "Mutant", group.by = "combined.ident" )
Error in FindMarkers.SCTAssay(object = data.use, latent.vars = latent.vars,  : 
  Object contains multiple models with unequal library sizes. Run `PrepSCTFindMarkers()` before running `FindMarkers()`.

other cluster works smoothly. 

My codes for DEG part are like

cluster_1_data <- subset(growthplate.spatial, idents = 1)
# Set identities within the subset to Control or Mutant based on your metadata column
cluster_1_data <- PrepSCTFindMarkers(cluster_1_data)
deg_cluster_1 <- FindMarkers(cluster_1_data, ident.1 = "Control", ident.2 = "Mutant", group.by = "combined.ident" )
print(deg_cluster_1)

cluster_2_data <- subset(growthplate.spatial, idents = 2)
cluster_2_data <- PrepSCTFindMarkers(cluster_2_data)
deg_cluster_2 <- FindMarkers(cluster_2_data, ident.1 = "Control", ident.2 = "Mutant", group.by = "combined.ident" )
print(deg_cluster_2)

cluster_3_data <- subset(growthplate.spatial, idents = 3)
cluster_3_data <- PrepSCTFindMarkers(cluster_3_data)
deg_cluster_3 <- FindMarkers(cluster_3_data, ident.1 = "Control", ident.2 = "Mutant", group.by = "combined.ident" )
print(deg_cluster_3)

## ? unequal library size
cluster_4_data <- subset(growthplate.spatial, idents = 4)
cluster_4_data <- PrepSCTFindMarkers(cluster_4_data)
deg_cluster_4 <- FindMarkers(cluster_4_data, ident.1 = "Control", ident.2 = "Mutant", group.by = "combined.ident" )
print(deg_cluster_4)

Thank you so much for solving this in advance!!

**Comment by zskylarli** [comment]
Hi - please refer to issue https://github.com/satijalab/seurat/issues/6427 and feel free to reopen the issue if this solution does not work. Thanks!
