### ISSUE TITLE
Merging error 

### ISSUE THREAD

**Issue by apal6** [satijalab/seurat#8768]
Hi, 

I have 6 samples and I am trying to merge then. When trying to run the joinlayers command, i get the error saying:

`Error in `[<-.data.frame`(`*tmp*`, , i, value = new("Seurat", assays = list( : 
  replacement has 32285 rows, data has 40001`

code:
merged_obj<- merge (x=samp1, y= list(samp2,samp2,samp4,samp5,samp6))
merged_obj[["RNA"]] <- JoinLayers(merged_obj)

How can I solve this?
Thank you!

**Comment by leonfodoulian** [comment]
Hi @apal6,

I am not sure if this is causing the issue, but you have a typo in your code: `samp2` is provided twice to the `merge` function.

Best,
Leon
