### ISSUE TITLE
error of the install of seurat

### ISSUE THREAD

**Issue by 2018luyi** [satijalab/seurat#877]
When I install of the seurat as your website show,I always has the problems as the below. I already install HDF5 in my platform. I hope you can help me to slove the problem.
![problem](https://user-images.githubusercontent.com/44388015/47334186-98c25800-d6b8-11e8-82a4-a7e47388bbec.png)
![problem](https://user-images.githubusercontent.com/44388015/47334212-b7285380-d6b8-11e8-931c-5cf798a66113.png)

**Comment by karim-soufi** [comment]
The error lies with the hdf5r R package not seurat. make sure you have HDF5 properly installed.

**Comment by 2018luyi** [comment]
Thanks for your respond. I have reslove this problem. Thanks .

2018-10-24 04:23:34"Henrik Bengtsson" <notifications@github.com>写道：

Sorry, I should have been clear; you only need the workaround if you cannot install system library libhdf5 on your system.
