### ISSUE TITLE
Problem in Seurat and Doubltfinder

### ISSUE THREAD

**Issue by Drizzle63** [satijalab/seurat#8771]
when I run the doubletFinder 2.04 , it shows that:
Error in seu@meta.data :  no applicable method for `@` applied to an object of class "list" 
does anyone know how to solve this problem?
 my R version is 4.4.0
should I install other verisons?

**Comment by morallawwithin** [comment]
https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/177
