### ISSUE TITLE
!Significant differences in avg_log2FC between Seurat versions 4 and 5 in FindMarkers function

### ISSUE THREAD

**Issue by xinmiaoyan** [satijalab/seurat#8776]
I ran the FindMarkers function on the same data with the same group assigned. However, the avg_log2FC is strikingly different between the old Seurat version 4 and the new version 5. The p-value and adjusted p-value seem the same as before, but the avg_log2FC is significantly different (see attached). Does anyone have a solution to this issue?

<img width="1034" alt="image" src="https://github.com/satijalab/seurat/assets/83053884/f7f75fbd-1788-4d71-bb18-bb9625399729">

**Comment by morallawwithin** [comment]
Look here:
https://github.com/satijalab/seurat/issues/6701

**Comment by mhkowalski** [comment]
Hello, 

Also linking our [NEWS](https://satijalab.org/seurat/articles/announcements.html) page that describes this change. The difference is related to choice in pseudocount, which will be much higher for lowly expressed genes.
