### ISSUE TITLE
Harmony integration through seurat

### ISSUE THREAD

**Issue by NeuralBind** [satijalab/seurat#8783]
Hello, to begin with great work and amazing tool ! 
Straight to the point i have a merged object with  3 conditions (condition column in metadata)  with 3 datasets/replicates each(with distinct numbers). 
When i try to run the harmony via the seurat function in order to integrate all the datasets together,  should i use the group.by.vars= c("condition", "dataset id")? Or should i use solely the seperate identifier (dataset id) for each dataset.  Each grouping seem to give slightly different umaps. Do i over-correct by using both condition and replicate?

Thank you in advance:)

**Comment by mhkowalski** [comment]
Hello, 

It seems that integrating by "dataset" or by "dataset" and "condition" would be the same,  as "dataset" would fully specify the condition. You might get slightly different results as there is some stochasticity in their [method](https://github.com/immunogenomics/harmony/issues/13). I would just integrate by "dataset" here.
