### ISSUE TITLE
is this an error in seurat?

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#879]

**Comment by karim-soufi** [comment]
I reckon it's the 2D kernel density estimation contour.

**Comment by 2236529177** [comment]
> I reckon it's the 2D kernel density estimation contour.
thanks a lot, but I totally can not understand what is your meaning.

**Comment by mschilli87** [comment]
@2236529177:

If you look at https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/plotting.R#L2914-L2932 you'll see four parameters concerning the contour:

1. `do.contour` (which defaults to `TRUE`): set it to `FALSE` and the white stuff you suspect to be an error will be gone.
2. `contour.lwd` (which defaults to `3`): decrease and the line will be thinner, increase and it will be thicker.
3. `contour.col` (which defaults to `"white"`): set it to `"purple"` and the white stuff will be turned into purple stuff.
4. `contour.lty` (which defaults to `2`): I'll leave it to you to find out what it does, consider it an exercise. :wink:

Even without knowing what the word *contour* means one can easily find this via [a simple search](https://github.com/satijalab/seurat/search?q=contour&unscoped_q=contour). Maybe you could do a certain (minimal) amount of research yourself before asking [> 50 people](https://github.com/satijalab/seurat/watchers) that are neither paid to help you, nor will be co-authors of your paper for help [several times a week](https://github.com/satijalab/seurat/issues?q=is%3Aissue+author%3A2236529177+)? :wink:

**Comment by 2236529177** [comment]
@mschilli87 ， Thanks a lot, I am so sorry so giving some many issues. about your exercise, as usual, lty means line type, such as solid line, dotted line.
your advice is really helpful, but as a user of seurat, I think we common users may have no ability to deeper into source code. and I also do think the instructions is a little not complete, I know the researcher are really busy. I can not require more, thinks a lot , if you are interested in questions I commited today, I hope you can help me , thinks a lot, after these questions, I think I will be lost from seurat.
