### ISSUE TITLE
Data download links on multimodal_vignette.Rmd don't work.

### ISSUE THREAD

**Issue by SethMagnusJarvis** [satijalab/seurat#8796]
I was trying to download the data and found that the links don't seem to work. It looks like this is because they have ftp:// in front of them. When I remove this the download works. 

This issue was found on safari on macOS

**Comment by zskylarli** [comment]
Hi - we no longer support that vignette. For multimodal analysis, please refer to [this](https://satijalab.org/seurat/articles/multimodal_reference_mapping) vignette instead.
