### ISSUE TITLE
Error in `ProjectCellEmbeddings.IterableMatrix` (affecting `FindTransferAnchors`)

### ISSUE THREAD

**Issue by bnprks** [satijalab/seurat#8799]
Hi, I recently had a question from a BPCells user who noticed that `FindTransferAnchors` did not complete when using BPCells objects as inputs. I think I've tracked this issue down to the changes made in [this Seurat commit](https://github.com/satijalab/seurat/commit/ec41c2c027f760430be86635b5f6f99362bae254) from September 2023. If that change is reverted, then my example below works just fine but with it present the function hangs.

I'm not exactly sure from reading the code in which situations the 2023 change is needed, but it seems to have had a side effect of disrupting some other use-cases.

When running this example the last call to `FindTransferAnchors` does not complete for me, but it runs fine if we use normal seurat objects
```r
library(BPCells)
library(Seurat)

pbmc3k <- pbmc3k.SeuratData::pbmc3k@assays$RNA@counts[,1:100]
cbmc <- cbmc.SeuratData::cbmc@assays$RNA@counts[,1:100]

matList1 <- list(as(pbmc3k, "IterableMatrix"), as(cbmc, "IterableMatrix"))
# Running this instead works fine:
# matList1 <- list(pbmc3k, cbmc)

sRef = CreateSeuratObject(counts = matList1[[2]])
sRef <- NormalizeData(sRef)
sRef <- FindVariableFeatures(sRef)
sRef <- ScaleData(sRef)
sRef <- RunPCA(sRef)
sRef <- FindNeighbors(sRef, dims = 1:30)
sRef <- FindClusters(sRef)
sRef <- RunUMAP(sRef, dims = 1:30)

sq1 <- NormalizeData(sq1)
anchors <- FindTransferAnchors(reference = sRef, query = sq1, dims = 1:30, reference.reduction = "pca")
```

Something extremely weird seems to happen when the line `reference.data <- do.call(cbind, reference.data.list)` is called. In the debugger I see it creates a dense matrix object of mostly NULL and some BPCells objects as entries.
```
> reference.data[1:3,1:3]
                                                                      
[1,] <S4 class ‘RenameDims’ [package “BPCells”] with 4 slots> NULL NULL
[2,] <S4 class ‘RenameDims’ [package “BPCells”] with 4 slots> NULL NULL
[3,] <S4 class ‘RenameDims’ [package “BPCells”] with 4 slots> NULL NULL
```
When the length of `reference.data.list` is 1, I think it ends up calling some default R implementation and doesn't even hit the BPCells implementation of `cbind2` which is how BPCells overrides `cbind` in normal cases.

**Comment by Gesmira** [comment]
Hi Ben, 
Thank you for bringing this to our attention! We introduced this code for another function that calls `ProjectCellEmbeddings.IterableMatrix` which could potentially be passed a reference object with multiple layers. I'm honestly not sure if we never tested for this case in `FindTransferAnchors` specifically or if the behavior of cbind on IterableMatrix classes changed recently, but I also had never seen that strange result before. 

As a test, I started by just removing the code that creates a list and instead set the reference.data directly. This allows `ProjectCellEmbeddings` to run normally, but if we use a reference with `IterableMatrix` counts and a query with `dgCMatrix` counts, it still errors out later as we also call `cbind` in [`StitchMatrix.IterableMatrix`](https://github.com/satijalab/seurat-object/blob/4d3739bbdb8b801f9adbe542ad179d7dec61cafc/R/utils.R#L2117-L2144) to temporarily join the reference and query data in one object. 

Reproducible example that highlights both the above and the case in which you call cbind on just one `IterableMatrix`:
```
> a <- pbmc3k
> b <- as(pbmc3k, "IterableMatrix")

# WORKS
> cbind(a,a)[1:3,1:3]
3 x 3 sparse Matrix of class "dgCMatrix"
              AAACATACAACCAC AAACATTGAGCTAC AAACATTGATCAGC
AL627309.1                 .              .              .
AP006222.2                 .              .              .
RP11-206L10.2              .              .              .

# DOESNT WORK 
> cbind(a,b)[1:3,1:3]
                                                           
[1,] <S4 class 'dgCMatrix' [package "Matrix"] with 6 slots>
[2,] <S4 class 'dgCMatrix' [package "Matrix"] with 6 slots>
[3,] <S4 class 'dgCMatrix' [package "Matrix"] with 6 slots>
                                                                                  
[1,] <S4 class 'Iterable_dgCMatrix_wrapper' [package "BPCells"] with 4 slots> NULL
[2,] <S4 class 'Iterable_dgCMatrix_wrapper' [package "BPCells"] with 4 slots> NULL
[3,] <S4 class 'Iterable_dgCMatrix_wrapper' [package "BPCells"] with 4 slots> NULL

# WORKS
> cbind(b,b)[1:3,1:3]
3 x 3 IterableMatrix object with class MatrixSubset

Row names: AL627309.1, AP006222.2, RP11-206L10.2
Col names: AAACATACAACCAC, AAACATTGAGCTAC, AAACATTGATCAGC

Data type: double
Storage order: column major

Queued Operations:
1. Concatenate cols of 2 matrix objects with classes: Iterable_dgCMatrix_wrapper, Iterable_dgCMatrix_wrapper (threads=0)
2. Select rows: 1, 2, 3 and cols: 1, 2, 3

# DOESNT WORK 
> cbind(b)[1:3,1:3]
                                                                                       
[1,] <S4 class 'Iterable_dgCMatrix_wrapper' [package "BPCells"] with 4 slots> NULL NULL
[2,] <S4 class 'Iterable_dgCMatrix_wrapper' [package "BPCells"] with 4 slots> NULL NULL
[3,] <S4 class 'Iterable_dgCMatrix_wrapper' [package "BPCells"] with 4 slots> NULL NULL
```

Do you know if running cbind on a `dgCMatrix` with an `IterableMatrix` worked previously? If it never did or you're not sure, we can deal with this by some combination of removing the need for the `cbind` call by doing any joining of layers upstream of `ProjectCellEmbeddings` and converting `IterableMatrix` classes to sparse matrices when both classes are used so `cbind` works in the later calls. 

Again, thanks for the clear bug report that made this much easier for us to pinpoint!

**Comment by bnprks** [comment]
Hi Gesmira,

Thanks to your comments I double-checked how the `Matrix` package handles `cbind` implementation, and have found some improvements that I think solve the issue (currently available from the latest BPCells main). Previously, `cbind` support came by defining a generic only for `cbind2(IterableMatrix, IterableMatrix)` (cbind repeatedly calls cbind2 for pairs of arguments). I've now added support for `cbind2(IterableMatrix, missing)` , `cbind2(IterableMatrix, dgCMatrix)`, and `cbind2(dgCMatrix, IterableMatrix)`. 

I don't think cbind of `dgCMatrix` with `IterableMatrix` ever worked previously, but it should work now. And single-argument `cbind` should work now too. 

When testing the above example with the BPCells update `FindTransferAnchors` appears to work fine, so probably no Seurat changes are needed after all.

-Ben

**Comment by Gesmira** [comment]
Awesome, thanks Ben! Glad this was figured out as it will also resolve other potential edge cases that we hadn't tested for yet any time an `IterableMatrix` and `dgCMatrix` are being joined. 
Best, 
Gesi
