### ISSUE TITLE
Normalization for Dataset with Multiple Conditions and Multiple Samples in Each Condition

### ISSUE THREAD

**Issue by Nack3l** [satijalab/seurat#8800]
I have a dataset containing multiomodal (RNA + ADT) data that has 9 samples across three different batches, with each batch loading 3, multiplexed samples. Batch 1 contains 3 samples corresponding to three healthy controls; batch 2 contains 3 samples taken from a single patient at 3 different time points (0, 3, 12 months); batch 3 contains 3 samples taken from another patient at 3 different time points (0, 3, 12 months). This dataset is a bit unique because while each batch contains 3 samples, batch 1 contains 3 unique replicates, while batch 2 and 3 contain only a single replicate at 3 time points.

I currently have a Seurat object that merges all 9 samples after standard demultiplexing and QC, and I understand that it is most appropriate to split my assays into multiple layers before I perform normalization (SCT for RNA and CLR for ADT). However, I am unsure as to whether I should split my object into 9 layers, with each layer corresponding to a sample, or 3 layers, with each layer corresonding to a batch. In other words, should I normalize each sample individually or each batch individually? I've currently gone with the former option, so my code looks as follows:

#Splitting merged Seurat object by sample (not batch), generating 9 different lyaers
comb.nonorm2[["RNA"]] <- split(comb.nonorm2[["RNA"]], f = comb.nonorm2$sample)
comb.nonorm2[["ADT"]] <- split(comb.nonorm2[["ADT"]], f = comb.nonorm2$sample)

#Normalizing both RNA and ADT by layer, so normalization is performed individually for each of the 9 layers
comb.nonorm2 <- NormalizeData(comb.nonorm2, assay = "ADT", normalization.method = "CLR")
comb.nonorm2 <- SCTransform(comb.nonorm2)

#Performing integration
comb.nonorm3 <- IntegrateLayers(object = comb.nonorm3, method = CCAIntegration, normalization.method = "SCT", verbose = F)

**Comment by dcollins15** [comment]
Hi @Nack3l,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
