### ISSUE TITLE
no slot of name "counts" for this object of class "Assay5"

### ISSUE THREAD

**Issue by danielguion** [satijalab/seurat#8804]
install.packages("Matrix")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/Matrix_1.6-5.tgz'
Content type 'application/x-gzip' length 5355734 bytes (5.1 MB)
==================================================
downloaded 5.1 MB

The downloaded binary packages are in
	/var/folders/1r/79nr9qg51152dcq218n63jym0000gn/T//RtmpHhbwcD/downloaded_packages
> install.packages("Seurat")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/Seurat_5.0.3.tgz'
Content type 'application/x-gzip' length 4236629 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

The downloaded binary packages are in
	/var/folders/1r/79nr9qg51152dcq218n63jym0000gn/T//RtmpHhbwcD/downloaded_packages
> 
> library(Matrix)
> library(Seurat)
Loading required package: SeuratObject
Loading required package: sp
‘SeuratObject’ was built under R 4.3.1 but the current version is
4.3.3; it is recomended that you reinstall ‘SeuratObject’ as the ABI
for R may have changed
‘SeuratObject’ was built with package ‘Matrix’ 1.6.3 but the current
version is 1.6.5; it is recomended that you reinstall ‘SeuratObject’ as
the ABI for ‘Matrix’ may have changed

Attaching package: ‘SeuratObject’

The following object is masked from ‘package:base’:

    intersect

> 
> # Create a data frame
> test_data <- data.frame(
+     gene = c("Gene1", "Gene2", "Gene3"),
+     sample1 = c(1, 2, 3),
+     sample2 = c(2, 3, 4)
+ )
> 
> row.names(test_data) <- test_data$gene
> test_data <- test_data[ , -1]  # Remove the 'gene' column, using row names instead
> 
> # Convert to sparse matrix
> test_sparse <- as(as.matrix(test_data), "dgCMatrix")
> 
> # Create a Seurat object
> test_pmbc <- CreateSeuratObject(counts = test_sparse, project = "Test Project")
> 
> # Check if the 'counts' slot exists
> str(test_pmbc@assays$RNA@counts)
Error in str(test_pmbc@assays$RNA@counts) : 
  no slot of name "counts" for this object of class "Assay5"

**Comment by samuel-marsh** [comment]
Hi @danielguion 
The issue here is that the structure of V5 objects have changed and so `test_pmbc@assays$RNA@counts` is no longer the location of counts within the object.

That is typically why it is better to use designated data accessor functions vs. `@` and `$`.

In this case there are couple ways to just check that "counts" exists.

First can just run object name which should give an output like this:

```
> pbmc
An object of class Seurat 
13714 features across 2700 samples within 1 assay 
Active assay: RNA (13714 features, 0 variable features)
 2 layers present: counts, data
```

Or you can check layers with `Layers` function:
```
> Layers(object = pbmc)
[1] "counts" "data"  
```

Best,
Sam
