### ISSUE TITLE
Problem in VlnPlot, error with missing value? 

### ISSUE THREAD

**Issue by rootze** [satijalab/seurat#8806]
Hello Seurat developer,

Thank you for developing Seruat V5. I am relatively new to version 5. 
I have a question error code that I recently ran into, which I am super confused about.

```
> p <- VlnPlot(
+     object = NucSeq,
+     group.by = 'seurat_clusters',
+     features = c("SST"),
+     pt.size = 0,
+     raster=TRUE,
+     ncol = 1
+ )
Error in if (all(data[, feature] == data[, feature][1])) { :
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: Removing 367722 cells missing data for features requested
2: Removing 367722 cells missing data for vars requested

> # Check if "SST" is in the row names of NucSeq
> if ("SST" %in% rownames(NucSeq)) {
+   print("SST is present in the row names of NucSeq.")
+ } else {
+   print("SST is not present in the row names of NucSeq.")
+ }
[1] "SST is present in the row names of NucSeq."

```
SST as a gene is present in my NucSeq data, but somehow, I cannot plot it. I am not exactly sure why. 
 
My seurat version is Seurat_5.0.3 and SeuratObject_5.0.1

**Comment by morallawwithin** [comment]
Which assay are you using? The integrated one? Try to specify the layer you want to use.

**Comment by rootze** [comment]
> Which assay are you using? The integrated one? Try to specify the layer you want to use.

Great! Thanks for answering the question.
