### ISSUE TITLE
How to assign cell types to barcodes for spatial transcriptomics deconvolution?

### ISSUE THREAD

**Issue by 532at** [satijalab/seurat#8807]
Hi,

I work with 10x Genomics Visium data which I would like to deconvolute to single cell resolution. 

To do so, I need to have a metadata file with cell types assigned to barcodes. Is it possible to run the Seurat clustering pipeline, assign cell types based on gene expression analysis and afterwards assign these cell types barcodes?

Thank you in advance for the response.

Adrian

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I do want to clarify first that standard Visium is not single cell resolution.  The most beads will span multiple cells/cell types.  But yes, you can run analysis on the spatial data and assign identities to spots but need to be careful about calling them single cells.

Best,
Sam

**Comment by 532at** [comment]
Hi Sam, 

yes, I am aware that 10x Visium is not single-cell resolution, however, it is possible to deconvolute it with single-cell data to make it single-cell. To do so, I need count matrix plus metadata file with assigned cell types as you can see here 8:45 - https://www.youtube.com/watch?v=egJXHvqSQLE

Most published scRNA datasets do not publish metadata file so my question was how to make these files using Seurat by myself.

Best,
Adrian

**Comment by samuel-marsh** [comment]
Hi Adrian,

Again I'd be careful how you refer to it.  You can use single cell data along side to help with annotation or multi-modal analysis but the spots are still not single cell.  So while you can give each spot a putative identity I would be careful about saying they are now single cells.

In terms of analysis I would direct you to the Seurat tutorials as a start for performing spatial analysis but then also suggest consulting with bioinformatician on the analysis if you are unfamiliar.

Best,
Sam

**Comment by 532at** [comment]
Hi Sam,

I am familiar with Seurat tutorials as well as ST pipeline. I would like to perform https://cell2location.readthedocs.io/en/latest/ using above mentioned files (metadata file specifically) which I would like to build using Seurat. I appreciate your suggestions, but I would not address that issue not knowing what is available in the Internet. 

Best,
Adrian
