### ISSUE TITLE
Issue with merging Seurat Objects 

### ISSUE THREAD

**Issue by youcef-benmohammed** [satijalab/seurat#8811]
Hi,

I'm encountering an issue with merging multiple Seurat objects
I have attempted to merge them using the merge function as follows:

atlas.sc <- merge(b.cells, y=list(myeloid, stroma, t.cells), add.cell.ids = ls())

However, after merging, I'm unable to retrieve the counts layer, which represents the counts of my merged object.

Here is the returned layers:  

atlas.sc@assays$RNA

Assay (v5) data with 47809 features for 153563 cells
Top 10 variable features:
 CCL19, FDCSP, COMP, PTGDS, CR2, CXCL10, CXCL13, CCL21, CXCL9, FCAMR 
Layers:
 counts.1, counts.2, counts.FL01_NHC.3, counts.FL02_NHC.3, counts.FL03_NHC.3, counts.FL04_NHC.3,
counts.FL05_NHC.3, counts.FL06_NHC.3, counts.FL07_NHC.3, counts.FL08_NHC.3, counts.FL09_NHC.3,
counts.FL10_NHC.3, counts.FL-LC-11-1951.3, counts.FL-RA-03-1955.3, counts.FLCAF1_ME_1952.3,
counts.FL_GB_08_1950.3, counts.4, data.1, data.2, scale.data.2, data.FL01_NHC.3, data.FL02_NHC.3,
data.FL03_NHC.3, data.FL04_NHC.3, data.FL05_NHC.3, data.FL06_NHC.3, data.FL07_NHC.3, data.FL08_NHC.3,
data.FL09_NHC.3, data.FL10_NHC.3, data.FL-LC-11-1951.3, data.FL-RA-03-1955.3, data.FLCAF1_ME_1952.3,
data.FL_GB_08_1950.3, scale.data.3, data.4

Could someone help me please.

Best,
Youcef

**Comment by samuel-marsh** [comment]
Hi Youcef,

can you explain what you mean by “unable to retrieve counts”?  What code are you running and what errors re you receiving?

Best,
Sam

**Comment by dcollins15** [comment]
I think you may just want to run `JoinLayers` on your output to join all of the counts into a single matrix?
