### ISSUE TITLE
samples from different public datasets with different condition

### ISSUE THREAD

**Issue by MWRR** [satijalab/seurat#8815]
I am studying a specific disease by integrating single cell RNA PBMC samples. So I collected samples with different conditions from different public datasets (7 public datasets). I picked just one sample or two from some datasets and 20 samples from others to get 100 samples from 75 donors in total. This includes different conditions of disease severities, healthy, and treatment.
I create a Seurat object for each sample. Then I merged all objects and filtered out the low-quality cells. 
`Seurat_Obj <- CreateSeuratObject(COV.Obj, min.cells = 10,min.features = 200, names.field = 1, names.delim = "_") `

I run the standard normalization workflow on each sample.
`seu.listNorm <-  SplitObject(filtered_smp, split.by = "orig.ident")`
`seu.listNorm <- lapply(X = seu.listNorm, FUN = function(X) {`
                        `X <- NormalizeData(X)`
                        `X <- FindVariableFeatures(X, selection.method = "vst", nfeatures = 3000)`
                          `X <- ScaleData(X,vars.to.regress=c("percent.mt","percent.ribo"), verbose = F)`
                          `X <- RunPCA(X, npcs = 50)`
                          `X <-  RunUMAP(X, dims = 1:50)`
                         `X<- FindNeighbors(X, dims = 1:50)`             
                        `X<- FindClusters(X, resolution = 0.8)})`

I applied DoubletFinder individually on each Seurat object to remove doublets.
Then I merge all samples.

`# merge all samples after removing doublets`
`merged.singlets <- merge(x = list.filtNorm[[1]],y = list.filtNorm[2:length(list.filtNorm)])`

and run the standard normalization workflow on merged samples.
`merged.singlets<- NormalizeData(merged.singlets)`
`merged.singlets <- FindVariableFeatures(merged.singlets, selection.method = "vst", nfeatures = 3000, verbose = FALSE)`
`merged.singlets <- ScaleData(merged.singlets,` `vars.to.regress=c("nFeature_RNA","nCount_RNA","percent.mt","percent.ribo"),`
                                `verbose = FALSE)`
`merged.singlets <- RunPCA(merged.singlets, npcs = 50)`

I applied the harmony to remove batch effect.
`harmony.obj <- RunHarmony(merged.singlets, 
                            group.by.vars = "orig.ident",
                            assay.use = "RNA",
                            #reduction = "pca", 
                            dims.use = 1:50, 
                            max_iter = 10,
                            early_stop = F,
                            #epsilon.cluster=-Inf,
                            kmeans_init_nstart=20,
                            kmeans_init_iter_max=100,
                            plot_convergence = TRUE)`

`harmony.obj <-  RunUMAP(harmony.obj, reduction = "harmony", dims = 1:50)`
`harmony.obj <-   FindNeighbors(harmony.obj, reduction = "harmony",  dims = 1:50)`
`harmony.obj <-   FindClusters(harmony.obj, resolution = 1.6, verbose = FALSE)`

I got 60 clusters. however there is overlap in the clusters, and they are not separated well. 

![image](https://github.com/satijalab/seurat/assets/32444200/4434b941-1906-420d-a89f-7c4510e99f55)
and the overlap happened when I use Azimuth package to annotate the cells.
![image](https://github.com/satijalab/seurat/assets/32444200/6e114745-5b63-41b7-964f-0477da2b47e1)

Have I done any mistake in my workflow? Is integrating samples from different public datasets cause of this?

**Comment by Gesmira** [comment]
Hi @MWRR, 
It's hard to make conclusions just by looking at the UMAP and different parameters (such as number of neighbors) can also lead to slight differences in the UMAP structure. To me, there is nothing inherently wrong with the way this looks and the clusters do appear decently well separated. I would instead look at marker genes per cell type/cluster, trying other visualizations like heatmapa, and see if the cell types look well separated there.
