### ISSUE TITLE
Problem in using sctransform in Seurat

### ISSUE THREAD

**Issue by twb2540** [satijalab/seurat#8816]
I've recently started merging 36 datasets using SCTransform and removing batch effects using harmony. 

Here's what I have been up to:

```
# Creating a list of samples
sample_list <- list(sample1, sample2, sample3, ...)

# Applying SCTransform using lapply
sample_list <- lapply(sample_list, function(seurat_obj) {
  seurat_obj <- SCTransform(seurat_obj, vars.to.regress = "percent.mt", verbose = FALSE)
  return(seurat_obj)
})

gastric_merge <- merge(sample1, y = c(sample2, sample3, sample4, sample5, 
sample6, sample7, sample8, sample9, sample10, 
sample11, sample12, sample13, sample14, sample15,	
sample16, sample17, sample18, sample21, sample22, 
sample23, sample24, sample25, sample26, sample27, 
sample28, sample29, sample30, sample31, sample32, 
sample33, sample34, sample35, sample36, sample39, sample40), merge.data = TRUE)

# Selecting integration features
gc.features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures = 5000)
VariableFeatures(gastric_merge) <- gc.features

# Running PCA, Harmony, UMAP, and clustering
gastric_merge <- RunPCA(object = gastric_merge, assay = "SCT", npcs = 50)
gastric_merge <- RunHarmony(object = gastric_merge, assay.use = "SCT", reduction = "pca", dims.use = 1:30, group.by.vars = "patient_id", plot_convergence = TRUE)
gastric_merge <- RunUMAP(object = gastric_merge, assay = "SCT", reduction = "harmony", dims = 1:30)
gastric_merge <- FindNeighbors(object = gastric_merge, assay = "SCT", reduction = "harmony", dims = 1:30)
gastric_merge <- FindClusters(object = gastric_merge, resolution = 0.4)
```

However, a few points remain unclear to me:

(1) Regarding visualization with the `DoHeatmap` function, I've noticed that it uses data from the `scale.data` slot, which only contains **variable genes**. However, not all of the genes on my list are included in the variable genes. As a result, these genes are missing from my heatmap. 

Would it be appropriate to rescale the `SCT` assay data (using the `ScaleData` function) before using the `DoHeatmap` function to include these non-variable genes in the heatmap?

(2) Although I specified 5000 genes as integration features, 
```
gc.features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures = 5000)
```
the integration object finally contains `scale.data` with 5135 genes, which does not match the `var.feature` count that I had specified. 

![1](https://github.com/satijalab/seurat/assets/167952095/672a23a2-93cd-4506-a86f-3226eefa51bc)

Could someone please clarify if there is an error on my part or if there's a misunderstanding?

(3) For additional analysis, such as running the `AverageExpression` function and conducting differential expression analysis with the `FindMarkers` function, should I specify the assay as `RNA` or `SCT`? Additionally, which `slot data` should I use for these functions?

Thank you,
BJ

**Comment by igrabski** [comment]
Hi BJ, to answer your questions:

(1) To address this, when running `SCTransform`, you can set `return.only.var.genes = F`, so that you can also compute Pearson residuals for genes beyond the variable features.

(2) We will investigate this behavior!

(3) To clarify, if you are wanting to run pseudobulk-based DE via `AggregateExpression` followed by `FindMarkers`, you should be using the `counts` slot and set the test in `FindMarkers` to `DESeq2`.

**Comment by maithermbarros** [comment]
I am analysing similar data and when trying to perform number 3 without success. @igrabski  when you say that "_**you should be using the counts slot**"_ are you referring to `AggregateExpression` or `FindMarkers`? I thought aggregateexpression had to be run on log normalized data, therfore I chose the `"data"` slot within my integrated `"SCT" `assay

This is what I have been trying to run, without success:

```
### Aggregate expression data by both sample type and cluster annotations
w_aggregated <- AggregateExpression(
  w, 
  assay = "SCT", 
  slot = "data", # data slot has log normalized data 
  group.by = c("sample.origin.detail", "wsnn_res.1"), 
  return.seurat = TRUE)

### recreate metadata bc it gets lost for some reason
w_aggregated$sample.origin.detail <- sapply(strsplit(Cells(w_aggregated), "_"), function(x) paste(x[1:2], collapse = "_"))
w_aggregated$seurat_clusters <- sapply(strsplit(Cells(w_aggregated), "_"), `[`, 4)
w_aggregated$sample.origin2 <- w_aggregated$sample.origin.detail
w_aggregated@meta.data <- w_aggregated@meta.data%>%
  mutate(sample.origin3 = case_when(
  sample.origin2 %in% c("Healthy_Male-1", "Healthy_Male-1", "Healthy_Male-3", "Healthy_Female-1", "Healthy_Female-2","Healthy_Female-3") ~ "Healthy",
  TRUE ~ sample.origin2
))

### Perform DE analysis across all groups
Idents(w_aggregated) <- "sample.origin2"

pseudobulk_WNN_markers <- FindAllMarkers(
  object = w_aggregated, 
  assay = "SCT", 
  slot = "data", 
  only.pos = FALSE, # Only return positive markers
  test.use = "DESeq2",
  min.pct = 0.1, 
  logfc.threshold = 0.25)

```
Then I get this error (even when trying to compare just clusters and setting Idents to "seurat_clusters" before running FindAllMarkers.
`Warning: When testing 20 versus all:
	some values in assay are not integers`

Any suggestions?

**Comment by igrabski** [comment]
Hi, you should be using `counts` for both `AggregateExpression` and `FindAllMarkers` if you plan to use the `DESeq2` workflow, since `DESeq2` operates on the level of counts (note that for `AggregateExpression`, this will pseudobulk the samples by counts, as is recommended by `DESeq2`). This should resolve the error you are finding, but please let me know if you are still encountering issues.
