### ISSUE TITLE
Issue with Pseudobulk using multiome v5 seurat object

### ISSUE THREAD

**Issue by leecon30** [satijalab/seurat#8821]
Hi Ive been running through your vignette for pseudobulking analysis (https://satijalab.org/seurat/articles/de_vignette.html) but i am encountering a strange problem. 

Firstly i have no problem comparing expression at the single cell level between replicates and treatment so my metadata columns are fine in that regard. The problem arrises when i apply aggregateExpression. I am able to aggregate the reads with the desired result using this code in your vignette - 

# pseudobulk the counts based on donor-condition-celltype
pseudo_ifnb <- AggregateExpression(ifnb, assays = "RNA", return.seurat = T, group.by = c("stim", "donor_id", "seurat_annotations"))

# each 'cell' is a donor-condition-celltype pseudobulk profile
tail(Cells(pseudo_ifnb))

The issue arises following the next step in your protocol 

pseudo_ifnb$celltype.stim <- paste(pseudo_ifnb$seurat_annotations, pseudo_ifnb$stim, sep = "_")

and the return error 
- Error in `x[[i, drop = TRUE]]`:
! ‘seurat_annotations’ not found in this Seurat object
 
When i look at the object created by the AggregateExpression function i can see it generates a v4 object that contains none of the original metadata columns in my object, only an orig.ident column.

So therefore the vignette command pseudo_ifnb$celltype.stim <- paste(pseudo_ifnb$seurat_annotations, pseudo_ifnb$stim, sep = "_") is not possible. 

Is this a conflict with the multiome v5 seurat object. Or has the aggregateExpression function not been updated to work with v5 objects? 

Ive been scratching my head all day, please let me know if you can think of anything. 

Cheers

```

**Comment by zskylarli** [comment]
Hi - we recently fixed this bug, so please update to the latest version of Seurat (>5.0.2) and try again. Thank you!

**Comment by leecon30** [comment]
Oh apologies i see i have v 5.0.0. ill try it now thank you
