### ISSUE TITLE
Reading in Visium-HD via Load10X_Spatial

### ISSUE THREAD

**Issue by chenebroad** [satijalab/seurat#8826]
Hi,

A colleague and I have been attempting to load recently generated 10X Visium HD data (from SpaceRanger v3.0.0) via the Load10X_Spatial function, and we both receive an error similar to:

Error in type.convert.default(data[[i]], as.is = as.is[i], dec = dec,  :
  invalid multibyte string at '<af>5ܖ<6a>)<b2><af>	<bb><f0>-<cc><ee>1<bf><fa>5l<b2><aa>[<ed><ad>Q<b8><cf>A=|Gr풿<fc><96>t8<cb>k'

I've done a bit more troubleshooting and I've encountered a similar error even when running the example 10X data from the quick-start vignette

I don't have the full readout for the sessioninfo but we were attempting to follow the vignette: https://satijalab.org/seurat/articles/visiumhd_commands_intro#install-seurat-update

I'm fairly certain we were running the latest version of Seurat upon following the vignette, but wanted to check in and see if there's something we can do to load and analyze the data. 

Edit: (My RStudio is being a bit wonky but here is the full error message):

> local.dir <- "/Users/chene/Desktop/UGER_files/mouse_test/square_008um"
> object <- Load10X_Spatial(data.dir = local.dir,
+                           filename = "filtered_feature_bc_matrix.h5")
Error in type.convert.default(data[[i]], as.is = as.is[i], dec = dec,  : 
  invalid multibyte string at '<af>5ܖ<6a>)<b2><af>	<bb><f0>-<cc><ee>1<bf><fa>5l<b2><aa>[<ed><ad>Q<b8><cf>A=|Gr풿<fc><96>t8<cb>k'
In addition: Warning messages:
1: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 1 appears to contain embedded nulls
2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 2 appears to contain embedded nulls
3: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 3 appears to contain embedded nulls
4: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 4 appears to contain embedded nulls
5: In read.table(file = file, header = header, sep = sep, quote = quote,  :
  line 5 appears to contain embedded nulls
6: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
7: In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  embedded nul(s) found in input

**Comment by chenebroad** [comment]
A fresh install of R and above packages fixed my load in issue.

**Comment by n00blet4656** [comment]
I am still running into this issue on R 4.4.1, even following the installation instructions. Are you experiencing this at all now? Thanks

**Comment by tingchiafelix** [comment]
Hi, I also had this issue loading the 10X Visium HD data using R version 4.3.3 and Seurat 5.0.1. Any suggestion?
