### ISSUE TITLE
non-zero exit

### ISSUE THREAD

**Issue by drchubos** [satijalab/seurat#8827]
Subject: Inquiry Regarding Installation Issue

Dear Seurat Package Maintainers,

I hope this email finds you well. I am writing to seek assistance regarding an issue I encountered while attempting to install the Seurat package.

Upon executing the command `remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE)`, I encountered the following warning messages:

```
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: fs      (1.6.3 -> 1.6.4) [CRAN]
5: ggplot2 (3.5.0 -> 3.5.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
Installing 2 packages: fs, ggplot2
警告： 正在使用 ‘ggplot2’ 這個程式套件，因此不會被安裝

  有二進位版本的，但原始碼版本是後來的:
   binary source needs_compilation
fs  1.6.3  1.6.4              TRUE

安裝原始碼套件 ‘fs’

警告訊息：
1: 於 i.p(...)： 安裝程式套件 ‘fs’ 時退離狀態的值不是 0
2: 於 i.p(...)：
  安裝程式套件 ‘C:/Users/user/AppData/Local/Temp/RtmpIpbSMM/file1e4823d17b9c/Seurat_5.0.0.tar.gz’ 時退離狀態的值不是 0
```

I have attempted several solutions to address this issue but have been unsuccessful thus far. I am reaching out to inquire if there are any alternative methods or possible solutions available to resolve this matter. For your reference, my operating system is Windows 10 and I am using R version 4.4.

Thank you very much for your time and assistance. I look forward to hearing back from you soon.

Warm regards,

**Comment by igrabski** [comment]
Hi, I would recommend that you instead install `Seurat` from CRAN, which has the most up-to-date version -- you can do this using `install.packages("Seurat")`.
