### ISSUE TITLE
How to integrate-remove batch effects and assign cells

### ISSUE THREAD

**Issue by francescopatane96** [satijalab/seurat#8829]
Hi! From my kwnoledge, integrateLayers works on a low dim representation, so it does not modify counts or data. If I want to integrate and assign cells (many tools operate on raw counts) what is the best strategy for doing so? Thank you

**Comment by mhkowalski** [comment]
Do you mean tools that provide annotation predictions, like our [Azimuth](https://azimuth.hubmapconsortium.org/) tool? I would recommend performing prediction separately for each "batch", rather than trying to used the corrected counts.

**Comment by francescopatane96** [comment]
Thank you for the reply and for the valuable suggestion. In doing so, does azimuth perform an integration step? How can i align my samples? I feel confused

**Comment by longmanz** [comment]
Hi @francescopatane96 ,

Thanks for your question! Azimuth does not perform integration step and if you need a integrated object, please follow our vignette (https://satijalab.org/seurat/articles/integration_introduction) to do so, after you have run Azimuth separately for each of your batch. 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
