### ISSUE TITLE
addModuleScore error and general errors

### ISSUE THREAD

**Issue by jimena2** [satijalab/seurat#8830]
I would like to addModuleScore to my R object.
If I use my default assay of integrated, then I get errors that my features are not present in my object

If I switch to RNA assay as my default, I get the following error:
`Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Run `rlang::last_trace()` to see where the error occurred.`

I've tried the function on another R object and it works, however I cannot get it to work with my current object and am unsure why.

It works for this one:
<img width="495" alt="Screenshot 2024-04-27 at 11 27 07 PM" src="https://github.com/satijalab/seurat/assets/35901414/6112df79-f124-499f-b23f-e577aba007d8">
does not work for this one:
<img width="800" alt="Screenshot 2024-04-27 at 11 27 44 PM" src="https://github.com/satijalab/seurat/assets/35901414/0b42cef1-1dfb-4324-aad1-f432e82d9ae4">

I also am not sure why I have layers present like "scale.data.mock2.1" in my monkeypox.integrated object, this becomes an error when I attempt to access the data at:
rownames(monkeypox.integrated@assays$RNA$counts)
where it makes me pick either counts.mock2.1 or counts.mkpx2.2, but am unsure which one to use in the context of calculating DEGs and running string DB. How do you know when to use which?

**Comment by longmanz** [comment]
Hi, 
After integration please consider JoinLayers() to merge all your subsets together and then run LayerData() to access your count data or normalized data. Please also make sure you are using Seurat v5 and follow the corresponding correct vignette (https://satijalab.org/seurat/articles/integration_introduction). GetAssayData() is deprecated in Seurat v5. 

In addition, please do **not** use integrated assay to perform any downstream analysis. And note that the integrated assay no longer presents in Seurat v5.
