### ISSUE TITLE
gene not found in features although in reference

### ISSUE THREAD

**Issue by jimena2** [satijalab/seurat#8835]
If a gene that I have in my custom reference does not appear in the filtered nor raw feature_bc_matrix, does this mean that the gene was not found to align at all? Or should it still appear even if it did not align?

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Unfortunately, this is question for 10X/Cell Ranger support.  If the gene is truly in the gtf for the custom reference and in the fasta then it should be present in output h5 files regardless of whether any reads aligned.  If it’s not there it’s likely something went wrong during reference creation or alignment.

Best,
Sam
