### ISSUE TITLE
Using Seurat SCTransform with Kallisto TCC Matrix

### ISSUE THREAD

**Issue by Rajesh-HKU** [satijalab/seurat#8836]
Dear team,

I have generated transcript-compatibility-count matrices using Kallisto bus tools from single cell data. I have two questions:

1. Can I use Seurat SCTransform to normalize the count data similar to how I would used it for gene counts? What would be the best practice in this regard?
2. If I wanted to find the ratio of the expression of  two genes at each cell level , can I directly use the ratio of the corresponding Pearson Residuals or would you only recommend using the "data" layer? 
3. In my data set, the "data" layer significantly zero-inflated even after SCTransform of the TCC matrix while the "scale.data" layer has variable values. How do I interpret this (if at all)?

Thanks.

Best regards,
Rajesh

**Comment by longmanz** [comment]
Hi @Rajesh-HKU,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
