### ISSUE TITLE
Ensembl ID conversion to gene ID 

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#8838]
I converted a SCE object to seurat but all the genes are ensembl ID. How do i properly convert it to gene ID?

**Comment by samuel-marsh** [comment]
Hi,

You can see `Azimuth:::ConvertEnsembleToSymbol` or check out bioMart package directly.  I would also check the SCE object because it may have gene symbols in the object meta data and you could swap them before converting to Seurat.

Best,
Sam

**Comment by chrkuo** [comment]
> Hi,
> 
> 
> 
> You can see `Azimuth:::ConvertEnsembleToSymbol` or check out bioMart package directly.  I would also check the SCE object because it may have gene symbols in the object meta data and you could swap them before converting to Seurat.
> 
> 
> 
> Best,
> 
> Sam

Thanks Sam 

If they're in the object how would i swap them in the meta data before converting?

**Comment by samuel-marsh** [comment]
To ensure everything works properly in your object I'd recommend extracting data and creating new object.  Adding back in any other meta data, dimreducs, graphs, etc from the original.
