### ISSUE TITLE
Export Seurat Object in 10X format

### ISSUE THREAD

**Issue by robertamezquita** [satijalab/seurat#884]
It might be nice to have a method for exporting a seurat object into 10X format (genes.tsv, barcode.tsv, matrix.mtx) so that Seurat can be used for some of the upstream procedures (normalization, variable feature selection, etc) and paired with downstream tools that operate outside of Seurat, such as scanpy and such. Would also be ideal to be able to split outputs based on `orig.ident` so that multiple 10X style folders can be created, one per unique `orig.ident`. 

Also would be handy for helping collaborators get their hands on a Loupe Cell Browser file (makes running the cellranger pipeline easier to generate the Loupe file from the 10X outputs, and would be great to have the same data used across both Loupe and in R analyses). Alternately, maybe its possible to take some of 10X's code and make a Loupe compatible file for exploratory analysis using Seurat processed object. Might be worth investigating making this specific aspect as something totally separate. 

Thoughts?

**Comment by satijalab** [comment]
We would be thrilled if someone in the community would like to increase operability between Seurat and Loupe, though we unfortunately do not have the resources to do this ourselves. If you know of others who might be willing to help, please do let us know!

**Comment by jdime** [comment]
Using function `write10xCounts()` from `library(DropletUtils)` can be a work around. It takes your Seurat object and writes the three files you mentioned @robertamezquita.
Using `version="3"` command allows to save "features.tsv.gz" instead of genes.tsv.

**Comment by robertamezquita** [comment]
Thanks @jdime !

**Comment by grimwoo** [comment]
> Using function `write10xCounts()` from `library(DropletUtils)` can be a work around. It takes your Seurat object and writes the three files you mentioned @robertamezquita.
> Using `version="3"` command allows to save "features.tsv.gz" instead of genes.tsv.

When I perform the code, _**write10xCounts(x = seurat.object, path = output.path)**_,  it gave the error, 
_Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘writeMM’ for signature ‘"Seurat"’._
Did I used the wrong code?

**Comment by Jon-bioinfo** [comment]
I found this to work with `write10xCounts(x = seurat.object@assays$RNA@counts, path = output.path)`
Since it expects a sparse matrix.

**Comment by grimwoo** [comment]
> I found this to work with `write10xCounts(x = seurat.object@assays$RNA@counts, path = output.path)`
> Since it expects a sparse matrix.

Thanks, but I found the method you provide cannot preserve the other infomation, like the "Celltype", "Clinical Info" ... in seurat object. Do you know any other way to do so?

**Comment by Jon-bioinfo** [comment]
'10x format' does not contain that information, it's just the three files specifying the gene by cell matrix.

But that information would probably be in the meta.data slot, so something like `write.csv(seurat.object@meta.data, 'metadata.csv')` should work.

**Comment by grimwoo** [comment]
> '10x format' does not contain that information, it's just the three files specifying the gene by cell matrix.
> 
> But that information would probably be in the meta.data slot, so something like `write.csv(seurat.object@meta.data, 'metadata.csv')` should work.

Thanks!

**Comment by massonix** [comment]
> Using function `write10xCounts()` from `library(DropletUtils)` can be a work around. It takes your Seurat object and writes the three files you mentioned @robertamezquita.
> Using `version="3"` command allows to save "features.tsv.gz" instead of genes.tsv.

Hi @jdime,

Do you know if it is possible to convert the output from write10xCounts() to a .cloupe file for exploration with the Loupe Browser?

Thanks,

Ramon

**Comment by jdime** [comment]
The .cloupe file has more information than just the read counts. It has coordinates for the tSNE/UMAP, cell clusters and differential gene expression. Whereas the write10xCounts() outputs only the read counts. Then, I don't think that you can do that @massonix. Alternatively, you could use a webapp to re-cluster cell and visualize cells similar to what you'd get in *cloupe. I've used these online options: [CReSCENT](https://crescent.cloud/) and [alona](https://alona.panglaodb.se/). Or Seurat itself has some [interactive plotting features](https://satijalab.org/seurat/v3.2/visualization_vignette.html).

**Comment by t-and** [comment]
Hi @jdime, thank you for suggesting this option for exporting from Seurat! For some reason when I run write10xCounts() from DropletUtils, I get an error stating that R cannot rename a file with a random string as its name to the original path file name. (e.g. "cannot rename file 'D:/outs for cds\file34042aec5614' to 'D:/outs for cds/merge/', reason 'Access is denied'") Do you have any idea how to fix this? 

Thanks so much!

**Comment by jdime** [comment]
Are you providing parameter `path` to write10xCounts(..., path = "path_to/out_directory") @t-and ?
Do you have access permissions to the parent directory where you are trying to save the MTX files?
Can you copy/paste the exact command that you are passing to write10xCounts?

**Comment by t-and** [comment]
Exact code is below! I am specifying a path that I know R can write files in. 

`write10xCounts(x = MI.gex.it3@assays$RNA@counts, path = "D:/outs for cds/merge/")`

**Comment by jdime** [comment]
That looks fine to me. Probably someone at the DropletUtils repo can help @t-and .

**Comment by jdime** [comment]
@maximilianh -- see @Jon-bioinfo response above on a sparse matrix in case you are still interested

**Comment by Celine-075** [comment]
Im now trying to write to 10x using 
```write10xCounts(x = filtered_seurat@assays$RNA@counts, path = "E:/scIntegrate_py/.spyproject/Grubman_preprocessed")```

But that wont work for me because i dont have 1 layer with counts, but 6 layers with counts because i've merged my samples (counts.1, counts.2 etc.). How can i write this merged set to 10x format?

**Comment by dkcoxie** [comment]
FYI - 10x released [`loupeR`](https://www.10xgenomics.com/support/software/loupe-browser/latest/tutorials/introduction/lb-louper), to generate a LoupeBrowser compatible .cloupe output from a Seurat object. As @jdime mention, this does require UMAP/TSNE to be run and clustering to have been performed prior to trying to export to .cloupe.

Note: currently only supports outputs for single-cell, not spatial
