### ISSUE TITLE
Subsetting and merging back Seurat Object brings different results

### ISSUE THREAD

**Issue by LeaLe88** [satijalab/seurat#8845]
Good morning,

I wonder if anyone can answer this question: If I  subset my Seurat object into celltype A and celltype B and then I merge it back together  I see some differences in the counts@p. Why is this the case?

Please find below some pictures attached for illustration:

Before subsetting:
![image](https://github.com/satijalab/seurat/assets/71077063/9bf44730-03cf-407e-83fd-d885a92ce45f)

After subsetting into celltypes A (Macrophages) and Celltype B (all other cells):

Celltype A (Macrophages) :

![image](https://github.com/satijalab/seurat/assets/71077063/6d068c15-ad9e-4a74-8fb8-a1124a9e8a12)

Celltype B (all other cells):

![image](https://github.com/satijalab/seurat/assets/71077063/dca81644-b5ba-4d4c-b295-afe84293406d)

Newly merged object:

![image](https://github.com/satijalab/seurat/assets/71077063/5bb3e6e1-2ef5-4316-b7ec-e54e17ef17eb)

The UMAP cluster seem to look as before however in slightly different positions.

However, comparing the counts I can see a difference: 

Before:
![image](https://github.com/satijalab/seurat/assets/71077063/0097250c-8582-460d-aaa9-517f9026b6fa)

After:
![image](https://github.com/satijalab/seurat/assets/71077063/74a68a6b-c7ce-4b27-99c7-ad138c0174d5)

I had to re-run FindVariableFeatures, ScaleData, RunPCA, FindNeighbors, FindClusters and RunUMAP in the newly merged object since all reductions, commands were gone. However, I repeated the commands exactly in the way as before.

Any idea what is causing this difference?
Thank you for any hint!

**Comment by LeaLe88** [comment]
Ok I think I know what happened. The order of cells changed, otherwise its the same:

![image](https://github.com/satijalab/seurat/assets/71077063/44ae1d99-ab39-4127-8f39-59a77c6d47e8)

**Comment by zskylarli** [comment]
Hi - yes, it's expected that the order of the cells will change after merging! Will close this issue but if something else comes up, feel free to reopen.
