### ISSUE TITLE
All cells in images must be present in the Seurat object(Xenium data)[subset with Xenium error]

### ISSUE THREAD

**Issue by ilovegreentea** [satijalab/seurat#8848]
After using subset() function to remove some cells, "**All cells in images must be present in the Seurat object**"  Error is occured.
I use 16 samples of TMA, merged all of the samples and add image information of each samples.
Error occured when i use PrepSCTFIndMarkers function to use FindallMarkers function.
Seurat_object <- PrepSCTFindMarkers(Seurat_object)

but there are no removed cells in my Image(in Seurat_object@images).

is there any problem to use subset() function with Xenium data? 
or if there is any tips to subset some cell then give me any advice.

**Comment by zskylarli** [comment]
This error is probably from subsetting on cells that are not in some of the images in the object, and should be fixed with our newest CRAN release! Please reinstall and try subsetting again.

**Comment by alikhuseynov** [comment]
`subset` is from `SeuratObject`, using version `5.0.2` seems to work but it gives warnings, any idea why?
```
Warning messages:
1: Not validating FOV objects 
2: Not validating Centroids objects 
3: Not validating Centroids objects 
4: Not validating FOV objects 
5: Not validating Centroids objects 
6: Not validating FOV objects 
7: Not validating FOV objects 
8: Not validating FOV objects 
9: Not validating Seurat objects 
10: Not validating Seurat objects 
```

**Comment by ilovegreentea** [comment]
hey, I used subset_opt function 
[](https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat.R)

**Comment by alikhuseynov** [comment]
> hey, I used subset_opt function https://github.com/alikhuseynov/add-on_R/blob/develop/R/subset_obj_seurat.R

sounds good, but FYI check this thread: 
https://github.com/satijalab/seurat/issues/7462#issuecomment-2118080666
you should be able to subset with `SeuratObject` version `5.0.2`

**Comment by ilovegreentea** [comment]
Wow.. I missed this issue,
I got same message in SeuratObject(5.0.2)

**Comment by alikhuseynov** [comment]
> Wow.. I missed this issue,
> 
> I got same message in SeuratObject(5.0.2)
> 
> 
> 
> but cells are successfully removed in image data..
> 
> I don't know meaning of the message 

The warning messages can be ignored.
