### ISSUE TITLE
ScaleData before of after FindIntegrationAnchors

### ISSUE THREAD

**Issue by yinshiyi** [satijalab/seurat#8849]
My coworkers are having a debate regarding when to run ScaleData, I thought to seek some guidance from the developer or other experts.

In the original V3 [link](https://satijalab.org/seurat/archive/v3.1/integration.html). ScaleData is run _after_ IntegratData and _before_ RunPCA and RunUMAP
```
.....
NormalizeData
FindVariableFeatures
# NO SCALEDATA here
pancreas.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
pancreas.integrated <- IntegrateData(anchorset = pancreas.anchors, dims = 1:30)
DefaultAssay(pancreas.integrated) <- "integrated"
# Run the standard workflow for visualization and clustering
pancreas.integrated <- ScaleData(pancreas.integrated, verbose = FALSE)
pancreas.integrated <- RunPCA(pancreas.integrated, npcs = 30, verbose = FALSE)
pancreas.integrated <- RunUMAP(pancreas.integrated, reduction = "pca", dims = 1:30)
```

In the V5 or V4, 
* IntegrateLayers = select feature + find anchor + run integration 
   * #8653 

In 2 seperate documentations, I see ScaleData being run _before_ IntegrateLayers
1. https://satijalab.org/seurat/articles/integration_introduction.html
2. https://satijalab.org/seurat/articles/seurat5_integration
```
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)

obj <- IntegrateLayers(
  object = obj, method = CCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.cca",
  verbose = FALSE
)
```

**Question: ScaleData before of after FindIntegrationAnchors? 
and why V3 and V5 are different?**

My guess: ScaleData is needed anytime before RunPCA, since V5 using "low-dimensional space rather than on gene expression levels", so RunPCA is needed to generate that Low-dimension first in V5, aka before Integration; whereas in V3, integration is run on higher dimension directly, so RunPCA is only needed for RunUMAP, which is after integration, so ScaleData is run after integration.

---------------------------
Additional notes:
* single command SCTransform replaces NormalizeData, FindVariableFeatures and ScaleData
   * [link](https://htmlpreview.github.io/?https://github.com/satijalab/sctransform/blob/supp_html/supplement/seurat.html)
* #1166

**Comment by longmanz** [comment]
Hi @yinshiyi ,

ScaleData is mostly run before RunPCA (in v4/5). 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
