### ISSUE TITLE
How to retrieve elements after using SplitObject()

### ISSUE THREAD

**Issue by Hofphi** [satijalab/seurat#885]
Hey,

I am currently working with a SeuratObject from one of our collaborators. This Object is a merged SeuratObject from seven different replicates. I want to unmerge/split the Object into each replicate so I can cluster them together in order to identify any batch effects between replicates.

I used the SplitObject() function which worked create for me! I am now struggling to extract the individual elements (replicates) from the splitted Object (obj.list):

> obj.list <- SplitObject(object=seurat_object, attribute.1 = "Replicate")
 
The obj.list has the typicall structure as the SeuratObject: 

> obj.list    Large list (7 elements
> r1:Formal class 'seurat'  [package "Seurat'} with 20 slots
> .. ..@ raw.data:Formal class 'dgCMatrix' [package "Matrix'] with 6 slots
> .. .. .. ..... and so on

How do I retrieve the individual elements/replicates from this obj.list? 

I checked the SubsetData() function but could not find a suitable parameter to extract these elements.

**Comment by leonfodoulian** [comment]
Hi,

Simply access to each object using the `$` sign. E.g. `obj.list$Replicate1` should give you the first object, etc.

Best,
Leon

**Comment by Hofphi** [comment]
Hey @leonfodoulian 

that was a simple solution. I was thinking to complicated, haven't tried this standard function.

Thanks!
