### ISSUE TITLE
Getting Multiple Genes on a single RidgePlot?

### ISSUE THREAD

**Issue by ariskare** [satijalab/seurat#8850]
I'm trying to plot several genes of interest in a single plot for my entire SeuratObject rather than having each gene as it's own column/plot. Is there a way to do this using RidgePlot()?

**Comment by igrabski** [comment]
RidgePlot will separate genes into different columns/plots, but you could try `DoHeatmap()` or `DotPlot()` -- if neither of those works for what you have in mind, you may need to create your own custom plots (for example, you could use the package `ggridges` to make a ridge plot with multiple genes).
