### ISSUE TITLE
After performing FindIntegrationAnchors, I generated an integrated assay, but my RNA assay data was deleted.

### ISSUE THREAD

**Issue by yaoli00** [satijalab/seurat#8852]
After performing FindIntegrationAnchors, I generated an integrated assay, but my RNA assay data was deleted Is there any mistake here?
Here is the code and the result.

`SLE_anchors <- FindIntegrationAnchors(object.list = list(CT1_seurat, CT3_seurat,OLD1_seurat,OLD2_seurat,SLE1_seurat, 
                                                             SLE2_seurat), 
                                          dims = 1:50,
                                          anchor.features = 3500)

save(SLE_anchors, file = "SLE_anchors.Rda")
SLE_PBMC <- IntegrateData(anchorset = SLE_anchors, dims = 1:50)

save(SLE_PBMC, file = "SLE_PBMC_integrated_data.Rda")`

An object of class Seurat 
22410 features across 34005 samples within 2 assays 
Active assay: integrated (3500 features, 3500 variable features)
 1 layer present: data
 1 other assay present: RNA

<img width="485" alt="屏幕截图 2024-05-03 123538" src="https://github.com/satijalab/seurat/assets/150777784/62d2b47f-ccda-4cbe-a780-696b04394e21">
"

**Comment by Gesmira** [comment]
Hi, 
I'm having trouble understanding what you mean. It appears that the `data` in the RNA assay is still there. Are you referring to the `scale.data`?

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if you continue to run into issues.
