### ISSUE TITLE
Error in CreateSeuratObject

### ISSUE THREAD

**Issue by scas224** [satijalab/seurat#8855]
I am trying to perform Seurat analysis on single cell data from NCBI GEO, and I have converted the data into a dataframe with genes as the rows and cells as the columns, and I have converted that dataframe to a matrix, but when I try to create a Seurat object I get this error:

Seurat <- CreateSeuratObject(counts = merged_matrix, , project = 'GSE129788', min.cells = 3, min.features = 200)
Warning: Data is of class matrix. Coercing to dgCMatrix.
Error in validObject(.Object) : 
  invalid class “LogMap” object: Rownames must be supplied

However, I do have both row names and column names

I saw that other people have had similar errors, and I followed some of those suggestions such as re-installing SeuratObject and Seurat and installing an older version of Matrix, but none of that worked. Any other ideas to fix this?

**Comment by igrabski** [comment]
Hi, can you show the output of `sessionInfo()` when you receive this error?

**Comment by longmanz** [comment]
Hi @scas224,

Thanks for using Seurat! Please let us know if you still have this issue after updating the Matrix and Seurat to the latest version. Please feel free to re-open the thread if the issue persists!
