### ISSUE TITLE
How to access Seurat metadata column as a changing variable?

### ISSUE THREAD

**Issue by Yijia-Jiang** [satijalab/seurat#8856]
Hi, I am trying to run scRNA-scATAC integration. For the label transfer function, is there a way for me to access seurat metadata columns as a variable? For the example, the current line of my code is below:

celltype.predictions <- TransferData(anchorset = transfer.anchors, refdata = rna$assign.ident.breast,
                                       weight.reduction = atac[["lsi"]], dims = 2:30)

I want to change this line into something like this:

var_col = assign.ident.breast
celltype.predictions <- TransferData(anchorset = transfer.anchors, refdata = rna@meta.data[var_col],
                                       weight.reduction = atac[["lsi"]], dims = 2:30)

However, I met the following error: Error: None of the provided refdata elements are valid.
In addition: Warning message:
In ValidateParams_TransferData(anchorset = anchorset, combined.ob = combined.ob,  :
  Please provide either a vector (character or factor) for label transfer or a matrix for feature transfer. 
Type provided: data.frame

Could you let me know if there is an easy way to do this? Thank you very much.

**Comment by Gesmira** [comment]
Hi, 
You can do this by putting the variable in double brackets: `rna@meta.data[[var_col]]`
