### ISSUE TITLE
subset() function does not respect the order of indices

### ISSUE THREAD

**Issue by dolchan** [satijalab/seurat#8857]
### Discussed in https://github.com/satijalab/seurat/discussions/8851

<div type='discussions-op-text'>

<sup>Originally posted by **dolchan** May  2, 2024</sup>
subset() function does not seem to respect the order of indices.  For example, spe[c(2,1), ] will return the same result as subset[c(1,2), ].  The same goes with spe[, 1:2] and spe[, c(2,1)].  I am not sure if this is by design or a bug, but it is not intuitive and is not consistent with what's expected.  When I tested it with SingleCellExperiment, sce[1:2, ] is different from sce[c(2,1), ].  This means there is no efficient way of permuting rows (genes) or columns (cells) in Seurat object.</div>

**Comment by dcollins15** [comment]
@dolchan we're appreciative of the feedback 🙏 

This current behavior is intended—for simplicity, Seurat avoids re-ordering its underlying counts matrices. I can see, though, why this functionality would be nice to have. We'll keep this request in mind for future iterations 😃
