### ISSUE TITLE
very urgent an error in seurat

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#886]

**Comment by satijalab** [comment]
Dear 2236529177 ,

Thank you again for your interest in Seurat and in engaging our user community.

We recently asked you #868 that you consider your GitHub issues more carefully before posting. In particular, we asked that you consider whether your issues represents a bug, error, or issue in the software, as we cannot provide personal interpretations of individual analyses. The issue you posted here does not represent an error with the software.

We also ask that you do not post issues repeatedly. For example, you have posted at least five issues requesting clarification on the hvg.info slot, which has been previously answered in #544 . While we understand that you wish to receive a response, repeated posting leads to our issues being dominated by a single user, and can limit interactions between the rest of the community.

You may be interested in posting future queries on https://bioinformatics.stackexchange.com/ , which has an active user base that considers many single cell analysis tools, including Seurat.

I hope you will consider these requests in the future. GitHub provides a mechanism for repository owners to limit or block interactions with individuals users if necessary. While we have never used this mechanism before, I want to clearly state our requests here, in case we choose to do so in the future.

**Comment by 2236529177** [comment]
> Dear 2236529177 ,
> 
> Thank you again for your interest in Seurat and in engaging our user community.
> 
> We recently asked you #868 that you consider your GitHub issues more carefully before posting. In particular, we asked that you consider whether your issues represents a bug, error, or issue in the software, as we cannot provide personal interpretations of individual analyses. The issue you posted here does not represent an error with the software.
> 
> We also ask that you do not post issues repeatedly. For example, you have posted at least five issues requesting clarification on the hvg.info slot, which has been previously answered in #544 . While we understand that you wish to receive a response, repeated posting leads to our issues being dominated by a single user, and can limit interactions between the rest of the community.
> 
> You may be interested in posting future queries on https://bioinformatics.stackexchange.com/ , which has an active user base that considers many single cell analysis tools, including Seurat.
> 
> I hope you will consider these requests in the future. GitHub provides a mechanism for repository owners to limit or block interactions with individuals users if necessary. While we have never used this mechanism before, I want to clearly state our requests here, in case we choose to do so in the future.

oh， so sorry, the bug I reported today is really an error, if not, I will never post any issue, thanks a lot.
