### ISSUE TITLE
An issue with running FindTransferAnchors on SCT-processed data.

### ISSUE THREAD

**Issue by minghao622** [satijalab/seurat#8867]
Hi,
I want to map the data from the query to the reference dataset, but I encountered an error when running the FindTransferAnchors step. Please help.

Here is the code I ran:
Below is the processing code for the reference data.
```R
ref[["RNA"]] <- split(ref[["RNA"]], f = ref$batch)
ref<- ref%>% 
    SCTransform(method = "glmGamPoi", vars.to.regress = c("percent.mt"), vst.flavor = "v2",verbose = FALSE) %>% 
    RunPCA(verbose = FALSE) %>% 
    RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) 
ref<- IntegrateLayers(object = ref, method = HarmonyIntegration,
                         orig.reduction = "pca", new.reduction = "harmony",
                         normalization.method = "SCT", verbose = F) %>% 
    RunUMAP(reduction = "harmony", dims = 1:30,return.model = T,
            verbose = FALSE,reduction.name = "umap.harmony") %>%
    FindNeighbors(reduction = "harmony", dims = 1:30, verbose = FALSE) %>%
    FindClusters(verbose = FALSE)
```
This section contains code for processing query data.
```R
query<- query %>% 
    SCTransform(method = "glmGamPoi", vars.to.regress = c("percent.mt"), vst.flavor = "v2",verbose = FALSE)
```
The previous steps ran smoothly, but an issue has arisen at this step.
```R
anchor  <- FindTransferAnchors(reference = ref,normalization.method = "SCT",
                               reference.reduction = "harmony",
                               query = query ,
                               k.filter = NA)
```
Error: Given reference assay (SCT) has 7 reference sct models. Please provide a reference assay with a  single reference sct model.
Traceback:

1. FindTransferAnchors(reference = ref, normalization.method = "SCT", 
 .     reference.reduction = "harmony", query = query, k.filter = NA)
2. ValidateParams_FindTransferAnchors(reference = reference, query = query, 
 .     normalization.method = normalization.method, recompute.residuals = recompute.residuals, 
 .     reference.assay = reference.assay, reference.neighbors = reference.neighbors, 
 .     query.assay = query.assay, reduction = reduction, reference.reduction = reference.reduction, 
 .     project.query = project.query, features = features, scale = scale, 
 .     npcs = npcs, l2.norm = l2.norm, dims = dims, k.anchor = k.anchor, 
 .     k.filter = k.filter, k.score = k.score, max.features = max.features, 
 .     nn.method = nn.method, n.trees = n.trees, eps = eps, approx.pca = approx.pca, 
 .     mapping.score.k = mapping.score.k, verbose = verbose)
3. stop("Given reference assay (", reference.assay, ") has ", reference.model.num, 
 .     " reference sct models. Please provide a reference assay with a ", 
 .     " single reference sct model.", call. = FALSE)

Based on the error message, I tried using JoinLayers to see if it would solve the issue, but it failed.
```R
ref[["SCT"]] <- JoinLayers(object = ref,assay = "SCT")
```
Error: Given reference assay (SCT) has 7 reference sct models. Please provide a reference assay with a  single reference sct model.

Can you tell me what modifications are needed in the code to make the FindTransferAnchors step run successfully? Thank you very much!!!

**Comment by dcollins15** [comment]
Unfortunately, if a dataset has been pre-processed with `SCTransform` and then integrated with `IntegrateData` it cannot be passed to the `reference` for `FindTransferAnchors`. For now, if you want to use an integrated dataset as a reference my recommendation would be to fall back to the v3 integration.

**Comment by minghao622** [comment]
ok,thank you for your suggestion, I will try it later.
