### ISSUE TITLE
FindAllMarkers and obj@assays$Spatial@data

### ISSUE THREAD

**Issue by mtrussart** [satijalab/seurat#8868]
Hi,

I have two questions related to the FindAllMarkers function:
1) I am trying to run the FindAllMarkers function on a Seurat object without using the normalisation provided by Seurat. As far as I have seen, the function does require to have previously run the Seurat normalisation on the seurat object beforehand to be able to run it. Is that right?
2) I would like to know if with the updated version of Seurat the previous "sobj@assays$Spatial@data" and arguments assay='Spatial', slot='data', is now replaced by "sobj@assays$Spatial@counts" with argument assay='Spatial', slot='counts' ?

Thanks a lot,
Marie

**Comment by longmanz** [comment]
Hi @mtrussart ,

Thanks for your question! V5 has a different data structure from V4 so you cannot use commands like sobj@assays$Spatial@data to access the data. Assay is deprecated in V5. 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
