### ISSUE TITLE
Issues with subsetting old Seurat objects with Seurat v5  Error in strsplit(x = colnames(Embeddings(object = value)), split = "_") :    non-character argument

### ISSUE THREAD

**Issue by AlonsoOga** [satijalab/seurat#8869]
I am trying to migrate all my integration pipeline from Seurat v4 to Seurat v5. I understand that there has been major improvements in regards to normalization. However, I have had a huge amount of issues when migrating my analysis from v4 to v5. I initially tried to use older versions of sctransform (0.3.5), SeuratObject (4.1.0) and Seurat (4.3.0), but for some reason I can't replicate the analysis that I did a year ago. I figured that it might be due to version incompatibility of dependencies with Seurat4.3.0, so I thought it would be best if I just do everything with Seurat5.0.3. 

However, previous objects that do not have any issues in Seurat4.3.0 (or even Seurat4.4.0) have issues in the new Seurat5.0.3. Subsetting the datasets becomes a nightmare. Most of my objects work fine when subsetting after doing `UpdateSeuratObject`, but some of them are just unable to update to SeuratObject v5 and this error follows: 

`Error in strsplit(x = colnames(Embeddings(object = value)), split = "_") : 
  non-character argument`

Any ideas of what can be happening here?

**Comment by Gesmira** [comment]
Hi, 
This error occurs when you run `UpdateSeuratObject`? Would you be able to include the output of printing one of the objects that this doesn't work with?

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if the issue persists.
