### ISSUE TITLE
Extract cell barcodes from FeaturePlot blend = TRUE

### ISSUE THREAD

**Issue by dy-lin** [satijalab/seurat#8871]
```
FeaturePlot(obj, features = c("adt_CD34", "adt_CD38"), blend = TRUE, combine = FALSE)[[3]]
```

For the plot above, I am interested in the cells that would be CD34+ and CD38-. In the blended plot, that is all the points that are shades of red with no green. Is there a way to extract the cell barcodes for these cells? I've tried accessing the `data` slot of the ggplot object, but that only contains the output of: 

```
Seurat:::BlendExpression(FetchData(obj, c("adt_CD34", "adt_CD38")))
```
I'd like to be able to systematically pulling out all cells that are of the red colour, rather than visualizing violin plots and picking an arbitrary threshold to draw across the violins:

```
VlnPlot(obj, features = c("adt_CD34", "adt_CD38"))
```

I've looked at `CellSelector()` but since the cells are not all in one cluster it makes selecting them individually difficult.

**Comment by samuel-marsh** [comment]
Hi,

You can do this fairly simply by just pulling the raw data and filtering the data.frame.

```
cells_of_interest <- FetchData(object = OBJ, vars = c("FEAT1", "FEAT2")) %>% 
  filter(FEAT1 > 0 & FEAT2 == 0) %>% 
  rownames()
```

Best,
Sam

**Comment by dy-lin** [comment]
Hi Sam, 

I understand I can pull out individual cells this way, but I want to specifically pull out clusters based on the FeaturePlot.

**Comment by samuel-marsh** [comment]
Hi,

Can you explain what you mean by “pull out clusters based on FeaturePlot”?

Best,
Sam

**Comment by dy-lin** [comment]
Essentially I'd like to be able to pull out something like this:
| Barcode  | Colour |
| ------------- | ------------- |
| cell_barcode  | colour_hex  |

If I pull out using the `FetchData` then it would pull out cells that express a certain feature regardless of shade or gradient. I want to be able to set a cut off on the gradient visually for expression.

I am asking if there is a way to extract the barcodes and their colours from the FeaturePlot (blend = TRUE) ggplot object, or a way to get the data frame above using a mix of internal functions such as `BlendExpression` or `BlendMatrix` or `BlendMap`. If that's not possible, then I will make do with `FetchData` 👍

**Comment by samuel-marsh** [comment]
So you can pull these things from ggplot2 object and easiest if you build it.

```
p1 <- FeaturePlot(pbmc, features = c("MS4A1", "CD3E"), blend = T)
p_build <- ggplot_build(p1[[3]])

data <- p_build$data[[1]]
barcodes <- rownames(p_build$plot$data)

rownames(data) <- barcodes
```

That said it's probably better to set thresholds based on expression values and not the binned color values that blended plots create.  Because it can be misleading as to the degree of coexpression if overall expression of one of the genes is significantly less than the other.

Best,
Sam
