### ISSUE TITLE
About FindVariableFeature selection 

### ISSUE THREAD

**Issue by kiwipeel** [satijalab/seurat#8875]
I used the default 'FindVariableFeatures' function from the Seurat package to identify variable features, but some of the genes appearing  as HVG are only expressed in 10-15 cells, and these cells are not even in a single cluster. Can we say that this is biologically informative ?

If this gene had been detected in excess specifically within a single cluster, then I would say it had some meaning. However, since the cells producing this gene are randomly distributed on the UMAP plot, I conclude it cannot have any significance, indicating that it doesn't contribute much to the clustering aspect either.

Can we impose a filter that requires a gene to be produced in at least 20 cells in order to be selected as a variable gene?

**Comment by mhkowalski** [comment]
Hi, 

I haven't personally encountered this but I do agree that these features are likely not very informative. You could remove features detected in very few cells from your Seurat object by specifying `min.cells=20` in `CreateSeuratObject()`. 

 If you don't want to remove these features entirely, I can think of a couple of other strategies.  If they are lower down on the list of `VariableFeatures`, you could try calculating a smaller set of variable features (`nfeatures = 1000`, for example) or setting your `VariableFeatures` to a subset of these features after calculating which features pass your minimum expression threshold. I hope this is helpful.
