### ISSUE TITLE
Error when loading VisiumHD using Seurat 5.1

### ISSUE THREAD

**Issue by DaiZYlab** [satijalab/seurat#8876]
> localdir <- "~/R/VisiumHD/"
> HD <- Load10X_Spatial(data.dir = localdir, bin.size = c(8, 16))
Error in parquet___arrow___ArrowReaderProperties__Make(isTRUE(use_threads)) : 
  Cannot call parquet___arrow___ArrowReaderProperties__Make(). See https://arrow.apache.org/docs/r/articles/install.html for help installing Arrow C++ libraries. 

do not know how to fix Anyone who the solution? thanks.

**Comment by patedip** [comment]
devtools::install_version('arrow', '13.0.0.1')

This fixed this issue for me. Apparently has to do with how the files are read and this issue was introduced in V14 of arrows and was never fixed in v15.
