### ISSUE TITLE
SaveH5Seurat error but  not display any information

### ISSUE THREAD

**Issue by MYDongHongJie** [satijalab/seurat#8885]
```
SaveH5Seurat(data_ob, filename = "data.h5Seurat",overwrite=TRUE)
Creating h5Seurat file for version 3.1.5.9900
Adding cell embeddings for pca
Adding loadings for pca
No projected loadings for pca
Adding standard deviations for pca
No JackStraw data for pca
Adding cell embeddings for harmony
Adding loadings for harmony
Adding projected loadings for harmony
Adding standard deviations for harmony
No JackStraw data for harmony
Adding cell embeddings for umap
No loadings for umap
No projected loadings for umap
No standard deviations for umap
No JackStraw data for umap
Adding cell embeddings for tsne
No loadings for tsne
No projected loadings for tsne
No standard deviations for tsne
No JackStraw data for tsne
Error: 
```

I use the SaveH5Seurat function, which displays an error but does not prompt any information. When I read the saved H5Seurat file, it will display "Cannot find dataset with cell names"
`data = LoadH5Seurat('scvelo_temp/temp.h5Seurat')
Validating h5Seurat file
Error: Cannot find dataset with cell names`

**Comment by longmanz** [comment]
Hi @MYDongHongJie,
Thank you for reporting this! However, please post this issue to SeuratDisk (https://github.com/mojaveazure/seurat-disk) since SaveH5Seurat() is a SeuratDisk function.
