### ISSUE TITLE
Error in methods::slot(object = object, name = "layers")[[layer]][features,  :    incorrect number of dimensions

### ISSUE THREAD

**Issue by AndreasHK1** [satijalab/seurat#8886]
I'm currently doing a spatial transcriptomics analysis and I'm trying to look at the gene expression in specific cell types in specific pathways. I made a for loop to iterate over relevant genes but it keeps giving me the same error: 
Error in methods::slot(object = object, name = "layers")[[layer]][features,  :    incorrect number of dimensions

I debugged every line in the script and everything works except for the first two lines in the my for loop. I'm still a rookie so I hope someone can help me. 

#Subsetting data
photo <- subset(ret, subset = type == "Cone" | type == "Rod")
bp<-subset(ret,type=="BP")
gabaac<-subset(ret,type=="GabaAC")
glyac<-subset(ret,type=="GlyAC")
hc<-subset(ret,type=="HC")
mg<-subset(ret,type=="MG")
rgc<-subset(ret,type=="RGC")

nrow(photo)

cell_types<-list()
cell_types[["photo"]]<-photo
cell_types[["BP"]]<-bp
cell_types[["GabaAC"]]<-gabaac
cell_types[["GlyAC"]]<-glyac
cell_types[["HC"]]<-hc
cell_types[["MG"]]<-mg
cell_types[["RGC"]]<-rgc

####### For loop #######

pathways <- list()
dge_list<-list()
cell_type_vln<-list()
cell_type_dimplot <- list()
pathways[["tca"]]<-tca.genes
pathways[["glycolysis"]]<-glycolysis.genes
pathways[["oxphos"]]<-oxphos.genes

for (i in 1:length(pathways)) {
  for (k in 1:length(cell_types)) {

    # Get the corresponding gene list
    pathway_genes <- pathways[[i]]
    cell_type_genes <- cell_types[[k]]
  
    intersected_genes <- intersect(rownames(cell_type_genes), toupper(pathway_genes))
  
    #Normalize data
    cell_dim <- NormalizeData(object = cell_type_genes, assay = "Spatial")
  
    #Dimensionality reduction
    cell_dim <- FindVariableFeatures(object = cell_dim, assay = "Spatial", nfeatures = 5000)
    cell_dim <- ScaleData(object = cell_dim, assay = "Spatial")
    cell_dim <- RunPCA(object = cell_dim, assay = "Spatial", verbose = FALSE)
    cell_dim <- FindNeighbors(object = cell_dim, dims = 1:30, assay = "Spatial")
    cell_dim <- FindClusters(object = cell_dim, verbose = FALSE)
    cell_dim <- RunUMAP(object = cell_dim, dims = 1:30, assay = "Spatial")
    # Visualize UMAP plot
    cell_type_dimplot[[names(pathways)[i]]] <- DimPlot(object = cell_dim, reduction = "umap", group.by = c("seurat_clusters", "orig.ident", "treatment"))
 
  }
}

**Comment by Baozi9** [comment]
hello  i just come with the same problem ,have U solve it ? I  try a lots of methods, but it doesnt work
