### ISSUE TITLE
Negative expression after integration in RNA Assay

### ISSUE THREAD

**Issue by AAA-3** [satijalab/seurat#8888]
Integrated, used RNA assay, joined layers, 

```
H9[["RNA"]] <- JoinLayers(H9[["RNA"]])
DefaultAssay(object = H9) <- "RNA"
H9 <- NormalizeData(H9) %>% FindVariableFeatures() %>% ScaleData(features = rownames(H9), vars.to.regress = c("percent.mt", "CC.Difference"), scale.max = 100, block.size = 2000) %>% RunPCA(npcs = 100) 
DotPlot(H9, features = c("ARL13B", "TTR", "AQP1"))
```
![image](https://github.com/satijalab/seurat/assets/68068335/4f9eb655-b363-4e64-8f30-a6377f52cca3)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The default for DotPlot is to use scaled expression data.  Therefore negative numbers are not negative expression.

Best,
Sam
