### ISSUE TITLE
Workflow question for multiple treatments with replicates

### ISSUE THREAD

**Issue by shanzhong** [satijalab/seurat#889]
Hi, I have a question regarding the recommended Seurat analysis workflow when there are multiple treatments as well as biological replicates for each treatment. Say I have treatments A, B and C, each with two biological replicates (1 and 2). Which of the following workflows (simplified to the essence) should I follow, or any alternatives if neither is the most appropriate? And could you explain more about the rationales for the recommendation?  Thanks!

Option 1:
```
all.data <- list()
for each treatment X in (A,B,C) {
    X.rep1 <- CreateSeuratObject(...)
    X.rep2 <- CreateSeuratObject(...) 
    #add replicate ID (as levels) to meta.data of X.rep1 and X.rep2
    this.data <- mergeSeurat(X.rep1, X.rep2)
    this.data <- NormalizeData(...)
    # remove batch effect between rep1 and 2 below
    this.data <- ScaleData(..., vars.to.regress=c(..., rep.id)) 
    all.data[[X]] <- this.data
}
genes.use <- ... #find variable genes in at least 2 treatments
combined.data <- RunMultiCCA(all.data, genes.use=genes.use, ...)
combined.data <- AlignSubspace(...)
```

Option 2:
```
all.data <- list()
for each sample Y in (A.1, A.2, B.1, B.2, C.1, C.2) {
    this.data <- CreateSeuratObject(...from sample Y...)
    this.data <- NormalizeData(this.data)
    this.data <- ScaleData(this.data)
    all.data[[Y]] <- this.data
}
genes.use <- ... #find variable genes in at least 2 samples
combined.data <- RunMultiCCA(all.data, genes.use=genes.use, ...)
combined.data <- AlignSubspace(combined.data,  grouping.var="treatment") # or grouping.var="sample" here??
```

**Comment by satijalab** [comment]
Thanks for the great question. This issue of nested experimental designs is something that we are thinking carefully about, so stay tuned.

But for now, my suggestion would be to use option 1 , IF this successfully removes the batch effect between replicates. If it does not, then you may need to run MultiCCA on all replicates individually.

Another way of saying this is that, if ScaleData removes technical effects in your experiment through regression -then there is no need for CCA.
