### ISSUE TITLE
Merge and JoinLayers on time-serie dataset

### ISSUE THREAD

**Issue by oceaneblard** [satijalab/seurat#8892]
Hello,

I have a developmental dataset with 6 timepoints and I did the following workflow (feel free to let me know if there is something wrong):
1) upload the data for each samples
2) merge all the samples into one object
3) join the layers so all the samples are mixed into one layer
4) filter, normalize (SCTransform) and cluster

I tried this workflow and also without joining the layers (no step 3) and have different results when observed with UMAP. Surprisingly without joining the layers, the common cells 'mixed' better in the UMAP.

Which workflow is the best practice? Joining the layers or not? Joining the layers before normalization or after?

Also, should I integrate my samples (they were run on the same 10X Genomics chip)?

Thank you for your help.

Oceane

**Comment by longmanz** [comment]
Hi @oceaneblard,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
