### ISSUE TITLE
Bridge integration with spatial transcriptomics as reference

### ISSUE THREAD

**Issue by AnnaAntonatouPap** [satijalab/seurat#8894]
Hello, 

I would like to ask a general question. I am doing spatial transcriptomics analysis ( similar to Slide-seq) and I want to integrate them with scATACseq data, based on my reading the best idea is to use dictionary learning since I also have a 10x multiome dataset, and use the ST dataset as a reference.  I see in the vignette, I can visualize the predicted annotations for the scATACseq on the reference UMAP embedding,I was wondering if I can visualize ATAC features into the spatial plot ( SpatialFeaturePlot)

Thanks in advance
Anna

**Comment by longmanz** [comment]
Hi @AnnaAntonatouPap ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
