### ISSUE TITLE
Best Practice for the QC analysis

### ISSUE THREAD

**Issue by recervictory** [satijalab/seurat#8898]
As a user of Seurat for single-cell analysis, I have been utilizing the QC functionalities provided for assessing the quality of my data. However, with an expanding number of samples, the process has become more complex. Currently, I've been examining the quality of my old PBMC dataset on a per-sample basis. Nevertheless, as the number of samples increases, I'm exploring alternative methods, particularly if it's feasible to conduct QC analyses across multiple samples and by batches.

#### Issue Description:

- Current Approach: Currently, I'm performing QC analyses using Seurat on a per-sample basis, focusing on metrics such as gene counts, mitochondrial gene percentages, and other relevant parameters.

- Challenges with Increasing Sample Numbers: As the number of samples in my dataset grows, managing QC on an individual sample basis becomes impractical and time-consuming. Hence, I'm seeking guidance on how to effectively handle QC with a larger sample size.

- Exploration of Alternatives: Given the complexity introduced by the increasing sample numbers, I'm interested in exploring whether it's possible and advisable to conduct QC analyses across multiple samples simultaneously. Additionally, I'm curious about the feasibility of conducting QC by batch, considering that my dataset might contain samples processed in different batches.

**Comment by longmanz** [comment]
Hi, 
The QC (gene counts, mitochondrial gene percentages, and other relevant parameters) you mentioned seem to matter on the cell level instead of the individual level. Are you performing any kind of pseudo-bulking prior to the QC? If not, it is fine to simply apply these QCs to your whole dataset without subsetting it on a per-sample basis.

**Comment by recervictory** [comment]
Thank you, @longmanz  for your response.

We were previously performing QC analyses on a per-sample basis, which has become increasingly tedious as the number of samples grows. Given the cell-level relevance of the QC metrics (gene counts, mitochondrial gene percentages, and other relevant parameters), it seems more efficient to conduct these analyses in batches.

Assuming that the samples were processed under similar conditions, batching them for QC would streamline the process significantly. This would allow us to manage the increasing dataset more effectively and maintain consistent quality checks across all samples.

I appreciate your insight, and I hope this approach aligns with the best practices for handling large-scale single-cell data.

Thanks again!
