### ISSUE TITLE
Passing latent variables to FindAllMarkers

### ISSUE THREAD

**Issue by khandarius** [satijalab/seurat#89]
Hi,

I have two batches of samples for analysis and an associated batch effect in the data. I have clustered the data together and I'm using the negative binomial test for finding cluster markers. I would like to pass the batch as a latent variable for the GLM when using the FindAllMarkers function, but this is not supported. Is there a particular reason for this? If not, could you consider adding this functionality in future releases of Seurat?

Thanks!

**Comment by andrewwbutler** [comment]
Hi, 

Thanks for pointing this out. We'll be sure to add this in the next version. One potential quick solution for now would be to just use an apply statement or a loop over FindMarkers to achieve the same functionality.
