### ISSUE TITLE
Merging more than two datasets in a single Seurat object

### ISSUE THREAD

**Issue by DanieleN90** [satijalab/seurat#890]
Hi,

I am trying to use Seurat to analyze a data from a scRNA-Seq experiments, and my data is splitted in 14 different folders.

What I am doing now is reading each folder as a single Seurat object and then merge them all in one big dataset. However, the merge() function can only work on two dataset at a time, so I merging each folder one step at a time through a for loop.

I have noticed that everytime that the merge function is called, a message about the log-normalization of the data appears. I was wondering how this normalization step works, and if by data are going to be impacted negatively.

I'll try to show my concern with an example:

I start with merging dataset1 and dataset2, they will get both normalized. Let's call this merged dataset "dataset12". In the next step I am merging dataset12 with dataset3, and the log-normalization message will appear again. Does this mean that the data from dataset12 gets normalized again? This would mean that when I will have merged all the 14 datasets, the first two datasets will have been normalized 13 times.

Will this impact urther analyses? If yes, how can I resolve this issue?

Thanks,
Daniele

**Comment by leonfodoulian** [comment]
Hi @DanieleN90,

The `object@data` slot will simply be updated at each run, without affecting the `object@raw.data` slot. So there is no impact on the analysis. 

Best,
Leon
