### ISSUE TITLE
Merge clusters

### ISSUE THREAD

**Issue by dincerkilic** [satijalab/seurat#8902]
Hello,

I would like to merge the clusters 0, 5, and 11 into named only "0".  Because I want to present them by the same color.
I tried;
Idents(seuratobj) <- c( "0" , "1", "2", "3", "4", "0", "6", "7" , "8" , "9", "10", "0", "12", "13", "14")

It did not work. Do you have suggestions?
Thank you!

**Comment by samuel-marsh** [comment]
Hi,

See this section from pbmc vignette:

```
new.cluster.ids <- c("Naive CD4 T", "CD14+ Mono", "Memory CD4 T", "B", "CD8 T", "FCGR3A+ Mono",
    "NK", "DC", "Platelet")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
```

Best,
Sam

**Comment by dincerkilic** [comment]
Thank you very much, this helps!
