### ISSUE TITLE
Why are the points in the plots drawn by the SpatialFeaturePlot() function very small?

### ISSUE THREAD

**Issue by XudongHan-bio** [satijalab/seurat#8906]
My procedure is as follows:
`
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
InstallData("stxBrain")
brain <- LoadData("stxBrain", type = "anterior1")
plot1 <- VlnPlot(brain, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
plot2 <- SpatialFeaturePlot(brain, features = "nCount_Spatial") + theme(legend.position = "right")
wrap_plots(plot1, plot2)
brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)
SpatialFeaturePlot(brain, features = c("Hpca", "Ttr"))
`

Get the following image:

![image](https://github.com/satijalab/seurat/assets/49810640/ea3e342a-925e-42db-929b-1780c90d319d)

Why are the points in the plots drawn by the SpatialFeaturePlot() function very small?

**Comment by XudongHan-bio** [comment]
I tried adjusting pt.size.factor, but it didn't work.

**Comment by dcollins15** [comment]
Thanks for reaching out @XudongHan-bio - this is a known issue with the current `stxBrain` dataset, we should be pushing an update soon 👍 

If you run:

```R
image <- brain[["anterior1"]]
scale_factors <- ScaleFactors(image)

hires_scale_factor <- scale_factors[["hires"]]
spot_radius <- scale_factors[["spot"]]
```

You'll notice that `hires_scale_factor` and `spot_radius` are equal - this should not be the case. Fortunately, there's an easy workaround:
```R
brain@images$anterior1@scale.factors$spot <- 89.4725
```

**Comment by XudongHan-bio** [comment]
Thanks, problem solved.

**Comment by psecekartal** [comment]
hi, how can we solve this problem for the other datasets? I have currently 0.24 or 0.22 scale.factors for my dataset
