### ISSUE TITLE
PseudobulkExpressoin vs AggregateExpression

### ISSUE THREAD

**Issue by nina-hahn** [satijalab/seurat#8919]
Dear all,

what is the difference between the Seurat functions PseudobulkExpression and AggregateExpression? So war I found some tutorial using AggregateExpression but none using PseudobulkExpression. When do I have to use which one for my spatial data analysis?

Kind regards,
Nina

**Comment by samuel-marsh** [comment]
Hi Nina,

Not member of dev team but hopefully can be helpful.  See source code here which shows that AggregateExpression passes inputs to PseudobulkExpression.  The outputs will be the same assuming the input parameters are identical.

https://github.com/satijalab/seurat/blob/1549dcb3075eaeac01c925c4b4bb73c73450fc50/R/utilities.R#L363

Best,
Sam

**Comment by nina-hahn** [comment]
Hi Sam, 

ahh thanks a lot!

Best, Nina
