### ISSUE TITLE
Visualising Depth

### ISSUE THREAD

**Issue by JoshuaCumming** [satijalab/seurat#892]
Hi,

I was wondering if it is possible to color either PCA plots or tSNEs by number of genes detected to visually represent any effects of depth on clustering?

I am trying to plot PCAs outside of Seurat using the normalized count from the Seurat object and they look very different compared to the PCAs generated in Seurat. I am using the `object@scale.data` slot to get the normalized data and then just use this in R
```R
PC<-prcomp(DNUC)
plot(PC$x[,1:2],col=col.library,main="first PCA")
legend("topleft",libraries,col=coldef.library,cex=0.5,bty='n')
```
However, it looks completely different to the PCA I generate in Seurat with:
```R
PCAPlot(object = DNUC, dim.1 = 1, dim.2 = 2)
DNUC <- ProjectPCA(object = DNUC, do.print = FALSE)
```
Any idea, why they would be so different?

Thanks for any help.

Best wishes,

Joshua

**Comment by satijalab** [comment]
Certainly - FeaturePlot can be used to overlay gene expression or metadata onto a PCA or tSNE plot.

For example
FeaturePlot(object, 'nGene') [or 'nFeature_RNA' in Seurat3], is great for visualizing these potential effects
