### ISSUE TITLE
Warning: Adding a dimensional reduction (integrated.rpca) without the associated assay being present

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#8927]
I am following this vignette https://satijalab.org/seurat/articles/parsebio_sketch_integration 
I have several questions and will appreciate it if you can help me: 
1) I am working on different studies, do I integrate samples first then integrate datasets together, if it makes sense?
2) In the vignette,  find highly variable genes was done before and after Sketch. Why? 
3) In the vignette there was a reference in the integration step. I am not sure what reference I am supposed to use in my case?
4) when I did not use a reference, I had this warning 
Warning: Adding a dimensional reduction (integrated.rpca) without the associated assay being present

The code: 
 I merged the BCells/disk Seurat objects (an object for each study dataset)
merged <- merge(obj2, c(obj3, obj4, obj5, obj6, obj7, obj8, obj9, obj10, obj11))

 I joined all layers
merged <- JoinLayers(merged)

merged <- NormalizeData(merged)
merged[["RNA"]] <- split(merged[["RNA"]], f = merged$dataset)

find variable features before Sketching (why?)
merged <- FindVariableFeatures(merged)

Sketch the data
merged <- SketchData(object = merged, ncells = 20000, method = "LeverageScore", sketched.assay = "sketch")
DefaultAssay(merged) <- "sketch"

find variable features after Sketching
merged <- FindVariableFeatures(merged, verbose = F)
merged <- ScaleData(merged, verbose = F)
merged <- RunPCA(merged, verbose = F)

 integrate the datasets. (what is the reference in my case?) 
merged <- IntegrateLayers(merged, method = RPCAIntegration, orig = "pca", new.reduction = "integrated.rpca",
                          dims = 1:30, k.anchor = 20, reference = which(Layers(merged, search = "data") %in% c("data.H_3060")),
                          verbose = F)

I did not use a reference and got this warning
 merged <- IntegrateLayers(
+   object = merged, method = RPCAIntegration,
+   orig.reduction = "pca", new.reduction = "integrated.rpca",
+   verbose = FALSE
+ )
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=40m 20s
Warning: Adding a dimensional reduction (integrated.rpca) without the associated assay being present

> merged
An object of class Seurat 
80180 features across 1475254 samples within 2 assays 
Active assay: sketch (40090 features, 2000 variable features)
 21 layers present: counts.dataset1, counts.dataset2, counts.dataset3, counts.dataset4, counts.dataset5, counts.dataset6, counts.dataset7, counts.dataset8, counts.dataset9, counts.dataset10, data.dataset1, data.dataset2, data.dataset3, data.dataset4, data.dataset5, data.dataset6, data.dataset7, data.dataset8, data.dataset9, data.dataset10, scale.data
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, integrated.rpca

**Comment by Flu09** [comment]
Anther issue I am facing is with the MNN method


> merged <- IntegrateLayers(
+   object = merged, method = FastMNNIntegration,
+   new.reduction = "integrated.mnn",
+   useNames = FALSE,
+   verbose = FALSE
+ )
Error in checkBatchConsistency(batches, cells.in.columns = TRUE) : 
  number of rows is not the same across batches (see batch "useNames")

**Comment by longmanz** [comment]
Hi @Flu09 ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
