### ISSUE TITLE
Convert Seurat to Anndata doesn't save scale.data

### ISSUE THREAD

**Issue by dhb2128** [satijalab/seurat#893]
Hi,

Thanks for writing the conversion to anndata option. It's been quite useful.

However, I've been having trouble exporting the scale.data slot to the X.slot. Even when I selected scale.data, the slot in the anndata object was, I believe, the same as obj@data. The only thing that worked was replacing the data slot with scale.data.

```
# doesn't work
Convert(obj, "anndata", x,
        X.slot="scale.data", raw.slow="raw.data")
# works
obj@data <- obj@scale.data
Convert(obj, "anndata", x,
        X.slot="data", raw.slow="raw.data")
```

Do you think it would be that difficult to also add the option to export the PCA gene loadings to the varm slots?

Thanks,
David

**Comment by satijalab** [comment]
As I understand it, AnnData objects store one representation of the data (ie, counts, normalized data, or scaled data). We give the user the option to select which slot to export, but I believe it can only be a single one. If this is incorrect, please weigh in and we will certainly change going forward.

**Comment by dhb2128** [comment]
Hi,

I think this is incorrect. AnnData also has the raw slot, which can store another version of the .X field (see https://anndata.readthedocs.io/en/latest/anndata.AnnData.html). Hence I think the `Convert` function is correct in theory in that you should be able to pick two out of raw.data, data, and scale.data and save them in the .X and .raw.X fields. However, as mentioned above even when I wanted the .X field to contain the scaled data rather than the data slot, it still saved the data slot into .X.

Both the function arguments in `Convert` and the code by eye seem to account for this (by having options for both raw and X, but in practice I couldn't figure out why it isn't saving the correct slot into X.
