### ISSUE TITLE
Visium image shrunk

### ISSUE THREAD

**Issue by weishwu** [satijalab/seurat#8931]
I loaded a Visium dataset in Seurat using Load10X_Spatial. The image is horizontally shrunk:
<img width="740" alt="Screenshot 2024-05-24 at 1 21 30 PM" src="https://github.com/satijalab/seurat/assets/13355007/69651de5-2867-47be-863a-c553814deef5">

This is what the original image looks like in Loupe Browser:
<img width="1097" alt="Screenshot 2024-05-24 at 1 26 45 PM" src="https://github.com/satijalab/seurat/assets/13355007/2ec24aa4-8a09-405c-a9ac-f52797c67c7a">

I didn't realize Seurat shrinks spatial images this way. Is there a way to disable shrinkage?

**Comment by WesDe** [comment]
You can set `crop=F` to avoid this effect.

**Comment by weishwu** [comment]
I tried `crop=F` but it only shows the background region. The entire image is still shrunk horizontally (or stretched vertically):
![Uploading Screenshot 2024-05-27 at 4.19.47 PM.png…]()

**Comment by longmanz** [comment]
Hi @weishwu, 
Thank you for reporting this and as dcollins15 has mentioned that it is definitely on our to-do list. We will close this issue for now.
