### ISSUE TITLE
RCTD for Xenium data

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#8932]
Dear all,

I was applying the vignette:
https://satijalab.org/seurat/articles/seurat5_spatial_vignette_2#mouse-brain-10x-genomics-xenium-in-situ

Annotations are extracted by:
annotations.df <- RCTD@results$results_df
annotations <- annotations.df$first_type

from the RCTD object produced by spacexr. Inspecting results_df, there is a column named "spot_class". For some cells, this column gives "doublet_certain".

However, in the Seurat vignette, there is no differentiation between singlets and doublets, is there any reason for that?

Thanks, best, Chris

**Comment by longmanz** [comment]
Hi, 
Thanks for reporting this and it is true that we did not incorporate the "doublet_certain" information. We will keep this in mind and update it in the future.

**Comment by guilledelavega** [comment]
Hi @longmanz ,

Did you finally update this information? I cannot see it and I am looking for some info.

Thank you!
