### ISSUE TITLE
remotes::install_github("satijalab/seurat-data", quiet = TRUE) does not work

### ISSUE THREAD

**Issue by asmlgkj** [satijalab/seurat#8933]
remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("satijalab/seurat-data", quiet = TRUE)

Warning message:
In i.p(...) :
The exit status was not 0 when installing package 'SeuratData_0.2.2.9001.tar.gz'

in centos8 or win11, the same error.
Thanks a lot

**Comment by Y-CBob** [comment]
same here. Warning message is : "
Installing 2 packages: uwot, SeuratObject
Warning: dependency ‘Matrix’ is not available
Packages which are only available in source form, and may need compilation of C/C++/Fortran: ‘uwot’ ‘SeuratObject’
installing the source packages ‘uwot’, ‘SeuratObject’

Error: Failed to install 'Seurat' from GitHub:
  ! System command 'Rcmd.exe' failed
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In i.p(...) : installation of package ‘uwot’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘SeuratObject’ had non-zero exit status
"

**Comment by asmlgkj** [comment]
error: Failed to install 'Seurat' from GitHub:
  ! System command 'R' failed
on today

**Comment by longmanz** [comment]
Hi, 
Please install Seurat and SeuratObject directly from CRAN using install.packages() function and then try to install the SeuratData again. Please feel free to re-open it if the issue persists.
