### ISSUE TITLE
GSE dataset to Seurat object convert problem

### ISSUE THREAD

**Issue by focusdk88** [satijalab/seurat#8937]
Hello

I am trying to create a Seurat object from the GSE146100 dataset.
(https://130.14.29.110/geo/query/acc.cgi?acc=GSE146100)

Seurat <- read.delim("GSE146100_NormData.txt.gz", header = T, stringsAsFactors = F)
View(Seurat)
![스크린샷 2024-05-27 163356](https://github.com/satijalab/seurat/assets/170923192/a4383e31-1038-4688-98b5-a1d5f903122c)

In next, how can i covert dataset to Seurat object? 

I would be very grateful if you could let me know.

Thanks
Best regard
DKK

**Comment by longmanz** [comment]
Hi, 
You can use commands like CreateAssayObject() and CreateSeuratObject() to convert any count / data matrix into a Seurat object.
