### ISSUE TITLE
Error about weight.reduction in TransferData

### ISSUE THREAD

**Issue by Mollyx06** [satijalab/seurat#8939]
I have a similiar error with [https://github.com/satijalab/seurat/issues/6098](url)
when I run this step
`predictions.assay <- TransferData(anchorset = anchors, refdata = ref@meta.data$celltype, prediction.assay = TRUE,
    weight.reduction = que[["pca"]], dims = 1:30)`
`Finding integration vectors
Finding integration vector weights
Predicting cell labels
Error in possible.ids[apply(X = prediction.scores, MARGIN = 1, FUN = which.max)]: invalid subscript type 'list'
Traceback:
1. TransferData(anchorset = anchors, refdata = ref@meta.data$celltype, 
 .     prediction.assay = TRUE, weight.reduction = que[["pca"]], 
 .     dims = 1:30)`

and this is my que[["pca"]]
![image](https://github.com/satijalab/seurat/assets/71691727/bdfb3a16-c092-4f89-bcee-90ede4f8a77a)
Is anything wrong?

**Comment by Mollyx06** [comment]
I changed the way of importing vectors, but it still reports the same error
![image](https://github.com/satijalab/seurat/assets/71691727/0256b042-4129-4633-825a-4250b317bc55)
detailed str in my 'que'
![image](https://github.com/satijalab/seurat/assets/71691727/661d4293-48af-4964-8913-050a7076cc84)

**Comment by Mollyx06** [comment]
In the end I dropped the PCA weighting and barely got the results.

**Comment by rachadele** [comment]
Had the same issue, reducing k.anchor in FindTransferAnchors from 10 to 5 fixed it.
