### ISSUE TITLE
GitHub wiki out of date

### ISSUE THREAD

**Issue by kevinrue** [satijalab/seurat#8945]
Just to point out that the Seurat wiki is out of date, and either needs an update or perhaps being removed to avoid any confusion, especially with v5 updates.

I used to point to https://github.com/satijalab/seurat/wiki/Seurat#slots when teaching the structure of Seurat object, but the layers have now replaced the slots.

>  Paul Hoffman edited this page Apr 16, 2020 · 8 revisions 

Thanks!

**Comment by longmanz** [comment]
Hi, 
Thanks so much for pointing this out! We will definitely remove it soon to avoid any confusion. Please refer to this page for the updates in our v5 object structure (https://satijalab.org/seurat/articles/announcements.html).

**Comment by AlbertoFabbri93** [comment]
@longmanz On the website you linked I can not find any explanation as simple and straightforward as the wiki. I can only find vignettes with example workflow... Am I wrong? If so, do you mind sharing a link?
