### ISSUE TITLE
spatstat.explore is not loaded

### ISSUE THREAD

**Issue by fangpingmu** [satijalab/seurat#8948]
I am using Redhat Linux system. R version is 4.4.0. 

When I directly load Seurat, it gives the error message that "object 'integral' not found whilst loading namespace 'spatstat.explore'". Using sessionInfo(), I cannot find that spatstat.explore is loaded. 

If I manually preloaded spatstat.explore, then I can load Seurat.

R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(Seurat)
Loading required package: SeuratObject
Loading required package: sp

Attaching package: ‘SeuratObject’

The following objects are masked from ‘package:base’:

    intersect, t

Error: package or namespace load failed for ‘Seurat’:
 object 'integral' not found whilst loading namespace 'spatstat.explore'
> library(spatstat.explore)
Loading required package: spatstat.data
Loading required package: spatstat.geom
Loading required package: spatstat.univar
spatstat.univar 2.0-3
spatstat.geom 3.2-9.017
Loading required package: spatstat.random
spatstat.random 3.2-3.002
Loading required package: nlme
Registered S3 methods overwritten by 'spatstat.explore':
  method           from
  Summary.fasp
  Summary.fv
  collapse.anylist
  collapse.fv
  compatible.fv
  density.ppp
  deriv.fv
  harmonise.fv
  harmonize.fv
  quantile.density
spatstat.explore 3.2-7

Attaching package: ‘spatstat.explore’

The following objects are masked from ‘package:spatstat.univar’:

    CDF, CDF.density, dkernel, kaplan.meier, kernel.factor,
    kernel.moment, kernel.squint, km.rs, km.rs.opt, match.kernel,
    pkernel, qkernel, quantile.density, reduced.sample, rkernel,
    stieltjes, StieltjesCalc, StieltjesCalc.stepfun

> library(Seurat)
>

I have tried to change the Depends section under DESCRIPTION as follows. However, it does not work. 

DESCRIPTION
Depends: spatstat.explore, R (>= 4.0.0), methods, SeuratObject (>= 5.0.2)

**Comment by alexanderchang1** [comment]
Also dealing with this issue.

**Comment by rachelxrachel** [comment]
I'm also having a similar error, but my issue is with Error: object 'integral' not found whilst loading namespace 'spatstat.core'

when trying to install remotes::install_version("Seurat", "4.0.2", repos = c("https://satijalab.r-universe.dev", getOption("repos")))

I have spatstat.core version 2.1.2 installed first from the repository. I'm working on R on a Mac. Was anyone able to resolve this issue to install Seurat?

**Comment by pkuerten** [comment]
Same issue. The following combination of old packages helped me get past the 'integral' error. 

devtools::install_version("spatstat.core", version = "2.4-0", repos='http://cran.us.r-project.org')
devtools::install_version("spatstat.data", version = "2.1-2", repos='http://cran.us.r-project.org')
devtools::install_version("spatstat.geom", version = "2.3-2", repos='http://cran.us.r-project.org')
devtools::install_version("spatstat.random", version = "2.1-0", repos='http://cran.us.r-project.org')

**Comment by fangpingmu** [comment]
One of our researchers has told me the following methods.

Install the github version of seuratobject remotes::install_github("satijalab/seurat-object") and then reinstall spastat.

**Comment by Chunfu-Shawn** [comment]
> Same issue. The following combination of old packages helped me get past the 'integral' error.
> 
> devtools::install_version("spatstat.core", version = "2.4-0", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.data", version = "2.1-2", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.geom", version = "2.3-2", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.random", version = "2.1-0", repos='http://cran.us.r-project.org')

This is helpful and resolves my issue. Thanks a lot!

**Comment by mailmrcai** [comment]
> Same issue. The following combination of old packages helped me get past the 'integral' error.
> 
> devtools::install_version("spatstat.core", version = "2.4-0", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.data", version = "2.1-2", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.geom", version = "2.3-2", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.random", version = "2.1-0", repos='http://cran.us.r-project.org')

this method worked.

**Comment by avishai987** [comment]
> Same issue. The following combination of old packages helped me get past the 'integral' error.
> 
> devtools::install_version("spatstat.core", version = "2.4-0", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.data", version = "2.1-2", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.geom", version = "2.3-2", repos='http://cran.us.r-project.org') devtools::install_version("spatstat.random", version = "2.1-0", repos='http://cran.us.r-project.org')

For me spatstat.geom and spatstat.random installation encountered error, but:
```
devtools::install_github("https://github.com/spatstat/spatstat.geom/releases/tag/v2.4-0")
devtools::install_version("spatstat.random", version = "2.2-0", repos='http://cran.us.r-project.org')
```
worked
