### ISSUE TITLE
Creating a Seurat Object with data from GEO

### ISSUE THREAD

**Issue by charmscharms** [satijalab/seurat#8955]
Hi all I have a question, most of public available dataset for vissium at GEO, have four different files counts(filtered_feature_bc_matrix.h5), scalefactors_json.json , image_lowres_image.png and coordinates (tissue_positions_list.csv) I was wondering to know if you have a workflow for creating a spatial Seurat object with these 4 files. I've tried to come up with a code for that, however getting errors when trying to read the image, positions files have 5 columns (X0, X0.1, X0.2, X171 and X136) also having trouble reading the json file. The only file I' m able to read is the h5 file, but has no coordinate. I'd like to do at least the analysis without the image/scale, but also I haven't been able to add the coordinates to the Seurat object created with the h5 file.

`counts <- Read10X_h5(counts_file) `
`seurat_obj <- CreateSeuratObject(counts = counts, assay = "Spatial")`

Thanks in advance
this was asked before in  https://github.com/satijalab/seurat/issues/3595 .

**Comment by zskylarli** [comment]
Hi - for Visium, you should direct your path in `Load10X_Spatial` to the folder containing all of those 4 files. Please refer to the documentation [here](https://satijalab.org/seurat/reference/load10x_spatial).
