### ISSUE TITLE
Problems regarding AggregateExpression Documentation 

### ISSUE THREAD

**Issue by emmanuelmekasha** [satijalab/seurat#8957]
Hello!

I'm trying my best to recreate the normalization functions that lead to the output of AggregateExpression, but I have failed several times. I believe there may be some ambiguity that's leading to my misunderstandings. Could someone outline the normalization steps from initializing the seurat object to getting the aggregated matrix from this function? I had previously thought the pipeline was as follows:
Inputted Seurat Object --> NormalizeData() leads to lognormalized data assay -> AggregateExpression() takes data assay as input and aggregates according to idents -> Output Matrix

Clarification would be greatly appreciated!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So the manual entry for `AggregateExpression` describes the process.  AggregateExpression is summing the raw count data (usually to create a pseudobulk sample (which requires summed raw counts analogous to a bulk-seq'ed sample)).
From documentation (web link here but also present in R): https://satijalab.org/seurat/reference/aggregateexpression


_Value_
_Returns a matrix with genes as rows, identity classes as columns. If return.seurat is TRUE, returns an object of class [Seurat](https://satijalab.org/seurat/reference/seurat-package)._

_Details_
_If return.seurat = TRUE, aggregated values are placed in the 'counts' layer of the returned object. The data is then normalized by running [NormalizeData](https://satijalab.org/seurat/reference/normalizedata) on the aggregated counts. [ScaleData](https://satijalab.org/seurat/reference/scaledata) is then run on the default assay before returning the object._

Best,
Sam
