### ISSUE TITLE
Many cells are assigned <NA> cluster when using ProjectIntegration & ProjectData function

### ISSUE THREAD

**Issue by sentisci** [satijalab/seurat#8965]
Cells that were not used during SketchData step are not assigned to a cluster and declared <NA>
I followed the following Vignette https://satijalab.org/seurat/articles/parsebio_sketch_integration

My code:

filtered_seurat <- NormalizeData(filtered_seurat)
filtered_seurat <- FindVariableFeatures(filtered_seurat, verbose = FALSE)
filtered_seurat <- SketchData(object = filtered_seurat,
ncells = 5000,
method = "LeverageScore",
sketched.assay = "sketch")
filtered_seurat
filtered_seurat <- FindVariableFeatures(filtered_seurat)
filtered_seurat <- ScaleData(filtered_seurat)
filtered_seurat <- RunPCA(filtered_seurat)
filtered_seurat <- IntegrateLayers(
object = filtered_seurat, method = RPCAIntegration,
orig.reduction = "pca", new.reduction = "integrated.rpca",
dims = 1:30, k.anchor = 20,
verbose = FALSE
)
filtered_seurat <- FindNeighbors(filtered_seurat,reduction = "integrated.rpca",
dims = 1:30)
filtered_seurat <- FindClusters(filtered_seurat, resolution = 0.5,
cluster.name = "rpca_clusters")

filtered_seurat_project <- ProjectIntegration(object = filtered_seurat,
sketched.assay = "sketch", assay = "RNA",
reduction = "integrated.rpca")

filtered_seurat_project_2 <- ProjectData(object = filtered_seurat_project, sketched.assay = "sketch",
assay = "RNA", sketched.reduction = "integrated.rpca",
full.reduction = "integrated.rpca.full", dims = 1:30,
refdata = list(celltype.full = "rpca_clusters"))

[filtered_seurat@meta.data](mailto:filtered_seurat@meta.data)$rpca_clusters[1:10]
[1] 6 5 1 7
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

[filtered_seurat_project@meta.data](mailto:filtered_seurat_project@meta.data)$rpca_clusters[1:10]
[1] 6 5 1 7
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
colnames([filtered_seurat_project@meta.data](mailto:filtered_seurat_project@meta.data))
[1] "seq_folder" "nUMI_RNA" "nGene" "nUMI_ADT" "nFeature_ADT" "percent_mt"
[7] "percent_ribo" "log10GenesPerUMI" "cells" "type" "nUMI_RNA_1og10" "nUMI_ADT_1og10"
[13] "nCount_SCT" "nFeature_SCT" "nCount_RNA" "nFeature_RNA" "nCount_ADT" "Patient"
[19] "Group" "leverage.score" "rpca_clusters" "seurat_clusters"

Can you please review and let me know as soon as you can ? Thanks in advance

**Comment by zskylarli** [comment]
Since you project the `rpca_clusters` labels to `filtered_seurat_project_2` under `celltype_full`, that should be where the projected labels are for the full object (i.e. for the cells that were not in the sketched object). Can you check `filtered_seurat_project_2$rpca_clusters`?

**Comment by sentisci** [comment]
Thanks. You are correct.
