### ISSUE TITLE
FetchData FilterCells

### ISSUE THREAD

**Issue by jmzvillarreal** [satijalab/seurat#897]
I am beginning to use Seurat for single cell analysis, in addition I am quite new into bioinformatics so first of all, sorry for the basic question...

I am trying to get a subset of my expression matrix by filtering the Seurat object by a level of the metadata using FetchData or FilterCells tool
```R
> head(pbmc@meta.data)
   nGene    nUMI     orig.ident AGE_GROUP CLUSTER_ID CELL_TYPE
C1  2076  165481 Human_pancreas     CHILD          0 ENDOCRINE
C2  2540  538982 Human_pancreas     CHILD          0 ENDOCRINE
C3  2726  486234 Human_pancreas     CHILD          0 ENDOCRINE
C4  2696  104782 Human_pancreas     CHILD          9 ENDOCRINE
C5  3013 1698283 Human_pancreas     CHILD          9 ENDOCRINE
C6  2730  141311 Human_pancreas     CHILD          9 ENDOCRINE
```
What would be the correct way to get only the ENDOCRINE cells for instance ?
Everything that I have tried gives me an error ...

Thanks very much in advance..
Best,
Jaime.

**Comment by stillhere89** [comment]
Hi,
Try SubsetData:
Creates a Seurat object containing only a subset of the cells in the original object. Takes either a list of cells to use as a subset, or a parameter (for example, a gene), to subset on.
