### ISSUE TITLE
Missing parallelization docs for v5?

### ISSUE THREAD

**Issue by nick-youngblut** [satijalab/seurat#8975]
It appears that there is only an archived [future vignette for v4](https://satijalab.org/seurat/archive/v4.3/future_vignette) and not for v5. 
Also, it appears that there is no documentation in the specific functions that can be parallelized. For example [the FindMarkers function docs](https://satijalab.org/seurat/reference/findmarkers) do not mention parallelization.

**Comment by sykesmarc** [comment]
I agree

**Comment by samuel-marsh** [comment]
Hi,

See https://github.com/satijalab/seurat/issues/9385#issuecomment-2486214970

Best,
Sam
