### ISSUE TITLE
Beginner: need help with PCA and generating plot

### ISSUE THREAD

**Issue by aigerim2398** [satijalab/seurat#8976]
So, I have 4 samples: control1, control2, treatment1 and treatment2. I need to create a plot of these 4 samples to see their distribution on the plot in a way so that there is 1 dot per sample (not many dots representing the cells). I am quite stuck and not sure what to do. 
My approach was to do pseudobulking, but I end up having every sample name associated with cell name (e.g. control1_dendritic). and the graph ends up having all the cells in it. Could you please suggest how I can do that?

**Comment by zskylarli** [comment]
Hi - not exactly sure what plot you are referring to, but for DimPlots, the pseudobulking should work for representing cells at the sample level as long as it is followed by running PCA and/or UMAP again, depending on what you are trying to achieve.

Additionally, in an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance. We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
