### ISSUE TITLE
Default FindMarkers - positive and negative?

### ISSUE THREAD

**Issue by rbedi** [satijalab/seurat#898]
Hi,

I'm using Seurat's FindMarkers to identify differentially expressed genes between cell clusters. I noted in the Guided Clustering tutorial that the default is for Seurat to consider both positively and negatively differentially expressed genes as markers for a given cluster. Because the counts for single cell data are considerably zero-inflated, we're considering instead only considering upregulated genes as putative cluster markers. There are several methods for dimensionality reduction that explicitly model zero inflation (eg ZIFA, ZINB-WaVE) but am wondering, in the case of cluster marker identification, are you aware of any work (or have any anecdotal experience) regarding this decision?

Thanks very much!

**Comment by satijalab** [comment]
Please feel free to check out Christoph's sctransform package : https://github.com/ChristophH/sctransform, which uses a regularized negative binomial to handle sparsity and variable read depth in single cell data.
