### ISSUE TITLE
uma application

### ISSUE THREAD

**Issue by MrsJae** [satijalab/seurat#8989]
```r
# insert reproducible example here
```

**Comment by MrsJae** [comment]
Uma application screen connect I need to delete it won't go away I didn't store that in my laptop

**Comment by samuel-marsh** [comment]
Hi,

can you please provide some additional information.  It is unclear what exactly the issue you are having is.

Best,
Sam

**Comment by zskylarli** [comment]
Will close due to inactivity. In the future, please make sure to follow these best practices for posting a Github issue:

1. **Describe your issue**:
    - A clear and concise description of what the bug is — avoid just pasting in the error message.  
    
2. **Reproducing Code Example**:
    - Provide a minimal reproducible example that demonstrates the issue using one of the datasets available through SeuratData. Paste the code in a code block.
    - The code example should make use of `pbmc_small` or one of the datasets available through SeuratData.
    
3. **Error Message**:
    - If any, paste the *full* error message (starting from line Traceback) in a code block.
    - If no error is raised, consider writing a simple test case that explicitly raises an error if the  
    
4. **System Information**:
    - Run `sessionInfo()` and paste the result in a code block.
