### ISSUE TITLE
CalcPerturbSig error with nn2

### ISSUE THREAD

**Issue by mangochiral** [satijalab/seurat#8990]
https://github.com/satijalab/seurat/issues/7222

I have multiple assays, with 2940 cells and the using targets_2+ cell for gd.class, for which some cells have none guide. I am getting error irrespective of reducing the num.neighbours to 1.
test_perturb <- CalcPerturbSig(test_perturb, 
                               assay = "RNA", 
                               slot = "data", 
                               gd.class = "targets_2+", 
                               nt.cell.class = "NT", 
                               reduction = "pca_antibc_sing", 
                               num.neighbors = 1, 
                               ndims = 10, 
                               new.assay.name = "PRTB")
                               
Error in nn2(data = numeric(0), query = c(-6.93251631983229, -0.338168035222451,  : 
  Cannot find more nearest neighbours than there are points
5. stop("Cannot find more nearest neighbours than there are points") 4. nn2(data = structure(numeric(0), dim = c(0L, 10L), dimnames = list( NULL, c("PCATBCSING_1", "PCATBCSING_2", "PCATBCSING_3", "PCATBCSING_4", "PCATBCSING_5", "PCATBCSING_6", "PCATBCSING_7", "PCATBCSING_8", "PCATBCSING_9", "PCATBCSING_10"))), query = structure(c(-6.93251631983229, ... 3. do.call(what = "nn2", args = args) 2. NNHelper(data = nt_mtx[, 1:ndims], query = all_mtx[, 1:ndims], k = num.neighbors, method = "rann") 1. CalcPerturbSig(test_perturb, assay = "RNA", slot = "data", gd.class = "targets_2+", nt.cell.class = "NT", reduction = "pca_antibc_sing", num.neighbors = 2, ndims = 10, new.assay.name = "PRTB")

**Comment by igrabski** [comment]
Hi Chandrima, can you confirm that the cells receiving a non-targeting guide are labeled exactly as "NT" in your column `targets_2+`?

**Comment by igrabski** [comment]
Since it's been a little while with no response, I will go ahead and close this issue, but please feel free to re-open or start a new issue if the problem persists!
