### ISSUE TITLE
The gene expression matrix after batch effect correction.

### ISSUE THREAD

**Issue by galaxyeee** [satijalab/seurat#8997]
Hi,
I've always been using Seurat for single-cell analysis, so thanks for developing such a great package. I have a question while I'm analyzing something.
When using packages like NMF for analysis, it's necessary to utilize the gene expression matrix. However, when correcting for batch effects using methods like fastMNN or Harmony, and wanting to analyze the corrected gene expression values, which gene expression matrix should be used? I also want to see results using the corrected gene expression values, but it seems that the batch-corrected values overwrite the original ones, as both @assays$RNA@scale.data and @assays$RNA@data contain the same values before and after batch correction. I'm currently using Seurat_v4. 

Thank you.
LIM

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful. Harmony and most other integration methods only correct the cell embedding, they do not produce corrected count matrices. Corrected count matrices do suffer from significant issues.  You should use RNA or SCT assay as appropriate for you specific analysis pipeline.

Best,
Sam
