### ISSUE TITLE
FindAllMarkers return.thresh (possible documentation fix)

### ISSUE THREAD

**Issue by rpeys** [satijalab/seurat#90]
When describing the return.thresh argument in FindAllMarkers, the documentation says: "Only return markers that have a p-value < return.thresh, or a **power** > return.thresh (if the test is ROC)"

Based on this line of code in FindAllMarkers: 
`if (test.use=="roc") {
                  gde=subset(gde,(myAUC>return.thresh|myAUC<(1-return.thresh)))
                }`
it looks to me like the user should actually pass in an **AUC** value, not power, to the return.thresh parameter.

Which is correct? Thanks!

**Comment by satijalab** [comment]
This was fixed in a previous release, closing the issue now.

**Comment by Sandman-1** [comment]
Hello, guys! I think the return.thresh parameter does not work for various test options in FindMarkers and FindAllMarkers. I have tried running these commands with test.use set to either Wilcox, MAST, LR, or DESeq2, and so far the return.thresh parameter has only worked with DESeq2. Is this a bug, or am I doing something incorrectly? An example of my code is below. Please let me know if you need additional information.

all_classes_sc.degs <- FindAllMarkers(TKO_hep, assay = "RNA", test.use = "MAST", logfc.threshold = log2(1.20), return.thresh = 1, random.seed = 1234)
