### ISSUE TITLE
Why HVG change when creating Integrated.data?

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#900]
Hi all!
I just realized that when I selected for HGV using your tutorial with 1000 genes per dataset, when I then created data.integrated object using RunMultiCCA function (I have three datasets), the number of high variable genes in genes.use changed if you now look at `data.integrated@var.genes`. Why is it happening? May RunMultiCCA be doing a kind of filtering? 
```R
data.list <- list(data.WT, data.Floxp, data.Floxm) 
genes.use <- c() 
for (i in 1:length(data.list)) {
  genes.use <- c(genes.use, head(rownames(data.list[[i]]@hvg.info), 1000)) 
}
genes.use <- names(which(table(genes.use) > 1)) 
for (i in 1:length(data.list)) {
  genes.use <- genes.use[genes.use %in% rownames(data.list[[i]]@scale.data)] 
}

> length(genes.use)
[1] 703

data.integrated <- RunMultiCCA(data.list, genes.use = genes.use, num.ccs = 30)

> length(data.integrated@var.genes)
[1] 698
```
Which is the real number of genes it is being used as HVG?

Thanks!

**Comment by 2236529177** [comment]
is there any rellationship with hvg.info and var.genes, really a problem.
but integreted obeject and each single obejcet may have differerent genes in the author`s paper.
![image](https://user-images.githubusercontent.com/25199946/47651615-af881380-dbbe-11e8-9403-30a357391d18.png)

**Comment by mvalenzuelav** [comment]
I think you are talking about differentially expressed genes, but what I asked for is about high variable genes before running CCA.

**Comment by 2236529177** [comment]
> I think you are talking about differentially expressed genes, but what I asked for is about high variable genes before running CCA.

do not you think they are similar?

**Comment by andrewwbutler** [comment]
Hi,

`RunMultiCCA` and `RunCCA` will filter out any genes that have zero variance in any of the datasets. 

https://github.com/satijalab/seurat/blob/e5bace41d77b221f4f222a61a74d2efad0de49a0/R/dimensional_reduction.R#L816-L818

https://github.com/satijalab/seurat/blob/e5bace41d77b221f4f222a61a74d2efad0de49a0/R/dimensional_reduction_internal.R#L131-L136

It's possible that you have a few genes that are marked as highly variable in one dataset but have zero variance in one (or more) of the remaining datasets.

**Comment by mvalenzuelav** [comment]
But, is a gene with zero variance supposed to be selected as a HVG? Moreover, we also make another selection of genes that appear at least in two of the datasets. Do you mean that a gene that only appear in two of the datasets is then discarded because it has zero variance in the third dataset? In this way, I do not understand why making a first selection of HVGs in two of the datasets if, finally, they have to be in the three datasets. Do I understand well?
Thanks so much!

**Comment by satijalab** [comment]
Andrew's resposne is correct. We find variable genes on each dataset individually as a matter of procedure (also, in case you just wanted to align the first two samples for example, the third dataset would not be applicable in this case).
