### ISSUE TITLE
How to integrate different samples of Visium HD data?

### ISSUE THREAD

**Issue by yifanfu01** [satijalab/seurat#9007]
Hi, We thanks for the rapid upgrade and compability with HD data.
But how could I integrated maybe 2 to 4 HD samples?
I think it's confused if i use interlayer() or similar functions.
Many thanks.
Regards,

**Comment by zskylarli** [comment]
Hi - thank you for reaching out! We’re always grateful when folks take the time to try out our spatial functions and help make Seurat better 🙂 `interlayer()` is not a Seurat function and it is unclear what integration you are trying to achieve. To help us better understand and resolve your question, please ensure that you provide a clear and concise description of what you are exactly trying to achieve, what the current roadblocks are, and if possible, provide a minimal reproducible example that demonstrates the issue and paste the code in a code block. 
    
We’re going to go ahead and close this issue for now, but once you’ve gathered these details, we strongly encourage you repost and we will be more than happy to help you resolve the problem.
