### ISSUE TITLE
Normalizing per sample for abundance plots

### ISSUE THREAD

**Issue by dianajzajac** [satijalab/seurat#9009]
Hi! I am plotting counts using the VlnPlot function. I am plotting nCount_RNA and grouping by my covariates, which splits it into four groups, and am doing this per cell type according to my annotations from clustering (so per cluster). I looked at cell counts using box plots per group, per sample, and realized that in some cell types, overall counts are dominated by one sample. I think this could affect my abundance plots (VlnPlot), where one sample will make the overall means appear larger than if counts were normalized on a per sample per group basis. I am curious if there is a way the lab suggests normalizing the data and plotting it to account for total cell counts per sample skewing abundance?

I appreciate the help, thanks in advance!

**Comment by zskylarli** [comment]
Hi @dianajzajac  - thank you for your question!

It might be helpful to check how the visualizations are impacted when you omit that specific dominant sample versus when you plot the full object to see if there is a substantial impact on the abundance plots. 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance. 

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. We look forward to seeing your post there - thanks for using Seurat!
