### ISSUE TITLE
CCA for batch correction on multiple datasets

### ISSUE THREAD

**Issue by pbrazda** [satijalab/seurat#901]
Hi, 

I tried the tutorial for the 'stimulated vs. control PBMC' dataset and I was wondering if it would be applicable to do batch-correction on multiple datasets in parallel. (It worked on my dataset as well, for comparing 2 sets. )
What shall I modify in the script then?

Thank you!

**Comment by 2236529177** [comment]
multiccca can do a lot of datasets

**Comment by ccasar** [comment]
In the first paragraph of the PBMC CCA tutorial is a link to [this file](https://www.dropbox.com/s/aji4ielg8gc70vj/multiple_pancreas_workflow.R?dl=1), demonstrating the integration of four data sets.

**Comment by pbrazda** [comment]
Great! Thank you.
