### ISSUE TITLE
any suggestions for gsea? 

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#902]
Dear author, do you plan to add gsea function to your seurat, or is there any service for doing this

**Comment by jevanveen** [comment]
Not a Seurat author, but I have had good results using the r package fgsea. Once you get the hang of it, it's a lot quicker and easier than using the web portals or the desktop app, and since it's in r you can very easily take your marker lists from Seurat and plug them in.

**Comment by GHHenryUTSW** [comment]
I use QuSAGE as I've had much better success implementing in R, compared to R-GSEA which I've never gotten to work.
