### ISSUE TITLE
AverageExpression 

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#9020]
Hi,
In my snRNA-seq data, the population of a celltype has increased significantly in group A compared to group B, but the AverageExpression of its marker gene didn't increase (and not in the differential expression genes), how to explain this?

Thank you!
Best

**Comment by zskylarli** [comment]
Hi @yulchen810 ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
