### ISSUE TITLE
DotPlot: negative average expression on scTransformed object

### ISSUE THREAD

**Issue by sagrikachugh** [satijalab/seurat#9029]
Hi Seurat Team,

Thanks for your effort answering our queries. 
I have a similar question regarding using RNA assay for visualization. [(#7817 comments)](https://github.com/satijalab/seurat/issues/7817)

I am not doing integration but using scTransform normalization, when I did dot plot to visualize marker genes for my cluster my Average expression ranges from -1 to 2, if `scale=TRUE`(default). I can avoid this by changing `scale = FALSE` making the expression positive 0 to 5. I am confused what's the right approach and which data slot to use. I understand dot plot scales the data before visualisation but in this particular case it made the expression negative.

Here's my code 

```{r}
so <- CreateSeuratObject(counts = counts(sce))
so<- Seurat::AddMetaData(so, metadata, col.name = NULL)

so <- SCTransform(so, vars.to.regress = "subsets_Mito_percent", 
                                 min_cells = 1, verbose = FALSE, 
                                 vst.flavor = "v2", 
                                 variable.features.n = NULL)

so <- RunPCA(so, verbose = FALSE)
so <- RunUMAP(so, dims = 1:15, verbose = FALSE)
so <- FindNeighbors(so, dims = 1:15, verbose = FALSE)
so <- FindClusters(so, verbose = FALSE, resolution = 0.8)
DimPlot(so, label = TRUE, cols = cluster_colours) 

markers <- FindAllMarkers(so, assay = "SCT", 
                                               test.use = "wilcox",
                                               min.pct = 0.01, 
                                               logfc.threshold = 0.1)

DotPlot(so, features = all_features, assay = "SCT", scale = FALSE, 
             cols = c("blue", "red")) +
              theme(axis.text.x = element_text(size = 8),
              axis.text.y = element_text(size = 8), legend.position = "bottom") + 
              scale_y_discrete(labels = function(x) str_wrap(x, width = 5)) + RotatedAxis() + ylab("Clusters")
```
Here are my resulting dot plots (both with scale=TRUE and scale=FALSE)
[DotPlot.pdf](https://github.com/user-attachments/files/15900512/DotPlot.pdf)

**Comment by zskylarli** [comment]
Hi - when setting `scale = TRUE`, the DotPlot function scales the average expression values across all features (genes) to have a mean of 0 and a variance of 1 within each gene, which can result in negative average expression values because the data is centered around zero and is more useful for comparing relative expression levels across genes. In general, you should be fine using the scaled visualization! We’re going to close this issue for now but encourage you to repost your question in our [Discussions board](https://github.com/satijalab/seurat/discussions) if you have further questions.

**Comment by adRn-s** [comment]
Sorry for necro-bumping, but I feel like context is important. I recently traversed a rabbit hole and ultimately developed my own DotPlot function, wherein I employ "min max normalization" (`minmax_norm <- function(x) (x - min(x)) / (max(x) - min(x))`) in lieu of the 2-step implementation by [Seurat](https://github.com/satijalab/seurat/blob/release/5.1.0/R/visualization.R#L4537-L4539) (`scale() %>% MinMax()` ).
