### ISSUE TITLE
Function to retrieve Average log FC and P value for a test for all genes across the identity classes?

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#903]
I could not find a function where I could get the results of significance tests (p value) of one cluster vs the rest and logFC calculations for all the genes in the data or a selected set of genes?. I wish to mimick the Single cell data as a bulk RNA seq data by averaging gene expression across the clusters and using each of the cluster as one sample as in EdgeR or DESeq2. If I could also obtain the logFC and p values for a test of significance against all other clusters along with it, I could use that data frame directly in IPA or similar tools.

Essentially what I am looking for is a function similar to FindAllMarkers but for all the genes I specify and for all clusters. If I use 'gene.use' argument, it still downselect the given gene list for significance and give out results only for a subset of genes specified.

Is there already a function for this?
Thank you in advance!

**Comment by camilliano** [comment]
Hi,
you should try something like  this:

```
object <- SetAllIdent(object, id = "orig.ident")
markers <- FindAllMarkers(object)
markers %>%top_n(10, avg_logFC)
```
I don't know if it's exactly what you are looking for but it could help.
I use it to compare all the DEG between control and stimulated data.

**Comment by bwang258** [comment]
Hi, 

I am not sure if I am understanding you right.

Isn't **FindAllMarkers** giving you p-value and logFC without the specification on `gene.use` ?

**Comment by saeedfc** [comment]
@bwang258 FindAllMarkers is not going to give the average of all genes in the set. It is usually genes only that are 'markers'. I want all the logFC for all genes. FindAllMarkers returns only results for some genes.
As far as I know there is no function in Seurat, which give you logFC for each identity for all gene sin the data set. Such a function could be handy as in my case where I can use it in porgrams like IPA.

At the end, I used a loop to set identity for the object such as to get two identities, identity X, and the rest. For each of these identity settings, then used average expression as a loop on each identity setting. Then with a loop, calculated Ratio of expression of Identity X/rest. This ratios were used in IPA.

I am no expert with R. This is what I came up with. Someone more familiar with R can make it a lot better and could probably end up with 3 or 4 line of code :)

Thanks everyone! 
`sos <- list()
# mono1 is the seurat object with 7 identities
#store in a list, each seurat object with only a single cluster as one identity class, and all other cells as the second identity class)
for(i in 1:7) {
	sos[[i]] <- SetIdent(mono1, cells.use =  WhichCells(mono1,
																												ident.remove = levels(mono1@ident)[[i]]), ident.use = paste0("NO_", levels(mono1@ident)[[i]]))
}
#Give name to each seurat Object
nam <- c()
for(i in 1:7) {
	nam[[i]] <- paste0("NO_", levels(mono1@ident)[[i]])
}

names(sos) <- nam

##not run avg0 <- AverageExpression(sos[[1]])
for(i in 1:7) {
	dfs[[i]] <- AverageExpression(sos[[i]])
}

df1 <- dfs[[1]]
df <- dfs

##based on the order of 'identity X'(x= 1:7) or 'Rest', calculated Ratio of expression for each setting, as some objects get saved with 'identity X' expression as 1st column and expression of 'rest' in the second column while some has the opposite order.
for(i in c(1,3)) {
	df[[i]][,3] <- df[[i]][,2]/df[[i]][,1]
}
for(i in c(2,4:7)) {
	df[[i]][,3] <- df[[i]][,1]/df[[i]][,2]
}
for(i in 1:7) {
	df[[i]][,1:2] <- NULL
}
nam_vector_ratio <- list()
for(i in seq(1:7)) {
	nam_vector_ratio[[i]] <- paste(colnames(df[[i]])[1],"_Ratio")
}
nam_vector_intensity <- list()
for(i in seq(1:7)) {
	nam_vector_intensity[[i]] <- c(levels(mono1@ident)[[i]],paste(colnames(df[[i]])[1],"_Ratio"))
}

##vector for column names in the data frame
vector_names <- c(nam_vector[[1]], nam_vector[[2]], nam_vector[[3]], 
									nam_vector[[4]], nam_vector[[5]], nam_vector[[6]], nam_vector[[7]])
##Create a dataframe with Average expression as 1st column and and expression ratio as the second ##column for each object.
mono1_IPA_df <- cbind(df[[1]],df[[2]],df[[3]],df[[4]],df[[5]],df[[6]],df[[7]])

length(mono1_IPA_df)
colnames(mono1_IPA_df) <- vector_names

IPA_subset <- subset.data.frame(x, subset = "gene", select = unique(mono1_markers$gene))`
