### ISSUE TITLE
Prevent AddModuleScore() adding numbers to the ends of module names, or add argument to the function to toggle this

### ISSUE THREAD

**Issue by wudustan** [satijalab/seurat#9030]
Currently, AddModuleScore has the following functionality:

    seurat <- AddModuleScore(seurat, features = list(set3, set24), name = c("set3", "set24")

    names(seurat@meta.data)
    > ..., set31, set242

Please either remove the automatic addition of a number to the end of the module names or allow an argument in the function to specify how the function behaves. When projecting a large set of modules, it's a waste of time removing the number suffix.

Cheers

**Comment by zskylarli** [comment]
Hi @wudustan, 

Thanks for the suggestion 🙂

Unfortunately, our bandwidth is limited so we won’t be able to include this in our roadmap at this time. We’ll circle back to this once our resources allow, or feel free to make a PR to fix this issue. 

We cannot overstate how much we appreciate your input and we encourage you to keep sharing your ideas. If you have other ideas, please don’t hesitate to let us know.
