### ISSUE TITLE
Calculate image features such as RGB or intensity of Visium HD bins

### ISSUE THREAD

**Issue by sunyumail93** [satijalab/seurat#9036]
Hello, I wonder if Seurat supports some advanced analysis of the images in the Visium HD data? I have fluorescence staining images aligned with the data and I only wanted to select bins that have positive staining. Maybe I am looking for some functions similar to this: https://squidpy.readthedocs.io/en/stable/api/squidpy.im.calculate_image_features.html, i.e. for each bin, it generates a metric such as the fluorescence intensity of that bin so I can do further subsetting of the bins. I appreciate if you could provide some suggestions of how to achieve this in Seurat. Thank you!

**Comment by zskylarli** [comment]
Hi @sunyumail93 ,

Thanks for the suggestion! 🙂 This is a very cool feature and we're glad you're testing our VisiumHD functionalities as well. Unfortunately, our bandwidth is limited so we won’t be able to include this in our roadmap at this time. We’ll circle back to this once our resources allow. 

We cannot overstate how much we appreciate your input and we encourage you to keep sharing your ideas. If you have other ideas, please don’t hesitate to let us know.

**Comment by sunyumail93** [comment]
Thank you for your response!
