### ISSUE TITLE
Fov in Visium data/ BuildNicheAssay

### ISSUE THREAD

**Issue by odunola26** [satijalab/seurat#9047]
Hello,

Please , i am trying to run "BuildNicheAssay" on my 10x visium data, but I am having error with the Fov, please can you guide me on how i can access this from my seurat object. here is my code :

Extract spatial coordinates from the centroids object
coords <- sample39_obj@images$slice1@boundaries$centroids@coords
coords

Ensure the coordinates matrix has proper row names
rownames(coords) <- sample39_obj@images$slice1@boundaries$centroids@cells

Create the FOV list with the correct format
fov <- list(FOV = coords)

Run BuildNicheAssay
sample39_obj <- BuildNicheAssay(
object = sample39_obj,
fov = fov,
group.by = "predicted.celltype",
assay = "niche",
cluster.name = "niches",
neighbors.k = 30,
niches.k = 5
)

HERE the error message i got:
Error in `object[[fov]]`:
! 'i' must be a character vector
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `object[[fov]]`:
! 'i' must be a character vector

Thank you.
Odunola

**Comment by dcollins15** [comment]
The `fov` parameter just takes the _name_ of the `FOV` instance stored in your object - in your case, you just need to do:

```R
sample39_obj <- BuildNicheAssay(
    object = sample39_obj,
    fov = "fov",
    group.by = "predicted.celltype",
    assay = "niche",
    cluster.name = "niches",
    neighbors.k = 30,
    niches.k = 5
)
```

**Comment by odunola26** [comment]
Thanks @dcollins15 

fov didn´t work. I tried with 'slice1' and it worked.

thank you.
