### ISSUE TITLE
Differences in the re-normalization of a public Seurat Object 

### ISSUE THREAD

**Issue by evaesquinas** [satijalab/seurat#9054]
I have downloaded a public seurat object which is already normalized. Due I want to focus on one particular subset of cells and I would like to re-cluster them, I will have to normalize. 
However, I realised that if I normalize the object again (the complete one that I downloaded), the normalization is not the same. 

- Is it because of the Seurat version? I am aware the DGE analysis can change depending on the Seurat version, but, I have not seen anything related to the normalization (_if there is any post/reference about this, send them to me please if you don't mind_). Or... maybe could it be because of the normalization method and/or the scale factor used?

    - Authors have written in the article that they have used Seurat 3.1.3 (although the Seurat object that they have provided seems to be created by Seurat 5.0.0 if I run `seu_downloaded@version`, _-something that I don't understand to be honest-_). 
  - I currently have Seurat 4.1.3.

- Could it be that I should use select the raw counts in the function `NormalizeData()` to normalize it myself again? 
I have tried this but it doesn't work.

```
seu_downloaded <- Seurat::NormalizeData(seu_downloaded,
                     normalization.method = "LogNormalize",
                     scale.factor = 10000, assay = assays[["RNA"]]@counts)
```

Since I would like to focus on one subset of cells and therefore, re-cluster cells again (to study the group in deep) and do everything that is related with the process (normalization, scale, etc again), I am worried to have inconsistency in the normalization of the full seu object that I have downloaded and my subsetted/re-clustered object (done by me).

**Is it recommended to normalize again all the downloaded Seurat objects from public data regardless if they are already normalized?** 

Any feedback will be really appreciated.

Thanks very much in advance

**Comment by Gesmira** [comment]
Ideally, you would normalize your objects in the same way. If your object already contains raw counts in the counts layer (in Seurat v5, you would access these like so: `seu_download[["RNA"]]$counts`), then `NormalizeData` will by default create a new data layer by normalizing the counts layer. You don't always have to normalize public data again, but in this case since you don't know how the data was originally normalized, I would recommend doing so.
