### ISSUE TITLE
Downsampling in rPCA integration

### ISSUE THREAD

**Issue by lizchcase** [satijalab/seurat#9056]
I am working on integrating multiple datasets together across a few species. Some are datasets that I've collected, and some are publicly available. Because of this, the sequencing saturation is going to be different for the different datasets, and I'm not sure how that will affect the integration as well as downstream analysis. 

Does anyone know: 
1) Does Seurat rPCA integration take differences sequencing saturation into account?
2) Is it necessary to downsample such that all datasets have the same reads/cell? If so, how would I go about doing this?

Thanks!

**Comment by longmanz** [comment]
Hi,
Thank you for using Seurat. rPCA does not take seq-saturation into account, but you should not need to down-sample your data. You may consider using CCA integration (https://satijalab.org/seurat/articles/integration_introduction) if you think the seq-saturation leads to strong batch effects. You may consider posting this to https://github.com/satijalab/seurat/discussions for a more general discussion with our community.
