### ISSUE TITLE
Exporting scaled data from Seurat Object

### ISSUE THREAD

**Issue by Close-your-eyes** [satijalab/seurat#906]
Dear Satijalab-Team and dear everyone else,

there have been a similar questions before (https://github.com/satijalab/seurat/issues/418 and https://github.com/satijalab/seurat/issues/319) but the answers weren't sufficient for me. Maybe because my aim is a little different ...
I would like to visualize what happens to my data set by Seurat's normalization and scaling procedures.

So, when I export the `object@data` before and after normalization as a data.frame these frame are not identical. Good. When I subsequently scale the data and export `object@data` again as data.frame it remains identical. What is generated though is the `@scale.data` slot within the object.

So, how can I export a scaled data matrix from the Seurat Object in order to visualize changes (before and after scaling) with the help of other packages?

Even if the information on scaling are not inserted into the `@data` slot, they must be used somehow during dimension reduction (pca and tsne), right? Otherwise they would be needless. 
The `@data` and `@scale.data` may be combined for calculation. But how? Could the same calculation procedure be used to export a scaled data matrix?

**Comment by Close-your-eyes** [comment]
Based on another issue I may have learned that tSNE and PCA are solely calculated based on the @scale.data slot. So, if I want to know what happens to my data by scaling I could just export the @scale.data slot as data.frame.

**Comment by ccasar** [comment]
I'm not sure what you are asking, but the explanation of the various data slots of the Seurat object in the [Seurat FAQs](https://satijalab.org/seurat/faq#7-how-is-data-stored-within-the-seurat-object-what-is-the-difference-between-rawdata-data-and-scaledata) might give you a better understanding of the matrices.
