### ISSUE TITLE
MT genes when using ensembl genes 

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#9065]
Hello, I would appreciate it if you help how to grep MT genes if I created my object using ensembl  ids.

Another question I have,  in general how to have both ( gene symbols and ensembl ids) in my object  and use either when needed. As for some downstream application I will need ensembl genes and for other I will need gene names. Thank you so much.

this is how i loaded my h5 files

sample <- Read10X_h5("/PATH/filtered_feature_bc_matrix.h5", use.names = FALSE)

**Comment by longmanz** [comment]
Hi, 
Gene IDs must be unique and we do not support having gene symbols and ensembl ids the same time. 
You can download the ensemble IDs to HGNC table at https://www.genenames.org/download/custom/. You can use that to obtain the ensembl IDs for your MT genes

**Comment by samuel-marsh** [comment]
@Flu09 as fyi I have all ensembl ids built in for all supported species in scCustomize for mitochondrial and ribosomal genes (and other gene lists).  See https://samuel-marsh.github.io/scCustomize/reference/Add_Cell_QC_Metrics.html

For ensembl id support for additional QC gene lists (and for adding hemoglobin %) use the 2.2.0 in dev release branch.

Best,
Sam
