### ISSUE TITLE
logFC Standard Error

### ISSUE THREAD

**Issue by dylanmr** [satijalab/seurat#907]
Is there anyway to extract the logfc standard error from the deseq2 test within seurat? I havent seen it in the results object.

thanks!

**Comment by satijalab** [comment]
We do not support this at the moment, but in my opinion, the error models that are learned by DESeq may not be applicable to the sparsity of scRNA-seq data, so I am not certain if the SE estimates could be interpreted with the same reliability/intepretability as in bulk assays
