### ISSUE TITLE
Conversion from h5ad to Seurat object 

### ISSUE THREAD

**Issue by AnnaAntonatouPap** [satijalab/seurat#9072]
Hello, 

I have an atlas in h5ad format  but because I am more familiar with r i want to convert it in seurat object. 
I am using the following code to do that  
```
 data <-Convert("annotated_filtered.h5ad", dest = "h5seurat", overwrite = TRUE) 
 data <- LoadH5Seurat("annotated_filtered.h5seurat")
```

but while loading i have the following error 
```
Validating h5Seurat file

Initializing RNA with data

Adding counts for RNA

Adding feature-level metadata for RNA

Error: Too many values for levels provided
Traceback:

1. LoadH5Seurat("/fast/AG_Robson/anna/atlas_limb/PengHe_Teichmann_2023/MouseAllData_annotated_filtered.h5seurat")
2. LoadH5Seurat.character("/fast/AG_Robson/anna/atlas_limb/PengHe_Teichmann_2023/MouseAllData_annotated_filtered.h5seurat")
3. LoadH5Seurat(file = hfile, assays = assays, reductions = reductions, 
 .     graphs = graphs, neighbors = neighbors, images = images, 
 .     meta.data = meta.data, commands = commands, misc = misc, 
 .     tools = tools, verbose = verbose, ...)
4. LoadH5Seurat.h5Seurat(file = hfile, assays = assays, reductions = reductions, 
 .     graphs = graphs, neighbors = neighbors, images = images, 
 .     meta.data = meta.data, commands = commands, misc = misc, 
 .     tools = tools, verbose = verbose, ...)
5. as.Seurat(x = file, assays = assays, reductions = reductions, 
 .     graphs = graphs, neighbors = neighbors, images = images, 
 .     meta.data = meta.data, commands = commands, misc = misc, 
 .     tools = tools, verbose = verbose, ...)
6. as.Seurat.h5Seurat(x = file, assays = assays, reductions = reductions, 
 .     graphs = graphs, neighbors = neighbors, images = images, 
 .     meta.data = meta.data, commands = commands, misc = misc, 
 .     tools = tools, verbose = verbose, ...)
7. AssembleAssay(assay = assay, file = x, slots = assays[[assay]], 
 .     verbose = verbose)
8. as.data.frame(x = assay.group[["meta.features"]], row.names = features)
9. as.data.frame.H5Group(x = assay.group[["meta.features"]], row.names = features)
10. as.factor(x = x[[i]])
11. as.factor(x = x[[i]])
12. stop("Too many values for levels provided", call. = FALSE)
````

Do you have any ideas how to solve it ?
Anna

**Comment by lizchcase** [comment]
Hi Anna,

This is the code I've used successfully to convert from h5ad to Seurat: 

```
library(Seurat)
library(reticulate)
library(anndata)

data <- read_h5ad("file_path/file.h5ad")
data <- CreateSeuratObject(counts = t(as.matrix(data$X)), meta.data = data$obs,min.features = 500, min.cells = 30)
saveRDS(data,"file_path/file.rds")
```

Hope that helps!

**Comment by zskylarli** [comment]
Hi, thank you for reporting this issue! Some of our functions for interoperability between objects are currently not fully supported in v5; until then, we recommend you use @lizchcase's suggestion to extract the counts, obs, and variables manually and create a Seurat object from scratch. You will be able to add in the normalized matrix as a data layer as well, and also set VariableFeatures() if needed. Let me know if you have any further questions!

**Comment by itscharliemu** [comment]
> Hi Anna,
> 
> This is the code I've used successfully to convert from h5ad to Seurat:
> 
> ```
> library(Seurat)
> library(reticulate)
> library(anndata)
> 
> data <- read_h5ad("file_path/file.h5ad")
> data <- CreateSeuratObject(counts = t(as.matrix(data$X)), meta.data = data$obs,min.features = 500, min.cells = 30)
> saveRDS(data,"file_path/file.rds")
> ```
> 
> Hope that helps!


Hi!

I am also trying to convert from h5ad to Seurat. However, after running your code without any error or warning messages, my data$X is NULL.

Do you have any ideas of why is this? Thanks!

**Comment by ShanshanHe-44** [comment]
> Hi Anna,
> 
> This is the code I've used successfully to convert from h5ad to Seurat:
> 
> ```
> library(Seurat)
> library(reticulate)
> library(anndata)
> 
> data <- read_h5ad("file_path/file.h5ad")
> data <- CreateSeuratObject(counts = t(as.matrix(data$X)), meta.data = data$obs,min.features = 500, min.cells = 30)
> saveRDS(data,"file_path/file.rds")
> ```
> 
> Hope that helps!

Thanks! Very helpful since I got endless error with 'Convert'. This way is really nice!

**Comment by pedrocastillorosique** [comment]
> Hi Anna,
> 
> This is the code I've used successfully to convert from h5ad to Seurat:
> 
> ```
> library(Seurat)
> library(reticulate)
> library(anndata)
> 
> data <- read_h5ad("file_path/file.h5ad")
> data <- CreateSeuratObject(counts = t(as.matrix(data$X)), meta.data = data$obs,min.features = 500, min.cells = 30)
> saveRDS(data,"file_path/file.rds")
> ```
> 
> Hope that helps!

Thank you Anna, it also worked for me. I had spot annotation for my data and converting .h5ad to .h5seurat wasn't working neither for me. In case you have meta.data it is such a good option.
