### ISSUE TITLE
Extracting the proportion of variance by confounding factors in latent.vars for DEA and using RNA/SCT Assay

### ISSUE THREAD

**Issue by Rahul1711arora** [satijalab/seurat#9088]
Hi, 

Thank you so much for Seurat and its functionalities. I have a question about the DE analysis. When using LR/NegBinom/MAST, etc we can set the confounding variables to regress our for using the latent.vars argument. Is this correct? And if it is, when we add the confounding factors, how can we extract the information about the variance being contributed by each factor in this argument? 

I also wanted to ask that when I ran the same data a few months ago with the same code, using the SCT model for DEA, I got a list of around 2000 differentially expressed genes. But when I ran the same analysis 2 weeks ago, I only got 81 genes. I checked that the Seurat version I used in both instances was v4.4. So, I'm not sure why these numbers are different. On the other hand, when I use the RNA assay, I get around 3000 DE genes. 

What would be your recommendation about using RNA/SCT assay? And if needed then switching to a newer version of Seurat? 

Best,
Rahul

**Comment by dcollins15** [comment]
Hi @Rahul1711arora,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

In terms of the inconsistent DE genes, it's impossible to diagnose without more information. 

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
