### ISSUE TITLE
FindMarkers with downsampling

### ISSUE THREAD

**Issue by ogarmar3** [satijalab/seurat#909]
Hi,
I'm using FindMarkers to get differentially expressed genes between two conditions, for each cluster.
Since each cluster has a different number of cells, I'm using downsampling to "normalize". I run FindMarkers multiple per cluster and then average the results to get a more accurate logFC value.

However, the results I get with this code don't match what I get without downsampling. I don't know if the mistake is in the first loop (Find Markers) or in the second one (average dataframes).

Any hint will be highly appreciated!

Thanks,
Marcos

```R
all.clusters<-list(CUX2LAMP5, CUX2COL5A2, RORBGAL, RORBPCP4, ROBO3, THEMIS, NR4A2CTGF)
cluster.names<-list("CUX2LAMP5", "CUX2COL5A2", "RORBGAL", "RORBPCP4", "ROBO3", "THEMIS", "NR4A2CTGF")
for (i in 1:7){
  data.list <- mget(ls(pattern="M_\\d+"))
  for (j in 1:20){
    #do DGE of all mEx clusters x10
    cluster <- all.clusters[[i]]
    #sampled.cells <- sample(cluster@cell.names, size=1293, replace=F)
    #cluster <- SubsetData(cluster, cells.use = sampled.cells)
    cluster <- SetAllIdent(object = cluster, id = "TAU")
    random.value<-sample(1:500, 1)
    cluster_markers <- FindMarkers(object = cluster, ident.1 = "MAP", ident.2 = "TAU", only.pos = FALSE, min.pct=0.1, logfc.threshold=FALSE, random.seed=random.value, max.cells.per.ident=458)
    data.list[[j]] <- cluster_markers
    #assign(paste(cluster.names[[i]], "_permut_markers",j, sep=""), cluster_markers)
    #cbind(paste(cluster.names[[i]], "_permut_markers", sep=""), cluster_markers)
    #append results of DGE in a dataframe
  }
  binded <- abind(data.list, along = 3)
  #assign(paste(cluster.names[[i]], "_permut_markers.avr", sep=""), rowMeans(binded, dims = 2))
  averaged <- rowMeans(binded, dims = 2)
  write.csv(averaged, paste(cluster.names[[i]], "_permut_markers.csv", sep=""))
}

```

**Comment by ogarmar3** [comment]
To better explain the issue:

I use the whole dataset to get the initial DEGs for each cluster (2 conditions). Then I filter for genes with pval_adj<0.05. Clusters with more cells will have longer lists and lower p_values. If I make a heatmap with those logFC values or with directional p_values, the hierarchical relationships between clusters will respond to dataset size instead of differential gene expression profile. Clusters with a similar number of cells appear closely related.

That's why I want to "normalize" those lists, so I have no differences driven by the dataset size of each cluster.
For heatmaps of logFC maybe I could use just the top genes, the same number of genes for all clusters? If I want to plot directional p_values I need to do something else to "normalize" the values.

**Comment by satijalab** [comment]
We do not recommend this procedure. While it is true that different clusters will have differential power to detect DE genes as a function of cluster size, repeated subsampling from the same data and then averaging the results to perform DE is not recommended.
