### ISSUE TITLE
Seurat::FindAllMarkers return nothing

### ISSUE THREAD

**Issue by tomyputw** [satijalab/seurat#9091]
I search and do not find similar question, but I think this problem is normal.

> SM2 <- seurat.SM2
> SM2.markers <- FindAllMarkers(SM2)
Calculating cluster pbmc1
Warning: No layers found matching search pattern provided
Calculating cluster pbmc2
Warning: No layers found matching search pattern provided
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing pbmc1 versus all:
	在为'rowSums'函数选择方法时评估'x'参数出了错: subscript out of bounds 
Warning: When testing pbmc2 versus all:
	在为'rowSums'函数选择方法时评估'x'参数出了错: subscript out of bounds 
Warning messages:
1: Layer 'data' is empty 
2: Layer 'data' is empty 
3: Layer 'data' is empty 
4: Layer 'data' is empty 
> #subscript out of bounds 
> SM2.markers
data frame with 0 columns and 0 rows

**Comment by igrabski** [comment]
Based on the warning messages, it seems that your Seurat object is missing the `data` layer. Please make sure you have run `NormalizeData()` (or alternatively `SCTransform()` if you are using that workflow) prior to running `FindAllMarkers()`.

**Comment by tomyputw** [comment]
@igrabski thank you very much. I make a obvious mistake
