### ISSUE TITLE
Impossible to open the search panel

### ISSUE THREAD

**Issue by isardds** [satijalab/seurat#9093]
Hello,
Since several days, when I open a map, I edit it and try to open the search panel (Ctrl+F), nothing appear.
Same thing if I used the context menu.
In the developer console of the browser, I can see this message when I try to open the search panel:

```
Uncaught TypeError: this.map is undefined
    open umap.controls.d358ded16c11.js:250
    search umap.0f9599c8a7b5.js:509
    globalShortcuts umap.0f9599c8a7b5.js:201
    handler DomEvent.js:108
[umap.controls.d358ded16c11.js:250:4](https://umap.openstreetmap.fr/static/umap/js/umap.controls.d358ded16c11.js)
Erreur dans les liens source : NetworkError when attempting to fetch resource.
URL de la ressource : moz-extension://32484317-ee19-49c8-92fa-04c1d24cd91a/model/static/DOMPurify/purify.min.js
URL du lien source : purify.min.js.map
```

I can see this issue on Linux with Firefox 127.0.2 and Brave 1.67.123 (Chromium 126.0.6478.126).

Thanks for your help.

**Comment by dcollins15** [comment]
I think you may be a little lost, friend — this issue appears to be related to the [uMap](https://umap.openstreetmap.fr/en/) tool so I think you may have posted here by mistake. 

Best of luck resolving your issue 😃
