### ISSUE TITLE
PrepSCTIntegration() errors

### ISSUE THREAD

**Issue by Natafui** [satijalab/seurat#9094]
I've seen a few older posts about this and have tried to apply those suggestions to my analysis, but am still getting errors. I have datasets from two different studies that I am attempting to integrate. Both have been internally batch-corrected across samples using Harmony integration. I have also tried to run these using both SCTransform([object], return.only.var.genes = TRUE) and SCTransform([object],return.only.var.genes = FALSE). 

Objects set to TRUE result with this:
filt_both_var <- list(filt_MI_var = filt_MI_var, filt_Wei_var = filt_Wei_var)
filt_features_var <- SelectIntegrationFeatures(filt_both_var)
filt_features_var <- PrepSCTIntegration(filt_both_var, anchor.features = filt_features_var)
  |                                                  | 0 % ~calculating  Error in .subscript.2ary(x, , j, drop = drop) : subscript out of bounds
In addition: Warning message:
In LayerData.Assay5(object = object[[umi.assay]], layer = layer,  :
  multiple layers are identified by counts.1 counts.2
 only the first layer is used

Objects set to FALSE result with this:
filt_both_all <- list(filt_MI_all = filt_MI_all, filt_Wei_var = filt_Wei_all)
filt_features_all <- SelectIntegrationFeatures(filt_both_all)
filt_features_all <- PrepSCTIntegration(filt_both_all, anchor.features = filt_features_all)
  |                                                  | 0 % ~calculating  Warning: Residuals not computed for the following requested features: RGS1, CXCL10, TREM2, CD69, OSM, IFITM1, FOLR2, NBL1, TNFSF13, COX4I2, BST2
Error in scale.data[anchor.features, ] : subscript out of bounds

Not sure how to fix this or if there is a different way I should be preparing each object. I followed the SCTransformed objects vignette by Seurat.

**Comment by igrabski** [comment]
Hi, it seems you may be following an older workflow -- for integration with `SCTransform`, we now have a single command `IntegrateLayers()` that can be called with `normalization.method` set to `SCT`, as shown in [this vignette](https://satijalab.org/seurat/articles/integration_introduction#perform-integration-with-sctransform-normalized-datasets). In addition, please make sure your versions of `Seurat` and `SeuratObject` are up-to-date. Please feel free to re-open this issue if you are still running into errors with this updated workflow!

**Comment by Natafui** [comment]
What if it's two separate seurat objects? I assume `IntegrateLayers()` is only for layers within the same object, rather than two separate objects?

**Comment by Natafui** [comment]
> Hi, it seems you may be following an older workflow -- for integration with `SCTransform`, we now have a single command `IntegrateLayers()` that can be called with `normalization.method` set to `SCT`, as shown in [this vignette](https://satijalab.org/seurat/articles/integration_introduction#perform-integration-with-sctransform-normalized-datasets). In addition, please make sure your versions of `Seurat` and `SeuratObject` are up-to-date. Please feel free to re-open this issue if you are still running into errors with this updated workflow!

What if it's two separate seurat objects? I assume IntegrateLayers() is only for layers within the same object, rather than two separate objects?

**Comment by Natafui** [comment]
I should also mention that the biosample-level integration that was performed  prior to cross-study integration used HarmonyIntegration() as the method, which doesn't have a "normalization.method" argument.

**Comment by igrabski** [comment]
In our current integration workflows, we recommend operating within a single object where the datasets to be integrated are present as separate layers, rather than maintaining the datasets as separate objects. For integrating with Harmony, the `normalization.method` doesn't need to be specified since Harmony operates on the PCs/dimension reduction itself.
