### ISSUE TITLE
FeaturePlot Error - Problem variables: 'colour'

### ISSUE THREAD

**Issue by KerriganBlake** [satijalab/seurat#91]
We're running Seurat_1.4.0.8 and getting an error that we haven't been able to trace. When we run FeaturePlot(data, c("gene1","gene2")) we get the message listed below. 

```
> FeaturePlot(pbmc, "S100A4")
Error: Each variable must be a 1d atomic vector or list.
Problem variables: 'colour'
```

This error does not seem to occur in Seurat_1.4.0.6 as we've tried running the same code there. Further, we're able to plot these genes with VlnPlot without issue.

**Comment by andrewwbutler** [comment]
Strange. Not able to reproduce that on my end. The most recent Seurat version is 1.4.0.16. Can you try updating to that? Also, make sure that ggplot2 is current as well.

**Comment by LupeG** [comment]
We updated the recommended settings to  to Seurat_1.4.0.16 and ggplot2_2.2.1.9000. We are still experience the above-mentioned problem.

Running the line: 
FeaturePlot(pbmc, c("MS4A1", "GNLY"),cols.use = c("grey","blue"))

We get the following error:
Error: Column `colour` must be a 1d atomic vector or a list

Can this be a problem with R version 3.3.3 (2017-03-06). A colleague does not experience this problem running R version 3.3.2.

**Comment by LupeG** [comment]
I was able to resolve the issue by using ColorBrewer:

install.packages("RColorBrewer")
library(RColorBrewer)
FeaturePlot(pbmc, c("MS4A1", "GNLY"),cols.use = (brewer.pal(3,"Blues")))
