### ISSUE TITLE
guide_legend problem when using SpatialPlot 

### ISSUE THREAD

**Issue by onmyojiyys** [satijalab/seurat#9101]
When using the spatialplot function to create spatial images, the icons in the legend are quite small. When adjusting the size of the icons with the guide_legend function, if there are more than two slices, only the legend of the last slice can be modified. Is there a way to resolve this issue?

SpatialPlot(scRNA, cols=colours, label = TRUE, label.size = 3, ncol = 2) + guides(fill = guide_legend(override.aes = list(size=4)))

![image](https://github.com/satijalab/seurat/assets/58845320/ee78dc41-c940-431b-a1c0-4604cd7cfb71)

**Comment by aladyeva-research** [comment]
Hi @onmyojiyys 
I think this is the default behavior for multi-panel plots. You can use "&" instead of "+" to apply transformation to all panels.
`SpatialPlot(scRNA, cols=colours, label = TRUE, label.size = 3, ncol = 2) & guides(fill = guide_legend(override.aes = list(size=4)))`

**Comment by onmyojiyys** [comment]
> Hi @onmyojiyys I think this is the default behavior for multi-panel plots. You can use "&" instead of "+" to apply transformation to all panels. `SpatialPlot(scRNA, cols=colours, label = TRUE, label.size = 3, ncol = 2) & guides(fill = guide_legend(override.aes = list(size=4)))`

It works for me. Thanks.
