### ISSUE TITLE
Is AggregateExpression() function reflect harmony batch correction?? 

### ISSUE THREAD

**Issue by ilovegreentea** [satijalab/seurat#9105]
Q1. Does the aggregate expression() function reflect harmonic batch correction?  

Q2. Otherwise do I have to use the batch correction method used by regular bulk-seq?

Q3. how to i extract data layer when i use AggregateExpression() function, It always show count layer.

**Comment by dcollins15** [comment]
Assuming that I've understood what you're asking:

1. When running `AggregateExpression` on an integrated assay then it should reflect any batch correction that was performed, assuming you've specified the correct `assays` value. `AggregateExpression` does not perform any batch correction itself.
2. Yes.
3. `AggregateExpression` is only intended to be run on the raw counts. You _could_ call `PseudobulkExpression` using `method="aggregate"`.
