### ISSUE TITLE
Integrating samples from demultiplexing with hashtag oligos to other samples sequenced individually

### ISSUE THREAD

**Issue by adhisadi** [satijalab/seurat#9107]
I have four samples multiplexed together with hashtag oligos. I have other over 50 samples which were sequenced individually.  I need to integrate all the samples for further analysis. How do we integrate multiplexed and individually sequenced samples?
My idea would be to subset each sample from multiplexed data.  I would need the sample IDs in the multiplexed samples in orig.ident metadata, so maybe that way I can separate with the subset function. 

P.S if it helps: I am following [this vignette](https://satijalab.org/seurat/articles/hashing_vignette) for demultiplexing. I want to Normalize the demultiplexed samples like my other individually sequenced samples and then integrate them all.

**Comment by dcollins15** [comment]
Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. I'll be happy to help resolve https://github.com/satijalab/seurat/issues/9108 once you're able to provide the requested info 🙂
