### ISSUE TITLE
TSNE (UMAP) plots in a trellis plot

### ISSUE THREAD

**Issue by joonlee3** [satijalab/seurat#911]
Hi,

   I am trying to generate sample-specific TSNE(UMAP) plots in a trellis plot by using Seurat package as shown in the figure attached below. Is there any function built in Seurat for this purpose? Please let me know. Thanks.

Joon

![image](https://user-images.githubusercontent.com/7217161/47945663-df465c80-ded9-11e8-9cd9-8d48ca053665.png)

**Comment by mojaveazure** [comment]
Hi Joon,

This functionality has been implemented in the `split.by` argument to DimPlot and currently available in Seurat v3.0 - alpha; please see [here](https://satijalab.org/seurat/install.html#prerelease) for instructions on installing Seurat v3.0, keeping in mind this is a prerelease version of the software so bugs are expected. For more information on Seurat v3.0, please see [here](https://satijalab.org/seurat/).
