### ISSUE TITLE
RunSLSI error

### ISSUE THREAD

**Issue by myylee** [satijalab/seurat#9118]
Hi Seurat team,

Thanks for the great package.

I have a large multiome dataset and I want to annotate a query snATAC-seq dataset with the multiome reference. Thus, I'm running the line below.

reference = RunSLSI(reference, assay = 'ATAC', graph = 'wsnn6Run2', n=30)

However, it crushes with the error shown below:
<img width="1252" alt="Screen Shot 2024-07-12 at 2 30 05 PM" src="https://github.com/user-attachments/assets/a2128557-323e-4bb5-8370-8ac5f0397857">

For the multiome dataset, there are 117122 cells, so I believe the error happened when trying to build a cell-cell similarity kernel of 117122 x 117122.

Any recommendations on how to solve this?

On the other hand, I also ran RunSPCA with the same graph, trying to learn a supervised projection to annotated scRNA-seq data and that step succeeded. Why did this work but not RunSLSI?

Any help is greatly appreciated!

Michelle Lee

**Comment by rsatija** [comment]
This may be a memory limitation, which sometimes can be more challenging for ATAC due to the much larger feature space. Are you able to get RunSLSI to work with a smaller subset of cells? You can also try reducing the number of features used when running RunSLSI.
