### ISSUE TITLE
No highly variable genes after using Findclusters

### ISSUE THREAD

**Issue by Cheryl312518** [satijalab/seurat#912]
Hi, all!

Here's a question that needs your help. 

Totally around 10000 cells have been processed which could be separated into 7 clusters. But using "Findclusters" there're no highly variable genes in first two clusters. It's really a big problem because these two clusters compose a large proportion of the whole profile. 

Do you think if I adjust parameters, it's possible to find the highly variable genes and which parameters? Or this profile are more possible due to the sample itself?  

Thanks for your reading and looking forward to your reply.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/44717765/47947617-04c77a80-df5b-11e8-9bc8-aac37ca4b66d.png">

**Comment by satijalab** [comment]
Of course the DE genes that are present will depend on your sample. One possibility is that clusters 0 and 1 are not distinct, and should be merged together. Another possibility is that the markers between them are subtle, and are not captured when running FindAllMarkers. You could run a specific FindMarkers command comparing clusters 0 and 1 to explore specific differences between these two groups
