### ISSUE TITLE
as.SingleCellExperiement() incompatibility with Seurat V5 objects

### ISSUE THREAD

**Issue by ondina-draia** [satijalab/seurat#9121]
Hello,

I encounter a problem with latest version of the Seurat object with V5 Assays and normalized with SCTransform, when I try to convert in SingleCellExperiment format, I get the following error:

`P30.N.sce <- as.SingleCellExperiment(obj$P30.N)`

_Error in `GetAssayData()`:_
_! GetAssayData doesn't work for multiple layers in v5 assay_

I tried to find a workaround to this trouble by manually creating the SingleCellExperiment object manually:

```
# Convert to V3/4 assay
obj$P30.N <- NormalizeData(obj$P30.N, assay = "RNA")
obj$P30.N[["RNA3"]] <- as(object = obj$P30.N[["RNA"]], Class = "Assay")

# Raw data stored in RNA3 as counts
counts <- GetAssayData(obj$P30.N, assay = "RNA3", slot = "counts")

# Extract normalized counts
#normalized_counts <- GetAssayData(obj$P30.N, assay = "RNA3", slot = "data")

# MetaData
meta_data <- obj$P30.N@meta.data

# Create SingleCellExperiment object
P30.N.sce <- SingleCellExperiment(
  assays = list(counts = counts, logcounts = normalized_counts),
  colData = meta_data
)

# Extract PCA data
pca_coords <- Embeddings(obj$P30.N, reduction = "pca")

# Add PCA coordinates to SingleCellExperiment
reducedDim(P30.N.sce, "PCA") <- pca_coords

# If there are UMAP embeddings, extract them:
if ("umap" %in% names(obj$P30.N@reductions)) {
  umap_coords <- Embeddings(obj$P30.N, reduction = "umap")
  reducedDim(P30.N.sce, "UMAP") <- umap_coords
}

```
It seems to work but some of the results I get are looking really odd.

What should I do? Is there a better solution than this? Did I make an error somewhere ?

**Comment by rsatija** [comment]
I'm not entirely sure why the converter function isn't working but would check two thigs

1. Does your RNA assay have multiple layers? If so, you should join them before conversion
2. Do you get this error prior to running SCTransform? Again, make sure your RNA assay does not have multiple layers. 

Those checks should fix your issue but regardless, the code you posted on manual object creation looks correct.
