### ISSUE TITLE
Supervised clustering with a subset of cells in combination with SCTransform

### ISSUE THREAD

**Issue by kenneditodd** [satijalab/seurat#9122]
Hello,

In my current dataset I have a cluster with ~30k T/NKT-like cells. With a high cluster resolution I can start to see and define subpopulations. However, I want to recluster the T/NKT-like cells and then annotate the subpopulation. My first reclustering pass resulted in a blob of a UMAP with no real distinct clusters. So, I am trying to use a gene list of known markers to do a supervised reclustering. Additionally, I am integrating data since the samples like to cluster by sample vs cell type.

I have looked at the recommendations from issue #2539 and have some follow up questions when using SCTransform. My current workflow is as follows.
```
# subset to NKT-like/T cells
keepCells <- human.annotated@meta.data[,"annotated_clusters"] %in% "T/NKT-like cells"
meta <- human.annotated@meta.data[keepCells,]
counts <- LayerData(obj, assay = "RNA", layer = "counts")[,keepCells]
tcells <- CreateSeuratObject(counts, meta.data = meta)
remove(human.annotated,meta)

# filter lowly expressed genes
counts <- GetAssayData(object = tcells, layer = "counts")
nonzero <- counts > 0  # produces logical
keep <- Matrix::rowSums(nonzero) >= 10  # sum the true/false
counts.filtered <- counts[keep,] 
tcells <- CreateSeuratObject(counts.filtered, meta.data = tcells@meta.data)

# sctransform, pca, harmony
tcells[["RNA"]] <- split(tcells[["RNA"]], f = tcells$sample)
t.nk.markers <- c("CD3D", "CD3E", "CD3G", "CD4", "CD8A", "CD8B", "TRAC", "TRDC", "NKG7", "KLRD1", "KLRF1", "GNLY", "PRF1", "GZMB", "XCL1", "XCL2", "NCAM1")
tcells <- SCTransform(tcells, 
                      verbose = FALSE, 
                      residual.features = t.nk.markers)
tcells <- RunPCA(tcells, assay = "SCT")
tcells <- IntegrateLayers(object = tcells,
                          method = HarmonyIntegration,
                          orig.reduction = "pca",
                          assay = "SCT",
                          features = t.nk.markers)

# choose dims
tcells@reductions$harmony@stdev <-
  apply(tcells@reductions$harmony@cell.embeddings, 2, sd)
ElbowPlot(tcells,
          reduction = "harmony") +
  geom_vline(xintercept = 6, linetype = "dashed", color = "red")

# umap
tcells <- RunUMAP(tcells,
                  dims = 1:6,
                  reduction = "harmony",
                  n.components = 3)
```

After this workflow I still have one blob for my UMAP.
I have provided by gene list at 2 different points: `SCTransform` and `IntegrateLayers`.

1. Was I correct to pass the gene list to `residual.features` in `SCTransform`?

2. Is there anything else that should be adjusted in my workflow to enhance my UMAP?

3. Could this be a consequence of integration?

Thanks in advance!

**Comment by rsatija** [comment]
1. You are correct to pass this, but you also want to set the features argument to t.nk.markers in RunPCA
2. While it may seem like focusing on a very small subset of genes can enhance cluster identification, in practice, this can actually dampen signal quite a bit since any individual gene can be noisy
3. You can certainly examine results without integration to see if you get better cell type separation
4. You can also use supervised annotation (like RunAzimuth) to get increased resolution of cell types. The Azimuth PBMC reference has high-resolution labels for T and NK cells. After annotation, you can check to see if the annotations make sense by checking the expression of your marker subsets.

**Comment by kenneditodd** [comment]
@rsatija Thank you! I ended up increasing the number of dimensions used with RunUMAP and got better subclustering results.
