### ISSUE TITLE
Bias in SCTransform normalization

### ISSUE THREAD

**Issue by sup27606** [satijalab/seurat#9124]
I am integrating two independent scRNA-seq samples (one control, one a gene KO) after normalizing each sample separately using SCTransform. While running differential gene expressions between the two samples using FindMarkers, I see a systemic bias in the log fold changes that to me is indicative of an issue with the normalization. 

Attached below is the histogram of log fold changes. As can be seen, the peak of the distribution is shifted leftward from zero, leading to an unusually high number of down regulated genes, that shouldn't be.

temp = FindMarkers(seurat_obj, group.by = "sample", ident.1 = "sample2", ident.2 = "sample1", logfc.threshold = 0, assay = "SCT")
hist(temp$avg_log2FC, 500, xlim = c(-2,2)); abline(v = 0, col = "red")

![image](https://github.com/user-attachments/assets/70475e61-1bd3-4799-9b15-b56b47ab7024)

I also plotted the mean expressions of each gene sample1 vs sample2 and saw an ever so slight bias in the scatter plot.
x = log2(rowMeans(seurat_obj@assays$SCT@counts[,seurat_obj$sample == "sample1"]))
y = log2(rowMeans(seurat_obj@assays$SCT@counts[,seurat_obj$sample == "sample2"]))
plot(x,y, pch = 19, cex = 0.2, xlab = "log expression, sample 1", ylab = "log expression, sample 2"); abline(a = 0, b = 1, col = "red")
![image](https://github.com/user-attachments/assets/6569e2d5-98fe-4b6d-86e9-cdc336484354)

Any suggestions from developers or expert users would be appreciated. Thanks in advance.

The code to reproduce the problem is as follows:

The two samples are preprocessed by filtering low quality cells and removing doublets using DoubletFinder, and saved as .rds files.

library(Seurat)
library(future)

options(parallelly.fork.enable = T)
options(future.globals.maxSize = 10000 * 1024^2)
plan("multicore", workers = 8)

obj1 = readRDS("COHP_55073/seurat_obj.rds"); obj1 = SCTransform(obj1, vst.flavor = "v2", vars.to.regress = "percent.mt")
obj2 = readRDS("COHP_54902/seurat_obj.rds"); obj2 = SCTransform(obj2, vst.flavor = "v2", vars.to.regress = "percent.mt")

obj1$sample = "sample1"
obj2$sample = "sample2"

seurat_obj_list = list(obj1, obj2)

features <- SelectIntegrationFeatures(object.list = seurat_obj_list, nfeatures = 3000)
seurat_obj_list = PrepSCTIntegration(object.list = seurat_obj_list, anchor.features = features)

anchors <- FindIntegrationAnchors(object.list = seurat_obj_list, anchor.features = features, normalization.method = "SCT")
seurat_obj = IntegrateData(anchorset = anchors, normalization.method = "SCT")
DefaultAssay(seurat_obj) = "integrated"
rm(obj1, obj2)
seurat_obj$orig.ident = seurat_obj$sample

DefaultAssay(seurat_obj) = "SCT"
seurat_obj = PrepSCTFindMarkers(seurat_obj)
temp = FindMarkers(seurat_obj, group.by = "sample", ident.1 = "sample2", ident.2 = "sample1", logfc.threshold = 0, assay = "SCT")

**Comment by rsatija** [comment]
It does appear that there is a very slight bias in the independent normalizations. This is minor (logFC of ~0.1), and may also reflect some broader systematic biological difference between samples. If you do see this, its not unreasonable to first merge the samples together prior to running SCTransform and DE (so they are normalized together), or to use the standard NormalizeData workflow when running DE;
