### ISSUE TITLE
error

### ISSUE THREAD

**Issue by eshimutu** [satijalab/seurat#9131]
```r
> DimPlot(CHDonly, label = T)
Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames
```

**Comment by igrabski** [comment]
Hi, this issue has arisen in the past when packages such as `ggplot2` were out-of-date. Please try updating `ggplot2`, `SeuratObject`, and `Seurat`, and see if the issue persists. I will close this issue for now, but if you continue to have this problem, please provide more code and information, as well as the output of `SessionInfo()`.
