### ISSUE TITLE
Installation issue in R ver. 4.4.1 (via conda)

### ISSUE THREAD

**Issue by zbidav** [satijalab/seurat#9140]
Hello, 
I apologize for the question. 
In our workspace, we use R version 4.4.1. I tried creating a basic conda environment but... encountered version conflicts. Is there a solution? 
I replicated this issue in conda in:

- Rocky Linux 9.4 (Blue Onyx)
- Ubuntu 20.04.5 LTS (Focal Fossa), WSL

Here is my code:
```{sh}
conda create -n seurat -c conda-forge -c bioconda -c defaults r-base=4.4.1 r-seurat
```
Or in yaml:
```{yml}
name: seurat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.4.1
  - r-seurat
```

![image](https://github.com/user-attachments/assets/6122cf93-cf98-4bce-a768-d7380075adcb)

**Comment by mhkowalski** [comment]
Hi, 

This seems to be something with R version incompatibility (it says that ```r-seurat 4.1.1-5.1.0``` requires ```r-base <4.3.0a0```). 
This worked for me, for example (although you will  have to change R version based on what version of seurat you'd like to install). 

```conda create -n seurat -c conda-forge -c bioconda -c defaults r-base=4.3.3 r-seurat=5.1.0```

I'll note that we only require R > 4.1, so this must be coming from conda (we don't manage this).
