### ISSUE TITLE
batch

### ISSUE THREAD

**Issue by zznx** [satijalab/seurat#9145]
Hi, I think someone has asked before, but I still hope to get help. Will the difference between health and disease be removed by going to batch

**Comment by samuel-marsh** [comment]
Hi @zznx,

Not member of dev team but hopefully can be helpful.  So this question isn't something that has a yes or no answer.  It is going to depend on effects occurring in health and disease, the type of analyses, the goal of the analysis, and many other experiment specific questions.  I would recommend testing multiple analytical pipelines to see which works best for what you are looking at.

If you have further analytical questions I would recommend posting in the discussion forum (https://github.com/satijalab/seurat/discussions) where other users may be able to help as well.

Best,
Sam
