### ISSUE TITLE
Is there any way to plot the average of features of Violin plot?

### ISSUE THREAD

**Issue by ryanhchung** [satijalab/seurat#9149]
Hi Team.

If I have a set of genes (a, b, c), can I plot their average expression with VlnPlot function?

This is what we normally use, and it will generate three plots.
```r
VlnPlot(data, features = c("a", "b", "c"), pt.size = 0, group.by = "clusters", ncol = 3)
```
but I want to plot the average expression of (a, b, c) in a single violin plot

Can you tell me how to solve it?

**Comment by Alexis-Varin** [comment]
Hi, you can do it by calculating a module score. Seurat has its own function `AddModuleScore`, and some other packages exist that also offer their own function, such as UCell, GSVA, AUCell...

**Comment by samuel-marsh** [comment]
Hi @ryanhchung @Alexis-Varin,

So it is critical to know that module scoring is not equivalent to average expression and each of those functions mentioned create scores in different ways with different caveats to their use.

If you are looking to combine the expression of those 3 genes you could combine the counts into a new "gene" that you could plot as on variable.

Or if you want to plot all of the genes individually on one plot you can use `VlnPlot`'s parameter `stack = TRUE` or `Stacked_VlnPlot` from my package scCustomize (https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#stacked-violin-plots)

Best,
Sam

**Comment by ryanhchung** [comment]
@samuel-marsh @Alexis-Varin Thank you everyone!
