### ISSUE TITLE
error in installing Seurat with conda

### ISSUE THREAD

**Issue by RuiyangLiu94** [satijalab/seurat#915]
I tried to install Seurat under a conda environment by:
 conda install -c bioconda r-seurat 
Installation seems successful, but when trying to load this package, there is an error: object ‘np_array’ is not exported by ‘namespace:reticulate’.

Later, I tried to install Seurat within R directly(still under the same conda environment). I tried install.packages("Seurat") and ended up with the same error.

Under the conda environment, my R version is 3.4.1; python version(if needed) is sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0).

From conda info:
            platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-862.14.4.el7.x86_64 centos/7 glibc/2.17

I am wondering what is going wrong here.

**Comment by RuiyangLiu94** [comment]
issue solved

**Comment by 23skdu** [comment]
> issue solved

what did you do to solve it? I'm running into this.

**Comment by Brunox13** [comment]
I was running into the same problem. I was using `r-reticulate` version 1.0; it was resolved by installing a newer version:
```bash
conda install -c conda-forge r-reticulate">1.0"
```
