### ISSUE TITLE
Best clustering resolution

### ISSUE THREAD

**Issue by llarapf** [satijalab/seurat#9163]
Hi there!
I´m analyzing Visium10x data using Seurat, and I wanted to know if there is a method to calculate the best clustering resolution, in order to get a good number of clusters.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  There are some methods that aim to solve this issue but there is not a firm consensus in field (google search should help you there).  In practice this is often dataset specific and analysis will require testing and examination of multiple resolutions to determine optimal for specific dataset at hand.

Best,
Sam
