### ISSUE TITLE
Gene expression per subpopulation(Radar plot)

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#917]
Hello everyone,
I have an idea but I need some help.

I would like to make a radar plot with a list of genes and their expression (log fold change) according to the celltype we provide.

Here a picture to be more accurate. (from tRanslatome R package)
![image](https://user-images.githubusercontent.com/37413033/48068782-09e32e80-e1d4-11e8-888f-dfbeeda22dc6.png)
"mister-a, mister-b" would be my celltype
"english, math..." would be my genes.

I am not very good at using R, so if anyone has some ideas, any hint will be appreciated... 

Thanks a lot !

**Comment by satijalab** [comment]
We don't support this in Seurat - though it is an interesting visualization. We'd be happy to consider a PR if someone would like to develop a function to generate this plot
