### ISSUE TITLE
Seurat v5.1 ImageFeaturePlot cannot plot genes starting with a number

### ISSUE THREAD

**Issue by tangmindan** [satijalab/seurat#9170]
### Discussed in https://github.com/satijalab/seurat/discussions/9144

<div type='discussions-op-text'>

<sup>Originally posted by **tangmindan** July 24, 2024</sup>
I found that ImageFeaturePlot cannot plot genes that begin with numbers, but other genes are normal.

![企业微信截图_17217878754606](https://github.com/user-attachments/assets/2871d8d3-5351-46ab-8323-1a0228a77afa)

Looking at the source code, I found that the fill in ggplot in the SingleImagePlot function is not supported.

![企业微信截图_17217900339104](https://github.com/user-attachments/assets/27b8f6a1-b706-4ac4-854c-9c8d7e483715)

Is there a way for me to modify all gene names directly after LoadXenium, such as adding "X" to the genes that start with a number?

</div>

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  See comments by dev team on post with same issue from last year:
https://github.com/satijalab/seurat/issues/6057#issuecomment-1626177049

If you rename the genes that should solve the issue.

Best,
Sam
