### ISSUE TITLE
where joinlayer should be located

### ISSUE THREAD

**Issue by asmlgkj** [satijalab/seurat#9171]
Thanks a lot
I am leating seurat v5.
In https://satijalab.org/seurat/articles/integration_introduction, 
joinlayers used after immediately after 
ifnb <- IntegrateLayers(object = ifnb, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)

# re-join layers after integration
ifnb[["RNA"]] <- JoinLayers(ifnb[["RNA"]])

but in https://satijalab.org/seurat/articles/seurat5_integration,
joinlayers used after 

obj <- IntegrateLayers(
  object = obj, method = CCAIntegration,
  orig.reduction = "pca", new.reduction = "integrated.cca",
  verbose = FALSE
)

obj <- FindNeighbors(obj, reduction = "integrated.cca", dims = 1:30)
obj <- FindClusters(obj, resolution = 2, cluster.name = "cca_clusters")
obj <- RunUMAP(obj, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")
p1 <- DimPlot(
  obj,
  reduction = "umap.cca",
  group.by = c("Method", "predicted.celltype.l2", "cca_clusters"),
  combine = FALSE, label.size = 2
)
obj <- JoinLayers(obj)
obj

would this order matters the final result ot other following analysis?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.

When (or if) you run JoinLayers depends on whether analyses need layers to be joined.  One reason as explained in the text of vignette you linked is for DE analysis:
_"Once integrative analysis is complete, you can rejoin the layers - which collapses the individual datasets together and recreates the original counts and data layers. You will need to do this before performing any differential expression analysis. However, you can always resplit the layers in case you would like to reperform integrative analysis"_

So when you run will be dependent on what analyses you are running.

Also for reference for the future you may have more luck with analysis based questions using the Discussion section (https://github.com/satijalab/seurat/discussions) vs. Issues which is mainly for bugs or errors in running Seurat.

Best,
Sam
