### ISSUE TITLE
Issue installing spatstat.core compatible with Seurat 4.0.2

### ISSUE THREAD

**Issue by rachelxrachel** [satijalab/seurat#9174]
Thanks! I've gotten Matrix downloaded as well as a v4 of SeuratObject. I am still having a problem trying to get Seurat installed. I'm getting "Error: object 'integral' not found whilst loading namespace 'spatstat.core'"

remotes::install_version(package = 'Seurat', version = package_version('4.0.2'))

I have installed spatstat.core from the archive already, so I'm not sure if there is a set compatible version that must be downloaded?

_Originally posted by @rachelxrachel in https://github.com/satijalab/seurat/issues/9169#issuecomment-2263660000_

**Comment by samuel-marsh** [comment]
Closing and reopening original issue to maintain continuity
