### ISSUE TITLE
Updating code to work with Assay5 class

### ISSUE THREAD

**Issue by rachelxrachel** [satijalab/seurat#9176]
Hi, I recently did all of my analysis using an older version of Seurat, and I am attempting to switch over to Seurat v5.

This is an old version of my code that worked with Seurat v4:

wt_E1 <- t(as.matrix(Exp_SOmerge@assays$RNA@counts[,which(Exp_SOmerge$celltype == 'YFPwt' & Exp_SOmerge$experiment == 'R1')]))

If I run it with v5, I get the error: 

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': error in evaluating the argument 'x' in selecting a method for function 'as.matrix': no slot of name "counts" for this object of class "Assay5"

How am I able to update my code to work with v5?

**Comment by longmanz** [comment]
Hi, 
In V5 we switch from 'slot' to 'layer' so the old syntax will not work. In your case, you can use LayerData() function to get the count matrix:
```
cell_idx = colnames(Exp_SOmerge)[which(Exp_SOmerge$celltype == 'YFPwt' & Exp_SOmerge$experiment == 'R1')]
count_data = LayerData(object = Exp_SOmerge, layer = "counts", assay = "RNA", cells = cell_idx)
```
