### ISSUE TITLE
Error while merge huge objects and filtering genes

### ISSUE THREAD

**Issue by Fougere87** [satijalab/seurat#918]
Hello, 

I'v been confronted to a strange issue today trying to merge two objects of approx 50000 cells using this line : 
```r
sample_data_merged= MergeSeurat(object1 = sample_data_1, object2 = sample_data_2, min.cells = 10,is.expr = 1, do.scale = F, do.center = F,add.cell.id1 = "M", add.cell.id2 = "F")
```
I obtained this error : 
```r
Error in which(as(i, if (extends(cli, "sparseMatrix")) "sparseVector" else "vector")) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519
```

Removing the min.cells and is.expr arguments, I didn't get the issue. 

Looks to be a bug associated with Rcpp, but I updated it and the problem was reproducible.   
It may be due to the use of an int type somewhere in the filtering function.   With a huge matrix the row index range may exceed the int limit and a long should be used instead.   
Just my guess...  but I'm no expert. 
I didn't dig much more... I just wanted to signal it ! 

Thanks a lot for your so useful job  !

**Comment by andrewwbutler** [comment]
Thanks for reporting! I was unable to reproduce on two objects of 50K cells using `merge` in Seurat v3 (likely because we removed those arguments). Hopefully this resolves the issue going forward but please open a new issue if this persists in v3.

**Comment by markrobinsonuzh** [comment]
@andrewwbutler Thanks for this great package!

I also got a similar error using version `Seurat_3.0.0.9000` .. 

```
Extracting anchors for merged samples
Finding integration vectors
Error in validityMethod(as(object, superClass)) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:519
```
.. from calling ..

```
seurat <- IntegrateData( anchorset=anchors, 
                         dims = 1:dims,
                         features.to.integrate=row.names(sl[[1]]) )
```

In my case, there are 24 samples and >85k cells. I'm just trying now to trim the number of genes used, in case that reduces the length of the vector (?), but if there are other suggestions, please let me know.

I can try and make a reproducible example.

Thanks, Mark
