### ISSUE TITLE
Consider exporting `VisiumV1` and `VisiumV2`

### ISSUE THREAD

**Issue by Nick-Eagles** [satijalab/seurat#9180]
Hello,

I worked on developing a [function](https://github.com/LieberInstitute/visiumStitched/blob/devel/R/spe_to_seurat.R) to convert a `SpatialExperiment` object to a `Seurat` object, which, as far as I know, has not been done yet (I'm aware of `as.Seurat()` for `SingleCellExperiment`). From what I could gather, the `VisiumV1` class is the best way to store Visium data from a `SpatialExperiment` in order to perform the conversion (see how I've done it [here](https://github.com/LieberInstitute/visiumStitched/blob/69ce3aec8364cccf93f52211ea456b061172f35d/R/spe_to_seurat.R#L117-L127)). Could you consider exporting the `VisiumV1` class? It seems useful for developers, and the use of `:::` (as I've done so far) is considered bad practice for R package developers.

Please also let me know if there's a better way to perform this conversion or different class I should be using. Thanks!

Best,
-Nick

**Comment by dcollins15** [comment]
Thanks for reaching out @Nick-Eagles!

`VisiumV1` and `VisiumV2` are both S4 classes, so you can instantiate them with `new`, e.g.:

```R
new(
    class = "VisiumV1",
    image = this_img,
    scale.factors = scalefactors(
        spot = NA, fiducial = NA, hires = NA,
        lowres = imgData(spe)[imgData(spe_small)$image_id == "lowres", "scaleFactor"]
    ),
    coordinates = coords,
    spot.radius = SPOT_DIAMETER / scaleFactors(spe_small),
    assay = "originalexp",
    key = paste0(sample_id, "_")
)
```

> From what I could gather, the VisiumV1 class is the best way to store Visium data from a SpatialExperiment in order to perform the conversion

I'd recommend using the `VisiumV2` class for this. `VisiumV2` should be compatible with any `Seurat` methods but also implements the `FOV` interface which will also allow you to use methods like `BuildNicheAssay`. You can use the `Read10X_Image` function for an example of how to populate `FOV`/`VisiumV2` instances, starting (here)[https://github.com/satijalab/seurat/blob/1549dcb3075eaeac01c925c4b4bb73c73450fc50/R/preprocessing.R#L1249].

**Comment by Nick-Eagles** [comment]
Thanks for the code example-- I wasn't aware of the instantiation of S4 objects this way. Great, thanks for pointing to the `VisiumV2` example as well. This resolves everything I had in mind!
