### ISSUE TITLE
Problems of installing an older version of Seurat

### ISSUE THREAD

**Issue by ShweiSTAT** [satijalab/seurat#9185]
Hi!

I was trying to install the version of 4.0.4 on my MacBook (Sonoma 14.5 with M2 chips). And I ran this line of code:

"remotes::install_version("Seurat", "4.0.4")"

It gave me this error message: 
<img width="866" alt="Screenshot 2024-08-05 at 5 26 42 PM" src="https://github.com/user-attachments/assets/9eb0affd-d2ec-44af-9249-51775324c048">

So I tried to install the "spatstat.core" package by myself. Since this package is deprecated  and not in maintenance anymore, I downloaded the original file from the CRAN archive. For the versions of "spatstat.core" older than 2.4-0, my computer failed to compile the file. For the later version, my computer successfully install the  "spatstat.core"  package. However, when I try to install Seurat, there is always an error message saying: 
<img width="870" alt="Screenshot 2024-08-05 at 5 33 05 PM" src="https://github.com/user-attachments/assets/3df4cde8-e9f1-4bcd-b4fe-6bb4c2273857">

I wonder if there is any ways to fix this error. I tried to install the 4.0.4 Seurat in other operating systems (Microsoft and Linux), and they gave similar error messages. I know this is a very older version of Seurat, but one of the software that I am using only support Seurat 4.0.4.

Thank you so much!

**Comment by zskylarli** [comment]
Hi - since we are no longer maintaining that version, one potential hacky solution would be to clone the repository locally, edit the DESCRIPTION file so that it does not depend on spatstat.core, and then use your local version of Seurat via devtools (although this may compromise some functionality). Thank you for posting this issue!
