### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by calvinhuapeng** [satijalab/seurat#92]
fail to install on both R 3.4.0 and 

```R
> library(Seurat)
Loading required package: ggplot2
Loading required package: cowplot

Attaching package: ‘cowplot’

The following object is masked from ‘package:ggplot2’:

    ggsave

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Seurat/libs/Seurat.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Seurat/libs/Seurat.so, 6): Library not loaded: /usr/local/lib/libgfortran.3.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/Seurat/libs/Seurat.so
  Reason: image not found
Error: package or namespace load failed for ‘Seurat’
> version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.3                         
year           2017                        
month          03                          
day            06                          
svn rev        72310                       
language       R                           
version.string R version 3.3.3 (2017-03-06)
nickname       Another Canoe               
```

**Comment by andrewwbutler** [comment]
Looks like an issue linking the to the fortran library. One thing to try would be uninstalling and reinstalling R and then Seurat.

**Comment by activedendrite** [comment]
I have the same fail to install issue (same error message, for both 3.3.3, 3.4.1), and I tried to uninstall and reinstall R, still got the same error.

**Comment by andrewwbutler** [comment]
Which installation method did you choose (binary or source)?

**Comment by maxbates** [comment]
I have this issue as well. binary.

**Comment by andrewwbutler** [comment]
What version of fortran are you running (`gfortran --version`)? One thing to try is updating to 6.1 from [here](https://gcc.gnu.org/wiki/GFortranBinaries) assuming you are running R>=3.4. That should also allow you to try the install from source if the binary is still giving you issues.

**Comment by maxbates** [comment]
I was missing this executable. A few times messing around with `brew install gcc` got it working. I still get the warnings above and will post if there are issues using the package e.g. going through the tutorial.

**Comment by activedendrite** [comment]
@andrewwbutler 

I was installing the binary using this:

> install_url("https://github.com/satijalab/seurat/releases/download/v2.0.0/Seurat_2.0.0_R3.4.tgz", binary = TRUE)
library(Seurat)

**Comment by activedendrite** [comment]
@andrewwbutler 

I tried to download the tgz file from the link (https://github.com/satijalab/seurat/releases/download/v2.0.0/Seurat_2.0.0_R3.4.tgz) to my desktop and tried to install that file, it was successful (although have to manually install some packages it requires).

**Comment by satijalab** [comment]
Closing this issue as our installation procedures have changed significantly, most notably since we now allow for direct installation from CRAN which should solve most installation issues.
