### ISSUE TITLE
How to filter the features?

### ISSUE THREAD

**Issue by danli349** [satijalab/seurat#9202]
Hello: 

How can I filter the features at least expressed in 10 cells?
```{r}
pbmc <- subset(
  x = pbmc,
  subset = nCount_ATAC < 7e4 &
    nCount_ATAC > 2000 &
    nCount_RNA < 25000 &
    nCount_RNA > 2000 &
    percent.mt < 20
)
```
Thanks

**Comment by mhkowalski** [comment]
Hi, we don't an explicit function to do this but you could always use the `CreateSeuratObject()` function with argument `min.cells = 10` as quick way to do this.

For example,
```
pbmc_tmp <- CreateSeuratObject(counts = pbmc[['RNA']]$counts, min.cells = 10) #make object requiring min number of cells for each feature
pbmc[['RNA']] <- subset(pbmc[['RNA']], features = rownames(pbmc_tmp)) #subset original RNA assay based on filtering
```

You would do this for any assay you would like (ATAC, RNA). Hope this helps!
