### ISSUE TITLE
installation of package ‘Seurat’ had non-zero exit status

### ISSUE THREAD

**Issue by JhannelleF** [satijalab/seurat#9208]
Hello, 

I am trying to download the seurat package on R but keep getting the errors: 
- ERROR: dependency ‘SeuratObject’ is not available for package ‘Seurat’
- Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status.

I have downloaded the caTools package as a dependency but still unable to successfully install seurat. 

<img width="1120" alt="Screenshot 2024-08-11 at 7 40 45 PM" src="https://github.com/user-attachments/assets/55fc926a-d0d9-43cc-847c-093ccf56b83e">

```

**Comment by igrabski** [comment]
Hi, the issue doesn't seem to be with Seurat itself but rather because `gfortran`, which is used in many different R packages, was not found in your system. After installing `gfortran` on your system, you can try installing Seurat again and it should work -- please re-open this issue if not!
