### ISSUE TITLE
How to handle Imbalanced celltype number of reference dataset in Seurat MapQuery

### ISSUE THREAD

**Issue by Nh-code** [satijalab/seurat#9209]
When using Seurat's `MapQuery`, is it necessary to balance the number of cells for each cell type in the reference dataset? I've noticed that the cell type counts in the reference dataset seem to affect the prediction results for the query dataset. How should this be addressed to obtain a more reliable prediction?

**Comment by igrabski** [comment]
Hi, it is not necessary to balance the number of cells in the reference dataset, but indeed the cell type counts can sometimes affect the prediction results, e.g. a very rare population in the reference data may be more difficult to detect in the query data.
