### ISSUE TITLE
Error in if (tools::file_ext(filename) == "parquet") { :    the condition has length > 1

### ISSUE THREAD

**Issue by JhannelleF** [satijalab/seurat#9216]
I am trying to load my spatial transcriptomics data using the code: 
seurat_obj <- Load10X_Spatial(data.dir = data_dir.B2) 

data_dir.B2 refers to the pathway to my Directory containing the H5 file specified.

The version of seruat is 5.0.1 

When I run the code I keep getting the error: 
Error in if (tools::file_ext(filename) == "parquet") { : 
  the condition has length > 1

How do I fix this?

**Comment by alosdiallo** [comment]
I can confirm that I am having the same issue with version 5.1.0

> Read10X_Image(
+   image_dir,
+   image.name = "tissue_lowres_image.png",
+   assay = "Spatial",
+   slice = "slice1",
+   filter.matrix = TRUE
+ )
Error in if (tools::file_ext(filename) == "parquet") { : 
  the condition has length > 1
> Load10X_Spatial(data.dir = data_dir)
Error in if (tools::file_ext(filename) == "parquet") { : 
  the condition has length > 1

**Comment by zezhuo** [comment]
Removing the "Spatial/tissue_positions.csv" file works in Seurat v5.1.0 for me.

**Comment by mhkowalski** [comment]
Hi, 

It seems like this error might be coming from having both a `tissue_positions.csv` and a `tissue_positions.parquet` file in your directory. I agree with @zezhuo  that removing the csv file should fix the problem. Please let us know if you're continuing to have issues.

**Comment by alosdiallo** [comment]
Hi @mhkowalski the tissue_positions.parquet file is for Visium HD.  I'm using regular visium, so when I remove tissue_positions.csv I get:

```
> Read10X_Image(
+    image_dir,
+    image.name = "tissue_lowres_image.png",
+    assay = "Spatial",
+    slice = "slice1",
+    filter.matrix = TRUE
+  )
Error in .local(obj, ...) : 
  cannot derive coordinates from non-numeric matrix
```

**Comment by Southwind497** [comment]
> Hi [@mhkowalski](https://github.com/mhkowalski) the tissue_positions.parquet file is for Visium HD and so I don't have that file. I'm using regular visium, so when I remove tissue_positions.csv I get:嗨，tissue_positions.parquet文件适用于visium HD，因此我没有该文件。我正在使用常规的visium，因此当我删除tissue_positions.csv时，我会得到：
> 
> ```
> > Read10X_Image(
> +    image_dir,
> +    image.name = "tissue_lowres_image.png",
> +    assay = "Spatial",
> +    slice = "slice1",
> +    filter.matrix = TRUE
> +  )
> Error in .local(obj, ...) : 
>   cannot derive coordinates from non-numeric matrix
> ```
> 
> What I had to do was to remove tissue_positions_list.csv, because the error:我要做的是删除tissue_positions_list.csv，因为错误： Error in if (tools::file_ext(filename) == "parquet") { : if（工具:: file_ext（filename）==“ parquet”）{：： the condition has length > 1 条件的长度> 1
> 
> Is indicating that the function is finding multiple files with the same name. The issue is now resolved for me as well. Thank you指示该函数正在找到具有相同名称的多个文件。现在，这个问题也对我解决了。谢谢

yes, you're right, rm tissue_positions_list.csv helped me solve the problem, what I want to know is why this file appeared. 
Thank you!!!!!!!!!!

**Comment by Max-xinyu-He** [comment]
Thanks a lot, i met this too, and rm tissue_positions_list.csv makes it work.

**Comment by MJoseMo** [comment]
Hi, 

I am facing a similar error with Seurat 5.4.0, when I tried to load spatial transcriptomics data, an error emerge: Error in if (tools::file_ext(filename) == "parquet") { :
the condition has length > 1
This is my data directory: 

<img width="245" height="176" alt="Image" src="https://github.com/user-attachments/assets/cfec75d4-6444-40f5-9afa-a2d0efc9a0e3" />
