### ISSUE TITLE
Work around for arrow package? Following visiumhd_analysis_vignette.Rmd

### ISSUE THREAD

**Issue by kyralindley** [satijalab/seurat#9220]
I've been following the vingette, and trying to use the Visium HD Spatial Gene Expression Library, Human Pancreas (FFPE) dataset. I got the data onto my computer and I've been trying to execute (object <- Load10X_Spatial(data.dir = data_dir, bin.size = c(8,16))). But everytime i get this error:

Error: NotImplemented: Support for codec 'zstd' not built
In order to read this file, you will need to reinstall arrow with additional features enabled.
Set one of these environment variables before installing:

 * Sys.setenv(LIBARROW_MINIMAL = "false") (for all optional features, including 'zstd')
 * Sys.setenv(ARROW_WITH_ZSTD = "ON") (for just 'zstd')

See https://arrow.apache.org/docs/r/articles/install.html for details

Neither of the changes they said to do fix the function, so i can use Load10x_Spatial to load my data. Is there an alternative package to arrow? I've raised an issue with arrow over this but gotten no response. Would love to hear of a work around to this problem if its known!

Thanks!

**Comment by DaiZYlab** [comment]
Install the developing version of Seurat will fix the error message.
