### ISSUE TITLE
dims in scvi  sketch integration

### ISSUE THREAD

**Issue by Flu09** [satijalab/seurat#9247]
I was following the v5 integration vignette and I choose 50 dims to continue with the integration of my sketched object ( active slot sketch assay)

> DefaultAssay(filtered_obj_sketched)
[1] "sketch"

For scvi it did not work beyond 30 dims. Although the object has 50 dims. 

> filtered_obj_sketched <- FindNeighbors(filtered_obj_sketched, reduction = "integrated.scvi", dims = 1:50)
Error in FindNeighbors.Seurat(filtered_obj_sketched, reduction = "integrated.scvi",  : 
  More dimensions specified in dims than have been computed

> filtered_obj_sketched <- FindNeighbors(filtered_obj_sketched, reduction = "integrated.scvi", dims = 1:40)
Error in FindNeighbors.Seurat(filtered_obj_sketched, reduction = "integrated.scvi",  : 
  More dimensions specified in dims than have been computed

> filtered_obj_sketched <- FindNeighbors(filtered_obj_sketched, reduction = "integrated.scvi", dims = 1:31)
Error in FindNeighbors.Seurat(filtered_obj_sketched, reduction = "integrated.scvi",  : 
  More dimensions specified in dims than have been computed

  > filtered_obj_sketched <- FindNeighbors(filtered_obj_sketched, reduction = "integrated.scvi", dims = 1:30)
Computing nearest neighbor graph

I decided to skip FindNeighbors step and check if RunUmap() will work .. again it only worked on 30 dims only. 
filtered_obj_sketched <- RunUMAP(filtered_obj_sketched, reduction = "integrated.scvi", dims = 1:30, return.model = T, reduction.name = "umap.scvi")

Then I faced this issue
> DimPlot(filtered_obj_sketched , reduction = "umap.scvi")
Rasterizing points since number of points exceeds 100,000.
To disable this behavior set `raster=FALSE`
Warning message:
Removing 932261 cells missing data for vars requested 

CCA, RPCA, harmony, I have no issue at all ( 50 dims in them and no warning message of any missing data)

I would appreciate it if you can help me especially regarding the removing of almost 1million cells

**Comment by igrabski** [comment]
Hi, these error messages are suggesting that your `integrated.scvi` reduction only has 30 dimensions available, which is why you are not able to specify more than 30. 

Regarding your second question, it seems like you are using a sketching workflow here. If the dimension reduction `umap.scvi` was only computed on your sketched cells, then only those will be plotted in `DimPlot`.

**Comment by Flu09** [comment]
@igrabski  The object has 50 dims. For harmony, rpca, and cca, it worked fine. only scvi is having issues

**Comment by igrabski** [comment]
Can you show the output of `filtered_obj_sketched@reductions$integrated.scvi`, as well as the output of `filtered_obj_sketched`?
