### ISSUE TITLE
seruat object interaction vignette link broken 

### ISSUE THREAD

**Issue by ChrisSteel-bio** [satijalab/seurat#9248]
Is this vignette available somewhere else?

https://satijalab.org/seurat/articles/integration_introduction

[Seurat object interaction vignette](https://satijalab.org/seurat/articles/interaction_vignette).

Many thanks

**Comment by samuel-marsh** [comment]
Hi,

The links are working fine for me currently.  Is this still an issue for you?

Best,
Sam

**Comment by desmondramirez** [comment]
Clicking the actual link "[Seurat object interaction vignette](https://satijalab.org/seurat/articles/interaction_vignette)" in the vignette sends me to a 404 page. It's not the same link as https://satijalab.org/seurat/articles/integration_introduction, which works.
