### ISSUE TITLE
Error when plotting after upgrading Seurat object

### ISSUE THREAD

**Issue by mxposed** [satijalab/seurat#925]
Hi
I have a Seurat object version 2.1.0, and I tried upgrading it and then plot.
My code is:
```R
c <- UpdateSeuratObject(c)
DimPlot(c, reduction = "tsne")
```

I get the following error:
```R
Error in switch(EXPR = as.character(x = class(x = value)), Assay = { : 
  EXPR must be a length 1 vector
```
with a stack trace pointing to `StashIndent.Seurat` call, and `ident` vector gets printed after the error.
`Embeddings(c, reduction = "tsne")` is present

**Comment by satijalab** [comment]
I tried to reproduce this on v2.1 objects that I had stored but was unable to, plotting worked fine after updating.

Can you provide any additional information about the object (and does the error persist if you run in the current version of Seurat v3?)

**Comment by mxposed** [comment]
The error does persist, what additional information would you need?

**Comment by andrewwbutler** [comment]
Are you able to share the object (or a downsampled version that reproduces the issue)?

**Comment by mxposed** [comment]
Here is the downsampled object: https://drive.google.com/file/d/1wGIAUcVEqQJqEUPAXNWNL-C7yjNWz990/view?usp=sharing

What is funny is that `FeaturePlot` works for it, but `DimPlot` gives the above error, so I suspect something is wrong with the `idents`. I've tried it again today with the newest version from seurat-3 branch.

**Comment by andrewwbutler** [comment]
So this issue turns out to be caused by the `idents` being a "ordered factor" instead of a regular "factor". Should work now as of  74e2de8.

**Comment by mxposed** [comment]
Great, this works now. Thank you
