### ISSUE TITLE
issue with Seurat object visiumV2 instead of visium V1

### ISSUE THREAD

**Issue by laetitiacollet** [satijalab/seurat#9251]
Hi, 

I try to reproduce the vignette : https://satijalab.org/seurat/articles/spatial_vignette.html in order to use afterward the cellchat pipeline for ligant receptor analysis. 
I  followed the vignette : 
library(Seurat)
library(SeuratObject)
library(Matrix)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)

InstallData("stxBrain")
brain <- LoadData("stxBrain", type = "anterior1")

However the object download from that is VisiumV2 and not VisiumV1. However, most of the command in the vignette works with object VisiumV1 and not with VisiumV2. 

Do you know how to fix this ? 

Thanks a lot in advance for you reply, 

Best regards, 

LC

**Comment by vapolonio** [comment]
I have the same issue, there is a way to set the version of visium to v1?

**Comment by dcollins15** [comment]
Thanks for reaching out! I've been meaning to push a patch up for this for a while now — in the meantime you can use the workaround detailed here:
- https://github.com/satijalab/seurat/issues/9012#issuecomment-2173544071
