### ISSUE TITLE
Error: package ‘SeuratObject’ 5.0.1 was found, but >= 5.0.2 is required by ‘Seurat’

### ISSUE THREAD

**Issue by imaasif4** [satijalab/seurat#9260]
I am tring to install Seurat package on linux system where the R version is 4.0.0, and while I was trying to install Seurat package it gives me this error... Can anyone help me with that
<img width="996" alt="Screenshot 2024-08-26 at 5 06 48 PM" src="https://github.com/user-attachments/assets/cd9c9166-9dcc-43ee-bd6d-d15e87db4fd9">

**Comment by samuel-marsh** [comment]
Hi,

If you install SeuatObject from CRAN (latest version is 5.0.2) and then install Seurat does that resolve the issue?

Best,
Sam

**Comment by samuel-marsh** [comment]
Sorry my mistake it appears that you are running R 4.0.0.  Newest SeuratObject requires 4.1.0.

So you can either install newer version of R (4.1.0 or greater; latest release is 4.4.1) or you'll have to install older version of Seurat from CRAN archive.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @imaasif4,

Were you able to resolve this issue?

Best,
Sam
