### ISSUE TITLE
Different DimPlot between Seurat V4 and V5

### ISSUE THREAD

**Issue by Tongbcc** [satijalab/seurat#9264]
Hi,
I felt confused about the umap figure created by `DimPlot()` fuction from Seurat V4 and V5. Figure 1 was created by V5, but I got a wisely different figure by V4, Figure 2, using a same seurat obj! Then I got the coordinate with `embb <- seurat_obj@reductions$umap@cell.embeddings`, and draw a scatter diagram with `plot(x=embb[, 1], y=embb[, 2], type="p")`. The result was like the figure by V4. Additionly, I also draw the plot in python with `sns.scatterplot(data=meta,x='umap_1',y='umap_2',hue=key,palette='tab20',s=1,linewidth=0)`, and got a figure like V4 again.

Has V5 performed further processing on the UMAP plot？

![image](https://github.com/user-attachments/assets/2ca4633f-fb24-4b8a-a272-4005e99e422c)
![image](https://github.com/user-attachments/assets/033a6dd7-673f-4655-9e5a-79a7f344539c)
![image](https://github.com/user-attachments/assets/8cd62246-2918-44ab-a1f5-e6d0c83fbad3)
![image](https://github.com/user-attachments/assets/6dce2a32-990c-49ea-a6cb-731196d77c51)

Best regards!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I cannot replicate this issue unfortunately.  Can you please provide code you are running and the code used to generate the Seurat object.

Best,
Sam

**Comment by Tongbcc** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. I cannot replicate this issue unfortunately. Can you please provide code you are running and the code used to generate the Seurat object.
> 
> Best, Sam

Hi, Dr. Marsh, 
I'm very pleased to receive your reply. Thanks for your attention!

The first plot was generated in Seurat-5.0.3, and the code as follows:
```
parser = argparse::ArgumentParser(description = 'Script to integration multi rds data')
parser$add_argument('-i', dest = 'input', help = 'input directory rds files')
parser$add_argument('-o', dest = 'prefix', help = 'output prefix')
opts = parser$parse_args()

library(Seurat)
library(dplyr)
library(cowplot)
library(reshape2)
library(future)
library(ggplot2)
library(harmony)

combined = readRDS(opts$input)
DefaultAssay(combined)<-'RNA'

combined <- subset(combined, subset=major.celltype.v3 == 'Epithelial')

combined <- NormalizeData(object = combined,
                          normalization.method = "LogNormalize",
                          scale.factor = 10000)

combined <- FindVariableFeatures(object = combined,
                                 nfeatures = 2000,
                                 selection.method = "vst")

combined <- ScaleData(object = combined,
                      verbose = FALSE)
combined <- RunPCA(object = combined,
                   npcs = 30,
                   verbose = FALSE)

combined <- RunHarmony(combined,
                       group.by.vars = "orig.ident")

combined <- combined %>% RunUMAP(reduction = "harmony", dims = 1:20) %>% FindNeighbors(reduction = "harmony", dims = 1:20)

combined <- FindClusters(combined, resolution =c(0.1,0.2,0.3,0.4,0.8,1,1.5,2,0.5))
combined <- RunTSNE(combined, reduction = "harmony", dims = 1:20)
saveRDS(combined,paste0(opts$prefix,".harmony.epi.rds"))

pdf(paste0(opts$prefix,".epi.umap.pdf"))
DimPlot(object = combined, reduction = "umap",label = TRUE)
dev.off()
```

The second plot was generated in Seurat-4.4.0, I did not do any more operations, and just draw a umap with `DimPlot(object = combined, reduction = "umap",label = TRUE)`. Later, I got the embedding matrix with `temp <- combined@reductions$umap@cell.embeddings`, drawed the third plot with `plot(x=temp[, 1], y=temp[,2], type='p')`.
Finally, I output 'cell embedding' and 'meta.data', and used Python to plot them. The code is as follows.

```
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

meta = pd.read_table(f'{prefix}.meta.txt',sep='\t',header=0,index_col=0)
umap = pd.read_table(f'{prefix}.umap.txt',sep='\t',header=0,index_col=0)
meta['umap_1'] = umap['umap_1']
meta['umap_2'] = umap['umap_2']

key='RNA_snn_res.0.5'
plt.figure(figsize=(8,8))
sns.scatterplot(data=meta,x='umap_1',y='umap_2',hue=key,palette='tab20',s=1,linewidth=0)
for xx in meta[key].unique():
    tmp = meta[meta[key]==xx]
    x,y = tmp['umap_1'].median(), tmp['umap_2'].median()
    plt.text(x,y,xx,fontsize=15)

plt.legend('',frameon=False)
plt.yticks([])
plt.xticks([])
plt.title(key)
plt.xlabel('')
plt.ylabel('')
```

I've hidden some specific names because the related content has not yet been published. Apologies for the inconvenience.

Best,
Baichuan Tong

**Comment by samuel-marsh** [comment]
Hi @Tongbcc,

Can you clarify something.  First, are you loading the object created in v5 in v4 or are you running identical code on both versions?  

Best,
Sam

**Comment by Tongbcc** [comment]
Hi,
I loaded the object created in v5 into v4. Only `Dimplot()` ran in v4.

Best,
Tong

**Comment by Tongbcc** [comment]
Hi @samuel-marsh 
I loaded the object created in v5 into v4. Only `DimPlot()` was ran in v4.

Best,
Tong

**Comment by samuel-marsh** [comment]
Hi Tong,

Thanks!  Are you able to reproduce the issue using dataset from SeuratData package?  This would help isolate issue further.

Best,
Sam

**Comment by Tongbcc** [comment]
Hi @samuel-marsh,

Your suggestion was excellent. I performed the same operation using PBMC data, but I got the same plot in both V4 and V5, which seems to be an issue with my data. I'm confused about this right now, but I'll continue troubleshooting. Thank you very much for your guidance.

Best,
Tong
