### ISSUE TITLE
Load in data from Loupe to Seurat

### ISSUE THREAD

**Issue by drchubos** [satijalab/seurat#9269]
Load in data from Loupe file
Could I ask how to import the loupe data with the original annotation (in loupe) to seurat?

**Comment by drchubos** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. See this page from 10X on exporting data from Loupe (https://www.10xgenomics.com/support/software/loupe-browser/latest/tutorials/assay-analysis/lb-sc-interoperability). These output files can then added to Seurat object as idents or dimensionality reductions etc. However, personally I would caution against this slightly as the outputs used by loupe are just default parameters run during CellRanger and therefore do not include cell QC or any other manual analysis steps and therefore can suffer from many issues.
> 
> Best, Sam

Hi Sam,

Thank you for your helpful input earlier. I wanted to follow up with a specific issue we're encountering related to the genes p15, p16, p19, and p21. In our current workflow, using Seurat's standard procedures, these genes seem to be filtered out during the normalization and preprocessing steps.

We have utilized CellRanger's aggr function to aggregate samples, which should theoretically retain all genes, including our genes of interest. However, after applying Harmony for batch correction and Seurat's standard normalization steps, we've noticed that these specific genes (p15, p16, p19, p21) are being filtered out or significantly downregulated.

Do you have any suggestions on how we could adjust our analysis pipeline to ensure these genes are retained and accurately represented? Any guidance or recommendations would be greatly appreciated.

Best regards,

**Comment by samuel-marsh** [comment]
Hi,

Can you clarify what you mean by filtered out?  Can you post the code you are running?

Thanks,
Sam
