### ISSUE TITLE
Analyze multi-ome object with multiple conditions

### ISSUE THREAD

**Issue by sky5198** [satijalab/seurat#9272]
I have reviewed the tutorial to integrate scRNA-seq and scATAC-seq data (https://satijalab.org/seurat/articles/seurat5_atacseq_integration_vignette). If I have multiple conditions, do I integrate all of the scRNA-seq objects first and then the scATAC-seq? Or do I integrate the scRNA-seq and scATAC-seq for each condition and then perform an integrate at the very end merging all of the conditions? 

I read that there was not a way to merge multi-ome objects yet but that post was made several years ago (https://github.com/satijalab/seurat/issues/5108),  so I was not sure if anything had changed. I could not find a tutorial to do this. 

Thank you in advanced!

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question. I would recommend integrating at the very end, after merging all conditions. I don't think it makes sense to do successive rounds of integration (i.e. try to integrate already integrated data).
