### ISSUE TITLE
FindAllMarkers v4 and v5

### ISSUE THREAD

**Issue by mdidish** [satijalab/seurat#9283]
Hello

I updated to Seurat 5.1.0 from Seurat 4.3.0.1, and noticed that you’ve made updates to FindAllMarkers (https://satijalab.org/seurat/articles/announcements.html). As expected, I’m getting higher log2FC values for some genes.

I’m creating a heatmap using the top 60 genes from each cluster, selecting those with the highest log2FC and adjusted p-value < 0.05 (most of the genes have a p-value of 0). The heatmap changes significantly between V4 and V5, and the V4 heatmap seems much clearer to me.

Heatmap with Seurat V4
<img src="https://github.com/user-attachments/assets/4f33dbef-02fd-46b8-a185-239abaf06497" alt="téléchargement V4" width="300">

Heatmap with Seurat V5
<img src="https://github.com/user-attachments/assets/970fe4e3-1a31-494a-a4c9-d70d600ab508" alt="téléchargement V5" width="300">

So I have two questions:
- Did you expect such a change between V4 and V5?
- Is it possible to use the V4 algorithm with V5, or should I downgrade my Seurat version?

Thank you for your help!

**Comment by samuel-marsh** [comment]
Hi,

As per other issues here yes this result is expected with the changes to how DE is calculated now in V5.  As suggested in other issues if you further filter the DE list before plotting using a pct.1/pct.2 (or pct.diff) threshold that should create better visualization.

See this issue and comments from devs: https://github.com/satijalab/seurat/issues/8462#issuecomment-2187259392

If you want to use V4 you will have to install that version of Seurat.  Though personally I would suggest staying in V5 and filtering.

Best,
Sam

**Comment by mdidish** [comment]
@samuel-marsh Thank you for your response.

Regarding the heatmap differences are not related to the change of thresholds, I have specified the same `logfc` and `min.pct`.

Here, the difference is only related to the method of calculating log2fc, with much larger FCs for RNAs very little expressed in one of the two groups with Seurat V5. On the heatmap, we see that this method of calculating log2fc leads to the selection of genes whose difference in expression is not so clear-cut. When I look at the gene names, I have among other things quite a few genes of ribosomal proteins.

My question therefore concerns the feedback from this method of calculating log2fc, for this dataset in any case it leads to selecting "bad" markers (not biologically relevant).

Best,
