### ISSUE TITLE
Error in Read10X_h5(filename = file.path(data.dir, filename), ...) :    unused argument (bin.size = c(8, 16))

### ISSUE THREAD

**Issue by NasimRahmatpour** [satijalab/seurat#9285]
Hello,
I am following this seurat tutorial for visium hd (https://satijalab.org/seurat/articles/visiumhd_analysis_vignette#load-visium-hd-data) using seurat version 5 for loading the data but it cannot recognize the bin.size argument.
object <- Load10X_Spatial(data.dir = localdir, filename= "filtered_feature_bc_matrix.h5", bin.size = c(8, 16))

Can you please help me with that? is it related to seurat version?

**Comment by cierra-walker** [comment]
Did you solve this issue? I'm running into as well.

**Comment by kokodur** [comment]
Is there a solution to this issue? I am using the demo dataset from 10x and am encountering the same problem and not having any success by adding further arguments to Load10X_Spatial. 

I have tried both maintaining the folder & file structure provided by 10x and also dumping everything into the localdir file path. All attempts yield the same error as above:

> 
> Error in Read10X_h5(filename = file.path(data.dir, filename), ...) : 
>   unused argument (bin.size = c(8, 16))

**Comment by ws500981** [comment]
I have the same issue too. Is there a solution to it yet?

**Comment by chrissikath** [comment]
I have the same issue. Seurat Version 5.1.0
