### ISSUE TITLE
RNA assay in seurat object for hdWGCNA, should I remove integrated assay?

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#9287]
Hi,
I have a seurat object containing 6 samples(seurat v4), I performed integration to correct batch effect-following [https://satijalab.org/seurat/articles/integration_introduction.html](url). Now I have two assays: "RNA" and "integrated".

I want to use this seurat object to do hdWGCNA analysis. 
1. Should I use "RNA" assay? Because I tried to use "integrated" assay, an error occur when SetupForWGCNA, and it worked when I use "RNA" assay.
2. Should I remove "integrated" assay? I tried to do MetacellsByGroups after the fisrt step in 1, it return me an ERROR again, `Error in MetacellsByGroups(seurat_obj = seurat_obj, group.by = c("cell_type",  : 
  Invalid reduction (harmony). Reductions in Seurat object: pca, umap`

The structure of my seurat object is like below:
![image](https://github.com/user-attachments/assets/221db4c3-7189-40e5-b54c-cca073c52199)

The data in "RNA" assay only be normalized, so I need to perform ScaleData, PCA and UMAP to "RNA" assay, and use the result to do hdWGCNA, right? 
If then, do I need to remove integrated assay from seurat object or I just keep it which will not affect hdWGCNA analysis?

Thank you very much!
Best

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  As this question is on best practices running hdWGCNA I would suggest posting to the GitHub repo for that package to hear from devs on best way to proceed.

Best,
Sam

**Comment by yulchen810** [comment]
@samuel-marsh I have already posted this question on hdWGCNA repo. Thank you!
