### ISSUE TITLE
GetAssayData Fails for meta.data

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#929]
```
> GetAssayData(pbmc_small, slot = "meta.data")
Error in GetAssayData(pbmc_small, slot = "meta.data") : 
  object 'to.return' not found
```

Reading the code of `GetAssayData`, I realise that it only works for `"raw.data"`, `"data"` and `"scale.data"` but the documentation vaguely suggests by its use of ellipsis that it works for more options than just those three:

> i.e. raw.data, data, scale.data, ...

**Comment by mojaveazure** [comment]
Hi Dario,

Apologies for the confusion, but `GetAssayData` only pulls data associated with expression levels from various assays (eg. RNA, CITE, etc.). We'll ensure that the documentation is clearer in the next release of Seurat.
