### ISSUE TITLE
ComputeSNN std::bad_alloc error

### ISSUE THREAD

**Issue by z5ouyang** [satijalab/seurat#9290]
Hi the Seurat team,

I do appreciate your input on how to overcome "ComputeSNN std::bad_alloc error" when expression matrix is NOT available.
This is related to [6473](https://github.com/satijalab/seurat/issues/6473)

Using seurat 5, I have a very large dataset, after getting the 'harmonized'/"batch removed" PCA reduction, my plan is to create a fake seurat object without expression matrix, to perform UMAP and cluster by Seurat:

```
# PCA <- readRDS("harmonized_PCA.rds")
D <- CreateSeuratObject(counts=data.frame(matrix(0,nrow=2,ncol=nrow(PCA),
                                                 dimnames=list(paste0("G",1:2),rownames(PCA))),check.names=F),
                        meta.data=meta)
D[['harmony']] <- CreateDimReducObject(embeddings=PCA,key="pca_",assay="RNA")
D <- FindNeighbors(D, dims = 1:dimN,reduction="harmony",verbose = FALSE)
D <- RunUMAP(D,reduction="harmony",dims = 1:dimN,
               umap.method ="umap-learn",metric = "correlation",
               verbose = FALSE)
D <- FindClusters(D,verbose = FALSE,resolution=0.8)
```
As you can tell the fake expression contains all 0, which *SOMETIMES* cause "ComputeSNN std::bad_alloc error". Questions:
1. Does the expression matrix (count/scale.data?) required for the ```FindNeighbors```?
2. Do you have any suggestions to perform UMAP/clustering without expression matrix?

Thanks in advance!

**Comment by adyzh** [comment]
Hi @z5ouyang,
Thanks for your question!
In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.
We’re going to close this issue for now but strongly encourage you to repost your question in the other forum.
We look forward to seeing your post there - thanks for using Seurat!
