### ISSUE TITLE
merging Seurat objects mapped to hg19 and hg38

### ISSUE THREAD

**Issue by shaghayeghsoudi** [satijalab/seurat#9298]
Hello,
I am working on some public data which I downloaded for the our pan cancer analysis.
Some datasets have mapped to the hg19 and some other datasets mapped to hg38. Unfortunately I do not have access to BAM or FASTQ files to perform realignments and make them consistent.
I created Seurat object for each of these datasets and now I need to merge Seurat objects  for the subsequent analysis.

Is there any way I could do this considering they have mapped to two different references?
I am simply using "merge" in Seurat but I am not sure as datasets mapped to two references, simply using "merge" makes sense.
I appreciate if you could provide any advice.
Thank you

Below are two objects as example:

```
> ecotyper_singlet_joined
An object of class Seurat 
36601 features across 58887 samples within 1 assay 
Active assay: RNA (36601 features, 2000 variable features)
 3 layers present: scale.data, data, counts
```

and 

```
> Jerby10X_singlet_joined
An object of class Seurat 
9862 features across 4024 samples within 1 assay 
Active assay: RNA (9862 features, 2000 variable features)
 3 layers present: scale.data, data, counts
```

**Comment by mccormickceci** [comment]
Hello,
Thanks for your message! This is not something that we currently have the infrastructure to solve in Seurat in terms of getting rid of any differences that might have come up through varying alignment references. However, you are probably right that this could introduce some issues with downstream analysis. I would refer you to the discussion board on our GitHub to see if anyone else has had a similar experience.
