### ISSUE TITLE
oveclustering vs underclustering approaches

### ISSUE THREAD

**Issue by amisharin** [satijalab/seurat#93]
Hi Seurat team, 

Thank you for pbmc33k tutorial and explaining there is no such thing as perfect clustering, especially on complex datasets. I understand the approach with initial overclustering and then merging similar branches (demonstrated in pbmc33k). But on large and complex tissue datasets this could get a bit complicated. I am interested in another approach as well: starting with underclustering, and then subsetting on one of the broad clusters (SubsetData), running them through another iteration of the same analysis to find finer subsets and define their identity. But what if I want to merge these final subclusters into a new Seurat object while preserving their identities (let's say to find markers for final subclusters or just for visualization purpose)? Would the approach used in Villani et al, 2017, figure 2B and supplemental R code (# Add Monocytes) work or is there a better, more robust and elegant way of doing this?

Thank you for your support.

Alexander

PS I'd be happy to get an opinion not only from Seurat team, but also from other users who faced the sample problem. Thank you.

**Comment by billytcl** [comment]
I think the easiest way (if you really want to do the split) is to get the cell names via the obj@ident == cluster_num, then subsetting from obj@raw.data. You can then plug that into a new seurat object. The easier way would be to crank up the clustering resolution, since it is graph based.

**Comment by amisharin** [comment]
Thank you. Going through overcluster and merge approach now.
