### ISSUE TITLE
Clarification on Directed vs. Undirected SNN Graph in Seurat Clustering

### ISSUE THREAD

**Issue by tim-meese** [satijalab/seurat#9312]
Dear Seurat Developers,

I have a question regarding clustering in the Seurat package. From my understanding, Seurat performs clustering on the shared nearest neighbors (SNN) graph. Could you please clarify whether this graph is directed or undirected?

I intend to apply methods from the igraph package to the SNN graph and need to construct an igraph object. In the Seurat source code, I found the function `RunLeiden()`, which constructs an igraph object using `graph_from_adjacency_matrix(adjmatrix = object, weighted = TRUE)`, resulting in a directed graph. However, I am unsure if the SNN graph itself is directed.

Thank you for your assistance.

Best regards, 
Tim

**Comment by zskylarli** [comment]
Hi - thank you for posting this issue! The SNN graph constructed in Seurat using FindNeighbors is not directed and the values in the adjacency matrix are symmetric. Please feel free to reopen the issue if you have any further questions!
