### ISSUE TITLE
Ch. 7 clustering methods

### ISSUE THREAD

**Issue by tud03125** [satijalab/seurat#9313]
Hey Everyone,

I'm working on scRNA-seq analysis pipeline using Seurat. On Ch. 7: https://www.singlecellcourse.org/biological-analysis.html, those clustering examples are very useful! The only problem is that in DimPlot, they only have "tsne," "pca" and "umap" as 'reduction' options. Not only that, but I want to try Hierarchical Clustering, K-means and "Graph-based Methods." But, I cannot see much coding examples with them. Just figures and texts about them. They do show a little coding how to get tSNE, PCA and heatmap. But otherwise, how do you set up coding to get graphical visualization/plots of 1) Hierarchical Clustering heatmap, 2) k-means clustering and 3) graph-based clustering?

**Comment by adyzh** [comment]
Hi @tud03125 ,
Thanks for your question!
In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.
We’re going to close this issue for now but strongly encourage you to repost your question in the other forum.
We look forward to seeing your post there - thanks for using Seurat!
