### ISSUE TITLE
Analyze more than 20 samples in Seurat R package

### ISSUE THREAD

**Issue by Motoufiq** [satijalab/seurat#9315]
Dear Seurat Team,

I hope you are doing well! 

I have a question, I have more than 20 scRNA-Seq samples from 4 donors and working on data analysis using Seurat R package. I always find trouble while integrating samples, and R crashes due to memory issue. All the analysis is being performed on my Mac Apple M1 Pro, 16 GB memory. In the earlier pilot project, I had 1 donor and 4 biological replicates, the integration analysis worked out. Is there a way to handle large datasets using Seurat R package. We have a R Studio installed on our HPC server, but I can only assign maximum 48G memory in that. Is there a resource or reference where I can refer and customize accordingly?

Please advise.

Best Regards,
Toufiq

**Comment by cyrillustan** [comment]
Hi Toufiq,

We have an example of handling larger datasets [here](https://satijalab.org/seurat/articles/parsebio_sketch_integration). Take a look and let us know if it does not solve your issue.

**Comment by Motoufiq** [comment]
@cyrillustan Thank you very much for the response. In my case, the number of cells combining all samples are approx. 132000 does the example you suggested works on this by considering "representative subset of cells (‘atoms’) from each dataset". I have a couple of samples with <1000 cells (one of them is approx. 700 cells, and another is approx. 910 cells).
