### ISSUE TITLE
how to integrate multiple HD Visium data

### ISSUE THREAD

**Issue by JuanXie19** [satijalab/seurat#9318]
Dear Seurat team,

I am using Seurat v5.1.0 to analyze HD Visium data, which consists of two biological replicates from a spinal cord sample. We hope to combine/integrate the two datasets and then to run clustering. I read the vignette (https://satijalab.org/seurat/articles/visiumhd_analysis_vignette), which seems to focus on single dataset analysis. I also searched and found one related issue (issue #9007), but unfortunately didn't get much useful information.  In addition, I read issue #7094 and tried to follow but failed.

Here is what I tried so far:

```
data1 <- Load10X_Spatial(data.dir = dir1, bin.size = c(8,16))
DefaultAssay(data1) <- 'Spatial.016um'

data2 <- Load10X_Spatial(data.dir = dir2, bin.size = c(8,16))
DefaultAssay(data2) <- "Spatial.016um"

data1 <- NormalizeData(data1)
data2 <- NormalizeData(data2)

data <- merge(x = data1, y = data2, add.cell.ids = c('rep1','rep2'))

```
I got an error when running the merge function:
![image](https://github.com/user-attachments/assets/eb1da5f6-c102-4e49-bdbe-1aad28efe72a)

I checked data1, and here is the basic info: 
![image](https://github.com/user-attachments/assets/7050bbe9-3c87-438c-b699-9179508f4bd2)

I also checked the spatial info, which is as follows:
![image](https://github.com/user-attachments/assets/5a5a04a6-73f8-4129-8136-d531d199dc1d)

Could you please help and see what might be the problem? I am new to HD Visium data and please pardon me if the question is too naive.

Thanks!

**Comment by adyzh** [comment]
Hi @JuanXie19, Thanks for your question!
I am not sure what is the purpose for integrating multiple Visium datasets, though merge() works with merging the counts of two Seurat objects. Sketching is generally used for highly scalable analysis with large number of cells. 
In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.
We’re going to close this issue for now but strongly encourage you to repost your question in the other forum.
We look forward to seeing your post there - thanks for using Seurat!

**Comment by BenxiaHu** [comment]
@adyzh do you think it is not a good idea to integrating multiple Visium HD datasets before normalization?

I have annother question, do you think normalizing individual samples and merging these normalized matrices before downstream analysis, such as dimension reduction is a good idea?
