### ISSUE TITLE
Seurat v3.0 alpha issues

### ISSUE THREAD

**Issue by star0044** [satijalab/seurat#932]
Dear Seurat developers,

Just installed the Seurat v3.0 alpha version.  I have three questions/issues

1) In `FindMarkers` (and `FindAllMarkers`), if I try to use "negbinom" or "poisson" I get the following error message
```R
> custom_cluster_markers <- FindMarkers(patient, assay = "RNA", 
+           ident.1 = 0, ident.2 = 1, features = NULL, 
+           logfc.threshold = 0.25, test.use = "negbinom", 
+           min.pct = 0.1, min.diff.pct = -Inf,
+           verbose = TRUE, only.pos = FALSE, 
+           max.cells.per.ident = Inf, random.seed = 1, 
+           min.cells.feature = 3,
+           min.cells.group = 3, pseudocount.use = 1)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 332, 0
```
When I run `FindAllMarkers`, not matter how I change the parameters I get:
```R
Warning message:
In FindAllMarkers(patient, assay = "RNA", features = NULL, logfc.threshold = 0.25,  :
  No DE genes identified.
```

The other tests, "wilcox", "bimod", "roc", "t" all work fine.  My data is UMI data.  Not sure why this is the case.  Am I doing something wrong, or is this a bug?

2) The `FilterCells` option is gone. Is there a way to filter out the high mitochondrial % cells, other than manually doing it before loading the matrix?

3) The `BuildClusterTree` function is gone.  Are you going to add it back in?

**Comment by GabeFalcao** [comment]
Regarding your question 2, I had the same thought and they answered here #926.

**Comment by ChristophH** [comment]
regarding 1, this was indeed a bug and has now been fixed

**Comment by GabeFalcao** [comment]
I'm having a weird error on the differential analysis that I thought was not worth opening a new issue @ChristophH . Using the same dataset, I'm able to run FindMarkers with "wilcox", "bimod", "roc", and others, but if I try to do "negbinom", "poisson", "DESeq2", I get this error:  

`allsmc.klf4kovswts.de.genes <- FindMarkers(klf4kovswts.to.test, ident.1 = "SMC_Klf4_KO_eYFP_Positive", ident.2 = "SMC_Klf4_WT_eYFP_Positive", print.bar = FALSE, test.use = "negbinom")
Error in FindMarkers.default(object = data.use, cells.1 = ident.1, cells.2 = ident.2,  : 
  The following cell names provided to cells.1 are not present:`  

Do I need to pass more information for those tests specifically or is this just a bug?  
Also, are you discontinuing `tobit` for Seurat v3? That is not an option anymore and I'm just wandering why.

Thanks!

Gabe

**Comment by ChristophH** [comment]
Hi Gabe,

The tests are working for me using the latest version of v3 alpha. When you
specify "negbinom", "poisson", or "DESeq2" as test method we internally use
the count matrix instead of the normalized data. It seems like for some
reason the cell names do not match.

What does WhichCells(klf4kovswts.to.test, idents
= "SMC_Klf4_KO_eYFP_Positive") return? If it returns the correct cell
names, are those also present as column names in klf4kovswts.to.
test[['RNA']]@counts ?

Please also provide the traceback of the error by typing traceback() after
the error occurs.

Best,
Christoph

**Comment by GBeattie** [comment]
Hey Gabe and Chistoph,

I had an identical error with my analysis, until I realised my active.ident ="integrated". After changing this to RNA (DefaultAssay(object) <- "RNA"), negbinom worked just fine.
