### ISSUE TITLE
scRNA-seq data integration Harmony 

### ISSUE THREAD

**Issue by nmhc98** [satijalab/seurat#9324]
Hello, I loaded data from 39 patients and created a merged seurat object with 39 layers (counts). I am interested in compare tissue types (Tumor Primary and Metastasis Liver),  so I labelled my samples in meta.data with two extra columns: "Type" and "Patient".  
I couldn't integrate data because of the multiple layers so I decided joinLayers[RNA] before starting the pre-proccessing workflow and the integration, when I performed RunHarmony split.by="Type".
I don't know if this method is correct.
Moreover, I wanted to perform automatic cell-annotation but I don't know if it's better to do that before or after integration. 

Best regards, 
Nerea

**Comment by dcollins15** [comment]
Hi @nmhc98,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
