### ISSUE TITLE
Add spatial coordinate based meta.data for Xenium

### ISSUE THREAD

**Issue by NathanKochhar** [satijalab/seurat#9333]
I am working on a Xenium analysis and an image slide with multiple samples on it and I wanted to add meta.data to my seurat object by the spatial coordinates of the samples. It was tricky to figure out but I did it using the following.

find the coordinates of a specific sample 
`cropped.coords <- Crop(xenium.obj[["fov"]], x = c(0, 5200), y = c(0, 9000), coords = "plot")
`

add sample meta.data from coordinates
`xenium.obj$sample[cropped.coords@boundaries[["centroids"]]@cells] <- "sample1"
`

I hope this helps someone!

**Comment by RajneeshSrivastava** [comment]
coords = "tissue" instead of "plot" might do the magic!
