### ISSUE TITLE
FindMarkers undocumented changes

### ISSUE THREAD

**Issue by roi-meir** [satijalab/seurat#9337]
Hi 
Recently we discovered some undocumented changes in the FindMarkers function that can drastically change the results of the differential expression analysis. This step is a major step that affects the interpretation of biological results, further analysis, and comparison to other studies.  
Examples of such changes
- Changing the pseudocount computation - [commit 69b054b](https://github.com/satijalab/seurat/commit/1eb852dff43663e5dc3f02c0ef09b03adb2e3163)
- Changing the default values of `logfc.threshold` and `min.pct`  - [commit d6b0152ab](https://github.com/satijalab/seurat/commit/d6b0152ab6f794a9736cdf0b9f81d83d91f16651) 

I think that such changes that change the default behavior should be documented in the NEWS file and be accompanied by a discussion of the scientific rationale behind the change.

Thank you very much for the package development!

**Comment by dcollins15** [comment]
Thanks for reaching out @roi-meir 

The changes to pseudocount are discussed in the [v5 release announcement](https://satijalab.org/seurat/articles/announcements) — AFAIK the updates to `logfc.threshold` and `min.pct` follow from that change. 

Your point about making sure the changelog is complete and accurate is well taken 🙂

**Comment by roi-meir** [comment]
Thank you @dcollins15 for developing this great package!

I looked at the `NEWS.md` file and missed the v5 announcement. 

I'm still unsure how changing `logfc.threshold` is related to this change. Since the added pseudocount is now smaller (at least for n>10), the log fold change after the update will be larger so if some change is needed I would've expected an increase in this threshold instead of a decrease.
