### ISSUE TITLE
Errors while adding MetaData

### ISSUE THREAD

**Issue by aditisk** [satijalab/seurat#935]
I am trying to add labels to my data and I am running into issues.  I am trying to set up all the metadata in an Excel sheet and import that into Seurat. I am looking to add labels like patient ID, HPV Status etc.  

Here is what I have tried so far:

•	Once I import my data and create a Seurat object, I exported the `obj@cell.names` table. 
•	I added corresponding labels in a column(s) next to the barcodes. So basically the dimensions of this file are number_of_barcodes x metadata_variables. Does each variable need to have a column name ? I have tried with and without and neither work for me.
•	I am importing this sheet back into R and using `AddMetaData()` to add this back to my Seurat object. I see the column name added in `obj@meta.data` but the values are all <N/A>. 

I am not sure why this isn’t working so any help is appreciated. Ideally I want to be able to add multiple labels at the same time. If that isn’t possible, one at a time is also okay.

Thank you so much.

**Comment by andrewwbutler** [comment]
When you import the metadata back into R, it should be a `data.frame` where the row names correspond exactly to the cell names of the Seurat object and the column names correspond to the metadata variables. You should then be able to use `AddMetaData` to add that `data.frame` to your Seurat object. 

If that still doesn't work, could you provide a small reproducible example of the problem so we can replicate it for debugging?

**Comment by aditisk** [comment]
Hi Andrew, 

Thanks for the response. I am yet to try the spreadsheet thing but I was able to add metadata via code to my Seurat object. The mistake I was making was that the cell names were column 1 of my dataframe instead of being "rownames". Once I changed that, it worked fine. Thanks for your help.

**Comment by ibseq** [comment]
Hi aditisk
having similar prob where I got the "NA"
> head(pbmc@meta.data)
                   orig.ident nCount_RNA nFeature_RNA Barcode cell.types
AAACCTGGTTCCCTTG-1     pbmc3k        610          393    <NA>       <NA>
AAACCTGTCACTTCAT-1     pbmc3k       1106          543    <NA>       <NA>
AAACGGGAGAGAACAG-1     pbmc3k        821          426    <NA>       <NA>

I had a cvs file imported from 10x where each barcode is assigned a cell type, I added this to my object using addmetadata:

pbmc <- AddMetaData(object = pbmc, metadata = read.csv("/Users/ibseeq

/Desktop/gem1_cell_types.csv"), col.name = "Barcode")

but I am still not able to see my 4 clusters as this was the aim of adding the metadata

any guide/help on how to do this correctly on the published tutorial from https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

thanks
ibseq

**Comment by aditisk** [comment]
Hi @ibseq, the cell barcodes should be the rownames of your metadata table. It looks like you are adding your barcodes as column names which may be the issue. I hope this helps.

**Comment by ibseq** [comment]
HI aditisk
do I need to change my cvs? a command will really help!
Also tried something different:
I imported the cvs as data.frame as I read this in another issue, I do not have the "NA" anylonger but I cannot see still my clusters...I still see the premade clusters. 
How I can run the pbmc guided tutorial to end up having my 4 clusters?
this is what I have done:
> library(Seurat)
> library(Matrix)
> library(patchwork)
> library(dplyr)
> pbmc <- CreateSeuratObject(counts = pbmc.data$`Gene Expression`, project = "pbmc3k", min.cells = 3, min.features = 200)
> pbmc
> mydata <- read.csv("//Users//ibseeq//Desktop//gem1_cell_types.csv", header = TRUE)
> df <- data.frame(mydata)
> print (df)
>pbmc <- AddMetaData(object = pbmc, metadata = mydata, colnames("Barcode"))
>

**Comment by ibseq** [comment]
I had help from another user to properly add the metadata to my object, but how do we enforce to use the premade clusters rather than what is on the pipeline? the imported data into my object is like not doing any difference ...

**Comment by hira-anis** [comment]
metadata = read.csv('path_to_csv', header = TRUE, row.names = 1) , helped remove the NAs when using
seuratobject <- AddMetaData(object = seuratobject, metadata = metadata)

**Comment by overcrowded-mick** [comment]
> Hi aditisk having similar prob where I got the "NA"
> 
> > head([pbmc@meta.data](mailto:pbmc@meta.data))
> > orig.ident nCount_RNA nFeature_RNA Barcode cell.types
> > AAACCTGGTTCCCTTG-1     pbmc3k        610          393           
> > AAACCTGTCACTTCAT-1     pbmc3k       1106          543           
> > AAACGGGAGAGAACAG-1     pbmc3k        821          426
> 
> I had a cvs file imported from 10x where each barcode is assigned a cell type, I added this to my object using addmetadata:
> 
> pbmc <- AddMetaData(object = pbmc, metadata = read.csv("/Users/ibseeq
> 
> /Desktop/gem1_cell_types.csv"), col.name = "Barcode")
> 
> but I am still not able to see my 4 clusters as this was the aim of adding the metadata
> 
> any guide/help on how to do this correctly on the published tutorial from https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html
> 
> thanks ibseq





https://stackdev.space/questions/combine-the-names-of-specific-columns-into-a-single-cell-for-every-row-in-the-dataset
