### ISSUE TITLE
Issue with reference mapping after integration in Seurat v5

### ISSUE THREAD

**Issue by YannLeGuen** [satijalab/seurat#9353]
Hi,
I note that my issue is similar to the two issues described at:
#https://github.com/satijalab/seurat/issues/8566
#https://github.com/satijalab/seurat/issues/6064
but these were closed without being resolved.

Briefly, I have integrated 4 datasets with the following code:
```
combined <- merge(obj1, y = c(obj2, obj3, obj4), 
                  add.cell.ids = c("obj1", "obj2", "obj3", "obj4"), project = "object")
combined[["percent.mt"]] <- PercentageFeatureSet(combined, pattern = "^MT-")
combined <- SCTransform(combined, method = "glmGamPoi", vars.to.regress = "percent.mt", vst.flavor = "v2")
combined <- RunPCA(combined, npcs = 50)
combined <- IntegrateLayers(object = combined, method = HarmonyIntegration, 
                            orig.reduction = "pca", new.reduction = 'harmony', 
                            assay = "SCT", verbose = TRUE)
combined <- FindNeighbors(combined, reduction = "harmony", dims = 1:30)
combined <- FindClusters(combined, resolution = 1, cluster.name = "harmony_clusters")

combined <- RunUMAP(combined, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
combined <- RunTSNE(combined, reduction = "harmony", dims = 1:30, reduction.name = "tsne.harmony")
output <- paste0(dr0, 'combined_ref_UMAP.rds')
saveRDS(combined, output)
```

I annotate the clusters in this combined object.

Then, I reload this object as reference with two new objects with cells to annotate
```
nobj1 <- CreateSeuratObject(counts = nojb1_data, 
                            project = "nobj_1", 
                            min.cells = 3, min.features = 200)
nobj2 <- CreateSeuratObject(counts = nojb2_data, 
                            project = "nobj_2", 
                            min.cells = 3, min.features = 200)
combined <- merge(nobj1, y = c(nobj2), 
                  add.cell.ids = c("nobj1", "nobj2"), project = "object")
combined[["percent.mt"]] <- PercentageFeatureSet(combined, pattern = "^MT-")
combined <- SCTransform(combined, method = "glmGamPoi", vars.to.regress = "percent.mt", vst.flavor = "v2")
rds <- paste0(dr0, 'combined_ref_UMAP.rds')
combined_ref<- readRDS(rds)
combined.anchors <- FindTransferAnchors(reference = combined_ref, query = combined, dims = 1:30,
                                        reference.reduction = "harmony",
                                        normalization.method="SCT",
                                        reference.assay="SCT")
predictions <- TransferData(anchorset = combined.anchors, refdata = combined.ref$harmony_clusters, dims = 1:30)
combined <- AddMetaData(combined, metadata = predictions)
```
I get the following error while using FindTransferAnchors:

> Error: Given reference assay (SCT) has 4 reference sct models. Please provide a reference assay with a  single reference sct model.

Could you indicate if SCT can be used in this or suggest an alternative method if that's not the case?

Thanks,
Yann

**Comment by FourAlarmFire** [comment]
> Hi @YannLeGuen, Thank you for reaching out! We’re always grateful when folks take the time to help make Seurat better 🙂. To answer your question, running integration using the v3 way for an "integrated" assay for FindTransferAnchors is the current work-around. We are working on making this process more clear for users!

sorry, does the v3 way means Seurat v3? I have no idea of 'the v3 way for an "integrated" assay for FindTransferAnchors'

**Comment by mmfalco** [comment]
[Here](https://github.com/satijalab/seurat/issues/8938#issuecomment-2541548843) is described the v3 pipeline which helped me to solve the issue.
