### ISSUE TITLE
Why removing ICA support ?

### ISSUE THREAD

**Issue by Fougere87** [satijalab/seurat#936]
Hi all and many thanks to Seurat developers for their work !

One question, I just installed the 3.0 alpha and I can see their is no RunICA anymore ? 
Is their a reason to that ? It was really useful to us here... !

Best, 
Chloé

**Comment by satijalab** [comment]
That's great to hear and thanks for the feedback. We released v3 as an alpha because we have not had time to add back all functionality, and will make sure to include RunICA in the full release.

**Comment by Fougere87** [comment]
I understand their is quite a lot work stacked up for this new version...
Glad to hear their will be support then :-)

Thanks again for your work !
