### ISSUE TITLE
SCtransform documentation error

### ISSUE THREAD

**Issue by gevro** [satijalab/seurat#9370]
Hi, The below two items contradict each other, because return.only.var.genes = TRUE by default, so it's not clear why conserve.memory sets return.only.var.genes to TRUE if that is already the default.

conserve.memory

    If set to TRUE the residual matrix for all genes is never created in full; useful for large data sets, but will take longer to run; this will also set return.only.var.genes to TRUE; default is FALSE

return.only.var.genes

    If set to TRUE the scale.data matrices in output assay are subset to contain only the variable genes; default is TRUE

**Comment by dcollins15** [comment]
I'm not sure I see the contradiction. When passing `conserve.memory=TRUE`, setting `return.only.var.genes=FALSE` has no effect.
