### ISSUE TITLE
Extract normalised count after integration

### ISSUE THREAD

**Issue by martina811** [satijalab/seurat#9371]
Hello everyone, 
I am performing integration with Seurat v.5 following this tutorial https://satijalab.org/seurat/articles/seurat5_integration and  I am currently using the CCA integration method. Once I performed the integration I want to extract the normalised count of the integrated dataset, so I run the comand _obj <- JoinLayers(obj)_ after the integration. 

In the 'count' slot do I have the normalised count that are corrected after the integration procedure? 
Or the 'count' slot after JoinLayers just contain the merged normalized count of the dataset I integrated? If yes, how to access to the normalised count corrected also after the integration? 

Thank you all for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Most integration techniques including what you mentioned do not correct the count matrix.  The integration is performed with embeddings (hence recommendation to switch back to RNA assay for DE).  Some methods that correct count matrices with integration have been reported to suffer from a number of biases and are not commonly recommended.  

Best,
Sam
