### ISSUE TITLE
Create Seurat Object Command runs and never stops

### ISSUE THREAD

**Issue by ambreen321kanwa** [satijalab/seurat#9372]
Hello All,
I loading a publicly available dataset and making a seurat object. The data is loaded perfectly but it never makes seurat object.
Here are the commands that I have used to load 10X data. First ten rows and first 10 columns command shows it is sparse matrix. str   () command shows its structure but it never makes Seurat object. Anyone can please help me figuring it out

data_dir <- '/home/work/....................'

list.files(data_dir) # Should show barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz
[1] "barcodes.tsv.gz" "features.tsv.gz" "matrix.mtx.gz" 

data <- Read10X(data.dir = data_dir)

data[1:10, 1:10]
10 x 10 sparse Matrix of class "dgCMatrix"
[[ suppressing 10 column names ‘AAACCCAAGAAACACT-1’, ‘AAACCCAAGAAACCAT-1’, ‘AAACCCAAGAAACCCA-1’ ... ]]

MIR1302-2HG . . . . . . . . . .
FAM138A     . . . . . . . . . .
OR4F5       . . . . . . . . . .
AL627309.1  . . . . . . . . . .
AL627309.3  . . . . . . . . . .
AL627309.2  . . . . . . . . . .
AL627309.5  . . . . . . . . . .
AL627309.4  . . . . . . . . . .
AP006222.2  . . . . . . . . . .
AL732372.1  . . . . . . . . . .

str(data)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
..@ i       : int [1:45976098] 2208 13488 25237 3921 4980 8311 6790 4946 3870 12642 ...
..@ p       : int [1:6794881] 0 0 0 3 3 3 4 4 5 6 ...
..@ Dim     : int [1:2] 36601 6794880
..@ Dimnames:List of 2
.. ..$ : chr [1:36601] "MIR1302-2HG" "FAM138A" "OR4F5" "AL627309.1" ...
.. ..$ : chr [1:6794880] "AAACCCAAGAAACACT-1" "AAACCCAAGAAACCAT-1" "AAACCCAAGAAACCCA-1" "AAACCCAAGAAACCCG-1" ...
..@ x       : num [1:45976098] 1 1 1 1 1 1 1 1 1 1 ...
..@ factors : list()

seurat_object = CreateSeuratObject(counts = data)

It would be greatly appreciated

**Comment by samuel-marsh** [comment]
Hi,

How much RAM do you have on your system.  It looks like you trying to load dataset with nearly 7 million cells?

Best,
Sam

**Comment by ambreen321kanwa** [comment]
Thank you for your response Sam
My current RAM is 32GB

**Comment by wangbenwang123** [comment]
A dataset containing 7 million single cells is highly unlikely to exist. Please double-check your data source.

**Comment by samuel-marsh** [comment]
Hi,

I would not necessarily be dismissive of a dataset of 7 million cells, they do exist, but it is wise to check that dimensions match expected number of cells.  However, in memory 32GB will not be enough for such a dataset.  I would suggest looking into the Seurat BPCells vignettes for large datasets.

Best,
Sam

**Comment by ambreen321kanwa** [comment]
Thanks for the advice.
It is greatly appreciated
Regards
Ambreen
