### ISSUE TITLE
Issue with CreateSeuratObject using TPM txt data

### ISSUE THREAD

**Issue by hyunsik1214** [satijalab/seurat#9373]
Hi, I wanted to conduct single cell seq analysis using the data from [here](https://ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120575), and the data is in TPM that has already gone through QC, and thus, it is not a raw data with integers.
So, what I did was I first brought up the data using read.delim and tried to create Seurat object using the CreateSeuratObject function because I saw some discussions that said I can still continue to create Seurat Object with normalized data like TPM.
Below are my codes:

feldman <- read.delim("GSE120575/GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt.gz", header = T, stringsAsFactors = F)

feldman.object <- CreateSeuratObject(counts = feldman)

However, there is an error that said
"Counts matrix provided is not sparse. Creating V5 assay in Seurat Object.
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in validObject(.Object) : 
  invalid class “LogMap” object: Rownames cannot be empty strings".
![2](https://github.com/user-attachments/assets/8ed6cdab-941c-4a60-920a-13966681b884)
This seems like more than one error and I have no idea what I have to solve. I would greatly appreciate if anyone can help! Thank you so much.

I have attached how the TPM data looks like.
![캡처](https://github.com/user-attachments/assets/c36b561f-1698-4a73-84b7-7ba473a71b67)
![1](https://github.com/user-attachments/assets/f1f49f60-66fd-4952-9ca2-99ac646af1a1)

**Comment by samuel-marsh** [comment]
Hi,

It seems likely that issue probably comes from your first row which is not numerical data.  If you remove that row does code work?

Best,
Sam

**Comment by hyunsik1214** [comment]
Hi Sam,

Thank you for the advice. I have tried that method just now, but it shows this error below:
Counts matrix provided is not sparse. Creating V5 assay in Seurat Object.
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric

![캡처](https://github.com/user-attachments/assets/c82293a6-e702-43ea-b683-d27440ed5480)

I have no idea what that Error in base is..

**Comment by samuel-marsh** [comment]
So it would appear that there are other rows that contain non-numeric data.  I would filter the matrix to remove those and try creating the object again.

Best,
Sam

**Comment by hyunsik1214** [comment]
Thank you for the advice!
I am really sorry and I am quite new to R. After searching up the method to remove the rows with non-numeric data, I tried to use the function as.numeric() followed by na.omit(). However, it doesn't seem to work as an error pops up even from the first step:
Error: 'list' object cannot be coerced to type 'double'

By any chance, do you have any idea on how to remove the rows with non-numeric data?

**Comment by samuel-marsh** [comment]
Hi,

I would try something like this: https://stackoverflow.com/questions/39871229/in-r-remove-rows-containing-no-integer-such-as-characters-i-e-from-a-data-fr

If you still have issues after removing non-numeric data please post here and I can reopen the issue but that should solve your issue.

Best,
Sam

**Comment by wangbenwang123** [comment]
I tried reading the data myself.
I found that the issue lies in the format of the original data, specifically the first two header lines, as well as the last column being ’NA‘. The correct code is as follows:

```r
feldman <- read.delim("GSE120575_Sade_Feldman_melanoma_single_cells_TPM_GEO.txt.gz", header = F, row.names = NULL, stringsAsFactors = F)
test <- feldman[-2,]
# length(unique(feldman[,1]))
colnames(test) <- test[1,]
test <- test[-1,]
rownames(test) <- test[,1]
test <- test[,-1]
test[1:5,1:5]
test <- as.matrix(test)
genes <- rownames(test)
samples <- colnames(test)
test <- matrix(as.numeric(test), nrow = nrow(test), ncol = ncol(test))
rownames(test) <- genes
colnames(test) <- samples
na_counts <- colSums(is.na(test))
num_na_cols <- sum(na_counts > 0)
print(num_na_cols)
cols_with_na <- which(na_counts > 0)
print(cols_with_na) # The last column is found to contain NA, removing this column
test <- test[,-cols_with_na] 

library(Seurat)
feldman.object <- CreateSeuratObject(counts = test)
rm('test')
# Reading coldata

# Read all lines of the file
lines <- readLines("GSE120575_patient_ID_single_cells.txt")

# Find the starting line of the "SAMPLES" section
sample_start <- grep("^SAMPLES", lines)

# Find the starting line of the "PROTOCOLS" section
sample_end <- grep("^PROTOCOLS", lines)

# Extract lines from "SAMPLES" to the line before "PROTOCOLS"
sample_lines <- lines[(sample_start + 3):(sample_end - 1)]

# Use trimws() to remove leading and trailing whitespace and remove empty lines
sample_lines <- sample_lines[trimws(sample_lines) != ""]

# Use read.delim to convert the extracted sample data into a data frame
sample_data <- read.delim(textConnection(sample_lines), sep = "\t", header = TRUE, stringsAsFactors = FALSE)

# Check the first few rows of the data frame
head(sample_data)
sample_data <- sample_data[,1:7]

identical(colnames(feldman.object@assays[["RNA"]]), sample_data$title) # Check if the title column in coldata matches the column names of feldman.object

feldman.object <- AddMetaData(feldman.object, metadata = sample_data)
```

**Comment by hyunsik1214** [comment]
Hi @wangbenwang123 ,
I have tried with your code, and it works perfectly! Thank you so much!
Thank you @samuel-marsh for the advice!
