### ISSUE TITLE
VlnPlot group.by

### ISSUE THREAD

**Issue by caofan** [satijalab/seurat#9375]
In VlnPlot, the default value of group.by is NULL. But when 'seurat_clusters' is present, it will be automatically used to group the cells. The default behavior of VlnPlot is not very clear in the documentation. I

By the way, is there a proper way to force the group.by to turn off even if those metadata exist?

**Comment by wangbenwang123** [comment]
In fact, the default grouping in `VlnPlot` is determined by `Idents(seurat_obj)`. However, every time you execute `FindClusters` (if you do not specify the `cluster.name` parameter), it will overwrite `'seurat_clusters'` and set it to `Idents(seurat_obj)`. So, if you do not want to group the cells in `VlnPlot`, you can first execute the following code:

```R
Idents(object) <- "all" 
VlnPlot(seurat_obj,features = features )
```

**Comment by samuel-marsh** [comment]
Hi,

I will add that in addition to plotting across all samples you can set active ident to any meta.data variable using code stated above but supplying the meta.data column name.  This behavior is similar to DimPlot which will also use the active ident unless an alternative is specified to `group.by`.

Best,
Sam
