### ISSUE TITLE
HTODemux not accurately classifying data?

### ISSUE THREAD

**Issue by andreanperry** [satijalab/seurat#9377]
I have data containing two barcodes. Below I've included the code I use to do the demultiplexing. When I look at a feature scatter plot of the data filtered only for singlets, it seems HTODemux has classified most of one of the barcodes as negative and for the other barcode, classifies what I would think (by eye) seem to be doublets as singlets (see plot included). Additionally the output of HTODemux is:  

# Run HTODemux for demultiplexing
> seurat_obj <- HTODemux(seurat_obj, assay = "HTO", positive.quantile = 0.999)
Cutoff for TotalSeq-B0303 : 11642 reads
Cutoff for TotalSeq-B0305 : 39 reads

Any thoughts on what the issue could be? I've tried recommendations from other similar questions on this forum (like normalizing across cells instead of features) but nothing so far has worked.

---CODE BELOW---

# Load Seurat library
library(Seurat)

# Load the 10X data for gene expression and antibody capture (HTO data)
data <- Read10X(data.dir = "/datapath/count/sample_filtered_feature_bc_matrix/")

# Extract gene expression (GEX) and hashtag oligonucleotide (HTO) data
gex_data <- data$`Gene Expression`
hto_data <- data$`Antibody Capture`

# Remove specific HTO features "TotalSeq-B0304" and "TotalSeq-B0306" from hto_data
hto_features_to_keep <- setdiff(rownames(hto_data), c("TotalSeq-B0304", "TotalSeq-B0306"))
hto_data <- hto_data[hto_features_to_keep, ]

# Create Seurat object for gene expression data (RNA)
seurat_obj <- CreateSeuratObject(counts = gex_data, project = "cell_hashing")

# Add the HTO data (hashtag oligonucleotides) as a new assay
seurat_obj[["HTO"]] <- CreateAssayObject(counts = hto_data)

# Normalize RNA data
seurat_obj <- NormalizeData(seurat_obj)

# Check average expression
AverageExpression(seurat_obj, assays ="HTO", layer = "counts")

# Normalize HTO data using centered log-ratio (CLR) transformation
seurat_obj <- NormalizeData(seurat_obj, assay = "HTO", normalization.method = "CLR", margin=1)

# Run HTODemux for demultiplexing
seurat_obj <- HTODemux(seurat_obj, assay = "HTO", positive.quantile = 0.999)

# Add demultiplexed sample identities as metadata
Idents(seurat_obj) <- "HTO_classification.global"

# Assign labels based on the HTO classification
seurat_obj$sample_label <- ifelse(seurat_obj$HTO_classification == "TotalSeq-B0303", "Sample 20",
                                  ifelse(seurat_obj$HTO_classification == "TotalSeq-B0305", "Sample 25", NA))

# Find variable features for RNA data
seurat_obj <- FindVariableFeatures(seurat_obj)

# Scale RNA data
seurat_obj <- ScaleData(seurat_obj)

# Perform PCA on RNA data
seurat_obj <- RunPCA(seurat_obj)

# Run UMAP on PCA-reduced data
seurat_obj <- RunUMAP(seurat_obj, dims = 1:10)

# Plot UMAP, coloring by the newly assigned sample labels
DimPlot(seurat_obj, reduction = "umap", group.by = "sample_label")
---
![Rplot](https://github.com/user-attachments/assets/cb74c606-b17c-4018-afdd-53553e7e8826)

**Comment by zskylarli** [comment]
Hi - did you generate this plot with the DimPlot function, since this seems like a FeaturePlot? We're unable to reproduce the issue, so if you can double check your code (especially the ifelse statements, since that seems like it could be problematic) and reopen this issue following our guidelines of providing reproducible code.
