### ISSUE TITLE
Will sequencing depth correction lower gene expression values in groups B and C if group A has much higher sequencing depth?

### ISSUE THREAD

**Issue by Jiahuan90** [satijalab/seurat#9379]
Hi,

I have three groups of single-cell samples: A, B, and C. The sequencing depth of group A is significantly higher than that of groups B and C. I am concerned that when I combine all three groups for analysis, even after applying sequencing depth correction, the expression levels of some genes (e.g., KLRC2) in groups B and C become undetectable.

Is it possible that the higher sequencing depth in group A is causing the correction to reduce the gene expression values in groups B and C, masking the true expression differences between the groups? How should I handle this issue in the analysis to avoid losing important signals from groups B and C?

Thank you for your kindly help!!

![2](https://github.com/user-attachments/assets/24410fd9-eead-497d-bb73-1fde9517b7cd)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  What kind of sequencing depth correction are you referring to?  Is this specific to Seurat or more general question?

Best,
Sam

**Comment by Jiahuan90** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. What kind of sequencing depth correction are you referring to? Is this specific to Seurat or more general question?
> 
> Best, Sam

Hello Sam, 

I'm looking for SCTransform + IntegrateLayer sequencing depth correction. The question is specific to Seurat~

Best,
Jiahuan

**Comment by mhkowalski** [comment]
Hi, 

I'm afraid I'm not able to answer your question based on what has been provided. We generally recommend that you use tools like SCT + IntegrateLayers to perform batch correction, but then you should use the original gene expression to perform differential expression analysis, etc. Therefore, applying batch correction will not alter the original gene expression. 

If you'd like to open a new issue explaining the exact analysis/code you are performing and visualization of the problem you are encountering, we'd be happy to take a look.
