### ISSUE TITLE
Plotting specific Groups on DimPlot

### ISSUE THREAD

**Issue by GabeFalcao** [satijalab/seurat#938]
Hello again,

A different question regarding the Seurat v3. On Seurat v2, I was able to plot on the TSNEPlot function, several groups of cells using a command like this: 
`TSNEPlot(allcells, do.label = F, cells.use = grep("tdtomato", allcells@cell.names, value = T), pt.size = 1, plot.title = "tdTomato Cells")`. 

This was an easy way to pull only the specific cells from the several combined experiments (I had tdtomato 1, 2 and 3 in the allcells, plus a couple of other libraries).  

I'm trying to do something similar now, but 1: there is no cell.names any more in the new seurat object. 2: I tried this: 

`DimPlot(object = all.cells, cells.use= grep("Klf4_WT", athero.integrated@meta.data$origin, value = T), reduction = "umap", label = FALSE, pt.size = 0.85)` . That plotted all the cells. 

An alternative would be to subset the data to plot. I have another issue with this. I have two groups to subset simultaneously (Klf4_WT_eYFP_Positive and Klf4_WT_eYFP_Negative). I tried this: 

`WT_CELLS <- subset(all.cells, origin == grep('^Klf4_WT_eYFP',all.cells@meta.data$origin, value=TRUE))` and I get this error:

`Warning message:
In origin == grep("^Klf4_WT_eYFP", all.cells@meta.data$origin,  :
  longer object length is not a multiple of shorter object length`

The object is generated, but the number of cells is incorrect. I also tried using an "or" option and use the whole name for the subset: "Klf4_WT_eYFP_Positive" | "Klf4_WT_eYFP_Negative", but that appears to be only for numeric/logical/complex.  

The help function tells me there is a `cells` on the DimPlot, but how can I select cells from 2 out 4 experiments to be plotted? I can't seem to find on the seurat object the cells or how they are different on the integrated object to be able to use "grep".

Thanks!

Gabriel

**Comment by satijalab** [comment]
You can type Cells(object) to get a list of cell names.

We'll make sure to make this clearer in the eventual docs, though it is listed on the current cheat sheet (see the  object interaction tab at : https://satijalab.org/seurat/essential_commands.html)

Also, please don't hesitate to ask questions like this on the GitHub, we'll do our best to be responsive. Even with a full set of documentation there will be some questions that arise, and we (and hopefully community members here) will do our best to help.

best,
Rahul

**Comment by GabeFalcao** [comment]
This is helpful @satijalab! And thank you very much for all your work and fast response!
