### ISSUE TITLE
PrepSCTFindMarkers before or after FindNeighbors/FindClusters/RunUMAP

### ISSUE THREAD

**Issue by gevro** [satijalab/seurat#9380]
Hi, Does it matter whether PrepSCTFindMarkers is run before or after FindNeighbors/FindClusters/RunUMAP?

All workflows I've seen run it after FindNeighbors/FindClusters/RunUMAP, but it seems to me like it is still ok to run it before. Is that correct?

**Comment by samuel-marsh** [comment]
Hi @gevro,

So that particular function only needs to be run in instances when you are going to run `FindMarkers`.  Just for clarity in your analysis I think it’s probably best to run it immediately before running `FindMarkers` as note all analysis require this step.

Best,
Sam

**Comment by gevro** [comment]
Thanks. But in principle, would it still work if it is run before FindNeigbors/FindClusters, i.e. it won't affect those functions at all?

**Comment by me-orlov** [comment]
Hi @gevro and @samuel-marsh ,

I am also wondering about the same thing! Does it change anything if I run or re-run FindNeigbors/FindClusters/RunUMAP after performing this step? Do you have any further insights about this that you might share? Thank you in advance!
