### ISSUE TITLE
Error in Ops.data.frame(guide_loc, panel_loc) : 

### ISSUE THREAD

**Issue by LiHangzls** [satijalab/seurat#9383]
> DimPlot(seuratobject)
Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames

This is my error code and prompt. I'm not sure if it's because I updated the environment. But many functions of my Seurat can't be used anymore. Please help me check it.

**Comment by longmanz** [comment]
Hi, 
This is actually not a Seurat problem, but a incompatibility issue between the "patchwork" and the "ggplot2" packages (see https://github.com/thomasp85/patchwork/issues/342 for details). You can fix it by re-installing patchwork to the latest version.

**Comment by AMAwatermelon** [comment]
update patchwork does work
