### ISSUE TITLE
Is normalized data in SCT assay can be phenotype for eQTL phenotype?

### ISSUE THREAD

**Issue by tewengtong** [satijalab/seurat#9384]
Dear Author,

I am currently using Seurat v5 SCTransform to do normalization. I wonder is that okay to use the SCT assay data slot to be phenotypes for eQTL analysis? If not, may I trouble you to give me some clues on which data I should use to do it after integration? Do I need to re-normalize the integrated data set or use the expression matrix from each library in one integrated object?

Looking forward to your reply!

Thank you!

Best,
Yihan

**Comment by longmanz** [comment]
Hi,
Do you plan to run single-cell cell-level eQTL analysis? If that is the case you can try to use SCT normalized data for your analysis. 
But usually single-cell eQTL analysis is done on (pseudo-)bulk level, where you need to aggregate the raw count data from cells of the same cell type within an individual, and then perform conventional normalization (like TMM) to the pseudo-bulked data. In that case you should not use SCT normalized data.

**Comment by tewengtong** [comment]
Hi,

Thank you so much for your reply! Yes, we plan to run eQTL at single-cell level using Siege (https://github.com/weizhou0/qtl). Please forgive me I am naive in single-cell analysis, is "data" layer in SCT assay the normalized one you mentioned to use? 

Thank you!
