### ISSUE TITLE
Parallelization in Seurat with future

### ISSUE THREAD

**Issue by Motoufiq** [satijalab/seurat#9385]
Hi, 

I attempted to use the `future` framework for parallelization during the `FindIntegrationAnchors` step in Seurat while working in R Studio on my Mac, but it caused R Studio to freeze and close. I then moved the analysis to an HPC system of my institution, but the `future` framework still didn’t work.

```r
library(future)
plan("multiprocess", workers = 4)
> plan("multiprocess", workers = 4)
Error: No such strategy for futures: ‘multiprocess’
```

On Mac, I switched to:
```r
plan("multisession", workers = 4)
```

I also tried:
```r
options(future.globals.maxSize = 50000 * 1024^2) # for 50 GB RAM
```

However, R Studio continues to close unexpectedly.

Best regards,  
Toufiq

**Comment by LilingJiang** [comment]
Hi there! I ran into the same issue and fixed it by using the multicore option on Linux. Starting from version 1.20.0 of the future package, the multiprocess strategy has been removed and replaced with multisession and multicore. Hope that helps.

**Comment by LilingJiang** [comment]
> Hi,
> 
> I attempted to use the `future` framework for parallelization during the `FindIntegrationAnchors` step in Seurat while working in R Studio on my Mac, but it caused R Studio to freeze and close. I then moved the analysis to an HPC system of my institution, but the `future` framework still didn’t work.
> 
> ```r
> library(future)
> plan("multiprocess", workers = 4)
> > plan("multiprocess", workers = 4)
> Error: No such strategy for futures: ‘multiprocess’
> ```
> 
> On Mac, I switched to:
> 
> ```r
> plan("multisession", workers = 4)
> ```
> 
> I also tried:
> 
> ```r
> options(future.globals.maxSize = 50000 * 1024^2) # for 50 GB RAM
> ```
> 
> However, R Studio continues to close unexpectedly.
> 
> Best regards, Toufiq

Hi there! I ran into the same issue and fixed it by using the multicore option on Linux. Starting from version 1.20.0 of the future package, the multiprocess strategy has been removed and replaced with multisession and multicore. Hope that helps.

**Comment by mccormickceci** [comment]
Hi
Unfortunately we are no longer supporting future in the V5 update, so I cannot really give a recommendation for solving this issue. However, you might find other people on the discussion board who have some suggestions on this specific issue.

**Comment by Motoufiq** [comment]
Thank you.
