### ISSUE TITLE
Error with ScaleData() that there is "no layer matching pattern data found"

### ISSUE THREAD

**Issue by hyunsik1214** [satijalab/seurat#9388]
Hi, I have been still working on the scRNA seq of the data published in [GSE120575](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120575).

I have used the following code to make Seurat object, and since the data published is already normalized, I have skipped the normalization process. However, when I tried to carry out ScaleData() for my Seurat object, the following Error has popped up:

Warning: No layers found matching search pattern provided
Error in `ScaleData()`:
! No layer matching pattern 'data' found. Please run NormalizeData and retry
Run `rlang::last_trace()` to see where the error occurred.

I have no idea what would have gone wrong...
Also, the following is the code I have run before ScaleData():

<img width="1184" alt="Screenshot 2024-10-10 at 5 53 44 PM" src="https://github.com/user-attachments/assets/b1818d96-1f13-4344-b5b3-2557d46d1b35">

**Comment by longmanz** [comment]
Hi, You will need to run `NormalizeData()` before running `ScaleData()`

**Comment by hyunsik1214** [comment]
The data is already published with normalization done. Do I still have to run NormalizeData()?

**Comment by longmanz** [comment]
Even if the data being loaded is already normalized, you still need to explicitly generate the 'data' layer (e.g., `feldman.object@assays$RNA@layers$data = feldman.object@assays$RNA@layers$counts`), otherwise Seurat would not be able to use the correct layer.

**Comment by hyunsik1214** [comment]
Thank you for the advice!
