### ISSUE TITLE
Error when using FindClusters in version3.0

### ISSUE THREAD

**Issue by BiqingZhu** [satijalab/seurat#939]
Dear Satija Lab,
 
We are currently using Seurat v3.0 package to merge 2 scRNA-seq datasets from sparse 10X data. In the course of using new Seurat, we encountered the following problem (screenshot attached):
 
![screen shot 2018-11-15 at 9 24 18 am](https://user-images.githubusercontent.com/44889161/48517772-830d1080-e8bb-11e8-924b-99619ac28b48.png)

In your help page, you just say the input should be 'Name of graph to use for the clustering algorithm', but we could not find any examples.
We will be very grateful for any advice you can give.
 
Best wishes

**Comment by satijalab** [comment]
In 3.0, we separate clustering into two steps. First, we construct a neighbor graph between single cells, and we next FindClusters (credit to scanpy for separating these two steps).

To do the first step, we run the FindNeighbors function - as documented on our 'cheat sheet' for Seurat v3
https://satijalab.org/seurat/essential_commands.html

**Comment by BiqingZhu** [comment]
Hi,

It works. Thank you so much.
