### ISSUE TITLE
Fail to install on R 3.4.1

### ISSUE THREAD

**Issue by rz2333** [satijalab/seurat#94]
Hi all,

I followed the instruction to install the seurat but failed. I have installed the Rtools and it's installed to 'c:\\Rtools' when I check it in R using Sys.getenv('PATH'). Here is the code:

library(devtools)
install_github("satijalab/seurat")
--------------------------------------------

and here is the error message:
Downloading GitHub repo satijalab/seurat@master
from URL https://api.github.com/repos/satijalab/seurat/zipball/master
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools34.exe'
Content type 'application/x-msdos-program' length 108085090 bytes (103.1 MB)
downloaded 103.1 MB

Installation failed: cannot change working directory

---------------------------------------------------------------
And here is the version of R:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle      

Thanks for your help!

**Comment by andrewwbutler** [comment]
This looks like a permissions problem. Maybe try running as admin?

**Comment by rz2333** [comment]
Hi Andrew,

It worked. Thanks!

Rui
