### ISSUE TITLE
Error when running SplitObject in version 3.0

### ISSUE THREAD

**Issue by yjluo** [satijalab/seurat#940]
Hello, 

I am trying to run the [tutorial](https://satijalab.org/seurat/pancreas_integration_label_transfer.html) for integrating different datasets, and I encountered an error in the following command.

```R
pancreas.list <- SplitObject(object = pancreas, split.by = "tech")
```

The RStudio console just shows up a "?". And if I send further commands, it generates the following error message.
```R
> Error in FetchData(object = object, vars = expr.char[vars.use], cells = cells) : 
> None of the requested variables were found: 
```
The function SplitObject seems OK in Seurat version 2.3.4. And I tried both R version 3.4.3 and 3.5.1.

Thank you for your help!

**Comment by andrewwbutler** [comment]
Hi,

It seems there was a bug introduced when trying to add in some old functionality. We've rolled back those changes until we work out the issue. Please try reinstalling.
