### ISSUE TITLE
Inquiry on editing metadata

### ISSUE THREAD

**Issue by hyunsik1214** [satijalab/seurat#9405]
Hi, below is the metadata for my seurat object:
<img width="1371" alt="Screenshot 2024-10-16 at 11 38 32 AM" src="https://github.com/user-attachments/assets/af94b6d8-4454-4e1b-9c47-8baaa8e1e668">

For the metadata column which I have marked with the red box, there are datas that show the pre- or post- treatment and patient ID, such as "Pre_P1", "Post_P3", "Pre_P4", etc. How can I remove the patient ID for all every data in this column so that there are only two conditions "Pre" and "Post"?

**Comment by joan-yanqiong** [comment]
I think this is not really a Seurat specific question, but I'll try to help. I'm sure there are different ways to achieve what you want, but this is one of them: 

```
library(dplyr)
library(tidyr)

# Separate your column into 2. 
meta_df_updated <- seurat_obj@meta.data %>% separate(your_variable_name, c("status", "patient"), sep = "_")

# Add metadata
seurat_obj <- AddMetaData(seurat_obj, meta_df_updated)
```
In the snippet, please replace 'your_variable_name' with the variable you highlighted, couldn't read the whole name. And I chose to split it into columns called 'Patient' (capturing the patient ID) and 'status' (capturing 'pre' or 'post'), but you can name it anything you want of course. Hope this helps!

**Comment by hyunsik1214** [comment]
Thank you so much!
