### ISSUE TITLE
Error generating dotplots

### ISSUE THREAD

**Issue by zelliesn** [satijalab/seurat#9419]
I've been getting the following error whenever I run the DotPlot function: 

`Error: (converted from warning) Scaling data with a low number of groups may produce misleading results
`
I thought maybe it was an issue with my Seurat object, but I am also getting this same error when I run the function on the sample data from the documentation.

```
> data("pbmc_small")
> cd_genes <- c("CD247", "CD3E", "CD9")
> DotPlot(object = pbmc_small, features = cd_genes)
Error: (converted from warning) Scaling data with a low number of groups may produce misleading results

```
Am I the only one experiencing this?? This function worked fine just a couple of days ago.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The issue you are experiencing is actually just related to your R settings and it is converting warnings to errors (see here for similar issue: https://github.com/satijalab/seurat/issues/8140#issuecomment-1847821230).  That should solve the issue with erroring.  The warning however should still occur dependent on the data being used for the plot to warn users in terms of the interpretation of the plot.

If changing the warning/error settings does not resolve this issue please comment here and I'll reopen the issue.

Best,
Sam
