### ISSUE TITLE
Set min_median_umi manually in PrepSCTFindMarkers()

### ISSUE THREAD

**Issue by EddieLv** [satijalab/seurat#9421]
I have multiple datasets of development, and used SCTransform to merge them, after ran SCTransform(srat.merged, assay = "Spatial, vst.flavor = "v2", method = "glmGamPoi"), I got each dataset's median umi as below (24 datasets in all):
1725.0
2895.0
5425.5
2005.0
1276.5
1513.5
2423.5
2871.0
4322.0
2215.0
695.0
2745.0
1722.0
2019.5
4410.0
2986.5
565.0
520.0
4399.0
4183.0
4480.0
2327.0
6594.0
4727.0
I found that sequence-depth of some datasets are extremely low, their median umis are 520, 566... So If I ran PrepSCTFindMarkers() with min(median_umi of each dataset), the gene expression of good datasets would decreased significantly.

My question is that, can I use mean(median_umi of each dataset) of median(median_umi of each dataset) as input of PrepSCTFindMarkers() in order to correct all datasets' sequence-depth to the same level?

**Comment by EddieLv** [comment]
@saketkc

**Comment by saketkc** [comment]
When you run `SCTransform`, you can pass `scale_factor` and set it to anything you want (in your case mean if you think that is more reasoanble). and then for other commands pass `recorrect_umi=F` to not recorrect again.
