### ISSUE TITLE
overlay two DimPlots

### ISSUE THREAD

**Issue by andrea-de-micheli** [satijalab/seurat#943]
Hello, 

I have to ggplot2 objects returned by DimPlots. I would like plot them together, in other words have the second ggplot2 overlaid on top of the first one. How can I achieve that? 

Thanks for your help!

Andrea

**Comment by satijalab** [comment]
We do not support this in Seurat - you may be able to use the magick package to acheive similar goals

https://cran.r-project.org/web/packages/magick/vignettes/intro.html
