### ISSUE TITLE
How to extract the spatial coordinate from a Seurat object with Visium samples?

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#9431]
Hi, thanks for your work. I wonder if there are any options I can refer to extract the spatial coordinates of a seurat object containing Visium samples. I guess it should be a part of assay. Thanks.

**Comment by samuel-marsh** [comment]
Hi @HelloWorldLTY,

See `GetTissueCoordinates` https://satijalab.github.io/seurat-object/reference/GetTissueCoordinates.html

Best,
Sam
