### ISSUE TITLE
DE analysis after pseudobulking (pct.1 and pct.2 are equal 1)

### ISSUE THREAD

**Issue by cihaterdogan** [satijalab/seurat#9438]
Hello Seurat Team,

I am following the https://satijalab.org/seurat/articles/de_vignette vignette.

We know that in a Seurat analysis, if "pct.1" and "pct.2" are equal to 1, it means that 100% of the cells in both groups being compared express the gene of interest; essentially, it means that the gene is expressed in every cell in both populations, and is therefore not a useful marker for distinguishing between them.

When analyzing differential expression, we want to see a large difference between pct.1 and pct.2 for a gene to be considered a good marker for one group compared to the other.

What I want to ask is why **pct.1** and **pct.2** values are mostly equal to **1** in the pseudobulk DE analysis, even though they have statistically significant **p_val** and a**vg log2FC** values.

<img width="558" alt="seurat_pseudobulk" src="https://github.com/user-attachments/assets/6d1f19ae-f289-41d1-9403-59b8ea3a5dd6">

I am curious to hear your comments on this. 

Thank you very much.

**Comment by rharao** [comment]
`pct.1` is the portion of cells in group 1 that express the feature _at all_, and likewise for `pct.2` and group 2. It is possible that, in both groups, every cell has non-zero expression of a feature, but the _within-group average expressions_ are still different. In this case, the DE table says that all CD14+ monocytes in both groups have some non-zero number of counts for _IL1RN_, but the the average log-normalized expression thereof in the stimulated CD14+ monocytes is ~ 2^6 = 64 times that in the unstimulated CD14+ monocytes.

**Comment by cihaterdogan** [comment]
Thank you for the clarification.
