### ISSUE TITLE
How to fix Warning: Layer counts isn't present in the assay object

### ISSUE THREAD

**Issue by skofm** [satijalab/seurat#9439]
I've searched for previous similar issues but I couldn't find a solution for this problem. I am trying to integrate single cell data from different timepoints, with multiple replicates. However, when I run IntegrateData, this issue persist and the 'integrated'  assay returns empty counts matrix.

'Warning: Layer counts isn't present in the assay object' 

This is my (simplified) prior workflow (showing only analysis of one object in the list): 

ZTX_object <- NormalizeData(ZTX_object)
ZTX_object <- FindVariableFeatures(ZTX_object)
all_genes <- rownames(ZTX_object)
ZTX_object <- ScaleData(ZTX_object, features = all_genes)
ZTX_object <- RunPCA(ZTX_object, features = VariableFeatures)
var_features_X <- SelectIntegrationFeatures(object.list = ZT_all_objects)
anchors_ZT_all <- FindIntegrationAnchors(object.list = ZT_all_objects,
                                         assay = rep("SCT", length(ZT_all_objects)), # to prevent 'subscript out of bounds'
                                         anchor.features = var_features_X,
                                         reduction = "rpca")
(FindIntegrationFeatures runs fine, however, the names of slots is empty and must be filled in manually)

Then, when I try integrating data, the mentioned error occurs:
integrated <- IntegrateData(anchorset = anchors_ZT_all, 
                                  normalization.method = "SCT",
                                  dims = 1:25)

Any help would be greatly appreciated!

**Comment by mhkowalski** [comment]
Hi, 

I think you need to add `normalization.method="SCT"` to your `FindIntegrationAnchors` and `IntegrateData` calls.  I'm referencing the v4 version of the integration vignette [here](https://satijalab.org/seurat/archive/v4.3/integration_introduction). Please let me know if this fixes your issue.

**Comment by skofm** [comment]
Thank you for your reply!

I tried using the SCT normalization, however, the issue with data layers
still persists. I was wondering if there is a different method to approach
this in V5 (as that is the version I am using).

Thanks
