### ISSUE TITLE
Error in FindIntegrationAnchors

### ISSUE THREAD

**Issue by maxshafer** [satijalab/seurat#944]
Using v3 of Seurat, I'm getting an error while running FindIntegrationAnchors.

I'm using data from two different species, and I'm pretty sure that the error is due to the fact that there are not enough Variable Features for the objects found in the raw data for both objects.

After running the following on both datasets:

```R
hypo.ast <- FindVariableFeatures(hypo.ast, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
```

Followed by
```R
> hypo.anchors <- FindIntegrationAnchors(reference.list, dims = 1:30)
Computing 2000 integration features
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
> traceback()
7: stop("'x' must be atomic")
6: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
5: sort.default(x = tie.ranks)
4: sort(x = tie.ranks)
3: head(x = sort(x = tie.ranks), nfeatures - length(x = features))
2: SelectIntegrationFeatures(object.list = object.list, nfeatures = anchor.features, 
       assay = assay)
1: FindIntegrationAnchors(reference.list, dims = 1:30)
```

I've traced the issue to within `SelectIntegrationFeatures` and when `var.features` is filtered by whether or not they appear in the raw data for both objects - this cuts the length of `var.features` below the length of `nfeatures` set in the initial call of `FindIntegrationAnchors`. This then causes `tie.val` to be <NA> NA, and for 0 features to be selected. In my case, 1888 of the `var.features` are found in the raw data of both datasets (less than `nfeatures=2000`).

Using `tie.val <- var.features[length(var.features)]` solves the problem, and gives me the Union of the VariableFeatures lists sorted properly (by values from var.features (intersection between datasets), then by the variability).

Thanks,
Max

**Comment by andrewwbutler** [comment]
Hi Max,

Thanks for the detailed bug report! I've changed that line to be `tie.val <- var.features[min(nfeatures, length(x = var.features))] ` which should resolve the issue.

**Comment by rahulnutron** [comment]
Dear Seurat Team,
Thanks for this great package!
I encountered a similar problem even in the latest version 3.0.2. My control dataset has 2294 cells and 38285 genes but my stimulus dataset has only 220 cells and 33602 genes. Also my stimulus dataset has some genes with zero expression in all cells. Interestingly, when I used gene name "gene.column=2" in Read10x, there is no error, however when I used gene id "gene.column=1" in Read10x, the error appears. Is it possible due to large number of different genes in the two dataset?

Regards,
Rahul

Error:

> blc.anchors <- FindIntegrationAnchors(object.list = list(ctrl, stim), dims = 1:20)
Computing 2000 integration features
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic

**Comment by jurtlest** [comment]
I'm also in the process of hoping to combine mice and human data following the vignette (https://satijalab.org/seurat/articles/integration_large_datasets.html) 
However, I'm running into seemingly exact issue

`> anchors <- FindIntegrationAnchors(object.list = data_list, reference = reference.list, reduction = "rpca", dims = 1:50)
Computing 2000 integration features
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=10s
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=18s
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) :
  'x' must be atomic
> traceback()
6: stop("'x' must be atomic")
5: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4: sort.default(x = reference)
3: sort(x = reference)
2: unique(x = sort(x = reference))
1: FindIntegrationAnchors(object.list = data_list, reference = reference.list,
       reduction = "rpca", dims = 1:50)
> data_list
$Moe_0105
An object of class Seurat
15135 features across 3215 samples within 1 assay
Active assay: RNA (15135 features)
 1 dimensional reduction calculated: pca`

Is there a probable way of bypassing this issue right now ??

**Comment by NatnichaJira** [comment]
Hi, I'm using Seurat 4.1.1 and have the error like you had discussing about. Here is my code:

> In_list <- lapply(X = In_list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
features <- SelectIntegrationFeatures(object.list = In_list)
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
> traceback()
6: stop("'x' must be atomic")
5: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
4: sort.default(x = tie.ranks)
3: sort(x = tie.ranks)
2: head(x = sort(x = tie.ranks), nfeatures - length(x = features))
1: SelectIntegrationFeatures(object.list = In_list)


I read your discussion but still don't know how to fix my problem. Could you please explain more how to solve this issue?
