### ISSUE TITLE
an object question about "plotGeneExpression" when I use cellchat to make a plot

### ISSUE THREAD

**Issue by wxginpumc** [satijalab/seurat#9440]
p <- plotGeneExpression(cellchat, signaling = "CCL")
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
警告: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Scale for y is already present.
Adding another scale for y, which will replace the existing scale.
The data layer exists in cellchat object, how could I correct this error?

**Comment by samuel-marsh** [comment]
Hi,

This appears to be an issue with CellChat package and not Seurat.  I would suggest posting it to their repo (https://github.com/jinworks/CellChat) for assistance.

Best,
Sam

**Comment by wxginpumc** [comment]
> Hi,
> 
> This appears to be an issue with CellChat package and not Seurat. I would suggest posting it to their repo (https://github.com/jinworks/CellChat) for assistance.
> 
> Best, Sam

Thanks for your advice. I will search for help in this reconmended site. Hope you are happy everyday!!!
