### ISSUE TITLE
Demultiplexing with hashtag oligos vignette - bad link

### ISSUE THREAD

**Issue by jkelrod97** [satijalab/seurat#9445]
Hello! I am trying to follow along with the demultiplexing vignette: https://satijalab.org/seurat/articles/hashing_vignette.html

However, when I click on the link to download the count matrices for RNA and HTO, I get a dropbox page that says the item was deleted.

Is someone able to update this link?

Thanks!

**Comment by mccormickceci** [comment]
Hi, sorry about that! We are currently in the process of organizing our dropbox and updating some links. The counts matrices should be available to download here in the meantime: 
https://www.dropbox.com/scl/fi/fvyfqw7fxxvz9qmj9hwhq/?rlkey=egon5w72f7zoqtqdtlxsowq6r&e=1
Hope this helps!
