### ISSUE TITLE
where to get fov parameter value for  LoadXenium

### ISSUE THREAD

**Issue by lidd77** [satijalab/seurat#9447]
Hello,

     I am using LoadXenium to read Xenium 5K data ,  for fov parameter , we need to write  a fov name , but I do not know where to  find 'fov' name ?

    could you please tell me  where to  find  'fov' name ?
 
    ` obj <- LoadXenium(datadir, fov = "fov", assay = "Xenium")`

Expecting your reply ! 
    

Best

**Comment by samuel-marsh** [comment]
Hi,

`fov` is personal choice to name the fov or you can just leave as default which is “fov”.

Best,
Sam

**Comment by lidd77** [comment]
> Hi,
> 
> `fov` is personal choice to name the fov or you can just leave as default which is “fov”.
> 
> Best, Sam

Thank you very much ! 
sorry for the late reply !
