### ISSUE TITLE
Loading Pre-Annotated Regions for Visium Analysis

### ISSUE THREAD

**Issue by abadgerw** [satijalab/seurat#9448]
I have pre-annotated regions in QuPath and exported them as geoJSON files. Can these be loaded directly using Seurat so that I may perform spatially-aware DE of my Visium data?

**Comment by cyrillustan** [comment]
Probably not. If you want to share the JSON file we may be able to take a look.

**Comment by abadgerw** [comment]
Thanks! I am sharing an example image and associated annotation created in QuPath here: https://drive.google.com/drive/folders/16M5Pqzpa5z9KHnV2OS55RHjKIESGWzr9?usp=sharing.

If I cannot directly import the pathologist annotations via my geojson file, do you have insight into an alternative method so that I can leverage this information as part of my analysis?

**Comment by abadgerw** [comment]
@cyrillustan I found the following from 10x: https://kb.10xgenomics.com/hc/en-us/articles/360058943912-How-can-I-transfer-pathologist-annotations-to-Loupe-Browser

If the file I sent can't be directly used by Seurat, is the above method the only way to be able to leverage my pathology annotations?

Thanks in advance for your help!

**Comment by abadgerw** [comment]
@cyrillustan hope you are doing well! I just wanted to check in and see if you had a moment to review the information above?

**Comment by cyrillustan** [comment]
Hi, yes, your information has captured our attention! After looking through this, I think it can be possible. You do have to convert the coordinates into the right format, though. Check out this [Vignette](https://satijalab.org/seurat/articles/visiumhd_analysis_vignette), especially the `CreateSegmentation()` function.

**Comment by abadgerw** [comment]
Thanks, @cyrillustan! I am still a bit confused as to how to convert the GeoJSON format into coordinates that can be read by createsegmentation. Any suggestions?

**Comment by abadgerw** [comment]
@cyrillustan we have had success loading in the GeoJSON. However, it is not scaling correctly. It was drawn on the full resolution image and we can't get it to match the low or high resolution CytAssist images displayed with Seurat. Any insight into how we can get the scaling of the GeoJSON to work?

**Comment by dcollins15** [comment]
@abadgerw from the sound of things you'll just need two more steps (I'm assuming you're taking advantage of the `VisiumV2` class, but please let me know if that's wrong):

1. Read the unscaled PNG image into your `Seurat`/`VisiumV2` instance
2. Reset the image's `scale.factors` to 1

It'll be something along the lines of:

```r
visium_fov <- object[["fov-name"]]
visium_fov.image <- unscaled_image_array
visium_fov.scale.factors <- scale.factors()
```

**Comment by abadgerw** [comment]
Thanks, @dcollins15! I think I'm a bit confused:

We are working with the Visium V2 chemistry. What do you mean by unscaled image? We have the hi-res and low-res image outputs from spaceranger and then also have the input images (CytAssist image and full resolution scanned image where the GeoJSON was drawn on). 

We originally tried to scale the GeoJSON (drawn on the full resolution scanned image) so that it would map onto the hi or low res image but had issues with that. Our goal is to ultimately be able to filter spots by the GeoJSON annotation classes.

**Comment by abadgerw** [comment]
@dcollins15 @cyrillustan I have been trying more things but am hitting a wall. I can extract coordinates and the region classification. I can then use the CreateSegmentation function to load this data. However, the overlay fails (ie cannot remove default boundary) as the coordinate systems are off for some reason (even when scaling with the scale factor from full resolution where the annotations are drawn and the lowres image in the Seurat object). 

I'm sharing a folder with my GeoJSON and the Seurat object .rds file: https://drive.google.com/drive/folders/10zoLx6NwlqU1IvkvsJKr8SYJ_nKjYbQf

Any insight into how I can get this to work?

**Comment by abadgerw** [comment]
I even tried redrawing annotations on the low res image to see if that could work. I was able to at least overlay the annotation but it doesn't overlap the tissue as expected on the spatial dim plot. Therefore, I'm now really confused given the annotation was drawn on the image being displayed so no scaling should be required.

**Comment by abadgerw** [comment]
@cyrillustan @dcollins15 I hope you are both doing well. I wanted to check back in and see if you had any insight based on the additional information shared?

**Comment by zskylarli** [comment]
Hello, thank you for your patience! Unfortunately, we do not have a direct function that supports what you are trying to do, especially since your GeoJSON file has multipolygons. I would suggest the following steps:

(1) Split your GeoJSON file into a separate polygon file for each closed-off section, instead of containing all points that divide all sections.
(2) Get coordinates with the st_coordinates() function. 
(3) Get coordinates of your image in the Seurat object with `GetCoordinates(obj[['slice1']],scale=NULL)`. 
(4) Manually align the two to overlap in the way that you want it to, by directly scaling or translating your annotation coordinates.
(5) Create a new dataframe for your adjusted annotation coordinates with a "x", "y", and "cells" column ("cells" can be anything, i.e. "NAWM").
(6) Following the vignette that @cyrillustan previously pointed to, create a segmentation with this dataframe and overlay it onto your "slice1". 
(7) Use Cells(obj[['newimage']]) to return the cell barcodes of spots contained in your cropped area. Manually create a new metadata column where those cells/spots are assigned the name of that region that you had cropped.
(8) Repeat 2-7 for all sections.

Let me know if this works or if anything is confusing. Thanks again!

**Comment by abadgerw** [comment]
@zskylarli to give more details, for the geojson file drawn on the full resolution image, I used the following code:

`` 
library(Seurat)
library(sf)
library(dplyr)
library(jsonlite)  # for JSON parsing

# ---- Step 0: Load Seurat object ----
# Replace with your actual file path
seurat_path <- "/Users/waldmanad/Library/CloudStorage/Box-Box/GeoJSON_Test/seurat_C013.rds"
obj <- readRDS(seurat_path)

# ---- Step 1: Load and validate GeoJSON ----
geojson_path <- "/Users/waldmanad/Library/CloudStorage/Box-Box/GeoJSON_Test/C013_SC_C_HE_X40_VISIUM-001.geojson"
annotations <- st_read(geojson_path)
annotations <- st_make_valid(annotations)

# ---- Step 2: Define scale factor from fullres to lowres ----
scale_factor <- 0.027383506

# ---- Step 3: Get Seurat spatial image coordinates ----
spatial_coords <- GetTissueCoordinates(obj[["slice1"]], scale = NULL)

# ---- Step 4 & 5: Build segmentation dataframe (x, y, cell) ----
segmentation_df <- do.call(rbind, lapply(seq_len(nrow(annotations)), function(i) {
  coords <- st_coordinates(annotations[i, ])[, 1:2] * scale_factor
  coords_df <- as.data.frame(coords)
  colnames(coords_df) <- c("x", "y")
  
  # Parse the JSON string to extract the 'name' field
  classification_parsed <- fromJSON(annotations$classification[i])
  classification_name <- classification_parsed$name  # Extract the 'name' field
  
  coords_df$cell <- classification_name  # Use the extracted 'name'
  coords_df
}))

# ---- Step 6: Create segmentation object ----
segmentation_obj <- CreateSegmentation(segmentation_df)

# ---- Step 7: Add segmentation to Seurat object ----
obj[["segmentation_obj"]] <- Overlay(obj[["slice1"]], segmentation_obj)

`` 
Following step 1 I see the following messages:

Reading layer `C013_SC_C_HE_X40_VISIUM-001' from data source 
  `/Users/waldmanad/Library/CloudStorage/Box-Box/GeoJSON_Test/C013_SC_C_HE_X40_VISIUM-001.geojson' 
  using driver `GeoJSON'
Simple feature collection with 6 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 6289 ymin: 2913 xmax: 40714 ymax: 36863
Geodetic CRS:  WGS 84

Warning message:
In st_is_longlat(x) :
  bounding box has potentially an invalid value range for longlat data

During the last step I get the following message:

Error: Cannot remove default boundary
In addition: Warning message:
The selected region does not contain any cell centroids

**Comment by abadgerw** [comment]
I did try running st_read with crs=na. This removed the following warning message: 

In st_is_longlat(x) :
bounding box has potentially an invalid value range for longlat data

However, I still got the same messages after Step 7:

Error: Cannot remove default boundary
In addition: Warning message:
The selected region does not contain any cell centroids

**Comment by abadgerw** [comment]
@zskylarli hope you are having a great week. I wanted to see if you had a chance to review what I shared above and had any insight into what may be going wrong?

**Comment by abadgerw** [comment]
@zskylarli Hope you are enjoying your week. Wanted to circle back to the code I shared and see if you had any suggestions?

**Comment by abadgerw** [comment]
@zskylarli I hope you had a great weekend. I'm hoping to move forward with my work and hopefully use Seurat. Any suggestions based on the code and errors I sent? Thanks in advance for your support with this!

**Comment by abadgerw** [comment]
@zskylarli Hope you are having a nice week. I just wanted to see if you had a chance to review this outstanding issue and had additional thoughts for troubleshooting?

**Comment by abadgerw** [comment]
@zskylarli @cyrillustan @dcollins15 I am circling back again to see if you had any insights based off the code I shared?

**Comment by abadgerw** [comment]
@zskylarli @cyrillustan @dcollins15 Apologies for the additional message but I'm hoping to get some assistance to move past the issue described above. Any help you can provide would be much appreciated.

**Comment by jp589** [comment]
Hello @abadgerw,

I struggled with the same issue. In my case I had Visum HD data, and I wanted to map a QuPath annotated region onto a Seurat object so that I could plot the high-resolution image with an overlay of the 16um bins that intersected with the annotation. However, the process should be similar for your case as well. The only thing is that my code is built for single polygon .geojson files. You'll have to split your .geojson file for each polygon like @zskylarli suggested and then loop the `get_intersecting_bins` function below for each polygon. You can store the intersecting bins output in a list and then collapse it after the loop has finished. From there you can do what you want with the selected bins. Either that or rewrite the following line to check for multiple polygons and process them appropriately:
`  Annotation_scaled <- st_sf(geometry = st_sfc(st_polygon(list(scaled_coords[,c(2,1)]))))`

Note: for my data I had to flip the x and y coordinates from the fullres annotation for it to match up properly with the lower resolution images.

Hope this helps!

```
library(sf)
library(Seurat)
library(ggplot2)

# probably a good idea to set your desired default assay here #

coords <- GetTissueCoordinates(obj, scale = "hires") # obj is the Seurat spatial transcriptomics object

sf_bins <- st_as_sf(coords, coords = c("x", "y"), crs = NA) # Convert to sf object

#(I've only tested with a single polygon.)
Qupath_annotation <- st_read("Exported_Qupath_annotation.geojson") # your exported annotation. coordinates are in fullres pixels at this point.

hires_scalefactor <- 0.1495327 # from scalefactors_json.json / replace with your scalefactor for hires or lowres

coords <- st_coordinates(Qupath_annotation) # Extract polygon coordinates

scaled_coords <- coords*hires_scalefactor #multiply fullres pixels by hires (or lowres) scale factor. coordinates are in hi/low res pixels.

Annotation_scaled <- st_sf(geometry = st_sfc(st_polygon(list(scaled_coords[,c(2,1)])))) #flip flop the x and y coordinates

intersect_matrix <- st_intersects(sf_bins, Annotation_scaled) # Determine which bins intersect with scaled annotation polygon

bin_intersect <- rownames(coords)[lengths(intersect_matrix) > 0] # Extract intersecting bins

length(bin_intersect) # sanity check to confirm that there were overlapping bins

SDP <- SpatialDimPlot(obj,
                      pt.size.factor = 1.6, # default point size
                      images = "slice2", # spatial field of view (usually something like "slice.016um")
                      image.scale = "hires", # resolution (usually hires or lowres)
                      cells.highlight = bin_intersect, 
                      cols.highlight = c("#FFFF00", "grey50")) + NoLegend() # visualize overlap
ggsave(filename = paste0(workdir, "Qupath_annotation_overlay.pdf"), plot = SDP, units = "in", width = 8, height = 7, limitsize = F) # save image

##### function version that returns the intersecting bins:

get_intersecting_bins <- function(seurat_obj, geojson, scalefactor, scale = "hires"){
  coords <- GetTissueCoordinates(seurat_obj, scale = scale) # seurat_obj is the Seurat spatial transcriptomics object

  sf_bins <- st_as_sf(coords, coords = c("x", "y"), crs = NA) # Convert to sf object
  
  Qupath_annotation <- st_read(geojson) # your exported annotation. coordinates are in fullres pixels at this point.
  
  Qu_coords <- st_coordinates(Qupath_annotation) # Extract polygon coordinates
  
  scaled_coords <- Qu_coords*scalefactor #multiply fullres pixels by hires (or lowres) scale factor. coordinates are in hi/low res pixels.
  
  Annotation_scaled <- st_sf(geometry = st_sfc(st_polygon(list(scaled_coords[,c(2,1)])))) #flip flop the x and y coordinates
  
  intersect_matrix <- st_intersects(sf_bins, Annotation_scaled) # Determine which bins intersect with scaled annotation polygon
  
  bin_intersect <- rownames(coords)[lengths(intersect_matrix) > 0] # Extract intersecting bins
  return(bin_intersect)
}
# example use
bin_intersection <- get_intersecting_bins(seurat_obj = obj, geojson = "Exported_Qupath_annotation.geojson", scalefactor = 0.1495327, scale = "hires")
```
