### ISSUE TITLE
Mismatch in Dotplot of raw counts and normalized data

### ISSUE THREAD

**Issue by Rong-ao** [satijalab/seurat#9452]
Hi Seurat team,
I am trying to use seurat to analysis scRNA-seq data. When I tried to show some gene expression level across different metadata groups with Dotplot(), I applied it to raw counts and normalized data, respectively, but I found there are some mismatch in Dotplot of raw counts and normalized data. Here are my plots below:
![image](https://github.com/user-attachments/assets/e8ff7a3e-de74-4f14-80a1-fb5c742a262e)
For example, the expression level of gene PDK3 of "lateAD_7" is relatively higher than "nonAD_7" in raw counts while this relative relationship is reversed in normalized data. In my understanding, normalization does not change the relative high or low between values. I am not sure that I have some misunderstanding or not. Can you help me to figure out what is the reason of that issue? Here is my code:
```
ob <- readRDS("my_seurat.rds")
metadata <- readRDS("my_seurat_meta.rds")
ob@meta.data <- metadata
Idents(ob) = 'seurat_clusters'
ob$cluster_adtype = paste0(ob$ADdiag3types, '_', ob$seurat_clusters) 
Idents(ob) = "cluster_adtype"
gene_of_interest <- c("PDK1", "PDK2", "PDK3", "PDK4")
test <- subset(ob, seurat_clusters == 7)
Idents(test) = "cluster_adtype"
DotPlot(test, features = unique(gene_of_interest))+RotatedAxis()+scale_x_discrete("")+scale_y_discrete("")

ob <- NormalizeData(ob) %>% FindVariableFeatures(nfeatures = 3000) %>% ScaleData()
test <- subset(ob, seurat_clusters == 7)
Idents(test) = "cluster_adtype"
DotPlot(test, features = unique(gene_of_interest))+RotatedAxis()+scale_x_discrete("")+scale_y_discrete("")
```
Thanks for your attention,
Rong-ao

**Comment by mhkowalski** [comment]
Hello, 

The `DotPlot` function is meant to work with log-normalized data and uses the `data` layer. 

If you have a seurat object pre v5 that hasn't been normalized, the `data` layer is automatically populated with counts. So the function is applying an averaging function that assumes the data has already been log-normalized, which doesn't really make sense. If you'd like to directly compare counts vs log-normalized data for your features of interest, I'd suggest using `VlnPlot` where you can specify `layer="counts"` or `layer="data"`. 

I hope this is helpful!
