### ISSUE TITLE
Seurat v3.0 Converting Seurat to SingleCellExperiment 

### ISSUE THREAD

**Issue by BiqingZhu** [satijalab/seurat#946]
Hi,

I am currently using Seurat v3.0 package and encountered the following problem (screenshot attached):

![screen shot 2018-11-16 at 4 00 25 pm](https://user-images.githubusercontent.com/44889161/48598794-c13c2a00-e9b8-11e8-8a10-9dcbfafd90df.png)

and it is also true for function 'Convert'.
I wonder if that function is for the old Seurat object, and if you have new equivalent functions.
I will be very grateful for any advice you can give.

Best wishes

**Comment by satijalab** [comment]
We will add this functionality but it is not currently supported in our alpha release of 3.0 

Please continue to use v2 if you want to convert to SCE

**Comment by thetapper** [comment]
Hi @BiqingZhu,

You can still access your data in v3 and load it into an SingleCellExperiment though:

> sce <- SingleCellExperiment(assays = list(counts = GetAssayData(object = my_seurat_obj, slot = "data")))

You just have to watch out which data slot in Seurat corresponds to which data slot in sce. Also any additional metadata has to be manually transfered too.

**Comment by andrewwbutler** [comment]
Conversion to SingleCellExperiment is now supported in v3. Please see our [conversion vignette](https://satijalab.org/seurat/v3.0/conversion_vignette.html) for details.

**Comment by raveancic** [comment]
Thank you for this, but even using the example of the vignette, and converting it from v2 to v3 I am always getting this error:  

```Error in validObject(.Object) : invalid class "DFrame" object: 
    number of columns and number of column names differ```

Do you have any idea why I am getting this?
Thank you very much in advance, 
All the best,
Alessandro
