### ISSUE TITLE
`DietSeurat` doesn't drop layers from objects

### ISSUE THREAD

**Issue by rharao** [satijalab/seurat#9464]
(I have double-checked to confirm that `DietSeurat` is provided in `Seurat` and not `SeuratObject`.)

While working on a reprex to answer a question in another issue on this repo, I found out that each of the following calls:
* `DietSeurat(pbmc_small, layers = "counts") # Only assay is "RNA"`
* `DietSeurat(pbmc_small, layers = "counts", assays = "RNA")`
* `DietSeurat(pbmc_small, layers = list(RNA = "counts"))`

results in an object with all layers retained:
```
An object of class Seurat 
230 features across 80 samples within 1 assay 
Active assay: RNA (230 features, 20 variable features)
 3 layers present: counts, data, scale.data
```

Layers not mentioned in the `layers` argument to `DietSeurat` should be dropped from the result.

**Comment by rharao** [comment]
Apologies for the duplicate issue!

**Comment by samuel-marsh** [comment]
No worries!

**Comment by rharao** [comment]
#8197 has been merged into develop.
