### ISSUE TITLE
Error in validObject(object = object) :    invalid class “Assay5” object: Layers must be two-dimensional objects

### ISSUE THREAD

**Issue by sguttr** [satijalab/seurat#9476]
I am currently trying to split my Seurat object into samples in order to follow the Integration vignette. My Seurat object is currently already split into days:

An object of class Seurat 
22798 features across 1342 samples within 1 assay 
Active assay: RNA (22798 features, 2000 variable features)
 11 layers present: counts.Day 3, counts.Day 4, counts.Day 5, counts.Day 6, counts.Day 7, data.Day 3, data.Day 4, data.Day 5, data.Day 6, data.Day 7, scale.data
 2 dimensional reductions calculated: pca, umap

I tried JoinLayers to create just three layers (counts, data and scale.data) and then converted the object back into a Seurat object because JoinLayers created an Assay5 file. However, I keep getting errors when using the split function.

I am following this code:

obj[["RNA"]] <- split(obj[["RNA"]], f = obj$Method)

But I keep getting this error code:

Error in validObject(object = object) : 
  invalid class “Assay5” object: Layers must be two-dimensional objects

If anyone could explain why this is happening and how I can rectify it, that would help. Thanks :)

**Comment by samuel-marsh** [comment]
Hi,

Can you please post the full code that you are running and the output of `sessionInfo()`?

Thanks,
Sam

**Comment by Harmony714** [comment]
I encountered the same issue. You can try table(sample$orig.ident). If there are samples with too few cells，such as <10 cells, remove them and then try split again, it should work fine.

**Comment by listen2099** [comment]
> I encountered the same issue. You can try table(sample$orig.ident). If there are samples with too few cells，such as <10 cells, remove them and then try split again, it should work fine.

<1 cells
