### ISSUE TITLE
How can i get batch adjusted expression profile?

### ISSUE THREAD

**Issue by bishwaG** [satijalab/seurat#948]
I am using CCA to analyse three time points from same sample. Is there any way to extract batch corrected expression matrix?

**Comment by timoast** [comment]
CCA does not produce a batch-corrected expression matrix but a set of cell embeddings and gene loadings, similar to PCA. You can read the paper (https://www.nature.com/articles/nbt.4096) for more details on CCA.

We recently released a preprint (https://www.biorxiv.org/content/early/2018/11/02/460147) describing new tools we have developed that _do_ produce a batch corrected matrix that you may be interested in. These new tools are in the upcoming Seurat v3 release, which is still in an alpha stage of development but is available on the release/3.0 branch. Installation instructions and tutorials for Seurat v3 are available on our [website](https://satijalab.org/seurat/).

**Comment by bishwaG** [comment]
@timoast Thanks a lot!
