### ISSUE TITLE
FeaturePlot for spatial transcriptomics data does not work

### ISSUE THREAD

**Issue by Yijia-Jiang** [satijalab/seurat#9481]
Hello, I am trying Seurat for the latest visium HD data and trying to use SpatialFeaturePlot function. I used the exact same script shown in vignette for preprocessing, but the feature plot is just H&E image and there is no gene expression level displayed. Could you help with this? Thank you very much.

```r
object <- Load10X_Spatial(data.dir = localdir)

# Setting default assay changes between 8um and 16um binning
Assays(object)
DefaultAssay(object) <- "Spatial"

head(object@meta.data)
vln.plot <- VlnPlot(object, features = "nCount_Spatial", pt.size = 0) + theme(axis.text = element_text(size = 4)) + NoLegend()
count.plot <- SpatialFeaturePlot(object, features = "nCount_Spatial") + theme(legend.position = "right")

# note that many spots have very few counts, in-part
# due to low cellular density in certain tissue regions
vln.plot | count.plot

length(rownames((object@assays$Spatial@features@.Data)))
# normalize both 8um and 16um bins
object <- NormalizeData(object)
object@assays$Spatial$data

p1 <- SpatialFeaturePlot(object, features = "CD3D") + ggtitle("CD3D expression (16um)")
p2 <- SpatialFeaturePlot(object, features = "CD4") + ggtitle("CD4 expression (16um)")
print(p1)
print(p2)
```
<img width="693" alt="Screenshot 2024-11-14 at 10 23 05 AM" src="https://github.com/user-attachments/assets/81755f33-7118-4d88-b77f-2a351a6cfdaf">

**Comment by Yijia-Jiang** [comment]
@zskylarli I ran a similar issue using the SpatialDimPlot on the same data. I also tried changing pt.size.factor but it was still the same.

**Comment by alikhuseynov** [comment]
> @zskylarli I ran a similar issue using the SpatialDimPlot on the same data. I also tried changing pt.size.factor but it was still the same.

using `pt.size.factor = 4` or similar should work for Visium HD. 
check this:
- https://github.com/satijalab/seurat/issues/8792#issuecomment-2072805590
