### ISSUE TITLE
Strong impact of number of ADT PCs on WNN UMAP?

### ISSUE THREAD

**Issue by erflynn** [satijalab/seurat#9482]
I'm running WNN following the tutorial on a dataset of about 200,000 skin cells. I noticed that choice of number of ADT PCs has a huge impact on the UMAP -- the UMAP clearly looks better with more ADT PCs, despite the elbow plot indicating we should likely use fewer. I am using the same exact settings (30 RNA PCs) except the number of ADT PCs. Seurat version 4.3.0.
![adt_pcs](https://github.com/user-attachments/assets/3099d1d9-b0e3-4347-bae3-68cb94fb29fc)

```
wnn <- FindMultiModalNeighbors(
  wnn, reduction.list = list("pca", "apca"), 
  dims.list = list(1:30, 1:n_adt_pcs), modality.weight.name = "RNA.weight",
  prune.snn=1/20 # adjusted to avoid small clusters
)
wnn <-RunUMAP(wnn, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
```
Have you noticed this before? Is this expected behavior? What would you recommend doing to proceed?

**Comment by erflynn** [comment]
Following up on this with a reprex -- 
Using the bmcite dataset and code in the (WNN tutorial)[https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis], we also see the pattern that too few PCs from ADT or RNA lead to poor UMAPs; however, the numbers at which this occurs are much lower (e.g. 3 or 5 PCs rather than 10 or 15). It does seem to be the case that after "enough" PCs, it looks relatively similar? (Though in other cases,  particularly in sub-clustering, we've found that "too many" PCs makesthe UMAP look worse.)

![bmcite_rna_adt_pc_vary](https://github.com/user-attachments/assets/d6b3eeaf-1784-48fa-abb2-2021ea62bf86)
![bmcite_pc_vary_selected](https://github.com/user-attachments/assets/f1ec516e-9adc-47ef-a222-0bc35e0248f1)

I understand that the low #s of PCs do not capture the variation in the data, making the nearest neighbor space for that modality poor. As a result, since WNN considers both the ability of the RNA and ADT PCs to predict cell identity in each space when determining the weights, this adds some noise.  

However, I do not understand why, in the original example, **while selecting more than 15 ADT PCs does not make sense given the elbow plot, it results in a much cleaner WNN UMAP.** We've also looked and these additional PCs do not associate with RNA cell type, and ADT UMAPs with more PCs still look very messy. Can you lend any insights as to why adding these PCs would be helpful? Given this, what do you recommend to do when choosing number of ADT PCs in larger datasets?

**Comment by dcollins15** [comment]
Hi @erflynn

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
