### ISSUE TITLE
Question about   ImageDimPlot function 

### ISSUE THREAD

**Issue by lidd77** [satijalab/seurat#9497]
Hello,
    I  run the following code , 

   `  FetchData( obj[["fov"]][["molecules"]], vars = "Tagln"))`
   and got the following result :
```
       x        y molecule
1 373.0469 1619.828    Tagln
2 383.9688 1631.656    Tagln
3 384.1406 1625.312    Tagln 
```
  **I know "Tagln" means  gene  , could you tell me what the meaning of  x/y coordinates  is  ?  RNA position from this Tagln ?**

 and another question , 
```
 dim(FetchData(  obj[["fov"]][["molecules"]], vars = "Tagln"))  # return (30331,3) 
 ImageDimPlot(obj, fov = "fov", molecules = c("Tagln"), nmols = 20)
```
  **For the first line code , it returns  (30331,3), so 30331 is the total number of  RNA or Gene or other some stuff? 
  I set nmols value 20 ,  so what does this number 20 mean ?**  
 
Expecting your reply ! 

Thank you very much ! 

Best

**Comment by lidd77** [comment]
> The dimensions (`dim`) of the matrix you requested (`FetchData`) are `(30331, 3)`: 30,331 rows (molecules) by 3 columns (x-coordinate, y-coordinate, and molecule name for each molecule; in your case, because you only requested _Tagln_, the molecule name is the same for all.)

Yeah, thank you .  
So 30331 means   30331 Tagln genes for  21920 cells  ,   the number of Tagln gene   is bigger than the number of cells   ? is it correct ?

**Comment by rharao** [comment]
Depending on the tissue and transcript, it is quite possible for there to be more reads for a transcript than there are cells in total; it just means that, on average, a cell has more than one copy of the transcript.

**Comment by adyzh** [comment]
Hi @lidd77, Thank you for reaching out! Looks like the question has been answered. I am going to go ahead and close the issue for now please feel free to reopen if there are any other questions!
