### ISSUE TITLE
Export log2(TPM/10+1) values from Seurat 

### ISSUE THREAD

**Issue by Tina-Siqi** [satijalab/seurat#9500]
Hi, I met similar problem with Issue#8365. It was mentioned in Issue#8365 that TPM matrix is not an available format of scRNA-seq normalized data that could export from Seurat, other software or R package  is needed. Could you please recommend a R package that  could help me to calculate log2(TPM/10+1) values based on Seurat Object? It seems like the downstream online software Cytosig recommend to use TPM based data. Many thanks!
![image](https://github.com/user-attachments/assets/ca2d96ed-b91d-4e2c-9504-5b2f7beb5ce3)

**Comment by igrabski** [comment]
Hi, I'm not sure if there are any packages that automatically do this computation, but you can extract the raw counts from a Seurat object by specifying `LayerData(object, assay='RNA', layer='counts')`, and then compute TPM from there.
