### ISSUE TITLE
PrepSCTIntegration Error in scale.data[anchor.features, ] : subscript out of limits

### ISSUE THREAD

**Issue by marika300925** [satijalab/seurat#9502]
Hello there!
I'm getting the error Error in scale.data[anchor.features, ] : subscript out of limits when running PrepSCTIntegration() function.

Could someone help me? The already existing issues on GITUP didn't fix my error

I'm working with 4 datasets, merged in the object "seurat_phase"  that i splitted before running the function into "splitObj"

#6. INTEGRATION
splitObj <- SplitObject(seurat_phase, split.by = "sample")
integ_features <- SelectIntegrationFeatures(object.list = splitObj, 
                                            nfeatures = 3000) 
split_seurat <- splitObj
for (i in 1:length(splitObj)) {
  split_seurat[[i]] <- SCTransform(splitObj[[i]], vst.flavor = "v2", variable.features.n= 10000)
}

save(split_seurat, file= "Invasive front/SCTrasmorm.result).RData")
save(spliObj, file= "Invasive front/spliObj.RData")

splitObj <- PrepSCTIntegration(object.list = split_seurat, 
                                   anchor.features = integ_features)

integ_anchors <- FindIntegrationAnchors(object.list = splitObj, 
                                        normalization.method = "SCT", 
                                       anchor.features = integ_features)
integratedObj <- IntegrateData(anchorset = integ_anchors, 
                                   normalization.method = "SCT")

**Comment by Mia1037** [comment]
I'm also getting this error when running SCTransform......

**Comment by mhkowalski** [comment]
Hello, 

I think that you should run this line after running `SCTransform()` on your object list.

``` R
integ_features <- SelectIntegrationFeatures(object.list = split_seurat, nfeatures = 3000)
```

Currently, you are selecting integration features based on the RNA assay, but those features may not necessarily be present in the `SCT` assay, hence why you're getting the indexing error.
