### ISSUE TITLE
how to let SCTransform  to use all gene to do scale data ?

### ISSUE THREAD

**Issue by lidd77** [satijalab/seurat#9504]
Hello,

     I am using SCTransform , this function only use 3000 genes to do scale data.

    I need to use all  genes ,  so how should I  do that ?
    I have checked SCTransform function parameters , but still not find suitable details .

    Expecting your reply !

Best

**Comment by samuel-marsh** [comment]
Hi,

See `return.only.var.genes` in documentation.

Best,
Sam

**Comment by lidd77** [comment]
> return.only.var.genes

Hello,  @samuel-marsh   ,  I have checked that doc ,   set return.only.var.genes = FALSE  ,.
but  if I  set   variable.features.n = 5000  , 5000 is more than the total gene number in my  seruat obj ,  so this also can return all genes ?

**Comment by samuel-marsh** [comment]
Yes that would work but you don’t want to set that parameter just based on how many genes you want returned in scale data because it is major factor in the analysis.
