### ISSUE TITLE
Number of cell in SCTramsform()

### ISSUE THREAD

**Issue by Chrisdoan9** [satijalab/seurat#9505]
Hi team,

I use a reference data set with around 160,000 cell, so may I know how many cells should I use in this case? Is 40,000 cells good enough? Thank you so much!

```
allen_reference <- SCTransform(allen_reference, ncells = 40000, verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>%
  RunUMAP(dims = 1:30)
```

**Comment by mccormickceci** [comment]
Hello! 
We typically run sctransform with a default of SCTransform(ncells=5000). I would say for a dataset of this size that should be a reasonable number of cells to run!
