### ISSUE TITLE
SCTransform assay size

### ISSUE THREAD

**Issue by raygozag** [satijalab/seurat#9506]
While running sctransform on a visium HD sample I obtain an SCT assay with a "scale.data" matrix of the same size than "counts" and yet counts is a dgCMatrix which is about 200mb, whereas the "scale.data" object is ~80 GB because it is an actual matrix with non-zero values almost everywhere. why is this matrix also not a dgcmatrix corresponding to counts?

Thanks

**Comment by samuel-marsh** [comment]
Hi,

`scale.data` is a dense matrix so will always be larger than counts matrix (Though 200 to 80GB seems like a lot; could change how many genes it's returning to scale data).

For dense matrix like this without 0 values a dgCMatrix is often actually larger in terms of object size than pure matrix.

```
pbmc <- pbmc3k.SeuratData::pbmc3k
pbmc <- UpdateSeuratObject(pbmc)
pbmc <- SCTransform(pbmc)

dense <- pbmc@assays$SCT$scale.data
sparse <- as.sparse(pbmc@assays$SCT$scale.data)

object.size(dense)
65188704 bytes
object.size(sparse)
97600616 bytes
```
