### ISSUE TITLE
Error in FindTransferAnchors

### ISSUE THREAD

**Issue by Feilijiang** [satijalab/seurat#951]
Hello,
I am trying to project a new dataset into the reference object, it reports errors "Performing PCA on the provided reference using 2000 features as input.Projecting PCA Error in data.frame(row.names = rownames(x = data)) : duplicate row.names: RP11-632C17--A." 
However, I don't have duplicate row.names in both reference and query dataset. I am wondering if the new dataset doesn't have the same dims as the reference to be the problem. Besides, which R package contains the %||% function? When I check the FindTransferAnchors function step by step, I can't run some steps.
Thank you very much for your help!

**Comment by Feilijiang** [comment]
I find out that it is the problem of feature names . In seurat2, the old seurat object is allowed to have underscores in feature names when the new version replaces it with dashes when "CreateAssayObject". Thus, the problem comes out when using old object projected to the new created reference object.

**Comment by Feilijiang** [comment]
Thank you very much for your reply. In fact, after I updated the old object, it still reported errors until I created a new object.

**Comment by AmandaKedaigle** [comment]
I am running into this same error. It would be helpful if UpdateSeuratObject fixed feature names that will be broken in v3.

Is there anyway to change feature names of a v3 (or v2) object, in order to do it myself? Thanks!

**Comment by beyondpie** [comment]
@andrewwbutler 
Is there any specific reason that not allowing the underscore in the names?
Thanks
