### ISSUE TITLE
CreateGeneActivityMatrix

### ISSUE THREAD

**Issue by zhangjl-work** [satijalab/seurat#9510]
Hi, does the CreateGeneActivityMatrix function, which calculates the gene activity matrix, have anything to do with the sequencing depth? 
For example, the same sample was sequenced in two data sets, both with about 5000 cells, in data 1, the median high-quality fragments per cell reached 20000, and in data 2, the median high-quality fragments per cell was 7000. 
Obviously, the sequencing depth of data 1 is higher, but the expression of some genes in the gene activity matrix calculated by this method shows an inverse trend, and the expression of some genes in data 1 is lower than that in data 2. Is this reasonable? I look forward to your reply.

**Comment by samuel-marsh** [comment]
Hi,

This function is no longer a Seurat function but rather part of Signac.  I would suggest posting to [Signac repo](https://github.com/stuart-lab/signac) for assistance with your question.

Best,
Sam
