### ISSUE TITLE
Using FindMarkers for "pseudo-bulk" analysis

### ISSUE THREAD

**Issue by haghani-sara** [satijalab/seurat#9517]
Hi, thank you for the wonderful package! I have scRNA-seq data for 2 samples (one WT and another a gene-KO sample). I've already followed the standard procedure for filtering, normalization, clustering, etc based on the seurat tutorial (https://satijalab.org/seurat/articles/pbmc3k_tutorial.html). From my understanding, FindallMarkers/FindMarkers is typically used to identify DEGs of cell clusters. I'd like to know if it be sensible for use FindMarkers to identify the DEGs between my two samples (KO vs WT). I call this a "pseudobulk" because I'll essentially be taking all cell types of KO to compare against all cell types of WT. I have tried this with the default wilcox.test, but not sure if it's a proper way of going about this statistically speaking. Would appreciate any guidance on this. Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi,

For some of the basics on pseudobulk DE you can see this Seurat vignette: https://satijalab.org/seurat/articles/de_vignette#perform-de-analysis-after-pseudobulking

You may also want to use other tools such as DESeq2, edgeR, etc directly as they can allow for more complex design formulas, filtering, or other steps.

Best,
Sam

**Comment by haghani-sara** [comment]
@samuel-marsh thank you so much!
