### ISSUE TITLE
Error in JackStraw with h5ad Input in Seurat v5: "Arguments of Different Sizes"

### ISSUE THREAD

**Issue by simang5c** [satijalab/seurat#9523]
### Description

I am using **Seurat v5** to analyze single-cell data and have encountered an issue with the `JackStraw` function when working with **h5ad files**. 

### Steps to Reproduce

1. Load data from an h5ad file into a Seurat object.
2. Perform PCA using the `RunPCA` function:

   ```r
   SeuratObj <- RunPCA(SeuratObj, features = VariableFeatures(object = SeuratObj))
   ```

3. Attempt to run the `JackStraw` function:

   ```r
   SeuratObj <- JackStraw(SeuratObj, dims = 20)
   ```

### Observed Behavior

The following error is thrown:

```
Error in order(c(col(x = x2)), runif(n = length(x = x2))): arguments of different sizes
```

### Additional Information

- The error seems to originate from **line 2338 of `dimensional_reduction.R`** in the Seurat package.
- Interestingly, this issue does not occur when loading data entirely into memory (as in Seurat v4 workflows) instead of using h5ad files.

### Question

- Will this be addressed in an upcoming version of Seurat?

Thank you for your attention to this matter! Please let me know if additional details or a reproducible example is needed.

**Comment by longmanz** [comment]
Hi, Currently JackSraw does not support on-disk objects so if you really want to use it, you may either load your data entirely into memory, or you can first sketch your data to get a smaller in-memory object to run this function. We may try to make it compatible with on-disk objects in the future but given the fact that JackStraw() relies on permutation of data, it might be very very slow for large objects. So it is probably not worth doing so. 

ElbowPlot() should be sufficient in most cases when deciding how many PCs are sufficient.
