### ISSUE TITLE
DotPlot

### ISSUE THREAD

**Issue by adRn-s** [satijalab/seurat#9524]
It would be nice to have an option to switch from base R `scale()` to min-max normalization instead. I'd rather have values between 0 and 1, instead of getting negative values on a given gene in clusters where the gene was really expressed, only below the average of all cells...

I'd be happy to open a PR if it would be considered. Though the change is rather silly to implement.

**Comment by igrabski** [comment]
Hi, thanks for the suggestion! We prefer the current implementation to maintain consistency with what's in the `scale.data` layer and with other visualizations using the scaled data, but I do understand your point and appreciate the suggestion!
