### ISSUE TITLE
Seurat analysis structure for CITE-SEQ

### ISSUE THREAD

**Issue by jkelrod97** [satijalab/seurat#9528]
Hello! I am new to single cell analysis and am working with a fairly complicated dataset. 

I have RNA and ADT counts tables for three patients at four different timepoints (T1, T2, T3, and T4), as well as for four different healthy controls. A total of sixteen RNA counts matrices and sixteen ADT counts matrices. I also have BCR/TCR results for each of the sixteen samples.

How would you recommend structuring my Seurat object(s) to analyze this data? I looked at the multimodal vignette and the integration vignette, but am having trouble applying it as the example data is much simpler than mine. I am interested in looking at changes in patients over time, as well as in comparing patients to controls at each stage.

I am thinking that I need to perform integration for the five different groups - control, patient T1, patient T2, patient T3, and patient T4. And then I will have an assay for RNA and an assay for ADT (not sure how to incorporate BCR/TCR), and a layer for each patient group. Is this reasonable?

Thanks to anyone who can help!

**Comment by AtSourav** [comment]
Hi @jkelrod97 ,

Thanks for your question! 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
