### ISSUE TITLE
Error: Could not find the following programs: fast_tsne

### ISSUE THREAD

**Issue by moruchen** [satijalab/seurat#9529]
hi 
i run [fast_tsne.R](https://github.com/KlugerLab/FIt-SNE/blob/master/fast_tsne.R) 
in R Server,then i use "seurat_object <- RunTSNE(seurat_object,reduction = "pca", dims = 1:20,tsne.method = "FIt-SNE")" ,but i get bug
"Error: Could not find the following programs: fast_tsne
In addition: Warning message:
In `[[.DimReduc`(args$object, cells, args$dims) :
  The following embeddings are not present: NA, NA, NA"
please give me some help!

**Comment by zskylarli** [comment]
Hi - glad you figured out the bug and thank you for sharing for your solution!
