### ISSUE TITLE
Error in cc.loadings[[1]][, cc.use] : subscript out of bounds

### ISSUE THREAD

**Issue by jmzvillarreal** [satijalab/seurat#953]
Hi, 
I am running a Multi CCA analysis on 4 datasets and tryng to align CCs for downstrean analysis I am getting this error when doing MetageneBicorPlot:
```R
MetageneBicorPlot(Uro_Multi_CCA, grouping.var = 'Uro', dims.eval = 1:50, display.progress = FALSE)
Rescaling group 1
Rescaling group 2
Rescaling group 3
Rescaling group 4
Error in cc.loadings[[1]][, cc.use] : subscript out of bounds
```
I have tried different numbers for dims.eval but I get the same error.
Can anybody tell me where is the problem ?
Thanks !
Jaime.

**Comment by satijalab** [comment]
It is difficult to debug this without having access to your data, but I would strongly suggest switching to the v3 alignment methodology, which has improved performance and should not be subject to this error

you can find out more at
https://satijalab.org/seurat/
