### ISSUE TITLE
Integrating multiple scRNAseq datasets without a reference (Seurat v3)

### ISSUE THREAD

**Issue by lauramaen** [satijalab/seurat#954]
Hi,

I would like to know if you recommend using Seurat v3 for integration of multiple scRNAseq datasets without a reference? I am planning to do a joint analysis on multiple scRNAseq datasets representing multiple time points (3 time points, 3 replicates per time point, 10x data, sequenced at the same time), and I am trying to find a “basic” tool for exploratory analysis. So, can I find corresponding “anchors” across my datasets without a known reference? Can the correction of expression values confound the further analysis in this case? Or do you recommend other tools for this kind of analysis, e.g. solely pseudotime tools?

Thanks.

**Comment by satijalab** [comment]
You may want to try performing a standard Seurat analysis without identifying anchors. If you see that cells are clustering by replicate instead of by cell type, you can ameliorate this by integrating replicates from each time point, one time point at a time, and then merging the results.
