### ISSUE TITLE
Installation issue Seurat

### ISSUE THREAD

**Issue by salvatoreNRIM** [satijalab/seurat#9546]
Hi, I am trying to install Seurat from R studio (version ‘2024.9.1.394’, and running on Mac), and I keep running in the same issue: 

`Installing package into ‘/opt/homebrew/lib/R/4.4/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘igraph’, ‘leiden’

Warning message in install.packages("Seurat"):
“installation of package ‘igraph’ had non-zero exit status”
Warning message in install.packages("Seurat"):
“installation of package ‘leiden’ had non-zero exit status”
Warning message in install.packages("Seurat"):
“installation of package ‘Seurat’ had non-zero exit status”`

I then tried to install igraph and Leiden separately, but I still have the "non-zero exit status".

**Comment by samuel-marsh** [comment]
Hi,

Can you please post full output of errors when installing leiden and igraph?

Best,
Sam

**Comment by salvatoreNRIM** [comment]
When I try to install igraph I get:
`ld: warning: could not create compact unwind for _igraphdgetv0_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdlaqrb_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdnaupd_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdnaitr_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdneigh_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdnconv_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdnapps_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdnaup2_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdngets_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdneupd_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsaitr_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsapps_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsaupd_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsaup2_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsconv_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsesrt_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdseupd_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsgets_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdsortc_: does not use standard frame
ld: warning: could not create compact unwind for _igraphdstqrb_: does not use standard frame
ld: warning: could not create compact unwind for ___emutls_get_address: does not use standard frame
ld: warning: could not create compact unwind for _allocate_tramp_ctrl: does not use standard frame
ld: warning: could not create compact unwind for ___gcc_nested_func_ptr_created: does not use standard frame
ld: warning: could not create compact unwind for ___gcc_nested_func_ptr_deleted: does not use standard frame
installing to /opt/homebrew/lib/R/4.4/site-library/00LOCK-igraph/00new/igraph/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MESSAGES failed, using "C" 
3: Setting LC_MONETARY failed, using "C" 
** help
*** installing help indices
*** copying figures
** building package indices
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MESSAGES failed, using "C" 
3: Setting LC_MONETARY failed, using "C" 
** installing vignettes
** testing if installed package can be loaded from temporary location
ERROR: loading failed
* removing ‘/opt/homebrew/lib/R/4.4/site-library/igraph’
R[write to console]: 

R[write to console]: 
R[write to console]: The downloaded source packages are in
	‘/private/var/folders/jd/8k7kg6v10sq4pnlc83zxy8wh0000gn/T/RtmpXS1MO3/downloaded_packages’
R[write to console]: 
R[write to console]: 

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: In install.packages("igraph", lib = "/opt/homebrew/lib/R/4.4/site-library") :
R[write to console]: 
 
R[write to console]:  installation of package ‘igraph’ had non-zero exit status
`

And for leiden:

`ERROR: loading failed
* removing ‘/opt/homebrew/lib/R/4.4/site-library/igraph’
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MESSAGES failed, using "C" 
3: Setting LC_MONETARY failed, using "C" 
ERROR: dependency ‘igraph’ is not available for package ‘leiden’
* removing ‘/opt/homebrew/lib/R/4.4/site-library/leiden’
R[write to console]: 

R[write to console]: 
R[write to console]: The downloaded source packages are in
	‘/private/var/folders/jd/8k7kg6v10sq4pnlc83zxy8wh0000gn/T/RtmpXS1MO3/downloaded_packages’
R[write to console]: 
R[write to console]: 

R[write to console]: In addition: 
R[write to console]: Warning messages:

R[write to console]: 1: 
R[write to console]: In install.packages("leiden", lib = "/opt/homebrew/lib/R/4.4/site-library") :
R[write to console]: 
 
R[write to console]:  installation of package ‘igraph’ had non-zero exit status

R[write to console]: 2: 
R[write to console]: In install.packages("leiden", lib = "/opt/homebrew/lib/R/4.4/site-library") :
R[write to console]: 
 
R[write to console]:  installation of package ‘leiden’ had non-zero exit status`

**Comment by samuel-marsh** [comment]
Hi,

So this is indicating an issue in the compilers that R uses for some packages.  I would reccomend trying a fresh install of R and the compilers (seems you're using homebrew).  If issues still persist then best I can suggest is the post in the repos for those packages and/or google the error messages and see if others have solution that might solve your issue.  If installation of Seurat continues to be issue once you get leiden and igraph installed please open new issue.

Best!
Sam
