### ISSUE TITLE
findconservedmarkers

### ISSUE THREAD

**Issue by jhong26** [satijalab/seurat#955]
The new v3.0.0.9000 of Seurat has an issue with FindConservedMarkers. FindIdent function has not been updated to reflect the new naming convention. Inside it uses `@ident` instead of `@active.ident`

**Comment by satijalab** [comment]
I agree that we need to re-implement this function in v3 - and will make sure we do so in advance of a formal release.

**Comment by andrewwbutler** [comment]
This should be working now in v3
