### ISSUE TITLE
totally intermingled clusters on tSNE

### ISSUE THREAD

**Issue by Rachael-rq** [satijalab/seurat#956]
Hi, 

I have several datasets and I performed the same procedure in plotting tSNE and FindClusters, but the result of one particular dataset seems absurd where the clusters on the tSNE plot all mixed together.
eg: 
![image](https://user-images.githubusercontent.com/12887308/48817249-7d626f80-ed80-11e8-90ca-fe9c1b236e8f.png)

what could be causing this ?

Thanks a lot!
Lyu

**Comment by Rachael-rq** [comment]
Thank you for replying.

I used 10 for both processes (clustering and tsne plot). I also tried to adjust the PCs, but that didn't help.

This only happens when I scale each sample individually and then combine the scale matrices. 
eg: #scaledatal <- list()
#for (lib in unique(my_seurat@meta.data$orig.ident))
##{
##  print("scaling for ")
#  print(lib)
#  libcell <- FastWhichCells(my_seurat, group.by='orig.ident', subset.value=lib)
#  libdata <- SubsetData(my_seurat, cells.use = libcell)
  #libdata <- CellCycleScoring(object = libdata, s.genes = cc.genes$s.genes, g2m.genes = cc.genes$g2m.genes, set.ident = TRUE)
#  libdata <- ScaleData(object = libdata, vars.to.regress = c('nUMI', 'nGene'),
#            display.progress = FALSE)
 # scaledatal[[lib]] <- as.matrix(libdata@scale.data)
#}
#
#names(scaledatal) <- NULL
#scaledata <- do.call('cbind',scaledatal)
#my_seurat@scale.data <- as.matrix(scaledata)

When I do VlnPlot of PCs for the identified clusters , it is like:

![image](https://user-images.githubusercontent.com/12887308/48894895-ce588d80-ee7e-11e8-9c14-8b06adf2e7a8.png)
![image](https://user-images.githubusercontent.com/12887308/48894916-da444f80-ee7e-11e8-8a58-3303ebbd637d.png)

It looks like the clustering wasn't based on PCs?

Thanks

**Comment by timoast** [comment]
When you add back the scale data you need to make sure the column order matches the order of cells in the object, since the way you constructed the scale data likely resulted in a different order:
```r
my_seurat@scale.data <- as.matrix(scaledata[, my_seurat@cell.names])
```
