### ISSUE TITLE
Error in readMM(file = matrix.loc) :    representation 'coodinate' not recognized.

### ISSUE THREAD

**Issue by Vincent8484** [satijalab/seurat#9569]
I want to use Read10X. But there is an error message as follows:
Error in readMM(file = matrix.loc) : 
  representation 'coodinate' not recognized
  
  Used this RScript
  Paren <-  Read10X( data.dir = "C:/Users/W10/Documents/Skin/Parental/")
   I used to use file.exists(..) and list.files(..) => the Result is TRUE
   
   How can I solve this issue?

**Comment by rharao** [comment]
Thanks for reporting. I am intrigued by the error message:
> Error in readMM(file = matrix.loc) :
> representation **'coodinate'** not recognized

The [Matrix Market format specification](https://math.nist.gov/MatrixMarket/formats.html#MMformat) holds that the first line of the file should be the magic number `%%MatrixMarket` followed by space-separated keywords, the second of which is either "array" or "**coordinate**". There appears to be, somehow, a spelling error in your counts matrix.

To confirm this, please show us the first line of the file: `readLines("C:/Users/W10/Documents/Skin/Parental/matrix.mtx", n = 1)` in R.

If the matrix has this spelling error, you could do one of two things:
1. Use a text editor to correct "coodinate" to "coordinate".
2. Consider the matrix file corrupted and download the data directory again from elsewhere.
   - If you do this, I suggest you check for the error again after download.
