### ISSUE TITLE
Integration with RNA velocity and loom

### ISSUE THREAD

**Issue by lambdamoses** [satijalab/seurat#957]
RNA velocity is gaining popularity recently. I have a colleague who mainly uses Python, and he said scanpy stores RNA velocity results in the same object as the matrix, dimension reduction, clustering, and etc., which he really likes. Now he wants my RNA velocity results from my analysis in R; I gave him my other analysis results written into a h5ad file from Seurat, but I can't write the RNA velocity results since Seurat doesn't convert that, and I can only store it on disk as RData or RDS. I like the interoperability of the loom branch of Seurat, but it would be nice if RNA velocity results are stored in the Seurat or loom object and can be written to h5ad along with other results. I just wish that R users and Python users can more easily share analysis results. So would it be possible for Seurat to have better integration with velocyto.R? Also, can you include the loom and h5ad features in the loom branch in version 3.0 release?

**Comment by satijalab** [comment]
Thanks for the feedback! Yes I agree that it would be great to have better integration with velocity, as we are also hugely supportive of this method. Given the current focus on upgrading existing functionality to 3.0 it may be difficult for us to get to this in the near future, any chance you'd be willing to help out with a PR?

**Comment by lambdamoses** [comment]
Yes, I can do a PR for RNA velocity integration.

**Comment by alextamburino** [comment]
Hi, I am primarily a Seurat / R user and looking to incorporate RNA velocity into my workflow. Can you please share an update on the integration efforts? Thanks, Alex

**Comment by chatterjee89** [comment]
> Hi, I am primarily a Seurat / R user and looking to incorporate RNA velocity into my workflow. Can you please share an update on the integration efforts? Thanks, Alex

I'm interested in this update as well.
Regards, Deep

**Comment by Dragonmasterx87** [comment]
Interested in this update! Been trying to figure this out, I think maybe running Velocyto, for emat/nmat info and then merging them into Seurat. 🤔

**Comment by jebard** [comment]
I posted a brief code snippet on how i've been doing this (granted it was for Seurat v2 objects, though a little modification and v3 isn't too far off).

https://github.com/velocyto-team/velocyto.R/issues/16#issuecomment-461067873

**Comment by andrewwbutler** [comment]
Closing this as we now have velocity support via the SeuratWrappers package. You can check out the vignette [here](https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/velocity.html).
