### ISSUE TITLE
RunUMAP facing numpy version error

### ISSUE THREAD

**Issue by justinesjw** [satijalab/seurat#958]
Dear Seurat Team,

I was trying to run my dataset using RunUMAP() function using the code below and faced a numpy versioning problem. 

However, after googling i found that numpy's newest version is 1.15.4 but it seems like RunUMAP() needs numpy version 1.6 and above.

Here are my code, sessionInfo(), and NumPY version in python.  
```R
mca <- RunUMAP(object=mca, reduction.use = "pca", dims.use = 1:20, min_dist = 0.75)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: Required version of NumPy not available: installation of Numpy >= 1.6 not found.
```
![image](https://user-images.githubusercontent.com/26448066/48841127-7d3b9180-edcb-11e8-90bb-3c1c03570eb9.png)
![image](https://user-images.githubusercontent.com/26448066/48841146-8c224400-edcb-11e8-93c0-5e54127bbcc9.png)
![image](https://user-images.githubusercontent.com/26448066/48841174-9e9c7d80-edcb-11e8-8c6f-88780085ad95.png)

Please advise me on where I may have overlooked. 

Thank you in advance!

**Comment by timoast** [comment]
In software versioning 1.15 > 1.6, so the version of numpy you have installed is fine. My guess is that reticulate, the R package that interfaces with python, is not accessing the python version where you have the latest numpy installed.

You can verify this by running:

```r
np <- reticulate::import("numpy")
print(np$version$full_version)
```

You can set the version of python to be used by reticulate by doing:
```r
reticulate::use_version("path/to/python")
```

You can find out where python is installed by running in a terminal:
```
which python
```

See [here](https://rstudio.github.io/reticulate/articles/versions.html) for more information about configuring the python version used by reticulate.

**Comment by justinesjw** [comment]
Hi! 

Thanks for the reply! 

I tried your way but still face the same problem. I checked the version of numpy that I am using, it's version 1.15.4

> packageVersion("reticulate")
[1] ‘1.10’

> py_discover_config()
python:         .../Miniconda3/python.exe
libpython:      .../Miniconda3/python37.dll
pythonhome:     ...\MINICO1
version:        3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Architecture:   64bit
numpy:         ...\MINICO1\lib\site-packages\numpy
numpy_version:  1.15.4
NOTE: Python version was forced by use_python function

> mca <- RunUMAP(object = mca, reduction.use = "pca", dims.use = 1:20, min_dist = 0.75)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: Required version of NumPy not available: installation of Numpy >= 1.6 not found.

Do you have any idea where else went wrong?

Thanks!

**Comment by itssomi** [comment]
I've had the same problem with you. I've just downgraded version of numpy from 1.15.4 to 1.15.1 and then problem was solved. I recommend you to try downgrading the version of numpy. Good luck!

**Comment by imoutsatsos** [comment]
Even after I downgraded my numpy version as suggested by @itssomi this did not work for me.
However, modifying the PATH environment variable as suggested in https://github.com/rstudio/reticulate/issues/367 worked! 

This seems to be an issue with 'reticulate'

**Comment by Lesdormis** [comment]
@imoutsatsos Yes, itssomi's method works for me too. Many thanks!
