### ISSUE TITLE
Integration of scRNA-seq Data: Can Target Cell Subpopulations Be Extracted First and Then Integrated?

### ISSUE THREAD

**Issue by kestlermai** [satijalab/seurat#9585]
I'm working on scRNA-seq data and am trying to understand the best approach for data integration, especially when the cell count reaches the million level？Is it necessary to start the integration process from the original counts matrix, or can I first extract specific cell subpopulations from each dataset and then merge the batches? What are the recommendations for these approaches, and could using pre-processed cell subpopulations affect the quality of the integrated results?

**Comment by samuel-marsh** [comment]
Hi @kestlermai,

Not member of dev team but hopefully can be helpful.  First, as fyi, I will transfer this issue to discussions where it is better suited to get feedback on this type of thing (vs. errors, bugs etc in Issues).

In my personal opinion yes this is totally fine as long as you can properly/accurately identify all cells of specific cell type prior to subsetting.  There is no need to analyze any cells that are irrelevant to your analysis goal/question (e.g., when you have hypothesis about specific cell type as it appears you do).  In fact integration as a whole should often be a follow on to analysis conducted with integration first.  You may either not need integration period or not need it for the specific biological question you are interested in.  Using any integrative analysis technique (Seurat, Harmony, LIGER, etc) when it is not required will likely on serve to obscure your data and potentially mask real biological differences.

Best,
Sam
