### ISSUE TITLE
Datasets integration

### ISSUE THREAD

**Issue by Felix-Simon** [satijalab/seurat#959]
Hi,

I am using Seurat v3 to integrate 10 libraries of 7,000 to 10,000 cells. After clustering, I hope to get between 100 to 200 clusters. I was planning to test 50, 100, 150 and 200 dimensions to use from the CCA with  FindIntegrationAnchors, and assess the resulting integrations with the “mixing” and the “local structure” metrics. I have some questions about this:

1) IntegrateData also needs me to specify a dimensionality, but this time it is a number of PCs used to assess the weighted distance between cells and anchors. Should I use the same dimensionality in both functions, as you did in your vignette, or should I also try to change the dimensionality used in IntegrateData independently from FindIntegrationAnchors? More generally, can it hurt to specify a higher dimension than needed (other than increasing computing ressources)?

2) MixingMetric seems to require to run first ScaleData and RunPCA on the integrated data. Does this mean that I should try different dimensionality with RunPCA each time I want to assess the result of an integration? Or would it be ok to choose one dimensionality, for instance 100, and use it to assess each integration of datasets?

3) LocalStruct is said in the help to return an “average over all groups”. However, to me it returns a list with, for each dataset before integration, a vector of numbers ranging from 0 to 1 (there is a number for each cell, so thousands of them). Should I take the average across all these vectors?

Best,
Félix

**Comment by satijalab** [comment]
1. We keep the dimensionality fixed for all steps in an integration analysis. 

2. For calculating metrics, we would recommend using the same dimensionality as in the integration step 

3. Using the mean as a summary statistic is fine (i.e. - yes)

**Comment by jon96as** [comment]
Hi all,

I've been using Seurat v3 to integrate 3 libraries of about 5,000 cells and it seems to be working really well! However, I am trying to assess the quality of integration and clustering by calculating some kind of metric (such as mixing metric or local structure metric) but I can't make them work...

I was wondering if you had any advice on what to do. Are there any vignettes or code available that would explain how to obtain this?
Thanks in advance,
Jon
