### ISSUE TITLE
Merge clusters

### ISSUE THREAD

**Issue by kathirij** [satijalab/seurat#96]
Hello,
   I am analyzing 10x dataset. I believe I have almost decided the correct resolution that correctly identifies unique populations in the my dataset (~3000 cells; 12 clusters; resolution 1.0). However, there are two sets of two clusters each that are similar to each other and I would like to merge them into single clusters. Decreasing resolution doesn't work because I loose some of the other interesting clusters.

I was hoping that there is a way to merge the clusters back instead of using lower resolution and subsetting data later on.

**Comment by amisharin** [comment]
Ok, I am not a member of Satija lab, but I had the same question. One approach is described in comments to pbmc33k dataset: https://www.dropbox.com/s/y6kwho066vugjrg/pbmc33k.R?dl=1 (or find the link on the "get started" page http://satijalab.org/seurat/get_started.html) via initial overclustering and then merging nodes of the cluster tree. 
Also, in the main R code: https://github.com/satijalab/seurat/blob/master/R/seurat.R#L2422 (V1.4):
"Rename one identity class to another
Can also be used to join identity classes together (for example, to merge clusters)."
I have not tried the later function, let me know if you get it to work.

**Comment by kathirij** [comment]
Thanks @amisharin 

The first approach you suggested seems pretty useful... I tried that and it worked in terms of merging clusters. Now, I have to play around with what biologically makes sense... Thanks!

**Comment by laijen000** [comment]
Hi! I am using Seurat v3 and after clustering and predicting likely cell identities, I want to merge some redundant clusters back together. Is there a way to do this in Seurat v3? The links above no longer seem to work. Thank you!

**Comment by shengqh** [comment]
> Hi! I am using Seurat v3 and after clustering and predicting likely cell identities, I want to merge some redundant clusters back together. Is there a way to do this in Seurat v3? The links above no longer seem to work. Thank you!

Just rename the cluster id to what you want. For example, if you want to merge cluster 3 and 5,  just rename the cluster 5 to 3.

```
obj$seurat_clusters[obj$seurat_clusters==5]=3
```
