### ISSUE TITLE
Error in FindClusters.Seurat

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat#960]
After upgrading to version 3 I get an error when trying to find clusters
Error in FindClusters.Seurat
Provided graph.name not present in Seurat object.

Could anybody help me with this?
Thanks

**Comment by ChristophH** [comment]
see #939

In 3.0, we separate clustering into two steps. First, we construct a
neighbor graph between single cells, and we next FindClusters (credit to
scanpy for separating these two steps).

To do the first step, we run the FindNeighbors function - as documented on
our 'cheat sheet' for Seurat v3
https://satijalab.org/seurat/essential_commands.html
<https://urldefense.proofpoint.com/v2/url?u=https-3A__satijalab.org_seurat_essential-5Fcommands.html&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=e2kPyDtZAzQoyPfLTjZ5kw&m=-GgkxVz_gdz_QIIqTHO5p3pB4lLhTciaZib98W9dGtk&s=qBpWahyC4FgjIoGDgY5aL4_KfuPj-_TCMU-3EKYr_oM&e=>
