### ISSUE TITLE
UMAP error - comparison only possible for atomic and list types

### ISSUE THREAD

**Issue by catsargent** [satijalab/seurat#961]
Hi,

I have got UMAP to work with the given pbmc example data. However, when I try to run it using my own analysis objects, I always get the following error:

Error in MySeuratObject < RunUMAP(MySeuratObject, reduction.use = "pca",  : 
  comparison (3) is possible only for atomic and list types

The only difference I can really see between my seurat object and the pbmc one is that the latter contains jackstraw data, whereas mine doesn't as I just use the PCElbowPlot for determining which PCs to use. However, if I then subsequently run jackstraw, I still get the same error, so I assume this doesn't have anything to do with it.

Would appreciate any insight into what might be causing the error.

Thanks!
Catherine

**Comment by satijalab** [comment]
The jackstraw does not affect UMAP results (we certainly run UMAP on datasets without JackStraw). Are you able to run UMAP on other datasets in the tutorials?  If so, the error likely originates separately in your object
