### ISSUE TITLE
stacked barplot for replicate metrics

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#962]
I have seen stacked barplots in several papers presenting single cell data.   Representation of replicate information on a per cluster basis seems to be advantageously presented in this fashion.   Here is some (non-Seurat) script for calling these stacked barplots.

![image](https://user-images.githubusercontent.com/33207886/48963474-eba55e80-ef47-11e8-950b-1a49fb9bb404.png)

```R
#basic plot of clusters by replicate
ggplot(object@meta.data, aes(x=res.1, fill=replicate)) + geom_bar()

#set the order of clusters in dataset w 30 clusters
factor(object@meta.data$res.1, levels=c(seq(0,30)))
object@meta.data$res.1 <- factor(object@meta.data$res.1, levels=c(seq(0,30)))
ggplot(object@meta.data, aes(x=res.1, fill=replicate)) + geom_bar()

#set custom order to dataset w 30 clusters
my_levels <- c(26,4,10,13,25,27,18,8,6,12,20,7,5,17,23,1,2,3,9,11,24,28,0,14,22,29,16,19,21,15,30)
factor(object@meta.data$res.1, levels= my_levels)
object@meta.data$res.1 <- factor(object@meta.data$res.1, levels= my_levels)
ggplot(object@meta.data, aes(x=res.1, fill=replicate)) + geom_bar()

#plot as proportion or percentage of cluster
ggplot(object@meta.data, aes(x=res.1, fill=replicate)) + geom_bar(position = "fill")
```

**Comment by satijalab** [comment]
Thanks for posting this here - it is a valuable example that we can point towards for similar types of questions.

If you think that this exact analysis would be useful for others to run, feel free to submit a PR (ClusterCompositionPlot, or similar), and we'll happily take a look

**Comment by dtm2451** [comment]
If I may, the dittoSeq package ([Bioconductor](https://bioconductor.org/packages/dittoSeq/), [Github](https://github.com/dtm2451/dittoSeq)) offers a function that creates these plots with a single line of code.

```
# Just a quick example with the built in Seurat data:
dittoBarPlot(
    object = pbmc_small,
    var = "RNA_snn_res.1",
    group.by = "groups")
```
![image](https://user-images.githubusercontent.com/38870347/88940780-0bbd1300-d23d-11ea-8526-0333fb119492.png)


dittoSeq offers a separate set of visualizations from Seurat's that handle both single-cell and bulk RNAseq data exploration. Many features overlap, many don't, but some additional features of dittoSeq's visualizations are color blindness-friendliness by default, and natively accepting data stored as Seurat-v2, Seurat-v3, or SingleCellExperiment objects.
