### ISSUE TITLE
integration of 3 or more groups 

### ISSUE THREAD

**Issue by KoichiHashikawa** [satijalab/seurat#963]
like to align 3 or more groups using CCA in Seurat v2.3, but do you have any tutorial for that?
More specifically, I like to do CCA, T-SNE, Clustering, finding conserved markers, finding DEGs between groups in each cluster.

**Comment by mschilli87** [comment]
@KoichiHashikawa: see https://github.com/satijalab/seurat/issues/207, https://github.com/satijalab/seurat/issues/239, https://github.com/satijalab/seurat/issues/601, and https://github.com/satijalab/seurat/issues/890. :wink:
