### ISSUE TITLE
Equivalent PrintCalcParams() in Seurat v3.0

### ISSUE THREAD

**Issue by llumdi** [satijalab/seurat#964]
What is the equivalent PrintCalcParams() function in the new Seurat version 3.0?

**Comment by andrewwbutler** [comment]
Hi,

The calculation parameters are now stored in the `commands` slot. You can see what's been run with `names(object@commands)` and print the results with the `Command` function (e.g. `Command(object = object, command = "NormalizeData.RNA")`).
