### ISSUE TITLE
Error in FindIntegrationAnchors

### ISSUE THREAD

**Issue by Felix-Simon** [satijalab/seurat#965]
Hi,

When using FindIntegrationAnchors  with a dimensionality of 100 it works:

<img width="718" alt="screen shot 2018-11-27 at 10 34 53" src="https://user-images.githubusercontent.com/45236949/49092479-23562400-f230-11e8-9f64-5f523d67ba05.png">

However when using a dimensionality of 150 I get an error:

<img width="776" alt="screen shot 2018-11-27 at 10 47 03" src="https://user-images.githubusercontent.com/45236949/49093341-e0954b80-f231-11e8-8347-7f9141abd75e.png">

<img width="703" alt="screen shot 2018-11-27 at 10 47 19" src="https://user-images.githubusercontent.com/45236949/49093351-e723c300-f231-11e8-8ab4-0eea071477aa.png">

Do you have any idea on how I could solve this problem?

Best,
Félix

**Comment by andrewwbutler** [comment]
Hi Felix,

Thanks bringing this up! This should be fixed as of 27cb4a7.

**Comment by Felix-Simon** [comment]
Hi,

Thank you very much!

Best,
Félix
