### ISSUE TITLE
Analyzing digital gene expression data (DGE) from drop-seq pipeline with Seurat.

### ISSUE THREAD

**Issue by hfberg** [satijalab/seurat#966]
I am using Seurat to cluster data that previously has been filtered, aligned and turned into DGE by the Drop-Seq alignment pipline from Drop-seq tools. This has created a file sample_DGE.txt.gz. I then want to cluster my data and do a QC analysis through calculating the percent mithocondrial genes. I am following the Seurat Clustering tutorial found here: https://satijalab.org/seurat/pbmc3k_tutorial.html In this tutorial they use the files barcodes.tsv, genes.tsv and matrix.mtx generated by 10x genomics as raw data, and read it with the command Read10X(). I have generated these three files from our DGE data inspired by this biostars page:  https://www.biostars.org/p/312933/#312954 It works fine, except that the row name title "GENE" is stored as a column name, saved into barcodes.tsv, which later in Seurat is a problem because seurat uses "GENE" as one of the cell barcodes when calculating the percent mitochondrial DNA per cell. Example below:

![enter image description here][1]

This of course, makes it impossible to use VlnPlot, generating the error: 
```R
> VlnPlot(object = pbmc, features.plot = c("nGene", "nUMI", "percent.mito"), nCol = 3)
 Error in if(all(data[,feature] == data[,feature][2])) { : missing value where TRUE/FALSE needed
```
Simple removing "GENE" manually from the barcodes.tsv file creates a error in dimensions at the Read10X step. 
```R
> pbmc.data <- Read10X(data.dir = "dir/to/barcode_matrix_and_gene_files")
 Error in dimnamesGets(x, value) : invalid dimnames given for "dgTMatrix" object
stop(gettextf("invalid dimnames given for %s object" dQuote(class(x))),  domail + NA)
dimnamesGets(x, value)
```
SO my question is: do anyone know a workaround to this problem? Or is there an equivalent to Read10X(), say ReadDGE() or ReadDropseq() that can be used directly on my DGE file?

  [1]: https://i.imgur.com/CRBwP3K.png

**Comment by andrewwbutler** [comment]
Hi,

You don't need to convert the DGE to the 10X format. I would recommend simply reading the DGE file you already have into R with something like `read.table` or `fread` and then providing the resulting matrix to `CreateSeuratObject`.

**Comment by hfberg** [comment]
Thank you! I just got the same tip from biostars! :) It was uncler for a first-timer like me what to do in the case of DGE data;) Thank you for taking the time to respond to my question.

Kind regards
Hanna

On 28 Nov 2018, at 22:17, Andrew Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

You don't need to convert the DGE to the 10X format. I would recommend simply reading the DGE file you already have into R with something like read.table or fread and then providing the resulting matrix to CreateSeuratObject.

**Comment by hepcat72** [comment]
I'm getting this error from the "Seurat Read10x" galaxy tool, where I don't have the opportunity to work with the code... so how do you solve this via changing the input file?
