### ISSUE TITLE
Where can i download any of the sample txt file for seurat analysis?

### ISSUE THREAD

**Issue by shaaaarpy** [satijalab/seurat#967]
All the tutorials either contain rds files or seurat objects..Can someone please provide a txt file. I need to understand the format so that i can create my own.
Thank you

**Comment by leonfodoulian** [comment]
Hi,

You can find details on the expression matrix at issue https://github.com/satijalab/seurat/issues/233#issuecomment-348030446.

Best,
Leon

**Comment by shaaaarpy** [comment]
![image](https://user-images.githubusercontent.com/23281566/49343520-d1c6f280-f690-11e8-8924-b3986cb66b70.png)
 My matrix is exaclty like your solution but still i am getting the same error.

**Comment by leonfodoulian** [comment]
This should fix your issue (as also explained in issue #233):

```R
raw_counts <- read.csv(file = paste0("/home/sharpy/Desktop/velocyto/","seurat_analysisa_2_cels.csv"),sep=",",row.names = 1, header = TRUE)
```

Best,
Leon

**Comment by shaaaarpy** [comment]
I can't use row.names=1 as the data has some repeated gene names. Is this possible though?

**Comment by leonfodoulian** [comment]
Gene names or IDs should be present as row names in your data, and not as an observation (in a column as their corresponding counts across cells). You will have either to collapse these rows by adding the gene counts for these genes if they correspond to the same gene, or maybe give them separate names by adding a suffix to their names. You can do that after reading your file in `R`, or immediately in Microsoft Excel or LibreOffice. 

Best,
Leon

**Comment by shaaaarpy** [comment]
Thanks a lot for your suggestion. I will implement and confirm.

Thank you
