### ISSUE TITLE
Set the X axis for FeaturePlot

### ISSUE THREAD

**Issue by lvila** [satijalab/seurat#968]
I am trying to use FeaturePlot to show the difference in a gene between a control and a mutant (in different plots). The problem is that the control X axis is from -50 to 50, and the mutant starts at -20. I would like to set the x axis value to make it comparable but xlim doesn't work. Is there a way to do this?

**Comment by ShanSabri** [comment]
Would you mind posting the output tSNE plot for each FeaturePlot? Are these two separate tSNE embeddings?

**Comment by lvila** [comment]
The data hasn't been published so I rather not share it but here is what the axes look like:
![control ki67](https://user-images.githubusercontent.com/45439341/49187773-34855a80-f32e-11e8-8070-a76c58779003.jpg)
![ki67 mut](https://user-images.githubusercontent.com/45439341/49187784-3e0ec280-f32e-11e8-93c6-b2b80209b579.jpg)

These are two separate tSNE plots featuring a gene. I am just showing the same gene on each one of them to compare them. Top is control and bottom is mutant. The x axis have different values that I haven't been able to change.

**Comment by ShanSabri** [comment]
But if they are two completely different embeddings then why would you want to extend out the x-axis? By default the full embedding is centered to the plot. Expanding the limits of the axis will not show additional data. To be clear, tSNE plots aren't easily interpretable in terms of the axes/units of the original, high-dimensional data. So I wouldn't try to interpret a tSNE plot quantitatively; t-SNE is just a visualization technique, nothing more.

**Comment by lvila** [comment]
Yes, but to show a control and a mutant and be comparable I would need to show that whatever population the control has at -50 is not in the mutant. The absence of that population is the reason why the mutant axis starts at -20. That's why I am trying to set the value of x and make it the same.

For example, I was able to do this with the TSNEPlot function:
TSNEPlot(ctrl.subset, do.return=TRUE) + xlim (c(-50, 50))
TSNEPlot(mut.subset, do.return=TRUE) + xlim (c(-50, 50))

**Comment by ShanSabri** [comment]
>  I would need to show that whatever population the control has at -50 is not in the mutant. 

tSNE is stochastic. If these are really two completely independent embeddings then there is no reason to assume that the same population found in both embeddings will lie in the same position. In fact, it is highly unlikely.

**Comment by lvila** [comment]
They are not completely independent. The original file is an aggregate file and I separated them with SubsetData. So the tSNE actually lines up.

**Comment by mojaveazure** [comment]
Have you tried [`coord_cartesian`](https://stackoverflow.com/questions/3606697/how-to-set-limits-for-axes-in-ggplot2-r-plots) instead of `xlim`? It's similar, but operates differently so I think it'll work better. Also try [`FeatureHeatmap`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/FeatureHeatmap), setting the `group.by` argument to the metadata column differentiating between your mutants and controls.

**Comment by lvila** [comment]
I looked at the source code for `FeaturePlot` and found that it doesn't actually return a `ggplot2` object directly; instead it [returns a _list_ of `ggplot2` objects](https://github.com/satijalab/seurat/blob/master/R/plotting.R#L1198). The following code works as expected:
```R
plist <- FeaturePlot(object = mut.subset,
            features.plot = c("gene1", "gene2","gene3"),
            cols.use = c("grey", "blue"), do.return = TRUE,
            reduction.use = "tsne")

plist[[1]] + xlim(c(-50,50))
```

**Comment by mjdapper** [comment]
I know v3 is quite new but I'm having a similar problem with keeping axes fixed when splitting out and none of the above solutions worked.  Any ideas?

**Comment by andrewwbutler** [comment]
Hi,

One way to achieve this in v3 is as follows:

```R
plots <- FeaturePlot(object = pbmc_small, features = rownames(pbmc_small)[1:6], combine = FALSE)
# replace arguments in xlim and ylim with the fixed limits you want
plots <- lapply(X = plots, FUN = function(p) p + xlim(c(0, 25)) + ylim(c(-25, 0)))
CombinePlots(plots = plots)
```

Alternative, we've found the [patchwork package](https://github.com/thomasp85/patchwork) to be quite useful for this sort of thing too, although it's not on CRAN yet.
```R
plots <- FeaturePlot(object = pbmc_small, features = rownames(pbmc_small)[1:6], combine = FALSE)
patchwork::wrap_plots(plots) * xlim(c(0, 50))
```
