### ISSUE TITLE
DotPlot colors used

### ISSUE THREAD

**Issue by smithsl** [satijalab/seurat#969]
Hi, 
Apologies if this has already been asked before, I looked but couldn't find an answer for my question.

Is it possible to colour the dots on a dotplot using the same colour scheme that is used for the heatmap.
i.e, `col.low = "#FF00FF",  col.mid = "#000000", col.high = "#FFFF00" `

I've tried the code below but it only takes the first 2 colours supplied.
```R 
dotplot <- DotPlot(
    object = object, genes.plot = markers_to_plot, plot.legend = TRUE,
    x.lab.rot=TRUE, do.return=T, cols.use=c("#FF00FF", "#FFFF00", "#FFFF00") 
)
```

Thanks very much,
Sam

**Comment by andrewwbutler** [comment]
Hi Sam,

If you return the `ggplot` object you can apply any color scale you want. For example:

```R
library(ggplot2)
DotPlot(
    object = object, genes.plot = markers_to_plot, plot.legend = TRUE,  
    x.lab.rot = TRUE, do.return = TRUE
) + scale_colour_gradient2(low = "#FF00FF", mid = "#000000", high = "#FFFF00")
```

**Comment by smithsl** [comment]
Thanks very much!
works perfectly
