### ISSUE TITLE
RunMultiCCA in Seurat 3

### ISSUE THREAD

**Issue by sinhaeti** [satijalab/seurat#971]
What is the updated version of RunMultiCCA for Seurat v3.0?

I have 14 different 10x datasets (from 3 different timepoints) that I am trying to compare.

**Comment by andrewwbutler** [comment]
Hi,

Please see our vignette on integrating data in Seurat v3.0 [here](https://satijalab.org/seurat/pancreas_integration_label_transfer.html).

**Comment by sinhaeti** [comment]
Thank you!
