### ISSUE TITLE
A bug in VlnPlot resulting in error in logic calculation

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#972]
Hello,

When I was making a Shiny app to facilitate exploratory graphing, I came across with a bug in `VlnPlot` function when `cells.use` argument is used. 

My goal is to graph genes of interest in a subset of cells. I have a combined Seurat object that is composed of 4 separate runs (let's call them `sample1`, `sample2`, `sample3`, `sample4` combined in this particular order).

In the `Seurat:::SingleVlnPlot` function the following line fails:

```R
# Seurat:::SingleVlnPlot
#...

if (all(data[, feature] == data[, feature][1])) {              ######## LOGIC FAILS HERE
    warning(paste0("All cells have the same value of ", 
      feature, "."))
  }
  else {
    data[, feature] <- data[, feature] + noise
  }

#...

```

I figured out the reason for this failure. In the parent `VlnPlot` function the following code introduces `NA`s to the already subsetted data frame (already subsetted due to `cells.use` argument passed to `FetchData` subfunction). This happens when the `ident.include` argument is set to `NULL`:

```R
# Seurat::VlnPlot
#...

if (is.null(x = ident.include)) {
    cells.to.include <- object@cell.names
  }
  else {
    cells.to.include <- WhichCells(object = object, ident = ident.include)   ##### NAs introduced
  }
#...

```

When I run the `VlnPlot` function by using the cells of the first sample (`sample1`), the function performs fine because the following code evaluates to `TRUE`/`FALSE` --(not `NA`)--. This is the case because `data[, feature][1]` is not `NA`.

```R
all(data[, feature] == data[, feature][1])  

```

However when I execute the `VlnPlot` function by using any other cell subset (excluding the first sample), due to `NA` introduction, the `data[, feature][1]` evaluates to `NA` resulting in the logic calculation to return `NA` as well.

Although I can't share the large Seurat object for reproducing the problem, the code below should still fail by using a sample dataset:

```R

# Combined Seurat object that contains multiple samples
combined <- readRDS("combined_seurat_object.rds")

################### This works ###################
cells <- WhichCells(combined, subset.name = "cond", accept.value = "sample1")
VlnPlot(combined, features.plot = "Cd3e", cells.use = cells, x.lab.rot = T, group.by = "ident")

################### This fails ###################
cells2 <- WhichCells(combined, subset.name = "cond", accept.value = "sample2")
VlnPlot(combined, features.plot = "Cd3e", cells.use = cells2, x.lab.rot = T, group.by = "ident")


```

As a suggestion, using a logical expression that evaluates the variance/st.dev in gene expression (`var(data[ , feature], na.rm=T) == 0`) might be better than testing for similarity by using the first cell in the dataset ( __data[, feature][1])__  )?

**Comment by mojaveazure** [comment]
Hi Atakan,

Sorry we never got back to you on this. Does this still happen in Seurat v3? The internal functions handling `VlnPlot`s now are [`ExIPlot`](ExIPlot) and [`SingleExIPlot`](https://github.com/satijalab/seurat/blob/master/R/visualization.R#L4026)

**Comment by FionaMoon** [comment]
Hi，
How to save this kind of problem? I also meet this problem.
```
> Score_name = 'nCount_RNA'
> P <- VlnPlot(data_single,features = Score_name)
Error in if (all(data[, feature] == data[, feature][1])) { : 
  missing value where TRUE/FALSE needed

> packageVersion('Seurat')
[1] ‘4.0.4’
```
Thank you inadvance.
