### ISSUE TITLE
ScaleData in version 3.0 can run under single core only.

### ISSUE THREAD

**Issue by cafeblue** [satijalab/seurat#973]
do.par and num.cores can be set as parameters for ScaleData, but they are not token by ScaleData, and it runs super slow for mine data. Multiple-cores works fine and very fast for me in version 2.

Are you going to enable multiple-cores for ScaleData in version 3?

Thanks!
wei

**Comment by mojaveazure** [comment]
Hi Wei,

As of commit 4595fad, Seurat v3 supports parallelization through the use of [futures](https://github.com/HenrikBengtsson/future). While we don't have documentation describing how to use futures ready, please see Henrik's [vignette](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html) for details on how to set up parallelization.
