### ISSUE TITLE
Further clustering of clusters obtained after 1st round of Seurat

### ISSUE THREAD

**Issue by nawazahid** [satijalab/seurat#974]
Hello Seurat community,

I used the subset function as suggested in many questions and in the tutorial "https://satijalab.org/seurat/interaction_vignette.html" to isolate the cell cluster of my interest. Subsequently, I used the normalize data, scale data and find variable genes followed by jackstraw to find out further subsets/sub-types. Eventually, when I ran tSNE, it just shows me the original clusters without making any further sub-clusters.

In this example, the first image is the tSNE of the entire dataset and the second image is the tSNE of the cluster 1 and cluster 6, I expected to see further clusters in the second image, How should I magnify further to see further sub-clusters in cluster 1 and 6 taken together.

Looking forward for some solution.
Thanks and regards

![rplot01](https://user-images.githubusercontent.com/45527657/49336140-3c4b4480-f637-11e8-983f-3684935298d8.jpeg)
![rplot](https://user-images.githubusercontent.com/45527657/49336143-3fdecb80-f637-11e8-90a8-8cb2b5373e65.jpeg)

**Comment by bwang258** [comment]
Hi @nawazahid ,

Not sure if it helps but did you change the value for **resolution** argument in the **FindCluster** function? This may give you more clusters in the original run. 

Besides, did you run **FindCluster** in your second run? Did you change the **identity** of the cells to the new **identity**? It seems that you are using the identity from the first run again in the second run. 

Hope it helps
