### ISSUE TITLE
Adding transparency to Featureplot overlay

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#975]
Hi,

I am using the Featureplot overlay function to plot two genes on the seurat tSNE plot. Is there a way that I can add transparency to the NA color so that the points do not mask the high cells?

Thanks,

Bibaswan

**Comment by satijalab** [comment]
This is a nice idea. 
I don't think we'll be able to look at this in the very near future, but if you're interested in trying it out yourself and submitting a PR ( you can use https://ggplot2.tidyverse.org/reference/geom_point.html for reference ) that would be wonderful
