### ISSUE TITLE
How to run tsne on multiple dataset?

### ISSUE THREAD

**Issue by snoopy-448** [satijalab/seurat#976]
Hi,
I have scRNA data of multiple cell lines and I want to run tsne on them. I've tried your RunMultiCCA function. It's great! It seems that it removes most of the batch effect. However, I want to also plot a TSNE figure on the initial data without batch effect removal. 
For example, I have 4 seurat object called line1, line2, line3 and line4, each for a specific cell line. I know I can merge the DGE matrix by myself and then run PCA, TSNE on the merged matrix. I want to know is there a more simple way to accomplish this using Seurat? Like RunMultiTSNE or something, to merge multiple object and run tsne in one step?
Thanks!
Yang

**Comment by bwang258** [comment]
Hi @snoopy-448,

**MergeSeurat** allows you to merge two Seurat object at a time. But be aware that there might be cells with the same name across the samples. You can rename the cell name with the sample name ahead of it. Check out the **add.cell.id** parameter. 

Hope it helps.

**Comment by snoopy-448** [comment]
Thanks!
