### ISSUE TITLE
Error in differential expression analysis

### ISSUE THREAD

**Issue by shaaaarpy** [satijalab/seurat#977]
> mydata_genes <- FindMarkers(mydata, ident.1 = "Nbl1", ident.2 = "Nbl2")
   |                                                  | 0 % ~calculating  
Error in model.frame.default(formula = countdata.test[x, ] ~ coldata[,  : 
  invalid type (list) for variable 'countdata.test[x, ]'

Can someone please explain this

**Comment by guangli0817** [comment]
I have the same issue, can anyone help with that? Thanks.

**Comment by kasumaz** [comment]
I have the same issue. Has anyone worked around this? I would love to know.
