### ISSUE TITLE
How to set gene names in seurat object?

### ISSUE THREAD

**Issue by shaaaarpy** [satijalab/seurat#978]
rownames(mydata)<-row_val
Error in `rownames<-`(`*tmp*`, value = c("Xkr4", "Gm37381", "Rp1", "Rp1",  : 
  attempt to set 'rownames' on an object with no dimensions

**Comment by bwang258** [comment]
Hi @shaaaarpy ,

I am not an expert with R but could you explain what `mydata` and `row_val` are in your workflow? 

When I need to get a gene list, I would usually do this:
`#Suppose my Seurat object name is seurat`
`gene_List <- rownames(seurat@data)`

If you look through the structure of your Seurat object, the row names of the data or raw.data should be all the genes. 

Hope it helps.

**Comment by mojaveazure** [comment]
Hi @shaaaarpy,

You cannot set the rownames of a Seurat object directly; you must alter the rownames of the `raw.data`, `data`, and `scale.data` slots directly, as well as the the rownames of any gene loadings for PCAs you may have calculated.
