### ISSUE TITLE
What is the rationale to choose a suitable number of hvg for CCA and subspace alignment?

### ISSUE THREAD

**Issue by riselinuh** [satijalab/seurat#980]

**Comment by satijalab** [comment]
The rationale is that the majority of genes in scRNA-seq are not markers of distinct cell states, and by performing an initial feature selection to focus on high variance genes, this can help dimensional reduction techniques like CCA to separate biological signal from noise.

We typically work with the top ~2,000 genes, ether for clustering or alignment, but typically do not see significant differences in altering this parameter. However, you can certainly adjust and explore how it affects your downstream results
