### ISSUE TITLE
Is it possible to figure out PC variance explained in Seurat?

### ISSUE THREAD

**Issue by kysbbubbu** [satijalab/seurat#982]
Hello 

I have simple question.

Is it possible to figure out PC variance explained for each PCs (ex. PC1, PC2, ...)in Seurat?

Or should i manually figure out ?

Thank you

**Comment by sansense** [comment]
You can easily get the sdev of the PCs from the SeratObject:

```
pca = SeuratObj@dr$pca
eigValues = (pca@sdev) ^2 ## 
varExplained = eigValues / sum(eigValues)
```

note that `sum(varExplained)` will be 1 (= Total variance)

**Comment by zeehio** [comment]
Sorry if this message sounds blunt, but this answer is wrong.

One way to show the error is to extract the first Principal Component `RunPCA(..., npcs=1)` and follow @sansense instructions. According to those instructions you would be extracting 100% of the variance (and you are not).

`sum(eigValues)` will only be the total variance of the data when `pca@sdev` includes all the components. If you extract the first 50 components in `RunPCA(..., npcs = 50)` then `sum(eigValues)` will contain only the variance captured by those first 50 components and not the total variance of the data.

**Comment by plijnzaad** [comment]
minor point: in Seurat3 the `pca@sdev` slot is called `stdev`

**Comment by VitorAguiar** [comment]
@zeehio What if you use only the top 2000 variable genes for PCA? Is it still appropriate to compute total variance on the full gene expression matrix?

**Comment by aandreas13** [comment]
@VitorAguiar It shouldn't matter, should it? The solution is using the 'scale.data' slot to compute the total variance. By default, scale.data is only scaling the variable genes anyway. If you are using the the 'counts' or 'data' slot, it will pose a problem indeed.

Apart from that, I realized that Seurat RunPCA computed the total variance for us already. It's in the seu_obj@reductions$pca@misc$total.variance and it agrees with the above answer.

**Comment by VitorAguiar** [comment]
Hi @aandreas13, I usually don't follow the default and I scale all genes. 

Thanks for pointing out that the total variance is included in the Seurat Object. I will take a look.

**Comment by aandreas13** [comment]
hi @VitorAguiar, sorry for not catching that earlier. I believe that the definition of % explained variance is based on the total variance of the data used for computing the PCA, so if you scale all genes, yet using only 2000 hvg for the PCA, then the max variance explainable by all PCs is the total variance of that 2000 genes. I am not sure how Seurat calculated the total variance for PCA, you might want to double check whether it's using the total variance of the hvg or the whole genes (if you scale all genes).

**Comment by VitorAguiar** [comment]
Right, `seu_obj@reductions$pca@misc$total.variance` corresponds to the total variance of the variable genes, not the variance in the entire data.
