### ISSUE TITLE
how to run RunCCA with 3>groups ?

### ISSUE THREAD

**Issue by KoichiHashikawa** [satijalab/seurat#984]
I tried to align 3> different groups. (this is not to merge 3> samples from the same group. I did not use MergeSeurat)
```R
Data.combined <- RunCCA(A, B, C, genes.use = genes.use, num.cc = 40) gave warning as 
Warning message in RunCCA(A, B, C, genes.use = genes.use, num.cc = 40):
"Both object2 and group set. Continuing with objects defining the groups"Scaling data matrix
```
Also it seems that RunCCA runs CCA wit the first 2 objects.

**Comment by lazappi** [comment]
@KoichiHashikawa If you have more than 2 datasets you want to integrate you need to use the `RunMultiCCA` function rather than `RunCCA`.

**Comment by TTTPOB** [comment]
> @KoichiHashikawa If you have more than 2 datasets you want to integrate you need to use the `RunMultiCCA` function rather than `RunCCA`.

But in Seurat 3 Pre-release, there is no RunMultiCCA function.

**Comment by KoichiHashikawa** [comment]
@lazappi 
Thanks so much for the advice.
That is exactly what I was looking for.
Also, do you have any thoughts on DEG analysis on 3> samples using FindMarkers?
I am not sure if it is unrelevant to compare the two samples of interest or I need to compare one group wit the rest of groups.
@TTTPOB 
Good to know, thanks!
I hope they will have alternative functions for that.

**Comment by KoichiHashikawa** [comment]
RunMultiCCA ran with 3 samples, but unlike the case of 2 sample CCA, the cells do not align well at all in the tSNE space though if I take any 2 samples out of the 3, those 2 aligned very well in every clusters.

Do you have any issues like this?

**Comment by KoichiHashikawa** [comment]
@andrewwbutler 
thanks so much for the advice. I will follow the demo to see how it goes.

Does Seurat v3 has any mathematical/statistical method to evaluate how well the code aligns objects?

thanks!

**Comment by satijalab** [comment]
Please see the preprint https://www.biorxiv.org/content/early/2018/11/02/460147 for information on benchmarking metrics and results
