### ISSUE TITLE
load mixed genome

### ISSUE THREAD

**Issue by rhart604** [satijalab/seurat#986]
Trying to load a sample with mixed cells from human and mouse.  The Read10X() function reports "Barcode file missing".  The files in the "outs/filtered_feature_bc_matrix" directory are: barcodes.tsv.gz, features.tsv.gz, and matrix.mtx.gz.  I'm using cellranger-3.0.0 to create the files.

If I gunzip the files, I get an error "Gene name file missing."

If I rename features.tsv to genes.tsv the data load.

Is there a way to specify features instead of genes?

**Comment by andrewwbutler** [comment]
Hi,

Only the latest Seurat version (v3.0) provides native support for reading Cell Ranger 3.0 files through the `Read10X` function. You can find more information about this pre-release [here](https://satijalab.org/seurat/). 

Alternatively, if you only have RNA-seq data and renaming that file returned a matrix where the gene/cell names are associated with the matrix correctly, that seems reasonable if you want to continue using Seurat 2.X
