### ISSUE TITLE
Will it cause bias when I add known marker genes in the process of RunCCA?

### ISSUE THREAD

**Issue by Pang-Junling** [satijalab/seurat#987]
Hi,
    In this process of RunCCA, if I have some gene markers of several cell types, should I also put them in the model (like following)?  Will it cause bias in the results? The results differ in some extent with several small clusters  changes. I need your suggestions.
```R
g.1 <- head(rownames(ctrl@hvg.info), 1000)
g.2 <- head(rownames(stim@hvg.info), 1000)
known_marker <- c("marker1","marker2"......"marker100")
genes.use <- unique(c(g.1, g.2, known_marker))
genes.use <- intersect(genes.use, rownames(ctrl@scale.data))
genes.use <- intersect(genes.use, rownames(stim@scale.data))
combined <- RunCCA(ctrl, stim, genes.use=genes.use, num.cc=20, add.cell.id1 = "ctrl", add.cell.id2 = "stim")
```

**Comment by satijalab** [comment]
Running on a provided subset of genes does by definition introduce supervision into the analysis, and in particular can limit the ability to discover new cell states that are defined by distinct markers. In general, we do not recommend this.
