### ISSUE TITLE
> 100 samples ident set to project name

### ISSUE THREAD

**Issue by raqsilva** [satijalab/seurat#988]
Hi,

I wanted to know if there is any reason why when the number of samples is bigger than 100, all idents are set to the project name. Furthermore, if there is a way to skip this with an argument instead of changing manually the function.

https://github.com/satijalab/seurat/blob/37a3750f599fc4c0e1226aced130441a8b250077/R/preprocessing.R#L104-L108

Thank you,
Raquel

**Comment by mojaveazure** [comment]
Hi Raquel,

By default, we set the identity classes to be the cell names for fewer than 100 cells, and to the project name for greater than 100 cells to reduce the size of the factor. There is no way to skip this, but you can manually set the identity classes after you create a Seurat object by overriding the `object@ident` slot.
