### ISSUE TITLE
Error in FindClusters

### ISSUE THREAD

**Issue by yanwu2014** [satijalab/seurat#99]
I'm getting an error in FindClusters with the "bimod" test.

```
Error in order(to.return$p_val, -to.return$avg_diff) :
  argument 1 is not a vector
Calls: FindAllMarkers -> FindMarkers -> [ -> [.data.frame -> order
Execution halted
```
Any ideas on what the issue could be?

**Comment by andrewwbutler** [comment]
This looks like a `FindMarkers` rather than a `FindClusters` command. Can you provide the code you ran that produced the error?

**Comment by yanwu2014** [comment]
Yes sorry about that typo it's an error in FindMarkers

Code snippet:
`cluster.markers <- FindAllMarkers(se.obj, thresh.use = 0.25, test.use = "bimod", only.pos = T, print.bar = T)`

Full error:
`Error in order(to.return$p_val, -to.return$avg_diff) : 
  argument 1 is not a vector
Calls: FindAllMarkers -> FindMarkers -> [ -> [.data.frame -> order
In addition: Warning messages:
1: In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
2: In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
3: In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
Execution [halted]`

The error seems to go away when I decrease the fold change threshold to 0.1

**Comment by satijalab** [comment]
This error occurs in some cases when there are no genes that pass the differential expression tests. We'll fix in an upcoming release.
