### ISSUE TITLE
DoHeatmap on Seurat3

### ISSUE THREAD

**Issue by sunyan4BGI** [satijalab/seurat#994]
Hi, developer !
I have a question on DoHeatmap of Seurat3
The heatmap I got from DoHeatmap looks fuzzy.
But it is good on DoHeatmap of Seurat2.
Do you have any ideas?
![image](https://user-images.githubusercontent.com/39484237/49630467-413e3880-fa29-11e8-83bd-8c3728bded55.png)

**Comment by sunyan4BGI** [comment]
I think I found the problem, it is caused by "geom_raster" in function "SingleRasterMap"
In Seurat2, you used "geom_tile"

**Comment by satijalab** [comment]
Thanks for your question - yes we did switch in v2->v3, as this significantly increases plotting time.

However, this only should be present when you try to view saved PDFs in a select few applications (it should not be a problem in Rstudio, R graphics, or Adobe Acrobat for example).
